### ISSUE TITLE
Question: How to drain a part of buffer data with a certain offset？

### ISSUE THREAD

**Issue by popozy** [envoyproxy/envoy#10004]
*Description*:
When I'm trying to add jaeger-span in dubbo-proxy filter in tracing,  a question confused me when trying to put new span context into dubbo attachment block for propagation -- in order to overwrite dubbo attachment block, I think I need to do the following 3 steps:
>+ Drain data in buffer from a certain offset (where attachment begins)
>+ Serialize attachment (containing new span context)
>+ Rewrite raw data to buffer from the offset where aatachment begins

But the question is, I cannot find a method in buffer.h to implement drain data from a certain offset not begining. Does it is reasonable  to implement a function like buffer.drain(void* data, size_t size, size_t offset);
What's more, it seems that buffer fragment operation is not acceptable?https://github.com/envoyproxy/envoy/issues/5754

**Comment by zuercher** [comment]
I think you can implement this using Buffer::move. Generally, move the buffer prefix to a new buffer, append your attachments, append the remainder of the original buffer. You can move the new buffer's data back to the original Buffer instance as well. You can minimize copying of data if you can arrange to track multiple buffers.

**Comment by popozy** [comment]
> I think you can implement this using Buffer::move. Generally, move the buffer prefix to a new buffer, append your attachments, append the remainder of the original buffer. You can move the new buffer's data back to the original Buffer instance as well. You can minimize copying of data if you can arrange to track multiple buffers.

Ops! Got it--just new a buffer instance, after which construct it with buffer prefix , new attachment, postfix part with https://github.com/envoyproxy/envoy/blob/74df8b3f1f36d60563b2dc0e9200ed65d1e43d31/include/envoy/buffer/buffer.h#L157, then I'd like to get the target buffer instance! 
I will have a try immediately! Thanks a lot!

**Comment by popozy** [comment]
make it by buffer.move and drain~~
And in this dubbo buffer overwriting case, a detail, which can not be ignored,  is that in dubbo serialize protocol(hessian-2), attachment block may begin with byte 0x48(Uppercase "H" in "HashMap") or 0x4d(Uppercase "M" in "Map") and end with 0x5a(Uppercase "Z").
*Ref: [UTF-8 encoding table and Unicode characters](https://www.utf8-chartable.de/)*
