### ISSUE TITLE
CacheFilter: Handle "Pragma: no-cache" request header

### ISSUE THREAD

**Issue by toddmgreer** [envoyproxy/envoy#10021]
If a request lacks a Cache-Control header, but has a "Pragma: no-cache" header, treat it as if it had "Cache-Control: no-cache".

Required by [RFC7234§5.4](https://httpwg.org/specs/rfc7234.html#header.pragma)

**Comment by toddmgreer** [comment]
Currently, we don't cache responses without cache-control headers, but when we start caching responses with cacheable-be-default status codes and no cache-control headers, we need to make sure "pragma: no-cache" is treated the same as "cache-control: no-cache". Note that any other "pragma" headers should be ignored.

**Comment by yosrym93** [comment]
Needs to be implemented after #9833 , as currently cache-control request headers are not checked.
