### ISSUE TITLE
Transfer-Encoding value is case-insensitive by RFC.

### ISSUE THREAD

**Issue by veshij** [envoyproxy/envoy#10041]
Envoy [rejects](https://github.com/envoyproxy/envoy/blob/acdc6c7658638891253b2a49e74535de11984a72/source/common/http/http1/codec_impl.cc#L582-L592) requests having "Transfer-Encoding: **C**hunked" with `unsupported transfer encoding` error.

Per [RFC7230: Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing](https://tools.ietf.org/html/rfc7230#section-4) transfer-coding names are case-insensitive:
>All transfer-coding names are case-insensitive and ought to be
   registered within the HTTP Transfer Coding registry, as defined in
   Section 8.4.  They are used in the TE (Section 4.3) and
   Transfer-Encoding (Section 3.3.1) header 

*Expected behavior*: all transfer-encoding comparisons are case-insensitive.
 
*Logs*:
```
D0213 02:23:06.031513 33976 http [external/envoy/source/common/http/conn_manager_impl.cc:278] [C516843051] dispatch error: http/1.1 protocol error: unsupported transfer encoding
```

**Comment by veshij** [comment]
I can try to take a look how to fix that.

**Comment by mattklein123** [comment]
Trivial fix here: https://github.com/envoyproxy/envoy/blob/be1051947a19010a4f5870d0ad561ef5979be9fe/source/common/http/http1/codec_impl.cc#L582-L592

**Comment by veshij** [comment]
@mattklein123 should we normalize transfer-encoding while parsing headers - otherwise it's possible to hit the same issue in other codepaths?

**Comment by mattklein123** [comment]
We haven't normalized header values so far to my knowledge. I'm not sure if it's worth it but I could go either way. @alyssawilk any thoughts?
