### ISSUE TITLE
allow new tcmalloc to be used as an option

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#10053]
https://abseil.io/blog/20200212-tcmalloc

Currently only supported on linux/x86_64 so we could add as a build option or potentially just rip out the old one and everyone else would get standard malloc (sub-optimal given the rise of ARM).

**Comment by jmarantz** [comment]
Is there a TL;DR on what's better about this version of tcmalloc compared to the one Envoy already uses?

**Comment by mattklein123** [comment]
@ahedberg posted some info here: https://envoyproxy.slack.com/archives/C78HA81DH/p1581621926211100

**Comment by lizan** [comment]
From its Quickstart doc seems it requires C++17, so we have to do the upgrade first.

**Comment by mattklein123** [comment]
Now that we are on C++17 I think we can go ahead and add this as a build option? It would be nice to use this on x86_64 builds even if we can't use it on ARM64 builds yet.

cc @ahedberg @lizan @dio @stedsome

**Comment by lizan** [comment]
@mattklein123 there's certain difference between gperftools / tcmalloc noted here: https://github.com/google/tcmalloc/blob/master/docs/gperftools.md#differences . Likely it means we won't have profiler with tcmalloc

**Comment by mattklein123** [comment]
IMO we can drop the profiler support. I don't know why anyone would ever use it given how much better perf works.

**Comment by ckennelly** [comment]
TCMalloc now has an ARM64 implementation for its per-CPU caches, as of google/tcmalloc@4c6e2e3bf96878bf2c87055ae14c87df9531200f

**Comment by rojkov** [comment]
Yeap, I'll take care.

**Comment by rojkov** [comment]
@ckennelly we build Envoy with clang v10.0.0 still, but the current RSEQ implementation checks for `__AARCH64_CMODEL_SMALL__` introduced in v11.0.0. As a result arm64 builds fail.

I've submitted https://github.com/google/tcmalloc/pull/58
