### ISSUE TITLE
DNS IPv6 fallback support follow-up

### ISSUE THREAD

**Issue by hennna** [envoyproxy/envoy#1005]
In #978 , we discussed the changes necessary to begin DNS IPv6 support which are reflected #1002 . For the fallback "auto" policy, we decided to query ares_gethostbyname twice. Once with parameter AF_INET6 and then with parameter AF_INET if the original query failed. 

An alternative option would be to use the AF_UNSPEC option provided in the c-ares library. This should ideally implement the "auto" policy desired. However, it is currently lacking in two parts:

1.Does not support returning multiple types of addresses

2. Has unpredictable behavior. For example, returning the IPv4 localhost address even when IPv6 is supported.

If either or both of these issues are supported by c-ares AF_UNSPEC, we should revisit this issue.

**Comment by hennna** [comment]
Another follow-up issue: adding support for DNS caching

**Comment by htuch** [comment]
I think another bigger issue is that you want to have the caller receive both IPv6/IPv4 addresses if available and be in a position to do its own fallback to IPv4 if the IPv6 address isn't routable. This is a change that would impact multiple call sites today, but something we should consider doing in the future to avoid surprising behavior.
