### ISSUE TITLE
http_service: server_uri: uri is always overwritten by the request URI path

### ISSUE THREAD

**Issue by lazy-always** [envoyproxy/envoy#10061]
Issue/Bug Template

Title: http_service: server_uri: uri is always overwritten by the request path

Description:

ext_authz config says uri parameter is mandatory parameter. But envoy always takes the URI path from the request and post to the cluster. Whatever we give any value in this parameter doesn't make any difference. 

Repro steps:

Config set as below. Running two servers on 8080 and 8082. One with endpoint /auth and second with endpoint /data. Post to localhost:10000/data. Envoy will try to connect to  ext_authz server with path /data. 
If we set anything let's say 
                   http_service:
                        server_uri:
                          uri: http://anything:8080/something/anything

Still, it wont take this path. Config is set as below

`static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: tenants
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: tenant1
                http_filters:
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                      http_service:
                        server_uri:
                          uri: http://host.docker.internal:8080/auth
                          #uri: /auth
                          ##uri: /simple-servlet/MyServlet
                          cluster: authc
                          # timeout: 0.25s
                          timeout: 3s
                        ##path_prefix: /simple-servlet
                        authorization_request:
                          allowed_headers:
                            patterns:
                              prefix: "x-b3"
                      ## This may not be required when we do the Authentication
                      #with_request_body:
                      #max_request_bytes: 1024
                      #allow_partial_message: false
                      #clear_route_cache: true
                  - name: envoy.router
                    typed_config: {}
  clusters:
    - name: tenant1
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      ##http2_protocol_options: {}
      load_assignment:
        cluster_name: tenant1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 8082
    - name: authc
      # This timeout controls the initial TCP handshake timeout - not the timeout for the
      # entire request.
      connect_timeout: 0.25s
      type: strict_dns
      ##http2_protocol_options: {}
      load_assignment:
        cluster_name: authc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 8080

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001
`

**Comment by lazy-always** [comment]
Similar issue was reported before @https://github.com/envoyproxy/envoy/issues/5357

**Comment by mattklein123** [comment]
I reopened the other issue, let's use that one to track.
