### ISSUE TITLE
Metrics - dog_statsd sink reporting counters as delta

### ISSUE THREAD

**Issue by chaosbox** [envoyproxy/envoy#10066]
*Title*: *Metrics - dog_statsd sink reporting counters as delta*

*Problem Description:*
* We use the dog_statsd sink for our envoy metrics, and we noticed that datadog-agent's statsd was receiving delta of the counter values instead of a cummulative counter. Also, in the statsd payload we mark the metric as a counter "|c" which confuses the datadog-agent. Datadog agent's dogstatsd stores it as a RATE type in Datadog, each value is a time-normalized delta of the metric’s value over the StatsD flush period.

The gauge metrics are working fine and metrics in the "/stats" page seems to be inline with the documentation, counters showing cummulative values.

*Envoy version:* 
v1.13.0 -> "bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7/1.13.0/clean-getenvoy-4bd7718-envoy/RELEASE/BoringSSL"

*Config:*
```
stats_sinks: [
  {
    name: "envoy.dog_statsd",
    hidden_envoy_deprecated_config: {
      prefix: "envoy",
      address: {
        socket_address: {
          address: "127.0.0.1",
          port_value: 8125
        }
      }
    }
  }
]
```

*Observation:*
Snippet of the statsd payload,

```
U 2020/02/13 15:34:08.101190 127.0.0.1:60944 -> 127.0.0.1:8125 #2945574
envoy.listener.0.0.0.0_9443.http.ingress_http.downstream_rq_2xx:363|c

U 2020/02/13 15:34:13.102812 127.0.0.1:60944 -> 127.0.0.1:8125 #2961769
envoy.listener.0.0.0.0_9443.http.ingress_http.downstream_rq_2xx:362|c

U 2020/02/13 15:34:18.102845 127.0.0.1:60944 -> 127.0.0.1:8125 #2977943
envoy.listener.0.0.0.0_9443.http.ingress_http.downstream_rq_2xx:364|c
```
statsd metric-type - `|c`  - counter

Based on the documentation `listener.0.0.0.0_9443.http.ingress_http.downstream_rq_2xx` is a counter, but we are emitting delta. Pondered the source and looks like stat_sinks extension, both udp and tcp sinks are emitting delta instead of actual values, but marking as a "counter". 

https://github.com/envoyproxy/envoy/blob/58c71def4bcbf9947c4c9dd8dd81e924c63fd995/source/extensions/stat_sinks/common/statsd/statsd.cc#L50-L56

**Comment by chaosbox** [comment]
We are currently dependant on this as we have all of our other metrics exported to datadog. We cannot move to `/stat` pull based exporter since we rely on tagging using `stats_tags`. 


cc: @mattklein123  @mergeconflict @zuercher

**Comment by mattklein123** [comment]
The statsd format uses deltas. I don't know anything about Datadog so I would recommend following up with them.
