### ISSUE TITLE
feature - AMQP Codec and Filter

### ISSUE THREAD

**Issue by aviramha** [envoyproxy/envoy#10078]
*Title*: AMQP Codec

*Description*:
AMQP is used for RabbitMQ and other message brokers.
The codec will be used to add a protocol filter to route messages to upstreams based on the (draft) conditions:

-  Queue name
- Probably other people have more use cases :)

Besides the load-balancing/filters, metrics will be collected.

I'm thinking on implementing it - should I get approval from one of the maintainers before starting to work on the PR?

**Comment by mattklein123** [comment]
> I'm thinking on implementing it - should I get approval from one of the maintainers before starting to work on the PR?

In general we request that one of the existing maintainers will "sponsor" your work on this type of filter and handle reviews, etc. This is until we potentially start splitting out unsponsored extensions into a separate repo (proposal for this on my plate). cc @envoyproxy/maintainers for sponsorship request.

**Comment by aviramha** [comment]
@envoyproxy/maintainers

**Comment by aviramha** [comment]
> > I'm thinking on implementing it - should I get approval from one of the maintainers before starting to work on the PR?
> 
> In general we request that one of the existing maintainers will "sponsor" your work on this type of filter and handle reviews, etc. This is until we potentially start splitting out unsponsored extensions into a separate repo (proposal for this on my plate). cc @envoyproxy/maintainers for sponsorship request.

Thanks for the response!! 
The group seems to be private, as clicking on the link leads to 404 and I can't seem to tag it.

**Comment by aviramha** [comment]
@mattklein123 
Should I considered them cc'd as you did, or not? (I can't seem to cc the group).

**Comment by mattklein123** [comment]
@aviramha yes they have been mentioned. FYI it's still on my plate to do an extension repo proposal. Another option would be to think about intercepting WASM support and doing this as a WASM module.
