### ISSUE TITLE
Lowercasing performance / clean-up

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#10088]
I was taking a look at lower-casing after the PR https://github.com/envoyproxy/envoy/pull/9952/files. I had a performance related change I wanted to throw out there for discussion before I made a PR, as well as some cleanup. 

1. `LowerCaseString` in headers currently uses a `lower()` method that calls `std::transform(string_.begin(), string_.end(), string_.begin(), tolower);`. This is *significantly* slower than using `absl::ascii_tolower` which is a character table lookup similar to `ToLowerTable`. Here's some performance benchmarks:
```
BM_TransformLower/0                   0.812 ns        0.812 ns    873228710
BM_TransformLower/1                    2.65 ns         2.65 ns    261764834
BM_TransformLower/10                   25.0 ns         25.0 ns     27930491
BM_TransformLower/50                   87.3 ns         87.3 ns      8022176
BM_TransformAsciiToLower/0            0.689 ns        0.689 ns   1000000000
BM_TransformAsciiToLower/1             1.83 ns         1.83 ns    383264264
BM_TransformAsciiToLower/10            7.02 ns         7.02 ns     99719850
BM_TransformAsciiToLower/50            23.6 ns         23.6 ns     29561697
```
where the benchmark args are the size of the string. I think this would be a good performance swap out to use in `LowerCaseString`.

2. If `absl::ascii_tolower` is already doing the character table lookup, do we need a `ToLowerTable` at all? `absl` gives us `absl::AsciiStrToLower` method. Here are some benchmarks for different tests
```
BM_AsciiStrToLower                                  19.4 ns         19.4 ns     35560884
BM_AsciiToLowerTransform                             125 ns          125 ns      5617309
BM_StringUtilToLower                                 127 ns          127 ns      5511716
BM_StringUtilLower                                  21.4 ns         21.4 ns     32538778
BM_LowerTableLower                                  20.5 ns         20.5 ns     33901722
```
where the options respectively are:
* use `absl::AsciiStrToLower(text)` to create a lowercased string copy.
* make a string copy and apply `std::transform(old, old, new, absl::ascii_tolower)` where the transform reads from the old string inserts in to new string
* Use `StringUtil::toLower`, that effectively does the previous (copies and transforms).
* Make a string copy and apply `std::transform(new, new, new, absl::ascii_tolower)` where the transform reads and inserts in to the new string
* Use the lowercase table.

It seems the most fast to use a character table lookup, but that we don't need to have our own library in `ToLowerTable` for it. I have a PR out that removes the lowercase table, does this seem worthwhile?

**Comment by asraa** [comment]
@adisuissa

**Comment by mattklein123** [comment]
@asraa one small point is that `LowerCaseString` is generally not used in a any perf critical paths that I know of. With that said, I agree we should just swap everything out for the absl utility so this sounds great!

**Comment by adisuissa** [comment]
Looking at `absl::AsciiStrToLower(text)` it seems that there are 2 versions, one works in-place, and the other that copies a string_view, and operates on that. From the perf test, I assume that `BM_AsciiStrToLower` uses the in-place version.
In any case, I would suggest using this over std::transform, wherever it's possible.
