### ISSUE TITLE
JWT Payload in custom header / metadata

### ISSUE THREAD

**Issue by method350** [envoyproxy/envoy#10086]
Good day guys,
i got a question regarding the envoy JWT authentication filter (_envoy.filters.http.jwt_authn_) while using the envoyproxy/envoy:v1.13.0 docker image.

According to the documentation this filter should be able to write the JWT payload to custom header or dynamic metadata.
[DOC](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto)
I tried both ways and i don't see either the request header or the metadata. The JWT payload header is nil and the dynamic metadata is not present.
`bad argument #2 to 'add' (string expected, got nil)`

The "authorization" header is present with current bearer token in it.

My configuration:
```
http_filters:
  - name: envoy.filters.http.jwt_authn
    config:
      providers:
        ***_stage:
          issuer: *****
          forward: true
          remote_jwks:
            http_uri:
              uri: ***
              cluster: ***_jwks_cluster
              timeout: 5s
          forward_payload_header: x-jwt-payload
          payload_in_metadata: jwt_payload
  - name: envoy.lua
    typed_config:
      "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
      inline_code: |
        -- Called on the request path.
        function envoy_on_request(request_handle)
          request_handle:logInfo("adding custom header")
          local payload = request_handle:headers():get("x-jwt-payload")
          request_handle:headers():add("x-custom", payload)
        end
        function envoy_on_response(request_handle)
        end
```

**Comment by qiwzhang** [comment]
In jwt_authn filter config,  you only specified Provider, you also need to specify [Requirement](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto#L486).   If not specified, the filter will not verify JWT, and header or metadata will not be created.

**Comment by method350** [comment]
@qiwzhang Thank you very much! That did the trick.

**Comment by lizan** [comment]
Closing as answered.
