### ISSUE TITLE
 Exchange data for one-way network

### ISSUE THREAD

**Issue by QiusHosens** [envoyproxy/envoy#10083]
i want to exchange data for one-way network.
eg. extranet ip A is 114.100.100.100, intranet ip B is 192.168.1.1,
i want to send data from A to B, and B to A.
can envoy be implemented ？
thanks !

**Comment by lizan** [comment]
What do you mean by one-way network? B is behind NAT?

**Comment by QiusHosens** [comment]
yes, only B can access A, A can't access B

**Comment by QiusHosens** [comment]
of course, B can connect to A with socket.
i mean B can ping A, A can't ping B

**Comment by QiusHosens** [comment]
> What do you mean by one-way network? B is behind NAT?

yes. B is behind NAT, i mean B can ping A, A can't ping B. B can connect to A with socket.

**Comment by lizan** [comment]
@QiusHosens What is the protocol are you using, where do you want to deploy Envoy? Generally it depends on the connectivity between A <-> Envoy, and B <-> Envoy, so if you deploy Envoy where NAT happens it could work.

**Comment by QiusHosens** [comment]
@lizan i want to use http, but i cannot deploy Envoy where NAT happens, only can deploy Envoy on A and B, can it work?
