### ISSUE TITLE
Admin interface /certs shows duplicated certs using SDS

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#10095]
**Issue Template**

*Title*: Admin interface /certs shows duplicated certs using SDS

*Description*:
I am using SDS (not sure if this is relevant) and have some certs loaded. `config_dump` shows the secrets correctly:
```json
  {
   "@type": "type.googleapis.com/envoy.admin.v3.SecretsConfigDump",
   "dynamic_active_secrets": [
    {
     "name": "default",
     "version_info": "2020-02-19 00:17:05.818690253 +0000 UTC m=+0.461950234",
     "last_updated": "2020-02-19T00:17:06.063Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "default",
      "tls_certificate": {
       "certificate_chain": {
        "inline_bytes": "elided"
       },
       "private_key": {
        "inline_bytes": "W3JlZGFjdGVkXQ=="
       }
      }
     }
    },
    {
     "name": "ROOTCA",
     "version_info": "2020-02-19 00:17:06.979164756 +0000 UTC m=+1.622424818",
     "last_updated": "2020-02-19T00:17:06.990Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "ROOTCA",
      "validation_context": {
       "trusted_ca": {
        "inline_bytes": "elided"
       }
      }
     }
    }
   ]
  }


However, the /certs endpoint has the same cert duplicated many many times:

Here are the unique entries:
```
$ curl -s http://localhost:15000/certs | jq '.certificates[]' -c | sort | uniq
{"ca_cert":[{"path":"./etc/istio/citadel-ca-cert/ca-cert-ns.pem","serial_number":"d6be877145ed117f62f70bf83385d92d","subject_alt_names":[],"days_until_expiration":"3649","valid_from":"2020-02-18T23:59:54Z","expiration_time":"2030-02-15T23:59:54Z"}],"cert_chain":[{"path":"<inline>","serial_number":"5ce466eb8250375a3acfadba55e99fcc","subject_alt_names":[{"uri":"spiffe://cluster.local/ns/default/sa/default"}],"days_until_expiration":"0","valid_from":"2020-02-19T00:17:06Z","expiration_time":"2020-02-19T00:18:06Z"}]}
{"ca_cert":[{"path":"<inline>","serial_number":"d6be877145ed117f62f70bf83385d92d","subject_alt_names":[],"days_until_expiration":"3649","valid_from":"2020-02-18T23:59:54Z","expiration_time":"2030-02-15T23:59:54Z"}],"cert_chain":[{"path":"<inline>","serial_number":"5ce466eb8250375a3acfadba55e99fcc","subject_alt_names":[{"uri":"spiffe://cluster.local/ns/default/sa/default"}],"days_until_expiration":"0","valid_from":"2020-02-19T00:17:06Z","expiration_time":"2020-02-19T00:18:06Z"}]}
```

Compared to all entries:
```
$ curl -s http://localhost:15000/certs | jq '.certificates[]' -c | sort  | wc -l
31
```
cc @incfly

**Comment by ramaraochavali** [comment]
The `/certs'  endpoints displays certs from all the tls contexts. So if the same cert is repeatedly used in multiple tls contexts, I think it is expected that it is shown multiple times as per the current implementation.
