### ISSUE TITLE
Wrong response code details set on response body too large

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#10119]
https://github.com/envoyproxy/envoy/blob/6a95a21ce49d1144d3cde7159c767c192a44d8a4/source/common/http/conn_manager_impl.cc#L2318 clearly shows that we're setting `RequestHeadersTooLarge` when we fail the request due to the response body being too large. We should update this to use a more appropriate response flag. 

Setting a response flag would also probably be useful here.

**Comment by nezdolik** [comment]
Hi @snowp, I would like to fix this issue.

**Comment by nezdolik** [comment]
This has been fixed in https://github.com/envoyproxy/envoy/pull/11331
