### ISSUE TITLE
Making httpcall to external services in lua filter 

### ISSUE THREAD

**Issue by forkjoseph** [envoyproxy/envoy#10112]
Hi,

I'm trying to configure Lua filter to make HTTP call to an external service. From the documentation, the API defines `headers, body = handle:httpCall(cluster, headers, body, timeout)`. 

It looks like "cluster" refers to Kubernetes cluster or any other Pod. Is there a way to make a Lua call to external services without authorization or ServiceEntry in Istio?

Here's my Lua code:
```lua
        function envoy_on_request(request_handle)
          request_handle:logCritical("HI")
          -- Make an HTTP call.
          local headers, body = request_handle:httpCall(
          "outbound|80||leelabs.org",
          {
            [":method"] = "GET",
            [":path"] = "/",
            [":authority"] = "leelabs.org",
            ["set-cookie"] = { "lang=lua; Path=/", "type=binding; Path=/" }
          },
          "hello world",
          5000)
          request_handle:logCritical("HI".. body)
```

**Comment by snowp** [comment]
The cluster refers to an Envoy cluster (https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster.proto, defined in your bootstrap or through your management server). You should be able to define a cluster for your remote service and reference that in your lua call

**Comment by forkjoseph** [comment]
Thanks for the pointer! I'm wondering whether there's a way to refer dynamically to "external cluster" that points to external end-point when a cluster is not found in the configuration.
