### ISSUE TITLE
Rewriting response body depending on HTTP status code

### ISSUE THREAD

**Issue by method350** [envoyproxy/envoy#10125]
I'm trying to implement the following scenario: JWT validation with _envoy.filters.http.jwt_authn_ filter -> external request authorization with _envoy.ext_authz_ -> additional response body validation with _envoy.lua_ _envoy_on_response_ function. If response body has any not authorized data i would like to replace the response body with my custom error response. So far LUA scripts are supporting replacement of response headers, like setting HTTP 401 Unauthorized. But still the client receive the response body. Is there any way to filter or modify the response body with envoy http filter depending on response http status code?

**Comment by bochuxt** [comment]
Please help by provide example.  I found a [wamse](https://github.com/envoyproxy/envoy-wasm/blob/master/examples/wasm/envoy_filter_http_wasm_example.cc) c++ but there is no onResponseBody function. 


class ExampleContext : public Context {
public:
  explicit ExampleContext(uint32_t id, RootContext* root) : Context(id, root) {}

  void onCreate() override;
  FilterHeadersStatus onRequestHeaders(uint32_t headers, bool end_of_stream) override;
  FilterDataStatus onRequestBody(size_t body_buffer_length, bool end_of_stream) override;
  FilterHeadersStatus onResponseHeaders(uint32_t headers, bool end_of_stream) override;
  void onDone() override;
  void onLog() override;
  void onDelete() override;
};

**Comment by method350** [comment]
help wanted

**Comment by dio** [comment]
I think this can be done using https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply.
