### ISSUE TITLE
Support Certificate Revocation Lists (CRLs) in DER format

### ISSUE THREAD

**Issue by AKBarcenas** [envoyproxy/envoy#10148]
*Description*:
Currently the only supported format for CRLs is PEM format, but this requires conversion of CRLs in DER format to PEM format resulting in an overall larger file.

As noted in #5713:
> Supporting DER format would allow passing ~30% smaller certificates and private keys over xDS (compared to currently supported PEM format) and avoid base64-decoding in Envoy.

Similar to #5713, the proposal here would be to support both formats rather than replace PEM with DER.

I am interested in taking on this work and I am opening this issue to track the feature.

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto#envoy-api-field-auth-certificatevalidationcontext-crl

**Comment by dio** [comment]
@AKBarcenas sounds great! 

cc. @PiotrSikora

**Comment by PiotrSikora** [comment]
Uhm, we should probably just reopen #5713.

**Comment by dio** [comment]
Closing in favor of #5713

**Comment by AKBarcenas** [comment]
Just to clarify on this issue, I was looking to implement this for CRLs specifically. However, I recognize that this likely would have a decent amount of overlap with implementation for TLS certificates.
