### ISSUE TITLE
Cannot load multiple CA certificates through SDS

### ISSUE THREAD

**Issue by tazmanian10** [envoyproxy/envoy#10155]
Hi all,

i've been trying to load multiple CA certificates through SDS by concatenating them and setting them as an inline string. However it seems that envoy always takes into account only the first one.

In order to test this, I have created two different authorities by using openssl and then created and signed certificates and keys with each one of them. I set the trusted authorities as a reply to the SDS request and get an ACK from envoy. However, when i use curl to send a request towards envoy, TLS handshake is completed only for the request that uses the certificates produced from the CA authority that sits on the top of the list i sent as a reply.

**Comment by dio** [comment]
@yxue do you have any ideas on this?

**Comment by tazmanian10** [comment]
I also think that it would be better to add multiple CA through a list, and not through the same string/file. Also the documentation should be updated in order to be clear about the current handling.
