### ISSUE TITLE
Dynamic Forward Proxy with auto_host_rewrite_header: works for HTTP but doesn't for HTTPS request

### ISSUE THREAD

**Issue by mabukhovsky** [envoyproxy/envoy#10160]
*Title*: *Dynamic Forward Proxy with auto_host_rewrite_header: works for HTTP but doesn't for HTTPS request*

*Description*:
Dynamic Forward Proxy: auto_host_rewrite_header: "X-Host-Port" works as intended for HTTP but doesn't for HTTPS (see the logs). The log is saying:
[source/common/http/conn_manager_impl.cc:278] [C65] dispatch error: http/1.1 protocol error: request headers failed spec compliance checks

*Repro steps*:
export http_proxy=0.0.0.0:8000

See the config provided.

HTTP request one works fine: 
curl --header "X-Host-Port: www.yahoo.com" http://www.news.com
Response with Yahoo page is returned.

HTTPS request fails: 
curl --header "X-Host-Port: www.yahoo.com" https://www.news.com

Log line:
[source/common/http/conn_manager_impl.cc:278] [C65] dispatch error: http/1.1 protocol error: request headers failed spec compliance checks (see full log below)

*Config*:

 {

  "configs": [
    {
      "@type": "type.googleapis.com/envoy.admin.v3.BootstrapConfigDump",
      "bootstrap": {
        "node": {
          "hidden_envoy_deprecated_build_version": "bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7/1.13.0/Clean/RELEASE/BoringSSL",
          "user_agent_name": "envoy",
          "user_agent_build_version": {
            "version": {
              "major_number": 1,
              "minor_number": 13
            },
            "metadata": {
              "ssl.version": "BoringSSL",
              "revision.status": "Clean",
              "revision.sha": "bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7",
              "build.type": "RELEASE"
            }
          },
          "extensions": [
            {
              "name": "dubbo",
              "category": "envoy.dubbo_proxy.protocols"
            },
            {
              "name": "envoy.file_access_log",
              "category": "envoy.access_loggers"
            },

... (cut long list of filters)...

        "static_resources": {
          "listeners": [
            {
              "name": "listener_0",
              "address": {
                "socket_address": {
                  "address": "0.0.0.0",
                  "port_value": 80
                }
              },
              "filter_chains": [
                {
                  "filters": [
                    {
                      "name": "envoy.http_connection_manager",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                        "stat_prefix": "ingress_http",
                        "route_config": {
                          "name": "local_route",
                          "virtual_hosts": [
                            {
                              "name": "local_service",
                              "domains": [
                                "*"
                              ],
                              "routes": [
                                {
                                  "match": {
                                    "prefix": "/"
                                  },
                                  "route": {
                                    "cluster": "dynamic_forward_proxy_cluster"
                                  },
                                  "per_filter_config": {
                                    "envoy.filters.http.dynamic_forward_proxy": {
                                      "auto_host_rewrite_header": "X-Host-Port"
                                    }
                                  }
                                },
                                {
                                  "match": {
                                    "prefix": "/"
                                  },
                                  "route": {
                                    "cluster": "dynamic_forward_proxy_cluster"
                                  }
                                }
                              ]
                            }
                          ]
                        },
                        "http_filters": [
                          {
                            "name": "envoy.filters.http.dynamic_forward_proxy",
                            "typed_config": {
                              "@type": "type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig",
                              "dns_cache_config": {
                                "name": "dynamic_forward_proxy_cache_config",
                                "dns_lookup_family": "V4_ONLY"
                              }
                            }
                          },
                          {
                            "name": "envoy.router"
                          }
                        ]
                      }
                    }
                  ]
                }
              ]
            }
          ],
          "clusters": [
            {
              "name": "dynamic_forward_proxy_cluster",
              "connect_timeout": "1s",
              "lb_policy": "CLUSTER_PROVIDED",
              "transport_socket": {
                "name": "envoy.transport_sockets.tls",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                  "common_tls_context": {
                    "validation_context": {
                      "trusted_ca": {
                        "filename": "/etc/ssl/certs/ca-certificates.crt"
                      }
                    }
                  }
                }
              },
              "cluster_type": {
                "name": "envoy.clusters.dynamic_forward_proxy",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig",
                  "dns_cache_config": {
                    "name": "dynamic_forward_proxy_cache_config",
                    "dns_lookup_family": "V4_ONLY"
                  }
                }
              }
            }
          ]
        },
        "admin": {
          "access_log_path": "/tmp/admin_access.log",
          "address": {
            "socket_address": {
              "address": "0.0.0.0",
              "port_value": 8001
            }
          }
        }
      },
      "last_updated": "2020-02-24T23:34:44.671Z"
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ClustersConfigDump",
      "static_clusters": [
        {
          "cluster": {
            "@type": "type.googleapis.com/envoy.api.v2.Cluster",
            "name": "dynamic_forward_proxy_cluster",
            "connect_timeout": "1s",
            "lb_policy": "CLUSTER_PROVIDED",
            "transport_socket": {
              "name": "envoy.transport_sockets.tls",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "common_tls_context": {
                  "validation_context": {
                    "trusted_ca": {
                      "filename": "/etc/ssl/certs/ca-certificates.crt"
                    }
                  }
                }
              }
            },
            "cluster_type": {
              "name": "envoy.clusters.dynamic_forward_proxy",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig",
                "dns_cache_config": {
                  "name": "dynamic_forward_proxy_cache_config",
                  "dns_lookup_family": "V4_ONLY"
                }
              }
            }
          },
          "last_updated": "2020-02-24T23:34:44.685Z"
        }
      ]
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ListenersConfigDump",
      "static_listeners": [
        {
          "listener": {
            "@type": "type.googleapis.com/envoy.api.v2.Listener",
            "name": "listener_0",
            "address": {
              "socket_address": {
                "address": "0.0.0.0",
                "port_value": 80
              }
            },
            "filter_chains": [
              {
                "filters": [
                  {
                    "name": "envoy.http_connection_manager",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                      "stat_prefix": "ingress_http",
                      "route_config": {
                        "name": "local_route",
                        "virtual_hosts": [
                          {
                            "name": "local_service",
                            "domains": [
                              "*"
                            ],
                            "routes": [
                              {
                                "match": {
                                  "prefix": "/"
                                },
                                "route": {
                                  "cluster": "dynamic_forward_proxy_cluster"
                                },
                                "per_filter_config": {
                                  "envoy.filters.http.dynamic_forward_proxy": {
                                    "auto_host_rewrite_header": "X-Host-Port"
                                  }
                                }
                              },
                              {
                                "match": {
                                  "prefix": "/"
                                },
                                "route": {
                                  "cluster": "dynamic_forward_proxy_cluster"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      "http_filters": [
                        {
                          "name": "envoy.filters.http.dynamic_forward_proxy",
                          "typed_config": {
                            "@type": "type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig",
                            "dns_cache_config": {
                              "name": "dynamic_forward_proxy_cache_config",
                              "dns_lookup_family": "V4_ONLY"
                            }
                          }
                        },
                        {
                          "name": "envoy.router"
                        }
                      ]
                    }
                  }
                ]
              }
            ]
          },
          "last_updated": "2020-02-24T23:34:44.688Z"
        }
      ]
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ScopedRoutesConfigDump"
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.RoutesConfigDump",
      "static_route_configs": [
        {
          "route_config": {
            "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
            "name": "local_route",
            "virtual_hosts": [
              {
                "name": "local_service",
                "domains": [
                  "*"
                ],
                "routes": [
                  {
                    "match": {
                      "prefix": "/"
                    },
                    "route": {
                      "cluster": "dynamic_forward_proxy_cluster"
                    },
                    "per_filter_config": {
                      "envoy.filters.http.dynamic_forward_proxy": {
                        "auto_host_rewrite_header": "X-Host-Port"
                      }
                    }
                  },
                  {
                    "match": {
                      "prefix": "/"
                    },
                    "route": {
                      "cluster": "dynamic_forward_proxy_cluster"
                    }
                  }
                ]
              }
            ]
          },
          "last_updated": "2020-02-24T23:34:44.688Z"
        }
      ]
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.SecretsConfigDump"
    }
  ]
}

*Logs*:
[2020-02-25 17:55:49.265][16][debug][conn_handler] [source/server/connection_handler_impl.cc:353] [C64] new connection
[2020-02-25 17:55:49.266][16][debug][http] [source/common/http/conn_manager_impl.cc:263] [C64] new stream
[2020-02-25 17:55:49.266][16][debug][http] [source/common/http/conn_manager_impl.cc:278] [C64] dispatch error: http/1.1 protocol error: request headers failed spec compliance checks
[2020-02-25 17:55:49.266][16][debug][http] [source/common/http/conn_manager_impl.cc:1854] [C64][S10943006874731286895] stream reset
[2020-02-25 17:55:49.266][16][debug][connection] [source/common/network/connection_impl.cc:101] [C64] closing data_to_write=66 type=2
[2020-02-25 17:55:49.266][16][debug][connection] [source/common/network/connection_impl_base.cc:30] [C64] setting delayed close timer with timeout 1000 ms
[2020-02-25 17:55:49.266][16][debug][connection] [source/common/network/connection_impl.cc:593] [C64] write flush complete
[2020-02-25 17:55:49.268][16][debug][connection] [source/common/network/connection_impl.cc:487] [C64] remote early close
[2020-02-25 17:55:49.268][16][debug][connection] [source/common/network/connection_impl.cc:192] [C64] closing socket: 0
[2020-02-25 17:55:49.268][16][debug][conn_handler] [source/server/connection_handler_impl.cc:86] [C64] adding to cleanup list
[2020-02-25 17:55:49.935][15][debug][conn_handler] [source/server/connection_handler_impl.cc:353] [C65] new connection
[2020-02-25 17:55:49.936][15][debug][http] [source/common/http/conn_manager_impl.cc:263] [C65] new stream
[2020-02-25 17:55:49.937][15][debug][http] [source/common/http/conn_manager_impl.cc:278] [C65] dispatch error: http/1.1 protocol error: request headers failed spec compliance checks
[2020-02-25 17:55:49.937][15][debug][http] [source/common/http/conn_manager_impl.cc:1854] [C65][S2195202743173113075] stream reset
[2020-02-25 17:55:49.937][15][debug][connection] [source/common/network/connection_impl.cc:101] [C65] closing data_to_write=66 type=2
[2020-02-25 17:55:49.937][15][debug][connection] [source/common/network/connection_impl_base.cc:30] [C65] setting delayed close timer with timeout 1000 ms
[2020-02-25 17:55:49.937][15][debug][connection] [source/common/network/connection_impl.cc:593] [C65] write flush complete
[2020-02-25 17:55:49.940][15][debug][connection] [source/common/network/connection_impl.cc:487] [C65] remote early close
[2020-02-25 17:55:49.940][15][debug][connection] [source/common/network/connection_impl.cc:192] [C65] closing socket: 0
[2020-02-25 17:55:49.942][15][debug][conn_handler] [source/server/connection_handler_impl.cc:86] [C65] adding to cleanup list
[2020-02-25 17:55:52.243][6][debug][main] [source/server/server.cc:174] flushing stats

**Comment by dio** [comment]
cc. @mattklein123

**Comment by mattklein123** [comment]
Is HTTPS trying to use CONNECT? We don't support CONNECT yet.

**Comment by mabukhovsky** [comment]
@mattklein123 Thanks for quick response. Do you plan to add HTTPS CONNECT support anytime soon? Without it Dynamic Forward Proxy functionality is limited to HTTP requests only.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/issues/1451. It's possible that @alyssawilk will implement this as she is working on similar stuff right now.

**Comment by mabukhovsky** [comment]
@mattklein123 Thanks for insight, truly appreciate your help. @alyssawilk Could you confirm that the issue described is related to #1451 and will be resolved anytime soon.
