### ISSUE TITLE
Error : SSL error: 268436536:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by vkpardava** [envoyproxy/envoy#10174]
Hi All,

We have a requirement where Service A communicates to Service B via Envoy hosted as sidecar on the same POD of kubernates 

SETUP : 
Service A POD has two containers running on different ports.
App Image : 8443
Envoy : 8080

Service B POD has only app container running on given port
App Image : 8443

We have Mutual Authentication in place for both the services so without valid certificates its not possible to communicate with each other.

Both the service only allows communication via TLSv1.2 protocol

WHAT WORKS : Service A -> Service B  communication without Envoy in middle

ISSUE : When we have the Envoy in between the flow is like below.

[Service A -> Envoy] -------------------> [Service B]
[Service A: 8443->localhost:8080] ------> [Service B:8443]

We get the error on envoy container as mentioned below when envoy tries to communicate to Service B

Error : SSL error: 268436536:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR

Is anyone here aware of this error and what it actually mean? Does envoy have any documentation on these error and its possible cause?

ATTACHED The yaml file with configuration.

Any pointer are really appreciated.

Thanks in Advance
[envoy_e1.txt](https://github.com/envoyproxy/envoy/files/4255551/envoy_e1.txt)

**Comment by dio** [comment]
cc. @lizan

**Comment by vkpardava** [comment]
@davidben @dvorak44 @agl @nharper @cjpatton

**Comment by agl** [comment]
TLSV1_ALERT_INTERNAL_ERROR means that the TLS endpoint received an &ldquo;internal error&rdquo; alert from the other side of the connection. TLS alerts aren't more descriptive than that. You would have to look at the logs from the process that generated the alert.

**Comment by vkpardava** [comment]
@agl this came from log only and its just telling this much only. when I trun off the client auth from REQUIRED and change it to REQUEST , i dont see this error but then it does not do MTLS.

How can I find the root cause, that what is making this fail when used with REQUIRED?

only internal error does not says anything.

**Comment by davidben** [comment]
You need to look at the other service's logs. (The log from Envoy and BoringSSL simply means "the other side reported an error". In order to determine the error, you need to look at the other side because Envoy and BoringSSL have no way of knowing.)

**Comment by vkpardava** [comment]
@davidben There are no logs rotation pertaining to this request, so I doubt its even not reaching the other side due to this error. is it a bug ?

**Comment by davidben** [comment]
No, it is definitely reaching the other side. `TLSV1_ALERT_INTERNAL_ERROR` means BoringSSL received an `internal_error` alert from the other side. Not only did it get to the other side, the other side ran into an internal error and told BoringSSL about it.

**Comment by Abhinavjain2302** [comment]
@vkpardava I am also getting the same error. Any update on what could be the reason?

**Comment by tariq1890** [comment]
+1 We've observed this in our production services. Can this be re-opened please?

```
routines:OPENSSL_internal:CLIENTHELLO_TLSEXT 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT
``

**Comment by davidben** [comment]
@tariq1890 That looks like a completely different error. (`CLIENTHELLO_TLSEXT` and `PARSE_TLSEXT` vs `TLSV1_ALERT_INTERNAL_ERROR`.) Yours means the ClientHello from the peer is invalid, which is certainly possible in production. The network is the network. Sometimes folks send you invalid stuff.
