### ISSUE TITLE
Server Module tests fail on PowerPC ppc64le 

### ISSUE THREAD

**Issue by aishwaryabk** [envoyproxy/envoy#10186]
I am working on testing envoy and the tests fail.

Failure:
ERROR: /envoy/test/server/BUILD:331:1: C++ compilation of rule '//test/server:filter_chain_benchmark_test' failed (Exit 1) process-wrapper failed: error executing command
`  (cd /root/.cache/bazel/_bazel_root/37e3aec351bcd85a6ea8b58e3592ef6e/sandbox/processwrapper-sandbox/6388/execroot/envoy && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm:-static-libgcc \
    PATH=/usr/local/bin:/opt/rh/devtoolset-7/root/usr/bin:/opt/gcc/bin:/usr/local/go/bin:/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/8c4bf428d77d0af50a5bd92e34c78505/process-wrapper '--timeout=0' '--kill_delay=15' 
  /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' `

In file included from test/server/filter_chain_benchmark_test.cc:19:0:
bazel-out/ppc-fastbuild/bin/external/com_github_google_benchmark/_virtual_includes/benchmark/benchmark/benchmark.h:1071:16:
 `error: 'virtual void benchmark::Fixture::SetUp(benchmark::State&)' was hidden [-Werror=overloaded-virtual]
   virtual void SetUp(State& st) { SetUp(const_cast<const State&>(st)); }
                ^~~~~
test/server/filter_chain_benchmark_test.cc:152:16: error:   by 'virtual void Envoy::Server::FilterChainBenchmarkFixture::SetUp(const benchmark::State&)'`
` [-Werror=overloaded-virtual]
   virtual void SetUp(const ::benchmark::State& state) override {
                ^~~~~`
`external/com_github_fmtlib_fmt/include/fmt/core.h: In member function 'void fmt::v5::internal::arg_map<Context>::push_back(fmt::v5::internal::value<Context>) [with Context = fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>]':`
`external/com_github_fmtlib_fmt/include/fmt/core.h:950:8: note: the ABI of passing aggregates with 16-byte alignment has changed in GCC 5`
  ` void push_back(value<Context> val) {
        ^~~~~~~~`

Environment:
Rhel 7.6
ppc64le

Is there a fix for this error?
Would like some help on this.

**Comment by dio** [comment]
cc. @lizan

**Comment by lizan** [comment]
what's your compiler version? cc @cmluciano

**Comment by aishwaryabk** [comment]
> what's your compiler version? cc @cmluciano

@lizan Compiler version is gcc-7.3.0

**Comment by cmluciano** [comment]
@lizan what is the plan for gcc and the testing harness? Should I switch ppc64le to try both or is clang-8 still the recommended version?

**Comment by lizan** [comment]
Tests are not built against gcc, there has been proposals but no one took action on gcc test CI integration yet. clang-9 is recommended version.
