### ISSUE TITLE
Envoy maps HTTP gateway timeout to gRPC UNAVAILABLE (instead of DEADLINE_EXCEEDED)

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#10184]
*Title*: *Envoy maps HTTP 504 to gRPC UNAVAILABLE (instead of DEADLINE_EXCEEDED)*

*Description*:
Envoy does mapping between HTTP and gRPC status codes in https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/status.cc

In `grpcToHttpStatus()`, DeadlineExceeded becomes 504, but in `httpToGrpcStatus()`, 504 becomes Unavailable.

*Proposal*:
Make 504 map to DeadlineExceeded in httpToGrpcStatus()

**Comment by mpuncel** [comment]
Apparently 504 maps to Unavailable in the official mapping https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.

The issue I was seeing was when the router filter enforces a timeout and sends a local reply, it starts with a 504 HTTP code which then gets mapped to Unavailable. maybe another option would be to make the gRPC timeout code similarly configurable? Unfortunately that'll probably mean plumbing that extra code through sendLocalReply() all over the place but that way we don't need to deviate from the official mapping

**Comment by dio** [comment]
@snowp do you have opinions on this?

**Comment by snowp** [comment]
I think we'll want to stick with the gRPC specified mappings, so that leaves making it possible to configure and set the gRPC code separately. WDYT @lizan

**Comment by mattklein123** [comment]
I think it would be best to handle this as part of the local reply customization work that hopefully someone will pick up and finish soonish.

**Comment by wtzhang23** [comment]
Hello; I'd like to work on supporting this on the [local_reply_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-localreplyconfig) (e.g. by adding a grpc_status field). Could I have the go-ahead for this?
