### ISSUE TITLE
api: add compile flag to have only one api version in Envoy

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#10198]
This flag would make it so that only one version, the current version (v3 right now), of the api is compiled in or attempted to be accessed at runtime.

The Envoy Mobile team is interested in this as it relates to non-trivial binary size reduction. More details about our thinking can be found in https://github.com/lyft/envoy-mobile/issues/710.

**Comment by junr03** [comment]
cc @htuch @lizan I am back in office, and looking to start a discussion around this. Let me know if you have ideas or work planned in this area as you ramp back up on api versioning work. I'd like to be on the same page as you all in order to prevent making changes here that conflict with your vision for versioning.

**Comment by htuch** [comment]
@junr03 this seems like a useful thing to have. I think with some macro magic we can capture/modify the v2 deps in the v3 APIs and no-op them for v3-only builds. When this compile time flag is set, Envoy will need to ensure it only generates v3 transport/resource versions (and only accepts these from any management server).

There's probably some things missing from the above, but happy to discuss further.

**Comment by lizan** [comment]
Ideally it is better with less macro magic and just link magic. #9649 should do some of the trick. cc @Shikugawa

**Comment by mattklein123** [comment]
v2 is going away soon so just closing this.
