### ISSUE TITLE
Proposal: add network direct response filter

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10192]
In some cases, we would like to collect telemetry for calls that are known to be missing routes (e.g. explicitly blacklisted network destinations, unknown destinations). The current work-around is to define an empty cluster and then rely on `tcp_proxy` to route to it. What we would want is to minimize resources used to handle such connections, and instead directly respond in a filter.

Do you think it's worth adding a simple network direct response filter that:
1) is a terminal filter
2) closes downstream connections
3) may potentially send a constant blob before closing

**Comment by mattklein123** [comment]
SGTM
