### ISSUE TITLE
hardcoded v2 type urls in xds requests

### ISSUE THREAD

**Issue by bennettdong** [envoyproxy/envoy#10209]
*Title*: *hardcoded v2 type urls in xds requests*

*Description*:
In order to migrate to v3 API, `loadTypeUrl` functions are used to determine type url in discovery requests. However, I found that some files are still using v2 type url constants in [this file](https://github.com/envoyproxy/envoy/blob/master/source/common/config/resources.h). This means that even envoy is configured to use v3, it will still send requests for v2 resources.

Correct me if there is any magic actually doing the conversion somewhere.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/common/router/scoped_rds.cc#L243
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/common/router/scoped_rds.cc#L258
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/common/upstream/cds_api_impl.cc#L68-L70
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/common/upstream/cluster_manager_impl.cc#L150-L155
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/common/upstream/cluster_manager_impl.cc#L752-L754
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/server/lds_api.cc#L43-L45
https://github.com/envoyproxy/envoy/blob/334724c8cbbdffcafcfb0590a9dd1d9bd71917e0/source/server/server.cc#L526-L535

**Comment by mattklein123** [comment]
cc @lizan

**Comment by Shikugawa** [comment]
@lizan This problem may be resolved with `getResourceName` in #9649. So I will fix them after merging it.
