### ISSUE TITLE
Is the note warning against using regex-based matcher still relevant after safe_regex?

### ISSUE THREAD

**Issue by kiranjthomas** [envoyproxy/envoy#10226]
*Title*: is the regex_based matcher warning found in [v2/stats.proto](https://github.com/envoyproxy/envoy/blob/b09184f8e9e17839f555f78ad8dbbcc57e3709db/api/envoy/config/metrics/v2/stats.proto#L98-L100) and [v3/stats.proto](https://github.com/envoyproxy/envoy/blob/b09184f8e9e17839f555f78ad8dbbcc57e3709db/api/envoy/config/metrics/v3/stats.proto#L107-L109) still relevant after safe_regex was implemented?

*Description*:
[v3/stats.proto](https://github.com/envoyproxy/envoy/blob/b09184f8e9e17839f555f78ad8dbbcc57e3709db/api/envoy/config/metrics/v3/stats.proto#L107-L109) and [v2.stats.proto](https://github.com/envoyproxy/envoy/blob/b09184f8e9e17839f555f78ad8dbbcc57e3709db/api/envoy/config/metrics/v2/stats.proto#L98-L100) both warn against using a regex-based matcher. Here is the warning

```
// A StringMatcher can be used to match against an exact string, a suffix / prefix, or a regex.
// **NB:** For performance reasons, it is highly recommended to use a prefix- or suffix-based
// matcher rather than a regex-based matcher.
```

 I'm wondering if that is still relevant after safe_regex was implemented in envoy `v.1.12.0`. Can anyone provide guidance on why this is or is not an issue?

I'm debating whether to use suffix or safe_regex when including circuit breaker stats. For circuit breaking, would we only see performance issues at startup?

**Comment by mattklein123** [comment]
Always prefer not using regex matching if you can avoid it, thus the warning still stands.
