### ISSUE TITLE
Valid JWS, Keycloak-issued, Token fails to be parsed 

### ISSUE THREAD

**Issue by ch-bohlen** [envoyproxy/envoy#10222]
Issue cross-posted to jwt_verify_lib: https://github.com/google/jwt_verify_lib/issues/43

*Title*: *Valid JWS, Keycloak-issued, Token fails to be parsed*

*Description*:
Using Istio's authentication policy (jwt_authn filter) and validating a Keycloak-issued Token fails due to the payload's base64 or json representation being detected as invalid.

The Token can be correctly parsed by https://jwt.io/ which outputs the correct JSON. The header and payload parts can also be properly parsed by https://www.base64decode.org/, also outputting correct JSON.

Versions:
Istio 1.4.5
Envoy 1.12.0
Keycloak 8.0.1

**JWS Token failing to parse:**

`eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwam9oV01GRVV3SmRCOHkwVXFpX3lWNEdFS3FIZUxpaUdZNGR2MUpIZzNvIn0.eyJqdGkiOiIwNjBhNzA2MS04ZGM0LTQ5Y2YtOGM5Zi05YjRjNjNjOTI2YTAiLCJleHAiOjE1ODMwOTkwMjYsIm5iZiI6MCwiaWF0IjoxNTgzMDk4NzI2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvdGVzdCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI1NWFiYjUzNi1jYWQyLTRhN2YtOGM3My05YzRlYTBjNDQ2ODYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ0ZXN0IiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiZDMwY2U3ZmMtZDlmNi00NGQxLWE4YzktMDRmOTA5ZTgyMmYzIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiY2xpZW50SWQiOiJ0ZXN0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRIb3N0IjoiMTcyLjI1LjAuMSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC10ZXN0IiwiY2xpZW50QWRkcmVzcyI6IjE3Mi4yNS4wLjEifQ.ANh4Zxhw9OBO-3yrctnSTkXxf6Tc-jTw3kl-fVw2GF1ridxQ5HOFfbYa8elCtuyh75CYd4Q4b56bam4S424BOmwBY2nrqBr_oRHmxGTytzpIh0EdE2rJl_twPjQnqiyZzIO_sEHxkldt9vlSFxNUUHyyj2gJKLx8jaRCayPVIXQ44RZ1UWEP48Mhg5WDd6UzT9GxZNSsj6yxzDHzpNQLRVnsDEfJVEcHm2kftXP-O2LZ_TtH3LliLXoCBNAycfhfA4w0RlQW-aKZm-BtHV_PyqcvaeYeA2Gxn6aFNIBJx2ovWP-6Nx8U1k-6bFoXmmoZjQ_oZHtg1FDs1Yxc3XTj1A`

**Decoded Header:**

`{"alg":"RS256","typ" : "JWT","kid" : "pjohWMFEUwJdB8y0Uqi_yV4GEKqHeLiiGY4dv1JHg3o"}`

**Decoded Payload:**

`{"jti":"060a7061-8dc4-49cf-8c9f-9b4c63c926a0","exp":1583099026,"nbf":0,"iat":1583098726,"iss":"http://localhost:8080/auth/realms/test","aud":"account","sub":"55abb536-cad2-4a7f-8c73-9c4ea0c44686","typ":"Bearer","azp":"test","auth_time":0,"session_state":"d30ce7fc-d9f6-44d1-a8c9-04f909e822f3","acr":"1","realm_access":{"roles":["offline_access","uma_authorization"]},"resource_access":{"account":{"roles":["manage-account","manage-account-links","view-profile"]}},"scope":"profile email","clientId":"test","email_verified":false,"clientHost":"172.25.0.1","preferred_username":"service-account-test","clientAddress":"172.25.0.1"}`

*Logs*:

`[Envoy (Epoch 0)] [2020-03-01 21:38:58.383][24][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/authenticator.cc:107] JWT authentication starts (allow_failed=true)
[Envoy (Epoch 0)] [2020-03-01 21:38:58.383][24][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/authenticator.cc:245] JWT token verification completed with: Jwt header is an invalid Base64url input or an invalid JSON
[Envoy (Epoch 0)] [2020-03-01 21:38:58.383][24][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:61] Called Filter : check complete OK`

**Comment by lizan** [comment]
@qiwzhang

**Comment by qiwzhang** [comment]
Please see my replied in https://github.com/google/jwt_verify_lib/issues/43

For Envoy or Istio,  since it is NOT using the latest version.  It is using 2020-01-08 version.  I also tested it with the JWT.  It works.

Are you sure you the included JWT is the problem one?

**Comment by qiwzhang** [comment]
https://github.com/envoyproxy/envoy/pull/10228 will update jwt_verify_lib to the latest.
