### ISSUE TITLE
Options for installing envoy FROM centos7 Docker image

### ISSUE THREAD

**Issue by kadimulam** [envoyproxy/envoy#10221]
We have a base Centos 7 Docker image. We are trying to install envoy on Centos 7 and create a single Docker image and thus a single container. We are looking something similar to https://joeyb.org/running-envoy-on-centos-6-7. Could you please let us know the options available?

**Comment by dio** [comment]
@kadimulam WDYT of this: 

```
FROM centos:7
RUN yum-config-manager --add-repo https://getenvoy.io/linux/centos/tetrate-getenvoy.repo
RUN yum install -y getenvoy-envoy
ENTRYPOINT ["/usr/bin/envoy"]
```

https://www.getenvoy.io/install/envoy/centos/?

**Comment by kadimulam** [comment]
@dio , we tried this and it works; but we are not allowed to connect to the repo - https://getenvoy.io/linux/centos/tetrate-getenvoy.repo due to security concerns. Is there a way we can download the repo binary and then install it?

**Comment by dio** [comment]
By reading the [.repo](https://getenvoy.io/linux/centos/tetrate-getenvoy.repo) file, I think you can browse the available rpms for stable releases here: https://tetrate.bintray.com/getenvoy-rpm/centos/7/x86_64/stable/Packages

**Comment by kadimulam** [comment]
@dio , thanks for sharing the location. We will try and let you know.
