### ISSUE TITLE
CI/tools: Format checker is not deterministic

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#10242]
During the format checker step of CI for https://github.com/envoyproxy/envoy/pull/10230, the tool doesn't deterministic output.

In one commit, it suggests:
![](https://user-images.githubusercontent.com/1109246/75825544-6f104b00-5d5a-11ea-9f08-2210b5137c24.png)

After applying the patch, it then fails again:
![](https://user-images.githubusercontent.com/1109246/75825591-83ecde80-5d5a-11ea-82a8-1b3c419734de.png)

[Apparently this has happened multiple times](https://github.com/envoyproxy/envoy/pull/10230#issuecomment-594203152) in other PRs, so opening an issue to track the effort of fixing this.

**Comment by mattklein123** [comment]
cc @htuch @lizan
