### ISSUE TITLE
allow changing trace propagation for mirrored traffic

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10257]
It appears that mirrored traffic receives a hard copy of the headers together with all the tracing headers. I think we need to allow:
- opting out from tracing for mirrored traffic
- spans should not always be shared between the mirrored and the original request (e.g. if a span is opened, it should be opened twice)

Ref: https://github.com/istio/istio/issues/21700

**Comment by mattklein123** [comment]
SGTM

**Comment by kyessenov** [comment]
I can work on this.
