### ISSUE TITLE
Proposal: add response flag for direct response

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10255]
We use a route action to return a custom error code (not 404) for when the route is not found. We would like to see that the route action was selected in an access log extension. The proposal is to add a response flag to indicate that a direct response action was chosen (for both HTTP and TCP), similarly to how NR would be used if it allowed non-404 response code.

**Comment by snowp** [comment]
You should be able to tell by looking at the `responseCodeDetails` value on `StreamInfo` from within your extension (it would say `direct_response`). Would that work for you?

**Comment by kyessenov** [comment]
Yeah, that works. Is there a principle when to use response flags vs response details?

**Comment by snowp** [comment]
In my mind response flags is a list of events that occurred during the stream (e.g. you can have UF,URX if you go upstream failures + exceeded retry count), while response code details is specifically what triggered that status code.

**Comment by kyessenov** [comment]
OK, in that case response code details seems like the right option. Thanks!
