### ISSUE TITLE
Conditionals in the access log

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10269]
We would like to report downstream and upstream TLS properties in the access log. Istio only allows a single format string for all proxies, so it would be nice to have a conditional in the access log depending on the traffic direction as a condition.

**Comment by mattklein123** [comment]
@kyessenov can you put together a design proposal for this? It's not clear to me how this is going to work.

**Comment by kyessenov** [comment]
I have a couple of ideas:

1. Add `%COND(X, Y Z)%` that evaluates `X` first before deciding whether to output `%Y%` or `%Z%`. I think this would require adding a bunch of indicator variables to report on traffic direction and whatnot.

2. Add another expression-based access log filter. Using CEL would be easy since we already have a context defined.

**Comment by mattklein123** [comment]
We already have `%REQ(X?Y):Z%` and similar. cc @zuercher to advise who I think has the most design intuition on the access logging stuff.

**Comment by mandarjog** [comment]
@kyessenov we can do this, however it seems we should really support differentiation of access logs in Istio.
