### ISSUE TITLE
Upgrading lightstep tracer version + making propagation mode configurable

### ISSUE THREAD

**Issue by spiliopoulos** [envoyproxy/envoy#10273]
*Description*:
This is a feature request. Right now envoy is using a very old version of the lightstep cpp tracing library that only supports 2 propagation modes that do not include b3 propagation. It would be great if we could upgrade the library to get access to more propagation mode and make selecting the propagation mode user configurable. This will enable developers to select the propagation mode that fits their environment. This seems also inline with the opinions expressed in https://github.com/envoyproxy/envoy/issues/1711#issuecomment-331664138

updating is also tracked in https://github.com/envoyproxy/envoy/issues/7363 but this feature request also includes the ability to make the tracers propagation mode user configurable.

**Comment by rnburn** [comment]
I have a PR in progress to update the LightStep tracer (https://github.com/envoyproxy/envoy/pull/10152)

I plan to follow on with another PR to make the propagation mode configurable.
