### ISSUE TITLE
http: add max stream time

### ISSUE THREAD

**Issue by markozhen** [envoyproxy/envoy#10274]
Hello. We're trying to terminate downstream http2 connections periodically using max_connection_duration. The goal is, for long-lived streaming requests, to have clients select a new upstream host after max_connection_duration has elapsed, and therefore balance new and existing client connections as the backing application scales out.

After some testing, I've noticed that when there are active streams, the connection does not terminate and instead sits in draining-closing state indefinitely until the streams finishes or idle timeout.

For busy streaming requests which never end, this leaves a lingering connection. I expect streams to get reset after the drain sequence and fully close when max_connection_duration is reached.

Looking at the http conn manager, it appears that calling `resetAllStreams()` after the drain sequence should work. An alternative idea would be to add a configurable upper bound to stream duration.

We'd be happy to work on a PR for this, and would welcome some input on the preferred approach.

**Comment by euroelessar** [comment]
`max_connection_duration` is expected to be used purely for graceful termination flow with zero availability hits.
Did you consider using `HttpConnectionManager.request_timeout` to limit lifetime of individual requests?

**Comment by markozhen** [comment]
We've tested `request_timeout` with a bidi grpc stream and it does not work. Specifically, the timer gets disarmed on the first response message from upstream (in [conn_manager_impl.cc#L1527](https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L1527))

Additionally documentation [here](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts) suggest that `request_timeout` is "not compatible with streaming requests".

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts for a discussion of how to configure stream timeouts that will work for streaming requests.

**Comment by markozhen** [comment]
@mattklein123  We've reviewed the linked documentation, however, none of the discussed points enables us to limit the max duration / lifetime of a stream. For a busy bidi stream, it will never hit the `stream_idle_timeout`. Moreover:
- `request_timeout` is disarmed (see above)
- route `timeout` is disabled (`onRequestComplete()` not called in router.cc when end_stream=false)
- connection `idle_timeout` doesn't reset streams

**Comment by mattklein123** [comment]
OK I see. Yes we would need to add a new timeout around max total stream time or something like this. I will mark this a help wanted feature request.

**Comment by Shikugawa** [comment]
@mattklein123 I will help you if there is no person working on this. Would you mind to assign me?

**Comment by nitgoy** [comment]
> `max_connection_duration` is expected to be used purely for graceful termination flow with zero availability hits.

If this is true, then the documentation of [max_connection_duration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-max-connection-duration) seems inaccurate since it mentions force-close of the connection in certain circumstance.

> If the connection is a downstream connection and there are any active streams, the drain sequence will kick-in, and the connection will be **force-closed** after the drain period. See [drain_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-drain-timeout).
