### ISSUE TITLE
Lua: timestamp in millis/ns

### ISSUE THREAD

**Issue by mindyor** [envoyproxy/envoy#10282]
*Description*:
We want to record timestamps in a Lua filter so that we know when requests and responses occur (and eventually derive the duration).
It appears Lua doesn't have a function to do this - os.time provides current time, but only at seconds, not millis or ns. os.clock provides a timestamp, but only for time spent in Lua.

Maybe something like `request_handle:timestamp`?

*Relevant Links*:
https://stackoverflow.com/questions/463101/lua-current-time-in-milliseconds

**Comment by dio** [comment]
cc. @vmg

**Comment by dio** [comment]
Should we reopen https://github.com/envoyproxy/envoy/issues/8461?

**Comment by snowp** [comment]
I think exposing a straight up high precision timestamp function would be fine, though now that I see #8461 I realize there's a bunch of gotchas around the timings as @vmg points out in his detailed post. 

I think in theory exposing an `upstreamTiming()` function that yields until `end_stream=true` has been seen (to ensure that the router has populated the timings) would be a fairly elegant solution if all we're looking for is the upstream request duration. It would be a bit more complicated to implement, but doesn't carry the same uncertainties about what point in time of the stream you're actually timing.

I can also see the argument for just exposing the simple timestamp function for its utility, it is a bit more flexible. 

WDYT?

**Comment by dio** [comment]
I think we can start with adding a simple timestamp function.

**Comment by mattklein123** [comment]
I also agree that we can just add a high resolution timestamp function. It should be simple and it would allow the filter to gather its own timing information in typical cases. I agree there are likely better ways of tackling the holistic stream timing problem, but that seems a lot more complicated to solve and I think that can be done orthogonally. I did reopen that issue though and marked it help wanted.

**Comment by snowp** [comment]
SGTM, sounds like we can handle this as two separate issues. @mindyor were you planning on adding this function or should I mark this as help wanted?

**Comment by mindyor** [comment]
Happy to add the function. Thoughts on the API? Not sure if `StreamHandleWrapper` is the right place to put the function.

**Comment by snowp** [comment]
I think it makes as much sense to have this function on `StreamHandleWrapper` as some of the other existing calls, I don't think there's a need to try to introduce a new class yet.
