### ISSUE TITLE
Add Via header for proxied requests

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1030]
As per https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html 14.45:

"The Via general-header field MUST be used by gateways and proxies to indicate the intermediate protocols and recipients between the user agent and the server on requests, and between the origin server and the client on responses. It is analogous to the "Received" field of RFC 822 [9] and is intended to be used for tracking message forwards, avoiding request loops, and identifying the protocol capabilities of all senders along the request/response chain."

**Comment by mattklein123** [comment]
I think this should be an optional / config driven behavior. It's fairly common that users want to hide the backend servers and overwrite the server header (and not have via). So it seems like we should provide both options.
