### ISSUE TITLE
Feature request: Histogram for header sizes

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#10308]
Would be nice to enrich existing stats with histogram for header sizes per upstream. 
Can work on this feature if it's something we want to add.

**Comment by mattklein123** [comment]
cc @jmarantz @adisuissa this might be useful for header map optimization work?

**Comment by jmarantz** [comment]
Assigning to @nezdolik for now, possibly to be re-assigned later.

**Comment by twisted-sres** [comment]
Hi, I would love to work on this. @nezdolik can you please tell me how to get started. Thanks :-)

**Comment by nezdolik** [comment]
@sresthas this issue has been submitted as proposal for cncf mentorship project: https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md#enrich-envoy-stats-with-header-size-histogram.
How about this issue, is very similar: https://github.com/envoyproxy/envoy/issues/3621

**Comment by Dhiraj240** [comment]
@nezdolik I would like to work on it during the mentorship. Can you assign me a similar issue?

Also, may I know the common chat channel to discuss more?

**Comment by Dhiraj240** [comment]
@nezdolik  Any updates, I have been waiting on how to get started and discuss with you.

**Comment by nezdolik** [comment]
Hi @Dhiraj240 not sure i understand, here is schedule: https://github.com/cncf/mentoring/tree/master/communitybridge/2020/q2 and you need to apply as mentee.

**Comment by Dhiraj240** [comment]
@nezdolik For selection, is contribution necessary in envoy?

**Comment by nezdolik** [comment]
@Dhiraj240 is not required, for more questions you could reach out on slack not to spam issue thread.

**Comment by Dhiraj240** [comment]
@nezdolik  I have applied on community bridge and messaged you on slack for more information. You can check my portfolio here at https://dhiraj240.github.io/
