### ISSUE TITLE
Better handle v2/v3 split in docs search

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#10311]
When searching the docs all the protobuf entries show up twice with little indication that one is V2 and the other is V3 (besides a small reference in the preview text):

![image](https://user-images.githubusercontent.com/2023366/76282111-fcb8d280-6253-11ea-86a1-07f4e2c18707.png)

(https://www.envoyproxy.io/docs/envoy/latest/search.html?q=cluster&area=default#)

It would be nice to better indicate what the difference between these results are

**Comment by htuch** [comment]
I think going beyond this, we also need to rethink how docs are organized for v2/v3. As we move towards a world in which there are v2/v3/v4alpha and some package namespaces are still only at v2, there's no good reason to keep labeling the API DAG with a single version in the docs tree.

I would like to see some structure in which each package appears once, and then provides access to the range of versions at the next level. 

This is further complicated though by files moving across package namespace between versions and implies a logical API organization similar to what we do today by hand in the docs tree.
