### ISSUE TITLE
Blocking log filters

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10326]
We would like to hold loggers until a remote call completes. Ideally, `log` callback could return a stop iteration status, and the Envoy suspends stream deletion until the blocking logger triggers the completion. The actual data plane request does not need to be suspended. The use case is a logging filter that needs to receive a response from another (remote) logging filter.

**Comment by mattklein123** [comment]
@kyessenov can you expand a bit? If the data plane request is not being suspended, why does the logger have to hold stream destruction? Can we just hold stream info by shared_ptr if not already done?

**Comment by kyessenov** [comment]
The underlying stream can be destroyed. We want to keep the filter state since that's how remote loggers communicates with the local logger. Basically,
1. logger A makes an RPC, returns StopIteration.
2. logger A receives a completion callback, writes status into filter state, calls continue.
3. logger B starts, reads the filter state, and writes a log.

**Comment by mattklein123** [comment]
This will be a substantial project. Please write a design proposal before working on this. Thanks!

**Comment by mandarjog** [comment]
This is going to be a great enabler for this type of use case. Was there a specific reason why log phase does not do StopIteration?

**Comment by mattklein123** [comment]
> Was there a specific reason why log phase does not do StopIteration?

Because it's more work to implement and it has never been requested before. :)

**Comment by kyessenov** [comment]
A single access log filter can perform async work by holding onto some state post-request. But this doesn't compose well when there are many access log filters. For example, the first access log filter may fetch some additional metadata out-of-band, that can be used by the second access log filter. This coordination needs some API support.
