### ISSUE TITLE
Explicit v2/v3 versioning in YAML/JSON files

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10343]
After the recent v3 cut, Envoy attempts to upgrade to v3 any unparseable v2 config. This leads to v3 related messages to config that the user intends as v2, a bad UX. There are a few options to make this explicit:

1. Allow version to be included in the filename, e.g. `foo.v2.yaml`, `bar.v3.yaml`.

2. Add a CLI flag to Envoy to imply an explicit version for bootstrap JSON/YAML (and others?)

CC @snowp

**Comment by SecurityInsanity** [comment]
FWIW I think Option #2 here is by far the better option. I've definitely seen some people use: `.v2.yaml` in reference to the version of the file placed on disk through whatever generated the file. Don't think it's safe to rely on that.

**Comment by snowp** [comment]
I also like #2, let me see if I can get a PR up for this

**Comment by htuch** [comment]
I think #2 is fine for bootstrap. For file-based xDS, we probably want to make use of the resource API version present in `ConfigSource`.
