### ISSUE TITLE
Move from ratelimit.proto to rls.proto

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#1034]
As part of the V2 API work we have renamed ratelimit to RLDS (RateLimitDiscoveryService) and moved the proto to envoy-api.

@htuch will do the work to consume envoy-api into envoy.
@junr03 will do the work to migrate envoy to use rlds.proto instead of ratelimit.proto

**Comment by mattklein123** [comment]
@junr03 this is a good one for James to work on when he starts in Feb. Can you give him the context on this?

**Comment by mattklein123** [comment]
@junr03 can we get this completed as part of the RL work in Q2? Would be nice to get this cleaned up as it causes confusion.

**Comment by htuch** [comment]
This is now RLS rather than RLDS.

**Comment by mattklein123** [comment]
Renamed issue to indicate RLS

**Comment by junr03** [comment]
Yeah I can take this. I talked to @jsedgwick and he is ok with the switch.

**Comment by lvijay** [comment]
Hi @junr03 any progress on this?

**Comment by lvijay** [comment]
Thanks @junr03!
