### ISSUE TITLE
tracers: Upgrade opentracing-cpp to 1.6.0

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#10345]
*Description*:
Current opentracing-cpp version is 1.5.1 which is a patch release of 1.5.0 that was released on June 20, 2018.

Version diff is https://github.com/opentracing/opentracing-cpp/compare/v1.5.1...v1.6.0 and release notes are:
- Support cloning span contexts
- Add optional accessors for trace-id/span-id
- Fix windows build issues
- Support string_views in opentracing::Value
- Add more flexible logging APIs

May be related to https://github.com/envoyproxy/envoy/issues/10273. /cc @rnburn

**Comment by rnburn** [comment]
It's not necessary for #10273
