### ISSUE TITLE
Allow headers removal for External Authorization filter

### ISSUE THREAD

**Issue by fpliu233** [envoyproxy/envoy#10351]
*Allow headers removal for External Authorization filter*: *Authorization server needs to redact the credentials issued by itself to avoid credential harvesting*

*Description*:
>Currently External Authorization only support header append and replacement. Authorization server response can't instruct External Authorization filter to remove headers which contains credentials. Removing credentials is important to prevent passing them to backend applications, which can be used to harvest credentials.

**Comment by dio** [comment]
I assume this is related to [`AuthorizationResponse`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#config-filter-http-ext-authz-v2-authorizationresponse) for the ext_authz configure to talk to [`HttpService`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#config-filter-http-ext-authz-v2-httpservice) as authorization server?

**Comment by fpliu233** [comment]
And the gRPC service https://www.envoyproxy.io/docs/envoy/latest/api-v2/service/auth/v2/external_auth.proto#service-auth-v2-checkresponse as well. We use gRPC.

**Comment by fpliu233** [comment]
I found the filter actually already does that.
