### ISSUE TITLE
Block requests to a certain endpoint

### ISSUE THREAD

**Issue by hsw48** [envoyproxy/envoy#10360]
I want to block all requests to a certain endpoint at the proxy layer to prevent them from reaching my server. Specifically all /favicon.ico requests. I haven't found anything that directly does what I'm looking for even though it feels like something that envoy would be perfect for.

Right now my first attempt is routing the "/favicon.ico" prefix to a cluster with the only configuration as: "max_requests_per_connection: 0".

That seems like a roundabout way of doing something I think there would be a more straightforward solution to. Thanks.

**Comment by ggreenway** [comment]
I think you can add a route to this prefix/URI of type direct_response (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=direct_response#envoy-v3-api-msg-config-route-v3-directresponseaction) and return whatever you want there, maybe a 404? Does that accomplish what you're hoping?
