### ISSUE TITLE
Blackhole support in the dataplane

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#10364]
Use case:
Istio has a concept of blackhole destination which is equivalent to a `NR` response_flag.
Since the user is trying to send requests to a destination that the configuration makes impossible to route to, it is important to gather metrics when this situation happens.

`NR` is automatically set by tcp_proxy, and router. Http router then uses localReply to set the configured http response code. 
Since automatic `NR` does not provide enough control, Istio implemented `NR` for http by having a default route with `localReply`, which gives us more control. However this method is missing the response_flag.

Proposal:
Add `response_flag` param to direct response. 
```yaml
 directResponse:
      "status": 502
      "response_flags": ["NR"]
```
This is straight forward. We will also add it to tcp_direct response.

This way all log filters can uniformly know that a particular request could not be routed due to `missing route`

@kyessenov 

- [ ] Add `response_flags` to http directResponse.
- [ ] Add `response_flags` to direct response network filter.

**Comment by kyessenov** [comment]
Note that there is no notion of a route in network filters.

**Comment by mandarjog** [comment]
@kyessenov tcp proxy does still use “NR” to express the abstract concept that “I could not do anything “ with this request . We just need to apply this uniformly.

**Comment by mandarjog** [comment]
@gargnupur
