### ISSUE TITLE
Question: Circular log file support

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#10382]
Would it be useful to take in a `max_log_file_size_kb` that ensures the log file size doesn't grow beyond that and is used in a circular mode? 

We are interested in collecting debug logs as those seem to be most useful in problematic situations, but always configuring envoy to collect them is impractical due to the volume.

**Comment by mattklein123** [comment]
Which logs are we talking about? Application logs or access logs?

**Comment by sumukhs** [comment]
Not sure what the difference is between the 2 you are referring to. 

I am referring to the log which is generated by envoy as part of the "log-path" command line argument

**Comment by mattklein123** [comment]
One is HTTP/filter access logs, one is the Envoy app log. You are talking about the Envoy app log. @ggreenway @jmarantz any thoughts on this? My feeling is this would be better accomplished with logrotate or similar to keep Envoy simple in this regard?

**Comment by ggreenway** [comment]
I agree with using logrotate or similar. There are several unix tools that can be used, with somewhat rich configuration. I don't think we should try to re-implement those in envoy.

Alternately, you could have envoy log to stdout/stderr, and pipe to something that directly manages the data how you want.

**Comment by jmarantz** [comment]
+1

**Comment by sumukhs** [comment]
Thanks. Wasn't aware of these tools. I'll look into setting them up with envoy output log.
