### ISSUE TITLE
Bazel builds envoy error.

### ISSUE THREAD

**Issue by Unforgiven00000yasuo** [envoyproxy/envoy#10399]
Because I want to build istio from source, I have to compile envoy first.I have cloned the corresponding code.
```
git clone https://github.com/istio/proxy.git
cd proxy
```
But I encountered this error while building envoy.
![image](https://user-images.githubusercontent.com/44249297/76728496-d504c580-6791-11ea-9ea3-2570a1b2a0e6.png)

**Comment by dio** [comment]
I think you need to run:

```
$ make build_envoy
```
