### ISSUE TITLE
 xDS thread processing is slow

### ISSUE THREAD

**Issue by zyfjeff** [envoyproxy/envoy#10394]
*Title*: *xDS thread processing is slow*

*Description*:
>  The current Envoy xDS processing, Admin handler、socket data reception are the same thread, when encountered with a large cluster, xDS processing is time-consuming, this time will cause the admin interface is not available, can not receive the ping package sent by the grpc server, resulting in the connection is closed by the grpc server.

**Comment by mattklein123** [comment]
This is a fundamental limitation of Envoy's threading model. It's not that we can't make this better, but it won't be easy and will require some holistic thinking. IMO it's better right now to focus on the inflight proposals to reduce Envoy management CPU (e.g. the IEDS proposal).

cc @jmarantz
