### ISSUE TITLE
The access log performance in JSON format is very bad

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#10415]
ENV:

8c8g,
One cluster and one route,
Network of k8s,
No other http filter except router,
1000 concurrent.

Access log of JSON format:
60000+ qps

Access log of TEXT format:
90000+ qps

The test may not be detailed enough, but it is illustrative enough. In addition, the insert operation of dynamicMetadata also seems to be very expensive, but there is no special test in this part, and the results will be added after subsequent tests.

**Comment by arkodg** [comment]
@wbpcode is this issue still relevant ?
the logic b/w text and JSON looks similar in https://github.com/envoyproxy/envoy/blob/main/source/extensions/access_loggers/file/config.cc
cc @tmsnan @cpakulski
