### ISSUE TITLE
Bucket TCP Connection Pool Connections by Key

### ISSUE THREAD

**Issue by rharding6373** [envoyproxy/envoy#10423]
I'd like to use TCP connection pool, but be able to classify connections based on a key and keep them in separate buckets so that pending requests only use a new or existing connection with the same key. This is more fine-grained connection management than the TCP connection pool currently offers.

I think this feature would be generally useful to the community, and it's similar to what is done in for Http connection pools. At a high level, this request is to convert the lists of active connections and pending requests to maps with a generic key that Envoy users can provide based on their use case.

I'm happy to implement this change.

**Comment by mattklein123** [comment]
IIRC this is already basically implemented? I thought we already supported generic keying? cc @ggreenway @zuercher

**Comment by rharding6373** [comment]
Any thoughts on this issue?

I see that the cluster manager can keep multiple pools that are keyed by hashed socket options. Is there already a way to take advantage of this generic keying for protocol-specific data provided at run time? Or is there another approach that you recommend?

**Comment by zuercher** [comment]
The connection pools are keyed by priority and socket options. There isn't currently a way to maintain separate pools based on protocol-specific data. 

It should be noted, however, that each ConnPool instance is a pool of connections to a single logical upstream host. If your intention is direct upstream requests to specific groups of hosts, that's a concern for the LoadBalancer. I'd need to know more about your actual use case, but perhaps one of the consistent hashing load balancers would suit. Protocol-specific data makes it into the LB host selection algorithm via the LoadBalancerContext object. For the TCP proxy that's just connection metadata, but referring back to #10421 again, a protocol specific network filter could implement LoadBalancerContext to produce hash keys for the consistent LBs based on anything in the protocol.

**Comment by rharding6373** [comment]
Our use case is to share connections that have similar protocol-specific metadata. E.g., a connection opened for user A can be reused by future connections by user A, but cannot be reused by user B. Ideally we'd also be able to enforce constraints among these groupings of connections, e.g. all connections pooled for user A + user B can't exceed some common threshold, as well as define policy for how to "move" connections between user A and B (i.e., close a connection for one user, open one for the other).

We only have one logical upstream host. Since the protocol-specific metadata is learned at runtime, unfortunately we don't know potential values in advance that would let us use a cluster-based approach.

Today the connection pool is not an extensible part of Envoy. What do you think would be the scope of making it extensible?

**Comment by rharding6373** [comment]
Any more thought on this issue?

**Comment by zuercher** [comment]
I think you have a couple of options.

1. You could make connection pools an extension point. However, at present Envoy has 3 connection pool implementations (tcp, http, http/2). The latter two combine encoder/decoder pooling into the connection pool which allows the http connection manager to deal with requests vs. connections. Reconciling all that with extensions seems very complex.

2. I think you could make use of the custom cluster type extension point to build a custom cluster type that implements its own connection pooling. I think with a little forethought this custom cluster type could be reused for any protocol that requires pooling by connection metadata. (My not-well-researched idea would be to allow the LoadBalancerContext to provide the information used to manage the connection pooling. That would allow other protocols to use the cluster type. The custom cluster would have to register for host set updates to manage its connection pools.)

**Comment by rharding6373** [comment]
Thanks for the suggestions! I'll try out option 2 and see how that goes.
