### ISSUE TITLE
Expose TcpUpstream ConnectionData

### ISSUE THREAD

**Issue by rharding6373** [envoyproxy/envoy#10424]
I'd like to use ConnectionState to maintain persistent state during the lifetime of an upstream connection in an L4 network filter based on the tcp_proxy. My reading of the code suggests that you should get ConnectionState from ConnectionData via connectionStateTyped(), and that tcp_proxy uses GenericUpstream/TcpUpstream to store the ConnectionDataPtr. Would there be objections if the GenericUpstream/TcpUpstream API were extended to get the current ConnectionData? Is there another pattern that is typically used to assign and access ConnectionState in network filters?

I'm happy to extend the API if that is deemed appropriate for this case.

**Comment by mattklein123** [comment]
cc @ggreenway @zuercher

**Comment by zuercher** [comment]
Sorry, I thought I had responded to this, but apparently not.

This is pretty tightly coupled with #10421. If you end up writing a custom network filter, you'll end up needing to use the tcp connection pool for upstream connections and can use the ConnectionState API directly to store information about those upstream connections across downstream requests. The thrift proxy does this to keep track of protocol state that's specific to the upstream connection. 

If a generic, extensible proxy filter is written, it would have to support access to the ConnectionState in some way, but that seems relatively straightforward.

**Comment by rharding6373** [comment]
Thanks for the input and the pointer to the thrift example. Agree that the issues are tightly coupled. Given the direction of the discussion on #10421 I'm fine closing this.
