### ISSUE TITLE
Make TcpProxy::Filter a derivable class

### ISSUE THREAD

**Issue by rharding6373** [envoyproxy/envoy#10421]
I'm creating an L4 filter that shares functionality with tcp_proxy but whose behavior must differ in some significant ways for our use case, e.g. open an upstream connection after receiving data from downstream and parsing and reacting to data from upstream in application-specific ways. I'd like to derive from TcpProxy::Filter so we can reuse the functionality that's already there and override the functions where our application has touch points.

I propose making the following functions in TcpProxy::Filter virtual, in addition to making all inheritance either public or protected:
- initialize
- initializeUpstreamConnection
- onConnectTimeout
- onDownstreamEvent
- onUpstreamData
- onUpstreamEvent
- onIdleTimeout

I'm happy to make these changes.

**Comment by mattklein123** [comment]
cc @alyssawilk @zuercher @ggreenway who have worked in this area to advise.

**Comment by ggreenway** [comment]
At one point in the past, TcpProxy did use inheritance to support websockets. I don't think it is really built in a way that handles inheritance very well. I think we should look into other ways of extending it, if that's needed.

From what you've described above, it sounds like you may be able to build what you need with a combination of downstream and upstream network filters, and possibly some minor changes to TcpProxy. If not, let's talk about more specifics about what you need, and figure out the best way to move forward.

**Comment by rharding6373** [comment]
Here is a more complete list of features we're trying to accomplish:
- Open upstream connection only after receiving downstream data (i.e., don’t disable reads when filter is initialized).
- Inject data upstream when a new upstream connection opens.
- Inject data downstream when it is associated with an upstream connection.
- Inject data upstream when the downstream connection closes, before returning the upstream connection to the pool.
- Maintain some state machine associated with the upstream connection (connection state), to determine what kind of data to inject upstream or downstream.
- Use dynamic, downstream-specific data as a key into the connection pool (See issue #10423).

My current understanding of envoy network filters is that the first item would require a modification to TcpProxy, and may be a significant behavior and potentially performance change for other users. The next three might be doable in a filter after TcpProxy that can access upstream connection state and inject data to both upstream and downstream and is notified with downstream closes. This would also require changing TcpProxy, though, since TcpProxy is terminal. The fifth item might be doable via an upstream filter if the upstream connection state is accessible. The last item is dependent on how the connection pool can be managed. Is this consistent with how you would envision a filter setup for this application to work?

Alternatively, we could write our own version of TcpProxy to do all this, but we'd like to explore other options first since we anticipate this would duplicate a lot of TcpProxy code and thus be difficult to maintain.

**Comment by ggreenway** [comment]
Got it. This helps to see all this in one place.

I agree it makes sense for this to implemented as a proxy filter, given all the direct interactions between the upstream and downstream side.

My feeling is that just making the methods you listed virtual may allow you to implement your new filter, but the interface between the two will be very brittle. Everytime someone needs to change or refactor TcpProxy, you'll probably have to change/refactor your derived filter, at least if it is something you plan to maintain out-of-tree (which I assume is what you have in mind, given that you didn't refer to a specific protocol; please correct me if this is a bad assumption on my part).

@alyssawilk do you have any opinions on this?

**Comment by alyssawilk** [comment]
Yeah, I think the clean way to do this is mostly with upstream filters.   I'd suggest giving that a try and we can help out if you get stuck anywhere

* Open upstream connection only after receiving downstream data (i.e., don’t disable reads when filter is initialized).
I think this can be done with a downstream filter today, no?  I'd argue it's useful enough that we could add it  to the base class if you think that's easier and there's general agreement.

*Inject data upstream when a new upstream connection opens.
Sounds like an upstream filter to me.

*Inject data downstream when it is associated with an upstream connection.
I think an upstream filter could do this too.

*Inject data upstream when the downstream connection closes, before returning the upstream connection to the pool.
I think an upstream filter can do this if you have half close enabled (so the close doesn't just clean up the whole connection).  We don't return connections to the pool anyway just for reference

* Maintain some state machine associated with the upstream connection (connection state), to determine what kind of data to inject upstream or downstream.
Could be in the custom filter for sure.

Use dynamic, downstream-specific data as a key into the connection pool (See issue #10423).
presumably could set or get this in streaminfo if your filter doesn't have access to the information you need.

**Comment by rharding6373** [comment]
After playing with upstream filters for a few days, I managed to do most of the kinds of upstream/downstream communication tasks we need. However, connection re-use is still an issue. Is there a way to make tcp_proxy reuse connections?

If not, it sounds like we will want to replace tcp_proxy with our own listener filter, as we'd like to take advantage of the built-in connection pool, but certainly don't want to rely on a brittle interface.

**Comment by ggreenway** [comment]
I think you've hit the limits of what tcp_proxy does. It is the protocol-agnostic proxy, intentionally not understanding the underlying protocol or message boundaries, so it doesn't have any support for connection re-use.

**Comment by alyssawilk** [comment]
Yeah, I think that's the one gotcha.  I could see subclassing for that - I think it'd be fine to add the concept of reuse to the tcp connection pool, but some entity would need to do the framing and handle connection reuse and I think at that point subclassing or doing a custom filter might make sense depending on how much of the existing code is usable.
