### ISSUE TITLE
May StreamInfo::FilterState::Object add a virtual method of serializeAsString?

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#10430]
In most cases, StreamInfo::FilterState::Object only store some simple values just like a string or number. Although serializeAsProto is very flexible, it is also relatively more complicated. It will be very helpful to provide a serializeAsString for the serialization of some simple value. Especially when recording access logs, it is unnecessary overhead to convert string/int to proto and then from proto to string.

**Comment by mattklein123** [comment]
Seems fine to me. @htuch @lizan ?

**Comment by lizan** [comment]
We already have such object that serialize as protobuf well known type:
https://github.com/envoyproxy/envoy/blob/master/source/common/stream_info/uint32_accessor_impl.h
https://github.com/envoyproxy/envoy/blob/master/source/common/router/string_accessor_impl.h

This will also automatically converted to right type in JSON access log. I don't think we need a serializeAs* methods for each type, unless there's a critical performance reason to do that.

**Comment by kyessenov** [comment]
I had some [luck](https://google.github.io/flatbuffers/) using [flatbuffers](https://google.github.io/flatbuffers/). I think proto serialization was taking >50% of CPU overhead in Wasm ABI, so we're avoiding it like a plague on the interface.
If we can agree to use flatbuffers as the format for filter state, that would be wonderful.

**Comment by htuch** [comment]
I'd probably want to see some application where adding flat buffers to Envoy is going to really pay off to justify having competing proto-like implementations. We always will have proto for xDS, I wish we could make that faster (xDS updates can sometimes dominate CPU on the main thread at scale).

Re: @wbpcode's question, I guess, why not, but again, it seems like something you want to do when you learn that this encoding is really performance critical, otherwise just use the constructs @lizan suggests, which are pretty convenient.

One thing to keep in mind is that there are many other access logger implementations than Envoy's gRPC or filesystem access log sinks. Some of these benefit from having proto as they are dumping their logs over gRPC. That said, for trivial scalar values, that doesn't matter.

**Comment by kyessenov** [comment]
Proto and flatbuffers don't serve the same purpose. You can put flatbuffer into protos as `bytes`. Wasm ABI really needs something more performant than protobuf for runtime data exchange, so I'd advise against using protobuf for runtime representations. Protobuf is perfectly suitable for RPCs.

**Comment by htuch** [comment]
@kyessenov can we cheaply (de)serialize into JSON flat buffers? My main worry is that in places where runtime representations become wire representations (e.g. custom gRPC access log), we're adding another layer of serialization and another Envoy dependency. We can do this, but we better have a strong motivating use case. Flat buffers also become a security critical dependency as they are on the data plane.

**Comment by kyessenov** [comment]
AFAIK there's no full JSON support. The library is very small (just one header file).

**Comment by wbpcode** [comment]
> We already have such object that serialize as protobuf well known type:
> https://github.com/envoyproxy/envoy/blob/master/source/common/stream_info/uint32_accessor_impl.h
> https://github.com/envoyproxy/envoy/blob/master/source/common/router/string_accessor_impl.h
> 
> This will also automatically converted to right type in JSON access log. I don't think we need a serializeAs* methods for each type, unless there's a critical performance reason to do that.

Really because of performance. In our actual use, I found that JSON format logs reduced qps by 1/3. An important reason is the conversion from proto to JSON. In addition, when I use dynamicMetadata to store some simple data, I find that it is also expensive. FilterState was used to replace dynamicMetadata, which was a significant improvement.

**Comment by htuch** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/10665
