### ISSUE TITLE
Idea: Make the Envoy documentation printable

### ISSUE THREAD

**Issue by thylong** [envoyproxy/envoy#10444]
*Title*: *Make the Envoy documentation printable *

*Description*:
>We're numerous locked at home for a while. Despite being a huge constraints, it's an opportunity for all of us to invest our time in value OSS projects like Envoy.
>
>Having a printed version of the documentation would help to turn off the screen and concentrate better on the content of this documentation.
>
>Can we consider adding a PDF generation button or something on the documentation?
>
>Thanks a lot for the project !

**Comment by mattklein123** [comment]
Sure. PRs welcome.
