### ISSUE TITLE
Discussion: reopen log files without hot restart envoy

### ISSUE THREAD

**Issue by caitong93** [envoyproxy/envoy#10450]
*Title*: *Reopen log files without hot restart envoy*

*Description*:

I'm trying to use logrotate + hot restarting envoy to dealing with increasing envoy access logs.
And I have read https://github.com/envoyproxy/envoy/issues/1109 . 
My concern is that frequent hot restarting affect performance (we use envoy as API gateway), and wonder if envoy can implement a more lightweight approach (like what nginx do, receive a signal and just reopen log files).

**Comment by mattklein123** [comment]
This is already implemented. Send SIGUSR1 IIRC.

**Comment by caitong93** [comment]
Thanks! My missing when reading docs.
