### ISSUE TITLE
Question: is there a filter that routes based on grpc request message value?

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#10451]
I am experimenting with gRpc apis via envoy and figured that routing based on paths is pretty rigid because grpc always sets the path to packagename.servicename/methodname. 

Header metadata matching is something I could use, but is there a way to specify matching routes based on some string matching (regex or equals or prefix) to a field value in the message format of the body in the request? 

If not, would it be a simple filter to add in mainline if it sounds like something useful?

**Comment by mattklein123** [comment]
Routing on the message contents requires having access to the message descriptor. This is a general topic that we do want to start figuring out for a variety of different use cases (tap, envoy mobile, etc.) but there is no easy answer here.

**Comment by sumukhs** [comment]
Doesn't the proto descriptor set already have the message description? We provide that as an input the transcoder. Isn't it a similar mechanism?

Or the other idea was to convert the incoming message to json and route based on the key value matching. I can see how this is not efficient though.

**Comment by mattklein123** [comment]
The grpc-json transcoder has the descriptor loaded into it. So yes, if you have the descriptor, it would be possible to do this. See https://github.com/envoyproxy/envoy/issues/6109
