### ISSUE TITLE
Debugging Envoy Code

### ISSUE THREAD

**Issue by MOURYA00** [envoyproxy/envoy#10465]
I am new to Envoy proxy, I started to learn about it, gone through the documentation.
I wan to understand the code in depth, so usually the best way to understand any code is by debugging it, I downloaded the envoy code and using visual studio as editor, I don't know how I can debug the code, like marking debug points and get the code hit at that break point.
I searched a lot, what I found is, building envoy using Bezel, but I want a way to debug it. 
Is there any other way I can do debugging and proceed to understand the code flow.

**Comment by cpakulski** [comment]
The following method works for me:
- build the static image with symbolic information:
    `bazel build -c dbg //source/exe:envoy-static`
- use debugger to load the image, set breakpoints and run Envoy:
    `gdb --args bazel-bin/source/exe/envoy-static -c <your-config-file>`
- to run Envoy without debugger:
    `bazel-bin/source/exe/envoy-static -c <your-config-file>`
If it crashes, `core` file is produced (on Linux) which you can load into gdb and inspect calling stack, local variables, etc.

**Comment by lizan** [comment]
I have my half baked `devcontainer` [here](https://github.com/lizan/envoy/commit/83cc3cba6171909cfcbfb64a368f399152fd264e), if you use VSCode you may find it useful. Will upstream when I have more bandwidth.

**Comment by MOURYA00** [comment]
Hi @cpakulski and @lizan ,Thanks for the reply, it was helpful for me to go further for debugging, but I found little difficult for me to understand the bazel, because many time while reading about the bazel, I found that it is better to use bezelisk instead of bazel, please share with me if you have any tutorial that you had found helpful to understand bazel. Thanks again.

**Comment by cpakulski** [comment]
I agree that using bazel does not come easily. Official documentation is probably the best place to find answers: https://docs.bazel.build/versions/master/bazel-overview.html. There is also bazel channel in Envoy's slack where you can ask specific questions.

**Comment by farah** [comment]
Hi @cpakulskim.

> The following method works for me:
And run Envoy:
>   `gdb --args bazel-bin/source/exe/envoy-static -c <your-config-file>`

What is the config file? 

When I run without it i get

```
envoy$ bazel build -c dbg //source/exe:envoy-static
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/farah/envoy/tools/bazel.rc
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=181
INFO: Reading rc options for 'build' from /Users/farah/envoy/.bazelrc:
  'build' options: --workspace_status_command=bash bazel/get_workspace_status --experimental_local_memory_estimate --experimental_strict_action_env=true --host_force_python=PY3 --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --action_env=BAZEL_LINKOPTS=-lm --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 --javabase=@bazel_tools//tools/jdk:remote_jdk11 --enable_platform_specific_config --define absl=1 --action_env=CC --action_env=CXX --action_env=LLVM_CONFIG --action_env=PATH --test_env=HEAPCHECK=normal --test_env=PPROF_PATH
ERROR: Unrecognized option: --enable_platform_specific_config
```

Really would like to get debugging with breakpoints working, preferably on MacOS.

**Comment by lizan** [comment]
@farah you have too old version of bazel, make sure you use bazelisk.
