### ISSUE TITLE
Cookie-based Session Affinity not respected across paths

### ISSUE THREAD

**Issue by PinchasLev** [envoyproxy/envoy#10468]
*Title*: *Cookie-based Session Affinity not respected across paths*

*Description*:

Multiple routes being configured for a service because some settings such as IdleTimeout need to be different.  Though, the desired behavior is that session-affinity would be preserved across all paths.   The approach taken was to set *route.routeAction.HashPolicy.Cookie* on each of the routes, setting the *name* and *path* fields to identical values.
After noticing that session-affinity would not always be kept, especially following a pod was killed and a replacement was restarted, or when the cookie expired and the ensuing request to that pod would not maintain session-affinity across paths, we tried another configuration based on comments in the Envoy codebase.  That approach doesn't set the *path* field at all and sets the *ttl* to 0.  That didn't either work.

With a broader question I'd like a clarification of the two modes for cookie-based hashing, as mentioned in the docs: generated and passive.  Is the generated mode invoked only when the upstream service doesn't set a cookie?

Another related question is, what concerns, if any, do we need to worry about when the upstream service sets cookies, in addition to those set by Envoy, given the values in the  *route.routeAction.HashPolicy.Cookie* protobuf?

*Repro steps*:

I'll add the repro steps as I get them from the user.

*Config*:

Envoy is being configured via Contour

  routes:
  - match: /
    timeout: 10m
    hashPolicy:
    - cookie:
        name: affinity
        path: /
        ttl: 60s
      terminal: true
    perFilterConfig:
      envoy.filters.http.ip_allow_deny:
        allow_cidrs:
           <xx.xx.xx.xx>
    services:
    - idleTimeout: 1m
      name: foobar
      port: 80
      strategy: RingHash
  - match: /content/whatever
    timeout: 60m
    hashPolicy:
    - cookie:
        name: affinity
        path: /
        ttl: 60s
      terminal: true
    perFilterConfig:
      envoy.filters.http.ip_allow_deny:
        allow_cidrs:
            <xx.xx.xx.xx>
    services:
    - idleTimeout: 1m
      name: foobar
      port: 80
      strategy: RingHash

I've also tried configuring Envoy with eliminating the *path* and setting *ttl* to 0s for both cookie settings, above, but to no avail.

*Logs*:
I hope to provide the relevant logs

**Comment by mattklein123** [comment]
cc @alyssawilk who I think is familiar with the cookie hashing code.

**Comment by alyssawilk** [comment]
caveat, I'm not terribly familiar with the cookie hashing, but poking around:

I assume your questions about generated / passive come from here:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-routeaction-hashpolicy-cookie
Looking at the proto docs, it looks like setting TTL is what gets you to go from only passive to generated.

Looking at where we add cookies,

https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.h#L363

    // The cookie value should be the same per connection so that if multiple
    // streams race on the same path, they all receive the same cookie.
    // Since the downstream port is part of the hashed value, multiple HTTP1
    // connections can receive different cookies if they race on requests.

So it's expected that there be some initial races, where you thrash around.  If you set the cookie TTL to 0, imagine that would become much worse as you regularly had clients assigned new cookies.   I'd think that if you had consistent upstreams across multiple Envoys that once you stabilized on a single cookie it would route consistently for the lifetime of the cookie, so if you set a TTL of 60s you should see 60s  stable routing behavior.  Is that not what you're seeing?

**Comment by PinchasLev** [comment]
Yes. We were seeing 60s of stable routing behavior and it broke down afterwards.  As mentioned earlier, affinity broke down once the ttl expired or the connection was moved to another pod.

I'm looking to verify whether *generated* mode, is what will ensure session-affinity even for requests matching different routes?

**Comment by alyssawilk** [comment]
Having different routes shouldn't affect how generated mode works - the hash should be the same assuming the client connection is the same (which may not be true for HTTP/1.1 even with the same route, given it would often have multiple connections with multiple ports)
If you want longer stable routing I think you can just increase your TTL then?

**Comment by PinchasLev** [comment]
Thanks for raising that point, regarding client connections potentially not being the same.  I'd need to investigate that in greater depth.  Though I'd need to know what fields are included in the hash.

Well, when you say the connection isn't the same, would that matter if the the request is presenting the cookie?  Or are saying that a new connection wouldn't--by definition--be presenting the cookie, and the generated cookie will be different given that different fields are being fed into the hashing function?

And yes, the user seems to be achieving longer stability by changing the TTL from 60s to 0.

**Comment by alyssawilk** [comment]
The hash is based on the four tuple, which includes the downstream port.
For HTTP/1.1 browsers generally open a number (6+) connections to a destination, each of which has its own distinct port.  That's the early race bit. Once the cookie is set it persists for the lifetime of the cookie, but if it is set to expire in 60s it's highly likely (if browser based, so with many connections) that the new cookie you get will be the same as the first.  Make sense?

**Comment by PinchasLev** [comment]
Alyssa, it makes sense, except that I find the *proto* confusing given that--based on what you're saying--only the *TTL* has any bearing, so why do does the *proto* include *name* and *path* fields?  How are those fields used in cookie-based session-affinity?

**Comment by alyssawilk** [comment]
The TTL has bearing on the lifetime and the generated hash (where the cookie directs to).  The path and the name affect the scope of where the cookie is used.  If "foo" cookie is used for path /foo and "bar" cookie is used for path /bar, each will end up with their own cookie, and due to the aforementioned HTTP/1.1 race they likely won't end up with the same hash, and the "foo" cookie wouldn't be sent on requests to "/bar"

**Comment by dio** [comment]
cc. @rshriram
