### ISSUE TITLE
HTTP Connection manager documents `request_timeout` as an idle timeout

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#10481]
*Description*:

The `HttpConnectionManager.request_timeout` is documented as:

> A timeout for idle requests managed by the connection manager. The timer is activated when the request is initiated, and is disarmed when the last byte of the request is sent upstream (i.e. all decoding filters have processed the request), OR when the response is initiated. 

The second sentence describes an active request, but the first sentence says this is a timer for "idle requests".  Maybe this language can be clarified?

*Relevant Links*:
>Any extra documentation required to understand the issue.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html

**Comment by mattklein123** [comment]
Yes the idle part is wrong. Doc PR appreciated. Please also reconcile with https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts

**Comment by jpeach** [comment]
Thanks for the confirmation @mattklein123. I should be able to send a PR later in the week.
