### ISSUE TITLE
Long compile times

### ISSUE THREAD

**Issue by ripread** [envoyproxy/envoy#10485]
Hey Envoy,

I'm trying to write a filter for Envoy to render HTML pages. I downloaded the echo2 filter example but the compile times take so long on my machine! After around 6 hours I had only completed 6/150 integration tests and things were still compiling. I don't need to build all of Envoy. I can build the library as a .so and load it into the prebuilt Docker.

- Am I doing something wrong?
- Is there a way to build filters without building all on Envoy?

**Comment by SecurityInsanity** [comment]
Hey @ripread ,

Envoy builds in extensions to the resulting binary through static linking. There's no way to dynamically load a `.so`. Though you probably don't need to run all of envoy integration tests for your filter. Ideally you'd only run the integration tests for your specific filter. However, you'd still need to run a build of envoy which will probably still take awhile if your progress on integration tests is a good indicator.

That being said I'd recommend using one of the other extension mechanisms for just rendering HTML.

- You could use LUA: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter (which seems like the most ideal right now based off of the limited information).

- Or if you wanted to be more on the cutting edge you can look at WASM: https://github.com/envoyproxy/envoy-wasm/blob/master/WASM.md .
