### ISSUE TITLE
stream info: expand protocol set

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10487]
As a follow-up to https://github.com/envoyproxy/envoy/pull/10383, I would like to differentiate between connections handled by HCM vs `tcp_proxy` across filter chains in a single listener. The `protocol` field in the stream info seems appropriate, but right now it's an enum with HTTP protocol versions. The proposal is to change it to be a bit mask, and and add a few values:
- TCP for all TCP including HCM traffic
- HTTP as a catch-all for HCM traffic
- if there is interest, we can also add gRPC in grpc_stats, mysql, redis, and others.

**Comment by kyessenov** [comment]
cc @mandarjog @zuercher for thoughts

**Comment by mattklein123** [comment]
This sounds reasonable to me.

> if there is interest, we can also add gRPC in grpc_stats, mysql, redis, and others.

My only comment here would be try to figure out a way to keep any extension protocols from creeping into the core, so I would probably try to figure out some way to make this extensible with well known bits and then potential optional bits or a repeated set of strings/codes/whatever.

**Comment by kyessenov** [comment]
Regarding the open-ended protocol set, is there a prior art or preference in Envoy?
Option 1: Make it a bit mask and reserve some base number of bits for core, and let the extensions pick the rest (in ad-hoc manner).
Option 2: Create a factory registration pattern that would register a protocol value via a static initializer.

**Comment by mattklein123** [comment]
> Option 2: Create a factory registration pattern that would register a protocol value via a static initializer.

This would be really nice but more work. Would definitely prefer this. The issue with this is wouldn't necessarily be consistent across deployments. Can we just use a repeated set of string codes or something?
