### ISSUE TITLE
Burst of HealthChecking Probes

### ISSUE THREAD

**Issue by PinchasLev** [envoyproxy/envoy#10498]
*Title*: *Burst of Health Checks on Cluster with Many Replicas of Envoy*

*Description*:
Users of upstream services are complaining about bursts of health checks.  The issue is that all replicas of Envoy require to internally maintain the accessibility of all the upstream replicas of a given service, so as to correctly implement the load balancing strategy, removing inaccessible upstreams from consideration, and therefore the number of probes is *n* * *m* in every period for every service.  Where *n* is the number Envoys running and *m* is the number of replicas for the service.  And if all Envoys came up at once, this burst of health check probes occur all at once.

I can think of multiple ways to address this.
1. Add some randomness to the periodicity, so that all copies of Envoy aren't issuing their health check probes to a given service in lock step.
2. Have the Envoys check the KV store whether the upstream has been checked within the periodicity, and only if no healthy probe was conducted within the timespan will a given Envoy issue a probe.  This approach has the downside of not having each Envoy check that it can reach every instance of an upstream.  Other downsides are its reliance on accessing the KV store, as well as its relative complexity.  The upside is that only *m* requests are done over the period.
3. Stagger the launch of the Envoys.  This approach requires launching Envoy in a way that isn't consistent with the way replicas are typically launched in *k8s*

**Comment by mattklein123** [comment]
Envoy already supports jitter via the `initial_jitter` and `interval_jitter` configuration options.

(2) Could probably be implemented via a custom health checker. Note also that Envoy can be used without active checking and rely on the control plane to provide centralized health checking.

**Comment by PinchasLev** [comment]
Thanks @mattklein123.  I'll read up on both options you mention.
