### ISSUE TITLE
gRPC-JSON transcoder does not support additional_bindings

### ISSUE THREAD

**Issue by jaredkhan** [envoyproxy/envoy#10505]
*Description*:
googleapis provides a Method annotation called http which can be used to describe a mapping from your gRPC service to a REST API

They extend the MethodOptions type to add http of type HttpRule: https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

They define the HttpRule type: https://github.com/googleapis/googleapis/blob/master/google/api/http.proto

Envoy implements this transcoding in its gRPC/JSON transcoder: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter

But additional_bindings, as seen in the HttpRule type are not supported.
This feature is intended to allow multiple URL mappings to the same gRPC method. This has turned out to be quite a desirable feature for us.

**An example use-case:**
we had resources at e.g. `api/fruits/orange` and `api/vegetables/carrot` and we wanted to add a key/value 'labelling' system to those resources (you could POST some new key value pairs to be associated with it, and GET those key value pairs). Naturally, the label resource names became `api/fruits/orange/labels` and `api/vegetables/carrot/labels` but behind the scenes these are both going to be calling the same GetResourceLabels method, since this labelling mechanism can be agnostic what it is labelling.

*Relevant Links*:
I've put together a toy example of how one would use this functionality including the proto file, the server, the client, and the envoy.yaml file. When the client tries to use the additional binding, it of course fails:
https://github.com/jaredkhan/additional_bindings_example

**Comment by jaredkhan** [comment]
Hm. Well, after a dive down the rabbit-hole of https://github.com/grpc-ecosystem/grpc-httpjson-transcoding I can no longer replicate this problem with the latest envoy. Nor any recent version of Envoy. So I'm not sure what image I must have been running before.

I'll just try on one more machine before closing this issue 😊

**Comment by qiwzhang** [comment]
By reading this code
<https://github.com/envoyproxy/envoy/blob/4283e25cacb89627819be51b1c1cd7d4bfcb35ff/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L162>,
it seems that additional bindings are not supported.   But it should be
easy to add,  just add a for loop here to add all rules in the
additional bindings.

**Comment by jaredkhan** [comment]
I tried on another machine and this does actually seem to work now. I'm not sure why it was failing for me before.

The additional_bindings handling is hidden in this line:
https://github.com/envoyproxy/envoy/blob/4283e25cacb89627819be51b1c1cd7d4bfcb35ff/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L176

Implemented in this dependency: https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/master/src/include/grpc_transcoding/path_matcher_utility.h

I can no longer replicate the failure I was seeing before but just in case it's useful to someone: When I was seeing additional_bindings get ignored I was able to work around it by changing e.g.:

```
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      get: "/greeting"
      additional_bindings: {
        get: "/other"
      }
    };
  }
```

for

```
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      custom: {
        kind: "GET"
        path: "/greeting"
      }
      additional_bindings: {
        custom: {
          kind: "GET"
          path: "/hello"
        }
      }
    };
  }
```

Then again, that may just have been an illusion.

Closing this issue for now 👋
