### ISSUE TITLE
Add support for multi-architecture images

### ISSUE THREAD

**Issue by xUnholy** [envoyproxy/envoy#10512]
Title: **Support ARM / ARM64 / AMD64 architecture**

**Description**:

I wish to request support for ARM architecture, however, it would be worthwhile adding support for any architecture type or at least those that are feasible. I'm currently running a Kube cluster on ARM devices, however, Istio cannot support ARM because Enovy is currently not compatible. 

I've raised an issue on the Istio project https://github.com/istio/istio/issues/21094 where there are several attempts to compile the Istio control plane in multi-architecture compatible images.

Such as this pull request: https://github.com/istio/istio/issues/21094

Although, this will also need the Envoy proxy to be compatible.

https://github.com/raspbernetes/multi-arch-images/issues/5

**Comment by moderation** [comment]
The issues you link to are for 32-bit Arm. I'm compiling and running Envoy on 64-bit arm64 / aarch64 on a Pi 4 running Ubuntu server 19.10 without issue. I think using a 64-bit OS on Pi will be an easier path than trying to support ARMv7l and 32-bit.

**Comment by xUnholy** [comment]
@moderation I have just attempted running Istio and confirmed even running Ubuntu server 19.x was unsuccessful. Given docker now supports fat manifests for multi-architecture support it shouldn't be a question regarding which architectures are current or popular. 

I've also seen a similar issue trending in the following issue https://github.com/envoyproxy/envoy/issues/1861

**Comment by anbern** [comment]
I'm trying the same : 4 Pi4s with 64bit Ubuntu Server 19 run microk8s as a cluster (no prob). Cannot enable the istio option ... root cause seems to be the missing arm64 build from envoy. Any chances to have this someday? It would be GREAT! 
Kind regards
Bernhard
