### ISSUE TITLE
Switch PGV string annotations using min_bytes to min_len

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10535]
Since https://github.com/envoyproxy/protoc-gen-validate/pull/256 landed, we can now use `min_len` in C++. The use of `min_bytes` was a temporary workaround, so we should move all of Envoy APIs to `min_len` (for v3+) and enforce via CI checks this style aspect.

CC @mattklein123 @asraa @SecurityInsanity

**Comment by SecurityInsanity** [comment]
We're gonna wait until the versioned proto's are exposed fully in bazel (right now: `package_version_status` is only exporting the "active" version). We want to it to export the "future" version as well so we can run an `api_proto_plugin` over the future versions to enforce the use of `min_len` over `min_bytes`.

**Comment by ankatare** [comment]
@htuch thanks for assigning me.

**Comment by ankatare** [comment]
@htuch thanks a lot for adding milestone. i will get back ASAP for any doubts on requirement understanding.

**Comment by ankatare** [comment]
@SecurityInsanity would you please guide me script file to enforce  in CI.

**Comment by SecurityInsanity** [comment]
@ankatare be more than happy too! Feel free to reach out to me on slack with any particular questions/guidance you need.

**Comment by ankatare** [comment]
@SecurityInsanity sure. Thanks for quick response :)

**Comment by ankatare** [comment]
sorry for delay.   i was off last week due to bad health.
