### ISSUE TITLE
Envoy alpine docker image created using root user

### ISSUE THREAD

**Issue by sagarkal** [envoyproxy/envoy#10541]
Hi,

We are planning to use envoy docker image envoy-alpine:v1.13.1 at an organization. However our twistlock instance reports that the image is created as a root user and flags it as a compliance issue. 

Is there a possibility that the user could be changed to a non-root user in the later stage of the Dockerfile?

Regards,
Sagar

**Comment by dio** [comment]
@sagarkal do you think something like below suffices your need?

```
FROM envoyproxy/envoy:v1.13.1

FROM frolvlad/alpine-glibc
RUN mkdir -p /etc/envoy
COPY --from=0 /usr/local/bin/envoy /usr/local/bin/envoy
COPY --from=0 /etc/envoy/envoy.yaml /etc/envoy/envoy.yaml
COPY --from=0 /docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 10000
RUN addgroup -S envoy -g 1337 \
  && adduser -S -G envoy -u 1337 envoy
USER envoy
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]
```

Build and run it, then check the user:

```
/ $ ps aux | grep envoy
    1 envoy     0:00 envoy -c /etc/envoy/envoy.yaml
```

**Comment by moderation** [comment]
If your organization is concerned about security I'd suggest running a "kitchen sink" Envoy container with every extension enabled isn't ideal. @dio's method above is good but ideally you should build a custom Envoy with only the extensions you require compiled into the binary (IMO).

**Comment by sagarkal** [comment]
@dio Yes your Dockerfile would suffice! are you considering releasing a new tag based on this Dockerfile? because I believe the it's a good security practice to run containers as non-root.

@moderation Well although what you said does make sense, I think having our own custom image would lead to an overhead of maintaining it and updating it as and when there is a newer image from envoy.

Nevertheless, any particular reason you guys think envoy container has to run as root by default?

**Comment by moderation** [comment]
Security vs. low maintenance - choose one. If you're running Twistlock I would have thought that security was important... ¯\_(ツ)_/¯

For what it's worth we run Envoy as part of Contour on a Kubernetes cluster where root is prohibited and it works. Where are you running this Envoy container?

**Comment by sagarkal** [comment]
@moderation We are gonna run envoy on Kubernetes too..
_we run Envoy as part of Contour on a Kubernetes cluster where root is prohibited and it works_
I did not quite get this..if you mean root is prohibited, then how do you use Envoy image that is based on root user? Or may be at run time you override the user using [RunAsUser](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups)?

**Comment by moderation** [comment]
@sagarkal we build our own images and add / run as non-root user.

**Comment by sagarkal** [comment]
@moderation Gotcha
