### ISSUE TITLE
threads: current worker thread index should be exposed to extensions

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#10544]
*Title*: `Stats API` should provide support for `per-thread` metrics

*Context*:
* there are use cases where cross-thread aggregation of metrics is not desirable since it can make metrics more obscure
* right now, `Envoy` already has a couple `per-thread` metrics, such as `server.worker_N.watchdog_miss`, but no general approach 
* having per-thread metrics could further improve `Envoy` observability story

*Proposal*:
* provide general approach to maintain per-thread metrics
* provide ready-to-use Stats API for that, e.g.
  * introduce `Scope::createScopePerThread(name)`
  * which will automatically include thread name into all metrics in that scope
  * e.g.
    ```
    auto scope   = parent.createScopePerThread("wasm.wm.<VM ID>")
    auto counter = scope.counter("memory_size_bytes")
  
    // as a result, `counter` will automatically get a full name
    // `wasm.vm.<VM ID>.worker_N.memory_size_bytes`
    ``` 

*Example use cases*:
* consider `Wasm` use case as an example
  * for every `Wasm` extension a separate `Wasm VM` will be created on each thread
  * for each `Wasm VM` it's important to have metrics like
     * `memory_size_bytes`
     * `restarts_total`
     * `traps_total`
  * having those metrics aggregated across all threads would make them more obscure

**Comment by snowp** [comment]
Would this just be helper functions around the existing stats subsystem that incorporates a thread name into the stats name? Or are you talking about having independent thread local stat stores?

cc @jmarantz

**Comment by jmarantz** [comment]
Yeah any particular reason not to just add a scope named for the current thread, and then use the existing API?

That would do exactly what you want functionally IIUC. It would also not be too far from optimal in its implementation in thread_local_store.cc: there would be one extra level of caching that would not be useful, but it's also probably not too expensive.

**Comment by yskopets** [comment]
I was thinking about a helper function which abstracts the way current thread name is inferred.

**Comment by jmarantz** [comment]
In the context of WASM this should be pretty easy without any extra infrastructure; Wasm code controls the scope used for the lookup.

Do you want to have all the WASM stats be per-thread? Or do you want to aggregate some of them?

**Comment by yskopets** [comment]
I'm mostly focused on metrics about `Wasm VMs` themselves.

Because in this particular case the advantages of `per-thread` metrics are clear to me - ability to spot a misbehaving VM.

I don't think that metrics of `Wasm` extensions need special treatment comparing to regular extensions. So, I would say that the same aggregated behaviour should stay the default for `Wasm` extensions as well.

**Comment by yskopets** [comment]
From my perspective, this proposal is mostly about:
* assigning a name to each thread (like `worker_N`)
* providing API to access that name
* providing a convenience method as part of Stats API

**Comment by jmarantz** [comment]
Sounds good. What's the reason this isn't addressed by using
```
  wasm_thread_scope_ = server().stats().createScope(absl::StrCat("worker_", worker_index));
```
or similar?

**Comment by jmarantz** [comment]
also there is not currently a thread name in Envoy, just a thread ID which in Linux is the pid.

**Comment by yskopets** [comment]
Ideally, I'd like to see `absl::StrCat("worker_", worker_index)` a part of Envoy API.

Is there a way to get ahold of `worker_index` from the factory context of a filter  ?

**Comment by jmarantz** [comment]
I guess there is a worker index, and it lives only in source/server/listener_manager_impl.cc in the ListenerManagerImpl ctor

You just want that plumbed into some context visible from a Filter, is that right?

**Comment by yskopets** [comment]
`Wasm WM` can be created from the context of any extension type. So far, it has been discussed for the `Listener` and `Cluster` contexts.

Will `worker_index` be available in the context of `ClusterManager` ?

**Comment by jmarantz** [comment]
IDK; I'll defer to @mattklein123 about the best place to expose a worker index to WASM, if there's not already a way to get to that.

**Comment by yskopets** [comment]
I think, I can re-phrase.

Will `worker_index` be available in the context of a callback that is executed on individual threads as part of `Slot::set()` ?

**Comment by mandarjog** [comment]
@PiotrSikora @jplevyak @kyessenov

**Comment by mattklein123** [comment]
> IDK; I'll defer to @mattklein123 about the best place to expose a worker index to WASM, if there's not already a way to get to that.

Yeah I think just formalizing the worker name or ID would be fine. We could make this available via the TLS interface potentially, or possible the dispatcher interface, or probably any number of other cases. Do you want to flesh out a concrete proposal?

**Comment by yskopets** [comment]
Yes, I can prepare a proposal.

But I need to take a deeper look into TLS mechanics first.

**Comment by yskopets** [comment]
@mattklein123 

I think, the most simple (and also very natural) way to expose `"worker name"` is to assign it to an `Event::Dispatcher`.  

In this case, it will be possible to access `"worker name"` from anywhere in the source code, at any moment, etc.

Regarding `"worker name"` vs `"worker index"`, just index is not enough because it doesn't account for the main thread.

So, the proposal is to:
* add `std::string name()` method to `Event::Dispatcher`
* change `allocateDispatcher(..)` methods of `Api::Api` to take `name` as a mandatory parameter
* update `ProdWorkerFactory::createWorker(..)` to allocate an `Event::Dispatcher` using `"worker_N"` as a name
* update `Server::InstanceImpl(..)` to allocate an `Event::Dispatcher` using `"main_thread"` as a name

**Comment by mattklein123** [comment]
@yskopets this sounds reasonable to me. I assume you plan on cleaning up the existing worker_name being passed around?

**Comment by yskopets** [comment]
yes

**Comment by yskopets** [comment]
The proposed use of `<thread name>` inside `Wasm` metrics is described in #10734
