### ISSUE TITLE
Allow specifying a different transport socket config for cluster health checks

### ISSUE THREAD

**Issue by spenceral** [envoyproxy/envoy#10575]
*Title*: *Allow specifying a different transport socket config for cluster health checks*

*Description*:
It is my understanding that today, cluster active health checking uses the [transport socket specified for the cluster](https://github.com/envoyproxy/envoy/blob/9521f88d93c1454739895d979e16000d1df0729b/api/envoy/api/v2/core/health_check.proto#L181). I'd like to allow overriding that transport socket for health checks. 

I have a use case where I need to proxy at L4, but I'd still like the power of L7 health checks. I'd like to allow specifying an optional healthcheck transport socket in a cluster's config. Adding this field in the cluster config makes it easy to add a new transport socket factory in upstream_impl.h that is used in Upstream::Host's createHealthCheckConnection if the optional field has been set.

I see that there have been similar, unresolved Issues in the past, so I'm open to any other implementation suggestions.

**Comment by htuch** [comment]
@snowp @lizan any thoughts here?

**Comment by snowp** [comment]
I don't see how this is required to do L7 health against something that uses tcp_proxy? You should be able to just specify a HTTP health check for the cluster. Is the problem that you're not using TLS when doing L4 proxying, but need to do so during health checking?

**Comment by spenceral** [comment]
You're right, I should've been more specific. I want to do https health checks so I'd like to configure a TLS transport socket for health checking.

**Comment by snowp** [comment]
Being able to override the transport socket seems reasonable to me, I think the fact that we have the transport socket abstraction in place makes this a lot easier to solve than it was before (as we don't need to make this feature TLS specific).

**Comment by spenceral** [comment]
Cool, I'll work on a PR in which I add a `healthcheck_transport_socket` field to the cluster config.

**Comment by mattklein123** [comment]
See also `TlsOptions tls_options = 21;` in the health check config. It would be nice to reconcile this and potentially deprecate that field if it can be made more general via the transport socket config?

**Comment by spenceral** [comment]
Looks like the health check `tls_options` alllows overriding ALPN protocols. You can also set ALPN protocols in the tls context of a tls transport socket so I do think we could deprecate `tls_options`.

However, since I'm proposing a single health check transport socket in the cluster config, users will only be able to specify one `alpn_protocols` list. A user could potentially have a different list for different health checks with today's configuration.

To be more similar to the current configuration, should I add a `transport_socket` field to the health check config? I could use a [TransportSocketMatchImpl](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/transport_socket_match_impl.h) to pick the right transport socket factory for a given health check.

**Comment by lizan** [comment]
It might makes more sense to use transport socket match. You should be able to add a match criteria for healthcheck to select right transport socket.

**Comment by mattklein123** [comment]
+1 for transport socket match. This would be very flexible. Thank you!

**Comment by spenceral** [comment]
Great, thanks for the feedback.

**Comment by bvandewalle** [comment]
Definitely interested in this feature as well. Thanks for working on it.

**Comment by adwski** [comment]
Is this usable? How it can be configured?
