### ISSUE TITLE
circuit-breakers:max_connections in tcp/conn_pool.cc

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#10588]
My circumstance I have config max_connections like 3,but when I start call(thrift proxy),the existing connections are much more than 3.So I debug the source code,is there any situation when there are existing conns(resource manager's current more then 1), and ready_conns_,busy_conns_,pending_conns_ are all empty?
Any help will be appreciate!!!

**Comment by htuch** [comment]
@zuercher might be able to help here with Thrift specifics, but I think we'll probably need more details to investigate.

**Comment by pyrl247** [comment]
Here is my yams config:
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902
      protocol: TCP
node:
  cluster: test-cluster
  id: test-id
static_resources:
  clusters:
  - circuit_breakers:
      thresholds:
        max_connections: 1
        max_pending_requests: 2
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_thrift
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.4.45.47
                port_value: 9990
    name: service_thrift
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.thrift_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.thrift_proxy.v2alpha1.ThriftProxy
          protocol: BINARY
          transport: FRAMED
          route_config:
            name: local_route
            routes:
            - match:
                service_name: ''
              route:
                cluster: service_thrift
          stat_prefix: pyrl_server1
          thrift_filters:
          - name: envoy.filters.thrift.router
            typed_config: {}
When I start thrift-client multi-thread,there are always more than 1 connection betweent envoy and thrift-server.seems max_connections didn't work at all.

**Comment by lambdai** [comment]
Drive by: Is it possible the existing 3 connections are among multiple worker thread, while you are looking at a lucky thread which owns no connections

**Comment by pyrl247** [comment]
Is this config(max_connections) work in each worker thread?not a global config?If I config max_connections as 3, and start envoy with cmd args --concurrency 2,Is that mean the max total connection between envoy and server will be 6(3*2)?

**Comment by zuercher** [comment]
It's per-worker, per-upstream. So the total number of connections for a cluster will be `max_connections * cluster_size * concurrency`. This is not specific to Thrift, BTW. It's a property of Envoy's connection pooling and applies to the http connection manager and tcp proxy as well.
