### ISSUE TITLE
Envoy is sometimes not removing buckets after listener/cluster removal

### ISSUE THREAD

**Issue by oblazek** [envoyproxy/envoy#10608]
**Bug**

*Title*: *Envoy is sometimes not removing buckets after listener/cluster removal*

*Description*:
> We have observed that envoy sometimes doesn't remove a stat (a buckets to be exact) when service/cluster is removed. When listener is frequently added and removed its buckets are not removed every time which results in:

```
cluster.cluster1.upstream_cx_connect_ms: No recorded values
cluster.cluster1.upstream_cx_connect_ms: No recorded values
cluster.cluster1.upstream_cx_connect_ms: No recorded values
cluster.cluster1.upstream_cx_connect_ms: No recorded values
```
> or 
```
envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="cluster2",le="1"} 17
envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="cluster2",le="1"} 0
envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="cluster2",le="1"} 0
envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="cluster2",le="1"} 0
```
> for `/stats/prometheus`. This gets to the point where each of our envoys have up to e.g. 800 000  metrics (but basically any number if we let it run longer) and they all start to have issues with handling xDS updates, because the master process is kept too busy. I have seen 1,5 milion of metrics and the host has been significantly less performant.

> Problem is that this happens only to buckets, not to counters and the only solution is to restart envoy.

*Repro steps*:
> I have been unable to reproduce this in our test env yet, this happens only on production systems where we have ~1 milion active connections (combination of http, https, tcp) and ~800-1300 listeners + clusters. 

*Notes*:
> This issue can be seen on both envoy 1.11.0 and 1.12.2. I will continue trying to reproduce this on our test env.

*Expected behavior*:
> Envoy should remove every time buckets when service/cluster is removed.

**Comment by htuch** [comment]
@jmarantz @mattklein123 I had the mental model that we don't remove stats at all, but this might be wrong. Do you know the desired behavior here?

**Comment by mattklein123** [comment]
We definitely remove stats, so something is up here. @jmarantz would you be willing to take a look?

**Comment by jmarantz** [comment]
I think I need more details about a repro, then I'd be happy to look at it, but let me share some thoughts.

We generally remove stats when a scope is removed.

The Stats::Store keeps a ref-counted collection of stats, and the ThreadLocalStore's Scope implementation holds onto a reference to each stat in its `CentralCacheEntry`. The Scope itself is usually managed by a unique_ptr (though ref-counted in a few places) and when its ref-count drops to zero, all the individual stats in the scope should be dropped from the store, and no longer emitted to prometheus.

What could be going wrong? Ideas:
 * the cleanup process has to run on all threads before it completes, and if any thread is blocked then cleanup won't occur. I'm assuming we'd have some kind of guard-dog/watch-dog failure if this happened?
 * someone could be holding onto the ScopeSharedPtr longer than expected

I hadn't looked into this corner of the code much, but `Scope::createScope` returns a unique_ptr, which is then used to initialize a shared_ptr<Scope> in `GoogleAsyncClientFactoryImpl::GoogleAsyncClientFactoryImpl`, which looks surprising but I guess makes sense.

This then gets held by potential multiple instances of GoogleAsyncClientImpl, and I'm not sure what their lifetime is, or if the particular stats that are leaking might be held by one of those.

`shared_ptr<Scope>` is also used by wasm but given this was seen in 1.11.0 I assume that's not related.

I don't know other ways at this point that cluster-stats could linger, but I do have another question about versions: would it be possible to repro on 1.13.1, just to make sure this situation still exists? There are unrelated reasons to go to that version as well.

**Comment by oblazek** [comment]
I will prepare our control plane for version 1.13.1 and will let you know as soon as I know more ;) thanks a lot.

**Comment by jmarantz** [comment]
Oh I just realized we worked with you earlier on https://github.com/envoyproxy/envoy/issues/9448 . In that thread you mentioned this:

> by a race when cluster of same name is added and removed right after. This happens quite a lot in our env

Does that still happen? Are the fixes that went into https://github.com/envoyproxy/envoy/pull/9533 and #9533 incorporated into your running Envoys?

**Comment by oblazek** [comment]
Yes, but little bit less often, since (as I mentioned before) we have not been using EDS before so every time some deployment has been scaled up if would remove/add cluster. 
But now clusters and listeners are removed only when deployment is scaled to 0 replicas, service (meaning listener+cluster) is removed *(see below) or readiness probe fails for all pods.

* service (listener+cluster) is added/removed if user itself creates/deletes it
* the same service (listener+cluster) is added/updated/removed every minute (on all envoy hosts) - but we are filtering out these metrics, so this doesn't cause duplicates anymore

**Comment by jmarantz** [comment]
I'm still not sure I fully understand the flow that you have.

Are the fixes that went into #9564 and #9533 incorporated into your running Envoys?

**Comment by oblazek** [comment]
And no, actually we did not incorporated those fixes. I had the impresion that those were related only to the segfaults we were having so that's why not. 
I am now closely watching one of our machines where we have deployed envoy 1.13.1 and something is not right there as well.

I am checking the metrics with this command and today this appeared:
```
curl localhost:8001/stats/prometheus | sort | uniq -c | awk '{if($1>1) print $0}' | sort
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="100"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="1800000"} 32
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="250"} 2
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="50"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="500"} 4
      3 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="25"} 0
      4 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="0.5"} 0
      4 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="1"} 0
      4 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="10"} 0
      4 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="5"} 0
```
but when I ran the same command after a few minutes I got:
```
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="10"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="1000"} 8
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="2500"} 9
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="5"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="500"} 7
      3 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="0.5"} 0
      3 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="1"} 0
```
and again:
```
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="0.5"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="1"} 0
      2 envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name="k8s1_ko__nextcloud_stable__nextcloud_proxy__n__https",le="5"} 0
```
and I know from the metrics that the user has been deploying a new version around that time so pod were scaled up and down during that time.

**Comment by jmarantz** [comment]
So does that mean this is now working properly in 1.13.1?

**Comment by oblazek** [comment]
I mean usually its only a matter of time before more duplications appear, so I will let you know asap. But seeing the same metric even twice doesn't seem right.

**Comment by jmarantz** [comment]
Those are histograms. See this comment in `source/common/stats/thread_local_store.cc`
```
std::vector<ParentHistogramSharedPtr> ThreadLocalStoreImpl::histograms() const {
  std::vector<ParentHistogramSharedPtr> ret;
  Thread::LockGuard lock(lock_);
  // TODO(ramaraochavali): As histograms don't share storage, there is a chance of duplicate names
  // here. We need to create global storage for histograms similar to how we have a central storage
  // in shared memory for counters/gauges. In the interim, no de-dup is done here. This may result
  // in histograms with duplicate names, but until shared storage is implemented it's ultimately
  // less confusing for users who have such configs.
  for (ScopeImpl* scope : scopes_) {
    for (const auto& name_histogram_pair : scope->central_cache_->histograms_) {
      const ParentHistogramSharedPtr& parent_hist = name_histogram_pair.second;
      ret.push_back(parent_hist);
    }
  }

  return ret;
}
```

So my theory at this point is that #9564 and #9533 fixes the problem reported here.

It is still confusing due to the way histograms work. If this is true, you may still see duplicate histograms due to your usage model of recreating the same cluster with the same name periodically, but that there will not be an unbounded leak.

**Comment by oblazek** [comment]
Aaah, ok that clarify things up a lot. Thanks. Please keep this issue opened for a few more days so I can be sure it's fixed.

**Comment by jmarantz** [comment]
This also highlights a functional issue with your approach: histograms will effectively restart from empty each time you add/remove a cluster with the same name. The same-named histograms from the distinct instantiations will not be combined, IIUC.

Workaround: use EDS :)

**Comment by oblazek** [comment]
We have been using EDS now for a few months, but true.. we could try **not** removing clusters when upstreams scale down to zero and then back up in our control plane.

**Comment by oblazek** [comment]
Thanks a lot @jmarantz, in 1.13.1 this work perfectly fine. Let's close this.
