### ISSUE TITLE
Does JWT validation filter supports ES256 alg with P-256K curve?

### ISSUE THREAD

**Issue by andrevegas** [envoyproxy/envoy#10607]
Hi,
First time dealing with this "new" kinds of encryp/sign keys, I know JWT validation filter works fine for RSA(s) algs, but came accros envoy rejecting the JWT configuration when adding the JWKS config key (ES256K - P-256K).

I'm not sure if envoy wouldn't support this curve (P-256K) or if there was an issue converting the pem key pair format to JWKS. (quick test with JWKS ES256 - P-256 (without K), seems to work, but I would need specifically P-256K curve in this case)

Can anyone offer some help?

Init envoy log output error:
```
[2020-04-01 07:17:37.230][1][critical][main] [source/server/server.cc:94] error initializing configuration '/etc/envoy.yaml': Issuer 'auth-service' in jwt_authn config has invalid local jwks: Jwks EC [x] and [y] fields have a parse error.
```

PEM keys:
private: "5KGcox2wWhAr33BuZon96t6dFpSYqPXZ5LicdkJPF4bogovzEYi"
public: "EOS7rjKyqe4Z68dFGwa8j7kGseQL8XNyR6YpKPHgjaW9ev2UKDKQV"

Converted JWKs (using nimbus-jwt):

```
    {
      "keys": [
        {
          "kty":"EC",
          "d":"v3wsqyW6IA33VnA476GpriOb2aMaVE2vjull3sserNA",
          "alg":"ES256K",
          "crv":"P-256K",
          "x":"hxgYULEB0NLIrevwMoLMzAzxLyz6T_-_Gbto9Qy3amA",
          "y":"oxWkWIRWUjlqwkSNq633cJMazwa9AE-BsCCoJEIBpp8"
        }
      ]
    }
```

Cheers,

**Comment by htuch** [comment]
@qiwzhang do you have any thoughts on this one (or next hop route)?

**Comment by qiwzhang** [comment]
Hi @andrevegas the actual code of processing JWKS is [here](https://github.com/google/jwt_verify_lib/blob/master/src/jwks.cc#L190). It seems that it is not supporting P-256K. 

But you are welcome to contribute to that repo to add such support.
