### ISSUE TITLE
Windows RBE Tracking Issue

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#10619]
*Description*:

We have started extending and enabling what is run in the Windows CI pipeline and found the Azure Pipelines build environment is severely underpowered to do a fully local build in a timely manner. While we may look in to using a user-managed Azure Pipelines worker, we should also explore the idea of using bazel RBE as the Linux CI does to cut down build times etc. Other projects (namely gRPC and tensorflow) seem to have success with this in their CI.

*Questions*:
- Are there any restrictions or limitations to the Google hosted RBE product that would prevent us from using it for the Envoy project CI builds?
  - Since Windows security is key (and the execution environment may not be via Hyper-V isolated containers), is it restricted to Google owned projects only or can we set up Envoy to use it?
- What is the correct entrypoint to start setting up RBE for Envoy CI? (the `envoy-build-tools` repo + setting up a toolchain? etc.)

*Links*:
- PR to enable Windows CI: https://github.com/envoyproxy/envoy/pull/10542
  - Example build that fails due to heap error in `cl.exe`: https://dev.azure.com/cncf/envoy/_build/results?buildId=36492&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3
- Draft PR with experiments around Windows CI environment: https://github.com/envoyproxy/envoy/pull/10610
  - Example build running 1 test (that takes over an hour): https://dev.azure.com/cncf/envoy/_build/results?buildId=36568&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3

**Comment by htuch** [comment]
@nicolasnoble can you share the gRPC experience with RBE here?

**Comment by nicolasnoble** [comment]
cc @jtattermusch - we've been able to run Windows RBE after a lot of tweaks in our environment: https://github.com/grpc/grpc/blob/cc43fd64ab97e45fcdd38759dd8d9eb273823b9e/third_party/toolchains/BUILD#L21

**Comment by sunjayBhatia** [comment]
Ah cool, this dockerfile should be a good reference: https://github.com/grpc/grpc/blob/master/third_party/toolchains/bazel_0.26.0_rbe_windows/Dockerfile

**Comment by sunjayBhatia** [comment]
Can you speak to what sorts of tweaks you had to make and if the RBE product is available for us to use with Windows?

**Comment by jtattermusch** [comment]
Also see https://github.com/grpc/grpc/pull/22473/files which migrates our stack to Win2019 workers (which is what you should use if you wanna go ahead with windows RBE).

What we've done for RBE windows:
- we haven't really done any custom tweaks, we basically just followed the user guide for RBE windows. Unfortunately the documentation for RBE windows is internal, so I'm not sure if you are able to access it.
- the process of setting up Windows RBE is more complicated than linux, because you need to create and build your own Dockerfile  and you also need to autogenerate your toolchain (basically what's in int bazel_0.26.0_rbe_windows directory.  But these steps are basically just mechanic and they are relatively well documented step by step (if you have access to the docs).

**Comment by sunjayBhatia** [comment]
> Unfortunately the documentation for RBE windows is internal, so I'm not sure if you are able to access it

I joined a google group and got access to some docs, not seeing any mention of Windows yet but that is a start, I'll keep looking for more docs and see if I can bother someone to get access

+1 to Windows 2019, we're working on a Dockerfile etc. to get that going and will make a PR to https://github.com/envoyproxy/envoy-build-tools

Thanks for the resources/tips, we will hopefully make some progress soon and maybe have more questions

**Comment by sunjayBhatia** [comment]
PR for docker image: https://github.com/envoyproxy/envoy-build-tools/pull/40

Confirmed that it locally has the dependencies to build envoy-static.exe and tests

**Comment by sunjayBhatia** [comment]
so far I don't see any flags to be able to choose the OS of the worker pool VMs in the docs: https://cloud.google.com/remote-build-execution/docs/set-up/remote-environment#create_a_worker_pool, does that sound like something that is available in some further hidden docs?

**Comment by jtattermusch** [comment]
The way a windows pool is setup internally is to create a regular linux pool and the file a ticket with the RBE team to switch your pool to windows OS (it's not self-service). So I guess you'll need to ask the RBE team if this is possible for external users.

**Comment by sunjayBhatia** [comment]
relevant bazel issue for this work: https://github.com/bazelbuild/bazel/issues/11101

**Comment by sunjayBhatia** [comment]
We've hacked together some changes to `bazel-toolchains` and `envoy-build-tools` that let us generate a MSVC toolchain:
- https://github.com/greenhouse-org/bazel-toolchains/tree/enable-docker-toolchain-non-linux
- https://github.com/greenhouse-org/envoy-build-tools/tree/generate-windows-msvc-toolchain

**Comment by sunjayBhatia** [comment]
Our next step is to get a test GCP environment with RBE + Windows enabled to test out our generated toolchain

**Comment by sunjayBhatia** [comment]
`bazel-toolchains` issue to see if they will take our changes: https://github.com/bazelbuild/bazel-toolchains/issues/855

**Comment by sunjayBhatia** [comment]
PR to enable remote cache in CI: https://github.com/envoyproxy/envoy/pull/10831

**Comment by sunjayBhatia** [comment]
We're testing out our generated toolchain config and toolchain image and with a few tweaks are so far successfully building Envoy with RBE, forthcoming PRs to upstream our work coming soon

**Comment by sunjayBhatia** [comment]
We've started a Draft PR here to demonstrate a working RBE build on Windows workers: https://github.com/envoyproxy/envoy/pull/11107 this should get turned into a full PR once we have upstreamed all our changes to the bazel-toolchains and envoy-build-tools dependencies

**Comment by sunjayBhatia** [comment]
This build log demonstrates a working build in CI that builds all sources and compiles tests not tagged with `skip_on_windows`: https://dev.azure.com/cncf/envoy/_build/results?buildId=39115&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy-build-tools/pull/64 for changes to envoy-build-tools that will enable generating Windows toolchain configs. All changes required for bazel-toolchains have been merged in: https://github.com/bazelbuild/bazel-toolchains/pull/873

**Comment by sunjayBhatia** [comment]
Our toolchain config changes have all been merged, we're just waiting on fixing some Windows specific issues caused by the merge of recent PRs
