### ISSUE TITLE
Support file refactoring within a package in v3

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10612]
As a result of the internal shadow construction technique used in #10355, it will not be possible to move protos between files (at least when they have deprecated v2 fields as reserved fields). This is a known limitation that should be addressed as needed, this issue tracks.

**Comment by ankatare** [comment]
@htuch is this issue still need help or ok to take for 1.17 ?

**Comment by htuch** [comment]
@ankatare I'd wait until we're done with the v2 deprecation in Q1 to take this on.

**Comment by ankatare** [comment]
@htuch Pls suggest if it is rady to take Now.

**Comment by htuch** [comment]
I'm going to close this one out as we no longer have the tooling issues since the v2 removal.
