### ISSUE TITLE
v3.Node has deprecated field build_version

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/envoy#10633]
*Title*: *v3.Node has deprecated field build_version*

*Description*:
While implementing [v3 integration tests in go-control-plane](https://github.com/envoyproxy/go-control-plane/pull/286), we realized that the json representation of v3.Node protobuf has the `build_version` deprecated field. As a result, the `jsonpb.UnMarshal` fails. I looked around and looks like the version is not part of a configuration.

```
{
  "node": {
    "id": "test-id",
    "cluster": "test-cluster",
    "build_version": "bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7/1.13.0/Clean/RELEASE/BoringSSL",
    "user_agent_name": "envoy",
    "user_agent_build_version": {
      "version": {
        "major_number": 1,
        "minor_number": 13
      },
      "metadata": {
        "ssl.version": "BoringSSL",
        "revision.sha": "bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7",
        "revision.status": "Clean",
        "build.type": "RELEASE"
      }
    },
    "extensions": [
      ...
      ...
    ]
  },
  "resource_names": [
    "cluster-v0-0"
  ],
  "type_url": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment"
}
```

Does this look like a bug?

**Comment by htuch** [comment]
@jyotimahapatra yeah, this seems strange. We were aware of this being a potential issue, see the history in https://github.com/envoyproxy/envoy/commit/0ee6212b02bdab7b3d66e868449ac93556e63118 and #9604. I assume this is REST-JSON subscription due to you reporting in JSON, will look.

**Comment by htuch** [comment]
Looks like we're missing a scrub of unknown fields when wire casting back to v2. I'll take this one, likely to have some cycles next week to fix.

**Comment by htuch** [comment]
Actually, I was thinking that's the issue if this was the reverse situation, going from v3 to v2, which is the known issue https://github.com/envoyproxy/envoy/issues/9619. 

Are you setting transport API version as well as resource API version in your tests? What does your `ConfigSource` look like?

**Comment by jyotimahapatra** [comment]
@htuch Thanks for taking a look. This is the config https://github.com/envoyproxy/go-control-plane/blob/8bdfeffe82378fad1a8dad94a94e91875347be1f/sample/bootstrap-restv3.yaml

The transport_version is set to v3.

**Comment by htuch** [comment]
What's puzzling me is why we see `build_version` and not `hidden_envoy_deprecated_build_version`, which is the field name that Envoy is using internally. Is there any easy way for me to replicate these tests? Another thing that might be helpful is a `-l trace` of the Envoy during this test.

**Comment by jyotimahapatra** [comment]
@htuch Sorry for false alarm, I think i made a mistake and did not set transport api version. The only strange thing is the mistake manifested only in the rest api case and not grpc case.

**Comment by jyotimahapatra** [comment]
Closing this because its a non issue. Sorry @htuch again for false alarm.
