### ISSUE TITLE
Add headers field

### ISSUE THREAD

**Issue by hanahmily** [envoyproxy/envoy#10638]
*Title*: *Add headers field to `envoy.config.trace.v3.Tracing.Http`*

*Description*:

Headers field to include in `envoy.config.trace.v3.Tracing.Http`. This can be used for scenarios in which additional ad hoc authorization headers (e.g. Authorization: Bearer xxxxx) are to be injected.

**Comment by htuch** [comment]
@hanahmily can you elaborate a bit more? How are the headers going to be used?
