### ISSUE TITLE
Add stat_prefix to listeners

### ISSUE THREAD

**Issue by bartebor** [envoyproxy/envoy#10635]
*Title*:  Listeners use socket address in stat name what can make undesired effects.

*Description*:
IP listeners may use IP address and port in stat names like so:
```
envoy.listener.0.0.0.0_14500.worker_2.downstream_cx_total
```
Some of them (admin at least) do not:
```
envoy.listener.admin.downstream_cx_total
```
For some storage backends, such as graphite, dot is interpreted as a nesting operator. This makes listener stats unnecesarily nested and incompatible between listeners. It is also harder to configure variables in grafana dashboards.

A simple backwards compatible solution would be to introduce optional `stat_prefix` field which would allow to specify custom name to use.

**Comment by ggreenway** [comment]
I'd be in favor of this, if you want to send a PR.

**Comment by mk46** [comment]
@ggreenway @bartebor I would like to take up this issue but need help from both of you.
