### ISSUE TITLE
v3: ConfigSource.transport_api_version does not change service name

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#10650]
*Description*:
It looks like service name (e.g. `envoy.service.secret.v3.SecretDiscoveryService`) is controlled by `resource_api_version` (implicitly through type url), while `transport_api_version` controls the type of a discovery request/response (e.g. `envoy.service.discovery.v3.DiscoveryRequest`).

It makes it impossible to control xds protocol and resource versions independently from each other.
Assuming that v2 and v3 messages serialization on the wire is compatible with each other it makes `transport_api_version` option no-op for non-aggregated endpoints.

What is an expected behavior? Is it supported pattern to use mismatched resource and transport versions for non-ads case? (If it is not supported - can it be enforced?)

*Relevant Links*:
* https://github.com/envoyproxy/envoy/blob/dd8d6e690b029dc68093d7ffee1f28bcf3d35e2e/source/common/config/subscription_factory_impl.cc#L61
* https://github.com/envoyproxy/envoy/blob/5248a4fb7d4c2a3d1fa151f944d3a63f6b7a06cf/source/common/config/type_to_endpoint.cc#L81

**Comment by mattklein123** [comment]
@htuch can you triage for 1.14?

**Comment by htuch** [comment]
This is a very good point, there is an inconsistency here. ADS correctly realizes the independence of transport/resource version, but non-ADS xDS infers xDS transport from resource type version (essentially via the `(envoy.annotations.resource).type` annotation).

I think we should fix this, but it's a bit of work, O(days). Not sure if we want to hold 1.14.0 back on this; the tradeoff is that v3 is only WAI for ADS in 1.14.0 if we don't.

**Comment by mattklein123** [comment]
OK let's move to 1.15

**Comment by htuch** [comment]
This was fixed in #11788

**Comment by dio** [comment]
@htuch sorry, the PR is still open.

**Comment by htuch** [comment]
My bad, let's land this for 1.15.0 .
