### ISSUE TITLE
v3: Aggregated delta gRPC is v2 only

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#10651]
*Description*:
Aggregated delta gRPC misses a case for v3 transport api version so always uses v2 url (potentially with v3 requests on the wire).

*Relevant Links*:
* https://github.com/envoyproxy/envoy/blob/5248a4fb7d4c2a3d1fa151f944d3a63f6b7a06cf/source/common/upstream/cluster_manager_impl.cc#L273-L274

**Comment by mattklein123** [comment]
@htuch can you triage for 1.14?

**Comment by htuch** [comment]
@mattklein123 I think this one is relatively easy to fix, I can probably do it tomorrow.
