### ISSUE TITLE
HTTP Request Buffering

### ISSUE THREAD

**Issue by Charana123** [envoyproxy/envoy#10671]
Is there a way to extend Envoy with a [custom extension](https://www.envoyproxy.io/docs/envoy/latest/extending/extending) to buffer HTTP request traffic ideally in a database engine until the upstream server has recovered from failure (i.e. becomes available again) and then immediately start the request resending.
If not what extension type should I be building to allow such functionality.

**Comment by mattklein123** [comment]
Yes you can do this with an HTTP filter. See the buffer filter and the caching filter for inspiration.

**Comment by Charana123** [comment]
A few questions
- In the case the upstream connection cannot be established, is an *encoding* http filter called to encode the error response *after* all retries have failed ?
- In the case the HTTP connection manager is set to mirror traffic for other upstream clusters. Can we detect a failed request to these mirrored clusters and buffer/re-send traffic to them as well ?

**Comment by Charana123** [comment]
@mattklein123, A few concerns by priority
- Our usecase requires the HTTP request is replicated to multiple hosts. I see that the http filter supports fire-and-forget mirror clusters but not synch req/resp [broadcasting](https://github.com/envoyproxy/envoy/issues/10804). Is there a way for our HTTP filter to detect failed FAF requests to mirrors and buffer/re-send traffic to these as well ? If not, is there anyway to replicate requests in envoy other than mirroring ?
- The filter stack is instantiated on a request, is there some async callback to detect that the upstream is available ? 
- A filter stack is *per-request*, so I assume buffered requests can't be sent over the same connection with the original. Im thinking the only
way to solve this is to pause iteration, use an http client to send the buffered request and resume the filter stack afterward ?

**Comment by mattklein123** [comment]
@Charana123 sorry this is going to require some code splunking to understand Envoy and develop a solution I would start by studying the router filter, async client, etc.
