### ISSUE TITLE
Cors sub domains cache issue?

### ISSUE THREAD

**Issue by walterfranssen** [envoyproxy/envoy#10694]
*Description*:
We have to subdomains like test1.test.nl and test2.test.nl and we use envoy as a gateway and its has subdomain gateway.test.nl.

if i go to the application on test1.test.nl everything is fine. But if i go 2 test2.test.nl i get a cors error. If i look to the request the allow-origin has the value:
access-control-allow-origin: https://**test1**.test.nl
access-control-expose-headers: Content-Disposition,If-Modified-Since,Location,Last-Modified
content-encoding: gzip
content-type: application/json; charset=utf-8
date: Wed, 08 Apr 2020 06:49:59 GMT
if-modified-since: Mon, 06 Jan 2020 13:54:05 GMT
last-modified: Mon, 06 Jan 2020 13:54:05 GMT
server: envoy
status: 200
vary: Accept-Encoding
x-envoy-upstream-service-time: 5
Referer: https://test2.test.nl/

Our configuration is like:

          route_config:
            name: test_route
            virtual_hosts:
            - name: test_services
              domains:
              - "*"
              cors:
                allow_origin_string_match:
                  - safe_regex:
                      google_re2: {}
                      regex: https:\/\/.*(test.nl|production.nl)
                allow_headers: "Accept,Accept-Encoding,Accept-Language,Content-Type,Content-Length,User-Agent,Referer,Authorization,Cookies,Host,Origin,Connection,Sec-Fetch-Mode,Sec-Fetch-Mode,Sec-Fetch-Site,X-Requested-With"
                allow_credentials: true
                allow_methods: GET,PUT,DELETE,POST,OPTIONS
                expose_headers: "Content-Disposition,If-Modified-Since,Location,Last-Modified"

Is something wrong in the config?

**Comment by mattklein123** [comment]
cc @dschaller

**Comment by walterfranssen** [comment]
sorry, probleem was that some microservice use the If-Modified-Since header in the response.
