### ISSUE TITLE
thrift proxy test driver dependencies

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#10701]
Envoy's thrift proxy network filter uses some python code to generate a variety of requests and responses in the various combinations of thrift transport and protocol that are support. One of the supported protocols, colloquially known as "ttwitter", is no longer supported in python and is not compatible with python3, blocking #4552.

The actual python3 incompatibility is in the twitter.common.rpc package and involves a type check against `long`, which no longer exists in python3. The fix is simple, but as the package is no longer support I don't expect we'll see an update. 

This issue enumerates so possible paths forward:

1. It's fairly simple to patch the library to remove the check for `long`. I think this is reasonable in the short-term.

2. Bring the unsupported twitter.common.rpc code into the envoyproxy org (not necessarily envoyproxy/envoy), and fix it. I dislike this path because the entire point of using external libraries was to test against a different implementation of the protocol. If the protocol were ever updated (and it does have a versioning provision) we'd be implementing both sides of the integration test.

3. Thrift supports other languages besides python and it should be possible to rewrite the code in `test/extensions/filters/network/thrift_proxy/driver` in another language. Java seems the mostly likely candidate since it's supported by bazel and has support for all the variations of thrift. I think we'd want to put that code in a new repository (under the envoyproxy org) and treat the entire payload generating structure as an external dependency.

4. Deprecate ttwitter support and delete usage of the abandoned libraries. I don't have a sense of how much the ttwitter thrift protocol is used in conjunction with Envoy so I don't know how to gauge how painful this would be to end users.

**Comment by zuercher** [comment]
#10702 implements the first option above.

**Comment by rgs1** [comment]
I think we should get started with option 4 (deprecate ttwitter and remove the abandoned tests), I am happy to drive. I pinged @mattklein123 offline to get a sense of whether other deployments are relying on ttwitter.

cc: @fishcakez @davinci26 @tkovacs-2 @caitong93

**Comment by rgs1** [comment]
@zuercher I think we can close this now that #20466 is done. 

cc: @phlax

**Comment by zuercher** [comment]
For anyone going across this bug in the future -- we chose option 4 and have deprecated the ttwitter protocol.
