### ISSUE TITLE
docs: content width issue 

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#10726]
Page doesn't cover the full width and few big words get out content. 

![image](https://user-images.githubusercontent.com/52198964/78930066-181c3500-7ac1-11ea-8a83-8b5e02ffb783.png)

If we increase width then contents cover inside.

**Comment by lucperkins** [comment]
Excessively long line lengths do readers a tremendous disservice and are universally regarded as a no-no amongst technical writers and UX specialists. I'd recommend keeping paragraph line lengths roughly where they are and using word wrapping/breaking for words that exceed that: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/.

**Comment by mattklein123** [comment]
If I were forced to pick I agree with @lucperkins that we should keep it at the narrow width, but curious to hear the opinions of others.

**Comment by moderation** [comment]
I think there is a middle ground. Agree that excessive line lengths aren't great. But we aren't reading a book here, we are reading technical information about a technical project. Wrapping the long proto strings like `extensions.filters.network.http_connection_manager.v3.ScopedRoutes.ScopeKeyBuilder.FragmentBuilder.HeaderValueExtractor.KvElement` isn't ideal.
The current design forces the content area into a width of 800px. Attached is a screenshot of the page modified to 1800px and the longest of the titles fits.
![Screenshot_2020-04-09_16-33-20](https://user-images.githubusercontent.com/246317/78949432-652be700-7a80-11ea-82a1-0e7789381346.png)
I'd like to see an expansion of the default super narrow 800px context box to 1800px. Even at 1800px it is only roughly just over half of my high resolution display. We should be able to use CSS tricks to ensure this works on mobile screen of smaller width.

**Comment by lucperkins** [comment]
As a professional technical writer I can tell you that the screenshot you include here presents an extremely user-hostile reading experience. UX research suggests that ~80 characters per line is optimal in terms of the amount of work the eye has to do to take in a chunk of text. And it doesn’t particularly matter if it’s in a book or on a screen. The principle still holds.

I implore project maintainers to preserve the integrity of the reading experience.

**Comment by moderation** [comment]
I have zero training in this space and don't try to play an interface and information expert online. Below is the screenshot of my primary screen as it stands today. If you are able to wrap the long proto names that are a core part of Envoy in a way that I can select and copy them into an IDE without breakage, I'm open to seeing it. I still feel the difference here is not knowledge retention when reading a novel, but can I cut and paste key snippets of code into my project and does the code make sense.

![image](https://user-images.githubusercontent.com/246317/78953370-7a5b4280-7a8d-11ea-8d43-4d001c664495.png)

**Comment by mk46** [comment]
@moderation @lucperkins  Can we close the issue or change the width from narrow to full?

**Comment by moderation** [comment]
I'd like to try and test an expansion to 1800px as the default and determine if there is a way to make it mobile friendly.

**Comment by mk46** [comment]
Hi @moderation, I have made some  changes and now content looks like

![image](https://user-images.githubusercontent.com/52198964/79891866-3b2ed900-841f-11ea-8e86-2678381f77b1.png)

Long words are breaking. @lucperkins @moderation May I push PR for that?

**Comment by lucperkins** [comment]
@mk46 Nice! I think that's the way to go.

**Comment by moderation** [comment]
LGTM
