### ISSUE TITLE
bazel --config=libc++ build requires PIC enabled libc++.a/libc++abi.a

### ISSUE THREAD

**Issue by paulnivin** [envoyproxy/envoy#10739]
The envoy libc++ build breaks on OS installs of libc++ (9 release) where libc++.a and libc++abi.a do not use PIC. This includes current official Ubuntu 18.04/Bionic LTS OS builds distributed by both https://apt.llvm.org and Canonical.

Example error:
```
ld.lld: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/lib/llvm-9/lib/libc++.a(algorithm.cpp.o)
>>> referenced by algorithm.cpp
>>>               algorithm.cpp.o:(std::__1::__rs_default::__rs_default()) in archive /usr/lib/llvm-9/lib/libc++.a
```

In prior versions of libc++, PIC was always enabled as the same files were used in both the static and shared libraries. https://reviews.llvm.org/D59248 and https://reviews.llvm.org/D60005 changed this behavior for libc++ and libc++abi respectively.

The pre-built binary Ubuntu tar.xz bundles on https://releases.llvm.org/download.html have libc++.a and libc++abi.a compiled with PIC and these archives are compatible with Envoy's current build setup. I'm unsure why the difference exists between the official .deb and .tar.xz bundles, but given the above llvm work, it seems that disabling PIC for libc++.a was intentional.

Allowing lld to use the shared library versions of libc++ enables the build to succeed:

```
bazel build --config=libc++ --action_env=BAZEL_LINKLIBS=-lc++:-lc++abi:-lm //source/exe:envoy-static
```

Would it be reasonable to file a PR to add a bazel config of "libc++-shared" to envoy's .bazelrc with the above BAZEL_LINKLIBS to be used for OS distributions where libc++.a is not compiled with PIC?

**Comment by mattklein123** [comment]
In general:
1) Static linking of the C++ std lib is preferred
2) We need PIC to do ASLR, etc.

So in general it would be better to actually figure out how to deal with this in the common case where we want everything static linked. cc @keith @lizan for further thoughts.

**Comment by lizan** [comment]
Yes for those purpose we do static link. I think you can do dynamic linking of libc++ with just adding `--host_linkopt=-lc++ --linkopt=-lc++` to bazel.

**Comment by paulnivin** [comment]
@lizan envoy does not build on current Ubuntu using the official upstream libc++ packages, as it cannot statically link libc++.a. If this is intended, can we update the docs to state that libc++.a must be compiled with PIC support for the default envoy builds?

Related, my understanding is that Android has the same PIC build requirement on libc++.a as envoy does, so they vendor it.

**Comment by lizan** [comment]
Yes it doesn't build since libc++-9 and we switched to use tar.xz package from upstream LLVM, and that's what we vendored in the envoy-build-ubuntu image.

>  If this is intended, can we update the docs to state that libc++.a must be compiled with PIC support for the default envoy builds?

Yes sure.
