### ISSUE TITLE
Reflect xDS version as a TextReadout stats

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10736]
Now that https://github.com/envoyproxy/envoy/pull/10639 provides a true text stat, we should be able to reflect the exact xDS version, rather than a hash. See related https://github.com/envoyproxy/envoy/issues/2172.

**Comment by efimki** [comment]
@htuch do you have a pointer where would this need to be added?

**Comment by htuch** [comment]
Grep around for ` stats_.version_.set(HashUtil::xxHash64(`, those are the sites that we currently take a hash of the version and place it in a stat.

**Comment by mattklein123** [comment]
Note that we can't change the old stats since not all backends support text readout, but we can add a new stat for this.
