### ISSUE TITLE
Document LoadReportingService

### ISSUE THREAD

**Issue by jamessynge** [envoyproxy/envoy#10749]
The proto for the rpc method LoadReportingService.StreamLoadStats provides an overview, but no hint as to how one would configure Envoy to initiate a connection. Digging through the code leads to a field called load_stats_config, but not much more info, certainly no examples. It would be helpful to have this documented.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/tree/master/examples/load-reporting-service. @kathan24 did some great work here creating an example. It would be nice to further weave this into the docs though. PRs definitely appreciated as @kathan24 also found this very confusing to get started with.

**Comment by mattklein123** [comment]
Looks like this is a dup of https://github.com/envoyproxy/envoy/issues/9651

**Comment by kathan24** [comment]
@jamessynge feel free to reach out on slack if you need any help with LRS
