### ISSUE TITLE
stats_tags - Allow fixed_value in TagSpecifier with regex to select metrics

### ISSUE THREAD

**Issue by murray-stripe** [envoyproxy/envoy#10751]
*Title*: *Support static tag-values, using a regex to match metrics in which it applies*

*Description*:

I have a deployment in which I need to apply a fixed tag-value to a sub-set of Envoy metrics. The existing support for tagging metrics via `StatsConfig.stats_tags` is very close to what I need and I am curious if the Envoy project would consider expanding functionality here.

Specifically I would like to provide a configuration such as:
```
"status_config": {
    "stats_tags": [
        {
            "tag_name": "some_foo",
            "fixed_value_filtered": {
                "value": "some_foo_value",
                "match_regex": "^cluster"
            }
        },
        {
            "tag_name": "some_bar",
            "fixed_value_filtered": {
                "value": "some_bar_value",
                "match_regex": "^http"
            }
        }
    ]
}
```

This would provide the tag `some_foo=some_foo_value` to all `cluster*` metrics and `some_var=some_bar_value` to all `http*` metrics.

Alternatively, the `match_regex` list could be `inclusion_list` with a type of [`type.matcher.v3.ListStringMatcher`](https://github.com/envoyproxy/envoy/blob/0c9cc0ee00fa263161db3ad26444e6ee62fb9fb8/api/envoy/type/matcher/v3/string.proto#L65).

I imagine that this could be an additional option added to the [`oneof tag_value`](https://github.com/envoyproxy/envoy/blob/0c9cc0ee00fa263161db3ad26444e6ee62fb9fb8/api/envoy/config/metrics/v3/stats.proto#L200) fields in order to avoid breaking backwards compatibility.

Thoughts? __Also, if this is something that the envoy team is okay with, I can dedicate my time to putting together a PR.__

**Comment by yanavlasov** [comment]
@jmarantz

**Comment by murray-stripe** [comment]
Hey @jmarantz, just bumping this. I have bandwidth to work on this now, but was hoping to discuss this a bit with the team to see if this is a good idea or if there is any feedback on how to approach this.

**Comment by jmarantz** [comment]
Hi @murray-stripe -- I am actually not super-familiar with the use of tags personally; I did a ton of work to make them less slow to init as the config scales.

If you are going to use REs would you consider taking over https://github.com/envoyproxy/envoy/pull/8831 which adds RE2 support generally, and have your new options only use RE2?

On the subject of the tag usage model, you should probably loop in other maintainers to get opinions on how your extensions would fit in. 

Thanks!

**Comment by murray-stripe** [comment]
@jmarantz I wouldn't mind taking on that work if you could give me a little context on the change and the goals and scope. The ticket is a little light on details.

cc @htuch @yanavlasov Hoping you all might know (or be) the right people to ping on this ticket.

**Comment by htuch** [comment]
Folks who can probably make informed comments on tag history and direction are @mrice32 and @snowp. What you propose sounds reasonable to me.

**Comment by jmarantz** [comment]
Context on #8831 was that I was researching some perf data for a couple of conference presentations I did last fall (one at EnvoyCon), as a way to demonstrate the impact on init-time of using RE2 rather than std::regex. The discovery was that changing a single tag-matching regex to RE2 improved startup latency by 10%, with a large number of clusters.

We could just merge master and get that reviewed, but I thought it really opens up a bunch of follow-up about converting all (or most) of the other tag-matcher regexes to RE2 as well, and not all of them can be converted that easily.

More broadly in Envoy we are trying to shift to RE2 and we should consider std::regex deprecated for at least 2 reasons (better performance, and that it doesn't throw exceptions).

**Comment by murray-stripe** [comment]
@jmarantz Thank you for the context! :-)

While I'm am definitely on-board using RE2, and even taking over the PR, I don't believe I have the time (or am knowledgeable enough ATM) to take on refactors of all existing regex usage (hoping that is not what you were inferring by taking over the work). I don't mind getting the PR updated and merged and then implementing my change using RE2.
