### ISSUE TITLE
grpc_web_reverse_bridge filter: design proposal

### ISSUE THREAD

**Issue by gary-lo** [envoyproxy/envoy#10760]
### Add a grpc_web_reverse_bridge filter that can be used by Envoy Mobile to unblock native clients who have an http1 limitation on any network hop as well as having a consistent stack with browsers.

![gRPC-Web](https://www.cncf.io/wp-content/uploads/2018/10/1.png)

*Description*:
Envoy on the server through (https://github.com/grpc/grpc/pull/8667) allow for servers to transparently support the grpc-web protocol. However gRPC-web officially only supports Javascript clients. Native Clients however often have the same limitations that gRPC-web solves for. However, there isn't any official way for native clients to talk gRPC-web protocol to the server. By creating a client for gRPC-web this will help create an end to end HTTP1 compatible gRPC-web experience.
 
```
The gRPC-Web spec starts from the point of view of the HTTP/2 spec, and then defines the differences. These notably include:

Supporting both HTTP/1.1 and HTTP/2.
Sending of gRPC trailers at the very end of request/response bodies as indicated by a new bit in the gRPC message header 4.
A mandatory proxy for translating between gRPC-Web requests and gRPC HTTP/2 responses.
```
[gRPC Blog](https://grpc.io/blog/state-of-grpc-web/)

The above situations are quite a common limitation on popular infrastructure stacks, people using AWS load balancers or popular EDGE provider such as Cloudflare, Akamai, and Cloudfront enforce HTTP1 to origin, as such gRPC-web is a great solution, however, a client counterpart is missing as gRPC-web is officially JS only library.
[CF HTTP1 to Origin](https://support.cloudflare.com/hc/en-us/articles/200168076-Understanding-Cloudflare-HTTP-2-and-HTTP-3-Support)
[Akamai HTTP1 to Origin](https://community.akamai.com/customers/s/question/0D50f00006Qr9DqCAJ/does-akamai-support-http2-from-origin-to-edge?language=en_US)
[CloudFront HTTP1 to Origin](https://aws.amazon.com/blogs/aws/new-http2-support-for-cloudfront/)

gRPC Load Balancing
[Rokt gRPC on AWS](https://rokt.com/engineering_blog/learnings-grpc-aws/)
[Load balancing on Bugsnag](https://www.bugsnag.com/blog/envoy)

**Comment by lizan** [comment]
IIUC the request here is to create a reverse grpc-web filter, which is similar to what `grpc_http1_reverse_bridge` does to `grpc_http1_bridge`. I'm not object to implement such a filter, though meanwhile you should be also able to try those filter to workaround those edge / lb doesn't support http2 to origin.

**Comment by gary-lo** [comment]
Correct. Thanks for the reply @lizan, you worded that much better than I. I've updated the issue.

Is it correct to assume for our web clients to use, we have to use grpc-web? Or is there some way to also use `grpc_http1_reverse_bridge` for web also?

Not an expert on ` grpc_http1_reverse_bridge/grpc_http1_bridge` but what are the major differences between the bridge and grpc-web?

**Comment by lizan** [comment]
> Is it correct to assume for our web clients to use grpc, we will have to use grpc-web? Or is there an equivalent way of applying a `grpc_http1_reverse_bridge` for web clients also?

Right, if you have JS client you have to use grpc-web. They shouldn't interfere each other so you should be able to do both in same Envoy.
