### ISSUE TITLE
access log: grpc access log grows unboundly if backend is slow

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#10764]
gRPC access log has no back pressure in case if backend can not keep up with the load. In this case it starts buffering all entries without any upper bound.

In a sense it is similar to #9458 but for other types of loggers.

In order to avoid OOM situations Envoy should:
1. Limit memory usage of buffered entries.
2. Drop new entries after some threshold (which can default to smth like 1MB).
3. Emit metric for number of dropped log entries.

**Comment by mattklein123** [comment]
I think the issue here is that we don't actually expose the high/low watermark events in the async client case. I think the correct fix here is to make sure that the router watermark events are exposed in the async client, and then in streaming cases the users of the client can respond to them and do what they think is best (reset, drop, etc.). cc @alyssawilk

**Comment by alyssawilk** [comment]
I'm happy to do the "exposing to user of async client" bit, but do you have thoughts on what the drop bits would look like?  If it's just early return and increment a stat on the log call I can pick that up.  If we're going to plumb something more complicated through so high value logs get logged during overload, I'd pass it off to someone with greater logging enthusiam :-P

**Comment by euroelessar** [comment]
I was thinking about something as simple as just dropping all log entries while buffer is above some watermark and incrementing corresponding stat.

**Comment by alyssawilk** [comment]
SG.  This is mildly complicated by the fact the access loggers didn't have stats, and I'm not sure if I can get away with only adding stats for the gRPC access logger. We'll see how the review goes :-P
