### ISSUE TITLE
HTTP/1.0 and keep-alive bug?

### ISSUE THREAD

**Issue by FqqCS** [envoyproxy/envoy#10769]
I was testing envoy server with ab (Apache Bench) and it turns out that if you enable the -k (keepalive) option, ab just hangs.

Turns out that ab uses HTTP/1.0 requests. It sends a Connection: keep-alive header, and i enabed http1.0 in envoy server. envoy does keep the connection alive, but it does not add a Connection: keep-alive header to the reply. ab assumes that the server does not support keep-alive, and waits for the server to close the connection, and as a result ab hangs until timout.

Envoy should probably add a Connection: keep-alive header to the response if it is found in the request, the request protocol is HTTP/1.0 and there's no Connection header in the Response object present yet.

I tried response_headers_to_add ; but it does not work. 

ab testing

ab -c 1 -n 2 -v 3 -k http://127.0.0.1/test
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...INFO: GET header ==
---
GET /test HTTP/1.0
Connection: Keep-Alive
Host: 127.0.0.1
User-Agent: ApacheBench/2.3
Accept: */*

---
LOG: header received:
HTTP/1.0 200 OK
server: envoy
date: Tue, 14 Apr 2020 07:52:22 GMT
content-type: application/octet-stream,text/html
x-envoy-upstream-service-time: 1

LOG: Response code = 200
apr_pollset_poll: The timeout specified has expired (70007)

route yaml
- match:
                  safe_regex: 
                    google_re2: 
                      max_program_size: 100 
                    regex: "^/test.*" 
                route:
                  cluster: local_service2
                name: "test"
                response_headers_to_add: 
                  header:
                    key: "connection"
                    value: "keep-alive"
                  append: true

**Comment by mattklein123** [comment]
This was already fixed: https://github.com/envoyproxy/envoy/issues/9797

**Comment by FqqCS** [comment]
tks
