### ISSUE TITLE
[docs] Link for deprecated log is broken

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#10771]
[Deprecated.md](https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md) contains a link named "deprecation log" that redirects to https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated with 404 response code.

**Comment by moderation** [comment]
I think this will be fixed by https://github.com/envoyproxy/envoy/pull/10754

**Comment by mk46** [comment]
Hi @mattklein123,  The deprecation log file is removed as per Deprecation Policy. Can we remove [DEPRECATED.md](https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md) ?

**Comment by mattklein123** [comment]
Let's track this in https://github.com/envoyproxy/envoy/pull/10754
