### ISSUE TITLE
[Question] Example for request_id_extension

### ISSUE THREAD

**Issue by a-sharma11** [envoyproxy/envoy#10772]
Background - I created an issue https://github.com/envoyproxy/envoy/issues/7804 which is closed using https://github.com/envoyproxy/envoy/issues/7624. From the documentation i am not able to figure out how to use this `request_id_extension`. Can someone provide an example of how to use `request_id_extension` to accomplish the behavior i need for https://github.com/envoyproxy/envoy/issues/7804

Attaching few folks involved in the pr
@euroelessar @rossdylan

**Comment by euroelessar** [comment]
There is an [example in tests](https://github.com/envoyproxy/envoy/blob/656697d938f3024b39b5e679af540a258c58cf2e/test/extensions/filters/network/http_connection_manager/config_test.cc#L1460-L1497), but I fear no real world one.
A general idea is that this configuration requires extending envoy using C++ plugin.

It should be possible to provide some alternative request-id extension implementations in upstream as well, assuming there are some well-known formats. @mattklein123 what do you think?
