### ISSUE TITLE
wasm: allow non-proto configuration

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#10781]
Currently, Wasm extension requires a proto for the module configuration: https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/wasm/v3/wasm.proto#L40

It is not clear how to use this Any field. The host generally does not have the protobuf schema for the module configuration (it's not compiled in). So all the envoy tooling dealing with protos is not effective.

Additionally, it creates an expectation that the module uses protos for its configuration. This is problematic since a minimal Wasm module with protobuf in it is over 1MB in size. 

The request is to change it back to `bytes`. The module should decide whether to use protobuf or just JSON.

cc @jplevyak @lizan

**Comment by lizan** [comment]
> Additionally, it creates an expectation that the module uses protos for its configuration. This is problematic since a minimal Wasm module with protobuf in it is over 1MB in size.

No, that's not the expectation. Feel free to wrap `google.protobuf.Struct` for JSON or `google.protobuf.BytesValue` for any arbitrary config type in the Any.

**Comment by kyessenov** [comment]
> > Additionally, it creates an expectation that the module uses protos for its configuration. This is problematic since a minimal Wasm module with protobuf in it is over 1MB in size.
> 
> No, that's not the expectation. Feel free to wrap `google.protobuf.Struct` for JSON or `google.protobuf.BytesValue` for any arbitrary config type in the Any.

How does Envoy decide what to do with Any in the filter? Wasm ABI supports only passing binary blob. If it's Any, then the expectation is that the bytes in Any are passed, meaning the module gets a protobuf. It doesn't seem to help understanding that Bytes must be implicitly within Any, compared to we could just `bytes`.

**Comment by lizan** [comment]
> How does Envoy decide what to do with Any in the filter? Wasm ABI supports only passing binary blob. If it's Any, then the expectation is that the bytes in Any are passed, meaning the module gets a protobuf. It doesn't seem to help understanding that Bytes must be implicitly within Any, compared to we could just use bytes.

Depends on how Envoy-WASM filter is implemented. We can specialize on BytesValue and Struct (i.e. convert it to JSON), having raw bytes in configuration reduces the config readability significantly.

Also, considering when we start converting some of current native Envoy extension to WASM (perhaps some via NullVM), we still need whole Envoy tooling dealing with protos. So we can't remove the type_url part from the API.

**Comment by kyessenov** [comment]
I really don't think proxy-wasm should be biased towards protos for the config. That means the ABI layer should just pass serialized Any to the filter. In the current situation, this is just adding another serialization step of Any->bytes on load, white it could have bytes and optimistically de-serialize as Any for all the tooling related work. Type URL does not exist as a concept for Wasm extensions.

Specialization to Bytes/Struct would work, but it's extremely awkward for a user to write those Anys. At least in Istio, we're just using plain JSON for authoring, so writing base64 encoders for Any bytes is far from usable.

**Comment by lizan** [comment]
> I really don't think proxy-wasm should be biased towards protos for the config. That means the ABI layer should just pass serialized Any to the filter. In the current situation, this is just adding another serialization step of Any->bytes on load, white it could have bytes and optimistically de-serialize as Any for all the tooling related work. Type URL does not exist as a concept for Wasm extensions.

I'm not arguing to change proxy-wasm ABI at all. I meant the Envoy host implementation should do specialization to the proto API we have for Envoy. So before Envoy passing the configuration to proxy-wasm ABI, it does specialization based on what in Any. So we still keep the type url in Envoy world, and also leave the room for the API tooling to be kicked in.


> Specialization to Bytes/Struct would work, but it's extremely awkward for a user to write those Anys. At least in Istio, we're just using plain JSON for authoring, so writing base64 encoders for Any bytes is far from usable. All the readability is already lost with Any, but now it's also harder to write due to proto type URL requirements.

You have to write base64 encoded for `bytes` so it is as awkward as, but for all cases. The readability is not lost with Any for Struct and all other know types. In Istio we can be opinionated to JSON only so Pilot always emit Struct-in-Any or Bytes-in-Any for the filters, but Struct-in-Any still have way better readability than raw bytes. We discussed this in the API PR and decided to use Any to support those cases.

**Comment by kyessenov** [comment]
Well, I think it boils down to performance I suppose. I really don't see why Envoy would need to do anything more than pass-through the module config as-is (and all these roundtrips to JSON/proto have a cost) for generic Wasm extensions (not the future Envoy extensions). There's a big difference between how Envoy loads extensions and Wasm loads extensions (it's many-to-many for Wasm).

In Istio, we primarily rely on EnvoyFilter, so it really doesn't matter if there is an intermediate Any. It's easy to embed a literal JSON in YAML in k8s configs.

The action item should be to update the spec to specify Bytes/JSON specialization. Those two types in Any need to be serialized back to bytes and passed as-is.

**Comment by lizan** [comment]
> Well, I think it boils down to performance I suppose. I really don't see why Envoy would need to do anything more than pass-through the module config as-is (and all these roundtrips to JSON/proto have a cost) for generic Wasm extensions (not the future Envoy extensions). There's a big difference between how Envoy loads extensions and Wasm loads extensions (it's many-to-many for Wasm).

The conversion can still only happen only once when Envoy load configuration (from file or xDS), and then cached what is supposed to pass via ABI, no?

**Comment by kyessenov** [comment]
Yes, it could be optimized to cache once. But the conversion is still unnecessary if the module consumes bytes, and that applies to the control planes, and all the listeners that consume it.

**Comment by yskopets** [comment]
Sorry to barge in.

I don't agree with #10782, so I'd like to ask you to consider one more perspective.

I think, it should be completely up to a Wasm extension to choose its configuration format:
* it can be plain text
* it can be JSON/YAML
* it can be Protobuf

Developer of a Wasm extension should be able to design and document this format independently from Envoy API constraints.

Users of a Wasm extension should be able to copy and paste configuration snippets from the extension's documentation.

Users of a Wasm extension should not be concerned with how to translate these snippets into Protobuf Struct format.

So, I don't agree with #10782 because it effectively forces all Wasm extensions to expect configuration in JSON format:
> `google.protobuf.Struct` and `google.protobuf.Value` are serialized as JSON before passing them to the plugin


I can propose an alternative set of guidelines for using `Any` in the context of Wasm extensions:
* document that at the moment `Any` can be either `google.protobuf.StringValue` or `google.protobuf.BytesValue`
* if a Wasm extension uses text configuration format (plain test, JSON, YAML), Envoy configuration should use `google.protobuf.StringValue` to wrap the original string value
* if a Wasm extension uses binary configuration format (Protobuf), Envoy configuration should use `google.protobuf.BytesValue` to wrap the original byte array value
* in both cases, Envoy's behaviour is limited to simply unwrapping and passing configuration data "as is"

As a side note, I don't understand the benefits of `google.protobuf.Struct` in this context:
* I would expect that users of a Wasm extension will naturally prefer to provide configuration in the original format supported by the extension (JSON/YAML)
* which means that it becomes a responsibility of a Control Plane to convert JSON string into `google.protobuf.Struct`
* and later Envoy has to do the reverse conversion

So, why do we need this use case ?

**Comment by kyessenov** [comment]
I think the crux of the issue is the perceived requirement to have type URL in the configuration blob to align with Envoy API standards. We should understand whether that's realistic at all, and if not, allow a `oneof` with one Envoy-specific configuration format for future Envoy extensions rewritten into Wasm, and another entirely opaque string/blob.

As a data point, I just converted an extension to not use protobuf struct to load its config in Wasm, and the size of the binary dropped from 1.1MB to 180KB. The gains are enormous.

**Comment by lizan** [comment]
> As a side note, I don't understand the benefits of `google.protobuf.Struct` in this context:
> 
> * I would expect that users of a Wasm extension will naturally prefer to provide configuration in the original format supported by the extension (JSON/YAML)
> * which means that it becomes a responsibility of a Control Plane to convert JSON string into `google.protobuf.Struct`
> * and later Envoy has to do the reverse conversion
> 
> So, why do we need this use case ?

@yskopets The benefit of google.protobuf.Struct as a normalized JSON, for example, instead of having a JSON/YAML escaped as a string in configuration like:

```
configuration:
  "@type": google.protobuf.StringValue
  value: '{"key":"value", "nested": {"foo": "bar"}'
```

which can be

```
configuration:
  "@type": google.protobuf.Struct
  key: value
  nested: 
    foo: bar
```

It also allows Envoy to reject the malformed JSON (e.g. syntax error) at xDS layer before passing it to WASM binary.

**Comment by lizan** [comment]
> I think the crux of the issue is the perceived requirement to have type URL in the configuration blob to align with Envoy API standards. We should understand whether that's realistic at all, and if not, allow a `oneof` with one Envoy-specific configuration format for future Envoy extensions rewritten into Wasm, and another entirely opaque string/blob.

We took long path to deprecate the `oneof`s for opaque config and even requires Structs have type_url as TypedStruct. Unless there's critical performance implication, which I don't think `oneof` improves much here. cc @htuch

**Comment by kyessenov** [comment]
Using embedded YAMLs, it doesn't look that bad if we're speaking about human authoring:

```yaml
configuration: |
    { 
      "key": value",
      "nested": {
          "foo" : "bar"
      }
    }
```

**Comment by mattklein123** [comment]
I agree with @lizan on this. It took a monumental amount of effort to converge on typed_config, and I would rather not go back to having multiple variants that we can load from. Given that we can specialize as has been suggested (we can add strings if we want per @yskopets) this seems like a reasonable compromise to me that would not require bloating the WASM module to support proto if they don't want?

**Comment by kyessenov** [comment]
I'm OK with using a wrapper for raw content. It really hurts comprehension IMHO, as we now have to put JSON into StringValue into Value into Any, but it'd work.

**Comment by mattklein123** [comment]
> as we now have to put JSON into StringValue into Value into Any, but it'd work.

Why can't you put it in a struct as has been suggested?

**Comment by kyessenov** [comment]
We could. But given we don't know if it's actually a struct or a string for a third party extension, we'd have to use something generic like a string value in the tooling.

**Comment by yskopets** [comment]
@lizan Thanks for clarifying `google.protobuf.Struct`!

It is now my understanding that if we know that a target Wasm extension uses JSON/YAML for its configuration, `google.protobuf.Struct` will a be a preferred way to deliver it (at least, it will look much more readable in the output of `/config_dump`).

**Comment by yskopets** [comment]
@kyessenov 

> I'm OK with using a wrapper for raw content. It really hurts comprehension IMHO, as we now have to put JSON into StringValue into Value into Any, but it'd work.

Why do you need 2 wrappers ( `Value ( StringValue ( data ) ) ` ) ?

Why `google.protobuf.StringValue` is not enough ?

**Comment by yskopets** [comment]
@kyessenov 

> We could. But given that we don't know if it's actually a struct or a string for a third party extension, we'd have to use something generic like a string value in the tooling.

Control Plane could optimistically try to parse configuration of a Wasm extension as YAML:
* if it is successful, use `google.protobuf.Struct` to deliver this configuration to Envoy
* otherwise, use `google.protobuf.StringValue`

**Comment by htuch** [comment]
I think there are two separate things here:
1. How do we deliver config to Envoy; `Any` seems super flexible, given it's basically a typed byte array.
2. How do Wasm extensions consume this config from Envoy. I think what I'm seeing above is the plan is to have Envoy be able to pass in JSON directly when it receives a `google.protobuf.Struct`. This makes sense to me; Envoy has the heavy protobuf machinery, Wasm can just think in terms of JSON.
