### ISSUE TITLE
manifest unknown on image pull docker

### ISSUE THREAD

**Issue by nbeny** [envoyproxy/envoy#10785]
*Title*: docker pull envoyproxy/envoy

*Description*:
When I trying to pull the docker image I got this error for image 'envoyproxy/envoy' and 'envoyproxy/envoy-alpine':
failed to build: manifest for envoyproxy/envoy:latest not found: manifest unknown: manifest unknown

It's working of course for every other image not from envoy. I try to specify the version and I got the same error..

**Comment by mk46** [comment]
Hi @nbeny, This issue is already [10738](https://github.com/envoyproxy/envoy/issues/10738) here.

**Comment by nbeny** [comment]
nice, thanks !
