### ISSUE TITLE
proposal: introduce a new extension point `core.ExtensionDataSource`

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#10795]
*Title*: introduce a new extension point `core.ExtensionDataSource`

*Context*:
* at the moment, Envoy already has `core.DataSource`, `core.RemoteDataSource` and `core.AsyncDataSource`
* the goal of `core.ExtensionDataSource` is to allow Envoy-based distributions to support custom data sources

*Proposal*:
* Define `core.ExtensionDataSource`
  ```protobuf
  package envoy.config.core.v3; 
 
  message ExtensionDataSource {

    string name = 1;

    google.protobuf.Any typed_config = 2;
  }
  ```
* Add `core.ExtensionDataSource` as an option to `core.AsyncDataSource`
  ```protobuf
  package envoy.config.core.v3;

  message AsyncDataSource {
    oneof specifier {
      option (validate.required) = true;

      // Local async data source.
      DataSource local = 1;

      // Remote async data source.
      RemoteDataSource remote = 2;

      // Extension async data source.
      ExtensionDataSource extension_source = 3;
    }
  }
  ```
* Define `ExtensionDataSourceFactory`
* Add a new case to the logic that handles `core.AsyncDataSource` (actually, I don't see it in the upstream Envoy repo)

**Comment by mattklein123** [comment]
This sounds reasonable to me. cc @envoyproxy/api-shepherds

**Comment by htuch** [comment]
Seems reasonable if we have a few potential implementations of this that are likely to be built. @yskopets can you talk a bit about motivation?

**Comment by yskopets** [comment]
@htuch 

We're trying to improve user experience with Envoy configuration.

Specifically, `core.RemoteDataSource` is too strict and low-level:
* it mandates a user to explicitly configure a `Cluster`
* it mandates a user to explicitly provide a checksum

User's focus is immediately shifted away from the original intention - just get my artifact into Envoy now and I will decide later how to harden configuration for production readiness. 

Having `core.ExtensionDataSource` will allow us to offer users higher-level building blocks, e.g.

```yaml
config:
  extension_source:
    typed_config:
      '@type': type.googleapis.com/com.example.artifacts.BintrayArtifact
      org: com.example
      artifact: something
      version: 1.2.3 
``` 

It's not a goal to implement all these datasources inside Envoy itself.

Instead, it's a responsibility of a standalone pre-processor/federated control plane/xds-relay (if I understand the scope of these projects correctly) to translate `BintrayArtifact` into `core.RemoteDataSource` or `core.DataSource`.

**Comment by htuch** [comment]
This is a pretty sophisticated use of the extension, as an intermediate representation, but sure, I can see this being generally useful.
