### ISSUE TITLE
request_id: Allow always setting x-request-id header in response

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#10807]
*Description*:
Currently non-configurable Envoy behavior is to return `x-request-id` header in response iff the tracing is forced.
It would be nice to have a configuration option to allow always returning the header in response.

It is especially useful for cross-correlating client-side debug logs with access logs on server side.

**Comment by mattklein123** [comment]
I thought we already had an issue on this but I can't quickly find it, +1.
