### ISSUE TITLE
[Help wanted] how to configure envoy to send http notification to all the members in the cluster without load balancing (broadcast)?

### ISSUE THREAD

**Issue by vsharathis** [envoyproxy/envoy#10804]
existing configuration sending a notification to the only one pod based on the lb_policy =Round Robin, but we have a case to send the notification to the all the members of the cluster (like a broadcast) , Kindly do the needful to solve the problem,

**Envoy version: 1.14.2**

- '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: envoy-ueauth-envoy-2-0
  type: STRICT_DNS
  connect_timeout:
    seconds: 18
  http2_protocol_options: {}
  lb_policy: ROUND_ROBIN
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      common_tls_context:
        tls_certificates:
        - certificate_chain:
            filename: "/aus-certs/server.pem"
          private_key:
            filename: "/aus-certs/key.pem"
          password:
            inline_string: "server@123"
        validation_context:
          trusted_ca:
            filename: "/aus-certs/trusted.pem"
        alpn_protocols: [ "h2", "http/1.1" ]
  dns_resolvers:
  - socket_address:
      address: 127.0.0.1
      port_value: 8600
      protocol: UDP
  load_assignment:
    cluster_name: envoy-ueauth-envoy-2-0
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: "192.168.25.133"
              port_value: "8445"
              protocol: TCP

**Comment by yanavlasov** [comment]
@snowp do you have any suiggestions?

**Comment by vsharathis** [comment]
@snowp Kindly share your thoughts to solve the problem. and thanks in advance

**Comment by snowp** [comment]
This is not something that's currently supported, so this would be have to be a feature request. 

I can imagine this being implemented as a new route action (broadcast to all hosts for a given cluster) or even as a separate filter if we want to avoid adding the complexity to the router (at the cost of missing out on some router features like `requset_headers_to_add`). 

@mattklein123 might have thoughts on how this would be implemented

**Comment by mattklein123** [comment]
> @mattklein123 might have thoughts on how this would be implemented

Yeah there is no way to do this today. It would require substantial changes to the router or possibly even a new filter to do it. It's certainly possible but would require a lot of design thought and a full proposal.

**Comment by vsharathis** [comment]
@snowp @mattklein123 @yanavlasov Thank you all for the quick response, is there any chance that can be included as a feature in upcoming releases?

**Comment by yanavlasov** [comment]
@vsharathis It is unclear to me if there is anyone else beside you asking for this feature. Can you try implementing it as a filter yourself?

**Comment by slonka** [comment]
> @vsharathis It is unclear to me if there is anyone else beside you asking for this feature. Can you try implementing it as a filter yourself?

I would be interested in such a feature. Can someone point me to how would I implement it in a filter?

**Comment by KiranCS-17** [comment]
We have similar requirement for broadcasting the request to multiple endpoints  in the down stream.
Would be good feature if ENVOY provides this

**Comment by KiranCS-17** [comment]
Could some body help if this facility is given in Envoy or any alternate methods
