### ISSUE TITLE
Reject v2 xDS configuration by default at EOQ3

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10816]
As we end the last quarter of the ability to load deprecated v2 xDS API in Q3 2020, we should switch to rejecting v2 xDS by default (with runtime override). 

Related to https://github.com/envoyproxy/envoy/issues/10815 (warning, rather than rejecting the config).

CC @alyssawilk @mattklein123 @envoyproxy/api-shepherds

**Comment by ankatare** [comment]
@htuch what needs to be done on this. could you please provide some pointers. is it similar to #10815  ?

**Comment by htuch** [comment]
I'll be working on this, I've updated bug status.
