### ISSUE TITLE
X-Ray tracing plugin doesn't publish conformant segment document

### ISSUE THREAD

**Issue by dastbe** [envoyproxy/envoy#10814]
*Title*:  X-Ray tracing plugin doesn't publish conformant segment document

*Description*:

Currently, the X-Ray tracing plugin publishes all fields as strings in the output JSON document. This is in violation of the datatypes defined by [the X-Ray documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-http), and results in X-Ray ignoring this fields when they are sent to the X-Ray service.

*Repro steps*:

Any Envoy configured with X-Ray tracing, for example

```
tracing:
  http:
  name: envoy.tracers.xray
  typed_config:
    "@type": type.googleapis.com/envoy.config.trace.v3.XRayConfig
    segment_name: ${SEGMENT_NAME}
    daemon_endpoint:
    protocol: UDP
    address: ${AWS_XRAY_DAEMON_ADDRESS}
    port_value: ${XRAY_DAEMON_PORT}
```

**Comment by mattklein123** [comment]
cc @marcomagdy

**Comment by marcomagdy** [comment]
@mattklein123 you can assign it to me
