### ISSUE TITLE
Delta xDS protocol question re: requests in flight

### ISSUE THREAD

**Issue by galbacarys** [envoyproxy/envoy#10836]
*Title*: *Delta xDS protocol question re: requests in flight*

*Description*:

After a read of the [xDS protocol docs](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol), I have a couple of questions centering around the implementation of delta xDS:

- According to [this doc](https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/api/v2/core/config_source.proto.html), it seems like the delta protocol (at least as of v1.14.1) is only implemented for CDS, is this in fact the case? If not, what resource types are supported as of v1.14.1?

- Are there any guarantees about the number of requests in flight from the client? i.e., can I assume that a client won't make two successive requests on the same stream for the same resource type without acking previous requests first? The reason I ask is if this is indeed the case, it will make the logic for streaming much easier.

Thanks a bunch!

**Comment by mattklein123** [comment]
cc @htuch @wgallagher this is a common question and it would be great to clarify this somehow via FAQ, etc.

**Comment by htuch** [comment]
Yeah, happy to update the FAQ once we have agreement on the questions here:

> According to this doc, it seems like the delta protocol (at least as of v1.14.1) is only implemented for CDS, is this in fact the case? If not, what resource types are supported as of v1.14.1?

This is stale. I believe all xDS (including ADS) now support delta xDS thanks to the contributions from @fredlas. We only have a single on-demand protocol (VHDS), but I think if you are interested in the delta aspect then this is a doc bug.

> Are there any guarantees about the number of requests in flight from the client? i.e., can I assume that a client won't make two successive requests on the same stream for the same resource type without acking previous requests first? The reason I ask is if this is indeed the case, it will make the logic for streaming much easier.

I don't think this is true. Just as with regular state-of-the-world xDS, it's possible for the client to change its mind about the resources it wants. For example, with EDS, when a CDS update arrives and changes the active clusters, then Envoy will send a new EDS request, even if there is already a `DiscoveryRequest` pending (which is likely, as we generally have a long poll operation).

LMK if that answers your questions and I'll make the FAQ/proto doc changes.

**Comment by galbacarys** [comment]
Appreciate the updates! Please bump the docs, that would be extremely helpful to future learners :) I know that there is some work being done over in https://github.com/envoyproxy/go-control-plane to [support the delta protocol](https://github.com/envoyproxy/go-control-plane/issues/251), and once that work is done I feel like there will be a lot more clarity on how to implement xDS. I think there's a bit of a lack of community support for the protocol, which is a shame because it's _perfect_ for my use case; do y'all happen to know of any examples of the protocol being used to implement a large scale control plane?

**Comment by htuch** [comment]
FAQ and proto doc updates at https://github.com/envoyproxy/envoy/pull/10876.

@galbacarys I don't think delta xDS is widely used yet, once go-control-plane has support here we will have a lot of control planes with this support.
