### ISSUE TITLE
break the established connections when the host was removed

### ISSUE THREAD

**Issue by Future2100** [envoyproxy/envoy#10846]
As the title described, I wish the connections can be broken when the host is removed from xDS configuration. I found the configuration filed `drain_connections_on_host_removal ` and set its value with true, but it doesn't work for me.

**Comment by mattklein123** [comment]
I can't remember where we landed with this. cc @nezdolik who did the original feature around this. Also cc @snowp. I think this is a a reasonable feature to add (if not already supported) but it would need some additional work.

**Comment by snowp** [comment]
I think currently we just mark the connections for draining, no attempt to aggressively tear them down.

 I imagine most use cases could use a combination of timeouts to ensure that connections are closed in a timely manner, but for cases where users want long lived streams I can see the usefulness of wanting to close those streams when the host is removed. 

The implementation shouldn't be too hard if we're just trying to reset the connections, though it would get more complicated if we want to give it some time to gracefully shut down before doing the reset.

**Comment by mattklein123** [comment]
I do agree that the existing feature coupled with both stream/connection idle timeouts might be good enough?

**Comment by Future2100** [comment]
The idle timeouts don't work for me, because the connections are long connection so I must break the connection by force.
