### ISSUE TITLE
transport/resource API version on xDS integration tests

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#10849]
*Description*:
Currently, the transport/resource API version is set V2. I think that we should change them into V3. In addition, we should support multiple resource API versions(V2/V3) for xDS integration test. This is like `downstream/upstream HTTP protocol` or `v4/v6` with `TestWithParam`.

**Comment by htuch** [comment]
I would be worried about combinatorial explosion if we change every test to be v2/v3 with a test param. We already have a dedicated integration test to validate the space of transport/resource versions in https://github.com/envoyproxy/envoy/blob/master/test/integration/api_version_integration_test.cc.

I would advise that we switch most tests over to v3 and retain one legacy integration test for v2, essentially a smoketest.

**Comment by htuch** [comment]
@Shikugawa further thoughts on this one?

**Comment by Shikugawa** [comment]
@htuch I agree with your idea. For the moment, we should transfer the V2 testing to V3 by remaining one of V2 integration test.

**Comment by Shikugawa** [comment]
nostale
