### ISSUE TITLE
Convert v2 API test fragments to v3

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10843]
While all programatically constructed test configs will be v3 (via API boosting rewriting), there are still v2 JSON/YAML fragments in test code. Many of these will "just work" as v3, but some may have v2 features that will have them treated as v2. This becomes confusing when they are extended by developers who want to model v3 features.

These need to be audited and updated as appropriate. Also, the names of methods such as `parseAccessLogFromV2Yaml` should be updated to reflect v3 when operating on fragments that should be v3.

This is somewhat similar to the work done by @dmitri-d for examples in https://github.com/envoyproxy/envoy/pull/10644 as part of https://github.com/envoyproxy/envoy/issues/9735.

CC @alyssawilk

**Comment by ankatare** [comment]
@htuch i would like to work on this as part of beginner in community.

**Comment by htuch** [comment]
@ankatare sure, I sent you an invite to the envoyproxy org so I can assign. I suggest following https://github.com/envoyproxy/envoy/pull/10644, since that already provides a lot of the heavy lifting in terms of examples of what needs to be done.

**Comment by ankatare** [comment]
@htuch  thanks for adding me in member list. as you suggested  let me go through #10644 . I will get back for any doubts.

**Comment by ankatare** [comment]
@htuch i read #10644  and found that changes were made in docs/root directory from V2 API ref to V3 API wherever applicable . from the problem statement for this issue do i need to make similar changes (in json and ymal) inside directory structure ../test/ , please correct if i am wrong.
This has to be done in current development branch ?

**Comment by htuch** [comment]
@ankatare yep, that's the goal.

**Comment by htuch** [comment]
This shouldn't be closed.

**Comment by ankatare** [comment]
@htuch seems it is closed. please reopen

**Comment by alyssawilk** [comment]
@ankatare you can tag your PR with
part of #number 
rather than
Fixes #number 
and it'll stop closing the issue off :-)

**Comment by ankatare** [comment]
@alyssawilk thanks for this suggestion i will tc it from next time.

**Comment by ankatare** [comment]
@alyssawilk would you check this PR#12113. hope now it is fine as per your suggestion ?

**Comment by htuch** [comment]
What's super weird is that I manually modify the commit messages and switch them from "Fixes #123456" to "Part of #123456" when I merge. GitHub still seems to close them out.

**Comment by ankatare** [comment]
@junr03 Hi,  would you please review PR #12058 . it will close this issue if all goes good :)
