### ISSUE TITLE
introduce FilterConfig for HTTP filters

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#10857]
So while thinking about #10164, I realized that it would be much easier to solve if we had a common base Config object to share across HTTP filters (e.g.: `FilterConfig`).

This class would then be the base class for all filter config classes, and we'd extend the abstract base Filter classes (e.g.: StreamFilter, StreamDecoderFilter, etc) to require a FilterConfig parameter to be constructed.

This FilterConfig class would then provide the usual stuff needed by filters (e.g.: context.localInfo(), context.scope(), context.runtime(), context.httpContext(), stats_prefix) which will:

a) reduce some typing and more importantly 
b) make it easier to solve things like #10164.

Unless someone has a strong reason not to do this, I'll send a tentative PR to get the conversation going.

cc: @mattklein123

**Comment by mattklein123** [comment]
> This class would then be the base class for all filter config classes, and we'd extend the abstract base Filter classes (e.g.: StreamFilter, StreamDecoderFilter, etc) to require a FilterConfig parameter to be constructed.

The abstract classes don't actually get constructed though, just the derived classes. Sorry can you flesh out a bit more what problem you are trying to solve?

**Comment by rgs1** [comment]
Right, we'd have make them constructible by adding something like this to include/envoy/http/filter.h:

```
StreamFilter(const std::shared_ptr filter_config) : config_(config) {}
const FilterConfig& config() { return *config_ }
```

I am trying to solve two things:

1) get rid of the duplication across each filter config, e.g.:

```
~/src/envoy/source/extensions/filters/http $ git grep 'runtime()' -- '*.h'
ext_authz/ext_authz.h:  Runtime::Loader& runtime() { return runtime_; }
fault/fault_filter.h:  Runtime::Loader& runtime() { return runtime_; }
ip_tagging/ip_tagging_filter.h:  Runtime::Loader& runtime() { return runtime_; }
ratelimit/ratelimit.h:  Runtime::Loader& runtime() { return runtime_; }
~/src/envoy/source/extensions/filters/http $ git grep 'timeSource()' -- '*.h'
adaptive_concurrency/adaptive_concurrency_filter.h:  TimeSource& timeSource() const { return time_source_; }
fault/fault_filter.h:  TimeSource& timeSource() { return time_source_; }
jwt_authn/filter_config.h:  TimeSource& timeSource() const { return time_source_; }
jwt_authn/filter_config.h:                                 timeSource());
jwt_authn/filter_config.h:        time_source_(context.dispatcher().timeSource()), api_(context.api()) {}
...
etc
...
```

Granted, no big deal here except removing some copy pasta. But, 

2) after this it would be easier to do things like what we talked about in #10164 (e.g.: lookup per filter route configs, and use that as the default way to override global filter configs).

My thinking is that, currently all filters have their own individual configs and it's really hard to share functionality across them.

**Comment by mattklein123** [comment]
I don't think we should change the interfaces to have implementation details. You could potentially add this to the PassThroughFilter variants or another base class?
