### ISSUE TITLE
Support redis command broadcasting to multiple clusters

### ISSUE THREAD

**Issue by inf-rno** [envoyproxy/envoy#10859]
*Title*: Support redis command broadcasting to multiple clusters

*Description*:
Currently, we support asynchronous fire and forget [request mirroring](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#config-filter-network-redis-proxy-v2-redisproxy-prefixroutes-route-requestmirrorpolicy) in the Redis filter. This only broadcasts the commands to a single other cluster. Request mirroring which excludes read commands is a very nice way to best-effort replicate Redis data. And unlike built in Master-Slave [Redis Replication](https://redis.io/topics/replication), this form of write broadcasting can be used for an Active-Active setup. We, at Shopify, would like to extend the current feature to support multiple upstreams for request mirroring.

We propose deprecating the existing `cluster` property under [RequestMirrorPolicy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#config-filter-network-redis-proxy-v2-redisproxy-prefixroutes-route-requestmirrorpolicy) and introduce an array of `clusters` instead with a minimum length of 1.

This is similar to the [change](https://github.com/envoyproxy/envoy/pull/9164) done to the HTTP filter's request mirror policy. The actual request mirroring is pretty [straightforward](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/redis_proxy/command_splitter_impl.cc#L16-L68) and iterating over this array of clusters should not be a concern.

Please let me know what you think and if you agree on the solution and I'll implement it.
Thanks

**Comment by mattklein123** [comment]
cc @envoyproxy/redis-dev but SGTM

**Comment by inf-rno** [comment]
after looking at this a bit longer it looks like this is already possible because `request_mirror_policy` is actually an [array of policies](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#config-filter-network-redis-proxy-v2-redisproxy-prefixroutes-route), so we are already able to do this! I'm not sure if we want to rename this property to be a plural but otherwise I think we can close this. 

Thanks for looking.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
Yes, that's correct you can mirror to multiple clusters at once.
