### ISSUE TITLE
Redis latency statistics

### ISSUE THREAD

**Issue by aviramha** [envoyproxy/envoy#10864]
Hi
I'm using Envoy to collect statistics of Redis and to mirror requests.
The results statistics are very odd, for example 
```cluster.ds.redis_cluster.upstream_commands.hmset.latency: P0(710,470) P25(995,1044.56) P50(1200,1167.84) P75(1344.44,1315.44) P90(1397.78,1629.56) P95(7546.67,3357.73) P99(7589.33,11984.9) P99.5(7594.67,25681.2) P99.9(7598.93,63899.2) P100(7600,130000)```
means that minimum latency for hmset command is 470ms, which is quite a lot and probably wrong.
I'm thinking maybe it's because of usage of pipeline, which leads me to the question how the timers work when commands are pipelined?

**Comment by mattklein123** [comment]
cc @HenryYYang @envoyproxy/redis-dev

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
The command stats should be per command on the upstream. Just for suresies I wrote a little test script to do a few hmsets and added some printfs to the stats code timers, and it definitely is recording hmset time individually.

Some questions for you:

- In your envoy configuration, do you have `latency_in_micros` set to `True`?
- If you run an `hmset` against one of your Redii, what kind of latency do you get?
- How big are your pipelines?
- What's your Redis running on (if EC2, what instance type)? What's the cpu /network/memory usage?

**Comment by aviramha** [comment]
Thanks for your reply @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg .

- No.
- 0.5-3ms
- Pretty big
- Redis Labs (managed)

If the timings are correct, my next lead would be that our pipelines are big hence slowing operation of each connection.. is my reading of the stats correct tho? P0(710,470) means 710ms and 470ms?

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
The unit is microseconds. See https://github.com/jmarantz/envoy/blob/1221cce68ae973fcdea38f27e6f017e492214e28/source/extensions/filters/network/common/redis/redis_command_stats.cc#L36.

Re the output of the admin interface, per Envoy documentation*:

> Histograms will output the computed quantiles i.e P0,P25,P50,P75,P90,P99,P99.9 and P100. The output for each quantile will be in the form of (interval,cumulative) where interval value represents the summary since last flush interval and cumulative value represents the summary since the start of Envoy instance. “No recorded values” in the histogram output indicates that it has not been updated with a value.

*https://www.envoyproxy.io/docs/envoy/latest/operations/admin

**Comment by aviramha** [comment]
Ah! So it's microseconds in that case. I think it needs to be better documented, as it explicitly says that it's milliseconds (atleast rest of statistics) unless you set it to microseconds.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
I've put up a PR to correct the docs: https://github.com/envoyproxy/envoy/pull/11073

I will fix this once I finish with some of my other work. Thanks for bringing to my attention!
