### ISSUE TITLE
Windows: executables built with dbg and fastbuild compilation modes crash on startup with failed absl assertion

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#10877]
*Description*:
Building envoy-static.exe and many (I don't believe it is all, but have not narrowed it down yet) test executables on Windows with fastbuild or debug compilatin modes causes a crash on startup due to a failed assertion:

```
Assertion failed: false && "*next_sample >= 1", file external/com_google_absl/absl/container/internal/hashtablez_sampler.cc, line 202
```

*Repro steps*:
Build `//source/exe/envoy-static` or tests with `-c dbg` or `-c fastbuild` on Windows

**Comment by sunjayBhatia** [comment]
Currently in CI etc. we are only building `opt` mode builds

**Comment by antoniovicente** [comment]
Looks like an https://github.com/abseil/abseil-cpp issue.

**Comment by antoniovicente** [comment]
I'm told it is fixed upstream.  We need to update to latest abseil.

Relevant change:
https://github.com/abseil/abseil-cpp/commit/62f05b1f57ad660e9c09e02ce7d591dcc4d0ca08#diff-d39294eb126ec74b09a131e2ef19918d

**Comment by sunjayBhatia** [comment]
thanks @antoniovicente good call and good find 👍 we can test out bumping abseil and ensure it fixes the issue

**Comment by antoniovicente** [comment]
Did it work?  We should bump up abseil version on the main repo.

**Comment by sunjayBhatia** [comment]
Yes it did, however we ran into some issues with linking other foreign cc dependencies (luajit and moonjit) when using dbg mode. We are locally testing a PR to disable them for the time being as they are only used in extensions so we can have a change set that enables dbg builds in one shot
