### ISSUE TITLE
admin: circuit breaker thresholds not in `/clusters` JSON

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#10897]
The plaintext version of `/clusters` includes the runtime interpolated value for circuit breakers, see [AdminImpl::addCircuitSettings](https://github.com/envoyproxy/envoy/blob/25ccc5f2442300bc31a4975ddff3d572fbc37519/source/server/http/admin.cc#L336-L347).

In practice:
```
$ curl -s 0:9999/clusters | grep priority::max | head -n4
my_cluster::default_priority::max_connections::1024
my_cluster::default_priority::max_pending_requests::1024
my_cluster::default_priority::max_requests::3000
my_cluster::default_priority::max_retries::3
```

The JSON version does not, see [admin/v4alpha/clusters.proto](https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v4alpha/clusters.proto).

Unless this information is available in another admin API, and even if it is, it seems like adding it to the JSON API would be a good idea.

**Comment by mattklein123** [comment]
+1 I would consider this a bug. @tonya11en do you mind fixing this?

**Comment by tonya11en** [comment]
I'm gonna get to this one soon. Spoke to @danielhochman about it today.

**Comment by dio** [comment]
@tonya11en I have submitted a PR for this since we need this (https://github.com/envoyproxy/envoy/pull/13296). However, if you have your PR and you have time to submit it, I'll be happy to close my PR. Thanks!
