### ISSUE TITLE
Does Envoy support per filter chain draining?

### ISSUE THREAD

**Issue by shashankram** [envoyproxy/envoy#10899]
My understanding has been that if a Listener with multiple filter chains is configured and a filter chain within the listener is updated, connections belonging to other filter chains but the same listener are also drained. Is this still the case? 

Looking at a few PRs, I see that there has been some effort to support per filter chain draining:
https://github.com/envoyproxy/envoy/pull/9205
https://github.com/envoyproxy/envoy/issues/4540
https://github.com/envoyproxy/envoy/pull/7246

Is this feature supported now?
What is the recommended listener configuration to drain connections per filter chain? Is a Filter Discovery Service (FDS) required?

**Comment by mattklein123** [comment]
This is almost complete and should work transparently once https://github.com/envoyproxy/envoy/pull/10662 lands (albeit in an alpha state). cc @lambdai

**Comment by shashankram** [comment]
Thanks @mattklein123. To clarify, per filter chain draining would work without needing Filter Discovery Service - using a listener with multiple filter chains would transparently drain connections per filter chain?

**Comment by shashankram** [comment]
@lambdai is there an update on this?

**Comment by shashankram** [comment]
Checking again.

**Comment by vorishirne** [comment]
@shashankram I beleive filter chain draining is fixed. I read in some other issues.
