### ISSUE TITLE
Consider standardizing on more detailed commit messages

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#10891]
As an end user who is not involved day-to-day in Envoy development, I only occasionally need to look at Envoy source code or commit history. Detailed commit messages can help people like me get context on the rapid changes occurring between updates more quickly.

As an example, I was looking into the details of how the max_connections circuit breaker is implemented. In particular, I wanted to know what happens if the runtime circuit breaker value is set lower than the current number of connections.

I noticed that there is both `source/common/http/conn_pool_base.cc` and `source/common/http/http1/conn_pool_legacy.cc` to look at, so I searched for the commit where conn_pool_legacy.cc was introduced but the commit message only showed `Combine H1 and H2 conn_pool implementations (#9668)`. While this gives me a bit of a trail to follow to PR and issue, it feels like that would be a good place to explain something like "the old connection pool implementations remain behind runtime flags so they can be switched to in an emergency".

Just food for thought, as a beneficiary I very much appreciate all of the work being done all the time, it just can be a bit hard to keep up with at times.

**Comment by mattklein123** [comment]
Thanks for raising this @mpuncel. I agree we can do better here in terms of making sure PR descriptions are correct and then copying the description into the final commit message before merge. I will discuss with the maintainers and do a process update PR. cc @envoyproxy/maintainers

**Comment by ggreenway** [comment]
+1. As a starting point, what if we copy whatever is in the release notes into the commit message?

**Comment by alyssawilk** [comment]
Ideally (to minimize maintainer scut work) change the template so folks creating PRs usually do that, and we can cover it when it's missed.

**Comment by ggreenway** [comment]
The default commit message on Squash is a combination of all the commits being squashed; none of the default text is taken from the PR description. But at least if the desired text is in the PR description, we can scroll up,, copy/paste it into the box, and not have to dig through the changes to get the text.

**Comment by mattklein123** [comment]
> But at least if the desired text is in the PR description, we can scroll up,, copy/paste it into the box, and not have to dig through the changes to get the text.

Yeah this is my thinking. I don't think there is any great automated way of doing this unless we build the actual merge action into RK which I suppose is possible (cc @itayd). Until then I think it can be a manual process in which the maintainer needs to 1) Make sure the PR author has a correct/description, and then 2) copy that into the final commit message before merge.

**Comment by asraa** [comment]
My descriptions can sometimes be verbose and explanatory. Can change the template to include a "Brief Description: *This would go in commit message*" as well as a "Detailed Description: *Additional details*"? 

Also, can we incorporate PR titles somewhere? Since the commit message just contains the author's commit messaged, maintainers could maybe format the commit messages as:

PR title
[newline]
Brief Description
Sign-off

**Comment by snowp** [comment]
In the past I've often copied the PR description into the final message when it made sense, though a lot of the time the PR has diverged somewhat from the original description, or the original description is appropriate for a commit message (it might be something akin to "I gave this a go, let me know what you think!"). 

I think one thing that is missing is making sure that people understand how maintainers arriving at the commit message when merging, so I think either a dedicated "commit message" section or just making it clear that the description ends up being used as the final commit message would be helpful.

**Comment by mattklein123** [comment]
> My descriptions can sometimes be verbose and explanatory. Can change the template to include a "Brief Description: This would go in commit message" as well as a "Detailed Description: Additional details"?

+1 this makes sense. If you want to update the template please go for it.

> I think one thing that is missing is making sure that people understand how maintainers arriving at the commit message when merging, so I think either a dedicated "commit message" section or just making it clear that the description ends up being used as the final commit message would be helpful.

Agreed, I think we should write this down in https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#submitting-a-pr and then the maintainers will need to make sure that the PR description, etc. is accurate before merge.

**Comment by snowp** [comment]
>My descriptions can sometimes be verbose and explanatory. Can change the template to include a "Brief Description: This would go in commit message" as well as a "Detailed Description: Additional details"?

I think it's okay to have a lot of detail included in a commit message if appropriate, but yeah if there is additional information included in the issue description that doesn't make sense in the commit message there should be an easy way to indicate that.
