### ISSUE TITLE
Question:  Permissive mode for jwt_authn http filter?

### ISSUE THREAD

**Issue by aleliaert** [envoyproxy/envoy#10907]
*Question*:
Need to add auth to a service that is widely used within organization.  Am planning on standing up Envoy as a reverse proxy with jwt_authn.  Have low confidence that jwt_authn config or client requests/JWTs will be correct at first.

As such, would like add auth in "permissive" mode where auth check is performed, but upon auth failing:
- Message written to access log about auth failure, with request header info (x_forwarded_for, user agent, request path, and ideally some safe fields from any JWT provided)
- Request allowed through

Is there a way to get this sort of behavior at present?

I do realize that there may be a way to log when requests come in without any JWT, but that doesn't help find (in a non-blocking way) any issues when there is a JWT.

Thanks!

**Comment by qiwzhang** [comment]
You can try to combine jwt_authn with rbac filters.  rbac filter allows you to specify shadow [rules](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/rbac/v3/rbac.proto#L32) which only evaluate but not enforce.

For access log info, you need to find out how to log filter metadata,  jwt layload can be written into filerMetadata [here](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L193)
