### ISSUE TITLE
Failing to hot restart envoy using hot-restarted.py

### ISSUE THREAD

**Issue by niraj2587** [envoyproxy/envoy#10902]
I am trying to setup envoy proxy for our use-case and it seems to be failing every time i try to hot restart the service.. 

I am not running multiple envoy instances.. There is only one docker container with Envoy running on it.. 

Exception 
| [2020-04-22 17:02:05.595][28][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
| unable to bind domain socket with id=0 (see --base-id option)
| starting hot-restarter with target: /etc/start_envoy.sh
| forking and execing new child process at epoch 0
| forked new child process with PID=6
| got SIGHUP
| forking and execing new child process at epoch 1
| forked new child process with PID=27
| got SIGCHLD
| PID=27 exited with code=1
| Due to abnormal exit, force killing all child processes and exiting
| force killing PID=6
| exiting due to lack of child processes
| [2020-04-22 17:02:05.600][7][warning][main] [source/server/server.cc:516] caught SIGTERM
| [2020-04-22 17:02:05.600][7][info][main] [source/server/server.cc:636] shutting down server instance
| [2020-04-22 17:02:05.600][7][info][main] [source/server/server.cc:583] main dispatch loop exited
| [2020-04-22 17:02:05.600][13][debug][main] [source/server/worker_impl.cc:120] worker exited dispatch loop
| [2020-04-22 17:02:05.600][13][debug][grpc] [source/common/grpc/google_async_client_impl.cc:35] Joining completionThread
| [2020-04-22 17:02:05.600][15][debug][grpc] [source/common/grpc/google_async_client_impl.cc:68] completionThread exiting
| [2020-04-22 17:02:05.600][13][debug][grpc] [source/common/grpc/google_async_client_impl.cc:37] Joined completionThread
| [2020-04-22 17:02:05.600][13][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:956] shutting down thread local cluster manager
| [2020-04-22 17:02:05.600][14][debug][main] [source/server/worker_impl.cc:120] worker exited dispatch loop
| [2020-04-22 17:02:05.601][14][debug][connection] [source/common/network/connection_impl.cc:109] [C12] closing data_to_write=0 type=1
| [2020-04-22 17:02:05.601][14][debug][connection] [source/common/network/connection_impl.cc:200] [C12] closing socket: 1
| [2020-04-22 17:02:05.601][14][debug][conn_handler] [source/server/connection_handler_impl.cc:122] [C12] adding to cleanup list
| [2020-04-22 17:02:05.601][14][trace][main] [source/common/event/dispatcher_impl.cc:169] item added to deferred deletion list (size=1)
| [2020-04-22 17:02:05.601][14][debug][connection] [source/common/network/connection_impl.cc:109] [C11] closing data_to_write=0 type=1
| [2020-04-22 17:02:05.601][14][debug][connection] [source/common/network/connection_impl.cc:200] [C11] closing socket: 1
| [2020-04-22 17:02:05.601][14][debug][conn_handler] [source/server/connection_handler_impl.cc:122] [C11] adding to cleanup list
| [2020-04-22 17:02:05.601][14][trace][main] [source/common/event/dispatcher_impl.cc:169] item added to deferred deletion list (size=2)
| [2020-04-22 17:02:05.601][14][trace][main] [source/common/event/dispatcher_impl.cc:169] item added to deferred deletion list (size=3)
| [2020-04-22 17:02:05.601][14][trace][main] [source/common/event/dispatcher_impl.cc:83] clearing deferred deletion list (size=3)
| [2020-04-22 17:02:05.601][14][debug][grpc] [source/common/grpc/google_async_client_impl.cc:35] Joining completionThread
| [2020-04-22 17:02:05.602][22][debug][grpc] [source/common/grpc/google_async_client_impl.cc:68] completionThread exiting
| [2020-04-22 17:02:05.602][14][debug][grpc] [source/common/grpc/google_async_client_impl.cc:37] Joined completionThread
| [2020-04-22 17:02:05.602][14][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:956] shutting down thread local cluster manager
| [2020-04-22 17:02:05.602][14][debug][connection] [source/common/network/connection_impl.cc:109] [C15] closing data_to_write=0 type=1
| [2020-04-22 17:02:05.602][14][debug][connection] [source/common/network/connection_impl.cc:200] [C15] closing socket: 1
| [2020-04-22 17:02:05.602][14][debug][client] [source/common/http/codec_client.cc:91] [C15] disconnect. resetting 0 pending requests
| [2020-04-22 17:02:05.602][14][debug][pool] [source/common/http/conn_pool_base.cc:265] [C15] client disconnected, failure reason:
| [2020-04-22 17:02:05.602][14][trace][main] [source/common/event/dispatcher_impl.cc:169] item added to deferred deletion list (size=1)
| [2020-04-22 17:02:05.602][14][debug][connection] [source/common/network/connection_impl.cc:109] [C13] closing data_to_write=0 type=1
| [2020-04-22 17:02:05.602][14][debug][connection] [source/common/network/connection_impl.cc:200] [C13] closing socket: 1
| [2020-04-22 17:02:05.602][14][debug][client] [source/common/http/codec_client.cc:91] [C13] disconnect. resetting 0 pending requests
| [2020-04-22 17:02:05.602][14][debug][pool] [source/common/http/conn_pool_base.cc:265] [C13] client disconnected, failure reason:
| [2020-04-22 17:02:05.602][14][trace][main] [source/common/event/dispatcher_impl.cc:169] item added to deferred deletion list (size=2)
| [2020-04-22 17:02:05.602][14][trace][main] [source/common/event/dispatcher_impl.cc:83] clearing deferred deletion list (size=2)

hot-restart was done via --> docker kill --signal=SIGHUP <container Id>

would appreciate if there are any pointers on what i could be doing wrong..

**Comment by niraj2587** [comment]
i have tried using the base-id option at startup as well but that doesnt seem to help.. I must be missing something trivial but not able to figure it out.

**Comment by niraj2587** [comment]
@mattklein123 would appreciate if you can have a look at this..

**Comment by mattklein123** [comment]
I would assume your container needs shared memory permissions.

**Comment by niraj2587** [comment]
@mattklein123 i have mounted the dev volume in my docker file for envoy.. is there more to it??

 volumes:
      - ./envoy/:/etc/
      - /dev:/dev

**Comment by niraj2587** [comment]
@mattklein123 would appreciate for any pointers here... I tried to mount other writtable directories on /dev/shm as well but that also didn't help...

**Comment by niraj2587** [comment]
![image](https://user-images.githubusercontent.com/4684510/80392405-f2828000-8863-11ea-8803-8985d53b1ad6.png)

**Comment by niraj2587** [comment]
turns out i was able to resolve the issue by using restart-epoch parameter in the startup script.. 

/usr/local/bin/envoy -c /etc/envoy.yaml --restart-epoch $RESTART_EPOCH
