### ISSUE TITLE
Is there a timeline for the Dynamic Forward Proxy feature to transition out of Alpha status?

### ISSUE THREAD

**Issue by chrisfw** [envoyproxy/envoy#10914]
Is there a timeline for the **Dynamic Forward Proxy** feature to transition out of Alpha status?

Description:
Use case would be for envoy to replace a current solution that requires httpd+mod_security as well as squid to provide both forward and reverse proxy functionality for http and https. 

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy
https://github.com/envoyproxy/envoy/issues/9916

**Comment by mattklein123** [comment]
In the v3 API this filter/cluster has been moved out of alpha.

**Comment by chrisfw** [comment]
That is great, thank you Matt!

**Comment by mabukhovsky** [comment]
@mattklein123 Thank you for confirmation. Does it mean it is in Beta? Or it has been tested and is suitable for production?

**Comment by ErwinGeirnaert** [comment]
Hi, I got this HTTP forward proxy working but it fails for HTTPS. There is a problem with the configuration example on https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy  where the file trusted_ca: {filename: /etc/ssl/certs/ca-certificates.crt} doesn't exist on the latest Docker repository. So HTTPS doesn't work
