### ISSUE TITLE
Envoy /stats/prometheus?filter not working with prometheus due to url percent encoding.

### ISSUE THREAD

**Issue by lxnch** [envoyproxy/envoy#10926]
When a prometheus job is configured to scrape envoy using `filter` query arg, it sends the requests with the params url percent encoded:

```
GET /stats/prometheus?filter=upstream%7Cdownstream HTTP/1.1
Host: X.Y.Z.Q:8524
User-Agent: Prometheus/2.15.2
Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
```

`upstream%7Cdownstream` doesn't get urldecoded properly and no metrics are returned.

`upstream|downstream` works fine, but prometheus can't be configured to not url percent encode the params from its scrape requests.

I'm willing to work on this if it's considered a bug and not expected behaviour. Assuming there already are some bits that do urldecoding in envoy, i think it's approachable even for someone that doesn't know c++ well (me).

Later edit:

use case: On large enough envoy deployments, we can't fit all the metrics we get from all envoys on just one prom box without eventually trashing it. So we're forced to rely on stats filtering so that each prom sees just a subset of the metrics. The lack of url decoding for `|`-based regex filters forces us to do quite a few unnecessary scrape jobs and various workarounds.

**Comment by zuercher** [comment]
I'm not sure we have URL decoding anywhere, but it's definitely not happening in the handler from prom stats.

**Comment by magederek** [comment]
This is really a problem as we use envoy as the ingress proxy in a large kubernetes cluster. Thousands of endpoints are registered to envoy so the statistics of them are so many, make it takes too much time for prometheus to pull all the metrics. We use the 'filter' parameter to filter the statistics on the envoy side so that it can lower the duration of pulling.

However, the value of request query parameters from prometheus is urlencoded, and envoy does not recognize it:

```bash
# without urlencode, got response from envoy
curl -s '127.0.0.1:10002/stats?filter=(cluster.upstream_(rq_total|rq_time_sum|rq_time_count|rq_time_bucket|rq_xx|rq_complete|rq_active|cx_active))|(server.version)'
cluster.dynamic_forward_proxy_cluster.upstream_cx_active: 0
cluster.dynamic_forward_proxy_cluster.upstream_rq_active: 0
cluster.dynamic_forward_proxy_cluster.upstream_rq_completed: 0
cluster.dynamic_forward_proxy_cluster.upstream_rq_total: 0
cluster.envolve_mate_cluster.upstream_cx_active: 0
cluster.envolve_mate_cluster.upstream_rq_active: 0
cluster.envolve_mate_cluster.upstream_rq_completed: 0
cluster.envolve_mate_cluster.upstream_rq_total: 0
cluster.envolve_xds_cluster.upstream_cx_active: 1
cluster.envolve_xds_cluster.upstream_rq_active: 1
cluster.envolve_xds_cluster.upstream_rq_completed: 2
cluster.envolve_xds_cluster.upstream_rq_total: 1
cluster.local_envoy_admin_cluster.upstream_cx_active: 10
cluster.local_envoy_admin_cluster.upstream_rq_active: 2
cluster.local_envoy_admin_cluster.upstream_rq_completed: 22
cluster.local_envoy_admin_cluster.upstream_rq_total: 24
cluster.local_envoy_http1_cluster.upstream_cx_active: 0
cluster.local_envoy_http1_cluster.upstream_rq_active: 0
cluster.local_envoy_http1_cluster.upstream_rq_completed: 0
cluster.local_envoy_http1_cluster.upstream_rq_total: 0
cluster.local_envoy_http2_cluster.upstream_cx_active: 0
cluster.local_envoy_http2_cluster.upstream_rq_active: 0
cluster.local_envoy_http2_cluster.upstream_rq_completed: 0
cluster.local_envoy_http2_cluster.upstream_rq_total: 0
server.version: 6166960

# no response with urlencode
curl '127.0.0.1:10002/stats?filter=%28cluster.upstream_%28rq_total%7Crq_time_sum%7Crq_time_count%7Crq_time_bucket%7Crq_xx%7Crq_complete%7Crq_active%7Ccx_active%29%29%7C%28server.version%29'
```

It is very helpful if someone can fix this or give some suggestion to make prometheus not to send request with urlencode.
