### ISSUE TITLE
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) X: Didn't find a registered implementation for name: 'envoy.filters.udp_listener.udp_proxy'

### ISSUE THREAD

**Issue by lolin9** [envoyproxy/envoy#10925]
Is the udp filter included and working by default in the official docker images? I tried v1.13, v1.4 and even the dev version but I still find that error in the logs while envoy trying very repetitively to get correct config
```
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) X: Didn't find a registered implementation for name: 'envoy.filters.udp_listener.udp_proxy
```
I am using the `envoyproxy/go-control-plane` to control the envoy instance but the config according to `/config_dump` is basically equal to what is in https://www.envoyproxy.io/docs/envoy/v1.13.1/configuration/listeners/udp_filters/udp_proxy except that it is of course in the dynamic resources section and the listener filter is defined as array instead o single object as in the static resource part in the cofg exampl (please have a look at https://godoc.org/github.com/envoyproxy/go-control-plane/envoy/api/v2#Listener)

**Comment by lolin9** [comment]
My bad. I forgot to set the listener's `address.socket_address.protocol` to `UDP`.

**Comment by tharun208** [comment]
@lolin9, I am getting the same issue even though I set the `address.socket_address.protocol` to `UDP`

**Comment by bruegth** [comment]
I have same issue until I noticed that it must be `listener_filters` not `filter_chains`

e.g.

    - name: listener_ntp
      reuse_port: true
      address:
        socket_address:
          protocol: UDP
          address: 0.0.0.0
          port_value: 123
      listener_filters:  ### listener_filters not filter_chains !!!
        name: envoy.filters.udp_listener.udp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
          stat_prefix: ingress_ntp
          cluster: service_timeserver
