### ISSUE TITLE
build: something wrong on azp

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#10932]
It seems that we caught the same error like this on azp.

https://dev.azure.com/cncf/envoy/_build/results?buildId=38099&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=477dbeb3-a0ba-5e4f-084c-db3104610ede&l=442

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/10938
