### ISSUE TITLE
build: upgrade base image to ubuntu 18.04

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#10944]
We have discussed this a while ago and as a part of #5325. We are 1 year from end of standard support so I think we should start upgrade.

WDYT? @envoyproxy/maintainers

**Comment by mattklein123** [comment]
+1 sgtm, especially since 20.04 just dropped.

**Comment by lolin9** [comment]
Why not to 20.04?

**Comment by lizan** [comment]
20.04 is too new, we don't have enough prebuilt tooling for them (e.g. LLVM), and it also implies the binary we put into the image can't run in an older versions.

**Comment by moderation** [comment]
Clang 10 prebuilt LLVM binaries for 18.04 are available. But no Clang 9.0.1 for either 18.04, 19.x or 20.04. https://releases.llvm.org/download.html. I asked on Twitter how these get updated but no response

**Comment by lizan** [comment]
We haven't upgraded to 9.0.1, 9.0.0 has pre-built binaries for 18.04 and 16.04. My guess is the prebuilt binaries are only released to platforms have critical bug in the previous minor version. (e.g. on arm64 clang 9.0.0 can't build Envoy).
