### ISSUE TITLE
Remove 'latest' tag from envoyproxy docker hub images

### ISSUE THREAD

**Issue by renana** [envoyproxy/envoy#10945]
Description:
Some envoyproxy images in docker hub contains the tag 'latest' which confuses users and per issue #10738 shouldn't be there.

For example, the one I was using to build our custom filter: https://hub.docker.com/r/envoyproxy/envoy-build-ubuntu/tags?page=1&name=latest

**Comment by lizan** [comment]
Yeah that makes sense. will do.

**Comment by lizan** [comment]
Done
