### ISSUE TITLE
Jinja2 version should be 2.11.1

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#10950]
It looks jinja2 version in requirements.txt  files at some places are old ( i.e. 2.10.3 ) .
Latest stable available is 2.11.1. 

Please suggest if need to change it.

**Comment by moderation** [comment]
Jinja should be 2.11.2 - https://github.com/pallets/jinja/releases/tag/2.11.2

I tried updating this in this failed PR but the Kafka extension breaks and I couldn't work it out - https://github.com/envoyproxy/envoy/pull/10594. You can see my PR for the places where the Jinja code needs to be updated. Happy for someone else to have a try

**Comment by ankatare** [comment]
@moderation yeah, 2.11.2 released couple of week back. Moreover many other s/w also need to have a look in requirements.txt.

**Comment by ankatare** [comment]
@zuercher Hi, i would like to take this.

**Comment by ankatare** [comment]
@moderation have you try with 2.11.1 version of jinja2  ? 
my suggestion is to try with 2.11.1 as 2.11.2 is just release so we can wait.

**Comment by mk46** [comment]
Hi @moderation, I have updated jinja2 to 2.11.2 and also updated dependencies gitdb to 4.0.4 and smmap to 3.0.2. 
I run `./docs/build.sh` and getting error like 

`Traceback (most recent call last):
  File "./docs/generate_extension_db.py", line 55, in <module>
    extension_db[extension] = GetExtensionMetadata(target)
  File "./docs/generate_extension_db.py", line 40, in GetExtensionMetadata
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/home/necuser/envoy/build_docs/venv/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

Could you help? Thanks in advance.
