### ISSUE TITLE
Hot restart second process block forever error.

### ISSUE THREAD

**Issue by mygityf** [envoyproxy/envoy#10953]
The second process will be block forever at recvmsg(); 
when primary process call sendmsg() failed with return code -1 in function sendHotRestartMessage() which send kStat to child process. 

Here are the block function.
std::unique_ptr<HotRestartMessage> HotRestartingChild::getParentStats() {
...
  std::unique_ptr<HotRestartMessage> wrapped_reply = receiveHotRestartMessage(Blocking::Yes);
...
}

I try to set socket send buffer size to 1024 at file envoy/source/server/hot_restarting_base.cc
int function HotRestartingBase::bindDomainSocket.

int bufSize = 1024;
setsockopt(my_domain_socket_, SOL_SOCKET, SO_SNDBUF, &bufSize, sizeof(bufSize));

when I try the hot restart feature, the second process will block at recvmsg() at file envoy/source/server/hot_restarting_base.cc
in function HotRestartingBase::receiveHotRestartMessage()

add printf log before and after sendmsg in primary process.
we will get the log like this.

sendmsg.begin total_size:2016
sendmsg.end rc:-1

Thanks.

**Comment by mattklein123** [comment]
Honestly not exactly sure what is going on here. Can you try to provide a bit more debugging detail? cc @jmarantz

**Comment by mdhume** [comment]
@mattklein123 We are seeing a similar issue. We are running with an older version of Envoy (v1.13.4) in containers through Istio.
We see that both the parent and child processes continue to run, but the admin interface (on port 15000) becomes unreachable and times out.

```istio-p+     139       1  0 Feb27 ?        00:15:50 /usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev1.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time
istio-p+     225       1  0 Feb28 ?        00:00:07 /usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev2.json --restart-epoch 2 --drain-time-s 45 --parent-shutdown-time
```

The parent process is still bound to the listening ports e.g.
```
tcp      129      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      139/envoy
```

Additionally we see these sockets for the parent and child process
```
unix  2      [ ]         DGRAM                    3267817098 139/envoy            @envoy_domain_socket_parent_1
unix  2      [ ]         DGRAM                    3425241826 225/envoy            @envoy_domain_socket_parent_2
unix  2      [ ]         DGRAM                    3425241825 225/envoy            @envoy_domain_socket_child_2
unix  2      [ ]         DGRAM                    3267817097 139/envoy            @envoy_domain_socket_child_1
```

Running an strace on the envoy pid (these are the pids on the host) shows that both parent and child processes are blocked on recvmsg
```
$ sudo strace -p 1161920
strace: Process 1161920 attached
recvmsg(6, 


sudo strace -p 1643032
strace: Process 1643032 attached
recvmsg(6,

```

Is there any additional data we can share that help with the investigation as to why this occurs?

**Comment by mattklein123** [comment]
> Is there any additional data we can share that help with the investigation as to why this occurs?

I would start by upgrading to the most recent version.
