### ISSUE TITLE
Clarifications on upstream_rq_time and downstream_rq_time

### ISSUE THREAD

**Issue by shashankram** [envoyproxy/envoy#10967]
Hi, I am trying to understand better what `upstream_rq_time` and `downstream_rq_time` exactly measure. I referred to the documentation but it wasn't clear to me. For ex. consider  `request: service A -> Envoy A -> Envoy B -> Service B; response: Service B -> Envoy B -> Envoy A -> Service A`, what do `upstream_rq_time` and `downstream_rq_time` mean here? How is the total RTT calculated?

**Comment by zuercher** [comment]
Envoy A's downstream_rq_time measures the time elapsed from when Envoy A starts handling Service A's request until the entire response has sent to Service A.

Envoy A's upstream_rq_time measures the time elapsed from the point where Service A's entire request has been received by the HTTP router filter until the entire upstream response from Envoy B has been received.

The same is true for Envoy B, except the downstream is Envoy A's request/response and the upstream is Service B.

So Envoy A's downstream_rq_time > Envoy A's upstream_rq_time > Envoy B's downtream_rq_time > Envoy B's upstream_rq_time.

Assuming there are no blocking filters in use (e.g. ext_auth) I expect the times to be reasonably close together.

**Comment by shashankram** [comment]
Thanks for clarifying!
