### ISSUE TITLE
Question: Replacement for "hosts" in V2.  

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#10973]
The  hosts field seems deprecated in V2 API. i refereed below docs
for V2:
https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/api/v2/cluster.proto#envoy-api-msg-cluster
for V3:
https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster
so in any json/yaml for V2 or in older version what would be the new replacement for hosts in V3 ? 

Is that been replaced by https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-address  ?

**Comment by zuercher** [comment]
`hosts` was deprecated in favor of `load_assignment` (https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/api/v2/cluster.proto#envoy-api-field-cluster-load-assignment).

**Comment by ankatare** [comment]
@zuercher thanks
