### ISSUE TITLE
 Question: What is static_clusters in API.

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#10980]
Hi All,

I wanted to know about static_clusters field in yaml/json fragment. i could not found any details in docs etc. 
see below code as a reference.

https://github.com/envoyproxy/envoy/blob/master/test/common/upstream/cluster_manager_impl_test.cc#L935

Thanks

**Comment by jyotima** [comment]
Here's some information about static clusters: https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v3/config_dump.proto#L191

Any clusters defined in bootstrap config is part of `static_clusters` .
Any clusters configured via control plane will be a dynamic cluster https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v3/config_dump.proto#L168

**Comment by ankatare** [comment]
@jyotima thanks . how is that different from cluster defined under bootstrap config under "static_resources" https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster

both are same ? moreover could you please help me by giving similar structure definition for static_clusters.

**Comment by ankatare** [comment]
@jyotima i got details now. 
https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/admin/v3/config_dump.proto#envoy-v3-api-msg-admin-v3-clustersconfigdump-staticcluster

Thanks for guidance.

**Comment by ankatare** [comment]
Closing it as got details
