### ISSUE TITLE
Can I run envoyproxy as transparent forward proxy?

### ISSUE THREAD

**Issue by freak82** [envoyproxy/envoy#10990]
Hi there,

We have transparent HTTP forward proxy which runs on standard Linux. However, we are trying to find more performant alternatives.

We would like to test/benchmark the envoyproxy when running as transparent forward proxy. We would like to test the simplest possible configuration to see the raw performance without any additional features turned ON.

So, here are my questions:
1. Is it possible to run envoyproxy in such mode?
2. Can you suggest the best configuration for such scenario?
3. Do you have some observations how much traffic or requests per second the envoyproxy can handle and with what configuration?

Thanks,
Pavel.

**Comment by jsalgado78** [comment]
I've very interested in envoy as a forward http proxy, like nginx proxy_pass, with set/add http headers capabilities. Is it possible ?

**Comment by moderation** [comment]
There is Dynamic Forward Proxy and SNI dynamic forward proxy capability

Dynamic forward proxy

- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto
- Helpful example based on headers - https://github.com/envoyproxy/envoy/issues/10756#issuecomment-618533459

SNI dynamic forward proxy

- https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/sni_dynamic_forward_proxy/v3alpha/sni_dynamic_forward_proxy.proto

**Comment by rvdisodia** [comment]
Hi all,
I am also looking for a similar solution.
I need to configure a transparent forward proxy, which does no operation on the coming request just route it on the basis of domain, I don't want envoy to make any changes(L3/L4 to L7) to the input request. 

With solution [#10756] we cannot specify a dns_resolver for the cluster. I have some constraints due to which cannot add the dns server in /etc/reslov.conf.
 
Is this achievable with envoy?
if yes a config sample will be a great help.

Thanks
Ravi Disodia

**Comment by shannoncarver** [comment]
> Hi all,
> I am also looking for a similar solution.
> I need to configure a transparent forward proxy, which does no operation on the coming request just route it on the basis of domain, I don't want envoy to make any changes(L3/L4 to L7) to the input request.
> 
> With solution [#10756] we cannot specify a dns_resolver for the cluster. I have some constraints due to which cannot add the dns server in /etc/reslov.conf.
> 
> Is this achievable with envoy?
> if yes a config sample will be a great help.
> 
> Thanks
> Ravi Disodia

**Comment by shannoncarver** [comment]
I'm also looking for a solution to setup a dynamic forward proxy that allows for using a specified dns_resolver.  Is this possible?

**Comment by moderation** [comment]
I've not tried this but you might be able to chain the [DNS filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/dns_filter) with the [Dynamic Forward Proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter) to achieve this.

**Comment by malza321** [comment]
Is there any way??

I just want to use like that on dynamic forward proxy.

To test, curl -x http://envoy ip:port http://target_ip:port 
I don't even need dns query.

But envoy always return "No healthy Upstream"

**Comment by malza321** [comment]
> Hi all,
> 
> I am also looking for a similar solution.
> 
> I need to configure a transparent forward proxy, which does no operation on the coming request just route it on the basis of domain, I don't want envoy to make any changes(L3/L4 to L7) to the input request. 
> 
> 
> 
> With solution [#10756] we cannot specify a dns_resolver for the cluster. I have some constraints due to which cannot add the dns server in /etc/reslov.conf.
> 
>  
> 
> Is this achievable with envoy?
> 
> if yes a config sample will be a great help.
> 
> 
> 
> Thanks
> 
> Ravi Disodia
> 
> 


Is there any way??

I just want to use like that on dynamic forward proxy.

To test, curl -x http://envoy ip:port http://target_ip:port
I don't even need dns query.

But envoy always return "No healthy Upstream"

**Comment by coder-kevin-1985** [comment]
Hi，I find the upgrade config my works, like the config demo in github：https://github.com/envoyproxy/envoy/blob/main/configs/encapsulate_in_http1_connect.yaml

the document is here：
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades

Hope to be helpful~

**Comment by wklken** [comment]
if anyone met the [Why is Envoy sending 404s to CONNECT requests? — envoy 1.34.0-dev-c0900a documentation](https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_envoy_404ing_connect_requests)

this issue solved the problem of CONNECT, proxy both http and https. https://github.com/envoyproxy/envoy/issues/11552
