### ISSUE TITLE
Reflect DiscoveryResponse.control_plane as a TextReadout stats

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#11000]
Similarly to #10736 we should add a TextReadout stat that will reflect "The control plane instance that sent the response".

**Comment by tharun208** [comment]
I like to work on this

**Comment by Vineet-Sharma29** [comment]
@tharun208 are still working on it? If not, I would like to work on it.

**Comment by tharun208** [comment]
@Vineet-Sharma29, feel free to revive it

**Comment by dr0pdb** [comment]
@efimki Hi, I am a student trying to work on this.

Where should this stat go?
 https://github.com/envoyproxy/envoy/blob/master/include/envoy/config/grpc_mux.h#L16

or 

https://github.com/envoyproxy/envoy/blob/master/include/envoy/config/subscription.h#L100

or somewhere else?

**Comment by efimki** [comment]
I was thinking that it should go to ALL_SUBSCRIPTION_STATS, next to `version_text`.

**Comment by efimki** [comment]
@dr0pdb are you planning to finish #11204 ?

**Comment by dr0pdb** [comment]
@efimki 
I would like to finish it but I will be busy with my university exams till mid-June. 

I closed it so that anyone else can work on it in the meantime if they want. Otherwise, I'll resume work once I am free again.

**Comment by efimki** [comment]
Sounds good, thanks! I may pick it up before then.

**Comment by efimki** [comment]
Quick update: it was decided to go with `ControlPanelStats` instead in #11390.
