### ISSUE TITLE
Least requests LB is not fair at edge cases

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#11004]
Least requests LB does independent random pick at every iteration without preserving any knowledge about previous attempts. This leads to unexpected behavior in a few edge cases.

1. In case of low number of backends envoy has increasingly higher chance of picking the same host twice instead of two different ones, which leads to higher chance (as high as 50% in case of 2 backends) to send next request to an instance with more active requests.
2. In some cases full scan is desired (e.g. relatively small amount of backends with strong requirements for utilization), but setting high choice count only wastes cpu without providing any guarantees.

Potential options:
1. For both (1) and (2), alter `LeastRequestLoadBalancer::unweightedHostPick` to preserve knowledge across iterations. It may add more memory usage (`hosts.size() * 8 bytes`) per load balancer instance) but should keep performance otherwise intact.
2. For (2), add new full-scan least requests load balancer.

Relevant Links:
https://github.com/envoyproxy/envoy/blob/0d9f2d59f9cac9dc742e8bcd4588e71e9331f4ac/source/common/upstream/load_balancer_impl.cc#L807-L828

**Comment by mattklein123** [comment]
cc @tonya11en @gkleiman who have been looking at related things.

**Comment by euroelessar** [comment]
One of the approaches I have in mind right now is something like this:
1. Maintain list of all hosts per source
2. At each `unweightedHostPick` call:
2.1. Let `size` be number of hosts.
2.2. Per each iteration:
2.2.1. Pick random host in `[0, size)` interval
2.2.2. Swap picked host with one at `size-1`
2.2.3. Decrement size by 1

This _should_ give us new host at each iteration while maintaining otherwise random picks.

**Comment by snowp** [comment]
cc @jmarantz as well who was looking into the LR load balancer recently

**Comment by jmarantz** [comment]
I noticed the same thing when looking at the implementation. I like your approach; I think that'd help a lot.

**Comment by barroca** [comment]
Can I have this assigned to me please?
