### ISSUE TITLE
Redis through Envoy giving latency

### ISSUE THREAD

**Issue by saagar241290** [envoyproxy/envoy#11011]
We are moving from single redis to cluster redis. For data migration, we are trying to introduce Envoy so that application connects to Envoy, which will replicate the data across single and cluster nodes.

While testing it, latency is observed while passing traffic through envoy. But when passed it to direct single redis, no latency found.

Config : 
```enable_dispatcher_stats: "true"
admin:
  access_log_path: "/tmp/envoy.log" # In production, change this to a real log file.
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0 # For smarter management, you might want this to listen on 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          downstream_auth_password:
            inline_string: passwd # In production, you need to change this to something better.
          settings:
            op_timeout: 5s
          prefix_routes:
            routes:
              - prefix: "" # Route based on prefix, keys starting with prefix_ will be written to both standard and new
                cluster: "standard"
                request_mirror_policy: [{cluster: "new", exclude_read_commands: True}]
            catch_all_route: # All other redis operations, execute on standard.
              cluster: "standard"
  clusters:
  - name: new
    connect_timeout: 1s
    type: static # Check https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster.proto#envoy-api-enum-cluster-discoverytype
    load_assignment:
      cluster_name: redis-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: cluster-redis-master
                port_value: 6379
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "passwd"}
  - name: standard
    connect_timeout: 1s
    type: static
    load_assignment:
      cluster_name: redis_standard
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: single-redis
                port_value: 11111
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "passwd"}
```
### Benchmarking result : 

**redis-benchmark -n 100000 -a passwd -t set,get -d 100 -c 5 -p 1999 -h envoy-host**
```
====== SET ======
  100000 requests completed in 7.12 seconds
  5 parallel clients
  100 bytes payload
  keep alive: 1

100.00% <= 1 milliseconds
100.00% <= 1 milliseconds
14042.97 requests per second

====== GET ======
  100000 requests completed in 7.82 seconds
  5 parallel clients
  100 bytes payload
  keep alive: 1

99.98% <= 1 milliseconds
100.00% <= 2 milliseconds
100.00% <= 2 milliseconds
12794.27 requests per second


```

**redis-benchmark -n 100000 -a passwd -t set,get -d 100 -c 5 -p 11111 -h single-redis**

```
====== SET ======
  100000 requests completed in 4.41 seconds
  5 parallel clients
  100 bytes payload
  keep alive: 1

100.00% <= 1 milliseconds
100.00% <= 1 milliseconds
22680.88 requests per second

====== GET ======
  100000 requests completed in 3.90 seconds
  5 parallel clients
  100 bytes payload
  keep alive: 1

100.00% <= 0 milliseconds
25614.75 requests per second

```

Please suggest.

**Comment by mpuncel** [comment]
I noticed something similar as we rolled out an application using Envoy for redis sharding (but first we tried with just a single redis node).

Looking at a `perf` flamegraph, I don't see anything completely egregious, but one thing that jumps out at me is creating stats in `Envoy::Extensions::NetworkFilters::Common::Redis::RedisCommandStats::createAggregateTimer` which is about 17% of CPU time under `Envoy::Extensions::NetworkFilters::RedisProxy::ProxyFilter::onData`. It looks like it's building a stat name every time to look up the stat, that could probably be cached?

**Comment by mattklein123** [comment]
cc @jmarantz ^

**Comment by jmarantz** [comment]
@mpuncel can you attach your flame-graph? I'd love to take a quick look.

We can easily cache the StatName for createAggregateTimer, as the two names being joined are known at construction time. The commandTimer not so much.

I'll write a small PR for createAggregateTImer.

**Comment by jmarantz** [comment]
We can actually build up StatNames for a few of these joins, as there are a finite number of commands. But the assumption always has been that joining stat-names (which is basically like appending bytes) and then doing the lookup in thread_local_store, is fast enough to do lots of times in the course of a request, as long as it's not taking any locks in the hot path, which it shouldn't be.

**Comment by mpuncel** [comment]
Here's the flamegraph. Github made me put it in a zip

[envoy-flamegraph.svg.zip](https://github.com/envoyproxy/envoy/files/4602449/envoy-flamegraph.svg.zip)

**Comment by jmarantz** [comment]
Thanks for the flame-graph; I was having a hard time understanding the overall impact of the stat creation. It's hard to even find it on the flame-graph.

Is there another perf view that made this jump out at you? Maybe a flat profile or top-down profile? I just want to make sure we are optimizing the right thing.

**Comment by mpuncel** [comment]
I don't read flame graphs very often so I could totally be zeroing in on the wrong thing. I clicked into the `Envoy::Extensions::NetworkFilters::Common::Redis::DecoderImpl::decode` span and was just noticed that RedisCommandStats::histogram() seemed non-neglible. It's probably a very small win, so not worth investing a lot of effort.

**Comment by mpuncel** [comment]
![Screen Shot 2020-05-11 at 12 53 46 PM](https://user-images.githubusercontent.com/1444855/81588482-943abe80-9386-11ea-927f-0f24045c717f.png)

**Comment by jmarantz** [comment]
I think the svg you sent is not the same as the one above; is that possible? In any case, if you hover over the call to `RedisCommandStats::histogram()` in your SVG, it should tell you the overall percentage of the run, which will help give more perspective of the potential upside. Thank you!

**Comment by mpuncel** [comment]
I double checked that it's the same .svg, that image is just drilled in on what I understand to be the request handling part of the filter.

Hovering over `RedisCommandStats::histogram()` shows .59%, the entire of `Envoy::Extensions::NetworkFilters::Common::Redis::DecoderImpl::decode` is 3.63%. This Envoy instance is also handling other non-redis traffic which is why I was analyzing the stats time as a percentage of redis time.

The part of the flame graph pertaining to the upstream redis response does not seem to spend as much time in stats

**Comment by jmarantz** [comment]
OK I found now the region of the svg you pasted from. Thanks! I had to learn how to navigate my way around an svg a little better in Chrome.

So there are some things to tweak here but will be pretty incremental, and the maximum overall throughput improvement will be pretty small overall I think, right?

Anyway I can cache a couple of things which may help a bit, but I don't think it's going to meaningfully impact the throughput numbers.

**Comment by mpuncel** [comment]
Yeah totally understood this stuff is all incremental, I just figured I'd share the flamegraph since I had it. This is also not a high priority on my end, the latency is still plenty good enough for us and the automatic sharding is awesome
