### ISSUE TITLE
Support Redis 5 stream commands

### ISSUE THREAD

**Issue by billyzs** [envoyproxy/envoy#11025]
Redis 5 added a new stream data type[1] and commands[2] to operate on one or multiple of them. Currently they are missing from envoy. I'm wondering if it's possible to support at least
1.  [xrange](https://redis.io/commands/xrange)
2. [xrevrange](https://redis.io/commands/xrevrange)
3. [xlen](https://redis.io/commands/xlen)

and maybe [xread](https://redis.io/commands/xread). xread is slightly difference since it could take multiple keys that exist on different cluster. Do you think xread with keys being on different clusters could be handled?
I saw  #6563 that added support for additional commands. For 1-3 is it just a matter of adding to the set of supported commands?
First time contributing, guidance appreciated :) Thanks!

[1] https://redis.io/topics/streams-intro
[2] https://redis.io/commands#stream

**Comment by mattklein123** [comment]
cc @envoyproxy/redis-dev

**Comment by mukundv18** [comment]
Does Envoy proxy support Redis Streams?
