### ISSUE TITLE
Documentation Improvement. ( clarity, typos and redirections glitch )

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#11027]
Hi,

I refereed below link for v2 and compared the same with V3 and found there is a change in name of field  "drain_connections_on_host_removal" to "ignore_health_on_host_removal"
api/v2:
https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/api/v2/cluster.proto#drain_connection_onhost_removal
api/v3/
https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster#ignore_health_on_host_removal

It would be good and will provide clarity in terms of code walk through etc if we can add **Note:** in doc for v3 along with new variable referring to old field and put statement like deprecated etc.

**Comment by phylake** [comment]
Is this actually a rename? It doesn't mention or imply connection draining

**Comment by phylake** [comment]
Looks like it #8056

**Comment by ankatare** [comment]
@phylake yeah, seems it is mention in #8056 but still there is a need to improve documentation.

**Comment by ankatare** [comment]
changing heading of this issue as found more docs related glitch.

**Comment by ankatare** [comment]
closing this issue now as it is long open for docs improvement.
