### ISSUE TITLE
Support preserving the `date` header in HTTP responses

### ISSUE THREAD

**Issue by chradcliffe** [envoyproxy/envoy#11030]
Envoy unconditionally sets the Date header in an HTTP response regardless of whether the upstream host included a Date header in its response. The [relevant RFC](https://tools.ietf.org/html/rfc2616#section-14.18) recommends that:

> The HTTP-date sent in a Date header SHOULD NOT represent a date and time subsequent to the generation of the message. It SHOULD represent the best available approximation of the date and time of message generation

The current behaviour seems perfectly compliant to me, but for one of my use cases I'd like to be able to preserve the upstream response date header. I was thinking this could be a flag in the HTTP Connection Manager configuration.

I can do the work and submit a PR if there is agreement that this is a sensible proposal.

**Comment by mattklein123** [comment]
Yes this seems fine to have be configurable. cc @alyssawilk
