### ISSUE TITLE
Teach transcoding filter to be aware of per vhost / per route settings 

### ISSUE THREAD

**Issue by gagata** [envoyproxy/envoy#11038]
Currently `envoy.filters.http.grpc_json_transcoder` is only applied on the 'global' level, meaning that it's not possible / easy to setup envoy's  configuration for the following scenarios:
- having two routes for two different domains configured with the same path value (assuming they use transcoding), example: say you have domain1.com/foo and domain2.com/foo and want requests to each of them be transcoded and then be forwarded to different upstreams
- using RDS with transcoded paths
- gracefully migrating from a setting that does not use transcoding to a setting that does (or the other way round), example: having a path that accepts some json in request and currently upstream is responsible for deserialization and being in the process to migrate over to a proto-based solution and leveraging transcoding plugin, for the time of the migration part of the traffic would go directly to the upstream, while the other part would be transcoded and sent to a newly implemented upstream

Potential solution:
Add similar logic to the transcoding filter as it is, for example, in `Buffer`

**Comment by gagata** [comment]
we need it at work, so I'm happy to send a patch for it - feel free to assign to me if there's no other concerns

**Comment by mattklein123** [comment]
@gagata go for it!

**Comment by gagata** [comment]
Hey @mattklein123 
Can you please advise what's the best way to approach the filter configuration where the filter is only specified on the virtual host level?

We've been testing the implementation from the linked diff for a while now, and the use case I'm stuck on is as follows:
- the general filter is basically empty (disabled)
- the filter is set on per-virtual host basis only (not for routes)
When trying to access the filter configuration, `decoder_callbacks_->route()` will return `nullptr` for a route `/something/that/will/soon/be/transcoded` (the route in the route configuration is the grpc one, after transcoding). 

The issue was kinda shadowed and hard to figure before, since in our config we used `/` to fallback to the old system (so the path was matched to something, and filter could've been applied). 

Questions:
- is it considered a valid use case?
- what would you suggest doing to solve the problem (some way of figuring out the per-virtual host config that's not realying on `route()` entry?)
- should I create a new issue to track this separately?
