### ISSUE TITLE
MySQL proxy

### ISSUE THREAD

**Issue by GTB3NW** [envoyproxy/envoy#1104]
It would be great to get a MySQL proxy support so that slaves can be taken out of load when they meet a threshold criteria for behind master for example.

**Comment by dveeden** [comment]
This might be interesting for a few use cases. This might make SSL/TLS for non-persistent connections more efficient for example. It might also save a roundtrip for SSL/TLS connections.

**Comment by dasch** [comment]
:+1: to this – being able to e.g. present a pool of sharded databases as a single instance (based on e.g. a column value) would be a killer feature.

**Comment by derekperkins** [comment]
> present a pool of sharded databases as a single instance (based on e.g. a column value) would be a killer feature.

@dasch If you're interested in that, you should check out Vitess, another CNCF project https://vitess.io/

**Comment by rshriram** [comment]
Please see #4975 
This is a strawman mysql wire protocol decoder. Will add sql parsing capabilities, and other things mentioned here over time..

**Comment by GTB3NW** [comment]
Great work @rshriram Looking forward to see what more you come up with!

**Comment by mattklein123** [comment]
Calling this complete. We can track new filter feature requests in new issues.
