### ISSUE TITLE
proposal: securing admin endpoint

### ISSUE THREAD

**Issue by cstrahan** [envoyproxy/envoy#11082]
# A proposal to secure the admin endpoint

I was chatting with @mattklein123 a couple weeks ago about securing the admin endpoint, under the assumption that we'd want some way to allow users to specify arbitrary filters (e.g. RBAC).

I would like to propose that we allow specifying a `Listener` config in the `Admin` message, and deprecate the `Admin` fields that can be taken directly from the `Listener` (e.g. address details).

The `AdminFilter` would be made a first class filter (registered with just like the other http filters), but we would validate that the `AdminFilter` is only used within the `Admin` config, and that the filter is specified last in the filter chain.

I would appreciate feedback from both Envoy users and developers; would this approach work for you?

**Comment by htuch** [comment]
This dupes https://github.com/envoyproxy/envoy/issues/2763, can you continue the discussion there? Suggest copy+paste ^^. Thanks.
