### ISSUE TITLE
Heathcheck and Outlier detection Behavior During Upstream Cluster Rolling Update in Kubernetes/ZDM for upstream cluster Rolling Update

### ISSUE THREAD

**Issue by rohitagg2020** [envoyproxy/envoy#11080]
**SetUp:**
I have a k8s cluster in which I am using envoyproxy as ingress. I have two running instances of the upstream cluster. 
I have configured both health check and outlier detection as part of the cluster configuration.
This the cluster configuration:
{
   "name":"cluster1",
   "type":"STRICT_DNS",
   "connect_timeout":"5s",
   "health_checks":[
      {
         "timeout":"1s",
         "interval":"1s",
         "unhealthy_threshold":2,
         "healthy_threshold":2,
         "tcp_health_check":{},
         "no_traffic_interval":"1s"
      }
   ],
   "circuit_breakers":{
      "thresholds":[
         {
            "max_connections":8000
         },
         {
            "priority":"HIGH",
            "max_connections":10000
         }
      ]
   },
   "outlier_detection":{
      "consecutive_5xx":3,
      "consecutive_gateway_failure":3
   }
}
**Action/Operation:**
I am trying to do the rolling update of my upstream cluster while making the calls continuously in parallel. I make 100 calls/sec and each call take 5 sec to respond. Hence I might have max 500 connections opened per upstream node at ingress.

I ensure that one instance of upstream cluster is always running when other one is being upgraded to the newer version.
When my upstream instance goes down, it doesn't accept any new request but it will serve all the ongoing request successfully and hence terminate gracefully.
**Expected Behavior**
I expect that max 6 calls(3 calls per cluster) should have failed. But I see that I get > 1300 call failures with 503 status code.
**Obesrvation:**
It might be that during the time outlier detection was taking place, I might have some connections to which the request would have already assigned. and hence I get the call failure.

I looked into the logs and I saw this error. But I am not sure what it means:

[debug][connection] [source/common/network/connection_impl.cc:711] [C4398] connecting to 100.96.1.42:443
[debug][connection] [source/common/network/connection_impl.cc:720] [C4398] connection in progress
[debug][pool] [source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
**[debug][connection] [source/common/network/connection_impl.cc:568] [C4398] delayed connection error: 111**
[debug][connection] [source/common/network/connection_impl.cc:193] [C4398] closing socket: 0
[debug][client] [source/common/http/codec_client.cc:88] [C4398] disconnect. resetting 0 pending requests
**[debug][pool] [source/common/http/http1/conn_pool.cc:136] [C4398] client disconnected, failure reason: 
[debug][pool] [source/common/http/http1/conn_pool.cc:167] [C4398] purge pending, failure reason: 
[debug][router] [source/common/router/router.cc:911] [C3654][S17475984688729051914] upstream reset: reset reason connection failure
[debug][http] [source/common/http/conn_manager_impl.cc:1354] [C3654][S17475984688729051914] Sending local reply with details upstream_reset_before_response_started{connection failure}**
[debug][http] [source/common/http/conn_manager_impl.cc:1552] [C3654][S17475984688729051914] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '91'
'content-type', 'text/plain'
'date', 'Tue, 05 May 2020 10:23:34 GMT'
'server', 'envoy'

**My question is how can I avoid this behavior and get near to zero call failures during the rolling update. What is it that I have to set to ensure that I get minimum no. of call failures. I am trying to achieve the ZDM behavior. If there is any other way to achieve that, I will gladly try it :)**

@mattklein123 Any pointer will be helpful.

**Comment by abhiroop93** [comment]
Hi @ruoshan ,
Did you find a way around this?
