### ISSUE TITLE
Identifying stable release for a minor version

### ISSUE THREAD

**Issue by aminjam** [envoyproxy/envoy#11091]
### Summary

As downstream consumers of envoy binary, we would like to find a process to discover and bump the envoy binary when a new version of a given minor has been released. 

### Facts

I see that in #10800 the community has stopped publishing `latest` tag for envoy docker image and I found the following [Stable release of Envoy doc](https://docs.google.com/document/d/1dFYR1b_n6Qz0caZmMqm008CKG7Q5eM5pXWPu0pAtGmw/edit#heading=h.xw1gqgyqs5b) that describes the release schedule for a given minor version.

### Problem

While it's technically possible to consume/watch the latest github release for enovy, extract the version info, and `docker pull` the given tag, there are a few downsides to this approach:
1. There is no guarantee that the docker image has been pushed to dockerhub when the release is made
1. All downstream consumers have to re-invent the same process in order to get the latest patched version of an envoy binary

### Questions

1. Would it be possible to have the downstream users consume a `1.minor.x` (e.g. 1.14.x) docker image tag in order to get the latest patched envoy binary for a given minor?
1. Is there a better workflow for consuming the latest patched envoy binary other than the docker image? We currently use the following docker image: `envoyproxy/envoy`

**Comment by mattklein123** [comment]
Yes this occurred to me also to have a per-stable-version "latest" tag that users can track if they wish. Marking help wanted for someone to look into script updates. cc @lizan

**Comment by aminjam** [comment]
@mattklein123 @lizan Is there any updates on this issue or thoughts about the path forward? I'd be happy to close this issue for now if there is no workaround or plan in the foreseeable future.

**Comment by sunjayBhatia** [comment]
I can work up a PR for this, feel free to assign it to me

**Comment by lizan** [comment]
@aminjam per-stable-version "latest" tag sounds good to me.

**Comment by mattklein123** [comment]
Please don't close this. We should definitely do this but we need someone to work on it. @sunjayBhatia that would be awesome!
