### ISSUE TITLE
high CPU usage in version 1.12 and above

### ISSUE THREAD

**Issue by gongcon** [envoyproxy/envoy#11093]
We have a service using envoy as side car. It's currently on 1.11.0 and CPU is below 1% without requests other than health checks. Once we upgrade it to 1.12 or even the latest 1.14, the CPU immediately goes up to 20% without requests.

Is there any known issue about this? Don't see any special thing in debug level logs. How can we troubleshoot it? By the way, healthchecks are HTTP/1.0 requests.

**Comment by mattklein123** [comment]
> How can we troubleshoot it?

Please provide some perf flame graphs, optimally from both the old and new version and we can take a look. Thank you!

**Comment by gongcon** [comment]
Thanks @mattklein123 for the response. Before getting into flame graphs, can you explain these in log? It takes exactly 1 second for a HTTP/1.0 request to finish. HTTP/1.1 and HTTP/2 are good. 

```
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][client] [source/common/http/codec_client.cc:104] [C6] response complete
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][connection] [source/common/network/connection_impl.cc:109] [C2967] closing data_to_write=194 type=2
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][connection] [source/common/network/connection_impl_base.cc:30] [C2967] setting delayed close timer with timeout 1000 ms
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][pool] [source/common/http/http1/conn_pool.cc:48] [C6] response complete
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][pool] [source/common/http/conn_pool_base.cc:93] [C6] destroying stream: 0 remaining
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][connection] [source/common/network/connection_impl.cc:622] [C2967] write flush complete
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][connection] [source/common/network/connection_impl.cc:514] [C2967] remote early close
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.225][25][debug][connection] [source/common/network/connection_impl.cc:200] [C2967] closing socket: 0
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.226][25][debug][conn_handler] [source/server/connection_handler_impl.cc:86] [C2967] adding to cleanup list
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.384][26][debug][connection] [source/common/network/connection_impl_base.cc:44] [C2960] triggered delayed close
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.384][26][debug][connection] [source/common/network/connection_impl.cc:200] [C2960] closing socket: 1
May 6, 2020 @ 16:57:57.000	 - 	[2020-05-06 23:57:57.384][26][debug][conn_handler] [source/server/connection_handler_impl.cc:86] [C2960] adding to cleanup list
```

**Comment by gongcon** [comment]
Captured 3-minute flame graph for the new envoy. Doesn't look like it gives any valuable info.

![envoy-fg](https://user-images.githubusercontent.com/7774447/81328320-8d900c80-9051-11ea-9277-7629c962c1d8.jpg)

**Comment by mattklein123** [comment]
You need debug symbols for the flame graph to be useful.

**Comment by gongcon** [comment]
I did. Here's my command `sudo perf record -F 99 -p 6361 -g -- sleep 180`

**Comment by gongcon** [comment]
Finally got the flame graphs. See longer epoll_wait in the new version.
[envoy_flame_grpah.zip](https://github.com/envoyproxy/envoy/files/4596234/envoy_flame_grpah.zip)

**Comment by gongcon** [comment]
Confirmed that it's caused by HTTP/1.0 heath check requests. Can it be fixed?

**Comment by mattklein123** [comment]
@gongcon there isn't enough info to fix the bug. Can you investigate more and/or please provide a flame graph that shows Envoy symbols? You need to use a binary with symbols.

cc @alyssawilk

**Comment by alyssawilk** [comment]
Also curious, can you try running from HEAD and seeing it reproduces?  We just fixed a bug with HTTP/1.0 with regards to connection: close - I could imagine if one side was not closing a non-keep-alive HTTP/1.0 connection correctly that the delay-close time could result in that 1s delay you describe.

**Comment by alyssawilk** [comment]
(Would still love to see the flame graphs either way though - the high CPU implies something is spinning while in that state which is surprising and likely buggy)

**Comment by gongcon** [comment]
Doesn't the one I posted earlier not including good flame graphs? What/Where is the binary with symbols?

I saw an HTTP/1.0 bug fix in 1.14.0 release note. That's why I tried it on. Isn't it the one you mentioned?
```
http: fixing a bug in HTTP/1.0 responses where Connection: keep-alive was not appended for connections which were kept alive.```

**Comment by alyssawilk** [comment]
Unfortunately the fix I'm talking about is in 1.15-dev (head) though if it
helps your case I'll tag it for backporting

* http: fixed several bugs with applying correct connection close behavior
across the http connection manager, health checker, and connecti
on pool. This behavior may be temporarily reverted by setting runtime
feature `envoy.reloadable_features.fix_connection_close` to false.

**Comment by gongcon** [comment]
How to set the switch of `envoy.reloadable_features.fix_connection_close`? I would like to try it out in dev and let you know.

**Comment by alyssawilk** [comment]
For the flame graphs, becuse it's a static image and most of the function names are truncared we can't really tell what's going in.

Building from head, Envoy should have the fixed behavior by default.
If you want to verify that was the fix you can set that boolean false using regular runtime mechanisms (bootstrap config, RTDS etc.) to restore prior behavior.

**Comment by gongcon** [comment]
Not the jpg image, it's the [zip file](https://github.com/envoyproxy/envoy/files/4596234/envoy_flame_grpah.zip) -- github doesn't allow uploading svg files.

**Comment by alyssawilk** [comment]
Ah sorry, the svg file is still  just telling me [envoy][envoy][envoy] for
non-kernel calls.
