### ISSUE TITLE
fixed_duration_ms is not working in Fault Injection.

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#11095]
I follow https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/fault_injection
and run ` bash enable_delay_fault_injection.sh` 
Observing response from backend service but not getting any delay.

**Comment by mk46** [comment]
Hi @alyssawilk, Can we reopen this issue. I try with v1.9.0- v.1.10.0 but facing the same problem?

**Comment by moderation** [comment]
@mk46 1.9.0 and 1.10.0 are very old by Envoy standards. You should test with 1.14.2 - https://www.envoyproxy.io/docs/envoy/v1.14.2/intro/version_history

**Comment by mk46** [comment]
@moderation I have done this for 1.14.2, facing the same issue. Not sure but the delay of 3s  https://github.com/envoyproxy/envoy/blob/7f251daa2e488587bc7335f91faceed420f162c4/examples/fault-injection/enable_delay_fault_injection.sh#L6
doesn't affect response time.

**Comment by alyssawilk** [comment]
Looking at the docs, it looks like you should only see a delay on half the requests.  Are you not seeing it on any? It'd help if you could attach some logs of what you're seeing.  Thanks!

**Comment by mk46** [comment]
@alyssawilk I have not seen any delay except delay of 1s between two requests https://github.com/envoyproxy/envoy/blob/3efafaa0d2a1625e74bf40976d6e9cfef9064f4b/examples/fault-injection/send_request.sh#L6 and attached the log below.

- https://raw.githubusercontent.com/mk46/test/master/response.log

**Comment by alyssawilk** [comment]
I meant the Envoy logs, sorry for not being clear.
Anyway, played around with it myself and it does look like something isn't up to date.  I'll go ahead and reopen

**Comment by cpakulski** [comment]
I am looking at this issue.

**Comment by mk46** [comment]
I have attached the [envoy log](https://raw.githubusercontent.com/mk46/test/master/envoy.log). Response getting after applying delay is from
 https://github.com/mk46/test/blob/b0e918666a6961ae01d73b2e48be4cff7c2be811/envoy.log#L122

**Comment by alyssawilk** [comment]
Awesome, thanks @cpakulski

**Comment by cpakulski** [comment]
@mk46 Please check changes in PR #11715. If you do not want to wait until it is merged into master update your local envoy.yaml file, rebuild images and it should be fine now.

**Comment by mk46** [comment]
@cpakulski It's working now. Thanks!
