### ISSUE TITLE
test: refactoring opportunities for FakeUpstream and health_checker_impl_test.cc

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#11109]
In the process of https://github.com/envoyproxy/envoy/pull/11098 I found there were large amounts of repeated code constructing FakeUpstream and in the health-checker test code.

IMO this boilerplate should be factored out into helper methods, greatly reducing code duplication and making future refactors much easier. For example, in test/common/upstream/health_checker_impl_test.cc there are tons of blocks exactly like

```
    health_checker_ = std::make_shared<TestHttpHealthCheckerImpl>(
        *cluster_, parseHealthCheckFromV2Yaml(yaml), dispatcher_, runtime_, random_,
        HealthCheckEventLoggerPtr(event_logger_), http_context_);
```

that could be factored into a single line, reducing code bloat, increasing (IMO) reliability, and certainly making future refactors easier. E.g. see the repetitive changes in https://github.com/envoyproxy/envoy/pull/11098/files#diff-441f309ff25aa293fedfc913fbd86fda

Similarly, there a lot of places across the codebase where a FakeUpstream is instantiated, and most (though not all) of the calls are quite similar, using already-set member variables for most of the arguments. There would be some parameterization needed. I count 33 instances to `new FakeUpstream(` which could also be factored.

A third case is test/extensions/filters/network/http_connection_manager/config_test.cc with 
```
HttpConnectionManagerConfig(parseHttpConnectionManagerFromV2Yaml(yaml_string), context_,
                                  date_provider_, route_config_provider_manager_,	                                  date_provider_, route_config_provider_manager_,
                                  scoped_routes_config_provider_manager_, http_tracer_manager_),	                                  scoped_routes_config_provider_manager_, http_tracer_manager_,
                                  http_context_)
```

This might be a good intern starter project.

**Comment by mk46** [comment]
Hi @jmarantz, I would like to take up this issue.

**Comment by jmarantz** [comment]
Great! I'd suggest you tackle those 3 subtasks in 3 different PRs. The two single-file ones will be easier, then you could tackle the createFakeUpstream() helper and changing all the uses as a third one.

Thank you!

**Comment by jmarantz** [comment]
@alyssawilk FYI

**Comment by mk46** [comment]
@jmarantz  Can we close this? Thanks!.

**Comment by jmarantz** [comment]
Yes thanks for all your effort, Manish!
