### ISSUE TITLE
Envoy filter logging

### ISSUE THREAD

**Issue by gituserjava** [envoyproxy/envoy#11129]
We successfully configured envoy.ext_authz, however we are unable to see logs of incoming and outgoing requests through this filter. How do I log incoming requests (entry and exit) of a particular filter with envoy? We have a traceId which will be coming from request header and we would like to see that in Envoy logs. Do we need to write a custom logic to acheive this? If there is any example, please let us know.

**Comment by ramaraochavali** [comment]
There is no generic mechanism, but have added logging ext authz request/responses in trace mode recently https://github.com/envoyproxy/envoy/pull/11041 - does it help?

**Comment by gituserjava** [comment]
@ramaraochavali , does it log request headers also? which version of envoy do we have it?

**Comment by dio** [comment]
@gituserjava could you share relevant part of your config? Are you using HTTP or gRPC?

**Comment by gituserjava** [comment]
@dio , I am using gRPC. My configuration is basic as shown below. I also configured config.yaml with `decision_logs` for `console `set to `true`. I am looking for logging not just for `ext_authz` but all filters in general that are used in envoy so that i can trace the request with the incoming traceId in request.

```
http_filters:
  - name: envoy.filters.http.ext_authz
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      grpc_service:
        envoy_grpc:
		  target_uri: 127.0.0.2:9191`

**Comment by gituserjava** [comment]
@dio
