### ISSUE TITLE
glibc issue with latest envoy image

### ISSUE THREAD

**Issue by laltralt** [envoyproxy/envoy#11165]
envoy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by traffic-director/envoy)"

**Comment by laltralt** [comment]
@lizan

**Comment by lizan** [comment]
@laltralt Which image are you running? This is expected behavior and documented in latest [version history](https://www.envoyproxy.io/docs/envoy/latest/version_history/current):

> build: official released binary is now built on Ubuntu 18.04, requires glibc >= 2.27.

**Comment by laltralt** [comment]
> @laltralt Which image are you running? This is expected behavior and documented in latest [version history](https://www.envoyproxy.io/docs/envoy/latest/version_history/current):
> 
> > build: official released binary is now built on Ubuntu 18.04, requires glibc >= 2.27.

I am using envoyproxy/envoy-dev:latest, so looks this is a hard requirement to have glibc >= 2.27 moving forward?

**Comment by lizan** [comment]
Are you running the image directly or copying the binary out of the image? The image itself runs fine with `docker run`.

**Comment by lizan** [comment]
```
$ docker pull envoyproxy/envoy-dev:latest && docker run --rm -it envoyproxy/envoy-dev:latest --version
latest: Pulling from envoyproxy/envoy-dev
Digest: sha256:c3b20d8afa4bd535a26a072a8e7e2bd513d27501d491da279bfbdf6b175dc190
Status: Image is up to date for envoyproxy/envoy-dev:latest
docker.io/envoyproxy/envoy-dev:latest

envoy  version: 593d32bf56ccdb0017cbf4d8c024e7fb3f7ed4e1/1.15.0-dev/Clean/RELEASE/BoringSSL
```

**Comment by laltralt** [comment]
> Are you running the image directly or copying the binary out of the image? The image itself runs fine with `docker run`. As long as you're using ubuntu 18.04 based image it should work (ubuntu 18.04 comes with glibc 2.27.

I am extract envoh binary from docker image and run it. I can close the issue if it is hard required to have ubuntu 18.04 comes with glibc 2.27.

**Comment by lizan** [comment]
@laltralt yeah the binary in official image is supposed to run under its image environment (i.e. requires glibc 2.27), if you want to run on older platforms you can build yourself: see https://www.envoyproxy.io/docs/envoy/latest/install/building#requirements or use pre-built binaries provided in [getenvoy.io](https://getenvoy.io).

**Comment by laltralt** [comment]
> @laltralt yeah the binary in official image is supposed to run under its image environment (i.e. requires glibc 2.27), if you want to run on older platforms you can build yourself: see https://www.envoyproxy.io/docs/envoy/latest/install/building#requirements or use pre-built binaries provided in [getenvoy.io](https://getenvoy.io).

@lizan, thanks for the information. Much appreciated! Will close this issue.

**Comment by movikbence** [comment]
@laltralt have you succeeded to build an image with the proper glibc?
