### ISSUE TITLE
max_program_size deprecated but still enforced by client

### ISSUE THREAD

**Issue by LisaLudique** [envoyproxy/envoy#11185]
Relevant Slack thread: https://envoyproxy.slack.com/archives/C78HA81DH/p1589406573415000

`max_program_size` from [RegexMatcher.GoogleRE2](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/regex.proto#envoy-v3-api-field-type-matcher-v3-regexmatcher-googlere2-max-program-size) was deprecated in https://github.com/envoyproxy/envoy/pull/10971 in favor of having the control plane enforce the regex max program size. However the size is still enforced with a default max of 100 if the config does not specify the field: https://github.com/envoyproxy/envoy/blob/302edab55f534abd3f83a297f994b31cf3fb8f92/source/common/common/regex.cc#L50-L56

We should consider not enforcing that check if the `max_program_size` field isn't set in the config (which will happen soon as the field is deprecated) or having the check operate based on runtime flags, another config field, etc.

**Comment by mattklein123** [comment]
cc @htuch @jmarantz @markdroth 

> We should consider not enforcing that check if the max_program_size field isn't set in the config (which will happen soon as the field is deprecated) or having the check operate based on runtime flags, another config field, etc.

Agreed, this is the simple fix and we should just do it. However, I still think this information has value Envoy side and I wonder if we should warn about it? But that could be done as a separate follow up. Potentially with a max program size driven from runtime or something? Curious of the thoughts of others here.

**Comment by ramaraochavali** [comment]
> Potentially with a max program size driven from runtime or something? Curious of the thoughts of others here.

Can we potentially add a histogram stat indicating the `regex_program_size` and log at debug/trace level the regex and program size - so that no additional config needed, but we get information needed?

**Comment by mattklein123** [comment]
> Can we potentially add a histogram stat indicating the regex_program_size and log at debug/trace level the regex and program size - so that no additional config needed, but we get information needed?

Yeah I think we should do something like this, either with optional warnings, stats, etc. I think we should land Lisa's fix though since the current behavior is not correct, but let's discuss in the PR.
