### ISSUE TITLE
Non-hermetic use of build_* dirs for tooling venv

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#11202]
The Docker workflow for tools, e.g. `fix_format`, is generally very repeatable between CI and the local environment. The one exception is the use of `build_*` directories in the source tree for venv artifacts. This can become a problem if they are corrupted or out-of-date across major changes to how venv or tools work.

Possible solutions:
* Bazelify tools and make more of the Bazel native pip3 support (see https://github.com/envoyproxy/envoy/pull/11108)
* For the cases where this isn't practical, introduce a cleanup phase when Docker uses these tools, or place their build directories in tmpdirs.

Ideally we still preserve the venv cache for native use of tooling where possible to provide good dev UX.

**Comment by mattklein123** [comment]
@phlax has been moving everything to bazel so I think this is complete. Closing and we can track specific further issues.
