### ISSUE TITLE
api: allow generic extension config in bootstrap

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#11219]
This is exists in WASM repo in a hard-coded way https://github.com/envoyproxy/envoy-wasm/blob/master/api/envoy/config/bootstrap/v3/bootstrap.proto#L183

We should make a generic mechanism, add a method to extension factory, allowing them to register bootstrap config types then they can do some global initialization based on those config.

@jplevyak @bianpengyuan to complement the exact case for wasm/stackdriver.

cc @envoyproxy/api-shepherds

**Comment by mattklein123** [comment]
+1 this has come up before. I think I suggested this solution previously. I would call this something like "global service extensions" or something like that.
