### ISSUE TITLE
Using Envoy without Docker 

### ISSUE THREAD

**Issue by sojo101** [envoyproxy/envoy#11214]
Hi,

Is there a properway to get envoy on a machine without using docker. I tried to install the getenvoy, but the issue is, it is not working properly with the example given in envoyproxy.io. It was giving error on not finding names like envoy.filters.network.http_connection_manager and other syntax errors, for few I was able to find the alternative but for others it was very tough to debug the issue (given I'm very new to envoy).

The alternative which i tried to resolve this issue, was to copy the envoy folder from your  /usr/local/bin of your docker machines listed in [Pre-built binaries](https://www.envoyproxy.io/docs/envoy/latest/install/building#pre-built-binaries). The question is, that will it be a proper way to use envoy, if we don't have docker set up for our production environment. Can we use these pre-built binary files in production machines?

**Comment by lizan** [comment]
@sojo101 which version of getenvoy (i.e. `envoy --version`) and which example given in envoyproxy.io were you trying to use? The names like `envoy.filters.network.http_connection_manager` are added in [1.14.0](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.14.0#deprecated), so the issue you were seeing are also applicable to official docker release images.

**Comment by sojo101** [comment]
Thanks for the quick reply, I was able to resolve it. Thanks!!
