### ISSUE TITLE
ext_authz v2 api is used even when configured with v3 protos (how to configure to use v3 auth service?)

### ISSUE THREAD

**Issue by sgtsquiggs** [envoyproxy/envoy#11228]
I am configuring envoy via xDS (go-control-plane) with the v3 APIs. When envoy queries my ext_authz service, it is querying using the v2 api instead of the v3 api. I know that in several cases we have to explicitly declare that we are using the v3 api (like with an ADS) but I did not see anywhere to specify which version of envoy auth service to use.

Example of where we need to specify "use v3 api":

```go
Rds: &envoy_extensions_filters_network_http_connection_manager_v3.Rds{
	ConfigSource: &envoy_config_core_v3.ConfigSource{
		ConfigSourceSpecifier: &envoy_config_core_v3.ConfigSource_Ads{Ads: &envoy_config_core_v3.AggregatedConfigSource{}},
		ResourceApiVersion:    envoy_config_core_v3.ApiVersion_V3,
	},
	RouteConfigName: "root",
},
```

As far as I can tell, there isn't anywhere to specify ApiVersion_V3 for ext_authz.

**Comment by ramaraochavali** [comment]
See https://github.com/envoyproxy/envoy/issues/10609

**Comment by dio** [comment]
I think this one is fixed. Please reopen if otherwise. Thank you!
