### ISSUE TITLE
There is no documented way of setting the timezone of timestamps in access log

### ISSUE THREAD

**Issue by amukherj** [envoyproxy/envoy#11238]
Title: There is no documented way of setting the timezone of timestamps in access log

Description:

I want only UTC timestamps in the Envoy access logs. However there seems to be no documented way of setting the timezone of log timestamps. It just picks up the local time. I am able to do the following for a workaround but this seems hacky.

    TZ=UTC envoy -c <config>

#3546 seems to suggest that the log entry timestamps are always in UTC, but I don't see this to be the case (envoy 1.14).

**Comment by mattklein123** [comment]
I'm pretty sure this used to be true (not 100% positive) but it's possible this regressed when we moved away from old time functions to either C++ chrono time and/or abseil. @jmarantz any thoughts here?

**Comment by amukherj** [comment]
In the mean time, do you see any risks with setting TZ=UTC for the envoy process?

**Comment by mattklein123** [comment]
> In the mean time, do you see any risks with setting TZ=UTC for the envoy process?

I don't think so, but I would definitely like @jmarantz to weigh in as he knows more about time stuff.

**Comment by jmarantz** [comment]
No worries, computers work off of UTC anyway; the time-zone is just for printing to human-readable strings.
