### ISSUE TITLE
incorrect stats increment for streaming requests

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#11237]
When a streaming service (let us say xds service) connects and disconnects with Envoy the `cluster.xds_cluster.upstream_rq_pending_failure_eject`, `cluster.xds_cluster.upstream_rq_pending_total` and `rq_5xx` are getting incremented incorrectly.  See below for a case where I disconnected twice.  Not sure if it was like that from earlier (IIRC - it is not the case) or it was caused by some recent changes like https://github.com/envoyproxy/envoy/pull/9668

Has any one seen this? Just opening an issue for us to track 

```
cluster.xds_cluster.upstream_rq_200: 2
cluster.xds_cluster.upstream_rq_2xx: 2
cluster.xds_cluster.upstream_rq_503: 96
cluster.xds_cluster.upstream_rq_5xx: 96
cluster.xds_cluster.upstream_rq_active: 0
cluster.xds_cluster.upstream_rq_completed: 98
cluster.xds_cluster.upstream_rq_pending_active: 0
cluster.xds_cluster.upstream_rq_pending_failure_eject: 98
cluster.xds_cluster.upstream_rq_pending_total: 98
```

**Comment by mattklein123** [comment]
@ramaraochavali sorry what do you think the problem is specifically? I'm not 100% clear on what the issue is.

**Comment by ramaraochavali** [comment]
@mattklein123 The problem is the increment of the following stats - When a client disconnects and reconnects to Envoy two times - I see them incremented like below. Even on single disconnection, the following stats are incremented. IIRC, even on connection these are getting incremented. 
```
cluster.xds_cluster.upstream_rq_pending_failure_eject: 98
cluster.xds_cluster.upstream_rq_pending_total: 98
```

**Comment by ramaraochavali** [comment]
I debugged this a bit more and found that this stat is also incremented for stream reset via connection termination from upstream

https://github.com/envoyproxy/envoy/blob/master/source/common/http/http2/conn_pool.cc#L53

Those were happening in our case. Now the stats make sense. I will push a PR to clarify that in the docs.
