### ISSUE TITLE
[test] Some test/extensions/clusters/redis/redis_cluster_integration_test test cases not running due to missing INSTANTIATE_TEST_SUITE_P

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#11246]
The test RedisClusterWithReadPolicyIntegrationTest.SingleSlotMasterReplicaReadReplica and  RedisClusterWithRefreshIntegrationTest.ClusterSlotRequestAfterFailure are not running because a INSTANTIATE_TEST_SUITE_P is missing from the test definition.

Missing lines diff test/extensions/clusters/redis/redis_cluster_integration_test.cc
@@ -376,6 +376,14 @@ INSTANTIATE_TEST_SUITE_P(IpVersions, RedisClusterWithAuthIntegrationTest,
                          testing::ValuesIn(TestEnvironment::getIpVersionsForTest()),
                          TestUtility::ipTestParamsToString);
 
+INSTANTIATE_TEST_SUITE_P(IpVersions, RedisClusterWithReadPolicyIntegrationTest,
+                         testing::ValuesIn(TestEnvironment::getIpVersionsForTest()),
+                         TestUtility::ipTestParamsToString);
+
+INSTANTIATE_TEST_SUITE_P(IpVersions, RedisClusterWithRefreshIntegrationTest,
+                         testing::ValuesIn(TestEnvironment::getIpVersionsForTest()),
+                         TestUtility::ipTestParamsToString);
+
 // This test sends a simple "get foo" command from a fake

When the missing INSTANTIATE_TEST_SUITE_P are added, the test fails with timeout as follows:

[----------] 2 tests from IpVersions/RedisClusterWithRefreshIntegrationTest
[ RUN      ] IpVersions/RedisClusterWithRefreshIntegrationTest.ClusterSlotRequestAfterFailure/IPv4
test/extensions/clusters/redis/redis_cluster_integration_test.cc:598: Failure
Value of: fake_upstreams_[0]->waitForRawConnection(fake_upstream_connection_2)
  Actual: false (Timed out waiting for raw connection)
Expected: true
Stack trace:
  0x21515cb: Envoy::(anonymous namespace)::RedisClusterWithRefreshIntegrationTest_ClusterSlotRequestAfterFailure_Test::TestBody()
  0x4df91f4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4de80bb: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4dd4113: testing::Test::Run()
  0x4dd4ae7: testing::TestInfo::Run()
... Google Test internal frames ...

[ RUN      ] IpVersions/RedisClusterWithReadPolicyIntegrationTest.SingleSlotMasterReplicaReadReplica/IPv4
test/extensions/clusters/redis/redis_cluster_integration_test.cc:225: Failure
Value of: fake_upstream_connection->waitForData(request.size(), &proxy_to_server)
  Actual: false (Timed out waiting for data.)
Expected: true
Stack trace:
  0x213bb9b: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::roundtripToUpstreamStep()
  0x2138146: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::simpleRequestAndResponse()
  0x214744a: Envoy::(anonymous namespace)::RedisClusterWithReadPolicyIntegrationTest_SingleSlotMasterReplicaReadReplica_Test::TestBody()
  0x4dfa234: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4de90fb: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4dd5153: testing::Test::Run()
  0x4dd5b27: testing::TestInfo::Run()
... Google Test internal frames ...

test/extensions/clusters/redis/redis_cluster_integration_test.cc:227: Failure
Expected equality of these values:
  request
    Which is: "*3\r\n$3\r\nset\r\n$3\r\nfoo\r\n$3\r\nbar\r\n"
  proxy_to_server
    Which is: ""
With diff:
@@ -1,7 +1,1 @@
-*3\r
-$3\r
-set\r
-$3\r
-foo\r
-$3\r
-bar\r\n
+""

Stack trace:
  0x213bcf5: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::roundtripToUpstreamStep()
  0x2138146: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::simpleRequestAndResponse()
  0x214744a: Envoy::(anonymous namespace)::RedisClusterWithReadPolicyIntegrationTest_SingleSlotMasterReplicaReadReplica_Test::TestBody()
  0x4dfa234: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4de90fb: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4dd5153: testing::Test::Run()
  0x4dd5b27: testing::TestInfo::Run()
... Google Test internal frames ...

-- Test timed out at 2020-05-18 20:06:08 UTC --
test/extensions/clusters/redis/redis_cluster_integration_test.cc:233: Failure
Expected equality of these values:
  response
    Which is: ":1\r\n"
  redis_client->data()
    Which is: "-upstream failure\r\n"
Stack trace:
  0x213c008: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::roundtripToUpstreamStep()
  0x2138146: Envoy::(anonymous namespace)::RedisClusterIntegrationTest::simpleRequestAndResponse()
  0x214744a: Envoy::(anonymous namespace)::RedisClusterWithReadPolicyIntegrationTest_SingleSlotMasterReplicaReadReplica_Test::TestBody()
  0x4dfa234: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4de90fb: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4dd5153: testing::Test::Run()
  0x4dd5b27: testing::TestInfo::Run()
... Google Test internal frames ...

**Comment by mattklein123** [comment]
@HenryYYang can you please take a look and fix?
