### ISSUE TITLE
upstream_rq_active across hot restarts

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#11256]
upstream_rq_active across hot restarts is carried forward to the child Envoy because it is marked as "Accumulate". This is decremented on request close (which happens on parent Envoy). So this seems to incorrect.

Should this gauge be of "NeverImport" type?

@jmarantz @mattklein123 WDYT?

**Comment by mattklein123** [comment]
I think it should definitely be accumulate as you want to know how many are active across both processes. The gauge should correctly decrement as the parent closes requests though. Note that there is a bug where we might not correctly decrement all of the parent's stats. See https://github.com/envoyproxy/envoy/issues/10806. We should definitely get that fixed.

**Comment by ramaraochavali** [comment]
Got it. Thanks
