### ISSUE TITLE
API to Expose Histogram Raw Bins

### ISSUE THREAD

**Issue by pjulien** [envoyproxy/envoy#11259]
In order to provide richer telemetry, it would be useful to provide the raw histogram bins found in the internal Circonus histograms to the outside world.

I have added data members to ``histogram_impl`` to record these bins so they can be made available via ``gRPC``.  However, it seems the ``gRPC`` messages from ``MetricsServiceSink`` are lifted directly from ``prometheus``.  This schema does not feature a message type that is appropriate for exposing these bins.

Would you have any guidance or preference on how this data should be exposed to the outside world?

**Comment by ggreenway** [comment]
Why is the prometheus format not adequate? It allows specifying both the bin upper-bound and the count. If the producer (in Envoy) populated this with all of the underlying bins from the histogram implementation, wouldn't that be what you're looking for?

**Comment by mattklein123** [comment]
cc @postwait who also contacted me about this offline.

**Comment by pjulien** [comment]
@ggreenway it could be but the histogram bins are all 8 bit integers.  The messages you're talking about are mostly floating point doubles.

**Comment by postwait** [comment]
@ggreenway so the internal format has explicit integral boundaries and "count below" which is what prometheus looks like is a transform that looses expressiveness without a lot of extra space.

In the internal binning bin {10,0} is lower bounded inclusively at 1.0 and upper bounded exclusively at 1.1.  That's challenging to express and also doesn't belong in a double.

Ideally, it would be a sparse list of `{ uint8_t val, uint8_t exp, uint64_t sample_count }` tuples.

**Comment by pjulien** [comment]
@ggreenway @mattklein123 /cc @postwait 

Pinging to keep this discussion alive

**Comment by mattklein123** [comment]
What sinks do we want this data to come out of? All? Just metrics service? Various `/stats` endpoints? I think that will help frame the conversation.

**Comment by pjulien** [comment]
> What sinks do we want this data to come out of? 

metrics via ``gRPC``.  We would pick up the data by polling it.

**Comment by mattklein123** [comment]
OK. My advice is to propose some API changes to enable this. If we need to move away from the prometheus protos I think that is OK.

**Comment by pjulien** [comment]
@mattklein123 /cc @postwait 

> My advice is to propose some API changes to enable this

After looking at the code, it seems that the `gRPC` code for metric sinks only allows pushing out data to providers.  I would like to add another `stats_sinks` or should I say "stat sink" similar to what was done for `Prometheus`.  The reasoning behind this is to allow custom polling by customers:  

1. In most scenarios, the URL in the admin page would be hit every minute and would be used for monitoring
1. However, when there is an incident, a customer could poll at a custom frequency, say every second, in order to render a graph.

The output of the service would be accessible from the admin console and would be either `protobuf` or `JSON` or whatever you wish.  This new admin page URL would contain all metrics including the histogram raw bins.

Finally, I am unsure if it's possible to make this code available as a ``stats_sinks`` extension since it would never actually push out any data itself using the ``xDS`` API.  In which case, I believe it needs to be integrated at the same level as `Prometheus` in the core server itself.

**Comment by mattklein123** [comment]
If you want pull behavior, a new admin handler seems right. Note that custom admin handlers can be added by extensions, including stat sinks. See the hystrix extension for example. cc @jmarantz in case he has any additional thoughts on this.

**Comment by pjulien** [comment]
Thank you @mattklein123 .  I'll check the extension out and proceed as outlined unless someone objects.

**Comment by pjulien** [comment]
@mattklein123 

> Note that custom admin handlers can be added by extensions, including stat sinks. 

One question for you... what macro should I use to register the factory?  Unlike `hystrix`, I'm only adding an admin handler, not a stat sink.  I have no need to implement `Stats::Sink`.

I tried using

```c++
REGISTER_FACTORY(CirconusSinkFactory, Envoy::Config::UntypedFactory);
```

but that doesn't seem to do anything.

**Comment by mattklein123** [comment]
You could probably make it a bootstrap extension? https://github.com/envoyproxy/envoy/pull/11413. cc @lizan

**Comment by pjulien** [comment]
@mattklein123 

> You could probably make it a bootstrap extension?

I don't see any way of getting to the `Server::Instance` with this type of extension.  I need to register the handler and it does seem like I can get `Server::Admin` from `ServerFactoryContext` but I also need the stats store and that doesn't seem to be reachable without `Server::Instance`.

Maybe a no-op `stats-sink` might be worthwhile here?  Just so we have proper initialization.

**Comment by mattklein123** [comment]
The boostrap extension is new but it should have access to the stats store if that is what is needed for this. Or, a no-op stats-sink extension might be fine also.

**Comment by pjulien** [comment]
@mattklein123 

I have added a [PR](https://github.com/envoyproxy/envoy/pull/11642) with the feature without tests or change log to gather initial feedback.

**Comment by kamelkev** [comment]
Any updates here?

**Comment by jmarantz** [comment]
A few years late but I'm messing around with visualizing histograms in the admin endpoint via html/js. It's still just messing around, but it's in https://github.com/envoyproxy/envoy/pull/26472.

In that PR, there's an endpoint /stats?type=Histograms&format=json/histogram_buckets=detailed which gives all the raw buckets from circlhist.

@postwait as you are on this thread, I wondered if you could help me understand what the max number of buckets I might see from `hist_num_buckets(cumulative_histogram_);` is. If it's not bounded then some C++-side aggregation may be needed; but it would be nice to expose the full data to the endpoint so consumers could do whatever hi-res thing they want.

**Comment by jmarantz** [comment]
@sschepens FYI -- do you want to own this (once I get the part of https://github.com/envoyproxy/envoy/pull/26472 that provides C++ access to the raw bins)?

**Comment by sschepens** [comment]
@jmarantz catching up here.

MetricsService already sends histogram buckets, what's the difference with what's @pjulien is asking? is it cumulative buckets and not just the interval buckets?

Also, according to @pjulien they don't actually need MetricsService for this, in that case, is there any need to add this to MetricsService?

**Comment by jmarantz** [comment]
The difference is that the histogram buckets that are sent are 19 very coarse buckets of fixed values. There is a built-in default, and these can be altered based on a match expression when starting Envoy, but I suspect that doesn't happen often.

The underlying histogram mechanism (circlhist) auto-computes buckets to match the data but most of that precision gets dropped when mapping to the fixed buckets. So when you start drawing histograms as I am trying to do in #26472 there isn't much useful data in them (IMO). So (AFAIK) that PR will be the first time in Envoy we've exposed the auto-computed bucket data .

The reason fixed buckets are desirable, at least on a per histogram basis, is that it makes it easier to aggregate the histogram data in the time-series database.
