### ISSUE TITLE
Support overriding host in XDS connection

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#11254]
Currently headers can be set for the XDS connection, via initial_metadata. For example:
```
          "initial_metadata": [
            {"key":"x-environment", "value": "canary"},
          ]
```

However, using this to set the host does not work.
```
          "initial_metadata": [
            {"key":":authority", "value": "xds.example.com"},
          ]
```

will result in the header being appended. A receiving Envoy will show the request as:

```
':method', 'POST'
':path', '/envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources'
':authority', 'xds-grpc,xds.example.com"
':scheme', 'https'
'te', 'trailers'
'content-type', 'application/grpc'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.4.2.4'
```
(note: cluster name is xds-grpc)

Setting `key=Host` has similar behavior

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host, " A 400 (Bad Request) status code may be sent to any HTTP/1.1 request message that lacks a Host header field or that contains more than one." which seems like appending the host header is not valid.

The motivation for this is to have an XDS proxy (another Envoy) that routes to the XDS server using Host header.

An alternative is to rename the cluster, but that will cause issues as all of our stats, alerting, tooling, etc expect an "xds-grpc" cluster.

**Comment by howardjohn** [comment]
/help-wanted (this probably doesn't actually do anything, but worth a shot)

**Comment by howardjohn** [comment]
cc @linsun @costinm @nmittler since you all independently ran into this same issue

**Comment by lambdai** [comment]
Envoy start to allow override host in envoy grpc.
Google grpc could extract host in grpc url. Something like the "www.google.com" in url "www.google.com/method".

See 
https://github.com/envoyproxy/envoy/pull/12338
