### ISSUE TITLE
How to invoke external Rest API within an Envoy filter

### ISSUE THREAD

**Issue by pheely** [envoyproxy/envoy#11262]
I am working on an Envoy HTTP filter that needs to invoke an external REST API and change the original request before sending to the upstream. I noticed [rest_api_fetcher](https://github.com/envoyproxy/envoy/blob/master/source/common/http/rest_api_fetcher.h). However, I don't know how to use it. Could you pinpoint me to any concrete example or any documentation. Thanks in advance.

**Comment by dio** [comment]
@pheely I think you're looking at implementing `Http::AsyncClient::Callbacks`. 

This is an example of calling out an endpoint from Envoy to a predefined "cluster". https://github.com/envoyproxy/envoy/blob/347ec29ab1834e14b49df4e24618ee07d57cf3c2/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L272-L274.

**Comment by mengmichael1** [comment]
@pheely Did you ever figure out how to get this working?
