### ISSUE TITLE
How to get upstream host from custom http filter or network filter?

### ISSUE THREAD

**Issue by lazy-always** [envoyproxy/envoy#11273]
Is there a way to get upstream host from http filter or network filter? callbacks_->streamInfo().upstreamHost() is alway nullptr. Basically, the custom filter needs to get lb-selected upstream host. Is it possible? I tried with upstream network filter. But upstreamHost is always nullptr. Please help.

**Comment by yuval-k** [comment]
AFAIK, host selection happens after your filter runs.
try implementing the `AccessLog::Instance` interface, and you should see it when the `log` method is called.

**Comment by lazy-always** [comment]
I am able to get this with "callbacks_->connection().remoteAddress()->asStringView()" but it gives the resolved IP Address. I am looking for the host name instead of IP Address. Any help?

**Comment by moisesrc13** [comment]
@yuval-k 
I also have the same question. Is there a way to get the  upstream host or IP and send it back in the envoy response?
