### ISSUE TITLE
Add support for Redis 6 ACL

### ISSUE THREAD

**Issue by jamesbibby** [envoyproxy/envoy#11296]
*Title*: Add support for Redis 6 ACL

*Description*:
Redis 6 introduces ACLs which require a username and password.   We would like to continue to use Envoy as a proxy for these deployments.

[Redis ACL]https://redis.io/topics/acl

I think there are two ways to go on the implementation.   Adding an optional username alongside the password in the options, or adding a new ACL type of configuration which requires a username and a password.   Interested in your thoughts and happy to contribute.

**Comment by mattklein123** [comment]
cc @envoyproxy/redis-dev for comment.
