### ISSUE TITLE
WIP: Resolve WSAE* errors on Windows into expected Posix error states

### ISSUE THREAD

**Issue by wrowe** [envoyproxy/envoy#11298]
We need an efficient mechanism/error class for seamlessly handling WSAE* results from windows socket api calls without an excessive switch case block of all possible translations. This may look like a new error class, mapped to a single int (DWORD) errno_ member, which can be evaluated with isEAgain(), isENotFound() and similar methods of evaluation.

This is a tracking issue just to note that @sunjayBhatia and I are attacking this puzzle next, during the first week of June. We expect this single change will eliminate a significant percentage of currently-failing tests on windows.

tag: area/windows

**Comment by davinci26** [comment]
Based on the winsock [connect](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-connect) documentation.

> For connection-oriented, nonblocking sockets, it is often not possible to complete the connection immediately. In such a case, this function returns the error WSAEWOULDBLOCK. However, the operation proceeds.

This affects the code in `ClientConnectionImpl::connect()`

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/11565 for some a solution to this issue and some commentary on alternative solutions; please review and provide feedback on the approach we have taken and alternatives considered
