### ISSUE TITLE
Impossible to establish a WebSocket/SignalR connection from Xamarin application using Envoy as proxy on an AWS ec2 machine

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [envoyproxy/envoy#11294]
_Description:_

This is driving me insane.

I am using Envoy as front-end proxy for a series of web services deployed in a EC2 instance on AWS (accessed through public ip address, so no other load balancer in the middle). 

For the REST api part i have no problems, but i have serious issues trying to establish a WebSocket connection using SignalR Core inside a Xamarin Android application.

The situation is the following:

Client --> Library Signalr C# --> Envoy (on AWS EC2, http protocol) --> Hub SignalR

In this chain the first element (the client) use a library (.net standard 2.0) that encapsulates the Microsoft 1.1.0 SignalR Core client.

Since i must guarantee that the library works both for windows and android applications, i created 2 test clients:

- a .net framework Windows Form client
- a Xamarin Android client

They both use my .net standard SignalR client library, and obviously anything (from the configuration of Envoy to the SignalR Hub) on the server is the same.

Now, the odd part is that the Windows Form client works fine (it establish the connection and is able to communicate with the Hub without problems), while the Xamarin Android client does not work at all (it is unable to establish even the connection, Envoy rejects it....).

Enabling the logs on Envoy i can see the following situation:

**Logs done with the Windows Form client:**

	[2020-05-22 13:53:02.534][12][debug][http] [source/common/http/conn_manager_impl.cc:261] [C5] new stream
	[2020-05-22 13:53:02.534][12][debug][http] [source/common/http/conn_manager_impl.cc:807] [C5][S14758295950792864533] request headers complete (end_stream=false):
	':authority', 'hprv.lsetest.gq'
	':path', '/evt/events'
	':method', 'GET'
	'connection', 'Upgrade,Keep-Alive'
	'upgrade', 'websocket'
	'sec-websocket-key', '2d4APjHTWNa+xR6+G7Mn6A=='
	'sec-websocket-version', '13'
	'x-requested-with', 'XMLHttpRequest'
	'authorization', 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQzMTRkNDg3YTdkZDUwMzlkYTYxOWYwNGNmYmUwOWQ0IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1OTAxNTU1ODEsImV4cCI6MTU5MDE1OTE4MSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EiLCJhdWQiOlsiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EvcmVzb3VyY2VzIiwiaHguY2wuYXBpIl0sImNsaWVudF9pZCI6Imh4LmNsLmFwaSIsInN1YiI6IjMiLCJhdXRoX3RpbWUiOjE1OTAxNTU1ODEsImlkcCI6ImxvY2FsIiwiaHgzNjUudXNlci5hY2NvdW50X3R5cGUuY2xhaW0iOiJVU1IiLCJoeDM2NS51c2VyLmRhdGEuY2xhaW0iOiJleUpKWkNJNk15d2lURzRpT2lKcGRHRWlMQ0pEYmlJNklrbFVRU0lzSWs1dElqb2lRVzUwYjI1cGJ5SXNJazF1SWpvaUlpd2lVMjRpT2lKRGIybHRZbkpoSWl3aVJXMGlPaUpoTG1OdmFXMWljbUZBZVdGNlpYWmxaRzh1WW5JaUxDSk5ZeUk2ZXlKSlpDSTZNeXdpVG0waU9pSkJiblJ2Ym1sdklFTnZhVzFpY21FaUxDSkJkQ0k2SWxWVFVpSXNJbEpzSWpwYklrOVhUaUpkZlN3aVEzTWlPbHRkTENKR2JDSTZNelFzSWtGalkyOTFiblJVZVhCbElqb2lWVk5TSWl3aVFXTmpiM1Z1ZEVsdWRHVnlibUZzSWpwbVlXeHpaU3dpUVdOamIzVnVkRkpsWjNWc1lYSWlPblJ5ZFdVc0lsQnlhWFpoWTNsQlkyTmxjSFJsWkNJNmRISjFaU3dpVlhObGNrUmxiR1YwWldRaU9tWmhiSE5sZlE9PSIsInNjb3BlIjpbImh4MzY1LnVzZXIuZGF0YSIsIm9wZW5pZCIsImh4LmNsLmFwaS5zY29wZSJdLCJhbXIiOlsiY3VzdG9tIl19.hFgsZ2sfQ-PJ7PCczutgyickfm5SEnlPYR9fgDpV0v8bdSC8-Uj4G2F9kTatMZJH6EtDO1rQTRaHO4n9G-LDWYVfhiRT8Fv9rtylxSIe_F_JGhBxrKO0YS3w_P32u6VQMy4q309QLVk6wkqBDs55ckXHKidkgKEaNGxY_Uku7-_vHJ8nYgGvC1sP2-_a9IPZAGdALND5wBIaHmhwJqo3gsD2ma0rZR3RAh0sEXdY8XP6quNbhf4GxsKqMrJrjRohi6xwU6QTmqy6u6DdVxMArix5H2yeXC2LbQh0ysdycJJHiXiVSYtOZuWGnaVhQJ-tz5mh0xPu43aK0qly11eKiA'

	[2020-05-22 13:53:02.534][12][debug][router] [source/common/router/router.cc:441] [C5][S14758295950792864533] cluster 'signalrhub21' match for URL '/evt/events'
	[2020-05-22 13:53:02.534][12][debug][router] [source/common/router/router.cc:597] [C5][S14758295950792864533] router decoding headers:
	':authority', 'hprv.lsetest.gq'
	':path', '/hubs/messages'
	':method', 'GET'
	':scheme', 'http'
	...

As you can see, the request is correctly matched and envoy route it to the hub.

**Logs done with the Xamarin Android client:**

	[2020-05-22 13:55:25.288][12][debug][http] [source/common/http/conn_manager_impl.cc:261] [C13] new stream
	[2020-05-22 13:55:25.288][12][debug][http] [source/common/http/conn_manager_impl.cc:807] [C13][S4493325436694169361] request headers complete (end_stream=false):
	':authority', 'hprv.lsetest.gq:80'
	':path', '/evt/events'
	':method', 'GET'
	'connection', 'Upgrade'
	'upgrade', 'websocket'
	'sec-websocket-version', '13'
	'sec-websocket-key', 'rnIJj9f7tkmAl0GDvHpsRQ=='
	'x-requested-with', 'XMLHttpRequest'
	'authorization', 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQzMTRkNDg3YTdkZDUwMzlkYTYxOWYwNGNmYmUwOWQ0IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1OTAxNTU3MjQsImV4cCI6MTU5MDE1OTMyNCwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EiLCJhdWQiOlsiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EvcmVzb3VyY2VzIiwiaHguY2wuYXBpIl0sImNsaWVudF9pZCI6Imh4LmNsLmFwaSIsInN1YiI6IjMiLCJhdXRoX3RpbWUiOjE1OTAxNTU3MjQsImlkcCI6ImxvY2FsIiwiaHgzNjUudXNlci5hY2NvdW50X3R5cGUuY2xhaW0iOiJVU1IiLCJoeDM2NS51c2VyLmRhdGEuY2xhaW0iOiJleUpKWkNJNk15d2lURzRpT2lKcGRHRWlMQ0pEYmlJNklrbFVRU0lzSWs1dElqb2lRVzUwYjI1cGJ5SXNJazF1SWpvaUlpd2lVMjRpT2lKRGIybHRZbkpoSWl3aVJXMGlPaUpoTG1OdmFXMWljbUZBZVdGNlpYWmxaRzh1WW5JaUxDSk5ZeUk2ZXlKSlpDSTZNeXdpVG0waU9pSkJiblJ2Ym1sdklFTnZhVzFpY21FaUxDSkJkQ0k2SWxWVFVpSXNJbEpzSWpwYklrOVhUaUpkZlN3aVEzTWlPbHRkTENKR2JDSTZNelFzSWtGalkyOTFiblJVZVhCbElqb2lWVk5TSWl3aVFXTmpiM1Z1ZEVsdWRHVnlibUZzSWpwbVlXeHpaU3dpUVdOamIzVnVkRkpsWjNWc1lYSWlPblJ5ZFdVc0lsQnlhWFpoWTNsQlkyTmxjSFJsWkNJNmRISjFaU3dpVlhObGNrUmxiR1YwWldRaU9tWmhiSE5sZlE9PSIsInNjb3BlIjpbImh4MzY1LnVzZXIuZGF0YSIsIm9wZW5pZCIsImh4LmNsLmFwaS5zY29wZSJdLCJhbXIiOlsiY3VzdG9tIl19.gfomQjMtdpR9hKaryFv7z1wMkG4hpgfCc9IBhTmtZMBqBZbP8wpfwovWS17-hgOnC76Wc_RjTGDJrNirDnpc2v_wO4zXIB5-YmDJ6vW6QQriie4JP-ZPJHM04iia8wx_IN5QCVq-b3zYRhOiniUukEax-8qjUXSkY9gk1no2q7jUjfkThJa-bVVLuoURFi34X1ArMZT-kSQfIb0FRCyXrue7Fkk7kpHGTMxKjOzelYvcS_16SZ4sTW4jZx48_2eh40jPtdCJGrgp8yW0WnmQQ-fAW9eM3WqNXkT2VJCXUQ5FHrXWL-HYqSRzrYEaO_K2IfGg3GoC_qz32fU4MyMkFg'

	[2020-05-22 13:55:25.288][12][debug][router] [source/common/router/router.cc:376] [C13][S4493325436694169361] no cluster match for URL '/evt/events'
	[2020-05-22 13:55:25.288][12][debug][http] [source/common/http/conn_manager_impl.cc:1516] [C13][S4493325436694169361] Sending local reply with details route_not_found

As you can see, the same request (done to the same url with the same parameters) does not works.... it does not arrive even to the Hub, it is Envoy that rejects it immediately.

The only difference in the two requests is the 'connection' header value, which is:

- In Windows Form: 'connection', 'Upgrade,Keep-Alive'
- In Xamarin: 'connection', 'Upgrade'

Now, i can think that maybe this is the problem... but when i try to run a copy of this configuration locally it all runs fine..... In fact if i modify the same Xamarin Android application (that runs on the same emulator) to point to a local configuration of Envoy (that connect to a local copy of the SignalR Hub), then it works!!!! (i use docker images, so i am sure that they are exact the same, both on local and on the server).

	[2020-05-22 14:01:44.874][13][debug][http] [source/common/http/conn_manager_impl.cc:261] [C0] new stream
	[2020-05-22 14:01:44.875][13][debug][http] [source/common/http/conn_manager_impl.cc:807] [C0][S6140785255548295220] request headers complete (end_stream=false):
	':authority', '10.0.2.2:80'
	':path', '/hubs21/messages'
	':method', 'GET'
	'connection', 'Upgrade'
	'upgrade', 'websocket'
	'sec-websocket-version', '13'
	'sec-websocket-key', 'Kj4LRxuB5U24QLXiaCv0Ng=='
	'x-requested-with', 'XMLHttpRequest'
	'authorization', 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImQzMTRkNDg3YTdkZDUwMzlkYTYxOWYwNGNmYmUwOWQ0IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1OTAxNTYxMDMsImV4cCI6MTU5MDE1OTcwMywiaXNzIjoiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EiLCJhdWQiOlsiaHR0cHM6Ly9hdXRoLmxzZXRlc3QuZ3EvcmVzb3VyY2VzIiwiaHguY2wuYXBpIl0sImNsaWVudF9pZCI6Imh4LmNsLmFwaSIsInN1YiI6IjMiLCJhdXRoX3RpbWUiOjE1OTAxNTYxMDMsImlkcCI6ImxvY2FsIiwiaHgzNjUudXNlci5hY2NvdW50X3R5cGUuY2xhaW0iOiJVU1IiLCJoeDM2NS51c2VyLmRhdGEuY2xhaW0iOiJleUpKWkNJNk15d2lURzRpT2lKcGRHRWlMQ0pEYmlJNklrbFVRU0lzSWs1dElqb2lRVzUwYjI1cGJ5SXNJazF1SWpvaUlpd2lVMjRpT2lKRGIybHRZbkpoSWl3aVJXMGlPaUpoTG1OdmFXMWljbUZBZVdGNlpYWmxaRzh1WW5JaUxDSk5ZeUk2ZXlKSlpDSTZNeXdpVG0waU9pSkJiblJ2Ym1sdklFTnZhVzFpY21FaUxDSkJkQ0k2SWxWVFVpSXNJbEpzSWpwYklrOVhUaUpkZlN3aVEzTWlPbHRkTENKR2JDSTZNelFzSWtGalkyOTFiblJVZVhCbElqb2lWVk5TSWl3aVFXTmpiM1Z1ZEVsdWRHVnlibUZzSWpwbVlXeHpaU3dpUVdOamIzVnVkRkpsWjNWc1lYSWlPblJ5ZFdVc0lsQnlhWFpoWTNsQlkyTmxjSFJsWkNJNmRISjFaU3dpVlhObGNrUmxiR1YwWldRaU9tWmhiSE5sZlE9PSIsInNjb3BlIjpbImh4MzY1LnVzZXIuZGF0YSIsIm9wZW5pZCIsImh4LmNsLmFwaS5zY29wZSJdLCJhbXIiOlsiY3VzdG9tIl19.ZTum-WGjPaVV5RRVemWPfq3qkkMkqiwrH7Yi8dxsQWj7zkbmT03W3t-YQmbkXg0FjlDjBzy4-ULTrQWRh4EPkQliadLRWcHN2uBy2fMGp7JYapgUmBxqpmLwNGBg3UrDD7XqzcNvxdNOfrLzl6zlIz1BFjObDLzrOssWpgYdkTvAgjxo1QqPgUxsBYAYWStFcsY3ZEykJr8Brw2601llTuVCMDXRq72cc4g3c8yeF1HfB6jjjT9Qq5n-rgJ35V9i2hm1i1EWuvZV2R-7u9q4j7_iaOZA7C6f0-9rHy9zwLWravAcQWb9MkKf02BCynFipWyoocpsIoa2UJsrXLanKQ'

	[2020-05-22 14:01:44.875][13][debug][router] [source/common/router/router.cc:441] [C0][S6140785255548295220] cluster 'signalrhub21' match for URL '/hubs21/messages'

NOTE: in local the url is different but it is the only thing that change in the configuration...

If (on the server) i replace Envoy with Nginx (configured in the same way) it works on all cases.

If i choose a different transport type (instead of Web Socket i try with Long Polling) then all it works (also in Xamarin Android).

If i use a javascript client then all it works.

To summarize:

	|                                  Xamarin Android                              |
	|                 Local                 |                 Server                |
	|        HTTP       |        HTTPs      |        HTTP       |        HTTPs      |
	|  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |
	| WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP |
	| ok |    |    |    |    |    |    |    | KO | ok | ok | ok | KO | ok |    |    |
	---------------------------------------------------------------------------------
	|                                  Windows Form                                 |
	|                 Local                 |                 Server                |
	|        HTTP       |        HTTPs      |        HTTP       |        HTTPs      |
	|  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |
	| WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP |
	| ok | ok |    |    | ok | ok |    |    | ok | ok | ok | ok | ok | ok |    |    |
	---------------------------------------------------------------------------------
	|                                  Client javascript                            |
	|                 Local                 |                 Server                |
	|        HTTP       |        HTTPs      |        HTTP       |        HTTPs      |
	|  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |  Envoy  |  Nginx  |
	| WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP | WS | LP |
	|    |    |    |    |    |    |    |    |    |    |    |    | ok |    |    |    |

	WS = WebSocket
	LP = LongPolling

I already tried to open a ticket on Microsoft, i get some useful advices but not the answer to the problem.

I tried o create a visual studio solution to display the error, but locally it works.... only on the server is not working.

Version of software used:

Envoy Proxy: latest available (at 2020-05-22) dockerized development image (needed to solve another problem related to SignalR and WebSocket, see issue https://github.com/envoyproxy/envoy/issues/10955).

Xamarin compiled for Android 7.1 (minimum version 4.1)
Microsoft SignalR client library: 1.1.0
My client library .Net Standard 2.0 (but i also tried without my library and the result is the same... i only incapsulate the standard library and do other things).

The local configuration (the one on the server differs only on the fact that it has more routes defined) of Envoy is the follow:

	admin:
	  access_log_path: /tmp/admin_access.log
	  address:
		socket_address: 
		  address: 0.0.0.0
		  port_value: 9901
	static_resources:
	  listeners:
		- address:
			socket_address:
			  address: 0.0.0.0
			  port_value: 80
		  filter_chains:
			- filters:
			  - name: main_routing
				typed_config: 
				  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
				  codec_type: auto
				  # use_remote_address: true
				  access_log:
				  - name: envoy.access_loggers.file
					typed_config:
					  "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
					  path: /dev/stdout
					  json_format:
						time: "%START_TIME%"
						protocol: "%PROTOCOL%"
						duration: "%DURATION%"
						request_method: "%REQ(:METHOD)%"
						request_host: "%REQ(HOST)%"
						path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
						response_flags: "%RESPONSE_FLAGS%"
						route_name: "%ROUTE_NAME%"
						upstream_host: "%UPSTREAM_HOST%"
						upstream_cluster: "%UPSTREAM_CLUSTER%"
						upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"

				  stat_prefix: ingress_http
				  route_config:
					name: local_config
					virtual_hosts:
					- name: proxy_priv_hub
					  domains:
						- "*"
						- "localhost"
						- "127.0.0.1"
					  routes:
						- match: { prefix: "/hubs/", case_sensitive: false }
						  route: 
							cluster: signalrhub
							auto_host_rewrite: true
							prefix_rewrite: "/hubs/"
							timeout: 300s
							upgrade_configs:
							  upgrade_type: "websocket"
							  enabled: true

						- match: { prefix: "/hubs21/", case_sensitive: false }
						  route: 
							cluster: signalrhub21
							auto_host_rewrite: true
							prefix_rewrite: "/hubs/"
							timeout: 300s
							upgrade_configs:
							  upgrade_type: "websocket"
							  enabled: true

						- match: { prefix: "/21/", case_sensitive: false }
						  route: { cluster: signalrhub21, prefix_rewrite: "/" }

						- match: { prefix: "/", case_sensitive: false }
						  route: { cluster: signalrhub }
						- match: { prefix: "", case_sensitive: false }
						  route: { cluster: signalrhub }

				  http_filters:
					- name: envoy.filters.http.fault
					  typed_config:
						"@type": type.googleapis.com/envoy.config.filter.http.fault.v2.HTTPFault
						abort:
						  http_status: 503
						  percentage:
							numerator: 0
							denominator: HUNDRED
					- name: envoy.filters.http.router
					  typed_config: {}

	  clusters:
		- name: signalrhub
		  connect_timeout: 0.25s
		  type: strict_dns
		  lb_policy: round_robin
		  load_assignment:
			cluster_name: signalrhub
			endpoints:
			- lb_endpoints:
			  - endpoint:
				  address:
					socket_address: { address: signalrhub, port_value: 80 }

		- name: signalrhub21
		  connect_timeout: 0.25s
		  type: strict_dns
		  lb_policy: round_robin
		  load_assignment:
			cluster_name: signalrhub21
			endpoints:
			- lb_endpoints:
			  - endpoint:
				  address:
					socket_address: { address: signalrhub21, port_value: 80 }

Any help is really appreciated.

If you need further information you only have to ask.

Thanks in advance.

**Comment by yuval-k** [comment]
how is your domains configued?
i see a difference in the requests:
`':authority', 'hprv.lsetest.gq'` vs `':authority', 'hprv.lsetest.gq:80'`

are the configured domains contain `hprv.lsetest.gq:80` ?

**Comment by LeonSebastianCoimbra** [comment]
> 
> 
> how is your domains configued?
> i see a difference in the requests:
> `':authority', 'hprv.lsetest.gq'` vs `':authority', 'hprv.lsetest.gq:80'`
> 
> are the configured domains contain `hprv.lsetest.gq:80` ?

Yes. I have different third-level domains but they all point to the same ip address.

Plus, there is no difference in this configuration when envoy is invoked using the Windows Form application or the Xamarin application.

Locally, to simulate the "production" situation i have specified equivalent domains inside the "hosts" file (i do not have a local DNS resolver).

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
Yeah, I guess the only remaining question is if we want route matching to ignore x-forwarded-for-matching-port by default.  Confusion of port handling has come up before
https://github.com/envoyproxy/envoy/pull/10960
https://github.com/envoyproxy/envoy/issues/886
and I'm not sure if there's a resolution that'd make everyone happy.

**Comment by LeonSebastianCoimbra** [comment]
One possible solution is to do what they did in Nginx, which is to ignore the port specification. With this choice I think they accepted the fact that there is the possibility (rightly or wrongly) that it is specified and therefore must be managed.

If you decide not to proceed with this option, I suggest highlighting this behavior in the documentation, in some how-to or in another way such that, however, it is clarified how the various cases must be managed.

**Comment by alyssawilk** [comment]
Yeah, I agree that this could be called out better in the docs.
IMO if you're matching host.com:80 in cleartext it should care about the port, but host.com:443 is less clear.  I think changing the default (with super clear comms and the usual guards) might be worthwhile, but I'm curious what @mattklein123 @PiotrSikora @antoniovicente think

Since you were debugging this yourself lately, is there somewhere we could have stuck an attention or warning block that would have been useful?

**Comment by mattklein123** [comment]
@alyssawilk sorry why doesn't https://github.com/envoyproxy/envoy/pull/10960 work for this case?

**Comment by alyssawilk** [comment]
It does, assuming they're Ok stripping as they send upstream, but it sounds like they rewrote their matchers to work as expected already.

My question is should we consider matching that way by default, and if we don't think that's the right thing to do, at least warning in the matcher docs somewhere since this has come up a few times AFIK.

Worst case I'll add it to my FAQ-in-progress  :-P

**Comment by mattklein123** [comment]
> It does, assuming they're Ok stripping as they send upstream, but it sounds like they rewrote their matchers to work as expected already.

I see, OK. I think this is why in the context of that issue I had suggested also adding a mode where we strip for matching only, but not for forwarding (and maybe that would be the default?). Should we have an issue about that?

> My question is should we consider matching that way by default, and if we don't think that's the right thing to do, at least warning in the matcher docs somewhere since this has come up a few times AFIK.

Per above I'm open to that. At minimum I think we should have the option to do this, if not the default. Definitely a FAQ in the interim would be great!
