### ISSUE TITLE
Observability on cluster dns resolving?

### ISSUE THREAD

**Issue by erikbos** [envoyproxy/envoy#11305]
Cluster configuration allows for detailed control over Envoy's behaviour as dns client 👍 But I cannot find any stats on dns resolving performance. Is there a way to get observability on this?

(I've seen AWS/Azure's vpc resolver's rate limiting kick in due to too many request/s with other sw, so I'd love to keep an eye on this)

**Comment by mattklein123** [comment]
What stats are you looking for exactly? There are stats on success/failure/etc.

**Comment by erikbos** [comment]
The stats I am looking for would indeed be number of successful requests, unanswered, etc: anything that can be used to determine dns resolving is not 100% working and hence cluster upstream connectivity is impacted.

In case there is cluster specific resolver configured it would good to have stats on the interaction with that specific resolver. (As nice to have perhaps resolve latency to dig into service time).

Good to hear there are stats on this! I just cannot find them.. I checked:

https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats
/stats 

Could you point me in the right direction? 

(The dns filter does have a stats prefix, but that does not apply to dns resolving for a cluster, right?)

**Comment by mattklein123** [comment]
See `update_attempt`, `update_failure`, etc. IIRC these are incremented for DNS service discovery. Doc updates appreciated.

**Comment by erikbos** [comment]
Thx for the pointer, indeed: according to logical_dns_cluster.cc: `update_attempt`, `update_success` and `update_failure` are the ones for DNS resolution attempts. Will submit doc fix.
