### ISSUE TITLE
Allow envoy to run as non-root user in docker container

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#11311]
Currently envoy runs as `root` in the docker container.

Arguably, its more secure to run as non-root.

Allowing the user to be configurable also allows envoy to access/listen to sockets as a particular user or group.

I can PR if its helpful.

I have an example implementation here https://github.com/phlax/envoy

**Comment by mattklein123** [comment]
I thought there was already in issue on this but I can't find it. PRs appreciated.

**Comment by phlax** [comment]
@mattklein123 could you point me to where a PR would go ? i was working from the docker image history and the image on hub

**Comment by mattklein123** [comment]
Presumably the docker files here: https://github.com/envoyproxy/envoy/tree/master/ci. cc @lizan
