### ISSUE TITLE
Custom error html page

### ISSUE THREAD

**Issue by featureed** [envoyproxy/envoy#11313]
Hi. 

Is it possible to replace 50X status replies with some custom html page + 200 OK, like nginx or haproxy do with error_page directive? (they use internal redirect for that, afaiu)

Did some search and found that https://github.com/envoyproxy/envoy/pull/11007 is already merged, but looks like this is for local pages only and not for html?

**Comment by mattklein123** [comment]
I will mark this help wanted. I think this is a fairly simple change to allow the content-type to be set as part of the reply mapper. @qiwzhang wdyt?

**Comment by fttyX** [comment]
I'd agree even with the option to leave content-type not touched by envoy, if that makes sense (in our case backend sets this header).

**Comment by SolovyevAndrei** [comment]
Hello

We need such feature too. Want to show beatiful error page to customers, when something is wrong with our backends.
It was quite easy with error_page in nginx. But no such possibility in envoy.

**Comment by deveshkandpal24121990** [comment]
@mattklein123 - I would like to work on this issue. Can you please assign this to me ?

**Comment by dio** [comment]
@mattklein123 for modifying proxied response (with non-2xx status), do you think it makes sense to have an `error_page` filter? (or to extend the local reply to work in response path; in Nginx, we need to turn on `proxy_intercept_errors` to let non-2xx proxied response to be handled by the proxy's `error_page` config). 

I can see it can also be implemented in Lua (with some thinking on how to not complicate the "state management" there).

**Comment by mattklein123** [comment]
> @mattklein123 for modifying proxied response (with non-2xx status), do you think it makes sense to have an error_page filter? (or to extend the local reply to work in response path; in Nginx, we need to turn on proxy_intercept_errors to let non-2xx proxied response to be handled by the proxy's error_page config).

Sorry what is the use case here? To intercept upstream responses and translate them? This seems out of scope for local reply mapping?

**Comment by dio** [comment]
@mattklein123 True, sorry that I wrongly submitted the comment here 😅. Seems like I wanted to reply on this issue: https://github.com/envoyproxy/envoy/issues/12883.
