### ISSUE TITLE
version converter + protobuf::Struct may break the convention of MessageUtil::hash()

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#11312]
Protobuf has a strange behavior that MapEntry type message copy constructor doesn't copy unknown fields. See reported [istio bug here](https://github.com/istio/istio/issues/23858#issuecomment-632249037), and the [root causing code](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/map_entry_lite.h#L315-L328)
It means a copied message may not has the exact hash code under MessageUtil::hash()

In envoy, [version converter](https://github.com/envoyproxy/envoy/blob/master/source/common/config/version_converter.cc#L66) annotates original type using unknown field on MapEntry and hit this protobuf bug/feature.

I can fix the `hash(message)` in filter chain manager by stripping `original type` prior to hash/lookup.

Meanwhile, @htuch could we skip annotating `XXMapEntry` typed message? `XXMapEntry` is a protobuf internal type. Message should be downgraded regardless the `XXMapEntry` original type.

**Comment by mattklein123** [comment]
cc @htuch @lizan

**Comment by htuch** [comment]
Yeah, just stripping the unknown fields in `MessageUtil::hash` seems the simplest way to fix this. Is there some concern that if we continue to annotate map entries that something else will break?

**Comment by lizan** [comment]
> Yeah, just stripping the unknown fields in `MessageUtil::hash` seems the simplest way to fix this. Is there some concern that if we continue to annotate map entries that something else will break?

SGTM, just set `SetHideUnknownFields` true in hash method would be the simplest way.

**Comment by lambdai** [comment]
Great! `SetHideUnknownFields` in MessageUtil::hash fixed my test case. Thanks!

**Comment by lambdai** [comment]
> Is there some concern that if we continue to annotate map entries that something else will break?

No further breakage AFAIK. I don’t know what I don't know though
