### ISSUE TITLE
Question about max_pending_requests and max_connections in circuit breaker

### ISSUE THREAD

**Issue by yukunlin** [envoyproxy/envoy#11326]
From https://github.com/envoyproxy/envoy/blob/6aee60364ef1bb539e19abc68d1e6cbe93c41512/source/common/http/conn_pool_base.cc#L114_L138, when there `ready_clients_` is empty, the following happens: 

* a check against `max_pending_requests` when there `ready_clients_` is empty
* the pending requests counter is incremented while a new connection is being created

Envoy does not seem to pre-intialized `ready_clients_`. Does this mean if `max_pending_requests` is smaller than `max_connections`, requests could be rejected due to the number of pending requests hitting the `max_pending_requests` limit,  even if the number of connections to upstream is less than `max_connections`?

**Comment by ggreenway** [comment]
> Does this mean if `max_pending_requests` is smaller than `max_connections`, requests could be rejected due to the number of pending requests hitting the `max_pending_requests` limit, even if the number of connections to upstream is less than `max_connections`?

Yes, I think that's correct, and is something that could happen after a cold start. I wouldn't expect it to happen once a steady-state has been reached.

**Comment by mattklein123** [comment]
Yes, that's correct with the current impl.

**Comment by yukunlin** [comment]
Thanks for the clarification. Regarding:

> I wouldn't expect it to happen once a steady-state has been reached.

Will the created `ActiveClient` instances always be around and moved back to `ready_clients_` after being used? Or could they be also closed (for example, in https://github.com/envoyproxy/envoy/blob/6aee60364ef1bb539e19abc68d1e6cbe93c41512/source/common/http/conn_pool_base.cc#L99-L103 perhaps?)

If the `ActiveClient` being created could be closed after steady-state, could that lead to a similar type of problem like the cold start scenario (requests being rejected due to `max_pending_requests` being hit before the `max_connections` limit is hit)?

**Comment by mattklein123** [comment]
Yes it's possible you could get back into that situation due to idle timeouts or something else.

**Comment by yukunlin** [comment]
Thanks, this clears things up.
