### ISSUE TITLE
gRPC data.accesslog.v2.AccessLogCommon: How to calculate time spent trying to connect to an upstream host?

### ISSUE THREAD

**Issue by v1b1** [envoyproxy/envoy#11322]
I'm trying to understand the various timings available in an HTTP access log entry for the purposes of recording (and providing evidence) where time is spent in Envoy vs. network wire time vs. upstream host handling time.

I noticed when logging transaction timings that the following fields are not set in the event of an upstream timeout:

`time_to_first_upstream_tx_byte`
`time_to_first_upstream_rx_byte`
`time_to_last_upstream_rx_byte`

It makes sense because Envoy is unable to forward a request upstream (no first upstream byte can be sent nor any were received), however I'm not sure how to calculate the time that Envoy spent exercising its filter logic (kernel socket buffer caveats aside) vs. the time spent trying to connect to an (un)healthy upstream host.

1) Does `time_to_first_upstream_tx_byte` include the time spent trying to send the first byte to a slow upstream host, or a host that failed and so another host was selected?

2) Is it possible to calculate just Envoy's processing/filtering time for requests and responses vs. network and upstream behaviour?

**Comment by dio** [comment]
@hanahmily @wu-sheng to speak from experience. 🙂

**Comment by v1b1** [comment]
Anyone?

**Comment by wu-sheng** [comment]
Hi, @dio @v1b1, sorry for the late. I am not watching the repo always.

> I noticed when logging transaction timings that the following fields are not set in the event of an upstream timeout:

When a timeout happens, no successful handshake. So, most likely, Envoy can't have the strategy to assign these values. 

Your question context is making me feel, you want to measure the latency cataloged by the envoy, network, and upstream service. This can't be resolved by envoy itself. The topology analysis based on distribute tracing typically fixes this issue.
Such as in [Apache SkyWalking](https://github.com/apache/skywalking)

We statistic metrics at the Server-side and Client-side, the difference(such as avg response time) between client and server-side metrics are the cost of the network. And server-side metrics is upstream service performance behaviour.
|Server|Client|
|------|-----|
|![image](https://user-images.githubusercontent.com/5441976/89418295-74871c80-d762-11ea-89af-82f4279e3059.png) | ![image](https://user-images.githubusercontent.com/5441976/89418316-7c46c100-d762-11ea-9ea8-7f6f0ae772c0.png)|

**Comment by v1b1** [comment]
Thanks @wu-sheng

I guess that means there's no way within Envoy to timestamp the moment before an HTTP connection is attempted/opened, but after an upstream host is selected?

**Comment by wu-sheng** [comment]
From my understanding, envoy can't.

> but after an upstream host is selected?

What do you mean selected? Do you mean based on a load balance strategy? If so, I don't think it is related to the metrics.
