### ISSUE TITLE
Extract TLVs from Proxy Protocol v2 and save it in dynamic metadata to be consumed by other filters

### ISSUE THREAD

**Issue by songhu** [envoyproxy/envoy#11336]
Issue Template

Title: Extract TLVs from Proxy Protocol v2 and save it in dynamic metadata to be consumed by other filters.

Description:

In Proxy Protocol v2 important information can be arranged in Type-Length-Value (TLV) format [1] and placed in the Proxy Protocol header. Information such as VPC endpoint [2] in TLVs could be useful by other filters.

Currently TLVs are read and discarded in the Proxy Protocol filter [3]. I would like to extend the Proxy Protocol Listener filter to extract TLVs of interest and save them as metadata which can be consumed by other filters.

My questions are:

1. Is there any on-going or planned work on the same issue?
2. It seems "setDynamicMetadata" is not available yet in Proxy Protocol filter, likely because the connection has not been created yet. Wondering is there any guideline and suggestions on how to bridge that gap?

Many thanks in advance!
Song   

[optional Relevant Links:]

[1] https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
[2] https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol
[3] https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc#L234-L256

**Comment by lizan** [comment]
Sounds reasonable. I'm not aware of any ongoing or planned work on the same issue. re 2. you might have to change the connection handling part to allow listener filters to emit metadata.

**Comment by songhu** [comment]
Hi lizan,
Thanks for the suggestion. I will look into the connection handling. I should come back with a pull request for review soon.
Have a great weekend.
Song
