### ISSUE TITLE
http: allow matching ignoring ports

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#11346]
See discussion on https://github.com/envoyproxy/envoy/issues/11294
and some on https://github.com/envoyproxy/envoy/pull/10960/files

I think if added a matcher for host.com I would expect host.com:80 to match for HTTP.  Arguably sending host.com:443 on port 80 shouldn't match, but maybe it could be a config option?

cc @mattklein123 @antoniovicente @snowp @PiotrSikora

**Comment by mattklein123** [comment]
+1 I think we should have an option for this.

**Comment by derekargueta** [comment]
Would this be configured at the Route level?

**Comment by alyssawilk** [comment]
No strong opinions.   I think the existing port stripping option is probably the easiest for most folks as it both fixes the local route matching problem and protects upstream from hitting the same class of issues.
Do you folks have an interest in preserving the original port but matching sans port, or was the stripping not on your radar?  Maybe we could something similar to https://github.com/envoyproxy/envoy/pull/15975 where we extend the port stripping option to allow strip-and-readd for all requests, not just CONNECT

**Comment by derekargueta** [comment]
oh wow I wasn't aware of `strip_matching_host_port` and `strip_any_host_port`, looks like these solve my problem. Should this ticket be closed?

**Comment by alyssawilk** [comment]
Sure, I guess we can close for now and reopen if folks want to match without altering the host header :-)
