### ISSUE TITLE
Vary header is not always set for compressible responses

### ISSUE THREAD

**Issue by kanongil** [envoyproxy/envoy#11343]
*Description*:

When the compressor or gzip filter is enabled, the `vary: accept-encoding` header is only set when the response is actually compressed. This can cause unexpected behaviour in caching proxies, depending on the order of the request.

*Repro steps*:

With a regular caching proxy in front of envoy, and a cacheable & compressible response:

1. `curl host/file.txt -v --compressed` - Compressed response is returned, expected.
1. `curl host/file.txt -v` - Uncompressed response is returned, expected.

Clear proxy cache, and do the reverse:

1. `curl host/file.txt -v` - Uncompressed response is returned, expected.
1. `curl host/file.txt -v --compressed` - Uncompressed response is returned, **unexpected**!

*How to fix:*

Envoy needs to always set `vary: accept-encoding` for any compressible responses. Otherwise, if an uncompressed response is cached, the proxy won't know to fetch a new incoming request with `Accept-Encoding: gzip` from upstream.

**Comment by mattklein123** [comment]
cc @junr03 @rojkov can you triage?

**Comment by junr03** [comment]
> Envoy needs to always set `vary: accept-encoding` for any compressible responses.

IMO what we need to define is what constitutes a "compressible" response. Are you proposing that the only requirement is that the compressor filter is enabled?

**Comment by rojkov** [comment]
I think it's a valid point. `Vary` should reflect the headers the filter took into consideration when serving a request even if compression is skipped.

Though the simple fact that the filter is enabled is not enough. Before setting `Vary` we also need to know if the filter is applicable to the request (e.g. consult `Content-Type`). And if not then the header should not be set.

**Comment by kanongil** [comment]
The current logic is here:

https://github.com/envoyproxy/envoy/blob/86caf439d6cae2c8173b19fd4fdc95361565a72d/source/extensions/filters/http/common/compressor/compressor.cc#L103-L106

Vary should apply to the responses that match the request invariant parts. A safe test would probably be:

```c
bool isCompressible = (isMinimumContentLength(headers) &&
    isContentTypeAllowed(headers) &&
    !hasCacheControlNoTransform(headers) &&
    isEtagAllowed(headers) &&
    !headers.ContentEncoding());
```

**Comment by rojkov** [comment]
Looks reasonable. I'd also AND'ed with `config_->enabled()` though.

@kanongil Do you mind submitting a patch?

**Comment by kanongil** [comment]
Sure, I'll see what I can do.

**Comment by rojkov** [comment]
@kanongil Are you still planning to submit a patch?

I've got some time to spend on community work, so I could submit the patch myself if you are busy.

**Comment by rojkov** [comment]
I've reproduced the issue locally (I'm using Polipo as a caching proxy) and I see the stats are acting up indeed due to short-circuiting logic.

If there's no objection I'll check what's wrong with the logic tomorrow.
