### ISSUE TITLE
Windows: Support setting permissions on Unix domain sockets

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#11354]
In the Envoy API for Pipe addresses, we explicitly support setting the file mode on Unix domain socket files, see: https://github.com/envoyproxy/envoy/blob/ece1b6aa21c940477d3587848bad0c153cf05987/api/envoy/config/core/v3/address.proto#L30

This file mode pattern does not translate well to Windows, to get similar granular permission control we would need to leverage Windows ACLs.

This issue is for discussion around this topic and to consider different options, some that come to mind immediately:
- As with abstract Unix domain sockets, simply do not support setting a file mode
- Attempt to translate the file mode to something that is passable on Windows
  - See parts of https://github.com/envoyproxy/envoy/pull/11334 as an attempt
  - See https://devblogs.microsoft.com/commandline/windowswsl-interop-with-af_unix/ for an interesting case study between Unix domain sockets on WSL + Windows
- Revamp the mode field of the API to transition to a more portable representation

**Comment by sunjayBhatia** [comment]
cc @wrowe @davinci26 @nigriMSFT

**Comment by sunjayBhatia** [comment]
The test that demonstrates this most succinctly is `//test/common/network:address_impl_test` -> `PipeInstanceTest.BasicPermission`

We have an underlying issue that we are not able to even `stat` the socket file, once that is solved, the file mode itself is the bigger question

**Comment by sunjayBhatia** [comment]
We are considering disabling that individual test for now on Windows before this issue is resolved

**Comment by sunjayBhatia** [comment]
related general issue: https://github.com/envoyproxy/envoy/issues/9571

**Comment by davinci26** [comment]
Is setting granular file permissions are requirement for a high priority scenario or is it a good to have? Is there a way to see what the customer demand for this is?

What I am thinking is that we could have this API in Windows with the current limitation. Basically only setting the socket read-only or write and write. And then offer an additional module just for win32 ACL. This is similar to the approach Python is taking.

Is there a way we could add win32 ACL support as plugin?

**Comment by sunjayBhatia** [comment]
further discussion: https://envoyproxy.slack.com/archives/CNAK09BSB/p1590785118071500

We are seeing differences in behavior about `stat()` on a unix domain socket

**Comment by sunjayBhatia** [comment]
as per @wrowe catching this: https://github.com/golang/go/issues/33357#issuecomment-517246291

**Comment by wrowe** [comment]
I'd suggest this issue remains unresolved and relevant
