### ISSUE TITLE
Upstream HTTP/2 connection limits

### ISSUE THREAD

**Issue by praneethvarma** [envoyproxy/envoy#11355]
I have been experimenting with Envoy recently. I am trying to understand the following. Thanks in advance for the help - 

I see that the common least request implementation uses the PnC method where n is configurable (randomly choose n hosts and pick the one with least among them). Assuming there is no zone aware routing or custom weights, statistically, traffic would be spread evenly. This means that there will be connections created for most hosts and will be kept alive in the respective pools (one per host for HTTP2 and multiple for HTTP1). I am trying to understand if there are any dynamic limitations for how many such connections can be kept alive (apart form the circuit breaker limits). Following is the behaviour I am observing -

**Setup** : I have about 400 hosts in a cluster backend. Requests to Envoy are ~30 rps(these requests are time taking ones). Envoy worker count - 4. HTTP/2 (incoming connections to the listener are HTTP1. Outgoing to cluster hosts are HTTP2. I am interested in upstream connections)

**Observation** : Envoy creates new connections (`upstream_cx_active` stat) as the requests come in and almost immediately, there is an uptick in the number of closed connection metric (`upstream_cx_close_notify`). Relevant circuit breaker settings for limits on cluster wide connections are - `max_connection_pools` and `max_connections`, both of which in my case are not configured, thereby not limiting them at all. So, this must not be the reason for closing connections almost immediately. A few seconds after the incoming traffic is completely cut off, the rate of of closing connections has come down to 0 leaving about 160 connections intact (active connections) for about an hour (I believe this is TCP connection idle timeout). So, all the connections that were created beyond the 160 mark were being actively closed. I am not sure if I am misconfiguring some setting to cause this. I think, the way it is, it would be very inefficient at high request rate to keep closing connections immediately this way. Is there some other setting (a logic that dynamically determines the total number of outstanding connections. I don't have a correlation to 160 anywhere else, so I am guessing this could be dynamically derived from other configurations.).

**Follow up** : Is there any affinity in the host selection process (I didn't find any such reference and I can see that it could cause the traffic skewed to a certain set of cluster hosts. Maybe, ends up behaving similarly to a tcp proxy?) to pick hosts that already have connections available in their individual pools ? I assume not. In this case, is it fair to assume that for scenarios where the number of available backends is high and the incoming connections that need to routed are sparse, it is likely that we have a high number connections per worker where some/many could be under/not utilized?

**Comment by lizan** [comment]
A couple possible reason:
- `max_connections` defaults to 1024 if it is not configured.
- an uptick of `upstream_cx_close_notify` means your upstream is sending GOAWAY, if the protocol is HTTP2, or `connection: close` in case of HTTP1.

**Comment by praneethvarma** [comment]
Thanks @lizan . Ya, the max connections that it reached was under 500. I will look into what is happening on the upstream. The upstream is another Envoy instance as well. Maybe there is a limit on the listener there. I will post my findings here soon.

**Comment by praneethvarma** [comment]
@lizan , I checked to see if I could find anything with the upstream hosts. Some observations - 

1. Given this is HTTP/2 , there won't be more than one connection per host. The active connections stabilize at 160 upon repeating this experiment multiple time, suggesting that it is unlikely for it to be caused by something on the upstream hosts. Would you agree?
2. In our setup, the `upstream_cx_close_notify` and `upstream_cx_destroy_local` go hand in hand during the entire time this happens. Also, `upstream_cx_destroy_remote` stays at 0 during this time. I am not entirely sure what `upstream_cx_destroy_local` accounts for (for now, assuming that the connection close is initiated locally).
