### ISSUE TITLE
eds: improve performance of updates

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#11362]
Looking at performance profiles, there are a number of places we can optimize EDS updates:

* We are burning 30-50% of time in version conversion. We can follow https://github.com/envoyproxy/envoy/issues/10875 to improve this.

* There is a lot of highly redundant computation happening as we are doing multiple `anyConvert`s, with proto deserialization overhead, version conversions, etc. e.g. when we access resource name, this does a full conversion. This will also apply to other resource types. Ideally we have a cheaper way to get at resource name. Also, message validation has to recover original type; we can possibly supply it directly.

I think EDS update performance can be improve somewhere in the 50-70% range if ^^ is done right.

**Comment by htuch** [comment]
FTR https://github.com/envoyproxy/envoy/pull/10982 was a step towards mitigating this overhead, this issue tracks the long-term fix. CC @pgenera @jmarantz

**Comment by zyfjeff** [comment]
@htuch The results of your performance analysis are consistent with the results of my previous performance analysis of EDS. In addition, I also found that the comparison of Metadata is also a very CPU-intensive point.

**Comment by mattklein123** [comment]
cc @lita @jessicayuen

**Comment by lita** [comment]
Just so the community is aware, we are seeing performance issues at Lyft also. Going to try sending v3 data for EDS to see if that helps alleviate some of the CPU pressure.

**Comment by htuch** [comment]
I think for folks who switch to v3, there probably isn't a big regression compared to before, but there might be a small amount of room to improve, see https://github.com/envoyproxy/envoy/issues/10875#issuecomment-636858298.

The most attractive low hanging fruit here is to avoid running the xDS resource through `anyConvert` twice, once for the resource name (from `GrpcMuxImpl`) and again by the xDS specific ingestion code. I'm going to work on this a bit this week, I think it's an optimization that would be been beneficial even before we started to do version conversion.

**Comment by htuch** [comment]
One other thing to note is that LEDS will also be one way to address this overhead (other than the initial update), see https://github.com/envoyproxy/envoy/issues/10373. Backend subsetting is another option.

**Comment by htuch** [comment]
There's also another optimization here that the discussion today from @mattklein123 on SotW/delta handling made me think about. If the `GrpcMuxImpl` can do state tracking of versions for all resources, we can skip delivering updates to the EDS subsystem (for example) when there is no change. Arguably, management servers should do this already, but this is a potential optimization to explore if there is a need to do this client side.

**Comment by htuch** [comment]
Tagging for collection in https://github.com/envoyproxy/envoy/issues/10943

**Comment by htuch** [comment]
I think as a result of a combination of the improvements from #11442 and https://github.com/envoyproxy/envoy/issues/10875#issuecomment-661101877, we can close this one out. Please reopen if https://github.com/envoyproxy/envoy/issues/10875#issuecomment-661101877 and HEAD Envoy is not sufficient.
