### ISSUE TITLE
Load balancing does not work with docker-compose links

### ISSUE THREAD

**Issue by jlong4096** [envoyproxy/envoy#11383]
*Load balancing does not work with docker-compose links*

*Description*:
If I run the front-proxy sandbox, but link front-envoy to service1, the requests are not load balanced.  Is this intentional?  Known?  I couldn't find any documentation or explanation.

*Repro steps*:
Patch:
[links.patch.txt](https://github.com/envoyproxy/envoy/files/4711931/links.patch.txt)

Output:
[logs.txt](https://github.com/envoyproxy/envoy/files/4711934/logs.txt)

**Comment by mk46** [comment]
@jlong4096 Please share docker-compose file.

**Comment by jlong4096** [comment]
See attached.  `examples/front-proxy/docker-compose.yaml`

[docker-compose.yaml.txt](https://github.com/envoyproxy/envoy/files/4732949/docker-compose.yaml.txt)

**Comment by mk46** [comment]
@jlong4096 Here networks are used to resolve other containers by its name, so no need to use the links. If you want front-envoy will start after service1 then use depends_on instead of links.
