### ISSUE TITLE
Request with Transfer-Encoding: chunked and Content-Length is valid per RFC, but rejected with HPE_UNEXPECTED_CONTENT_LENGTH

### ISSUE THREAD

**Issue by veshij** [envoyproxy/envoy#11398]
Duplicating https://github.com/nodejs/http-parser/issues/517 to envoy.
Prior to making changes to http-parser library wanted to confirm that proposed change looks reasonable to envoy maintainers.

Current implementation of nodejs/http-parser rejects requests with Transfer-Encoding: chunked and Content-Length headers with HPE_UNEXPECTED_CONTENT_LENGTH.
https://github.com/nodejs/http-parser/blob/master/http_parser.c#L1804-L1815

But per https://tools.ietf.org/html/rfc7230#section-3.3.3 that's a valid http request, Content-Length must be ignored:

       If a message is received with both a Transfer-Encoding and a
       Content-Length header field, the Transfer-Encoding overrides the
       Content-Length.

**Comment by mattklein123** [comment]
cc @alyssawilk @PiotrSikora @antoniovicente can you advise?

**Comment by alyssawilk** [comment]
If a message is received with both a Transfer-Encoding and a
       Content-Length header field, the Transfer-Encoding overrides the
       Content-Length.  Such a message might indicate an attempt to
       perform request smuggling (Section 9.5) or response splitting
       (Section 9.4) and ought to be handled as an error.  A sender MUST
       remove the received Content-Length field prior to forwarding such
       a message downstream.

We're handling it as an error.  As the spec says (and experience indicates) it's a major smuggling vector to allow both.  If you can convince the http_parser folks to allow it I'd say we could add a configuration option to allow it in Envoy but I'd prefer we default off.

**Comment by veshij** [comment]
I'm thinking of this approach:
* opt-in in http-parser to allow parsing such requests and return both headers if enabled
* verify envoy rejects such requests and enable http-parser opt-in by default in envoy.
* add opt-in to envoy to allow serving such requests.

**Comment by antoniovicente** [comment]
Envoy has tests to verify behavior when both transfer-encoding and content-length are present.  Moving the code that rejects this kind of request from the parser to Envoy code seems fine.
 https://github.com/envoyproxy/envoy/blob/702a3648273af44408e93ab5e584e2b7e5261f6b/test/integration/integration_test.cc#L377
