### ISSUE TITLE
Traffic control based on previous response time for http request 

### ISSUE THREAD

**Issue by ryanlyy** [envoyproxy/envoy#11417]
for envoy load balance, whatever it is round robin, hash etc, there is no traffic control policy which does load balance based response time of previous http request. As you know, for one upstream endpoint, if it always has delay for its response comparing with other upstream endpionts. that means that upstream may be in not good status(for example: high CPU, high network bandwidth/latency etc) but it is still healthy. then envoy shall can change its weight and forward less percent traffic to that endpoint to make its traffic control real balanced.

Thanks,
Ryan

**Comment by mattklein123** [comment]
Correct this is not implemented currently, though in practical terms least request LB does a good job of handling this.

**Comment by ryanlyy** [comment]
@mattklein123 thanks a lot for your response. Least Request means to chose upstream endpoint which has least http request but it does not mean remote is busy and response is slow if it does not count on response time. And in long time running, the upstream requests are average. Looking at the statistics, there is count on response, so envoy shall be can count response time and when chose upstream it can count on it whatever LB is (hash, rr, maglev etc). any idea?

Thanks,
Ryan
