### ISSUE TITLE
Traffic Control based upstream CPU and Memory etc measurement

### ISSUE THREAD

**Issue by ryanlyy** [envoyproxy/envoy#11416]
Looking at currently traffic policy (weighted) round robin, hash etc load balance, they all does not count on upstream CPU utilization. in  those kind of load balance, if upstream endpoint CPU is high, envoy can still forward traffic to that upstream w/o difference with others upstream endpoints. then it is really not load balanced. So can envoy support traffic control policy based on upstream CPU utilization?

Thanks,
Ryan

**Comment by mattklein123** [comment]
Not currently, see https://github.com/envoyproxy/envoy/issues/6614 which would be a good way of accomplishing this.

**Comment by ryanlyy** [comment]
@mattklein123 that is great. what is the plan to deliver this feature?

Thanks,
Ryan

**Comment by ryanlyy** [comment]
Hello, any comments?

Thanks,
Ryan
