### ISSUE TITLE
Feature Request: Disable Nagle's algorithm

### ISSUE THREAD

**Issue by OneFirefly** [envoyproxy/envoy#11434]
It seems like there is currently no way to disable Nagle's algorithm which is relevant for applications that require low latency. To my knowledge, this algorithm is by default enabled for TCP connections.

Nginx also has the feature (tcp_nodelay)

Are there any plans to implement this?

**Comment by mattklein123** [comment]
TCP_NODELAY is set on all proxy connections by default.

**Comment by OneFirefly** [comment]
Thank you
