### ISSUE TITLE
Should encodeHeaders be called if decodeHeaders is not called in HTTP Filters?

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#11447]
While working on WebAssembly filters we discovered that it is possible for encodeHeaders to be called on a HTTP filter even if decodeHeadershas never been called.  This occurs if there is an error while parsing the headers or at a higher level resulting in sendLocalReply() being called without decodeHeaders.  

Do we want this behavior?  The filter in question has no context for the encodeHeaders call and was not involved in the decision to sendLocalReply().  We could just not call the filter in this case.

**Comment by mattklein123** [comment]
> Do we want this behavior? The filter in question has no context for the encodeHeaders call and was not involved in the decision to sendLocalReply(). We could just not call the filter in this case.

At least for the C++ filter stack, this is the way "it has always been." I think here is utility in this in some cases like for example the local reply case you outlined. I do think this behavior could be optional but I think it would need to be config driven somehow on a per filter basis. cc @alyssawilk

**Comment by alyssawilk** [comment]
yeah, there's a TODO in the HCM (ConnectionManagerImpl::ActiveStream::sendLocalReply) to only run the response through filters which saw the request, but at this point I'm not sure that we could just convert on over - I agree it's something we'd need to folks to configure.
