### ISSUE TITLE
Question about trusted_ca parameter in validation_context 

### ISSUE THREAD

**Issue by smart-duck** [envoyproxy/envoy#11474]
Can you confirm me that the full certificate chain is required (from Intermediate to root CA) and that using a file with only the intermediate CA will failed ?

Thank you

**Comment by davidledev** [comment]
I have the same problem using PKI with 3 levels (root, intermediate and end-entity). It works fine when i use the root CA in "trusted_ca" part. But i obtain error with intermediate CA in "trusted_ca" part. I obtain the following error with curl. It seems it cannot check the certificate chain.

`
curl -vvvv -k --cert certificate.pem --key privkey.key  https://localhost:1443/tto
....
 TLSv1.3 (IN), TLS Unknown, Unknown (21):
* TLSv1.3 (IN), TLS alert, Server hello (2):
* OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0
* stopped the pause stream!
* Closing connection 0
curl: (56) OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0
`

Here is my listener configuration:
`
static_resources:
    listeners:
    - name: listener_k8s
      address:
        socket_address: { address: 0.0.0.0, port_value: 1443 }
      filter_chains:
      - filters:              
        - name: envoy.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            stat_prefix: ingress_http
            codec_type: AUTO
            route_config:
              name: route
              virtual_hosts:
              - name: service
                domains: ["*"]
                routes:
                - match: { prefix: "/" }  
                  route:
                    cluster: service              
            http_filters:
            - name: envoy.router
        tls_context:
          require_client_certificate: true
          common_tls_context:
            validation_context:
              # CA used to generate client certificate
              trusted_ca:        
                filename: "/etc/envoy/certs/subca.pem"
            tls_certificates:
              - certificate_chain: { filename: "/etc/envoy/certs/serv.pem" }
                private_key: { filename: "/etc/envoy/certs/privkey_serv.key" }


`
