### ISSUE TITLE
Suggested new feature: modifiable User-Agent for HTTP HealthChecks

### ISSUE THREAD

**Issue by bvandewalle** [envoyproxy/envoy#11492]
As we are using Envoy together with Active HTTP HealthChecks, a lot of our upstream services are wondering about those HealthChecks in their logs.
Ideally, I would like to modify the user-agent to add some information to the healthCheck. 

The HC http user-agent is hardcoded in Envoy to `Envoy/HC`:
https://github.com/envoyproxy/envoy/blob/master/source/common/http/headers.h#L261

I'm suggesting adding a flag to the healthCheck config to optionally allow the user to define the HC user-agent

**Comment by snowp** [comment]
Have you looked at using `request_headers_to_add` to set the user-agent? From a brief look at the code I imagine a `user-agent` header added there with `append=false` would overwrite the default

**Comment by bvandewalle** [comment]
Thanks for the suggestion @snowp , let me try that. I will report here

**Comment by bvandewalle** [comment]
This can be closed, for anyone else, I can confirm that @snowp  suggestion works.
