### ISSUE TITLE
release/v1.14 fails on Windows due to undeclared SO_DOMAIN

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#11519]
`release/v1.14` started failing on Windows on 6/7 (without any code changes), most likely due to changes in the AZP's Windows CI image (reorganized `include`, etc.):
```
source/common/network/utility.cc(354): error C2065: 'SO_DOMAIN': undeclared identifier
```
It still passes on `master`, and there are no changes between `release/v1.14` and `master` in `include/envoy/common/platform.h`, so I'm not sure where else to look, or how to narrow this down without access to Windows machine.

@lizan @mattklein123 any ideas on what might be the cause or who could help fix it?

**Comment by mattklein123** [comment]
cc @wrowe

**Comment by PiotrSikora** [comment]
@wrowe but `//source/exe:envoy-static` was building fine on Windows on 1.14 until 6/6:
https://dev.azure.com/cncf/envoy/_build/results?buildId=41469&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3
(from #11470)

and it started failing on 6/7 without any code changes:
https://dev.azure.com/cncf/envoy/_build/results?buildId=41553&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3
(from #11491)

**Comment by sunjayBhatia** [comment]
@PiotrSikora I think you are right, it is possible changes to the Windows AZP image have affected this, I haven't been able to see anything specific from this history: https://github.com/actions/virtual-environments/commits/master/images/win

To maintain a consistent build environment we may want to backport the changes to Windows CI that run it in Docker so we are not at the whims of AZP images

But also to @wrowe's point, we don't expect the 1.14 release branch to work on Windows so another option may be to remove Windows CI from current LTS release branches altogether.

**Comment by PiotrSikora** [comment]
Sounds good, let's just disable Windows CI on v1.14 branch. See: #11525.
