### ISSUE TITLE
Question: How to redirect request to second server on first server unavailability

### ISSUE THREAD

**Issue by stepupit-work** [envoyproxy/envoy#11533]
Hi Team,
My requirement is that hit first server for request if that server is unavailable then redirect same request on another server (back-up server).

Can you provide if this functionality is supported in envoy?

**Comment by stepupit-work** [comment]
@mk46 Thanks for your reply.

Can you share an example.

**Comment by mk46** [comment]
In https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy, at step 4.
Below links will help you to get more details. 
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/overview
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers
