### ISSUE TITLE
Misuse of runtime_fraction and is there a better alternative?

### ISSUE THREAD

**Issue by zhishi** [envoyproxy/envoy#11560]
_Description:_

We encountered a traffic problem recently which is caused by `runtime_fraction`. Basically We want to split traffic among three endpoints groups, which are from same upstream cluster. The endpoints group is identified by endpoint metadata. For example, we want to split traffic as: `"group1": 5%, "group2": 5%, "group3": 90%`. So we use three routes with different matching rules, which use `runtime_fraction` to decide the percentage like below:
```
  {
    "match": {
      "prefix": "/",
      "runtime_fraction": {
        "default_value": {
          "denominator": "HUNDRED",
          "numerator": 5
        },
        "runtime_key": "key1"
      }
    },
    "route": {
      "cluster": "upstream",
      "metadata_match": {
        "filter_metadata": {
          "envoy.lb": {
            "stage": "group1"
          }
        }
      }
    }
  },
  {
    "match": {
      "prefix": "/",
      "runtime_fraction": {
        "default_value": {
          "denominator": "HUNDRED",
          "numerator": 5
        },
        "runtime_key": "key2"
      }
    },
    "route": {
      "cluster": "upstream",
      "metadata_match": {
        "filter_metadata": {
          "envoy.lb": {
            "stage": "group2"
          }
        }
      }
    }
  },
  {
    "match": {
      "prefix": "/"
    },
    "route": {
      "cluster": "upstream",
      "metadata_match": {
        "filter_metadata": {
          "envoy.lb": {
            "stage": "group3"
          }
        }
      }
    }
  }
```
It looks natural right? But the reality is only group1 get 5% traffic and group3 get all other 95% traffic, so there is 0% traffic to group2. After investigating tracing logs and code base, we found the reason: the random number used by `runtime_fraction` is only generated once through the whole filter chain (https://github.com/envoyproxy/envoy/pull/1878). So to make it working correctly, you must add previous percent into each route, for example:
  First route: 5, to get 5 percent traffic
  Second route: 10 (5 + previous percent), to get 5 percent traffic
  Third route: 20 (10 + previous precent), to get 10 percent traffic
  Last route, to get left traffics

Since it's easy to make mistake like this, we think it's better to add more document and comments for `runtime_fraction`. Also we want to know is this a misuse of `runtime_fraction`, which may be only designed for traffic split between two groups? Because one side effect of this problem is we can't use runtime configuration to change the percentage easily, since it may mess up the adding in each route.

And is there a better alternative than `runtime_fraction` to handle this scenario?

cc @rgs1 @fishcakez

**Comment by mattklein123** [comment]
I think in general we want people to use weighted clusters for this, but I'm not sure if this works with the subset LB which I think you are using? cc @snowp @zuercher

**Comment by snowp** [comment]
Yeah weighted cluster seems like a better option here, it seems like it has support for specifying `metadata_match` per cluster so it should work with the subset lb

**Comment by zhishi** [comment]
For weighted cluster if the selected cluster has no healthy endpoints, will it fallback to another cluster? That's one reason we use `runtime_fraction` matching rule.

**Comment by snowp** [comment]
It does not, but I don't see how `runtime_fraction` would either - they both operate at the route selection level which has no knowledge of cluster health

**Comment by fishcakez** [comment]
> It does not, but I don't see how `runtime_fraction` would either - they both operate at the route selection level which has no knowledge of cluster health

When there are multiple routes that only differ by the runtime fraction match and the subset metadata set as a route action it means that requests always route to the same cluster in the router. Later on the in filter chain when performing subset load balancing between endpoints in that single cluster, the subset load balance can be configured to fallback/panic to endpoints in other subsets if there are not enough healthy endpoints in the subset that matches the values set by the route action.

**Comment by zhishi** [comment]
I wonder will the same logic apply for weighted cluster when all the routes point to same cluster with only difference in subset metadata?

**Comment by sc0ttbeardsley** [comment]
If there was a way to do fallbacks with weighted clusters we could use that but seems like it isn’t supported. should this convert to a feature request instead of trying to make `runtime_fraction` work?
