### ISSUE TITLE
DownstreamConnectionTermination (DC) response flag not set for gRPC

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#11572]
The DC response flag signifies that the downstream disconnected or cancelled the connection or request and is very useful for understanding what happened to certain requests via access logs.

It's currently set with this logic:
```
  // A downstream disconnect can be identified for HTTP requests when the upstream returns with a 0
  // response code and when no other response flags are set.
  if (!stream_info_.hasAnyResponseFlag() && !stream_info_.responseCode()) {
    stream_info_.setResponseFlag(StreamInfo::ResponseFlag::DownstreamConnectionTermination);
  }
```

The problem for gRPC is that we may have seen the 200 HTTP response code already, but a cancellation can happen later while receiving the body/trailers.

Proposal: update that logic to add the flag for gRPC requests unless a gRPC status was seen.

Getting into the details, would it make sense to add a isGrpc() and grpcCode() to StreamInfo? ActiveStream would also need to look for grpc-status in the trailers to set it into the stream info.

**Comment by mattklein123** [comment]
> The problem for gRPC is that we may have seen the 200 HTTP response code already, but a cancellation can happen later while receiving the body/trailers.

I think this is the same problem for HTTP though, right? So it seems like potentially this is a larger issue in which downstream disconnect needs to be tracked in a more explicit way?
