### ISSUE TITLE
Can envoy support a build process without bazel?

### ISSUE THREAD

**Issue by smijolovic** [envoyproxy/envoy#11586]
cmake/make
go build

There are common ways to build binaries, and bazel is an absolute nightmare with legacy dependencies abound and a slew of unnecessary inclusions for specific project needs.

Can we please get a more security focused and simpler method to build code with the compilers for the appropriate code and a true list of necessary dependencies vs these bloated build environments that do not keep their dependencies up to date?

When trying to do a CentOS dev build to compile an envoy binary, the following always happens:

[rpmbuild@localhost envoy-1.14.2]$ bazel build --verbose_failures //source/exe:envoy-static 
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/rpmbuild/nimbus8/envoy-build/envoy-1.14.2/tools/bazel.rc
INFO: Analyzed target //source/exe:envoy-static (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: Process exited with status 1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 0.620s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

This build process is not intuitive at all. Bazel is more painful than helpful in this process.

**Comment by mattklein123** [comment]
We will not support a non-bazel build system. I would suggest following up with Bazel if you have Bazel specific feature requests and if there are specific things we can improve on the Envoy side feel free to open issues here.
