### ISSUE TITLE
Formalize policy and removal of exclusionary language from Envoy

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#11596]
We should formalize our policy around exclusionary language in Envoy in the contributor guide. In recent times these have all been commented on in code review in an ad-hoc way, but we should make it explicit in the contributor/review guide. This includes not allowing the following phrases:
- master/slave (use primary/replica instead)
- blacklist (use deny list instead)
- whitelist (use allow list instead)

There are some usages of the above terms in the repo that can be easily cleaned and we can use this as a tracking issue for that. The only API usages that I know of is in the client_ssl_auth filter (white_list) and in the redis filter (master/replica). This can be fixed in the next major version.

We should also decide on whether we want to rename the master branch in the repository to something else like main or trunk. I am in favor of doing this but there will be some temporary churn due to broken links, etc.

I will leave this issue open for community comment to see if there is other language that we should not allow. After that I can update the contribution guide and then we can create tracking issues for cleanup of various existing instances in the project.

cc @envoyproxy/maintainers

**Comment by moderation** [comment]
RocketMQ network filter needs replica change too.

**Comment by mattklein123** [comment]
Regarding the branch rename I discussed with @caniszczyk and we are going to wait until GitHub/git decide on what the new default is going to be. Then we can align with that. I will get started on the rest of it.

**Comment by mattklein123** [comment]
Master has been renamed to main in all projects in the org. We can follow up with additional cleanups as needed in individual projects.
