### ISSUE TITLE
Proposal: Add dynamic metadata to rate limit actions

### ISSUE THREAD

**Issue by clarakosi** [envoyproxy/envoy#11593]
**Description**: Currently to pass information from the dynamic metadata to the rate limit actions one would need to use the Lua filter to append a header with the relevant information. Instead, it would be more useful to be able to use the dynamic metadata directly as one of the actions of the rate limiter.

The action can follow the current MetaData schema[1] to get the value: 

```yaml
actions:
  - { dynamic_metadata: { key: “…”, path: [] } }
```
key: The key name of metadata to retrieve the Struct from the metadata. 
path: The path to retrieve the value from the Struct

**Links**:
1. https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/metadata/v3/metadata.proto.html

**Comment by htuch** [comment]
Seems reasonable functionality; how will a value in the action be interpreted?

**Comment by clarakosi** [comment]
I think we can interpret it the same way we interpret the values from the other actions.

**Comment by htuch** [comment]
SGTM, should I assign this to you?

**Comment by clarakosi** [comment]
Yes, thanks!
