### ISSUE TITLE
Question on using RBAC and JWT http filters

### ISSUE THREAD

**Issue by pete-thecat** [envoyproxy/envoy#11605]
Following the example (https://github.com/envoyproxy/envoy/issues/7913) I have the filters listed below. But is seems that the JWT is not getting parsed as I do not end up with anything in dynamicMetadata (see logs below config.)  The payload_in_metadata is supposed to put the JSON parsed JWT **if verified**. Because I am not seeing the text in the log and rbac is failing I am assuming that verification is failing. Is there a way for me to get more details as to why, I have logging at trace? Or does someone see an error in my configuration? I used the local_jwks that keycloak is publishing for the openid-configuration::jwks_uri. Just to try and eliminate keycloak server as an issue. Another debug point is that if I remove the rbac filter the test curl statement completes successfully (not sure if there is any validation of the JWT token in that case). 

Any help on why the JWT is not getting processed would be greatly appreciated!
-Pete

### config:

     - name: envoy.filters.http.jwt_authn
            config:
              providers:
                myauth_provider:
                  issuer: https://myEnvoyProxyIP/auth/realms/FOO 
                  from_headers: 
                    - name: Authorization
                  forward_payload_header: Authorization
                  forward: true
                  payload_in_metadata: auth_payload
                  local_jwks:
                    inline_string: '{"keys":....}'
              rules:
              - match: {prefix: /applicationTree}
                requires: {provider_name: myauth_provider}
          - name: envoy.filters.http.rbac
            config:
              rules:
                action: ALLOW
                policies:
                  "admin":
                    permissions:
                      and_rules: 
                        rules:
                        - url_path: 
                            path: 
                              prefix: /applicationTree
                        - header: 
                            name: "authorization"
                            prefix_match: "Bearer" 
                    principals:
                       - metadata:
                           filter: envoy.filters.http.jwt_authn
                           path:
                             - key: auth_payload
                             - key: iss
                           value:
                             string_match:
                               prefix: /auth

### logs: 

1580 [2020-06-16 15:45:20.362][14][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:68] checking request: remoteAddress: 10.129.2.1:35092, localAddress: 10.130.3.67:8443, ssl: uriSanPeerCertificate: , subjectPeerCertificate     : , headers: ':authority', 'ingress-proxy-svc'
1581 ':path', '/app-svc/applicationTree'
1582 ':method', 'GET'
1583 'user-agent', 'curl/7.29.0'
1584 'accept', 'application/json'
1585 'authorization', 'Bearer **A token that jwt.io can verify left out for readability**'
1586 'x-request-id', 'd3b03b8e-e51e-4380-b541-e7f50aa81a4f'
1587 'content-length', '0'
1588 'x-forwarded-host', 'ingress-proxy-svc'
1589 'x-forwarded-port', '443'
1590 'x-forwarded-proto', 'https'
1591 'forwarded', 'for=10.24.1.1;host=ingress-proxy-svc;proto=https;proto-version='
1592 'x-forwarded-for', '10.24.1.1,10.129.2.1'
1593 'x-envoy-external-address', '10.24.1.1'
**1594 , dynamicMetadata:**
1595 [2020-06-16 15:45:20.362][14][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:111] enforced denied
1596 [2020-06-16 15:45:20.362][14][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1417] [C6][S14342354663607799590] Sending local reply with details rbac_access_denied
1597 [2020-06-16 15:45:20.362][14][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1504] [C6][S14342354663607799590] encode headers called: filter=0x56018f97ec80 status=0
1598 [2020-06-16 15:45:20.362][14][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1504] [C6][S14342354663607799590] encode headers called: filter=0x56018f97eb40 status=0
1599 [2020-06-16 15:45:20.362][14][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1615] [C6][S14342354663607799590] encoding headers via codec (end_stream=false):
1600 ':status', '403'
1601 'content-length', '19'
1602 'content-type', 'text/plain'
1603 'date', 'Tue, 16 Jun 2020 15:45:20 GMT'
1604 'server', 'envoy'
1605 
1606 [2020-06-16 15:45:20.362][14][trace][connection] [external/envoy/source/common/network/connection_impl.cc:409] [C6] writing 124 bytes, end_stream false
1607 [2020-06-16 15:45:20.362][14][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1750] [C6][S14342354663607799590] encode data called: filter=0x56018f97ec80 status=0
1608 [2020-06-16 15:45:20.362][14][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1750] [C6][S14342354663607799590] encode data called: filter=0x56018f97eb40 status=0

### Test (in a bash script):

- get valid access token from keycloak, store in token
- curl -vvv X GET -ik -H 'Accept: application/json' -H "Authorization: Bearer $token"  https://myEnvoyProxyIP/app-svc/applicationTree

**Comment by qiwzhang** [comment]
A couple errors in your jwt_authn config:

1) Following lines:
```
             from_headers: 
                - name: Authorization
```
mean it will try to find TOKEN as following:
```
Authorization: TOKEN
```
If your TOKEN is in default location "Authorization: Bearer ",  just remove them, use default locations. Or you have to specify value_prefix as
```
             from_headers: 
                - name: Authorization
                  value_prefix: "Bearer "
```

2) following two lines are conflicting each other
```
 forward_payload_header: Authorization
 forward: true
```

`forward: true` means to forward the original token header as it is.   So it will keep the original `Authorization` header.  `forward_payload_header: Authorization` means to write jwt payload data (not the original jwt token),  to header `Authorization`. 

It seems that rbac can access jwt payload from metadata, so not need to write jwt_payload to the header,  so just remove `forward_payload_header`

**Comment by htuch** [comment]
@qiwzhang any thoughts on this one?

**Comment by pete-thecat** [comment]
Thank you @qiwzhang for the detailed explanation. I have made the recommended changes 
- remove forward_payload_header. 
- removed from_headers 
  - I also tried adding the value prefix, but as you mentioned, since I am using the standard, I just removed that config.
There was no change in behavior. FYI, I forgot to mention that I am using version 1.13.1.

**Comment by qiwzhang** [comment]
@pete-thecat could you update with final envoy config?

I suggest you debug one filter at time.   First try jwt_authn filter first to make sure if works.  Then just add rbac filter only to make sure it works.   Then combine them.

It seems that the problem could be in rbac filter.  @yangminzhu is the expert in rbac filter,  he can take a look for you

**Comment by pete-thecat** [comment]
### Tested 
- Just jwt_authn filter:
  - I get the valid response when I put in a valid JWT token, and 
  - I get an unauthorized (401) response when I put in a corrupted one or an expired token. 
- jwt_authn and rbac filter:
  - I get a forbidden response (403) per the configuration below.
    - If I use any for the principals instead of metadata I do get a valid response. It seems to be the use of the jwt_authn filter is the principal section that is the issue. Or I should say that the JWT does not seem to be parsed and placed as JSON in the dynamicMetadata.

### Current Configuration:
I upgraded to envoy 1.15.0-dev, just to make sure I had the most current version, I made sure to resolve any deprecated items. In the principals section I have played around with various types of matches, trying to make it simple enough to pass. That is why I think the parsed token is not where it should be or I am missing something that will get it there so the rbac can validate it has the information I want to filter on.
```
197           http_filters:
198           - name: envoy.filters.http.jwt_authn
199             typed_config:
200               "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
201               providers:
202                 myauth_provider:
203                   issuer: https://myEnvoyProxyIP/auth/realms/ALIS
204                   forward: true
205                   payload_in_metadata: auth_payload
206                   local_jwks:
207                     inline_string: '{"keys":[{"kid":.... Truncated for readablity}]}'
208               rules:
209               - match: {prefix: /applicationTree}
210                 requires: {provider_name: myauth_provider}
211           - name: envoy.filters.http.rbac
212             typed_config:
213               "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
214               rules:
215                 action: ALLOW
216                 policies:
217                   "admin":
218                     permissions:
219                       header: 
220                         name: "authorization"
221                         prefix_match: "Bearer"
222                     principals:
223                       - metadata:
224                           filter: envoy.filters.http.jwt_authn
225                           path:
226                             - key: auth_payload
227                           value:
228                             present_match: true

```
### Logs:

```
1096 [2020-06-17 19:26:58.368][18][debug][http] [source/common/http/conn_manager_impl.cc:1373] [C18][S3892078671634037766] request end stream
1097 [2020-06-17 19:26:58.368][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:123] Called Filter : setDecoderFilterCallbacks
1098 [2020-06-17 19:26:58.368][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:45] Called Filter : decodeHeaders
1099 [2020-06-17 19:26:58.368][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:83] Called Filter : check complete OK
1100 [2020-06-17 19:26:58.368][18][trace][http] [source/common/http/conn_manager_impl.cc:1089] [C18][S3892078671634037766] decode headers called: filter=0x561d238c1a40 status=0
1101 [2020-06-17 19:26:58.368][18][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:74] checking request: requestedServerName: , sourceIP: 10.129.2.1:41434, directRemoteIP: 10.129.2.1:41434, remoteIP: 10.24.1.1:0,localAddress: 10.129.0.85     :8443, ssl: uriSanPeerCertificate: , dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'ingress-proxy-svc'
1102 ':path', '/app-svc/applicationTree'
1103 ':method', 'GET'
1104 'user-agent', 'curl/7.29.0'
1105 'accept', 'application/json'
1106 'authorization', 'Bearer <truncated for readablity>'
1107 'x-request-id', 'b8b4448b-22fd-4fae-bfb5-c430d5f037cc'
1108 'content-length', '0'
1109 'x-forwarded-host', 'ingress-proxy-svc'
1110 'x-forwarded-port', '443'
1111 'x-forwarded-proto', 'https'
1112 'forwarded', 'for=10.24.1.1;host=ingress-proxy-svc;proto=https;proto-version='
1113 'x-forwarded-for', '10.24.1.1,10.129.2.1'
1114 'x-envoy-external-address', '10.24.1.1'
1115 , dynamicMetadata:
1116 [2020-06-17 19:26:58.369][18][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:117] enforced denied
1117 [2020-06-17 19:26:58.369][18][debug][http] [source/common/http/conn_manager_impl.cc:1516] [C18][S3892078671634037766] Sending local reply with details rbac_access_denied
1118 [2020-06-17 19:26:58.369][18][trace][http] [source/common/http/conn_manager_impl.cc:1624] [C18][S3892078671634037766] encode headers called: filter=0x561d2396ceb0 status=0
1119 [2020-06-17 19:26:58.369][18][trace][http] [source/common/http/conn_manager_impl.cc:1624] [C18][S3892078671634037766] encode headers called: filter=0x561d2392f180 status=0
1120 [2020-06-17 19:26:58.369][18][debug][http] [source/common/http/conn_manager_impl.cc:1773] [C18][S3892078671634037766] encoding headers via codec (end_stream=false):
1121 ':status', '403'
1122 'content-length', '19'
1123 'content-type', 'text/plain'
1124 'date', 'Wed, 17 Jun 2020 19:26:57 GMT'
1125 'server', 'envoy'
1126 
1127 [2020-06-17 19:26:58.370][18][trace][connection] [source/common/network/connection_impl.cc:427] [C18] writing 124 bytes, end_stream false
1128 [2020-06-17 19:26:58.370][18][trace][http] [source/common/http/conn_manager_impl.cc:1894] [C18][S3892078671634037766] encode data called: filter=0x561d2396ceb0 status=0
1129 [2020-06-17 19:26:58.370][18][trace][http] [source/common/http/conn_manager_impl.cc:1894] [C18][S3892078671634037766] encode data called: filter=0x561d2392f180 status=0
1130 [2020-06-17 19:26:58.370][18][trace][http] [source/common/http/conn_manager_impl.cc:1920] [C18][S3892078671634037766] encoding data via codec (size=19 end_stream=true)
1131 [2020-06-17 19:26:58.370][18][trace][connection] [source/common/network/connection_impl.cc:427] [C18] writing 19 bytes, end_stream false
1132 [2020-06-17 19:26:58.370][18][trace][connection] [source/common/network/connection_impl.cc:315] [C18] readDisable: disable=false disable_count=1 state=0 buffer_length=2145

```

**Comment by pete-thecat** [comment]
I figured out my problem... the jwt_authn filter rules match was not being met for my test case. In my configuration the rbac filter was being triggered because there was a JWT in the header, but the authn filter was not being executed because the rule was not being satisfied. Therefore the dynamic meta data was not populated and rbac was properly failing. Seeing the logs now, there is a clear indication that my rule is being matched and the extraction of the JWT is being done. My lack of experience with the envoy product and its logging lead me to gloss over what is now so apparent; nothing was done because the rule did not match, but that is not an error. 
Envoy was doing exactly what I told it to do..... 
```
  .-'---`-.
,'          `.
|             \
|              \
\           _  \
,\  _    ,'-,/-)\
( * \ \,' ,' ,'-)
 `._,)     -',-')
   \/         ''/
    )        / /
   /       ,'-'
```
