### ISSUE TITLE
Reduce boilerplate config in integration tests

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1162]
Today, when adding a new integration test with its own configuration requirements, we need to either:

1. Create/clone an Envoy config, with some amount of boilerplate, or
2. Reuse an existing config, adding in listeners/filters etc. unrelated to the original config.

Ideally, we would be able to programatically generate configs, with a common base and per-test customization. This might be much more feasible in v2 where we have proto objects to build the configs.

**Comment by alyssawilk** [comment]
So do you still want to wait until v2, or should I resurrect the json formatted I spent 30 minutes twiddling with?

**Comment by htuch** [comment]
Yep, I think v2 makes sense, was just going through the v2 API issues and getting an idea of who might be owning some of them. Since you expressed interest in this aspect I tagged you on it.
