### ISSUE TITLE
ext auth: remove ext auth specific tracing

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#11623]
While looking at some tracing stuff I noticed that the ext auth filter does its own tracing: https://github.com/envoyproxy/envoy/blob/9aa85a314552bffb60c13a6acfd60317eaa3bc14/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L220.

This is before we added tracing directly into async client: https://github.com/envoyproxy/envoy/blob/9aa85a314552bffb60c13a6acfd60317eaa3bc14/include/envoy/http/async_client.h#L237

We should replace the ext auth specific tracing with that provided by the async client.

cc @dio

**Comment by dio** [comment]
Gotcha. This is also relevant for `httpCall()`. Thanks for this.
