### ISSUE TITLE
tracing: support getting/setting baggage on spans

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#11622]
The Envoy span API: https://github.com/envoyproxy/envoy/blob/9aa85a314552bffb60c13a6acfd60317eaa3bc14/include/envoy/tracing/http_tracer.h#L108

Does not support getting/setting baggage. At Lyft we will need to make use of this against the OT driver so will need to add this support. It should be fairly trivial to call through to the OT driver code for this but will need to figure out how to handle this generically for tracers that do not support baggage (possibly a feature capability bit or similar).

cc @rnburn @objectiser @garrettheel

**Comment by objectiser** [comment]
> but will need to figure out how to handle this generically for tracers that do not support baggage (possibly a feature capability bit or similar).

Can't it just be a no-op.

**Comment by mattklein123** [comment]
> Can't it just be a no-op.

I think NOP is probably fine to start with, but I could imagine some uses cases in which people would think they are sending baggage and it doesn't actually do anything in practice?

**Comment by LisaLudique** [comment]
What are your thoughts on logging a warning to avoid failing silently in tracers that do not support baggage (i.e. in the no-op methods)?

**Comment by matthewgrossman** [comment]
with #12260 merged do we want to close this issue? Or we do we want to leave it as a tracker for other Tracer's not-yet-implemented functionality?

**Comment by mattklein123** [comment]
I think we can close for now, thank you!
