### ISSUE TITLE
Add beforeFinalizingSpan callback to AsyncClient::Callbacks to allow specific tagging in extensions

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#11635]
In the current `AsyncRequestImpl::onComplete()` and `AsyncRequestImpl::onFailure()` we call  `onSuccess` and `onFailure` callbacks respectively after finalizing the upstream span (by calling `Tracing::HttpTracerUtility::finalizeUpstreamSpan()`). Currently, there is no chance at the implementation side e.g. `ext_authz` extension to add extension specific tags to the current active span. Adding `beforeFinalizingSpan()` (not sure about the name) as an additional callback for `AsyncClient::Callbacks` probably could help to rectify this.

As an additional observation, for gRPC async client, `finishSpan()` happens after `onSuccessRaw` (hence subsequently `onSuccess` callback) is called. `onSuccessRaw` gives the opportunity to add extension specific tags (e.g. in ratelimit extension: https://github.com/envoyproxy/envoy/blob/8d7cd0c61659a2dee0e6527de2c624ada8d2e12b/source/extensions/filters/common/ratelimit/ratelimit_impl.cc#L73).

This is somewhat relevant to https://github.com/envoyproxy/envoy/issues/11623 since the current implementation of tracing (for HTTP Service) in `ext_authz` adds additional specific tags for `ext_authz` (while I'm not sure dropping those tags probably will not introduce problems).

cc. @mattklein123.

**Comment by mattklein123** [comment]
Makes sense, thanks for opening.

**Comment by mattklein123** [comment]
Fixed
