### ISSUE TITLE
Windows: yaml-cpp errors when files are checked out on Windows with CRLF line endings

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#11659]
Currently we have had to mark some tests as failing on Windows when the Envoy codebase is checked out with CRLF line endings. `yaml-cpp` fails to parse test fixtures and errors with something like: `yaml: line 3: mapping values are not allowed in this context`

Current (possibly non exhaustive) list of tests affected:
- //test/common/buffer:watermark_buffer_test
- //test/common/runtime:runtime_impl_test
- //test/exe:main_common_test
- //test/integration:dynamic_validation_integration_test
- //test/server:server_test

We should be able to support parsing configs with any valid line ending (or make a policy that this is not the case) and add tests that run cross-platform to ensure files with CRLF and LF line endings are parsed correctly.

**Comment by sunjayBhatia** [comment]
cc @wrowe @davinci26 @nigriMSFT

**Comment by wrowe** [comment]
Note that 11719 only papers over the issue to get RBE CI //test/... running.

This defect to have the yaml parser properly handle CR+LF line endings remains unaddressed.

**Comment by wrowe** [comment]
This was resolved by https://github.com/envoyproxy/envoy/pull/12381#event-3605975396 - the internal test substitution wrote back binary istream as a text istream, resulting in \r\r\n sequences. Arguable but not really a problem for yaml-cpp to accept.

**Comment by sunjayBhatia** [comment]
Closing this as per comment above
