### ISSUE TITLE
Windows: Recent bump to rules_go breaks Windows + RBE

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#11657]
We have found that the recent bump to `rules_go` v0.23.3 breaks Windows building via RBE. This is not a specific issue with `rules_go`, but rather a bug in Bazel/RBE (to be further determined the exact cause). We are intending to patch `rules_go` with a small patch in the interim while the underlying issue gets sorted out.

The failure manifests itself in Envoy as:

```
ERROR: C:/_eb/external/go_sdk/BUILD.bazel:43:1: GoToolchainBinaryCompile external/go_sdk/builder.exe.a failed (Exit 1): builder.exe.bat failed: error executing command 
  cd C:/_eb/execroot/envoy
  SET GOROOT=external/go_sdk
  bazel-out/host/bin/external/go_sdk/builder.exe.bat
Execution platform: @rbe_windows_msvc_cl//config:platform
'bazel-out' is not recognized as an internal or external command,
operable program or batch file.
Target //source/exe:envoy-static failed to build
```

However, this is not an Envoy/`rules_go` specific issue, we have been able to reproduce this separately, see link below

*Links*
- `rules_go` PR with some description of the issue: https://github.com/bazelbuild/rules_go/pull/2542
- minimal repro of the issue and description: https://github.com/greenhouse-org/bazel-issue-repro/tree/master/ctx_actions_run_rbe

**Comment by sunjayBhatia** [comment]
cc @wrowe @davinci26 @nigriMSFT

**Comment by sunjayBhatia** [comment]
See https://github.com/bazelbuild/bazel/issues/11636 for Bazel issue

**Comment by sunjayBhatia** [comment]
looks like there are some volunteers to fix the issue in Bazel: https://github.com/bazelbuild/bazel/issues/11636

**Comment by wrowe** [comment]
@sunjayBhatia Would you go ahead and check status on this?

**Comment by sunjayBhatia** [comment]
I'm going to remove myself from this issue as I'm not actively working on it
