### ISSUE TITLE
[Proto-gen-validation] negative "nanos" generated by type "Duration"

### ISSUE THREAD

**Issue by jianwen612** [envoyproxy/envoy#11658]
*Description*:
When I was using token_bucket protobuf which is defined here:
`api/envoy/type/v3/token_bucket.proto`
Some test case generated by fuzzer shows negative "nanos":
>fill_interval {
      seconds: 12032
      nanos: -8
    }

By looking into it, I found that in type `google.protobuf.Duration`,
it seems the validation only checks the "sum" of `seconds` and `nanos` but doesn't check them separately.
(The validation is here)
https://github.com/envoyproxy/protoc-gen-validate/blob/3bd820adb86cc455b16b37465905a9b99e22cbbb/templates/cc/duration.go

This issue causes the function `validateDuration` to fail here:
https://github.com/envoyproxy/envoy/blob/5faff2add085eb4f11046725861233a63d89ad7c/source/common/protobuf/utility.cc#L898

And one of the network filters which I'm testing on uses this function in its constructor (local_ratelimit filter).
In order to make my fuzz test code to run, I could only check this condition by myself before passing it to the constructor.
But I suggest we modify the validation rule to make `nanos` always greater or equal to 0, because I think negative `nanos` doesn't make sense and we may have to use extra code to check it.

Thanks!
/cc @asraa 
/cc @akonradi

**Comment by htuch** [comment]
Makes sense, but probably belongs in the issue tracker for https://github.com/envoyproxy/protoc-gen-validate/issues

**Comment by jianwen612** [comment]
> Makes sense, but probably belongs in the issue tracker for https://github.com/envoyproxy/protoc-gen-validate/issues

Thanks for the information! I will open an issue there.
