### ISSUE TITLE
How is original destination lb being supported by v3?

### ISSUE THREAD

**Issue by fuqianggao** [envoyproxy/envoy#11664]
In v2 API, to use original destination lb, one needs to set both:
cluster.lb_policy -> ORIGINAL_DST_LB
cluster.type -> ORIGINAL_DST

Now in v3 API, ORIGINAL_DST type is still available, but ORIGINAL_DST_LB is not in lb_policy anymore.

Is this feature still supported in v3? If so, how should one configure?

BTW, the doc says: "Original destination service discovery must be used with the original destination load balancer. "
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#arch-overview-service-discovery-types-original-destination

**Comment by mattklein123** [comment]
Like this: https://github.com/envoyproxy/envoy/blob/7f251daa2e488587bc7335f91faceed420f162c4/test/common/upstream/original_dst_cluster_test.cc#L108-L115

Can you update the docs? I agree they are bad.

Note the original intention here (which hasn't been finished) is that the original_dst cluster can be moved to an extension which can be compiled out.

**Comment by fuqianggao** [comment]
Thanks. Sure, I can update the doc. Just to clarify a few things
1. For original destination, although we use cluster_provided as lb_policy, we don't actually need to provide a specific lb algorithm, right?
2. For the doc, should it only reflect the latest (v3) settings, or should it cover both v2 and v3?

**Comment by mattklein123** [comment]
1) Right
2) Only v3 is fine.

Thank you!
