### ISSUE TITLE
keep ApiState pause/resume ref-counted, to make sure resume on the state is always called (always in pair).

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#11674]
per Harvey, let's make the ApiState pause/resume operations always come in pair.
Currently there is no guarantee on when/whether the "resume" will be called after the ApiState has been "pause"d.

We should consider mechanism like RAII object which auto-resume the paused resource type when the object died.

**Comment by stevenzzzz** [comment]
PR #11739 made an improvement on returning a Cleanup instance which resumes the paused resources on destruction. 
This work well with most of the callsites in our codebase, i.e., the pause/resume happens in pair in a single main thread dispatcher event. 
The only exception is in ClusterManagerImpl::updateClusterCount, this method is called by multiple functions in cluster manager impl, and the pause-resume may span across several main thread dispatcher events[1]. This is not ideal, as it is hard to tell when the pause happens and when will it be resumed. also a possible stuck eds response could stop CDS from been continued. we will sort out the right move there and see if we can achieve the "resume when out of pause scope" goal for all Pause callsites.

[1] https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L806-L808

**Comment by htuch** [comment]
I'll take this on in the context of https://github.com/envoyproxy/envoy/issues/11877. I realized that we need to pause/resume the type URL undergoing update there, which means we definitely need ref counting (since we have existing pause/resumes nested inside config updates).
