### ISSUE TITLE
Front-proxy example error == returned a non-zero code: 127

### ISSUE THREAD

**Issue by lu4t** [envoyproxy/envoy#11679]
Hi, when running the front-proxy example on a laptop, I get the following error on step 3/8:

/bin/sh: pip3: not found
ERROR: Service 'service1' failed to build: The command '/bin/sh -c pip3 install -q Flask==0.11.1 requests==2.18.4' returned a non-zero code: 127

I found on Dockerfile-service file, on lines 3 and 4: 

RUN apk update && apk add python3 bash curl
RUN pip3 install -q Flask==0.11.1 requests==2.18.4

However, to run pip3, the correct package to add is named: py3-pip (not python3).

If I edit and change the dockerfile-service file, the dockers seem to build correctly.

When doing docker-compose ps, I still got an error saying:
front-proxy_front-envoy_1 status: Exit 1
front-proxy_service1_1 status: Exit 127
front-proxy_service2_1 status: Exit 127

So the example seems to be failing somewhere else also...

**Comment by dio** [comment]
@lu4t I think this PR https://github.com/envoyproxy/envoy/pull/11523 will fix that. 

Relevant: https://github.com/envoyproxy/envoy/issues/11506#issuecomment-640912515.

**Comment by lu4t** [comment]
thanks @dio for your comment; #11523 might solve problem with starting after build is complete, but I still think pip3 wont work if the package name to be added is not corrected. This has nothing to do with permissions. I believe.

> 
> 
> @lu4t I think this PR #11523 will fix that.
> 
> Relevant: [#11506 (comment)](https://github.com/envoyproxy/envoy/issues/11506#issuecomment-640912515).

**Comment by dio** [comment]
@lu4t can you try to run:

```
docker run --rm -it -e ENVOY_UID=0 envoyproxy/envoy-alpine-dev:latest apk add python3 && which pip3 && pip3 --version &&  pip3 install Flask==0.11.1
```

In my local, it prints:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
...
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

OK: 67 MiB in 30 packages
/usr/local/bin/pip3
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Requirement already satisfied: Flask==0.11.1 in /usr/local/lib/python3.7/site-packages (0.11.1)
...
```

**Comment by lu4t** [comment]
Hi @dio 
the && on your command was causing me problems on w10 powershell... looks like it is not workind for me.
Instead, I ran envoy docker and started a bash, and this is what I got (I hope is valid for you):

```
> docker run --rm -it -e ENVOY_UID=0 envoyproxy/envoy-alpine-dev:latest /bin/ash
> 
> / # ls
bin                   etc                   lib64                 opt                   run                   sys                   var
dev                   home                  media                 proc                  sbin                  tmp
docker-entrypoint.sh  lib                   mnt                   root                  srv                   usr
> / # apk add python3
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
> (1/10) Installing libbz2 (1.0.8-r1)
> (2/10) Installing expat (2.2.9-r1)
> (3/10) Installing libffi (3.3-r2)
> (4/10) Installing gdbm (1.13-r1)
> (5/10) Installing xz-libs (5.2.5-r0)
> (6/10) Installing ncurses-terminfo-base (6.2_p20200523-r0)
> (7/10) Installing ncurses-libs (6.2_p20200523-r0)
> (8/10) Installing readline (8.0.4-r0)
> (9/10) Installing sqlite-libs (3.32.1-r0)
> (10/10) Installing python3 (3.8.3-r0)
> Executing busybox-1.31.1-r16.trigger
> Executing glibc-bin-2.31-r0.trigger
> /usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link
> 
> OK: 67 MiB in 30 packages
> / # which pip3
> / # pip3 --version
> /bin/ash: pip3: not found
> / # pip3 install Flask==0.11.1
> /bin/ash: pip3: not found
> / #
```

On the same bash, but this time usign the right package name, this is what you get:


```
/ # apk add py3-pip
(1/26) Installing py3-appdirs (1.4.4-r1)
(2/26) Installing py3-ordered-set (4.0.1-r0)
(3/26) Installing py3-parsing (2.4.7-r0)
(4/26) Installing py3-six (1.15.0-r0)
(5/26) Installing py3-packaging (20.4-r0)
(6/26) Installing py3-setuptools (47.0.0-r0)
(7/26) Installing py3-chardet (3.0.4-r4)
(8/26) Installing py3-idna (2.9-r0)
(9/26) Installing py3-certifi (2020.4.5.1-r0)
(10/26) Installing py3-urllib3 (1.25.9-r0)
(11/26) Installing py3-requests (2.23.0-r0)
(12/26) Installing py3-msgpack (1.0.0-r0)
(13/26) Installing py3-lockfile (0.12.2-r3)
(14/26) Installing py3-cachecontrol (0.12.6-r0)
(15/26) Installing py3-colorama (0.4.3-r0)
(16/26) Installing py3-distlib (0.3.0-r0)
(17/26) Installing py3-distro (1.5.0-r1)
(18/26) Installing py3-webencodings (0.5.1-r3)
(19/26) Installing py3-html5lib (1.0.1-r4)
(20/26) Installing py3-pytoml (0.1.21-r0)
(21/26) Installing py3-pep517 (0.8.2-r0)
(22/26) Installing py3-progress (1.5-r0)
(23/26) Installing py3-toml (0.10.1-r0)
(24/26) Installing py3-retrying (1.3.3-r0)
(25/26) Installing py3-contextlib2 (0.6.0-r0)
(26/26) Installing py3-pip (20.1.1-r0)
Executing busybox-1.31.1-r16.trigger
Executing glibc-bin-2.31-r0.trigger
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

OK: 79 MiB in 56 packages
/ # pip3 --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

I checked, and all the /examples folder on the repo have this same effect.

**Comment by dio** [comment]
Gotcha. Could you either create a PR or comment to https://github.com/envoyproxy/envoy/pull/11523?

**Comment by lu4t** [comment]
@asraa and @dio, this issue should not be closed as it is still happening. 
Examples, like front-proxy, are not running if you follow the guide: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy

The exact same problems described on my first post are happening:
(A) Dockerfile-service file should be corrected on line 3: 
from: RUN apk update && apk add python3 bash curl
to: RUN apk update && apk add **py3-pip** bash curl

After this correction is done, you wont get the error:
`bin/sh: pip3: not found
ERROR: Service 'service1' failed to build: The command '/bin/sh -c pip3 install -q Flask==0.11.1 requests==2.18.4' returned a non-zero code: 127`
and the docker build will complete.

(B) However, after this correction is done, you still will get an error on the services:

`docker-compose ps
          Name                         Command                State     Ports
-----------------------------------------------------------------------------
front-proxy_front-envoy_1   /docker-entrypoint.sh /bin ...   Exit 1
front-proxy_service1_1      /bin/sh -c /usr/local/bin/ ...   Exit 127
front-proxy_service2_1      /bin/sh -c /usr/local/bin/ ...   Exit 127`
