### ISSUE TITLE
Question: Accessing environment variable in lua filter

### ISSUE THREAD

**Issue by samitpal** [envoyproxy/envoy#11676]
This is a question.

I'm using lua filter and I need a way to access an environment variable within the lua code. Is that possible?

**Comment by dio** [comment]
While it is not recommended, you can always use `os.getenv` (calling system call every time you handle a request probably costly). I think a combination of templating for config and metadata could give better help there.

However, if you insist to do it, an example to call it directly from the script:

```
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:headers():add("system-path", os.getenv("PATH"))
                end
                function envoy_on_response(response_handle)
                  response_handle:headers():add("system-path", os.getenv("PATH"))
                end

```

**Comment by samitpal** [comment]
Thanks!
I was trying os.getenv myself and was not doing it right. It works now. Although like you said from performance point of view I will try to figure out a way where I may not need to read from env.

Closing this ticket
