### ISSUE TITLE
The LinkedObject::moveIntoList usage is unsafe

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#11691]
Usage of the `LinkedObject::moveIntoList()` and `LinkedObject::moveIntoListBack()` is unsafe. Clang-tidy rightfully complains:

```
source/common/http/http2/codec_impl.cc:1317:3: error: 'stream' used after it was moved [bugprone-use-after-move,-warnings-as-errors]
  stream->moveIntoList(std::move(stream), active_streams_);
  ^
source/common/http/http2/codec_impl.cc:1317:24: note: move occurred here
  stream->moveIntoList(std::move(stream), active_streams_);
                       ^
source/common/http/http2/codec_impl.cc:1317:3: note: the use and move are unsequenced, i.e. there is no guarantee about the order in which they are evaluated
  stream->moveIntoList(std::move(stream), active_streams_);
  ^
```

This pattern is used throughout the code. So far compiler generated working code, but it should be cleaned up before we hit this issue in production.

**Comment by antoniovicente** [comment]
One possible way to fix this: make the moveIntoList method "static"

The ASSERTs should refer to stream->inserted_ instead of this->inserted_.

**Comment by lizan** [comment]
FYI we had a fix before: https://github.com/envoyproxy/envoy/pull/7376 cc @lambdai, I think we should revisit this.
