### ISSUE TITLE
Fault Filter - Abort Faults' Responses

### ISSUE THREAD

**Issue by Augustyniak** [envoyproxy/envoy#11707]
Envoy's fault filter supports abort faults. When Envoy inject an abort fault it returns a response that uses `text/plain` as its content-type and sets "fault filter abort" as its body.

At Lyft, mobile clients try to deserialize every response that they get from the server (or/and Envoy). There are a few known issue when it comes to deserializing responses that are sent by Envoy's fault filter when an abort fault is injected:

- Even though Lyft mobile applications set `application/json` or/and `application/x-protobuf` as the value of `accept` header that they send as part of network requests that they make, Envoy filter returns a response with `content-type` equal to `text/plain`.
- There is no easy way to tell when Envoy injected a fault - a mobile client would need to look for "fault filter abort" body of a request in order to be sure that Envoy injected a fault but hard-coding a string like this on the client is not preferable. Can a client just assume that every request with `x-envoy-fault-abort-request` HTTP header set ends up getting an abort fault in response? No, it's not that simple because of the existence of `x-envoy-fault-abort-request-percentage` HTTP header. If a client sends a request with `x-envoy-fault-abort-request` HTTP header equal to 503 and `x-envoy-fault-abort-request-percentage` equal to 10 (10%) it's up to the Envoy to decide whether a fault should be injected or not (with 10% chance of the fault being injected).

Because of the aforementioned issues with the current Envoy's fault filter responses the following changes to fault filter's responses is proposed:

- Make fault filter return an empty response if an abort fault is injected.
- Make fault filter set the value of `x-envoy-injected-faults` HTTP header to `abort` every time an it injects an abort fault.

**Comment by mattklein123** [comment]
Can you use the new local reply mapper feature to map the response however you like?

**Comment by Augustyniak** [comment]
@mattklein123 Thanks for chiming in :) 

I think that a recently introduced local reply mapper is an acceptable solution here. Let me expand a little bit on why I think it's not the best solution here and propose an alternative one - to modify the implementation of `sendLocalReply` method (more details later on) to make all responses send by Envoy filters include `x-envoy-local-response` HTTP header https://github.com/envoyproxy/envoy/blob/0c6523c0925d260de41d89002044d0d6271550d0/source/common/http/utility.cc#L419-L420

Even though my initial Github issue was focused only on a fault filter after talking with @murki and @gkleiman I think that we should think bigger here and expand the scope of the issue to all Envoy's filters instead of focusing on any specific filter.

### What do we want to accomplish?

As a reminder, we want our clients NOT to emit deserialization error analytics events if they receive a response from one of Envoy's filters that they cannot deserialize. Why? We think, that for the most part network serialization errors that are emitted in response to injected faults (by a fault filter) or rate limits being exceeded (by a rate limit filter) or any other Envoy filters are not actionable. In cases like this, instead of alarming mobile on-call people on serialization errors, we prefer to alarm them on failed network requests - for example, instead of alarming our on-call due to issues with deserializing responses from rate limit filter we want to alarm them on the increase in the number of 429 status codes coming from a "server" (since the real issue here is not that a client cannot deserialize a response but the fact that some clients are being rate-limited).

### Why not local reply mapper?

- to make local reply mapper work we would need to specify its configuration for each of the existing filters to ensure that `content-type` HTTP header that they use is set to the right value. We would also need to ensure that all new Envoy filters use local reply mapper too.
- for `application/x-protobuf` `content-type` (that our mobile applications sometimes require) our mobile applications require the following format of `content-type` HTTP header that our mobile applications send: `application/x-protobuf; messageType=foo.bar.Baz`. We would need to "teach" Envoy how to encode a protobuf response AND make Envoy attach `messageType=foo.bar.Baz` string as part of the value of `content-type` HTTP header. Now, there are multiple reasons for which we don't want Envoy to do this: 1) local reply mapper doesn't support protobuf responses 2) Envoy doesn't know a `messageType` a mobile client expects 3) this logic is too specific to Lyft and cannot be simply added to OSS Envoy.

### What's the proposed solution?

To be able to allow clients not to emit deserialization errors for responses from Envoy filters all responses that come out of any of Envoy's filters would need to have some kind of a special HTTP header attached to them, for example, `x-envoy-local-response: true`.

The initial idea is to modify the implementation of `sendLocalReply` https://github.com/envoyproxy/envoy/blob/0c6523c0925d260de41d89002044d0d6271550d0/source/common/http/utility.cc#L419-L420
so that it adds `x-envoy-local-response: true` to all of the responses. To do that, we would need to verify that this method is only used (as its name suggest) to send responses that are created locally by Envoy filters.

**Comment by mattklein123** [comment]
I like the idea of adding an `x-envoy-local-response` header for local replies, as this is a common point of confusion anyway, but I still wonder whether this should be configurable or could just be done with a "catch all" local reply mapper config. If this is not possible with a local reply mapper catch all config today could we just add the capability to add generic headers to local replies? I think there are other issue(s) on this already. cc @alyssawilk for thoughts here.

**Comment by Augustyniak** [comment]
I really like the idea of using local reply mapper for this. The only issue is that local reply mapper doesn’t currently support addition of http headers - this is something that I’m going to take a look at.  Hopefully, I will be able to add this capability to local reply mapper and use a it to add `x-envoy-local-response` HTTP header to all responses that are sent by any of envoy filters.

**Comment by Augustyniak** [comment]
The changes to local state mapper - allowing local state mapper to add HTTP headers to local replies - were implemented as part of https://github.com/envoyproxy/envoy/pull/12093
