### ISSUE TITLE
Support multiple management servers

### ISSUE THREAD

**Issue by tschroed** [envoyproxy/envoy#1170]
It's common in high-availability scenarios to have hot standby components. This should apply to the management server so that if the primary fails we can go to backups. As part of this it should be possible to dynamically change the management server endpoints programmatically (i.e. from within 3rd party code).

@htuch as you look at v2 API implementation.

**Comment by mattklein123** [comment]
This seems like something DNS could be used for, no? Is the extra complexity really needed? (We plan on bootstrapping envoy via DNS to managers).

**Comment by tschroed** [comment]
DNS is the obvious choice but there are significant downsides at scale that make other naming services attractive. (For some of the flavor have a look at Spotify's love/hate relationship with DNS, even if their solution is kind of just a beefier DNS infrastructure.)

Google's own painful experience with DNS for service discovery many years ago let us to alternative solutions.

**Comment by mattklein123** [comment]
I'm fairly familiar with the pros/cons of DNS, and for config server bootstrapping it seems pretty great to me.

Anyhow, it's unclear what functionality you are really asking for on the envoy side. Do you want a static cluster where the static IPs can be modified via API at runtime? (I can't think of any other way this could work). If so, that seems reasonable to me.

**Comment by tschroed** [comment]
I think it's two pieces:

1. Support for a fallback such that in a timespan shorter than the update interval an Envoy in the field can talk to a different management server, say O(1s), without any changed input from external systems. This would be a decision made strictly locally by the Envoy process itself.

2. The ability to change those management server endpoints to different ip:port pairs, say because we've replaced the old one(s) with new one(s) based on new data from external systems. I think this is what you describe above.

**Comment by mattklein123** [comment]
OK, here is how I suggest we implement (really 2 separate items):

1. We should allow the definition of eds/rds/lds/etc. to supply a list of clusters. If > 1 cluster is defined, envoy should move to the next cluster if there is any kind of failure. We can implement fancier stuff, but this is dead simple and would just keep cycling through clusters until a good one is found.

2. Yes, I think this is just a static cluster where code can modify the backends from within the process / via API. This isn't supported today but it won't be hard to implement.

How does that sound?

**Comment by tschroed** [comment]
Rad.
