### ISSUE TITLE
Add Buffer to UdpStatsdSink

### ISSUE THREAD

**Issue by murray-stripe** [envoyproxy/envoy#11710]
__Description__
Statsd protocol allows for metrics to be [newline separated](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#multi-metric-packets). The current implementation for statsd sink does not take this into account an instead writes metrics out one at a time. [source](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/common/statsd/statsd.cc#L38).

I understand that for UDP, there is the MTU to contend with and that the decision to not use a buffer was possibly chosen to avoid having to deal with this concern. I'd like to propose a change that introduces a buffer to the `UdpStatsdSink` who's size is determined by a configuration.

In general I imagine the semantics would look like such:

  + A new `buffer_size` config value will be added to [`DogStatsdSink`](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/metrics/v3/stats.proto#L316) and [`StatsdSink`](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/metrics/v3/stats.proto#L265)
  + Default configuration value of `0` will indicate no buffer is to be used and will maintain current behavior
  + The buffer will be created at the beginning of [`UdpStatsdSink::flush`](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/common/statsd/statsd.cc#L51) and will flush both as necessary (when full) and at the end.

Constraining the buffer lifespan to a `UdpStatsdSink::flush` invocation I think strikes a balance between better performance and simplicity of the implementation.

If this idea is agreeable, I should be able to produce a small PR in short-order.

**Comment by mattklein123** [comment]
Yup SGTM.

**Comment by murray-stripe** [comment]
Awesome. I'll put together a PR.
