### ISSUE TITLE
example/ext_authz: INVALID_ARGUMENT:transport_api_version

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#11764]
In https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/ext_authz, I have an issue with step 2.
Container front _envoy fails with below logs 

`front-envoy_1             | [2020-06-26 04:28:38.684][6][info][main] [source/server/server.cc:296]   envoy.thrift_proxy.protocols: auto, binary, binary/non-strict, compact, twitter
front-envoy_1             | [2020-06-26 04:28:38.692][6][critical][main] [source/server/server.cc:98] error initializing configuration '/etc/front-envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:transport_api_version: Cannot find field.) has unknown fields
front-envoy_1             | [2020-06-26 04:28:38.692][6][info][main] [source/server/server.cc:673] exiting
front-envoy_1             | Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:transport_api_version: Cannot find field.) has unknown fields`

**Comment by dio** [comment]
@mk46 sorry, mind sharing your `envoyproxy/envoy-dev:latest` version?

```
docker run --rm -it envoyproxy/envoy-dev:latest --version
```

It seems like you need to re-pull the `envoy-dev:latest` image.

You can do: 

```
docker-compose build --pull
```

or 

```
docker pull envoyproxy/envoy-dev:latest
```

**Comment by mk46** [comment]
@dio It's working. Thanks!
