### ISSUE TITLE
Help needed: http2 reset resolved by max_headers_count - should 431?

### ISSUE THREAD

**Issue by gongcon** [envoyproxy/envoy#11774]
What can be the causes of Envoy reseting a request in HTTP/2 connection? We have 2 levels of Envoy, L1 serves end user at the edge using HTTP/1.1 connections; L2 is the sidecar of actual service. L1 to L2 is connected via HTTP/2. We found that L2 recently has some `http2_tx_reset` which caused 503 in L1 responses. For these problematic responses, we do not see spans from L2, only see spans from L1 with response_flag `UR,URX`. All retries fail in this case no matter what number we set it to. The current retry policy is: 
```
retry_on: connect-failure,gateway-error
num_retries: 1
per_try_timeout: 0.5s
```

Seems not related to issue #11369 since HTTP/2 connection is not terminated while this happens.

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
Hmmm, unfortunately that stat is incremented where nghttp2 sends the stream reset, not where Envoy rejects the request.  That means the instructions for debugging Envoy replies (https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_envoy_sending_internal_responses) are not really going to help you.

The likely root cause is that nghttp2 is a bit more spec compliant than http_parser so some things pass Envoy's HTTP/1.1 validation but don't pass HTTP/2 validation.  I've been working to reduce the differences - if you're running an older Envoy build I suggest you upgrade.  If you're running a more recent build you may have found one we haven't run across yet.

Even more unfortunately it's not very easy to debug this case today if you've got high load.  If it's possible for you to run a debug build at your L2 you can turn on trace logs, and get pretty detailed data on where nghttp2 is rejecting your request.  Alternately if you can't run a debug build, trace logs or access logs of the requests getting reset still might be enough to repro.  If you need a hand debugging you can post logs here or message me on slack (if they might have sensitive data) and I'll see if I can help you sort out what's going on.

**Comment by gongcon** [comment]
Thanks @alyssawilk for the help. We're currently running version 1.12.0, not the latest but not very old either -- please instruct. 

Debugging it may be quite difficult for us. The error rate is about 0.01%, and the service has 2-4k rps. Enabling one single node in debug mode may not catch the issue, also the huge amount of logs will overwhelm the log server.

**Comment by alyssawilk** [comment]
yeah, I was worried about that w.r.t. the log rates in production.  Argh.

Are you running 1.12.0 or the CVE release?  I think if you're running 1.12.2 you've got most of the consistency checks.

Do the access logs on the 5xx requests get you anything interesting we could use as breadcrumbs?  I really do want to do detailed errors for nghttp2 stream resets the way we have for in-envoy responses, but if I recall correctly while it gives useful debug logs on stderr (which aren't plausible for you) the error codes it returns programatically were not useful last time I checked.  In the meantime if the requests failing have upgrade headers or weird methods that'd certainly be a clue.

**Comment by gongcon** [comment]
We are running 1.12.0.

Just updated the connection between L1 and L2 to HTTP/1.1 and the problem is still there. Seems it's not related to HTTP/2. The difference between L1 and L2 is HTTPS is terminated in L1.

**Comment by alyssawilk** [comment]
So the L2 rejects over HTTP/1.1?  That's both surprising and promising if you're seeing the errors reflected in http1 stats you could turn up details in the access logs (in the link above) and see what it's telling you.

**Comment by gongcon** [comment]
We turned on access log yet didn't see those problematic requests show up. Does including `%RESPONSE_CODE_DETAILS%` help in this case? As mentioned earlier, Envoy doesn't send tracing spans when this error occurs either.

**Comment by gongcon** [comment]
Sorry, posted too early. Do catch some requests with response_flags DPE. Will add %RESPONSE_CODE_DETAILS% and update you later.

**Comment by gongcon** [comment]
I must be watching stats in another region after changed the protocol to HTTP/1.1. Here's my current observations:
* No rx_reset and no downstream 5xx in L1 Envoy when using HTTP/1.1 to communicate with L2, yet see "response_flags:DPE" and empty response_code_detail in access log.
* See rx_reset and downstream 5xx in L1 Envoy when using HTTP/2. However, no "response_flags:DPE" in access log at all.

**Comment by gongcon** [comment]
Just tried 1.12.4 and the problem persists.

**Comment by gongcon** [comment]
Another question is, how can the requests pass validation in L1 and fail in L2?

**Comment by alyssawilk** [comment]
empty response code detail is puzzling - we're pretty good at filling that in on the HTTP/1.1 path.  Having DPE and no details and no 500 is even more confusing. 
There's a few ways things can pass validation at the L1 and fail at the L2 - header size being one that comes to mind (if you're right near the edge and add debug headers, you can go over).  I'm not sure how many other variants there are - they're not super common - but unfortunately I don't think the information from your logs gives me enough breadcrumbs for me to help you sort it out :-(

**Comment by gongcon** [comment]
I suspected that as well, yet from the document, it should response 431 when using HTTP/1.1 in this case, so not quite sure if that's true. Empty response with flags DPE make me very confused.

Is there any test app on your side to capture the requests and output when errors occur?

**Comment by alyssawilk** [comment]
Unfortunately not that I know of :-(
If you can get mirroring and more data about the requests in question I'd be happy to help debug but as-is I'm not sure what to suggest.

**Comment by gongcon** [comment]
Problem is I don't have a test app to capture the requests.
I'm going to have a single node of L2 envoy log on debug level. What specific messages shall I look at?

**Comment by gongcon** [comment]
these are the only messages show up, not meaningful at all.
```
[2020-07-08 00:59:36.568][29][debug][http] [source/common/http/conn_manager_impl.cc:259] [C1127] new stream
[2020-07-08 00:59:36.568][29][debug][http2] [source/common/http/http2/codec_impl.cc:620] [C1127] sent reset code=2
[2020-07-08 00:59:36.568][29][debug][http2] [source/common/http/http2/codec_impl.cc:743] [C1127] stream closed: 2
[2020-07-08 00:59:36.568][29][debug][http] [source/common/http/conn_manager_impl.cc:1791] [C1127][S1814176236361225808] stream reset
```

**Comment by alyssawilk** [comment]
If you can run with  http/1 between levels and a head build, I think you should get a "Sending local reply with details" presumably with details blank, but that'll get you connection info which may get you headers?

**Comment by gongcon** [comment]
Updated inter-communication to HTTP/1.1 between levels. Saw that the DPE errors in access log are highly correlated to the debug message `headers size exceeds limit` in envoy log. After changing the log level to trace, I can see all the headers outputs. Looking at the envoy log, the size of headers is merely a few KiB, yet the number of headers exceeds 100. Errors go away after increasing `max_headers_count`.

From the doc, envoy should response 431 in this case. Looks like a bug to me -- it should not silently error out. The message `headers size exceeds limit` is misleading as well. Is it ok to open an issue ticket?

**Comment by alyssawilk** [comment]
Yeah, agree it should not error out in a way that's this hard to debug.  Glad you've solved the immediate issue!  I'll take on looking into reproducing and fixing the debugability problem (probably next week)

**Comment by alyssawilk** [comment]
I think we're not going to get 431s until we either drop nghttp2 error handling, or at least change the exception error path, but we can definitely get details and have better docs on how to use stats when details don't exist
