### ISSUE TITLE
Feature: DNS filter support for SRV Records

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#11789]
@abaptiste @mattklein123  - Do you think adding support for SRV records would be useful for the DNS filter ? When containers use well known ports, the A or AAAA DNS queries can identify their IP. However, with a dynamic port configuration, the port number is usually unknown and requires discovery through the SRV query.

If this makes sense, can we track the feature in this issue?

**Comment by mattklein123** [comment]
Yeah makes sense to me. I would also love to support SRV in envoy itself for service discovery. There is a long open issue here.

**Comment by abaptiste** [comment]
@mattklein123 Can you assign this to me, please?  I'll start working on this.
