### ISSUE TITLE
Change in behavior of httpConnPoolForCluster

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#11786]
After https://github.com/envoyproxy/envoy/pull/11435 the signature for httpConnPoolForCluster changed semantically, but due to implicit conversion between `Http::Protocol` and `absl::optional<Http::Protocol>` existing usages will compile just fine, but the meaning of the invocation will be slightly different. See https://github.com/envoyproxy/nighthawk/issues/388 for an example of this causing surprising change in behavior.

A similar issue can be seen here: https://github.com/envoyproxy/envoy/blob/master/source/common/tcp_proxy/tcp_proxy.cc#L434-L435 where HTTP/2 will only be selected if protocol resolution resolved to HTTP/2 - if the protocol selection is left to its default value this code will only select HTTP/2 if the `http2_protocol_options` are set on the cluster. One option would be to introduce another `httpConnPoolForCluster`-like function that allows specifying the protocol directly without doing any resolution.

This issue also begs the more general question of how to handle these kind of changes - it is possible that other out of tree code fall into the same category here where the semantic of the code changes under them.

cc @mattklein123 @alyssawilk

**Comment by mattklein123** [comment]
@snowp sorry I'm not 100% following. Did we cause a regression such that we need to revert something? Can you maybe summarize the issue here?

**Comment by snowp** [comment]
I think there's a regression in the TCP over HTTP case: previously the semantics of `httpConnPoolForCluster` meant that we were always selecting HTTP/2, now it's specifying that the downstream protocol is HTTP/2, which means that it would only resolve to HTTP/2 if regular HTTP protocol selection resolves to HTTP/2 /w downstream protocol being HTTP/2.

We can fix this but the bigger question imo is whether we need to be more careful with these kind of changes as it's part of the `include/` API so there's no telling what external usages this might subtly break. One option would be to split the existing `httpConnPoolForCluster` into `resolveHttpConnPoolForCluster` (new behavior) and `httpConnPoolForCluster` (old behavior), but open for ideas.

Not sure if we need to revert this, might be fine to roll forward (unless we cant get it in before the new version is cut)

**Comment by mattklein123** [comment]
> After #11435 the signature for httpConnPoolForCluster changed semantically, but due to implicit conversion between Http::Protocol and absl::optional<Http::Protocol> existing usages will compile just fine, but the meaning of the invocation will be slightly different. See envoyproxy/nighthawk#388 for an example of this causing surprising change in behavior.

Sorry for being dense but from looking at #11435 it's not clear to me what broke here. It seems like passing a downstream protocol would create an optional with a value and do the same thing? Or you are saying that just passing something is different in behavior than what happened previously? Can you provide more explicit detail?

> We can fix this but the bigger question imo is whether we need to be more careful with these kind of changes as it's part of the include/ API so there's no telling what external usages this might subtly break. One option would be to split the existing httpConnPoolForCluster into resolveHttpConnPoolForCluster (new behavior) and httpConnPoolForCluster (old behavior), but open for ideas.

Historically we have not had API stability, but this seems like a potentially bad/confusing case that we probably want to fix (especially since I'm still confused what the problem is).

**Comment by snowp** [comment]
The problem is that the old signature had the caller pass the resolved, actual protocol to use, vs now we pass an optional downstream protocol and perform the protocol resolution. The tcp_proxy code was written to say "always use HTTP/2", but now it's saying "resolve the protocol with HTTP/2 as the downstream protocol". This means that if anyone was using TCP over HTTP/2 with a cluster that would resolve to HTTP/1.1 (e.g. protocol_selection is left at its default value, `http2_protocol_options` not set), it would now attempt to do TCP over HTTP/1.1 instead of HTTP/2.

Since the signature change was `Http::Protocol` -> `absl::optional<Http::Protocol>`, there is no feedback mechanism within the tree or for external users of the API since any invocation of the old signature is also valid for the new one. I think just being aware about this possibility and avoiding semantic changes to the API that doesn't trigger a compilation failure of the old usage would be good enough.

**Comment by mattklein123** [comment]
OK thanks for the explanation. I think I understand now. Agree this is not great and we should probably fix this is if there is a simple way to do so. @alyssawilk any thoughts here?

**Comment by alyssawilk** [comment]
Given TCP over HTTP/1 isn't supported, can we detect it early enough to just fail if someone specifies that configuration?  Given all the tunneling stuff is new, I think we can get away with tweaking config validation if it's plausible programmatically.

**Comment by snowp** [comment]
I think that's definitely an option, though it would prevent people from using the same cluster for TCP over HTTP/2 + regular HTTP proxying (no clue if this is a valid use case). If we pass `absl::nullopt` it should always use HTTP/2 as long as `http2_protocol_options` is set, so maybe that's enough?

Not sure if we want to do anything wrt making sure that external use cases don't accidentally pick up this new behavior when they pull in latest master?

**Comment by alyssawilk** [comment]
hm, I definitely thing we want to get something in before we cut the release - ping me on slack today and let's sort out a plan?
