### ISSUE TITLE
Question: gRPC API's timeout not considered?

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#11790]
Any gRPC api's that get proxied via Envoy does not honor the grpc time out parameter in the header.

For example, If the timeout is 100 seconds from the client, envoy times out at the default 15 seconds value.
Wondering why gRPC requests do not honor the timeout specified in the call?

**Comment by nezdolik** [comment]
@sumukhs make sure that you have `max_grpc_timeout` configured: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout, otherwise grpc-timeout header would not be considered.

**Comment by sumukhs** [comment]
Thanks @nezdolik . I'll try that out
