### ISSUE TITLE
stats: need mechanism for finding a stat by name in production code

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#11799]
In reviewing https://github.com/envoyproxy/nighthawk/pull/390 I realize that we have no great way to robustly look up a stat by name in production code, other than in the context of the code that created it.

One scenario I have in mind is from https://github.com/envoyproxy/nighthawk/pull/390 where we are using config to identify a gauge name to compute an injected delay for a test server. But was this gauge created with a mix of dynamic segments? Interfaces do not specify this, and implementations may change.

In tests we deal with this by keeping expensive maps from strings to counters, gauges, and histograms.

I wanted to share my thoughts on how I think we can solve this in production as well. The lookup will be expensive, but it can be atomic and done once. Roughly:
```
class GaugeReference {
public:
 GaugeReference(Scope&, absl::string_view name) {}
 absl::optional<uint64> value() {
   Gauge* gauge = gauge_.get([this](return slowlyFindGauge(); };
   if (gauge == nullptr) {
     return absl::nullopt;
   }
   return gauge->value();
}

private:
  Scope::Scope& scope_;
  std::string name_;
  Gauge* slowlyFindGauge() { 
     ... iterate through all gauges in the scope looking for one where gauge.name() == name_
    return gauge; // possibly nullptr
  }
    
  AtomicPtr<Gauge, AtomicPtrAllocMode::DoNotDelete> gauge_;
};
```

**Comment by jmarantz** [comment]
@oschaaf @mattklein123 @snowp

**Comment by mattklein123** [comment]
@jmarantz sorry not 100% following. Can you describe the use case?

**Comment by jmarantz** [comment]
Filter A defines a gauge.
Filter B can be configured to change its behavior based on some arbitrary gauge defined elsewhere in the code, and all we have is a string name for the gauge.

Currently there is no convenient robust mechanism to look up an existing gauge by name, that works for names that may have dynamic components.

**Comment by mattklein123** [comment]
Ah I see. OK makes sense.

**Comment by jmarantz** [comment]
Further thoughts: the atomic ref wrapper methodology above could ideally use something like Scope::iterateCounters(), iterateGauges(), etc, to reduce the memory churn required to find a stat.

Initially it could be built on Store::counters(), Store::gauges(), without enduring the remarkable toil of adding a family of new Scope APIs (there are lots of implementations of Scope).

**Comment by antoniovicente** [comment]
I think that the implementation in #12128 does a linear scan over stats, which makes it unsuitable for use in prod code outside some very limited cases.  This internal API should be used with caution.
