### ISSUE TITLE
"mode" setting on config.core.v3.Pipe has no apparent effect

### ISSUE THREAD

**Issue by gvwirth** [envoyproxy/envoy#11809]
Hello,

We're setting up a Listener to use a unix socket, and are attempting to set the mode of the pipes to (octal) 666. We've set this config on the listener (this is copy/pasted from a config dump via the admin web interface):

      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "listener_http",
       "address": {
        "pipe": {
         "path": "/run/copilot-http",
         "mode": 438
        }
       }, ...

However the resulting socket at /run/copilot-http has a mode of 755 (which is umask default):

    gwirth@Garets-MacBook-Pro copilot-v2 % docker exec -it 76f00264e1b3 ls -la /run
    total 32
    drwxr-xr-x 1 root root 4096 Jun 29 22:07 .
    drwxr-xr-x 1 root root 4096 Jun 29 22:07 ..
    srwxr-xr-x 1 root root    0 Jun 29 22:07 copilot-http

We are running this inside of the official Envoy container, version 1.14.1. Is there extra config we're missing, or another setting that's overriding the mode of the socket perhaps?

Thank you!

**Comment by yanavlasov** [comment]
This is potentially a bug. I think in some cases the `mode` specified by configuration is ignored. However I'm unsure if this covers your case.
Would you be able to provide smallest configuration that recreates the problem, please?

**Comment by gvwirth** [comment]
[Archive.zip](https://github.com/envoyproxy/envoy/files/4853577/Archive.zip)
Here is a config that reproduces the issue. Thank you for looking into this and please let us know if there is more information we can provide.
