### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Ccaomei** [envoyproxy/envoy#11814]
When I compiled the source code of Envoy, I encountered this error. I had installed Autoconf and Automake and still reported this error. Please help me check the problem.My error report is as follows:

bazel build //source/exe:envoy-static  --verbose_failures
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/weilh/envoy_source/envoy/envoy-1.14.0/tools/bazel.rc
DEBUG: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
INFO: Call stack for the definition of repository 'com_github_gperftools_gperftools' which is a http_archive (rule definition at /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /home/weilh/envoy_source/envoy/envoy-1.14.0/bazel/repositories.bzl:760:5
 - /home/weilh/envoy_source/envoy/envoy-1.14.0/bazel/repositories.bzl:129:5
 - /home/weilh/envoy_source/envoy/envoy-1.14.0/WORKSPACE:13:1
INFO: Repository 'com_github_gperftools_gperftools' used the following cache hits instead of downloading the corresponding file.
 * Hash '97f0bc2b389c29305f5d1d8cc4d95e9212c33b55827ae65476fc761d78e3ec5d' for http://192.168.49.112:8080/123/gperftools-2.7.90.tar.gz
If the definition of 'com_github_gperftools_gperftools' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_github_gperftools_gperftools':
   Traceback (most recent call last):
        File "/home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "/home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, in patch
                fail(<1 more arguments>)
Error applying patch command ./autogen.sh:
configure.ac:172: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /home/weilh/envoy_source/third_package/autoconf/install/bin/autoconf failed with exit status: 1
ERROR: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/envoy/bazel/foreign_cc/BUILD:10:1: @envoy//bazel/foreign_cc:gperftools_build depends on @com_github_gperftools_gperftools//:all in repository @com_github_gperftools_gperftools which failed to fetch. no such package '@com_github_gperftools_gperftools//': Traceback (most recent call last):
        File "/home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
                patch(ctx)
        File "/home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, in patch
                fail(<1 more arguments>)
Error applying patch command ./autogen.sh:
configure.ac:172: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /home/weilh/envoy_source/third_package/autoconf/install/bin/autoconf failed with exit status: 1
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.152s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 513 targets configured)
    Fetching ...ang_x_tools; Cloning c9f9432ec4b21a28c4d47f172513698febb68e9c of https://go.googlesource.com/tools
    Fetching ...g_protobuf; Cloning 6c65a5562fc06764971b7c5d05c76c75e84bdbf7 of https://github.com/golang/protobuf

**Comment by dio** [comment]
Seems like it is a fetching problem due to network (or cache) error.

Two relevant lines:

> ERROR: An error occurred during the fetch of repository 'com_github_gperftools_gperftools':

> ERROR: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/envoy/bazel/foreign_cc/BUILD:10:1: @envoy//bazel/foreign_cc:gperftools_build depends on @com_github_gperftools_gperftools//:all in repository @com_github_gperftools_gperftools which failed to fetch.

1. I can see you did this behind a proxy. Check on that?
2. `bazel clean --expunge` before runnning `bazel build` again, just in case the cache is broken.

**Comment by Ccaomei** [comment]
> Seems like it is a fetching problem due to network (or cache) error.
> 
> Two relevant lines:
> 
> > ERROR: An error occurred during the fetch of repository 'com_github_gperftools_gperftools':
> 
> > ERROR: /home/weilh/.cache/bazel/_bazel_weilh/2dd9409ed716891262986af31b7f0943/external/envoy/bazel/foreign_cc/BUILD:10:1: @envoy//bazel/foreign_cc:gperftools_build depends on @com_github_gperftools_gperftools//:all in repository @com_github_gperftools_gperftools which failed to fetch.
> 
> 1. I can see you did this behind a proxy. Check on that?
> 2. `bazel clean --expunge` before runnning `bazel build` again, just in case the cache is broken.

Sorry, I don't think this is an Error. The first thing that should be addressed is "Error applying patch command./autogen.sh:
Configure. Ac :172: error: possibly undefined macro: AC_PROG_LIBTOOL
Legitimate, please use m4_pattern_allow If this Token and others are legitimate.
See the Autoconf documentation.
Autoreconf: / home/weilh/envoy_source/third_package/autoconf/install/bin/autoconf failed with the exit status: 1"

**Comment by dio** [comment]
OK. That particular error is related to missing `libtool`. Have you followed this https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers especially the installing deps part?
