### ISSUE TITLE
extend route's hashing policy to support hashing on a regex substitution

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#11811]
Currently, the hash policy for a route supports hashing on a header's entire value:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/route/v3/route_components.proto#L609

We have a use case in which we'd like to hash on a regex substitution on `:path` (e.g.: to extract a given id). 

There's two options I can think of:

1) add support for hashing on a metadata key (reusing what was added in ##11698)

2) add support for applying `type.matcher.v3.RegexMatchAndSubstitute` on a header and then hashing on that result

Any preferences/thoughts?

cc: @htuch @snowp @mattklein123

**Comment by htuch** [comment]
I think hashing on a match group result (i.e. (2)) sounds reasonable, it seems this capability would be generally useful, e.g. extracting out some structured information from a header to hash on.

**Comment by mattklein123** [comment]
+1 on a regex hash on a header.

**Comment by rgs1** [comment]
Ok, I'll send a PR in a bit.
