### ISSUE TITLE
example/cors: Front envoy service unable to start in frontend and backend

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#11836]
Front envoy fails on both frontend and backend with the same log given below.

`front-envoy_1       | [2020-07-01 11:36:32.046][8][critical][main] [source/server/server.cc:101] error initializing configuration '/etc/front-en
voy.yaml': unable to open file '/var/log/access.log': Permission denied
front-envoy_1       | [2020-07-01 11:36:32.047][8][info][main] [source/server/server.cc:704] exiting
front-envoy_1       | unable to open file '/var/log/access.log': Permission denied`

**Comment by dio** [comment]
Have you tried to re-pull the images again? Since this https://github.com/envoyproxy/envoy/commit/504d78bac735e03e733adea6475d31702334e5e4 commit should fix that.

**Comment by dio** [comment]
Seems like the example needs to run as `docker-compose build --pull` so the base images will be re-pulled.

**Comment by mk46** [comment]
@dio sorry, I think the issue is due to running envoy without root.

**Comment by yanavlasov** [comment]
@phlax is it related to unrooting docker images?

**Comment by phlax** [comment]
yep @mk46 's PR will fix the problem in the example - by setting the logging to /dev/stdout. 

Im thinking we should add a doc on setting permissions for file logging.

Im also wondering what the default logging target is

**Comment by dio** [comment]
I would argue, the best practice on logging inside a container is through stdout and stderr.

Some references:

1. https://www.datadoghq.com/blog/docker-logging/
2. https://platform9.com/blog/kubernetes-logging-best-practices/
3. https://timber.io/blog/collecting-application-logs-on-kubernetes/

**Comment by phlax** [comment]
> I would argue, the best practice on logging inside a container is through stdout and stderr.

i couldnt agree more - but there are times/reasons that someone would want to log to a file. 

In this case, if we dont document the right way to log to a file, they will probably set `ENVOY_UID`=`0` as a workaround

**Comment by phlax** [comment]
...also, that was partly the reason i was asking about the default logging target - because in a container it *should* be `/dev/stdout` etc

**Comment by phlax** [comment]
checking my dev configs - i think it is `/dev/stdout` as i havent set it and that is what it does

**Comment by dio** [comment]
@phlax feel free to submit a PR on documenting that further 🙂. Thanks!
