### ISSUE TITLE
Docker image for 1.12.5 is missing

### ISSUE THREAD

**Issue by i0rek** [envoyproxy/envoy#11838]
Hello,

thank you very much for maintaining envoy! I noticed that the docker image for envoy 1.12.5 is missing and I was wondering if that is known already.

Thanks!

**Comment by mk46** [comment]
@i0rek Hi, I think envoy 1.12.5 is changed to 1.12-latest. Please check https://hub.docker.com/r/envoyproxy/envoy/tags for more details.

**Comment by i0rek** [comment]
`v1.12-lastest` was updated 23 days ago, I don't think that is the version that was released yesterday. Thanks for helping though!

**Comment by i0rek** [comment]
https://hub.docker.com/layers/envoyproxy/envoy/v1.12.5/images/sha256-7f10a15462290dc64f774e3aec04fecbae736cf13e2368b539d9444ee36d4b92?context=explore is released!
