### ISSUE TITLE
Proposal: Add a default value to ratelimit dynamic_metadata action

### ISSUE THREAD

**Issue by clarakosi** [envoyproxy/envoy#11849]
**Description**: We recently added dynamic_metadata action (issue #11593) that gets descriptor information from the metadata. As currently built the dynamic_metadata action looks for information in the dynamic metadata and if isn’t there it stops and does not build the descriptor. We now realize there may be instances where the information isn’t there because of the failure of another filter, it never existed or some other edge case. So instead of letting the descriptor fail, we would like to include an optional default string value for instances where the information is not in the dynamic metadata. 

The updated schema would look like:
 
```yaml
- dynamic_metadata:
    descriptor_key: “…”
    default: “…”
    metadata_key:
      key: “…”
      path:
        - key: “…”
```

**Comment by mattklein123** [comment]
Makes sense to me, thank you.
