### ISSUE TITLE
FractionalPercent when using with RouteMatch

### ISSUE THREAD

**Issue by belyalov** [envoyproxy/envoy#11874]
**_Title:_** Log debug/info/whatever message when `FractionalPercent.numerator` greater than `FractionalPercent.denominator`
**_Description:_** When using `FractionalPercent` with `RouteMatch` it is possible to mess up with values on `denominator` / `numerator` so the underlying condition
```cpp
(random_value % denominator) < numerator
```
Will be always evaluated to `true` because of `numerator` exceeds `denominator`. It becomes hard to debug why configuration does not work (no logs, just shows that clusterN has been selected).

Do you guys think it is make sense to add some kind of logging to simplify configuration debuggability?
If so I can add this.

Thanks

**Comment by snowp** [comment]
Alternatively we could add in configuration validation that will reject configuration where numerator > denominator, unless there are use cases where you'd want to do that?

**Comment by belyalov** [comment]
This is not clear to me:
- route configuration simply depends on runtime *key*, basically string, seems nothing to validate here
- update runtime values through `rtds` or any other methods could not be validated as well (simply ignore unacceptable values?)

**Comment by snowp** [comment]
I see, this is about using RuntimeFractionalPercent, not a FractionalPercent proto configured via xDS. 

Seems like logging the numerator/denominator as debug/trace would be the best way to handle this since there is no validation framework around runtime values.

**Comment by belyalov** [comment]
Ok, I'll take care of... :)
