### ISSUE TITLE
Lua Envoy Filter , parsing of response_body is not working in lua

### ISSUE THREAD

**Issue by ajoysinha** [envoyproxy/envoy#11876]
I am trying to implement lua filter to communicate with OPA ( open policy agent ) [ other authorization server has some issue , not working ], hence trying to implement lua filter.

I am able to configure lua filter to communicate with OPA. and getting the response back in response_body.

response_body output is as below 
```
{"decision_id":"b4867d1a-2316-4e83-ab5e-20300e4ad57e","result":false}
```
I am looking some way to extract the value from response_body. but do not get any way to do the same. 
I need to do some processing on the result value here.

I have tried to import json also, but it fails with error. 

any suggestion will make my day.

my code is as below 
```
inlineCode: |
        
           function envoy_on_request(request_handle)
                 
              request_handle:headers():add("Content-Type","application/json")
              
              local response_headers, response_body = request_handle:httpCall(
              "outbound|8181||auth.local",
              {
                [":method"] = "POST",
                [":path"] = "/v1/data/opa/meddetails/allow",
                ["Authorization"] = request_handle:headers():get("Authorization"),
                ["Content-Type"] = "application/json",
                [":authority"] = "auth.local" 
              },
              "",
              5000)
              
              for key, value in pairs(response_headers) do
                request_handle:logCritical(key .. " " .. value)
              end
               
              request_handle:logCritical(response_body)
             
              request_handle:logCritical("------------------")
              
            end
            function envoy_on_response(response_handle)
              response_handle:headers():add("x-this","works")
            end
```

**Comment by ajoysinha** [comment]
Can anybody help me on this ..

**Comment by dio** [comment]
@ajoysinha it seems like your request is successful, but you can't log the body?

I'm not sure if the following example could help you: https://github.com/dio/envoy-lua-opa
