### ISSUE TITLE
x-envoy-max-retries header is ignored with 5xx retry policy

### ISSUE THREAD

**Issue by vinzo99** [envoyproxy/envoy#11883]
Description:

When using a retry policy on 5xx response, it seems that x-envoy-max-retries header is always ignored, whether retry policy is configured in envoy.yaml or with x-envoy-retry-on header.

The following tests have been reproduced in our lab order to simulate a customer configuration. We run Envoy 1.14.1 with a sample envoy.yaml, that redirects to a dummy server that just responds 500 Internal Server Error. Retry_policy was either set in envoy.yaml, or with x-envoy headers, or both. Here are the tests :

1°) retry_policy with 5 num_retries and no x-envoy headers : 5 retries performed
2°) retry_policy with 5 num_retries and "x-envoy-max-retries: 2" : 5 retries performed
3°) retry_policy with 2 num_retries and "x-envoy-max-retries: 5" : 2 retries performed
4°) no retry_policy and "x-envoy-max-retries: 5" : no retry performed at all

Tests 2-3-4 have been run again adding "x-envoy-retry-on: 5xx", same behaviour.

Envoy version is 1.14.1.

The headers are set using curl -H and are correctly observed in the access log.

I can provide specific logs on request for the selected scenario.

Thanks

**Comment by yanavlasov** [comment]
This sounds like a bug. By any chance can you run the same test with 1.15 or master to confirm this is still a problem, please?

**Comment by vinzo99** [comment]
The same tests have been run with 1.15.0, same result.

**Comment by lretrain91** [comment]
hi i'm a colleague of @vinzo99.
what should we do now since 1.15.0 is not fixing the issue ?

**Comment by lretrain91** [comment]
Hello, any new ?

**Comment by VassoSof** [comment]
Hello @yanavlasov,

Any plans for that? 

Regards,
Vasso

**Comment by VassoSof** [comment]
@yanavlasov  Any update on this?

@vinzo99  as to be notified

**Comment by va1erian** [comment]
Hello,

we were able to make this feature work by commenting the following line : https://github.com/envoyproxy/envoy/blob/b33f3cc74ccd0f6e9c01f5ed21bd7d7510646356/source/common/http/conn_manager_utility.cc#L182

However I assume this code is there for a reason... is there something we're missing?

**Comment by danielkwinsor** [comment]
I would like to add that the internal client requirement should be added to documentation for all these headers.  It is present for a few headers, but no such "internal-only client" stipulation is mentioned for retry in general: https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/http/http_filters/router_filter#http-headers-consumed-from-downstreams

**Comment by vinzo99** [comment]
Reviving thread to remain open.

**Comment by yanavlasov** [comment]
Sorry for not responding sooner. I've reread the issue and it does not look like a bug. Envoy allows x-envoy-... headers from trusted downstream servers only. It uses the combination of the [use_remote_address in the HTTP connection manager](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto) value of the XFF header and the IP address of the peer to determine if request is trusted or untrusted. See more info [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing)

It looks like in your case Envoy does not consider the request as "trusted" and strips the x-envoy-... headers before the request is proixied.
