### ISSUE TITLE
stack_decode.py does not work

### ISSUE THREAD

**Issue by vikaschoudhary16** [envoyproxy/envoy#11889]
Description:
As mentioned in the [code comments]( https://github.com/envoyproxy/envoy/blob/master/tools/stack_decode.py#L8-L9), there are two ways to use `stack_decode.py` to translate addresses in the backtrace to the file and line numbers. I have tried both the approaches. i.e making it read from the stdin and also running envoy under the stack_decode.py, in either case, addresses are not getting translated.

```
 15 ?        S      0:00 /usr/bin/python3 /usr/local/bin/stack_decode.py /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster details.bookinfo --service-node sidecar~10.60.1.252~det
     16 ?        Sl     0:01 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster details.bookinfo --service-node
```
but still in the backtrace logs address is not getting converted to file and line number
```
critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:71] Backtrace (use tools/stack_decode.py to get line numbers):
2020-07-03T19:23:29.984196Z	critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:75] #0: std::__1::__function::__func<>::operator()() [0x5564bb12b48f]
2020-07-03T19:23:29.984201Z	critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:75] #1: Envoy::Extensions::Common::Wasm::Context::onRequestHeaders() [0x5564bb94e464]
2020-07-03T19:23:29.984206Z	critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:75] #2: Envoy::Extensions::Common::Wasm::Context::decodeHeaders() [0x5564bb950aea]
2020-07-03T19:23:29.984209Z	critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:75] #3: Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders() [0x5564bc968a79]
2020-07-03T19:23:29.984212Z	critical	envoy backtrace	[./extensions/metadata_exchange/backtrace.h:75] #4: 
```
I am also sure that i built envoy with debug symbols.

**Comment by lizan** [comment]
@vikaschoudhary16 If the binary doesn't contains debug symbol, there's no way to get line number, is it a binary with symbols?

**Comment by vikaschoudhary16** [comment]
@lizan i am sure binary have debug symbols:
```
root@instance-2:/home/vikas/proxy# ls -ltr bazel-bin/src/envoy/envoy
-r-xr-xr-x 1 root root 1828600064 Jul  4 13:11 bazel-bin/src/envoy/envoy
root@instance-2:/home/vikas/proxy# file bazel-bin/src/envoy/envoy
bazel-bin/src/envoy/envoy: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

**Comment by drao9** [comment]
We are facing the same issue. Any finding? @vikaschoudhary16

**Comment by vikaschoudhary16** [comment]
Not yet!

**Comment by howardjohn** [comment]
I think its the https://github.com/envoyproxy/envoy/blob/main/tools/stack_decode.py#L28 is looking for a regex that doesn't match Istio's logging format

**Comment by ashstarry** [comment]
docker exec -it ecs-envoy-container /usr/bin/python3 /tools/stack_decode.py /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml

**Comment by ashstarry** [comment]
docker cp path/to/log.txt ecs-envoy-container:/log.txt

**Comment by ashstarry** [comment]
docker exec -it ecs-envoy-container /usr/bin/python3 /tools/stack_decode.py -s /usr/local/bin/envoy < /log.txt
