### ISSUE TITLE
envoy reset downstream connections without sending any data to upstream

### ISSUE THREAD

**Issue by andrewshaoyu** [envoyproxy/envoy#11899]
Description:

1. Downstream using java http client get some connection errors (connection reset by peer),this maybe envoy reset the connection
1. Then tcpdump in envoy and downstream
1. From the pcap, downstream connect to envoy's port 80 with a random port after shakehands, then downstream make a http post request,envoy side reply with ack. 
1. After 500ms, envoy reply to downstream with [RST,ACK]
1. During the 500ms gap, did not find any data to upstream with the POST body.
1. From downstream side, get the POST request to envoy side, ack from envoy side, finally get [RST,ACK] from envoy.

Enviroment
1. istio 1.3.6,envoy version is 1.12.0
1. use envoy as a edge dateway
1. open the envoy logging ,http=debug,connection=debug. did not find any error

Question:
1. Does anyone know about the problem?

**Comment by yanavlasov** [comment]
Were there any logs messages at all? It maybe that connection does not reach envoy at all, due to misconfiguration.

**Comment by andrewshaoyu** [comment]
what's logs could be useful? there too many logs.

connection must be connected, kernel didnot pass the data to envoy or there are some problems during the connection close()

**Comment by yanavlasov** [comment]
Ok, let me ask this then. Does this problem happen to all client requests or only to some requests?

**Comment by andrewshaoyu** [comment]
Finally，i find the problem,client idletimeout is greater than envoy idletimeout.
