### ISSUE TITLE
Can filter decodeHeaders be called multiple times? 

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#11926]
We have code that inserts into FilterState in the decodeHeaders call, which crashes if decodeHeaders is called multiple times in the same test without resetting the filter state. Should we be handling that "exists in filterstate" situation in code? Or is decodeHeaders guaranteed to never be called twice for a given filterchain. It does have an `end_stream` variable similar to decodeData, but looking at the code it looks like that just defines whether to expect a body or not -- it seems decodeHeaders expects a complete header map.

**Comment by wbpcode** [comment]
The 'decodeHeaders' of a filter instance will  never be called twice. But for the robustness of the code, I still recommend that you deal with the 'exists in filterstate' situation.
