### ISSUE TITLE
Follow ups on gRPC<->JSON transcoder filter

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#1192]
- Test coverage 100%
- Factor out building PathMatcher.

**Comment by mattklein123** [comment]
I think this is complete. Closing.

**Comment by mattklein123** [comment]
@lizan I'm going to reopen this as I just checked and there is still missing coverage on a few error paths. Please cover them when you do more features on the filter.

**Comment by lizan** [comment]
Yes there are a few TODOs there. Will working on it soon.

**Comment by mattklein123** [comment]
Closing as stale and not worth tracking.
