### ISSUE TITLE
TCP Proxy turn off nat

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#11976]
We are using TCP proxy with Envoy. However, when traffic travels through proxy, Envoy replacing source IP with its own. We need help on preserving original source IP. 

The upstream server is an F5 balancer in network A, clients are in network B and where envoy is running is on network C

if me client go directly to the upstream server I can see the source ip correctly, but if I go to envoy which is in another network and route me to the upstream I dont see the correct source ip, I see the envoy ip

In F5 you can disable NAT Translation in order to get the real source IP by modifying "Source address translation" to None, how can I do the same in envoy when using tcp_proxy?

I tried what is on this link https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency.html?highlight=transparency
But that doesnt help me to what I need because clients can only connect to network B and only envoy can connect to upstream

**Comment by yanavlasov** [comment]
Duplicate of #11942
