### ISSUE TITLE
Change grpcStatus and grpcMessage in the response when encoding data in Envoy::Http::StreamEncoderFilter

### ISSUE THREAD

**Issue by aydanjiwani** [envoyproxy/envoy#11982]
It is possible to send a response with the sendLocalReply method in StreamDecoderFilterCallbacks, but there is no equivalent method in the StreamEncoderFilterCallbacks. Attempted to call sendLocalReply  method of StreamDecoderFilterCallbacks inside encoderTrailers, but received runtime error - something like response header is not in the scope. Is there another way?

**Comment by mattklein123** [comment]
You can just change the headers directly?
