### ISSUE TITLE
extensions/filters/http/header_to_metadata coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#11994]
Hello,
The Envoy project has recently started collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, extensions/filters/http/header_to_metadata, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in [test/per_file_coverage.sh](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh) 
Thanks!

**Comment by rgs1** [comment]
Thanks! I'll send a PR at some point today.

**Comment by rgs1** [comment]
It's possible we are already good per the (updated?) report:

```
source/extensions/filters/http/header_to_metadata |   |   | 98.4 % | 240 / 244 | 97.0 % | 32 / 33
-- | -- | -- | -- | -- | -- | --
 ```

checking...

**Comment by alyssawilk** [comment]
yeah, sorry, just reran and the source is out of date.  Sorry about the noise!
