### ISSUE TITLE
extensions/filters/network/direct_response coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#11998]
Hello,
The Envoy project has recently started collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, extensions/filters/network/direct_response, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in [test/per_file_coverage.sh](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh) 
Thanks!

**Comment by asraa** [comment]
@jianwen612 if you find yourself already diving in to network filter testing, you may be able to help close this issue (and other network/filters). this coverage reports is over unit and integration tests

**Comment by jianwen612** [comment]
> @jianwen612 if you find yourself already diving in to network filter testing, you may be able to help close this issue (and other network/filters). this coverage reports is over unit and integration tests

Oh it happens that I am also working on direct_response filter now. There is no unit test for this filter so the coverage it low. I think I can add a simple unit test here the next week.
