### ISSUE TITLE
extensions/filters/udp/dns_filter coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#12004]
Hello,
The Envoy project has recently started collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, extensions/filters/udp/dns_filter, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in [test/per_file_coverage.sh](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh) 
Thanks!

**Comment by abaptiste** [comment]
From the 8-28-2020 coverage report, the dns_filter has 93.9% coverage

Many changes for https://github.com/envoyproxy/envoy/issues/11789 were targeted for increasing coverage.  I feel this issue can be resolved.

**Comment by mattklein123** [comment]
@abaptiste in general we want 97%. Can you get up that high and then remove the exclusion?

**Comment by abaptiste** [comment]
Ack. Will continue to work on coverage.
