### ISSUE TITLE
[security] Keeping embargoed patches up to HEAD during early disclosure

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#12036]
Title: Keeping embargoed patches up to HEAD during early disclosure

Description:

Hi all, I wanted to open a community issue up to get some feedback and hopefully reduce the amount of work we're all doing.

During the weeks coming up to a security release, private distributors receive patches against main branch. These patches have the potential to go out-of-sync, especially when there are large refactors in the code. We've found it to be a bit of a headache to keep these patches up to date, so I wanted to bring this up as an issue for discussion and solicit some feedback.

* If you are on the private distributors list, do you build envoy from HEAD during the emargo period? 
* What tooling do you currently use to update patches? 
* Would you benefit from patches shared against HEAD more frequently, or are willing to share work?
* Anything else?

@envoyproxy/security-team

**Comment by mattklein123** [comment]
My 2c on this is that the security team and patch authors should rebase the patches weekly (?) and send them out to the list until the release. This would also help the security team with the scramble at the end to rebase all the patches which happens every time.
