### ISSUE TITLE
Security Assessment

### ISSUE THREAD

**Issue by msample** [envoyproxy/envoy#1204]
If Envoy is being positioned as an edge-capable router, it would be ideal to have some security assessment of the code.  Could we engage some volunteer security experts to help build a repeatable process for security review and some CI fuzzing/VA/etc tests?  

Ideally this process and tools could be applied to contributed filters as well such we don't end up with 'trusted' (e.g. from core committers) and 'unknown' filter classifications.

**Comment by mattklein123** [comment]
Not really sure what I/we can concretely do here, but will leave this open to track. Envoy is already getting attention from security experts at least two "very large companies" (Lyft is not a "very large company"). Presumably if issues are found they will be reported and fixed. If anyone wants to volunteer for something more official let me know.

**Comment by msample** [comment]
I will tap some of my security friends to see if we can setup some CI tests for fuzzing etc. E.g. with AFL.  Thx for keeping this open - hopefully they will comment here.

**Comment by mattklein123** [comment]
Fuzzing is going to be worked on by G at some point. I think @PiotrSikora is going to tackle this. https://github.com/lyft/envoy/issues/508 tracks.

**Comment by mattklein123** [comment]
CNCF is going to sponsor something official here. We are also looking into setting up a bug bounty. Assigning over to @caniszczyk.

**Comment by mattklein123** [comment]
This has been done. We will make the report available publicly soon.

**Comment by msample** [comment]
Awesome, I look forward to reading the report. Thank you.

**Comment by mattklein123** [comment]
Yes

**Comment by caniszczyk** [comment]
It's also here: https://github.com/envoyproxy/envoy#security-audit

https://github.com/envoyproxy/envoy/blob/master/docs/SECURITY_AUDIT.pdf
