### ISSUE TITLE
Feature Request: Configure consistent hashing balancing behavior

### ISSUE THREAD

**Issue by mattrobenolt** [envoyproxy/envoy#12066]
In haproxy, there is a configuration [`balance`](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#balance) that allows specifying attributes other than strictly the URL to be used for balancing. Commonly this is used to route based on an HTTP header, a specific url parameter, or the remote IP.

I've been trying to find an existing issue in Envoy or somewhere in existing configuration that'd allow this, with no luck.

For my specific use case, I'd need to use an HTTP header for routing, but the others are just nice to haves based on haproxy feature set.

Thanks!

**Comment by junr03** [comment]
take a look at the route matching here https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch and let us know if you are missing specific matchers you'd like to see

**Comment by mattrobenolt** [comment]
Yes, those seem applicable. So the logic already exists for routing, it’d be nice to use the same RouteMatch structs then for consistent hashing behavior.
