### ISSUE TITLE
Outlier detection prevents failing Active HealthChecks endpoints to get ejected.

### ISSUE THREAD

**Issue by bvandewalle** [envoyproxy/envoy#12076]
I'm not sure if this is the intended behaviour as I could not find that much documentation on activating both Active and Passive HC together.

**What I'm seeing:** 
I have 3 endpoints defined on a cluster. 1 of them is failing the active HTTP healthChecks (503 return code) and this is confirmed on the HealthCheck logs. I would expect that endpoint to get removed but I see my traffic still being proxied to it.
Digging further, I realized that as part of my OutlierDetection configuration I have a `MaxEjectionPercent` left to the default `10` (%) .It seems that this parameter defined for outlierDetection prevents the removal of an endpoint for ActiveHealthChecks.

**What I would expect:**
I would expect the `MaxEjectionPercent` to only affect Passive HealthChecks. Therefore, if Active HealthChecks are failing for a specific endpoint, I would expect that endpoint to be removed regardless of the ratio defined in `MaxEjectionPercent` 

My configuration:

`OutlierDetection`:
```
		OutlierDetection: &cluster.OutlierDetection{
			ConsecutiveGatewayFailure:          &wrappers.UInt32Value{Value: 3},
			EnforcingConsecutiveGatewayFailure: &wrappers.UInt32Value{Value: 100},
			EnforcingConsecutive_5Xx:           &wrappers.UInt32Value{Value: 0},
			BaseEjectionTime:                   &duration.Duration{Seconds: 60},
		},
```

`Active HealthChecks` :
```
		HealthChecks = []*core.HealthCheck{{
			Timeout:            &duration.Duration{Seconds: 4},
			Interval:           &duration.Duration{Seconds: 60},
			UnhealthyThreshold: &wrappers.UInt32Value{Value: 2},
			HealthyThreshold:   &wrappers.UInt32Value{Value: 2},
			HealthChecker: &core.HealthCheck_HttpHealthCheck_{
				HttpHealthCheck: &core.HealthCheck_HttpHealthCheck{
					Host: serviceName,
					Path: "/",
					ExpectedStatuses: []*envoy_type.Int64Range{
						{
							Start: 200,
							End:   310,
						},
					},
					RequestHeadersToAdd: []*core.HeaderValueOption{{
						Header: &core.HeaderValue{
							Key:   "user-agent",
							Value: "Ingress healthchecks",
						},
						Append: &wrappers.BoolValue{Value: false},
					}},
				},
			},
			EventLogPath: "/var/log/envoy/envoy_hc.log",
		}}
``

**Comment by snowp** [comment]
I suspect you're hitting the panic threshold: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/panic_threshold

**Comment by bvandewalle** [comment]
Thanks @snowp  it looks like it might have been the panic treshold indeed.
