### ISSUE TITLE
Ability to configure "max_connection_duration" for TCP traffic

### ISSUE THREAD

**Issue by nrjpoddar** [envoyproxy/envoy#12077]
*Title*: *Configuration setting for maximum duration for a connection for TCP traffic*

*Description*:
For TCP listeners/clusters it's useful to have a maximum connection duration setting which can force rebalancing/re-establishing of connections for long lived sessions. Additionally, it can be used as a good practice measure for edge proxies from keeping a connection resource consumed for a long time.

[*Relevant Links*:]
* HTTP protocol options support [max_connection_duration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#core-httpprotocoloptions) which is similar to this request but only applicable for HTTP listeners/clusters.

**Comment by mk46** [comment]
Hi @nrjpoddar, Are you working on this issue. If not then I would like to work on it.

**Comment by nrjpoddar** [comment]
I'm not @mk46, please go ahead and assign it yourself. Thanks!

**Comment by mk46** [comment]
@alyssawilk  Can we close this issue? Thanks!.

**Comment by nrjpoddar** [comment]
Thanks for implementing this feature @mk46 and Envoy team!
