### ISSUE TITLE
Setting "user_agent_name" field in bootstrap config

### ISSUE THREAD

**Issue by coodie** [envoyproxy/envoy#12091]
I tried to set ["user_agent_name"](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-node) in bootstrap json passed to envoy, but it didn't seem like value passed to this field appeared in config_dump and it always appeared as "envoy" regardless of what I put there. Reading the [code](https://github.com/envoyproxy/envoy/blob/master/source/server/server.cc#L361) it seems like this field cannot be overriden and it's always "envoy". Is there a specific reason for this?

**Comment by dio** [comment]
I see no harm to make it configurable (can be overridden). But I don't have all of the contexts either. This is introduced in https://github.com/envoyproxy/envoy/pull/9301/files#diff-3eda0ff865e056f19775ad626a5c2920R308. 

re: context, probably @yanavlasov has the answer.

**Comment by coodie** [comment]
I tried to add "user_agent_version" as well, but it suffers [from the same problem](https://github.com/envoyproxy/envoy/blob/master/source/server/server.cc#L362). Except that one cannot have "user_agent_build_version" and "user_agent_version" at the same time, and this code writes to "user_agent_build_version" effectively overriding "user_agent_version" - as it changes the type of that field.

**Comment by lizan** [comment]
Those fields are not intended to be configurable from via bootstrap JSON/YAML. Those fields are intended to notify what is the user agent (in this case, envoy) and what it is capable of to control-plane, so your control-plane know what binary (xDS client implementation) it is serving config to. i.e. If you implemented different xDS client (such as gRPC), you should set them in your implementation.

It's unfortunate that we shared the same `Node` message definition for bootstrap configuration and the DiscoveryRequest, though those field. Those field shouldn't exposed via bootstrap. We might want to split them to two definition in v4.

**Comment by htuch** [comment]
Yeah, I think if you override these values, you will have a bad time when working with control planes that try and fix client bugs by conditioning on user agent name.
