### ISSUE TITLE
Front Proxy sandbox documentation is outdated

### ISSUE THREAD

**Issue by yosrym93** [envoyproxy/envoy#12111]
The docs at: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy are outdated. The mentioned ports for the front-envoy are 8080, 8001, and 8443. While actually the opened ports are 8000 & 8001. Consequently some of the given commands do not run successfully.

**Comment by akonradi** [comment]
The services run on port 8000, but the front Envoy is listening on 8080, 8001, and 8443. Can you try again after patching in #12112?

**Comment by mk46** [comment]
Hi @yosrym93, It's working for me. Could you please share logs or error? It may be mentioned ports in docs are used by other services.

**Comment by yosrym93** [comment]
I was not working on the most updated master, my bad. Issue closed.
Thanks @akonradi and @mk46.

**Comment by mk46** [comment]
@yosrym93 Could you please share logs?

**Comment by yosrym93** [comment]
@mk46 there are no problems or logs, I was just running an older commit. That's why the code did not match the docs. Sorry for the inconvenience.
