### ISSUE TITLE
CacheFilter: Add date metadata/ internal header to cached responses

### ISSUE THREAD

**Issue by yosrym93** [envoyproxy/envoy#12140]
When a response is being inserted to the cache, the cache filter should add a date internal header or metadata to the cached response. This should be used instead of the response `Date` header throughout the CacheFilter module as there might be a clock skew between the origin and Envoy.

**Comment by yosrym93** [comment]
Among the updates that should be made when this is implemented:
- Update CacheabilityUtils::isCacheableResponse() has_validation_data conditions.
- Update LookupRequest::requiresValidation() and remove the check for a future response_time.

**Comment by toddmgreer** [comment]
I think we should add things like this to the plugin API. Plugins can turn them into header if needed, and we can avoid the cost of modifying headers for in-memory caches.

Offhand, I think we should add a Metadata struct (or proto?) that would be included in makeInsertContext and LookupResult.
