### ISSUE TITLE
http: upstream protocol error shouldn't be 503 UC

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#12157]
Was debugging issues similar to https://github.com/istio/istio/issues/24753, while https://github.com/envoyproxy/envoy/pull/11916 isn't an appropriate fix, though a response in case of upstream protocol error ended up with 503 UC flag is quite confusing.

- We should add reponse flag like UPE (similar to DPE) to indicate that's the reason.
- 502 is a better response code? https://tools.ietf.org/html/rfc7231#section-6.6.3
> The 502 (Bad Gateway) status code indicates that the server, while
   acting as a gateway or proxy, received an invalid response from an
   inbound server it accessed while attempting to fulfill the request.

cc @lambdai

**Comment by lambdai** [comment]
+1
Usually access log is much more wider adopted by debug log. 
Additional response flags could allow us get closer to the root cause at a low runtime cost meanwhile significantly reduce the mental load going through the debug log.

**Comment by PiotrSikora** [comment]
Yes, `502 Bad Gateway` is more appropriate here.

**Comment by storyicon** [comment]
Is there any plan to correct the 502/503 return code? We expect that when an upstream error occurs, the return code of envoy should be consistent with nginx.

**Comment by lizan** [comment]
Yes I think this should be fixed. I have partial fix locally. cc @alyssawilk
