### ISSUE TITLE
expose stats for time blocked in the main thread

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#12186]
Last week we had an issue when dealing with huge sets of IPs for the IP tagging filter. The problem is triggered by the fact that we have a few places from where we call `/config_dump` and dumping 100s of megabytes of IP ranges ended up blocking the main thread for a few seconds. This meant that a few important things that we run from the main thread didn’t run on time, most notably the timer callback that refreshes tokens for our local HTTP rate limiter.

So this specific issue can be addressed in a few different ways (don’t dump ip sets from `/config_dump`, don’t call `/config_dump` too frequently, etc). However, we are more worried about the meta issue: the lack of visibility into the fact that the main thread could get blocked for a long period of time.

We are thinking of adding some instrumentation to track the time spent in non-idle mode in the main thread and exposing stats for this (e.g.: percentile of time the main thread is blocked).

Thoughts?

cc: @jmarantz @mattklein123

**Comment by zuercher** [comment]
I'm not 100% sure this covers your case, but have you looked into these: https://www.envoyproxy.io/docs/envoy/latest/operations/performance.html

**Comment by mattklein123** [comment]
Yeah I think the stats that @zuercher mentions should work for the main thread also.

**Comment by rgs1** [comment]
Yes -- works for the main thread too. This is what we need. Thanks!
