### ISSUE TITLE
Question: Is decodeData called with end_stream set to true guaranteed to be called even when there are HTTP trailers in the request?

### ISSUE THREAD

**Issue by hq6** [envoyproxy/envoy#12196]
This [comment](https://github.com/envoyproxy/envoy/blob/568b75960dcf0650cf600d5e1181480ee4f519e0/include/envoy/http/filter.h#L528) states that "end_stream supplies whether this is the last data frame." 

If there are HTTP trailers in the request (in some sense, additional data after the last data frame), is it guaranteed that `decodeData` will be called at least once with `end_stream` set to true?

**Comment by mattklein123** [comment]
> If there are HTTP trailers in the request (in some sense, additional data after the last data frame), is it guaranteed that decodeData will be called at least once with end_stream set to true?

No, end_stream is only true if there are no trailers. Please feel free to PR a comment fix.
