### ISSUE TITLE
Identify required patches for Envoy Windows port public alpha

### ISSUE THREAD

**Issue by wrowe** [envoyproxy/envoy#12205]
This is a placeholder to tag all WIP to get us to a usable alpha state.

Reflects another milestone in the history of issue #129

**Comment by wrowe** [comment]
#10871 "Replace pipe() with os_sys_calls_impl::socketpair(AF_UNIX,...) in buffer tests"
offers a suggestion of applying the evutil_win_socketpair_afunix() helper of libevent.

**Comment by wrowe** [comment]
https://github.com/envoyproxy/envoy/issues/11655 doesn't seem critical for alpha, but should probably be implemented before the first beta candidate.

**Comment by wrowe** [comment]
Open question of whether https://github.com/envoyproxy/envoy/issues/10420 is needed before alpha.

**Comment by wrowe** [comment]
cc @envoyproxy/windows-dev

**Comment by wrowe** [comment]
cc @rmiller14

**Comment by sunjayBhatia** [comment]
Closing this, alpha has been announced, any issues for Windows beta should be added to this milestone: https://github.com/envoyproxy/envoy/milestone/16
