### ISSUE TITLE
//test/integration:stats_integration_test is flaky

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#12209]
~5% flake rate with 100 runs.  Multiple test cases fail.  Sample failures:

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithRealSymbolTable/IPv4
test/integration/stats_integration_test.cc:377: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 37114
  37115
Stack trace:
  0x20c1a7e: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeClusterSizeWithRealSymbolTable_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithRealSymbolTable/IPv4, where GetParam() = 4-byte object <00-00 00-00> (5102 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithRealSymbolTable/IPv4
test/integration/stats_integration_test.cc:377: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 37118
  37115
Stack trace:
  0x20c1a7e: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeClusterSizeWithRealSymbolTable_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithRealSymbolTable/IPv4, where GetParam() = 4-byte object <00-00 00-00> (5252 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithFakeSymbolTable/IPv4
test/integration/stats_integration_test.cc:304: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 45007
  45003
Stack trace:
  0x20bf5c1: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeClusterSizeWithFakeSymbolTable_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithFakeSymbolTable/IPv4, where GetParam() = 4-byte object <00-00 00-00> (4031 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithFakeSymbolTable/IPv4
test/integration/stats_integration_test.cc:304: Failure
Expected equality of these values:
  m_per_cluster
    Which is: 45002
  45003
Stack trace:
  0x20bf5c1: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeClusterSizeWithFakeSymbolTable_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeClusterSizeWithFakeSymbolTable/IPv4, where GetParam() = 4-byte object <00-00 00-00> (3955 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4
test/integration/stats_integration_test.cc:424: Failure
Expected equality of these values:
  m_per_host
    Which is: 1382
  1380
Stack trace:
  0x20c234c: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeHostSizeWithStats_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4, where GetParam() = 4-byte object <00-00 00-00> (1187 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4
test/integration/stats_integration_test.cc:424: Failure
Expected equality of these values:
  m_per_host
    Which is: 1381
  1380
Stack trace:
  0x20c234c: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeHostSizeWithStats_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4, where GetParam() = 4-byte object <00-00 00-00> (1187 ms)

[ RUN      ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4
test/integration/stats_integration_test.cc:424: Failure
Expected equality of these values:
  m_per_host
    Which is: 1384
  1380
Stack trace:
  0x20c234c: Envoy::(anonymous namespace)::ClusterMemoryTestRunner_MemoryLargeHostSizeWithStats_Test::TestBody()
  0x4d8edd4: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x4d7f5db: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x4d6d093: testing::Test::Run()
  0x4d6da57: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] IpVersions/ClusterMemoryTestRunner.MemoryLargeHostSizeWithStats/IPv4, where GetParam() = 4-byte object <00-00 00-00> (1379 ms)

**Comment by antoniovicente** [comment]
Tested as of commit 3e92500dfae541b95f22823b03dfdd711e80538a from Mon Jul 20 14:19:03 2020 -0700

cc @jmarantz @mattklein123

**Comment by mattklein123** [comment]
I will defer to @jmarantz to diagnose. My personal opinion is this test is not worth the pain and we should track the memory usage some other way to look for major regressions.

**Comment by mattklein123** [comment]
@jmarantz thoughts on disabling this tests since it now seems like it's not deterministic? I've seen it flake multiple times now.

**Comment by jmarantz** [comment]
Ok... Not going to die on this hill... One quick question.... On clang 10? What other command line options?

**Comment by mattklein123** [comment]
I assume clang-10 as it's failing in CI now (this seems new so something changed). You might be able to fix it.

**Comment by antoniovicente** [comment]
This is based on running on my workstation with clang10.

bazel test --config=libc++ --test_env=ENVOY_MEMORY_TEST_EXACT=true //test/...

**Comment by jmarantz** [comment]
Do you see flakiness if you use -c opt, out of curiosity?

I can't think of a reason that '-c opt' should affect flakiness... Just
curious as I had not previously observed the flakes.

**Comment by antoniovicente** [comment]
I did the local run after seeing it fail in CI, but repoing in CI being really hard.

in -c opt, I see 52 failures out of 1000 test iterations.  Failures look similar to the ones posted in the test description, multiple test cases are affected.

**Comment by jmarantz** [comment]
Ok... Seeing as I really don't have time to suss out the flake e should just come out the EQ tests

**Comment by antoniovicente** [comment]
@mum4k @oschaaf
