### ISSUE TITLE
[rocketmq_proxy] assert failure with untrusted buffer when onData()

### ISSUE THREAD

**Issue by jianwen612** [envoyproxy/envoy#12220]
#### Since documentation of rocketmq_proxy shows it is still an alpha version, and only accept trusted data, I think this is not a security issue, so I post it here.
The assert failure is here:
`ASSERT(frame_length > header_length);`
(https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/rocketmq_proxy/codec.cc#L40)
There is an assert() for input data. I think it should use an if-block to check the validity instead of using an assert:
```
if(frame_length <= header_length){
    has_error = true;
    return nullptr;
}
```
Even though it doesn't accept untrusted data now, in the future, all stable versions of network-layer filters should eventually accept untrusted data.  If the data is invalid(from untrusted sender or modified in the network), it will potentially cause a crash here.

Above is a possible fix for this issue. If anyone has a better idea, please let me know. I'm working on fuzz test for network-layer filters.

/cc @aaron-ai 

/cc @samkerner
/cc @asraa

**Comment by zuercher** [comment]
cc @lizhanhui @lizan

**Comment by jianwen612** [comment]
To reproduce this failure, this test case can be added to test/extensions/filters/network/rocketmq_proxy/conn_manager_test.cc

```
TEST_F(RocketmqConnectionManagerTest, AssertFailure) {
  const std::string yaml = R"EOF(
  stat_prefix: test
  )EOF";
  initializeFilter(yaml);
  buffer_.add(std::string({'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00'}));
  EXPECT_EQ(conn_manager_->onData(buffer_, false), Network::FilterStatus::StopIteration);
  EXPECT_EQ(1U, store_.counter("test.request").value());

  buffer_.drain(buffer_.length());
}
```

Since no other suggestions were proposed here, I'm going to make a pull request to fix it.
