### ISSUE TITLE
push checks: <binary> exists, but cannot be executed by other users

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#12230]
I have seen this problem a few times before with tools like clang.  For some reason tools/code_format/check_format.py checks if the binary in question is executable by other users and fails in cases where the binary in question is on the user's home directory and is executable by the user running the git commands.  Could we weaken this check?  Perhaps by checking if binaries are executable by attempting to run them with a --version argument or explicitly checking for owner executable in cases where the current user owns the binary in question?

Running pre-push check; to skip this step use 'push --no-verify'
  Checking format for .bazelrc - ERROR: command /home/avd/gopath/bin/buildifier exists, but cannot be executed by other users

**Comment by zuercher** [comment]
Seem like we could relax it to take any executable bit.
