### ISSUE TITLE
[HTTP] Refactor protocol constraints checks

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#12279]
Protocol constraints checks consists of limits of inbound and outbound frames of different types. The implementation is spread out through the codec source code. For readability and sharing between legacy and new codec implementations, protocol constrains checks should be refactored into a dedicated class.

Sub-task of the #12278

**Comment by mattklein123** [comment]
@yanavlasov is this a dup of https://github.com/envoyproxy/envoy/issues/10646 or related?

**Comment by yanavlasov** [comment]
I'd say it is a pre-requisite. This bug is to refactor flood checks, but the class can be extended to do other checks as well.
