### ISSUE TITLE
[HTTP/2] extend flood protection to upstream servers

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#12281]
Flood protection checks are currently enabled in downstream (server) codecs. These checks need to be extended to the upstream client codecs as well to allow Envoy to work with untrusted upstream servers.

Depends on #12280
Sub-task of #12278

**Comment by antoniovicente** [comment]
While we're at it, we should rethink how flood protection is implemented.  We have seen that throwing an exception when triggering the flood condition  is risky.

https://github.com/envoyproxy/envoy/issues/11370 may be the best way to address data frame flooding cases.  Control frame flooding requires more thought.

**Comment by yanavlasov** [comment]
Upstream flood and abuse checks will be implemented in the following steps:

1. Add upstream flood and abuse checks to the client codec, protected by a runtime flag, disabled by default. (see PR#13635)
1. Implement all tests for all relevant upstream flood/abuse cases
1. Flip the upstream checks to be enabled by default, and runtime flag to disable them.
1. Remove the flag altogether after deprecation period.

**Comment by yanavlasov** [comment]
Tests that need to be implemented for upstream flood/abuse checks. Test names come from the http2_flood_integration_tests test suite

- [x] Ping PR#13635
- [ ] Settings
- [ ] Metadata
- [ ] WindowUpdateOnLowWatermarkFlood
- [ ] RST_STREAM
- [ ] GoAwayOverflowOnDrainTimeout
- [ ] DownstreamIdleTimeoutTriggersFloodProtection
- [ ] DownstreamConnectionDurationTimeoutTriggersFloodProtection
- [ ] RstStreamOnUpstreamRemoteCloseBeforeResponseHeaders
- [ ] RstStreamOnStreamIdleTimeoutAfterResponseHeaders
- [ ] EmptyHeaders
- [ ] EmptyHeadersContinuation
- [ ] EmptyData
- [ ] PriorityIdleStream
- [ ] PriorityOpenStream
- [ ] PriorityClosedStream
- [ ] WindowUpdate
- [ ] ZerolenHeader
- [ ] ZerolenHeaderAllowed
