### ISSUE TITLE
Dynamic OT tracing question

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#12291]
*Title*: *Dynamic OT tracing question*

*Description*:
I'm using https://github.com/jaegertracing/jaeger-client-cpp and have configured `client_sampling=100 random_sampling=0 overall_sampling=100` with the intent that my downstream client can decide when spans should be sent by upstream components, and can't seem to turn spans off. Every request produces one even without the header

I traced the potential issue to 
```
  if (!tracing_decision.traced) {
    options.tags.emplace_back(opentracing::ext::sampling_priority, 0);
  }
```
where it looks like the only change to the span when the decision is to not trace is to add a `sampling_priority` of 0

https://github.com/envoyproxy/envoy/blob/v1.15.0/source/extensions/tracers/common/ot/opentracing_driver_impl.cc#L193-L195

So the question is: if I'm reading the source correctly is it by design that spans are always sent, or am I likely misconfiguring something?

**Comment by phylake** [comment]
@objectiser I found #2787 where you comment
> Other OpenTracing compatible tracers - the only way to influence the sampling of a trace instance in the OpenTracing standard is through the use of the sampling.priority tag - so in this situation if the proxy sampling decision is false, the sampling.priority tag will be set to 0 when creating the span. It is then the tracer's responsibility to use or ignore that hint.

It sounds like this is by design and an issue with https://github.com/jaegertracing/jaeger-client-cpp then, is that right?

**Comment by objectiser** [comment]
Does your root span have a tag with `sampling.priority` set to 0? If so, then the tracer is ignoring the hint. However, as mentioned in the [spec](https://opentracing.io/specification/conventions/), it is only a hint so not guaranteed to be supported by the tracers.

**Comment by phylake** [comment]
Thanks for the quick reply @objectiser! 
> Does your root span have a tag with `sampling.priority` set to 0?

I don't believe so. Do you agree this isn't a problem with the Envoy implementation? If so I'll close this

**Comment by objectiser** [comment]
@phylake I think the problem is that the `sampling.priority` tag is on a hint, and not mandatory behaviour, so no guarantee that tracers would implement. But it is the only OpenTracing API mechanism where an app can try to influence the sampling decision.

So agree, with the OpenTracing API as currently stands, it is not an issue with envoy.
