### ISSUE TITLE
//test/integration:extension_discovery_integration_test unconditionally depends on RBAC extension

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#12315]
While trying to import PR #11826 into an environment that disables most extensions, I noticed a direct dependency between //test/integration:extension_discovery_integration_test and //source/extensions/filters/http/rbac:config.

Are direct dependencies between envoy core and specific extensions allowed?  Is there a minimal subset of extensions that are considered essential and all Envoy consumers must include in their builds?

cc @yanavlasov

**Comment by antoniovicente** [comment]
https://github.com/envoyproxy/envoy/pull/11826#discussion_r461780464

**Comment by yanavlasov** [comment]
Fixed
