### ISSUE TITLE
Allow CSDS Requests to specify status only

### ISSUE THREAD

**Issue by therealmitchconnors** [envoyproxy/envoy#12339]
*Title*: *Allow CSDS Requests to specify status only*

*Description*:
>CSDS returns the status of each selected client, as well as a config dump.  I would like to query the status of many clients at once, but the size and cost of config dumps makes this prohibitively expensive.  Can we add an optional field to the CSDS Request to allow users to request status data only?

*Relevant Links*:
>https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/status/v2/csds.proto#L56

**Comment by kyessenov** [comment]
I think there are additional issues with CSDS as it stands today:
- unclear semantics of status aggregation (what does it mean for RDS to be accepted if it consists of many individual resource exchanges, what if the same resource accepted by one proxy but not another)
- rigid set of type URLs: it should be possible to query any UDPA type status, including SDS, SRDS, VHDS, ECDS, etc.

**Comment by htuch** [comment]
CSDS as it exists today is really just a gRPC wrapper around the admin config dump. I think this proposal is reasonable, but I would also suggest we include version, last synced time, name for resources as well. In terms of the set of types, I would hope we could reasonably have this status provided for all types Envoy supports, but it should ideally be done for the admin interface as well.

**Comment by therealmitchconnors** [comment]
@htuch when you refer to version, last synced, and name, are you referring to the per-collection values, or per-resource values?  I think it would be inexpensive to output:

```
version: deadbeef
last_synced: 2020-08-11T07:00:32.123
name: listeners
```

but if you're looking for these values on a per-resource level, that could a very large payload for large service meshes.  Perhaps what we need is an enum controlling the verbosity of output?

**Comment by htuch** [comment]
Collection is fine for now I think.
