### ISSUE TITLE
Proposal: add ability to ignore new hosts for trickle/panic calculations until they pass a health check

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#12331]
This request is very similar to the existing `ignore_new_hosts_until_first_passing_hc` feature, which allows for not including a host in the "total" count used for spillover and panic mode until a health check has completed.

This request proposes another option which is to wait until a _passing_ health check has completed, not assuming that the first health check succeeds.

The goal here is to be able to scale up a locality by say 2x, registering the endpoints in service discovery before they're ready to allow for control plane propagation. Health checks will fail for an undetermined amount of time until the endpoints go healthy, at which point they should be counted.

**Comment by mattklein123** [comment]
This seems fine to me but will defer to @snowp on this. cc @nezdolik also who has done work in this area.

**Comment by snowp** [comment]
Yeah seems fine to me. I think we'd want to change the API a bit to use a structured `HostWarmingPolicy` or something to that effect instead of a series of bools, but other than that this should be easy to do given the existing `excluded_hosts` concept

**Comment by nezdolik** [comment]
+1 for grouping those flags into some sort of struct as they are very similar, not to clutter api. Sounds like a valuable and doable feature, one should probably add new hosts to excluded list by checking specific health flag, which will be used for calculating locality weights/panic mode etc.
