### ISSUE TITLE
Proposal: add support for x-ratelimit-* headers

### ISSUE THREAD

**Issue by Pchelolo** [envoyproxy/envoy#12356]
**Rational**

For the client to be able to actively throttle their requests they need to know their current status with regards to rate limits. A [draft RFC](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html) exists specifying `RateLimit-Limit, RateLimit-Remaining, RateLimit-Reset` headers, which seem to have fair adoption. 

**Prior art**

A few pull requests were created in the ratelimit service https://github.com/envoyproxy/ratelimit/pull/77, taking over https://github.com/envoyproxy/ratelimit/pull/56 but they were closed due to issues with a general approach. According to @mattklein123, the better approach compared to the one taken in the pull request would be to change the ratelimit API to provide the necessary data, while setting the response headers in envoy. 

**Proposal**

1. Drop `response_headers_to_add` and `request_headers_to_add` from the RateLimitResponse proto in v4, deprecate the fields in v3 protocol per https://github.com/envoyproxy/ratelimit/pull/77#issuecomment-482272850
2. Add a field to the `RateLimitResponse:DescriptorStatus:reset` supporting the `X-RateLimit-Reset` header and implement providing the data in rate limiter service.
3. Implement support for `RateLimit-Limit, RateLimit-Remaining, RateLimit-Reset` in envoy ratelimit filter under a filter configuration parameter.

I'm going to contribute all the code/testing if the proposal is approved by maintainers. 
cc @junr03

**Comment by mattklein123** [comment]
This proposal SGTM. The only thing I would recommend is not deprecating the request/response headers to add fields, as they may have other uses. Since they are already implemented I don't see any reason to remove them. We can add this behavior additionally. Thank you!

**Comment by Pchelolo** [comment]
> The only thing I would recommend is not deprecating the request/response headers to add fields, as they may have other uses. Since they are already implemented I don't see any reason to remove them. We can add this behavior additionally. 

Great, thank you. This makes the job even easier :)
