### ISSUE TITLE
replacing .first/.second names with more meaningful names using structured binding

### ISSUE THREAD

**Issue by stedsome** [envoyproxy/envoy#12354]
This is an expansive cleanup effort, and as it is so expansive, this issue is created to track all the related PRs that are divided into components.
@alyssawilk @asraa

**Comment by stedsome** [comment]
This is the PR that started the discussion of needing to split the change further into submodules.
https://github.com/envoyproxy/envoy/pull/12334

**Comment by asraa** [comment]
Thanks! My impression is that (a) at least the PRs should be split into subcomponents (please label the PRs based on the components), and that (b) this is a great clean-up for things that will have a big readability impact. I'd love to see ones where .first/.second are used extensively be replaced, over ones that are only used once.

**Comment by stedsome** [comment]
> Thanks! My impression is that (a) at least the PRs should be split into subcomponents (please label the PRs based on the components), and that (b) this is a great clean-up for things that will have a big readability impact. I'd love to see ones where .first/.second are used extensively be replaced, over ones that are only used once.

Thanks for the message, I will add the component labels to PRs, and I certainly agree that in some instances, the impacts are pretty small. However, do you mind quantifying "used extensively" so that I can have an idea when I am trimming down the PRs.

**Comment by asraa** [comment]
Sure! I really like the factory/factory name one, and things like deprecated/canonical, but for ones that are simply going over key/value pairs without a significant meaning, i think it's ok to leave as is (the metadata one and json one comes to mind).

**Comment by stedsome** [comment]
> Sure! I really like the factory/factory name one, and things like deprecated/canonical, but for ones that are simply going over key/value pairs without a significant meaning, i think it's ok to leave as is (the metadata one and json one comes to mind).

Yes that is what I planned to do! Also I believe in the new PR (pretty small just to test the water), there are no such cases.
