### ISSUE TITLE
Extend Envoy::Buffer to allow for transfer of ownership of buffer slices without copying

### ISSUE THREAD

**Issue by roelfdutoit** [envoyproxy/envoy#12373]
I am building a network filter that has to move the content of an `Envoy::Buffer` into a proprietary library (calling it X in the rest of this description) while avoiding copies as far as possible.  The filter has to convert from an `Envoy::Buffer` to a `X::Buffer` and then allow the library to access the content beyond the scope of the current `onData()` call.  The `X::Buffer` interface is very similar to `Envoy::Buffer`, with an `X::Buffer` instance acting as a container for buffer slices.  One of the differences is that `X::Buffer` has methods to transfer ownership of buffer slices, e.g. `extractFrontSlice()`, `popFrontSlice()`, `pushFrontSlice()`.  My understanding is that `Envoy::Buffer::getRawSlices()` provides a read-only view on the slices, and that no mechanism exists to extract slices without copying.  In other words I want to avoid using `Envoy::Buffer::copyOut()` or `Envoy::Buffer::linearize()`.  I could implement a convoluted mechanism where each slice in the `Envoy::Buffer::RawSliceVector` is wrapped in a new object that keeps a reference and refcount on the source `Envoy::Buffer`, and then inject those new slice objects into the `X::Buffer` instance, effectively indirectly “transferring ownership” of the `Envoy::Buffer` slices.  I would much rather prefer implementing the `X::Buffer` interface as a simple mapping of the `Envoy::Buffer` interface. I also understand that not all `Envoy::Buffer` instances are `Envoy::Buffer::OwnedImpl` instances and that the implementation for the new method(s) would sometimes result in a copy.

I am available to implement the required changes.

**Comment by alyssawilk** [comment]
cc @antoniovicente

**Comment by antoniovicente** [comment]
What API do you have in mind?

std::unique_ptr<Slice> transferFrontSlice();
std::unique_ptr<BufferFragment> transferFrontSlice();

something else?
Note these APIs may need to change in the future, the roadmap of improvements to the Envoy buffer class is not well defined.

**Comment by roelfdutoit** [comment]
I appreciate your feedback!

The `BufferFragment` variant should work given that the external library just needs a read-only object that provides access to the slice data and length.   It would probably be a special implementation of `BufferFragment` that wraps a `Slice`, and not just `BufferFragmentImpl`.  The downside of using `BufferFragment` is that its purpose (to wrap externally owned data) does not really match what I'm trying to do.

`Slice` has the major complication that it is defined in `buffer_impl.h` instead of `buffer.h`, but it would simplify things a little bit given that `OwnedImpl` already keeps the slices in the `SliceDeque`.

It feels like what is needed is a new class in `buffer.h` from which `Slice` can derive - something like:
```
class SliceBase {
public:
  virtual ~SliceBase() = default;
  virtual const uint8_t* data() const PURE;
  virtual uint64_t dataSize() const PURE;
};
```

`Buffer::Instance` would then get the following method:
`virtual std::unique_ptr<SliceBase> extractFrontSlice() PURE;`

What do you think?

**Comment by antoniovicente** [comment]
The thing you're proposing seems similar to moving the definition of the Slice interface class to the header defined in the includes directory.  The only real difference between the BufferFragment and Slice version of the API I mentioned is wherever or not you need to call an explicit method to do cleanup or rely on destructor to do the needful.  So the Slice version is probably the way to go.

I guess we may want two layers of Slice interface since the externalized slices should probably be const while OwnedImpl requires that the slices be mutable.

**Comment by roelfdutoit** [comment]
The cleanup-via-destructor model is good enough for my use case.

If you are open to defining the `Slice` interface in `buffer.h` then I would propose the following, keeping in mind that class naming is probably one of the hardest problems in computer science :)

`class SliceData` that provides a read-only view on the usable content of the slice.
`class Slice : public SliceData` that defines the rest of the current `Slice` interface, with the possible exception of the `describeSliceForTest` method which would be available in `SliceImpl` in `buffer_impl.h`.

.. and the following method in `Buffer::Instance`:
`virtual std::unique_ptr<SliceData> extractFrontSlice() PURE;`

**Comment by antoniovicente** [comment]
I agree that naming is the only remaining problem in computer science.

I was going for Slice and MutableSlice, but SliceData and Slice would also work.

**Comment by roelfdutoit** [comment]
I will work on getting a PR ready.
