### ISSUE TITLE
JWT authentication issuer not configured error

### ISSUE THREAD

**Issue by hinawatts** [envoyproxy/envoy#12377]
Hi, 
I am trying to enable JWT authentication in envoy.yaml. The token passed in request is generated by service hosted by our company. And in this token, we don't use 'iss' (issuer) claim. And when I use envoy with configuration for JWT, I get an error "Jwt issuer is not configured". Can I skip the issuer validation in JWT auth in envoy?

**Comment by hinawatts** [comment]
Please let me know if there is any suggestion here.

**Comment by qiwzhang** [comment]
Unfortunately,  "iss" is a required field in Envoy jwt_authn filter.

**Comment by Jeskz0rd** [comment]
Is there any other options for this issue?

**Comment by qiwzhang** [comment]
We can add a new field in jwt_authn `JwtProvider` [config](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L55) to specify field name to extract issuer.    Such as

// The field name in jwt payload to specify issuer.
// Normally "iss" is used.  If other field name is used, use this field to specify it.
string  issuer_field_name = 9;

**Comment by qiwzhang** [comment]
Hi @mattklein123 please assign this to me.

**Comment by qiwzhang** [comment]
It turn out "iss" is not needed in most cases.  Change the code to:  if "iss" is not in the jwt payload,  not to verify it.

**Comment by ycfreeman** [comment]
seems the fix is not applied to the related .proto file

**Comment by qiwzhang** [comment]
@ycfreeman I changed the way to fix this.  The new way did not require config proto file change.  It allows "iss" field to be empty.  If it is empty, "iss" is not verified.

**Comment by Coconut105** [comment]
Hello,
having issuer attribute always set to some value in Envoy is against https://tools.ietf.org/html/rfc7519#section-4.1.1 where it is mentioned as optional. 
Could you please fix it so that is also optional in Envoy?

**Comment by qiwzhang** [comment]
It has been fixed. Now "iss" is optional.  Unless you use "allow_fail_or_mssing" or "allow_missing" flag.

**Comment by Coconut105** [comment]
You have only fixed the case where "iss" is not present in JWT but "issuer" field is configured in envoy.
Verification should still not happen if "iss" is present in JWT but "issuer" field not present in envoy. But you don't allow not having "issuer" set in envoy. This is against RFC 7515 and needs to be fixed.

**Comment by qiwzhang** [comment]
I see.  In jwt_authn filter config,  "issuer" is a required field now.  This should be changed to be optional.

**Comment by qiwzhang** [comment]
Hi can someone reopen this issue, and assign it to me?   Thanks
