### ISSUE TITLE
inotify_fd_ assertion is misleading

### ISSUE THREAD

**Issue by mook-as** [envoyproxy/envoy#12383]
*Description*:
#9098 added a description on the assertion for when `inotify_fd_` failed to initialize.  [The assertion] says to `Consider increasing value of user.max_inotify_watches via sysctl`; however, it's asserting that [`inotify_init1(IN_NONBLOCK)`] succeeds, which [creates new inotify instances] instead of watches.  So the user should be increasing `user.max_inotify_instances` instead.

[The assertion]: https://github.com/envoyproxy/envoy/blob/v1.15.0/source/common/filesystem/inotify/watcher_impl.cc#L28
[`inotify_init1(IN_NONBLOCK)`]: https://github.com/envoyproxy/envoy/blob/v1.15.0/source/common/filesystem/inotify/watcher_impl.cc#L20
[creates new inotify instances]: https://linux.die.net/man/2/inotify_init1

*Repro steps*:
- `echo 1 | sudo tee /proc/sys/user/max_inotify_instances`
- Run envoy.

**Comment by dio** [comment]
cc. @sriduth

**Comment by sriduth** [comment]
The assertion message is misleading - I will open a PR to fix this, will also try to see if we can use `errno` to deliver a better error message.

**Comment by sriduth** [comment]
I made a patch here: https://github.com/sriduth/envoy/commit/acf3831b4b2a4d636db0033c955e30f74a9ea6d5
but based on the original issue reported #7130, it looks like `inotify_init1` can fail of either `user.max_inotify_watches` is set to a low value - ill dig deeper into this.

Also, we could improve the message logged if `inotify_add_watch` fails in the `WatcherImpl::addWatch` method, currently it just prints `No space left on device` which is `std::strerror` I think.

**Comment by sriduth** [comment]
in initial report for #7130 `sysctl -w user.max_inotify_watches=524288` was mentioned as the fix used

**Comment by Swaagie** [comment]
@sriduth this is still an issue. I recently ran into this and can confirm using `max_inotify_watches` resolved it rather than using `max_inotify_watches`. Do you still intent to PR the changes from your fork?
