### ISSUE TITLE
sending reset from upstream to envoy in integration test

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#12409]
I am trying to write an integration test in which client send requests to envoy and envoy sends it  to upstream and upstream will send reset to the envoy in response.  I looked into existing IT'S and seems like " codec_client_->sendReset(*request_encoder_)" will do the job. Seems like this test is doing the same, can anybody confirm. I am confused about whether sendReset is resetting the upstream or upstream is resetting envoy. 

https://github.com/envoyproxy/envoy/blob/d7c7e9a79eed80afa56a0b05cf6adf0516750d14/test/integration/http_integration.cc#L1170

**Comment by yanavlasov** [comment]
The code you have linked will reset stream from client to Envoy. If you need to reset stream from upstream to envoy take a look at the HttpIntegrationTest::sendRequestAndWaitForResponse() method https://github.com/envoyproxy/envoy/blob/2a6a4b8d758b4bf4238cb6d2babdd3d83fbf45bc/test/integration/http_integration.cc#L286

The `upstream_request_` is the encoder you can use to send the data from upstream to envoy. To send reset you can use the `encodeResetStream()` method.

**Comment by pitiwari** [comment]
thanks
