### ISSUE TITLE
 manifest unknown

### ISSUE THREAD

**Issue by vorticalbox** [envoyproxy/envoy#12403]
I am trying to set up envoy in docker but I am getting this error.

```
Building envoy
Step 1/5 : FROM envoyproxy/envoy
ERROR: Service 'envoy' failed to build: manifest for envoyproxy/envoy:latest not found: manifest unknown: manifest unknown
```

I also get this error with docker pull

```
docker pull envoyproxy/envoy                                                                                                                  1 ↵
Using default tag: latest
Error response from daemon: manifest for envoyproxy/envoy:latest not found: manifest unknown: manifest unknown
```

**Comment by dio** [comment]
As commented here: https://github.com/envoyproxy/envoy/issues/10738#issuecomment-612184855 

> With us now releasing security/stable releases, "latest" no longer has any meaning so it has been removed. Please pin to a specific version.
