### ISSUE TITLE
Prometheus format for /cluster in administration interface

### ISSUE THREAD

**Issue by rumanzo** [envoyproxy/envoy#12436]
Hi! We want to count requests to each upstreams in cluster. It's possible by /cluster in admin interface, but is it possible to make an interface for prometheus like for stats?format=prometheus (/stats/prometheus) ?

**Comment by fengyinqiao** [comment]
I have met the problem as you too.So,did you resolve it or find any workaround?

**Comment by rumanzo** [comment]
> I have met the problem as you too.So,did you resolve it or find any workaround?

My colleague wrote a wrapper for sending to graphite.
see #13249
