### ISSUE TITLE
MaxBodySize as config or cmd line parameter in source/common/router/config_utility.cc

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#12431]
We are using envoy as a web server to serve up some static file content.
We had to tweak the above constant to respond with some of the larger image files.

Would it be useful to expose this as a config (or cmd line param) rather than a hard coded constant?

**Comment by mattklein123** [comment]
Yeah +1 to making this configurable. This was hard coded a while ago to just prevent accidental problems.

**Comment by sumukhs** [comment]
Given this config is inside the router, would LDS be the right place for it?

**Comment by mattklein123** [comment]
I think it should probably be on a per-route basis. Can it just sit next to the direct response config itself?

**Comment by mk46** [comment]
Now MaxBodySize is configurable by `route.v3.RouteConfiguration.max_direct_response_body_size_bytes`. I think, we should close this. dup of https://github.com/envoyproxy/envoy/issues/13422
