### ISSUE TITLE
Proposal: Introduce host_rewrite_path support in route config

### ISSUE THREAD

**Issue by Pchelolo** [envoyproxy/envoy#12430]
**Rational**

Using subdomains for tenant-id in a multi-tenant application is a relatively popular strategy, our own MediaWiki (the software behind Wikipedia) uses `Host` header to distinguish between different language wikis. Ability to rewrite `Host` based on path would provide flexibility in moving the tenant-id from subdomain to path when deploying existing software behind the proxy.

**Proposal**

Introduce a new `host_rewrite_path` option in `RouteAction:host_rewrite_specifier`. 

```
// Indicates that during forwarding, the host header will be swapped with the result of the
// given regex substitution run agains the request path. 
type.matcher.v3.RegexMatchAndSubstitute host_rewrite_path = 36;
```

The behavior of the new property would be the following: `Host` header will be set to the result of the `RegexMatchAndSubstitute`, executed agains the path. However, this would need to be applied with care, since the regex matcher needs to be guaranteed to match the whole path string. Alternatively, a new `RegexMatchAndReplace` message could introduced, where the result would replace the input string with capture groups applied, or null if the regex did not match the input - in that case the host header would not be swapped if the regex did not match.

We are going to provide implementation and testing. Seeking approval from the maintainers and guidance on whether to reuse `RegexMatchAndSubstitute` or introduce a new message type.

**Comment by dio** [comment]
cc. @snowp

**Comment by mattklein123** [comment]
At a high level this feature makes sense to me. 

> However, this would need to be applied with care, since the regex matcher needs to be guaranteed to match the whole path string. Alternatively, a new RegexMatchAndReplace message could introduced, where the result would replace the input string with capture groups applied, or null if the regex did not match the input - in that case the host header would not be swapped if the regex did not match.

I'm a little hazy on this part. Can you explain in more detail. Could adding additional parameters to `RegexMatchAndSubstitute` also help change the behavior in a way that would work for you?

**Comment by Pchelolo** [comment]
> I'm a little hazy on this part. Can you explain in more detail? Could adding additional parameters to RegexMatchAndSubstitute also help change the behavior in a way that would work for you?

On a second thought, `RegexMatchAndSubstitute` would work just fine as is. I was being too worried about missconfiguring this, but introducing new flags wouldn't really make it any easier to configure. I'll implement a version with just `RegexMatchAndSubstitute`.
