### ISSUE TITLE
visibility issues after #12337

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#12444]
After picking up #12337, I can't get our visibility overrides going.

For context, we don't have Envoy as a git submodule and instead it we fetch it via bazel as a tarball using http_archive.

Doing something like:

```
ADDITIONAL_VISIBILITY = [
  '@foo//pinterest:__subpackages__'
]
```

in our extensions_build_config.bzl fails with:

```
ERROR: /private/var/tmp/_bazel_rgs/6fea2029bf5452e6659bcb3f721f95cc/external/envoy/BUILD:18:14: invalid package name '@foo//pinterest:__subpackages__': must start with '//'
```

cc: @lizan @alyssawilk

**Comment by rgs1** [comment]
In case it wasn't clear from the initial description, I am trying to get our filters to see core extensions, e.g.:

```
/Users/rgs/code/envoy-pinterest/pinterest/filters/http/copy_header/BUILD:10:17: 
in cc_library rule //pinterest/filters/http/copy_header:copy_header_lib: Target
'//pinterest/filters/http/copy_header:copy_header_lib' violates visibility of target
'@envoy//source/extensions/filters/http/common:pass_through_filter_lib'. 
```

**Comment by lizan** [comment]
I'll look into this later today. With some workable solution in envoy-filter-example. 

In general ``//source/extensions/filters/http/common:pass_through_filter_lib` should be public though.

**Comment by rgs1** [comment]
If we can't figure out a solution by EOD, we could merge #12451 to workaround this in the meanwhile.

**Comment by rgs1** [comment]
We still need to make the pass through filter public visible, will send a PR shortly.

**Comment by rgs1** [comment]
Regardless of the fix here we definitely want the pass through filter to be public I'd think (see #12463).
