### ISSUE TITLE
Provide Hystrix event stream to visualize circuit breaking

### ISSUE THREAD

**Issue by elevran** [envoyproxy/envoy#1244]
[Hystrix Dashboard](https://github.com/Netflix/Hystrix/wiki/Dashboard) can help visualize the health of the Envoy mesh based on information provided.
The specification format is discussed [here](https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring) and [here](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream).

**Comment by mattklein123** [comment]
This sounds useful!

**Comment by trabetti** [comment]
We started working on this feature. We want to discuss some design issues before we implement, such as which is the preferred user interface for activation, how to map Envoy statistics to Hystrix stream data, how to add sse support, etc.

**Comment by mattklein123** [comment]
Thanks @trabetti this sounds very cool. TBH I don't really have any idea what this feature will entail. Providing a bunch more info here or in a short 1-2 page gdoc on the feature overview and an implementation sketch would be great.

**Comment by trabetti** [comment]
please see more details in the attached doc.
[hystrix-envoy proposal.docx](https://github.com/envoyproxy/envoy/files/1499559/hystrix-envoy.proposal.docx)

**Comment by mattklein123** [comment]
@trabetti please provide a google doc (or equivalent) that supports shared commenting and editing. Thank you.

**Comment by trabetti** [comment]
updated last comment with gdoc link

**Comment by trabetti** [comment]
Hi @mattklein123 Any chance you could take a look this week? We are in a point that some design decisions are needed, and we would really appreciate your feedback. Thank You!

**Comment by mattklein123** [comment]
@trabetti yes sorry I have been slammed. It's on my list for today.

**Comment by mattklein123** [comment]
@trabetti I dropped two comments in the doc. I think admin handler makes sense. You will need to make the admin filter streaming capable on a per handler basis. I also think continuing to use Hystrix wording in Hystrix makes sense, with appropriate docs. LMK if you have other questions. I think this will be a super cool feature!

**Comment by trabetti** [comment]
Thanks @mattklein123 . Which filters did you refer to that do streaming? In our implementation we need to get the socket from the initial request and use it for streaming forever. Does it work the same way in those filters?

**Comment by mattklein123** [comment]
The filter infrastructure in general is streaming. Here is the admin filter:
https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc#L52

In `onComplete` currently, we basically call into the handler and send the full response, returning the code: https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc#L420

Instead, you will want to pass in the filter callbacks so that you can stream the response. See: https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h

**Comment by trabetti** [comment]
@mattklein123 - If we implement the hystrix stream support as an admin handler - after we get the request from hystrix dashboard, is it possible to start a new thread that will do the streaming messages through the same socket? The socket is used by both threads.

**Comment by mattklein123** [comment]
@trabetti I'm not sure I follow. You would probably leave a stream open and then periodically flush to it via async timer. There shouldn't be any other threads.

**Comment by mattklein123** [comment]
I would probably do a streaming admin filter, as admin has full access to the server/stats store and filters do not.

**Comment by trabetti** [comment]
About a month ago, Netflix has stopped development of Hystrix Dashboard, and recommends using it only behind authorization checks. See https://github.com/Netflix-Skunkworks/hystrix-dashboard.
We believe that producing an Hystrix event stream could still have value in Envoy but wanted to get your feedback before doing further work.

**Comment by mattklein123** [comment]
@trabetti I don't have an opinion. No one has asked me for this feature.
