### ISSUE TITLE
build: resource is restricted by Bazel scheduler

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#12455]
Build is not worked parallelly. We can find `[Sched]` and CPU is not fully used, so that it might be caused by Bazel scheduler behavior. This error can be found after [this commit](https://github.com/envoyproxy/envoy/pull/11955/commits/e7440bed50e0867cc2eba5fc25a4485c5a99b693).

```
shikugawa@machine:~/dev/envoy$ bazel build //test/integration:protocol_integration_test --jobs=60
INFO: Analyzed target //test/integration:protocol_integration_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/yaml/include:

INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/event/include:
[3 / 2,332] 60 actions, 1 running
    CcConfigureMakeRule external/envoy/bazel/foreign_cc/gperftools_build/include; 14s linux-sandbox
    [Sched] CcCmakeMakeRule external/envoy/bazel/foreign_cc/nghttp2/include; 24s
    [Sched] CcCmakeMakeRule external/envoy/bazel/foreign_cc/ares/include; 24s
    [Sched] Compiling external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_message.cc [for host]; 24s
    [Sched] Compiling external/com_google_protobuf/src/google/protobuf/compiler/java/java_extension_lite.cc [for host]; 24s
    [Sched] Compiling external/com_google_protobuf/src/google/protobuf/compiler/java/java_generator_factory.cc [for host]; 24s
    [Sched] Compiling external/com_google_protobuf/src/google/protobuf/compiler/code_generator.cc [for host]; 24s
    [Sched] Compiling external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc [for host]; 24s ...
```

![Screenshot from 2020-08-04 13-49-15](https://user-images.githubusercontent.com/17607122/89254110-51247a80-d659-11ea-8825-78b67faaa090.png)

**Comment by lizan** [comment]
I can't reproduce this. Do you have anything in user.bazelrc or ~/.bazerc?

**Comment by Shikugawa** [comment]
`user.bazelrc` is only this.

```
build --config=clang
build --test_output=all
```

The commits before two weeks ago is worked fine. So It might not be a problem on my environment.

**Comment by lizan** [comment]
What if you don't specify --jobs?

**Comment by Shikugawa** [comment]
It may be caused by `--experimental_local_memory_estimate` in .bazelrc. It might have a confusional bug. So we prefer to destroy it.

**Comment by mattklein123** [comment]
> It may be caused by --experimental_local_memory_estimate in .bazelrc. It might have a confusional bug. So we prefer to destroy it.

Yes I hit this also recently. On my underpowered laptop it decided to only run one job with this set. I haven't seen it as an issue on my bigger cloud machine.

**Comment by moderation** [comment]
I've commented on this in Slack and at https://github.com/envoyproxy/envoy/issues/1861#issuecomment-658282306. The behavior changed in Bazel 3.2.0 and any machine without much memory will scale back to a single CPU. I've had to override this setting in `.bazelrc` on my RPI4 with 4 cores and 8G of RAM and my Lenovo X1 Carbon with 12 cores and 16G of RAM
