### ISSUE TITLE
No throwing exceptions in header files 

### ISSUE THREAD

**Issue by stedsome** [envoyproxy/envoy#12469]
Google internally forbids the use of exception and having exceptions thrown in envoy header files can cause trouble when google code tries to include envoy library. 

This is to raise this issue of possibly rewriting all the instances where exceptions are thrown in header files. It primarily involves getting rid of template functions that are throwing exceptions, which may or may not be a significant change to envoy downstream.

**Comment by stedsome** [comment]
@ahedberg is more knowledgeable on this issue.

**Comment by mattklein123** [comment]
As I mentioned this is fine with me as long as all the fixes are simple which it sounds like they should be. If they aren't simple let's circle back and discuss.

**Comment by asraa** [comment]
I just added an exception linter in this PR https://github.com/envoyproxy/envoy/pull/12471
Maybe the lint portion of this could just extend the deny list.

**Comment by stedsome** [comment]
Yes. But I probably want to do the linting part last after all corresponding changes have been made.

**Comment by stedsome** [comment]
This issue is now closed. @ahedberg
