### ISSUE TITLE
CodeQL failing on init

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#12465]
CodeQL is failing on initialization:

```
PUT /repos/envoyproxy/envoy/code-scanning/analysis/status - 422 in 153ms
##[error]init action failed: HttpError: Invalid request.

"matrix_vars" is not a permitted key.
RequestError [HttpError]: Invalid request.

"matrix_vars" is not a permitted key.
    at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.sendStatusReport (/home/runner/work/_actions/github/codeql-action/v1/lib/util.js:205:28)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/setup-tracer.js:163:9) {
  name: 'HttpError',
```

@jhutchings1 Have you seen this in other CodeQL build right now?

PRs: https://github.com/envoyproxy/envoy/pull/12417/checks?check_run_id=945498206
https://github.com/envoyproxy/envoy/pull/12416/checks?check_run_id=945428645

**Comment by jhutchings1** [comment]
Thanks for the heads up @asraa! This looks like it's no longer reproducing based on https://github.com/envoyproxy/envoy/runs/946307314?check_suite_focus=true. Let me know if you're still seeing it, and I can ask engineering to drill in.

**Comment by asraa** [comment]
Will do! @antoniovicente I wonder if this is a flake. If we continue to see it, maybe we can add some automatic re-try.
