### ISSUE TITLE
Integrate with SkyWalking distributed tracing framework

### ISSUE THREAD

**Issue by zyfjeff** [envoyproxy/envoy#12486]
I am from Alibaba Cloud team. We provide cloud service for hosted Istio/Envoy as a mesh solution.
Some of our users are using Apache SkyWalking language agents in their services, now, they want to migrate to the Istio mesh solution.Apache SkyWalking has provided fully topology, metrics, and alarms solution in the service mesh scenario,
but we still want the Envoy could support tracing by following the SkyWalking data model, which is different from the Zipkin model.

The Context Propagation should follow this, Standard Header Item is enough for step one. 
https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v3.md

The spans should follow this, 
https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/Tracing.proto#L28-L31

@lizan

**Comment by lizan** [comment]
Thanks for raising this, we do also have similar use case. I'm happy to sponsor.

**Comment by wbpcode** [comment]
is any process for this work? @lizan We are about to do the same. But I don't know what the community's plans are.

**Comment by dio** [comment]
@wbpcode if you’re interested I think you can take this. I can help you on the review.

**Comment by dio** [comment]
I actually have an initial code for this. If you think it will be helpful for you to get started, I can share it with you.

**Comment by wbpcode** [comment]
@dio Thank you very much. I can try it out. Because we desperately need this feature and are willing to share the end result.
Where can I see your initial version? It would be very helpful.

**Comment by dio** [comment]
Here you are: https://github.com/envoyproxy/envoy/compare/master...dio:sky-tracer?expand=1. I think it compiles and I had a docker-compose setup to "manually" test it (two services, with envoys, oap-server, and UI), I'll clean up the test bed and share it with you.

**Comment by XuejiaoZhang** [comment]
Yup, thanks, will followup  there.

**Comment by XuejiaoZhang** [comment]
It will be great to have Skywalking integration with Envoy.

**Comment by wbpcode** [comment]
It's over. May be we can close it. @zyfjeff

**Comment by zyfjeff** [comment]
@wbpcode Great work, I'll close it
