### ISSUE TITLE
How to avoid communication between threads?

### ISSUE THREAD

**Issue by kishan-patel** [envoyproxy/envoy#12499]
We have a requirement where the server will tell our Envoy network filter which source IP and port to use for the outgoing egress TCP connection. 

The obvious issue that we need to solve is potential address already in use errors (i.e. when a message is received on one thread, and there is already a connection established on another thread with the same IP and port that we are instructed to use).

We are thinking of using a map that is shared across all threads, where the key would be the destination address + source address. Each thread would consult this map to see whether an entry exists for a given destination address + source address combination before deciding whether to create a new connection. 

This approach would involve using locks and would also deviate from Envoy's threading model, where threads don't really communicate with each other. Is there another way that this can be solved? Picking the thread based on which listener accepted the connection perhaps?

**Comment by antoniovicente** [comment]
What is the intended behavior when the requested source IP and port is already in use?

You may need to set some socket options to allow multiple connections to bind to the same local ip:port, and fail on connect if a connection with the same src and dest ip:port already exists.

It sounds like you need a locked data structure.  If you run into contention problems, I think the most you can do in this case is shard the map by source ip:port to reduce lock contention.

**Comment by kishan-patel** [comment]
Thank you for taking the time to reply.

> What is the intended behavior when the requested source IP and port is already in use?

We are expected to send the message over the already established connection (even though it may have been created on a different thread).

> It sounds like you need a locked data structure. If you run into contention problems, I think the most you can do in this case is shard the map by source ip:port to reduce lock contention.

This is the way that it has been implemented so far in the prototype that we are developing. However, we weren't sure whether it was the best approach due to all of the locking and communication between filters on different threads. Do you see a major problem with this solution or have an alternative suggestion in mind (broadcasting the message in all of the thread's TLS slot perhaps)?

**Comment by antoniovicente** [comment]
> Thank you for taking the time to reply.
> 
> > What is the intended behavior when the requested source IP and port is already in use?
> 
> We are expected to send the message over the already established connection (even though it may have been created on a different thread).

IIRC Buffer::Instance and Network::Connection objects are not thread safe.  I expect you will run into some problems unless you do sends by posting to the thread that owns the relevant connection and verify that the connection still exists in that thread prior to writing to it's output buffer.

> > It sounds like you need a locked data structure. If you run into contention problems, I think the most you can do in this case is shard the map by source ip:port to reduce lock contention.
> 
> This is the way that it has been implemented so far in the prototype that we are developing. However, we weren't sure whether it was the best approach due to all of the locking and communication between filters on different threads. Do you see a major problem with this solution or have an alternative suggestion in mind (broadcasting the message in all of the thread's TLS slot perhaps)?

**Comment by kishan-patel** [comment]
How would I go about posting from one worker thread to another? I was looking at the `runOnAllThreads(Event::PostCb cb)` method inside the `thread_local.h` interface, but it seems like you would only be able to invoke this method from the main thread.
