### ISSUE TITLE
Transparent udp proxy

### ISSUE THREAD

**Issue by chadr123** [envoyproxy/envoy#12513]
I'm working on the transparent udp proxy for envoy.
By my understanding, the udp filter system supports only one filter.

> void ListenerImpl::createListenerFilterFactories(Network::Socket::Type socket_type) {
  if (!config_.listener_filters().empty()) {
    switch (socket_type) {
    case Network::Socket::Type::Datagram:
      if (config_.listener_filters().size() > 1) {
        // Currently supports only 1 UDP listener filter.
        throw EnvoyException(fmt::format(
            "error adding listener '{}': Only 1 UDP listener filter per listener supported",
            address_->asString()));
      }

And udp filter system cannot utilize the existing original_src filter because it is not compatible with udp filter system.
So, I thought that there is no way to extend the existing original_src filter or add a new filter for that.
So, if I add a new option to udp_proxy filter for transparent udp proxy, it is feasible.

Actually I add a new option to udp_proxy and it works fine now but it is better to discuss with you to contribute this feature.
What do you think about this?
You can see the my WIP patch at https://github.com/chadr123/envoy/commit/aed05ad91bac70ef8e533890bb8ff9afc9fb111c

**Comment by chadr123** [comment]
Could you review my idea?

**Comment by mattklein123** [comment]
@chadr123 at a high level this LGTM, though you will need to use the socket open abstractions in the final PR (see https://github.com/envoyproxy/envoy/blob/master/source/common/network/socket_option_impl.h). Thank you!

**Comment by chadr123** [comment]
> @chadr123 at a high level this LGTM, though you will need to use the socket open abstractions in the final PR (see https://github.com/envoyproxy/envoy/blob/master/source/common/network/socket_option_impl.h). Thank you!

Thank you for your review.
I will revise my patch and will send a PR. :)
