### ISSUE TITLE
JWT Authentication Filter - add validation results to Attribute Context

### ISSUE THREAD

**Issue by peterwhitesell** [envoyproxy/envoy#12519]
In our Kubernetes and Istio based microservice platform, we capture traffic telemetry with dimensions derived from Envoy Attributes. This is a feature request to add attributes to the Attribute Context [1] based on the results from JWT Token Validation performed by the JWT Authentication Filter [2].
Without this information, we don't have visibility into _why_ authentication fails. We'd like to be able to distinguish between
* no token was presented
* token was presented with invalid signature
* properly signed token was rejected due to incorrect Audience, Issuer, etc.

*Relevant Links*:
[1] https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto.html
[2] https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter

**Comment by qiwzhang** [comment]
jwt_authn verification status defined [here](https://github.com/google/jwt_verify_lib/blob/master/jwt_verify_lib/status.h)  should have enough info.   We can save such status into filter metadata.  Will that be good eought?

**Comment by peterwhitesell** [comment]
@qiwzhang the statuses enumerated in that file are exactly (and well above and beyond!) the information I'm looking for. I'm swimming a bit over my head to understand if "saving such status into filter metadata" is the same as adding them to the attributes.

My end goal is to leverage them as attributes with Istio and [in their docs](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values) is stated "Istio exposes all standard Envoy attributes". Am I understanding correctly that when what you're proposing is implemented in Envoy, and the resulting envoy release is pulled into Istio, that all those JWT statuses would be available in Istio attributes?

**Comment by qiwzhang** [comment]
Yes,  once Envoy jwt_authn filter writes jwt_verify_status into metadata,  it think it will be part of `listerner_metadata`.

**Comment by mhite** [comment]
I can see that post 1.4.x (?) the response message bodies in failed JWT requests are now including information on why (ie. token expired, invalid signature, etc.). Does this mean the metadata is now enhanced also, and that there are new attributes available for metrics and logging of response status?

Thanks.

**Comment by qiwzhang** [comment]
Response to the downstream client has proper error messages.  But that info
is not in any fitlerState or Metadata.
If anyone wants to write the info to access log,  they can use {REPLY_BODY}
since jwt_authn is calling sendLocalReply() with the proper error message.
