### ISSUE TITLE
envoy on arm64

### ISSUE THREAD

**Issue by BitRacer** [envoyproxy/envoy#12511]
any chance an arm64 build will be made available?  im looking to get envoy and istio running on an arm64 cluster.

**Comment by dio** [comment]
@BitRacer do you think https://www.envoyproxy.io/docs/envoy/latest/install/building#arm64-binaries will help you?

**Comment by BitRacer** [comment]
@dio ill take a look. Im new to this part of k8s and really hoping to use my budget home microk8s cluster to envoy, istio, service mesh etc.  thanks for the lead.

**Comment by everflux** [comment]
I believe the docs are wrong:
Stable image is only intel: https://hub.docker.com/r/envoyproxy/envoy/tags/
Development includes arm64: https://hub.docker.com/r/envoyproxy/envoy-dev/tags/
But even the alpine development image is missing arm64 tags/manifest entries: https://hub.docker.com/r/envoyproxy/envoy-alpine-dev/tags

**Comment by mattmoor** [comment]
Hmm, I would love to see a fat released image here as well.

**Comment by cakoolen** [comment]
Is there a chance to get this re-opened since I would like such an image to be released as well.

**Comment by everflux** [comment]
Arm64 is already present, see https://hub.docker.com/r/envoyproxy/envoy/tags/
