### ISSUE TITLE
Envoy does external DNS request for hostname in /etc/hosts

### ISSUE THREAD

**Issue by cuonglm** [envoyproxy/envoy#12543]
I set my domain name in `/etc/hosts`, but envoy still does external DNS query for that domain:

```
{"level":"debug","service":"envoy","name":"upstream","time":"2020-08-03T09:58:25Z","message":"DNS request timed out 4 times"}
{"level":"debug","service":"envoy","name":"upstream","time":"2020-08-03T09:58:25Z","message":"transport socket match, socket default selected for host with address 127.0.0.100:80"}
{"level":"debug","service":"envoy","name":"upstream","time":"2020-08-03T09:58:25Z","message":"DNS refresh rate reset for does-not-exist.com, refresh rate 5000 ms"}
```

I expect envoy to skip the DNS query and always use the IP set in `/etc/hosts`. I can't find anywhere in the doc mention about envoy behavior with `/etc/hosts`.

**Comment by rshriram** [comment]
I think this is because of c-ares (the DNS library that envoy uses). You might want to look at the c-ares docs to see why it doesn't pick up the /etc/hosts.. They have some env vars to control the behavior

**Comment by gunsluo** [comment]
I have the same issue.  I use docker/docker-compose to run envoy and get the same error message.
