### ISSUE TITLE
gRPC timeout processing does not match gRPC semantics

### ISSUE THREAD

**Issue by dfawley** [envoyproxy/envoy#12578]
Description:

In gRPC, the client chooses a deadline before starting an RPC; this is a fixed point in time.  When sending the RPC, gRPC attaches a header (`grpc-timeout`) containing the remaining timeout as a duration (e.g. "10s").  Envoy reads this timeout duration and applies it internally, but only starts the timer after the client finishes sending the request data.  This may never happen in the case of long-lived streams (e.g. pubsub), or be significantly delayed in the case of client-streaming RPCs (e.g. a large file upload).

There are two fields in a route that can affect the gRPC timeout as Envoy handles it: `max_grpc_timeout` and `grpc_timeout_offset`.  We would like to continue to support these features, but apply the proper semantics to them.  There are are three main options for this:

1. Change the behavior and call it a bug fix.
2. Add a client capability that affects the behavior of these fields and the handling of the `grpc-timeout` header.
3. Add new fields with the proper semantics and deprecate the existing ones.

Secondarily, it might be worth considering if the gRPC semantics could be useful for non-gRPC streams as well.  For example, if a client is uploading much more data on a stream than expected, or if the server is reading the data slowly for some reason, the Envoy timeouts will never be applied, and the stream will be allowed to continue indefinitely.

References:

https://github.com/envoyproxy/envoy/blob/cf850688a93b8dea5705170a211ea98b77beda61/api/envoy/api/v2/route/route_components.proto#L960-L988

cc @htuch @markdroth @ejona86

**Comment by htuch** [comment]
Discussed earlier, but FTR I think I'm in favor of (3), since (1) might potentially break existing unary gRPC users and (2) adds special casing that can be avoided.

**Comment by dfawley** [comment]
What are the next steps here?

If there are new fields to specify a maximum grpc timeout & offset (3), but according to gRPC semantics, what will they be called and how will they work?  Who would be able to implement these changes?

**Comment by markdroth** [comment]
I think we can probably propose whatever field names and semantics we want.  We don't necessarily have to implement them in Envoy just to add them to the API (although it would be good if we have someone signed up to work on that as a follow-up item).

**Comment by dfawley** [comment]
Here would be my proposal for implementing (3):

```protobuf
message RouteAction {

  ...

  google.protobuf.Duration max_grpc_timeout = 23 [deprecated = true];
  google.protobuf.Duration grpc_timeout_offset = 28 [deprecated = true];

  ...

  message GrpcRouteActions {
    // If set, honor the grpc-timeout field in the request headers according to gRPC
    // timeout semantics, but limit it to the value specified here.  Also ignore the
    // timeout, max_grpc_timeout, and grpc_timeout_offset fields in this RouteAction.
    // If set to zero, no limit shall be applied.  If unset, the timeout for gRPC calls
    // is determined according to the timeout field as normal.
    //
    // TODO: Should the config_http_filters_router_x-envoy-upstream-rq-timeout-ms header
    // take precedence and apply Envoy semantics?  Should both be in effect, possibly?
    google.protobuf.Duration max_timeout = 1;

    // If set, honor the grpc-timeout field in the request headers according to gRPC
    // timeout semantics, but reduce the timeout of all gRPC calls by this amount.
    google.protobuf.Duration timeout_offset = 2;
  }

  GrpcRouteActions grpc_route_actions = ###;
}
```

**Comment by htuch** [comment]
@lizan @mattklein123 do you folks have any thoughts on this one?

**Comment by mattklein123** [comment]
I don't have a strong opinion on this one way or the other. If we do (1) we could put it behind a runtime flag in Envoy and call it a bug fix and see if anyone complains. (3) is also fine with me. Note that in Envoy we have the HCM request_timeout as well as the idle timeouts to protect against slow clients.
