### ISSUE TITLE
gRPC - Request/Response body as byte array/JSON

### ISSUE THREAD

**Issue by ashoke-cube** [envoyproxy/envoy#12626]
I have set up a lua filter for accessing the request/response details [headers and body] for a gRPC service. I am able to see proper headers data.  The request/response data is of the form _'userdata : xxxxxxxxxxx'_

For example:

`print (request_handle:body()) -> userdata: 0x40dae6a0`

1. Is there a utility to get the data in byte array/JSON format? 
2. I understand the conversion requires .proto files, how do I specify it in the filter?

**Comment by dio** [comment]
I'm started to think probably we need to consolidate C++ implemented utilities (that is exposed to the Lua world) into a dedicated "wrapper", either to be attached to the stream handle or available globally. 

We see e.g. 

1. https://github.com/envoyproxy/envoy/pull/12552 to add base64 encoding helper
2. https://github.com/envoyproxy/envoy/pull/10329 to add timestamping helper
3. This issue to add get JSON string from a protobuf message (this request also can be implemented in C++, using `MessageUtil::getJsonStringFromMessage`)

If attaching to stream handler wrapper is preferred (this is in line with `httpCall`):

```lua

function envoy_on_request(request_handle) {
  request_handle:utility().base64Encode("ok");
  request_handle:utility().currentTimestamp();
  request_handle:utility().getJsonStringFromProtoMessage(request_handle.body());
}
```

Or if we prefer it to be available globally,

```lua
function envoy_on_request(request_handle) {
  envoyBase64Encode("ok");
  envoyCurrentTimestamp();
  envoyGetJsonStringFromProtoMessage(request_handle.body());
}
```

cc. @mattklein123

**Comment by mattklein123** [comment]
Sure all of that SGTM @dio

**Comment by paawan01** [comment]
Is there anything currently available to achieve this in lua filter ?

**Comment by dio** [comment]
@paawan01 you can get the data "bytes", via `getBytes()` API.

`request_handle:body()` doesn't return a string. It returns a [buffer wrapper](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html#config-http-filters-lua-buffer-wrapper).

Hence a call to it ends up with a value that looks like `userdata: 0x40dae6a0` 

Try this instead:
```
local body = request_handle:body()
local bytes = tostring(body:getBytes(0, body:length()))
```

But yeah you can't really work with the encoded protobuf in Lua yet, but you can forward that data to another service.
