### ISSUE TITLE
Allow ignoring port in virtualHosts.domain

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#12647]
In our environments, sometimes ports are included in HTTP headers (ie `curl foo -H "Host: foo:1234"`). The tricky thing here is we do not know what port will be set here - due to fronting LBs, especially Kubernetes node ports, the port may be completely different from the listener port.

Envoy provides two mechanism to work around this problem:
* `strip_matching_host_port` - this does not work as the port needs to match the listener, in our case it does not
* Wildcard in the domain, like `foo:*` - This does not work because we need to support wildcard hosts. This would end up with `*.foo:* config being generated, which is not respected by Envoy

We would like some way to ignore the port, whether that is a `strip_matching_host_port` type flag that strips *all* ports or more advanced matching on domain, or something else entirely

**Comment by mattklein123** [comment]
> We would like some way to ignore the port, whether that is a strip_matching_host_port type flag that strips all ports or more advanced matching on domain, or something else entirely

IIRC This was discussed when strip_matching_host_port was added, and we decided to go for the less invasive option. Suggestions appreciated here of options that would work.

**Comment by howardjohn** [comment]
The only two options I can think of are:
* We could add another option like `strip_any_host_port`
* We could change domain matching to support `*.foo.com:*` in some way, whether that is allowing prefix+suffix wildcard or otherwise
But open to other ideas

**Comment by rshriram** [comment]
the domain matching is currently a trie. if we allow choice of another algorithm like linear search, then the virtual host can be a standard string match (most flexible, with regex et al). This will come with performance cost for gateways with 1000s of hosts.

alternatively, we could do the `strip_any_host_port` but somehow I feel like this is a bandaid to the underlying problem of flexible string matching at scale. it is also the fastest fix IMO>

**Comment by ramaraochavali** [comment]
I think it is better to add strip_any_host_port instead of waiting for reimplementing domain matching part. Fixed it https://github.com/envoyproxy/envoy/pull/14491. PTAL
