### ISSUE TITLE
bumping the version of protobuf

### ISSUE THREAD

**Issue by stedsome** [envoyproxy/envoy#12652]
When trying to bump the version of cel-cpp, it broke the current version of protobuf that envoy uses, which leads me to look into this issue. 

It turns out that protobuf 3.10.1, which is at this point, 10 months old. It would nice if someone is willing to take on this. I tried to do this on my own but it seems that it is more involving than just updating in repository_locations.bzl. Can someone familiar with protobuf look into this? 
@asraa

**Comment by moderation** [comment]
There was a short chat with @antoniovicente on Slack about this https://envoyproxy.slack.com/archives/C78HA81DH/p1595887714282900. I've also found that the latest protobuf breaks the build. @antoniovicente mentioned he had some local patches for this to work. It would be great if we could raise a PR to bump the protobuf version. I'm still planning on some PRs to bump other dependencies shortly.

**Comment by mattklein123** [comment]
This is done.
