### ISSUE TITLE
Bazel build with error “/usr/bin/ld.gold: error: cannot find libc++.a”

### ISSUE THREAD

**Issue by packyzbq** [envoyproxy/envoy#12679]
Hi, I am building envoy on mips and enconter an error when compiling net_zlib. The error is as follows:
```
/usr/bin/ld.gold: error: cannot find libc++.a
/usr/bin/ld.gold: error: cannot find libc++abi.a
```
I find the bazel uses rules_foreign_cc and will start a sandbox to compile zlib. The PATH env is set to `/root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/sandbox/processwrapper-sandbox/3/execroot/io_istio_proxy:/bin:/usr/bin:/usr/local/bin`,which doesn't include any libs such as libc++.a and  libc++abi.a

How can I solve this problem?

**Comment by lizan** [comment]
Can you paste the command you ran to build and the full output log? If you're using gcc/gold you shouldn't use libc++.

**Comment by packyzbq** [comment]
I solve the problem after installing the libc++-dev libc++abi-dev and setting clang-7 as the compiler.
