### ISSUE TITLE
Warmup of host for Java Applications

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#12678]
For applications developed using Java, when a new host starts, it takes a period of warmup to achieve the best performance. This leads to a possible demand scenario: For the newly started host, its weight in the load balancing process should be reduced. However, all current Envoy load balancing strategies do not support host warmup.
Is it possible to add a new type of load balancing? Or turn the load balancing strategy into a part of extensions, so that developers can expand and develop new load balancing strategies according to their needs?

**Comment by snowp** [comment]
Would this be satisfied by #11050 ?

**Comment by wbpcode** [comment]
Thanks. That's what I want.

**Comment by ejc3** [comment]
While slow start would be ideal, what we've done in our Kubernetes setup is before the readiness check succeeds for the first time, we send a good amount of local load (warm up url's) to the host.
