### ISSUE TITLE
admin: Certain clusters/listeners objects in config_dump don't give @type field when they are of Any type

### ISSUE THREAD

**Issue by lita** [envoyproxy/envoy#12674]
*admin*: Certain *clusters/listeners objects in config_dump don't give `@type` field when they are of `Any` type*

*Description*:
I am trying to marshal the output of /config_dump back to its proto object, but the marshaling fails because  [`StaticListener`](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/admin/v3/config_dump.proto#L88), [`DynamicListenerState`](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/admin/v3/config_dump.proto#L105), [`DynamicCluster`](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/admin/v3/config_dump.proto#L183) and [`StaticCluster`](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/admin/v3/config_dump.proto#L165) messages contain a nested `Any` type but config_dump doesn't produce a `@type` field for these nested proto messages.

Here is the output of the /config_dump with just static config and the latest envoy image from docker (v14.4):
* [Static Listener Dump](https://gist.github.com/lita/4bd7dbe9192c8ce169572f6f305290dc#file-config_dump-json-L635-L684)
* [Static Cluster Dump](https://gist.github.com/lita/4bd7dbe9192c8ce169572f6f305290dc#file-config_dump-json-L685-L724)

This is the output of /config_dump with the Istio's BookInfo example to show the `DynamicCluster` and `DynamicListenerState` case:
* [Dynamic Cluster](https://gist.github.com/lita/879b795fe12079e2d522691145a6f995#file-istio_config_dump-json-L500-L503)
* [Dynamic Listener](https://gist.github.com/lita/879b795fe12079e2d522691145a6f995#file-istio_config_dump-json-L1844-L1850)

Note that these objects are of `Any` type but do not have a `@type` field.

My guess is that this is an issue with the proto marshaling code vs what is admin code is doing, but Harvey suggested to make an issue anyway.

cc @htuch

**Comment by htuch** [comment]
I wonder if it's somehow being lost around https://github.com/envoyproxy/envoy/blob/master/source/server/admin/admin.cc#L640, i.e. in the JSON rendering. Is it reasonable to add an `ENVOY_LOG` and dump out `dump.DebugString()` as well as the JSON after conversion?

**Comment by lita** [comment]
Sure, I can try to get that.

**Comment by lita** [comment]
Okay, so I added these logs line in the admin code:

```cpp
  ENVOY_LOG(info, dump.DebugString());
  response_headers.setReferenceContentType(Http::Headers::get().ContentTypeValues.Json);
  const auto jsonString = MessageUtil::getJsonStringFromMessage(dump, true);
  response.add(jsonString); // pretty-print
  ENVOY_LOG(info, jsonString);
```

And it does look like the dump does contain the type information.
```
        clusters {
          name: "accounts"
          type: STATIC
          connect_timeout {
            nanos: 250000000
          }
          dns_lookup_family: V4_ONLY
          load_assignment {
            cluster_name: "accounts"
            endpoints {
              lb_endpoints {
                endpoint {
                  address {
                    socket_address {
                      address: "127.0.0.1"
                      port_value: 8081
                    }
                  }
                }
              }
            }
          }
          183412668: "envoy.api.v2.Cluster"
        }
```

But the json output does not:

```json
"static_clusters": [
    {
     "cluster": {
      "@type": "type.googleapis.com/envoy.api.v2.Cluster",
      "name": "accounts",
      "type": "STATIC",
      "connect_timeout": "0.250s",
      "dns_lookup_family": "V4_ONLY",
      "load_assignment": {
       "cluster_name": "accounts",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 8081
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2020-08-19T00:01:52.850Z"
    }
   ]
  }

```

I turned off pretty print and that didn't help.

```json
{"listeners":[{"name":"ingress_http","address":{"socket_address":{"address":"0.0.0.0","port_value":80}},"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","stat_prefix":"ingress_http","route_config":{"virtual_hosts":[{"name":"default","domains":["*"],"routes":[{"match":{"prefix":"/accounts"},"route":{"cluster":"accounts","idle_timeout":"15s"}}]}]},"http2_protocol_options":{"max_concurrent_streams":100,"initial_stream_window_size":65536,"initial_connection_window_size":1048576},"use_remote_address":true,"stream_idle_timeout":"300s","request_timeout":"300s","common_http_protocol_options":{"idle_timeout":"3600s","headers_with_underscores_action":"REJECT_REQUEST"}}}]}]}],"clusters":[{"name":"accounts","type":"STATIC","connect_timeout":"0.250s","dns_lookup_family":"V4_ONLY","load_assignment":{"cluster_name":"accounts","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"address":"127.0.0.1","port_value":8081}}}}]}]}}]}
```

**Comment by dio** [comment]
@lita @htuch do you think having an option to return proto text format (instead of JSON) will be helpful here?

**Comment by dio** [comment]
I'm not sure but seems like the part you have highlighted in https://github.com/envoyproxy/envoy/issues/12674#issuecomment-675786843 is part or `BootstrapConfigDump`, i.e. [BootstrapConfigDump.bootstrap](https://github.com/envoyproxy/data-plane-api/blob/a89e7e0ace1474032e3775808429cbebc8a7efd9/envoy/admin/v3/config_dump.proto#L69), which has `config.bootstrap.v3.Bootstrap` type where the `static_resources.listeners[*]` type is "unwrapped" [`listener.v3.Listener`](https://github.com/envoyproxy/data-plane-api/blob/a89e7e0ace1474032e3775808429cbebc8a7efd9/envoy/config/bootstrap/v3/bootstrap.proto#L54), not an `Any`.

The `Any` part of that listener will be [here](https://gist.github.com/lita/4bd7dbe9192c8ce169572f6f305290dc#file-config_dump-json-L764-L769). Enclosed in [this object](https://gist.github.com/lita/4bd7dbe9192c8ce169572f6f305290dc#file-config_dump-json-L759-L760) with `envoy.admin.v3.ListenersConfigDump` as its type.

**Comment by lita** [comment]
Ah yeah, my bad @dio. It looks like I was looking in the wrong field. Seems like this is not a problem with vanilla envoy. Let me try upgrading the istio and seeing if it is a problem there.

**Comment by dio** [comment]
I can see that when running `istio/proxyv2:1.4.9` which is `envoyproxy/envoy v1.12.x`. Looking at the proto at that time: https://github.com/envoyproxy/envoy/blob/a624dee970f41f1c4030d6d5c368692b30417aca/api/envoy/admin/v2alpha/config_dump.proto#L109 it is "unwrapped" [`api.v2.Cluster`](https://github.com/envoyproxy/envoy/blob/a624dee970f41f1c4030d6d5c368692b30417aca/api/envoy/admin/v2alpha/config_dump.proto#L109).

**Comment by lita** [comment]
Ohh I see. My bad. So I just need to use the older proto objects and use jsonpb. My bad. Thanks @dio for pointing this out. Ended up being an issue with version mismatch.
