### ISSUE TITLE
Using Rate Limiting with Dynamic Metadata

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#12688]
Hi, I'm trying to configure the Rate Limiting Filter using Dynamic Metadata information as the key value descriptor being sent (as documented here: https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action-dynamicmetadata). However when I try this, I get the following error and it seems like the "dynamic_metadata" field is not recognized 

> Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[0].rate_limits[0].actions[0]) dynamic_metadata: Cannot find field.) has unknown fields

My Rate Limiting section under the route config looks like this: 
<pre>
rate_limits:
  - stage: 0
    actions:
    - dynamic_metadata:
        descriptor_key: xxxx
        metadata_key:
          key: envoy.filters.http.jwt_authn
          path:
            - key: xxxx
</pre>

And the filter config looks like this:
<pre>
http_filters:
- name: envoy.filters.http.ratelimit
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
    stage: 0
    domain: xxxx
    failure_mode_deny: false
    timeout: 0.25s
    rate_limit_service:
      grpc_service:
        envoy_grpc:
          cluster_name: rate_limit_service
</pre>

I have also tried using the Rate Limit Override option (https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/http/http_filters/rate_limit_filter#rate-limit-override) 
but in that case the "limit" field is not recognized. 

I am on Envoy version 1.15.0, which is the version of documentation I have been using, and I have also tried the latest dev version (envoy-alpine-dev:latest) with the same results.

Is this an issue with my configuration, my build, or a bug?

Thanks for any help.

**Comment by Pchelolo** [comment]
I wonder if you are indeed using v3 config for the `http_connection_manager`? Try specifying 

```
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        ... blablabla
```

We are using it [successfully](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/charts/api-gateway/templates/_config.yaml#123) with v3 config and envoy 1.15

**Comment by jaegchoi** [comment]
> I wonder if you are indeed using v3 config for the `http_connection_manager`? Try specifying
> 
> ```
>     filter_chains:
>     - filters:
>       - name: envoy.filters.network.http_connection_manager
>         typed_config:
>           "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
>         ... blablabla
> ```
> 
> We are using it [successfully](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/charts/api-gateway/templates/_config.yaml#123) with v3 config and envoy 1.15

That was actually the issue! Thanks so much
