### ISSUE TITLE
on-demand VHDS not work correctly

### ISSUE THREAD

**Issue by kkHAIKE** [envoyproxy/envoy#12683]
sorry my poor eng :)
On branch master,  the vhds http filter will skip handle all request, it cause allways get 404 code(empty main route)
in other words, let me show you the code...

https://github.com/envoyproxy/envoy/blob/51551ae944c642e6fc61563cbea8653087e70f1f/source/extensions/filters/http/on_demand/on_demand_update.cc#L12-L24
1. all request will continue to empty router, because of the code will never run into L18
2. gdb bp L14 ,  *usesVhds* always be false and *routeConfig* type is *NullConfigImpl*
3. *routeConfig* is read from https://github.com/envoyproxy/envoy/blob/51551ae944c642e6fc61563cbea8653087e70f1f/source/common/router/rds_impl.cc#L252-L254

after review the code, i find the reason

1. config init here: https://github.com/envoyproxy/envoy/blob/51551ae944c642e6fc61563cbea8653087e70f1f/source/common/router/rds_impl.cc#L232-L237
2. and update here: https://github.com/envoyproxy/envoy/blob/51551ae944c642e6fc61563cbea8653087e70f1f/source/common/router/rds_impl.cc#L256-L264
3. but if first RDS response is got, prog will run into here and not call onConfigUpdate: https://github.com/envoyproxy/envoy/blob/51551ae944c642e6fc61563cbea8653087e70f1f/source/common/router/rds_impl.cc#L128-L139
4. so TLS config is keep inited null.

ping @dmitri-d 
[config_dump.txt](https://github.com/envoyproxy/envoy/files/5084020/config_dump.txt)

**Comment by kkHAIKE** [comment]
i was make a simple patch, need review https://github.com/kkHAIKE/envoy/commit/a09c9552bc01de9cb617c5a395e7cb91c3006f5f

**Comment by lizan** [comment]
@dmitri-d

**Comment by dmitri-d** [comment]
It looks like the issue you are seeing will be triggered every time both rds and vhds configurations change together. I think the change you are proposing should resolve the problem; could you create a PR and also add a test for the change?
