### ISSUE TITLE
[question] Can accesslog record each upstream_host and upstream_response_code when retrypolicy on?

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#12698]
Hello:
   I want ask some question about envoy http accesslog.
   Can accesslog record each upstream_host and it's response_code when retry?
   I use the %UPSTREAM_HOST% , it only record the last reqeust upstream_host.
   I want to the log show like this:
      upstream_host:"192.168.1.1:80","192.168.1.2:80","192.168.1.3:80"
      response_code:     503 ,                       503      ,          200

**Comment by ggreenway** [comment]
Not exactly like that, but if you specify an `upstream_log` in the http connection manager, it will log each upstream attempt on a separate entry. The downstream and upstream logs can be linked by including a common field (downstream address:port, trace-id, etc).

**Comment by pyrl247** [comment]
I see,Thank u~ But here r some other problem , I set upstream_log like this:
`

          http_filters:
          - name: front-router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_log:
                name: envoy.file_upstream_log
                filter:
                  status_code_filter:
                    comparison:
                      op: GE
                      value:
                        default_value: 500
                        runtime_key: "..."
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /data/envoylogs/upstream.log
                  json_format:
                   upstream_status: '%RESPONSE_CODE%'

it shows each upstream attempt , but It seems the %RESPONSE_CODE% always be 0 during upstream_log. It work fine when use access_log in HttpConnectionManager.

**Comment by ggreenway** [comment]
I'm not sure why that's always printing zero. I have a similar config, but without the `filter` and using `format` instead of `json_format`, and it's working as expected.

**Comment by pyrl247** [comment]
Thank u! I will try it your way.
