### ISSUE TITLE
Teach domains to allow trailing wildcards / unknown ports in Host

### ISSUE THREAD

**Issue by cmaloney** [envoyproxy/envoy#1269]
The "domains" configuration within a virtual_hosts of a route config allows wildcards at the start of the domain currently, but not the tail.

This means If I do something (like for local development) where I run envoy on port 8080 locally with a name based virtual host / domains set (ideally the same one i'm going to be deploying), I have to match the port exactly inside the domains, otherwise the request doesn't match and I get a 404 from envoy, which has no immediate debugging feedback as to why it's happening

Open to writing up a patch to help implement this, but not sure what's the approach that would be preferred:
1. Match domains excluding the port
2. Allow "trailing" wildcards, so things like `example.com:80*`, `example.com:*` would properly function

Some other option I haven't thought of here.

**Comment by mattklein123** [comment]
This is kind of related to https://github.com/lyft/envoy/issues/886. 

I would be in favor of (1) if you want to do a patch. I thinking having an option to "ignore port" when doing domain matching would be useful (basically just strip the port component of authority if it is present and the user asks for it). Code you need to modify is roughly here: https://github.com/lyft/envoy/blob/master/source/common/router/config_impl.cc#L555

**Comment by 9len** [comment]
we've bumped into the ignore-port use case several times, and it feels pretty universal when ports are dynamically allocated.

**Comment by bartebor** [comment]
@mattklein123 It would be really useful to have possibility of having trailing wildcard for virtual host domains, such as `app1.*`, `app2.*` just like  [nginx's `server_name`](http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name) allows. It is very convenient when envoy's listener port is exposed with wildcard DNS name with CNAMEs or during development. Are there any cons of supporting such scenario? We could compare domains in sequence as they appear in routing or use more efficient way like hashing.

**Comment by mattklein123** [comment]
@bartebor I think it's reasonable to support if someone wants to do a patch.

**Comment by htuch** [comment]
@bartebor @mattklein123 I'd like to see this implemented in a scalable, performant way. I think an inverted trie would do this.

**Comment by bartebor** [comment]
I looked into the code and found that [current implementation](https://github.com/envoyproxy/envoy/blob/master/source/common/router/config_impl.cc#L944) of wildcards searches unordered maps with keys of descending length.  

Wildcard at the end are essentially the same in terms of searching and could be implemented similarily without need of new data structure.

@htuch, would you like to have current implementation replaced with something new?
