### ISSUE TITLE
Tail latency of envoy proxy is bad if every request create a new connection

### ISSUE THREAD

**Issue by NonStatic2014** [envoyproxy/envoy#12718]
We have envoy running as the front door service basically doing
1. JWT token validation for auth
2. Routing based on dynamic routing config

We have monitored the upstream duration and total duration (envoy + upstream duration). What we noticed was: if sending request to this service every 5 seconds and each time use a new connection, we could see ~2% requests have significant long latency of upstream and total duration. I checked the upstream telemetry for each long latency request but the result looks normal. 

For example a request could have 2200 ms of upstream duration, 2202 ms of total upstream, the request handled by upstream cluster within 300 ms. 

But if the client keep a connection alive and use the same connection sending requests every 5 seconds, we could **NOT** repro this issue. 

Does anyone have any idea if this is a configuration issue we overlooked? Thank you!

**Comment by mattklein123** [comment]
This seems generally expected. Creating new connections is costly. Can you explain why you think this shouldn't be the case?

**Comment by NonStatic2014** [comment]
I expect once a connection between envoy to upstream cluster is created, it will be alive for a long while(e.g. 1hr). When a request comes to envoy, envoy will reuse the existing connection to talk to upstream cluster and get back result. Is this not the case?

**Comment by NonStatic2014** [comment]
I would expect the connection creation latency on the client <--> envoy side, but not envoy <--> upstream side. 

If every time a new connection from client is created, envoy <--> upstream need to recreate connection, I would expect all requests having longer upstream duration, but now we only see ~2% of them.

**Comment by mattklein123** [comment]
By default Envoy does keep alive upstream connections. You will need to take a look at stats, logs, etc. to see why that is not happening for your use case.

**Comment by NonStatic2014** [comment]
I run the test again this morning with Prometheus monitoring the upstream active connection and see below results. The first part was `curl` to the endpoint every 5 seconds; the second part was the use the same connection sending request every 5 seconds. Can you give me a suggestion on which setting(s) I should look into? @mattklein123 , Thank you!

![image](https://user-images.githubusercontent.com/9442504/90680516-d17cdb00-e216-11ea-9da3-5b874eba396e.png)

**Comment by NonStatic2014** [comment]
I also noticed: If I have two clients to reach this envoy and eventually reach the same upstream:
1. First one generate 600 QPS, latency looks expected.
2. Second one generate 1 request every 5 seconds using curl (each time create a new connection)

The second one still can repro this issue! I hope this information could be helpful. Thanks!

**Comment by yanavlasov** [comment]
Envoy also provides the `upstream_cx_connect_ms` stat that may tell you if connection establishment takes a long time. Other than that I do not think there are any other stats the can help you determining high latency of upstream requests if you are measuring high `upstream_rq_time` values (I assume this is what you are looking at).

**Comment by NonStatic2014** [comment]
Get back to this thread with my finding. 

I noticed that for each upstream cluster, if I set `tcpKeepalive` setting to some reasonable numbers, then the connection will be persisted and the tail latency in this case could much better than before. 

So the follow-up questions would be: Is there any side-effect to make this change? Why envoy does not have this enabled by default? 

Thanks!

**Comment by antoniovicente** [comment]
TCP keep alives do require periodically sending extra packets over the network.  There are costs, specially for endpoints that are part of mobile networks which may not have assigned dedicated channels 100% of the time.

What TCP keepalive parameters are you setting?

Also, where are your upstreams located?  Is it possible that there's a stateful NAT between the envoy and the upstreams that ends up benefit from the TCP keepalive traffic, and the absence of these keep-alives eventually results in some TCP connections pointing to an unknown destination or a machine that has seen been turned off?
