### ISSUE TITLE
Proposal: introduce ignore_vh_rate_limits setting for a route

### ISSUE THREAD

**Issue by Pchelolo** [envoyproxy/envoy#12714]
**Rational**

We have a virtual host setup with a fairly complex routing configuration and all routes have the same rate limits. We want to exempt a couple of routes from the limits (in our case routes for docs, but it's easy to imagine other examples of routes that need to be excluded from rate limiting). Currently, it's possible to achieve this in 2 ways:
- Copy the rate limiting config to each route explicitly. This is fairly verbose and prone to errors when updating the config. Even using yaml references makes it easy to forget adding a limit when introducing a new route
- Move the rate limit config to VH level and use `include_vh_rate_limits` option. This works for limited routes, but for the routes that are exempt we need to define some bogus descriptors, cause `include_vh_rate_limits: false` does not exclude VH limits if the route rate limit policy is empty. This is not the end of the world, but this makes envoy send an unnecessary request to the service, and looks hacky.

**Proposal**

Introduce explicit `ignore_vh_rate_limits` setting into route, `false` by default. If it's set to `true`, the VH rate limits will be ignored regardless of whether the route provided any rate limiting policy of its own.

Alternatively to introducing a new setting, `include_vh_rate_limits` could be deprecated and replaced with a enum setting `vh_rate_limits = [ IGNORE, INCLUDE, OVERRIDE ]` with the semantics:
- IGNORE - **do not use** virtual host rate limits **regardless** whether route has rate limit policy
- INCLUDE - **use** virtual host rate limits **regardless** whether route has rate limit policy - equivalent to `ignore_vh_rate_limits = true`
- OVERRIDE - **use** virtual host rate limits **unless** route has rate limit policy - equivalent to `ignore_vh_rate_limits = false`

I personally prefer the second idea for the API even though it requires deprecating a field, it seem more clear, but leaving the decision to the maintainers.

We will provide implemetation/testing, seeking comments/approval.

**Comment by mattklein123** [comment]
+1 on the 2nd option, thank you!
