### ISSUE TITLE
Trying to generate clang.bazelrc using bazel/setup_clang.sh results in an error

### ISSUE THREAD

**Issue by dmitri-d** [envoyproxy/envoy#12717]
The error is `ERROR: at most one key may be specified` and it's due to bazel unable to handle starlark flags in bazerc (see https://github.com/bazelbuild/bazel/issues/11301). 

https://github.com/envoyproxy/envoy/pull/12376 is the commit that introduced the breaking change. The issue has been fixed in bazel 3.3.0.

**Comment by mattklein123** [comment]
cc @lizan
