### ISSUE TITLE
Support custom verification logic for certificates in TLS context configuration

### ISSUE THREAD

**Issue by crazytan** [envoyproxy/envoy#1272]
Currently in TLS context [config](https://lyft.github.io/envoy/docs/configuration/listeners/ssl.html#config-listener-ssl-context), we can specify which client certs are accepted by using `verify_certificate_hash` or `verify_subject_alt_name`. However this is not sufficient if we want to do more complicated authorization based on certs, e.g., wildcard matching or verification based on other field. So my question is: is there any plans to support more complex verification configs or custom hooks?

More context on this: we're working on a framework called [SPIFFE](https://spiffe.io/) that is similar to Istio Auth but not limited to Kubernetes. And we're using envoy as a sidecar proxy to do mTLS communication between all services. It seems that the current TLS config is not enough if we want to do any serious authorization policies based on certs.

**Comment by mattklein123** [comment]
@crazytan definitely open to more complex stuff but will need specifics on what you are looking for. Can you provide more explicit details on what you need? cc @PiotrSikora @myidpt

**Comment by crazytan** [comment]
@mattklein123 since we're still in an early phase of designing, I may not have all the use-cases yet. However one thing we definitely want is to wildcard matching on subject alternative name.

**Comment by mattklein123** [comment]
@crazytan config proposals and PRs welcome.

**Comment by myidpt** [comment]
In Istio, we rely on a filter to call out to Mixer (another component) to do AuthZ. Can you tell why you want to implement the logic here?

**Comment by crazytan** [comment]
@myidpt well first of all, since service-to-service communication happens often, we're afraid that relying on another component to do authz may be slow; second, there's already limited form of matching going on with dnsname. It could be handy if URI matching also supports wildcard.

**Comment by myidpt** [comment]
Sure. Actually the filter does not need to call out to mixer - you could implement all the logic in the filter itself. Adding a wildcard support to verify_subject_alt_name  seems fine to me, but I'm a little concerned about supporting custom hooks in SSL context. It complicates the ssl context code.

**Comment by crazytan** [comment]
@myidpt Yeah I agree that custom hooks may be excessive. But wildcard support for verifying SAN seems totally reasonable to me.

**Comment by ramaraochavali** [comment]
@mattklein123 Probably this can be closed now that we have agreed that generic SPIFFE validation can be supported with this issue https://github.com/envoyproxy/envoy/issues/3883

**Comment by mattklein123** [comment]
Sounds good, closing. Thank you!
