### ISSUE TITLE
Support hash policy in the udp proxy

### ISSUE THREAD

**Issue by chadr123** [envoyproxy/envoy#12725]
The udp proxy does not support hash based lb algorithms perfectly because it does not provide LoadBalancerContext when choose a host.
So, the udp proxy with hash based lb algorithms will select a host by random manner.

I have investigated the tcp case and I found that it has the hash policy option.
So, I think that we can support it in udp case as well simply.

Here is the my draft version of implementation : https://github.com/chadr123/envoy/commit/d95c3f527e3cf130a80d473f2d22a7a1591ce7fa

Could you review my idea?

**Comment by mattklein123** [comment]
@chadr123 please see https://github.com/envoyproxy/envoy/issues/9514 of which I think this is a duplicate. Would love for you to implement that so let's continue the discussion there?
