### ISSUE TITLE
stats: Ability to not count health checks

### ISSUE THREAD

**Issue by JKerwood** [envoyproxy/envoy#12760]
**Title:** Ability to not count health check paths in statistics

**Description:** With multiple nodes and a mesh of upstream and downstream the count of health checks can get high.  Weeding this out the real requests especially during canary deployments / low volume times is difficult.
Having the ability to configure the statistics to ignore /health for example would help us see statistics on the real requests and not the fast health check urls.

**Comment by mattklein123** [comment]
Which stats are you asking about specifically? Health checks are excluded from certain stats already, like HTTP response codes.

**Comment by JKerwood** [comment]
I'm asking about application level health checks.  So health checks from Kubernetes, health checks from envoy to another pod.  Would the request into the other pod not be counted as a request?

**Comment by mattklein123** [comment]
If you use https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/health_check_filter any incoming health check requests will be marked as such and not count in stats.

**Comment by JKerwood** [comment]
I've tried setting the health_check_filter and I still get counts in my stats.  Maybe I'm doing it wrong?
