### ISSUE TITLE
stats: Provide TLS certificate expiration metric

### ISSUE THREAD

**Issue by efe-selcuk** [envoyproxy/envoy#12780]
#### Description

For organizations that are managing certificate lifecycles, having Envoy provide a metric that surfaces this would allow monitoring across the entire fleet, without relying on the lifecycle management to rotate certificates in time. This is useful whether or not the certificates have short validity periods, but it's especially useful for long validity periods where the certificate management process may not be regularly exercised.

The format could be something like `cluster.clustername.ssl.certificate.expiry: <seconds to expiration>`

**Comment by efe-selcuk** [comment]
Ah, I missed this, it's on [the statistics page](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/statistics), thanks. And I'm also now discovering `/certs` endpoint, which provides the metric per cert, which I think is important. I'll take a note to see how I might have found these more easily.

It looks like `days_until_first_cert_expiring` was present from the initial import so I couldn't find any supporting docs; do you happen to know why it was implemented in that way?

At first thought I think there's still value in providing the metric, per certificate/cluster/listener, via `/stats` (since it's what's actually being monitored, and the tooling exists to split across the dimensions), so the org doesn't have to manually inspect (or build tooling) for `/certs` to determine what needs rotation. Do you agree?

**Comment by mattklein123** [comment]
> It looks like days_until_first_cert_expiring was present from the initial import so I couldn't find any supporting docs; do you happen to know why it was implemented in that way?

Because we used it for the type of monitoring you are asking for at Lyft. :+1: 

> At first thought I think there's still value in providing the metric, per certificate/cluster/listener, via /stats (since it's what's actually being monitored, and the tooling exists to split across the dimensions), so the org doesn't have to manually inspect (or build tooling) for /certs to determine what needs rotation. Do you agree?

I don't feel strongly about it. There is always the issue of stats cardinality explosion with this type of stuff. A single metric + the certs endpoint has always been good enough for our ops usage but if you want to do a proposal feel free.

**Comment by efe-selcuk** [comment]
I see, appreciate the insight. I'll go back to the team and see if this is sufficient for what we want to deliver.
