### ISSUE TITLE
[Spelling] Mass clean-out of one-off spelling terms

### ISSUE THREAD

**Issue by wrowe** [envoyproxy/envoy#12807]
The https://github.com/envoyproxy/envoy/blob/master/tools/spelling/spelling_dictionary.txt file is littered with single-use keywords, often keywords specific to one platform/implementation.

As pointed out by @ggreenway https://github.com/envoyproxy/envoy/pull/12716#discussion_r475781460 we can resolve most of these on a permanent basis by placing these terms in backticks.

This is a tracking issue to solicit cleanup. The @envoyproxy/windows-dev crew are happy to take some of this on to unwind the use of many Windows terms from the spelling dictionary.

**Comment by mk46** [comment]
Hi @wrowe,  I would like to take up this.

**Comment by ggreenway** [comment]
> Hi @wrowe, I would like to take up this.

@mk46 Go for it. I'd recommend doing it in reasonable sized chunks, not one enormous PR. It makes it much easier to review.

**Comment by Bhaarat-khatri** [comment]
Is this issue is still open. I can see above one patch is merged. Is anyone is working on it please tell me otherwise please assign it to me

**Comment by ggreenway** [comment]
@Bhaarat-khatri In the last PR working on this, it felt like more work than it was worth to figure out what should and what shouldn't be in the dictionary. If you really want to take a stab at it, go ahead, but there's a good chance it won't make it through the review process.

If you don't feel like you want to work on this, I think I'll take no-stalebot off of this issue.

**Comment by wrowe** [comment]
I agree it's a hassle, but I will take point on reviewing proposed PR's

**Comment by siddharthkhonde** [comment]
hi. is this still open? I can take a look into this as a beginner.

**Comment by ggreenway** [comment]
I think we decided this isn't worth the trouble; it's a lot of toil for almost no gain. Closing.
