### ISSUE TITLE
x-b3-sampled is always set to 0 when x-request-id is not formatted as UUID

### ISSUE THREAD

**Issue by aogonevskiy** [envoyproxy/envoy#12808]
I had an issue with jaeger/zipkin tracing not working in Istio when requests to my service were going through kubernetes ingress controller (https://stackoverflow.com/questions/63507749/x-b3-sampled-header-is-always-set-to-0-when-accessing-service-through-ingress-co). Took me few days to figure out that it was caused by a format of x-request-id header used by ingress controller. Envoy proxy expects it to be an UUID and ingress controller passes it as a non-formatted random string (e.g. `x-request-id: 60e82827a270070cfbda38c6f30f478a`). In this case envoy quietly sets x-b3-sampled header to 0 and none of the requests are getting sampled.

So I guess this is not a bug report but more of a question. By looking at the code it seems like envoy uses request id to pass sampling decision when request id is getting generated internally (which is totally fine).  But my understanding is that x-request-id is a non-standard header and when it is getting passed from the outside envoy is basically enforcing the format of the header. It has to be UUID for tracing to work. Should there be an option to handle this scenario more gracefully?

**Comment by objectiser** [comment]
Not sure of the history behind using `x-request-id` to carry the tracing decision - but this should be the responsibility of the tracing provider using its own trace context format - which I believe is the case now.

So potentially modifying the `x-request-id` is no longer required?

cc @mattklein123

**Comment by mattklein123** [comment]
The history is that using x-request-id allows for stable sampling of access logs as well as tracing. That's why it was done that way originally. This has come up multiple times and now the x-request-id handling is extensible, though there is no other OOB implementation. cc @euroelessar
