### ISSUE TITLE
RBAC Network filter Stat Naming

### ISSUE THREAD

**Issue by rene-m-hernandez** [envoyproxy/envoy#12813]
When using the RBAC network filter, the following statistics are output:
```
{prefix}rbac.allowed: 0
{prefix}rbac.denied: 0
{prefix}rbac.shadow_allowed: 2
{prefix}rbac.shadow_denied: 2
```

Where `{prefix}` is the `stat_prefix` set here: https://www.envoyproxy.io/docs/envoy/v1.14.2/api-v2/config/filter/network/rbac/v2/rbac.proto#config-filter-network-rbac-v2-rbac

This formatting does not seem follow the formatting of other statics e.g. `cluster.*`, `htttp.*`, `listener.*`; this can be problematic for existing metric integrations e.g. [DataDog](https://docs.datadoghq.com/integrations/envoy/). Would it be possible to align the RBAC network filter stat reporting with other Envoy metrics? e.g. `rbac.{stat_prefix}.*`

**Comment by mattklein123** [comment]
cc @kyessenov @yangminzhu
