### ISSUE TITLE
[Redis] Add support for redis modules

### ISSUE THREAD

**Issue by inf-rno** [envoyproxy/envoy#12822]
*Description*:
We at Shopify are looking to add CAS support to redis similar to how it functions in [memcached](https://github.com/memcached/memcached/wiki/Commands#cas). We plan on doing this with the use of redis [modules](https://redis.io/modules). Effectively, we will be adding to the command set with things like `cas.get`, `cas.set`, etc. and would like envoy to be able to route them correctly. The general problem is to support custom commands that redis allows through its modules.

We could of course run our own fork and add the required commands to [supported_commands.h](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/common/redis/supported_commands.h). But my proposal is to make this available via configuration in the redis filter. We could add a config like:

```
"modules": [
  {
      name: "cas",
      commands: {
          simple: ["cas.get",...],
          write: ["cas.set",...],
          mset: ["cas.mset",...],
          ...
      }
  },
  ...
]
```

We could add this to the top level [config](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto) or to the connection pool [settings](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#envoy-api-msg-config-filter-network-redis-proxy-v2-redisproxy-connpoolsettings) whichever make sense for the implemenation/semantics.

If we agree on the feature and the proposal then I can work on implementing it.  Thank you. cc @mattklein123 @HenryYYang

**Comment by mattklein123** [comment]
Yes this makes sense to me. I don't have a strong opinion on where to put it in the config. @HenryYYang @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg?

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
Seems reasonable. I definitely think it's better to avoid adding non-mainline commands to supported_commands.h. In terms of where to put it, I think the listener makes sense- especially as the same listener can mirror traffic to multiple clusters. I don't have a strong opinion on where to stick it inside the redis config section of the listener.

Another consideration is that we currently don't support certain commands in cluster mode, such as scan. I assume we cannot validate that the our custom command config will work for sure on startup, however.
