### ISSUE TITLE
Create New Header Matcher

### ISSUE THREAD

**Issue by murray-stripe** [envoyproxy/envoy#12826]
I'd like to propose (__and implement__) a new header matcher (for `config.route.v3.HeaderMatcher`). Internally we have a need to match a header using the `range_match` (`type.v3.Int64Range`) field. However, the value that is being matched on is actually created by a custom filter on the downstream Envoy.

This filter generates this header by hashing the value of another header. It would be useful if this could all exist in a single place under the header-matcher. This new matcher would hash some header and then perform a range-match. I imagine the configuration of the `HeaderMatcher` would look like such:

```yaml
name: X-my-header
hash_match:
  start: 0
  end: 123456
```

The hash that it generated would exist in some fixed range (e.g. whatever would fit in `uint64_t`).

**Comment by mattklein123** [comment]
This feels a bit specific to me. What about making an extension point that could be used for a custom matcher?

**Comment by murray-stripe** [comment]
I think that sounds extremely reasonable. I'll start putting something together.

**Comment by murray-stripe** [comment]
Please feel free to point me toward any code or anything I should know for building out a new extension point. Otherwise I'll grep around the code-base and attempt to model off of something else that seems similar in shape.

**Comment by mattklein123** [comment]
Take a look at https://github.com/envoyproxy/envoy/blob/d321ede4d262cc2259064337be7b407e463ede24/api/envoy/config/overload/v3/overload.proto#L44 (or just generally search for typed_config) and you can find some good examples.
