### ISSUE TITLE
Plumb v2 protos into existing v1 xDS APIs

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1284]
As an initial stepping stone towards the v2 APIs, we will be splitting the existing implementation of the v1 APIs into two distinct modules:
1. The internal API for xDS modules (e.g. ` EdsClusterImpl : public BaseDynamicClusterImpl`), which will have its API largely unchanged. Its implementation will expect v2 protos to be delivered via a Subscription.
2. A REST API fetch module that subscribes to the v1 APIs and surfaces the results as a Subscription.

An example for EDS is in #1166.

Current status of this is that work is ongoing for CDS (I'm reasonably close to having a PR ready for this). Then we need to do this for RDS/LDS/RLDS. 

The end result of this will be the ability to consume v2 APIs which adhere to the subset expressible in the v1 API.

**Comment by mattklein123** [comment]
Done.
