### ISSUE TITLE
Unable to perform TLS origination to upstream Kafka broker

### ISSUE THREAD

**Issue by kgumbs** [envoyproxy/envoy#12856]
Description:
I'm not sure if this is supported, but I would like to take plaintext from producer and encrypt when sending to upstream Kafka broker. Please see my config below.

Config:
>
    static_resources:
    listeners:
      address:
        socket_address:
          address: 0.0.0.0   # Host that Kafka clients should connect to.
          port_value: 19092  # Port that Kafka clients should connect to.
      filter_chains:
        - filters:
          - name: envoy.filters.network.kafka_broker
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
              stat_prefix: exampleprefix
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: localkafka
    clusters:
    - name: localkafka
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: localkafka
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: kafka1 
                    port_value: 9093
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        allow_renegotiation: true
        common_tls_context:
          tls_certificates:
            certificate_chain: { "filename": "/etc/ssl/myclient.pem" }
            private_key: { "filename": "/etc/ssl/myclient.key" }
          validation_context:
            match_subject_alt_names:
              exact: "kafka1"
            trusted_ca:
              filename: /etc/ssl/ca-cert
     admin:
       access_log_path: "/dev/null"
        address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081

Logs :
>
        myclient_1    | [2020-08-27 13:46:12.559][15][debug][connection]      
        [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
        myclient_1    | [2020-08-27 13:46:12.559][15][debug][connection]                            [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
        myclient_1    | [2020-08-27 13:46:12.593][15][debug][connection]   [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
        myclient_1    | [2020-08-27 13:46:12.593][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
        myclient_1    | [2020-08-27 13:46:12.593][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:175] [C1] handshake complete
        myclient_1    | [2020-08-27 13:46:12.593][15][debug][pool] [source/common/tcp/original_conn_pool.cc:303] [C1] assigning connection
        myclient_1    | [2020-08-27 13:46:12.593][15][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:631]  TCP:onUpstreamEvent(), requestedServerName: 
        kafka1_1      | [2020-08-27 13:46:12,666] INFO [SocketServer brokerId=1] Failed authentication with /192.168.112.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
        myclient_1    | [2020-08-27 13:46:12.701][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:297] [C1] SSL shutdown: rc=0
        myclient_1    | [2020-08-27 13:46:12.701][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C1] 
        myclient_1    | [2020-08-27 13:46:12.703][15][debug][connection] [source/common/network/connection_impl.cc:584] [C1] remote close
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][connection] [source/common/network/connection_impl.cc:208] [C1] closing socket: 0
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C1] client disconnected
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][connection] [source/common/network/connection_impl.cc:112] [C0] closing data_to_write=0 type=0
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][connection] [source/common/network/connection_impl.cc:208] [C0] closing socket: 1
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][conn_handler] [source/server/connection_handler_impl.cc:111] [C0] adding to cleanup list
        myclient_1    | [2020-08-27 13:46:12.704][15][debug][pool] [source/common/tcp/original_conn_pool.cc:255] [C1] connection destroyed
        kafka1_1      | [2020-08-27 13:46:12,742] INFO [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer)
        kafka1_1      | [2020-08-27 13:46:12,747] INFO Successfully submitted metrics to Kafka topic __confluent.support.metrics (io.confluent.support.metrics.submitters.KafkaSubmitter)
        kafka1_1      | [2020-08-27 13:46:14,050] INFO Successfully submitted metrics to Confluent via secure endpoint (io.confluent.support.metrics.submitters.ConfluentSubmitter)

**Comment by mattklein123** [comment]
cc @adamkotwasinski

**Comment by adamkotwasinski** [comment]
I'm not 100% sure, but I think it be doable with any kind of proxy in between Kafka client and a Kafka server.
I'd do the following to make sure that there are no configuration problems with certificates:
1) remove the `envoy.filters.network.kafka_broker` filter from chain (it just collects metrics, so it should not have any effect)
2) increase the log levels on client/server sides to figure out why `SSL handshake failed`
3) are certificates okay? when using these certificates as a "raw" Kafka client, do you manage to connect successfully?

**Comment by kgumbs** [comment]
@adamkotwasinski, My certificates are okay, they work as expected with the raw Kafka client. Also, I'm able to connect via Envoy when downstream tls is enabled. I will try your recommendations and provide an update.

**Comment by kgumbs** [comment]
Failed Log:
>
    myclient_1    | [2020-08-31 18:12:03.699][8][debug][upstream] [source/common/upstream/upstream_impl.cc:286] transport socket match, socket default selected for host with address 192.168.80.5:9093
    myclient_1    | [2020-08-31 18:12:03.699][8][debug][upstream] [source/common/upstream/strict_dns_cluster.cc:167] DNS refresh rate reset for kafka1, refresh rate 5000 ms
    myclient_1    | [2020-08-31 18:12:03.884][22][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:236] [C0] new tcp proxy session
    myclient_1    | [2020-08-31 18:12:03.884][22][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:380] [C0] Creating connection to cluster localkafka
    myclient_1    | [2020-08-31 18:12:03.885][22][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
    myclient_1    | [2020-08-31 18:12:03.885][22][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C1] connecting
    myclient_1    | [2020-08-31 18:12:03.885][22][debug][connection] [source/common/network/connection_impl.cc:756] [C1] connecting to 192.168.80.5:9093
    myclient_1    | [2020-08-31 18:12:03.886][22][debug][connection] [source/common/network/connection_impl.cc:772] [C1] connection in progress
    myclient_1    | [2020-08-31 18:12:03.886][22][debug][pool] [source/common/tcp/original_conn_pool.cc:125] queueing request due to no available connections
    myclient_1    | [2020-08-31 18:12:03.886][22][debug][conn_handler] [source/server/connection_handler_impl.cc:423] [C0] new connection
    myclient_1    | [2020-08-31 18:12:03.886][22][debug][connection] [source/common/network/connection_impl.cc:616] [C1] connected
    myclient_1    | [2020-08-31 18:12:03.886][22][debug][connection]  [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
    myclient_1    | [2020-08-31 18:12:03.954][22][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
    myclient_1    | [2020-08-31 18:12:03.955][22][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
    myclient_1    | [2020-08-31 18:12:03.961][22][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C1] handshake expecting read
    myclient_1    | [2020-08-31 18:12:03.961][22][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:175] [C1] handshake complete
    myclient_1    | [2020-08-31 18:12:03.961][22][debug][pool] [source/common/tcp/original_conn_pool.cc:303] [C1] assigning connection
    myclient_1    | [2020-08-31 18:12:03.961][22][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:631] TCP:onUpstreamEvent(), requestedServerName: 
    kafka1_1      | [2020-08-31 18:12:03,961] DEBUG [SslTransportLayer channelId=192.168.80.5:9093-192.168.80.4:58420-0  key=sun.nio.ch.SelectionKeyImpl@2303ffdc] SSL handshake completed successfully with peerHost '192.168.80.4' peerPort   58420 peerPrincipal 'CN=myclient, O=XXXXXXX, L=XXXXX, ST=XXXXXX, C=US' cipherSuite  'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256' (org.apache.kafka.common.network.SslTransportLayer)
    kafka1_1      | [2020-08-31 18:12:03,963] DEBUG [SocketServer brokerId=1] Successfully authenticated with /192.168.80.4 (org.apache.kafka.common.network.Selector)
    kafka1_1      | [2020-08-31 18:12:04,014] DEBUG [SslTransportLayer channelId=192.168.80.5:9093-192.168.80.1:52680-0 key=sun.nio.ch.SelectionKeyImpl@2b16f1e2] SSLEngine.closeInBound() raised an exception. (org.apache.kafka.common.network.SslTransportLayer)
    kafka1_1      | javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
    kafka1_1      |         at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    kafka1_1      |         at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
    kafka1_1      |         at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
    kafka1_1      |         at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1542)
    kafka1_1      |         at org.apache.kafka.common.network.SslTransportLayer.handshakeFailure(SslTransportLayer.java:866)
    kafka1_1      |         at    org.apache.kafka.common.network.SslTransportLayer.maybeProcessHandshakeFailure(SslTransportLayer.java:904)
    kafka1_1      |         at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:290)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
    kafka1_1      |         at kafka.network.Processor.poll(SocketServer.scala:893)
    kafka1_1      |         at kafka.network.Processor.run(SocketServer.scala:792)
    kafka1_1      |         at java.lang.Thread.run(Thread.java:748)
    kafka1_1      | [2020-08-31 18:12:04,015] INFO [SocketServer brokerId=1] Failed authentication with /192.168.80.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
    myclient_1    | [2020-08-31 18:12:04.048][22][debug][connection]     [source/extensions/transport_sockets/tls/ssl_socket.cc:297] [C1] SSL shutdown: rc=0
    myclient_1    | [2020-08-31 18:12:04.048][22][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C1] 
    kafka1_1      | [2020-08-31 18:12:04,048] DEBUG [SocketServer brokerId=1] Connection with /192.168.80.4 disconnected (org.apache.kafka.common.network.Selector)
    kafka1_1      | java.io.EOFException
    kafka1_1      |         at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:614)
    kafka1_1      |         at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:95)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
    kafka1_1      |         at kafka.network.Processor.poll(SocketServer.scala:893)
    kafka1_1      |         at kafka.network.Processor.run(SocketServer.scala:792)
    kafka1_1      |         at java.lang.Thread.run(Thread.java:748)
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][connection] [source/common/network/connection_impl.cc:584] [C1]  remote close
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][connection] [source/common/network/connection_impl.cc:208] [C1] closing socket: 0
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C1] client disconnected
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][connection] [source/common/network/connection_impl.cc:112] [C0] closing data_to_write=0 type=0
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][connection] [source/common/network/connection_impl.cc:208] [C0] closing socket: 1
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][conn_handler] [source/server/connection_handler_impl.cc:111] [C0] adding to cleanup list
    myclient_1    | [2020-08-31 18:12:04.049][22][debug][pool] [source/common/tcp/original_conn_pool.cc:255] [C1] connection destroyed
    kafka1_1      | [2020-08-31 18:12:07,769] DEBUG Got ping response for sessionid: 0x1002208a9ac0001 after 2ms (org.apache.zookeeper.ClientCnxn)
    myclient_1    | [2020-08-31 18:12:08.683][8][debug][main] [source/server/server.cc:190] flushing stats


Working log with TLS enabled from downstream:
>
    myclient_1    | [2020-08-31 18:25:43.742][15][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:236] [C2] new tcp proxy session
    myclient_1    | [2020-08-31 18:25:43.742][15][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:380] [C2] Creating connection to cluster localkafka
    myclient_1    | [2020-08-31 18:25:43.742][15][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
    myclient_1    | [2020-08-31 18:25:43.742][15][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C3] connecting
    myclient_1    | [2020-08-31 18:25:43.743][15][debug][connection] [source/common/network/connection_impl.cc:756] [C3] connecting to 192.168.96.5:9093
    myclient_1    | [2020-08-31 18:25:43.743][15][debug][connection] [source/common/network/connection_impl.cc:772] [C3] connection in progress
    myclient_1    | [2020-08-31 18:25:43.743][15][debug][pool] [source/common/tcp/original_conn_pool.cc:125] queueing request due to no available connections
    myclient_1    | [2020-08-31 18:25:43.743][15][debug][conn_handler] [source/server/connection_handler_impl.cc:423] [C2] new connection
    myclient_1    | [2020-08-31 18:25:43.744][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C2] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.744][15][debug][connection] [source/common/network/connection_impl.cc:616] [C3] connected
    myclient_1    | [2020-08-31 18:25:43.744][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C3] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.757][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C3] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.757][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C3] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.762][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C3] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.762][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:175] [C3] handshake complete
    myclient_1    | [2020-08-31 18:25:43.762][15][debug][pool] [source/common/tcp/original_conn_pool.cc:303] [C3] assigning connection
    myclient_1    | [2020-08-31 18:25:43.762][15][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:631] TCP:onUpstreamEvent(), requestedServerName: 
    myclient_1    | [2020-08-31 18:25:43.762][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C2] handshake expecting read
    kafka1_1      | [2020-08-31 18:25:43,762] DEBUG [SslTransportLayer channelId=192.168.96.5:9093-192.168.96.4:41766-0 key=sun.nio.ch.SelectionKeyImpl@57ce0279] SSL handshake completed successfully with peerHost '192.168.96.4' peerPort 41766 peerPrincipal 'CN=myclient, O=XXXXX, L=XX, ST=XXXXXX, C=US' cipherSuite 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256' (org.apache.kafka.common.network.SslTransportLayer)
    kafka1_1      | [2020-08-31 18:25:43,762] DEBUG [SocketServer brokerId=1] Successfully authenticated with /192.168.96.4 (org.apache.kafka.common.network.Selector)
    myclient_1    | [2020-08-31 18:25:43.932][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C2] handshake expecting read
    myclient_1    | [2020-08-31 18:25:43.932][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:190] [C2] handshake expecting read
    myclient_1    | [2020-08-31 18:25:44.040][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:175] [C2] handshake complete
    kafka1_1      | [2020-08-31 18:25:44,167] DEBUG [SslTransportLayer channelId=192.168.96.5:9093-192.168.96.1:37986-1 key=sun.nio.ch.SelectionKeyImpl@7f0a3acc] SSL handshake completed successfully with peerHost '192.168.96.1' peerPort 37986 peerPrincipal 'CN=myclient, O=XXXXXX, L=XXX, ST=XXXX, C=US' cipherSuite 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384' (org.apache.kafka.common.network.SslTransportLayer)
    kafka1_1      | [2020-08-31 18:25:44,168] DEBUG [SocketServer brokerId=1] Successfully authenticated with /192.168.96.1 (org.apache.kafka.common.network.Selector)
    myclient_1    | [2020-08-31 18:25:44.185][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:297] [C3] SSL shutdown: rc=0
    myclient_1    | [2020-08-31 18:25:44.185][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C3] 
    kafka1_1      | [2020-08-31 18:25:44,186] DEBUG [SocketServer brokerId=1] Connection with /192.168.96.1 disconnected (org.apache.kafka.common.network.Selector)
    kafka1_1      | java.io.EOFException
    kafka1_1      |         at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:614)
    kafka1_1      |         at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:95)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
    kafka1_1      |         at kafka.network.Processor.poll(SocketServer.scala:893)
    kafka1_1      |         at kafka.network.Processor.run(SocketServer.scala:792)
    kafka1_1      |         at java.lang.Thread.run(Thread.java:748)
    kafka1_1      | [2020-08-31 18:25:44,186] DEBUG [SocketServer brokerId=1] Connection with /192.168.96.4 disconnected (org.apache.kafka.common.network.Selector)
    kafka1_1      | java.io.EOFException
    kafka1_1      |         at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:614)
    kafka1_1      |         at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:95)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
    kafka1_1      |         at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
    kafka1_1      |         at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
    kafka1_1      |         at kafka.network.Processor.poll(SocketServer.scala:893)
    kafka1_1      |         at kafka.network.Processor.run(SocketServer.scala:792)
    kafka1_1      |         at java.lang.Thread.run(Thread.java:748)
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/common/network/connection_impl.cc:584] [C3] remote close
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/common/network/connection_impl.cc:208] [C3] closing socket: 0
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C3] client disconnected
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/common/network/connection_impl.cc:112] [C2] closing data_to_write=0 type=0
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/common/network/connection_impl.cc:208] [C2] closing socket: 1
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:297] [C2] SSL shutdown: rc=1
    myclient_1    | [2020-08-31 18:25:44.187][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C2] 
    myclient_1    | [2020-08-31 18:25:44.188][15][debug][conn_handler] [source/server/connection_handler_impl.cc:111] [C2] adding to cleanup list
    myclient_1    | [2020-08-31 18:25:44.188][15][debug][pool] [source/common/tcp/original_conn_pool.cc:255] [C3] connection destroyed
    kafka1_1      | [2020-08-31 18:25:47,931] DEBUG Got ping response for sessionid: 0x10022145bb20001 after 2ms (org.apache.zookeeper.ClientCnxn)
    myclient_1    | [2020-08-31 18:25:48.642][9][debug][main] [source/server/server.cc:190] flushing stats

**Comment by adamkotwasinski** [comment]
That's without the kafka filter right?
Then it looks like something related to SSL connection being closed too quickly? Unsure if I understand it fully, but the below part in 
```
kafka1_1      | [2020-08-31 18:12:04,014] DEBUG [SslTransportLayer channelId=192.168.80.5:9093-192.168.80.1:52680-0 key=sun.nio.ch.SelectionKeyImpl@2b16f1e2] SSLEngine.closeInBound() raised an exception. (org.apache.kafka.common.network.SslTransportLayer)
kafka1_1      | javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
<< snip java stack trace >>
kafka1_1      | [2020-08-31 18:12:04,015] INFO [SocketServer brokerId=1] Failed authentication with /192.168.80.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
myclient_1    | [2020-08-31 18:12:04.048][22][debug][connection]     [source/extensions/transport_sockets/tls/ssl_socket.cc:297] [C1] SSL shutdown: rc=0
```
Maybe someone with better knowledge of SSL could help here. It looks like Envoy code actually does invoke `SSL_shutdown`, so no idea why Kafka doesn't see the notify:
```
First, it sends close_notify and returns zero or one on success or -1 on failure.
```
We can see it returned 0 in above log.

**Comment by kgumbs** [comment]
Any further updates?

**Comment by kgumbs** [comment]
Hello @mattklein123 and @adamkotwasinski, Just wanted to let you know I'm still encountering this error.
