### ISSUE TITLE
Hierarchical EDS weighted load balancing

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1285]
EDS now expresses weights at both the endpoint and locality level, these need to be combined to produce an effective LB weighting. The issue tracks the implementation work  on this.

**Comment by alyssawilk** [comment]
Given #1929 took longer than expected I'm probably not going to be able to pick this one in up in the near future.

**Comment by mpuncel** [comment]
is this a duplicate of #2725 ?

**Comment by htuch** [comment]
I don't think we're going to be removing the weight limits, given how the hierarchical Maglev balancer works today. I think we should close this one out, as the work is complete, feel free to open additional tracking issues for point features.

**Comment by ZackButcher** [comment]
Should we update the comment in the API about this issue given it's been closed?

https://github.com/envoyproxy/envoy/blob/6a8b843840687c24109b5a0dddf50868f9355e65/api/envoy/api/v2/endpoint/endpoint.proto#L109-L114

**Comment by htuch** [comment]
Agree, PRs welcome :)

**Comment by ZackButcher** [comment]
The resolution is not clear to me from this issue given it was closed with no changes. Based on current LB impl, the limit of 128 sticks around due to perf concerns and the reference to this issue should be removed, or have the underlying perf concerns been addressed?

**Comment by mattklein123** [comment]
There aren't any perf concerns anymore w/ weighting for both RR and LR. Both have been fixed. I don't recall exactly how Maglev works. TBH I would probably just update the comment to remove the attention link until if/when someone complains that the weight max needs to be larger than 128.
