### ISSUE TITLE
MySql filter example shows protocol errors

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#12868]
### description

While testing the sandbox examples for #12491 i noticed that the mysql filter shows protocol errors, eg:

```
mysql.egress_mysql.protocol_errors: 31
mysql.egress_mysql.queries_parse_error: 2
```
despite the errors, all of the mysql commands appear to work as documented

this can be seen on azure here:

https://dev.azure.com/cncf/envoy/_build/results?buildId=49219&view=logs&j=5799eb7e-eba2-5aab-b97e-d4dd72e7ced8&t=1d3119f4-58fb-569d-0a6a-9fe5a7e7686d&l=5322

### steps to reproduce

run mysql example from sandbox documentation

**Comment by mattklein123** [comment]
cc @dio @rshriram

**Comment by phlax** [comment]
i can confirm that this bug appears to be fixed
