### ISSUE TITLE
master branch build fails in Linux

### ISSUE THREAD

**Issue by rajma** [envoyproxy/envoy#12887]
Title: Building master branch fails in Ubuntu 18.04. 

Description:
When I build the master branch of the envoy proxy with bazel build //source/exe:envoy-static, the build fails, however the release tag v1.15.0 builds without errors
Logs:
Here is the error message on the console
ERROR: /home/user/github/envoy/source/common/upstream/BUILD:11:17: C++ compilation of rule '//source/common/upstream:cds_api_lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 353 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
source/common/upstream/cds_api_impl.cc: In member function 'virtual void Envoy::Upstream::CdsApiImpl::onConfigUpdate(const std::vector<std::reference_wrapper<Envoy::Config::DecodedResource> >&, const string&)':
source/common/upstream/cds_api_impl.cc:47:36: error: unused variable '_' [-Werror=unused-variable]
   for (const auto& [cluster_name, _] : clusters_to_remove) {
                                    ^
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.

Workaround:
When I change the bazel/envoy_internal.bzl and remove the -Werror flag on the posix_options with "-Wno-error", then the build succeeds

Additional Information:
I think this probably occured when the C++17 standard was updated. This is not the only place where the breakage occurs. This fails in many places with similar unused variable errors.

**Comment by sunjayBhatia** [comment]
looks related to https://github.com/envoyproxy/envoy/pull/12828 and some of the issues going on here: https://buildkite.com/bazel/envoy/builds, if youre willing to root these out and make a PR (and introduce a CI check that prevents this from happening on new code) that would be super helpful

**Comment by rajma** [comment]
Apologies for the delay in response. Not familiar with the CI stuff but will take a look and see if I can do something about it. Thanks
