### ISSUE TITLE
what's the stage mean in rate limit

### ISSUE THREAD

**Issue by du2016** [envoyproxy/envoy#12892]
```
(optional, integer) Refers to the stage set in the filter. The rate limit configuration only applies to filters with the same stage number. The default stage number is 0.
```

i have find this in the envoy doc,but what's the stage mean？what is the different of state 0 or state 10?

**Comment by mattklein123** [comment]
It's a mechanism to have multiple rate limits in the filter chain. For example:
pre-auth rate limit -> auth -> post-auth rate limit

**Comment by du2016** [comment]
thanks

**Comment by jdomag** [comment]
@mattklein123 @du2016  
Any idea how to use it? I'm wondering if I can have 2 different rate limiting services and point few workloads to rateLimitService1 and few workloads to rateLimitService2  - not sure if it's possible though.
