### ISSUE TITLE
network tls: alternative to using socket BIOs in SslSocket

### ISSUE THREAD

**Issue by florincoras** [envoyproxy/envoy#12899]
TLS sockets are currently using BIOs that rely on access to a socket file descriptor, namely:

```
BIO* bio = BIO_new_socket(callbacks_->ioHandle().fdDoNotUse(), 0);
```

To avoid direct use of the fd and to ensure that `SslSocket`s can work with any type of `IoHandle`s, probably mem BIOs should be used instead. I am willing to do the work but does anybody know if this comes with any significant downsides? Are there any better alternatives?

**Comment by florincoras** [comment]
cc @mattklein123 @antoniovicente

**Comment by antoniovicente** [comment]
One possible option would be to add a method to IoHandle that creates an SSL bio that is appropriate for the IoHandle in question.  It does pollute the IoHandle interface in some ways.  We should keep in mind that IoHandle::readv and writev should not be used on IoHandles used by SSL libraries.

**Comment by florincoras** [comment]
Interesting idea! Personally, I like the option of being able to abstract any type of transport with IoHandles, i.e., being able to readv/writev to an IoHandle that internally implements TLS/QUIC seems good to me. But, agreed, that could lead to a significant amount of api pollution.

**Comment by antoniovicente** [comment]
Writing a BIO that calls into IoHandle for peek/read/write operations may also be an option.

**Comment by mattklein123** [comment]
cc @ggreenway @lizan @PiotrSikora @davidben for thoughts.

I don't know about the available options. Some type of shim over an IOHandle would be great if it's possible to implement a custom one as @antoniovicente suggests.

**Comment by antoniovicente** [comment]
See:
BIO_METHOD acts like a vtable, allows you to specify read/write/etc functions
BIO *BIO_new(const BIO_METHOD *method);

BIO::ptr would point to the IoHandle*

**Comment by florincoras** [comment]
Looking at what @antoniovicente suggested!

**Comment by florincoras** [comment]
Surprisingly enough, something as simple as #12911 seems to be working.
