### ISSUE TITLE
Support for deterministic traffic mirroring

### ISSUE THREAD

**Issue by adriank-convoy** [envoyproxy/envoy#12891]
## Description:

We have a use case where we'd like to mirror the same X% of requests from a production endpoint to multiple test endpoints to compare performance. Currently we're forced to mirror a large percentage of traffic to each in order to get enough data for analysis, but ideally we'd only like to mirror something like 5%. Similar to `route.RouteAction.HashPolicy`, we'd like to be able to use some property of the request (header or query string) to deterministically mirror the same requests to all test endpoints.

### Desired behavior

If the runtime_fraction of test endpoint A and B are equal and the hash policy is configured for both: the same requests are mirrored to both

If the runtime_fraction of test endpoint A is 5%, and the runtime_fraction of B is 10%, and the hash policy is configured for both: the same 5% of requests going to A will also be mirrored to B + an additional 5%

If the hashing policy is not configured, mirroring is random

Thanks!

**Comment by mattklein123** [comment]
Do you want a hash policy? Or do you actually want some type of "mirror match policy"? Could tapping somehow be a different way of achieving this if the tap filter supported gRPC output?

**Comment by adriank-convoy** [comment]
Good point, I guess the phrase 'deterministic mirroring' is actually a bit ambiguous. In our case we don't care which specific requests are mirrored, just that the same requests are mirrored to all endpoints. It doesn't have to be hash based, but  hashing seems like a reasonable fit. 

I wasn't aware of tapping, but it sounds like it could be used for the other case where you want to dictate which specific requests are mirrored. It actually sounds like it could work as-is for our use case as well if you control the caller, and can add a special header to some % of your calls, but that won't always be the case. I would imagine both options would be useful to have.

That being said, for our use case I'd like the configuration of what % gets mirrored to live in Envoy's config, so the fact that mirroring is happening in the first place is transparent to the caller & production endpoint.

**Comment by mattklein123** [comment]
Sorry so the issue is basically that you have multiple mirror policies, but each has an independent fraction?
