### ISSUE TITLE
flaky tests: unicode processing bug

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#12896]
https://github.com/envoyproxy/envoy/pull/12516

```
Traceback (most recent call last):
  File "/source/ci/flaky_test/process_xml.py", line 101, in <module>
    output_msg += getGitInfo(CI_TARGET)
  File "/source/ci/flaky_test/process_xml.py", line 76, in getGitInfo
    for line in [next(f) for x in range(6)]:
  File "/source/ci/flaky_test/process_xml.py", line 76, in <listcomp>
    for line in [next(f) for x in range(6)]:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 209: ordinal not in range(128)
```

cc @stedsome @asraa @lizan

**Comment by asraa** [comment]
Potential fix would be to open the file with encoding specified https://github.com/envoyproxy/envoy/blob/760a164640acf75a8009ac89b5ff06f78a733221/ci/flaky_test/process_xml.py#L73

My issue is testing this. I thought I was able to ssh into a azp workflow at some points, can't find it now.

**Comment by mattklein123** [comment]
cc @lizan on how to best test. @asraa I would be OK with just trying a fix but up to you.

**Comment by asraa** [comment]
Cool, realized it reproduces if I clone the PR. Testing now, will tag the fix for review hopefully soon https://github.com/envoyproxy/envoy/pull/12900
