### ISSUE TITLE
Users want access to the documentation for the current stable Envoy release

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/envoy#1290]
Right now, Envoy 1.3.0 is the most recent tagged Envoy release. I take that to mean that 1.3.0 is the current stable version and should be used in production.

However, the 1.3.0 docs are unreachable. Only the 1.4.0 docs are available.

**Comment by mattklein123** [comment]
PRs appreciated on reorganizing the doc site layout somehow.

**Comment by mattklein123** [comment]
I think the best thing to do here is just to have the docs publish script iterate through a set of tags and just checkout a branch and build the sphinx build the tag into a subdirectory. So we could for example put the current docs into /latest, then have /1.3.0, /1.2.0, etc. I think it won't be that hard to do this and will find someone to work on this next week.
