### ISSUE TITLE
 How does Envoy cache routeConfiguration?

### ISSUE THREAD

**Issue by KimJiAh** [envoyproxy/envoy#12914]
I wonder if Envoy stores the same RouteConfiguration in duplicate. 

![image](https://user-images.githubusercontent.com/30854006/91810593-1d913c00-ec69-11ea-9a52-ed328e175912.png)

When I use 'istioctl proxy-config route' with route name, two identical RouteConfigurations are output as a result.

So I guess Envoy stores RouteConfiguration in duplicate. 

But I found that in Envoy code(rds_impl.cc), Envoy saves the dynamic configuration as node_hash_map and the static configuration as node_hash_set. 

If this is correct, I think Envoy does not save RouteConfiguration as a duplicate. Is this right?

**Comment by snowp** [comment]
Envoy only tracks one version of each resource, so I would expect this to be an issue with the Istio tooling or /config_dump rather than an indication that Envoy is storing duplicates.
