### ISSUE TITLE
Deny POST request to certain URLs using http filters

### ISSUE THREAD

**Issue by zainhasib** [envoyproxy/envoy#12918]
Hello, I want to deny certain https POST requests from the envoy proxy. Can somebody help me with that? 

I did check the filters here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/http_filters

Which filter should I use in my case?

**Comment by snowp** [comment]
The easiest way is probably to use the route configuration (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v3-api-msg-config-route-v3-routeconfiguration) to specify a DirectResponseAction for the routes you want to exclude. That way you're just using the regular router filter to block traffic matching specific route entries.

**Comment by zainhasib** [comment]
Hi
We have configured envoy using xDS with REST-JSON URL. The problem we have is if we send external request (from postman) to envoy gateway for xDS REST endpoints like v2/discovery:routes it return the envoy DiscoveryResponse from the service.
How can we block this external request for xDS REST Endpoints? I tried adding a route for these REST URL but it doesn’t work.
