### ISSUE TITLE
Make UDP GSO batch writer useful without QUIC/QUICHE

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#12921]
The current implementation of `UdpGsoBatchWriter` is uses some QUICHE code. This should be untangled such that non-QUIC UDP use cases can use the GSO batch writer. See https://github.com/envoyproxy/envoy/blob/82e5e104e21636aa583f28ccc9232b7af3584ac6/source/extensions/quic_listeners/quiche/udp_gso_batch_writer.h#L74

**Comment by danzh2010** [comment]
I'm not sure if it's possible to untangle batch writer from QUICHE code without implementing a new GSO batch writer. But even current batch writer can be used for other UDP cases as well. So it's not clear what's the actionable item for this issue.
