### ISSUE TITLE
Do you all have a a branching and release policy?

### ISSUE THREAD

**Issue by reselbobasg** [envoyproxy/envoy#12922]
I am doing an article on branching and release policies for the most popular open-source projects. To say Envoy is not popular is an extreme understatement.

Thus, I ask, do you have have a branching and release policy/pattern that I can read? Or is it a matter of convention and tribal knowledge? If so, what is the policy/pattern?

Thanks in advance,
Bob Reselman

**Comment by snowp** [comment]
You can find the release policy here: https://github.com/envoyproxy/envoy/blob/master/RELEASES.md
