### ISSUE TITLE
Envoy tap filter threat model clarifications

### ISSUE THREAD

**Issue by lhluo** [envoyproxy/envoy#12920]
Hi Envoy team, we're working on a custom filter extension that models after the Tap filter. In Envoy's [threat model page](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/threat_model#core-and-extensions), I see that `envoy.filters.http.tap` should "only be used when both the downstream and upstream are trusted". One of our top requirements is system security **with untrusted downstreams**. I dug into the tap filter implementation but couldn't identify any obvious attack vectors (admittedly C++ security is not my area of expertise). 

I've posted to slack but this might be a better place to pose the question. Wondering if anyone with more familiarity can comment on the security implications of the tap filter? What are the risks of using a tap filter with an untrusted downstream?

**Comment by mattklein123** [comment]
It's only noted that because it hasn't been hardened. There may be buffering issues that need to be looked at, etc.

**Comment by lhluo** [comment]
@mattklein123 thanks for the answer. Could you clarify on what hardened means? How can we help tag this filter as hardened?

**Comment by mattklein123** [comment]
> Could you clarify on what hardened means? How can we help harden this filter against untrusted downstreams?

Run it in production, audit it for security/unlimited buffering/etc. issues.

**Comment by lhluo** [comment]
I'm assuming other "hardened" filters have undergone the above auditing? 
Is there a standard process we use to audit envoy filters? Or case-by-case basis?

**Comment by mattklein123** [comment]
I wish I had a an official checklist for you but I don't. cc @htuch as such a checklist would be pretty nice from an extension maturity level tracking perspective.

**Comment by htuch** [comment]
I've opened https://github.com/envoyproxy/envoy/issues/12962 to track this, with some suggestions to start things of.
