### ISSUE TITLE
grpc_http1_reverse_bridge: support getting message length from upstream header

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#12957]
*Title*: *grpc_http1_reverse_bridge: support getting message length from upstream header*

*Description*:
Right now the gRPC reverse bridge filter can operate in 2 modes based on the withhold_grpc_frames config option. If it's false, then the upstream must prefix gRPC messages with the message-length frame header. If it's true, then the filter buffers the entire upstream response so it can count the length and add the prefix itself.

I think it would be useful to have a 3rd option which would be to get the message length from an upstream header, which would allow the upstream to avoid having knowledge of the gRPC message format, but still let the filter stream rather than buffer.

One weird wrinkle is we may not want to use the usual `content-length` header, because the upstream may want to use a `transfer-encoding: chunked` still which means that the `content-length` header should not be set.

Proposal:

Add a string `response_size_header` option, which lets users specify a custom header to use to get the length in bytes of the response message. If this is set, ignore `withhold_grpc_frames`.

**Comment by mattklein123** [comment]
Sounds reasonable to me!
