### ISSUE TITLE
Extension maturity checklist

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#12962]
While we now have explicit extension [security postures](https://github.com/envoyproxy/envoy/blob/f1c0031819ddc7b8a9f6352ad6722f4abf8ab664/bazel/envoy_library.bzl#L37), there is no systematic way to govern how extensions are promoted from untrusted to trusted, i.e. when they are considered robust to downstream or upstream; we generally rely on Envoy maintainer intuition and burn time. We should probably have a checklist providing _guidelines_ on how this can be done in a consistent way.

Some ideas:
* Does the extension have fuzz coverage? If it's only receiving fuzzing courtesy of the generic listener/network/HTTP filter fuzzers, does it have a dedicated fuzzer for any parts of the code that would benefit?
* Does the extension have unbounded internal buffering? Does it participate in flow control via watermarking as needed?
* Does the extension have at least one deployment with live untrusted traffic for a period of time, N months?
* Does the extension rely on dependencies that meet our [extension maturity model](https://github.com/envoyproxy/envoy/issues/10471)?
* Is the extension reasonable to audit by Envoy security team for obvious scary things, e.g. `memcpy`, does it have gnarly parsing code, etc?
* Does the extension have active `CODEOWNERS` who are willing to vouch for the robustness of the extension?
* Is the extension absent a [low coverage exception](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh#L5)?

Thoughts on any others? CC @envoyproxy/security-team

**Comment by mattklein123** [comment]
This sounds like a great initial list to me. Should we codify this somewhere in the repo and iterate?

**Comment by junr03** [comment]
>  extension reasonable to audit by Envoy security team for obvious scary things, e.g. memcpy

I, naively, wonder how much of this type of audits could be codified in linters instead of relying solely on the eyes of the sec team.

**Comment by asraa** [comment]
> Does the extension have fuzz coverage? If it's only receiving fuzzing courtesy of the generic listener/network/HTTP filter fuzzers, does it have a dedicated fuzzer for any parts of the code that would benefit?

On that note, I'm working on a local refactor for the generic HTTP filters, so that the class framework only takes in a filter and then encodes/decodes the HTTP message, without any mock construction unless you specify it. I want to make the interface the library exposes easier for single-fuzz targets to adopt and extend. I'll be following the refactor with a dedicated ext_authz target.

**Comment by htuch** [comment]
@junr03 yes, good point, some of this should just be code format or CodeQL checks, but other parts are more subjective, e.g. "is this a scary parser?".
