### ISSUE TITLE
Add explicit source IP hash to RDS.

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1296]
Hash specifically on the source IP (rather than using XFF, which has complex semantics) for the v2 API.

**Comment by rshriram** [comment]
Would it make sense to hash on the 5-tuple (src ip port, dst ip, port and proto - http, http2, etc)? It becomes a bit more generic doesn't it ?

**Comment by alyssawilk** [comment]
I think it depends on what you're trying to accomplish.  If you're trying for session affinity (a given client likely landing on the same backend, or best-effort "sticky" load balancing) hashing on the 5 tuple doesn't work well for users who are still on HTTP/1, as they're likely to have multiple connections on different ephemeral ports.

**Comment by htuch** [comment]
I think we could extend the bools in the `ConnectionProperties` to allow folks to opt in and out of different tuple indices to support source IP hashing, 5-tuple hashing, or anything in between. The proto is extensible, so let's do source IP first and then build the rest as folks feel the need and can contribute PRs.

**Comment by rshriram** [comment]
Okay, I see the issue. Source ip makes more sense. The other issue here is that the downstream to upstream choice when using ketama hash is a function of number of upstream nodes. If we wanted constant mapping, we would need a different hashing function that is independent of the upstream pool size.

**Comment by akonradi** [comment]
Fixed by #1727.
