### ISSUE TITLE
Options to maintain sticky session(affinity) should support samesite attribute

### ISSUE THREAD

**Issue by pc-rshetty** [envoyproxy/envoy#12970]
Google Chrome recently enforced a feature(https://blog.heroku.com/chrome-changes-samesite-cookie) which prevents us from sending a cookie to a cross site to avoid CSRF. This is all great and envoy's current mechanism works great. What doesn't work is when we iframe our application within another web application(example salesforce) chrome thinks we are going from salesforce to our domain even though we are going from our domain to our domain.
Currently the default if not specified is SameSite=Lax and we need an ability to override this by SameSite=None since this cookie has no sensitive information. 

This will pretty much block anyone using Envoy for an application which is iframed into another web application. 

*Description*:
>Describe the the desired behavior, what scenario it enables and how it
would be used.
We have following options 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=cookie#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-cookie
name
ttl
path

Along with these please add an options 
1>SameSite(default to None) 
2>Option to mark the cookie as secure

Some comparison AWSELB cookie has default samesite=None and is marked as secure

Alternatively as a quick fix the samesite can bet set as None and cookie marked secure if you do not want to expose this option. (The behavior will remain same before chrome launched the change and this cookie has no confidential info)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
https://blog.heroku.com/chrome-changes-samesite-cookie
https://github.com/istio/istio/issues/27006
https://stackoverflow.com/questions/59459260/aws-lb-sticky-session-and-samesite

**Comment by pc-rshetty** [comment]
We have a workaround by writing this envoy filter in istio 


```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadLabels:
    app: myingressgateway
  filters:
    - listenerMatch:
        listenerType: GATEWAY
      filterType: HTTP
      filterName: envoy.lua
      filterConfig:
        inlineCode: |
          function envoy_on_response(response_handle)
            function set_cookie_header(rh)
              s = rh:headers():get("Set-Cookie")
              if string.find(s, "mycookie=" ) and not string.find(s, "SameSite") then
                s = s.."; SameSite=None; Secure"
              end
              return s
            end
            if response_handle:headers():get("Set-Cookie") then
              secure_cookie_header = set_cookie_header(response_handle)
              response_handle:headers():replace("Set-Cookie",secure_cookie_header)
            end
          end```

**Comment by plallin** [comment]
@pc-rshetty what is the intent of `string.find(s, "mycookie=" )` in your filter?

I've re-written your filter as per the last API for `EnvoyFilter` as documented in [the latest version of the documentation](https://istio.io/latest/docs/reference/config/networking/envoy-filter/), and without the  `myCookie=` logical check:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              function set_cookie_header(rh)
                s = rh:headers():get("Set-Cookie")
                if not string.find(s, "SameSite") then
                  s = s.."; SameSite=None; Secure"
                end
                return s
              end
              if response_handle:headers():get("Set-Cookie") then
                secure_cookie_header = set_cookie_header(response_handle)
                response_handle:headers():replace("Set-Cookie",secure_cookie_header)
              end
            end
```

**Comment by plallin** [comment]
Upon trying out the scripts (either @pc-rshetty or mine), I recommend against using them.

`response_handle:headers():replace("Set-Cookie",secure_cookie_header)` is not safe -- if you have several `set-cookies` headers it will mutate all of them which might not be what you want to do (I suppose that in most cases you will *not* want to mutate all `set-cookie` headers, only the one related to your own sticky cookie).

Unfortunately I do not have a solution to offer. I would be please to learn how other users of Istio deal with the same-site parameter for their own sticky cookies.

**Comment by CondormanFr** [comment]
It is very strange that this functionality is not yet include in envoy. As explain by initial submitter, google has switch to check  the SameSite parameter since more tha an year and if you have not this , application can not work properly.
Is it possible to add the missing properties (SameSite first) with cookies in Envoy ?

**Comment by CondormanFr** [comment]
> @pc-rshetty I've re-written your filter as per the last API for `EnvoyFilter` as documented in [the latest version of the documentation](https://istio.io/latest/docs/reference/config/networking/envoy-filter/):
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: secure-session-cookie-filter
>   namespace: istio-system
> spec:
>   workloadSelector:
>     labels:
>       istio: ingressgateway
>   configPatches:
>   - applyTo: HTTP_FILTER
>     match:
>       context: GATEWAY
>       listener:
>         portNumber: 443
>         filterChain:
>           filter:
>             name: envoy.http_connection_manager
>             subFilter:
>               name: "envoy.router"
>     patch:
>       operation: INSERT_BEFORE
>       value:
>         name: envoy.lua
>         typed_config:
>           "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
>           inlineCode: |
>             function envoy_on_response(response_handle)
>               function set_cookie_header(rh)
>                 s = rh:headers():get("Set-Cookie")
>                 if string.find(s, "mycookie=" ) and not string.find(s, "SameSite") then
>                   s = s.."; SameSite=None; Secure"
>                 end
>                 return s
>               end
>               if response_handle:headers():get("Set-Cookie") then
>                 secure_cookie_header = set_cookie_header(response_handle)
>                 response_handle:headers():replace("Set-Cookie",secure_cookie_header)
>               end
>             end
> ```

Does this code works with Istio 1.8.4 ? I didn't success to make it working ...

**Comment by pbn4** [comment]
> Upon trying out the scripts (either @pc-rshetty or mine), I recommend against using them.
> 
> `response_handle:headers():replace("Set-Cookie",secure_cookie_header)` is not safe -- if you have several `set-cookies` headers it will mutate all of them which might not be what you want to do (I suppose that in most cases you will _not_ want to mutate all `set-cookie` headers, only the one related to your own sticky cookie).
> 
> Unfortunately I do not have a solution to offer. I would be please to learn how other users of Istio deal with the same-site parameter for their own sticky cookies.

Posting my solution which addresses this problem: 


```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-cookie-filter-stickiness
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER # http connection manager is a filter in Envoy
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_response(response_handle)
                function rewrite_cookie(s)
                  if string.find(s, "stickiness=" ) and not string.find(s, "SameSite") then
                    s = s.."; SameSite=None; Secure"
                  end
                  return s
                end
                if response_handle:headers():get("Set-Cookie") then
                  rewritten_cookies = {}
                  for key, value in pairs(response_handle:headers()) do
                      if key == "set-cookie" then
                        rewritten_cookie = rewrite_cookie(value)
                        table.insert(rewritten_cookies, rewritten_cookie)
                      end
                  end
                  response_handle:headers():remove("Set-Cookie")
                  for key, value in next, rewritten_cookies do
                    response_handle:headers():add("Set-Cookie", value)
                  end
                end
              end
```

it assumes that cookie name is `stickiness`. It's not lightweight though, it searches through and reassigns all of the `Set-Cookie` headers and modifies only one with where 'stickiness' substring is found.

**Comment by adiseshan** [comment]
The below Envoyfilter fixed our problem.
Import point to note
`Lua expects % used as escape character for characters like - `


```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER # http connection manager is a filter in Envoy
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              rewritten_cookies = {}
              for key, value in pairs(response_handle:headers()) do
                if key == "set-cookie" and string.find(value, "SOME%-COOKIE%-KEY=" ) then
                  rewritten_cookie = value.."; SameSite=None; Secure"
                  table.insert(rewritten_cookies, rewritten_cookie)
                elseif key == "set-cookie" then
                  table.insert(rewritten_cookies, value)
                end
              end
              response_handle:headers():remove("Set-Cookie")
              for key, value in next, rewritten_cookies do
                response_handle:headers():add("Set-Cookie", value)
              end
            end
```
