### ISSUE TITLE
Support running without an admin interface

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#1297]
Some of Envoy's use cases, such as reverse-proxying to a non-TLS-capable backend, don't benefit much from having an admin interface available. It's just one additional port that I need to figure out how to firewall away from unauthorized access.

It'd be nice if the admin interface were made optional. Potential ways to disable it include leaving out the `"admin"` section of the config, or passing some special flag.

**Comment by mattklein123** [comment]
It's hard for me to imagine why anyone would ever run without the admin interface. Too useful for ops. However, not opposed to making it optional if someone does the patch.

**Comment by tlhunter** [comment]
FWIW, if one wants to "disable" the admin interface, I believe the following would work:

```json
 "admin": {                                       
   "access_log_path": "/dev/null",                
   "address": "tcp://127.0.0.1:0"                   
 }                                               
```

This asks the OS to assign a random high port. It'll then only listen for requests originating within the machine.

**Comment by mattklein123** [comment]
Closing as I just don't see this getting implemented. If someone wants to step up we can reopen.

**Comment by aceqbaceq** [comment]
tlhunter => your solution is amazing.
mattklein123 = if there is smth its hard to imagine to you it doesnt mean anything
