### ISSUE TITLE
Block xDS REST endpoint access from outside

### ISSUE THREAD

**Issue by zainhasib** [envoyproxy/envoy#12999]
Hi
We have configured envoy using xDS with REST-JSON URL. The problem we have is if we send external request (from postman) to envoy gateway for xDS REST endpoints like v2/discovery:routes it return the envoy DiscoveryResponse from the service.
How can we block this external request for xDS REST Endpoints? I tried adding a route for these REST URL but it doesn’t work.

**Comment by htuch** [comment]
This question needs some more information to answer. What is "postman"? Why are you routing to your xDS API server external requests through the Envoy gateway? I think this is almost certainly a configuration error.

**Comment by zainhasib** [comment]
Hi @htuch 
Postman is an application to make HTTP requests : https://www.postman.com/

The xDS API server accept a post request from envoy that returns the route and cluster information, right? However, what we found was that any client can make request to the API server and fetch those information, so we are asking how can we block that access by anyone other than envoy itself?

**Comment by zainhasib** [comment]
Adding http redirect filter to xDS urls did the trick!
