### ISSUE TITLE
HTTP filter need use recreateStream when POST a body

### ISSUE THREAD

**Issue by kkHAIKE** [envoyproxy/envoy#12994]
From:
https://github.com/envoyproxy/envoy/blob/0b24c6ac8ebaddfd46852e732d82675b3521d35a/include/envoy/http/filter.h#L497-L503
and:
https://github.com/envoyproxy/envoy/blob/0b24c6ac8ebaddfd46852e732d82675b3521d35a/source/common/http/filter_manager.cc#L1283-L1289
we can found a large commit 2 years ago....https://github.com/envoyproxy/envoy/commit/bbf5674c2c9a901ec4e964e4dd1d845516e672b2

VHDS filter need this to recreate new stream after route update ok.. but only GET(no body) request work now...POST will return 404...

I don't quite understand this commit: `Because the filter's and the HCM view of if the stream has a body and if the stream is complete may differ`

ping @alyssawilk and thx for your PR, may be we can found a way to do that!!!

**Comment by alyssawilk** [comment]
for the comment that confused you, the HCM may have received body bytes where the router has not received decodeData, or the router may not have received end stream after headers (know there is no body) where the HCM has.

That's somewhat different from the recreateStream with body issue.  There's nothing which actually prevents Envoy from supporting recreateStream, but it's complicated.  Imagine streaming a body through a decompression filter, and having recreateStream called halfway through compressing? I don't think it's impossible to do but it's not trivial so we started with the trivial case (no body, no trailers).  If you have an interest in this feature I think it'd be a fine addition to Envoy but I think you'd have to pick it up yourselves.

**Comment by kkHAIKE** [comment]
thx!
