### ISSUE TITLE
Add grpc_service_method fields in CEL filter extension

### ISSUE THREAD

**Issue by XSAM** [envoyproxy/envoy#13002]
*Title*: Add grpc_service_method fields in CEL filter extension

*Description*:

|Attribute|Type|Description|
|-|-|-|
|request.grpc_service_method|string|gRPC service methods e.g. "unary" "bidi_streaming"

gRPC provides four kinds of service methods: `unary`, `client_streaming`, `server_streaming`, and `bidi_streaming`. Every method may have different strategies to handle.
For instance, we may filter out the streaming method while calculating the latency of requests in Wasm extension (the same strategy puts on the streaming may result in a vast latency that has no meaning, say, a 10m latency)

[optional *Relevant Links*:]
https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle

**Comment by htuch** [comment]
I don't think you can determine whether this is unary vs. streaming or even streaming type from wire-level gRPC. You most likely need to have service descriptors, which we don't currently have a way of feeding to the CEL evaluation. CC @kyessenov @markdroth

**Comment by kyessenov** [comment]
Yeah, gRPC method signature does not indicate whether it is streaming or not. At HTTP level, it's always just a single long request. I wonder if what you're looking for is per-frame hooks. grpc_states can emit individual gRPC frames that could be exposed for filters.

**Comment by markdroth** [comment]
Correct.  gRPC does provide 4 different interfaces for these different types of calls, but those are really just API conveniences; under the hood, they are all the same at the wire protocol level.  In fact, even gRPC itself does not have this information down at the layer at which authz checks are done.

**Comment by XSAM** [comment]
Thanks for the detailed explanation. I now use the data from `grpc_stats` to filter the gRPC method.
