### ISSUE TITLE
Accessing tracing information within an HTTP Filter

### ISSUE THREAD

**Issue by cyran-ryan** [envoyproxy/envoy#13013]
Hi, I'm attempting to access the tracing information generated by the HTTP connection manager within one of our custom HTTP filters. Is there any way to access the active trace within an HTTP filter? Or is that not propagated down to a level that's accessible to the filter? 

I've tried setting or getting the `x-b3-*` headers but those also seem to not be available. 

Specifically I'm looking for the span id and the trace id.

Thanks for any tips!

**Comment by mattklein123** [comment]
See this API: https://github.com/envoyproxy/envoy/blob/83578ec2760ec823de92200cf169bca2903513a0/include/envoy/http/filter.h#L239

**Comment by cyran-ryan** [comment]
Thanks so much! That's what I was looking for and some how missed it.
