### ISSUE TITLE
Expired SSL cert on 3rd party mirror - Kafka

### ISSUE THREAD

**Issue by murray-stripe** [envoyproxy/envoy#13011]
*Title*: Expired SSL cert on mirror - external dependency - kafka

*Description*:

The download mirror for the [kafka dependency](https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl#L640-L648) seems to have an expired certificate and from-source builds are not currently possible with an empty bazel cache.

There may not actually _be any_ resolution to this from the Envoy project's side, but creating the ticket for posterity and to note for the maintainers.

Error from browser when attemping to access the Kafka download:
![image](https://user-images.githubusercontent.com/63568820/92498075-2bdedb00-f1c8-11ea-993b-44dbf0665358.png)

*Repro steps*:

```
bazelisk clean --expunge
bazelisk build //...
```

**Comment by akonradi** [comment]
I don't see that mirror listed on the [Apache mirrors list](http://ws.apache.org/mirrors.cgi)

**Comment by murray-stripe** [comment]
I noticed the same thing. I've patched our internal build to use the Berkeley mirror for the time being.

**Comment by moderation** [comment]
Looks like we should switch to the suggested mirror https://mirrors.gigenet.com/apache/kafka/2.4.1/kafka_2.12-2.4.1.tgz
```

**Comment by htuch** [comment]
Agreed, let's just switch mirror, would you be able to submit a PR? Thanks.
