### ISSUE TITLE
Example of C++ gRPC non-web load-balancing and sharding use case?

### ISSUE THREAD

**Issue by HappyCerberus** [envoyproxy/envoy#13027]
*Title*: *Example of gRPC non-web load-balancing and sharding use case?*

*Description*:
>I'm trying to determine how to use Envoy for C++ gRPC load balancing and sharding (I will very likely need both in our stack).
>I'm not quite sure how to transplate the gRPC-Web examples to a gRPC client talking to a gRPC server (this is all in the backend).
>Also I don't quite understand the documentation section for gRPC, it says that loadbalancing for gRPC is supported but gRPC-LB lookaside isn't, which is something that clashes with my understand what Envoy is. I would expect that gRPC-LB lookaside is the only way gRPC could integrate with Envoy.

**Comment by htuch** [comment]
I'm not sure what you mean by sharding here, Envoy works as part of a sharded solution, but it's not itself a sharding solution.

I don't see an obvious example of what you're looking for in our existing overview, but you could start with just configuring Envoy for HTTP/2 ingress and egress, and then look at gRPC specific fields in the API. If you can contribute back an example when you have one that'd be welcome.

**Comment by HappyCerberus** [comment]
Hmm, OK, maybe my low understanding of front-end concepts is really leading me astray here.

This is our setup in a very simplified form (I will treat the front-end here as black box), all of this is gRPC, front-end is javascript, Layer 1, Layer 2 is C++:

- front end sends request to Layer 1 component, some of these requests result in stateful processing, so this traffic needs to be sharded
- Layer 1 component gRPC requests to Layer 2 component which cache critical, so not exactly stateful, but moving the traffic for a "session" is extremely expensive, I can live with either sharding or sticky load balancing here

I forget what is the name of the Google internal service that provides dynamic sharding configs, I thought that Envoy was equivalent / similar to that.

**Comment by HappyCerberus** [comment]
After asking around, it seems that people are just treating gRPC as plain HTTP traffic.
I was pointed to this [method for injecting custom HTTP headers](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_client_context.html#a723eca3a227cffa120108e3fce01c230).

Is this what you would recommend?

**Comment by htuch** [comment]
What do you want to use the custom HTTP headers for?

**Comment by HappyCerberus** [comment]
Well, to insert the values that Envoy will use to shard / load balance based on.

**Comment by htuch** [comment]
Sure, that sounds reasonable.
