### ISSUE TITLE
extensions/watchdog coverage

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#13031]
Hello,
The Envoy project has been collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, source/extensions/watchdog, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in test/per_file_coverage.sh

Thanks!

**Comment by alyssawilk** [comment]
closing this one off as we don't have a workaround for death test coverage
