### ISSUE TITLE
TLS handshake to upstream fails on CLIENT_HELLO

### ISSUE THREAD

**Issue by coders-kitchen** [envoyproxy/envoy#13047]
*Title*: TLS handshake to upstream fails on CLIENT_HELLO

*Description*:
We are examining currently the usage of Ambassador on one of our Kubernetes clusters.
The cluster will run the WhatsApp business clients (https://developers.facebook.com/docs/whatsapp) and we need to expose endpoints for each WhatsApp business number running on the cluster.

While we're testing we faced the issue, that we can't access the exposed service.

When requesting the exposed URL we get this response 

    upstream connect error or disconnect/reset before headers. reset reason: connection failure

On the envoy logs we do see 

    [2020-09-01 17:59:25.483][20][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:197] [C2] handshake error: 1                              
    [2020-09-01 17:59:25.483][20][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C2] TLS error: 268436496:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE 268435610:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO  

and on the WhatsApp Web instance the logs stating

    SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 

In comparison, when accessing the service via `kubectl port-forward` and using `curl -k` we receive back the expected webpage

**Envoy version** 1.15.0

**WhatsApp Business client version** v.2.29.3

When using nginx this problem doesn't appear and TLS is correctly terminated on the proxy.

**Repro steps**:

_Requirements_
docker compose needs to be installed

_WhatsApp installation_

    git clone https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts.git
    cd WhatsApp-Business-API-Setup-Scripts/installation
    export WA_API_VERSION=2.29.3
    docker-compose up

_Envoy_

Attached is a zip with the config (windows machine, you may need to adapt the `socket_address.address`
[envoy-tls.zip](https://github.com/envoyproxy/envoy/files/5202083/envoy-tls.zip)

    docker build -t envoy:v1 .
    docker run --rm -d --name envoy -p 9901:9901 -p 10000:10000 envoy:v1    

Breaking call via envoy

    curl http://localhost:10000

Working call directly to the installation

    curl -k https://localhost:9090

*Logs*:
[trace.logs.txt](https://github.com/envoyproxy/envoy/files/5202103/trace.logs.txt)

Thank you in advance

Peter

**Comment by htuch** [comment]
@ggreenway @lizan @PiotrSikora any thoughts?

**Comment by ggreenway** [comment]
I think the key is the server error message: `no shared cipher`. The server is saying that it has no cipher suites in common with what the client advertised as supported.

To understand why it's not working, look at the configured cipher suites on both the client and the server. Probably one of them is very restrictive. Also, check the version of TLS being used. TLS 1.3 has different rules for cipher suite negotiation (and different supported cipher suites) from TLS 1.2 and earlier.

**Comment by coders-kitchen** [comment]
Hi,

thank you for the swift reply.

I made a quick test to see which cipher suite is agreed between `curl` and the service.

My findings so far are

_cipher suite used_ : `ECDHE-RSA-AES256-GCM-SHA384`
_TLS version_ : `1.2`

using `curl -k --ciphers ECDHE-RSA-AES256-GCM-SHA384 https://localhost:9090` works completely fine

in contrast using envoy with this

    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: whatsapp_service
              http_filters:
              - name: envoy.filters.http.router
      clusters:
      - name: whatsapp_service
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: whatsapp_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal
                    port_value: 9090
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config: 
            "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
            common_tls_context:
              tls_params:
                cipher_suites: ["ECDHE-RSA-AES256-GCM-SHA384"]
                tls_maximum_protocol_version: TLSv1_2


is breaking

accordingly to the TCP Dump both calls do propose the Cipher Suite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030).

If tested it again with nginx and the agreed cipher suite is the same (TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030) ).

Please find attached a tcp dump with the following order

- curl against NGINX proxying to the https://localhost:9090
- `curl -k --ciphers ECDHE-RSA-AES256-GCM-SHA384 https://localhost:9090`
- curl against envoy proxing to the https://localhost:9090

[nginx_curl_envoy.zip](https://github.com/envoyproxy/envoy/files/5203629/nginx_curl_envoy.zip)

Thank you

**Comment by ggreenway** [comment]
It's hard to say what's wrong without knowing how your upstream (nginx) is configured. Check for things like whether you require SNI, supported EC curves, and any other TLS config. If that fails, I'd compare the working and non-working clienthello in wireshark and look for differences, and maybe cross-reference it with the serverhello to see what is being selected in the working case, to figure out which bit is incompatible.

**Comment by coders-kitchen** [comment]
hi,

thanks for the hints, we will investigate on this direction further :)

**Comment by PiotrSikora** [comment]
Per your description, both `curl` and NGINX are connecting to `localhost:9090`, but Envoy is configured to connect to `host.docker.internal:9090`. Maybe that's the issue?

**Comment by coders-kitchen** [comment]
Again thanks for the hints.

We found the root cause, the service is configured with `ssl.ec-curve = "secp384r1"`

Envoy is using as default either `X25519` and `P-256` or just `P-256` (https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v2/api/v2/auth/common.proto)

changing the ecdh_curve setting to `P-384` solved the issue.

**Comment by techpavan** [comment]
Adding my experience on this. The same behavior was observed in my testing, but the logs were not helpful. This configuration was working on some websites, but failing on others. As the working websites are huge organizations and failed are the smaller ones, I guessed it to be shared servers and issue related to SNI. Adding the appropriate sni configuration fixed it.
