### ISSUE TITLE
Alias issue in DeltaXDS，which can cause envoy send request, request, ack

### ISSUE THREAD

**Issue by Agent-Tao** [envoyproxy/envoy#13046]
Alias issue in DeltaXDS，which can cause envoy send request, request, ack

*Description*:
if envoy add a watch for "redis_aaaaa" resource in deltaAPI,
the xds server response like this:
alias: redis_aaaaa
name:""

when envoy get this reponse，convertAliasWatchesToNameWatches will cause updateInterest.
but still can invoke CdsApiImpl::onConfigUpdate.
this strange thing is:
maybe_resume_eds = cm_.adsMux()->pause(type_urls) can cause envoy send CDS request again to XDS server, not eds.

in xds server side, the messages are:
1: 
type_url=type.googleapis.com/envoy.config.cluster.v3.Cluster
Subscribe=[redis_aaaaa]
Nonce=
Unsubscribe=[]

2:
type_url=type.googleapis.com/envoy.config.cluster.v3.Cluster
Subscribe=[]
Nonce=
Unsubscribe=[redis_aaaaa]

3:
type_url=type.googleapis.com/envoy.config.cluster.v3.Cluster
Subscribe=[]
Nonce=redis_aaaaa$1.0
Unsubscribe=[]

is it according with delta xds design or it is a bug?

**Comment by htuch** [comment]
Can you elaborate on why you are using aliases for CDS? Typically aliases are reserved for VHDS.

**Comment by Agent-Tao** [comment]
We do not intent to use alias, but some  people working on control plane who use alias instead of name by mistake which cause envoy  unusual behavior.  If aliases are for VHDS, should we add some check to prevent using it in other type of xds?

**Comment by htuch** [comment]
I think you should definitely not be sending alias instead of name. It would make sense to add to Envoy some validation that aliases aren't being used outside of VHDS.

**Comment by Agent-Tao** [comment]
fine，thanks, I would do this later

**Comment by Agent-Tao** [comment]
I can not reproduce this problem in new version.  It seems that the code has been refactored， the 'convertAliasWatchesToNameWatches'  also does not exist. so close this issue.
