### ISSUE TITLE
Allow HTTP CONNECT proxying to route based on HTTP headers

### ISSUE THREAD

**Issue by nicktrav** [envoyproxy/envoy#13042]
Currently, [`connect_matcher`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch) only supports matching on the HTTP `CONNECT` method.

I'd like to propose / request enhancing this matcher by allowing it to match on the other fields under a route's `match` config. Specifically, we'd like to be able to use the HTTP headers to control where the CONNECT is directed.

In terms of the existing code, `ConnectRouteEntryImpl` only supports checking to see if the request method is `CONNECT`, here:

https://github.com/envoyproxy/envoy/blob/50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/source/common/router/config_impl.cc#L1029-L1036

The following patch is essentially what we're looking for:

```patch
diff --git a/source/common/router/config_impl.cc b/source/common/router/config_impl.cc
index ae92edeab..d5ef311c5 100644
--- a/source/common/router/config_impl.cc
+++ b/source/common/router/config_impl.cc
@@ -1027,9 +1027,10 @@ void ConnectRouteEntryImpl::rewritePathHeader(Http::RequestHeaderMap& headers,
 }

 RouteConstSharedPtr ConnectRouteEntryImpl::matches(const Http::RequestHeaderMap& headers,
-                                                   const StreamInfo::StreamInfo&,
+                                                   const StreamInfo::StreamInfo& stream_info,
                                                    uint64_t random_value) const {
-  if (Http::HeaderUtility::isConnect(headers)) {
+  if (Http::HeaderUtility::isConnect(headers) &&
+      RouteEntryImplBase::matchRoute(headers, stream_info, random_value)) {
     return clusterEntry(headers, random_value);
   }
   return nullptr;
```

Happy to put up this patch along with some tests, unless there's good reason for not allowing more advanced matching for CONNECT?

**Comment by htuch** [comment]
@alyssawilk WDYT?

**Comment by alyssawilk** [comment]
No objection on my part.  I think the problem was that all the other matchers assume the request has a path, and CONNECT HTTP/1.1 does not which is why @mattklein123 preferred separate matching entirely.  Extending the CONNECT matcher to do other header based matching SGTM as long as we're careful to continue supporting nonexistent paths :-)

**Comment by mattklein123** [comment]
SGTM!
