### ISSUE TITLE
HTTP/2 CONNECT implementation is possibly not compliant with h/2 spec

### ISSUE THREAD

**Issue by nicktrav** [envoyproxy/envoy#13044]
This is a minor nitpick on some documentation I found for the CONNECT proxy behavior that doesn't like up with the HTTP/2 spec.

The existing documentation for [`connect_matcher`](https://github.com/envoyproxy/envoy/blob/50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/api/envoy/config/route/v3/route_components.proto#L438-L440) mentions this:

> For HTTP/2, where CONNECT requests may have a path, the path matchers will work if there is a path present

The h/2 spec has this to say in [section 8.3](https://tools.ietf.org/html/rfc7540#section-8.3):

> The ":scheme" and ":path" pseudo-header fields MUST be omitted.

> A CONNECT request that does not conform to these restrictions is
> malformed (Section 8.1.2.6).

I noticed that when this functionality was added in #10894, some of the implementation makes use of the path, which would seemingly violate the spec as a client should not be sending `:path` in the request.

I don't think anything is _broken_ right now (CONNECT with h/1 and h/2 works great!), but I wanted to mention this to see if this is just a docs issue, or something that should actually be fixed in the implementation.

**Comment by htuch** [comment]
@alyssawilk to clarify.

**Comment by alyssawilk** [comment]
Totally fair point by the original RFC.  Envoy also supports extended connect:

https://tools.ietf.org/id/draft-mcmanus-httpbis-h2-websockets-02.html#the-extended-connect-method

On requests that contain the :protocol pseudo-header field, the
      :scheme and :path pseudo-header fields of the target URI (see
      Section 5) MUST also be included.

If you can think of a place to include links which would make it more clear what's going on (and not perplex the next person) that'd be great!

**Comment by nicktrav** [comment]
Ah! This is great. TIL.

I'll see how the existing documentation could be enhanced. Thanks!
