### ISSUE TITLE
How to get "response" data in the HTTP trace at the proxy level

### ISSUE THREAD

**Issue by pp-dsouzajude** [envoyproxy/envoy#13059]
*Title*: *How to get "response" data in the HTTP trace at the proxy level?*

*Description*:
I have a service mesh setup using Envoy proxy as the data plane. Envoy is configured to send tracing data to `AWS X-Ray` on port 2000. In this setup I have two services `dashboard` and `counter` where the dashboard communicates with the counter service to increase the counter. The two communicate via the envoy proxy in the following way:

```
client --> ingress-gw --> 21000:dashboard-proxy:5000 <--> dashboard
                                 |
                                 | --> 21000:counter-proxy --> counter
```

Since I have enabled tracing, I expect to see HTTP response data (in particular the response status codes) from the proxies themselves, but the response seems to be empty in the trace. A snipped of the trace looks like this:

```json
{
    "Segments": [
        {
            "Document": {
                "id": "000001d0dca79ea9",
                "name": "dashboard-proxy",
                "start_time": 1599819018.758217,
                "trace_id": "1-5f5b4cf5-3358cf2cd62199d3fba71f9d",
                "end_time": 1599819018.767297,
                "parent_id": "0000019605a00b3c",
                "http": {
                    "request": {
                        "url": "https://dashboard.ingress/",
                        "method": "GET",
                        "user_agent": "curl/7.61.1",
                        "client_ip": "10.140.27.62"
                    },
                    "response": {}
                },
                "annotations": {
                    "response_flags": "-",
                    "component": "proxy",
                    "upstream_cluster": "local_app",
                    "request_size": "0",
                    "downstream_cluster": "dashboard",
                    "node_id": "dashboard-10-140-20-30-6c6cf4c2f42443d2b2cb0fe35d72fea8-sidecar-proxy"
                }
            },
            "Id": "000001d0dca79ea9"
        }
   ]
}
```

Here you can see the trace from the `dashboard-proxy` is empty! ie. `response: {}` and **I can't seem to understand why this is the case**. I need help with this.

As per the above flow, the `dashboard-proxy` has an `ingress` listener listening for requests on port `21000` and it also has an `egress` listener listening for requests from the dashboard service on port `5000` which then routes traffic to the `counter-proxy`. Both listeners have tracing enabled.

**Is this a limitation that HTTP tracing data for responses cannot be captured at the proxy level? If not, could someone help me configure Envoy correctly so I can get this data in my trace.**

**Additional Info:**
* Envoy version: v1.14.4
* Consul version: 1.8.3

Thanks!

[optional *Relevant Links*:]
* [Consul Connect](https://www.consul.io/docs/connect)
* [Consul Connect Envoy Integration](https://www.consul.io/docs/connect/proxies/envoy)
* [AWS X-Ray](https://aws.amazon.com/xray/)
* [AWS X-Ray Envoy Configuration](https://www.envoyproxy.io/docs/envoy/v1.14.4/api-v2/config/trace/v2alpha/xray.proto#envoy-api-msg-config-trace-v2alpha-xrayconfig)

**Please see attached the following:**
* Sample envoy configuration for the dashboard-proxy [consul-mesh-envoy-sample.json.txt](https://github.com/envoyproxy/envoy/files/5208449/consul-mesh-envoy-sample.json.txt)
* AWS X-Ray trace data where response is empty [trace-data.json.txt](https://github.com/envoyproxy/envoy/files/5208451/trace-data.json.txt)

**Comment by htuch** [comment]
@marcomagdy @lavignes can you folks shed any light on this? Looks like the X-ray tracer does take into account the status tag.

**Comment by dastbe** [comment]
@pp-dsouzajude could you try Envoy 1.15? We can take a deeper look at this, but I'm suspecting that you are getting bitten by https://github.com/envoyproxy/envoy/pull/10834 which was merged and made available in the 1.15 release.

**Comment by pp-dsouzajude** [comment]
Seems to be so! Unfortunately as of now, Consul only supports versions until v1.14.4 of Envoy, so I won't be able to test with the latest release of Consul, but they've told me that I can atleast try with the [dev](https://hub.docker.com/r/hashicorpdev/consul), so i'll give it a try and see if it works and get back to you on this unless you have some other workaround from the dockerized AWS X-Ray daemon end?! @dastbe

**Comment by pp-dsouzajude** [comment]
@dastbe It works now. Thanks! I just upgraded to Envoy v1.15.0 and it solved the issue.

The trace looks beautiful now!

**Thanks a lot for this awesome piece of software!**

<img width="1099" alt="mesh-xray-trace" src="https://user-images.githubusercontent.com/61741037/92994583-dffba100-f4fb-11ea-86b4-820a1cec02bf.png">
