### ISSUE TITLE
fault injection: delayed request counts as active fault even after delay is finished

### ISSUE THREAD

**Issue by markdroth** [envoyproxy/envoy#13069]
When the HTTP fault injection filter triggers a delay for a request, that request continues to count as an active fault after the delay has elapsed.  It does not stop counting as an active fault until the request finishes.

For simple short-lived requests, that's probably fine, since the request will not last much longer beyond the end of the delay anyway.  However, for a long-lived stream (e.g., a gRPC streaming call), this seems like the wrong thing: if the fault injection filter delays the request by 30 seconds and then the request lasts for hours or days after that, it should not continue to count as an active fault.

I have not actually seen this bug in action; it's something that we discovered when trying to figure out how to implement the fault injection functionality in gRPC.  The only place in the fault injection filter where it decrements the counter is in `onDestroy()`:

https://github.com/envoyproxy/envoy/blob/429d5e842933059b33a525ca3adc3782ee203b0e/source/extensions/filters/http/fault/fault_filter.cc#L433

I imagine that one could easily reproduce this in a sandboxed Envoy by setting the fault injection filter to add a 30-second delay to all RPCs and then starting a gRPC streaming call.  Once the fault ends but the streaming call is still in flight, the counter should still say 1.

CC @htuch

**Comment by mattklein123** [comment]
Yeah agreed we should fix this. cc @Augustyniak @snowp

**Comment by kailun-qin** [comment]
Tested using sandboxed environment. The issue can be reproduced w/ gRPC streaming calls.
