### ISSUE TITLE
extraneous cors http_filter in cors example

### ISSUE THREAD

**Issue by ronaldpetty** [envoyproxy/envoy#13089]
*Title*: *extraneous cors filter in cors example*

*Description*:
> In github.com/envoyproxy/envoy/examples/cors/frontend/front-envoy.yaml there is a http_filter for envoy.filters.http.cors.  I could be confused but I don't think that is necessary.  The cors setup is on the backend front-envoy (backend/front-envoy.yaml). I removed it and everything worked the same - as expected.  If I am wrong can someone point me in the right direction?

**Comment by mattklein123** [comment]
cc @dschaller @phlax
