### ISSUE TITLE
Constraint checking for v2 protos (and JSON translations)

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1308]
In v1, we rely on various JSON config schema checks. In v2, we don't have any way to express basic sanity properties such as required fields being present, a timeout field being non-zero, string non-empty. 

Some of these constraints are implied by the protobuf (e.g. enum type values), but the protobuf type system is weaker than JSON schema in many respects. During initial work in #1284, we can still rely on the v1 JSON schema checks, but as soon as we start consuming v2 APIs directly from management servers we need to add this behavior.

Some alternatives to solving this:
1. Add checks directly at consuming sites in the Envoy config ingestion code. 
2. Convert protos to canonical JSON, add a JSON schema that reflects the constraints and used the existing RapidJSON schema check.
3. Use Google's proto internal constraint language.

(1) is simple, but makes the schema implicit in the code, so we don't get to use it in other tools that check configs. OTOH, JSON schema is not very deep and only reflects some of what makes a sound configuration, so this isn't such a huge loss. (2) involves repeating the protos in a JSON schema file, which is verbose and needs to be kept in sync with the protos. It's unclear when/if (3) will be OSS.

@mattklein123 @louiscryan for comment.

**Comment by mattklein123** [comment]
(3) would be best. Can we see about timeline? I assume it's not an option.

(2) sounds kind of awful.

(1) I guess is the fallback. I think if we factored the code checks correctly we could do it in a way where we could user it both in tools and main code as well as the "dry run"/canary functionality if that gets built.

**Comment by htuch** [comment]
Going over https://github.com/lyft/envoy/blob/master/source/common/json/config_schemas.cc and observing how the JSON schema is used today, the checks that we get from it are:

1. Types {object, array, string, boolean, integer, enum}.
2. `required` properties on objects.
3. Restrictions on `additionalProperties`.
4. `minLength` on strings.
5. `minimum`, `exclusiveMinimum`, `maximum` on integers.
6. `minItems` and `uniqueItems` on arrays.
7. `oneOf` object properties.
8. `pattern` regex restrictions on strings.
9. Maps from enums, where in proto we are doing repeated flattened (key, value) pairs due to a restriction on map keys being non-enum.

By construction, proto3 will provide (1), (3) and (7). Constraint checks will need to validate the rest.

**Comment by htuch** [comment]
(2) is essentially requiring that a message field is set for all wrapped types, Duration, messages etc. For strings, we will treat non-empty as the same as being set, in which case this is the same as (4).

**Comment by htuch** [comment]
Started to prototype this. One issue I've hit is whether we want to push the `VALIDATE_MIN_LENGTH` to the sites that directly consume deeply nested fields (e.g. the `ip_address` inside an endpoint at the leaf of a `ClusterLoadAssignment`), or whether we want to write a separate validation library.

In favor of local checks is that doing this in a separate library requires writing proto traversal code to iterate over the entire message tree for each proto, similar to code that already exists in the code that consumes protos today. So, we end up writing more verbose boiler plate code to make this work. Also, the validation library may drift from the code (same criticism as schema).

In favor of a separate validation library is that it can in principle be separately linked into other tools to validate configs without requiring full Envoy config processing. The benefits of this might be more hypothetical than real though, given that this is a C++ library and management servers are often written in things like Go etc. Plus, these are just weak checks, as much as they are nice for sanity checking, they don't tell you if it will blend.

I'm also going to quickly scope out the work of writing a protoc plugin for this tomorrow, if it's going to take me as much time or less as doing the boiler plate for the validation library, it might be more fruitful.

@mattklein123 Any thoughts?

**Comment by mattklein123** [comment]
I think per our offline thread if we can do this via protoc plugin that @rodaine is working that would be pretty awesome because then it will work in both go and c++ (and maybe other langs in the future).

**Comment by htuch** [comment]
In addition to the above validations, we should check that enums are within range, see https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#enum.

**Comment by rodaine** [comment]
> In addition to the above validations, we should check that enums are within range

Totally agree. Adding a rule for `defined_only`

**Comment by htuch** [comment]
Note to self: make sure we apply `minItems` across the various places we're doing `[0]` on lists today with the assumption that we're taking the JSON -> proto translation path and have a guaranteed singleton list.

**Comment by htuch** [comment]
@rodaine have you given any thought to the treatment of `oneof` and backwards compatibility? https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility-issues. Seems like it would be useful to add in support to check that we really do have exactly one of the currently active fields during validation, so that code can alter switch on the known values without having to worry about the newer/older fields.

**Comment by rodaine** [comment]
Interesting, so if I'm understanding what you're suggesting, checking that at least one of the `oneof` fields is set?

**Comment by mattklein123** [comment]
Calling this done! Yay!
