### ISSUE TITLE
safer example runner

### ISSUE THREAD

**Issue by ronaldpetty** [envoyproxy/envoy#13084]
*Title*: *safer example runner*

*Description*:
> I just used envoy/examples/verify-common.sh and during its cleanup it does a docker prune, which removes ALL stopped containers.  I have dozens of containers in the stop state and use them for various unrelated activities.  While I did read the script, I didn't put it together that "verify-...." was going to remove things it didn't own.  I recommend injecting id information on these related containers and only delete them.  Maybe via ENV, or something like that.  If others think that is a good idea (or maybe just adding documentation or a feature gate on delete) I am open to implementing it.

**Comment by mattklein123** [comment]
cc @phlax

**Comment by phlax** [comment]
hi @ronaldpetty apologies for this. 

I originally wrapped this test in a docker-in-docker container partly for this reason.

the wrapper wasnt added to the ci pipeline - but im thinking to add at least some documentation to make it easy to run these tests in an isolated way

**Comment by ronaldpetty** [comment]
Hi @phlax, not a problem, I am new here :).

Happy to help if you have something at some point!  Maybe close for now?

**Comment by phlax** [comment]
> Maybe close for now?

lets keep it open  until i add the relevant docs

**Comment by phlax** [comment]
@ronaldpetty thinking about this further - im realising its an issue just running a single `verify.sh` script. 

Im gonna PR so it prunes in ci as required, but not when you run individual tests

**Comment by ronaldpetty** [comment]
That sounds right.  I was digging into examples and still trying to see how
to run them.

**Comment by phlax** [comment]
after testing this further, it turns out that the prune isnt required at all.
