### ISSUE TITLE
nodeID is empty when envoy reconnect to go-control-plane

### ISSUE THREAD

**Issue by ElwinGao4444** [envoyproxy/envoy#13105]
when I kill go-control-plane and restart it, envoy can not reconnect to it successful, I found that:
1. envoy re-send req to go-control-plane without "Node" struct
![image](https://user-images.githubusercontent.com/48503777/93197484-47288800-f77e-11ea-976c-7f44ae9c3c48.png)
2. type Runtime have Node struct, but CDS, LDS don't have Node struct(I don't known what about others types)
![image](https://user-images.githubusercontent.com/48503777/93196994-b2258f00-f77d-11ea-9073-b1eede21ed72.png)
3. when restart envoy, everythin is ok.

env: CentOS 7
envoy version: 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL
go-control-plane version:github.com/envoyproxy/go-control-plane v0.9.7-0.20200826174037-95aae272b9d1

**Comment by mattklein123** [comment]
Possibly related to https://github.com/envoyproxy/envoy/issues/9682. cc @kyessenov
