### ISSUE TITLE
Does envoy support proxy authorization?

### ISSUE THREAD

**Issue by chengdol** [envoyproxy/envoy#13101]
*Title*: *Proxy authorization support on envoy?*

*Description*:
I use envoy as an https forward proxy (tunnel), then I need to add proxy authorization on it. for example, ideally it should work like this:
```
curl -x envoy:3128 https://www.example.org -U [user:password]
```
The https forwarding is good with CONNECT, but I did not find stuff relates to proxy-authorization, the only thing I find is [External Authorization](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto), from the demo, I am not sure whether it is able or how does it work with CONNECT? All experiments I have tried failed.

Can someone share some lights on it? Thanks!

**Comment by mattklein123** [comment]
We don't support proxy auth today, though you could built with a custom filter or Lua.
