### ISSUE TITLE
quic: support in-place filterChainUpdate

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#13115]
Need to add handling in udp case here: https://github.com/envoyproxy/envoy/blob/4706ee01abe191eef73c64d86c1835baf566323c/source/server/connection_handler_impl.cc#L40

**Comment by alyssawilk** [comment]
lazy-ask: was this not accepting updates to the quic filter chain, or not being able to in-place add/remove quic listeners?

**Comment by ggreenway** [comment]
The call to `listener.second.tcpListener()->get().updateListenerConfig(config);` is guarded by `if (config.listenSocketFactory().socketType() == Network::Socket::Type::Stream) {`. The ask is to do the same thing for datagram listeners.

**Comment by alyssawilk** [comment]
OK, I think we need to either support this for alpha or make it really clear in docs it's not yet supported.

It shouldn't be too much work to forward packets for old connections to the old listener and new to the new listener, but it's not trivial.

**Comment by lambdai** [comment]
The ownership of the filter chain is not clear to me: Quic listener need to decide whether the old and new config has filter chain only change.
Also, the per worker thread listener needs to track what connections are bind to the gone filter chain. AFAIK this is done in ActiveTcpListener, the quic listener needs a similar accounting.

**Comment by alyssawilk** [comment]
Ok, I'm going to note lack of support in the docs PR, so removing this from the Alpha list.
