### ISSUE TITLE
quic: disallow ConnectionBalancer config

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#13116]
ConnectionBalancer isn't currently supported for udp/quic, and implementing it would probably be CPU-inefficient due to packet forwarding between workers. Disallow this config.

This should be done before MVP as it would other invalidate a previously-loadable config.

**Comment by danzh2010** [comment]
More details: QUIC traffic shouldn't have connection_balance_config 
configured at all: https://github.com/envoyproxy/envoy/blob/ba474ac375418d5529a30a9510a8ff5f0a5ada9a/generated_api_shadow/envoy/config/listener/v3/listener.proto#L256

ListenerImpl::buildSocketOptions() should throw if both connection_balance_config and quic are  configured.
