### ISSUE TITLE
Add DurationTimeout response flag for HCM.

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#13142]
In PR #12495, I have added the "DurationTimeout" response flag for TCP connection timeout and should be the same for HTTP also.
CC @htuch

**Comment by yanavlasov** [comment]
Don't we already have `max_connection_duration` in the [HttpProtocolOptions](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-httpprotocoloptions) ?

**Comment by mk46** [comment]
Yes, we have but when max_connection_duration reached on HTTP connection-level then it doesn't produce any response flag.
https://github.com/envoyproxy/envoy/blob/419428a82945a1a2ab0ab48e054e76ee851c5450/source/common/http/conn_manager_impl.cc#L443
When  #12495  got merged, "DurationTimeout" as a response flag will be produced at the TCP connection-level. It should be the same for both.
