### ISSUE TITLE
All spans get kind = CLIENT when sharedSpanContext = false

### ISSUE THREAD

**Issue by LarsAndreasEk** [envoyproxy/envoy#13141]
Hi,

When sharedSpanContext is set to false, which is the default in istio, all spans sent from sidecars to zipkin is marked as kind = CLIENT, at least in my setup.

I wonder whether this is by design. My understanding is that egress traffic should get kind = CLIENT, whereas ingress traffic should have kind = SERVER, regardless of whether shared spans are used or not.

Setup: k8s, istio (tested both 1.7 and 1.6), zipkin tracing. Tested HTTP traffic with curl, using the BookInfo sample. 

Please advice.

Best regards,
Lars Andreas Ek

**Comment by LarsAndreasEk** [comment]
Seems related to https://github.com/envoyproxy/envoy/issues/4397 and https://github.com/envoyproxy/envoy/pull/4426

**Comment by mattklein123** [comment]
cc @objectiser
