### ISSUE TITLE
Retrieving socket options in access loggers

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#13166]
Problem we're trying to solve: extract downstream/upstream remote socket options for use in an access logger.

I think we can do this for downstream via a custom listener filter that has access to the Socket and place this in dynamic metadata, which the access logger can then consume.

I don't see a mechanism to do this upstream, upstream network filters don't have a way to reach into the Socket.

1. Is this a correct assessment of the current situation?
2. Would it be reasonable to provide upstream network filters the ability to peek at the Socket for getsockopt (possibly wrapped to limit interactions to only this method)?
3. Is there a more principled way we could ask Envoy to collection a set of socket options and make them available for logging? I can imagine a config option to specify which socket options to collect, alongside which ones to set as we have today.

CC @florincoras @mattklein123 @eziskind

**Comment by yanavlasov** [comment]
It may depend on what socket options are of interest. If this comes from a specific request can we get a list of options?

**Comment by eziskind** [comment]
This is for a Google-internal use-case where we want to get a custom socket option that has been set by the virtual networking layer.

**Comment by mattklein123** [comment]
> Would it be reasonable to provide upstream network filters the ability to peek at the Socket for getsockopt (possibly wrapped to limit interactions to only this method)?

This seems OK to me at the network filter level, especially if it's only const access.

> Is there a more principled way we could ask Envoy to collection a set of socket options and make them available for logging? I can imagine a config option to specify which socket options to collect, alongside which ones to set as we have today.

I think we could do this, but I'm not sure it's worth it if we do the previous item, at leas for now.

**Comment by htuch** [comment]
We discussed offline and the preferred option is network filter access to socket options, assigned to @eziskind.

**Comment by htuch** [comment]
@eziskind are you planning on tackling this in the short term or should we park it as help wanted?

**Comment by eziskind** [comment]
Yes, I'll probably get to this next quarter. You can mark it "no stalebot"?
