### ISSUE TITLE
log: allow extensions enrich the logs (regression)

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy#13174]
We have some use-cases where a filter needs to set dynamic metadata when the stream ends, but before log() happens, to enrich the logs with data gathered through the lifecycle of the request (and regardless if it ended or reset).

We used to do it using onDestroy(), but now that log() happens before onDestroy, this approach doesn't work anymore (as of https://github.com/envoyproxy/envoy/pull/12850).

solution suggestion: adding another callback to `StreamFilterBase` named `onStreamCompleted` that will be called just before `log()` happens here: https://github.com/envoyproxy/envoy/blob/84f538f1ddcb5c16d98627df8b5e8c38f0f26720/source/common/http/conn_manager_impl.cc#L207-L208

This will allow extensions to enrich the logs, without the need to reason on all the cases where the stream might end (i.e. if it was reset or not).

If there are no objections, we can contribute this change.

cc @kyessenov

**Comment by mattklein123** [comment]
Why can't logging happen immediately after `onDestroy()` of all filters?

**Comment by yuval-k** [comment]
I have no issue with that, but please see:
https://github.com/envoyproxy/envoy/pull/12850
https://github.com/envoyproxy/envoy/issues/12616

**Comment by mattklein123** [comment]
The bug was about logging happening after deferred destruction. I don't see any issue with doing the logging phase after onDestroy() is called for each filter, though this would need to be documented that log happens after onDestroy(). I'm not sure if assumptions are being made on the inverse. It would be nice to avoid another callback if we don't need it.

cc @jplevyak @snowp

**Comment by yuval-k** [comment]
SGTM

**Comment by kyessenov** [comment]
I think it's confusing to call `onDestroy` before `onLog` for filters that cross-register as log handlers, but it's not a big deal.
We wanted to do blocking access loggers at some point https://github.com/envoyproxy/envoy/issues/10326 which might exacerbate this issue.

**Comment by mattklein123** [comment]
> I think it's confusing to call onDestroy before onLog for filters that cross-register as log handlers, but it's not a big deal.
We wanted to do blocking access loggers at some point #10326 which might exacerbate this issue.

I don't feel strongly about it. If we do want a new callback, I might recommend calling it onPreDestroy(), so the flow is onPreDestroy(), onLog(), onDestroy().

**Comment by kyessenov** [comment]
What do you think about changing your filter to cross-register as access logger (`addAccessLogHandler`)? This is more aligned with the intent. We may need to make sure the ordering is right (HTTP filters before access log handlers).

**Comment by yuval-k** [comment]
yes, that's exactly the problem with `addAccessLogHandler` - the order.
I think it is better to have another callback or move `onDestroy` before on `log` than rely on ordering, as the semantics are more clear and less likely to break in the future.
i.e. - how do you know to tell apart a real access log extension (that writes to a new sink) vs something that enriches the existing access logs, if they both use the same callback?
That said, I'm open to implement any fix that will get the consensus.
WDYT?

**Comment by mattklein123** [comment]
> I think it is better to have another callback (onPreDestroy) or move onDestroy before on log than rely on ordering, as the semantics are more clear and less likely to break in the future.

Yeah I agree. Let's just do it. It will be more clear. I think my only remaining question is:
1) Should this new callback be opt-in (via registration) to avoid compile breakages for existing filters?
2) If not, should we actually do a larger change to make a single `onDestroyPhase(...)` function which takes a stage enum? This seems more future proof but would be a larger breaking change.

WDYT? cc @snowp @alyssawilk

**Comment by alyssawilk** [comment]
I'm fine with an optional (default no-op) onEncodeComplete - seems like a reasonable entry point and I prefer no-op base class to 50 filters having to make a no-op.

**Comment by yuval-k** [comment]
> I'm fine with an optional (default no-op) onEncodeComplete - seems like a reasonable entry point and I prefer no-op base class to 50 filters having to make a no-op.

@mattklein123 Any objections to optional default no-op callback?
Assuming we are all in agreement I can open a PR later today.|

**Comment by mattklein123** [comment]
SGTM! Please also add good docs to the rest of the functions in filter.h so it's clear to the next person what the expectations are. Thank you!
