### ISSUE TITLE
Tunnel TCP over HTTP/2 POST

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#13185]
Today, Envoy supports tunneling [TCP over HTTP/2 CONNECT](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-tcp-over-http-2), which is awesome! 

I understand that HTTP/2 CONNECT method is designed to handle such a use case. However, edge proxy might not accept CONNECT due to [security concern](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-tcp-over-http-2).

Therefore, I wonder if we can extend the existing TCP proxy to support HTTP/2 POST, so that any edge proxies would be happy to accept the tunneling request.

**Comment by wlhee** [comment]
cc @htuch @alyssawilk

**Comment by alyssawilk** [comment]
While wrapping TCP in CONNECT is industry standard (and included in various RFCs) I haven't heard of any standards around POST encapsulation.  Unless I'm missing one, I suspect we wouldn't want that upstream, but I can think of some fairly straight-forward changes to upstream Envoy we could make to make it fairly easy to implement a custom plugin to allow this locally.

As a side note, the security concern with CONNECT is mainly that when you decapsulate payload you're letting potentially unsanitized content into your network.  I think switching to encapsulating and decapsulating via POST would just be hiding the security problem so probably more dangerous than CONNECT.   You'd risk whatever proxy you're proxying with not supporting fully bidirectional data with POST (where often when the response is started, the request data is stopped)

**Comment by wlhee** [comment]
Thanks Alyssa, a custom plugin sounds awesome! How would we move forward to adding a plugin? I could help contributing if you could share some pointers with me.

**Comment by alyssawilk** [comment]
Unfortunately it's not quite as simple as adding a plug-in, I think first we'd need to make tcp pluggable.
@lambdai had started looking into that but is now focused on the in-memory proxying, but might be able to catch you up.  Basically we'd want to refactor source/common/tcp_proxy/upstream.* (in place) to mimic the HTTP GenericConnectionPool and GenericUpstream, then add config to make it pluggable.  Happy to explain in more detail if you want to ping me on hangouts.

**Comment by alyssawilk** [comment]
Ok, refactoring done, so I'll close this off as fixed once  #13548 lands

Functionally you should be able to create your own custom upstream like the generic upstream which instead of creating TCP or HTTP, creates TCP or _Your-custom-subclass_ which inherits from HttpUpstream and overrides setRequestEncoder to do the exact same code, only swapping POST instead of CONNECT.  If you need help with this feel free to give me a ping.

**Comment by wlhee** [comment]
Thanks Alyssa, I will check it!

**Comment by wlhee** [comment]
@alyssawilk based on my experiment, it looks like TcpProxy or some cluster magic for **upstream Envoy** also need to adjust accordingly?

I have the following setup:

client -> (TCP) -> client Envoy TcpProxy (tunnel enabled) -> (HTTP/2 POST) -> upstream Envoy HTTP listener -> loopback cluster -> (HTTP/1?) -> upstream Envoy TcpProxy listener -> (TCP) -> server

It looks like if client Envoy TcpProxy uses H2 POST in the HttpUpstream, it stops working.
It seems like there is some logic in upstream Envoy, which will only be triggered for HTTP/2 CONNECT and bytestream to unwrap the TCP stream from the H2 stream?

Example config can be found here: https://github.com/envoyproxy/envoy/issues/13001#issuecomment-689185101
