### ISSUE TITLE
Local Envoy Rate Limiting for HTTP

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy#13187]
*Title*: Support local rate limiting in Envoy for HTTP

*Description*:
Have per instance rate limiting support in Envoy for HTTP Requests.

Local Rate limiting exists for Envoy but it's specific to TCP connections(afaik) and thus would be good to extend the HTTP Rate limiter filter to support per instance rate limiting too. 

Proposal:
In rls.proto provide an option for local rate limiting rather than contacting the rate_limit_service.
In rate limit filter,  one of the challenging things would be how to maintain quota state per instance. We can explore following options:
1) Global table to store quota limits state. This is asked by Lua filter too : https://github.com/envoyproxy/envoy/issues/4027
2) Use thread local storage and have per worker quota. This would solve problem of not having to maintain mutexes between threads and still should provide reasonable quota limits.

**Comment by moderation** [comment]
Local rate limiting is already supported - https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/local_rate_limit_filter#config-network-filters-local-rate-limit

**Comment by mattklein123** [comment]
This is a dup of https://github.com/envoyproxy/envoy/issues/10813. cc @rgs1
