### ISSUE TITLE
Envoy documentation should be Windows friendly

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#13190]
*Title*: *Envoy documentation should be Windows-friendly*

*Description*:

Various code snippets and configuration files in the documentation (https://www.envoyproxy.io/docs/envoy/latest/start/start) rely on POSIX tools (e.g. `chown`) and primitives such as `/dev/null/`.

As we make progress towards #129, we should revisit the documentation experience for Windows users.

**As we do this work, we need to consider documentation bloat.** We should try to avoid duplicating every example and code snippet for Windows as it would make the documentation harder to maintain. 

`PowerShell` on Windows offers aliases for many of the commonly used POSIX commands so we could possibly leverage it.

cc @envoyproxy/windows-dev

**Comment by phlax** [comment]
we could possibly use something like this https://github.com/executablebooks/sphinx-tabs where docs diverge

**Comment by mattklein123** [comment]
> we could possibly use something like this https://github.com/executablebooks/sphinx-tabs where docs diverge

+1 I would love to figure this out for other reasons, like eventually maybe showing both YAML and JSON versions of snippets.

**Comment by davinci26** [comment]
Thanks for the pointer @phlax.  I will look at the issue this week. Assigning it to myself.

**Comment by phlax** [comment]
@davinci26 i separated the sphinx/tabs bit  out to a separate ticket - not sure if you want to take that one too - i figured we can land that quicker

**Comment by davinci26** [comment]
I dont mind taking that as well. I plan on building the documentation and starting to get familiar with it today so I can add the `sphnix-tabs` as an exercise to get myself familiar with the tech stack.

**Comment by phlax** [comment]
ref: #13229

**Comment by sunjayBhatia** [comment]
Cross reference child issue: https://github.com/envoyproxy/envoy/issues/14605

**Comment by sunjayBhatia** [comment]
cross reference child issue: https://github.com/envoyproxy/envoy/issues/14607

**Comment by davinci26** [comment]
@wrowe I think we can close this one now. We have done work to add the information needed to the docs. We can do it now on as-needed basis.

**Comment by davinci26** [comment]
This should now be closed with the existing documentation work.
