### ISSUE TITLE
Add Sphinx tab renderer to documentation

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13213]
## Description

Where docs diverge - eg:

- instructions for different platforms
- providing configs in different formats
- code snippets for different languages 

...it would be really useful to have tab rendering

## refs

- https://github.com/envoyproxy/envoy/issues/13190#issuecomment-695199756
- https://github.com/executablebooks/sphinx-tabs

**Comment by davinci26** [comment]
@phlax do you have any place in mind in the docs that we could use it today?

I can add it as an example usage in my PR.

**Comment by phlax** [comment]
i had a look through the docs - there are places where we could use this, but i dont see any where we could use it without changing quite a bit of docs.

One example would be the clone instructions in the sandbox examples - this could be split between ssh/https - but im also wondering if we should put the example headers to an rst include - so its probs out of scope of this ticket.

i also have another ticket im looking at #9662 - where i think it would be very helpful to have this in place

**Comment by phlax** [comment]
ref: #13229 

@davinci26 ^^

**Comment by phlax** [comment]
>  i dont see any where we could use it without changing quite a bit of docs... so its probs out of scope of this ticket.

@davinci26 i added #13230 which once landed will make it easy to update this example, ie

split https://github.com/envoyproxy/envoy/pull/13230/files#diff-ba8b9695d4b21caa10303d3c9be7aa9dR9 between `ssh`/`https`
