### ISSUE TITLE
Discussion: Envoy filter callbacks optimize

### ISSUE THREAD

**Issue by hdacer** [envoyproxy/envoy#13211]
Recently, I found a problem and wondered whether it can be optimized, below is the example code currently: 

![image](https://user-images.githubusercontent.com/16503505/93840961-c1986100-fcc4-11ea-839c-36f1197a8470.png)
// currently, all filter implementations are created like this.

    
> For each connection request, the framework will call the lambda expression created above, and the expression will dynamically create the same filter object repeatedly according to the configuration.

 
>  For a listener, the filter configuration is actually the same, and it should not be created repeatedly with the client as the granularity. Each client requests to share a full-time filter object. Under the current logic, it not only reduces the concurrent processing performance, but also brings the repeated overhead of memory.

> It is recommended to create the filter object as a globally shared one. When the filter configuration changes, it only needs to be updated once. Recommended improvement methods: First, in the filter configuration analysis stage, dynamically create a globally shared processing object according to the configuration, and hang it under the connection manager. Then, the lambda expression is modified as follows:

![image](https://user-images.githubusercontent.com/16503505/93840844-61092400-fcc4-11ea-9eb1-ad366fa45ed1.png)

**Comment by yanavlasov** [comment]
This will only work if a filter does not have per connection or per request (depending on filter type) state. The CORS filter you are referencing is an HTTP filter and it does have a per request state (i.e. `origin_`) so the approach you are suggesting will not work.
If you are building your own filter and you know that it does not have per connection or per request state you can use a shared filter object.

**Comment by hdacer** [comment]
> This will only work if a filter does not have per connection or per request (depending on filter type) state. The CORS filter you are referencing is an HTTP filter and it does have a per request state (i.e. `origin_`) so the approach you are suggesting will not work.
> If you are building your own filter and you know that it does not have per connection or per request state you can use a shared filter object.

**Comment by hdacer** [comment]
Yes, as you mentioned, we are building our own filter without per connection or per request state.

We refer to the existing filter framework and found that all current filters are designed in this way, so we doubt if there is any reason behind it.
