### ISSUE TITLE
envoy build in ubuntu and need some help

### ISSUE THREAD

**Issue by guoruijing** [envoyproxy/envoy#13227]
I failed to build envoy in ubuntu:

1) ubuntu 18.04
   a) container build: ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
     still in trying

   b) bare metal build: bazel build  //source/exe:envoy-static
   Hit issue https://github.com/envoyproxy/envoy/issues/13079

2) ubuntu 20.04

    a) container build: ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'

FAILED: Build did NOT complete successfully (894 packages loaded, 25584 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (894 packages loaded, 25584 targets configured)
./ci/do_ci.sh: line 49: pushd: bazel-testlogs: No such file or directory

    b) bare metal build: bazel build  //source/exe:envoy-static
I need to remove some compiler option to build out envoy:

iff --git a/bazel/envoy_internal.bzl b/bazel/envoy_internal.bzl
index 10b3448c0..3404d39f7 100644
--- a/bazel/envoy_internal.bzl
+++ b/bazel/envoy_internal.bzl
@@ -7,7 +7,6 @@ def envoy_copts(repository, test = False):
     posix_options = [
         "-Wall",
         "-Wextra",
-        "-Werror",
         "-Wnon-virtual-dtor",
         "-Woverloaded-virtual",
         "-Wold-style-cast",
diff --git a/bazel/external/quiche.BUILD b/bazel/external/quiche.BUILD
index 6ca8429b3..e3acf9a32 100644
--- a/bazel/external/quiche.BUILD
+++ b/bazel/external/quiche.BUILD
@@ -57,7 +57,6 @@ quiche_common_copts = [
     "-Wno-unused-function",
     # quic_inlined_frame.h uses offsetof() to optimize memory usage in frames.
     "-Wno-invalid-offsetof",
-    "-Wno-range-loop-analysis",
 ]

my questions: what approach is right to build envoy in ubuntu? OS? build command?
I use gcc. how can I change to clang?

**Comment by dio** [comment]
@guoruijing, try this: https://gist.github.com/dio/9a7c826a2dbf004a81112db0d167d209?

**Comment by NomadXD** [comment]
@dio Have you tried to built it with ubuntu 20.04 with clang ? Appreciate if you could provide some steps to build envoy with clang. I tried with gcc and the build fails due to a known issue that hasn't fixed so far i guess.

[https://github.com/envoyproxy/envoy/issues/10422](url)
