### ISSUE TITLE
TLS-PSK 

### ISSUE THREAD

**Issue by 7hacker** [envoyproxy/envoy#13237]
*Title*: Add TLS-PSK to Envoy

*Description*:
Envoy can be used as a TLS proxy for unsecure services, however currently supports TLS cert-based auth. TLS-PSK is a faster alternative that can be used for services running on low latency, low powered resources

**Comment by yanavlasov** [comment]
@PiotrSikora if you have any comments on supporting TLS-PSK

**Comment by salrashid123** [comment]
hi @ggreenway

could we add in one of the suggested labels to this FR to revivie it?

for ref, [stunnel supports](https://www.stunnel.org/auth.html)  it and here's a [trivial standalone example](https://gist.github.com/salrashid123/56f45cc54feae86014ecce16403a6c1a) in c

thanks

**Comment by ggreenway** [comment]
@salrashid123 only if someone is planning to work on it. This hasn't seen any activity in years. Are you planning to submit a PR?
