### ISSUE TITLE
Add a welcome message/ DCO nag from the repo bot to new contributors

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13232]
## Description

First time contributors often havent added DCO - when reviewers point  this out it can be misunderstood as a criticism or as a review of the PR.

If the repo bot automatically posted a message saying something like "welcome @newcontributor - please read contributing guidelines if you havent already..." - it could also nag about DCO if that hasnt been added already

not sure if this is possible - might make it easier for new contribs - also flags to reviewers more explicitly that its a new contributor

**Comment by mattklein123** [comment]
Agreed this would be neat. cc @itayd for thoughts on how to do this with RepoKitteh

**Comment by itayd** [comment]
can you define explicitly what needs to be done here?
when would the message be emitted? only for first time contributors? every pr?

**Comment by phlax** [comment]
>  when would the message be emitted? only for first time contributors? every pr?

the welcome message would be for first time contributors (i guess if they havent opened a PR before too ?)

for the DCO nag - i guess either whenever DCO will fail (need to look to see if this checks PR or commits...) or at least when a PR was opened and DCO would fail

**Comment by phlax** [comment]
> i need to look to see if this checks PR or commits...

thinking more about this - i think if any *commits* are missing DCO would probs be the rule to trigger

**Comment by itayd** [comment]
@phlax i think it makes sense on every time DCO emits, we should add a message that:
1. explain nicely that we don't hate the contributor, it's just DCO
2. explain how to resolve the DCO issue

Re the welcome message, why not just point to it from a PR template? Add a link to a document welcoming people.

**Comment by phlax** [comment]
> Re the welcome message, why not just point to it from a PR template? Add a link to a document welcoming people.

i was thinking this for a few reasons

- there are some links/messages in PR template already i think - but not everyone reads that properly
- in the case that DCO is missing, they will get a thankyou and welcome message first, so its less frightening
- makes it obvious to reviewers that its a new contrib

i think the DCO messaging is more important tho

**Comment by phlax** [comment]
...another reason...

if you create a new PR for the first time and it messages you immediately i think in most cases you will immediately receive an email with an `@contributor` message - and contrib guidelines etc

**Comment by phlax** [comment]
I was thinking for messages...

### welcome

```
Welcome @newcontributor and thankyou for your contribution.

We will try to review your Pull Request as quickly as possible.

In the meantime please read the contribution guidelines if you haven't already (link...)
```
### DCO
```
Hi @newcontributor it seems that one or more of the commits in your Pull Request has not been signed.

We require this to ensure we know and remember who made each contribution.

You can fix this with the following commands

INSTRUCTIONS

Full information can be found here (link...)

```

**Comment by itayd** [comment]
This makes sense. @phlax would you like to write this behavior yourself? I will teach you how.

**Comment by phlax** [comment]
> would you like to write this behavior yourself? I will teach you how.

i would love to! 

i had a quick look to see if i could figure it out - but it wasnt immediately obvious and i was working on other things

lmk what you want me to do to get started

**Comment by mattklein123** [comment]
I think this is working now.
