### ISSUE TITLE
Envoy proxy not working for HTTP/1.1 requests which are multi-part form uploads

### ISSUE THREAD

**Issue by tariq1890** [envoyproxy/envoy#13240]
*Description*:

We are facing issues when two services (which are sidecar'ed with envoy proxies) communicate over HTTP and attempt a multi-part POST requests. Please note that other POST and GET requests work fine with no issues.

We get the generic envoy 503 error: `upstream connect error or disconnect/reset before headers`. I am unable to understand what exactly went wrong from this error. 

These envoy proxies are managed through Istio and there have been multiple issues posted highlighting this issue:

https://github.com/istio/istio/issues/27423
https://github.com/istio/istio/issues/27373
https://github.com/istio/istio/issues/25734

Any insights on this would be appreciated. What do we look for? What most likely could have gone wrong as far as envoy proxy configuration is concerned?

**Comment by tariq1890** [comment]
Please refer to this link for debug logs: https://github.com/istio/istio/issues/27423#issuecomment-696363395

**Comment by yanavlasov** [comment]
I have looked at the log and it seems the the upstream server has closed connection about 500ms after it was established and request was sent. You may want to look at the logs on the upstream service to see if there was a reason for closing the connection. 

```
10:09:03  2020-09-18T17:08:34.099062Z	debug	envoy pool	queueing request due to no available connections
10:09:03  2020-09-18T17:08:34.099066Z	debug	envoy pool	creating a new connection
10:09:03  2020-09-18T17:08:34.099126Z	debug	envoy client	[C28] connecting
10:09:03  2020-09-18T17:08:34.099133Z	debug	envoy connection	[C28] connecting to 100.96.104.65:3000
10:09:03  2020-09-18T17:08:34.102893Z	debug	envoy connection	[C28] connection in progress
10:09:03  2020-09-18T17:08:34.103020Z	debug	envoy http	[C27][S2136150783590076220] request end stream
10:09:03  2020-09-18T17:08:34.103041Z	debug	envoy connection	[C28] connected
10:09:03  2020-09-18T17:08:34.103080Z	debug	envoy connection	[C28] handshake expecting read
10:09:03  2020-09-18T17:08:34.106345Z	debug	envoy connection	[C28] handshake expecting read
10:09:03  2020-09-18T17:08:34.106359Z	debug	envoy connection	[C28] handshake expecting read
10:09:03  2020-09-18T17:08:34.106676Z	debug	envoy connection	[C28] handshake complete
10:09:03  2020-09-18T17:08:34.106709Z	debug	envoy client	[C28] connected
10:09:03  2020-09-18T17:08:34.106716Z	debug	envoy pool	[C28] attaching to next request
10:09:03  2020-09-18T17:08:34.106722Z	debug	envoy pool	[C28] creating stream
10:09:03  2020-09-18T17:08:34.106734Z	debug	envoy router	[C27][S2136150783590076220] pool ready
...
10:09:03  2020-09-18T17:08:50.683095Z	debug	envoy connection	[C28] 
10:09:03  2020-09-18T17:08:50.683120Z	debug	envoy connection	[C28] remote close
10:09:03  2020-09-18T17:08:50.683124Z	debug	envoy connection	[C28] closing socket: 0
10:09:03  2020-09-18T17:08:50.683182Z	debug	envoy connection	[C28] SSL shutdown: rc=0
10:09:03  2020-09-18T17:08:50.683194Z	debug	envoy connection	[C28] 
10:09:03  2020-09-18T17:08:50.683216Z	debug	envoy client	[C28] disconnect. resetting 1 pending request
10:09:03  2020-09-18T17:08:50.683228Z	debug	envoy client	[C28] request reset
10:09:03  2020-09-18T17:08:50.683240Z	debug	envoy router	[C27][S2136150783590076220] upstream reset: reset reason connection termination
```

**Comment by tariq1890** [comment]
Does Envoy enforce a 500ms timeout by default? The upstream service is known to take about 5000ms since this is a data upload.

When I look at the application logs, it does look like the request is received, but it eventually gets flooded with the same requests, because of envoy's retry policy and eventually returns a `503`

**Comment by tariq1890** [comment]
Would trace logs give us more info here? I usually shy away trace logs because it ends up emitting way too much info

**Comment by yanavlasov** [comment]
I does not look like Envoy's timeout, since it is the remote (from Envoy's perspective) end that closed the connection. Are you suggesting to enable trace logging on Envoy? I doubt it would yield more information. I think the key piece is why the remove end had closed the connection.

**Comment by tariq1890** [comment]
@yanavlasov We figured out the issue. It was caused by the Envoy proxy OOMing on the server's end. Looks like the server's envoy needed more memory to process the multipart request.

I don't claim to be any envoy expert, but what I don't get is that the client-side envoy faces no memory issues while trying to send this multi-part request. Isn't the volume of data received same as that of what is sent?

**Comment by yanavlasov** [comment]
Are both Envoys configured the same? Especially buffer sizes? If the buffers are too large it is possible that on Envoy quickly pushes too much data into its peer causing it to run out of memory.

**Comment by ingluife** [comment]
Hi guys.
Is there any solution here?
I have the same problem.
I'm uploading a long file (More than 120 Mb) and when the uploading process is 4% the connection is closed with the same message:

```
> Content-Type: multipart/form-data; boundary=------------------------0b46c37147adb82e
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 503
< content-length: 95
< content-type: text/plain
< date: Wed, 28 Oct 2020 00:33:32 GMT
< server: istio-envoy
* HTTP error before end of send, stop sending

upstream connect error or disconnect/reset before headers
```
Additional context:
It works when I upload a small file (less than 100 Gb).

Tested:
I tried to simulate the upload process from inside the POD, using `curl` and the same long file pointing directly to the Container where is running the API that makes the uploading process, and It works perfectly.

It does not work when I point to the Istio Gateway infrastructure.

Thanks!

**Comment by sp0cket** [comment]
Can we please reopen this? I have the same issue with https://github.com/istio/istio/issues/27373

**Comment by pranavelric** [comment]
When attempting to upload a file, I receive a `response_code_details : 'downstream_remote_disconnect`' and a `response_code: 0`. Does anyone know of any potential workarounds for this issue?

**Comment by alita-moore** [comment]
In my case the system appears to successfully upload the file and the consumer service receives the file, but then after 60 seconds the stream is terminated mid-stream.
