### ISSUE TITLE
Expose RandomGenerator via Api interface

### ISSUE THREAD

**Issue by akonradi** [envoyproxy/envoy#13243]
This is a feature request and, if approved, tracking issue for the necessary changes.

There are several components that make use of random values, which requires plumbing references to `Envoy::Random::RandomGenerator` down from the top level `Server` class to the consumer locations. In order to implement parts of #13110, references to RandomGenerator have to be made available further and further down, in lower-level classes. Instead of adding yet more dependency injection points, this issue proposes to make a RandomGenerator reference available via the `Envoy::Api::Api` interface. This is a simple refactor, except that there are enough usages that it should be done over several PRs.

/cc @htuch @antoniovicente @KBaichoo

**Comment by mattklein123** [comment]
+1 sgtm!

**Comment by htuch** [comment]
Yeah, I was +1 offline, API == platform, RandomGenerator is platform.
