### ISSUE TITLE
How to get Prometheus format for /cluster in administration interface

### ISSUE THREAD

**Issue by fengyinqiao** [envoyproxy/envoy#13249]
*Title*: ***Prometheus format for /cluster in administration interface***

*Description*:
>In administration interface,I can only get the metric format as below:
![](https://cdn.jsdelivr.net/gh/fengyinqiao/cloudimg/data/20200924114901.png)

>JSON format:
![](https://cdn.jsdelivr.net/gh/fengyinqiao/cloudimg/data/20200924115001.png)

>But I need the prometheus format,how can I deal with it?
PS:I know "/stats/prometheus" can provide the prometheus format.

[optional *Relevant Links*:]
>Other people met the same problem except me.
see https://github.com/envoyproxy/envoy/issues/12436

Looking forward to the reply!!! Thank you~

**Comment by dio** [comment]
> PS: I know "/stats/prometheus" can provide the prometheus format.

Sorry, I confused a bit. What is stopping you to use `/stats/prometheus`?

**Comment by fengyinqiao** [comment]
> > PS: I know "/stats/prometheus" can provide the prometheus format.
> 
> Sorry, I confused a bit. What is stopping you to use `/stats/prometheus`?

I want the metrics of prometheus format on each upstream host, these are in /clusters not in /stats/prometheus.

**Comment by dio** [comment]
Got it. So currently per upstream host stats is not included in `server_.stats()`, 

https://github.com/envoyproxy/envoy/blob/07f7c59a4e0a8892a2e2fc3443b2ae47ccb33ff2/source/server/admin/stats_handler.cc#L148

but rather "generated" on-the-fly by (for JSON)

https://github.com/envoyproxy/envoy/blob/07f7c59a4e0a8892a2e2fc3443b2ae47ccb33ff2/source/server/admin/clusters_handler.cc#L72 or (for text) https://github.com/envoyproxy/envoy/blob/07f7c59a4e0a8892a2e2fc3443b2ae47ccb33ff2/source/server/admin/clusters_handler.cc#L150

I think we need to consult this to @jmarantz. Should this be included in `server_.stats()` or we can extract the logic on getting per upstream host stats and append that to Prometheus output?

**Comment by jmarantz** [comment]
I am guessing that the cardinality of hosts is so large in some cases, that we don't want to include all of the individual host stats in the main stats output, but require stats clients to request them explicitly. This design predates my involvement and I'm not inclined to change it as it might break current stats clients by overwhelming them with data.

**Comment by dio** [comment]
@jmarantz Got it. So seems like from https://github.com/envoyproxy/envoy/issues/12436 the request is to have, for example: `/clusters/prometheus` or `/clusters?format=prometheus`. I think it makes sense, and as you said it is up to the client to decide.

**Comment by dio** [comment]
I'm not sure if this is a good practice to have two different endpoints for prom. Seeking for opinion: cc. @rumanzo @liamawhite @mandarjog

**Comment by jmarantz** [comment]
RE scale, there was a talk at KubeCon 2019 by Splunk about stats cardinality blowing through hundreds of gigs of memory in Prometheus ([slides](https://static.sched.com/hosted_files/kccncna19/2c/great_cardinality_disasters_of_our_time.pdf)) and the source of the stats explosion was Envoy (via Istio). So we need to be a little careful about silently and significantly expanding the cardinality of prometheus output.

**Comment by mattklein123** [comment]
Yeah I think we definitely do not want to output host stats by default due to cardinality issues. Somehow having an option to do this whether on a different endpoint or the same one seems ok.

**Comment by mandarjog** [comment]
Since /cluster has enumerated endpoints, it should surely not be by default.

I think we should add "format=Prometheus" to all /admin endpoints uniformly where it makes sense.

We have started scraping /memory endpoint recently in Istio.

**Comment by renanqts** [comment]
Did the request comes alive? I could not see any PR linked
