### ISSUE TITLE
Envoy Windows server code samples

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#13281]
*Description*:

I would like to start working on examples (sandboxes) that run on Windows Server Container instead of Alpine Linux. I already got one working but I would like to get more samples to give a good onboarding experience for Windows users.

I have the following questions:

1. Where should the examples be placed. Should we have a separate folder for Windows samples or share between the folders?
2. Do we want to start testing the examples on Windows? @sunjayBhatia 

The main issue that I encounter is that by definition the container setup is platform specific and it is hard to write platform agnostic code. One approach is to use [powershell core](https://github.com/powershell/powershell) for the samples which is open source and cross platform but I am not sure how familiar the community is.

Currently I have put the code on a [personal repository](https://github.com/davinci26/windows-envoy-samples)  to share it with you but I think the envoy project is better home for this code.

Let me know what you think!

**Comment by davinci26** [comment]
@envoyproxy/windows-dev

**Comment by sunjayBhatia** [comment]
Maybe we can use a single dockerfile with 2 different build stages? just be sure to only build the Linux stage on Linux and vice versa for Windows:
- https://docs.docker.com/develop/develop-images/multistage-build/
- https://docs.docker.com/compose/compose-file/#target

**Comment by davinci26** [comment]
> just be sure to only build the Linux stage on Linux and vice versa for Windows:

I think it is possible that someone might want to run the Linux samples on Windows. I think that should be possible although I haven't tried it out.

**Comment by phlax** [comment]
> I already got one working but I would like to get more

could you post a WIP PR with the working example? 

if we can review/update that one it could be a model for the rest

> I think it is possible that someone might want to run the Linux samples on Windows.

iiuc - yep - i think its likely

**Comment by sunjayBhatia** [comment]
> I think it is possible that someone might want to run the Linux samples on Windows. I think that should be possible although I haven't tried it out.

Yeah, I bet we will have to have 2 separate docker compose files

**Comment by davinci26** [comment]
> could you post a WIP PR with the working example?

I will get one rolling and we can iterate more there.

**Comment by sunjayBhatia** [comment]
> Maybe we can use a single dockerfile with 2 different build stages?

This doesn't work, docker build/compose is pretty dumb and tries to build all the stages even when you ask to run a specific one

**Comment by sunjayBhatia** [comment]
Trying this out again the more problematic issue is that many examples use images that are linux specific and we may have to build our own for Windows (mostly just echo servers and we could use node.js etc. - though there isn't a Windows docker image available from upstream, some 3rd party images are)
