### ISSUE TITLE
Support for per route "with_request_body" configuration for ext_authz

### ISSUE THREAD

**Issue by nickhiggs** [envoyproxy/envoy#13285]
*Title*: Support for per route "with_request_body" configuration for ext_authz

*Description*:
For the ext_authz extension we would like to be able to configure with_request_body for specific routes. Our use case is for enabling SAML from our ext_authz service which requires posting the SAML assertion in the body for authentication to a specific endpoint. We would like to be able to do this without the additional overhead of passing the body on every request other request.

**Comment by frasercobb** [comment]
Thank you for addressing this so quickly.

Could you help me understand the design decision to have a disable flag rather than setting "with_request_body" ?
I was originally thinking of using this feature to disable with request body by default, and enable it for a specific route.

Thanks again.

**Comment by dio** [comment]
@frasercobb yeah, I was about to have per route `with_request_body` but config wise it will be a bit complicated since we need to think of merging these two if both are enabled (global and per-route). And implementation wise this is easier. But yeah, of course, we can always revisit that.

**Comment by frasercobb** [comment]
@dio Thank you for the explanation, I would prefer a slightly clunky feature now rather than a perfect one later so your decision sits well with me. Thanks again.
