### ISSUE TITLE
[question]Does envoy support socket timeout ?

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#13290]
Like the connect_timeout in cluster,does envoy support socket timeout?Such as socket read timeout or socket write timeout?

**Comment by mattklein123** [comment]
Envoy supports many different types of timeouts. See here: https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts

**Comment by pyrl247** [comment]
I have seen this doc before,But it does not content the socket read timeout or socket write timeout.

**Comment by yanavlasov** [comment]
If you are referring to SO_RCVTIMEO or SO_SNDTIMEO values than Envoy is not using them, because it is not using blocking I/O.

**Comment by pyrl247** [comment]
@yanavlasov Maybe use libevent EV_TIMEOUT in file_event could work?

**Comment by yanavlasov** [comment]
I do not EV_TIMEOUT applies to to reading or writing from sockets. This is used to create time based event in libevent. Perhaps a better approach is for you to describe the problem you are trying to solve so someone can suggest a solution.

**Comment by pyrl247** [comment]
here is my circumstance, Such as thrift proxy , I want to set thrift request timeout in envoy. Surely I can set thrift request timeout in my downstream application code,but I want envoy can work with request timeout if the downstream forget.

**Comment by yanavlasov** [comment]
This is something that may need to be implemented in the thrift extension if it does not exist already. Adding @zuercher @rgs1  as owners.

**Comment by rgs1** [comment]
cc: @fishcakez
