### ISSUE TITLE
udp dns filter: re-use underlying dns resolver

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#13321]
udp dns filter: re-use underlying dns resolver

*Description*:
Currently the UDP DNS filter creates a new DnsResolver instance on DnsFilter creation (wrapped around a `DnsFilterResolver`). All DnsFilterResolverr should reuse the same underlying DnsResolver for efficiency gains. Further changes to resolver creation via Event::Dispatcher::createDnsResolver need to be able to throw an exception, which is not safe during Filter instance construction but would be during config construction.

**Comment by junr03** [comment]
@abaptiste is this something you could pick up?

**Comment by abaptiste** [comment]
@junr03 Sure, let me take a look

**Comment by abaptiste** [comment]
With the changes for this, I'm seeing an assertion failure in the dispatchers due to thread ID mismatches.

```
[assert] [source/common/event/dispatcher_impl.cc:152] assert failure: isThreadSafe().
[backtrace] [bazel-out/.../backtrace.h:104] Caught Aborted, suspect faulting address 0xc
[backtrace] [bazel-out/.../backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[backtrace] [bazel-out/.../backtrace.h:92] Envoy version: 0/1.16.0-dev/test/DEBUG/BoringSSL
[backtrace] [bazel-out/.../backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x201210c] source/common/signal/signal_action.cc:20
[backtrace] [bazel-out/.../backtrace.h:96] #1: __restore_rt [0x7f96799b68a0] ??:0
[backtrace] [bazel-out/.../backtrace.h:96] #2: Envoy::Network::DnsResolverImpl::onAresSocketStateChange() [0x1b5d5ea] source/common/network/dns_impl.cc:223
[backtrace] [bazel-out/.../backtrace.h:96] #3: Envoy::Network::DnsResolverImpl::initializeChannel()::$_1::operator()() [0x1b5db5f] source/common/network/dns_impl.cc:77
[backtrace] [bazel-out/.../backtrace.h:96] #4: Envoy::Network::DnsResolverImpl::initializeChannel()::$_1::__invoke() [0x1b5db28] source/common/network/dns_impl.cc:75
[backtrace] [bazel-out/.../backtrace.h:96] #5: open_udp_socket [0x1b6fc2c] /root/.cache/bazel/_bazel_root/37e3aec351bcd85a6ea8b58e3592ef6e/sandbox/linux-sandbox/1525/execroot/envoy/external/com_github_c_ares_c_ares/ares_process.c:1244
[backtrace] [bazel-out/.../backtrace.h:96] #6: ares__send_query [0x1b6f073] /root/.cache/bazel/_bazel_root/37e3aec351bcd85a6ea8b58e3592ef6e/sandbox/linux-sandbox/1525/execroot/envoy/external/com_github_c_ares_c_ares/ares_process.c:860
```

The identified line in dns_impl.cc is calling `dispatcher_.createFileEvent` which is the function containing the assertion.

This is happening for one integration test where I have to setup two DNS Filters on separate listeners to exercise the external lookup logic.

That said, I get the same failed assertion at a different point in the filter if I move both the `DnsFilterResolver` and `DnsResolver` into the filter's config construction.

Am I missing something with the use of dispatchers in the filter?

**Comment by mattklein123** [comment]
The issue is the UDP filter is per-listener, so you need per-worker DNS resolvers. I don't think it's going to be easy to always check everything inline.

@junr03 I think the correct solution to your cleanup is you need a common config verification function for DNS resolvers that is always called on config load on the main thread, such that we guarantee there is no issue if/when a resolver is created on a worker?

**Comment by junr03** [comment]
@mattklein123 I guess there are two points I confounded into one issue:
- It seemed, at first glance that the filter was creating more DnsResolver instances than strictly necessary, instead of sharing.
- Creation of the DnsResolver was happening outside of config handling. 
I agree that a way to solve the second point is what you suggest, and would mean that no work needs to happen in the UDP filter.

I hadn't looked into the implementation of the DnsFilterResolver, but I was imagining a similar setup to the DnsCache were the DnsFilterResolver would take resolution requests cross-thread and move execution of calls of the DnsResolver back onto the main thread. However, if you (and @abaptiste) think that is not feasible or desired here, I can close out this issue; and open one to solely tackle the config verification in the way that you suggest, not having to touch the UDP filter at all.

**Comment by mattklein123** [comment]
> However, if you (and @abaptiste) think that is not feasible or desired here, I can close out this issue; and open one to solely tackle the config verification in the way that you suggest, not having to touch the UDP filter at all.

Yeah I would recommend not doing that for this filter for performance/complexity reasons.

**Comment by abaptiste** [comment]
Is the goal to minimize the number of resolvers being created throughout envoy?

**Comment by mattklein123** [comment]
> Is the goal to minimize the number of resolvers being created throughout envoy?

The goal is to make sure we check all of the config options on the main thread / during config load and prior to data plane operation. Per above though I think this is not the right solution so I'm going to close this issue. @junr03 can you please make sure to track the config check fix in some other issue?

**Comment by junr03** [comment]
> Is the goal to minimize the number of resolvers being created throughout envoy?

Yes, @abaptiste per our conversation in slack that would be the goal with the threading setup I proposed above. However, per @mattklein123 the investment is not worth the complexity.

re: the primary goal of DNS config validation, it can now be tracked here: https://github.com/envoyproxy/envoy/issues/13512
