### ISSUE TITLE
Windows: List of APIs/features disabled or with degraded functionality on Windows

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#13322]
To set expectations about Windows support through the release phases (Alpha evaluation, GA, etc.), we should document the currently disabled or degraded features on Windows

For now this list includes (non-exhaustive):
- Tracing extensions are disabled
- ~~Signal handling/process lifecycle control is disabled~~
- Hot restart is disabled
- ~~Per-request RTT latency metrics https://github.com/envoyproxy/envoy/issues/12305~~
- As of https://github.com/envoyproxy/envoy/pull/12546 WASM has been added and disabled on Windows
- Worker thread signalling (guarddog/watchdog) is not implemented

Please add comments for additional APIs/features that should be mentioned and we will get them added to the list.

This could instead be a document in the Envoy source tree, or a GitHub issue tag instead to allow us easier iteration/addition if the maintainers think it is more appropriate.

**Comment by sunjayBhatia** [comment]
cc @envoyproxy/windows-dev

**Comment by sunjayBhatia** [comment]
@mattklein123 do you think this is appropriate for the help wanted tag?

**Comment by mattklein123** [comment]
Sure!

**Comment by wrowe** [comment]
This is part of the #13190 roll-up issue

**Comment by wrowe** [comment]
Note specifically issue 13596 for CA path spec differences between windows and linux

**Comment by wrowe** [comment]
Note specifically issue 13964 for differences between /dev/null vs. NUL, missing /dev/ devices stdout, stderr, tty, console

**Comment by wrowe** [comment]
@sunjayBhatia was #15298 sufficient?

**Comment by sunjayBhatia** [comment]
Yeah I think we could close this since we have documentation for the various things that are disabled and have plans to have some automated generation around those docs

**Comment by davinci26** [comment]
Closing based on the discussion in the windows-dev group and the comment above.
