### ISSUE TITLE
Ability to route match based on one or more headers

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy#13330]
Hi,

I know we can route based on a single header field, is it possible to route based on say either header-X or header-Y

`{
                          "match": {
                            "prefix": "/"
                          },
                          "route": {
                            "cluster_header": "header-X"
                          }
                        }`

**Comment by mattklein123** [comment]
No it's not currently possible to do this kind of compound matching, however we are starting to look at what a new route config with a more extensible matching system might look like that would support something like this. cc @snowp
