### ISSUE TITLE
[http] Setting a threshold value for lazy headermap

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#13333]
PR #12656 introduces a new configuration parameter, _envoy.http.headermap.lazy_map_min_size_, that sets the threshold value for the lazy headermap - the number of headers in the headermap after which the headermap will use an underlying dictionary to map the headers. The threshold default value is infinity at the moment, which keeps the same behavior as before this PR.

This issue is for tracking what the default parameter value should be.
Preliminary benchmarks have shown (see PR #12656) that a threshold value of 3 presents good results for many scenarios. Before settling on a default value other than infinity, users of Envoy are encouraged to try different values for this parameter and share the findings for their scenarios with the community.

**Comment by mattklein123** [comment]
@adisuissa I wanted to ping back on this. Is this something we can lock in a default for at this point?
