### ISSUE TITLE
Allow interpreting variables in initial_metadata for a ext_authz grpc service

### ISSUE THREAD

**Issue by brectanus-sigsci** [envoyproxy/envoy#13345]
*Description*:
>Variable interpretation is now allowed for HTTP based ext_authz `headers_to_add` (see #7946), but there seems to be no way to do something similar with gRPC ext_authz services. The gRPC version has an `initial_metadata` field (see: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/grpc_service.proto#envoy-api-msg-core-grpcservice) that seems like it could work similarly, but it does not support variable interpretation. 
>
> I'd like to do something like the following in order to include more info on the downstream connection for auth:
>```
>           - name: envoy.ext_authz
>             config:
>               grpc_service:
>                 envoy_grpc:
>                   cluster_name: my-cluster-grpc
>                 timeout: 0.2s
>                 initial_metadata:
>                 - key: "x-downstream-tls-cipher"
>                   value: "%DOWNSTREAM_TLS_CIPHER%"
>                 - key: "x-downstream-tls-version"
>                   value: "%DOWNSTREAM_TLS_VERSION%"
> ```
>
> There are also probably similar needs in other filters, such as `envoy.rate_limit` also noted in #7946 

cc @dio

**Comment by chengdol** [comment]
I wonder how can I use these data carried by `initial_metadata` from the `network.ext_authz` external auth grpc server. 

From my experiment, these key-value pairs did not show up in the CheckRequest object which is super confused against the description: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice
