### ISSUE TITLE
Symlink-atomic reads for private key/certificate pairs

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#13370]
In https://github.com/envoyproxy/envoy/pull/10163, support is added to load both private key and certificate on an inotify event. However, this is not fully atomic w.r.t. symlink changes. Imagine you have foo/ pointing at bar/ containing `key.pem` and `cert.pem`. Then you relink `foo/` to point at `baz/` with `key.pem` and `cert.pem` during a rotation. In our current solution, there is a race, where `key.pem` might be read from `bar/` and `cert.pem` from `baz/` during the relink. 

We need to fully resolve a symlink with `readlink` before reading the key/cert pair.

I think this might actually also affect runtime snapshots; is this true @mattklein123?

CC @tsaarni @lizan

**Comment by mattklein123** [comment]
> I think this might actually also affect runtime snapshots; is this true @mattklein123?

I don't believe so. This is why there is a level of indirection for the symlink and the snapshot directory. It reads the entire new directory at once after the swap. I think we would need to do something similar for the cert case where we introduce a base directory and do the swap there.

**Comment by htuch** [comment]
Yes, this makes sense. We can also just use `readlink` to resolve to the real directory and then read individual files, so we don't need to force that structure.

**Comment by mattklein123** [comment]
Yeah if we assume that the parent directory is consistent, readlink would work also agreed.

**Comment by tsaarni** [comment]
Adding `readlink` for atomic reads sounds good solution to me as well.

Is it a scenario where a new TLS connection happens to be established right at the moment of the rotation?  I guess in theory there is yet another, but probably less likely race: at the end of the rotation the when old certificate & key files get removed, the old resolved path could cause open to fail.

**Comment by markdroth** [comment]
FYI, gRPC is going to support this without depending on `readlink(2)`, for two reasons:

1. `readlink(2)` isn't portable, and we didn't want to have to provide a separate solution for Windows.
2. We didn't want to force people to use a symlink in cases where it might not be necessary.  For example, it's actually fully possible to do this swap safely without a symlink by creating a new directory with new files and then renaming the directories to swap the new one into place.  And there may be cases where the certs aren't actually ever going to change, in which case the symlink is unnecessary.

So gRPC is going to handle this by having a file-watcher CertificateProvider whose config will indicate the directory containing the cert and key files and the filenames within that directory of the two files.  The provider will check the timestamps of both the directory and the files, then read the files, then check the timestamps again.  If the "before" and "after" timestamps don't match, then it will assume that it did not get a safe atomic read, so it will throw away the result and try again.

There are some edge cases where it is possible to get a non-atomic read with this approach, but they are exceedingly rare (e.g., if the system clock gets set backward by exactly the time difference between when the old and new files were written, or if the files' timestamps are explicitly set to the same values), so we're not really worried about them.

**Comment by htuch** [comment]
Interesting. A few questions / comments:
* The current design doesn't require a symlink, or even `readlink` really, just some form of path canonicalization.
* How do you know there has been an update in gRPC? Are you still using inotify?
* Why not hash? We're actually hash already in the watcher, so we could do a hash based scheme similar to what you describe that is even more robust and doesn't rely on timestamps.

I think there's actually three orthogonal things to figure out here:
1. How do we build an API to be more explicit about what we're watching. Currently, it's very implicit and assumes just looking at parent directory based on path decomposition.
2. How are watches performed? I think this is inherently platform specific, Envoy already supports watching on various platforms.
3. How do we deal with atomicity? #13721 uses `readlink`/`realpath` (alternative), but we could also reasonably read the files twice and look at hashes after two successive reads.

The `WatchedDirectory` API is largely about (1) in #13721. It aims to strike a balance in terms of supporting backwards compatibility with `DataSource` and providing control. I'd be open to other suggestions if the ergonomics are better.

I think (3) can be dealt with independently as an implementation detail. I'm good with switching to hashes if folks prefer.

**Comment by markdroth** [comment]
Initially, we are not planning to use inotify, although we might switch to it later, once we've finished migrating to EventManager-based polling.  For now, we're planning to do a polling-based approach where we check for changes periodically via a timer.

Reading the files twice and comparing the hashes of their contents could work as an alternative to using timestamps.  But it does seem like a more heavy-weight approach, since filesystem access can actually be a bottleneck on really busy systems.

**Comment by htuch** [comment]
I'm not sure if this filesystem access is a real bottleneck here given that rotations are relatively rare, the files are tiny and in may cases only live in a tmpfs or other virtual filesystem. But yeah, timestamps can work at the expense of risking some corner cases (e.g. if last modified timestamp is coarse grained, two files might be last modified at the same time).

I think I'll give this hash-scheme a shot, since it will simplify Windows compatibility.

**Comment by tsaarni** [comment]
Just to double check since I'm not familiar with the total picture: are all the files related to a secret `read()` to memory during the watch callback?  I ask since of course hashing before and after could only catch changes during callback.

**Comment by htuch** [comment]
Right now, we pass both contents read and path to the update callbacks. However, we can read files into memory and pass a pseudo-`DataSource` with the contents "inlined". This ensures that any consumer of the `DataSource` does not look at the filesystem outside of `sds_api.cc`.
