### ISSUE TITLE
Envoy service proxy processes HTTP 1.1 requests with increasing delay on a persistent connection

### ISSUE THREAD

**Issue by amukherj1** [envoyproxy/envoy#13376]
*Title*: *Envoy service proxy processes HTTP 1.1 requests with increasing delay on a persistent connection*

*Description*:
> I have a custom HTTP application which supports sending multiple HTTP1.1-wrapped RPC calls (using protobufs) from a client to a server on a persistent TCP connection. These are on different hosts and I have put an Envoy sidecar on each for egress and ingress, handling TLS and mTLS auth.
> 
> I can see that the caller service dispatches the requests to Envoy immediately but they show up in Envoy's log with an increasing delay (varying between several seconds to several minutes). The communication between the Envoys doesn't show increasing latency. I suspect this could be because we open a persistent TCP connection and then send successive HTTP requests to the egress Envoy, but the egress Envoy might be waiting for the response of each request before dispatching the next - in other words serializing the requests.
> If yes, Is there a way to support such configurations, or should we switch to an HTTP2 client?
> If no, what could be the problem?

Version of Envoy: 1.12.2

[optional *Relevant Links*:]
>Envoy log snippet (from the egress proxy.

```[2020-10-01 22:52:25.081][2019][debug][http] [source/common/http/conn_manager_impl.cc:259] [C69950] new stream

[2020-10-01 22:52:25.081][2019][debug][http] [source/common/http/conn_manager_impl.cc:708] [C69950][S2904751784239169371] request headers complete (end_stream=false):
':authority', 'www'
':path', '/foo/bar.RpcSvc/'
':method', 'POST'
'content-type', 'application/x-myrpc'
'content-length', '446'
'some-unique-id', '1097097667177086992'
'x-foo-envoy-clus', 'remote1'

[2020-10-01 22:52:25.081][2019][debug][lua] [source/extensions/filters/common/lua/lua.cc:37] coroutine finished

[2020-10-01 22:52:25.081][2019][debug][router] [source/common/router/router.cc:549] [C69950][S2904751784239169371] router decoding headers:
':authority', 'www'
':path', '/foo/bar.RpcSvc/'
':method', 'POST'
':scheme', 'https'
'content-type', 'application/x-myrpc'
'content-length', '446'
'some-unique-id', '1097097667177086992'
'x-foo-envoy-clus', 'remote1'
'x-forwarded-for', 'myip'
'x-forwarded-proto', 'http'
'x-envoy-internal', 'true'
'x-request-id', '198df9bd-45d0-43f6-aff2-3f1d2bbe9efc'
'x-hop-count', '1'

[2020-10-01 22:52:25.081][2019][debug][router] [source/common/router/router.cc:1618] [C69950][S2904751784239169371] pool ready

[2020-10-01 22:52:25.081][2019][debug][http] [source/common/http/conn_manager_impl.cc:1257] [C69950][S2904751784239169371] request end stream

[2020-10-01 22:52:25.084][2019][debug][router] [source/common/router/router.cc:1036] [C69950][S2904751784239169371] upstream headers complete: end_stream=false

[2020-10-01 22:52:25.084][2019][debug][http] [source/common/http/conn_manager_impl.cc:1552] [C69950][S2904751784239169371] encoding headers via codec (end_stream=false):
':status', '200'
'reorder-request', '1097097667177086992'
'content-length', '71'
'x-envoy-upstream-service-time', '2'
'date', 'Thu, 01 Oct 2020 22:52:24 GMT'
'server', 'envoy'
```

The corresponding tcpdump record indicating that the request hit the network as soon as it was sent from the caller and wasn't queued at the caller's end.

```
22:52:07.870293 IP (tos 0x0, ttl 64, id 24011, offset 0, flags [DF], proto TCP (6), length 700) localhost.58624 > localhost.8331: Flags [P.], cksum 0x00b1 (incorrect -> 0xfecd), seq 7978:8638, ack 369, win 128, length 660
E...].@.@..n..........$.Eq.....<P.......POST /foo/bar.RpcSvc/ HTTP/1.1
Content-Type: application/x-myrpc
Content-Length: 446 
Host: www
Some-Unique-Id: 1097097667177086992
X-foo-envoy-clus: remote1
```

**Comment by mattklein123** [comment]
This version is very old. Please try with latest and report back.

**Comment by amukherj1** [comment]
> This version is very old. Please try with latest and report back.

I will try to. Just for my understanding, does this seem like some known issue with older versions?

**Comment by mattklein123** [comment]
There have been many changes that might effect those over the last year, hard to say.

**Comment by lipingtababa** [comment]
Hi @amukherj1 We have almost the identical problem. The communications between our envoy ingress sidecar and the AWS  LB are okay, but we from time to time experience delays between the ingress sidecar and the service container.
The tcpdump files show that the service sends out the IP packets in time, but the envoy/sidecar doesn't process it until 1-10s later.
And it happens when the traffic, CPU utilization and everything else looks fine.
Another interesting thing to note is that it happens to one request per time, never in bulk.

We are going to upgrade our version from 1.10.0 to 1.14.3 and will share our results here.

**Comment by amukherj1** [comment]
The behavior seems to be the same with Envoy 1.15. I will try to put the test code (Golang) and config in a repo and share it here soon.

**Comment by lambdai** [comment]
I remember elder envoy didn't support http pipelining in http1. 
When envoy is not done with the current response, the early next request bytes delivered to envoy. 
These new bytes is not lost but the dispatcher lost the notification.

Somehow the dispatcher may be notified by unrelated events or timer.

Your minutes of delay fit this pattern. And you should be able to confirm if your requests form the http pipeline case with a tcpdump running at envoy server side.
