### ISSUE TITLE
sandbox: TLS sandbox

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#13373]
Users are frequently confused on TLS configuration. We should have a sandbox that demonstrates both downstream and upstream TLS configuration. We could have the sandbox potentially generate self signed certs similar to what we do in the integration tests: https://github.com/envoyproxy/envoy/blob/master/test/config/integration/certs/certs.sh

**Comment by mattklein123** [comment]
cc @phlax this would be a good one to add to your list.

**Comment by phlax** [comment]
yep @mattklein123 im definitely happy to take this one

**Comment by phlax** [comment]
checking through for prior art, im seeing the `front-proxy` example has an existing `tls` example:

https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/front-envoy.yaml#L63

this should be quite useful for getting started

**Comment by phlax** [comment]
some possibly relevant refs:
- #12965 
- #13221 
- #12586 
- #9577

**Comment by mattklein123** [comment]
@phlax good point regarding that example. I would say we should do 2 things:
1) Rename it "TLS front proxy" or something like that
2) Also demonstrate TLS upstream connections

WDYT?

**Comment by phlax** [comment]
yep, re upstream connections

i think lets knock out the tutorial first (#13386) which also has some tls examples, and then i can collate the info into a tls sandbox, and we can figure out what it needs to demonstrate

**Comment by phlax** [comment]
> Rename it "TLS front proxy" or something like that

i need to check through a  bit more, but i think the front-proxy example is useful even without the  tls bits - i would be more tempted to just separate out the tls to its own example (or maybe even just leave it, and add a tls focused example)

**Comment by mattklein123** [comment]
>  i would be more tempted to just separate out the tls to its own example (or maybe even just leave it, and add a tls focused example)

Sure sgtm

**Comment by chintan-mishra** [comment]
@phlax , I noticed that you referred #13321.

I want to point out that in the referenced issue the `envoy` user within the container can read the TLS certificates but Envoy binary cannot read the certificates provided in `envoy.yaml`.

The `envoy.yaml` configuration attached in the referenced issue works fine with v1.14.4.

**Comment by phlax** [comment]
@chintan-mishra thanks for info.

I tagged it because i figured i might be able to look at that bug when following up on adding an example - might be beyond my immediate capabilities tho
