### ISSUE TITLE
Aggregated Discovery Service (ADS) support in v2 Subscriptions

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1338]
We'll need to add the notion of a shared ADS resource to `ConfigSource` handling and `SubscriptionFactory`, add an ADS variant of `Subscription` and implement appropriate muxing to provide ADS semantics. See https://github.com/lyft/envoy-api/pull/124.

**Comment by htuch** [comment]
Some notes:

* Need to ensure ordering is CDS/EDS then LDS/RDS to ensure dependencies are in place when updating routes.
* EDS and RDS should coalesce the requested resources and only issues on request for each CDS/RDS update.

**Comment by mattklein123** [comment]
This is done. Closing.
