### ISSUE TITLE
502 on our ALB when traffic rate drops

### ISSUE THREAD

**Issue by softcane** [envoyproxy/envoy#13388]
*Title*: *502 on our ALB when traffic rate drops*
Envoy version: 1.14.1

**Issue**
We observer 502 error codes on our AWS ALB when traffic rate drops in during off-hours.
![image (1)](https://user-images.githubusercontent.com/1730359/95026126-59b42400-068f-11eb-9e75-b788c040c305.png)

**Background:**
We are migrating our ingress controller from Nginx to Istio ingress gateway. We are running ingress proxy on NodePort behind ALB in AWS. Kube proxy is running in the IPtable mode and externalTrafficPolicy is configured to Cluster.

During the load test (40K/sec), we figured out that requests are not evenly distributed between the ingress pods and Deployment/Scaling skew the thing even further.

**Problem:**
Kube-proxy has very Poor support for keepalive connections if it runs in the "Iptable" mode. In "Iptable" mode, kube-proxy use a compound probability to pick up a pod IP during routing. Problem is, these rules were invocated only the first time when it opens the TCP connection and since then all subsequent requests are channelled through the same TCP connection (POD).

**_Why it was not an issue in the Ngnix?_**

keepalive_timeout  75s;
keepalive_requests 100;
http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests

Sets the maximum number of requests that can be served through one keep-alive connection. After the maximum number of requests are made, the connection is closed.
Closing connections periodically is necessary to free per-connection memory allocations. Therefore, using the too high maximum number of requests could result in excessive memory usage and not recommended.
As the istio-proxy works at layer 7, it does request-load-balancing on persistent connections for in/outbound connections between pods in the cluster. Connections are not recycled periodically since the envoy can handle large bursts of requests with a very small footprint.

**Before/After the patch**
![1](https://user-images.githubusercontent.com/1730359/93028468-791ddb00-f614-11ea-8986-b974ea93f0f1.png)
![3](https://user-images.githubusercontent.com/1730359/93028469-79b67180-f614-11ea-8dd7-5a6467141288.png)

*Config*:
```
common_http_protocol_options:
            max_connection_duration: 75s
```

**Comment by mattklein123** [comment]
Sorry what is this issue tracking? Are you saying you fixed your problem with the max connection duration config?

**Comment by softcane** [comment]
Adding ‘max_connection_duration’ fixes the uneven connection distribution issues but now I’m getting few 502 errors on the ALB.

**Comment by mattklein123** [comment]
Fundamentally, the problem is that ALB is reusing connections that Envoy is closing. This is an inherent race condition with HTTP/1.1. You need to configure the ALB max connection / idle timeout to be < any envoy timeout.

**Comment by softcane** [comment]
Thanks,
ALB idle timeout is 60 sec which is less than max_connection_duration (75sec)

Idl_timeout on envoy proxy is default one hour.

When you say any timeout you mean beside the one that I mentioned here?

**Comment by mattklein123** [comment]
To have no race conditions, the ALB needs to support max_connection_duration and have that be less than Envoy's max connection duration. There is no way to fix this with Envoy.

**Comment by softcane** [comment]
Same ALB is used to serve traffic to Nginx ingress pods on a separate node port and we donor have such issue there 

Nginx conf
keepalive_timeout 75s;
keepalive_requests 100;

**Comment by mattklein123** [comment]
keepalive_timeout is different from max_connection_duration. If you don't configure max_connection_duration and just reduce Envoy's idle_timeout that might work. I can't remember if we have a max requests limit for downstream. I don't think so.

**Comment by softcane** [comment]
I think kube-proxy will not balance the traffic if I don't set `max_connection_duration`. Terminating connection periodically allowing kube-proxy to reevaluate its iptable rules and hence balance the traffic.

Isn't the higher Idle_timout on the envoy proxy (1hour) than ALB (60sec) is better in the sense that ALB can close the idle connection before the envoy?

**Comment by mattklein123** [comment]
> Isn't the higher Idle_timout on the envoy proxy (1hour) than ALB (60sec) is better in the sense that ALB can close the idle connection before the envoy?

Yes, but you are also using max_connection_duration which is independent and thus there is a race condition. If ALB supported HTTP/2 you could use that. Without that there is no fix here without any code changes. If we supported max_requests for downstream connection that would also "fix" the issue, but IIRC we don't support that.

**Comment by softcane** [comment]
Do you see any possibility to add a support for   max_requests_connection in the downstream connection?

**Comment by mattklein123** [comment]
> Do you see any possibility to add a support for max_requests_connection in the downstream connection?

It's a reasonable feature request so feel free to open an issue on that and we can mark it help wanted.

**Comment by softcane** [comment]
Great, thanks for all the help so far.
