### ISSUE TITLE
Doc update: "life of a request"

### ISSUE THREAD

**Issue by cgthayer** [envoyproxy/envoy#13397]
*Title*: Doc update: "life of a request"

*Description*:

* Reading the STYLE doc https://github.com/envoyproxy/envoy/blob/master/STYLE.md
* Has a link to "Life of a Request" which is 404
* Should go to https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/life_of_a_request.rst
* Also that fie has broken images, so the links there need to be updated.

**Comment by phlax** [comment]
thanks @cgthayer unless you/someone prs first i can look at that as part of #13386

**Comment by htuch** [comment]
You should not link directly to the RST, but instead to https://www.envoyproxy.io/docs/envoy/latest/intro/life_of_a_request
