### ISSUE TITLE
stats: Remove --use-fake-symbol-tables option.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#13399]
See also https://github.com/envoyproxy/envoy/issues/6307 which removes the code supporting fake symbol tables, but leaves the option in place.

Removing the option is a breaking change, so splitting that off on its own.

**Comment by mk46** [comment]
Hi @jmarantz, I would like to take it if you're not working on it.

**Comment by jmarantz** [comment]
You are welcome to take it; I expect it will be pretty easy and I can review. However, I think it would be better to wait a bit, because removing an option can break production setups, potentially. @mattklein123 when do you think would be appropriate? Maybe 1-2 weeks prior to the cut-date for 1.17?

**Comment by mattklein123** [comment]
If the code was removed in the last release IMO it can be removed any time during this cycle so fine to do it now.
