### ISSUE TITLE
subset lb: small subsets hit panic threshold while being populated/depopulated

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#13429]
Currently, `healthy_panic_threshold` defaults to 50% and is applied to the whole cluster:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/cluster/v3/cluster.proto#L517

We use the subset LB to move traffic across versions [0], so during a deploy a subset (internally represented as a host
set) can grow from zero to a few hosts for a new version and then the other way around for an old version.

While the subset is being populated -- or being emptied -- we see spikes of `lb_healthy_panic`. This of course
leads to SR drops. 

There are a few potential workarounds or solution for this issue:

1) we tried `ignore_new_hosts_until_first_hc`, but it didn't help

2) we could introduce a new knob to override `healthy_panic_threshold` for host sets that have less than N hosts, e.g.: `healthy_panic_threshold_min_hosts` 

3) we could make the above knob be subset lb specific, and be configurable per subset perhaps

Thoughts?

cc: @fishcakez @mattklein123 @zuercher @snowp  

[0] https://medium.com/pinterest-engineering/simplifying-web-deploys-19244fe13737

**Comment by snowp** [comment]
Doesn't the subset refresh happen within a single event on the dispatcher? How is load balancing happening during the subset update?
