### ISSUE TITLE
Question: How might I output the version of protoc and libprotobuf used during an Envoy build?

### ISSUE THREAD

**Issue by hq6** [envoyproxy/envoy#13421]
Is there a flag that one can pass to the bazel command, or a configuration file one can modify, to force the build to output the following information?
1. The version of protoc used to compile protobufs in Envoy extensions (filters).
2. The version of protobuf that Envoy is linked against.
3. The version of grpc that Envoy is linked against.
4. Whether Envoy links statically or dynamically against the above libraries.

If there's a way to infer from this by examining build files, that would also be greatly appreciated.

**Comment by snowp** [comment]
You can see what versions Envoy builds against in bazel/repository_locations.bzl. Basically everything is statically linked in Envoy (sans glibc etc)

**Comment by hq6** [comment]
Does Envoy build protoc from source, or uses a pre-built binary from that package?

The documentation [here](https://github.com/protocolbuffers/protobuf) seems to imply that the C++ protoc is intended to be built from source, but I'm not sure how to tell whether that is what Envoy's build does.
