### ISSUE TITLE
Customize 'RBAC: access denied' message

### ISSUE THREAD

**Issue by arief-hidayat** [envoyproxy/envoy#13437]
*Title*: *Customize `RBAC: access denied` message*

*Description*:
I am using istio CRs to configure authn & authz policy. 

Access without valid & authorized token gets 403 with `RBAC: access denied` in the response body.

Is there a way to customize this response body? e.g. I would like to send json message instead.

thanks 

[optional *Relevant Links*:]
I see this value is hardcoded here.
https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/rbac/rbac_filter.cc#L118

**Comment by snowp** [comment]
You should be able to use https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply to modify the response by filtering on the response and rewriting it into the format that you want.

**Comment by arief-hidayat** [comment]
thanks. I will try that

**Comment by ldemailly** [comment]
current loc is 
https://github.com/envoyproxy/envoy/blob/v1.25.0/source/extensions/filters/http/rbac/rbac_filter.cc#L159

it does seem it would be nice to be able to simply put a custom message in each RequestAuthentication or AuthorizationPolicy
