### ISSUE TITLE
How to configure Envoy to pass the absolute URL to the upstream service?

### ISSUE THREAD

**Issue by sushil-prasad** [envoyproxy/envoy#13435]
I want to set up Envoy in front of a Squid caching proxy that accepts absolute URLs. For example, when  “GET https://www.google.com” is sent to Squid, it returns with 200 OK. 

When Envoy is set up in front of Squid, the absolute URL gets parsed before sending to the upstream server. For example, the URL 'https://www.google.com' is sent as '/' and not as 'https://www.google.com'.

Any recommendations on how to set up Envoy in front of the Squid caching proxy which accepts the absolute URL?

Test Setup
-----------
Client --> Envoy --> Squid -->  Internet

Request to squid directly 
-------------------------

Client ==> Squid
	GET https://www.google.com HTTP/1.1

Client <== Squid
	HTTP/1.1 200 OK

Request via Envoy when "http_protocol_options.allow_absolute_url: false"
--------------------------------------------------------------------------
Client ==> Envoy
	GET https://www.google.com HTTP/1.1

Client <== Envoy
	HTTP/1.1 400 Bad Request

Request via Envoy when "http_protocol_options.allow_absolute_url: true"
-------------------------------------------------------------------------
Client ==> Envoy
	GET https://www.google.com HTTP/1.1

Envoy ==> Squid
	GET / HTTP/1.1
	host: www.google.com
	x-forwarded-for: 192.168.1.181
	x-forwarded-proto: http
	x-envoy-internal: true
	x-request-id: aba6cc5e-5fe8-4613-8828-cede14874660
	x-envoy-expected-rq-timeout-ms: 30000
	content-length: 0

Envoy <== Squid
	HTTP/1.1 400 Bad Request
	X-Squid-Error: ERR_INVALID_URL 0

Client <== Envoy 
	HTTP/1.1 400 Bad Request
	x-squid-error: ERR_INVALID_URL 0

**Comment by snowp** [comment]
@alyssawilk Do you know if we allow configuring this behavior?

**Comment by alyssawilk** [comment]
Yeah, I don't think Envoy supports forwarding absolute URLs, and if we did there'd probably be some extra work to not forward it as GET http://www.google.com/ because of the way it is represented internally.

**Comment by nmeessen** [comment]
In case anyone bumps into this, I managed to work around the issue with Lua and make Envoy forward to squid for both "CONNECT" and non-CONNECT using absolute URLs (in my case that's for non-TLS traffic)
`static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0 
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: passthrough_outboundproxy 
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: outbound_proxy 
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    disabled: true
              - match:
                  prefix: "http://"
                route:
                  cluster: outbound_proxy
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:headers():replace(":path", "http://"..request_handle:headers():get(":authority")..request_handle:headers():get(":path"))
                end
          - name: envoy.filters.http.router
          http_protocol_options:
            allow_absolute_url: true
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT

  clusters:
  - name: outbound_proxy 
    type: LOGICAL_DNS
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
    load_assignment:
      cluster_name: outbound_proxy 
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <my-corporate-egress-proxy>
                port_value: 8080
`
