### ISSUE TITLE
Ability to configure zone aware load balancing settings as config settings

### ISSUE THREAD

**Issue by liamawhite** [envoyproxy/envoy#1344]
We are trying to enable AZ aware routing in Istio, which we have done but its currently only for the defaults of 100% and >= 6 upstream clusters. We would like to be able to configure `upstream.zone_routing.enabled` and `upstream.zone_routing.min_cluster_size` as config options instead of runtime options in order to utilise the AZ aware routing properly.

cc @rshriram

**Comment by mattklein123** [comment]
Should be simple change. PRs welcome.

**Comment by srikailash** [comment]
Hello @mattklein123  , I am interested to work on this issue . After going through code i found that , configuration call for min cluster size can be made here https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/load_balancer_impl.cc#L245 , but question is which configuration file in (envoy/source/common/config/ ) can be used to add this . Thanks in advance .

**Comment by mattklein123** [comment]
Hi, thanks for offering to work on this. 

You will want to add the configuration to the cluster object here:
https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/cds.proto#L40

Once that is done, you can thread the configuration out of that and into LB construction via the cluster manager: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L679

If you need help feel free to reach out to @danielhochman here or in Slack and he can help you further.

**Comment by mattklein123** [comment]
@srikailash FYI I just opened envoyproxy/data-plane-api#465. Once I implement this, doing this item will be pretty trivial.

**Comment by srikailash** [comment]
Thanks for the update @mattklein123  . Following .

**Comment by srikailash** [comment]
Hello @mattklein123 or @danielhochman   , can you please check if this looks right (https://github.com/srikailash/data-plane-api/commit/17570cbb631a347bd4309c54c8adcd381c7b0f71) before i create a pull request  for data-plane-api .
I understand that next step would be to call lb_.reset() in cluster_manager_impl.cc with ZoneAwareLoadBalancer class if that's the case . Would implement that after getting this right . 
Thanks in advance .

**Comment by mattklein123** [comment]
@srikailash not quite. I would add the zone aware setting to the new `CommonLbConfig` message: https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/cds.proto#L352. It's basically already plumbed all the way through for healthy panic. You should be able to pull the value out similarly and use it as the default to the call to runtime.

**Comment by srikailash** [comment]
Got it . Change with this  https://github.com/srikailash/data-plane-api/commit/ff5490df98929beabb7a580e0710d287371cf3a4 .
Thanks .

**Comment by mattklein123** [comment]
That looks about right. There are various requirements around documentation, etc., but that can be covered in normal code review. Thanks!

**Comment by srikailash** [comment]
Will go through documentation and try to fix as much as possible before submitting PR . 
Thanks for the guidance .

**Comment by srikailash** [comment]
Thanks for merging @mattklein123  , htuch. Changes to https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/load_balancer_impl.cc#L17 to use values from configuration instead of runtime has to be done as a part of this issue or can this be closed ?

**Comment by cmluciano** [comment]
@srikailash Are you working on the Envoy side of this PR?

**Comment by mattklein123** [comment]
@juchem I don't think anyone is working on this. The config is already present IIRC it just needs to be wired up. It should be a pretty simple change.
