### ISSUE TITLE
jwt_authn: encapsulated jwt payload verification

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#13456]
This is feature request on JWT authn filter. This feature exists on Istio/proxy. https://github.com/istio/proxy/blob/master/src/envoy/http/authn/authenticator_base.cc#L130

To be clearly, this feature is to verify encapsulated JWT payload, such as,
If we have JWT payload like this,
```
{
       "iss": "service@example.com",
       "sub": "user-service",
       "aud": ["user1"],
       "original_claims": {
         "iss": "service2@example.com",
         "sub": "user-service2",
         "aud": ["user1"],
       }
}
```
With this feature, claims in `original_claims` will be used to be verified.
I'd like to discuss that this feature should be upstreamed on Envoy. cc. @liminw @yangminzhu @lizan

**Comment by yangminzhu** [comment]
thanks for opening the issue, also cc @qiwzhang.

**Comment by Shikugawa** [comment]
I agree with upstreaming this feature. 
If I implement this feature on another filter, request should walk 
1) jwt_authn filter to verify encapsulated JWT payload, and pass them with `forward_payload_header`. 
2) encapsulated jwt payload validation filter to exchange with specified claim (In this example, that is `original_claims`) and do duplicated action with jwt_authn.
It is not efficient solution and increases complexity.

**Comment by qiwzhang** [comment]
It is not clear to me.  Could you clarify what need to be done in order to "verify encapsulated JWT payload"?  JWT payload is a opaque data for jwt_auth filter.

**Comment by Shikugawa** [comment]
@qiwzhang What I said is only to set payload which is encapsulated by specified claim. Specifically, in current jwt_authn implementation, when we passed below JWT to it,

```
{
    "iss": "service@example.com",
    "sub": "user-service",
    "aud": ["user1"],
    "original_claims": {
      "iss": "service2@example.com",
      "sub": "user-service2",
      "aud": ["user1"],
    }
}
```

The JWT payload to set by [this](https://github.com/envoyproxy/envoy/blob/a0d952048c536c2da29be79df480a046ccf2be89/source/extensions/filters/http/jwt_authn/filter.cc#L79) will be same of above. But We'd like to do is to set,

```
{
    "iss": "service2@example.com",
    "sub": "user-service2",
    "aud": ["user1"],
}
```

into payload on dynamic metadata.

**Comment by qiwzhang** [comment]
I see.  Your feature request is to only write subset of payload to filter Dynamic metadata. Now jwt_authn is writing the whole jwt payload,  I see that it is more flexible, the downstream filters can choose any fields they want to consume.  What is the motivation to write subset?  trying to save memory?  JWT payload is not that big,  I really don't think you will save much on memory usage.

**Comment by Shikugawa** [comment]
@qiwzhang The motivation of this feature is to support RCToken exchange on jwt_authn. If we don't have this feature, we should write this exchange filter as extension but it is pretty redundant. I think that this feature should be integrated with jwt_authn filter.

**Comment by qiwzhang** [comment]
I don't think jwt_authn should do RCToken Exchange.  It should be done in a separate filter.

**Comment by Shikugawa** [comment]
@qiwzhang RCToken exchange is only example. The requirement of this feature is not only for them so it might be upstreamed. (Sorry, I'm not sure a specific situation...) Would you mind to tell me your philosophy about this?

**Comment by qiwzhang** [comment]
Sorry,  I may not have understand the issue correctly.   Maybe if we dig into the detail, it will be more clear.  Could you propose how  you will implement it?

**Comment by Shikugawa** [comment]
@qiwzhang We are considering to re-implement Istio AuthN filter to reduce tech debt and replace simpler api. I wrote the design doc of this. I will invite you here. Feel free to ping me on slack or here.
