### ISSUE TITLE
Improve install docs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13461]
Reading through the "build and installation" docs it seems like more focused on building than installing.

I think, ideally, we want instructions for how to do binary installs on different OS - at the moment it seems more targeted towards architectures.

One limitation here is that there are not many official packages atm (at least in the few linux distros i checked) - but it would be good to document what there was, and perhaps work with other distros to create official packages.

**Comment by snowp** [comment]
There is also https://www.getenvoy.io/ that Tetrate maintains (cc @lizan), which provides packages for a lot of different systems.

**Comment by mattklein123** [comment]
Yeah for now I would just link out to getenvoy for any binaries that people want beyond the docker images.

**Comment by phlax** [comment]
cool, ill put a page together with some links etc

**Comment by phlax** [comment]
checking here https://www.getenvoy.io/, it seems the following are supported:
- debian
- ubuntu
- centos
- rhel
- macos
- docker

**Comment by phlax** [comment]
i think this was mostly resolved in #13490
