### ISSUE TITLE
front-proxy example emits configuration warning on startup

### ISSUE THREAD

**Issue by tkgregory** [envoyproxy/envoy#13467]
*Description*:
Several helpful examples are provided in the `examples` directory of this project. When running the `examples/front-envoy` example I am observing warnings in the log to do with *Configuration does not parse cleanly as v3.*. 

It would be very helpful for this example to use the most up-to-date config so that new users (such as myself) can create a usable deployment without warnings.

*Repro steps*:
In project:

1. `cd examples/front-proxy`
1. `docker-compose up --build`

Observe the below warning in the log output

*Logs*:
```
front-envoy_1  | [2020-10-09 15:01:12.982][7][warning][misc] [source/common/protobuf/utility.cc:294] Configuration does not parse cleanly as v3. v2 configuration is deprecated and will
 be removed from Envoy at the start of Q1 2021: envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
```

The expectation is that this warning should not be emitted.

**Comment by phlax** [comment]
@tkgregory thanks for raising this, i can look into it unless you pr first

/assign phlax

**Comment by tkgregory** [comment]
Thanks @phlax that would be really handy. I'd happily help out, but I couldn't figure it out myself!

**Comment by dio** [comment]
@tkgregory I think you can replace the v2 `envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager` with v3 `type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`.

```diff
diff --git a/examples/front-proxy/front-envoy.yaml b/examples/front-proxy/front-envoy.yaml
index c266022e68..14204c9813 100644
--- a/examples/front-proxy/front-envoy.yaml
+++ b/examples/front-proxy/front-envoy.yaml
@@ -8,7 +8,7 @@ static_resources:
     - filters:
       - name: envoy.filters.network.http_connection_manager
         typed_config:
-          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
+          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
           codec_type: auto
           stat_prefix: ingress_http
           route_config:
@@ -38,7 +38,7 @@ static_resources:
     - filters:
       - name: envoy.filters.network.http_connection_manager
         typed_config:
-          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
+          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
           codec_type: auto
           stat_prefix: ingress_http
           route_config:
```

**Comment by phlax** [comment]
thanks @dio - ill create a pr  with your suggested fix...

**Comment by phlax** [comment]
one thing that confuses me about this ticket, is why the examples config validation is not detecting this

**Comment by dio** [comment]
@phlax while emitting warning messages, we transparently "upgrade" v2 to v3 messages. Relevant: https://github.com/envoyproxy/envoy/pull/13238. 

I think in the future, we can put an effort to detect the newly added config to skip v2 messages.

**Comment by tkgregory** [comment]
Thank you. I can confirm that the suggestion from @dio has solved the problem for me.

**Comment by mattklein123** [comment]
cc @htuch on ^. I thought that for config checking we fail on all warnings? Maybe that type doesn't count? It's probably worth understanding why though.
