### ISSUE TITLE
Statements from `psql` don't get parsed by the network filter postgres_proxy

### ISSUE THREAD

**Issue by WesleyBatista** [envoyproxy/envoy#13476]
*Title*: *Statements from `psql` don't get parsed by the network filter postgres_proxy*

*Description*:

With a very basic setup I got psql connections to postgres being proxied by envoy, and that could be confirmed by checking the **/stats** page where `postgres.postgres.sessions` and `postgres.postgres.sessions_encrypted` were getting increased. But unfortunately I noticed that `INSERT` and `SELECT` were not.

From the [docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter#config-network-filters-postgres-proxy-dynamic-metadata):
> When the Postgres filter detects that a session is encrypted, the messages are ignored and no decoding takes place.

Is this what is happening here?

With the docker-compose setup that I created [here](https://github.com/WesleyBatista/envoy-postgres-proxy-example) there is not specific increased security setup, I am actually even trusting all connections for the sake of seeing the filter working.

In what cases would the parser surely decode the message, and how can one reproduce it?

Thanks for looking :)

*Relevant Links*:
1. [Envoy Docs - Postgres proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter)
2. repo: [envoy-postgres-proxy-example](https://github.com/WesleyBatista/envoy-postgres-proxy-example)

**Comment by cpakulski** [comment]
Most likely the session is encrypted. Try to disable ssl:
`psql -U postgres -h localhost "sslmode=disable"`

**Comment by WesleyBatista** [comment]
Thanks for the answer and example! nice to see it working :D
