### ISSUE TITLE
bazel build  error   in centos7

### ISSUE THREAD

**Issue by zjd87** [envoyproxy/envoy#13489]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

WARNING: Download from https://github.com/grpc/grpc/archive/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz failed: class java.io.IOException Tried to reconnect at offset 9,318,152 but server didn't support it
ERROR: An error occurred during the fetch of repository 'com_github_grpc_grpc':
   java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz] to /root/.cache/bazel/_bazel_root/6828f19b3e1129fed5024145c6ebe69b/external/com_github_grpc_grpc/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz: Tried to reconnect at offset 9,318,152 but server didn't support it
INFO: Repository com_envoyproxy_protoc_gen_validate instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/6828f19b3e1129fed5024145c6ebe69b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Skipping '//source/exe:envoy-static': no such package '@com_github_grpc_grpc//bazel': java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz] to /root/.cache/bazel/_bazel_root/6828f19b3e1129fed5024145c6ebe69b/external/com_github_grpc_grpc/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz: Tried to reconnect at offset 9,318,152 but server didn't support it
WARNING: Target pattern parsing failed.
ERROR: no such package '@com_github_grpc_grpc//bazel': java.io.IOException: Error downloading [https://github.com/grpc/grpc/archive/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz] to /root/.cache/bazel/_bazel_root/6828f19b3e1129fed5024145c6ebe69b/external/com_github_grpc_grpc/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz: Tried to reconnect at offset 9,318,152 but server didn't support it
INFO: Elapsed time: 548.744s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: source/exe

how to solve this ?

**Comment by dio** [comment]
@zjd87 could you download https://github.com/grpc/grpc/archive/d8f4928fa779f6005a7fe55a176bdb373b0f910f.tar.gz to your build machine?

**Comment by zjd87** [comment]
can download,  but  part of download is break, rate of download is slow

**Comment by zyfjeff** [comment]
@zjd87 Build Envoy through Bazel in China failed due to the network speed. We need a VPN to accelerate.

**Comment by zjd87** [comment]
ok, thanks
