### ISSUE TITLE
Support to  config tracing custom tags based on response headers?

### ISSUE THREAD

**Issue by silencehe09** [envoyproxy/envoy#13484]
Looking forward to your help. @htuch @objectiser 

*Title*: *Support to  config tracing custom tags based on response headers?*

*Description*:
> 

- Background:  Our team are trying out Istio1.7 using Envoy as data plane, and we meet some trouble with tracing based on Envoy proxy. In some cases , we need to collect tracing data from response headers in Envoy. For  example, the application generates an ID of  business logic ( called BID) according to the incoming request , and set the BID in reponse headers for response.  Thus,  tracing data will be related with the BID, which is helpful for troubleshooting.

>

- Question :  Envoy supports to config tracing custom tags based on  request headers, literal values or environments. Is there any way to config custom tags based on response headers？Or does Envoy support ? 

[optional *Relevant Links*:]
>Wiki: [Envoy custom tags](https://www.envoyproxy.io/docs/envoy/latest/search.html?q=trace&check_keywords=yes&area=default)

**Comment by akashjain971** [comment]
Was any work done on this?
Setting tracing tags based on response headers would be really helpful.
Even though this can be achieved using dynamic metadata, wasm sdk does not support that.
WASM supports filter state but lua does not support it.
Response headers would be clean and readable just like request headers.
