### ISSUE TITLE
brew install envoy

### ISSUE THREAD

**Issue by ankane** [envoyproxy/envoy#13491]
Hi, thanks for this great project! Just wanted to let you know that Envoy is now available on Homebrew, so Mac users can install it with:

```sh
brew install envoy
```

Thanks to @rebello95 and others involved in the `-Wrange-loop-analysis` work for making this possible.

Ref: https://github.com/Homebrew/homebrew-core/pull/61858

**Comment by phlax** [comment]
thanks @ankane (ref #13461)

**Comment by mattklein123** [comment]
Awesome work! Thank you!
