### ISSUE TITLE
Windows build didn't copy exe to host

### ISSUE THREAD

**Issue by lodejard** [envoyproxy/envoy#13492]
*Title*: Windows build didn't copy exe to host

*Description*:
>Following https://github.com/envoyproxy/envoy/tree/master/ci#on-windows build ran to completion but did not copy exe to host machine as last step. Host disk *did* contain empty `C:\Windows\Temp\envoy-docker-build\envoy\source\exe` from the very start, but remained empty. Manual around was used (see below repro).

*Repro steps*:
> git clone master branch (was c155e8c657b3f3a15165700dfdbe84626cdb43b9)
> `./ci/run_envoy_docker.sh './ci/windows_ci_steps.sh'`
> ended with
```bash
INFO: From Linking source/exe/envoy-static.exe:
   Creating library bazel-out\x64_windows-opt\bin\source\exe\envoy-static.lib and object bazel-out\x64_windows-opt\bin\source\exe\envoy-static.exp
Target //source/exe:envoy-static up-to-date:
  C:/_eb/execroot/envoy/bazel-out/x64_windows-opt/bin/source/exe/envoy-static.exe
INFO: Elapsed time: 13403.284s, Critical Path: 803.67s
INFO: 4635 processes: 4635 local.
INFO: Build completed successfully, 6891 total actions
cp: cannot stat 'bazel-bin/source/exe/envoy-static.exe': No such file or directory
disk space at end of build:
Filesystem       Size  Used Avail Use% Mounted on
C:/tools/msys64   20G  5.0G   15G  25% /
``` 
*Workaround steps*:
> git clone master branch (was c155e8c657b3f3a15165700dfdbe84626cdb43b9)
> on host: `./ci/run_envoy_docker.sh bash`
> in container: `./ci/windows_ci_steps.sh`
> in container: `cp /c/_eb/execroot/envoy/bazel-out/x64_windows-opt/bin/source/exe/ /c/build/envoy/source/exe/ -r`

*Admin and Stats Output*:
>N/A

*Config*:
> clean checkout of c155e8c657b3f3a15165700dfdbe84626cdb43b9
> Windows 10 Enterprise
> Docker desktop community 2.4.0.0 (48506) stable
> Docker engine v19.03.13

*Logs*:
>docker container inspect [container.txt](https://github.com/envoyproxy/envoy/files/5359986/container.txt)
>/c/_eb/command.log [command.log](https://github.com/envoyproxy/envoy/files/5359997/command.log)

*Call Stack*:
> N/A

**Comment by sunjayBhatia** [comment]
@lodejard I was not able to replicate this on my dev workstation, and CI should be running the exact command you are running: https://github.com/envoyproxy/envoy/blob/1ca53123c078b6545d393d2974c58ddc3bebabb4/.azure-pipelines/pipelines.yml#L334

Your output is a tiny bit different than what I see in CI:

From https://dev.azure.com/cncf/envoy/_build/results?buildId=54201&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=168f295b-0553-5364-35f7-923225ecd8b3&l=1904

```
...
INFO: From Linking source/exe/envoy-static.exe:
   Creating library bazel-out\x64_windows-opt\bin\source\exe\envoy-static.lib and object bazel-out\x64_windows-opt\bin\source\exe\envoy-static.exp
Target //source/exe:envoy-static up-to-date:
  bazel-bin/source/exe/envoy-static.exe
INFO: Elapsed time: 218.662s, Critical Path: 96.73s
INFO: 4700 processes: 4696 remote cache hit, 4 remote.
INFO: Build completed successfully, 7017 total actions
```

whereas your output shows:

```
...
Target //source/exe:envoy-static up-to-date:
  C:/_eb/execroot/envoy/bazel-out/x64_windows-opt/bin/source/exe/envoy-static.exe
...
```

This might just be a weird artifact of the CI build running in RBE, but could be significant?

Do you have any overrides for Bazel version or anything else in your environment?

**Comment by sunjayBhatia** [comment]
@lodejard did you have any updates on this issue? were you able to perform any of the debugging steps listed above?

If not, I'm inclined to close this due to inactivity

**Comment by lodejard** [comment]
Hi, sorry for the long delay!

I'll try to reproduce with above on the latest code this week and I'll close if this issue is gone.

**Comment by sunjayBhatia** [comment]
@lodejard any luck?
