### ISSUE TITLE
Make `DynamicForwardProxy::DnsCache` support retrieving `DnsHostInfo` of a given host name from map

### ISSUE THREAD

**Issue by talnordan** [envoyproxy/envoy#13505]
*Title*: *Make `DynamicForwardProxy::DnsCache` support retrieving `DnsHostInfo` of a given host name from map*

*Description*:

I am thinking of extending the `Extensions::Common::DynamicForwardProxy::DnsCache` interface so that the `DnsHostInfo` of a given host name can be retrieved from the cache.

The filter I've been working on needs to perform DNS lookups and maintain the resolved info in a cache.
Therefore, I would like to be able to reuse the existing `DnsCache` code by invoking `loadDnsCacheEntry()`.
Such functionality is currently used by `DynamicForwardProxy` and by `SniDynamicForwardProxy`.
However, as opposed to current use cases, the caller of `loadDnsCacheEntry()` in my new use case requires access to the actual IP address resolved.

IIUC retrieving the `DnsHostInfo` resolved for a single host name using the current interface would require invoking `DnsCache::hosts()`.
This function returns all hosts currently stored in the cache, and seems to require copying this entire host map.
What I have in mind is modifying the `DnsCache` interface, in order to allow retrieving a single `DnsHostInfo` instance currently cached in the host map, by providing the host name.

One way to allow such behavior would be introducing a new getter function which receives a host name and returns a `DnsHostInfoSharedPtr` if the host is in the map.
Alternatively, we can modify `LoadDnsCacheEntryResult` so that it includes this information if the status returned is `InCache`, as well as modifying the signature of `LoadDnsCacheEntryCallbacks::onLoadDnsCacheComplete()` to make it include this information, for those cache entries which require loading.

Are there easier ways to retrieve the information?
If not, would it be appropriate to extend the `DnsCache` interface in such a way?

**Comment by mattklein123** [comment]
This sounds reasonable to me!
