### ISSUE TITLE
Could envoy support  specific  work pthread  auto bind cpu, if  i start --concurrency 1 

### ISSUE THREAD

**Issue by zjd87** [envoyproxy/envoy#13502]
be similar to NGINX  worker_processes 1;  worker_cpu_affinity auto;

**Comment by htuch** [comment]
Can you please elaborate on this by explaining what Nginx does or linking to the exact part of the documentation? Thanks.

**Comment by zjd87** [comment]
I mean that each work thread  can bind each cpu core, in case of multi work thread  compete  for the same cpu core

**Comment by htuch** [comment]
I think you are asking for CPU pinning via thread affinity. There was some discussion of this in https://github.com/envoyproxy/envoy/issues/4602. Do you have reason to suspect that there is a real issue here?

I think this might also come up in a performance measurement context, CC @oschaaf.

**Comment by zjd87** [comment]
> I think you are asking for CPU pinning via thread affinity. There was some discussion of this in #4602. Do you have reason to suspect that there is a real issue here?
> 
> I think this might also come up in a performance measurement context, CC @oschaaf.

#4602 should be kernel tcp reuseport, solve thundering herd and request load-balance
But my focus is that two or more thread maybe send interrupt signal in a moment, cause that cpu utilization rate reduce; If suport CPU pinning via thread affinity such configure, maybe avoid this case.
Thank you!

**Comment by zjd87** [comment]
@htuch https://github.com/envoyproxy/envoy/issues/13602   help me  solve this question , thank you!

**Comment by zjd87** [comment]
@htuch "Configurable ciphers: Each TLS listener and client can specify the ciphers that it supports."   how to configure ciphers, and  here isn't   configure demo in https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl
