### ISSUE TITLE
Generated docs are no longer published in (circle) CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13506]
### description

since we moved to azure for docs generation in #13481 we lost the ability to click through to get the generated doc artefacts

i use this quite a lot and was in the process of adding a repokitteh command to make it easier to get the link to the artefact (#13326)

it would be great if we can publish the docs artefacts on azure too

**Comment by mattklein123** [comment]
Hmm yeah. It seems bad to lose this. @lizan or @phlax can we figure out how to bring this back somehow?

**Comment by lizan** [comment]
We do have this and the link is in logs: https://dev.azure.com/cncf/envoy/_build/results?buildId=53840&view=logs&jobId=7e620c85-24a8-5ffa-8b1f-642bc9b1fc36&j=7e620c85-24a8-5ffa-8b1f-642bc9b1fc36&t=fb9b4be7-62d0-57cf-b629-fd6407055b34

**Comment by phlax** [comment]
it seems we also have per pr publishing, eg

http://storage.googleapis.com/envoy-pr/13490/docs/start/start.html

ill close this as i can continue with what i was doing `8)`

**Comment by mattklein123** [comment]
Oh nice. Can we update the docs and/or make this more obvious?

Maybe for docs can we have a CI step which is "Publish draft docs URL" and then just print the URL?

**Comment by phlax** [comment]
yep, and perhaps repokitteh can also help here

**Comment by lizan** [comment]
@phlax yeah I think use rk to publish them as detail url makes sense. (same for coverage report)
