### ISSUE TITLE
Is local rate limiting per worker thread or per envoy instance?

### ISSUE THREAD

**Issue by nitgoy** [envoyproxy/envoy#13517]
*Title*: *Is local rate limiting per worker thread or per envoy instance?*

*Description*:
>From reading the envoy documentation, I was under the impression that the local rate limiting is per envoy instance while the global rate limiting can be used to share/apply the limits across multiple envoy nodes (via the grpc service). But after reading the local rate limit code [here](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L37), it seems to me that the token bucket is local to the filter. Envoy's [threading model documentation](https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310) suggests that each worker thread initializes a separate set of listeners including all the filters. That implies the token bucket is actually local to each worker thread and not shared across the worker threads.
Is my understanding correct? If that's the case, does that mean we need to divide the local rate limits in envoy config by the max number of configured worker threads? That sounds really weird as the worker threads may not be fully balanced.
Or may be I'm missing something and the token bucket is indeed shared with other worker threads (the fact that it's an atomic variable shows it's designed to be shared with other threads). Sorry, I'm a complete newbie to envoy stack and trying to learn the threading model with respect to the filter instances.

[optional *Relevant Links*:]
>https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/local_rate_limiting
>https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/global_rate_limiting

**Comment by mattklein123** [comment]
Yes it is shared across all workers. Appreciate any doc updates to better reflect this. cc @rgs1

**Comment by nitgoy** [comment]
Thanks a lot for the confirmation. Would appreciate any pointers to documentation/code related to the shared filter instances across worker threads. It'll be useful for a bandwidth limit filter that I'm planning to add.

**Comment by rgs1** [comment]
Something like #13525 -- I should probably add a note for the L4 local rate limiter as well.

**Comment by nitgoy** [comment]
Just noticed that a previous note in [docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst](https://github.com/rgs1/envoy/blob/master/docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst) says:
"In the current implementation each filter and filter chain has an independent rate limit."

It seems to conflict with this new note.

**Comment by rgs1** [comment]
> Just noticed that a previous note in [docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst](https://github.com/rgs1/envoy/blob/master/docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst) says:
> "In the current implementation each filter and filter chain has an independent rate limit."
> 
> It seems to conflict with this new note.

It's true that each filter chain has its own rate limiter, but it's not true that each filter has its own rate limiter given that there's one rate limiter per config:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/local_ratelimit/local_ratelimit.h#L48

and one config per filter chain which is shared across filters:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/local_ratelimit/local_ratelimit.h#L74

**Comment by rgs1** [comment]
@nitgoy #13528 should clean it up. Thanks!
