### ISSUE TITLE
Add a glossary to docs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13532]
### description

The Envoy docs (and community discussions) use a lot of terminology that is not always clear/precise to new users

Some phrases are Envoy-specific, others are common in related communities (eg serverless, service mesh, etc). Many use acronyms

It would be good to have a glossary so key terms used in the Envoy docs can be set out clearly

Terms that immediately spring to mind

- `typed_config`
- [a-Z]DS
- middle/edge proxy
- data plane
- control plane
- circuit breaker
- (Envoy) filter
- (Envoy) extension
- (Envoy) Bootstrap
- sidecar

im happy to collate/write the glossary, but suggestions of terms and/or definitions would be greatly appreciated

**Comment by mattklein123** [comment]
+1 this would be great.

**Comment by moderation** [comment]
Upstream and downstream!
- A request is a salmon - https://twitter.com/benplotnick/status/1299178415996702726
- https://twitter.com/benplotnick/status/1230308689703100416
- https://twitter.com/mattklein123/status/1299139849279082496

**Comment by phlax** [comment]
- front proxy
- double proxy

**Comment by phlax** [comment]
> Upstream and downstream!

funnily i had been thinking about definitions for these, but the potentially counter-intuitive request salmon hadnt ever occurred to me.

~definitions i had been thinking of were:

- upstream: machine or network that an envoy proxy initiates connections to (in response to downstream requests)
- downstream: machine or network initiating requests to an envoy proxy

**Comment by phlax** [comment]
but now im thinking about request salmons im wondering about egress proxying too

**Comment by mattklein123** [comment]
Note that we have https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/intro/terminology. We should merge this into whatever we come up with here.

**Comment by phlax** [comment]
i havent gone through all the service discovery types completely, and some of the terms may not be 100% correct, but ive created a wiki page here to get started

https://github.com/phlax/envoy/wiki/Glossary

**Comment by phlax** [comment]
thanks @moderation added, and ive opened a wip PR to progress this #13829
