### ISSUE TITLE
Some deprecated configs dont seem to be caught in config validation

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13542]
### description

The `config_validation` part of CI checks configs in docs + examples to ensure that they are not using deprecated features 

Some features seem to pass CI even tho they should be updated. The relevant configs trigger warnings when Envoy is run (in verify examples eg)

### refs
- #13503 
- #13529

**Comment by htuch** [comment]
@phlax do you have an example repro for this? Happy to dive into this one.

**Comment by phlax** [comment]
@htuch looking through current CI it seems like there are no deprecation warnings any more, so im not quite sure exactly what the issue was here.

tracking back through, i think this ticket was created from this comment https://github.com/envoyproxy/envoy/pull/13503#pullrequestreview-506680908 - so i guess the issues fixed there would be the repro

**Comment by htuch** [comment]
I verified that switching back to v2 HCM in `examples/cors/backend/front-envoy.yaml ` generates a test failures with:
```
Failed
'' config failed. Error: The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition. (envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager)
```

I'm pretty sure the set of PRs that made v2 fatal-by-default has taken care of catching these v2 cases in config validation.
