### ISSUE TITLE
Wasm: Extract response protocol in the onResponseHeaders function

### ISSUE THREAD

**Issue by mcieplak** [envoyproxy/envoy#13553]
### Description
We cannot seem to find an approach to extract the HTTP response protocol in the onResponseHeaders function. It seems there is no corresponding attribute that has this information. It also appears that the stream object itself is not accessible through the proxy wasm API which is there in the Lua API.

### Observations / Areas Explored
- In the request flow, the onRequestHeaders function does have an attribute called request protocol which is accessible through the getValue function call. However, there does not exist a response protocol attribute that can be accessed in onResponseHeaders which has similar information.
- Some attributes such as response code are not accessible in the onResponseHeaders function but available in others functions such as onResponseBody or onLog.

### Questions
1. Is there an approach to extract the response protocol in the onResponseHeaders function?
2. If an option does not exist through the API, would it be possible using a foreign function interface instead?

**Comment by htuch** [comment]
@PiotrSikora can you help out with this one? Thanks.

**Comment by PiotrSikora** [comment]
@kyessenov is the expert of all properties exposed in Wasm.

**Comment by kyessenov** [comment]
Request and response protocol are usually the same, since it is negotiated in the codec for two parties to be able to understand each other. Is that not the case for you?

**Comment by mcieplak** [comment]
@kyessenov I thought the request protocol is actually the protocol from the incoming client connecting to Envoy. Is this not the case? If the Wasm filter needs to be attached before the main envoy.router filter then I believe we do not have the upstream cluster information and it's corresponding protocol here in the onRequest flow.

This is the reason which I was hoping the response protocol would have this information in the onResponse flow as that is part of the connection between Envoy and the upstream. Are there any properties here that contain this information?

**Comment by kyessenov** [comment]
@mcieplak It makes sense to record the upstream protocol. I'm not sure if it's correct to call it response protocol, since it would be strange to have request and response have mismatched protocols (e.g. http/1.1 and h2). Maybe upstream.protocol?

**Comment by mcieplak** [comment]
@kyessenov I agree that response protocol sounds a little bit confusing as I meant the protocol in terms of the upstream. It makes sense to call it upstream protocol instead. Is this attribute already available or is this something that will need to be added?
