### ISSUE TITLE
bug: original_dst filter should update downstream local address

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#13554]
Prior to https://github.com/envoyproxy/envoy/pull/12935, the socket address was already updated before constructing stream info. Now that stream info is created ahead of listener filters, the value for the downstream socket address changed.

**Comment by kyessenov** [comment]
It affects logging mostly, but may also affect RBAC policies if they reference destination address. I think istio is the most affected downstream project as a heavy user of original_dst.

**Comment by mattklein123** [comment]
FWIW I would really love to have an integration test here, I just don't know if it's technically possible.
