### ISSUE TITLE
Process for regenerating crates.bzl

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#13566]
We now have bazel/crates.bzl but no documented process or script for regenerating. We should have some push-button method or recipe to regenerate from the various TOML.

Assigning to @lambdai for triage and/or fix.

CC @PiotrSikora @envoyproxy/dependency-shepherds

**Comment by PiotrSikora** [comment]
cc @Shikugawa

**Comment by Shikugawa** [comment]
Previously, I've created [simple script](https://github.com/Shikugawa/envoy-wasm/blob/e2b9313d2b177903154e2ee1f1689e2c0b519021/tools/cargo-raze.sh) to generate crate.bzl. (This tool have not been merged). Can you use this?

**Comment by moderation** [comment]
I was looking through the PR trying to find out how `cargo raze` was invoked and now I know why I couldn't find it :smile:

**Comment by htuch** [comment]
@Shikugawa yes, if we fix it to clean up all artifacts and add some documentation in bazel/README.md or bazel/EXTERNAL_DEPS.md. Thanks!

**Comment by htuch** [comment]
@Shikugawa I just tried this script. The path is not quite right and it only runs for a single TOML, but we multiple of these in the tree. Also, the output at the end looks quite different to our existing crates.bzl, it seems there was some hand editing as well.

This is problematic as things exist; we have no way to bump dependencies if there are security issues or to try out the advice in https://github.com/google/cargo-raze/issues/249#issuecomment-709495941 to generate sha256 pinning. This is tempered by them being test-only deps, but still. Would appreciate this being cleaned up as part of the post-Wasm merge CC @PiotrSikora @lizan

**Comment by PiotrSikora** [comment]
@htuch I don't believe there were any edits to the generated files. The `cargo-raze` tool changed a bit since we generated them, and I imagine that if you use the older version (`cargo install cargo-raze --version 0.3.8`), then you should see the same output.

**Comment by PiotrSikora** [comment]
We could combine them all into a single TOML and then use `[[example]]` or `[[bin]]` sections with relative paths to existing `.rs` files to generate multiple targets from it. I think that @Shikugawa was looking into it a while ago.

**Comment by htuch** [comment]
This would be really great, thanks.

**Comment by lizan** [comment]
Yeah that would be great. We can also look into to generate this as part of repository rule (similar to pip3_import for python), though that will be part of rules_rust.

**Comment by PiotrSikora** [comment]
Fixed in #13615. Not sure why it didn't pick it up.
