### ISSUE TITLE
Troubleshooting TLS client authentication

### ISSUE THREAD

**Issue by tonybaines** [envoyproxy/envoy#13563]
*Title*: *Troubleshooting TLS client authentication*

*Description*:
When client TLS authentication is configured and a client connects with an untrusted cert/key (not signed by a known CA), or a trusted but unauthorised cert (not in the set of authorised digests), or with no certificate at all, the response is always the same - the connection is closed with an empty reply from Envoy.  This makes it impossible for clients to diagnose the issue.

The envoy `access.log` contains nothing, standard logging only seems shows a message if a trusted cert which is unauthorised *and* if debug level is switched on for connections, making it impossible to detect or discriminate from production envoy logs.

> [2020-10-14 09:39:42.916][35][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C65] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

Ideally it should be possible to return a 401 status with body to the client and to log the failure in `access.log`.

[optional *Relevant Links*:]
Issue #1472 was originally raised to ask a similar question, it was closed in favour of #4283 but the solution there doesn't seem to help with this situation since the failed connection negotiation never makes it as far as the access log.

**Comment by htuch** [comment]
How can a 401 be returned if the client TLS hasn't been established? Or are you talking about TLS to upstreams from Envoy?

**Comment by tonybaines** [comment]
You're quite right of course, a client response wouldn't be possible to downstream without minimal TLS negotiation but for the situation of a trusted certificate (CA chain is recognised), but which is unauthorized it doesn't seem unreasonable.

What are your thoughts on the server side diagnostics?

**Comment by htuch** [comment]
Have you look at using `trust_chain_verification` to control behavior on untrusted certs? What do you mean by unauthorized in this situation?

I'd probably look at `trace` logs and `/stats`, but I think you're asking how to handle this cleanly in production when you have a mix of different failure scenarios and want to handle them gracefully?

CC @lizan @ggreenway @PiotrSikora for thoughts on how to handle this cleanly.

**Comment by ggreenway** [comment]
I haven't verified the behavior, but my expectation would be that an ssl alert would be sent to the client, probably code 48 (unknown CA). That may be useful for the client to debug.

An http access log wouldn't contain an entry, because there was no http request on the connection (closed before any request could be received). But there may be useful information in connection-level access logs, which were added in the last 6 months or so (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto.html?highlight=access_log).

**Comment by PiotrSikora** [comment]
Accepting connections with missing/invalid client certificate at the TLS layer would violate the requested policy, so while I agree that it would lead to a better end-user experience, I don't think that we should do it. Also, as @ggreenway said, the client should receive a TLS alert, and the user-agent should be able to present it to the end-user.

However, you can request - but not require - client certificates at the TLS layer, and use RBAC filter to enforce credentials at the HTTP layer, returning 401 in case of missing/invalid client certificates.

**Comment by tonybaines** [comment]
@htuch We're using `extensions.filters.network.client_ssl_auth.v3.ClientSSLAuth` for authorisation - there doesn't seem to be a way of seeing authorisation failures, even with debug logs switched on.  Is there any extra metadata I can extract into the logs for this?

@ggreenway Thanks for the pointer - that gives me logs on connection attempts by downstream whether or not mutual TLS was negotiated, and records the downstream CN which is a big step forward in being able to diagnose problems from the server side.  I had hoped that `%CONNECTION_TERMINATION_DETAILS%` might include some detail but it always logs 'null'.

There is an `* OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0` for the specific case of a downstream cert signed by a CA chain that's not trusted.

Overall I think the listener access log is good enough for our use, there are relatively few downstream clients and low churn so CN is enough to do a manual diagnosis of the three scenarios I mentioned.
