### ISSUE TITLE
Docs improvement on Read The Docs theme

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#13584]
Can we remove `Built with Sphinx using a theme provided by Read the Docs` from footer?
cc @mattklein123 @moderation @phlax

**Comment by moderation** [comment]
@mk46 why?

**Comment by mk46** [comment]
I don't think this is related to envoy.

**Comment by moderation** [comment]
It is very much related to Envoy. Docs are a big part of the project and the projects success and are part of every CI run. The maintainers and the community spend a lot of time improving them. See https://github.com/envoyproxy/envoy/tree/master/docs

**Comment by phlax** [comment]
> Can we remove Built with Sphinx using a theme provided by Read the Docs from footer?

seems like a good idea, we are not hosting on "read the docs" - altho i guess using their theme we should make sure its credited somewhere

on a related note - i was wondering about the theme. The RTD theme, i believe, is mobile-compliant, which i guess is the reason we are using that theme particularly.

i think  we should consider using the "Alabaster" theme, which i think is also good on mobile, but more plain so we could add a little colour without changing the layout.

see https://www.writethedocs.org/guide/tools/sphinx-themes/ for good discussion/background

**Comment by phlax** [comment]
expanding a little on my comment, i think its a little confusing seeing the RTD attrib, because i at first assumed wrongly that the docs were hosted there.

i think one advantage of the RTD layout is that its very familiar to devs that its docs.

It wasnt on my immediate radar to suggest changing the theme, as i think it requires some consideration/agreement to do so

**Comment by htuch** [comment]
I think we should have some visual distinction between the navigation elements and the content, so Alabaster would need some tweaking to support that. I don't think what we're shooting for is minimalism FWIW, but having something that is visually clean and ergonomic is important.

**Comment by phlax** [comment]
> I don't think what we're shooting for is minimalism

yep, i was just trying to think how we could apply envoy purples to a mobile-compliant UI

**Comment by mattklein123** [comment]
re: footer: No strong opinion but we should give credit where credit is due.

re: theme: I'm fine to change the theme, but we should get a bunch of opinions before doing it. Personally, I would rather focus on the content before we start playing with visual stuff like that.
