### ISSUE TITLE
Make Envoy github wiki editable 

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13586]
### description

it would be quite handy if the  wiki was editable by repo members as it could be used for staging docs/info and collaborative editing

the 2 wiki pages i would quite like are

- glossary - (as a staging area before adding to docs)
- useful links, eg
   - stackoverflow moans/solutions
   - 3rd party tutorials/walkthroughs

**Comment by phlax** [comment]
eg this walkthrough is great - but im not sure where to link it 

https://www.aapelivuorinen.com/blog/2020/08/01/envoy-json-grpc-transcoding/

**Comment by htuch** [comment]
Seems like it could be useful, the alternative is to build out more structured information in GH .md. One downside is that without maintenance and active management it might become stale and misleading (same as any other docs, but now we have another place to fight this battle).

**Comment by phlax** [comment]
> One downside is that without maintenance and active management it might become stale and misleading

yep, for sure.

i think i was trying to find a way that we can have ~public docs that are easy-to-update. 

I guess the page of links is my biggest priority - i would rather we didnt add them to docs as we would need to ~vet/maintain them etc

**Comment by phlax** [comment]
in the absence of anywhere else to put these ive created a wiki page in my repo to collate links for now

https://github.com/phlax/envoy/wiki/Useful-links

**Comment by htuch** [comment]
I think this would be reasonable to take on the official Envoy wiki page, what do we need to do to set some allowlist of contributors to edit it?

**Comment by phlax** [comment]
> what do we need to do to set some allowlist of contributors to edit it?

on further investigation it seems that is not possible

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis

it seems like the edit options are `collaborators` OR `everyone` - and i think collaborators is defined as commit access

not sure if this will work. pity.

feel free to close the ticket as #wontfix

**Comment by phlax** [comment]
we could still move the page to the envoy wiki - just less people will be able to update

**Comment by phlax** [comment]
or everyone can, but im not  sure about that - might  work

**Comment by htuch** [comment]
Yeah, I don't fully understand the ACLs here, GitHub isn't super clear. Can we just make this a `.md` that we edit via PRs? This seems to be the easiest to reason about. Maybe open a PR for your set of links?

**Comment by phlax** [comment]
> Maybe open a PR for your set of links?

ok. ill let it incubate a while longer first, im adding links pretty frequently, and dont want to create a lot of PR noise

**Comment by phlax** [comment]
bump

**Comment by htuch** [comment]
@lizan has made the wiki world-writable on a trial basis.
