### ISSUE TITLE
Add a Postgres sandbox

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13597]
### description

it would be really useful to have a sandbox to demonstrate the Postgres filter

**Comment by dio** [comment]
@cpakulski probably we can adapt https://github.com/tetratelabs/envoy-postgres-stats-example to this repo?

**Comment by cpakulski** [comment]
Thanks Dhi, This is good idea. I will have to integrate it with CI as it
runs examples now.

**Comment by phlax** [comment]
@cpakulski lmk if i can help in any way

**Comment by fabriziomello** [comment]
@dio @cpakulski @phlax I'm working on it now.

**Comment by phlax** [comment]
@fabriziomello i think the easiest way to get started is to copy out the `mysql` sandbox and then swap out the backend server

**Comment by fabriziomello** [comment]
> @fabriziomello i think the easiest way to get started is to copy out the `mysql` sandbox and then swap out the backend server

It's exactly what I'm doing... ;)

**Comment by phlax** [comment]
fixed in #13651
