### ISSUE TITLE
sandbox: PostgreSQL Network Filter sandbox

### ISSUE THREAD

**Issue by fabriziomello** [envoyproxy/envoy#13628]
Adding a complete example of how the Postgres Network Filter works will make life easier for those who want to try it. 

The idea here is create a sandbox like [other filters](https://www.envoyproxy.io/docs/envoy/latest/start/start#sandboxes) already does. 

We already implemnted a complete example [here](https://github.com/ongres/envoy-postgres-stats-example) so now the task is just to write the documentation.

**Comment by phlax** [comment]
hi @fabriziomello i think this is is a duplicate of #13597

**Comment by phlax** [comment]
if you are up for taking that ticket on  that would be great - i would be happy to help

**Comment by fabriziomello** [comment]
Ohh @phlax sorry... Didn't pay attention. Will close it!

Anyway I'm working on it now! Thanks!
