### ISSUE TITLE
Getting upstream_reset_before_response_started{local reset}

### ISSUE THREAD

**Issue by hinawatts** [envoyproxy/envoy#13643]
*Title*: While doing perf testing we start getting the response upstream_reset_before_response_started{local reset} intermittently

*Description*: We are using envoy as reverse proxy, where a request from client hits envoy and based on some header we route it to upstream configured with 4 hosts. It works fine based on functionality point, however while doing perf we start getting upstream_reset_before_response_started{local reset} intermittently on few upstream hosts.
>Describe the issue. Getting upstream_reset_before_response_started{local reset} in response .

Can you please help me understand what could be the reason behind this ? CPU usage of envoy and upstream is within limits.

**Comment by yanavlasov** [comment]
There are multiple reasons for local reset. For instance response timeout, invalid messaging from upstream, etc. You need to see if there are any other counters that go up with the upstream_reset_before_response_started.
