### ISSUE TITLE
'grpc-accept-encoding' header isn't respected in grpc-web

### ISSUE THREAD

**Issue by vbfox** [envoyproxy/envoy#13647]
When envoy receive a request from grpc-web either without `grpc-accept-encoding` header or with any value like `grpc-accept-encoding: identity` it will send the request to the upstream with it's own set of accepted encoding (`identity,deflate,gzip` currently) but if the upstream answer with one of theses (`grpc-encoding: gzip` for example) envoy forward that encoding to the grpc-web client even if it wasn't in the requested list.

### Potential solutions

1. Forward the client header to the upstream as-is if provided and only insert `grpc-accept-encoding: identity` instead of risking to provide an encoding when not expected.
2. Continue sending an envoy-specific encoding list but transcode the result to an encoding that the client claim to support in the filter.

### Note 1

This comment seem wrong, not changing the request headers would have been more correct:

https://github.com/envoyproxy/envoy/blob/ef125e3b20820397d82d58e1e36be3bd598e4323/source/extensions/filters/http/grpc_web/grpc_web_filter.cc#L88

The specification can be found here: https://github.com/grpc/grpc/blob/master/doc/compression.md#compression-method-asymmetry-between-peers

### Note 2

The current code tend to work well with go servers because they don't implement `grpc-accept-encoding` ( https://github.com/grpc/grpc-go/issues/2786 ) and currently use the same compression as the request (`grpc-encoding`) but if that issue is solved grpc-web will be broken in more cases.

### Existing issue

* https://github.com/envoyproxy/envoy/issues/9168 seem to be about the same problem or a variant of it but closed as stale
* https://github.com/grpc/grpc-web/issues/561 is about support of *gzip* encoding on grpc-web side

**Comment by asraa** [comment]
@fengli79 @lizan any thoughts on this?

**Comment by vbfox** [comment]
I created a PR with an attempt at 'Solution 1' https://github.com/envoyproxy/envoy/pull/13654 if it is the direction that is finally decided

**Comment by asraa** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/13654
