### ISSUE TITLE
Consolidate/(re)tag Envoy Docker images

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13649]
### description

in the course of updating the install/build instructions (#13490), i have transposed the current information about available Docker images from here:

https://www.envoyproxy.io/docs/envoy/latest/start/building#pre-built-binaries

into a table here:

https://storage.googleapis.com/envoy-pr/13490/docs/start/install.html#pre-built-envoy-docker-images

The table highlights a few issues

Currently you cant do

```
docker run envoyproxy/envoy
```

as there is no `latest` image - i think the `latest` should point to the current latest eg `v1.16-latest`

this can confuse some users (including me) - see #13570

the `envoyproxy/envoy-dev*` images do have a `latest` which points to last successful build on `master/head`.

i would propose to consolidate this image with `envoyproxy/envoy` and rename the tag to eg `head`

the `envoyproxy/build-image-ubuntu` has no `latest` and instead tags images with the last commit sha (from the envoy-build-tools repo).

this is fine for pinning the build image in CI, but its a pita for end-users as they have to know the sha tag and difficult to use in documentation (see https://github.com/envoyproxy/envoy/pull/13622#discussion_r507742056 for related issue)

i would propose adding a `latest` tag on this repo.

i have added an idealised Docker images table here:

https://storage.googleapis.com/envoy-pr/13490/docs/start/install.html#idealised-envoy-docker-images

(the above links to tables may/not work correctly as #13490 is developed further)

**Comment by phlax** [comment]
> people will use it in production whether we like it or not

this could be helped hugely with some info here:

https://hub.docker.com/r/envoyproxy/envoy
ie - the bit where it says "This repository doesn't have an overview"

**Comment by phlax** [comment]
in my understanding - people *will* use these images for production or whatever  else, even once they have found  the `vCURRENT-latest` tag if they are not advised otherwise

**Comment by phlax** [comment]
not sure if i understand about "multiple release lines" - i think the current releases are as the table shows (and the old documentation)

**Comment by phlax** [comment]
>  Is there any other way we can deal with this?

not exactly another way - but i would suggest adding an official `docker/library` image that *is* optimized for ~production use (at least in the general case)

i think this suggestion is a bit outside of the scope of this ticket - but i think that is the way we can differentiate between versioned/ongoing builds and official/production ones - ie providing the latter

**Comment by mattklein123** [comment]
> ie - the bit where it says "This repository doesn't have an overview"

Happy to update text on the repos if you want to suggest some.

> not sure if i understand about "multiple release lines" - i think the current releases are as the table shows (and the old documentation)

We support 4 stable releases at this point. So for right now 12.x, 13.x, 14.x, 15.x. A generic "latest" doesn't mean anything and will break people if they pin to latest.

**Comment by phlax** [comment]
> A generic "latest" doesn't mean anything and will break people if they pin to latest.

i think its no different to eg Debian tagging `Buster` -> `Stable` or eg `nginx` having an  image that you can do `docker run nginx` out of the box with

**Comment by phlax** [comment]
> Happy to update text on the repos if you want to suggest some.

im thinking mostly we can use the table above and the info here https://storage.googleapis.com/envoy-pr/13490/docs/start/docker.html

**Comment by mattklein123** [comment]
> i think its no different to eg Debian tagging Buster -> Stable or eg nginx having an image that you can do docker run nginx out of the box with

I agree, but it's a bad idea and we shouldn't repeat bad ideas just because they are common.

**Comment by phlax** [comment]
`latest` == `latest-stable` ie track stable rather  than a particular version -  i think it has specifically functionality - but defo we could doc the potential gotcha of "stable changes"

**Comment by phlax** [comment]
> A generic "latest" doesn't mean anything

i think right now `latest` == `v1.16-latest` as that is current stable

**Comment by mattklein123** [comment]
The problem is that if someone pins to "latest" and is on the 1.16.x line, once we release 1.17.x, they will move. This is not acceptable IMO. 

If this is a docs issue, I would rather just fix the docs somehow.

**Comment by phlax** [comment]
> The problem is that if someone pins to "latest" and is on the 1.16.x line, once we release 1.17.x, they will move. This is not acceptable IMO.

k, well i still think we should consolidate the `-dev` images to the other envoy images (afaiaa they are the same just different release points) with a different tag *and* add a latest for the build image

**Comment by mattklein123** [comment]
We do have a latest tag for the nightly images.

**Comment by phlax** [comment]
my proposal

get rid of "-dev"

tag what is currently "-dev:latest" -> ":head"

**Comment by phlax** [comment]
ie, not

```
docker run envoyproxy/envoy-dev
```
but, instead

```
docker run envoyproxy/envoy:head
```

**Comment by phlax** [comment]
similar to what GetEnvoy does

**Comment by mattklein123** [comment]
The reason we have "-dev" split from non-dev is that with the nightly per-SHA images, we would get constant complaints about "
I don't see the tagged images" in docker hub, because docker hub search is terrible, so I don't think we can do this either.

**Comment by phlax** [comment]
well we are left with the non-idealized distro table

as someone who tried to follow those docs and the build etc i did not know what was official/production/dev whatever

it was my biggest gripe with the project (as a new user)

**Comment by mattklein123** [comment]
All I can tell you is we arrived at the current state based on a bunch of iteration and a lot of people complaining. Unless there is an obviously better state, I'm not in favor of changing.

Let's fix the docs and go from there.

**Comment by phlax** [comment]
when i searched for the `Dockerfile` for the recipe i found it in the `ci` folder which just confused me further

i think we need to do a lot more like GetEnvoy and confuse new users less

sorting the docs out  should address workflows and potential pitfalls

**Comment by phlax** [comment]
> Let's fix the docs and go from there.

ill just remove the idealized table and leave it as is - that *is* what is there

**Comment by phlax** [comment]
hmm, well at  least i will PR to tag the `envoyproxy/build-image-ubuntu` image with `latest` - im hoping there is no reason why that cant happen - and it will make using this (huge) image a lot easier

**Comment by phlax** [comment]
> nightly per-SHA images

just to clarify (in my mind) i dont think we have "nightlies" we have the `master` head published to `-dev:latest` on last successful build

**Comment by mattklein123** [comment]
> hmm, well at least i will PR to tag the envoyproxy/build-image-ubuntu image with latest - im hoping there is no reason why that cant happen - and it will make using this (huge) image a lot easier

Sure.

> just to clarify (in my mind) i dont think we have "nightlies" we have the master head published to -dev:latest on last successful build

Correct.

**Comment by lizan** [comment]
> hmm, well at least i will PR to tag the `envoyproxy/build-image-ubuntu` image with `latest` - im hoping there is no reason why that cant happen - and it will make using this (huge) image a lot easier

No, this confuses folks as well. We pin images in this repo, which `ci/run_envoy_docker.sh` pins to, latest image could be broken and not buildable any version of Envoy before we move CI to the last one.

**Comment by phlax** [comment]
> No, this confuses folks as well.

and hardcoding the sha like this https://github.com/envoyproxy/envoy/pull/13622#discussion_r507742056 doesnt?

im really struggling to see how having a `latest` in addtion to whatever sha builds there are could confuse people - sure they dont need to use it, and neither does CI

**Comment by phlax** [comment]
im going to indulge myself and explain why i think the current strategy is a really bad idea, then i will rest my case - feel free to ignore, close the ticket or leave it blowing in the wind.

### no version == latest *is* the convention

>>   i think its no different to eg Debian tagging Buster -> Stable or eg nginx having an image that you can do docker run nginx out of the box with

> I agree, but it's a bad idea and we shouldn't repeat bad ideas just because they are common.

personally i dont think it is a bad idea, but regardless this is how pretty much every software distribution system works. Going against such a firm convention is simply breaking users expectations

### using official images/distribution channels is *authoritative*

my ideal would be to be able  to do

```
docker run envoy
apt-get install envoy
yum install envoy
```
this is not just convenience or the desire  to use a "vanity"  name in the install command - its about using the "official" envoy in *my* repos (ie vetted by Debian, Docker, redhat or whoever)

when i first started using the project i found the current distribution very difficult to understand (no official packages, no `latest`), compounded by what documentation there was

### build-image-ubuntu has no docs

mostly because you are expected to use it with `run_envoy_docker.sh` which also (wiithout documenting the fact, or needing to in 90% of uses) mounts `/var/run/docker.sock` and is privileged - ie gives root on the host system

the  only time i have ever run this script is in an isolated throwaway vm - there is no way i would run this on my local machine, ever

---

i feel the need to  make theses points because to me these *are* the footguns that gave me a bad experience of trying to  use the  project as a new user.

case rested.

**Comment by mattklein123** [comment]
For the official images, I am strongly against a generic latest tag for the reasons noted. So objections noted but we aren't going to do that.

For the build image I think it's fine to have a latest tag (and we can still spin to SHA in CI) but I will defer to @lizan on that.

**Comment by lizan** [comment]
> ### envoy-build-ubuntu has no docs
> mostly because you are expected to use it with `run_envoy_docker.sh` which also (wiithout documenting the fact, or needing to in 90% of uses) mounts `/var/run/docker.sock` and is privileged - ie gives root on the host system (dropping the user privileges to `id -u` in this container is like a maginot line)
> 
> the only time i have ever run this script is in an isolated throwaway vm - there is no way i would run this on my local machine, ever

That's a separate issue from tagging build docker image. I am still against tagging latest and recommend that to folks to use. The only image would work is what that script, (i.e. what `ci/envoy_build_sha.sh` sets to env). We've been seen issues before:
- using latest image to build older version, now we have stable releases so this is likely to happen.
- the latest image not even buildable master, this happens when we upgrade LLVM and/or GCC toolchains. For example LLVM 10 takes us long time to upgrade (see https://github.com/envoyproxy/envoy/pull/11222).

**Comment by phlax** [comment]
> That's a separate issue from tagging build docker image

not entirely.

not having a `latest` image creates 2 problems

- in documentation you *must* hardcode the somewhat arbitrary last-build-sha-on-the-build-repo-when-the-docs-were-published
- trying to use the image outside of the `run_envoy_docker.sh` script looks like this

```console
$ docker images | grep build-ubuntu
envoyproxy/envoy-build-ubuntu   b480535e8423b5fd7c102fd30c92f4785519e33a   7757d8081892        2 weeks ago         3.8GB
$ docker run envoyproxy/envoy-build-ubuntu whoami
Unable to find image 'envoyproxy/envoy-build-ubuntu:latest' locally
docker: Error response from daemon: manifest for envoyproxy/envoy-build-ubuntu:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
$ docker run envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a whoami
root
```

ie. you have to copypasta  the sha to make the image work  - which is just frustrating

to make clear  why  running `run_envoy_docker.sh` is a really bad idea - let me suggest the following command, which you might not want to run

```
./ci/run_envoy_docker.sh bash -c "docker run -v /:/nom-nom-im-going-to-eat-you bash -c 'whoami && ls /nom-nom-im-going-to-eat-you'"
```

**Comment by phlax** [comment]
apologies if my example seemed flippant - i was trying to make a point - inside that container you have root on the *host*

**Comment by lizan** [comment]
Again it's not a tagging issue or an issue of the script. if you can do `docker run`, no matter you use the script or not you already have root access to the host... i.e. just run `docker run -v /:/nom-nom-im-going-to-eat-you bash -c 'whoami && ls /nom-nom-im-going-to-eat-you'` even if you're not root?

I'm happy to improve the doc or script re: how to get the image tag properly, but `latest` doesn't work for sure.

**Comment by phlax** [comment]
i give up
