### ISSUE TITLE
Cannot enable pprof using static compiled envoy

### ISSUE THREAD

**Issue by hazelnutsgz** [envoyproxy/envoy#13672]
As guided by the instruction on [CPU or memory consumption testing with pprof](https://github.com/envoyproxy/envoy/blob/master/bazel/PPROF.md), I tried to monitor the overall performance behaviors of envoy.

But after running ```CPUPROFILE=/tmp/mybin.cpuprof bazel-bin/source/exe/envoy-static <args>``` to make the ```envoy-static``` running, I cannot fetch the data from /tmp/mybin.cpuprof. 

I was wondering if there is anything wrong with the compilation of ```envoy-static```, or anything else went wrong here. Thanks.

**Comment by yanavlasov** [comment]
Can you clarify the problem, please?

**Comment by hazelnutsgz** [comment]
The thing here is that no such the file called ```/tmp/mybin.cpuprof``` was found, after running ```CPUPROFILE=/tmp/mybin.cpuprof bazel-bin/source/exe/envoy-static -c myconfig.yaml```.

So I cannot use ```pprof -text bazel-bin/source/exe/envoy main_common_base* | head -n5``` to get the pprof result.

Thanks.

**Comment by yanavlasov** [comment]
Hmm, I'm not sure what the problem is. You can also try to enable profiler through the admin interface [like so](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--cpuprofiler) and see if it works.

**Comment by lambdai** [comment]
By default we switched to google tcmalloc but the cpu/heap profiler is provided by gperf tcmalloc

run `bazel build --define tcmalloc=gperftools //source/exe:envoy` to build envoy and the profiler will be back

**Comment by hazelnutsgz** [comment]
I enabled it, yo

**Comment by nareddyt** [comment]
Hi @hazelnutsgz, did you have any luck with this? I also cannot get envoy to output the cpu profile file.
