### ISSUE TITLE
wasm: plugin configuration is racey

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#13690]
Context: https://github.com/istio/istio/issues/28017

[Plugin configuration](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/wasm/v3/wasm.proto#L78) is applied every time xDS is loaded that references the same `root_id`. This is inherently racey if the same `root_id` is referenced in multiple places. It is also applied if the xDS is rejected, corrupting the existing plugin configuration state.

**Comment by PiotrSikora** [comment]
I'm working on this.

**Comment by kyessenov** [comment]
@PiotrSikora Can you share how you want to plan to fix this? I proposed a few options and not sure which one is the preference. I'm curious how we can make it work in the upcoming istio release.

**Comment by PiotrSikora** [comment]
Second option from https://github.com/istio/istio/issues/28017#issuecomment-713391694, i.e. create a new root context for each plugin configuration.

See those PRs: https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/78 and https://github.com/envoyproxy/envoy/pull/13753. Could you give them a try?

Note that those PRs are still WIP, and plugin instances are not garbage collected, but other than that it works fine in WasmVMs (I didn't do any testing with NullVMs, other that the fact that it's passing existing tests).

**Comment by PiotrSikora** [comment]
Thinking about this now, the existing PRs have one-to-many relationship between in-VM RootContext and Plugins/FilterConfigs, where `plugin_root_id` and `plugin_configuration` are used as the sharing key.

But perhaps it makes sense to make this relationship one-to-one, to simplify lifecycle and make the reasoning about what's configured in Envoy and what's available within WasmVM a bit more sane? What do you think?

**Comment by kyessenov** [comment]
I think that would have too much effect on existing plugins. The root context is used as a per-worker singleton already, so changing the semantics would change that. It's not easy to tell the performance cost of having many roots.

**Comment by kyessenov** [comment]
Confirmed this is not happening on master (istio/proxy and envoy). Extensions usually assumed eternal root, so they need to be fixed to clean up properly on termination. For example, telemetry should be pushed or it gets dropped.
