### ISSUE TITLE
Migrate Emscripten to native Bazel support

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#13720]
Emscripten recently gained native Bazel support, we should use it instead of the custom rules:
https://github.com/emscripten-core/emsdk/tree/master/bazel

**Comment by bianpengyuan** [comment]
@lizan I'd like to take a stab on this.

**Comment by lizan** [comment]
@bianpengyuan I doubt it will work well after taking a brief look there. It will introduce unnecessary bazel dependencies from rule_nodejs, and it hardcodes Linux x64 binaries which will break macOS (and also arm64 / Windows in future).

**Comment by PiotrSikora** [comment]
Could one of you report those issues to Emscripten folks? They should ship unusable rules, and we shouldn't need to maintain Emscripten rules in Envoy.

**Comment by bianpengyuan** [comment]
Created https://github.com/emscripten-core/emsdk/issues/650 to track this. Meanwhile, I am going to move wasm_cc_binary rule to proxy-wasm-cpp-sdk, so that it does not require importing envoy repo to use that.

**Comment by mattklein123** [comment]
I think this is done.
