### ISSUE TITLE
repokitteh /retest seems to be broken

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13725]
### description

/retest seems to no longer work, instead gives the message

```
Cannot retry non-completed check: envoy-presubmit, please wait.
```

**Comment by phlax** [comment]
also doesnt seem to cope with restarting a test that has been cancelled due to timeout

**Comment by lizan** [comment]
This is due to the [outage of AZP](https://status.dev.azure.com/_event/210657400) that doesn't report `envoy-presubmit` check status (but subchecks). #13744 should includes a workaround and for cancelled tests.
