### ISSUE TITLE
Question about how to use envoy Oauth2

### ISSUE THREAD

**Issue by hsuyuming** [envoyproxy/envoy#13736]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Question about how to use envoy Oauth2

*Description*:
I very want to learn how to use envoy's Oauth2 functionality. Is it possible can integrate with github Oauth or Azure AD Outh2 ? If yes, is someone can provide example let me understand how to use that.and I also not quite understand what if the sds_config I need to provide. I look at the test case, but not find any thing related.

I am not sure what this line mean:
credentials:
      client_id: foo
      token_secret:
        name: token
        sds_config:
          path: "/etc/envoy/token-secret.yaml"
      hmac_secret:
        name: hmac
        sds_config:
          path: "/etc/envoy/hmac.yaml"

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by rgs1** [comment]
Maybe related to #13637.

cc: @williamsfu99

**Comment by hsuyuming** [comment]
Thank you, i think it is similar

**Comment by williamsfu99** [comment]
@hsuyuming 
Did you find what you were looking for in the other thread?

**Comment by carlin-q-scott** [comment]
The documentation is wrong regarding the token and hmac. If you want to reference a file for the token and hmac, they have to be in separate files that look like this:

```yaml
resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  name: hmac
  generic_secret:
    secret:
      inline_string: g1iXBWBfGSIBgIyTcG699G/Zh+Ty20kW+BWiO6aYhwM=
```

The example "yaml file" provided for defining the credentials only works if it's defined in your envoy.yaml config file where the oauth filter is defined. 

Please fix the documentation. I spent probably 4 hours trying to figure out how to do this, and managed to figure it out after looking at https://github.com/envoyproxy/envoy/issues/13637#issuecomment-715536227
