### ISSUE TITLE
debugging opt binaries with symbols using DWARF/Fission

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#13738]
I've been unable to get a usable (non zero bytes) .dwp files for optimized build after #12569, so maybe docs can be improved around that. 

cc: @lizan @foreseeable

**Comment by lizan** [comment]
@rgs1 I think you missed some options from our `.bazelrc`. Make sure you have the following:

```
build:linux --fission=dbg,opt
build:linux --features=per_object_debug_info
```
