### ISSUE TITLE
Make OAuth scopes configurable

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#13766]
*Title*: Make OAuth scopes configurable

*Description*:
It's [currently hard-coded to `scope`](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/oauth2/filter.cc#L51) but the scopes can vary widely, e.g. see Github's OAuth scopes: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

cc @rgs1 @fishcakez @williamsfu99

**Comment by williamsfu99** [comment]
FYI you tagged a random William

**Comment by derekargueta** [comment]
🤦 woops, fixed

**Comment by Smirl** [comment]
I am getting `openid is required scope` from my IdP (actually a [locally running test one](https://hub.docker.com/r/qlik/simple-oidc-provider)).

`openid` is a required scope for `oidc`. Would be great to be able to specify them.

Is this filter intended to be used for oidc (i.e. propegating ID tokens, cookies, etc.) or only for oauth2 (subtle difference I know).

**Comment by williamsfu99** [comment]
@Smirl 
I don't see an issue running this filter with OIDC/SAML for enterprise apps, although I don't have any experience running the filter with any sort of SSO gateway to speak more on the subject. I would not recommend federating the access tokens for consumer apps though, as internal admins of the filter should be the ones controlling who can access what.

**Comment by andreyprezotto** [comment]
@Smirl I'm currently working on a fix to make the scope parameter configurable, and I'll open a pull request soon. Let you all know by posting it here.
In my local tests, I can see the cookies and Authorization header forwarded in the headers to the upstream service.
