### ISSUE TITLE
compression: support request compression

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#13779]
compression: support request compression

*Description*:
Currently the [compressor filter](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/common/compressor/compressor.cc) only supports _response_ compression.

On the other hand the decompressor filter is bidirectional, i.e., it supports _both_ request and response decompression.

In order to use envoy as a full biderectional compression solution, compression should be added on the request side. This would require adding compression on the `decode*` functions in the compressor filter. The decompressor filter could be used for inspiration.

**Comment by mk46** [comment]
Hi @junr03, I would like to work on this issue.

**Comment by junr03** [comment]
being worked in https://github.com/envoyproxy/envoy/pull/14302
