### ISSUE TITLE
x-request-id is being modified when using tracing

### ISSUE THREAD

**Issue by Brunomachadob** [envoyproxy/envoy#13774]
*Description*:
The issue is that even by simply adding an empty `tracing: {}`, Envoy is modifying the `x-request-id` that was sent in the request, changing the version from `4` to `9` 🤷‍♂️ 

I have noticed this before in our logs from another gateway we have, which contains this configuration, but I had no idea that `tracing` was the cause, yesterday by luck I managed to track down the problem to this property when enabling tracing for this new gateway.

I configured Envoy with the upstream cluster pointing to `postman-echo.com` which will return as response body, the request headers sent.

```bash
curl --location --request GET 'localhost:8080/headers' \
--header 'x-request-id: 968ea8f8-3806-45c9-8228-8d3dde5df3b4' \
--header 'x-another-id: 968ea8f8-3806-45c9-8228-8d3dde5df3b4'
```

```json
{
    "headers":{
        "x-forwarded-proto":"http",
        "x-forwarded-port":"80",
        "host":"localhost",
        "x-amzn-trace-id":"Root=1-5f97d990-6daf0ed27c296cad5e916f6c",
        "content-length":"0",
        "user-agent":"curl/7.64.1",
        "accept":"*/*",
        "x-request-id":"968ea8f8-3806-95c9-8228-8d3dde5df3b4",
        "x-another-id":"968ea8f8-3806-45c9-8228-8d3dde5df3b4",
        "x-envoy-expected-rq-timeout-ms":"15000"
    }
}
```

`x-request-id` change:
```diff
-968ea8f8-3806-45c9-8228-8d3dde5df3b4
+968ea8f8-3806-95c9-8228-8d3dde5df3b4
```

My use case is the one below, as I need to copy the `x-request-id` as a tag:
```yaml
tracing:
  custom_tags:
      - tag: x-request-id
          request_header:
          name: x-request-id
```

But as you can try it out here, only by adding an empty `tracing: {}` the problem already happens.

*Note*:
The problem only happens with the `x-request-id`, as you can see I used also a `x-another-id` and that one did not change.

*Versions I tried*:
- v1.16-latest
- v1.15.0

*Repro steps*:
I created a gist with the problem here: https://gist.github.com/Brunomachadob/d998a59c27ada3cacfafa95d2f3ecd9f

Let me know if you need me to run it with `envoy_collect`, I tried a few times here but failed, guess I'm doing something wrong with the docker setup for it.

**Comment by yanavlasov** [comment]
It looks like this is how stable tracing IDs work. @mattklein123 for more info

**Comment by mattklein123** [comment]
See the docs https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing and https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-request-id.

Better docs appreciated, but this is "stable sampling" kicking in. You might be able to disable this by controlling random sampling. This is also why we made this component extensible, but there is no other implementation upstream. cc @euroelessar

**Comment by Brunomachadob** [comment]
Thanks for the reply...

But what couldn't understand is why the value is being mutated.
I configured Envoy with 
```yaml
generate_request_id: true
preserve_external_request_id: true
```

So I guess it should obey my configuration and if the header was provided, it should use it as it is.

My use case is related to PSD2 regulations for Open Banking and specifically about the Berlin Group specification, where every party calling our gateway will provide an UUIDv4 `x-request-id` header, and we should be able to track everything they send to us by it.

But the problem is they ask us to provide details about `968ea8f8-3806-45c9-8228-8d3dde5df3b4` and then we need to search on our services by `968ea8f8-3806-95c9-8228-8d3dde5df3b4`

**Comment by Brunomachadob** [comment]
Oh, okay, now after navigating [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-id-extension) I saw it
```
If not set, Envoy uses the default UUID-based behavior:
* Request ID is propagated using x-request-id header.
* Request ID is a universally unique identifier (UUID).
* Tracing decision (sampled, forced, etc) is set in 14th byte of the UUID.
```

**Comment by Brunomachadob** [comment]
So the decision of sampling and the actual sampling happens in different points in time?
You first need to tag the request that you want to sample with something, then later in time you check that tag in order to sample it?

**Comment by Brunomachadob** [comment]
Maybe I can try to come up with an extension based on `UUIDRequestIDExtension` that actually does the same, but specifically for the `getTraceStatus` & `setTraceStatus` uses a different header to keep track of the sampling.

**Comment by Brunomachadob** [comment]
Closing this one in favor of the other issue that I linked here.
