### ISSUE TITLE
Docs are published before Docker images - leaving dangling links

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#13778]
### description

raised by a user in the slack channel...

when docs are published, they publish links/instructions for a docker image `envoy-dev:SHA` with the `sha` corresponding to the last commit on master

unfortunately when the docs are published the Docker images are still cooking, and the links dont work (for maybe an hour or so)

as we are constantly updating master, i would imagine that we are quite frequently publishing links that dont work in the latest docs.

**Comment by mattklein123** [comment]
cc @lizan I think it would be reasonable to split out docs publish from docs CI and do that after docker publish?

**Comment by lizan** [comment]
yeah that sgtm.
