### ISSUE TITLE
Incorrect error responses for large HTTP POST request bodies when routing through Akamai

### ISSUE THREAD

**Issue by jphx** [envoyproxy/envoy#13781]
My organization is running into a problem for HTTP POST requests that are routed through the Akamai content delivery network when the server returns a response without reading the entire request body.  The circumstances where this is a problem are the following:

1. The client does _not_ include the `Expect: 100-Continue` request header, or
2. The client does include the `Expect: 100-Continue` request header, and the server-side triggers a `100 Continue` response, but doesn't consume the entire request body before returning a final response.

Here are some sample situations when such "early responses" occur:

1. If the client didn't send valid authentication credentials, or sends credentials that aren't sufficient for the requested action, the Envoy external authorization server might trigger a `401 Unauthorized` or `403 Forbidden` response.
2. If a rate limiter service decides the request shouldn't be allowed to proceed, it might trigger a `429 Too Many Requests` response from Envoy.
3. After examining the request path, an upstream service might reject the request with a `404 Not Found` error.
4. The upstream service might examine the `Content-Length` header and see that the size of the request body the client is sending is too large, triggering a `413 Request Entity Too Large` error.
5. If the `Content-Length` header wasn't specified with the request, the upstream service will start reading the request body.  But at some point, the upstream service might decide the request body is too large and respond with `413 Request Entity Too Large` without consuming the remainder of the request body.  This case is a little different than the others because it can cause a problem even when the `Expect: 100-Continue` header is specified by the client, since the upstream service will reply with a `100 Continue` response before it starts to read the request body.

The first two cases listed above are examples of Envoy's "local reply" processing, while the others are a result of how the upstream service processes the request.

You may wonder why any of this is a problem.  After all, plenty of HTTP clients know how to use a response that is returned before the client has completed writing the request body.  For example, `curl` does.  But not all clients are smart enough to handle this in the preferred way.  (I hesitate to say "correctly" since I can't find any definitive advice about this situation in the HTTP specification.)  Some clients behave more-or-less like the following:

1. Open socket to server.
2. Write the HTTP request headers (assume that `Expect: 100-Continue` is _not_ included) and the HTTP request body.  If a write error occurs during this processing, raise an error.
3. Once the HTTP request is completely written, read from the socket to find a response.

An example of an HTTP "client" that's not as smart as we would like it to be is the [Akamai](https://www.akamai.com/) content delivery network proxy.  Our setup uses the Akamai CDN in between our clients and our Envoy proxy.

    client <--> Akamai <--> Envoy <--> Upstream service

With this setup, a client that submits a POST request with a large request body and no `Expect: 100-Continue` header always gets a `503 Service Unavailable` error from Akamai instead of the error that it _should_ be getting (401, 403, 404, 413, 429) due to Akamai's apparent inability to handle early HTTP responses.  The Akamai proxy client _appears_ to be implemented using the simple steps above, and when Akamai gets an error writing the request body, it returns a 503 response to the client instead of checking first to see if a response from the server is already available.  We've tried setting a large `delayed_close_timeout` in  Envoy, but that just causes the request to block longer before the 503 is received.  We can probably avoid this symptom by enabling request buffering in Envoy, but since the supported request bodies can be extremely large, and we want to handle lots of concurrent requests, the increased Envoy memory usage would make this impractical.  Besides, we much prefer to use Envoy as a streaming proxy.

Our efforts to get the Akamai proxy to improve have been unsuccessful.  So I'm wondering if there's something that can be done on the Envoy side.  Would it be possible to configure Envoy to read and discard remaining request body bytes when returning an error, if `Expect: 100-Continue` was not specified on the request, or if request processing has already proceeded to the point where a `100 Continue` response was already returned?  This processing would have to be done during Envoy's local reply processing as well as after the request is routed to the upstream service.

Assuming there's no magic configuration that's going to get request bodies to be consumed, would it be possible to implement a filter that would perform this processing?  I'm not terribly familiar with the capabilities of filters.

Thanks for any advice!

**Comment by yanavlasov** [comment]
I do not think there is anything you can do with Envoy's configuration.
However I believe the filter is possible, it can delay response header encoding until it sees the request stream has ended. It would lead to a lot of wasted bandwidth though.
@alyssawilk @mattklein123 @antoniovicente  for any additional comments.

**Comment by antoniovicente** [comment]
As far as I know early error responses wiith "Connection: Close" headers is a valid way to handle these POSTs.  You should encourage Akamai to improve their implementation.

The work around that you describe involving a filter that discards the rest of the body when the body is below some size threshold with a timeout would likely work most of the time, but won't work for errors generated before HTTP parsing is complete or the if there's no configured route.  The filter pipeline is not created for these early errors.

**Comment by mattklein123** [comment]
You could use the buffer filter with some max size. This is very wasteful for bandwidth and memory, but might work for you. Note that this will not cover *all* early return cases per @antoniovicente but would cover most of them.

**Comment by jphx** [comment]
Thanks for the advice.  We considered using buffering, but some services support extremely large request bodies, so it didn't seem practical for us due to the increased memory usage.  Thanks also for the observations that a filter wouldn't cover all situations.  That hadn't occurred to me.  I don't really _want_ to write a new filter to deal with this, and the fact that it wouldn't cover all situations gives me ~an excuse~ a reason not to.

**Comment by chrskrchr** [comment]
@jphx - thank you for capturing the specifics of this problem in such great detail.  My organization is running into the exact same issue at the moment, and your post gave us a hint that we might be able to work around it by requiring clients to provided an `Expect: 100-Continue` header on the request.  We're testing that workaround now.

We're also engaged with Akamai support to see if this is something they might be able to address on your end.  Just curious to know if you'd been provided with any more specific workarounds by Akamai, or if you went with a workaround and have since moved on...

**Comment by jphx** [comment]
@chrskrchr We've been in contact with Akamai also.  They've been investigating and have said they _think_ they may be able to provide a configuration option to help with this, but they haven't finished their work yet.  If/when I learn more, I'll update this issue.  So far our best workaround is to encourage the use of the `Expect: 100-Continue` header.

**Comment by chrskrchr** [comment]
Thanks, @jphx.  We'll do the same.

I also want to point out to anyone else that stumbles across this thread to pay special attention to the case used in the `Expect: 100-Continue` header value.  The value must be `100-Continue` for Akamai to process it correctly.  [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.1.1) states that this value is case-insensitive, but passing `100-continue` as referenced in the RFC won't triggered the desired behavior in Akamai.
