### ISSUE TITLE
metrics service: reduce amount of time queries?

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#13782]
*Description*:
Metrics service requests a timestamp for each metric it has to push, once for [counters](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc#L52) and [gauges](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc#L68) and [twice](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc#L85) for [histograms](https://github.com/envoyproxy/envoy/blob/master/source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc#L101). I assume this can be very expensive when having lots of metrics.
Would it be correct to get a single timestamp when it receives the metric snapshot and use that timestamp across all metrics?

This would make sense if the metric snapshot is really a precalculated immutable snapshot.

**Comment by ramaraochavali** [comment]
Yes. I think that makes sense for metrics service - MetricSnapshotImpl having the time when snapshot was created and using it across all metrics.
