### ISSUE TITLE
Add support for printing stack traces when exception is unhandled

### ISSUE THREAD

**Issue by jamessynge** [envoyproxy/envoy#1378]
This isn't a feature that can be provided in a portable fashion, but it very useful where the compiler/runtime don't unwind the stack before calling the std::terminate_handler when dying.

**Comment by mattklein123** [comment]
I think this is probably as simple as just printing a backtrace inside of an std::terminate handler. cc @dnoe

**Comment by dnoe** [comment]
Normally that wouldn't work but I think it will because we're using the custom pthread wrapper instead of std::thread.

**Comment by gumpt** [comment]
I’d be interested in taking this if it isn’t done and no-one is actively working on it.

**Comment by dnoe** [comment]
I don't think anyone is working on it. PRs would definitely be welcome!
