### ISSUE TITLE
Some requests were dropped by envoy?

### ISSUE THREAD

**Issue by NonStatic2014** [envoyproxy/envoy#13790]
*Title*: *Some requests were dropped by envoy?*

*Description*:
In our envoy, we log twice: 

1. at very beginning when request arrives, we log a unique id in the request header in the lua filter;
```lua
local some_id = request_handle:headers():get("some-id")
if some_id ~= nil then
  request_handle:logInfo("some-id: "..string.sub(some_id , 1, 36))
else
  request_handle:logInfo("some-id: -")
end
```
2. the access log, including the same request header.

After run a while, we see some of requests could only be found in the #1 log above. Is there any clue to debug this issue? Currently the issue only repro in the prod environment, which may not be ok to turn on tracing log. 

Thanks!

**Comment by dio** [comment]
@NonStatic2014 probably the access logs are not flushed yet?

**Comment by NonStatic2014** [comment]
After debugging into the network setup, it was due to the access log was dropped by our logging system.
