### ISSUE TITLE
Route specific HTTP Local Rate limiter not working

### ISSUE THREAD

**Issue by gargnupur** [envoyproxy/envoy#13805]
*Title*: *Route specific HTTP Rate limiter not working*

*Description*:
Using new Http Local Rate Limiter(https://github.com/envoyproxy/envoy/pull/13395) and it's working at the global config but not at route specific one.

I added debug logs in the Local Rate Limiter Code and it seems to reach the generateStats and FilterConfig methods but not the runtime decodeHeaders method.

*Repro steps*:
Sample config:
`filter_chains:
- filters:
  - name: http
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: client
      http_filters:
      - name: envoy.router
      route_config:`
        name: client
        virtual_hosts:
        - name: client
          domains: ["*"]
          routes:
          - name: client_route
            match: { prefix: / }
            route:
              cluster: server-outbound-cluster
              timeout: 0s
            typed_per_filter_config:
              envoy.filters.http.local_ratelimit:
                "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                stat_prefix: local_rate_limit
                token_bucket:
                  max_tokens: 1
                  tokens_per_fill: 1
                  fill_interval: 600s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'`

**Comment by rgs1** [comment]
@gargnupur hmm that's pretty much how we use it. Can you share your listener config too?

**Comment by rgs1** [comment]
@gargnupur can you share the generated stats under the `local_rate_limit` prefix?

**Comment by gargnupur** [comment]
Everything is 0...

# TYPE envoy_local_rate_limit_http_local_rate_limit_enabled counter
envoy_local_rate_limit_http_local_rate_limit_enabled{} 0

# TYPE envoy_local_rate_limit_http_local_rate_limit_enforced counter
envoy_local_rate_limit_http_local_rate_limit_enforced{} 0

# TYPE envoy_local_rate_limit_http_local_rate_limit_not_enabled counter
envoy_local_rate_limit_http_local_rate_limit_not_enabled{} 0

# TYPE envoy_local_rate_limit_http_local_rate_limit_ok counter
envoy_local_rate_limit_http_local_rate_limit_ok{} 0

# TYPE envoy_local_rate_limit_http_local_rate_limit_rate_limited counter
envoy_local_rate_limit_http_local_rate_limit_rate_limited{} 0

**Comment by rgs1** [comment]
Note that you still need to add the filter, with an empty-ish config, to the list of http filters in the http conn manager config.

**Comment by gargnupur** [comment]
Thanks.. That worked!

I see in the documentation now that you have included an empty one for HTTPConnectionManage, but can we make this clear that this is required. Also, why is this needed?

**Comment by rgs1** [comment]
It's needed because you need to declare up front your HTTP filters (order matters). You can't enable a filter via a per route config (in what order would it be evaluated?).

**Comment by gargnupur** [comment]
Got it thanks much!

**Comment by rgs1** [comment]
If you think docs could improve, please send a PR. Happy to review!
