### ISSUE TITLE
Support dynamic host rewrite and Proxy-Authorization Header injection via SDS in TCPProxy tunneling

### ISSUE THREAD

**Issue by larryrun** [envoyproxy/envoy#13809]
Hi team,

We use the TCPProxy filter to tunneling TCP traffic to upstream services. The upstream service is also an Envoy, it does the authn/authz check and then forward the packets to the real port. 

When a client calls a service, the traffic flow looks like :
[Client(call 2.2.2.2:80)] -> [Iptables redirect to \:8000] -> [ClientSide Envoy TCPProxy (listens on 8000, Will do tunneling based on the client request: 2.2.2.2:80)] -> [Iptables redirect to \:9000] -> [ServiceSide Envoy(listens on 9000, forwards to 2.2.2.2:80)] -> [Service(listens on 80)]

Problems we are facing:
- The [TCPProxy tunneling config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#envoy-v3-api-msg-extensions-filters-network-tcp-proxy-v3-tcpproxy) only supports a hard coded host, but in our case the upstream endpoint is depending on the client request. so it will be helpful if this host field can be configured to a dynamic value, like ```%DOWNSTREAM_LOCAL_ADDRESS%```
- An additional Proxy-Authorization header need to be injected

To address the above difficulties. we configured a second listener(just like [this example](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-tcp-over-http-2) in the offical doc) in the client side Envoy with HTTP filters, and redirect the packets sent from TCPProxy filter to this listener. And use 
- ```request_headers_to_add```=```%DOWNSTREAM_LOCAL_ADDRESS%``` to add the Host(\:authority) Header;
- ext_authz filter to inject the Proxy-Authorization header (the value is a token). 

So we are wondering, is this the right way to achieve our requirement in your opinion? We see there are some improvements can be made:
- As the second listener is needed, extra unnecessary packets are generated, this seems to impact the TCP performance.
- The token injection is implemented by using an ext_authz filter, not via an SDS which looks like a more appropriate way of handling token values

One option that came to my mind is that, allowing an HTTP filter chain to be configured for the TCPProxy Tunneling's HTTP CONNECT request, so that we can add more sophisticated HTTP logic. 

For the token injection, I found another helpful [feature request#6654](https://github.com/envoyproxy/envoy/issues/6654) that was created long time ago. Is there any plan for it?

What do you guys think?
Thanks for your hard working and this great project!

**Comment by yanavlasov** [comment]
I think this is a problem that @lambdai is trying to solve as well. @alyssawilk for any more comments as well.

**Comment by alyssawilk** [comment]
Hm, I like the idea of allowing a filter chain for tcp tunneled over HTTP.
It smells more like upstream filters to me, which would imply using the work @snowp is doing there.
Alternately a simpler but hacker solution (which wouldn't go upstream but you could use in the interim)  I think you could use pluggable upstreams (almost landed -see https://github.com/envoyproxy/envoy/pull/13548) to put your own business logic in your own custom http-over-tcp handler.

**Comment by larryrun** [comment]
@alyssawilk @yanavlasov thanks for your reply!
I'll check @snowp and @lambdai 's work, and I'll also see how the pluggable upstreams can help.
And for the token via SDS, any ideas for this [feature request#6654](https://github.com/envoyproxy/envoy/issues/6654) ?

**Comment by cortex93** [comment]
Hi @larryrun, we are trying to build a dynamic upstream TLS proxy configuration. We have a working static solution here https://gist.github.com/cortex93/6d7cd9738b077d0447ab891cbacd0d5e but we need to get rid of `host_rewrite_literal` in HCM and `hostname` in tunneling_config.
Use case is `Client --(http://dynamic.target/)--> envoy L1 --(TLS Upstream)--> envoy L2 --(TcpProxy passthrough to https://corporate.proxy)--> Corporate Proxy --(CONNECT dynamic.target)--> dynamic.target`
It seems that you succeed in some way to bypass the limitation of TcpProxy. Do you think it can be adapted ?

**Comment by cortex93** [comment]
@alyssawilk regarding my previous comment, would you mind reopen this ?

We should be able to do TLS upstream with a non statically configured hostname

**Comment by scrocquesel** [comment]
There is an ongoing discussion at https://github.com/envoyproxy/envoy/issues/13809

**Comment by scrocquesel** [comment]
There is an ongoing discussion at https://github.com/envoyproxy/envoy/issues/18838

**Comment by scrocquesel** [comment]
@lambdai any ongoing work around evaluating the hostname of tunneling_config ? Should another issue be created ?

**Comment by scrocquesel** [comment]
Still not fixed

**Comment by scrocquesel** [comment]
@lambdai any progress on this one ?

**Comment by scrocquesel** [comment]
dynamic hostname in tcpproxy is being adressed by https://github.com/envoyproxy/envoy/issues/19612

**Comment by jewertow** [comment]
Injecting Proxy-Authorization was addressed in #38398. [Here](https://github.com/jewertow/envoy-playground/blob/master/inject-proxy-authorization/envoy.filters.http.upstream.credential_injector/envoy.yaml) you can see example configuration which sets `Host` header based on SNI and injects `Proxy-Authorization` from a secret.
