### ISSUE TITLE
The size of the envoy binary built from source code is extrordinary large

### ISSUE THREAD

**Issue by hustshawn** [envoyproxy/envoy#13815]
*Title*: *One line description*

*Description*:
Hi, I tried to build the code but find the size of the binary is extremely large. I used the script inside of `ci` directory, and built with options `bazel.release.server_only`. Anyone knows why? and where I did wrong?

```
git checkout release/v1.15
ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
```
The size of binary goes to 1.2GB, is it normal? I expect it should be no more than 100MB as I saw in the istio-proxy.
```
root@ip-172-31-45-102:~/build/envoy/source/exe# ls -ltrah
total 1.2G
drwxr-xr-x 3 root root 4.0K Oct 29 08:03 ..
drwxr-xr-x 2 root root 4.0K Oct 29 08:36 .
-r-xr-xr-x 1 root root 1.2G Oct 29 08:54 envoy
```

The machine I used for building the source
 
```
$ cat /etc/os-release 

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yanavlasov** [comment]
I think this build includes debug symbols in the binary file. You can define `BAZEL_BUILD_OPTIONS=--strip=always` to build binary without symbols.

**Comment by hustshawn** [comment]
Hi @yanavlasov , thanks for your suggestion. I tried with the `BAZEL_BUILD_OPTIONS`, but the result is still 1.1.G

**Comment by lizan** [comment]
@hustshawn you should be able to find stripped binary at `linux/amd64/build_release_stripped/envoy` without any option. The unstripped one is at `linux/amd64/build_release/envoy` which could be 1+GB

**Comment by hustshawn** [comment]
@lizan Yes. you are right. I find the stripped binary even though the path is not exactly the same as mine. I am able to find it by searching for `build_release_stripped` path pattern. Thank you so much.
