### ISSUE TITLE
Invalid config on Specifying gRPC Access Log Service to V3

### ISSUE THREAD

**Issue by rohitagg2020** [envoyproxy/envoy#13813]
*Title*: *Specifying GRPC Access Log Service to V3 crashes Envoy.*

*Description*:
>When mentioning to use the V3 version for GRPC Access Log Service, envoy crashed. Instead of crashing, it should start sending the data on V3 apis.
Envoy Documentation mentions that we can specify which version to use for gRPC ALS by specifying *transport_api_version*.
https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/grpc/v3/als.proto.html?highlight=common_config#envoy-v3-api-msg-extensions-access-loggers-grpc-v3-commongrpcaccesslogconfig

*Config*:
> Following is the Config used to specify the filter:
   ```filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: test_cluster}
          http_filters:
          - name: envoy.filters.http.router
          access_log:
          - name: envoy.access_loggers.http_grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
              common_config:
                log_name: egressenvoyaccesslog
                grpc_service:
                  envoy_grpc: 
                    cluster_name: accessLogService
                transport_api_version: V3
```

*Logs*:
> Logs mention that Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(common_config) transport_api_version: Cannot find field.) has unknown fields even though the documentation mentions that it is mandatory to specify if we want to use the Version 3.

```
[2020-10-29 06:40:40.492][1][critical][main] [source/server/server.cc:96] error initializing configuration '/etc/envoy/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(common_config) transport_api_version: Cannot find field.) has unknown fields
[2020-10-29 06:40:40.492][1][info][main] [source/server/server.cc:616] exiting
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(common_config) transport_api_version: Cannot find field.) has unknown fields
```

**Comment by dio** [comment]
@rohitagg2020 I think it is not crashing, but as the error message suggests: "Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(common_config) transport_api_version: Cannot find field.) has unknown fields
"   

What is your envoy binary version? I believe this is added from v1.15.0.

**Comment by jdfcio** [comment]
Did you get to the bottom of this @rohitagg2020 ? I'm seeing someting similar here;

https://github.com/envoyproxy/envoy/issues/20773
