### ISSUE TITLE
CodeQL-Build fails.

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#13811]
CodeQL-Build fails due to out of space.
  Ref [#13671](https://github.com/envoyproxy/envoy/pull/13671/checks?check_run_id=1317196107) 
```
 Oops! A fatal internal error occurred.
  com.semmle.util.exception.CatastrophicError: An error occurred during the evaluation of Operand::NonPhiMemoryOperand::hasDefinition#3#fff/3@b0e47a
  The RA to evaluate was:
      {1} r1 = CONSTANT(unique int)[1]
      {2} r2 = JOIN r1 WITH Operand::NonPhiMemoryOperand::hasDefinition#3#fff#join_rhs AS R ON FIRST 1 OUTPUT R.<1>, R.<2>
      {3} r3 = JOIN r2 WITH Operand::NonPhiMemoryOperand#3#fff_120#join_rhs AS R ON FIRST 2 OUTPUT r2.<0>, r2.<1>, R.<2>
      {3} r4 = JOIN r3 WITH SSAConstruction::Cached::getMemoryOperandDefinition#2#ffff@staged_ext AS R ON FIRST 2 OUTPUT r3.<2>, R.<3>, R.<2>
      return r4
  
  (eventual cause: IOException "No space left on device"
```

**Comment by yanavlasov** [comment]
It has been working for recent PRs. It could be that /retest on your PR did not rebuild codeQL. You can try adding an empty commit to your PR to kick off the codeQL rebuild.

**Comment by yanavlasov** [comment]
Please re-open if this is still a problem.

**Comment by mk46** [comment]
Hi @yanavlasov, still have the same problem. Do you have any idea about 'retest-circle' that isn't working for all Github user or deprecated [CONTRIBUTING.md](https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md)?)

**Comment by phlax** [comment]
@mk46 feel free to PR to remove the circle reference, its no longer used/available

**Comment by mk46** [comment]
@phlax Done [#13824](https://github.com/envoyproxy/envoy/pull/13824).
