### ISSUE TITLE
INFO level logs for dropped requests due to underscores in the name

### ISSUE THREAD

**Issue by Brunomachadob** [envoyproxy/envoy#13833]
*Description*:
I wonder if the level `INFO` would be more suitable for when this important consequence happens.
We usually don't have low log level as `debug` in production environments.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/f7f870917bd25dc8200bcce8c259bd588cafb559/source/common/http/http1/codec_impl_legacy.cc#L1052

**Comment by yanavlasov** [comment]
This may be very noisy. I think if you need to log the headers that were dropped (or caused 503) you may want to write a custom filter. Arguably this functionality should have been implemented as a filter to begin with.

**Comment by guoruijing** [comment]
admin can look statistics to find out the issue so that debug level should be ok.
    stats_.dropped_headers_with_underscores_.inc();

**Comment by Brunomachadob** [comment]
The problem is that I have an open gateway that is called by dozens of other companies integrating with us. 
I have a dashboard with this metric in place, but this does not tell us anything else other than "a fail happened" and nothing else to help me understand where it came from, path and this sort of things.

But that is fine. This was something I was wondering if this should be really debug or we could bump the level.
Recently we decided to change our behaviour to drop the underscore headers, so we are back to safety again, no requests dropped.

But we are also in the dark in relation to which headers were dropped, but that is not important.

I guess we can close this one.
