### ISSUE TITLE
Support consuming filesystem xDS via {binary protobuf, YAML, JSON}

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1384]
Unlike the gRPC delivery of the v2 APIs, we are initially only supporting JSON translation of the protobufs on the filesystem. We should have a flexible mechanism for supporting {binary protobuf, YAML, JSON} consumption.

**Comment by htuch** [comment]
This should apply to the bootstrap proto as well. In addition, we should perhaps allow specifying the entire bootstrap proto on the command-line, as it's small and some deployments will benefit from this form of orchestration.

**Comment by htuch** [comment]
Updated to reflect that we will not support ASCII PB, since this is not standardized. YAML will be the preferred humand-readable variant of the configuration.

**Comment by mattklein123** [comment]
I think this is done. Closing.
