### ISSUE TITLE
Extend PerfAnnotationContext with begin and end events.

### ISSUE THREAD

**Issue by rojkov** [envoyproxy/envoy#13860]
*Title*: *Extend `PerfAnnotationContext` with begin and end events.*

*Description*:
The current interface of PerfAnnotationContext allows easy recording of durations for a region of code inside a single lexical scope with `PERF_OPERATION` and `PERF_RECORD` annotations. But sometimes it might be useful to record durations between events happening in different scopes, e.g. how long it takes to destroy an `ActiveTcpConnection` after its corresponding `ActiveStream` has been destroyed (given they are 1-to-1).

I'd like to propose two additional annotations `PERF_BEGIN(category, description)` and `PERF_END(category, description)` asserting that a closing `PERF_END` always happens after `PERF_BEGIN`.

**Comment by antoniovicente** [comment]
Possible concern: ending up with an unbounded number of open perf measurements.  We may want to consider creating an RAII object that starts perf collection on construction and stops at destruction time to handle the case you describe.

**Comment by jmarantz** [comment]
@rojkov sgtm. go for it.

@antoniovicente an RAII implementation is what we have now: https://github.com/envoyproxy/envoy/blob/3a6e4a26480721207799c502c666874cc8b3784b/source/common/common/perf_annotation.h#L163

It is just wrapped by macros so we can leave it in production code and give it zero cost when compiled out.

**Comment by antoniovicente** [comment]
> @rojkov sgtm. go for it.
> 
> @antoniovicente an RAII implementation is what we have now:
> 
> https://github.com/envoyproxy/envoy/blob/3a6e4a26480721207799c502c666874cc8b3784b/source/common/common/perf_annotation.h#L163
> 
> It is just wrapped by macros so we can leave it in production code and give it zero cost when compiled out.

I assume that the cross scope version would need to persist the object somewhere.

**Comment by rojkov** [comment]
> I assume that the cross scope version would need to persist the object somewhere.

Yes. In `PerfAnnotationContext` I guess which is a singleton.

**Comment by jmarantz** [comment]
We'd have to persist a little more than that: specifically the start-time of the operation, so you could subtract that off of the end-time when you record.
