### ISSUE TITLE
lb: Add custom consistent hashing key for Endpoints

### ISSUE THREAD

**Issue by inf-rno** [envoyproxy/envoy#13862]
*Title*: Add custom consistent hashing key for Endpoints

*Description*:
This API change comes out of the discussion in https://github.com/envoyproxy/envoy/pull/13656. Which tries to address the original problem in #9074 that I tried to solve via #10233. The core of the problem is the need to have a semantic name for Endpoints in a cluster that identify it uniquely without piggy backing things like hostname or resolved address which can still change for the same semantic endpoint. e.g.: A redis which is migrated to different clusters etc. will have a different URL/IP address but contains the same data and is expected to be used in the same way by clients. But because the consistent hashing depends on hostname/address they will be rehashed and the hash rings/table would no longer be consistent.

In https://github.com/envoyproxy/envoy/pull/13656, I proposed a more generic solution perhaps using something like a `hash_key` in [MetadataEnvoyLbKeyValues](https://github.com/envoyproxy/envoy/blob/master/source/common/config/well_known_names.h#L41) of [LbEndpoint](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-lbendpoint) so the lb can use that to determine the hash key? Or it could be part of the [Endpoint](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-endpoint) object like `hostname` is (I think that is being used for something like this even though it doesn't have to resolve to anything).

I prefer the metadata based solution.

**Comment by inf-rno** [comment]
cc @mattklein123

**Comment by inf-rno** [comment]
bump

**Comment by mattklein123** [comment]
@inf-rno sorry what are you looking for? The proposal sounds reasonable to me.

**Comment by inf-rno** [comment]
Oh sorry. I was just looking for approval of the proposal as well. I will tackle this next. Thank you!

**Comment by vanhtuan0409** [comment]
May I know the status of this PR?
