### ISSUE TITLE
The design of tcp_proxy

### ISSUE THREAD

**Issue by hazelnutsgz** [envoyproxy/envoy#13879]
I just checked the source code of how envoy implements the tcp_proxy, and find that after receiving the data from downstream, it would copy the data from read_buffer to write_buffer ```write_buffer_->move(data);``` (internal is ```memcpy(dest, data, copy_size);```). Here are 3 questions I didn't figure out:

1. Why do we need the time-consuming data copy? Is that because we need modify the content of buffer?
2. If so, In what scenario would the envoy modify the content in the context of tcp_proxy?
3. Could **copy on write** improve the performance of this situation?

Thanks.
@brian-pane

**Comment by mattklein123** [comment]
cc @ggreenway @antoniovicente 

Move doesn't actually copy in cases of large slices. Modification can happen via interim filters.

What all of that said, we have discussed recently the potential concept of a CoW buffer with slicing capabilities, but would need to figure out whether the complexity is worth the perf gain depending on the use case.

**Comment by antoniovicente** [comment]
write_buffer write_buffer_->move(data); does a move, does not copy the data.

**Comment by hazelnutsgz** [comment]
> write_buffer write_buffer_->move(data); does a move, does not copy the data.

When I traced the  implementation of ```write_buffer write_buffer_->move(data)```, and find that in ```void OwnedImpl::coalesceOrAddSlice(SlicePtr&& other_slice)```, if the requirement of ```other_slice->canCoalesce() && !slices_.empty() && slice_size < CopyThreshold &&
      slices_.back()->reservableSize() >= slice_size)``` met, it will make the real data copy, say, at https://github.com/envoyproxy/envoy/blob/master/source/common/buffer/buffer_impl.h#L156, envoy would launch```memcpy``` to do the data copy.

So is that the meaning of "Move doesn't actually copy in cases of large slices"?

Thanks.

**Comment by antoniovicente** [comment]
The key condition is "slice_size < CopyThreshold".  CopyThreshold is currently 512 bytes.

Copies are done to coalesce small fragments only.  The reader side of the connection attempts to read multiples of 16KB and push that through the filter pipeline.  The typical size of blocks moved between buffers is about 20KB due to some quirks of the buffer implementation.

**Comment by hazelnutsgz** [comment]
> The key condition is "slice_size < CopyThreshold". CopyThreshold is currently 512 bytes.


Yes, this one makes a lot of sense, I was wondering whether 512 a randomly set number or a result conducted by a lot of experiments.


> Copies are done to coalesce small fragments only. 


What's the intuition behind this design? Given that large packet we dont need real copying, why do we need to copy small fragments?

Thanks for you help.
