### ISSUE TITLE
dubbo_proxy parse hessian missing some case in switch 

### ISSUE THREAD

**Issue by serverglen** [envoyproxy/envoy#13913]
- HessianUtils::peekLong missing case 0xeb、0xec、0xed、0xfc、0xfd
- HessianUtils::peekInt missing case 0xcc

**Comment by zyfjeff** [comment]
At present, the implementation of Hessian2 in the Envoy has been poorly completed. We plan to open the internal hessian2 code and then replace the implementation of Hessian2 in the Envoy.

**Comment by serverglen** [comment]
> At present, the implementation of Hessian2 in the Envoy has been poorly completed. We plan to open the internal hessian2 code and then replace the implementation of Hessian2 in the Envoy.

@zyfjeff Thank for your reply, I communicated with you two weeks ago. you open the internal hessian2(refactor) code until the end of the year at least, I understand that this PR does not conflict with your refactoring code, because this is really a bug
