### ISSUE TITLE
grpc-json-transcoder: Filter replaces the last colon in the path by slash

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#13920]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
Have an envoy transcoding config with `HttpRule{post: "/a/{arg=**}"}`.
Send request with `:path` header set to `/a/b:c:d`.

Expected: `arg` value in request message is set to `b:c:d`.
Actual: `arg` value in request message is set to `b:c/d`.

*Theory*:
Underlying `grpc-httpjson-transcoding` library treats the last colon in path in a special way declaring everything after that as a "verb":
https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/faf8af1e9788cd4385b94c8f85edab5ea5d4b2d6/src/include/grpc_transcoding/path_matcher.h#L339-L345

**Comment by lizan** [comment]
cc @qiwzhang can you get more clarification on this spec re: path matcher? https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L224-L231

**Comment by qiwzhang** [comment]
Yes,  Google http_template supports custom verb which is the last portion in the path; e.g. `/path:verb`.   But the way we handle it is not right, hence it is the bug.

Here is the correct [way](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/path_matcher.h#L345) of handling it.

We should remember a list of custom verbs that configured.   If and only if the last path segment is one of them,  we replace it with "/".   Here we just blindly replace it.

The change in https://github.com/envoyproxy/envoy/pull/13921  is wrong.

**Comment by euroelessar** [comment]
@qiwzhang 
So it's a bug in [grpc-httpjson-transcoding](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/faf8af1e9788cd4385b94c8f85edab5ea5d4b2d6/src/include/grpc_transcoding/path_matcher.h#L335)?
I can send a path to that repo to copy behavior from [api_manager](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/path_matcher.h#L345).

**Comment by qiwzhang** [comment]
Yes, it is a bug.  In the grpc proto,  if we have:

a) option.http.rule {
    get: /foo/{x=**}:d
}

b) option.http.rule {
    get: /foo/{x=**}
}

for path = /foo/a:b:d   

for a) x=a:b  
for b) x=a:b:d

**Comment by qiwzhang** [comment]
If you like, I can help to fix this.

**Comment by euroelessar** [comment]
Added https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/pull/43 with a fix

**Comment by qiwzhang** [comment]
Cool.   grpc-ecosystem/grpc-httpjson-transcoding#43 is the correct fix.  Approved.

**Comment by euroelessar** [comment]
Thanks for the prompt response.

**Comment by euroelessar** [comment]
BTW, Can you share what are use cases for this feature, please?

**Comment by qiwzhang** [comment]
https://cloud.google.com/apis/design/custom_methods
