### ISSUE TITLE
Question: Can I front proxy from a wildcard subdomain to upstream cluster with matching wildcard subdomain host pattern?

### ISSUE THREAD

**Issue by danludwig** [envoyproxy/envoy#13928]
*Title*: *Question: Can envoy front proxy from a wildcard subdomain to upstream cluster with matching wildcard subdomain host pattern?*

*Description*:

I have a goal of serving a front-proxy for an existing web service that is traditionally hosted at a wildcard domain such as *.my-service.com, so that it can also be accessed from an alternate wildcarded hostname such as *.my-service.services.my-company.com. We have some options for solving this problem of hosting the service at more than one wildcard domain, and I am researching the feasibility of using envoy as one of those options. I have very little experience with envoy, and proxy networking in general, but I have a decent grasp of http, and have spent a few days reading envoy documents and trying things out.

I've set up envoy to listen to *.my-service.services.my-company.com, and am trying to find a way to:
- Rewrite the incoming host header from <something>.my-service.services.my-company.com to <something>.my-service.com.
- Configure a cluster that can forward the incoming requests to <something>.my-service.com.

It is important that the value of the leftmost subdomain in the request coming into envoy be passed to the upstream cluster host as the leftmost subdomain.

I have not yet looked into using EDS or CDS to resolve upstream endpoints or cluster configuration at runtime, but have looked at LOGICAL_DNS and STATIC_DNS cluster configurations, and achieved some success with them when using hardcoded subdomains (such as foo.my-service.com). There is no need to balance load across multiple upstream IP addresses or hosts, as *.my-service.com is a logical service which hides its clustering and load balancing details from external systems like envoy.

I and some from my team have looked for examples of how to do this and are finding them to be elusive, if they exist. Looking for some guidance here as my current understanding of envoy's capabilities do not seem to be dovetailing very well with my research goals. If you had a problem similar to the one stated here, would you solve it with envoy, and if so, how?

**Comment by danludwig** [comment]
bump

**Comment by pablogomezd** [comment]
bump
