### ISSUE TITLE
Update rules_foreign_cc

### ISSUE THREAD

**Issue by oquenchil** [envoyproxy/envoy#13943]
Envoy is failing after a flag flip which affects rules_foreign_cc
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1752#1430dbb5-ec1d-4fff-9394-3d623f259aff

The flag flip went in here:
https://github.com/bazelbuild/bazel/commit/9a2893dc84cf8e05c1472c5ecff094e8da1d2049

The description of the incompatible change is here:
https://github.com/bazelbuild/bazel/issues/10860

Envoy is not using the API, all that's needed here is to update to the most recent version of rules_foreign_cc.

**Comment by antoniovicente** [comment]
cc @benjaminp @lizan 

I'm not sure what's causing the problem you describe.

The https://github.com/bazelbuild/rules_foreign_cc was updated to the most recent change in that repo 14 days ago thank to https://github.com/envoyproxy/envoy/pull/13758

**Comment by benjaminp** [comment]
I think it's because this has been red for a few weeks: https://buildkite.com/bazel/envoy

**Comment by Wyverald** [comment]
The buildkite pipeline is failing to pull the docker image `gcr.io/bazel-public/ubuntu1804-java11`.

@philwo, any ideas?

**Comment by philwo** [comment]
@Wyverald Can you quote the error message and link to a job where the error can be seen? I had a quick look at Buildkite from my phone but couldn’t see anything pointing to Docker.

**Comment by Wyverald** [comment]
https://buildkite.com/bazel/envoy/builds/1360#f0b7d037-077d-46c6-bb67-6aafecb8617a

```

Pulling gcr.io/bazel-public/ubuntu1804-java11 | 5s
-- | --
  | Using default tag: latest
  | error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=gcr.io%2Fbazel-public%2Fubuntu1804-java11&tag=latest: EOF
  | Exited with 1
  | Retrying 2 more times...
  | Using default tag: latest
  | error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=gcr.io%2Fbazel-public%2Fubuntu1804-java11&tag=latest: write unix @->/var/run/docker.sock: write: broken pipe
  | Exited with 1
  | Retrying 1 more times...
  | Using default tag: latest
  | error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=gcr.io%2Fbazel-public%2Fubuntu1804-java11&tag=latest: EOF
  | Exited with 1
  | Failed 3 retries
  | !!! :docker: Pull failed.
  | 🚨 Error: The command exited with status 1


```

**Comment by lizan** [comment]
@benjaminp @philwo looking at the bazel CI failure and last green, the reason that RBE is failing is because we started use multipool and that isn't match what bazelci does. We have a couple of large machines labeled `size=large` for V8 build because they times out in normal machines. This results:

```
(04:07:58) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_googlesource_chromium_v8/BUILD.bazel:30:8: Executing genrule @com_googlesource_chromium_v8//:build failed (Exit 34): java.io.IOException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: there are no bots capable of executing the action, requested action properties: OSFamily = Linux, label:size = large
```

A short-term fix will be exclude those build target from bazel-ci.

**Comment by lizan** [comment]
Seems fixed https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1761#1e9f82e4-91f4-4b11-8f0d-afdab0fa3c6d
