### ISSUE TITLE
Upstream connection events, EOF and I/O errors are never propagated to network filters

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#13940]
The read/write network filters never receive information about:

- upstream connection events (connected, local/remote close),
- mid-stream I/O errors (see: #13939),
- EOF (in case of connections without half-close semantics),

which significantly limits robustness and capabilities of WebAssembly and `ext_proc` extensions.

cc @mattklein123 @gbrail @kyessenov

**Comment by kyessenov** [comment]
Thanks for digging into it. I wonder if it is possible to solve this fully for raw byte streams without application-level semantics on framing. I think there's some just some inherent non-determinism in closure with TIME_WAIT and proxy in the middle.

**Comment by antoniovicente** [comment]
What actions would wasm filters want to take of midstream errors or EOF?

I assume that there's also a logging issue; are HTTP requests that fail after partial response tagged appropriately?

**Comment by PiotrSikora** [comment]
Because upstream connection events are not propagated to network filters, Wasm is currently using `end_stream=true` (which is missing in case of mid-stream error) as a signal for upstream connection close events.

More generally, I'd like to be able to log that the connection was prematurely closed from within Wasm plugins.
