### ISSUE TITLE
Envoy doesn't always send complete request body on POST request

### ISSUE THREAD

**Issue by jphx** [envoyproxy/envoy#13947]
### Description

My organization has been struggling to isolate an intermittent problem we've been experiencing.  We have a legacy -- but still important -- request path that uses an [HAProxy](http://www.haproxy.org/) server downstream of Envoy.

```
client <--> HAProxy <--> Envoy <--> upstream service
```

When this arrangement is used -- and only when this arrangement is used, so far as we can tell -- the upstream service occasionally hangs trying to read the request body of an HTTP POST request.  What's happening is that the upstream service reads the `Content-Length` header and then tries to read that many bytes from the body of the request.  In the failing cases, it appears that Envoy stalls while sending request body bytes to the upstream service.  The upstream service therefore blocks trying to read the body bytes until the 120-second timeout in the upstream service cancels request processing and resets the connection to Envoy, triggering Envoy to return a 503 response.

At first we thought it must be an HAProxy problem, but I've used `tcpdump` to capture all traffic between HAProxy and Envoy and I've verified that the size of the request body sent from HAProxy to Envoy for failing requests is identical to that sent for working requests.  The data itself is encrypted, but the sizes are consistent.  And Envoy _has_ ACKed, at the TCP level, the request bytes that were sent, so it seems that the request body _is_ getting to Envoy.  It must therefore be Envoy that's not passing on the bytes on the upstream service.

We can reproduce this problem only on HTTPS connections, so maybe it has something to do with Envoy's TLS processing, or maybe that's important only because it affects the timing or the size of the chunks that are processed at a time by Envoy.

The configuration of buffer sizes seems to make a difference in how often the problem occurs, and what size request body is necessary to trigger it.  For example, changing the Envoy setting `per_connection_buffer_limit_bytes` for the downstream listener changes the symptoms.  Similarly, changing buffer sizes in HAProxy affects the symptoms.  But so far we've found no combination of buffer sizes that make this intermittent problem go away completely.  We can only affect the size of the request body that's needed to trigger it.

### Steps to reproduce

We've managed to construct a standalone test case that runs HAProxy, Envoy v1.16.0, and an upstream service using [Docker Compose](https://docs.docker.com/compose/), that can be used to (usually) reproduce and observe the problem.  This test case lives at https://github.com/jphx/envoy-stalled-request-body.  Instructions for running the test case are in the repository.

We would be very appreciative of any help in diagnosing and preventing this problem.

**Comment by antoniovicente** [comment]
cc @cpakulski @antoniovicente 

Thanks for the detailed report.

This seems very similar to this recently fixed issue which is waiting backport to v1.16 https://github.com/envoyproxy/envoy/issues/12304

Reason: it involves a stall while processing HTTPS bodies with specific watermark limits configured via per_connection_buffer_limit_bytes

cpakulski: let me know if you need some help with backports.

**Comment by jphx** [comment]
The referenced bug fix does sound promising.  I ran our standalone test case using the `envoyproxy/envoy-dev:1d6d68bd659a78ad53b46799efa2f810c3eb2dd7` image, and so far I've been unable to reproduce the problem.  Thanks very much for the quick advice.  I'm now going to try that image in a real environment where we see the problem with an actual service.

**Comment by jphx** [comment]
A follow-up:  After deploying the mentioned Envoy image to our staging environment, we can no longer reproduce the problem.  I'd say it's a pretty good bet that the referenced pull request fixed it for us.  We'll have to figure out what to do until there's an official release that contains the fix.

Thanks again for the help!  Closing this issue is okay with me.
