### ISSUE TITLE
Envoy abruptly closes new listener H/2 connection before sending max concurrent streams settings

### ISSUE THREAD

**Issue by kryzthov-stripe** [envoyproxy/envoy#13948]
*Title*: Envoy abruptly closes new listener H/2 connection before sending max concurrent streams settings

*Description*:
When an Envoy listener accepts a new H/2 connection and is configured with a low max concurrent streams limit, there is a race between the client receiving the H/2 max concurrent streams setting from Envoy and the client opening an arbitrary number of streams.
If the clients opens too many streams (in excess of the server's max concurrent streams limit) before receiving the H/2 max concurrent streams settings frame, Envoy closes the connection with a protocol error.

*Repro steps*:
I'm reproducing this behavior with Envoy 1.15 in the following setup:
```Client (load generator) -> Envoy no.2 -> Envoy no.1 -> Go backend```
The listener on Envoy #1 is configured with H/2 max concurrent streams = 5.
Both Envoys are configured with concurrency 1 to help reproduction.

 * Go backend: https://gist.github.com/kryzthov-stripe/6cde4085a564010c252c43ad82de5349 listens on localhost:8080
 * Envoy no.1 configuration: https://gist.github.com/kryzthov-stripe/5552582ac4efd8189ca443ea6bbcd8a9 listens on localhost:10000 and forwards to the Go backend
    ```envoy-static --config-path envoy1.yaml --concurrency 1 --component-log-level connection:trace,http2:trace```
 * Envoy no.2 configuration: https://gist.github.com/kryzthov-stripe/beaa5a5ea9be34a247f2b409ecfc7ccc listens on localhost:20000 and forwards to Envoy #1
    ```envoy-static --config-path envoy2.yaml --concurrency 1 --component-log-level connection:trace,http2:trace```
 * Client: `go get github.com/rakyll/hey` sends 200 requests ~concurrently
    ```hey -c 200 -t 0 http://localhost:20000```

All the 200 requests will fail with HTTP 503:
```
Status code distribution:
  [503]	200 responses
```

The access logs for Envoy no.1 will show 5 requests failed with DPE:
```
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "f079c522-298f-43e3-bc9b-c96c239b372c" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "9893eb75-5097-4474-b521-1e047a8b85df" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "784ef569-af2b-4876-8fc8-cfd6aa3c5285" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 0 - "-" "hey/0.0.1" "2e7cbb58-d4df-4460-a1c8-b981b0b495e5" "localhost:20000" "-" "-" - -
[2020-11-09T20:04:05.679Z] [-] "GET / HTTP/2" 0 DPE 0 0 1 - "-" "hey/0.0.1" "78a5da2a-6a06-4cef-a382-f6e1692a8318" "localhost:20000" "-" "-" - -
```

The access logs for Envoy no.2 will show 200 requests failed with UC 503s:
```
[2020-11-09T20:04:05.677Z] [-] "GET / HTTP/1.1" 503 UC 0 95 1008 - "-" "hey/0.0.1" "78a5da2a-6a06-4cef-a382-f6e1692a8318" "localhost:20000" "127.0.0.1:10000" "-" - -
```

The Envoy no.1 trace logs show that it handled 5 streams, and identified the 6th stream as invalid, and closed the connection:
```
source/server/configuration_impl.cc:79] loading 1 listener(s)
source/server/configuration_impl.cc:129] loading stats sink configuration
/source/common/runtime/runtime_impl.cc:524] RTDS has finished initialization
y/source/common/upstream/cluster_manager_impl.cc:182] cm init: all clusters initialized
/source/server/server.cc:534] there is no configured limit to the number of allowed active connections. Set a limit via the run
urce/server/server.cc:631] all clusters initialized. initializing init manager
source/server/listener_manager_impl.cc:844] all dependencies initialized. starting workers
urce/server/server.cc:652] starting main dispatch loop
nvoy/source/common/network/connection_impl.cc:506] [C0] socket event: 2
nvoy/source/common/network/connection_impl.cc:607] [C0] write ready
nvoy/source/common/network/connection_impl.cc:506] [C0] socket event: 3
nvoy/source/common/network/connection_impl.cc:607] [C0] write ready
nvoy/source/common/network/connection_impl.cc:544] [C0] read ready. dispatch_buffered_data=false
nvoy/source/common/network/raw_buffer_socket.cc:25] [C0] read returns: 532
nvoy/source/common/network/raw_buffer_socket.cc:38] [C0] read error: Resource temporarily unavailable
source/common/http/http2/codec_impl.cc:1062] [C0] updating connection-level initial window size to 268435456
source/common/http/http2/codec_impl.cc:524] [C0] dispatching 532 bytes
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=4, flags=0
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=4 flags=0 length=30 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=4
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=8, flags=0
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=8 flags=0 length=4 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=8
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=125 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
nvoy/source/common/network/connection_impl.cc:753] [C1] connecting to 127.0.0.1:8080
nvoy/source/common/network/connection_impl.cc:769] [C1] connection in progress
source/common/http/http2/codec_impl.cc:1062] [C1] updating connection-level initial window size to 268435456
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=38 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:1329] [C0] track inbound frame type=1 flags=5 length=37 padding_length=0
source/common/http/http2/codec_impl.cc:614] [C0] recv frame type=1
source/common/http/http2/codec_impl.cc:588] [C0] about to recv frame type=1, flags=5
source/common/http/http2/codec_impl.cc:763] [C0] invalid frame: Stream was refused on stream 11
nvoy/source/common/network/connection_impl.cc:112] [C0] closing data_to_write=0 type=2
nvoy/source/common/network/connection_impl_base.cc:30] [C0] setting delayed close timer with timeout 1000 ms
nvoy/source/common/network/connection_impl.cc:506] [C1] socket event: 2
nvoy/source/common/network/connection_impl.cc:607] [C1] write ready
nvoy/source/common/network/connection_impl.cc:616] [C1] connected
nvoy/source/common/network/connection_impl_base.cc:44] [C0] triggered delayed close
nvoy/source/common/network/connection_impl.cc:208] [C0] closing socket: 1
```

From a network capture, we can see Envoy no.1 never sent Envoy no.2 a settings.
![image](https://user-images.githubusercontent.com/51547117/98600387-5285c480-2292-11eb-9541-060e6c097ff9.png)
Envoy no.2 still expects the max concurrent streams to be the H/2 default (ie. unlimited), per:
```
   SETTINGS_MAX_CONCURRENT_STREAMS (0x3):  Indicates the maximum number
      of concurrent streams that the sender will allow.  This limit is
      directional: it applies to the number of streams that the sender
      permits the receiver to create.  Initially, there is no limit to
      this value.  It is recommended that this value be no smaller than
      100, so as to not unnecessarily limit parallelism.
```

The *Stream concurrency* section of the H/2 spec seems to indicate that Envoy could simply refuse individual streams (https://tools.ietf.org/html/rfc7540#section-5.1.2).
In particular, the spec doesn't mention that this scenario should lead to a connection error, but merely a stream error:
```
   Endpoints MUST NOT exceed the limit set by their peer.  An endpoint
   that receives a HEADERS frame that causes its advertised concurrent
   stream limit to be exceeded MUST treat this as a stream error
   (Section 5.4.2) of type PROTOCOL_ERROR or REFUSED_STREAM.  The choice
   of error code determines whether the endpoint wishes to enable
   automatic retry (see Section 8.1.4) for details).
```

It seems Envoy no.1 could simple refuse streams in excess to its configured max concurrent streams settings, allowing the client (Envoy no.2) to possibly retry these requests on a different connection/endpoint?

**Comment by antoniovicente** [comment]
@asraa @yanavlasov @antoniovicente @akonradi @alyssawilk 

Yes, that sounds like a race.  I think that a possible way to avoid losing the connection is to limit the number of streams created before the remote endpoint settings are received.  Another mitigation may include preferring stream reset over connection close in cases where the remote endpoint has not ACKed SETTINGs.  Preferring stream reset to connection close when the number of active streams is exceeded also seems like a possible mitigation, but does not allow us to detect cases where the client is intentionally misbehaving.

There's some chance that this behavior is implemented deep down in nghttp2, needs some investigation.

**Comment by yanavlasov** [comment]
It looks like nghttp2 applies limits before new settings were ACKed, from the log it looks like it did not even send the SETTINGS yet. It is not strictly speaking a bug as the [standard does not explicitly say](https://tools.ietf.org/html/rfc7540#section-6.5.3) that new setting MUST be enforced only after receiving ACK. But I would argue that this implementation is not very friendly to race conditions.

**Comment by antoniovicente** [comment]
Thanks for confirming.  This being enforced by nghttp2 means that in order to change behavior we'll need to make some changes to the nghttp2 implementation.

**Comment by yanavlasov** [comment]
@tatsuhiro-t for any additional comments.

**Comment by tatsuhiro-t** [comment]
Do you have any evidence that connection close is done by nghttp2?

**Comment by kryzthov-stripe** [comment]
My limited understanding of what happens is that Envoy's H/2 codec receives an invalid frame callback on `onInvalidFrame` with error code `NGHTTP2_ERR_REFUSED_STREAM` in:
https://github.com/envoyproxy/envoy/blob/e9d85da91fcc504265b0cded8b4df101bc35603c/source/common/http/http2/codec_impl.cc#L894-L920

This error code is not handled specifically, leading Envoy to return `NGHTTP2_ERR_CALLBACK_FAILURE`, which I'm assuming is fatal to the connection.

It looks like we might be able correctly handled stream refusals with something like:
```
  if (error_code == NGHTTP2_ERR_REFUSED_STREAM) {
    return 0;
  }
```

**Comment by yanavlasov** [comment]
I think you are correct in your assessment. According to [RFC](https://tools.ietf.org/html/rfc7540#section-5.1.2) exceeding the limit of concurrent streams must result in stream level error, not connection level error. The change you are suggesting should fix the issue with connection closure. It will however not address the issue of the race condition in enforcing the setting.

**Comment by antoniovicente** [comment]
Somewhat related: https://github.com/envoyproxy/envoy/issues/13933 and https://github.com/envoyproxy/envoy/pull/14820
