### ISSUE TITLE
Unexpected space encoding of query string parameters in gRPC-JSON transcoder

### ISSUE THREAD

**Issue by mhoran** [envoyproxy/envoy#13965]
*Title*: Unexpected space encoding of query string parameters in gRPC-JSON transcoder

*Description*:
When using gRPC-JSON transcoding, query string parameters which contain the literal `+` character are sent to the gRPC upstream retaining the `+` character. Contrast this to query string parameters containing a percent encoded space, `%20`, which are sent to the gRPC upstream as a space. Unfortunately a percent encoded `+` character, `%2B`, is also sent to the gRPC upstream as a literal `+` character. This makes it impossible to differentiate between `+` indicating a space and `+` intended to be a literal `+`. This is compounded by the fact that a browser's URI object encodes spaces as `+` and therefore there is no easy way, aside from manually encoding query string parameters, to pass query string parameters containing spaces through to a gRPC service via gRPC-JSON transcoding.

*Repro steps*:
1) Configure Envoy with gRPC-JSON transcoding as per https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter
2) Curl an endpoint with a `+` query parameter as follows: `curl 'http://localhost:envoy-port/endpoint?query=Hello+World'`
3) Use Wireshark or similar to see that Envoy passes this on to the gRPC upstream as a `+`
4) Curl an endpoint with a `+` percent-encoded query parameter as follows: `curl 'http://localhost:envoy-port/endpoint?query=Hello%2BWorld'`
5) Use Wireshark or similar to see that Envoy passes this on to the gRPC upstream as a `+`
6) Curl an endpoint with a ` ` percent-encoded query parameter as follows: `curl 'http://localhost:envoy-port/endpoint?query=Hello%20World'`
7) Use Wireshark or similar to see that Envoy passes this on to the gRPC upstream as a ` `

Note that there does not need to be an actual gRPC service backing this test if something like Wireshark is used since the behavior can be observed over the wire.

*Config*:
This can be reproduced using the sample config found here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter

*Logs*:
There is nothing unexpected in the logs, but they can be provided if necessary.

**Comment by mattklein123** [comment]
cc @lizan @qiwzhang @euroelessar

**Comment by euroelessar** [comment]
Is it a standard behavior? (looks like browsers/http libraries in general treat `+` as space, but I can't find any rfc/spec which would specify this behavior.
Any preference - if we should unconditionally treat `+` as space or introduce additional option to never decode query/path arguments and allow server to deal with it?

Also, it opens another question - it looks like Envoy in general doesn't do this conversion during query arguments decoding, e.g. 
https://github.com/envoyproxy/envoy/blob/e3c097da5e52ad02b1000d94eb87c4df34df9e01/source/common/http/utility.cc#L982-L1007
https://github.com/envoyproxy/envoy/blob/e3c097da5e52ad02b1000d94eb87c4df34df9e01/source/common/http/utility.cc#L360-L361

**Comment by mhoran** [comment]
The `URI` object in particular behaves this way; when leveraging `#searchParams.append(...)`, spaces will be replaced with `+`. It seems this behavior is documented in [RFC 1866](https://tools.ietf.org/html/rfc1866#section-8.2.1) (HTML 2.0) and the behavior has persisted ever since. I tried encoding the space as `%20` before passing to `#searchParams.append` but unfortunately that results in double-encoding of the `%`.

I think the behavior of the gRPC-JSON transcoder is particularly interesting here, since percent-encoded params are completely decoded when sent to the gRPC upstream. So `%20` comes through as ` ` and `%2B` as `+`. So my expectation would be that a literal `+` received by the gRPC-JSON transcoder would be converted to ` ` as appropriate.

Regarding decoding elsewhere, my gut reaction is that this would not normally be an issue with a standard HTTP server as it should know how to handle `+` in the query params.

**Comment by nezdolik** [comment]
@mhoran and me will pair to work on this

**Comment by mhoran** [comment]
We started looking into this. We have an integration test but I'm not sure it's failing for the expected reason. I hope to have time to look into this again in the new year.

**Comment by nezdolik** [comment]
@euroelessar if we go with first option (always treating `+` as a space), could it potentially affect existing users who rely on Envoy passing `+` as plus? Am thinking what would be the impact.
I would go with config option approach to change/fix this issue. @mattklein123 @mhoran any thoughts?

Wrote a test that reproduces mentioned above behaviour: https://github.com/nezdolik/envoy/commit/e9f07d56004d47929bc599dacb94c2c33f61ebfa

**Comment by dio** [comment]
cc. @qiwzhang @nareddyt

**Comment by mhoran** [comment]
I also started looking at this again today and similarly devised a test that covers the issue: https://github.com/mhoran/envoy/commit/ad88335137f9d74ef0d8b416c566188411a69e69.

I think the current behavior is a bit of an edge case, but I'm hesitant to hide it behind a new option. Perhaps it's rather rare for the `+` to be used in the real world; however, in our case, it was the default browser behavior that exposed this, and the resulting behavior was rather confusing. I too find it strange that this behavior is not encoded in the URI encoding spec but rather the HTML 2.0 spec.

Since I've been poking at this again I discovered that there is existing configuration for handling escaping in the `PathMatcher`. There are three options -- escape all characters except reserved, all characters except slash, and all characters. The default is all characters except reserved. This configuration could be reused to handle the `+` encoding issue, if desired. I started to spike out a fix for this based on this approach.

Open to hearing other opinions on this, but I would prefer that the default case be compatibility with RFC 1866. I do understand that this may break things for those relying on the current behavior, though. Also, it looks like this fix would ultimately land in `PathMatcher` which is pulled in from https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/master/src/include/grpc_transcoding/path_matcher.h, so perhaps we need to open a conversation there as well.

**Comment by nezdolik** [comment]
Agree @mhoran. We could have a config option that would default to RFC expected behaviour with possibility to fallback to current behaviour.

**Comment by mattklein123** [comment]
If we think we are not spec compliant and we think the risk of breaking people is relatively low, I would fix it but but the fix behind a runtime feature flag. If no one complains we can just delete the old code path.

**Comment by qiwzhang** [comment]
I am about to move path_matcher code to a new repo with this pr https://github.com/envoyproxy/envoy/pull/15299
