### ISSUE TITLE
Protocol detection after terminating CONNECT

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#13981]
*Title*: *Protocol detection after terminating CONNECT*

*Description*:
When using Envoy as an outbound CONNECT-terminating proxy, it forwards the payload of the HTTP request to the upstream as raw TCP. It would be useful to be able to detect the tunneled protocol for telemetry purposes, or even to block certain protocols (e.g. to block any plaintext traffic).

I'd guess the easiest way to accomplish this would be with upstream network filters, perhaps reusing a lot of code from listener filters such as TLS inspector?

**Comment by lizan** [comment]
Sounds like this is another use case of https://github.com/envoyproxy/envoy/issues/11725. cc @lambdai

**Comment by mpuncel** [comment]
agreed, if we had a way of dispatching to an "internal listener" that would be even better so that all of the normal listener filters could be used

**Comment by lambdai** [comment]
My experimental code at internal listener supports listener filter including tls inspector. It take time to land though

**Comment by mattklein123** [comment]
cc @alyssawilk I think this has come up multiple times. I'm not sure if we are tracking all of these requests in some holistic way.

**Comment by alyssawilk** [comment]
By this one do you mean protocol introspection, or for CONNECT specifically?  I hadn't seen either so no tracking that I know of.  I agree that while an HTTP filter inspecting data would be easiest, upstream TCP filters modeled off of the TLS inspector would be cleanest.
