### ISSUE TITLE
response - setBytes() generates lua error

### ISSUE THREAD

**Issue by ceastman-ibm** [envoyproxy/envoy#13985]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Trying to use setBytes() but get this error: cannot call body() after body has been streamed

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Trying to use setBytes() in istio's ingress gateway to change the response body but I get this error from the logs of the istio-ingressgateway: cannot call body() after body has been streamed

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

setBytes was added from this pr: https://github.com/envoyproxy/envoy/pull/13172

envoyfilter being added to istio:
[envoyfilter.yaml.gz](https://github.com/envoyproxy/envoy/files/5526859/envoyfilter.yaml.gz)

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
istio 1.8.0-alpha.2

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by dio** [comment]
@ceastman-ibm would you mind trying:


```yaml
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              headers = response_handle:headers()
              streamInfo = response_handle:streamInfo()
              dynamicMetadata = streamInfo:dynamicMetadata()
              requestData = dynamicMetadata:get("request_headers")

            -- This section of code is for redirecting to maintenance if a 4xx or 5xx status code is detected
              headerStatus = headers:get(":status")
              if headerStatus ~= nil then
                if string.match(headerStatus, '[4-5].*') and headerStatus ~= "401" then

                  response_handle:body() -- call this before calling httpCall

                  local console_response_headers, console_response_body = response_handle:httpCall(
                    "outbound|80||maintenance.devtest.svc.cluster.local",
                    {
                      [":method"]   = "GET",
                      [":path"]     = "/maintenance/"..headerStatus,
                      [":authority"] = "maintenance.devtest.svc.cluster.local"
                    },
                    "",
                    1000
                  )
                  local content_length = response_handle:body():setBytes(console_response_body)
                  response_handle:headers():replace("content-length", content_length)
                  response_handle:headers():replace("content-type", "text/html")

                end
              end
            end

```

**Comment by forcedroidbrain** [comment]
@dio thanks, your solution helped
