### ISSUE TITLE
[Question] prefix_rewrite based on selected host in the upstream cluster

### ISSUE THREAD

**Issue by rkbalgi** [envoyproxy/envoy#13992]
*Title*: prefix_rewrite based on selected upstream cluster

*Description*:
Is there anyway possible to rewrite the prefix based on the selected host in a cluster?
I have a static cluster of 4 hosts - 1,2,3,4 and when I receive a request with prefix `/msg.host_x/`, I want the `x` to be replaced by 1,2,3 or 4 based on whichever host is selected in the cluster.

**Comment by phlax** [comment]
quoting @antoniovicente on slack channel:

> No, that's not possible.  One of the things that makes this kind of rewrite difficult is that the proxy would need to rewrite the request again if a different host is selected on retry.

**Comment by rkbalgi** [comment]
Closing as this is not possible at the moment. Thanks guys.
