### ISSUE TITLE
How to see the circuit breaker statistics of  dynamic cluster from SDS ?  

### ISSUE THREAD

**Issue by silencehe09** [envoyproxy/envoy#13995]
@mattklein123  Looking forward to your help. 
The envoy version is 1.10.  By following the wiki  [Statistics overview](https://www.envoyproxy.io/docs/envoy/v1.10.0/operations/stats_overview), I can't see the circuit breaker  statistics of dynamic cluster from SDS, such as `my-foo-cluster` , via the `GET /stats` command in envoy container, but I can see the statistics  of  the cluster `xds-grpc` that is static cluster.

**Comment by lambdai** [comment]
It's likely you didn't have the correct [statsMatches](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-statsmatcher) including what you expected.

BTW: 1.10 is an ancient version and it has been EOL for more than 6 months.
