### ISSUE TITLE
warming cluster is not removed at new CDS response

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#13994]
If the cluster "foo" is warming, and the next CDS response doesn't contains "foo", 
the cluster "foo" will not be removed.

This doesn't follow the concept of wildcard subscription. Also, LDS api doesn't 
act like this.

CC @htuch

**Comment by lambdai** [comment]
Although this behavior is even guarded by integration test. 
https://github.com/envoyproxy/envoy/blob/0e42452a48a8e8d10f5a230a94acb7e5fe84e38f/test/integration/ads_integration_test.cc#L544-L575

IMHO it's a bug. Should we create a flag to optionally introduce new behavior.

**Comment by htuch** [comment]
Seems broken, probably don't even need a runtime flag.
