### ISSUE TITLE
When will envoy return "100-continue" to the client and write it into access log?

### ISSUE THREAD

**Issue by NonStatic2014** [envoyproxy/envoy#14008]
In our production environment, we recently noticed there are some access log record showing envoy return `RESPONSE_CODE:100` to the client. But from client side, we got confirmed they never send any `Expect: 100-continue` header. Also I have tried if I added the `-H "Expect: 100-continue"` in the `curl` command with `-v`, I can see the response including a HTTP 100 response code followed by a HTTP 200 response code (as below `curl` output). And in the access log, this request is recorded as `RESPONSE_CODE:200`. Then it is confusing what triggered envoy return and record status code 100?

```
... ...
> POST /v1/foo/bar HTTP/1.1
> Host: foo.bar.net
> User-Agent: curl/7.58.0
> Accept: */*
> Expect: 100-continue
> Authorization: Bearer <tooooo long>
> Content-Type: application/json
> Content-Length: 332
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 100 Continue
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
< server: foo-bar-server
< date: Thu, 12 Nov 2020 01:01:54 GMT
< content-type: application/json
... ...
```

Thanks!

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
My intuition was that 100-followed-by-200 would result in a 200, and 100 followed by disconnect would result in the 100 being logged, and looks correct according to a quick regression test.   I wonder if you have an upstream sending unexpected 100s, and your client is disconnecting?

**Comment by NonStatic2014** [comment]
We don't see any 100 from upstream (an istio in kubernetes cluster) logs.

"100 followed by disconnect": do you mean envoy received all headers but not start receiving body and then client disconnected somehow? In this case shouldn't I expect response code 0 with a DC flag?

**Comment by alyssawilk** [comment]
if an upstream sends 100-continue, and Envoy forwards it on, then the client disconnects, the 100 goes to the access logs.

I don't know how 100 could end up in your access logs if neither Envoy nor your upstream is sending 100s, and AFIK Envoy only sends 100s when prompted, so I suspect either your client is occasionally sending expect 100-continue or your upstream is occasionally sending 100s.  I suspect the disconnect is because it's unexpected, which is why the full response isn't proxied.
