### ISSUE TITLE
Interval Latched Histograms

### ISSUE THREAD

**Issue by hamdiallam** [envoyproxy/envoy#14007]
Histogram: Support flushing histograms on /stats instead of on a timer

From the documentation : "_The output for each quantile will be in the form of (interval,cumulative) where interval value represents the summary since last flush interval and cumulative value represents the summary since the start of Envoy instance_"

The cumulative metrics doesn't do a good job in reflecting the current latency profile of a running instance. The _interval_ value relies on the stats timer which is sufficient if we rely on that timer when exporting metrics. For systems that collect metrics from an adhoc process on-demand via an endpoint like `/stats`, can we support latching the histograms until the stats endpoint is queried to fully capture an interval? This is something I can work on contributing.

**Comment by ramaraochavali** [comment]
I think it is reasonable to add `/stats?flushHistograms` with out disturbing the existing `/stats` endpoint.  

@mattklein123 WDYT?

**Comment by hamdiallam** [comment]
I think here we'd want to expand on the Bootstrap config? Something like `stats_flush_on_endpoint` so that envoy does not setup a timer at all to flush the histograms and instead triggers the flush on /stats? The endpoints can remain the same

**Comment by mattklein123** [comment]
Sure this sounds reasonable to me.

**Comment by ramaraochavali** [comment]
Ah. Sorry I did not realise that you only wanted stats flush on admin access. Yeah. Bootstrap change makes sense to me

**Comment by hamdiallam** [comment]
@ramaraochavali ahh, I wasn't aware you were going to patch this

**Comment by jmarantz** [comment]
I realize I reviewed the PR that implemented this, but why did we make flushOnAdmin default to true?

It basically  means we need to do a full stats sink any time you access any /stats endpoint, which may double the cost or worse. The functionality seems useful but why did we decide to make this the default?
