### ISSUE TITLE
Dynamic gRPC call credentials

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#14006]
Hi, I'm trying to make a gRPC call using the google_grpc service so I can add credentials to the requests. Specifically I'm trying to use the access_token call credential option, but it only accepts a string. However I'd like to set the access_token value dynamically by using the response body from an HTTP call in a Lua script. Is this possible? I would think that the access_token should not have to be hardcoded into the envoy config

**Comment by antoniovicente** [comment]
cc @htuch  @JimmyCYJ who may be able to provide a better answer.

I think the closest I can find is gRPC Security Token Service (STS) to get call credentials.  https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/core/v3/grpc_service.proto#L132

**Comment by jaegchoi** [comment]
Hey, thanks for responding. Yeah I saw the sts_service option, but it looks like that is for token exchange only, while the token I am trying to get is through the Client Credentials grant. So at this moment I guess this isn't possible?

**Comment by htuch** [comment]
The other possibility is using a metadata credentials plugin, https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/core/v3/grpc_service.proto#L200, to perform the call and then populating metadata (which is basically HTTP/2 headers) with the values where the access token is expected. Lua is not supported today fo metadata credentials plugins.
