### ISSUE TITLE
Request with Transfer-Encoding: chunked and Content-Length is valid per RFC, but rejected with protocol error: http/1.1 protocol error: both 'Content-Length' and 'Transfer-Encoding' are set.

### ISSUE THREAD

**Issue by ceastman-ibm** [envoyproxy/envoy#14004]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Request with Transfer-Encoding: chunked and Content-Length is valid per RFC, but rejected with protocol error: http/1.1 protocol error: both 'Content-Length' and 'Transfer-Encoding' are set.

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Getting a 503 UC error in istio logs. Having both these headers set should not cause a 503 UC error.

This was supposed to be fixed in https://github.com/envoyproxy/envoy/issues/11398 but it looks like all that changed was the description of the error but the behavior remained the same - connection terminated prematurely

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
istio 1.8.0-alpha.2

*Logs*:
>Include the access logs and the Envoy logs.

developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.839936Z	trace	envoy http	[C1699] completed header: key=X-Response-Time value=3182.367
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863003Z	debug	envoy client	[C1699] protocol error: http/1.1 protocol error: both 'Content-Length' and 'Transfer-Encoding' are set.
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863194Z	debug	envoy connection	[C1699] closing data_to_write=0 type=1
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863268Z	debug	envoy connection	[C1699] closing socket: 1
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863464Z	debug	envoy client	[C1699] disconnect. resetting 1 pending requests
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863545Z	debug	envoy client	[C1699] request reset
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863617Z	trace	envoy main	item added to deferred deletion list (size=1)
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863701Z	debug	envoy router	[C275][S16472241048796508750] upstream reset: reset reason: connection termination, transport failure reason: 
developer-ui-6dfb88b5b6-sg8hc istio-proxy] 2020-11-12T19:58:29.863886Z	debug	envoy http	[C275][S16472241048796508750] Sending local reply with details upstream_reset_before_response_started{connection termination}

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by ceastman-ibm** [comment]
setting allow_chunked_length to true based upon https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http1protocoloptions has resolved the issue.

For others running into this in istio. this was fixed in istio-1.8.0-alpha.2 with this envoyfilter:

```apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-developer-ui
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        http_protocol_options:
          allow_chunked_length: true
```

**Comment by achilles-git** [comment]
Can we apply same Configuration on istio-1.7.3 ?

**Comment by achilles-git** [comment]
In istio-1.8.2 after applying above EnvoyFilter the transfer-encoding: chunked issue is resolved but the CDS is not syncing.
`$istioctl proxy-status`
shows status for CDS as STALE (Never Acknowledged)

```
reviews-v2-6bc6c477c-frvns.testing   STALE (Never Acknowledged)     SYNCED     SYNCED     SYNCED       istiod-77db4dc8cd-dtc42     1.8.2

**Comment by kameshchauhan** [comment]
> In istio-1.8.2 after applying above EnvoyFilter the transfer-encoding: chunked issue is resolved but the CDS is not syncing.
> `$istioctl proxy-status`
> shows status for CDS as STALE (Never Acknowledged)
> 
> ```
> reviews-v2-6bc6c477c-frvns.testing   STALE (Never Acknowledged)     SYNCED     SYNCED     SYNCED       istiod-77db4dc8cd-dtc42     1.8.2
> ```

We are also facing the same issue the above envoy filter is causing. In fact not even the issue of sync but rather the istio-proxy are not coming up.

**Comment by jmarantz** [comment]
FWIW, somewhat confusingly, the RFC *explicitly* disallows this case but also specifies what should be done if it arises. I think https://www.rfc-editor.org/rfc/rfc2616#section-4.4 is authoritative, at the end of the section (just before 4.5).

> Messages MUST NOT include both a Content-Length header field and a
   non-identity transfer-coding. If the message does include a non-
   identity transfer-coding, the Content-Length MUST be ignored.
