### ISSUE TITLE
Poor DNS cache performance with large number of unique domains

### ISSUE THREAD

**Issue by chradcliffe** [envoyproxy/envoy#14018]
*Description*:
We are using Envoy as a dynamic forward proxy and are looking to connect upstream to a large number of hosts at unique domains (>> 100k).

We ran across performance issues in the implementation of the DNS cache when scaling to >40k hosts.

The primary issue is that both the DNS cache implementation and the dynamic forward proxy implementation each create a new copy of the entire cache on update. This is a reasonable implementation given Envoy's threading model and if you know the map is small, but it runs into scalability issues as the map grows.

With default configuration, the DNS cache will hit circuit-breaker limits before hitting this performance issue, so this issue won't be hit in overload conditions where you expect only a small number of hosts. The trouble occurs when you want to configure Envoy to handle a much larger number of host names.

This performance issue is probably not surprising, since I would expect the motivating use case was for a much smaller number of hosts. Looking at the [dynamic forward proxy documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy), it's fairly clear that there are some features that would not be feasible for a large number of hosts (e.g. observability in the admin output).

I'd like to understand if the intention is for the DNS cache to be used as a general-purpose cache that will be able to scale, or if it's primarily intended to only be paired with the dynamic forward proxy cluster.

*Repro steps*:
1. Configure Envoy to use a dynamic forward proxy.
2. Set the `max_hosts` and `host_ttl` in the `dns_cache_config` to something large.
3. Disable the DNS cache circuit breakers (`envoy.reloadable_features.enable_dns_cache_circuit_breakers`)
4. Run traffic against Envoy destined to ~50k unique domains or more

I also created a Google Benchmark test to exercise the DNS cache implementation in isolation and observed a cache insertion complexity of greater than O(N^2) (N=number of elements in the map).

**Comment by mattklein123** [comment]
In general I wouldn't assume the implementation has to be the way that it is. Definitely open to perf improvements. Do you want to suggest some concrete changes?

> The primary issue is that both the DNS cache implementation and the dynamic forward proxy implementation each create a new copy of the entire cache on update. This is a reasonable implementation given Envoy's threading model and if you know the map is small, but it runs into scalability issues as the map grows.

I don't recall the history of why I implemented it like this, but I'm guessing with some thought it could be merged into a single structure and accessed via locking.

> I also created a Google Benchmark test to exercise the DNS cache implementation in isolation and observed a cache insertion complexity of greater than O(N^2) (N=number of elements in the map).

This part I find surprising. I believe the implementation is using maps everywhere? Do you have more details on this?

**Comment by chradcliffe** [comment]
> In general I wouldn't assume the implementation has to be the way that it is. Definitely open to perf improvements. Do you want to suggest some concrete changes?

In our use case, we expect frequent cache updates, which makes maintaining a global map with locking less attractive. For us, it seems to make sense to have each worker thread maintain their own local cache and receive updates from the main thread. This adds a bit of complexity since each worker would have to manage its own cache expiry (and there would be some memory overhead for the additional maps in each thread), but I think that would provide a noticeable improvement for large maps.

Here's a more concrete flow:
1. Worker thread DNS cache has cache miss, sends request to worker thread dispatcher
1. Main thread checks main thread map (posts to worker thread with DNS result on cache hit)
1. On cache miss, main thread resolves using DNS resolver, updates main thread map
1. Main thread posts DNS resolution result to the requesting worker thread
1. Worker thread receives resolution result, updates local cache

There might be some other opportunities for improvement, but I think we'll need to solve the immediate copying problem before other issues become important.

> I don't recall the history of why I implemented it like this, but I'm guessing with some thought it could be merged into a single structure and accessed via locking.

It might make sense to keep the dynamic forward proxy host map separate from the DNS cache, but use a lock for access to the dfp host map. The two maps currently use two different value types, so it might be easier to maintain them separately (particularly if we're okay with posting updates to worker threads). It's also useful to be able to have the DNS cache available but not use the dynamic forward proxy cluster.

> > I also created a Google Benchmark test to exercise the DNS cache implementation in isolation and observed a cache insertion complexity of greater than O(N^2) (N=number of elements in the map).
> 
> This part I find surprising. I believe the implementation is using maps everywhere? Do you have more details on this?

I pushed the benchmark test [here](https://github.com/chradcliffe/envoy/blob/chradcliffe/dns-cache-benchmark/test/extensions/common/dynamic_forward_proxy/dns_cache_impl_benchmark_test.cc#L65).

The implementation is using maps everywhere, but because the implementation creates a new map and populates it on each update, the insertion complexity of the cache is much worse than the complexity of a hash map insertion.

The implementation does the following on insert:
1. Creates a new empty `flat_hash_map<string, DnsHostInfoSharedPtr>`
1. Iterates over the existing `flat_hash_map<string, PrimaryHostInfoPtr>` map (an `O(capacity)` operation)
1. If an entry has been resolved, inserts the `DnsHostInfoSharedPtr` entry into the new map (if the load factor is exceeded, this will lead to a reallocation and copy of the existing entries)

Given that, I think it makes sense that the performance starts to degrade as the number of entries rise.

**Comment by mattklein123** [comment]
> In our use case, we expect frequent cache updates, which makes maintaining a global map with locking less attractive. For us, it seems to make sense to have each worker thread maintain their own local cache and receive updates from the main thread.

The downside of this is you will multiply your memory usage by the number of workers which for a large cache seems not great. (I suppose you could evict things faster from the workers but it still seems sub-optimal).

In paging back in this code, I think I was mostly trying to avoid locking, but I'm not sure that is the best design choice given your use case. I think if you had a RW lock on the map, and then more granular locks for each host entry (allowing for address updates that are independent), things would scale quite well.

I would probably advocate just using locking and removing all of the copies everywhere in both the DNS cache as well as the forward proxy host map. WDYT?

**Comment by chradcliffe** [comment]
Seems like that's a good minimal change -- if we find there's a lot of lock contention in our use case, we can always introduce a thread-local cache on the filter side of things.

This is an important change for us, so I'm going to take a preliminary pass at what you suggested this week. Feel free to assign this issue to me.

**Comment by mattklein123** [comment]
> This is an important change for us, so I'm going to take a preliminary pass at what you suggested this week. Feel free to assign this issue to me.

OK sounds good. I can potentially work on it also if you run into issues but will assign to you for now.
