### ISSUE TITLE
Enable Wasm with V8 runtime on CI for both Windows and Linux/arm64.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#14027]
Enable Wasm with V8 runtime on CI for both Windows and Linux/arm64.

cc @lizan

**Comment by lizan** [comment]
For arm64 the issue is we don't have emscripten, though we can enable wasm without emscripten tests, WDYT?

**Comment by PiotrSikora** [comment]
Sounds good, majority of tests have both C++ and Rust versions.

**Comment by lizan** [comment]
@PiotrSikora wasm-cpp-host failed to build on Windows:

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/60523/logs/15

**Comment by PiotrSikora** [comment]
Could you try https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/117? I don't have a way to test it.

Also, please keep it mind that `wee8.genrule_cmd` wasn't tested on Windows, so it might need some fixes as well.

**Comment by PiotrSikora** [comment]
@lizan did it help?

**Comment by lizan** [comment]
Trying it out https://dev.azure.com/cncf/envoy/_build/results?buildId=61370&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53

**Comment by PiotrSikora** [comment]
Could you try again with the latest commit? Previous build failed because of change to cargo-raze artifacts that wasn't updated in Envoy yet, buy it is now.
