### ISSUE TITLE
upstream_cx_active skyrocketing 

### ISSUE THREAD

**Issue by tydurd** [envoyproxy/envoy#14049]
*Title*: *Envoy 1:12.2 within an AKS cluster randomly generates high number of _upstream_cx_active_  producing _upstream_cx_destroy_with_active_rq_ and _upstream_rq_pending_failure_eject_ with traffic mirroring*

*Description*:
I'm running Envoy 1:12.2 as a sidecar within an AKS cluster and I'm trying to mirror traffic to another pod within the same cluster. The mirrored pod is behind an headless k8s service and the envoy service discovery type for this service is set to strict_dns.

Running a load test against the Envoy proxy with a load of 1200-1500 RPS consistently produces the following behavior:
- upstream_cx_active is usually within the range of 50-100
- periodically, the _upstream_cx_active_ skyrockets to 800-1200 and then either I got high number of _upstream_cx_destroy_with_active_rq_ or _upstream_rq_pending_failure_eject_, both resulting in 5xx errors. Running a netstat while _upstream_cx_active_ peaks shows a lot of established connections between the envoy proxy and the mirrored service

During the test, the envoy container is never overloaded, and constantly runs at 50% of CPU assigned to it. 

I'm pretty sure I'm missing something really basic, I'd really appreciate if you could lend an hand here and pointing me to root cause.
Please find below the envoy configuration:

  static_resources:
	listeners:
	- address:
		socket_address:
		  address: 0.0.0.0
		  port_value: 80
	  filter_chains:
	  - filters:
		- name: envoy.http_connection_manager
		  config:
			codec_type: auto
			stat_prefix: ingress_http
			route_config:
			  name: local_route
			  virtual_hosts:
			  - name: bookservice
				domains:
				- "*"
				routes:
				- match:
					prefix: "/" 
				  route:
					cluster: local_service
					request_mirror_policy:
					  cluster: mirror_service
			http_filters:
			- name: envoy.router
			  config: {}
	clusters:
	- name: local_service
	  connect_timeout: 2.25s
	  type: static
	  lb_policy: round_robin
	  hosts:
	  - socket_address:
		  address: 127.0.0.1
		  port_value: 8080
	  circuit_breakers:
		thresholds:
		  max_connections: 10000
		  max_requests: 10000
		  max_pending_requests: 10000
	- name: mirror_service
	  connect_timeout: 2.25s
	  type: strict_dns
	  lb_policy: round_robin
	  hosts:
	  - socket_address:
		  address: {{ .Values.loggingService.ip }}
		  port_value: 80
	  circuit_breakers:
		thresholds:
		  max_connections: 10000
		  max_requests: 10000
		  max_pending_requests: 10000
  admin:
	access_log_path: "/dev/stdout"
	address:
	  socket_address:
		address: 0.0.0.0
		port_value: 8081

**Comment by junr03** [comment]
@tydurd do you mind formatting the config so that it is easy to read?

**Comment by yanavlasov** [comment]
The symptom indicates that the upstream can not keep up with the load.

**Comment by lambdai** [comment]
your upstream cluster is localhost. It is highly possible that there is a spike of new tcp SYN to localhost upstream, and both the SYN queue and accept queue are full.
Then envoy will resend SYN packet in 3 seconds while your envoy connect timeout is 2.25s. 

Try increase connect time out to 5 or 10 seconds to see if number of upstream_cx_destroy_with_active_rq is reduced

**Comment by tydurd** [comment]
Thanks a lot for the quick heads-up guys. After a full day of testing I've found out that the cause is that, occasionally, the mirrored service (which writes to an NFS volume) can't keep up with the load and hence the spikes in upstream_cx_active.
