### ISSUE TITLE
open /dev/shm some files error：permission denied

### ISSUE THREAD

**Issue by feimeng1029** [envoyproxy/envoy#14057]
if /dev/shm/ directory has some dirs not files and these dirs have 750 permissions，pilot-agent will error and then will delete 
 config file envoy-recv0.yaml.It will make envoy not work.

**Comment by junr03** [comment]
Sorry, this seems like a problem with the file permissions on your setup, or even how pilot-agent (outside of the envoy project) deals with your local filesystem. I am not sure how the envoy maintainers can assist you.

**Comment by feimeng1029** [comment]
Oracle is installed on my server, and Oracle contains a directory with 750 permissions. This error was reported when I installed pilot agent on this machine. In this case, I can't install pilot agent on this machine.
![image](https://user-images.githubusercontent.com/37317258/99493106-9f138300-29a9-11eb-95a3-32889240c3b0.png)

![image](https://user-images.githubusercontent.com/37317258/99493071-8efba380-29a9-11eb-9259-8e2419e8e1aa.png)

**Comment by feimeng1029** [comment]
I understand that /dev/shm is a public shared memory directory, so pilot-agent should not prevent other applications from installing or accessing it

**Comment by lambdai** [comment]
@feimeng1029 Can you create an issue in github.com/istio/istio and close this one?
