### ISSUE TITLE
PAUSE session while making a long request

### ISSUE THREAD

**Issue by micheleselea** [envoyproxy/envoy#14063]
Hi all, I have my libevent-server that runs monothread event server. If I have a request that need a long blocking operation to complete I can make it in a separate thread. In this scenario what have I to return from on_frame_recv_callback in order to make request wait until I signal the data ready? what do you think is the best way to do such long request?

**Comment by junr03** [comment]
How is envoy involved in this setup?

**Comment by micheleselea** [comment]
Sorry you are right wrong place
