### ISSUE TITLE
Dynamically link tests

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1407]
As discussed in #1400, this is probably the long term way to improve both build performance and disk utilization (should be able to get ASAN from 24GB to 4GB). I think this would be a useful improvement to developer productivity and also help with the Travis CI disk and CPU situation. I would swag this as probably 1-2 days work, looking for volunteers.

The first step would be to ensure we have the right artifacts in the external deps to perform dynamic link, we build with static only flags today. Then, modify the `envoy_cc_test*` macros in `envoy_build_system.bzl` to link dynamically. Then, mostly debugging. I'll leave this ticket open for volunteers.

**Comment by mattklein123** [comment]
We are doing this, so closing.
