### ISSUE TITLE
Why http 4xx status code not set error tag

### ISSUE THREAD

**Issue by chinaran** [envoyproxy/envoy#14074]
https://github.com/envoyproxy/envoy/blob/master/source/common/tracing/http_tracer_impl.cc#L256
The 5xx status code has error tag.
But why without 4xx?

**Comment by junr03** [comment]
Sorry, do you mean why does 4xx not have an error tag?

**Comment by chinaran** [comment]
@junr03 yes, thanks for your answer.
eg. a jaeger span's http.status_code is 404, but without error tag, jaeger ui will not show the red warning "!".

**Comment by jotak** [comment]
Hi,
I'm wondering the same thing. Would it make sense to have client-side spans in error for 4xx, and not server-side spans?
