### ISSUE TITLE
listener: deprecate use_proxy_proto

### ISSUE THREAD

**Issue by tbarrella** [envoyproxy/envoy#14085]
*Title*: ~~Check all filter chains before injecting proxy proto listener filter~~ deprecate use_proxy_proto

*Description*: See discussion [here](https://github.com/envoyproxy/envoy/pull/14025#discussion_r526442863)

**Comment by mattklein123** [comment]
Yes, we should deprecate it, but I'm more concerned about whether we block it or not right now. Do we have a check that it's all or none? If not can we add it behind a runtime guard?

**Comment by tbarrella** [comment]
Incidentally, it seems this behavior has been around for a while, it looks like since #1471 if I'm interpreting the code right

**Comment by lambdai** [comment]
+1 for runtime guard and add warning message

**Comment by ggreenway** [comment]
I'd say don't change the behavior, deprecate it, and make sure docs show how to add it to the listener filters explicitly.

**Comment by mattklein123** [comment]
My concern is the existing behavior makes absolutely no sense. How can it work at all? I'm fine with whatever approach we want, definitely deprecation, but I'm also potentially in favor of warn/fail on mismatch behind a runtime flag.

**Comment by ggreenway** [comment]
I agree it makes no sense, but changing it has the risk of breaking someone's config that currently works (even if it doesn't make sense). And if we're deprecating it, the risk doesn't seem worth it. If we weren't going to deprecate it, I'd say definitely fix it (with runtime guard).

**Comment by mattklein123** [comment]
OK sounds good. I'm fine either way, but let's definitely do the deprecation.

**Comment by tbarrella** [comment]
I have a few questions about how to deprecate something (referring to the [breaking change policy](https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#breaking-change-policy))

>Deprecators must implement a conversion from the deprecated configuration to the latest vNalpha (with the deprecated field) that Envoy uses internally.

What does this mean in this case? For examples that use `use_proxy_proto` like  [this](https://github.com/envoyproxy/envoy/blob/master/docs/root/configuration/best_practices/_include/edge.yaml) it seems like I just need to update them to instead use
```
listener_filters:
- name: envoy.filters.listener.proxy_protocol
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
```

But must there also be some code/tool that manipulates configuration for people?

>The PR author deprecating the old configuration is responsible for updating all tests and canonical configuration, or guarding them with the DEPRECATED_FEATURE_TEST() macro.

Is this true for fuzzing tests as well? Referring to this [test case](https://github.com/envoyproxy/envoy/blob/master/test/server/server_corpus/clusterfuzz-testcase-server_fuzz_test-5647989147697152)

For adding `[deprecated = true]` to proto definitions, would this only be for v4alpha (there's also v3 and v2)?

**Comment by lambdai** [comment]
> For adding [deprecated = true] to proto definitions, would this only be for v4alpha (there's also v3 and v2)?
You only need to add for v3 and run  `tools/proto_format/proto_format.sh fix` to sync to other versions.

Not fully sure about the fuzzer CC @asraa

**Comment by htuch** [comment]
+1 on deprecate. The less magic in the filter chains the better IMHO (as well as existing behavior being broken).

**Comment by mattklein123** [comment]
I think we should a) deprecate and also b) warn on mismatch (not all or nothing).

I think this will give us good coverage.

**Comment by mattklein123** [comment]
This is fixed.
