### ISSUE TITLE
Disabling extensions on envoy

### ISSUE THREAD

**Issue by koustubh25** [envoyproxy/envoy#14090]
**Title**: *What's the correct way to disable extensions?*

**Description**:

Following this documentation https://www.envoyproxy.io/docs/envoy/v1.15.0/operations/cli.html?highlight=disable%20extensions#cmdoption-disable-extensions, I tried to start envoy with 

```
envoy -c <myconfig> --disable-extensions grpc_credentials/envoy.grpc_credentials.file_based_metadata
```

However, I see this error message in the console
```
[2020-11-19 01:44:34.216][1][warning][misc] failed to disable unknown extension 'grpc_credentials/envoy.grpc_credentials.file_based_metadata'
```
Following the logs on startup I can see this

```
I1119 01:44:34.216 1 envoy] [1][main][source/server/server.cc:297] statically linked extensions:
I1119 01:44:34.216 1 envoy] [1][main][source/server/server.cc:299]   envoy.grpc_credentials: envoy.grpc_credentials.aws_iam, envoy.grpc_credentials.default, envoy.grpc_credentials.file_based_metadata
```

I am using envoy version `v1.15.0`

What's the correct way to define the list of extensions to disable?

**Comment by moderation** [comment]
I don't have experience disabling the extensions at the command line but I think you want to use the specific string at https://github.com/envoyproxy/envoy/blob/master/source/extensions/extensions_build_config.bzl#L31 `envoy.grpc_credentials.file_based_metadata`

**Comment by koustubh25** [comment]
@moderation 
I tried this as well

```
envoy -c <config> --disable-extensions envoy.grpc_credentials.file_based_metadata
```
with no luck
```
[2020-11-19 03:04:16.322][1][warning][misc] failed to disable invalid extension name 'envoy.grpc_credentials.file_based_metadata'
```

Am I missing something?

**Comment by lambdai** [comment]
Hmm, looking at the code, the correct magic string is **envoy.** grpc_credentials/envoy.grpc_credentials.file_based_metadata`

`$ docker run -it --entrypoint sh envoyproxy/envoy:v1.15.1 -- /docker-entrypoint.sh -c /etc/envoy/envoy.yaml --disable-extensions envoy.grpc_credentials/envoy.grpc_credentials.file_based_metadata`
[2020-11-19 10:18:34.391][7][info][misc] disabled extension 'envoy.grpc_credentials/envoy.grpc_credentials.file_based_metadata'

Let me fix the doc later
