### ISSUE TITLE
Where Could we find the waiting queue?

### ISSUE THREAD

**Issue by Harrryyy** [envoyproxy/envoy#14136]
Currently, we want to figure out where Envoy store requests, Is there any waiting queue in Envoy before the request is sent to the service? The reason for locating the waiting queue is that we attempt to calculate the average request wait time, or is it already provided as a metric? Thank you

**Comment by yanavlasov** [comment]
In normal case there is no queue, the request is immediately sent to the upstream server if there is available upstream connection. If there is no available connection the request will wait until one is established, you can observe this wait time through the [upstream_cx_connect_ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#general) histogram.

There is one case for H/2 upstream protocol when connection is available however the number of active streams has reached its limits. In this case new requests are queued inside the nghttp2 codec until some existing active streams complete and new one can be started. This queue is currently not instrumented, i.e. there are no stats that tell how long it is or the wait time in that queue.
