### ISSUE TITLE
Audit handling of addresses when listener filters (proxy protocol, etc) modify it

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#14133]
The handling of downstreamLocalAddress and downstreamRemoteAddress is messy and unclear. Audit uses of the address on both the connection and StreamInfo. Clean up code so it is easier to understand. 

* Specifically, the addresses are set twice on the connection StreamInfo, once before listener filters are run and once after. Try to find a better way to handle this.
* HCM sets the downstream address before doing XFF handling. Can this be removed?

**Comment by rgs1** [comment]
Related: https://github.com/envoyproxy/envoy/pull/14432#issuecomment-758004199.
