### ISSUE TITLE
Oauth Group validation

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#14153]
Add group validation in oauth filter

Will be nice that after authenticate, we can validate that the user is part of x group comma separated, this could be added at the oauth config

config:
  token_endpoint:
    cluster: oauth
    uri: oauth.com/token
    timeout: 3s
  authorization_endpoint: https://oauth.com/oauth/authorize/
  **authorization_groups**: /app/admin,/app/ro

In order to do that, add a way to parse the token and see if the user is part of those groups

**Comment by zuercher** [comment]
cc @rgs1 @derekargueta as oauth codeowners.

**Comment by rgs1** [comment]
cc: @williamsfu99

**Comment by juanvasquezreyes** [comment]
is there any update on this enhancement?

this is an example of the JWT Token and the group I'm trying to validate in order to grant or deny access
```
{
  "exp": 1606863262,
  "iat": 1606862962,
  "auth_time": 1606858962,
  "jti": "628aec15-9336-4db7-b90e-0006ac73dac6",
  "iss": "https://oauth-server/auth/realms/test-realm",
  "aud": "account",
  "sub": "75977a76-e2a4-4bb4-bfd1-c403a5d7fe1e",
  "typ": "Bearer",
  "azp": "keycloaktest",
  "session_state": "03de48d4-0376-483b-b3e2-24adbbc81fc5",
  "acr": "0",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "keycloaktest": {
      "roles": [
        "uma_protection"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "profile email keycloaktest",
  "email_verified": false,
  "groups": [
    "/keycloaktest/approved",
    "/remove",
    "/test",
    "offline_access",
    "uma_authorization"
  ],
  "preferred_username": "approved"
}
```

**Comment by williamsfu99** [comment]
@juanvasquezreyes 
Working on this enhancement now - should have it done by tomorrow (28th!)

**Comment by juanvasquezreyes** [comment]
> @juanvasquezreyes
> Working on this enhancement now - should have it done by tomorrow (28th!)

Thank you @williamsfu99

**Comment by williamsfu99** [comment]
Created #14527. Note @juanvasquezreyes the additional description in the PR message, in case you end up needing a more sophisticated authz framework in the future.

**Comment by williamsfu99** [comment]
Update - rejected the attached PR because authorizing groups should not happen at an authentication step. To unblock you, however, you could use a combination of the [JWT filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto) and the [ext_authz filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto) with the `payload_in_metadata `/`metadata_context_namespaces` fields.

**Comment by juanvasquezreyes** [comment]
@williamsfu99  thank you for the update, it wasnt only for groups could be for anything in the token

Also adding JWT filter makes another call to authorizator and using ext_authz_filter needs another container to just do the validation

That's why I was thinking just one call could do everything, also I'm trying to implement this using contour in kubernetes, so adding these 2 extra steps doesnt seem a good way to achieve this

**Comment by pratiklotia** [comment]
@juanvasquezreyes / @williamsfu99 
are there any examples/code snippets on how to use combination of the [JWT filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto) and the [ext_authz filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto) for the authorization part?

**Comment by juanvasquezreyes** [comment]
> @juanvasquezreyes / @williamsfu99 are there any examples/code snippets on how to use combination of the [JWT filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto) and the [ext_authz filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto) for the authorization part?

This worked for me
`              http_filters:
                - name: envoy.filters.http.oauth2
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
                    config:
                      forward_bearer_token: true
                      token_endpoint:
                        cluster: oidc-service
                        uri: ${OIDC_TOKEN_ENDPOINT}
                        timeout: 5s
                      authorization_endpoint: ${OIDC_AUTH_ENDPOINT}
                      redirect_uri: "https://%REQ(:authority)%/callback"
                      redirect_path_matcher:
                        path:
                          exact: /callback
                      signout_path:
                        path:
                          exact: /signout
                      credentials:
                        client_id: ${OIDC_CLIENT_ID}
                        token_secret:
                          name: token
                        hmac_secret:
                          name: hmac
                - name: envoy.filters.http.jwt_authn
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                    providers:
                      default_provider:
                        payload_in_metadata: "payload"
                        issuer: ${OIDC_JWT_ISSUER}
                        remote_jwks:
                          http_uri:
                            uri: ${OIDC_JWKS_ENDPOINT}
                            cluster: oidc-service
                            timeout: 5s
                          cache_duration:
                            seconds: 300
                    rules:
                      - match:
                          prefix: "/"
                        requires:
                          provider_name: "default_provider"
                - name: envoy.filters.http.rbac
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                    rules:
                      action: ALLOW
                      policies:
                        "authorized":
                          principals:
                            - metadata:
                                filter: envoy.filters.http.jwt_authn
                                path:
                                  - key: payload
                                  - key: groups
                                value:
                                  list_match:
                                    one_of:
                                      string_match:
                                        exact: ${ALLOWED_GROUP}
                          permissions:
                            - any: true`

**Comment by pratiklotia** [comment]
@juanvasquezreyes thank you very much for the example. I really appreciate the snippet and the timely response.

I'm testing this out for a single upstream. I want to do it this authZ per upstream/virtual_host? Basically, by using Groups, I want to limit which user can access what virtual_hosts/upstream paths a user can access. I'm gonna play around by creating multiple 'policies' and adding it to the virtual_host/upstream filter- if you have any insight to share on that use case, please do let me know.

**Comment by RoboLee** [comment]
@pratiklotia Could you please share me details on your fixing as well as use case?
