### ISSUE TITLE
HttpConnectionManager.idle_timeout documentation deprecation unclear

### ISSUE THREAD

**Issue by max0ne** [envoyproxy/envoy#14160]
*Description*:
The `idle_timeout` field description in [this page](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-common-http-protocol-options) has a *This field is deprecated. Use idle_timeout instead* note, but the `idle_timeout` it points to is also this field. I'm not sure if this field is actually deprecated, and if so what should be used instead.

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-common-http-protocol-options

**Comment by mk46** [comment]
I think link redirect to [common_http_protocol_options](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-common-http-protocol-options) is valid one. The `idle_timeout` can be config as 
```
common_http_protocol_options:
    idle_timeout: 0.90s

```
 See the link below to common_http_protocol_options. Ref [core.HttpProtocolOptions](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-httpprotocoloptions).

**Comment by zuercher** [comment]
`idle_timeout` in `common_http_protocol_options` is the replacement for `idle_timeout` in the HttpConnectionManager. I was going to suggest we point the link to the actual field that replaces idle_timeout, but since this problem only exists in the v2 api, which is scheduled to be removed soon, I'm not sure if it's worth the time.
