### ISSUE TITLE
 [Feature Request] 2FA

### ISSUE THREAD

**Issue by zero77** [envoyproxy/envoy#14180]
*Title*: *One line description*

*Description*:
 Can you please add 2FA to provide additional security before clients are able to establish a connection to the end device.

[optional *Relevant Links*:]
Google already provide a 2FA module that can be integrated with protocols like SSH and OpenVPN.
https://github.com/google/google-authenticator-libpam

**Comment by zuercher** [comment]
Could you provide a little more context about your use case?

**Comment by zero77** [comment]
@zuercher 
There isn't a specific case, its more about increasing the security of a reverse proxy when vpn is not an option.

**Comment by zero77** [comment]
no stalebo

**Comment by mattklein123** [comment]
2FA is not something that Envoy would typically provide. Please provide more info on your feature request otherwise we will close this out.
