### ISSUE TITLE
Does envoy have envoy_response_code for metrics like envoy_cluster_upstream_rq_time_sum

### ISSUE THREAD

**Issue by mjaow** [envoyproxy/envoy#14196]
*Title*: *One line description*

*Description*: Doese envoy have envoy_response_code for metrics for duration , something like envoy_cluster_upstream_rq_time_sum?  I don't find it , is it reasonable to have one?

> Describe the the desired behavior, what scenario it enables and how it
would be used.

is it reasonable to have envoy_response_code in envoy_cluster_upstream_rq_time_sum , to group request duration by response code

**Comment by mattklein123** [comment]
This doesn't exist today.
