### ISSUE TITLE
Build envoy for MacOS

### ISSUE THREAD

**Issue by AndreyFlyAway** [envoyproxy/envoy#14202]
*Title*:  Cant build envoy for MacOS

*Description*:
I try to build envoy without using the Docker. I use instruction from readme but I get error below. It cause when Bazel build external dependencies - com_googlesource_chromium_v8. I don't know what to do with this. 

*Repro steps*: 
Also I installed latest Xcode.
Check new updates for my MacOS.
To build I used command from README.md:
`bazel build -c opt //source/exe:envoy-static`

Master branch.
Bazel 2.2.0
Xcode 12.2
macOS Catalina 10.15.7

*Logs*:

ERROR at //build/config/mac/mac_sdk.gni:85:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /private/var/tmp/_bazel_a19869333/4be4632b69cfd5012d6277984fa20c9d/sandbox/darwin-sandbox/1351/execroot/envoy/external/com_googlesource_chromium_v8/wee8/out/wee8/
Command: python /private/var/tmp/_bazel_a19869333/4be4632b69cfd5012d6277984fa20c9d/sandbox/darwin-sandbox/1351/execroot/envoy/external/com_googlesource_chromium_v8/wee8/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.14
Returned 1.
stderr:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_a19869333/4be4632b69cfd5012d6277984fa20c9d/sandbox/darwin-sandbox/1351/execroot/envoy/external/com_googlesource_chromium_v8/wee8/build/mac/find_sdk.py", line 127, in <module>
    print(main())
  File "/private/var/tmp/_bazel_a19869333/4be4632b69cfd5012d6277984fa20c9d/sandbox/darwin-sandbox/1351/execroot/envoy/external/com_googlesource_chromium_v8/wee8/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.14+ SDK found

See //build/config/sysroot.gni:64:3: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
See //build/config/BUILDCONFIG.gn:509:23: which caused the file to be included.
  _linker_configs = [ "//build/config/mac:strip_all" ]

**Comment by moderation** [comment]
I build on MacOS without issue (however I'm not building the WASM extension). The version of Bazel you are using is very old. I would consider using 3.6.0 or greater with the latest being 3.7.1

**Comment by mathetake** [comment]
@AndreyFlyAway V8 has been updated to the newer version in https://github.com/envoyproxy/envoy/pull/14298 4 days ago, so could you please try again with HEAD ?

cc @PiotrSikora

**Comment by mathetake** [comment]
> The version of Bazel you are using is very old. I would consider using 3.6.0 or greater with the latest being 3.7.1

yeah, this could be the cause actually.

**Comment by PiotrSikora** [comment]
Do you have Xcode command line tools installed?

**Comment by AndreyFlyAway** [comment]
I figure out what was the problem. First of all I used fork from istio release-1.6 branch (my mistake). I replaced downloading old version of com_googlesource_chromium_v8 by newest from this repo - chnaged it in repositories.bzl. I don't know the true nature of this error but it helps. Thank you all for help.
