### ISSUE TITLE
Access logs format

### ISSUE THREAD

**Issue by simeongr** [envoyproxy/envoy#14209]
*Title*: *Access logs format is suspicious*

*Description*:
We are seeing logs like this one:
`[2020-11-26T14:25:49.160Z] "POST /istio.mcp.v1alpha1.ResourceSource/EstablishResourceStream HTTP/2" 200 - 1671 9758 300008 - "-" "grpc-go/1.24.0" "f88ece7f-e28f-454b-9bd0-2bf22b0a2260" "localhost:15019" "100.68.194.145:15019"`

It looks like the format of the log is:
`"[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH):256% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\"\n"`

However, if this is correct, then the duration is going to be 300 008ms, which does not sound correct. Do you have any idea what field stands behind the “300 008" value? If it’s time, is it in milliseconds, microseconds, nano, or?

**Comment by dio** [comment]
According to https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage.html?highlight=duration `%DURATION%` gives you "Total duration in milliseconds of the request from the start time to the last byte out." 

What makes you think `300008` in milliseconds is wrong?

**Comment by simeongr** [comment]
From what I know, this is internal communication within the K8s cluster, and 300 000ms equal to 5m, which sounds way too much.

**Comment by yanavlasov** [comment]
Looks like request was closed due to a time out.

**Comment by nvasilev98** [comment]
In continuation of Simeon's thought, we have researched the envoy's implementation and we figured out that the duration is returned in nanoseconds. Here are the following functions that are responsible for returning duration:



```

absl::optional<std::chrono::nanoseconds> duration(absl::optional<MonotonicTime> time) const {
  if (!time) {
      return {};
    }
    return std::chrono::duration_cast<std::chrono::nanoseconds>(time.value() -
                                                                start_time_monotonic_);
  }




absl::optional<std::chrono::nanoseconds> requestComplete() const override {
    return duration(final_time_);
  }


```

And in the test function, they compare it to nanoseconds:

https://github.com/envoyproxy/envoy/blob/105e3f1559c51f5098de1e021abefeee40844dfb/test/common/formatter/substitution_formatter_test.cc#L312

Are we looking at the wrong thing? Is the duration converted from nanoseconds to milliseconds in another piece of code?

**Comment by yanavlasov** [comment]
It is converted to milliseconds here: https://github.com/envoyproxy/envoy/blob/ae7d84132858d831286a6b079fab8271faa451f5/source/common/formatter/substitution_formatter.cc#L450

**Comment by itsLucario** [comment]
How can we get the `REQUEST_TX_DURATION` or `RESPONSE_TX_DURATION` or `DURATION` in microseconds or even the
