### ISSUE TITLE
Why the response status use 503 instead of 502 when the connection reset by peer scenario?

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#14201]
Why the response status is 503 instead of 502 when the connection reset by peer scenario?
503 is means the server is currently unable to handle the request `due to a temporary overloading or maintenance of the server`. 
502 is means the server, while acting as a gateway or proxy, `received an invalid response` from the upstream server it accessed in attempting to fulfill the request.

**Comment by mattklein123** [comment]
Historical reasons. You can remap it using the local reply mapper if you want.

**Comment by wangfakang** [comment]
> Historical reasons. You can remap it using the local reply mapper if you want.

ok, thx. And will later versions solve this problem?

**Comment by mattklein123** [comment]
> ok, thx. And will later versions solve this problem?

No, I doubt we will change the default here as I don't think the churn is worth it. HTTP status codes are somewhat arbitrary across the internet to be honest.
