### ISSUE TITLE
Windows: reverse_bridge_integration_test is flaky

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#14218]
*Description*:

`//test/extensions/filters/http/grpc_http1_reverse_bridge:reverse_bridge_integration_test` is flaky on Windows Platform.

See #13954 and pipeline run https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/59181/logs/109

**Comment by rmiller14** [comment]
Duplicate of #14106 

I confirmed that this issue no longer repros on the latest master.  I investigated this issue for a few days, and the failure had the same symptoms as #14106.
