### ISSUE TITLE
Does envoy support TCP-SNI proxy

### ISSUE THREAD

**Issue by rapatchi** [envoyproxy/envoy#14214]
*Title*: *Does envoy support TCP-SNI proxy*

*Description*:
We need a TCP proxy where we can want to route connections based on SNI hello packet without doing SSL termination. Is this supported in envoy?. We need something as mentioned in relevant links.

*Relevant Links*:
>https://fabiolb.net/feature/tcp-sni-proxy/

**Comment by phlax** [comment]
hi @rapatchi - yes it does

there is an example in a PR waiting to land

you can see the docs for the PR here https://storage.googleapis.com/envoy-pr/ced9f8e/docs/start/sandboxes/tls-sni.html

the docs need some work, specifically regarding tls/sni passthrough (not 100% if that is what you were looking for)

the examples in the PR should work, or you can just look at their config

the PR is here #13975

**Comment by rapatchi** [comment]
@phlax Could you help me understand one thing in the example mentioned above?. There is no SSL termination happening on envoy right ?. The only SSL termination that is happening is on the domain endpoints right ?

**Comment by phlax** [comment]
@rapatchi yes that is a possibility - tls/sni passthrough

in the examples the third one is an example of this

**Comment by jmarantz** [comment]
Looks like this has been answered.
