### ISSUE TITLE
Support hashing on multiple headers (and other criteria) in route hash policy

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1422]
The v2 RDS supports a `repeated` hash policy, but today we only hash on a single header field. Support for multiple hash criteria should be added for v2 implementation completion.

**Comment by akonradi** [comment]
What are the semantics of multiple hash policies? For example, if both header and cookie hash policies were specified, would the expected behavior be to hash the header and cookie together? If so, what effect does ordering of polices have?

**Comment by htuch** [comment]
I think the idea is that the hash is a function of all these individual inputs. Ordering probably doesn't matter; you might get a different hash function if you do header then cookie vs. cookie then header, but for a given policy order you should get the same results each  time for the same request headers.
