### ISSUE TITLE
Access log command operator for HTTP request size including headers

### ISSUE THREAD

**Issue by tomboc** [envoyproxy/envoy#14230]
*Title*: *Access log command operator for HTTP request size including headers*

*Description*:
Add a way to include the full size of a HTTP request, including headers, in access log entries.

Currently the command operators %BYTES_SENT% and %BYTES_RECEIVED% render the size of HTTP body, excluding headers. Add new command operators or specifiers for the existing ones to render the size of a HTTP request or response including:
* request line / status line
* headers
* body
* trailers

*Relevant Links*:

* (https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators)

**Comment by josheinhorn** [comment]
Alternatively to a new field for the full request/response sizes, could we do the same thing being done in the gRPC Access Logger i.e. add new log command operators for [request header bytes](https://github.com/envoyproxy/envoy/blob/7985d815e49f7bd899998436f615ae5497bfff8c/api/envoy/data/accesslog/v3/accesslog.proto#L384) and [response header bytes](https://github.com/envoyproxy/envoy/blob/7985d815e49f7bd899998436f615ae5497bfff8c/api/envoy/data/accesslog/v3/accesslog.proto#L408)? Looks like both `RequestHeaderMap` and `ResponseHeaderMap` are available to the [access log formatter](https://github.com/envoyproxy/envoy/blob/4d77fc802c3bc1c517e66c54e9c9507ed7ae8d9b/source/common/formatter/substitution_formatter.cc#L116), and both have a [`byteSize`](https://github.com/envoyproxy/envoy/blob/29adffbee09233899e459a522c9335dc82620ace/include/envoy/http/header_map.h#L507) method. This doesn't appear to capture the request/status lines and trailers, but it is a simpler MVP that can be iterated on. WDYT?

**Comment by qiwzhang** [comment]
It should be easy to add following operators:
* %REQUEST_HEADER_BYTES%
* %RESPONSE_HEADER_BYTES%
* %RESPONSE_TRAILER_BYTES%

But it will require more work to add size for request/status line.

It it is OK, please assign issue to me,  I can work on it.

**Comment by qiwzhang** [comment]
I am going to work on it soon.
