### ISSUE TITLE
Expand the area of ScopeTrackedObject usage

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#14249]
Expand the area of `ScopeTrackedObject` usage.

Currently the `ScopeTrackedObject` is used at the L7 stream level. The mechanism essentially registers that the dispatcher is doing some particular work.

When a Fatal Error occurs on a thread, we invoke several debug actions on the dispatcher that encountered the error, trying to also leverage the `ScopeTrackedObject` (what it was working on at the time) to give additional insight into the crash. 

With this mechanism as is, there are many parts of the pipeline (see image below) that if we "burst" (crashed) there we'd get no additional information. Furthermore, even when we do crash at the L7 level we have room to improve what we dump -- we don't dump some useful L4 information such as IP address IIRC. 

![Stream Pipeline](https://user-images.githubusercontent.com/3191890/100923315-0272da00-34ad-11eb-8573-0b74abc1d43c.png)

Ideally, we should be able to crash along any point of the pipeline and get information from the earlier phase from the pipeline as well. This will likely mean extending what objects implement the `ScopedTrackedObject` interface, and probably changing how the dispatcher tracks `ScopeTrackedObject`s, perhaps as a stack vs as a single object.

Let me know if that makes sense, thanks.

**Comment by mattklein123** [comment]
+1 this makes sense to me. I agree that we should be able to track multiple scopes and then just have them all dump at once.

**Comment by antoniovicente** [comment]
Tracking a stack of ScopeTrackedObjects makes sense to me.  I would suggest changing the fatal action debug interface to take a list/vector of tracked objects rather than invoking the interface for each object in the stack.

**Comment by antoniovicente** [comment]
Another possible question is if it would be possible to dump the HTTP context when there's a crash at the connection level.  This could be possible if there was a way for objects to register trackers with their parent object.  Note that there would have to be some indirections in the ScopeTrackedObjects registration, so that an HTTP context that is added or removed after connection processing starts is properly dumped on crash.
