### ISSUE TITLE
Support regex path matching in route table

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1425]
The v2 API has committed to support for regex matching for route matches. This will only be enabled when regexes are specified in the route configuration (and as a result, will only imply a performance cost in this situation). This issue tracks implementation work on this.

**Comment by delisdeli** [comment]
This would be great for the following path forwarding use case:
`/foo/{foo_id}/bar/{bar_id}` to `/foodle/{foo_id}/barble/{bar_id}`
