### ISSUE TITLE
Some of the docker images referred to in the docs are no longer available

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#14269]
### description

some of the docs refer to images that arent available on dockerhub, eg:

https://www.envoyproxy.io/docs/envoy/v1.14.0/start/start#quick-start-to-run-simple-example

**Comment by mattklein123** [comment]
@phlax is this due to the DockerHub changes? This seems bad but I'm not sure there is much we can do about it?

**Comment by phlax** [comment]
it could be - might be due to their new retention policies

if we know why the images have disappeared we could maybe do something about it - like republish them

**Comment by phlax** [comment]
i think this has been resolved now
