### ISSUE TITLE
Update max_stream_duration dynamically

### ISSUE THREAD

**Issue by Chuongv** [envoyproxy/envoy#14260]
# Allow ability to update max_stream_duration dynamically

## Description

We want to do some work at the start of the decodeHeaders of our downstream request and not count it against our `max_stream_duration`. We can dynamically update the request timeout by setting `x-envoy-upstream-rq-timeout-ms` in our decodeHeaders to account for this. However the timer is stopped after the request decoder filter ends or the response has started.

Given a response could send the headers (disarming the timer) and be streaming the body, we have no way to enforce this other than using `max_stream_duration`.

> The HTTP protocol max_stream_duration is defined in a generic message used by the HTTP connection manager. The max stream duration is the maximum time that a stream’s lifetime will span. You can use this functionality when you want to reset HTTP request/response streams periodically. You can’t use request_timeout in this situation because this timer will be disarmed if a response header is received on the request/response streams. This timeout is available on both upstream and downstream connections.

From [Envoy Docs](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts)

## Solution

Allow updating the `max_stream_duration`

[Envoy protocol options](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-field-core-httpprotocoloptions-max-stream-duration)

**Comment by mattklein123** [comment]
Seems reasonable to allow this to be modified by a filter somehow. Feel free to propose something concrete!

**Comment by Shikugawa** [comment]
@mattklein123 This feature can be required in a special situation. Could we reopen this?
