### ISSUE TITLE
Rate limit: add soft limiting capability to local rate limit filter

### ISSUE THREAD

**Issue by nitgoy** [envoyproxy/envoy#14268]
*Title*: *Add soft limiting capability to local rate limit filter*

*Description*:
>In some scenarios, it's useful to enforce the rate limits only when the system is under stress while applying no or higher limits during normal operations. This way the effects of rate limiting are not seen unless the system is getting close to being stressed by the requests or connections rate.
>This is useful in scenarios when you've several instances of rate limit filter that individually apply the rate limits on a subset of the requests.

I'm not sure if we can use the signals from resource monitors to be used as a sign of under stress but it would be ideal. That way the rate limit filter can be hooked with various resource monitors such as memory, connections, cpu, network, etc.
Alternatively, we can have a separate config that can be compared against the global request/connection rate to check whether to enforce the rate limits.

**Comment by mattklein123** [comment]
Interesting idea. I wonder if we could use a bunch of the scalable timer work that was implemented by @akonradi to also scale local rate limits?

**Comment by akonradi** [comment]
This sounds like the inverse use case for the scaled timers: as the load increases, the "allow next request" timeout should go up, not down. I don't know how the rate limiting is implemented though, so there might be an opportunity I'm missing. If not, we should still be able to use the scaling overload action trigger to produce a load factor percentage, and use that to change the rate limit timeout.

**Comment by mattklein123** [comment]
> This sounds like the inverse use case for the scaled timers: as the load increases, the "allow next request" timeout should go up, not down. I don't know how the rate limiting is implemented though, so there might be an opportunity I'm missing. If not, we should still be able to use the scaling overload action trigger to produce a load factor percentage, and use that to change the rate limit timeout.

Yeah I was mostly just suggesting that the scaling infra could be used for this as it sounds pretty similar.

**Comment by nitgoy** [comment]
I'm not familiar with the scaling infra. Can you point to its documentation/design?

**Comment by akonradi** [comment]
I think what you want is to be able to use a range trigger to set an overload action's value. https://github.com/envoyproxy/envoy/pull/12352 added the range trigger, and https://github.com/envoyproxy/envoy/pull/13120 shows how you can use it with an existing overload action. There's a scaled timer infra that is built on top of that, but I don't think you want that since it scales in the wrong direction (load factor goes up -> timeouts go down).
