### ISSUE TITLE
ForbiddenException calling AWS public or private API through Envoy

### ISSUE THREAD

**Issue by hsw48** [envoyproxy/envoy#14285]
I have a public AWS API set up that returns a 403 Forbidden response when called through Envoy. I can access it successfully going directly from Postman and through my API Gateway when bypassing Envoy. So the issue seems to be with how Envoy is making the request.

This API is meant to be private, but was made public to debug why it was unaccessible even from within the VPC. It turns out to not even be accessible while public if called via Envoy.

In Envoy logs I get:
':status', '403'
'x-amzn-errortype', 'ForbiddenException' 
...

In Envoy config we are using TLS for the transport socket:

    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:

Like I said previously, the same request made directly from Postman or through our Gateway without Envoy is successful. Let me know if there is any other info I can provide. Thanks

**Comment by dio** [comment]
For my understanding:

You have: 

1. client -> API Gateway
2. client -> Envoy -> API Gateway

and you fail only when doing #2? Could you compare what are being sent from client to API Gateway vs envoy to API Gateway?

**Comment by dio** [comment]
I think @lavignes from AWS has an answer here: https://envoyproxy.slack.com/archives/C78M4KW76/p1607119841154300?thread_ts=1607118102.154200&cid=C78M4KW76. Thank you @lavignes!

**Comment by vovkman** [comment]
If anyone comes across this in the future, the solution for me was to set `:authority` header equal to dns
