### ISSUE TITLE
Deflake xds_integration_test for Windows release builds

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#14286]
#13688 enabled xds_integration_test for Windows, but this appears to be flaking, see:

* (Presubmit) https://dev.azure.com/cncf/envoy/_build/results?buildId=59693&view=logs&j=4afecb4c-71c7-5b5c-ab99-a70ed4c927ad&t=4cd2fc51-3314-5d69-4df3-f765ae0c08dc
* (Postsubmit) https://dev.azure.com/cncf/envoy/_build/results?buildId=59350&view=logs&s=27eddb93-7805-576c-c80f-37b2176e40f7&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd

The failure happens in roughly the same test cases. This may have to do with edge triggered behavior. I'm going to disable temporarily and leave this as a TODO for @envoyproxy/windows-dev.

**Comment by davinci26** [comment]
Fixed the flakiness issue with #14447
