### ISSUE TITLE
logs: add expressions to textual logs

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#14291]
Consider adding CEL-based expressions to stdout loggers either as an extension to file access logger or a separate logger. The expressions could be passed as parsed ASTs or raw text to be parsed locally with ANTLR.

There are two benefits:
- conditional expressions (log this or that based on some clause);
- consistency with other CEL-based integrations, e.g. rbac or istio's telemetry customizatons.

cc @douglas-reid @lizan

**Comment by mattklein123** [comment]
@kyessenov can't this just be a new access log filter that is a CelFilter?

**Comment by lizan** [comment]
Yeah this could be a access log filter
