### ISSUE TITLE
Remove memory  allocation in Win32 WatcherImpl::directoryChangeCompletion

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#14307]
In `WatcherImpl::directoryChangeCompletion` we allocate a `Buffer::OwnedImpl` to call `ioHandle` `write`.

This should be changed to `writev` to prevent memory allocation or we should implement and use #14244

**Comment by davinci26** [comment]
cc @envoyproxy/windows-dev

**Comment by rmiller14** [comment]
I don't have the ability to assign this, but I went ahead and submitted a PR for this issue.
