### ISSUE TITLE
Issue and PR template

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1432]
Per offline discussion we will create templates for opening issues as well as PRs that will help make things a bit more efficient.

For defect issues: Things like common debugging tips and data to include.
For PRs: Description of change, any extra testing recommended, regression risk, etc.

We can propose the templates here so people can comment.

**Comment by ccaraman** [comment]
# Proposed PR Template:
#### Description
What does this PR do? If fixing a bug, please describe what the original issue is and how the change resolves it. If applicable, refer to the tracking issue.

#### Risk level
Low/Medium/High - explain

#### Testing Validation
- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Extra - Please explain: Stats, Smoke test, ...

# Proposed Issue Template:
#### Description
What issue is being seen? If feature request, please describe desired behavior and what scenario it enables. 

#### Repro Steps (Optional)
If applicable, please include configs, sample requests, etc...

#### Call Stack (Optional)
Please refer to [Envoy Bazel documentation](https://github.com/lyft/envoy/blob/c3ad82cf34175d3ff65840f35425a126e5a4b655/bazel/README.md#stack-trace-symbol-resolution)  for more information on gathering a stack.

**Comment by mattklein123** [comment]
A few comments:

For the PR template, testing validation section, I would make it clear that we don't expect all testing types in all PRs. I would make it more clear that people should think about different testing types depending on PR risk and to discuss why they did what they did.

For the issue template, can we be more specific, and split into issue requests and bug reports? For issue requests, we should ask for details on the feature being requested, links to standards if applicable, etc. For bug reports, we should be explicit and ask for repro steps, and minimally the config, /cluster, /stats, etc. We should eventually also link to the tool that @htuch is working on. In terms of optional call stacks, if it's a crash, the call stack should be required.

**Comment by mattklein123** [comment]
@htuch @dnoe @alyssawilk any comments on ^ ?

**Comment by htuch** [comment]
Thanks for adding the templates @ccaraman. I like the idea of an issue template. Here's some ideas of things we could ask for:

* `envoy-static --version`
* Execution environment (e.g. OS, distribution, etc.)
* https://github.com/lyft/envoy/pull/1456 tarball (or logs, stats and other admin endpoints, in addition to the config). TBH, the most useful stuff I've seen so far when chasing bugs on GH is (1) logs gathered at `-l trace` level (2) stats from the admin endpoint (3) config JSON.

For the PR template, I'm actually a fan of not going too far down the path of a Markdown style template, but prefer to specify an ASCII format with mandatory tags. E.g.

```
<subsystem>: one line summary.

What does this PR do? If fixing a bug, please describe what the original issue is and how the change resolves it. If applicable, refer to the tracking issue.

risk-level: (low|medium|high)
testing: <explanation of unit and integration tests>
[optional deprecated: <description of what is deprecated>]
[optional release-notes: <description of what to add to next point release notes>]

[optional Fixes #issue]
```

Or something like that. It's nice to be able to prep the initial PR description in `vi` and to have some of this information expressed in tags, in particular for automating handling of deprecation and release notes. To do this, it would be good to have some mandatory validation of the commit message.

**Comment by htuch** [comment]
Also, on risk level, I think it would be good to explain what this means in more detail. Is this basically "risk of crashing/dropping/misdirecting production traffic"? Also, examples of what is expected for each level would be good. My naive guess would be `low` is most small changes or a new optional filter, `medium` is localized with heavy testing and `high` is really complicated things (e.g. flow control, replacing the gRPC transport, etc).

**Comment by mattklein123** [comment]
@ccaraman can we actually drop the templates into a public gdoc? I think it will be easier to iterate/comment.

**Comment by rshriram** [comment]
how do you estimate risk level of a feature PT or bug fix PR?
may be have something like "feature w/ config, behavior change,bug fix, etc" ?

**Comment by ccaraman** [comment]
@rshriram It is hard to write a guide on how to estimate the risk level. The PR owner should have an idea of how risky the change is or collaborate with someone more familiar to understand the potential impact and go over testing strategies.

**Comment by ccaraman** [comment]
@mattklein123 @htuch  [Here](https://docs.google.com/document/d/1oHIZOCT5ldBCxx_T9_RBZj2zBGNQ9sVjeszghqeGMEA/edit?usp=sharing) is the google doc with the template proposals. Please let me know if you can't access/comment on it.

**Comment by htuch** [comment]
Looks good, added some comments in the doc @ccaraman.

**Comment by mattklein123** [comment]
Done!
