### ISSUE TITLE
Noop HTTP Filter

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#14322]
When using ECDS to provide a filter configuration, it would be helpful to be able to provide a noop filter that would act as a passthrough. This would allow management servers to respond with a noop config most of the time and replacing it with another filter whenever necessary. 

With the unified matching work and support for skipping filter execution this would be possible to express via an always true matcher that skips filter execution, but the need for an actual filter configuration (that would always be skipped) makes this a bit awkward.

Given that, it seems like registering the PassthroughFilter as a proper HTTP filter would be an easy way to provide this functionality. 

Thoughts? @mattklein123

**Comment by snowp** [comment]
Another option would be to handle an ECDS response that doesn't contain a filter config as indicating that a noop filter should be used, though this seems less explicit.

**Comment by mattklein123** [comment]
Per your point, if the config is optimized down to always skip, can't we just remove the filter entirely?

**Comment by snowp** [comment]
Relying on the match tree to skip the filter is a bit awkward since we would still require a filter config to be specified. While we can configure some arbitrary filter in way where it acts like a NOOP filter (e.g. fault filter with 0% fault chance), it seems a bit gross API-wise. Maybe we can make it possible to omit the filter config if the match tree can be reduced to "always skip"? 

cc @htuch since Matt is out

**Comment by htuch** [comment]
@snowp can you share two example configs here (for posterity and also because I don't think I have the full context paged in)?
