### ISSUE TITLE
status code when retrying

### ISSUE THREAD

**Issue by storyicon** [envoyproxy/envoy#14373]
When a request is retried several times and responds, only the status code of the last response can be seen in the envoy log. Is there any way to obtain the status code of each response?

**Comment by yanavlasov** [comment]
You mean in the access log? There is currently no way to do it.

**Comment by storyicon** [comment]
For example, in nginx we can achieve this effect:

![image](https://user-images.githubusercontent.com/29772821/102332870-a38e8400-3fc7-11eb-9135-3162b0afe2ee.png)

We can see the `elapsed` / `addr` / `status code` of each retry. We are using these variables in nginx:
```
$upstream_status
$upstream_addr
$upstream_response_time
```
This is very helpful for positioning problems. Is there any plan to support in the future?

**Comment by yanavlasov** [comment]
As far as I know there are no plans. Retry information would need to be plumbed through StreamInfo or router filter metadata. @mattklein123 for any other comments.

**Comment by mattklein123** [comment]
I'm pretty sure every try is in the upstream access logs? cc @zuercher
