### ISSUE TITLE
ALPN documentation could use some clarifications

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#14378]
*Title*: ALPN documentation could use some clarifications

*Description*:
The current documentation for https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto.html?highlight=upstreamtlscontext#extensions-transport-sockets-tls-v3-commontlscontext `alpn_protocols` seems to be missing some information

The doc mentions:
> Supplies the list of ALPN protocols that the listener should expose.

However, this field is also present for UpstreamTlsContext in cluster, where the behavior isn't explained.

Additionally, as far as I can tell Envoy is not actually doing an negotiation of application protocol to use in the cluster (and instead uses ProtocolSelection). Per https://tools.ietf.org/html/rfc7301#section-3.2, I would have expected a mismatch of UpstreamTlsContext and DownstreamTlsContext alpn_protocols to result in an error while it seems envoy does not. If this is intentionally, it would be useful to have a note in the docs about this.

**Comment by dio** [comment]
cc. @lizan

**Comment by lizan** [comment]
Isn't this a dup of https://github.com/envoyproxy/envoy/issues/3431? In short, upstream ALPN isn't supported now and there's ongoing work #14239 

> Additionally, as far as I can tell Envoy is not actually doing an negotiation of application protocol to use in the cluster (and instead uses ProtocolSelection). Per https://tools.ietf.org/html/rfc7301#section-3.2, I would have expected a mismatch of UpstreamTlsContext and DownstreamTlsContext alpn_protocols to result in an error while it seems envoy does not. If this is intentionally, it would be useful to have a note in the docs about this.

I didn't fully get this part, are you saying Envoy listener isn't sending ` a fatal "no_application_protocol" alert.` when client advertises protocol it doesn't support?

**Comment by howardjohn** [comment]
So the field doesn't do anything whatsoever in the upstreamtlscontext?
 What I have seen is my upstream and downstream alpn do not match but I don't get
a fatal "no_application_protocol" alert, but if upstream tls context does nothing maybe that explains it.
