### ISSUE TITLE
Question: Should the maximum size of response headers be configurable?

### ISSUE THREAD

**Issue by esmet** [envoyproxy/envoy#14370]
It looks like we added configuration for max_request_headers_kb and talked about the response header max size use case, but didn't implement it in https://github.com/envoyproxy/envoy/pull/5859

Do we still want this to be configurable?

**Comment by alyssawilk** [comment]
I think it'd be good to have, looks like there just hasn't been a pressing need.
Could be considered part of untrusted downstreams, cc @yanavlasov

**Comment by yanavlasov** [comment]
Currently it is hardcoded to 60Kb, whichi we considered to be ok for untrusted downstreams. I will bring it up in our internal discussion to see if there other use case where it may be needed.
