### ISSUE TITLE
more complete dubbo protocol support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#14391]
*Title*: *more complete dubbo protocol support such as group/headers match*

*Description*:
>The current dubbo proxy only provides the ability to route based on interface and method. Although it does expose an API for group/headers matching, it does not implement it.

**Comment by alyssawilk** [comment]
cc @zyfjeff @lizan

**Comment by zyfjeff** [comment]
#14529 Integrating [hessian2-codec](https://github.com/alibaba/hessian2-codec) can help dubbo implement more complex routing.
