### ISSUE TITLE
network.client_ssl_auth.v3.ClientSSLAuth.auth_api_cluster   caches signature list on service failure

### ISSUE THREAD

**Issue by salrashid123** [envoyproxy/envoy#14392]
[extensions.filters.network.client_ssl_auth.v3.ClientSSLAuth](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/client_ssl_auth/v3/client_ssl_auth.proto#extensions-filters-network-client-ssl-auth-v3-clientsslauth) 

Describes an external serivce that will return a list of valid client cert signatures to allow.   However, once a client envoy service contacts the server and retrieves the valid list, the client envoy will cache the valid list if the upstream `auth_api_cluster` service unresponsive.

---

The full config/repro steps is detailed in my test repo here:
[https://github.com/salrashid123/envoy_mtls](https://github.com/salrashid123/envoy_mtls)

to repro, 
1. Run envoy
  `envoy -c server.yaml --base-id 0 -l debug`
2. Attempt to access upstream service
  this should fail
```curl -v -H "host: http.domain.com"     --resolve  http.domain.com:8081:127.0.0.1    --cert certs/client.crt    --key certs/client.key     --cacert certs/tls-ca-chain.pem      https://http.domain.com:8081/get```
3. Run `auth_api_cluster` service (which appens to be envoy returning static cert)
`envoy  -c certsvc.yaml --base-id 1`
4. Attempt to access upstream service.  
   this will succeed
5. Stop `auth_api_cluster` service
6. Attempt to access upstream service. 
  this will succeed.  Expected fail.

---

Maybe this is working as intended but i expected pessimistic authorization.

**Comment by alyssawilk** [comment]
I think that's the behavior I would expect as well, but I suspect documentation about fail-open vs fail-closed would be helpful.
cc @ggreenway

**Comment by ggreenway** [comment]
Yeah, I think I would expect this to fail also, but to do so reasonably, I think we need at least one more configuration knob: the TTL of the cached response. I don't know that I would classify this as a bug or not though; it's under-specified in the documentation.

**Comment by salrashid123** [comment]
not to intentionally throw a whole wrench into this but is there a specific reason why a _list_ of valid certs are returned here anyway (vs something like an making an outbound OCSP request or alternatively the configuration for `ClientSSLAuth` accepts  CAs as a dataSource and locally verifies ocsp-stapled requests from the downstream?

any of the above would take a signifiant rewor for this filter though

**Comment by salrashid123** [comment]
re: ocsp stuff, 
  found it here:  https://github.com/envoyproxy/envoy/pull/12685

re: bug or not, 
 if it makes any difference, i'd argue it is a bug:  for a security feature like this, its expected to failclosed.
