### ISSUE TITLE
Envoy v1.16.2 release image not pushed to Dockerhub

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#14400]
Moving from slack thread: https://envoyproxy.slack.com/archives/C78HA81DH/p1607556532055200

The job failed on the initial backport PR push but passed on a [subsequent retry,](https://dev.azure.com/cncf/envoy/_build/results?buildId=60158&view=logs&jobId=703bebaa-c8b3-579f-1e1c-845f8cf67043&j=703bebaa-c8b3-579f-1e1c-845f8cf67043&t=24c5c8d8-c9f4-551a-ba59-33a0004adbfa) ([raw log here](https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/60158/logs/239)) however it did not push the `envoyproxy/envoy` image with the `v1.16.2`  and updated `v1.16-latest` tags. That pipeline run did build the `-dev` named images, which leads me to believe the AZP branch/tag name environment variable was not what we expected it to be in the passed run (maybe hard to tell without admin access to the pipeline).

**Comment by sunjayBhatia** [comment]
@envoyproxy/stable-maintainers

**Comment by sunjayBhatia** [comment]
@cpakulski

**Comment by cpakulski** [comment]
I see that image was successfully pushed to https://hub.docker.com/r/envoyproxy/envoy-google-vrp-dev/tags?page=1&ordering=last_updated

**Comment by sunjayBhatia** [comment]
Yep, the `vrp` image was pushed, but not the main release https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&ordering=last_updated

**Comment by cpakulski** [comment]
1.16.2 docker image has been successfully pushed to DockerHub.

**Comment by sunjayBhatia** [comment]
thanks!

**Comment by sunjayBhatia** [comment]
closing, tagged image: https://hub.docker.com/layers/envoyproxy/envoy/v1.16.2/images/sha256-996a3118589f52023e99ae5ef77cdc84c936384375fb68a597b655202f4285bc?context=explore
