### ISSUE TITLE
Resolve python dependency patch in protobuf

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#14412]
Complete the discussion in https://github.com/envoyproxy/envoy/pull/14253#discussion_r536912177.

The issue is conflicting python module definitions for `google.protobuf` and `google.rpc` under `google` coming from two repos, which requires patching in the module lookup code.

cc @htuch

**Comment by busunkim96** [comment]
If the blocker is `google.api.expr` published to PyPI, it looks like that is doable. It would most likely be published to the existing [google-api-common-protos](https://pypi.org/project/googleapis-common-protos/) package.

**Comment by htuch** [comment]
I think we also consume `annotations.proto` from `google.api.expr`. Is there some way we can validate this with a mock `pip` build?

**Comment by busunkim96** [comment]
`google/api/annotations.proto` is already published in the package. (see [github repo](https://github.com/googleapis/python-api-common-protos/tree/master/google/api)). 

```
python3 -m pip install google-api-common-protos
```

```
busunkim@busunkim:~/github/python-aiplatform$ python3
Python 3.6.9 (default, Feb 24 2020, 21:10:07) 
[GCC 9.2.1 20190909] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.api import annotations_pb2
```

Happy to set up a branch on https://github.com/googleapis/python-api-common-protos with the `google.api.expr` protos if that is what is needed.

**Comment by kyessenov** [comment]
These are all dependencies:
```
@com_google_googleapis//google/api/expr/v1alpha1:checked_py_proto
@com_google_googleapis//google/api/expr/v1alpha1:syntax_py_proto
@com_google_googleapis//google/api/expr/v1alpha1:checked_py_proto_genproto
@com_google_googleapis//google/api/expr/v1alpha1:syntax_py_proto_genproto
@com_google_googleapis//google/rpc:status_py_proto
@com_google_googleapis//google/api:httpbody_py_proto
@com_google_googleapis//google/api:annotations_py_proto
@com_google_googleapis//google/api:http_py_proto
@com_google_googleapis//google/rpc:status_py_proto_genproto
@com_google_googleapis//google/api:httpbody_py_proto_genproto
@com_google_googleapis//google/api:annotations_py_proto_genproto
@com_google_googleapis//google/api:http_py_proto_genproto
```

If we can remap these to pre-generated committed versions, that would probably work!

**Comment by kyessenov** [comment]
cc @TristonianJones: we'd like to have google api expr Python protos published, instead of bazel build in googleapis.

**Comment by busunkim96** [comment]
I created a branch on python-api-common-protos with the `google/api/expr` protos https://github.com/googleapis/python-api-common-protos/tree/add-api-expr. (PR: https://github.com/googleapis/python-api-common-protos/pull/27)

Releasing will need to wait for next year since I need to check that releasing these protos in this package is OK.

**Comment by kyessenov** [comment]
Not stale, but fell off my radar.
