### ISSUE TITLE
response_headers_to_remove remove server header

### ISSUE THREAD

**Issue by tydurd** [envoyproxy/envoy#14421]
Hi team, I have the following envoy configuration (envoy v.1.12.2) and can't find a way to remove 'server' from response headers.

  static_resources:
        listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
          - filters:
            - name: envoy.http_connection_manager
              config:
                server_name: "demo"
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  response_headers_to_remove:
                    - server
                    - x-envoy-upstream-service-time
                  name: local_route
                  virtual_hosts:
                  - name: bookservice
                    domains:
                    - "*"
                    routes:
                    - match:
                        prefix: "/" 
                      route:
                        cluster: localcluster
                http_filters:
                - name: envoy.router
                  config: {}
        clusters:
        - name: localcluster
          connect_timeout: 2.25s
          type: static
          lb_policy: round_robin
          hosts:
          - socket_address:
              address: 127.0.0.1
              port_value: 8080
      admin:
        access_log_path: "/dev/stdout"
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8081

I've tried removing the header both in the virtual host config and route config without success. What am I missing?

**Comment by alyssawilk** [comment]
response_headers_to_remove removes headers sent by upstream, but Envoy often adds its own server header.  
There's an HCM field "server_header_transformation" - I suspect setting it to PASS_THROUGH may solve your problem.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=server_header_transformation#envoy-v3-api-enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-serverheadertransformation
