### ISSUE TITLE
NPE when wasm bootstrap extension makes http calls.

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy#14420]
Currently, when a wasm bootstrap extension tries to make an http call, envoy will crash.
The reason for this crash, is that when wasm bootstrap extensions are initialized ([here](https://github.com/envoyproxy/envoy/blob/7d348d1b65d3c5ae58d0259e397fbd3df8686f11/source/server/server.cc#L432)), the cluster manager is not yet initialized (that happens a bit further in the code, [here](https://github.com/envoyproxy/envoy/blob/7d348d1b65d3c5ae58d0259e397fbd3df8686f11/source/server/server.cc#L535)) and is nullptr.

The confusing part is that clusterManager is returned by reference from ServerFactoryContext, implying that it cannot be nullptr.

An "easy" (non-)solution would be to move the bootstrap extension until after the cluster manager is initialized, but I think that would break the "default_socket_interface" feature.

A "hacky" solution is to wrap the createWasm call in WasmFactory::createBootstrapExtension ([here](https://github.com/envoyproxy/envoy/blob/7d348d1b65d3c5ae58d0259e397fbd3df8686f11/source/extensions/bootstrap/wasm/config.cc#L73)) in a lambda, and post it to the dispatcher, to defer its execution. This way it should execute after the cluster manager is initialized (I didn't test this yet).

Would love to get some feedback on how to go about this before starting a PR, as the current "hacky" solution, a partialy initialized `ServerFactoryContext` still makes it into the bootstrap extension which is not ideal.

Another thought that comes to mind is to send the bootstrap extension a more minimal context object, and add another callback that's called once the cluster manager is initialized.

cc @EItanya

**Comment by alyssawilk** [comment]
cc @lizan @mathetake @PiotrSikora

**Comment by yuval-k** [comment]
after think about this, I think a reasonable solution is to remove the ServerFactoryContext on creation time, add a callback to BoostrapExtension that will receive it when it is ready. I'm working on this and should have PR ready later today

**Comment by mandarjog** [comment]
@mdhume how did you address this problem in your singleton ?

**Comment by mdhume** [comment]
@mandarjog We are setting up the singleton Wasm filter in Istio 1.5.8 so we use the previous `wasm_service`specification in the bootstrap config and not `bootstrap_extensions`. The corresponding source is https://github.com/istio/envoy/blob/bc117b4449ab2b63f4631d712ae51328f39c931e/source/server/server.cc#L432 . In that version of the code seems like the cluster manager is being initialized before the wasm service is initialized.
