### ISSUE TITLE
api: CSDS should report status per resource, not per resource type

### ISSUE THREAD

**Issue by markdroth** [envoyproxy/envoy#14431]
The current CSDS protos have the [status](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/service/status/v3/csds.proto#L97) and [client_status](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/service/status/v3/csds.proto#L102) and fields at the resource-type level, not the level of individual resources.  They also provide the SotW system version (for [LDS](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/admin/v3/config_dump.proto#L102), [RDS](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/admin/v3/config_dump.proto#L235), [CDS](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/admin/v3/config_dump.proto#L180), and [EDS](https://github.com/envoyproxy/envoy/blob/5dc58a6a98ae781020f3742c3ee13b48cee670fe/api/envoy/admin/v3/config_dump.proto#L369)), which is effectively a per-resource-type version.

This representation doesn't seem capable of representing the underlying reality, because the transport protocol allows the client to ACK/NACK a strict subset of resources at a given system version.  Here are some scenarios that are not made clear by this representation:

- Server sends RDS response containing resources A and B at system version 1, and client ACKs.  Then resource B is updated, so server sends RDS response containing resource B at system version 2, and client NACKs.  At this point, client has ACKed resource A at system version 1 but has NACKed resource B at system version 2 (so is still using resource B at system version 1).
- Client subscribes to LDS resources A and B.  Server sends both resources at version 1, and client ACKs.  Now client subscribes to resource C.  Server sends a new LDS response containing resources A, B, and C, all still at system version 1.  Resource C is invalid, so client NACKs.  At this point, the client is actually using the current version of resources A and B, but it has NACKed C, all at the same version.
- Pretty much any scenario using the incremental protocol variants.  Unlike the SotW protocol variants, the incremental variants do not use the system version at all; instead, they report a version for each individual resource, and ACK/NACK is based on that version instead of the system version.

I think CSDS should be changed to report both version and status on a per-resource basis instead of a per-resource-type basis.  When using the SotW API, the per-resource version can actually be the system version, but it should still be reported on a per-resource basis, since it can be different for different resources.

For bonus points, in the case where a resource was NACKed, it might be useful to report both the version that was NACKed and the older version that is actually still being used (if any).

CC @fuqianggao @htuch

**Comment by markdroth** [comment]
Actually, it looks like the version *is* per-resource, so it's just the status that's the problem.

**Comment by htuch** [comment]
@fuqianggao WDYT? I seem to remember some confusion over this, e.g. whether we report only the latest acked version vs. earlier ones, but this seems to make sense for finer grained reporting.

**Comment by markdroth** [comment]
From the xDS client's perspective, it seems like it would make sense for the protos to look something like this:

```
message ResourceStatus {
  // The identity of the resource.
  // type_url may be unset for new-style names, where the type is included in the name.
  string type_url = 1;
  string name = 2;

  // If any version of this resource has been ACKed, these fields indicate the version and
  // contents of the resource.
  string version_acked = 3;
  google.protobuf.Any current_resource = 4;

  // If the most recent version of this resource has been NACKed, these fields indicate
  // the version and error message.
  string version_nacked = 5;
  string nack_error = 6;
}

message CsdsResponse {
  repeated ResourceStatus resource_status = 1;
}
```

This seems a lot easier to understand than what is in CSDS today.

**Comment by fuqianggao** [comment]
Yeah, I agree finer grained reporting is useful, and necessary for deltaXds. As long as there is no breaking change, it SGTM.

**Comment by lidizheng** [comment]
There is a similar design in [`config_dump.proto`](https://github.com/envoyproxy/envoy/blob/76bcbd7d31615196d6d7295a741a5329689fdb9e/api/envoy/admin/v3/config_dump.proto#L113) that the listener dump can have active state or error state. In the error state, it stores the received-but-nacked version of listener resource. However, this pattern is not carried over to routes, clusters, and endpoints.

* Is adding the `UpdateFailureState` to other xDS resources an option?
* Or do we prefer to simplify the CSDS responses? We could add it as a separate RPC method. It definitely helps to reduce the complexity of the CSDS implementation.

**Comment by markdroth** [comment]
The current CSDS protocol is really bloated, but I guess we shouldn't break backward compatibility.  Let's just make the changes we need in the current API.  I think this includes two things:

1. We need to add a field for per-resource status.
2. We need to report two versions on a per-resource basis: the current version actually being used on the client (which corresponds to the resource contents reported by the client) and the most recent version seen by the client.  (Those two versions will be different in the case where the client has NACKed the current version and is still using a previous version.)  Presumably, the existing version field in the API should be one of these (I'm not sure which one, but we should figure it out and document it), but we should add a new field for the other one.

@lidizheng, can you put together a PR proposing these new fields, and we can iterate on that?  Thanks!

**Comment by lidizheng** [comment]
Sent out PR https://github.com/envoyproxy/envoy/pull/14689 to add an `error_state` field to all dynamic resources in config dump proto. The missing expressiveness in existing config dump is that if a resource has a newer NACKed version, there isn't a way to tell.

The `error_state` fields are using type `UpdateFailureState`, which already existed in `config_dump.proto`. This PR extends `UpdateFailureState` with an extra `version_info` field to record the latest rejected version.

```protobuf
message UpdateFailureState {
  // What the component configuration would have been if the update had succeeded.
  google.protobuf.Any failed_configuration = 1;
  // Time of the latest failed update attempt.
  google.protobuf.Timestamp last_update_attempt = 2;

  // Details about the last failed update attempt.
  string details = 3;

  // This is the version of the rejected resource.
  string version_info = 4;
}
```

I think the solution is better than offering per-resource synchronization status (not to mention the potential circular dependency issue). For ACKed resource, this field will be empty; for NACKed resource, this field will store the NACKed version with several meta information.
