### ISSUE TITLE
docker: build su-exec in bazel and put in to docker

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#14454]
*Title*: *One line description*

*Description*:
`su-exec` was introduced to drop permission in the docker entrypoint, this has been built in [docker stage](https://github.com/envoyproxy/envoy/blob/master/ci/Dockerfile-envoy#L7-L12) but it should be part of main build and monitored by dependency policy. It also causes some docker build flakiness.

cc @envoyproxy/dependency-shepherds @phlax

**Comment by arkodg** [comment]
happy to pick this up @lizan

**Comment by arkodg** [comment]
can't seem to reproduce the flakiness
here's what I did
```
mkdir builder
ENVOY_DOCKER_BUILD_DIR=builder ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
for i in {1..20}; do docker build -f ci/Dockerfile-envoy -t envoy .;docker builder prune -af; done
```

**Comment by lizan** [comment]
The flakiness is from downloading the source from GH:
https://github.com/envoyproxy/envoy/blob/release/v1.17/ci/Dockerfile-envoy#L8

it may not reproducible easily in your local env though.

**Comment by phlax** [comment]
@lizan @arkodg i think this ticket should be closed now - su-exec is no longer built in the docker recipe
