### ISSUE TITLE
OSX: setting TCP_NODELAY sometimes produces an error

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#1446]
Invoking `setsockopt(,IPPROTO_TCP, TCP_NODELAY,,)` on OSX while the socket is still connecting sometimes results in an error with `errno` set to `EINVAL`. The man page indicate this is because "the socket has been shut down," but it seems to occur during the connection phase as well.

See discussion in #1381. In tests, I've privately modified the code to query the value of TCP_NODELAY after the connection is completed and it has always reported being set even when the error condition is triggered. It remains possible that this is not always true.

If we wanted to remove the possibility of triggering this error, one solution would be to add a flag to the `Network::ConnectionImpl` constructor that indicates TCP_NODELAY is desired. Then when the connection is complete (see `ConnectionImpl::onWriteReady`) we would invoke `setsockopt` or not  based on the flag. The `ConnectionImpl::noDelay` method would no longer be used publicly.

**Comment by terinjokes** [comment]
Peeking into XNU, it looks like this is the relevant block:[[1]][xnu]

[xnu]: https://github.com/opensource-apple/xnu/blob/dc0628e187c3148723505cf1f1d35bb948d3195b/bsd/kern/uipc_socket.c#L4724-L4730

```c
if ((so->so_state & (SS_CANTRCVMORE | SS_CANTSENDMORE)) ==
    (SS_CANTRCVMORE | SS_CANTSENDMORE) &&
    (so->so_flags & SOF_NPX_SETOPTSHUT) == 0) {
    /* the socket has been shutdown, no more sockopt's */
    error = EINVAL;
    goto out;
}
```

I'm running into a similar issue using Envoy on illumos, which has a similar block:[[2]][illumos] ([OS-6312][smartos])

[illumos]: https://github.com/illumos/illumos-gate/blob/f7877f5d39900cfd8b20dd673e5ccc1ef7cc7447/usr/src/uts/common/fs/sockfs/sockcommon_sops.c#L797-L803
[smartos]: https://smartos.org/bugview/OS-6312

```c
/* X/Open requires this check */
if (so->so_state & SS_CANTSENDMORE && !xnet_skip_checks) {
    SO_UNBLOCK_FALLBACK(so);
    if (xnet_check_print)
        printf("sockfs: X/Open setsockopt check => EINVAL\n");
    return (EINVAL);
}
```
