### ISSUE TITLE
How to build asan with clang?

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#14489]
*Title*: *I need some help for building asan with clang*

*Description*:
I tried `bazel test --config=clang-asan ...`, but got:
```
ld.lld: error: undefined symbol: __muloti4
>>> referenced by numbers.cc
>>>               bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/strings/_objs/strings/numbers.pic.o:(absl::operator*(absl::int128, absl::int128))
clang: error: linker command failed with exit code 1
```

After applying the solution in https://bugs.llvm.org/show_bug.cgi?id=16404
```diff
diff --git .bazelrc .bazelrc
index 6a7cd55d0..7d9c1ef49 100644
--- .bazelrc
+++ .bazelrc
@@ -69,6 +69,7 @@ build:asan --copt -fno-optimize-sibling-calls
 # Clang ASAN/UBSAN
 build:clang-asan --config=asan
 build:clang-asan --linkopt -fuse-ld=lld
+build:clang-asan --linkopt -rtlib=compiler-rt

 # macOS ASAN/UBSAN
 build:macos --cxxopt=-std=c++1
```
now I get:
```
ld.lld: error: undefined symbol: _Unwind_Backtrace
>>> referenced by sanitizer_unwind_linux_libcdep.cpp.o:(__sanitizer::BufferedStackTrace::UnwindSlow(unsigned long, unsigned int)) in archive /usr/lib/llvm-11/lib/clang/11.0.1/lib/linux/libclang_rt.asan-x86_64.a
>>> referenced by sanitizer_unwind_linux_libcdep.cpp.o:(__sanitizer::BufferedStackTrace::UnwindSlow(unsigned long, void*, unsigned int)) in archive /usr/lib/llvm-11/lib/clang/11.0.1/lib/linux/libclang_rt.asan-x86_64.a

ld.lld: error: undefined symbol: _Unwind_GetIP
>>> referenced by sanitizer_unwind_linux_libcdep.cpp.o:(__sanitizer::(anonymous namespace)::Unwind_Trace(_Unwind_Context*, void*)) in archive /usr/lib/llvm-11/lib/clang/11.0.1/lib/linux/libclang_rt.asan-x86_64.a
clang: error: linker command failed with exit code 1
```

Maybe I miss something? I am using Ubuntu 20.04 & clang 11. It would be great if anyone provides me some help.

**Comment by caitong93** [comment]
Plz try `./ci/run_envoy_docker.sh 'bazel test --config=clang-asan ..'` .  It's suggested to use docker build to keep ur local development environment same as others https://github.com/envoyproxy/envoy/tree/master/ci#on-linux .

**Comment by spacewander** [comment]
It seems the docker used by `./ci/run_envoy_docker.sh` doesn't contain `clang`.
```sh
./ci/run_envoy_docker.sh 'echo $(which clang)'

./ci/run_envoy_docker.sh 'echo $(which gcc)'
/usr/bin/gcc
```

**Comment by caitong93** [comment]
See https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L84

**Comment by nareddyt** [comment]
So it seems like some of the bazel flags from https://github.com/envoyproxy/envoy/blob/e90d674fd2eddd883481011bf580fbb7080f535b/bazel/setup_clang.sh#L26 are needed. These are not set for `clang-asan` in the root-level bazelrc by default, only added for CI. Wonder why.

**Comment by nareddyt** [comment]
The issue seems related to https://github.com/envoyproxy/envoy/issues/13973. Unfortunately I had no luck setting those extra bazel flags, so I had to disable Ubsan for now. https://github.com/GoogleCloudPlatform/esp-v2/pull/445 and https://github.com/envoyproxy/nighthawk/issues/593 track this.
