### ISSUE TITLE
No healthy host for HTTP connection pool error while using envoy external authorization using http service.

### ISSUE THREAD

**Issue by mukund-thakur** [envoyproxy/envoy#14482]
No healthy host for HTTP connection pool error while using envoy external authorization using http service.

*Description*:
I have been trying to use Envoy proxy from intercepting google cloud storage calls using hadoop gcs connector https://github.com/GoogleCloudDataproc/hadoop-connectors . This flow is working fine for me now. Now I want to add http service based authorization on the Envoy side before forwarding the requests to google storage server by following this doc https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter but getting this error. 

Here is the proxy logs :

> [2020-12-18 18:11:11.156][3998945][debug][http] [source/common/http/filter_manager.cc:721] [C0][S9503803361663740970] request end stream
[2020-12-18 18:11:11.279][3998945][trace][filter] [source/extensions/filters/http/ext_authz/ext_authz.cc:69] [C0][S9503803361663740970] ext_authz filter calling authorization server
[2020-12-18 18:11:11.304][3998945][debug][router] [source/common/router/router.cc:429] [C0][S15803442533933423924] cluster 'ext-authz' match for URL '/storage/v1/b/gcs-mthakur-bucket'
[2020-12-18 18:11:11.361][3998945][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1357] no healthy host for HTTP connection pool
[2020-12-18 18:11:11.370][3998945][debug][http] [source/common/http/async_client_impl.cc:100] async http request response headers (end_stream=false):
':status', '503'
'content-length', '19'
'content-type', 'text/plain'

Here is my envoy yaml:

>   http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              http_service:
                  server_uri:
                    uri: 127.0.0.1:8080
                    cluster: ext-authz
                    timeout: 30s

... corresponding cluster conf as well.

I have a server running at localhost on port 8080 written in java. 

Do I need to implement anything in my auth server? I am unable to find any relevant docs. Please help. Thanks

**Comment by dio** [comment]
Hey @mukund-thakur!

There is a working example in the repo: https://github.com/envoyproxy/envoy/tree/master/examples/ext_authz as the source for this sandbox: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/ext_authz

This is a sample for having ext_authz with HTTP service: https://github.com/envoyproxy/envoy/blob/master/examples/ext_authz/config/http-service.yaml

The GCS service should act as the upstream service here: https://github.com/envoyproxy/envoy/blob/2a9bb4d075f39e83a1b2c999ce6cfa8e21515c4d/examples/ext_authz/config/http-service.yaml#L54, and your Java application should be here: https://github.com/envoyproxy/envoy/blob/2a9bb4d075f39e83a1b2c999ce6cfa8e21515c4d/examples/ext_authz/config/http-service.yaml#L68. The example of ext_authz service is written in JavaScript https://github.com/envoyproxy/envoy/blob/master/examples/ext_authz/auth/http-service/server.js but I think you'll get the idea. 

Hope it helps!

**Comment by mukund-thakur** [comment]
Thanks @dio for the docs. I tried this and it works. But I am not using docker and running the services separately and my auth server is running at http://127.0.0.1:8080/ 

> 
> , and your Java application should be here:
> https://github.com/envoyproxy/envoy/blob/2a9bb4d075f39e83a1b2c999ce6cfa8e21515c4d/examples/ext_authz/config/http-service.yaml#L68
> 
So I updated the address here to 127.0.0.1 and port as well. 

But getting error

> No healthy host for HTTP connection pool 

Also I am seeing some suspicious logs 

> DNS for 127.0.0.1 resolved with: flags=3[MoreComing=yes, Add=yes], interface_index=0, error_code=-65568, hostname=127.0.0.1.

I am expecting envoy to at least send the calls to http://127.0.0.1:8080/.

**Comment by mukund-thakur** [comment]
I ran this node server https://github.com/envoyproxy/envoy/blob/master/examples/ext_authz/auth/http-service/server.js  in my localhost as well which I am able to access using curl but not working with envoy. I think I am missing some configuration here when not run the complete setup using docker. 

Here is the my yaml config. Please suggest if any changes required. Thanks   
> http_filters:
> name: envoy.filters.http.ext_authz
>             typed_config:
>               "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
>               transport_api_version: V3
>               http_service:
>                 server_uri:
>                   uri: http://127.0.0.1:9002/
>                   cluster: ext_authz-http-service
>                   timeout:  15s
>                 authorization_response:
>                   allowed_upstream_headers:
>                     patterns:
>                     - exact: x-current-user
>     name: ext_authz-http-service
>     connect_timeout: 15s
>     type: STRICT_DNS
>     lb_policy: ROUND_ROBIN
>     load_assignment:
>       cluster_name: ext_authz-http-service
>       endpoints:
>       - lb_endpoints:
>         - endpoint:
>             address:
>               socket_address:
>                 address: 127.0.0.1
>                 port_value: 9002

**Comment by dio** [comment]
@mukund-thakur when specifying the endpoints using IP addresses you should use `STATIC` cluster type instead of `STRICT_DNS`.

**Comment by mukund-thakur** [comment]
Thanks a lot @dio . It worked.
