### ISSUE TITLE
Configuration option for gRPC response code for request timeout

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#14484]
*Title*: *Configuration option for gRPC response code for request timeout*

*Description*:
Today, if a gRPC request times out, the router filter returns a 504 direct reply, which then gets translated to an UNAVAILABLE gRPC code according to the official mapping: https://grpc.github.io/grpc/core/md_doc_http-grpc-status-mapping.html

Our users would like to be able to distinguish request timeouts from 503-equivalent errors, so I'd be interested in adding a configuration option to choose the gRPC code to stand in for timeouts (e.g. to use DEADLINE_EXCEEDED instead).

**Comment by mattklein123** [comment]
Can this already be done with the local reply mapper? If not can we make the mapper capable of doing it?
