### ISSUE TITLE
Support configurable date formats for DOWNSTREAM_PEER_CERT_V_START/END

### ISSUE THREAD

**Issue by esmet** [envoyproxy/envoy#14501]
We currently support configurable date formats using an access log command operator for START_TIME but it would be helpful to expend this behavior to DOWNSTREAM_PEER_CERT_V_START and DOWNSTREAM_PEER_CERT_V_END as well.

**Comment by rgs1** [comment]
FWIW we are adding support for formatter extensions here:

https://github.com/envoyproxy/envoy/pull/14512

So maybe this can be implemented as an extension.
