### ISSUE TITLE
build: envoy picks up system libidn2-dev package and fails to link

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#14506]
`libidn2-dev` debian package is detected by curl build but should be overridden for reproducible builds.

**Comment by wrowe** [comment]
This is fubar upstream. They've failed to add a undesired feature guard in their CMakeLists.txt here

```
# Check for idn
check_library_exists_concat("idn2" idn2_lookup_ul HAVE_LIBIDN2)
```

I think we must reject/revert 7.74, until upstream adds the appropriate CURL_DISABLE_IDN2 toggle. @htuch your thoughts?

**Comment by wrowe** [comment]
The alternative is to patch for the use of 7.74, but I'm hoping we could see an upstream 7.74.1 before our 1.17.0 package.

**Comment by wrowe** [comment]
The proposed patch https://github.com/curl/curl/pull/6362 would have us introduce USE_LIBIDN2: "off" to the cache_entries of envoy_cmake_external in https://github.com/envoyproxy/envoy/blob/b4ca626476403d816926ba10ff453065bd7ed642/bazel/foreign_cc/BUILD#L105

Just waiting to see that this is the correct field name and patch is accepted before injecting it into our baze/foreign_cc/curl.patch, but this workaround seems fine.

**Comment by htuch** [comment]
Ideally let's get this option added upstream, so we only need to modify the `BUILD`.

**Comment by wrowe** [comment]
> Ideally let's get this option added upstream, so we only need to modify the `BUILD`.

Agreed @htuch - I've run the draft proposed curl#6362 through our schema in our PR https://github.com/envoyproxy/envoy/pull/14601 for the 1.17.0 milestone, and this looks
correct to me, but it's blocked on a dep-maintainter's review. Would you mind taking that
review please? If we pass it, I'll relay our success to the curl PR.
