### ISSUE TITLE
Is there a limit on how many clusters we can create?

### ISSUE THREAD

**Issue by songhu** [envoyproxy/envoy#14510]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Is there a limit on number of clusters?*

*Description*:
>It seems that my envoyproxy setup stopped accepting new clusters from my CDS/EDS after 1500 clusters. I was wondering is there any limit on the max number of clusters? 
>I also observed that I have a high number of threads on the CDS/EDS (seems matching the number of clusters), maybe that's the reason behind? It's likely that I might missed a thread limit on my Grpc setup, but just want to double check is there any limit on envoyproxy as well.
>Thanks!

>EnvoyProxy version: 1.15.2
>xDS: CDS and EDS on one Grpc server (C++)
>Maximum number of clusters added: around 1500
>Maximum number of threads on xDS process: 1098

**Comment by jmarantz** [comment]
What does the "Maximum number of threads on xDS process: 1098" mean? Did you set the Envoy concurrency limit to a very high number; higher than the number of cores?

**Comment by antoniovicente** [comment]
@htuch mentioned #10793 as a related issue.

To handle larger numbers of clusters, you should switch over to ADS as the communication mechanism between your envoys and control plane. This should result in a constant number of gRPC clients and threads as the number of CDS/EDS targets increase.

Docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/xds_api#aggregated-discovery-service

**Comment by songhu** [comment]
@jmarantz Thanks for your reply. When envoy was not accepting new clusters, I went and checked the number of threads in the process where xDS was running, I counted 1098 threads at the time. In my setup each cluster was getting its endpoints from EDS. It seems each cluster will need a thread in the EDS.
@antoniovicente I think you are right, I should try ADS.  Thanks!
