### ISSUE TITLE
List of SSL cipher stat names is incomplete

### ISSUE THREAD

**Issue by akonradi** [envoyproxy/envoy#14524]
The list of cipher names and curves supported by BoringSSL is larger than the set that Envoy exports stats for ("cluster.[cluster_name].ssl.ciphers.[cipher]" and ("cluster.[cluster_name].ssl.curves.[cipher]"). The list in Envoy is currently [hard-coded](https://github.com/envoyproxy/envoy/blob/483dd3007f15e47deed0a29d945ff776abb37815/source/extensions/transport_sockets/tls/context_impl.cc#L475) and [separate](https://github.com/envoyproxy/envoy/blob/483dd3007f15e47deed0a29d945ff776abb37815/source/extensions/transport_sockets/tls/context_config_impl.cc#L373) from the list of actual supported stats.

/cc @jmarantz @PiotrSikora

**Comment by jmarantz** [comment]
It's easy enough to use the configured ciphers; should've done that in the first place. Moreover we should probably log (rate-limited) when we see one we didn't expect, otherwise you can't learn from production what it was.
