### ISSUE TITLE
Trying to downgrade to a specific version

### ISSUE THREAD

**Issue by long1eu** [envoyproxy/envoy#14520]
I'm on macOS And I'm trying to install a specific version, but I don't manage to do it. I tried `brew install envoy --HEAD` just to test it but I get `Error: No head is defined for envoy`. 

Any idea on how to install an old version?

**Comment by hakuno** [comment]
I do use Docker. It has official images hosted [at here](https://hub.docker.com/r/envoyproxy/envoy-alpine).

**Comment by long1eu** [comment]
This is still an issue.
