### ISSUE TITLE
Support for max_requests_connection in downstream connections

### ISSUE THREAD

**Issue by CAFxX** [envoyproxy/envoy#14531]
As discussed in https://github.com/envoyproxy/envoy/issues/13388#issuecomment-704444298 it would be ideal to have a way to configure envoy to serve up to a certain number of requests on each downstream HTTP connection before signaling to the client (via `Connection: close`) that the connection should be closed.

nginx support this with [`keepalive_requests`](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests):

> Sets the maximum number of requests that can be served through one keep-alive connection. After the maximum number of requests are made, the connection is closed.

The main use case for us is forcing load balancers to periodically reopen requests to speed up the convergence to a uniform load distribution on the backends.

**Comment by mk46** [comment]
I would like to take up this issue. If I am correct, need to add max_requests_connection in the *protocol.proto file for the config.

**Comment by ggreenway** [comment]
There's already an option for this on the upstream side on the cluster config. So you can either add the downstream option on the HCM config, or we could consider deprecating the existing cluster option and adding the new one to `core.v3.HttpProtocolOptions`.

**Comment by mk46** [comment]
@ggreenway Thanks for the suggestion to move on. Could you please guide me to implement further? See the linked PR.

**Comment by CAFxX** [comment]
Can we reopen? This is still relevant.
