### ISSUE TITLE
L4 traffic routing and custom-defined filter

### ISSUE THREAD

**Issue by small-pineapple** [envoyproxy/envoy#14530]
Current L4 filters in [source\extensions\filters\network](https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/network) do encode decode work in Envoy::Networks::ReadFilter::onData and Envoy::Networks::WriteFilter::onWrite respectively. However, the knowledge of how L4 data packet formed haven't tell envoy, those 2 virtual function return can not indicate the packet boundary in buffer, so envoy have no idea about the boundary of packet in tcp stream data. 

When using envoy as network proxy, for example, istio sidecar, a traffic routing like redirect 20% taffic to another subnet defined in DestinationRule applied, how envoy/istio cope with this to avoid the incorrect data split? There is a [example](https://github.com/istio/istio/tree/master/samples/tcp-echo) of routing tcp traffic, but I am not sure it involve envoy or not.

 Or envoy just incapable of this?

**Comment by lambdai** [comment]
Not sure if it's the question you ask:
For plain tcp stream that is terminated by tcp_proxy, a single downstream tcp will always relayed to a single tcp upstream. LB occurs on upstream host selection so no need to "packet boundary".

Http traffic is handled by HttpConnManager as an L4 network filter. The http request parser within determines the boundary of http request(or parse concurrent streams if it's h2).

BTW: it's istio `virtual service` that defines the weight and LB, not destination rule :) Destination is applied strictly after a host is selected and there is no chance to execute load balance.
