### ISSUE TITLE
How can I redirect to another domain(Host) if all servers are down?

### ISSUE THREAD

**Issue by sefaphlvn** [envoyproxy/envoy#14532]
*Title*: *Redirect to another host when all servers down*

*Description*:
> I want to forward traffic to another domain when the backend servers doesn't respond. I'm not sure if it is possible to do this with routes. if it's perfect

Like this https://support.citrix.com/article/CTX108946

**Comment by mattklein123** [comment]
It might be possible to do this with a local reply mapper (turn a no host error into a redirect) but AFAIK I don't think we have this built-in. @alyssawilk @snowp?

**Comment by alyssawilk** [comment]
yeah, I don't think there's anything in the core code which would allow this.
I think you could write a filter which would on the observed 5xx response would do an internal redirect (on 5xx, change host and recreateStream) 
Arguably we could also add this as a feature to the local reply mapper as well but I don't think it's there today.
