### ISSUE TITLE
Config rejection when outlier detection max_ejection_time is not set

### ISSUE THREAD

**Issue by hennna** [envoyproxy/envoy#14535]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*: Config rejection "outlier detector's max_ejection_time cannot be smaller than base_ejection_time" when outlier detection max_ejection_time is not set https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/outlier_detection_impl.cc#L283

>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
Envoy should not validate max_ejection_time if not set in config as max_ejection_time is a newly introduced configuration parameter.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
Config with base_ejection_time set but not max_ejection_time set fails validation.

outlier_detection {
      ...
      base_ejection_time {
        seconds: 30
      }
      ...
}

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by mattklein123** [comment]
I think this is a recent regression. @cpakulski do you mind fixing? It should be quick. Thank you.

**Comment by cpakulski** [comment]
No problem.

**Comment by cpakulski** [comment]
Fixed in #14540.
