### ISSUE TITLE
/listeners admin endpoint

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1453]
Currently we have a /listeners endpoint, but it's just a quick hack to let us run integration tests with zero bound ports. We need to add a full /listeners endpoint that dumps full config of all listeners like we are doing with /routes. Either we can somehow move the test lookups to use this new endpoint, or we can move /listeners that exists today to something like /listeners_for_testing or whatever.

**Comment by mattklein123** [comment]
@rodaine can you look at this one also?

**Comment by rodaine** [comment]
Will do!

**Comment by mattklein123** [comment]
@rodaine @junr03 this is another good one for James to potentially work on as a starter task.

**Comment by mattklein123** [comment]
@jsedgwick I'm going to go ahead and close this one. I think with our new `/dump_config` design this is no longer needed.
