### ISSUE TITLE
//test/server:server_fuzz_test build failure

### ISSUE THREAD

**Issue by stefanbucur** [envoyproxy/envoy#14543]
*Title*: *The //test/server:server_fuzz_test fuzz target fails to build*

*Description*:
The following command fails on the latest HEAD (7e3b483bbb004bf2b8234e3ec2be6ceef254a2f9):

```sh
 $ bazel build --config=remote --config=clang --config=asan-fuzzer -c opt //test/server:server_fuzz_test
```

The error message:
```
ERROR: /usr/local/google/home/sbucur/.cache/bazel/_bazel_sbucur/4e2ed66b5d3aec1195331fcaa64efd63/external/io_opentracing_cpp/BUILD.bazel:19:8: Executing genrule @io_opentracing_cpp//:generate_version_h failed (Exit 1)
CMake Error at /usr/share/cmake-3.18/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  clang.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.a2iiJcISX0/CMakeFiles/CMakeOutput.log".
-- Cache values
Target //test/server:server_fuzz_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.432s, Critical Path: 6.55s
INFO: 1108 processes: 468 remote cache hit, 209 internal, 431 remote.
FAILED: Build did NOT complete successfully
```

The problem seems to happen when building the `@com_lightstep_tracer_cpp//:generate_version_h` dependency. Here is the dependency chain:
```
$ bazel query 'somepath(//test/server:server_fuzz_test, @com_lightstep_tracer_cpp//:generate_version_h)'        
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = c95607c101213b9a4586ef91ac2cf15d12d5aa659882dcc1e00f00c441172beb
//test/server:server_fuzz_test
//test/server:server_fuzz_test_lib
//source/extensions/tracers/lightstep:config_envoy_extension
//source/extensions/tracers/lightstep:config
//source/extensions/tracers/lightstep:lightstep_tracer_lib
//external:lightstep
@com_lightstep_tracer_cpp//:manual_tracer_lib
@com_lightstep_tracer_cpp//src/recorder:no_grpc_transporter_lib
@com_lightstep_tracer_cpp//:config_lib
@com_lightstep_tracer_cpp//:gen-config/lightstep/version.h
@com_lightstep_tracer_cpp//:generate_version_h
```

**Comment by stefanbucur** [comment]
By the way, building this locally on my machine gives a different error, at linking time:

```
$ bazel build --config=clang --config=asan-fuzzer -c opt //test/server:server_fuzz_test
[...]
ERROR: [...]/envoy/test/server/BUILD:316:19: Linking of rule '//test/server:server_fuzz_test' failed (Exit 1) clang failed: error executing command [...]/clang-11/bin/clang @bazel-out/k8-opt/bin/test/server/server_fuzz_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld.lld: error: undefined symbol: __muloti4
>>> referenced by int128_have_intrinsic.inc:251 (external/com_google_absl/absl/numeric/int128_have_intrinsic.inc:251)
>>>               bazel-out/k8-opt/bin/external/com_google_cel_cpp/eval/public/_objs/builtin_func_registrar/builtin_func_registrar.o:(absl::operator*(absl::int128, absl::int128))
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
Target //test/server:server_fuzz_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3135.163s, Critical Path: 1058.58s
INFO: 7782 processes: 3203 internal, 4578 linux-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
```

Is this a Clang versioning issue? (I'm using Clang 11 locally)

**Comment by rojkov** [comment]
> ld.lld: error: undefined symbol: __muloti4

`__muloti4` is defined in libc++ and missing in libstdc++. Probably the lib gets overridden somewhere in .bazelrc

**Comment by stefanbucur** [comment]
@asraa do you have a sense what could be the issue here? (both for the remote and local build) Am I building this target with the wrong flags?

**Comment by asraa** [comment]
Could you try running `bazel/setup_clang /path/to/clang` (then bazel clean --expunge, and re-try?) This will set up the CC env variable to the right path.

**Comment by stefanbucur** [comment]
Same problem :( I ran the following:

```
$ bazel/setup_clang.sh $HOME/clang-11
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
$ bazel build --config=remote --config=clang --config=asan-fuzzer -c opt //test/server:server_fuzz_test
[...]
ERROR: /usr/local/google/home/sbucur/.cache/bazel/_bazel_sbucur/4e2ed66b5d3aec1195331fcaa64efd63/external/io_opentracing_cpp/BUILD.bazel:19:8: Executing genrule @io_opentracing_cpp//:generate_version_h failed (Exit 1)
-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.R8K1CaF2xB/CMakeFiles/CMakeOutput.log".
-- Cache values
CMake Error at /usr/share/cmake-3.18/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  clang.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Target //test/server:server_fuzz_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 40.179s, Critical Path: 2.12s
INFO: 2327 processes: 230 remote cache hit, 2097 internal.
FAILED: Build did NOT complete successfully
```

**Comment by asraa** [comment]
Hm. Just for reference CI and RBE are configured with a clang-10 toolchain, so I wonder if that might be causing the problem.

However, there's still the local error. 
Locally, can you run with `--config libc++`?
Remote build, can you try with a clang-10 installation?

**Comment by stefanbucur** [comment]
> Hm. Just for reference CI and RBE are configured with a clang-10 toolchain, so I wonder if that might be causing the problem.

I switched locally to Clang-10, and the error still persists remotely.

Can you confirm that the remote command works for you? I'm imagining that, in theory, remote builds should behave the same regardless of where the build command originates from.

> 
> However, there's still the local error.
> Locally, can you run with `--config libc++`?

I've just re-issued the command, and it's rebuilding everything. This build seems to be taking a lot of time. Is this expected or there are tricks I can use to speed it up, aside from remote building?

**Comment by asraa** [comment]
With remote build, this succeeds for me at HEAD:
```
bazel clean --expunge
bazel/setup_clang.sh /opt/llvm
bazel build --config=remote --config=clang --config=asan-fuzzer -c opt //test/common/common:base64_fuzz_test
```

`server_fuzz_test` worked up to linking, which took more than 20 min, but I can keep it running in the background.

`server_fuzz_test` is the largest fuzz target since it compiles most of Envoy, if it were just for testing the config `base64_fuzz_test` is probably the smallest and will take the least amount of time. The v8 build in server_fuzz_test takes an extremely long time.

I haven't seen this error but some of the environment configurations I have (which I imagine shouldn't make a difference since they're passed as action_env in clang.bazelrc but I could be wrong) are
CC=/path/to/clang, CXX=/path/to/clang++

**Comment by stefanbucur** [comment]
> With remote build, this succeeds for me at HEAD:
> 
> ```
> bazel clean --expunge
> bazel/setup_clang.sh /opt/llvm
> bazel build --config=remote --config=clang --config=asan-fuzzer -c opt //test/common/common:base64_fuzz_test
> ```

Now it works for me too! And I have no idea why :) I don't recall making any changes to my environment nor the compiler. I'm wondering if this could be an RBE cache hit from a previous build, but I'll take it as it is :)

I can also confirm that the build works locally when using `--config libc++`. Is this the recommended way to build all fuzz targets in Envoy?

**Comment by asraa** [comment]
> Is this the recommended way to build all fuzz targets in Envoy?

Yep, the official build is with libc++. I just have that option in my home bazelrc. CI and OSS-Fuzz builds with libc++.
