### ISSUE TITLE
jwt_authn: JWKs health

### ISSUE THREAD

**Issue by skjolber** [envoyproxy/envoy#14556]
*Title*: *jwt_authn: JWKs health*

*Description*:
> Make it so that the state of the JWKs cache is reflected in the application (readiness) health.
>
> Basically tie in readiness check to the JWKs cache, which should refresh if JWKs are missing or expired. This should result in
> 
> * JWKs are prefetched on startup, before traffic is accepted.
> * suspended traffic if the cache expires and cannot be refreshed

**Comment by qiwzhang** [comment]
This seems a reasonable and legal requirement for a stable production proxy using jwt_authn.

My proposal is:
1) add a new remote jwks fetching approach: fetching it at envoy config thread (main thread). Currently it is fetching in the worker thread when handling the first traffic. One benefit is: such JWKS cache can be shared by all worker threads. 
2) if the init fetching fails, not to mark the listener ready so it will not bind the listener port, envoy is not healthy.
3) jwks re-fetch can be done at config thread too, so it is a background thread for worker threads, jwks re-fetching will not block normal traffic.
4) if re-fetching fails, there is not easy to disable the listener,  not easy to expose such unhealthy state. One way is to expose a `/jwt_authn_health_path` handled by the `jwt_authn` fitler. LB or other health filter can call it.

**Comment by qiwzhang** [comment]
It seems the action items are:
1) add `bool background_fetch` in [remote_jwks](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-remotejwks) config proto to enable jwks fetching in the config thread.
2) add new jwks_fetch stats; such as `jwks_fetch_ok_count`, and `jwks_fetch_failure_count`.

**Comment by nareddyt** [comment]
I will take a look next week. You can assign this issue to me.

**Comment by qiwzhang** [comment]
Please assign this issue to me.  Thanks.
