### ISSUE TITLE
DirectResponseEntry::newPath doesn't perform prefix rewrites

### ISSUE THREAD

**Issue by Noah-Wagner** [envoyproxy/envoy#14565]
*Title*: newPath doesn't perform prefix rewrites

*Description*:
The method [DirectResponseEntry::newPath](https://github.com/envoyproxy/envoy/blob/540507edf8bf9f59e6a982b3f4ee62e85c217969/source/common/router/config_impl.cc#L715) performs redirects for schemes, ports, hosts, and paths, but does not perform redirects for prefix_rewrites. This was a little unexpected to me and seems to be a bit of an uneven API. Especially considering in the one place this method is used we rewrite the path header based on our prefix_rewrite: [LINK](https://github.com/envoyproxy/envoy/blob/540507edf8bf9f59e6a982b3f4ee62e85c217969/source/common/router/router.cc#L371). Is there a history for this or is it acceptable for me to send a refactor PR that inlines prefix rewriting into newPath()?

**Comment by mattklein123** [comment]
cc @alyssawilk
