### ISSUE TITLE
Support for max_requests_connection in downstream connections of thrift proxy

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#14560]
Support for max_requests_connection in downstream connections of thrift proxy which make the envoy can actively disconnect from the thrift client at the right time.

Consider such a scenario. Assume that the thrift server has opened port 10000 and the IP is 1.2.3.4.  But the  envoy sidecar of the thrift client initially only had a virtual listener of 0.0.0.0:10000. Then the connection and request of the thrift client will be processed by 0.0.0.0:10000. But after a while, we created a new listener of 1.2.3.4:10000 for the sidecar, and at this time we expect that the new request will be processed by 1.2.3.4:10000. However, because the connection between the thrift client and the sidecar is a keep-alive connection, unless the client actively disconnects, subsequent requests will still be processed by 0.0.0.0:10000.

**Comment by rgs1** [comment]
It would still not be a clean drain, because there's no way in thrift to drain a connection cleanly afaik. But maybe that's OK for most use-cases?

Happy to review a PR if you want to give this a go @wbpcode. 

cc: @fishcakez

**Comment by wbpcode** [comment]
> It would still not be a clean drain, because there's no way in thrift to drain a connection cleanly afaik. But maybe that's OK for most use-cases?
> 
> Happy to review a PR if you want to give this a go @wbpcode.
> 
> cc: @fishcakez

I will have a try.
