### ISSUE TITLE
Cannot register "/" path for JSON transcoding

### ISSUE THREAD

**Issue by vsekhar** [envoyproxy/envoy#14561]
*Title*: *Cannot register '/' path for JSON transcoding*

*Description*:
Envoy crashes when starting up with a JSON transcoding path at the root ("/").

*Repro steps*:
```proto
syntax = "proto3";
package svctest;

import "google/api/annotations.proto";

message HelloRequest {}
message HelloResponse {
    string message = 1;
}

service Hello {
    rpc Hello(HelloRequest) returns (HelloResponse) {
        option (google.api.http) = {
            // get: "/root"   // this works
            get: "/"          // this fails
        };
    }
}
```

*Config*:
```service
[Unit]
Description=Envoy
After=docker-credential-gcr.service config-firewall.service svc-test-external-hello-v2.service
Wants=docker-credential-gcr.service config-firewall.service svc-test-external-hello-v2.service

[Service]
Restart=always
Environment="HOME=/home/envoy"
# ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries=gcr.io
ExecStart=/usr/bin/docker run --name=envoy \
                              --log-opt tag=\"envoy\" \
                              --rm \
                              --user 2000 \
                              --net container:svc-test-external-hello-v2 \
                              gcr.io/endpoints-release/endpoints-runtime:2 \
                              --service svctest.endpoints.project-id.cloud.goog \
                              --listener_port 8081 \
                              --backend grpc://127.0.0.1:8080 \
                              --rollout_strategy managed
ExecStop=/usr/bin/docker stop envoy
ExecStopPost=/usr/bin/docker rm envoy
```

*Logs*:
Many repetitions of:

```
Jan 05 06:38:07 svc-test-external-inst-041z docker[1761]: W0105 06:38:07.000 20 envoy] [20][config]gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ingress_listener: transcoding_filter: Cannot register \'svctest.Hello.Hello\' to path matcher
```

More log here: https://gist.github.com/vsekhar/1f207da2539306092f5341b93ed8dc9e#file-journalctl-u-envoy-service

**Comment by qiwzhang** [comment]
grpc_transcoder filter uses path_matcher [code](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/master/src/include/grpc_transcoding/path_matcher.h).  It doesn't support root "/" path. 

Normally, you would not use root path to call a gRPC method. 

But its support can be easily added. 

@TAOXUY could you help to add such support and add a grpc_transcoder integration test for this case

**Comment by Jawadh-Salih** [comment]
I am getting a path matcher error for path variable in a HTTP URL. Can anyone help me?
```go
option (google.api.http) = {
			get: "/v1/companies/{param1}/{param2}"
		};
```

gives me following error 

`transcoding_filter: Cannot register 'pb.Service.ListValues' to path matcher`

**Comment by TAOXUY** [comment]
Hi @Jawadh-Salih, though the error log looks same, it could be different issue so please put your issue in a new thread.

**Comment by TAOXUY** [comment]
This one has been addressed in https://github.com/envoyproxy/envoy/pull/14585 and should be closed.
