### ISSUE TITLE
BazelCI is failing for Bazel@HEAD: no field 'libraries_to_link'

### ISSUE THREAD

**Issue by c-parsons** [envoyproxy/envoy#14579]
**Title**: BazelCI is failing for Bazel@HEAD

**Description**:
Example buildkite failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1839#ec110a35-1129-4d6c-a8bb-0cf2a089fad5

```
(02:07:05) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/329b2ef63c6f648a22d719484bf56ee1/external/upb/BUILD:127:18: in upb_proto_library rule @upb//:descriptor_upb_proto:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/329b2ef63c6f648a22d719484bf56ee1/external/upb/bazel/upb_proto_library.bzl", line 168, column 36, in _upb_proto_rule_impl
  | if type(cc_info.linking_context.libraries_to_link) == "list":
  | Error: 'LinkingContext' value has no field or method 'libraries_to_link'
```

**Culprit**:
https://github.com/bazelbuild/bazel/commit/9a2893dc84cf8e05c1472c5ecff094e8da1d2049

**Suggested fix**:

Quick fix: Flip `--incompatible_require_linker_input_cc_api` to false in your bazelCI definition

Long term fix: please see the documentation for `incompatible_require_linker_input_cc_api` and update your Starlark code

**Comment by snowp** [comment]
@lizan you want to take a look?

**Comment by asraa** [comment]
Not sure if it will help, but upb can also be bumped to a newer version.
