### ISSUE TITLE
TSAN failure in fuzz_coverage - DNS Cache

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#14581]
This TSAN failure happens occasionally in fuzz_coverage builds while fuzzing the SNI Cluster network filter.

The whole stack trace is here https://gist.github.com/asraa/75fe00e05270dd72bc9bd319bf2bfced 

Sometimes I get a shorter stack trace like:
https://gist.github.com/asraa/9bbafb728a48a654fd3ee4ed7edbb979

I mostly see that this is coming from running dispatcher in this `advanceTimeAndRun` which loads cache entries. I see logs about this mutex being already destroyed https://github.com/envoyproxy/envoy/blob/1bf77f3cccc12fd4ebe12207c272c6755f2498bb/source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc#L141

I reproduced this by replicating the fuzzing step the fuzz_coverage job does
```
bazel build --config remote --config plain-fuzzer --config clang-tsan --define=dynamic_link_tests=true --config libc++ --copt=-DNDEBUG test/extensions/filters/network/common/fuzz:network_readfilter_fuzz_test
mkdir /tmp/corpus
cp -r test/extensions/filters/network/common/fuzz/network_readfilter_corpus /tmp/corpus
bazel-bin/test/extensions/filters/network/common/fuzz/network_readfilter_fuzz_test /tmp/corpus -seed=1 -max_total_time=60 -max_len=2048 -rss_limit_mb=8192 -timeout=30
```

My gut feeling is that this should be changed:
https://github.com/envoyproxy/envoy/blob/1bf77f3cccc12fd4ebe12207c272c6755f2498bb/test/extensions/filters/network/common/fuzz/uber_readfilter.cc#L129-L131

**Comment by mattklein123** [comment]
cc @chradcliffe it would be good to investigate this to make sure this is a test issue and not a real issue.
