### ISSUE TITLE
filters: use filter config name in typed_per_filter_config

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#14599]
In case of the extension config is repeated twice in a filter chain, the current solution of using extension name as a lookup key for filter config overrides does not work. The proposal is to use the filter config name instead.

**Comment by snowp** [comment]
Might be a dupe of https://github.com/envoyproxy/envoy/issues/12274 ? 

In general this makes sense to me, just wondering if there is any problem with making this change in terms of compatibility. Maybe we'd try the filter config name first then fall back to the extension name?

**Comment by kyessenov** [comment]
Indeed, this is a dupe.
