### ISSUE TITLE
Issues with route timeout configuration

### ISSUE THREAD

**Issue by rgleme** [envoyproxy/envoy#14606]
Hello

I am trying to set my route timeout to use 60s value:

              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: load_balancer_3
                  timeout: 60s
                  idle_timeout: 60s

Envoy version: v1.16.2

Although, when I am receiving its response... I am getting 15s default value

* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 504 
< date: Fri, 08 Jan 2021 20:15:11 GMT
< content-type: text/plain
< content-length: 24
< server: envoy
< 
* Connection #0 to host  left intact
upstream request timeout
real	0m15,655s
user	0m0,025s
sys	0m0,010s

I need to envoy wait 60s for the request

Could you help me ?
Thank you

**Comment by htuch** [comment]
There are multiple timeouts that interact with the request lifecycle, see https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts.html. You're probably encountering the default `timeout` which is 15s.

**Comment by rgleme** [comment]
Hello Htuch

Yes, probably I am encountering default timeout. But inside my route configuration, I am using the "timeout" parameter

          routes:
          - match:
              prefix: "/"
            route:
              cluster: load_balancer_3
              timeout: 60s
              idle_timeout: 60s

**Comment by htuch** [comment]
It's kind of hard to tell without more config or request context. Are you sure your route matches, there are no HCM-level timeouts etc.?
