### ISSUE TITLE
docs: Add documentation to API fields for which Windows values/usage may differ, be disabled, etc.

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#14607]
*Description*:
Fields in Envoy's API that may have platforms specific values or usage or are related to features disabled on Windows should be documented as such.

*Relevant Links*:
- e.g. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto.html#config-core-v3-socketoption the `buf_value` field may have different padding/byte order requirements etc. between platforms (see specifically the differences in the `linger` struct between Windows and Linux when using the `SO_LINGER` option)
- See https://github.com/envoyproxy/envoy/issues/13322 for some examples to start with
- child issue of https://github.com/envoyproxy/envoy/issues/13190

**Comment by sunjayBhatia** [comment]
cc @envoyproxy/windows-dev

**Comment by wrowe** [comment]
This should now be satisfied.
