### ISSUE TITLE
FR - Ability to log headers from authorization response *without* forwarding to upstream service

### ISSUE THREAD

**Issue by kev1n11** [envoyproxy/envoy#14622]
### Description
Using Envoy as a front proxy and its access logs is the most important logs. Would be nice if there's a way to log response headers from the External Authorization Server *without* forward that to the upstream service.

Currently, the work around is
- add `allowed_upstream_headers`, say `foo-header` as per https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=allowed_upstream_headers#extensions-filters-http-ext-authz-v3-authorizationresponse
- add `%REQ(FOO-HEADER)%` as per https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by htuch** [comment]
@dio thoughts on how best to do this?

**Comment by esmet** [comment]
I think the most straightforward way to do this is to use a gRPC authorization service and return `dynamic_metadata` in the CheckResponse and log that in your access logs using `DYNAMIC_METADATA(...)`.

Is using a gRPC service an OK option for your use case?

**Comment by esmet** [comment]
@htuch / @dio I'm happy to take this if the ask evolves into adding dynamic metadata to HTTP-only responses (or something similar).

**Comment by htuch** [comment]
Cool. @kev1n11 does this address your use case?

**Comment by esmet** [comment]
Let's un-stale this since I have an open PR for the HTTP implementation side

**Comment by esmet** [comment]
@kev1n11 would be good to hear if this addresses your use case

**Comment by kev1n11** [comment]
@esmet `DYNAMIC_METADATA` would definitely address my use case 👍 🙏 

Sorry for some reason I never received notification on this issue 🤦 Switching to gRPC (from HTTP) would be a little heavy for us at this stage just to support this use case (as we would need to perform proper load testing and migrate our endpoint.

**Comment by esmet** [comment]
Great. https://github.com/envoyproxy/envoy/pull/14843 should now allow for setting dynamic metadata when using an HTTP authorization server to prevent needing to move to gRPC.
