### ISSUE TITLE
Document External Processing Filter is unimplemented

### ISSUE THREAD

**Issue by salrashid123** [envoyproxy/envoy#14631]
Doc bug:

[External Processing Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto#external-processing-filter)  docs have boilerplate text 

```
This extension is functional but has not had substantial production burn time, use only with this caveat.
```
but doesn't seem to be implemented at all (its just a commit of the proto):

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/ext_proc/ext_proc.cc

---

suggest removing/hiding this filter until its usable or update the boilerplate text stating so.

**Comment by htuch** [comment]
@gbrail can you make the implementation status clearer?

**Comment by gbrail** [comment]
This was fixed and can be closed.

**Comment by salrashid123** [comment]
the boriler plate notices are abit confliciting but  readers will get the idea fromthe warning.
thx
