### ISSUE TITLE
envoy.reloadable_features.consume_all_retry_headers deprecation

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#14639]
Your change #11913 (router: consume all retry related headers) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @numerodix

**Comment by numerodix** [comment]
I'm happy to take this one.

**Comment by mattklein123** [comment]
@numerodix please do, thanks!
