### ISSUE TITLE
Envoy SSE(Server-sent events) support

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/envoy#14632]
*Title*: *Envoy SSE(Server-sent events) support*

*Description*:
> I have a requirement to proxy **http connections with SSE support**. I think by configuring envoy for **proxying http2** connections and configuring related timeouts like **stream_idle_timeout** will do the job but I'm not sure how a long held http/1.1 connection will behave in a scenario like this with envoy. Are there any recommended way to keep a **http/1.1 connection open for a long duration with envoy ?** 

> And if I want to implement a custom filter to perform some business logic, **what kind of a filter should I implement ?**

**Comment by htuch** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts.html for timeout advice. You probably want a HTTP filter.
