### ISSUE TITLE
envoy.reloadable_features.preserve_query_string_in_path_redirects deprecation

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#14648]
Your change #11493 (feat(router): keep query string by default for redirects) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @knight42

**Comment by knight42** [comment]
@mattklein123 Thanks for letting me know! I will file a PR to remove the old code path later this day.
