### ISSUE TITLE
envoy.reloadable_features.stop_faking_paths deprecation

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#14650]
Your change #11048 (http: pathless CONNECT) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by zuercher** [comment]
Fixed the title, since my change only added strict_1xx_and_204_response_headers (but I guess I sorted the list so stop_faking_paths moved).

**Comment by zuercher** [comment]
#14651 is the ticket for envoy.reloadable_features.strict_1xx_and_204_response_headers. I think this one should be for envoy.reloadable_features.stop_faking_paths but references the wrong PRs.

**Comment by zuercher** [comment]
@alyssawilk I'm going to reassign this to you. Whatever script created this and #14651 got confused because I sorted the flag names in #11458.

**Comment by alyssawilk** [comment]
ah yeah, the script uses git blame so moving it would do it.
thanks for checking, I'm happy to pick it up.
