### ISSUE TITLE
Go control plane generation 

### ISSUE THREAD

**Issue by kprakasam** [envoyproxy/envoy#14687]
*Title*: *Go control plane generation missing v2 API*

*Description*:
>I am trying to generate go control plane using `tools/api/generate_go_protobuf.py` when done  it is missing [v2 API](https://github.com/envoyproxy/go-control-plane/tree/master/envoy/api/v2). 

What I noticed is that script copies protobufs for each `bazel query kind '("go_proto_library", "@envoy_api//...")'`  which for some reason excludes targets under `@envoy_api//envoy/api/v2/...`

I posted in slack channel no one has responded so I am creating this issue.

*Repro steps*:
> From inside envoy folder run ./tools/api/generate_go_protobuf.py

**Comment by htuch** [comment]
@kprakasam v2 is now deprecated and will be removed at EOQ. Is there a reason to support this until then?

**Comment by kprakasam** [comment]
[V2 Api](https://github.com/envoyproxy/go-control-plane/tree/master/envoy/api/v2) continue to be generated by the CI pipeline, we build envoy with our filters with our own build scripts, I am just wondering if we are missing anything out that cause this failure.

**Comment by htuch** [comment]
@kyessenov any idea?

**Comment by kyessenov** [comment]
No idea. The script nukes envoy/ before copying https://github.com/envoyproxy/envoy/blob/master/tools/api/generate_go_protobuf.py#L103, and it hasn't been deleted on go-control-plane, so it must be working. Maybe it's some magic with generated_api_shadow?

**Comment by kprakasam** [comment]
All `*.pb.go` are copied from `bazel-bin/...` using targets listed by `bazel query kind '("go_proto_library", "@envoy_api//...")` however this query doesn't return any of the targets under `@envoy_api//envoy/api/v2/...`, is there any specific bazel setting cause this?

**Comment by htuch** [comment]
I just ran the query in my tree and I see:
```
...
@envoy_api//envoy/api/v2:pkg_go_proto
@envoy_api//envoy/config/listener/v2:pkg_go_proto
@envoy_api//envoy/config/filter/accesslog/v2:pkg_go_proto
@envoy_api//envoy/api/v2/route:pkg_go_proto
@envoy_api//envoy/type/tracing/v2:pkg_go_proto
@envoy_api//envoy/type/metadata/v2:pkg_go_proto
@envoy_api//envoy/api/v2/listener:pkg_go_proto
@envoy_api//envoy/api/v2/endpoint:pkg_go_proto
@envoy_api//envoy/api/v2/cluster:pkg_go_proto
@envoy_api//envoy/api/v2/auth:pkg_go_proto
@envoy_api//envoy/api/v2/core:pkg_go_proto
@envoy_api//envoy/type/matcher:pkg_go_proto
...
```
@kprakasam maybe this is something in your tree?

**Comment by kprakasam** [comment]
We use Envoy  as submodule to the filters we have, when the query is run from top level folder instead of submodule envoy folder theses targets are missing. 

Anyway we need to modify `generate_go_protobufs.py` to add our own targets, when I add `@envoy_api//envoy/api/v2/...` to the list it's working.

I'll leave it up to guys to treat this as a bug or not.

```
TARGETS = '@envoy_api//...'
V2_TARGETS = '@envoy_api//envoy/api/v2/...'
.
.
.
def generateProtobufs(output, generate_ebay_protos=False):
  bazel_bin = check_output(['bazel', 'info', 'bazel-bin']).decode().strip()
  bazel_bin = '/private/var/tmp/_bazel_pkannan/c99961cf5f04eb2f0509306e269148cf/execroot/ebay_envoy/bazel-out/darwin-fastbuild/bin'
  go_protos = check_output([
      'bazel',
      'query',
      'kind("go_proto_library", %s)' % TARGETS,
  ]).split()

  go_protos = go_protos + check_output([
      'bazel',
      'query',
      'kind("go_proto_library", %s)' % V2_TARGETS,
  ]).split()
.
.
.
```

**Comment by htuch** [comment]
Feel free to contribute a patch here. I don't see this as being a bug given that this is a helper script for projects like go-control-plane, but has no tests and isn't used as part of the Envoy build itself.

**Comment by kprakasam** [comment]
@htuch
