### ISSUE TITLE
Add More Features to MySQL Proxy

### ISSUE THREAD

**Issue by qinggniq** [envoyproxy/envoy#14697]
*Title*: *Add More Features of MySQL Proxy*

*Description*:

Currently, Envoy MySQL Proxy seems only support collecting stats. Our team wants to extend MySQL Proxy, make it support more features like *route, authentication, mirrors, fault* like *Redis Proxy*.

There are already some work/proposals of supporting MySQL relevant area in the community, see blow.  I wonder whether it makes sense of community to consider adding these features of MySQL Proxy. 

[optional *Relevant Links*:]

[#13551](https://github.com/envoyproxy/envoy/issues/13551)
[#3501](https://github.com/envoyproxy/envoy/issues/3501)
[#3502](https://github.com/envoyproxy/envoy/pull/3502)
[#4975](https://github.com/envoyproxy/envoy/pull/4975)

**Comment by htuch** [comment]
Seems reasonable to me. @rshriram any thoughts for folks extending the filter?

**Comment by dio** [comment]
Let's do this!

**Comment by qinggniq** [comment]
I'm now developing the authentication function , but I found that currently the codec logic of connection phase is not enough to support the authentication function . So I plan to complete the codec logic first , might migrate codec logic of [mysql-proxy](https://github.com/mysql/mysql-proxy ) . Do you have any ideas about this plan ?

**Comment by dio** [comment]
@qinggniq I think that's a fair observation. Mind to break it down in a doc/issues so we can have a complete laundry list on codec? Thank you!

**Comment by qinggniq** [comment]
> @qinggniq I think that's a fair observation. Mind to break it down in a doc/issues so we can have a complete laundry list on codec? Thank you!

I am glad to do this.
