### ISSUE TITLE
ecds: add support for network filters

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#14696]
Implement ECDS for network filters in listeners. API added [here](https://github.com/envoyproxy/envoy/pull/14674)

**Comment by kyessenov** [comment]
QQ: from a quick glance, https://github.com/envoyproxy/envoy/blob/master/source/common/filter/http/filter_config_discovery_impl.h would work just fine for network filters. However, it would need to be templatized by factory and factory callback classes. This would make it a header-only source file. Is that a reasonable approach style-wise?

**Comment by htuch** [comment]
@kyessenov if you can minimize what gets dragged into the template I think it would be good; we prefer not having massive header-only templates. E.g.. put a bunch of the shared logic in a shared base class.

**Comment by tbarrella** [comment]
I plan to redo and finish #14717 with these steps:

- [ ] Move files (envoy/filter/http -> envoy/filter, etc.)
- [ ] Create shared base classes
- [ ] Templatize code
- [ ] Make network filter code additions/changes/tests

**Comment by tbarrella** [comment]
I stopped work on this for now so @kyessenov or someone else can continue. Templatizing ECDS code so it can be used for more than just HTTP filters is done, but I did not start any work on network filters.

**Comment by zirain** [comment]
@kyessenov do you plan to bring back https://github.com/envoyproxy/envoy/pull/14717?
