### ISSUE TITLE
envoy 1.17.0 osx build failure

### ISSUE THREAD

**Issue by chenrui333** [envoyproxy/envoy#14690]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
ninja -v
ninja -v install
copy_dir_contents_to_dir $BUILD_TMPDIR/$INSTALL_PREFIX $INSTALLDIR
replace_in_files $INSTALLDIR $BUILD_TMPDIR \${EXT_BUILD_DEPS}
replace_in_files $INSTALLDIR $EXT_BUILD_DEPS \${EXT_BUILD_DEPS}
mkdir -p $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/copy_curl/curl
copy_dir_contents_to_dir $INSTALLDIR $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/copy_curl/curl
touch $EXT_BUILD_ROOT/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/empty_curl.txt
cd $EXT_BUILD_ROOT
_____ END BUILD SCRIPT _____
rules_foreign_cc: Build script location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/curl/logs/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/curl/logs/CMake.log

Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 979.353s, Critical Path: 257.58s
INFO: 3677 processes: 1249 internal, 2427 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1685628642
relates to https://github.com/Homebrew/homebrew-core/pull/68841

**Comment by htuch** [comment]
`google_com_proxy.v2.yaml` no longer exists, do you have some scripts wrapped around this that are causing an issue?

**Comment by chenrui333** [comment]
Cool, what is the replacement for that config file?

**Comment by chenrui333** [comment]
> Mac OS 1.17 builds fine in Envoy's CI, see https://dev.azure.com/cncf/envoy/_build?definitionId=3

the build works fine, it is just the example test failed (to verify envoy function)

**Comment by htuch** [comment]
`configs/envoyproxy_io_proxy.yaml`. Sounds like I can close this out.

**Comment by chenrui333** [comment]
thanks! I will give that config a try.
