### ISSUE TITLE
[grpc-transcoding] Transcode unknown variable bindings

### ISSUE THREAD

**Issue by jhance** [envoyproxy/envoy#14710]
I have a use-case where I have a grpc server that is acting as a sort of proxy and needs to forward unknown variable bindings to its upstream. I plan to do the implementation but I would like to upstream this feature so that we don't have to carry forward an internal patch indefinitely and would like early feedback on the idea/implementation notes.

Currently variable bindings from path matching can only be transcoded if the request message contains them, e.g. a route for `/route/{path=**}` will need a message like this:

```
message Request {
  string path = 1;
  google.api.HttpBody body = 2;
}
```

I propose for unknown variable bindings, we recognize a special protobuf in the same way we recognize `HttpBody`:

```
message Request {
  // I don't know what package this should go in
  envoy.google.api.extensions.UnknownVariableBindings unknown_bindings = 1;
}
```

Where this particular message is defined as
```
message  UnknownVariableBindings {
  map<string, string> bindings = 1;
}
```

Implementation wise, we can locate the `UnknownVariableBindings` at the same time we recognize `HttpBody` and store it in `MethodInfoPtr` alongside there.

To transcode the actual value, we will take advantage of the fact that an embedded message in protobuf is the same wire format as a string/bytes field. This means we can construct one additional `BindingInfo` here https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L359 (by accumulating the list of unknown bindings in the loop above, and then creating the `BindingInfo` later, by constructing the protobuf map, serializing it to bytes, and putting the serialized protobuf as the `value` for the `BindingInfo`. In this way we won't need any modifications to the upstream grpc transcoder library.

We can either serialize the protobuf by hand in the above loop (to avoid copying) or assume that the amount of keys is rather small and construct then serialize at the end (for readability).

**Comment by jhance** [comment]
Suggestion by @euroelessar that I also like: We can place this in `HttpBody` instead.

**Comment by qiwzhang** [comment]
My feeling is such usage is very special, it requires special codes in the grpc_transcoder filter to handle it, it may de-stabilize the code which is used by many products.  It will make the code too complicated that it is not easy to maintain.

**Comment by euroelessar** [comment]
Hi @qiwzhang,

From usage point of view, we have a use case where individual grpc endpoints _can_ serve hundreds of individual paths using the same logic. The caveat is that this endpoint needs to know some additional metadata derived from the path segments.
One of potential solutions is to pass original url to the server and replicate all the parsing/matching flow but that's arguable too much of a burden for the application (+ the complexity of ensuring that route configuration is in sync between envoy and the application).

From complexity point of view, the proposed change of populating `extensions` field with unknown bindings is 3 semantically-meaningful lines of code (+ mechanical addition of new argument to some functions + tests), so it's likely not too bad.
It can be gated by a boolean option to ensure that it doesn't affect any products by default.

Another alternative would be to provide support of extensions for transcoding logic (e.g. allow users to write own extensions based on `extensions` field of `HttpBody` in response + similar flow in request. This is more powerful but arguably much more invasive change.

Any thoughts?

**Comment by jhance** [comment]
@qiwzhang Here is draft PR: https://github.com/envoyproxy/envoy/pull/15338
