### ISSUE TITLE
deps: Adopt patch free Chromium URL library

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#14743]
When we have upstream Chromium to give us an IDN-free optional build we can adopt Chromium URL library without patching it.

Context: https://github.com/envoyproxy/envoy/pull/14583#discussion_r559660170

**Comment by yanavlasov** [comment]
I think we should first see if we can avoid the patch altogether. Chromium may not be too motivated to make this change as it is not part of their use case.

**Comment by yanavlasov** [comment]
The patch has been minimized in PR #14853 but it still requires a separate build target to build library without files that depend on ICU.
