### ISSUE TITLE
Account for possible trailing dot in domain name matching

### ISSUE THREAD

**Issue by boringuy** [envoyproxy/envoy#14748]
*Title*: Account for possible trailing dot in domain name matching

*Description*:
"example.com" is the relative domain name
"example.com." is the absolute domain name
"http://example.com/" and "http://example.com./" are equivalent but when setting up the "domains" field under VirtualHosts, one needs to explicitly specify "domains: ["example.com", "example.com."]" for the match to work.
It would be nice that both the domain name in the yaml config and in the host/:authority header be normalized before matching so one does not need to explicitly specify both form of the same domain name.

[optional *Relevant Links*:]
http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by cretz** [comment]
Bump. Right now our control plane duplicates every vhost domain with an appended dot to get around this. I suspect we'd opt in to this with a `strip_trailing_host_dot` akin to what `strip_matching_host_port` already does to preserve existing behavior. Thoughts? I may be able to send in PR if that approach is acceptable.

**Comment by mattklein123** [comment]
> I suspect we'd opt in to this with a strip_trailing_host_dot akin to what strip_matching_host_port already does to preserve existing behavior. Thoughts? I may be able to send in PR if that approach is acceptable.

Yeah that makes sense to me.
