### ISSUE TITLE
All tests segfault on arm64 & clang-10

### ISSUE THREAD

**Issue by jrajahalme** [envoyproxy/envoy#14756]
All bazel tests SEGFAULT after otherwise completing all test cases successfully when compiled with clang-10 on arm64. This appears to be a clang-10 bug affecting Envoy tests via code in gperftools heap checker. See related bug reports:

- gperftools issue: https://github.com/gperftools/gperftools/issues/1241
- clang Bugzilla: https://bugs.llvm.org/show_bug.cgi?id=48798

Since Envoy binary only crashes if run with `HEAPCHECK` defined (e.g., `HEAPCHECK=normal`), and then only when the process exits, I'm not repeating stack traces here (see the linked bug reports above).

While a compiler bug like this may seem concerning, the code pattern under which the SEGFAULT happens seems to be fairly specialized (low-level syscall inline assembly in a C++ class member function).

**Comment by mattklein123** [comment]
IIRC this is a known issue? @lizan?

**Comment by jrajahalme** [comment]
@mattklein123 Upstream fix proposed: https://github.com/gperftools/gperftools/pull/1244.

**Comment by lizan** [comment]
Yeah this is known when I enabled arm64 but I haven't dig it deeply. Thanks for looking into @jrajahalme

**Comment by jrajahalme** [comment]
gperftools fix has been applied: https://github.com/gperftools/gperftools/commit/c5747615da78f7c2d91112f2a6b6b4da4f18540a.
