### ISSUE TITLE
Add custom resolver support for v2 Address messages

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1477]
In the v2 API, we allow `Address` messages to specify a resolver plugin. This will transform logical addresses to concrete addresses. This supports address virtualization and address namespaces that are non-standard. This issue will track the implementation of the registration facility, invocation of the resolver at appropriate code sites and an example resolver for testing.

The resolver should be capable of returning an arbitrary `Address::Instance` subclass, which will be able to support a notion of a string representation for both the logical and physical address. These can then be plumbed into logs, stats and generated headers as distinct concepts.

**Comment by akonradi** [comment]
This seemed straightforward until I started looking at the already-existing-but-unrelated DNS resolver, which resolves names asynchronously. It seems like that's the right way to resolve names in general, but the code paths that would use this expect config parsing to be a synchronous affair.

**Comment by htuch** [comment]
I guess the question is how dynamic do we need to be? We could do resolution at config ingestion time, which would probably be fine for Google, but the general resolver scheme would probably also support this happening at bind/connect time. I'd be fine with a synchronous config time load resolution as a first step, because that's all that Google needs.

The use cases for the resolver so far have been IP NAT and port name mapping (from a named port to a specific port). I think there was also the idea we would use SRV in the `Address` for existing DNS resolution, but that can follow the existing path.

If you want to do this at `bind` time, then we need to do some dispatcher based callback once the resolution happens. That shouldn't be too bad, but I haven't looked at the code.

**Comment by htuch** [comment]
Thinking about how `onConfigUpdate()` works today, the interface is very synchronous. Would it be simpler to do the resolution at `bind` time?

**Comment by akonradi** [comment]
We could defer resolution until `bind()`, `connect()`, or `ip()` are called if they're already treated as blocking methods. A fancier implementation could even start an asynchronous request when the Instance is first created to reduce the amount of time spent blocking, but that might be overkill.

**Comment by akonradi** [comment]
After talking with @htuch in person, this is going to stay completely synchronous for now - no remote lookups, no network access. The calling code could be modified to support asynchronous lookups, but it would require significant changes and a lot more callbacks sprinkled around.

**Comment by mattklein123** [comment]
@htuch @akonradi +1 let's keep it simple/synchronous unless we have a clear need for something else.

**Comment by mattklein123** [comment]
I think this is done. Closing.
