### ISSUE TITLE
VHDS: Is there any way to update resources that have been unsubscribed?

### ISSUE THREAD

**Issue by storyicon** [envoyproxy/envoy#14776]
I found that whenever vhds subscribes to a resource, it will unsubscribe from the previous resource, which causes me to be unable to update the old resource issued through VHDS.

---

### prepare:
The Listener listened to port `50000` and pointed to the route named `local_route`, which was configured with `vhds`.

### step1: 
```
curl --location --request GET '127.0.0.1:50000'  --header 'Host: a'
```
VHDS Server will receive:
```
DeltaDiscoveryRequest{
    ResourceNamesSubscribe: ["local_route/a"],
    ResourceNamesUnsubscribe: [],
}
```
Then VHDS Server responds:
```
DeltaDiscoveryResponse{
    Resources: []Resource{
        {
            Name: "local_route/a",
            Version: ...
            Resource: ...
        }
    }
}
```
### step2:
```
curl --location --request GET '127.0.0.1:50000'  --header 'Host: b'
```

VHDS Server will receive:
```
DeltaDiscoveryRequest{
    ResourceNamesSubscribe: ["local_route/b"],
    ResourceNamesUnsubscribe: ["local_route/a"],
}
```
Then VHDS Server responds:
```
DeltaDiscoveryResponse{
    Resources: []Resource{
        {
            Name: "local_route/b",
            Version: ...
            Resource: ...
        }
    }
}
```

My question is, why does the subscription of `local_route/b` cause the cancellation of `local_route/a`?
Is there any way I can update `local_route/a`?

I haven’t read Envoy’s source code for VHDS, so I’m not sure if it’s a problem with my way of using it. There are too few documents/usage related to VHDS.

**Comment by asraa** [comment]
What version of Envoy are you using? 
@dmitri-d Do you think this https://github.com/envoyproxy/envoy/issues/12158 is related?

**Comment by dmitri-d** [comment]
It sounds very much like the issue in https://github.com/envoyproxy/envoy/issues/12158, which should be resolved now (see https://github.com/envoyproxy/envoy/pull/12819).

**Comment by storyicon** [comment]
I encountered this problem in Envoy version `1.15.0`, and it no longer exists in `1.16.0`.
What confuses me is that I did not find the relevant change information in the CHANGELOG of `v1.15.0`~`v1.16.0`. Did I miss something?
