### ISSUE TITLE
In Podman or Docker: Permission denied on SELinux machines

### ISSUE THREAD

**Issue by rrichardson** [envoyproxy/envoy#14787]
*Permissions issues when running in Podman or Containerd (DockerCE)*

*Description*: When starting envoy in podman or docker (as a UID other than 0) 
```
chown: changing ownership of '/dev/stdout': Permission denied
chown: changing ownership of '/dev/stderr': Permission denied
```

Presumably it's complaining about this line : https://github.com/envoyproxy/envoy/blob/main/ci/docker-entrypoint.sh#L26 

Even if you run as root, SELinux takes exception to a container changing ownership of stdout and stderr. 

I haven't found a more elegant workaround than adding this flag in podman: 
```
--security-opt label=disable 
```
That's a bit of a blunt hammer.  There is probably a more precise approach. 

I *think* on non-root podman with cgroupsv2,  the `chown /dev/std*`  approach is probably not needed at all, because podman will give the container its very own FDs that pretend to be in, out and err.   Maybe in this script we should check the ownership before attempting to change them?

*Repro steps*:
1. On a recent Linux machine with SELinux enabled (I was working on FCOS 33) 
run: 
```
podman run \
  --name=envoy \
  --hostname=envoy \
  -e ENVOY_UID=1000 \
  -e ENVOY_GID=1000 \
  --user root \
  --security-opt label=disable \
  -p [2600:aba:9d6:baba:f0c0:52ee::]:6443:6443 \
  -v /var/lib/envoy/config/:/config \
  -v /var/lib/envoy/cluster:/cluster \
  docker.io/envoyproxy/envoy:v1.17-latest
```

**Comment by phlax** [comment]
> Maybe in this script we should check the ownership before attempting to change them?

this seems reasonable, do you want to PR this ?

**Comment by phlax** [comment]
the other possible improvment here is to check that the user is root and/or is able to chown

**Comment by phlax** [comment]
@rrichardson this should be resolved in #15115 can you confirm

**Comment by rrichardson** [comment]
I'll take a look today or tomorrow. Thanks.

**Comment by rrichardson** [comment]
@phlax - Using the latest envoyproxy/envoy-dev image,  I have verified that the non-root podman execution works correctly.
My invocation looked like: 

```
podman run -it --name envoy --rm -v /var/envoy:/config envoyproxy/envoy-dev:latest -c /config/config.yaml
```

Running as a non-privileged user (that owns the /var/envoy directory,  it was able to run, write to stdout/stderr and load the config.

**Comment by phlax** [comment]
brilliant - shall we close this ticket ?

**Comment by AkhilRaja** [comment]
@rrichardson @phlax I still get this issue when I deploy this to cloud run on Google cloud. Any workarounds for me ? Stuck on this for a long time now :(  Thanks in advance
