### ISSUE TITLE
Add environment variable DataInput extension

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#14781]
Tracks adding a DataInput extension that allows matching on an environment variable. 

This would allow users to do things such as following a match path only for a specific instance (i.e. by matching on HOSTNAME) while still sending out the same xDS configuration to a large set of Envoy instances.

**Comment by snowp** [comment]
Currently the easiest way to add this would be to add it as a `DataInput<HttpMatchingData>`, but it would be interesting to support this more generically by having a different category of `DataInput`s that doesn't require protocol data (other examples would be things like the current time, information from Envoy's bootstrap, etc.) that would automatically work regardless of which protocol data the match tree is using.

**Comment by kailun-qin** [comment]
We might not be able to abstract one single category of `DataInput` for all the potential usages here (env vars, current time, info from bootstrap etc.). I guess the requirement here is to start w/ the env vars at the first place?

**Comment by snowp** [comment]
When I mentioned having a different category of DataInput I was talking about how the templating of DataInput works today. 

Right now each DataInput is templated by the protocol specific input (e.g. `DataInput<HttpMatchingData>`), so if we wanted to support an env var input we'd have to make a `EnvironmentInput : public DataInput<HttpMatchingData>` and register it. 

This typing means that we'd need to do the same if we ever wanted to use it in another context, e.g. if we introduced `DataInput<NetworkMatchingData>`, then we'd need to create a new `EnvironmentNetworkInput : public DataInput<NetworkMatchingData>`.  As you can see this is a bit cumbersome, so it would be nicer if we could define a `EnvironmentInput : public GenericDataInput` which wasn't dependent on the protocol type.

When I listed the examples I was listing other input types that would fit under this `GenericDataInput` category, not insinuating that they should be the same input type.
