### ISSUE TITLE
Need to support stat tags in Cluster config

### ISSUE THREAD

**Issue by l8huang** [envoyproxy/envoy#14807]
*Title*: Add tags to cluster stat

*Description*:
Currently cluster stat consists of scope name and stat name, for example:
`cluster.cluster_0.update_success`
in which `cluster.cluster_0` is scope name, and `update_success` is stat name. The `prefix` is empty and tags are not supported.

We have a requirement which need to add additional information to cluster Prometheus metrics. My first thought is using `alt_stat_name` and encoding the information into it, then use `stats_config.stats_tags` to extract these information as tags in Prometheus output. But I run into a problem quickly: the information contains `:`, which will be converted to `_`. That's, the extracted tag will be mutated, which is not what we want. So I need to find another way to do it.

Considering Envoy's stat supports tags, I'm thinking add tags support  to cluster config could be a better way.

Please kindly let me know if I misunderstood any thing.
CC @envoyproxy/api-shepherds

**Comment by snowp** [comment]
Conceptually this seems fine but I'm not sure if we have a great way to ensure that it would apply to all cluster stats since there are a lot of per cluster stats that are created throughout the code base.

@jmarantz might have thoughts here
