### ISSUE TITLE
MySQL codec need to be improved

### ISSUE THREAD

**Issue by qinggniq** [envoyproxy/envoy#14809]
*Title*: *MySQL codec need to be improved*

In #14697, we decide to implement the authentication function of MySQL Proxy, but currently the Envoy MySQL Codec has not fully support MySQL Protocol, especially not support the `auth plugin name`, `auth plugin data` fields.  Thus MySQL Proxy will only support [Old Password Authentication](https://dev.mysql.com/doc/internals/en/old-password-authentication.html), which is removed after mysql 5.7.5([ref](https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html)). 

To make MySQL Proxy more  versatile, we need to complete MySQL Codec, help for further development.

[optional *Relevant Links*:]
> https://dev.mysql.com/doc/internals/en/connection-phase.html
> https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html

**Comment by qinggniq** [comment]
cc @dio @htuch

**Comment by yanavlasov** [comment]
@rshriram @venilnoronha @mattklein123 as current codeowners
