### ISSUE TITLE
Make TLS OIDs accessible to HTTP extensions

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#14801]
*Title*: Make TLS OIDs accessible to HTTP extensions

*Description*:
HTTP/Network extensions can access the downstream TLS connection info via something like
```cpp
decoder_callbacks_.streamInfo().downstreamSslConnection();
```
However, the `Envoy::Ssl::ConnectionInfo` interface doesn't appear to provide access to querying OIDs. The particular use-case I want to solve with this is OID-matching. For OCSP stapling we already have some utility code for parsing OIDs out of a `CBS` (crypo bytestring). I'm thinking it would be convenient to have

```cpp
virtual absl::Span<const std::string> oidsPeerCertificate() const PURE;
virtual absl::Span<const std::string> oidsLocalCertificate() const PURE;
```

like we do for `dnsSansPeerCertificate` and `dnsSansLocalCertificate`.

This assumes there is not currently a way for an HTTP extension to access client certificate OIDs, which I have not yet found as the `Envoy::Ssl::ConnectionInfo` seems to only return specific fields or SHA hashes of the certificate.

*Relevant Links*:
* https://github.com/envoyproxy/envoy/blob/main/include/envoy/ssl/connection.h#L19
* https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/ocsp/asn1_utility.h#L109-L114
* https://boringssl.googlesource.com/boringssl/+/HEAD/include/openssl/bytestring.h#27

**Comment by derekargueta** [comment]
bump

**Comment by derekargueta** [comment]
@mattklein123 @PiotrSikora so I was thinking about this a bit more, and I should start with what the actual desired feature is - ability to match against TLS OIDs and reject connections that don't match. I started with this ticket thinking to use this in an HTTP filter that would reject with HTTP 400 (currently what we have in Nginx, checks certain variables and rejects with HTTP 400) but since this is connection-level info, I'm wondering if the ClientSSLAuth network filter is a better place for this functionality. Does this seem like a reasonable contribution?

**Comment by mattklein123** [comment]
I think either is reasonable. I think it really depends on what type of rejection you want (connection close, nice HTTP response, etc.).
