### ISSUE TITLE
quick start demo file doesn't enable admin

### ISSUE THREAD

**Issue by sandipb** [envoyproxy/envoy#14811]
https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy says that starting envoy with the given demo config `envoy-demo.yaml` should result in:

> The Envoy admin endpoint should also be available at http://localhost:9901

It doesn't seem to working, as the admin section is not enabled in the config.

**Comment by yanavlasov** [comment]
This is definitely a bug. Either doc needs to be updated or demo configuration.

**Comment by phlax** [comment]
hi i removed the admin section from most examples as it wasnt necessary for the examples and/or exposing admin needed to be documented

i think this one needs it added back

@sandipb do you want to pr a fix ? if not i am happy to

**Comment by sandipb** [comment]
Please ignore the earlier commit(8f2ba91). The last one is my actual attempt.
