### ISSUE TITLE
How to use Envoy to support GRPC protobuf field based load balance

### ISSUE THREAD

**Issue by jackyh** [envoyproxy/envoy#14813]
**If I have a route.proto like this:**

syntax = "proto3";
package routing;
message CopyImageRequest {
    int32 camera_id = 1;
}
message CopyImageResponse {
    string result = 1;
}
service RoutingService {
    rpc service_A_hello(CopyImageRequest) returns (CopyImageResponse) {};
    rpc service_B_hello(CopyImageRequest) returns (CopyImageResponse) {};
    rpc service_C_hello(CopyImageRequest) returns (CopyImageResponse) {};
}

**how can I use Envoy to achieve ingress load balance by "camera_id"?**

**Comment by snowp** [comment]
Are you asking to use a protobuf field value as the hashing key for one of the deterministic load balancers? Or something else?

In general we don't have support for extracting field values from a gRPC payload, though there has been various asks in this space in the past, so I wouldn't be opposed to adding this if someone wants to take own it.

**Comment by mitchsw** [comment]
I am also looking to consistently load balance a gRPC service, using some request field as the hash key.

It looks like creating a "gRPC proxy" (similar to the existing Dubbo proxy?), and an associated `LoadBalancerContext` is a fairly large project. The proxy would also require the .proto descriptor to use the [Reflection APIs](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection) to extract some "field path".

**Comment by mitchsw** [comment]
Actually, on second look, we could build off #10263, and just write a HTTP filter that extract some field into a `Envoy::Http::Hashable` filter state object. I don't know exactly how to do that, but we may be able to crib most of the logic needed for proto reflection from [grpc_json_transcoder](https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/grpc_json_transcoder).

**Comment by cliveseldon** [comment]
@mitchsw did you get anywhere with as I'm interested in doing something similar?
