### ISSUE TITLE
Add support for QUIC upstream

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#14829]
As we close in on https://github.com/envoyproxy/envoy/issues/2557 we want to start thinking about upstream support for QUIC.

The main use case may be for mobile (https://github.com/envoyproxy/envoy-mobile/issues/1033) but it could be used in general for forward proxying and cross-data center hops.

v1 would be hard-coded QUIC with no failover, but for use on the internet it would eventually need to include  things like QUIC vs TCP racing, 0-rtt credential caching, alt-scv cache, etc.

**Comment by davinci26** [comment]
Feel free to tag me for any windows specific (test or otherwise) issues

**Comment by alyssawilk** [comment]
Closing as this is functionally done, though there's bells and whistles yet
