### ISSUE TITLE
Disable session ID based TLS session resumption

### ISSUE THREAD

**Issue by amitkatyal** [envoyproxy/envoy#14835]
Is there a way to disable the session ID based TLS session resumption? The Envoy docs only talk about the session ticket based session resumption but there is no mention of the session ID based TLS session resumption.

**Comment by yanavlasov** [comment]
@PiotrSikora might know

**Comment by PiotrSikora** [comment]
There is not.

**Comment by ggreenway** [comment]
It wouldn't be difficult to add: add a new config setting for it, then have the context call `SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_OFF)`.
