### ISSUE TITLE
in k8s has port Permission denied after version 15

### ISSUE THREAD

**Issue by imogenliu** [envoyproxy/envoy#14838]
got an error: **envoy cannot bind '0.0.0.0:80': Permission denied** when deploy to k8s, but the strange thing is that local docker-compose is working fine.

I have tried version: v1.17.0, v1.16.2,  v1.15.3, which working fine in local docker-compose, but have this error in k8s.
but v1.14.6 working for both k8s and local docker-compose

**Comment by yanavlasov** [comment]
This does not look like an Envoy bug. You can also ask this question in the `envoy-users` channel on the envoyproxy slack, which may get you a quicker response.

**Comment by lizan** [comment]
We no longer run Envoy as root by default starting Envoy 1.15.x, you can set ENVOY_UID and ENVOY_GID to 0, or give it right capabilities to listen on a well-known port.

https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.15.0
> build: runs as non-root inside Docker containers. Existing behaviour can be restored by setting the environment variable ENVOY_UID to 0. ENVOY_UID and ENVOY_GID can be used to set the envoy user's uid and gid respectively.
