### ISSUE TITLE
network filter test fail

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#14836]
FilterStatus ExampleContext::onDownstreamData(size_t data_length, bool end_stream) {
  WasmDataPtr data = getBufferBytes(WasmBufferType::NetworkDownstreamData, 0, data_length);
  logTrace("onDownstreamData " + std::to_string(id()) + " len=" + std::to_string(data_length) +
           " end_stream=" + std::to_string(end_stream) + "\n" + std::string(data->view()));
  setBuffer(WasmBufferType::NetworkDownstreamData, 0, 5, "write");
  return FilterStatus::Continue;
}

The "write" string did not successfully write to Downstream by tcpdump capture.

The test environment: redis server and client.
redis client: Execute the "get name" command
tcpdump show:
00:02:53.786968 IP (tos 0x0, ttl 64, id 19055, offset 0, flags [DF], proto TCP (6), length 75)
    10.73.87.58.48918 > 10.73.87.58.1999: Flags [P.], cksum 0xc343 (incorrect -> 0xd0b0), seq 18:41, ack 9646, win 512, options [nop,nop,TS val 2912045230 ecr 2912042425], length 23
	0x0000:  4500 004b 4a6f 4000 4006 2d38 0a49 573a  E..KJo@.@.-8.IW:
	0x0010:  0a49 573a bf16 07cf ec00 5b78 b3fe dff6  .IW:......[x....
	0x0020:  8018 0200 c343 0000 0101 080a ad92 48ae  .....C........H.
	0x0030:  ad92 3db9 2a32 0d0a 2433 0d0a 6765 740d  ..=.*2..$3..get.
	0x0040:  0a24 340d 0a6e 616d 650d 0a              .$4..name..

---------------------------------------
name terminates, not write

**Comment by yanavlasov** [comment]
Looks like this is a WASM filter which only applied to HTTP traffic.

**Comment by liuqi-sun** [comment]
> Looks like this is a WASM filter which only applied to HTTP traffic.

This is a network filter example. 
http WASM filter example is here: https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/example/http_wasm_example.cc
The  "setBuffer(WasmBufferType::HttpResponseBody, 0, 12, "Hello, world");" function is successful.

**Comment by yanavlasov** [comment]
I see, look like documentation is out of date. @PiotrSikora @mathetake @lizan for any comments.

**Comment by PiotrSikora** [comment]
`setBuffer(WasmBufferType::NetworkDownstreamData, ...)` modifies content of the downstream buffer (which is going to be sent to upstream by other filters chain, e.g. `tcp_proxy`), it's not for sending payload downstream.

In any case, the linked test clearly passes.

Also, you might want to open further issues about using [Proxy-Wasm C++ SDK](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) in its repo, not here.
