### ISSUE TITLE
circuit breaker retry budgets have no defaults (disagreeing with docs)

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#14842]
*Title*: *circuit breaker retry budgets have no defaults (disagreeing with docs)*

*Description*:
The [docs on retry_budget](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers-thresholds-retrybudget) say that `budget_percent` defaults to 20%, and that `min_retry_concurrency` defaults to 3. 

However, it looks like the code does no such thing and the actual behavior of `retry_budget: {}` is to not use a retry budget at all. This snippet is from source/common/upstream/upstream_impl.cc:

```
  absl::optional<double> budget_percent;
  absl::optional<uint32_t> min_retry_concurrency;
  if (it != thresholds.cend()) {
    <snip some unrelated things>
    if (it->has_retry_budget()) {
      // The budget_percent and min_retry_concurrency values do not set defaults like the other
      // members of the 'threshold' message, because the behavior of the retry circuit breaker
      // changes depending on whether it has been configured. Therefore, it's necessary to manually
      // check if the threshold message has a retry budget configured and only set the values if so.
      budget_percent = it->retry_budget().has_budget_percent()
                           ? PROTOBUF_GET_WRAPPED_REQUIRED(it->retry_budget(), budget_percent)
                           : budget_percent;
      min_retry_concurrency =
          it->retry_budget().has_min_retry_concurrency()
              ? PROTOBUF_GET_WRAPPED_REQUIRED(it->retry_budget(), min_retry_concurrency)
              : min_retry_concurrency;
    }
  }
  return std::make_unique<ResourceManagerImpl>(
      runtime, runtime_prefix, max_connections, max_pending_requests, max_requests, max_retries,
      max_connection_pools,
      ClusterInfoImpl::generateCircuitBreakersStats(stats_scope, priority_stat_name,
                                                    track_remaining, circuit_breakers_stat_names_),
      budget_percent, min_retry_concurrency);
```

and then in source/common/upstream/resource_manager_impl.h if `budget_percent` is an empty optional then no retry budget is used.

We've also observed this behavior in production by running a fault injection test before/after setting a default retry budget.

**Comment by mpuncel** [comment]
Ah I see that if you set these values via Runtime, then the defaults are correct. but not if you set them via xDS:

```
      const double budget_percent = runtime_.snapshot().getDouble(
          budget_percent_key_, budget_percent_ ? *budget_percent_ : 20.0);
      const uint32_t min_retry_concurrency = runtime_.snapshot().getInteger(
          min_retry_concurrency_key_, min_retry_concurrency_ ? *min_retry_concurrency_ : 3);
```

**Comment by yanavlasov** [comment]
@snowp for any comments

**Comment by snowp** [comment]
I think the mismatch in expected behavior comes from the fact that it requires at least one of the fields in RetryBudget to be set in order to treat RetryBudget as enabled, which differs from other configuration usages where setting the outer message to empty enables the feature. I would have expected 

```
retry_budget: {}
```

to enable it with the defaults, but this doesn't seem to be the case.

@tonya11en do you recall if this was intentional?

**Comment by tonya11en** [comment]
> @tonya11en do you recall if this was intentional? 

Sorry for the delay. I don't think this behavior was the intent. It would make sense to use the retry budgets over the retry circuit breakers if there is anything set in the runtime (even {}) or over xds.

I'll take a closer look today.
