### ISSUE TITLE
"LEAST_REQUEST" lb_policy can possibly select the host with most active requests.

### ISSUE THREAD

**Issue by AdiJohn** [envoyproxy/envoy#14859]
*Title*: "LEAST_REQUEST" lb_policy can possibly select the host with most active requests.

*Description*: 
With regarding to unweighted least request loadbalacing, the behavior [described in Envoy doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#weighted-least-request):

> An O(1) algorithm which selects N random available hosts as specified in the configuration (2 by default) and picks the host which has the fewest active requests. This is also known as P2C (power of two choices). The P2C load balancer has the property that **a host with the highest number of active requests in the cluster will never receive new requests**.

However, with the [current implementation](https://github.com/envoyproxy/envoy/blob/2ee9543fbb0fccdb69d4dcd8cb57a19743afb94b/source/common/upstream/load_balancer_impl.cc#L854), it can possibly select the host with most active requests, because it is possible that the N randomly selected hosts are the same, or at least contain duplicates (i.e., when the resulted [rand_idx](http://go/gh/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L858) are the same across iterations). Is this expected?

**Comment by mattklein123** [comment]
I think this is by design at least with the current implementation. Feel free to do a doc update. In the future we could consider an option to retry to avoid duplicates but that seems like a different feature request, and I'm not sure it matters in practice. cc @tonya11en

**Comment by tonya11en** [comment]
We all had a fairly lengthy discussion in a PR submitted to avoid duplicates when going P2C (https://github.com/envoyproxy/envoy/pull/11006). Take a look at the discussion for context, but I believe the gist of it is that the selection probability differences from preventing duplicate selections were negligible if you had >5 hosts. We'd also need to keep a copy of the host vector in each worker thread to do the fisher-yates shuffle, so the memory footprint was non-trivial.

**Comment by AdiJohn** [comment]
I see. Thanks for the explanation.
