### ISSUE TITLE
How to tunneling raw tcp over websocket, any example?

### ISSUE THREAD

**Issue by wuhuizuo** [envoyproxy/envoy#14860]
*Title*: *How to tunneling raw tcp over websocket, any example?*

*Description*:

Some gw in product will disable connect method for private tcp proxy service for security. websocket is ok.
gw will refuse http connect method using [tcp-over-http](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades.html?highlight=upgrade_type#tunneling-tcp-over-http)
how to tunnel tcp(socket servie, like android debug bridge service) over websocket with envoy, any examples?

**Comment by phlax** [comment]
hi @wuhuizuo there are some example configurations in the websockets sandbox here:

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket

not sure if i understand the question exactly but there is an example of `tcp` proxying a web socket without termination included here:

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket#step-5-test-proxying-wss-passthrough

**Comment by wlhee** [comment]
https://github.com/envoyproxy/envoy/pull/14552 might help. It supports TCP over HTTP POST.

**Comment by wuhuizuo** [comment]
> hi @wuhuizuo there are some example configurations in the websockets sandbox here:
> 
> https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket
>
> not sure if i understand the question exactly but there is an example of `tcp` proxying a web socket, without termination, included here:
> 
> https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket#step-5-test-proxying-wss-passthrough

thanks for your reply, but I need an example of tcp tunneling with websocket prototol. not proxy websocket service with tcp proxy。 

wlhee's [comment](https://github.com/envoyproxy/envoy/issues/14860#issuecomment-770137967) may be closed.

**Comment by phlax** [comment]
@wuhuizuo if you have resolved your issue, could you close this ticket

**Comment by wuhuizuo** [comment]
> @wuhuizuo if you have resolved your issue, could you close this ticket

ok.

**Comment by wuhuizuo** [comment]
tunneling by HTTP POST is blocked by my company's firewall. The request is chunked-encoded, the the firewall buffer the request, and then timeouted for waitting the rest request fragments.

I have no right to setting the firewall.
kubectl is using websocket to portward pod or service's tcp port, and kubectl port-forward is allowed.

I think i need reopen the issue, maybe this issue should be treated as a feature requirement.
@phlax

**Comment by phlax** [comment]
@alyssawilk do you know if Envoy can support this ?

**Comment by alyssawilk** [comment]
The last folks who ran into issues with CONNECT being unsupported added POST tunneling which is another option you might consider.
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades

Envoy doesn't currently allow upgrades from raw TCP to websocket, though it could be implemented fairly easily as another option on the CONNECT path, especially if you crib off of the PR which went from CONNECT-only to CONNECT-or-POST.

**Comment by wuhuizuo** [comment]
@alyssawilk I have tried, it used empty http chunked body to establish the tunnel connect, firewall will failed with timeout.The firewall want to buffer the full request body.

**Comment by lambdai** [comment]
I am wondering if the grpc streaming request is able to go through the firewall at your side. The underlying of grpc request is also POST method.

If grpc request is allowed, you should be able to borrow something from grpc request
