### ISSUE TITLE
Reloading dynamic configuration(LDS and CDS) from files not at the same time

### ISSUE THREAD

**Issue by defool** [envoyproxy/envoy#14876]
*Title*: *Reloading dynamic configuration from files not at the same time*

*Description*:
>In this example(https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem), 
if the cluster name changed  in `cds.yaml` and `lds.yaml` at the same time,  envoy may returns 503 response. 

*Repro steps*:
> Change  the cluster name  in `cds.yaml` and `lds.yaml` at the same time.

**Comment by mattklein123** [comment]
This is by design given Envoy's eventually consistent configuration model. Generally your control plane would want to sequence updates to avoid this (potentially using ADS).

**Comment by defool** [comment]
Thanks, ADS is what I need.
