### ISSUE TITLE
wasm-cc example uses all available disk space on CI

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#14874]
We need to figure out what to do:

1. Run CI with more disk space
2. Reduce disk requirements by wasm-cc example
3. Free up disk space by deleting artifacts from previous steps. 

For step 3 @phlax has suggested to delete `envoy-docker-images.tar.xz`

**Comment by yanavlasov** [comment]
@PiotrSikora for visibility

**Comment by phlax** [comment]
> Reduce disk requirements by wasm-cc example

this is difficult to do without a) reducing size of build image, or b) using a custom image with bazel and requirements

> Free up disk space by deleting artifacts from previous steps.

the `envoy-docker-images.tar.xz` is pretty large so we could do one/some/all of:

- only put the required docker image into the xz for this step
- delete the xz after loading
- remove any unneccessary docker images after loading

if this doesnt free up enough space a more drastic move would be to have an env var on the `verify.sh` scripts that flags images to clean up after use (at least in CI)

the other option, and one that i think is probably worth considering, is to have 2 parallel jobs running the verify scripts

the first could run the sandbox/es requiring the build image - currently only the wasm example

the second could run all the rest

this would be quicker on ci although obv use more resources, it would also mean that we could potentially add more compile type examples that use the build image without breaking ci further

**Comment by phlax** [comment]
@yanavlasov @lizan if there is any consensus on the above approaches i can PR, im towards the option to separate verify runs, but happy to implement another solution if its helpful

**Comment by yanavlasov** [comment]
I'm ok with breaking it up into separate runs. However I think the run with build images would still have same disk space issue right? We will probably need to do the steps you propose above, i.e. delete the archive file, and images that are not going to be used.

**Comment by phlax** [comment]
@yanavlasov  have raised a PR to separate the wasm test run

im not sure if deleting the tarball etc is necessary at this stage.

the relevant `df` before/after the main test run:

``` console
/dev/sda1        84G   65G   19G  78% /
/dev/sda1        84G   78G  5.7G  94% /
```

and for the wasm/compiler run

```
/dev/sda1        84G   65G   19G  78% /
/dev/sda1        84G   75G  8.3G  91% /
```

also, if diskspace becomes an issue again, im thinking the better solution  is to reduce the originally created tarball as that has the added bonus of reducing up/download times too
