### ISSUE TITLE
understanding migrating from nginx to envoy

### ISSUE THREAD

**Issue by dogecoin2018** [envoyproxy/envoy#14871]
Guys, I am new in envoy and I just knew it today. 

I wanted to migrate my nginx server to envoy.. But couldn't find any resources on using PHP (app like wordpress) and how "location directive" and "web root" from nginx works in envoy (opening files like css, images, etc). Or do i need an app to run these? Also, I don't want to use laravel to run php.

Is envoy a fully proxy? I wanted to know if these Nginx conf is also available or equivalent in envoy:

```
root /var/www/web_folder;

location{
  try_files $uri $uri/ /index.php?q=$uri&$args;
}
```

```
location ~ \.php${
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  try_files $fastcgi_script_name =404;
  set $path_info $fastcgi_path_info;
  fastcgi_param PATH_INFO $path_info;
  
  fastcgi_index index.php;
  
  fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
  fastcgi_read_timeout 300;
}
```

If not available, what are the best tool to run php with wordpress on envoy?

Really sorry about this question.

**Comment by ggreenway** [comment]
Envoy does not function as a general-purpose webserver, so there is no direct equivalent for either CGI or  a www root.
