### ISSUE TITLE
Passing dynamic state from a filter extension to a cluster extension for use in chooseHost

### ISSUE THREAD

**Issue by cretz** [envoyproxy/envoy#14897]
*Title*: Passing dynamic state from a filter extension to a cluster extension for use in chooseHost

*Description*:

Opening issue per Slack convo. Problems with options today:

* [State on http conn stream info](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters) - you don't have access to the http connection manager stream info in the load balancer context
* Dynamic state on connection stream info at the connection level - only have access connection as const in filter, so can't set state
* [Route metadata criteria](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets#example-route-with-metadata-criteria) - Can set arbitrary metadata under `envoy.lb` at config time which is nice and solves most use cases, but not quite as dynamic as we may need
* `LoadBalancerContext::downstreamHeaders` - eww
* Use a singleton - This is what dynamic forward proxy does for DNS cache, but not a good general purpose approach

Open to any suggestions.

**Comment by snowp** [comment]
I could imagine being able to set a generic object on the LB context that could be downcast to an extension specific type for use in a custom cluster, though there might be a better way to do this depending on the specific use cases. Is your use case not well handled by setting metadata criteria? If not, could you elaborate on the use case?

cc @htuch since this is somewhat related to extensible load balancing

**Comment by cretz** [comment]
I think it is mostly well handled by setting the metadata criteria (especially since we'll update it via VHDS on alterations as we need it). I would prefer a typed approach (similar to FilterState) over proto WKT structs, but it's not a big deal.

Now that I think about it, I can't think of a use case, since I have the headers and downstream connection available to me, where I couldn't handle my dynamic upstream selection with that info + fixed metadata criteria. We have cases where one may have a different upstream based on client, request domain/url/header/query/etc...but I have that info available. So really, the route metadata criteria may be enough for our use case presently.
