### ISSUE TITLE
Envoy adds content-length header to HTTP/1.1 GET/HEAD/DELETE/TRACE requests

### ISSUE THREAD

**Issue by chradcliffe** [envoyproxy/envoy#14890]
*Description*:
Envoy adds a `Content-Length: 0` header to HTTP/1.1 requests whose original downstream headers do not specify a `Content-Length` header and whose method does not define semantics for request bodies (confirmed with GET/HEAD, probably also DELETE/TRACE).

According to [RFC7230](https://tools.ietf.org/html/rfc7230):
> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body.

In the descriptions of methods in [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3), GET, HEAD, DELETE, TRACE, and CONNECT do not have defined semantics for request bodies. While the current behaviour is _technically_ valid for these methods, it's not the recommended behaviour.

*Edit*: I have observed the current behaviour causing breakage for upstream servers that are either too pedantic or are broken in the presence of `content-length` for GET requests.

However, I'm sure we'll break other traffic if we choose not to include the `content-length` header. I think the best approach to avoid breaking the most traffic is to preserve the presence/absence of a `content-length` header from the upstream to downstream (and vice-versa on the response path if applicable).

I wasn't able to find any specific discussion of this issue in the past, however it appears that the inclusion of `content-length` is a deliberate decision taken with some thought, so I'm sure there are/were very good reasons for the current behaviour. It's also not very clear to me how we would go about fixing this issue, so hopefully there is someone who can give some guidance/suggestions if this is something the community would like to see fixed.

*Repro steps*:
Send a GET/HEAD request without a `content-length` through Envoy, observe that the upstream headers have a `content-length: 0` header set.

*Admin and Stats Output*: N/A

*Config*: N/A

*Logs*: N/A

*Call Stack*: N/A

**Comment by ggreenway** [comment]
cc @alyssawilk

**Comment by mattklein123** [comment]
For historical context, when I originally wrote Envoy I decided to adhere to the new-style RFC guidelines which remove most/all of the historical per-method differences in handling. This is why we allow GET with bodies, for example. This is all technically allowed by the RFC.

The reality is every time we change anything in this area a ton of stuff breaks and it's super painful. At this point I don't think we can change this and I don't think it's worth it. However, I would be fine with configuration options that allow altering the message semantics. I'm sure @alyssawilk has other thoughts.

**Comment by chradcliffe** [comment]
I updated the description to clarify that adding headers can break some poorly-written upstreams that don't expect content-length for GET requests (fwiw).

**Comment by alyssawilk** [comment]
@mattklein123 given Envoy will add back C-L: 0 for "bodyless" methods, what would you think of a runtime-guarded option to remove C-L:0 as we encode headers to the codecs?  It shouldn't cause problems insofar I think servers must interpret "bodyless" headers as having no body, and if the next server is Envoy it'll cheerfully add them right back.  Unless of course your newfangled endpoints behind Envoy now expect C-L to always be present?

I'd like us moving towards well documented and at least configurable handling of "bodyless" requests with bodies, probably a permanent config knob to reject said requests which starts false and transitions true.  That way folks who want it can retain it, but we close off yet another common smuggling vector for folks with naive and standards compliant upstreams.

**Comment by mattklein123** [comment]
> @mattklein123 given Envoy will add back C-L: 0 for "bodyless" methods, what would you think of a runtime-guarded option to remove C-L:0 as we encode headers to the codecs? It shouldn't cause problems insofar I think servers must interpret "bodyless" headers as having no body, and if the next server is Envoy it'll cheerfully add them right back. Unless of course your newfangled endpoints behind Envoy now expect C-L to always be present?

Spec-wise I agree it should be fine, but I'm super twitchy about changes like this since every time we make them it breaks someone, and our usage is orders of magnitude larger than when I think we made another change like this. This one in particular seems benign enough to try with runtime, so will defer to your judgement on that.

> I'd like us moving towards well documented and at least configurable handling of "bodyless" requests with bodies, probably a permanent config knob to reject said requests which starts false and transitions true. That way folks who want it can retain it, but we close off yet another common smuggling vector for folks with naive and standards compliant upstreams.

Did you mean *not* standards compliant? I believe the behavior we have today is standards compliant technically. In terms of config knob, absolutely yes that sounds great. In terms of changing the default, again, I would be pretty twitchy because I think we will break someone. Even with runtime reversion these things can be pretty painful to debug.

**Comment by noahziheng** [comment]
I had a similar problem when I was creating a spider. A few DDosS/WAF Provider and historical website(especailly made by ASP.NET) can't handle the GET request with Content-Length: 0.
I think envoy NEED a config knob for us who make request to old-school service(ex. spider to some old .gov website).We need use Istio to manage exgress by envoy but transparent please. @mattklein123 
Same issue at Istio: https://github.com/istio/istio/issues/30146

**Comment by roelfdutoit** [comment]
Public example of a site that breaks with `C-L:0`:  https://cr.yp.to (the guy that invented x25519)
His server rejects all requests with `C-L:0` and sends back the following reply:
```
HTTP/1.1 501 I do not accept messages
Server: publicfile
Date: Wed, 17 Feb 2021 19:43:52 GMT
Content-Length: 52
Connection: close
Content-Type: text/html

<html><body>I do not accept messages</body></html>
closed
```

**Comment by alyssawilk** [comment]
OK, this is in, but default off behind the guard "envoy.reloadable_features.dont_add_content_length_for_bodiless_requests"

Would someone encountering this problem be willing to canary and make sure it works well for you?

**Comment by chradcliffe** [comment]
I can take a look at this tomorrow. We have a reliable test case for this.

**Comment by chradcliffe** [comment]
Looks good to me! All the plumbing appears to be in place and with the runtime flag enable there's no C-L:0 field emitted for the site that we were having trouble with. Thanks!
