### ISSUE TITLE
GRPC JSON TRANSCODER can't generate correct pb file with other proto plugin

### ISSUE THREAD

**Issue by Luciferre** [envoyproxy/envoy#14901]
*Title*: *GRPC JSON TRANSCODER can't generate correct pb file with other proto plugin*

*Description*:
We have a private proto plugin to generate grpc related code. It also needs to add an option code block inside the service rpc block, for example:

```
  rpc isXXXEnabled(XXXProto) returns (XXXOutProto) {
    option (google.api.http) = {
      post: "/isenabled"
      body: "*"
    };

    // private plugin option
    option (.xxx.grpc_method) = {
       name: "XXXAction"
     package: "xxx.actions"
   };
  }
```

Then I used protoc command to generate proto descriptor file and deployed to envoy, but envoy logs has error :" Could not find xxx service in proto descriptor file".
But if I removed the option (.xxx.grpc_method) block, the envoy can be deployed successfully. 

This seems like a bug for me. It would be great if it could be fixed, otherwise I need to remove every plugin option in order to generate the correct pb file everytime. 

*Repro steps*:
GrpcVersion=1.29.0
envoy version = v1.17.0

**Comment by ggreenway** [comment]
@lizan or @htuch can you comment on this?

**Comment by qiwzhang** [comment]
Based on grpc transcoding [code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L124) , most likely your custom plugin caused wrong format of proto descriptor file. 

You can copy these code to form a standalone to parse your generated descriptor file to debug it.
