### ISSUE TITLE
VHDS continues to fail after invalid resource

### ISSUE THREAD

**Issue by cretz** [envoyproxy/envoy#14918]
*Title*: VHDS continues to fail after invalid resource

*Description*:

When sending a virtual host from my control plane to Envoy (I push, I don't have the on-demand filter enabled), if I give it a resource w/ a domain that's already in use, I get:

> Only unique values for domains are permitted. Duplicate entry of domain X in route Y

Then, for every "response" I push after that w/ new vhost info (i.e. completely unrelated to the one pushed), I get that same error. Essentially pushing one bad virtual host basically makes the stream send the same error back all the time.

*Repro steps*:

Send vhost w/ duplicate domain of one sent before over VHDS. Accept error. Try to send any other VHost and same error is sent back every time. If I get to tackling this one, I'll make an integration test.

I can provide more info if needed, I am using 1.17.0. I have already worked around it by disallowing dupes from my control plane, I only open this issue out of fear for the next invalid config that may make the VHDS stream return continuous errors.

**Comment by mattklein123** [comment]
Cc @dmitri-d @adisuissa @htuch

**Comment by htuch** [comment]
I think this somewhat overlaps with https://github.com/envoyproxy/envoy/issues/14847; while we could fix the problem in VHDS, really we should have the gRPC mux reject duplicates much earlier. This only happens with SotW updates I'm guessing and not delta. This is another reason we will be in a much better state when `[New]GrpcMuxImpl` converge. We can fix for now with a small change to `GrpcMuxImpl`.

**Comment by dmitri-d** [comment]
I'll take a look.

**Comment by dmitri-d** [comment]
It's a legit issue due to how vhds computes RouteConfiguration after an update. I have a fix, but need to clean it up.

**Comment by htuch** [comment]
@dmitri-d is it possible to fix (at least for duplicates) in `GrpcMuxImpl`? That way we also solve #14847 and other resource types that might not have the correct behavior for duplicate resources. Or, are there other possible resource failures that are VHDS specific here and need resolving on the router side?

**Comment by dmitri-d** [comment]
> Or, are there other possible resource failures that are VHDS specific here and need resolving on the router side?

Yep, this is exactly it, an exception is being thrown during `RouteMatcher` instantiation due to presence of duplicate domain names. I don't think I need to make changes on the router side though, I changed when `ConfigImpl` is instantiated (and therefore validated).

**Comment by htuch** [comment]
Why can't we avoid the duplicate domain name by catching the duplicate at the `GrpcMuxImpl` level?

**Comment by dmitri-d** [comment]
It's not just duplicate names though -- I took a quick look, there are a few exceptions that can be thrown during `ConfigImpl` instantiation, all due to invalid configuration (`RouteMatcher` ctor throws exceptions on multiple wildcard domains and duplicate domain names. `VirtualHostImpl` ctor also can throw an exception, as do both `HeaderParser::configure` calls. I'd need to duplicate the validation for those, and then it will need to be kept in sync.

**Comment by htuch** [comment]
I see, makes sense to ensure we can handle this gracefully in VHDS then.
