### ISSUE TITLE
Forward Connection:Close header to downstream

### ISSUE THREAD

**Issue by madhu-shankar** [envoyproxy/envoy#14910]
*Title*: *Preserving the connection: close header after closing the connection with upstream*

*Description*:
We have a Envoy setup which is fronted by a LoadBalancer. Whenever the upstream hosts send a `Connection:close` header, Envoy closes the connection with upstream endpoint(`upstream_cx_close_notify` stat) and removes this header from the response. We want to also close the connection between the LoadBalancer and Envoy, for this we need Envoy to preserve the header in the response. I could not find any configuration which could control this behavior from the documentation. If there are any, please the share the configuration that could help us do this.

I saw [add/remove header configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v3-api-msg-config-route-v3-routeconfiguration), but with this header will be added to every response. We want to add the header based on the response from upstream, or else at fixed intervals like after every X requests.

One of the other ways we are envisioning this is to implement a network filter that will do this for us. Please guide us with the right approach for this.

[*Relevant Links*:]
>https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v3-api-msg-config-route-v3-routeconfiguration

**Comment by ggreenway** [comment]
Can you elaborate on why you want the upstream response to cause the downstream connection to close? Are you trying to ensure that the LB->Envoy connection doesn't live forever? Is there a specific failure condition you're trying to deal with?

In general, there isn't a strong relation between the upstream and downstream connection when doing HTTP proxying. The semantics of such a connection could get very confusing with HTTP/2 when there are multiple concurrent requests.

**Comment by madhu-shankar** [comment]
Yes, the intention is to not have the LB->Envoy connection live forever. We are doing migration between two type of stacks, as part of it we add and remove partitions on the LoadBalancer. While doing so, the load is not getting distributed evenly across partitions reason being that the LB->Envoy connections are living forever and the traffic keeps going to the old partitions.

In order to fix the load distribution, we have to bounce our Envoy fleet which drains the existing connections and establish new connections after restart. This takes longer time and needs manual intervention, that's why we are looking at connection reaping strategy.

**Comment by ggreenway** [comment]
Would something different, such as what's requested in #8443 (which recently had some interest), or `max_connection_duration`, be close enough? They're both ways to limit the lifetime of the downstream connection from within Envoy.

**Comment by madhu-shankar** [comment]
Yes, `max_connection_duration` and `max_requests_per_connection` are good configuration knobs that we can work with. Can you throw some light on how the connection closing works in this case? Does it use the same connection close header so that the LB can forward this header and force the client->LB connection also to be closed? as we want the whole connection chain(remote_Client -> LB -> Envoy) to be closed.

**Comment by ggreenway** [comment]
Note that `max_requests_per_connection` isn't (yet) implemented/supported for downstream connections.

For HTTP/1, Envoy will send a `Connection: close` header after `max_connection_duration` if another request comes in. If not, after some period of time, it will just close the connection.

I don't know what your downstream LB is going to do, but note that according to the spec, the `Connection` header is hop-by-hop for HTTP proxies.

**Comment by madhu-shankar** [comment]
> Note that `max_requests_per_connection` isn't (yet) implemented/supported for downstream connections.
> 
Are you considering any other type of configuration of connection termination? like closing fixed number of connections after a fixed period of time, independent of number of requests served on the connections and lifetime of the connection.
Because with `max_requests_per_connection` when the upstream cluster is heterogeneous, with hosts of different capacities, the time taken to serve the same number of requests varies from host to host which will result in connection living for longer than expected on smaller hosts, which affects the load balancing.

> For HTTP/1, Envoy will send a `Connection: close` header after `max_connection_duration` if another request comes in. If not, after some period of time, it will just close the connection.
> 
> I don't know what your downstream LB is going to do, but note that according to the spec, the `Connection` header is hop-by-hop for HTTP proxies.

Our LB can be configured to forward the `connection: close` header to the downstream. We will try out the `max_connection_duration` configuration.

**Comment by anandkumarpatel** [comment]
We are having this same issue when using istio (https://github.com/istio/istio/issues/32516). We are migrating to use istio with envoy sidecars frontend be an AWS ELB. We see that connections from ELB -> envoy stay open even when our application is sending `Connection: Close`. `max_connection_duration` works but does not seem to be the best option. Our applications are smart enough to know when they are overloaded from a client and send `Connection: Close` to shard load. 

I tried writing an envoy filter to get around this but the filter gets applied before the stripping. Did anyone discover a way to forward the connection close header?

**Comment by tsuna** [comment]
In my case we have a bug with a client app where the app leaks the connection, so we wanted to implement a server side workaround (detect the condition that triggers this bug and close the connection from the server side to avoid leaking it and keeping it open until `max_connection_duration` lapses).

**Comment by srinathrangaramanujam** [comment]
Any way to achieve this?
