### ISSUE TITLE
wasm: allow customization of prometheus namespaces

### ISSUE THREAD

**Issue by brianwolfe** [envoyproxy/envoy#14920]
*Title*: permit calling of registerPrometheusNamespace from WASM extensions

*Description*:

Currently, prometheus metrics are namespaced by envoy unless the metric prefix is explicitly registered using `registerPrometheusNamespace`. This functionality was added in https://github.com/envoyproxy/envoy/pull/11808. Making this dynamically configurable would allow us to customize the metric naming, reducing the bandwidth & CPU load for our metric processing. As described in https://github.com/istio/istio/issues/27635, we need an additional ABI call and main-thread call to adjust the set of prometheus namespaces.

Does this sound like a reasonable change to make? Are there any complications around supporting this?

@yingzhuivy

*Relevant Links*:
* Istio issue https://github.com/istio/istio/issues/27635

**Comment by ggreenway** [comment]
cc @lizan

**Comment by mathetake** [comment]
fyi: if https://github.com/envoyproxy/envoy/pull/17357 lands, we can configure prometheus stats via foreign function calls from Wasm plugins.

**Comment by mathetake** [comment]
https://github.com/envoyproxy/envoy/pull/17357 has landed, and this is all transparently to wasm users - no need to register your own prometheus namespace and instead Envoy takes care of that automatically.
