### ISSUE TITLE
Docs should be sync with latest commit

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#14937]
Docs are not rendering the latest commit from https://github.com/envoyproxy/envoy/commit/18db4c90e3295fb2c39bfc7b2ce641cfd6c3fbed

**Comment by mk46** [comment]
cc @phlax

**Comment by mattklein123** [comment]
I think the issue is the netlify config is broken from master -> main switch. I will take a look.

**Comment by mattklein123** [comment]
Fixed
