### ISSUE TITLE
Wasm: provides useful response code/flag on VM failure

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy#14947]
Currently when Wasm VM fails due to [any reasons](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/02a3ce21c8828d85063a9468e9d39dd8536a5980/include/proxy-wasm/wasm_vm.h#L134), proxy-wasm-cpp-host will close stream, which will result in empty response at Envoy. It will be more user friendly to at least populate response header and flags to indicate errors is from Wasm VM.

cc @PiotrSikora @mathetake

**Comment by PiotrSikora** [comment]
Do you mean in the access logs or as part of the HTTP response (I believe we return 503 in fail close case, correct)?

**Comment by bianpengyuan** [comment]
as part of http response. It currently returns empty response. I guess there is some parts of proxy-wasm-cpp-host and envoy that are not hooked up well, but have not yet dug deeper on this.

**Comment by PiotrSikora** [comment]
Not stale.

**Comment by PiotrSikora** [comment]
Not stale. @mathetake do you have some time to look at this?

**Comment by mathetake** [comment]
I could.. maybe next week or so.

**Comment by mathetake** [comment]
yeah, we haven't handle the failure info in Envoy but only handles it in cpp-host (except the startup time failure), so that's the reason why we don't send 503 even in the fail-close case. will work on a fix.
