### ISSUE TITLE
Add env variables to header

### ISSUE THREAD

**Issue by pantianying** [envoyproxy/envoy#14952]
Can we use environment variables in the Envoy configuration? For example, when I use istio, I currently have a requirement that the requester carry namespace information in the header. The namespace information already exists in the container's environment variable. I wish we had something like this to pass the header information.
```
          "request_headers_to_add": [
           {
            "header": {
             "key": "ns-name",
             "value": "%ENV("namespace")%
            },
            "append": false
           }
          ]
```
However, I have tried many methods now, but I can't dynamically add the data in the environment variable. Is there any other method

**Comment by antoniovicente** [comment]
cc: @envoyproxy/api-shepherds 

Where is the config in question coming from?  Is it provided by a file on disk or an ads/xds config server?

This environment expansion should arguably be expanded through some combination of code that runs during bootstrap or prior to bootstrap.  One potential proposal could involve having the proxy take a list of key-value substitutions that can be referenced in other parts of the config.  A wrapper script that kicks off the Envoy task could generation of that list from a subset of the environment and write it out to a config file that envoy loads as part of the bootstrap process.

Of course this variable expansion during config load has non trivial complexity and performance costs.

**Comment by htuch** [comment]
We actually have some support for this in tracing today (`EnvironmentCustomTag`).

I'm not against environment variable expansion as a feature in header/access logs; it's probably only used for a small set of use cases. I agree it probably makes sense to evaluate at config load rather than runtime; arguably this is no worse than other kinds of expansions we perform in our formatters.

**Comment by htuch** [comment]
This is related to https://github.com/envoyproxy/envoy/issues/12767
