### ISSUE TITLE
Make ENVOY_BUG only log critical in official debug builds

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#14957]
Given that WASM has been seeing ENVOY_BUG crashes, we should consider adding a compile time flag that makes ENVOY_BUG only log critical/increment stat and NOT abort, even in debug mode.

We may want release branches to be non-crashing in official debug releases  for the next few releases until extensions are safe and ENVOY_BUG conditions are fixed.

See https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/95

cc @PiotrSikora: If we view ENVOY_BUGs as at least as strong as ASSERTs, why shouldn't they crash in debug mode? ASSERTs are also subject to being buggy.

**Comment by PiotrSikora** [comment]
Note: it's not only Wasm but also `ext_authz` (and possibly `ext_proc`).

> cc @PiotrSikora: If we view ENVOY_BUGs as at least as strong as ASSERTs, why shouldn't they crash in debug mode? ASSERTs are also subject to being buggy.

That's a very good point. It might be that we just only to fix this single buggy `ENVOY_BUG`.

**Comment by bianpengyuan** [comment]
Can we please reopen this? Thanks!

**Comment by mattklein123** [comment]
I think per above we decided to just fix the buggy ENVOY_BUGs? Do we need to reopen this?

**Comment by PiotrSikora** [comment]
@mattklein123 yeah, but that didn't happen yet, so let's reopen until the offending `ENVOY_BUG` is fixed (see: #15496).
