### ISSUE TITLE
Is response_payload_too_large configurable?

### ISSUE THREAD

**Issue by npuichigo** [envoyproxy/envoy#14953]
I want to ask a question that whether response_payload_too_large is configurable.

The only information I found is envoy is doing non-streaming proxying and the response payload exceeded configured limits, and it till trigger a 500 error.

From the code, max payload seems to be a constant. (https://github.com/envoyproxy/envoy/blob/main/source/common/http/http2/metadata_encoder.h#L77)

**Comment by yanavlasov** [comment]
The code you are referencing is for encoding HTTP/2 METADATA frames. It is unlikely you are using this. Would you be able to describe the problem in more details and provide your Envoy configuration, please?

**Comment by alyssawilk** [comment]
response_payload_too_large is generally the details for an internally generated response when
1) the response is buffering, not streaming
2) the response exceeds the configured buffer limits
You should be able to avoid this either by not buffering the full response, or by increasing the buffer limits:
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control

**Comment by npuichigo** [comment]
@alyssawilk thx, I'll try to add per_connection_buffer_limit_size in listener, while currently I only set it in clusters.

By the way, here's the trace log before.
```
texttospeech_service_envoy.1.ic15y3e27sct@node8    | [2021-02-05 10:10:54.351][87][debug][http] [source/common/htt     p/filter_manager.cc:816] [C2][S14827961806439449665] Sending local reply with details response_payload_too_large d     irectly to the encoder
1511 texttospeech_service_envoy.1.ic15y3e27sct@node8    | [2021-02-05 10:10:54.351][87][debug][http] [source/common/htt     p/conn_manager_impl.cc:1484] [C2][S14827961806439449665] encoding headers via codec (end_stream=false):
1512 texttospeech_service_envoy.1.ic15y3e27sct@node8    | ':status', '500'
1513 texttospeech_service_envoy.1.ic15y3e27sct@node8    | 'content-length', '21'
1514 texttospeech_service_envoy.1.ic15y3e27sct@node8    | 'content-type', 'text/plain'
1515 texttospeech_service_envoy.1.ic15y3e27sct@node8    | 'date', 'Fri, 05 Feb 2021 10:10:53 GMT'
1516 texttospeech_service_envoy.1.ic15y3e27sct@node8    | 'server', 'envoy'
1517 texttospeech_service_envoy.1.ic15y3e27sct@node8    |
```
