### ISSUE TITLE
wasm: expose env variables to Wasm VMs through environ_get WASI interface

### ISSUE THREAD

**Issue by mathetake** [envoyproxy/envoy#14958]
Reading env variables from inside Wasm VMs are already defined in WASI's environ_get functions, and well supported in various compiler toolchains. However the current implementation of proxy-wasm-cpp-host and envoy does not expose any value to a VM.

There are strong demands from the community for supporting this, and it makes sense to add the new configuration in the Wasm filter's extension to control which variables should be exposed to the Wasm VM.

ref: https://github.com/proxy-wasm/spec/issues/19

**Comment by antoniovicente** [comment]
cc @PiotrSikora @lizan

**Comment by antoniovicente** [comment]
Do you have a specific proposal in mind?  cc'ing other folks involved in WASM integration.

**Comment by PiotrSikora** [comment]
This is already part of WASI spec (see discussion in proxy-wasm/spec#19). The only missing piece is Envoy implementation and exposing it in the configuration.

**Comment by antoniovicente** [comment]
What are the next steps?
- Do we need any consensus building before implementation can start?
- Is someone on the hook to do the Envoy implementation?

**Comment by PiotrSikora** [comment]
Consensus has been reached. @mathetake is already working on it https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/126.
