### ISSUE TITLE
Missing support for client certificate revocation lists

### ISSUE THREAD

**Issue by abloom-stripe** [envoyproxy/envoy#1496]
For security purposes we need the ability to revoke existing keys, preferably via CRL. There does not appear to be a field in the [`ssl_context` block](https://lyft.github.io/envoy/docs/configuration/listeners/ssl.html).

**Comment by mattklein123** [comment]
@abloom-stripe please sync up with @PiotrSikora before implementing (if you want to implement) just to make sure we don't duplicate effort. Thank you.

**Comment by mhenniges** [comment]
Hello all - Is this is issue is being worked on? Or just a proposal at the moment?

**Comment by mattklein123** [comment]
AFAIK no one is working on this. cc @PiotrSikora

**Comment by mattklein123** [comment]
This is done.
