### ISSUE TITLE
Keeping envoy build cache between reboots

### ISSUE THREAD

**Issue by alishir** [envoyproxy/envoy#14978]
*Title*: *Keeping build cache between reboots*

*Description*:
> Each time I try to build envoy after a system reboot with this command `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev' ` it starts from scratch. As you know during the build envoy creates some files in `/tmp/envoy-docker-build` and system reboot makes `/tmp/` directory clean. Is it possible to change the directory that envoy creates artifacts during build to some other directories rather than `/tmp`?

**Comment by caitong93** [comment]
You can change the directory by setting [`ENVOY_DOCKER_BUILD_DIR`](https://github.com/envoyproxy/envoy/blob/17e815122ff53d0ac6cb2d64cdbf1bfc547bb7e8/ci/README.md#on-linux) environment.
