### ISSUE TITLE
ext_authz: How to add authorization response headers to downstream response?

### ISSUE THREAD

**Issue by linarkou** [envoyproxy/envoy#14998]
*Title*: *How to add authorization response headers to downstream response?*

*Description*:
I have an external authorization service (http service) that sends some cookie in case of successful authorization. I want to send this cookie to the client (downstream). As for now I found way just to send this cookie to upstream using `http_service.authorization_response.allowed_upstream_headers_to_append` , but I need something like `allowed_downstream_headers_to_append`.
Does anyone have any ideas on how to solve this problem?

**Comment by antoniovicente** [comment]
cc @gsagula @dio

**Comment by esmet** [comment]
Hi @linarkou - this sounds a lot like https://github.com/envoyproxy/envoy/issues/7986, and there's currently a pull request in review https://github.com/envoyproxy/envoy/pull/14514. Please take a look and let me know if this is what you had in mind.

**Comment by linarkou** [comment]
@esmet yes, this is what I was looking for! Thanks a lot!
