### ISSUE TITLE
[router]: expose header modifcations protobufs to filters. 

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#15012]
*Title*: Expose header modifications to filters.

*Description*:
We have the requirement to let the filter peek into what header modifications would be done to the request/response, right now the modifications are all hidden in router which is at the end of the chain.

**Comment by antoniovicente** [comment]
What about modifications done by filters, not based on router config?

Would getting access to headers before and after modifications help?

**Comment by stevenzzzz** [comment]
we want to forward the response mod to another component to make further decisions, so we want to see the original "mods" in protobufs. 
OTOH, I'd upvote if we allow filter to do header modifications earlier than router, it'd be useful esp when filters may want to take actions on "modified" headers, right now these "mods" are not visible to filters.

**Comment by ahedberg** [comment]
> we want to forward the response mod to another component to make further decisions, so we want to see the original "mods" in protobufs.

Specifically, this separate component expects a list of headers to add and a list of headers to remove. So exposing Envoy's view of what headers would be added/removed would be optimal for us; otherwise; we'd have to construct those lists based on a diff of original headers and modified headers, and that feels error-prone.

**Comment by htuch** [comment]
I think the hacky way to do this is to look at the current `route()` from stream filter callbacks, and then `finalizeRequestHeaders()` manually from the `routeEntry()`. This is fragile; if you change filter chain ordering or clear routeCache() or modify headers later in the filter chain, things can break.

The clean way to do this would be a long term API change in which we move header add/remove to a dedicated filter. We then use per-filter configuration in `RouteConfiguration` to specify what these headers should be at different levels of granularity (route, virtual host etc). You put the header mutator before your filter. I think this is a desirable way to go as it reduces the router monolith into another filter and gives flexibility.

**Comment by ahedberg** [comment]
We could call `finalizeResponseHeaders` on the `RouteEntry` object, but we'd still have to compute the headers-to-add and headers-to-remove ourselves, which is also fragile.

I like the idea of a dedicated header modification filter. Is the idea that we can link that separate filter into our filter chain, and now we can add an API where we ask Envoy "what headers would you add to this response" and "what headers would you remove" in later filters?

**Comment by htuch** [comment]
I was thinking this filter could actually just sit before the filter that has a need to understand the added headers. Note that even this is fragile; if later filters cause a repick of route, if you make some policy decision earlier in the filter chain you would have done this with stale information. I think a robust configuration might be: `[.. some filters .., header modification filter, some filter that needs to know the finalized headers, router]` for the HTTP filter chain.

**Comment by htuch** [comment]
@ahedberg understanding the problem a bit better now (the use case is to be able to pass the header mutations on the response path to an external service at request time for later use), I think maybe just providing some way to recover these header actions would be reasonable. It's only a really valid thing when you have full knowledge that there will be no further route modifications later in the filter chain, but I think in your case this is true.
