### ISSUE TITLE
Generic Dynamic Forward Proxy with On Demand CDS

### ISSUE THREAD

**Issue by tigerlily-he** [envoyproxy/envoy#15026]
*Title*: Dynamically forward requests using Cluster / Endpoint Discovery Service (CDS/EDS) to look up endpoint addresses

*Description*:

### Desired behavior: 
We would like to have dynamic name resolution where the request is routed to an upstream cluster that is not known ahead of time. This is already possible with HTTP using DNS via the [Dynamic Forward Proxy extension](https://github.com/envoyproxy/envoy/tree/main/source/extensions/common/dynamic_forward_proxy), but we’d like to be able to hook into the existing CDS/EDS tools to resolve clusters dynamically. This would allow for a more generic dynamic proxy and facilitate the implementation of [delegation tables (dtabs)](https://twitter.github.io/finagle/guide/Names.html#interpreting-paths-with-delegation-tables). 

A secondary goal is to use this dynamic forward proxy with non-HTTP protocols such as Thrift.

### Potential Solutions:
1. Expand on the Dynamic Forward Proxy Filter: This HTTP filter rewrites the host header with the provided value before DNS lookup. We could extend this filter to connect to Endpoint Discovery Service (EDS) instead of DNS cache for destination lookup.
2.  Use the [programmatic API’s in ClusterManager](https://github.com/envoyproxy/envoy/blob/main/include/envoy/upstream/cluster_manager.h#L138-L149) to trigger Cluster Discovery Service (CDS): this looks promising but we’ll need a way to stall the request while CDS and EDS do their thing and there doesn’t appear to be a clean way to do so.
3. An even better approach we’re not aware of.

**Comment by antoniovicente** [comment]
cc @envoyproxy/api-shepherds

**Comment by antoniovicente** [comment]
cc @mattklein123 @alyssawilk

**Comment by bryce-anderson** [comment]
cc @hamdiallam @vkostyukov

**Comment by htuch** [comment]
What you describe is on-demand CDS, when you add a new on-demand CDS filter and use option (2). Some discussion at https://github.com/envoyproxy/envoy/issues/2500 but that is stale.

I think this is probably a better approach in terms of how we've been viewing incremental xDS and on-demand vs. integrating with dynamic forward. You will eventually hit a situation when you want to manage the xDS that has been lazy loaded like a cache in the dynamic forward proxy, but this is a totally different aspect of Envoy's dynamic config.

**Comment by lambdai** [comment]
Yeah, this is exactly on-demand CDS. The current status is that the XDS transport could support on-demand, however, Envoy as a CDS client doesn't know how to send an appropriate set of cluster name to CDS server. Meanwhile, an end2end on-demand CDS also need XDS server support ondemand CDS request and generate correct CDS response. A joint effort is needed.

I am experimenting a *datapath* on-demand EDS on my dev branch. AFAIK EDS is born as on-demand. However, Envoy CDSApi throws all the known cluster names to EDS server.  I am going to expose the add/remove EDS resource ability to network filters on datapath(or, worker threads). This could significantly scale the istio mesh and also any Envoy deployment in where EDS clusters configs are blindly transmitted.

 @htuch WDTY?

**Comment by mattklein123** [comment]
+1 I think this is on-demand CDS and I think we should just tackle that in a similar way to what we have done with on-demand VHDS.

**Comment by lambdai** [comment]
@mattklein123 @htuch Please take a look at #15053.

I can write a design doc describing #15053 and the follow up, including the low hanging fruit that request EDS upon the traffic on a worker thread.

**Comment by htuch** [comment]
@lambdai you might want to sync with @adisuissa who is looking at LEDS right now.

**Comment by lambdai** [comment]
Thank you @htuch I feel LEDS is a generally orthogonal appproach.
My attempt is to address whether an EDS cluster is needed at all. It's essentially only Envoy could answer.
My hunch is that LEDS addresses how to deliver the endpoints changes in within an EDS cluster, *after* Envoy request that EDS cluster name. 

Scheduling an offline chat with @adisuissa

**Comment by htuch** [comment]
@lambdai on-demand EDS has to remain purely opt-in FWIW. There are concerns around coupling data plane with control plane reliability whenever you use on-demand xDS.

**Comment by lambdai** [comment]
> @lambdai on-demand EDS has to remain purely opt-in FWIW. There are concerns around coupling data plane with control plane reliability whenever you use on-demand xDS.

Opt-in for sure. I understand the concern. Sorry I didn't make it clear. I will add the design doc before I go beyond the cluster manager API in #15053

**Comment by lambdai** [comment]
Chatted with @adisuissa We all agree LEDS and lazy-EDS are orthogonal

**Comment by tigerlily-he** [comment]
Yes, what we're looking for is on-demand CDS. From my understanding, "on-demand CDS" means that CDS only starts looking for a cluster when there is a request for that cluster.

One of our use case is delegation table. We would like to be able to specify a path (e.g. /foo/bar) on a request. That request will go to one set of endpoints when a process is running in a production setting and another set of endpoints when testing by rewriting how the path translates into to an address. In this case, on demand CDS should discover testing endpoints upon initial request for testing endpoints.

> We all agree LEDS and lazy-EDS are orthogonal

What is LEDS?

**Comment by adisuissa** [comment]
> What is LEDS?

Locality-Endpoint Discovery Service (LEDS, #10373) is a sub-EDS API to fetch the endpoints of a locality.

**Comment by lambdai** [comment]
> One of our use case is delegation table. We would like to be able to specify a path (e.g. /foo/bar) on a request. That request will go to one set of endpoints when a process is running in a production setting and another set of endpoints when testing by rewriting how the path translates into to an address. In this case, on demand CDS should discover testing endpoints upon initial request for testing endpoints.

IMHO what you describe is more like a namespace(or context maybe?) in CDS cc @htuch

**Comment by lambdai** [comment]
Since you erase EDS from title, I am creating new lazy load EDS to track the progress.

**Comment by tigerlily-he** [comment]
Sure. It's clearer to spell out the design of lazy loadable EDS cluster in a separate issue. I am interested in the design doc when you have it ready. @lambdai
