### ISSUE TITLE
Allow json output for logging (not access logs)

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#15020]
This is a recreation of https://github.com/envoyproxy/envoy/issues/13636, which was closed due to https://github.com/envoyproxy/envoy/pull/13832. While that PR got closer, it is still not possible to get full JSON log output as far as I can tell. `%_` just makes new lines escaped, but may still result in invalid JSON.

For example, with a log format of `{"level":"%l","time":"%Y-%m-%dT%T.%fZ","scope":"envoy %n","msg":"%_"}`:
I will get logs like:
`{"level":"warning","time":"2021-02-10T14:45:45.640752Z","scope":"envoy config","msg":"StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp [::1]:15012: connect: connection refused""}`

This is not valid JSON as the quotes in the message are not escaped.
cc @dio

**Comment by antoniovicente** [comment]
@howardjohn What do you see as the next steps?  Would you or someone from istio be interested in taking on this issue?

**Comment by howardjohn** [comment]
It would be great if there was some way to fully escape the message, not just newlines. Unfortunately I don't have the technical chops to make this change.

**Comment by dio** [comment]
Sorry I missed this. So we need to still do escaping, right?

**Comment by dio** [comment]
I have submitted a PR to add a new "%j" formatter to do JSON string escaping for the log message.
