### ISSUE TITLE
ExtAuthz dynamic metadata unavailable for StreamAccessLog service when DenyResponse sent

### ISSUE THREAD

**Issue by rockspore** [envoyproxy/envoy#15031]
*Description*:

This is on Envoy 1.17, which configured with an ExtAuthz service that sends the dynamic metadata for access log purpose whether the call is rejected or not.

When a call goes through and a OkResponse is sent, the dynamic metadata gets collected by the StreamAccessLog service correctly. However, when a call is rejected, the metadata is not available to the service.

Both Envoy docs and #12671 seem to imply the dynamic metadata should be available regardless. So I'd like to check and see if anyone else has had the same use case and got it to work.

**Comment by mattklein123** [comment]
cc @esmet

**Comment by erikbos** [comment]
Indeed, you're right: looks like CheckResponse.DynamicMetadata for a deny response does not yet emit the metadata. It does for an allowed request.

(tested on go-control-plane v0.9.9-0.20201210154907-fd9021fe5dad and envoy eb99bfc13150fe57405138af3a6f1751fad7d8e2/1.18.0-dev)

**Comment by dio** [comment]
@rockspore @erikbos could you help to send us the trace log? I'm looking at: `Received CheckResponse: ...`. Thank you!

**Comment by dio** [comment]
I think I found it, let me try to add a test for this.

**Comment by dio** [comment]
@rockspore @erikbos, when you have time, could you help us to validate the fix? I have it on dio123/envoy:fix-15031 (this is an ubuntu-based image). Thank you very much for your help and time!

**Comment by rockspore** [comment]
Yes I have verified that the metadata gets emitted with the fix. Thanks a lot for working on this, @dio!

Also, many thanks for confirming the issue, @erikbos!
