### ISSUE TITLE
Performance difference - Envoy front proxy - alpine linux sandbox vs ubuntu sandbox (envoy binary with debug symbols)

### ISSUE THREAD

**Issue by dakshinai** [envoyproxy/envoy#15046]
*Title*: 
Performance difference - Envoy front proxy - alpine Linux sandbox vs ubuntu sandbox (envoy binary with debug symbols)
*Description*:
We are testing the performance of envoy front proxy described - https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy

The backend service runs on alpine Linux. Our modified setup is built on Ubuntu container image that includes envoy built with debug symbols. Fortio is our HTTP client.

Alpine Linux sandbox results:
_Starting at 1000 qps with 8 thread(s) [gomax 22] for 1m0s : 7500 calls each (total 60000)
Ended after 1m0.008274322s : 43993 calls. qps=733.12
All done 43993 calls 10.899 ms avg, 733.1 qps_

Ubuntu sandbox results:
_Starting at 1000 qps with 8 thread(s) [gomax 22] for 1m0s : 7500 calls each (total 60000)
Ended after 1m0.112927366s : 24312 calls. qps=404.44
All done 24312 calls 19.765 ms avg, 404.4 qps_

Can you help clarify if the Linux stack can influence the performance or is there something we may be missing?

**Comment by petedmarsh** [comment]
Hi @dakshinai, did you ever get to the bottom of this?
