### ISSUE TITLE
api: Envoy should NACK typed_per_filter_config entries for filters that don't support override configs

### ISSUE THREAD

**Issue by markdroth** [envoyproxy/envoy#15043]
Currently, if an HTTP filter registers a given config type as its top-level config in the HCM filter list, and Envoy receives a RouteConfiguration that has a message of that config type in a `typed_per_filter_config` map, it will ignore that entry instead of NACKing the config, even though that config will never be used.  This seems like it's silently ignoring an error that could cause confusion for users, because they might think that they're overriding something that can't actually be overridden, and they're not getting any error to tell them it's not working.

I think this can probably be done by changing [`NamedHttpFilterConfigFactory::createRouteSpecificFilterConfig()`](https://github.com/envoyproxy/envoy/blob/f174fba476a921efb981e80c346faf7e6723c0c4/include/envoy/server/filter_config.h#L193) to throw an exception instead of returning null.  That way, any filter that overrides that method to actually parse the relevant config type will allow the config to be parsed, but any filter that doesn't will reject an override config.

CC @htuch

**Comment by antoniovicente** [comment]
Seems like a worthwhile improvement as it would help proxy users detect errors in the config they have written.

**Comment by htuch** [comment]
Yep, this behavior seems to only have an upside. Technically it might break existing users, it might be worth exercising caution and adding a runtime flag. I'm thinking of scenarios in which RouteConfiguration has some typed route config that is supported in Envoy vM but not in vN where N < M. Some operator has a mixed fleet of envoy vM and vN.

**Comment by soulxu** [comment]
hi, I submitted a PR to improve this, https://github.com/envoyproxy/envoy/pull/15135
