### ISSUE TITLE
Outlier detection using custom HTTP headers (for Graphql api)

### ISSUE THREAD

**Issue by skk2142** [envoyproxy/envoy#15056]
*Outlier detection for Graphql APIs*

*Description*:
GraphQL apis do not use HTTP error codes. They typically send error as a part of the JSON response (even errors throw on the server). HTTP code is always 200. This makes it hard to use envoy for outlier detection. To make outlier detection work, one can set the error code in the headers, say `graphql-status` (like `grpc-status`). Is it possible to use custom headers for outlier detection? Since Graphql is being adopted as a replacement for REST apis on the server(netflix is using [graphql federation](https://netflixtechblog.com/how-netflix-scales-its-api-with-graphql-federation-part-1-ae3557c187e2)), it might be a great use case to add this feature in envoy.

**Comment by junr03** [comment]
I need to look at the code to refresh my mind. But this is something that has been discussed in the past in the context of gRPC status. 

I could imagine how the outlier detection system could have extensions for having custom ways to detect errors. The rest of the code would work the same way in terms of eviction and inclusion.

**Comment by skk2142** [comment]
Thanks. I found this which is very relevant: https://github.com/envoyproxy/envoy/pull/7942/files

I don't code in go so I'd be hard for me to even attempt to add this feature but this would be a great feature.
