### ISSUE TITLE
Load Balancing with network redirect

### ISSUE THREAD

**Issue by bmsan** [envoyproxy/envoy#15057]
*Title*: *Configuring Load Balancing with network redirect*

*Description*:
> Is there a way to configure envoy to load balance by redirecting to one of the backends? 
> The traffic would then go directly between user <--> backend_X (backend_X was selected by envoy for redirection), without all the network traffic passing through envoy.
> Usecase : Scenarios of high throughput data traffic where the machine where envoy is hosted would become a bottleneck if all the traffic would pass through it.

In nginx there is [ngx_http_split_clients_module](http://nginx.org/en/docs/http/ngx_http_split_clients_module.html)

```
split_clients "${remote_addr}" $destination {
  40%   server1:port1;
  30%   server2:port2
  20%   server3:port3;
  10%   server4:port4
}

server {
  listen       myport;
  location /  {
    return 302 http://$destination$request_uri;
  } 
}
```

**Comment by lambdai** [comment]
Can you clarify? This nginx config doesn't seem to bypass nginx. In theory, you cannot because "http request lb" and "bypass HTTP proxy" is contradicting. A L7 proxy cannot determine the http request/response boundary if the byte stream is not parsed by http proxy.

**Comment by bmsan** [comment]
I will try to describe the behavoir I would like to obtain.
We have N identical servers, which should handle data from the users.
When an user contacts my_domain.com I would like the entity behind my_domain.com(could that be envoy?) to select one of the N servers and issue a redirect to the user (you contacted my_domain.com but you should contact serverK). 
The user would get redirected and it would see serverK instead of my_domain.com in the address bar.
After the redirect the redirecting entity wouldn't be involved at all in the communication between the user and serverK.

**Comment by bmsan** [comment]
One more thing to point out in my nginx example, the bypassing nginx and creating a direct connection user<-->backend is done by returning http [code 302](https://en.wikipedia.org/wiki/HTTP_302)

**Comment by mattklein123** [comment]
We don't support anything like this today, though I suppose it could be relatively easily implemented with an HTTP upstream plugin that just returns a redirect? cc @alyssawilk

**Comment by lambdai** [comment]
Aha, I misinterpreted the requirement. I thought you are asking for LVS on HTTP + DSR.

Looks like envoy acts as a dynamic content server. The future http upstream may cover this as Matt mentioned.

It's also possible to intercept the upstream request by a new cluster upstream extension. When your self-defined `HttpConnPool` is touched, a backend host is already selected by lb defined in cluster.
See the host info fetched by the HttpConnPool [here](https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/test/integration/upstreams/per_host_upstream_config.h#L71-L88). You HttpConnPool can respond 302 using the host info.

It's not a trivial approach though but this is the most reasonable one in my head
