### ISSUE TITLE
Enable jwt_claims to header for jwt_based routing

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#15062]
*Add the ability to copy jwt_claims to headers to enable jwt_based routing*

*Description*:
[jwt_authn_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter)
validates jwt tokens and rejects a token if it is invalid. May times we want to route a request at ingress based on the jwt-token presented. For example a claim me be related to `canary` in which case the user should be routed to the canary backend.

At present this can be done using Lua or a Wasm filter, however this is an often requested feature and makes sense for it to be directly supported.

Options

**A: jwt_authn_filter configuration**
1. Add `action` configuration to the `jwt_authn_filter`, which will copy claims to a header.
2. Ensure that the target header is sanitized.
3. Relies on RBAC to happen afterwards
4. flush route to generate new route.

**B: support jwt-match in http routes**
1. Add nested jwt claims as route matches.
2. The match will be done on `unvalidated` claims, which is fine since it will be rejected by jwt later anyway.
3. This saves us from flushing routes. It makes it equivalent to a client that *also* populates the said header along with sending the jwt token.

@yangminzhu @kyessenov

**Comment by qiwzhang** [comment]
For A:  we just add following into JwtProvider:
```
message PayloadToHeader {
   // it is the path in payload json, such as "a.c"
   string payload_path = 1;

   // the header key
   string header_key = 2;
};

repeated PayloadToHeader payload_to_headers = 13;

bool clear_route_cache = 14;

```

**Comment by yangminzhu** [comment]
for A, after the jwt filter clear the route cache, will the request go through the same filter chain again? If so how does the jwt filter know if should not clear the cache again?

for B, the routing part probably still need to validate the token to some extent, sometimes a path is excluded from the JWT so the jwt filter might be configured to bypass validation of it, in that case, the routing should not use any information from the token.

or maybe `C: add a metadata_to_header filter`, the metadata will only be populated after validation and the filter will be a bit more general, but this has the same drawback for flushing routing.

**Comment by mandarjog** [comment]
@yangminzhu if you believe “B” is equivalent to a client also populating the header then there is no validation needed during routing. If a route is not protected then it does not need a validated token. Can you help me understand the failure case?

**Comment by qiwzhang** [comment]
@yangminzhu clear_route_cache will not cause request to re-pass filter chain.

**Comment by qiwzhang** [comment]
I like your `C:  add a metadata_to_header filter`.  So not to put too much specialize code  into jwt_authn.

**Comment by yangminzhu** [comment]
> @yangminzhu if you believe “B” is equivalent to a client also populating the header then there is no validation needed during routing. If a route is not protected then it does not need a validated token. Can you help me understand the failure case?

I was actually thinking the opposite, the use case of routing based on the jwt token that cannot be faked by client side: the routing part checks the token and makes the decision without even validating the token as it relies on the later jwt_authn filter for the validation. Later the jwt_authn filter also bypassed the validation for some reasons (e.g. path is excluded from validation). That's why I mean the routing part should still validate the token to prevent such cases.

If the path excluded from the routing is consisting with the routing, i.e. it is also excluded from the routing, then I guess this is not a big issue because it will not be routed anyway? 

Or if you are thinking the use case of routing based on header that could be freely configured by the client, then yes I think this is not an issue. But I'm not sure if that is the use case here? I thought the reason of using JWT token is to prevent such cases.

**Comment by mandarjog** [comment]
normally we keep routing, authentication and authorization separate. The client and route is free to request anything they want. Jwt validation filter should be inserted if we want that resource to be protected, and jwt to be validated.

I see your point from an API / user experience standpoint, but XDS api need not be user friendly. we will surely tie it together in the Istio API.

we can leave it to envoy api shepherds if they are ok with including jwt validation config embedded in the route.

**Comment by mandarjog** [comment]
We still do need this. Someone from Google will work on it.
