### ISSUE TITLE
benchmark: expose google benchmark's intrinsic command-line options

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#15076]
*Description*:
>Currently we populate a `TCLAP` command-line parser with a few options, and use the `TCLAP` infrastructure to parse the command line early in test/benchmark/main.cc. There are actually a number of google-benchmark options that may be useful, such as `--benchmark_report_aggregates_only --benchmark_repetitions=10`. See https://android.googlesource.com/platform/external/google-benchmark/+show/refs/heads/master/README.md for details. However, they are not accessible because `TCLAP` errors out on any command-line options it doesn't recognize.

I think it is sufficient to move the call to `::benchmark::Initialize(&argc, argv);` to the first line of `main()` and then both the Google Benchmark options will be supported, and also the new custom option "skip_expensive_benchmarks". If you do that, then you get this with "benchmark --help":
```
benchmark [--benchmark_list_tests={true|false}]
          [--benchmark_filter=<regex>]
          [--benchmark_min_time=<min_time>]
          [--benchmark_repetitions=<num_repetitions>]
          [--benchmark_report_aggregates_only={true|false}]
          [--benchmark_display_aggregates_only={true|false}]
          [--benchmark_format=<console|json|csv>]
          [--benchmark_out=<filename>]
          [--benchmark_out_format=<json|console|csv>]
          [--benchmark_color={auto|true|false}]
          [--benchmark_counters_tabular={true|false}]
          [--v=<verbosity>]
```
So in that case you don't get the help for --skip_expensive_benchmarks. I think it will still work though. An alternative would be to use the absl mechanism for declaring a command-line flag for skip_expensive_benchmarks rather than TCLAP, and then I think "--help" will give you the integrated view.

So there's a few things to sort out here. I think this would be easy to do.

**Comment by Razdeep** [comment]
@jmarantz I would like to work on this issue.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/15133

**Comment by jmarantz** [comment]
This is a great improvement but I don't think it's ideal.

I think "--help" should give you both skip_expensive_benchmarks *and* the google benchmark options. Otherwise they are hard to discover. The checked in fix makes all the options work (yay!) but only shows help for skip_expensive_benchmarks.

IMO the best solution (as described above) is to use the absl command-line flags for everything, then hopefully `--help` will just work.
