### ISSUE TITLE
upstream connect error or disconnect when trying to configure front proxy

### ISSUE THREAD

**Issue by ahaw** [envoyproxy/envoy#15079]
*Title*: *upstream connect error or disconnect when trying to configure front proxy*

*Description*:
>When trying to connect I'm getting error:
curl -v localhost:8080/service/1
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /service/1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Wed, 17 Feb 2021 19:17:57 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failurea

*Repro steps*:
Follow steps from: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
All configs are copypasted from https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy

*Logs*:
There is nothing showing when executing curl trying to connect

**Comment by mk46** [comment]
It seems that the service container doesn't start or not running. Could you please check `docker-compose ps`?

**Comment by ahaw** [comment]
Ive mixed two configurations, and the expecting service was not listening
