### ISSUE TITLE
Problems with Discovery Response in lds

### ISSUE THREAD

**Issue by bgc8214** [envoyproxy/envoy#15084]
I'm setting up a lot of xds, using an envoy for the first time.
I think eds and cds are pretty good, but I want to ask you a question because lds is not working well.
<pre>
<code>
dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: REST
      refresh_delay: 15s
      transport_api_version: V3
      cluster_names: [ config-server ]

static_resources:
  clusters:
    - name: config-server
      connect_timeout: 30s
      type: STATIC
      load_assignment:
        cluster_name: config-server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1 # simple webserver sits here
                      port_value: 8080
</code>
</pre>
This is the setup in envoy.yaml.

<pre>
<code>
{
  "name": "listener_0",
  "address": {
    "socket_address": {
      "address": "0.0.0.0",
      "port_value": 10000
    }
  },
  "filter_chains": [
    {
      "filters": [
        {
          "name": "envoy.http_connection_manager",
          "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
            "stat_prefix": "ingress_http",
            "route_config": {
              "name": "local_route",
              "virtual_hosts": [
                {
                  "name": "local_service",
                  "domains": [
                    "*"
                  ],
                  "routes": [
                    {
                      "match": {
                        "prefix": "/test"
                      },
                      "route": {
                        "cluster": "test",
                        "prefix_rewrite": "/"
                      }
                    }
                  ]
                }
              ]
            },
            "http_filters": [
              {
                "name": "envoy.router"
              }
            ]
          }
        }
      ]
    }
  ]
}

</code>
</pre>

This is json who responds to requests from /v3/discovery:listeners.

But the error keeps coming out as shown below.

[2021-02-18 07:29:00.026][49426113][warning][config] [source/common/protobuf/message_validator_impl.cc:43] Unknown field: type envoy.service.discovery.v3.DiscoveryResponse reason INVALID_ARGUMENT:filter_chains: Cannot find field.

I can't find what it is even if I keep trying to get it wrong on the filter chain.

Can you tell me what's wrong? Or maybe you could give me another example file.

And what can we do if we add rds here?

**Comment by lambdai** [comment]
I use your posted listener config. It's legit.

I doubt if you encoded the DiscoveryResponse from the wrong source. See https://github.com/envoyproxy/envoy/blob/0ba9e045147af4b6a265d6d09b0eabb896b6426f/test/integration/listener_lds_integration_test.cc#L152-L162

From high level, 
1. the above json should be transformed into a `envoy::config::listener::v3::Listener` typed `listener` 
2. response.add_resources()->PackFrom(`listener`)
3. encode the response into grpc response
