### ISSUE TITLE
Docker build aborts early if BAZEL_BUILD_EXTRA_OPTIONS contains a space

### ISSUE THREAD

**Issue by dankegel** [envoyproxy/envoy#15080]
With envoy from git ( a96ebf4a9b4dae50c17469c64b179930e57c802e ) on ubuntu 18.04,
the command
```
./ci/run_envoy_docker.sh "BAZEL_BUILD_EXTRA_OPTIONS='--define wasm=wasmtime' ci/do_ci.sh bazel.dev"
```
aborts instantly, but using the alternate syntax
```
./ci/run_envoy_docker.sh "BAZEL_BUILD_EXTRA_OPTIONS='--define=wasm=wasmtime' ci/do_ci.sh bazel.dev"
```
seems to start off nicely.

It doesn't matter what option you pass, all that matters is the embedded space.  So
```
./ci/run_envoy_docker.sh "BAZEL_BUILD_EXTRA_OPTIONS='--local_ram_resources=6000 --local_cpu_resources=6' ci/do_ci.sh bazel.dev"
```
also aborts instantly.

Adding 'bash -x' to the front shows that the last line run is 
```
  docker run ... /bin/bash -lc 'groupadd --gid 1000 -f envoygroup     && useradd -o --uid 1000 --gid 1000 --no-create-home --home-dir /build envoybuild     && usermod -a -G pcap envoybuild     && chown envoybuild:envoygroup /build     && sudo -EHs -u envoybuild bash -c '\''cd /source && BAZEL_BUILD_EXTRA_OPTIONS='\''--local_ram_resources=6000 --local_cpu_resources=6'\'' ci/do_ci.sh bazel.dev'\'''
```
so perhaps we're in the 7th circle of quoting hell :-)

**Comment by dankegel** [comment]
In the unlikely event anyone needs a quick hack workaround, I just hardcoded build options in build_setup.sh, e.g.
```
--- a/ci/build_setup.sh
+++ b/ci/build_setup.sh
@@ -99,6 +99,7 @@ BAZEL_BUILD_OPTIONS=(
   "--test_output=errors"
   "--repository_cache=${BUILD_DIR}/repository_cache"
   "--experimental_repository_cache_hardlinks"
+  "--local_cpu_resources=8"
   "${BAZEL_BUILD_EXTRA_OPTIONS[@]}"
   "${BAZEL_EXTRA_TEST_OPTIONS[@]}")
```

**Comment by phlax** [comment]
> so perhaps we're in the 7th circle of quoting hell :-)

eek!

i can have a look at what is happening with this var as it is passed through

**Comment by phlax** [comment]
after experimenting with this a little, it seems like the problem comes from which way round the `'` and `"` are used

@dankegel 

if above is correct, the following should work:

```
./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define wasm=wasmtime" ci/do_ci.sh bazel.dev'
```

can you confirm ?

if so, im wondering if we need to highlight the point somewhere
