### ISSUE TITLE
Missing transport_api_version in rate limiting leads to crash

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#15083]
*Title*: Old envoyproxy/ratelimit leads to crash
*Description*:
Forwarding an issue from our repo: https://github.com/istio/istio/issues/30900

Basically, it sounds like when missing `transport_api_version` in the rate limiting config, we get a crash

Expected behavior is some more graceful failure, probably a NACK

*Repro steps*:
See https://github.com/istio/istio/issues/30900. I did not reproduce myself, just forwarding this

**Comment by mattklein123** [comment]
cc @htuch @adisuissa this is the same issue that keeps getting reported over in the ratelimit repo, so it seems like something is broken?

**Comment by htuch** [comment]
@howardjohn does this reproduce on `main`? I was previously unable to repro with the example from the ratelimit repo.

**Comment by howardjohn** [comment]
I am not too familiar with this, just copied over from the Istio repo, but I did try their config on main and it didn't crash. I wasn't sure if this was because it's fixed or because it requires a request or something - I didn't set up the full rate limit service.
