### ISSUE TITLE
EXPECT_ENVOY_BUG testing in debug mode uses EXPECT_DEBUG_DEATH, leads to flakiness in test coverage reports

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#15092]
EXPECT_ENVOY_BUG provides a good decent way to provide test coverage for ENVOY_BUG but there is some room for improvement. Use of EXPECT_DEBUG_DEATH prevents us from properly verifying that the code following the ENVOY_BUG will not crash even in debug mode.  Also, test coverage reports which are generated from a debug build end up being flaky due to the fork used in the implementation of the death test handler.

Should we consider some internal API that makes ENVOY_BUG non-fatal in a scope in order to make it possible to test ENVOY_BUG in debug mode without triggering the default fatal behavior?

cc @alyssawilk @asraa

**Comment by asraa** [comment]
> Also, test coverage reports which are generated from a debug build end up being flaky due to the fork used in the implementation of the death test handler.

I had no idea this would happen! EXPECT_DEBUG_DEATH I agree is messy. 

>  Use of EXPECT_DEBUG_DEATH prevents us from properly verifying that the code following the ENVOY_BUG will not crash even in debug mode. 

In debug mode we would crash at ENVOY_BUG though, so you can't really verify the code after won't crash in debug mode. If you wanted to test behavior after ENVOY_BUG in opt mode you would need to do something like
`EXPECT_ENVOY_BUG({triggerEnvoyBug(); somePostOperation();}, "envoy_bug: log message");`
which would verify that `somePostOperation()` executes in opt mode (or use #ifdef NDEBUG after)

The only thing I can think of is that we add a define to TestRunner that changes ENVOY_BUG behavior. However, that would mean that you can't reproduce a debug crash on an ENVOY_BUG (for e.g. if we find a fuzz test reproducing an ENVOY_BUG failure, then gtest that, it won't reproduce the crash)

**Comment by asraa** [comment]
I just realized that this was in the context of coverage numbers.

How about we leverage `build:coverage --define=ENVOY_CONFIG_COVERAGE=1` to make ENVOY_BUGs non-fatal in coverage mode (and match that with EXPECT_ENVOY_BUG implementation)?

**Comment by alyssawilk** [comment]
SGTM!
