### ISSUE TITLE
[Question] Thread safe way to use grpc bidi stream with envoy grpc async client inside a http filter. 

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/envoy#15095]
*Title*: *Thread safe way to use grpc bidi stream with envoy grpc async client inside a http filter.* 

*Description*:

I have written a http filter for web socket connections that is capturing websocket frames and publishing metadata related to these frames through a **grpc bidi stream with envoy grpc client**. According to the filter logic, there may be a possible race condition that will occur on `Grpc::AsyncStream stream_{};`. So the below code segment explains about the possible race condition. 

From `decodeData(Buffer::Instance& data,bool)` in my http filter, I'm calling a method in my helper class which publish metadata through a grpc bidi stream. Helper class has a pointer to `Grpc::AsyncStream stream_{};`

```c++
FilterDataStatus HttpSampleDecoderFilter::decodeData(Buffer::Instance& data, bool) {
    HelperClass::publishMetadataAsync(data);
    return FilterDataStatus::Continue;
}
```
My HelperClass implements `Grpc::AsyncStreamCallbacks` and has methods `onMessage()` and `onRemoteClose`. Also the `publishMetadataAsync` method too.

```c++
void HelperClass::publishMetaDataAsync(Buffer::Instance& data){
    stream_->sendMessage(params);
}

void HelperClass::onRemoteClose(Grpc::Status::GrpcStatus status, const std::string& message) {
    stream_ = nullptr;
    ENVOY_LOG(trace, "onRemoteClose : {} {}", status, message);
};

```
So my concern is that when `onRemoteClose()` gets called when the remote upstream gets disconnected, there maybe a possibility of calling `stream_->sendMessage(params);` at the same time.Since I assign `stream_ = nullptr` in `onRemoteClose`, calling a method on nullptr makes a segmentation fault. And I don't think a simple if condition to check `stream_!= nullptr` will work because I assume these two happen in 2 different threads. I'm not sure whether it's a good choice to use mutex to handle `stream_` in a thread safe way because envoy encourages non-blocking thread model.

So my questions are, 
1. Is my concern valid ?
2. How to handle this kind of a scenario by following envoy best practices ?

**Comment by snowp** [comment]
The threading here depends on where you're allocating the gRPC client, if it's done as part of the filter then it should end up on the same thread as the filter, so the null check should be sufficient. If you are trying to put it on another thread (e.g. the main thread) then you'd probably be posting the sends to the relevant dispatcher, which means that you'd also be okay with just a null check since the send and the remote close callback is still running on the same thread.

**Comment by NomadXD** [comment]
@snowp I'm creating a **gRPC async client for each of the filter objects** that get created. So I think just doing a nullptr check will do the job. But since you mentioned about dispatching to main thread, I'm a little bit concerned about my implementation. So basically , according to my implementation **a gRPC bidi stream will be created for each of the filter objects that gets created.** Since the lifetime of a filter object is equal to the lifetime of a web socket connection, 1000 web socket connections means 1000 bidi streams from envoy to the external grpc service. Will that be a problem in terms of envoy memory management ? 
Also I read this from envoy docs,
 
`Maximum concurrent streams allowed for peer on one HTTP/2 connection. Valid values range from 1 to 2147483647 (2^31 - 1) and defaults to 2147483647.` 
So I assumed I'm safe with having high number of concurrent streams in terms of connection management. But not sure in terms of memory management. Thanks a lot for the help.
