### ISSUE TITLE
Keeping more than 2 processes on hot-restart

### ISSUE THREAD

**Issue by svagner** [envoyproxy/envoy#15099]
*Title*: *Keeping more than 2 processes on hot-restart*

*Description*:
Currently, once we're doing hot restart we are keeping only 2 processes - parent (that will follow `parent_shutdown_time`) and child (that will accept() connection and do current work). It's happening on `shutdownAdmin` method here - https://github.com/envoyproxy/envoy/blob/7e2099ae585ba70997d59a8dfe6246b9728c1b24/source/server/server.cc#L832

Could you please explain to me what is the reason for that? Why can't we keep old processes draining connections with some processes limit? Let's say if we'd have this as result with limit 4 we'd have something like that:

parent (draining, restart_epoch 0) -> child (draining,  restart_epoch 1) -> child (draining,  restart_epoch 2) -> child (accept(),  restart_epoch 3)

Next reload:
child (draining,  restart_epoch 1) -> child (draining,  restart_epoch 2) -> child (draining,  restart_epoch 3) -> child (accept(),  restart_epoch 4)

Does this make sense?

**Comment by junr03** [comment]
Sorry, I think I am a little lost on your suggestion. What is the need of keeping more than two (draining, and active) processes alive?

**Comment by svagner** [comment]
So currently even if we have long `drain_time ` and `parent_shutdown_time` and if we do more than 1 hot restarts within `drain_time` - the parent will be killed even if it's still draining connections. That's happening because of the limitation that we have only 2 processes in time.

**Comment by svagner** [comment]
Generally what I'd like to see: 

```
parent (draining 10 sockets, restart_epoch 0) -> child (draining 5 sockets, restart_epoch 1) -> child (draining 1 sockets, restart_epoch 2) -> child (accept(), restart_epoch 4)
```

restart_epoch=3, in that case, was terminated because it finished draining of connections

**Comment by mattklein123** [comment]
FWIW, what you propose is how I implemented hot restart in "proto Envoy" (Twitter edge proxy). I did not repeat this in Envoy as in general we rarely made use of the multi-generation support since deploys are not very frequent, and I didn't think the complexity was worth it. I'm still generally of that mindset.

**Comment by lambdai** [comment]
CC @mandarjog

**Comment by lambdai** [comment]
Hotrestart is the source of complexity. I want to CC guys in my ex-team to list some bleeding SEVs wrt hotrestart.

I could imagine the immediate follow up could be 
query the last N hotrestarting instance
revert hotrestart
gracefully kill one instance in the hotrestart chain
etc

**Comment by caitong93** [comment]
>  I did not repeat this in Envoy as in general we rarely made use of the multi-generation support since deploys are not very frequent, and I didn't think the complexity was worth it. 

Agreed. As a user I have had some problems with hot restart. For example, when you have n Envoy process running at the same time, the total memory usage would be n times that of one Envoy process. If the parent is killed by OOM during the hot restart, the the child would possibly block on the `recvmsg` call. Hot restart in Envoy is not **lightweight**,  so I just avoid frequent hot restart.

**Comment by svagner** [comment]
I agree that probably it is not a problem for every envoy user. But if we're talking about wide installation in the big environment where we have separate teams who are working with envoy using any automation configuration system, the hot restart is becoming unpredictable. 

About memory: probably it's a problem for embedded devices but even on big traffic envoy consumes ~ 200Mb for a single process. Even if we assume that child will do COW for all pages it means to keep 5 children we need 1Gb. Is it big deal on the present hw? And I'm not talking that we should keep that for everyone. I'm proposing to keep it as an option. If someone is ready to pay 1gb for envoy they should be able to set more processes for hot restart.

Probably I don't know some root architecture concerns that are don't allow us to implement so. That's why I'm only asking to figure out what problems can be with that. And if community agree that we want such functionality I'm ready to contribute to it.

**Comment by mattklein123** [comment]
> Probably I don't know some root architecture concerns that are don't allow us to implement so. That's why I'm only asking to figure out what problems can be with that. And if community agree that we want such functionality I'm ready to contribute to it.

There aren't any explicit architecture concerns. It's certainly possible to implement. The question is should we? In general most sophisticated Envoy users invest in xDS, which allows reconfiguration dynamically without performing hot restart. So hot restarts are really only used for binary restarts, and then typically in non-container scheduler worlds. I personally don't think it's worth it to implement this given the (IMO) limited usefulness of the feature for the larger community.
