### ISSUE TITLE
http filters: add request local storage (RLS)

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#151]
Implementation should be similar to how TLS works but built on top of the HTTP filter stack.

**Comment by mattklein123** [comment]
@alyssawilk this is the issue I was chatting with you about. I think you want "CLS" (connection local storage). IMO it could work very much like TLS where filters at config load time allocate a slot: https://github.com/envoyproxy/envoy/blob/master/include/envoy/thread_local/thread_local.h

**Comment by htuch** [comment]
Would there be any relationship with connection/request metadata? Or do we want to treat them as read-only and a distinct concept.

**Comment by mattklein123** [comment]
We could probably put the metadata into a slot. Not sure. Needs some thinking. This is a way that filters can pass arbitrary data between.

**Comment by mattwoodyard** [comment]
+1 for a unified CLS and RLS design. I've implemented both internally, but with the current APIs its not the cleanest design.

**Comment by jmarantz** [comment]
This is a cool idea.  Is this also a place where request-headers, response-headers, and possibly response-body can go, rather than passing them around discretely as needed?  It's nice to have the arbitrary slots but requests also have some semantics that could be held directly.
