### ISSUE TITLE
Add x-envoy-overloaded header to overload conditions(envoy stops accepting requests)

### ISSUE THREAD

**Issue by caoyukun0430** [envoyproxy/envoy#15106]
*Title*: *Add x-envoy-overloaded header to overload conditions(envoy max heap size reaches and stops accepting requests)*

*Description*:
When we configure circuit breaking on upstream services and trigger it by sending lots of traffic at the same time. We received responses for the dropped requests with the header x-envoy-overloaded: true.
< HTTP/1.1 503 Service Unavailable
< content-length: 81
< content-type: text/plain
< **x-envoy-overloaded: true**
< date: Fri, 03 Jul 2020 18:14:58 GMT
< server: istio-envoy
< 
/* Connection #0 to host 10.107.212.149 left intact
upstream connect error or disconnect/reset before headers. reset reason: overflow

But in the second condition of envoy overload: 
after configuring overload manager on the ingress gateway to set envoy overload stop_accepting_requests heap size to small values, we send large traffic to upstream services through the ingress gateway. And it triggers envoy overloaded and stops accepting requests. **We didn't see the header x-envoy-overloaded in the response**.
< HTTP/1.1 503 Service Unavailable
< content-length: 16
< content-type: text/plain
< date: Sat, 04 Jul 2020 13:52:49 GMT
< server: istio-envoy
< connection: close
< 
/* Closing connection 0
envoy overloaded 

I checked envoy document: it states explicitly that you only use this header for the circuit breakeriing and maintenance mode (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-overloaded). 

Is that any particular reason that you don't consider the envoy overloaded condition of stop accepting requests when map heap size reached? Because it looks to me it also belongs to envoy overload conditions and this header is useful for us to match our specific needs. 

**Desired behavior:**
I checked the envoy code, I think in the stop accepting requests overload condition, we need to modify the modify_headers for **nullptr** below to function that returns x-envoy-overloaded.
https://github.com/envoyproxy/envoy/blob/ff9c09f2146b15cef339b16aa42067df1664cd61/source/common/http/conn_manager_impl.cc#L897-L899

One reference could be the x-envoy-overloaded modify_headers example of circuit breaking.
https://github.com/envoyproxy/envoy/blob/ff9c09f2146b15cef339b16aa42067df1664cd61/source/common/router/router.cc#L993-L999

Thanks for the support!

BR/Yukun

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by junr03** [comment]
seems like a fair use of the header. 

@eziskind any opinions on this?

**Comment by eziskind** [comment]
Sounds fine to me. I'm just wondering if it would be useful to use a different header so that the client can distinguish between envoy itself being overloaded vs circuit-breaking kicking in to protect the upstream. Is that distinction useful? @akonradi @htuch

**Comment by akonradi** [comment]
I don't have an opinion on this, but looping in @antoniovicente

**Comment by antoniovicente** [comment]
Adding such a header in more places seems fine.  But it would be good to have a config field to suppress generation of that header in all cases.  I don't like the concept of openly advertising when a proxy is in overload or otherwise broadcasting when a potential attack on the proxy is working.

**Comment by htuch** [comment]
+1 I also agree it should be a distinct header, since the circuit breaker is upstream overload and we're talking about Envoy itself here as per @eziskind.
