### ISSUE TITLE
Is it possible to route requests by hashing an HTTP parameter ?

### ISSUE THREAD

**Issue by serhatcetinkaya** [envoyproxy/envoy#15118]
*Description*:

Let's say I have 3 upstream hosts behind envoy (number of hosts is static and almost never changes) and I want to route traffic on them based on the value of some HTTP parameter. What I want to do is take HTTP parameter `p`'s value, calculate its modulus (p % 3 = k) and route the client to `k-th` upsteam server. For example:

http://example.com/api?param=123 -> since 123 % 3 = 0, this will go to upstream-0
http://example.com/api?param=728 -> since 728 % 3 = 2, this will go to upstream-2
http://example.com/api?param=10 -> since 10 % 3 = 1, this will go to upstream-1

Is it possible to create a route config that satisfies this requirement ?

**Comment by junr03** [comment]
afaik there is no automatic calculation for what you propose. But you can combine [query param matching](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-queryparametermatcher) with clusters to enable that.

cc @snowp who might have more elegant suggestions.
