### ISSUE TITLE
Upstream HTTP/1 server through authenticated (SQUID) proxy

### ISSUE THREAD

**Issue by jeratora** [envoyproxy/envoy#15116]
*Description*:
Is it possible to configure Envoy so that an incoming request is forwarded to an upstream server through an corporate proxy requiring authentication ? (credentials being set in Envoy).

The pipeline would look like this : client --> sidecar Envoy (TLS origination + proxy credentials) --> Corporate Squid Proxy --> upstream server (REST)

I was thinking about using CONNECT but I'm not sure about HTTP1/1 complete support. As a fallback, a direct response + a LUA script using OpenRESTY to make proxied calls to the upstream server. But to be honest, I would prefer a pure "proxy" solution.

Thanks in advance for any hint / pointer / sample configuration.

*Relevant Links*:
https://github.com/envoyproxy/envoy/issues/11308

**Comment by cortex93** [comment]
@jeratora you will find a sample at https://github.com/envoyproxy/envoy/issues/11308#issuecomment-791592585
