### ISSUE TITLE
Got `GLIBC_2.18' not found error when using envoyproxy/envoy-build-centos

### ISSUE THREAD

**Issue by zihuaweng** [envoyproxy/envoy#15119]
I need to create an envoy image based on centos7 so I use envoyproxy/envoy-build-centos to build envoy. I used the same command for ubuntu `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'` but change the image to centos. 

image:
envoyproxy/envoy-build-centos:edbec0b7a298045bc4f3adbb2c04a3a2d257ccf5
source:
envoy 1.17 release branch

It failed when building wee8 using gn
```
/usr/local/bin/gn: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/gn)
```
The envoyproxy/envoy-build-centos is based on centos7 and only has GLIBC_2.17 installed, how do we build envoy successfully using the centos image?

**Comment by junr03** [comment]
cc @lizan

**Comment by zihuaweng** [comment]
Found a solution to bypass the glibc version issue and it works for red hat Linux 7 images. 
```
# Download gn code and compile it in the image instead of using the binary release
git clone https://gn.googlesource.com/gn
cd gn
python build/gen.py
ninja -C out  
cp out/gn /usr/local/bin/gn
chmod +x /usr/local/bin/gn

# Change bazeltools gn location in envoy/bazel/external/wee8.genrule_cmd so the system default gn will be used  
gn=buildtools/linux64/gn ==> gn=/usr/local/bin/gn
```

**Comment by bartsmykla** [comment]
I created a PR with fixes: https://github.com/envoyproxy/envoy-build-tools/pull/154
