### ISSUE TITLE
wasm: route matching for http filter

### ISSUE THREAD

**Issue by mathetake** [envoyproxy/envoy#15129]
It might be useful if Envoy allows users to specify when to call the Wasm callbacks, just like jwt filter. This would reduce the cost of calling back and forth between Envoy and Wasm VMs when users want to apply custom logics on the specific paths. cc @PiotrSikora @lizan

**Comment by PiotrSikora** [comment]
This is not unique to Wasm, see: https://github.com/envoyproxy/envoy/issues/11690.
