### ISSUE TITLE
Variable substitution in rewrite rules

### ISSUE THREAD

**Issue by jespersoderlund** [envoyproxy/envoy#15132]
*Title*: Variable substitution in rewrite rules

*Description*:
Today it's possible to use regexp to match parts of the incoming path and re-write using these matches. 

There are also situations where you want to include other parts of the request into the re-write rule, e.g. the value of a header or a metadata that has been picked-up.

A concrete example, is when proxying to a backend service which has a rest-based API which includes a customer id as part of the path, like `/rest-resource/customer-id/whatever`, but the customer-id might be part of an Authorization header or JWT token on the incoming request.

Ideally we would be able to use the same variables as used in the access-log format in all the re-write rules, prefix_rewrite, regexp_rewrite, redirect, ...

**Comment by dtjm** [comment]
Just leaving a breadcrumb here as I have been researching this functionality. 

I haven't actually tried it yet, but it looks like this may be doable using a combination of Lua scripting and the `:path` pseudo-header since headers and metadata should be accessible in the Lua environment.

**Comment by jespersoderlund** [comment]
That is probably possible. Though Lua scripting adds computing overhead and latency and should only be needed for non standard things IMO. I would definitely not put this feature in that bucket, but it seems not to get immediate traction so maybe my use case is the outlier, wanting to rewrite the path to include a user is picked up from the authenticated user, or actually a substring of the username
