### ISSUE TITLE
dubbo: more complete dubbo protocol support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#15131]
Title: more complete dubbo protocol support such as group/headers match

Description:

The current dubbo proxy only provides the ability to route based on interface and method. Although it does expose an API for group/headers matching, it does not implement it.

**There was a same issue before. But it was closed because of timeout. It seems that I cannot reopen it, so I simply re-created a new one.**

related issue: #14391 #14529

**Comment by wbpcode** [comment]
I will try get this done.

**Comment by zyfjeff** [comment]
🎉, Welcome to contribute
