### ISSUE TITLE
listener: performance degradation when exact balance used with original dst

### ISSUE THREAD

**Issue by caitong93** [envoyproxy/envoy#15146]
*Title*: *listener:performance degradation when exact balance used with original dst*

*Description*:

We use Envoy as a sidecar, all out bound traffic is first redirected to 127.0.0.1:15001(Envoy) by iptables, then forwarded to different listeners by original dst. When `exact balance` is enabled(on all listeners), we found the connection balance being worse. Tested with 32 downstream connections, 2 workers, connection distribution between the two handlers is always 1:31(sometimes 2:30) by observing [`downstream_cx_active`](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#per-handler-listener-stats).
When a new connection being received, it will be handled by `ExactConnectionBalancer`  first, and [increase `numConnections()` of the selected handler by one](https://github.com/envoyproxy/envoy/blob/v1.17.0/source/common/network/connection_balancer_impl.cc#L31). Then connection is forwarded to a new listener in `ConnectionHandlerImpl::ActiveTcpSocket::newConnection()` , and [decrease that gauge immediately](https://github.com/envoyproxy/envoy/blob/v1.17.0/source/server/connection_handler_impl.cc#L377 ).
If connections arrive quickly, there is a high chance that the first handler is always selected since `numConnections()` of all handlers are zero.

**Comment by lambdai** [comment]
IMHO the rebalance should be applied to the second listener. In most of the cases, the first listener doesn't own any connection

**Comment by caitong93** [comment]
> IMHO the rebalance should be applied to the second listener. In most of the cases, the first listener doesn't own any connection

Correct me if i am wrong. It seems rebalance can only happen at the first listener, see [comments here](https://github.com/envoyproxy/envoy/blob/v1.17.0/source/server/connection_handler_impl.cc#L370). If `exact_balance` is only enabled for the second listener, I guess it won't work.

**Comment by lambdai** [comment]
@caitong93  It won't work under the current code. 

This is a reasonable scenario that to apply to the second listener.  @mattklein123 I can change if you agree.

**Comment by mattklein123** [comment]
Yeah I agree we probably need to specially handle this case where for forwarded connections we do the rebalance at that point and not initially.

**Comment by boeboe** [comment]
@lambdai 

Will the fix mean that users have to configure exact_balance on the first catch_all listener 0.0.0.0:15001, or do users have to configure it on the next listener 0.0.0.0:9080 (in case the upstream service/cluster is at 9080)?

Related to https://github.com/istio/istio/issues/18152, where @hobbytp tried to apply the exact_balance on the second listener.

**Comment by lambdai** [comment]
> Will the fix mean that users have to configure exact_balance on the first catch_all listener 0.0.0.0:15001, or do users have to configure it on the next listener 0.0.0.0:9080 (in case the upstream service/cluster is at 9080)?

Sorry for the late reply.
For istio where the 15001 listener **usually** doesn't hold connection, the 15001 should use no-op balancer (the goal is to reduce latency) and the huge amount of "9080" sub listeners should use exact_balancer (trade cross thread migration for balancing).

Yeah, you can also use exact_balancer for 9080 listener and not to use balancer for 9070.
