### ISSUE TITLE
Lua filter: Expose streamInfo::requestedServerName()

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#15142]
*Description*:
The Lua filter currently allows access to the "stream info" on a request which exposes a few helpful pieces of information ([docs here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#config-http-filters-lua-stream-info-wrapper)) including the request protocol, downstream address, etc. Another useful piece of information in the stream info API is the requested server name (for SNI). It would be useful to expose this so users can do some inspection of the requested server name (see link below) or other use cases. This field is allowed as a variable in access logs/dynamic header values already and would be useful to add access in the Lua filter as well.

*Relevant Links*:
- Related to project Contour attempting to solve https://github.com/envoyproxy/envoy/issues/6767 but it could be useful outside of that context as well
  - Specifically needed when we have a filter chain/routes that match a wildcard domain `*.foo.com` and want to verify the requested server and `:authority` match

**Comment by sunjayBhatia** [comment]
Happy to put up a PR for this myself, but figured an issue would be better first

**Comment by snowp** [comment]
Sure, I see no problem with exposing this information.
