### ISSUE TITLE
discovery service path customization

### ISSUE THREAD

**Issue by if6was9** [envoyproxy/envoy#1515]
We would like to be able to pass extra contextual information through the discovery APIs and/or be able to alter the URI paths.

For instance, the SDS API is set up to be invoked at: /v1/registration/{service}

As an example enhancement would be able to re-configure this to /foo/bar/v1/registration/{service}.

Related enhancement that may achieve some but not all of the same objective would be to allow headers to be injected into the request.

It seems logical that the --service-cluster and --service-node and --service-zone options would be injected into the request header stream.  (Have not confirmed that this is/is-not the current behavior.  Just seems like it would be nice-and-logical.)

Some discussion here:

https://groups.google.com/forum/#!topic/envoy-users/dskbMpFiqlQ

**Comment by mattklein123** [comment]
This is fixed in v2 via sending Node as part of every request. Closing as won't fix.
