### ISSUE TITLE
Escape percent sign in log/custom response format

### ISSUE THREAD

**Issue by jasonstitt** [envoyproxy/envoy#15159]
*Title*: *Escape percent sign in log/custom response format*

*Description*:

The "access log" format uses %s for format strings, such as `%RESPONSE_CODE%`, but I don't see any way to escape a literal percent sign. Couldn't find one documented, and tried both `\%` and `%%` and neither worked.

Use case: This isn't just a log format, it's also used for custom responses (by `type.googleapis.com/envoy.extensions.filters.http.response_map.v3.ResponseMap`, under `body_format_override.text_format`). If configuring HTML responses, inline CSS can very easily break the config.

[optional *Relevant Links*:]

* https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-strings
* https://www.getambassador.io/docs/latest/topics/running/custom-error-responses/

**Comment by antoniovicente** [comment]
Yeah, seems like we should add %% -> % as a substitution option to substitution_formatter.cc

**Comment by zufardhiyaulhaq** [comment]
@jasonstitt correct me, you want to escape `%` when input custom access log format right?

**Comment by zufardhiyaulhaq** [comment]
or you want to input something like this to be recognized as well?
```
%%RESPONSE_CODE%%
```

**Comment by jasonstitt** [comment]
My use case is for escaping `%` (to insert a literal % in the output)
