### ISSUE TITLE
test: io_socket_handle_impl_integration_test.cc contains non-hermetic tests that depend on external network connectivity

### ISSUE THREAD

**Issue by antoniovicente** [envoyproxy/envoy#15164]
The style guidelines in https://github.com/envoyproxy/envoy/blob/main/STYLE.md call for tests being hermetic and no non-local network access.

The test in https://github.com/envoyproxy/envoy/blob/main/test/common/network/io_socket_handle_impl_integration_test.cc depends on external network connectivity to a hard-coded external IP address and fails in environments that correctly restrict external network connectivity.

It may be helpful to pass --sandbox_default_allow_network=false to bazel test in CI to detect tests that attempt external network connectivity.

cc @davinci26 @alyssawilk @mattklein123 @htuch @lizan

**Comment by davinci26** [comment]
We discussed in the PR with the reviewers and this is why I marked the test as `tags = ["requires-network"]`  (see [here](https://github.com/envoyproxy/envoy/blob/5e9806c1912866c6acf599fdd3370019eaaf99a9/test/common/network/BUILD#L436))

Is this not good enough?

**Comment by antoniovicente** [comment]
Thanks for pointing to that PR review comment.  It may have been helpful to add a comment that refers to it to the test's source code.  I didn't know about `tags = ["requires-network"]`, it seems that this test is the only one tagged in that way.

I filed the bug due to getting a report of this test failing in a dev's environment while reviewing a PR.  See https://github.com/envoyproxy/envoy/pull/15135#discussion_r580937355

**Comment by davinci26** [comment]
Yeah makes sense, I will add some comments on the source code of the test to leave trails on the discussion to make it clearer for the next person.

We chose it over the `manual` tag, because manual libraries are not getting compiled on CI and they end up being stale code. This allows devs to have a clear way to execute this feature on their dev box otherwise the code is not getting covered at all on Envoy tests.

**Comment by davinci26** [comment]
Follow up after the PR with the comments is merged is to use `getLocalAddress` and make the test pass on CI. See https://github.com/envoyproxy/envoy/pull/15212#discussion_r583839576
