### ISSUE TITLE
http call always failed (no healthy upstream) if target cluster has lb subset config

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#15163]
*Title*: http call always failed (no healthy upstream) if target cluster has lb subset config

*Description*:

When I try to send http request with `cluster->httpAsyncClient().send(...)`, if target cluster has lb subset config, then the requests always failed with a No Healthy Upstream error.
The reason is the metadataMatchCriteria() of route entry of async http client always return null.

https://github.com/envoyproxy/envoy/blob/5e9806c1912866c6acf599fdd3370019eaaf99a9/source/common/http/async_client_impl.h#L238

**Comment by wbpcode** [comment]
Maybe we can extend RequestOption so that it can be used to pass metadataMatchCriteria. When users use async http client to send requests, they can configure metadataMatchCriteria according to their needs.  🤔

**Comment by zuercher** [comment]
Some mechanism for passing the required metadata would be necessary for this to work.

**Comment by wbpcode** [comment]
For this problem, I think a small extension to RequestOption/StreamOption is sufficient. Just as below:

```
    StreamOptions& setmetadataMatchCriteria(const Router::MetadataMatchCriteria* m) {
      metadata_match_criteria_ = m;
      return *this;
    }
```

**Comment by wbpcode** [comment]
#15863
