### ISSUE TITLE
Is there a way to get the original value of host before rewrite ?

### ISSUE THREAD

**Issue by gengleilei** [envoyproxy/envoy#15169]
I need to print the original value of the host in the access log, and currently use the AUTHORITY field to extract the host value. If host is rewritten, the rewritten value is extracted from the AUTHORITY field, Is there a way to get the original value of host before rewrite ?

**Comment by wbpcode** [comment]
Set original host value to filter state or dynamic metadata before host is rewritten. Access log can print value in filter state or dynamic metadata. In general, a simple C++ filter can easily achieve this.

**Comment by wbpcode** [comment]
or simple lua script also can do this.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#dynamicmetadata

**Comment by gengleilei** [comment]
> Set original host value to filter state or dynamic metadata before host is rewritten. Access log can print value in filter state or dynamic metadata. In general, a simple C++ filter can easily achieve this.

Thank you very much for your reply. Does the above method need to modify the Envoy code? Are there fields in the existing HTTP header that can be extracted directly.

**Comment by wbpcode** [comment]
If you use C++ filter do this, you may need develop a new simple C++ http filter. If you use Lua script do this, then you don't need to write any C++ code. 
Currently in envoy, for each request Headers, it is an object shared by each module. After rewriting, the original data cannot be retrieved. You can only use some methods to save the required original data before rewriting.
