### ISSUE TITLE
Fallback when GrpcService parse failed to create gRPC call on wasm

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#15170]
It will be troublesome not to allow just identifying gRPC target host name as `grpcCall` argument. Specifically, we should provide fallback mechanism if `GrpcService` parse failed from bytes stream. 

https://github.com/envoyproxy/envoy/blob/c8fb3a56b4e8e282b0da80e2b19a347969d9cb2f/source/extensions/common/wasm/context.cc#L981-L984

We will get into some trouble without this feature when we introduce support gRPC client from proxy-wasm SDK such as Rust. (It doesn't have gRPC client support right now), because it will be required new code for the desired language generated from Envoy API proto. 

My expected behavior is when we failed to parse bytes stream, then try to parse the bytes stream as hostname. We will get `ParseFailure` after failed to parse hostname.

**Comment by Shikugawa** [comment]
cc @mathetake @PiotrSikora

**Comment by PiotrSikora** [comment]
The next iteration of the ABI uses cluster name instead of gRPC service proto definition, so it might be fine to add such fallback now, since it's purely additive and optional feature.

I'm a little worried about the mismatch between Envoy and SDKs, though. I think we need to bump ABI to v0.2.2.

See previous discussion: https://github.com/envoyproxy/envoy-wasm/issues/594.

**Comment by Shikugawa** [comment]
@PiotrSikora 
> The next iteration of the ABI uses cluster name instead of gRPC service proto definition, so it might be fine to add such fallback now, since it's purely additive and optional feature.

"cluster" is envoy specific notion. So I think that we should allow to accept hostname in ABI spec. After that we support to accept cluster name in envoy implementation.

**Comment by PiotrSikora** [comment]
> "cluster" is envoy specific notion.

Agreed, but we're in Envoy-specific issue, so I referred to it like that. It's actually called "upstream_name" in the spec.

> So I think that we should allow to accept hostname in ABI spec. After that we support to accept cluster name in envoy implementation.

When you say hostname, do you mean FQDN and port?

Note that we already allow cluster/upstram name in HTTP callouts, so adding the same to gRPC callouts is reasonable... Doing anything else might be too much for small ABI bump.

**Comment by Shikugawa** [comment]
SGTM. For now, let's proceed with specifying upstream cluster name.
