### ISSUE TITLE
hash policy should look at all values of a header

### ISSUE THREAD

**Issue by markdroth** [envoyproxy/envoy#15182]
The current hash policy code only looks at the first value of a given header.  The code even has a TODO about this:

https://github.com/envoyproxy/envoy/blob/76286f6152666c73d9379f21f43152bd03b00f78/source/common/http/hash_policy.cc#L42

For consistency with the changes that were recently made in routing to always look at multiple values of a given header, I think we should do the same thing here.

CC @htuch

**Comment by htuch** [comment]
Yeah, this seems a bug to me, we should hash on the full header as per @mattklein123
