### ISSUE TITLE
Integration test improvements

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#1518]
It would be nice to have end-to-end tests which were slightly less deterministic, to make it easier to have many streams and large bidirectional data flows going independently of each other.    This results in less deterministic tests but allows fuzzing corner cases for things like watermark limits and unexpected disconnects and resets.

Possibly a separate issue but likely predicated on this, it'd be nice to be able to do simpler things with less boilerplate - set a default backend response and client->sendSynchronousRequest, then inspect response headers or upstream headers after the fact. 

Finally, while I'm thinking about it, perhaps make an easy config for which test should apply to which languages so one doesn't have to edit multiple integration tests every time you want something tested for http/h2/h2-upstream.

... and as long as I'm dreaming, I'd like a pony.

**Comment by PiotrSikora** [comment]
Related: #186.

**Comment by mattklein123** [comment]
@alyssawilk are we still tracking stuff with this? Or should we call it done for now?

**Comment by alyssawilk** [comment]
Yeah, I have one last fix I'd like to get in.  There's still one race I was debugging but I'll ship it out for early inspection / critiques while I track that down
