### ISSUE TITLE
How to expose envoy outside the localhost

### ISSUE THREAD

**Issue by RameshKandukuriB** [envoyproxy/envoy#15192]
Configured envoy as edge gateway using standalone exe, I can route and access the the https endpoints using localhost:PortNumber. I need to expose my localhost outside on the network so that other users on my domain access the endpoints. What configuration should I use to expose envoy-gateway on my localhost to the domain network?

**Comment by yanavlasov** [comment]
I doubt anyone can answer this question. It depends on you network configuration and not on Envoy. You may need to do nothing or a lot depending on your situation.
