### ISSUE TITLE
Remove duplicated links to extensions/categories

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15191]
### Description

Now that we have automated linking between categories/extensions we need to remove the duplicated hard-coded existing links

**Comment by mk46** [comment]
Hi @phlax,  I would like to take it. Could you please point any example? Thanks!

**Comment by phlax** [comment]
>  I would like to take it.

hi @mk46 - cool!

there are a couple of parts to this and there are quite a few places that need updating i think

also, there are a couple of different situations we need to think about.

it might make sense to address this incrementally

a good example to get started is here:

https://storage.googleapis.com/envoy-pr/48325a4/docs/api-v3/config/accesslog/v3/accesslog.proto.html#config-accesslog-v3-accesslog

which is a bit more complex as its a legacy extension and has both `name` and `typed_config`

i guess what we need to do is remove the list from under `name` and replace with some text saying see below for list of names

in the the `typed_config` section we probably want to do something similar

this text is coming from here:

https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/accesslog/v3/accesslog.proto#L43

**Comment by phlax** [comment]
@mk46 did you make any progress ?

i need to address this bug quite quickly so perhaps i should get started on it ?

(apologies for hassling)

**Comment by mk46** [comment]
Would mind taking a look at linked PR

> @mk46 did you make any progress ?
> 
> i need to address this bug quite quickly so perhaps i should get started on it ?
> 
> (apologies for hassling)

Please take a look on linked PR. Thanks!
