### ISSUE TITLE
Converge the buffer parameter and op, or not

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#15218]
Userspace Io Handle is following the IoSocketHandle pattern right now.
1. Respect the watermark.
2. Reserve and read. The reserve is an op that computing the upper limit of a move.

This io handle is not used anywhere until a specialized listener and connection factory is landed.

Create this issue to explore after

1. How to improve the reserve-and-read? Do we want to use the exact value in socket handle?
2. Since the internal socket represents a hidden and extra chain node betweens the downstream socket and upstream socket, should we aim at downstreamsocket to upstream socket fairness, or os socket to internal socket fairness?

Once we understand it, the next step is to either unify the buffer parameters(remove duplication definition) or admit the exception at the internal userspace socket.

**Comment by lambdai** [comment]
CC @ggreenway @antoniovicente

**Comment by antoniovicente** [comment]
Motivating comment thread: https://github.com/envoyproxy/envoy/pull/14917#discussion_r583844596

I think this relates to buffer move limits, amount of data that the filter pipeline can move in one go and connection write limits.  I agree that we want a consistent framework for these things.
