### ISSUE TITLE
Use envoy-api specified protos in admin endpoint output.

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#1522]
In order to create admin endpoint output that can be programatically processed and analyzed, envoy-api needs to define proto apis for admin endpoint output format.

**Comment by srikailash** [comment]
Hello @junr03 , i can work on this issue . Have some questions regarding implementation 
1. I see that "/admin" has a bunch of actions (for example clusters and routes) , do you want me to add separate proto apis for each of them .
2. Work for this issue will be first adding proto to data-plane-api and modify https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc to use apis , please correct me if i am wrong.
Thanks in advance!

**Comment by junr03** [comment]
1. Yes, the idea is that each action would have a defined proto.
2. Correct again.

@srikailash happy to see some work in this area, @jsedgwick at Lyft is also starting to work on this, so I would like to avoid work duplication. He is mostly working on new endpoints so his work (both in defining the protos and adding the endpoints to the admin interface) should be parallelizable with moving the existing endpoints. 

I think a good first step would be to start a discussion on the structure we want to adopt for the output of the various endpoints. I am not sure if here, a google doc, or a PR or issue in data-plane-api is the best place for that. Thoughts @htuch?

**Comment by mattklein123** [comment]
We are starting to do this so closing this generic issue.
