### ISSUE TITLE
[Question] Envoy as a remote bazel cache

### ISSUE THREAD

**Issue by GabrielGhe** [envoyproxy/envoy#15228]
*Using Envoy as a remote cache for bazel*

Please forgive my ignorance, I'm still learning about Envoy. I'm trying to see if it would be possible to use Envoy as a remote cache implementation for bazel. There are currently [3 cache recommendations](https://docs.bazel.build/versions/master/remote-caching.html#setting-up-a-server-as-the-caches-backend) in bazel's docs, one of which is [nginx](https://docs.bazel.build/versions/master/remote-caching.html#nginx).
Each of those 3 options have their own set of problems:
1. nginx is good, but it has its faults. ([Blog post describing Dropbox migrated from nginx to Envoy](https://dropbox.tech/infrastructure/how-we-migrated-dropbox-from-nginx-to-envoy))
2. bazel-remote is written in golang and golang's GC pauses are a hindrance when cache response time is critical.
3. Google Cloud isn't an option for us.

It would need to support thousands of concurrent proto reads and writes to disk. Would Envoy be a good alternative?

**Comment by alyssawilk** [comment]
cc @toddmgreer

**Comment by GabrielGhe** [comment]
Related https://github.com/envoyproxy/envoy/issues/13295

**Comment by GabrielGhe** [comment]
Related https://github.com/envoyproxy/envoy/issues/378

**Comment by GabrielGhe** [comment]
bump to prevent close
