### ISSUE TITLE
Automated link to code from documentation

### ISSUE THREAD

**Issue by itayd** [envoyproxy/envoy#15232]
*Title*: Use https://github.com/cluttercode/clutter to link to code from documentation

*Description*:
Currently linking to documentation requires either linking to a line at a certain sha or a line on main, which is susceptible to becoming stale since location of code changes with other changes.

Suggested solution is to use clutter to automate this process. A suggested PR is: https://github.com/envoyproxy/envoy/pull/15051, though it needs further work to install clutter.

*Relevant Links*:
- https://github.com/cluttercode/clutter
- https://github.com/cluttercode/sphinx-clutter

**Comment by itayd** [comment]
cc @htuch @phlax

**Comment by htuch** [comment]
I think this is strictly a win from the PoV of docs being able to precisely references code locations, which comes up a fair bit (e.g. Life of a Request).
