### ISSUE TITLE
coverage flakiness on source/server

### ISSUE THREAD

**Issue by mathetake** [envoyproxy/envoy#15239]
The coverage on source/server recently has been flaky between 94.4 and 95.1 on unrelated PRs, for example https://github.com/envoyproxy/envoy/pull/15210 and https://github.com/envoyproxy/envoy/pull/15117.

What I have observed:
- This is somehow deterministic, i.e. on some commits, retesting would not work to go green.
- The root cause sits in `source/server/connection_handler_impl.cc`
    - by digging into the report, you can see that [these lines](https://github.com/envoyproxy/envoy/blob/7fd5792296f26ef4fd63a5fe4081bdc9605c70a4/source/server/connection_handler_impl.cc#L559-L571) would not be covered sometimes.

Temporarily the coverage threshold is loosen in https://github.com/envoyproxy/envoy/pull/15238 to stop this being a blocker on unrelated PRs. We should not tighten again the corresponding threshold until we resolve this flakiness.

**Comment by alyssawilk** [comment]
cc @asraa @antoniovicente  did we think this had something to do with ENVOY_BUG?

**Comment by asraa** [comment]
Hmmm that was fixed by https://github.com/envoyproxy/envoy/pull/15104/files, ENVOY_BUGs act as they do in opt mode while running coverage (non-fatal). If I peek at coverage reports, I maybe would have seen a decrement of line number counts after an ENVOY_BUG I know was tested, but I don't see that anymore. (Then again, I don't necessarily trust line numbers on coverage reports)

Was this the same issue you were seeing then?

**Comment by alyssawilk** [comment]
Ah curses, the ENVOY_BUG issue came up at the last envoy call as a potential cause of the coverage flakiness.  If it's not that (given it's fixed) we'll have to do some digging  :-(

**Comment by alyssawilk** [comment]
Also @mathetake thanks so much for not just the quick fix but finding the flaky area.
@ggreenway would you have cycles to take a look and add some deterministic testing for that area?

**Comment by lambdai** [comment]
I am not fully sure ENVOY_BUG is the root cause. One of the KP of conn handler is that there are too many internal classes. It is hard to write the test case to cover these lines.

This is my attempt toward deterministic https://github.com/envoyproxy/envoy/pull/15127

**Comment by mathetake** [comment]
not stale
