### ISSUE TITLE
How can I write custom filter and plug with HTTP filters or connection Manager?

### ISSUE THREAD

**Issue by mannuiitd** [envoyproxy/envoy#15230]
*Title*: *pluggable custom filters*

*Description*:
>How can i write my own HTTP filter which can be processed by connection manager?

[optional *Relevant Links*:]
>My requirement to use chain of custom filters to process request and response, i do not see any example or proper documentations.

**Comment by rojkov** [comment]
Have you checked this example https://github.com/envoyproxy/envoy-filter-example?
