### ISSUE TITLE
Add RouteEntry API to calculate URL rewrite as per getPathRewrite / finalizePathHeader

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#15246]
*Title*: *Add RouteEntry API to calculate URL rewrite as per getPathRewrite / finalizePathHeader*

*Description*:

We have a filter that uses request path to calculate some values. 
Unfortunately it currently does NOT have access to the results of url rewrite that is done in the router.
We would like to add a method `std::string RouteEntry::GetPathAfterRewrite()` that would return the same result as the getPathRewrite + finalizePathHeader methods.

**Comment by efimki** [comment]
@alyssawilk @htuch @stevenzzzz @ahedberg

**Comment by alyssawilk** [comment]
As discussed in-house I think that'd be a viable workaround but ccing @snowp and @mattklein123 for non-google takes

**Comment by mattklein123** [comment]
This sounds reasonable to me. The caveat being that the answer that is returned may be inaccurate if things change between when the API is called and when the router actually runs.

**Comment by efimki** [comment]
Awesome, thanks for confirming! 
Maybe it should be named `std::string RouteEntry::GetCurrentUrlPathAfterRewrite()` to make it clear(er) that it could change.

**Comment by snowp** [comment]
I don't think the returned value from a given RouteEntry instance would change, rather the route entry itself might change if the route cache is cleared at some point. Given that I don't think it makes sense to include this as part of the new function, but we should make sure this interaction is documented for routes in general.

+1 on this being a reasonable addition

**Comment by mattklein123** [comment]
> I don't think the returned value from a given RouteEntry instance would change, rather the route entry itself might change if the route cache is cleared at some point.

I might be mistaken but I think even the value could change? Imagine path being changed but the path still matches the same route?

**Comment by snowp** [comment]
Oh that's true, and it could also change if the path changes without a route cache clear, since the input to the path rewrite operation would change. So yeah making the name reflect the current evaluation of path rewriting makes sense to me.

**Comment by htuch** [comment]
I think it's a "viable workaround". This is not that dissimilar to https://github.com/envoyproxy/envoy/issues/15012. In both cases, we would be in a better place for these kinds of things if the router simply did less. I.e. if both path rewrites and headers to add/remove etc. were configurable filters that could be placed at explicit points in the filter chain, with the existing config expressed as per-route filter config.

I don't think there is anything actionable in ^^ in the context of this issue, but when we take @snowp generic matching API and redo `RouteConfiguration`, we might be able to take an approach in which we bake less into the route actions directly.

**Comment by efimki** [comment]
I've drafted https://github.com/envoyproxy/envoy/pull/15286 and would appreciate any input.
I'm also not sure where is a good place to add the tests for new API.

**Comment by alyssawilk** [comment]
test/common/router/config_impl_test.cc has tests for rewritePathHeader which you could extend?
