### ISSUE TITLE
Documentation for v1.17.1 missing

### ISSUE THREAD

**Issue by martin-sucha** [envoyproxy/envoy#15254]
Release notes / documentation (https://www.envoyproxy.io/docs/envoy/v1.17.1/intro/version_history) linked from the 1.17.1 release (https://github.com/envoyproxy/envoy/releases/tag/v1.17.1) returns 404 instead of the content of the docs.

**Comment by Shikugawa** [comment]
I've already noticed this issue since v1.17.1 triggered CI failed with missing master branch. I will fix this tomorrow.
