### ISSUE TITLE
enforce pragma once in header file

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#15264]
I find my newly added header file not following the style guide `Header guards should use #pragma once.`

Looks like this is not unique 
```
$ for f in `find include/ source/ test/ -name "*.h"`; do grep "pragma once" $f >/dev/null|| echo $f; done | wc -l
81
```

I will blindly add the pragma directive to make the future include no-brain.

Do we need a rule formatter to check/fix after the above change?

**Comment by alyssawilk** [comment]
yeah, looks like it's mostly but not all test code.  It'd definitely be worth adding to the fix format script IMO.

**Comment by lambdai** [comment]
An quick fix is added formatted is not ready.

Also the exceptions are listed below for track

1. chromium url
```
source/common/chromium_url/url_parse.h
source/common/chromium_url/url_parse_internal.h
source/common/chromium_url/url_canon_stdstring.h
source/common/chromium_url/url_canon_internal.h
source/common/chromium_url/url_canon.h
```
2. test/config/integration/certs
```
test/config/integration/certs/clientcert_hash.h
...
```
3. test/extensions/transport_sockets/tls/test_data/
```
test/extensions/transport_sockets/tls/test_data/
```

**Comment by yanavlasov** [comment]
The `source/common/chromium_url` should go away soon. I'm not quite certain when deprecation period has started for the code that uses it.

**Comment by botengyao** [comment]
We can close this issue in favor of the merged PR above.
