### ISSUE TITLE
Does envoy provide cluster-specific configurations for filters?

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#15271]
*Title*: *cluster-specific configurations for filters*

*Description*:
>There seems to be no way to configure a cluster-specific configuration for a certain network or http filter. 
Is there any plan to support it?

**Comment by alyssawilk** [comment]
Some of the filter have per route config but I don't know of any plans to add per cluster config.  I think it'd be a reasonable feature to add though.

**Comment by WeavingGao** [comment]
> Some of the filter have per route config but I don't know of any plans to add per cluster config. I think it'd be a reasonable feature to add though.

Got it. I'll try to implement it. Thanks a lot.
