### ISSUE TITLE
Legacy protocol support in Envoy - Diameter Radius etc

### ISSUE THREAD

**Issue by vsharathis** [envoyproxy/envoy#15279]
In the 4g and 5g collaboration, the legacy protocol support is missed in the envoy, as per the envoy document
envoy supports following protocols :

```
-       http
- 	http2
- 	https
- 	tcp
- 	tls
- 	grpc
- 	grpc-web
- 	mongo
- 	mysql*
- 	redis*
- 	udp
```
but when in the actual telco vendors have both legacy and envoy supported protocols (till now), if envoy can identify the legacy protocols, (Diameter, radius) vendors can use envoy as a load balancer for both legacies and supported protocols.

**Comment by alyssawilk** [comment]
I don't think there would be objection to adding legacy protocols, but per https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md to land it upstream you'd have to find someone willing to code it up (and support it) and a maintainer to co-own.

**Comment by vsharathis** [comment]
RADIUS stands for Remote Authentication Dial-In User Service, is a security protocol used in the AAA framework to provide centralized authentication for users who want to gain access to the network.
Features – Some of the features of RADIUS are:

Open standard protocol for AAA framework i.e it can use between any vendor device and Cisco ACS server.
It uses UDP as a transmission protocol.
It uses UDP port number 1812 for authentication and authorization and 1813 for accounting.
If the device and ACS server is using RADIUS then only the passwords of AAA packets are encrypted.
No explicit command authorization can be implemented.
It provides greater extensive accounting support than TACACS+.
In RADIUS, authentication and authorization are coupled together.
Diameter is a planned replacement of RADIUS. It is an AAA protocol for applications such as network access and IP mobility.
It is intended to work in both local and roaming AAA situations.

The diameter is just twice the predecessor protocol Radius.
It uses **TCP or SCTP** and not UDP.
It uses transport-level security (IPSEC or TLS).
It has a 32-bit identifier instead of 8 bit.
It supports stateless as well as stateful mode.
It supports application-layer acknowledgment, defines failover.
It offers better roaming support.
It uses AVPs.
Diameter allows the definition of new commands and attributes. It is easy to extend.
in simple words diameter support TLS/TCP and DTLS/SCTP

for now, Istio will not support STCP, this implementation to be taken care of in envoy proxy guess, kindly check and share your comments.

For reference: #7521 and envoyproxy/envoy#9430

RFCs attached for reference:
https://tools.ietf.org/html/rfc6733
https://tools.ietf.org/html/rfc3588
https://tools.ietf.org/html/rfc5719
