### ISSUE TITLE
TSI socket does not obey read limits or write buffer high-watermarks

### ISSUE THREAD

**Issue by yihuazhang** [envoyproxy/envoy#15296]
The current TSI socket implementation has the following problems: 

1. It uses a default max frame size - 1MB defined in gRPC [ALTS TSI implementations](https://github.com/grpc/grpc/blob/master/src/core/tsi/alts/handshaker/alts_tsi_handshaker.h#L44 ). It is considered too large and also inconsistent with SSL socket, which is 16KB. 
2. TsiSocket doRead() does not obey read limits by doing an unbounded read from a raw socket. 
3. TsiSocket doWrite() has the problems of 1) inefficient memory usage by protecting full input data into an internal buffer and 2) potentially losing the data stored in the internal buffer that has yet been flushed to the network.

**Comment by yihuazhang** [comment]
F.Y.I. @htuch, @jiangtaoli2016, @antoniovicente

**Comment by antoniovicente** [comment]
ALTS / TSI is for the most part only used by Google.  I assume your team will drive the fixes to this component.

**Comment by htuch** [comment]
While Google is the developer of ALTS, it's actually used by many GCP users, so anyone running Envoy on GCP probably has some interest in this bug resolution.
