### ISSUE TITLE
Add grpc_httpjson_transcoder external dependency to core

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#15304]
This is for https://github.com/envoyproxy/envoy/pull/15299 to address https://github.com/envoyproxy/envoy/issues/7763

*Title*: Add grpc_httpjson_transcoder external dependency to core

*Description*:
[grpc_httpjson_transcoding](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding) external dependency is already used by http filter extension  [grpc_transcoder](https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/grpc_json_transcoder). 

In order to support url_template in RouteMatch,  propose to add this dependency to core:

Following items (from [check list](https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md#new-external-dependencies)) may have issues:
* SecPolicy: no
* CI-Tests: no
* Releases: no

**Comment by qiwzhang** [comment]
@envoyproxy/dependency-shepherds @envoyproxy/security-team

**Comment by dio** [comment]
@qiwzhang do you accept external contributions for enabling CI in that repo? :).

**Comment by qiwzhang** [comment]
Yes @dio

**Comment by qiwzhang** [comment]
Hi @nareddyt  could you help to add CI test for grpc_httpjson_transcoding repo?

**Comment by nareddyt** [comment]
I still do not have admin access to the repo. I will try again.

**Comment by moderation** [comment]
Full results from OSSF Scorecard is:
```
scorecard --repo=https://github.com/grpc-ecosystem/grpc-httpjson-transcoding

RESULTS
-------
Active: Pass 10
Branch-Protection: Fail 0
CI-Tests: Fail 4
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Pass 10
Frozen-Deps: Fail 5
Fuzzing: Fail 10
Packaging: Fail 0
Pull-Requests: Pass 10
SAST: Fail 10
Security-Policy: Fail 0
Signed-Releases: Fail 0
Signed-Tags: Fail 0
```
Descriptions of categories at https://github.com/ossf/scorecard#checks. In addition to CI, doing code scanning with CodeQL might be another quick win. Some of the dependencies inhttps://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/master/repositories.bzl are themselves old - protobuf 3.10.1 as an example.

**Comment by nareddyt** [comment]
@qiwzhang I was planning on updating the dep for protobuf tomorrow. I can handle CI setup as well once I have permissions.

I don't have background on the other items. @moderation which ones are hard blockers?

**Comment by moderation** [comment]
@nareddyt CI and Security Policy are both `MUST` for core deps - https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md#new-external-dependencies

**Comment by qiwzhang** [comment]
@moderation 
1) CI is added 
2) security policy is added.

Could you check again?  

Thanks

**Comment by moderation** [comment]
`scorecard` is picking up your security policy. Not sure why your CI score is unchanged.
```
RESULTS                    
-------                    
Active: Pass 10            
Branch-Protection: Fail 0  
CI-Tests: Fail 4           
CII-Best-Practices: Fail 10
Code-Review: Pass 10       
Contributors: Pass 10      
Frozen-Deps: Fail 5        
Fuzzing: Fail 10           
Packaging: Fail 0          
Pull-Requests: Pass 10     
SAST: Fail 10              
Security-Policy: Pass 10   
Signed-Releases: Fail 0    
Signed-Tags: Fail 0        
```
@envoyproxy/dependency-shepherds for review

**Comment by antoniovicente** [comment]
Is it worth considering splitting the url_template code into a separate library that can be consumed by core?

Do we have benchmarks that compare the url_template implementation from grpc_httpjson_transcoder to equivalent RE2 regexps that match the same inputs?

**Comment by qiwzhang** [comment]
It is a good idea to split `path_matcher` code used for url_template match from grpc_httpjson_transcoder.  I will explore that.

**Comment by qiwzhang** [comment]
For performance,  @nareddyt has a performance test.  Maybe he can add url_template perf test with the pending pr to get the number

**Comment by nareddyt** [comment]
> For performance, @nareddyt has a performance test. Maybe he can add url_template perf test with the pending pr to get the number

Sure, I'll get started on that today.

**Comment by nareddyt** [comment]
@antoniovicente @qiwzhang the benchmark is added in #15493. Fairly interesting - I expected it to be slow, but not slower than the equivalent regex route matchers. I guess building the whole tree structure but not taking advantage of combining multiple routes adds a lot of overhead.

**Comment by qiwzhang** [comment]
This issue can be replaced by https://github.com/envoyproxy/envoy/issues/15506
