### ISSUE TITLE
TCP port conflict

### ISSUE THREAD

**Issue by style95** [envoyproxy/envoy#15305]
*Title*: *TCP port is conflict while sending traffic to multiple destinations*

*Description*:
I am new to Envoy, so if this is a too-naive question, please bear with me.

When my service is trying to send some packets to endpoints 1 and 2, it seems sometimes the TCP port is in conflict.

For example, when my service is trying to send some packets like below:

* `10.10.10.10:54321` -> `10.10.10.11:8080`
* `10.10.10.10:54321` -> `10.10.10.12:8080`

Since the destination IPs are different and no issue.
But if the Envoy has come to the scene, it becomes like below:

* `10.10.10.10:54321` -> `127.0.0.1:15001` (Connected to `10.10.10.11:8080`)
* `10.10.10.10:54321` -> `127.0.0.1:15001` (Trying to newly connect to `10.10.10.12:8080`)

In this case, in the Envoy side, there is already a connection between `10.10.10.10:54321 -> 127.0.0.1:15001`.
So it responds with Ack rather than `SYN_ACK` while handling the second traffic.

So it causes retry and introduces around 1 second of delay.

In the below screenshot, my service is connected to one service and try to make a new connection to another service.
And Envoy responds with ACK rather than SYN_ACK as it considers the connection is already made.
![image](https://user-images.githubusercontent.com/3447251/109922826-4f12bf00-7d01-11eb-84db-8eaf5fdfb798.png)

* `10.173.94.54:51052` -> `125.209.234.18:10006` (already connected)
* `10.173.94.54:51052` -> `172.24.34.140:8080` (tries to connect)

Because of the NAT nature of Envoy, it becomes

* `10.173.94.54:51052` -> `127.0.01.1:15001` (envoy)
* `10.173.94.54:51052` -> `127.0.01.1:15001` (envoy)

So the port source is conflicted.
Since it rarely happens as ports are enough but it occasionally "happens" anyway.

Is there any way to work around or resolve this issue?

Thanks in advance.

**Comment by alyssawilk** [comment]
do you need to hard-code the port for talking to loopback?
Generally if you're trying to TCP proxy from a listener on 10.10.10.10 to an "upstream" at 127.0.01.1:15001 you simply wouldn't specify a port for the upstream connection, and Envoy will auto-select an unused ephemeral port, allowing for many connections.

**Comment by lambdai** [comment]
That is the limitation of NAT. I don't see what Envoy could do here.

There are proposal to use more local ip (127.0.0.X for free) or more port (15001, 15002...) *in istio*

**Comment by lambdai** [comment]
@style95 Could you update description? s/10.10.10.10:8080/10.10.10.10:54321/  It's much clear since 54321 is an obvious ephemeral port randomly picked up by client :)

**Comment by lambdai** [comment]
> do you need to hard-code the port for talking to loopback?
> Generally if you're trying to TCP proxy from a listener on 10.10.10.10 to an "upstream" at 127.0.01.1:15001 you simply wouldn't specify a port for the upstream connection, and Envoy will auto-select an unused ephemeral port, allowing for many connections.

I can speak for @style95 Port 15001 is the redirected port that Envoy is listening. 15001 is not the port bind by Envoy to connect to the remote <ip:8080>

**Comment by style95** [comment]
@lambdai Thanks. I updated the description accordingly.

@alyssawilk It's exactly what @lambdai described.
`15001` is the listening port of Envoy.
The client randomly selects the source ports to connect to the destinations and they are in conflict.

> That is the limitation of NAT. I don't see what Envoy could do here.
> There are proposal to use more local ip (127.0.0.X for free) or more port (15001, 15002...) in istio

So if we use Envoy, it would happen anyway? 
I am curious if all users of Envoy are really facing the same issue.

Even if we use multiple IPs(`127.0.0.x`) and more ports, I believe it would happen and the probability would not be small.

Is there any way to at least deal with the 1s delay at Envoy?

**Comment by alyssawilk** [comment]
You are creating two different connections and you're saying the kernel is assigning them to the same ephemeral port? I'm confused about how that could happen so I think I'm still misunderstanding the problem.

I've definitely seen port exhaustion being a problem but AFIK that would result in Envoy failing to create a connection upstream entirely, not using one port for 2 connections.

**Comment by style95** [comment]
@alyssawilk 
My service is trying to create two different connections with different source IP/port and destination IP/port.
But because of NAT nature, packets are path through Envoy and at this point, destination IP/port are changed to the Envoy's one. At this point, the two destinations becomes one Envoy and it makes a tcp port conflict.

In the example below, if there is no envoy in between my service and destinations, there would be no problem even if my service is using the same source IP/Port.
```
10.173.94.54:51052 -> 127.0.01.1:15001 (envoy) -> 125.209.234.18:10006 (already connected)
10.173.94.54:51052 -> 127.0.01.1:15001 (envoy) -> 172.24.34.140:8080
```

**Comment by style95** [comment]
I am curious this configuration could alleviate the situation.

>transparent
(BoolValue) Whether the listener should be set as a transparent socket. When this flag is set to true, connections can be redirected to the listener using an iptables TPROXY target, in which case the original source and destination addresses and ports are preserved on accepted connections. This flag should be used in combination with an original_dst listener filter to mark the connections’ local addresses as “restored.” This can be used to hand off each redirected connection to another listener associated with the connection’s destination address. Direct connections to the socket without using TPROXY cannot be distinguished from connections redirected using TPROXY and are therefore treated as if they were redirected. When this flag is set to false, the listener’s socket is explicitly reset as non-transparent. Setting this flag requires Envoy to run with the CAP_NET_ADMIN capability. When this flag is not set (default), the socket is not modified, i.e. the transparent option is neither set nor reset.


https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto.html?highlight=transparent

**Comment by style95** [comment]
Does anyone have any idea about this?
