### ISSUE TITLE
Connection limit filter

### ISSUE THREAD

**Issue by nitgoy** [envoyproxy/envoy#15325]
*Title*: *Add support for limiting absolute number of connections*

*Description*:
>Envoy has the capability to limit the rate of new connections via the L4 local rate limit filter. It would also be useful to be able to limit the total number of connections, specifically on a per filter chain basis or based on some descriptors from the request.

**Comment by alyssawilk** [comment]
Are you looking for something like overload.global_downstream_max_connections?

https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager

**Comment by alyssawilk** [comment]
cc @phlax this took me a while to dig up even though I knew it existed. 

Maybe we should have links from the https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/global_rate_limiting#arch-overview-global-rate-limit since it does limit connections

**Comment by nitgoy** [comment]
> Are you looking for something like overload.global_downstream_max_connections?

AFAIK, the downstream_max_connections can be applied at listener level. I'm looking for something that can be customized per filter chain and/or support descriptors like the rate limit filters do.

**Comment by mattklein123** [comment]
I think this is a reasonable request. Do you want to throw together a short design doc for discussion?

**Comment by delong-coder** [comment]
Hi @mattklein123 @alyssawilk 
I created a PR for the short design doc, please take a look:
https://github.com/envoyproxy/envoy/pull/15519/files
After that we can contribute our code, thanks.

**Comment by nitgoy** [comment]
Closing this issue with the following PR merged:
https://github.com/envoyproxy/envoy/pull/15519
