### ISSUE TITLE
udp: make max packet size configurable

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#15327]

**Comment by mk46** [comment]
@mattklein123  Hi, I would like to work on this.  I think  `max_packet_size` should be  in `UdpProxyConfig`?

**Comment by sidd4u** [comment]
@mattklein123 Hi, I would like to work on this request. I have been working on C++ for 8 years. I need to start contributing to open source for my own development. Could you please give me the opportunity to work on this.

**Comment by mattklein123** [comment]
@mk46 @sidd4u I have a half finished PR for this so it would be best to pick a different issue, thank you.
