### ISSUE TITLE
Version History Path Mismatch

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#15330]
*Title*: *Mismatch of version_history page for v1.17.1 from Home page of Envoyproxy wrt github path*

*Description*:
> Home page of envoyproxy "https://www.envoyproxy.io/docs" there is no direct link for v1.17.1. it is through github ref "https://github.com/envoyproxy/envoy/releases/tag/v1.17.1".
Is there any change in doc root/ structure ?  

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Shikugawa** [comment]
@ankatare We can see v1.17.1 link on https://www.envoyproxy.io/docs. Would you mind describing this problem for more detail?

<img width="1219" alt="Screen Shot 2021-03-06 at 9 40 05" src="https://user-images.githubusercontent.com/17607122/110188686-f3127c80-7e5f-11eb-9ca3-214c06d7ea56.png">

**Comment by mattklein123** [comment]
This was just fixed by @moderation

**Comment by ankatare** [comment]
@mattklein123 thanks for clarifying it
