### ISSUE TITLE
Service registration example and docs

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#1534]
There's already an example SDS, but we could also have a simple example service registration app that healthchecks and registers/deregisters. At the very least, maybe add to the service discovery docs that make it more obvious how to do this sort of thing yourself.

This issue would be partially obviated by #1533

**Comment by fabianfett** [comment]
@bplotnick Did you find anything? I need information on how to enforce my envoy to register with my sds service. The envoy does lookups but does not register the service that I want to advertise.
