### ISSUE TITLE
[Question] Send a local response without closing the connection

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/envoy#15343]
*Title*: *Send a local response without closing the connection*

*Description*:
I have written a custom http filter for web socket connections to rate limit based on the number of frames sent through a connection. The filter basically publishes metadata needed for rate limiting and analytics through a gRPC bidi stream. I have a requirement to send a local reply from the filter when the connection is rate limited.

eg: Message throttled out due to subscription level throttling limit reached.

But since this is a websocket connection, I don't want to close the connection. Just send local responses without closing the connection. Envoy ext_auth and ratelimit filters use `sendLocalReply()` but it closes the connection. Is my requirement possible with the current envoy implementation in filter level without modifying envoy source ? Thanks

**Comment by dio** [comment]
cc. @alyssawilk @snowp

**Comment by alyssawilk** [comment]
I think I need a bit more information about what you're trying to do here.

If you're proxying websocket, you're forwarding headers and streaming body upstrema, then proxying headers and streaming websocket data from upstream.

sendLocalReply sends headers and body and end stream downstream.  There's not much point keeping the connection open once you've sent end stream as the upstream can't send more data.  Also having sendLocalReply send headers isn't going to play well with upstream sending response headers.    Are you just wanting to send some websocket payload downstream?   That might be doable but there will be some complications.

**Comment by NomadXD** [comment]
@alyssawilk Yeah, keeping the connection open after sendLocalReply() doesn't make any sense that way. So how do I send some websocket payload downstream ? By calling encodeData() from a filter ? If it's doable with my current knowledge about envoy (implemented some http filters with grpc async client), would like to give it a try. Thanks

**Comment by alyssawilk** [comment]
yeah, this is where you have to be a bit careful.  Sending data before upstream has sent response headers is going to cause problems.  If you make sure you delay until your filter has seen response headers, you should be able to addEncodedData/injectEncodedDataToFilterChain to add payload.  I'd suggest reading up on the differences between the two and integration testing to make sure you're happy with the results but I think they'll handle the work you're looking for.

**Comment by NomadXD** [comment]
@alyssawilk yeah probably my filter sees the response headers first because for websocket connections,  response headers are sent at the connection initialization time with 101 upgrade accepted. And I'm talking about a some point later in time that some websocket frames have already sent through envoy and when the throttle limit (5000 frames per minute) is reached, sending a websocket payload saying that the limit is reached without closing the connection. Thanks a lot for the help. Will go through the integration tests and see.
