### ISSUE TITLE
Use jinja for protodoc

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15351]
### description

the complexity of protodoc seems to have outgrown the python templating pattern used

this is resulting in a lot of `\n` and `{indent}` fu and making it increasingly difficult to work with

one possible solution to this problem is to use python only to create structured variables that a proper templating/markup lang like jinja can consume

**Comment by phlax** [comment]
cc @htuch

**Comment by htuch** [comment]
@phlax seems totally reasonable.

**Comment by phlax** [comment]
protodoc uses jinja now
