### ISSUE TITLE
./ci/do_ci.sh: line 120: bazel: command not found

### ISSUE THREAD

**Issue by jtou100** [envoyproxy/envoy#15357]
My steps:
export ENVOY_DOCKER_BUILD_DIR=/data/envoy/envoy-docker-build
export IMAGE_NAME=envoyproxy/envoy-build-centos
export IMAGE_ID=d9b1f1cbb24b2cecca768feaa9fa3c6e6660a948-amd64

and execute command:
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'

![image](https://user-images.githubusercontent.com/5299177/110270414-b3cf6180-8000-11eb-900e-cf43349d00d2.png)

There is no bazel command, but my system has this command. I don't know if any steps are missing. Can any friend help me

**Comment by mk46** [comment]
I think you had skipped any toolchain. Please see https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#building-envoy-with-bazel.
