### ISSUE TITLE
Ability to check the cluster health in the filter

### ISSUE THREAD

**Issue by lwpyr** [envoyproxy/envoy#15389]
*Title*: Ability to check the cluster health in the filter

*Description*:
When the upstream cluster is down, we want to have a way to check it in the filter and do something against it, for example, re-route the request.
If there is a way to check the cluster health in the filter? or if it is possible we can add the ability?

**Comment by mattklein123** [comment]
Health is a complicated topic as it depends on priority, locality, and a bunch of other things. You can get at the cluster's current priority set through https://github.com/envoyproxy/envoy/blob/498d65b2fabceebbda9c0b993ba63c127fd16f27/include/envoy/upstream/thread_local_cluster.h#L24 which may be enough for what you need? cc @snowp

**Comment by lwpyr** [comment]
> Health is a complicated topic as it depends on priority, locality, and a bunch of other things. You can get at the cluster's current priority set through
> 
> https://github.com/envoyproxy/envoy/blob/498d65b2fabceebbda9c0b993ba63c127fd16f27/include/envoy/upstream/thread_local_cluster.h#L24
> 
> which may be enough for what you need? cc @snowp

Thanks for your reply, I'm kind of a novice to this project, your advice can help a lot.
To narrow the definition, if there is no endpoint could serve the request, we think the cluster is down. Do you think it is OK to just follow the no-pass-through logic in the health check filter, which checks the cluster info stats.

**Comment by mattklein123** [comment]
> Do you think it is OK to just follow the no-pass-through logic in the health check filter, which checks the cluster info stats.

This could work also depending on your needs.
