### ISSUE TITLE
Flaky test: //test/extensions/quic_listeners/quiche/integration:quic_http_integration_test 

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#15407]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/68704/logs/212

//test/extensions/quic_listeners/quiche/integration:quic_http_integration_test failed with a timeout on TSAN on my PR with unrelated changes.

**Comment by auni53** [comment]
Ah I just meant that the test failed due to a timeout, not a test failure.

**Comment by danzh2010** [comment]
The test is already sharded. I'll increase test_size to give it longer time.
