### ISSUE TITLE
Missing header "age" for "valid-for-minute" response in cache filter.

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#15413]
*Title*: *Not getting "age" header for "valid-for-minute" resonse in cache filter.*

*Description*: After 30 sec resending curl request (curl -i localhost:8000/service/1/valid-for-minute) In cache filter for response type "valid-for-minute" not getting age header.
ref : https://www.envoyproxy.io/docs/envoy/v1.17.1/start/sandboxes/cache#valid-for-minute   
                       
>Describe the issue.

[optional *Relevant Links*:] https://www.envoyproxy.io/docs/envoy/v1.17.1/start/sandboxes/cache
>Any extra documentation required to understand the issue.

**Comment by mk46** [comment]
Hi @ankatare, First response from service1_1  (curl -i localhost:8000/service/1/valid-for-minute) will contains no age header as expected. After that, any request from service1 will be served cache filter for 60s will have `age header`.
I have verified the above. Please see service1 log
```
service2_1     |   stored_response = yaml.load(open('/etc/responses.yaml', 'r')).get(response_id)
service2_1     | 127.0.0.1 - - [17/Mar/2021 15:12:00] "GET /service/2/valid-for-minute HTTP/1.1" 200 -
service2_1     | 127.0.0.1 - - [17/Mar/2021 15:13:01] "GET /service/2/valid-for-minute HTTP/1.1" 304 -
service2_1     | 127.0.0.1 - - [17/Mar/2021 15:13:03] "GET /service/2/valid-for-minute HTTP/1.1" 304 -
```
Please LMK how you're producing?

> _Description_: After 30 sec resending curl request (curl -i localhost:8000/service/1/valid-for-minute) In cache filter for response type "valid-for-minute" not getting age header.

**Comment by ankatare** [comment]
@mk46 yeah. next and subsequent request < 60 Sec for service_1 should have age header (i.e. cached response).

**Comment by ankatare** [comment]
also it seems working fine now on latest code. Thanks !!!

**Comment by ankatare** [comment]
We can close this now as it is non repro on latest code.
