### ISSUE TITLE
documentation for circuit breaker cx_open statistic is misleading or possibly incorrect

### ISSUE THREAD

**Issue by rblumen-desk** [envoyproxy/envoy#15415]
In the file [cluster_stats.rst](https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/upstream/cluster_manager/cluster_stats.rst)

The documentation for cx_open says: "Whether the connection circuit breaker is closed (0) or open (1)"

I am observing that when the circuit breaker is allowing traffic provides a 0 for the cx_open statistics.  I had interpreted the documentation to mean open is allowing traffic and closed is not allowing traffic.  I brought this up on the [slack support channel](https://envoyproxy.slack.com/archives/C78HA81DH/p1615400316109000).  Tony Allen (@tonya11en) responded: 

> That documentation needs to say something like
> Whether the connection circuit breaker has capacity and can admit more connections (0) or is at capacity and will reject new connections (1)

**Comment by mattklein123** [comment]
Thanks, docs PRs appreciated.

**Comment by tonya11en** [comment]
> Thanks, docs PRs appreciated.

lol, I'll take care of this tonight. Feel free to assign.
