### ISSUE TITLE
ENVOY_BUG improvement for tracking: unique identifier

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#15439]
Counters are held in the `EnvoyBugRegistrationImpl` keyed by filename:lineno. 

In anticipation of monitoring per ENVOY_BUG hits over time, ideally ENVOY_BUGs should have a unique identifier. This change would be better made sooner rather than later while its still in early adoption. Filename:lineno isn't stable over changes.

Proposal:
Migrate `ENVOY_BUG(condition, msg)` to `ENVOY_BUG(bug_id, condition, msg)` for example (from a real usage):

`ENVOY_BUG(service_stop, service_static->status_.dwCurrentState == SERVICE_RUNNING, "Attempting to stop Envoy service when it is not running");`

**Comment by antoniovicente** [comment]
Giving ENVOY_BUGs a name seems very attractive.  The file + line as IDs are not stable and thus not great for use in monitoring/stats.

Giving ASSERTs names seems much harder, but that may be fine since they really shouldn't ever trigger.
