### ISSUE TITLE
Proxying with HTTP CONNECT does not pass to ext_authz filter as expected

### ISSUE THREAD

**Issue by rohrit** [envoyproxy/envoy#15438]
*Title*: Proxying with HTTP CONNECT does not pass to ext_authz filter as expected

*Description*:

*** Initially tested with OPA but is reproducible for ext_authz filters in general ****

I have a dynamic forward proxy as described in https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy being used to implement a forward proxy. I have used instructions from https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#:~:text=Envoy%20also%20has%20support%20for,Find%20below%20some%20usage%20scenarios.&text=Note%20that%20when%20using%20HTTP,when%20you%20have%20the%20choice. to configure support for HTTP CONNECT. I am also trying to use OPA as an external authorizer to implement a blacklist for blocking certain websites.

Without OPA, both HTTP and HTTPS based sites are proxied correctly. However, with OPA in the mix only HTTP based sites work and for HTTPS, OPA does not get the request from Envoy and the request times out eventually.

*Repro steps*:
HTTP proxying working

$ curl -k -v -x 10.0.2.15:10000 http://neverssl.com
* Rebuilt URL to: http://neverssl.com/
*   Trying 10.0.2.15...
* TCP_NODELAY set
* Connected to 10.0.2.15 (10.0.2.15) port 10000 (#0)
> GET http://neverssl.com/ HTTP/1.1
> Host: neverssl.com
> User-Agent: curl/7.58.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< content-type: text/html
< content-length: 2536
< last-modified: Thu, 19 Nov 2020 22:29:21 GMT
< accept-ranges: bytes
< server: envoy
< date: Wed, 10 Mar 2021 14:51:22 GMT
< etag: "e8bb9152091d61caa9d69fed8c4aebc6"
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 eee4869214ceb6482750c38369bff498.cloudfront.net (CloudFront)
< x-amz-cf-pop: MAA50-C2
< x-amz-cf-id: 0_bjdUO7V4sEhcJjxpHnevLTHCqohVGE7-MSq0xNGJXgvaZdlRKVDw==
< age: 74621
< x-envoy-upstream-service-time: 94
<
<html>
    <head>
        <title>NeverSSL - helping you get online</title>

        <style>
        body {
             font-family: Montserrat, helvetica, arial, sans-serif;
             font-size: 16x;
             color: #444444;
             margin: 0;
        }
        h2 {
            font-weight: 700;
            font-size: 1.6em;
            margin-top: 30px;
        }
        p {
            line-height: 1.6em;
        }
        .container {
            max-width: 650px;
            margin: 20px auto 20px auto;
            padding-left: 15px;
            padding-right: 15px
        }
        .header {
            background-color: #42C0FD;
            color: #FFFFFF;
            padding: 10px 0 10px 0;
            font-size: 2.2em;
        }
        
        </style>
    </head>
    <body>

    <div class="header">
        <div class="container">
        <h1>NeverSSL</h1>
        </div>
    </div>

    <div class="content">
    <div class="container">

    <h2>What?</h2>
    <p>This website is for when you try to open Facebook, Google, Amazon, etc
    on a wifi network, and nothing happens. Type "http://neverssl.com"
    into your browser's url bar, and you'll be able to log on.</p>

    <h2>How?</h2>
    <p>neverssl.com will never use SSL (also known as TLS). No
    encryption, no strong authentication, no <a
    href="https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security">HSTS</a>,
    no HTTP/2.0, just plain old unencrypted HTTP and forever stuck in the dark
    ages of internet security.</p>

    <h2>Why?</h2>
    <p>Normally, that's a bad idea. You should always use SSL and secure
    encryption when possible. In fact, it's such a bad idea that most websites
    are now using https by default.</p>

    <p>And that's great, but it also means that if you're relying on
    poorly-behaved wifi networks, it can be hard to get online.  Secure
    browsers and websites using https make it impossible for those wifi
    networks to send you to a login or payment page. Basically, those networks
    can't tap into your connection just like attackers can't. Modern browsers
    are so good that they can remember when a website supports encryption and
    even if you type in the website name, they'll use https.</p>

    <p>And if the network never redirects you to this page, well as you can
    see, you're not missing much.</p>

    </div>
    </div>

    </body>
</html>
* Connection #0 to host 10.0.2.15 left intact

HTTPS proxying not working

$ curl -k -v -x 10.0.2.15:10000 https://www.google.com
* Rebuilt URL to: https://www.google.com/
*   Trying 10.0.2.15...
* TCP_NODELAY set
* Connected to 10.0.2.15 (10.0.2.15) port 10000 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive
>
... times out eventually

*Config*:
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.envoy_proxy.name }}-config"
  namespace: {{ .Values.namespace }}
  labels:
    config: "{{ .Values.envoy_proxy.name }}-config"
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: dynamic_forward_proxy_cluster
                  - match:
                      connect_matcher:
                        {}
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      upgrade_configs:
                        - upgrade_type: CONNECT
                          connect_config:
                            {}
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: V3
                  with_request_body:
                    max_request_bytes: 8192
                    allow_partial_message: true
                  failure_mode_allow: false
                  grpc_service:
                    google_grpc:
                      target_uri: opa:9191
                      stat_prefix: opa
                    timeout: 10s
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_lookup_family: V4_ONLY
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              http_protocol_options: {}
              upgrade_configs:
                - upgrade_type: CONNECT
      clusters:
      - name: dynamic_forward_proxy_cluster
        connect_timeout: 1s
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY

* *

**Comment by rohrit** [comment]
Any clues as to why OPA does not get called for HTTP CONNECT requests? Is there any obvious issue with the configuration used. Any help would be greatly appreciated!

**Comment by bkaimal** [comment]
@mattklein123 , i observed that the HTTP CONNECT requests are not passed to ext_authz filters only GET is sent. This is probably expected but was not sure, so thought to check. For Lua filters, i do see the filter get all the requests.

**Comment by rohrit** [comment]
@mattklein123 , i observed that the HTTP CONNECT requests are not passed to ext_authz filters only GET is sent. This is probably expected but was not sure, so thought to check.

**Comment by rohrit** [comment]
there is probably an issue here but it was not confirm hence closing.
