### ISSUE TITLE
Add (more) unit tests for python tooling

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15453]
### description

some of the python tooling could do with some unit tests. 

there are some tests already, but some code has no tests and is not necessarily triggered during a ci run so can be broken without detection (cf #15427 )

i would suggest using pytest as a general approach

related #15403

**Comment by yashwant121** [comment]
Hi @phlax 
Can I work on this issue?

**Comment by phlax** [comment]
hi @yashwant121 - yep that would be great

i think the `tools/dependency/release_dates.py` requires some tests

are you familiar with using pytest already ? and bazel ?

**Comment by yashwant121** [comment]
I have some experience of adding coverage via Gtest, in cpp, Learning abt pytest & bazel will be fun.

**Comment by phlax** [comment]
k - so probably the initial challenge is getting the test runner in place.

as pytest is not currently used in the envoy codebase we dont have a working example/setup to copy from.

perhaps i should raise a PR to add a test runner and then you can pick my commit once its working ?

**Comment by yashwant121** [comment]
that's great.

**Comment by phlax** [comment]
give me a day or so to add the PR and i will ping you

**Comment by phlax** [comment]
@yashwant121 i have been working on this but havent quite figured out a good pattern yet - apologies for delay

**Comment by yashwant121** [comment]
its alright @phlax, thanks for the efforts. I can wait :p

**Comment by phlax** [comment]
@yashwant121 the framework for testing has been added as well as some generic base classe - probs to add missing tests we also want to update the tools

if you are still interested in helping with this im happy to provide some pointers

probs easiest thing is to jump on the envoy-dev slack channel and we can discuss further

**Comment by yashwant121** [comment]
Hi @phlax, thanks for the initial work on this. I will setup my envoy slack channel and will ping you there in case stuck. Thanks!

**Comment by phlax** [comment]
the newer pattern uses `envoy_py_binary` for python bazel targets - this auto creates a pytest runner

see the [README](https://github.com/envoyproxy/envoy/blob/main/tools/README.md) for how to use and set up a python target

the README probs needs work so any feedback on it would be great

the release_dates target will need to be updated to use either a Runner or Checker

**Comment by phlax** [comment]
tooling is now moved to https://github.com/envoyproxy/pytooling and has high test/coverage
