### ISSUE TITLE
docs: Improve error output for config validation

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#15456]
https://dev.azure.com/cncf/envoy/_build/results?buildId=68915&view=logs&jobId=a9c3f16a-7a41-5cb0-a55b-0d11e9c98c50&j=a9c3f16a-7a41-5cb0-a55b-0d11e9c98c50&t=044b2326-1800-5bcd-b44b-584adc5b0b85

failed due to validation of included YAML snippets, but the errors appear in the middle of the output, making it not obvious where the error was. Ideally we can bring this error message closer to the end of the output, or at least indicate what failed at the end.

@phlax

**Comment by phlax** [comment]
related #15313
