### ISSUE TITLE
Envoy is interrutped and exits immediately when handling multiple (sigterm) signals

### ISSUE THREAD

**Issue by caoyukun0430** [envoyproxy/envoy#15467]
*Title*: *Envoy exits immediately when handling multiple (sigterm) signals, instead of waiting for the handling of the first signal to finish.*

*Description*:
We use envoy with istio 1.8.3 and we know that there is issue in Isitio/Envoy that during worker node reboot, envoy can't be gracefully terminated https://github.com/istio/istio/issues/28738.
https://github.com/envoyproxy/envoy/blob/d753c8ef017c8c8d59f001b4ec4f75b711553a0b/source/server/server.cc#L616-L619
So we did custom implementation to solve this by adding sleep() function with same drain_duration as istio pilot-agent, in this case, both pilot-agent and istio will align on the graceful termination duration in node reboot/ pod deletion scenario.
```
 sigterm_ = dispatcher.listenForSignal(SIGTERM, [&instance]() {
      ENVOY_LOG(warn, "caught SIGTERM");
      ENVOY_LOG(warn, "Envoy graceful termination period is {}s, starting...", drain_duration);
      sleep(drain_duration);
      ENVOY_LOG(warn, "Envoy graceful termination period {}s completed.", drain_duration);
      instance.shutdown();
    });
```

But when actually testing reboot scenario, since all processes in containers receives SIGTERM from Linux at the same time, we found out that envoy receives SIGTERM signals two times(once from Linux, once from pilot-agent forwarding). 
In this case, the **unexpected behavior** happens, i.e. the second SIGTERM signal immediately exits/kills envoy even if the envoy dispatcher is still handling the first SIGTERM (meaning when it's in sleep(drain_duration)).

In the following example log, we use the default drain duration 5s. When I kill process 16 (envoy) two times very quickly, in the bash, we see in the log that
1. the sleep function is **interrupted in less than one sec 19:05:34- 19:05:35**, which is the time I did two "kill 16"
2. the **second SIGTERM is not even handled by the dispatcher**(since the log "caught SIGTERM" shows up only once.)
```
$ kubectl exec -ti client-7c954c6bf4-mzxh7 -c istio-proxy -n testcase01 -- bash
bash-4.4$ ps -auxwwf
## COMMENT: Here I removed other processes from the log(e.g. pilot-agent, ...)##
istio-p+     16  0.3  0.3 187592 53768 ?        Sl   19:04   0:00  \_ /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster client.testcase01 --service-node sidecar~172.17.0.20~client-7c954c6bf4-mzxh7.testcase01~testcase01.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --log-format-prefix-with-location 0 --log-format %Y-%m-%dT%T.%fZ.%l.envoy %n.%v -l info --component-log-level misc:error --concurrency 2
bash-4.4$ kill 16
bash-4.4$ kill 16
bash-4.4$ command terminated with exit code 137
$ kubectl logs client-7c954c6bf4-mzxh7 -c istio-proxy -n testcase01 --tail=20 -f
2021-03-12T19:04:25.947525Z	info	Envoy proxy is ready
2021-03-12T19:05:24.615077Z	info	envoy main	shutting down parent after drain
2021-03-12T19:05:34.688546Z	warning	envoy main	caught SIGTERM
2021-03-12T19:05:34.688727Z	warning	envoy main	Envoy graceful termination period is 5s, starting...
2021-03-12T19:05:35.350796Z	warning	envoy main	Envoy graceful termination period 5s completed.
2021-03-12T19:05:35.350819Z	info	envoy main	shutting down server instance
2021-03-12T19:05:35.350881Z	info	envoy main	main dispatch loop exited
2021-03-12T19:05:35.354746Z	error	sds	Remote side closed connection
2021-03-12T19:05:35.354496Z	error	sds	Remote side closed connection
2021-03-12T19:05:35.354988Z	info	xdsproxy	disconnected from XDS server: istiod.istio-system.svc:15012
2021-03-12T19:05:35.354072Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2021-03-12T19:05:35.354391Z	warning	envoy config	StreamSecrets gRPC config stream closed: 13, 
2021-03-12T19:05:35.354406Z	warning	envoy config	StreamSecrets gRPC config stream closed: 13, 
2021-03-12T19:05:35.356757Z	info	envoy main	exiting
2021-03-12T19:05:35.363014Z	info	Epoch 0 exited normally
2021-03-12T19:05:35.363038Z	info	No more active epochs, terminating

```
The reason we think could be when envoy main thread(dispatcher) is occupied by the first SIGTERM signal, it can't listen/ handle for other signals, so when more signals arrives, it immediately exits. But we can't explain the reason.
But we tried to simulate the same signal handling process on linux system generally. When the process is handling one signal, it will not be interruptted by other signals.

*Expected Behavior*
Take the simple example-handler.cpp I shared as an example, since the handler is still dealing with the first SIGINT(sleeping 30s here), the following multiple SIGINT signals can't interrupt it. 
```
$ ./test_signal
Going to sleep....
Going to sleep....
Going to sleep....
Going to sleep....
^CInterrupt signal (2) received.
sleep 30s....
^C^C^C^C^C
done
```
[example-handler.txt](https://github.com/envoyproxy/envoy/files/6132533/example-handler.txt)

So the behavior in envoy really differs, when the second SIGTERM or SIGINT comes, the handling of first signal is killed immediately!
It looks to us that this is the bug in envoy signal handling. Or can you explain why in envoy, multiple signals will force envoy to exit immediately, instead of the behaviors we see in linux as the exmple code I shared?

*Repro steps*:
As you see, to reproduce, first a few lines of code needs to be added into SIGTERM handling, but it's not hard to undetstand.
And to deploy istio with the updated envoy binary which has the code changes. In any sidecar with envoy proxy you can witness the behavior.

*Admin and Stats Output*:
n/a

*Config*:
n/a

*Logs*:
As shown above.

*Call Stack*:
n/a

**Comment by hobbytp** [comment]
@caoyukun0430 The sleep function will be interrupted by signal, and dispatcher does not disable signal, that is why the 2nd signalterm interrupt the sleep function.

**Comment by caoyukun0430** [comment]
Thanks @hobbytp for the explanation! 
So the reason is that dispatcher handles signals asynchronously. it generates event to dispatch the queue and then returns so that the following signals can be handled.  But sleep function will be interrupted by the following signals. 
Our workaround is to apply a while loop to force the envoy to continue waiting/sleeping until drain duration reaches. 

But this is not a bug in envoy and I will close the issue now!
Although I hope Envoy could support graceful termination in node reboot scenario in the future!

/Yukun
