### ISSUE TITLE
Custom headers are all converted to lowercase

### ISSUE THREAD

**Issue by sunnoy** [envoyproxy/envoy#15477]
*Title*: *Custom headers are all converted to lowercase*

*Description*:
https://github.com/istio/istio/issues/31360

Does envoy support this ？

**Comment by wbpcode** [comment]
Nope. And as @howardjohn said, at this point, fixing the application to ensure that it is case insensitive would be a little better.

**Comment by jmarantz** [comment]
Duplicate of https://github.com/envoyproxy/envoy/issues/14363
