### ISSUE TITLE
[enhancement] Customize the rejection code and information of the access denied (RBAC)

### ISSUE THREAD

**Issue by wzshiming** [envoyproxy/envoy#15488]
Discussion https://github.com/istio/istio/issues/31452

*Description*:

Customize the rejection code and information of the access denied (RBAC).

*User Story*:

In a public cluster,  Istio to isolate different tenants so that they are invisible to each other, want to hide the existence of the workload from the access by presenting 404.

**Comment by wzshiming** [comment]
https://github.com/envoyproxy/envoy/blob/031f75dd113e2f7be41b94a0365145e7bf1e6c12/api/envoy/config/rbac/v3/rbac.proto#L110-L140

Maybe need to add a field, but I'm not sure about the process and how to do it properly.

**Comment by snowp** [comment]
I believe you can use the https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply feature to rewrite the local reply sent by the rbac filter.

**Comment by wzshiming** [comment]
Thanks, It sounds like it should work, let me try.

**Comment by yangminzhu** [comment]
The `local_reply` in HCM should work. 

I feel it might worth to still add first-class supports in the RBAC filter for customizing the local response?
One benefit is it could potentially give more flexibility, for example, different response for different RBAC rules, embed policy name in response for debugging purpose. Just commenting the idea here for some more comments from the community.

**Comment by wzshiming** [comment]
PING @snowp
