### ISSUE TITLE
Override createRouteSpecificFilterConfig in kill_request http filter

### ISSUE THREAD

**Issue by xiaobinxbw** [envoyproxy/envoy#15499]
When kill_request http filter is passed in as the route level typed_filter_config, the error below is detected:
<img width="1341" alt="Screen Shot 2021-03-15 at 2 37 34 PM" src="https://user-images.githubusercontent.com/78503218/111224665-029a6f80-859c-11eb-836f-f75ed1528a07.png">

As per the troubleshooting result, createRouteSpecificFilterConfig needs to be overriden in https://github.com/xiaobinxbw/envoy/blob/main/source/extensions/filters/http/kill_request/kill_request_config.cc to avoid this error.

**Comment by xiaobinxbw** [comment]
cc @stevenzzz

**Comment by stevenzzzz** [comment]
cc @stevenzzzz

**Comment by derekargueta** [comment]
Seems this ticket was completed with https://github.com/envoyproxy/envoy/pull/15503 ?
