### ISSUE TITLE
Add http_pattern_matcher as dependency for envoy dataplane_core

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#15506]
This is for [#15299](https://github.com/envoyproxy/envoy/pull/15299) to address[ #7763](https://github.com/envoyproxy/envoy/issues/7763)

This issue replaced issue https://github.com/envoyproxy/envoy/issues/15304

Description:
url_template is implemented in this http_pattern_matcher [repo](https://github.com/google/http_pattern_matcher)
In order to support url_template in RouteMatch, need to add this repo as envoy dataplane_core dependency.

Actually, this  http_pattern_matcher [repo](https://github.com/google/http_pattern_matcher) split from [grpc_httpjson_transcoding](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding).  Just moved path_matcher related code to the new repo.

**Comment by qiwzhang** [comment]
@envoyproxy/dependency-shepherds @envoyproxy/security-team

**Comment by qiwzhang** [comment]
We have added CI and fuzz tested into this repo.  

@moderation could you help to score it?

**Comment by moderation** [comment]
Even though I can see the fuzzing added to the repo the score is unchanged - https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/commit/0b74abcd88a5df3ca2f1b0fe59e32df0eb930561. The fuzzing check is at https://github.com/ossf/scorecard/blob/main/checks/fuzzing.go and I think you need to follow some more steps including adding a `project.yaml` file documented at https://google.github.io/oss-fuzz/getting-started/new-project-guide/#creating-the-file-structure
```
RESULTS
-------
Active: Pass 10
Branch-Protection: Fail 0
CI-Tests: Fail 5
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Pass 10
Frozen-Deps: Fail 5
Fuzzing: Fail 10
Packaging: Fail 0
Pull-Requests: Pass 10
SAST: Fail 10
Security-Policy: Pass 10
Signed-Releases: Fail 0
Signed-Tags: Fail 0
```

**Comment by qiwzhang** [comment]
@moderation were you checking grpc_httpjson-transcoding repo?   If so,  it is wrong.  We should check http_pattern_matcher [repo](https://github.com/google/http_pattern_matcher) under google.

**Comment by moderation** [comment]
Yes! Wrong repo. `scorecard --repo=https://github.com/google/http_pattern_matcher`
```
RESULTS
-------
Active: Pass 10
Branch-Protection: Fail 0
CI-Tests: Fail 10
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Pass 10
Frozen-Deps: Fail 5
Fuzzing: Fail 10
Packaging: Fail 0
Pull-Requests: Fail 4
SAST: Fail 10
Security-Policy: Pass 10
Signed-Releases: Fail 0
Signed-Tags: Fail 0
```
Your CI and Fuzzing are not being picked up by the OSS Scorecard

**Comment by qiwzhang** [comment]
@nareddyt could you help to check with CI and Fuzzing not been picked up?

**Comment by nareddyt** [comment]
I assume fuzzing will be picked up once https://github.com/google/oss-fuzz/pull/5427 is merged.
Not sure why CI is not detected. We are using prow, which is listed as a supported system in the documentation: https://github.com/ossf/scorecard/blob/main/checks.md#ci-tests

**Comment by qiwzhang** [comment]
Hi @moderation, could you re-run the score card for this rero?

**Comment by qiwzhang** [comment]
@envoyproxy/dependency-shepherds @envoyproxy/security-team

Can you approve this proposal?   Thanks
