### ISSUE TITLE
Question: What is the maximum number of routes

### ISSUE THREAD

**Issue by obeleh** [envoyproxy/envoy#15512]
We're using Envoy 15.3 with XDS cluster configuration. 12 vhosts and 1663 routes per vhost. It's for a migration project and that number should go down later. Before that we had a lot fewer routes. We noticed that the first `232` routes work but the rest didn't. I googled a lot but I couldn't find any indication what the limit with regards to configuration are. I tried reading a bit of the C++ code but couldn't find it there. But that's not a good indication of whether it is there or not :P 

So my question is, what technical limits does Envoy have? All I could find are connection based limitations which I get is important for a proxy. But what are the configuration limitations or where could I find them?

**Comment by mattklein123** [comment]
There is no explicit limit on the number of routes, other than memory usage and the fact that right now route picking is a linear FIFO scan.
