### ISSUE TITLE
~GrpcMuxWatchImpl() uses watches_.remove(this) which traverses the list.

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#15528]
*Title*: ~GrpcMuxWatchImpl() uses watches_.remove(this) which traverses the list.

*Description*:

~GrpcMuxWatchImpl() uses std::list::remove() to remove itself from `watches_` list. 
This traverses the list and takes O(N) for each destruction.
We could speed things up to O(1) if GrpcMuxWatchImpl would keep a list iterator for itself and used std::list::erase() instead.

**Comment by stevenzzzz** [comment]
cc @htuch @chaoqin-li1123 @stevenzzzz

**Comment by stevenzzzz** [comment]
let's do similar trick as is done in https://github.com/envoyproxy/envoy/pull/11751

**Comment by stevenzzzz** [comment]
cc @htuch 
cc @chaoqin-li1123

**Comment by chaoqin-li1123** [comment]
Yeah, I think we can store the list iterator and use it for constant time removal.

**Comment by htuch** [comment]
Sure, makes sense.

**Comment by mk46** [comment]
I am taking this. PTAL to linked PR.
