### ISSUE TITLE
routes timeout is ignored if we set max stream duration

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#15530]
It looks like when we set `timeout` at route and specify `max_stream_duration` for ` grpc_timeout_header_max`  Envoy is ignoring the timeout value and never timing out the route because max_stream_duration's max_stream_duration is not set for http1 requests. Is this intended behaviour?

Here is the route config
```
 "route": {
           "cluster": "outbound|80||httpbin.org",
           "timeout": "3s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_stream_duration": {
            "grpc_timeout_header_max": "3s"
           }
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/httpbin-ext"
            }
           }
          },
          "decorator": {
           "operation": "httpbin.org:80/*"
          }
         }
        ],
        "include_request_attempt_count": true
       },
       
```
In this case, we are expecting http1 requests to honour the timeout specified. But the http1 requests never timeout.

Is this intended behaviour? If it is I think it is very confusing and not clear from the documentation that it is how timeouts work with the new fields.

Should n't it honour timeout if MaxStreamDuration's MaxStreamDuration is not set at all?

**Comment by ramaraochavali** [comment]
@alyssawilk thoughts?

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L157 - Specifically this is not set if usingNewTimeouts i.e. MaxStreamDuration is set.

**Comment by ramaraochavali** [comment]
Looking at the original API PR https://github.com/envoyproxy/envoy/pull/13018 - looks like its primarily intended for grpc timeouts and streams. It accidentally changing the behaviour of the original `timeout` field for http requests seems to be undesirable atleast from what I understand from the conversation.

@snowp @mattklein123 @htuch Is that correct or it is intentional that we when we specify `MaxStreamDuration` the top level message with just `grpc-timeout` it does not honour the `timeout` value for http requests also?

**Comment by jmarantz** [comment]
@adamsjob FYI

**Comment by mattklein123** [comment]
@ramaraochavali yeah I agree this is a bug. Can you work on a proposed fix?

**Comment by markdroth** [comment]
This sounds like a bug to me as well.  We probably missed this case in #13302.
