### ISSUE TITLE
Occasional openssl flake in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15555]
### description

there is sometimes failures generating ssl certificates, eg:

```
2021-03-17T19:02:51.9734549Z Can't load /home/vsts/.rnd into RNG
2021-03-17T19:02:51.9735432Z 140516289237440:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/vsts/.rnd
```

not sure what the cause is but perhaps an openssl bug 

if it is the same as described here:

https://github.com/openssl/openssl/issues/7754#issuecomment-598808341

then doing:

```
touch ~/.rnd
```

before generating the certifcates seems to fix

**Comment by mk46** [comment]
Is this failing only in `verify example`?

**Comment by phlax** [comment]
as far as i have seen - yep

**Comment by phlax** [comment]
here is an example fail on the post-submit queue

https://dev.azure.com/cncf/envoy/_build/results?buildId=69466&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=2073

**Comment by asraa** [comment]
I see this issue in https://github.com/envoyproxy/envoy/pull/15263
but I've re-ran about 6-7 times now with no luck on success. It says that grpc-bridge is failing, any advice for debugging?

**Comment by phlax** [comment]
so further info re this bug

- it doesnt happen when i run the examples locally
- it happens on every ci run - even those that pass

im going to add the `touch` workaround to see if that makes a difference...
