### ISSUE TITLE
listener: replacing a listener with same port but TCP -> UDP crashes

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#15562]
The following code needs to take into account TCP vs. UDP otherwise we end up trying to create a new TCP listener for a UDP configuration.

https://github.com/envoyproxy/envoy/blob/9a89e312432de6ce26b9e125e4711d4445f9f2c3/source/server/listener_manager_impl.cc#L502-L509

**Comment by mattklein123** [comment]
This is a follow on from the issue reported here: https://github.com/envoyproxy/envoy/issues/12043#issuecomment-801862107 by @zarianec. 

cc @lambdai FYI

**Comment by lambdai** [comment]
I see... I guess we can reject new listener config if tcp listener and udp listener cannot use the same port.
Or find listener by both L4 address and L4 protocol

**Comment by mattklein123** [comment]
> Or find listener by both L4 address and L4 protocol

Yeah I think ^. IMO it's fine to have different protocols on the same port.
