### ISSUE TITLE
Question: Is there are any way to determine whether is a terminal filter at runtime?

### ISSUE THREAD

**Issue by qinggniq** [envoyproxy/envoy#15565]
*Title*: *Is there are any way to determine whether is a terminal filter at runtime*

*Description*:
Put `is_terminal` flag at proto file, and return deferent filter logic base on the flag.

**Comment by snowp** [comment]
What do you mean by runtime here? I believe the terminal filter check is for a config load check to prevent people from putting a terminal filter in the middle of their filter chain, so I'm not sure if being able to change this on a per request basis would be helpful?

**Comment by qinggniq** [comment]
@snowp  Sorry for not fully explained, recently I make a exist filter from non-terminal filter to terminal filter in this pr #15485 because the new feature require the filter to maintain connection, for api backward compatibility, it's not accepted. So I'm trying to find out a way to make it backward compatible, I'm trying to add a  `is_terminal` field to control whether this filter is a terminal filter, when `is_terminal` is false, the filter works as before, when is true, the filter works with new features.

**Comment by qinggniq** [comment]
@snowp Maybe a stupid question, can I make `is_terminal` to be a filed of my filter factory,  and determine it's value when call `createFilterFactoryFromProto`, then change the sequence of *validateTerminalFilters* and *createFilterFactoryFromProto* in the related function like https://github.com/envoyproxy/envoy/blob/a240824c376693b16ca8be51e435b95c42f3449f/source/server/listener_manager_impl.cc#L108-L115 ?

**Comment by snowp** [comment]
I think there are two main options: what you said to pass additional information to `isTerminal` or have this new filter functionality of yours be configured via a different config type, allowing you to use a different factory.

@alyssawilk any thoughts here?

**Comment by alyssawilk** [comment]
yeah, this seems an invasive enough change I wonder if it'd be easier to clone and support both for the deprecation window.  If not having config for old mode vs new seems reasonable.

**Comment by qinggniq** [comment]
I think adding a new method `virtual bool isTerminalByConfig(const Protobuf::Message& proto_config, Server::Configuration::FactoryContext& context)` to `NamedHttpFilterConfigFactory` like below:
```cpp
class NamedHttpFilterConfigFactory : public ProtocolOptionsFactory {
...
virtual
/**
   * @return bool true if this filter must be the last filter in a filter chain, false otherwise. mark it as deprecated.
   */
  virtual bool isTerminalFilter() { return false; }
/**
   * @return bool true if this filter must be the last filter in a filter chain, false otherwise, dynamic determined by config
   */
  virtual bool isTerminalFilterByConfig(const Protobuf::Message&, Server::Configuration::FactoryContext&) { return isTerminalFilter();}
};
```
And replace `isTerminalFilter()` call with `isTerminalFilterByConfig(message, context)`, that will not affect the current implementation of other filters and give ability to determine a filter whether is terminal at runtime. WDYT?

**Comment by alyssawilk** [comment]
Yeah, I think that's fine, though I'd lean towards just replacing isTerminalFilter entirely, having isTerminalFilterByConfig return false by default and updating our internal filters.

**Comment by qinggniq** [comment]
> Yeah, I think that's fine, though I'd lean towards just replacing isTerminalFilter entirely, having isTerminalFilterByConfig return false by default and updating our internal filters.

I'm not sure whether some users might implement their own filters in the meanwhile implement `isTerminalFilter`, replace `isTerminalFilter` entirely might cause their filters to be fail to build. A well known case is that in
 https://github.com/envoyproxy/envoy-filter-example/blob/8f0f8bba38868e875613b74f57df38f543e764ba/echo2_config.cc#L30 
, we need modify *envoy-filter-example* repo at the same time, but it all up to you.

**Comment by alyssawilk** [comment]
I'm fine with it being multi-phase but for now include is not expected to be backwards compatible and I'd prefer to not have cruft and potentially confusing multiple APIs in the long run.

cc @mattklein123 @snowp for thoughts (on retaining both isTerminalFilter and isTerminalFilterByConfig in the long run)

**Comment by mattklein123** [comment]
Sorry I don't fully understand the use case. The issue is there is a private filter which has to support both terminal and non terminal modes and we want config to drive that?

**Comment by alyssawilk** [comment]
context: https://github.com/envoyproxy/envoy/pull/15485
changing the msql proxy to support terminal and non-terminal

**Comment by mattklein123** [comment]
OK thanks. Yeah I would be fine just replacing `isTerminal` and adding params.
