### ISSUE TITLE
Prefer values in URL over values in request body

### ISSUE THREAD

**Issue by Asdprom** [envoyproxy/envoy#15599]
I have a gRPC service with a method declared, for example, like this
```
service UserService
{
	rpc CreateUser(CreateUserRequest) returns (google.protobuf.Empty) {
		option (google.api.http) = {
			put: "/v1/users/{UserId}"
			body: "*"
		};
	}
}

message CreateUserRequest{
	int32 UserId = 1;
        ...
}
```
Envoy is configured exactly like in [sample](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration) config, except some ports, service names and addresses.

I am sending the following request:
```
PUT http://localhost:9090/v1/users/10
```
and request body:
```
{
  "UserId": 20,
  ...
}
```
In result, gRPC service recieves `UserId` value of 20.
And I wanted to know, is there any way to change this behaviour to prefer values in URL over request body ones?

**Comment by mattklein123** [comment]
cc @qiwzhang

**Comment by Asdprom** [comment]
Any update on this one?
