### ISSUE TITLE
Can envoyproxy run as a dynamic HTTPS terminating transparent proxy

### ISSUE THREAD

**Issue by filipdavidovic** [envoyproxy/envoy#15598]
Hi,

I am currently running Envoy as a transparent proxy. I use the `iptables -j TPROXY` feature to route requests to Envoy, log them, and finally forward them to the original destination. This works like a charm for HTTP and TCP. I'd like to do the same for TLS secured traffic as well.

In order to inspect all traffic, I need Envoy to establish a TLS connection with the downstream and a TLS connection with the upstream. In order to establish an appropriate TLS connection with the downstream, I need Envoy to present a valid certificate for the hostname the downstream is requesting. Since the hostname can be **anything**, I need Envoy to dynamically generate the certificate upon seeing the SNI. Note that I can trust an arbitrary CA certificate on the downstream so that Envoy-generated certificates are considered valid.

This feature is similar to what [mitmproxy is offering](https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#transparent-https). I am aware that this can be done by generating one wildcard certificate which matches everything, i.e. `CN=*`, but I am looking for something more rebust and "secure".

**Can Envoy act as a dynamic HTTPS terminating transparent proxy?** If such a feature is not available for Envoy, I might be available to implement it myself. I would need pointers on where to start since I am not fully familiar with Envoy's codebase.

Thank you!

**Comment by lambdai** [comment]
> I need Envoy to dynamically generate the certificate upon seeing the SNI.

If you can foresee the SNI before the connection arrives(and hopefully the space of the SNI is not too huge), you can pre-generate the certs and bind each cert with a network filter chain and attach a FilterChainMatch. FilterChainMatch has the server name field so that the connection with the correct cert can be created.

There is not yet a dynamic cert generation at the connection serve phase.

There was a filter chain discovery service (FCDS) which can be extended to be `ondemand`. But AFAIK the known use case in the past doesn't involve a cert dynamic generation.

**Comment by filipdavidovic** [comment]
@lambdai Thank you for the answer. I cannot foresee the CNI before it arrives. The idea is to have Envoy be completely dynamic and agnostic of the upstream. I think I will opt for a "super certificate" using wildcards and hope that it covers the whole CNI space.

**Comment by filipdavidovic** [comment]
@lambdai I will put my thoughts and understandings from researching about the potential solution. As it stands, I don't think dynamic certificate generation is possible with Envoy. 

Whenever Envoy gets a new packet/request I want it to read the SNI and ask a configuration server for a secret/listener for that specific SNI. Neither of the following features can solve my problem because they don't query the server on per-request basis, but poll the server for changes. Since I don't know the SNI beforehand, I cannot give Envoy the configuration before a request is made.

There are two features that I looked into:
1. [Secret Discovery Service (SDS)](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret)
    - SDS is intended to be used for managing secrets, such as TLS certificates and keys, so it seemed interesting.
2. [xDS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration) and more precisely [LDS](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/lds#config-listeners-lds)
    - LDS supports changing only its filter chains without draining the listener ([source](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/network_filter_chain#filter-chain-only-update)).

I see that you've mentioned that LDS/FDS can be configured to be `ondemand` and I imagine this is exactly what I'm looking for. This could potentially make option 2 work. However, I could not find anything about this in the documentation. Could you give me a pointer or an example configuration on where I could look?

Thank you!
