### ISSUE TITLE
Asserts are causing gcc pipeline to fail but not linux_x64

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#15618]
I observe that in run [69927](https://dev.azure.com/cncf/envoy/_build/results?buildId=69927&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec)

https://github.com/envoyproxy/envoy/blob/0d9e808910ae6a85b5bb501a8b2584e29af86147/source/server/transport_socket_config_impl.h#L46

is causing a test failure in `gcc` but not `linux_x64`

Is this expected?

**Comment by mattklein123** [comment]
Possibly a timing issue?

**Comment by mattklein123** [comment]
Or does it repro every time? Does the GCC build not enable asserts?
