### ISSUE TITLE
How does envoy respond after receiving a packet from the listener 127.0.0.1:15001 

### ISSUE THREAD

**Issue by sunnoy** [envoyproxy/envoy#15625]
*Title*: *How does envoy respond after receiving a packet from the listener 127.0.0.1:15001*

*Description*:
client IP <22.168.15.38> -> svc ip <21.100.85.147>

The first socket is  `22.168.15.38:49104->21.100.85.147:1989` to send [syn]

iptables redirect

```bash
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001 
```

then the socket is  `22.168.15.38:49104->127.0.0.1:15001` to send [syn]

The socket that the client expects to receive is `21.100.85.147:1989->22.168.15.38:49104` , to req [syn+ack]

See the existence of this package by capturing the package

![image](https://user-images.githubusercontent.com/19342276/112112574-aa451c80-8bf0-11eb-8ceb-3ab14773d5d9.png)

How does envoy make this?

The documentation says:

https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_dst_filter
```bash
Original destination listener filter reads the SO_ORIGINAL_DST socket option set when a connection has been redirected by an iptables REDIRECT target, 
or by an iptables TPROXY target in combination with setting the listener’s transparent option.
```

Saw the relevant code:

```c++
  sockaddr_storage orig_addr;
  memset(&orig_addr, 0, sizeof(orig_addr));
  socklen_t addr_len = sizeof(sockaddr_storage);
  int status;

  if (*ipVersion == Address::IpVersion::v4) {
    status = sock.getSocketOption(SOL_IP, SO_ORIGINAL_DST, &orig_addr, &addr_len).rc_;
  } else {
    status = sock.getSocketOption(SOL_IPV6, IP6T_SO_ORIGINAL_DST, &orig_addr, &addr_len).rc_;
  }
```

is envoy extracts the original destination address from the socket option SO_ORIGINAL_DST, and then creates the following socket: `21.100.85.147:1989->22.168.15.38:49104 `,returned to the client?

or

is envoy uses the packet-back mechanism of iptables redirection ?

**Comment by lambdai** [comment]
> is envoy extracts the original destination address from the socket option SO_ORIGINAL_DST, 
Yes
> and then creates the following socket: 21.100.85.147:1989->22.168.15.38:49104 ,returned to the client?
No. Envoy would consider the accepted socket has local address `21.100.85.147:1989` and then relooks up the listeners with options `bind_to_port=false`.

**Comment by sunnoy** [comment]
@lambdai  You seem to have misunderstood my question，My question is how the socket `21.100.85.147:1989->22.168.15.38:49104`  seen by the client was generated during the three-way handshake,packet 6 in wirshark

**Comment by sunnoy** [comment]
it use conntrack 

```bash
[NEW] tcp      6 120 SYN_SENT src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 [UNREPLIED] src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248
[UPDATE] tcp      6 60 SYN_RECV src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248
[UPDATE] tcp      6 432000 ESTABLISHED src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248 [ASSURED]
[UPDATE] tcp      6 120 FIN_WAIT src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248 [ASSURED]
[UPDATE] tcp      6 30 LAST_ACK src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248 [ASSURED]
[UPDATE] tcp      6 120 TIME_WAIT src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248 [ASSURED]
[DESTROY] tcp      6 src=22.0.68.108 dst=21.0.196.116 sport=46248 dport=8080 src=127.0.0.1 dst=22.0.68.108 sport=15001 dport=46248 [ASSURED]
```
