### ISSUE TITLE
Support generic CSDS types 

### ISSUE THREAD

**Issue by su225** [envoyproxy/envoy#15622]
*Title*: *Support generic CSDS types*

*Description*:
Currently, Client Status Discovery Service supports only 5 types of config status listed below
* Listener Config
* Cluster Config
* Route Config
* Scoped Route Config
* Endpoint Config

However, more features were added to envoy like _Extension Configuration Discovery Service_ (ECDS). Besides this, some projects like Istio add additional xDS types like the ones below
* NDS for sidecar DNS resolution
* PCDS - Proxy config discovery

Given this scenario, from Universal Data Plane API (UDPA) perspective, it makes sense to have a generic CSDS API which could be used when specific APIs are not yet available or when other projects implementing UDPA have their own xDS types. It looks similar to specific ones. Here is the (pseudo) protobuf of how it would look (not final, open for suggestions)
```proto
// admin.v3.GenericXdsConfigDump
message GenericXdsConfigDump {
    string type_url = 1;
    repeated google.protobuf.Any configs = 2; 
}
```

Then `PerXdsConfig` changes as shown below (1000 or large number because it is supposed to be the last one in the list)
```diff
// Detailed config (per xDS) with status.
// [#next-free-field: 8]
message PerXdsConfig {
  option (udpa.annotations.versioning).previous_message_type =
      "envoy.service.status.v2.PerXdsConfig";

  ConfigStatus status = 1;
  ClientConfigStatus client_status = 7 [deprecated = true];

  oneof per_xds_config {
    admin.v3.ListenersConfigDump listener_config = 2;
    admin.v3.ClustersConfigDump cluster_config = 3;
    admin.v3.RoutesConfigDump route_config = 4;
    admin.v3.ScopedRoutesConfigDump scoped_route_config = 5;
    admin.v3.EndpointsConfigDump endpoint_config = 6;
+   admin.v3.GenericXdsConfigDump generic_xds_config_dump = 1000;
  }
}
```

**Comment by lizan** [comment]
Sounds reasonable to me. cc @envoyproxy/api-shepherds

**Comment by markdroth** [comment]
Would it make more sense to just add a more generic and simpler message structure for CSDS, similar to what I suggested in https://github.com/envoyproxy/envoy/issues/14431#issuecomment-746728834?  We might even be able to migrate the existing types to this more generic structure over time.

**Comment by htuch** [comment]
Either this or #14431, agree with the idea of extending to opaque Any.

**Comment by su225** [comment]
@markdroth - Based on ideas from #14431 and looking around the PRs related to it, it can be enhanced without breaking lot of existing things. I'll create a PR for this. 
```proto
message GenericXdsConfigDump {
    string type_url = 1;
    repeated XdsResource configs = 2;
}

message XdsResource {
    string type_url = 1; // redundant :(
    string name  = 2;
    string version_info = 3;
    google.protobuf.Any xds_config = 4;
    google.protobuf.Timestamp last_updated = 5;
    UpdateFailureState error_state = 6;
}
```

**Comment by su225** [comment]
@markdroth @htuch @lizan - raised https://github.com/envoyproxy/envoy/pull/15760 . This is the first implementation. Once the API is refined, I'll copy it over to other API versions and add docs.

**Comment by su225** [comment]
Fixed formatting
