### ISSUE TITLE
Universal dynamic configuration capability

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#15643]
*Description*:
>It seems reasonable to add an universal dynamic configuration capability to Envoy. In addition to not support dynamic configuration and complex value types, I found that RTDS is very suitable for this feature.
>I have implemented a `DynamicRtdsSubscription class` which can accept RTDS resource subscriptions at runtime and call the binding callbacks when the resources update. Since the original RTDS value is a `Struct`, I can convert it to my self-defined type in the callbacks. It works for me and I'm wondering if this feature could be added to Envoy.

**Comment by snowp** [comment]
Can you speak a bit to the specific use case you have in mind? Between RTDS and ECDS we have plenty of options for dynamic configuration, so your use case might already be solved by them.

**Comment by WeavingGao** [comment]
I developed a universal component that can be used in L4 or L7 Filter or any other component. This universal component relies on complex dynamic configurations. These configurations have nothing to do with cluster or listener, so we found that RTDS is relatively suitable. Any other suggestions?
