### ISSUE TITLE
Support custom DNS resolvers in DNS cache used by DynamicForwardProxy filter

### ISSUE THREAD

**Issue by ntgsx92** [envoyproxy/envoy#15657]
*Support custom DNS resolvers in DNS cache used by DynamicForwardProxy filter*

*Description*:
>
Context:
We're trying out [Dynamic Forward Proxy filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy#arch-overview-http-dynamic-forward-proxy) to proxy HTTP requests to upstream clusters as a replacement for one of our internal service. One of the requirement for the new replacement is that it needs to be able to resolve DNS address dynamically via our own name resolution system. Additionally, we're building a DNS server that will talk to our custom name resolution system. However, we quickly found out that the DNS cache used by the filter only supports default DNS resolver(/etc/resolv.conf) which is not ideal if you would like to configure Envoy to talk to your own DNS resolver instead. 

What we're proposing:
Adding an optional config in DNS cache called `dns_resolvers` that will default using DNS servers from `/etc/resolv.conf` but can be overridden to a set of IP addresses if specified.

**Comment by mattklein123** [comment]
This sounds reasonable to me!

**Comment by malza321** [comment]
I'm really looking forward to it!

**Comment by ntgsx92** [comment]
pull request added

**Comment by ntgsx92** [comment]
pull request has merged. Resolving
