### ISSUE TITLE
Clang tidy fails in CI for dependabot

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15700]
### description

clang-tidy-diff is failing in CI for depenadabot although afaict the tidy script (ie from upstream) doesnt actually fail - it exits `0`  - so not obvious what is failing or why

example failure:

```
INFO: Elapsed time: 252.909s, Critical Path: 20.98s
INFO: 6872 processes: 1695 remote cache hit, 5177 internal.
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
INFO: Invocation ID: ab783acd-de6a-494d-a4d9-a1015f1bc5ef
Running clang-tidy-diff against da39f2aec26ad6aa645871def0401e88cf4cd21b (da39f2aec26ad6aa645871def0401e88cf4cd21b), current HEAD (9a41881eaf1966911252598d25abf9a3afa0258e)
No relevant changes found.
##[error]Bash exited with code '1'.
Finishing: Run CI script
```

This is the line in the upstream `clang-tidy-diff.py` that exits 0 printing "No relevant..."

https://github.com/llvm/llvm-project/blob/d92b4956d6db8904f6a21c0e037dd5161b843b87/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py#L199-L201

**Comment by phlax** [comment]
all of the dependabot prs failed on this - so there should be some clue there as to why it fails

something to do with the type of diff i guess

**Comment by phlax** [comment]
on further inspection this seems to be a problem only for dependabot - so defo to do with the type of diff which dependabot creates

not sure how best to track this - we could add some debugging to main and force one of the PRs to rebase i guess

**Comment by phlax** [comment]
cc @moderation

**Comment by lizan** [comment]
yeah it's weird to see those fails on clang tidy

**Comment by phlax** [comment]
even more wierdly - this one has passed #15729 - while others still seem to be failing

**Comment by lizan** [comment]
I found the reason... We use the last_github_commit.sh to determine the merge base, while the branch from dependabot is committed by GitHub, so it generates no diff and the script will fail. Will fix this soon.

**Comment by phlax** [comment]
this is fixed
