### ISSUE TITLE
Embedding MemBlockBuilder into the data representation for Buffer::Instance

### ISSUE THREAD

**Issue by rialg** [envoyproxy/envoy#15701]
*Description*:
As suggested by @jmarantz in #13770, having the BufferImpl, `OwnedImpl`,(and related classes - i.e.`Slice` - ) to store its raw data in members of the type `MemBlockBuilder` could improve memory safety at the class level.

**Comment by rialg** [comment]
Hi @jmarantz,

I have started to refactor the `Slice` class in `source/common/buffer/buffer_impl.h`. I wanted to check with you if replacing the `storage_` type would be a good start since doing so might imply that the `base_` attribute would have to be removed, as the reference to the beginning of the Slice can be store in the `MemBlockBuilder`'s `data_` member. wdyt?

```
diff --git a/source/common/buffer/buffer_impl.h b/source/common/buffer/buffer_impl.h
index 33b9bed..2112489 100644
--- a/source/common/buffer/buffer_impl.h
+++ b/source/common/buffer/buffer_impl.h
@@ -9,6 +9,7 @@
 
 #include "common/common/assert.h"
 #include "common/common/non_copyable.h"
+#include "common/common/mem_block_builder.h"
 #include "common/common/utility.h"
 #include "common/event/libevent.h"
 
@@ -33,10 +34,11 @@ namespace Buffer {
 class Slice {
 public:
 public:
   using Reservation = RawSlice;
-  using StoragePtr = std::unique_ptr<uint8_t[]>;
+  using Storage = MemBlockBuilder<uint8_t>;
 
   static constexpr uint32_t free_list_max_ = Buffer::Reservation::MAX_SLICES_;
-  using FreeListType = absl::InlinedVector<StoragePtr, free_list_max_>;
+  using FreeListType = absl::InlinedVector<Storage, free_list_max_>;
```

**Comment by jmarantz** [comment]
@antoniovicente @KBaichoo for visibility, as they are also looking at changes to BufferImpl for other reasons.

@rialg one thing we want to make sure that this change is "instruction-neutral" and "memory-layout-neutral" while adding better abstraction boundaries and strict control of use of memcpy. I *think* what you have achieves that but I just wanted to have Antonio & Kevin in the loop for this.

Having said that, to me, that looks like a good place to start for BufferImpl.

OTOH if there are other TODOs remaining from the prior PR it might be better to do those first. BufferImpl is one of the more important and performance-critical components of the data plane.

**Comment by rialg** [comment]
The PR #15722 was created to keep track of the changes for this issue. Atm, I've only applied the patch for `mem_block_builder.h` which was taken from the previous PR.

My plan is to modify other classes to use the `MemBlockBuilder` resource mgmt objects, such as BufferImpl, as previously agreed. wdyt?

**Comment by KBaichoo** [comment]
IIUC the situation correctly, the main types you'd actually want to target is the `Storage` (a byte array) and `Slice`. Right now the `Storage` abstraction is just an array of bytes multiple of 4k and the `Slice` contains most of the "brains" (which section writable, capacity, etc.) 

It might be awkward having some logic spewed across both the `Slice` and `MemBlockBuilder`s. I think if you're able to create clear boundaries using `MemBlockBuilder`, this could work. 

Some other considerations include:
* Some slices don't own their storage (i.e. more akin to string_view)
* Prepend is an operation we'd also need to support
* There's a freelist of `Storage` object, and having `MemBlockBuilder` interoperate with that

**Comment by antoniovicente** [comment]
I think that doing low level operations on buffers and operations like memcpy on a class like BufferImpl is acceptable.  This code has high test coverage and has received the attention required to ensure that the low level operations in use there are suitably safe.

**Comment by antoniovicente** [comment]
@rialg @jmarantz what are your thoughts on my replies above? I think that it is fine for Buffer::Instance to do low level operations, no need to use MemBlockBuilder

Can this issue be closed?

**Comment by jmarantz** [comment]
Agreed; let's close this for now, especially as we'd have to extend MemBlockBuilder to handle this case.

There may be other instances of memcpy calls we should still tackle, but for now let's leave this one alone.

**Comment by rialg** [comment]
Hi @antoniovicente, sorry for your late response. After reviewing your previous comment, I agree with you on this point. Maybe, it will be better to update other places with MemBlockBuilder, but for that I will create a separate PR. So, this issue can be closed. WDYT @jmarantz ?
