### ISSUE TITLE
http ：Inconsistent number of HTTP request response callbacks 

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#15724]
OnRequestHeaders and onResponseHeaders are called the same number of times when I test by "sudo curl http://10.73.87.60:8000/", but OnRequestHeaders and onResponseHeaders are called differently when I perform stress testsby "./wrk -t4 -c400 -d1s --latency http://10.73.87.60:8000/", why?

**Comment by liuqi-sun** [comment]
![envoy_statistics](https://user-images.githubusercontent.com/48784730/112803706-2c788980-90a6-11eb-9b0c-ba3f151da492.png)
![my_log_1](https://user-images.githubusercontent.com/48784730/112803709-2da9b680-90a6-11eb-8c07-5e8f30349ee2.png)
![my_log_2](https://user-images.githubusercontent.com/48784730/112803712-2e424d00-90a6-11eb-946d-4808c14283c1.png)
![pressure_measuring_tools](https://user-images.githubusercontent.com/48784730/112803714-2edae380-90a6-11eb-9fb0-761e61d6cc8c.png)

**Comment by liuqi-sun** [comment]
![envoy_statistics](https://user-images.githubusercontent.com/48784730/112804103-942ed480-90a6-11eb-8f0a-88dc2236ec6b.png)
![my_log_1](https://user-images.githubusercontent.com/48784730/112804112-95600180-90a6-11eb-92ff-3506a9524e25.png)
![my_log_2](https://user-images.githubusercontent.com/48784730/112804114-95f89800-90a6-11eb-885b-d44cfd9bd47b.png)
![pressure_measuring_tools](https://user-images.githubusercontent.com/48784730/112804115-96912e80-90a6-11eb-9582-6128f8a564db.png)

**Comment by mattklein123** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
From the screenshots, it looks that the number of `onRequestHeaders()` callbacks matches `downstream_rq_total`, and the number of `onResponseHeaders()` callbacks matches `downstream_rq_completed`. Since those stats are generated by core Envoy, the issue seems unrelated to Wasm.

Also, both of those numbers are higher than the number of requests reported by `wrk`, so I imagine that after the requested `30s` duration, `wrk` terminates requests in flight without waiting for the responses.

**Comment by liuqi-sun** [comment]
> From the screenshots, it looks that the number of `onRequestHeaders()` callbacks matches `downstream_rq_total`, and the number of `onResponseHeaders()` callbacks matches `downstream_rq_completed`. Since those stats are generated by core Envoy, the issue seems unrelated to Wasm.
> 
> Also, both of those numbers are higher than the number of requests reported by `wrk`, so I imagine that after the requested `30s` duration, `wrk` terminates requests in flight without waiting for the responses.

I think the issue seems unrelated to Wasm. even if `wrk` terminates requests in flight without waiting for the responses. the REQ and RES should be equal. is it a bug?
