### ISSUE TITLE
Docs for recent tags show pre-release banner

### ISSUE THREAD

**Issue by victorhaggqvist** [envoyproxy/envoy#15744]
*Title*: Docs for recent tags show pre-release banner

*Description*:
All recent tags after https://www.envoyproxy.io/docs/envoy/v1.16.0/ appears to now show the pre-release banner, which  I believe previously was only there for https://www.envoyproxy.io/docs/envoy/latest/. Not sure about the correctness of the actual docs in relation to the tag, or if it is only the banner that is incorrectly rendered.

![2021-03-29_1617021027](https://user-images.githubusercontent.com/1887628/112837232-e9b1b400-909b-11eb-9e3f-5fd595e9aaa0.png)

**Comment by phlax** [comment]
thanks for reporting @victorhaggqvist i can look at fixing unless you want to ?

**Comment by victorhaggqvist** [comment]
you feel free to, I briefly looked and concluded it is probably related to the build/CI process env somewhere, as it looks like it is conditionally rendered on `release_level`  in https://github.com/envoyproxy/envoy/blob/main/docs/root/index.rst https://github.com/envoyproxy/envoy/blob/486cd88789625afe786de80d0b3f3b07576f3557/docs/conf.py#L46

but post that I'm rather clueless about how that works with bazel, so you feel free to look at it

**Comment by phlax** [comment]
@Shikugawa from my reading of source (maybe incorrect) this is happening because the release tag is not set correctly - not sure how that relates to the backport/release workflow exactly

```bash
 10 RELEASE_TAG_REGEX="^refs/tags/v.*"
 11 
 12 if [[ "${AZP_BRANCH}" =~ ${RELEASE_TAG_REGEX} ]]; then
 13   DOCS_TAG="${AZP_BRANCH/refs\/tags\//}"
 14 fi
 15 
```

**Comment by phlax** [comment]
cc @lizan

**Comment by phlax** [comment]
or the regex match might be wrong

**Comment by mattklein123** [comment]
I believe @lizan already fixed this, but I'm not positive.

**Comment by phlax** [comment]
if/once this is fixed it would be good if we can update the docs to remove these on historical versions etc

**Comment by phlax** [comment]
this is a list of the docs that currently have the problem described here (latest also have problem described here #15730) 

- https://www.envoyproxy.io/docs/envoy/v1.17.1/
- https://www.envoyproxy.io/docs/envoy/v1.17.0/
- https://www.envoyproxy.io/docs/envoy/v1.16.2/
- https://www.envoyproxy.io/docs/envoy/v1.16.1/
- https://www.envoyproxy.io/docs/envoy/v1.15.3/
- https://www.envoyproxy.io/docs/envoy/v1.14.6/
- https://www.envoyproxy.io/docs/envoy/v1.13.7/

also the following is linked/listed in the docs but the page doesnt exist (im guessing the build failed):

https://www.envoyproxy.io/docs/envoy/v1.13.8/

**Comment by phlax** [comment]
> I believe @lizan already fixed this, but I'm not positive.

@lizan can you confirm whether this is fixed ?

afaict the `AZP_BRANCH` env var is passed through - so either the wrong branch is being passed or the regex match isnt working

**Comment by phlax** [comment]
on further investigation, this is fixed in the working v1.14-7 branches - and will hopefully be rectified in the next releases of those

for the v13 branches not sure of the status - latest link is broken, previous shows pre-release and fixes are not backported

cc @mattklein123

**Comment by phlax** [comment]
https://www.envoyproxy.io/docs

**Comment by phlax** [comment]
this is now resolved i think
