### ISSUE TITLE
EDS+ORIGINAL_DEST hybrid

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#15750]
*Title*: EDS+ORIGINAL_DEST hybrid

*Description*:
It would be useful to have some sort of hybrid of EDS and original dest clusters. The intent here would be to give ORIGINAL_DEST behavior, but allow affixing per-endpoint metadata which is used by various components - for example, transport_socket_match. 

One way this could be used is to allow explicitly setting the destination IP, but configuring per-endpoint TLS settings. As a concrete example, this would be useful in a service mesh for Kubernetes, where we need to hit specific pods (endpoints) for StatefulSets, but have different TLS settings depending on which pod (some may have an envoy on the other side to terminate TLS while some may not)

Its plausible this is implementable in current Envoy (some endpoint subsetting??) but I couldn't figure it out.

cc @lambdai

**Comment by lambdai** [comment]
It seems the existing end 2 end flow without this hybrid req is to create a listener(bind_to_port==false, probably) for each subset of endpoints. 

What you are proposing is to use one listener but create subsets/matchers in original_dst cluster.

 @howardjohn  Can you explain the pain of using listener is traffic multiplexer? I remember istio did have flags to experimenting listener-as-dispatcher in the past

**Comment by howardjohn** [comment]
Creating multiple listeners still doesn't help unless you also create a dedicated cluster for each one as well? I am thinking about upstream TLS settings (and in future upstream cluster filter??), not the downstream settings

**Comment by lambdai** [comment]
> Creating multiple listeners still doesn't help unless you also create a dedicated cluster for each one as well? I am thinking about upstream TLS settings (and in future upstream cluster filter??), not the downstream settings

Good point! To rephase it, we have N (N>>1) upstream TLS settings and we assume the matcher(  ip:port collection to a upstream tls setting) in one original_dst should reduce cpu/ram consumption, meanwhile, updating that original_dst cluster should not damaging the existing connection.  Actually the latter part is not clear to me yet

**Comment by howardjohn** [comment]
Consider another case, ignoring Istio. I just have a single listener and am using HTTP Routes. I may want to send 50% of traffic to cluster `foo_original_dest` and 50% to `foo_round_robin`. In this case, I cannot create a dedicated cluster for each transport_socket_match, since I need envoy to do the load balancing.

Another case is I have 100 endpoints, and I want to set up TLS termination, some HTTP routing, then send to cluster and configure upstream TLS config per-endpoint, where I have N different possible upstream TLS settings. Today, I would need to make N filter chains, then setup N http routes, and N clusters. The filter chains would need to have the full list of endpoints associated, so any endpoints would require a filter chain drain (and full LDS push).

if we had this hybrid, we can instead have 1 filter chain, 1 http route, and 1 cluster with N transport_socket_matches.

**Comment by howardjohn** [comment]
I think this is still a useful feature even if its not a high priority
