### ISSUE TITLE
Performance drop with the envoy version upgrade

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [envoyproxy/envoy#15787]
*Title*: *performance of envoy is degraded with the envoy version upgrade*

*Description*:
We have conducted a performance test by directly using envoy as a router deployed on docker containers. The performance test was conducted with the same configuration set (see below), by varying envoy version (1.14.1 , 1.16.0 , 1.17.1) and average throughput recorded for these cases were 7054.7/s, 5575.2/s and 4946.6/s respectively. 

**Here are the environment details on the performance test:**

[Dockerfile](https://github.com/wso2/product-microgateway/blob/envoy-gw/router/src/main/resources/Dockerfile) was used to create the image (with varying the envoy version for three scenarios).

> Testing environment : docker on openstack ubuntu
> Docker container resource allocations (for envoy router): 
>          cpus : '2'
>          memory : 256m

As the back-end service, we had used a sample HTTP echo service, which implemented using [netty](https://netty.io/) server and this service (without proxying) has average throughput more than 20000/sec.
Here are the details of back-end service:

> 
> Environment : docker on openstack ubuntu
> Docker container resource allocations: 
>          cpus : '2'
>          memory : 4g
> 

So according to the above output, we can observe that there is performance drop with the envoy version upgrade.

Is there any reason for this??

**Comment by mattklein123** [comment]
It's going to be almost impossible to say what the issue is from the information provided. I would recommend capturing some flame graphs of each scenario and sharing them.

**Comment by VajiraPrabuddhaka** [comment]
@mattklein123 I will share the flame graphs. 
But, before that ,could you explicitly answer to the question "Is there a performance drop with the envoy version upgrade ?"

**Comment by phlax** [comment]
> could you explicitly answer to the question "Is there a performance drop with the envoy version upgrade ?"

i dont think there is an *explicit* answer

there is only answers dependent on your environment and configuration

if you can share that information, the setup of the tests and the results then others can look more closely at why that might be the case

**Comment by VajiraPrabuddhaka** [comment]
@phlax @mattklein123 I'm using pre-build docker image of envoy, is there a way to get flame graphs from that, without building the project. Could you please share some guide to capture flame graphs..

I have been reading [this](https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md#on-cpu-analysis). Is that the correct way to capture flame graphs for envoy..

**Comment by VajiraPrabuddhaka** [comment]
@mattklein123 find the attached flame graphs for each scenarios.

[flame_graphs.zip](https://github.com/envoyproxy/envoy/files/6257694/flame_graphs.zip)

> perf-kernel_1.14.1.svg - envoy 1.14.1
> perf-kernel_1.16.0.svg - envoy 1.16.0
> perf-kernel_1.17.1.svg - envoy 1.17.1

Environment details:

> Testing environment : docker on openstack ubuntu
> Docker container resource allocations (for envoy router):
> cpus : '2'
> memory : 256m

Used docker images : [https://hub.docker.com/r/envoyproxy/envoy](https://hub.docker.com/r/envoyproxy/envoy)

**Comment by mattklein123** [comment]
@VajiraPrabuddhaka unfortunately there are no symbols associated with the flame graphs so they are not very useful. Please make sure to use a binary with symbols when generating.

**Comment by VajiraPrabuddhaka** [comment]
@mattklein123 could you please point out a binary with symbols, so that I can use it??

I previously tried with [this](https://hub.docker.com/r/envoyproxy/envoy-debug/tags/?page=1&ordering=last_updated) and it gave me the same results.
