### ISSUE TITLE
HTTP filter before and after evaluation of Connection: Close header sent by upstream

### ISSUE THREAD

**Issue by bhatiakartik10** [envoyproxy/envoy#15788]
*Title*: *Forwarding connection:close header received from upstream to downstream*

*Description*:
Picking up from #14910, I wish to write an http filter before and after Envoy closes the connection with upstream. Boils down to 2 questions:
1. Is there a way to recognise that connection: close header has been sent by the upstream and add a header denoting the same?
2. Is there a way to consume the header added above and send connection: close header to downstream?

From my understanding, encoder http filters can modify headers after http-connection-manager has processed the response (and closed the connection to upstream, removing the header), hence achieving 1 might be difficult. 
Please correct me if I'm wrong somewhere and suggest a way to do this.

[*Relevant Links*]
>https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/http_filters

**Comment by mattklein123** [comment]
Stepping back, can you describe what you are actually trying to achieve? Do you want to set a header when Envoy is about to close the downstream connection?

**Comment by bhatiakartik10** [comment]
For a connection close request sent by upstream, I just want to forward it to downstream as well.

**Comment by mattklein123** [comment]
This doesn't make sense in the context of Envoy, where downstream and upstream are decoupled and can use different protocols. I'm still not completely understanding the actual problem you are trying to solve?

**Comment by bhatiakartik10** [comment]
I understand that they are decoupled however we have a Envoy setup which is fronted by a LoadBalancer. Whenever the upstream hosts sends a Connection:close header, Envoy closes the connection with upstream endpoint and removes this header from the response. We want to also close the connection between the LoadBalancer and Envoy (so that LB->Envoy doesn't live forever), for this we need Envoy to preserve the header in the response.

We are doing some internal migration between two type of stacks, as part of it we add and remove partitions on the LoadBalancer. While doing so, the load is not getting distributed evenly across partitions reason being that the LB->Envoy connections are living forever and the traffic keeps going to the old partitions.

We considered using the `max_connection_duration` configuration, but that won't really work in our use case.

**Comment by mattklein123** [comment]
> We considered using the max_connection_duration configuration, but that won't really work in our use case.

I would consider just using a shorter idle timeout? I don't think there is going to be a great way to handle this otherwise.
