### ISSUE TITLE
Add a flag to set the service region

### ISSUE THREAD

**Issue by marcosrmendezthd** [envoyproxy/envoy#15783]
*Description*:
> Add a flag "--service-region" to set the service region similar to how the zone is setup so that we don't need to modify the bootstrap.

**Comment by mattklein123** [comment]
see https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-config-yaml which you can use to override bootstrap config.

**Comment by marcosrmendezthd** [comment]
thanks @mattklein123 !
