### ISSUE TITLE
listener: switch default for SO_REUSEPORT to true

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#15794]
Switch the default to SO_REUSEPORT to true as at this point functional kernel support is widespread, and it's an ongoing support burden for Envoy with people complaining about connection imbalance. Plan:

1) Deprecate `reuse_port`
2) Add WKT `enable_reuse_port`
3) Default for `enable_reuse_port` will be true, with a runtime feature flag to flip the default to false (preserve current behavior).

cc @envoyproxy/api-shepherds @antoniovicente

**Comment by mattklein123** [comment]
I'm realizing that flipping the default to true probably also has to be aware of hot restart. I don't think hot restarting onto a different default is going to go well.

**Comment by daixiang0** [comment]
Still available?
