### ISSUE TITLE
Support build targets on Windows. 

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#15819]
*Description*:
>Describe the desired behavior, what scenario it enables and how it would be used.

In linux `./ci/run_envoy_docker.sh './ci/do_ci.sh <TARGET>'` supports a wide variety of targets for developers.

We should support a similar range of targets on Windows.

**Comment by wrowe** [comment]
I think https://github.com/envoyproxy/envoy/pull/16643 will cover your use case?

**Comment by davinci26** [comment]
closed via #16643
