### ISSUE TITLE
There are two same types cluster names, I wonder what is difference.

### ISSUE THREAD

**Issue by jihyun00** [envoyproxy/envoy#15848]
*Title*: *There are two same types cluster names, I wonder what is difference.*

*Description*:
I ran below commands and I found ingressgateway had more endpoints than an application pod.

```
# ingressgateway
kubectl exec sandbox-ingressgateway-79d477b787-7p7gx -n test -c istio-proxy -- curl -XPOST http://127.0.0.1:15000/clusters
```

```
# application
kubectl exec sandbox-test-application-baseline-5dd8bdcf78-2bfgk -n test -c istio-proxy -- curl http://127.0.0.1:15000/clusters
```

I found Ingressgateway had both cluster names. But Application pod didn't have the first one.
1) outbound_.8080_.canary_.test.common.svc.cluster.local
2) outbound|8080|canary|test.common.svc.cluster.local

what is difference between the two?

**Comment by rojkov** [comment]
I suspect this is how Istio configures Envoy instances. You'd better ask somebody from the Istio project why it does so.

**Comment by jihyun00** [comment]
@rojkov Thanks! I'll ask istio groups!
