### ISSUE TITLE
Lua Filter Response Handle Metadata is nil when method is "OPTIONS"

### ISSUE THREAD

**Issue by mikosa** [envoyproxy/envoy#15873]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:  Lua Filter Response Handle Metadata is nil when method is "OPTIONS"

*Description*:
I am using Lua filter  v2 to copy request headers into metadata and then in the response handle I am copying the metadata and adding it as headers in the response.

When the request method is GET, everything works as expected.

When the request method is OPTIONS, it seems that metadata is returning nil. and this is creating an error. 

- I am not able to check using lua if the metadata is nil before trying to query the metadata. If I try to check if metadata is nil, i still get a nil error

- Also I tried to run the code only when the request method is GET but in the response handle, I dont have access to the request method 

So I am not able to to run my code only when the method is not OPTIONS

```    function envoy_on_request(handle)
            local headers = handle:headers()
            local metadata = handle:streamInfo():dynamicMetadata()                
            local rid = headers:get("x-request-id")
            local mymeta = metadata:set("envoy.filters.http.lua", "request-id", rid)
          end
          function envoy_on_response(res_handle)
             local metadata = res_handle:streamInfo():dynamicMetadata()
             local pis =  metadata:get("envoy.filters.http.lua")["request-id"]
             res_handle:headers():add("x-request-id", pis)
          end
```
*Repro steps*:

try above lua code in v2 (maybe also v3)
make sure u have CORS to generate OPTIONS request methods
if u dont have the request-id, u can generate any header u want

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by snowp** [comment]
Can you provide an Envoy config that reproduces this issue? I think that would be helpful in tracking down the cause of this, thanks!

**Comment by mikosa** [comment]
this is more of an istio deployment

**Comment by snowp** [comment]
Most of us aren't familiar with Istio enough to reproduce Istio deployments, so I would suggest looping the Istio folks in first to understand what Envoy configuration this is using as a first step. Once we have a way to reproduce this it will be a lot easier for us to take a look. Alternatively if you are able to set up an example Envoy config that doesn't use Istio that would be helpful.

At a high level I'm not sure why SETTINGS would be different from any other types in this regard, so there might be some interaction with the CORS filter, but it's hard to verify without a reproducer.
