### ISSUE TITLE
UDP: add support for multiple filters

### ISSUE THREAD

**Issue by davidkornel** [envoyproxy/envoy#15887]
Does UDP support network filters? If not, why not? Are there some issues with it, or someone has to implement it? 

**Network filters:**
I'd like to write my own filter that works with UDP as well but currently as I know network filters won't apply for UDP listeners.
I know that for now, only 1 UDP listener filter per listener supported, but what about network filters?

**Listener filters:**
In #11656 it was mentioned that 
>Someone would need to finish the UDP filter manager work so that we can support multiple filters.

Is there any progress on this? What are your plans with UDP in the future?

Sorry for a lot of questions. But I really want to know what should I expect.
Thanks for your time and help in advance

**Comment by snowp** [comment]
I know we have some support for UDP listeners, but not sure how sophisticated the support is compared to TCP. 

@alyssawilk @mattklein123 might know more

**Comment by mattklein123** [comment]
I would love to have multiple UDP filters implemented, but someone needs to work on it. There is no high level reason it is not done, it's just that no one has cared to do it yet. I will repurpose this issue to track that.

**Comment by davidkornel** [comment]
Alright, thanks. Yes, that would be very nice to have multiple UDP filters. I'd say I'll do it but unfortunately to this point, I only changed a small portion of the code to implement a smaller feature I need. And I definitely don't see where and how should these changes be done. So I see two options right now. We'll wait until someone - who's capable - get the job done, or if someone gives me help I'll try it myself. WDYT how challenging it would be to implement the support for multiple UDP filters?

**Comment by mattklein123** [comment]
> WDYT how challenging it would be to implement the support for multiple UDP filters?

For experienced contributors I would say medium, for new contributors hard. I can try to find some time to write down some implementation notes but I'm not sure when I will be able to get to it.

**Comment by zhxie** [comment]
Sounds great. Then I think it may be not difficult to realize UDP multiple filters.

But, in my opinion, I think network socket, transport socket, listener filter and network filter would better be decoupled. Though there are a lot of major differences between TCP and UDP, one is stream-based, the other is datagram-based, one is reliable, the other only delivers with best-effort. But no one says you cannot put HTTP over UDP, or DNS over TCP. I think it would better if we could apply existed network filters on UDP, to make network socket unified. You mentioned MTU, but I do not think it is the thing we, a proxy, should consider. Users should be aware of MTU and the OS is responsible for fragmentation.
