### ISSUE TITLE
proposal: Downstream source ip/port filter

### ISSUE THREAD

**Issue by davidkornel** [envoyproxy/envoy#15889]
**Concept:**
I am thinking of a new filter that would do filtering on the source IP/port of the connection. With this filter, we would be able to control where to accept connections from. Like [filter_chain_match](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchainmatch)'s `source_prefix_ranges` and `source_ports`. If the source IP is in the given CIDR range in `source_prefix_ranges` and the port is listed below `source_ports` then accept, otherwise reject.

Not sure if this should be a network or a listener filter. 

**Use case:** 
In #15590 I mentioned that we want to let a single RTP stream on a single listener and no more because multiple streams would cause problems.
The main problem is with this use case that it is focused on UDP and as I know network filters don't work with UDP listeners in general (looking for further information in #15887). And right now only 1 UDP listener filter per listener supported.
WDYT? 

**Questions:**
- Is there any situation when a UDP listener rejects/refuses a "connection"? And if so, where, when and how should it happen?
- In general, if I want to implement this function somehow for UDP listeners what would you recommend how should this be done and what'd be the easiest and best way.

**Note:** 
First I thought this could work with configuring the `filter_chain_match` in a listener, but the connection is refused immediately if the `filters` list is empty. And there's no such filter that does nothing. So it didn't work. But the main idea is similar of the filter is similar to this.

Let me know anything you think about this. I'll gladly work on this, but need some guideline. Thanks

**Comment by lambdai** [comment]
FilterChainMatch is not applied to udp_listener. Partially because udp listener doesn't not support "connection filter chain"

I would suggest creating the *udp filter chain*. Since the udp is packet-oriented, it's probably not reasonable to separate listener filter vs network filter as in the tcp listener.

A single udp filter chain can simulate the role of FilterChainMatch which dispatches to multiple filter chains. A generalized udp filter chain selector can be done after. 

WDYT?

**Comment by mattklein123** [comment]
Yeah I would suggest we track this in https://github.com/envoyproxy/envoy/issues/15887 per @lambdai. Also, we need to tease apart whether you want this for TCP or UDP. If you want this for TCP I would say either do it with filter chain match or potentially via network RBAC.

If you want this for UDP I think it makes more sense to properly implement multiple filters. Then we can do whatever we want including RBAC for UDP, etc.
