### ISSUE TITLE
Is the program release or debug

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#15898]
The file command shows with debuginfo, but --version shows release
![envoy-info](https://user-images.githubusercontent.com/48784730/114146799-9ae10580-994a-11eb-897c-aafa59baf8e6.png)

**Comment by snowp** [comment]
That probably is an -opt build (at least -NDEBUG is set). It seems to be a custom build (based on `Modified`), so it's probably easier to find out by tracking down how this was built? 

No reason why an optimized build can't contain debug info/symbols, it all just depends on how you build it.
