### ISSUE TITLE
Ability to log outlier event to stderr

### ISSUE THREAD

**Issue by fredwangwang** [envoyproxy/envoy#15905]
*Title*: *Able to log outlier event to stderr*

*Description*:

We run envoy as sidecar and want to monitor outlier events. We already have the log shipper setup to read from docker container logs. Right now envoy supports configure the outlier event to a file sink, which needs to have additional log rotation and log shipping in place to read that information. It would be much more straightforward if the outlier events are also dumped into stderr so we can use the existing log shipping infrastructure.

**Comment by snowp** [comment]
Have you tried specifying the target of the file sink as `/dev/stderr`? This is typically supported for file outputs

**Comment by fredwangwang** [comment]
Thanks @snowp for your quick response! Just tried and it is indeed able to send log to stderr.

Closing
