### ISSUE TITLE
Docs flake in post-submit jobs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15901]
### description

docs fails from time to time with the following error:

```
+ git add .
+ git commit -m 'docs envoy@9ad2b69595e6b7470adf7f27ee181cf293b50ff3'
[main aac8b1cb5] docs envoy@9ad2b69595e6b7470adf7f27ee181cf293b50ff3
 1265 files changed, 4611 insertions(+), 4609 deletions(-)
 rewrite docs/envoy/latest/searchindex.js (77%)
+ git push origin main
To github.com:envoyproxy/envoyproxy.github.io
 ! [remote rejected]     main -> main (cannot lock ref 'refs/heads/main': is at 50dc906721004ca1638d1ff9a10aebd5384c20c7 but expected 2dbbc249deb9183e75d9f846792333b7538d8e66)
error: failed to push some refs to 'github.com:envoyproxy/envoyproxy.github.io'
```

which can be seen here https://dev.azure.com/cncf/envoy/_build/results?buildId=71621&view=logs&j=681c7800-c42c-5f1e-f2ee-699120aa5784&t=9a535103-4675-5a3d-3e9c-59a6e6997567&l=122

its problematic as it means that docs are not getting published when they should be

**Comment by phlax** [comment]
im guessing that this is caused by ~simultaneous pushes to main and by the time it wants to publish the docs the website refs are changed

if this is correct perhaps we need to add some code to force a rebase when this error is hit

**Comment by mattklein123** [comment]
Yes I think this is the case, but I'm not sure it's worth handling. It fixes itself typically shortly thereafter.

**Comment by phlax** [comment]
the problem is when it happens on a stable build - ie published - i think its the reason that some of the links on the envoy docs page dont work

**Comment by mattklein123** [comment]
> the problem is when it happens on a stable build - ie published - i think its the reason that some of the links on the envoy docs page dont work

I'm very skeptical, around release time the branches are mostly locked, but I suppose it's possible.

**Comment by phlax** [comment]
well what is fact is that some of the published docs are broken - they dont exist - the link goes nowhere

**Comment by mattklein123** [comment]
> well what is fact is that some of the published docs are broken - they dont exist - the link goes nowhere

Maybe it's this problem or maybe it's another problem. It's hard to say without more information.

**Comment by phlax** [comment]
yep - ill follow up - but lets try and actually publish the docs 8/

**Comment by phlax** [comment]
this has been resolved by the newer docs publishing pipeline
