### ISSUE TITLE
Can Envoy allow changing address in a listener config update?

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#15907]
*Description*:
The current listener update reject the new config if the new address of the same listener name is different.
It's safe: new reuse the socket. 

Can we relax a little bit to support 127.0.0.1 <-> 0.0.0.0 address update? With proper socket options 
this behavior should be safe and avoid service interruption.

What's the drawback?

What can be done in control plane?

Also see the failure in https://github.com/istio/istio/pull/32053#issue-611743918 why it's nice to have in Envoy

**Comment by snowp** [comment]
I think this has come up before and iirc there is no fundamental reason why this can't be supported, @mattklein123 might recall the details

**Comment by mattklein123** [comment]
@lambdai sorry I can't really parse the issue text. Can you clarify your various points?

At this point I honestly don't remember why I/we originally blocked address changes. I think it's probably fine to allow address changes and just correctly handle the case where we make a new socket for the new listener and correctly drain the old listener (which I guess would happen anyway).

Is there any case which wouldn't work that I am forgetting?

**Comment by mattklein123** [comment]
@lambdai if we end up deciding to change this, can you also fix https://github.com/envoyproxy/envoy/issues/15562 please? It's in the same code area.

**Comment by lambdai** [comment]
> @lambdai sorry I can't really parse the issue text. Can you clarify your various points?
> 
> At this point I honestly don't remember why I/we originally blocked address changes. I think it's probably fine to allow address changes and just correctly handle the case where we make a new socket for the new listener and correctly drain the old listener (which I guess would happen anyway).
> 
> Is there any case which wouldn't work that I am forgetting?

I am less ambitious: I wish we can start with allow update from wildcard ip to unicast ip. 

I don't have the use case of changing from a unicast ip to another unicast ip.  Although literally the code path should be exactly 
the same as "wildcard ip" to "unicast ip" update, IMO unicast ip to unicast ip update is more likely a config error. 

My major concern is that the listener update is not yet revertible on error. For example, if the new listener config want to listen 
"10.0.0.1:22". The new update can pass the validation, but can fail on work thread because
1. 10.0.0.1 is not a valid nic ip
2. port 22 is used by another process.
3. Envoy process is not privileged.

If we allows address update, the old listener will be drained, and the new listener fails to bind. And the old listener won't come back.

**Comment by mattklein123** [comment]
FWIW, as part of fixing https://github.com/envoyproxy/envoy/pull/15818 I'm going to change it so that all sockets are allocated ahead of time on the main thread (even for SO_REUSEPORT). This will fix a bunch of the corner cases you are talking about and make the logic much simpler to understand. I don't know when I will get to finish that PR though.

In terms of only allowing wildcard IP to unicast IP I don't feel that strongly about it. We can discuss in code review.

**Comment by soulxu** [comment]
> I am less ambitious: I wish we can start with allow update from wildcard ip to unicast ip.
> 
> I don't have the use case of changing from a unicast ip to another unicast ip. Although literally the code path should be exactly
> the same as "wildcard ip" to "unicast ip" update, IMO unicast ip to unicast ip update is more likely a config error.
> 
> My major concern is that the listener update is not yet revertible on error. For example, if the new listener config want to listen
> "10.0.0.1:22". The new update can pass the validation, but can fail on work thread because
> 
> 1. 10.0.0.1 is not a valid nic ip
> 2. port 22 is used by another process.
> 3. Envoy process is not privileged.
> 
> If we allows address update, the old listener will be drained, and the new listener fails to bind. And the old listener won't come back.

a question for the preference of envoy between 'update a listener' and 'add a new listener and delete the old one'. Looks like add a new listener and delete the old one can avoid the trouble (by need the control-plane to ensure the new one works before delete the old one), or we have a preference of `update a listener`.

**Comment by lambdai** [comment]
@soulxu Is your high level goal that only updating address? 

If the listener update involves changes other than address, the huge advantage of updating the listener is that your new tcp request never lost. Also, if you have multiple filter chains living in the listener.

Even if the goal is address only update, ideally if you are changing from wildcard address to nic address. the "update" path guarantees no tcp new request lost, if the update is implemented properly :)

**Comment by soulxu** [comment]
> @soulxu Is your high level goal that only updating address?

yes
> 
> If the listener update involves changes other than address, the huge advantage of updating the listener is that your new tcp request never lost. Also, if you have multiple filter chains living in the listener.
> 
> Even if the goal is address only update, ideally if you are changing from wildcard address to nic address. the "update" path guarantees no tcp new request lost, if the update is implemented properly :)

copy that, thanks for the explanation :)
