### ISSUE TITLE
Is there a filter to analyse or modify the postgre sql

### ISSUE THREAD

**Issue by roycyz** [envoyproxy/envoy#15919]
Just like the title.

**Comment by cpakulski** [comment]
There is postgres filter which creates a metadata based on SQL query: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter.html?#dynamic-metadata. It is however in experimental stage and works only for simple statements. We need a better SQL parser to address all the cases.

Modifying SQL is not possible.

**Comment by htuch** [comment]
This seems to answer the question, I think it's best to move informal questions like this to Slack.

**Comment by roycyz** [comment]
> There is postgres filter which creates a metadata based on SQL query: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter.html?#dynamic-metadata. It is however in experimental stage and works only for simple statements. We need a better SQL parser to address all the cases.
> 
> Modifying SQL is not possible.

I can get the messages in postgres_filter.cc. But  These data contain sql protocols. Also I can't change the buffer,Its encapsulated without interface.
From the web page,it's not support in my version.My version is 1.15 and thanks.
