### ISSUE TITLE
[Documentation| Panic mode] Are numbers for normalised total health correct?

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#15917]
Looks like calculations in documentation for panic mode contain some errors [here](https://github.com/envoyproxy/envoy/blob/20e4dd2c0e5bacf07cd2fa7f559ae4714da8f905/docs/root/intro/arch_overview/upstream/load_balancing/panic_threshold.rst):
![Screenshot 2021-04-11 at 23 51 50](https://user-images.githubusercontent.com/14430883/114322517-f82eaf80-9b20-11eb-8b1f-50614866da30.png)
Normalised total health is incorrect for two last lines according to [definition of normalised total health](https://github.com/envoyproxy/envoy/blob/9ad2b69595e6b7470adf7f27ee181cf293b50ff3/docs/root/intro/arch_overview/upstream/load_balancing/priority.rst#priority-levels):
```
normalized_total_health = min(100, Σ(health(P_0)...health(P_X)))
```

**Comment by htuch** [comment]
@snowp can you take a look?

**Comment by snowp** [comment]
Seems right to be with an overprovisioning factor of 1.4, e.g. we treat 25% health as 25% * 1.4 = 35% health, or am I missing something here?

Perhaps the documentation should be clearer about what health(P_x) means? Might not be clear that it includes the overprovisioning factor

**Comment by nezdolik** [comment]
>>>Perhaps the documentation should be clearer about what health(P_x) means?

Agree, this would be helpful

**Comment by nezdolik** [comment]
Actually, I now see this formula (health(P_X)), which explains the calculations:
```
health(P_X) = min(100, 1.4 * 100 * healthy_P_X_backends / total_P_X_backends)
normalized_total_health = min(100, Σ(health(P_0)...health(P_X)))
```
