### ISSUE TITLE
http to tcp filter

### ISSUE THREAD

**Issue by rtttech** [envoyproxy/envoy#15920]
I want to create a filter that can transcode a http request to a tcp request, How can I do that? 

for example: http rest -> redis transcode

**Comment by htuch** [comment]
It's a bit unclear what is being asked here, can you clarify?

**Comment by rtttech** [comment]
> It's a bit unclear what is being asked here, can you clarify?

When envoy received a http request It relays the http request to upstream service, that's the normal case. However our upstream service can only handle tcp protocol(not http),   so we have to implement a filter that perform the transcoding.

**Comment by htuch** [comment]
There are many examples of this, e.g. see https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_web/v3/grpc_web.proto. You will need to write an HTTP filter to do this.

**Comment by rtttech** [comment]
> There are many examples of this, e.g. see https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_web/v3/grpc_web.proto. You will need to write an HTTP filter to do this.

thank you very much, but After check the grpc_web source code I am still now clear that how the http filter send a tcp request to upstream. I dont found any code that does the job.

**Comment by htuch** [comment]
You're right, if you are transcoding to something that isn't fundamentally L7, then this looks different. I don't think there is a lot of precedents, but you would need to replace the router filter and make your HTTP filter a terminal filter, that interacts directly with the TCP connection pool in upstream.

**Comment by rtttech** [comment]
Thank you. I found this can satisfy my need, how can I use it in istio(if envoy already has the feature)

https://github.com/envoyproxy/envoy/pull/14552

configure example:
envoy/configs/terminate_http2_post.yaml

**Comment by htuch** [comment]
I think you'll need to take this to the Istio issue tracker, see https://github.com/istio/istio. Since you say this answers the original question, I'm going to close this out. Thanks.
