### ISSUE TITLE
Struggling to make gRPC-web and HTTPS work

### ISSUE THREAD

**Issue by NickEPalmer** [envoyproxy/envoy#15928]
I've got a SPA web app that uses gRPC web and envoy to proxy back to a server that speaks gRPC.  This all works great, no problems.

I'm trying to make this secure using HTTPS/TLS and just keep running into issues and can't seem make it work.

Our setup is this:

Web Client SPA app (accessed from web node.js server also running on the lahinch server.  URL is https://lahinch.mycorp.com ).  Web app connects to the envoy proxy using this address "https://coxos.mycorp.COM:8090"
      \ 
        \\
          Envoy Proxy  (coxos - 172.16.0.116) - listens on port 8090 and proxies to port 50251
            \\
              \\
                Backend gRPC server  (lahinch - 172.16.0.109) - listens on port 50251
          
    
From reading the envoy docs, the web client is downstream and the backend server is upstream.

Here is my envoy.yaml file

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8090
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                  - name: envoy.access_loggers.http_grpc
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
                      common_config:
                        log_name: envoygrpclog
                        grpc_service:
                          envoy_grpc:
                            cluster_name: controlweb_backendservice
                        transport_api_version: V3
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: controlweb_backendservice
                            hash_policy:
                              - header:
                                  header_name: x-session-hash
                            max_stream_duration:
                              grpc_timeout_header_max: 300s
                      cors:
                        allow_origin_string_match:
                          - safe_regex:
                              google_re2: {}
                              regex: .*
                        allow_methods: 'GET, PUT, DELETE, POST, OPTIONS'
                        allow_headers: >-
                          keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,grpc-status-details-bin,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,access-token,x-session-hash
                        expose_headers: >-
                          grpc-status-details-bin,grpc-status,grpc-message,access-token
                        max_age: '1728000'
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.cors
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              # https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/transport_sockets/tls/v3/tls.proto#extensions-transport-sockets-tls-v3-downstreamtlscontext
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      # Certificate must be PEM-encoded
                      filename: /etc/lahinch.pem
                    private_key:
                      filename: /etc/lahinch.key.pem
                validation_context:
                   trusted_ca:
                      filename: /etc/ssl/certs/ZZZ-CA256.pem
  clusters:
    - name: controlweb_backendservice
      type: LOGICAL_DNS
      connect_timeout: 0.25s
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: cluster_controlweb_backendservice
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: lahinch.mycorp.com
                      port_value: 50251
      http2_protocol_options: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: /etc/lahinch.pem
                private_key:
                  filename: /etc/lahinch.key.pem
            validation_context:
              trusted_ca:
                filename: /etc/ssl/certs/ZZZ-CA256.pem
        
                
Using this, I'm getting the following in the envoy log when I try and run my web app:

[2021-04-09 22:08:33.939][17][debug][conn_handler] [source/server/connection_handler_impl.cc:501] [C2] new connection
[2021-04-09 22:08:33.945][17][debug][http] [source/common/http/conn_manager_impl.cc:254] [C2] new stream
[2021-04-09 22:08:33.945][17][debug][http] [source/common/http/conn_manager_impl.cc:886] [C2][S3055347406573314092] request headers complete (end_stream=false):
':authority', 'coxos.mycorp.com:8090'
':path', '/WanderAuth.HostService/LogIn'
':method', 'POST'
'connection', 'keep-alive'
'content-length', '124'
'accept', 'application/grpc-web-text'
'x-user-agent', 'grpc-web-javascript/0.1'
'access-token', ''
'x-grpc-web', '1'
'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68'
'grpc-timeout', '90000m'
'content-type', 'application/grpc-web-text'
'origin', 'https://lahinch.mycorp.com'
'sec-fetch-site', 'same-site'
'sec-fetch-mode', 'cors'
'sec-fetch-dest', 'empty'
'referer', 'https://lahinch.mycorp.com/'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-US,en;q=0.9'

[2021-04-09 22:08:33.946][17][debug][router] [source/common/router/router.cc:425] [C2][S3055347406573314092] cluster 'controlweb_backendservice' match for URL '/WanderAuth.HostService/LogIn'
[2021-04-09 22:08:33.946][17][debug][router] [source/common/router/router.cc:582] [C2][S3055347406573314092] router decoding headers:
':authority', 'coxos.mycorp.com:8090'
':path', '/WanderAuth.HostService/LogIn'
':method', 'POST'
':scheme', 'https'
'accept', 'application/grpc-web-text'
'x-user-agent', 'grpc-web-javascript/0.1'
'access-token', ''
'x-grpc-web', '1'
'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68'
'grpc-timeout', '90000m'
'content-type', 'application/grpc'
'origin', 'https://lahinch.mycorp.com'
'sec-fetch-site', 'same-site'
'sec-fetch-mode', 'cors'
'sec-fetch-dest', 'empty'
'referer', 'https://lahinch.mycorp.com/'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-US,en;q=0.9'
'x-forwarded-proto', 'https'
'x-request-id', 'a4a041ab-dc29-4ed7-a342-90ac03b3be3c'
'te', 'trailers'
'grpc-accept-encoding', 'identity'
'x-envoy-expected-rq-timeout-ms', '15000'

[2021-04-09 22:08:33.946][17][debug][pool] [source/common/http/conn_pool_base.cc:79] queueing stream due to no available connections
[2021-04-09 22:08:33.946][17][debug][pool] [source/common/conn_pool/conn_pool_base.cc:106] creating a new connection
[2021-04-09 22:08:33.946][17][debug][client] [source/common/http/codec_client.cc:41] [C3] connecting
[2021-04-09 22:08:33.946][17][debug][connection] [source/common/network/connection_impl.cc:860] [C3] connecting to 172.16.0.109:50251
[2021-04-09 22:08:33.946][17][debug][connection] [source/common/network/connection_impl.cc:876] [C3] connection in progress
[2021-04-09 22:08:33.946][17][debug][http2] [source/common/http/http2/codec_impl.cc:1184] [C3] updating connection-level initial window size to 268435456
[2021-04-09 22:08:33.946][17][debug][http] [source/common/http/filter_manager.cc:755] [C2][S3055347406573314092] request end stream
[2021-04-09 22:08:33.947][17][debug][connection] [source/common/network/connection_impl.cc:666] [C3] connected
[2021-04-09 22:08:33.947][17][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:224] [C3] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2021-04-09 22:08:33.948][17][debug][connection] [source/common/network/connection_impl.cc:241] [C3] closing socket: 0
[2021-04-09 22:08:33.948][17][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:224] [C3] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2021-04-09 22:08:33.948][17][debug][client] [source/common/http/codec_client.cc:99] [C3] disconnect. resetting 0 pending requests
[2021-04-09 22:08:33.948][17][debug][pool] [source/common/conn_pool/conn_pool_base.cc:343] [C3] client disconnected, failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2021-04-09 22:08:33.948][17][debug][router] [source/common/router/router.cc:1026] [C2][S3055347406573314092] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2021-04-09 22:08:33.948][17][debug][http] [source/common/http/filter_manager.cc:839] [C2][S3055347406573314092] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER}
[2021-04-09 22:08:33.948][17][debug][http] [source/common/http/conn_manager_impl.cc:1484] [C2][S3055347406573314092] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '190'
'content-type', 'application/grpc-web-text+proto'
'access-control-allow-origin', 'https://lahinch.mycorp.com'
'access-control-expose-headers', 'grpc-status-details-bin,grpc-status,grpc-message,access-token'
'date', 'Fri, 09 Apr 2021 22:08:33 GMT'
'server', 'envoy'

[2021-04-09 22:08:36.139][9][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:101] starting async DNS resolution for lahinch.mycorp.com
[2021-04-09 22:08:36.139][9][debug][main] [source/server/server.cc:199] flushing stats
[2021-04-09 22:08:36.141][9][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:109] async DNS resolution complete for lahinch.mycorp.com
[2021-04-09 22:08:36.141][9][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:155] DNS refresh rate reset for lahinch.mycorp.com, refresh rate 5000 ms

So the error appears to be this: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER

I've looked up this error and it appears to be be related to security and certificates.  But I haven't been able to find a good answer as to what I'm doing wrong.  

When it comes to the required certs, should the certs be the same that is used by client(downstream), the proxy or the backend(upstream server) or both? I've tried using different certs for the different servers and the same certs for the servers and I still get the same error.    

Thanks in advance,
Nick

**Comment by htuch** [comment]
Is your upstream expecting TLS? Can you connect to it manually without Envoy?

**Comment by NickEPalmer** [comment]
By default the upstream is is not expecting TLS, but it can be configured for that which I have done.  And yes I can connect without Envoy.  I have a simple test program but it didn't support using TLS/certs so I had to update the test program for that.  After some configuration issues, I was able to run the test program using TLS/certs which makes a gRPC connection using port 50251 to the upstream server.

My first test involved running both the test program and upstream server on my dev system.  I created the required certs for my dev system and used those certs with both the test program and upstream server.  In this case I can connect successfully using TLS.  

I then took the test program and copied it and the required files to a separate system and was able to successfully connect to my dev system running the upstream server using TLS/certs remotely.

Next I tried to add Envoy to this test.  I modified my envoy file to use the certs I had created for my dev system and pointed the upstream envoy server to my dev system.  I then ran the test program and pointed it at envoy.  This test failed.

I'm also a bit confused about the the server certificates. Which system should they specify?  In my case the upstream server is named lahinch.  And those are the certs I'm using in yaml.  Is that correct?

**Comment by htuch** [comment]
You have the same certs/keys for your downstream and upstream. Is this intended? The downstream key/certs are what will be used by the Envoy when acting as a server for clients attaching. The upstream key/certs are used for the client TLS portion of mTLS when speaking to the backend/upstream.

**Comment by NickEPalmer** [comment]
I actually got things working :) More on that later.

I'm not sure if having the same cert is intended or not, as finding examples to follow was a bit tricky and I've been trying lots of different combinations to see what works.  Is it required to have different certs for the upstream and downstream servers/clients?  

For TLS to work, it seems that it is required that the the entire chain uses SSL/certs, but do the certs all have to be the same?

Here is what ended up making things work. There were several things wrong that I had to correct.

On dev my system, I went and examined the certs I was using and realized that I had exported the cert from my dev system incorrectly.  I re-exported the cert and rebuilt the pem files and updated my docker and yaml files. After doing this I was able to go from my dev test client to envoy to my dev test server using TLS.  Success one.  I then did the same test using a remote client and that worked.  I then modified the web app config on my test server to point to dev system and I was able to successfully run our web app using https pointing back to my dev system.  Success two.  I updated the test server web config to point to the test server backend and retried and things still didn't work.  Then I went digging thru the code and realized that there was code to support TLS in the dev testing, but not in the release builds.  So I fixed that and updated the test server and bingo things worked.  

I've been doing some more testing and have some questions.  

1. In my yaml I had been using the validation context like this:

            validation_context:
              trusted_ca:
                filename: /etc/ssl/certs/ZZZ-CA256.pem

I tried taking this out and things still worked correctly.  The certs I'm using are issued by our internal CA so they are valid for any internal system.  When and why would you use the trusted_ca specification?

2. In going back and cleaning up all the files I was using I discovered I was doing the following in my docker build file:

ADD ./coxosV2.crt.pem /etc/coxosV2.crt.pem
ADD ./coxosV2.key.pem /etc/coxosV2.key.pem

ADD ./coxosV2.crt.pem /etc/lahinch.pem
ADD ./coxosV2.key.pem /etc/lahinch.key.pem
ADD ./coxosV2.key.pem /etc/lahinch.crt.pem

ADD ./coxosV2.crt.pem /etc/nickopti990.pem
ADD ./coxosV2.key.pem /etc/nickopti990.key.pem
ADD ./coxosV2.key.pem /etc/nickopti990.crt.pem

ADD ./coxosV2.crt.pem /etc/nickopti990v2.pem
ADD ./coxosV2.key.pem /etc/nickopti990v2.key.pem
ADD ./coxosV2.key.pem /etc/nickopti990v2.crt.pem

So even though I had created all the different cert PEM and key files to test with, I was actually always using the coxosV2 files the entire time.  

I cleaned up the docker build file to only have this now:

ADD ./coxosV2.crt.pem /etc/coxosV2.crt.pem
ADD ./coxosV2.key.pem /etc/coxosV2.key.pem

So this means that as far as the certs go, the cert assigned to both the upstream and downstream server is pointing to my envoy server.  Actually I guess it's pointing to the server that hosts docker and the envoy docker image.  Given my question about which certs to use, does using this cert make sense?

Sorry for all the questions, just trying to understand all this.

**Comment by htuch** [comment]
Certs don't need to be the same for downstream/upstream; each hop uses [m]TLS differently potentially. You need to decide based on PKI in your environment how to make this work. The best way to think about this is hop-by-hop; what are the client/server certificates that should be in play on each hop in your network path.

**Comment by NickEPalmer** [comment]
Ok thanks, I think I understand. I'll do some more testing, but I think I've resolved this issue
