### ISSUE TITLE
Zipkin trace span timestamp annotation is not properly replaced during serialization

### ISSUE THREAD

**Issue by bianpengyuan** [envoyproxy/envoy#15960]
https://github.com/envoyproxy/envoy/pull/15492 adds timestamp annotations to span, but the replacement records is not properly set:

https://github.com/envoyproxy/envoy/blob/110aec2b2fb61c8c9d3e7295b08beb8d46cc01e3/source/extensions/tracers/zipkin/span_buffer.cc#L136

With the code above, it records replacement as key: `"cr":"1618349542333171"`   value: `"cr":1618349542333171`, but the serialized annotation string is like `"annotations":[{"value":"cr","timestamp":"1618349542333171"}]`. This make jaeger trace report fails due to wrong timestamp data type: https://github.com/istio/istio/issues/32026

cc @dio @jamesmulcahy

**Comment by jamesmulcahy** [comment]
Good catch, @bianpengyuan -- apologies for the trouble!
