### ISSUE TITLE
can envoy enable to auto add token to header after validate token to request?

### ISSUE THREAD

**Issue by jinglina** [envoyproxy/envoy#15964]
when I use *AuthorizationPolicy* to authenticate a jwt token, 
step1, client to jwt server to generate token using private key and return token
step2, client requests with token and verify token using public key through  Api gateway
step3, after verfication, access to protected api to finish jwt check

I wonder If envoy can add token to header automatically in step2, in that case ,client won't take token to header?

I know **EnvoyFilter** with *Lua* extension can add header automatically before request to api, If envoy can do this by any configration in any policy ?

**Comment by htuch** [comment]
Not sure I fully understand the question, but maybe @qiwzhang can help.

**Comment by jinglina** [comment]
Let's put it in that way:  After verifing authorization in **Request authentication** , envoy knows the jwksUri or jwks; To verify author
policy ,like **AuthorizationPolicy** which need token , can token to added to header automatically by envoy throgh some rule?

**Comment by jinglina** [comment]
Or any further efforts to it ?
