### ISSUE TITLE
Envoy upstream connection failure due to 503 upstream_reset_before_response_started{local reset} LR

### ISSUE THREAD

**Issue by madhu-shankar** [envoyproxy/envoy#15968]
*Title*: *Envoy is failing to connect to upstream cluster*

*Description*:
>We are using Original Destination routing while routing request to upstream cluster. We were intermitently seeing 503s returned by Envoy. Upon checking the Response flag and Response details in Access logs, we found that 503s are being sent due to failure in connecting with upstream host. This is a sample access log entry `503 upstream_reset_before_response_started{local reset} LR`

>To give some context on the upstream cluster, it periodically closes connections and sends `connection:close` header.

1. What is the underlying cause for the 503 response from Envoy, is it failing to handle the `connection:close` and has stale connections to upstream.

2. We tried fixing it by configuring retry on connection reset using the below config,
```
retry_policy:
   retry_on: reset
```
Even after configuring the 1-retry, there has been a reduction in the number of 503 responses. But still some upstream connections are failing with `URX` flag. Do you suggest any other configuration or tuning this configuration itself to completly eliminate 503 responses?

Also, we saw different Response details for the same scenario is Envoy-1.13.1 and Envoy-1.15.2. 
* Envoy-1.13.1: `503 upstream_reset_before_response_started{connection failure} UF`
* Envoy-1.15.2: `503 upstream_reset_before_response_started{local reset} LR`

Can you confirm if this behavior has changed from 1.15.0? We saw this [issue](https://github.com/envoyproxy/envoy/issues/14394) mentioning about this change.

*Relevant Links*:
>https://github.com/envoyproxy/envoy/issues/14394.
>[Response flag in Access loging](https://www.envoyproxy.io/docs/envoy/v1.15.2/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-retrypolicy-num-retries)

**Comment by yanavlasov** [comment]
Is it possible that upstream server sends "connection: close" on connections that Envoy used to start a request?

**Comment by madhu-shankar** [comment]
the upstream sends connection:close in the response after serving fixed number of requests on each connection. If your question was if upstream sends connection: close on a new request without giving normal response, then no.

**Comment by dozer47528** [comment]
Same problem.
I have an unreachable ip in a cluster, and Envoy 1.15 won't retry.
The accesslog is `503 upstream_reset_before_response_started{local reset} LR`

**Comment by yanavlasov** [comment]
Sorry for not responding earlier. I got confused by you mentioning the server sending `connection: close`. I do not think it is related. It looks like your back end takes time to get ready and start serving connections. This leads to Envoy not being able to connect to back end.
You can increase the number of retries. It is possible that adding health checks could address this issue as well if you have multiple backends.
Adding @snowp for any additional suggestions.
