### ISSUE TITLE
rbac: efective policy ID in standard engine

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#15971]
RBAC currently adds `shadowEffectivePolicyID` field to Dynamic Metadata buy only when shadow engine is being used.

We have a use case where we would need to know which policy has been applied for traffic that has been allowed by the standard engine.

We could add a new `effectivePolicyID` field to Dynamic Metadata, does this seem OK? would it need to be turned on via proto settings?

**Comment by htuch** [comment]
Seems reasonable, @yangminzhu?

**Comment by yangminzhu** [comment]
I think this makes sense to me. This probably can be enabled by default unless there are any concerns about the performance overhead of writing to dynamic metadata on every matched requests.

The change should be small, just need to be consistent with the current shadow engine design: there are two fields `shadowEffectivePolicyID` and `shadowEffectivePolicyResult`. It also supports adding custom prefix (`shadow_rules_stat_prefix`) to the field which is useful when you have multiple RBAC filters.
