### ISSUE TITLE
Build on windows failure

### ISSUE THREAD

**Issue by kunalekawde** [envoyproxy/envoy#15982]
*Title*: *build failure on windows*

*Description*:
I've followed the procedure as per https://github.com/envoyproxy/envoy/tree/main/bazel under windows section. Once the build was done and bazel test failed. Later on after cleanup (bazel clean --expunge) and I'm getting following error:

```
C:\Users\user_xx\envoy>bazel build //source/exe:envoy-static
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 4bb9f5f7d71d826c10b10c65bcaf53847a038f646101c25de10e52d8ffae7a7e
INFO: Analyzed target //source/exe:envoy-static (763 packages loaded, 24096 targets configured).
INFO: Found 1 target...
ERROR: <builtin>: Failed to determine workspace status: Process exited with status 127
/bin/bash: bazel\get_workspace_status: No such file or directory
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 644.487s, Critical Path: 16.93s
INFO: 181 processes: 178 internal, 3 local.
FAILED: Build did NOT complete successfully

```

Other details:
Executing this in windows cmd prompt , had tried git bash but on build error there as well realized that 'link' should refer to MS - VS-Code 'link' and not from gnu.

**Comment by davinci26** [comment]
Hey, thanks for the issue

> Once the build was done and bazel test failed

How did the test fail?


> Executing this in windows cmd prompt , had tried git bash but on build error there as well realized that 'link' should refer to MS - VS-Code 'link' and not from gnu.

Yeah your observation is correct. You might want to ensure that the link.exe that resolves on your PATH is from VC++ Build Tools and not /usr/bin/link.exe from MSYS2, which is determined by their relative ordering in your PATH. A dirtier hacky way is to rename gnu `link.exe` to `link_.exe`.

> Executing this in windows cmd prompt

I know that some people have successfully built the project from cmd but for the time being we only recommend and test that all bazel commands should be executed from MSYS2. Is this an inconvenience for you?

**Comment by kunalekawde** [comment]
> 
> 
> Hey, thanks for the issue
> 
> > Once the build was done and bazel test failed
> 
> How did the test fail?
> 
It was the same error of 'Failed to determine workspace status'

> > Executing this in windows cmd prompt , had tried git bash but on build error there as well realized that 'link' should refer to MS - VS-Code 'link' and not from gnu.
> 
> Yeah your observation is correct. You might want to ensure that the link.exe that resolves on your PATH is from VC++ Build Tools and not /usr/bin/link.exe from MSYS2, which is determined by their relative ordering in your PATH. A dirtier hacky way is to rename gnu `link.exe` to `link_.exe`.
> 
> > Executing this in windows cmd prompt
> 
> I know that some people have successfully built the project from cmd but for the time being we only recommend and test that all bazel commands should be executed from MSYS2. Is this an inconvenience for you?

Executing from MSYS2 also gave error:
```
C:\Windows\Temp\tmp.ZbY9g03Z4B\com_github_luajit_luajit\src>cl /nologo /c /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline /DLUAJIT_ENABLE_LUA52COMPAT /O2 host\minilua.c
minilua.c

C:\Windows\Temp\tmp.ZbY9g03Z4B\com_github_luajit_luajit\src>link /nologo /out:minilua.exe minilua.obj
link: extra operand 'minilua.obj'
Try 'link --help' for more information.

*******************************************************
*** Build FAILED -- Please check the error messages ***
*******************************************************
Traceback (most recent call last):
  File "C:\_eb\execroot\envoy\external\com_github_luajit_luajit\build.py", line 53, in <module>
    win_main()
  File "C:\_eb\execroot\envoy\external\com_github_luajit_luajit\build.py", line 45, in win_main
    shutil.copy("lua51.lib", dst_dir + "/lib")
  File "C:\Users\user_xx\Python38\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\user_xx\Python38\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'lua51.lib'

```
Not sure if this is also due to 'link'
```
$ link --help
Usage: link FILE1 FILE2
  or:  link OPTION
Call the link function to create a link named FILE2 to an existing FILE1.

      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Report any translation bugs to <https://translationproject.org/team/>
Full documentation <https://www.gnu.org/software/coreutils/link>
or available locally via: info '(coreutils) link invocation'

```

**Comment by davinci26** [comment]
The issue that you are seeing is because link.exe resolves to `link.exe` from gnu and not from MSVC.

**You might want to ensure that the link.exe that resolves on your PATH is from VC++ Build Tools and not /usr/bin/link.exe from MSYS2, which is determined by their relative ordering in your PATH. A dirtier hacky way is to rename gnu link.exe to link_.exe.**

**Comment by kunalekawde** [comment]
Thanks @davinci26 , I shall try with this change.
