### ISSUE TITLE
QUIC issues with concurrency > 1

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#15988]
Example configs from https://github.com/envoyproxy/envoy/pull/15987 load, but downstream doesn't work with concurrency > 1

We should either fix the bug causing QUIC to fail with this set up, or reject the config if we know something isn't set up properly.

cc @danzh2010

**Comment by danzh2010** [comment]
It's not a config issue, but the BPF filter doesn't support CID long than 8 bytes across multiple worker threads.

**Comment by moderation** [comment]
Great you found the issue. I've tested with all permutations of sudo, setcap etc. and can't get concurrency > 1 to work.
