### ISSUE TITLE
envoy.reloadable_features.allow_response_for_timeout deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16005]
Your change #12178 (gRPC-Web: Fix failing HTTP/2 requests on some browsers due to empty trailers) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by daixiang0** [comment]
Could I take it if possible?
