### ISSUE TITLE
envoy.reloadable_features.hcm_stream_error_on_invalid_message deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16007]
Your change #12498 (http: send GOAWAY for H2 downstreams  for envoy.overload_actions.disable_http_keepalive) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by akonradi** [comment]
@alyssawilk I think your script is buggy. #12498 added the runtime override `envoy.reloadable_features.overload_manager_disable_keepalive_drain_http2`, not `envoy.reloadable_features.hcm_stream_error_on_invalid_message deprecation`

**Comment by akonradi** [comment]
Oh I see. Part of that PR moved `hcm_stream_error_on_invalid_message` since it was out of order alphabetically

**Comment by alyssawilk** [comment]
yeah, the script uses git blame.  If we really care about ordering we should enforce it via script :-/
