### ISSUE TITLE
envoy.reloadable_features.http_transport_failure_reason_in_body deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16008]
Your change #12321 (router: add transport failure reason to response body) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
ping!

**Comment by daixiang0** [comment]
Could I take it if possible?

**Comment by alyssawilk** [comment]
SG - please take all the stale ones you want :-)
