### ISSUE TITLE
envoy.reloadable_features.activate_timers_next_event_loop deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16003]
Your change #11823 (dispatcher: Run zero-delay timeout timers on the next iteration of the event loop) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by antoniovicente** [comment]
Will try to get to this soon.  Thanks for the reminder.
