### ISSUE TITLE
Refactor common Subscription concerns to a base class

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1601]
Each individual Subscription is managing stats/logging/version tracking. This can be shared in a common base class, e.g. `SubscriptionBaseImpl`.

**Comment by mattklein123** [comment]
@fredlas have you been working on this effectively? Or is this something else? cc @htuch

**Comment by fredlas** [comment]
This is from before my time, so I can't be sure, but I would maybe guess that this has already been done. Did there maybe used to be a {Cds,Eds,etc}Subscription? And that's where the (recently removed) templatization came from?

**Comment by mattklein123** [comment]
@fredlas yeah I think so. I'm guessing we can close this but I'm not sure. @htuch ?

**Comment by htuch** [comment]
Yep, I think this is effectively sorted by now, this goes back to early in the v2 API work.
