### ISSUE TITLE
envoy.reloadable_features.enable_type_url_downgrade_and_upgrade deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16015]
Your change #12913 (Support mixed v2/v3 xDS request/responses ) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by chaoqin-li1123** [comment]
Sure, will clean it up!
