### ISSUE TITLE
deprecated http_match_on_all_headers and http_set_copy_replace_all_headers

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16018]
"envoy.reloadable_features.http_match_on_all_headers",
    "envoy.reloadable_features.http_set_copy_replace_all_headers",

The script didn't work for these two since they merged with issue #195 which doesn't make any sense.

assigning to myself to dig up their origin

**Comment by mattklein123** [comment]
@alyssawilk I think it refers to setec issue 195 :(

**Comment by alyssawilk** [comment]
haha, I'd checked setec _PR_ 195, and it wasn't that.
