### ISSUE TITLE
envoy.reloadable_features.prefer_quic_kernel_bpf_packet_routing deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16011]
Your change #13086 (udp: support forwarding packets between workers) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
ping!

**Comment by ggreenway** [comment]
Looking into this; the runtime override is currently used by tests to make sure we test the non-kernel path. Deleting this will result in a test coverage gap. Need to figure out a way to force this behavior off, but only from tests.

**Comment by ggreenway** [comment]
@alyssawilk what you think about having a static bool on the relevant class, and have the test call `ActiveQuicListenerFactory::setUseBPFPacketRoutingForTest(false); doTheTest(); ActiveQuicListenerFactory::setUseBPFPacketRoutingForTest(true);`? Default of the static bool would be false; only test code would ever change it's value.

**Comment by alyssawilk** [comment]
SGTM, though optionally I'd encourage some helper class which sets and then reverts once it goes out of scope.
