### ISSUE TITLE
Who is the 2021/Q2 stable maintainer?

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#16027]
It seems that we don't have any person who will be involved in stable maintaining. Could we consider it?

**Comment by mattklein123** [comment]
> Could we consider it?

Are you volunteering? :)

**Comment by Shikugawa** [comment]
@mattklein123 Of course I can do that. But @lizan said that we should elect non-Tetrate stable maintainer previously. If he agrees to it, I can continue to work with them.

**Comment by mattklein123** [comment]
Realistically I think it will need to be someone from the Istio community so I will let you all sort it out and discuss. cc @lizan @htuch

**Comment by lizan** [comment]
Yeah we should diverse who is maintaining stable releases. This links to the Istio Networking WG discussion this morning. cc @dmitri-d any interest from Red Hat side? cc @duderino.

**Comment by dmitri-d** [comment]
@lizan: sure thing.

**Comment by htuch** [comment]
Sounds like @dmitri-d is it :)

**Comment by dmitri-d** [comment]
Is there any process that I need to follow?

**Comment by Shikugawa** [comment]
> Is there any process that I need to follow?

@dmitri-d Stable maintainer's task is to track backport for envoy which released for 1 year. (In this quarter, 1.18, 1.17, 1.16, 1.15 are target versions of maintaining) To do this work, you should watch PRs which attached `backport/review` and approve them (it will be done by attaching `backport/approve` tag). After that, you should create backport PR for the target versions of envoys.
