### ISSUE TITLE
Install Envoy with getenvoy went wrong

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#16032]
*Title*: Install Envoy with getenvoy went wrong

*Description*:
Install Envoy with getenvoy went wrong

![image](https://user-images.githubusercontent.com/48784001/114999857-ce84d800-9ed4-11eb-988b-34c18fc2fc32.png)

*Repro steps*:

follow instructions at getenvoy site

**Comment by phlax** [comment]
@Xunzhuo my guess is that this is related to release yesterday

cc @lizan

**Comment by Xunzhuo** [comment]
![image](https://user-images.githubusercontent.com/48784001/115753271-964a3180-a3cd-11eb-9cf2-b53357c508e6.png)
1.18.2 has been released but I try to install it with getenvoy, return 404 as this issue tells and getenvoy try to install v1,17.1

**Comment by lizan** [comment]
Yes I'm working on them. We're also doing migration from Bintray because it will be sunset on May 1.

**Comment by Xunzhuo** [comment]
@lizan tks~ 
It seems like that I can directly get .rpm from http://tetrate.bintray.com/getenvoy-rpm/centos/8/x86_64/stable/Packages/

**Comment by lizan** [comment]
@Xunzhuo it is weird that your package manager is trying to download from `getenvoy-rpm/centos/`**2.2** which is not a valid centos version. What's the environment you're using?

**Comment by Xunzhuo** [comment]
@lizan Ops~ I realize what may caused this weird error, my server runs on a System of Tencent which based on CentOS, and its version is 2.2, so package manager is trying to download from getenvoy-rpm/centos/2.2  which caused 404 response...

**Comment by phlax** [comment]
@Xunzhuo is this resolved ?

afaict all of the tetrate/bintray links are not working - at least the ones linked from Envoy install docs - i think we should keep it open until this can be successfully installed

**Comment by lizan** [comment]
https://status.bintray.com/incidents/x1dvhtdqkcnx
