### ISSUE TITLE
Can't connect to front proxy sandbox

### ISSUE THREAD

**Issue by cdelguercio** [envoyproxy/envoy#1603]
Following the guide in [https://lyft.github.io/envoy/docs/install/sandboxes/front_proxy.html](https://lyft.github.io/envoy/docs/install/sandboxes/front_proxy.html)

**After following all the steps** curl -v $(sudo docker-machine ip default):8000/service/1 **yields:**

*   Trying 192.168.99.100...
* connect to 192.168.99.100 port 8000 failed: Connection refused
* Failed to connect to 192.168.99.100 port 8000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.99.100 port 8000: Connection refused

**sudo docker-machine ls:**

default   -        virtualbox   Running   tcp://192.168.99.100:2376           v17.06.2-ce

curl -v $(sudo docker-machine ip default):2376/service/1 **yields:**

*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 2376 (#0)
> GET /service/1 HTTP/1.1
> Host: 192.168.99.100:2376
> User-Agent: curl/7.47.0
> Accept: */*
> 

* Connection #0 to host 192.168.99.100 left intact

**sudo docker version:**

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

**sudo docker-machine version:**

docker-machine version 0.12.2, build 9371605

**sudo docker-compose version:**

docker-compose version 1.16.0, build ea60ca1
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

**Comment by mattklein123** [comment]
I'm going to guess this is a local docker specific issue as I haven't heard anyone else mention this. Going to close. If this is still an issue please reopen or hop into slack and we can debug.

**Comment by hanoisteve** [comment]
What kind of a docker issue causes this ? As I also am seeing connection refused on a demo application.
