### ISSUE TITLE
Support using downstream TCP destination port for SNI dynamic forward proxy upstream connection

### ISSUE THREAD

**Issue by dippynark** [envoyproxy/envoy#16048]
*Title*: Support using downstream TCP destination port for SNI dynamic forward proxy upstream connection

*Description*:
Currently the [SNI dynamic forward proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter) allows setting a `port_value` to be used for the upstream TCP connection if the [SNI host does not have a port embedded](https://github.com/envoyproxy/envoy/blob/2500a45fd97171c05fe0eff5b2814049719b2070/source/extensions/common/dynamic_forward_proxy/dns_cache.h#L147). It'd be useful if this filter supported using the destination port of the downstream TCP connection (maybe when the `port_value` is zero/unset). As far as I know most TLS clients do not embed the port in the SNI host anyway.

By using IPTables redirection together with the listener filter `envoy.filters.listener.original_dst` this feature would allow Envoy to proxy TLS traffic dynamically to any port depending on which port the client used to connect to Envoy.

I have created a WIP PR to demonstrate this suggestion more concretely.

**Comment by htuch** [comment]
@lizan WDYT?
