### ISSUE TITLE
Allow `UpstreamTlsContext` without any certificates.

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#1604]
When using Envoy as a TLS sidecar, it's useful to have a network shape like:

```
[thing that can't do https] => Envoy => [https service]
```

This doesn't work with the v2 APIs, because `ClientContextConfigImpl` assumes its `common_tls_context` has at least one cert. This seems like a too-strict assumption, most HTTPS connections don't have client certs.

**Comment by mattklein123** [comment]
I think this is a bug.

**Comment by PiotrSikora** [comment]
Sorry, I've misread your comment, yes, this is a regression.

I'll fix it next week - I'm traveling this week and unable to test fix properly.
