### ISSUE TITLE
Allow listening on UNIX sockets

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#1605]
Currently, creating a listener to a `unix://` (v1) or `pipe:` (v2) address will fail. The v1 codepath just crashes with a SIGSEGV, the v2 codepath fails with a somewhat opaque message about `""` not being a valid IP address.

There's some conflicting comments in `listener_manager_impl.cc` about whether this feature is intended to work, so I wanted to at least record somewhere that we want it:

```
ProdListenerComponentFactory::createListenSocket(
// TODO(mattklein123): UDS support.

ListenerImpl::ListenerImpl(
// TODO(htuch): Validate not pipe when doing v2.
```

There's two specific use cases in mind:
* Using sockets as intermediate layers in a multi-filter config, where one filter (say `tcp_proxy`) forwards to one or another listener. Using ports means that all layers are exposed to users with SSH access, but sockets on Linux use standard filesystem permissions and can be stuffed into a protected directory.
* Providing egress to a sandboxed process (e.g. networkless Docker container) via a UNIX socket mounted into the chroot. This is super-fiddly to get working with a TCP socket because :iptables:, and unix sockets are straightforward.

**Comment by mattklein123** [comment]
This is not suppose to work currently. I don't think it would be very hard to get working though if you want to work on it. Likely only a few places need to be changed.

**Comment by jmillikin-stripe** [comment]
I have a super-hacky patch that just comments out the safety checks and it seems to work. Probably I'll have it PR-able some time next week.

**Comment by htuch** [comment]
The crash on v1 is basically because we don't have JSON schema guarding against this. The v2 is caveat emptor until we have proto constraints (Real Soon Now). Since @jmillikin-stripe is planning to PR, I think we can leave it as is until the PR.

**Comment by mattklein123** [comment]
Yeah IIRC I think I already did most of the work to make it work, even with hot restart, I just never finished it up and added integration tests. I think other than adding some tests it will be very easy to finish up.

**Comment by mpuncel** [comment]
+1 for this. We're looking at deploying envoy to multi-tenant machines, and we would like to set up a listener for each tenant for egress using a unix socket 1) so we don't have to worry about port conflicts and 2) so we can use filesystem permissions to control access to the listener

**Comment by jnb** [comment]
Another +1 for this.  For our setup we have HAProxy listening on Unix sockets.  We're thinking about replacing HAProxy with Envoy, but need a way to get it to also listen on Unix sockets.

**Comment by syml** [comment]
Can hot restart work with abstract sockets? It seems there has to be a moment where the socket is unbound, and traffic would be lost then.
Can we consider a first PR without hot restart support? Especially for abstract sockets, which might be a permanent incompatibility anyway.

**Comment by mattklein123** [comment]
I think even abstract sockets should work as we can pass the FDs across the UDS transport like we do for everything else. All that's really needed is the name to look it up by.

For everyone that is asking for this, I'm pretty certain this basically already works. There are probably a few asserts that need to be removed, maybe a tiny amount of logic to be added, and some tests. That's it.
