### ISSUE TITLE
log resolved admin port

### ISSUE THREAD

**Issue by codefromthecrypt** [envoyproxy/envoy#16050]
*Title*:
log resolved admin port

*Description*:
Right now, the admin port can be set to zero, avoiding port conflicts. It prints to console like so:
```
[external/envoy/source/server/server.cc:486] admin address: 127.0.0.1:0
```

It would be nice if this logged the actual listen port as that can be easier for "expect" like tools who parse console out vs determining the admin port file and parsing that.

**Comment by htuch** [comment]
This makes sense, I'll leave this as an open issue, but you might also find https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-admin-address-path useful.

**Comment by mk46** [comment]
@htuch  I would like to work on this.

**Comment by htuch** [comment]
@mk46 sure, assigned!
