### ISSUE TITLE
how can I use http connect proxy in istio?

### ISSUE THREAD

**Issue by rtttech** [envoyproxy/envoy#16056]
How can I achieve the following result in istio?
 
Features implemented in this pull: https://github.com/envoyproxy/envoy/pull/14552

configure example:
envoy/configs/terminate_http2_post.yaml

**Comment by alyssawilk** [comment]
For Envoy set up, I think the example configs are the way to go. :-)
For Istio-specific set up I don't think we can help you though @lambdai  may have pointers.

**Comment by lambdai** [comment]
@rtttech For now you have to use EnvoyFilter CR. 
https://istio.io/latest/docs/reference/config/networking/envoy-filter/

**Comment by rtttech** [comment]
Istio does not support upgrade_configs currently. Is it possible to set this parameter in envoy-filter?
