### ISSUE TITLE
Multiple virtual hosts issue

### ISSUE THREAD

**Issue by BatanGaming** [envoyproxy/envoy#16064]
(Sorry, cannot come up with issue's title)

Let's say we have 4 virtual hosts for domain `example.com`:

- `stand1.*`
- `stand1.ws.*`
- `ws.*`
- `*`

When I go to page `stand1.example.com` frontend makes http request to `stand1.example.com/api/service1` and connects to `stand1.ws.example.com` by websocket. 
In `stand1.example.com/api/service1` Service1  makes request to `stand1.example.com/api/service2`.  
But when I do multiple requests - about 10-15 (I was strongly pressing to F5 button) - domain changes to `example.com` but not for all requests. 
For websocket it changes to `ws.example.com` and for `service1 -> service2` to `example.com` so `stand1` discarded but not for `frontend -> service1` request. 

I'm pretty sure that my web apps works fine and urls are correct. Maybe there's some behavior like:

 **_`stand1.ws.*` virtual host busy so let's pass request to `ws.*` since they are similar_?**

Another one question: how to configure http -> https redirection if http listener uses 80 port and https - 443?
I tried:
- `require_tls: ALL` for http listener (doesn't work)
- `https_redirection: true` for http listener (doesn't work)
- `https_redirection: true` with `port_redirection: 443` for http listener (doesn't work)

**Comment by BatanGaming** [comment]
I stopped my prod (which is on `example.com`) and now everything is ok. Any ideas?

**Comment by BatanGaming** [comment]
So, I still didn't find out the solution

**Comment by lambdai** [comment]
@BatanGaming  Given the http request and a route table, route match should be deterministic.
Is it possible you have multiple http conn manager configs(so as more than one route table) and SNI decides which HCM to use? 
The combination of <SNI, httprequest>  match is not deterministic.
See https://github.com/envoyproxy/envoy/issues/6767

Try rename the route with unique names and see if the desired route is selected.

**Comment by BatanGaming** [comment]
@lambdai I'm not sure about multiple route tables. We don't have multiple http connection managers but we have multiple virtual hosts which have own route tables. So, is it what you're talking about?

Also, can you please tell how to configure http->https redirection? I wrote above what I already have tested

**Comment by lambdai** [comment]
> I'm not sure about multiple route tables

Do you happen to have multiple filter chains in the same listener?

```
     "name": "0.0.0.0_443",
     ...
       "filter_chains": [
        {
         "filter_chain_match": {
          "server_names": [
           "*.foo.com"
          ]
         },
         {
         "filter_chain_match": {
          "server_names": [
           "*.bar.com"
          ]
         },
     ]

**Comment by BatanGaming** [comment]
I got it. No, we have only one http conn manager

**Comment by BatanGaming** [comment]
HI, @lambdai, I have good news. I removed wildcard domains from certificate and now it seems to be working fine. Maybe it's really related to #6767. So, I still have one open question - how to configure http->https redirect?
