### ISSUE TITLE
ext_proc for external waf

### ISSUE THREAD

**Issue by ynsta** [envoyproxy/envoy#16081]
*Title*: Implementing an external web application firewall using ext_proc

*Description*:

I saw that you were looking for potential usages for ext_proc. I was thinking on experimenting with ext_proc to implement a waf with [ModSecurity](https://github.com/SpiderLabs/ModSecurity).

This would permit to have a ModSecurity / envoys base waf that is not directly linked with envoy as in https://github.com/octarinesec/ModSecurity-envoy but that use a defined interface.

So this external processor should be able to perform all phases of mod security :

* Request headers processing
* Request body processing
* Response headers processing
* Response body processing
* Logging

Do you think this is compatible with what you want to do with ext_proc.

**Comment by snowp** [comment]
@gbrail

**Comment by asraa** [comment]
@envoyproxy/security-team this may be interesting

**Comment by gbrail** [comment]
Yes, WAF-like stuff is certainly one of the things ext_proc is intended to help with. There are a few capabilities that have been designed (but not all implemented) that can help with this. Specifically:

1) If initially you only need to look at HTTP headers, then you can get started right now with a processor that looks at the headers and rejects a request.
2) Right now you can see the HTTP body, but only in buffered mode -- this will be a limitation for a general-purpose WAF. I'm interested in discussing what other body-processing modes could possibly help here but they all have tradeoffs.
3) We designed an "async mode" in which we send data to the processor but do not wait for a response. This may be helpful in some cases where you need to efficiently monitor traffic but don't need to act on it immediately.

**Comment by ynsta** [comment]
Thanks, for the second item I'll look at what are the limitations and compare with current apache or nginx, modsecurity modules.
