### ISSUE TITLE
hotkey for redis: find hotkeys by heat

### ISSUE THREAD

**Issue by littlegreyzhang** [envoyproxy/envoy#16096]
hotkey for redis: find hotkeys by heat

Can I submit a PR to add the following feature? @mattklein123  @yiyouguisu

Description:
> Count some(1\~255) keys of commands. Then convert the frequence to heat(0\~255) by logarithm function.

We can do this in client/proxy/redis.
Relative Merits:
> client: It's simple and direct. But it need to hack into the client code. And it's difficult to adapt to multi language framework.

> proxy: It's completely transparent to client & redis. It can solve the problem of language heterogeneity.

> redis(--hotkeys): It will scan the entire keyspace. Therefore, the scanning time is positively correlated with the number of keys.

> redis(MONITOR): In some particular cases, running a single MONITOR client can reduce the throughput by more than 50%. Running more MONITOR clients will reduce throughput even more.

We just want to find some hotkeys. Not the heat of all the keys. So I want to use some cache algorithm(such as LFU) to implement this feature in proxy(envoy).

Relevant Links:
> https://github.com/redis/redis/pull/4392
> https://redis.io/topics/lru-cache
> https://redis.io/commands/monitor

**Comment by asraa** [comment]
@msukalski  @henryyyang

**Comment by mattklein123** [comment]
This sounds like a reasonable feature to add to me.

**Comment by littlegreyzhang** [comment]
I will do it.

**Comment by littlegreyzhang** [comment]
I need help for pass the linux_x64 gcc check.
