### ISSUE TITLE
Prometheus stats for listener with stat_prefix set have wrong labels/extraction

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#16103]
If a listener has a `stat_prefix` configured (new in Envoy 1.18) and the stat_prefix does not match the regular expression for an address (`1.2.3.4_443` or similar), the prometheus stats will include the `stat_prefix` in the stat name instead of in a label, eg `envoy_listener_vip_downstream_cx_overflow{}` for `stat_prefix: vip`.

The correct output is `envoy_listener_downstream_cx_overflow{envoy_listener_address="vip"}`

**Comment by jmarantz** [comment]
I'm trying to understand this issue more specifically. What is the stat_prefix and where is that specified?

Also, it's worth pointing out https://github.com/envoyproxy/envoy/pull/17357 which seems vaguely related, though that particular PR is focused on solving a problem for metrics defined by users in wasm code and how to differentiate them from the ones defined by Envoy C++ code. But it has in common with this issue:
 * Prometheus as a stats sink
 * stat-name prefixes

**Comment by ggreenway** [comment]
Sorry, this is all directly the result of #15951, which added a configurable [stat_prefix](https://github.com/envoyproxy/envoy/pull/15951/files#diff-f76ce906fb5b9dde8e23a117a524f178e43b28c1002dc7d1cd3d98ac134c6a23R111) to listeners. Before this, the stats were always prefixed with the ip:port of the listener (converting colons to underscores).
