### ISSUE TITLE
move simple LRU cache code into envoy

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#16108]
In this [PR](https://github.com/envoyproxy/envoy/pull/14341), jwt_authn is adding cache feature JWT token.  

It is using a simple_LRU_cache map from [here](https://github.com/google/jwt_verify_lib/tree/master/simple_lru_cache)

This map supports O(1) lookup with LRU auto purge.

This simple_LRU_cache code can be used by other Envoy modules, hence propose to move this code into Envoy.

**Comment by wrowe** [comment]
Reopening on request for further development

**Comment by wrowe** [comment]
Note @mk46 will be following this up per https://github.com/envoyproxy/envoy/pull/14341/files#r661736772

**Comment by mk46** [comment]
@wrowe Once #14341  got merged, will start working.  Please feel free to assign me.
