### ISSUE TITLE
Use "Via: envoy" header instead of "Server: envoy"

### ISSUE THREAD

**Issue by lewislbr** [envoyproxy/envoy#16118]
**Title**
Use `Via: envoy` header instead of `Server: envoy`

**Description**
Currently, envoy attaches a `Server: envoy` header to all responses. This overwrites any `Server` header defined upstream. 

The [`Server` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) should be used by the server that generates the response in its origin, and be respected if set.

The [`Via` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via) could be used instead to inform that the request/response was handled with envoy.

**Relevant Links**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server
https://tools.ietf.org/html/rfc7231#section-7.4.2
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via
https://tools.ietf.org/html/rfc7230#section-5.7.1

**Comment by asraa** [comment]
@yanavlasov also while @alyssawilk is out, maybe this makes sense. it would need to be flag protected if implemented.

**Comment by mattklein123** [comment]
See the "server_name", "server_header_transformation," and "via" options here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto

**Comment by lewislbr** [comment]
@mattklein123 This is more about using `Via` instead of `Server` to add the proxy information, rather than the option to set up any of them, as in the case of `Server` it’s usually defined upstream. Is there any reason why `Server` is used?

**Comment by mattklein123** [comment]
Envoy's original use was as a gateway in which it was desired to obfuscate the real backend server, so server was overwritten. I don't think it's worth changing this default behavior given that it can all be controlled via configuration.
