### ISSUE TITLE
Webassembly Runtime Guide

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#16111]
As envoy source code shows:
 
![image](https://user-images.githubusercontent.com/48784001/115530576-7b40ca00-a2c6-11eb-9767-e3d26c719162.png)

How can I run wasm in Wasmtime, Wavm.. instead of v8 engine in Envoy ?

I try to edit directly envoy config to change runtime field to wasmtime or wavm, but it seems not to work right.

![image](https://user-images.githubusercontent.com/48784001/115639947-6d338d80-a348-11eb-866d-6a7c11d4d71a.png)

Is it now Envoy just support v8 to run wasm or something else? How can I build envoy with these runtime?

**Comment by asraa** [comment]
As seen here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto
those are not enabled by default in builds.
You will need to build Envoy yourself with --define wasm=wavm to enable this config setting https://github.com/envoyproxy/envoy/blob/cfc04c4ff221ef2bdbcdf7d6de0d1c8b37e08db6/bazel/BUILD#L396

I hope.

**Comment by Xunzhuo** [comment]
@asraa  Thanks so much~
