### ISSUE TITLE
Handling millions of rules

### ISSUE THREAD

**Issue by xpepermint** [envoyproxy/envoy#16117]
I'd like to think of my envoy service as the gateway handling all the incoming/outgoing traffic for all the services I host for my clients. I wonder how such a setup would perform in case I have 1 million clients and each client has its own domain, http/grpc rules, and such. 

Because the envoy must calculate all these conditions on each request I expect this to be much less performant compare to running a dedicated envoy instance per client where the envoy holds only a few rules. However, running multiple instances would require more server resources.

Is my understanding correct? What would be the best path forward and the most long-term sustainable setup for such k8s system that handles many domains and many http/grpc rules? Should I go with envoy-per-client or shared-envoy for all clients?

**Comment by tonya11en** [comment]
It's tough for me to give my opinion without understanding your scenario better, but for these multi-tenant proxy use cases, you may consider using [scoped routes](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#route-scope). It sounds like you're considering an Envoy per tenant as a method of config namespacing, so the scoped routes may allow you to keep it all on a single Envoy.

**Comment by xpepermint** [comment]
Thanks, @tonya11en for your reply. Basically, the use case is actually super simple and we can debate on a theoretical level. I'd like to host N domains where each domain has N rules. The question is more about how the envoy searches among all defined rules. The linear search would be slow, the indexed list would be faster but is it fast enough to have the config sized in MBs?

**Comment by snowp** [comment]
It depends on the matching logic required for these domains, if you have N unique domains with M <<<< N rules per domain, you could list the N domains as virtual hosts (exact match here gives you a hash lookup), and provide the M rules for each virtual host which will be searched linearly. If you need more complicated domain lookup (e.g. virtual host wildcard) you end up in linear scan territory again. 

There aren't any specific limits to how large this can be, but you might find that trying to maintain a hash map of millions of domains might be expensive in terms of memory. Some of the work done around generic matching could be useful here to provide sub-linear matching with a smaller memory footprint, but we're not yet at a point where that can be used for routing.

**Comment by xpepermint** [comment]
This is helpful @snowp, thank you. I've seen different implementations for the hash lookup but I'd say this part is the fastest possible and is provided by the programing language itself so should be good. Linear lookups on the second level should not cause problems. My biggest fear is/was the level one (domain level) lookup where the "most expensive" lookup happens. 

So if I understand this correctly, matching based on domain (`vhost`) is fast. Could you scaffold an example configuration for me, just to make sure I get it right?
