### ISSUE TITLE
original_dst : use local address with transparent sockets and TPROXY

### ISSUE THREAD

**Issue by tomastigera** [envoyproxy/envoy#16130]
*Title*: *original_dst : use local address with transparent sockets and TPROXY*

*Description*:

Use the local address if the listener uses `transparent` or allow user to set such an option on the original_dst.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto.html?highlight=transparent

*Reasoning:*

Original destination uses `SO_ORIGINAL_DST` to get the original destination https://github.com/envoyproxy/envoy/blob/118f66e87bae3961c5726ad46239a85cdadc316f/source/common/network/utility.cc#L398

This method does not provide the desired result in all cases. Firstly, it depends on conntrack and specifically on the default conntrack zone. Secondly, if there is DNAT between TPROXY and the actual socket, as the nat table is after mangle table. Then the result is the pre-DNAT address. It is indeed the original dest (the service IP), however, it is not the original dest from the point of view of the actual connection seen by envoy.

The `SO_ORIGINAL_DST` works well with the REDIRECT target as that uses DNAT to redirect the packet and returns the original dest address instead of the local one.

In case of TPROXY, there is no DNAT involved in the redirection, therefore the local address of the socket is the same as the original destination. Therefore using `localAddress` that uses the `getsockname()`  system call is enough to return the original destination of the connection. It works well also in the case of DNAT happening after TPROXY. It also works in case there is no conntrack or when the conntrack happens in other than the default zone.

[optional *Relevant Links*:]

`localAddress`

https://github.com/envoyproxy/envoy/blob/118f66e87bae3961c5726ad46239a85cdadc316f/source/common/network/io_socket_handle_impl.cc#L603

**Comment by lambdai** [comment]
Are you suggesting the document of `transparent` should not refer to `original_dst` listener filter?

**Comment by tomastigera** [comment]
This is a prototype I tested in my usecase. It gets the original destination after DNAT that occurs between TPROXY and envoy and works well also in the regular case of a simple redirection.

https://github.com/tomastigera/envoy/commit/7ccdc1b10ce48f701a414e9195c04382ca58752f

**Comment by tomastigera** [comment]
> Are you suggesting the document of `transparent` should not refer to `original_dst` listener filter?

No, I was saying that the original_dst may not get the right address in all cases with TPROXY.

Regarding the documentation of `transparent`, I think the wording is fine. I'd stress that it MUST be set if TPROXY is used.

**Comment by davinci26** [comment]
if you end up doing this work, please tag me on the PR because there might be complications with Windows since we don't support the `IP_TRANSPARENT` option.

Note regarding the current implementation is that if you want to `#ifdef` the code you might want to do it with `#ifdef IP_TRANSPARENT` because `SOL_IP` is defined on Windows but `IP_TRANSPARENT` is not.

**Comment by lambdai** [comment]
do you agree with my proposal? https://github.com/envoyproxy/envoy/issues/16179
I am tortured by always adding duplicated original_dst , and you wants a different implementation of original_dst
And we both don't like extra syscalls.

We should have an option to define the exact original_dst we want.

**Comment by tomastigera** [comment]
> @tomastigera do you agree with my proposal? #16179

I do not quite follow, I might not have enough knowledge, but it seems like `use_original_dst` just add the `original_dst` automatically. 

> I am tortured by always adding duplicated original_dst , and you wants a different implementation of original_dst

I do not want to have a different implementation, I merely want the `original_dst` to use the right method of obtaining the original destination based on the environment it lives in. That is, if traffic is steered towards envoy using the iptables REDIRECT, use the current method and if TPROXY is used, use a different method.

In my proposal, it is determined automatically based on the whether the listening socket is transparent or not. I can see that a user would like to perhaps configure that, but I left it out atm (a) for the sake of simplicity and (b) because I am not so fluent in C++ to make the whole plumbing right away.

Reading the `original_dst_cluster` it does not seem like it would use the `localAddress` unless it was overridden/restored by the `original_dst`. Or would it? Perhaps using whatever is the `localAddress` in case the address wasn't overridden would be just good enough.

> And we both don't like extra syscalls.

Well the added syscall to test whether the socket is transparent can be avoided if there is access to the fact the `transparent` is set to `true`. I added the syscall just for the sake of simplicity to demonstrate in code what I am after.

> We should have an option to define the exact original_dst we want.

+1

**Comment by tomastigera** [comment]
@lambdai any progress in this issue? I saw the PR but it does not seem it merged

**Comment by lambdai** [comment]
sorry i was on something else. I just updated the pr with the implementation and test cases.

**Comment by tomastigera** [comment]
Not quite stale yet, there is an active PR https://github.com/envoyproxy/envoy/pull/16349
