### ISSUE TITLE
Question: How can I build specific version envoy with CI Docker images?

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#16136]
*Title*: *How can I build specific version envoy with CI Docker images?*

*Description*:

I want to build envoy in v1.18.2 with CI Docker images, How can I build specific version envoy with CI Docker images?

**Comment by Xunzhuo** [comment]
After running `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'` , compiled envoy version is 1.19.dev

**Comment by asraa** [comment]
You can checkout 1.18.2 https://github.com/envoyproxy/envoy/tree/v1.18.2 if you'd like to build it yourself.

or https://hub.docker.com/layers/envoyproxy/envoy/v1.18.2/images/sha256-7a348fb943f7aaf526509ffc73c818a9ff33f7d0fd06ce37d9426af081ec1295?context=explore

**Comment by Xunzhuo** [comment]
Thanks @asraa
