### ISSUE TITLE
upstream: per host connection limit support?

### ISSUE THREAD

**Issue by arikachen** [envoyproxy/envoy#16157]
*Title*: per host connection limit support?

*Description*:
using this feature to prevent too much active connections in a host.
```
diff --git a/api/envoy/config/cluster/v3/cluster.proto b/api/envoy/config/cluster/v3/cluster.proto
index f4e3386cf..08accac6e 100644
--- a/api/envoy/config/cluster/v3/cluster.proto
+++ b/api/envoy/config/cluster/v3/cluster.proto
@@ -756,6 +756,9 @@ message Cluster {
   // parameter to 1 will effectively disable keep alive.
   google.protobuf.UInt32Value max_requests_per_connection = 9;

+  // Optional maximum connections for upstream host.
+  google.protobuf.UInt64Value max_connections_per_host = 70;
+
   // Optional :ref:`circuit breaking <arch_overview_circuit_break>` for the cluster.
   CircuitBreakers circuit_breakers = 10;

diff --git a/source/common/conn_pool/conn_pool_base.cc b/source/common/conn_pool/conn_pool_base.cc
index a5df5aadc..9b7a76600 100644
--- a/source/common/conn_pool/conn_pool_base.cc
+++ b/source/common/conn_pool/conn_pool_base.cc
@@ -44,6 +44,11 @@ bool ConnPoolImplBase::shouldCreateNewConnection(float global_preconnect_ratio)
     return pending_streams_.size() > connecting_stream_capacity_;
   }

+  if (host_->cluster().maxConnectionsPerHost() > 0 &&
+      host_->stats().cx_active_.value() > host_->cluster().maxConnectionsPerHost()) {
+    return false;
+  }
+
   // If global preconnecting is on, and this connection is within the global
   // preconnect limit, preconnect.
   // We may eventually want to track preconnect_attempts to allow more preconnecting for

```

**Comment by yanavlasov** [comment]
Hmm, your code change snippet does not match the issue description. From the description it looks like you want per host [circuit breaker](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking) but your code changes preconnect behavior. Can you describe a bit more what you are trying to accomplish, please?

**Comment by arikachen** [comment]
> Hmm, your code change snippet does not match the issue description. From the description it looks like you want per host [circuit breaker](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking) but your code changes preconnect behavior. Can you describe a bit more what you are trying to accomplish, please?

@yanavlasov thanks for you reply.  Yes, per host circuit breaker is more flexible and complex, it will support our requirement.  In my case, we want limit per host connections by cluster level config, all host has the same limit.

**Comment by yanavlasov** [comment]
If all hosts have the same limit, why not then set the cluster circuit breaker limit to number_of_hosts * max_connections_per_host ? This may work if the number_of_hosts stays the same. If loadbalancing works correctly you should have the same number of connection per host.

**Comment by arikachen** [comment]
> If all hosts have the same limit, why not then set the cluster circuit breaker limit to number_of_hosts * max_connections_per_host ? This may work if the number_of_hosts stays the same. If loadbalancing works correctly you should have the same number of connection per host.

It could easily burst connections to number_of_hosts * max_connections_per_host when enable session sticky.

**Comment by yanavlasov** [comment]
Ok, adding @alyssawilk for any more comments in this area

**Comment by alyssawilk** [comment]
Happy to help.  @arikachen could you give a concise explanation of what you're hoping for here?

**Comment by wbpcode** [comment]
@alyssawilk 

Now the circuit breaker supports the limit of the maximum number of connections at cluster granularity. 

But for each host, there is no separate limit on the number of connections. Although a reasonable load balancing algorithm can be configured to ensure that the maximum number of connections per host is roughly the same (The maximum number of connections in the cluster circuit breaker / The number of hosts), **this restriction is not strict**.

We hope that for each host, a strict maximum connection limit can be configured just like a per host circuit breaker.

**Comment by alyssawilk** [comment]
Gotcha.  Yeah that seems a reasonable request and I don't think there's any current bounds today, and especially not cross-thread.

cc @RyanTheOptimist who was interest in global per-host limits too.
