### ISSUE TITLE
rbac: policy order is not respected

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#16152]
*Title*: *RBAC: policy order is not respeted*

*Description*:
RBAC Filter documenation specifies that policies are iterated [in order](catalog|26504) `The policies are examined in order.`, protobuf maps maintain order, but we're then dumping the policies configuration into a `std::map` which orders elements by key, this breaks the specified contract.

The fix seems simple, it would seem we don't actually need a map, so instead of using `std::map<std::string, std::unique_ptr<PolicyMatcher>>` we could probably use a `std::vector<std::pair<std::string, std::unique_ptr<PolicyMatcher>>>`?

Another way to fix this would be to add the policy name to `PolicyMatcher` and just use a `std::vector<std::unique_ptr<PolicyMatcher>>`.

If this seems OK i can have a go at doing this.

**Comment by asraa** [comment]
@yangminzhu

**Comment by htuch** [comment]
This doesn't make sense; protobuf doesn't have any guaranteed ordering of a protobuf map. How can the policies be examined in order?

I think the logic described is supposed to be order agnostic, but this part of the documentation doesn't make sense to me.

**Comment by sschepens** [comment]
> This doesn't make sense; protobuf doesn't have any guaranteed ordering of a protobuf map. How can the policies be examined in order?

I think this is actually not true, i have seen protobuf implementations and they do retain order, java uses a LinkedHashMap to do that. Protocol-wise i think maps are just repeated key-value pairs, so it could theoretically maintain order.

**Comment by htuch** [comment]
Definitely true, see https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.map#Map

**Comment by yangminzhu** [comment]
yeah, I think the doc needs to be fixed and updated for a more accurate description.

If you really want to support ordering, probably you could first sort the keys (policy name) and then evaluate them one-by-one in the map. This avoids API changes and should be no-op for existing users of RBAC filter because there is no guarantee to the order of the evaluation (the doc is wrong).

**Comment by sschepens** [comment]
There is actually an implicit ordering because we use a `std::map` which orders by key. We could probably take advantage of this to order the policies, but should probably be documented or tested because it could change in the future.

**Comment by yangminzhu** [comment]
oh, I see what you mean, yes `std::map` is ordered and it is used internally by the RBAC filter (https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/common/rbac/engine_impl.h#L49), but this is not the order of the protobuf.map which could cause confusions if the user expects the order to be the one in the config API. I think we need a doc update anyway to at least match the current implementation.

**Comment by htuch** [comment]
@yangminzhu @sschepens would one of you be able to work on the doc update here? Thanks

**Comment by yangminzhu** [comment]
@htuch I will take this and update the doc.
