### ISSUE TITLE
Is there any possibilities to support reuse previous connection pools when updating a static cluster

### ISSUE THREAD

**Issue by shaftofchina** [envoyproxy/envoy#16165]
We found that when we use **ClusterManagerImpl::addOrUpdateCluster** to update a static cluster, it will firstly reset the previous clusterEntry which will lead to deconstruction of all related connection pools and of course its established tcp connections. However, our problem is that when we update a static cluster most of its endpoints are the same as previous one, just a few endpoints changed. Therefore, we want to know if it is possible to support reuse previous connection pools of the same host when updating a static cluster.

**Comment by yanavlasov** [comment]
I'm confused about your use of a static cluster. I do not think it was designed to have its members changed. Perhaps you can explain more what you are trying to accomplish.
In any case i think what you are describing is the intended behavior of cluster update.

**Comment by shaftofchina** [comment]
> I'm confused about your use of a static cluster. I do not think it was designed to have its members changed. Perhaps you can explain more what you are trying to accomplish.
> In any case i think what you are describing is the intended behavior of cluster update.

In fact, I may find my situation described at the official docs.

**Comment by shaftofchina** [comment]
> I'm confused about your use of a static cluster. I do not think it was designed to have its members changed. Perhaps you can explain more what you are trying to accomplish.
> In any case i think what you are describing is the intended behavior of cluster update.
I may find my problem described at the official docs.For some reason, we use CDS without EDS by specifying fully static clusters. 
![image](https://user-images.githubusercontent.com/26037176/116175325-a9009580-a742-11eb-9dde-bb1d1729933d.png)

**Comment by yanavlasov** [comment]
Ah, this use case. I think people who use CDS typically use EDS as well. Given this I think there will be little interest in making this use work as you'd like it. If you can code it, feel free to submit a PR.

**Comment by shaftofchina** [comment]
> Ah, this use case. I think people who use CDS typically use EDS as well. Given this I think there will be little interest in making this use work as you'd like it. If you can code it, feel free to submit a PR.

Glad to do so. Actually, I am working on it now.
