### ISSUE TITLE
Access Log Command Operator: REQUEST_TX_DURATION

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#16188]
Envoy already has four access log command operators of duration, i.e., DURATION, REQUEST_DURATION, RESPONSE_DURATION, RESPONSE_TX_DURATION, but it seems impossible to calculate the duration from the start time to the last byte of the request sent to the upstream with these commands.

The duration might be named REQUEST_TX_DURATION which could be used to observe Envoy's own delay in the downstream to upstream direction.

The existing StreamInfo interface can get or calculate REQUEST_TX_DURATION directly, we only need to add a field extractor in the StreamInfoFormatter.

**Comment by yanavlasov** [comment]
Feel free to submit a PR with this change.

**Comment by WeavingGao** [comment]
@yanavlasov I submit a PR

**Comment by WeavingGao** [comment]
> Feel free to submit a PR with this change.
