### ISSUE TITLE
Add createFilterFactoryFromProto for all existing network/HTTP filters

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1619]
Need to define proto schema and `createFilterFactoryFromProto` variants.

**Comment by mattklein123** [comment]
@rshriram the only thing left is transcoder filter, right? Can you ACK that you are doing that? Otherwise I can do it tomorrow.

**Comment by rshriram** [comment]
Sorry just seeing this. Can close this

**Comment by mattklein123** [comment]
Finished!
