### ISSUE TITLE
how to modify envoy timezone ,for ingressgateway

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#16204]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
[root@master01 ~]# kubectl cp /usr/share/zoneinfo/Asia/Shanghai istio-ingressgateway-d46c4ff9b-6qh4k:/etc/localtime -n istio-system
tar: localtime: Cannot open: Read-only file system
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by 13567436138** [comment]
su root,anybody know the password of root

**Comment by hobbytp** [comment]
> su root,anybody know the password of root

You cannot su root in istio ingress-gateway which is using not-root now. currently changing timezone in istio/envoy is also not supported. so
1. you could update the istio-ingress gateway to use root privilege (default is not root), and then try again.
2. Or changing the timezone in your own image.
