### ISSUE TITLE
Increase in upstream_cx_active due to setting max_connection_duration config

### ISSUE THREAD

**Issue by bhatiakartik10** [envoyproxy/envoy#16215]
*Title*: *Observed increase in `upstream_cx_active` after setting `max_connection_duration` to 120 seconds*

*Description*:
We recently deployed a new configuration by setting `max_connection_duration` to 120 seconds,  to limit long-lived downstream connections. However during deployment there was a significant increase in `envoy_cluster_upstream_cx_active` statistic as it went from around 1400 to 2000. `envoy_cluster_upstream_cx_total` and all downstream statistics were not impacted.  Attached is the graph below.

<img width="1512" alt="Screenshot 2021-04-28 at 10 24 07 PM" src="https://user-images.githubusercontent.com/32274048/116443460-4fe34f80-a871-11eb-9aea-709719bb522b.png">
(upstream_cx_active on left Y axis, upstream_cx_total on right, incremental deployment starts at 16:50 and ends 18:30). 
<br/><br/>
Few Notes:

1.  No other envoy configuration change was made.
2. The clusters are defined using original destination config, with `idle_timeout` being set to 60s in each of them.
3. There was no change in number of incoming requests, or the upstream setup during this time.
4. Change was deployed on different regional stacks, with each region varying in number of downstream clients and throughput of requests. Each region was impacted with some more than others, but could not find any correlation.
5. Running envoy v1.15

My questions:

1.  Can you explain the difference between the `upstream_cx_active` and `upstream_cx_total` statistics. From the documentation I understand one is gauge, while the other is a count, but wouldn't a change in one affect the other?
2.  Is this behaviour expected? I could not find any related issue or indications in the documentation. And no change in downstream connection stats indicate something weird is happening here.

*Relevant Links*:
>https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#core-httpprotocoloptions

**Comment by yanavlasov** [comment]
The `upstream_cx_active` gauge tracks open connections, it can go and down as connections are opened and closed. The `upstream_cx_total` counter tracks total number of connection that were made to the cluster, it includes both currently open connections and connections that were closed.
Why you are seeing what you are seeing in your graphs is up to you to figure out based on how your software plots these values.
