### ISSUE TITLE
web socket keep alive no longer working version upgraded from v17 to v18

### ISSUE THREAD

**Issue by mattygyk** [envoyproxy/envoy#16224]
Hi
 
we are running envoy proxy in front of a janus WebRTC server using websockets

Using envoy version envoy :
version: d6a4496e712d7a2335b26e2f76210d5904002c26/1.17.1/clean-getenvoy-bb8060d-envoy/RELEASE/BoringSSL works fine and this works and I we can see two way keep alive going over the websocket.

When we update the envoy proxy to version to:
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

the keep alive no longer works and therefore our sessions disconnect .

the envoy.yaml is basically the default and other than any existing changes to v3 api .

Suspect its related to  "max_stream_duration" 

Can anyone advise ?

**Comment by yanavlasov** [comment]
@alyssawilk might know if something has changed in this area

**Comment by alyssawilk** [comment]
could be related to https://github.com/envoyproxy/envoy/issues/16129 ?
