### ISSUE TITLE
Include an additional header and problem details in the message body of the response for overload scenarios

### ISSUE THREAD

**Issue by sha-rath** [envoyproxy/envoy#16227]
*Title*: *: Include an additional header and problem details in the message body of the response for overload scenarios*

*Description*:
We know that _x-envoy-overloaded_ header is set on the downstream response if a request is dropped either due to maintenance mode or upstream circuit breaking. 

We have a specific requirement where an additional header and a JSON content (ProblemDetails) has to be added to the message body of the response for the above scenario along with the _x-envoy-overloaded header_. This is a 3GPP 5G specific requirement which states the following:

> > 3GPP 29.500
> > Protocol and application errors common to several 5GC SBI API specifications for which the NF shall include in the HTTP response a payload body ("ProblemDetails" data structure or application specific error data structure) with the "cause" attribute indicating corresponding error are listed in table 5.2.7.2-1.
> 
> NF_CONGESTION | 503 Service   Unavailable | The NF   experiences congestion and performs overload control, which does not allow   the request to be processed. (NOTE 4)
> -- | -- | --
> 
> It also states “This means that all 3GPP NFs shall support the processing of the specific HTTP status code for the specific HTTP method, when received in a HTTP response message. In such cases, the 3GPP NF shall also support the handling of the "ProblemDetails" JSON object with the Content-Type header field set to the value "application/problem+json" for HTTP status codes 4xx and 5xx, if the corresponding API definition in the related technical specification does not specify another response body for the corresponding status code”

What is the best way to do this? Could this be provided as a configurable option to the user, so that when this is set, the following response is observed in case of an overload? 

```
HTTP/1.1 503 Service Unavailable
content-type: application/problem+json
x-envoy-overloaded: true
date: Tue, 16 Feb 2021 10:55:06 GMT
server: istio-envoy 
* Connection #0 to host 10.106.177.180 left intact
{
      " cause": "NF_CONGESTION"
}
```
Note : In our use case, only the “cause” attribute of the ProblemDetails JSON Object was considered.

Currently, we have made some code changes and have exposed a helm chart parameter for the user to configure. When this is enabled, we add/overwrite the original message body with ProblemDetails and also include the Content-Type header.

Awaiting some valuable feedback on this and also, are there any better approaches to have this feature implemented?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-overloaded
https://tools.ietf.org/html/rfc7807

**Comment by akonradi** [comment]
This would be trivial with a custom HTTP filter. In the overload manager config you'd declare an action with a custom name with appropriate triggers connected to it, then add the header iff overloaded. If it is useful, this could even be added to upstream Envoy. I imagine a config with two fields: "header name" and "overload action to watch".
