### ISSUE TITLE
regression test QUIC crash caused by the import

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16234]
See discussion on #16100 (h/t @moderation for discovery)

**Comment by DavidSchinazi** [comment]
Thanks for filing. I'll take care of this.

**Comment by alyssawilk** [comment]
Awesome, thanks!

**Comment by DavidSchinazi** [comment]
I'm able to reproduce the crash at 58a13570f3f4dea9bad8b8fa5e1221d7ed5056de (from 2021-04-23) but not at 82e33f6ee0607698f6ed357cf2ec2375949c76b9 (from today 2021-04-29). @moderation could you please try again on tip of tree with your setup to confirm whether this is fixed?

**Comment by moderation** [comment]
I can't reproduce now either. I did try this morning after https://github.com/envoyproxy/envoy/pull/15912 but before https://github.com/envoyproxy/envoy/pull/16151 and was able to crash. But now everything looks good! Thanks

**Comment by DavidSchinazi** [comment]
Thanks! Let's keep this issue open to track the addition of a regression test, but it looks like we resolved the crash.
