### ISSUE TITLE
gRPC proto file generation question

### ISSUE THREAD

**Issue by dragonbone81** [envoyproxy/envoy#16240]
Hi all, I'm trying to use the ext_proc filter which requires to use grpc proto files. I know there are proto files defined in envoy, but I was wondering how to use them to generate the generated code. Do we just copy the files and generate it ourselves (this seems strange). Do we use https://github.com/envoyproxy/go-control-plane that already has the generated files (saw this suggested elsewhere). Or should we be doing something else?
Thanks!

**Comment by yanavlasov** [comment]
You may ask in envoy-dev slack channel.

**Comment by gbrail** [comment]
This is one of the consequences of Envoy's extensive use of protobufs -- you can't just compile a .proto or two and get stubs that work -- everything depends on something else.

If you are building in Go, then go-control-plane is indeed the right place to go -- people and tools in the Envoy community keep that up to date.

**Comment by dragonbone81** [comment]
@gbrail Thanks for the verification on using go-control-plane!
