### ISSUE TITLE
Crash support: Restore crash context on filter's posted callback

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#16241]
Crash support: Restore crash context on filter's posted callback

*Description*:

There exists a variety of filters that stop iteration to make an asynchronous call that on completion calls back the filter. Lets call these *cb_filters*. The issue is that the context used for crash dumping gets lost. Hence if we crashed in this callstack, we’d be missing the crash dumps that we’d usually get.

Proposed solution:
- *cb_filters* can easily reconstruct the crash dump context (the necessary `ScopeTrackedObject`) via a method on the `ActiveStream` / `Filter Manager`.
- If *cb_filters* do not add the context themselves, we complain, and add restore the crash context at a common entry point such as `commonContinue()`.

**Comment by antoniovicente** [comment]
cc @alyssawilk @junr03 

Thanks for improving crash handlers by also dumping request information when filters are resumed via commonContinue().
