### ISSUE TITLE
[xds:EDS/SRDS/LDS] do not process the resources if the protobuf is the same as last version 

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#16257]
*Title*: No need to instantiate from protobufs if the config is the same as last version for LDS/SRDS/EDS

*Description*:
  In CDS/RDS, Envoy will skip the resource if the protobuf is the same as last version.  
  We should do the same for SRDS/LDS/EDS (if not yet), to save CPU and other unnecessary cost (draining etc..).

**Comment by stevenzzzz** [comment]
CC @AndresGuedez @antoniovicente

**Comment by stevenzzzz** [comment]
we can skip validation as well if the lds/rds impl keeps last version's protobuf, if the protobuf is the same.

**Comment by antoniovicente** [comment]
@yanavlasov @htuch

**Comment by htuch** [comment]
I think this is most reasonable to do in delta xDS, where the config version is per-resource and included inline with the resource proto. We probably want to make this runtime controlled; there are probably deployments out there that don't treat version and resource name as cache identifiers (which is something we're working to solve explicitly with `xdstp://` naming).

**Comment by htuch** [comment]
Delta xDS expects that the management server does not send unchanged resources. It's fine for the client to still dedup, but in a properly functioning environment, this case should not be regular behavior.

**Comment by antoniovicente** [comment]
The client has payed a significant cost by just downloading the redundant config updates.  It would be best to prioritize optimization of the config provider, not Envoy.
