### ISSUE TITLE
bazel build config_load_check_tool failure

### ISSUE THREAD

**Issue by mattygyk** [envoyproxy/envoy#16250]
Hi I am installing config_load_check_tool using bazel on ubuntu 16

Command:
bazel build //test/tools/config_load_check:config_load_check_tool  --sandbox_debug

Error.

Target //test/tools/config_load_check:config_load_check_tool failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/024c378c6e455b9118e04c1795b58121/external/envoy_api/envoy/annotations/BUILD:5:18 error executing shell command: '/bin/bash -c #!/usr/bin/env bash
function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf...' failed (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Am new to bazel so any help would be much appreciated , thanks

**Comment by yanavlasov** [comment]
You may want to ask on envoy-dev slack channel about this problem.

**Comment by mattygyk** [comment]
> You may want to ask on envoy-dev slack channel about this problem.

Thanks for the advice.
