### ISSUE TITLE
Enforce verification of signed commits

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16252]
### description

currently we dont have any enforcement of signed commits - iirc this is doable on PRs, but i think its a repo setting (rather than CI)

related github info here https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

**Comment by phlax** [comment]
cc @lizan @mattklein123 @htuch

**Comment by phlax** [comment]
to clarify - this is **not** DCO - its verify the signature key with github - ie not just signing but verifying the signing key

**Comment by htuch** [comment]
I think we need to think about dev experience here if we want to make this mandatory. Specifically, we need to make sure that our dev documentation and get-going-on-your-first-pr setup scripts make this fairly transparent. I agree with the value of signed commits, but we can't just tell folks to go learn GPG without providing a TL;DR.

**Comment by phlax** [comment]
agreed - re documenting

re having to know gpg - as we enforce dco i thought that we would already have required gpg - altho checking now im not so sure - it seems you can sign a commit with just text

**Comment by ggreenway** [comment]
> it seems you can sign a commit with just text

Yep, DCO is just text in the commit message. No cryptography involved.

**Comment by ggreenway** [comment]
Given our squash-merge workflow, do the signed commits even make it into the history? I think they might just be part of the PR history.

**Comment by phlax** [comment]
well - for users that dont use gpg to push and have their public gpg key uploaded to github it shows `unverified` next to their username on commits

iirc you can enforce that PRs must have this (not 100% reading the docs, and not sure what our current setting is)
