### ISSUE TITLE
How to control accees log file sizs on access_log config?

### ISSUE THREAD

**Issue by malza321** [envoyproxy/envoy#16265]
Hi! I'm struggling to find out how to set up log file size or make new log file everyday on envoy.

filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout

This is my config.

And also log format time is not correct. That is not local time here. I also want to know how to use %z option.

Envoy.yaml config will be great help! Cuz I Use envoy binary file to run and config file only.

**Comment by ggreenway** [comment]
For log size management, I recommend logrotate (https://linux.die.net/man/8/logrotate)

**Comment by ggreenway** [comment]
For the time formatting, does the documentation for `START_TIME` on https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-strings answer your question?

**Comment by malza321** [comment]
> For log size management, I recommend logrotate (https://linux.die.net/man/8/logrotate)

thanks!

but I don't have root permission in my company...

**Comment by malza321** [comment]
> For the time formatting, does the documentation for `START_TIME` on https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-strings answer your question?

I want to change utc time to my localtime. and I tried %z and it show +00:00 in the end of time text.

I want +09:00 in the end of time text or want to chanege $H to $(H+9). is that possible?
