### ISSUE TITLE
add H3 support for CONNECT / upgrades

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16291]
Lets us enable
DownstreamProtocolIntegrationTest, FaultyFilterWithConnect
DownstreamProtocolIntegrationTest, ConnectStreamRejection
and as much of tcp_tunneling_integration_test.cc and websocket_integration_test.cc

**Comment by DavidSchinazi** [comment]
I'm actively working on this, will have a PR out soon

**Comment by DavidSchinazi** [comment]
Yup, still on my back burner - got pulled away on something else. Not stale.

**Comment by DavidSchinazi** [comment]
not stale

**Comment by moderation** [comment]
Not stale https://github.com/envoyproxy/envoy/pull/17877

**Comment by alyssawilk** [comment]
Done enough (there's TODOs left, but the feature will be alpha until the spec lands)
