### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by hamdiallam** [envoyproxy/envoy#16308]
*Title*: *SOCKS proxy support*

*Description*:
Are there plans (or a desire) to support SOCKS proxy with envoy? I wasn't able to find anything on the topic

**Comment by lambdai** [comment]
It should be trivial to support SOCKS4 CONNECT command via chained tcp proxy and original dst cluster

**Comment by hamdiallam** [comment]
Can you elaborate on this a little more? I'm looking to implement support

**Comment by hamdiallam** [comment]
Apologies for accidentally closing & re-opening

**Comment by lambdai** [comment]
@hamdiallam From high level, you can create a SOCKS protocol network filter and insert it before TcpProxy network filter.

That SOCKS network filter consumes the SOCKS bytes and set the upstream endpoint address. 

Meanwhile, if you chain the tcp proxy with original_dst cluster, the SOCKS network can set the upstream endpoint transparently to tcp proxy.

The only issue is that TcpProxy currently create the upstream connection way to early(in onNewConnection). It is  before SOCKS filter consuming the SOCKS frame. You can either hack the tcp proxy.
You may want to hack the tcp proxy, or propose the new option in TcpProxy

**Comment by hamdiallam** [comment]
Gotcha thanks, I'll give this a try

**Comment by noob-vivek** [comment]
Would it be a bad idea to write socks protocol as new listener so that tcp proxy could be bypassed? I was wondering to write socks protocol parser as new listener and setup hostname as SNI and attach sni_dynamic_forward_proxy and tcp_proxy in filter chain.
