### ISSUE TITLE
Prevent repokitteh from alerting/assigning code shepherds for `draft` PRs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16302]
### description

currently repokitteh alerts shepherds (eg api, dependency etc) when certain code changes

it would be helpful if this did not happen on PRs that are marked as `draft` 

if this is implemented repokitteh will need to watch for when a PR ceases to be draft (this is what happens i think already in requesting reviews from codeowners - not sure how that works)

apart from the benefit of not notifying about a PR until its ready (and the need to make those changes is confirmed) it also allows you to rebase a WIP PR on another that makes those changes and where the current PR is not expected to land until after the notifiable change has landed - ie the current PR wont end up making those changes

**Comment by phlax** [comment]
cc @itayd

**Comment by itayd** [comment]
is this what @alyssawilk is working on?
