### ISSUE TITLE
Is LUA filter httpCall() non Blocking IO for sync requests.

### ISSUE THREAD

**Issue by sumitaneja** [envoyproxy/envoy#16323]
As per doc https://www.envoyproxy.io/docs/envoy/v1.16.0/configuration/http/http_filters/lua_filter

httpCall API on requst_handle/response_handle has 2 flavors sync and async.  
With Sync flavor will this be non blocking IO or blocking??

Use case-
Above Doc mentions "Do not perform blocking operations from scripts. It is critical for performance that Envoy APIs are used for all IO."
 
Now httpCall will make a sync call to service which may return delayed response (say after 30 seconds).    Want to confirm this is not anti-pattern and It would be non blocking.

**Comment by wbpcode** [comment]
Sync flavor of httpCall only blocks Lua coroutine but will not blocks envoy. So it would be non blocking IO although you use sync httpcall in lua script.
