### ISSUE TITLE
docs building issue:  when running ci/run_envoy_docker.sh 'ci/do_ci.sh docs'

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#16321]
*Title*: docs building issue:  when running ci/run_envoy_docker.sh 'ci/do_ci.sh docs'

*Description*:
ci/run_envoy_docker.sh 'ci/do_ci.sh docs'

It failed with error

Collecting setuptools (from sphinx==3.5.4->-r /source/docs/requirements.txt (line 164))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools from https://files.pythonhosted.org/packages/11/1b/7012b145cb228aed20f9b2b8b259df49e7963d900799ea44791f54d06ab9/setuptools-56.1.0-py3-none-any.whl#sha256=9ceb15de17f8e99dd4903f88e05e04285fa60f364f67bdcc4334aa71604b7a39 (from sphinx==3.5.4->-r /source/docs/requirements.txt (line 164))

it is running with docker so it should not have anything to do with my local installation.  My host is Linux Ubuntu

**Comment by phlax** [comment]
@qiwzhang im gonna assume that this is resolved - the current docs requirements.txt does have hashes

please re-open if you are still facing this issue

**Comment by phlax** [comment]
after further investigation it turns out that this can happen if you are using python <3.8 - envoy's ci env expects 3.8+
