### ISSUE TITLE
envoy access log clarification 

### ISSUE THREAD

**Issue by debbyku** [envoyproxy/envoy#16322]
We are using istio-1.8.3 and which is using envoy 1.16.3-dev.  From envoy access log, we would like to clarify what is  UPSTREAM_LOCAL_ADDRESS, DOWNSTREAM_REMOTE_ADDRESS & DOWNSTREAM_LOCAL_ADDRESS.

**access log definition** 
[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REA
SON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL
_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\

**access log**
[2021-05-01T18:38:31.133Z] "- - -" 0 "-" 143 2096 6005 - "-" "-" "-" "-" "10.201.113.8:55443" outbound|55443||winsolst01 192.168.23.12:46192 10.201.113.8:55443 192.168.23.12:44295 - -

**extraction from the log**
 %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
 192.168.23.12:46192      10.201.113.8:55443         192.168.23.12:44295         -                        -

192.168.23.12 is the pod address.  It is the downstream address
10.201.113.8:55443  is the address that the process inside the pod connecting to.  it is the upstream address.  

%UPSTREAM_LOCAL_ADDRESS%
Local address of the upstream connection. If the address is an IP address it includes both address and port.

%DOWNSTREAM_REMOTE_ADDRESS%
Remote address of the downstream connection. If the address is an IP address it includes both address and port.

%DOWNSTREAM_LOCAL_ADDRESS%
Local address of the downstream connection. If the address is an IP address it includes both address and port. If the original connection was redirected by iptables REDIRECT, this represents the original destination address restored by the Original Destination Filter using SO_ORIGINAL_DST socket option. If the original connection was redirected by iptables TPROXY, and the listener’s transparent option was set to true, this represents the original destination address and port.

Thanks.

**Comment by lambdai** [comment]
The overall description is awesome!

> %DOWNSTREAM_LOCAL_ADDRESS%
> Local address of the downstream connection. If the address is an IP address it includes both address and port. If the original connection was redirected by iptables REDIRECT, this represents the original destination address restored by the Original Destination Filter using SO_ORIGINAL_DST socket option. If the original connection was redirected by iptables TPROXY, and the listener’s transparent option was set to true, this represents the original destination address and port.

Thank you for clarifying it. There are several positive and negative methods to recover the original dst.
* ProxyProtocolFilter
The Downstream local address is the ip in the proxy protocol payload.
* [x-envoy-original-host](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-original-dst-host)
Not impact DOWNSTREAM_LOCAL_ADDRESS
