### ISSUE TITLE
StartTlsIntegrationTestSuite/StartTlsIntegrationTest.SwitchToTlsFromClient/0 flakes on coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16365]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/74596/logs/245
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/74598/logs/241

I have no idea why this started flaking but @cpakulski could you take a look?

**Comment by cpakulski** [comment]
@alyssawilk I am looking at it.

**Comment by antoniovicente** [comment]
Also failing on Window CI, not just coverage.
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/74729/logs/170

**Comment by lizan** [comment]
@bryce-anderson

**Comment by lizan** [comment]
I think this is caused by https://github.com/envoyproxy/envoy/pull/15443

**Comment by cpakulski** [comment]
If it is a blocker, please revert the PR until we correct it.

**Comment by cpakulski** [comment]
@antoniovicente Thanks for reviewing and merging!
