### ISSUE TITLE
For http filters, when is body callbacks(for either request or response) are called?

### ISSUE THREAD

**Issue by dandlake** [envoyproxy/envoy#16375]
Hi,

I have a question on how body callbacks are called for http filters, for either request or response. If the body is big and takes time to receive in envoy, how much body will be buffered, and when will the body callbacks(like onResponseBody) be invoked? How can I find the details on these behavior? 

Thanks in advance.

**Comment by antoniovicente** [comment]
The filter decode body callbacks are called as chunks of the body are parsed by the codec and pushed through the filter pipeline.  There is a separate body callback call for each body chunk.  end_stream is set if the current chunk is the last body chunk associated with the request or response.  Most of the buffering happens in output buffers, after the bytes have been processed by the filter pipeline.
