### ISSUE TITLE
grpc_bridge_service tag is invalid if the service name contains a '.' character

### ISSUE THREAD

**Issue by cmayer-indeed** [envoyproxy/envoy#16384]
### Problem
This is an issue if the gRPC service name is a fully-qualified Protobuf service name (i.e. includes the package name).

https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/source/common/config/well_known_names.cc#L98

For example if the service name is `indeed.jobservice.JobService` and method name `getJob`, the raw stat name for the `success` metric would look like this:

```
cluster.jobservice.grpc.indeed.jobservice.JobService.getJob.success
```

Leading to the resulting tag `grpc_bridge_service:indeed`, obviously invalid.

### Suggested Solution
Use a regex for this tag.

```
// cluster.[<route_target_cluster>.]grpc.(<grpc_service>.)*
// The trailing .\w+.\w+ segments match the method name and stat name. This works as long as the method name
// and stat name do not contain '.' characters.
addRe2(GRPC_BRIDGE_SERVICE, "^cluster\.\w+\.grpc\.([\w.]+)\.\w+\.\w+$");
```

**Comment by jmarantz** [comment]
The above suggestion should work, but will produce tags with "." in them, which can't currently happen. I don't know if that matters for any stats sinks.

Another option would be to mutate the service names when constructing the tags, swapping "." for "_".

I don't have a strong preference; just wanted to throw that out as another option.

**Comment by junpengl** [comment]
I am going to work on this issue and submit a PR soon. @jmarantz can you help reopen this issue?

**Comment by junpengl** [comment]
> sure -- how do you plan to solve?

I am going to replace all the dots in the gRPC service name to underscore and re-emit the metrics. Currently I emit both the original metrics (with only dots) and the one with underscore in our internal fork so we can migrate from the existing metrics. For the change here I am planning to just emit the metrics with underscore to avoid emitting duplicate metrics. And the change will only be applied when a gRPC stats filter config is set to true.

**Comment by jmarantz** [comment]
sg. CC @markdroth for any grpc-related concerns but I'm guessing this doesn't have any functional impact, just on how the stats look.

Is it possible some gRPC service name might be "foo.bar" and another "foo_bar" and they will become merged due to this?

**Comment by junpengl** [comment]
> Is it possible some gRPC service name might be "foo.bar" and another "foo_bar" and they will become merged due to this?

It is possible and I don't have a good way to avoid that. I can replace only selected services defined by users so they can skip the potential collision case. But then we are not solving the original problem for them they might well just not using this feature at all.

**Comment by jmarantz** [comment]
this is probably ok; might need to document it tho.

**Comment by markdroth** [comment]
I don't have any gRPC-specific concerns about this.

I agree that the potential naming conflict is a problem, but I don't know enough about the Envoy stats framework to suggest an alternative.
