### ISSUE TITLE
The remote_address rate limit action does not apply with `use_remote_address: true` and no `x-forwarded-for` header  in the request

### ISSUE THREAD

**Issue by petedmarsh** [envoyproxy/envoy#16399]
*Title*: *The remote_address rate limit action does not apply with `use_remote_address: true` and no `x-forwarded-for` header  in the request*

*Description*:

If Envoy is configured as a proxy with rate limiting using the `remote_address` action and both:

```
#...
                use_remote_address: true
                xff_num_trusted_hops: 0
#...
```

Then the `remote_action` action will not match a request which does not include a `x-forwarded-for` header, i.e.:

```
curl http://localhost:8888/test # this will not cause a descriptor to be generated and never gets rate limited
```

but a request with an `x-forwarded-for` header will:

```
curl -H 'x-forwarded-for: 1.1.1.1' http://localhost:8888/test # this will cause a descriptor to be generated
```

*and* in the later case the rate limit descriptor will use the downstream connection IP as the key (which is the correct behaviour!) and not the value passed in `x-forwarded-for` (i.e. it will not rate limit on the IP 1.1.1.1 it will rate limit on the IP the request actually came from)

I believe this is not the correct behaviour and in this set up the `remote_action` rate limit action should apply if no `x-forwarded-for` is sent to the proxy and should use the downstream connection IP as the key.

*Repro steps*:

This branch: https://github.com/petedmarsh/ratelimit/tree/remote-address-rate-limit-action-bug has full reproduction and a script to walk you through it.

*Admin and Stats Output*:
*Config*:
*Logs*:
*Call Stack*:

See: https://github.com/petedmarsh/ratelimit/tree/remote-address-rate-limit-action-bug

**Comment by antoniovicente** [comment]
@rgs1 @esmet @mattklein123

**Comment by rgs1** [comment]
I think @kyessenov or @esmet might know.
