### ISSUE TITLE
doc test in presubmit tests is flaky 

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#16422]
This presubmit test doc [test](https://dev.azure.com/cncf/envoy/_build/results?buildId=75162&view=logs&j=91e633a5-4907-5da1-5862-92a79fe2387a&t=f29e24e7-a093-5724-80bd-d79975d268cb) failed.  

But looked its output [log](https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/75162/logs/33),
I could not figure out what was wrong.

I run into this a couple times,  If I made an un-related changes to trigger it to re-run again,  it may pass.

**Comment by phlax** [comment]
hi @qiwzhang rebase to main - i think it should fix the problem

**Comment by qiwzhang** [comment]
I just rebased my pr to main last night.  Do you have any new changes since then?

**Comment by phlax** [comment]
commented here for resolution https://github.com/envoyproxy/envoy/pull/16298#discussion_r629540760

**Comment by phlax** [comment]
closing this as the issue seems to be resolved
