### ISSUE TITLE
test envoy-presubmit (check linux_x64 gcc) failed with "execv: Argument list too long"

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#16438]
The log is [here](https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/75359/logs/147).

It is from [pr](https://github.com/envoyproxy/envoy/pull/16298#issuecomment-839360973)

**Comment by antoniovicente** [comment]
Known issue, see https://github.com/envoyproxy/envoy/issues/16196
