### ISSUE TITLE
wasm: enable Rust gRPC tests

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#16432]
https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/wasm/wasm_filter_test.cc#L880

It is time to reimburse these tech debts by introducing the current version of Rust SDK, with gRPC callout/stream host features.

**Comment by antoniovicente** [comment]
cc @PiotrSikora 

@Shikugawa Is this something you could take on?

**Comment by PiotrSikora** [comment]
@Shikugawa did you start working on this? I'd like to make sure that all Envoy tests pass before a new Rust SDK release.

**Comment by Shikugawa** [comment]
@Shikugawa No. I've not started to work on this.

**Comment by PiotrSikora** [comment]
I have those tests ready. I'll send a PR once the prerequisite PRs are merged (https://github.com/envoyproxy/envoy/pull/16430, https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/165, https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/107).
