### ISSUE TITLE
Required field not comment in docs

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#16439]
*Title*:  Required field not comment in docs

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

I find if no connection_timeout set, cluster config would raise an error.
In https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#, it does not comment `REQUIRED`.

Some [discuss](https://envoyproxy.slack.com/archives/C78HA81DH/p1620746018086800?thread_ts=1620716123.084300&cid=C78HA81DH) is in slack.

I want to fix it while do not know how to do :(

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by mk46** [comment]
I am taking a look at this.

**Comment by mk46** [comment]
@phlax  Would you mind to take a look on linked PR?  Thanks!.
