### ISSUE TITLE
Remove `--bootstrap-version` command line option

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16456]
### description

once v2 has been fully removed the bootstrap-version no longer makes any sense (see https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-bootstrap-version)

apart from removing the cli option and related docs i think we also need to ensure that the logic for loading as v2 and upgrading is also removed

there is (also) some stuff in `api/envoy/config/core/v3/config_source.proto` that may need to change

**Comment by phlax** [comment]
cc @htuch

**Comment by htuch** [comment]
Yeah, we should probably do this at some point, let's have the dust settle first. https://github.com/envoyproxy/envoy/pull/16274 stopped users doing anything dangerous here, so I think maybe clean this one up after next release.

**Comment by daixiang0** [comment]
Still available?

**Comment by htuch** [comment]
Sure

**Comment by daixiang0** [comment]
> Yeah, we should probably do this at some point, let's have the dust settle first. #16274 stopped users doing anything dangerous here, so I think maybe clean this one up after next release.

Is time to clean it? If so, I would like to take.

**Comment by htuch** [comment]
If you want to work on the PR, we can merge it after 1.19 ships in early July.

**Comment by daixiang0** [comment]
got, would do it after 1.19.

/assign

**Comment by jpeach** [comment]
Will this option make sense again as the v4 API matures?

**Comment by htuch** [comment]
@jpeach postmortem pending, but I think based on  v2 -> v3 experiences, v4 is very far away (at least multiple years) if it happens at all.

**Comment by htuch** [comment]
Fixed in #17724
