### ISSUE TITLE
doc: default cipher suite docs are misleading for server and client context

### ISSUE THREAD

**Issue by desimone** [envoyproxy/envoy#16469]
*Title*: default cipher suite docs are misleading for server and client context

*Description*:

 The [default tls client config](https://github.com/envoyproxy/envoy/pull/13850) has changed since v1.16 to be distinct from the default server config. 

From

https://github.com/envoyproxy/envoy/blob/bf5d0eb44b781ac26ff1513700bcb114b7cf4300/source/extensions/transport_sockets/tls/context_config_impl.cc#L332-L356

To

https://github.com/envoyproxy/envoy/blob/ce071f6a7f5524e09c5d7bac75c9951e1b827a50/source/extensions/transport_sockets/tls/context_config_impl.cc#L315-L331

This is not clear in the [docs](https://www.envoyproxy.io/docs/envoy/v1.17.3/api-v3/extensions/transport_sockets/tls/v3/common.proto.html?highlight=tls#extensions-transport-sockets-tls-v3-tlsparameters). 

For example, where `tls_minimum_protocol_version` / `tls_maximum_protocol_version` explicitly mention the difference in client and server configs, `cipher_suites` does not.

If you agree, I'd be happy to make this change / update the docs to be more clear that the new default client cipher suite is as follows. 

```
[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]
[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
```

### Related context

- https://github.com/pomerium/pomerium/issues/2195
- https://github.com/envoyproxy/envoy/issues/5401 
- #13850
- #5396
- #5397

**Comment by antoniovicente** [comment]
@PiotrSikora @ggreenway @phlax 

You're right, the client cipher list changed due to https://github.com/envoyproxy/envoy/pull/13850

We'ld be happy to accept PRs to update the docs so they are more correct and clear.
