### ISSUE TITLE
Questions: How to debug/test a lua plugin without deploying it to envoy?

### ISSUE THREAD

**Issue by alex-lx** [envoyproxy/envoy#16473]
We're planning to develop a lua plugin for our istio service mesh's gateway, and we think it might be low effective to debug it by deploying it to a running envoy. so how  to debug/test a lua plugin without deploying it to envoy?

Thanks

**Comment by antoniovicente** [comment]
cc @dio 

It's possible that running against a real Envoy would be the most effective way to debug/test, but dio may know of alternate toolchains that would be useful during development of lua plugins.

**Comment by alex-lx** [comment]
My question may not so clear, but yes, what we are looking for is a dev tool. Thanks for clarify that.
