### ISSUE TITLE
Not able to start Envoy with demo configuration in latest code.

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#16475]
*Title*: Getting error while launching envoy with demo configuration *invalid value Invalid type URL, unknown type: envoy.extensions.access_loggers.stream.v3*

*Description*: Trying from below url
https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#run-envoy-with-the-demo-configuration

**Error details:**  
Unable to parse JSON as proto (INVALID_ARGUMENT:(access_log[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.access_loggers.stream.v3.StdoutAccessLog for type Any): {"static_resources":{"listeners":[{"address":{"socket_address":{"address":"0.0.0.0","port_value":10000}},"name":"listener_0","filter_chains":[{"filters":[{"typed_config":{"http_filters":[{"name":"envoy.filters.http.router"}],"access_log":[{"name":"envoy.access_loggers.stdout","typed_config":{"@type":"type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog"}}],"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","route_config":{"name":"local_route","virtual_hosts":[{"routes":[{"match":{"prefix":"/"},"route":{"host_rewrite_literal":"www.envoyproxy.io","cluster":"service_envoyproxy_io"}}],"name":"local_service","domains":["*"]}]},"stat_prefix":"ingress_http"},"name":"envoy.filters.network.http_connection_manager"}]}]}],"clusters":[{"type":"LOGICAL_DNS","connect_timeout":"30s","dns_lookup_family":"V4_ONLY","transport_socket":{"typed_config":{"sni":"www.envoyproxy.io","@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"},"name":"envoy.transport_sockets.tls"},"name":"service_envoyproxy_io","load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":443,"address":"www.envoyproxy.io"}}}}]}],"cluster_name":"service_envoyproxy_io"}}]}}

**Comment by phlax** [comment]
hi @ankatare this suggests a mismatch between the version of envoy that you are using and the docs you are following

could you either ensure you are using envoy built on latest code or check the docs for the envoy version you are using

**Comment by ankatare** [comment]
@phlax tahnks for quick response. code was on 17.1. on latest 1.18.2 it is fine.

**Comment by ankatare** [comment]
May be we can close this...

**Comment by phlax** [comment]
yep - i think so - not sure how we can flag this better - one idea i had is using `versionadded` directives (see #15763 ) but not sure how easy or whether it will resolve this

**Comment by ankatare** [comment]
@phlax one more way is to use `--mode validate `with each configuration before to start envoy :) . WDYT ?

**Comment by ankatare** [comment]
> yep - i think so - not sure how we can flag this better - one idea i had is using `versionadded` directives (see #15763 ) but not sure how easy or whether it will resolve this

yes... it is good idea

**Comment by ankatare** [comment]
Closing this incidence as running good in latest code.

**Comment by learnbyseven** [comment]
This is still an issue with all your latest code.

**Comment by phlax** [comment]
hi @learnbyseven please reread my comment here https://github.com/envoyproxy/envoy/issues/16475#issuecomment-840344681

**Comment by learnbyseven** [comment]
Hi @phlax , I have just started with envoy following installation guide (Latest one) , My envoy version shows; /1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL and I have downloaded and use the latest sample from https://www.envoyproxy.io/docs/envoy/latest/_downloads/92dcb9714fb6bc288d042029b34c0de4/envoy-demo.yaml file. I solved it just with by using putting a "connect_timeout: 5s". 
Example:
clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    connect_timeout: 5s

now , validate gives configuration 'envoy-demo.yaml' OK and envoy is running fine. Kindly review it one more time please.

**Comment by phlax** [comment]
with versions `< 1.19` the `connect_timeout` setting is required, for later versions it has a default

**Comment by learnbyseven** [comment]
I assume envoy package version has a coupling with OS version. 
OS : DISTRIB_ID=Ubuntu, DISTRIB_RELEASE=18.04
Envoy : getenvoy-envoy/bionic,now 1.18.2.p0.gd362e79-1p75.g76c310e amd64 [installed]

**Comment by phlax** [comment]
its not so much related to the OS (atho its a factor) - it deps on what version you have installed

we are currently transitioning to a new packaging system, hopefully things will be clearer once that has been set up

**Comment by learnbyseven** [comment]
Good to hear , I have updated the UB 18.04 with latest packages and install Envoy as per the latest doc (yesterday only) and got into the issue. No worries thanks ! for your swift responses, really appreciated.
