### ISSUE TITLE
lyft.github.io/envoy/ 404s, should redirect to new site at envoyproxy.github.io/envoy/

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#1650]
This broke pretty much every Google hit for the Envoy docs, so it'd be nice to get a redirect in place.

**Comment by mattklein123** [comment]
Right now the entire repo is redirecting. If we make a repo in lyft org and put in a redirect, I think it will break a bunch more stuff. Not sure if there is a great way to deal with this.

**Comment by mattklein123** [comment]
I think we figured out how to put a redirect in.
