### ISSUE TITLE
Removal of `access_log_path` is likely to break users' config

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16515]
As can be seen in bugs relating to example configs mismatching with the current `envoy-dev` docker image (eg #16511 #16475 ) users are likely to experience broken  configurations when upgrading

I think the `access_log_path` should not have been removed without deprecation

This would probably not have prevented the issues posted above (not sure - it might have prevented them failing - perhaps it would have just emitted a deprecation warning) - but they do highlight how this hard forking change is likely to break users' config

**Comment by phlax** [comment]
cc @davinci26 @ankatare

**Comment by phlax** [comment]
see also #15761

**Comment by davinci26** [comment]
What do you have in mind for deprecation? How would you do it alternatively?

Currently it is marked as `deprecated` in the proto

https://github.com/envoyproxy/envoy/blob/50024c1ff774029d67c6e27e5893c5d1400065a3/api/envoy/config/bootstrap/v3/bootstrap.proto#L314

**Comment by phlax** [comment]
> What do you have in mind for deprecation? How would you do it alternatively?

not sure how deprecation works tbh - i know that i have dealt with config in the past that emits warnings rather than failing - not sure how that is expressed in the code

**Comment by davinci26** [comment]
@phlax what is the action item here? When I updated to 1.18.3 the old configs where working and just a warning was emitted

**Comment by phlax** [comment]
@davinci26 not sure exactly - does it work the same with current `HEAD` - mostly i opened this ticket because people kept on posting that the container/docs etc that they were following were breaking due to this - ie due to mismatch of envoy version and docs or container

**Comment by phlax** [comment]
ie #16511 and #15761 - altho checking again - it might be the reverse problem of trying to use an old container/envoy with newer docs

if we are totally sure that adding `access_log_path` works still in the latest version - and just emits warning i guess we can close this

**Comment by davinci26** [comment]
Yeah it does, just verified with 1.18.3 envoy binary. Also all the code samples in the source tree do not use access logging for the admin interface.

**Comment by phlax** [comment]
cool - thanks for checking this out @davinci26
