### ISSUE TITLE
is it possible to use dynamic  forward proxy without dns?

### ISSUE THREAD

**Issue by malza321** [envoyproxy/envoy#16513]
Hi!

I just want to use like that on dynamic forward proxy. bacause there is no cloud native infra system. some service should be called by ip:port only.

is there any way??

To test, curl -x http://envoy ip:port http://target_ip:port
I don't even need dns query.

But envoy always return "No healthy Upstream"

configure example will be great help thanks!!

**Comment by alyssawilk** [comment]
doing a quick scan of proxy_filter.cc and the dns cache I'm not seeing offhand any fast-path for addresses, though it would be a completely reasonable thing to do.

**Comment by malza321** [comment]
> doing a quick scan of proxy_filter.cc and the dns cache I'm not seeing offhand any fast-path for addresses, though it would be a completely reasonable thing to do.

Sorry. I can't catch what you exactly mean.

So you mean It is not possible? Why it needs dns cache? It is not domain name based proxy So I thought It does't need reference at all.

I just wanted to know the way which is like the proxy_pass in nginx.

If target host name is ip:port base, nginx forwards to target directly. But if target host name is domain name base, nginx dose dns query to dns server in resolv.conf.

I'm using envoy on inbound service, and nginx on outbound(but is has no domain name). So I want to change nginx to envoy even on outbound if that is possible.
