### ISSUE TITLE
Question: How to extract text between square brackets with RegexMatcher

### ISSUE THREAD

**Issue by durd07** [envoyproxy/envoy#16518]
*Title*: *How to extract text between square brackets with RegexMatcher*

*Description*:
>when I run ./tools/code_format/check_format.py fix to fix the format issues, it report the error:

ERROR: ./source/extensions/filters/network/sip_proxy/decoder.cc:580: Don't use std::regex in code that handles untrusted input. Use RegexMatcher

following is my code:

```c++
std::regex pattern = ".*sip:(.*?)[:;].*";
std::match_results<absl::string_view::const_iterator> m;
if (std::regex_match(sip_header.begin(), sip_header.end(), m, pattern)) {
  return absl::string_view{&*m[1].first, static_cast<size_t>(m[1].length())};
} else {
  return "";
}
```

So does anyone know how to achieve the same effect with RegexMatcher, extract text between square brackets? I want to get the substring tafe.default.svc.nokia.local  from sip:tafe.default.svc.nokia.local:15306;role=anch;lr;transport=tcp.
Thanks in advance!

[optional *Relevant Links*:]
>I posted this question on envoy-dev group https://groups.google.com/g/envoy-dev/c/7YSybwF9tHM but seems no answer, so post it into issues.

**Comment by rojkov** [comment]
RegexMatcher has no support for submatching. I think you can start with using [Re2](https://github.com/google/re2/blob/master/re2/re2.h) instead of std::regex. There are examples in Envoy's code base.

**Comment by durd07** [comment]
Hi @rojkov,

thanks for your answer, it works now.
here is my solution:

```c++
std::string domain = "";
re2::RE2::FullMatch("sip:tafe.default.svc.nokia.local:15306;role=anch;lr;transport=tcp", "".*sip:(.*?)[:;].*"", &domain);
```
