### ISSUE TITLE
cache_front-envoy_1 container exiting

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#16511]
*Title*: *cache_front-envoy_1 container exiting while strating with cache_services*

*Description*: Issue occured in latest code. see below logs
url followed : https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache#step-1-start-all-of-our-containers

/new_folder/envoy/examples/cache$ docker-compose up -d
Starting cache_service2_1    ... done
Starting cache_front-envoy_1 ... done
Starting cache_service1_1    ... done

/new_folder/envoy/examples/cache$ docker-compose ps
       Name                      Command               State      Ports
-------------------------------------------------------------------------
cache_front-envoy_1   /docker-entrypoint.sh /bin ...   Exit 1
cache_service1_1      /bin/sh -c /usr/local/bin/ ...   Up       10000/tcp
cache_service2_1      /bin/sh -c /usr/local/bin/ ...   Up       10000/tcp

/new_folder/envoy/examples/cache$ docker-compose ps
       Name                      Command               State      Ports
-------------------------------------------------------------------------
**cache_front-envoy_1   /docker-entrypoint.sh /bin ...   Exit 1**
cache_service1_1      /bin/sh -c /usr/local/bin/ ...   Up       10000/tcp
cache_service2_1      /bin/sh -c /usr/local/bin/ ...   Up       10000/tcp

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
i suspect this is the same problem as #16475 - ie a mismatch between the docs and the container you have locally installed

if you are using the latest examples can you make sure you have the latest version of the containers used

**Comment by ankatare** [comment]
Hi @phlax as per doc  https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#install-docker

minumum required version is 19.03 and in my setup it is... 20.10.5 ( see below ) 
please suggest. 

necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by phlax** [comment]
not the docker version - the envoy version - ie assuming you are working out of the current `main` `HEAD` envoy repo - make sure that the docker image/s you are using (eg `envoyproxy/envoy-dev`) is the correct one - either by pulling it or removing it before trying to run the example

**Comment by phlax** [comment]
im assuming you skipped the step:

```
docker-compose build --pull
```

**Comment by ankatare** [comment]
@phlax I used all steps as mentioned in https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache#step-1-start-all-of-our-containers. Moreover i cloned from latest main branch and to install Envoy used https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-ubuntu-linux
see below 
necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ envoy --version

envoy  version: 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/clean-getenvoy-b76c773-envoy/RELEASE/BoringSSL

**Comment by phlax** [comment]
on the basis that it works correctly in CI - im thinking that there must be an issue with your setup - i can test further locally if necessary

can you do the following (after first ensuring that you are on envoy `main` and `main` is up-to-date

```console
$ cd examples/cache
$ ./verify.sh
$ echo "$?"
```

after running the example you should see a `0` returned

**Comment by ankatare** [comment]
@phlax Ok. Let me double check all above.  Thanks a lot for all your time and Help !!!

**Comment by ankatare** [comment]
@phlax after running all above steps and verification (latest main etc) i run ./verify.sh and out is as below

necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ echo "$?"
7

**Comment by phlax** [comment]
im struggling to understand how that could not work - i just ran it locally (on my debian machine) and it works correctly - ci tests it on a ubuntu machine - but as it runs in docker im not sure any of that matters much

on my machine this is what i see:

```console
$ git log -n1 
commit ae780e21824bcb947299f5a048797fbf3cac21ba (HEAD -> main, upstream/main)
$ docker images | grep envoy-dev
envoyproxy/envoy-dev                latest    1da342f7b72e   40 hours ago     135MB

```

what do you see for those commands ?

**Comment by phlax** [comment]
also...

before running `./verify.sh` can you make sure that the composition is not running - ie

```
$ docker-compose down
$ ./verify.sh
```

**Comment by ankatare** [comment]
> im struggling to understand how that could not work - i just ran it locally (on my debian machine) and it works correctly - ci tests it on a ubuntu machine - but as it runs in docker im not sure any of that matters much
> 
> on my machine this is what i see:
> 
> ```
> $ git log -n1 
> commit ae780e21824bcb947299f5a048797fbf3cac21ba (HEAD -> main, upstream/main)
> ...
> $ docker images | grep envoy-dev
> envoyproxy/envoy-dev                latest    1da342f7b72e   40 hours ago     135MB
> ```
> 
> what do you see for those commands ?

necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ git log -n1
commit 07c4c17be61c77d87d2c108b0775f2e606a7ae12 (HEAD -> new_test, test, remove_v2_support, main)
....

necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ docker images | grep envoy-dev
envoyproxy/envoy-dev                 latest                                     1da342f7b72e   41 hours ago    135MB

**Comment by ankatare** [comment]
> also...
> 
> before running `./verify.sh` can you make sure that the composition is not running - ie
> 
> ```
> $ docker-compose down
> $ ./verify.sh
> ```

After compose down.. same result  

necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ echo "$?"
7

**Comment by phlax** [comment]
`main` is not the same as envoy `HEAD` - ie

```
$ git log -n1
commit 07c4c17 (HEAD -> new_test, test, remove_v2_support, main)
```

depending on your setup (assuming you have the envoy repo `remote` set to `upstream` can you do something like

```
$ git checkout `main`
$ git fetch upstream
$ git rebase upstream/main

```

and then try running the `verify.sh` script again

**Comment by ankatare** [comment]
@phlax   this time it works 👍  ..... It was just with the issue with rebasing with main or something else ?   

```
necuser@dldt-project_005:~/new_folder/envoy/examples/cache$ docker-compose ps
       Name                      Command               State                 Ports
------------------------------------------------------------------------------------------------
cache_front-envoy_1   /docker-entrypoint.sh /bin ...   Up      10000/tcp, 0.0.0.0:8000->8000/tcp
cache_service1_1      /bin/sh -c /usr/local/bin/ ...   Up      10000/tcp
cache_service2_1      /bin/sh -c /usr/local/bin/ ...   Up      10000/tcp

```

**Comment by phlax** [comment]
as explained it was a mismatch between the config you had in your local checkout and the config expected by the current docker image - see #16515 for underlying cause

**Comment by phlax** [comment]
@ankatare are you happy to close this ticket - while i fear others might hit this issue (if they have old checkouts of the repo) the actual problem is #16515

**Comment by ankatare** [comment]
@phlax sure and thanks a lot for all your support on this investigation
