### ISSUE TITLE
Support sending stats with Graphite-formatted tags

### ISSUE THREAD

**Issue by vaccarium** [envoyproxy/envoy#16523]
*Title*: *Support sending stats with Graphite-formatted tags*

*Description*:
I'm currently working on a Graphite tag-aware stat sink, and we'd love to get this extension accepted into the upstream Envoy repo. This is a follow-up to issue #14863 but smaller in scope (#14863 originally proposed a more flexible sink, while what I'm proposing here would be limited to Graphite tags).

*Relevant Links*:
https://graphite.readthedocs.io/en/latest/tags.html describes Graphite tags.

**Comment by vaccarium** [comment]
cc @moderation, as you commented on this in #14863

**Comment by alyssawilk** [comment]
cc @envoyproxy/maintainers anyone interested in sponsoring?  If not this would be another use case for contrib.

**Comment by antoniovicente** [comment]
Does graphite have its own protocol to collect stats or does it build on top of statsd?  Basically, does this makes sense as a separate extension or as graphite options on the statsd sink?

**Comment by PAFomin-at-avito** [comment]
@antoniovicente: Graphite has its own tagging format but not a complete stats protocol, so what I'm talking about is Statsd protocol extended with Graphite tagging.

Making this an option on the statsd sink is a good idea, but for now I'm leaning towards a separate extension for two reasons:
* Prior precedent: Envoy already has a statsd sink with tagging ([//source/extensions/stat_sinks/dog_statsd/](https://github.com/envoyproxy/envoy/blob/main/source/extensions/stat_sinks/dog_statsd/)), and it's implemented as a separate sink and not as an option.
* The "plain" statsd sink supports both UDP and TCP connections, and it would make sense to support tags for both of them. This sink uses different code for sending stats over TCP and UDP. Extending the UDP implementation looks quite easy, but the TCP code is more optimised, and extending it without additional discussion probably wouldn't be wise.

**Comment by vaccarium** [comment]
@antoniovicente: Graphite has its own tagging format but not a complete stats protocol, so what I'm talking about is Statsd protocol extended with Graphite tagging.

Making this an option on the statsd sink is a good idea, but for now I'm leaning towards a separate extension for two reasons:

    Prior precedent: Envoy already has a statsd sink with tagging (//source/extensions/stat_sinks/dog_statsd/), and it's implemented as a separate sink and not as an option.
    The "plain" statsd sink supports both UDP and TCP connections, and it would make sense to support tags for both of them. This sink uses different code for sending stats over TCP and UDP. Extending the UDP implementation looks quite easy, but the TCP code is more optimised, and extending it without additional discussion probably wouldn't be wise.

**Comment by mattklein123** [comment]
I think it's fine to support this, but can it be done in a similar way to DogStatsd where we use the common statsd code? PRs appreciated.

**Comment by vaccarium** [comment]
Yes, this can be done by extending the common code. I'll be glad to send a PR later tonight.
