### ISSUE TITLE
jwt_authn: breaking change in payload encoding

### ISSUE THREAD

**Issue by wozz** [envoyproxy/envoy#16528]
*Title*: jwt_authn: breaking change in payload encoding

*Description*:
The encoding format for the JWT Payload header in the jwt_authn filter was changed in https://github.com/envoyproxy/envoy/pull/14779. This is a breaking change in golang due to the way the base64 package works: https://golang.org/pkg/encoding/base64/#pkg-variables

*Repro steps*:
see test changes here: https://github.com/envoyproxy/envoy/pull/14779/files#diff-ccb8c0f9dfe4011484c9d7ca83d56abbe8b60c7b1b8dcd8efbc3debe0c6c5a1cR179

*Config*:
n/a

*Logs*:
n/a

*Call Stack*:
n/a

**Comment by daixiang0** [comment]
Do you mean `StdPadding`  in Golang base64 package?

**Comment by wozz** [comment]
https://play.golang.org/p/XxPFj1UKrZV

This shows the error that the new encoding will produce.

**Comment by qiwzhang** [comment]
I see.  so adding padding fixes problems for python JWT library,  but break golang one. 
Since padding is not required in the JWT [rfc](https://www.rfc-editor.org/rfc/rfc7515.txt),  I think we should revert this pr [ #14779](https://github.com/envoyproxy/envoy/pull/14779).

**Comment by qiwzhang** [comment]
@TAOXUY could you help to revert it?  Thanks

**Comment by TAOXUY** [comment]
I c. I will revert that PR and tweak/resubmit it by adding a option to support python case.

**Comment by qiwzhang** [comment]
SG
