### ISSUE TITLE
Cache ratelimits on envoy edge proxy before communicating to the ratelimiting service

### ISSUE THREAD

**Issue by minbaev** [envoyproxy/envoy#16571]
Hi,
We are trying to use envoy edge proxy with global ratelimiting (GRL)  and from my understanding  - all requests will have to go to that external GRL service. We are planning to have several edge proxies each communicating with GRL service.

We integrated the ratelimit service with our edge proxy - https://github.com/envoyproxy/ratelimit -  and now comes a question. 

We don't want all the requests go to GRL service but rather ratelimits be cached locally on each edge proxy. Then we think about a mechanism to sync local cache from each envoy edge proxy with GRL service. Synchronization might be happening every period of time, lets say every 5 minutes.

Is there a solution for such design already or do we have to implement the caching and synchronization ourselves (on C++ level)?

Thank you

**Comment by alyssawilk** [comment]
cc @mattklein123 @rgs1 @junr03

**Comment by rgs1** [comment]
One quick question is, any chance a local rate limiter would be enough:

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter


Given you are open to caching, which means it won't be a truly global & centralized rate limiter, I wonder if the local one might suffice for your use-case. You'd save yourself from a lot of the extra complexity...

**Comment by minbaev** [comment]
@rgs1 Thanks for your reply. We are using local rate limit as well.
with the global rate limit we want some more advanced header parsing based on which we will limit rate.


With caching-global we want to cache locally then update the global rate limit through synchronization, it won't be truly global/accurate but we can compromise on 100% ratelimit accuracy to avoid all requests going to the GRL
Hope it makes sense.

**Comment by cocotyty** [comment]
@minbaev https://github.com/envoyproxy/envoy/issues/16668
I think we have the same problem.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/pull/15483. This is a dup of https://github.com/envoyproxy/envoy/issues/14299. cc @htuch
