### ISSUE TITLE
Is it possible to customize metrics of external authorization?

### ISSUE THREAD

**Issue by konstantin-tkachuk** [envoyproxy/envoy#16573]
I am currently using envoy with OPA as a sidecar of a microservice to authenticate incoming requests. Now I want to track how many requests get denied. I have found the following statistics and they work for me:

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#statistics

However, the envoy_http_ext_authz_denied counter only allows me to track the *total* amount of requests that get denied. I want to have more detail, such as: how many of those were READ/WRITE requests? how many requests were denied for tenant xyz?

Is there some mechanism how I can add custom tags to the counter? Instead of just
```
envoy_http_ext_authz_denied{envoy_http_conn_manager_prefix="ingress_http"} 0
```
I wish to have 
```
envoy_http_ext_authz_denied{envoy_http_conn_manager_prefix="ingress_http", custom_key="custom_value"} 0
```

**Comment by alyssawilk** [comment]
cc @esmet @gsagula @dio
