### ISSUE TITLE
Websocket upgrade: does envoy care about the websocket data/framing ?

### ISSUE THREAD

**Issue by gopakumarce** [envoyproxy/envoy#16586]
To what extent does envoy act as a proxy for websocket ? After the Upgrade handshake is done, does it ever look into the websocket framing itself / does it care about the websocket data being proper - or does it just treat it as a tcp afterwards ? I checked envoy source code and I did not see any signs of envoy having code to interpret websocket framing etc..

The reason for asking is to know whether I can use an http upgrade sequence and then send non-websocket data over that connection assuming my client and server are in my control - will envoy have any unhappiness with that ?

**Comment by alyssawilk** [comment]
Envoy doesn't do any websocket framing. You can use the upgrade path for any arbitrary TCP data, though I'd suggest using a different upgrade name or CONNECT support. :-)

**Comment by gopakumarce** [comment]
Hi @alyssawilk thx a lot for the response. Yes CONNECT seems the most appropriate thing to do for arbitrary TCP data, but then looks like connect is missing http header matching support and we have to use some special "connect match" filters. Hence using the Upgrade path  since its  very flexible with filters matching http headers .. Yes probably I should change the name away from websocket :)

**Comment by gopakumarce** [comment]
@alyssawilk does envoy buffer up upgrade data or is it streaming ? I hope its streaming - I am seeing a behaviour here https://github.com/envoyproxy/envoy/issues/17281 and hence the question

**Comment by alyssawilk** [comment]
All Envoy processing streams by default, websocket included.  If you use the buffer filter for non-websocket data it's strongly recommended to have a custom upgrade filter chain (see docs) to not buffer on the upgrade path.  That issue was closed off as user error :-)

**Comment by gopakumarce** [comment]
Thanks @alyssawilk .. yes I figured after some googling and some envoy command dumps that buffer filter is NOT on by default, thx again for the prompt response
