### ISSUE TITLE
Windows: Configuration, Dynamic from filesystem

### ISSUE THREAD

**Issue by wahmedswl** [envoyproxy/envoy#16631]
*Title*: *One line description*
Configuration: Dynamic from filesystem, Windows

*Description*:
>Trying envoy on windows with dynamic configuration from filesystem. Following documentation from https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem, everything seems to be configured as by guide but still newly added lb_endpoints.endpoint comes online. It works if i restart envoy so its mean configuration is ok but updates are not reflected.

*Repro steps*:
> Just run envoy with the given conf.yaml and update cds.yaml with new endpoint, changes will not reflect.

*Config*:
>Envoy config files are attached.
[envoy.zip](https://github.com/envoyproxy/envoy/files/6528918/envoy.zip)

Thanks

**Comment by wahmedswl** [comment]
Hi, tried in WSL2 its not working there as well. No linux environment so cannot check either its just WSL2 or dynamic file configuration is not working at all.

Thanks

**Comment by wahmedswl** [comment]
There might be config issue as well, so any help would be appreciated.

Thanks

**Comment by phlax** [comment]
cc @wrowe

**Comment by wrowe** [comment]
Ping also @davinci26

**Comment by wrowe** [comment]
I wouldn't pay much attention to wsl2. I've done various experiments of tail -f across the environments, and the filesystem seems too removed to neatly follow win32 changes from wsl2 or vis a versa. We have put in zero effort to the wsl2 environment, my last tests a year ago indicated a number of inconsistencies. We are entirely focused on the win32 implementation and are happy to examine the trouble you are having picking up filesystem conf changes.

**Comment by davinci26** [comment]
Have you seen the demo at https://github.com/sunjayBhatia/envoycon-2020-demo? This demo is utilizing this feature and I have recently made it work for my own work on a new setup with Envoy 1.18.3

This was used in https://youtu.be/f3DezuydHr4
