### ISSUE TITLE
Add DCO

### ISSUE THREAD

**Issue by caniszczyk** [envoyproxy/envoy#1663]
https://developercertificate.org/

**Comment by mattklein123** [comment]
Will call this resolved once bot is active, we remove Lyft CLA bot, etc.

**Comment by caniszczyk** [comment]
@mattklein123 DCO bot is now active (I forgot about the built in one with GitHub now):

https://github.com/organizations/envoyproxy/settings/installations/53244

All PRs now will need DCO (including in flight PRs)

If we do a quick test today, we can remove the CLA today.

**Comment by mattklein123** [comment]
OK I will figure out how to do this and then add instructions in the contributing guide.

**Comment by caniszczyk** [comment]
This is done. CLA check is remove, DCO check is enforced.

**Comment by mattklein123** [comment]
I'm still figuring out how to correctly configure git client. Then will update contributing guide and call this fixed.

**Comment by caniszczyk** [comment]
@mattklein123 

I updated the CONTRIBUTING.md with info: https://github.com/envoyproxy/envoy/pull/1673

**Comment by caniszczyk** [comment]
@mattklein123 if you want it to be automatic, you can add something like this to your .gitconfig

[alias]
  amend = commit -s --amend
  commit = commit -s

There may be easier ways to do this with git now but I have to check things out.

**Comment by mattklein123** [comment]
Yeah I'm poking around. We can merge this and I will update again when I figure it out.
