### ISSUE TITLE
Understand active connections with upstream

### ISSUE THREAD

**Issue by hinawatts** [envoyproxy/envoy#16639]
*Title*: *How many connections can be opened from envoy to upstream per worker for http1.1 requests*

*Description*:  We have deployed envoy proxy in pod that is forwarding requests to upstream cluster which has 60 hosts. Below are the configurations at our end - 

1.  Number of pods of envoy -  25
2.  Number of hosts in upstream -60
3. Envoy concurrency -  30
4. Circuit breaker.max_connections - 2400

When we are running performance tests for our service that hits envoy proxy, we are seeing `upstream_cx_active` value as 1800 per pod, which I think is coming from concurrency * number of hosts in upstream. Connections are not going beyond 1800 even at higher rate. Will worker create max one connection per each upstream host?

> When does envoy worker thread creates new connection with upstream over http1.1 ?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
Envoy doesn't default to 1 connection per host unless you've capped the connections artificially low somehow (e..g https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto)

**Comment by hinawatts** [comment]
So, one worker can create multiple connections with the same host in upstream cluster based on the load, right?

**Comment by hobbytp** [comment]
yes, one worker can create multiple connections with the same upstream host.

**Comment by hinawatts** [comment]
Thanks for the information.
