### ISSUE TITLE
remove gQUIC support from Envoy

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16642]
or at least make it clear it's going away fairly soon, and is not sticking around for the standard 1 year data plane SLO

**Comment by alyssawilk** [comment]
We should also make sure h3-29 EoL is made clear, given it isn't expected to last a year.

**Comment by danzh2010** [comment]
> We should also make sure h3-29 EoL is made clear, given it isn't expected to last a year.

What's this about?
