### ISSUE TITLE
Logging protobuf message with `ShortDebugString()`

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#16654]
There are many log prints in Envoy like `ENVOY_LOG(info, "message: {}", some_proto.DebugString())`, which makes the certain log outputs in multiple lines. For humans, multi-line logs are more readable, but they are not friendly to some log collection and storage systems. Usually these systems collects and stores logs line by line. For example, I want to store Envoy logs in elastic search for quick search, but when these logs are output in the form of multiple lines, it is difficult to find the complete logs.

So I was wondering if Envoy could output one log whose level is higher than `info` or `warn` in a single line.

**Comment by phlax** [comment]
cc @yanavlasov
