### ISSUE TITLE
some failed gRPC requests get a 5xx stat but are logged with a 200 HTTP status code

### ISSUE THREAD

**Issue by samrabelachew** [envoyproxy/envoy#16667]
*Title*: some failed gRPC requests get a 5xx stat but are logged with a 200 HTTP status code

*Description*:
Hello, I'm unsure if this is a bug or intended design. We've noticed that some types of failed grpc requests can get a 5xx stat but also be logged with a 200 HTTP status code.

For example, when a response timeout [occurs](https://sourcegraph.com/github.com/envoyproxy/envoy@a467b0ef41864459f4b4ad76fad7e1efb06b0bf8/-/blob/source/common/router/router.cc#L891), we will increment `upstream_rq_504` metric. Later on though, we will [set](https://sourcegraph.com/github.com/envoyproxy/envoy@a467b0ef41864459f4b4ad76fad7e1efb06b0bf8/-/blob/source/common/http/utility.cc#L529) the response HTTP status code to 200, which is where the logged status code comes from I believe. I don't think this behavior is consistent for all types of failed gRPC requests either.

This can cause confusion around measuring success rates and identifying gRPC errors when they exist. I was hoping to find a way to better define this. Would there be objections to changing this behavior so that:
`If a valid grpc status error code exists (i.e. greater than 0), we do not increment any HTTP status code metrics (4xx/5xx) and instead rely on the grpc stats filter to provide us gRPC specific metrics.` 

^ From a logs perspective, we can set the HTTP status code to nil or leave it at 200. This wouldn't need to change the behavior of non-status code request metrics like `upstream_rq_timeout` which would still increment in the case described earlier. Would this also cause confusion for other users?

Alternatively, we could require all gRPC requests to have a corresponding HTTP status code set using the conversion rule (https://sourcegraph.com/github.com/envoyproxy/envoy/-/blob/source/common/grpc/status.cc#L28). I can't tell if it might be misleading though since the real source of truth should be the grpc status code.

**Comment by samrabelachew** [comment]
cc @lizan (gRPC senior maintainer)

**Comment by mattklein123** [comment]
My 2c is that changing this behavior would be too disruptive so I don't recommend it. From a logging perspective, do we support logging the gRPC status code in addition to the HTTP status code? That seems like potentially a better solution? It is accurate pedantically that the HTTP status code is 200 at the point of logging.

**Comment by samrabelachew** [comment]
@mattklein123, we do, it just caused some confusion for a user when they realized they could see 5xx without seeing the corresponding logs to understand why. For the timeout scenario, the error translated to a `HTTP 200 gRPC 14 failure-reason UT` log. Focused on the status codes, not seeing the failure reason hid the real reason for the issue.

I'm okay with not changing it if it's too disruptive, but I think this creates inconsistent behavior since only a few types of failed gRPC requests would be included in metrics measuring 5xx rates. Would that be a little confusing?

**Comment by lizan** [comment]
Re: why the HTTP status is set to 200. The behavior comes from [gRPC over HTTP2 spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md), in all gRPC response, the status code should be 200 as long as content-type is `application/grpc`. In any case when content-type is `application/grpc` the HTTP status doesn't have useful means, so you should use `grpc-status` and `grpc-message` for that.

Which types of failed gRPC request included in metrics measuring 5xx rates?

**Comment by samrabelachew** [comment]
@lizan, the cases I see are those in the [router.cc file](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc) that use the `chargeUpstreamCode()` fxn, passing in a fixed status code. The function will increment the corresponding upstream_rq_xxx stat based on that parameter. I believe the cases are: timeouts, no healthy upstream, maintenance mode, and 100.

**Comment by mattklein123** [comment]
I'm on the fence on this one. One one hand, I agree that in a perfect world we would not emit those stats for gRPC responses and then rely on the stats filter to get insight. On the other hand, I think it's very likely we are going to break the monitoring of someone's deployment in subtle ways that may go unnoticed for some time.

Thus, I would be weary of changing this behavior even under runtime guard. WDYT about making the configurable in the router?

**Comment by samrabelachew** [comment]
That's fair. I could try to make this configurable via the router. I believe the set of changes to do so would be:
* define a boolean field like `suppress_grpc_request_failure_code_stats` within the router filter
* update router logic so that the fxn `chargeUpstreamCode()`, doesn't increment group stats (e.g. 5xx) and individual code stats (e.g. 504) when seeing that the current request is gRPC and the field `suppress_grpc_request_failure_code_stats` is set to true; most likely this will involve creating a separate stat helper fxn to handle this behavior

This would allow us to maintain existing behavior and those interested in opting in to this feature to do so. If that sounds good @mattklein123 and @lizan, I will begin those changes.

**Comment by mattklein123** [comment]
Yes I think that plan makes sense to me.
