### ISSUE TITLE
Supporting FIPS build on CentOS 7

### ISSUE THREAD

**Issue by Fchateauvert** [envoyproxy/envoy#16678]
*Title*: Support building Envoy with the FIPS compliant borringssl library on CentOS 7

*Description*:
Hi gang,

I'm working on getting a FIPS compliant build of Envoy to work on CentOS 7 through the Tetrate getEnvoy pipeline.  I hit a roadblock however when the build tried to run a script defined in [boringssl_fips.genrule_cmd](https://github.com/envoyproxy/envoy/blob/main/bazel/external/boringssl_fips.genrule_cmd).  This script was written to only work on Ubuntu, as the libraries pulled in will only work if glibc 2.18 is present on this host.

In order to get around this, I forked the Envoy repo and made modifications to this script to ensure that it worked on both CentOS and Ubuntu.  I was capable of successfully building a CentOS 7 version of Envoy FIPS with this change in the Tetrate getEnvoy repo, and it shouldn't impact any existing build pipelines in the Envoy repo.

Here's the link to the code I've modified on a fork of Envoy:
https://github.com/Fchateauvert/envoy/pull/2
Note that this PR is not ready for review, and is just here to present the direction I am taking with this new feature.

I was wondering if this is the right approach to accomplish this, or if there are any aspects of Envoy I may have missed in this change.  

*External Links*
[Tetrate Repository](https://github.com/tetratelabs/getenvoy-package)

**Comment by lizan** [comment]
There's a couple reason that BoringSSL FIPS doesn't work CentOS 7.

The policy docs: https://github.com/envoyproxy/envoy/issues/16678
States that:

> The cryptographic module is also supported on the following operational environments for which
operational testing and algorithm testing was not performed:
• Linux 4.X executing on x86_64 architecture;
• Linux 4.X executing on POWER9 architecture;
• Linux 5.X executing on x86_64 architecture; and
• Linux 5.X executing on POWER9 architecture.

CentOS 7 never met this, also it specifies that LLVM should be download from official LLVM website so I don't think using `llvm-toolset-7.0` would appropriate.

**Comment by nickolaev** [comment]
@Fchateauvert I was working on a similar task and I ended up with the same approach, although I was completely patching the whole script for the purposes of the build. Your solution looks great. Please follow up with a PR for this to become upstream.

However, we should still note that what we end up is not a FIPS verified library according to the PDF pointed out at the beginning of the script:
https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3678.pdf
