### ISSUE TITLE
LUA filter httpCall() buffers original request body,

### ISSUE THREAD

**Issue by sumitaneja** [envoyproxy/envoy#16674]
In lua filter we are making a httpCall to another service.  This is simple post call with no response body
But get 413 too large error if original request size is > 1MB

Seems before making http call, it streams and buffers original request body.

**Comment by sumitaneja** [comment]
not clear why original request body is buffered

**Comment by phlax** [comment]
cc @snowp

**Comment by snowp** [comment]
@sumitaneja Can you share the entire Lua script you're using? Feel free to edit it if it contains information you don't want to share, just looking for the general shape of it

**Comment by sumitaneja** [comment]
@snowp Simplified view of lua script part of envoy Lua filter. 

   - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                local p = request_handle:headers():get(":path")
                local rlHeaders = {}
                local sid = request_handle:headers():get("someheader")
                local ridOr = request_handle:headers():get("someHedaer")
                local rid = string.gsub(ridOr, "/", "%%2F")
                local rlkey = sid .. "/" .. rid
                rlHeaders[":method"] = "PUT"
                rlHeaders[":path"] = "/someURL/" .. rlkey
                rlHeaders[":authority"] = "cluster.svc.cluster.local"
                local headers, body = request_handle:httpCall(
                 "lua_cluster",
                rlHeaders,
                nil, 
                5000)
    
              end

 When i make request with payload size >1mb it fails with 413 too large error.  Using istio 1.6

**Comment by sumitaneja** [comment]
Envoy version
12cfbda324320f99e0e39d7c393109fcd824591f/1.14.1/Clean/RELEASE/BoringSSL

**Comment by sumitaneja** [comment]
Reproduced with sandbox lua filter. https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/lua

**cat envoy.yaml** 
static_resources:
  listeners:
  \- name: main
     address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                local mylibrary = require("lib.mylibrary")

                function envoy_on_request(request_handle)
                  request_handle:headers():add("foo", mylibrary.foobar())
                  request_handle:logWarn("WENTRY")
                  local head,body = request_handle:httpCall("lua_cluster", 
                  {
                       [":method"] = "GET",
                       [":path"] = "/v3/875b1e5a-0a25-47e4-a9f7-ae33b988edb3",
                       [":authority"] = "run.mocky.io"
                  },nil, 5000)
                  request_handle:logWarn("status " .. head[":status"])
                  request_handle:logWarn("EXIT")
                end
                function envoy_on_response(response_handle)
                  body_size = response_handle:body():length()
                  response_handle:headers():add("response-body-size", tostring(body_size))
                end
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: lua_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS # static
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: lua_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: run.mocky.io
                port_value: 80
  - name: web_service
    connect_timeout: 0.25s
    type: STRICT_DNS # static
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 80

**Comment by phlax** [comment]
@sumitaneja can you surround all of your quoted code and log traces with ` ``` ` - it will make it a lot easier to read

**Comment by sumitaneja** [comment]
@phlax Thanks.updated comments.

**Comment by sumitaneja** [comment]
> @sumitaneja can you surround all of your quoted code and log traces with `` ``` `` - it will make it a lot easier to read

@phlax Thanks.updated previous comments.

**Comment by snowp** [comment]
When issuing a synchronous httpCall the filter will pause the stream until we get the response (since we handle the response inline in the Lua), which then ends up having to buffer the request when making a fall during on_request. 

The API lets you fire and forget the request (by setting the `async` param), but I don't think there is a way to asynchronously handle the response of the http call. If someone can figure out a way for that to make sense in the API I wouldn't be opposed to adding it, but I think it would take some careful thought

**Comment by sumitaneja** [comment]
@snowp Is it not possible to not to buffer request during filter execution. That was understanding while using filter. We expect filter not to read body unless explicitly requested and API exposed by lua filter gives optimal performance.

Else whats the alternative, We have requirement to do some request and response validation by external service.

Request payload can be upto 1 gb. and filter doesn't need to read payload.

**Comment by snowp** [comment]
Currently the code will buffer the request while waiting for the response (I assume in order to allow code to read the body after the call), unless you set the https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall `asynchronous` value to true. This would mean that you don't get to see the response of the httpCall however. Any other changes to this behavior would require code change in some way.

Besides this you could always do this as a native C++ filter which provides more control over control flow, or if WASM API provides more flexibility around this (I'm not very familiar with it) that might be an option.

**Comment by sumitaneja** [comment]
That would need envoy/istio upgrade.
for current release If we increase buffering limit, Can you confirm if buffering happens in-memory or in some temp file for large payloads.
.

**Comment by snowp** [comment]
It's all in memory
