### ISSUE TITLE
Add ability to filter ConfigDump by arbitrary predicates

### ISSUE THREAD

**Issue by paul-r-gall** [envoyproxy/envoy#16680]
*Title*: Add ability to filter ConfigDump by arbitrary predicates

*Description*:
ConfigDump has the potential to be extremely large in production, even after filtering by resource. I'd propose adding the ability for integrations to register per-resource matchers, and then add a general `match_*` query parameter family allowing users to specify additional matching parameters. 

For example, `/config_dump?match_id=abcd&match_some_data=efgh&resource=dynamic_routes` will use the registered RouteConfiguration matcher to see which dynamic routes match the parameters {id: "abcd", some_data: "efgh"}, and only return those.

I've already started work on a partial implementation of the above.

**Comment by phlax** [comment]
cc @mattklein123

**Comment by mattklein123** [comment]
Sounds great!

**Comment by paul-r-gall** [comment]
See draft pr #16774.

**Comment by mattklein123** [comment]
Do we really need this feature to be extensible? Do you have a use case for it? Can we just have the functionality be built-in?

**Comment by paul-r-gall** [comment]
I think that if we want to provide filtering by _arbitrary_ predicates, then it needs to be extensible.

I.E., the end user knows best what parameters they want to match on and how that matching works, and we should provide the framework/ability for them to override the whatever default name/metadata matching we settle on.

**Comment by mattklein123** [comment]
> Edit -- while at the moment, simple name/metadata regex matching is sufficient for Google's use case, it's likely we'll need to do more sophisticated matching in the future.

I apologize for being dense, but can you help me with a contrived example of what a different extension might do?

**Comment by paul-r-gall** [comment]
> I apologize for being dense

More likely than not it's me who's being dense.

I was considering a search query like "All dynamic route configs that include a route which maps to cluster `xyz`", or "All scoped route configs whose first key fragment = `123` and whose second key fragment = `456`". Additionally, a custom extension would have the option of doing different matching for different config types, as opposed to a single generic match on `Protobuf::Message`.

All that said, I do know that creating and maintaining a new extension is extra work and complexity, so I'll defer to the maintainers when considering what would be best. 

As an aside, there's also discussion happening on the draft PR linked above.

**Comment by paul-r-gall** [comment]
Filtering by name regex completed, closing this issue.
