### ISSUE TITLE
Envoy closes downstream connection if upstream hangs up before response

### ISSUE THREAD

**Issue by xjtian** [envoyproxy/envoy#16707]
*Title*: *Envoy closes downstream connection if upstream hangs up before response*

*Description*:

If an upstream hangs up (e.g. due to workload termination) after a request is forwarded but before it has sent any part of the response back, Envoy will close the downstream client's TCP connection. I was expecting this to return a 503 and respect retry configuration, but Envoy kills the downstream connection immediately once the upstream hangs up.

*Repro steps*:

- Make a HTTP/1.1 request to an upstream that takes a while to compute a response
- Terminate the upstream workload before it sends the response
- Envoy will close the downstream client connection

**Comment by mattklein123** [comment]
In general, this is not true. Envoy will keep the connection open if it can. Please provide more detailed logs (on debug/trace level) if you are able to repro your case.
