### ISSUE TITLE
[deps] Create github action to file github issues for stale deps

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#16705]
Mentioned in https://github.com/envoyproxy/envoy/pull/16687

>  It would be good to track dependencies more closely, we fell behind on grpc by 6 months and multiple releases.

It should be possible to run a github actions workflow scheduled once per day to check if newer releases have happened for our deps.

We already have [code](https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/tools/dependency/release_dates.py#L43) to check if there was a newer release date for the dependencies we have. We would need to use this method (maybe pipe in a configuration parameter) to auto-file github issues instead. Creating issues could reuse code from the deprecation [create_issues](https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/tools/deprecate_version/deprecate_version.py#L53) method.

**Comment by kaushambisharma** [comment]
would like to work on this issue but will need some guidance.

**Comment by ME-ON1** [comment]
Hi, 

I was looking at this issue and i have some question to ask!  
do we need to create different issue for diff deps or one issue for all lagging deps . And at what time should the action start running this ??

**Comment by asraa** [comment]
I would think maybe one issue per dependency, since that way PRs can be issued updating one dependency at a time against them (sometimes it would be hard to batch updates)

Time shouldn't matter.

**Comment by phlax** [comment]
fixed by #17876
