### ISSUE TITLE
Lua filters for TCP Proxy?

### ISSUE THREAD

**Issue by ajsalow** [envoyproxy/envoy#16758]
Is there a way to use Lua filters with the TCP proxy like you can with the HTTPConnectionManager?

**Comment by junr03** [comment]
Not currently. The Lua stack is only adapted for HTTP operation as an HTTP filter.

**Comment by amankumarcs** [comment]
Is there a way to use Lua filters with the TCP proxy like you can with the HTTP connection manager?
