### ISSUE TITLE
Use protoc-gen-doc for generating proto rst

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16769]
In trying to find a way to turn the current docs build into a bazel build job i have been looking at the protodoc code, but im struggling because im not finding an easy way to make an aspect build a dep of another build rule

Another goal i have here is to use a template syntax for protodoc

afaict (and happy to be corrected) the current aspect implementation:

- generates for all dependencies for each of the included protos
- does this repeatedly as many of the deps are shared
- generates rst for many protos that are then not included in the final docs

I then started to look at a more efficient way of generating these rst files and came across https://github.com/pseudomuto/protoc-gen-doc

While this project doesnt have support for generating rst - there is a fork that does here https://github.com/flyteorg/protoc-gen-doc which uses a template syntax for generating the rst

It seems to me that we could kill 3 proverbial birds with one stone - ie:

- only generate rst for protos that are actually used
- only generate rst for any included proto once
- make use of a template syntax at the protoc generation stage

**Comment by phlax** [comment]
cc @htuch @mattklein123

**Comment by phlax** [comment]
one possible issue with this approach is inclusion of protoc-gen-validate annotations - altho there is a related bug here https://github.com/pseudomuto/protoc-gen-doc/issues/434

**Comment by phlax** [comment]
regarding this last point - ie pgv - im not sure if these are currently used in docs generation

**Comment by mattklein123** [comment]
At a high level this sounds fine to me, but I don't have a very good understanding of the flow. @htuch will be a better person to talk to when he is back.

**Comment by phlax** [comment]
investigating a bit further - a few things ive found...

### protoc-gen-doc

not so sure about using this. Afaict its pretty much abandonware - at least v poorly maintained.

also not sure it does what we want without quite a lot of hackage. While i think we do want to move towards a template based system, we need annotations to be parsed before attempting to render the template

protoc-gen-doc uses go templates - which is usable - but we would need to hack quite a lot into the actual go code in order to get all of the parts we want parsed, before entering the template

having said that it did show some promise in that generating rst files using this took a fraction of the time taken by current rst generation, and it didnt make my computer sound like a bitcoin miner while it did it

### api protos aspect rendering

while this does also generate rst from all deps it does at least have some code to filter out any deps that dont start with an `envoy.` prefix - so it doesnt (repeatedly) parse and generate all of the google wkt protos

what this means is that it all the v2 protos are still included and there are some duplications from transitive deps

afaict it generates ~2x as many rst files as are actually used

### summary so far

i think we want to use a pattern of parsing individual files without deps, i think without using an aspect as this seems to be the source of the inefficiency, but i think we more likely want to use a python protodoc parser with a jinja template as i had first thought

**Comment by phlax** [comment]
closing this - protoc-gen-docs seems to be a bit of a non-starter for reasons laid above, also i have managed to get the protodoc aspect working with a build rule.

There is still some inefficiency here as it builds redundant v2 api protos -> rst - this could be resolved with some additional filtering i guess - but it will also become a non-issue once the v3 protos no longer have v2 protos listed as deps
