### ISSUE TITLE
Seeking proposals for how to implement STREAMING body mode in ext_proc

### ISSUE THREAD

**Issue by gbrail** [envoyproxy/envoy#16760]
*Title*: Help figure out how to implement STREAMING body mode for the ext_proc filter

*Description*:

The ext_proc protocol describes four ways to handle request and response bodies:

1) Ignore them. This is the default and works fine.
2) BUFFERED mode -- this is already implemented. The filter buffers the body in memory, returns an error if the buffer fills up before end of stream, sends the buffer to the external processor, and waits for a response which will optionally modify the buffer.
3) STREAMING mode -- not implemented yet. This is intended to support the use case of an external processor that wants to modify the body one chunk at a time, or otherwise handle a body of arbitrary size.
4) BUFFERED_PARTIAL -- not implemented yet. This is intended for processors that want to inspect only the start of the body, or perhaps cache bodies smaller than a certain maximum size.

In order for STREAMING mode to be implemented, the filter would need to do something like this, for both the encoding and decoding paths:

1) en|decodeData is called with a chunk of data.
2) Save a pointer to the buffer that we just received.
3) Send a message on the gRPC stream that contains the new body chunk.
4) When the processor sends back a response, apply any modifications to the body chunk saved in step 2.
5) Continue processing, which will presumably loop back to step 1.

This doesn't work consistently because there is no way for step 1 (en|decodeData) to respond with a status that tells the filter manager, "do not continue iteration and do not send me any more chunks." As a result, in some cases, we perform steps 1, 2, and 3, and then while waiting for the response, we end up back on step 1 even though we never got to step 4. As a result, we don't know how to apply modifications to the body in a way that will allow us to properly process them in order.

In some cases, a combination of StopIterationAndWatermark, combined with calling "*AboveWriteBufferHighWatermark" seems to do the trick. But sometimes it doesn't. The result is that after en|decodeData returns, but before it can call "continue," the next chunk is delivered.

Since this doesn't work, I can think of a few more possibilities:

1) The filter could try to keep track of all the chunks that it received, assuming that a StopIterationAndWatermark status means that although more chunks will be received, none will be forwarded to other filters. Then, apply responses to individual chunks as they come back. But the problem here is that when we finally call "continue," won't all the chunks be sent on down the filter chain?
2) The filter could try to somehow be notified when the watermark really causes reading of writing is paused. It could buffer everything to that point and not clear the watermark until it has all been processed. I don't see how to do that in both directions, however.
3) The filter could keep track of multiple buffers, but then clear each buffer so that when we "continue" it would just continue with empty buffers down the filter chain. Then when we actually know what data should be forwarded, we could call "injectEn|DecodedDataToFilterChain." This might work and I'll have to try it.
4) We could give up and make streaming mode read-only. We can probably adjust things so that the filter will still have the ability to send back an error in many cases after reading the body, but otherwise the body would really be read-only. This would mean that there are cases in which ext_proc is not useful.

If you read all this, then thanks -- as you can see I could use some advice on how to make this whole thing work!

**Comment by junr03** [comment]
@snowp do you want to comment as the other owner of ext_proc?

**Comment by snowp** [comment]
3) seems like a reasonable way to do this, though it probably needs some testing to make sure there's nothing preventing this from working. If you want to avoid the empty data frames to the next filters maybe you can stop iteration in this case? 

cc @alyssawilk in case there are other ways of accomplishing this

**Comment by alyssawilk** [comment]
I guess offhand I can think of 2 ways to handle this.

The cleaner way would be to implement a StopAllIteration for body data, like we have for headers.  This would really stop further calls until resumption was triggered.  That said, it's going to be a complicated and high risk change.

The hackier way would be akin to 3, moving the data into locally owned buffers as encodeData calls happen and re-injecting the original or modified data as return calls are processed.  If you would want a series of streamed RPCs this may not be that terrible, though you'd want to make sure you use the watermark callbacks to stop the flow of incoming data as your locally cached data grows past configured limits.

**Comment by gbrail** [comment]
Thanks for the comments so far. Plan 3 -- clearing buffers as we send them to the remote server, and then using the "inject into filter chain" capability to put them back -- works for me in some manual tests. My current challenge is figuring out how to test them properly in an automated way. I'll probably have a draft PR next week or the week after.

**Comment by gbrail** [comment]
I have a working PR, with working tests for this now:

https://github.com/envoyproxy/envoy/pull/17069

It works using the idea "3" from up top:

1) As data callbacks come in to the filter, it "moves" the data into a new buffer, which it dispatches via gRPC message to the external processor, and then keeps in a queue.
2) As a result, filters farther down the chain see empty buffers in their data callbacks.
3) When a response comes back from the external processor, it injects the processor's result into the filter chain using "inject**codedData". (The processor may respond indicating that there is no change, which means that the original buffer stored in the queue is what gets injected.)
4) The filter raises the watermark when chunks are outstanding to be processed by the filter so that we do not fill up with buffers waiting for processing.

This works well for large bodies and I have observed that I can stream them through without running out of memory, and the watermarking appears to be working. The stream of body chunks being sent to the processor also ends up being pipelined, which is a good thing because otherwise latency would be very high.

As it is, this feature has the potential to introduce a lot of latency for large message bodies, because in the worst case each body chunk has to endure a gRPC round trip. So while this feature will make it theoretically possible for someone to, for example, compress or encrypt data without buffering, in practice I think this will be uncommon and slow.

I think that a better use case for this feature would be to effectively buffer the data, but to have a safety valve to ignore bodies that are larger than a certain size. I'm also considering another body processing mode specifically designed for this which I think will be more useful.
