### ISSUE TITLE
Bazel internal env variable $TEST_TEMPDIR is used in build_setup.sh

### ISSUE THREAD

**Issue by boringuy** [envoyproxy/envoy#16788]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Bazel internal env $TEST_TMPDIR variable is used in build_setup.sh*

*Description*:
According to the link below, $TEST_TMPDIR is for bazel internal use only. "--test_tmpdir" should be use instead. Using $TEST_TMPDIR somehow has a side effect of setting bazel max_idle_secs to 15 instead of the default 3 hours which caused it to wipe the sandbox (I was using --sandbox-debug) every time I run do_ci.sh and wiping the sandbox takes a long time. Switching to use "--test_tmpdir" doesn't override the max_idle_secs. So, is this intentional so do_ci.sh will shutdown bazel basically immediately? If not, I can submit a PR to change build_setup.sh to use "--test_tmpdir" instead. 

[optional *Relevant Links*:]
https://github.com/bazelbuild/bazel/issues/11062

**Comment by junr03** [comment]
cc @lizan

**Comment by boringuy** [comment]
So, was trying out the change and turns out $TEST_TMPDIR also change the output base path, so if we don't set it, we also need to add bazel startup option --output_base or --output_user_root to mimic the current behavior. Since I am not familiar with existing ci environment, I am probably not the best to make a PR for this. So, this is more just a question and I can work around this locally.

**Comment by lizan** [comment]
Yes it is set intentionally for CI purpose. But we're open to change it to more explicit way by specifing `--test_tmpdir` and `--output_base`. In CI environment the idle secs should be small as well.
