### ISSUE TITLE
ci README contains scripts that don't exist

### ISSUE THREAD

**Issue by justincely** [envoyproxy/envoy#16790]
*Title*: ci README contains scripts that don't exist

*Description*:
[Testing changes to the build image as a developer](https://github.com/envoyproxy/envoy/tree/main/ci#testing-changes-to-the-build-image-as-a-developer) as a section seems to be outdated.  The instructions are:

```bash
DISTRO=ubuntu
cd ci/build_container
LINUX_DISTRO="${DISTRO}" CIRCLE_SHA1=my_tag ./docker_build.sh  # Wait patiently for quite some time
cd ../..
IMAGE_NAME="envoyproxy/envoy-build-${DISTRO}" IMAGE_ID=my_tag ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.whatever'
```

But the entire `ci/build_container` directory doesn't exist and I don't see the other scripts anywhere else in the `ci` folder.  Did these move, or are these just outdated?

**Comment by phlax** [comment]
not sure of the exact history - but my guess is that https://github.com/envoyproxy/envoy-build-tools was separated out from the main repo at so,me point - and these notes werent updated

**Comment by mk46** [comment]
The above docs are in favor of Circle CI  which is deprecated.

**Comment by mk46** [comment]
In https://github.com/envoyproxy/envoy/pull/10729, `ci/docker_build.sh` was removed.

**Comment by justincely** [comment]
Should I just open a PR to remove this section then?  For me it was just added noise that confused me trying to get CI scripts running locally.

**Comment by phlax** [comment]
> Should I just open a PR to remove this section then?

i think yes - but lets open the PR and check again

**Comment by mk46** [comment]
#16800 is merged. Can we close this?

**Comment by phlax** [comment]
yep, closing...
