### ISSUE TITLE
How to configure from reverse proxy to forward proxy?

### ISSUE THREAD

**Issue by malza321** [envoyproxy/envoy#16815]
Hi. I'm struggling with configure conf from reverse proxy to forward proxy.
![image](https://user-images.githubusercontent.com/45122419/120800448-eb579680-c57a-11eb-82a6-e287ad9a2c0b.jpeg)

No.1 I made it.

But When I try No.2 with https, proxy A always response 400 Bad request. And there is no problems with http.

proxy A just dose forward to proxy B1, B2 with load balancer without any certificate because It just needs for forward to proxy B1, B2.

To test I used curl -x http://proxy A https://target

Any recommendations to make this one? 

thanks!

**Comment by junr03** [comment]
It would be helpful if you shared your current configuration

**Comment by malza321** [comment]
> It would be helpful if you shared your current configuration

Here is my conf in proxy A
  listeners:
  - name: proxyA
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 44000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: proxyB
          http_filters:
          - name: envoy.router
  clusters:
  - name: proxyB
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: proxyB
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: proxyB
                port_value: 44000

**Comment by phlax** [comment]
@malza321 please enclose all configuration and log traces etc in ` ``` `

**Comment by malza321** [comment]
> @malza321 please enclose all configuration and log traces etc in ` ``` `

Thanks a lot! :)
