### ISSUE TITLE
Backport request: Backport PR `16643` to 1.18 

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#16820]
### Backport request: Backport PR https://github.com/envoyproxy/envoy/pull/16643 to 1.18 

I would like to request a backport of the PR https://github.com/envoyproxy/envoy/pull/16643 to the 1.18 branch. The main motivation is the following.

I have a private CI pipeline which I am developing to build and publish `envoy.exe` and I want to be able to tell the `windows_ci_steps.sh` to only build `envoy.exe`. This is important because we our pipeline does a lot of things which I want to avoid because they reduce the reliability of the pipeline and require credentials such as the deflaking script.

### Risks associated with the backport

Looking at the changes in the PR, they do not affect the production code and hence regression probability is extremely slim

**Comment by davinci26** [comment]
I can prepare the PR if it helps

**Comment by alyssawilk** [comment]
@dmitri-d thoughts?

**Comment by dmitri-d** [comment]
@alyssawilk:  will do

**Comment by dmitri-d** [comment]
Opened a PR: https://github.com/envoyproxy/envoy/pull/17068

**Comment by davinci26** [comment]
Closed by #17068. Thanks @dmitri-d for doing this!
