### ISSUE TITLE
proto_sync uses py input and stalls in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16835]
### description

there are a couple of places in the `proto_sync.py` script that use py `input` to get confirmation from users whether changes should be applied

this doesnt make sense in CI where it just stalls, and makes the format job fail with no useful output after waiting for a long time

**Comment by phlax** [comment]
cc @htuch

**Comment by mk46** [comment]
Hi @phlax, I would like to work on this.

**Comment by phlax** [comment]
cool @mk46 ill assign the ticket to you

i think the easiest would be to detect somehow whether its a ci env and just skip asking
