### ISSUE TITLE
OSX Build: md5sum and /proc/cpuinfo needed

### ISSUE THREAD

**Issue by msample** [envoyproxy/envoy#1683]
Followed current build instructions for OSX but building with bazel on OSX/macos also needs a md5sum binary and a /proc/cpuinfo file.

cheap fix (would be better not to grep /proc/cpuinfo or to use 'sysctl -a hw' on OSX):

```
brew install md5sha1sum  
sudo mkdir -p /proc
sudo docker run <linux-image-you-have> cat /proc/cpuinfo  > /proc/cpuinfo
```

Also OSX Sierra (10.12.x) or greater is required to get the required 8.3.3 version of xcode.  The AppStore will spin forever if you try to upgrade xcode on an earlier OSX.

Complaints before cheap fix:

```
WARNING: /Users/*/envoy-filter-example/envoy/bazel/repositories.bzl:26:5: /private/var/tmp/_bazel*/60fe7735f74821add3f845fcade3ae2a/external/envoy_deps/./repositories.sh: line 9: md5sum: command not found

WARNING: /private/var/tmp/_bazel*/729952d62f84db3f8ddad6d51f4d2c7d/external/envoy/bazel/repositories.bzl:18:5: Fetching external dependencies...
External dependency cache directory /private/var/tmp/_bazel*/729952d62f84db3f8ddad6d51f4d2c7d/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
grep: /proc/cpuinfo: No such file or directory
```

**Comment by msample** [comment]
I just reviewed my install history and I think this can be closed.   I was looking at fixing these issues and noticed that they occurred before I updating the envoy submodule in envoy-filter-example. After updating, the files with the warnings cited have OS X/Darwin specific fixes. 

Sorry for the noise.

**Comment by mattklein123** [comment]
OK closing.
