### ISSUE TITLE
HTTP3 demo config has errors

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#16843]
### description

the http3 demo configuration has a configuration error here:

https://github.com/envoyproxy/envoy/blob/72bf41fb0ecc039f196be02f534bfc2c9c69f348/configs/envoyproxy_io_proxy_http3_downstream.yaml#L16-L28

trying to load this throws the following error:

```
ERROR (validation failed): configs/envoyproxy_io_proxy_http3_downstream.yaml
Failed to parse static_resources field: Failed to parse listeners field: Failed to parse filter_chains field: Failed to parse transport_socket field: Message type "envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext" has no field named "downstream_tls_context".
 Available Fields(except extensions): ['commonTlsContext', 'requireClientCertificate', 'requireSni', 'sessionTicketKeys', 'sessionTicketKeysSdsSecretConfig', 'disableStatelessSessionResumption', 'sessionTimeout', 'ocspStaplePolicy']....
```

currently this problem is hidden from CI as the `listeners` field is repeated and this entire block is ignored (i found this linting the yaml)

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by mk46** [comment]
Hi @phlax, I think the config should be like below 
```
           name: envoy.transport_sockets.quic
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
```

**Comment by phlax** [comment]
@mk46, do you want to PR a fix ?

if you do - dont forget to remove the additional `listeners`

@alyssawilk can you confirm that this was the intended config ?

**Comment by mk46** [comment]
See my change https://github.com/mk46/envoy/commit/a58423f11fa424dd9811dd579441741c4ecfb529. I have tested with and without a UDP listener.

**Comment by phlax** [comment]
seems right to me - ill assign this ticket to you

**Comment by alyssawilk** [comment]
Hey @adisuissa it seems pretty broken that Envoy would ignore half the config due to what's basically a yaml error, without warnings of any kind.  @phlax is working on linting our example configs but I'm wondering if we could do better in-Envoy to detect and reject configs like this.  WDYT?
