### ISSUE TITLE
update links to jaegertracing-plugin.tar.gz

### ISSUE THREAD

**Issue by codefromthecrypt** [envoyproxy/envoy#16866]
*Title*: update links to jaegertracing-plugin.tar.gz

*Description*:

It is super cool that there are examples, but these are pointing to a GitHub repository which will become archived. Can these plugins be re-hosted here or at jaeger instead?

That or remove the content, doesn't matter to me, just I don't want these links to break without knowing cc @phlax 

```
examples/front-proxy/Dockerfile-jaeger-service
14:         && curl -Ls https://github.com/tetratelabs/getenvoy-package/files/3518103/getenvoy-centos-jaegertracing-plugin.tar.gz \

examples/jaeger-native-tracing/Dockerfile-frontenvoy
15:         && curl -Ls https://github.com/tetratelabs/getenvoy-package/files/3518103/getenvoy-centos-jaegertracing-plugin.tar.gz \
```

**Comment by phlax** [comment]
for reference - related tickets - that gave rise to the hacky workaround...

in envoy rep - https://github.com/envoyproxy/envoy/issues/12287

and in tetrate repo - https://github.com/tetratelabs/getenvoy-package/issues/35

im wondering how tetrate derived this binary - and whether it would be possible to eg add a bazel rule to compile it in the envoy repo, or perhaps just as part of building the example

**Comment by lizan** [comment]
I did it in a hacky way to derive the binary, the recipe is https://github.com/tetratelabs/getenvoy-package/issues/35#issuecomment-541380474 . We should be able to do that in CI if it is desired.

**Comment by phlax** [comment]
@lizan any thoughts about the best way forward on this ?

im tempted to initially just copy the binary into the repo - and then open a ticket re adding build instructions etc

**Comment by codefromthecrypt** [comment]
GitHub has packages also. This could be done with an OCI tool using ghcr.io and envoyproxy in the repo name

Another way is to create a junk repo in envoyproxy org and add a release named "jaeger", and upload the files here into that release. Then you can use the raw URLs here.

Regardless, something should be done, ideally without checking these into the source tree as it is already expensive to clone.

Even a junk repo in the envoyproxy org is better than a strange dependency on a 3rd party site, even if that site wasn't a dead domain.

food for thought.

**Comment by mattklein123** [comment]
@codefromthecrypt frankly we have limited resources to deal with all of these types of issues. If you are willing/able to help I'm happy to create a repo for you in envoyproxy and you can fix?

**Comment by phlax** [comment]
> Even a junk repo in the envoyproxy org is better than a strange dependency on a 3rd party site, even if that site wasn't a dead domain.

its on my list of things to do, i just havent got round to it yet, any help appreciated

**Comment by codefromthecrypt** [comment]
sure. If it were me, I would call the repo "misc" or similar

given a release called "jeagertracing-plugin", we could upload these artifacts and the download url would look like this:

`https://github.com/envoyproxy/misc/releases/download/jeagertracing-plugin/jeagertracing-plugin-centos.tar.gz`

this could be used for any other opaque or otherwise informal artifacts that help in docs but aren't worth making a separate project over.

If you like this, go ahead and create the repo and add me. I'll move the things there and send a PR to update the links accordingly. I don't feel strongly on repo name so feel free to change it.

**Comment by codefromthecrypt** [comment]
also if there are any issues with the format of the link or we want make them permalinks, we can in any case setup redirects here https://github.com/envoyproxy/envoyproxy.github.io/blob/main/netlify.toml

**Comment by mattklein123** [comment]
@codefromthecrypt I made you https://github.com/envoyproxy/misc and gave you write access. Please let me know if you need other access. Please also setup a README on the new repo. Thank you a ton for helping with this.

**Comment by codefromthecrypt** [comment]
ok done. https://github.com/envoyproxy/envoy/pull/17497

feel free to revise the [README](https://github.com/envoyproxy/misc) or anything as you see fit
