### ISSUE TITLE
HTTP/JSON to gRPC/Flatbuffers transcoder

### ISSUE THREAD

**Issue by joseprupi** [envoyproxy/envoy#16875]
I would like to know what is the best way to implement a transcoder for HTTP/JSON to gRPC/Flatbuffers.

I am thinking on implementing my own filter that encodes and decodes but any recommendation and if possible point me to some documentation would be appreciated

**Comment by zuercher** [comment]
I think the existing grpc filters are probably a good place to start. The grpc_web and grpc_json_transcoder filters both convert protocols (although neither accepts json).

**Comment by joseprupi** [comment]
Thanks, I will take a look to those
