### ISSUE TITLE
Pods getting destroyed with Error - "envoy main caught SIGTERM "

### ISSUE THREAD

**Issue by surendarmsk1** [envoyproxy/envoy#16893]
Our environment is having envoy proxy configured across each Pod and we see Pods are getting destroyed very often. Below are the istio-proxy logs. As we can see, suddenly after 200 response, Pod is getting terminated.

what are the other areas where we can troubleshoot this issue as why pod was destroyed?

"textPayload": "[2021-06-06T07:18:50.069Z] GET /source/prometheus **HTTP/1.1 200** - 0 175218 287 286 - Prometheus/2.21.0
"textPayload": "2021-06-06T07:18:55.705823Z\tinfo\tAgent draining Proxy\n",
"textPayload": "2021-06-06T07:18:55.705824Z\tinfo\tWatcher has successfully terminated\n",
"textPayload": "2021-06-06T07:18:55.705840Z\tinfo\tStatus server has successfully terminated\n",
"textPayload": "2021-06-06T07:18:55.706103Z\terror\taccept tcp [::]:15020: use of closed network connection\n",
"textPayload": "2021-06-06T07:18:55.706843Z\tinfo\tGraceful termination period is 5s, starting...\n",
"textPayload": "2021-06-06T07:19:00.706956Z\tinfo\tGraceful termination period complete, terminating remaining proxies.\n",
"textPayload": "2021-06-06T07:19:00.707019Z\twarn\tAborting epoch 0...\n",
"textPayload": "2021-06-06T07:19:00.707049Z\twarn\tAborted all epochs\n",
"textPayload": "2021-06-06T07:19:00.707056Z\tinfo\tAgent has successfully terminated\n",
**"textPayload": "2021-06-06T07:19:00.707618Z\twarning\tenvoy main\tcaught SIGTERM\n",**

**Comment by daixiang0** [comment]
I guess it is not root cause, could you check your app logs?

**Comment by surendarmsk1** [comment]
This is an GKE cluster and Yes, the above pasted logs are from entire pod app logs and i am pasting the screenshot of it.. As we could see, we are getting 200 response till 2021-06-06 12:48:52.281 IST and Post that Pod started to destroy. Apart from these logs, we don't have anything elseat app level. I also checked the istio-gateway log & cpu/memory/heapsize of this pod during issue timeframe & everything looks good.

Anything else we need to focus on to find the cause of this pod destroy?

![image](https://user-images.githubusercontent.com/67820537/121317850-4ba65980-c928-11eb-9d31-213a790acd45.png)

**Comment by phlax** [comment]
@surendarmsk1 i think the suggestion was to post the envoy logs

re logs please post the text and enclose in ` ``` `

**Comment by surendarmsk1** [comment]
Unfortunately we dont have envoy logs configured on the clusters. Is there any other way to get this issue checked?

**Comment by phlax** [comment]
i doubt we will be able to help you without them - i think you'll need to figure out a way to access them

**Comment by surendarmsk1** [comment]
Closing as not required logs are available
