### ISSUE TITLE
Enhance ext authz filter to pass labels for peer info

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#16898]
CheckRequest API supports passing additional labels such as pod labels https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#service-auth-v3-attributecontext-peer in the peer's attribute context.

However ext authz filter does not have configuration to specify those labels. We have a usecase to pass k8s pod labels to checkrequest.

Can we enhance ext authz filter and add labels config so that checkRequest can use it while constructing request?

Are there any alternatives?

**Comment by zuercher** [comment]
cc @esmet

**Comment by esmet** [comment]
I think this is a reasonable feature request. In the mean time, could you use the Kubernetes downward API to push labels into the pod as configuration, and include those as request headers? https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api

You could then have your auth service read those request headers and do the appropriate thing.

**Comment by ramaraochavali** [comment]
@esmet Can you explain more about how to pass request headers from pod config? BTW, we are using gRPC external authz service. But I am curious to know how to pass pod config -> request headers? Sorry - I am not fully aware how that works.
