### ISSUE TITLE
ftp proxy support?

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#16901]
Envoy supports proxy various protocols, http, kafka, redis, mq and so on. I wonder if it is possible to add another ftp proxy to envoy?
haproxy supports the ftp protocol, but only supports passive mode. Envoy may be able to do better. 🤔

**Comment by moderation** [comment]
FTP should be considered deprecated and should not be added to Envoy - https://developers.google.com/web/updates/2019/12/chrome-80-deps-rems

**Comment by phlax** [comment]
im not sure the protocol is deprecated just because chromium no longer supports it - i think there are still use cases for it (altho tbh i personally havent used it for some time)

**Comment by phlax** [comment]
eg - package distribution - https://wiki.debian.org/FTP

**Comment by moderation** [comment]
We know from analysis that Curl is bad news from a security, CVE and dependency point of view. We want to remove Curl - https://github.com/envoyproxy/envoy/issues/11816. Whether ftp is considered deprecated or not, we should not enable it in core Envoy for similar reasons

**Comment by wbpcode** [comment]
I think that chrome no longer supports FTP does not mean that FTP is abandoned. In fact, FTP is still widely used in many places.

I don't quite understand why it is related to Curl lib. The two seem to be incomparable. As @phlax  said, one is the protocol and the other is the library.

**Comment by moderation** [comment]
The point of raising curl was not to say it was equivalent to FTP. Assuming that an existing library would be used for FTP, it would introduce a new dependency. FTP is a protocol but in order for Envoy to support it, wouldn't a library / code be required to implement it?

As outlined in https://envoycon2020.sched.com/event/ecdA/understanding-maintaining-and-securing-envoys-supply-chain?linkback=grid-full, curl represents the largest concentration of CVE's that impact Envoy. There could be a bulletproof, fuzzed and well maintained FTP library with a CVE track record we could use. But as curl has demonstrated (and Envoy as well) building secure networking code is difficult. 

FTP could be enabled as an extension and compartmentalized. A new extension would need to follow the policy at https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md.  And the introduction of new dependencies needs to follow the policy at https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md

**Comment by wbpcode** [comment]
The FTP protocol is actually quite simple (although its network model is slightly more complicated). So I think we may not need to introduce new deps.

**Comment by wbpcode** [comment]
> FTP could be enabled as an extension and compartmentalized. A new extension would need to follow the policy at https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md. And the introduction of new dependencies needs to follow the policy at https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md


Yes, adding new extensions must of course conform to the community's norms. This issue is just to understand the wishes of the community and the possibility of adding fpt support.
If the community recognizes that this work is valuable to Envoy users, then we can try to promote it.
