### ISSUE TITLE
Make upstream ClientConnection available to Encoder Filter

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#16929]
*Title*: *Make upstream ClientConnection available to Encoder Filter*

*Description*:
Our proxy needs to record the connection level stats, like RTT to the backend on the per-request basis.
That information seems to be available on the ClientConnection, but the encoder filter doesn't have access to it.
It would be useful to make it available (if there is one).

**Comment by efimki** [comment]
@alyssawilk @htuch

**Comment by htuch** [comment]
@efimki in your case, why can't an upstream filter obtain these connection level stats and then have them propagated back to the HTTP filter (in HCM) via https://github.com/envoyproxy/envoy/pull/15543/files?

**Comment by alyssawilk** [comment]
@htuch that'd be ideal, but upstream filters aren't implemented yet :-)

**Comment by snowp** [comment]
We do have upstream network filters, would that be sufficient?

**Comment by alyssawilk** [comment]
The ask was for per-request RTT so I _think_ not unless there's some clever way to communicate between the upstream network filter and the codec?

**Comment by snowp** [comment]
Could the network filter periodically update a value in the FilterState with the current (last read) RTT of the connection, allowing a filter to read this value from the upstream connection FS?

**Comment by htuch** [comment]
Yeah, I think periodic update for RTT might be plausible as an approximation with a snapshot on downstream HTTP events, previously discussed with @efimki. I'm hoping we get upstream HTTP filters soon though :)
