### ISSUE TITLE
How to do hot restart of istio envoy proxy?

### ISSUE THREAD

**Issue by lokeshwaran100** [envoyproxy/envoy#16934]
*Title*: *How to do hot restart of istio envoy proxy?*

*Description*:
I could see there is a python wrapper available to perform the hot restart. But from where it needs to be invoked from?

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter#operations-hot-restarter
https://blog.envoyproxy.io/envoy-hot-restart-1d16b14555b5

**Comment by ramaraochavali** [comment]
Currently hotrestart is not supported in Istio. Why do you want to hot restart it? Can you explain more about the usecase?

**Comment by lokeshwaran100** [comment]
> Currently hotrestart is not supported in Istio. Why do you want to hot restart it? Can you explain more about the usecase?

@ramaraochavali: I'm using [istio-csr](https://github.com/cert-manager/istio-csr) agent for provisioning external CA via cert-manager. In this case, the root certificate is provided by me. I might need to change this root certificate in future but not very often though. When I change the root certificate I need to delete the [istio-csr](https://github.com/cert-manager/istio-csr) agent pod, istiod pod and also the workload pod in order to make it work. But I don't want to bring down the workload pod which will cause downtime. Instead, I could see that envoy proxy allows something called hot restart which will allow the envoy proxy to use the update configuration without downtime. So wondering whether istio provides such support?

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/31522 - Would this help?

**Comment by zuercher** [comment]
Since this is more an Istio question than an Envoy one, I'm going to close it.
