### ISSUE TITLE
Resource Type in Dynamic Configuration Control Plane pointing to v2

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#16937]
*Title*: *Resource Type is still pointing to v2*

*Description*:
> In Sandboxes examples, dynamic control plane configurations for proxy's cluster resource type is v2. is this correct ?

[optional *Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/dynamic-configuration-control-plane

[
  {
    "cluster": {
      "**@type": "type.googleapis.com/envoy.api.v2.Cluster"**,
      "name": "xds_cluster",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "http2_protocol_options": {},
      "load_assignment": {
        "cluster_name": "xds_cluster",
        "endpoints": [
          {
            "lb_endpoints": [
              {
                "endpoint": {
                  "address": {
                    "socket_address": {
                      "address": "go-control-plane",
                      "port_value": 18000
                    }
                  }
                }
              }
            ]
          }
        ]
      }
    },
    "last_updated": "2020-10-25T20:20:54.897Z"
  }
]

**Comment by phlax** [comment]
this is due to config being initially consumed as v2 and then upgrading

once https://github.com/envoyproxy/envoy/issues/16456 is resolved this should hopefully be fixed

we could resolve in the short term by adding `--bootstrap-version=3` although im wondering if this has already been fixed by https://github.com/envoyproxy/envoy/pull/16274 and we just need to update the docs

i can check...

**Comment by ankatare** [comment]
@phlax just wondering this resource type is also supported in latest docker image ? is this behaviour is correct if we don't see docs ... as per my understanding v2 is no longer supported, right ?

**Comment by phlax** [comment]
> as per my understanding v2 is no longer supported, right ?

no longer supported in the sense of being maintained etc - but scraping it out of the various bits of the codebase is an ongoing process

eg im currently working on removing it from the protos #https://github.com/envoyproxy/envoy/pull/16903

**Comment by ankatare** [comment]
@phlax Oh Ok. Got it. Thanks

**Comment by phlax** [comment]
checking this - it seems like its still an issue:

```json
[
  {
    "cluster": {
      "@type": "type.googleapis.com/envoy.api.v2.Cluster",
      "name": "xds_cluster",
      "type": "STRICT_DNS",
      "load_assignment": {
        "cluster_name": "xds_cluster",
        "endpoints": [
          {
            "lb_endpoints": [
              {
                "endpoint": {
                  "address": {
                    "socket_address": {
                      "address": "go-control-plane",
                      "port_value": 18000
                    }
                  }
                }
              }
            ]
          }
        ]
      },
]
```

**Comment by ankatare** [comment]
Ok.
