### ISSUE TITLE
scoped routes: Derive keys from dynamic request metadata

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#16945]
### Extend the route scope key builder to consider filter metadata

Currently the scope_key_builder's [fragments](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-scopedroutes-scopekeybuilder-fragmentbuilder) only support extracting values from headers. For use-cases in multi-tenant meshes where the tenants have no idea about the route scope abstraction, this is not enough.

I'd like to extend this to also include the [dynamic request metadata](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.html?#metadata-and-filter-state) propagated through the filter chain. If my understanding is correct, it would allow for more advanced tenant derivation in the filter chain without needing tenants to identify themselves via headers.

If this is a welcome change, I'm happy to submit the patch shortly.

*Relevant Links*
* https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing.html?#route-scope

**Comment by zuercher** [comment]
cc @htuch

**Comment by htuch** [comment]
Sure, this makes sense.

**Comment by tonya11en** [comment]
this is still in review
