### ISSUE TITLE
Graphical presentation Of Dynamic Configuration (Control Plane)

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#16950]
*Title*: *Graphical presentation of feature "Dynamic Configuration (Control Plane)"*

*Description*:
>Similar to the way we have graphical presentation Of FrontProxy  
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy 

can we also have similar presentation for Dynamic Configuration (file system) and for Dynamic Configuration (Control Plane)

It gives better understanding for new users. 

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/dynamic-configuration-control-plane
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/dynamic-configuration-filesystem

**Comment by alyssawilk** [comment]
It would definitely be nice to have, but I'm not sure anyone with understanding of the system has the cycles to do it :-/
cc @phlax
