### ISSUE TITLE
Is there any way to disable lua filter for particular service  or particular route 

### ISSUE THREAD

**Issue by rajneran7890** [envoyproxy/envoy#16970]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
I think this answers your question :-)

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#per-route-configuration
