### ISSUE TITLE
envoy.filters.http.ext_proc release date enquiry

### ISSUE THREAD

**Issue by mikirtn** [envoyproxy/envoy#16971]
***Title***: envoy.filters.http.ext_proc release date enquiry

***Description*:**
Hey everyone,
me and my team are eager to get http filter feature, and we didn't find any reference when it's going to get officially released,
the feature is External Processing Filter and may be referenced by the qualified name envoy.filters.http.ext_proc

**[optional *Relevant Links*:]**
Filter codebase: https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/ext_proc
Filter documentation: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3alpha/processing_mode.proto.html?highlight=ext_proc

any help would be much appreciated !

**Comment by alyssawilk** [comment]
cc @gbrail @snowp

**Comment by gbrail** [comment]
Implementation continues. Streaming body mode is in progress in https://github.com/envoyproxy/envoy/pull/17069, and another contributor is working on metadata support. Those are the two missing pieces to making the filter feature-complete, plus some smaller things like route-specific configuration. Work on writing fuzz tests is also happening.

After that I know that there is work required to move the filter from "alpha" to non-alpha status. This is my first real contribution to Envoy, and perhaps some of the others on this PR will have an idea what steps are necessary there.

**Comment by anatzadik** [comment]
Thanks Greg for you detailed response. 
Is there a rough estimation for when the filter will move to a non-alpha status?

**Comment by chet** [comment]
Hey @gbrail, thanks for the update! I was curious if the contributor you're referring to is also working on implementing `request_attributes` and `response_attributes`? I was considering beginning an effort on making those specific pieces work, but came across this Issue (which makes it look like there might already be some good progress). Let me know, thank you!

**Comment by liu0013** [comment]
Hey @gbrail could we add a flag to skip ext_proc service per request/response? that can avoid useless overhead if ext_proc service only handle some special headers, maybe requestA with the header, requestB without the header. so requestA's header will be sent to ext_proc service, requestB's header won't be sent to ext_proc service.

**Comment by pgeler** [comment]
@liu0013 we are using composite_filter, to my experience it does work well on 1.19.0 https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter

**Comment by gbrail** [comment]
"per-route" configuration is in the .proto but hasn't been implemented yet. As we are burning down other features I think that we can do that soon. I don't know as much about the details there, as I've been immersed in the guts of Envoy rather than the configuration, but I wonder if that would help?

**Comment by pgeler** [comment]
@gbrail +1 on per-route support

**Comment by liu0013** [comment]
Thanks @pgeler ! looks like composite_filter can help on my question right now.
