### ISSUE TITLE
Optimize admin stats memory use

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#16981]
*Title*: *Optimize admin stats memory use*

*Description*:

Prometheus admin stats handler cost too much memory as #16139(https://github.com/envoyproxy/envoy/issues/16591) said.

Now all serialized bytes are always buffered in the admin handler, then they may also be buffered in the networking layer for a slow client.

Details refer to [Google docs](https://docs.google.com/document/d/1k2wyZo1pGr8_jaxd7wfpPHctR47bhQgk8E5gFl1HJLU/edit?usp=sharing).

@jmarantz please take a look and add anything if I miss.

**Comment by jmarantz** [comment]
Any particular reason why we need both this Issue and the one referenced?

**Comment by daixiang0** [comment]
Just think it would be clear to track all memory related issues in stats field, and also it is a summary/proposal.

**Comment by daixiang0** [comment]
Update [link](https://docs.google.com/document/d/1k2wyZo1pGr8_jaxd7wfpPHctR47bhQgk8E5gFl1HJLU/edit?usp=sharing).

**Comment by daixiang0** [comment]
update

**Comment by jmarantz** [comment]
https://abseil.io/blog/20190812-btree indicates it's more cache-friendly and uses less memory.

Note that with just 1 iteration there's going to be some variance, so for the most part I'd consider most of the timings to be equivalent. It looks like when we construct larger pages (10k or 100k) then btree really wins. At lower page-sizes (100 or 1000) std::set is better. At 10k it's about a wash. I think more reps are needed to gain confidence.
