### ISSUE TITLE
benchmarking: add ability to trace Envoy code paths

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#16988]
benchmarking - add ability to trace Envoy code paths

*Description*:
It would be useful to be able to instrument Envoy code with tracing elements that time code execution in order to measure time spent in any given code path. The desired output would look similar to a flamegraph, but specific to codepaths that are instrumented.

This would allow developers to be more targeted in their benchmarking, and would enable timing deployments that don't have access to flamegraph or similar tools (e.g., inaccessible remote servers, mobile deployments via envoy mobile).

*Potential Implementation*:
Data Collection: data collection would happen with a RAII class similar to Scope Trackers that can create recursively nested scopes that time execution from creation to destruction. Further, implementing timing as a scope stack lends nicely to constructing rich timelines of code execution. This class could use the existing Timespan interface to produce timing measurements.

Data retrieval: a new extension similar to metrics sinks, or access loggers could be built in order to retrieve timing information.

*Relevant Links*
The desired instrumentation would be similar to that in https://github.com/tokio-rs/tracing. More research is required to see if there is an already existing similar library in C++, or if a simple custom solution as described above would suffice.

**Comment by mattklein123** [comment]
cc @rojkov @jmarantz for perf expertise.

**Comment by rojkov** [comment]
I'd probably go for Perfetto. It's used for performance instrumentation by Chrome developers. Supports [RAII-based track events](https://perfetto.dev/docs/instrumentation/track-events), integrates with system tracing, provides trace processors, visualizers...

I'll experiment with it.

**Comment by rojkov** [comment]
I played a bit with Perfetto. It may well be the tracer we want. Here's how the existing UI can show tracing data.

![last (2)](https://user-images.githubusercontent.com/33377/124295277-550a9680-db61-11eb-80a9-f80b0e82d701.png)

You can notice nested slices created with RAII objects and a couple of slices corresponding to objects' life spans - `ActiveTcpConnection` and `ActiveStream`. The latter are shown in separate child tracks (one child track per worker thread). For the selected duration the UI shows some predefined stats like total duration, average duration and occurrences. The stats can be customized with a tailored SQL query, e.g. the stats for the whole timeline and all concurrent threads:

![Screenshot (24)](https://user-images.githubusercontent.com/33377/124296523-bda64300-db62-11eb-8051-5ad552e3e667.png)

Here's the WIP patch: https://github.com/rojkov/envoy/pull/6/files

The tracing data in binary Protobuf format is dumped into `envoy.pftrace` upon process termination. But a custom interceptor can be hooked to transmit the data somewhere else (and to mix it with e.g. traced kernel syscalls).

The bad news is that Perfetto adds ~650K to Envoy binary. Also expect additional latency when a tracing session is active: https://perfetto.dev/docs/instrumentation/track-events#performance.

**Comment by jmarantz** [comment]
Cool; I assume we could add a bazel option to include this in the binary?

**Comment by rojkov** [comment]
Sure. The patch is just a quick and dirty hack. The final PR should have it pluggable the same way it's done for the perf annotations.

**Comment by mattklein123** [comment]
This looks amazing! +1 for a build option to enable this.
