### ISSUE TITLE
Option to auto dump active configuration and start Envoy with it

### ISSUE THREAD

**Issue by apolukhin** [envoyproxy/envoy#16987]
There may be cases when the xDS services go down and Envoy is restarted at the same time. In that case Envoy would wait for the xDS services to start, probably loosing the traffic.

A local dump of configuration would allow Envoy to start with latest configuration, without waiting for the xDS services.

*Relevant Links*:
Looks like this functionality was requested on stackoverflow too https://stackoverflow.com/questions/59444392/how-could-i-start-envoy-from-a-dumped-config-which-is-generated-by-config-dump

**Comment by mattklein123** [comment]
This is a request we have had periodically over the years. The reason we have pushed back on this is that if the control plane is down, scale up is broken anyway, so the control plane really needs to be considered a T0 component. One of handling this would be to use file based xDS and have a local daemon cache the config.

**Comment by apolukhin** [comment]
> use file based xDS and have a local daemon cache the config.

Yes, that would work. Hovewer such a caching daemon would be reinvented by each new xDS, which is not quite convenient.

Adding caching functionality to Envoy would remove the burden from users and lower the fault tolerance requirements for xDS.

**Comment by mattklein123** [comment]
It would also make Envoy itself more complicated. Perhaps we could host an OSS daemon that would do such a thing if you want to work on it?

**Comment by soulxu** [comment]
is it can be dumped by admin API https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/config_dump.proto#admin-v3-configdump? then you would have a daemon to dump the config(periodically, but may have stale config), then the envoy restart with the dump config.
