### ISSUE TITLE
Support for HTTP/1.0

### ISSUE THREAD

**Issue by enricoschiattarella** [envoyproxy/envoy#170]
Envoy responds to an HTTP/1.0 request with an upgrade request

```
GET / HTTP/1.0

HTTP/1.1 426 Upgrade Required
server: envoy
date: Mon, 24 Oct 2016 21:11:59 GMT
x-envoy-protocol-version: HTTP/1.1
content-length: 0

```

It would be nice to support 1.0 as there are some ancient clients out there.

**Comment by mattklein123** [comment]
I was hoping to avoid HTTP/1.0 support (not that it's hard, but just because). Is this a theoretical request or is HTTP/1.0 support blocking a real deployment?

**Comment by enricoschiattarella** [comment]
It is not blocking any deployment.
I discovered that it was missing while running some benchmarks with AB and thought that it might be useful to have when using Envoy as an edge.
No objections if you prefer to close the issue.

**Comment by mattklein123** [comment]
No let's keep it open to track in case this becomes a blocker for someone.

**Comment by lcapaldo** [comment]
I'm exploring the possibility of using envoy with a largish codebase that has a tendency to default to using http/1.0. It's not impossible to change all those uses, but one of the appeals of envoy to me in the first place is avoiding having to "touch all the code" to do those sorts of things. It would simplify my exploration greatly if envoy supported http/1.0.

**Comment by ihmccreery** [comment]
I'm considering using envoy as a replacement for [GoogleCloudPlatform/k8s-metadata-proxy](https://github.com/GoogleCloudPlatform/k8s-metadata-proxy); this is a blocking feature for that.

**Comment by htuch** [comment]
Some folks at Google have asked for this to act in a similar capacity to the GCE metadata server, that servers HTTP/1.0. Looking at `http-parser`, it seems this has HTTP/1.0 support. I think the scope of the work is adding support in https://github.com/envoyproxy/envoy/blob/master/source/common/http/http1/codec_impl.cc, updating tests, and plumbing through HTTP/1.0 in various places we plumb HTTP/1.1 config. My estimate would be a few days work max.

@mattklein123 WDYT?

**Comment by mattklein123** [comment]
I think it's more than a few days, but it's not that difficult. The main "complexity" is supporting the different Connection/Keep-Alive semantics between 1.0/1.1. I'm not sure that any changes to codec_impl.cc are required, possibly just removing the block in conn_manager_impl and dealing with the keep alive stuff. I'm sure @alyssawilk could do this within a week.

**Comment by moderation** [comment]
I'm not in favor of supporting 1.0. From a financial services and therefore heavily regulated point of view, 1.0 will be something that will need to be turned off. 1.0 is insecure and old.

**Comment by mattklein123** [comment]
> I'm not in favor of supporting 1.0. From a financial services and therefore heavily regulated point of view, 1.0 will be something that will need to be turned off. 1.0 is insecure and old.

I'm not sure I agree it's any more insecure than 1.1, but it is old, which is why I have had no interest in supporting it in the past. If we enable 1.0 we should do it behind a config option to allow people to keep it off if they want.

**Comment by ggreenway** [comment]
1.0 support should be harmless.  Is it even necessary to be able to disable it?  Every 1.1 client will negotiate http1.1.  So if 1.0 was disabled, the effect would either be rejecting those requests, or treating them as 1.1 (which would cause envoy and the client to disagree about whether the connection should be kept alive).  So is it worth adding the extra complexity (new config knob, additional tests for both modes) to allow disabling it?

I am going to need 1.0 support sometime in the next 3-6 months, to support a few legacy clients I can't get rid of.

**Comment by alyssawilk** [comment]
@htuch I think proper HTTP/1 support would take someone Envoy savvy O(month), otherwise probably about twice as long.

The logic for keep-alive and chunking are straight forward but non-trivial to get right, but there's a long tail of other differences which are technically required.  Do you know if said users mainly want framing and connection close?  There's a nice summary of differences here: http://www8.org/w8-papers/5c-protocols/key/key.html

I'd prefer to disable it by default if for no other reason than we can comment it as a "work in progress", do major features folks care about, and then add spec-abiding enhancements without config-protecting each iteration. I think if we commented the feature as "use at your own risk" we could probably get away with launch-and-iterate, where by Envoy guidelines we're not supposed to do user-affecting changes without config guarding.  @mattklein123 WDYT?

**Comment by htuch** [comment]
Yeah, I think there's some confusion on the scope here. We don't want full HTTP/1 keep-alive and chunked encoding I think. We want enough to emulate the GCE/GKE metadata server, which should be more constrained (this is just serving up some simple files and key:value pairs). That's why I suggested O(days).

**Comment by ggreenway** [comment]
@htuch do you need http1 on the upstream or downstream side for this?  Which bits will you end up implementing?

**Comment by mattklein123** [comment]
If we do HTTP/1.0 I would only do it for downstream connections. I don't agree that it would take 1 month+, since many of the things that are discussed in the document @alyssawilk points out Envoy doesn't deal with. I'm pretty sure an initial cut is literally:
1. Deciding if we want config guard or not in http_connection_manager
2. Removing HTTP/1.0 block in conn_manager_impl, potentially based on config.
3. Inverting keep-alive logic for 1.0 connections (require connection: keep-alive for keep alive otherwise assume close).

I'm sure there are other things that would come up but especially if we guard w/ config (and I think we should) we can launch and iterate.

**Comment by ggreenway** [comment]
I agree with only needing it on downstream side.  That's all I need, at least.

**Comment by alyssawilk** [comment]
+1 to downstream only for the first pass.  We always upgrade to HTTP/1 when forwarding upstream so that works for our* current and future needs.

*speaking as GFE and not Google - goodness only knows what everyone else is going to want in the long run ;-)

**Comment by ihmccreery** [comment]
FYI the GoogleCloudPlatform/k8s-metadata-proxy ship sailed.

**Comment by yudiandreanp** [comment]
It's blocking our deployment on the downstream side. 
As a workaround, we put an nginx in front of our envoyproxy for the specific services only (which still have HTTP1.0 clients).

Any updates on this?

**Comment by alyssawilk** [comment]
I believe I'll be taking this on for the Google use case.  I'll pick it up for now.  

I suspect the first pass will be having a default host, handling the inverted close logic and lack of chunking support -  I don't have the cycles to implement full standards compliance :-(     Hopefully once we have something bare bones, folks can pick up other features as needed to bring us closer in line with the spec.

**Comment by alyssawilk** [comment]
I encourage folks on this issue to turn this feature on and let me know how it goes.  If there's other corner cases in the spec you need supported I'm more likely to get them done while I have all the state mentally swapped in :-)

**Comment by jboeuf** [comment]
Thanks much @alyssawilk. I'll give it a shot and let you know.

**Comment by ramaraochavali** [comment]
@alyssawilk If we need to build this for upstream also like for example when `use_downstream_protocol `is set on the cluster and the incoming connection is http1.0, can we use same http1.0 for upstream? Is that feasible with current setup and code? How difficult it is to build?  I know you have decided not to build upstream and add additional complexity there - but just want to get your sense on level effort/difficulty and would this be an acceptable change?

**Comment by alyssawilk** [comment]
I think preserving HTTP/1.0 with use_downstream_protocol would be undesirable for most folks so I think you'd want to add an extra config knob to include http1.0.  If you have a business need to preserve this, it makes me sad but I'd totally give you the thumbs up and sign on for reviews.  

I think largely you'd have to
*) send the HTTP/1.0 string as the request version
*) make sure we don't chunk encode POST bodies
*) handle connection life time correctly (don't keep alive unless explicitly specified)

**Comment by ramaraochavali** [comment]
Thank you for the feedback.

>  If you have a business need to preserve this, it makes me sad but I'd totally give you the thumbs up and sign on for reviews.

We also want to avoid this as it unnecessary complexity in Envoy.  I will sure take your help if we ever needed to build this - but I hope we do not have to :-)

**Comment by ramaraochavali** [comment]
Sorry. I thought http1.1 does not allow a html form to be submitted with method as GET (thus allowing all the form parameters visible in the url) - But I was wrong. Http/1.1 still allows that but strongly discourages this use case (in favor of POST-based form submission).

Please ignore the above ^^

**Comment by thomas-gouder-ps** [comment]
Hi @mattklein123 @alyssawilk - are there any intentions to implement this for downstream connections? We're seeing Envoy reply with 404 errors when connecting to HTTP/1.0 servers (legacy infrastructure).

**Comment by thomas-gouder-ps** [comment]
> Hi @mattklein123 @alyssawilk - are there any intentions to implement this for downstream connections? We're seeing Envoy reply with 404 errors when connecting to HTTP/1.0 servers (legacy infrastructure).

Perhaps a secondary question - is there a way to exclude certain hosts from interception by envoy?

**Comment by alyssawilk** [comment]
sorry do you mean downstream (HTTP/1.0 from clients) or upstream (HTTP/1.0 from backends)?  you said downstream but "connecting to servers" which would be upstream.  We have downstream support (default off) and have no plans AFIK for upstream support (but would welcome additions if someone wants to implement it)

**Comment by thomas-gouder-ps** [comment]
Apologies, yes, upstream. I'll give it a shot.
