### ISSUE TITLE
ci build for docs giving -  ModuleNotFoundError: No module named 'pip'

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#17000]
*Title*: *ModuleNotFoundError: No module named 'pip' Error while running docs ci locally*

*Description*: Need help on fixing error as described below
 
>Describe the issue.

```console
$ ci/run_envoy_docker.sh 'ci/do_ci.sh docs'
No remote cache is set, skipping setup remote cache.
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=x86_64
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
HEAD is now at dfdc226 fix isterminal filter (#144)
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
building using 8 CPUs
building for x86_64
generating docs...
Traceback (most recent call last):
  File "/source/build_docs/venv/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

**Comment by phlax** [comment]
im not sure i understand why this would happen now - ie i dont think anything changed in the build image or docs build that would cause this

regardless, #15229 is about to land at which point `pip` wont be necessary at all

**Comment by ankatare** [comment]
humm. even i tried debugging it locally. not sure why it is hapening.   Would be great helpful if you help here !!!

**Comment by phlax** [comment]
are you using the most recent `envoy-build-ubuntu` image ?

**Comment by ankatare** [comment]
Yeah, it is latest cloned as  referred in  https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-ubuntu-linux

**Comment by phlax** [comment]
hmm - what im struggling to understand is that if you are running inside that container then that should be the same as in ci (i dont use that image so i cant test immediately)

**Comment by phlax** [comment]
what do you get for ?

```console
$ docker images | grep envoy-build-ubuntu
```

**Comment by ankatare** [comment]
ok. will get back ASAP

**Comment by ankatare** [comment]
@phlax see reults below

necuser@dldt-project_005:~/new_folder/envoy$ docker images | grep envoy-build-ubuntu
envoyproxy/envoy-build-ubuntu        55d9e4719d2bd0accce8f829b44dab70cd42112a   934ad7f43563   6 weeks ago     4.43GB
envoyproxy/envoy-build-ubuntu        d9b1f1cbb24b2cecca768feaa9fa3c6e6660a948   3e93399b8711   3 months ago    4.48GB
envoyproxy/envoy-build-ubuntu        19a268cfe3d12625380e7c61d2467c8779b58b56   6d037ae34f91   7 months ago    3.83GB
envoyproxy/envoy-build-ubuntu        b480535e8423b5fd7c102fd30c92f4785519e33a   7757d8081892   8 months ago    3.8GB
envoyproxy/envoy-build-ubuntu        e7ea4e81bbd5028abb9d3a2f2c0afe063d9b62c0   dcfae9a9d797   9 months ago    3.79GB
envoyproxy/envoy-build-ubuntu        f741613fc395cc489a630122eeb5e611b3cb1a5e   48a44a656769   10 months ago   3.77GB
envoyproxy/envoy-build-ubuntu        923df85a4ba7f30dcd0cb6b0c6d8d604f0e20f48   b11658dea8fb   11 months ago   3.69GB
envoyproxy/envoy-build-ubuntu        04f06115b6ee7cfea74930353fb47a41149cbec3   4681bdbc2d12   13 months ago   3.58GB

also
necuser@dldt-project_005:~/new_folder/envoy$ envoy --version

envoy  version: 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/clean-getenvoy-b76c773-envoy/RELEASE/BoringSSL

**Comment by phlax** [comment]
i think i see the problem

the `run_envoy_docker` mounts your local build directory into the image - including the virtualenv used to create the docs

my guess is that the virtualenv has been created historically and is not working with the default python inside the image

i think either you need to remove the virtualenv and let it be recreated - or wait a few days until i have removed this code

**Comment by ankatare** [comment]
@phlax Ok. Thanks for help. let me check this  as well.

**Comment by phlax** [comment]
@ankatare closing this as its no longer required to have pip/venv - requirements are now handled by bazel (since #15229 landed)
