### ISSUE TITLE
Question: How to embed XDS client in Envoy

### ISSUE THREAD

**Issue by conqerAtapple** [envoyproxy/envoy#17012]
*Title*: *How to embed XDS client in Envoy*

*Description*:
We are currently exploring possibilities of a file system based configuration reader which does the following:
- Reads any updates to configuration from a  file/directory 
- Translates the configuration changes (whole or delta) to XDS
- Speaks XDS to Envoy's XDS listener.

How can we achieve this within Envoy? One possibility is to launch a new thread for this which can setup a listener for file system. But this would be intrusive and change the threading model.

**Comment by mattklein123** [comment]
Couldn't you just use file based xDS and have some other process write the config out?

**Comment by conqerAtapple** [comment]
> Couldn't you just use file based xDS and have some other process write the config out?

Absolutely makes sense to have another process write the xDS config.  We were exploring if the client/user could be saved from writing the error prone configurations and let the translator do that. But i think this idea might bring in other issues. 
Thanks for the answer.
