### ISSUE TITLE
The QUIC causes the process to crash

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#17034]
![image](https://user-images.githubusercontent.com/48784730/122548390-de9b6e00-d063-11eb-84e0-c8dade325fd5.png)
envoy：v1.17.0
![image](https://user-images.githubusercontent.com/48784730/122548457-f7a41f00-d063-11eb-8f7f-30c33f3f6540.png)

**Comment by alyssawilk** [comment]
sorry can you give a bit more detail?  Were you running with one of the sample configs and standard traffic?

**Comment by liuqi-sun** [comment]
> sorry can you give a bit more detail? Were you running with one of the sample configs and standard traffic?
Does v1.17.0 support QUIC？

**Comment by liuqi-sun** [comment]
# An example config which accepts HTTP/1 requests over TCP and forwards them to google using HTTP/3
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
#                  host_rewrite_literal: www.google.com
                  cluster: service_google
#                  cluster: inbound|80||
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: inbound|80||
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80

  - name: service_google
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
#                address: www.google.com
                address: 192.168.71.134
#                port_value: 443
                port_value: 6121
#    typed_extension_protocol_options:
#      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
#        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
#        explicit_http_config:
#          http3_protocol_options: {}
#        common_http_protocol_options:
#          idle_timeout: 1s
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
#          sni: www.google.com
          sni: 192.168.71.134


client request： sudo curl 127.0.0.1:10000/
curl: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by curl)
curl: (52) Empty reply from server

**Comment by liuqi-sun** [comment]
`# An example config which accepts HTTP/1 requests over TCP and forwards them to google using HTTP/3
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
#                  host_rewrite_literal: www.google.com
                  cluster: service_google
#                  cluster: inbound|80||
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: inbound|80||
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80

  - name: service_google
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
#                address: www.google.com
                address: 192.168.71.134
#                port_value: 443
                port_value: 6121
#    typed_extension_protocol_options:
#      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
#        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
#        explicit_http_config:
#          http3_protocol_options: {}
#        common_http_protocol_options:
#          idle_timeout: 1s
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
#          sni: www.google.com
          sni: 192.168.71.134
`

client request：sudo curl 127.0.0.1:10000/
curl: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by curl)
curl: (52) Empty reply from server

**Comment by liuqi-sun** [comment]
**# An example config which accepts HTTP/1 requests over TCP and forwards them to google using HTTP/3
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
#                  host_rewrite_literal: www.google.com
                  cluster: service_google
#                  cluster: inbound|80||
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: inbound|80||
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80

  - name: service_google
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
#                address: www.google.com
                address: 192.168.71.134
#                port_value: 443
                port_value: 6121
#    typed_extension_protocol_options:
#      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
#        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
#        explicit_http_config:
#          http3_protocol_options: {}
#        common_http_protocol_options:
#          idle_timeout: 1s
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
#          sni: www.google.com
          sni: 192.168.71.134
**

**Comment by liuqi-sun** [comment]
`# An example config which accepts HTTP/1 requests over TCP and forwards them to google using HTTP/3
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
#                  host_rewrite_literal: www.google.com
                  cluster: service_google
#                  cluster: inbound|80||
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: inbound|80||
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80

  - name: service_google
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
#                address: www.google.com
                address: 192.168.71.134
#                port_value: 443
                port_value: 6121
#    typed_extension_protocol_options:
#      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
#        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
#        explicit_http_config:
#          http3_protocol_options: {}
#        common_http_protocol_options:
#          idle_timeout: 1s
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
#          sni: www.google.com
          sni: 192.168.71.134
`

**Comment by liuqi-sun** [comment]
# An example config which accepts HTTP/1 requests over TCP and forwards them to google using HTTP/3
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_google
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: inbound|80||
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80

  - name: service_google
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.71.134
                port_value: 6121
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
          sni: 192.168.71.134

**Comment by liuqi-sun** [comment]
> sorry can you give a bit more detail? Were you running with one of the sample configs and standard traffic?

client request：sudo curl 127.0.0.1:10000/
curl: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by curl)
curl: (52) Empty reply from server

**Comment by liuqi-sun** [comment]
![image](https://user-images.githubusercontent.com/48784730/122860178-de46ef80-d34f-11eb-93b7-75dc014cbd1e.png)
![image](https://user-images.githubusercontent.com/48784730/122860199-e6069400-d34f-11eb-892e-8b6699067046.png)

**Comment by alyssawilk** [comment]
I don't think QUIC went alpha until after the release was cut.  I can't reproduce at HEAD so please try with that.

**Comment by liuqi-sun** [comment]
> I don't think QUIC went alpha until after the release was cut. I can't reproduce at HEAD so please try with that.

sorry. I don't understand what you're saying. I use envoy v1.17.0, Does v1.17.0 support QUIC？

**Comment by alyssawilk** [comment]
It does not, sorry

**Comment by liuqi-sun** [comment]
> It does not, sorry

Do I need to use the latest version?

**Comment by liuqi-sun** [comment]
> It does not, sorry

Does v1.18.3 support QUIC？I failed to use Envoy v1.18.3.

**Comment by alyssawilk** [comment]
If you want to use QUIC please build from head, or use the nighly builds.  There is currently no release with QUIC support.
