### ISSUE TITLE
How to calculate sha256 digest of mesaage in lua filter

### ISSUE THREAD

**Issue by sumitaneja** [envoyproxy/envoy#17036]
Looking for way to calculate sha256 digest body, preferably reading body in chunks for large payloads. 
is there any optimized API available to calculate digest as part of lua filter with istio

**Comment by dio** [comment]
I think you can use the combination of https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#bodychunks and https://github.com/Egor-Skriptunoff/pure_lua_SHA. 

For each received body chunk (you can treat it as a string(?, probably requires it to be UTF-8)) and pass it to:

```lua
local append = sha.sha256()
append(chunk)
...

-- and finally
local your hash = append()
```
