### ISSUE TITLE
add support for drain and quit

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#17056]
We have drain listener support in admin interface. We would like to enhance that to drain and quit with additional request parameter `/drain_listeners?graceful&quit` - The usecase is when proxy is  terminated via SIGTERM we want to drain and quit.

**Comment by ramaraochavali** [comment]
@howardjohn FYI

**Comment by howardjohn** [comment]
One issue with this is if we have no connections and immediately terminate, then there may be races form new requests. What we probably want is "start draining and exit when there are no connections left, with a minimum time of X seconds".

We may also need to make sure we don't get stuck from connection to control plane, etc. I guess that would just be "downstream connections" which would handle that?

**Comment by ramaraochavali** [comment]
if we set https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-drain-strategy as immediate and quit after all existing connections are drained without waiting for full drain duration is that not sufficient? So basically what I am thinking is if we call '/drain_listeners?graceful&quit` with immediate drain-strategy - Envoy should quit after all connections are drained. 

@mattklein123 any recommendations? Basically we want the proxy to quit as soon as draining is done?

**Comment by howardjohn** [comment]
@ramaraochavali there is a still a small race if we do *just* that. Consider this timeline:
* at 0s: we trigger '/drain_listeners?graceful&quit`
* There are no connections open, we quit
* At 0.00001s a new connection is attempted to open. This fails since we quit.

If we can switch modes it would work as we want though:
* at 0s: we trigger '/drain_listeners?graceful` (NO quit)
* At 0.00001s a new connection is attempted to open. This works fine, but gets told to `connection:close`
* 5s later, hopefully we stop getting new connections. Call '/drain_listeners?graceful&quit`
* Once all existing connections are done we exit
* If not, after some other deadline (maybe terminationGracePeriod for pod?) we hard exit

The exact sequence and timings is obviously user-specific, but I think we would need to be able to transition from draining -> draining+quit mode.

**Comment by mattklein123** [comment]
I agree with @howardjohn that by itself there are race conditions. With that said, there is some amount of leeway here on how much of this functionality is built into Envoy vs. assuming that an external process manager sequences things in the right order. To keep things simple I would recommend trying to keep things simple on the Envoy side and documenting well. I have no objection to a feature where Envoy quits when there are no more active connections, though it will take some thinking to figure out how to implement (callback based, polling based, etc.).

**Comment by ramaraochavali** [comment]
> To keep things simple I would recommend trying to keep things simple on the Envoy side and documenting well. 

Are you suggesting, we sequence the whole flow in a process manager - I am fine with that. Only problem is how do we determine there are no active connections? I guess we have to look up bunch of stats to determine this from outside and exclude some like control plane connections/long running gRPC connections etc because we do not send proactive go-away on them when draining starts? or Any other better way?

**Comment by mattklein123** [comment]
I think my point is that there is a gradient of complexity. On one hand, I think this could be done today in Envoy using a process manager that polls stats as you say, after putting Envoy into HC fail and drain mode. An argument can be made that this is too difficult to do in a process manager and we can add more complexity into Envoy, all the way to having the entire process be driven by Envoy itself. I don't have a super strong opinion on where on this gradient we should land, I'm just pointing out that the design proposal should consider all the different implementation options.

**Comment by howardjohn** [comment]
Here is prior art in knative: https://github.com/knative/serving/blob/5af4e84d140f679c200fbfec617c13fe691c1711/cmd/queue/main.go#L239-L251 (this is strictly golang code, not envoy related).

So in this case they address the race condition by always sleeping for some time, then call Shutdown which does the drain+exit.

@mattklein123 totally agree on the complexity gradient. I think having Envoy do the "only exit after X seconds, even if no connections" part is not required. However, having Envoy exit when 0 connections can likely be more efficient than process manager, with the assumption that Envoy knows better when it has 0 connections than the process manager (not sure how true that is).

So my personal preference would be for Envoy to just implement `'/drain_listeners?graceful&quit` and leave the race condition mitigate to process manager.

**Comment by ramaraochavali** [comment]
I think we can make use of this` openConnections()` method on listener to check if open connections across all listeners and when it becomes zero we can quit.

Couple of questions
- Is poll mechanism OK in the admin handler that periodically (every few ms) and quits envoy if it is zero?
- It still does not handle long running gRPC connections?

@mattklein123 WDYT? If that is acceptable we can implement '/drain_listeners?graceful&quit' in envoy?

**Comment by mattklein123** [comment]
IMO polling is OK for the first cut, though I would do something more like 1-5s for the poll.

You are right that this won't handle long lived connections, but that is a much larger problem related to drain in general, in the sense that we only do "passive" draining. We don't do "active" draining for existing requests. My advice would be to tackle that as a potential follow on item. See also https://github.com/envoyproxy/envoy/pull/16201 which would be a good step towards fixing the 2nd issue. cc @murray-stripe

**Comment by ramaraochavali** [comment]
Ok. Makes sense. Let me work in this

**Comment by kyessenov** [comment]
A simple hack would be to return the number of draining listeners for `/drain` endpoint. Since it doesn't do any work once drain starts, we can poll and wait for it to become zero in the agent.

**Comment by ramaraochavali** [comment]
Closing this as we have implemented this in Istio using active connections.

**Comment by joshuaswickirl** [comment]
https://github.com/istio/istio/issues/34855
