### ISSUE TITLE
Does Envoy do external requests to get info

### ISSUE THREAD

**Issue by quenenni** [envoyproxy/envoy#17054]
Hello,

I would like to know if Envoy proxy needs to query the structure of a type or a schema to an external server?
From https://github.com/envoyproxy/envoy/blob/main/examples/redis/envoy.yaml
```
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
```
From this, does Envoy need to query type.googleapis.com to get infos it needs?
Or is it only an internal filter reference in Envoy?

If it indeed needs to query the googleapis address, when will it be? 
Only on installation, app update, service restart or ..

I wasn't able to find that info in the doc.
I read a blog about it, but I can say I understood that much (a bit too much over my head), and still don't know about external calls after reading it.
https://blog.envoyproxy.io/dynamic-extensibility-and-protocol-buffers-dcd0bf0b8801

Thank you.

**Comment by soulxu** [comment]
it won't query `type.googleapis.com`, it is just a URL of type `type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy`. Then the protobuf will know what type of message you want to unpack.

**Comment by quenenni** [comment]
@soulxu 

Perfect. 
Thank you for your help.
