### ISSUE TITLE
Question: Does cert reload via SDS trigger request draining?

### ISSUE THREAD

**Issue by shamsimam** [envoyproxy/envoy#17073]
*Title*: Does cert reload via SDS trigger request draining and GoAway frames on HTTP/2 requests?

*Description*:

We have Jetty http/2 downstream clients that make gRPC requests to an upstream backend via Envoy. We are currently using Envoy hot-reloads to trigger picking up new certificates managed in a [CommonTlsContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-commontlscontext) without dropping traffic. However, we are running into issues where after triggering a hot-reload of Envoy (for certificate refresh), the next http/2 request occasionally receives a GoAway frame (because the connection is being reused). The Jetty client does not handle this well and fails the gRPC request as it deems the GoAway frame to be an error (separate discussion whether the client is doing the right thing). We have attributed this behavior of Envoy to [draining of requests as the Envoy instance is being hot restarted](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining).

An alternate to hot-restart is to use [SDS to reload the new certificate](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#config-secret-discovery-service) and this does not trigger a hot restart. The Envoy documentation on [draining](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining) does not list SDS cert reload as a scenario when requests will be drained. I wanted to confirm that switching to using SDS will not cause requests from our Jetty client to receive the GoAway frame after a reload of the certificate.

Can someone help confirm that this is the case?

**Comment by htuch** [comment]
Correct, SDS does not drain, it jsut updates the certificates for the next handshake.
