### ISSUE TITLE
 x-b3-sampled header always set to 1 in ext_authz request

### ISSUE THREAD

**Issue by mmayeda** [envoyproxy/envoy#17085]
The ext_authz envoy filter seems to always use an x-b3-sampled header value of 1 even after setting the`HttpConnectionManager.tracing.random_sampling` to a value of 0.0.  Is there some global sampling configuration being used by the filter that I was unable to find in the docs or is this unexpected behavior? 

Incoming requests do not have the `x-client-trace-id`, `x-envoy-force-trace`, or `x-b3-sampled` headers set and outgoing requests to other services (not including the ext_authz filter request) in the envoy mesh are abiding by the `HttpConnectionManager.tracing.random_sampling` setting.

**Comment by alyssawilk** [comment]
quick question - what makes you think this is ext_authz?  a quick grep of the code has both opencensus and zipkin tracers adding this header but I don't see ext_authz doing so in the Envoy code base?

**Comment by mmayeda** [comment]
Sorry I didn't mean to imply that the ext_authz code was responsible for setting the x-b3-sampled header, just that the header is always set to 1 in the external auth filter request even though the other routed requests abide by the `HttpConnectionManager.tracing.random_sampling` setting

**Comment by mmayeda** [comment]
@alyssawilk Do you know if this is expected behavior or potentially a bug?

**Comment by alyssawilk** [comment]
oh, I was hoping for a quick "fix" if you thought it was ext authz.  It looks like the only places Envoy sets the trace if headers are in the opencensus tracer and the zipkin tracer.  I assume you're using one of those?

**Comment by mmayeda** [comment]
Yes, I'm using the zipkin tracer

**Comment by mmayeda** [comment]
@alyssawilk  After taking a look at the code I do believe ext_authz is responsible for the header always being set to 1.   The header is set if the zipkin span object's sampled variable is true.  The zipkin span's sampled variable is assigned what is in the request options [here](https://github.com/envoyproxy/envoy/blob/b62dae29a5dd06b7f689899b26974d9567a98f0e/source/common/http/async_client_impl.cc#L262), and the request [options](https://github.com/envoyproxy/envoy/blob/b62dae29a5dd06b7f689899b26974d9567a98f0e/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L248) passed to the async client by ext_authz always have the default sampled value of true.

**Comment by jn1z** [comment]
We've encountered this issue as well. Is there a solution or a workaround for this behavior?

**Comment by yanavlasov** [comment]
This is open source project with volunteer contributions. There is no escalation. If you have resource to fix the problem this may the best course of action.

**Comment by chrisxrepo** [comment]
@mmayeda can you give me a example config for the inssue?

**Comment by esmet** [comment]
> @alyssawilk After taking a look at the code I do believe ext_authz is responsible for the header always being set to 1. The header is set if the zipkin span object's sampled variable is true. The zipkin span's sampled variable is assigned what is in the request options [here](https://github.com/envoyproxy/envoy/blob/b62dae29a5dd06b7f689899b26974d9567a98f0e/source/common/http/async_client_impl.cc#L262), and the request [options](https://github.com/envoyproxy/envoy/blob/b62dae29a5dd06b7f689899b26974d9567a98f0e/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L248) passed to the async client by ext_authz always have the default sampled value of true.

I looked at this and I think I agree.

If true, then we probably have this issue in the ratelimit filter as well as the lua, jwks, and oauth filters.

**Comment by esmet** [comment]
Friendly ping for more opinions on this @alyssawilk / @kyessenov

**Comment by alyssawilk** [comment]
thanks for looking at this @esmet and sorry for lag.
Yeah I like the idea of both inheriting by default and actually setting the shadow traces based on config.  Per your patch, I wonder if there's a need to keep sampled_ if we retain sampled_preference_? Not sure if there's a need for both or you just hadn't cleaned it up.  Also I think we'll want to runtime guard as this results in data plane changes, but that should hopefully be easy to tweak

**Comment by esmet** [comment]
Great, I'll prepare a real PR Soon ™️ and then we can work out those details.

**Comment by kyessenov** [comment]
The context for my change to set sampled was that mirrored requests are also using the async client, and these requests would copy the original request tracing header which confuses the tracing system. I think it's fair to make the choice of whether to sample / trace auxiliary requests configurable. My main concern is that this is pervasive in other places in envoy, so we might need some common xDS API to govern them all (a subset of HCM, perhaps, and maybe, placed into gRPC/HTTP cluster reference).

**Comment by carolinestere** [comment]
Hello! Any news on this issue? I saw that @esmet opened a PR [async_client: add trace sampling preference](https://github.com/envoyproxy/envoy/pull/18261), but it got closed due to inactivity.

**Comment by carolinestere** [comment]
I was thinking of opening a PR with the following changes:

```
diff --git a/source/common/http/async_client_impl.cc b/source/common/http/async_client_impl.cc
index 2c1da999f2..fb23594ba9 100644
--- a/source/common/http/async_client_impl.cc
+++ b/source/common/http/async_client_impl.cc
@@ -256,7 +256,9 @@ AsyncRequestImpl::AsyncRequestImpl(RequestMessagePtr&& request, AsyncClientImpl&
   } else {
     child_span_ = std::make_unique<Tracing::NullSpan>();
   }
-  child_span_->setSampled(options.sampled_);
+  if (options.sampled_) {
+    child_span_->setSampled(options.sampled_);
+  }
 }
 
 void AsyncRequestImpl::initialize() {
diff --git a/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc b/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
index 6ea6343968..f15bf3cc21 100644
--- a/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
+++ b/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
@@ -279,7 +279,8 @@ void RawHttpClientImpl::check(RequestCallbacks& callbacks,
     auto options = Http::AsyncClient::RequestOptions()
                        .setTimeout(config_->timeout())
                        .setParentSpan(parent_span)
-                       .setChildSpanName(config_->tracingName());
+                       .setChildSpanName(config_->tracingName())
+                       .setSampled(false);
 
     request_ = thread_local_cluster->httpAsyncClient().send(std::move(message), *this, options);
   }
```

Does it make sense?

**Comment by carolinestere** [comment]
@alyssawilk @esmet @kyessenov I opened a [PR](https://github.com/envoyproxy/envoy/pull/19343) that fixes this issue, could you please take a look when you've got time?
