### ISSUE TITLE
TCP connect only health check for SSH application

### ISSUE THREAD

**Issue by amitkatyal** [envoyproxy/envoy#17099]
TCP health checks are connect-only, if "send" is an empty payload as per the envoy documentation.
{
  "send": "{...}",
  "receive": []
}

For ports 80 & 443, we confirmed that the envoy is stopping the health check immediately after the three-way handshake. 
However, for the SSH application, we observed that the envoy proxy is trying to create an SSH connection & since the server is not allowing the SSH connection w/o credentials, the envoy is reporting a health check failure.

Please confirm if this is expected behavior and share the TCP-based health check details for other protocols (for example, RDP, CIFS...etc).

**Comment by alyssawilk** [comment]
Not my area, but I would expect that if you can't do a TLS connection to a TLS upstream that the health check would fail.

**Comment by amitkatyal** [comment]
Thanks, @alyssawilk,
It is not doing TLS. Please find below the health check capture dump.

![image](https://user-images.githubusercontent.com/42130809/123118661-7633fe80-d460-11eb-855b-7a11dbdf450d.png)

**Comment by alyssawilk** [comment]
apologies, somehow misread ssh as ssl.
"we observed that the envoy proxy is trying to create an SSH connection"
I don't recall Envoy having SSH functionality.  Is this a trace of envoy at *.193 doing a health check to an scp server at .215?  What payload is it sending?

**Comment by amitkatyal** [comment]
Yes, attached is the TCP capture of the envoy doing the health check at 10.194.194.193:22.
We have configured TCP health check every 60 seconds and the same can be confirmed from the TCP capture.

For TCP port 80, the envoy is only doing the three-way handshake. Please find below the TCP dump.
![image](https://user-images.githubusercontent.com/42130809/123130499-6e795780-d46a-11eb-94d0-4d8acc906f74.png)

**Comment by amitkatyal** [comment]
Any pointers would be of great help. Thanks
