### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#17101]
![image](https://user-images.githubusercontent.com/48784730/123091758-4e429c00-d45c-11eb-9a5f-3c50b1c3b119.png)
I google said it was a GCC bug. Please help me

**Comment by daixiang0** [comment]
please share env details(envoy version, clang/gcc version and so on)

**Comment by liuqi-sun** [comment]
> please share env details(envoy version, clang/gcc version and so on)

![image](https://user-images.githubusercontent.com/48784730/123196989-6eff0600-d4dd-11eb-9c07-fea85abd5c30.png)
envoy main branch，The latest version
bazel build -c opt //source/exe:envoy-static --jobs 4
