### ISSUE TITLE
Unable to build arm64 binaries (segfault during v8 bytecode_builtins_list_generator)

### ISSUE THREAD

**Issue by timonwong** [envoyproxy/envoy#17100]
Hello, 
I'm encountering a strange error when building arm64(aarch64) binaries (It's worked for amd64 build though):

Using following command from https://github.com/envoyproxy/envoy/tree/main/ci#on-linux:
```
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
```

And during wee8 building, there is a strange error:

[130/1236] CXX obj/third_party/inspector_protocol/crdtp/cbor.o
[131/1236] LINK ./bytecode_builtins_list_generator
[132/1236] ACTION //:generate_bytecode_builtins_list(//build/toolchain/linux/unbundle:default)
FAILED: gen/builtins-generated/bytecodes-builtins-list.h
**python ../../tools/run.py ./bytecode_builtins_list_generator gen/builtins-generated/bytecodes-builtins-list.h
Return code is -11**
[133/1236] CXX obj/src/inspector/inspector/Console.o
[134/1236] CXX obj/third_party/inspector_protocol/crdtp/dispatch.o
[135/1236] CXX obj/src/inspector/inspector/Profiler.o
[136/1236] CXX obj/src/inspector/inspector/Schema.o
[137/1236] CXX obj/src/inspector/inspector/HeapProfiler.o
[138/1236] CXX obj/torque_base/implementation-visitor.o
[139/1236] CXX obj/src/inspector/inspector/Debugger.o
[140/1236] CXX obj/src/inspector/inspector/Runtime.o

Which is a segmentation fault without any additional messages.

Envoy Branch: release/v1.18

Machine Information:
AWS Graviton: c6g.2xlarge

**Comment by maikoulin** [comment]
I have encountered this problem, have you solved it?

**Comment by timonwong** [comment]
> I have encountered this problem, have you solved it?

Nope, it's still segement fault...

**Comment by moderation** [comment]
I'm building on aarch64 Linux on a Raspberry Pi and MacOS M1. I don't use Docker to build and I compile out a bunch of functionality I don't need include the WASM support that causes your segfault. From my ~/.bazelrc

`build --define wasm=disabled`

More info at https://github.com/envoyproxy/envoy/tree/main/bazel#enabling-and-disabling-extensions

This doesn't fix the segfault and is a work around however this approach will unblock you if you don't require WASM filters

**Comment by timonwong** [comment]
@moderation thanks, I did have success building without any wasm support for arm64 builds. But we are looking for build with wasm support...

The last update is I have successfully built wee8 under huaweicloud Kunpeng. (still cannot build with AWS Graviton, very strange...)

**Comment by moderation** [comment]
Any ideas for WASM support for aarch64 @lizan @PiotrSikora @mathetake ?

**Comment by PiotrSikora** [comment]
It builds and passes all the tests on the CI on Linux-aarch64, so I have no idea what could be the issue. Perhaps too little memory on RPi?

You could try building from https://github.com/envoyproxy/envoy/pull/19275. Maybe that will work, or at least provide a more helpful error.

**Comment by timonwong** [comment]
@PiotrSikora 
I think it's not a build system issue, maybe some hardware or host machine operating system related problem:
I just copied the `bytecode_builtins_list_generator` binary to the environment which fails, it still gives me SIGSEGV even without giving any command line arguments.

It should:
```
# ./bytecode_builtins_list_generator
Usage: ./bytecode_builtins_list_generator <output filename>
```

However it produces:
```
# ./bytecode_builtins_list_generator
Segmentation fault
```

**Comment by timonwong** [comment]
It's interesting that on machine that's ok running ldd gives me:

```
# ldd ./bytecode_builtins_list_generator
        linux-vdso.so.1 (0x0000ffff9f401000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff9f352000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff9f1be000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff9f19a000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff9f041000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff9f3d5000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff9ef88000)
```

However on break one:

```
# ldd ./bytecode_builtins_list_generator
not a dynamic executable
```

**Comment by PiotrSikora** [comment]
@timonwong thanks for investigating!

> I think it's not a build system issue, maybe some hardware or host machine operating system related problem:

It's not only about the build system, but those builds are quite different in terms of compiler flags, etc., so you never know.

Could you see if debug build helps? Perhaps run `./bytecode_builtins_list_generator` under `gdb`?

On the `main` branch:
```
$ bazel build -c dbg @com_googlesource_chromium_v8//:build
```

In #19275:
```
$ bazel build -c dbg @v8//:wee8
```

**Comment by timonwong** [comment]
@PiotrSikora 

> Could you see if debug build helps? Perhaps run `./bytecode_builtins_list_generator` under `gdb`?

gdb does not help much, the bytecode_builtins_list_generator crash during startup, even before loading any :

```
gdb bytecode_builtins_list_generator -batch -ex 'set disable-randomization off' -ex 'catch throw' -ex 'catch signal SIGSEGV' -ex 'break main' -ex 'run gen/builtins-generated/bytecodes-builtins-list.h'

warning: Could not find DWO CU obj/bytecode_builtins_list_generator/generate-bytecodes-builtins-list.dwo(0x755ec394d72caf7b) referenced by CU at offset 0x0 [in module /workspace/bytecode_builtins_list_generator]
Catchpoint 1 (throw)
Catchpoint 2 (signal SIGSEGV)
Breakpoint 3 at 0x3ccec: file ../../src/builtins/generate-bytecodes-builtins-list.cc, line 110.
During startup program terminated with signal SIGSEGV, Segmentation fault.
```

What is more interesting is, after I compile the `bytecode_builtins_list_generator` using g++, it just works... 

The build ⌘:
```bash
buildtools/linux-arm64/gn gen out/wee8 '--args= is_debug=true v8_symbol_level=2 v8_optimized_debug=false is_clang=false custom_toolchain="//build/toolchain/linux/unbundle:default" use_custom_libcxx=false use_custom_libcxx_for_host=true use_sysroot=false use_glib=false v8_expose_symbols=true is_component_build=false v8_enable_i18n_support=false v8_enable_gdbjit=false v8_use_external_startup_data=false v8_enable_shared_ro_heap=false target_cpu="arm64"'

# Just build the bytecode_builtins_list_generator binary
ningja -C out/wee8 bytecode_builtins_list_generator
```

**Comment by timonwong** [comment]
Maybe it's a PAGESIZE issue?

on good host machine (debian/ubuntu):
```
getconf PAGESIZE # 4096
```

on problem host machine (CentOS/RHEL):
```
getconf PAGESIZE # 65536
```

Some issues maybe related after searching:
- https://github.com/electron/electron/issues/25387
- https://github.com/electron/electron/issues/21395
- https://github.com/microsoft/vscode/issues/108509

**Comment by timonwong** [comment]
The sections headers from the generated binary (using llvm+clang):

```
 Program Headers:
   Type           Offset             VirtAddr           PhysAddr
                  FileSiz            MemSiz              Flags  Align
   PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                  0x0000000000000268 0x0000000000000268  R      0x8
   INTERP         0x00000000000002a8 0x00000000000002a8 0x00000000000002a8
                  0x000000000000001b 0x000000000000001b  R      0x1
       [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
   LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                  0x000000000001da4c 0x000000000001da4c  R      0x1000
   LOAD           0x000000000001da50 0x000000000001ea50 0x000000000001ea50
                  0x000000000000b750 0x000000000000b750  R E    0x1000
   LOAD           0x00000000000291a0 0x000000000002b1a0 0x000000000002b1a0
                  0x00000000000027c8 0x00000000000027c8  RW     0x1000
   LOAD           0x000000000002b968 0x000000000002e968 0x000000000002e968
                  0x0000000000000018 0x00000000000000f0  RW     0x1000
   DYNAMIC        0x000000000002b2e8 0x000000000002d2e8 0x000000000002d2e8
                  0x00000000000001f0 0x00000000000001f0  RW     0x8
   GNU_RELRO      0x00000000000291a0 0x000000000002b1a0 0x000000000002b1a0
                  0x00000000000027c8 0x0000000000002e60  R      0x1
   GNU_EH_FRAME   0x000000000001beac 0x000000000001beac 0x000000000001beac
                  0x00000000000005bc 0x00000000000005bc  R      0x4
   GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                  0x0000000000000000 0x0000000000000000  RW     0x0
   NOTE           0x00000000000002c4 0x00000000000002c4 0x00000000000002c4
                  0x0000000000000038 0x0000000000000038  R      0x4
```

Generated `(PT_)LOAD` overlaps for 64k page size:
PT_LOAD (RE)  0x1ea50 + 0x0b750 = 0x2a1a0
PT_LOAD (RW) Starts at 0x2b1a0. (0x2a1a0 - 0x2a1a0) = 4096 which is just 4k and overlaps with 64k page with different purpurse (execute & write).

However, for gcc builds:

```
   LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                  0x000000000002d738 0x000000000002d738  R E    0x10000
   LOAD           0x000000000002d920 0x000000000003d920 0x000000000003d920
                  0x00000000000026f8 0x00000000000027d8  RW     0x10000
```

As you can see, PT_LOAD(RW) - PT_LOAD(RE) = 66024 > 64k.

So it's ok for gcc builds...

**Comment by timonwong** [comment]
It's basically caused by the gn (or ninja) add `max-page-size=4096' to the linker options:

```
[53/53] python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./bytecode_builtins_list_generator" -- clang++ -pie -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=4096 -Wl,--icf=all -Wl,--color-diagnostics -Wl,--no-call-graph-profile-sort --target=aarch64-linux-gnu -no-canonical-prefixes -Werror -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,-O2 -Wl,--gc-sections -o "./bytecode_builtins_list_generator" -Wl,--start-group @"./bytecode_builtins_list_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt
```

Maybe switching to bazel will solve this problem, I'll try it later in a few days.
