### ISSUE TITLE
How do i install envoy 1.16.4 ?

### ISSUE THREAD

**Issue by ashwinkupatkar** [envoyproxy/envoy#17115]
>> yum whatprovides getenvoy-envoy                         

```
getenvoy-envoy-1.14.5.p0.gfa0371e-1p69.ga5345f6.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.15.0.p0.g50ef094-1p67.g2aa564b.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.15.1.p0.g670a4a6-1p69.ga5345f6.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.16.0.p0.g8fb3cb8-1p69.ga5345f6.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.16.2.p0.ge98e41a-1p71.gbe6132a.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.17.0.p0.g5c801b2-1p71.gbe6132a.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.17.0.p0.g5c801b2-1p72.g28ef262.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.17.1.p0.gd6a4496-1p74.gbb8060d.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable



getenvoy-envoy-1.18.2.p0.gd362e79-1p75.g76c310e.x86_64 : Certified, Compliant and Conformant Builds of Envoy
Repo        : tetrate-getenvoy-stable
```

gives me above result. How can i install envoy-1.16.4 ? Any leads on this issue ?

**Comment by alyssawilk** [comment]
cc @phlax in case this relates to your packaging work?

**Comment by ashwinkupatkar** [comment]
I need package version 1.16.4 but i am unable to get it when i query tetrate-getenvoy repo.

I even checked the nightly builds contents. Did not find it.

**Comment by phlax** [comment]
not sure on the current stage of getenvoy repos and available versions

we are in the process of creating host installable packages, but it may take a little time

you could probably extract the binary from the related docker build if necessary

**Comment by ashwinkupatkar** [comment]
Ok... I have a centos 7 vm to deploy this envoy binary. Which docker image as exact do you suggest to extract the binary ?

**Comment by phlax** [comment]
for v1.16.4 specifically see https://hub.docker.com/layers/envoyproxy/envoy/v1.16.4/images/sha256-45cc09f3e43c79a5133119d547acdc68aff629fdb3106c1d0646f46fe8dbbbc1?context=explore - should work in redhat also i think

**Comment by ashwinkupatkar** [comment]
Ok.. normally, I use amd64 . I think that will be good. Will try. Thanks @phlax. 

It will be really great if raw binaries are readily available. Will save lof of effort.
