### ISSUE TITLE
clang build error

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#17128]
![image](https://user-images.githubusercontent.com/48784730/123255989-06d31300-d523-11eb-936c-91c4b118bbd8.png)

![image](https://user-images.githubusercontent.com/48784730/123254265-076aaa00-d521-11eb-9794-117e194fbe3c.png)

 bazel build --config=clang -c opt //source/exe:envoy-static --define tcmalloc=gperftools --jobs 4
![image](https://user-images.githubusercontent.com/48784730/123254100-d38f8480-d520-11eb-830e-5dc598414100.png)

How to disable the ‘-fno-delete-null-pointer-checks’ parameter？

**Comment by qinggniq** [comment]
From my personal experience, I recommend you to keep the clang version same with the version which the ci uses, now is clang10.  The version of tools below you should take care about:
- python version (>=3.8), `google-api` package need to be installed
- go version (>=1.11), set GOPROXY property
- clang/clang++ version (>=10) 
- gcc/g++ version (I'm not sure, but at least 7.0)
- libc++ and libstdc++-7-dev (or higher)

And most important, follow with [Build Guide](https://github.com/envoyproxy/envoy/blob/main/bazel/README.md). Good luck.

**Comment by cfanbo** [comment]
me too.why?

**Comment by liuqi-sun** [comment]
> me too.why?
The clang version is too low，so not support -fno-delete-null-pointer-checks.
I cat not disable the ‘-fno-delete-null-pointer-checks’ parameter. so i use clang v12.
![image](https://user-images.githubusercontent.com/48784730/124533890-c2f6dc80-de45-11eb-8938-b4f5566546d9.png)
