### ISSUE TITLE
Ensure sandbox docs show correct git clone version for envoy repo

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#17126]
### description

Currently if you go to test the sandboxes with an historical version - the dependencies tell you to clone envoy at `main` `HEAD`

(eg see https://www.envoyproxy.io/docs/envoy/v1.18.3/start/sandboxes/setup#clone-the-envoy-repository)

Some of the examples in main wont work correctly with specific versions, so these docs should show to clone the specific version from the repo, and probably some info/warnings about ensuring that the envoy container you have is also correct/up-to-date/matching

**Comment by alyssawilk** [comment]
cc @phlax
