### ISSUE TITLE
Failed to use V1.18.3 QUIC

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#17125]
Two questions：
1、QuicUpstreamTransport is fail
The configuration file：google_com_http3_upstream_proxy.yaml
error：
lq@ubuntu:~/work/go/bin/quic-go/example/client$ sudo curl 192.168.71.135:10000/
curl: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by curl)
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: QUIC_NO_ERROR with details: Closed by application

2、QuicDownstreamTransport is fail
The configuration file：envoyproxy_io_proxy_http3_downstream.yaml
client：quic-go client
server：envoy

error：
./main -v -insecure https://192.168.71.130:10000
GET https://192.168.71.130:10000
failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Activating reading of ECN bits for IPv4 and IPv6.
Activating reading of packet info for IPv4 and IPv6.
client Starting new connection to 192.168.71.130 ([::]:41254 -> 192.168.71.130:10000), source connection ID (empty), destination connection ID fab75d188a3feebfdf12fd5db42c06db3732dcc2, version v1
muxer Adding connection ID (empty).
client Not doing 0-RTT.
client -> Sending packet 0 (1252 bytes) for connection fab75d188a3feebfdf12fd5db42c06db3732dcc2, Initial
client 	Long Header{Type: Initial, DestConnectionID: fab75d188a3feebfdf12fd5db42c06db3732dcc2, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0, PacketNumberLen: 2, Length: 1222, Version: v1}
client 	-> &wire.CryptoFrame{Offset: 0, Data length: 276, Offset + Data length: 276}
client Received a Version Negotiation packet. Supported Versions: [draft-29 0x54303531 0x51303530 gQUIC 46 0xca4a5ada gQUIC 43]
client Destroying session with error: no compatible QUIC version found (we support [v1], server offered [draft-29 0x54303531 0x51303530 gQUIC 46 0xca4a5ada gQUIC 43])
client No compatible QUIC version found.
muxer Removing connection ID (empty).
client Connection fab75d188a3feebfdf12fd5db42c06db3732dcc2 closed.
Get "https://192.168.71.130:10000": no compatible QUIC version found (we support [v1], server offered [draft-29 0x54303531 0x51303530 gQUIC 46 0xca4a5ada gQUIC 43])

It looks like the version is inconsistent. What version is Envoy Quic?

**Comment by alyssawilk** [comment]
If you want to use QUIC please build from head, or use the nighly builds.  There is currently no release with QUIC support.

**Comment by liuqi-sun** [comment]
> If you want to use QUIC please build from head, or use the nighly builds. There is currently no release with QUIC support.

I build from head,envoy version is 1.19.0-dev.
Version as follows:
./bazel-bin/source/exe/envoy-static  version: 5e248dc778b90dc26b6e3384b6c191018cbe7a8a/1.19.0-dev/Modified/DEBUG/BoringSSL

QuicupstreamTransport still fails.
The configuration file：google_com_http3_upstream_proxy.yaml
envoy log:
![image](https://user-images.githubusercontent.com/48784730/123406905-f92e9380-d5dd-11eb-8573-047956a30913.png)

curl response:
![image](https://user-images.githubusercontent.com/48784730/123406993-0fd4ea80-d5de-11eb-975f-d95fc1ad5534.png)
