### ISSUE TITLE
Coverage build flaking on death tests

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#17136]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/80258/logs/245
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/80265/logs/158
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/80261/logs/269
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/80207/logs/315
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/80245/logs/207

**Comment by alyssawilk** [comment]
Doesn't look like we've updated gtest recently, and Ryan says no recent relevant changes to docker or coverage ci....

**Comment by phlax** [comment]
last change to the build image was 22351ae2574a0e3b6ba7d48f1653ba4c6659da70 (april 15) so i doubt that is what changed

not sure about coverage changes, and cant think of any ci changes that would have caused it to change

do we know ~exactly when the problem started ocurring ?

**Comment by phlax** [comment]
actually - last change was 85a8570cd0530402de21c48c6688dddb187775d5 (May 7)

**Comment by moderation** [comment]
Latest gtest is https://github.com/google/googletest/releases/tag/release-1.11.0 and it's in my list of deps to upgrade
