### ISSUE TITLE
Validating headers in Envoy

### ISSUE THREAD

**Issue by gituserjava** [envoyproxy/envoy#17164]
Is there a way we can read custom headers from request in envoy.filters.http.ext_authz in Envoy? Our request will contain a header as shown below and after successful authentication via `ext_authz` we want Envoy to validate if the request contains the header and the corresponding value. So in the below example if the request does not contain the below header or if it contains a value other than `sales_service`, Envoy should reject the request and return 401. Please advise. 

`consuming-service-name : sales-service`

Please note that sales-service is one of the allowed value. For examples, sales-service, marketing-service should be allowed but accounts-service should not be allowed.

**Comment by moderation** [comment]
You should be able to validate headers with the RBAC filter - https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rbac_filter

**Comment by gituserjava** [comment]
@moderation , looks like I can use this. Could you please share an example that shows usage of validating the incoming headers?
