### ISSUE TITLE
Filter linking docs out of date

### ISSUE THREAD

**Issue by justincely** [envoyproxy/envoy#17173]
The [developer docs on linking filters to the binary](https://github.com/envoyproxy/envoy/blob/main/bazel/DEVELOPER.md#filter-linking) seem to be a bit out of date.  The two links in that paragraph to the server code for examples just 404; I presume the code was moved somewhere?  Would be great to have this updated to the right location.

**Comment by lizan** [comment]
Yes that's right. PR is appreciated.

**Comment by justincely** [comment]
thanks @lizan, PR up
