### ISSUE TITLE
Transition to the quiche HTTP/2 codec

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#17180]
Presently Envoy is utilizing [nghttp2](https://github.com/nghttp2/nghttp2) codec for HTTP/2 protocol. A critical outstanding issue with nghttp2 codec is the security release process that is incompatible with the Envoy's.  This opens the potential for 0-day vulnerabilities in Envoy.

[quiche](https://quiche.googlesource.com/quiche/) maintainers offered to provide HTTP/2 codec implementation with the security release process compatible with Envoy's. quiche is currently used in Chromium and Envoy for QUIC.
This issue tracks the transition from nghttp2 code to quiche. The transition plan will go through the following steps:

- [ ] Create shim layer that allows Envoy's [HTTP/2 codec wrapper](https://github.com/envoyproxy/envoy/blob/765c970f06a4c962961a0e03a467e165b276d50f/source/common/http/http2/codec_impl.h#L110) to transparently work with nghttp2 or quiche codecs 
- [ ] set the default codec to nghttp2 with runtime override for testing period of 3 months
- [ ] flip the default to quiche codec with runtime override back to nghttp2 and start standard deprecation period
- [ ] remove nghttp2 codec from Envoy after deprecation period has completed.

**Comment by yanavlasov** [comment]
@birenroy from the quiche team will be working on this.

**Comment by moderation** [comment]
\nostale

**Comment by moderation** [comment]
no stalebot

**Comment by birenroy** [comment]
Can you assign this to me, please? Thanks.
