### ISSUE TITLE
LDN to support loading huge filter config data separately.

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#1718]
Some filters may need to use huge config data.  For example, grpc-json transcoder filter (https://envoyproxy.github.io/envoy/configuration/http_filters/grpc_json_transcoder_filter.html), needs to use a huge descriptor data.

This config data could not be read from file if LDS is used since LDS could not use file.  It is not good idea to embed these huge config data in the LDS payload either.  1) It will slow down the refresh.  2) not easy for human to read LDS config. 

It is better to load these huge config data separately. Until all these data are loaded, LDS processing can start.

Here is an idea,  add a "blob_store" section as following in the LDS payload

"blob_data": {
    "data1": "/data1_path/v1",   # URL path to fetch the data.
    "data2": "/data2_path/v2"
}

The URL paths will use the same protocol and host as LDS service.  LDS api will load the LDS first, subsequently, load all blob data. Then start to process LDS. 

In the filer config.  These data can be refereed as

{
                "type": "decoder",
                "name": "mixer",
                "config": {
                    "proto_descriptor_pb": "blob_data.data1",
                     ...
               }
},

The filer config code will get data stored in blob_data by calling some functions.  In this case, the filter see the value is prefixed with "blob_data.",  it will get the data "data1" from blob store.

**Comment by qiwzhang** [comment]
@lizan @kyessenov what do you think?

**Comment by lizan** [comment]
I'm not sure if it is worth to maintain this complexity.

For gRPC transcoder, the descriptor is not that huge, for example, https://github.com/envoyproxy/envoy/blob/master/test/proto/bookstore.proto generates 10KB descriptor while the proto source itself is 4.4KB. Make gRPC transcoder to take inline protobuf descriptor from LDS, and/or support gRPC reflection is the right way for the transcoder.

Do we have other use case that requires this?

**Comment by mattklein123** [comment]
I don't have any conceptual objection to this, but I agree with @lizan that it will be a substantial amount of work.

**Comment by lizan** [comment]
@mattklein123 or @htuch Do you have a rough idea how large blob inlining into [Filter.config](https://github.com/envoyproxy/data-plane-api/blob/master/api/lds.proto#L42) will impact performance etc?

**Comment by mattklein123** [comment]
No I don't. You would need to test. I would recommend measuring on some real use cases and see if there is an issue.

**Comment by htuch** [comment]
Yeah, +1 on making this feature data driven, i.e. let's see where we have issues before adding the complexity.  I'm open to exploring design changes here, but we need the complexity to be justified by need.

**Comment by mattklein123** [comment]
Closing for now as I don't see this being implemented. We can reopen if needed.
