### ISSUE TITLE
HTTP/1.1: timed out chunked encoded responses are terminated with `\r\n\r\n`

### ISSUE THREAD

**Issue by Diggsey** [envoyproxy/envoy#17186]
It appears that timed out chunked encoded responses are terminated with `\r\n\r\n`. The connection should be closed/reset without this termination.

(Original report below)

-----

This was tested in envoy v1.17.2, so this may have already been addressed, but I couldn't find anything in the changelog, or any related closed issues.

*Description*:
The default request timeout of 15s is actually a timeout on streaming of responses. This will typically be determined by the speed of the client's connection. If the client takes longer than 15s to complete the download, *even if the upstream server is capable of streaming more quickly* then envoy will close the connection.

However, what's worse is that if the response is being sent chunked, envoy will terminate the chunked response normally. This results in the client receiving a truncated file, with no indication that there was a problem with the download.

*Repro steps*:
Use `curl` to download a `>30 MB` file with `--rate-limit 200k` from a default-configured envoy. The download will appear to complete successfully, but the file will be truncated.

*Config*:
All default.

**Comment by mattklein123** [comment]
Unfortunately there is no default that is going to make everyone happy, so I doubt we will go through the pain of changing it in this case.

**Comment by Diggsey** [comment]
@mattklein123 regardless, terminating the stream as though nothing went wrong is a bug.

**Comment by mattklein123** [comment]
> @mattklein123 regardless, terminating the stream as though nothing went wrong is a bug.

It's not a bug. It's by design. See here for more information on timeouts: https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts

If you have suggestions on how to improve either the documentation or the functionality we are very much interested. This is a complicated topic.

**Comment by Diggsey** [comment]
You seem to be missing the point: if there is a timeout, Envoy should immediately close the connection. It should not terminate the stream with `\r\n\r\n` and then close the connection.

**Comment by mattklein123** [comment]
> You seem to be missing the point: if there is a timeout, Envoy should immediately close the connection. It should not terminate the stream with \r\n\r\n and then close the connection.

The point was not clear from your original report, but thanks for clarifying! Yes I agree that for HTTP/1.1 this is a bug. I will make the issue more clear and mark this help wanted. cc @alyssawilk

**Comment by Diggsey** [comment]
Sorry, I misrememberd and this is also incorrect - chunked encoding is terminated by a "zero size" chunk, not by `\r\n\r\n`.

The issue I'm seeing is that HTTP clients see the request as completing successfully. I think this is a problem with Envoy sending the terminator because it occurs with multiple HTTP clients (curl/browser/insomnia/etc) but it could also be caused by clients being overly permissive. Unfortunately most clients don't give sufficiently detailed output to see what *exactly* is going on with the transfer encoding.

Either way, even if Envoy is not doing something *wrong* here, it seems likely that there is a better way to indicate a failed response (eg. by terminating in the middle of a chunk or something) that would force the client to see that something's wrong.

(Especially given that Envoy is particularly susceptible to this issue due to the unfortunate choice of defaults,)

**Comment by alyssawilk** [comment]
Any chance you could provide a trace of this happening?  Theoretically 
IdleTimeoutIntegrationTest.PerStreamIdleTimeoutAfterBidiData verifies we don't send \r\n\r\n on idle timeouts and I validated manually with some logging it's handling that correctly.   While it's possible there's some corner case with large buffers and backup, I'm only seeing the HTTP/1.1 codec sending \r\n\r\n when serializing trailers, or explicitly proxying the last data on a connection.
