### ISSUE TITLE
Useless time conversion for histogram

### ISSUE THREAD

**Issue by R1kk3r** [envoyproxy/envoy#17184]
*Title*: Useless time conversion for histogram

*Description*:

I am trying to understand if, for an histogram, value reported to it are kept as-is. I mean, if for p50, the value returned is one of the real value submitted or if it is the result of an averaging/calculation (for speed/efficiency reason). Then, I came across [this piece of code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/stat_sinks/common/statsd/statsd.cc#L116) and I really don't get what is the purpose of `std::chrono::milliseconds(value).count()` with a `value` type of `uint64_t`? I would understand the conversion if `value` was a `Duration` type though.

**Comment by mattklein123** [comment]
Yeah that conversion doesn't seem necessary. PR appreciated.
