### ISSUE TITLE
envoy should read the data from the buffer Instead of listener filter to peek the data from socket buffer directly

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#17229]
According the review comment: https://github.com/envoyproxy/envoy/pull/16952#issuecomment-872377652, we can improve the listener filter.

Currently, the listener filter needs to register the file event to the socket, and peek data from the socket buffer directly. Which lead to the bug like https://github.com/envoyproxy/envoy/issues/16951. A better way is envoy read the data into the buffer, and listener filter read those data from the buffer.

**Comment by lambdai** [comment]
+1 
The listener filters have the requirement to read/peek/write data. Currently the listener filter is operating the socket and event directly.
The connection abstraction might overkill. My hunch is that libevent bufferevent works
