### ISSUE TITLE
inline http cookie header

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#17234]
The current `cookie` is not be implemented as O(1) inline header which make the cookie-related operation very expensive.

Perhaps we can set a special delimiter `;` for the cookie to make the cookie an inline header.

**Comment by mattklein123** [comment]
cc @asraa @alyssawilk

**Comment by alyssawilk** [comment]
I think Dan actually fixed the delimiter issue (https://github.com/envoyproxy/envoy/blob/main/source/common/http/header_map_impl.cc#L437) but where I agree O(n) isn't good I suspect inlining cookies would break things for some users.  it'd be nice to have a configurable bootstrap option for which headers to inline so folks could optimize on their own.

**Comment by mattklein123** [comment]
> it'd be nice to have a configurable bootstrap option for which headers to inline so folks could optimize on their own.

FWIW when I wrote the custom inline header code I intended to eventually make it bootstrap configurable. It should be quite easy:
https://github.com/envoyproxy/envoy/blob/d3a90127f8c408651e8ab44e961408ca1fd972b4/source/server/server.cc#L350-L362

**Comment by wbpcode** [comment]
After that, we will have three ways to define the inline header.
The first is the macro definition in HeaderMap. This type of inline header provides related methods with the same name(getXXX, setXXX).
The second is to implement the inline header through RegisterCustomInlineHeader.
The third is to specify the header name to be set as the inline header in the bootstrap.
