### ISSUE TITLE
Ubuntu installation fails due to Bintray not being accessible

### ISSUE THREAD

**Issue by javiku** [envoyproxy/envoy#17236]
Following the installation steps for Ubuntu described in https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-ubuntu-linux results in an error accessing bintray repositories:

```
Err:8 https://dl.bintray.com/tetrate/getenvoy-deb bionic InRelease              
  403  Forbidden [IP: 35.157.24.53 443]
```

It is currently (for some hours now) impossible to install Envoy in Ubuntu following the recommended steps.

**Comment by codefromthecrypt** [comment]
ACK these packages are deprecated. I tried a little and failed.

@arkodg do you know a temporary workaround to let debian/ubuntu work?

Seems some are able to at least temporarily use cloudsmith for some types of packages
https://github.com/blake/vagrant-consul-tproxy/blob/33547e9dc1d0f86a13aa2c84e3a6d60575df5135/examples/vagrant/cloud-init-injection/cloud-configs/common.cfg

I tried monkeying various combinations of https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-debian-gnu-linux and https://help.cloudsmith.io/docs/debian-repository#public-repositories to no avail

**Comment by javiku** [comment]
For anyone needing a temporary workaround (for automated processes or CI not failing), we are temporarily installing Envoy on Ubuntu 18.04 like this (thanks to info in [this comment](https://github.com/envoyproxy/envoy/issues/16867#issuecomment-874369852)):

```
ENVOY_VERSION="1.15.5"

# ALTERNATIVE INSTALLATION METHOD
wget https://archive.tetratelabs.io/envoy/download/v${ENVOY_VERSION}/envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
tar -xf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
chmod +x envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy
sudo mv envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy /usr/bin/envoy
rm -rf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz envoy-v${ENVOY_VERSION}-linux-amd64
```

**Comment by carlossg** [comment]
You can find packages and instructions at https://cloudsmith.io/~tetrate/repos/getenvoy-deb-stable/setup/#formats-deb

**Comment by ohdearaugustin** [comment]
The packages are not available anymore as bintray.com is end of life. Refer to https://jfrog.com/center-sunset/

The suggested repository from @carlossg are the same guys, who operated the old one.

**Comment by arkodg** [comment]
thanks for surfacing the link with the correct installation steps @carlossg 

can confirm it works
```
root@c8f200002b8e:/# curl -1sLf \
>   'https://deb.dl.getenvoy.io/public/setup.deb.sh' \
>   | sudo -E bash
Executing the  setup script for the 'tetrate/getenvoy-deb-stable' repository ...

   OK: Checking for required executable 'curl' ... 
   OK: Checking for required executable 'apt-get' ... 
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=16.04  codename=xenial  arch=x86_64  
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ... 
   OK: Updating apt repository metadata cache ... 
   OK: Attempting to install 'apt-transport-https' ... 
   OK: Checking for apt dependency 'ca-certificates' ... 
   OK: Checking for apt dependency 'gnupg' ... 
   OK: Importing 'tetrate/getenvoy-deb-stable' repository GPG key into apt ... 
   OK: Checking if upstream install config is OK ... 
   OK: Installing 'tetrate/getenvoy-deb-stable' repository via apt ... 
   OK: Updating apt repository metadata cache ... 
   OK: The repository has been installed successfully - You're ready to rock!

root@c8f200002b8e:/# apt install getenvoy-envoy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  getenvoy-envoy
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.5 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://deb.dl.getenvoy.io/public/deb/ubuntu xenial/main amd64 getenvoy-envoy amd64 1.18.2.p0.gd362e79-1p75.g76c310e [16.5 MB]
Fetched 16.5 MB in 1s (15.7 MB/s)         
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package getenvoy-envoy.
(Reading database ... 5342 files and directories currently installed.)
Preparing to unpack .../getenvoy-envoy_1.18.2.p0.gd362e79-1p75.g76c310e_amd64.deb ...
Unpacking getenvoy-envoy (1.18.2.p0.gd362e79-1p75.g76c310e) ...
Setting up getenvoy-envoy (1.18.2.p0.gd362e79-1p75.g76c310e) ...

root@c8f200002b8e:/# envoy --version

envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

```

@codefromthecrypt @phlax  I believe we are in a state of flux where `deb.dl.getenvoy.io` might not be the final home for fetching these debs. Do we want to still go ahead and update the envoyproxy docs ?

**Comment by codefromthecrypt** [comment]
@arkodg my 2p is we either remove the references of getenvoy from https://www.envoyproxy.io/docs/envoy/latest/start/install or fix them. At the moment, they say literally that things are in flux ("...using Get Envoy until official packages exist.") then give you some broken steps also!

**Comment by codefromthecrypt** [comment]
I spiked this, folks can comment whether to merge it, change it or have me repurpose it to delete the "get envoy" instructions entirely. One way or another, let's stop advertising broken! https://github.com/envoyproxy/envoy/pull/17246

**Comment by phlax** [comment]
>  I believe we are in a state of flux where deb.dl.getenvoy.io might not be the final home for fetching these debs. Do we want to still go ahead and update the envoyproxy docs ?

i think we want to update the docs in the interim - its going to be a matter of weeks before we are ready with the newer distro links set up

that said - im very -1 to documenting with this script - i would much prefer we keep the existing format of the docs with the setup requirements explicit, active checking for checksums, and no requirements beyond what is actually required to install and run envoy

**Comment by sgtang** [comment]
Hey guys, thanks for the workaround using the Cloudsmith repo. Our issue is that the 1.16.4 version isn't available there and we need it for compatibility with Consul Connect (https://www.consul.io/docs/connect/proxies/envoy). Is there another way to grab that specific version in the meantime? Thanks.

**Comment by phlax** [comment]
> Is there another way to grab that specific version in the meantime? Thanks.

you can extract the binary from the docker image - its not ideal - but its a workaround for now

**Comment by javiku** [comment]
> Is there another way to grab that specific version in the meantime? Thanks.

As I mentioned early, you could also download version 1.16.4 with:
```
wget https://archive.tetratelabs.io/envoy/download/v1.16.4/envoy-v1.16.4-linux-amd64.tar.xz
```
We were using this method because the version we needed (1.15.5) was not available in the cloudsmith.io repos.

> We're going to give func-e a shot for now.

We saw func-e some days ago, but we weren't sure how "official" it is or its current status.

**Comment by codefromthecrypt** [comment]
> We saw func-e some days ago, but we weren't sure how "official" it is or its current status.

I think it is safe to say anything not in the envoyproxy org is not official. https://func-e.io is a Tetrate project and the replacement for what was formerly the getenvoy CLI. Its aim is to make things easier, like before you know what a service mesh or data plane is etc. We intentionally did not replace the system packages as the confusion of the past taught us that lesson!

func-e is decoupled from https://archive.tetratelabs.io/envoy, but is its primary user. This archive is built from the official docker images and the official Homebrew (macOS) packages. In other words, exactly the same binaries as what docker or MacOS installs would produce. This is intentional because we also don't want confusion as to "who built what" (yet another lesson learned).

It is intentional and for the foreseeable future that https://archive.tetratelabs.io/envoy is used for func-e though #16830 will provide a more official way to get tarballs when implemented. The archive uses permalinks intentionally to get out of the "which package repository is down today" problem which everyone including Tetrate staff were burnt badly by. It is also a way to ensure the least bandwidth is used. For example, debug images are massive, but the archive controls which files have it, etc so that the first timer experience is far more reasonable.

I think it is very related, to mention the above now, but I do think that when the dust settles discussions about Tetrate stuff should be in the appropriate repos, and that will help folks know what is official or not (ex if we are chatting about it here, and it is an envoyproxy thing, it is official!). Meanwhile, I hope this helped!

**Comment by javiku** [comment]
Thank you very much for that detailed and clarifying explanation! We have a much clearer vision now.

**Comment by dclipca** [comment]
> For anyone needing a temporary workaround (for automated processes or CI not failing), we are temporarily installing Envoy on Ubuntu 18.04 like this (thanks to info in [this comment](https://github.com/envoyproxy/envoy/issues/16867#issuecomment-874369852)):
> 
> ```
> ENVOY_VERSION="1.15.5"
> 
> # ALTERNATIVE INSTALLATION METHOD
> wget https://archive.tetratelabs.io/envoy/download/v${ENVOY_VERSION}/envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
> tar -xf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
> chmod +x envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy
> sudo mv envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy /usr/bin/envoy
> rm -rf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz envoy-v${ENVOY_VERSION}-linux-amd64
> ```

Use `ENVOY_VERSION="1.19.0"` because it's the latest stable version as shown by (https://www.envoyproxy.io/).
