### ISSUE TITLE
Troubleshooting mTLS connection failures

### ISSUE THREAD

**Issue by zthomas2** [envoyproxy/envoy#17245]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Troubleshooting mTLS connection failures

*Description*:
I believe I am having the same issue as described in [this](https://github.com/envoyproxy/envoy/issues/13563) thread. In my case though, I am not able to get the TCP access logger to log the relevant data I would need for troubleshooting failed client connections in a production environment. The data is clearly there, as it is logged correctly when I have the connection logger set to debug, as below. The format string for the access logger line below the debug is:

`"[%START_TIME%] call_duration_ms=%DURATION% client_address=%DOWNSTREAM_REMOTE_ADDRESS% certificate_subject=%DOWNSTREAM_PEER_SUBJECT% termination_reason=%CONNECTION_TERMINATION_DETAILS% response_flags=%RESPONSE_FLAGS% cipher=%DOWNSTREAM_TLS_CIPHER% tls_version=%DOWNSTREAM_TLS_VERSION% reply=%LOCAL_REPLY_BODY%\n"`

`[2021-07-06 17:09:05.190][26][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:224] [C31] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2021-07-06 17:09:05.190][26][debug][connection] [source/common/network/connection_impl.cc:203] [C31] closing socket: 0
[2021-07-06T17:09:05.144Z] call_duration_ms=46 client_address=<IP>:<PORT> certificate_subject=CN=client-test.company.net,O=company,L=city,ST=state,C=US termination_reason=- response_flags=- cipher=ECDHE-RSA-AES128-GCM-SHA256 tls_version=TLSv1.2 reply=`

I must be missing something simple, but I can't figure out why CONNECTION_TERMINATION_DETAILS and RESPONSE_FLAGS are unpopulated.

**Comment by lambdai** [comment]
It seems the only filled CONNECTION_TERMINATION_DETAILS are tls timeout  and rbac.

RESPONSE_FLAGS is similar. You may want to create your own flag/detail and populate at the right condition

**Comment by zthomas2** [comment]
@lambdai Thanks for your response! Is there a more well defined way to handle what I'm trying to do here? I feel like this must be a fairly common requirement, especially as mTLS gains tractions.
