### ISSUE TITLE
ProxyProtocol implementation does not accept all valid header formats

### ISSUE THREAD

**Issue by tonulr** [envoyproxy/envoy#1728]
Valid header formats are:
```
- TCP/IPv4 :
    "PROXY TCP4 255.255.255.255 255.255.255.255 65535 65535\r\n"
  => 5 + 1 + 4 + 1 + 15 + 1 + 15 + 1 + 5 + 1 + 5 + 2 = 56 chars

- TCP/IPv6 :
    "PROXY TCP6 ffff:f...f:ffff ffff:f...f:ffff 65535 65535\r\n"
  => 5 + 1 + 4 + 1 + 39 + 1 + 39 + 1 + 5 + 1 + 5 + 2 = 104 chars

- unknown connection (short form) :
    "PROXY UNKNOWN\r\n"
  => 5 + 1 + 7 + 2 = 15 chars

- worst case (optional fields set to 0xff) :
    "PROXY UNKNOWN ffff:f...f:ffff ffff:f...f:ffff 65535 65535\r\n"
  => 5 + 1 + 7 + 1 + 39 + 1 + 39 + 1 + 5 + 1 + 5 + 2 = 107 chars
```
(Ref: http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt p2.1.)

Currently, only the first two seem to be supported.

I ran into this issue trying to configure a Proxy V1 enabled healthcheck on Google Cloud Platform,
which uses the `PROXY UNKNOWN\r\n` format.
(Ref: https://cloud.google.com/sdk/gcloud/reference/compute/health-checks/create/https)

**Comment by mattklein123** [comment]
@tonulr thanks for the report. If someone would like to fix this the code is here: https://github.com/envoyproxy/envoy/blob/master/source/common/network/proxy_protocol.cc

**Comment by mattklein123** [comment]
I think this is fixed per linked PR.
