### ISSUE TITLE
Envoy UBI based Docker images on RedHat OpenShift Catalog

### ISSUE THREAD

**Issue by david-yu** [envoyproxy/envoy#17295]
*Title*: Envoy UBI based Docker images on RedHat OpenShift Catalog

*Description*:
Currently Envoy does not provide official packages on RHEL/CentOS since getenvoy.io is no longer officially providing RPM packages any longer due to trademark issues (docs: https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-rpm-based-distros) 

OpenShift currently requires that for officially certified images on OpenShift, containers should be built based on the UBI [image](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8), which is based on a RHEL base image. This base image has been leveraged heavily in OpenShift in secure environments, as security is one of the main value props for running OpenShift on self-managed deployments. 

Our team at HashiCorp is wondering if it's possible to also provide a UBI based Envoy image on the RedHat catalog, without infringing on the Envoy trademarks, since we also provide support for OpenShift environments for Consul. We would be open to doing some work to make this image available. Preferably the obi-minimal image should be used to reduce footprint on downloads.

[optional *Relevant Links*:]
Blog post on RedHat UBI Based Images: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

cc @mdeggies

**Comment by mattklein123** [comment]
cc @phlax

**Comment by phlax** [comment]
> Currently Envoy does not provide official packages on RHEL/CentOS since getenvoy.io is no longer officially provide RPM packages 

a situation we hope to resolve fairly shortly

> Our team at HashiCorp is wondering if it's possible to also provide a UBI based Envoy image on the RedHat catalog, without infringing on the Envoy trademarks

iiuc then its ok to package Envoy as long as you dont claim it *is* Envoy - i think it just needs to be clear that you have packaged it (IANAL)

as i understand it the trademark issue was more to do with domains

relatedly in my quest to add packaging im testing against the ubi images

**Comment by david-yu** [comment]
> relatedly in my quest to add packaging im testing against the ubi images

Thank @phlax! I'm curious are you also working on getting Envoy images on RedHat catalog built using UBI base images? I apologize if there is a duplicate issue or work that is going that I'm not aware of.

**Comment by phlax** [comment]
> I'm curious are you also working on getting Envoy images on RedHat catalog built using UBI base images?

no - im building rpms and then testing the rpms for install/start/stop/uninstall etc

**Comment by david-yu** [comment]
@phlax Thanks for the heads up! I think we'll likely need to utilize the changes you make for https://github.com/envoyproxy/envoy/issues/16867 to also support building UBI images. Btw does the Envoy community also plan to build at least CentOS based Docker images once that is available? Or is the plan more so to rely on distroless images to avoid having to couple OS libraries with a Docker image?
