### ISSUE TITLE
Is there a poster filter plugin ?

### ISSUE THREAD

**Issue by HuanLiu-hotstar** [envoyproxy/envoy#17307]
*Title*: *Is there a poster filter plugin ?*

*Description*:
- 1 envoy has provided some kind of useful pre-filter to implement our business logic ,for example rate limit service, authentication services and so on, these plugins are before the real request to domain service. 
- 2 But for some scenario, for example I want to update token and response it to client , post-filter will helpful when finished the response from domain service.
- 3 picture as follows:
![image](https://user-images.githubusercontent.com/84910109/125415264-4bd675b0-9774-4da2-ac0d-c89f540ed175.png)

**Comment by mattklein123** [comment]
You want an "encoder" filter.

**Comment by HuanLiu-hotstar** [comment]
> You want an "encoder" filter.

yes, I want do some action with the Response from DomainService.
