### ISSUE TITLE
Slow performance on aarch64?

### ISSUE THREAD

**Issue by jboero** [envoyproxy/envoy#17313]
*Title*: *Possible performance issues with arm64 build on A72 cores?*

*Description*:
> envoy  version: 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/clean-getenvoy-b76c773-envoy/RELEASE/BoringSSL
> I recently migrated a use case I've been testing without issues on x86_64 to a high-end aarch64 box I have (Honeycomb LX2K) which has 16xA72 cores @2.2Ghz, 32GB RAM, and 4x10GbE.  I notice a single client connection maxes out a CPU core at 30MB/s where x86_64 is able to saturate a 10Gb network fine.  Running parallel clients scales linearly (30MB/s per process, maxed core on each).  **It could just be the CPUs** but they tend to perform much better than this in other operations (this isn't a Raspberry Pi).  Anwyay I wanted to put this out there in case others noticed performance issues on arm64 or if anybody has an optimized build for aarch64.  I have been unable to get my own build together with bazel.

I realize ARM is a bit experimental right now but curious if anybody else notices unexpected performance issues or finds a way to tune things better.  This box usually has no problems pushing ~2GB/s in other apps, so 30MB/s is a bit suspect.

**Comment by moderation** [comment]
There was a PR recently to address aarch64 performance however it landed after the 1.18.3 release - https://github.com/envoyproxy/envoy/pull/16104. The PR has the issue details but the performance issue unaccelerated cryptographic operations - https://github.com/envoyproxy/envoy/issues/16105

It would be very interesting to see if you get improved results using a latest main build

**Comment by jboero** [comment]
Ah great thanks I'll try that in the next release.

**Comment by moderation** [comment]
@jboero you are in luck. 1.19.0 was just released - https://groups.google.com/g/envoy-announce/c/26P9tluO6mQ

**Comment by jboero** [comment]
Thanks!

**Comment by jboero** [comment]
Boom and like that I can now do 300MB/s - up from 30MB/s.  Thank you 1.19.

**Comment by moderation** [comment]
That's awesome. Thanks for reporting the update
