### ISSUE TITLE
envoy.reloadable_features.vhds_heartbeats deprecation

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#17326]
Your change #13201 (xds: add support for TTLs) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by daixiang0** [comment]
Could I take it if possible?

**Comment by KBaichoo** [comment]
was fixed in https://github.com/envoyproxy/envoy/pull/19602
