### ISSUE TITLE
have any plan to support coroutine mode for filters?

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#17332]
*Description*:
have any plan to support coroutine mode for filters? It will make some block operations easier. 

[optional *Relevant Links*:]
https://en.cppreference.com/w/cpp/language/coroutines

**Comment by snowp** [comment]
We don't have any plans to support C++20 anytime soon, primarily due to having to support various platforms (e.g. mobile platforms) that don't support these new features

**Comment by mattklein123** [comment]
See also https://github.com/envoyproxy/envoy/issues/2052. It's something that would be pretty neat to support, the Lua programming model has worked out very nicely for users, but as @snowp said it's not easy to do generically. Also, at this point we should probably be investing more in WASM. cc @PiotrSikora

**Comment by PiotrSikora** [comment]
FYI, there is some work happening in WebAssembly ([stack swithcing](https://github.com/WebAssembly/stack-switching)) and in Proxy-Wasm/WASI around async, but it's probably going to take another year before it's finalized and usable.

**Comment by jokerwyt** [comment]
Is there any update? I think now co-routine ecosystem is improved a lot since 2021.
