### ISSUE TITLE
Backport request: Backport 16914 to 1.17 and 1.18

### ISSUE THREAD

**Issue by jacob-delgado** [envoyproxy/envoy#17349]
*Title*: *Backport request: Backport 16914 to 1.17 and 1.18*

*Description*:

The original issue that the PR fixed, see https://github.com/envoyproxy/envoy/issues/16804, is addressed can be found at https://github.com/envoyproxy/envoy/issues/16804. It was mentioned to go through the proper channels to request formal approval for a backport, see @snowp's comment https://github.com/envoyproxy/envoy/pull/17261#issuecomment-879945817. @dmitri-d has approved the v1.18 version, but it has yet to merge.

*Issue*:

When getting a rebalancer by address and a wild card match is being used, the first match in the list is returned. However, if there are listeners with addresses "0.0.0.0" and "::" then the first active listener found will be used, irrespective of the IP family type. 

*Proposed fixes*:

This is put behind a runtime guard for 1.19 where it is enabled by default, with the ability for the user to disable this. In 1.17 and 1.18 I'm requesting we ship with this code, but turn it off by default and the user must explicitly enable the same runtime guard.

I have cherry-picked these commits and made the appropriate changes to disable it by default. They can be found at
v1.17: https://github.com/envoyproxy/envoy/pull/17262
v1.18: https://github.com/envoyproxy/envoy/pull/17261

*Risks*:
Low. Given that the user must opt-in to use this feature I do not anticipate any issues. The old behavior can easily be reverted by not setting this flag.

**Comment by jacob-delgado** [comment]
cc @nrjpoddarv @ycai-aspen

A formal request to get listener changes back ported.

**Comment by nrjpoddar** [comment]
It feels like a perfect change to be back ported as its opt-in and @jacob-delgado has done the work so I hope it can be approved.

**Comment by snowp** [comment]
Ran this by the other maintainers and while this is a borderline case we're okay with the back port due to its small scope and the fact that it's essentially a bug fix

What is the state of the PRs? I think we should get them all green before merging any, just to make sure they end up in the same dot release

**Comment by jacob-delgado** [comment]
> Ran this by the other maintainers and while this is a borderline case we're okay with the back port due to its small scope and the fact that it's essentially a bug fix
> 
> What is the state of the PRs? I think we should get them all green before merging any, just to make sure they end up in the same dot release

The v1.17 PR is blocked on https://github.com/envoyproxy/envoy/pull/17263

The v1.18 PR is ready to merge and is blocked on https://github.com/envoyproxy/envoy/pull/17261/checks?check_run_id=3014552903. I have no idea how to fix this issue.

**Comment by jacob-delgado** [comment]
Both v1.17 and v1.18 PRs were merged in. Thanks!

**Comment by mathetake** [comment]
I will cut the new tag on 1.17 and 1.18 after another backport(https://github.com/envoyproxy/envoy/issues/17350, https://github.com/envoyproxy/envoy/pull/17426, https://github.com/envoyproxy/envoy/pull/17441) also lands. sg? @lizan
