### ISSUE TITLE
Backport of `www-authenticate header` to 1.17 and 1.18

### ISSUE THREAD

**Issue by cyran-ryan** [envoyproxy/envoy#17350]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Request of backport of JWT auth header fix (#16216)

*Description*:
>Describe the issue.

The `jwt_authn` filter does not follow the HTTP specification and causes some clients to misbehave when receiving a 401 response. #16216 fixes this issue for the main branch and 1.19. This issue is to discuss the possibility of back-porting this change to 1.18 and 1.17. I would be willing to create and put up the PRs to do so.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by snowp** [comment]
After talking about this with other maintainers this seems like an okay thing to backport. Please get the 1.17 and 1.18 PRs ready and we'll get the process started

**Comment by cyran-ryan** [comment]
Both PRs are now opened! See #17441 and #17426

**Comment by cyran-ryan** [comment]
Backport completed
