### ISSUE TITLE
Relationship between grpc service definition timeout and cluster definition connect_timeout

### ISSUE THREAD

**Issue by swav** [envoyproxy/envoy#17353]
In the configuration shown below there is timeout: 1s of grpc_service which is defined to call cluster: ext_authz which also has connect_timeout: 5s. Is there a relationship between those two timeouts? The grpc_service timeout is defined as "the timeout for a specific request", vs connect_timeout as "The timeout for new network connections to hosts in the cluster", so in case the grpc_service timeout is 'started' first, should it be larger or at least, equal to that of the cluster connect_timeout? 

Is there a best practice advice I can follow? For now, I have set both to the same value of 5s for testing, to be set via an environment variable to 3s in prod.

thanks in advance,
swav

"http_filters": [
             {
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "ext_authz"
                },
                **"timeout": "1s"**
               },
               "transport_api_version": "V3"
              }
             },
...
"dynamic_active_clusters": [
{
     "version_info": "1626296116754330624",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "ext_authz",
      "type": "LOGICAL_DNS",
      **"connect_timeout": "5s",**

**Comment by snowp** [comment]
The connect timeout is how long to wait for the connection to be established, while the timeout is how long to wait for the response for a given request. It probably makes sense to have timeout > connect_timeout

**Comment by swav** [comment]
Thank you very much for clarifying this. :)
