### ISSUE TITLE
[ext_proc] request_body_mode override for stream with a request without a body causes seg fault

### ISSUE THREAD

**Issue by ikepolinsky** [envoyproxy/envoy#17354]
Received permission to make this crash a public issue from @htuch 

*Title*: *request_body_mode override for stream with a request without a body causes seg fault*

*Description*:
The following scenario causes a seg fault:
1. Downstream sends a GET request to Envoy with no HTTP Body
2. ext_proc filter sends ProcessingRequest message to external process with request_headers set
3. External process replies with ProcessingResponse message setting the ProcessingMode mode_override to BUFFER the request_body
4. A seg fault occurs because the downstream request does not contain a body.

If the downstream request contains a body (e.g., POST request with data) a crash does not occur.

The following test case can be added to `test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc` to recreate the seg fault
```
// Test how the filter responds when asked to buffer a request body for a GET
// request with no body.
TEST_P(ExtProcIntegrationTest, BufferBodyOverrideNoRequestBody) {
  initializeConfig();
  HttpIntegrationTest::initialize();
  auto response = sendDownstreamRequest(absl::nullopt);

  ProcessingRequest request_headers_msg;
  waitForFirstMessage(request_headers_msg);
  processor_stream_->startGrpcStream();
  ProcessingResponse resp;
  resp.mutable_request_headers();
  auto* proc_mode = resp.mutable_mode_override();
  proc_mode->set_request_body_mode(ProcessingMode::BUFFERED);
  processor_stream_->sendGrpcMessage(resp);

  handleUpstreamRequest();

  processor_stream_->finishGrpcStream(Grpc::Status::Ok);

  // TODO: fix what should be the expected behavior here?
  verifyDownstreamResponse(*response, 500);
}
```

**Comment by snowp** [comment]
@gbrail

**Comment by ikepolinsky** [comment]
I've had a chance to look into this a bit more and want to add some more context.

The crash is caused when the external process requests the buffered body of a GET request. This does not happen when requesting the buffered body of a POST request, even if the POST request's body is empty.

[This line](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_proc/processor_state.cc#L70) is the cause of the crash, because for GET requests `bufferedData()` is never initialized and remains null. The following code works, but I'm not sure if it's appropriate because it might need to be fixed elsewhere to prevent this issue from occurring again.

```
        if (complete_body_available_) {
          // If we get here, then all the body data came in before the header message
          // was complete, and the server wants the body. So, don't continue filter
          // processing, but send the buffered request body now.
          if (bufferedData() == nullptr) {
            ENVOY_LOG(debug, "bufferedData is null, initializing empty buffer");
            Buffer::OwnedImpl buf;
            addBufferedData(buf);
          }
          ENVOY_LOG(debug, "Sending buffered request body message");
          filter_.sendBufferedData(*this, true);
        }
```

Note, simply doing a null check such as `(complete_body_available && bufferedData() != nullptr)` results in an infinite processing loop that never changes state.

**Comment by ikepolinsky** [comment]
Instead of creating an empty buffer to send, we might want to treat this situation as a spurious message. GET, DELETE, and HEAD _should not_ have bodies, but it's possible and not officially supported. Thoughts?
