### ISSUE TITLE
Clarity on `upstream_cx_max_requests` 

### ISSUE THREAD

**Issue by jothi7891** [envoyproxy/envoy#17379]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Clarity on `upstream_cx_max_requests` *

*Description*:
>Describe the issue.

I tried browsing through the documentation , but could understand completely what this `upstream_cx_max_requests` mean and when it does get a non zero value ?

In our org, we have basically disabled the `circuit_breaker` thresholds by setting it to a very high value as suggested in the docs. But we have seen applications receive `503` with body as `"disconnect/reset before headers. reset reason: overflow"` which we thought would only be happening when circuit breaker is tripped. None of the `circuit_breaker_flags`(https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#circuit-breakers-statistics) were turned on.  The only thing we saw was non-zero values on this metric.

So would like to understand the usage of the metric and also when the error message "disconnect/reset before headers. reset reason: overflow" would be sent in addition to circuit_breaker getting tripped.

All our cluster backends are `HTTP1.1`

```
root@dev55-uswest1adevc:~# curl http://localhost:1338/server_info
{
 "version": "11934bd081011cd7d58a9d49be4965917cce8aa0/1.13.0-dev/Modified/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 32,
  "config_path": "/nail/etc/envoy/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_format_escaped": false,
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 1,
  "cpuset_threads": false,
  "disabled_extensions": [],
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "7200s"
 },
 "uptime_current_epoch": "1511429s",
 "uptime_all_epochs": "12158306s"
}
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by htuch** [comment]
Do you set `max_requests_per_connection`? https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto

**Comment by jothi7891** [comment]
No, we do not use that setting. Infact , we just use the `yaml` files rather than the `protobuf` for configuring envoy.

**Comment by htuch** [comment]
Could you share the `/config_dump` or YAML config for the cluster in question? This should only be set AFAICT when `max_requests_per_connection` is enabled.

**Comment by jothi7891** [comment]
[envoy_config_dump.json.zip](https://github.com/envoyproxy/envoy/files/6857143/envoy_config_dump.json.zip)

here is the config dump

**Comment by htuch** [comment]
@jothi7891 does this reproduce on a recent release or at HEAD? 1.13.0 is pretty old at this point.

**Comment by jothi7891** [comment]
@htuch - There is no definite way to reproduce it but it does occur quite regularly on 1.13.0. We have plans to migrate to the latest stable version and can let you know if its still a problem after our migration.

One more question, would `envoy` send "disconnect/reset before headers. reset reason: overflow" when the number of requests exceed `max_requests_per_connection` ?

**Comment by htuch** [comment]
I don't think so. Let's see if this is still happening at latest stable, since my spelunking here is limited to HEAD.
