### ISSUE TITLE
release/v1.19 branch is not available 

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#17385]
Will be such branch available similar to v1.17...etc? At which point for v1.19? Or envoy is dropping such practice?

**Comment by lizan** [comment]
@mathetake since you're now stable maintainer for Q3, can you create a release branch from v1.19.0 tag and kicks off 1.19.1-dev?

**Comment by mathetake** [comment]
sure will do.

**Comment by mathetake** [comment]
now created: https://github.com/envoyproxy/envoy/tree/release/v1.19
