### ISSUE TITLE
Handshake Access log Filter

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#17394]
In some secured environments, we would like only log handshakes (both success and failure). One way is to add logs in Context with logger id (ssl) - currently sslsocket.cc logs failure but at debug level on "connection" logger. 

Another way is add a new access log filter that filters only successful/failure handshakes and logs. Have n't looked at the code to see if it is a feasible option - but I am guessing it should be possible.

Any other thoughts?

 @lizan @PiotrSikora WDYT?

**Comment by lizan** [comment]
I haven't fully investigated, this should be done through [listener access log](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-access-log)

**Comment by ramaraochavali** [comment]
Yeah. We should configure at listener access log - but do not we need additional access log filter https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-accesslogfilter? or are you saying additional config in access log?

**Comment by ramaraochavali** [comment]
@lizan ^^ is that correct statement?

**Comment by ramaraochavali** [comment]
@lizan any suggestions?
