### ISSUE TITLE
Does envoy provide a mechanism to observe configuration changes?

### ISSUE THREAD

**Issue by zhangzerui20** [envoyproxy/envoy#17390]
I'm doing something similar to `Istio`, using `Iptable` to intercept HTTP requests and envoy to handle the traffic. I use `xDS` to connect envoy to our own service registry. When a new service is registered, new `cDS` and rds will be generated and sent to `envoy`.

Just doing this still does not work properly, because it also needs to generate DNS records. I found that `DNS Filter` can do this, but it is currently under development. Therefore, I am going to develop a module to watch the `envoy` cluster configuration and generate a DNS record for each cluster.

So, my question is whether `envoy` provides a watch mechanism so that I can perceive that the cluster configuration of `envoy` has changed. If not, I can only use polling to check whether changes have occurred.

**Comment by htuch** [comment]
Probably need more detail. Who is the watch mechanism used by? Some extensions inside of Envoy, some external process?

How do you plan on regenerating the DNS filter config?

Envoy itself will watch for xDS changes either via gRPC or filesytem (inotify).
