### ISSUE TITLE
[wasm] Can I transfrom http request into tcp on HTTP Filter

### ISSUE THREAD

**Issue by orangetangerine** [envoyproxy/envoy#17392]
*Title* : *Can I transfrom HTTP request into tcp on HTTP Filter*

*Description* :
We have an old RPC framework running on production, with a self-designed RPC protocol via TCP. And I've made a transformer to turn gRPC request onto this private RPC request, so that these old services can run in Kubernetes, work on L7, and be controlled by Istio-proxy.
My question is, can I do this transform by WASM on HTTP Filter? If I apply a custom wasm on HTTP Filter, how can I turn gPRC requests to TCP bytes(non HTTP format).

I found *ReplaceDownstreamData* in APIs, but it seems only available in TcpContext, not HttpContext.

**Comment by orangetangerine** [comment]
Like:
envoyfilter reveive:
```
POST / HTTP/1.1
Content-Type: application/grpc
body...
```

and send to backend server:
```
0f 0b            0f 0a   00 01  00 ff           xx  xx xx xx
(magic header) (length) (path)  (body length)  (http body)
```

**Comment by htuch** [comment]
So, you want to do gRPC -> some custom TCP protocol. I think if this was a terminal HTTP filter and able to perform a cluster pick itself via cluster manager from the TCP connection pool this would be possible in a C++ filter, but that's pretty complicated and not sure if this can be done in Wasm.

Maybe you could convert to an HTTP CONNECT internally and then loopback to the Envoy to continue the request. @alyssawilk @PiotrSikora thoughts on how to do this simply in either C++ or Wasm?

**Comment by orangetangerine** [comment]
> So, you want to do gRPC -> some custom TCP protocol. 
Yes! 
I already made an external filter as sidecar in Golang to transform gRPC to custom protocol.
So there are two sidecars: istio-proxy and my filter. 
If protocol transformation can be done in Wasm, it could get better performance.
