### ISSUE TITLE
Support JWT extraction from cookies in jwt_authn

### ISSUE THREAD

**Issue by theshubhamp** [envoyproxy/envoy#17424]
*Title*: Support JWT extraction from cookies in jwt_authn

*Description*:
It's common for JWTs to be sent as HttpOnly cookies from a browser. `jwt_authn` currently supports extraction from headers and query parameters but lacks the ability to work with cookies. 

It can be made to work with cookies by using a combination of these 3 filters as discussed [on #7025's comment](https://github.com/envoyproxy/envoy/issues/7025#issuecomment-709654349):
`header_to_metatdata` -> metadata to header (using Lua ) -> `jwt_authn`

Adding first party support to extract from cookies will make doing this much easier.

**Comment by theshubhamp** [comment]
Looked at the structure of `jwt_authn` and I believe it can be done this way:
- Add `from_cookies` to config schema that accepts cookie names as a list (similar to `from_params`)
-  Change [extractor.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/jwt_authn/extractor.cc) and to extract cookie using the `Envoy::Http::Utility::parseCookieValue` function


I can contribute a PR if the community thinks this would be a good addition

**Comment by htuch** [comment]
Seems a reasonable feature. @qiwzhang WDYT?

**Comment by tilgovi** [comment]
Came here from #7025 to say that I would find this useful and am currently using `header_to_metadata` -> lua -> `jwt_authn`.

**Comment by qiwzhang** [comment]
Yes,  it will be a good feature to have.

**Comment by theshubhamp** [comment]
Great, I'll try it out and send a PR
