### ISSUE TITLE
Publish release tags to Dockerhub

### ISSUE THREAD

**Issue by bndw** [envoyproxy/envoy#1742]
It would be nice if there were tagged versions in Dockerhub for releases, in addition to the SHA tags. e.g. `lyft/envoy:v1.4.0`

**Comment by mattklein123** [comment]
Fixed thank you @bndw!

**Comment by andrewwebber** [comment]
It still seems difficult to find git tags against the docker hub. For example where is v1.7.0

https://github.com/envoyproxy/envoy/releases
https://hub.docker.com/r/envoyproxy/envoy-alpine/tags/

**Comment by bndw** [comment]
@andrewwebber Every release of Envoy has a corresponding Dockerhub tag, so just pull it by name:

```
docker pull envoyproxy/envoy:v1.7.0
```

Digging through the Dockerhub UI will prove difficult-- it doesn't have search and it only shows a subset of the most recent tags.

**Comment by andrewwebber** [comment]
My mistake, your correct, thanks!
