### ISSUE TITLE
Option to disable all lint analysis during a build

### ISSUE THREAD

**Issue by codefromthecrypt** [envoyproxy/envoy#17442]
*Title*: Option to disable all lint analysis during a build

*Description*:
Folks building from release tags could presume all lint related problems are addressed. It is likely that complete disabling of all static analysis would improve build perf and definitely less drift issues like #17428

*Relevant Links*:
Ex home-brew (os/x) recipe that took 8hrs to complete and lint problems took 5 hrs to fail https://github.com/Homebrew/homebrew-core/pull/81490

**Comment by htuch** [comment]
Having a fast build for developers iterating etc. without checks seems helpful, providing it is opt-in and isn't used in any supported builds by default.

I would not assume that all lint problems for all combinations of compilers/platforms/versions are addressed in a given release tag though :)

**Comment by htuch** [comment]
@ggreenway did you do a breakdown of how the compiler was spending its time when looking into Envoy build times?

**Comment by ggreenway** [comment]
Yes. I don't recall the exact data, but >50% of the time was spent on including headers, and the template instantiations necessary; I don't think any of that is included in analysis time, but I'm really sure how the compiler accounts for that.

**Comment by codefromthecrypt** [comment]
thanks for the context. there are really two independent reasons to allow this (and hopefully the work is less than the analysis in any case)

* allow a way for the build not to fail on lint. even outside the thing I mentioned I recall some getenvoy builds broken and no one knowing how to sort out the lint glitch caused by some drift. This is toil especially on a tag already released as it isn't going to become re-released. Ex any loops that are not so hot would stay that way. Meanwhile, allowing opt-out of linters lowers the bar for someone to later to succeed in building at all.
* much secondarily, is seeing if there's any build perf advantage to this.

A constant feedback I feel whether said out loud or not, is basically envoy is made for the "black t-shirt crowd" with a special set of skills, you can succeed at basic things. It would really help a lot to lean into making things like cutting a binary less likely to result in lost workweeks. This seems one of those things/
