### ISSUE TITLE
Fault injection documentation is misleading about TCP

### ISSUE THREAD

**Issue by donutmonger** [envoyproxy/envoy#17448]
The documentation for [extensions.filters.common.fault.v3.FaultDelay](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/common/fault/v3/fault.proto#extensions-filters-common-fault-v3-faultdelay) mentions that it can be used to "delay proxying of TCP connections"; but as far as I can tell, no such filter is implemented for TCP.

As far as I can tell it is a relic from https://github.com/envoyproxy/data-plane-api/pull/192 where TCP fault injection was [originally defined](https://github.com/envoyproxy/data-plane-api/pull/192/commits/ff6eeea4b9e701e5d9c1b3f0de6d9d21fde3247d#diff-212101a831bdee8f92f390e9df8314f2241bbdc6c20597f0405ddd309f63ce84R98-R113) (but dropped in a subsequent [commit in the PR](https://github.com/envoyproxy/data-plane-api/pull/192/commits/81186d76aa23226a2f403fce84efd2c5fb585855#diff-fbc61d824785edb992bf13e99819d7615909ef8217d2f842b620d927085cbaf2)).

I'm still kind of hoping I'm wrong about all of this :sweat_smile: but I think it is just a doc inconsistency.

**Comment by htuch** [comment]
This seems about right, @mattklein123 are there any known plans for TCP fault injection?

**Comment by mattklein123** [comment]
Yeah, I don't think generic level network fault exists today, though I don't think it would be hard to add. We have it for HTTP and Mongo today. Doc updates appreciated.

**Comment by mk46** [comment]
@mattklein123 I am taking look at this.
