### ISSUE TITLE
[HELP] compile_commands.json cannot work on standard library

### ISSUE THREAD

**Issue by tianxinheihei** [envoyproxy/envoy#17447]
After successfully building envoy on macos, I run tools/vscode/refresh_compdb.sh to generate  compile_commands.json, which generated commands like
{
    "command": "external/local_config_cc/wrapped_clang -D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG DEBUG_PREFIX_MAP_PWD=. -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=11.1 -std=c++17 -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -target x86_64-apple-macosx -D\"CARES_STATICLIB\" -D\"FMT_HEADER_ONLY\" -D\"SPDLOG_FMT_EXTERNAL\" -isystem external/com_github_fmtlib_fmt/include -isystem bazel-out/darwin-fastbuild/bin/external/com_github_fmtlib_fmt/include -isystem external/com_google_protobuf/src -isystem bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/src -isystem bazel-out/darwin-fastbuild/bin/external/envoy/bazel/foreign_cc/zlib/include -isystem external/com_github_gabime_spdlog/include -isystem bazel-out/darwin-fastbuild/bin/external/com_github_gabime_spdlog/include -isystem bazel-out/darwin-fastbuild/bin/external/envoy/bazel/foreign_cc/event/include -isystem external/com_github_jbeder_yaml_cpp/include -isystem bazel-out/darwin-fastbuild/bin/external/com_github_jbeder_yaml_cpp/include -isystem external/boringssl/src/include -isystem bazel-out/darwin-fastbuild/bin/external/boringssl/src/include -isystem bazel-out/darwin-fastbuild/bin/external/envoy/bazel/foreign_cc/ares/include -isystem external/com_github_circonus_labs_libcircllhist/src -isystem bazel-out/darwin-fastbuild/bin/external/com_github_circonus_labs_libcircllhist/src -isystem bazel-out/darwin-fastbuild/bin/external/envoy/bazel/foreign_cc/gperftools_build/include -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/any_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/descriptor_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/duration_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/empty_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/struct_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/timestamp_proto -I bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/wrappers_proto -I bazel-out/darwin-fastbuild/bin/source/common/common/_virtual_includes/logger_impl_lib_standard -I bazel-out/darwin-fastbuild/bin/source/common/common/_virtual_includes/thread_impl_lib_posix -I bazel-out/darwin-fastbuild/bin/source/common/event/_virtual_includes/dispatcher_lib -I bazel-out/darwin-fastbuild/bin/source/common/event/_virtual_includes/signal_impl_lib_posix -I bazel-out/darwin-fastbuild/bin/source/common/filesystem/_virtual_includes/watcher_lib -I bazel-out/darwin-fastbuild/bin/source/common/api/_virtual_includes/os_sys_calls_lib -I bazel-out/darwin-fastbuild/bin/source/common/filesystem/_virtual_includes/filesystem_impl_lib_posix -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/com_google_absl -iquote bazel-out/darwin-fastbuild/bin/external/com_google_absl -iquote external/com_github_fmtlib_fmt -iquote bazel-out/darwin-fastbuild/bin/external/com_github_fmtlib_fmt -iquote external/envoy_api -iquote bazel-out/darwin-fastbuild/bin/external/envoy_api -iquote external/com_google_googleapis -iquote bazel-out/darwin-fastbuild/bin/external/com_google_googleapis -iquote external/com_google_protobuf -iquote bazel-out/darwin-fastbuild/bin/external/com_google_protobuf -iquote external/com_envoyproxy_protoc_gen_validate -iquote bazel-out/darwin-fastbuild/bin/external/com_envoyproxy_protoc_gen_validate -iquote external/com_googlesource_code_re2 -iquote bazel-out/darwin-fastbuild/bin/external/com_googlesource_code_re2 -iquote external/com_github_cncf_udpa -iquote bazel-out/darwin-fastbuild/bin/external/com_github_cncf_udpa -iquote external/opencensus_proto -iquote bazel-out/darwin-fastbuild/bin/external/opencensus_proto -iquote external/com_github_gabime_spdlog -iquote bazel-out/darwin-fastbuild/bin/external/com_github_gabime_spdlog -iquote external/com_github_cyan4973_xxhash -iquote bazel-out/darwin-fastbuild/bin/external/com_github_cyan4973_xxhash -iquote external/com_github_jbeder_yaml_cpp -iquote bazel-out/darwin-fastbuild/bin/external/com_github_jbeder_yaml_cpp -iquote external/com_googlesource_googleurl -iquote bazel-out/darwin-fastbuild/bin/external/com_googlesource_googleurl -iquote external/boringssl -iquote bazel-out/darwin-fastbuild/bin/external/boringssl -iquote external/com_github_circonus_labs_libcircllhist -iquote bazel-out/darwin-fastbuild/bin/external/com_github_circonus_labs_libcircllhist -iquote external/envoy -iquote bazel-out/darwin-fastbuild/bin/external/envoy -Wall -Wextra -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -Wformat -Wformat-security -Wvla -Wno-deprecated-declarations -Wreturn-type -DGPERFTOOLS_TCMALLOC -DENVOY_HANDLE_SIGNALS -DENVOY_OBJECT_TRACE_ON_DUMP -D__APPLE_USE_RFC_3542 -DENVOY_ENABLE_QUIC -DENVOY_GOOGLE_GRPC -I /Applications -I /Library -I /Users/bytedance/Library -I /Applications/Xcode.app/Contents/Developer -I /Applications/Xcode12.app/Contents/Developer -x c++ -c tools/bootstrap2pb.cc",
    "directory": "tmp/_bazel_bytedance/b63b4b814b7aa085068de555ba49a36f/execroot/envoy",
    "file": "tools/bootstrap2pb.cc"
  },

however, vscode cannot find function defined in standard library, has error like 
{
	"resource": "envoy/source/server/active_raw_udp_listener_config.cc",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "pp_file_not_found",
	"severity": 8,
	"message": "In included file: 'cstdint' file not found",
	"source": "clang",
	"startLineNumber": 1,
	"startColumn": 10,
	"endLineNumber": 1,
	"endColumn": 58,
	"relatedInformation": [
		{
			"startLineNumber": 3,
			"startColumn": 10,
			"endLineNumber": 3,
			"endColumn": 19,
			"message": "Error occurred here",
			"resource": "envoy/network/connection_handler.h"
		}
	]
}

how to solve this problem?

**Comment by htuch** [comment]
@lizan do you know how to make this work on Mac? CC @ggreenway
