### ISSUE TITLE
How to enable I global ratelimit in typed_per_filter_config in route?

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#17456]
I want to enable a global ratelimit in route level.
I try like this ,but it doesn't work.
`

              routes:
              - match: { prefix: "/" }
                route:
                  cluster: some_service
                  rate_limits:
                  - actions:
                    - request_headers:
                        header_name: "Caller"
                        descriptor_key: "d-caller"
                    - source_cluster: {}
                    stage: 0
                  - actions:
                    - remote_address: {}
                    stage: 1
                typed_per_filter_config:
                  envoy.filters.http.ratelimit:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                    stage: 0
                    domain: caller-test
                    failure_mode_deny: true
                    request_type: external
                    timeout: 5s
                    rate_limit_service:
                      transport_api_version: V3
                      grpc_service:
                        envoy_grpc:
                          cluster_name: rls

`

**Comment by htuch** [comment]
Do you have the rate limit filter configured in the HTTP filter chain?

**Comment by pyrl247** [comment]
Yes,I have a stage 1 ratelimit in http filter chain

**Comment by htuch** [comment]
Not sure why you also have a stage 0 config on the route level then?

**Comment by qinggniq** [comment]
@kyessenov

**Comment by qinggniq** [comment]
AFAIK, you can not set the filter config in `typed_per_filter_config`, you can only set https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#extensions-filters-http-ratelimit-v3-ratelimitperroute in `typed_per_filter_config`.

**Comment by pyrl247** [comment]
I know , thx!!
