### ISSUE TITLE
How long does Envoy (arm64 version) start the first health check for a new endpoint?

### ISSUE THREAD

**Issue by ikingye** [envoyproxy/envoy#17461]
*Description*:

Envoy get the new endpoint from xds-server immediately.
But it takes about one minute to set the health_flag to `healthy` (query from [/clusters](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--clusters)), although the endpoint is healthy at the beginning.

It seems just the new endpoint strike first health check slowly.
When the endpoints are all healthy, I restart the envoy, and check the `/clusters`, all the health_flag are healthy (and that meets expectation).

[healthy_threshold](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#config-core-v3-healthcheck) is `1`

**Comment by htuch** [comment]
Might be helpful to share your config to understand in more detail.. In general, HC docs are at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking. Envoy should start health checking immediately when a new endpoint is assigned.

**Comment by moderation** [comment]
As per https://github.com/envoyproxy/envoy/issues/17313 make sure you are using 1.19.0 as this is the only release with the crypto performance improvements for aarch64
