### ISSUE TITLE
Is there a command to view the configuration of eds?

### ISSUE THREAD

**Issue by zhangzerui20** [envoyproxy/envoy#17476]
The configuration of endpoints cannot be found using `127.0.0.1:15000/config_dump`. Is there a command to see the configuration issued by eds?

**Comment by ramaraochavali** [comment]
config_dump?include_eds will give eds details

**Comment by htuch** [comment]
Also some of this information is available on the `/clusters` admin endpoint.

**Comment by zhangzerui20** [comment]
I got what I want through `config_dump?include_eds`
