### ISSUE TITLE
Problem with aarch64 for Jetson compiling, memory alignment issue

### ISSUE THREAD

**Issue by nimams** [envoyproxy/envoy#17478]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Cannot run the image binary on Jetson Xavier*

*Description*:
>I'm trying to run "envoyproxy/envoy-dev:9bdb13e831da2f3a1dfbd0ffb60e1be8aab681c9" or "envoyproxy/envoy:v1.19-latest". There is an issue with memory paging and alignment. It looks like the problem comes from "tcmalloc". I have seen there is a patch issued to address this issue: https://www.gitmemory.com/issue/envoyproxy/envoy/15235/850516622

*Repro steps*:
> You can try to pull the images mentioned above on Jetson Xavier and try to run them with this command:
```docker run --rm envoyproxy/envoy:v1.19-latest --version```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
> external/com_github_google_tcmalloc/tcmalloc/system-alloc.cc:550] MmapAligned() failed (size, alignment) 1073741824 1073741824 @ 0x5578d6a960 0x5578d5cc80 0x5578d5c6c0 0x5578d45ef0 0x5578d598f0
external/com_github_google_tcmalloc/tcmalloc/arena.cc:34] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 131072 48 @ 0x5578d6ac70 0x5578d45f6c 0x5578d598f0

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

If it is beneficial, I can grant access to the device. Also, I'm willing to help to apply the patch if I get the instruction on how I should apply the patch.

**Comment by htuch** [comment]
This looks like a dupe of https://github.com/envoyproxy/envoy/issues/15235, let's followup there.
