### ISSUE TITLE
block router update when during cluster warming

### ISSUE THREAD

**Issue by holooooo** [envoyproxy/envoy#17483]
*Title*: *block router update when during cluster warming*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

 In istio gateway, when virtual service update, it will push update by cds and rds.But new cluster is always stuck in warming status when router is ready. That cause request get 503 status code in response.

Can we add some block in cluster warming stage? Such as:
1. CDS recive full data. 
2. Block router update.
3. Find add and update clusters, and make them warming.
4. Unblock router update.Block cluster delete.
5. Router manager start handle new update.
6. Unblock cluster delete
7. delete old cluster

That can make sure router alway hava ready cluster to use, make less 503 UC status code

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/cluster_manager#cluster-warming

**Comment by lambdai** [comment]
That's reasonable for the virtual service caused CDS - RDS update. 

However, the reality is that CDS and RDS are not always coupled. There is no guarantee that CDS happens before RDS. 
You might also want the next RDS executed ASAP when there is a CDS config is never complete.

I add the NC error flag to indicate the the cluster is missing, which probably worth treated differently than other error code.
