### ISSUE TITLE
ext_authz: OkResponse.ResponseHeadersToAdd are always appended

### ISSUE THREAD

**Issue by theganyo** [envoyproxy/envoy#17494]
When returning ResponseHeadersToAdd on an OkHttpResponse from an ext_authz call using the Go library, the response headers are _always_ appended to the target's headers, regardless of the value of HeaderValueOptions.Append.

Note, too, that this is the opposite of the default claimed on the ResponseHeadersToAdd field:

https://github.com/envoyproxy/data-plane-api/blob/main/envoy/service/auth/v3/external_auth.proto#L102

**Comment by asraa** [comment]
Hmm seems to be the case that they are always `addCopy`d. @dio correct me if I'm wrong?

**Comment by dio** [comment]
I think we should have another "container" `Http::HeaderVector response_headers_to_set_{};`? So, when we receive `if (response->ok_response().response_headers_to_add_size() > 0)` we loop over the headers (options) and check for `header.append().value()`. We `authz_response->response_headers_to_add.emplace_back()` when `header.append().value()` and vice versa, emplace back to `authz_response->response_headers_to_set`. When encoding headers, we can have `if (!response_headers_to_set_.empty()) {` with `setCopy`.

**Comment by esmet** [comment]
@dio Yes that makes sense. I'm still not clear how the existing bug manifests itself as always appending instead of never appending, though. I think I don't yet understand how append defaults to true, given the proto comment.

**Comment by dio** [comment]
_I think I have a mistake in the Draft PR above (my mind was mixed up with something else)._ 

Since we always do `addCopy` when we have entries inside the `response_headers_to_add_` vector (set by the `onComplete` call, the `append` field value itself is ignored), hence it is always appended (not replaced).

**Comment by esmet** [comment]
I was previously under the assumption that addCopy (as opposed to appendCopy) only added non-existent headers and didn't append. Now that I read the HeaderMapImpl I see that's wrong, so now I need to understand the difference between these two 🤔

**Comment by dio** [comment]
I think in this case using `addCopy` is the right one when the `append` value (of a `HeaderValueOption`) is true. I'm not sure if we are encouraged to use `appendCopy` anymore. cc. @asraa.
