### ISSUE TITLE
Allow /healthcheck/fail from not admin webpage

### ISSUE THREAD

**Issue by stevesloka** [envoyproxy/envoy#17508]
*Title*: Allow the result of calling `/healthcheck/fail` but not from the Admin Webpage

*Description*:
I'd like a way to tell Envoy to begin draining connections and start shutting down, but not require the admin page to do this. Currently we have a related CVE in Contour (https://github.com/projectcontour/contour/security/advisories/GHSA-5ph6-qq5x-7jwc) due to this since you can create a Kubernetes Service type=ExternalName pointing to `localhost` which allow the admin webpage to be exposed. 

Contour has a way to enable a clean shutdown sequence (https://projectcontour.io/docs/v1.17.1/redeploy-envoy/) by first calling the `/healthcheck/fail` endpoint in Envoy and then polling for open connections. 

We also expose metrics on a new listener, so I can hide the rest of the admin functionality via that new listener. We're struggling with how to approach this. Our current solution is to disable externalName service but users want to use them for various different reasons. 

The ultimate goal would be if we could drop the admin webpage from running, then we'd be able to better manage this issue.

**Comment by mattklein123** [comment]
> I'd like a way to tell Envoy to begin draining connections and start shutting down, but not require the admin page to do this.

What do you suggest? I could see different somewhat hacky ways of doing this such as custom signals, watching some file, listening on a unix domain socket, etc., but it seems like the system using Envoy should be able to protect from such external attacks?

**Comment by sunjayBhatia** [comment]
Could be something in the runtime config? Might not be the right place since its not only configurable using the local filesystem, but using a file watch was what i thought of as well

**Comment by sunjayBhatia** [comment]
I think changing the Admin server to listen on a socket file shared between containers would work for us, havent tried it yet with the admin server listener

I see discussion in https://github.com/envoyproxy/envoy/issues/2763 about making the admin server use a fully fledged listener, which would also be quite nice to give us the flexibility to fix it

**Comment by mattklein123** [comment]
You should be able to change the admin config to use a unix domain socket today.

**Comment by sunjayBhatia** [comment]
I get a malformed IP address exception when trying to use a Pipe address type

https://github.com/envoyproxy/envoy/blob/9bd86b8ca194a49a304bba2ccba67a25b1bb53b2/source/server/admin/admin.cc#L120-L144 doesnt seem to allow it

if youre amenable to it, we can probably make the change to support it, seems simple as checking the requested address type and creating the correct listen socket type?

**Comment by mattklein123** [comment]
I'm pretty positive people run admin over UDS, so not sure exactly what problem you are facing. I would debug it and if there is an actual bug, sure please fix it.

**Comment by sunjayBhatia** [comment]
yep youre right, had a typo somewhere else! yeah that should hopefully work for us, if we can also have some documentation how to still get to the admin page cc @stevesloka

**Comment by dprotaso** [comment]
@sunjayBhatia you could exec into the container and suggest `curl

ie. 

```yaml
admin:
  address:
    pipe: {"path":"/envoyproxy.sock"}
```

```bash
curl --unix-socket /envoyproxy.sock  http://localhost:
```

Abstract sockets work too 

```yaml
admin:
  address:
    pipe: {"path":"@/envoyproxy/admin"}
```

```go
package main

import (
	"net/http"
	"net"
	"fmt"
	"context"
	"io/ioutil"
)

func main() {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.DialContext = func(_ context.Context, _, _ string) (net.Conn, error) {
		return net.Dial("unix", "@/envoyproxy/admin")
	}

	client := &http.Client{Transport: transport}
	resp, err := client.Get("http://@/envoyproxy/admin:")
	if err != nil {
		fmt.Println(err)
		return
	}

	defer resp.Body.Close()
	fmt.Println(resp.StatusCode)

	bytes, err := ioutil.ReadAll(resp.Body)
	fmt.Println(string(bytes), err)
}
```

**Comment by sunjayBhatia** [comment]
Only worried if we use abstract sockets if we ever enable envoy running on windows we will have to make another change but yeah we should def do this

**Comment by stevesloka** [comment]
I've got this working on a PR for Contour. I'll see if I can update docs in Envoy and also blog about it at least to explain the process if it helps anyone else out. =)

Thanks everyone for the help and input!
