### ISSUE TITLE
if upstream only have one host ,outlierdetection also remove the host from the health host list

### ISSUE THREAD

**Issue by du2016** [envoyproxy/envoy#17504]
*Title*: *One line description*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

in the doc,`max_ejection_percent mean The maximum % of an upstream cluster that can be ejected due to outlier detection. Defaults to 10% but will eject at least one host regardless of the value.`

i think if the upstream cluster only have one host,it should be keep in the health host list

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by asraa** [comment]
@snowp, does it seem reasonable to add a minimum host #?
