### ISSUE TITLE
Proposal: policy on handling bad commits

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#17507]
Occasionally committed PRs may introduce bugs that were not caught during review or CI. Presently such bad commits are fixed in the open if they are not older than 7 days. Older commits may be treated as CVEs if they introduce a security vulnerability.
However there is currently no policy on how tainted commit ranges are identified. Tainted commit range includes all commits, starting from the bad commit and up to the commit that fixes, or rolls back the bad commit (inclusive).
This presents a challenge for Envoy operators that deploy code from the main branch. Specifically when advancing the main branch internally there is currently no reliable way to tell if the internal main branch head is in the middle of a tainted commit range.

This proposal is to establish a policy on handling bad commits that would provide Envoy operators with a (more) reliable way of ensuring that internal main branch head is not broken. Specifically:

1. Ordinarily a bad commit is reverted.
2. The revert PR adds the following message: `Fixes bad commit #12345`
3. In some cases a commit may be infeasible to revert, such that it is in itself is critical to Envoy stability (i.e. security bug fix) or may require chain reverts that affect a significant portion of the code.
4. In this case a PR that fixes the problem will be applied.
5. An additional line is placed in the PR message: `Fixes bad commit #12345`

NOTE: this mechanism relies on internal main branch to be at least 7 days behind OSS main branch.

**Comment by yanavlasov** [comment]
@mattklein123 @lizan @alyssawilk

**Comment by ggreenway** [comment]
I think this policy makes sense. If we agree on it, we should add this exact text as an optional field in the PR template. Also, it should be clear whether the reference is a commit hash, PR number, or both.

**Comment by alyssawilk** [comment]
SGTM.  for ease of tooling do we want the Pr number for the commit, the hash or both?

optional nit,  I'd lean towards a simpler "fixes commit #12345" since I think the fact it was a bad commit is implicit from it needing to be fixed :-P

**Comment by mattklein123** [comment]
Sure SGTM in general. Let's make sure to clearly document this somewhere in addition to the PR template per @ggreenway

**Comment by yanavlasov** [comment]
PR # is I think easier. But tooling can really work with both.

**Comment by ggreenway** [comment]
First test run of the policy-in-progress: #17522
