### ISSUE TITLE
self define response message when use local ratelimit

### ISSUE THREAD

**Issue by du2016** [envoyproxy/envoy#17516]
*Title*: *One line description*
self define response message when use local ratelimit
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

some times when we migrate a service to envoy , we want consistent with business data format , so we should define rasponse message such as {code: 12345,message: "ratelimit"} and with a 200 http code ,not only return a reponse code(429),

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
See the local reply mapper feature which should handle this.
