### ISSUE TITLE
Document max_connection_duration in the timeouts faq

### ISSUE THREAD

**Issue by jamessynge** [envoyproxy/envoy#17525]
Reading through the HTTP Connection Manager code, I can get reasonable idea of how `max_connection_duration` is used, but I'm not certain I've got all the subtleties. It would be helpful if someone that understands this feature, and how it interacts with the other limits (e.g. `delayed_close_timeout`), could update the [timeouts faq](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts.html) with more details.

For context, my goal is to prompt clients to reconnect to a pool of auto-scaling Envoy proxies periodically in order to get a better distribution of traffic across that pool of proxies as the size or membership of the pool changes. I'm trying to understand whether I can configure Envoy to send GOAWAY messages (or "Connection: close" on HTTP/1.x connections) after a certain time, without breaking in-flight requests, ideally even if those requests are hanging GETs.

**Comment by agrawroh** [comment]
I also had some question on how the inflight requests are getting handled etc. when we have `max_connection_duration` defined and looked at the code to understand a little more. I clarified the docs and also added a section in the Timeout FAQs here: https://github.com/envoyproxy/envoy/pull/18193

**Comment by jamessynge** [comment]
Thanks @agrawroh.
