### ISSUE TITLE
UI for configuration

### ISSUE THREAD

**Issue by GregorBiswanger** [envoyproxy/envoy#17526]
The **configuration** in Envoy is a **disaster**. I often waste hours getting something working.

Please extend the Admin UI for a simpler configuration.

**Comment by phlax** [comment]
> The configuration in Envoy is a disaster.

Hi @GregorBiswanger sorry you have had a bad experience getting things set up

we are working to simplify the configuration and add defaults where we can - and improve the documentation - but this takes time, and Envoy has to meet some very complex set ups - so at least to some extent it is necessarily complex

there are a number of third-party tools that help you configuring Envoy (too many to mention) both as an edge proxy and as part of a service mesh

for that reason Envoy is unlikely to add a UI to the core server

beyond uis and addons, i would suggest working through the quick-start section of the docs, and as many sandbox tutorials as you have time for, these demonstrate a lot of the core patterns

**Comment by GregorBiswanger** [comment]
@phlax Thank you for your quick response!

Can you recommend a free third-party tool that I can only do the configuration with?

**Comment by mattklein123** [comment]
> The configuration in Envoy is a disaster. I often waste hours getting something working.

For starters, when asking for help with an OSS project that is run by volunteers, I would recommend engaging in more constructive dialog.

> Can you recommend a free third-party tool that I can only do the configuration with?

Your query does not have enough information on what you are trying to do. If the existing documentation does not work for you I would ask specific questions, submit improvements, or look for higher layer products that are better suited to your needs (Istio, Ambassador, Gloo, Consul connect, etc, etc.)

**Comment by GregorBiswanger** [comment]
@mattklein123 Sorry if my message sounds offensive. I was just very frustrated.

What can definitely help would be a JSON schema. This can also be used with YAML. IDEs support it wonderfully and you then get a wonderful guide to the possibilities of envoy.

**Comment by mattklein123** [comment]
> What can definitely help would be a JSON schema.

We use protobuf which is stronger than JSON schema. See https://github.com/envoyproxy/envoy/issues/13078 for efforts to build a vscode extension for Envoy configuration. Help appreciated!
