### ISSUE TITLE
Implementation status of async mode in ext_proc filter

### ISSUE THREAD

**Issue by taehioum** [envoyproxy/envoy#17532]
Hi, I would like to ask if async_mode is (or planned to be) implemented in ext_proc filter.

Although

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto#extensions-filters-http-ext-proc-v3alpha-externalprocessor

doesn't list ```async_mode``` as a valid config, envoy seems to accept it as a valid configuration, as adding it doesn't lead to failure during the bootstrapping process. (Although adding it didn't change the way ext_proc filter operates)

The ```message_timeout``` also mentions that 'There is no timeout when the filter is running in asynchronous mode.', and service.ext_proc.v3alpha.ProcessingRequest contains an ```async_mode``` field, so I was wondering if ext_proc can run in async mode as of now, or the related fields / descriptions were added in advance.

Thanks!

**Comment by gbrail** [comment]
It's not implemented yet (which is why it's marked "not-implemented-hide" in the docs). A PR currently in the queue updates the docs a bit that I think will more clearly show this.

**Comment by taehioum** [comment]
@gbrail Thanks for the clarification :)
