### ISSUE TITLE
Adopt absl common libraries

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1754]
Google's common C++ libraries are now OSS: https://github.com/abseil/abseil-cpp. This a lightweight alternative to something like Boost which can replace existing adhoc utils such as string join/split with standard implementations.

This issue will track a proposal to:
1. Add absl as an external dependency to Envoy (it already has Bazel support).
2. Replace existing implementation of duplicate functionality with absl alternatives. Places to look at include `common/common/utility.h`, `Optional`, mutexes, `make_unique`, (others?)
3. Use absl utilities going forward.

**Comment by mattklein123** [comment]
@htuch are there any API docs? I can't find any? Or should I just browse the source?

**Comment by htuch** [comment]
https://abseil.io/docs/

**Comment by mattklein123** [comment]
I took a brief look through and the code looks sane and not Boost like to me so no objections from me. I have a small preference to wait until there is a thing we really want to use from here (string view sounds pretty useful, not sure what else there is), but not a big deal.

**Comment by ggreenway** [comment]
I looked at some of the thread annotations, and it would allow annotating the lock-ordering I committed yesterday, and it looks like clang would warn if the order is violated, so that would be useful (https://github.com/envoyproxy/envoy/blob/c52afae2f54ebc5dddc545300d030e9d1e41349c/source/common/filesystem/filesystem_impl.h#L97)

**Comment by mattklein123** [comment]
I looked at the annotation stuff very briefly. How does that work? Does clang have pluggable annotations? Or these are annotations already implemented by clang?

**Comment by ggreenway** [comment]
There's some nifty stuff built into clang: https://clang.llvm.org/docs/ThreadSafetyAnalysis.html

abseil adds macros for using it, and has the appropriate checks for if the compiler supports the annotations.

**Comment by mattklein123** [comment]
Cool that's pretty neat. SGTM.

**Comment by mattklein123** [comment]
This is done. We can start using ABSL now.
