### ISSUE TITLE
Asking for a way to debug 502/Bad Gateway errors

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [envoyproxy/envoy#17559]
*Description*:
I'm running `envoy` as a gateway service on `Azure` k8s cluster for an application. The high level architecture of my setup can be depicted in the following diagram.
![MGW simple architecture](https://user-images.githubusercontent.com/17524063/127780113-1fc9e3cc-d213-4833-b939-efd895d1c01a.png)

Arrows with numbers are used to show the path that the request is going through. Following are the details of my k8s setup.

> Envoy container resource allocations:
> ```
> limits:
>       cpu: '2'
>       memory: 4Gi
> requests:
>       cpu: '2'
>       memory: 4Gi
> ```
> There were 6 replicas of envoy containers running.

Envoy base image used : https://hub.docker.com/layers/envoyproxy/envoy-alpine/v1.18.2/images/sha256-daf6afad80c4c10465b734df81f47a168c1d868b1c9e458f46f1d1f2c2727f2a?context=explore

I ran a perf test for this application using Jmeter, with relatively high concurrency (i.e. ~ 10000 threads) and got about 9 % of intermittent `502/Bad Gateway` errors. When I investigating on these errors I found following error logs in my `Nginx Ingress Controller`'s (referring the nginx ingress controller from above diagram) stderr logs.

> 2021/07/19 07:02:02 [error] 1597#1597: *318696 connect() failed (111: Connection refused) while connecting to upstream,
> 2021/07/19 07:01:55 [error] 1765#1765: *565821 connect() failed (104: Connection reset by peer) while connecting to upstream,
> 2021/07/19 07:11:32 [error] 1765#1765: *564969 peer closed connection in SSL handshake while SSL handshaking to upstream,
> 2021/07/19 07:00:25 [error] 1765#1765: *568648 upstream prematurely closed connection while reading response header from upstream,

I didn't see any access logs or error log entries in `Envoy` containers, corresponding to the above errors. 

As per my understanding, these errors are coming due to failure of step (2) connection (connection from Nginx Ingress Controller to Envoy service) of the above diagram. 

> Note: The above mentioned errors are coming only under a high load (i.e. when running the perf test) and the above setup is totally working fine in normal use (without high loads).

Is there any reason or known issue in `Envoy` side regarding this or is there a way to troubleshoot and find the exact reason for this from `Envoy` side??

**Comment by Rajith90** [comment]
It seems like envoy does not accept some requests from nginx under high load, it would be really helpful if we can get some direction on how to debug this or tune parameters in the envoy to handle these loads

**Comment by cobb-tx** [comment]
I'm having the same problem
