### ISSUE TITLE
Limit max active connections to a TCP listener

### ISSUE THREAD

**Issue by prateek0394** [envoyproxy/envoy#17561]
*Title*: *Limit max active connections to a TCP listener*

*Description*:
>I am looking for a way to limit maximum active connection counts to a TCP listener of Envoy. This is to ensure proxy do not burnout self with increasing traffic. I tried looking for this but couldnt find anything which can help in configuring this. 

Closest discussion I found to this has here : https://github.com/envoyproxy/envoy/issues/2920

Any leads would be really appreciated. Thanks.

**Comment by prateek0394** [comment]
This is definitely one of the solutions to do so. 
https://www.envoyproxy.io/docs/envoy/v1.15.2/configuration/operations/overload_manager/overload_manager#config-overload-manager

Please let me know if there are any other alternatives

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/connection_limit_filter
