### ISSUE TITLE
Attempting to limit response size using Content-Length and lua filter

### ISSUE THREAD

**Issue by swav** [envoyproxy/envoy#17607]
I have a follow up to the question raised originally: (https://github.com/envoyproxy/envoy/issues/17340). 

I have implemented lua on_response filter to read value of Content-Length response header and if it exceeds some predefined value, in my case 1 MiB, to write new response body with an error message and 502 response status.
I have also added per_connection_buffer_limit_bytes: 3145728 on listener level.

This works as expected, responses sized below 1MiB go through, response sizes over 1 MiB get 'pre-empted' by my script like this:

if errMsg ~= nil then
  local content_length = response_handle:body():setBytes(errMsg)
  response_handle:headers():replace("content-length", content_length)
  response_handle:headers():add("Proxy-Status", "http_response_body_size")
  response_handle:headers():replace(":status", 502)
end

but if I attempt to request an image file which will exceed 3 MiB in size (value set in per_connection_buffer_limit_bytes on listener), I receive a 500 status code in response and not 502 and my 'Proxy-Status' header is also gone.
The log shows this: Sending local reply with details response_payload_too_large directly to the encoder

There is also 'per_connection_buffer_limit_bytes' setting on cluster level, but I found out that setting it there and not on listener level has no effect at all.

This brings me to these questions:

1. Why is my 502 status code lost and only 500 status returned when response size is larger than 3 MiB? This 'kind of' renders my lua script only partially useful, in that I can return 502 only in cases where response size is over my lua script limit but below per_connection_buffer_limit_bytes.
2. What is the relationship between per_connection_buffer_limit_bytes set on cluster level vs on listener level? Ideally I would prefer to have a different setting on the cluster level because listener is more global, vs the cluster is specific and ends up getting responses from a very specific route.
[envoy-config-host-rewrite-1.18.3.txt](https://github.com/envoyproxy/envoy/files/6939996/envoy-config-host-rewrite-1.18.3.txt)

I've attached my envoy config yaml (as txt) file, the lua filter dealing with response size is: responselimit.lua, which can be used with envoy 1.18.3 docker image started using this script (renamed to .txt to copy it here)
[run-envoy-1.18.3.txt](https://github.com/envoyproxy/envoy/files/6940022/run-envoy-1.18.3.txt)
and running these curl commands (various image files, under 1MiB, between 1 and 3 MiB and over 3 Mib 
[curl-get-image-local.txt](https://github.com/envoyproxy/envoy/files/6940036/curl-get-image-local.txt)

Thanks, in advance,
Swav

**Comment by swav** [comment]
I think I understand why I'm causing response_payload_too_large error. Re-reading the docs (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#): 
handle:body() 
"Returns the stream’s body. This call will cause Envoy to suspend execution of the script until the entire body has been received in a buffer." And this can exceed buffer size set in listener per_connection_buffer_limit_bytes, hence 500 error.

So I read the second part of the docs dealing with handle:bodyChunks(): 
"Returns an iterator that can be used to iterate through all received body chunks as they arrive. Envoy will suspend executing the script in between chunks, but will not buffer them. "
...and this offers alternative solution to iterate over each chunk and set it to empty string, like the docs show. This works fine, that is I get back my 502 and the body has my error message, but the problem that I'm seeing is that I'm still iterating through every chunk of the response to null it all out. So if my response is 15 MiB and my lua filter limit is 1 MiB, I will still be iterating through all chunks of the body to set them to empty, which is wasteful and makes the script wait till the end of the original body is reached. 
How can I improve this? Ideally, I'd like to:
a) set the response body to contain few bytes of error message
b) replace status header with 502 
to be done with it without iterating entire response body only to throw it out.

**Comment by yanavlasov** [comment]
@dio for any suggestion on how to abort response early from a lua filer.
