### ISSUE TITLE
Number of stats and length of stat name should be configurable

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#1761]
Envoy currently hardcodes a limit of 16k individual stats, with a fixed maximum name length.  These values should be tunable.

**Comment by mattklein123** [comment]
+1

**Comment by ggreenway** [comment]
Defaults should be settable at compile-time via .bazelrc (or similar), and overridable via CLI flag at startup.

**Comment by htuch** [comment]
@hennna

**Comment by mattklein123** [comment]
> It is easy to make finding unused stats O(1) with a free-list or similar. But doing the name-lookups is a little bit harder in shared memory. We'll probably need a lookup table of some kind in the shared memory.

If we want to do this, I would recommend doing it as a totally independent change from the length stuff. Given how low frequency stat allocation is from shared memory the current situation is probably not that big of a deal for most people.

**Comment by ggreenway** [comment]
I was going to benchmark filling up a somewhat big number of stats, maybe 1M or something, and see how long it takes.  That should simulate the worst likely-case, which is startup with a large configuration.  But I'm expecting that would be pretty slow: n^2 is 1 trillion operations.  

But I agree that it can be done in a separate change.  Making the sizes tunable won't cause any degradation to existing use cases unless users opt-in to a really large stat size, and they should immediately notice some pain on startup if they choose too-large of a size.
