### ISSUE TITLE
How to pass metadata_context into requests to the ext_authz service?

### ISSUE THREAD

**Issue by erir910** [envoyproxy/envoy#17628]
Hi Envoy authors. I have been trying for hours to pass metadata from the Envoy instance to the gRPC external authorization service (both network and http) using the `Check()` method request argument which contains `metadata_context` as shown in th [docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto.html). I've tried to inject the metadata into the `listener.metadata` field from the envoy instance but it never works and the metadata is always empty inside the ext_authz service request. What am I doing wrong?

**Comment by esmet** [comment]
Hi @erir910 

If your use case is to add static configuration to `listener.metadata` and then use that from within the external authorization service, I think you may want to look at `context_extensions` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto.html#service-auth-v3-attributecontext

You can then set per-route config similar to how the Emissary Ingress (formerly Ambassador) does it https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto.html#service-auth-v3-attributecontext

Let me know if that doesn't make sense or fit the use case you're describing.
