### ISSUE TITLE
How to control frequency of metrics emission

### ISSUE THREAD

**Issue by shalako** [envoyproxy/envoy#1762]
Looking at docs like: https://envoyproxy.github.io/envoy/configuration/cluster_manager/cluster_stats.html

I can't tell how often each metric is emitted. My hope is no metric is emitted on each request (as this will overwhelm aggregation and visualization systems), and that the frequency with which they are emitted is configurable, but I haven't figured out how.

If all metrics are emitted on a periodic frequency, I would be concerned that timers might be averaged over the period instead of being emitted as percentiles. I haven't found any metrics with names indicating their values are percentiles. Response time / latency being of most interest.

Thank you!

**Comment by mattklein123** [comment]
Please see this blog post for how stats currently work: https://medium.com/@mattklein123/envoy-stats-b65c7f363342

The stat flush interval is configurable. See: https://envoyproxy.github.io/envoy/configuration/overview/overview.html

**Comment by mattklein123** [comment]
Closing this out. Please reopen if you have further questions.
