### ISSUE TITLE
Current state of adaptive concurrency filter

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#17647]
Hello folks,
I see the adaptive concurrency filter is in the [experimental](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/adaptive_concurrency_filter.html?highlight=envoy%20filters%20http%20adaptive_concurrency) state. We are planning to use it in production, so I'm wondering if there is any concern using it production. If there is no, should we move the state to stable (or at least beta)? 

Thanks!

**Comment by ggreenway** [comment]
cc @tonya11en @mattklein123

**Comment by mattklein123** [comment]
We don't have good criteria of when filters are unmarked from being experimental. In general it's fuzzy matching around how many people we know are using it in production. For adaptive concurrency I don't have any concerns about using it in production, but nor do I know a lot of concrete stories about doing so, so I don't think it makes sense to remove it. 

So please use it in production and report back!

**Comment by hochuenw-dd** [comment]
@mattklein123 sure. will do 👍

**Comment by ramaraochavali** [comment]
@hochuenw-dd Sorry to tag you on old issue but wanted to check with you if have you used it in prod and if yes, can you please share your experience?

@tonya11en If you have any data usage in prod - can you please share as well?

**Comment by tonya11en** [comment]
This was deployed at Lyft ~2020 and I no longer work there, so I unfortunately can't share any data.
