### ISSUE TITLE
Build fails with updated wasmtime

### ISSUE THREAD

**Issue by rahulchaphalkar** [envoyproxy/envoy#17646]
*Title*: *Updating to wasmtime 0.27.0 or higher results in build errors*

*Description*:
>Envoy currently builds for wasmtime 0.26.0, as can be [seen here](https://github.com/envoyproxy/envoy/blob/af94f9ffefce4f9c25d4d3ae88a2bb02ab7beb2c/bazel/repository_locations.bzl#L733). I wanted to try out a more recent wasmtime (which is up to 0.29.0 now), so tried 0.27.0 by changing the `version` to 0.27.0 and `sha256` to the appropriate sha `68aef150d3b0ac93e30cd797eac397852ac35a6e809bfa1d759af70177ebf659`. However, while building envoy, the build was interrupted by build errors like this -
```
ERROR: /home/user/.cache/bazel/_bazel_user/66af1bc4ca7e16b0c8ff4e2f9bac0d80/external/com_github_wasmtime/BUILD.bazel:16:13: Compiling Rust staticlib rust_c_api (30 files) failed: (Exit 1): process_wrapper failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper --subst 'pwd=${pwd}' -- external/rust_linux_x86_64/bin/rustc ... (remaining 105 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
error[E0599]: no method named `ok` found for struct `wasmtime::Memory` in the current scope
  --> external/com_github_wasmtime/crates/c-api/src/memory.rs:35:64
   |
35 |     let memory = Memory::new(&store.store, mt.ty().ty.clone()).ok()?;
   |                                                                ^^ method not found in `wasmtime::Memory`

error[E0599]: no function or associated item named `deserialize` found for struct `wasmtime::Module` in the current scope
   --> external/com_github_wasmtime/crates/c-api/src/module.rs:189:26
    |
189 |         unsafe { Module::deserialize(&engine.engine, binary.as_slice()) },
    |                          ^^^^^^^^^^^
    |                          |
    |                          function or associated item not found in `wasmtime::Module`
    |                          help: there is an associated function with a similar name: `serialize`

error: aborting due to 2 previous errors
```
I saw build errors for more recent wasmtime versions as well. Is there something else I'm not updating when going from 0.26.0 to newer?

**Comment by ggreenway** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
You need to update `wasm-c-api` to a matching version.

**Comment by rahulchaphalkar** [comment]
Yes, I checked, but the latest wasm-c-api version (commit) is the same one used for wasmtime 0.25.0 . Wasm-c-api latest commit i see is `c9d31284651b975f05ac27cee0bab1377560b87e` in Jan of this year.

**Comment by PiotrSikora** [comment]
Did you update Wasmtime in Proxy-Wasm C++ Host as well?

**Comment by rahulchaphalkar** [comment]
Ah I haven't! Let me try that out. Thanks!

**Comment by PiotrSikora** [comment]
@rahulchaphalkar if you get it working, PRs would be appreciated. Thanks!

**Comment by rahulchaphalkar** [comment]
After updating proxy-wasm-cpp to a newer wasmtime, i was able to build with newest wasmtime 0.29.0 . Closing the issue, thanks.
