### ISSUE TITLE
Route UDP packets to different upstreams based on origin IP

### ISSUE THREAD

**Issue by msiemens** [envoyproxy/envoy#17652]
I want to be able to route UDP packets to different upstreams based on the packet's origin IP. With TCP this can be accomplished using `filter_chain_match`'s [`source_prefix_ranges`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchainmatch), but as far as I can tell, filter chains cannot be applied to UDP listeners. It would be great to be able to have some sort of mechanism to achieve this with UDP, too.

**Comment by lambdai** [comment]
The mode is different among TCP and UDP.

Filter chain match execution is applied at the very begin of the tcp connection(think it at the first tcp packet), and all the rest of the data of that tcp connection reuse the chain selection.
What's more, you can specify different downstream network filters for different tcp connections.

For UDP, the decision has to be made for each packet. And, at this moment, the downstream udp filters are not that resourceful. I am wondering if you demand a original-ip-based UDP *loadbalancer* to select a upstream endpoint.

**Comment by msiemens** [comment]
> I am wondering if you demand a original-ip-based UDP _loadbalancer_ to select a upstream endpoint.

Yes, that's bascially right. But I understand that this might not be in scope for Envoy and would understand if this won't be implemented :)

The reason for opening this issue is that in the project I work on, we need to route UDP packets based on origin IP (as I mentioned). When researching for possible solutions I found that NGINX does seem to support this by using UDP load balancer along with the [map module](http://nginx.org/en/docs/http/ngx_http_map_module.html) for the routing part (although I haven't concluded my tests yet). And with some folks recommending Envoy as an alternative to NGINX I wondered if this could be achieved with Envoy too.

**Comment by mattklein123** [comment]
I think this is something we could look at adding (some type of basic route table within the UDP filter) but it would need to be specified and implemented. There is no way to do this today.

**Comment by zhxie** [comment]
I would like to take a try adding routing option for UDP proxy filter.
