### ISSUE TITLE
[route] Create route-table level typed_per_filter_config for "global" route config. 

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#17662]
*Title*: Create route-table level typed_per_filter_config for "global"/route-table-wide route config. 

*Description*:
We have this use cases where we want to store some "global" per-filter route config, the current available locations are vHost or per-route-entry per_filter_typed_config, we'd hope that the same data structure is available at higher level, e.g. at RouteConfiguration level for the "global" route config, which would reduce the data redundancy due to missing such top-level config container.

**Comment by stevenzzzz** [comment]
cc @htuch @yanavlasov @AndresGuedez

**Comment by mattklein123** [comment]
I agree this would be a nice addition.

**Comment by htuch** [comment]
+1 makes sense to me (and this will be a known win for real use case we have).

**Comment by mattklein123** [comment]
I do want to call out that we have to be vary careful when we add this feature, as we have had some recent issues around code not correctly respecting the various levels of typed filter config. See for example https://github.com/envoyproxy/envoy/pull/17546 and https://github.com/envoyproxy/envoy/pull/17449. cc @soulxu

**Comment by soulxu** [comment]
> I do want to call out that we have to be vary careful when we add this feature, as we have had some recent issues around code not correctly respecting the various levels of typed filter config. See for example #17546 and #17449. cc @soulxu

Yea, good news is we probably just need to ensure the `mostSpecificPerFilterConfig` and `traversePerFilterConfig` method works with global route config.

https://github.com/envoyproxy/envoy/blob/5b4bad85bd7adb923cf25dd319f8f3f45b7c2670/envoy/router/router.h#L1012-L1027
