### ISSUE TITLE
A customized tcp filter cannot use hashpolicy

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#17670]
hi，i have some questions about the tcp_proxy filter
i make my customized tcp distribution filter follow tcp_proxy filter.
This filter is to distribute msg to different upstream according to tcp's data.
1、decode tcp data first to get the **cluster name**.
2、use the **cluster name** to distribute to  clusters according to _hash policy of tcp_proxy_.
i realize the 1 and the data can reach to the specified cluster,but the hash policy not effective.
my filter is different from tcp_proxy is in initializeUpstreamConnection(),i don't use pickRoute(),and use the cluster name as the variable for  cluster_manager_.getThreadLocalCluster.
i don't understand if the pickRoute control the lb policy.
![image](https://user-images.githubusercontent.com/36953705/129017509-2d91ab39-2ee4-433d-8f5a-6d261bc266f8.png)

**Comment by ggreenway** [comment]
tcp_proxy is inteded to be a terminal filter (the last filter in the chain). No filters should come after it.

If you want to have another filter choose which cluster should be routed to, you should add a network filter before tcp_proxy in the chain. That network filter can do something similar to the `sni_cluster` filter to instruct tcp_proxy which cluster to use: 
```
  if (!sni.empty()) {
    // Set the tcp_proxy cluster to the same value as SNI. The data is mutable to allow
    // other filters to change it.
    read_callbacks_->connection().streamInfo().filterState()->setData(
        TcpProxy::PerConnectionCluster::key(),
        std::make_unique<TcpProxy::PerConnectionCluster>(sni),
        StreamInfo::FilterState::StateType::Mutable, StreamInfo::FilterState::LifeSpan::Connection);
  }
```

**Comment by hbgongen** [comment]
oh...thanks for this opinion,i also want to know **read_callbacks_->connection().streamInfo().filterState()**,this function getData or setData,i want to know this class FilterState is actually a container to store some certain object which can use during all the filterchain or the whole connection.

**Comment by hbgongen** [comment]
I have successfully solved it, thanks @ggreenway
