### ISSUE TITLE
Support multiple accounts for the 'aws_request_signing' filter

### ISSUE THREAD

**Issue by dragoscalinescu** [envoyproxy/envoy#17672]
I'm facing a use case where one envoy needs to handle traffic for multiple AWS accounts, for which I have the access and secret keys pairs.
I don't want to create a new envoy instance for each account.

There doesn't seem to be a way to achieve this currently in envoy. Access and secret keys are read from the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env vars, so this can only fit one account.

I believe there should be a way to specify these secrets per cluster configuration (through different env vars / files / .. )

**Comment by ggreenway** [comment]
cc @rgs1 @derekargueta @marcomagdy @tonya11en

**Comment by rgs1** [comment]
One way of doing this could be:

a) the secrets – key id & access key – would be available in SDS 
b) we could then have the filter read the SDS config name for the key pair it needs to use from the matched route entry or upstream cluster (e.g.: using metadata)
c) signing happens with the retrieved pair
