### ISSUE TITLE
TEST_P(XfccIntegrationTest, TagExtractedNameGenerationTest) has lots of stale test cases

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#17687]
This test contains a list of stat names to check how they are tag extracted. While making a small change to this test, I noticed that many of the elements in the list are never checked at all (I think the count was 174). 

This test should be cleaned up to reflect current stats that are emitted, and then modified so that un-tested cases make the test fail, so that it doesn't become stale in the future.

**Comment by ggreenway** [comment]
cc @jmarantz

**Comment by ankatare** [comment]
@ggreenway can you elaborate it more. I would like to understand and work on this

**Comment by ggreenway** [comment]
If you look at the test, there's a big list of cases to test. Many of them are unintentionally not hit at all, due to changes to stats over the years since the test was written.

I think the test should keep track of which cases have been hit, and fail at the end of the test if any case has not been hit. Anytime a case isn't hit, it probably means that someone made some change to stats, and a corresponding change in this test is needed also.

**Comment by ankatare** [comment]
@ggreenway Thanks for explaining it. Let me understand it , will get back for any doubts.
