### ISSUE TITLE
Certificate and Key mismatch leading to continuous logging by envoy-proxy

### ISSUE THREAD

**Issue by harshaagrahara** [envoyproxy/envoy#17693]
*Title*: Certificate and Key mismatch leading to continuous logging by envoy-proxy

*Description*:
When a wrong key for a certificate is passed to envoy-proxy, it is continuously logging the below message:

gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) https_listener: Failed to load private key from <inline>, Cause: error:0b000074:X.509 certificate routines:OPENSSL_internal:KEY_VALUES_MISMATCH

**Is there a way to suppress this (or any) message to certain number of times (say 3 or 5), rather than continuously logging it?**

*Repro steps*:
Pass incorrect key and certificate pair to envoy-proxy.

**Comment by ggreenway** [comment]
That message is logged once each time updating the listener config fails due to the key mismatch. I'm not sure why your listener config is being continuously. How are you configuring envoy? Are you using LDS or SDS?
