### ISSUE TITLE
The connection between envoys is slow.

### ISSUE THREAD

**Issue by holooooo** [envoyproxy/envoy#17694]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:  The connection between envoys is slow

*Description*:
The connection time between envoys is unstable. In most time, it use 1,2 ms.But somtime it will rise to hundreds ms.

It only happen in both pod injected envoy sidecar.How can I check where is real question on?

[full.log](https://github.com/envoyproxy/envoy/files/6974006/full.log)

**Comment by rojkov** [comment]
This is a very broad topic. There could be many reasons. Probably you could start with collecting more data on e.g. what process makes syscalls that take too long (`perf trace --duration 100`).

**Comment by holooooo** [comment]
thx lot!!After eliminating a large number of possible causes，we found is physic network interface trouble.Now envoy is fast again
