### ISSUE TITLE
how can I skip wee8 during building?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#17705]
hello, wasm will not be used in my enviroment, is there any way to disabled the wee8 during building?

**Comment by moderation** [comment]
Following the directions at https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#enabling-and-disabling-extensions I disable WASM with the following in my `~/.bazelrc` file

`build --define wasm=disabled`

**Comment by zirain** [comment]
@rojkov ths, the code works.
