### ISSUE TITLE
Not showing deprecation warnings for boosted protos

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#17706]
It turns out we still attempt to do API boosting in many cases, including bootstrap. This causes protos to load as v2, and once that happens, we miss out on important things like deprecation warnings as the field(s) are not deprecated in v2. This might also apply to PGV validation but I haven't checked that.

After discussing with @htuch we think it would be best to just remove boosting entirely. This might require fixing some tests along the way. If it turns out this is going to take a long time we could potentially:
1) Change the default for do_boosting to false for all functions that support it and audit all prod code to make sure it stays false.
2) Hardcode bootstrap version to 3 and fail if it's set to anything else. (We might still want to do this.)

**Comment by mattklein123** [comment]
cc https://github.com/envoyproxy/envoy/issues/10943

**Comment by davinci26** [comment]
See https://github.com/envoyproxy/envoy/issues/15559
