### ISSUE TITLE
Why the status always set to 200 when respond with a gRPC trailers-only scenario

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#17707]
*Title*: *Why the response status always set to 200 when respond with a gRPC trailers-only scenario*

*Description*:
Why is the response status always set to 200 when respond with a gRPC trailers-only scenario ?
https://github.com/envoyproxy/envoy/blob/95038feabf260c3937465951d5da603d31ea3bd4/source/common/http/utility.cc#L538-L548

**Comment by ggreenway** [comment]
The gRPC spec states that responses should be http-200, and use grpc-specific headers for the actual grpc status.
