### ISSUE TITLE
Actually deprecate use_proxy_proto

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#17703]
https://github.com/envoyproxy/envoy/blob/0ab463fe054de02786b2de24a17206b14b12c01d/api/envoy/config/listener/v3/listener_components.proto#L242-L243

Has been deprecated for quite some time, but no warning or deprecation stat is emitted.

After the removal of tls inspector auto injection in https://github.com/envoyproxy/envoy/pull/17373 this becomes particularly bad, because proxy proto now gets auto injected after manual listener filters which is almost definitely wrong.

We need to complete this deprecation first by warning on this field's use and emitting a deprecated stat, and then actually removing support for it entirely.

cc @ggreenway @tbarrella @lambdai

**Comment by ggreenway** [comment]
Why isn't a stat or warning emitted? I thought that was handled by the config loading infrastructure.

**Comment by mattklein123** [comment]
> Why isn't a stat or warning emitted? I thought that was handled by the config loading infrastructure.

Oh hmm, yeah, I think you are right, it should be. Let me check on this.

**Comment by mattklein123** [comment]
There is no warning printed when used as part of a static listener in bootstrap, though I think there should be. I'm trying to figure out what is going on.

**Comment by mattklein123** [comment]
https://github.com/envoyproxy/envoy/issues/17706 is the warning issue.

I'm still going to add a next warning for this case since it's extra bad and now that we aren't cleaning up deprecated fields very fast people might ignore it.
