### ISSUE TITLE
Have Envoy support a NULL-DNS resolver type

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#17715]
Have Envoy support a new DNS resolver type: NULL-DNS resolver, which don't do DNS resolving at all.

*Description*:
Currently Envoy support two DNS resolver types: cares and apple.  Can we add a NULL-DNS resolver type, which if configured,  the Envoy code won't perform any DNS resolving at all.
With the effort of "Refactoring Envoy DNS resolution as extension #17479",new DNS resolver types can be easily added.  A NULL-DNS resolver may fit in the requirement in some scenarios like DNS resolving is not necessary.

>Describe the desired behavior, what scenario it enables and how it would be used.
If configure with Null-DNS resolver type, no DNS resolving is performed.

>Any extra documentation required to understand the issue.

**Comment by yanjunxiang-google** [comment]
cc @htuch @jmarantz @yanavlasov

**Comment by mattklein123** [comment]
Now that this is an extension point you could potentially maintain this internally? I'm skeptical this has general OSS utility.
