### ISSUE TITLE
Envoy always sends tracing spans with logs for stream events

### ISSUE THREAD

**Issue by gongcon** [envoyproxy/envoy#17711]
Envoy 1.18.0 fixed verbose mode to emit annotations for stream events. However, it emits annotations even when verbose mode is off, which is the default setting in the config
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing

**Comment by jamesmulcahy** [comment]
@alyssawilk Yes, looks like it. That commit isn't actually checking the verbose flag, it's unconditionally adding the spans. 

This should be a straightforward fix. At a quick glance, `Tracer::startSpan` (which has access to the Config containing the verbose flag) probably needs to put the verbose flag into the `Span`, so that  `JsonV2Serializer::toListOfSpans` can determine whether or not to add the annotations.  

I'm pretty slammed right now, but will see if I can fix this up asap, if nobody else gets to it.

**Comment by dio** [comment]
@gongcon, do you mean annotation for `cr` and `ss`, something like below?

```
		"annotations": [{
			"timestamp": 1630916478253243,
			"value": "cr"
		}],

...

		"annotations": [{
			"timestamp": 1630916478252958,
			"value": "ss"
		}],

```

I think the referenced "stream events" are (called by `annotateVerbose` https://github.com/envoyproxy/envoy/blob/cc1d41e7ee9fbfb7ee3c8f73724cdc41d7c6bbb0/source/common/tracing/http_tracer_impl.cc#L235-L237): 

- `lastDownstreamRxByteReceived`
- `firstUpstreamTxByteSent`
- `lastUpstreamTxByteSent`
- `firstUpstreamRxByteReceived`
- `lastUpstreamRxByteReceived`
- `firstDownstreamTxByteSent`
- `lastDownstreamTxByteSent`
https://github.com/envoyproxy/envoy/blob/cc1d41e7ee9fbfb7ee3c8f73724cdc41d7c6bbb0/source/common/tracing/http_tracer_impl.cc#L96-L133

Hence, your trace annotations will have something like:

```
		"annotations": [{
			"timestamp": 1630916874738262,
			"value": "last_downstream_rx_byte_received"
		}, {
			"timestamp": 1630916874738334,
			"value": "first_upstream_tx_byte_sent"
		}, {
			"timestamp": 1630916874738342,
			"value": "last_upstream_tx_byte_sent"
		}, {
			"timestamp": 1630916874741176,
			"value": "first_upstream_rx_byte_received"
		}, {
			"timestamp": 1630916874741206,
			"value": "first_downstream_tx_byte_sent"
		}, {
			"timestamp": 1630916874741220,
			"value": "last_upstream_rx_byte_received"
		}, {
			"timestamp": 1630916874741236,
			"value": "last_downstream_tx_byte_sent"
		},
```

You can try this using the provided `examples/zipkin-tracing` in this repository.

```
$ git clone https://github.com/envoyproxy/envoy.git
$ cd envoy/examples/zipkin-tracing
$ # make sure you don't have processes listening to TCP 8000 and 9411
$ docker-compose up --build
$ # Wait for a moment and once it is running,
$ curl localhost:8000/trace/2
$ # Wait for a moment and then check for Zipkin traces,
$ curl -s localhost:9411/api/v2/traces | jq .[0][0].annotations
[
  {
    "timestamp": 1630917492083505,
    "value": "ss"
  }
]
```

And then you can try to use the verbose mode. By applying the following diff:

```patch
diff --git a/examples/zipkin-tracing/front-envoy-zipkin.yaml b/examples/zipkin-tracing/front-envoy-zipkin.yaml
index 0469b5895f..fcfe76e150 100644
--- a/examples/zipkin-tracing/front-envoy-zipkin.yaml
+++ b/examples/zipkin-tracing/front-envoy-zipkin.yaml
@@ -12,6 +12,7 @@ static_resources:
           "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
           generate_request_id: true
           tracing:
+            verbose: true
             provider:
               name: envoy.tracers.zipkin
               typed_config:
diff --git a/examples/zipkin-tracing/service1-envoy-zipkin.yaml b/examples/zipkin-tracing/service1-envoy-zipkin.yaml
index bcee3c873d..302f2b6450 100644
--- a/examples/zipkin-tracing/service1-envoy-zipkin.yaml
+++ b/examples/zipkin-tracing/service1-envoy-zipkin.yaml
@@ -46,6 +46,7 @@ static_resources:
         typed_config:
           "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
           tracing:
+            verbose: true
             provider:
               name: envoy.tracers.zipkin
               typed_config:
diff --git a/examples/zipkin-tracing/service2-envoy-zipkin.yaml b/examples/zipkin-tracing/service2-envoy-zipkin.yaml
index c13ba31ab6..454bf9576f 100644
--- a/examples/zipkin-tracing/service2-envoy-zipkin.yaml
+++ b/examples/zipkin-tracing/service2-envoy-zipkin.yaml
@@ -11,6 +11,7 @@ static_resources:
         typed_config:
           "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
           tracing:
+            verbose: true
             provider:
               name: envoy.tracers.zipkin
               typed_config:
```

Doing the same as the non-verbose one, you'll get similar to:

```
curl -s localhost:9411/api/v2/traces | jq .[0][0].annotations
[
  {
    "timestamp": 1630916874738262,
    "value": "last_downstream_rx_byte_received"
  },
  {
    "timestamp": 1630916874738334,
    "value": "first_upstream_tx_byte_sent"
  },
  {
    "timestamp": 1630916874738342,
    "value": "last_upstream_tx_byte_sent"
  },
  {
    "timestamp": 1630916874741176,
    "value": "first_upstream_rx_byte_received"
  },
  {
    "timestamp": 1630916874741206,
    "value": "first_downstream_tx_byte_sent"
  },
  {
    "timestamp": 1630916874741220,
    "value": "last_upstream_rx_byte_received"
  },
  {
    "timestamp": 1630916874741236,
    "value": "last_downstream_tx_byte_sent"
  },
  {
    "timestamp": 1630916874741257,
    "value": "cr"
  }
]
```

**Comment by gongcon** [comment]
@dio yes, I meant the annotation for the acronymic ones like `cr` and `ss`. Aren't they controlled by the verbose option?

**Comment by dio** [comment]
@gongcon they are not controlled by `verbose` option.

**Comment by dio** [comment]
I'm closing this since we need a better description and do some checking if removing `cr` and `ss` is desired and not breaking any implementation. Please open a specific issue when you think we should remove them. Thanks, @gongcon!
