### ISSUE TITLE
Envoy Filter - dynamicMetadata() shared between INBOUND on_request and OUTBOUND on_request

### ISSUE THREAD

**Issue by Arsen-Uulu** [envoyproxy/envoy#17733]
*Description*:
This is not an issue. Just a question

I was wondering if is it possible to share dynamicMetadata() between inbound and outbound streams. 

so I capture Inbound request_headers,  use dynamicMetadata():set() and use dynamicMetadata():get() on outbound request.

Any suggestions or workarounds will be appreciated

Thank you

**Comment by rojkov** [comment]
Could you briefly describe your use case?
