### ISSUE TITLE
getenvoy.io/gpg route broken

### ISSUE THREAD

**Issue by mcristina422** [envoyproxy/envoy#17743]
*Title*: *getenvoy.io/gpg route broken*

*Description*:
Previously envoy was installed using the instructions provided [here](https://www.envoyproxy.io/docs/envoy/v1.17.1/start/install#install-envoy-on-debian-gnu-linux). That required adding a key provided at `https://getenvoy.io/gpg`. As of last night, this route no longer works and redirects to https://www.envoyproxy.io/docs/envoy/latest/start/install, breaking CI install scripts.

The [latest](https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-debian-gnu-linux) instructions are updated to point at `curl -sL 'https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key'` but the old route of `getenvoy.io/gpg` was still used in CI. Was this breaking change announced/widely communicated? 

*Repro steps*:
`curl -sL 'https://getenvoy.io/gpg' | apt-key add -`

*Logs*:
`gpg: no valid OpenPGP data found.`

**Comment by mcristina422** [comment]
Oh, I guess maybe this should have been opened on https://github.com/tetratelabs/getenvoy.io ?

Either way I bet there will be a number of devs hitting this same issue today

**Comment by mattklein123** [comment]
cc @phlax.

We are in the middle of trying to migrate to officially provided packages and it's a little bumpy. Not sure if there is a quick fix we can do here or not.

**Comment by mcristina422** [comment]
Additionally those who are still on xenial (end of life) are not supported. 
```
W: The repository 'https://deb.dl.getenvoy.io/public/deb/debian xenial Release' does not have a Release file.
E: Failed to fetch https://deb.dl.getenvoy.io/public/deb/debian/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by leyao-daily** [comment]
Meet the same issue.

**Comment by codefromthecrypt** [comment]
I'll look into this. We recently moved the getenvoy domain into the LF/envoy control and missed a file

**Comment by codefromthecrypt** [comment]
This should be working now. I dragged the folder containing the two below files to https://app.netlify.com/sites/getenvoy-website/deploys

_redirects
```
# See https://docs.netlify.com/routing/redirects/ for syntax

# Redirect the old GPG key used for getenvoy linux packages to the archived contents
/gpg https://raw.githubusercontent.com/tetratelabs-attic/getenvoy.io/master/site/static/gpg

# Redirect everything else to the install page
# This uses shadowing because netlify requires an index.html, but we don't want to serve it.
/* https://www.envoyproxy.io/docs/envoy/latest/start/install 301!
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
</body>
</html>
```
