### ISSUE TITLE
Missing field in envoy-demo.yaml

### ISSUE THREAD

**Issue by christian-oudard** [envoyproxy/envoy#17752]
Following the tutorial here: https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#check-your-envoy-version

When I run envoy for the first time with the example config, it crashes, telling me I need to specify `connect_timeout`.
```
$ envoy --version
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

$ envoy -c envoy-demo.yaml
...
    [2021-08-17 18:23:18.386][42243][critical][main] [external/envoy/source/server/server.cc:113] error initializing configuration 'envoy-demo.yaml': Field 'connect_timeout' is missing in: name: "service_envoyproxy_io"
```

I was able to fix it by adding `connect_timeout: "1s"`, but it took a while to figure that out.
This is with the example config at https://www.envoyproxy.io/docs/envoy/latest/_downloads/92dcb9714fb6bc288d042029b34c0de4/envoy-demo.yaml

**Comment by leyao-daily** [comment]
Hi, connect_time has a default value now. So this field has been removed in the latest release. Maybe you use an old version of envoy.

**Comment by mattklein123** [comment]
Was just typing the same thing ^. Unless you are using a dev/latest image please use the matching docs for the release you are using.
