### ISSUE TITLE
TLS termination of HTTPS requests after CONNECT

### ISSUE THREAD

**Issue by rohrit** [envoyproxy/envoy#17760]
I have a question regarding using Envoy as a forward proxy with HTTP CONNECT working with dynamic forward proxy to send traffic to any upstream sites. Is it possible to terminate the TLS connection at Envoy after the initial HTTP CONNECT request?

**Comment by alyssawilk** [comment]
@lambdai had plans which would at least avoid passage through loopback, but I don't think anyone has the cycles to simplify beyond this today.

**Comment by rohrit** [comment]
Thank you for the reply, @alyssawilk !
