### ISSUE TITLE
Does Envoy Proxy's Kafka Network Filter Support Routing to Multiple Kafka Brokers?

### ISSUE THREAD

**Issue by michaeljmarshall** [envoyproxy/envoy#17791]
*Title*: *Does Envoy Proxy's Kafka Extension Support Routing to Multiple Kafka Brokers?*

*Description*:
I am running Kafka on Kubernetes, and I am looking to expose the brokers via a single load balancer. Envoy Proxy seems like a possible solution. However, I can't seem to get it to work with a single envoy proxy proxying to multiple brokers. The examples I have seen seem to indicate that I need to open multiple ports up on Envoy, but I was hoping for a solution with one address (host:port) that fronts the whole cluster.

Based on reading through some of the source code in the repository, it seems to me that there is some indication that the kafka network filter is supposed to be that single broker:

https://github.com/envoyproxy/envoy/blob/508934a659fcbf2a889016b38108418b44110429/contrib/kafka/filters/network/source/mesh/command_handlers/metadata.cc#L24-L26

Is the kafka network filter supposed to front a whole cluster? Am I reading documentation for a not yet released feature (I see this was just moved to `contrib` this week)? Is there any documentation on the current state and the desired state for the kafka filter?

Additionally, I noticed that there are two pages for kafka on the website. I'm not sure how these relate to each other.
1. https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/kafka_broker_filter.html
2. https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/kafka_broker/v3/kafka_broker.proto.html

Thank you for any insight you can provide!

Note: I searched through the existing issues and I only noticed one similar issue: https://github.com/envoyproxy/envoy/issues/15113. I don't think it is the same though, as this is directed towards kafka specifically and directly addresses a question about a comment in the source code.

**Comment by moderation** [comment]
@adamkotwasinski

**Comment by adamkotwasinski** [comment]
No, not yet!
But I'm working on that - it's going to be a `kafka-mesh` (not `kafka-broker`) filter, that's going to actually _process_ the inbound produce requests and according to _rules_ (topic regexes) forward them to correct upstream servers.

**Comment by michaeljmarshall** [comment]
@adamkotwasinski - that's great news! Thanks for your quick reply. Is there something (an issue, perhaps?) that I can follow to view your progress on this `kafka-mesh`?

**Comment by adamkotwasinski** [comment]
@michaeljmarshall There's nothing "formal" like an issue, but in the worst case you could wait until this PR https://github.com/envoyproxy/envoy/pull/11936 gets closed (it's the main one where I keep development, and its fragments are extracted and pushed into mainline on feature-by-feature basis).

**Comment by raissonsouto** [comment]
@adamkotwasinski, can you help me please?

https://stackoverflow.com/questions/78096885/how-to-use-kafka-broker-filtering-at-envoy
