### ISSUE TITLE
support verify_certificate_hash/verify_subject_alt_name config in routes

### ISSUE THREAD

**Issue by jwfang** [envoyproxy/envoy#1780]
currently *verify_certificate_hash/verify_subject_alt_name* are in global listener,
if we also support them in route, we may accomplish per-route SSL verify IMHO.

to accomplish, i guess we just can just don't do verify on SSL-handshake by leave listener/verify_* empty,
and somehow pass the SSL context down to route and do the verify there.

**Comment by jwfang** [comment]
the issue with this approach is how to generate a proper error respone for different request.

this problem doesn’t exist for listener since application level protocol has not started.

**Comment by jwfang** [comment]
if we consider verify failure in routes is abnormal, may be just close the  downstream connection is acceptable ?

**Comment by htuch** [comment]
Can you elaborate on the use case that would require SSL validation on a per-route basis? In general, SSL validation is a concept that applies somewhere between L4 and L7, but routing is performed at L7.

**Comment by jwfang** [comment]
thanks for replying.

we are trying to do s2s service authorization via mTLS, and would like to have control at method level.

**Comment by mattklein123** [comment]
I don't see any particular reason that we couldn't enforce something like this on a per-HTTP route basis and then respond with 403 at HTTP layer. I would prefer this is a discrete filter if there is interest in actually doing this.

**Comment by htuch** [comment]
In the existing API, I think this makes sense in two scenarios:
1. Some routes you just don't care about doing any validation on, and some subset you do.
2. You share `RouteConfiguration` objects across listeners, and want to know which SSL cert/listener combo was used when doing the route selection.
In v2, since we'll have multiple certs, I can see this being useful on a per-route basis in general.

**Comment by mattklein123** [comment]
Note that HTTP filters have access to connection/SSL data so this would be very easy to add in general as a filter.

**Comment by jwfang** [comment]
@mattklein123 i like the idea of seperate filter, it made the ssl auth config more explicit and seperate.

if we are going to do it in filter, does the *tls-verify* config still goes to *http_connection_manager* and we only access selected route config from the filter ?
otherwise (*tls-verify* config in filter), we may have to reduplicate the virtual-host/route selection logic in the filter.

**Comment by mattklein123** [comment]
> if we are going to do it in filter, does the tls-verify config still goes to http_connection_manager and we only access selected route config from the filter? otherwise (tls-verify config in filter), we may have to reduplicate the virtual-host/route selection logic in the filter.

Yeah I'm not sure. That's a good point. The current stuff that is built just does redirection. It doesn't actually do any 403, etc. so we might be able to split it there. If we want redirection at the route level we should just build that into the existing router.

**Comment by PiotrSikora** [comment]
Note that in order for clients to send any certificates, server must request them during initial TLS handshake, which means that we'd need to configure listeners with `trusted_ca` (possibly ignoring result of verification) if any of the routes are going to require client certificates.

**Comment by jwfang** [comment]
sorry for the late, just back from holidays.

thanks for your help and suggestion, i did a early draft in #1830 which mimic the redirection behaviour in Router::Filter.

@PiotrSikora , from https://github.com/envoyproxy/envoy/blob/a0adb668f0cb51d7aeea2f79246209d24a10cd64/source/common/ssl/context_impl.cc#L38 it seems as long as there is *caCertFile*, *SSL_VERIFY_PEER* will be set, but not necessary *SSL_VERIFY_FAIL_IF_NO_PEER_CERT*.
i guess this maybe okay as long as we send a client certificate request to the client via *SSL_VERIFY_PEER* but not verify during handshakes and defer verify later during **routing** ?

**Comment by PiotrSikora** [comment]
`SSL_VERIFY_FAIL_IF_NO_PEER_CERT` shouldn't be set, because it would mean that at least one of: `require_client_certificate`, `verify_certificate_hash`, `verify_subject_alt_name  ` is enforced server-wide for all routes, so existing behavior is fine.

**Comment by jwfang** [comment]
@mattklein123 

i am planning to:
1. add request cert info fields to *RequestInfo*
2. duplicate *verify_certificate_hash/verify_subject_alt_name* configs in *RouteEntry*
3. copy cert info from SSL connection to *RequestInfo* in *ActiveStream::decodeHeaders*
4. check *RequestInfo* against *RouteEntry* in *Router::Filter::decodeHeaders*

is the above approach reasonable ?

**Comment by mattklein123** [comment]
@jwfang I don't think you need to copy anything to RequestInfo. You have access to a const connection from the filter: https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L93 (You can get the TLS connection off of that if it's a TLS connection). Then you can use properties of the TLS connection to perform various types of matching and then return 403, etc. if it doesn't match.

My one request if we do this in the router filter: I really want to prevent the router filter from blowing up in size as much as possible. Please put all of this logic in some new utility classes that can be called from router filter decode headers. Then you more easily test that utility class directly. Thank you.

**Comment by jwfang** [comment]
@mattklein123

thanks, access connection directly is much cleaner.

do we have acess to the current matched *routeentry* in filter ? if so, we may keep the config in router, but do the verify logic in seperate filter.

**Comment by mattklein123** [comment]
Yes https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L112

A dedicated filter is better IMO if there is no technical reason not to do it.

**Comment by mattklein123** [comment]
@danielhochman can you please work with @jwfang on this. This has the potential to be a general RBAC filter where we can do things based on TLS, Istio RBAC rules, etc.

**Comment by jwfang** [comment]
@mattklein123 @htuch @danielhochman 
create #1900 ,  early push to get your early feedback.

**Comment by spikecurtis** [comment]
I really like the idea of adding authorization to Envoy's data plane API.  For those who don't know me, I have been thinking a lot about the topic of authorization in distributed applications.  Where I would like for us to get to is a mechanism that is general enough to build authorization systems that support a wide variety of use cases.

The first high-level comment I have about [the current dataplane proposal](https://github.com/envoyproxy/data-plane-api/pull/199) is that I think we want to disentangle authorization from Route Discovery Service.

 * RDS only applies to HTTP connections, so isn't useful for authorizing other traffic
 * Mixing Authorization with routing in the discovery API causes these things to be inseperable in the control plane.  Ideally we'd like to support an architecture where routing and authorization could be loosely coupled or decoupled control plane components.
 * RDS defines a hierarchy of traffic matching (host first, then path & other headers) that make certain kinds of authorization policies hard to express.  The hierarchy makes sense for HTTP service routing, but imagine attempting to implement a policy that drops all traffic from a list of abusive IP addresses: you'd have to walk every route and add this constraint.

From discussions at Tigera, we would prefer an authorization filter (or filters) that can call an external service over a well-defined gRPC API.  The API call would include the details of the request, including HTTP method, path, etc., details of the TLS connection like X.509 cert, and Layer 3-4 details like IP address, port, etc.  The external service would render an authorization decision and return the result, which would be enforced by the filter.

The primary motivation for this architecture is flexibility.

 * It gives authors of authorization systems the ability to deploy alongside Envoy, or as a network service.
 * It allows different access control policy syntaxes, like Access Control Lists (ACLs), Role Based Access Control (RBAC), Attribute Based Access Control (ABAC), etc. to be implemented using the same underlying Envoy API.
 * It allows the decision rendering systems to be authored in the language of choice for the developer (so long as there are gRPC bindings available).  While C++ works well for Envoy's high performance byte streaming & filtering, it may not be an idea choice for authorization policy.

**Comment by spikecurtis** [comment]
cc @lxpollitt @saumoh

**Comment by mattklein123** [comment]
> The first high-level comment I have about the current dataplane proposal is that I think we want to disentangle authorization from Route Discovery Service.

The proposal as it stands now I think will work for multiple use cases. It's defined as a separate auth concept, which is then used as part of route lookup. This doesn't mean that needs to be done in the router filter. It will likely be implemented in its own filter. We can also build an L4 auth filter using the same set of auth primitives.

> From discussions at Tigera, we would prefer an authorization filter (or filters) that can call an external service over a well-defined gRPC API. The API call would include the details of the request, including HTTP method, path, etc., details of the TLS connection like X.509 cert, and Layer 3-4 details like IP address, port, etc. The external service would render an authorization decision and return the result, which would be enforced by the filter.

I think we can do both here. At Lyft, we have no need to call an external service. Our needs are extremely simple. However, I think in the data-plane-api PR that is in progress, we can add a rule type that is actually a callout to an external service. To me this is the best of both worlds and users can use the functionality they need.

**Comment by spikecurtis** [comment]
> The proposal as it stands now I think will work for multiple use cases. It's defined as a separate auth concept, which is then used as part of route lookup. This doesn't mean that needs to be done in the router filter. It will likely be implemented in its own filter. We can also build an L4 auth filter using the same set of auth primitives.

@mattklein123 can you say more about what you are imagining?  What I see of the current proposal is that while `AuthAction`s are independently defined, you can only pass them to Envoy over the RDS.

**Comment by mattklein123** [comment]
> @mattklein123 can you say more about what you are imagining? What I see of the current proposal is that while AuthActions are independently defined, you can only pass them to Envoy over the RDS.

That's because that is our (Lyft/QQ/?) immediate need. It doesn't preclude building an L4 filter that consumes the same structures.

**Comment by mattklein123** [comment]
Calling this fixed via https://github.com/envoyproxy/envoy/pull/3455. We can open new issues for incremental RBAC matching conditions as needed.
