### ISSUE TITLE
No way to access a refresh_token in the oauth2 filter

### ISSUE THREAD

**Issue by Alexcei88** [envoyproxy/envoy#17808]
I am using [OAuth2 filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) to protect my microservices. Identity broker is Keycloak. 
According Keycloak documentation many its REST API methods are required passing **refresh_token** instead of **access_token**. 
For example [to logout user from identity provider](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/oidc-generic.adoc#logout-endpoint) I need to pass the **refresh_token** to authentificate me on the server.
It's strange, but keycloak developers designed so.

Configuring OAuth2 filter I can specify token endpoint and whether to pass the recieved **access_token** to upstream ( _forward_bearer_token_ parameter). But the received **refresh_token** just get lost by envoy. How can I get a **refresh_token**? 

I am ready to make PR to save refresh_token somewhere in the OAuth2 filter. What do you think?

**Comment by phlax** [comment]
cc @rgs1 @asraa

**Comment by rgs1** [comment]
Thanks for reporting this @Alexcei88 – happy to help reviewing a PR if you want to start working on something.

**Comment by Alexcei88** [comment]
I found one more general case.  
To logout user many OAuth provider receive id_token through id_token_hint query parameter. This is used as an indication of the identity of the End-User. Right now envoy doesn't save id_token anywhere, so I cannot get this parameter. So, it looks like I also need to save id_token .

**Comment by Alexcei88** [comment]
I found one more general case.
To logout user many OAuth provider receive id_token through id_token_hint query parameter. This is used as an indication of the identity of the End-User. Right now envoy doesn't save id_token anywhere, so I cannot get this parameter. So, it looks like I also need to save id_token.

I will take care it soon.

**Comment by siepkes** [comment]
@rgs1 Could this issue be re-opened and tagged help-wanted? This feature would be valuable for me as well and I think it could be beneficial to more people.

**Comment by Alexcei88** [comment]
@siepkes , PR already approved some days ago and changes are in the main branch.

**Comment by phlax** [comment]
@Alexcei88 which PR - shall i close this ticket again ?

**Comment by Alexcei88** [comment]
https://github.com/envoyproxy/envoy/pull/18353

**Comment by siepkes** [comment]
@Alexcei88 Totally missed that one, sorry!
