### ISSUE TITLE
remove ':' restriction in cluster names

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1782]
@hennna @htuch I need to refresh my memory of this whole situation. I will put some notes in over the weekend.

Related to https://github.com/envoyproxy/envoy/issues/1761

**Comment by hennna** [comment]
Searching through past issues I'm seeing #667 #573.

I think the proposal would be to remove the json check here: https://github.com/envoyproxy/envoy/blob/8a09d86383c3c177eddcf8b1265900769540a4aa/source/common/json/config_schemas.cc#L1350

and do a character replace here: https://github.com/envoyproxy/envoy/blob/0efa18c36d6f789562690b5053c2c4b00987979e/source/common/stats/stats_impl.cc#L35 as we do with IPv6 addresses https://github.com/envoyproxy/envoy/blob/be01fc2a8ea04fba1b67fce61d189c19f56e0bf3/source/server/listener_manager_impl.cc#L97

**Comment by hennna** [comment]
To make the cluster name length variable, the stats name length must also be variable. Is the 127 character stats name a hard limit? https://github.com/envoyproxy/envoy/blob/master/source/common/stats/stats_impl.h#L29

**Comment by mattklein123** [comment]
Making the name variable length is what is being discussed in #1761. Yes, what you have above sounds about right. We basically just need to make sure the stats themselves don't have ':' in it. (In a perfect world this would only be a statsd thing but not sure it's worth dealing with right now. I think replacing with '_' is fine). So yeah if you want to work on this part go for it.

I think @ggreenway is doing the other one but depending on timelines he might be interested in giving it up also.

**Comment by hennna** [comment]
Okay. I'll take this one.

**Comment by ggreenway** [comment]
I'm halfway through making the sizes configurable.  Hopefully will have a PR up for it next week sometime.

**Comment by hennna** [comment]
Actually doing the character replacement during stats initialization alone may not be enough.  The stats name is used during lookup, caching and flushing.

https://github.com/envoyproxy/envoy/blob/master/source/common/stats/stats_impl.h#L185
 
https://github.com/envoyproxy/envoy/blob/63a88acb01e3fbfcb0fe129c53003cd2be713590/source/common/stats/thread_local_store.cc#L134

https://github.com/envoyproxy/envoy/blob/bc2ca38babde89487e4f00c9297e3577b82244a9/source/common/stats/statsd.cc#L63

Are there central places to look to minimize the number of changes necessary? Is it possible to just change the statsd flush code?

**Comment by mattklein123** [comment]
Yeah you definitely can't just change it during init. As you point out it either has to be done at the "top" (before stat is created) or at the "bottom" (at the sink).

This problem is going to occur with any user defined name. (RDS is probably broken once @junr03 adds route specific stats if they were to include ':'). So we should probably try to fix 

There are a few different ways I can think of to fix this the sink level, but TBH they are all a little ugly. Why not just formalize what we do for listeners? Basically before we create the scope, just replace ':' with '_'. You could have this be a helper utility that is called during cluster scope create. Better, could we perhaps just do this as part of the scope create itself such that scopes cannot have any reserved characters? Then we can leave the ASSERT in the low level stats code, and just fix any sites which build stat names from user input. This does not seem that bad.
