### ISSUE TITLE
Benchmarking/load testing tools for envoy

### ISSUE THREAD

**Issue by jsedgwick** [envoyproxy/envoy#1784]
Hi, apologies if I missed it, but is there any sort of benchmarking and/or load testing tool for envoy? How is perf tested?

**Comment by mattklein123** [comment]
We have some tooling built by Google here: https://github.com/envoyproxy/envoy-perf

But it's still early days for anything official. We don't currently publish any numbers. For better or worse all the current tuning that I have done has been against live systems and some microbenchmarks for specific cases. 

Obviously there are the usual load testing tools out there including h2load, wrk, etc.

**Comment by mattklein123** [comment]
Closing this out for now. Please reopen if there are other questions.
