### ISSUE TITLE
Network filter to mirror socket options upstream/downstream

### ISSUE THREAD

**Issue by VivekSubr** [envoyproxy/envoy#17841]
*Title*:  Network filter to mirror socket options upstream/downstream

*Description*:
I am using envoy in istio-sidecar. 

So, the application running inside the pod ('downstream') creates a socket and does setsockopt on that socket to set some IP headers (DSCP byte in my case), but envoy uses a different socket to send message to target application ('upstream'). 

So, during proxying, these IP headers are lost. Current network filters don't seem to have a solution to this.

Hence, I wish to add a new network filter 'mirrorSockOpt filter' that will do getsockopt on downstream and do setsockopt on the outbound upstream connection.

Does that make sense? Do you think such a filter can be merged with envoy code? (I can't work on WASM filter since we are using a old version of istio, 1.6, and we are performance sensitive).

**Comment by phlax** [comment]
> Do you think such a filter can be merged with envoy code?

its probably worth taking a look at the (recently updated) contrib extensions policy https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#contrib-extensions

cc @mattklein123

**Comment by mattklein123** [comment]
cc @PiotrSikora. What do you think about this as a WASM use case in general? I don't think doing a filter here would be that difficult, though I'm not sure we would want to merge it if WASM is a better place for this type of thing.

**Comment by tederigobert** [comment]
Do you mean my laptop will remain block until 37 days? For reason

**Comment by michalmaka** [comment]
Hello @VivekSubr, I'm also interested in this feature. Could you make it reopen by labelling as stated by github's bot?

**Comment by VivekSubr** [comment]
Actually, it turns out it's not so simple - there is no way to extract
socket options from the other end of a tcp socket, since it sends only the
tcp payload, not the ip headers.

With some research, I could see two ways
1. Use raw sockets, but that doesn't fit in with envoy flow
2. Use linux socket filters, but that would force envoy to always run with
high privileges.

So, rather than that, we thought of adding a envoy cluster configuration to
setsockopt on outbound traffic. I mean there's already a configuration sort
of for it,
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html?highlight=bindconfig

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-bindconfig

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#envoy-v3-api-msg-config-core-v3-socketoption

We made changes so that istio can push the config.

Thanks and Regards,
Vivek S

**Comment by jlatusek2** [comment]
> 

@VivekSubr Hi, I'm facing similar problem and would like to ask how you want to use Linux sock filter to make it work?

**Comment by VivekSubr** [comment]
Hello,

I don't know how I'd make it work with linux socket filters... one
objection was raised is that they require root permissions to run, not a
good property to have for a proxy. It may be possible to use Raw sockets to
implement this, but that's another can of worms.

What my team went with - add the dscp value to envoy configuration and make
it do setsockopt as per the configuration in outbound connection. I wasn't
the guy who wrote the code, so don't know the details.

There already some config options -
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#envoy-v3-api-msg-config-core-v3-socketoption

Maybe use this? Not sure if this can be configured at run time, maybe
extend it so it is?

Thanks and Regards,
Vivek S

**Comment by s-jlatusek** [comment]
@VivekSubr I see, thx for your help. :))
