### ISSUE TITLE
subset lb: support overriding TLS upstream config 

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#17882]
The subset LB allows us to route to the right upstream in a dynamic environment. However, there's currently no way to dynamically alter the TLS configuration that should be used to contact a given upstream endpoint (e.g.: overriding the configured SAN). More specifically, what we need is to construct an exact SAN match from a pre-configured prefix SAN using extracted metadata. That is, there is a 1:1 mapping from a subset to an exact SAN match.

Furthermore, if the header-to-metadata supported setting SubjectAltNames based on available metadata, e.g.:

```
  auto data = std::make_unique<Network::UpstreamSubjectAltNames>(alt_names);
  stream_info.filterState()->setData(Network::UpstreamSubjectAltNames::key(), std::move(data),
                                     StreamInfo::FilterState::StateType::Mutable);
```

we could achieve what we need. Given this opens up some security considerations, feedback would be much appreciated.

Somewhat related to this use case, the router solves this here:

https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L494L513

cc: @zuercher @mattklein123 @fishcakez @bpalermo

**Comment by zuercher** [comment]
It seems to me that the security concern for this change would be the possibility of a bad actor disabling Envoy's SAN verification or setting it to accept an unexpected SAN. Header-to-Metadata's security posture already assumes trusted upstreams, it seems the worst one could do is cause upstream requests to fail. Am I missing something?

**Comment by rgs1** [comment]
@zuercher that's our thinking too. So perhaps something like #18112?
