### ISSUE TITLE
thrift proxy: add access logger support

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#17898]
Similar to #1953. 

cc: @zuercher @fishcakez

**Comment by wbpcode** [comment]
Here is some related issue #13085 #6138. We do need a general design to solve these problems.

**Comment by wbpcode** [comment]
At present, for the general log solution, gRPC logger is the most difficult problem to solve.

**Comment by rgs1** [comment]
I might start working on this soon, so re-opening.

**Comment by rgs1** [comment]
Well, I thought commenting would re-open it – it didn't. I'll just open a new one.
