### ISSUE TITLE
Envoy memory leak when compiling with new TCMalloc

### ISSUE THREAD

**Issue by junpengl** [envoyproxy/envoy#17897]
*Title*: *Envoy memory leak when compiling with TCMalloc*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

When compiling Envoy v1.18.3 with the new TCMalloc library (from the official Envoy ubuntu Docker image),  the Envoy server memory_physical_size and heap_size shouldn't increase after initial start, especially when its memory_allocated doesn't increase. However I observed steady increase of Envoy server's physical memory and heap size. The issues happens for all the Envoys we run with the new version. 

Once I compiled the Envoy v1.18.3 source code with the old gperftool TCMalloc (using "--define tcmalloc=gperftool" option), the issue went away. I also didn't notice the issue with old Envoy versions that don't have the new TCMalloc library. 

The memory graph looks like this. The highest line is the memory_physical_size, the second higher one is the memory_heap_size and the lowest one is the memory_allocated. And the metric before May 27 is when we are running with the old Envoy v1.13.6. After that when we upgrade to v1.18.3 you can see the heap size kept increasing until it triggers an OOM and restarts. This is an testing application with traffic volume ~5 rps and small requests/responses size. 
![memory_usage_graph](https://user-images.githubusercontent.com/10250392/131186334-0485815b-e2bb-45e9-8917-5cbb7d37f285.png)

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs

This memory issue happens with Envoy v1.18.3 with the new TCMalloc library (from the official Envoy ubuntu image). Our Envoy is connecting to our own xDS which implements the REST xDS endpoints v3. I haven't tried to reproduce the issue with open-sourced xDS yet. 

>**Note**: 

It is also really frustrated that I couldn't get a heap profile the new TCMalloc library. Also based on what I read in https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md It seems like the performance test can only be done with the gperftools. So it seems like the tests might not cover when using the new TCMalloc library?

*Config*:

config_dump: [config_dump.zip](https://github.com/envoyproxy/envoy/files/7069307/config_dump.zip)
I have removed & redacted some sensitive information. This Envoy is just acting as a normal sidecar that proxy requests for an application. 

*Logs*:
>Include the access logs and the Envoy logs.

Nothing out of ordinary shows up in the logs.

**Comment by rojkov** [comment]
The version of tcmalloc in Envoy is more than 6 months old now. Could you please try to update it and test again?

Also do you have the [overload manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager) configured to try to release unused memory? Note that HeapShrinker is hardcoded to release memory if  ("physical_mem" - "allocated_mem") > 100M.
