### ISSUE TITLE
The number of envoy connections 65,000+ will make the cpu fully loaded

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#17907]
I ran into a problem recently.I use the version 1.15.2 release in docker.
In the product environment,my cpu will fully loaded when the connection reach to 65000+.
I check the handle of linux system,or the port of every connection.They seem to be normal.
/etc/sysctl.conf:
![envoy1](https://user-images.githubusercontent.com/36953705/131298310-32e616df-a048-4cf6-943f-21f2e8e86b26.png)
![envoy2](https://user-images.githubusercontent.com/36953705/131298312-94bf5927-32a2-4786-bfe5-b118ac1afa18.png)
/etc/security/limits.conf:
![envoy3](https://user-images.githubusercontent.com/36953705/131298400-70090be3-d3a7-4751-add1-0004932334c7.png)
And the yaml of envoy:
![envoy4](https://user-images.githubusercontent.com/36953705/131298640-868abfe8-0c72-49be-ac80-b871f4e8a45e.png)
I don't know if my envoy yaml has some problem.
I  even try to close the limit of cluster's circuit breaker,when it reached the the number of connections,it also cause the cpu fully loaded....
when connection is 60000,cpu is only 60%,when reached 65000+,it will be highly 2400%（sum cpu core:24).
It confused me lot...
Please help me check this problem..Thank you.

**Comment by junr03** [comment]
@oschaaf or @jmarantz could probably have some pointers

**Comment by rojkov** [comment]
Could you make some [flamegraphs ](https://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html) for your setup?

What's the output of `sysctl kernel.msgmni` in your system?

PS. it smells like some counter gets overflowed after 65535.

**Comment by hbgongen** [comment]
thanks，i will try to get its flamegrahs.
kernel.msgmni is 15885.
@rojkov

**Comment by hbgongen** [comment]
when i change msgmni to 70000,it also has fully cpu loaded when the tcpconnection reach 65000+. @rojkov

**Comment by hbgongen** [comment]
![image](https://user-images.githubusercontent.com/36953705/131617908-b12c5162-0cef-42f5-8cd4-da414ae9cf34.png)
i find this problem,cpu all for the kernel function **connect**.
Maybe Before we connect,shall we bind a port in case of the cost of selecting unused port.

**Comment by rojkov** [comment]
This looks like Envoy is trying to open 65000+ connections to the same single upstream and running out of local ports (65536 connections is a hard limit here). Is that the case?

**Comment by hbgongen** [comment]
Yes...Sorry..Ahahahah,i have find this problem.single listener port to same upstream is only 60000+ because of the ip port range...i ignore that envoy will create a local ip to upstream.
