### ISSUE TITLE
Tag the data-plane-api repository as part of the envoy release process

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#17904]
*Title*: Tag the data-plane-api repository as part of the envoy release process

*Description*:

It it not very clear how to match the xDS API to the right version of Envoy. go-control-plane releases don't line up with Envoy releases, and consuming xDS protobufs directly from the Envoy repository means pulling a large repository and (I think) reimplementing a bunch of tooling.

I did experiment with generating the tags in the `data-plane-api` repository, but since only protobuf commits get mirrored, there's not enough git history to create all the corresponding tags. Probably solvable by not using bash, but just tagging as part of the envoy release seems more direct and simpler.

I'm happy to help with this if i can, but I expect this needs someone with permissions to tag repositories and a good understanding of the Envoy release machinery.

```bash
#! /usr/bin/env bash

set -o errexit

readonly ENVOYDIR=~/upstream/envoy

envoy::tags() {
    (
        cd "$ENVOYDIR"

        # Note that the sort works to order releases from newest to oldest as long
        # as Envoy never goes to v2, or to a 3-digit minor release.
        for release in $(git tag | egrep '^v[[:digit:]]([.][[:digit:]]+)+' | sort -t. -n -r -k 2,3); do
            printf "%s\t%s\n" "$release" "$(git rev-parse "$release")"
        done
    )
}

closest::release() {
    local sha="$1"

    (
        cd "$ENVOYDIR"
     
        git describe --tags "$sha" | grep -E --only-matching '^v[[:digit:]]([.][[:digit:]]+)+'
    )
}

mirror::history() {
    git log | awk '
    BEGIN {
        Count = 0
    }

    /^commit / {
        Commit[Count] = $2
    }

    /Mirrored from/ {
        Mirror[Count] = $5
        Count++
    }

    END {
        for (n = 0; n < Count; n++) {
            printf "%s\t%s\n", Commit[n], Mirror[n]
        }
    }
    '
}

declare -A releases

envoy::tags | while read tag sha ; do
    releases[$tag]=$sha
done

currentvers=

mirror::history | while read sha mirror ; do
    # closest vers tells us the last envoy version that was released
    # prior to this commit.
    closestvers=$(closest::release "$mirror")
    printf "%s\t%s\n" $sha $closestvers

    if [ -z "$currentvers" ]; then
        currentvers=$closestvers
    fi

    # At the version boundary, tag the new version.
    if [ "$currentvers" != "$closestvers" ]; then
        echo git tag "$currentvers" "$sha"
        currentvers=$closestvers
    fi
done
```

**Comment by jpeach** [comment]
xref https://github.com/envoyproxy/go-control-plane/issues/391

**Comment by phlax** [comment]
cc @ggreenway @snowp

**Comment by alecholmez** [comment]
@jpeach Also had an offline conversation about potentially moving the build of go-control-plane away from bazel since it adds quite a bit of complexity. We would reference the data-plane-api protos as the source of truth
