### ISSUE TITLE
Support dynamic state in composite filters

### ISSUE THREAD

**Issue by qas** [envoyproxy/envoy#17905]
*Title*: 
**dynamic state be read and applied by Envoy when doing the matching with composite filters**

*Description*:
This feature request is for allowing dynamic state values to be used within matchers for composite filters.

Currently the only way to apply dynamic state values is to create a custom HTTP filter that reads dynamic state and sets HTTP headers, and use this filter first before the composite filter (then do matching based on HTTP headers as shown in your [example](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter#sample-envoy-configuration))

*Relevant Links*:

1. [Dynamic state](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters#dynamic-state)
2. [Composite filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter)
3. [Slack discussion](https://envoyproxy.slack.com/archives/C78M4KW76/p1625645005375500)

**Comment by phlax** [comment]
cc @snowp

**Comment by snowp** [comment]
This should be relatively easy to do if someone has the time to pick this up: add the downstream StreamInfo to https://github.com/envoyproxy/envoy/blob/main/source/common/http/matching/data_impl.h#L14 and add an input (https://github.com/envoyproxy/envoy/blob/main/source/common/http/matching/inputs.h) that extracts the specified dynamic data. 

In order for matching on filter state to make sense we need to be able to extract some string value out of it, so it would probably be reliant on `serializeAsString` being defined for the object (at least as a first iteration).
