### ISSUE TITLE
external-dns support?

### ISSUE THREAD

**Issue by ThomasLohmann** [envoyproxy/envoy#17901]
Hi everyone,

any plans to support external-dns for Envoy? It would be really helpful and it's a common challenge on a bare-metal Kubernetes cluster. See the following link: https://github.com/kubernetes-sigs/external-dns

the idea/user story is the following: As a user, I want to create DNS records via external-dns in Cloudflare (or any other DNS provider) automatically, once another node or service has been added to the cluster, so that I don't need to do it manually.

Currently, we are using Envoy + Keepalived with a custom DNS script to update our DNS records in Cloudflare automatically. Since Envoy doesn't work with external-dns, we need a custom DNS script. In order to simplify our stack by a lot, we want to drop the custom DNS script in favour of external-dns. It would be really great, if we can find a solution to make that happen asap. Please, see our whole stack:

![Architecture](https://user-images.githubusercontent.com/20458351/131214766-bea28a1d-9c8e-4000-a8e4-e550f976e4d2.png)

Just as a side note: We use dedicated servers for our worker nodes and VMs for our master nodes both provided by Hetzner/Hetzner Cloud. See the following links:

https://www.hetzner.com/dedicated-rootserver/matrix-ax

https://www.hetzner.com/cloud

If something is unclear, please let me know.

Regards,
Thomas

**Comment by phlax** [comment]
cc @mattklein123

**Comment by mattklein123** [comment]
No, I don't think this is something that we will support. It seems like more of a control plane concern than an Envoy concern. I'm not even sure what the Envoy feature would be here.

**Comment by ThomasLohmann** [comment]
@mattklein123 are you sure that it is a control plane issue and not a missed implementation by external-dns/envoy? Since our DevOps things so. Otherwise, how would you implement external-dns for a bare-metal cluster with an external load balancer like Envoy, HAProxy, Nginx etc. and connect it with external-dns?

Regards,
Thomas

**Comment by mattklein123** [comment]
> external-dns/envoy

I don't know what this and it's not maintained by us, so I would suggest discussing with the maintainers of that project?

**Comment by ThomasLohmann** [comment]
@mattklein123 alright. I will discuss it with the maintainers of external-dns. Because I was not sure, if this issue needs to be solved by Envoy or external-dns.
