### ISSUE TITLE
Clarify API versioning for alpha APIs

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#17920]
*Title*: Clarify API versioning for alpha APIs

*Description*:

The [API_VERSIONING](https://github.com/envoyproxy/envoy/blob/main/api/API_VERSIONING.md) doc has a couple of exceptions for  the compatibility policy:

1. Changes made within 14 days of the introduction of a new API field or message.
1.  API versions tagged vNalpha. Within an alpha major version, arbitrary breaking changes are allowed.

In (1), even if the 14 days has not elapsed, and API might still be included in an official Envoy release. In this case, can we make it clear that once included in a release, the API is subject to compatibility?

In (2), if a v1alpha API can be changed in any way at any time, how can a control plane ever feel safe experimenting with it? As a control plane author, this is telling me that an alpha API can have breaking changes with no way for me to handle the transition. Does this mean that an API at the same`v1alpha2` version can be completely incompatible between Envoy versions?

Finally, as a blanket rule, can we ban re-use of field numbers? AFAICT, this makes is difficult to impossible for a control plane to track API changes across Envoy versions. If a breaking change is needed, then dropping support for a field number (but not re-using that number), still makes it possible for me to carry a patch where I can serve different field numbers to different Envoy versions.

**Comment by mattklein123** [comment]
cc @envoyproxy/api-shepherds 

I agree about (1). Please raise a PR to adjust this text.

I think (2) is going to require a lot more thinking. I agree that with breaking changes we are going to reduce the chance that people will experiment with the API. So this leaves us with:
1) Just stop doing alpha and admit that all APIs are basically final (I'm getting pretty close to leaning in this direction myself)
2) Do alpha, but avoid breaking changes, and then have some official policy for locking in the move to non-alpha. (Rename just to connote stability and possibly clean up deprecated fields while still reserving them.)
3) Other?

Thoughts?

**Comment by jpeach** [comment]
> cc @envoyproxy/api-shepherds
> 
> I agree about (1). Please raise a PR to adjust this text.
> 
> I think (2) is going to require a lot more thinking. I agree that with breaking changes we are going to reduce the chance that people will experiment with the API. 

I do think that is is OK for alpha APIs to spend less on compatibility than major version APIs. People adopting them should be prepared to do at least some transition work across Envoy releases. I'm not sure how to couch it in spec language, but breakages are OK as long as you can migrate between Envoy releases.

**Comment by htuch** [comment]
My basic thinking is that alpha APIs are unfit for use in production systems and control planes should not support them. This aligns with @mattklein123 take that basically all APIs are final. The question is how do we enforce this for `contrib/`?

In any case, I think whatever rules we adopt have to be machine enforced with `buf`. We're past the point that humans can consistently enforce them in a scalable way across the full surface.

**Comment by adisuissa** [comment]
I also agree that at the moment anything added as alpha is essentially final. I think that typically alpha/beta is used for a specific version release of a binary, during which the API can change. However, this makes little sense in how Envoy's versioning works as the binary version is orthogonal to the API version.

For `contrib/` I think the bar is much lower, and it is up to a contributor to set their API as alpha or not.
Using alpha implies that the API may introduce breaking changes, and this might be ok in use-cases where the extension depends on something very dynamic and it may not be clear up-front. The users of an alpha extension essentially agree that the API may break.
Once the API is final, or if there's sufficient community around it, the API can move to non-alpha mode. This is also required when moving it from a `contrib` to a regular `extension`.

**Comment by jpeach** [comment]
Perhaps a middle ground for alpha APIs is to be more aggressive about incrementing version numbers. Rather than making changes to v1alpha1 that are not wire-compatible, leave v1alpha1 in place N and make the change in v1alpha2. Envoy doesn't need to support both versions, but would continue to ship the protobufs (because go-control-plane isn't strongly bound to Envoy releases). Then control planes can pick the right version of the alpha API to serve to the right version on Envoy if they need to.

**Comment by jpeach** [comment]
> My basic thinking is that alpha APIs are unfit for use in production systems and control planes should not support them in situations when you need to do things like binary upgrades.

IME, the envoy project has been really good at API compatibility, so it's easy to make the same assumptions about alpha APIs :)

**Comment by mattklein123** [comment]
Having thought about this a bit more, I would vote for one of two extreme options:
1) No more alpha outside of contrib.
2) Alpha outside of contrib is allowed during development of a feature, but there is a extremely clear understanding that alpha APIs are not stable, should not be used in production, and if someone wants to use a feature in production they need to say so so we can move the API to non alpha.

We have run into alpha -> non-alpha problems often enough that I think it's time to do away with it or be much more explicit about what guarantees there are.

Thoughts?

**Comment by lizan** [comment]
I'm leaning to 1. as we have contrib now, new extensions can be started in contrib during its development and then moved into main if there's desire.

**Comment by mattklein123** [comment]
Yes (1) is my vote also.

**Comment by htuch** [comment]
I vote for (1). But I also think that we are going to relitigate this whole issue inside of contrib, as control planes decide to support contrib extensions. There really is no free lunch, we need to be clear that anything inside of contrib is completely unsupported and unsupportable in any commercial product or production environment. If folks don't like that for a feature, then there needs to be a sustained effort by folks to move it to non-contrib.

**Comment by mattklein123** [comment]
> If folks don't like that for a feature, then there needs to be a sustained effort by folks to move it to non-contrib.

I agree.

Well sounds like are aligned on (1). We should audit all alpha APIs in core and move them to non-alpha.

**Comment by jpeach** [comment]
@mattklein123 @htuch Can you help me understand why simply incrementing the alpha version number doesn't address most of the issues here (e.g. [this](https://github.com/envoyproxy/envoy/pull/17479#discussion_r700570928) comment)

**Comment by mattklein123** [comment]
> @mattklein123 @htuch Can you help me understand why simply incrementing the alpha version number doesn't address most of the issues here (e.g. this comment)

It does work, but it's a lot more work for the project. I really don't want to go down that road.

**Comment by mattklein123** [comment]
How are you going to track which alpha version for which version? Etc.? Can we update multiple times within a release? It's just more complicated for all involved.

If people are using things in products it just can't be alpha.

**Comment by jpeach** [comment]
> How are you going to track which alpha version for which version? Etc.? Can we update multiple times within a release? It's just more complicated for all involved.

I can think of suggestions for this, but I'll avoid ratholing on it :)

> If people are using things in products it just can't be alpha.

True enough.

**Comment by htuch** [comment]
I worry have multiple alpha versions is the equivalent of multiple major versions. We know how to support it, but it's honestly a PITA if we can avoid this structurally.

**Comment by alyssawilk** [comment]
coming in late, for something like HTTP/3, would we have wanted it to land in contrib to start with?  I'm generally fine with a policy of "hide rather than alpha" for !contrib, but I think there are cases where alpha makes sense for in progress work.

**Comment by mattklein123** [comment]
> coming in late, for something like HTTP/3, would we have wanted it to land in contrib to start with? I'm generally fine with a policy of "hide rather than alpha" for !contrib, but I think there are cases where alpha makes sense for in progress work.

One other random idea: When using an alpha proto we output a stern warning that says this proto should only be used for development and should not be used in any deployments/products in which API stability is needed.

Thoughts?

I'm OK with ^ but I'm looking through the current alpha protos and some of them already need to move.

**Comment by alyssawilk** [comment]
+1 to warnings, at the very least.  One other things we could try process-wise is any alpha tagging comes with a filed issue to the author to actually get it to GA.  It'd make it easy to see who is working on it, and make the expectation that it "graduate" more clear.

**Comment by mattklein123** [comment]
OK I like the warning idea. I will work on that, and then in parallel I will start moving some over that I know are already used in production.

**Comment by jpeach** [comment]
> > coming in late, for something like HTTP/3, would we have wanted it to land in contrib to start with? I'm generally fine with a policy of "hide rather than alpha" for !contrib, but I think there are cases where alpha makes sense for in progress work.
> 
> 
> 
> One other random idea: When using an alpha proto we output a stern warning that says this proto should only be used for development and should not be used in any deployments/products in which API stability is needed.

Just to be extra clear, I'm not asking for API stability, only the ability to implement a rolling upgrade across envoy versions, which I *think* is a weaker constraint.

**Comment by mattklein123** [comment]
> Just to be extra clear, I'm not asking for API stability, only the ability to implement a rolling upgrade across envoy versions, which I think is a weaker constraint.

We understand what you are asking for. What we are saying is we aren't going to do it because it's too much work. :)

There are only 2 options we will support:

1) Full API stability
2) No API stability (alpha)

I'm going to do a change to actively warn when using an alpha proto with a link to documentation around what that means. With that said, we are willing to work with you on this as it was not as clear as it should have been. So I'm also going to start moving some of the protos I know are being used in production to non-alpha.

**Comment by mattklein123** [comment]
OK after further discussion, I think here is the final plan:

1) We will ban `alpha` in package namespaces and force migrate existing alpha packages. It's TBD whether we do this for contrib also. I would argue yes but we can sort this out later.
2) We will remove usage of the `[#alpha:] ` protodoc annotation.
3) We will add parallel message and field annotations for `work_in_progress` similar to https://github.com/cncf/xds/blob/main/udpa/annotations/status.proto.
4) Envoy will warn on usage of any message or field marked as work_in_progress that there is no support, no API stability, etc.
5) We will force work_in_progress for all contrib protos (especially if we also force migrate away from an alpha namespace)

cc @envoyproxy/api-shepherds @alyssawilk. Final call for thoughts and objections. :)

**Comment by mattklein123** [comment]
(I will work on this also as my next "side project")

**Comment by htuch** [comment]
SGTM (I'm agnostic on alpha vs. WiP terminology, so whatever works)

**Comment by alyssawilk** [comment]
I prefer alpha to WIP but given you're doing the work I'm happy to let you pick the color of the bike shed :-P

**Comment by mattklein123** [comment]
> I prefer alpha to WIP but given you're doing the work I'm happy to let you pick the color of the bike shed :-P

I don't care at all. If there is a preference for alpha we can do that. The only issue is we already have work_in_progress in one of the annotations and I don't really want to deprecate/change it, and then it would be odd to have things not matching at the field/message level? For that reason alone I would probably just stay with WIP.

**Comment by htuch** [comment]
I don't care that much, but one observation is WIP is self-descriptive, alpha has had some confusion over the years on what exactly is meant (which we have clarified with some ink).
