### ISSUE TITLE
Checking directory exists or not would be much better

### ISSUE THREAD

**Issue by qiandu2006** [envoyproxy/envoy#17944]
https://github.com/envoyproxy/envoy/blob/51b451b8b8644370ac7523c689fff3b166de4615/examples/front-proxy/Dockerfile-service#L5

`RUN [ -d /code ] || mkdir /code`

**Comment by wbpcode** [comment]
Does this example not work properly?

**Comment by qiandu2006** [comment]
My error. At this first time of building, there was "/code exists" in output. Now this problem could not be reproduced. Sorry for the interrupting!
