### ISSUE TITLE
Support multi-level locality aware routing

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1796]
Now that Envoy is aware of hierarchical locality (region, zone, sub_zone), it may be useful to be able to perform LB in a region, zone and sub_zone aware fashion. The current implementation groups these into a single flat locality identifier, so is effectively concatenating the locality names across levels.

**Comment by htuch** [comment]
@rshriram @mattklein123 is there a final direction we decided on taking on this? In any case, I don't see any major changes around this until v4.

**Comment by mattklein123** [comment]
@htuch I haven't thought about this in a while. TBH I think we should just close this until someone asks for it explicitly but up to you.

**Comment by htuch** [comment]
Ack, closing it out for now, will reopen if anyone wants this.
