### ISSUE TITLE
Tech-debt: upgrade Thrift (or move to contrib)

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#17971]
*Title*: Tech-debt: upgrade Thrift (or move to contrib)

*Description*:
At the moment Envoy uses [Thrift v0.3.9](https://github.com/envoyproxy/envoy/blob/338a42c89825653f30bd979933db94ed13619686/bazel/repository_locations.bzl#L564-L585) from twitter.common which was released on 2016-10-17.
AFAICT the project was last updated on [August 2019](https://github.com/twitter-archive/commons/tree/master/src/python/twitter/common), and is now deprecated.

Should the thrift filter extension be moved to contrib?

Pinging the extension code owners: @zuercher @rgs1

**Comment by rgs1** [comment]
I don't think we should move it to contrib/ given that we actively maintain and use it in production. Plus, there's been some new contributions from outside of Pinterest too. 

That Twitter common stuff is used for integration testing, I am happy to explore alternatives. 

cc: @fishcakez

**Comment by moderation** [comment]
From a @envoyproxy/dependency-shepherds point of view replacing the long deprecated libraries with something maintained would be preferable and align with the [Dependency Policy](https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md).

Considering the Thrift community is active I would have thought there were replacements for these long deprecated projects but last time I look I couldn't find anything.

**Comment by zuercher** [comment]
@rgs do you use the finagle thrift variant? Maybe we should drop that part? Twitter doesn't seem to be supporting it in python, but I haven't looked recently if it's still a going concern for Java/JVM-based languages.

**Comment by rgs1** [comment]
> do you use the finagle thrift variant? Maybe we should drop that part? Twitter doesn't seem to be supporting it in python, but I haven't looked recently if it's still a going concern for Java/JVM-based languages.

Not currently and in theory we could do without the finagle variant within our thrift mesh... 

cc: @fishcakez sc0ttbeardsley
