### ISSUE TITLE
where are metadata_exchange and stat wasm plugin code？I can not find them.

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#17990]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
where are metadata_exchange and stat wasm plugin code？
*Description*:
>Describe the issue.
where are metadata_exchange and stat wasm plugin code？
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Shikugawa** [comment]
@13567436138 `metadata_exchange` exists here. https://github.com/istio/proxy/tree/master/extensions/metadata_exchange
