### ISSUE TITLE
write:errno=104 SNI

### ISSUE THREAD

**Issue by GTB3NW** [envoyproxy/envoy#18028]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:  Receiving `write:errno=104` when setting up SNI

*Description*:
> Following the SNI tutorial, I missed the note at the top which mentions the requirement for it. It's good that there's a note highlighting the requirement, but requires pre-requisite knowledge of the listener filters to understand that it can't be skipped over. I think the docs would benefit from this error code `write:errno=104` to help people correct their issue quicker

[optional *Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/sni
> https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector#config-listener-filters-tls-inspector

**Comment by GTB3NW** [comment]
I'll keep this open. I've since resolved my issue but I think it could have been avoided for users who shoot themselves in the foot by missing the note, having google scrape this issue alone should help :)

**Comment by zuercher** [comment]
I believe the errno from boringssl/openssl isn't specific to an SNI issue, so I don't think it's helpful to reference the error message in the docs.

**Comment by GTB3NW** [comment]
That's true it's not specifically an SNI issue but indicative of it not being setup correctly. As I said this issue may be enough once it's crawled, to put people on the right track, so if you're happy with that I'm happy for this to be closed too :)
