### ISSUE TITLE
How to config token_bucket for each ip address when use ratelimit filter?

### ISSUE THREAD

**Issue by dozer47528** [envoyproxy/envoy#18023]
I known how to config a token_bucket for a specific ip address.

But I need to config independent token_bucket for each ip.

Can envoy support this kind of config?

Thanks.

**Comment by zuercher** [comment]
You can use the remote address descriptor to send the IP to a global rate limiting service, which can use that IP as part of its rate-limiting decision. I think to use the local rate limiter you'd have to configure a descriptor per IP and that's obviously not going to work well across large numbers of IP addresses.

**Comment by dozer47528** [comment]
@zuercher thanks, and I found the examples from this project: https://github.com/salrashid123/envoy_ratelimit
