### ISSUE TITLE
allow caching alt-svc to key-value store

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18034]
super useful for envoy mobile.

**Comment by alyssawilk** [comment]
so @envoyproxy/api-shepherds I'm hitting a problem with APIs here.

I naively tried to add key_value.v3.KeyValueStoreConfig key_value_config = 3; to AlternateProtocolsCacheOptions here:

https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/protocol.proto#L93

but that's adding a dependency from core to extensions/common which already has a dependency on core for  TypedExtensionConfig
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/common/key_value/v3/config.proto

options I can think of
1) moving the (alpha) k-v store config into common 
2) using Any/TypedExtensionConfig to not directly import the k-v store into common, but only allow the value to be the k-v store
3) break up the monolithic common api library so http-common can depend on k-v-extension can depend on typed-extension-config-common
4) insert other option here.

Preference?

**Comment by htuch** [comment]
Yeah, in general, the invariant should be core shouldn't depend on extensions. I think we can move https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/common/key_value/v3/config.proto to `envoy.config.common` as per (1).

Alternatively, if you strongly believe that `KeyValueStoreConfig` will always only have a single field, `TypedExtensionConfig`, then feel free to remove the file and just include `TypedExtensionConfig at all relevant sites. We do this with other opaque extensions.

**Comment by alyssawilk** [comment]
Oh lovely, the move didn't help because common depends on core, so core can't depend on common.  Still with monolithic configs.
