### ISSUE TITLE
com_github_fmtlib_fmt has a newer release 8.0.1

### ISSUE THREAD

**Issue by ME-ON1** [envoyproxy/envoy#18052]
*WARNING* com_github_fmtlib_fmt has a newer release than 7.0.3@<2020-08-07 13:39:57>:8.0.1@<2021-07-02 23:14:33>

**Comment by phlax** [comment]
@ME-ON1 does ` com_github_nodejs_http_parser` have a newer release that we can use ?

other ci is flagging issues with it

**Comment by phlax** [comment]
8/

**Comment by ME-ON1** [comment]
No i was working on this issue  #16705 and was running script locally but it created issues.

**Comment by phlax** [comment]
cool, if you are looking to PR updates the one i posted needs looking at so i was watching you posting hoping it would appear 8/

i can look into it tho

**Comment by ME-ON1** [comment]
> @ME-ON1 does com_github_nodejs_http_parser have a newer release that we can use ?

These are the logs coming from [release_dates.py](https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/tools/dependency/release_dates.py#L43)
Also have no knowledge about that. I'm new with code base here.

**Comment by phlax** [comment]
are you on slack ?

**Comment by ME-ON1** [comment]
Yes, with `dogebinge` name.

**Comment by moderation** [comment]
> @ME-ON1 does ` com_github_nodejs_http_parser` have a newer release that we can use ?
> 
> other ci is flagging issues with it

The latest release for `nodejs/http-parser` is a documentation change saying the project is deprecated :disappointed: 

We had a couple of folks try to get the replacement `llhttp` over the line and it looks close but not quite there yet - https://github.com/envoyproxy/envoy/pull/15814. @asraa has been leading the charge.

**Comment by phlax** [comment]
not an easyfix it seems. Also that PR keeps the legacy parser initially so the problem wouldnt go away straight away

**Comment by asraa** [comment]
yeah, it's been blocked for a while -- handed off to some other Googlers. maybe @KBaichoo knows the status? I'm not 100% sure who was taking it over...

**Comment by KBaichoo** [comment]
We (me and @yanavlasov)  haven't yet started digging into the llhttp yet, but are planning on working on it. There are a few open questions on how debuggable llhttp is given it's transpiled to C, and how patching it could work.

**Comment by phlax** [comment]
closing this as there is a newer ticket for it #18321
