### ISSUE TITLE
stats scope for grpc access log should be envoy wide

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#18066]
*Description*:

Currently an grpc access logger is instantiate using the creator' context. Usually the owner is an filter that can be destroyed.
The logger use the stats scope of the owner. It's fine if the logger is destroyed along with the owner.
However, the grpc access logger is expensive so that logger is cached. The logger can outlive its creator and the logger stats could refer a destroyed counter.

Since the grpc access loggers are shared for good, perhaps we should maintain an grpc access logger manager wide scope.
And generate server wide `access_logs.grpc_access_log.logs_written`.

Though we lost the detailed "<per_filter_prefix>.access_logs.grpc_access_log.logs_written" stats, but that counter is broken already when the cache is introduced.

cc @mattklein123 @ggreenway @jmarantz

**Comment by lambdai** [comment]
#18067 explains how to pin the scope in access logger cache.
However, #18067 finds the root scope by using the dynamic cast.
Not ideal but it avoid introducing new method in CommonFactoryContext for now

**Comment by mattklein123** [comment]
There are 2 possible fixes:
1) If logger stats need to be scoped to the creator, we can figure out a way of having the stats be passed by the creator, and not created by the logger.
2) If logger stats can be global, then I think your fix is OK.

**Comment by lambdai** [comment]
> If logger stats need to be scoped to the creator, we can figure out a way of having the stats be passed by the creator, and not created by the logger.

This approach need some work with the the logger cache. A logger attached to the stats prefix A should not be used by stats_prefix B. 

Following this path, perhaps we can split the stats part from the cached logger as in #18067 

The logger user  gets a shared logger from logger cache. 
The logger user create a new `logger with stats`, wrapping the above shared logger and offer a stat.

**Comment by jmarantz** [comment]
qq: in the current system, how often is the Stats Scope created/destroyed?

There's a fair amount of overhead for that so I wanted to make sure that was not happening per-request.

**Comment by lambdai** [comment]
> qq: in the current system, how often is the Stats Scope created/destroyed?

I don't think there are many Scope created per-request. Perhaps 0 if not close to 0.

createScope()/scopeFromElements()/scopeFromStatNames() occurrences are rare.

**Comment by ggreenway** [comment]
Yeah, as far as I can tell, we only create/destroy scopes on config updates.
