### ISSUE TITLE
Cannot extract multiple cookies from lua filter via handle:headers():get("set-cookie")

### ISSUE THREAD

**Issue by hdimitriou** [envoyproxy/envoy#18069]
**Title**: *Cannot extract multiple cookies from lua filter via `handle:headers():get("set-cookie")`*

**Description**:
I am trying to modify a cookie inside an envoy http lua filter, so inside `envoy_on_response(response_handle)` I grab the cookies via `response_handle:headers():get("set-cookie")` and that brings a string, which contains cookies delimited by comma, like `foo1=bar;Path=/;Max-Age=120,foo2=bar; Max-Age=180; Path=/`

The problem is that 'Expires' field contains a date value with comma inside for example `Expires=Fri, 10 Sep 2021 13:49:04 GMT`, which breaks my parsing, if multiple cookies are present. 

How can I solve this and parse the individual cookies?

**Comment by vparchas** [comment]
I am also interested in this. Is there a method on the `headers()` object that would return the matching headers as an array?

**Comment by zuercher** [comment]
It's possible to retrieve the individual value of multiple headers within Envoy, but that hasn't been exposed in the lua filter. Someone would have to modify the lua wrappers to allow it.

**Comment by vparchas** [comment]
Any pointers to the lua wrappers? I would like to try and give it a shot.

**Comment by agrawroh** [comment]
We have a similar requirement. I opened a PR:
https://github.com/envoyproxy/envoy/pull/18177

**Comment by hdimitriou** [comment]
So is this considered fixed?

**Comment by hdimitriou** [comment]
I wonder when will those be available on istio and which version...
Anyway thanks, i will close this issue
