### ISSUE TITLE
Allow inject-able Singletons for test

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#1808]
As disused briefly in #1802 if we need to mock out more system calls it'd probably be worthwhile instead of plumbing the OsSysCallsImpl through all relevant class hierarchies to have it be a singleton and have the Envoy Singleton class allow injection.  Then for tests we could replace the static instance with a test-only  instance which could do custom things like mock out bind calls and it would also allow testing corner cases with non-fatal syscall failure.

**Comment by akonradi** [comment]
It would be nice to do something similar for the static factory registries as well.
