### ISSUE TITLE
support formatter in tcp proxy tunneling setting

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#18128]
Tunneling in tcp proxy allows [adding arbitrary headers](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#L82)

The underlying access log formatter is created but the downstream stream info is not passed during the evaluation. So the %DOWNSTREAM_LOCAL_ADDRESS% produces "-".

It seems trivial to support it. I have it running locally and making the tcp_proxy + CONNECT consume the downstream original_dst.

Is there any concern that if we add this functionality? CC @alyssawilk

**Comment by alyssawilk** [comment]
Nope, sounds like a solid improvement!

**Comment by lambdai** [comment]
Thank you for the feedback! @alyssawilk 
/assign @lambdai
