### ISSUE TITLE
Tracing sample rates

### ISSUE THREAD

**Issue by bobbytables** [envoyproxy/envoy#1813]
Hi, I'm wondering if there's a configuration option that I'm missing from the docs for adding sample rates for OpenTracing headers to requests. Right now it seems all requests are sampled and thats not what we want exactly.

I've read this schema for the config file but I don't see anything related to what I'm curious about: https://github.com/envoyproxy/envoy/blob/master/source/common/json/config_schemas.cc

**Comment by mattklein123** [comment]
Right now the tracing sample rate is only configurable via "runtime": https://envoyproxy.github.io/envoy/configuration/http_conn_man/runtime.html

This has been raised before and it would be a very trivial change to add config options for this. cc @rshriram @objectiser

**Comment by hausdorff** [comment]
Following up from the [slack conversation](https://envoyproxy.slack.com/archives/C78HA81DH/p1514469439000093) I'll pick this up.

**Comment by hausdorff** [comment]
As far as I can tell, `tracing.client_enabled` and `tracing.global_enabled` are also only captured in the runtime. Does it make sense to add them to `tracing.proto`, too?

**Comment by michalholecek** [comment]
Hi,
so.. as of today, is it possible to limit % of requests that will be traced ? I haven't managed to find any solution.

**Comment by mattklein123** [comment]
You can do it using runtime, but the config changes have not been implemented IIRC. IT's a relatively simple change if someone wants to step up.

**Comment by bobbytables** [comment]
@mattklein123 - Is this not configurable in the HTTPConnManager? Via: https://github.com/envoyproxy/data-plane-api/blob/3cfebb2eb16e4b6b2d85a268b6dcc3e077d43b92/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L71

**Comment by mattklein123** [comment]
@bobbytables from my quick search of the code I don't think that configuration has been implemented. Those fields should be be "not implemented hidden." I can fix that today.

**Comment by shakti-das** [comment]
@mattklein123 We need this functionality, can I take it up to implement the envoy side code for it?

**Comment by mattklein123** [comment]
@shakti-das yes feel free. it should be a trivial change.

**Comment by shakti-das** [comment]
@mattklein123 One implementation specific question: If runtime and tracing_config both have values. Should the the tracing_config override the runtime?

**Comment by objectiser** [comment]
Sorry for jumping in, but definitely - the runtime config can be used as defaults, but the tracing_config would be used to provide custom tracing configure for specific situations, so must override.

**Comment by mattklein123** [comment]
@shakti-das @objectiser it's the opposite. The configured value becomes the default for the runtime lookup, and runtime overrides. There are similar examples elsewhere with the same pattern.

**Comment by objectiser** [comment]
@mattklein123 Sorry if I've confused things - maybe I'm misunderstanding the terminology.

What is the term you are using for https://github.com/envoyproxy/data-plane-api/blob/master/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L71? This is what I meant in terms of the configuration that overrides.

**Comment by mattklein123** [comment]
@objectiser what you refer to is basically the configured default value. Then we have a system called "runtime" which allows overrides (https://www.envoyproxy.io/docs/envoy/latest/operations/runtime). For example, see how we handle fault filter settings: https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/fault/fault_filter.cc#L34

The default is taken from the config, then when we call `featureEnabled` (or other runtime functions) we use the configured value as the default in the runtime lookup.

**Comment by shakti-das** [comment]
Thanks for the example, will keep the override similar.

**Comment by objectiser** [comment]
@mattklein123 Ok thanks - I was thinking that runtime meant the "runtime wide" defaults - not per request/filter.

**Comment by bobbytables** [comment]
Awesome, thanks!
