### ISSUE TITLE
No way to retrieve JWT kid as metadata

### ISSUE THREAD

**Issue by lizfeed** [envoyproxy/envoy#18138]
*Title*: No way to retrieve JWT tokens from metadata

*Description*:

The JWT option [payload_in_metadata](https://www.envoyproxy.io/docs/envoy/v1.19.1/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtprovider-payload-in-metadata) allows you to store the metadata stored in the JWT payload, for logging or further processing. However, JWT headers like [kid](https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.4) are not passed on, presumably because they are headers and not payloads.

*Why I care*:

Validating the payload in my use-case is useful because it forms part of our authentication chain: Every `kid` is valid for at most one `sub`, and so the `kid` needs to be checked to ensure a client isn't misrepresenting their `sub`.

*Note*:
"header" can be a bit confusing here. JWTs are often passed as `HTTP` headers, but JWTs themselves have headers, bits of data that aren't signed so they can be used for validating signatures. [jwt.io](https://jwt.io/#debugger-io) shows the difference between `header` and `payload` clearly.

[optional *Relevant Links*:] attached inline

**Comment by dio** [comment]
I have a draft PR here: https://github.com/envoyproxy/envoy/pull/18140. It adds a new `header_to_metadata` field, which I think will serve your use case well. I also have `dio123/envoy:jwt-auth-18138` (which has this change compiled in, it is an ubuntu-based envoy image) pushed to Docker Hub. If you have time, could you try it out (apparently I need to have a setup for jwt_authn (and add that to the examples directory of this repo to play around, hence I can validate it manually as well)? Thank you!
