### ISSUE TITLE
API breaking change detector is breaking in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#18147]
### description

its not clear if its a genuine issue, but it looks more like an issue installing the tool

first breakage in postsubmit CI was here:

https://dev.azure.com/cncf/envoy/_build/results?buildId=88659&view=logs&j=34589ac8-7a1a-5ab1-7ee8-e202f4bf08f2&t=53ebe0b6-7636-59b5-d093-fd2c4c2b2c60&l=134

**Comment by adisuissa** [comment]
Wasn't able to reproduce it, and I don't see the same breakage in later merged PRs, e.g., https://dev.azure.com/cncf/envoy/_build/results?buildId=88682&view=logs&jobId=34589ac8-7a1a-5ab1-7ee8-e202f4bf08f2 is not failing in the same place.
Note that there is another fault during "Post-job: Cache" (https://dev.azure.com/cncf/envoy/_build/results?buildId=88682&view=logs&jobId=34589ac8-7a1a-5ab1-7ee8-e202f4bf08f2&j=34589ac8-7a1a-5ab1-7ee8-e202f4bf08f2&t=968730b6-1801-4212-929c-9efb3aa743e8) that I've seen failing in other PRs, but I don't think it's related.
I'll look at some other PRs later, to see if the problem reoccurs.

**Comment by phlax** [comment]
yep, it seems it was just those 2 consecutive PRs that failed, some upstream problem i guess

either way, it seems to have gone away
