### ISSUE TITLE
tracing: Enable metadata to be specified in CLI that can be added to tracing data

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#1815]
As suggested by @htuch in https://github.com/envoyproxy/data-plane-api/pull/187#discussion_r142982630 it would be useful to enable metadata to be supplied to a proxy for inclusion in reported tracing data.

The initial use case is to enable version information, associated with the cluster being managed by the proxy, to be included.

**Comment by htuch** [comment]
One suggestion; I would keep it simple to start with, and only support basic `key: <string|int|bool>` metadata to start with. Metadata is a tree of nested structures/arrays (it's basically a JSON object), so keeping it flat would simplify implementation. Later on, if folks want hierarchical keys or representation of nested values, it could be added as an additional issue.
