### ISSUE TITLE
docker_build.sh fails with unexpected compiler version error

### ISSUE THREAD

**Issue by rnburn** [envoyproxy/envoy#1816]
When I run these steps:
```
DISTRO=ubuntu
cd ci/build_container
LINUX_DISTRO="${DISTRO}" CIRCLE_SHA1=my_tag ./docker_build.sh
```
I get the error:
```
Unexpected compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
The command '/bin/sh -c ./build_container_ubuntu.sh' returned a non-zero code: 1
```
For reference, this is the expected version from [build_container_ubuntu.sh](https://github.com/envoyproxy/envoy/blob/master/ci/build_container/build_container_ubuntu.sh#L25):
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

**Comment by jmillikin-stripe** [comment]
Ubuntu updated their GCC package. https://github.com/envoyproxy/envoy/pull/1827 should fix.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/1827
