### ISSUE TITLE
Question: Can envoy mirror tcp traffic when acting as a tcp proxy?

### ISSUE THREAD

**Issue by samitpal** [envoyproxy/envoy#18172]
I'm running envoy in tcp proxy mode. I know envoy can mirror traffic when acting in http mode, but not sure if that is possible in tcp proxy mode. I don't see any documentation which suggests  mirroring is supported in tcp mode, but I still wanted to ask.

**Comment by alyssawilk** [comment]
As far as I know that's not possible today.

**Comment by samitpal** [comment]
Ok, thanks! Closing the issue.
