### ISSUE TITLE
Fetch upstream properties (IP,port) WASM C++

### ISSUE THREAD

**Issue by M4tteoP** [envoyproxy/envoy#18198]
Hi all, I need to find out as much information as possible (IP, port, request uri) about the client that sends the request (I'm still actively working on [implementing a wasm WAF](https://github.com/envoyproxy/envoy/issues/17463)). I found[ this issue regarding RUST SDK](https://github.com/envoyproxy/envoy/issues/14440) that shows the _upstream properties_, but I can't find out where these properties are with the C++ SDK.
Thanks a lot for any help

**Comment by mathetake** [comment]
@M4tteoP  You can use `getValue` API to retrieve properties in C++ SDK. Here's an example usage in Istio: https://github.com/istio/proxy/blob/master/extensions/common/context.cc#L142-L145

**Comment by mathetake** [comment]
and JFYI you can ask Wasm questions like this in #envoy-wasm channel in Envoy slack.

**Comment by M4tteoP** [comment]
Thanks a lot @mathetake. I joined #envoy-wasm channel, see you there!
