### ISSUE TITLE
Envoy docs website returns 404

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/envoy#18215]
Official documentation website is returning 404 for any page under `latest`

Examples:
- https://www.envoyproxy.io/docs/envoy/latest
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_http1_bridge_filter

![image](https://user-images.githubusercontent.com/11142171/134367453-6ad6ed77-e2e6-4635-b02f-42cd0bf5984c.png)

Versioned docs are working:
- https://www.envoyproxy.io/docs/envoy/v1.19.1/

**Comment by nareddyt** [comment]
cc @phlax since I see you had some docs PRs

**Comment by phlax** [comment]
im working on this atm, apologies for outage

**Comment by phlax** [comment]
this should now be resolved i believe
