### ISSUE TITLE
CI flakes

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18211]
https://dev.azure.com/cncf/envoy/_build/results?buildId=89146&view=results
https://dev.azure.com/cncf/envoy/_build/results?buildId=89159&view=results
https://dev.azure.com/cncf/envoy/_build/results?buildId=89159&view=results

We're getting ~3 failures on main a day with api compat build failing. @adisuissa kindly agreed to look into it, but filing for tracking and because I noticed it's not just api compat ( it just fails more often) but tends to be colocated with other failures, e.g. verify or coverage.  I suspect some circleci hiccup is the root cause

cc @phlax @lizan

**Comment by phlax** [comment]
verify-examples mostly fails for one of 2 reasons

- docker import fails
- websocket test fails

im not seeing the first problem too often anymore, and my attempt to track it down didnt turn up anything obvious

the latter problem, is i think a bona fide flake - i can go through the test and try and make it more robust at some point

the problems with the api proto breaker are i believe related to upstream repo/s - at least when ive tracked the failures that seems to be the case

**Comment by adisuissa** [comment]
To the best of my understanding the api_compat issue is due to wrong configuration of the repository_cache flag or usage of the cache (which I'm looking at how this should be solved).

From a quick look at the verify errors, it seems they are unrelated.
