### ISSUE TITLE
SAN with wildcard after string, does not match match_subject_alt_names value

### ISSUE THREAD

**Issue by Coconut105** [envoyproxy/envoy#18235]
Hello,

We face an issue with matching the wildcarded SAN of client certificate with an exact value in the match_subject_alt_names of a listener.

If the client SAN is "test*.github.com" and the match_subject_alt_names field contains an exact value of "test123.github.com", the TLS Handshake fails with code "495 Certificate Unknown".
However, client SAN "*.github.com" works just fine.

We believe this is a bug since according to RFC 2818 “Names may contain the wildcard character * which is considered to match any single domain name component or component fragment. E.g., *.a.com matches foo.a.com but not bar.foo.a.com. f*.com matches foo.com but not bar.com.“

**Comment by yanavlasov** [comment]
This is correct DNS SAN matcher only supports the `*.` case. This is not standard compliant and needs to be improved.

**Comment by lizan** [comment]
@Coconut105 can you clarify your question? RFC 2818 doesn't state any about client certificate but server certificate for HTTPS. Since the wildcard is considered to match any single domain name component or component fragment, I don't think `test*.github.com` is supported by that statement either.

**Comment by Coconut105** [comment]
@lizan @yanavlasov https://datatracker.ietf.org/doc/html/rfc2818#section-3.2 states: "If a server has such knowledge (typically from some source external to HTTP or TLS) it SHOULD check the identity as described above (ie. Server Identity checks section)."
According to this statement, the same rules as when checking the Server Identity should be applied. Server identity checks section https://datatracker.ietf.org/doc/html/rfc2818#section-3.1 states: "Names may contain the wildcard character * which is considered to match any single domain name component or component fragment. E.g., *.a.com matches foo.a.com but not bar.foo.a.com. f*.com matches foo.com but not bar.com."

So if the same rules apply for both client and server identity verification, then test*.github.com must be supported.
