### ISSUE TITLE
Performance: Allocating stats is O(n)

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#1824]
Allocating a single stat is O(n) where n is the maximum number of stats that the shared memory can hold.  So allocating all of the stats takes O(n^2).

For the default value of 16k stats, this took approximately 1 second, which isn't unreasonable to pay when starting up and/or loading a large config.

When the maximum number of stats is 100k, my benchmark took approximately 2 minutes.

**Comment by ggreenway** [comment]
The likely fix for this is to create a lookup table for names and a freelist, so that allocating a single stat is O(log(n)) or O(1) (depending on hash-table vs binary-search-tree implementation).

This will be somewhat ugly because it must be implemented in shared-memory.

Probable implementation of hash-table: 

* Make each RawStatData into a linked-list element by having a uint64_t prev and next, which is an index into the array of RawStatData (pointers can't be used in the shared memory).
* Create a separate-chained hash table for name lookups
* Include the name hash function in the hot restart version string
* Create a free-list using the same linked-list hooks in the RawStatData.  Initially put all elements in the free list.

**Comment by mattklein123** [comment]
This is starting to cause us issues. I will fix this.

**Comment by jmarantz** [comment]
Hey Matt -- are you still working on this?  Or does it need picking up.  I'm thinking of picking up something in the perf space.

**Comment by mattklein123** [comment]
@jmarantz I was planning on doing this in the next 2 weeks, but I haven't started yet. If you want to work on it I can assign it over to you. My plan was to basically implement the hash table approach that @ggreenway outlines above (I concur that is the right approach).

**Comment by jmarantz** [comment]
OK, great.  Having noticed the gap in time I just wanted to make sure it was still on your radar.  I'm sure there's plenty of stuff to bite off apart from that.  I'm kind of looking for something that's important and complex, but not urgent.

I agree it sounds like a great approach.  I think that's consistent with this: http://vhanda.in/blog/2012/07/shared-memory-hash-table/

I'm curious as well: is there a need for concurrent access across processes, thus requiring shared-memory mutexes across a few platforms?   I was wondering about what happens during a hot-swap.

**Comment by mattklein123** [comment]
Yeah this must work with shared memory. You are welcome to work on this if you want. It's not super urgent, but we did experience production problems due to this issue so I was going to fix it.

**Comment by jmarantz** [comment]
Yes definitely in shared memory, but with concurrent access to shared memory?

**Comment by mattklein123** [comment]
Yup.

**Comment by jmarantz** [comment]
OK, I see the shared-mem mutex pattern you use now in hot_restart_impl.h.  Sure; I'll take this one.  If it's cool I'll also use this as an excuse to add https://github.com/google/benchmark so I can measure the benefit.

**Comment by ggreenway** [comment]
I suggest adding google/benchmark in a separate PR.

**Comment by mattklein123** [comment]
@jmarantz assigned it over. Feel free to reach out to myself or @ggreenway if you have any questions.

**Comment by jmarantz** [comment]
Thanks Matt.  Related PR for adding a microbenchmark infrasturcture: https://github.com/envoyproxy/envoy/pull/2348
