### ISSUE TITLE
TLS: allow specification of both type and value for SAN matcher

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#18259]
Presently SAN matcher just specifies values that can be matched against DNS, URI, EMAIL and IP elements of SAN. However it is not possible to restrict this to specific types. I.e. check DNS:www.google.com or URI:https://www.google.com

This may allow certificate validation bypasses, where a signed certificate with malformed e-mail SAN www.google.com can be used to bypass intended check for DNS SAN.

This proposal is to update certificate [matching API](https://github.com/envoyproxy/envoy/blob/5c146696351be2bac731abd501333fbac824d919/api/envoy/extensions/transport_sockets/tls/v3/common.proto#L407) to include both type and value.

**Comment by yanavlasov** [comment]
@mattklein123 @ggreenway

**Comment by mattklein123** [comment]
SGTM

**Comment by ggreenway** [comment]
SGTM

**Comment by mathetake** [comment]
+1 

[SPIFFE validator is manually ignoring non-URI SANs and check only URL SANs](https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc#L227-L238) so it would be nice we can use the new API there as well.

**Comment by pradeepcrao** [comment]
I will work on fixing this (in case no one else is actively working on a fix).

**Comment by adisuissa** [comment]
Fixed by #18628, closing.
