### ISSUE TITLE
rate limit failed to use source_cluster

### ISSUE THREAD

**Issue by xichengliudui** [envoyproxy/envoy#18269]
*Title*: rate limit failed to use source_cluster

*Description*:
> using `RateLimit.Action.SourceCluster` to configure rate limit access does not take effect，request_headers is fine

ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action

The documentation provides how to work with `request_headers`. can you provide a configuration that uses `source_cluster`? thank you very much

request_headers: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#using-rate-limit-descriptors-for-local-rate-limiting

**Comment by s-krawczyk** [comment]
Reopenning this. I lost 3 days to figure out how this works. I try to get source_cluster in incoming request without success. Nothing works. Any example. How this --sourceCluster is populated to requests? Checked the code and nothing is there that could help me. Is it passed thru headers if so than what I should enable?

**Comment by msfmydream** [comment]
@s-krawczyk I am trying to use source_cluster with local_rate_limit, Have you successfully achieved it ？
