### ISSUE TITLE
Dep release date checker seems to be inconsistent

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#18274]
### description

some PRs have started failing as the release date for `rules_go` is wrong (pr to fix is here #18273 )

the release date has  been wrong for some time so its not really clear why this would show now, this issue is to track investigating that

**Comment by phlax** [comment]
cc @moderation

**Comment by moderation** [comment]
There was a prior conversation about the possibility of the Github generated SHA changing. That is why we prefer developer generated artifacts. `rules_go` is a developer provided artifact so strange it would change.

`https://github.com/bazelbuild/rules_go/releases/download/v{version}/rules_go-v{version}.tar.gz"`

Are there other artifacts having the same issue?
