### ISSUE TITLE
test: test/integration:multiplexed_integration_test fails in frequently in CI coverage, and rarely with tsan in isolation

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#18290]
Coverage tests often fail on two test-suites:
 * test/integration:multiplexed_integration_test 
 * test/extensions/filters/http/kill_request:kill_request_filter_integration_test

I think the pass-rate for coverage is like 50% these days, making me think this is a race issue. Of course another big difference in coverage tests is possible inter-test-suite state bleed. Not sure if that is the case here.

This prompted to see if I could find tsan issues with either of those in isolation. Out of a large number of iterations I found one failure in IpVersions/Http2FrameIntegrationTest.DownstreamSendingEmptyMetadata/IPv4 captured in https://gist.github.com/jmarantz/2dd5708100def03d418e88d35583fc18

One theory we have is that this member variable's destruction is racing:
https://github.com/envoyproxy/envoy/blob/9f80d2c2c4a561dfb8b65a7fb27589ea1bc0abeb/test/integration/multiplexed_integration_test.cc#L1723

**Comment by jmarantz** [comment]
I'm having some trouble finding the PR# where that code got added, but here is the commit:

https://github.com/envoyproxy/envoy/commit/e7c114224f75571fc64542c4e641a73768e2df71

**Comment by adisuissa** [comment]
> I'm having some trouble finding the PR# where that code got added, but here is the commit:
> 
> [e7c1142](https://github.com/envoyproxy/envoy/commit/e7c114224f75571fc64542c4e641a73768e2df71)

Hmmm... probably because this test was added as part of a security patch.

The fix for the multiplexed_integration_test is in PR #18293.
