### ISSUE TITLE
[XDS] Do not track resources when there is no subscription interested in it.

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#18292]
*Title*: Do not track resources that have no subscribers. 

*Description*:
In DeltaSubscriptionState, all the resources from Server are "tracked"/put-into-resourceState without condition.  

see https://github.com/envoyproxy/envoy/blob/main/source/common/config/delta_subscription_state.cc#L125-L128

This could cause resources been tracked when there is 0 subscribers: 

1. Server sends "A, B, C" via EDS response, 
2. DeltaSubscriptionState will track them with their version, even if there is no subscription of A,B,C at all. 
3. upon reconnection, EDS will request A,B,C as they are in the resource_state_ with a version, they will be sent to the Server as if Envoy has A,B,C EdsClusters while there are none.

*Repro steps*:
See the Description section.

**Comment by stevenzzzz** [comment]
cc @ adisuissa

**Comment by stevenzzzz** [comment]
the communication between the two parties are totally async:
 after step 2, there will be a request to Server with "A" in the resource_name_unsubscribe list, b
 but in the same time, the Client could have already received an EDS response from Server with "A" in it, queued right after the CDS response, "A" gets tracked again by Envoy. 
 The EDS request with resource_name_unsubscribe{"A"} is sent to Server, server removes it from the stream, but when reconnection happens "A" will be resent to Server as it will not be removed by EDS response, while in CDS's point of view, it's already "removed" (leaked).

**Comment by adisuissa** [comment]
I think what you are describing isn't related to unsubscribed resources.
This will probably occur in the following scenario:
1. Client sends a request for resource {A}.
2. Server sends a response containing resources {A,B}.
3. Reconnect happens.
4. Client will send a request for resources {A,B}, although it only registered for {A}.

I wonder if this can be reproduced in an integration test, or if upon a reconnect `updateSubscriptionInterest` will remove the resource.

**Comment by stevenzzzz** [comment]
Yeah, it's just the scenario we are seeing in our product. 

as the title says, right now it will "track resources when there is no subscription interested in it".

**Comment by stevenzzzz** [comment]
https://github.com/envoyproxy/envoy/pull/18295 is merged, let's close this issue.
