### ISSUE TITLE
Request: add Envoy to the Homebrew package manager

### ISSUE THREAD

**Issue by rw-rs** [envoyproxy/envoy#1829]
For local development, it would be very useful to add Envoy to the macosx Homebrew package manager.

**Comment by htuch** [comment]
@rw-rs The core Envoy development team doesn't work on package management, we'd like the distributions themselves to own this. We definitely welcome community contributions here, perhaps you could drive this or file an issue with the Homebrew folks to add Envoy as a supported package?

**Comment by htuch** [comment]
@zuercher for OS X visibility.
