### ISSUE TITLE
Set "track_remaining" to true when Circuit Breaker is not explicitly configured

### ISSUE THREAD

**Issue by Fchateauvert** [envoyproxy/envoy#18312]
*Title*: *Set "track_remaining" to true when Circuit Breaker is not explicitly configured*

*Description*:
Today, if Circuit Breaking isn't explicitly configured, the feature is still enabled with some default values.

The issue is that the configuration parameter "track_remaining" is set to `false` by default.  Here is the definition of this configuration parameter: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-msg-config-cluster-v3-circuitbreakers

This is a problem since even the Circuit Breaking documentation seems to imply that these "remaining" metrics are always available, and doesn't mention that they need to be explicitly turned on:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking

Ideally, when Circuit Breaking isn't explicitly configured, track_remaining should be set to "true" in order to give users observability into whether they about to exhaust the number of configured max connections.  Alternatively, the documentation should reflect how these statistics are only available if explicitly turned on and won't be on by default.

**Comment by snowp** [comment]
These stats were made configurable to avoid bloating the already large set of cluster stats, so I don't think we'd want to enable them by default. Updating the docs to be clear about this behavior seems preferred to me
