### ISSUE TITLE
Make xDS request timeout configurable

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#1833]
Async Client uses NullRetryPolicy and the API fetcher hardcodes the upstream request timeout to 1s. This is too low in some environments, and it would be nice to make this configurable.
(https://github.com/envoyproxy/envoy/blob/master/source/common/http/rest_api_fetcher.cc#L56)

**Comment by rshriram** [comment]
please assign this to me

**Comment by jinuxstyle** [comment]
Is there any progress on this? @rshriram
