### ISSUE TITLE
CVE scanner doesnt seem to respect versions

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#18354]
### description

Currently the cve scanner is failing on the kafka dependency

We have version `2.8.1` 

The CVE only affects versions `2.0.0` -> `2.8.0`

Checking through the source code of the cve scanner i dont seen any code that handles the versions that are affected - the CVE provides 2 fields `versionStartIncluding` and `versionEndExcluding` - but these dont seem to be used

im guessing this is why the scanner is failing but im a bit confused how this isnt a recurring problem, and whether upgrading will make any difference

**Comment by phlax** [comment]
cc @htuch @moderation

**Comment by moderation** [comment]
Is the version handling code? https://github.com/envoyproxy/envoy/blob/main/tools/dependency/cve_scan.py#L209-L254

**Comment by phlax** [comment]
afaict, yes, but debugging and stepping through there is nothing (afaict) that checks the actual versions listed in the CPE

certainly in this case it returns `True` despite the current version being set as `versionEndExcluding`

**Comment by phlax** [comment]
more specifically it  returns `True` here https://github.com/envoyproxy/envoy/blob/main/tools/dependency/cve_scan.py#L239 

the `cpe.version` is set to `*` - im not totally clear why or how that is derived, but either way it doesnt seem to look at the key variable in the cpe metadata

**Comment by htuch** [comment]
I don't think the tool yet supports version ranges, only exact match and wildcard.

**Comment by phlax** [comment]
so @htuch trying to figure out a way forward

im happy to fix the tool so that it can work properly with versions, but v reluctant to do so without refactoring it into an OO pattern and adding some unit tests

shall i exclude this CVE for now (with a comment explaining why) and as time allows i can address the underlying issue ?

**Comment by htuch** [comment]
Sure, sounds like a plan.

**Comment by phlax** [comment]
workaround for current issue is here #18367

**Comment by phlax** [comment]
fixed in #19047
