### ISSUE TITLE
params_match, Method parameter definition. The key is the parameter index, starting from 0. The value is the parameter matching type.  is parameter  type int?I wander?can anyone give an example? 

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18369]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

extensions.filters.network.dubbo_proxy.v3.MethodMatch¶
[extensions.filters.network.dubbo_proxy.v3.MethodMatch proto]

{
  "name": "{...}",
  "params_match": "{...}"
}
name
(type.matcher.v3.StringMatcher) The name of the method.

params_match
(repeated map<uint32, extensions.filters.network.dubbo_proxy.v3.MethodMatch.ParameterMatchSpecifier>) Method parameter definition. The key is the parameter index, starting from 0. The value is the parameter matching type.

extensions.filters.network.dubbo_proxy.v3.MethodMatch.ParameterMatchSpecifier¶
[extensions.filters.network.dubbo_proxy.v3.MethodMatch.ParameterMatchSpecifier proto]

The parameter matching type.

{
  "exact_match": "...",
  "range_match": "{...}"
}
exact_match
(string) If specified, header match will be performed based on the value of the header.

Only one of exact_match, range_match may be set.

range_match
(type.v3.Int64Range) If specified, header match will be performed based on range. The rule will match if the request header value is within this range. The entire request header value must represent an integer in base 10 notation: consisting of an optional plus or minus sign followed by a sequence of digits. The rule will not match if the header value does not represent an integer. Match will fail for empty values, floating point numbers or if only a subsequence of the header value is an integer.

Examples:

For range [-10,0), route will match for header value -1, but not for 0, “somestring”, 10.9, “-1somestring”

Only one of exact_match, range_match may be set.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
Hi. Again, sorry for the delayed response. I am in my long holiday and cannot pay attention to every news in time.

The parameter match is used to match the dubbo RPC args. Since the type of args is determined by Dubbo RPC itself, it is very diverse. So only a few types of args can be matched correctly. Such as string or number args.
