### ISSUE TITLE
Envoy uses lots of memory even without any active connections

### ISSUE THREAD

**Issue by ppadevski** [envoyproxy/envoy#18376]
*Title*: *Envoy uses lots of memory even without any active connections*

*Description*:
I have a fairly large setup of 2500 clusters. All clusters look more or less like

{"name": "host-0", "connect_timeout": "120s", "lb_policy": "ROUND_ROBIN", "transport_socket": {"name": "envoy.transport_sockets.tls", "typed_config": {"@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext", "sni": "host-0.com", "common_tls_context": {"tls_params": {"tls_minimum_protocol_version": "TLSv1_2", "tls_maximum_protocol_version": "TLSv1_2", "cipher_suites": ["ECDHE+AESGCM:RSA+AESGCM:ECDHE+AES:RSA+AES"], "ecdh_curves": ["prime256v1:secp384r1:secp521r1"]}, "validation_context": {"verify_certificate_hash": "C2:5B:..."}}}}, "load_assignment": {"cluster_name": "host-0", "endpoints": [{"lb_endpoints": [{"endpoint": {"address": {"socket_address": {"address": "host-0.com", "port_value": 443}}}}]}]}, "cluster_type": {"name": "envoy.cluster.strict_dns"}}

I have one static listener, one static CDS cluster, one custom route that simply deduces the cluster from URL, e.g. /host-0/suffix would look up host-0 and do a rewrite. I can share the code but it isn't very interesting.

My setup has 32 CPUs. If I load all 2500 clusters I end up with 256.5m of memory usage without any connections. Let's assume that I am okay with those and am willing to waste them.

The problem happens when someone actually uses Envoy for a while. I wrote a simply python client that does a GET on each cluster in a loop and the response body is 1MB. The server always sets "connection: close" as I wanted to see the Envoy behaviour without its pools.

After I invoke the python client a couple of times which again does 2000 requests (1 connection per request), I end up with Envoy having 451.9m of memory. At this point there are no active connections whatsoever, either downstream or upstream.

So somehow I started with idle Envoy using 250 MB and ended up with idle Envoy using 450 MB. It actually gets worse. If I continuously repeat this Envoy would end up with about 650 MB after an hour and more than 1 GB after a day.

There is seemingly an absolute limit though - which in my case is 1.4 GB. I haven't been able to grow Envoy larger than that.

Now, here are some more observations.
The memory is seemingly increased rapidly during the time the responses each of 1 MB are proxied.
The per_connection_buffer_limit_bytes option on either the downstream or the upstream isn't really helping. It seemingly just slows things down but we end up in the same situation.
The memory is somehow connected to the cluster objects as if I remove all of them via CDS after I have reached 500+ MB it takes Envoy a few seconds but eventually the memory goes down to 35 MB.
Forcing an update to the cluster via CDS (e.g. by using metadata or changing some other option so that the hash is different) does NOT seemingly help. In fact, I may be wrong, but I didn't see any difference after forcing an update for all of the 2500 clusters.
This isn't seemingly caused by the allocator. I tried the default (tcmalloc), I tried gperftools, and I eventually even turned the tcmalloc off as I wanted to get a better picture of the memory as I already knew how to do so via https://github.com/vmware/chap

I believe this live core was about 500 MB and here are some of the objects that take most of the memory:

Unsigned chunks have 1893436 instances taking 0xc0dff48(202,243,912) bytes.
Signature 558c457f4e08 (std::_Sp_counted_ptr_inplace<bool, std::allocator<bool>, (__gnu_cxx::_Lock_policy)2>) has 255110 instances taking 0x7ca020(8,167,456) bytes.
Signature 558c457fa8c8 (Envoy::Common::CallbackManager<unsigned int, std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > const&, std::vector<std::shared_ptr<Envoy::Upstream::Host>, std::allocator<std::shared_ptr<Envoy::Upstream::Host> > > const&>::CallbackHolder) has 90135 instances taking 0x6e1860(7,215,200) bytes.
Signature 558c45805628 (Envoy::Upstream::HostSetImpl) has 85034 instances taking 0x160f6d0(23,131,856) bytes.
Signature 558c45803bc0 (Envoy::Router::ShadowWriterImpl) has 82534 instances taking 0x284cc0(2,641,088) bytes.
Signature 558c457fa820 (Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl::ClusterEntry) has 82533 instances taking 0x25c7d60(39,615,840) bytes.

Most of the memory is unsigned, meaning it is e.g. numbers or classes/structs without a vtable.
My strict_dns clusters resolve to 1 IPv4 address and 1 IPv6 address each yet somehow I am seemingly wasting 23 MB on those.

That being said there were no memory leaks in the application. All of the memory bloat is somehow held directly or indirectly by the clusters and the only way to cure that is to remove and consecutively add the same cluster.

Since I am running a cloud application I cannot really have 1.4 GB go to waste when I don't have any active connections. Is there an option that I am missing with which to make Envoy seemingly cache less data (if it is in fact caching slices or buffers). But again I can reproduce the issue with all allocators and seemingly there is an upper limit.

**Comment by ppadevski** [comment]
I have turned off stats completely if that matters.

**Comment by mattklein123** [comment]
It's hard to say where the memory is being used without a more complete graph of memory allocations. I knew how to do that on the old tcmalloc, but I'm not sure how to do it with the new one. cc @jmarantz @rojkov who can hopefully help get a better flame graph of allocations with attribution so we can better figure out where the memory is living.

If there are truly no active connections (either downstream or upstream) I'm surprised that any memory is being held. Can you provide a dump of `/stats` showing all the stats when you think there are no connections?

**Comment by ppadevski** [comment]
One other observation:

I am actually using OpenSSL. When I switch to BoringSSL by default the situation is a bit better:
275 MB initial (vs 250 MB OpenSSL) and 430 MB 1h later (vs 800 MB+ OpenSSL)

The memory is increasing rapidly from 275 MB to about 400 MB during the initial 2000 requests and then slowly by ~5 MB for next 1h till it reaches 430 which is a far better upper limit than 1.4 GB). I'll leave it running for a while and we'll see.

Since I am making 2000 request which make 2000 distinct connections for 2000 distinct clusters and maybe they hit different workers it is possible that something is eagerly initialised at first and then initialised slower in threads that it wasn't previously initialised in.

I believe that on a setup with just 4 CPUs (vs 32 CPUs) the memory usage after 1h is ~330 MB but I don't have the initial memory (I think it was about 175-200 MB).

Let me see if I can gather /stats next week but again not sure what it would display if stats are turned off via stats_matcher: reject_all: true.

If the memory does not go above 500 MB for 32 CPUs I guess I can live with it but it will take me some time to gather other measurements.

Does anybody know if thread local clusters are eagerly/lazily initialised and if they happen to cache certain objects (slices, buffers, SSL, etc)? Does anybody want to make a guess as to why the first requests for each cluster increase memory?

**Comment by rojkov** [comment]
Thanks for reporting! Could you please put your configs here? I'd like to reproduce the setup.

**Comment by jmarantz** [comment]
just wanted to mention quickly (I know the issue is closed) that turning off stats completely breaks some functionality. https://github.com/envoyproxy/envoy/issues/14051 discusses that issue.
