### ISSUE TITLE
Optimize TrieLookupTable

### ISSUE THREAD

**Issue by mergeconflict** [envoyproxy/envoy#18405]
@mattklein123 put [some work](https://github.com/envoyproxy/envoy/pull/223), many years ago, into optimizing `HeaderMapImpl` for header lookups that are constant-time in terms of the total number of headers. More recently, @ramaraochavali [extracted the Trie code](https://github.com/envoyproxy/envoy/pull/5512) into `common` for use in Redis.

I was poking around a bit, looking at some performance data from our Envoy deployments at Google, and found that we spend about 1-2% of our CPU time on the worker threads in `Envoy::TrieLookupTable::find`, called from `Envoy::Http::HeaderMapImpl::StaticLookupTable::lookup`. If we can squeeze a bit more performance out of this, it's worthwhile for us, and I think I may have found a way to do so.

The current `TrieLookupTable` implementation is sparse and uncompressed: each `TrieEntry` contains an array with 256 entries, keyed by a single character. We can think of `find()` as being worst-case O(_n_) in terms of the number of characters in the `string_view key`: we traverse entries until we either know the trie doesn't contain our key, or we've found it. Of course, any lookup implementation will have O(_n_) worst case time complexity in the length of the key (for example, if we just used a hash map, we have to look at all the characters to compute a hash), but the repeated pointer traversal may add a significant constant factor. Pointer traversal is more expensive than accessing sequential bytes in CPU cache.

So I did a bit of digging in the literature and found a couple data structures for this purpose that are more cache-friendly:

* [Cache-conscious string hash tables](https://people.eng.unimelb.edu.au/jzobel/fulltext/spire05.pdf): a fast, unordered hash optimized for strings.
* [HAT-Trie](https://sjmulder.nl/dl/pdf/compsci-databases/2017-askitis-hattrie.pdf): an ordered prefix trie that is compressed to achieve similar lookup performance to the cache-conscious hash table, with lower memory consumption.

There are some promising benchmarking results in these papers, but I haven't yet done any benchmarking in the context of Envoy yet, to compare the current implementation against them (or, for that matter, against `absl::flat_hash_map`). Matt [previously pointed out](https://github.com/envoyproxy/envoy/pull/11546#issuecomment-642382512) that we probably need to flesh out our existing benchmarks more. I know @adisuissa has done some work in this area before as well, so we'll chat and figure out the right thing to do.

**Comment by jmarantz** [comment]
Also consider perfect hash-tables for a set of keys known at compile-time: https://www.gnu.org/software/gperf/manual/gperf.html

**Comment by jmarantz** [comment]
FWIW sample gperf usage in a C++ system built with bazel:
 * https://github.com/apache/incubator-pagespeed-mod/blob/41aa63a027ed428b86ecaf2a1eaf3fda28d821b8/net/instaweb/rewriter/BUILD#L162
 * https://github.com/apache/incubator-pagespeed-mod/blob/master/net/instaweb/rewriter/rewrite_filter_names.gperf

It'd be worth just doing the easiest thing first though and try using absl::flat_hash_map.

**Comment by mattklein123** [comment]
> It'd be worth just doing the easiest thing first though and try using absl::flat_hash_map.

Agree this is worth trying. This trie code originates from 5+ years ago, well before we were using abseil, and in response to some silly horse race benchmarks with nginx. There are likely better ways of doing it than this simple trie.

**Comment by adisuissa** [comment]
+1 on first trying to use `absl::flat_hash_map` which I think is a very simple change to make it happen.
As for the kind of benchmarks, IIUC most of the header names have the same prefix, so we should aim for tests that capture this scenario. Not sure if there's a known distribution of the header name length, but I guess we should test various lengths between 4 to 128.

**Comment by jmarantz** [comment]
RE "same prefix": can you give examples?

I was thinking of very common things like "Date", "Cache-Control", "Content-Type", "Cookie".

There's also the common case where a bunch of custom headers are in use and they all fail the builtin-header lookup. Failing that lookup should be fast too.

**Comment by adisuissa** [comment]
I meant the ones that use [this prefix](https://github.com/envoyproxy/envoy/blob/bcf6729041263b824c97c74f3618fa649fd83f8e/source/common/http/headers.h#L128). I guess that some of the other (e.g., those that start with "content-" or "grpc-" can also be considered using the same prefix).

**Comment by jmarantz** [comment]
That dynamic-ish prefix makes it less elegant to use something like gperf, but my suspicion is that with absl::flat_hash_map we could get some benefit without having to think too much about a hierarchical prefix lookup first. It'd be best to get some benchmarks.

**Comment by mergeconflict** [comment]
Alright, I did some basic benchmarking of a few different implementations, including the "HAT-Trie" I linked above. I will try to present the benchmark code and the results in some reasonable format here tomorrow, but for now I'll summarize: `absl::flat_hash_map` seems like a good choice. Probably somewhere between 10-100x faster than the current implementation in my environment, depending on the number of entries and the length of the keys.

**Comment by jmarantz** [comment]
I feel like 100 entries and 16 chars is the most relevant example, where it's 5x better to use hash for hits, and 3x better to use tries for misses. This is looking closer to a wash if we expect half the headers to not be builtin http ones.

It'd be better to look at sets of http headers specifically.

**Comment by jmarantz** [comment]
Matt -- do you have a sense of what percentage of headers seen by Envoys (including response & request) are in the O(1) set?

I could imagine that traffic to/from browsers largely use known headers, but internal API traffic may use all sorts of non-standard headers.

I was poking around httparchive.org, which I thought in the past had given me queryable access to a ton of internet web data including response headers, but I couldn't figure out how to do it anymore -- now it's just predefined queries.

**Comment by mattklein123** [comment]
> Matt -- do you have a sense of what percentage of headers seen by Envoys (including response & request) are in the O(1) set?

Sorry no clue, as you say I'm sure it very much depends on the workload.

**Comment by mattklein123** [comment]
(Honestly, I would say, test deploy the switch to flat_hash_map at Google and if it looks better across various workloads just make the change upstream.)
