### ISSUE TITLE
Https Client in envoy

### ISSUE THREAD

**Issue by slimshady986** [envoyproxy/envoy#1841]
Hello guys,

I am building a simple Decoder Filter. I need to do a **blocking** call to an **HTTPS** external endpoint to access an information an to embed the response into the incoming HTTP request header. Is there any code in envoy that can be leveraged to do this call ? If yes, can you pinpoint the code part(s) to use ?

Thanks in advance,

**Comment by mattklein123** [comment]
You want to use AsyncClient:
https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/async_client.h

Wrapper code used in various places:
https://github.com/envoyproxy/envoy/blob/master/source/common/http/rest_api_fetcher.h

**Comment by mattklein123** [comment]
Closing. Please reopen if you have further questions.

**Comment by slimshady986** [comment]
Hello Matt, Thanks for your answer. I am trying to use the async client as suggested.
1) In order to use the client in a blocking manner as explained in my first question, I suppose  that I need to use the FactoryContext dispatcher with a _Block_ RunType  ?
2) I am trying to test it as follow but I have a segmentation fault (on the sending line) when running the server:
```
HttpFilterFactoryCb Oauth2ProxyFilterConfig::createFilterFactory(const Json::Object &config,
                                                                             const std::string &,
                                                                             FactoryContext &context) {
                config.validateSchema(Json::Schema::OAUTH2_PROXY_HTTP_FILTER_SCHEMA);

                std::cout << "TRACE1" << std::endl;
                Http::MessagePtr message(new Http::RequestMessageImpl());
                message->headers().insertMethod().value().setReference(Http::Headers::get().MethodValues.Get);
                message->headers().insertHost().value().setReference("local_service");
                TestCallback * cb =  new TestCallback();
                std::cout << "TRACE2" << std::endl;

                context.clusterManager().httpAsyncClientForCluster("local_service")
                       .send(std::move(message),*cb,Optional<std::chrono::milliseconds>(std::chrono::milliseconds(1000)));
```

with 

```
class TestCallback : public Http::AsyncClient::Callbacks {
        void onSuccess(Http::MessagePtr&& ) {
            std::cout << "TRACEonSuccess" << std::endl;
        }

        void onFailure(Http::AsyncClient::FailureReason) {
            std::cout << "TRACEonFailure" << std::endl;
        }
    }
```
Thanks in advance,
Chadi

**Comment by mattklein123** [comment]
@slimshady986 nothing blocks in Envoy. Everything must be async. If you are looking for a simple blocking programming model please take a look at the LuaJIT filter in https://github.com/envoyproxy/envoy/pull/1859. This will merge for alpha usage this week. 

The best I can offer you for how to make a call in inline in a filter is the RL filter, but that is gRPC: https://github.com/envoyproxy/envoy/blob/master/source/common/filter/ratelimit.cc
