### ISSUE TITLE
Support FIPS builds on CentOS 7

### ISSUE THREAD

**Issue by bartsmykla** [envoyproxy/envoy#18425]
*Title*: *Support FIPS builds on CentOS 7

*Description*:
When you want to build envoy with FIPS in mind today you can do it only on Ubuntu/Debian.
I understand that we are following [this certification document](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3678.pdf) issued for Google to build FIPS "compliant" version of BorringSSL and according to this document, the build was tested only on:

- Debian Linux 4.19.37 (Rodete) running on HPE Z620 with Intel Xeon E5-2680 with PAA
- Debian Linux 4.19.37 (Rodete) running on HPE Z620 with Intel Xeon E5-2680 without PAA
- Ubuntu Linux 18.04 running on Google Arcadia-Rome with AMD Rome with PAA
- Ubuntu Linux 18.04 running on Google Arcadia-Rome with AMD Rome without PAA
- Ubuntu Linux 18.04 running on Zaius P9 with POWER9 with PAA
- Ubuntu Linux 18.04 running on Zaius P9 with POWER9 without PAA (single-user mode)

I would like to suggest to switch to [other certification document](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4028.pdf) issued for VMware and follow their instructions for building BoringSSL as according to this document, the build was tested on:

- Amazon Linux 2 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Amazon Linux 2 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Photon OS 2.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Photon OS 2.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Photon OS 3.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6126R with AES-NI
- Photon OS 3.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6126R without AES-NI
- Photon OS 3.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Photon OS 3.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Photon OS 4.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Photon OS 4.0 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Red Hat Enterprise Linux 7.9 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Red Hat Enterprise Linux 7.9 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Red Hat Enterprise Linux 8.2 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Red Hat Enterprise Linux 8.2 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Ubuntu 18.04 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Ubuntu 18.04 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Ubuntu 20.04 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Ubuntu 20.04 on ESXi 7.0 running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI
- Ubuntu 20.04 running on Dell PowerEdge R740 with Intel® Core i5 with AES-NI
- Ubuntu 20.04 running on Dell PowerEdge R740 with Intel® Core i5 without AES-NI (single-user mode)
- Within ESXi 7.0 (as a host) running on Dell PowerEdge R740 with Intel® Xeon Gold 6126R with AES-NI
- Within ESXi 7.0 (as a host) running on Dell PowerEdge R740 with Intel® Xeon Gold 6126R without AES-NI
- Within ESXi 7.0 (as a host) running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R with AES-NI
- Within ESXi 7.0 (as a host) running on Dell PowerEdge R740 with Intel® Xeon Gold 6230R without AES-NI

doing so we'll be able to build envoy FIPS version of Envoy for CentOS 7/8. The changes are actually not very complicated and are involving downloading version of llvm+clang for other linux distributions and compiling `ninja-build` from the repository.

I'm happy to introduce the patch if the community will be willing to accept it :-)

*Relevant Links*:
https://github.com/envoyproxy/envoy/issues/16678
https://github.com/envoyproxy/envoy/blob/54b686bb5f16cae0d506293fbefb82ab5588c3d3/bazel/external/boringssl_fips.genrule_cmd
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3678
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4028

**Comment by bartsmykla** [comment]
I created PR with the changes I described above: https://github.com/envoyproxy/envoy/pull/18426

**Comment by lizan** [comment]
I'm OK with the VMware certification document, the only question here is that seems to come out later than BoringSSL, and it might delay the updating process of BoringSSL FIPS in the future. @bartsmykla any idea on that?
