### ISSUE TITLE
envoy.reloadable_features.health_check.graceful_goaway_handling deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18438]
Your change #13599 (HTTP health checker: handle GOAWAY from HTTP2 upstreams) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
reminder ping!

**Comment by daixiang0** [comment]
Could I take it if possible?
