### ISSUE TITLE
envoy.reloadable_features.preserve_downstream_scheme deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18441]
Your change #15321 (http: sending the original url scheme (or best guess) upstream.) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by daixiang0** [comment]
@alyssawilk Could I take it if possible?

**Comment by alyssawilk** [comment]
oh I already have the change queued up and ready to go, just waiting for the merge conflicts to die down.  generally we have the PR author do their own clean up but we're happy to have folks help with stale ones.

**Comment by alyssawilk** [comment]
oops - this one looked stale but we actually intentionally defered it one release so I'm on it now :-)

**Comment by daixiang0** [comment]
Thanks, I will work on other things.
