### ISSUE TITLE
envoy.reloadable_features.use_observable_cluster_name deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18447]
Your change #15139 ([cluster] Use `alt_stat_name` for general observability purposes (access log, tracing, admin)) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by daixiang0** [comment]
@alyssawilk still available?

**Comment by daixiang0** [comment]
I'd like to take it.
