### ISSUE TITLE
use envoy.reloadable_features.remove_legacy_json deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18451]
Your change #14467 (Replace rapidjson with nlohmann/json) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by asraa** [comment]
@dio do you know if anyone has been running this with the flag flipped to true?

**Comment by dio** [comment]
> the flag is false by default

@alyssawilk oops sorry too fast to comment. Will ask around.

**Comment by dio** [comment]
@wbpcode could you help to test this, since it seems you have a sensible environment to test this given: https://github.com/envoyproxy/envoy/issues/4705#issuecomment-599934902. Thanks!

**Comment by dio** [comment]
Talked to @ramaraochavali from Salesforce offline, it seems he can help to test this in their environment. Thanks, @ramaraochavali!

**Comment by ramaraochavali** [comment]
@dio we deployed with that run time flag and basic flows (Service -> Service) communication are working

**Comment by wbpcode** [comment]
@dio Sorry for the delayed reply. I can do a quick test in my local env with config of the production environment.

**Comment by wbpcode** [comment]
It works well for me. Although in my scenario, I just use it to convert a string into a Json object and process the sub-objects in it.
