### ISSUE TITLE
build: Unable to build with bazel native proto_library

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#1847]
When we migrate https://github.com/istio/api/pull/199 to a bazel native proto_library and want to link them against bazel, without using `envoy_proto_library`, it will result link errors because envoy use custom protobuf. There is no way to workaround it.

We have options:
1. Migrate envoy build to use bazel native `proto_library`.
2. Have a easy workaround to bind external proto_library. The `protobuf_bzl` and runtime library should be easy swapped.

IMO in long term 1. is ideal, while in short term 2 is acceptable. WDYT? @htuch

**Comment by htuch** [comment]
As discussed offline, we need to eventually support some fairly heavy `.bzl` customization for the `proto_library` in order to allow proto constraints code generation via https://github.com/lyft/protoc-gen-validate. See https://github.com/lyft/protoc-gen-validate/blob/master/bazel/pgv_proto_library.bzl and https://github.com/lyft/protoc-gen-validate/blob/master/bazel/protobuf.bzl.

**Comment by lizan** [comment]
Took a quick look on `protoc-gen-validate`, and it doesn't look like it will conflict with native proto_library that much.

The essential problem is envoy tries to link against prebuilt protobuf runtime library, while native proto library tries to look up runtime library in different path. (for C++ its defaulted to `@com_google_protobuf_cc//:protobuf`.

I think in short term 2. will be achievable via #1682, this will allow us to not use Envoy's prebuilt protobuf but bind from `@com_google_protobuf_cc//:protobuf`. With some additional cosmetic changes accross `data-plane-api` and `envoy`, to rename `protobuf_bzl` to `com_google_protobuf`/`com_google_protobuf_cc` then they would be interchangeable.

**Comment by htuch** [comment]
I agree, I think we are fine consuming off-the-shelf protoc and libs from some single canonical source. Where we need customization is in the `protobuf.bzl` rules for invoking `protoc`. Let's make #1682 the plan-of-record (@jmilikin-stripe) and while that's being merged I'll try and surface `protoc-gen-validate` in the `data-plane-api` and `envoy` build systems for C++.

**Comment by htuch** [comment]
I think we need option 1 for a few other reasons as well, so closing this issue out and following up with the concrete tracking issue for this in #1873.
