### ISSUE TITLE
Extending Envoy for custom load balance strategy

### ISSUE THREAD

**Issue by richardor** [envoyproxy/envoy#1848]
How to extend envoy for my own load balance strategy? 
I want to proxy the clients which contains the same infomation to the special server.
thank you.

**Comment by mattklein123** [comment]
@richardor I'm sorry I don't understand the question. Please provide a lot more detail regarding what you are after.

**Comment by richardor** [comment]
@mattklein123 
Thanks for your reply.
For example, we are developing a video meeting product with gRPC.  I want to route the clients of the same room to the same erver.  
But the envoy's load balance doesnot support it. May be I can extend the http filter for grpc, I donot know.

**Comment by richardor** [comment]
@mattklein123 
maybe I can use subset load balancer, verified by the room id.
Does it support grpc？ 
https://github.com/envoyproxy/envoy/blob/master/source/docs/subset_load_balancer.md

**Comment by mattklein123** [comment]
Subset LB is currently under development by @zuercher. By the sounds of it, I think your best bet is probably to ring hash on  a header and stick your room ID in a header. This could be gRPC "metadata" (HTTP headers).https://envoyproxy.github.io/envoy/configuration/http_conn_man/route_config/route.html#config-http-conn-man-route-table-hash-policy

**Comment by mattklein123** [comment]
Closing this out as answered. Please reopen if not.
