### ISSUE TITLE
Build error: no such package '@protobuf_bzl//'

### ISSUE THREAD

**Issue by grobinson-blockchain** [envoyproxy/envoy#1850]
I get the following build error with Bazel:

    bazel build //source/exe:envoy-static
    External dependency cache directory /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
    make: Entering directory '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps'
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/backward.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/backward.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/backward.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gcovr.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gcovr.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gcovr.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/googletest.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/googletest.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/googletest.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/http-parser.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/http-parser.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/http-parser.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/protobuf.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/protobuf.dep.log
    DEBUG: /root/envoy/bazel/repositories.bzl:18:5: Fetching external dependencies...
    DEBUG: /root/envoy/bazel/repositories.bzl:24:5: External dep build exited with return code: 256
    DEBUG: /root/envoy/bazel/repositories.bzl:25:5:
    DEBUG: /root/envoy/bazel/repositories.bzl:26:5: Timed out; also encountered an error while attempting to retrieve output
    ERROR: Skipping '//source/exe:envoy-static': error loading package 'source/exe': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed
    WARNING: Target pattern parsing failed.
    ERROR: error loading package 'source/exe': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed
    INFO: Elapsed time: 705.921s
    FAILED: Build did NOT complete successfully (0 packages loaded)
        currently loading: source/exe

on `v1.4.0` branch. I've tried clearing the Bazel cache and restarting the build - but it then fails on this step.

The build is running on Debian version:

    Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux

with Bazel version:

    Build label: 0.6.1
    Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Thu Oct 5 21:54:59 2017 (1507240499)
    Build timestamp: 1507240499
    Build timestamp as int: 1507240499

**Comment by grobinson-blockchain** [comment]
Sometimes, the protobuf dep passes, and I get this error:

    bazel build //source/exe:envoy-static
    External dependency cache directory /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
    make: Entering directory '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps'
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/backward.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gcovr.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/googletest.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/http-parser.dep' is up to date.
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/protobuf.dep' is up to date.
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep.log
    Loading: 0 packages loaded
        currently loading: source/exe
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep
    make: Leaving directory '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps'

    real    7m57.674s
    user    6m25.900s
    sys 0m24.180s
    DEBUG: /root/envoy/bazel/repositories.bzl:18:5: Fetching external dependencies...
    DEBUG: /root/envoy/bazel/repositories.bzl:24:5: External dep build exited with return code: 0
    DEBUG: /root/envoy/bazel/repositories.bzl:25:5:
    DEBUG: /root/envoy/bazel/repositories.bzl:26:5: External dependency cache directory /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
    make: Entering directory '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps'
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/backward.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gcovr.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/googletest.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep' is up to date.
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/http-parser.dep' is up to date.
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/lightstep.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep
    make: '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/protobuf.dep' is up to date.
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/rapidjson.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/spdlog.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/tclap.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep
    Building in /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.build, logs at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.log
    Successful build of /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep
    make: Leaving directory '/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/envoy_deps'

    real    7m57.674s
    user    6m25.900s
    sys 0m24.180s
    ERROR: in target '//external:cc_toolchain': error loading package '@local_config_cc//': Extension file not found. Unable to load file '@local_config_cc//:dummy_toolchain.bzl': file doesn't exist or isn't a file
    INFO: Elapsed time: 478.660s
    FAILED: Build did NOT complete successfully (5 packages loaded)
        currently loading: @local_config_cc//

**Comment by grobinson-blockchain** [comment]
Small update: The build fails with this error for tag `v1.4.0` but not for master.

**Comment by htuch** [comment]
Bazel 0.6.1 will work with master. For v1.4.0, you probably want something more like 0.5.2 or 0.5.3.

**Comment by mattklein123** [comment]
Closing as answered.
