### ISSUE TITLE
how to delete gperftools for build envoy

### ISSUE THREAD

**Issue by NameHaibinZhang** [envoyproxy/envoy#18540]
*Title*: *One line description*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

 I want build envoy for chinese cpu, but gperftools is not use for this, how to delete this

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by rojkov** [comment]
You can disable tcmalloc with
```
bazel build -c opt //source/exe:envoy-static --define=tcmalloc=disabled
```
