### ISSUE TITLE
what typed_extension_config does load_balancing_policy have?no document?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18542]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
config.cluster.v3.LoadBalancingPolicy.Policy¶
[config.cluster.v3.LoadBalancingPolicy.Policy proto]

{
  "typed_extension_config": "{...}"
}
typed_extension_config
(config.core.v3.TypedExtensionConfig)
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by davinci26** [comment]
None. This is an entry point for users to develop they own extension to handle LoadBalancingPolicy.
