### ISSUE TITLE
Load balancing and persistent connections

### ISSUE THREAD

**Issue by natetarrh** [envoyproxy/envoy#1855]
Hi! I looked for documentation around this and wasn't able to find anything salient.

How does Envoy behave when load balancing persistent HTTP/2 connections to an upstream cluster? Specifically, how does it handle cases where hosts are added or removed to a cluster that uses strict DNS service discovery? Will it rebalance traffic when hosts are added, or will it only balance new connections to new hosts? 

We're looking to address issues we have with using Kubernetes services to load balance persistent gRPC connections, where we see uneven load balancing behavior that persists after a rolling restart of pod backends.

**Comment by mattklein123** [comment]
I thought we had docs on this but I can't quickly find them. Will do an update at some point. 

The answer is that load balancing is at the request level, not the connection level. Traffic will be rebalanced as hosts are added and removed.

**Comment by natetarrh** [comment]
Thanks Matt!
