### ISSUE TITLE
integration tests using different language/libraries

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#186]
Right now all of our integration tests use Envoy itself for fake clients and fake upstreams. This is useful for ease of testing (compiles to a single binary), but it would be good to have an additional set of tests that are written using a different language (probably Go) so that we can test interop.

cc @louiscryan

**Comment by mattklein123** [comment]
@PiotrSikora per discussion are you interested in taking ownership of this? (No delivery timeframe implied by saying yes).

**Comment by mattklein123** [comment]
It would be also good to use this framework for stress testing.

**Comment by PiotrSikora** [comment]
Yes, please assign this to me.
