### ISSUE TITLE
gRPC-web am I able to add metadata containing apiKey within envoy?

### ISSUE THREAD

**Issue by jereloh** [envoyproxy/envoy#18607]
*Title*: *gRPC-web am I able to add metadata containing apiKey within envoy?*

*Description*:
Currently passing through the apiKey within the metadata through react.js. Also able to use Kreya (grpc-web client) to test grpc-web adding the metadata of {apiKey: "token_abc"} and is working fine.

Can I use envoy to add the metadata so that the apiKey does not get exposed on the browser?
e.g. react.js -> envoy (also to add apiKey metadata like a middleware) -> grpc svr

**Comment by dio** [comment]
Seems like this is similar to [`GrpcService.initial_metadata`](https://github.com/envoyproxy/envoy/blob/45ec050f91407147ed53a999434b09ef77590177/api/envoy/config/core/v3/grpc_service.proto#L295)? Currently, the [`GrpcWeb`](https://github.com/envoyproxy/envoy/blob/136e11d8300d3f6713e909b6ff634c85ea1f2824/api/envoy/extensions/filters/http/grpc_web/v3/grpc_web.proto#L17) filter doesn't have further configurations when communicating with the upstream gRPC service.

**Comment by markdroth** [comment]
@wenbozhu may be able to advise further about grpc-web semantics.

**Comment by wenbozhu** [comment]
@jereloh   could you try what @dio suggested? 

If we need fix how Envoy configures metadata (headers) for grpc-web initiated upstream grpc calls, please help file a feature request.
