### ISSUE TITLE
what are Original Dst Filter and Original Src Filter functions?the doc is too simple !

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18602]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

Original Dst Filter:
Use the Original destination address on downstream connections.

Original Src Filter:
Use the Original source address on upstream connections.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by davinci26** [comment]
See [Original Destination](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_dst_filter) it queries for `SO_ORIGINAL_DST` which allows envoy to know the original destination of a connection that has been redirected by IPTABLES.

This is useful to program envoy to run as sidecar.


Original Source is similar but it gives you the original source of the connection
