### ISSUE TITLE
Setting `auto_sni` causes a spike in the number of active upstream connections

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#18617]
### Title

When the `auto_sni` flag is set as `true` we are seeing a visible spike in the number of active upstream connections.

### Description

We are seeing increased number of **Active Upstream Connections** when `auto_sni` flag is set as `true` in the `UpstreamHttpProtocolOptions`. [[Link]](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto)

We are not specifying `auto_san_validation`. We do see a drop in the Active Upstream CX after turning off the `auto_sni`.

**Configuration:**

```scala
name: "some-cluster",
connect_timeout: "50ms",
load_assignment: ...,
max_requests_per_connection: 10000,
typed_extension_protocol_options: {
  "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
    "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
    explicit_http_config: {
      http_protocol_options: {}
    },
    upstream_http_protocol_options: {
      auto_sni: true,
    },
  },
},
```

**Metrics Screenshot:**

![Screen Shot 2021-10-13 at 11 38 07 AM](https://user-images.githubusercontent.com/12120828/137217968-dd93ac7d-85d4-4d42-83a3-f75396e4175e.png)

**Comment by agrawroh** [comment]
@mattklein123 I was able to verify that it doesn't happen when we just have a single SNI. We are using [override_auto_sni_header](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#:~:text=with%20auto_sni%20field.-,override_auto_sni_header,-(string)%20An%20optional) and there are certain requests which when doesn't have this header set making the SNI fallback to the "host". We can close this question now.

_"Every SNI requires a new connection pool, since all connections must have that SNI attached to it."_

Do you think we should add 1-2 lines about this in the docs? It wasn't very intuitive for me. If you are okay I can open a small PR to add the additional info.

**Comment by mattklein123** [comment]
> Do you think we should add 1-2 lines about this in the docs? It wasn't very intuitive for me. If you are okay I can open a small PR to add the additional info.

Sure doc updates are always appreciated! Thank you.
