### ISSUE TITLE
Support certificate chain and private key via PFX/PKCS12

### ISSUE THREAD

**Issue by anrossi** [envoyproxy/envoy#18615]
Allow customers to provide Envoy with a TLS certificate via PFX/PKCS12 file.
This would create a new `DataSource` field on the [TlsCertificate](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-tlscertificate) message called `pfx_file`. This field will be functionally mutually exclusive with the `certificate_chain` and `private_key` field, since it cannot be marked `oneof` for API compatibility reasons.
Not sure on how to interact with the `watched_directory` field; I prefer not doing filesystem monitoring for `pfx_file`, since my read of the documentation is that `watched_directory` is only for SDS, which doesn't use PFX/PKCS12.
The existing `password` field would be used to provide the password for decrypting the PFX/PKCS12 file, if it is encrypted.

This enables a specific customer scenario on Windows, as well as simplifies the distribution of the certificates and private keys on all supported platforms, since it's a single file, instead of multiple.

**Comment by mattklein123** [comment]
I don't know too much about this area, but a couple of thoughts:
1) Could we just auto detect whether it's PFX/PKCS12 and have it "just work" without any other API changes? IMO this would be optimal.
2) If not I wonder if instead of a new file field, would we want some type of cert_chain_type field that would say whether it's of this type?

Both of those seem better than adding a new file field specifically for this, but I don't feel too strongly about it. cc @lizan @ggreenway for further thoughts.

**Comment by anrossi** [comment]
@mattklein123 
Regarding 1) that's possible, but because the PFX/PKCS12 contains both a private key and certificate (and potentially also a certificate chain), does it belong in the `certificate_chain` field, or the `private_key` field?
The only way I know to do this would be to trial call the API for reading the PFX/PKCS12 and on failure go on to the existing API calls.
Regarding 2) This would make it much easier to reuse the existing field, IMO, because then the specific type is specified, and there's no need for trial API calls.

I don't feel strongly about either approach as long as the support is added in a way consistent with the rest of the API. To me, that seemed like a new field, but I'm new to the Envoy project, so maybe a type field is more consistent with the design.

**Comment by htuch** [comment]
Not strong opinoins, but we could solve (1) above by pointing _both_ `certificate_chain` and `private_key` at the same PFX/PKCX12 file, and the semantics would be that Envoy extracts the relevant part of the file when this happens with this format.

**Comment by anrossi** [comment]
I'm not a fan of that approach because `PKCS12_parse` returns both, which means part of the result would be discarded for each field and the work duplicated, and it still requires a trial call of `d2i_PKCS12_bio` before trying the other formats.

**Comment by mattklein123** [comment]
I'm fine with a new field. Do you want to just do the API and docs first and we can discuss in a PR?
