### ISSUE TITLE
Envoy v1.20.0 slower to re-initialize dynamic listeners

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#18616]
*Description*:
It appears Envoy v1.20.0 is a bit slower to re-initialize dynamic listeners for which configuration has changed.

As part of regular dependency bumps, when bumping Contour's dependency on Envoy from v1.19.1 to v1.20.0 (see [PR](https://github.com/projectcontour/contour/pull/4075)) we have seen our end-to-end tests fail/take quite a lot longer to run to completion. These test repeatedly create/delete k8s Ingress/Contour HTTPProxy/Gateway API *Route objects that the Contour controller programs Envoy dynamically with over xDS. The tests update these k8s resources and then assert requests to Envoy succeed. We've seen the time taken for requests to succeed when config is updated increase substantially when bumping to v1.20.0 with the same Contour controller code.

With a `git bisect` of commits betwen v1.19.0 and v1.20.0, it *seems* that we can narrow this slowdown to [this commit](https://github.com/envoyproxy/envoy/commit/ba474ac375418d5529a30a9510a8ff5f0a5ada9a) that for one changes the default for Envoy to use the `SO_REUSPORT` socket option but also changes how listener updates work. Granted this is not the most exact/minimal test case but it appears this commit might be related.

*Repro steps*:
I can try to work up a smaller repro but for now, running the Contour `e2e` tests has been how we have experimented, capturing logs and fiddling with timeouts etc.:
- Clone https://github.com/projectcontour/contour
- Ensure Docker, `kind`, `go`, and `ginkgo` are installed
- Run `make e2e`
- Note run time of test suites
- Update Envoy image to v1.20.0 [here](https://github.com/projectcontour/contour/blob/d8bdd94dd317ff0d5766af1f41098dd20cc328fc/examples/render/contour.yaml#L5132)
- Re-run `make e2e`
- Note increased run time of test suites/failures

*Theories/mitigations*
- We are using the default Go HTTP client in tests and logging request errors in our test suite we see TLS handshake timeout errors for HTTPS requests/plain HTTP requests hang forever (Go default client has no request timeout, oops on our part using that!)
- It appears the updated listener update/worker logic holds open connections that never succeed, maybe as part of what is described in the linked change in the effort to not drop connections on draining listeners
- In the Contour tests, we can mitigate slowdowns by adding more strict timeouts to HTTP requests, though we still see listener updates as much slower anecdotally

**Comment by howardjohn** [comment]
We are seeing the same in Istio. Essentially it looks like when a listener drains, some (maybe 50%, but I didn't get a large sample size to say exactly 50/50) hang. netstat shows them stuck in Recv-Q.

Suspecting the reuseport stuff, we disabled it via runtime flag. When we did this, we got a different error - NACKs from address already in use.

cc @mattklein123 @lambdai

**Comment by sunjayBhatia** [comment]
> Suspecting the reuseport stuff, we disabled it via runtime flag. When we did this, we got a different error - NACKs from address already in use.

Same for Contour

**Comment by mattklein123** [comment]
> The underlying expectation is that kernel should requeue the socket of the dying passive socket(old listener) to another passive socket(new listener). What's importantly, the libevent should somehow be notified and wake 1+ worker thread.

Unfortunately this is not the way it works. Sockets are not re-queued. A lot of care was put into make sure that we don't wind up with dead socks that are never accepted, and I'm surprised to hear this is happening. I'm happy to look into this if we can come up with a more self contained repro?

**Comment by sunjayBhatia** [comment]
> a more self contained repro

working on something smaller, was able to get a little spike to do what is happening with Contour, but now its not reproducible  😅

**Comment by mattklein123** [comment]
> I transfer the ownership of listen socket factory to the in place updated new listener, all looks good until I hit the case updating an updating listener. Still fixing...

OK lmk if you need help fixing. Just ping me on Slack.
