### ISSUE TITLE
Support additional output format in stats admin interface

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#1862]
Currently `admin/stats` spits out statistics in an unstructured way. This makes it difficult to process them programmatically. Can we support some thing like `admin/stats?format=json` which outputs the same stats in json which will enable easy programmatic access.

**Comment by ramaraochavali** [comment]
@mattklein123  Implemented this [PR](https://github.com/envoyproxy/envoy/pull/1865). Please review and let me know your comments

**Comment by mattklein123** [comment]
Fixed
