### ISSUE TITLE
Share remote JWKS cache across filter chains

### ISSUE THREAD

**Issue by Joon-L** [envoyproxy/envoy#18636]
*Title*: *Share JWKS cache across filter chains*

*Description*:
>We have multiple (could be thousands or more) of filter chains from a single listener where each chain will have its remote JWKS configurations. Most of the filter chains share the same remote JWKS provider with the identical URI and cluster.
However, JWKS caches are created per filter chain so each chain separately calls the JWKS endpoint on its own. This causes issues when trying to use the jwks [async_fetch feature](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-remotejwks) added in v.1.19 as the main thread will storm the JWKS endpoint with thousands of requests at once on startup.

Would there be a way to share the JWKS cache across filter chains similar to the way we share across threads?

One *hacky* alternative is to have cache_duration supported in local_jwks and have a different process outside of Envoy update the file (this still has the same issue of each chain reading from the same file but will at least reduce the number of remote calls made to the actual JWKS endpoint).

**Comment by qiwzhang** [comment]
Sorry,  I missed this issue.  Let me see, coding wise, if it is easy to create Jwks cache to be shared globally.  Currently,  it is per worker thread.
