### ISSUE TITLE
How do I clone traffic (shadow proxy) while still able to keep the XFF and remote client ip?

### ISSUE THREAD

**Issue by unisqu** [envoyproxy/envoy#1863]
How do I clone traffic (shadow proxy) while still able to keep the XFF and remote client ip?

Currently I'm running envoy inside a docker container (172.17.0.1) but the forwarded traffic to varnish etc always show originating IP from 172.17.0.1 instead from the end user client ip. Please help. Thanks

**Comment by mattklein123** [comment]
The shadow feature does not alter XFF. It uses whatever has already been defined by the connection manager settings.

**Comment by mattklein123** [comment]
Closing as answered.
