### ISSUE TITLE
what's the difference between cache filter and buffer filter？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18653]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
what's the difference between cache filter and buffer filter？
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by davinci26** [comment]
Cache filter is used to perform http caching, see [Cache filter](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache.html?highlight=cache) and Buffer filter is used to to stop filter iteration and wait for a fully buffered complete request.
