### ISSUE TITLE
Support query tracing in the Postgres filter

### ISSUE THREAD

**Issue by ahachete** [envoyproxy/envoy#18657]
*Support query tracing in the Postgres filter*: *RFC: record all or a % of the queries that traverses the Postgres filter and send them as traces to an external collector*

*Description*:
This is a RFC / feature request, if it is feasible.

There are many potential very interesting uses for capturing the queries that are sent to a database like Postgres. They may be used for performance analysis (including throughput and latency); audit and security analysis; load replay; and potentially many others. The main goal of this issue is to enhance the functionality of the existing Postgres filter to capture those queries and send them to an external system for processing.

It is a goal to not impact (measurably) the performance on the Postgres filter due to this process. For this reason, minimal to no processing of the queries should happen. In particular, query parsing should not be performed. Query fingerprinting should also not be performed.

Essentially, this would be similar to logging al the queries, and send the logs via an external logging mechanism; except that it is proposed to send them as traces, including the duration of the query. 

It may work as follows: for every Postgres wire protocol message that contains a query (either simple protocol; or extended protocol, including subsequent bind message(s) to also capture the values of the parameters) a trace would be generated. The trace would contain a single span, including among other usual trace/span fields:
* The query text
* The parameters and the values, if it is an extended protocol query
* The timestamp when the query was received at Envoy
* The duration of the query, as observed by Envoy (when the first reply packet from the query is sent downstream)

These traces may be then sent externally to a collector. Ideally, this could be done over the [Open Telemetry Protocol](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md) in gRPC format. But given that there's no OTLP protocol support in Envoy (yet: related issues #13801 and #9958); and that there's definitely zipkin support in Envoy; it is proposed to send the traces via zipkin (which is a supported receiver in OpenTelemetry collector contrib), reusing as much code as possible.

There should be options to limit the number of queries logged. However, it should be designed to support high volumes of query logging, as that's required for some of the use cases (in particular, workload replaying). A initial few options (which could potentially be combined) could be:
* A percentage, used for sampling.
* Only trace queries whose duration is above a given threshold.
* Only trace queries if their response is an error.

It is a non-goal to support context propagation --which would be hard, the Postgres protocol doesn't provision anything for this, and applications that support it use non-standardized mechanisms based on SQL comments embedded into the queries.

**Comment by cpakulski** [comment]
I was thinking about extending access logging, which sends logs to various sinks: a file or grpc server. File sink obviously accepts just lines, but grpc uses more structured approach and can represent database specific structure, like DB name, query, result, etc.
That would however not cover zipkin format.
