### ISSUE TITLE
v2 doc tooling

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1866]
@htuch opening ticket here so we can track what we need. IMO the minimum tooling is:
1) Build RST tree for v2 docs.
2) Merge auto generated tree into static tree
3) Build docs as a single block

^ will allow cross linking between auto generated docs and arch docs and vice versa. The tooling would optimally allow auto generation of the type of JSON/YAML overviews we have now, followed by some basic boiler plate param descriptions, which we could then customize via special comments inside the protos.

**Comment by mattklein123** [comment]
Reminder, replace https://github.com/envoyproxy/envoy/pull/1857/files#diff-cc3bfd0cbce08a759df63ad8e2f01b5fR147 with real docs cross linking when tools are ready. cc @zuercher

**Comment by htuch** [comment]
Work started in https://github.com/envoyproxy/data-plane-api/pull/205.

**Comment by mattklein123** [comment]
@junr03 can you please help @htuch with the conversion of examples from v1 to v2 in the repo. It's similar to the work we have to do at Lyft internally anyway.

**Comment by junr03** [comment]
👌

**Comment by mattklein123** [comment]
Calling this done. We can do example/config conversions in 1.6.0. Will open a different ticket on that.
