### ISSUE TITLE
I can't understand how to use google_grpc config

### ISSUE THREAD

**Issue by gibmir** [envoyproxy/envoy#18663]
*Title*: *I can't understand how to use google_grpc config*

*Description*:
> I can't find any example of GrpcService *config* field 
```json
{
  "target_uri": "...",
  "channel_credentials": "{...}",
  "call_credentials": [],
  "stat_prefix": "...",
  "credentials_factory_name": "...",
  "config": "{...}",
  "per_stream_buffer_limit_bytes": "{...}",
  "channel_args": "{...}"
}
```
In documentation i found only this: "(Struct) Additional configuration for site-specific customizations of the Google gRPC library."
but i need to know what i can put in this structure(maybe you have some examples of google_grpc configuration).

[optional *Relevant Links*:]
>  [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-field-config-core-v3-grpcservice-google-grpc)

**Comment by gibmir** [comment]
Great thanks! I think  you resolve my main problem.  
If i need to configure grpc channel i should use something like this?
```json
config.core.v3.GrpcService.GoogleGrpc
{
  "channel_args":  
      {
          "string_value": "grpc.server_handshake_timeout_ms"
          "int_value":  1000
      },
     {
          "string_value": "grpc.max_reconnect_backoff_ms"
          "int_value":  1000
     }
}
```

**Comment by chaoqin-li1123** [comment]
Hi, you can put the config inside the args field of channel_args, which is of map type.
google_grpc:
  channel_args:
    args:
      grpc.http2.max_pings_without_data: { int_value: 3 }
      grpc.default_authority: { string_value: foo }
      grpc.http2.max_ping_strikes: { int_value: 5 }
      grpc.ssl_target_name_override: { string_value: bar }

**Comment by gibmir** [comment]
@chaoqin-li1123 @davinci26 Great thanks 🙂
