### ISSUE TITLE
JWT Auth filter store auth result in dynamic metadata

### ISSUE THREAD

**Issue by zhiyong-gayang** [envoyproxy/envoy#18661]
In our filter chains we have two auth filters, one is the JWT auth filter, another is customized Key auth filter, the scenario we want to support is if JWT OR Key auth pass, then the auth should pass, but if we add the two filters in filter chain, their relationship is AND, not OR.
The solution is in JWT auth filter, no matter the auth fail or success, let this filter continue and add dynamic metadata to store the auth result (fail or success), then in Key auth filter, read the JWT auth result from dynamic metadata and plus the key auth result to decide whether continue or stop.
I want to ask is there other options can support this scenario? or can we add this feature in JWT auth filter to support it?

**Comment by qiwzhang** [comment]
Could you take a this this [allow_missing_or_failed](https://github.com/envoyproxy/envoy/blob/d60f86c6b54e4ba376f67474d4e5a11f2c8d4dfb/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L478)?

If it is true,  jwt_authn file will not reject any request,  Your Key-Auth filter can use its result in the metadata or headers

**Comment by garyyang2002** [comment]
Thanks @qiannawang, for the metadata part, I guess we need to add the result by ourselves, is there any feature support it? or we need to change the JWT filter to add it.

**Comment by qiwzhang** [comment]
for now,  jwt_authn  doens't add verification status, (failed, or passed) to the metadata.   It only adds payLoad to metadata if verification is success.   You could derive the data from there.

Or you can change the jwt_authn to add the verification status to the metadata.

**Comment by garyyang2002** [comment]
Thanks, @qiwzhang.
