### ISSUE TITLE
accesslog filter what extension filter do we have？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18671]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
extension_filter
(config.accesslog.v3.ExtensionFilter) Extension filter.

Precisely one of status_code_filter, duration_filter, not_health_check_filter, traceable_filter, runtime_filter, and_filter, or_filter, header_filter, response_flag_filter, grpc_status_filter, extension_filter, metadata_filter must be set
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by htuch** [comment]
Please see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging
