### ISSUE TITLE
Decide on policy for histogram SI unit suffix

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#18693]
There is a linting rule that requires histograms to not have SI unit suffixes (such as `_ms` for milliseconds): https://github.com/envoyproxy/envoy/blob/1d601f273ac0ec9f8030788d94370ad40261f693/tools/code_format/check_format.py#L823

This was added in #8484 with the intent that stats sinks would properly format the units of the histogram to the format appropriate for that stats system.

However, none of the Envoy built-in sinks have support for these semantics, and most histograms are in the ignore-list for the rule (because they were created before the linting rule was added).

Additionally, non-histogram metrics are supposed to have SI units where appropriate, so this creates inconsistency. 

Should the rule be kept, and built-in sinks updated to use it, or should the rule be removed, and allow a sink to remove the suffix if needed (by trimming the last 3 characters of the name, for example)?

**Comment by htuch** [comment]
@jmarantz
