### ISSUE TITLE
Upstream Active Connection metric increase after v1.20.0 upgrade

### ISSUE THREAD

**Issue by khushbr** [envoyproxy/envoy#18700]
*Title*: *Upstream Active Connection metric increase after upgrade*

*Description*:
>We upgraded Envoy from v1.17 to v1.20 for our system. We use Envoy in 2 manner: 1/ As regular Envoy Proxy(the ingress fleet) 2/ As a reverse service proxy for services that talks to the Envoy in #1. After the upgrade to v1.20, we are seeing an increase in `upstream_cx_active` metric but the `upstream_cx_total` metric looks as expected(refer the snapshot). 
On further debugging, we noticed recurring spike in `upstream_cx_destroy` and `upstream_cx_destroy_local` metrics but nothing in `envoy_cluster_upstream_rq_timeout` or `envoy_cluster_upstream_cx_idle_timeout`

(Follow the red line go up after 10/20)
<img width="1260" alt="Screen Shot 2021-10-20 at 6 25 15 PM" src="https://user-images.githubusercontent.com/59671881/138201109-3a434cbe-dcf7-4ce3-8bee-071c71192482.png">

I am trying to make sense of why the active upstream connection count has gone up after the upgrade ? 
1/ We did not change any other config around connection pool and timeout.  
2/ I checked the Connection Manager code changes since v1.17 and couldn't find a relevant change.
3/ I have gone through the release notes, looking for any breaking change, minor behavior change for 1.17, 1.18 and 1.20, and did not find anything specific to this.

Happy to add more logs/metrics.

**Comment by mattklein123** [comment]
I think this is due to REUSE_PORT now being the default. I could see this leading to more active connections with more concurrent workers receiving even connections.

**Comment by khushbr** [comment]
Understood. I was confused because the `/config_dump` API did not return the `lb_policy`. 
Is there another way to verify the Load Balancing in-use? 
```
curl localhost:8081/config_dump | grep -w -A10 clusters
     "clusters": [
      {
       "name": "envoy-to-remote",
       "type": "STRICT_DNS",
       "connect_timeout": "0.200s",
       "health_checks": [
```
