### ISSUE TITLE
Bazel 5.x support

### ISSUE THREAD

**Issue by keith** [envoyproxy/envoy#18718]
I'm filing this as a tracking issue around bazel 5.x, which should be RC next week https://github.com/bazelbuild/bazel/issues/14013

I've started lightly testing this to see how much work it will be to update. I will update this issue with the issues we find:

- [ ] I discovered https://github.com/bazelbuild/bazel/issues/14152, which we have some ways to workaround given the limited use case of `genrule_repository` today
- [ ] It seems the java flags we pass are now outdated, there are some new warnings about the ones we pass being deprecated, and for me builds would fail immediately until I started passing `--java_runtime_version=remotejdk_11`
- [ ] Update build tools image

**Comment by keith** [comment]
It seems the java flags we pass are now outdated, there are some new warnings about the ones we pass being deprecated, and for me builds would fail immediately until I started passing `--java_runtime_version=remotejdk_11`

**Comment by htuch** [comment]
CC @phlax

**Comment by keith** [comment]
Landed in https://github.com/envoyproxy/envoy/pull/19706#event-5983133239
