### ISSUE TITLE
Http to grpc transcoding: is there a way to return a 423 response status code?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#18712]
Hi,

I'm using envoy to handle do the http to grpc transcoding, and I have an endpoint, where on http side I would like to return the status code 423 Locked under some circumstances.
Currently com.google.rpc.Code doesn't offer support for this particular status code, but I was wondering if there is any trick I can apply on envoy side to generate this code under given circumstances? Maybe by passing some specific headers/metadata or something on that line, so that I can control it from the code...

Thanks

**Comment by htuch** [comment]
@qiwzhang @lizan
