### ISSUE TITLE
upstream HTTP/3 0-RTT should work, and be restricted to safe methods

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#18715]
[Section 4 of RFC 8470](https://datatracker.ietf.org/doc/html/rfc8470#section-4) says:

> Absent other information, clients MAY send requests with safe HTTP methods ([RFC7231], Section 4.2.1) in early data when it is available and MUST NOT send unsafe methods (or methods whose safety is not known) in early data.

In Envoy we should make sure that we only send 0-RTT for [safe methods](https://datatracker.ietf.org/doc/html/rfc7231#section-4.2.1): GET, HEAD, OPTIONS, and TRACE.

**Comment by RyanTheOptimist** [comment]
@danzh2010 I think you're working on this in #19388. Is that right?

**Comment by danzh2010** [comment]
Right, and we probably need an issue to track upstream 0-RRT support along aside this one.

**Comment by RyanTheOptimist** [comment]
I think this issue talks about both 0-RTT needing to working in general, and about be specific to safe methods. What would the other issue be tracking?

**Comment by ggreenway** [comment]
Sorry, I'm late to the party on this. 

I think this MUST be configurable, and possibly should be disabled by default. Lots of http APIs mis-use verbs; there should be a way to make it safe in those situations.

**Comment by RyanTheOptimist** [comment]
Can you clarify what you'd like disabled by default? Upstream HTTP/3 0-RTT completely?  Upstream HTTP/3 0-RTT being restricted to only "safe" methods? Or maybe said differently, what config options would you like to see for this?

**Comment by ggreenway** [comment]
I think the config option should probably be a list of allowable 0-rtt http verbs. 

I'm unsure what the default should be. Maybe it should be an empty set, maybe it should be GET, HEAD, OPTIONS, and TRACE.

I honestly don't feel too strongly about the default, as long as their's an escape hatch to turn it off if it is problematic for a specific installation. There's a tradeoff between performant-by-default vs safer-by-default.

**Comment by danzh2010** [comment]
> I think the config option should probably be a list of allowable 0-rtt http verbs.
> 
> I'm unsure what the default should be. Maybe it should be an empty set, maybe it should be GET, HEAD, OPTIONS, and TRACE.
> 
> I honestly don't feel too strongly about the default, as long as their's an escape hatch to turn it off if it is problematic for a specific installation. There's a tradeoff between performant-by-default vs safer-by-default.

Making 0-RTT configurable is also discussed in https://github.com/envoyproxy/envoy/issues/19542, though it wasn't a priority in earlier discussion.  If we want users be able to opt out all HTTP/3 0-RTT requests now or some HTTP methods later, how about adding an enum config knob in router filter to have options: `NotAllowed` and `AllowedForSafeMethods` for now? One can always extends the option if needed later.

**Comment by ggreenway** [comment]
That sounds reasonable to me.
