### ISSUE TITLE
Segmentation Fault on Monterey

### ISSUE THREAD

**Issue by lacasaprivata2** [envoyproxy/envoy#18820]
Sudden segmentation fault on Monterey (MacOS) when running Envoy 1.20 proxy

On the commands

envoy
envoy -c envoy.yaml
envoy --help
....

*Description*:
 line 5: 93025 Segmentation fault: 11

Is there a FAQ for resolving this?

**Comment by juliaogris** [comment]
A new release would be fabulous!

**Comment by codefromthecrypt** [comment]
1.20.1 (available in homebrew) sorts this out
