### ISSUE TITLE
Weighted cluster in LDS vs cluster load balancing weight in CDS

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#18837]
Hi!
I noticed that users at least can have two options to route the traffic to different destinations using weights. 
[weighted cluster](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/traffic_splitting#traffic-splitting-across-multiple-upstreams) in LDS and [load_balancing_weight](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-lbendpoint) in CDS (between locality and within locality). Apparently, they are at different places in the data flow, and the one in CDS is locality-aware. 
Are there any other differences that could affect users' choice over weighted_cluster or load_balancing_weight?

Thanks!

**Comment by lambdai** [comment]
weight cluster impact the decision of a cluster. I don't think this step will inspect the weights of the endpoints within that cluster, nor the locality.
*once the cluster is chosen*, the load_balancing_weight impacts you choose the upstream endpoint.

**Comment by lambdai** [comment]
My impression is that retry never reconsider other cluster, otherwise lots of things could break although I don't have the full picture.
but retry can reconsider another endpoint
