### ISSUE TITLE
what the difference between sni_dynamic_forward_proxy and dynamic_forward_proxy ，I know dynamic_forward_proxy how to config，but sni_dynamic_forward_proxy  I don't know how to config？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18834]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
what the difference between sni_dynamic_forward_proxy and dynamic_forward_proxy ，I know dynamic_forward_proxy how to config，but sni_dynamic_forward_proxy  I don't know how to config？
*Description*:
>Describe the issue.
what the difference between sni_dynamic_forward_proxy and dynamic_forward_proxy ，I know dynamic_forward_proxy how to config，but sni_dynamic_forward_proxy  I don't know how to config？
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by asraa** [comment]
Please check this documentation https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter
for examples of the config. Feel free to open another issue with a more specific question
