### ISSUE TITLE
Pass through HTTP status 102 processing

### ISSUE THREAD

**Issue by aksdb** [envoyproxy/envoy#18844]
*Title*: Envoy should pass through all 102 processing status from upstream services.

*Description*:
Upstream services might send a 102 processing as a form of keep-alive. Envoy should simply pass them on without interfering.

(Optional: also pass through other unknown 1xx status)

*Relevant Links*:
* WebDAV: https://datatracker.ietf.org/doc/html/rfc2518#section-10.1
* HTTP 1.1: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
  > A client MUST be prepared to accept one or more 1xx status responses prior to a regular response [...]
  > Proxies MUST forward 1xx responses, unless the connection between the proxy and its client has been closed, or unless the proxy itself requested the generation of the 1xx response.

**Comment by mattklein123** [comment]
cc @alyssawilk for thoughts on this.

**Comment by aksdb** [comment]
Btw I edited the description. I just realized I mixed up "downstream" and "upstream" :-/

**Comment by alyssawilk** [comment]
yeah I think arguably we should rename the encode100ContinueHeaders functions to encode1xxHeaders and allow any no-op 100s
Matt, if you agree that's reasonable I can add it to my queue

**Comment by mattklein123** [comment]
> Matt, if you agree that's reasonable I can add it to my queue

Sure makes sense to me.

**Comment by aksdb** [comment]
@alyssawilk First of all: thank you so much for implementing this (so fast!).

I tried with the recent master, but was not quite able to figure out if I am doing it wrong, or if it doesn't work (yet?) as it should.

If I open a connection **directly** to my (test) service, it sends a 102 every 2 seconds. So an example request looks like this:
```
> curl -vvv 'http://127.0.0.1:3000/test?wait=10s'
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /test?wait=10s HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Processing
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Processing
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Processing
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Processing
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Processing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 18 Nov 2021 08:07:18 GMT
< Content-Length: 18
< 
* Connection #0 to host 127.0.0.1 left intact
Returned after 10s⏎
```

When I do the same **with envoy** (commit 1eb1841f) in between, it now looks like this:
```
> curl -vvv 'http://127.0.0.1:8080/test?wait=20s'
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /test?wait=20s HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 102 Unknown
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 Gateway Timeout
< content-length: 24
< content-type: text/plain
< date: Thu, 18 Nov 2021 08:08:45 GMT
< server: envoy
< 
* Connection #0 to host 127.0.0.1 left intact
upstream request timeout⏎
```

It seems to only forward the first 102, and apparently it turns "Processing" into "Unknown" (or strips it right away; might be curl that turns it into "Unknown"). The remaining 102s seem to be swallowed, so the request now also runs into a timeout.

Am I missing something or is this so far expected behavior?

Maybe I am using the feature flag wrong?
I have this in my config:
```yaml
layered_runtime:
  layers:
    - name: static_layer
      static_layer:
        envoy.reloadable_features.proxy_102: true
```

**Comment by alyssawilk** [comment]
ah yeah, if you check the release notes, as with 100s and 103s, Envoy only handles the first, sorry that wasn't clear to you

Handling multiple 1xxs is significantly more complicated.  Simply passing them through in the happy path isn't so bad, but when things are backed up, we only have one "slot" in the HTTP processing machine to buffer 1xxs,and handling more than one gets hella complicated and I think would take more time than I can afford to tackle this quarter.  

Filed https://github.com/envoyproxy/envoy/issues/19044 for posterity

**Comment by aksdb** [comment]
Thanks for clarification. I probably have a pretty naive view on this and hoped that upstream responses can simply be passed  through. But given the many protocol conversions envoy supports, this likely is not possible without some state machine around it.

Again many thanks for tackling this (so soon) and also thanks for even considering looking into it some time later for an even broader solution! :smiley:
