### ISSUE TITLE
support proto file level 'not-implemented-hide' tag

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#18841]
*Title*: *support proto file level 'not-implemented-hide' tag*

*Description*:

The community supports adding a #not-implemented-hide tag to proto messages/fields to hide these unimplemented APIs when generating docs, but currently this tag does not work at the file level.

**Comment by asraa** [comment]
@phlax what do you think? maybe this points to https://github.com/envoyproxy/envoy/blob/e3a3689ed318a9e28dcacb878163e948d9b6c376/tools/protodoc/protodoc.py#L749? seems like a reasonable thing to hide for whole unimplemented files

**Comment by phlax** [comment]
seems reasonable to me - probably a question for @htuch 

shouldnt be too difficult to implement i think

**Comment by htuch** [comment]
It seems reasonable, but I'm also curious why the file-level WiP doesn't work here?

**Comment by wbpcode** [comment]
I am not sure, but the meanings of 'WiP' and 'not-implemented-hide' are slightly different. 'WiP' is just unstable, but 'not-implemented-hide' is not implemented at all.

**Comment by htuch** [comment]
Fair. I think this is reasonable to add in protodoc.

**Comment by wbpcode** [comment]
This should be closed by the #18923.
