### ISSUE TITLE
Run On-Proxy

### ISSUE THREAD

**Issue by vitruvvius** [envoyproxy/envoy#18867]
I desire to run our applications on-proxy - meaning, like how blockchain apps get run "on-chain", I'd like to integrate our game engine directly onto envoy itself and use the envoy APIs to send/recv.

Why? The feature set and performance of envoy is amazing. Along with the statistics. We can see gRPC attempting to replicate envoy, and do just this, with their new, native xDS implementation.

In particular, we have a rust app. It does two things very well - real time streaming over web-sockets and real time streaming over http2. 

Since we're using rust, this means we can receive calls into our rust app from C/C++ through a binding with no overhead. This means that we can technically call and receive data from the envoy apis directly.

So, the process for accomplishing this should be quite simple. Rather than pointing downstream to a remote server, one points to a local process and shares memory instead of an additional hop on the network. Or, one simply injects the application code in a filter to receive http1.1/http2/websocket requests and accept/respond accordingly.

My question, therefore, is where would one modify envoy or attach such that this could be possible?

**Comment by mattklein123** [comment]
> My question, therefore, is where would one modify envoy or attach such that this could be possible?

I think you could probably pretty easily embed your application code in a terminal filter, and then use AsyncClient, etc. to make additional network calls if you want. The application code even be global and instantiated once, and then the filter would just receive requests.

**Comment by vitruvvius** [comment]
Will the TerminalFilter, though, operate with websockets + asynchronous workers?

As in, say that I receive a request and require to do 1second of async i/o work (fetch a database, cache, third party library http call, etc)

Does the filter expect synchronous, immediate behavior?
