### ISSUE TITLE
Is there any tool available to convert a v2 envoy.yaml into a v3 one?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#18866]
Hi,

I'm trying to upgrade my envoy instance from 1.16 to 1.18, and doing this I've realized that v2 config was deprecated and I should move to v3. 

All good with this, but is there a tool or something that will allow me to do this migration quicker ? I don't feel like going over all the V3 docs to convert it. Plus the logs envoy is providing when trying to start it using a v2 conf file, are not very clear, usually dumping huge sections of the config content saying that something is off with that, or a field out of that section is unknown

Thanks 

The error I'm getting is :

`The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition. (Unknown field in: {"admin":{"access_log_path":"/tmp/admin_access.log","address":{"socket_address":{"address":"0.0.0.0","port_value":9901}}},"static_resources":{"clusters":[{"connect_timeout":"150s","hosts":[{"socket_address":{"port_value":9090,"address":"m-api"}}],"dns_lookup_family":"V4_ONLY","name":"grpc-backend-services","type":"STRICT_DNS","lb_policy":"ROUND_ROBIN","typed_extension_protocol_options":{"envoy.extensions.upstreams.http.v3.HttpProtocolOptions":{"explicit_http_config":{"http2_protocol_options":{}},"@type":"type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"}}},{"name":"swagger-backend-services","hosts":[{"socket_address":{"address":"m-api","port_value":8080}}],"type":"STRICT_DNS","lb_policy":"ROUND_ROBIN","connect_timeout":"150s","dns_lookup_family":"V4_ONLY"}],"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","codec_type":"AUTO","local_reply_config":{"mappers":[{"status_code":423,"body":{"inline_string":"Project is locked"},"filter":{"grpc_status_filter":{"statuses":["RESOURCE_EXHAUSTED"]}}}]},"stat_prefix":"grpc_json","route_config":{"name":"local_route","virtual_hosts":[{"routes":[{"match":{"prefix":"/v4/api-docs"},"route":{"cluster":"swagger-backend-services","prefix_rewrite":"/v2/api-docs","timeout":{"seconds":1500}}},{"route":{"prefix_rewrite":"/","timeout":{"seconds":1500},"cluster":"swagger-backend-services"},"match":{"prefix":"/v4/swagger-ui"}},{"route":{"cluster":"grpc-backend-services","timeout":{"seconds":600}},"match":{"prefix":"/","grpc":{}}}],"name":"local_service","domains":["*"]}]},"http_filters":[{"typed_config":{"print_options":{"always_print_enums_as_ints":false,"always_print_primitive_fields":true,"preserve_proto_field_names":false,"add_whitespace":true},"@type":"type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder","proto_descriptor":"/data/m-api.pb","services":["m.api.mAPI"]},"name":"envoy.filters.http.grpc_json_transcoder"},{"name":"envoy.router"}]},"name":"envoy.filters.network.http_connection_manager"}]}],"address":{"socket_address":{"port_value":51051,"address":"0.0.0.0"}},"name":"m-api-listener"}]}})`

**Comment by ghevge** [comment]
BTW the URL mentions in the error doesn't work: https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition.

**Comment by hbrls** [comment]
> BTW the URL mentions in the error doesn't work: https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition.

The example here is workable.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter
