### ISSUE TITLE
Issue returning a get request with gRPC -> JSON bridge

### ISSUE THREAD

**Issue by EwanValentine** [envoyproxy/envoy#1887]
Hi there,

I have two microservices, both exposing a gRPC server. I have an envoy front-proxy set-up, with the following config:

```json
{
  "listeners": [
  {
    "address": "tcp://0.0.0.0:10000",
    "filters": [
    {
      "type": "both",
      "name": "http_connection_manager",
      "config": {
        "codec_type": "http1",
        "access_log": [
        {
          "path": "/dev/null",
          "filter" : {
            "type": "logical_or",
            "filters": [
              {
                "type": "status_code",
                "op": ">=",
                "value": 500
              },
              {
                "type": "duration",
                "op": ">=",
                "value": 1000000
              }
            ]
          }
        },
        {
          "path": "/dev/null"
        }],
        "stat_prefix": "router",
        "route_config": {
          "virtual_hosts": [
            {
              "name": "integration",
              "domains": [ "*" ],
              "routes": [
                {
                  "prefix": "",
                  "cluster": "service"
                },
                {
                  "prefix": "",
                  "cluster": "hello-service"
                }
              ]
            }
          ]
        },

        "filters": [
          {
            "type": "both",
            "name": "grpc_json_transcoder",
            "config": {
              "proto_descriptor": "/etc/hello-service.pb",
              "services": ["models.HelloService"]
            }
          },
          {
            "type": "both",
            "name": "grpc_json_transcoder",
            "config": {
              "proto_descriptor": "/etc/service.pb",
              "services": ["models.AuthService"]
            }
          },
          { "type": "decoder", "name": "router", "config": {} }
        ]
      }
    }]
  }],

  "admin": { "access_log_path": "/dev/null", "address": "tcp://0.0.0.0:9000" },
  "statsd_udp_ip_address": "0.0.0.0:8125",

  "cluster_manager": {
    "clusters": [
      {
        "name": "hello-service",
        "features": "http2",
        "connect_timeout_ms": 5000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://hello_1:50052"
          }
        ]
      },
      {
        "name": "service",
        "features": "http2",
        "connect_timeout_ms": 5000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://service_1:50051"
          }
        ]
      }
    ]
  }
}
```

The first service exposes two methods, one GET, one POST. Both of those work. Then I have an almost identical second service, exposing two methods, both GET. 

The first service works as expected, however the second service returns a 200, but nothing for the body. I suspected it was my code as one service works, but the other doesn't. But I created a gRPC client, and that works as expected with the service that's not returning anything via Envoy. So I wondered if it was my config.

Here's my repo: https://github.com/EwanValentine/envoytest

**Comment by lizan** [comment]
The route config doesn't looks correct, it should be:

```
              "routes": [
                {
                  "prefix": "/models.AuthService/",
                  "cluster": "service"
                },
                {
                  "prefix": "/models.HelloService/",
                  "cluster": "hello-service"
                }
              ]
```

route calculation happens after transcoder, so the gRPC native path in route config is fine.

I don't remember what is the behavior if two route have same prefix. Is the first one always picked @mattklein123 ?

Also, you can consolidate two transcoder filter into one, by generating a single proto descriptor contains both from multiple proto source and specify both services in `services`. That shouldn't be the real reason this didn't work but it could also be.

**Comment by EwanValentine** [comment]
> Also, you can consolidate two transcoder filter into one, by generating a single proto descriptor contains both from multiple proto source and specify both services in services. That shouldn't be the real reason this didn't work but it could also be.

Possibly, just wondering how to do that from a practical standpoint. If you have say several microservices, each with their own protobuf definition. Do you have any suggestion on how I could merge those into one?

**Comment by lizan** [comment]
> Possibly, just wondering how to do that from a practical standpoint. If you have say several microservices, each with their own protobuf definition. Do you have any suggestion on how I could merge those into one?

You can feed multiple proto source to one `protoc` call. You can also try cat the descriptor binaries into one file, since the `FileDescriptorSet` just has one repeated field, I didn't try this but it might just work.

Though I don't think having two filters is the real problem in your case, if it turns out to be the root cause, just file me a bug then I can fix it.

**Comment by EwanValentine** [comment]
@lizan I added those route prefixes, however the second service still hung, no response at all this time? 

So I tried to merge all the protobuf files together, but because I'm importing google.api.annotations, it ends up importing this twice, thus causes a multiple import error :(

**Comment by mattklein123** [comment]
> I don't remember what is the behavior if two route have same prefix. Is the first one always picked @mattklein123 ?

Yes, matching is FIFO. @EwanValentine can you provide a log with "-l 1" (debug) level logging?

**Comment by lizan** [comment]
@EwanValentine 
> But I created a gRPC client, and that works as expected with the service that's not returning anything via Envoy.

Is this going through Envoy or directly to the service? With the previous route it shouldn't be through Envoy.

Providing log with debug would be very helpful, thanks.

**Comment by EwanValentine** [comment]
I added "-l 1" to my Dockerfile, like: 
`CMD /usr/local/bin/envoy -l 1 -c /etc/envoy.json --service-cluster front-proxy` 

And I'm getting... 

```

proxy_1    | [2017-10-18 23:44:20.651][6][warning][main] source/server/server.cc:164] initializing epoch 0 (hot restart version=8.2490552)
proxy_1    | [2017-10-18 23:44:20.667][6][warning][main] source/server/server.cc:332] starting main dispatch loop
proxy_1    | [2017-10-18 23:44:20.667][6][warning][main] source/server/server.cc:316] all clusters initialized. initializing init manager
proxy_1    | [2017-10-18 23:44:20.667][6][warning][config] source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
```

Nothing outputted on request

**Comment by mattklein123** [comment]
What version of envoy are you running? Please make sure you are using current master if using docker images where trace/debug messages are compiled in by default. There should be tons of messages at -l 1.

**Comment by EwanValentine** [comment]
```
FROM lyft/envoy:latest
RUN apt-get update && apt-get -q install -y curl dnsutils
RUN touch /var/log/envoy.log
CMD /usr/local/bin/envoy -l 1 -c /etc/envoy.json --service-cluster front-proxy
``` 

That's my Dockerfile.

Here's all my output when I run the service and make a couple of requests... 

```
service_1  | 2017/10/19 07:43:44 Listening on port: :50051
hello      | 2017/10/19 07:43:45 &{}
hello      | 2017/10/19 07:43:45 running on port: :50052
proxy_1    | [2017-10-19 07:43:45.690][7][warning][main] source/server/server.cc:164] initializing epoch 0 (hot restart version=8.2490552)
proxy_1    | [2017-10-19 07:43:45.712][7][warning][main] source/server/server.cc:332] starting main dispatch loop
proxy_1    | [2017-10-19 07:43:45.712][7][warning][main] source/server/server.cc:316] all clusters initialized. initializing init manager
proxy_1    | [2017-10-19 07:43:45.712][7][warning][config] source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
service_1  | 2017/10/19 07:44:01 1
proxy_1    | [2017-10-19T07:44:01.034Z] "POST /api/v1/users/1 HTTP/1.1" 200 - 0 34 2 0 "-" "PostmanRuntime/6.4.1" "cdf144d8-ec2b-4592-91a0-d08641091e12" "localhost:8080" "172.20.0.2:50051"

proxy_1    | [2017-10-19T07:44:05.257Z] "POST /api/v1/hello/ewan HTTP/1.1" 0 UH 0 0 32236 - "-" "PostmanRuntime/6.4.1" "f77fb3ab-23ed-468d-b3be-8c9e0839b643" "localhost:8080" "-"

```

As you can see they are both POST requests, but in Postman I'm making a GET request, and in my protobuf, I'm doing... 

```
rpc Hello(HelloRequest) returns (HelloResponse) {
    option (google.api.http) = {
      get: "/api/v1/hello/{name}"
    };
  }
``` 

The first service works, the second just hangs indefinitely.

**Comment by EwanValentine** [comment]
So I fixed it, I changed my hostnames from `service_1` and `hello_1` to `service` and `hello` and ensured both docker containers had `container_name` set respectively in docker-compose. So I suspect it was a Docker/dns 'thing'. The fact they all seem to be POST requests was a red herring. 

Thanks for your time and help on this! Seems it was something my end after all 😅
