### ISSUE TITLE
Allow access to get/setRequestHeaders within the callback of an httpCall in an onRequestHeaders implementation.

### ISSUE THREAD

**Issue by owenammann** [envoyproxy/envoy#18875]
I am trying to write an Envoy WASM filter using the C++ SDK. 
My goal is:
- Envoy receives an HTTP request to my upstream service.
- The Envoy WASM HTTP filter makes a call to one of my upstream clusters (not my service).
- The upstream response will return data with which I will decorate the original http request
- I am able to change the headers (actually path) of the original request based on the response of my upstream cluster

The problem is, once I make my HTTP call with httpCall, I only have access to the response data in my callback. There is no option at all to edit the original request, which is counterintuitive. In my opinion, it will not be a problem to extend the scope of getting HTTP headers into the callbacks of an httpCall.

I won't paste my exact code, as it is sensitive, but I will paste an example of exactly what I am trying to do. Is there any workaround for this? As of now, this use case does not seem possible without some fairly involved event gymnastics at best. I believe there is a similar respective use case with httpCall() inside onRequestBody()

I appreciate any help or insight with this! Thanks!
```
// NOLINT(namespace-envoy)
#include <string>
#include <unordered_map>

#include "proxy_wasm_intrinsics.h"

class ExampleContext : public Context {
public:
  explicit ExampleContext(uint32_t id, RootContext* root) : Context(id, root) {}

  FilterHeadersStatus onRequestHeaders(uint32_t) override;
};
static RegisterContextFactory register_ExampleContext(CONTEXT_FACTORY(ExampleContext));

FilterHeadersStatus ExampleContext::onRequestHeaders(uint32_t) {
  auto context_id = id();
  auto callback = [context_id](uint32_t, size_t body_size, uint32_t) {
    auto response_headers = getHeaderMapPairs(HeaderMapType::HttpCallResponseHeaders);
    auto body = getBufferBytes(BufferType::HttpCallResponseBody, 0, body_size);

    //Get information from the body (what I do is basically this)
    std::string value;
    myParse(body, value);

    //Get original headers (Not possible)

    auto path = getRequestHeader(":path");
    auto path_str = std::string(path->view());
    
    path_str += "&key=" + value;

    //Set request header from original request (Not possible)

   replaceRequestHeader(":path", path_str);

   continueRequest();
  };
  root()->httpCall("cluster", {{":method", "POST"}, {":path", "/"}, {":authority", "foo"}},
                   "hello world", {{"trail", "cow"}}, 1000, callback);
  return FilterHeadersStatus::StopIteration;
}
```

**Comment by mattklein123** [comment]
cc @PiotrSikora @mathetake

**Comment by PiotrSikora** [comment]
Yeah, this is the same underlying issue as in #17208. Please assign it to me, I'll get around to it shortly. Thanks!

**Comment by owenammann** [comment]
Hey @PiotrSikora thanks! I am not sure how to assign this issue to you.

**Comment by owenammann** [comment]
Hey @PiotrSikora,
Trying to understand the SDK better. Where in the code is this inline function `getHeaderMapPairs` limited to just `onRequestHeaders`? Considering the callback is evaluated after onRequestHeaders returns, it would make since that the callback cannot call this, but I am curious how this is actually implemented. Maybe a simple way to implement may be what you mentioned here re: "caching"
  https://github.com/envoyproxy/envoy-wasm/issues/445 ? would you mind please elaborating on this?
Or, what I am curious about, is if we can include all callbacks within the "scope" of their parent methods (even if after returning StopIteration). It appears that GRPC calls have this already within "GrpcCallHandler": https://github.com/envoyproxy/envoy-wasm/issues/475. As I understand it, instead of the callback being in the RootContext, the handler takes the current context as a parameter, which allows further modifications to headers and body etc.

```
inline WasmDataPtr getHeaderMapPairs(WasmHeaderMapType type) {
  const char *ptr = nullptr;
  size_t size = 0;
  proxy_get_header_map_pairs(type, &ptr, &size);
  return std::make_unique<WasmData>(ptr, size);
}
```
Thanks!
Owen

**Comment by owenammann** [comment]
Is it because getContext is of type Context and not ExampleContext?

**Comment by owenammann** [comment]
@PiotrSikora  I was actually able to achieve doing this in the callback by making an HttpCallHandler similar to grpc. going to make a pull request

**Comment by owenammann** [comment]
Nevermind, it appears I don't have this issue in the first place. I am able to access the original request in the callback. I had a code error which was causing a crash.
