### ISSUE TITLE
FR: field extractor of attempt count in the access log

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#18870]
The attempt account is located in the stream info. Both HCM and tcp_proxy maintain the value.

This is helpful to triage the slow request due to the retry.

https://github.com/envoyproxy/envoy/blob/main/envoy/stream_info/stream_info.h#L627

**Comment by cpakulski** [comment]
There are several retry algorithms/policies, so it would be nice to see which hosts/clusters were attempted.

**Comment by lambdai** [comment]
It's always good to have more but I intend to keep the topic small. 

In terms of the retried detail, when we want to dump list value, we always want to limit the number of elements and of course we need to track them first

**Comment by ggreenway** [comment]
> There are several retry algorithms/policies, so it would be nice to see which hosts/clusters were attempted.

You can configure an access log line for each upstream attempt; that will tell you everything about which cluster, which host in that cluster, why it failed, etc.
