### ISSUE TITLE
handle http/2 with no initial streams

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18880]
right now it looks like we won't increase max streams.

**Comment by YaoZengzeng** [comment]
@alyssawilk @mattklein123 maybe I'd like to fix this:)

**Comment by alyssawilk** [comment]
Feel free to take a pass at it and let me know if you need pointers.

**Comment by YaoZengzeng** [comment]
AFAK, now the **concurrent_stream_limit_** could only adjust downward and when it drops to zero, the state of client will transist to **DRAINING**. 

So what I should do is make the **concurrent_stream_limit_** configurable, not just downward. And transist the state of client to **BUSY** other than **DRAINING**, when **concurrent_stream_limit_** become zero.

Is it correct? @alyssawilk

**Comment by alyssawilk** [comment]
That sounds right!  You should be able to turn up the 0 streams integration test to make sure you have that logic right.
The other gotcha is if the Envoy is say configured to have a max concurrent streams of 100, and we start at 10 and then the client renegotiates to 150, we still want to cap it at 100, so be careful not to exceed the configured bounds :-)

**Comment by YaoZengzeng** [comment]
@alyssawilk thanks for your reminder :)

Another question, if now we have a max concurrent streams of 100 and 80 of them are active streams, then the client renegotiates to 60. So **part I**: the state of client should transist from READY to BUSY, right? On the contrary, **part II**: if now the state of client is BUSY and the max concurrent streams get increased, the state should transist to READY?

If it is right, **part I** seems have not implemented yet, I could start from it.
