### ISSUE TITLE
Can xds control plane be dynamically discovered after bootstrap?

### ISSUE THREAD

**Issue by manlinl** [envoyproxy/envoy#18891]
*Title*: *Can xds control plane be dynamically discovered after initial bootstrap?*

*Description*:
All the Envoy config today define xds control plane cluster as static resource. Usually it is accessed by resolving a DNS name. Is it possible after the initial bootstrapping process, the xds control plane just push down its own endpoints to proxies? That is to dynamically override xds control plane's static cluster configuration. 

Thanks.

**Comment by htuch** [comment]
I have deja vu on this topic of dynamic clusters overriding static ones. I think we don't allow it due to complexity and confusion potential, @mattklein123 or @snowp  might remember better (it's come up a few times).

**Comment by mattklein123** [comment]
> I have deja vu on this topic of dynamic clusters overriding static ones. I think we don't allow it due to complexity and confusion potential, @mattklein123 or @snowp might remember better (it's come up a few times).

Yeah agreed this has been discussed before, and I also agree that the complexity seems dubiously worth it. Is there some reason DNS is not a workable solution for you?

**Comment by manlinl** [comment]
Thanks for the insight. DNS works for us. I was curious if current setup allows making XDS control plane part of the mesh itself.
