### ISSUE TITLE
add sequence id to external processor's processing request

### ISSUE THREAD

**Issue by marcosrmendezthd** [envoyproxy/envoy#18905]
*Description*:

In order to properly reassemble streamed request and response bodies, we could add a sequential identifier than can be used to recreate the full payload in the correct order.

An EPS might defer processing and queue requests to reassemble them later. The EPS can use the request id and time to tag requests, but there is no guarantee that this would be effective in reassembling a payload due to network latency or the actual processing time of the request.

The sequence id could be added to the [processing request](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ext_proc/v3/external_processor.proto#envoy-v3-api-msg-service-ext-proc-v3-processingrequest) or the [body](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ext_proc/v3/external_processor.proto#envoy-v3-api-msg-service-ext-proc-v3-httpbody). Though perhaps adding it to the processing request might be useful for other things.

**Comment by gbrail** [comment]
That's an interesting idea. Would it mean, for example, that we'd add a counter to each "ProcessingRequest" that ext_proc sends to the external processor? That would not be difficult.

However, are you imagining that the processor would send back responses that used the same counter, allowing out-of-order reassembly of streamed payloads in the Envoy proxy? I don't think that'd work, because it'd require that the Envoy proxy hold the entire message body in memory, and in that case you're better off using the "BUFFERED" processing mode anyway.

**Comment by marcosrmendezthd** [comment]
i'm only thinking of the processing request. adding it to the processing response would not scale for the reason you mentioned.

i also thought that adding hints about the request body byte offsets may be useful as well if the information is available. adding the sequence id would basically provide ordering, and the assumption would be that we can recreate the body by appending the bytes in that order.

**Comment by gbrail** [comment]
Is it possible that all you need is an "offset" in the message that we send
with each body chunk? That would be easy to calculate and also would solve
your problem I think.

**Comment by marcosrmendezthd** [comment]
if there is an offset for the request and response body in the processing request, that would solve recreating the request and response body. it can also be a little bit tricky to determine when a request is done, though is there is an end of stream, i thought the sequence id would basically help with that. do the same for the response. what do you think?

processing request w/ request id seq 1 -> request headers
processing request w/ request id seq 2 -> request body offset 0
processing request w/ request id seq 3 -> request body offset 1024
processing request w/ request id seq 4 -> request body offset 2048 (end of stream)
processing request w/ request id seq 5 -> request trailers

processing request w/ request id seq 6 -> response headers
processing request w/ request id seq 7 -> response body offset 0 (end of stream)
processing request w/ request id seq 8 -> response trailers

**Comment by marcosrmendezthd** [comment]
any comments/updates on this issue @gbrail ?

**Comment by marcosrmendezthd** [comment]
@gbrail can we reopen this?
