### ISSUE TITLE
Ensure that each virtual host has at least one route.

### ISSUE THREAD

**Issue by gekonwi** [envoyproxy/envoy#18917]
A [VirtualHost](https://github.com/envoyproxy/envoy/blob/0264041ec7a271c0291aa2d761856045c90aef7e/api/envoy/config/route/v3/route_components.proto#L44) without [routes](https://github.com/envoyproxy/envoy/blob/0264041ec7a271c0291aa2d761856045c90aef7e/api/envoy/config/route/v3/route_components.proto#L94) seems useless. Could we add PGV requiring at least one route in each `VirtualHost`?

Motivation: We recently, accidentally, created such hosts without routes and it took several DEVs quite some time to trace this down.

**Comment by htuch** [comment]
In the presence of the new `matcher`, I think it's harder to write a PGV annotation that captures the "can't route to anything useful property".
