### ISSUE TITLE
Envoy forward headers

### ISSUE THREAD

**Issue by gituserjava** [envoyproxy/envoy#18926]
I am using `envoy.ext_authz` filter with `OPA` as my external authorization service provider. The OPA policy executes successfully however it is returning `403 UAEX` in both success and error scenarios. I tested the policy in Rego playground and it returns `true` in success scenario and `false` in error scenario. I am suspicion whether envoy is sending `x-custom-header` in my use-case. 
**Questions** : 

1. Will envoy forward request headers to OPA or will we need to explicitly pass header to OPA with some Envoy configuration? Please advise.
2. Please advise on how i can troubleshoot this error. Is there a way i can log input headers in envoy or in OPA?

**Policy:**
```
package demo

default allow = false

allow = {
        input.headers["x-custom-header"] == "foo"
}
```

**Input:**
```
{
       "headers": {
              "x-custom-header" :"foo"
        }
}
```
**Rego playground output:**
```
{
     "allow": [
           true
     ]
}
```

**Comment by esmet** [comment]
@gituserjava I believe authorization request headers need to be allowlisted https://github.com/envoyproxy/envoy/blob/e98f39b1b3729c8ee507cf4b64cbbe72e3991457/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L241 though certain ones like Authorization, etc are included automatically.
