### ISSUE TITLE
Free developers from understanding the service topology

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#18953]
Hi community, 
Per my understanding, in the service mesh model, by default, owners of one service have to know the service graph to configure envoy clusters in order to have some important observability (e.g. all envoy upstream cluster metrics) and reliability features (e.g. outlier detection). However, sometimes users don't know what services they are calling and what services are calling them. 
I think an ideal situation is what is mentioned in this [5 years of Envoy OSS](https://mattklein123.dev/2021/09/14/5-years-envoy-oss/) blog. `most engineers did not need to know anything about the real system topology.`

I'm wondering usually how people achieve this?  Solutions I can think of are:
1. users can have the sidecar envoy proxy knows the state of the world - every sidecar knows all services in the system
2. users can get this information from somewhere else. For example, this [blog](https://netflixtechblog.com/how-netflix-uses-ebpf-flow-logs-at-scale-for-network-insight-e3ea997dca96) explains one approach to use ebpf to understand the service dependencies
3. users can onboard the application to service mesh first by using the original destination cluster and access log to get the destination address from logs. After that, users can create envoy clusters and migrate traffic to dedicated envoy clusters.
4. similar to the third solution, users can use the original destination cluster and write a simple lua filter to send the IP information to some sink. The users can analyze the data from the sink.

Thank you!

**Comment by rojkov** [comment]
I'd recommend asking this question in Envoy's user group and in the #envoy-users slack channel to attract more people's attention.

**Comment by hochuenw-dd** [comment]
@mattklein123 A gentle ping since this is your blog 😄  I'm curious about any quick hints that you may have. Thank you!

**Comment by mattklein123** [comment]
> @mattklein123 A gentle ping since this is your blog 😄 I'm curious about any quick hints that you may have. Thank you!

- Sorry I don't have any piece of advice. Any of the options you list could work, it really depends on the overall design of the system you are trying to design which is beyond the scope of Envoy itself. I would recommend talking to other practioners, watching conference talks, etc. for ideas.

**Comment by hochuenw-dd** [comment]
@mattklein123 thanks!
