### ISSUE TITLE
can envoy metrics provide cpu/memory etc. resource usage of upstream

### ISSUE THREAD

**Issue by ryanlyy** [envoyproxy/envoy#18952]
Looking at page, https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats, there is no upstream cpu/memory etc. resource cpu usage. Can envoy provide upstream cpu/memory resource usage? and then envoy can support upstream endpoint cpu usage based load balancing?

Thanks.

**Comment by rojkov** [comment]
I'm not a load balancing expert, but I presume the upstream services could report their load first to something.  For example to a global authority. Then global load balancing could be used:

"[Global load balancing refers to having a single, global authority that decides how load should be distributed between hosts. For Envoy, this would be done by the control plane, which is able to adjust the load applied to individual endpoints by specifying various parameters, such as priority, locality weight, endpoint weight and endpoint health.](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/overview)"
