### ISSUE TITLE
The definition of a filter is confusing.

### ISSUE THREAD

**Issue by Lee-Jong-Woo** [envoyproxy/envoy#18954]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *The definitions of 'global rate limit', 'local rate limit' in network filter, and 'global rate limit', 'local rate limit' in HTTP filter are confusing.*

*Description*:
>What is the reason for dividing the network filter and the http filter, and what does each do?

Each filter has 'Local Rate Limit' and 'Global Rate Limit'.

The total network filter has 'Local Rate Limit' and 'Global Rate Limit', and the HTTP filter has 'Local Rate Limit' and 'Global Rate Limit'.

How are these 4 filters different and in what situations are they appropriate to use?

It is difficult to understand just by referring to the website.

please help.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Lee-Jong-Woo** [comment]
Alse, I confuse the 'External Authorization' in Network filter and the 'External Authorization' in Http filter

I wait the answer

If it is difficult to explain the exact definition, please give an example.

**Comment by rojkov** [comment]
Have you checked these docs:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/local_rate_limiting,
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/global_rate_limiting?

**Comment by Lee-Jong-Woo** [comment]
As I understand it, network filters are filters on L3/L4 and HTTP filters are filters on L7.

And in the HTTP filter, the global rate limit is applied to all routes, and the local rate limit is applied only to some routes for which the local rate limit is set.

Is my understanding so far correct?

Although I have understood this far, it is difficult to understand the difference between the roles of global rate limit and local rate limit in network filters.

**Comment by rojkov** [comment]
> As I understand it, network filters are filters on L3/L4 and HTTP filters are filters on L7.

That's right.

My understanding is that local rate limiting is an additional stage before global rate limiting used to avoid overwhelming the latter. Perhaps a better doc is needed.

/cc @mattklein123 @htuch
