### ISSUE TITLE
Host is not ejected due to race condition in the outlier detection 

### ISSUE THREAD

**Issue by jparklab** [envoyproxy/envoy#18950]
*Title*: **Host is not ejected due to race condition in the outlier detection**

*Description*:

 We use outlier detection with consecutive_local_origin_failure to eject hosts. 
 When a host is down for a longer period of time(>10 minutes), we occasionally see that envoy stops ejecting the troubled host after the host has been ejected and unejected several times, and, keeps sending requests to the host afterwards.

 I instrumented envoy with addtional debug logging, and below is what I found is causing the issue.

 When envoy sees a connection timeout to an upstream host, envoy checks the consecutive_local_origin_failure_ counter and ejects the host as below.
 
 1. [worker thread] DetectorHostMonitorImpl::localOriginFailure: The function is called when envoy detects a local origin error, it increments consecutive_local_origin_failure_ counter , and calls onConsecutiveLocalOriginFailure method on detector which notifies the main thread to eject the host.
 ```
 void DetectorHostMonitorImpl::localOriginFailure() {
  std::shared_ptr<DetectorImpl> detector = detector_.lock();
  if (!detector) {
    // It's possible for the cluster/detector to go away while we still have a host in use.
    return;
  }
  local_origin_sr_monitor_.incTotalReqCounter();
  if (++consecutive_local_origin_failure_ ==
      detector->runtime().snapshot().getInteger(
          ConsecutiveLocalOriginFailureRuntime,
          detector->config().consecutiveLocalOriginFailure())) {
    detector->onConsecutiveLocalOriginFailure(host_.lock());
  }
 }
 ```
 2. [main thread] DetectorImpl::onConsecutiveErrorWorker: checks healthFlag to see if the host is already flagged as FAILED_OUTLIER_CHECK. If not, proceed to the next steps
 3. [main thread] DetectorImpl::onConsecutiveErrorWorker: ejectHost method is called in to eject host. the method will set the healthFlag of the host to be FAILED_OUTLIER_CHECK
 4. [main thread] DetectorImpl::onConsecutiveErrorWorker: resetConsecutiveLocalOriginFailure is called to reset consecutive_local_origin_failure_ counter
 ```
void DetectorImpl::onConsecutiveErrorWorker(HostSharedPtr host,
                                            envoy::data::cluster::v3::OutlierEjectionType type) {
  // Ejections come in cross thread. There is a chance that the host has already been removed from
  // the set. If so, just ignore it.
  if (host_monitors_.count(host) == 0) {
    return;
  }
  if (host->healthFlagGet(Host::HealthFlag::FAILED_OUTLIER_CHECK)) {
    return;
  }

  // We also reset the appropriate counter here to allow the monitor to detect a bout of consecutive
  // error responses even if the monitor is not charged with an interleaved non-error code.
  updateDetectedEjectionStats(type);
  ejectHost(host, type);

  // reset counters
  switch (type) {
  case envoy::data::cluster::v3::CONSECUTIVE_5XX:
    stats_.ejections_consecutive_5xx_.inc(); // Deprecated
    host_monitors_[host]->resetConsecutive5xx();
    break;
  case envoy::data::cluster::v3::CONSECUTIVE_GATEWAY_FAILURE:
    host_monitors_[host]->resetConsecutiveGatewayFailure();
    break;
  case envoy::data::cluster::v3::CONSECUTIVE_LOCAL_ORIGIN_FAILURE:
    host_monitors_[host]->resetConsecutiveLocalOriginFailure();
    break;
  default:
    // Checked by schema.
    NOT_REACHED_GCOVR_EXCL_LINE;
  }
}
```
 
 If there is another pending request to upstream that times out, it follows step 1. and 2. but does not proceed to step 3 and 4 since the host has been flagged as FAILED_OUTLIER_CHECK.
 Since step 4 is skipped. consecutive_local_origin_failure_ counter is not reset to 0, and thus, it never becomes lower than the threshold value.
 
 
*Repro steps*:

Run the envoy with the configuration below, and have a http server that listens to the one of the endpoints addresses, and run multiple clients that send requests simultaneously.
Here's python code I used to reproduce the issue

```
import requests
import time
from concurrent.futures import ThreadPoolExecutor

session = requests.Session()
def send_queries(url):
    fast_count = 0
    consecutive_slow_response = 0

    for idx in range(10000):
        start_time = time.time()
        r = session.get(url)
        r.raise_for_status()
        duration = time.time() - start_time

        if duration > 0.5:
            print("[{}] Duration {:.2f} ms, Downstream: {}, Client Addr: {}, Instance: {}. After {} fast responses".format(
                idx,
                duration * 1000,
                r.headers['x-downstream'],
                r.headers['X-remote'],
                r.headers['X-instance'],
                fast_count
            ))
            if fast_count == 0:
                consecutive_slow_response += 1
                if consecutive_slow_response > 2:
                    print("consecutive slow responses, stopping")
                    break
            else:
                consecutive_slow_response = 0
            fast_count = 0
        else:
            fast_count += 1
        time.sleep(0.1)
        

NUM_THREADS=2
with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
    works = []
    for _ in range(NUM_THREADS):
        works.append(executor.submit(send_queries, 'http://192.168.1.102:8080'))

    for w in works:
        w.result()
```

I was able to reproduce the issue with envoy version 1.19.1 and 1.20.0

*Config*:

```envoy.yaml
node:
  cluster: test-cluster
  id: test-id

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

cluster_manager:
  outlier_detection:
    event_log_path: "./eject-event.log"

dynamic_resources:
  lds_config:
    path: "./envoy-lds.yaml"
  cds_config:
    path: "./envoy-cds.yaml"

```

```envoy-cds.yaml
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: dynamic_service
  connect_timeout: 1.0s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  outlier_detection:
    # consecutive_5xx: 1
    consecutive_local_origin_failure: 1
    interval: 1s
    base_ejection_time: 2s
    max_ejection_time: 3s
    split_external_local_origin_errors: true

  load_assignment:
    cluster_name: dynamic_service
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8081
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8082
```

```envoy-lds.yaml
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8080
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http_3
        http_filters:
        - name: envoy.router
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains: ["*"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: dynamic_service }
            # https://www.envoyproxy.io/docs/envoy/latest/api-v3/config \
            # /route/v3/route_components.proto#config-route-v3-retrypolicy
            retry_policy:
              retry_on: "connect-failure,refused-stream,gateway-error"
              num_retries: 1
        http_filters:
        - name: envoy.filters.http.router
```

**Comment by jparklab** [comment]
This can be fixed by resetting the counter inside  DetectorImpl::checkHostForUneject. I can make a PR for the fix, but would like to hear if that is the right way to fix this issue.

**Comment by rojkov** [comment]
@cpakulski would you mind looking at it?

**Comment by cpakulski** [comment]
@rojkov. Sure - I will take care of this.

**Comment by cpakulski** [comment]
@jparklab I am trying to repro this, but since Envoy and backend webservers are running on the same host in my setup I never experience any timeout. I have a full control of webservers, so I can easily add a timeout before replying. If I add a random delay to a webserver, say between 0-2 seconds, do you think that the described scenario should occur?

**Comment by jparklab** [comment]
You can simply have a cluster with two endpoints where one of the endpoints point to an invalid ip address/port, and the other points to your webserver.

**Comment by cpakulski** [comment]
@jparklab Yes, you are right. Your proposed fix is fine. consecutive5xx and gateway counters are already reset in https://github.com/envoyproxy/envoy/blob/release/v1.20/source/common/upstream/outlier_detection_impl.cc#L358-L359, so you can also call `resetConsecutiveLocalOriginFailure`().

**Comment by jparklab** [comment]
@cpakulski Thanks for checking. I created a PR with the fix: #19205

**Comment by cpakulski** [comment]
I will try to construct a unit test to simulate timeouts and see if it triggers the bug (as suggested in #19205 comment).

**Comment by cpakulski** [comment]
ping.
