### ISSUE TITLE
x-envoy-upstream-service-time clarification

### ISSUE THREAD

**Issue by theganyo** [envoyproxy/envoy#18959]
The header documentation says:

```
Contains the time in milliseconds spent by the upstream host processing the request and the 
network latency between Envoy and upstream host. This is useful if the client wants to determine
service time compared to network latency between client and Envoy. This header is set on responses.
```

Can this be defined even more precisely? I assume this duration begins at "first byte sent to target" - but is it "first byte received from target" or "last bye received from target" or something different? Thanks!

**Comment by rojkov** [comment]
@wbpcode Do you still remember the details?

**Comment by theganyo** [comment]
Thank you!

**Comment by lxv458** [comment]
hi, @wbpcode @theganyo  

I went through the code of envoy and draw the flow of some kind of durations reported in accesslog, I think it is very useful for debuging latency errors. And would you like to double check whether it is correct?

 ![accesslog](https://user-images.githubusercontent.com/11827241/148384360-9d9ce3c7-c1ac-4b90-b8bf-198666cdcca1.png)

**Comment by mccurdyc** [comment]
@lxv458 I just wanted to express my gratitude for your diagram! I would love to see this in the official docs.

For folks like myself looking for `Request_TX_Duration`, it IS now supported in the access log via `%REQUEST_TX_DURATION%`.

v1.26.4 docs - https://www.envoyproxy.io/docs/envoy/v1.26.4/configuration/observability/access_log/usage.html

**Comment by Tony-Peteryu** [comment]
@lxv458 
hi！May I ask how to understand the DURATION field and RESP (X-ENVOY-UPSTREAM SERVICE TIME) field in the access logs of both the client and server after using the ISIO proxy in a request

**Comment by bofeng96** [comment]
> hi, @wbpcode @theganyo
> 
> I went through the code of envoy and draw the flow of some kind of durations reported in accesslog, I think it is very useful for debuging latency errors. And would you like to double check whether it is correct?
> 
> ![accesslog](https://user-images.githubusercontent.com/11827241/148384360-9d9ce3c7-c1ac-4b90-b8bf-198666cdcca1.png)

Nice graph

**Comment by akashjain971** [comment]
> hi, @wbpcode @theganyo
> 
> I went through the code of envoy and draw the flow of some kind of durations reported in accesslog, I think it is very useful for debuging latency errors. And would you like to double check whether it is correct?
> 
> ![accesslog](https://user-images.githubusercontent.com/11827241/148384360-9d9ce3c7-c1ac-4b90-b8bf-198666cdcca1.png)

Can you also include the new metric `COMMON_DURATION` in this diagram? 
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators
