### ISSUE TITLE
tracing: Use openapi definition for service to enhance tracing information

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#1897]
As mentioned by @rshriram in https://github.com/envoyproxy/envoy/pull/1858#discussion_r145196231 it would be good to use an openapi description of the service to enhance the tracing information.

This could include:
* setting the operation name to the operationId, or if not available, the method and path template
* using any path parameters to extract the parameter values and associate them as tags with the span

**Comment by ayj** [comment]
Istio is starting to add support for OpenAPI. See [github.com/istio/api/mixer/v1/config/client/api_spec.proto](https://github.com/istio/api/blob/master/mixer/v1/config/client/api_spec.proto) for the normalized specification which should support most any HTTP based API spec, e.g. OpenAPI2, OpenAPI3, and gRPC. To give an idea of how this is used, see the corresponding path (uri_template) matching code under https://github.com/istio/mixerclient/tree/master/api_spec.

We could consider adding the equivalent as a filter in Envoy. It would be useful for other API related features as well, e.g. quota.

**Comment by objectiser** [comment]
@ayj Is this information going to be used to enrich the tracing span data in the mixer?
