### ISSUE TITLE
question: how to improve the ipv6 support in envoy

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#18973]
I'm trying to answer a very generic question about how was the ipv6 support in Envoy. 

For answer this question, ​I checked the unit-test and integration test, there is infrastructure in those tests for testing both ipv4 and ipv6. I think that means the major functionality was being tested with ipv6. I also searched the issue, there aren't too much ipv6 related issues. 

So can I say envoy already support ipv6 well? Do we need anything to improve ipv6 support further? (I guess through test, more integration and functional tests..etc) 

Appreciate any feedback or comment!

**Comment by ggreenway** [comment]
As far as I know, Envoy fully supports IPv6.

**Comment by soulxu** [comment]
> As far as I know, Envoy fully supports IPv6.

thanks for the feedback!
