### ISSUE TITLE
[Oauth] Option to customize sign-out redirect

### ISSUE THREAD

**Issue by joberdick-rcd** [envoyproxy/envoy#18983]
*Title*: [Oauth] Option to customize sign-out redirect

*Description*:
Currently, the oauth2 filter redirect after 'signout_path' path is used it redirects to /. This does not allow for logout of of the identity provider and in many cases might just re-trigger login if / is used by the application. 

It would make sense to have to ability to customize where the redirect after sign-out goes to suit the need of that use case.

**Comment by chenwng** [comment]
Encountered the same issue during integration with keycloak. It would be good to be able to configure the logout endpoint for signout redirection.

**Comment by dagtveit** [comment]
i have the same issu aswell is no one looking into this ?

**Comment by johnpmayer** [comment]
Yeah, this feels like it wouldn't be terribly hard to add.

- A new configuration option, signout_redirect_uri
- Pipe it into the filter
- Use it here

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/oauth2/filter.cc#L509

I may take a crack at this.

**Comment by fiadliel** [comment]
A nice-to-have here would be to allow a no redirect option too (e.g. 204 No Content). This would allow the endpoint to be used in cases where it's invoked in a background iframe, for example, from a single signout system, without adding extra unnecessary calls.

**Comment by kkumlien** [comment]
@vikaschoudhary16 you working on this? looks like just a matter of changing this hard-coded **new_path** to a [type.matcher.v3.PathMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/path.proto#envoy-v3-api-msg-type-matcher-v3-pathmatcher) parameter:

`  const std::string new_path = absl::StrCat(headers.getSchemeValue(), "://", host_, "/");`

here: https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/oauth2/filter.cc#L552

or for quick fix, even and env variable would do (for me).
