### ISSUE TITLE
Client connection should not call socket::connect if bind local address fails

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#18981]
Currently the client connection binds is called in its constructor. The bind can fail.

The client connection owner is unaware of this failure, usuallly ClientConnection::connect() is called after.

So it's ClientConnection that check the bind has failed and not call underlying socket::connect after.

It's not a hard failure since the event callback will detect the localclose value as set by the failing bind()

**Comment by antoniovicente** [comment]
@AndresGuedez @alyssawilk 

Possible solutions would involve use of a factory method to create the socket and bind it.

**Comment by davinci26** [comment]
Interesting find. The same thing if the call to apply socket options also fails (`STATE_PREBIND`).

We already have a `bind_error_` variable that we could leverage to return early if the caller tries to connect when we know that something is already wrong.
