### ISSUE TITLE
Version History not in sync

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#18985]
*Title*: *Version History details not abailble for v1.18.0 and 1.18.1 in path https://www.envoyproxy.io/docs*

*Description*: Seems Version Hostory is out of sync with https://www.envoyproxy.io/docs/envoy/v1.18.2/version_history/version_history
>Describe the issue.

**Comment by phlax** [comment]
iirc these docs were not produced during release, not sure why, but the releases all happened on the same day (1.18.x - 2) so i pointed them all at 1.18.2

not sure if there is any need to fix this
