### ISSUE TITLE
envoy 1.20 build fails due to unknown warning option '-Wno-maybe-uninitialized

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#18986]
Title: envoy 1.20 build fails using clang due to unknown warning option '-Wno-maybe-uninitialized'

Description:

We are trying to build new envoy binary based envoy 1.20 source code but we are facing some issues:

```
error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]
Target //source/exe:envoy-static failed to build

```
We are compiling using CLANG. Below is a section of our Dockerfile used for the build:

```

WORKDIR /tmp
--
  | RUN	git clone https://"${GERRIT_USERNAME}:${GERRIT_PASSWORD}"@gerrit.ericsson.se/a/3pp/foss/github.com/envoyproxy/envoy
  | #RUN git clone https://github.com/envoyproxy/envoy.git
  | WORKDIR /tmp/envoy
  | RUN	git checkout ${ENVOY_VERSION}
  | RUN	CC=clang CXX=clang++ bazel build --fission=no -c opt //source/exe:envoy-static
  | RUN	strip bazel-bin/source/exe/envoy-static -o bazel-bin/source/exe/envoy

```

Compiling exactly in the same way with envoy 1.18.4 source code we didn't have any issue.

Can you please suggest how to fix  it?

Thanks!

**Comment by lambdai** [comment]
The clang version matters.  What's your clang version?

main branch is well tested using clang-12

I think istio CI is building envoy 1.20 using llvm-11 and I don't see this error there

**Comment by eoregua** [comment]
Hi,

We also tried with clang-12 and llvm-11 and we have the same issue:

'''
ERROR: /tmp/envoy/source/extensions/clusters/redis/BUILD:20:17: Compiling source/extensions/clusters/redis/redis_cluster_lb.cc failed: (Exit 1): clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 196 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.

'''

This is a section of the our Dockerfile used for the build:

'''
RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-sles12.4.tar.xz \
 && tar -xf clang+llvm-12.0.0-x86_64-linux-sles12.4.tar.xz \
 && cd clang+llvm-12.0.0-x86_64-linux-sles12.4 \
 && cp -rf bin/* /usr/bin/ \
 && cp -rf lib/* /usr/lib/ \
 && cp -rf share/* /usr/share/ \
 && rm /clang+llvm-12.0.0-x86_64-linux-sles12.4.tar.xz \
 && rm -rf /clang+llvm-12.0.0-x86_64-linux-sles12.4
RUN git clone https://github.com/llvm/llvm-project.git \
 && cd llvm-project \
 && git checkout llvmorg-11.0.0 \
 && mkdir build/ \
 && cd build/ \
 && cmake -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi"  -Wno-error=deprecated -G "Unix Makefiles" ../llvm \
 && make cxx \
 && make install-cxx install-cxxabi \
 && cp -rf /usr/local/lib/* /usr/lib/ \
 && cp -rf /usr/local/include/* /usr/include/
#
# Seems, libncurses needs to be installed after installing parts of llvm-project
#
RUN zypper install --auto-agree-with-licenses --no-confirm libncurses5 \
        && zypper clean --all
WORKDIR /tmp
RUN     git clone https://"${GERRIT_USERNAME}:${GERRIT_PASSWORD}"@gerrit.ericsson.se/a/3pp/foss/github.com/envoyproxy/envoy
#RUN git clone https://github.com/envoyproxy/envoy.git
WORKDIR /tmp/envoy
RUN     git checkout ${ENVOY_VERSION}
RUN     CC=clang CXX=clang++ bazel build  --fission=no -c opt //source/exe:envoy-static
RUN     strip bazel-bin/source/exe/envoy-static -o bazel-bin/source/exe/envoy


'''

**Comment by rojkov** [comment]
`-Wno-maybe-uninitialized` is a gcc specific option added in case of bazel detecting gcc. You can try to modify your build command as `bazel build --config=clang ...` (no need to set CC/CXX).

**Comment by eoregua** [comment]
The build was modified:
```
RUN	 bazel build --config=clang  --fission=no -c opt //source/exe:envoy-static

```
Failed with the following reason:

```
ERROR: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/com_google_absl/absl/debugging/BUILD.bazel:31:11: Compiling absl/debugging/stacktrace.cc [for host] failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 55 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

```

Building instead in the following way:

```

RUN	CC=clang CXX=clang++ bazel build --config=clang --fission=no -c opt //source/exe:envoy-static

```
Requires too much space on disk and it's failing:


```
Use --sandbox_debug to see verbose messages from the sandbox
ld.lld: error: failed to open bazel-out/k8-opt/bin/source/exe/envoy-static: No space left on device
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.

```

The build instead is working fine replacing -Wno-maybe-uninitialized with -Wno-uninitialized in / bazel/envoy_internal.bzl but I don't know if it's right way to overcome this building issue:

```

RUN     git checkout ${ENVOY_VERSION}
RUN     sed -i s/""/ bazel/envoy_internal.bzl
RUN     CC=clang CXX=clang++ bazel build --fission=no -c opt //source/exe:envoy-static
RUN     strip bazel-bin/source/exe/envoy-static -o bazel-bin/source/exe/envoy

```

**Comment by kamesh7773** [comment]
Use this Kali Linux ISO file from the following link: https://drive.google.com/file/d/1XvstnTnKlKm7lMqZbrff7h_qD67DNA4e/view?usp=sharing

This ISO already includes installed drivers, so you only need to boot from it and plug in your TP-Link (TL-WN722N) WiFi adapter.
