### ISSUE TITLE
how to run envoy as a daemon or into background

### ISSUE THREAD

**Issue by SanZhiYuan** [envoyproxy/envoy#19000]
I can not find a command line arg or a config option to run envoy as a daemon, 

> as https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy mentioned
>  * To start Envoy as a system daemon download the demo configuration, and start as follows:
>  * envoy -c envoy-demo.yaml

the envoy process still runs on foreground, so how to run envoy  as a daemon on background?

I'm running envoy with version: 96701cb24611b0f3aac1cc0dd8bf8589fbdf8e9e/1.20.0/Modified/RELEASE/BoringSSL installed by homebrew on MacOS Catalina 10.15.7

thanks

**Comment by rojkov** [comment]
I think there's no functionality for detaching from e.g. interactive terminal sessions in Envoy.

Why would you need it? Docker or systemd need to be Envoy's parent process to control e.g. restarts.

**Comment by SanZhiYuan** [comment]
thanks for explain.

we were using haproxy / nginx as our proxy, they both have a daemon option, so I am hoping the same thing from envoy.

I think a daemon process may easy for developers to 'play' with envoy, docker still a little heavy and systemd may require too much privileges.

> I think there's no functionality for detaching from e.g. interactive terminal sessions in Envoy.
> 
> Why would you need it? Docker or systemd need to be Envoy's parent process to control e.g. restarts.
