### ISSUE TITLE
docs: links broken for items like http_filters/grpc_json_transcoder_filter

### ISSUE THREAD

**Issue by kriswuollett** [envoyproxy/envoy#19017]
*Title*: docs: links broken for items like http_filters/grpc_json_transcoder_filter

*Description*:

Links to documentation like that found in the [Sample Envoy configuration for gRPC JSON transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration) use a link path that predates #8027. Following these links yield page not found. Also the web links no longer need to use the `www` prefix.

**Comment by ankatare** [comment]
seems it is tc in  #19101
