### ISSUE TITLE
Does envoy provide a clock timer?

### ISSUE THREAD

**Issue by qls152** [envoyproxy/envoy#19029]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Does envoy provide a clock timer?*

*Description*:
Does envoy provide a clock timer? It can calculate the operating time of a certain function and perform corresponding management. If not, I plan to provide one here.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
May be you can provide more background info to describe you needs. For example, why we need this feature ? After that, we can discuss it further.

**Comment by qls152** [comment]
> May be you can provide more background info to describe you needs. For example, why we need this feature ? After that, we can discuss it further. 😃

We want to calculate the time and total time of each path experienced by any request in the same filter to assist in troubleshooting and optimization of critical paths in business processing. Timesource in Envoy provides a poorly abstracted function to meet this demand.

**Comment by wbpcode** [comment]
May be profile is more suitable for this need?

**Comment by qls152** [comment]
> May be profile is more suitable for this need?

It can not use to log。we want to log some time。

**Comment by rojkov** [comment]
Would [Perfetto](https://perfetto.dev/docs/instrumentation/tracing-sdk) work for you? There's #17591 adding preliminary support for it in Envoy.

**Comment by qls152** [comment]
> Would [Perfetto](https://perfetto.dev/docs/instrumentation/tracing-sdk) work for you? There's #17591 adding preliminary support for it in Envoy.

thanks， it is Okay！
