### ISSUE TITLE
headers op cannot evaluate REQUESTED_SERVER_NAME

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#19024]
reported by Jack Muratore  https://envoyproxy.slack.com/archives/C78M4KW76/p1637074615179900

"%REQUESTED_SERVER_NAME%" can not be evaluated in the headers op, which can be used by tcp_proxy's tunnel and http router. 
I suspect access log cannot use it as well.

The root cause is that this legit var name  REQUESTED_SERVER_NAME has the prefix "REQ" and the parser tried to parse it as a format of 
"REQ(...)".

**Comment by banjocat** [comment]
To clarify. It does work in access_logs it just doesn't work in add_headers.

**Comment by agrawroh** [comment]
Created a PR to add it:
https://github.com/envoyproxy/envoy/pull/19038
