### ISSUE TITLE
QuicHttpIntegrationTest.NoPortMigrationWithoutConfig flaky

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#19027]
This test fails with $ bazel test test/integration:quic_http_integration_test --runs_per_test=2000 --test_filter="*NoPortMigrationWithoutConfig*"

[ RUN      ] QuicHttpIntegrationTests/QuicHttpIntegrationTest.NoPortMigrationWithoutConfig/IPv4
test/integration/quic_http_integration_test.cc:608: Failure
Value of: quic_connection_->waitForPathResponse(std::chrono::milliseconds(2000))
  Actual: true
Expected: false
Stack trace:
  0x2992ae9: Envoy::Quic::QuicHttpIntegrationTest_NoPortMigrationWithoutConfig_Test::TestBody()
  0x5c4b944: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x5c3ba9e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x5c24123: testing::Test::Run()

**Comment by RenjieTang** [comment]
I ran the command a few times, but I wasn't able to reproduce this flakiness.
This test scenario is that without port migration config, the client will not receive any path response after path degrading is triggered.
Hmmm I wonder how this could be flaky.

**Comment by danzh2010** [comment]
This is likely a result of https://github.com/envoyproxy/envoy/issues/19283. Close it here.
