### ISSUE TITLE
tcp_proxy access logs for failed upstream connection attempts

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#19035]
I'd like to log failed upstream connection attempts from tcp_proxy.

One possible implementation would be similar to `upstream_log` on the http router. But there's very little to log for the failure cases; far less useful information than there can be from an http request, due to fewer failure modes.

Another option would be an additional access log formatter that prints the list of upstream addresses attempted. This is less flexible, but also less verbose (failures are in the one and only access log line for this connection).

A third option is to emit a log with some given configuration only for failed upstream attempts, so that in the success case (first connect attempt succeeds), logs look exactly as they do now, but in the case of a failure, an additional log could be emitted.

Any opinions on these options, or other ideas?

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk

**Comment by alyssawilk** [comment]
I'd definitely be interested in rich details for what failed, especially for things like handshake failure and better explanation of why upstream endpoints were unhealthy (which we may have data on)

**Comment by ggreenway** [comment]
I think for flexibility and consistency with http, it makes the most sense to add `repeated config.accesslog.v3.AccessLog upstream_access_log`, instead of adding a formatter that tries to log the history for all attempts in one log line.

Thinking through how to implement, and use cases, I think it will only be useful in the failure cases, so would it make sense to name the field something like `upstream_failed_attempt_access_log`, and only log in the fail-to-connect cases? Because I think in the success cases, the downstream and upstream info will be the same so there's not much value in having a separate downstream and upstream access log for a success.

Another option is to leave it as `upstream_access_log`, and log in both the failure and success case, but leave it up to a user-configured access log filter to only log if the response flags are non-zero or something. With this approach, I'm not sure how to best handle the `StreamInfo::UpstreamInfoImpl`, which is currently shared between upstream attempts in tcp_proxy (and so a failure of any attempt can be seen in the response flags). Maintaining compatibility with current behavior would be tricky, but doable.

@alyssawilk any opinions on this (as the only person to express interest in this so far)?

**Comment by alyssawilk** [comment]
hmmm, I have something different in mind which ideally we'd find a way to have overlap but may just not.

IMO we should have generic details for disconnect reasons.  Often the reason for disconnect may be upstream connection failure, but there are other disconnect details that would presumably be relevant like RBAC nacking or DNS failure that I think we'd want to track.  But those would presumably be singular failures

**Comment by ggreenway** [comment]
> we should have generic details for disconnect reasons

Are you thinking about something like adding `%UPSTREAM_CONNECTION_TERMINATION_DETAILS%`?

**Comment by alyssawilk** [comment]
I'm thinking I want information not just about why upstream terminated, I want information about why the session in general was terminated, so I guess downstream termination details.  Often downstream will be "because upstream connectivity failed" but there are other reasons like those I mentioned above.

**Comment by ggreenway** [comment]
I think we're trying to solve different problems. I just want to have a log of the failed upstream attempts.
