### ISSUE TITLE
How to get xDS information on envoy filter

### ISSUE THREAD

**Issue by Patrick0308** [envoyproxy/envoy#19031]
*Title*: *How to get xDS information on envoy filter*

*Description*:
How to get EDS/RDS/CDS information on envoy filter, I want to modify request headers base on xDS information.

**Comment by rojkov** [comment]
Filters and xDS belong to different planes.

Could you please elaborate your use case?

**Comment by Patrick0308** [comment]
I want to impact routing rules. I think I should modify the control plane. Thanks, for your reply.
