### ISSUE TITLE
[Feature] I can't find UDP proxy rate limit API Settings.

### ISSUE THREAD

**Issue by laskdjlaskdj12** [envoyproxy/envoy#19042]
*Title*: *One line description*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Is there any example about UDP Proxy Local rate limit settings? 
i only find local rate limit filter is accepts in filter_chains in filters

i am using 1.18.2 envoy version and v3 api

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
cc @phlax
