### ISSUE TITLE
ci: boringssl_fips package is inaccessible

### ISSUE THREAD

**Issue by rojkov** [envoyproxy/envoy#19060]
*Title*: *boringssl_fips package is inaccessible*

*Description*:

Currently all CI builds are broken because one dependency became inaccessible.

*Logs*:
https://dev.azure.com/cncf/envoy/_build/results?buildId=94876&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467

The relevant part is
```
WARNING: Download from https://commondatastorage.googleapis.com/chromium-boringssl-fips/boringssl-ae223d6138807a13006342edfeef32e813246b39.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

**Comment by PiotrSikora** [comment]
cc @agl @davidben

**Comment by agl** [comment]
Thanks for the notice. This has been restored. (I forgot that these files were being hosted in an otherwise unused project.)

**Comment by rojkov** [comment]
Thank you @agl! Everything works now.
