### ISSUE TITLE
Envoy routing scalability & performance question

### ISSUE THREAD

**Issue by manlinl** [envoyproxy/envoy#19067]
*Title*: *Envoy routing scalability & performance question*

*Description*: some context, recently we are evaluating introducing service mesh into our service platform. Our goal is to support 2k+ services on a single mesh. We are POCing using Envoy hijacks outbound HTTP/gRPC traffic and route based on target domain (`:authority`). 

AFAIK, the XDS today doesn't support lazily requesting routing policy based on ":authority" header it sees in traffic, instead it asks for all possible routes, that is O(2k+), routes. For each request, Envoy need to match the route. Is the algorithm O(1) or O(n) today? 

Istio uses one virtual listener per destination port to shard the outbound routes. I am not sure how many listeners Envoy can handle? In our case, our services are pretty homogeneous, exposing port 80/443. So we have a huge routing table. I appreciate if some expert can provide some insight on the best practice.

**Comment by RyanTheOptimist** [comment]
cc: @asraa

**Comment by manlinl** [comment]
Friendly ping...

**Comment by asraa** [comment]
Hey! Sorry for the break -- routing is O(n), the issue is tracked here https://github.com/envoyproxy/envoy/issues/6602 and will probably have better responses for what the status of that is.

**Comment by manlinl** [comment]
Thank you @asraa! Just another related question, scoped routing configuration uses a key e.g., a header value to pick a route. Is it O(1)?
