### ISSUE TITLE
Unable to build arm64  generate_bytecode_builtins_list

### ISSUE THREAD

**Issue by maikoulin** [envoyproxy/envoy#19089]
I'm encountering a strange error when building arm64(aarch64) 

And during wee8 building, there is a strange error:

[130/1236] CXX obj/third_party/inspector_protocol/crdtp/cbor.o
[131/1236] LINK ./bytecode_builtins_list_generator
[132/1236] ACTION //:generate_bytecode_builtins_list(//build/toolchain/linux/unbundle:default)
FAILED: gen/builtins-generated/bytecodes-builtins-list.h
python ../../tools/run.py ./bytecode_builtins_list_generator gen/builtins-generated/bytecodes-builtins-list.h
Return code is -11

**Comment by RyanTheOptimist** [comment]
cc:@lizan

**Comment by lizan** [comment]
What's your build environment? Are you using envoy-build container to build?

**Comment by maikoulin** [comment]
Version: https://github.com/envoyproxy/envoy/archive/7f2d69f96843583d109082e89aecb6cd52365eb2.tar.gz
OS: Ubuntu 18.04.6 LTS
Architecture: ARM64

I tried to build envoy with the envoy-build-ubuntu image, and the final result was also this error.

**Comment by maikoulin** [comment]
Same as in this question。
https://github.com/envoyproxy/envoy/issues/17491

**Comment by timonwong** [comment]
> Same as in this question。
> #17491

Also #17100

**Comment by timonwong** [comment]
@maikoulin 
Ad discussed in #17100, you can patch `wee8.genrule_cmd`

```bash
elif [[ $${ARCH} == "aarch64" || $${ARCH} == "arm64" ]]; then
  WEE8_BUILD_ARGS+=" target_cpu=\"arm64\""

  # Force align with 64k for aarch64
  export LDFLAGS="$${LDFLAGS-} -z max-page-size=0x10000"
fi
```
