### ISSUE TITLE
Add a tag to Envoy Access Logging (command operator)

### ISSUE THREAD

**Issue by Edimo24** [envoyproxy/envoy#19092]
I am trying to customize some of envoy operators. I would like to add some tags to different operators in envoy source code like %DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT% but I am not sure how to do it since I do not have experience with Envoy source code.
I need something like %[tag]DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT[/tag]%. Any suggestion where in the source code do I have to make the changes?

**Comment by RyanTheOptimist** [comment]
cc: @asraa

**Comment by Edimo24** [comment]
@asraa I would appreciate any suggestion

**Comment by asraa** [comment]
Hey! 

Take a look at https://github.com/envoyproxy/envoy/blob/b610fba9a94217ed48c939b04278635e7f2b2283/source/common/formatter/substitution_formatter.h#L22

You'd need to make changes in that module

**Comment by Edimo24** [comment]
Hello,

I checked the one that you mentioned but in the substiturion_formatter.h there is nothing similar with what I am trying to do (I checked here: https://github.com/envoyproxy/envoy/blob/b610fba9a94217ed48c939b04278635e7f2b2283/source/common/formatter/substitution_formatter.h)

**Comment by Edimo24** [comment]
Hello @asraa,

I am trying to add a string to a command operator but as far as I can understand this command operator does not return a string. Is there any way how to convert it to string?

I am trying to do the changes in substitution_formatter.cc for the DOWNSTREAM_LOCAL_ADDRESS command operator.
The idea was to convert the command operator to a string and then concatenate with another string (see below).

I tried to use asSring() but apparently it did not work (How can I check if asString is supported for this command operator).

} else if (field_name == "DOWNSTREAM_LOCAL_ADDRESS") {
field_extractor_ =
StreamInfoAddressFieldExtractor::withPort([](const StreamInfo::StreamInfo& stream_info) {
std::string localaddress;
localaddress = stream_info.downstreamAddressProvider().localAddress()->asString();
std::string changed_localaddress = "[text I want to add]" + localaddress + "[/text I want to add]";
return changed_localaddress;
});
