### ISSUE TITLE
404 when using remote WASM code from private github repos

### ISSUE THREAD

**Issue by dlcrista** [envoyproxy/envoy#19096]
*Title*: *Cannot use the remote wasm code from a private github repo*

*Description*:
> Is it possible to use a private github repo as the uri for httpuri? If so, how? I am getting a 404 issue. It doesn't seem like this it is able to do this directly from here, from reviewing the docs. It seems to expect the github repo to be public!

[optional *Relevant Links*:]
>The docs are provided here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/http_uri.proto#envoy-v3-api-msg-config-core-v3-httpuri

**Comment by ggreenway** [comment]
cc @envoyproxy/wasm-dev
