### ISSUE TITLE
Envoy appears to resolve "localhost" incorrectly when windows VPN is turned on?

### ISSUE THREAD

**Issue by tomqwpl** [envoyproxy/envoy#19112]
I have a weird problem with Envoy.
I'm using 1.20 on Windows : `version: 96701cb24611b0f3aac1cc0dd8bf8589fbdf8e9e/1.20.0/Modified/RELEASE/BoringSSL`

I have some clusters configured, and the hostname is "localhost". These work fine normally, and envoy can connect to the upstream hosts.
However, when I turn the Windows VPN on to connect to work it all stops working. Envoy resolves localhost and gets an incorrect IP address. Well, kind of incorrect. It appears to be the external internet facing IP address of my broadband router. It's the same value as google reports if I ask it "what is my IP address". So correct at some level, but not useful since clearly I wouldn't be able to connect to my upstream servers using it.

Still with the VPN turned on, using golang `net.LookupIP("localhost")`, I get `127.0.0.1`, which is what I would expect. Maybe they have a shortcut for that though.

This doesn't feel like expected behaviour to me, indeed it's something I would have to work round in all likelyhood. However, I'm hoping someone more knowledgeable in networking might be able to say whether this was a bug or not.

Thanks

**Comment by ggreenway** [comment]
cc @wrowe

**Comment by wrowe** [comment]
This is the nature of Windows dns, and would be worth examining a workaround/hardcoded hack. Whether that belongs in c-ares or envoy itself is a topic worth discussing first.
