### ISSUE TITLE
Are initialized zipkin and datadog trace ids different?

### ISSUE THREAD

**Issue by seglo** [envoyproxy/envoy#19110]
*When envoy is configured to initialize traces and propagate them as zipkin and datadog HTTP headers the IDs seem to be different*

*Description*:

If DataDog and b3/zipkin tracing is enabled and a trace is initialized do the corresponding ids have any relationship to one another or is each randomly generated?  DataDog trace ids are typically 64 bit long integers, whereas b3 ids could be a 128 bit or lower hex number.  Some tracing libraries convert between the two. i.e. convert a 64 bit long to a 64 bit hex string and vice versa, but if the envoy ids are random in both cases then one wouldn't translate to the other.  [Here's an example in Kamon](https://github.com/kamon-io/Kamon/blob/d7b89032adfcd432c4c282822f1f2fc8d4d6b59d/reporters/kamon-datadog/src/main/scala/kamon/datadog/DatadogSpanReporter.scala#L41) where hex trace IDs are converted to base 10 when reporting to DataDog.  

For example, I'm observing the following HTTP headers that are associated to a trace in my environment.

```
x-b3-traceid: 16f5175124b5191af5273fdf79d7bba9, 
x-datadog-trace-id: 8032554674212085418
```

In this case the b3 trace id is 128 bit.  In base 10 it is `30515601561871624100066069095397178281`.  If I take the lower 64 bits to get an ID I can use with DataDog I get `17665158292438498217`.  Neither of these match the `8032554674212085418` integer that's in the datadog header.

My C++ isn't the strongest so I couldn't validate this in the code. I was hoping someone else could confirm if this behaviour is correct and/or desirable.

**Comment by ibrahimalihc** [comment]
They are different. DataDog's APM supports both B3 and DataDog headers: https://docs.datadoghq.com/tracing/setup_overview/setup/go/?tab=containers#b3-headers-extraction-and-injection. But it seems that Envoy only recognizes DataDog headers: https://github.com/envoyproxy/envoy/blob/10d783d8985a21b9fabe28461e143532be6119d4/source/extensions/tracers/datadog/datadog_tracer_impl.cc#L38-L41

If Envoy's DataDog tracer supported B3 as well, that would greatly help with interoperability.
