### ISSUE TITLE
Does this situation call for SDS, CDS, or RDS Discovery?

### ISSUE THREAD

**Issue by tlhunter** [envoyproxy/envoy#1912]
I have an existing discovery service which provides a giant array of information about service instances. Here's a truncated example of this list:

```json
[
  {
    "announcementId": "3dd65646-177f-42d5-8d5a-ed87af935171",
    "serviceType": "emailer",
    "serviceUri": "http://host1:31995"
  }, {
    "announcementId": "e66a760f-f83c-4895-9a30-0933308ce345",
    "serviceType": "emailer",
    "serviceUri": "http://host2:31168"
  }, {
    "announcementId": "32c04b41-ade0-4eff-a746-93cda7355929",
    "serviceType": "web",
    "serviceUri": "http://host1:31570"
  }
]
```

I'm currently building a "discovery translation" service to transform my existing data to the format required by Envoy, exposing data via the CDS `/v1/clusters` or SDS `/v1/registration` or RDS `/v1/routes` endpoints.

My goal is to create a Docker instance with Envoy and an App running, and allow the app to make outbound requests to localhost:80 and have those requests routed via Envoy. I've already got incoming requests routing through Envoy to the app and Envoy is able to communicate with my external discovery translation.

I'm having some difficulty setting up an `envoy.json` file to describe these needs. In particular I'm not sure if I should be using SDS, CDS, RDS, or some combination.

Here's an example of my current configuration, though none of the discovery features are currently working:

```js
{
  "listeners": [
    {
      "address": "tcp://0.0.0.0:6000", // Incoming Requests
      "filters": [{
        "name": "http_connection_manager",
        "config": {
          "codec_type": "auto",
          "stat_prefix": "ingress_http",
          "route_config": {
            "virtual_hosts": [{
              "name": "local_service",
              "domains": ["*"],
              "routes": [{
                "timeout_ms": 0,
                "prefix": "/",
                "host_rewrite": "tcp://127.0.0.1:3000", // Port App listens on
                "cluster": "application_cluster"
              }]
            }]
          },
          "filters": [{
            "name": "router",
            "config": {}
          }]
        }
      }]
    },

    {
      "address": "tcp://127.0.0.1:80",
      "filters": [{
        "name": "http_connection_manager",
        "config": {
          "codec_type": "auto",
          "stat_prefix": "egress_http",
          "rds": {
            "cluster": "discovery_cluster",
            "route_config_name": "such_a_cool_name",
            "refresh_delay_ms": 10000
          },
          "filters": [{
            "name": "router",
            "config": {}
          }]
        }
      }]
    }
  ],

  "admin": {
    "access_log_path": "/tmp/admin_access.log",
    "address": "tcp://0.0.0.0:8080"
  },

  "cluster_manager": {
    /*
    "cds": {
      "refresh_delay_ms": 10000,
      "cluster": {
        "name": "cds_cluster",
        "type": "static",
        "connect_timeout_ms": 250,
        "lb_type": "round_robin",
        "hosts": [{
          "url": "tcp://10.10.21.121:3090" // discovery translator
        }]
      }
    },
    */
    "clusters": [
      {
        "name": "application_cluster",
        "connect_timeout_ms": 250,
        "type": "logical_dns",
        "lb_type": "round_robin",
        "hosts": [{
          "url": "tcp://127.0.0.1:3000", // Port App listens on
        }]
      }
    ],
    "sds": {
      "refresh_delay_ms": 10000,
      "cluster": {
        "name": "discovery_cluster",
        "type": "static",
        "connect_timeout_ms": 250,
        "lb_type": "round_robin",
        "hosts": [{
          "url": "tcp://10.10.21.121:3090" // discovery translator
        }]
      }
    }
  }
}
```

**Comment by mattklein123** [comment]
@tlhunter there is really no "right" answer to this question. If I understand your setup, it sounds like you have a single application cluster and a potentially very simple route table, so it sounds like potentially you only need SDS. Does this help? https://envoyproxy.github.io/envoy/intro/arch_overview/dynamic_configuration.html. If not, what would make it better?

**Comment by tlhunter** [comment]
Thanks for linking me to that document. I thought I'd read all the docs but somehow missed that page.

In our case we have dozens of types of services ("clusters", in Envoy terminology, I believe) and hundreds of service instances at any point in time. Typically an individual service would know which services it needs to find ahead of time. However we'd like to build a generic envoy configuration, one which could be used by many different services, providing it in a Docker image which application owners would inherit via `FROM`. We'd like to keep any occurrences of service "names" out of the config and be able to find them all dynamically in order to support everyone needs.

After reading that document I believe we'll have to use SDS and CDS together. Since we won't be doing any rolling deployments or canary deploys we can skip RDS. Please let me know if this sounds wrong!

The "Dynamic configuration" document does help but perhaps it would benefit from some diagrams or example implementations. Maybe link to it from the "Service discovery" page to assist with page discovery.

**Comment by mattklein123** [comment]
> After reading that document I believe we'll have to use SDS and CDS together. Since we won't be doing any rolling deployments or canary deploys we can skip RDS. Please let me know if this sounds wrong!

You will likely need to use RDS unless you do routing via header. Otherwise you will need to have dynamic route tables for the clusters.

**Comment by tlhunter** [comment]
I think what we'll do is have service make a request to localhost:80 where Envoy will be listening and have the application override the `Host` header.
