### ISSUE TITLE
GRPC client to REST server / Converting protobuf to json

### ISSUE THREAD

**Issue by maxlein** [envoyproxy/envoy#19120]
*GRPC client to REST server*: *I want envoy to bridge a grpc client to REST server*

*Description*:
We have the requirements of having a REST server and a REST client as part of an interface to an external party.  
To not have a dependency on some not so well-done REST c++ libraries we would like to use grpc, as we use it already internally.  

So I got the REST server working with the GrpcJsonTranscoder and it's all fine.  

For the REST client I am using the grpc_http1_reverse_bridge.  
But the problem here is, that the protobuf data is not transcoded to json.
Is there any way of converting the protobuf to json?

**Comment by ggreenway** [comment]
cc @lizan

**Comment by lizan** [comment]
There's no easy way to do this, you might want to implement another Envoy filter to achieve that.

**Comment by maxlein** [comment]
Thx for the info.  
Is there any info/help on that apart from the http filter example?  
Is the GrpcJsonTranscoder filter open source? Because I couldn't find it.  
That way I could get an idea on how complex this will be.

**Comment by asayah** [comment]
@maxlein  check this https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest_advanced/

**Comment by maxlein** [comment]
Well, that's the wrong direction.
This grpc transcoder we already have.

Question is about a grpc client calling a REST Server which doesn't know protbuf.

**Comment by alwaysastudent** [comment]
> Well, that's the wrong direction. This grpc transcoder we already have.
> 
> Question is about a grpc client calling a REST Server which doesn't know protbuf.

What did you folks end up doing?

**Comment by maxlein** [comment]
> > Well, that's the wrong direction. This grpc transcoder we already have.
> > Question is about a grpc client calling a REST Server which doesn't know protbuf.
> 
> What did you folks end up doing?

we ended up using a json REST client ;)
