### ISSUE TITLE
Support changing the host header in ext_proc

### ISSUE THREAD

**Issue by srinandan** [envoyproxy/envoy#19129]
*Title*: *Support changing the host header in ext_proc*

*Description*:
I was attempting dynamic routing via ext_proc. To do this, I believe I have to set the Host header. However, according to [here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_proc/mutation_utils.cc#L125), this header cannot be modified via ext_proc. 

The host header is modifiable in the ext_authz filter. 

Envoy Version: `envoy  version: 96701cb24611b0f3aac1cc0dd8bf8589fbdf8e9e/1.20.0/Clean/RELEASE/BoringSSL`

NOTE: I couldn't find anything in the documentation that talks about restrictions to modifying such headers. It will be good to add this restriction to the documentation.

**Comment by gbrail** [comment]
We had some discussion of this a long while back in https://github.com/envoyproxy/envoy/issues/14789
