### ISSUE TITLE
All PRs with dependency updates fail in CI

### ISSUE THREAD

**Issue by rojkov** [envoyproxy/envoy#19136]
*Title*: *All PRs with dependency updates fail in CI*

*Examples*:
#19125, #19124, #19122

*Logs*:
```
github_release:  GitHubRelease(organization='census-instrumentation', project='opencensus-proto', version='v0.3.0', tagged=True)
Traceback (most recent call last):
  File "/source/tools/dependency/release_dates.py", line 288, in <module>
    verify_and_print_release_dates(
  File "/source/tools/dependency/release_dates.py", line 258, in verify_and_print_release_dates
    release_date = get_tagged_release_date(repo, metadata['version'], github_release)
  File "/source/tools/dependency/release_dates.py", line 215, in get_tagged_release_date
    release = repo.get_release(github_release.version)
  File "/source/build_tools/release_dates/venv/lib/python3.8/site-packages/github/Repository.py", line 3053, in get_release
    headers, data = self._requester.requestJsonAndCheck(
  File "/source/build_tools/release_dates/venv/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/source/build_tools/release_dates/venv/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"}
```

**Comment by rojkov** [comment]
cc @phlax @kfaseela

**Comment by phlax** [comment]
cc @ashankar-fiserv

**Comment by kfaseela** [comment]
https://github.com/envoyproxy/envoy/pull/19111 should fix this. Waiting for review after incorporating comments.

**Comment by phlax** [comment]
i think it may already be fixed, or was in some way transient

neither pre or post submit queues trigger this and running the offending script against current HEAD doesnt fail

i retested one of the above PRs and it passed, ill kick the others now

it would be nice to know what caused this - not sure if the fact that it always fails on the opencensus dep is relevant. It may be just that a release was temporarily deleted, and our error handling is not great.

As the script is already a bit flaky, its hard to tell immediately if the change that i made yesterday has caused it, but mho is that its unrelated

lets keep this open for now - we can close after a day or two if the issue has gone away

**Comment by phlax** [comment]
another failing PR check:

https://github.com/envoyproxy/envoy/pull/19097/checks?check_run_id=4359014533

https://dev.azure.com/cncf/envoy/_build/results?buildId=95492&view=logs&jobId=1c04237c-5f52-5959-5f83-5522b3556331&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467

**Comment by rojkov** [comment]
It may well be a transient issue. The failing repo is unusual in that its [releases page](https://github.com/census-instrumentation/opencensus-proto/releases) doesn't list the v0.3.0 release. But the tag is there.

I've just re-run #19082 a couple of times with no success.

**Comment by phlax** [comment]
yep - it doesnt appear to have fixed #19097 either 

ill check out one of these branches and try to repro locally...

**Comment by kfaseela** [comment]
@phlax could you please check my review mentioned above, I was also hitting this issue intermittently, and hence made sure that get_release call is guarded properly in the PR what I was working on

**Comment by phlax** [comment]
> made sure that get_release call is guarded properly in the PR what I was working on

ha, k, thanks, will do

i have managed to repro locally

**Comment by phlax** [comment]
cool, thanks @kfaseela it works perfectly
