### ISSUE TITLE
Proposal: Istio Envoy mTLS Private Key Protection with HSM

### ISSUE THREAD

**Issue by giantcroc** [envoyproxy/envoy#19134]
## Istio Envoy mTLS Private Key Protection with HSM
Envoy uses boringssl for tls communication, and the enabling of mTLS can also protect the connection between services from being attacked and tampered, but there’s still vulnerabilities within the private key management in Envoy, as the private key is exposed as clear text data inside the memory. The proposal is to provide a selectable choice to enable the PKCS#11 standard inside Envoy together with Hardware Security Module (HSM) to serve better security for key management within Envoy. 
#### Current workflow
Currently, the istio-proxy container runs the Envoy Proxy either in router mode, for ingress gateway or in sidecar mode when running as a proxy alongside the application. In sidecar mode the init container sets up all the required iptable rules and the control plane builds all the necessary listeners, routes, cluster and endpoint configurations and pushes them to the proxies.
And the use of mTLS protocol can provide a more secure and reliable connection. The flow diagram shows the current communication mode between sidecars and where the certificate will be used in this mesh.
![44444](https://user-images.githubusercontent.com/20723282/144005825-12c00022-44c3-485e-9506-37cc3edd56e2.png)
In the current workflow, the certificate which is used for mTLS connection between sidecars was generated by Istio-Agent and issued to the sidecar, and the TLS private key is exposed as clear text data inside the memory of the pod. Although Istio's authentication policy can avoid most malicious third-party attacks, once a pod is compromised, the communication packages between the sidecar and other sidecars might be tampered with, which may lead to security vulnerabilities in the cluster.
![33333](https://user-images.githubusercontent.com/20723282/144005876-4328f11c-7a35-4e23-b17b-b58653d1c49f.png)
In order to provide a way where the cluster can benefit from a pluggable third-party HSM backend and the envoy proxy can be extended to perform as a private key provider, we came up with this proposal. This design works for most use cases and provides an option that customers can choose to enable this option according to their needs. The workflow is shown in the diagram below.

Our changes are mainly in the process of generating CSR and key pair in Istio-Agent. The key point is to enable a selectable choice that the CSR and key pair can be generated in Envoy and protected by HSM backend. We introduced a global variable to enable the usage of external private key providers and in order to give customers a more flexible choice to adapt to all situations, if the external provider does not exist, the certificate and key pair will be generated by default flow.
### Design
This proposal tends to increase the security level of cryptographic operations and key management inside Envoy. It involves modifying Istio-Agent and Envoy to provide an advanced-level security to save the secrets (Istio-Agent mTLS private key) securely inside HSM (SoftHSM as sample) based on the PKCS#11 standard. 
#### Control plane
The workflow of control plane is shown in the diagram below.
![22222](https://user-images.githubusercontent.com/20723282/144005905-81da3e70-5d90-40c9-ab51-b526180b0621.png)
The main changes of workflow are shown by the blue arrows. 
**1.2 1.3** The SDS request no longer requires Istio-Agent to generate keypair and CSR. And the SDS response sent to envoy does not directly contain the private key, but config to generate HSM private key provider. A kind of protobuf definition of SDS response is shown below.
```
message Config {
   string hsm_library = 1;
   string key_label = 2;
   string usr_pin = 3;
   string so_pin = 4;
   string token_label = 5;
   string rsa_key_size = 6;
   // csr_config is a string composed of various configuration items
   // provided to envoy, which are used to generate CSR by openssl
   string csr_config = 7;
}
```
**1.4 1.5** Then HSM private key provider will init HSM context once, and generate rsa keypair in HSM and CSR by openssl cmdline with PKCS#11 engine. 
**1.6** Since envoy’s SDS does not support CSR type resources, we use gRPC instead. CSR will be sent to Istio-Agent by gRPC request. 
**1.13** After Istio-Agent receives the signed certificate, it will be sent to envoy through gRPC response and saved in Boringssl config.
#### Data plane
The workflow of data plane is shown in the diagram below.
![11111](https://user-images.githubusercontent.com/20723282/144005632-e6b4eed9-a93f-46ad-bb8d-67deebd65c84.png)
**2.3** When Boringssl perform TLS handshake in HTTPS connection, it will call signing/decryption function in HSM Private Key Provider. 
**2.4 2.5 2.6** And HSM will execute signing or decryption and return the result to HSM Private Key Provider. 
**2.7** Finally HSM Private Key Provider will return the result to Boringssl

#### Key generation
Two new approaches are provided for private key generation corresponding to the current. 
A.    Envoy will by default try to load the pre-conducted private key and save it into SoftHSM. 
B.    While there's no pre-conducted key ready, Istio-Agent will deliver all configuration and call Envoy to generation the CSR, and Envoy can call the PKCS#11 APIs implemented inside the HSM(SoftHSM as sample) to generate the signing key.
For both cases, the output returned is a key handle instead of the plain-text key.
 
#### Key retrieval
While following the PKCS#11 standard, id and label are used as the identifiers to fetch the private key. Either of them is usable to fetch the identical key. And the key that was retrieved is a handle instead of the plain-text data block. 

We also raise a proposal in istio community: https://github.com/istio/istio/issues/36296.
@lizan @ggreenway @asraa

**Comment by mattklein123** [comment]
Can you please close this and open a new issue with just the Envoy side change(s) you are requesting? Thank you!

**Comment by ggreenway** [comment]
It's helpful to understand the context of what you're trying to do in istio, but I agree that you'll need to make a concrete proposal of what you plan to change in Envoy.

Also, this isn't the first time HSM support has come up. See #1106.

**Comment by giantcroc** [comment]
> Can you please close this and open a new issue with just the Envoy side change(s) you are requesting? Thank you!

OK, I will modify the proposal later. Thanks!

**Comment by giantcroc** [comment]
> It's helpful to understand the context of what you're trying to do in istio, but I agree that you'll need to make a concrete proposal of what you plan to change in Envoy.
> 
> Also, this isn't the first time HSM support has come up. See #1106.

OK, I will modify the Istio part of this proposal and add more details about Envoy part. Thanks!

**Comment by giantcroc** [comment]
Hi! I create a new issue to show more details about our proposal. 
https://github.com/envoyproxy/envoy/issues/19217
Looking forward to your comments and suggestions. Thanks!
@lizan @ggreenway @mattklein123 @asraa
