### ISSUE TITLE
Support callbacks on write completion in the async gRPC client

### ISSUE THREAD

**Issue by gbrail** [envoyproxy/envoy#19148]
*Title*: Support callbacks on write completion in the async gRPC client

*Description*: To complete the ext_proc filter, I need to implement "async mode." In this mode, the filter doesn't wait for a response message from the external processing server -- it sends messages on the gRPC stream for each phase of the request / response, and the server is expected to process them, but can't send back a response. (This feature was thought to be useful for systems that want to monitor the flow of traffic in a more flexible way than logging allows today.)

My first attempt to implement this is failing because keeping track of the state of the gRPCs is complex. ext_proc is now reusing the gRPC stream, which means that we can't "close" it if there are messages in flight to the remote server -- and since we're just putting messages on a stream asynchronously, then we have no way to know that.

I would like to enhance the "RawAsyncStream" and its subclasses by making the "sendMessageRaw" method either call a callback when the write completes, or invoke a method on the RawAsyncStreamCallbacks interface. By doing this, I solve two problems:

First, ext_proc won't try to close or reuse a stream until all the messages to the remote server have been dispatched. This is necessary so that it will simply work.

Second, I'm worried about flow control for this feature, since in theory we can be processing HTTP requests faster than we can send messages to the external processing server. If we wait for each message to be actually written before we send them, however, then I think that we can introduce a little bit of backpressure which should help with this situation.

Can someone familiar with the gRPC implementation let me know if this makes any sense, and possibly point me to where such a thing might be done? Thanks!

**Comment by gbrail** [comment]
@ajaymandvekar This is something we'd have to think about in order to complete async mode support.

**Comment by chaoqin-li1123** [comment]
IIUC, calling [closeStream()](https://github.com/envoyproxy/envoy/blob/5424c7e357e6841213267651c8fa5bd2a7669813/source/common/grpc/google_async_client_impl.cc#L230) actually don't delete the raw grpc stream,  neither does it cancel any queued or inflight write request. If you don't want to wait for a ext_proc response, calling closeStream() after all ext_proc requests have been sent and always returning Continue filter status may be sufficient.(correct me if I miss something)

**Comment by gbrail** [comment]
Right -- as I recall my problem was with resetStream(), which I had to
start calling because we switched to using a pooled gRPC client. But I have
some other things I want to experiment with to improve performance in that
area, so let me see what happens first.
