### ISSUE TITLE
upstream_starttls_integration_test flaky

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#19147]
[ RUN      ] StartTlsIntegrationTestSuite/StartTlsIntegrationTest.SwitchToTlsFromClient/0
test/extensions/transport_sockets/starttls/upstream_starttls_integration_test.cc:251: Failure
Value of: test_server_->server().listenerManager().numConnections()
Expected: is equal to 1
  Actual: 0 (of type unsigned long)
Stack trace:
  0x8cfd28: Envoy::StartTlsIntegrationTest_SwitchToTlsFromClient_Test::TestBody()
  0x1966ed8: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1966e05: testing::Test::Run()
  0x1967c20: testing::TestInfo::Run()
... Google Test internal frames ...

*Repro steps*:
bazel test test/extensions/transport_sockets/starttls:upstream_starttls_integration_test --runs_per_test=200

**Comment by ankatare** [comment]
@danzh2010 in my local env test results is PASSED. 
See below
bazel test test/extensions/transport_sockets/starttls:upstream_starttls_integration_test --runs_per_test=200

```
:~/new_folder/envoy$ bazel test test/extensions/transport_sockets/starttls:upstream_starttls_integration_test --runs_per_test=200 --cache_test_results=no
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analyzed target //test/extensions/transport_sockets/starttls:upstream_starttls_integration_test (0 packages loaded, 19109 targets configured).
INFO: Found 1 test target...
Target //test/extensions/transport_sockets/starttls:upstream_starttls_integration_test up-to-date:
  bazel-bin/test/extensions/transport_sockets/starttls/upstream_starttls_integration_test
INFO: Elapsed time: 65.275s, Critical Path: 50.19s
INFO: 203 processes: 1 internal, 202 linux-sandbox.
INFO: Build completed successfully, 203 total actions
//test/extensions/transport_sockets/starttls:upstream_starttls_integration_test PASSED in 0.6s
  Stats over 200 runs: max = 0.6s, min = 0.5s, avg = 0.6s, dev = 0.0s

```

**Comment by ankatare** [comment]
JFYI: i run in latest dev code

**Comment by danzh2010** [comment]
Mark as fix for now.
