### ISSUE TITLE
TLS certificate validation: how to asynchronously fetch CRL using CRL DP present in cert

### ISSUE THREAD

**Issue by vikaskumar11** [envoyproxy/envoy#19142]
*Title*: *TLS certificate validation: how to asynchronously fetch CRL using CRL DP present in cert*

*Description*:
> I've a custom cert validator. In our environment, leaf cert doesn't have CRL support because of management challenges with large volume of leaf cert. Instead, next level cert has CRL support. So, I want to asynchronously fetch that CRL and do validation. Apparently envoy http async client is available in upstream context.

**Comment by vikaskumar11** [comment]
@ggreenway Can you please add label "help wanted".

**Comment by ggreenway** [comment]
cc @htuch. This is related to the discussion of libcurl in the community meeting this morning. Is the recommended approach for the extension to create a cluster for each CRL host it needs to connect to, and then use AsyncHttpClient on that cluster? I've never looked at how to do this; can extensions dynamically create clusters that aren't in the config?

**Comment by htuch** [comment]
I think this is a place we could make use of the dynamic forward cluster, but I'm not aware of any place in Envoy that does this beside the data forwarding plane. If someone can establish this pattern, I think it will be useful in many places.

**Comment by ggreenway** [comment]
It may make more sense to make a simpler API, that doesn't do any connection pooling, that just does an http request to a given url asynchronously. It could make a cluster under the hood if needed as an implementation detail.

**Comment by htuch** [comment]
Yeah, we could have an implicit "Envoy internal service dynamic forward proxy cluster" for this.
