### ISSUE TITLE
Customize Envoy access logging command operator REQ(X?Y):Z

### ISSUE THREAD

**Issue by Edimo24** [envoyproxy/envoy#19157]
I am trying to customize some of envoy operators. I would like to add some tags to different operators in envoy source code like %REQ(X?Y):Z% and %RESP(X?Y):Z%. I need something like %**[tag]**REQ(X?Y):Z**[/tag]**%. 

Normally I would do the changes in header_formater.cc but I cannot find these two command operators there, any idea where to edit the Envoy code in order to have the tags?

**Comment by ggreenway** [comment]
I think what you're looking for is here: https://github.com/envoyproxy/envoy/blob/main/source/common/formatter/substitution_formatter.cc#L368
