### ISSUE TITLE
http: directly response 1xx will trigger the assert failure

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#19159]
I'm just using envoy to do some test, expect envoy return http 100 directly, with envoy config:

```
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  path: "/"
                direct_response:
                  status: 100
          http_filters:
          - name: envoy.filters.http.router
```

Then it got failed with assertion.

```
[2021-12-01 09:20:08.167][2902603][debug][http] [source/common/http/filter_manager.cc:834] [C0][S13764954477484614782] request end stream
[2021-12-01 09:20:08.167][2902603][debug][http] [source/common/http/filter_manager.cc:946] [C0][S13764954477484614782] Sending local reply with details direct_response
[2021-12-01 09:20:08.167][2902603][critical][assert] [source/common/http/filter_manager.cc:1078] assert failure: !CodeUtility::is1xx(Utility::getResponseStatus(headers)) || Utility::getResponseStatus(headers) == enumToInt(Http::Code::SwitchingProtocols).
```

not sure it is useful usecase in the real world, but seems it shouldn't be failed at assertion.

**Comment by soulxu** [comment]
Working on a fix, it should be able fixed here by checking the 1xx response and invoking `encode1xxHeaders` instead of `encodeHeaders`

https://github.com/envoyproxy/envoy/blob/3baae860b020d0014938f061c2fa0b215ecbc1df/source/common/http/filter_manager.cc#L975

cc @alyssawilk

**Comment by alyssawilk** [comment]
hm, I'm actually inclined to think that configuring a direct response with rc 1xx is a control plane bug and should be validated against. 100 headers are informational headers and I believe they need to be followed with non-informational headers for a complete response.
cc @htuch @wrowe for thoughts

**Comment by htuch** [comment]
Yeah, I agree, it doesn't seem to have a valid use case that I can think of. It would be fine with me to add a PGV validation here, since I don't see any reasonable use of the API with the more relaxed current state.

**Comment by soulxu** [comment]
got it, thanks for the feedback
