### ISSUE TITLE
Envoy Install doc issue

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#19160]
*Title*: *doc to install envoy in ubuntu is not correct for v1.18.3*

*Description*: see url https://www.envoyproxy.io/docs/envoy/v1.18.3/start/install#install-envoy-on-ubuntu-linux
>Describe the issue. command "**`sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable""`**

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ankatare** [comment]
issue is "E: Failed to fetch https://dl.bintray.com/tetrate/getenvoy-deb/dists/bionic/InRelease  403  Forbidden [IP: 52.36.71.255 443]"

**Comment by phlax** [comment]
hmm - we are probably going to need to backport some fixes to the docs

im close to having deb publishing ready (#17979) but its looking more like the new year before that will be ready, rpm support should follow

we will then need to figure out how to publish for currently supported historic versions

im wondering if we should just backport what is in the current docs first as these links no longer work
