### ISSUE TITLE
WASM：onRequestBody will not be called when no body in a http request

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#19170]
*Title*: *WASM：onRequestBody will not be called when no body in a http request*

*Description*:
If I want to set body in onRequestBody api when  no body in a http request, wasm seems do not work, it will skip the onRequestBody api since there is no body in the http request.

**Comment by ggreenway** [comment]
cc @envoyproxy/wasm-dev

**Comment by StarryVae** [comment]
cc @mathetake

**Comment by mathetake** [comment]
cc @PiotrSikora as I won't be able to work on this for next few months
