### ISSUE TITLE
[gRPC-JSON transcoder] Support configurable request buffer limit

### ISSUE THREAD

**Issue by hq6** [envoyproxy/envoy#19175]
*Title*: *Support configurable request buffer limit in gRPC-JSON transcoder*

*Description*:
Today, as far as I can tell, the gRPC-JSON transcoder can handle a maximum request size of 64 KB, due to [flow control](https://github.com/envoyproxy/envoy/blob/main/source/docs/flow_control.md) limitations limiting the amount of data a filter can buffer.  The requested feature is to add a configurable buffer limit, similar to the one in the [buffer filter](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/buffer/buffer_filter.cc#L63).
This will allow the filter to support larger requests when necessary.

**Comment by qiwzhang** [comment]
From JSON to proto message transcoding, I don't think the filter needs to buffer up the whole request body,  it can do "field-by-field" while the data is coming in.  It may need to buffer up a whole field.  So the current limit may limit the field length. 

My only concern with the bigger limits is:  will it break the whole flow-control if this filter buffer up more data than flow-control allowed. 

@alyssawilk @nareddyt ?

**Comment by hq6** [comment]
I think for my use case, there are particular fields that might be larger than 64 KB which is why I'm requesting this feature.

If the flow control allowed limit is available via some API, then the filter could do a minimum of this limit (if specified) and the flow control limit, right?

**Comment by nareddyt** [comment]
>  the gRPC-JSON transcoder can handle a maximum request size of 64 KB, due to flow control limitations limiting the amount of data a filter can buffer

Flow control should not affect the buffer limit in the gRPC JSON transcoder. There are two separate buffer limits the transcoder checks:
1) for requests, it gets the limit from the `per_connection_buffer_limit_bytes` field in the [Listener config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto). Default is 1 MiB, but you can change your listener config to have any value.
2) for responses, it gets the limit from the `per_connection_buffer_limit_bytes` field in each [cluster's config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto)

Implementation of this is located here: https://github.com/envoyproxy/envoy/blob/70a5f295da789610b9d078015f43e39c6a76d4b6/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L892-L926

We have multiple tests that overwrite the limits to test under/over limit code paths: https://github.com/envoyproxy/envoy/blob/70a5f295da789610b9d078015f43e39c6a76d4b6/test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc#L1143

You can follow the code in this helper function. The tests above just set the buffer limits in listener and cluster API, which you can do as an Envoy user. https://github.com/envoyproxy/envoy/blob/70a5f295da789610b9d078015f43e39c6a76d4b6/test/config/utility.cc#L925

**Comment by hq6** [comment]
Thanks for the pointers! 
We'll try the listener configurations and validate whether those will allow us to overcome the limits.
