### ISSUE TITLE
What is the Envoy retry behavior when we don't set retry_policy for upstream?

### ISSUE THREAD

**Issue by Andy-Gong** [envoyproxy/envoy#19183]
Hi, team, 
Currently, when sending the request to upstream, one of the upstream nodes returns some 503 responses and route_config as below which isn't set any retry_policy. For this use case, I want to ask 2 questions.

1. will the request be retried?
2. If we add the `retry_policy`, will the request be sent to another upstream node or does it just re-send the request to the same upstream? 

```
{
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "xxx",
      "virtual_hosts": [
       {
        "name": "xxx",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "xxx"
          }
         }
        ]
       }
      ]
     }
    }
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
``

**Comment by alyssawilk** [comment]
If there's no retry policy, Envoy will not retry.  If there is, the host for the retry will be selected based on the load balancing configured (least loaded, round robin etc)
