### ISSUE TITLE
Internal address metadata transfer from upstream

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#19189]
We would like to expose some metadata through the user space socket (internal listener). The metadata can originate from several sources:
- endpoint metadata;
- upstream cluster metadata;
- stream info remote address;
- downstream and upstream stream info metadata and filter state;

The right place to write appears to be the connection stream info metadata and filter state. Filter state is preferable since it supports nesting (e.g. HCM on internal listener can access it), unless dynamic metadata starts supporting nesting as well.

The point of declaration would ideally be the point of use, which is the internal listener. That helps with the duplication across upstream clusters. Listeners in general are mutually trusted.

**Comment by kyessenov** [comment]
To add some context, the internal listener is likely to utilize HTTP dynamic forward proxy or TCP original destination cluster for forwarding. Therefore, as a _minimum requirement_, the metadata passed from the original listener to the internal listener must be able to configure:
* host header override (e.g. obtained from `CONNECT` method);
* local address override in L4 stream info (to drive original destination cluster);
* (optional) true destination descriptor in case the peer is also a tunnel endpoint (e.g. we can set an HTTP header `original-dst` in `CONNECT` so that the terminating listener can forward to the endpoint in `original-dst`).

The above could be done with dynamic metadata as long as both dynamic forward proxy and original destination cluster can use the dynamic metadata instead of direct HTTP/TCP stream information.

A secondary requirement is to be able to share a filter state between the original listener and the internal listener. The usage is to enable continuation of evaluation of policy between listeners, e.g. to pass a concrete state between filters in the two listeners.

**Comment by wrowe** [comment]
Tagging as enhancement, let me know if you wanted other labels

**Comment by kyessenov** [comment]
#19274
