### ISSUE TITLE
Routing protobuf payloads to gRPC services

### ISSUE THREAD

**Issue by hstefan** [envoyproxy/envoy#19198]
*Title*: Routing protobuf payloads to gRPC services

*Description*:

At Spotify we've been looking into allowing clients to call gRPC backend services by implementing something similar to [gRPC Fallback](https://googleapis.github.io/HowToRPC.html#making-rpc-api-requests). This would allow us to support unary calls from platforms where gRPC isn't available or for some reason suboptimal from the clients perspective, while still retaining type safety from Protobuf and its serialization semantics.

Initially we investigated using `grpc_http1_bridge_filter` for bridging HTTP 1.1 clients to native gRPC backends, but that would require every client application to prepend the gRPC frame as specified by the wire format, which isn't ideal organizationally. Additionally, the bridge does not the allow the usage `google.api.http` for mapping paths to RPC handlers (a functionality currently supported in the `grpc_json_transcoder` filter).

Our ideal scenario would be bypassing the transcoding semantics in `grpc_json_transcoder`  whenever `Content-Type` is set to `application/x-protobuf` or similar, and instead simply forwarding the request body (a protobuf message) to the designated gRPC method (based on path). Alternatively, the `grpc_http1_bridge_filter` could be extended to perform the gRPC framing internally depending on Content-Type, but that approach wouldn't allow us to map paths and verbs with `google.api.http` annotations.

This is something that would allow us to leverage Envoy more heavily in our backend systems, and we'd be happy do discuss contributing a patch if this feature request is sound from the project's perspective.

**Comment by nezdolik** [comment]
@mattklein123 @alyssawilk @euroelessar any opinions on this?

**Comment by alyssawilk** [comment]
For the goal of skipping the transcoder filter based on content type, I thought snow did work here (https://github.com/envoyproxy/envoy/issues/12968) based on a similar desire to turn filters on and off by header value (https://github.com/envoyproxy/envoy/pull/14722)  but I didn't follow along the whole chain.  @snowp can you advise?

**Comment by hstefan** [comment]
@alyssawilk I'm not sure I understand how that would help in our case, I think that PR tries to achieve something else if I understand correctly.

What we're trying to do is allowing HTTP 1.1 clients to call gRPC by sending the request protobuf as the payload as an alternative to JSON. For some of our applications serializing protobufs is not an issue, and their pain point is using gRPC libraries in their platforms, so something we can still leverage protobuf in these cases.

As far as I understand we can use the http1_bridge to solve one part of the problem, but each client would have to send a payload following the gRPC wiring format (0x0 + content-len + protobuf payload). What we'd like to do is moving the gRPC framing to the proxy layer, so that the client would only send the protobuf payload instead.

The JSON transcoding filter may also be of help in case this "bypassing" of the transcoder could also respect the same routes defined with `google.api.http` options in the protoset descriptor. If not that could be confusing to clients, as the path and verb mapping would only apply to the JSON-payloads but not protobuf.

Does that make sense? Please let me know if I can help clarifying anything else about the idea.

**Comment by snowp** [comment]
Re skipping filter execution we can do that with the matching API + SkipAction: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api.html?highlight=extensionwithmatcher#filter-integration

re http1_bridge I don't see any problem with adding support to the http1_bridge filter to inject the gRPC frame (the same way the reverse bridge manages it) if someone is willing to do that work

**Comment by hstefan** [comment]
@snowp glad to hear injecting the framing sounds reasonable to you. 

re SkipAction: wouldn't that also bypass the `google.api.http` annotations? Consider this example:

```protobuf
service ConcatService {
    rpc Concat(ConcatRequest) returns (ConcatResponse) {
        option (google.api.http) = { get: "/v1/concat" };
    }
}
```

The json transcoder would map `/v1/concat` to the `Concat` RPC, but I believe skipping the filter means the URL wouldn't be mapped and the verb and path would be different depending on content-type (if that's how we determine the payload type). Is there any way to respect this mapping for protobuf as well? If not, would it make sense to add something for that?

**Comment by euroelessar** [comment]
It doesn't feel plausible to implement bypass-transcoding logic in json-grpc-transcoder as many of its features rely on a full ownership/control over the generated protobuf message.
For example, one can specify url as `/v1/{a.b.message_id}`, which assumes that `a.b.message_id` field is unconditionally set to the corresponding field, which is non-trivial to ensure if an original message body is supplied by the caller.

Arguably, I'd recommend to stick to gRPC call notation as close as possible, which is what http1_bridge does for you. It is understandable that managing frames can be a hustle if your language of choice does not have a proper grpc library support, in which case it's reasonable to add a logic to generate frame size for you for unary-unary calls from the content length.

Are there particular business/technological reasons which would require/encourage you to use non-grpc call notation?

**Comment by hstefan** [comment]
That makes a lot of sense @euroelessar. I hadn't considered dynamic routes and was actually only considering static mapping. It shouldn't be a big problem to stick to gRPC notation, but what I was thinking about was the case where a grpc service is exposed both through JSON transcoding and the "protobuf over http1" approach I was proposing. It may be a bit confusing that the same RPC requires different paths depending on what serialization format you're invoking from the client, but it does sound unfeasible considering the example you mentioned (and presumably other generation issues).

I'll discuss this with my team next week and see when we can get started writing a patch for the `http1_bridge `, as I'm happy to hear it doesn't sound too crazy to introduce it.
