### ISSUE TITLE
Add a string to a command operator - Envoy Access logging

### ISSUE THREAD

**Issue by Edimo24** [envoyproxy/envoy#19218]
Hello,

I am trying to add a string to a command operator but as far as I can understand this command operator does not return a string. Is there any way how to convert it to string?

**I am trying to do the changes in substitution_formatter.cc for the DOWNSTREAM_LOCAL_ADDRESS command operator.**
The idea was to convert the command operator to a string and then concatenate with another string (see below).

I tried to use asSring() but apparently it did not work (How can I check if asString is supported for this command operator).

  } else if (field_name == "DOWNSTREAM_LOCAL_ADDRESS") {
    field_extractor_ =
        StreamInfoAddressFieldExtractor::withPort([](const StreamInfo::StreamInfo& stream_info) {
          std::string localaddress;
          localaddress = stream_info.downstreamAddressProvider().localAddress()**->asString();**
          std::string changed_localaddress = "[text I want to add]" + localaddress + "[/text I want to add]";
          return changed_localaddress;
        });

**Comment by Edimo24** [comment]
@ggreenway

**Comment by ggreenway** [comment]
I don't understand the question. Can you elaborate/rephrase?

**Comment by Edimo24** [comment]
@ggreenway I tried the above mentioned scenario but it does not work since I am returning a string where I should not return one. To keep the long story short I need any ideas how to add tags in some of command operators. I want to add tags at several command operators but I am struggling a lot how to do it. (tried different changes in Envoy code) 

When accessing Access logs I need to see something like  [tag]%DOWNSTREAM_LOCAL_ADDRESS%[/tag],[tag]%DOWNSTREAM_REMOTE_ADDRESS%[/tag]. Do you have any idea how to do it?

**Comment by ggreenway** [comment]
Why not just put `[tag]` directly into the format string? Why does the replacement formatting need to change?

**Comment by Edimo24** [comment]
How to do it? Because I only find the command operators under envoy/source/common/formatter/substitution_formatter.cc
And the way how these command operators are generated are as below: (line 838)

  **} else if (field_name == "DOWNSTREAM_LOCAL_ADDRESS") {
    field_extractor_ =
        StreamInfoAddressFieldExtractor::withPort([](const StreamInfo::StreamInfo& stream_info) {
          return stream_info.downstreamAddressProvider().localAddress();**

Do you have any suggestion where to add the [tag] directly?

**Comment by Edimo24** [comment]
@ggreenway I also realized that in the default format string there are not all the command operators so I am not sure if I can add the tag directly there... (for instance the DOWNSTREAM_LOCAL_ADDRESS is not there)

**Comment by Edimo24** [comment]
@ggreenway any suggestion?
