### ISSUE TITLE
Upstream Connection ID in Access Logs

### ISSUE THREAD

**Issue by llu94** [envoyproxy/envoy#19215]
*Title*:  Implement an Upstream Connection ID Field in the Access Logs

*Description*:

As per the latest documentation Envoy currently supports the downstream connection ID in its access logs. This is used to cross reference logs across multiple log sinks or to do timing related analysis on connections. Is it possible to have a comparable log entry for the upstream connection IDs and if so how would one go about doing it? 

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by llu94** [comment]
Can someone add the area/access_log label to this issue?

**Comment by rojkov** [comment]
cc @auni53 @zuercher @davinci26 @itamarkam

**Comment by itamarkam** [comment]
@yanavlasov can you please mark this as "no stalebot"? I can work on this in a couple of weeks.
