### ISSUE TITLE
Utility::getLocalAddress() returns address with the wrong IP version

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#19231]
This helper function is supposed to take in a IP version and returns the first non-loopback address of that version.  However, https://github.com/envoyproxy/envoy/pull/18821 changes it to return the first non-loopback address of any IP version.

**Comment by danzh2010** [comment]
@junr03

**Comment by junr03** [comment]
@danzh2010 sorry for the bug. I have fixed and modified tests in #19286 ptal
