### ISSUE TITLE
Proactively sending close header to the downstream

### ISSUE THREAD

**Issue by jhpatel** [envoyproxy/envoy#19236]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Proactively sending close header to downstream upon failure and graceful shutdown.

*Description*:
We noticed close header is not sent proactively upon the side car app failure and also during envoy shutdown. In side car/service mesh like scenarios this will be extremely useful to kick failed/unhealthy node out immediately without any failure or retry flood. There're multiple options to incorporate it without affecting existing behavior. I'll add in comment or share a design document. I'm new but can try contribute the change with some guidance, as it seems not too complicated.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @mattklein123
