### ISSUE TITLE
ext_authz: "envoy_grpc" client of "grpc_service" always uses HTTP/1.1

### ISSUE THREAD

**Issue by acruise** [envoyproxy/envoy#19246]
*Title*: ext_authz: "envoy_grpc" client of "grpc_service" always sends HTTP/1.1

*Description*:
I'm trying to set up an authenticated, non-transparent forward proxy server (i.e. using HTTP CONNECT). After a day or two of struggle getting the basic proxy functionality working, now I'm trying to plug in an external authorization service.  I'm currently using Envoy 1.20.1 in docker (because the Mac DNS thing is ridiculous! :)

I built my external authorization service using the following dependencies:

    io.envoyproxy.controlplane:api:0.1.28
    io.grpc:grpc-netty-shaded:1.39.0

And the server code is basically boilerplate for now:

        package com.example.etc
        
        import io.envoyproxy.envoy.service.auth.v3.AuthorizationGrpc
        import io.envoyproxy.envoy.service.auth.v3.CheckRequest
        import io.envoyproxy.envoy.service.auth.v3.CheckResponse
        import io.grpc.ServerBuilder
        import io.grpc.stub.StreamObserver
        
        object EnvoyAuthzServer {
              private val server = ServerBuilder
                .forPort(10003)
                .directExecutor()
                .addService(AuthzService)
                .build()
        
            @JvmStatic
            fun main(args: Array<String>) {
                server.start()
                server.awaitTermination()
            }
        }
        
        object AuthzService : AuthorizationGrpc.AuthorizationImplBase() {
            override fun check(request: CheckRequest, responseObserver: StreamObserver<CheckResponse>) {
                super.check(request, responseObserver)
            }
        }

When this server is running, and receives an ext_authz request, the netty http2 listener complains that the request is HTTP/1.1.  Indeed, if I substitute a netcat listener for this server, that's what's happening:

        computer:project alex.cruise$ nc -l -k 10003
        POST /envoy.service.auth.v3.Authorization/Check HTTP/1.1
        host: ext-authz
        te: trailers
        grpc-timeout: 200m
        content-type: application/grpc
        x-envoy-internal: true
        x-forwarded-for: 172.17.0.2
        x-envoy-expected-rq-timeout-ms: 200
        transfer-encoding: chunked
        [...]
        
After fighting with this for about half a day, I decided to try the `google_grpc` client instead of `envoy_grpc` and it immediately started with HTTP/2, and netty is happy. There aren't any visible configuration parameters in `envoy_grpc` that would seem to make sense here.

I suppose my ext_authz server is "from the future" of gRPC with respect to Envoy, but it'd be really nice if this version mismatch were easier to google!

I can attach logs, config, etc. later if desired.

**Comment by phlax** [comment]
cc @dio

**Comment by ramaraochavali** [comment]
I guess the upstream cluster when you have used envoy_grpc, does not have http2_protocol_options set. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster

**Comment by acruise** [comment]
> upstream cluster when you have used envoy_grpc, does not have http2_protocol_options set

That's true! It would be good if the docs for envoy_grpc mentioned that. :)
