### ISSUE TITLE
Questions on stream id exhaustion and handling the error NGHTTP2_ERR_STREAM_ID_NOT_AVAILABLE

### ISSUE THREAD

**Issue by sha-rath** [envoyproxy/envoy#19257]
*Title*: *Questions on stream id exhaustion in long-lived HTTP2 connections and handling the error NGHTTP2_ERR_STREAM_ID_NOT_AVAILABLE*

*Description*:
In one of our tests where an HTTP2 server based on nghttp2 was used, it was observed that an unknown error was thrown once the stream id's were exhausted. After this, the connection remained open without any valid stream id and therefore it failed to handle new requests. A new connection was not opened as well. It is possible that nghttp2 sent out the error **NGHTTP2_ERR_STREAM_ID_NOT_AVAILABLE (-509)** as the stream id's reached a maximum value, but it probably wasn't handled properly. Since HTTP2 codec in Envoy is based on nghttp2, would Envoy handle this particular error and close the connection? I could not see this error being handled in the envoyproxy code.

The standard here https://httpwg.org/specs/rfc7540.html#StreamIdentifiers states the following:
`"Stream identifiers cannot be reused. Long-lived connections can result in an endpoint exhausting the available range of stream identifiers. A client that is unable to establish a new stream identifier can establish a new connection for new streams. A server that is unable to establish a new stream identifier can send a GOAWAY frame so that the client is forced to open a new connection for new streams"`

The _max_requests_per_connection_ is supposed to be set to 2^29 when Envoy is acting as a client and therefore expected to drain the connection once this limit is reached. When Envoy is used as a server, does it send a GOAWAY frame so that the client is forced to open a new connection as described in the standard above? Also, is there any limit set on _max_requests_per_connection_?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
Related - https://github.com/envoyproxy/envoy/issues/19219

**Comment by sha-rath** [comment]
cc @YaoZengzeng could you please look into this as well please?

**Comment by YaoZengzeng** [comment]
@sha-rath I will:)

**Comment by sha-rath** [comment]
Thank you!

**Comment by alyssawilk** [comment]
If this has been observed for other nghttp2 servers I think filing an issue with nghttp2 might make sense?
cc @birenroy to make sure oghttp2 handles this gracefully.

**Comment by alyssawilk** [comment]
Is this a duplicate of https://github.com/envoyproxy/envoy/issues/19257 ?

**Comment by sha-rath** [comment]
@alyssawilk sorry my question was wrongly framed. I have updated my question now. I'm not sure if there is an issue with nghttp2 as such, would like to hear it from @birenroy as well. I think you meant #19219. If so, yes, it is mostly similar except for the error handling part.

**Comment by birenroy** [comment]
I don't have much detailed knowledge of nghttp2 or its internals. I would expect it to send a GOAWAY as indicated in the spec, but I haven't investigated the source code.

I'll make a note to ensure our replacement library does the right thing.
