### ISSUE TITLE
Add per-request time added by Envoy to statistics

### ISSUE THREAD

**Issue by nosmo** [envoyproxy/envoy#19268]
*Title*: Add per-request time added by Envoy to statistics

*Description*:

As mentioned in #12437, the total time added by Envoy to a request can be obtained from access logs by subtracting %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% from %DURATION% on a per-request basis. We'd like to analyse this number for the purposes of monitoring and reporting, and so it would be extremely useful if this number could be stored in a histogram and made available in a manner similar to other `time_bucket` elements emitted by Envoy statistics so it can be analysed via Prometheus.

**Comment by phlax** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
Sorry for the delayed reply. I occasionally miss some news. 😞 

About this question, I think Envoy has provided request time bucket. Or are `downstream_rq_time` and `upstream_rq_time` not enough for you?

**Comment by nosmo** [comment]
No problem, thanks for your response! In our usecase they're not quite accurate enough - in theory you should be able to estimate by subtracting the required quantile (0.99 in our case) in `upstream_rq_time` from `downstream_rq_time` but in practice variations between the two histograms means that the numbers don't fully align properly when subtracted.
