### ISSUE TITLE
dynamic_warming_clusters does not turn active

### ISSUE THREAD

**Issue by hzxuzhonghu** [envoyproxy/envoy#19262]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/36446/integ-security-istiodremote-tests_istio/1469215302897111040/artifacts/security-mtls-first-party-jwt-7/_suite_context/test-ns1-1-13830-state-1569201954/config/c-v1-b4f9bbdb6-2qzvb_proxy-config.json  

This is the config dump, as can be seen, there are many dynamic warming clusters, not sure why they are always warming.

```
"dynamic_warming_clusters": [
    {
     "version_info": "2021-12-10T08:19:32Z/10",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|443||c.test-ns1-1-13830.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|443||c.test-ns1-1-13830.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "default_original_port": 443,
         "services": [
          {
           "name": "c",
           "namespace": "test-ns1-1-13830",
           "host": "c.test-ns1-1-13830.svc.cluster.local"
          }
         ]
        }
       }
      },
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "protocol": "istio-peer-exchange"
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {
             "match_subject_alt_names": [
              {
               "exact": "spiffe://cluster.local/ns/test-ns1-1-13830/sa/c"
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.443_._.c.test-ns1-1-13830.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer"
        }
       }
      ]
     },
     "last_updated": "2021-12-10T08:19:32.492Z"
    },
```

**Comment by hzxuzhonghu** [comment]
@Shikugawa seems related to #12783

**Comment by hzxuzhonghu** [comment]
@lambdai  is this similar as #13874

**Comment by howardjohn** [comment]
Maybe never sent EDS?

**Comment by hzxuzhonghu** [comment]
It has sent, you can see it in the config, "outbound|443||c.test-ns1-1-13830.svc.cluster.local" lb endpoint is empty as the pod readiness probe(15020) has not succeeded. 

```
    "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "outbound|443||c.test-ns1-1-13830.svc.cluster.local",
      "policy": {
       "overprovisioning_factor": 140
      }
     }
    },
    {
     "endpoint_config": {
      "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
      "cluster_name": "outbound|7070||multiversion.test-ns1-1-13830.svc.cluster.local",
      "endpoints": [
       {
        "locality": {},
        "lb_endpoints": [
         {
          "endpoint": {
           "address": {
            "socket_address": {
             "address": "10.20.0.52",
             "port_value": 7070
            }
           },
           "health_check_config": {}
```

**Comment by howardjohn** [comment]
I think after CDS update EDS must be resent though?

**Comment by hzxuzhonghu** [comment]
It looks cds is not updated after first sent, there is no factor that would lead to that.

**Comment by Shikugawa** [comment]
@hzxuzhonghu Could you share the debug log? I'd like to check how the warming cluster initialization walked the execution step.

**Comment by hzxuzhonghu** [comment]
I have no debug log, it is run in ci, I could not reproduce in local env. I can open `debug` and have a test with ci.

**Comment by Shikugawa** [comment]
> I have no debug log, it is run in ci, I could not reproduce in local env. I can open debug and have a test with ci.

I have a lot of unknown settings to reproduce this problem... It has reproduced at first on https://github.com/istio/istio/pull/36446?

**Comment by hzxuzhonghu** [comment]
@Shikugawa 

config_dump https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/36446/integ-security-k8s-tests_istio/1471322947493826560/artifacts/security-mtls-first-party-jwt-0/_suite_context/istio-state-1998788007/cluster-0/istio-egressgateway-78dbb9489f-hfh7b_proxy-config.json


envoy debug log:  https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/36446/integ-security-k8s-tests_istio/1471322947493826560/artifacts/security-mtls-first-party-jwt-0/_suite_context/istio-state-1998788007/cluster-0/istio-egressgateway-78dbb9489f-hfh7b_istio-proxy.log

**Comment by Shikugawa** [comment]
This behavior is a bug caused by the Init Manager. After examining the logs, the following facts were found.

1. this is not caused by the initialization of the EDS cluster. As far as I can see, `ClusterImplBase::onPreInitComplete()` is called normally. 
2. Probably, `ClusterImplBase::onInitDone()` is not called. Therefore, `ClusterImplBase::finishInitialization()` is not called, and the handler `initialization_complete_callback_`, which is called when the cluster is successfully started, is not called. The callback is `ClusterManagerInitHelper::onClusterInit()`, where the process of transitioning the warming to active is done, and this is the root cause of this issue.
3. `ClusterImplBase::onInitDone()` should be called after all target handles are called in InitManager. Some clusters are successfully going to Active, but such clusters have `locked_fn` called properly in `WatcherHandleImpl::ready()`. (This is a callback that is called when the cluster is successfully initialized.) However, clusters that are left warm are not called. Clusters that have successfully become active will try to acquire the lock again and succeed, even if the callback fails to acquire the lock once, but clusters that are still warming will not even try to acquire the lock in the first place.

**Comment by Stono** [comment]
Hey!
So I've been chatting with @howardjohn as I believe we're seeing this, or something similar in production on istio `1.12.1`, and also saw it on `1.11.x`.

We have an alert that fires when we see sync issues between `istiod` and proxies.  It's very rare, maybe once every other week.  We have a high churn environment (300-500 deployments a day).  There's been no correlation between the affected workloads when it does happen.  Restarting the affected workload "resolves" it as the proxy gets the latest config.

Talking through the latest example.   `vds-dvla-importer` was deployed, which caused `vds-admin-2` to receive updated config.  It seemed to reject that config.

When we run an `istioctl proxy-status` command, we see this diff returned:

```
-
+                                    "matchSubjectAltNames": [
+                                        {
+                                            "exact": "spiffe://cluster.local/ns/vds-dvla-importer/sa/vds-dvla-importer-account"
+                                        }
+                                    ]
                                 },
```

In the config dump, we see `outbound|80||app.vds-dvla-importer.svc.cluster.local` is there as `2021-12-20T17:00:00Z/845`, and it is there as warming at `2021-12-20T20:22:19Z/854`.

So it appears `istiod` pushed at `17:` config with SANs. Then at 20:22 without SANs, which it is not accepting

As previously mentioned, restarting the workload "fixes" it, the new pods get config they accept.

**Comment by Shikugawa** [comment]
@Stono I've been investigating this issue with @hzxuzhonghu for a few days now. After examining the logs provided, we have found that in the initialization step of the cluster, the trigger to go to Active is not being called and therefore is not transitioning to warming. According to the logs provided by @hzxuzhonghu, it is only the EDS clusters that are warming, and these clusters will not become Active without a pair of CDS push and EDS push. Also, the warmed clusters are sending CDS pushes twice, which I am not sure is necessary. It is possible that this problem existed potentially before the introduction of the warm state and became apparent after the introduction of the warm state.

Does this problem occur in other than EDS clusters? Could you please provide the config and logs?

**Comment by howardjohn** [comment]
So sending 2 CDS push in a row without EDS may trigger this? I could see
this plausibly happening in Karl's case

**Comment by hzxuzhonghu** [comment]
***
In the incremental protocol variants, the server sends each resource in its own response. This means that if the server has previously sent 100 resources and only one of them has changed, it may send a response containing only the changed resource; it does not need to resend the 99 resources that have not changed, and the client must not delete the unchanged resources.

In the SotW protocol variants, all resource types except for Listener and Cluster are grouped into responses in the same way as in the incremental protocol variants.
***

According to this doc, we donot need to send the eds for a cluster if the cluster doesnot change.

**Comment by lambdai** [comment]
> 2\. Probably, `ClusterImplBase::onInitDone()` is not called.

ClusterImplBase::onInitDone() is[ the only statement in the init_watcher of the cluster ](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/upstream_impl.cc#L1055)

IMO, this lambda is not called IFF the init_watcher_ is destroyed during the cluster destroyed. 

Particularly, any early destroyed/ready target doesn't cause the callback of watcher lost.

I confirmed by adding ready target in a test case.

It's not clear to me whether the cluster manager should be more robust or we do need to improve init manager

**Comment by hzxuzhonghu** [comment]
I would be better if this can be improved, I think both xds server and envoy can benefit.
