### ISSUE TITLE
Dependency checker should ignore pre-releases

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#19263]
### description

currently the dependency checker doesnt discriminate pre-releases - eg https://github.com/envoyproxy/envoy/issues/19154

**Comment by phlax** [comment]
cc @kfaseela

**Comment by kfaseela** [comment]
I can work on this

**Comment by moderation** [comment]
Be aware that there is all manner of different release strategies being used by repos. Some repos don't have releases. Some repos have releases but never tag a latest release. Some repos have releases where everything is a pre release. 

An example of a dependency we use that has _only_ pre releases - https://github.com/grailbio/bazel-compilation-database/releases

**Comment by phlax** [comment]
hmm, thats annoying - not sure why they are doing that, altho i believe that repo is in "maintenance mode" so maybe related

in the main i think we only want notifying of actual releases rather than pre-releases - there are a couple already where its flagging the "wrong" version

**Comment by moderation** [comment]
That is one example - there are many in our full list

**Comment by phlax** [comment]
can we add a flag in the metadata `use_prerelease` or somesuch ?

**Comment by phlax** [comment]
For reference these are the currently flagged releases, that i think should not be, or have the wrong version:

- https://github.com/envoyproxy/envoy/issues/19207
- https://github.com/envoyproxy/envoy/issues/19156
- https://github.com/envoyproxy/envoy/issues/19155
- https://github.com/envoyproxy/envoy/issues/19154

not 100%, but i think this is a byproduct of the fixes/updates we made to the dep checker recently

either way - it would be good to have these flag the correct versions, and only when they are released etc

i had a quick look through repository locations and didnt see anything else pegged to a pre-release, but then it wasnt obv the situation with bazel-compilation-database either so not sure of any others
