### ISSUE TITLE
Transport socket for internal listeners

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#19274]
*Description*: add support for custom transport socket options for the internal listeners.

*Issue*: Internal address in an HTTP connection pool assumes re-use of the TCP stream between multiple downstream HTTP requests. This is not always desired, e.g. if the internal listener partitions requests into multiple streams based on some request attributes, because it puts those attributes into the outer envelope upstream from the internal listener.

As an analogy, Proxy Protocol upstream transport uses the source address in the protocol header, which means HTTP connection pool establishes a new Proxy Protocol connection for different source addresses. The proposal is to generalize this behavior, so that internal listeners can serve as the generic L4 tunneling protocol encapsulation and define what request attributes to use to mux multiple L7 requests onto a single L4 stream.

Concretely, we would like to define a transport socket that enumerates the request attributes to use to form a hash when using an internal address. This would be a generalization of [ProxyProtocolData](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/envoy/network/proxy_protocol.h).

It also makes sense to propagate this information to the internal address stream info by default (see [1]). It might also be desirable to declare the hash in the internal listener itself instead of the upstream internal address, this is up to discussion.

cc @lambdai @wjtracey 

Reference:
1.  [metadata transfer over internal listener](https://github.com/envoyproxy/envoy/issues/19189).

**Comment by kyessenov** [comment]
@alyssawilk For thoughts since it's related to ALPN propagation in transport socket options.

**Comment by alyssawilk** [comment]
will that be relevant?  I thought the config was basically
one envoy filter chain --- internal upstream transport socket -- internal listener --- another envoy filter chain --- upstream
where there would be no ALPN on the intenal hop, and the upstream hop wouldn't have any internal config?

**Comment by lambdai** [comment]
@kyessenov @alyssawilk 

The ALPN concern should be extended to any "out-of-band" connection data.

If we zoom into the connection establish phase, we can see it's asynchronous
1. router request a "connection" from the cluster providing the transport socket 
2. the cluster return the router a established "connection" asynchronously. The transport socket object of the returned connection may not be the exact one. That's the point of the conn pool.

That says, the connection pool must track what connections are exchangeable and the connection pool key is used.

The de facto is that the conn pool key combines the router setting(e.g. use downstream connection id as key)  and transport socket setting(alpn and proxyprotocol address).

The proposed new transport socket protocol demands more `context` participating in the conn key

**Comment by alyssawilk** [comment]
This may be naive but I'm not sure if we can do all of that?  I would think we'd be doing a literal replacement of the 2 hop system with a 1 hop system.  right now you generally wouldn't configure the loopback upstream with "do alpn" or "add a proxy protocol header", you'd rely on the actual upstream to do that.  Similarly we wouldn't expect the loopback upstream to be able to infer what the next hop upstream would do.
Now there's definitely areas where we're going to want to communicate information from one hop to the next - ideally I'd think we'd want to communicate actual ALPN negotiated or second hop upstream info.  I wonder if we can make the upstream stream info a shared pointer, and have the virtual loopback one just point to the actual upstream stream info once it has been established?

**Comment by alyssawilk** [comment]
alternately, potentially also naive, do we need the full listener stack for this? in-house when we do http/2 over http/2 we don't mock out the equivalent of the entire filter chain, we do a more simple pre-processing.  The Envoy mobile stack has the ability to create a virtual codec getting headers, body, and data, and put them through an HCM, and _if_ the use case here is 2 rounds of HTTP processing, we could have the upstream request do something similar to that. That said if you need the two hops to handle [tcp/http http/tcp http/http tcp/tcp] and not just [http/http] the current route is definitely more flexible

**Comment by kyessenov** [comment]
@alyssawilk In general, I agree that "flattened" version would probably be simpler and more efficient. E.g. something like upstream network filters for muxing and listener filters for de-muxing. We are not ruling out that option long term. We actually spent a long time arguing that. But currently, we think it's more flexible to have 2 hop solution because it lets us do things:
- avoid complete re-design of xDS in the control plane, chaining two listeners is easier to accomplish in convoluted control plane code;
- explore some "layer-breaking" protocols, like TLS within HTTP. Envoy makes it hard to plug network-level features like listener filter chain matching or sniffing within HCM.

What we essentially would like from internal listeners now is a mechanism to define a custom transport protocol (e.g. think of ability to write custom TLS encoder as an extension). Hence, we want a flexible integration with HTTP pooling that takes into account additional transport socket options.

**Comment by lambdai** [comment]
In short term we'd like to assume all the downstream traffic is tcp, so 2 rounds of HTTP processing does not happen.

The longer term plan is to support parsing downstream http GET to upstream http CONNECT. 

What is the shortest path to achieve? My understanding is that HCM cannot magically create CONNECT request from a non-CONNECT request.

**Comment by kyessenov** [comment]
This is a diagram for composition with the internal listener. The gist is that internal listener allows us to implement a custom transport socket using existing primitives from listener (filters, chains, etc):

[internal-composition.pdf](https://github.com/envoyproxy/envoy/files/8026100/internal-composition.pdf)

@mattklein123 FYI.

**Comment by kyessenov** [comment]
To elaborate more on the wire specifics, and provide more context for the above diagram:

Consider an originating connection to service `X:80` from pod `A`. Normally, `X` VIP would resolve to some member pod-port `B:8080`. Normally, if we want Envoy to proxy this traffic, we would use EDS for `X` and have a regular TCP connection to `B:8080`.

Our goal is to wrap this connection into a shared, secure tunnel in the form of HTTP CONNECT inside mTLS. So what we would like to Envoy to produce is:
* TLS to `B:xxxx` where `xxxx` is some random reserved port.
* h2 connection within TLS
* h2 CONNECT stream within h2 connection with the following headers:
   - source-ip: A
   - destination-ip: B
   - destination-port: 8080

Because we need to place the resolved address into the header, we have to perform EDS resolution prior to initiating CONNECT request in HCM. Hence, the need for the two-phase internal listener design. We also have additional policies and telemetry that need to be applied in the internal (tunnel) listener. Because we would like to avoid creating internal listeners for each service and/or each member pod, we would like these policies to be expressed in terms of dynamic metadata and filter state.

**Comment by kyessenov** [comment]
Not stale.
