### ISSUE TITLE
Questions on unmatched stats_tags, it will change metrics name

### ISSUE THREAD

**Issue by chinaran** [envoyproxy/envoy#19278]
When add new custom stats tag on istio, if you don't restart envoy, the metrics name will have some prefix.
For example (base on https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/):
Add extra tag: request_operation，before restart envoy, the name envoy_request_operation___somevalue___istio_requests_total is created.
I know stats_config is a  part of the bootstrap configuration.
But why envoy handle unmatched tags like this, it will break current metrics.
Can envoy just ignore unmatched tags？

**Comment by phlax** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
I'm not too familiar with Istio operation. Can you describe the sequence of of events, with the expected/actual results just in terms of Envoy calls?

Thanks!

**Comment by kyessenov** [comment]
This is due to regex for tag extraction being in the bootstrap while the
tag production being in xDS. That means that without a restart the two are
inconsistent. One way to solve it is to allow dynamic tags in production
and avoid bootstrap.

**Comment by chinaran** [comment]
@kmyerson You are right. It's better if envoy allows dynamic tags in production
and avoid bootstrap.

**Comment by jmarantz** [comment]
So currently when Envoy registers a new stat, it starts with a fully elaborated stat-name. When the stat is constructed in memory, it goes through a tag extraction process using the currently-known tag-extraction regexes.

Are you suggesting that when a new tag-extraction regex is added, that Envoy should re-iterate through all known stats and perform tag extraction again?

**Comment by chinaran** [comment]
@jmarantz I'm suggest envoy can support dynamic udpate stats_tags configuration.
If using istio, and a k8s cluster has hundreds of pods, when adding a new stat tag, you need restart all pods.
During the restart time(may be very long), some services monitoring data is abnormal, because metrics name changed by the new stat tag.
After all pods restarted, Monitoring data becomes normal.

**Comment by jmarantz** [comment]
This is worth thinking about, but I'm not optimistic. I'd have to think about it more. The main trouble is the existing stat objects (counters etc) are referenced from lots of structures in Envoy, so we have to keep the same objects. The question is whether we can contrive to mutate their tags and tag_extracted_name without disturbing operations on other threads.

I'm guessing this cannot be made safe without adding mutexes to each stat, which would consume a lot of memory.

**Comment by chinaran** [comment]
@jmarantz I understand. Envoy stats system is complex. The design porpuse is using low memory and thread safe.
