### ISSUE TITLE
Will the slowstart mode be supported in the future?

### ISSUE THREAD

**Issue by CrossingTheRiverPeole** [envoyproxy/envoy#19299]
slow start mode：
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start.html?highlight=slowstart

**Comment by tonya11en** [comment]
Can you elaborate a bit on what you mean? Slow start can already be configured via the [cluster configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-slowstartconfig-slow-start-window).

**Comment by CrossingTheRiverPeole** [comment]
Sorry, I made a mistake, please ignore this question
