### ISSUE TITLE
Request/response header bytes calculation content

### ISSUE THREAD

**Issue by nehap4** [envoyproxy/envoy#19293]
I tried enabling Access log for envoy-proxy by adding REQUEST_HEADERS_BYTES & RESPONSE_HEADERS_BYTES parameters after referring https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#. However I am unable to the map the request/response header size of HTTPS request sent by browser with what is getting printed in the access log. Calculating the bytes using the request/response getting printed in debug logs doesn't match. Is there any way to know the actual contents of the headers used for this calculation?

**Comment by phlax** [comment]
cc @TAOXUY

**Comment by cpakulski** [comment]
@nehap4 Can you elaborate a bit where did you observe the mismatch? For example, the expected value of request header was X and access log printed Y. Just would like to get some info to help me start investigation.

**Comment by nehap4** [comment]
The request header looks something like below in browser:

GET /api/xxx HTTP/1.1
Host: xxx
Connection: keep-alive
sec-ch-ua: 
sec-ch-ua-mobile: ?0
User-Agent: xxxx
sec-ch-ua-platform: "macOS"
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: script
Referer: FQDN
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Cookie: xxxx

Expected bytes : 829


and the envoy debug log for same request is:

[2021-12-15 10:04:35.420][17][debug][router] [source/common/router/router.cc:673] [C5929][S7971607195520936122] router decoding headers:
':authority', 'xxxx'
':path', '/api/xxx'
':method', 'GET'
':scheme', 'https'
'sec-ch-ua', '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"'
'accept', 'application/json, text/plain, */*'
'sec-ch-ua-mobile', '?0'
'user-agent', 'xxxx'
'sec-ch-ua-platform', '"macOS"'
'sec-fetch-site', 'same-origin'
'sec-fetch-mode', 'cors'
'sec-fetch-dest', 'empty'
'referer', 'xxxxx'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-GB,en;q=0.9'
'cookie', 'xxxxx'
'x-forwarded-proto', 'https'
'x-request-id', 'cffc39f5-3a97-4e61-8252-617cfdbe564c'
'x-auth-request-email', 'xxxxxx'
'x-envoy-expected-rq-timeout-ms', '300000'

Reported bytes via  REQUEST_HEADERS_BYTES: 786

**Comment by rgs1** [comment]
Hmm I wonder if this is somewhat similar to what was fixed in #15908.
