### ISSUE TITLE
headers_with_underscores_action isn't applied for Clusters (upstreams)

### ISSUE THREAD

**Issue by Spoonbender** [envoyproxy/envoy#19302]
*Title*: headers_with_underscores_action isn't applied for Clusters (upstreams)

*Description*:
The `HttpProtocolOptions.headers_with_underscores_action` action can be configured in two separate places:
1. As part of the Listener's HTTP Connection Manager settings, under `common_http_protocol_options.headers_with_underscores_action`
2. As part of the Cluster settings, under `common_http_protocol_options.headers_with_underscores_action`

However, it seems the setting is only applied at the Listener level:
When configured at the Cluster, the action isn't performed.

We should either write in the documentation that this option is not applied to upstreams (in the same fashion as we do in `max_connection_duration`), or implement the logic to apply the action at the cluster-level as well.

*Relevant Links*:
[HttpProtocolOptions docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-httpprotocoloptions)
[HeadersWithUnderscoresAction docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-enum-config-core-v3-httpprotocoloptions-headerswithunderscoresaction)

**Comment by phlax** [comment]
cc @yanavlasov @danzh2010

**Comment by danzh2010** [comment]
Thanks for reporting this issue! Adding the support in cluster makes more sense to me. Is it a blocker for you? 
cc @alyssawilk

**Comment by Spoonbender** [comment]
> Thanks for reporting this issue! Adding the support in cluster makes more sense to me. Is it a blocker for you? cc @alyssawilk

No, not a blocker, mostly a matter of convenience and flexibility.

**Comment by yanavlasov** [comment]
This is an artifact of using the same configuration for both listener and cluster protocols. The doc needs to be clarified that the setting only applies to downstream connections and is ignored in cluster configuration. This setting is to mitigate confusion attacks in access control based on headers and as such not applicable for responses.

**Comment by alyssawilk** [comment]
https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/protocol.proto#L214

  // Action to take when a client request with a header name containing underscore characters is received.
  // If this setting is not specified, the value defaults to ALLOW.
  // Note: upstream responses are not affected by this setting.

I think the documentation is pretty clear here.

**Comment by Spoonbender** [comment]
@alyssawilk my (incorrect) understanding from the configuration schema and the docs was that if I configure this field for a cluster, then the `headers_with_underscores_action` would be applied to headers of requests routed to that cluster. The docs only explicitly specify that response headers will not be affected.

**Comment by alyssawilk** [comment]
"Action to take when a *client* request with a header name containing underscore characters is received."
If the client request had underscores, those actions will be taken.
If a filter alters the request, but the client request didn't have underscores, the action won't be taken.

So I think the docs do state that today but it sounds like it'd be helpful to make it more explicit for folks who don't live in the Envoy code base :-)    Please let me know if the wording in https://github.com/envoyproxy/envoy/pull/19398 seems more clear?

**Comment by Spoonbender** [comment]
@alyssawilk I think it is better

**Comment by alyssawilk** [comment]
Awesome, thanks.  lmk if you have any suggestions for improvements, otherwise I'll leave it to Lizan :-)
