### ISSUE TITLE
support request mirror policies at the virtual host and/or route configuration level 

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#19306]
Currently you can only set request mirror policies at the route level:

https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L1101

We have a use case where we'd like to set this for all routes in a given vhost or set of vhosts, thus it would be nice to support this at a higher scope than just route level.

**Comment by rgs1** [comment]
cc: @htuch for API thoughts.

**Comment by htuch** [comment]
This keeps coming up for different routing policy - there is a general desire to be able to apply policy at different scopes across [entire route config, virtual host, route, weighted cluster]. I think it's totally fine. If we had to do this all over again, I think we might think about doing it in a more principled way, but for now, examples like CORS and hedge policy point the way to just adding it. CC @envoyproxy/api-shepherds

**Comment by rgs1** [comment]
cc: @JuniorHsu

**Comment by JuniorHsu** [comment]
Our use case is in a higher level, which is `RouteConfiguration`

**Comment by JuniorHsu** [comment]
I figure out it needs more care since
1. There's `VirtualHost` between `RouteConfiguration` and `RouteAction`. It's a little weird to skip `VirtualHost` if we add mirror policy to `RouteConfigurateion`
2. ` repeated RequestMirrorPolicy request_mirror_policies` is an array . If we specify policy in higher level but want to remove the policy in an specific route, we might need another boolean `remove_mirror_policies` which is needed but tedious.

**Comment by rgs1** [comment]
> I figure out it needs more care since
> 
> 1. There's `VirtualHost` between `RouteConfiguration` and `RouteAction`. It's a little weird to skip `VirtualHost` if we add mirror policy to `RouteConfigurateion`

Yes, we should support it for both `RouteConfiguration` and `VirtualHost`

> 2. ` repeated RequestMirrorPolicy request_mirror_policies` is an array . If we specify policy in higher level but want to remove the policy in an specific route, we might need another boolean `remove_mirror_policies` which is needed but tedious.

We might, but I don't think we need to implement that right away. Let's keep it simple for the first iteration.
