### ISSUE TITLE
Consistent picks from weighted cluster across multiple proxy levels

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#19312]
In our configuration we have two proxy levels. If a route uses weighted cluster to pick a service, we would like to have consistent picks in both L1 and L2 proxies. The use case is the following:

1. L1 makes a pick from weighted cluster, which contains services in multiple zones, and determines the zone where the service is located
2. L1 forwards request  to L2 in that zone
3. L2 needs to make the same pick as otherwise it can forward to a service in a different zone, resulting in high tail latency

We could make this work if L1 and L2 have different routing configuration, but this complicates the config pipeline and make it even harder to reason about eventually consistent config on L1s and L2s.

The proposal is to add a `random_number_source` field the the weighted cluster proto, which will allow to use a random number other than stream ID. For this case this can just be a header name, so that L1 can tell L2 the random number that was used in weighted cluster pick.

**Comment by yanavlasov** [comment]
@snowp for comments.

**Comment by snowp** [comment]
The idea of making the source of the random value be configurable makes sense to me (it was the idea that came to mind as I was reading the problem statement as well).

Would you implement this by inserting a random value into a header at L1 and re-evaluating the route, or would you you have L1 just insert a header containing the random number via a filter? 

Would you want some kind of mechanism to only support this for trusted downstreams (e.g. using the internal address check) or is it enough to have this just be configurable?

**Comment by yanavlasov** [comment]
Thanks @snowp 
I was thinking of adding a filter to insert a header with random value at L1.

I think Envoy already has a mechanism for detecting internal requests and cleaning internal only headers if it is not internal. I think this should be enough for now.
