### ISSUE TITLE
No Healthy Upstream error when health_check property omitted

### ISSUE THREAD

**Issue by tlhunter** [envoyproxy/envoy#1932]
This is a bit of a follow up to #1912. I'm currently using only CDS. My CDS endpoint returns information about hundreds services. Here's a truncated result:

```json
{
  "clusters": [
    "...",
    {
      "name": "autocomplete",
      "type": "strict_dns",
      "connect_timeout_ms": 2000,
      "lb_type": "random",
      "hosts": [
        {
          "url": "tcp://host1:31208"
        },
        {
          "url": "tcp://host2:31672"
        },
        {
          "url": "tcp://host3:31916"
        }
      ]
    },
    "..."
  ]
}
```

Note that there is no `health_check` property defined (on any entry) which should mean that health checks are disabled.

However, when I run the application, I notice two things. The first thing is that Envoy takes about 4 minutes before it starts allowing ingress HTTP calls to occur. The output logs which confirm this look like so:

```
[2017-10-24 22:09:38.532][203][warning][main] source/server/server.cc:164] initializing epoch 0 (hot restart version=9.200.16384.127)
[2017-10-24 22:09:38.562][203][warning][main] source/server/server.cc:332] starting main dispatch loop
Env Vars as seen from App: { HOME: '/root',
  HOSTNAME: '4c6976b72d2a',
  PORT0: '8080',
  PORT1: '8081',
  PORT_APP: '3000',
  S6_KEEP_ENV: '1',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PROTO: 'IPC',
  IPCLOCALPATH: '0' }
Server running at http://127.0.0.1:3000/
Access externally via http://127.0.0.1:8080/
[2017-10-24 22:13:39.799][203][warning][main] source/server/server.cc:316] all clusters initialized. initializing init manager
[2017-10-24 22:13:39.799][203][warning][config] source/server/listener_manager_impl.cc:448] all dependencies initialized. starting workers
```

Afterwards, if I make an egress request to the **autocomplete** service via Envoy, the request will fail. Manually making a cURL request to that same URL will succeed (assuming I replace `tcp://` with `http://`). When it fails, Envoy displays the following message:

```
503 - "no healthy upstream"
```

I am making use of a special `Envoy-Discovery-Target` header to notify Envoy which discovery service I'm attempting to communicate with. This configuration appears to partly work because when I grep the `/stats` admin endpoint after three failed egress requests I see the following (all lines with 0 values removed for brevity):

```
cluster.autocomplete.external.upstream_rq_503: 3
cluster.autocomplete.external.upstream_rq_5xx: 3
cluster.autocomplete.lb_healthy_panic: 3
cluster.autocomplete.max_host_weight: 1
cluster.autocomplete.update_attempt: 14
cluster.autocomplete.update_success: 12
cluster.autocomplete.upstream_cx_none_healthy: 3
cluster.autocomplete.upstream_rq_503: 3
cluster.autocomplete.upstream_rq_5xx: 3
```

The several minute pause, the `upstream_cx_none_healthy: 3` stat, and the envoy process idling at 10% of CPU makes me think that health checking is somehow enabled. Does anyone know these services are listed as unhealthy despite now health checks?

The following is my current configuration:

```json
{
  "listeners": [
    {
      "name": "ingress_http_listener",
      "address": "tcp://0.0.0.0:8080",
      "filters": [{
        "name": "http_connection_manager",
        "config": {
          "codec_type": "auto",
          "stat_prefix": "ingress_http",
          "route_config": {
            "virtual_hosts": [{
              "name": "route_vhost_local_service",
              "domains": ["*"],
              "routes": [{
                "timeout_ms": 0,
                "prefix": "/",
                "host_rewrite": "tcp://127.0.0.1:3000",
                "cluster": "application_cluster"
              }]
            }]
          },
          "filters": [{
            "name": "router",
            "config": {}
          }]
        }
      }]
    },

    {
      "name": "egress_http_listener",
      "address": "tcp://127.0.0.1:80",
      "filters": [{
        "name": "http_connection_manager",
        "config": {
          "codec_type": "auto",
          "stat_prefix": "egress_http",
          "route_config": {
            "virtual_hosts": [{
              "name": "route_vhost_remote_services",
              "domains": ["*"],
              "routes": [{
                "prefix": "/",
                "cluster_header": "Envoy-Discovery-Target",
                "timeout_ms": 15000,
                "retry_policy": {
                  "retry_on": "5xx",
                  "num_retries": 3,
                  "per_try_timeout_ms": 5000
                }
              }]
            }]
          },
          "filters": [{
            "name": "router",
            "config": {}
          }]
        }
      }]
    }
  ],

  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://0.0.0.0:8081"
  },

  "cluster_manager": {
    "cds": {
      "refresh_delay_ms": 10000,
      "cluster": {
        "name": "cds_cluster",
        "type": "static",
        "connect_timeout_ms": 250,
        "lb_type": "round_robin",
        "hosts": [{
          "url": "tcp://10.10.21.121:3090"
        }]
      }
    },
    "clusters": [
      {
        "name": "application_cluster",
        "connect_timeout_ms": 250,
        "type": "logical_dns",
        "lb_type": "round_robin",
        "hosts": [{
          "url": "tcp://127.0.0.1:3000"
        }]
      }
    ]
  }
}
```

**Comment by mattklein123** [comment]
A few things:

1) It sounds to me like DNS is hanging/failing at large scale.
2) You should be able to see status once Envoy boots by looking at /stats and /clusters.
3) For large CPU, it might have to do with the rate of DNS refresh and the number of DNS queries you are doing. You may have to lower the rate. See cluster settings for how to lower the DNS refresh interval. A perf profile / flame graph can help here in seeing where CPU time is being spent.

**Comment by tlhunter** [comment]
@mattklein123 you were right, there were largscale DNS issues. They've been resolved and the 3 minute pause has been reduced to 15 seconds.

**Comment by zanes2016** [comment]
Update: the `503 - no healthy upstream` intermittent response still exists with full ADS (CDS, LDS, EDS, & RDS). So far the only we to resolve the issue is to either restart the Discovery Server or the Envoy Proxies. 

Note that we do not have any Health Checks enabled and the configuration correctly specifies the IP:PORT pairs for the upstream service.

**Comment by nirvanagit** [comment]
@zanes2016 / @tlhunter - its been a while, but wanted to understand how this was resolved?

From what I understand, envoy is not able to get the resolutions for the endpoints you are accessing, and that is resulting in UH / no healthy upstream errors.

Was there any optimization you did to remediate the situation?
