### ISSUE TITLE
Add support for intermediate CA as trusted_ca with X509_V_FLAG_PARTIAL_CHAIN

### ISSUE THREAD

**Issue by dnephin** [envoyproxy/envoy#19326]
*Title*: Add support for intermediate CA as trusted_ca with X509_V_FLAG_PARTIAL_CHAIN

*Description*:
I am attempting to use Envoy with a `common_tls_context.validation_context.trusted_ca` where the PEM encoded certificate at that path is an intermediate (not self signed) certificate. Envoy is failing to communicate with the upstream with error:

> DeltaAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

After looking around a bit, and trying to use `openssl s_client -connect` with the certs I found that `openssl` only works if I use the `-partial_chain` flag. If I understand correctly the equivalent flag for the library is `X509_V_FLAG_PARTIAL_CHAIN`, and I don't see any way to set that in Envoy.

Is there some other way to allow an intermediate CA in `trusted_ca` ? Would you consider adding another option to `common_tls_context.validation_context` (or something around there) to pass this `X509_V_FLAG_PARTIAL_CHAIN` flag to the certificate verification?

Docs reference for that flag ([link](https://www.openssl.org/docs/man1.1.1/man3/X509_VERIFY_PARAM_set1_ip_asc.html)):

> The X509_V_FLAG_PARTIAL_CHAIN flag causes intermediate certificates in the trust store to be treated as trust-anchors, in the same way as the self-signed root CA certificates. This makes it possible to trust certificates issued by an intermediate CA without having to trust its ancestor root CA. With OpenSSL 1.1.0 and later and <X509_V_FLAG_PARTIAL_CHAIN> set, chain construction stops as soon as the first certificate from the trust store is added to the chain, whether that certificate is a self-signed "root" certificate or a not self-signed intermediate certificate. Thus, when an intermediate certificate is found in the trust store, the verified chain passed to callbacks may be shorter than it otherwise would be without the X509_V_FLAG_PARTIAL_CHAIN flag.

**Comment by Shikugawa** [comment]
I think it would be nice to have the ability to use intermediate certificates as trust anchors.

**Comment by ggreenway** [comment]
I agree, allowing trust of intermediate certs would be useful.

**Comment by Shikugawa** [comment]
@bryanwux assigned.

**Comment by bryanwux** [comment]
> @bryanwux assigned.

Thanks

**Comment by sergeybykov** [comment]
@bryanwux were you able to make any progress? We are keenly interested in this.

**Comment by LuyaoZhong** [comment]
@bryanwux  is busy on other work. I'd like to take this.

@ggreenway Do we need to introduce a new option? One alternative is making it default just like X509_V_FLAG_CRL_CHECK and X509_V_FLAG_CRL_CHECK_ALL, because it sounds a common usecase.

https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L104~#L106

**Comment by dnephin** [comment]
I forgot to mention this in my original post. In Go, https://pkg.go.dev/crypto/x509 always has the behaviour of allowing partial chains. So always setting `X509_V_FLAG_PARTIAL_CHAIN` would match the behaviour of the Go stdlib.
