### ISSUE TITLE
Crash in TCP proxy with flow control

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#1933]
Stack trace: https://github.com/istio/proxy/issues/593#issuecomment-338859258

It looks like when tcp_proxy successfully write buffer to downstream after once it was above watermark, then the below watermark callback calls `readDisable(false)` for upstream connection, but at that moment the upstream connection could be already closed. The default `per_connection_buffer_limit_bytes` is 1MiB so large payloads could hit this easily. 

The `file_event_` is reset [here](https://github.com/envoyproxy/envoy/blob/master/source/common/network/connection_impl.cc#L166) but dereferenced [here](https://github.com/envoyproxy/envoy/blob/master/source/common/network/connection_impl.cc#L262) so it results segfault.

@alyssawilk @PiotrSikora

**Comment by mattklein123** [comment]
This is loosely related to https://github.com/envoyproxy/envoy/issues/1928.

@alyssawilk I can fix this quickly if you are busy with other stuff. We can chat about it tomorrow.

**Comment by mattklein123** [comment]
I think @alyssawilk is busy with other stuff right now. I will fix this later today.
