### ISSUE TITLE
[Question] Where can I find the CI log

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#19345]
Where can I find the file for the CI error such as 

/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-opt/testlogs/test/extensions/transport_sockets/starttls/upstream_starttls_integration_test/test.log

**Comment by junr03** [comment]
The files are not accessible, but the test output is streamed to CI. So if you search for the test name and scrollback on the CI logs you will see the same output that would be in the file you are looking for.
