### ISSUE TITLE
Envoy error handling causes calling grpc clients confusion

### ISSUE THREAD

**Issue by egoldschmidt** [envoyproxy/envoy#1934]
I've been struggling with intermittent gRPC errors of the form `transport: received the unexpected content-type "text/plain"` when making calls from our Go service to a Python backend -- through a pair of Envoy instances in the "service-to-service" model. The error itself is emitted by the [header handling logic in the Go gRPC client library](https://github.com/grpc/grpc-go/blob/8214c28a62e1bd83dab226bc654dad72db2d8352/transport/http_util.go#L251). Looking deeper, this makes sense: Envoy specifically writes a 504 with content-type `text/plain` on timeout [(link)](https://github.com/envoyproxy/envoy/blob/master/test/common/router/router_test.cc#L582-L583).

As it is, I don't see how you can use the Go client with an Envoy instance that enforces timeouts. Is there a way that we can more idiomatically communicate errors back to callers? I.e., can't we send a header frame with `grpc-status: DEADLINE_EXCEEDED` and skip the text/plain and body nonsense? Instead should we make grpc clients tolerate `text/plain`?

I can unblock myself by setting timeouts extremely high to sidestep this issue altogether, but I'd love to discuss a better path forward.

**Comment by mattklein123** [comment]
> I.e., can't we send a header frame with grpc-status: DEADLINE_EXCEEDED and skip the text/plain and body nonsense? 

Nonsense is a matter of context.

There are many things we can do here (optionally via config):
1) Indicate to router that errors should be returned as gRPC errors (DEADLINE_EXCEEDED).
2) Auto-detect that a call is a gRPC call and return gRPC errors without any config switch.
3) Configuration over local error generation (no body, custom body, etc.)

Someone will need to work on ^. Marking help wanted.

**Comment by mattklein123** [comment]
Related to https://github.com/envoyproxy/envoy/issues/1178
