### ISSUE TITLE
https://www.envoyproxy.io/ links 404

### ISSUE THREAD

**Issue by brianbegy** [envoyproxy/envoy#19365]
*Title*: https://www.envoyproxy.io/ links 404

*Description*:
Call to action buttons "Get Started" and "Download" on the home page of https://www.envoyproxy.io/ 404.

*Repro steps*:
Visit https://www.envoyproxy.io/, click "Get Started"
![image](https://user-images.githubusercontent.com/17928652/147776985-bf4f7a06-e8c6-49af-9499-2f6250cd8c8e.png)

(Chrome Version 96.0.4664.110 (Official Build) (x86_64))

**Comment by jaketerrito** [comment]
Seems to only be an issue when on "latest", using something specific like "v1.20.1" seems to work.
https://www.envoyproxy.io/docs/envoy/latest VS https://www.envoyproxy.io/docs/envoy/v1.20.1

**Comment by phlax** [comment]
yep, something corrupted the latest docs build, ill look into it tomorrow, apologies for outage

**Comment by phlax** [comment]
it seems like there is an issue with a config example in the docs, ill raise a PR to resolve shortly

not immediately clear yet why this did not get caught in CI, but ill try and track down

**Comment by phlax** [comment]
seems like this is the culprit (or at least the change that is causing the issue) https://github.com/pygments/pygments/releases/tag/2.11.0

also seems like this is a reoccurrence of a similar problem:

https://github.com/envoyproxy/envoy/pull/13343

the reason its not picked up by ci is that ci is only building the rst, and not the html - probs we want to at least test rst -> html in ci

**Comment by phlax** [comment]
workaround is here https://github.com/envoyproxy/pytooling/pull/151

docs should be rebuilt shortly, if all goes well...

**Comment by phlax** [comment]
site is back up, fix/workaround:

- https://github.com/envoyproxy/pytooling/pull/152
- https://github.com/envoyproxy/envoyproxy.github.io/pull/212

apologies again for inconvenience

**Comment by phlax** [comment]
> the reason its not picked up by ci is that ci is only building the rst, and not the html - probs we want to at least test rst -> html in ci

this is not quite correct, just that envoy ci pins hashes whereas docs is not - probs we should pin deps there also
