### ISSUE TITLE
Wrong x-forwarded-for address

### ISSUE THREAD

**Issue by sefaphlvn** [envoyproxy/envoy#19368]
*Wrong x_forwarded_for address*

*Description*:
> Hi all, 
> This case happened a server with multiple ip adressess. 

Client
> eth0(10.216.15.213) default route
> eth1(10.216.14.4) this interface has ip route to 10.170.122.18

Control Plane Server
> envoy control plane address(10.170.122.18). 

There is no route issue. Just x-forwarded-for header is not include correct address. Traffic source address is 10.216.14.4 you can see in image. 

![image](https://user-images.githubusercontent.com/45564783/147810339-f5ae8362-2bb6-489f-8779-f082ae03c657.png)

**Comment by yanavlasov** [comment]
You will need to explain more about your test set-up before anyone can help you.

**Comment by sefaphlvn** [comment]
Envoy discover all resources from my management server(REST). This scenario happening during any resource requests(lds, cds, eds). when I check access logs from management server I saw this wrong ip address in "x-forwarded-for" header.

my lab environment:
```
management server: 10.170.22.18

client(envoy):
  - eth0: 10.216.15.213 (default)
  - eth1: 10.216.14.4
```
client route config like that:
```
$ ip route get 10.170.122.18
10.170.122.18 via 10.216.14.1 dev eth1 table 1001 src 10.216.14.4 uid 0
```

```
$ ip rule
0:	from all lookup local
5:	from 10.170.122.0/24 lookup 1001
5:	from all to 10.170.122.0/24 lookup 1001
```
tracepath result:

```
$ tracepath 10.170.122.18
 1?: [LOCALHOST]                      pmtu 1500
 1:  10.216.14.1                                          6.002ms
 1:  10.216.14.1                                          5.945ms
 2:  ***********                                        6.130ms
 3:  ***********                                          6.058ms
 4:  10.170.122.18                                         0.931ms reached
```
nmcli result:
```
ens256: connected to upstream
        "VMware VMXNET3"
        ethernet (vmxnet3), 00:50:46:82:1A:89, hw, mtu 1500
        ip4 default
        inet4 10.216.15.213/24
        route4 10.216.15.0/24
        route4 0.0.0.0/0
        inet6 fe80::250:56ff:fe83:8c89/64
        route6 ff00::/8
        route6 fe80::/64

ens192: connected to management
        "VMware VMXNET3"
        ethernet (vmxnet3), 00:50:46:82:86:CF, hw, mtu 1500
        inet4 10.216.14.4/24
        route4 10.216.14.0/24
        route4 0.0.0.0/1
        route4 128.0.0.0/1
        inet6 fe80::250:56ff:fe83:86cf/64
        route6 ff00::/8
        route6 fe80::/64
```
in this scenario I don't have any route problem. Only "x-forwarded-for" ip address not the right source address
If you have any questions I will be happy to answer.
