### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Barborica-Alexandru** [envoyproxy/envoy#19379]
Hi guys, sorry to bother you with building issues again. A quick rundown of everything i tried up to now:

Windows 10 + Docker desktop

Docker ubuntu 18 + clang+llvm 10 through 13
Docker ubuntu 20 + clang+llvm 10 through 11
Fedora 34 + clang+llvm 10 thought 13
Fedora 34 + package manager clang

(I then tried LXC ubuntu 18 + clang+llvm 11 and that one was real bad. failed on some kind of filesystem include or whatever.)

The build fails in the same spot no matter what:
```
In file included from ../../src/builtins/accessors.cc:9:
../../src/deoptimizer/deoptimizer.h:115:39: error: offset of on non-standard-layout type 'v8::internal::Deoptimizer' [-Werror,-Winvalid-offsetof] 
  static int output_offset() { return offsetof(Deoptimizer, output_); }
```

I then tried to eliminate all warnings and used this bazel build --copt=-w --cxxopt=-w -c opt envoy --define tcmalloc=disabled
but to no avail. Same error.

Anyway the context is that I need my binary without tcmalloc as it prevents envoy from running on low ram systems and on some embedded high ram systems. 
~~I would gladly use the docker CI image but I failed to understand how to use it on windows but for building a linux build. I'll settle for a step by step solution to use the CI image to build a release binary without tcmalloc.~~
I'm used to the process of building envoy being an ordeal in and of itself, but I feel that since version 1.20 something has changed as after a few days of troubleshooting I would finally be able to build the binary. This is no longer the case. 

All I can say is that this is a damn good piece of software for me to continue to fight through these build issues, and I want to make sure its well understood that I have nothing but respect for the devs. A new working and updated manual build process would not be amiss in the documentation. Just waiting until the build starts failing even in the docker CI image is not ideal.

I managed to build it in the docker CI image. But I am still very curious where the issue is in my process. 
I admit I might have forgotten occasionally to switch the branch/checkout version 1.20 so I might have been building master. I am going to verify this, but even so I would be curios to know what I am doing wrong. All I am doing is following https://github.com/envoyproxy/envoy/blob/main/bazel/README.md But in a docker container.

**Comment by yanavlasov** [comment]
You can try posting your build errors on Slack envoy-dev channel. This type of problem is not going to get attention here.

**Comment by libbkmz** [comment]
The same issue. Trying to build http-filter-example, and getting the same error with this commandline:
```
bazel build //:envoy --sandbox_debug --config=clang --verbose_failures --spawn_strategy=local --copt="-Wno-invalid-offsetof" --copt="-Wno-range-loop-construct" --copt="-Wno-error" --cxxopt="-Wno-error" --cxxopt="-Wno-invalid-offsetof" --cxxopt="-Wno-range-loop-construct"
```

Looks like copts and cxxopts are not propagating into the v8 genrule, cause I can't see these options under that commandline:
```
FAILED: obj/v8_base_without_compiler/accessors.o
clang++ -MMD -MF obj/v8_base_without_compiler/accessors.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"\" -D__ST
DC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DV8_ATOMIC_OBJECT_FIELD_WRITES -DV8_ATOMIC_MARKING_STATE -DV8_ENABL
E_LAZY_SOURCE_POSITIONS -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_SNAPSHOT_COMPRESSION -DV8_SHORT_BUILTIN_CALLS -DV8_ENABLE_WEBASSEMBLY -DV8_ALLOCATION_FOLDING -DV8_ALLOCATION_SITE_TRACKING -DV8_ADVAN
CED_BIGINT_ALGORITHMS -DV8_INCLUDE_RECEIVER_IN_ARGC -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DV8_IMMINENT_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DV8_TARGET_ARC
H_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_LINUX -DV8_RUNTIME_CALL_STATS -I../.. -Igen -I../../include -Igen/include -I../../third_party/zlib -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-
protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-pre
fixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -fno-omit-frame-pointer
 -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wmissing-field-initializers -Wno-shadow -Wunreachable-code -Wshorten-64-to-32 -O3 -fdata-sections -ffunction-sections -fno-unique-section-names -g1 -gdwarf-aranges -fvi
sibility=default -Wexit-time-destructors -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti  -Wno-sign-compare -Wno-deprecated-copy -Wno-unknown-warning-option -Wno-range-loop-analysis -Wno-shorten-64-to-32 -Wno-implicit-i
nt-float-conversion -Wno-builtin-assume-aligned-alignment -Wno-final-dtor-non-final-class -Wno-invalid-constexpr -c ../../src/builtins/accessors.cc -o obj/v8_base_without_compiler/accessors.o
```

**Comment by yanavlasov** [comment]
I saw these build failures as well on my workstation. Not sure about the root cause. CI builds seem to be fine. For now workaround is not to build WASM. Add `--define=wasm=disabled` to the bazel command line.

@PiotrSikora if this build problem is known.

**Comment by PiotrSikora** [comment]
I never saw this error when bulding Envoy, and it doesn't happen on the CI, but I think @alyssawilk saw it a while ago.

@Barborica-Alexandru @libbkmz could you test with https://github.com/envoyproxy/envoy/pull/19514? It should fix the issue.
