### ISSUE TITLE
Add detail about histogram buckets to the /stats endpoint

### ISSUE THREAD

**Issue by VillePihlava** [envoyproxy/envoy#19378]
*Title*: Add detail about histogram buckets to the `/stats` endpoint

*Description*:

Currently there is no way of seeing how many values an individual histogram bucket (with an upper and lower bound) contains from the `/stats` endpoint.

The `/stats` endpoint currently only prints a summary that can look like this:

`listener.0.0.0.0_9000.cryptomb.rsa_queue_sizes: P0(nan,1.0) P25(nan,8.024987213802275) P50(nan,8.049991475868183) P75(nan,8.074995737934092) P90(nan,8.089998295173636) P95(nan,8.094999147586819) P99(nan,8.098999829517364) P99.5(nan,8.099499914758681) P99.9(nan,8.099899982951737) P100(nan,8.1)`

 The `/stats/prometheus` endpoint is a little more helpful for determining how many values an individual bucket has, but the buckets only have an upper bound and include the values of the buckets below it, for example:

```
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="2"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="3"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="4"} 2
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="5"} 3
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="6"} 4
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="7"} 9
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="8"} 10
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="9"} 58667
```

With this kind of config:

```
stats_config:
  histogram_bucket_settings:
    match:
      contains: "cryptomb"
    buckets: [2,3,4,5,6,7,8,9]
```

It would be nice to have a way of seeing individual buckets that are bounded by an upper bound and a lower bound determined from the previous bucket's upper bound. For example, when using something like `/stats?histogram_buckets`, the output for histograms could look something like this:

`listener.0.0.0.0_9000.cryptomb.rsa_queue_sizes: [2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 5, 8: 1, 9: 58657]`

Any feedback, suggestions, or corrections are appreciated especially on the format of the output!

*Relevant Links*:

Initially discussed in this pull request https://github.com/envoyproxy/envoy/pull/19180

**Comment by VillePihlava** [comment]
@jmarantz @ggreenway

**Comment by ggreenway** [comment]
This sounds good to me; I like it.
