### ISSUE TITLE
Add Hyperscan regex engine to accelerate regex matching

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#19376]
*Title*: Add Hyperscan regex engine to accelerate regex matching

*Description*:

[Hyperscan](https://www.hyperscan.io/) is a high-performance multiple regex matching library. Hyperscan uses hybrid automata techniques to allow simultaneous matching of large numbers of regular expressions, as well as matching of regular expressions across streams of data.

Hyperscan takes more time in compilation but runs considerably faster in matching. Azure chooses the optimized regex engine in performance sensitive scenarios of WAF, reducing latency for about 14.9x in high processing heavy volume attack scenarios.

We believe Hyperscan can be adopted in scenarios like IPS/IDS and WAF, and we are working on bringing Hyperscan into Envoy. There is an open which we would like to get feedback on:

- How we bring Hyperscan to Envoy. We can
    1. Add a regex engine into the current regex message directly. This method is the simplest one but has less flexibility and may cause some run-time issues since Hyperscan is only compatible to x86 servers.
    2. Extend the regex interface to support any engine with a typed config. This way requires invasive changes.
    3. Introduce a new regex matcher which supports pluggable engines. We have to migrate from the original regex matcher to the new matcher when it is possible.
    4. Introduce a global option in the bootstrap message which is similar to the `default_socket_interface`, then we can follow the configuration to populate all regex matchers. This breaks per regex granularity but simplifies implementation.

In my perspective, the second option looks natural, and I am working on it in #19168. I would like to hear some suggestions and advices from the community, and which method is better in the long run.

*Relevant Links*:

[Hyperscan: A Fast Multi-pattern Regex Matcher for Modern CPUs](https://www.usenix.org/conference/nsdi19/presentation/wang-xiang)
[Regex Set Scanning with Hyperscan and RE2::Set](https://www.hyperscan.io/2017/06/20/regex-set-scanning-hyperscan-re2set/)
[Optimize Azure cloud security with Intel Hyperscan](https://www.hyperscan.io/2020/09/28/optimize-azure-cloud-security-with-intel-hyperscan/)

**Comment by yanavlasov** [comment]
The second option is only needed if you want to support use case where different regex pattern use different engines. If you want to allow engine selection for all patterns than option 3 or 4 would work best. 

For simplicity I would suggest first implementing option 4.

It would also be good to add some benchmarks for each engine type. I'm unsure what patterns to use, but I think the more important variable is the length of input. I think we should at least test up to 64Kb.
