### ISSUE TITLE
Linked packet capture feature as the same with Netscaler/BigIP

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#19375]
Current the hardware load balancer (HLB) such as Netscaler/BigIP provide the linked packet capture functionality to make the packet capture more convenient. It mainly solves two pain points when we do packet capture.
 

1.  If you set the filter with client IP and VIP, it can capture all the packets from client to vip and also from LB to all upstream servers. So we can get a full picture about the whole stream.

2. Several clients-to-vip connections map to one connection from LB to upstream server. So there should be a way to show the relationship between the packet from client to vip and the packet from LB to backend server.

 I have a solution for  envoy as a software load balancer (SLB). There are two parts of work. One is for envoy, one is for linux kernel. 

For envoy side, the main works is as follows:

1. Pass the client connection information to the server side connection
2. Add the client port information as the socket ancillary data when envoy sends packet out. 
3. Add configuration to filter which client/VIP should be captured. ()

For kernel side, need recognize the ancillary data added by envoy and add the client port information as TCP option. So when we capture the packet from LB to upstream server, we can know which client connection the packet is from. 

I have done the work  for both envoy and kernel side and it works as expected.  I just want to confirm with community to see whether this kind of envoy PR can be accepted since the feature need some kernel help.  Are there any suggestions for this kind of case which need other software/kernel's co-working.

**Comment by l8huang** [comment]
If I understand it correctly, for packets outgoing to upstream, the ancillary data is downstream source port number. Could you please also elaborate the ancillary data you used in your solution?

**Comment by zhangbo1882** [comment]
> If I understand it correctly, for packets outgoing to upstream, the ancillary data is downstream source port number. Could you please also elaborate the ancillary data you used in your solution?

Yes. Just use the downstream src port as the ancillary data.

**Comment by alyssawilk** [comment]
I think just about anything can go in contrib so you're welcome to put something together there :-)

**Comment by zhangbo1882** [comment]
@alyssawilk , thanks. I will submit a PR for review.
