### ISSUE TITLE
How to configure GrpcJsonTranscoder to not replace accentuation with special characters?

### ISSUE THREAD

**Issue by sudopablosilva** [envoyproxy/envoy#19387]
*Title*: *How to configure GrpcJsonTranscoder to not replace accentuation with special characters?*

*Description*:
>When using GrpcJsonTranscoder as EnvoyFilter, the request response body replaces accentuation with special characters as shown attached. I wonder if there is a way to configure a different charset/encoding.

Find attached the EnvoyFilter configuration for reference
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/87768873/148142411-5dada796-af01-4ee5-bec2-8e38b03ed43d.png">

GRPC request and response
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/87768873/148142524-a839adee-3517-4b9e-9ddd-57337431f94d.png">

Unexpected REST response
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/87768873/148142175-5cb01f50-98aa-4eca-81ed-7928f463765d.png">

**Comment by qiwzhang** [comment]
Per JSON standard,  unitcode has to be escaped in JSON.  Here is my [digging](https://stackoverflow.com/questions/13107329/how-to-handle-unicode-values-in-json-strings/13107892). 

I checked transcoding code [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/internal/json_escaping.cc#L347), I dont see any options to alter this behaviors.
