### ISSUE TITLE
Best way to create a RPM for 1.21

### ISSUE THREAD

**Issue by naaly17** [envoyproxy/envoy#19396]
Hi!

I need a RPM for 1.21, looked at using https://github.com/tetratelabs/func-e/blob/master/USAGE.md, but their latest version is 1.20, I think I can build it if I get the binary? What is the best way to get this?

Or open to any other ideas!

Thank you so much for the help! We use envoy for our production and I need a new feature for 1.21, already late on our release, so need to get everything setup for the official release.

**Comment by phlax** [comment]
i have a very WIP PR to build RPMs altho its blocked by other PRs so im not expecting it to land quickly

it also needs quite a bit of updating

the PR is here https://github.com/envoyproxy/envoy/pull/16899

the current focus for packaging is this https://github.com/envoyproxy/envoy/pull/17979

once debian packaging is setup i will focus on rpm packaging

**Comment by codefromthecrypt** [comment]
@naaly17 sorry about the confusion. The USAGE (both in markdown and the built-in man page) of func-e are examples of how to use commands to list all versions and choose a specific one. The binary isn't pinned to a specific version, rather, its main goal is to allow any version published in [archive-envoy](https://archive.tetratelabs.io/envoy/index.html)

```bash
$ func-e versions -a
* 1.24.1 2022-12-06 (set by $FUNC_E_HOME/version)
  1.24.0 2022-10-19
  1.23.1 2022-08-26
```

Meanwhile, RPMS upstream (here) are the best outcome vs people using func-e to create them ad-hoc.
