### ISSUE TITLE
Add roadmap to Envoy? 

### ISSUE THREAD

**Issue by bryanwux** [envoyproxy/envoy#19419]
Currently, envoy doesn't have a roadmap feature. In terms of project management, I think adding this feature will greatly help maintainers prioritize tasks. Contributors can also find what features they are interested in contributing to more intuitively.

Examples:
[https://github.com/orgs/dapr/projects/52](https://github.com/orgs/dapr/projects/52)
[https://github.com/kubernetes/kubernetes/projects/10](https://github.com/kubernetes/kubernetes/projects/10)

**Comment by alyssawilk** [comment]
Envoy does have a roadmap feature but doesn't use it heavily.  I'm not sure how kubernetes manages but in Enovy Maintainers are generally sponsored by companies and are going to prioritize the tasks their companies want then to work on, and contributors generally are doing the same.

**Comment by tuhao1020** [comment]
@alyssawilk Where can we get the envoy's roadmap?
