### ISSUE TITLE
HandleUpstreamSocketFail flakes on windows

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#19430]
[ RUN      ] UpstreamProtocols/ProtocolIntegrationTest.HandleUpstreamSocketFail/IPv4_HttpDownstream_Http3UpstreamBareHttp2
[2022-01-05 14:55:01.580][308][error][quic] [bazel-out/x64_windows-opt/bin/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:3619] Client: Failed writing packet 7 of 33 bytes from 127.0.0.1 to 127.0.0.1:64487, with error code 10009. long_term_mtu_:1250, previous_validated_mtu_:0, max_packet_length():1250, is_mtu_discovery:0

[2022-01-05 14:55:01.580][308][error][quic] [bazel-out/x64_windows-opt/bin/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:3957] Client: Write failed with error: 10009 (Unknown error)

test/integration/protocol_integration_test.cc(3600): error: Value of: response->complete()
  Actual: false
Expected: true
Stack trace:
  00007FF7D22A0A36: (unknown)
  00007FF7D22BA028: (unknown)
  00007FF7D22BA1ED: (unknown)
  00007FF7D22BAC5D: (unknown)
... Google Test internal frames ...

**Comment by alyssawilk** [comment]
ugh, all that debug info and now there's a different test with the same problem:
[ RUN      ] Protocols/DownstreamProtocolIntegrationTest.OverflowDecoderBufferFromDecodeData/IPv4_HttpDownstream_HttpUpstreamBareHttp2
test/integration/protocol_integration_test.cc(3069): error: Value of: response->complete()
  Actual: false
Expected: true
Stack trace:
  00007FF709E850D6: (unknown)
  00007FF709E9E6C8: (unknown)
  00007FF709E9E88D: (unknown)
  00007FF709E9F2FD: (unknown)
... Google Test internal frames ...

unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.

cc @wrowe @soulxu is there something different about event management and socket draining on windows that would explain why we're not doing full reads here?

**Comment by soulxu** [comment]
@alyssawilk the different is windows doesn't support edge triggered event. so we have some emulation for edge triggered event. That is asking the caller to drain all the data from the socket, otherwise the read event will keep send to the envoy, then we got a busy loop. 

It is really late for me now, I can take a look at this tomorrow morning also. Before that, hope those info ^ can help you.

**Comment by soulxu** [comment]
> @alyssawilk the different is windows doesn't support edge triggered event. so we have some emulation for edge triggered event. That is asking the caller to drain all the data from the socket, otherwise the read event will keep send to the envoy, then we got a busy loop.
> 

We will unregister the file event before read data, then we only re-register the file event after no data in the socket, you can see here 
https://github.com/envoyproxy/envoy/blob/b88fd5805118665f748c343dedd97161ca73f116/source/common/network/win32_socket_handle_impl.cc#L119-L124

**Comment by alyssawilk** [comment]
OK, _finally_ got logs for this

key bit

2022-02-01T14:42:29.8260172Z [2022-02-01 14:41:33.793][3532][debug][connection] [source/common/network/connection_impl.cc:138] [C497] closing data_to_write=248 type=2
...
2022-02-01T14:42:29.8298775Z [2022-02-01 14:41:33.793][4204][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C496] read error: An existing connection was forcibly closed by the remote host.

we generally flush-close, but my guess is that windows doesn't have the "process data ahead of errors" magic, and so picks up the disconnect without doing the read.  Meanwhile delayed_close_timeout was set to 100 nanos, which rounds down to 0s without any sort of warning. (cc @envoyproxy/api-shepherds for that lovely behavioral characteristic)

I suspect we can fix this by upping the flush close timeout.  We'll see if it breaks anything else.
