### ISSUE TITLE
Add local ratelimit example

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#19438]
*Title*: *Add local rate limit example*

*Description*:
Now we have [an implement](https://github.com/envoyproxy/ratelimit) for global rate limit, but no examples for local rate limit.

I want to add one under the sandbox in the doc web if possible.

**Comment by phlax** [comment]
sounds like a good plan, i would be happy to review

**Comment by daixiang0** [comment]
Fixed by #19471
