### ISSUE TITLE
Why the official example cannot serve as http2 edge proxy?

### ISSUE THREAD

**Issue by jiangdongzi** [envoyproxy/envoy#19451]
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#configuring-envoy-as-an-edge-proxy

I use the example configuration and curl the envoy, and always show http1.1 header.
![image](https://user-images.githubusercontent.com/17529657/148671160-9e400771-98a1-4266-b6fe-e30f0ee54870.png)

and below is my configuration almost the same as official example configuration.

![image](https://user-images.githubusercontent.com/17529657/148671245-01077b90-f33a-4d5f-a4c5-2d17f1c2faf2.png)

**Comment by jiangdongzi** [comment]
@alyssawilk , sorry, but does the envoy doc need update?

**Comment by alyssawilk** [comment]
Can you dump logs from curl -v?

I see 
*   Trying 127.0.0.1:10443...
* Connected to localhost (127.0.0.1) port 10443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1

which looks like it's offering HTTP/2

**Comment by jiangdongzi** [comment]
> Can you dump logs from curl -v?
> 
> I see
> 
> * Trying 127.0.0.1:10443...
> * Connected to localhost (127.0.0.1) port 10443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> 
> which looks like it's offering HTTP/2

Sorry, I found my error.  the `”` in my alpn_protocols configuration is wrong,  it should be `"`.  But I think the official example need update,  as there is no `alpn_protocols` filed,  and in this condition it cannot serve as http2.  If adding this configuration correctly, envoy can serve as an http2 edge proxy.  

![image](https://user-images.githubusercontent.com/17529657/148884634-560ebedb-f716-4bd4-aa51-58c49ce78eed.png)

Without alpn_protocols, curl -v gives `ALPN, server did not agree to a protocol`. and only serve as http1.1 edge server. At least from my test.

**Comment by alyssawilk** [comment]
huh, reading the docs it does look like that should be set.  I wonder how or why it worked in the past?  I'll add it in, and thanks for the report!
