### ISSUE TITLE
Invoking external authorization on grpc protocol selectively based on certain headers

### ISSUE THREAD

**Issue by keshavprasadms** [envoyproxy/envoy#19453]
Hi there,

Is it possible to invoke the external authorization grpc endpoint based on certain headers and skip the auth check if header is missing?

I am using OPA as external authorization service on grpc protocol. I want to invoke this auth check only if I receive headers which contains `Content-Type: application/json` since I am performing checks in OPA only on json contents.

Now if I get binary contents I want to skip the checks (`Content-Type: application/octet-stream`). Is it possible to do this currently in envoy?

**Comment by alyssawilk** [comment]
cc @esmet @gsagula @dio

**Comment by esmet** [comment]
I think one way to do this is to create a specific route that uses header matching. Then, configure that route to skip authorization checks.

**Comment by keshavprasadms** [comment]
I would want to route all traffic (prefix as `/` ) to the authorization service. There are some routes which can accept multiple type of payloads (json, binary, URL etc). And also adding multiple urls would be difficult to maintain in long run. I will give it a try to see if header matching works for my situation or not. If there is any other way, please let me know. Not sure if using lua filters will work ot not.
