### ISSUE TITLE
Allow disabling connection pooling and use 1:1 connection with upstream and downstream

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#19458]
*Title*: Allow disabling connection pooling and use 1:1 connection with upstream and downstream

*Description*:
It would be great to have an option (on cluster?) to allow HTTP proxying to follow connection properties like tcp_proxy. That is:
* When downstream opens a connection, we open a connection to upstream.
* We never share an upstream connection with multiple downstream connections, and the reverse
* If the upstream closes, so does the downstream, and the reverse.

Example motivating use case: https://github.com/istio/istio/issues/36768

Basically the proxy captures 100% of traffic. We have some known services where we do special routing for, but for the rest we passthrough with an ORIGINAL_DST cluster. The problem is that uses see unexpected behavior because the connection pooling in Envoy. The most common I have seen is when the upstream is doing DNS load balancing. Because Envoy is keeping the downstream connection alive and sending 503s, the user's HTTP client will re-use the connection and not retry DNS, so it will be stuck failing forever getting 503s.

Alternatives considered:
* Use a tcp_proxy. Unfortunately, we don't know which destination will be used until we process HTTP, so we need to send it through HCM.
* Close downstream connection only when Envoy cannot connect to upstream. This is like a subset of above which would probably fix some issues but not all

**Comment by alyssawilk** [comment]
Can you comment a bit more about how this differs from setting max_requests_per_connection to 1?

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-max-requests-per-connection

**Comment by howardjohn** [comment]
Yes, the difference is we want the downstream/upstream to explicitly control connection handling, not Envoy.
 For example, consider this client:
```
con := connect(example.com)
con.sendReq()
con.sendReq()
con.disconnect() # this should be propagated to upstream
```

`max_requests_per_connection` will result in 2 different upstream connections. With this proposal, there would be 1 single connection.

**Comment by alyssawilk** [comment]
ah, totally makes sense.  I think this is a dup of https://github.com/envoyproxy/envoy/issues/12370 then?

**Comment by fatedier** [comment]
@alyssawilk I'm not sure if #12370 is already completed and solve this issue. 

`connect_pool_per_downstream_connection` flag is added to the cluster config to use a separate connection pool for every downstream connection. But if the upstream connection closes, the downstream still won't.

#12370 is not active for 14 months. Is there any more develop plan?

**Comment by alyssawilk** [comment]
It's not complete, it just has more explanation and discussion so better to have that tracking the desired feature.
AFIK no one is actively working on it.  If your company has a need for it it'd be great for you to pick it up!

**Comment by fatedier** [comment]
> It's not complete, it just has more explanation and discussion so better to have that tracking the desired feature. AFIK no one is actively working on it. If your company has a need for it it'd be great for you to pick it up!

I'd love to but am not familiar with c++.

**Comment by lambdai** [comment]
@alyssawilk Can you reopen this? 1 downstream conn with 1 upstream conn pool does not fully resolve the problem.

We need to convert some of the upstream failure (e.g. connect failure) into a downstream connection error. 

This behavior may not make sense for all cluster types, but it align with the original_dst cluster as upstream

**Comment by kyessenov** [comment]
I think we can narrow it down to a specific problem: ORIGINAL_DST (IP-based) HCM should be able to appear transparent at L4, by propagating the connection events downstream. This is because the common usage for ORIGINAL_DST is to avoid any upstream decision making by Envoy so there is no need for Envoy to manage upstream connections. This can be used, for example, to collect pure L7 telemetry for all L4 using inspection and a more "lenient" HCM filter.

**Comment by Fishrock123** [comment]
Would it be possible to instead of having a 1:1 connection for every request, create a new backing connection + retry when a 503 is encountered?

That kind of middle option seems like it would have most of the benefit without having a dramatic performance reduction.

**Comment by ramaraochavali** [comment]
> This is solved by connection_pool_per_downstream_connection

@howardjohn  Is the downstream connection closed if upstream closes the connection allowing the downstream to re-resolve dns?

**Comment by howardjohn** [comment]
> @howardjohn Is the downstream connection closed if upstream closes the connection allowing the downstream to re-resolve dns?

I think so? we should double check

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/issues/19458#issuecomment-1009653805 - based on this I think the DNS re-resolution wont happen.

**Comment by howardjohn** [comment]
> [#19458 (comment)](https://github.com/envoyproxy/envoy/issues/19458#issuecomment-1009653805) - based on this I think the DNS re-resolution wont happen. We need to test it though

:thinking: how could the downstream not?? Does that mean if the upstream closes we just end up 503ing forever...? Definitely needs some testing

**Comment by kyessenov** [comment]
I'm pretty sure the current logic doesn't couple connection events between upstream and downstream.

**Comment by AmitKatyal-Sophos** [comment]
This configuration should fix the NTLM authentication problem, right?
https://github.com/envoyproxy/envoy/issues/21543

**Comment by hellojaewon** [comment]
> This is solved by connection_pool_per_downstream_connection

@howardjohn 
Does connection_pool_per_downstream_connection option satisfies your third requirement?
> If the upstream closes, so does the downstream, and the reverse.

I thought if downstream connection is closed then the corresponding upstream connection will be closed immediately. However, the upstream connection seems to be closed after idle_timeout. Maybe https://github.com/envoyproxy/envoy/issues/37617 is the same issue.

**Comment by howardjohn** [comment]
Sounds like https://github.com/envoyproxy/envoy/issues/37617 which seems like just a bug. There is no point in keeping a connection open if its guaranteed to never be used again.

**Comment by hellojaewon** [comment]
> Sounds like #37617 which seems like just a bug. There is no point in keeping a connection open if its guaranteed to never be used again.

I read PR in https://github.com/envoyproxy/envoy/pull/12812. Although I'm not accustomed to read envoy codebase, I couldn't find any code that handle the socket close event for both upstream and downstream connection.

And as @kyessenov said, current logic doesn't couple connection between upstream and downstream. 

> I'm pretty sure the current logic doesn't couple connection events between upstream and downstream.

So, the behavior is not a bug. It's intended.
I tested envoy 1.28.0 and latest(1.32.3) and the result was same.

My question is that, if this is intended what can I do further? In our usecase, this is very important functionality.

May I open a new Issue?

**Comment by SCLogo** [comment]
I think we are facing this kind of issue with istio and spot instances. sometimes on node termination I see the URX/UF flag on upstream proxy. Few packets arrive after the app started the graceful shutdown. will this `connection_pool_per_downstream_connection` solve the issue?
