### ISSUE TITLE
Add Hyperscan input matcher to accelerate regex matching

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#19472]
*Title*: Add Hyperscan input matcher to accelerate regex matching

*Description*:

[Hyperscan](https://www.hyperscan.io/) is a high-performance multiple regex matching library. Hyperscan uses hybrid automata techniques to allow simultaneous matching of large numbers of regular expressions, as well as matching of regular expressions across streams of data.

In the previous discussion of #19168 and #19376, we think it would be appropriate to introduce Hyperscan as an input matcher which can be plugged into the matcher API directly.

I have performed a benchmarking use the same method [comparing RE2 with std::regex](https://github.com/envoyproxy/envoy/blob/main/test/common/common/re_speed_test.cc) in my i9-9980HK, and the result shows that Hyperscan matcher reaches nearly a 50% performance improvement compared with the default regex matcher.
```
---------------------------------------------------------------------
Benchmark                           Time             CPU   Iterations
---------------------------------------------------------------------
BM_CompiledGoogleReMatcher        369 ns          368 ns      1963625
BM_HyperscanMatcher               244 ns          244 ns      2846760
```

**Comment by rojkov** [comment]
Sounds promising. I'd sponsor the extension.

**Comment by KfreeZ** [comment]
Will there be any doc changes for this enhancement?
