### ISSUE TITLE
Is there an easy way to transfer config_dump from running envoy to static configuration?

### ISSUE THREAD

**Issue by jiangdongzi** [envoyproxy/envoy#19499]
Our production config largely from dynamic configuration. I want to debug in my local machine.  Now my method is to extract the config manually. For example, I copy the dynamic_listeners to static config and route the same way.

**Comment by alyssawilk** [comment]
Not that I know of. cc @htuch @adisuissa

**Comment by phlax** [comment]
i dont think there is but it would be an interesting tool, im thinking there would be a few variable involved in how the runtime config was interpreted as static in the general case

**Comment by adisuissa** [comment]
Also note that the config dump may not cover all fields, for example for endpoints we rebuild the contents [here](https://github.com/envoyproxy/envoy/blob/b38f7ea5088fdd239cf2fd4379c776ccd7d1a949/source/server/admin/config_dump_handler.cc#L294).

**Comment by htuch** [comment]
I have some vague recollection that Istio built a tool like this. @kyessenov @mandarjog do you know?
