### ISSUE TITLE
external authorization adding data to body

### ISSUE THREAD

**Issue by javid-dastgoshadeh** [envoyproxy/envoy#19496]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *external authorization adding data to body*

*Description*:

Recently, we have been working on a decoupled access control mechanism for backend applications deployed on Kubernetes. Our solution is based on OPA and Envoy and the main goal is to fully decouple access control logic from beckend. This mechanism controls the access to resources on three different levels including action, resource and instance (ex. DB rows). Controlling access to actions and resources can be effectively done with Envoy external authorization paired with allow response from OPA but in order to control access to DB rows, we need to add extra data to the original request so that the backend application can include this data in DB queries. 
OPA documentation has clear guidance for this case in the following link: 

https://www.openpolicyagent.org/docs/latest/envoy-primer/#example-policy-with-object-response

Our initial assumption was to enrich original request body based on the data received from OPA and send the enriched request to upstream service. We tried different configurations and Rego files but none of them resulted in an enriched request being received to the upstream service. 
As a result, we carefully studied Envoy documentation and found the following links: 
 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-queryparameter
 
It appears that enriching body is only possible for downstream services with only string values and Envoy offers limited functionality regarding manipulation of original request. Also, it is clearly mentioned in Envoy document that we can set additional query parameters and headers for upstream. This solution also has its own limitations including adding too many values in query parameters and adding array data. 
We would appreciate your time and would be glad if you help us come up with a suitable solution and also give us more information in case we have missed something.

**Comment by alyssawilk** [comment]
cc  @esmet @gsagula @dio

**Comment by dio** [comment]
@javid-dastgoshadeh how about leveraging https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter here? cc. @gbrail
