### ISSUE TITLE
envoy.reloadable_features.grpc_bridge_stats_disabled deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#19503]
Your change #16284 (grpc: block stat collection in grpc bridge filter with runtime) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by giantcroc** [comment]
Hi, I have done it. 
#19627
