### ISSUE TITLE
postgres: Support StartTLS upstream and plain-text downstream

### ISSUE THREAD

**Issue by terorie** [envoyproxy/envoy#19527]
*Title*: *Allow Postgres proxy to upgrade unencrypted downstream connection into encrypted upstream connection*

*Description*:

The PostgreSQL filter supports TLS termination: https://github.com/envoyproxy/envoy/pull/14634 In this mode, it accepts an encrypted client connection (downstream), strips TLS, and creates an outgoing unencrypted connection to the SQL DB (upstream).

Conversely, it should support the opposite where Envoy accepts unencrypted (`sslmode=disable`) Postgres connections, adds StartTLS on top, and dials securely to the upstream.

This is particularly useful for Google Cloud SQL which enforces the use of client certificates.
Unfortunately a few Postgres clients (such as Rust's `tokio-postgres`) don't support client certs.
So a service proxy is required to establish a secure connection.
(Google Cloud SQL specifically provides the `cloud_sql_proxy` tool for this reason but obviously Envoy is a preferred choice given its maturity)

Defining a `starttls` transport socket on the `cluster` config in Envoy v1.21 results in surprising behavior.
When making an insecure connection to Envoy, the Postgres filter will just pass through the connection attempt to the upstream without attempting to upgrade the socket into TLS mode.

*Proposed fix*:

* Introduce a new `upstream_sslmode` string that mirrors the available PostgreSQL `sslmode` settings.
* When `upstream_sslmode` is defined, send that to the upstream instead of the `sslmode` specified by the client.
* When `upstream_sslmode` is `prefer`, `require`, `verify-ca`, or `verify-full` and the downstream connection is unencrypted, initiate an upstream StartTLS upgrade.

*Useful links*:

- PostgreSQL SSL: https://www.postgresql.org/docs/9.1/libpq-ssl.html
- Google Cloud SQL SSL settings: https://cloud.google.com/sql/docs/postgres/configure-ssl-instance#client-certs
- Google `cloud_sql_proxy`: https://github.com/GoogleCloudPlatform/cloudsql-proxy

**Comment by alyssawilk** [comment]
cc @fabriziomello @cpakulski @dio

**Comment by cpakulski** [comment]
Seems that there is demand for this feature. I will try to implement this.

**Comment by fabriziomello** [comment]
@cpakulski doing that we'll loose the ability to decode the protocol and expose metrics. We introduced starttls into Postgres filter to terminate the SSL and able us to decode the protocol even for encrypted client connections.

**Comment by terorie** [comment]
@fabriziomello I would disagree here – Envoy can also dial to HTTPS upstreams while still being able to expose HTTP metrics.

**Comment by cpakulski** [comment]
Correct. Encryption happens in the very last step, when packets are sent upstream. Postgres filter will see traffic in clear-text.

**Comment by fabriziomello** [comment]
@cpakulski hmmm ... I was not aware of that. Thanks to you and @terorie for the clarification.

**Comment by glebarez** [comment]
indeed there's a need for this.
I stumbled upon this ```Postgres STARTTLS``` thing while trying to get nginx to do the subject.

**Comment by hobbytp** [comment]
Glad to hear that, the related istio issue is here: https://github.com/istio/istio/pull/37290, seems only after this envoy issue fixed, the istio can support postgresql in upstream/cluster part.

**Comment by sha-rath** [comment]
I'm very much interested in this feature as well. Do you have any further updates on this @cpakulski ?
