### ISSUE TITLE
Is there a way to specify cipher suites for TLS 1.3

### ISSUE THREAD

**Issue by linwuz-db** [envoyproxy/envoy#19548]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Is there a way to specify cipher suites for TLS 1.3?*

*Description*:
> According to https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto, cipher_suites parameter is ignored when negotiating TLS 1.3. Is there a way to configure cipher suites for TLS 1.3? Specifically, I want to forbid using TLS_CHACHA20_POLY1305_SHA256. 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by moderation** [comment]
I'll leave this for the TLS experts however my understanding is that the cipher's for TLS 1.3 are not configurable by design. I recall a discussion with @PiotrSikora where he confirmed that specifying cipher suites like below would be ignored in TLS 1.3
```
"tls_params": {
    "cipher_suites": [
        "[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]",
        "[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]",
        "ECDHE-ECDSA-AES256-GCM-SHA384",
        "ECDHE-RSA-AES256-GCM-SHA384"
    ],
    "tls_maximum_protocol_version": "TLSv1_3",
    "tls_minimum_protocol_version": "TLSv1_2"
},
```

**Comment by PiotrSikora** [comment]
Correct, TLS 1.3 ciphersuites in BoringSSL are hardcoded (see:  [BoringSSL's ssl.h#1496](https://boringssl.googlesource.com/boringssl/+/f7975703204c738144990efb8406eee0668fbf2e/include/openssl/ssl.h#1496)).

OpenSSL added `SSL_set_ciphersuites` to configure TLS 1.3 ciphesuites, but that API is missing in BoringSSL. cc @davidben 

It's a good question regarding TLS 1.3 and `TLS_CHACHA20_POLY1305_SHA256`. Perhpas we shouldn't have allowed TLS 1.3 in FIPS builds and the default maximum supported version was incorrectly changed from TLS 1.2 to TLS 1.3 in #12114?

@agl do you have any thoughts on that?

**Comment by linwuz-db** [comment]
It will be great for BoringSSL to provide the API to configure TLS 1.3 ciphersuites just like OpenSSL. It's ok for us to allow TLS 1.3 in FIPS builds and we could manually set the maximum TLS version to TLS 1.2 if it's really needed.

**Comment by visweshn92** [comment]
Hi,

Re-opening to get traction on this ticket.

@PiotrSikora / @agl : Could you confirm the possibility of removing TLS_CHACHA20_POLY1305_SHA256 in the FIPS build? Or allowing a way to configure the TLS 1.3 ciphers?

**Comment by PiotrSikora** [comment]
BoringSSL recently added [`SSL_CTX_set_compliance_policy(ssl_compliance_policy_fips_202205)`](https://boringssl.googlesource.com/boringssl/+/451ea3ca3e0b61273333162564f16d190f6b6d14), which does exactly that, but it won't be available in FIPS builds until BoringCrypto `fips-20220613` is validated, which might take up to a year.

**Comment by visweshn92** [comment]
@PiotrSikora Could you clarify the need to wait for new validation? Looks like the diff touched only the ssl-related files and not anything under `crypto/fipsmodule`, so can we just consume the latest BoringSSL reusing the previously validated BoringCrypto?

**Comment by PiotrSikora** [comment]
I'm absolutely not an authoritative person on the topic, but my conservative interpretation of FIPS validations is that you must use the specific commit SHA that has been validated.

Also, BoringCrypto is the name used for FIPS validated version of BoringSSL, but it's the same library, so you cannot use crypto bits from 2019 with TLS bits from 2022.

**Comment by Slach** [comment]
@PiotrSikora could you suggest, how to watch validation status `fips-20220613` BoringCrypto?

**Comment by agl** [comment]
> could you suggest, how to watch validation status fips-20220613 BoringCrypto?

See [NIST's page](https://csrc.nist.gov/Projects/cryptographic-module-validation-program/modules-in-process/Modules-In-Process-List) and search for "BoringCrypto".

**Comment by reedloden** [comment]
> @PiotrSikora could you suggest, how to watch validation status `fips-20220613` BoringCrypto?

https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4407

`fips-20220613` is https://boringssl.googlesource.com/boringssl/+/853ca1ea1168dff08011e5d42d94609cc0ca2e27

The "Software Versions" on the certificate lists `853ca1ea1168dff08011e5d42d94609cc0ca2e27`

**Comment by visweshn92** [comment]
@reedloden I believe the `fips-20220613` certification won't be sufficient to actually use any of TLS 1.3 ciphers to claim FIPS. 

Although `SSL_[CTX_]_set_compliance_policy` is available in the branch, it looks like the actual TLS 1.3 KDF commit into fipsmodule made after that branch cut https://boringssl.googlesource.com/boringssl/+/480344d4fa03319efa29cdca41f051c41f5bf95a.

**Comment by wiegandf** [comment]
Is it correct that with https://boringssl.googlesource.com/boringssl/+/451ea3ca3e0b61273333162564f16d190f6b6d14%5E%21/ it would be possible to specify the cipher suites for TLS 1.3?

If yes, could this issue be reopened @PiotrSikora ?

**Comment by kyessenov** [comment]
It's already implemented, see `compliance_policy` field on TLS context.

**Comment by wiegandf** [comment]
Thank you @kyessenov  - I think I misread this change as I thought it's a solution for the initial issue. 

The issue about not being able to specify the cipher suites for TLS 1.3 is not only about FIPS - which would be solved with the compliance polices.

It's also to support some national regulatories like the KSA National Cryptographic Standards: https://nca.gov.sa/ncs_en.pdf that only allow TLS_AES_256_GCM_SHA384 with TLS 1.3.

**Comment by kyessenov** [comment]
@wiegandf I think the compliance policy is meant for that, e.g. there would be "KSA standard" option, but it would require boringssl to implement such support. TLS 1.3 does not directly allow changing "required" cipher suites per RFC.
