### ISSUE TITLE
envoy.reloadable_features.http2_new_codec_wrapper  log spamming when true

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#19544]
reported on slack (https://app.slack.com/client/T5CALEVRN/threads/thread/CKQ2LK23G-1642102812.002100)

Hi, we see large volume of errors like [2022-01-13 20:16:40.391][299][error][quic] [.../external/com_github_google_quiche/quiche/http2/adapter/callback_visitor.cc:72] OnConnectionError not implemented since early Dec. 2021.  A quick looking back to change history shows a QUICHE sync back to Nov.

Started 12/2 right after an upstream sync containing the QUIC version bump

**Comment by birenroy** [comment]
It's a spurious log line, we'll remove it.

**Comment by birenroy** [comment]
I've removed both of those log lines in the upstream code. You should no longer see them after the next Envoy import.

**Comment by biefy** [comment]
Thank you for the quick response and fix.
