### ISSUE TITLE
Controlling the timing for Listener socket to bind to the port to simulate Connection Failure in integration tests

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#19553]
Related with https://github.com/envoyproxy/envoy/issues/19501.

This is a proposal for a change to manually control when ListenerSocket is actually bound to a port and listened to. The reason we need this feature is that we want to simulate a Connection Failure in our integration tests by initially assuming that the Listener and port are not actually bound.
If there is a more efficient way to do this, or if there is an integration test that already implements this, please let me know.

**Comment by alyssawilk** [comment]
Sorry if I'm not understanding the request, but any reason to just not start up the Envoy instance if you want a connection failure?

**Comment by Shikugawa** [comment]
Since we want to test the request from Envoy to Upstream, Envoy needs to be up and running, and the number of clusters of BootStrap config and FakeUpstream needs to match when `BaseIntegrationTest::initialize()` is called. So it is impossible to not launch FakeUpstream that we want to simulate Connection Failure.
Therefore, it is necessary to create a state in which FakeUpstream is launched and Listener and Port are not bound.
There is a disable option for Listener, but I don't think we can call disable from a test thread.
