### ISSUE TITLE
ExtAuthz: HttpRequest id field seems to be integer instead of UUID

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#19551]
*Description*:
From the Envoy docs for [service.auth.v3.AttributeContext.HttpRequest](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto.html#envoy-v3-api-msg-service-auth-v3-attributecontext-httprequest)

The `id` field is described as follows:

> The unique ID for a request, which can be propagated to downstream systems. The ID should have low probability of collision within a single day for a specific service. For HTTP requests, it should be X-Request-ID or equivalent.

However, in an example setup I have noticed that the id is a string of digits, such as `"11351951127518978566"`, rather than what `X-Request-Id` is meant to be (a UUID).

It is entirely possible that I'm configuring something wrong in the listener/HCM? I've looked it over a few times now..

I'm using Envoy v1.19.0

*Repro steps*:
I've created a repository here which should reproduce the issue on any machine:
https://github.com/cetanu/extauthz_request_id_repro

Specific links:

* [Envoy config](https://github.com/cetanu/extauthz_request_id_repro/blob/main/containers/envoy.yaml)
* [External Authorization logic](https://github.com/cetanu/extauthz_request_id_repro/blob/main/src/main.rs#L43-L50), just prints the id

**Comment by alyssawilk** [comment]
cc  @esmet @gsagula @dio

**Comment by cetanu** [comment]
I was notified about this issue by a colleague of mine, I let it go stale but I believe it's still relevant and could be a low-hanging fruit for a new contributor
