### ISSUE TITLE
downstream connection maps to wrong upstream connection

### ISSUE THREAD

**Issue by lxv458** [envoyproxy/envoy#19566]
*Title*: *downstream connection maps to wrong upstream connection*

*Description*:
Recently, I got some extraordinary access logs, such as 503LR with short duration and 200/403 with long duration.
Thus, I change the log level to trace and found something interesting.

I doubt that the mapping of downstream and upstream is incorrect or disordered. That is to say, the downstream connection D1 waiting for upstream connection U1 connected, but during the waiting period, about 8 seconds later, downstream connection D2 (withs same url) created an upstream connection U2 which connected successfully. 
Here comes the magic! D1 thinks U2 is for itself, so D1 use U2 to complete its request, which results in 200/403 with long duration. Hence, D2 has to use U1 which returns *connect timeout* and returns 503 LR with short duration.

I want to know **whether this behavior is correct, or is there something I misunderstand?**

Here is part of the accesslog, proxy log and figure.
[2022-01-14T05:25:00.131Z] "GET /v1/m/xxxx HTTP/1.1" 403 - "-" 0 13 8488 - "10.16.7.66" "xxxx" "5_TCLbiL" "100.xx.xxx.193" "10.17.33.63:9082" outbound|9082|v2|a.m.svc.cluster.local 10.17.40.26:34058 10.17.40.26:1443 10.16.7.66:24360 100.xx.xxx.193 -

[2022-01-14T05:25:08.603Z] "GET /v1/m/xxxx HTTP/1.1" 503 LR "-" 0 84 1529 - "10.16.6.62" "xxxx" "JdD4Mtb6" "100.xx.xxx.193" "10.17.33.63:9082" outbound|9082|v2|a.m.svc.cluster.local - 10.17.40.26:1443 10.16.6.62:24360 100.xx.xxx.193 -

![accesslog](https://user-images.githubusercontent.com/11827241/149729628-e30b57a8-9918-4940-a543-8a8d8fd3782e.PNG)
![description](https://user-images.githubusercontent.com/11827241/149729644-14e5c99d-2e37-46dc-9da7-67d007184204.PNG)

Here is the figure showing the mapping of downstream connections and upstream connections, which I drew as I understood.
![conn](https://user-images.githubusercontent.com/11827241/149729659-9158f96d-e154-4004-a012-273e0944fa13.PNG)

**Comment by lizan** [comment]
Upstream and downstream connection are not 1:1 mapped in HTTP connection manager so this might happen. The problem is U1 exceed connection timeout which is irrelevant to which downstream connection it maps to. So you might want to adjust timeout for the upstream cluster.

**Comment by lxv458** [comment]
@lizan Yes, you're absolutely right.
After going through the code of envoy, we also verify the conclusion of downstream and upstream are not exact match.

Now, we are indeed digging into the truth of why connect timeout.
We observed that the server envoy did not answer SYN ACK after receiving SYN, but we don't know why.............
The next request is answered correctly.
Do you have any ideas?

Here is the tcpdump results.
![1](https://user-images.githubusercontent.com/11827241/150458491-7a89f48f-9404-42fd-a75d-c1d70c567744.png)
