### ISSUE TITLE
No stack info when use admin API cpuprofiler.

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#19565]
I complie envoy use centos7.2,and collect the cpuprofiler with admin api(curl -X POST localhost:15000/cpuprofiler?enable=y).But thers is no stack info about envoy.
Here is the output.
```
File: envoy
Type: cpu
Showing nodes accounting for 10ms, 100% of 10ms total
      flat  flat%   sum%        cum   cum%
      10ms   100%   100%       10ms   100%  [envoy]
         0     0%   100%       10ms   100%  [libc-2.17.so]
```
I have builded envoy with no strip ,and even complie dwp file in pprof work directory.
Any help will be appreciated!!

**Comment by lizan** [comment]
https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md#collecting-cpu-or-heap-profile-for-a-full-execution-of-envoy

Did you build Envoy with `--define tcmalloc=gperftools`?

**Comment by pyrl247** [comment]
Yes，I have define tcmalloc=gperftools,or the cpuprofiler admin api can not be posted.

**Comment by fxposter** [comment]
I'm facing the same issue, are there any workarounds?
