### ISSUE TITLE
bazel build the http filter with envoy v1.16.0 failed by "execv: Argument list too long"

### ISSUE THREAD

**Issue by xajhljq** [envoyproxy/envoy#19567]
I am trying to build the http filter with envoy v1.16.0 with following commands:
bazel build //http-filter-example:envoy

the result of building is following with gnu7 or gnu9:

gnu7
with bazel "fatal error: cannot execute '/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus': execv: Argument list too long"

gnu9
with bazel "fatal error: cannot execute '/usr/lib/gcc/x86_64-linux-gnu/9/cc1plus': execv: Argument list too long"

Then I try to build the http filter with envoy v1.16.0 with following commands:
(bazel build //http-filter-example:envoy -c dbg) or (bazel build //http-filter-example:envoy -c opt)
It will build successfully, however the binary file size of envoy is too big.

How can I solve this problem in a faster way?

**Comment by lizan** [comment]
What's the `ulimit` of your environment?

**Comment by xajhljq** [comment]
> What's the `ulimit` of your environment?

the default value of "ulimit -s " is 8192. Then I set “ulimit -s 65536”, can't solve this problem yet. How can I solve this problem in another way?
