### ISSUE TITLE
General question about headers

### ISSUE THREAD

**Issue by Edimo24** [envoyproxy/envoy#19587]
Hello,

I need to modify a bit the one specific part of the header (to be more precise a command operator). I think I found the exact line where I can do the changes (already tested) but I want to modify only one command operator and not the whole header.

https://github.com/envoyproxy/envoy/blob/main/source/common/formatter/substitution_formatter.cc#L1194

I see the "val" variable is converted as string so I assume I can directly use replace function but after making a build the ingressgateway and egressgateway pods are not coming up.
My question is what does this header contain? From my understanding it is the default template of command operators.
https://github.com/envoyproxy/envoy/blob/main/source/common/formatter/substitution_formatter.cc#L58

**Comment by Edimo24** [comment]
@phlax

**Comment by phlax** [comment]
im probably not the best person to answer this question - i would suggest asking on the slack dev channel
