### ISSUE TITLE
Add logs to indicate connection loss on downstream TCP and HTTP requests

### ISSUE THREAD

**Issue by sha-rath** [envoyproxy/envoy#19604]
*Title*: *Add logs to indicate connection loss on downstream TCP and HTTP requests*

*Description*:
We have a couple of internal security design rules and one of them suggests including logs for connection loss on downstream TCP and HTTP requests. It may be a suitable indicator for possible security threats. Envoy currently does NOT implement such logs and hence submitting this feature request.

For example, in an Istio service mesh, it should be possible for a user to see the connectivity loss logs between the client and Ingress Gateway. Also, implementing logs to show connection reset and end of idle timeout on downstream could be beneficial. All these logs could be made available at the log level:info.

**Comment by lizan** [comment]
Is the `listener access logs` what you're looking for?

**Comment by sha-rath** [comment]
@lizan Thanks for the quick response.  A small correction in my description...is it possible to include connection loss logs under generic logs and not access logs? (I mean, I prefer to see these logs at the info level without enabling access logging, just like how we see details like envoyproxy is ready etc.)

From our security design rule point of view, it is apparently not advisable to have connectivity loss logs as access logs since these logs are configurable. There seems to be a possibility of it not being caught as a non-audit security log. 

Currently, even with these access logs, downstream connection issues (eg: _DC: Downstream connection termination_) are logged only for HTTP requests and not TCP.

**Comment by sha-rath** [comment]
@lizan @htuch Any opinion on this?

**Comment by htuch** [comment]
Re: connection logs as generic logs, can you just point the access logs at `/dev/stdout` or `/dev/stderr`? I.e. can we just leverage standard Unix paradigms here rather than having Envoy add special case support for sending access logs to the debug log stream?
