### ISSUE TITLE
Fail to create Unix Domain Socket (UDS) cluster using CDS

### ISSUE THREAD

**Issue by spikecurtis** [envoyproxy/envoy#1961]
**Bug Template**

*Title*: Fail to create Unix Domain Socket (UDS) cluster using CDS

*Description*:
Attempting to create an upstream cluster that uses a Unix Domain Socket (UDS) fails when creating it over the CDS. [Envoy Docs](https://www.envoyproxy.io/envoy/configuration/cluster_manager/cluster.html#config-cluster-manager-cluster) suggest UDS should be supported.

However, I get 
```[2017-10-27 22:46:43.892][16][warning][upstream] external/envoy/source/common/upstream/cds_subscription.cc:62] cds: fetch failure: unknown protocol scheme: unix:///var/run/test.sock```

*Repro steps*:
Create an upstream cluster using the `unix://<file_path>` scheme.

I'm fairly confident the culprit is [AddressJson::translateAddress](https://github.com/envoyproxy/envoy/blob/ad9606d32ac375e88555cd8108c7abae89d9fdf8/source/common/config/address_json.cc#L9) failing to correctly handle the `url=true, resolved=false` case.  In that case, it incorrectly assumes the address must be a TCP socket.

I'm happy to knock up a PR.

**Comment by mattklein123** [comment]
I think this should work. It's the same code for CDS and for initial load and we use UDS at Lyft. Are you specifying "static" cluster type vs. DNS? Can you provide the full cluster definition?

**Comment by spikecurtis** [comment]
My cluster looks like this
```
   {
    "name": "test_server",
    "connect_timeout_ms": 5000,
    "type": "strict_dns",
    "lb_type": "round_robin",
    "hosts": [
     {
      "url": "unix:///var/run/test.sock"
     }
    ],
    "features": "http2",
    "circuit_breakers": {
     "default": {
      "max_pending_requests": 10000,
      "max_requests": 10000
     }
    }
   }
```

Changing it to be `"type": "static"` seems to work.  Docs bug/bad error message?

**Comment by mattklein123** [comment]
The docs do indicate that unix:// is only usable for "static" clusters, but perhaps it could be more clear? We could try to make the error message better also but it would take a bit of thinking on how to do that given how the code is structured. If you feel like doing a doc PR for clarity that would be appreciated.

**Comment by mattklein123** [comment]
Fixed
