### ISSUE TITLE
virtual_host/domains: "infix" wildcards?

### ISSUE THREAD

**Issue by acruise** [envoyproxy/envoy#19625]
*Title*: Is there a way to use "infix" wildcards in a virtual_host/domains list? e.g. `foo-*.example.com`

*Description*:
I tried it and it doesn't work, but maybe I'm missing something?

**Comment by lizan** [comment]
It is not supported https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-virtualhost-domains

You might be able to use regex match on `:authority` header with header matcher though.
