### ISSUE TITLE
Close a connection and remove it from the connection pool after a specified "idle time"

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#19626]
*Title*: *Close a connection and remove it from the connection pool after a specified "idle time"*

*Description*:

After a connection is released back to the pool and not reused for a while, close it and remove it from the pool. The time should be set in the cluster configuration.

*Background*

We have some services which will close connections at the server-side if that connection is idle for a short period of time. This behavior caused envoy raise ”ConnectionPool::PoolFailureReason::RemoteConnectionFailure“ errors.

My guess is that the connection has been closed from the upstream side, but the envoy hasn't detected that yet and tried to reuse it.  

If the connection pool can have an "idle time" setting for pooled connections, I can make the idle time shorter than the one in the upstream service and therefore avoid this issue.

**Comment by alyssawilk** [comment]
For HTTP variants, the cluster's protocol config already includes an idle timeout, which I think is what you're looking for.
I don't think there's a config knob for this for TCP proxy sessions, but unless you have prefetching on the connection is only fetched when there's a downstream connection and is closed afterwards so I don't think there has been a need.

**Comment by zhaohuabing** [comment]
@alyssawilk Thanks for the clarification. I'm implementing a custom TCP filter that needs to reuse connections in a connection pool, that's why I raise this question. I'll look into the idle timeout implementation in the HTTP and see if I could do something similar in my custom TCP filter.

**Comment by zhaohuabing** [comment]
@alyssawilk The [online docs](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts) say that both the downstream and upstream connections have an idle time. I went through the code and only found idle time for downstream in the [HTTP connection manager](https://github.com/envoyproxy/envoy/blob/35d18c932a325bf62a67b2d95021a18e0e32d167/source/common/http/conn_manager_impl.cc#L140).  I haven't found idle time out for connections in the upstream connection pool implementation.  The code is complicated, so maybe Envoy does have dile time for pooled connection for upstream somewhere and I just missed it?

**Comment by zhaohuabing** [comment]
Update： Never mind. I found a clue here: https://github.com/envoyproxy/data-plane-api/pull/513
