### ISSUE TITLE
[RFC] Dependency checking in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#19636]
### Description

We are currently landing an integrated `envoy.dependency.check` tool in https://github.com/envoyproxy/pytooling

This will run almost all of the existing dependency checks, fixes some issues, adds some flexibility, and runs much faster by virtue of async preloading of data

This will give us more flexibility about which checks we run where in CI, and will also allow us to integrate the current azp cve scan job into the github job that raises issues for newer releases of dependencies

I would propose that we move towards doing the following in CI:

#### presubmit/dependencies

Run all checks - dont error on warnings.

This will run:
- cves
- dates - this will still error on date mismatch
- releases
- issues

cves, releases, issues will warn when there are CVEs, newer releases, or if the issues need syncing, but wont error

Of the above, currently only dates are checked in current CI.

My local testing suggests that this will be fast/reliable enough, that we can run it in pre-submit, altho it will require at least a read-only github token (i think it may already have this to do the dates check)

The only caveat is that it might introduce transient CI flakes downloading additional data, but tbh i dont think any more so than other parts of CI - so my suggestion would be that we add, and then reconsider if it presents an issue

#### github-action/dependency-checks

This will run with `-werror` :

- cves 

And with the default no-error-on-warning (but actually syncing issues):

- issues

This will reflect the current behaviour as a first step.

### follow up

As a next step, i would suggest that we add functionality to raise a github issue for found CVEs and then we can just run the checker without error-on-warn

**Comment by phlax** [comment]
cc @htuch @moderation @kfaseela

**Comment by htuch** [comment]
What is the distinction between error/warning here? Could we also use required vs. non-required GH checks to do the same?

**Comment by phlax** [comment]
> What is the distinction between error/warning here?

the checkers emit/collect 3 types of result - success, warning, error

if there are any errors - the return code from the checker is >0 - if there are any warnings and `-werror` the return code is >0

> Could we also use required vs. non-required GH checks to do the same?

not sure, but i think this is more to do with the return code of the checker

ie - atm - if the cve scanner finds a failing dep, it errors, and continues to error until someone fixes it (ie bumps dep or excludes cve). My suggestion would be that the checker should not fail, its doing its job correctly and failing often isnt even noticed straight away. Rather i think it should warn (ie emit warning messages) and raise a ticket. Failure should be reserved for an unexpected outcome/transient downloads/software breakage etc

> Basically trying to understand what presubmit/dependencies is gong to give us.

- dates - ensure they match correctly (as it does now if bzl files change)
- cves - report of potential CVEs - one advantage to running it here is that if someone adds a dep it will be checked immediately
- releases - report of latest versions, commits since commit, etc. Again if someone is adding or updating a dep you will see immediately whether it has newer versions, and how out of date it is etc
- issues - a report of what tickets should be opened/closed

ill set up a couple of CI runs shortly to try and exemplify what im describing above

**Comment by phlax** [comment]
So the following would be the initial configuration in Envoy CI, with a couple of exceptions:

- the github job has been hacked to trigger on PR, rather than by cron
- the `issues` check should have `--fix` set to actually sync the release issues

#### github-action/dependency-checks

this is the bazel commands that are run:

```console
.github/workflows/check-deps.yml:          time bazel run //tools/dependency:check -- -c issues  # --fix
.github/workflows/check-deps.yml:          time bazel run //tools/dependency:check -- -c cves -w error

```

and these are the checks it triggers in CI:

https://github.com/envoyproxy/envoy/runs/4896107083?check_suite_focus=true#step:5:143

https://github.com/envoyproxy/envoy/runs/4896107083?check_suite_focus=true#step:5:273

There is a CVE exclude commented out to trigger the CVE error

My ideal with this is that it doesnt error on finding a CVE, but instead creates a ticket - so more like:

```console
.github/workflows/check-deps.yml:          time bazel run //tools/dependency:check -- -c cve-issues -c release-issue --fix
```

Running these checks together will make it faster as they are preloading data, some from different sources.

#### presubmit/dependencies

This just runs all checks, doesnt error on warnings, and doesnt fix anything:

```console
ci/do_ci.sh:  time bazel run "${BAZEL_BUILD_OPTIONS[@]}" //tools/dependency:check

```

The CI run for this can be seen here:

https://dev.azure.com/cncf/envoy/_build/results?buildId=99430&view=logs&j=1c04237c-5f52-5959-5f83-5522b3556331&t=db3f3889-c922-566b-fa2e-4bc4948bc467&l=691

Despite running all checks, its taking ~25s in Envoy CI to run, including setting up the bazel env

**Comment by htuch** [comment]
SGTM, thanks for the explanation.

**Comment by daixiang0** [comment]
It would be perfect to generate a CVE issue by CI, while it may bring repeated alarms :(

**Comment by phlax** [comment]
i think this has been mostly agreed, and implemented, anything remaining is tracked elsewhere
