### ISSUE TITLE
make use of gcompat for glibc in alpine

### ISSUE THREAD

**Issue by chritiene** [envoyproxy/envoy#19643]
The [envoyproxy/envoy-alpine](https://hub.docker.com/layers/envoyproxy/envoy-alpine/v1.21-latest/images/sha256-9e8e3f13bf6132358577370a1faf079779b9bb3077f76e938464db029f65abdc?context=explore) official docker image is using [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) to add glibc.

Why not using [gcompat](https://pkgs.alpinelinux.org/package/edge/community/x86_64/gcompat) which can be installed easily via `apk add gcompat`

**Comment by lizan** [comment]
Have you tried use gcompat instead of glibc? AFAIK using musl comes with performance drop and I'm not sure if gcompat could make fully glibc compatible.

**Comment by chritiene** [comment]
Don't think we stress envoy to a level to notice any performance difference.  First (small) test showed envoy was working with gcompat.

**Comment by moderation** [comment]
My $0.02 - trying to use Alpine which is a musl environment for a binary like Envoy that explicitly requires glibc is not good practice. As it is we use a random Alpine base image - https://github.com/envoyproxy/envoy/blob/main/ci/Dockerfile-envoy-alpine#L1. Should we trust this?

I recommend using the Distroless containers that support glibc natively, come from a trusted source and are similarly very small in size - https://www.envoyproxy.io/docs/envoy/latest/start/install.html?highlight=distroless#pre-built-envoy-docker-images

The plan is to deprecate the Alpine images - https://github.com/envoyproxy/envoy/issues/16275. @phlax I think we can do this now

**Comment by chritiene** [comment]
> The plan is to deprecate the Alpine images

Ouch. I was not aware of that. When does this become effective? We use envoy in combination with some other tools (to set up and update envoy config files) on an Alpine image. Not sure what the impact of using a distroless image is.

> As it is we use a random Alpine base image - https://github.com/envoyproxy/envoy/blob/main/ci/Dockerfile-envoy-alpine#L1. Should we trust this?

Which could be another reason to use an official alpine image and use the gcompat package. 

FWIW we use an official Alpine image and have a similar ~horrible~ elaborate command to pull in glibc as is used in the [frolvlad/alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc/) docker image. The [gcompat](https://pkgs.alpinelinux.org/package/edge/community/x86_64/gcompat) feels much cleaner, hence wondering if that is supported/endorsed.

**Comment by lizan** [comment]
@chritiene You may still build your own image based on Alpine and gcompat and copy Envoy binary from distroless or other official image, all image contain same binary built on Ubuntu container.
