### ISSUE TITLE
How to secure and virtualize database connections with proxies

### ISSUE THREAD

**Issue by yeranosyanvahan** [envoyproxy/envoy#19656]
Hello everyone, I have planned a mysql database consolidation strategy (i.e. bringing databases to one big bulky server) and here lies the problem.  Let's call this server The Big Bulky Database Server  (BBDS)
There are a heck ton of application on my servers and some user postrgesql, mysql5.7, mariadb10 and so on.
To make it simple let's say that each application has a dedicated server with it's database.
Problem: I need to connect every app to BBDS(database server) but I don't want to expose a ton of ports each port for each application to connect to the database specifically for that application with everything.

Supposed solution:  make use of virtual hostnames (similar to virtualhosts in apache), which are done thanks to SNI in TLS. So each request has ServerNameIdentifier with which it figures out that Application A requests A.mysql5.7, which means it needs mysql5.7 server that is hosted to serve for application A.

The problem is that by default the sql client's doesn't connect to sql server with TLS, so encryption is needed.  
Obviously we need 2 proxies. One for encrypting and one for decrypting.
TLS Termination and TLS Origination proxies are perfect for this task. And The documentation confirms that.
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl

Can you please share how can I do that? I couldn't find much about tls origination in the documentation.
Thanks a lot. Open to suggestion (if you have any)

**Comment by lizan** [comment]
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/double-proxy I think this is the example you want to look into?
