### ISSUE TITLE
Add Runtime config API

### ISSUE THREAD

**Issue by nmittler** [envoyproxy/envoy#1967]
*Title*: *Add Runtime config API*

*Description*:
As part of some ongoing work in Istio to support Spring Boot applications using Hystrix circuit breakers, there is a desire to allow the application to override the circuit breaking configuration of it's Envoy instance.

I think to be safe, we'd want to be able to change any of Istio's circuit breaker params:

- cluster.MaxRequestsPerConnection
- cluster.CircuitBreaker.Default.MaxConnections
- cluster.CircuitBreaker.Default.MaxRequests
- cluster.CircuitBreaker.Default.MaxPendingRequests
- cluster.OutlierDetection.MaxEjectionPercent
- cluster.OutlierDetection.BaseEjectionTimeMS
- cluster.OutlierDetection.ConsecutiveErrors
- cluster.OutlierDetection.IntervalMS
- cluster.OutlierDetection.MaxEjectionPercent

*Relevant Links*:
[Related Discussion](https://github.com/envoyproxy/envoy/pull/1935#issuecomment-340227309)
[Istio's circuit breaker params](https://github.com/istio/pilot/blob/master/proxy/envoy/policy.go#L78)

**Comment by mattklein123** [comment]
I suggest handling this via https://github.com/envoyproxy/envoy/issues/514. All of the above settings are currently configurable (or will be with a few minor alterations) via the runtime system built into Envoy. If we had an easy to use admin API which allowed you to query/set runtime keys would that satisfy what you need? Then you could hit the local API via an interceptor.

**Comment by nmittler** [comment]
@mattklein123 whatever you think ... I only raised this issue because you had suggested it.

**Comment by mattklein123** [comment]
@nmittler I'm asking if the above solution will satisfy you. :)

**Comment by nmittler** [comment]
@mattklein123 yeah AFAIK that should work

**Comment by mattklein123** [comment]
OK I'm going to resolve this in favor of #514 as that will solve your issue and is already open.

**Comment by nmittler** [comment]
@mattklein123 SGTM, thanks!
