### ISSUE TITLE
In the /stats/prometheus statistics list is there a method that will allow me to monitor http to grpc transcoded request per endpoint? 

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#19687]
I'm trying to monitor at the envoy level all the http calls per endpoint that are grpc transcoded, but so far I was not able to locate a proper method to do this in the /stats/prometheus list.

This is what I'm using for grpc service, but I want something similar for envoy, if possible 
`sum (increase(grpc_server_processing_duration_seconds_count{namespace=~\"$Namespace\",job=~\"$Service\"}[1m])) by (method)`

Any idea ?

Thanks

**Comment by mattklein123** [comment]
cc @qiwzhang

**Comment by ghevge** [comment]
@qiwzhang any idea? Thanks

**Comment by ghevge** [comment]
I'm still interested in this functionality. Thanks!
