### ISSUE TITLE
Consider necessity of `bazel_buildtools`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#19686]
### description

bazel buildtools - ie `buildozer` and `buildifier` was previously added as a requirement for building docs from the api

this is no longer necessary as the information is taken directly from bazel and/or config files now.

we may wish to remove it as its not used anywhere by CI, otoh we might want to update docs and potentially even the scripts triggered by the git hooks to make use of the bazel loaded version

there are also other possible uses that we may wish to keep or readd this for - eg we could use these tools to auto fix dependency dates or shas, or update other bazel files automatically

if we keep we probably want to move it from `api/bazel/repository_locations.bzl` -> `bazel/repository_locations.bzl`

**Comment by phlax** [comment]
cc @moderation

**Comment by moderation** [comment]
@phlax I'm in favor of removing if we are not using

**Comment by phlax** [comment]
yep, i think me too - i probs want to readd it - but it needs to be moved from where it is - and if its not being used i think there is not point putting it anywhere else just now - ill raise a pr to remove

**Comment by phlax** [comment]
cc @keith 

closing this as we have removed the build tools for now

**Comment by keith** [comment]
If we ever want to revisit this I think we could use something like https://github.com/keith/buildifier-prebuilt/ to make vendoring these trivial
