### ISSUE TITLE
Unable to get internal redirect policy working (docs / examples lacking)

### ISSUE THREAD

**Issue by kdowney-cloudwallcapital** [envoyproxy/envoy#19682]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: internal redirect of 307 bubbles up to browser rather than being handled

*Description*:
We have an Envoy router sitting in front of Consul's UI and two GraphQL-based microservices. (One of them with websockets.) The goal is to make all three services available at different paths in Envoy, e.g. /consul routes to http://localhost:8500/consul. The problem we are hitting is all three issue redirects, e.g. /graphql gets a 307 redirect to /graphql/ when you hit it. The desired behavior is that Envoy will consume this redirect, go to /graphql/ on the microservice, and then return *that* response to the client. The actual behavior observed no matter how I configure internal redirect policies, actions, etc. is that the 307 goes back through Envoy and then the browser tries to go to http://localhost:9900/graphql/, which does not exist.

E.g. I'd expect this would match the 307 and force it to be processed:

                  internal_redirect_policy: {
                    max_internal_redirects: 5,
                    redirect_response_codes: [307]
                  },
                  internal_redirect_action: HANDLE_INTERNAL_REDIRECT

but it's the same whether that policy is set or not. Also note I struggled to find good examples of this anywhere and I saw a lot of questions out there about how to set this up for various scenarios, so some more documentation may be useful.

[optional *Relevant Links*:]
See attached full envoy.yaml

[envoy.yaml.txt](https://github.com/envoyproxy/envoy/files/7934213/envoy.yaml.txt)

**Comment by phlax** [comment]
skim reading your config its not immediately obvious to me what is/not working - im not so familiar with the internal redirect config

if you resolve your problem i would be happy to review any updates to the docs or examples that might make this clearer

**Comment by mattklein123** [comment]
cc @alyssawilk who knows about internal redirects.

**Comment by alyssawilk** [comment]
did you check stats?  If you're hitting the route with internal redirects configured, failures to redirect should get tagged with one of the stats here: https://github.com/envoyproxy/envoy/blob/main/source/common/router/context_impl.h#L18

If that doesn't turn up anything if you could dump trace logs from a single request it may help show what's going on

**Comment by kdowney-cloudwallcapital** [comment]
Thanks Alyssa, I can see the stats now. We found a workaround for the GraphQL issue (a regex rewrite to avoid the trailing slash, and switching away from the embedded GraphiQL tool) and so it's just Consul that's a problem now. Give me a couple hours to play with this and if I figure it out I will add a comment and close. Thanks for the tips!

**Comment by kdowney-cloudwallcapital** [comment]
OK, so I have a bit more information. For one of those cases returning 307, I do see this stat updated:

`cluster.serenity_portfolio_summary_ws.upstream_internal_redirect_failed_total: 2
`

and I also see this, which suggests *why* those two requests failed:

`http.ingress_http.passthrough_internal_redirect_no_route: 2
`

@alyssawilk, what I would like is for a 307 sent back to Envoy to be followed and for it to fetch the new location. Is this possible in the configuration? I would have thought what I have above would do this.

**Comment by kdowney-cloudwallcapital** [comment]
Trace logs you requested for this scenario:

`
[2022-01-26 00:56:10.851][23989][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:24] [C1] read returns: 163
[2022-01-26 00:56:10.851][23989][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:38] [C1] read error: Resource temporarily unavailable
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:555] [C1] parsing 163 bytes
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:834] [C1] message begin
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:475] [C1] completed header: key=date value=Wed, 26 Jan 2022 00:56:10 GMT
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:475] [C1] completed header: key=server value=uvicorn
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:475] [C1] completed header: key=location value=http://localhost:9900/metrics
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:685] [C1] onHeadersCompleteBase
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:475] [C1] completed header: key=transfer-encoding value=chunked
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:1263] [C1] status_code 307
[2022-01-26 00:56:10.851][23989][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:1273] [C1] Client: onHeadersComplete size=4
[2022-01-26 00:56:10.851][23989][debug][router] [external/envoy/source/common/router/router.cc:1244] [C0][S10617589657952339435] upstream headers complete: end_stream=false
[2022-01-26 00:56:10.851][23989][debug][router] [external/envoy/source/common/router/router.cc:1477] [C0][S10617589657952339435] attempting internal redirect
[2022-01-26 00:56:10.851][23989][debug][router] [external/envoy/source/common/router/router.cc:1508] [C0][S10617589657952339435] Internal redirect failed
`

**Comment by kdowney-cloudwallcapital** [comment]
The trace logs seem to match the stats: you can see that it gets the 307 at the top and then in the last line it bails out on the redirect. So I don't think Envoy has a bug; this is a configuration problem our end causing it to not process the redirect.

**Comment by alyssawilk** [comment]
so the internal redirect is supposed to save the round trip between Envoy and Client of  doing the redirect.
If you redirect from /foo to http://loopback.com/bar you still need Envoy to have a route configured for loopback.com/bar, so it knows where to send the request.  The error you send indicates you don't have a route configured for the redirect URL.

**Comment by kdowney-cloudwallcapital** [comment]
OK. I had a hunch that was the case. How is the route expressed? http://localhost:9090/foo/metrics -> http://localhost:9001/metrics/ redirects to http://localhost:9001/metrics. The latter is a *cluster* address. Do I need to put in a match that references localhost:9001? Or is it a match that uses a header? This is why I raised this as a documentation issue: I read the docs and examples and could not find guidance on how to configure this so it works.  Thank you very much for your patience and help.

**Comment by kdowney-cloudwallcapital** [comment]
Also, small thing: it would be nice if the trace actually logged the path that had no route. :-)

**Comment by kdowney-cloudwallcapital** [comment]
OK, I figured out a way to fix our config. It's a bit ugly, but it works! I had to add matching rules that keyed off the x-envoy-original-path header. If it matches the original inbound request path, it kicks the 307 back where it came from.

Thanks for the help, @alyssawilk, the tips helped me find this.

```
              - match: 
                  prefix: "/"
                  headers:
                  - name: "x-envoy-original-path"
                    prefix_match: "/serenity/platform/installation_info"
                route: {
                  cluster: serenity_portfolio_summary_ws
                }
              - match:
                  prefix: "/"
                  headers:
                  - name: "x-envoy-original-path"
                    prefix_match: "/serenity/portfolio/portfolio_summary"
                route: {
                  cluster: serenity_portfolio_summary_ws
                }
```

**Comment by alyssawilk** [comment]
Glad you're set.  You should just be able to match on the new path, but really whatever works :-P
Fair point on the logs - I'll throw together a quick PR to improve that, and close this out if that works for you

**Comment by kdowney-cloudwallcapital** [comment]
Thanks @alyssawilk, closing this issue now. Matching on new path would work too, but I had to do it this way because all our microservices sitting behind Envoy expose the same set of paths: /metrics, /graphql, etc.. So I need to disambiguate to pick the right cluster, and the x-envoy-original-path header does that nicely. :-)
