### ISSUE TITLE
Support `request.query` request attribute

### ISSUE THREAD

**Issue by sergiitk** [envoyproxy/envoy#19724]
*Title*: Support`request.query` request attribute

*Description*:
Envoy [Request attributes](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#request-attributes) are missing `request.query`, which is commonly used to retrieve the query part of HTTP url. Some examples:

1. googleapi's `attribute_context.proto` serves a purpose similar to Envoy's attributes. It provides [`Request.query`](https://github.com/googleapis/googleapis/blob/master/google/rpc/context/attribute_context.proto#L182-L184):

>     // The HTTP URL query in the format of `name1=value1&name2=value2`, as it
>     // appears in the first line of the HTTP request. No decoding is performed.

2. Google Cloud Armor CEL environment provides [`request.query` attribute](https://cloud.google.com/armor/docs/rules-language-reference#attributes)

3. Envoy's own interpretation of `attribute_context.proto` is used in the auth module. It provides `HttpRequest.query`, but never fills it in for some reason:

>     // This field is always empty, and exists for compatibility reasons. The HTTP URL query is
>     // included in `path` field.

*Implementation details*:
Envoy already supports the `request.url_path` which is URL path without query string by separating finding query offset:
https://github.com/envoyproxy/envoy/blob/70a5f295da789610b9d078015f43e39c6a76d4b6/source/extensions/filters/common/expr/context.cc#L112-L117

 I think it should be straightforward to take the rest of the string and provide it via `requset.query`.

*Relevant Links*:
- Envoy CEL filter's [RequestWrapper](https://github.com/envoyproxy/envoy/blob/70a5f295da789610b9d078015f43e39c6a76d4b6/source/extensions/filters/common/expr/context.cc#L72-L134)

**Comment by mattklein123** [comment]
cc @kyessenov @douglas-reid

**Comment by daixiang0** [comment]
Very curious about the mentioned compatibility reasons.

**Comment by kyessenov** [comment]
Makes a lot of sense. I think it would be nice to have that attribute parsed and presented as a map for usability, but that probably needs extra care due to potentially malformed inputs.

**Comment by sergiitk** [comment]
cc @tyxia

**Comment by kyessenov** [comment]
I think just using the complete of `url_path` is probably the right way since that's what has been done before, and anything on top can be supplanted with custom functions.
