### ISSUE TITLE
code coverage for contrib extension

### ISSUE THREAD

**Issue by dorisd0102** [envoyproxy/envoy#19729]
*Title*: code coverage for contrib extension

*Description*:
The "bazel coverage" could not generate the code coverage report of contrib extension,  is there any plan to implement it?  

[optional *Relevant Links*:]
No

**Comment by mattklein123** [comment]
This would be nice to have somehow, but it's not implemented yet. I will mark it help wanted.

**Comment by daixiang0** [comment]
@dorisd0102 you can run `bazel.coverage //contrib/...` to get it.

**Comment by dorisd0102** [comment]
Hi @daixiang0 ,
For non-contrib code under source, after bazel coverage, there is code coverage in bazel-out/_coverage/_coverage_report.dat , then  I could use "genhtml bazel-out/_coverage/_coverage_report.dat -o generated/coverage" to generate a coverage report. 

But for contrib code, it seems no code coverage reported in bazel-out/_coverage/_coverage_report.dat after bazel coverage run.

This is my execuction:
$ bazel coverage //contrib/sip_proxy/filters/network/test:cov_test
INFO: Build completed successfully, 3 total actions
//contrib/sip_proxy/filters/network/test:cov_test               (cached) PASSED in 9.1s
  /home/felixdu/.cache/bazel/_bazel_felixdu/29c3a0bddff37a5f1a60349652c66c6a/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/cov_test/coverage.dat
$ grep contrib bazel-out/_coverage/_coverage_report.dat | wc
      0       0       0

**Comment by daixiang0** [comment]
Please run ` bazel.coverage //contrib/sip_proxy/filters/network/...`:
```
Writing directory view page.
Overall coverage rate:
  lines......: 5.0% (2307 of 46145 lines)
  functions..: 6.0% (494 of 8266 functions)

````

**Comment by daixiang0** [comment]
There is no target about `cov_test`:
```
//contrib/sip_proxy/filters/network/test:app_exception_impl_test         PASSED in 24.5s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/app_exception_impl_test/coverage.dat
//contrib/sip_proxy/filters/network/test:config_test                     PASSED in 29.0s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/config_test/coverage.dat
//contrib/sip_proxy/filters/network/test:conn_manager_test               PASSED in 31.3s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/conn_manager_test/coverage.dat
//contrib/sip_proxy/filters/network/test:decoder_test                    PASSED in 31.3s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/decoder_test/coverage.dat
//contrib/sip_proxy/filters/network/test:router_test                     PASSED in 26.8s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/contrib/sip_proxy/filters/network/test/router_test/coverage.dat
```

**Comment by dorisd0102** [comment]
@daixiang0  Many thanks for your quick response./so


It seems overall coverage rate reported in bazel.coverage only include the code coverage in source/ that contrib/sip-proxy called. It dose not include the source code under contrib.

you could check the detailed  coverage data in bazel-out/_coverage/_coverage_report.dat.

**Comment by daixiang0** [comment]
#19867 may help.
