### ISSUE TITLE
Add new tap output sink type BufferedAdminSink

### ISSUE THREAD

**Issue by noahgoldman** [envoyproxy/envoy#19727]
*Title*: *Add new tap output sink type `BufferedAdminSink`*

*Description*:

The existing `/tap` admin endpoint makes it easy to setup ad-hoc captures on an Envoy instance with minimal dependencies (an HTTP client such as `curl` being all that's required).  There are however, some cases where the streaming approach taken by this endpoint becomes more challenging to use:
* As an Envoy operator, I often want to use traffic tapping to capture just a few matching requests to get samples of some piece of behavior.  Capturing say "the first N requests" using the current `/tap` endpoint is not possible with just an HTTP command-line client (although can certainly be added with a more complex client).
* Intermediate hops that proxy `/tap` requests to the admin handler may not properly support streaming HTTP responses, or configure timeouts such that connections with long-lived streaming responses are closed.

To be more specific, these are pain points currently experienced by Envoy operators at Uber.

Introducing a new `BufferedAdminSink` type to [envoy.config.tap.v3.OutputSink](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/tap/v3/common.proto#L230) would allow users of the `/tap` endpoint to configure traffic tapping to work around both points listed above.  Rather than streaming traces as they are collected, a request to the `/tap` endpoint with the new output sink type would block until a specified number of traces are collected, or the serialized size of collected traces reaches a specified number of bytes.  The endpoint would then return the entire set of serialized traces at once.

To make this more concrete, here is a proposed definition for `BufferedAdminSink`:

```proto
// BufferedAdminSink configures a tap output to collect traces without returning them until
// one of multiple criteria are satisfied.
// Similar to StreamingAdminSink, it is only allowed to specify the streaming admin output
// sink if the tap is being configured from the `/tap` admin endpoint.
message BufferedAdminSink {
  // Stop collecting traces when the specified number are collected.
  // If other criteria for ending collection are reached first,
  // this value will not be used.
  uint64 max_traces = 0;

  // Stop collecting traces when the total size of the serialized traces reaches this value.
  // If other criteria for ending collection are reached first,
  // this value will not be used.
  uint64 max_total_bytes = 1;
}
```

There are certainly a number of different ways to design this API.  The criteria for stopping trace collection could be a `oneof`, and other criteria (such as a timeout) could potentially be added.  When it comes to API reusability, the concept of a "trace complete criteria" could be something that could be a more general message.  I wasn't able to find anything suitable in the API currently, but I'd be more than open to suggestions.

I attempted to think through the questions in the [API Review Checklist](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md) when considering this.  Please let me know if there's anything I missed on that front!

Headcount is currently available at Uber to implement this enhancement.  We'd love to get feedback on our proposed additions, and ideally sign-off that something like what was described above is a feature we can contribute!

**Comment by mattklein123** [comment]
I think this a fine feature request, though my initial reaction is that if the admin call blocks, you still have a high likelihood that clients may give up before you get the response you are looking for. I suppose you are OK with configuring client max hanging GET / response time?

**Comment by noahgoldman** [comment]
> I think this a fine feature request, though my initial reaction is that if the admin call blocks, you still have a high likelihood that clients may give up before you get the response you are looking for.

Yeah, that's definitely possible.  Particularly in the case I listed above, where the `/tap` request might be proxied through a hop with a lower request timeout.

In my opinion however, a case where the call blocks for a very long time would probably occur in a situation where one of the other output sinks would be more appropriate.  I can imagine a use-case where you'd want to do an ad-hoc capture of an HTTP trace for a very infrequent request (maybe that happens once every 10 minutes or so).  At that point, I think the `StreamingAdminSink` is totally fine to use, since you aren't worried about deciding when to close the request once "enough" traces are captured.

I'd expect the normal use-case for this sink to be an operator wanting to capture a sample of somewhat frequent requests.  If I were using this feature, I'd probably have an expectation for how long it would take for my matching criteria to collect the specified number of traces, and cancel the request if it took too long.

> I suppose you are OK with configuring client max hanging GET / response time?

Definitely. I think this could be reasonably set as a required field on `BufferedAdminSink`, or potentially a global configuration parameter?  The per-output sink approach seems a little more flexible to me personally.  Let me know if you have any preferences there!

**Comment by noahgoldman** [comment]
With #20142 being merged, I think we're all set to close this out.
