### ISSUE TITLE
Question to init state of ring hash based LB

### ISSUE THREAD

**Issue by minopolous** [envoyproxy/envoy#19739]
The documentation says nothing, if for two ports in a deployment the same hash ring is set up (if the hosts are for both ports at the same place in the ring and, if using the same input to the hash function we'd expect the same targeted host), or if the positioning in the ring is random.
What can be seen is, that different ports defined in istio are targeting different hosts (stickyness is isolated between ports).
Asking in the direction of - if there is any chance to share stickyness between ports by tuning configuration...

**Comment by snowp** [comment]
Are you asking about the case where two upstreams are defined for the same cluster with different ports? Or do you have two listeners in Envoy which both use ring hash to route? 

For the latter I'd expect the hashing to work out the same since they'd be using the same cluster

**Comment by minopolous** [comment]
Difficulty is that we use istio wrapping envoy. Let me try first in istio terms, then attaching an extract from the resulting envoy ingress gateway configuration. 
In a single istio virtualservice definition two match/route entries (for the two ports), one for grpc (:5656), one for http (:9001) are defined.  Both route/destinations points to the same destinationrule with a single subset "v1".  LB hashing input is a label containing the user name.
