### ISSUE TITLE
uhv: move http-parser to envoy

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#19749]
Envoy will need to use a modified version of http-parser as part of the unified header validation component. The first step would be to bring in http-parser into Envoy. Then, as part of a separate issue, http-parser will be modified to add a configuration setting that skip header validation.

Right now,  [http-parser](https://github.com/envoyproxy/envoy-setec/blob/main/bazel/external/http-parser.BUILD) is built as an [external library](https://github.com/envoyproxy/envoy/blob/bbcd487bd178ef5254545941ac369d944da41913/bazel/repositories.bzl).

**Comment by moderation** [comment]
I thought the plan was to stop using the deprecated `http-parser`. See:
- https://github.com/envoyproxy/envoy/issues/5155
- https://github.com/envoyproxy/envoy/issues/15290

It looks like all of the [uhv issues](https://github.com/envoyproxy/envoy/issues/created_by/ameily) rely on bringing the deprecated code into Envoy?

**Comment by ameily** [comment]
We are working with Yan on the unified header validation component and he shared a technical specification to start working against, which I was under the impression had been approved. There is more discussion going on about this issue in the PR, #19786.
