### ISSUE TITLE
What does `wasm_fail_stream` mean exactly, as a response code detail?

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#19747]
We've rolled out a WASM filter to our envoy infrastructure and noticed that occasionally, a single node will gradually start failing requests with a response code detail of `wasm_fail_stream`.

I am wondering, what does this mean exactly? It's unclear and doesn't appear to be documented. We are trying to determine a cause and fix for this.

This seems to be the relevant block of code in envoy:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/context.cc#L1592-L1625

**Comment by cetanu** [comment]
https://envoyproxy.slack.com/archives/CM2CQ4XJ5/p1643672245850239

**Comment by owenammann** [comment]
Um, this slack message is password protected...

**Comment by bbensen** [comment]
![Screen Shot 2022-04-15 at 10 13 01 AM](https://user-images.githubusercontent.com/3228906/163600442-34b232ac-14d1-49b9-9595-a8d31c5711aa.png)

Not that it helps that much but the slack message above just indicates that this error means "the (wasm?) vm has failed"
