### ISSUE TITLE
uhv: http-parser: allow extension methods

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#19757]
As part of the unified header validation component, http-parser needs to be updated to allow the use of extension methods, similar to how nghttp2 allows them. http-parser will be modified to add a new configuration setting that does not validate the method. This will allow similar behavior between the h1 and h2 codecs.

Within Envoy, a new configuration setting may need to be added as well that controls this behavior, outside of the UHV component or header validation policy.

This will need to be completed after http-parser has been brought into Envoy, #19749.

**Comment by yanavlasov** [comment]
UHV will not be used with http-parser and will only work with Balsa codec. This is no longer applicable.
