### ISSUE TITLE
Initial health check per connection

### ISSUE THREAD

**Issue by ankitkumarr** [envoyproxy/envoy#19768]
*Title*: An option for an initial health when creating a connection to any host in a cluster.

*Description*:
If [active health checking](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking) is configured for a cluster, an initial active health check is performed for all hosts as part of [cluster warming](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/cluster_manager#cluster-warming). However, this initial health check seems to only be performed when initializing the cluster. If a connection is reset, or if a host restarts, the health check would not be performed until the next configured health check interval. The request here is to add an option for an "inline" health check (as part of active health check config) that performs a health check whenever creating a new connection to any given host, but before routing any requests.

I would be happy to work on a PR for this, if the feature request seems reasonable.

Thank you!

**Comment by efimki** [comment]
@yanavlasov FYI

**Comment by mattklein123** [comment]
cc @alyssawilk. I think this is going to be tricky to implement so I would recommend doing a design before writing any code. The main reason it will be tricky is that the health checking system is disjoint from the connection pooling system and linking them up is not going to be easy.

The other thing I would mention is this feature is somewhat similar to the existing HTTP/2 keep alive feature which uses ping frames. I would take a look at that also to see if something like that could be used here or generalized in some way: https://github.com/envoyproxy/envoy/blob/79f963df35ade67fa3c351a08369688f259a7e08/api/envoy/config/core/v3/protocol.proto#L333

**Comment by alyssawilk** [comment]
AFIK the h2 ping options are for making sure long lived connections are still around, but the inline health check is more for new connections to make sure that the upstream is suitable for traffic.  I think this is going to be needed for a number of internal use cases, but +1 to doing an early design doc as it's likely going to be a series of non-trivial changes

**Comment by mattklein123** [comment]
> but the inline health check is more for new connections to make sure that the upstream is suitable for traffic

Yeah that's true, though the conn pool has logic I'm pretty sure to hold the connection until it has been verified (streams are not sent there) so in that sense I think there is a bunch of overlap.

My larger point is that it may be easier to have an independent "inline conn pool health check" config vs. the async active health checking. Perhaps they can share some of the same protos. Anyway a bunch to think about.

**Comment by ankitkumarr** [comment]
I started looking at this, but had to switch gears with other work. I will pick this back up in the next week or two. Please feel free to assign this to me!
