### ISSUE TITLE
memory leak when HTTP/2 codec wrapper API turned on by default

### ISSUE THREAD

**Issue by abhinavdahiya** [envoyproxy/envoy#19761]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *envoy keep using more memory until OOMKill after HTTP/2 codec wrapper API turned on by default*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

When running envoy binary that includes the changes from https://github.com/envoyproxy/envoy/pull/19614
we see that envoy keeps using more memory until it gets OOMKilled.

Here's a capture of the heap profile collected using `--define tcmalloc=gperftools`
[envoy.prof.zip](https://github.com/envoyproxy/envoy/files/7975300/envoy.prof.zip)

turning the feature `envoy/reloadable_features/http2_new_codec_wrapper` false fixes the issue
of memory leak.

**Comment by xjtian** [comment]
For context - we saw Envoy sidecars which typically use ~300MB memory at steady-state eventually get OOMKilled after hitting their 4GB memory limit upon pulling the linked change in.

**Comment by mattklein123** [comment]
cc @alyssawilk @birenroy can you take a look at this? Should we revert the flag while we sort this out? Unfortunately I think this also went into the last release so either the revert or the fix will need to be backported. cc @oschaaf

**Comment by birenroy** [comment]
I think we found the leak. We'll give the fix some time to bake internally before enabling the runtime feature again.

**Comment by birenroy** [comment]
This was fixed in the QUICHE upstream repository on February 1st:
  https://github.com/google/quiche/commit/6c61814256b13aa4550839653672be47c2203103

The fix was imported into Envoy on February 7th:
  https://github.com/envoyproxy/envoy/commit/510319c393972f9a54d3c3bf65bf09b9174a73ec

**Comment by kvcache** [comment]
I just had to disable this feature on my grpc service due to memory exhaustion exactly in this manner: https://github.com/envoyproxy/envoy/issues/8857

I am using `envoyproxy/envoy-dev:latest`, which on my server is:
```
envoy  version: 9ac1efc72d00a09604ddac335edf570d317b7c8c/1.22.0-dev/Clean/RELEASE/BoringSSL
```

The workaround I applied in `config.yml`:
```
layered_runtime:
  layers:
  - name: "static"
    static_layer:
      envoy.reloadable_features.http2_new_codec_wrapper: false
```

Without this configuration envoy takes _unbounded memory_ (explodes after a few _gigabytes_). With this stanza in my configuration file and exactly the same synthetic test envoy's heap stays below 32 _megabytes_. New configuration looks like:
```
curl -s localhost:9901/stats | grep memory
envoy.overload_actions.reset_high_memory_stream.count: 0
server.memory_allocated: 14546920
server.memory_heap_size: 23068672
server.memory_physical_size: 24858854
```
which is perfectly healthy. I'm not sure this new_codec_wrapper feature is ready for v1.22

**Comment by mattklein123** [comment]
cc @alyssawilk @birenroy ^^^ I think we need to disable it again. :(

**Comment by birenroy** [comment]
@kvcache Can you say anything about your traffic pattern? Are they long-lived gRPC streams, or short-lived?

Is there a way for me to run your synthetic test setup?

In the meantime, we'll get a PR out to default-disable the feature.

**Comment by kvcache** [comment]
I'll describe my load pattern, and I'm happy to give you as much detail as I can but this is a production/closed-source application:

* Long-lived H2 **_connections_**
* New H2 **_stream_** per request (suspect this is related)
* 120 physical connections, confirmed via AWS NLB connection metrics
* NLB just doing bare TCP routing
* TLS with a `letsencrypt` cert on Envoy
* When Envoy hits the memory limiter, if I kill the load harness envoy recovers
* Envoy is a sidecar - the local service is hosted on a Unix Domain Socket

Thank you for the default-disable. If there's more helpful information I can provide you can DM me and we can figure out how to get you all the answers you need.

**Comment by birenroy** [comment]
@diannahu did some investigation and found the likely cause. We'll have a fix upstream in QUICHE soon. Thanks for the report!
