### ISSUE TITLE
Remove alpine images

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#19781]
It has been planned for some time to remove the alpine images as we now have distroless that are better suited for the same purpose, and as it adds some maintenance overhead.

We have some contention for diskspace in envoy's CI builder, and the distroless images have been around for a while, so now would seem to be the time to remove.

related tasks:

- [x] Remove alpine build CI
- [x] Remove alpine info from docs
- [ ] Add discontinuation notice on dockerhub

**Comment by daixiang0** [comment]
Does it mean we will not have `envoy:alpine`?

**Comment by phlax** [comment]
> Does it mean we will not have envoy:alpine?

yep. The distroless image is smaller, more secure, easier to maintain, so this one has kinda become obsolete

**Comment by moderation** [comment]
Would be good to complete this and remove Alpine (and then follow up with Moonjit removal).

**Comment by phlax** [comment]
so alpine status is that its removed (at least the envoy alpine image) from any usage in the repo

re the dockerhub message - i dont have permissions to update this directly (cc @lizan)

im happy to close out this bug, as there is a more general issue with metadata on dockerhub (#19784 ) which this could be handled as part of

**Comment by mattklein123** [comment]
Yeah let's call this complete and we can track other improvements in different issues. Thank you all!

**Comment by nickblake-cambia** [comment]
@phlax @lizan Any chance that the https://hub.docker.com/r/envoyproxy/envoy-alpine/tags can be updated to reflect the current status of deprecation/dropped support on DockerHub? I see this ticket originally had a related task that was never completed that makes it look like an active project if you view on DockerHub directly?

**Comment by phlax** [comment]
@nickblake-cambia yep - i can fix this - ill take a look tomorrow
