### ISSUE TITLE
upstream timeout is not working, if value is greater than 30 secs

### ISSUE THREAD

**Issue by charuhans** [envoyproxy/envoy#19798]
*Title*: *timeout_ms is not working, if value is greater than 30 secs*

*Description*:
I am using Ambassador for external authentication and rerouting, which in turn uses envoy proxy.
I have deployed a service in the cluster which sleeps for 31 secs and returns 200 HTTP status code.

All my HTTP calls are failing with 502 bad gateway. Looking at logs, it seems to be timing out after 30 secs:
"POST /test-endpoint/run HTTP/1.1" 0 DC 16 0 30000 - , ," "insomnia/2021.7.2" "7819d615-9bdb-4f6b-a198-97f2ad89f023" "" "*:12000

Below is the envoy route:

{
"match": {
"case_sensitive": true,
"prefix": "/test-endpoint/",
"runtime_fraction": {
"default_value": {
"denominator": "HUNDRED",
"numerator": 100
},
"runtime_key": "routing.traffic_shift.cluster_test_service_12000_test"
}
},
"route": {
"cluster": "cluster_test_service_12000_test",
"cors": {
"allow_credentials": true,
"allow_headers": "",
"allow_methods": "GET, HEAD, PUT, POST, DELETE, OPTIONS",
"allow_origin_string_match": [
{
"exact": ""
}
],
"filter_enabled": {
"default_value": {
"denominator": "HUNDRED",
"numerator": 100
},
"runtime_key": "routing.cors_enabled.**"
},
"max_age": "86400"
},
"prefix_rewrite": "/",
"priority": null,
"timeout": "600.000s"
}
}

Kubernetes environment : GKE
Kubernetes Version: 1.19.5
Ambassador: 1.12.4
Envoy: 1.15.4

[optional *Relevant Links*:]
>I am looking for recommendation, on what I might be doing wrong, in my set up or do I need to configure some other timeout. Please, note I have also tried added x-envoy-upstream-rq-timeout-ms header.

**Comment by snowp** [comment]
I don't think Envoy would ever return 502 Bad Gateway - do you have another layer that might be enforcing this timeout?

**Comment by lambdai** [comment]
The error code “DC" in is downstream_termination, any possible that the client insomnia disconnected actively after 30 seconds?
