### ISSUE TITLE
IpVersions/Http2FrameIntegrationTest.AdjustUpstreamSettingsMaxStreams/IPv4 is Flaky

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#19808]
I have a PR out which simply changes contents of a .md file. However, it had a failure of [IpVersions/Http2FrameIntegrationTest.AdjustUpstreamSettingsMaxStreams/IPv4 in linux_arm64 release](https://dev.azure.com/cncf/envoy/_build/results?buildId=100605&view=logs&jobId=767be981-567e-57d8-68c3-2140ede0a0bd&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca). Since this PR did not change any code, I think this must have been a flake.

**Comment by RyanTheOptimist** [comment]
@anrossi it looks like this test was originally created by @davinci26 who is no longer on the project. Is this something you could take a look at?

**Comment by anrossi** [comment]
@rectified95 FYI, this might be something to take a look at to learn more.
