### ISSUE TITLE
IpVersions/IntegrationTest.AllWorkersAreHandlingLoad/IPv6 is flaky

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#19807]
I have a PR out which simply changes contents of a .md file. However, it had a failure of [IpVersions/IntegrationTest.AllWorkersAreHandlingLoad/IPv6 in macos test](https://dev.azure.com/cncf/envoy/_build/results?buildId=100605&view=logs&jobId=fa3d3e18-6969-5713-c3e7-3581195704fd&j=fa3d3e18-6969-5713-c3e7-3581195704fd&t=ba370bef-ca49-52f5-0c93-7c0c0f27c465). Since this PR did not change any code, I think this must have been a flake.

**Comment by RyanTheOptimist** [comment]
@YaoZengzeng it looks like you may have worked on this test recently. Can you take a look?

**Comment by htuch** [comment]
@wrowe code spelunking indicates you added this test. Reading through the code at https://github.com/envoyproxy/envoy/blame/main/test/integration/integration_test.cc#L163, I'm wondering if the OS scheduler and being unlucky could lead to significant connection imbalance.

**Comment by htuch** [comment]
I'm going to disable this test later today if we don't have a reasonable plan to fix as it's continuing to flake.

**Comment by KBaichoo** [comment]
This is still flaking, see CI runs for the following PRs: [18846](https://dev.azure.com/cncf/envoy/_build/results?buildId=101502&view=logs&j=fa3d3e18-6969-5713-c3e7-3581195704fd&t=ba370bef-ca49-52f5-0c93-7c0c0f27c465), [19894](https://dev.azure.com/cncf/envoy/_build/results?buildId=101479&view=logs&j=fa3d3e18-6969-5713-c3e7-3581195704fd&t=ba370bef-ca49-52f5-0c93-7c0c0f27c465), [19630](https://dev.azure.com/cncf/envoy/_build/results?buildId=101465&view=logs&j=fa3d3e18-6969-5713-c3e7-3581195704fd&t=ba370bef-ca49-52f5-0c93-7c0c0f27c465)

Does it make sense to disable this test?
