### ISSUE TITLE
Dynamic label values with stats

### ISSUE THREAD

**Issue by nitgoy** [envoyproxy/envoy#19812]
*Title*: *Is it possible to emit stats from a filter with dynamic values for labels?*

*Description*:
>We want to emit some stats from our custom filter with labels or dimensions that have dynamic values. The values are not from any fixed space and can't be anticipated either e.g. route names. We looked at the upstream_rq_xx metric because that metric has cluster name and response codes that could have many different values. But from the code it looks like all the response codes are predefined and stat objects are being fetched from a pre-populated list in the [HTTP codes class for upstream](https://github.com/envoyproxy/envoy/blob/main/source/common/http/codes.cc). The cluster name is also probably coming from a separate stat scope for each cluster.

Is there a way for a custom extension to initialize separate scope/stats based on a dynamic list of values?

**Comment by snowp** [comment]
Extensions have full access to the stats system and can do what they want in terms of creation scopes, stats. etc. You can take a look at most of the filter extensions and see how they create their own stats

An example of a filter that uses dynamic stats would be the grpc_stats filter: https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc#L208-L209

Information on dynamic tokens in general can be found here: https://github.com/envoyproxy/envoy/blob/main/source/docs/stats.md#dynamic-stat-tokens

**Comment by nitgoy** [comment]
Thanks a lot @snowp for the pointers. We'll try out if that will work for our use case.
