### ISSUE TITLE
Error attempting to build on Windows with provided docker image

### ISSUE THREAD

**Issue by tomqwpl** [envoyproxy/envoy#19825]
I'm attempting to follow the instructions on the ci/README.md page, "Developer use of CI docker images" to build Envoy on Windows to try and diagnose an issue we're having.

I'm running the shell script as described.
```
./ci/run_envoy_docker.sh './ci/windows_ci_steps.sh'
```
I'm running this from within a "git bash" shell, so MSYS shell. I'm not running this under WSL for example.

If I run the script as my normal windows user I get:

```
ERROR: SymlinkDirectories(c:\build\tmp/_bazel_ContainerAdministrator/install/123df92719b107a86cd72886e258fa44, c:\bui
ld\tmp\install): CreateJunction: ERROR: src/main/native/windows/file.cc(401): DeviceIoControl(\\?\c:\build\tmp\instal
l): Access is denied.

FATAL: failed to create installation symlink 'c:\build\tmp\install': (error: 5): Access is denied.
```

However, if I try running the same thing from a command prompt running as administrator, I get the following instead:
```
ERROR: SymlinkDirectories(c:\build\tmp/_bazel_ContainerAdministrator/install/123df92719b107a86cd72886e258fa44, c:\bui
ld\tmp\install): CreateJunction:
FATAL: failed to create installation symlink 'c:\build\tmp\install': success
```

Actually if I try deleting the complete tmp directory and starting again, I get the same "Access Denied" error as above. Interestingly the directory appears to be created anyway.

I'm unclear what I need to do to make this work. The instructions for building envoy on Windows "manually" talk about making sure symlinks are enabled, or you're running as administrator and so on, but I was naively assuming that the shell script and docker image would be set up to do anything that needed to be done?

Does "developer mode" have to be turned on my machine in order for this to work, even though the build is being run inside a docker container?

Anyway, any pointers anyone could give me on how to build on Windows using the docker image would be very welcome.

Thanks.

**Comment by htuch** [comment]
@envoyproxy/windows-dev @phlax

**Comment by daixiang0** [comment]
Try open cmd using admin permission.

**Comment by tomqwpl** [comment]
@daixiang0 Apologies if my original problem description wasn't clear. It also doesn't work if I run the script from within a command shell running as admin.
