### ISSUE TITLE
url path prepend

### ISSUE THREAD

**Issue by ninoslavmedan** [envoyproxy/envoy#19835]
Hi There,

I am wondering if someone would be able to help me with this question. I have following situation.
When route in Envoy cluster mathes /someword I'd like to modify the path to be  prepenaded with fixed string ir
/someword would become /fixedpath?url=someword

fxiedpath is fixed string while someword can have many different values so I need some clever way to prepend the path with the fixed prefix. Is there a way to do this in Envoy proxy?
Nino

**Comment by htuch** [comment]
Does `prefix_rewrite` (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction) help?

**Comment by ninoslavmedan** [comment]
I was thinking about it as well and I can set it up easily if I know what the original prefix is. But in this case it can be more than 100 different urls. I cannot call them one by one and I do not see how to reference in prefix_rewrite what is matched in prefix at least this is not obvious to me. Any ideas there?

**Comment by htuch** [comment]
What about `regex_rewrite`?

**Comment by ninoslavmedan** [comment]
ok  so I was thinking of this. In order to match /somewords I was thinking of this expression [^\/]$  now what I do not get is how to construct regex_rewrite to give me /fixedpath?url=????   where these questions marks will be just anything copied from the original. I guess it does not make sense to use my original regex-ex there . I hope you see where I am struggling here

**Comment by htuch** [comment]
PTAL at the docs (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction). You can reference capture groups, e.g. `\1`.

**Comment by ninoslavmedan** [comment]
That was great. I did not realize how simple actually it is. This little config did the trick. Thanks a lot. You made not only my day but my week :)

              - match:
                  prefix: "/"
                route:
                  regex_rewrite:
                    pattern:
                      google_re2:
                        max_program_size: 200
                      regex: "(.*)"
                    substitution: "/blbla?url=\\1"
                  cluster: my.test.com
