### ISSUE TITLE
Doc: links in history are dead

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#19840]
*Title*: *dead links in history*

*Description*:

Check https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.11.0:
- Use of json based [schema](https://github.com/envoyproxy/envoy/blob/aa6a397b6536ac7949592110f5b7f76732671010/v1.11:test/tools/router_check/validation.proto) in router check tool tests. The tests should follow validation schema.
- tools: added [proto](https://github.com/envoyproxy/envoy/blob/aa6a397b6536ac7949592110f5b7f76732671010/v1.11:test/tools/router_check/validation.proto) support for [router check tool](https://www.envoyproxy.io/docs/envoy/v1.11.2/install/tools/route_table_check_tool#install-tools-route-table-check-tool) tests.

The links linked to v1.11:test are all dead, and can not find `v1.11` branch in GH page. Is it deleted?

It is just a history issue, with little effect on users. While these kinds of problems should be avoided as much as possible as the version iterates.

**Comment by phlax** [comment]
the link is wrong

```
:repo:`schema <v1.11:test/tools/router_check/validation.proto>`.
```

https://www.envoyproxy.io/docs/envoy/latest/_sources/version_history/v1.11.0.rst.txt

its trying to version a repo link - care to fix it @daixiang0

**Comment by daixiang0** [comment]
https://github.com/envoyproxy/envoy/tree/release/v1.11

Do we delete this release branch?

**Comment by phlax** [comment]
you can still acess from the tag https://github.com/envoyproxy/envoy/tree/v1.11.0
