### ISSUE TITLE
Make python 3.10 the default interpreter

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#19842]
### description

Currently the officially supported, and used/tested in CI version of python is 3.8

Locally i test with 3.9 and these 2 versions are mostly compatible

Version 3.10 brings quite a lot of change, and un/breaks a few things. It is seeing fairly rapid adoption imhe

I think we should plan in the next month or two to make 3.10 the official/supported version

Relatedly there is quite a bit of work going on in `rules_python` to add bazel python toolchains https://github.com/bazelbuild/rules_python/pull/618

**Comment by phlax** [comment]
cc @htuch @moderation

**Comment by moderation** [comment]
Moving to 3.10 sounds good. I have 3.10 installed on my Linux system but all sorts of stuff breaks if you try and make it the default Python

**Comment by htuch** [comment]
+1

**Comment by phlax** [comment]
related https://github.com/envoyproxy/envoy/issues/16001

**Comment by phlax** [comment]
this has now been implemented
