### ISSUE TITLE
Can we use threadsafeSnapshot()  instead of all snapshot() ?

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#19884]
In integration test,  if the client  use FeatureFlag, FeatureFlag.enabled()  will always report errors as “”snapshot can only be called from a worker thread or after the main thread is registered”;”

**Comment by htuch** [comment]
I can't say for sure, it would be good to see an example of what you are trying to do, but what you suggest is used inside unit tests.

**Comment by zhangbo1882** [comment]
For example, in the ssl integration test test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc.
The test case will first  call initialize() to start an envoy as a proxy in a separate thread . Then it will call makeSslClientConnection() to simulate a client. The client and the server will use the same code to create socket. Now I add some code  with FeatureFlag when create the socket.  My code will call FeatureFlag.enabled().  Now the  client will always report errors as “”snapshot can only be called from a worker thread or after the main thread is registered”.  Actually the client is a simulated one, it is not a worker thread or main thread.

**Comment by htuch** [comment]
I guess I'm a bit puzzled on why you need to be checking feature flags here, do you have some example? You probably know under what conditions the test is being run.

**Comment by htuch** [comment]
You don't need to read feature flags for that, you can just follow a standard pattern like https://github.com/envoyproxy/envoy/blob/027d6ca15adeae8cd478fcce67fc24322318e52e/test/integration/protocol_integration_test.cc#L3406.

**Comment by zhangbo1882** [comment]
> You don't need to read feature flags for that, you can just follow a standard pattern like
> 
> https://github.com/envoyproxy/envoy/blob/027d6ca15adeae8cd478fcce67fc24322318e52e/test/integration/protocol_integration_test.cc#L3406
> 
> .

Thanks @htuch .  This can help enable the feature.  But I want check whether the feature is enable or not. That's why I have to call FeatureFlag.enabled() which will print the errors.
