### ISSUE TITLE
envoy clusters problem when cx_connect_fail not zero

### ISSUE THREAD

**Issue by jinuxstyle** [envoyproxy/envoy#1989]
Envoy took a long time (sometimes nearly 1 minute) to get hosts for all upstream clusters (~30) ready via sds in my environment. I found the cx_connect_fail was not zero when the issue occurred. I suspected it may be caused by connection timeout, so I adjusted the connect_timeout_ms of sds settings from 250 ms to 2500 ms. The problem never appeared again during my test.

```
sds_cluster::172.24.1.22:9019::cx_active::18
sds_cluster::172.24.1.22:9019::cx_connect_fail::15
sds_cluster::172.24.1.22:9019::cx_total::33
```
Although the problem has been fixed, I still have several questions in my mind:

1. in what situation the  cx_connect_fail could greater than zero?

2. why the envoy takes a long time to get hosts for all upstream clusters when there have failed connection to sds server?

Thanks in advance!

**Comment by jinuxstyle** [comment]
update: found connect_timeout in stats

$ curl xxx/stats|grep sds |grep timeout

cluster.sds_cluster.upstream_cx_connect_timeout: 15

**Comment by mattklein123** [comment]
Sounds like you are having networking problems between Envoy and the SDS server. I would take a look at that.

**Comment by mattklein123** [comment]
Closing. Please reopen if there is more to look at it here.
