### ISSUE TITLE
Error in building from source on M1 MacOS

### ISSUE THREAD

**Issue by smahapatra1** [envoyproxy/envoy#19916]
Bazel build -s envoy doesn't work:

$uname -a
Darwin mycomputer 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

$bazel build -s envoy
ERROR: Traceback (most recent call last):
	File "/xyz/external/v8/bazel/defs.bzl", line 396, column 28, in _v8_target_cpu_transition_impl
		v8_target_cpu = mapping[settings["//command_line_option:cpu"]]
Error: key "darwin_arm64" not found in dictionary
ERROR: /xyz/external/v8/BUILD.bazel:3082:10: Errors encountered while applying Starlark transition
ERROR: Analysis of target '//:envoy' failed; build aborted:

**Comment by moderation** [comment]
I'm building on M1 without issue. What version of Bazel are you running (you should be using `5.0.0`)? Do you have the full version of XCode installed? I build with a bunch of extensions compiled out using `bazel build -c opt //source/exe:envoy-static.stripped`

**Comment by smahapatra1** [comment]
I do see Applications->Xcode in the Finder.
The .bazelversion file in the envoy directory has 5.0.0.
➜  envoy git:(main) ✗ cat .bazelversion
5.0.0

I see a recent commit with V8 and bazel changes and the error appears
related:

ERROR: Traceback (most recent call last):
File "/private/var/tmp/../external/v8/bazel/defs.bzl", line 396, column 28,
in _v8_target_cpu_transition_impl
v8_target_cpu = mapping[settings["//command_line_option:cpu"]]
Error: key "darwin_arm64" not found in dictionary

My naive reading is that V8 defs.bazel doesn't have a case for
"darwin_arm64" and needs a patch.

Thank you for your prompt response.

**Comment by moderation** [comment]
The `.bazelversion` in the code repo is not the installed version of Bazel you have. What is the output of `bazel version` when you run that from the command line?

I don't use any of the WASM functionality that requires v8 so I compile that out of my version with `~/.bazelrc` including `build --define wasm=disabled`

**Comment by smahapatra1** [comment]
➜  envoy git:(main) ✗ bazel --version
bazel 5.0.0

➜  envoy git:(main) ✗ bazel build -c opt //source/exe:envoy-static.stripped --define wasm=disabled
Target //source/exe:envoy-static.stripped up-to-date:
  bazel-bin/source/exe/envoy-static.stripped
INFO: Build completed successfully, 2 total actions

➜  envoy git:(main) ✗ bazel build -c opt //source/exe:envoy-static.stripped
INFO: Build option --define has changed, discarding analysis cache.
ERROR: Traceback (most recent call last):
	File "/...external/v8/bazel/defs.bzl", line 396, column 28, in _v8_target_cpu_transition_impl
		v8_target_cpu = mapping[settings["//command_line_option:cpu"]]
Error: key "darwin_arm64" not found in dictionary
ERROR: /...external/v8/BUILD.bazel:3082:10: Errors encountered while applying Starlark transition

So wasm=disabled clearly works and v8 seems to be the problem.
I have not tried building from the other repo that @htuch commented above.

**Comment by keith** [comment]
I submitted a fix for this here https://github.com/envoyproxy/envoy/pull/20216
