### ISSUE TITLE
listener: the behavior is different between ipv6 any address and ipv4-mapped ipv6 address when ipv4_compat is set.

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#19922]
When the ipv4_compat is set, and the listener is listening on Ipv6 any address "::". 

A request to "192.168.0.1"/"::FFFF:192.168.0.1", the socket's local address is "::FFFF:192.168.0.1", then envoy will translated this address to "192.168.0.1". Then the filter chain matching only can match "192.168.0.1"

When the ipv4_compat is set, and the listener is listening on Ipv4-mapped ipv6 address "::FFFF:192.168.0.1". 

A request to "192.168.0.1"/"::FFFF:192.168.0.1", the socket's local address is "::FFFF:192.168.0.1", but envoy won't translated this address, keep it as "::FFFF:192.168.0.1". Then the filter chain matching only can match "::FFFF:192.168.0.1"

This is due to
https://github.com/envoyproxy/envoy/blob/027d6ca15adeae8cd478fcce67fc24322318e52e/source/common/network/tcp_listener_impl.cc#L74-L77

`ioHandle->localAddress()` will translate the address when ipv4_compat flag is set on the socket. But we only invoke this when it is any address.

Note this was found when fix https://github.com/envoyproxy/envoy/pull/19716, but it isn't related to that, since https://github.com/envoyproxy/envoy/pull/19716 is the case of redirect the connection, and the redirection is based on original dst, the kernel will return same ipv4 and ipv6 address as client request.

**Comment by soulxu** [comment]
The obvious fix is to translate the address for ipv4-mapped ipv6 address also. But want to double-check whether the translation is expected behavior. Since the translation doesn't depend on what the client request to. If you request with `::FFFF:192.168.0.1`, it will be translated to `192.168.0` also.. But also seems ok, seems a consistent behavior all the ipv4-mapped address will be translated when the ipv4_compat flag is set and whatever the client is requesting to.

**Comment by htuch** [comment]
@ggreenway

**Comment by soulxu** [comment]
cc @lambdai also

**Comment by lambdai** [comment]
My understanding is that ::FFFF:192.168.0.1 should always be normalized to 192.168.0.1.

For filter chain match api, we can either exclude "::ffff:0:0/96" in filter chain match, 
or transform the listener config's filter chain match proto to normalized format
or warn the user that ipv6 filter chain match and ipv4 filter chain match are not equivalent.
