### ISSUE TITLE
Add an option to have healthchecks not re-use connections after succeeding

### ISSUE THREAD

**Issue by ryangardner** [envoyproxy/envoy#1994]
*Description*:

(discussed in slack earlier) 

When sending health checks against an HTTP2 endpoint, the initial connection to a prior-knowledge http2 service first passes in the magic string followed by the http2 frames. 

With the current behavior of envoy, the connection is re-used between health checks. With the way the HTTP2 protocol works, the "magic" bytes are not allowed after the first connection and are interpreted as part of a new frame. 

If there were an option to have it sever a connection after a successful check, it would enable a static set of bytes to be sent to a grpc health check endpoint.

**Comment by mattklein123** [comment]
Partial implementation here: https://github.com/envoyproxy/envoy/pull/2001. Just needs unit tests.
