### ISSUE TITLE
External Health Check Service

### ISSUE THREAD

**Issue by marcosrmendezthd** [envoyproxy/envoy#19945]
*Description*:
> The ability of defining an external health check service, similar in fashion to how ALS or RLS is defined.

If there is a way to configure a different cluster for health checking, I'd appreciate an example.

**Comment by marcosrmendezthd** [comment]
actually, I may have misunderstood the documentation. if an envoy is not assigned as a health checker, will it use FetchHealthCheck periodically to gather health details?

https://github.com/envoyproxy/envoy/blob/cc089aa5b162c711e7b7767e9b02c08eb238677a/api/envoy/service/health/v3/hds.proto#L70

**Comment by KBaichoo** [comment]
cc @phlax

**Comment by phlax** [comment]
not that im aware of off hand but ill grep the docs/examples to see if i can glean more

**Comment by marcosrmendezthd** [comment]
We might want to consider providing a way to decouple HDS from control-plane duties; xds, cds, eds. A design similar to the way the rate limit service would provide this; filter configuration for an grpc cluster and an additional stanza for the health check proto (external?) in addition to tcp, custom, http, etc. Does this make sense? Otherwise, in order to implement HDS we'd basically need to render those details into the config snapshots sent to Envoy, and depending on how that's managed and size of the fleet, it could be quite a task.

**Comment by marcosrmendezthd** [comment]
@phlax @KBaichoo ^^^
