### ISSUE TITLE
Could Envoy support regex PartialMatch?

### ISSUE THREAD

**Issue by clark1013** [envoyproxy/envoy#19948]
*Description*:
I am trying to migrate from Nginx to Envoy. There are a lot of regex configs only match a subsequence of the uri. But Enovy's `safe_regex` forces to match the entire uri. So could envoy support this scene through `re2::RE2::PartialMatch`?

[optional *Relevant Links*:]
Nginx regex match use `pcre_exec`: https://www.pcre.org/original/doc/html/pcre_exec.html
It performs like this:
```
Source Code:
    pcre *re = pcre_compile("^/a", 0, &errstr, &erroff, NULL);
    if (re == NULL) {
        printf("regex compile failed: %s", errstr);
        return 1;
    }
    char *subjects[4] = {"/a", "/a/b/c", "/a/c", "/b/c"};
    for (int i=0; i<4; i++) {
        char *subject = subjects[i];
        int rc = pcre_exec(re, NULL, subject, strlen(subject), 0, 0, NULL, 0);
        printf("%s match result %d\n", subject, rc);
    }

Output:
/a match result 0
/a/b/c match result 0
/a/c match result 0
/b/c match result -1
```

**Comment by daixiang0** [comment]
Nginx and Envoy are applicable to different fields, could you share the case you want to migrate?

**Comment by clark1013** [comment]
> Nginx and Envoy are applicable to different fields, could you share the case you want to migrate?

@daixiang0 Currently our API gateway is based on Nginx, It's responsible for route a request to a service, The service discovery is based on Consul. Recently we are building our service mesh based on istio and Envoy, we want to directly use Envoy as the API gateway, so we need to migrate route configs from Nginx to Envoy.

**Comment by KBaichoo** [comment]
cc @junr03 @snowp

**Comment by KfreeZ** [comment]
@zhxie would hyperscan help with this?

**Comment by jmarantz** [comment]
instead of PartialMatch could you use FullMatch, but modify the pattern so you don't anchor on the beginning/end? Sorry this may be a naive question. E.g. this test fragment works for me:
```
  RE2 re(".*abc.*");
  EXPECT_TRUE(RE2::FullMatch("xabcd", re));
```

**Comment by clark1013** [comment]
> instead of PartialMatch could you use FullMatch, but modify the pattern so you don't anchor on the beginning/end? Sorry this may be a naive question. E.g. this test fragment works for me:
> 
> ```
>   RE2 re(".*abc.*");
>   EXPECT_TRUE(RE2::FullMatch("xabcd", re));
> ```

@jmarantz Thanks for your advice. We will have a try. :smiley:
