### ISSUE TITLE
CI: Docker linux multiarch workflow often times out

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#19958]
CI: Docker linux multiarch workflow often times out

*Description*:
See CI for the following PRs: [19953](https://dev.azure.com/cncf/envoy/_build/results?buildId=101520&view=logs&j=2229703b-209a-5c70-43aa-3eacf674f12a&t=06218374-b1ef-5f45-4455-5a78d6d63b65), [19877](https://dev.azure.com/cncf/envoy/_build/results?buildId=101458&view=results), [19932](https://dev.azure.com/cncf/envoy/_build/results?buildId=101452&view=results) where we have the operation timeout.

Perhaps we should give the workflow more time than the 60 minutes it has.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
> Perhaps we should give the workflow more time than the 60 minutes it has.

yep, sounds like a plan altho its taking a long time - i guess its just transient upstream issues - there doesnt seem any failure
