### ISSUE TITLE
build 1.20 envoy by centos7 officail image get err "call to member function 'pause' is ambiguous"

### ISSUE THREAD

**Issue by huanghuangzym** [envoyproxy/envoy#19978]
*Title*:  build envoy by centos7 officail image get err "call to member function 'pause' is ambiguous"

*Description*:
>
we build envoy use offical centos build image with 1.20 envoy
get error

NFO: Analyzed target //src/envoy:envoy (305 packages loaded, 7421 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/530ed184f85848d5a11a3a8203c74c1b/external/envoy/source/common/upstream/BUILD:12:17: Compiling source/common/upstream/cds_api_helper.cc failed: (Exit 1): clang failed: error executing command /opt/llvm/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 136 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/envoy/source/common/upstream/cds_api_helper.cc:26:43: error: call to member function 'pause' is ambiguous
    maybe_resume_eds_leds = cm_.adsMux()->pause({eds_type_url, leds_type_url});
                            ~~~~~~~~~~~~~~^~~~~
external/envoy/envoy/config/grpc_mux.h:73:45: note: candidate function
  ABSL_MUST_USE_RESULT virtual ScopedResume pause(const std::string& type_url) PURE;
                                            ^
external/envoy/envoy/config/grpc_mux.h:85:45: note: candidate function
  ABSL_MUST_USE_RESULT virtual ScopedResume pause(const std::vector<std::string> type_urls) PURE;
                                            ^
1 error generated.
Target //src/envoy:envoy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1092.627s, Critical Path: 330.33s
INFO: 407 processes: 10 internal, 397 processwrapper-sandbox.
FAILED: Build did NOT complete successfully


it seems in this https://github.com/envoyproxy/envoy/pull/18195/files

maybe_resume_eds_leds = cm_.adsMux()->pause({eds_type_url, leds_type_url});

should chage it to support centos7 build?

std::vector<std::string> urllist = {eds_type_url, leds_type_url};
maybe_resume_eds_leds = cm_.adsMux()->pause(urllist);

**Comment by daixiang0** [comment]
Do you mean build Envoy in `CentOS:7`?

**Comment by huanghuangzym** [comment]
> 

yes，build envoy in centos 7

**Comment by daixiang0** [comment]
Is there any special reason that need build in centos 7? Build with ci script like `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'` works.

**Comment by huanghuangzym** [comment]
emm, we want to support envoy run in vm, not in k8s,  vm system can not upgrade to centos 8,so we need to build a binary for running in centos7

**Comment by robejfarr** [comment]
Caveat we're novices on C and C++ build chains with Envoy, but you've probably seen this PR and the comment(s) on it https://github.com/envoyproxy/envoy-build-tools/pull/154#issuecomment-1033902348 ?

We can build Envoy version 1.20.1 on CentOS 7 with `clang and libc++` (which works for us), but not `clang and libstdc++` and got a similar issue to yourself.

**Comment by JamesXNelson** [comment]
just fyi, we expect to need to be able to build in centos 7 machines that run in sensitive data centers where docker is not allowed. Would _love_ to see some traction on how to figure this out, so we can either produce working binaries for customers, or give them (as simple as possible) instructions on how they can build it themselves.
