### ISSUE TITLE
envoy-filter-example does not build with the correct toolchain config

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#20013]
Build script checks out the `envoy-filter-example` repository and changes directory into it before running bazel. As a result bazel does not pick up the .bazelrc file that is in the envoy repository causing bazel to auto detect toolchain.

We presently [copy .bazelversion](https://github.com/envoyproxy/envoy/blob/8136cce6dd66260eba6342b3f0f756e9e0f19016/ci/filter_example_setup.sh#L29), but may also need to copy .bazelrc file

**Comment by zuercher** [comment]
Actually, it already copies that file, so I'm going to close this.
