### ISSUE TITLE
What is the maximum allowed value for max_pending_lookups

### ISSUE THREAD

**Issue by zhaohaom-aws** [envoyproxy/envoy#20023]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *What is the maximum allowed value for max_pending_lookups?*

*Description*:
>We are using envoy to act as a DNS resolver and sometime redirect DNS traffics to external resolver. We set up a DNS filter and 
we would like to know the maximum allowed value for field max_pending_lookups.

[optional *Relevant Links*:]
>[Any extra documentation required to understand the issue.
](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/dns_filter.html?highlight=dns%20filter)

**Comment by yanjunxiang-google** [comment]
I don't see any default setting for this proto field:

https://github.com/envoyproxy/envoy/blob/3236abed247c71049e943be6d485d398fc646f9a/api/envoy/extensions/filters/udp/dns_filter/v3/dns_filter.proto#L93

There is an example configuration which set this to be 256:

https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/listeners/udp_filters/dns_filter.rst#:~:text=max_pending_lookups%3A%20256

**Comment by abaptiste** [comment]
There is no default.  In tests its set to `256`.  In testing (many moons ago) I don't recall seeing the value greater than 1.
