### ISSUE TITLE
Add ResponseHeadersToAdd/Remove to VirtualHost and RouteAction

### ISSUE THREAD

**Issue by 9len** [envoyproxy/envoy#2002]
Currently`ResponseHeadersToAdd/Remove` is settable on the `RouteConfiguration`. We'd like to add these fields to the `VirtualHost` and `RouteAction` as well, with the same precedence behavior as `RequestHeadersToAdd`.

@rshriram also [notes](https://envoyproxy.slack.com/archives/C78HA81DH/p1510003753000039) that it would be nice to have both `RequestHeadersToUpdate` and `ResponseHeadersToUpdate` to be able to replace an existing header rather than adding a second value. I'm happy to let the schema gods determine the right naming/semantics.

**Comment by zuercher** [comment]
The existing `HeaderValueOption` protobuf message has an `append` field to control whether it appends to existing values or replaces them (the default). So I think the add/update part is already in place for request headers.

**Comment by zuercher** [comment]
(Though the append flag seems to be ignored.)

**Comment by zuercher** [comment]
Starting on this one too.
