### ISSUE TITLE
Distribute GTP-C traffic to upstream hosts according to TEID

### ISSUE THREAD

**Issue by hundredbag** [envoyproxy/envoy#20034]
*Title*: *Distribute GTP-C traffic to upstream hosts according to TEID*

*Description*:
I would like to ask suggestions and comments for implementing GTP-C traffic distribution to upstream hosts according to TEID.

I want to distribute the GTP-C traffic from a single node evenly to the upstream pods, while also ensuring that the traffic with the same TEID value of GTP-C is forwarded to the same pod. 
As far as I know, UDP proxy chooses a host for each packet when use_per_packet_load_balancing is true, and forwards traffic from a client with the same IP and port to the same host when use_per_packet_load_balancing is false. 
However, in my use case, a single client generates GTP-C traffic, so it is difficult to perform our desired behavior using existing UDP proxy functions.

I am considering adding a funtionality that handles GTP-C traffic in addition to StickySessionClusterInfo and PerPacketLoadBalancingClusterInfo  in UdpProxyFilter class, or adding a load balancer functionality that considers the TEID of GTP-C traffic.
I would appreciate any comments on my considerations and on implementation, as well as corrections for any misunderstandings in my understanding.

**Comment by adisuissa** [comment]
CC'ing @mattklein123 @danzh2010 as code-owners of the udp-proxy filter and may be able to give some guidance.

**Comment by mattklein123** [comment]
Unfortunately I don't know anything about these acronyms. :)

Can you describe a bit more what is required? Could it be covered in some way by generic hashing support (hashing on byte ranges, etc.)?

**Comment by hundredbag** [comment]
Hello. Thanks for the reply.

I'd like to add a bit more information about GTP-C and TEID.

I plan to use Envoy for communication between components within a 5G Telco system running in a container environment. GTP-C is a protocol used for control plane messages to establish, modify, and terminate tunnels between components of system, and is one of the important features of 5G.

In my environment, a GTP-C packet consisting of a GTP-C header and a message is delivered as the payload of a UDP packet. TEID is a "Tunnel endpoint identifier" in the header of the GTP protocol. Bit 4 of the first byte of the GTP-C header contains the TEID flag field, which indicates the presence or absence of a TEID value. If the value of the TEID flag is 1, there is a TEID value from the 4th to the 8th byte of the GTP-C header.
(For more detailed explanation, please refer to the link => https://en.wikipedia.org/wiki/GPRS_Tunnelling_Protocol#GTP_version_2)

I would like to add a function that performs the following actions based on the TEID value. (I think it's possible to apply a generic hashing to the TEID values ​​for load balancing.)
1. If the TEID value is 0 or there is no session corresponding to this TEID value, the per-packet round-robin policy is applied.
2. If there is a session corresponding to the TEID value, the packet is forwarded to the upstream host of the session.

Please let me know if you have any required information and comments.

**Comment by mattklein123** [comment]
Is it possible to implement this via https://github.com/envoyproxy/envoy/issues/9514? I would really rather see us implement generic byte hashing for UDP (essentially allow configuring byte ranges to hash on in a datagram). I think this is generically useful for lots of people.

**Comment by hundredbag** [comment]
Doing hash to a specific byte range from the UDP packet's payload according to the configuration is a similar solution to what I was considering for handling GTP-C traffic.
However, I believe that we need additional features for GTP-C handling to the feature suggested in issue #9514 and generic byte hashing.

Here's why:
1. When the value of the byte range is a specific value (in my case, TEID field value is 0), a special behavior is required, so an additional feature (in my case, apply round robin policy to the packet) is required rather than general hashing. TEID value with 0 in GTP-C means creation of a tunnel, which occurs frequently.
2. Since the TEID value of GTP-C is determined dynamically, it is not sufficient to perform routing by specifying token values ​​in the configuration. 

I would appreciate any comments on a good way to handle GTP-C based on generic byte range hashing.

**Comment by hundredbag** [comment]
For (1), I think that it would be great to use generic hashing in the way you described.

For (2), I meant to say that using a token statically defined in the configuration file like #9514 is not a good way for GTP-C, since the TEID value is assigned in a non-predictable way by the endpoint at tunnel creation time. 
A GTP tunnel is identified by IP address, UDP port, and TEID value. Therefore, I think it is good to use generic hashing for creating, finding Envoy's UDP session, but to use IP address, UDP port, and TEID as a hash key for GTP tunnel identification. 
What do you think of this idea?

**Comment by mattklein123** [comment]
> Therefore, I think it is good to use generic hashing for creating, finding Envoy's UDP session, but to use IP address, UDP port, and TEID as a hash key for GTP tunnel identification.
What do you think of this idea?

I think what I'm after is to not have "TEID" anywhere in the code. Can we use generic byte ranges to create the lookup/hash value? If so that seems optimal.

**Comment by hundredbag** [comment]
I'm considering using N bytes of data starting at a specific offset in the UDP payload to generate/find the hash key. It would be good to make the starting offset and length (N bytes) configurable.

I also need to discuss how to handle the specific action for certain matching values. In my case, I need per-packet round robin if the value (N bytes from a start offset) is zero.

**Comment by mattklein123** [comment]
Yes ^ sounds good to me. My advice would be to propose the API first and we can discuss there and then do the implementation. I don't think the implementation will be very difficult.

**Comment by hundredbag** [comment]
OK. I'll create an API proposal soon.
Thank you for the comments.

**Comment by hundredbag** [comment]
Hello,
I have a question regarding the proper location to apply this API.

This issus is about generic byte hashing for UDP (N bytes from a certain startpoint) to create/find a session to upstream host. In addition, I need a function to perform a specific action for certain matching values.

In my opinion, it is good to add an optional configuration for generic hashing inside the existing UdpProxy API. For example, in the UdpProxy config, adding a config consisting of the starting position, byte length, and a field that compares the value with matching condition and determines whether the filter is disabled or not.

Is there a better place than UdpProxy to apply this API? I would appreciate any advice on the above design.

**Comment by northmirko** [comment]
@hundredbag Did you make any progress on this ? I am eager to help and contribute.

**Comment by hundredbag** [comment]
@northmirko Sorry for the late reply. I'm afraid we have not made any progress in this feature on Envoy and have no plans in  the near future😢
