### ISSUE TITLE
Pin pip hashes in example Dockerfiles

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#20039]
### description

Currently a few of the Dockerfile examples have `pip install` instructions that dont use a requirements file or enforce hashes

This means that they are not picked up by depdendabot and also that they can break (cf #20038 #20037 #20035 )

Specifically they can effectively cause bitrot in historical branches as the pulled dependencies no longer match the historical code

It will mean more dependabot noise mostly for the same app, but i think its the right thing to do

**Comment by phlax** [comment]
cc @kfaseela

**Comment by daixiang0** [comment]
I think it is a good enhancement and also we should pin image hashes.

**Comment by phlax** [comment]
@daixiang0 do you want to take this ticket ?

this would be a really helpful improvement

**Comment by daixiang0** [comment]
Sure.

/assign

**Comment by phlax** [comment]
couple of tips re this:

- use a requirements.in
- use pip-compile to generate the requirements.txt (`pip install pip-tools`)
- cd to the relevant directory and issue the following
```console
$ pip-compile --generate-hashes --reuse-hashes --allow-unsafe requirements.in
```
- make sure you have a v uptodate pip-tools as it has changed recently re namespace separators

-
