### ISSUE TITLE
Where can we get envoy's roadmap?

### ISSUE THREAD

**Issue by tuhao1020** [envoyproxy/envoy#20047]
#19419

**Comment by adisuissa** [comment]
I am aware of the [Envoy community calls agenda and minutes](https://docs.google.com/document/d/1Yc4zkV-A_cC_R3C0u6D15WQAsRSxADs8p2l8UMMa4P4/edit#) and that different issues are tracked using github's issue tracker.

As @alyssawilk mentioned in #19419 the features are typically prioritized by the tasks that the companies sponsoring the maintainers request, but maybe there's some doc with an explicit roadmap somewhere.

**Comment by phlax** [comment]
there are issue milestones also - https://github.com/envoyproxy/envoy/milestones

these are probably more concerned with specific release issues than roadmap, but it feels like that is probably the best system we have to track forward planning also

**Comment by tuhao1020** [comment]
@phlax  @adisuissa  thanks!
