### ISSUE TITLE
Envoy inline headers do not support appending values

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#2004]
For performance reasons, the headers that Envoy uses internally are stored inline in the Http::HeaderMap implementation. Appending values is not supported for these headers. The v2 API, however, allows them to be configured for append or replace at various levels (see #2003).

Currently, requests to append values are ignored and the header value is simply replaced. It can be argued that even this should not be allowed.

Need to determine whether modification of the inline headers via API config is allowed. If not, write validation code to prevent it. If allowed, consider whether specifying values to append is a configuration error or should just be ignored. The chosen behavior and the list of inline headers should be documented.

**Comment by zuercher** [comment]
N.B. The comment in `source/common/http/header_map_impl.cc`:

```
    // TODO(mattklein123): Currently, for all of the inline headers, we don't support appending. The
    // only inline header where we should be converting multiple headers into a comma delimited
    // list is XFF. This is not a crisis for now but we should allow an inline header to indicate
    // that it should be appended to. In that case, we would do an append here. We can do this in
    // a follow up.
```

**Comment by alyssawilk** [comment]
When this is done, we should make sure to update the lua docs, w.r.t add() behavior
See comments added on https://github.com/envoyproxy/data-plane-api/pull/445/files
