### ISSUE TITLE
envoy oath2 refresh access token

### ISSUE THREAD

**Issue by saurabh256** [envoyproxy/envoy#20058]
This is more of a question than issue but I believe it could lead to few issues 
1. I do not see any documentation or example to get new access token using refresh_token. This will be much helpful. 
2. Is there a way to get new access token using refresh token using backend call?  Usecase I am looking for user activity happens from front end , call comes to backend (envoy) with refresh token (coming from cookie) then envoy makes call to authorisation endpoint to get new access token using refres_token. 

Apologies for putting question here as the envoy-user group is not allowing me to post new conversation. I also believe documentation is very thin on Oauth2 filter.

**Comment by adisuissa** [comment]
cc @rgs1 @derekargueta @snowp as oauth2 filter owners

**Comment by thomasvargiu** [comment]
Hi! No news on this issue?
