### ISSUE TITLE
how  to setup a demo with `onRequestMetadata`

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#20056]
Hi folks, I'm trying to build WASM filter with `onRequestMetadata` 

https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/7afb39d868a973caa6216a535c24e37fb666b6f3/proxy_wasm_api.h#L460

Is there any doc/ut/e2e can show me how to setup a demo?

**Comment by daixiang0** [comment]
You can refer to https://www.envoyproxy.io/docs/envoy/latest/_downloads/fbba116ecfd0961809317acd2df6e3c2/envoy_filter_http_wasm_example.cc.

**Comment by zirain** [comment]
> You can refer to https://www.envoyproxy.io/docs/envoy/latest/_downloads/fbba116ecfd0961809317acd2df6e3c2/envoy_filter_http_wasm_example.cc.

I have read that , but there's nothing about `onRequestMetadata`.

**Comment by daixiang0** [comment]
I think you can get/update/delete metadata kind like `onRequestBody` codes.

**Comment by zirain** [comment]
@mattklein123 do you have any suggestions?

**Comment by adisuissa** [comment]
cc @envoyproxy/wasm-dev

**Comment by PiotrSikora** [comment]
@zirain it's unclear what you're trying to do, but `onRequestMetadata` is called for HTTP/2 METADATA frames, which AFAIK are not processed by default in Envoy (but perhpas this changed since the last time I've looked). Is that what you're after?

**Comment by zirain** [comment]
> @zirain it's unclear what you're trying to do, but `onRequestMetadata` is called for HTTP/2 METADATA frames, which AFAIK are not processed by default in Envoy (but perhpas this changed since the last time I've looked). Is that what you're after?

How can I enable this in Envoy?

**Comment by adisuissa** [comment]
> How can I enable this in Envoy?

The HTTP/2 metadata protocol has an experimental support, more [info](https://github.com/envoyproxy/envoy/blob/main/source/docs/h2_metadata.md).

You'll need to enable [allow_metadata](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/protocol.proto#L430) on the HCM and/or the upstream cluster. [This integration test setup](https://github.com/envoyproxy/envoy/blob/db17881226e3ea036ac659bdde7612b05b15f8c4/test/integration/multiplexed_integration_test.cc#L214) may help with guiding what needs to be done.

**Comment by zirain** [comment]
@adisuissa thanks for your response, let me try what you have suggested.
