### ISSUE TITLE
router check tool: add an option to write test results to a file in a structured format

### ISSUE THREAD

**Issue by seventhscream** [envoyproxy/envoy#20064]
*Title*: router check tool: add an option to write test results to a file in a structured format

*Description*:
At the present, the tool writes test results to the standard output streams in a text format.
We'd like to integrate with the tool in our validation workflows, so it might be better to have an option to make the tool write test results to files in some structured way for further processing.

We could have an option `--output` with the file path where to save the test results. Test results could be represented with a proto message `ValidationResult` (to be crafted). Setting the `--output` option wouldn't affect the standard output the tool produces.

**Comment by daixiang0** [comment]
I think you can use a pipe command like `route_check | tee <any_script>`?

**Comment by seventhscream** [comment]
Sure, this is one of the options.
Some benefits of the structured output:
- It would be easier to parse results, meaning less errors.
- It would also be safer to use as the proto is expected to be backward compatible.

It's not mandatory, but might be nice to have. Besides, I wanted to implement it myself. WDYT?

**Comment by daixiang0** [comment]
I think it is good.

/cc @envoyproxy/envoy-maintainers

**Comment by adisuissa** [comment]
cc @mattklein123

**Comment by mattklein123** [comment]
Sure SGTM
