### ISSUE TITLE
Bad version strings in 1.20.2

### ISSUE THREAD

**Issue by andrewstucki** [envoyproxy/envoy#20098]
*Title*: *Bad version strings in 1.20.2*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Looks like the version strings in the latest release artifacts contain `-dev` metadata in them.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```bash
➜  ~ docker run --rm envoyproxy/envoy:v1.20.1 --version

envoy  version: ea23f47b27464794980c05ab290a3b73d801405e/1.20.1/Clean/RELEASE/BoringSSL

➜  ~ docker run --rm envoyproxy/envoy:v1.20.2 --version

envoy  version: 4aaf9593152c6996b9da384c8918e9ad4f0abd4d/1.20.2-dev/Clean/RELEASE/BoringSSL
```

Notice `1.20.2-dev` rather than `1.20.2`

**Comment by daixiang0** [comment]
Not sure it is a wrong push or push code bug.

/cc @phlax

**Comment by andrewstucki** [comment]
So, looks like in all of the releases yesterday except for `1.21.1` the `VERSION` file at the top of the repo contains the `-dev` build label -- not quite sure of the typical release process, but I'm assuming that was an accident.

1.18.6:

https://github.com/envoyproxy/envoy/blob/a79ca225f1ed924b855dff8a26bd7f7cdb84e694/VERSION#L1

1.19.3:

https://github.com/envoyproxy/envoy/blob/a17cdcdfad24de101e95716b77549ba689824f25/VERSION#L1

1.20.2:

https://github.com/envoyproxy/envoy/blob/4aaf9593152c6996b9da384c8918e9ad4f0abd4d/VERSION#L1

1.21.1:

https://github.com/envoyproxy/envoy/blob/af50070ee60866874b0a9383daf9364e884ded22/VERSION#L1

**Comment by phlax** [comment]
cc @RyanTheOptimist - im wondering if we need to update the release docs somewhere to ensure that all versions are correctly bumped

**Comment by mattklein123** [comment]
This is a known SNAFU during our release process. We have fixed the procedures for future releases. We don't plan on doing a new release just to fix this issue, though perhaps we should do an email announce about it @RyanTheOptimist and then close this issue? WDYT?

**Comment by RyanTheOptimist** [comment]
I've sent the reply. Sorry for the headache. The procedure should prevent this from happening in the future.
