### ISSUE TITLE
Listener update may choose in place update too aggressively

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#20100]
When comparing the old listener and the new listener config,
[all the repeated fields are considered as set.](https://github.com/envoyproxy/envoy/blob/main/source/server/listener_impl.cc#L946)

An unexpected case is, if a listener filter chain is reordered along with some network filter chain add/deletion,
the listener filter chain update is ignored.

I go through the fields in the top level message listener and find these fields. Please correct me if I am wrong

* filter_chains: set semantic
* listener_filter_chains: ordered_list semantic
* socket_options: set semantic
* access_log: set semantic 

listener_filter_chains need to be compared separately.

CC @kyessenov

**Comment by soulxu** [comment]
seems when creating the override ListenerImpl, it will recreate the listener filters factory based on the new config https://github.com/envoyproxy/envoy/blob/b6bc5ca51227cea3ce00e0302d43ce50031d513e/source/server/listener_impl.cc#L430

and we update this override ListenerImpl into ActiveTcpListener https://github.com/envoyproxy/envoy/blob/b6bc5ca51227cea3ce00e0302d43ce50031d513e/source/server/connection_handler_impl.cc#L39

Then when the new connection is coming, it should be able to use the new listener filter factory list, right?

**Comment by kyessenov** [comment]
Not stale, need a doc at a minimum.

**Comment by soulxu** [comment]
The first step is adding an integration for this case https://github.com/envoyproxy/envoy/pull/20914

Then next step is going to check the filter draining code, ensure it skip the draining when there is only listener filters order update and no filter chain update.

**Comment by kyessenov** [comment]
Needs a fix, test added to confirm the issue.

**Comment by soulxu** [comment]
This issue can be closed also, since the integration test https://github.com/envoyproxy/envoy/pull/20914 already validate this case is ok.
