### ISSUE TITLE
Participation in Security Scorecards promo

### ISSUE THREAD

**Issue by devmoran** [envoyproxy/envoy#20106]
*Title*: *Participation in Security Scorecards promo*

*Description*:
I saw that Envoy recently integrated [scorecards](https://github.com/envoyproxy/envoy/commit/4ac979915fce8562e49293d8e52a48fc25ec6cf6), woop.
We're working with the scorecards team at Google Open Source Security on building a promo site together and I wanted to know - would you be happy for us to use Envoy’s logo on the site? We’re putting together a sheet of logos for prominent projects who are using the tool.
Let me know if you need any other information or want to discuss this separately.

**Comment by mattklein123** [comment]
@devmoran I think this would be fine but could you email envoy-maintainers@googlegroups.com and we can discuss further? Thank you.
