### ISSUE TITLE
Envoy 1.21, error for TLS: envoy->(TLS)->postgresql

### ISSUE THREAD

**Issue by maksimaz** [envoyproxy/envoy#20117]
*Title*: *Envoy 1.21, error for TLS: envoy->(TLS)->postgresql*

*Description*:
>**1)** I trying to make a chain  **psql(or java client)->(TCP)->envoy->(TLS)->postgresql** and got error on the side envoy->(TLS)->postgresql (see envoy trace in envoy.txt and error_postgresql_trace.txt with line "2022-02-25 15:05:00.448 MSK [24579] [unknown]@[unknown] LOG:  connection received: host=192.168.0.47 port=47422")
>**2)** I have success for **psql(or java client)->(TLS)->postgresql** (see success_postresql_trace.txt with line "2022-02-25 14:52:54.725 MSK [24290] [unknown]@[unknown] LOG:  connection received: host=192.168.0.47 port=54628")

>For **1)** and **2)** I use the same set of certificates. 

>Example client call for psql for **1)** "sudo -u postgres psql 'host=192.168.0.60 port=5432 dbname=sammy user=sammy password=secret sslmode=verify-ca sslcert=/opt/certpostgre/postgres-frontend.example.com.crt sslkey=/opt/certpostgre/example.com.key sslrootcert=/opt/certpostgre/ca.crt'"
Example client call for psql for **2)** "sudo -u postgres psql 'host=192.168.0.47 port=3333 dbname=sammy user=sammy password=secret' "

>[envoy.txt](https://github.com/envoyproxy/envoy/files/8141576/envoy.txt) - envoy static configuration
[error_postgresql_trace.txt](https://github.com/envoyproxy/envoy/files/8141577/error_postgresql_trace.txt) - postgresql trace for 1)
[success_postresql_trace.txt](https://github.com/envoyproxy/envoy/files/8141580/success_postresql_trace.txt)  - postgresql trace for 2)
[pg_hba.conf.txt](https://github.com/envoyproxy/envoy/files/8141578/pg_hba.conf.txt) - postgresql pg_hba.conf
[postgresql.conf.txt](https://github.com/envoyproxy/envoy/files/8141579/postgresql.conf.txt) - postgresql.conf

>Software version: PostgreSQL 14, envoy 1.21, Ubuntu 20.04.

Could some one help with 1.?

**Comment by yanavlasov** [comment]
It is hard to tell with the information provided. Looks like handshake does not complete. Can you try enabling access logging to see what failure Envoy is registering? See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#trouble-shooting

@ggreenway @PiotrSikora

**Comment by PiotrSikora** [comment]
As far as I recall, PostgreSQL is using StartTLS, so you cannot use TCP proxy with TLS for load balancing.

Did you try using [Envoy's Postgres Proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter) filter instead?

**Comment by maksimaz** [comment]
I updated envoy to version c444c6ee9e949306a87cd3a712472f08d76c3716/1.22.0-dev/Clean/RELEASE/BoringSSL and:

1) I success connected to PostgreSQL: **psql->(TLS)->postgresql** (SSL connection from DN:"CN=sammy,O=MyExample\, Inc.,ST=CA,C=US" CN:"sammy" - see success_postresql_trace.txt)
2) I have error when connect to PostgreSQL through the envoy: **psql->(TCP)->envoy->(TLS)->postgresql** (handshake ok, but "SSL connection from DN:"(anonymous)" CN:"(anonymous)"" - see error_postresql_trace.txt)

For 1) and 2) I use the same set of certificates.

[envoypostgrestarttls.yaml.txt](https://github.com/envoyproxy/envoy/files/8155382/envoypostgrestarttls.yaml.txt) - envoy static configuration for StartTLS
[envoylog.txt](https://github.com/envoyproxy/envoy/files/8155381/envoylog.txt) - envoy trace
[success_postresql_trace.txt](https://github.com/envoyproxy/envoy/files/8155384/success_postresql_trace.txt) -  postgresql trace for 1)
[error_postresql_trace.txt](https://github.com/envoyproxy/envoy/files/8155383/error_postresql_trace.txt) -  postgresql trace for 2)

**Comment by cpakulski** [comment]
@maksimaz  **psql->(TCP)->envoy->(TLS)->postgresql** will not work. There is opened issue for that scenario #19527.
