### ISSUE TITLE
Using Tensorflow bazel files

### ISSUE THREAD

**Issue by smahapatra1** [envoyproxy/envoy#20123]
*Title*: *Using Tensorflow Bazel files*

*Description*:
Envoy is a beautiful piece of software with a lot to learn about programming from it including the powerful use of Bazel. On the other hand, I was wondering if there is any way one can reduce the Bazel mechanism build-up needed for a project by re-using one from Tensorflow or Envoy. In that spirit, I wanted to check what maintainers think about using Tensorflow Bazel stuff for Envoy as well.

[optional *Relevant Links*:]
https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE

**Comment by daixiang0** [comment]
Do you mean to use build architecture like TF?

**Comment by smahapatra1** [comment]
Yes, if it is possible. I am not a Bazel expert, but I have read the use in both TF and Envoy. I am also trying to use Bazel for my own project and trying to pick a model. Thanks.
  
  
  
  
  
  
  

  
  
>

**Comment by lizan** [comment]
It is actually pretty similar architecture but also tailored for project specific needs. I don't think we can simply reuse TF or TF can reuse what we do because we do have different dependencies.
