### ISSUE TITLE
Non Sampled X-Ray Tracing

### ISSUE THREAD

**Issue by jayrp11** [envoyproxy/envoy#20127]
*Title*: *Non Sampled X-Ray Tracing*

*Description*:
When trace is non sampled in source/extensions/tracers/xray/xray_tracer_impl.cc create new non sampled trace. This creates bit of issue when trace id is used to correlate logs with other tools like Spring Boot apps using brave-propagation-aws. Is it possible to continue using same trace id having non-sampled flag. 

Caution: I am not really expert in C++ so just reading code with limited knowledge on the language.

[optional *Relevant Links*:]
source/extensions/tracers/xray/xray_tracer_impl.cc line 117

**Comment by suniltheta** [comment]
thanks @mattklein123 for merging the CR. I guess we can close this issue now.
Just curious if this should have been closed automatically from the merge, and if I didn't format my PR properly for this.

**Comment by mattklein123** [comment]
You probably just didn't have "fixes <this issue>" is your PR description.

**Comment by suniltheta** [comment]
I will make a note.
