### ISSUE TITLE
High CPU usage for matching routes (re2::DFA::InlinedSearchLoop)

### ISSUE THREAD

**Issue by ZIK-1337** [envoyproxy/envoy#20147]
What are the solutions to reduce CPU usage? There are a lot of routes, each request in the loop is matched - probably because of this.
Envoy v1.15.0
Top 50 usage from pprof:

> Showing top 50 nodes out of 260
      flat  flat%   sum%        cum   cum%
  1842.68s 20.48% 20.48%   1842.82s 20.48%  re2::DFA::InlinedSearchLoop
   484.96s  5.39% 25.87%    484.96s  5.39%  tc_newarray
   391.39s  4.35% 30.22%   4550.41s 50.57%  Envoy::Router::RegexRouteEntryImpl::matches (inline)
   373.74s  4.15% 34.37%    373.74s  4.15%  writev
   372.04s  4.13% 38.51%   5005.04s 55.63%  Envoy::Router::VirtualHostImpl::getRouteFromEntries
   353.18s  3.93% 42.43%   3138.31s 34.88%  re2::RE2::Match
   277.19s  3.08% 45.51%    277.19s  3.08%  absl::string_view::find_first_of
   261.06s  2.90% 48.42%    261.06s  2.90%  __GI___pthread_rwlock_rdlock
   241.56s  2.68% 51.10%   2206.65s 24.52%  re2::DFA::Search
   183.22s  2.04% 53.14%    458.71s  5.10%  Envoy::Router::RouteEntryImplBase::matchRoute
   170.52s  1.90% 55.03%    170.52s  1.90%  __nss_database_lookup
   164.50s  1.83% 56.86%    164.50s  1.83%  re2::Prog::GetDFA
   149.17s  1.66% 58.52%   3290.14s 36.57%  re2::RE2::DoMatch
   123.84s  1.38% 59.89%    123.84s  1.38%  operator delete[]
   110.38s  1.23% 61.12%    110.38s  1.23%  Envoy::Router::RouteEntryImplBase::evaluateRuntimeMatch (inline)
   106.25s  1.18% 62.30%    106.25s  1.18%  readv
    97.59s  1.08% 63.39%    114.70s  1.27%  <unknown>
    96.40s  1.07% 64.46%     96.40s  1.07%  __GI___pthread_rwlock_unlock
    91.51s  1.02% 65.47%     91.51s  1.02%  re2::DFA::AnalyzeSearchHelper
    86.56s  0.96% 66.44%     86.56s  0.96%  epoll_wait
    74.57s  0.83% 67.27%     74.57s  0.83%  std::__1::vector::empty (inline)
    72.68s  0.81% 68.07%     72.68s  0.81%  Envoy::Router::RouteEntryImplBase::tlsContextMatchCriteria
    68.16s  0.76% 68.83%    206.62s  2.30%  google::protobuf::Value::clear_kind
       54s   0.6% 69.43%     69.60s  0.77%  std::__1::basic_string::basic_string
    53.85s   0.6% 70.03%   2784.69s 30.95%  re2::Prog::SearchDFA
    53.39s  0.59% 70.62%    219.42s  2.44%  google::protobuf::Map::erase
    51.24s  0.57% 71.19%     52.60s  0.58%  lj_str_new
    51.14s  0.57% 71.76%     51.14s  0.57%  epoll_ctl
    47.31s  0.53% 72.29%     52.85s  0.59%  Envoy::TrieLookupTable::find (inline)
    34.52s  0.38% 72.67%     96.46s  1.07%  google::protobuf::ListValue::~ListValue
    32.60s  0.36% 73.03%    121.74s  1.35%  re2::DFA::AnalyzeSearch
    32.09s  0.36% 73.39%   6586.35s 73.20%  http_parser_execute
    24.09s  0.27% 73.66%   4574.50s 50.84%  non-virtual thunk to Envoy::Router::RegexRouteEntryImpl::matches(Envoy::Http::RequestHeaderMap const&, Envoy::StreamInfo::StreamInfo const&, unsigned long) const
    21.26s  0.24% 73.89%   3346.77s 37.20%  Envoy::Regex::(anonymous namespace)::CompiledGoogleReMatcher::match
    21.18s  0.24% 74.13%     54.39s   0.6%  google::protobuf::Value::MergeFrom
    18.50s  0.21% 74.33%     86.90s  0.97%  Envoy::Router::RouteEntryImplBase::evaluateTlsContextMatch
    18.01s   0.2% 74.53%     93.21s  1.04%  std::__1::__shared_count::__release_shared (inline)
    14.72s  0.16% 74.70%    286.98s  3.19%  Envoy::Http::PathUtil::removeQueryAndFragment
    13.77s  0.15% 74.85%    312.11s  3.47%  google::protobuf::internal::MapFieldLite::MergeFrom
    13.05s  0.15% 75.00%    211.98s  2.36%  google::protobuf::Map::~Map
    11.90s  0.13% 75.13%     50.83s  0.56%  non-virtual thunk to Envoy::Http::RequestHeaderMapImpl::getPathValue() const
    11.81s  0.13% 75.26%   7087.44s 78.77%  std::__1::__function::__func::operator()
    10.31s  0.11% 75.37%   1274.87s 14.17%  std::__1::default_delete::operator() (partial-inline)
    10.21s  0.11% 75.49%    124.94s  1.39%  Envoy::Http::ConnectionManagerImpl::ActiveStream::encodeHeaders
     8.05s 0.089% 75.58%     84.21s  0.94%  Envoy::Http::HeaderUtility::matchHeaders
     7.60s 0.084% 75.66%   8546.59s 94.99%  event_base_loop
     7.21s  0.08% 75.74%    110.14s  1.22%  google::protobuf::Arena::CreateMaybeMessage
     6.34s  0.07% 75.81%   6693.40s 74.39%  Envoy::Network::FilterManagerImpl::onContinueReading
     5.91s 0.066% 75.88%     67.14s  0.75%  google::protobuf::util::(anonymous namespace)::DescriptorPoolTypeResolver::ResolveMessageType
     5.83s 0.065% 75.94%     73.82s  0.82%  google::protobuf::util::converter::ProtoStreamObjectSource::RenderMap

Graph (file):
![profile001](https://user-images.githubusercontent.com/67591287/156111444-3db59f18-55e5-4f5e-a8ad-38e7a6a32efc.svg)
Github crops the picture, so more link to it: https://drive.google.com/file/d/1JDetSWWR24Trt9_Q7Ck5qVogvgM5zG-K/view?usp=sharing

**Comment by wbpcode** [comment]
The regex matchs are always expensive if there are may routes with regex match in the route table.

And there is new matcher API which may solve this problem. 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/common/matcher/v3/matcher.proto

**Comment by zhxie** [comment]
I am interesting with the case. Do you have a very large route table or a complex expression?

**Comment by ZIK-1337** [comment]
> I am interesting with the case. Do you have a very large route table or a complex expression?

There are more than 4000 routers, the expressions are not complicated but the routers themselves are long

**Comment by ZIK-1337** [comment]
> The regex matchs are always expensive if there are may routes with regex match in the route table.
> 
> And there is new matcher API which may solve this problem. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/common/matcher/v3/matcher.proto

Nowhere in the change list does it say anything about improved performance when working with regex match. If it says anywhere, can you send me a link?

**Comment by zhxie** [comment]
I agree with @wbpcode, the regex matches are expensive. And since you are using regex, the logic in `routes` and `matcher` (matching API) may be the same, to match the rule one by one.
IMO, if you have to use regex, and there is no room for improvement in your rule set, maybe you can have a try on other regex engine (#19473) though it is still under review.

**Comment by rojkov** [comment]
> the expressions are not complicated but the routes themselves are long

IIRC we always do RE2::FullMatch for routes. And in case of long route strings this type of matching is not very performant. RE2::PartialMatch with anchors in the regexes could help, I guess.

/cc @snowp @jmarantz

**Comment by jmarantz** [comment]
@adisuissa @htuch 

See also https://github.com/envoyproxy/envoy/issues/6602

I think variants on how to evaluate regexes linearly are never going to be enough. We need a routing specification that enables holistic evaluation via a trie.

**Comment by mirwide** [comment]
Combine math by prefix and regexp in route config will improve performance. If split route by section and build tree, possible to reach complexity O(log n).
This case has route format
```
/a1/b1/[^/]+/d1
/a1/b1/[^/]+/d2
/a1/b1/[^/]+/d2/[^/]+
...
/an/bn/[^/]+/dn
```
Match only 1 section by 1 regexp rule and 0-3 section with regexp in route. Section has 50-100 variant value.

I compare performance envoy with 4000 regexp route and 800 regexp route with similar traffic and same filter config in prodaction. Result to be depressing.
Utilization per 1000 rps
|rule|mCPU|
|-----|-----|
|800|1800|
|4000|6500|

**Comment by htuch** [comment]
@jmarantz this exists now with unified matching, @snowp

**Comment by jmarantz** [comment]
Should #6602 be closed then?

**Comment by htuch** [comment]
Depends on the progress - we have a matcher field in `VirtualHost` but not sure where it's at, @snowp can comment.
