### ISSUE TITLE
Filter modification of request routing

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2015]
There are various applications where we would want to be able to modify the route in an L7 filter, e.g. based on a gRPC call to an external server, decide which cluster to send the cluster to, and continue with the normal request filter pipeline. This issue will track work here. @mattklein123 for SWAG and history.

**Comment by mattklein123** [comment]
This is a straightforward feature to add. Basically I would do the following:

Add new filter callback API `setRoute(Router::RouteConstSharedPtr)` here: https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L118

Any future filters will see this route. If you are only going to use this from private code, this is all you need to do (+ basic tests obviously). If you want to have some kind of self contained RouteImpl in public code to share, that would be nice too, but not required.

**Comment by mattklein123** [comment]
Small additional note. AsyncClient already has a standalone set of route impl stuff: https://github.com/envoyproxy/envoy/blob/master/source/common/http/async_client_impl.h#L183. These should be pulled out into a standalone thing that can be used both in AsyncClient as well as by filter writers.
