### ISSUE TITLE
matcher: support prefix match map for prefix matching

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#20198]
*Title*: matcher: support prefix match map for prefix matching

*Description*:

https://github.com/envoyproxy/envoy/blob/9adf1704c62725b324112beec2a50fbd1fa602ed/source/common/matcher/matcher.h#L225-L226

As mentioned in #6602 and #20147, we would like to have a prefix matching mechanism for route matching. Fortunately, the unified matching API provides an interface for prefix matching, but the code has not been implemented in Envoy. It would be good if we can support the prefix matching which can potentially help improving the performance of Envoy.

**Comment by zhxie** [comment]
I am not sure if someone is working on it, and if not, I would like to help. @snowp

**Comment by seblaz** [comment]
Hi @zhxie! Thanks for implementing this, do you know if this is release in some version of Envoy? Because I couldn't find it in the changelog

**Comment by zhxie** [comment]
No, API of prefix matching has been introduced in earlier version, this patch only add the implementation so it does not have a release note.

**Comment by seblaz** [comment]
Great, and do you know in which version of Envoy was it included?

**Comment by zhxie** [comment]
Since it is merged in March, it should be delivered from v1.22.

**Comment by seblaz** [comment]
Thanks!
