### ISSUE TITLE
Percentage based enablement of Rate limit filter

### ISSUE THREAD

**Issue by rene-m-hernandez** [envoyproxy/envoy#20195]
After reviewing the RateLimit filter documentation, I was hoping to take advantage of this feature as a way to ramp up a new RLS implementation:

> ratelimit.<route_key>.http_filter_enabled  
% of requests that will call the rate limit service for a given route_key specified in the [rate limit configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit). Defaults to 100.  

However, this appears to be ["runtime" only setting](https://www.envoyproxy.io/docs/envoy/v1.20.0/configuration/http/http_filters/rate_limit_filter#runtime). As far as I can tell, there is no way to set this via xDS (apologies if I did not look hard enough); therefore, if I wish to selectively apply the filter, I must make filesystem updates which is not something I do.

Would it be possible to configure this behavior via a setting in Network/HTTP filter configuration (LDS) or via a setting in the Route configuration (RDS)?

**Comment by rojkov** [comment]
Have you checked RTDS (Runtime Discovery Service)?
