### ISSUE TITLE
8001/clusters?format=json doesn't support json response encoding

### ISSUE THREAD

**Issue by toaler** [envoyproxy/envoy#2020]
Response format: 8001/clusters?format=json doesn't support json response encoding

*Description*:

Nope, just curl a request against 8001/clusters?format=json doesn't support json response encoding.

*Repro steps*:

curl "http://<host>:8001/clusters?format=json

Returns just a list of metric/value pairs.

**Comment by mattklein123** [comment]
Related to https://github.com/envoyproxy/envoy/issues/1522. We would like to define all the admin outputs in proto which will allow auto JSON output.
