### ISSUE TITLE
Reducing Docker image size

### ISSUE THREAD

**Issue by mieubrisse** [envoyproxy/envoy#20215]
The Docker image currently being published is 28.3MB compressed. When running the image, the vast bulk of it is due to the 53.9MB `envoy` binary in `/usr/local/bin`. Is there any way to make this smaller? We're trying to bundle an Envoy proxy along with a gRPC server so that the gRPC server can be accessed via `grpc-web`, but adding Envoy is taking our image size from 10MB to 38MB compressed.

**Comment by mattklein123** [comment]
Unfortunately no, there is no easy way to make this smaller. If you compile a custom Envoy and remove all extensions other than the ones you need that would help a lot.

**Comment by mieubrisse** [comment]
How can I do that @mattklein123 ? I'm not seeing a way to disable extensions in https://github.com/envoyproxy/envoy/tree/main/ci#building-and-running-tests-as-a-developer

**Comment by moderation** [comment]
@mieubrisse Instructions for disabling optional features and extensions is covered at https://github.com/envoyproxy/envoy/tree/main/bazel#disabling-optional-features. Interestingly enough you can even compile out Google gRPC and still have the gRPC features work. Big wins including compiling out WASM. An example `~/.bazelrc` file is:

```bazel
build --define deprecated_features=disabled
build --define disable_object_dump_on_signal_trace=disabled
build --define hot_restart=disabled
build --define google_grpc=disabled
build --define path_normalization_by_default=true
build --define quiche=enabled
build --define signal_trace=disabled
build --define wasm=disabled
build --define zlib=ng
build --override_repository=envoy_build_config=/home/<username>/Library/envoy/build
```
The last line points my custom [extensions_build_config.bzl](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_build_config.bzl) that has the majority of the extensions removed. You will be able to significantly reduce the binary size with the combination of these two approaches

**Comment by mattklein123** [comment]
Thank you for the instructions @moderation!
