### ISSUE TITLE
How to config the ring hash min size of the cluster runtime?

### ISSUE THREAD

**Issue by richardor** [envoyproxy/envoy#2021]
@mattklein123 
refer to ： https://www.envoyproxy.io/envoy/configuration/cluster_manager/cluster_runtime
cause the default size of ring hash is 1024, I want to set it larger. how to config it?

my configuations are as follows:
  "cluster_manager": {
    "clusters": [
      {      
        "name": "service1",
        "connect_timeout_ms": 250,
        "type": "strict_dns",
        "lb_type": "ring_hash",
         "features": "http2",  
          "hosts": [
          { 
            "url": "tcp://ip1:8888"
          },
          {
            "url": "tcp://ip2:8888"
          }
        ]
      }
    ]
  }

**Comment by danielhochman** [comment]
Currently it's not configurable except with a [runtime value](https://www.envoyproxy.io/envoy/configuration/cluster_manager/cluster_runtime.html?highlight=ring_hash#ring-hash-load-balancing) that globally affects all `ring_hash_lb` clusters.

It will be fixed shortly. The configuration was added to the data plane in https://github.com/envoyproxy/data-plane-api/pull/202. Now I need to wire it up in Envoy itself. Will have a change merged by next week to do that. In the meantime you can use the runtime value for testing if you'd like.

**Comment by mattklein123** [comment]
Closing this out as answered.
