### ISSUE TITLE
Is there any metric to track requests with status code = 0?

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#20246]
## Description

Is there any metric which could be used to track the number of requests with final status code = 0? When clients close the request before Envoy could respond, the access logs record the final status code as `0`. 

We are wondering if there is any metric emitted from the HCM which could be used to accurately track such requests? I think `downstream_cx_destroy_remote_active_rq` is close enough but it'd be nice to see if there are any dedicated counter(s) to track such requests.

**Comment by jmarantz** [comment]
I don't think there's a an rq_0xx or rq_000 stat available right now but it would be easy to add I think.

**Comment by frankh** [comment]
this is a pretty important missing feature

`downstream_cx_destroy_remote_active_rq` is kind of close, but that's not aggregated per upstream cluster so of limited value

really the rq_xx metrics should include `0` or `499` for these requests

**Comment by andrew-demb** [comment]
I've just opened a new issue for this feature request https://github.com/envoyproxy/envoy/issues/40224
