### ISSUE TITLE
stats: native datadog tagged metric support

### ISSUE THREAD

**Issue by kevintchan** [envoyproxy/envoy#2024]
I'd like to take advantage of recently introduced tag support [Add configurable stats tags #1852](https://github.com/envoyproxy/envoy/pull/1852), but there's no sink support yet. Is it possible to extend the current statsd sink or create a new statsd sink which includes tags?

**Comment by mattklein123** [comment]
@kevintchan the statsd protocol does not support tags, so it's impossible to add it. When speaking about tags, the stats backend you are talking to must support it. E.g., we are adding Prometheus support which supports tagging. What actual backend are you talking to?

**Comment by mattklein123** [comment]
Sorry I see it in the title: Datadog. OK will live it open to track native Datadog support.

**Comment by jippi** [comment]
if prometheus tagged metrics land, then using telegraf or similar tool to scrape it out and emit it to datadog is trivial 30line config, thats how we've done it everywhere in our infra so far :) 

especially since there are way more projects supporting prometheus than datadog these days :)

**Comment by taiki45** [comment]
Same here for some reasons:

- My stats wire was already built for statsd.
- It seems Envoy has one step to support full Prometheus metrics (HDR histogram). ref: https://github.com/envoyproxy/envoy/issues/1947
- I have some short-lived Envoy containers which run as side-car with short-lived service-level batch jobs.

When Envoy fully supports Prometheus metrics, I might be able to switch to [Prometheus Pushgateway](https://prometheus.io/docs/instrumenting/pushing/). But for now, I think I want to use the DogStatsD extention.

I'm working on the new sink right now. It will be > 100 LOC change set without test and change user-facing behavior (offers new configuration). How can I move this forward?

**Comment by mattklein123** [comment]
@taiki45 if it's a new sink with dedicated config, etc., please just do the PR. Let us know if you need any help.

**Comment by taiki45** [comment]
@mattklein123 Thanks. So when I finish my work, I'll make the PR and let's discuss there.
