### ISSUE TITLE
refactor `re2.max_program_size.error_level`to not use global ints

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#20254]
*Title*: Deprecated `re2.max_program_size.error_level`

*Description*:
`envoy envoy_bug envoy bug failure: false. Details: The Envoy community is attempting to remove global integers. Given you use re2.max_program_size.error_level please immediately file an upstream issue to retain the functionality as it will otherwise be removed following the usual deprecation cycle.` since https://github.com/envoyproxy/envoy/pull/20168.

As far as I know, there is no alternative for this option. The proto api/envoy/type/matcher/v3/regex.proto even explicitly recommends to use this field.

We need some non-deprecated way to to make Envoy allow larger regex's than the default (100)
cc @alyssawilk 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk

**Comment by alyssawilk** [comment]
Coming back to this I would say we should support it if no one is using it. If as you say it's mentioned in the APIs I think we'd have to leave it around for a full year, but if no one has had complaints after a year because no one uses it, why should we keep it in the code base?

**Comment by howardjohn** [comment]
We do use it and will continue to use it unless an alternative is implemented. We have strong requirements to have regex over the default size

**Comment by alyssawilk** [comment]
Ah sorry, that wasn't clear.  I'll make sure I replace it then. Thanks for responsibly (and quickly!) reporting!

**Comment by mattklein123** [comment]
I'm thinking that for this one perhaps this would be a good candidate for a CLI flag and some kind of global value? I just don't see anyone setting this on a per regex basis. The other option would be an env variable, though we don't have any precedent for that.

**Comment by alyssawilk** [comment]
I can also just leave the runtime variable as-is, and do the plumbing to not have the access illegal.  I think that'd be the minimum if I can do it without refactoring the world
