### ISSUE TITLE
Historic docs versions were not published (due to bad versioning)

### ISSUE THREAD

**Issue by cboitel** [envoyproxy/envoy#20286]
*Title*: Version history states a published version is pending

*Description*: 

If you look at the version history for version v1.21.1, it states v1.21.1 is pending instead of listing date version was pusblished.

* [v1.21.1 version history](https://www.envoyproxy.io/docs/envoy/v1.21.1/version_history/version_history)

By the way, v1.20.2 isn't listed on [envoy's doc main page](https://www.envoyproxy.io/docs)

**Comment by phlax** [comment]
i believe the version issue is known/resolved if not yet published cc @RyanTheOptimist (related issue #20098)

wrt the docs not being published, i can look into that

**Comment by phlax** [comment]
@cboitel i have renamed/hijacked your issue to focus on the docs publishing issue which is a slightly bigger problem

I updated the docs publishing system some time ago, and it works fine for publishing anything from that point on, but the required changes for the new pipeline were not backported, so historical versions are not being published

Ideally we backport the changes - im struggling to think of any other workaround

cc @RyanTheOptimist

**Comment by phlax** [comment]
hmm, just realizing the changes we made were only to the `latest` publishing pipeline - so this should have just worked - maybe its because CI is failing and not reaching the required docs publishing stage - ill check CI...

**Comment by phlax** [comment]
the problem is the version numbers preventing publication

```console
Given git tag does not match the VERSION file content:v1.20.2 vs v1.20.2-dev
```

Given git tag does not match the VERSION file content:v1.20.2 vs v1.20.2-dev

**Comment by cboitel** [comment]
Looks like the v1.21.1 pipeline was ok regarding doc publishing but doc fails to be generated correctly 

https://dev.azure.com/cncf/envoy/_build/results?buildId=102210&view=results

**Comment by phlax** [comment]
the verify issue is separate - and has been addressed now i think (flake8 dep went stale)

the docs for the immediately prior patch version should be almost correct

we are discussing what to do regarding the failed builds and `-dev` suffix on the productions builds - specifically whether its worth creating a release to rectify
