### ISSUE TITLE
Effective TLS version used in a mesh

### ISSUE THREAD

**Issue by trstringer** [envoyproxy/envoy#20280]
*Title*: *What is the effective TLS version used when Envoy proxies are meshed together?*

*Description*:

I understand from the [TLS configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto) that Envoy defines a min and max TLS version. But in the case of `client -> server` in a mesh where this is `Envoy -> Envoy`, what will be the requested TLS version in the ClientHello message? Will it be the client Envoy's min or max TLS version? Or some other determining factor?

**Comment by daixiang0** [comment]
I think two Envoy use same TLS version.

**Comment by trstringer** [comment]
@daixiang0 thank you for your message! Yes I would imagine they use the same TLS version, but the initiating Envoy proxy (the "client") sends the ClientHello message and requests to use which version of TLS? The max TLS version configured for the instance of Envoy? Or something else?

Thank you again for the assistance!

**Comment by ggreenway** [comment]
The maximum value that both sides support will be used. If the two sides don't share any common versions (one side is TLS1.3 only, other side is TLS1.2 only), the handshake will fail and they won't be able to communicate.

**Comment by trstringer** [comment]
Great thank you for the clarification!
