### ISSUE TITLE
active healthchecking: add logging 

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#2028]
Similar to the [outlier detection log](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/outlier#ejection-event-logging), a healthchecking log would be useful for observing production behavior at more detail than stats provide.

**Comment by mattklein123** [comment]
@jsedgwick big +1 to the general plan. I don't feel super strongly where the proto is placed. IMO I would actually probably put it here: https://github.com/envoyproxy/data-plane-api/tree/master/envoy/api/v2/cluster since it's part of core cluster management.

**Comment by jsedgwick** [comment]
@mattklein123 interesting, I like the idea of having these (and there will be more, presumably) alongside the components they're logging for. I guess my concern is discoverability if logging structures aren't all in the same-ish place. Trying to cc Brian if he's opinionated about that (I'm not, really) but can't find his username here.

In any event, I'll get this going with `api/v2/cluster/{outlier_detection/active_healthcheck}_log.proto` for now

**Comment by mattklein123** [comment]
I don't really have a strong opinion about this either. I don't think discoverability is really that big of a problem in general in this case. I assume you are referring to @brian-pane?

**Comment by jsedgwick** [comment]
Nope meant @btc, github wasn't recognizing his handle on autocomplete.
Anyways, SGTM in `cluster/`

**Comment by btc** [comment]
I agree it is reasonable to bundle the data proto messages by feature. I don't have a strong opinion and `cluster` SGTM. I presume the gRPC service definition, once defined, will be located in [data-plane-api/envoy/service](https://github.com/envoyproxy/data-plane-api/tree/master/envoy/service). 👍
