### ISSUE TITLE
Add CLI flag to disable hot restart

### ISSUE THREAD

**Issue by tlhunter** [envoyproxy/envoy#2029]
Hot Restart should be disable-able via a CLI argument

> mklein [4:28 PM] 
not currently, we could add a CLI option to disable hot restart
[4:29] 
please file an issue on that

https://envoyproxy.slack.com/archives/C78M4KW76/p1510187339000151

**Comment by tonya11en** [comment]
Should this flag replace the bazel build argument '--define hot_restart=disabled' or exist with it?

I was poking around for low-hanging fruit and this seemed pretty straightforward.

**Comment by mattklein123** [comment]
@tonya11en I would probably leave the compile flag as some people want the ability to just compile out the functionality entirely. I think doing a CLI flag alongside would be pretty straightforward.
