### ISSUE TITLE
[Question] Is it possible to run envoy in docker but proxy to a service running on windows host outside of docker

### ISSUE THREAD

**Issue by AtLeastITry** [envoyproxy/envoy#20314]
*Title*: 
Is it possible to proxy a request to a service running outside of docker

*Description*:
I'm attempting to communicate to a envoy proxy hosted in a docker container, but have it proxy a request to a service outside of docker. 

For example imagine the following setup:
- Service A (UI client)
- Service B (Envoy proxy)
- Service C (API running locally on my windows machine via kestrel outside of docker)

What i want is: 
1. Service A makes a request to Service B
2. Service B proxies the request to Service C
3. Service C then returns a response back 
4. Service B Then proxies the response back to service A
5. Service A can consume the response

What is happening:
1.  Service A makes a request to Service B
2. Service B fails to proxy the response with the following error: `upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: immediate connect error: 99`

*Things I've tried that didn't work*
- Running the service in WSL2 directly
- Setting the socket_address whilst having the type as logical_dns:
   - 127.0.0.1
   - 172.31.247.252 (this was the IP of the WSL instance running at the time)
- Setting the socket_address whilst having the type as static:
   - localhost

*Extra notes*
- I'm running docker directly in WSL2 and not using Docker desktop so things like "host.docker.internal" do not exist

**Comment by daixiang0** [comment]
(Not test) In Linux, I think it works as I can use host IP in container, in Win, not sure.

**Comment by AtLeastITry** [comment]
> (Not test) In Linux, I think it works as I can use host IP in container, in Win, not sure.

I did try running the service directly in WSL (outside of docker) and then point to the WSL host IP in the envoy config but that still didn’t work. Maybe it’s just an unsupported scenario?

**Comment by phlax** [comment]
no idea about windows im afraid, but i would suggest that this comes down to your docker networking config (see https://docs.docker.com/network/) - which can be configured in many different ways
