### ISSUE TITLE
build envoy from a machine without internet access

### ISSUE THREAD

**Issue by railwaycat** [envoyproxy/envoy#20318]
Hi, we are trying to use Envoy in a project, it requires us to build Envoy from source code on a machine which has no access to internet. I would like to know if there is any way to do that? I searched the envoy document but didn't able to find a clue. 

I tried the following:

1. Bazel is able to fetch all dependencies to local cache directory by `bazel fetch envoy`. But our download gateway is not a build machine, we are not able to run bazel on it. 

2. Bazel has an option `--distdir` to get all dependency tarballs from a local directory, if we can download them separately without bazel. I know the direct dependencies are in file https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl, but that is not all the dependencies in recursive (dependencies of dependencies). Is there an easier way to list all the dependencies (name/url) in recursive?

Thank you for any help!

**Comment by phlax** [comment]
see here for some docs on querying/listing transitive dependencies:

https://bazel.build/docs/query-how-to

there are also separate dependencies defined for the api - in `api/bazel/repository_locations.bzl`

**Comment by railwaycat** [comment]
Thanks @phlax! I haven't try `bazel query` command, will play with it!

**Comment by wbpcode** [comment]
The `bazel sync` is also a possible method. https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html

**Comment by railwaycat** [comment]
Thanks @wbpcode. I tried both `bazel fetch envoy` and `bazel sync` commands. My experience is:

- `bazel fetch envoy` finishes without any error, however the cached content is not enough for Envoy offline build, bazel still complains failure on download dependencies for example "zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz"
- `bazel sync` finishes with some error output, but then Envoy **is** able to build without internet access. 

I'm thinking of extract URLs from the output of `bazel sync --experimental_repository_resolved_file=` and download them separately. 

Is there an official recommend method to build Envoy on a offline machine? I can't find it from Envoy document.

**Comment by wbpcode** [comment]
As far as I know, here is no an official method to do this. 
My own method as a reference:
- Get all the deps by the `bazel sync` and then download them.
- Create new build image based on the `envoyproxy/envoy-build-ubuntu:xxxxxxx` and downloaded deps. Set the `BAZEL_BUILD_EXTRA_OPTIONS` by the env variable.
- Use the new build image as my develop & build env.

**Comment by railwaycat** [comment]
I believe tried similar steps to yours @wbpcode but there is a gap for me between step 1 and step 2:

The content of deps cached by `bazel sync` are un-tarred, deps are extracted to each directories. I found them at `~/.cache/bazel/_bazel_xxx/<workspace hash>/external/`. But `--distdir` option asks for a directory with tarballs. I learned this from an open issue of bazel[^1].

Can I know more details on how you are using the results from `bazel sync` of step 1 for `--distdir` build options in step 2? I will appreciate that!

[^1]: https://github.com/bazelbuild/bazel/issues/13493

**Comment by railwaycat** [comment]
I believe I found how to fill the gap: 

1. Use `bazel sync --repository_cache=$HOME/foo` to specify a directory for cache. The structure of this directory will be like `$HOME/foo/content_addressable/sha256/<hash of each deps>/<renamed tarball>`.

2. Build with `bazel build envoy --distdir=$HOME/foo`.

Now the next step for me is how to make the first step through another gateway machine.

**Comment by wbpcode** [comment]
> I'm thinking of extract URLs from the output of bazel sync --experimental_repository_resolved_file= and download them separately.

I download all the deps in the resolved file and compress it to a tar.

**Comment by railwaycat** [comment]
I thought I succeed the build by `--distdir` directory but it turns out might be the cache from bazel itself:(

Could you let me know how you download all the deps in resolved file? Is it by a bazel Starlark script or a single command? Sorry my bazel knowledge is limited..
