### ISSUE TITLE
Istio not giving metrics like istio_requests

### ISSUE THREAD

**Issue by doverk96** [envoyproxy/envoy#20325]
Hey,
I have Istiod set in my k8s cluster, tried running httpbin sample application and then tried to manual inject envoy sidecar using command Kubectl apply -f <(istioctl Kube-inject -f httpbin.yaml).
It has started emitting metrics but am not able to get metrics like requests total.
My objective is to get requests duration, api latency

**Comment by tommorvolloriddle** [comment]
Hi Ronak
I am a beginner and trying to setup Kubernetes cluster in hybrid mode.
I have a Linux master node and windows worker node with Istio. I want to inject istio-proxy side car inside windows application pod.
Could you please help me with this.
TIA.

**Comment by doverk96** [comment]
Hey, I simply used istioctl kube-inject command, available on istio documentation.
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#manual-sidecar-injection

**Comment by ggreenway** [comment]
@doverk96 this seems like more of an istio than an envoy question. I suggest asking over there.
