### ISSUE TITLE
registry: templated factory registrations inheritance

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#20324]
*Title*: registry: templated factory registrations inheritance

*Description*:
Currently, factory registrations for base class cannot be used by their derivations. For example, an input `Input` registered for `BaseClass` cannot be created from a factory of `DerivedClass`. We do not have any precedence for these interactions with the existing extension registries, so it will be better if we can come up with a good solution to support shared inputs.

*Relevant Links*:
#20116

**Comment by kyessenov** [comment]
Another instance where factories might need to be smarter: custom tree matchers are specialized by `DataType` even though the matchers do not directly inspect the data. That means we have to register the same matcher for each possible `DataType`.
