### ISSUE TITLE
Consume bootstrap_extension in config_test

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#20335]
im wondering if its possible that config_test cant handle `bootstrap_extension` ?

i can see one of the example yaml files in the docs has a `layered_runtime` but i dont see any with `bootstrap_extension` so im wondering if that is the culprit

_Originally posted by @phlax in https://github.com/envoyproxy/envoy/pull/19467#discussion_r824343681_

**Comment by kyessenov** [comment]
not stale. I'm wondering it myself as I'm noticing presumably validated samples that shouldn't be right.
