### ISSUE TITLE
Script to automate envoyproxy/data-plane-api SHA updates to envoyproxy/envoy

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2033]
Whenever `data-plane-api` is updated, we need to put in a commit to the main Envoy repo to update `envoy_api_deps()`. This is a bit of a futz, in particular when we move docs to `data-plane-api` (likely today/tomorrow). This could easily be automated away, by writing a script that automatically creates a PR in the main Envoy repo to do the SHA bump.

An example of how it could work would be to live in `data-plane-api/tools`, do a shallow Envoy clone in a tmp dir, create PR, push to GH and teardown. Or, it could be in `envoy/tools` and do some stateful stuff on the current git tree, creating and removing branches as needed.

I think this should only be a couple hundred lines of Python/Go/Fortran/Cobol.

**Comment by kragniz** [comment]
I'm pretty sure you can do this only using the github API, I'll have a play around and see if it's possible

**Comment by kragniz** [comment]
It is possible: https://gist.github.com/kragniz/db79fc0695e4c1567a5933e1be306aa2

#2364 was created with this.

**Comment by kragniz** [comment]
This is going to create a PR on *every* commit to `data-plane-api`, let me know if that's overly enthusiastic

**Comment by mattklein123** [comment]
@kragniz I will be honest I'm kind of ambivalent about doing this. I don't think lack of auto update has been a big pain point for us (not to mention we would need to find a place to run the bot code). @htuch WDYT? I'm inclined to just close this. (@kragniz sorry that you potentially did work that won't be used, though we will have the gist if we want to go back to this at some point).

**Comment by htuch** [comment]
I like the use of GH APIs for this. My main concern is that sometimes the update needs manual intervention (e.g. if some non-frozen field names changes), then you need to do a local PR. I think if you could manually run the script to generate the PR and kick it off when you've made a change it would be a nice convenience.

**Comment by kragniz** [comment]
It's currently running on one of my servers, I can turn it off if it's not helpful

**Comment by mattklein123** [comment]
@kragniz I think we have decided to turn the bot off for now. If possible do you think you could submit the code as a script that could be run by someone manually? cc @envoyproxy/maintainers

**Comment by kragniz** [comment]
No probs, it's turned off now. I'll clean up the script and submit it later

**Comment by kragniz** [comment]
I pushed it over here: https://github.com/envoyproxy/data-plane-api/pull/419

**Comment by mattklein123** [comment]
Thanks @kragniz! Going to close this one out for now.
