### ISSUE TITLE
stats: create integration subtest to capture # of counters and gauges so we can track their increase

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#20341]
test/integration/stats_integration_test.cc was previously able to detect incremental increases in per-cluster memory use, but this capability was lost when tcmalloc stopped reporting a deterministic number of bytes allocated >1 year ago. Since then we can only set approximate thresholds, and can't flag PRs that increase per-cluster stat overhead to evaluate whether the increased memory usage brings justifiable value.

A more deterministic approach is to simply count the # of stats-per-cluster. This can use the same test infrastructure but simply add a new test. I'll do this during post-perf code therapy.

**Comment by jmarantz** [comment]
@ggreenway @alyssawilk here's an outline of my proposed solution to the test flakes issue @alyssawilk fixed in #20338

**Comment by alyssawilk** [comment]
I don't understand the value of having a test which fails every time we add a stat.  Can't we track the increase in the number of stats just by looking at the files where they're added?

**Comment by jmarantz** [comment]
They can be added in a number of places, so it might be hard to (say) have a format-check that scans source files. Adding individual stats is never a problem; the issue is adding stats that will be replicated per cluster or other high-cardinality config.

Having the expected-count change in the PR has the value that it triggers us to question whether the value the stat adds is worth the permanent memory increase for all users, and possible remedies include putting the stat in an optional block, which is enabled by a runtime flag. That's been done in a few places.
