### ISSUE TITLE
Envoy CDS update issues when using stats reject_all

### ISSUE THREAD

**Issue by gschier** [envoyproxy/envoy#20355]
When using the following config to disable stats, clusters get configured properly on initial boot and the first time they're changed, but any additional updates never occur.

```yaml
stats_config:
  stats_matcher:
    reject_all: true
```

When the above config is removed, everything returns to normal. Is there some sort of stat, similar to https://github.com/envoyproxy/envoy/issues/8473, that is required for cluster update to happen? I'm not using healthchecks, and updates go through Delta XDS using CDS via `go-control-plane`.

**Comment by jmarantz** [comment]
reject-all is really not useable IMO. See discussion in https://github.com/envoyproxy/envoy/issues/14610 and proposal in https://docs.google.com/document/d/1CnyeIi5hMBqXZRKm-0_yW3yy69HM80BHg-EGwkJb-qw/edit

**Comment by gschier** [comment]
Thanks for the reply, and good to know I'm not crazy. I've switched to using `exclusion_list` with a prefix defined to exclude all my internal resources.
