### ISSUE TITLE
buffer: memory copy hardware offloading

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#20362]
*Title*: buffer: memcpy hardware offloading

*Description*:
We are seeking opportunity to accelerate memory copy by hardware offloading. In our early PoCs, we found that hardware offloading of memory copy in some case with big size data movement (e.g., TLS) would bring throughput improvement and latency reduction. We would be glad if we can introduce the method to Envoy to improve the performance.

We have an open and wish to get feedback on.

>Currently, memory copy happens majorly in buffer (e.g., OwnedImpl::copyOut, Slice::append) which is difficult to make extensible. We would like to generate a memory copy provider which provides memory copy method from bootstrap configuration, and store the provider into a singleton for OwnedImpl and Slice to access.

**Comment by wbpcode** [comment]
will this memcpy hardware offloading brings additional overhead for the fragmented memory copy?

**Comment by zhxie** [comment]
We can add some if else branches to only offload large enough memcpy to the hardware in our memory copy provider.

**Comment by wbpcode** [comment]
The copy operation may be very frequent. While one-time if/else is very cheap, frequent if/else comes with some overhead.

**Comment by wbpcode** [comment]
If there are relevant benchmarks that prove that this work can indeed improve performance. 
Then my suggestion is to provide some new buffer API to handle hardware offloading. Users can optionally use these APIs (such as in TLS).

**Comment by zhxie** [comment]
But in that way, codes in existing extensions have to be changed. And I think it is not a common way.

**Comment by daixiang0** [comment]
> If there are relevant benchmarks that prove that this work can indeed improve performance. Then my suggestion is to provide some new buffer API to handle hardware offloading. Users can optionally use these APIs (such as in TLS).

New buffer API is easy but brings more cost for users due to code changes. If Envoy support extend buffer API, users can easily get its benefit, what users only need to do is change the config. It is hard but worth doing I think.

**Comment by ggreenway** [comment]
Can you elaborate on what type of hardware offload you're using? For the types of solutions I'm imagining, you would send a work-request to memcpy to the hardware, go away and do something else, then come back when the hardware has said it is finished. If that's the case, it could be very disruptive to the codebase because many common operations would become asynchronous, and I'm skeptical that there is a significant performance improvement, without benchmarks to see the improvement.

**Comment by ggreenway** [comment]
Can you describe the hardware, and the interface to using it? At what size of a copy does it become more efficient to use this hardware than a normal cpu-based memcpy?

**Comment by zhxie** [comment]
We are going to use [Intel DSA](https://01.org/blogs/2019/introducing-intel-data-streaming-accelerator), which provides a sync blocking and async polling interface for memory copy offloading. [The high-level API](https://github.com/intel/DML/blob/5a2956362d7b1c65d8aee753938ae9bf5cf0b7fd/include/dml/hl/execute.hpp#L87) looks like `execute(const data_view, data_view)` which is similar to `memcpy(void*, const void*, size_t)`. Currently, we did not have open cut-off point data for the solution, but it gains performance improvement in our PoCs , in which we replace `memcpy` directly and have a lot of 16 kB memory copies.

**Comment by ggreenway** [comment]
As a starting point, I'd recommend replacing memcpy with the hw acceleration, make a build, and produce some benchmark results. Then share the code changes and benchmark results here, and we can figure out the next steps. It might make more sense as a compile-time option than a configuration option.

**Comment by daixiang0** [comment]
Still available.

**Comment by daixiang0** [comment]
Still available.
