### ISSUE TITLE
verify_examples is broken on v1.18

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#20360]
verify_examples for cache and dynamic-config-cp are both broken on v1.18. I tried to cargo-cult my way around these issues in #20223 but wasn't able to get it across the finish line. 

https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/103180/logs/249

**Comment by RyanTheOptimist** [comment]
@oschaaf can you take a look at this with your Release Manager hat on?

**Comment by phlax** [comment]
not sure why this didnt close - but i think the issue is resolved
