### ISSUE TITLE
What does requested_server_name mean in access log?

### ISSUE THREAD

**Issue by juchaosong** [envoyproxy/envoy#20373]
*Title*: *What does requested_server_name mean in access log?*

*Description*:
> I find when requested_server_name and authority are different in the access log, the request will return 404 code.
> But I don't know what does the requested_server_name mean and why it different from authority?
```
{
  "request_id": "4d5ee90d-cc10-9152-884e-2e9fbdda434c",
  "authority": "grpc-gateway.dev.gs-robot.com",
  "path": "/tempo/v1alpha1/manifests?page=1&pageSize=10",
  "response_code": 404,
  "upstream_cluster": null,
  "duration": 0,
  "response_code_details": "route_not_found",
  "x_forwarded_for": "116.227.21.55",
  "upstream_local_address": null,
  "downstream_remote_address": "116.227.21.55:49927",
  "bytes_sent": 0,
  "start_time": "2022-03-16T13:21:08.687Z",
  "downstream_local_address": "172.19.145.197:8443",
  "connection_termination_details": null,
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
  "upstream_host": null,
  "upstream_transport_failure_reason": null,
  "response_flags": "NR",
  "route_name": null,
  "method": "OPTIONS",
  "upstream_service_time": null,
  "requested_server_name": "api-gateway.dev.gs-robot.com",
  "bytes_received": 0,
  "protocol": "HTTP/2"
}
```

[optional *Relevant Links*:]
>[http-404-when-authority-and-requested-server-name-are-different](https://discuss.istio.io/t/http-404-when-authority-and-requested-server-name-are-different/10713)

**Comment by ggreenway** [comment]
Most commonly, requested_server_name is the value in TLS server-name-indication. But if you're not using TLS, other transport protocols could set this field from an analogous field.

**Comment by lambdai** [comment]
another view is that requested_server_name is per tls connection wide attribute and authority is per http request attribute

**Comment by spencercjh** [comment]
We finally found that the problem was caused in this issue: https://github.com/istio/istio/issues/9429
