### ISSUE TITLE
unified header formatter and substitution formatter

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#20389]
*Title*: *unified header formatter and substitution formatter*

*Description*:

As the title, now the header formatter and substitution formatter provide not exactly the same command, can we try to unified them?

Related issue: #15036 #7213

**Comment by cpakulski** [comment]
I can take this issue. Have been doing some prototyping to divide formatters into those which operate only on StreamInfo and those which need request and response headers and trailers.

**Comment by wbpcode** [comment]
Thanks. I would like to help review it.
