### ISSUE TITLE
Release schedule for mutation_rules in ext_proc

### ISSUE THREAD

**Issue by technicianted** [envoyproxy/envoy#20384]
*Title*: *Release schedule for mutation_rules in ext_proc*

*Description*:
Support for `mutation_rules` has been merged in main branch by #19622 last January. What's the plan to be in a release branch?

**Comment by wbpcode** [comment]
We may create a new release version at 2022/04/15. Check https://github.com/envoyproxy/envoy/blob/main/RELEASES.md for more info.
