### ISSUE TITLE
config_load_check_tool seems to always reject config files

### ISSUE THREAD

**Issue by hammett** [envoyproxy/envoy#2040]
*Title*: Tool fails with the example configs on the repo

*Env*: MacOS

*Envoy Version*: master from github as of today

*Description*:
Grab a simple config like https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/front-envoy.json

Running the check tool yields:
`
...
[2017-11-09 19:11:51.894][262074][debug][upstream] source/common/upstream/cluster_manager_impl.cc:508] shutting down thread local cluster manager
JSON supplied is not valid. Error(offset 0, line 1): Invalid value.
`

Using the same config file in a docker file and starting it up seems to work fine.

**Comment by mattklein123** [comment]
@junr03 could you take a quick look at this?

**Comment by junr03** [comment]
@hammett the input for the tool is a directory that holds configuration files. The tool tests all files in the directory for validity. That means that if you ran it on the entire https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/ directory, it will fail on all the files that are not configuration files.

**Comment by hammett** [comment]
Makes sense. so it's trying to parse a dockerfile and failing. thanks!
