### ISSUE TITLE
bug??

### ISSUE THREAD

**Issue by gnblao** [envoyproxy/envoy#20407]
https://github.com/envoyproxy/envoy/blob/52668550a903d528cb4f7ee2eb815e76e44363c5/envoy/registry/registry.h#L181

**Comment by gnblao** [comment]
I think so：
         static absl::flat_hash_map<std::string, Base*>  *factories；
         if (!factories)
              factories = new absl::flat_hash_map<std::string, Base*>;

**Comment by KBaichoo** [comment]
the local static declaration of factories in that function effectively only initializes it once. e.g. it's essentially the code you wrote.
