### ISSUE TITLE
OOTB compression support for /stats/prometheus endpoint 

### ISSUE THREAD

**Issue by demandbase-gmavadiya** [envoyproxy/envoy#20417]
*Title*: *Compression support for /stats/prometheus endpoint *

*Description*:
>Currently any request to /stats/prometheus endpoint with `accept-encoding: deflate,gzip` responds with a `content-type: text/plain; charset=UTF-8`. Given the amount of metrics, this significantly increases the amount of data that needs to be transferred translating to higher costs. We did some testing on istio sample app and the metrics data size reduced from 89K to 11K when gzip was enabled.

[optional *Relevant Links*:]
> Istio allows this via custom bootstrap, which works but involves updating all the deployments to add this annotation. Given the nature of change and benefits it will provide, OOTB support would be nice to have, Refer - https://github.com/istio/istio/issues/30987

**Comment by ggreenway** [comment]
cc @jmarantz who's been working on the stats endpoint infrastructure.

**Comment by jmarantz** [comment]
Agreed; I'm not sure if there's anything that blocks setting up the compression filter in the chain with the admin filter, but I also haven't heard of people doing that before, as the admin filter may be special in the way it's configured, or whether code change might be required.

**Comment by demandbase-gmavadiya** [comment]
@daixiang0 @jmarantz I have tried the `http_filter` option using `envoy.filters.http.compressor` but that is not compressing `/stats/prometheus` endpoint output.
