### ISSUE TITLE
Envoy forward proxy - man in the middle with ssl termination

### ISSUE THREAD

**Issue by batistado** [envoyproxy/envoy#20425]
Hi
I wanted to check if envoy supports Man in the middle with SSL termination as a forward proxy?
If so can you link me to any documentation or example config how to do it?

**Comment by daixiang0** [comment]
May be cluster filter or custom HTTP conn pool helps. 🤔

**Comment by batistado** [comment]
How? Care to elaborate?

**Comment by daixiang0** [comment]
@soulxu maybe you know details.

**Comment by soulxu** [comment]
> @soulxu maybe you know details.

I guess this is what @LuyaoZhong trying to do here https://github.com/envoyproxy/envoy/issues/18928

@batistado ^ is that the requirement you asking for?

**Comment by soulxu** [comment]
> @soulxu maybe you know details.

@batistado not sure you are asking a normal tls termination or something like what @LuyaoZhong is doing here https://github.com/envoyproxy/envoy/issues/18928

**Comment by LuyaoZhong** [comment]
@batistado I think it is indeed what we are doing with #18928 . We have a workable [PR](https://github.com/envoyproxy/envoy/pull/19137) to mimic the server certificate, which might satisfy your requirement.

There are limitations if we don't have the real server cert as reference to mimic cert, for instance we will lose TLS extensions, etc. That's why we are discussing the new workflow on #18928.

**Comment by vorishirne** [comment]
@LuyaoZhong I want to test your changes as much as you want. I am a forward dynamic tls proxy geek. 

So the traffic has to be routed via iptable rules or how in your example config attached in PR?

**Comment by LuyaoZhong** [comment]
@vorishirne Yes, you need to route traffic to Envoy with proper iptables rule set.

**Comment by vorishirne** [comment]
@LuyaoZhong is this feature still under development

**Comment by LuyaoZhong** [comment]
@vorishirne Yes, see the issue [TLS bumping](https://github.com/envoyproxy/envoy/issues/18928) .

**Comment by kmushegi** [comment]
This video could be useful? just watched it myself, looking for similar things https://www.youtube.com/watch?v=B8nTc08CeRQ
