### ISSUE TITLE
crash_integration_test timing out on coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#20444]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/104233/logs/260
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/104166/logs/267

**Comment by alyssawilk** [comment]
@KBaichoo git says you might have the most context - can you take a look?

**Comment by KBaichoo** [comment]
will take a look, is it timing out often enough that we should disable it under coverage for now?

**Comment by phlax** [comment]
@KBaichoo looking through post submit logs it seems that its permafailing on integration tests but afaict not always the same ones

i can look further later today, but it seems like timeouts is the most likely cause, so im wondering if we can resolve by adjusting them

**Comment by KBaichoo** [comment]
Yea, I looked into it a bit more last night, I think we got "lucky" with it passing before from re-running the failing parts under coverage to eventually pass the entire test. 

```
[01:21:02] kbaichoo:crash-timeout-fix:8 $bazel test //test/extensions/filters/http/kill_request:crash_integration_test --config=coverage
INFO: Analyzed target //test/extensions/filters/http/kill_request:crash_integration_test (1 packages loaded, 2 targets configured).
INFO: Found 1 test target...
INFO: LCOV coverage report is located at /usr/local/google/home/kbaichoo/.cache/bazel/_bazel_kbaichoo/bcdd3f08b0540a99da559596e399a288/execroot/envoy/bazel-out/_coverage/_coverage_report.dat
 and execpath is bazel-out/_coverage/_coverage_report.dat
INFO: From Coverage report generation:
Target //test/extensions/filters/http/kill_request:crash_integration_test up-to-date:
  bazel-bin/test/extensions/filters/http/kill_request/crash_integration_test
INFO: Elapsed time: 458.734s, Critical Path: 458.00s
INFO: 19 processes: 2 internal, 17 linux-sandbox.
INFO: Build completed successfully, 19 total actions
//test/extensions/filters/http/kill_request:crash_integration_test       PASSED in 455.0s
  Stats over 16 runs: max = 455.0s, min = 358.2s, avg = 426.9s, dev = 35.4s
```
So that brings the runtime of it to ~ `455 * 16 = 7280` which under 2 shards isn't enough to not be timed out.
is running with shard by 16, I
