### ISSUE TITLE
xds: crash in onDiscoveryResponse

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#20458]
We experienced a crash in the XDS code path in our CI. Unfortunately we don't have a lot of debug info here (this is one of the few areas without core dumping support). Attached below are the logs

Envoy log: https://storage.googleapis.com/istio-prow/logs/integ-security_istio_postsubmit/1505969504671240192/artifacts/security-90e03050bd514c82bd47a1/TestReachability/_test_context/test-ns1-1-99926-state1182920515/primary-0/vm-v1-55b6b4d745-nnkx6_istio-proxy.envoy.err.log

Core dump: unfortunately not available

Config dump: we don't have the exact config, but it should be extremely similar to https://storage.googleapis.com/istio-prow/logs/integ-security_istio_postsubmit/1505969504671240192/artifacts/security-90e03050bd514c82bd47a1/TestReachability/_test_context/test-ns1-1-99926-state1182920515/primary-0/a-v1-7f7dc896d6-qzzj7_proxy-config.json which was another non-crashing workload running at the same time.

This doesn't seem like much to go on unfortunately

**Comment by lambdai** [comment]
I see onDiscoveryResponse is messing up the control_plane() field, I can give a quick fix.

But it's not clear to me if that is the root cause of the crash.
