### ISSUE TITLE
thrift: deprecate ttwitter

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#20466]
As a follow-up to discussions in #10701, let's initiate the process to deprecate ttwitter support in Thrift Proxy. We believe that the protocol is not widely used and supporting it makes Thrift Proxy more complex. Plus, to test it we need to bring in twitter-commons which is deprecated and doesn't properly support Python3. So here's the proposed plan:

1) I'll send a PR with changelog entry to give notice of the deprecation along with a log warning when ttwitter is enabled
2) I'll send an email to the appropriate lists giving a heads up about the deprecation
3) I'll remove tests related to ttwitter, which effectively unblocks the py3 dependencies update 
4) after a year has gone by, we'll delete the code that supports ttwitter

cc: @zuercher @mattklein123 @fishcakez @davinci26 @phlax

**Comment by mattklein123** [comment]
+1 thanks a ton @rgs1 for driving this.

**Comment by rgs1** [comment]
Alright, sounds like we are ready to delete TTwitter. I'll send something (unless @JuniorHsu beats me to it).

cc: @fishcakez @zuercher
