### ISSUE TITLE
filesystem dynamic config only triggers on rename events

### ISSUE THREAD

**Issue by asuffield** [envoyproxy/envoy#20474]
https://github.com/envoyproxy/envoy/blob/e58c890ded5c13e60eba3285c96ffefd6f7215cf/source/common/config/filesystem_subscription_impl.cc#L30 only subscribes to MovedTo events, not Modified events.

This means that if the file is overwritten directly, rather than with the traditional "write to temporary file and then rename into place" approach, envoy will ignore the config change. That is at least surprising.

Whether it should work this way is an interesting question, but at the very least, it should be explicit in https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem that only renames will be picked up.

**Comment by mattklein123** [comment]
This is very much on purpose as atomic renames are the only way to achieve consistency. Doc update PRs very much appreciated.

**Comment by asuffield** [comment]
Makes total sense once you know about it, took about four hours to learn because it doesn't seem to be mentioned anywhere - fixing the documentation is fine.

**Comment by daixiang0** [comment]
@envoyproxy/envoy-maintainers please close this since fixed.
