### ISSUE TITLE
lua ,response body parsing issue for one upstream

### ISSUE THREAD

**Issue by medhat-ramadan** [envoyproxy/envoy#20490]
I am parsing response body in lua script using following code which is working for all upstream but one have issue parsing the body looks gibberish . instead it should have string json data .
`                     local body = response_handle:body() 
                      local jsonString = tostring(body:getBytes(0, body:length()))
                      response_handle:logInfo(jsonString)`

![envoy](https://user-images.githubusercontent.com/11191928/159746650-788e1940-b228-4f6d-a20a-4fbc2ffc1b73.PNG)

**Comment by phlax** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
Hi, @medhat-ramadan It seems that the upstream responses are some binary data. Would you like to ensure the upstream response body again? If it's possible, can you provide the content of response body?

**Comment by medhat-ramadan** [comment]
Hi @wbpcode the body is json data
removing request header  accept-encoding solved the problem seems like decoding/compression problem
`                request_headers_to_remove:
                - accept-encoding  `

**Comment by wbpcode** [comment]
Sound you are right. Based on the `accept-encoding` header, the upstream server responds with conpressed/encoded body to Envoy.
