### ISSUE TITLE
Check if it is grpc request on the spot during sendLocalReply 

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#20496]
*Title*: *Check if it is grpc request on the spot during sendLocalReply *

*Description*:
For HTTP requests, when they are transoded into gRPC requests by JsonGrpcTranscoder filter and get rejected by `sendLocalReply` in filters after, the filter manager will [treat requests as HTTP requests](https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L904) and send HTTP response directly based on a state variable assigned during request header [initilization](https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.h#L291) though they are gRPC requests now. 

The sendLoalReply should send a gRPC response and let the JsonGrpcTranscoder to transcode the google.rpc.Status, espeically the `details` if we implement https://github.com/envoyproxy/envoy/issues/20495.

**Comment by TAOXUY** [comment]
@nareddyt @qiwzhang @shuoyang2016

**Comment by daixiang0** [comment]
Agree, it is really an enhancement.

**Comment by TAOXUY** [comment]
`is_grpc_request` is introduced by

https://github.com/envoyproxy/envoy/commit/fb7bdbe45cc04ef504b1092f037b45a45cad2714
