### ISSUE TITLE
what TypedExtensionConfig does config.bootstrap.v3.FatalAction has the doc is empty？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20500]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
what TypedExtensionConfig does config.bootstrap.v3.FatalAction has the doc is empty？
*Description*:
>Describe the issue.
I want to config bootstrap fatal_actions，but no TypedExtensionConfig  in the doc？
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
Maybe you miss https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto.html?highlight=fatal_actions#config-bootstrap-v3-fatalaction.

**Comment by 13567436138** [comment]
I have exactly readed the doc above ,but not have more informations
