### ISSUE TITLE
is enabled runtime_key random or it has some rules

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20524]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
is enabled runtime_key random or it has some rules*Description*:
>Describe the issue.
sometime I have to config enabled field,It has a sub field runtime_key,I don't know how to config it for some config don't have examples.is it random or it has some rules?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
searching the docs and grepping the code it seems there are quite a few different uses of `runtime_key`

my reading is that the key names are significant, and as documented

(eg try `$ git grep shadow_enabled` )
