### ISSUE TITLE
C++ filters using coroutines

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2052]
I think it should be possible to have a native filter API that is accessed via coroutines, much like Lua. This would make the common case programming model substantially simpler, allow type safety, and native performance.

Initially we could potentially use POSIX ucontext / NT fibers, and eventually switch to C++20 coroutines.

**Comment by ascheglov** [comment]
Let's keep it alive for a while. Although I doubt that coroutines are better than callbacks, I'd like to give it a try and see how it would look like.
