### ISSUE TITLE
Linked packet capture feature provided by hardware Loadbalancer(Netscaler/BigIP)

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#20536]
Current the hardware load balancer (HLB) such as Netscaler/BigIP provide the linked packet capture functionality to make the packet capture more convenient. It mainly solves two pain points when we do packet capture.

If you set the filter with client IP and VIP, it can capture all the packets from client to vip and also from LB to all upstream servers. So we can get a full picture about the whole stream.

Several clients-to-vip connections map to one connection from LB to upstream server. So there should be a way to show the relationship between the packet from client to vip and the packet from LB to backend server.

I have a solution for envoy as a software load balancer (SLB). There are two parts of work. One is for envoy, one is for linux kernel.

For envoy side, the main works is as follows:

Pass the client connection information to the server side connection
Add the client port information as the socket ancillary data when envoy sends packet out.
Add configuration to filter which client/VIP should be captured. ()
For kernel side, need recognize the ancillary data added by envoy and add the client port information as TCP option. So when we capture the packet from LB to upstream server, we can know which client connection the packet is from.

I have done the work for both envoy and kernel side and it works as expected. I just want to confirm with community to see whether this kind of envoy PR can be accepted since the feature need some kernel help. Are there any suggestions for this kind of case which need other software/kernel's co-working.

**Comment by zhangbo1882** [comment]
https://github.com/envoyproxy/envoy/pull/20525

**Comment by mattklein123** [comment]
Sorry I don't think I have enough information to have an opinion on how this might work in Envoy. In general though, we fully decouple upstream and downstream, so we are never going to directly connect them.

The way we typically handle such issues is to pass metadata between downstream and upstream. This might be the way to go for your use case. For example take a look at https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/original_src/original_src.cc and other uses of `addUpstreamSocketOptions`. Similar things could be done with network filters, dynamic metadata, etc.

**Comment by mattklein123** [comment]
> The original_src feature will change the source IP for the traffic from envoy to upstream server. This is NOT what we want.

I'm not suggesting that you use original_src as a solution to your problem. I'm explaining that is an example of how we carry ancillary data between downstream and upstream in Envoy. Envoy's architecture fully decouples downstream for upstream and we won't allow the type of direct connection you are proposing for abstraction and encapsulation reasons. With that said, between something like the original_src mechanisms and dynamic metadata, and various extension points, you can achieve what you are after. I would suggest researching how original_src works and proposing something along those lines.

**Comment by zhangbo1882** [comment]
Thanks. I will investigate more.

**Comment by zhangbo1882** [comment]
@mattklein123 , I have read the doc/code about the original_dst and also dynamic metadata. I have the following thinkings, if I am wrong, correct me.
Currently dynamic metadata is saved in streamInfo and it can be produced and consumed by each filter. But there is no code to pass the metadata from downstream streamInfo to upstream streamInfo, right ?  So I think I can add a new network filter to set the information I need as dynamic metadata in downstream streamInfo. Then still need some changes to pass the dynamic metadata from downstream to upstream streamInfo. Is it reasonable ?

**Comment by mattklein123** [comment]
See stream_info.h and you will see that we already pass stream info between downstream and upstream. I'm guessing what you need to do is already supported but I'm hazy on the details so I'm not 100% sure. cc @alyssawilk who has worked on the upstream stream info split and cleanup and @kyessenov @lambdai who are doing similar info passing for Istio.

**Comment by kyessenov** [comment]
Upstream host selection is mostly driven by transport socket options. I recently added capture of host metadata and downstream filter state so that might be a better route to propagate info to upstream.

**Comment by zhangbo1882** [comment]
> Upstream host selection is mostly driven by transport socket options. I recently added capture of host metadata and downstream filter state so that might be a better route to propagate info to upstream.

@kyessenov , could you help tell me the PR so that I can have a better understanding, thanks.

**Comment by zhangbo1882** [comment]
> See stream_info.h and you will see that we already pass stream info between downstream and upstream. I'm guessing what you need to do is already supported but I'm hazy on the details so I'm not 100% sure. 

@mattklein123 , it is supposed that you are talking about 

/**
   * @return the downstream connection info provider.
*/
  virtual const Network::ConnectionInfoProvider& downstreamAddressProvider() const PURE;

From the name convention for the function downstreamAddressProvider(), it seems that it can get what I want. Actually, this function does NOT get what it seems to be.  

For example, a downstream client 1.1.1.1 connection to listener 2.2.2.2:80, then envoy (3.3.3.3) connect to upstream server 4.4.4.4:8080.
The function downstreamAddressProvider() will return 1.1.1.1 in the downstream streamInfo. But in the upstream streamInfo, it will return 3.3.3.3. What I really want is it will return 1.1.1.1 for the upstream streamInfo. 

I also check the code, I cannot find the code to set the downstream address info  in upstream streamInfo.

**Comment by kyessenov** [comment]
This [PR](https://github.com/envoyproxy/envoy/pull/19435/checks?check_run_id=5827390482) adds `host()` to transport socket options. Transport socket options also has `filterState()` accessor. That seems like a natural way to bridge from downstream to upstream.

**Comment by zhangbo1882** [comment]
@kyessenov,  no matter use dynamic metadata or filter state to pass the information I need, the key point is that for the same upstream, there are multiple downstreams and the information which is  passed to the same upstream will change continuously after the upstream connection is established. In your PR, transport socket options for upstream should be unchanged once the upstream connection is established, right ? For my case, I have to set the information for the upstream streamInfo whenever UpstreamRequest::onPoolReady is called, but the upstream streamInfo in onPoolReady is a const data, I can not set it, do you have any suggestion where to set the filter state ?

**Comment by zhangbo1882** [comment]
It seems that what I want is like the PR https://github.com/envoyproxy/envoy/pull/19668

**Comment by zhangbo1882** [comment]
@alyssawilk , do you have any comments how to propagate the l4 downstream streamInfo to l4 upstream streamInfo ?

**Comment by kyessenov** [comment]
That PR had a problem that you mentioned - it's not possible to always correlate downstream and upstream stream info since multiple streams map into one. The internal upstream PR solves this via two mechanisms:
1) it's only a subset of downstream info that will be shared;
2) that subset participates in the upstream connection pool hash, so that they are all the same for downstream stream infos.

**Comment by zhangbo1882** [comment]
Let me clarify my requirement. 

1. Two clients 1.1.1.1:port1 and 1.1.1.2:port2 will access the same listener 2.2.2.2:80.

2. Envoy(3.3.3.3) creates a connection to access the upstream server 4.4.4.4:8080.  Both client1 and client2 will share the same connection between envoy and upstream server. 

3. Now for each http/tcp request from client1/client2 to envoy, envoy will send request to upstream server with the connection in step 2. My requirement is that I want to know the request(envoy to upstream server) is for client1 or client2.

**Comment by zhangbo1882** [comment]
@mattklein123  could you help have a quick review https://github.com/envoyproxy/envoy/issues/20536.  It mainly includes two changes.

1. Add a new network filter to set the dynamic metadata.
2. copy the metadata from downstream to l4 upstream streamInfo. (It only add one function https://github.com/envoyproxy/envoy/pull/20733/files#diff-b61a05a18225decb27f5620aefda1646c259e314547a7d985c369f62a684c12bR531)
If it is reasonable, I can continue add the test cases.

**Comment by zhangbo1882** [comment]
@mattklein123 , I would like to use tap framework to do the work. But I do not have a straightforward thinkings how tap can meet my requirement.
I have checked the tap code, tap framework will

match traffic in listener and tap output the traffic
match traffic in cluster and tap output the traffic.
My requirement is that matching traffic in listener and tap output the traffic in cluster. So it seems that envoy need some mechanism to pass some information from downstream to upstream. Do you have any suggestion how can envoy achieve the target? Can you help reopen this PR #20733 for further discussion ?

**Comment by mattklein123** [comment]
Since your focus appears to be HTTP/1.1 traffic, why can't you just use the L7 HTTP tap filter and then capture the HTTP traffic for a particular client based on matching rules? Obviously this filter runs in "downstream" context but I don't really understand why you need to capture both the downstream and upstream traffic if you are just trying to see the traffic that is flowing for a particular client to a particular server.

**Comment by zhangbo1882** [comment]
Capturing downstream/upstream real packets is used for some L4 layer issue troubleshooting (TCP latency/retransmission and so on).  Tap filter is used for application issue troubleshooting since it mirror the traffic instead of getting the real traffic. From envoy's view, it is based on transport socket, it will NOT touch L4 in details. But from system's view, we should know more details from L2 to L7 for the first-hand traffic data.

**Comment by mattklein123** [comment]
Yes if you are really set on getting the kernel level packets you will need to proceed down the path that we already discussed, but as I said, this path does not work in any sensible way for HTTP/2 and HTTP/3, so I don't think this is something that we will accept upstream. If you want to propose changes to handle metadata propagation between downstream and upstream so that you can write custom extensions that is something we can discuss.

**Comment by zhangbo1882** [comment]
Do you mean that copy metadata from downstream to upstream ?  I think this kind of change should also change the envoy framework code instead of the filter extension.

**Comment by mattklein123** [comment]
What I mean is that we are not going to accept the full solution upstream because as I already explained it will not work for HTTP/2 and HTTP/3. You will need to maintain private extensions that work for your HTTP/1 use case.

We are happy to accept a small number of core changes to make your extensions work, if you can define what those required changes are. I think this should be related to moving metadata from downstream to upstream beyond what is already done.

**Comment by zhangbo1882** [comment]
Thanks @mattklein123. I will try to submit a PR for moving metadata from dowstream to upstream.

**Comment by zhangbo1882** [comment]
@mattklein123 , could you help have a look at the PR #21524, thanks.
