### ISSUE TITLE
[Forward proxy mode] Allow only client connections that match a CN from the client certificate

### ISSUE THREAD

**Issue by batistado** [envoyproxy/envoy#20533]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Allow only client connections that match a CN from the client certificate

*Description*:
We have a use case where we run envoy in forwarding proxy mode and block all connection requests that do not have a matching Common Name in the client certificate.
The closest that I could get to is this match_typed_subject_alt_names in [https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-exten[…]ficatevalidationcontext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext)

The SAN types it supports are [https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#enum-extensions-transp[…]taltnamematcher-santype](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#enum-extensions-transport-sockets-tls-v3-subjectaltnamematcher-santype) which doesn't include Common Name.

Is it possible to achieve what I am trying to do with Envoy running as a forward proxy?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @ggreenway

**Comment by daixiang0** [comment]
It is an interesting question, does it use to deny fake connections? In that case, certs are fake as well, is there a really case that fakes other fields except CN?

**Comment by batistado** [comment]
@daixiang0 In addition to this CN check in the client cert, we will also accept connections from a specified list of hosts/IP addresses. So even a cert CN is compromised, the proxy shouldn't allow connects based on host/IP filtering. Is this possible with envoy running as forward proxy? If yes, can you share example config?

**Comment by batistado** [comment]
@daixiang0 Please let me know if https://github.com/envoyproxy/envoy/issues/20563 can work.
