### ISSUE TITLE
local reply during encoding should continue encoding from the encoder filters hasn't encoded

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#20535]
*Title*: local reply during encoding should continue encoding from the encoder filter before the one raises local reply

*Description*:

Currently, when the local reply is raised by encoder filter during encoding header time, it will send the local reply directly to downsteam. We want the local reply to continue going through the filters that haven't encoded.

https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L932-L940

It can also be related to the TODO the local reply raised in decoding time should also be encoded through only the seen filters, not the whole encode filter chains.

https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L983-L991

**Comment by phlax** [comment]
cc @snowp
