### ISSUE TITLE
RDMA over the internet

### ISSUE THREAD

**Issue by vitruvvius** [envoyproxy/envoy#20539]
RDMA

*Description*:
Has the envoy team considered embedding RDMA into transport layer?

**Comment by phlax** [comment]
interesting question 

im not clear if you are asking about:

- Envoy making use of RDMA (which is my reading of the description)
- Envoy proxying RDMA (which title seems to suggest)

cc @mattklein123

**Comment by vitruvvius** [comment]
Any commentary on whether there are plans to introduce RDMA in the ecosystem - downstream or upstream clusters. 

Eventually will need it for an open source video streaming / computer vision platform. curious whether or not this has been thought of yet so we would not need to copy modules out of envoy to acquire duplicate functionality.

**Comment by daixiang0** [comment]
In my knowledge, it is hard to proxy RDMA as it uses its own transport way, more like point-to-point. As Envoy mostly works as a sidecar/gateway to proxy, RDMA is not intended for proxy.

I am curious about the design of the video streaming / computer vision platform and how do you want to use Envoy, including how to use RDMA.

**Comment by vitruvvius** [comment]
# purpose

rdma infiniband - and its equivalent dma alternatives - helps solve a cost problem when rebroadcasting video/lidar data to upstream/downstream clusters. it also helps solve a scaling problem in computer vision / ml workloads. most notably seen as one of the reasons behind NVIDIA buying Mellanox.

# context

(1) we view envoy - irrespective to its singularity of focus of an L7 proxy - as a powerful, elegant way to open any machine to the internet. mobile, desktop, server, storage cluster, etc. in particular, one does not have to reduplicate rate limiting for ddos mitigation, grpc transcoding, & other great plugins... all generally optimized/safe. grpc community does so, too, & has been slowly integrating a lot of key features around xDS.

(2) we treat every machine as though it's open to the internet (irrespective to whether that's true, see below). so, every "socket" (virtual address) connected in the network accessible through some other route. this forms a graph of sockets - tcp, ipc, quic, udp, rdma - to broadcast video/lidar streams into

# outcome

(1) envoy acts as the bedrock of the network. we apply a lot of the plugins to mitigate the problems that come w/ opening to the internet, authenticating peer to peer packets, and don't desire to rewrite them

(2) with a graph of connected "software-defined assets," (a group of whatsapp users, a group of iot devices, etc), we embed algorithms & routing in envoy to stream real-time data to correct remote socket

(3) we don't desire to move outside of envoy when rebroadcasting lidar/video streams (ie, no need for cpu)

from past experience running distributed file systems @ msft, we infer RDMA will solve a cost & scale barrier in real-time video/lidar streaming that prevents consumption in our target use cases. an axiom of rdma over ethernet is that it's connected directly to other machines. in this sense, we're not opening ourselves to the internet. but, we don't want to duplicate packets outside of envoy. so, we intend to apply RDMA to refocus clusters of compute resources on in-memory vision algorithms & not on packets/networking. typically, i would throw as many machines as needed elastically. however, we're hoping to break through a cost inflection.

**Comment by soulxu** [comment]
We have thought about Envoy + RDMA, using the IP network to route the node, then setup RDMA connection to transfer the data.

**Comment by vitruvvius** [comment]
for the use case noted, internet was not the most accurate term

good to note, though, rdma over ip has been developed

rdma in general has followed an equivalent roadmap as dpdk. the only difference - for those curious - was separating the cpu & forming dedicated hardware

**Comment by mattklein123** [comment]
To be honest I haven't thought about RDMA since my HPC days at Amazon in the early 10s. I think it's conceivable that this could work with Envoy, but it would need a lot of thinking. Fundamentally, Envoy is used to operating on streams of data. If we consider RDMA a stream of put/get operations, it might layer in similar to how we do UDP today.

My advice would be to do a design document on how this might fit in to the existing abstraction layers. It's definitely interesting!

**Comment by mattklein123** [comment]
> (1) Does the team imagine any future DPDK support?

Envoy is very extensible. There is already a config extension for VPP/VCL which is similar to DPDK: https://github.com/envoyproxy/envoy/tree/main/contrib/vcl/source. I know there are some people doing DPDK with Envoy but I'm not sure if any of it is open.

> (2) Does the team imagine any support for listening over ipc sockets (for local thread to thread message passing)?

We already support unix domain sockets, and I don't think it would be difficult to support other things similar to the VPP/VCL stuff. I think to advise more we will need more info on specific use cases.
