### ISSUE TITLE
what is bootstrap bootstrap_extensions used for？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20540]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
what is bootstrap bootstrap_extensions used for？*Description*:
>Describe the issue.
I don't know what is the config usage.the doc don't explain ,anybody knows?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
>  Specifies optional bootstrap extensions to be instantiated at startup time. Each item contains extension specific configuration.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto.html?highlight=bootstrap_extensions

there are a couple of existing extensions listed there (wasm/vcl)

im sure this is an area that could have better documentation
