### ISSUE TITLE
how many overload action typed_config are threre？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20541]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
how many overload anction typed_config are threre？
*Description*:
>Describe the issue.
I want to config overload action，the typed_config in the doc I discoveried one is   type.googleapis.com/envoy.config.overload.v3.ScaleTimersOverloadActionConfig。 what are others？ the doc don't say。
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
I think now only support it.
