### ISSUE TITLE
Zstd compression support in envoy

### ISSUE THREAD

**Issue by rainingmaster** [envoyproxy/envoy#20543]
*Title*: *Zstd compression support in envoy*

*Description*:
> Since 2015, [zstd](https://github.com/facebook/zstd) has been getting [better and better performance](https://facebook.github.io/zstd/) since 2015, and this feature has also been introduced to [various platforms](https://en.wikipedia.org/wiki/Zstd#Features). As an increasingly important proxy component in cloud-native, Envoy also needs to support this special effect.

cc @rojkov

**Comment by daixiang0** [comment]
cross with https://github.com/envoyproxy/envoy/pull/20434

**Comment by rojkov** [comment]
As stated in the PR already I'm OK to sponsor this enhancement. Intel needs it as a benchmark for the upcoming zstd acceleration in QuickAssist HW and is willing to support it together with ByteDance.

**Comment by rainingmaster** [comment]
Done with https://github.com/envoyproxy/envoy/pull/20434 now!
