### ISSUE TITLE
Ratelimit domain at filter in the filterchain level limits multitenancy

### ISSUE THREAD

**Issue by eguzki** [envoyproxy/envoy#20553]
*Title*: Ratelimit domain at HTTP filter level limits multitenancy

*Description*:
The rate limiting [domain(s)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-ratelimit-v3-ratelimit) used in the global rate limiting filter in Envoy are shared across all traffic domains that hit the gateway. The global rate limiting filter is created at the filterchain level and there is no way to specify a domain at the VirtualHost level. This means the filter configuration is shared at the gateway level (which rate limiting service to call, which domain to use). Whereas the triggering of actual rate limiting calls happens at the [virtual host](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost) or [route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction) level by adding actions. 

This need to have shared domains causes several issues:
* All rate limit configurations applied to the [external rate limit service](https://github.com/Kuadrant/limitador) need to use a shared domain or set of shared domains. This means that for each rate limiting request, the [external rate limit service](https://github.com/Kuadrant/limitador)  will need to iterate through each of the rate limit resources within the shared domain and evaluate each of their conditions to find which one applies. As the number of APIs increase so would the number of resources that the [external rate limit service](https://github.com/Kuadrant/limitador)  would need to evaluate.
* With a shared domain comes the risk of a clash. To avoid a potential clash, it would be necessary to add a globally unique `generic_key` action per domain at the envoy config and conditions to match that `generic_key` at the rate limit service configuration.  

What would be the suggested approach to tackle the aforementioned issues?

*Relevant Links*:
* [Kuadrant](https://github.com/Kuadrant)

**Comment by rahulanand16nov** [comment]
A `domain` extension at the virtual host level will also fix this problem similar to https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#extensions-filters-http-ratelimit-v3-ratelimitperroute
