### ISSUE TITLE
forward fix extensions being depended on by core code/tests

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#20589]
so way back when I fixed the default visibility rules so extensions were in general not visible to core code and non-extension tests.

That said, it relies on maintainers remembering to not let folks fix visibility rules, as individual contributors don't know it's problematic (e.g. https://github.com/envoyproxy/envoy/pull/20560#discussion_r837623827) and that's clearly not a good plan.

I think as a follow up to https://github.com/envoyproxy/envoy/issues/9953 we should have CI out disallow "visibility" in //extension BUILD files, to require admin approval of any violations of the extension policy.  cc @envoyproxy/envoy-maintainers for any other ideas / objections and cc @phlax for if you can pick it up or if you want to suffer reviewing my awful python :-P

**Comment by phlax** [comment]
im happy to pick it up - but i have a bit of a backlog atm so if you want to resolve more quickly

also, from my pov its probably quicker translating existing code into the pytooling libs - so would be happy to review

**Comment by alyssawilk** [comment]
"happy to review" clearly you have not reviewed much of my python :-P  Thanks, PR sent your way.
