### ISSUE TITLE
Envoy should not alter thrift THeader key

### ISSUE THREAD

**Issue by fishy** [envoyproxy/envoy#20595]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Currently envoy always lowercase thrift THeader key and this is wrong*

*Description*:
Thrift THeader keys are case-sensitive according to [the spec](https://github.com/apache/thrift/blob/f0336417cae1c32f4ea59a9f9851a15f269340f7/doc/specs/HeaderFormat.md), so altering them is a bug.

This is the line that does it: https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/filters/network/thrift_proxy/header_transport_impl.cc#L151

*Repro steps*:
Make a thrift client and send "Foo: Bar" THeader to a thrift server via envoy. The server receives "foo: Bar" instead.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by marcoferrer** [comment]
Linking thrift issue requesting clarification on key format in the header spec
https://issues.apache.org/jira/browse/THRIFT-5541

**Comment by fishy** [comment]
not stale
