### ISSUE TITLE
CI test builds failing with "invalid action cache entry"

### ISSUE THREAD

**Issue by mkbehr** [envoyproxy/envoy#20599]
*Title*: CI test builds failing with "invalid action cache entry"

*Description*:
I'm seeing CI runs fail to build changed files with messages like:

`ERROR: /source/test/extensions/filters/http/cache/BUILD:71:24: Compiling test/extensions/filters/http/cache/cache_filter_test.cc failed: (Exit 34): Invalid action cache entry 0da235ebddfcb79aa14ea81f1aa904e9fdf4b016e4fb535094a666317649c5b5: expected output test/extensions/filters/http/cache/_objs/cache_filter_test/cache_filter_test.pic.o does not exist.`

I've seen a couple different PRs with this problem: my results [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=105022&view=logs&jobId=8bf29878-a4cc-50f7-4e84-2255e6fd4065&j=8bf29878-a4cc-50f7-4e84-2255e6fd4065&t=3267cd16-a387-57e0-0ef4-d7a4d1c6c089) for #20593 and another failure [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=104941&view=logs&jobId=8c169225-0ae8-53bd-947f-07cb81846cb5&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec) for #20581.

There's a recent [Bazel bug](https://github.com/bazelbuild/bazel/issues/15074) with similar error messages, so we can probably fix this by pulling in the fix there.

*Repro steps*:
Run the linux_x64 gcc presubmit on https://github.com/envoyproxy/envoy/pull/20593.

**Comment by keith** [comment]
According to that bazel issue it is fixed in bazel 5.1, which I updated main too yesterday https://github.com/envoyproxy/envoy/commit/fd92486e4c751b29cd92412fd862ced6c6bae073 🤔

**Comment by keith** [comment]
In case the CI log rotates here's more of the stack:

```
ERROR: /source/test/extensions/filters/http/cache/BUILD:71:24: Compiling test/extensions/filters/http/cache/cache_filter_test.cc failed: (Exit 34): Invalid action cache entry 0da235ebddfcb79aa14ea81f1aa904e9fdf4b016e4fb535094a666317649c5b5: expected output test/extensions/filters/http/cache/_objs/cache_filter_test/cache_filter_test.pic.o does not exist.
java.io.IOException: Invalid action cache entry 0da235ebddfcb79aa14ea81f1aa904e9fdf4b016e4fb535094a666317649c5b5: expected output test/extensions/filters/http/cache/_objs/cache_filter_test/cache_filter_test.pic.o does not exist.
	at com.google.devtools.build.lib.remote.RemoteExecutionService.downloadOutputs(RemoteExecutionService.java:1031)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.downloadAndFinalizeSpawnResult(RemoteSpawnRunner.java:367)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:284)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:239)
```

**Comment by keith** [comment]
I'm wondering now if this degraded in Bazel 5.1 and we should downgrade back to 5.0 🤔

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/20615

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/20741
