### ISSUE TITLE
generate compile_commands.json fail

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#20607]
[Wed Mar 30 22:59:31][#120# ] (main)$./tools/gen_compilation_database.py 
ERROR: /mnt/cache/_bazel_stack/5a617312af51e0dbefb3398d3212136c/external/base_pip3_sphinx/BUILD.bazel:22:11: no such package '@base_pip3_importlib_metadata//': The repository '@base_pip3_importlib_metadata' could not be resolved: Repository '@base_pip3_importlib_metadata' is not defined and referenced by '@base_pip3_sphinx//:pkg'
ERROR: Analysis of target '//tools/docs:sphinx_runner' failed; build aborted: 
INFO: Elapsed time: 1.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 0 targets configured)
    Fetching @emscripten_bin_linux; fetching
    Fetching @base_pip3_pyparsing; fetching
    Fetching @base_pip3_yarl; fetching
    Fetching @base_pip3_python_gnupg; fetching
    Fetching @base_pip3_multidict; fetching
    Fetching @rust_linux_x86_64; fetching
    Fetching @base_pip3_idna; fetching
    Fetching @base_pip3_cffi; fetching
Traceback (most recent call last):
  File "./tools/gen_compilation_database.py", line 124, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "./tools/gen_compilation_database.py", line 20, in generate_compilation_database
    subprocess.check_call(["bazel", "build"] + bazel_options + [
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//tools/...', '//contrib/...']' returned non-zero exit status 1.

[Wed Mar 30 22:59:46][#121# ] (main)$pip3 install importlib_metadata
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.8/dist-packages (4.10.1)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib_metadata) (1.0.0)

But I have already installed the pkg.

**Comment by zhxie** [comment]
You may require Python 3.10 to refresh compilation database.

**Comment by wbpcode** [comment]
cc @phlax

**Comment by phlax** [comment]
> You may require Python 3.10 to refresh compilation database.

yes, this is the issue - python3.10 _doesnt_ require `importlib-metadata` (and its deps) so it is not listed/pinned in the requirements file

**Comment by zhangbo1882** [comment]
Thanks @zhxie.  It works now after I upgrade the python to 3.10.
