### ISSUE TITLE
[Question] External Authz behavior with gRPC

### ISSUE THREAD

**Issue by gadinaor-r7** [envoyproxy/envoy#20608]
*Title*: *External Authz with gRPC behavior - authz service called for each gRPC method*

*Description*:
>We are using envoy v1.2.1 (through Contour) with gRPC services behind our envoy proxy.
We are gRPC with a persistent connection that runs multiple gRPC calls (unary and streaming) through the Envoy Proxy.
We have ext_authz configured (via the relevant contour resources)

Everything works great with one caveat - we see the external authorization service being called for every HTTP Route/gRPC method.

1. Is there a way to avoid the excessive authorization calls ? and just keep it once for gRPC session?
2. I've seen #3023 - and I was wondering if we are missing something with regards to how gRPC "tunnel" would work or should be configured.

**Comment by lakamsani** [comment]
Hello, have the same question. Is it possible to reopen this? We tried ngnix sub request based authentication to a backend grpc service. It performs authentication just once per initial connection. Not for all subsequent RPCs that use the same connection. Docs below.

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

Would be awesome if envoy external authentication worked like that.
