### ISSUE TITLE
tracing: Apply custom tags after common tags

### ISSUE THREAD

**Issue by matthewgrossman** [envoyproxy/envoy#20635]
*Title*: *Apply custom tags after common tags*

*Description*:
When emitting spans, envoy adds some tags automatically. Some of these tags are set upon initialization in `startSpan` (ex. [`zone`](https://github.com/envoyproxy/envoy/blob/62f3f52c13e3ca785f820087fb30e12cf8c4e691/source/common/tracing/http_tracer_impl.cc#L298), `span.kind` for [opentracing](https://github.com/envoyproxy/envoy/blob/62f3f52c13e3ca785f820087fb30e12cf8c4e691/source/extensions/tracers/common/ot/opentracing_driver_impl.cc#L204)), while some of these are set upon finalization in [`setCommonTags`](https://github.com/envoyproxy/envoy/blob/62f3f52c13e3ca785f820087fb30e12cf8c4e691/source/common/tracing/http_tracer_impl.cc#L220) (ex. [`component`](https://github.com/envoyproxy/envoy/blob/62f3f52c13e3ca785f820087fb30e12cf8c4e691/source/common/tracing/http_tracer_impl.cc#L249))

For tags that are set in `startSpan`, users can override these values dynamically using tracing configuration:
```yaml
tracing:
  custom_tags:
    - tag: span.kind
      literal:
        value: server
    - tag: component
      literal:
        value: other_component
```
In this situation, `span.kind` will be overwritten at span-finalization time by whatever was in configuration. However, for tags in `setCommonTags` like `component`, whatever envoy has hardcoded will take precedence over custom_tags and clobber what the configuration specifies.

AFAICT, this is simply due to the ordering in this snippet of code: https://github.com/envoyproxy/envoy/blob/62f3f52c13e3ca785f820087fb30e12cf8c4e691/source/common/tracing/http_tracer_impl.cc#L211-L220

**My proposal:** put the custom-tag application at the very end of finalization, giving users full customization and final say on whatever tags envoy enriches into the spans. 

I'm interested to hear if there's some intentional reason for this existing ordering, but I'm struggling to come up with a legitimate reason. Happy to work on this as well if we agree this is the path forward

**Comment by mattklein123** [comment]
Yup this sounds reasonable to me. Please feel free to do a PR. cc @wbpcode @Shikugawa as other training experts.

**Comment by Shikugawa** [comment]
It seems good to refactor for me.

**Comment by matthewgrossman** [comment]
linked my WIP draft PR, just need to get testing working on my m1 and will ping this week when ready for review

**Comment by matthewgrossman** [comment]
should be ready for review, pretty straightforward https://github.com/envoyproxy/envoy/pull/20645
