### ISSUE TITLE
CDS static load performance

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2063]
When loading large CDS static configs with embedded static hosts (see attached), it seems to take ~87ms on my workstation per cluster at startup. This is prohibitive at large cluster sizes, e.g. at 1k it takes ~87s, 10k is > 10 mins. No analysis yet on why this is happening, creating this issue to track further investigation.

[envoy_1k.log](https://github.com/envoyproxy/envoy/files/1475205/envoy_1k.log)
[envoy_1k_clusters_1k_virtual_hosts.json.gz](https://github.com/envoyproxy/envoy/files/1475208/envoy_1k_clusters_1k_virtual_hosts.json.gz)
[envoy_10k_clusters_10k_virtual_hosts.json.gz](https://github.com/envoyproxy/envoy/files/1475209/envoy_10k_clusters_10k_virtual_hosts.json.gz)

**Comment by htuch** [comment]
So, those initial numbers were on a `fastbuild` binary. With `opt`, I see ~32s for 1k, so ~32ms per cluster.

**Comment by tlhunter** [comment]
I have to wait about 15s when dealing with 1,500 CDS hosts. Unfortunately I haven't had any chance to debug the issue.

**Comment by mattklein123** [comment]
Without looking into this in detail, I think this is likely related or a dup of https://github.com/envoyproxy/envoy/issues/1824. I will fix.

**Comment by tlhunter** [comment]
I'm no longer working on the project, but I did discover that switching hostnames to IP addresses caused Envoy to boot in 2s instead of 15s.

**Comment by mattklein123** [comment]
@jmarantz I'm assigning this over to you also. I'm pretty certain that most of the load time problems have to do with the slow stat implementation, but maybe you can take a look at this also.

**Comment by jmarantz** [comment]
investigating this one first as it has a direct repro.

I am building with -O2 -g -ggdb so it's optimized and somewhat visible in terms of line numbers so cachegrind can get some detail.

My first random peaks at the stack while running though showed a lot of regex overhead as well as stats.

**Comment by jmarantz** [comment]
With https://github.com/envoyproxy/envoy/pull/2358 the 10k test is down to 30 seconds, but that still seems quite slow.  kcachegrind reveals that most of the time is in TagExtractor (including called functions), which is doing a lot of string, vector, and regex work.  I'm not sure what's going on yet from a config perspective.  But it does seem like startup should be faster if it can be.

Looking only at leaf function time, I've got a regex lib function taking 32% of the time, and operator new[] and free() taking up another combined 24%.   THen several more functions related to vectors & regexes follow.

**Comment by mattklein123** [comment]
@jmarantz one quick comment is that if tag regex extraction is very expensive, beyond just making it faster, it might be worthwhile to somehow optionally disable it for people that don't care about tags. 

Thanks for working on this. It's awesome to have someone looking into this!

**Comment by jmarantz** [comment]
@mattklein123 that seems reasonable, though I don't know what the functional implication of turning off tag extraction would be.  Maybe some of the things that are done in tag extraction could be done another way?  In any case I opened https://github.com/envoyproxy/envoy/issues/2373 to track that separately.

**Comment by mrice32** [comment]
@mattklein123, as mentioned in #2373, we can optionally disable it by [disabling the default regexes](https://github.com/envoyproxy/data-plane-api/blob/master/api/stats.proto#L54) and not providing any custom ones (maybe we should create a more elegant option for disabling it).

**Comment by mrice32** [comment]
Yep, agreed.  I only wanted to mention in case others in the community were having similar issues (for instance: https://github.com/istio/istio/issues/2554).

**Comment by mattklein123** [comment]
@jmarantz is there remaining work on this or should we resolve as complete (for now)?

**Comment by jmarantz** [comment]
There are more performance gains on the table (prototyped already) but not clear if it's worth it, e.g. the 10k case can still ~double in speed, from ~3 seconds to ~1.5 seconds IIRC, but at the cost of either adding & maintaining an alternative tag-extraction mechanism alongside regex (compatible) or removing regexes (possibly breaking some integrations).  I'm not sure if the current situation is fast enough in practice.

One thing more significant still on the table is config-reload performance which could be a lot faster with a tag-extraction cache, and also potentially runs concurrently with requests.  Could open up a separate issue for that though.

**Comment by mattklein123** [comment]
@jmarantz I'm inclined to close this is fixed. How about opening new tracking issues on the remaining perf enhancements so that we can triage if what we have so far is good enough? I think you have done so much amazing improvement that it's probably ok for now. Awesome work! :)
