### ISSUE TITLE
The semantic of TcpProxy on demand cluster lookup timeout

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#20633]
As a follow up of https://github.com/envoyproxy/envoy/pull/20409

When the ondemand cluster up is enabled at TcpProxy, It's reasonable to introduce the timeout for cluster lookup. 

I'd like to know how people feel about the semantic about the timeout value.

Currently ClusterManagerImpl provides a timeout for along with the requestOnDemandClusterDiscovery interface.

It maintains a timer for each cluster name. That says, all the type of traffic across all work threads will be notified the same time point.

If the lookup requests are arriving at 1s interval, under the setting of timeout config as 10 seconds, the consequence would be

One of the notification is triggered at 10 seconds after requested, one is notified after 9 seconds,
And one of the lookup will be immediately notified 

I am wondering this is good enough.

Alternatively we can maintain a timer for each downstream TCP request, and hold each TCP request no shorter than the configured timeout.

CC @alyssawilk @ggreenway 

Why not using other timers? 

The idle timeout or connection timeout can be used to fail the tcp proxy request, however, 
these duration (1 hour)  are usually orders of magnitude larger than a cluster lookup (within 1 minute).

**Comment by alyssawilk** [comment]
also cc @itayd in case he wants a more user friendly response when there's PR repokitteh command on issues, and vice versa

**Comment by lambdai** [comment]
I strongly incline to use per tcp_proxy now.
The reason is that a tcp proxy instance may set timeout to a significant large timeout. If the lookup depends on the timer within the on demand cluster manager,
the first timer essentially disables all the timeout for any follow up tcp proxy instance.

**Comment by htuch** [comment]
Yeah, agree on per-TCP proxy session as that is what makes sense semantically. The existing API doesn't preclude these semantics AFAICT (it doesn't have this level of detail). Would be good to clarify when you do make the change.
