### ISSUE TITLE
 Enable heap-profiling with the current tcmalloc

### ISSUE THREAD

**Issue by rojkov** [envoyproxy/envoy#20651]
The latest tcmalloc has got support for heap-profiling, but it's not going to deal with file dumps for it. So, Envoy should be responsible for writing files with profiling results. If implemented we'd have fewer reasons to keep the dependency on gperftools.

[`::tcmalloc::MallocExtension::StartAllocationProfiling()`](https://github.com/google/tcmalloc/blob/537932ef8582881cbd8ea1e86c22860d658c6748/tcmalloc/malloc_extension.h#L470) starts profiling and returns an [`::tcmalloc::AllocationProfilingToken`](https://github.com/google/tcmalloc/blob/537932ef8582881cbd8ea1e86c22860d658c6748/tcmalloc/malloc_extension.h#L458https://github.com/google/tcmalloc/blob/537932ef8582881cbd8ea1e86c22860d658c6748/tcmalloc/malloc_extension.h#L458) instance which can be stopped and fed to [`::tcmalloc::Marshal()`](https://github.com/google/tcmalloc/blob/537932ef8582881cbd8ea1e86c22860d658c6748/tcmalloc/profile_marshaler.h#L28) returning gzip-encoded data consumable with PProf.

Probably we could have a bootstrap extension registering a signal handler (an admin http-hook?) which, when activated, started profiling and then every minute or so dumped collected data into files. It could be done in the main thread or in a thread dedicated to profiling.

**Comment by lambdai** [comment]
+1 I am not aware of the google tcmalloc Marshal() can now produce pprof consumable file.

I recommend enable the heap profiling admin handler when google::tcmalloc is linked

Then the admin_handler + pprof operation would be working regardless it's google or gperftools tcmalloc

**Comment by mattklein123** [comment]
I think this should be built-in and not an extension? Can we just do it directly from the existing core admin handling code?

**Comment by mattklein123** [comment]
Sorry +1 to what @lambdai said.
