### ISSUE TITLE
http1.1: support half closed clients

### ISSUE THREAD

**Issue by ldemailly** [envoyproxy/envoy#2066]
In http1.1 a client can choose to add "Connection: close" to the header and half close their (write) end of the socket and wait for the answer

What happens is envoy does forward the request but then immediately closes both end (probably because it reads the EOF/readability of 0 as an error instead of normal)

Repro
```
$ fortio curl -loglevel=debug -keepalive=false -halfclose http://echosrv2:8080/debug
18:41:30 D http.go:290> Created client:
{IP:10.39.255.58 Port:8080 Zone:}
GET /debug HTTP/1.1
Host: echosrv2:8080
Connection: close
User-Agent: istio/fortio-0.3.6

18:41:30 D http.go:504> Half closed ok after sending request &{{0xc4200e25b0}} {10.39.255.58 8080 }
18:41:30 E http.go:545> EOF before reading anything on &{{0xc4200e25b0}} {10.39.255.58 8080 }
18:41:30 V fortio_main.go:141> Fetch result code -1, data len 0, headerlen 0
```
envoy log
```
[2017-11-16T18:41:30.081Z] "GET /debug HTTP/1.1" 0 - 0 0 0 - "-" "istio/fortio-0.3.6" "e16c359b-048a-47a5-b5ab-b5e917bd2f72" "echosrv2:8080" "10.36.2.8:8080"
```

Spec extract
> Servers SHOULD always respond to at least one request per connection, if at all possible. Servers SHOULD NOT close a connection in the middle of transmitting a response, unless a network or client failure is suspected.

**Comment by ldemailly** [comment]
cc @ggreenway who mentioned he is fixing it for tcp

**Comment by ggreenway** [comment]
Tracking tcp proxy issue at https://github.com/envoyproxy/envoy/issues/2067

**Comment by fkowal** [comment]
I am tracking the same bug i think.
```
echo -e "GET /status/ping HTTP/1.1\r\nHost: example\r\n\r\n" | nc -v $IP $PORT
```
I this example the client send a tcp FIN, i guess this is what you mean as halfclose.
The Connection: close header is just a representation of that

**Comment by kthommandra** [comment]
Does anyone know if mainstream browsers (Chrome, Firefox etc) can end up doing TCP half-close under certain scenarios ?

**Comment by kthommandra** [comment]
It clearly shows that there are web apps that end up doing TCP half-close
(eg: see attachment Reviewboard app in Firefox)

Given this behavior, shouldn't Envoy support TCP half-close on HTTP connections?
HA-Proxy seems to work just fine with this.

I haven't yet seen client badness/error etc due to this but its very confusing to see so many "DC" response flag messages being logged in Envoy access logs frequently. I'm not sure how the app recovers from this lack of HTTP response due to cnxn close.

[firefox-half-close.pdf](https://github.com/envoyproxy/envoy/files/4806773/firefox-half-close.pdf)

**Comment by ggreenway** [comment]
> It clearly shows that there are web apps that end up doing TCP half-close
> (eg: see attachment Reviewboard app in Firefox)
> 
> Given this behavior, shouldn't Envoy support TCP half-close on HTTP connections?
> HA-Proxy seems to work just fine with this.
> 
> I haven't yet seen client badness/error etc due to this but its very confusing to see so many "DC" response flag messages being logged in Envoy access logs frequently. I'm not sure how the app recovers from this lack of HTTP response due to cnxn close.
> 
> [firefox-half-close.pdf](https://github.com/envoyproxy/envoy/files/4806773/firefox-half-close.pdf)

I brought this up a few years ago as a potential issue, and at the time, no widely-used http client was sending a half-close after the request but before the response. I looked at several.  If that's changed, we may need to revisit this.

**Comment by fasaxc** [comment]
> I looked at several. If that's changed, we may need to revisit this.

As mentioned on the (dupe) issue #17160 filed by my colleague, looks like busybox's `wget` has moved to using half-close in recent versions.  Since busybox is used a lot for tire-kicking in Kubernetes, I think this is worth fixing.  It makes Envoy appear flaky.

**Comment by ggreenway** [comment]
What version of busybox is it that's broken? I went grep'ing through the busybox source and found this in wget.c:

```
/* Tried doing this unconditionally.
 * Cloudflare and nginx/1.11.5 are shocked to see SHUT_WR on non-HTTPS.
 */
#if SSL_SUPPORTED
		if (target.protocol == P_HTTPS) {
			/* If we use SSL helper, keeping our end of the socket open for writing
			 * makes our end (i.e. the same fd!) readable (EAGAIN instead of EOF)
			 * even after child closes its copy of the fd.
			 * This helps:
			 */
			shutdown(fileno(sfp), SHUT_WR);
		}
#endif
```

Looking at the history, the `shutdown( SHUT_WR)` call was added in 2016-08-20, and the conditional for only doing it on https (and comment) were added 2017-01-11, so I'm wondering if you're on a version between those two dates. Also, sounds like other widely-deployed http proxies also don't like half-close, based on that comment.

**Comment by fasaxc** [comment]
Yes, I think we hit the sweet spot for that issue.  v1.26.  I misread my colleague's comment on our slack; he said they "only do it for HTTPS since v1.27" which I took to mean "only started doing it for HTTPS _too_ in v1.27".

**Comment by ldemailly** [comment]
ping

**Comment by ldemailly** [comment]
ping

**Comment by ggreenway** [comment]
@ldemailly this is unlikely to see any movement unless someone shows a need for it and is willing to work on the fix.

**Comment by kyessenov** [comment]
This is a real problem for CONNECT. TCP half-close is much more common and if we want to faithfully map onto HTTP/1.1 CONNECT,  we need to support half-closed semantics. The issue can happen with read direction, too (e.g. upstream closing their end, which is interpreted as full close by Envoy but as half-close by tcp_proxy client).
