### ISSUE TITLE
corrupt stats for internal listener

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#20665]
Stats produced by an internal listener seem to have "envoy://" in their name, which is confusing. Example:
```
listener.envoy_//internal_outbound.worker_39.downstream_cx_total: 0
````

/cc @lambdai

**Comment by lambdai** [comment]
As a workaround, stat_prefix can be specified 
```
      listener_scope_(server_.stats().createScope(
          fmt::format("listener.{}.",
                      !config.stat_prefix().empty()
                          ? config.stat_prefix()
                          : Network::Address::resolveProtoAddress(config.address())->asString()))),
```

The goal of address `envoy://` as listener name is to avoid conflicting. 
There is no guaranteed collision by default, I think I will simply remove "//" in the default address representation.

Note that `:` is replaced to `_` as part of the metric name sanitize. This sanitize is enforce anyway b/c ipv6 address contains ":"

**Comment by lambdai** [comment]
CC @daixiang0 
Same for pipe: when the address if "/tmp/testpipe". See below

So we'd better sanitize the address string in `listener_impl` rather than changing the `Address::asString()`;
```
listener./tmp/testpipe.downstream_cx_length_ms: No recorded values
```

**Comment by daixiang0** [comment]
I will take a look and update, thanks!
