### ISSUE TITLE
How to configure tcp_proxy with CDS?

### ISSUE THREAD

**Issue by tlhunter** [envoyproxy/envoy#2068]
I originally posted this in Slack but wasn't able to get a reply from those who were online at the time. Putting it here for asynchronous conversation purposes.

Is it possible to get `tcp_proxy` working with clusters as defined via CDS? I am able to get it working with `http_connection_manager` just fine. Here is the error I'm encountering:

```
[2017-11-15 01:18:26.445][251][critical][main] source/server/server.cc:78] error \
  initializing configuration '/etc/envoy.json': tcp proxy : unknown cluster \
  'TCPSERVICE' in TCP route
```

However that `TCPSERVICE` service is available in CDS. The CDS response provides information about hundreds of different clusters. Here's a truncated result with just the applicable one:

```json
{
  "clusters": [
    "...many HTTP services",
    {
      "connect_timeout_ms": 2000,
      "hosts": [
        {
          "url": "tcp://instance1.datacenter.opentable.com:1234"
        }
      ],
      "lb_type": "random",
      "name": "TCPSERVICE",
      "type": "strict_dns"
    }
  ]
}
```

And finally, here is what my generated configuration file looks like. If the `egress_listener-TCPSERVICE` section is removed then the file compiles just fine and I'm able to make egress HTTP connections.

```json
{
  "listeners": [
    {
      "name": "ingress_http_listener",
      "address": "tcp://0.0.0.0:3002",
      "filters": [
        {
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "CONSUMERNAME-ingress",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "route_vhost_local_service",
                  "domains": [
                    "*"
                  ],
                  "routes": [
                    {
                      "timeout_ms": 0,
                      "prefix": "/",
                      "host_rewrite": "tcp://127.0.0.1:3000",
                      "cluster": "CONSUMERNAME-cluster-ingress"
                    }
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    },
    {
      "name": "egress_http_listener",
      "address": "tcp://127.0.0.1:80",
      "filters": [
        {
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "CONSUMERNAME-egress",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "route_vhost_remote_services",
                  "domains": [
                    "*"
                  ],
                  "routes": [
                    {
                      "prefix": "/",
                      "cluster_header": "Envoy-Discovery-Target",
                      "timeout_ms": 15000,
                      "retry_policy": {
                        "retry_on": "5xx",
                        "num_retries": 3,
                        "per_try_timeout_ms": 5000
                      }
                    }
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    },
    {
      "name": "egress_listener-TCPSERVICE",
      "address": "tcp://127.0.0.1:6379",
      "filters": [
        {
          "name": "tcp_proxy",
          "config": {
            "stat_prefix": "CONSUMERNAME-egress-TCPSERVICE",
            "route_config": {
              "routes": [
                {
                  "cluster": "TCPSERVICE"
                }
              ]
            }
          }
        }
      ]
    }
  ],
  "cluster_manager": {
    "cds": {
      "refresh_delay_ms": 10000,
      "cluster": {
        "name": "envoy-discovery.api.opentable.com",
        "type": "logical_dns",
        "connect_timeout_ms": 250,
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://envoy-discovery.api.opentable.com:80"
          }
        ]
      }
    },
    "clusters": [
      {
        "name": "CONSUMERNAME-cluster-ingress",
        "connect_timeout_ms": 250,
        "type": "logical_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://127.0.0.1:3000"
          }
        ]
      }
    ]
  }
}
```

My intention with this approach is to provide a catch-all for all HTTP traffic, routing based on the `Envoy-Discovery-Target` header. When it comes to non-HTTP traffic I'll generate a list of those `tcp_proxy` entries based on the name of the cluster and an internal port to listen on.

**Comment by mattklein123** [comment]
Currently, tcp_proxy clusters must be defined when the listener is created. They cannot come later via CDS. Thus, in the current implementation you will need to use LDS also. It would be possible to relax this and allow the tcp_proxy to specify clusters that are not yet defined, but that would require a code change.

**Comment by tlhunter** [comment]
Thanks for the reply, I'll checkout LDS.

**Comment by tlhunter** [comment]
It looks like I can output the following JSON from an LDS to get my desired outcome:

```json
{
  "listeners": [
    {
      "name": "%TCP_SERVICE_NAME%-listener",
      "address": "127.0.0.1:%DESIRED_PORT%",
      "filters": [{
        "name": "%TCP_SERVICE_NAME%-filter",
        "config": {
          "name": "tcp_proxy",
          "config": {
            "stat_prefix": "%TCP_SERVICE_NAME%-egress",
            "route_config": {
              "routes": [{
                "cluster": "%TCP_SERVICE_NAME%"
              }]
            }
          }
        }
      }]
    }
  ]
}
```

However with this scenario the LDS needs to somehow keep a registry of relationships between services. For example if I have consumers C1, C2, C3, then LDS needs to know that C1 needs to talk to producers P4 and P5, C2 needs to talk to P6, etc. Registering these requirements ahead of time seems a little dangerous, especially when C1 version 2.0 is released and needs to talk to P6 and no longer P4. Also, what happens when a developer does one-off local testing?

I do know, at the point in time the envoy.json file is created, which servicename/ports I want to access from a given consumer. Like I know that C1 wants to access P4 and that C1 is expecting to do so over port 1234. The listeners I need won't really be dynamic; C1 will always need to talk to P4 and P5 through the same ports.

Does this still sound like LDS is the best approach? Are most users somehow registering the producers they need to communicate with ahead of time? Does my use-case even make sense or am I beginning to misuse Envoy?

**Comment by mattklein123** [comment]
> Does my use-case even make sense or am I beginning to misuse Envoy?

Unfortunately there is no right answer here. Your use case makes sense, but every use case is different in terms of whether you can use centralized control or service local based configuration. I would say that in general most people are moving towards feeding intention into the central management system and serving it from there.

It's not a very difficult change to add a configuration option to allow TCP proxy config to load with a cluster that does not exist and gracefully fail at runtime if the cluster continues to not exist. If you want to turn this issue into a feature request that's fine also.

**Comment by tlhunter** [comment]
@mattklein123 thanks for the recommendation, glad to hear it wouldn't be a difficult change. I've created #2075.
