### ISSUE TITLE
Implement other protocol as a HTTP codec

### ISSUE THREAD

**Issue by smwyzi** [envoyproxy/envoy#20685]
Now, in source/extensions/filters/network/http_connection_manager/config.cc,
we createCodec according to codec_type_, so if we want to extend a codec, we have to add codes in tree.

How about createCodec using a factory like many other extensions, e.g. network filters extensions, in this way, anyone can extend a new codec in a separate code rep，and static link to envoy using REGISTER_FACTORY when building the separate code rep.

What's more, if someone want to implement a new RPC protocol, it can be implemented as a new HTTP codec, and it has some advantages:

- The new protocol can reuse all of the HTTP filter stacks
- Istio can config envoy for the new protocol using the existing VirtualService and DestinationRule etc.

Is this a proper way to extend Istio & Envoy to support other RPC protocols?

**Comment by zuercher** [comment]
In this case, codec type is an HTTP major version (or the AUTO special case). For what protocol are you trying to add a new codec type?

**Comment by smwyzi** [comment]
> In this case, codec type is an HTTP major version (or the AUTO special case). For what protocol are you trying to add a new codec type?

some private RPC protocol

**Comment by smwyzi** [comment]
> it will lead to all manner of complicated exceptions to HTTP processing

@zuercher yes, i agree with you.

But in the other hand, each protocol is implemented as a separate network filter, has the following defects:

- Each network filter need to implement some commen filters(like HTTP filters), e.g. RateLimit, Router, wasm, fault etc.
- Istio can't config other network filters, VirtualService and DestinationRule can only config HTTP connection manager
