### ISSUE TITLE
cache H2 availability and settings

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#20696]
for the auto_http pool especially (but h2 in general) it'd be good to know if the server spoke H2 last time it was connected to, and what the stream limits were, and prefetching connections / capping stream limits based on that.
cc @jpsim @goaway 

I think I want to do this by extending the alt-svc cache (which already tracks alt-svc headers, quic srtt, quic 0-rtt credentials) to track generic server properties, and having one per cluster by default.
cc @mattklein123 @snowp for thoughts

**Comment by alyssawilk** [comment]
also it makes sense to always have this for DFP, but I'm less sure how we want to handle it for non-dfp clusters for optimal behavior.  appreciate folks' thoughts

**Comment by mattklein123** [comment]
> I think I want to do this by extending the alt-svc cache (which already tracks alt-svc headers, quic srtt, quic 0-rtt credentials) to track generic server properties, and having one per cluster by default.

+1 this makes sense to me and would be great. We should probably rename alt-svc cache to connection properties cache or something like that, but that's a minor point.

**Comment by RyanTheOptimist** [comment]
The Chrome data structure for this is "HttpServerProperties", for what it's worth. Alt-Svc is HTTP specific, so a name with "HTTP" in it makes sense to me. But I'm not married to anything specific.
