### ISSUE TITLE
MaglevLoadBalancer consistent hashing implementation is NOT stable

### ISSUE THREAD

**Issue by mitchsw** [envoyproxy/envoy#20703]
*Title*: `MaglevLoadBalancer` consistent hashing implementation is NOT stable

*Description*:
The `MaglevLoadBalancer` builds a lookup table (LUT) of consistent hashing routes using an algorithm that hashes hostnames/hashKeys/etc for each host. An important prerequisite for this algorithm to be consistent is that **the input vector of hosts are in a stable order**.  This requirement isn't well stated in the [Maglev paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf) (Google's Borg always uses ordinal replicas, and it's somewhat assumed in the paper: `B0`, `B1`, `B2`, ...), but here is another [reference implementation](https://github.com/kkdai/maglev/blob/master/maglev.go#L125) that first string sorts the hosts before building the LUT.

The [Envoy implementation](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/maglev_lb.cc#L19) does not build the LUT from a stable list of hosts. The order of hosts can change due to unrelated system dynamics. When the order of hosts does change, **the Maglev LUT changes** slightly.

The impact is small, so I am not so surprised this bug was previously missed. The order of hosts _mostly_ doesn't matter, except in the case where two hosts share very similar preferences for a LUT entry in their permutation lists. If two hosts contend for the same LUT entry within a single iteration, the order of hosts **does matter** to tie break and decide which host "wins" the LUT entry (order of `entries` in [this loop](https://github.com/envoyproxy/envoy/blob/0a587f23b21ab34b28d9c53428af259b3f7b0970/source/common/upstream/maglev_lb.cc#L35-L36)).

From simulations (see below), approx 20 out of 65537 LUT entries change when permutating the order of 6 hosts (i.e. there are 20 "tiebreaks" between the 6 hosts). This translates to 1-in-3000 (0.03%) keys routing differently whenever the host order changes. Whilst this seems small, it is **definitely a painful correctness bug for systems with hard consistency requirements**.

A stable host order is not a requirement for the `RingHashLoadBalancer` algorithm. It is not impacted.

*Repro steps*:

1. Use Maglev load balancing
2. Use dynamic endpoint discovery of 6 hosts (I used EDS, but DNS may work too)
3. Enable `upstream=trace` logging to print the Maglev lookup table whenever it updates
4. Remove and then re-add a host -> the order of hosts will now be changed 
5. Observe small changes in the new Maglev lookup table (approx 22/65537 errors) even though the hostname (the key we use for consistent hashing) is unchanged - **bug!**
6. Now 1-in-3000 keys are routed to different hosts unexpectedly

*Config*:

* Redis proxy using a Maglev consistent hashing load balancer.
* Endpoint discovery via a xDS control plane.
* Six Redis endpoints

*Logs*:

Here is an example diff of stripped logs from two constructions of the maglev lookup table of the exact same 6 hosts. In both cases, the hostnames did **not** change, but the order of hosts was different due to unrelated service discovery dynamics. In this case, there are 18 out 65537 errors. (If the hostnames _did_ change, there would be many many more diffs.)

```
$ diff /tmp/envoy_lut_stripped_1.txt /tmp/envoy_lut_stripped_2.txt
7143c7143
< [source/common/upstream/maglev_lb.cc:71] maglev: i=7142 address=XX.XXX.XXX.XXX:6379 host=redis-2
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=7142 address=XX.XXX.XXX.XXX:6379 host=redis-0
14323c14323
< [source/common/upstream/maglev_lb.cc:71] maglev: i=14322 address=XX.XXX.XXX.XXX:6379 host=redis-5
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=14322 address=XX.XXX.XXX.XXX:6379 host=redis-2
25561c25561
< [source/common/upstream/maglev_lb.cc:71] maglev: i=25560 address=XX.XXX.XXX.XXX:6379 host=redis-0
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=25560 address=XX.XXX.XXX.XXX:6379 host=redis-3
26572c26572
< [source/common/upstream/maglev_lb.cc:71] maglev: i=26571 address=XX.XXX.XXX.XXX:6379 host=redis-0
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=26571 address=XX.XXX.XXX.XXX:6379 host=redis-3
28330c28330
< [source/common/upstream/maglev_lb.cc:71] maglev: i=28329 address=XX.XXX.XXX.XXX:6379 host=redis-3
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=28329 address=XX.XXX.XXX.XXX:6379 host=redis-5
34846c34846
< [source/common/upstream/maglev_lb.cc:71] maglev: i=34845 address=XX.XXX.XXX.XXX:6379 host=redis-2
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=34845 address=XX.XXX.XXX.XXX:6379 host=redis-0
42811c42811
< [source/common/upstream/maglev_lb.cc:71] maglev: i=42810 address=XX.XXX.XXX.XXX:6379 host=redis-0
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=42810 address=XX.XXX.XXX.XXX:6379 host=redis-5
43034c43034
< [source/common/upstream/maglev_lb.cc:71] maglev: i=43033 address=XX.XXX.XXX.XXX:6379 host=redis-3
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=43033 address=XX.XXX.XXX.XXX:6379 host=redis-0
44178c44178
< [source/common/upstream/maglev_lb.cc:71] maglev: i=44177 address=XX.XXX.XXX.XXX:6379 host=redis-2
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=44177 address=XX.XXX.XXX.XXX:6379 host=redis-1
46285c46285
< [source/common/upstream/maglev_lb.cc:71] maglev: i=46284 address=XX.XXX.XXX.XXX:6379 host=redis-0
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=46284 address=XX.XXX.XXX.XXX:6379 host=redis-3
53595c53595
< [source/common/upstream/maglev_lb.cc:71] maglev: i=53594 address=XX.XXX.XXX.XXX:6379 host=redis-5
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=53594 address=XX.XXX.XXX.XXX:6379 host=redis-0
55287c55287
< [source/common/upstream/maglev_lb.cc:71] maglev: i=55286 address=XX.XXX.XXX.XXX:6379 host=redis-4
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=55286 address=XX.XXX.XXX.XXX:6379 host=redis-0
57384c57384
< [source/common/upstream/maglev_lb.cc:71] maglev: i=57383 address=XX.XXX.XXX.XXX:6379 host=redis-1
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=57383 address=XX.XXX.XXX.XXX:6379 host=redis-4
57429c57429
< [source/common/upstream/maglev_lb.cc:71] maglev: i=57428 address=XX.XXX.XXX.XXX:6379 host=redis-0
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=57428 address=XX.XXX.XXX.XXX:6379 host=redis-3
59122c59122
< [source/common/upstream/maglev_lb.cc:71] maglev: i=59121 address=XX.XXX.XXX.XXX:6379 host=redis-5
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=59121 address=XX.XXX.XXX.XXX:6379 host=redis-2
59863c59863
< [source/common/upstream/maglev_lb.cc:71] maglev: i=59862 address=XX.XXX.XXX.XXX:6379 host=redis-3
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=59862 address=XX.XXX.XXX.XXX:6379 host=redis-5
63646c63646
< [source/common/upstream/maglev_lb.cc:71] maglev: i=63645 address=XX.XXX.XXX.XXX:6379 host=redis-1
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=63645 address=XX.XXX.XXX.XXX:6379 host=redis-4
65386c65386
< [source/common/upstream/maglev_lb.cc:71] maglev: i=65385 address=XX.XXX.XXX.XXX:6379 host=redis-4
---
> [source/common/upstream/maglev_lb.cc:71] maglev: i=65385 address=XX.XXX.XXX.XXX:6379 host=redis-1
```

*Algorithm Simulations:*

 Here is a fragment of a simulation sweep permutating the order of 6 hosts and counting the LUT entries that change.

```
[...]
21/65537 errors (0.0320%) for input host list permutation [4 0 1 2 3 5]
21/65537 errors (0.0320%) for input host list permutation [0 4 1 2 3 5]
18/65537 errors (0.0275%) for input host list permutation [1 0 4 2 3 5]
18/65537 errors (0.0275%) for input host list permutation [0 1 4 2 3 5]
16/65537 errors (0.0244%) for input host list permutation [1 4 0 2 3 5]
24/65537 errors (0.0366%) for input host list permutation [4 1 0 2 3 5]
18/65537 errors (0.0275%) for input host list permutation [2 4 0 1 3 5]
18/65537 errors (0.0275%) for input host list permutation [4 2 0 1 3 5]
22/65537 errors (0.0336%) for input host list permutation [0 4 2 1 3 5]
[...]
```

Also, as the number of hosts increases, so does the number of "tiebreaks", and hence errors increases too. Some extreme cases:

 * When simulating reversing a list of 200 hosts, 1-100 LUT entries change.
 * When simulating reversing a list of 500 hosts, 1-50 LUT entries change.

**Comment by mattklein123** [comment]
Thanks for the really detailed report! Super interesting. The fix seems simple enough if you would like to do a PR. Thank you!

**Comment by mitchsw** [comment]
Yes glad to take a look @mattklein123

**Comment by y1r** [comment]
I submitted a pull request to solve this issue: https://github.com/envoyproxy/envoy/pull/28055
