### ISSUE TITLE
Add gcloud resultstore to CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#20714]
### description

@alyssawilk has tested out the resultstore ui with our CI and it seems this would be a very useful/welcome addition

there are 2 things that need to happen

- add bazel CI flags
- ensure CI gcloud acc has the relevant IAM set up

**Comment by alyssawilk** [comment]
I think I granted the correct permissions for the account, though I'm less sure of how to run the steps with the script to verify.  happy to help if you run into problems.
cc @keith @lizan for visibility

**Comment by lizan** [comment]
Let's see how it goes https://github.com/envoyproxy/envoy/pull/20729

@alyssawilk I don't see permission is added to the two used in azp, that might needed.

**Comment by alyssawilk** [comment]
I thought I added it to all our user agent accounts.  can you let me know which I misssed?

**Comment by lizan** [comment]
@alyssawilk azure-pipelines@envoy-ci.iam.gserviceaccount.com andazure-pipelines-release@envoy-ci.iam.gserviceaccount.com

**Comment by alyssawilk** [comment]
cloud projects add-iam-policy-binding envoy-ci --role roles/cloudsourcetoolscore.developer --member serviceAccount:azure-pipelines@envoy-ci.iam.gserviceaccount.com 
worked happily

on the other I got 
  detail: Service account azure-pipelines-release@envoy-ci.iam.gserviceaccount.com
    does not exist ?

**Comment by lizan** [comment]
@alyssawilk the release service account is `azure-pipeline-release@envoy-ci.iam.gserviceaccount.com`  (no s after pipeline)

**Comment by alyssawilk** [comment]
gah sorry, done for that one as well

**Comment by lizan** [comment]
Fixed by #20729
