### ISSUE TITLE
inline_string encode

### ISSUE THREAD

**Issue by fengyangdi** [envoyproxy/envoy#20713]
*Title*: *What is the encode for inline_string*

*Description*:
>I use inline_string for direct_response, in string,there are some chinese, like 你好，I use several unicode like \u4f60\u597d and \344\275\240\345\245\275 and \xe4\xbd\xa0\xe5\xa5\xbd , \ue4bda0e5a5bd all not right

**Comment by lizan** [comment]
https://developers.google.com/protocol-buffers/docs/encoding protobuf string is UTF-8. You might want to use `inline_bytes` instead for specific encoding.

**Comment by fengyangdi** [comment]
> https://developers.google.com/protocol-buffers/docs/encoding protobuf string is UTF-8. You might want to use `inline_bytes` instead for specific encoding.

I have tried inline_bytes, it will download a file

**Comment by fengyangdi** [comment]
> https://developers.google.com/protocol-buffers/docs/encoding protobuf string is UTF-8. You might want to use `inline_bytes` instead for specific encoding.

same as inline_string or will download a file

**Comment by lizan** [comment]
whether your browser downloads a file depends on `content-type` header, you need to specify that in your route.

**Comment by fengyangdi** [comment]
> content-type

OK, It's OK, I have set the wrong response header， inline_string is ok， no need special encode，thank you!
