### ISSUE TITLE
Local ratelimit sandbox is flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#20712]
### description

The new local rate limit sandbox is failing verification fairly frequently in CI

for example here https://dev.azure.com/cncf/envoy/_build/results?buildId=105533&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&s=9703e969-5193-5265-9b36-ed5b6d7fdc01&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=8485

**Comment by phlax** [comment]
@daixiang0 it would be v helpful if we resolve this asap - im seeing quite a lot of flakes for this and if we fix before 1.22 is cut we will avoid adding a flake on the release branch

**Comment by daixiang0** [comment]
Will do it this week.

**Comment by mattklein123** [comment]
@phlax if this is flaky let's just revert and we can reapply after the release?

**Comment by daixiang0** [comment]
I think the cause is the small token refresh time makes the limit unexpected, I will post a fix to enlarge time today.

Feel free to revert it before the release.

**Comment by daixiang0** [comment]
BTW, does it mean that one requirement of the release is no flaky tests, or has it been marked as flaky?
