### ISSUE TITLE
where to set runtime settings and what runtime settings do we have？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20730]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
where to set runtime settings and what runtime settings do we have？*Description*:
>Describe the issue.
where to set runtime settings and what runtime settings do we have？
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zuercher** [comment]
Runtime feature flags are typically documented with the field in the control plane API that they modify. They should also appear in the release notes for Envoy versions when they are added, when their default values are modified, and when they are removed. That said, they're [enumerated in the code](https://github.com/envoyproxy/envoy/blob/main/source/common/runtime/runtime_features.cc).

There are also other runtime flags whose names are based on information in the config. For instance, [weighted cluster routing](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#config-route-v3-weightedcluster) has a `runtime_key_prefix` field that's used to allow runtime-overrides for cluster weights on a per-cluster basis.

Configuration is covered here: https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime
