### ISSUE TITLE
Feature Request: Allow configuring of tcp_proxy with CDS

### ISSUE THREAD

**Issue by tlhunter** [envoyproxy/envoy#2075]
Currently we're able to configure `http_connection_manager` with CDS. This allows applications to perform egress service discovery over HTTP and route using various methods, such as HTTP headers.

It would be very convenient to allow configuring `tcp_proxy` via CDS as well. Of course TCP messages cannot be routed using HTTP headers. Being able to provide different ports to listen on and and specify which cluster they should route to would then allow applications to easily perform TCP egress.

> Currently, tcp_proxy clusters must be defined when the listener is created. They cannot come later via CDS. [...] It's not a very difficult change to add a configuration option to allow TCP proxy config to load with a cluster that does not exist and gracefully fail at runtime if the cluster continues to not exist. If you want to turn this issue into a feature request that's fine also.
> -- @mattklein123 (Issue #2068)

Currently if one tries to use `tcp_proxy` with CDS the following error is generated:

```
[2017-11-15 01:18:26.445][251][critical][main] source/server/server.cc:78] error \
  initializing configuration '/etc/envoy.json': tcp proxy : unknown cluster \
  'TCPSERVICE' in TCP route
```

Ideally it could perhaps emit a warning. Once the first CDS request succeeds the `tcp_proxy` would then begin proxying connections.

Please see #2068 for more background and example `envoy.json` configuration.

**Comment by rshriram** [comment]
did you mean RDS by any chance? CDS pertains to clusters. We use CDS throughout envoy in Istio, for TCP and HTTP. For TCP, we are using LDS, though its less than ideal. Something like RDS would be more fitting.

**Comment by tlhunter** [comment]
Yeah, I meant CDS.

I have a giant collection of name: [host/port] combinations which I can route HTTP requests to just fine. The goal is to be able establish a connection with one of those instances and do the same using TCP.

**Comment by snowp** [comment]
Is this still a an issue? Looking at the source it looks like the validation is only performed on the V1 config: https://github.com/envoyproxy/envoy/blob/master/source/common/filter/tcp_proxy.cc#L60-L75

Can this be bypassed with the V2 config? Or is there something I'm missing?

**Comment by mattklein123** [comment]
@snowp hmm yeah I guess this isn't an issue for v2 simple configs. I think the main issue here is that with out the deprecated v1 stuff we don't support more complex routing w/o the checks (that more complex stuff in v2 us ultimately meant to be implemented as part of filter chain matching).

IMO we can just remove the checks for the v1 part since the rest of the code should work fine and then call this resolved. @ggreenway WDYT?

**Comment by mattklein123** [comment]
(The other option is to introduce an option much like the "validate_clusters" option for HTTP routes, since some people like to have the checking in place to catch errors).

**Comment by ggreenway** [comment]
I'm fine with removing that check. It looks like everything will still work.

**Comment by mattklein123** [comment]
Fixed
