### ISSUE TITLE
get `bootstrap.node.metadata` in access logs?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#20784]
*Title*: *One line description*

get `bootstrap.node.metadata` in access logs?

*Description*:

want to output some metadata to access log, can I get `bootstrap.node.metadata` in access logs?

**Comment by MarcinFalkowski** [comment]
@zirain Sorry for reviving the old issue, but I just stumbled upon it searching for the same question. 
You closed it as completed, but I don't see explanation / link how to achieve it. Can you help me?

**Comment by zirain** [comment]
you should be able to do this with `%CEL(xds.node.xxxx)%`

related to:
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.html#configuration-attributes
- https://github.com/envoyproxy/envoy/pull/31319
