### ISSUE TITLE
grpc `proto_descriptor` not parseable

### ISSUE THREAD

**Issue by kenjones-cisco** [envoyproxy/envoy#2078]
**Issue Template**

*Title*: *One line description*
grpc `proto_descriptor` not parseable

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it 
would be used.

Following the instructions for generating the [required descriptor](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter.html#configure-grpc-json-transcoder), protoc generates the file as expected.

I add the file to my ConfigMap for Openshift, and then the `envoyproxy/envoy-alpine` reads the configuration file and attempts to load the descriptor file. But it keeps resulting in the error `transcoding_filter: Unable to parse proto descriptor`. 

I'm using **protoc v3.5.0** with syntax `proto3`.

```bash
protoc -I/googleapis -I. --include_imports --include_source_info --descriptor_set_out=proto.pb src/main/proto/tenants.proto
```

The tenants.proto, proto.pb, and envoy.yaml can be found here:
https://gist.github.com/kenjones-cisco/1aaf30094bfaf0717ddd879e11ad1f50

I'm trying to determine why the file can't be parsed. I know it is accessible as the file is located in the same directory as the `envoy.yaml` and I provide the full absolute path to the `proto.pb` file.
Are there any limitations as to the version of protobuf? Any other ways to determine the root cause of the issue?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
@lizan do you mind taking a look?

**Comment by lizan** [comment]
I'm back, will take a look later today.

**Comment by lizan** [comment]
@kenjones-cisco I could reproduce it with the `proto.pb` in your gist.
But when I use protoc v3.5.0 with same command to generate the proto descriptor again, it works.

My generated proto descriptor is [here](https://gist.github.com/lizan/9836b131dda526fbec70308c85b8457e), which works.

Note the proto descriptor is a binary, but in your gist looks like github is treating it as text. So I doubt I got same file content as yours. What is your `proto.pb` md5 hash?

**Comment by lizan** [comment]
I think the problem is that ConfigMap is not binary safe. See:
https://github.com/kubernetes/kubernetes/issues/32432

**Comment by kenjones-cisco** [comment]
@lizan  Thanks, for the response and feedback. 

That does make sense about ConfigMap. I guess I will need to actually copy the file directly into the envoy image to make use of it.

**Comment by developersPHP** [comment]
hi you slove the question? i have the same problem. when initializing envoy configuration .the error message like this:
error initializing configuration '/etc/envoy/envoy.yaml': transcoding_filter: Could not find 'reservations.ReservationService' in the proto descriptor
