### ISSUE TITLE
cannot open source file "envoy/config/route/v3/route_components.pb.h"C/C++(1696)

### ISSUE THREAD

**Issue by zackzhangkai** [envoyproxy/envoy#20785]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

Cannot find some pkg in code.

*Description*:
>Describe the issue.

1. cannot open source file "envoy/config/route/v3/route_components.pb.h"C/C++(1696)

![image](https://user-images.githubusercontent.com/20178386/162921632-8606c051-3eec-4b0d-8ee0-e94641466994.png)

2. cannot open source file "absl/container/node_hash_set.h"C/C++(1696)

![image](https://user-images.githubusercontent.com/20178386/162921726-ce345eae-8884-4cb1-8950-aabd7efa87af.png)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
I'm newer to c++, otherwise, expect your warningly response.Thanks a lot!

**Comment by zuercher** [comment]
That file is generated during the build. See `.devcontainer/README.md` -- I think that might help, but I don't use VScode. Another option might be to ask in the Envoy slack.

**Comment by daixiang0** [comment]
Please check `tools/vscode`, then you can run task to refresh comdb.

**Comment by zackzhangkai** [comment]
Thanks for your warmly replying. Because of my GreatWall Internet in China, I cannot download some packages by executing the shell as the tools/vscode. 

By the way, which IDE your are using and recommend.

**Comment by daixiang0** [comment]
I think you need a proxy server to download the necessary dependencies. 

The vscode is official support, others I have no ideas.
