### ISSUE TITLE
tracing: RFC Fine grained tracing in Envoy

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#2081]
Currently Envoy tracing does not distinguish between client and server spans. The zipkin tracer does it implicitly based on the ‘operation_name’. To be able to make better use of finer grained tracing, with internal spans representing the steps performed within the proxy (both edge and middle), then the span kind should be explicitly defined on the relevant span. Although LightStep may not have a problem with this, the new PR to move to the OpenTracing API means at some point other OpenTracing compatible tracers will be supported, and they may rely on the client/server spans being defined correctly.

There are three scenarios:

(a) Middle ingress (representing inbound request to the service)

In this case we would want to record a “server” span when receiving the request (in the HTTP connection manager) and then atleast an internal span to represent the call out from the router (to the service). 

(b) Middle egress (representing outbound request from the service)

In this case we would want to record an internal span when receiving the request from the service (in the HTTP connection manager) and then a “client” span to represent the call out from the router to a remote service/proxy.

(c) Edge proxy

The edge proxy is representing a gateway - so think it would be good if this created a ‘server’ span on receiving the request (i.e. in the connection manager) and then a ‘client’ span in the router.

In all of these scenarios, internal spans can be optionally recorded to identify the tasks performed by the listener (e.g. authentication, rate limiting, etc).

Main proposed changes:

- Explicitly tag appropriate spans with the “span.kind” tag of “client” or “server”
- Only decorate those client/server spans with the relevant http tags
- Change zipkin tracer to use the “span.kind” tag value (which will not actually be stored in the zipkin span) as an indication of whether to create client or server annotations
- Optionally create an internal span per filter
- Introduce new “operation_name” value of “Edge” - to represent an edge proxy - so that it will create a server span and a client span - representing a gateway between the real client app and the service - and also other internal spans representing the steps performed by the gw.

**Comment by mattklein123** [comment]
This sounds like a reasonable plan to me. @rnburn any thoughts on ^?

**Comment by rnburn** [comment]
Yes, looks good to me.

**Comment by objectiser** [comment]
@mattklein123 @rnburn  One thing I would like to clarify - in the current impl the internal span created in the router can be disabled.

In the steps outlined above, the internal spans generated per filter (e.g. auth, rate limiting, etc) could be enabled based on configuration. However I am not sure whether the internal spans created in the HTTP conn mgr and router should be optional?

For example, handling an inbound request, the server span would be created in the HTTP conn mgr - if there is a possibility that the router will be called multiple times (e.g. to handle retries) then each retry would ideally need to create a new span. Similarly for outbound requests - the router would be creating the 'client' span - but if it results in retries, then may be better to have the internal span (created in the HTTP conn mgr) to contain those multiple 'client' spans.

So wondering whether it is better to always create the internal spans in the HTTP conn mgr and router - and only have the other internal spans (for the other filters) optional? The downside is that this would create more spans.

Other option is have them optional, but possibly enable them automatically if a retry policy has been defined.

**Comment by mattklein123** [comment]
@objectiser yeah, I've thought through a bunch of ^. My concern about always creating the router span is that in simple cases, we will add an extra level of nesting for no reason. Over  many hops, and without intelligent filtering on the trace UI side, this will make the traces substantially more dense than they need to be.

I would personally err on the side of things being optional and/or putting intelligence in based on retry policy as you mention. 

Thoughts?

**Comment by objectiser** [comment]
Yeah I think having internal spans optional (possibly based on one property rather than property per filter?) - and then auto enable the internal span in httpconnmgr/router if retry policy.

**Comment by mattklein123** [comment]
I think it's actually a bit more complicated than just retry in thinking about it more. For example, at Lyft we need to make the router span because we also make auth/ratelimit spans, independent of retry policy. Potentially we need some concept to ask if other internal spans have been created off of the parent span and then also key off of that?

**Comment by objectiser** [comment]
That is why I was thinking that all internal spans should be created off a single config property - so we would have three situations:
* internal spans disabled and no retry - so just create the client or server span
* internal spans disabled but retry policy - this would create the client/server/internal spans in the httpconnmgr and router only
* internal spans enabled - this would create spans in httpconnmgr, router and all other filters.

However if you would prefer more individual control over which filters created spans, then as you say, any span created in a filter would require a span to also be created in in the httpconnmgr.

**Comment by mattklein123** [comment]
FWIW I think we should continue to allow individual control. Within that confine, I think it also is fine to allow more automated options, but it's not super clear to me what the options should be. Perhaps we can discuss in the context of a data-plane-api PR?

**Comment by objectiser** [comment]
Sounds like a plan - if you have a concrete idea then feel free to create the issue, otherwise I'll create one in the next couple of days.

**Comment by objectiser** [comment]
As discussed on https://github.com/envoyproxy/data-plane-api/issues/265 there is currently no need for additional config to support this, if the parent span is created on demand (if does not already exist) when required by a filter.

One [question](https://github.com/envoyproxy/data-plane-api/issues/265#issuecomment-347355200) raised on that issue, regarding the start time associated with the parent span, would need to be considered. Preferrably, if the parent span is being created on demand due to a filter, then the parent span should be created with the time when the request was initially received by the connection manager.

**Comment by mattklein123** [comment]
IIRC this work has been completed. @objectiser LMK if that isn't the case.

**Comment by objectiser** [comment]
@mattklein123 Sorry its been open along time. I think some areas may have been addressed, or no longer relevant, but explicitly setting the `span.kind` still needs to be done. I'll just open a separate issue for this.
