### ISSUE TITLE
Patch releases for supported versions

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#20826]
### Description

The current docker images have flagged CVE issues (at least some of which are known not to affect us)

There were also some issue with the last patch releases related to docs and the version reported by the binary

For above reasons we will be releasing some patch versions:

- [x] 1.19.4 - https://github.com/envoyproxy/envoy/milestone/23
- [x] 1.20.3 - https://github.com/envoyproxy/envoy/milestone/24
- [x] 1.21.2 - https://github.com/envoyproxy/envoy/milestone/25

Release images for 1.18 and below have not been included as these are EOL

We may want to make this clearer with docs etc if we are not going to patch them

**Comment by phlax** [comment]
cc @pradeepcrao

**Comment by daixiang0** [comment]
Do we have something like cherry-pick bot in Istio like https://github.com/istio/istio/pull/37873#issuecomment-1065814764? I think it is useful and make backport easier and clearer.

**Comment by phlax** [comment]
@pradeepcrao i have created milestones for each of the patch releases and updated the links in this ticket to reflect

i have also grouped any PRs i could see into their relevant milestone
