### ISSUE TITLE
thrift: struct name are decoded as empty strings, which impacts decoderFilter

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#20838]
*Title*:  struct name are decoded as empty strings for thrift decoder

*Description*:
thrift decoder wrongly decodes the struct name, field name and other container name to empty string.
(FYI decoder works for metadata and stringValue)

As a result, all the filters would get the empty struct name.

*Repro steps*:
I use this test as example
https://github.com/envoyproxy/envoy/blob/007eb3f5d80df65a9d91f3f6e4641b44a39a0747/test/extensions/filters/network/thrift_proxy/conn_manager_test.cc#L209
and do `cout` in the decoder code, figure out empty string from the decoder.

**Comment by zuercher** [comment]
The struct names aren't used in any of the currently supported protocols. They're not generally available at runtime. IIRC, the original plan had been to support the JSON protocol, where they're necessary.

**Comment by JuniorHsu** [comment]
Thanks @.zuercher for the helpful information.
I'll make the test in #20816 reflect this fact.
