### ISSUE TITLE
Large tail latency when using sync HttpCall function in lua filter

### ISSUE THREAD

**Issue by siyigao1212** [envoyproxy/envoy#20842]
*Description*:
We are using lua filter **sync** HttpCall function in lua filter to call a thirdParty service, the script is just like this
```
    local headers, body= handle:httpCall(
        "cluster_name",
        {
            [":method"] = "GET",
            [":path"] = "service_path",
            [":authority"] = "authority",
        },
        "",
        5000
    )
```
We found that with a higher QPS like 500, there will be a large tail latency like P99=20-40ms when envoy concurrency > 1, after breaking down the latency, we found that the bottleneck is the latency from the third party service respond to envoy.

When we change the envoy' concurrency to 1 or  change the http call mode to async, there won't be such problems. So is there any issue for lua filter to deal with the response at sync mode?

**Comment by zuercher** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
The async request does not care about the third-party response, it will be quickly of course. So I think the sync or async does not mattter.

The performance of third-party service is the key point. Can you provide some more stats about your scene? For example:
- qps of the third-party service? will it be different when set envoy concurrency > 1?
- envoy metrics data of your target cluster (third-party service)? We can get the P99/P95 value from the `upstream_rq_time`. We can compare these values under different configurations.

**Comment by siyigao1212** [comment]
Thanks @wbpcode , very happy to know there is no problem with sync mode for lua filter.

After checking the third party service, we found that it's some problem with the tcp_nodelay settings. Thanks for your response anyway.

**Comment by jtway** [comment]
@siyigao1212 any chance you're able to share more on the tcp_nodelay settings that were problematic? We've seen similar issues (without LUA) in select environments. Unsure if they are the same.

**Comment by siyigao1212** [comment]
The solution we used to solve the tail latency is to set tcp_nodelay as true, which means disable the Nagle's Algorithm. Nagle's Algorithm is to reduce the number of small packets of tcp socket and then improve network utilization, but at our scenario, it could cause the large tail latency problem. So if the tail latency is very important, it's better to disable Nagle Algorithm.
