### ISSUE TITLE
Support for abstract namespace UDS upstream clusters

### ISSUE THREAD

**Issue by loozau** [envoyproxy/envoy#2085]
Feature request: please add support for abstract sockets as an upstream cluster (on Linux).

There's already some code to detect whether a socket address is an abstract UDS https://github.com/envoyproxy/envoy/blob/2ac2e2e93f262f98dd3733bfe9084e9dc40d9992/source/common/network/address_impl.cc#L228, but it just raises an exception.

*Config*
The configuration file should specify abstract sockets with a leading '@' character, rather than the real '\0' character, as it's not ergonomic to have null bytes in the configuration file. '@' as '\0' is used by Linux's netstat, and Go (https://github.com/golang/go/blob/master/src/syscall/syscall_linux.go#L312).

Sample cluster config snippet:
```
{
  "name": "service",
  "connect_timeout_ms": 100,
  "type": "static",
  "lb_type": "random",
  "hosts": [
     {
        "url": "unix://@abstract/uds"
        "url": "unix:///tmp/regular/uds"
     }
  ]
}
```

*Relevant Links*
http://man7.org/linux/man-pages/man7/unix.7.html

**Comment by loozau** [comment]
Here're patches that I've used to get things working locally. Off the top of my head, there's still a lot missing:
- Tests
- A better understanding of where PipeInstances are used
- Verification that we're running on Linux.

```
*** address_impl.cc
--- address_impl.cc
***************
*** 235,251 ****
--- 235,262 ----
  PipeInstance::PipeInstance(const std::string& pipe_path) : InstanceBase(Type::Pipe) {
    memset(&address_, 0, sizeof(address_));
    address_.sun_family = AF_UNIX;
    StringUtil::strlcpy(&address_.sun_path[0], pipe_path.c_str(), sizeof(address_.sun_path));
    friendly_name_ = address_.sun_path;
+   if (address_.sun_path[0] == '@') {
+     address_length_ = strlen(address_.sun_path);
+     address_.sun_path[0] = '\0';
+     abstract_namespace_ = true;
+   }
  }
  
  int PipeInstance::bind(int fd) const {
+   if (abstract_namespace_) {
+     return ::bind(fd, reinterpret_cast<const sockaddr*>(&address_), 2 + address_length_);
+   }
    return ::bind(fd, reinterpret_cast<const sockaddr*>(&address_), sizeof(address_));
  }
  
  int PipeInstance::connect(int fd) const {
+   if (abstract_namespace_) {
+     return ::connect(fd, reinterpret_cast<const sockaddr*>(&address_), 2 + address_length_);
+   }
    return ::connect(fd, reinterpret_cast<const sockaddr*>(&address_), sizeof(address_));
  }
  
  int PipeInstance::socket(SocketType type) const { return socketFromSocketType(type); }
```

```
*** address_impl.h
--- address_impl.h
***************
*** 203,212 ****
--- 203,214 ----
    int connect(int fd) const override;
    const Ip* ip() const override { return nullptr; }
    int socket(SocketType type) const override;
  
  private:
+   bool abstract_namespace_{false};
+   int address_length_{0};
    sockaddr_un address_;
  };
  
  } // namespace Address
  } // namespace Network
```

**Comment by mattklein123** [comment]
@loozau in general this seems reasonable to me. If you want to work on a PR please go for it (we can help in slack / in PR if needed). Thank you!

**Comment by syml** [comment]
I'm going to follow up on this. @loozau helped me getting started
I have a PR https://github.com/envoyproxy/envoy/pull/2512. I would appreciate some help to get it through :) Tests especially need some enhancement.

**Comment by mattklein123** [comment]
Fixed.
