### ISSUE TITLE
Install and use Lua modules in Lua filters

### ISSUE THREAD

**Issue by norbjd** [envoyproxy/envoy#20859]
*Title*: *Install and use Lua modules in Lua filters*

*Description*:

Is it possible to install Lua modules to use in Lua filter? My specific use case is to retrieve the nanoseconds using the [`luaposix`](https://github.com/luaposix/luaposix) module (see example below), but in fact, it can be anything else with any module.

Example:

```yaml
http_filters:
- name: envoy.filters.http.lua
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
    inline_code: |
      function envoy_on_request(request_handle)
        posix = require 'posix'
        sec, nsec = posix.clock_gettime(0)
        request_handle:logInfo(nsec)
      end
```

Obviously, this module is not installed so I get the error:

```
[2022-04-16 16:12:58.697][17][error][lua] [source/extensions/filters/http/lua/lua_filter.cc:768]
    script log: [string "function envoy_on_request(request_handle)..."]:2: module 'posix' not found:
        no field package.preload['posix']
        no file './posix.lua'
        no file '/b/f/w/bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/luajit.build_tmpdir/luajit/
        no file '/usr/local/share/lua/5.1/posix.lua'
        no file '/usr/local/share/lua/5.1/posix/init.lua'
        no file '/b/f/w/bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/luajit.build_tmpdir/luajit/
        no file '/b/f/w/bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/luajit.build_tmpdir/luajit/
        no file './posix.so'
        no file '/usr/local/lib/lua/5.1/posix.so'
        no file '/b/f/w/bazel-out/k8-opt/bin/external/envoy/bazel/foreign_cc/luajit.build_tmpdir/luajit/
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

Am I missing something or this is just impossible? For info, I'm running envoy in a Docker container so if there are extra steps to install the module inside the container, this is fine for me.

**Comment by wbpcode** [comment]
Hi, how did you run the Envoy? Run Envoy with a docker? From the logs, you may need install the [luaposix](https://github.com/luaposix/luaposix) wich luarocks in your container or host.

**Comment by norbjd** [comment]
@wbpcode :wave:  thanks for the answer. I'm running Envoy with Docker. To my surprise, I don't see Lua installed in the container:

```
$ docker run --rm -it --entrypoint sh envoyproxy/envoy:v1.22.0
# lua
sh: 1: lua: not found
# find / -name 'lua' # returns nothing
# find / -name '*.lua' # returns nothing
```

So I tried to install it myself, alongside with `luaposix` via `luarocks`.

```Dockerfile
FROM    envoyproxy/envoy:v1.22.0

RUN     apt update && apt install -y \
            wget build-essential unzip \
            luajit libluajit-5.1-dev

# install luarocks (see https://luarocks.org/ "Quick Start")
RUN     wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz \
 &&     tar zxpf luarocks-3.8.0.tar.gz \
 &&     cd luarocks-3.8.0 \
 &&     ./configure && make && make install \
 &&     cd -

RUN     luarocks install luaposix
```

But when doing a request to Envoy, I get an error:

```
[2022-04-18 08:51:54.127][42][error][lua] [source/extensions/filters/http/lua/lua_filter.cc:768] 
    script log: error loading module 'posix.glob' from file '/usr/local/lib/lua/5.1/posix/glob.so':
        /usr/local/lib/lua/5.1/posix/glob.so: undefined symbol: lua_gettop
```

I've also tried installing `lua5.1 liblua5.1-dev` instead of `luajit libluajit-5.1-dev`, but got the same error.

I'm not sure that installing Lua like this is the right way. But `luarocks` require Lua, so it must be installed.

**Comment by wbpcode** [comment]
Envoy buid and link luajit staticly. So luajit is not installed in the container. 

In my scene, I installed `luarocks` with apt directly. And you may be need rebuild envoy binary with external flags `--define exported_symbols=enabled`.

```
* Exported symbols during linking with `--define exported_symbols=enabled`.
  This is useful in cases where you have a lua script that loads shared object libraries, such as
  those installed via luarocks.
```
https://github.com/envoyproxy/envoy/blob/main/bazel/README.md

**Comment by wbpcode** [comment]
I cannot promise it. But it would be work after rebuilding. I build our envoy with this flag and its ok to use libs installed by the luarocks.

**Comment by mattklein123** [comment]
See also this PR: https://github.com/envoyproxy/envoy/pull/17492#issuecomment-1098834259.

I would like to get this fixed in the official builds by just permanently exporting all Lua symbols. This will require sending an export table to the linker with a specific set of symbols. If someone could do this that would be awesome.

**Comment by wbpcode** [comment]
And don't think you need install luarocks when you building envoy binary.

**Comment by norbjd** [comment]
@wbpcode I'll try to tweak envoy build then, thanks :stuck_out_tongue: I thought that the module should be installed before the build, but you're right, this makes no sense. Sorry about the newbie question.

@mattklein123 so you mean that with the PR you linked, there will be no more needs to rebuild envoy with a specific option? That would be great! :raised_hands:

**Comment by mattklein123** [comment]
> @mattklein123 so you mean that with the PR you linked, there will be no more needs to rebuild envoy with a specific option? That would be great! raised_hands

Yes. The issue with the linked PR is it exported *all* symbols which adds a huge amount to the binary size. We can't ship that. But if we only export the Lua symbols it should be a pretty small size addition and will be worth it. cc @keith

**Comment by keith** [comment]
Yea I think that PR was on the right track, is anyone interested in picking up that work? I imagine the biggest piece will be enumerating the required symbols, and measuring the size difference.

**Comment by wbpcode** [comment]
I can take it, but I have no much free bandwidth recently. so if there is no other one can take it, I can try to land it afterwards.

**Comment by norbjd** [comment]
Hello @wbpcode, thanks for working on this! Does #21102 solves this issue and enable the usage of Lua modules **by default**? I cannot test since there is no release yet with this PR :smile:

**Comment by wbpcode** [comment]
@norbjd yep. May be you can test it with a dev image?

**Comment by norbjd** [comment]
@wbpcode Sadly I can't find a `dev` tag on Docker Hub (I've also searched for `edge`, `main` or `latest` but couldn't find). Are `dev` images pushed to another registry?

**Comment by wbpcode** [comment]
@norbjd check here https://hub.docker.com/r/envoyproxy/envoy-dev/

**Comment by norbjd** [comment]
@wbpcode Thanks, it works!

For reference, I tried with the following `Dockerfile`, with the `envoy-dev` image based on the commit linked to the PR #21102 (6abcebc93f3d0616ba38ad9c5fec97dfc9c32645). It works too with the last commit at the time of writing (c4ecdd07585d43fb2bbe145b60417ba412941ec8).

```Dockerfile
FROM    envoyproxy/envoy-dev:6abcebc93f3d0616ba38ad9c5fec97dfc9c32645

RUN     apt update && apt install -y \
            luarocks

RUN     luarocks install luaposix
```

I have no longer the error `module 'posix' not found`, and the Lua script in my question prints correctly `nsec`.

I'm closing this issue, thanks again for your work! :muscle:
