### ISSUE TITLE
possible opt to filter match wrapper and http filter chain

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#20866]
*Title*: *some possible opts to composite filter and http filter chain*

*Description*:

Current composite filter may inject match tree to the `ActiveStreamFilterBase` instances. And then when we iterate the http filters, the match tree will be evalated and decide to skip the composite filter or not.

This way is very flexible but make the http filter chain APIs more complex. Why could we add a new API to `Http::FilterChainFactoryCallbacks` to return http headers. And when we create the filter instance, we can add the filter instance to filter chain or not according to the match result.

```
  return [stats, match_tree](Http::FilterChainFactoryCallbacks& callbacks) -> void {
    if(match(callbacks.requestHeaders(), match_tree) {
      auto filter = std::make_shared<Filter>(*stats, callbacks.dispatcher());
      callbacks.addStreamFilter(filter);
      callbacks.addAccessLogHandler(filter);
    }
  };

```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
cc @snowp

**Comment by wbpcode** [comment]
Hi @snowp, any suggestion to this issue? will it be a possible approach? May be we can even add inner filter/filters to filter chain directly to avoid delegating. 🤔

**Comment by snowp** [comment]
How would one specify the match here? Would it be up to the filter implementation to specify the match criteria? If so how would this differ from just having the filter noop when it sees these headers?

There has been some discussions around this kind of flexible HTTP filter chains (cc @mattklein123 @htuch who were previously involved), and iiuc the concern was making it too hard to reason about the final filter chain. 

Do you have a concrete use case in mind? I think that would help drive the discussion

**Comment by wbpcode** [comment]
> How would one specify the match here? Would it be up to the filter implementation to specify the match criteria? If so how would this differ from just having the filter noop when it sees these headers?

The composite filter factory will complete this matching and then decide to add inner filter to chain or not. So all the other filters needn't do this  headers check. Any filter/filters that need optioanl semantics can use the composite filter as the checker.

**Comment by wbpcode** [comment]
> Do you have a concrete use case in mind? I think that would help drive the discussion

Yeah. I can create a quick draft PR to drive the discussion. But this need to wait for me to complete some current works.

**Comment by wbpcode** [comment]
Sorry for my mistake. I think I got the match wrapper and composite filter mixed up. 😞 I will do some more investigation and then create a draft PR.
