### ISSUE TITLE
what's the difference between cache filter and buffer filter?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20861]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
what's the difference between cache filter and buffer filter?
*Description*:
>Describe the issue.
what's the difference between cache filter and buffer filter?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Envoy http filters will handle HTTP requests in a streamlined manner by default. 
```
Get header -> Process header -> Send header -> Get body -> Process body -> Send body.
```

The buffer filter will stop the filter iteration. And continue the iteration after the whole http request is buffered.
The cache filter will cache the http responses to reduce accesses to the backend services and get higher throughput and lower latency.
