### ISSUE TITLE
docs: wrong release notes in recent merge

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#20876]
*Title*: docs: wrong release notes in recent merge

*Description*:
Commit 0e8899c90213b39d8f4a1a083d4fd31e9c2fe8c1 introduced in #20757 contains new features of the previous version in the release notes.

In the file changes, we can see nearly 50 new features are introduced, while they are exactly the new features of v1.22.0 except the ext_proc one which is the real new feature.

**Comment by wbpcode** [comment]
cc @phlax @htuch

**Comment by wbpcode** [comment]
May be we can revert the single file and just add the correct release note to the file to fix it?

**Comment by zhxie** [comment]
Ok, I will submit a quick fix.

**Comment by mpwarres** [comment]
Oof, sorry about that. It didn't occur to me to doublecheck release notes after a conflict-free merge from main. Lesson learned!
