### ISSUE TITLE
How to change the User-Agent for gRPC HealthCheck

### ISSUE THREAD

**Issue by na-ga** [envoyproxy/envoy#20884]
*Title*: 

Is there a way to change the User-Agent for gRPC HealthCheck?

*Description*:

The User-Agent for gRPC HealthCheck is "Envoy/HC". gRPC HealthCheck uses the following `service_name` option You can change the `service` in `grpc.health.v1.HealthCheckRequest`, but not the UserAgent.

- https://www.envoyproxy.io/docs/envoy/v1.21.0/api-v3/config/core/v3/health_check.proto.html#config-core-v3-healthcheck-grpchealthcheck

HTTP Health Checks can be changed to any UserAgent using the `request_headers_to_add` option below.

- https://www.envoyproxy.io/docs/envoy/v1.21.0/api-v3/config/core/v3/health_check.proto.html#config-core-v3-healthcheck-httphealthcheck

Is there any way to change the UserAgent for gRPC HealthCheck?

**Comment by htuch** [comment]
https://github.com/envoyproxy/envoy/pull/20071 does `initial_metadata` work here? CC @wanlill

**Comment by wanlill** [comment]
I think so, we actually have a unit test which exercise this: https://github.com/envoyproxy/envoy/blob/main/test/common/upstream/health_checker_impl_test.cc#L4503
