### ISSUE TITLE
Envoy lua filter httpCall fails for external https request.

### ISSUE THREAD

**Issue by railsonsousa106** [envoyproxy/envoy#20898]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Envoy lua filter httpCall fails for external https request.*

*Description*:
I tried to run external HTTPS call in envoy lua filter as follows.
```
local stream, body = request_handle:httpCall(
                  "outbound|8443||auth.ai.market",
                  {
                    [":method"] = "POST",
                    [":path"] = "/userinfo",
                    [":authority"] = "auth.ai.market",
                    ["Content-Type"] = "application/json",
                    ["Authorization"] = auth_head,
                    ["x-forwarded-proto"] = "https"
                  },
                  nil,
                  5000
                )
```

But I get 400 error from cloudflare.
![image](https://user-images.githubusercontent.com/68667346/164141193-f524089a-73b5-4a8e-b3e5-ac12f635e593.png)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
I believe you need to configure the cluster you're using to do TLS upstrea.
