### ISSUE TITLE
Question: Why traffic_direction is set to OUTBOUND

### ISSUE THREAD

**Issue by Kumassy** [envoyproxy/envoy#20894]
*Title*: *traffic_direction in config.listener.v3.Listener*

*Description*:

I looked at [front-envoy](https://github.com/envoyproxy/envoy/blob/main/examples/front-proxy/front-envoy.yaml) and [jaeger-native-tracing](https://github.com/envoyproxy/envoy/blob/main/examples/jaeger-native-tracing/front-envoy-jaeger.yaml).
Both example uses front-envoy, which handles request from remote user. 

> Front proxy
> https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy

Front envoy must forward request from remote user to envoy mesh by ingress listener. In this listener configuration, `traffic_direction` should be `INBOUND`.

However, some tracing-enabled examples set `traffic_direction: OUTBOUND` 

- https://github.com/envoyproxy/envoy/blob/main/examples/jaeger-native-tracing/front-envoy-jaeger.yaml#L7
- https://github.com/envoyproxy/envoy/blob/main/examples/zipkin-tracing/front-envoy-zipkin.yaml#L7

whereas front envoy example does not set `traffic_direction`, so `traffic_direction: UNSPECIFIED` is used implicitly.

- https://github.com/envoyproxy/envoy/blob/main/examples/front-proxy/front-envoy.yaml
 

Question: What is the correct value for `traffic_direction` for the front envoy? `traffic_direction: OUTBOUND` 
 is correct?

[optional Relevant Links]

- https://www.envoyproxy.io/docs/envoy/latest/intro/life_of_a_request.html explains ingress and egress listener

**Comment by alyssawilk** [comment]
cc @phlax

**Comment by kyessenov** [comment]
Outbound makes sense if you think about the connection to the backend. Gateway must start a trace and half-open a span on the gateway. Inbound makes sense if you expect the incoming connection to have a trace already. In reality, we should really add a GATEWAY traffic direction with the right logic to handle both cases at the same time.

**Comment by Kumassy** [comment]
Thanks for the reply.

Ah, I guess `Outbound` does not mean ingress traffic.

> Outbound makes sense if you think about the connection to the backend. gateway must start a trace and half-open a span on the gateway.

That makes sense when I think about creating span.
