### ISSUE TITLE
How to integrate LDAP with the envoy proxy?

### ISSUE THREAD

**Issue by ayasha05** [envoyproxy/envoy#20920]
We are using envoy with open source redis and wanted to enable the LDAP for envoy, kindly provide some configuration to achieve this.

**Comment by wbpcode** [comment]
cc @weisisea

**Comment by mattklein123** [comment]
Sorry I don't fully understand the request. Can you say more?

**Comment by ayasha05** [comment]
We need to integrate the LDAP(external authorisation service) for envoy, any code base or configuration or documentation which I can follow to achieve this?

**Comment by wbpcode** [comment]
Can this https://github.com/envoyproxy/envoy/blob/main/examples/ext_authz/config/opa-service/v3.yaml helps?

**Comment by ayasha05** [comment]
Do we have any other services apart from opa and gRPC which is suitable with envoy or this two are the only services which we can integrate?

**Comment by mattklein123** [comment]
Envoy doesn't have any built in ldap support if that is what you are asking.

**Comment by g0a019a** [comment]
We are exploring options for any plugin available to integrate ldap to envoy for External Authorization.

**Comment by doujiang24** [comment]
We have implemented a plugin based on envoy Golang filter and go-ldap, it could integrate ldap to envoy for External Authorization.
If anyone are interested in it, feedbacks are welcome!
https://github.com/mosn/envoy-go-ldap-auth
