### ISSUE TITLE
Using OPA external authorization with Kafka network filter

### ISSUE THREAD

**Issue by ruifelixpereira** [envoyproxy/envoy#20936]
*Title*: *Using OPA external authorization with Kafka network filter*

*Description*:
>I am using envoy in a microservices context for 2 scenarios: 1) typical HTTP services using OPA external Authorization; 2) Kafka broker filter with TCP proxy. Now I would like also to use OPA for external authorization with Kafka. It would be great to use the OPA ext_authz network filter in front of the Kafka broker filter. This would allow to have Envoy with OPA in front of all microservices whether they are http/grpc or kafka.

**Comment by giantcroc** [comment]
Hi, I think it's good to support external authorization for kafka in envoy, I can take it.

**Comment by ruifelixpereira** [comment]
@wbpcode is there anything I can help?
