### ISSUE TITLE
listener in-place update can be used for listener filter config update

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#20933]
Inspired by https://github.com/envoyproxy/envoy/issues/20100

Currently update the order of listener filters using the in-place update, since we rebuild the listener filter factory when in-place update.
https://github.com/envoyproxy/envoy/blob/b6bc5ca51227cea3ce00e0302d43ce50031d513e/source/server/listener_impl.cc#L430

That also means we can use in-place update for listener filter config update. But currently, it is fully update.

**Comment by soulxu** [comment]
cc @lambdai

**Comment by wbpcode** [comment]
Yeah, sound right. Because we always rebuild the listener filter factory when we using the in-place listener update. So we can ingore the listener filter config comparing when we decide whether to use the in-place listener update.

**Comment by soulxu** [comment]
According to the discussion https://github.com/envoyproxy/envoy/pull/21059#pullrequestreview-968110370, this doesn't seem to have a strong benefit to taking the risk to improve this. This can be done in the future if people asking this in the production.
