### ISSUE TITLE
Metrics List Request

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#20934]
*Title*: *Metrics List Request*

*Description*:

Now the only way I know to get the metrics list is to deploy Envoy and post requests to the metric endpoint, please tell me if something missing.

When metrics change, a monitor system like Prometheus would raise the error for the missing metrics, which is not conducive to upgrade and maintenance.

I think we can add a doc of metrics list and update it when we release,  which makes metrics obvious and easy to check what/which we need or not. Potentially we will reduce some metrics and improve performance.

**Comment by mattklein123** [comment]
In general this would be really nice, but it's no so easy as metrics can be created dynamically. With that said I would love to figure out a way to auto generate docs for all standard metrics. cc @jmarantz

**Comment by jmarantz** [comment]
A few things to unpack here:
 * defining doc for each stat in the code where we create the stat -- not sure if that's what Matt meant but I think it's easy to add a new stat and not remember to add documentation for it.
 * a more robust way to prune unneeded stats out of the system than what's currently available via the matcher API, as some stats are read in production code, which would misbehave if they were eliminated -- there's a separate bug about this
 * enumerating the "core" stats we expect to be there, thought that's made tricky by some potentially important ones being created on-demand.

**Comment by daixiang0** [comment]
I want to split stats into two kinds: static and dynamic.

For the static one, we list all of them, for the dynamic one, we list all patterns with examples, that would be helpful.

The way to generate docs may be like how API does, or we can update one doc by hand when stats update as the first step, at least cover static stats.

**Comment by zhangbo1882** [comment]
@daixiang0 , what are the dynamic metrics ?

**Comment by daixiang0** [comment]
> @daixiang0 , what are the dynamic metrics ?

Metrics which are generated according to certain rules,
