### ISSUE TITLE
access_log:  upstream tls details

### ISSUE THREAD

**Issue by surki** [envoyproxy/envoy#20939]
*Title*: *adding upstream TLS session details in access log*

*Description*:
I am using "dynamic forward proxy", want to log upstream TLS details (tls version, ciphers, session id etc). I could only find the formatter for downstream connections, not for upstream connections. Before making changes to add those, wanted to check  if its already available in someway/I am overlooking.

**Comment by wbpcode** [comment]
Yeah, there is no specific upstream connnections info in current formatter.

**Comment by surki** [comment]
@wbpcode thanks, will make the changes

**Comment by wbpcode** [comment]
I am not sure if it is easy to get upstream connection info when we try to flush logs. 🤔
