### ISSUE TITLE
Missing tags for envoy-alpine 1.22 on dockerhub

### ISSUE THREAD

**Issue by tabacco** [envoyproxy/envoy#20945]
*Title*: Missing tags for envoy-alpine 1.22 on dockerhub

*Description*:
> It looks like 1.22.0 and 1.22-latest were never tagged on dockerhub for envoy-alpine, even though they were released a while ago.

[optional *Relevant Links*:]
> [Current dockerhub tags](https://hub.docker.com/r/envoyproxy/envoy-alpine/tags)

**Comment by tabacco** [comment]
Hmm it looks like maybe the alpine image was quietly discontinued? Do you not think this is something worth advertising? To my knowledge there was no announced deprecation period, no mention in the changelog, etc.

**Comment by phlax** [comment]
hi @tabacco you are correct that alpine has been discontinued - although it was after a period of deprecation

I agree we could have communicated this better and that dockerhub is probably the best place for this - apologies if this was not clearer

re adding metadata to dockerhub i opened a ticket regarding this some time ago #19784 - but it will take a bit of work to fix this up, esp for the alpine images which we no longer publish, so i havent got around to it so far
