### ISSUE TITLE
admin: consider removing the HTML home page for the admin endpoint or move it to an extension

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#20952]
Based on discussions with @ggreenway and @mattklein123 , most users access admin via curl, and don't have any need for an HTML display.

Currently, admin "/" returns an HTML response, and admin "/help" returns a list of commands as text.

Locally I think the HTML view is useful and could be more so, but we may be a special snowflake. We could go one of several ways here:
 * delete the HTML generation code from the OSS codebase -- we'd just put that in our private repo. In this case, admin "/" could be changed to be the equivalent of "/help", which I believe is how it behaved in the distant past.
 * move the HTML generation code into an extension, which could be excluded at compile-time. In that case, admin "/" would call the extension if enabled, or would return a message indicating that the extension needs to be compiled in.
 * leave the HTML generation code where it is, where "/" returns an HTML menu for all admin commands.

in any case, I think it would be beneficial, at whatever visibility the HTML experience wants to be, to enhance it per https://github.com/envoyproxy/envoy/pull/19546 (html view of stats) and ultimately https://github.com/envoyproxy/envoy/pull/18670 (hierarchical html viewer for stats), and later similar views for /cluster_info, which makes it practical to interactively find your way around 10s of thousands of clusters and the millions of stats they generate.

So I want to use this Issue to poll for people who would use that view, #18670 in particular, once it lands.

**Comment by mattklein123** [comment]
I would vote for option (2), keep it, as an extension. From an onboarding experience I think this is a great thing to have (cc @phlax). There are probably others that use it in prod if you do. :)

**Comment by daixiang0** [comment]
I prefer to keep it since I often use dashboard provided by Istio which needs the HTML feature of Envoy. I think users who use Istio + Envoy have similar behavior.

**Comment by NersesAM** [comment]
As an end-user I'd like to keep it be it via option 3 or option 2 which is enabled by default in release binaries.

**Comment by jmarantz** [comment]
So with option 2....this could be like configured like wasm in that it's a bootstrap option which is compiled into the default binary, but is easy to disable with something like ` bazel --//source/extensions/admin_html/admin_html:enabled=false`

And if that's disabled then admin "/" will return a message indicating that the feature has been compiled out, and /stats?format=html will return a BadRequest (400). Does that sound reasonable?

**Comment by jmarantz** [comment]
Matt -- I'm confused about how the options differ. I thought the main point of moving this into an extension was to be able to reduce code-space overhead for the HTML generation.

I was thinking if that's the goal, we'd parallel the way wasm is compiled in/out of the system, and it can be by default compiled in, but would be easy for envoy-mobile to remove it.

The related question for E-M is whether to remove the entire admin infrastructure if it's never used.

**Comment by mattklein123** [comment]
The difference is that for a pure compile time option people have to explicitly set that option in the build, we have to individually test that option in the compile time options CI, etc. If it's an extension it works like every other extension and people are used to using that functionality to add/remove pieces of the system. It's a minor point but all things being equal I would probably do a bootstrap extension. I don't feel strongly about it though.

**Comment by jmarantz** [comment]
Sorry I'm still missing some subtle point :)

I think wasm is both a bootstrap extension and an enabled-by-default compile-time option. You are right that it'd be necessary to add a test for behavior when it's disabled in compile-time-options; that makes sense.

Is there an official guide to how-to-write-a-bootstrap-extension? Doing this the easiest way possible SGTM especially as I'm not sure there's a material amount of code savings -- mostly a few 1k-ish static strings for the HTML, CSS, and (eventually) JS in C++ static string constants.

**Comment by mattklein123** [comment]
I'm honestly not sure why WASM is a compile time option, it probably shouldn't be at this point, given that bazel should pull it in to whatever extensions use it. cc @PiotrSikora 

If we look at https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_build_config.bzl, there are several bootstrap extensions, and they are generally in the category of things that need to load early on, of which this type of admin extension would be.

Again I really don't have a super strong opinion about it, but that's the way I would do it.

**Comment by jmarantz** [comment]
Sorry what I meant by "compile-time" is that whether it gets pulled in depending on the bazel command line. When I build envoy-static with wasm (default) with -c opt, I get 374M binary without wasm, and 511M binary with wasm.

**Comment by mattklein123** [comment]
Right what I'm saying is I don't understand why WASM needs a different compile time option. It seems to be it should just get included in or out based on your extension config. But that's a different issue.

**Comment by PiotrSikora** [comment]
> I'm honestly not sure why WASM is a compile time option, it probably shouldn't be at this point, given that bazel should pull it in to whatever extensions use it. cc @PiotrSikora

@lizan migrated them to `envoy.wasm.runtime.*` extensions (see: #12574, #14014 and #14062), but it looks that the migration was never finished.

Also, I imagine that it's much easier for "normal" users to provide build flags than to modify [`source/extensions/extensions_build_config.bzl`](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_build_config.bzl) as part of the build process.

**Comment by jmarantz** [comment]
Yeah for WASM it's really nice to not have to have the weight of compiling and linking v8 when iterating on envoy-static development that does not involve wasm., and it's nice to be able to do that via command-line. AFAICT this is working fine for me now -- I can build (relatively) small envoy-static.

Matt I had assumed what you wanted for admin-html was not to have the weight of all the html/css/js generation code in the Envoy binary when you don't need it. What are the other benefits of eliding those from the build?

Super-naive question: is there a "how to write an extension" doc somewhere going into all this?

**Comment by mattklein123** [comment]
IIRC all of the extensions can now be enabled/disabled on the CLI also (cc @lizan) but I don't remember the details. In any case it's not a big deal. Whatever you all think is best is fine with me (extension or CLI switch only).

> Matt I had assumed what you wanted for admin-html was not to have the weight of all the html/css/js generation code in the Envoy binary when you don't need it. What are the other benefits of eliding those from the build?

Yeah just code size and potentially security footprint for people that don't need that code.

> Super-naive question: is there a "how to write an extension" doc somewhere going into all this?

Unfortunately there is not, though there are plenty of existing examples. The best thing we have is this: https://github.com/envoyproxy/envoy/blob/main/api/STYLE.md#adding-an-extension-configuration-to-the-api

**Comment by lizan** [comment]
Yes all extensions can be enabled/disabled by CLI (by `--<extension_path>:enabled=true|false`)

+1 to option 2 and leave it defaults on.

**Comment by jmarantz** [comment]
This was resolved in https://github.com/envoyproxy/envoy/pull/21814
