### ISSUE TITLE
Provide prebuilt static binaries for convenience

### ISSUE THREAD

**Issue by kragniz** [envoyproxy/envoy#2095]
It would be nice, as mentioned in slack, to provide pre-built binaries. They don't have to be 100% portable, just work on recent versions of common distros.

These could be built in CI, then automatically uploaded to github releases for distribution.

**Comment by taion809** [comment]
@mattklein123 can you assign this to me?  I'm already doing a lot of this during my work day.

**Comment by mattklein123** [comment]
@taion809 what's your plan? Just take the binary that we build and put in the docker image and just put it somewhere directly?

**Comment by taion809** [comment]
@mattklein123 the plan (at least how i have done it in the past and would like to do here) is use the release workflow to build the osx / linux binaries and add them to the release tag on github

**Comment by mpuncel** [comment]
Is this being worked on right now? I was just looking into playing around with envoy and a prebuilt binary would make life much easier!

**Comment by alyssawilk** [comment]
I don't see it assigned, and it's still flagged help wanted, so I don't think anyone has picked it up as of yet.  

Do check out the instructions for docker builds - I think for the most part Envoy is pretty easy to get up and running in a container at least and there's lots of helpful folk on slack if you run into any problems.

**Comment by taion809** [comment]
@mpuncel i'm still looking into this but i've gotten a bit behind due to work, I'll try to get something ready this week

**Comment by taion809** [comment]
@bndw that's the plan right now, i'm actually working on this right now see: https://circleci.com/gh/taion809/envoy-build-tests
