### ISSUE TITLE
Failure in replacing listener on the same address with a different listener name.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#2096]
**Bug Template**

*Title*: Replacing listener on the same address with a different listener name fails.

*Description*:
Suppose there is a listener with the name "A" on address 0.0.0.0:443. LDS sends a new list of listeners, where the listener "A" is replaced by a new listener with the name "B" on address 0.0.0.0:443. Envoy's listener_manager fails to replace the listener "A" by the listener "B" - the expected behavior is to remove the listener "A" and to add listener "B".

The problem is seen in the listener_manager code:
https://github.com/envoyproxy/envoy/blob/cbff0f7fc56c53e3aac383081021856c8dbcb732/source/server/listener_manager_impl.cc#L185

```
auto existing_active_listener = getListenerByName(active_listeners_, name);
auto existing_warming_listener = getListenerByName(warming_listeners_, name);
```

The existing active listeners are checked by name, since "B" is a new listener, it is found neither in active_listeners_ nor in warming_listeners_.

Then, the following code checks if there is an active listener on address 0.0.0.0:443, and finds collision with listener "A" which is not yet removed at this point. 
https://github.com/envoyproxy/envoy/blob/cbff0f7fc56c53e3aac383081021856c8dbcb732/source/server/listener_manager_impl.cc#L241

```
    if (!new_listener->bindToPort() &&
        (hasListenerWithAddress(warming_listeners_, *new_listener->address()) ||
         hasListenerWithAddress(active_listeners_, *new_listener->address()))) {
      const std::string message =
          fmt::format("error adding listener: '{}' has duplicate address '{}' as existing listener",
                      name, new_listener->address()->asString());
      ENVOY_LOG(warn, "{}", message);
      throw EnvoyException(message);
    }
```

The problem stems from the fact that the new listeners are added first, and only then the listeners meant to be removed are removed. Adding listeners with different names from the listeners meant to be removed, can cause a collision on the same address:

https://github.com/envoyproxy/envoy/blob/923fe316d1cabfe15aa757017268271beb42e7d9/source/server/lds_api.cc#L42
```
  for (const auto& listener : listener_manager_.listeners()) {
    listeners_to_remove.emplace(listener.get().name(), listener);
  }

  for (const auto& listener : resources) {
    const std::string listener_name = listener.name();
    listeners_to_remove.erase(listener_name);
    if (listener_manager_.addOrUpdateListener(listener)) {
      ENVOY_LOG(info, "lds: add/update listener '{}'", listener_name);
    } else {
      ENVOY_LOG(debug, "lds: add/update listener '{}' skipped", listener_name);
    }
  }

  for (const auto& listener : listeners_to_remove) {
    if (listener_manager_.removeListener(listener.first)) {
      ENVOY_LOG(info, "lds: remove listener '{}'", listener.first);
    }
  }
```

**Comment by mattklein123** [comment]
I did this for a reason, but I will need to research what that reason was. :) I will get back to you.

**Comment by mattklein123** [comment]
@vadimeisenbergibm yeah I think we could do remove before add in lds_api.cc to fix this issue. Marking bug/help wanted.

**Comment by mbanikazemi** [comment]
I am guessing the reason for not removing all listeners first before adding the ones from the new configuration is optimization for the more common cases where a large number of listeners remain during updates. In that spirit, I will shortly submit a PR that avoids doing that but solves the problem. (If removing all first and then adding new one is not a concern I can change the PR to simply do that.)
