### ISSUE TITLE
tracing: rename `upstream_cluster.name` tag name

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#20964]
Now, `upstream_cluster` is used as tag name for the cluster name and `upstream_cluster.name` is used as tag name for the cluster `alt_stat_name`.

However, for the Json format tracing message, the `upstream_cluster.name` may be treated as a Json object with a `name` field wichin some parsing/message systems (For example, ES). And this will conflict wich the normal `upstream_cluster` tag.

In my opinion, we should avoid tag names like `a` and `a.b` to be present at same time. It would be better just `a`/`a_b` or `a.b`/`a.c`.

**Comment by ankatare** [comment]
@wbpcode would like to understand more on it ... would you please mind to give some example ..

**Comment by wbpcode** [comment]
I send my Json format tracing messages to ES. It just like something as follow.
```
{
  "name": "aaaaa",
  "tags": {
    "upstream_cluster": "cluster_name",
    "upstream_cluster.name": "cluster_stat_name"  
   }
}
```
Looks like that the ES parser treat `"upstream_cluster.name": "cluster_stat_name"` a object like `"upstream_cluster": { "name": "cluster_stat_name"}` and try to merge it with `"upstream_cluster": "cluster_name"`. Then an exception will be throwed because the incompatible types.

Here is a related discussion: https://discuss.elastic.co/t/how-to-handle-dot-in-field-names-in-es-7-0/176511

Although I think it's problem of ES, it would be great if we can work around it.

**Comment by ankatare** [comment]
@wbpcode Thanks.. let me check this.

**Comment by ankatare** [comment]
@wbpcode can we connect today on slack ? thanks

**Comment by wbpcode** [comment]
> @wbpcode can we connect today on slack ? thanks

Sorry for the late reply. You can send messages to me on slack anytime.
