### ISSUE TITLE
Envoy Dockerimage is show dev build for 1.20.2 image. 

### ISSUE THREAD

**Issue by pavansh** [envoyproxy/envoy#20967]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *using docker image 1.20.2 it is showing envoy version with -dev. *

*Description*:
docker run -it envoyproxy/envoy:v1.20.2 sh
$ envoy --version

envoy  version: 4aaf9593152c6996b9da384c8918e9ad4f0abd4d/1.20.**2-dev**/Clean/RELEASE/BoringSSL

Is it ok or I am missing something ? 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
hi @pavansh this is a known issue and should be resolved by #20824

**Comment by phlax** [comment]
fixed by https://hub.docker.com/layers/envoy/envoyproxy/envoy/v1.20.3/images/sha256-9bcf8720bf8c13effccc30bdfba71b404ffeb599cbf1f26e6a2418694d39091e?context=explore
