### ISSUE TITLE
envoy_reloadable_features_http_strip_fragment_from_path_unsafe_if_disabled deprecation

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#20986]
Your change commit 90f16e3f38a0e41ea8f23b585e41c18721dcb203 (Reject or strip fragment from request URI) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by yanavlasov** [comment]
I will need to check as this feature may be used internally, and figure out what to do here.

**Comment by yanavlasov** [comment]
Fixed in #27847
