### ISSUE TITLE
replace envoy_reloadable_features_sanitize_http_header_referer with config knob

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#20989]
Your change #17443 (conn_manager: sanitize invalid urls in HTTP header's referer field) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
cc @RenjieTang please off on removing this one - I got a report on slack that this broke things for someone who is getting invalid referer headers.  I think we may have to add a permanet knob as part of UHV.
cc @yanavlasov

**Comment by jtway** [comment]
Thank you @alyssawilk!

**Comment by jtway** [comment]
Looks like the run time guard was removed prior to this issue getting worked.
