### ISSUE TITLE
Switch to simulated time system in integration tests

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#20996]
HttpIntegrationTest would benefit from switching to using SimulatedTimeSystem to avoid flakiness caused by unpredictable delay of timers in real time. Per-discussion in https://github.com/envoyproxy/envoy/pull/20931#pullrequestreview-950002388, we should use simulated time whenever possible in new integration tests and possibly making the switch in the existing ones  as well.

**Comment by zhxie** [comment]
I think this is a duplicate of #4160.
