### ISSUE TITLE
Feature Request: broadcast messages to all Envoy instances

### ISSUE THREAD

**Issue by gingerich** [envoyproxy/envoy#2099]
# Message Broadcast

*Description*:
Services can broadcast messages into the mesh. All Envoy instances are aware of the broadcast. A service can "subscribe" to the messages it cares about through its Envoy instance.

*Motivation*:
One of the common patterns emerging in microservice architecture is abstracting service-to-service communication using messages and pattern matching. Messages provide a uniform, transport-independent communication layer. The idea being, services can emit messages into the mesh without knowing which service(s) will handle it. Services specify which messages they care about using patterns (think JSON property matching). This is another layer of abstraction that further decouples services. The end goal is that services need not know of the existence of any other service, they just know how to talk to the mesh.

*Disclaimer*:
I'm very much a microservice newbie, learning as I go. Envoy caught my eye as a leap forward for microservice architecture, but I noticed it doesn't incorporate the messages and pattern matching abstraction. Maybe this was a conscious choice? Maybe it isn't feasible with the current architecture? Maybe there's a better way? Maybe it belongs in a different layer of the mesh?

Inspiration: [SenecaJS](https://github.com/senecajs/seneca)

**Comment by mattklein123** [comment]
@gingerich at a very high level this sounds a lot more like something Kafka, Kinesis, etc. would provide vs. Envoy. Can you describe in more detail exactly what Envoy would do here? I'm sure I fully understand the feature request. Thank you.

**Comment by mattklein123** [comment]
Going to close this for now. Please let us know if we can map this to a more concrete feature request.
