### ISSUE TITLE
docs: remove v1 API anchors

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2100]
Post 1.5.0 release, we should remove all of the anchors inside the v1 specific doc tree, such that all arch, etc. docs will need to link into v2. This will be a forcing function to start the migration from v1 to v2. I don't think we should do this for the 1.5.0 release.

cc @htuch

**Comment by taion809** [comment]
I have some bandwidth to go through the docs sometime this week

**Comment by mattklein123** [comment]
@taion809 OK, thanks. This is going to be super tedious, so be warned. My intention was basically to go through https://github.com/envoyproxy/data-plane-api/tree/master/docs/root/api-v1 and delete all anchor targets in that tree, and then clean out all refs that refer to it (and optimally replace relevant ones with v2 references). Obviously feel free to do this in pieces and we can track what has been done here. Thank you!!!

**Comment by taion809** [comment]
Tedious? Toil? Sir.. I work in DevOps.

**Comment by mattklein123** [comment]
> Tedious? Toil? Sir.. I work in DevOps.

🤣

**Comment by taion809** [comment]
just an update:  i was on call @ work last week so I didn't get a chance to look into this.  I'll be waiting until the docs move from data-plane-api to here before submitting a PR.

**Comment by taiki45** [comment]
FYI, I'm working on this. I'm replacing links to v2 ones in all arch overview, configuration, etc. docs. I think 70 % of work was done today.

**Comment by taion809** [comment]
@taiki45 thanks, i ended up getting too busy to get through a bunch of this

**Comment by mattklein123** [comment]
@taiki45 is this done or is there more to do? Thank you for your effort here!

**Comment by taiki45** [comment]
I was thinking that too. What I'm not getting the meaning is the "anchors" because I'm not familiar reStructuredText yet. Is that something like this?: `.. _config_cluster_manager_v1:`

We've already removed possible v1 links from current docs (except from v1 docs tree), but we didn't remove all of anchors from v1 doc tree. Probably we should remove all of anchors from v1 docs tree when we remove v1 docs. If so, we can say this issue has been fixed.

**Comment by mattklein123** [comment]
> We've already removed possible v1 links from current docs (except from v1 docs tree), but we didn't remove all of anchors from v1 doc tree. Probably we should remove all of anchors from v1 docs tree when we remove v1 docs. If so, we can say this issue has been fixed.

Yeah originally I was thinking we would remove all the anchors from the v1 tree just to avoid things we missed, but it's not a big deal. If you already went through and removed all of what you saw, I think that's great and we can track any stragglers later. If you agree we can close this as done?

**Comment by taiki45** [comment]
>Yeah originally I was thinking we would remove all the anchors from the v1 tree just to avoid things we missed, but it's not a big deal.

I see, now I understand that.

> If you already went through and removed all of what you saw, I think that's great and we can track any stragglers later.

Yes, I checked with grep-ing v1 links in generated docs tree and I think all of possible ones were replaced. So I agree we can close this as done.

If anyone find more jobs to do about this, of-course please report that.

**Comment by mattklein123** [comment]
Cool, closing. Thank you!!!
