### ISSUE TITLE
KeepAliveTimeeTriggersFloodProtection flaky on coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#21019]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/106879/logs/292

**Comment by alyssawilk** [comment]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/107028/logs/265

**Comment by yanavlasov** [comment]
Sounds good. I will be working on it tomorrow.
