### ISSUE TITLE
Feature Request: Support for inverse route header matching

### ISSUE THREAD

**Issue by brirams** [envoyproxy/envoy#2101]
I'd like to be able to construct an `rds.Route` that will be matched if a header is _not_ a certain value or if it's not present at all. Currently, one could do the former with a negative lookahead regex but doing so means that the header must at least be present in order for the route to be matched. Ideally, envoy would have first class support for inverse matching that would follow these semantics:

For $header_a, match if:
- $header_a != $desired_value
OR
- $header_a is not present in request headers

Context: https://envoyproxy.slack.com/archives/C78M4KW76/p1511652507000035

**Comment by srikailash** [comment]
Hello @brirams , i am interested to work on this issue . After a  bit of digging into code i found that RouteConfigProviderManagerImpl::handlerRoutes in source/common/router/rds_impl.cc can be modified to validate headers . Please provide more context(i couldn't access slack link) , Thanks .

**Comment by gumpt** [comment]
If this isn't being worked on by anyone else, and the feature is still desired, I'd be interested in working on it.

**Comment by mattklein123** [comment]
@gumpt have at it!
