### ISSUE TITLE
thrift tests flaking on windows

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#21017]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_apis/build/builds/106885/logs/97

[       OK ] TransportAndProtocol/ThriftConnManagerIntegrationTest.IDLException/FramedBinaryMultiplexed (1255 ms)
[ RUN      ] TransportAndProtocol/ThriftConnManagerIntegrationTest.IDLException/FramedCompactMultiplexed
Failed bash -c "PYTHONPATH=$(dirname C:/botcode/w129/bazel-out/x64_windows-opt/bin/test/extensions/filters/network/thrift_proxy/integration_test.exe.runfiles/envoy/test/extensions/filters/network/thrift_proxy/driver/generate_fixture.sh) C:/botcode/w129/bazel-out/x64_windows-opt/bin/test/extensions/filters/network/thrift_proxy/integration_test.exe.runfiles/envoy/test/extensions/filters/network/thrift_proxy/driver/generate_fixture.sh idl-exception framed compact -s svcname -T C:/botcode/w129/_tmp/1d56d98246b8435015e6c7618ec3c66f execute "
[2022-04-25 19:57:23.462][4648][critical][assert] [test/test_common/environment.cc:406] assert failure: false.

**Comment by JuniorHsu** [comment]
weird indentation here but should not fail the command?
https://github.com/envoyproxy/envoy/blob/main/test%2Fextensions%2Ffilters%2Fnetwork%2Fthrift_proxy%2Fdriver%2Fgenerate_fixture.sh#L73

**Comment by alyssawilk** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=114123&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53

[       OK ] TransportAndProtocol/ThriftConnManagerIntegrationTest.OnewayEarlyClose/HeaderCompactMultiplexedPassthrough (6952 ms)
[ RUN      ] TransportAndProtocol/ThriftConnManagerIntegrationTest.OnewayEarlyClosePartialRequest/UnframedBinaryMultiplexedPassthrough
================================================================================
[14,708 / 14,717] 925 / 927 tests, 1 failed; Testing //test/integration:overload_integration_test [167s (4 actions)] ... (9 actions running)


@JuniorHsu any chance you could add some debug info so if it flakes again we have some breadcrumbs?
