### ISSUE TITLE
Should we support TCP Keep-Alives on listener side?

### ISSUE THREAD

**Issue by rainingmaster** [envoyproxy/envoy#21042]
*Title*: *Should we support TCP Keep-Alives on listener side?*

*Description*:
So far we only support [TCP Keep-Alives](https://www.freesoft.org/CIE/RFC/1122/114.htm) on [cluster side](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/upstream_impl.cc#L80), but as the RFC said:
> A TCP keep-alive mechanism should only be invoked in server applications that might otherwise hang indefinitely and consume resources unnecessarily if a client crashes or aborts a connection during a network failure.

If we have TCP Keep-Alives on listener side, it will protect our server to hang to many idle connection when client has crash.

**Comment by mattklein123** [comment]
This is supported today via generic socket options that can be set on the listener socket. Though I can't remember if we have a specific option for it like we do on the cluster side.

**Comment by rainingmaster** [comment]
> This is supported today via generic socket options that can be set on the listener socket. Though I can't remember if we have a specific option for it like we do on the cluster side.

Cluster side should be supported since this PR: https://github.com/envoyproxy/envoy/pull/3042/files#diff-cc3502882065c5e035482a2bccd3a7e43ba62017ad01e4ebb7acb2e15fd31075R445. And the configuration is [tcp_keepalive in UpstreamConnectionOptions](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/cluster/v3/cluster.proto#L1184).

Could you point out which commit id via generic socket options that can be set on the listener socket, sorry that I didn't found it... Thanks!

**Comment by mattklein123** [comment]
See `socket_options` here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto

**Comment by rainingmaster** [comment]
> See `socket_options` here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto

I see, the generic socket option should be cover all options now...

By the way, since we have `upstream_bind_config` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster, `tcp_keepalive ` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-upstreamconnectionoptions should be abandon or user will be confuse of it just like me?

**Comment by mattklein123** [comment]
I don't think it's worth deprecating. Maybe do a doc PR?

**Comment by rainingmaster** [comment]
Close with https://github.com/envoyproxy/envoy/pull/21063
