### ISSUE TITLE
Least specific header mutation wins by default.

### ISSUE THREAD

**Issue by AdiJohn** [envoyproxy/envoy#21057]
There is toggle in route.proto to toggle whether the most specific header (at route level) wins or the least specific header (at connection manager level) mutation wins.https://github.com/envoyproxy/envoy/blob/217f7ff9df5e056ad3dc3e398e158b5b13ede93f/api/envoy/config/route/v3/route.proto#L94

The API documentation states the default value will be true for V3 API but actually it is not.

**Comment by wbpcode** [comment]
Looks like this is a docs error. Should we just update the docs or we need change the bool to BoolValue to change the default value?

cc @phlax @mattklein123

**Comment by AdiJohn** [comment]
Fixed
