### ISSUE TITLE
Build failed when building envoy 1.22.0 with gcc and libstdc++ in opt mode 

### ISSUE THREAD

**Issue by hxysayhi** [envoyproxy/envoy#21060]
*Title*: *Build failed when building envoy 1.22.0 with gcc and libstdc++ in opt mode*

*Description*:
> envoy version: 1.22.0
git tag: v1.22.0
build in docker,  docker image: envoyproxy/envoy-build-ubuntu:142e6d5662b98277a84c327da26ed266ab0e3191-amd64
build command: bazel --bazelrc=/dev/null build -c opt envoy

Error:
```
ERROR: /workspaces/envoy/source/common/config/BUILD:414:17: Compiling source/common/config/watch_map.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 154 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
source/common/config/watch_map.cc: In member function 'virtual void Envoy::Config::WatchMap::onConfigUpdate(const google::protobuf::RepeatedPtrField<envoy::service::discovery::v3::Resource>&, const google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char> >&, const string&)':
source/common/config/watch_map.cc:215:69: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  215 |       type_url_, reinterpret_cast<std::vector<DecodedResourcePtr>&>(decoded_resources),
      |                                                                     ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors 

```

I followed [this release build suggestion](https://github.com/envoyproxy/envoy/blob/release/v1.22/bazel/README.md#release-builds) in the [README](https://github.com/envoyproxy/envoy/blob/release/v1.22/bazel/README.md#building-envoy-with-bazel)
>Release builds should be built in opt mode, processed with strip and have a .note.gnu.build-id section with the Git SHA1 at which the build took place. They should also ignore any local .bazelrc for reproducibility.

According to [config-flag-choices](https://github.com/envoyproxy/envoy/blob/release/v1.22/bazel/README.md#config-flag-choices)
```
Different [config](https://docs.bazel.build/versions/master/guide.html#--config) flags specify the compiler libraries:

--config=libc++ means using clang + libc++
--config=clang means using clang + libstdc++
no config flag means using gcc + libstdc++
```
When I execute `bazel --bazelrc=/dev/null build -c opt envoy`, GCC will be used.

When I execute `bazel build -c opt envoy`, clang will be used to compile envoy, and everything is going well.

There are some reference about strict-aliasing
- [StackOverflow: fix-for-dereferencing-type-punned-pointer-will-break-strict-aliasing](https://stackoverflow.com/questions/8824622/fix-for-dereferencing-type-punned-pointer-will-break-strict-aliasing/8825257#8825257)
- [What is the Strict Aliasing Rule and Why do we care?](https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8)

By the way, `bazel --bazelrc=/dev/null build -c opt envoy.stripped` will failed because there is no alias of `envoy.stripped` in the BUILD file.

**Comment by mattklein123** [comment]
cc @keith

**Comment by keith** [comment]
Here's a fix for the `envoy.stripped` issue https://github.com/envoyproxy/envoy/pull/21097

**Comment by keith** [comment]
> When I execute bazel --bazelrc=/dev/null build -c opt envoy, GCC will be used.

The project's `.bazelrc` is still loaded successfully when you pass this flag, which you can see by passing `--announce_rc` and see that _some_ options are still being passed. How is the presence of `--bazelrc=/dev/null` affecting clang vs GCC for you? Does your `~/.bazelrc` have a `build --config=clang` line you're expecting to be picked up? If not can you include the difference in flags you see with `--announce_rc` with and without `--bazelrc=/dev/null`? AFAIUI the intent of that flag is just to ignore any non-hermetic global bazelrc files, so IMO ideally it shouldn't affect any normal build behavior.

**Comment by keith** [comment]
As far as the original GCC compiler error here, to unblock you can consider passing `--copt=-fno-strict-aliasing` although I can't say I fully understand the implications of that. It only happens with `-c opt` because gcc flips it on by default in that case, and we never pass it manually. Also clang's implementation of `-fstrict-aliasing` doesn't error on this same case, so I'm not sure what to think about that, we're out of my C++ depth.

There is actually another instance, both introduced in https://github.com/envoyproxy/envoy/commit/e58c890ded5c13e60eba3285c96ffefd6f7215cf#diff-3d9b7f541cceecbc0ee4f3ff9972955b13408dd67823e05a1be1a6ed8b6ab064R251 so hopefully @adisuissa can chime in and come up with a recommendation

**Comment by keith** [comment]
I imagine we could be quicker to catch instances of this, even if it's gcc only, by enabling that flag for more builds, although I'm not sure what the build performance impact would be

**Comment by adisuissa** [comment]
Thanks for cc'ing me on this @keith.
Unfortunately I only use clang, but I was able to repro the error using docker.
I'll work on a fix for this tomorrow.
