### ISSUE TITLE
Priority order of Compressors (Brotli, Gzip)

### ISSUE THREAD

**Issue by barnhill** [envoyproxy/envoy#21068]
*Title*: *Priority order of Compressors (Brotli, Gzip)*

*Description*:
When configuring envoy we would like to have Brotli prioritized over Gzip if its in the Accept-Encoding header in any order.  Is there a way to prioritize Brotli even if the header comes through with the order `gzip,br`.  Currently it will see that gzip is supported and it will just use it.  This comes into play with iOS devices as from apple their default value for this header is `gzip,deflate,br` and it will never use Brotli due to this ordering.  Any help would be appreciated.

**Comment by KBaichoo** [comment]
Not yet an expert in this area, from https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/compressor_filter#config-http-filters-compressor the compression filter knows the other compression libraries available in the filter chain. 

Moreover, it seems like the filter works with quality values, so I __think__ if you added a simple filter than replaces the accept-encoding on the request side with quality value weighting, priority of compression should be applied e.g. with `br quality value > gzip quality value`

**Comment by barnhill** [comment]
But if you request it with "gzip,deflate,br" as in the case of the default on iOS ... it will never use Brotli as it uses the first one in the list that it supports.  Maybe there is a way to do this with composite filters?

**Comment by KBaichoo** [comment]
A cleaner way to achieve this is adding additional tie breaking logic to the filter. It would probably be added here as well as the proto: https://github.com/envoyproxy/envoy/blob/5afc6faf0b2986581f8e7d88b46b3dbf1881f57c/source/extensions/filters/http/compressor/compressor_filter.cc#L390-L398

For us to override the choice even if the quality values are equal if we prefer one compressor over the other.

**Comment by barnhill** [comment]
Any ideas on moving this forward?

**Comment by KBaichoo** [comment]
Hi, @barnhill I don't have bandwidth to work on this, but hopefully the pointers above should be enough for someone who wants this to implement it. Happy to review any such implementations.

**Comment by barnhill** [comment]
It would be nice to label this as help wanted

**Comment by giantcroc** [comment]
@barnhill Hi, I can help with it.

**Comment by KBaichoo** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/23005
