### ISSUE TITLE
Documentation: More emphasis on how to get v2 configuration API

### ISSUE THREAD

**Issue by NickMRamirez** [envoyproxy/envoy#2107]
The documentation about configuring Envoy (https://www.envoyproxy.io/docs/envoy/latest/configuration/configuration) makes it seem like the v2 API is included with this repository. Looking at it more closely now, it does say that it's included in the Data Plane API repository, but maybe that could be called out more? 

Otherwise, the casual reader assumes the v2 API is included in this repository and when they build the latest release version of the code:

```
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
```

...the `envoy` binary does not know how to handle the v2 schema. Also, the `--v2-config-only` command-line flag is not recognized.

The configuration errors I was getting weren't making any sense until I realized that they were validating against the v1 API. Some more explicit callouts to how to build the v2 API (such as, needing to go to the https://github.com/envoyproxy/data-plane-api/tree/master/ci repository instead) might help newcomers.

**Comment by mattklein123** [comment]
@NickMRamirez that option has not merged yet: https://github.com/envoyproxy/envoy/pull/2105. With the docs now split between two repos things may be slightly not aligned as we do development. When we snap a release the docs will be snapped also.

**Comment by NickMRamirez** [comment]
I also might be totally wrong about the v2 API being available in the data plane API. I tried that one just now and got:

```
Invalid do_ci.sh target. The only valid targets are bazel.{docs,test}.

```

**Comment by mattklein123** [comment]
Closing this out for now as we have completed the first major pass on v2 docs. Please check it out and let us know what is missing.
