### ISSUE TITLE
how much time consumed for a request/response in envoy

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#21084]
Does envoy has any logs/metrics to show how much time is consumed in envoy handling exclude the time consumed in network transmit?
For example, client send packet at time1, envoy receives the packet at time2, then send packet to upstream server at time3, get the response at time4, send response to client at time5.

Does envoy log the time2-4? It seems that envoy only have the duration(time5 - time2).

**Comment by wbpcode** [comment]
May be this can helps.
```
%RESPONSE_DURATION%
HTTP
Total duration in milliseconds of the request from the start time to the first byte read from the upstream host.
```

Check this for more duration log command: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by zhangbo1882** [comment]
@wbpcode , 
I think RESPONSE_DURATION = time4(receive response from upstream)-time2(receive request from downstream client).
What I need is time3(send request to upstream) - time2(receive request from downstream client). This time duration can tell us how long envoy handle the request. It is very useful to isolate the latency issue in production environment.

For example, client complains that it wait for a long time to get response. 
We need tell client that which component consume the time. From current envoy access log, we cannot know whether the time is consumed by envoy or intermediate network or  upstream server.  If envoy have the time3-time2 and time5-time4, we can get the answer.

**Comment by wbpcode** [comment]
May `%REQUEST_TX_DURATION%` works?

```
%REQUEST_TX_DURATION%
Total duration in milliseconds of the request from the first byte read from the upstream host to the last byte sent downstream.
```

May be the `time_to_first_upstream_tx_byte` is better. But it not supported by the normal file log.

**Comment by zhangbo1882** [comment]
From official doc https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage, it show that 
%REQUEST_TX_DURATION%
HTTP
Total duration in milliseconds of the request from the start time to the last byte sent upstream.
From my understanding, it is only for the duration to send traffic to upstream. This is not what I need.

**Comment by wbpcode** [comment]
> From official doc https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage, it show that %REQUEST_TX_DURATION% HTTP Total duration in milliseconds of the request from the start time to the last byte sent upstream. From my understanding, it is only for the duration to send traffic to upstream. This is not what I need.

> Total duration in milliseconds of the request from the start time to the last byte sent upstream.

FWIW, the start time in the docs means `receive request from downstream client`.

**Comment by akashjain971** [comment]
@zhangbo1882 maybe this will help you.
https://github.com/envoyproxy/envoy/issues/18959#issuecomment-1006558978
