### ISSUE TITLE
Questions on Envoy Proxy

### ISSUE THREAD

**Issue by sirishacse06** [envoyproxy/envoy#2109]
Hi,
I am new to Envoy Proxy, please help in answering below questions.
1)Is there a documentation on Envoy observability that displays various graphs to show the performance of the application.If so please share the links 
2)Is dashboard a different program other than envoy and is it to be installed separately to display the envoy histograms?
3)Where are the logs stored?
4)Does envoy can go alongside MongoDB and DynamoDB only? or can it support any other Databases also?

Thanks,
Sirisha

**Comment by zuercher** [comment]
Matt Klein wrote a [blog post](https://medium.com/@mattklein123/lyfts-envoy-dashboards-5c91738816b1) related to stats dashboards a while back, you might find it useful.

There is no specific dashboard program for Envoy. Stats may be forwarded to a statsd-style collector and there are a number of ways that data can be stored and displayed. There were recent changes to support Prometheus stats scraping, which will eventually support histogram data.

By default, Envoy's internal logging is sent to the console. It can be configured to write to a file via the command line.

Access logs can be configured in the [HTTP connection manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/http_conn_man) and [TCP Proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/network_filters/tcp_proxy_filter) among other filters. Part of the configuration is where to write the files. In the future, these logs will be streamable via GRPC.

Envoy's mongodb and dynamodb filters provide enhanced statistics gathering for those databases. Envoy can proxy other databases (at either the HTTP or TCP level), but database-specific stats require someone to write a protocol-aware filter.

**Comment by sirishacse06** [comment]
Thank you for your response!
Is there is a management UI for writing the scripts, if not are they written and executed at shell of Linux and if in Windows is it at cmd?

**Comment by zuercher** [comment]
I'm not sure which scripts you're asking about.

**Comment by sirishacse06** [comment]
Like Configuration scripts. Sample script from https://www.envoyproxy.io/docs/envoy/latest/install/ref_configs
**Snippet:-**
build/source/exe/envoy -c configs/google_com_proxy.json -l debug
curl -v localhost:10000

Another one:- mkdir -p generated/configs
bazel build //configs:example_configs
tar xvf $PWD/bazel-genfiles/configs/example_configs.tar -C generated/configs

**Comment by zuercher** [comment]
There is no Envoy-provided UI for generating those scripts. There is an example config generator written in Python: https://github.com/envoyproxy/envoy/blob/master/configs/configgen.py (which is used to generate the configs during `bazel build //configs:example_configs`.

**Comment by sirishacse06** [comment]
Okay. Can we install and run Envoy Proxy in Windows OS?

**Comment by zuercher** [comment]
See envoyproxy/envoy#129

**Comment by moderation** [comment]
@sirishacse06 the Microsoft Envoy fork is at https://github.com/microsoft/envoy but doesn't look like it is being worked on.

**Comment by sirishacse06** [comment]
@zuercher @moderation Thank you for sharing the information.

**Comment by mattklein123** [comment]
Closing for now. Please let us know if you have further questions.
