### ISSUE TITLE
Is it possible to instruct envoy transcoder to return the errors triggered at its level as a JSON and not as a plain string ?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#21090]
Hi,

Is it possible to instruct envoy transcoder to return the errors triggered at its level in the following JSON format, and not just as a plain string message? 
Current response:
`project.isDone: invalid value false for type type.googleapis.com/test.api.YesNo`

What I would like to get is a JSON like this:
`{
  "code": 3,
  "message": "project.isDone: invalid value false for type type.googleapis.com/test.api.YesNo",
  "details": []
}`

The reason why I want this is because I want to have a standard error message structure across my transcoded endpoints. 

Thanks!

FYI I'm triggering this error by passing a Boolean value in a filed that expects an enum value.

**Comment by alyssawilk** [comment]
cc @qiwzhang @lizan

**Comment by ghevge** [comment]
Any feedback on this one ? Thanks!

**Comment by lizan** [comment]
@ghevge you may do this with existing local reply mapper: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply

**Comment by ghevge** [comment]
@lizan  Thank you! I will give it a try.
