### ISSUE TITLE
Is there a straightforward way to build the proto files for csharp (or any other particular language)?

### ISSUE THREAD

**Issue by buehler** [envoyproxy/envoy#21104]
Dear envoy team

I'm currently trying to build the `*.proto` files in the API folder to be used to create configs for the envoy proxy. Sadly, it is non-trivial to build the proto files with "buf" or by any other means.

I tried to use the dotnet grpc tools, but essentially searching and including all of the dependencies has proven to be error prone work. Next I tried to use "buf" since I saw that you use this as well. Now I'm hitting the following error:
```bash
% buf generate                                                                                                        ~/Development/github/mse-wirepact-k8s-operator/Envoy
envoyproxy\api\contrib\envoy\extensions\filters\network\kafka_mesh\v3alpha\kafka_mesh.proto:5:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\config\core\v3\protocol.proto:11:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\config\route\v3\route_components.proto:20:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\bootstrap\internal_listener\v3\internal_listener.proto:5:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\common\async_files\v3\async_file_manager.proto:5:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\filters\http\composite\v3\composite.proto:7:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\filters\http\ext_proc\v3\processing_mode.proto:5:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\filters\network\meta_protocol_proxy\matcher\v3\matcher.proto:5:8:xds/annotations/v3/status.proto: does not exist
envoyproxy\api\envoy\extensions\filters\network\meta_protocol_proxy\v3\route.proto:5:8:xds/annotations/v3/status.proto: does not exist
```

I try to generate c-sharp types from the envoy proto files (in particular the `bootstrap.proto` part) to generate "static" configs for an envoy instance.

The goal is to create a bootstrap object in code, then serialize it to json/yaml and give it to envoy.

I'd appreciate any nudge in the direction of solving my building issues ;-)

Thank you

**Comment by phlax** [comment]
without bazel would be hard work as that is what the protos and their deps are collected with. Even with bazel its not trivial.

the bazel target you are looking for is `@envoy_api//:v3_protos` 

there is an example of generating documentation from the protos in `tools/protodoc/protodoc.bzl`. This uses "aspects" and a protobuf plugin so is not the easiest code to follow

you probs want to look at `rules_proto` 

i have ~successfully built json schemas from the protos in the past, but it never got past r&d and was some time ago (#15100 )

**Comment by buehler** [comment]
Hey @phlax 
Thanks for the reply!

I guess I'll have to let it be. But thank you for the idea! It would've been a cool feature for my operator to generate the envoy config (that gets injected as a sidecar) via statically typed classes, rather than a big string with interpolated ports :-)
