### ISSUE TITLE
Envoy stops updating through XDS server

### ISSUE THREAD

**Issue by renuka-fernando** [envoyproxy/envoy#21107]
*Title*: Envoy stops updating through XDS server

*Description*:
Envoy is serving (proxing) for existing routes, clusters, etc. but it is not updating via the SotW xDS gRPC server for new routes, clusters, etc.

Envoy version: v1.20.0
Go control plane version: v0.10.0 - simple cache
SotW xDS gRPC server

Final log printed was ["[22][warning][client] [source/common/http/codec_client.cc:122] [C8266518] Connection is closed by peer during connecting."](https://github.com/envoyproxy/envoy/blob/v1.20.0/source/common/http/codec_client.cc#L121-L122)

Two replicas of envoy and two replica of xDS servers are running for HA purpose. We identified that one replica of envoy was updated properly and the other one stopped updating. But both of envoy replicas serves for downstream requests with its existing route, cluster configs.

What could be the reason for this kind scenario?

*Repro steps*:
We couldn't reproduced the issue again, restarting envoy fix the issue.

*Config*:
```json
{
    "static_resources": {
        "clusters": [
            {
                "name": "xds_cluster",
                "type": "STRICT_DNS",
                "connect_timeout": "1s",
                "transport_socket": {
                    "name": "envoy.transport_sockets.tls",
                    "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                        "common_tls_context": {...}
                    }
                },
                "load_assignment": {
                    "cluster_name": "xds_cluster",
                    "endpoints": [
                        {
                            "lb_endpoints": [
                                {
                                    "endpoint": {
                                        "address": {
                                            "socket_address": {
                                                "address": "xds-server",
                                                "port_value": 10000
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                "typed_extension_protocol_options": {
                    "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
                        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
                        "explicit_http_config": {
                            "http2_protocol_options": {}
                        }
                    }
                }
            }
        ]
    },
    "dynamic_resources": {
        "lds_config": {
            "ads": {},
            "resource_api_version": "V3"
        },
        "cds_config": {
            "ads": {},
            "resource_api_version": "V3"
        },
        "ads_config": {
            "api_type": "GRPC",
            "grpc_services": [
                {
                    "envoy_grpc": {
                        "cluster_name": "xds_cluster"
                    }
                }
            ],
            "transport_api_version": "V3"
        }
    }
}
```

*Logs*:

```log
[2022-04-18 06:21:43.511][1][info][upstream] [source/common/upstream/cds_api_helper.cc:30] cds: add 1507 cluster(s), remove 6 cluster(s)
[2022-04-18 06:21:43.554][1][info][upstream] [source/common/upstream/cds_api_helper.cc:67] cds: added/updated 0 cluster(s), skipped 1507 unmodified cluster(s)
[2022-04-18 06:21:44.317][1][info][upstream] [source/common/upstream/cds_api_helper.cc:30] cds: add 1507 cluster(s), remove 4 cluster(s)
[2022-04-18 06:21:44.351][1][info][upstream] [source/common/upstream/cds_api_helper.cc:67] cds: added/updated 0 cluster(s), skipped 1507 unmodified cluster(s)
[2022-04-18 06:26:23.084][1][info][upstream] [source/common/upstream/cds_api_helper.cc:30] cds: add 1505 cluster(s), remove 6 cluster(s)
[2022-04-18 06:26:23.123][1][info][upstream] [source/common/upstream/cds_api_helper.cc:67] cds: added/updated 0 cluster(s), skipped 1505 unmodified cluster(s)
[2022-04-18 06:26:23.957][1][info][upstream] [source/common/upstream/cds_api_helper.cc:30] cds: add 1505 cluster(s), remove 4 cluster(s)
[2022-04-18 06:26:23.997][1][info][upstream] [source/common/upstream/cds_api_helper.cc:67] cds: added/updated 0 cluster(s), skipped 1505 unmodified cluster(s)
[2022-04-18 06:27:53.029][1][info][upstream] [source/common/upstream/cds_api_helper.cc:30] cds: add 1507 cluster(s), remove 4 cluster(s)
[2022-04-18 06:27:53.066][1][info][upstream] [source/common/upstream/cds_api_helper.cc:67] cds: added/updated 2 cluster(s), skipped 1505 unmodified cluster(s)
[2022-04-18 06:34:01.436][22][warning][client] [source/common/http/codec_client.cc:122] [C8266518] Connection is closed by peer during connecting.
```

**Comment by renuka-fernando** [comment]
When restarting both go control plane XDS servers we noticed that the healthy envoy server logs [`StreamAggregatedResources gRPC config stream closed: 13`](https://github.com/envoyproxy/envoy/blob/v1.20.0/source/common/config/grpc_stream.h#L159-L160). But the other envoy server which stopped updating through XDS server did not print such a log when it lost connection to the XDS server.

**Comment by renuka-fernando** [comment]
We got the same issue again, but this time we did not observed the log "Connection is closed by peer during connecting." this time, seems there is no relation with it.

This time we have sent the scond xds update after 10 hours we sent the first one. The frozen envoy proxy has logged `[source/common/upstream/cds_api_helper.cc:30] cds: add * cluster(s), remove * cluster(s)` only once and the healthy envoy proxy continue to update xds without any issues. Again restarting the frozen envoy proxy fixed the issue.

**Comment by renuka-fernando** [comment]
We have enabled debug logs of the component "config" with command line option `--component-log-level config:debug`. Is there any other configuration that will help to identify the issue if it occurs again?

**Comment by renuka-fernando** [comment]
We updated tcp_keepalive configs a long time ago and this issue didn't occur so far.
https://github.com/envoyproxy/go-control-plane/issues/91#issuecomment-439443260

**Comment by nickamorim** [comment]
So ever since you’ve added the TCP keepalive config, you haven’t
experienced the issue? Doesn’t that mean it solved the problem?

Nick

**Comment by jamesmulcahy** [comment]
I appreciate this issue is closed, but wanted to share our experience/context relating to this type of issue.

We've seen an issue like this in production.  We're running hundreds of thousands of envoy instances, and saw small numbers of them (~10) in a stuck state.  envoy thought it was connected to the xds server, but the linux tcp stack had no open connection between envoy and the xds server.

We were using TCP keepalives, but these didn't help.  I guess because the TCP level connection was gone, there was nothing to be kept alive anymore.  It seems that somehow envoy lost track of the closed connection.

We've since switched to [H2 Keepalives](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-keepalivesettings) and haven't seen this problem since.
