### ISSUE TITLE
HTTP1 content-length

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#21161]
If envoy receive a HTTP1 request whose content-length is  10000, but actually there is no any data in the http body. Should envoy validate the HTTP request or just forward it to upstream server without any validation ?

**Comment by daixiang0** [comment]
Refer to [rfc7230](https://greenbytes.de/tech/webdav/rfc7230.html#message.body.length)
> If a message is received without [Transfer-Encoding](https://greenbytes.de/tech/webdav/rfc7230.html#header.transfer-encoding) and with either multiple [Content-Length](https://greenbytes.de/tech/webdav/rfc7230.html#header.content-length) header fields having differing field-values or a single Content-Length header field having an invalid value, then the message framing is invalid and the recipient must treat it as an unrecoverable error. If this is a request message, the server must respond with a [400 (Bad Request)](https://greenbytes.de/tech/webdav/rfc7231.html#status.400) status code and then close the connection. If this is a response message received by a proxy, the proxy must close the connection to the server, discard the received response, and send a [502 (Bad Gateway)](https://greenbytes.de/tech/webdav/rfc7231.html#status.502) response to the client. If this is a response message received by a user agent, the user agent must close the connection to the server and discard the received response.

**Comment by zhangbo1882** [comment]
From the rfc, it seems that it does not define the behavior for a proxy when it receives the request.  From my test in envoy, envoy does validate the content-length with the real data.
