### ISSUE TITLE
How to access/protect envoy admin API?

### ISSUE THREAD

**Issue by michelvocks** [envoyproxy/envoy#2117]
Hello,

we would like to use envoy as proxy with the main functionality to do blue/green deployments.
The idea is to manipulate envoy clusters via the admin API from a remote server to automatically route traffic to the blue/green environment and later automatically to production.

I found it really hard to get into the API of envoy. Even after several hours of reading it is still not clear for me if I can simply send API requests with curl to the admin API or is only gRPC supported?
I tried to build the gRPC protofiles (https://github.com/envoyproxy/data-plane-api/tree/master/api) but it seems like there is no documentation on how to do it? 

Another missing information is the topic "How do I protect the admin API?". Is there a way to protect the API? For example with x.509 certificates?

Cheers

**Comment by zuercher** [comment]
There are two things going on here.

1. Envoy supports querying an API to obtain configuration data. These requests originate from an Envoy instance and are made against some API implementation external to Envoy. The protobuf bindings in envoyproxy/data-plane-api are used for the v2 API. The v1 API uses JSON.
2. Envoy can be configured to start an [admin interface](https://www.envoyproxy.io/docs/envoy/latest/operations/admin) which provides commands to view things like stats, clusters, listeners, and server info.

To configure Envoy to obtain configurations from an API server, you end up defining one or more static clusters which refer to the API server host(s). I've not tried this, but in the cluster configuration you can configure TLS for the upstream (API) hosts to secure the requests.

**Comment by michelvocks** [comment]
Hello @zuercher,

thanks for your reply. That makes it a bit clearer for me.
For now, we decided to not use envoy. 
Don't get me wrong, I think envoy is a great product with a lot of features. But the complexity combined with the missing documentation is the killing factor for us. I hope that this will be fixed in the future. ☺️

Cheers
