### ISSUE TITLE
Prometheus format metrics aren't parsable by Prometheus

### ISSUE THREAD

**Issue by JonathanO** [envoyproxy/envoy#2118]
*Description*:
The Prometheus metrics output added by https://github.com/envoyproxy/envoy/pull/2026 don't quite meet the Prometheus spec and as a result aren't parsable by Prometheus (at least not 2.0.0.)

Specifically:
* Label values should be double quoted but are not;
* Backslash, double-quote, and line-feed must be backslash escaped in label values;
* Metric names must match `[a-zA-Z_:][a-zA-Z0-9_:]*` but the current implementation is including . in the names;
* Label names must match `[a-zA-Z_][a-zA-Z0-9_]*` but the current implementation is including . in the names.

*Relevant Links*:
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

*Stats example*
Broken:
```
# TYPE cluster.outlier_detection.ejections_enforced_consecutive_gateway_failure counter
cluster.outlier_detection.ejections_enforced_consecutive_gateway_failure{envoy.cluster_name=VERIFICATION-SERVICE} 0
```
Results in err="no token found" from Prometheus.

A possible alternative?:
```
# TYPE cluster:outlier_detection:ejections_enforced_consecutive_gateway_failure counter
cluster:outlier_detection:ejections_enforced_consecutive_gateway_failure{envoy_cluster_name="VERIFICATION-SERVICE"} 0
```

**Comment by mattklein123** [comment]
@lita can you please take a look?

**Comment by lita** [comment]
I have a PR to fix this here: https://github.com/envoyproxy/envoy/pull/2121 Thanks for reporting the bug!

**Comment by haribruno** [comment]
The metric names produced by envoy also has "-" in them which is not parseable  by Prometheus.
I think we should update the sanitizePrometheusName function to replace "-" to "_" also.

Example:
# TYPE envoy_listener_ssl_ciphers_AES128-SHA256 counter
envoy_listener_ssl_ciphers_AES128-SHA256{envoy_listener_address="0_0_0_0_443"} 3446

**Comment by mattklein123** [comment]
@haribruno please open a new issue and/or just do a PR. Thank you!
