### ISSUE TITLE
No response_flag for request blocked by filter like  http.rbac 

### ISSUE THREAD

**Issue by wenlxie** [envoyproxy/envoy#21197]
*Description*:
When a request is denied, the [RESPONSE_CODE_DETAILS](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-response-code-details) will include the name of the matched policy that caused the deny in the format of rbac_access_denied_matched_policy[policy_name] (policy_name will be none if no policy matched), this helps to distinguish the deny from Envoy RBAC filter and the upstream backend.

From the description of http.rbac  filter,  the response_flag is not set when traffic is blocked. 
In the response_flag definition, there is also no such response_flag for this kind of behavior in envoy.

Is it better that there can have one for this?

**Comment by mattklein123** [comment]
cc @kyessenov @alyssawilk for thoughts on this.

**Comment by alyssawilk** [comment]
I think it'd be fine to have a flag for this.  I went through an audited all local response paths to make sure we had details but IMO flags are still missing in many cases and added mostly ad hoc.

**Comment by kyessenov** [comment]
It'd be fine to add I think. There's an ext_authz flag (UAEX) which fulfills the same purpose.
