### ISSUE TITLE
HTTP/3 serving fails with EIO on Linux

### ISSUE THREAD

**Issue by kanongil** [envoyproxy/envoy#21200]
*Description*:

The supposedly stable HTTP/3 server feature fails to deliver UDP packets on one of my cloud servers.

*Analysis*:

The linux build enables [the GSO batch writer](https://github.com/envoyproxy/envoy/blob/83af7c0b864c69f87e8d3c6969675423a379af4c/source/common/quic/udp_gso_batch_writer.h#L3-L6) to optimize delivery of UDP packets. However, the [`UDP_SEGMENT` feature](https://github.com/torvalds/linux/commit/bec1f6f697362c5bc635dacd7ac8499d0a10a4e7) that this relies on, requires that [`NETIF_F_HW_CSUM` offloading](https://github.com/torvalds/linux/blob/c5eb0a61238dd6faf37f58c9ce61c9980aaffd7a/include/linux/skbuff.h#L58-L62) is enabled. If not enabled (either from an explicit disable or through missing hardware support), the kernel UDP logic returns [an `EIO` error](https://github.com/torvalds/linux/blob/c5eb0a61238dd6faf37f58c9ce61c9980aaffd7a/net/ipv4/udp.c#L931) for any write larger than the interface `MTU`, and envoy *gives up delivering the packet!*

Note that this is a critical issue on one of my cloud servers, which is served by the `virtio_net` driver *without the [`VIRTIO_NET_F_CSUM` feature](https://github.com/torvalds/linux/blob/a7391ad3572431a354c927cf8896e86e50d7d0bf/drivers/net/virtio_net.c#L3493)*. I have no way to enable it, and my current workaround is a custom compile of `envoy` where I force `UDP_GSO_BATCH_WRITER_COMPILETIME_SUPPORT = 0`.

*Repro steps*:

1. Using `envoy` binary from published v1.22.0 Linux x86_64 docker image with example HTTP/3 server from [here](https://github.com/envoyproxy/envoy/blob/v1.22.0/configs/envoyproxy_io_proxy_http3_downstream.yaml).
2. Ensure MTU is <= 1500 and transmit `tx-checksumming` is `off` on the primary network interface: `ethtool -K <if> tx off`.
3. Perform any HTTP/3 request from an external host.
4. Observe that no usable packets are returned from the server, and an error is printed to the server console. 

*Config*:

https://github.com/envoyproxy/envoy/blob/v1.22.0/configs/envoyproxy_io_proxy_http3_downstream.yaml

*Logs*:

```
[2022-05-05 17:19:10.518][1411][error][quic] [external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:3874] Server: Write failed with error: 5 (Input/output error)
```

`strace`
```
recvmmsg(36, [{msg_hdr={msg_name={sa_family=AF_INET, sin_port=htons(36346), sin_addr=inet_addr("<snip>")}, msg_namelen=128->16, msg_iov=[{iov_base="\302\0\0\0\1\20\231v\35\272\230:&\260\232\34\354B\312\267\266\320\24\34eNH\270\22\301\330\3"..., iov_len=1500}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("eth0"), ipi_spec_dst=inet_addr("<snip>"), ipi_addr=inet_addr("<snip>")}}], msg_controllen=32, msg_flags=0}, msg_len=1200}], 16, MSG_TRUNC|MSG_WAITFORONE, NULL) = 1
sendmsg(36, {msg_name={sa_family=AF_INET, sin_port=htons(36346), sin_addr=inet_addr("<snip>")}, msg_namelen=16, msg_iov=[{iov_base="\316\0\0\0\1\24\34eNH\270\22\301\330\3\363\311\fi\236W\242\263\240G\307\10\231v\35\272\202"..., iov_len=3600}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=0, ipi_spec_dst=inet_addr("<snip>"), ipi_addr=inet_addr("0.0.0.0")}}, {cmsg_len=18, cmsg_level=SOL_UDP, cmsg_type=0x67}], msg_controllen=56, msg_flags=0}, 0) = -1 EIO (Input/output error)
```

**Comment by RyanTheOptimist** [comment]
Thanks for the report! I'm not familiar by the details here. Perhaps @danzh2010 has a better idea? That being said, I do have a couple of questions. I'm curious why the interface MTU ends up smaller than the QUIC packet size? Normally QUIC connections in envoy have a max packet size of 1250 bytes. Secondly, OsSysCallsImpl::supportsUdpGso attempts to check to see if UDP GSO works but checking that UDP_SEGMENT seems to work correctly. https://github.com/envoyproxy/envoy/blob/main/source/common/api/posix/os_sys_calls_impl.cc#L108 Would it be possible to check NETIF_F_HW_CSUM similarly in that method, do you think?

**Comment by kanongil** [comment]
Thanks for looking into this. The check you link only verifies that the kernel supports the `UDP_SEGMENT` option. You can't really pre check whether GSO will actually work, since it depends on the used network interface and options.

I see two ways to fix this:

1. Add an option to manually disable the feature and provide a warning / advise when `EIO` is encountered.
2. Transparently disable GSO for an interface on any `EIO`.

Given that this is a corner case and the potential complexity of implementing option 2, I would probably just go for 1. Any proper deployment will likely always want GSO.

**Comment by kanongil** [comment]
I don't know why envoy tries to send 3600 bytes in a packet, but packet size > interface MTU is needed to utilise the GSO optimization.

**Comment by RyanTheOptimist** [comment]
Sounds reasonable. I'll take a stab at that.
