### ISSUE TITLE
Feature Request: Routing based on HTTP query string

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2120]
*Title*: *Routing based on HTTP query string*

*Motivation*:
For some applications, the HTTP query string carries information useful for routing.  The `prefix`, `path`, and `regex` fields in the Route configuration structure only match on the part of the `:path` prior to the `?`.

*Proposal*:
Add one new field to the [Route](https://www.envoyproxy.io/docs/envoy/latest/api-v1/route_config/route.html#config-http-conn-man-route-table-route) configuration structure:

*query_regex*
_(optional, string)_ Indicates that, in addition to `prefix`, `path`, or `regex`, the route additionally requires a regular expression match on the query string.  The entire query string (minus the leading `?`) must match the regex.

*Notes*
* If there's interest in this, I am willing to contribute an implementation.

*Alternatives*
Another way to achieve a similar result would be to support a structured config instead of a regular expression; e.g.,
```
"query_matches": [
  {
    "key": "env",
    "value": "test"
  },
  {
    "key": "user_id",
    "regex": "\d+[02468]"
  }
]
```
This approach would be more expressive than a single regex, but it would add more complexity to the HTTP connection manager filter.

**Comment by 9len** [comment]
we supported this in the NGINX-flavor of the Turbine Labs product, and would love to be able to support it in the Envoy-based one. 

I think our preference would be to treat query matches similar to header matches, schema-wise.
