### ISSUE TITLE
Why does dubbo filter set inbound|20880|| in inbound so that it will not report dubbo router: unknown cluster inbound|20880||

### ISSUE THREAD

**Issue by yingjianjian** [envoyproxy/envoy#21215]
*Description*:
ask  @wbpcode  Why does dubbo filter set inbound|20880|| in inbound so that it will not report dubbo router: unknown cluster inbound|20880||
E.g:
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
        name: virtualInbound
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.dubbo_proxy
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.network.dubbo_proxy.v3.DubboProxy
          value:
            dubboFilters:
            - name: envoy.filters.dubbo.router
            routeConfig:
            - interface: '*'
              name: inbound|20880||
              routes:
              - match:
                  method:
                    name:
                      safeRegex:
                        googleRe2: {}
                        regex: .*
                route:
                  cluster: inbound|20880||
            statPrefix: inbound|20880||
  workloadSelector:
    labels:
      app: dubbo-sample-provider

`
  Upstream::ThreadLocalCluster* cluster = cluster_manager_.get(route_entry_->clusterName());
  if (!cluster) {
    ENVOY_STREAM_LOG(debug, "dubbo router: unknown cluster '{}'", *callbacks_,
                     route_entry_->clusterName());
    callbacks_->sendLocalReply(
        AppException(ResponseStatus::ServerError, fmt::format("dubbo router: unknown cluster '{}'",
                                                              route_entry_->clusterName())),
        false);
    return FilterStatus::StopIteration;
  }

`
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Sorry, can you describe your question with more detailed info? I don't get your problem clearly.

As you can see in the code snippet you post, when the dubbo router cannot get the cluster by the name, the error `unknown cluster` will be returned. So may be the xds server just only create a ` inbound|20880||` for the indound proxy.

It seems that this issue is not directly related with Envoy.

**Comment by yingjianjian** [comment]
> * inbound|20880||

Sorry just saw the reply. My question is this. At present, the inbound cluster configuration in Dubbo's case is inbound|20880|, not, for example, inbound|20880|http-80111|***** why can it be configured as inbound|20880||

**Comment by wbpcode** [comment]
> > * inbound|20880||
> 
> Sorry just saw the reply. My question is this. At present, the inbound cluster configuration in Dubbo's case is inbound|20880|, not, for example, inbound|20880|http-80111|***** why can it be configured as inbound|20880||

This depends on the implementation of xds server. From the inspect of Envoy, the name of cluster has no special meaning.

> why can it be configured as `inbound|20880||`

Because xds server create it.

**Comment by yingjianjian** [comment]
> > > * 入站|20880||
> > 
> > 
> > 不好意思刚看到回复。我的问题是这个。目前 Dubbo 的情况下 inbound 集群配置是 inbound|20880|，而不是比如 inbound|20880|http-80111|***** 为什么可以配置成 inbound|20880||
> 
> 这取决于 xds 服务器的实现。从 Envoy 的检查来看，集群的名称并没有什么特别的含义。
> 
> > 为什么可以配置为`inbound|20880||`
> 
> 因为 xds 服务器创建它。

Thank you, the code implementation of this part is in that function, I will study it
