### ISSUE TITLE
Bazel build command failed

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#21219]
*Title*: *Bazel build fail*

*Description*: On latest code while running below command , its failing.. please help .. 
bazel build //source/exe:envoy-static
2022/05/10 15:50:47 Downloading https://releases.bazel.build/6.0.0-pre.20220421.3/release/bazel-6.0.0-pre.20220421.3-linux-x86_64...
2022/05/10 15:50:47 could not download Bazel: HTTP GET https://releases.bazel.build/6.0.0-pre.20220421.3/release/bazel-6.0.0-pre.20220421.3-linux-x86_64 failed with error 404

**Comment by mattklein123** [comment]
cc @keith

**Comment by keith** [comment]
Can you update your `bazelisk` version locally and see if that fixes it? https://github.com/bazelbuild/bazelisk/releases

**Comment by ankatare** [comment]
@keith @mattklein123 Thanks for help.
@keith thanks for pointers.. solved this issues with update the file **.bazelversion** locally with latest stable **version 5.1.1**

**Comment by keith** [comment]
wait that's not what i meant, that's changing the _bazel_ version not the _bazelisk_ version. at this point the version in the `.bazelversion` is the only supported version to use for building envoy, so you might run into various other issues

**Comment by ankatare** [comment]
@keith But that did not worked.. i tried :( . So yeah, its a kind of workaround to me to proceed atleast

**Comment by keith** [comment]
Can you try on this branch https://github.com/envoyproxy/envoy/pull/21253 with `./bazelw build envoy`?

**Comment by tobiayofe** [comment]
> Can you update your `bazelisk` version locally and see if that fixes it? https://github.com/bazelbuild/bazelisk/releases

Where can we affect this change, please?
