### ISSUE TITLE
Changing grpc application name

### ISSUE THREAD

**Issue by riyadshairi979** [envoyproxy/envoy#21259]
Hi folks
I have a REST client connecting to gRPC server through Envoy. But due to firewall I am getting this error below.
My question is, can I rewrite the request header at Envoy in such a way that the application name (i.e. `grpc`) get removed and firewall allow the request to get to the server.
```
E               <div id="content">
E               <h1>Application Blocked</h1>
E               <p>Access to the application you were trying to use has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.</p>
E               <p><b>User:</b> xxx.xxx.xxx.xxx </p>
E               <p><b>Application:</b> grpc </p>
E               </div>

**Comment by dio** [comment]
I think you can use: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v-16-api-field-config-route-v3-routeconfiguration-request-headers-to-remove.

And if you want to set it to something else:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v-7-api-field-config-route-v3-routeconfiguration-request-headers-to-add (by setting the `append` flag to false).
