### ISSUE TITLE
Ability to mark host as unhealthy and still accept new connections

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#21256]
i was trying to use "curl http://localhost:15000/healthcheck/fail -X POST" but this also makes envoys to stop accepting new connections. In our case we want to continue accepting new connections and at the same time fail hc so that AWS NLB knows that hc is failing. Is there any way to mark envoy as unhealthy and continue accepting new connections till we do drain in the end ?

**Comment by mattklein123** [comment]
I don't believe that admin endpoint fails new connections. It should do exactly what you are asking for. What makes you think otherwise?
