### ISSUE TITLE
OAuth2 Filter's [AuthorizationEndpointFormat]  `state` parameter could be configurable

### ISSUE THREAD

**Issue by timmotw** [envoyproxy/envoy#21252]
OAuth2 Filter's [AuthorizationEndpointFormat]  `state` parameter could be configurable `state` could be configurable

OAuth2 Filter's [AuthorizationEndpointFormat]  `state` could be configurable which would save the cases where re-writing redirect `URLs` and instead always have a static `state` parameter `URL` value.

https://github.com/envoyproxy/envoy/blob/aa19a78404e285d5cd219c564a68e67c59484075/source/extensions/filters/http/oauth2/filter.cc#L58-L59

e.g. A web-app makes a `gRPC` request which responds with a redirect. The gRPC request is merely an `XMLHttpRequest` which needs to be intercepted and finally redirect the `window.location.href` to the `SSO` server's login page. After a successful authentication/authorization it is required to actually redirect to the web-app's URL and not to re-issue the gRPC initial request which was the `state` parameter's value.

**Comment by mattklein123** [comment]
Sorry I'm not sure what this is referring to. Please provide more information.

**Comment by timmotw** [comment]
@mattklein123 I have updated the description. I hope it is all good now.

Thank you!

**Comment by mattklein123** [comment]
cc @rgs1

**Comment by timmotw** [comment]
My `envoy` instance is reverse proxied behind `nginx` at `https://$host/api/v3` and the `state` parameter takes the following value:

`&state%3Dhttp%253A%252F%252F127.0.0.1%253A8085` => `&state=http://127.0.0.1:8085`

I believe that a good solution would be able to have the ability to define a static or dynamic value for the `state` parameter:

1. **static**:      `state: "https://localhost/api/v3"`
2. **dynamic**: `state: "%REQ(:scheme)%://%REQ(:x-forwarded-for)%/api/v3"`
