### ISSUE TITLE
Envoy does not recognize `envoy.api.v2.auth.Secret` type_url for secrets when using filesystem XDS

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#21260]
*Title*: Envoy not recognizing type for secrets

*Description*:
When using the file system as a config source for XDS, it appears that Envoy does not accept `envoy.api.v2.auth.Secret` as a type for secrets.

*Repro steps*:
Clone the following repo and run `docker-compose up --build envoy`
https://github.com/cetanu/secret_invalid_type_url_repro
This repo contains a private key from a self-signed certificate and is not PII

*Logs*:
```
Filesystem config update failure: Unable to parse JSON as proto (INVALID_ARGUMENT:(resources[0]): invalid value Invalid type URL, unknown type: envoy.api.v2.auth.Secret for type Any)
```

**Comment by phlax** [comment]
there is v3 config/api equivalent:
 
```yaml
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
```

i think you probably want to look at these docs for the newer proto/configuration, for example here:

https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret

**Comment by cetanu** [comment]
Indeed, that seems to work fine... I must have been suffering from some confusion yesterday. I'm getting these secrets from SDS and I must be specifying V2 as the resource api version accidentally...
