### ISSUE TITLE
Add option for Custom headers to append empty string when dynamic value cannot be resolved

### ISSUE THREAD

**Issue by paul-r-gall** [envoyproxy/envoy#21265]
*Title*: Add option for Custom headers to append empty string when dynamic value cannot be resolved.

*Description*:
Custom headers currently do not append anything if `%DYNAMIC_VALUE%` does not resolve to a non-empty string. It would be helpful to have an additional option in `HeaderValueOption` to append "header-name:" in these cases. Happy to send a PR myself.

**Comment by mattklein123** [comment]
Sure sounds fine to me.
