### ISSUE TITLE
Load balancing within http2 connection pool

### ISSUE THREAD

**Issue by anuraagkonda** [envoyproxy/envoy#21279]
*Title*: *Load balancing within http2 connection pool*

*Description*:
  Based on this document here https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310,  though HTTP/2 connection pools 
  only make a single connection to each upstream host at a time, if there are four workers, there will be four HTTP/2 connections per 
  upstream host at steady state. So when does envoy uses another HTTP/2 connection for passing requests ?. Is that algorithm based  
  on [max concurrent streams(https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/connection_pooling)] ?.

**Comment by mattklein123** [comment]
Correct, it's per thread and based on max concurrent streams.

**Comment by mattklein123** [comment]
In HTTP/2 streams are split between outgoing and incoming (for push), thus the actual limit is half the max. In general, there is such a larger number of concurrent streams I'm very surprised this actually works?

**Comment by anuraagkonda** [comment]
Thanks @mattklein123. Yes we are currently testing a teclo product in a cloud native environment. For which we are seeing large number of concurrent streams. Our main issue is that of the connection is causing request to fail. We were expecting the connection to drain in that scenario, but that hasn't been the case. Still investigating that issue and looking for logs. Hence wanted to understand how the load balancing works internally within http2 connection pool.
