### ISSUE TITLE
[route] add a option to not consider port in :authority when matching route.

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#21272]
*Title*: Add an option in route to strip port in ":authority" when we do service picking.

*Description*:

See related issue, but different: https://github.com/envoyproxy/envoy/issues/19589

a Cloud Customer sets the host match rule without a port, and oftentimes they configure their http services on multiple ports other than the default one. 

The traffic comes in as "www.foo.com:8080", and since the host/domain in config is without a point, doamin "www.foo.com" will not match the host and a 404 returned or the default catch-all virtualHost is matched instead. 

It'd be ideal if we can add an option in RouteConfiguration, say "strip_host_port_in_domain_matching", only match on the domain portion if the :authority happens to contain a port.  

In a cloud-proxy scenario, this allows different cloud customers to set different behaviors for their traffic load balancing. 

[optional *Relevant Links*:]
> See https://github.com/envoyproxy/envoy/issues/19589 , where a single HCM level option 'strip_any_host_port' removes port from ":authority" on receiving the request.

**Comment by stevenzzzz** [comment]
cc @adisuissa @alyssawilk

**Comment by stevenzzzz** [comment]
cc @htuch @yanavlasov

**Comment by htuch** [comment]
I think this makes sense given this is just a `RouteConfiguraiton` level variant of `strip_any_host_port` at HCM-level. Chatting with @stevenzzzz offline, the usefulness of this comes up in multi-tenant SRDS scenarios, where we don't want a shared setting across all scopes.

I'd suggest:
* Using consistent terminology, so `strip_any_host_port` here.
* Consider future proofing so that this can also accommodate `strip_matching_host_port` if needed later.
* Clearly documenting the override semantics between this setting and the HCM-level setting.

**Comment by yurykats** [comment]
One key difference here is that we don't want to mutate (ie actually strip) the value. The need is not to use the port for purpose of matching, but otherwise leave it intact.

**Comment by mattklein123** [comment]
SGTM. Agree on consistent terminology.

**Comment by htuch** [comment]
I think if we do this non-mutation, we must ensure that there is no use of `:port` in the virtual host domains (or that they could never match if there was one there) FWIW. In this case, we should name this `ignore_host_port` I think.

**Comment by stevenzzzz** [comment]
for "strip_any_host_port", I actually lack some context first place why we would strip port from host at listener level. As a proxy, I'd hope it to be as transparent as possible. but Envoy mutates the very import ":host" header with little customer intervention. 

I am adding a new "ignore_port_in_host_matching" option at route-table level, which doesn't mutate the host header. 

OTOH, strip_any_host_port cause tricky issue w.r.t host-rewrite: should the original port from request be used or not when there is no port_rewrite.  (I think it should be, but envoy is doing the other way). ==> https://github.com/envoyproxy/envoy/issues/19589

**Comment by stevenzzzz** [comment]
this can be closed now.
