### ISSUE TITLE
Fancy logger always add lock to sink?

### ISSUE THREAD

**Issue by npuichigo** [envoyproxy/envoy#21287]
https://github.com/envoyproxy/envoy/blob/4be974cc4aa6379b7e1f98256b9a21fc4516afbd/source/common/common/fancy_logger.cc#L116-L118

Does fancy logger always add a lock to sink even the underlying sink delegate doesn't need to lock? Or if no lock is provided like the following `FileSinkDelegate`, a default lock will be created?

https://github.com/envoyproxy/envoy/blob/a683723630417822a34a02cfce15f1a77b4e85bc/source/server/server.cc#L100-L101

**Comment by mattklein123** [comment]
cc @jmarantz

**Comment by npuichigo** [comment]
Resolved. It seems that an stderr sink always has a lock.
