### ISSUE TITLE
Indication of connection loss on downstream TCP and HTTP requests

### ISSUE THREAD

**Issue by egerkke** [envoyproxy/envoy#21294]
*Title*: *Indication of connection loss on downstream TCP and HTTP requests*

*Description*:

Hi Ladies and Gents,

In our project according to our internal security design rules, TCP connection loss from clients shall be indicated as non-audit security log since it can be an indicator of a security threat.
I tried to check what Envoy logs into access log in such case and:
 - used an HTTP traffic generator (vegeta) on my laptop
 - iptables to disable traffic from the generator
 - configured TCP idle_timeout to 60 seconds

In the captured tcpdump it was visible the after 60 seconds the iptables rule was applied, Envoy tried to finish the TCP connection. Then retried 10 times.

What is unclear for me:
 - Can you please help me how many times Envoy will retry to close the session? Or I reached it with the 10 times?
 - If I did not reach then will there be any indication in Envoy's access log when it gives up?
 - Also a question if connection reset from client appears in access log?
 
 Thanks in advance!

**Comment by mattklein123** [comment]
I'm not sure I completely follow what you are asking, but it sounds to me like you are talking about kernel level TCP retries. Envoy is not aware of this. From Envoy's perspective it would see the remote close and if you have connection level access logging set up you would be able to log information about the closed connection.

**Comment by egerkke** [comment]
Hi Matt,
Many thanks!
And if client opens TCP connection, sends some request, then disappears without closing the connection then will there be any indication in the access log?

**Comment by mattklein123** [comment]
Yes

**Comment by egerkke** [comment]
Sorry again for grabbing your precious time. I tried to trigger connection loss to see the outcome in Envoy access log:
 - started continuous HTTPv1 GET traffic
 - applied iptables rule to disable source IP
 - the loss (that client is not sending anything) is visible in the tcpdump
 - Envoy tries to close the connection with TCP FIN, ACK after 60 seconds of inactivity
 - then retries to finish the connection 10 times
I waited 1,5 hours and no any error related message appeared in the access log.

This is our access log configuration:

```
"access_log": [
             {
              "name": "envoy.access_loggers.file",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
               "path": "/dev/stdout",
               "log_format": {
                "text_format_source": {
                 "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
                },
                "formatters": [
                 {
                  "name": "envoy.formatter.req_without_query",
                  "typed_config": {
                   "@type": "type.googleapis.com/envoy.extensions.formatter.req_without_query.v3.ReqWithoutQuery"
                  }
                 }
                ]
               }
              }
             }
```
I've read this link through,  [Envoy access log](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage) but couldn't identify what operator we are missing.

Can you please help if we are missing anything?

Many thanks in advance!

**Comment by egerkke** [comment]
Hi @lambdai ,

Thanks for the information. I asked many questions in one ticket, let me know separate them as:
- Q1. downstream connection loss
- Q2. TCP RST from downstream client

In case of Q1, I'm attaching now a pcap file.
[downstream_client_loss.pcap.tar.gz](https://github.com/envoyproxy/envoy/files/8742262/downstream_client_loss.pcap.tar.gz)
Here the downstream client is 100.109.96.1 and Envoy is 10.244.1.11.
Client creates TCP connection, then sends GET requests and receives replies. Then I simulate the connection loss of the downstream.
This use case did not create any access log entry for me, only the HTTP 200s. Shouldn't this be logged somehow that cliennt disappeared?

**Comment by lambdai** [comment]
> This use case did not create any access log entry for me, only the HTTP 200s. Shouldn't this be logged somehow that cliennt disappeared?

No. http conn manager generates access log for each *http request*. Http access log does not provide L4 info if the L4 event does not cause a request failure. If the RST/connection loss occurs and lead to partial req/response, you should see a transport layer failure reason. E.g. DC, LR... See https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

It would be good to have an independent network filter to generate the TCP access log.

**Comment by lambdai** [comment]
It's easy to implement, but the functionality is too thin (tracking connection_id and close reason) to create a dedicated network filter...
@mattklein123 WDTY?

**Comment by kfaseela** [comment]
This aligns to the requirement in the comment here as well? https://github.com/envoyproxy/envoy/issues/19604#issuecomment-1040502819

**Comment by egerkke** [comment]
Hi Lady and Gents,

Please help me to phrase properly.

Indicating TCP connection level issues of downstream client when:
 - connection was established earlier
 - there is no active http request
 - something happens on client side with the connection
   - loss of connectivity with client
   - RST is sent from client

With error log information:
 - TCP connection ID
 - and Connection closure reason

Either in:
 - access log
 - or generic log

Therefore such log can be used to detect possible security threat coming from client side.

**Comment by mattklein123** [comment]
I'm pretty sure the listener log will cover your case. Can you please look and let us know what is missing?

**Comment by egerkke** [comment]
Hi Matt,
I attached above my [tcpdump](https://github.com/envoyproxy/envoy/files/8742262/downstream_client_loss.pcap.tar.gz) that I created when simulated the use case of disappeared client. This use did not create any log entry.

**Comment by mattklein123** [comment]
Sorry I don't have the time right now to look through the TCP dump. Feel free to share screen shots of wireshark output of annotated sections.

What is the full config you are using. Have you turned on listener access logs as I suggested?

**Comment by egerkke** [comment]
Hi Matt,

The wireshark output screen shot:
![wireshark](https://user-images.githubusercontent.com/96073071/171225769-68dfd64e-454c-4c7d-99ad-c21f16676b0a.jpg)

And this is the access log configuration I used:

>             "access_log": [
>             {
>              "name": "envoy.access_loggers.file",
>              "typed_config": {
>              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
>               "path": "/dev/stdout",
>               "log_format": {
>                "text_format_source": {
>                 "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %CONNECTION_TERMINATION_DETAILS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
>                },
>                "formatters": [
>                 {
>                  "name": "envoy.formatter.req_without_query",
>                  "typed_config": {
>                   "@type": "type.googleapis.com/envoy.extensions.formatter.req_without_query.v3.ReqWithoutQuery"
>                  }
>                 }
>                ]
>               }
>              }
>             }
>            ],

Earlier I haven't noticed there is '%CONNECTION_TERMINATION_DETAILS%' operator as well, now I added this as well and reproduced the use case. It did not create any access log entry.

BR.
Gergo

**Comment by egerkke** [comment]
Hi Matt,

Annotated TCP dump:
[downstream_client_loss_annotated.pcapng.tar.gz](https://github.com/envoyproxy/envoy/files/8815023/downstream_client_loss_annotated.pcapng.tar.gz)

Full Envoy config:
[envoy_config.tar.gz](https://github.com/envoyproxy/envoy/files/8815026/envoy_config.tar.gz)

And we are using HTTP connection manager access log.

**Comment by mattklein123** [comment]
I already explained that you need to use the listener access log if you want to see a log at the connection level for every connection. Please use that.

**Comment by egerkke** [comment]
OK, thanks, I try it out. Till now I believed the listener access log is also to be configured via the HTTP connection manager operators.

**Comment by egerkke** [comment]
Hi Matt,

Sorry, for just replying now. I configured listener access log with the following settings:

>  inline_string: "[%START_TIME%] TCP Connection %DOWNSTREAM_REMOTE_ADDRESS% %BYTES_RECEIVED% %CONNECTION_TERMINATION_DETAILS% %UPSTREAM_REQUEST_ATTEMPT_COUNT% %DURATION% %RESPONSE_FLAGS% \n"

Also attached the whole configuration. [base_envoy_config_with_listener_accesslogs.txt.tar.gz](https://github.com/envoyproxy/envoy/files/8853900/base_envoy_config_with_listener_accesslogs.txt.tar.gz)

With this configuration when the TCP connection is closed normally y client, it appears in the access like:
> [2022-06-07T13:43:30.306Z] TCP Connection 100.109.96.1:38321 196 - 0 1780 -

But when I simulated the connection loss, also similar output appeared after the 10th fin,ack retransmission:
> [2022-06-07T13:44:04.673Z] TCP Connection 100.109.96.1:55855 588 - 0 71011 -

%CONNECTION_TERMINATION_DETAILS% holded no additional information: "-"

Can you please help that which operator shall give additional information how the TCP connection was terminated?

Thanks in advance!

**Comment by mattklein123** [comment]
> Can you please help that which operator shall give additional information how the TCP connection was terminated?

I'm not sure this is possible. I don't think the kernel differentiates between these 2 types of closes, or at least not without special linux specific syscalls. If you want to investigate and open an issue specific to that feature request that is fine. Thank you!

**Comment by egerkke** [comment]
OK, thanks for the support, I raise a feature request.
BR.
Gergo
