### ISSUE TITLE
Add exec_config_source support to ConfigSource, allowing secrets to be generated by local scripts

### ISSUE THREAD

**Issue by jamesmulcahy** [envoyproxy/envoy#21292]
*Description*:

There are circumstances where we want to use our xds control plane to push configuration to envoy, but the control plane does not have the necessary information available to it to allow it to push a fully formed resource.  One specific example of this is secrets which are only available on the instance itself – or secrets which may be known to the control plane, but are in an encrypted form and need decrypting on the instance before they can be consumed by envoy.

I've written up an outline of a [design](https://docs.google.com/document/d/1SWf530qVhkrYcqTvb5UUsRuQgXVfyzFCHAsOZmtrCPQ/edit#) to address this use case

**Comment by mattklein123** [comment]
Thanks for the feature request. I'm not thrilled with building execute directly into the API, as it's highly environment dependent what this means and what the capabilities are. I think it would be better to just have an extension point here if there isn't one already such that you can build your own local execute extension. cc @envoyproxy/api-shepherds for thoughts.

**Comment by markdroth** [comment]
I agree, adding this general-purpose mechanism to `ConfigSource` seems like overkill.

If the goal here is to get TLS certificate data from an external command, I think a better approach would be to use the `CertificateProvider` framework being built in #19582.

**Comment by htuch** [comment]
I like the idea of a config provider extension point that Matt suggests. It's just a generic extension point that will have an API to act as an xDS provider. Then @jamesmulcahy can implement this exec as an extension.

**Comment by jamesmulcahy** [comment]
> I think we should support an in-tree extension point, and then you can maintain a private extension for your use case? Does that work?

Yeah, that works for us!

**Comment by htuch** [comment]
@jamesmulcahy will you folks take on the implementation work here?

**Comment by jamesmulcahy** [comment]
@htuch Sorry for the delay in replying; I was out on vacation.

Yes, we plan to take this on, but don't have line of sight to a specific point in time when we will get to this -- we're juggling a few other things at the moment.
