### ISSUE TITLE
Excluding network errors from upstream_rq_5xx

### ISSUE THREAD

**Issue by jwilner** [envoyproxy/envoy#21295]
A*Title*: Exclude network errors from upstream_rq_5xx
*Description*:

Envoy's stats classify per try timeouts (and presumably other network errors) as 5xx style errors. Pre-try timeouts are not actually 5xxs from upstreams, and I need to track those separately. Is there an established mechanism for distinguishing them (there seems to be [this](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-split-external-local-origin-errors) in the context of outlier detection)? 

```shell 
> grep mycluster stats.txt | grep -E 'per_try_timeout|upstream_rq_504'
cluster.mycluster.external.upstream_rq_504: 658
cluster.mycluster.upstream_rq_504: 658
cluster.mycluster.upstream_rq_per_try_timeout: 658
```

Additionally, is there any documentation or discussion we can refer to about these classifications?

**Comment by mattklein123** [comment]
There isn't any way to do this today though it's a reasonable feature request.

> Additionally, is there any documentation or discussion we can refer to about these classifications?

I don't think so. Whatever we have would be here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#statistics. It would be great to do a doc PR if you are so inclined to make the current behavior more clear.

In terms of the "why," in general my philosophy (which is where this originally came from), is that if a decision that Envoy makes on behalf of an upstream leads to a failure, the failure should be charged to the upstream. This has worked well in most operational deployments that I know of.

**Comment by jwilner** [comment]
Thanks -- that philosophy is certainly understandable.

I think I'll probably do a little grepping of the codebase to reason about
what the various relationships between the stats are and then open up just
such a PR.
