### ISSUE TITLE
Single worker thread design and http2_filter issue

### ISSUE THREAD

**Issue by Joeostr** [envoyproxy/envoy#21290]
We are successfully using envoy with a custom http_filter, but we are running into a concurrent issue with HTTP2. I wonder if we are missing something, or an Envoy limitation which needs to improve.

HTTP2 creates a single connection per domain, and its multiplexing within that connection. In our scenario, the custom http_filter is reaching out to an external module, and must wait for a response. While waiting, all other requests for that domain are queued which results in a very slow browsing experience. HTTP1 is a lot better because it runs 6 connections in parallel

**Comment by mattklein123** [comment]
It's hard to help without a bunch more information. There is nothing inherent in Envoy that should be causing this blocking.

**Comment by Joeostr** [comment]
Hi @mattklein123, below is an example of code (not the actual code), and description of what we face

**Description**
https://github.com/iluxa/envoy-filter-example/blob/main/TEST.md
 
**Code Example**
https://github.com/iluxa/envoy-filter-example/blob/main/forward-proxy.yaml
https://github.com/iluxa/envoy-filter-example/blob/main/http-filter-example/http_filter.cc
https://github.com/iluxa/envoy-filter-example/blob/main/http-filter-example/http_filter.h
https://github.com/iluxa/envoy-filter-example/blob/main/http-filter-example/http_filter_config.cc

**Comment by Joeostr** [comment]
`If you need to make side calls you can use the built in AsyncClient functionality.`

@mattklein123 , can you please point me to the documentation describing the AsyncClient functionality?

**Comment by mattklein123** [comment]
https://github.com/envoyproxy/envoy/blob/main/envoy/http/async_client.h

You can search the code for uses. There are many.

**Comment by Joeostr** [comment]
@mattklein123, we tried the below to resolve the issue (split proxying into two stages), but it doesn't seem to work when using Envoy as a transparent proxy. If you don't mind, can you give me a quick example of how we can use Async with [this ](https://github.com/iluxa/envoy-filter-example/blob/1627904274a0a3f52db934429c55936ac0bc25c7/http-filter-example/http_filter.cc) example code?

We aren't using sleep, its just there as an example in replacement of the real code

https://github.com/iluxa/envoy-filter-example/commit/b4e33b814fc28b3fa64aa5694560cf8ec89c6aac

**Comment by Joeostr** [comment]
@mattklein123, the Async examples are HTTP based (RestfulAPI), which doesn't cover our use case. We compile our code together with Envoy, and just call code functions. 

We also tried to split the proxying into two stages. The first stage splits streams into connections, and the second stage performs the actual filtering. This is strangely not working when running Envoy as a transparent (bridged) proxy. Explicit proxy does work. Example below

https://github.com/iluxa/envoy-filter-example/blob/main/forward-proxy-transparent.yaml

**Comment by mattklein123** [comment]
As I already explained, you cannot block ever. If your custom code blocks, you are going to have to run it on a different thread and synchronize the dataplane threads with that thread.
