### ISSUE TITLE
OAuth2 filter for Azure AD?

### ISSUE THREAD

**Issue by mukundv18** [envoyproxy/envoy#21334]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Can OAuth2 filter be used for authenticating on Azure AD?*

*Description*:

Trying to achieve Envoy to authenticate and authorize the users before talking to Redis.

```
                                  Azure AD
                                       ^
                                       |
                                       |
Application         ---->           Envoy           ----->            Redis

```

Since the Envoy should interact with Redis and NOT Web application, what should be specified in the redirect URI?
Also, since the application will be using redis client to talk to Envoy, how to perform authentication/authorization using Azure AD?

**Comment by snowp** [comment]
The OAuth2 filter today is a HTTP filter so I don't think this would work for Redis since Redis is not a HTTP protocol

I'm not sure how the OAuth2 filter would work for a network filter, maybe @rgs1 has thoughts? In any case this would have to be a new filter

**Comment by mukundv18** [comment]
Thank you @snowp !
