### ISSUE TITLE
RUNTIME_GUARD(envoy_reloadable_features_allow_concurrency_for_alpn_pool);

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#21345]
Yesterday's [change](https://github.com/envoyproxy/envoy/commit/6122195d8f64ac54157412e6aa48f2450c1d6b3c#diff-564059d71ff5c0acfb543ba9d9d652bcd7b716e741dcc45c6b8e4d60ff5428c0) to `RUNTIME_GUARD(envoy_reloadable_features_allow_concurrency_for_alpn_pool);` (from `FALSE_RUNTIME_GUARD`) causes our end-to-end tests to crash, hitting the `ENVOY_BUG` [here](https://github.com/envoyproxy/envoy/blob/471eb786e9ff897140f8d800b5e3e7f21916991e/source/common/upstream/cluster_manager_impl.cc#L1893).

**Comment by alyssawilk** [comment]
can you tell me a bit more about your tests?  are they doing alpn pool without tls somehow?

**Comment by ravenblackx** [comment]
Discussed with Alyssa in Slack a bit, short version is that we have a custom tls config (I think `validation_context_sds_secret_config` having an `api_config_source` with `api_type: GRPC` was surmised to be the likely cause, or near it.)
