### ISSUE TITLE
Pre-initialize upstream connection pools

### ISSUE THREAD

**Issue by nitgoy** [envoyproxy/envoy#21346]
*Title*: *Is there a way to pre-initialize the upstream connection pools?*

*Description*:
>We are seeing some issues with gRPC flows where upstream connection creation is taking longer than we can afford for some scenarios. If we could perhaps pre-initialize the upstream connection pools so that they have at least one connection created well ahead of client requests, it would help avoid that cost for the first few requests. Is there a way in envoy to achieve that?
>
>I looked at the preconnect option but it seems to only help establish extra connections after the first one and that too only for http1.1. We are using http/2 exclusively.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster-preconnectpolicy

**Comment by snowp** [comment]
@alyssawilk do you know if we have a good mechanism here? I vaguely recall that we have some prefetching in place but not sure about the specifics

**Comment by nitgoy** [comment]
@alyssawilk can you consider adding such an option to either the preconnect policy or via a separate config?

**Comment by alyssawilk** [comment]
@nitgoy I'm booked up with work for my day job so I think you'd have to find someone else to pick this up.

@lambdai I think we could do a first pass config-validating that it wasn't set up for those corner cases.   A more ambitious implementation would involve allowing prefetching and applying those things (writing proxy protocol, applying socket options) once the connection was matched.
