### ISSUE TITLE
Prepared Clusters

### ISSUE THREAD

**Issue by sefaphlvn** [envoyproxy/envoy#21350]
Hi all,

Do unused clusters cause a problem? 
I want to keep a prepared cluster for APM(skywalking). I want to use cluster if APM is enabled.

**Comment by snowp** [comment]
In general having extra clusters should be fine, there might be minimal memory overhead being introduced but if its completely unused this should be minimal. Even if you enable active health checking it should be operating in a low overhead mode until used
