### ISSUE TITLE
Question: Cross compile for ARM

### ISSUE THREAD

**Issue by jojimt** [envoyproxy/envoy#21367]
I am running into https://github.com/envoyproxy/envoy/issues/15235 and would like rebuild with tcmalloc=gperftools for arm64 as recommended in the issue. However, I am unable to find instructions for building the binary for arm and then rolling it into a docker image. Any pointers/help on this?

**Comment by phlax** [comment]
hi @jojimt not sure about cross compiling envoy itself - in CI we use an ARM machine to build the binary and then use buildx to cross-compile just the containers

there is an arm build container here https://hub.docker.com/r/envoyproxy/envoy-build-ubuntu/tags so using the build container the steps would be pretty similar - eg

```console
$ ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
```

as the binary is builting statically it should be possible to drop it into any container image with the correct version of glibc

**Comment by jojimt** [comment]
Thanks @phlax. I was able to do that on an Arm machine and successfully build the docker image with the change.
