### ISSUE TITLE
FR: downstream http1 protocol setting in HCM to add "connection close" upon upstream connect failure

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#21365]
It aligns with the abstractation that envoy acts as an *inbound* proxy

A*inbound* proxy is a server sidecar-ish proxy that does not applying LB because there is only one upstream endpoint, e.g. an original_dst cluster

**Comment by htuch** [comment]
What's the current behavior @lambdai? Does a more general behavior where we reflect upstream status to downstream make sense in some of these narrower cases (maybe also dynamic forward?). CC @alyssawilk @yanavlasov for guidance.

**Comment by alyssawilk** [comment]
Generally Envoy preserves the downstream connection as it can be reused for subsequent requests.  The HCM will send connection close (which is http/1.1. specific) if the connection can not be reused - client specified connection close, connection is "corrupt" (not fully drained, failed upgrade etc.).   I think sending close on the narrow case of not fetching upstream connection and downstream HTTP/1.1 feels specific enough I'd prefer we do it in a filter, and instead give some way for filters to inform the HCM to close the connection iff downstream is HTTP/1.1

**Comment by lambdai** [comment]
To rephrase: it's nice to have some publish some signal to the downstream, either via metadata, error details, etc. It should not citizen because only it is consumed in http1.1. Correct? @alyssawilk

**Comment by lambdai** [comment]
> and instead give some way for filters to inform the HCM to close the connection iff downstream is HTTP/1.1

Am I understanding you correctly? 
1. HCM is the only executor to add "connection: close" on http1.1
2. HCM should expose the api for a http filter to notify a "connection: close" is desired
3. The rule to produce the notification should live in http filter, not in core HCM config.

**Comment by kyessenov** [comment]
To provide more background - this is coming from a use case where the client to Envoy treats HTTP connection closure as something more than request failure (which have its meaning in HTTP) - it tries to re-resolve DNS in client SDK. So while if you think of HTTP correctness either way is fine, for the higher SDK-level behavior they expect one certain HTTP way.

**Comment by alyssawilk** [comment]
@lambdai Yep, that sums up my opinion (though I'm not fixed on it so you're welcome to debate or ask Matt/Snow for a second opinion)
