### ISSUE TITLE
oghttp2 doesn't handle classic connect requests

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#21386]
:method CONNECT
:authority host:80

appears to bounce

Semi-blocking https://github.com/envoyproxy/envoy/issues/20378

**Comment by alyssawilk** [comment]
also if you want a terrible repro patch, you can take https://github.com/envoyproxy/envoy/compare/main...alyssawilk:extended?expand=1 and comment out the force-override to nghttp2

**Comment by birenroy** [comment]
Okay, support for "classic" CONNECT is in upstream QUICHE now:
  https://github.com/google/quiche/commit/4e85f2ae9800295c076ff231984ab12befc1435a

**Comment by alyssawilk** [comment]
still getting "Violation in HTTP messaging rule"
Are you sure this patch addresses the fact that CONNECT requests don't need to have path and scheme?

**Comment by birenroy** [comment]
Alright, please try the latest commit:
  https://github.com/google/quiche/commit/0eae705e30cb1999753523cd4809e049e1a62572
