### ISSUE TITLE
Envoy Proxy as Redis Proxy, how to authenticate?

### ISSUE THREAD

**Issue by mukundv18** [envoyproxy/envoy#21389]
*Title*: *The password passed via Redis Client has to be passed as Bearer token to external authorisation service OPA. Is it possible? If yes, how?*

*Description*:
We are using Envoy Proxy as Proxy for Redis. All the communication to Redis is via Envoy proxy. 
When using 'redis-cli', we send the password with '-a' option. Is it possible send this as Bearer token to OPA (used for external authorisation) to be validated against an AD?

**Comment by htuch** [comment]
@yanavlasov you've been looking at this filter recently, any thoughts? @weisisea as CODEOWNER.
