### ISSUE TITLE
configs/examples: convert all to v2

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2139]

**Comment by mattklein123** [comment]
Note: We should leave all the v1 configs around for reference/posterity/testing until we kill v1, but should convert them all to v2 for reference/testing.

**Comment by derekargueta** [comment]
@mattklein123 I'd be happy to work on this. Since the V2 examples can be expressed in various ways - static config, semi-static, or completely dynamic with either streaming JSON or gRPC, is there any preference on what examples to demonstrate?

**Comment by mattklein123** [comment]
@derekargueta awesome! Really appreciate the help. TBH, I would start by just converting the existing v1 examples that we have to v2 as-is, then we can look at adding new ones. The existing examples are:
https://github.com/envoyproxy/envoy/tree/master/configs
https://github.com/envoyproxy/envoy/tree/master/examples

The goal I think would be to convert them all to YAML and lose the JSON.

**Comment by srikailash** [comment]
@mattklein123, I would like to work on this. Feel free to assign this to me. Thanks!

**Comment by mattklein123** [comment]
@srikailash thank you!!!

**Comment by srikailash** [comment]
@mattklein123, regarding migrating examples(https://github.com/envoyproxy/envoy/tree/master/examples). I see that all the examples are migrated here (https://github.com/envoyproxy/envoy/pull/2286). Should i just clean-up by removing the deprecated files? Thanks!

**Comment by mattklein123** [comment]
@srikailash these configs remain: https://github.com/envoyproxy/envoy/tree/master/configs

We should convert them to v2 YAML.

**Comment by srikailash** [comment]
@mattklein123 , sorry for the very late reply.(been busy last week)
Is the idea to get rid of all the template json files and modify configgen?
Thanks!

**Comment by mattklein123** [comment]
@srikailash the idea is to convert the templates into v2 YAML, and then modify configgen/jinja to create v2 YAML configurations.

**Comment by srikailash** [comment]
@mattklein123, ack. Thanks!

**Comment by srikailash** [comment]
@mattklein123, mind having a quick look at this commit (https://github.com/srikailash/envoy/commit/02f2f6d2612e342c4fdc642c255a414cb7c2f908). Will submit a PR after a bit of clean up and will have to add yaml files for other configs(envoy_double_proxy and envoy_service_to_service) . Thanks!

**Comment by mattklein123** [comment]
@srikailash looks close enough to do a full PR. Thank you!!!

**Comment by mattklein123** [comment]
This is in progress.

**Comment by mattklein123** [comment]
@srikailash do you still plan on finishing this? I would love to get this done so really appreciate the effort.

**Comment by srikailash** [comment]
@mattklein123, was busy over last weeks. Sorry for the delay. Yes, i still plan to finish this, there are some final checks left in my PR. Will reopen this week.

**Comment by mattklein123** [comment]
Done!
