### ISSUE TITLE
listener ecds: reject the connection directly instead of using a fake listener filter

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#21427]
see the discussion here https://github.com/envoyproxy/envoy/pull/21133#discussion_r867488644

current implementation is using a `MissingConfigTcpListenerFilter` to reject the connection https://github.com/envoyproxy/envoy/pull/21133/files/9f2b442e8c90cf1e426917ed4de8d3f303eff90f#diff-998fda72180293e9c2eaf07d3ead906aba6998220cbcd9f10f63bc283f5c6119R41

but it seems overcomplex, we should be able to reject the connection directly.

**Comment by htuch** [comment]
@kyessenov @adisuissa should this just be fixed in https://github.com/envoyproxy/envoy/pull/21133 or does it make sense to fix after merge?

**Comment by adisuissa** [comment]
I would suggest decoupling it from #21133 for a couple of reasons:
1. This is similar to how HttpFilter works (see [`MissingConfigFilter`](https://github.com/envoyproxy/envoy/blob/cf840b8c4822a692184e3df471df89e4973e72fb/source/extensions/filters/network/http_connection_manager/config.cc#L87)).
2. Early return in [`buildFilterChain`](https://github.com/envoyproxy/envoy/pull/21133/files/9f2b442e8c90cf1e426917ed4de8d3f303eff90f#diff-998fda72180293e9c2eaf07d3ead906aba6998220cbcd9f10f63bc283f5c6119R75) stack may be more riskier (haven't considered the implications entirely).

**Comment by soulxu** [comment]
I'm a little prefer to fix in #21133 in the beginning, but I agree with what @adisuissa suggested here, and happy to help on this.

**Comment by soulxu** [comment]
> @soulxu Are you proposing adding an if check below:
> 
> https://github.com/envoyproxy/envoy/blob/253c5c554b82250ddac19709af3e80c264977f4f/source/server/active_stream_listener_base.h#L87
> 
> Something like:
> 
> if (false == config_->filterChainFactory().createListenerFilterChain(*active_socket) ) { active_socket->socket().ioHandle().close(); // close the socket return; }

Yes, that is what I'm thinking
