### ISSUE TITLE
`manager_` could be a dangling reference when Envoy shuts down

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#21447]
Thank @JuniorHsu for reporting a crash.

`manager_` could be a dangling reference when Envoy shuts down

_Originally posted by @lambdai in https://github.com/envoyproxy/envoy/pull/19971#discussion_r882135365_

**Comment by JuniorHsu** [comment]
this occurs again.

**Comment by kyessenov** [comment]
This is quite convoluted. I think the remaining bit of information missing is https://github.com/envoyproxy/envoy/pull/14954. That PR modified the destructor of `ClusterInfo` which owns the last SSL socket context to be dispatched and deleted on the main thread. So it should be easy to delay `manager_` destruction after `dispatcher_` to fix this crash.
