### ISSUE TITLE
Envoy %GRPC_STATUS_NUMBER% got String instead of Number

### ISSUE THREAD

**Issue by mrnonz** [envoyproxy/envoy#21454]
Hi, I have use Envoy with custom logging with `%GRPC_STATUS_NUMBER%` but I got String instead of Number

*Config*
```json
"status_code": "%GRPC_STATUS_NUMBER%",
```

*Result*
```json
"status_code": "OK",
```

**Comment by daixiang0** [comment]
Could you share which version of Envoy you use?

**Comment by mrnonz** [comment]
@daixiang0 I use this version

`envoy  version: 4ce93dc3ace00ae9108b179d0afaceac13f4602a/1.17.4/Modified/RELEASE/BoringSSL`

I think this my misunderstand; I think if this command operator not set will be error instead of return the main string. I will try to upgrade envoy to >= `1.22.0` since command operator ``%GRPC_STATUS_NUMBER%`` added.

Thank you

**Comment by daixiang0** [comment]
Sure, you are welcome, hope it helps you.
