### ISSUE TITLE
CI always fail when add new extension 

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#21467]
*Title*: *CI always fail when add new extension *

*Description*:
#21126 delete tools/extensions/extensions_check.py, but CI image does not update, it makes CI always fail, e.g. https://dev.azure.com/cncf/envoy/_build/results?buildId=109375&view=logs&j=c5dd2866-6ab3-5f3c-3a44-4cef0ec909b5&t=a9eb66d6-8944-5769-b3f7-476949dadcb8&l=61

**Comment by phlax** [comment]
@daixiang0 i dont believe that this is related to the build image - i think you need to merge main

**Comment by phlax** [comment]
closing this as i think this was a misdiagnosis of the problem - please reopen if you believe there is actually still a problem and we can investigate

**Comment by daixiang0** [comment]
Thanks for help!
