### ISSUE TITLE
Missing integration tests for listener filter matcher functionality

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#21484]
*Title*: Missing integration tests for listener filter matcher functionality

*Description*:
It looks to me there is no integration tests to verify listener filter matcher functionality.  i.e, if there is configuration in ListenerFilterChainMatchPredicate filter_disabled in listener filter:

https://github.com/envoyproxy/envoy/blob/2382e041ef1b63aff5de767f0af570b7dfb00e8c/api/envoy/config/listener/v3/listener_components.proto#L367

https://github.com/envoyproxy/envoy/blob/2382e041ef1b63aff5de767f0af570b7dfb00e8c/source/server/listener_manager_impl.cc#L132

[optional *Relevant Links*:]

**Comment by kyessenov** [comment]
There's this https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc#L40.

**Comment by yanjunxiang-google** [comment]
> There's this https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc#L40.

Cool, thanks for the info. Let me close this issue.
