### ISSUE TITLE
Provide an envoy binary package based on RPM and Ubuntu instances for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [envoyproxy/envoy#21503]
I am trying to install envoy on the arm64 platform using [this](https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-ubuntu-linux) document, but it is failing. On using the command ``` sudo apt install -y getenvoy-envoy``` it displays the error ```E: Unable to locate package getenvoy-envoy```.  It looks like the envoy binary is not available for the arm64 platform. It will be useful if we have a envoy binary for the arm64 platform. 

If interested, we can get access to ARM H/W through [WorksOnArm](https://github.com/WorksOnArm).

**Comment by phlax** [comment]
hi @odidev this has been an outstanding issue for a while (there are few related existing tickets)

we recenty made some progress here and now have debs (with the static Envoy binary)  built/tested in CI - for both x86_64  and arm64

the next steps are adding rpm support and hooking up the website to start publishing the builds

**Comment by odidev** [comment]
Sounds good. Can you please provide some possible dates when you are going to release the arm64 binary?

**Comment by phlax** [comment]
at this point, not sure about exact dates

at this point Envoy CI is building and testing the binaries so I guess before we start publishing these officially it would be good to start testing them

i can add a PR that adds the first part of the publishing pipeline in the next few days - once that is in place it should be possible to download the debs and test them with `dpkg -i`

in terms of rpms i have tried a couple of approaches - one based on `rules_pkg` and another (more hermetic) build based on https://github.com/google/rpmpack

i havent tested in a while but `rules_pkg` has been developed quite a bit so i want to look again at it (this is what is being used to package debs)

any help testing or progressing this would be greatly appreciated

**Comment by odidev** [comment]
It’s good to know that you have already made some progress. It would be nice if PR was available. I will try to contribute from my side.

**Comment by odidev** [comment]
Any updates on this?

**Comment by phlax** [comment]
not as yet, ive been busy with other things, but its v much on my todo list

**Comment by odidev** [comment]
I understand, let me know if I can help when you are ready

**Comment by JCzz** [comment]
Any news on this?

**Comment by odidev** [comment]
Hi Team,

Adding a gentle reminder to take a look at the above issue.

**Comment by phlax** [comment]
hi see [#16867 ](https://github.com/envoyproxy/envoy/issues/16867#issuecomment-1280908059) for further info
