### ISSUE TITLE
`total_listeners_warming` stats set to 0 when listeners are still warming

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#21520]
*Title*: `total_listeners_warming` stats set to 0 when listeners are still warming

*Description*:
We saw a case where incomplete RDS response leads to listeners warming. However, the `total_listeners_warming` shows 0 still.

Configs attached below

[server_info.txt](https://github.com/envoyproxy/envoy/files/8809530/server_info.txt)
[stats.txt](https://github.com/envoyproxy/envoy/files/8809531/stats.txt)
[config_dump.txt](https://github.com/envoyproxy/envoy/files/8809532/config_dump.txt)

This was easily reproducible for us by simply truncating an RDS response

**Comment by KBaichoo** [comment]
cc @kyessenov @adisuissa

**Comment by lambdai** [comment]
```
 "state": "INITIALIZING",
```

I remember that is a minor bug during server starts.

**Comment by mattklein123** [comment]
Do you have a repro for this? It's hard to say what is going on here.

**Comment by howardjohn** [comment]
I was able to simply not send all the requested routes (just did something like `routes = routes[:1]` in our control plane). I can get a more minimal repro in a bit.

Note this is with Istio config so we have the bind_to_port=false listeners
