### ISSUE TITLE
Envoy forward proxy authentication with NTLM

### ISSUE THREAD

**Issue by rohrit** [envoyproxy/envoy#21543]
*Title*: *Envoy forward proxy authentication with NTLM*

*Description*:
This is a question as to whether someone has tried proxy authentication with NTLM as described at https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-grvhenc/b9e676e7-e787-4020-9840-7cfe7c76044a 

Nginx has support in its plus offering and through OSS (https://github.com/gabihodoroaga/nginx-ntlm-module#:~:text=The%20NTLM%20module%20allows%20proxying,Negotiate%22%20or%20%22NTLM%22). I am trying to figure out whether similar is possible with Envoy.

**Comment by KBaichoo** [comment]
cc @wrowe

**Comment by kyessenov** [comment]
Note this clause:
> The upstream connection is bound to the client connection once the client sends a request with the "Authorization" header field value starting with "Negotiate" or "NTLM".

Proxying NTLM implies some solution to https://github.com/envoyproxy/envoy/issues/19458

**Comment by rohrit** [comment]
I have updated the link to the MS doc with the relevant one in the original description

**Comment by rohrit** [comment]
> Note this clause:
> 
> > The upstream connection is bound to the client connection once the client sends a request with the "Authorization" header field value starting with "Negotiate" or "NTLM".
> 
> Proxying NTLM implies some solution to #19458

Please see https://web.archive.org/web/20200724074947/https://www.innovation.ch/personal/ronald/ntlm.html as well.

**Comment by rohrit** [comment]
Just to confirm, it looks like this would not work till https://github.com/envoyproxy/envoy/issues/19458 gets fixed.

**Comment by kyessenov** [comment]
@rohrit Yes, we need a way to support something like #19458. I think the consensus is that it should be _doable_ in dedicated filters, but not necessarily supported out of the box.

**Comment by wrowe** [comment]
Not envoy.filters.http.ext_authz - that already works for HTTP auth. NTLM isn't HTTP, it changes an HTTP connection to be stateful. HTTP is not stateful across requests, it would need to be a connection level filter as described in the associated issues

**Comment by wrowe** [comment]
See also https://github.com/envoyproxy/envoy/issues/12370

**Comment by rohrit** [comment]
The authentication would need to work in context of a HTTP CONNECT request which use HCM. (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#connect-support, https://github.com/envoyproxy/envoy/blob/28d4286a22c1db574ce68d0722bf5acea5dc3d05/configs/terminate_http1_connect.yaml). 

It is not quite clear what is needed here as I am not familiar with the internals of Envoy and if there are other options for performing NTLM authentication. Perhaps a new network filter is what was meant then.
