### ISSUE TITLE
uhv: oghttp2: disable header validations based on compile flag

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#21548]
*Title*: uhv: oghttp2: disable header validations based on compile flag

*Description*:
oghttp2 is being adopted in Envoy and has recently add a method of disabling header validations through a configuration setting. Using a compile time `ifdef`, disable H2 header validation within the parsing library when building UHV. This will be very similar to H1. We plan on using the new `validate_http_headers` exposed by the `external_quiche_http2::adapter::OgHttp2Adapter::Options` class, most likely within the [Http2Options](https://github.com/envoyproxy/envoy/blob/b424d3832256d5cd1dae6c7c1e469b82b568d58d/source/common/http/http2/codec_impl.cc#L1966) constructor.

Refs #19751

**Comment by ameily** [comment]
CC @alessandrogario

**Comment by KBaichoo** [comment]
cc @birenroy @yanavlasov

**Comment by birenroy** [comment]
The QUICHE work is done, and my understanding was that @yanavlasov  would handle or delegate the task of hooking up the compile time flag.
