### ISSUE TITLE
CORS Access-Control-Allow-Private-Network

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [envoyproxy/envoy#21553]
*Title*: CORS Access-Control-Allow-Private-Network

*Description*:

Add a new `allow_private_network` option to `config.route.v3.CorsPolicy` that will make Envoy respond requests with the header `Access-Control-Allow-Private-Network: true` when the header `Access-Control-Request-Private-Network: true` is present on OPTIONS requests.

> Chrome is deprecating direct access to private network endpoints from public websites as part of the [Private Network Access](https://wicg.github.io/private-network-access/) (PNA) specification.
> 
> Chrome will start sending a CORS preflight request ahead of any [private network request](https://developer.chrome.com/blog/private-network-access-preflight/#what-is-private-network-access) for a subresource, which asks for explicit permission from the target server. This preflight request will carry a new header, Access-Control-Request-Private-Network: true, and the response to it must carry a corresponding header, Access-Control-Allow-Private-Network: true.

*Relevant Links*:
> https://developer.chrome.com/blog/private-network-access-preflight/

**Comment by KBaichoo** [comment]
cc @daixiang0 @wbpcode

**Comment by daixiang0** [comment]
I will take a look.

**Comment by daixiang0** [comment]
@envoyproxy/envoy-maintainers please close as it is fixed.

**Comment by bruce-c-liu** [comment]
Hi when will this be released?

**Comment by adisuissa** [comment]
> Hi when will this be released?

IIUC this will be part of 1.24.0, and according to the [releases schedule](https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#major-release-schedule) the version should be cut in a couple of weeks.
