### ISSUE TITLE
Is grpc global ratelimit support for  xds *dynamic_resources*  ?

### ISSUE THREAD

**Issue by Neil-Boyle** [envoyproxy/envoy#21624]
*Title*: *Is grpc global ratelimit support for  xds *dynamic_resources*  ?*

*Description*:
listener.filter_chains.filters.http_connection_manager.RouteSpecifier defined as three kind   impl in xds go-controller-plane

type HttpConnectionManager_Rds struct {
	// The connection manager’s route table will be dynamically loaded via the RDS API.
	Rds *Rds `protobuf:"bytes,3,opt,name=rds,proto3,oneof"`
}

type HttpConnectionManager_RouteConfig struct {
	// The route table for the connection manager is static and is specified in this property.
	RouteConfig *v32.RouteConfiguration `protobuf:"bytes,4,opt,name=route_config,json=routeConfig,proto3,oneof"`
}

type HttpConnectionManager_ScopedRoutes struct {
	// A route table will be dynamically assigned to each request based on request attributes
	// (e.g., the value of a header). The "routing scopes" (i.e., route tables) and "scope keys" are
	// specified in this message.
	ScopedRoutes *ScopedRoutes `protobuf:"bytes,31,opt,name=scoped_routes,json=scopedRoutes,proto3,oneof"`
}

in HttpConnectionManager_Rds impl of  **dynamical RDS api,  RateLimits is not support** as there is none VirtualHost define..

differently, HttpConnectionManager_RouteConfig support VirtualHost.RateLimits

it meens envoy don't support  **global ratelimit for  dynamical RDS api?**

any help will be welcome , tks

[*Relevant Links*:]
[ratelimit in envoy virtual host](https://www.envoyproxy.io/docs/envoy/v1.15.2/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit)

[dynamical rds api](https://www.envoyproxy.io/docs/envoy/v1.15.2/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-rds)

**Comment by yanavlasov** [comment]
RDS provides `config.route.v3.RouteConfiguration` which includes both virtual host config and route config where rate limit overrides can be specified.

**Comment by Neil-Boyle** [comment]
> 

in envoy v3 api, config.route.v3.RouteConfiguration is defined by HttpConnectionManager_RouteConfig, I can't find it in HttpConnectionManager_Rds.- =

**Comment by Neil-Boyle** [comment]
> RDS provides `config.route.v3.RouteConfiguration` which includes both virtual host config and route config where rate limit overrides can be specified.

in envoy v3 api, config.route.v3.RouteConfiguration is defined by HttpConnectionManager_RouteConfig, I can't find it in HttpConnectionManager_Rds.- =

**Comment by Neil-Boyle** [comment]
resolved  tks~
