### ISSUE TITLE
Is there a way to override upstream max_X parameters ?

### ISSUE THREAD

**Issue by Dgotlieb** [envoyproxy/envoy#21623]
Hi,

I'm trying to increase the below parameters from 1024 to a higher number.
https://github.com/envoyproxy/envoy/blob/ad7328f407b1016302adebb46305649f60fb6801/source/common/upstream/upstream_impl.cc#L1425-L1427

The way I'm doing it today is modifying the values and rebuilding the docker image.
I wonder if I can simply override this parameters passing arguments to the container or merging my version of `envoy_bootstrap.json` on container start.

Thanks!

**Comment by yanavlasov** [comment]
You can override these values in the circuit breaker configuration: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break

**Comment by Dgotlieb** [comment]
@yanavlasov thanks for your reply
How can it be done on the container? 
I'm not sure if it's important, but I'm using nomad with [`service connect`](https://www.nomadproject.io/docs/job-specification/connect) and could not find how to override it.

Will appreciate a guidance if possible.
Thanks!

**Comment by yanavlasov** [comment]
It should be part of the cluster configuration.
