### ISSUE TITLE
[Question] get namespace and pod info in accesslog

### ISSUE THREAD

**Issue by shuxnhs** [envoyproxy/envoy#21636]
can i append the information of pod and namespace in access log

**Comment by pxpnetworks** [comment]
I think it is possible using the Access Log command operator %ENVIRONMENT(X):Z%

Example:

node_name: %ENVIRONMENT(NODE_NAME)%

and on the k8s deployment define the Env Vars like this:
```
env:
- name: NODE_NAME
valueFrom:
	fieldRef:
	fieldPath: spec.nodeName
- name: POD_NAME
valueFrom:
	fieldRef:
	fieldPath: metadata.name
- name: POD_NAMESPACE
valueFrom:
	fieldRef:
	fieldPath: metadata.namespace
```

**Comment by shuxnhs** [comment]
> ine the Env Vars lik

thanks for your answers but i got ` Not supported field in StreamInfo: ENVIRONMENT(XXX)` on the access log

**Comment by shuxnhs** [comment]
oh，my envoy version is 1.18.3.

**Comment by daixiang0** [comment]
That is reasonable to me, please try a newer version.
