### ISSUE TITLE
[Question] - Build wasm runtime with specific flags/features

### ISSUE THREAD

**Issue by jlb6740** [envoyproxy/envoy#21634]
I would like to build wasmtime with specific flags (for example for perf support). Where would I make modifications to manipulate how  wasmtime is built?

**Comment by jlb6740** [comment]
@yanavlasov thanks!
@kyessenov @PiotrSikora .. Any pointers here. Searching around the codebase and not being nearly familiar enough with how Bazel works it is not clear to me what steps it takes to build a very specific wasmtime (in contrast to say wamr for example where it looks like I could make modifications in bazel/foreign_cc/Build to change that build). Any pointers would be appreciated.

**Comment by jlb6740** [comment]
Thanks @daixiang0 . I saw this file and at first thought this was the place, but I could not see what were obvious build steps here and I also didn't see any means for modifying the Wasmtime build flags through this file. I see now from @PiotrSikora comment that I needed to consider that the build parameters (cargo file) were outside of this project, but that that project in question was indeed listed as a deps here. 

So the process would be to modify the repository_locations.bzl under this project and have it point to my forked proxy-wasm-cpp-host that has the modifications to the Cargo file that in turn modifies the building of Wasmtime. Ok .. thanks!!

**Comment by jlb6740** [comment]
Hi @daixiang0 and @PiotrSikora, an update here:

Wasmtime has the ability to support profiling jitted code using VTune or perf. 
In order to do this you need to (1) build in the support using a feature flag at build time and (2) then at runtime you have to pass another flag to actually turn on the profiling. 
I modified the envoy-private/bazel/external/wasmtime.BUILD file to hopefully support the building of wasmtime with the vtune feature flag like so: 


rust_library(
    name = "rust_c_api",
    srcs = glob(["crates/c-api/src/**/*.rs"]),
    crate_root = "crates/c-api/src/lib.rs",
    crate_type = "staticlib",
    crate_features = ["vtune"],
    edition = "2018",
    proc_macro_deps = [
        "@proxy_wasm_cpp_host//bazel/cargo:wasmtime_c_api_macros",
    ],
    deps = [
        ":helpers_lib",
        "@proxy_wasm_cpp_host//bazel/cargo:anyhow",
        "@proxy_wasm_cpp_host//bazel/cargo:env_logger",
        "@proxy_wasm_cpp_host//bazel/cargo:once_cell",
        "@proxy_wasm_cpp_host//bazel/cargo:wasmtime",
    ],
)

But it is not clear to me where to supply the flag during instantiation wasmtime.  Do you have any pointers? Thanks.

**Comment by PiotrSikora** [comment]
@jlb6740 you need to make this changes in Proxy-Wasm C++ Host repo (see [my previous comment](https://github.com/envoyproxy/envoy/issues/21634#issuecomment-1151790006)).

**Comment by daixiang0** [comment]
@PiotrSikora now do we support adding runtime flag with WASM like below:
```
wasmtime --vtune <my_wasm_file>
```

**Comment by PiotrSikora** [comment]
> @PiotrSikora now do we support adding runtime flag with WASM like below:
> 
> ```
> wasmtime --vtune <my_wasm_file>
> ```

We don't support that... I'm not familiar VTune, but wouldn't that require Envoy to be at least aware of it?
