### ISSUE TITLE
Question: Can we use foreign function `expr_evalute` to check Envoy config?

### ISSUE THREAD

**Issue by rahulanand16nov** [envoyproxy/envoy#21631]
I was looking into tests and came across the following:
https://github.com/envoyproxy/envoy/blob/f8f8628f4ec7cb2dcec92f094ffd4715dcc31dab/test/extensions/filters/http/wasm/test_data/test_cpp.cc#L181-L186

I am not sure what it's exactly doing? Is it just marshaling the string literal into the protobuf? Is it checking if a cluster named `test` exists? Can I do something similar from a wasm module?

**Comment by kyessenov** [comment]
It's sending a CEL expression, which is an xDS proto literal, and then checking that evaluating it returns protobuf bytes. Yes, this is part of Wasm ABI.

**Comment by rahulanand16nov** [comment]
Can you give me an example of a use case?

If I am understanding it correctly, if I send the same expression as above, it will just send back protobuf bytes and it has nothing related to the state of Envoy's configuration? Can I use it to check if a particular cluster entry is present or not?

**Comment by kyessenov** [comment]
Yes, this has absolutely nothing to do with configuration validation. It's just testing that we can evaluate on protos from Wasm. The use case is customizing access logs and telemetry, with fields derived from some protos (like dynamic metadata).

**Comment by kyessenov** [comment]
We use this capability in istio/proxy in this extension https://github.com/istio/proxy/blob/master/extensions/stats/config.proto.

There are sample expressions here https://github.com/istio/proxy/blob/master/testdata/stats/client_config_customized.yaml.tmpl#L20.

This essentially allows creating prometheus stats based on values from the request or configuration resources handling the request.
