### ISSUE TITLE
move AccessLog::RequestInfo to a better namespace

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#2163]
AccessLog::RequestInfo is not used exclusively for logging. It should move to another namespace. Consider Envoy::Network, Envoy::Router, or perhaps a new namespace (e.g. Envoy::Request).

*Relevant Links*:
#2161

**Comment by mattklein123** [comment]
I think this is done.

**Comment by zuercher** [comment]
I don't think this has been done.

https://github.com/envoyproxy/envoy/blob/master/include/envoy/access_log/access_log.h#L68
https://github.com/envoyproxy/envoy/blob/master/source/common/access_log/request_info_impl.h#L11

**Comment by mattklein123** [comment]
Ah. OK. Sorry reopening.
