### ISSUE TITLE
Upstream part of smarter way to pick endpoints for dual-stack IPv4/v6 support

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#21640]
As @mattklein123 said at https://github.com/envoyproxy/envoy/issues/16123#issuecomment-825250584 the issue https://github.com/envoyproxy/envoy/issues/16123 can be separated into two parts: upstream and downstream.

The downstream part is about `Support multiple addresses in the listener` https://github.com/envoyproxy/envoy/issues/11184, and it is under review.

So it is time to look at the upstream part.

A little background here:

With `multiple addresses in listener`, it gets rid of the duplicated listeners. but since people want to choose endpoint smartly (ipv4 request choose ipv4 endpoint, ipv6 request choose ipv6 endpoint), still have to add duplicated config.

* One way is using two duplicated filter chains to choose two duplicated clusters. 
* Another way is using the endpoint metadata to get rid of the duplicated clusters, it is a little improved but still, has two duplicated filter chains. The example config can be referenced here https://github.com/envoyproxy/envoy/pull/19367#issuecomment-1111613214

So I'm thinking there need three things to reach the final goal:
* Choose a correct endpoint
    This still can base on the endpoint metadata, but it needs to set the different metadata based on the downstream connection's IP version automatically. We can extend the HTTP `Set-Metadata filter` https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/set_metadata/v3/set_metadata.proto to support converting some variables (the variables like this https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers) to the metadata. Like a new `%IPVERSION%` variable, then convert that variable to specific metadata. (maybe add a network filter also to support the TCP use case)
* Choose a correct upstream local address
     Since Istio using the `upstream_bind_config` in Cluster (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-bindconfig) to set the upstream local address as 127.0.0.6 for the connection to the App, it will do the same thing for the IPv6 also. So we also need a way to choose the correct upstream local address. We can implement this by adding a new policy to the `upstream_bind_config`, allowing the binding of different local addresses based on the IP version.
* Choose a correct endpoint for the dynamic proxy case or use the DNS name for the endpoint address.
    I think this can be done by the `HappyEyeballConnection`. The `dns_lookup_family` will be set as `ALL` as the `HappyEyeballConnection` requirement https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-enum-config-cluster-v3-cluster-dnslookupfamily
    The `HappyEyeballConnection` will get both ipv4 and ipv6 addresses from the DNS, then we can add a new policy to allow it to choose the address based on the downstream IP version.
    And this PR is on my radar https://github.com/envoyproxy/envoy/pull/21539, we can a new connection provider for it.

Appreciate any feedback and comments on this, let me know whether those proposals are enough for this use-case and correct for this usecase!

**Comment by lambdai** [comment]
My 2 cents:

* downstream metadata
Now that this v4/v6 selection is across protocols on top of TCP, it might worth encode metadata or filter state in listener. 

* upstream bind 
Upstream bind need to be extended to provide multiple bind address for sure. In terms of consuming the new addresses, IMHO it is natual to bind v4 address if the v4 upstream address.

**Comment by howardjohn** [comment]
Not sure how much this is "entire driven by Istio" vs "Istio also had a use case", but IIUC we actually hadn't concluded on whether the correct approach was to ensure v4 downstream goes to v4 upstream or if they are decoupled.

**Comment by soulxu** [comment]
> Not sure how much this is "entire driven by Istio" vs "Istio also had a use case", but IIUC we actually hadn't concluded on whether the correct approach was to ensure v4 downstream goes to v4 upstream or if they are decoupled.

Thanks for the feedback! At least I think I shouldn't move this forward before istio has a conclusion here. 

@jacob-delgado @zhlsunshine probably needs you guys' help to move the discussion on the istio side.

**Comment by jacob-delgado** [comment]
Envoy should allow a way for users to pick what's best for their project. There are other projects besides Istio that may need this capability and each should choose a way that fits their needs. I'm not sure if that's possible or if I just increased the scope by a lot, however.

**Comment by zhlsunshine** [comment]
In my opinion, it will make sense if the solution can help to reduce the consume and improve performance of Envoy for Istio dual stack support.

**Comment by soulxu** [comment]
> Our customers would like a "native ip" solution. IPv4 downstream should go to IPv4 upstream, if possible. Same for IPv6. There is some concern about underlying network issues by proxying across protocols.

I prefer to add a network filter to add metadata, it is generic and can be used for other usecase.

**Comment by soulxu** [comment]
May I get some feedback from you @mattklein123 @ggreenway ? also @RyanTheOptimist for HappyEyeBallConnection, thanks in advance!

**Comment by ggreenway** [comment]
My understanding is that the use case is to support both v4 and v6 downstream and upstream, and use the matching version for the downstream and upstream connection. BUT, don't have two mostly-duplicate listeners and clusters. Is that summary correct?

Assuming it is correct, I'd say that this should be implemented with a downstream filter, as suggested by @soulxu, and subset load balancer in the cluster that has 2 subsets for the two IP versions.

**Comment by soulxu** [comment]
> > My understanding is that the use case is to support both v4 and v6 downstream and upstream, and use the matching version for the downstream and upstream connection. BUT, don't have two mostly-duplicate listeners and clusters. Is that summary correct?

Yes, that is what I said also, thanks!

> 
> I guess this makes sense, though I still wonder why this is really necessary upstream. I get why we need it downstream.
> 

Yes, this is good question. Therea are two cases I can imagine are:
* An Ipv4 Application doesn't support Ipv6 client well
* The Application tracking the clients based on the IP address. The loadbalance will switch the client address randomly between the ipv4 and ipv6 address.

@jacob-delgado append anything if you have.

> > Assuming it is correct, I'd say that this should be implemented with a downstream filter, as suggested by @soulxu, and subset load balancer in the cluster that has 2 subsets for the two IP versions.
> 
> This would work, though I wouldn't be against more first class support in which we have a mode in which we remember the downstream version (I guess this is really the point that we want them to match?), and use that to engage dual stack support for upstream sockets?

I thought the major thing is we need a way to create subset load balance and choose the correct subset. And the dynamic metadata endpoint is a mechanism to generate subset and select the subset in the existing envoy, so we can reuse it. The setting of metadata can be done at the listener directly or by a network filter.

Both their works for this case. If we do that with the listener, then it will be less code change although it core code change. If we do it with a filter, it will be a more generic feature, that can be used in different use cases if people want to select different endpoints based on the downstream variables.

Also note, that item #1 and #3 are for the use case of ipv4-to-ipv4 and ipv6-to-ipv6. Item #2 is used for people who want to bind a specific local address for upstream. For istio, it wants to bind to 127.0.0.6 for ipv4, there should be an Ipv6 address want to bind also, and that should be able to be selected automatically in a specified ipv4 address and a specified ipv6 address.  Otherwise, people still have to create duplicated clusters to bind different local addresses. Item #2 can be thought about separately.

**Comment by jacob-delgado** [comment]
I talked with a respected network solutions architect at F5, here's what he had to say as he understands the topic a lot better than I ever would:

> A primary use-case is for those who support dual-stack with the goal of transitioning from IPv4 to IPv6.  In other words, they eventually want to migrate everything to IPv6, but there are legacy workloads that cannot be lifted.  IPv6 semantics are quite different from IPv4, so it's not as simple as just flipping a switch and getting to IPv6 on clients.  In this use-case, it is desirable to force as much traffic to utilize IPv6 as possible, rather than relying on an essentially arbitrary choice by the mesh.
> 
> As has been mentioned elsewhere, one may also wish to use IPv6 capabilities if the client knows that they are available.  For example, IPv6 header support is considerably more flexible than IPv4.  At some point, one may wish to utilize SRv6 -- for example -- in their system.  This is likely to be uncommon for typical application use-cases, but could be very relevant to Service Providers that are using Kubernetes workloads for value-added-service realization.  Moreover, the route path for IPv6 may differ from IPv4 if the traffic is leaving the cluster.  If the client "knows" this and wishes to take advantage of the path difference (for example, if there are different service available along the two paths), it needs to ensure IPv6 egressing the Pod.  Once again, this is likely to matter more to Service Providers than other consumers, but it is useful in that context.  For example, there is a provider in the real-world that has existing assets outside K8s that are nearly all IPv6-only.  Some K8s workloads are IPv4-only.  There are exposed services outside the cluster that these workloads must reach.
>
> This provider, therefore, provides a stateful DNS46/NAT46 bridge for traffic exiting the cluster.  While useful, it adds considerable complexity.  If the client is IPv6 capable, it can bypass this extra proxied hop, and that is the desired eventual goal for all workloads in that cluster.

**Comment by soulxu** [comment]
@mattklein123 gently ping

**Comment by mattklein123** [comment]
> @mattklein123 gently ping

Sorry what input are you looking for?

**Comment by soulxu** [comment]
> > @mattklein123 gently ping
> 
> Sorry what input are you looking for?

Sorry, both I and @jacob-delgado give some input at above for the reason why people want the ipv4 to ipv4 and ipv6 to ipv6. Do those reasons make sense and are something we want to support?

**Comment by mattklein123** [comment]
> Sorry, both I and @jacob-delgado give some input at above for the reason why people want the ipv4 to ipv4 and ipv6 to ipv6. Do those reasons make sense and are something we want to support?

Kind of? Is there an actual customer that has a use case? I would rather not make changes here unless there is a blocked use case and then I would like to hear more about that specific use case.

**Comment by soulxu** [comment]
> > Sorry, both I and @jacob-delgado give some input at above for the reason why people want the ipv4 to ipv4 and ipv6 to ipv6. Do those reasons make sense and are something we want to support?
> 
> Kind of? Is there an actual customer that has a use case? I would rather not make changes here unless there is a blocked use case and then I would like to hear more about that specific use case.

I believe AspenMesh/F5 has customer wants that, I leave this to @jacob-delgado 

I think I can begin to prepare the item 2, it is a blocker for the dual-stack if people want to choose a local bind ipv4 and ipv6 address for upstream.

**Comment by mattklein123** [comment]
Yes I agree working on (2) makes sense to me and seems independent. For the rest I would prefer to wait until we here about a specific blocked use case? Is that ok?

**Comment by soulxu** [comment]
> Yes I agree working on (2) makes sense to me and seems independent. For the rest I would prefer to wait until we here about a specific blocked use case? Is that ok?

Thanks for all the feedback! that sounds good to me. For the rest, we also can see if @jacob-delgado has more input here.

**Comment by jacob-delgado** [comment]
We've been working lately with large telecommunication companies that have expressed apprehension about an approach that uses IPv4 downstream and IPv6 upstream.

These customers have setup packet captures endpoints both before and after each proxy to understand the behavior of their system (and to look for opportunities to optimize various settings even at the kernel level). Some settings, such things as MTU minimum requirements being 576 for IPv4 and 1280 bytes for IPv6, being different between the two protocols are concerning to them; for instance, what would this mean for buffering at the Recv-Q and Send-Q for Envoy in instances of short-lived, but high bandwidth connections as well as long-lived, but many short transactions connections?

They also aren't strictly using http/h2 for all services, but also need to handle raw TCP and TLS over TCP tunneled connections. There is some concern that it would be difficult for them to troubleshoot end to end connections and optimize for a long-term strategy of deprecating IPv4 within their systems.

However, I also think that this use case may be limited to them and those in this sector as they transition their networks to align with a CNCF ecosystem. That is why I'm suggesting this be user configurable, if possible. To the majority of users, they do not care if their connection is proxied over a different protocol upstream, as long as it works.

**Comment by ggreenway** [comment]
> Yes I agree working on (2) makes sense to me and seems independent. For the rest I would prefer to wait until we here about a specific blocked use case? Is that ok?

It doesn't sound like there's any blocked use-case; it's just that to configure envoy to behave how they want, they would need an ipv4 listener -> ipv4 cluster, and ipv6 listener -> ipv6 cluster. So it sounds like the concern is the doubling of config size. So does it make sense to add a mechanism to avoid the duplicate config for this specific use-case, and is there anything more generally useful from this mechanism?

**Comment by soulxu** [comment]
> > Yes I agree working on (2) makes sense to me and seems independent. For the rest I would prefer to wait until we here about a specific blocked use case? Is that ok?
> 
> It doesn't sound like there's any blocked use-case; it's just that to configure envoy to behave how they want, they would need an ipv4 listener -> ipv4 cluster, and ipv6 listener -> ipv6 cluster. So it sounds like the concern is the doubling of config size. So does it make sense to add a mechanism to avoid the duplicate config for this specific use-case, and is there anything more generally useful from this mechanism?

For the item1, I think it is enough to resolve the @jacob-delgado usecase, since their control plane is istio. The item 3 I added for completion for this case if people want to use it with DNS host name, but I think istio won't need that.

For the item1, as I propose above, we can add a network filter here, it will convert some l4 stream info into dynamic metadata, then people can use that for choosing the endpoint. It seems like a very generic mechanism, and seems can be used in many different use cases.
