### ISSUE TITLE
Gzip example is failing in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#21647]
...not sure why

**Comment by daixiang0** [comment]
Is there a log link for it? I can help take a look.

**Comment by daixiang0** [comment]
Test at local, it works.

**Comment by phlax** [comment]
https://dev.azure.com/cncf/envoy/_build?definitionId=11&_a=summary

**Comment by phlax** [comment]
this issue was introduced with the forwardport of the 1.22.1 patch stack

i have opened a PR to revert the gzip example to unbreak CI, but im concerned that this is flagging an actual real problem, ill test locally

**Comment by phlax** [comment]
testing locally and this appears to pass - not sure why that is different to CI 

im guesing the issue is related to https://github.com/envoyproxy/envoy/commit/d4c39e635603e2f23e1e08ddecf5a5fb5a706338

**Comment by phlax** [comment]
ive added a PR to improve CI debugging so we can see what is happening #21658

**Comment by phlax** [comment]
cc @giantcroc this is the failing error:

```console

> [gzip] Test service: localhost:10000/upload with decompression
ERROR: curl (http://localhost:10000/upload -X POST -i -H Content-Encoding: gzip --data-binary @file.gz)
EXPECTED: decompressed-size: 10485760
RECEIVED:
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 2
decompressed-size: 1138688
server: envoy
date: Fri, 10 Jun 2022 10:52:21 GMT
x-envoy-upstream-service-time: 10

OK


```

**Comment by giantcroc** [comment]
> 

Hi, I also think it is dued to [d4c39e6](https://github.com/envoyproxy/envoy/commit/d4c39e635603e2f23e1e08ddecf5a5fb5a706338), and `decompressed-size: 1138688`  is approximately the size of file.gz * `MaxInflateRatio` , and the result is 1129000.

**Comment by phlax** [comment]
@giantcroc can i assign this to you ? it would be good to get the example back, not sure of the best solution myself

**Comment by giantcroc** [comment]
> 

OK, I can help with it.
