### ISSUE TITLE
release note for v1.22.1/version_history/current is 404

### ISSUE THREAD

**Issue by helight** [envoyproxy/envoy#21650]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/433500/172972100-19f65458-19d5-4790-b51b-4b66796e3971.png">

**Comment by mattklein123** [comment]
Sorry we are having trouble building v22 images. cc @phlax who will look tomorrow.

**Comment by phlax** [comment]
this should be fixed in #21657
