### ISSUE TITLE
Envoy Distroless Image for v1.22.1 isn't released

### ISSUE THREAD

**Issue by dhawani** [envoyproxy/envoy#21652]
Distroless image for version v1.22.1 isn't released. 

The last tag for v1.22-latest is two months old. 
https://hub.docker.com/r/envoyproxy/envoy-distroless/tags

**Comment by phlax** [comment]
yep we are aware thanks for reporting

**Comment by phlax** [comment]
this should be resolved in https://github.com/envoyproxy/envoy/pull/21657
