### ISSUE TITLE
FilterState LifeSpan::Connection lifetime lasts longer than the downstream connection

### ISSUE THREAD

**Issue by tpetkov-VMW** [envoyproxy/envoy#21663]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *FilterState LifeSpan::Connection lifetime lasts longer than the downstream connection*

*Description*:
>After https://github.com/envoyproxy/envoy/commit/3e6aee697f64566cff708d82397ade0fa613bd04 Envoy keeps FilterState data for the combined duration of the downstream and upstream connections.
Internally, we are keeping dynamically created upstream clusters inside FilterState, relying on their cleanup after the downstream connection is closed. With the commit above, we get a circular dependency of the upstream cluster/connection, effectively leaking it.

*Repro steps*:
> Here's an example of our SpecialFilter, that creates a SpecialCluster during runtime
```
Http::FilterHeadersStatus SpecialFilter::decodeHeaders(Http::RequestHeaderMap& /*headers*/,
                                                        bool /*end_stream*/) {
  using Clusters::SpecialCluster;

  auto& cluster_name = route_entry->clusterName();
  auto& fs = decoder_callbacks_->streamInfo().filterState();

  if (fs->hasData<SpecialCluster>(SpecialCluster::ID)) {
    SpecialCluster* cluster = fs->getDataMutable<SpecialCluster>(SpecialCluster::ID);
    cluster->reset(cluster_name);
  } else {
    auto cluster = std::make_shared<SpecialCluster>(cm_, time_source_);
    cluster->reset(cluster_name);
    fs->setData(SpecialCluster::ID, cluster, StreamInfo::FilterState::StateType::Mutable,
                StreamInfo::FilterState::LifeSpan::Connection);
  }

  return Http::FilterHeadersStatus::Continue;
}
```
Now, this issue can have a few categories, so will try to mention all of them below:
Bug: Regression in behavior, documentation points to old expectations
From envoy/stream_info/filter_state.h line 43
```
  // - Connection makes an object survive the entire duration of a connection.
  //   Any stream within this connection can see the same object.
 ```
Question: Is there another recommended way to keep an upstream cluster's lifetime limited by the downstream connection lifetime?
Feature request: If no other solution is present, can we introduce a new LifeSpan value, called DownstreamConnection?

**Comment by kyessenov** [comment]
Hi,

I should start by saying that the fact that the downstream lifespan filter state would be deleted on connection close was not a documented behavior. The invariant is that the filter state is present as long as the connection, but can outlast the connection, for a variety of reasons. If you want a precise lifetime, I suggest subscribing to the filter callbacks (e.g. `onLog` and `onDestroy`) and manually releasing the filter state content. 

A similar issue has come up with the internal redirects. The chosen workaround was to do what I suggested and keeping track of lifecycle callback counts.

**Comment by ppadevski** [comment]
Usually the downstream and upstream connections are decoupled as upstream connections are pooled.

What is the point of LifeSpan::Connection if a random pooled upstream connection can extend an Object lifetime? I am mostly concerned about the new behaviour being ... nondeterministic.

In terms of design, wouldn't it be better if either LifeSpan::Connection behaved as before or a new enum value LifeSpan::DownstreamConnection was implemented so that user code would not have to keep track of anything ... which usually means to either creative copy-pasting, bugs and so on.

**Comment by alyssawilk** [comment]
So agree with https://github.com/envoyproxy/envoy/issues/21663#issuecomment-1152515007  the lifetime was not guaranteed  I think if we changed things in a way that broke downstream usage we'll try to come up with a workaround. :-)

I could imagine either marking state objects which need to be shared, or possibly having a configurable option to revert to the old behavior (so not pool common characteristics) if desired?  I'm not sure which would make more sense but interested in @ggreenway and @mattklein123 thoughts as well.

**Comment by ggreenway** [comment]
I have a non-public filter that is keep certain connection-level metrics that was implemented with Connection lifetime filter state, that depends on it being destructed. It may not have been a documented behavior, but it was at least implicit. I'd personally consider this a bug/regression, although a minor one.

**Comment by ggreenway** [comment]
If you're curious of my exact use-case: I needed a quick-and-dirty way to measure how many requests per connection, as a histogram, happened on each downstream connection. So I had a Connection scoped filter state in an http filter, incremented the count for each request, and committed the histogram value in the destructor. There are other ways to do this; my use case isn't that important (I just needed it for a temporary experiment). But it was a useful mechanism to have available.

**Comment by kyessenov** [comment]
WDYT about adding extra metadata to the filter state to indicate that the object should be shared with the upstream stream info and participate in the hashing decisions? That way we can basically merge parts of #19435 with less config. This also expands to the use case of #21524 but for the filter state.

**Comment by tpetkov-VMW** [comment]
Took the change from your fork, and things look good on our end, thanks for the quick response!
