### ISSUE TITLE
Proposals on OOM prevention for Envoy Redis filter

### ISSUE THREAD

**Issue by weisisea** [envoyproxy/envoy#21667]
[Envoy Redis filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis) is an Envoy filter that can process Redis commands from clients, find the right Redis server in Redis cluster, and send the client requests to that Redis server. In certain cases, Envoy Redis filter could consume large amounts of memory, leading to risk of getting OOM-killed.

We have been looking at the scenarios where Envoy Redis filter can get OOM-killed and exploring solutions to mitigate the risk. Please check out our proposals in the [doc](https://docs.google.com/document/d/1Gvkm7ZILMIajmUjVnPs8ML8es5ch78ZJHEeCkGWqvhw/edit#) and feel free to leave comments/suggestions. Any feedback would be welcome!

Thanks!

**Comment by weisisea** [comment]
@mattklein123 @HenryYYang @msukalski

**Comment by LeonGao91** [comment]
Hi @weisisea , the proposal looks great, curious do you have any patches on this already?

**Comment by weisisea** [comment]
@LeonGao91 Thanks for the interest! We have made some code changes internally but haven't got a chance to contribute them back to Github. Will try finding some time to do that.
