### ISSUE TITLE
Question: Rewrite complex path

### ISSUE THREAD

**Issue by nicolasmanic** [envoyproxy/envoy#21668]
*Title*: *Rewrite complex path*

*Description*:

In my case, one `regex_rewrite` cannot meet my needs since the rewriting part will require some, is it possible to chain multiple rewrites or use a 3rd party system to decide about the new path?

**Comment by zhxie** [comment]
I think it is difficult to complete with existing extensions. Maybe Lua or WASM helps.

**Comment by nicolasmanic** [comment]
Hi @zhxie what do you mean by "difficult to complete with existing extensions"? I have been looking at how to rewrite paths using Lua, but it's not clear to me from the docs even if it is possible.

Here is an example:
Original Path: `https://myservice.org/application/p1-p2-....pN`
I would like to rewrite to something like: `https://myservice.org/application/p1/p2/....pN`

Since the number of pX in the last part of the path is not fixed it's hard to rewrite using a single `regex_rewrite`, maybe I could do it if I could chain multiple `regex_rewrite`.

But I also might have cases where the rewrite is not even possible to do with a regex eg:

`https://myservice.org/application/{some random hash}` -> `https://myservice.org/application/{some other random hash}`

In this scenario, I have do a db lookup and calculate the new hash for the path

**Comment by zhxie** [comment]
Yes. I meant we could not chain `regex_rewrite` exactly.

BTW, if you want to replace some patterns with other strings like in your example, `-` to `/`, it is easy to achieve by `regex_rewrite`. `regex_rewrite` can replace all matched strings to substitutions at once. But if you want replace some random hash to another random hash, I do not think it can be done with `regex_rewrite` currently.

**Comment by nicolasmanic** [comment]
About replacing a path with something random can it be done with external processing filters?

**Comment by zhxie** [comment]
I am not sure if it could be done with other filters. From the doc, I think it can be done with external processing.

**Comment by nicolasmanic** [comment]
Thanks I will give it a shot and report back
