### ISSUE TITLE
consistent hash not work

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#21675]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
consistent hash not work
*Description*:
>Describe the issue.
![1655131738(1)](https://user-images.githubusercontent.com/31508490/173381179-021a8541-5597-4efd-befd-436ff7ccb611.jpg)

![1655131826(1)](https://user-images.githubusercontent.com/31508490/173381366-d6e8946a-7a32-4600-acd7-c73b92ef3bf8.jpg)

![image](https://user-images.githubusercontent.com/31508490/173381470-95d75cce-0b1d-4ea5-a5f3-d6f3ae6c0046.png)

![image](https://user-images.githubusercontent.com/31508490/173381560-b77b45e2-edce-4334-8b1c-4d7f138697bc.png)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Could you provide some more explanation to `consistent hash not work`?

FWIW, weighted clusters and consistent hash load balancing are independent functions. The request matched this route will select a cluster first base on the weight and then select a host base on the hash ring.
