### ISSUE TITLE
how to share data between inbound wasm and outbound wasm？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#21672]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
how to share data between inbound wasm and outbound wasm？

*Description*:
>Describe the issue.
I recieved a request header in inbound wasm and I want to set the same request header in outbound wasm？
how to do this，any code will be thankful、
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
cc @PiotrSikora
