### ISSUE TITLE
Make fault abort message configurable

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#21673]
Currently fault filter when abort is configured aborts requests but also sends a message "fault filter abort" to the client.  Is it possible to customize this message (we want no message to be returned) either via fault filter api or via run time flag?

**Comment by wbpcode** [comment]
May be the local reply can helps? According the disscustion in the #9178, may be we needn't dedicated configuration for fault filter.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply

**Comment by ramaraochavali** [comment]
I see . That makes sense.
