### ISSUE TITLE
Per upstream host stats

### ISSUE THREAD

**Issue by vandyvilla** [envoyproxy/envoy#21685]
*Title*: Is there any way to expose per-host upstream stats

*Description*:
In our deployment, we care a lot about long tail stats, including P99 latency, bad/slow hosts causing frequent timeouts, etc. Currently it seems we only have aggregate upstream stats. I am wondering is there a way to expose per-host upstream stats, which could help us quickly pinpoint the bad/slow hosts. 

More specifically, 1. would this feature require code changes? 2. would this feature be generally useful or beneficial for the community too? If yes, we can contribute back to the community. 3. what is the general guideline for adding this change, e.g., should we follow the way how tagged stats is implemented today? 

Appreciate any feedback or comments!

**Comment by wbpcode** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
The host stats are kept by default and are visible in admin /clusters. AFAIK there is no way to stream those out to the stats sinks; you can only see snapshots on admin.

**Comment by jmarantz** [comment]
I suspect the main reason they were originally designed to be kept separate from stats is that there can be an extremely number of backend hosts in some configurations so the cardinality would stress several aspects of the stats system (memory, cpu overhead). They way they are held in the host system is much lower overhead than other stats.

**Comment by vandyvilla** [comment]
Thanks Joshua. Our upstream is Redis Cluster with no more than 200 master nodes. Would that cause a cardinality problem? If not, is it possible to export those host stats from admin to stats sinks, any pointers on how to achieve this? 

Thanks!

**Comment by jmarantz** [comment]
You would definitely need that to be under API, runtime, or flag-flip control; it would blow out memory for large existing deployments if enabled by default.

if you can find a memory neutral way to conditionalize the stats block in each host to point to real stats that would be ideal. Then you could run Envoy in "export_host_stats" mode but for your use-case it would not be too expensive.

I don't have specific code pointers handy but I suspect source/common/upstream is the place to start looking for how these host-stats get populated. I think @antoniovicente refactored that code to make it even leaner, I'd guess 2 years ago, and he may have a more specific pointer.

**Comment by jmarantz** [comment]
I looked at this again and I think I have a better idea. I think it might not be too hard to have the stats sinks simply iterate through the cluster/hosts hierarchy to enumerate those stats to stats sinks and the /admin endpoint. But I would still only do this if a flag was set.

For the admin /stats endpoint you could enable this by query-param, e.g. `/stats?hosts` though I'm not sure if that's any more convenient than just visiting /clusters. I guess what you mainly want are the stats sinks and it might not be too hard to have a runtime option that toggles inclusion of the host stats.

**Comment by jmarantz** [comment]
Here are some code pointers if you want to try this:
 * envoy/stats/primitive_stats.h - definition of the very low-cost stats held in each host
 * envoy/upstream/host_description.h - ALL_HOST_STATS defines the stats held in each host
 * Upstream::HostDescription::stats().counters() returns a vector of name/value pairs for each counter. Note that the name is not elaborated -- it's just the leaf name of the stat, so it would have to be combined in the sink with the names of the cluster and host to disambiguate.
 * Upstream::HostDescription::stats().gauges() -- same thing but for gauges
 * source/server/server.cc -- contains the code to generate a MetricSnapshot, which is provided to sinks. You'd have to add new elements to MetricSnapshotImpl to hold the name/value pairs, organized by host. Sinks would each have to be modified to read this data.
 * source/extensions/stat_sinks/common/statsd/statsd.cc, function UdpStatsdSink::flush would be an example of one of the sink functions that would have to be modified to include the host-owned gauges and counters in its iteration.

This is a pretty medium-to-large sized project but I think it's not too risky or complicated. The main issue is that you'd want to, at least eventually, make sure that all known sinks behave the same. And the technical challenge is you'd probably want to avoid bloating memory while populating it. For example, you probably want to share the string storage when populating the host metrics into the MetricSnapshotImpl, and have a lazy way of elaborating the cluster/host-name as the sink is generating its output.

I've probably given as much detail as you can digest but why don't you take a look at that and see if you want to go further with this.

**Comment by mattklein123** [comment]
Per @jmarantz the reason this is not done by default is similar to the reason we don't output per-route stats by default. Stats are expensive and can easily blow out your backend TSDB without careful control. 

I think it's fine to have optional output of per host stats, either globally or per cluster, but this cannot be enabled by default.

**Comment by vandyvilla** [comment]
Thanks @jmarantz and @mattklein123 ! I will take a look at the pointers and see if we want to proceed.
