### ISSUE TITLE
Increased functionality for request mirroring

### ISSUE THREAD

**Issue by paul-r-gall** [envoyproxy/envoy#21684]
Increased functionality for Request Mirroring in Envoy.

**Description**:
Currently, it is impossible for mirrored requests to have any custom filter chain code applied to them. For example, suppose that some request is by default routed to cluster `generic_cluster` and shadowed to cluster `debug_cluster`. If the filter chain does any kind of custom business logic that is dependent on cluster name/metadata (header modification, async RPCs, etc), all that business logic will only be run for `generic_cluster`. Similarly, access loggers and related post-response actions will only be taken for the primary cluster. 

Additionally, it's currently the case that large POST requests are just not mirrored at all, due to the need to buffer the entire request before shadowing.

**Questions**:
1. At what point should request mirroring begin? Currently, mirroring only starts when a request has been fully received, which leads to large POSTs being dropped.
2. Should mirrored requests have the option of being access-logged?

**Proposed Improvements**:
1. Every request should be mirrored if the route requests it. This includes large POSTs, which are not currently mirrored at all.
2. Mirrored requests should traverse the filter chain, or at least be able to have arbitrary custom logic (potentially async) applied to them.
3. Mirrored requests should increment upstream connection stats (I believe that this one is already true).

**Comment by paul-r-gall** [comment]
@alyssawilk @mattklein123 @yanavlasov, @AndresGuedez for discussion.

**Comment by wbpcode** [comment]
May be custom cluster filter (upstream network filter) or custom `GenericConnPool` can helps 🤔

**Comment by alyssawilk** [comment]
I think I agree with all of the above except maybe (2) where my intuition says in an ideal world where we have upstream filters, we'd do one pass through downstream logic, and then each request would traverse its own set of upstream filters.

**Comment by AndresGuedez** [comment]
> we'd do one pass through downstream logic, and then each request would traverse its own set of upstream filters.

Agreed, although we can achieve similar behavior by allowing a subset of filters to be configured for the mirror filter chain.

**Comment by alyssawilk** [comment]
FWIW after some discussion with the team on their design constraints, upstream filters aren't sufficient for a couple of reasons.  I'm working with paul on design and will take first pass on reviews.

**Comment by activehigh** [comment]
Has there been any progress on this?
