### ISSUE TITLE
Is there any way to get stats per each sessions? If not, I need your opinion that expose session stats.

### ISSUE THREAD

**Issue by DebugIsNotAnOption** [envoyproxy/envoy#21690]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Is there any way to get stats per each sessions? If not, I need your opinion that expose session stats.

*Description*:
Hello Everyone.
Thank you for your contribution, it is very helpful for everyone.

My company uses Envoy as loadbalencer to distribute TCP/UDP in Telco industry.
Currently, we are considering expose sessions  to 3rd party service for monitoring and troubleshooting.
I think that session will be included:
- 5tuple per each session
- rx/tx packets per each session
- dropped packets per each session

Now, Envoy expose those stats per each Cluster and Listener
However, we need not only above stats what I mentioned before but also Cluster/Listener stats.

Q1. Is there any way to get sessions stats code base? 
 In my experience, a few information regarding sessions what I want is in ActiveSession class(in case of UDP).
Unfortunately, for me, it is encapsulated many class and namespace.  I though that ListenerManager and FilterManager could be re-usable but It is hard to get/expose stats and it is not elegant. Would you please let me know an approach to get stats if it exist?

Q2. If not, I need your opinion that expose session stats.
 I think there must be a reason why the session information was encapsulated. We want to expose stats to the outside, and if you want, we want to contribute the code. I'd like to hear your opinions on exposing session information to the outside, and I'd like to know how to approach it if possible.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
@jmarantz do you have any thoughts here?

**Comment by jmarantz** [comment]
I don't know that much about the data structure support for sessions in Envoy. But if you want to add a new group of stats that will be replicated for each cluster, then it needs to be made optional via API.

Rule of thumb:
 * assume 100 bytes per counter/gauge, more for histograms
 * assume there will be up to 100k clusters in some installations
 * so if you add (say) 100 new stats for each cluster, this will cost 100*100*100k = 1 gigabyte.

In your application you might have a much smaller number of clusters, so it might make sense for you to enable stats detail locally, but you wouldn't want to add that cost to all Envoy users.

There's a somewhat related PR in flight now; should land soon: https://github.com/envoyproxy/envoy/pull/21302

**Comment by mattklein123** [comment]
What is a "session" in this context? Can you illustrate some example stats that you would like to see?
