### ISSUE TITLE
Envoy start problem in example with docker-compose

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#21705]
*Title*: *Envoy start problem in example with docker-compose*

*Description*:

When trying examples with docker-compose locally, Envoy starts with some problems.

![image](https://user-images.githubusercontent.com/23182024/173724341-fe5f7ddb-03e0-48b7-bb57-8ab024290129.png)

![image](https://user-images.githubusercontent.com/23182024/173724373-108b5b6c-00a4-4142-a60b-08b0356ee3f7.png)

**Comment by RyanTheOptimist** [comment]
Screen shots are a bit challenging to read here (no cut-paste). Can you attach the text, and please call out the particular problems that you're seeing so we can route the issue to the right people.

**Comment by StarryVae** [comment]
> thanks, i think it may be some problems of dns, the dns resolution for example service consumes about 75s,  which makes envoy is not fully initialized.

**Comment by RyanTheOptimist** [comment]
Meaning there is a problem with DNS in the environment that your Envoy is running in but that Envoy itself is working correctly? (If so, should we close this issue?)

**Comment by StarryVae** [comment]
> Meaning there is a problem with DNS in the environment that your Envoy is running in but that Envoy itself is working correctly? (If so, should we close this issue?)

i tried to run examples with docker-compose, for example [https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/local_ratelimit.html](url), but envoy startups slow due to the dns resolution for example service, i don't know if it is reasonable.

**Comment by daixiang0** [comment]
Does your environment has a complex DNS setting? If so, Envoy would load all of them for potential use.

**Comment by StarryVae** [comment]
> Does your environment has a complex DNS setting? If so, Envoy would load all of them for potential use.

here is the DNS setting:

search it.org
nameserver 127.0.0.11
options ndots:0

if i remove the `search it.org`, Envoy will start normaly.
