### ISSUE TITLE
Why envoy return with Stream max duration time reached

### ISSUE THREAD

**Issue by highwayliu** [envoyproxy/envoy#21731]
I use envoy as gRPC proxy. And i found some times envoy return Stream max duration time reached
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/39515014/174010256-b021d87f-bcf8-4d1b-a84a-44cfcc69a4fb.png">
Also I use wireshark to debug the process
<img width="1309" alt="企业微信截图_2dd23b48-8522-48f5-871c-8a137320aabf" src="https://user-images.githubusercontent.com/39515014/174024657-6d3a688a-c00b-4b59-8b23-9f7d41e0601e.png">

my config is below

`

static_resources:
  listeners:
  - name: listener_0
    address: 
      socket_address:
        address: 0.0.0.0
        port_value: 9081
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          use_remote_address: true
          common_http_protocol_options:
            max_connection_duration: 3600s
            max_stream_duration: 600s 
          http2_protocol_options:
            max_concurrent_streams: 128
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: grpc_server
                  max_stream_duration: 
                    grpc_timeout_header_max: 15s
                    grpc_timeout_header_offset: 15s
                  retry_policy:
                    retry_on: connect-failure,refused-stream,gateway-error,deadline-exceeded,unavailable
                    num_retries: 3
          http_filters:
          # - name: some.customer.filter
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

          access_log:
          - name: envoy.access_loggers.http_grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "${ACCESS_LOG_PATH}"
              log_format: 
                text_format: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT% \"%REQ(X-REQUEST-ID)%\" \"%UPSTREAM_HOST%\" [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% \"-\" %BYTES_SENT% \"-\" \"%REQ(USER-AGENT)%\" %DURATION% %RESPONSE_DURATION% %BYTES_RECEIVED% %GRPC_STATUS_NUMBER% %RESPONSE_FLAGS% \"%RESPONSE_CODE_DETAILS%\" %CONNECTION_ID%\n"
          request_timeout: 300s
          stream_idle_timeout: 300s
          request_headers_timeout: 15s
      
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: "h2"
            tls_certificates:
              - certificate_chain:
                  filename: /etc/server.pem
                private_key:
                  filename: /etc/server.key
        
                
  clusters:
  - name: grpc_server
    connect_timeout: 10s
    type: STATIC
    lb_policy: ROUND_ROBIN
    circuit_breakers:
      thresholds:
        - max_retries: 20

    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 128
            connection_keepalive:
              interval: 30s
              timeout: 5s
              connection_idle_interval: 300s
    load_assignment:
      cluster_name: grpc_server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ${SERVICE_NAME}
                port_value: ${SERVICE_PORT}
`

**Comment by RyanTheOptimist** [comment]
@mattklein123 any thoughts on who would be good to take a look at this?

**Comment by mattklein123** [comment]
What's the question here? If the stream max duration is reached Envoy will terminate the stream? Please provide more information, a properly formatted config, etc. if you would like more help. Thank you.

**Comment by highwayliu** [comment]
你好，我是刘海伟，QQ 806864128，1310627032，微博 http://weibo.com/1688577641是华南理工09网络工程的学生，你的来信我已收到！请放心！！！
