### ISSUE TITLE
SNI based routing with modified SNI name

### ISSUE THREAD

**Issue by kzorfy** [envoyproxy/envoy#21736]
*Title*: *SNI based routing without TLS termination*

*Use Case*:
When user makes a HTTPS request for DNS name [dd-server_name.kzorfy.com](http://dd-server_name.kzorfy.com/), I need to extract the DNS name from SNI and use to to construct the upstream DNS name [wd-server_name.kzorfy.com](http://wd-server_name.kzorfy.com/). The `server_name` in the DNS name is dynamic in nature and can have different values. I only need to replace `dd` prefix in the DNS name with `wd` prefix and route the request without doing TLS termination in envoy.

I looked at [sni_dynamic_forward_proxy_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter) filter but it doesn't allow modifications to the SNI value. I saw `override_auto_sni_header` option to override SNI value for upstream but it does not support dynamic construction of SNI.

Does anyone know whether this is doable either using any built-in envoy functions or writing our logic in a custom filter. Any leads on this would be appreciated.

**Comment by RyanTheOptimist** [comment]
@ggreenway This might be a bit far afield, but do you have any insight here?

**Comment by ggreenway** [comment]
I don't think there's any way to do this currently, but it makes sense to be able to put logic in the middle to mutate the name. Either you could write a custom filter to do it, or maybe consider adding a way to add the logic with Lua. This kind of thing is a great use case for a small Lua script.

**Comment by kzorfy** [comment]
@ggreenway Lua script is only available as HTTP filter but not at layer 4. Can you providing some starting pointers on how I can add custom filter. It would be great if you can share some examples.

**Comment by ggreenway** [comment]
I would look at source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc. You'll need to make a copy of that with some logic to mutate the SNI name, or you could consider adding an extension point to that filter so that it can include run some specified code to do the mutation.
