### ISSUE TITLE
Unable to build v1.20.3+ on Centos 7 - Failure building wee8

### ISSUE THREAD

**Issue by acarlson0000** [envoyproxy/envoy#21755]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Unable to build v1.20.3+ on Centos 7 - Failure building wee8*

*Description*:
When attempting to build envoy from source on v1.20.3 or v1.20.4 (the latest 2 versions containing security fixes) we recieve a build error:
```
[171/1251] ACTION //:generate_bytecode_builtins_list(//build/toolchain/linux/unbundle:default)
FAILED: gen/builtins-generated/bytecodes-builtins-list.h 
python3 ../../tools/run.py ./bytecode_builtins_list_generator gen/builtins-generated/bytecodes-builtins-list.h
./bytecode_builtins_list_generator: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
Return code is 127
```
When attempting to build v1.20.2, this compiles successfully.

We are using the Centos Docker Build image from https://github.com/envoyproxy/envoy-build-tools/blob/main/build_container/Dockerfile-centos (we are aware of https://github.com/envoyproxy/envoy-build-tools/blob/main/build_container/README.md - as we wrote this README)

We are aware Centos 7 is old, but we would like to support it until its maintenance window expires (and obviously take the latest fixes from Envoy source)

Command to build:
```
git clone https://github.com/envoyproxy/envoy.git
cd envoy
git checkout v1.20.x (in this case, we are doing v1.20.4)
scl enable devtoolset-9 bash
./bazel/setup_clang.sh /opt/llvm
bazel build --config=libc++ -c opt //source/exe:envoy-static
```

Seems a little strange - we can't see any v8/wee8 dependency change between 1.20.2 and 1.20.4 - https://github.com/envoyproxy/envoy/compare/v1.20.2..v1.20.4 (there is some bazel and obviously code/security fixes included) - but given that 1.20.2 produces an artifact and is able to link, but 1.20.3/1.20.4 does not is worrying 

I can provide some extra sandbox debug info if required (as there's a lot of logs output) - but the error can be reproduced reliably from the Centos Build container.

**Comment by acarlson0000** [comment]
We would ideally like to move to the latest and greatest of Envoy - but are currently unable to build that for other reasons (however: don't want to complicate this ticket regarding this issue)

**Comment by RyanTheOptimist** [comment]
@phlax do you happen to have any insight here?

**Comment by phlax** [comment]
nothing immediately - @PiotrSikora may have some idea

**Comment by acarlson0000** [comment]
Hi @PiotrSikora - I was using the container from build-tools in the commit that was relevant to 1.20.2 (which we built and tagged some time back - and I was pulling down v1.20.4 directly into that container to build the latest version).

To confirm: v1.20.2 builds fine in that container, but 1.20.3 / 1.20.4 do not.

Just noticed the LLVM commit on the build-tools repo - I'll give that a go by regenerating the container, thanks!

**Comment by markmsmith** [comment]
@acarlson0000 I think I'm following a similar path to you and hitting the same error with Envoy `1.20.6` and `envoyproxy/envoy-build-centos:2635f3db824bb06340102da51ea7e292133af038`.  
Why did you close this - did you find a solution for building Envoy `1.20.3+` for CentOS 7?

**Comment by markmsmith** [comment]
Thank you very much!  After switching to that version I've finally been able to get a successful build of Envoy 1.20.6 for CentOS 7, after fighting with it for several days.  

For the FIPS build I still had to patch out the Clang version checks [here](https://github.com/envoyproxy/envoy/blob/v1.20.6/bazel/external/boringssl_fips.genrule_cmd#L27-L42), since it fails with 10.0.0 instead of 7.0.1, but something more nuanced could be a future enhancement.

I really appreciate the quick response, this made my week.
