### ISSUE TITLE
When will the v1.22.2 envoy-alpine image be available on Dockerhub?

### ISSUE THREAD

**Issue by shashankram** [envoyproxy/envoy#21758]
When will the v1.22.2 envoy-alpine image be available on Dockerhub? It has been a few days since the release but I can't find the image at https://hub.docker.com/r/envoyproxy/envoy-alpine/tags.

Thanks

**Comment by RyanTheOptimist** [comment]
@mattklein123 Do you know the status of docker images?

**Comment by phlax** [comment]
hi @shashankram alpine was deprecated some time ago and has now been discontinued

i would encourage you to check out the `distroless` image instead

**Comment by shashankram** [comment]
> hi @shashankram alpine was deprecated some time ago and has now been discontinued
> 
> i would encourage you to check out the `distroless` image instead

Thanks for letting me know, I wasn't aware alpine support was dropped!

**Comment by phlax** [comment]
yep @gabrielgiussi for sure! 

perhaps we can also add something about `distroless` also

we desperately need some metadata on our dockerhub pages for this too
