### ISSUE TITLE
Resolve release pipeline issues (1.20.5 post-mortem)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#21768]
### description

we have been hit by an issue on our various release branches of running out of disk space when building the docker images - this then prevents the release from publishing 

#### what failed ?

we were again hit by docker disk space issues on the release branch

#### could it have been prevented ?

yes, but the issue was complicated by the fact that the PR to the release branch passed, but when the PR landed it failed

if we hadn't published the branch when the PR landed and failed we could have resolved the issue

i think the best way to prevent this happening in the future is to automate the tagging/release after a succesful CI run - that way the tagging happens iff the release branch _can_ pass

part of the issue seems to be that what is tested in a PR to what is not exactly the same as what is tested in actual releases - but having said that this _did_ fail postsubmit before/unrelated to the failing tag build

#### do we need to worry about disk space as these seem to be an endemic release issue ?

afaict, not any longer in terms of current `main` - the binaries/images/build are all much smaller so the problem seems to be resolved

that said our current azp ci image uses up most of its space with dotnet and other stuff we are unlikely to ever use - and even if we did we would most likely do so with bazel. It would be great if we could use an underlying image that just had a bit more disk space and didnt have lots of stuff we wont use.

we will need to resolve the diskspace issue for this release (or 1.20.6 at least) and as a precaution ill add the aggressive `rm -rf` patch when i add the patch stack etc for 1.19.x

#### related links

- [release PR](https://github.com/envoyproxy/envoy/pull/21737)
- [failed CI on patch landing](https://dev.azure.com/cncf/envoy/_build/results?buildId=110873)
- [failed CI on release](https://dev.azure.com/cncf/envoy/_build/results?buildId=110874)

**Comment by phlax** [comment]
cc @mattklein123 @lizan

**Comment by mattklein123** [comment]
I agree it would be really nice to fully automate the tagging/release so that it only gets tagged if it actually passes. I'm not sure how to do this though. I think we would probably have to have a manually triggered GH action that somehow does this?

**Comment by phlax** [comment]
i think we could have azp CI trigger a branch tag when it gets far enough through - not sure exactly - but it seems likely - @lizan ?
