### ISSUE TITLE
Release note link broken in release announcement

### ISSUE THREAD

**Issue by ejc3** [envoyproxy/envoy#21764]
https://www.envoyproxy.io/docs/envoy/v1.20.5/version_history/current

![Uploading Screen Shot 2022-06-17 at 9.03.53 PM.png…]()

**Comment by phlax** [comment]
@ejc3 thanks for reporting it seems like we have had another failed release - we are working to prevent this in the future - ill follow up to resolve

**Comment by phlax** [comment]
@ejc3 fyi i added a postmortem here #21768 - we will follow up to resolve early next week

**Comment by phlax** [comment]
this should be resolved now
