### ISSUE TITLE
Adding an extension in dynamic forward proxy config to further process the returned address

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#21760]
*Title*: Adding an extension in dynamic forward proxy config to further process the returned address

*Description*:
After DFP resolves an target and get the address[es], sometimes application may want to further process the address, for example, perform an address conversion for the IPv4 address based on certain network requirement, and return that converted address to DNS cache manager.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by htuch** [comment]
I think this makes sense, CC @envoyproxy/api-shepherds.The idea would be a DFP resolver plugin performs the moral equivalent of what an EDS address resolver would do. Basically, wherever we have a socket address, whether it comes from xDS or is resolved via DNS, we might want an opportunity to apply a local resolver.
