### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [envoyproxy/envoy#21773]
*Title*: *Document supported hardware architectures*

*Description*:
I have checked the documentation but did not find any word about supported architectures - only about supported operating systems.

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know). This kind of information is important for the end-users.

You have an awesome table about prebuilt binaries for different architestures. But that does not mean that other architectures are not supported - at least I did not find this information in the documentation.

Thanks in advance!

**Comment by ggreenway** [comment]
cc @phlax

**Comment by phlax** [comment]
@zamazan4ik thanks for raising this issue - it would be good to clarify any docs that need to be

could you be more specific wrt which docs are not so clear - for the starter/install/example docs i added some info about architectures and compatibility

i would definitely be happy to review any PRs that clarfiied this

**Comment by zamazan4ik** [comment]
Not sure, where exactly will be better to place such description. Maybe somewhere in "Install" section? And their describe which platforms are supported. If you have different support levels for different platforms - describe it too.

**Comment by zamazan4ik** [comment]
Ping

**Comment by zamazan4ik** [comment]
@phlax could you label with "no stalebot" please?
