### ISSUE TITLE
Envoy wraps http response errors

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#21782]
*Title*: Envoy wraps http error response 

*Description*:
I am using an envoy configuration with a gRPC transcoder filter and http route filter. When the upstream server responds with a bad request or any other error response, the response code that passed to the downstream is 503, and envoy logs do not print the original error code and message.
Expected: the envoy proxy will respond to downstream with the original error code and message, or at least log the original error code and message.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
I think log the original error code and message is useful. Could you provide the config here to reproduce?

**Comment by ggreenway** [comment]
cc @qiwzhang @lizan
