### ISSUE TITLE
BLPOP, PIPLINE commands 

### ISSUE THREAD

**Issue by Jacobien1** [envoyproxy/envoy#21783]
I'm currently using Envoy for a project but I came across an Error where the redis client 'Redis-py' crushes at pipeline and also it shows an error at BLPOP are those commands not supported by Envoy?

**Comment by daixiang0** [comment]
Could you share the detailed error log here?

**Comment by Jacobien1** [comment]
> Could you share the detailed error log here?

hey,
redis-cli>> blpop list1 list2 list3 
command is not supported

**Comment by ggreenway** [comment]
cc @msukalski @henryyyang @mattklein123 @weisisea

**Comment by Jacobien1** [comment]
can you add the missing commands?

**Comment by daixiang0** [comment]
PIPLINE is not really a command in Redis, see https://redis.io/docs/manual/pipelining/. Now Envoy support it see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis#supported-commands:
> At the protocol level, pipelines are supported. MULTI (transaction block) is not. Use pipelining wherever possible for the best performance.

Now we support commands that can be reliably hashed to a server. Since we support LPOP and BLPOP is a blocking version for it(https://redis.io/commands/blpop/), seems we can support it as well.

I create #21843 for this.

**Comment by daixiang0** [comment]
@Jacobien1 do you use BLPOP with the block indefinitely(zero timeout)?

**Comment by Jacobien1** [comment]
Hello, sorry for the late response, I use it with  timeout and without zero timeout

**Comment by daixiang0** [comment]
@Jacobien1 for now you need to build it at local, then modify Dockerfile-proxy in redis example like below:
```
FROM envoyproxy/envoy-dev:latest

COPY ./envoy.yaml /etc/envoy.yaml
RUN chmod go+r /etc/envoy.yaml

COPY ./envoy /usr/local/bin/envoy
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "proxy"]
```
Then you can run via `docker-compose build && docker compose up` to try.

**Comment by Jacobien1** [comment]
@daixiang0 that's the problem I'm facing to build it locally, the documentation is vague and I don't know how to build an image locally

**Comment by daixiang0** [comment]
Just replace binary in envoyproxy/envoy:latest is enough for tests.

**Comment by Jacobien1** [comment]
@ggreenway I did but I have the following error, do you know why?
![image](https://user-images.githubusercontent.com/38212679/176117619-733d41fa-aed9-4084-acb9-54b47c4e968e.png)

**Comment by daixiang0** [comment]
Never met, here is my log:
```
root:[redis]$ pwd
/github/envoy/examples/redis
root:[redis]$ git diff
diff --git a/examples/redis/Dockerfile-proxy b/examples/redis/Dockerfile-proxy
index c2474f3dc8..30374eb465 100644
--- a/examples/redis/Dockerfile-proxy
+++ b/examples/redis/Dockerfile-proxy
@@ -2,4 +2,5 @@ FROM envoyproxy/envoy-dev:latest

 COPY ./envoy.yaml /etc/envoy.yaml
 RUN chmod go+r /etc/envoy.yaml
+COPY ./envoy /usr/local/bin/envoy
 CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "proxy"]
root:[redis]$ cp ../../linux/amd64/build_envoy_release/envoy ./
root:[redis]$ docker-compose build
Building proxy
Sending build context to Docker daemon  427.2MB
Step 1/5 : FROM envoyproxy/envoy-dev:latest
 ---> eb3b89d358ab
Step 2/5 : COPY ./envoy.yaml /etc/envoy.yaml
 ---> Using cache
 ---> 984da59a0d09
Step 3/5 : RUN chmod go+r /etc/envoy.yaml
 ---> Using cache
 ---> fdc3da0e1826
Step 4/5 : COPY ./envoy /usr/local/bin/envoy
 ---> 7cd9e2f35706
Step 5/5 : CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-clu                                                   ster", "proxy"]
 ---> Running in 2514a166f429
Removing intermediate container 2514a166f429
 ---> ca531c2e623c
Successfully built ca531c2e623c
Successfully tagged redis_proxy:latest
Building redis
Sending build context to Docker daemon  427.2MB
Step 1/1 : FROM redis
 ---> aa4d65e670d6
Successfully built aa4d65e670d6
Successfully tagged redis_redis:latest
```

**Comment by Jacobien1** [comment]
AHHH so I have to build a binary first

**Comment by Jacobien1** [comment]
@daixiang0 sorry for bothering, is there anyway to build the binary without making the tests, it looks like it takes a long time to build one

**Comment by Jacobien1** [comment]
@daixiang0 the blpop works more or less well in my case, I have only one issue and you are the only one who may help. I need to have to work the transaction mode in redis, I found out that for the transaction mode I need 4 commands multi, exec, discard, watch can you tell me or help on where to add those commands to have the transaction mode

**Comment by daixiang0** [comment]
Please check https://github.com/envoyproxy/envoy/pull/21843
