### ISSUE TITLE
Expose dispatcher queue length

### ISSUE THREAD

**Issue by mrice32** [envoyproxy/envoy#2178]
*Title*: Expose dispatcher queue length.

*Description*:
It would be nice to be able to understand the dispatcher's internal event queue by being able to query the length of the list.  The context is that we (at Google) have some internal interfaces for dispatcher-like objects, and we need this piece of information to expose for those interfaces.  We would like to be able to wrap the dispatcher in this interface so internal libraries that are used inside filters, for instance, can publish events to Envoy's dispatcher.  cc @htuch

**Comment by mattklein123** [comment]
There is `event_base_foreach_event()` (http://www.wangafu.net/~nickm/libevent-book/Ref3_eventloop.html), but that's probably not very efficient. Not sure if there is something better. This might require a small patch to libevent to do efficiently.

**Comment by mrice32** [comment]
Would this give us what we want more directly: http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/event_8h.html#afcbf68a9eaf33ff684c01e26e25c0d7d ?

**Comment by mattklein123** [comment]
Yeah that looks about correct. I would quickly look at the code just to see if it is doing a full count or referencing some variable. Not sure of perf implications.

**Comment by mrice32** [comment]
See https://github.com/libevent/libevent/blob/release-2.1.8-stable/event.c#L1251 .  It does acquire the base lock (as most libevent methods do), but other than that, it's just reading existing count variables.

**Comment by mrice32** [comment]
Closing because this is no longer a requirement for us, and it doesn't seem like anyone else needs it, either.
