### ISSUE TITLE
gRPC-JSON transcoder returns text/plain for transcoding error

### ISSUE THREAD

**Issue by michaljemala** [envoyproxy/envoy#21791]
*Title*: *gRPC-JSON transcoder returns text/plain for transcoding error*

*Description*:

Our APIs use enumerations heavily. If an invalid enum value is sent the gRPC-JSON transcoder returns 400 - Bad request using MIME type `text/plain` which is completely fine. However, we would like to also have an option to tell the transcoder to returned these error using the gRPC error JSON structure using the `application/json` MIME type, i.e.:

```json
{
  "code": 0,
  "message": "string",
  "details": [...]
}
```
The reason for this is to provide unified error handling to our clients.

**Comment by daixiang0** [comment]
Is `convert_grpc_status` helpful, like https://stackoverflow.com/questions/61962716/how-to-send-error-response-as-json-in-grpc-using-envoy-proxy?

**Comment by michaljemala** [comment]
`convert_grpc_status` does not help in this case as it translates from headers returned from upstream. In the case I describe the upstream is not reached at all.
