### ISSUE TITLE
`resultstore`/BEP streaming events are timing out in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#21797]
As suspected some `resultstore` events are timing out:

https://dev.azure.com/cncf/envoy/_build/results?buildId=111023&view=logs&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c&l=526

now that we know that this is an issue - since we added #21775 - we will need to figure out what to about it - perhaps revert for now - i dont see a way to make this warning only

related:

- https://github.com/google/resultstoreui/issues/84
- https://github.com/google/resultstoreui/issues/85

**Comment by phlax** [comment]
cc @lizan @alyssawilk

**Comment by alyssawilk** [comment]
Sorry, when you say revert it, do you mean resultstore use or the timeout?  I think having a timeout is fine.  If it's not respected and it's still breaking CI I can go ask resultstore devs to help investigate.

**Comment by phlax** [comment]
https://source.cloud.google.com/results/invocations/0544fabd-21fd-46b7-b7d6-65cd907d72b0/targets
