### ISSUE TITLE
With the oauth2 filter, forward_bearer_token combined with large tokens easily blows most default max-header-size

### ISSUE THREAD

**Issue by Stono** [envoyproxy/envoy#21819]
*Title*: Ability to be specific about which tokens are returned from the oauth2 filter

I'm currently trying to replace our nginx -> oauth2-proxy setup with just using envoy (istio) directly.  I managed to get this working using `type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2`, however I do need access to the original token.

`forward_bearer_token` does that (adds the token to the `Authorization` header, but it also adds the token to the cookie, as well as the idToken and the refresh token.

Unfortunately, our tokens are pretty large (they contain all of a users groups for example, and some other bits of permissions).  Subsequently the duplication in the cookies and the `Authorization` header easily blows our default max-http-header size configuration.  Now we can increase that value (with some risk obviously) but ideally i'd really like to be able to configure what gets returned, rather than everything.

So to be clear, we see:

- Cookie: BearerToken, RefreshToken, idToken
- Header: Authorization: BearerToken

We actually only want the Authorization header, so perhaps some configuration to be a bit more fine grained than just `forward_bearer_token`.

I did find a couple of related issues:

- https://github.com/envoyproxy/envoy/pull/18353 - seems to be the original implementation
- https://github.com/envoyproxy/envoy/issues/15489 - was the original request (around asking for some configuration to add more configuration options).

I did try to "work around" the issue by adding a lua filter after the oauth2 filter to strip out the cookies i wasn't interested in:

```
              local function startswith(source, partial)
                return source:find('^' .. partial) ~= nil
              end

              function envoy_on_response(response_handle)
                print("handling response 2")
                local headers = response_handle:headers()
                local cookies = {}
                for key, value in pairs(headers) do
                  if key == "set-cookie" then
                    if (not (startswith(value, "BearerToken") or startswith(value, "IdToken") or startswith(value, "RefreshToken"))) then
                      cookies[#cookies + 1] = value
                    end
                  end
                end

                response_handle:headers():remove("set-cookie")

                for _, cookie in pairs(cookies) do
                  response_handle:headers():add("set-cookie", cookie)
                end
                io.flush()
              end
```

But then I just get stuck in a 302 redirect loop as it seems to break the auth.

So yeah, it'd be great to be more fine grained about what gets returned.  It'd also be great if someone could help me understand why my somewhat hacky work around didn't work (as I wasn't stripping the session cookies).

**Comment by ggreenway** [comment]
cc @derekargueta @snowp
