### ISSUE TITLE
I want evnoy to return "connection: keep-alive" header

### ISSUE THREAD

**Issue by ztgoto** [envoyproxy/envoy#21822]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *I want evnoy to return "connection: keep-alive" header*

*Description*:
> I found that if envoy does not return the "connection: keep-alive" header, many clients cannot reuse the connection, resulting in poor performance

**Comment by daixiang0** [comment]
Could you provide the Envoy version you used and detailed logs?

I use main HEAD and `fortio` to test it(`fortio` use keepalive conntions as default) and it will reuse connections.

**Comment by ztgoto** [comment]
> Could you provide the Envoy version you used and detailed logs?
> 
> I use main HEAD and `fortio` to test it(`fortio` use keepalive conntions as default) and it will reuse connections.

The problem comes from performance testing #17266

I found that nginx will return "connection: keep-alive" header to client, but envoy will not, and I cannot set "connection: keep-alive" header in envoy. I suspect the performance difference has something to do with this.
The latest test I used is evnoy:v1.22.2, but the result is still the same.

**Comment by daixiang0** [comment]
I guess it is not the root cause, could you try with `fortio load -c 4 -n 100 ` and `fortio load -keepalive=false -c 4 -n 100`?

You can enable admin endpoint `admin/stats/prometheus` and get stats about `downstream_cx_total`, if enable keepalive, you can see only 4 connections, if disable, you can see 100 connections.

**Comment by ztgoto** [comment]
> I guess it is not the root cause, could you try with `fortio load -c 4 -n 100 ` and `fortio load -keepalive=false -c 4 -n 100`?
> 
> You can enable admin endpoint `admin/stats/prometheus` and get stats about `downstream_cx_total`, if enable keepalive, you can see only 4 connections, if disable, you can see 100 connections.

You're right, but if it weren't for the "connection:keep-alive" header, then I really can't think of a reason for such a big gap. Is the processing flow of envoy really much more complicated than that of nginx?

**Comment by daixiang0** [comment]
I am not familiar with Nginx, hard to say it. 

BTW, you can test via `fortio` again to get a new benchmark.

**Comment by ztgoto** [comment]
I use fortio to test, the performance of nginx is still much better than that of envoy (nginx:envoy=4:1), but fortio is not like wrk, which can overwhelm the cpu of nginx, or it may be that I am using it incorrectly.
fortio load -c 8  -qps 0   'http://127.0.0.1:9101'

**Comment by ggreenway** [comment]
Unless you have configured envoy to not re-use connections, it will reuse by default. Can you post your envoy config that is resulting in lack of connection reuse?

**Comment by ztgoto** [comment]
> Unless you have configured envoy to not re-use connections, it will reuse by default. Can you post your envoy config that is resulting in lack of connection reuse?

This is my misunderstanding, from the downstream_cx_total metric, envoy does have reused connections. I'm just curious where this performance difference between nginx and envoy comes from.
