### ISSUE TITLE
linux_x64 coverage times out

### ISSUE THREAD

**Issue by silverstar194** [envoyproxy/envoy#21833]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:
linux_x64 coverage times out after 120 minutes

*Description*:
[linux_x64 coverage times out](https://github.com/envoyproxy/envoy/pull/21725/checks?check_run_id=7009386786)
Validation has been rerun three times and fails to pass. Timeout is set to 120 minutes.

PR:
[Relevant PR](https://github.com/envoyproxy/envoy/pull/21725)

Azure Pipeline:
[Azure Pipeline](https://dev.azure.com/cncf/envoy/_build/results?buildId=111080&view=logs&s=76816cb1-0469-591b-9542-430a8e387e98&j=9847b632-4506-56d9-5b24-dbc653a96189)
*Repro steps*:
See above PR

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:

*Config*:

*Logs*

The job running on agent i-0b980d1964b1ec217 ran longer than the maximum time of 120 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
Agent: i-0b980d1964b1ec217
Started: Today at 11:22 AM
Duration: 2h 3m 56s

Job preparation parameters
7 queue time variables used
[99.9% tests](https://dev.azure.com/cncf/envoy/_build/results?buildId=111080&view=ms.vss-test-web.build-test-results-tab) passed

**Comment by phlax** [comment]
hi @silverstar194 ive been trying to track down these issues with coverage timing out 

i believe that precompiled protoc (#21588 ) makes a small amount of difference but doesnt resolve i think (not sure if your pr was merged with this update, but worth rebasing/merging to current main)

another possible candidate is resulstore streaming of build data - im trying to follow up on this also

**Comment by silverstar194** [comment]
@phlax  I just merged in latest main. Fingers crossed
