### ISSUE TITLE
Is there a way to return a custom HTTP response code using the grpc_json_transcoder filter?

### ISSUE THREAD

**Issue by augustomarinho** [envoyproxy/envoy#21839]
I'm implementing an API using the _grpc_json_transcoder_ filter and working well. I know the HTTP response code is mapped to _grpc-status_ according to the [code.proto ](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto ) definition. But, I have a doubt if it would be possible to customize the HTTP return code, like answering HTTP 201 (Created) or HTTP 202 (Accepted) in a successful response without using the Lua script to intercept the upstream. Do we have more information about it? Thanks in advance.

**Comment by ggreenway** [comment]
cc @lizan @qiwzhang

**Comment by qiwzhang** [comment]
your desired http_status code will be based on what?  a field from response_body?   or grpc status code in the response headers?  But for a successfully grpc response, there will not be grpc_status code in the response header.

**Comment by augustomarinho** [comment]
@qiwzhang Reading the [code.proto ](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto) I understood that isn't possible to use _grpc-status_ because doesn't have this mapping. Is there another native way in Envoy to do that?

To make this feasible, I implemented a Lua script to change the HTTP response based on a custom header returned by the application, more and less like that:
```
local function isempty(s)
  return s == nil or s == ''
end

function envoy_on_response(response_handle)
  local headers = response_handle:headers()
  local custom_response_code = headers:get("x-http-response-code")
  response_handle:logInfo("Custom Response Code: " .. custom_response_code)
  if response_handle:headers():get(":status") == "200" and (not isempty(custom_response_code)) then
    response_handle:headers():replace(":status", custom_response_code)
  end
end
```

But, I'd like to understand if exists a better way to do that.

**Comment by qiwzhang** [comment]
So you are requesting a feature that allowing gRPC server to set the HTTP status code after transcode the response to HTTP/json,  is that correct?   Current envoy grpc_transcoder doesn't support anything like this.  For your idea of using a response header,  it is not supported by grpc_transcoder either.

But it should be easy to add it.

**Comment by augustomarinho** [comment]
In fact, my goal is to understand if the transcoder can customize HTTP codes that don't have mapped in [code.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto). 

As the transcoding specs talk about "... RESTful JSON API client to send requests to a gRPC service ...", I'd like to design my APIs returning HTTP codes more connected with this paradigm (REST). As I implementing a RESTful async API, I believe the better HTTP code to return would be 202 for this case (at least, according to https://www.rfc-editor.org/rfc/rfc7231#section-6.3.3).

**Comment by qiwzhang** [comment]
Sorry,  grpc transcoder could not customize http code from grpc status-code. I also feel it is not the right approach, in grpc world, only 0 means success,  non-zero codes mean errors. I guess your requirement doesn't fit into grpc world.

**Comment by augustomarinho** [comment]
Thanks,  @qiwzhang  for your time to talk about a little of this topic. Feel free to close this comment or let me know if can do that.

**Comment by fgmacedo** [comment]
@qiwzhang 

> But it should be easy to add it.

So the feature is not do map grpc codes to http codes, but to use response metadata like `x-http-code` (custom header) to inform the `grpc_transcoder` the desired HTTP response status code.

On the gRPC server, we'll need to write something like this to define a custom http response:

``` go
_ = grpc.SetHeader(ctx, metadata.Pairs("x-http-code", "201"))
```

Do you consider adding this as a new feature to the `grpc_transcoder`?

The flow can be: We define a custom http header (metadata) that the `grpc_transcorder` knows, and if present on the grpc server response, it uses the value of the header as the response code to the client.

ref 1: [Setting custom response metadata in a go grpc server)(https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-metadata-1).

ref 2: Similar implementation on [gRPC-Gateway](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#controlling-http-response-status-codes)

**Comment by wrossmorrow** [comment]
Just chiming in as another party that would be interested in the ability to "cleanly" set the HTTP code corresponding to a transcoded gRPC call.
