### ISSUE TITLE
api: not-implemented-hide should warn

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#21855]
A field with `[#not-implemented-hide:]` protodoc annotation is considered stable in xDS sense, e.g. it does not trigger WIP warnings. That seems wrong, and causes issues when a hidden field is promoted to WIP alpha.

**Comment by NaveenGokavarapu19** [comment]
Hi i am beginner. i want to take up this issue. Are there any prerequisites for taking up the issue.
