### ISSUE TITLE
Envoy fails to parse lds v1 responses

### ISSUE THREAD

**Issue by jvshahid** [envoyproxy/envoy#2188]
*Description*:

when running envoy version https://github.com/envoyproxy/envoy/commit/b62c541005b601e9fde8c2fa0399f2f6c935fc3c with v1 config and v1 lds envoy will fail to parse the lds response with the following provided in [this gist](https://gist.github.com/jvshahid/a4541bdccb954fd03bda7e1231d289e8)

*Repro steps*:

Start envoy with the following config:

```json
{
   "listeners" : [],
   "cluster_manager" : {
      "clusters" : [
         {
            "type" : "static",
            "connect_timeout_ms" : 250,
            "hosts" : [
               {
                  "url" : "tcp://127.0.0.1:8080"
               }
            ],
            "lb_type" : "round_robin",
            "name" : "0-service-cluster"
         },
         {
            "lb_type" : "round_robin",
            "hosts" : [
               {
                  "url" : "tcp://127.0.0.1:2222"
               }
            ],
            "connect_timeout_ms" : 250,
            "type" : "static",
            "name" : "1-service-cluster"
         },
         {
            "connect_timeout_ms" : 250,
            "hosts" : [
               {
                  "url" : "tcp://127.0.0.1:61003"
               }
            ],
            "lb_type" : "round_robin",
            "type" : "static",
            "name" : "lds-cluster"
         }
      ]
   },
   "admin" : {
      "address" : "tcp://127.0.0.1:9901",
      "access_log_path" : "/dev/null"
   },
   "lds" : {
      "refresh_delay_ms" : 1000,
      "cluster" : "lds-cluster"
   }
}
```

and the following listeners config returned by the lds server

```json
{
   "listeners" : [
      {
         "ssl_context" : {
            "cipher_suites" : "[ECDHE-RSA-AES256-GCM-SHA384|ECDHE-RSA-AES128-GCM-SHA256]",
            "cert_chain_file" : "/etc/cf-instance-credentials/instance.crt",
            "private_key_file" : "/etc/cf-instance-credentials/instance.key"
         },
         "address" : "tcp://0.0.0.0:61001",
         "name" : "listener-8080",
         "filters" : [
            {
               "config" : {
                  "stat_prefix" : "ingress_tcp-9534127d-306e-49b5-5158-9688cf1cd33b",
                  "route_config" : {
                     "routes" : [
                        {
                           "cluster" : "0-service-cluster"
                        }
                     ]
                  }
               },
               "type" : "read",
               "name" : "tcp_proxy"
            }
         ]
      },
      {
         "ssl_context" : {
            "private_key_file" : "/etc/cf-instance-credentials/instance.key",
            "cipher_suites" : "[ECDHE-RSA-AES256-GCM-SHA384|ECDHE-RSA-AES128-GCM-SHA256]",
            "cert_chain_file" : "/etc/cf-instance-credentials/instance.crt"
         },
         "address" : "tcp://0.0.0.0:61002",
         "name" : "listener-2222",
         "filters" : [
            {
               "name" : "tcp_proxy",
               "type" : "read",
               "config" : {
                  "stat_prefix" : "ingress_tcp-d784818b-5cc6-4335-5ad7-f3bec75347fd",
                  "route_config" : {
                     "routes" : [
                        {
                           "cluster" : "1-service-cluster"
                        }
                     ]
                  }
               }
            }
         ]
      }
   ]
}
```
watch envoy constantly failing to parse the lds output with the error given in [this gist](https://gist.github.com/jvshahid/a4541bdccb954fd03bda7e1231d289e8)

The issue seems to be in the translation from the lds v1 to v2. It looks like the trusted_ca filename is set to the empty string but instead should be left out completely.

**Comment by mattklein123** [comment]
@htuch do you mind taking a quick look at this? I think this might be a constraint bug. I can take a look tomorrow if you don't have time.

**Comment by alyssawilk** [comment]
Yeah, looks like you're right If you pass in LDS proto without ca_cert by the time it hits onConfigUpdate it somehow picks up an empty (thus invalid) trusted_ca


  tls_context {
    common_tls_context {
      tls_params {
        cipher_suites: "[ECDHE-RSA-AES256-GCM-SHA384|ECDHE-RSA-AES128-GCM-SHA256]"
      }
      tls_certificates {
        certificate_chain {
          filename: "/usr/local/google/home/alyssar/.cache/bazel/_bazel_alyssar/3a7172795bcbacd0230af40aaea95285/bazel-sandbox/7743837000705908879/execroot/envoy/bazel-out/k8-dbg/bin/test/server/lds_api_test.runfiles/envoy//test/config/integration/certs/servercert.pem"
        }
        private_key {
          filename: "/usr/local/google/home/alyssar/.cache/bazel/_bazel_alyssar/3a7172795bcbacd0230af40aaea95285/bazel-sandbox/7743837000705908879/execroot/envoy/bazel-out/k8-dbg/bin/test/server/lds_api_test.runfiles/envoy//test/config/integration/certs/serverkey.pem"
        }
      }
      validation_context {
        trusted_ca {
          filename: ""
        }
      }
      deprecated_v1 {
      }
    }
  }

**Comment by alyssawilk** [comment]
Fix should be in shortly.  As an aside, thanks for the great repro instructions - they made tracking this down so much easier!

**Comment by jvshahid** [comment]
thanks @alyssawilk for the quick turnaround
