### ISSUE TITLE
Request Body Validation

### ISSUE THREAD

**Issue by aanshul22** [envoyproxy/envoy#21929]
For a POST request, is it possible to validate the request body by using a JSON/YAML config model?

I would like to use schema matching to validate the request payload. I cannot find anything that lets me access the request body and check for required /missing parameters and check for the data types of the parameter values.

**Comment by aanshul22** [comment]
@phlax Could you please assist? I would really appreciate it.

**Comment by phlax** [comment]
im not aware of any existing extension that does this - but i may be wrong

**Comment by phlax** [comment]
see https://www.tetrate.io/blog/validating-a-request-payload-with-wasm/

**Comment by bryanwux** [comment]
Yes, as @wbpcode said, a wasm filter can help to validate the http request body. You may want to have a look at this https://github.com/intel/modsecurity-wasm-filter.
