### ISSUE TITLE
envoy start error deploy way is sidecar in my app

### ISSUE THREAD

**Issue by gogowaiting** [envoyproxy/envoy#21920]
*Title*: *One line description*
deploy envoy sidecar in my app ，but envoy contianer start error。
I want to configure the external OPA authentication function through envoy and start the error reporting through sidecar,
*Description*:
>
uri is my opa sidecar access url
this is my envoy.yaml file

`static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 80 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      typed_per_filter_config:
                        envoy.filters.http.ext_authz:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                          check_settings:
                          context_extensions:
                            virtual_host: local_service
                      routes:
                        - match: { prefix: "/install" }
                          route: { cluster: some_service }
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                        http_service:
                            server_uri:
                                uri: localhost:8181/v1/data/ecpdev/api/install
                                cluster: ext-authz
                                timeout: 0.25s
                                failure_mode_allow: false

  clusters:
    - name: some_service
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: some_service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 8000
    - name: ext-authz
      connect_timeout: 0.25s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: ext-authz
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 8181`
-------------
error info：
error initializing configuration '/etc/envoy/envoy.yaml': Error: non-terminal filter named envoy.filters.http.ext_authz of type envoy.filters.http.ext_authz is the last filter in a http filter chain.

**Comment by daixiang0** [comment]
The route filter should be the last, please check https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/ext_authz.html?highlight=envoy%20filters%20http%20ext_authz and try.

**Comment by gogowaiting** [comment]
> The route filter should be the last, please check https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/ext_authz.html?highlight=envoy%20filters%20http%20ext_authz and try.



> 
ok，thanks

**Comment by wbpcode** [comment]
I think this may be can be closed directly now? @gogowaiting
