### ISSUE TITLE
Is it possible to manipulate the initial request headers while using ext_authz?

### ISSUE THREAD

**Issue by catalin-me** [envoyproxy/envoy#21938]
Is it possible to adjust the original request headers while using an external authorization filter after the request is validated?

For example, I have tried to edit the `r.HTTPRequest.Attributes.Request.Http.Headers[k] = v` structure using custom values, but the initial request seems to remain intact.

**Comment by wbpcode** [comment]
Yeah. You can override the original request headers by set `headers` in the ok response.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#service-auth-v3-okhttpresponse
