### ISSUE TITLE
Support "envoyproxy/envoy-distroless" image in arm64

### ISSUE THREAD

**Issue by yankay** [envoyproxy/envoy#21936]
*Title*:  Support "envoyproxy/envoy-distroless" image in arm64

*Description*:

In the doc, it shows Support "envoyproxy/envoy-distroless" image in arm64.

![image](https://user-images.githubusercontent.com/1469319/176376986-db918eb4-bf7d-41bf-b031-73bff3fee0ef.png)

But in the docker hub, there are no arm64 image.

![image](https://user-images.githubusercontent.com/1469319/176377095-aaaa19cc-0a47-4baa-b31e-b8480b5ba8ab.png)

So , is there something wrong.

**Comment by phlax** [comment]
hi @yankay this was fixed in https://github.com/envoyproxy/envoy/pull/21134

the docs you posted are for `latest` - i dont think the 1.20 branch has the fix

im thinking it would probably not be so difficult to backport it

**Comment by phlax** [comment]
correction to above - i think i misread the issue - there is a fix in the pipeline for this - more information can be seen here #22261

**Comment by phlax** [comment]
closing as that issue has more information and associatied fixes/backports
