### ISSUE TITLE
Support 500 error for cluster not found

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#21930]
*Title*: *One line description*

*Description*:
In v0.5.0 of gateway-api, 500 should be returned for invalid references: https://github.com/kubernetes-sigs/gateway-api/blob/cea484e38e078a2c1997d8c7a62f410a1540f519/apis/v1beta1/httproute_types.go#L204-L221

Fault injection is not viable to implement this, afaik, since we may want a weighted cluster and only have it apply to one of the clusters. Instead, it seems https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=route#envoy-v3-api-enum-config-route-v3-routeaction-clusternotfoundresponsecode is more appropriate. However, this enum only supports 404 and 503.

It would be great to allow 500 here OR an alternative mechanism to implement this behavior

Note: v0.5.0 hasn't shipped _yet_, but it should soon and I think this issue is pretty much settled.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
IMO, I thinks it is reasonable to support custom 5xx response code for the `cluster_not_found`.

And `LocalReplyConfig` may can be a alternative.

**Comment by wbpcode** [comment]
cc @mattklein123

**Comment by kyessenov** [comment]
503 is more appropriate for transient cluster-not-yet-found errors. Why not just direct respond with 500 if cluster is known to be permanently missing?

**Comment by howardjohn** [comment]
I am fine with solutions like direct_response if we can do it on a weighted cluster basis btw (and keep the transient cluster-not-yet-found errors as 503), the proposed solution just seemed the simplest

**Comment by mattklein123** [comment]
No objection to me to add an option to return 500 for that case.

**Comment by howardjohn** [comment]
Thanks :+1:
