### ISSUE TITLE
ci: proto_format.sh script fails on git push

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#21946]
*Title*: ci: proto_format.sh script fails on git push

*Description*:
I'm attempting to push to a fork of Envoy and the `proto_format.sh` script is failing. This also occurs when I run the script manually, outside of a `git push`.

```
ERROR: /home/meilya/Projects/envoy/tools/proto_format/BUILD:86:8: Executing genrule //tools/proto_format:formatted_api failed: (Exit 1): bash failed: error executing command (from target //tools/proto_format:formatted_api) /bin/bash -c ... (remaining 1 argument skipped)
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/format_api.runfiles/envoy/tools/proto_format/format_api.py", line 18, in <module>
    from tools.proto_format.data import data
  File "/b/f/w/bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/format_api.runfiles/envoy/tools/proto_format/data.py", line 3, in <module>
    data = DataEnvironment.load("/b/f/w/bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/data_pickle.P")
  File "/b/f/w/bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/format_api.runfiles/base_pip3_envoy_base_utils/envoy/base/utils/data_env.py", line 40, in load
    with open(parsed.pickle, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/b/f/w/bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/data_pickle.P'
```

Prior to clearing my bazel cache, the `data_pickle.P` file referenced in the error did exist. After clearing the cache, the file no longer exists.

One of the directories referenced in the traceback, `bazel-out/k8-opt-exec-78EB2C24/bin/tools/proto_format/format_api.runfiles/envoy/tools/proto_format/`, contains broken links to `data_pickle.P`, `data.py`, and `entry_point_data_data_env_main.py`.

My environment is:

- Ubuntu 20.04.03
- Bazel v6.0.0-pre.20220421.3
- Rebased on upstream `main`
  ```
  git merge-base --fork-point main HEAD
  7c04dda02a61c4866b6cc7273c776d62dd3fb127  # this is upstream/main
  ```
- user.bazelrc is using the CI RBE:
  ```
  build --config=remote-clang
  build --remote_cache=grpcs://remotebuildexecution.googleapis.com
  build --remote_executor=grpcs://remotebuildexecution.googleapis.com
  build --remote_instance_name=projects/envoy-ci/instances/default_instance
  ```
- The proto_format.sh script is being run because I made a modification to `api/envoy/extensions/http/header_validators/envoy_default/v3/header_validator.proto` file.
- Previously, on another branch, I ran some of the CI steps locally within Docker. However, I am now running everything on the host.
- This error continues to occur even after I cleared the bazel cache, via `bazel clean --expunge`

**Comment by daixiang0** [comment]
Is it related to remote cache? It works at my local without remote cache.

**Comment by phlax** [comment]
i believe it to be related to RBE - im going to try and repro locally

**Comment by phlax** [comment]
ive managed to repro and have  good idea of the problem, not sure of the solution yet

**Comment by phlax** [comment]
@ameily #21986 fixes for me with RBE - can you confirm ?
