### ISSUE TITLE
forward_downstream_sni Filter for Forward Proxy Egress

### ISSUE THREAD

**Issue by DanStough** [envoyproxy/envoy#21953]
*Title*: *Add a filter to forward downstream SNI to an upstream cluster that is also an envoy proxy (egress proxy)*

*Description*:
This feature was already discussed as part of #4076 and declined as part of #4334 as [istio-specific](https://github.com/envoyproxy/envoy/pull/4334#issuecomment-436478343), but I was trying to do something similar with bare Envoy and couldn't figure out a better way to do it. I wonder if the time/circumstances have changed since the original issue that Envoy would consider pulling in this feature?

Use case refresher:
Client dials *.example.com -> [iptables redirect]-> client envoy -> [mTLS connection with original *.example.com SNI] -> envoy forward proxy -> original *.example.com destination

**Comment by wbpcode** [comment]
cc @lizan Could you take a look when you have free time?

**Comment by LuyaoZhong** [comment]
This feature sounds interesting. I'm curious about the scenario, do you have a concrete example?
And could you elaborate on the traffic type, such  as tls or http, between the entities to help me understand it?

**Comment by DanStough** [comment]
Hey @LuyaoZhong 👋 

The scenario I'm thinking of is very similar to the one described in #4076, where we'd like to set up an allow-list of wildcard subdomains that can be routed through a secondary proxy serving as an egress gateway. The egress gateway would allow for monitoring all traffic leaving several sidecars or a mesh (Consul in this case). An example might be something like a list of kafka servers (*.kafka.example.com), where a client could be redirected between any of them, and the list might evolve over time. 

To add a bit more detail about the proposed flow:

1. tls dial of one.kafka.example.com 
2. [iptables redirect to sidecar envoy listener] 
3. listener has TLS inspector filter to gather `server_name` 
4. FilterchainMatch on `server_name: *.kafka.example.com` request is routed to upstream cluster 
5. upstream cluster has `forward_original_sni ` filter that adds `sni: one.kafka.example.com`, routes traffic to 10.0.0.1:8443 (listener of egress gateway envoy)  <- This doesn't exist today to my knowledge
6. Hop over the network to the egress envoy instance
7. egress envoy listener has TLS inspector filter to gather `server_name`  
8. FilterchainMatch on `server_name: *.kafka.example.com` 
9. Traffic is routed to the `original_destination` cluster, reaching the terminal destination.

This would be most useful for TLS traffic, as I understand [auto_sni](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-upstreamhttpprotocoloptions-auto-sni) might be used to accomplish something similar for HTTP traffic. Also, the connection between envoy instances doesn't need to be protocol aware.
