### ISSUE TITLE
travis ci bug breaks ipv6 tests

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#2195]
See travis-ci/travis-ci#8891

When bug is resolved we should be able to revert a6d04b8d647c0616463a266c1d4d095558090df3.

**Comment by zuercher** [comment]
Assigned myself -- I'll keep an eye on this and undo my fix when this gets resolved.

**Comment by alyssawilk** [comment]
"Fixed" by #2224  :-)

**Comment by zuercher** [comment]
Since we've figure out how to do IPv6 tests in Circle CI, we've disabled our Travis build and this doesn't matter anymore.
