### ISSUE TITLE
Allow immediate health check failure without active health check configured

### ISSUE THREAD

**Issue by freedomljc** [envoyproxy/envoy#21967]
*Title*: *Allow immediate health check failure without active health check configured*

*Description*:
Based on [x-envoy-immediate-health-check-fail](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-immediate-health-check-fail), it will exclude the host from load balancing only when the healthcheck is configured in the cluster. Currently we are exploring to remove envoy active healthcheck, but still want to keep [`/healthcheck/fail`](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-healthcheck-fail) working, thus ensuring gracefully shutdown. 

One idea is to update [the router logic](https://github.com/envoyproxy/envoy/blob/f40aba4c3e72a605c00a880137c07a4d3e6003a7/source/common/router/router.cc#L1381-L1382) to set the host unhealthy regardless whether the healthcheck is configured in the cluster. In this way, when healthcheck is not configured in the cluster but having healthcheck filter in upstream, the normal http response with the header `x-envoy-immediate-health-check-fail` would be able to mark the host unhealthy once `/healthcheck/fail` gets invoked.

Would like to check whether the idea makes sense, before starting the implementation.

**Comment by wbpcode** [comment]
If the active health checking is not enabled, when will the host will resume to be healthy after we set it to unhealthy?

**Comment by wbpcode** [comment]
> It seems there's no way to tell downstream that the host is ready to accept the traffic again

Then I think it's hard to convince users to accept this behavior.

**Comment by freedomljc** [comment]
> Then I think it's hard to convince users to accept this behavior.

I guess the inconvenience could be related to the naming `/healthcheck/fail` VS `/healthcheck/ok`, as developers might expect `/healthcheck/ok` to work for this case as well. However, in practice `/healthcheck/fail` is mainly used to drain the host when it is being terminated. It is not that common to invoke `/healthcheck/ok` to un-drain the host afterwards.

Alternatively, we can add another admin command like `/healthcheck/drain` to differentiate from the existing cmd:  `/healthcheck/drain` excludes the host from the load balancing regardless of whether active healthcheck is configured in the downstream clusters, when healthcheck filter is configured in the listener. 

- If active healthcheck is configured in the cluster, `/healthcheck/ok` is able to negate the impact of `/healthcheck/drain`.
- If active healthcheck is not configured in the cluster, we won't be able to negate the impact of `/healthcheck/drain`.

**Comment by mattklein123** [comment]
I don't see any good way of making this work well when there is implicit linking of configuration between upstream and downstream.

It sounds like perhaps passive health checking / outlier detection might be a better fit here? Perhaps the immediate health check fail could feed into passive health checking which might be good enough for your use case.

I do think it happens that people health check fail a host during debugging, and then hit the ok endpoint to have it take traffic again, so I agree with @wbpcode this would be confusing to many users.

**Comment by freedomljc** [comment]
Got it, I'll seek other options then.
