### ISSUE TITLE
Porting BoringSSL-OQS Fork Into Envoy

### ISSUE THREAD

**Issue by drouhana** [envoyproxy/envoy#21961]
Hi everyone, firstly apologies if this is the wrong place to open a discussion on this.

## What I'm Trying To Do

I'm currently working on an open source implementation of a post-quantum enabled service mesh. This effort is in 3 parts:

- Nginx-oqs (finished in march of this year)
- Envoy (in progress)
- Istio (contingent on completion of envoy)

Nginx was fairly straightforward to port the OpenSSL-OQS fork, but Envoy is giving me some trouble. Envoy is incompatible with OpenSSL (there is a [team](https://github.com/envoyproxy/envoy-openssl) working on fixing this currently), so I had to use the BoringSSL-OQS fork  
  
  
## How I'm Doing it

To [update BoringSSL for envoy](https://github.com/envoyproxy/envoy/blob/11d1a0f002e1742c72b0c41e6e640f6420625371/bazel/repository_locations.bzl#L75), specifically the "main-with-bazel" branch must be used:

![Screen Shot 2022-06-24 at 07 31 31](https://user-images.githubusercontent.com/56026339/175546317-c5fad7b1-ab35-4314-a938-ef6542e12bee.png)

The last updated Boringssl-OQS main-with-bazel was from 2019, so I [forked it](https://github.com/drouhana/boringssl/tree/master-with-bazel) and added the siphash.h file needed by Envoy.

A few other modifications I needed to make in the [Envoy fork](https://github.com/drouhana/envoy-fork) I'm modifying:

- Disable jwt-auth
- Disable QUIC to side-step Quiche compatibility issues

Envoy successfully builds with my modifications

![image](https://user-images.githubusercontent.com/56026339/175549746-efd0b7b1-e412-476e-b65e-72e9d19c054d.png)
![image](https://user-images.githubusercontent.com/56026339/175549767-c2a2e67d-9da0-4936-9c3f-e060573becf0.png)

Here are the commands I used to generate the self-signed CA cert and the server cert as per the instructions on the OpenSSL-OQS page. I have tried them with all combinations of standard/OQS/hybrid for both the CA cert and the server cert

    /usr/local/openssl/apps/openssl req -x509 -new -newkey rsa:2048 -keyout root_CA.key -out root_CA.crt -nodes -subj "/CN=oqstest CA" -days 365 -config /usr/local/openssl/apps/openssl.cnf
  
    /usr/local/openssl/apps/openssl req -new -newkey rsa3072_dilithium2 -keyout serverkey.key -out servercsr.csr -nodes -subj "/CN=oqstest server" -config /usr/local/openssl/apps/openssl.cnf
   
    /usr/local/openssl/apps/openssl x509 -req -in servercsr.csr -out servercert.crt -CA root_CA.crt -CAkey root_CA.key -CAcreateserial -days 365  

## How It's Working: Standard RSA

I can confirm my build works by passing RSA certs and keys generated using the OQS-OpenSSL fork. The HTTPS server successfully performs the TLS handshake, and I am able to reach HTTP upstream.

![image](https://user-images.githubusercontent.com/56026339/175548753-138d6dbe-2ae8-4a91-8319-99e9b4b9c8b3.png)

## How It's Not Working 1: "Cannot Load Certificate Chain"

If I pass the (hybrid or OQS) server cert to Envoy, I get this error:

![image](https://user-images.githubusercontent.com/56026339/175548131-5b90e05d-e5d1-4c70-bd53-ad5fc37dc99b.png)

I have tracked it down to this portion of the Envoy source code:

![image](https://user-images.githubusercontent.com/56026339/175549103-476f1386-8163-4122-acff-48a287353550.png)

Here is a diagram of the functions and their locations in the Envoy and BoringSSL source code:

![image](https://user-images.githubusercontent.com/56026339/175549228-3ebb0ffb-365a-4eb0-8cd6-307984d1a67d.png)

## How It's Not Working 2: "Unsupported Algorithm"

If I pass the (RSA) root CA cert to Envoy with the (hybrid or OQS) key, I am faced with this error instead

![Screenshot_f](https://user-images.githubusercontent.com/56026339/175549342-ee7caf71-95fe-4fcb-9227-6b4343dc16c5.png)

## Questions

If anyone is curious and wants to reproduce this, the instructions are on [this repo](https://github.com/Post-Quantum-Mesh/envoy-oqs) I have set up.

At this point, I feel like there may be something catastrophically important I'm missing about either BoringSSL-OQS, Envoy, or just software development in general.

I would love any and all feedback/advice/thoughts/criticism about why this may be happening, and what I can do to fix this.

**Comment by ggreenway** [comment]
Without looking more closely, my first guess is that because you're using a BoringSSL from 2019, it doesn't support one of the default ciphersuites that envoy tries to configure.

Unless you can get this branch of BoringSSL rebased onto a recent release, I think this is probably a dead-end.

**Comment by drouhana** [comment]
@ggreenway yes, that was a big concern of mine when I saw that the only master-with-bazel branch was from 2019. 

However, envoy builds completely fine with it, passes the tests (some functionalities are disabled, like jwt-auth, quic, etc), and is able to initialize a TLS server using standard RSA encryption. The certificate and keys for the standard RSA are generated using the Boringssl fork from 2019. 

If the outdated BSSL was the issue, wouldn't the standard RSA fail as well?

**Comment by ggreenway** [comment]
Without digging in further, I don't know exactly what the issue is. But you've already identified several incompatibilies (jwt, quic, etc). I believe there have been CVEs fixed in BoringSSL since 2019, so I think any path forward using BoringSSL will need a more recent version. I don't think it is worth any time trying to make current Envoy work with old BoringSSL.

**Comment by drouhana** [comment]
@ggreenway That's fair, i appreciate your input on this. 

I reached out to the bssl-oqs to discuss an updated master-with-bazel, but I think the easiest solution would be envoy that works with openssl. 

Interestingly, the incompatibilities I found were the same ones identified by the envoyproxy team that was working on full [openssl integration](https://github.com/envoyproxy/envoy-openssl/issues/1)
