### ISSUE TITLE
Remove HTTP request/response headers from DEBUG LOGs

### ISSUE THREAD

**Issue by Edimo24** [envoyproxy/envoy#21979]
I am trying to remove completely HTTP request/response headers from debug logs to avoid leakage of sensitive information. Do you have any suggestion where is the best option to do the changes?

I was thinking probably at https://github.com/envoyproxy/envoy/blob/main/source/common/router/upstream_request.cc or https://github.com/envoyproxy/envoy/blob/main/source/common/router/debug_config.cc.

I would appreciate any help!

**Comment by daixiang0** [comment]
I am curious that why you enable DEBUG level in production, which is for debugging and will introduce extra resource costs I think.

**Comment by Edimo24** [comment]
Thanks for your reply, the DEBUG level is not enabled in production but just for debugging. I still have to consider removing HTTP request/response headers from DEBUG logs or adding a tag before some sensitive information (just to make it clear that it is sensitive information) but I am not sure where would it be the best option to do this changes.

**Comment by wbpcode** [comment]
If you have your internal fork of Envoy, I think you can just remove the log code or guard the code by special runtime config.

**Comment by Edimo24** [comment]
I do have the internal fork of Envoy but I am looking for suggestions where to do the changes in which file from Envoy repo? I mean where to edit the debug logs? (never done it before)

**Comment by Edimo24** [comment]
@ggreenway Please have a look and I would appreciate any suggestion

**Comment by ggreenway** [comment]
Have you considered disabling the logs you don't want with https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-enable-fine-grain-logging?

**Comment by Edimo24** [comment]
I have checked the documentation you provided and it is not really clear how to use fine grain logging for my case- I will continue digging around for more info.
What if I want to add a string to the log operators containing sensitive information in debug logs? (i.e. lets say I consider that "DOWNSTREAM_LOCAL_ADDRESS" has some sensitive information and, in debug logs I want it to be not only the IP address but "random STRING" + "DOWNSTREAM_LOCAL_ADDRESS", do you have any suggestion in where I can do this editing?
