### ISSUE TITLE
Jwt AuthN filter dynamic remote_jwks: http_uri or local_jwks: file_name

### ISSUE THREAD

**Issue by satishnaidu** [envoyproxy/envoy#21994]
Dynamic JWT provider jwks configuration to validate JWT token based on claim values from JWT header.
*Description*:

- We would like to validate the JWT token based on dynamic remote_jwks: http_uri configuration or local_jwks:file_name

- Instead of validating against multiple public keys at the JWKS endpoint, we would like to fetch the right public key based on the x_policy claim value(from the header)

- We can write a pre-filter in Lua before JWT authn filter which reads the JWT token "x_policy" value from the header and set jwks endpoint value or local file_name value to DynamicMetaData so that the next filter JWT AuthN will use the configuration to load the configuration to validate the JWT token

- Please let me know whether the same functionality can be achieved with any other existing configuration

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtprovider

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-filterstaterule

>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Could you create multiple providers based on your  x_policy claim values. And then choose right provider for every request based on the `RequirementRule` match?

**Comment by wbpcode** [comment]
cc @lizan

**Comment by satishnaidu** [comment]
@wbpcode 
I tried that approach, there are two problems

1. There are no way to configure the requirement rule match based on JWT header value to choose the right provider

( I mean, the match: prefix: / URL is same for all the requests, i need to chose the provider based on decode jwt header value )

2. If configure the filter with multiple require provider configurations, In future for any new providers I have to update the envoyfilter with new providers list
`# Example 3: require A or B
requires_any:
  requirements:
    - provider_name: provider-A
    - provider_name: provider-B
 `
In case of Lua, the pre-lua filter always construct the dynamic remote_jwks: uri value based on the JWT decoded header claim, so need to rollout new filters to production for every new providers list

CC: @lizan

**Comment by lizan** [comment]
With the current implementation Lua is probably the best way to do it. This requirement rules seems too complex, having a token exchange (via ext_authz perhaps) might be a better solution overall though.

**Comment by qiwzhang** [comment]
Your idea of dynamic "remote_jwks" will not work.  Normally, remote jwks is fetched at the start of Envoy, and periodically re-fetched in a interval at the main thread, worker threads of processing requests are read-only for these remote jwks data.

**Comment by satishnaidu** [comment]
Thanks @qiwzhang for the update, I got the point that we cannot use the remote_jwks endpoint dynamically.
Is it possible to use local_jwks: file_name: <<file_path>> configuration dynamically.

I mean, in Lua filter I can download all the public keys into the envoy file system during startup, 
For instance,
/var/lib/publickeys/A_key.pem
/var/lib/publickeys/B_key.pem, etc

Is there any way to modify the envoy proxy code, to change the file_name value based on the request fields?

Client Request -> Lua Pre Filter -> JWT AuthN filter 

Lua PreFilter:
   Download all the public keys during startup and write to the envoy file system
   Read JWS header fields and update the DynmicMetadData map, to set which local_jwks:file_name: A_key.pem to use.

CC: @lizan  @wbpcode

**Comment by qiwzhang** [comment]
Jwks from `local_jwks: file_name` is only loaded at Envoy start-up time.
