### ISSUE TITLE
Fix `depdendency.check` flakes

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22023]
The sha check test can be flakey as it downloads tarballs from github

While it is useful for updating the shas it is duplicating the sha checking that bazel does (and can fail for that reason)

Im thinking this tool would be more useful standalone and not run as a check

---

broadening this ticket to include the flakey downloads of NIST data

**Comment by phlax** [comment]
cc @kfaseela

**Comment by daixiang0** [comment]
Agree, GH download may be flakey.
