### ISSUE TITLE
Move code out of printers.h

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#2205]
Per discussion on https://github.com/envoyproxy/envoy/pull/2204#discussion_r156745821
it would be nice if the code in printers.h lived closer to the code it's printing and worked more consistently.

**Comment by zuercher** [comment]
You probably figured this out already, but just in case... I poked around a bit at the printers.h stuff and I believe the reason it doesn't work in cors_filter_integration_test.cc (or header_integration_test.cc) is that the headers are in a `TestHeaderMapImpl` and `PrintTo` for `HeaderMapImpl` doesn't apply (though it seems like it should be). If I hack in a `PrintTo` that takes `TestHeaderMapImpl`, I get readable output from failed comparisons.

**Comment by alyssawilk** [comment]
Yeah, that was Matt's suggestion on the code review.  I guess if we get printer.h included by default and add that it's a viable workaround but I prefer Matt's suggestion of having the printing code near the objects they're for.

Is there any reason we don't just ostream in base classes?  I noticed we have rewritten the header printing code in (ndebug-only) production code and was wondering why we don't just have pretty printing in the base class.

**Comment by rishabhkumar296** [comment]
Hi, I would like to work on this issue.
