### ISSUE TITLE
Improve code block higlighting colors in docs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22050]
Currently the color scheme for code block highlighting just doesnt look right to me:

![code-block-colors](https://user-images.githubusercontent.com/454682/177710393-6a18f1fe-d9fa-4c0e-97e8-5116f30c4ea0.png)

while i dont think red and green should _never_ be seen its probably not the best visual contrast and is known to be troubling to people with color blindness and/or dyslexia

i also think red should generally not be used for anything other than errors

**Comment by daixiang0** [comment]
Agree

**Comment by moderation** [comment]
Also agree. Not good from an accessibility and color blindness point of view. And not great aesthetically

**Comment by phlax** [comment]
Preview of various styles:

https://www.florian-diesch.de/doc/sphinx/themes-and-pygments-styles/index.html#theme-default

**Comment by phlax** [comment]
https://dt.iki.fi/pygments-gallery
