### ISSUE TITLE
Header validation: referer validation santizes referers with schemes allowed by RFC 3986

### ISSUE THREAD

**Issue by fishcakez** [envoyproxy/envoy#22062]
*Description*:
The URI RFC allows schemas to include digits . - + (as well as alphabetical characters) but currently the validation only allows schemes to have alphabetical characters, otherwise if enabled will sanitize the header.
```
scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```
Source:  https://datatracker.ietf.org/doc/html/rfc3986#section-3.1.

*Repro steps*:
Referers using scheme such as app-info:// and android-app:// will be removed by the header validation logic.

*Call Stack*:
See https://github.com/envoyproxy/envoy/blob/9adf1704c62725b324112beec2a50fbd1fa602ed/bazel/external/http_parser/http_parser.c#L523

*Related Issues*
https://github.com/envoyproxy/envoy/issues/20989

cc @yanavlasov

**Comment by alyssawilk** [comment]
+ @bencebeky (though I think this will fall under UHV rather than a balsa util)

**Comment by fishcakez** [comment]
Can workaround this by disabling the feature via https://github.com/envoyproxy/envoy/blob/b67a3fc250cd9f74fde744d400d7c6857ea80dea/source/common/http/conn_manager_utility.cc#L106

**Comment by bencebeky** [comment]
Thanks for the heads up.  In fact I wrote an URL validator that matches http-parser behavior, it's out for review at https://github.com/envoyproxy/envoy/pull/22040.  It would be very easy to change it to comply with the spec.  Then moving from http-parser to Balsa would automatically solve this issue.

**Comment by fishcakez** [comment]
@bencebeky @alyssawilk now that #22040 is landed, should we "fix" the balsa implementation?

**Comment by dalegaspi** [comment]
> Can workaround this by disabling the feature via
> 
> https://github.com/envoyproxy/envoy/blob/b67a3fc250cd9f74fde744d400d7c6857ea80dea/source/common/http/conn_manager_utility.cc#L106

i just found out that the `envoy.reloadable_features.sanitize_http_header_referer` option seems to have been [deprecated since version 1.24](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0) was there any specific reason for doing this and is there a replacement flag/option that does the same thing?
