### ISSUE TITLE
double continue on data after `inject*DataToFilterChain()`

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/envoy#22064]
### Bug
Currently the filter manager has a bug where it iterates data on a single filter multiple times. This occurs when a filter:

1) Stops iteration of body and trailers.
2) Calls `injectDecodedDataToFilterChain()` to inject body to the next filter (implicitly continuing iteration of the body).
3) Calls `continueDecoding()` to continue iteration of the trailers.

After further debugging, I found the filter manager is calling `decodeData` on the _next_ filter twice, once in step 2 and again in step 3. This leads to data duplication and messes up internal filter state. Same bug exists on encoder path via `injectEncodedDataToFilterChain()`.

### Reproduction
See the new test filter and integration test added in https://github.com/envoyproxy/envoy/pull/22056. This reproduces the error with the test `EndStreamAtTrailersRealisticFilters`. With the original code (please revert changes to `filter_manager.cc` to test), it fails with `upstream_reset_before_response_started{connection_termination}`.

### Attempt to fix
I tried to fix it in https://github.com/envoyproxy/envoy/pull/22056 by introducing simple boolean variables to the StreamDecoderFilter state. It fixes these issues, but it causes issues for other filters. See https://github.com/envoyproxy/envoy/pull/22056#issuecomment-1178254727 for all the other tests that fail when this is introduced.

Frankly, I am not sure why those other tests are failing. I tried stepping through the debugger but I do not have enough knowledge on the other filters to optimally debug.

### Proposal

I am worried the current fix will break other users. **Instead, let's add a new HTTP Decoder Filter API.** This guarantees to not break any pre-existing users and makes the use of the `inject*DataToFilterChain()` clearer. This new API is meant to complement the current `continueDecoding()` API: https://github.com/envoyproxy/envoy/blob/516bc2b0621daffbc783e6038be64a8a0f9ef3d1/envoy/http/filter.h#L344-L355

New API:
```
/**
   * The same as `continueDecoding()`, but only iterates on filter trailers. This routine
   * does not handle headers, metadata, or body data.
   *
   * This routine can only be called
   * if the filter has previously returned StopIteration from decodeTrailers().It
   * is meant to replace `continueDecoding()` -- it is an error to call both routines
   * in an individual filter.
   *
   * This routine should only be used in advanced cases in which a filter calls `injectDecodedDataToFilterChain()`.
   * Since data injection indicates that a filter does not wish to participate in standard HTTP connection manager
   * buffering and continuation, the filter should **not** call `continueDecoding()`.
   * Instead, the filter is expected to manually handle continuation of trailers via this routine.
   */
  virtual void continueDecodingTrailers() PURE;
```

Implementation will just be a subset of the `continueDecoding()` in filter manager. Should be very clean. i.e. https://github.com/envoyproxy/envoy/blob/516bc2b0621daffbc783e6038be64a8a0f9ef3d1/source/common/http/filter_manager.cc#L52

Same API will be added for HTTP encoder filter: `continueEncodingTrailers()`.

**Comment by mattklein123** [comment]
Thanks for raising. I don't think we should any new APIs until we understand what exactly is broken here. It would be good to understand that first as I would much prefer to fix the bug. I will mark this help wanted.

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by nareddyt** [comment]
Thanks, I would appreciate any help on this. I updated https://github.com/envoyproxy/envoy/pull/22056 to comment out my attempted fix. Anyone can reproduce the problem by running the new tests I added in `test/integration/http_async_inject_body_test.cc`

**Comment by yanavlasov** [comment]
@KBaichoo as well
