### ISSUE TITLE
Embed a visualize dashboard for envoy is possible？

### ISSUE THREAD

**Issue by saltbo** [envoyproxy/envoy#22099]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Embed a visible dashboard for envoy is possible？*

*Description*:
> It is difficult to read the configuration of the envoy, I develop a dashboard for the envoy. I want to know if people need it.

[optional *Relevant Links*:]
>https://github.com/saltbo/seenvoy

![image](https://user-images.githubusercontent.com/17308208/178230173-ff7a0b00-0733-4b90-9894-905a4105a664.png)
![image](https://user-images.githubusercontent.com/17308208/178230372-cb87ab71-433a-4ff2-9a82-eee42a9a84d4.png)
![image](https://user-images.githubusercontent.com/17308208/178230522-5160b9cd-bce1-4a53-9ce8-eabe005f0472.png)
![image](https://user-images.githubusercontent.com/17308208/178230681-c07b8f77-2f05-48f0-8404-b0fb24f72f28.png)
![image](https://user-images.githubusercontent.com/17308208/178230769-4fd67cb9-429a-4eb0-a8ff-275dd283a5fd.png)
![image](https://user-images.githubusercontent.com/17308208/178230808-d8383d6d-3375-48bc-9919-f1ae37c7aea6.png)

**Comment by adisuissa** [comment]
cc @mattklein123 @alyssawilk @htuch

**Comment by jmarantz** [comment]
+1 this is very cool. I am a bit torn as it would be more convenient for us to have this tightly integrated, and having a richer UI expression integrated into the stats declaration can help keep it in sync with the code a little bit easier than having it be in its own repo.

I was going to re-open #19546 soon; just need a couple small tweaks. Now that I'm through a long planning cycle and just got back from vacation I am hoping to clean this up.

**Comment by saltbo** [comment]
Thank you for your recognition. I do want to integrate more closely with the envoy. For example, maybe we can use `seenvoy` instead of the current HTML admin page. However, I also have some concerns because `seenvoy` is 
 developed using SPA. As a result, it may be larger in size than the SSR HTML admin page.

**Comment by saltbo** [comment]
It's easy to integrate SPA like https://github.com/saltbo/seenvoy/blob/master/main.go

I want to transfer the saltbo/seenvoy to the envoyproxy/dashboard. Then compile the dist directory of dashboard into envoy

**Comment by jmarantz** [comment]
Take a look also at https://github.com/envoyproxy/envoy/pull/18670 - that won't be functional right now but look at the description and screenshot. I think you need deeper C++ integration to build a usable view of the stats like that for, say, 100k clusters, which would be 10M stats. I want to get https://github.com/envoyproxy/envoy/pull/19546 merged first though and then we can get a high-performance hierarchical view.

**Comment by saltbo** [comment]
My skill in C++ is weak. I do not intend to go deep into the development of C++ in the short term. I hope to develop the front code using envoy API.

**Comment by jmarantz** [comment]
Thinking about this further, a couple of options look feasible.

You've clearly got a lot of value-add in this visualization (css, js etc), but the Go part is pretty small. Would you consider translating that to C++ and integrating it with admin.cc etc? The benefit is that anyone that compiles Envoy (without the flag to disable admin HTML) would get your visualization for free, without changing their deployment.

Another possibility is to leave the visualization server outside the Envoy binary as you have it. We could still access high-cardinality structures but we'd have to document and stabilize the interface between the Go server and the C++ server. That would make it a little more complicated to evolve over time as you wouldn't be able to upgrade production installations of the two servers concurrently, so it would effectively become an API surface. Anyone wanting to use this would need to run parallel Go servers -- or maybe just one Go server that can point to any Envoy?

I don't think we could use that as it would complicate our already-complex deployment so we'd probably keep a custom one in  in C++.

So from my perspective the lowest-friction path is to translate your 90 lines of Go into C++ and integrate. WDYT?

**Comment by saltbo** [comment]
Yes, I agree.  I would translate the 90 lines of Go into C++ and integrate it with admin.cc.

**Comment by jmarantz** [comment]
Great! You might want to scan through https://github.com/envoyproxy/envoy/pull/19546 (which I just opened for review; it was previously in draft) which will help you get familiar with the mechanism it adds to embed CSS and HTML files into the C++ binary at build time, simplifying deployment. It will also show you some of the hook-points for your transliterated Go. I don't think that part will be complicated once you know where to put it. But mostly look at the BUILD files for how to embed CSS/HTML into C++ constants.

One question on your impl: do you use 3rd party JS libraries? That might be an issue if you are referencing (say) jquery servers from inside a private network that can't reach the internet.

**Comment by saltbo** [comment]
Don't worry, I'm not using 3rd party JS libraries.

#19546 Thank you, I will try it.

**Comment by mattklein123** [comment]
One other thing to keep in mind is that for the non embedded parts we could potentially bundle what is needed in the full sized (ubuntu) docker images. That would make it easy to try/use for the average user. IMO we should keep it out of the slim (distroless) images. cc @phlax

**Comment by jmarantz** [comment]
That's a good point -- Docker probably makes it feasible to serve JS & CSS
from files provided alongside the binary.

Is it sufficient, though, to rely on the compile-time option to cut out the
HTML entirely? Or do you want to be able to be able to enable the HTML but
leave the text out of the binary? The total amount of text is pretty small
compared to the binary, and would be in 'text' space when declared as a
static constexpr char[].

**Comment by mattklein123** [comment]
> Is it sufficient, though, to rely on the compile-time option to cut out the
HTML entirely? Or do you want to be able to be able to enable the HTML but
leave the text out of the binary? The total amount of text is pretty small
compared to the binary, and would be in 'text' space when declared as a
static constexpr char[].

IMO it's probably fine to just have all of it be guarded by the compile time flag. As long as people can compile it out I'm fine with having it all be under that guard.

In terms of all the extra stuff that would be required outside the binary (if we don't compile it in, which is probably simpler for dev anyway), IMO would could just have bundle/install instructions and then just auto bundle/install in the docker image?

**Comment by jmarantz** [comment]
I think dev is not too bad when compiling it in; you can also tweak the build to allow reading files when serving so you can edit them without recompiling or even restarting Envoy.

**Comment by zhxie** [comment]
I have a high level question, do we really need to add a web UI to Envoy itself?
Embedding fancy dashboard will increase the binary size heavily, while a simple web page is too difficult to use for ops. I think Envoy should only expose RESTful APIs, and leave to other developers to setup their own dashboards, or separate into a new project like envoy-webui owned by ourselves.
For some further thoughts, we can add a tab dashboard into the [homepage](https://www.envoyproxy.io/) of Envoy, where we can connect to the Envoy admin and view or modify these configs with these fascinating graphs.
CC @mattklein123 @jmarantz

**Comment by phlax** [comment]
> Embedding fancy dashboard will increase the binary size heavily, while a simple web page is too difficult to use for ops. I think Envoy should only expose RESTful APIs

i would generally agree with this point - i think we risk various kinds of bloat, and additiional maintenance including a UI ourselves, whereas an API could be more powerful, and agnostic to the UI tech etc

**Comment by phlax** [comment]
i guess the upside to embedding a UI is that you dont need to worry about a separate process/container/networking/etc

re API - realizing that is what we have already - i guess there is already tooling that is hooking into this

**Comment by saltbo** [comment]
I found the config_dump API is so slow when the config size is big. This causes seenvoy to load very slowly. I think maybe need a cache for it. but the frontend tech stack maybe not support, eg: localStorage is limit 5MB. Maybe must depends on a backend server to resolve it? 

What do you think about it?

**Comment by saltbo** [comment]
Or implement the cache for config_dump API, and use a querystring to refresh it?

**Comment by jmarantz** [comment]
@saltbo can you add a separate issue for config_dump being slow? This is parallel to https://github.com/envoyproxy/envoy/issues/18675 which is largely addressed for non-Prometheus cases. Landing https://github.com/envoyproxy/envoy/pull/19898 would finish it off.

I think the solution to slow endpoints is streaming and possibly also filtering. I don't think it should be necessary to add a cache, as that would (a) risk staleness confusion (b) still be slow on first query (c) trap a bunch of memory.

**Comment by saltbo** [comment]
Maybe it's different. For the frontend, It needs to parse the JSON data, if we use the streaming, Although the data can be received, it is not complete JSON data and still cannot be parsed, still waiting for received done...

**Comment by saltbo** [comment]
I found the influxdb to save the config_dump data, I will try it.

**Comment by jmarantz** [comment]
There are two challenges:
 * the server bogs down buffering up the entire config as text, locking up the main thread for a significant time, and holding a significant amount of memory. During this process no other main-thread activities occur, including config updates, stats sinks, and other admin requests
 * browser overhead parsing that monolithic chunk of text and generating DOM structures to present it in a usable fashion

Both of these can be addressed by structuring the server endpoints to deliver consumable chunks and a UI to progressively disclose that so that users can more rapidly get to what their looking for compared to sifting through a gigantic text dump.

In any case I think it makes sense to discuss the problem -- as you perceive it -- in a separate issue.

**Comment by saltbo** [comment]
I use influxdb to save the data from config_dump API, then the seenvoy logic is based on it. Now the user experience is very great.
