### ISSUE TITLE
Retries for httpCall from EnvoyFilter

### ISSUE THREAD

**Issue by sumitaneja** [envoyproxy/envoy#22094]
Deployment:  OKE+istio-proxy enabled for pods..

We have EnvoyFilter defined in Istio,  From this filter, Http call is made µService deployed in OKE container,
Query 1: how can i configure retries here.   I observed virtual service retry not kicking if call is from Envoyfilter http client.
As part of envoyfilter definition a cluster was defined to create route to µService deployment within OKE from Envoy

Query 2:  If I configure programmatic retry in while loop, Envoy retries on same replica of target service. We want retries to happen on different replica if available.  Any configuration changes shall impact this particluar client only and should not impact current behavior for other deployments in cluster. (oke services, istio-proxy vitrtual services  etc.)

As part of envoyfilter definition a cluster was defined to create route to µService deployment within OKE from Envoy

```
- applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value: # cluster specification
          name: "lua_cluster"
          type: STRICT_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: lua_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: "xxx.svc.cluster.local"
                          port_value: 8080
`
``

**Comment by adisuissa** [comment]
Hi, not sure I fully grok your questions but I'll try to answer:
1. Retry configurations are typically done for a [route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-retry-policy), so you should be able to set the policy for the route to your `lua_cluster` cluster.

2. IIUC your programmatic retry is defined in a filter, but I'm missing what you are actually doing. If you want to programmatically change things, you can probably add a header that causes the change to a different route.

**Comment by sumitaneja** [comment]
Thanks @adisuissa 
For 1 can you help with more concrete example.  I am not sure how this can be achieved

For 2 this is my sample code in lua filter. Even though above cluster is round robin and STRICT_DNS, all requests are landing on same host from lua filter

```
               while retry and count < 3 do
                 count = count+ 1
                 rlHeaders["x-retry-count"] = count
                 headers, body = request_handle:httpCall(
                  "lua_cluster",
                 rlHeaders,
                 limitBody,
                 30000)
                 rlStatus = headers[":status"]
                 if(rlStatus and rlStatus == "200")
                 then
                  retry = false
                 end
                end

```
