### ISSUE TITLE
How envoy handle old and new quic connections when reload？

### ISSUE THREAD

**Issue by yfming** [envoyproxy/envoy#22119]
how envoy handle old and new quic connections when reload.
when reload, if envoy can keep quic connections open to complete old connections.
and if new connections can not still be handled by old workers.

**Comment by wbpcode** [comment]
cc @alyssawilk @danzh2010

**Comment by danzh2010** [comment]
What kind of reload? If the config update requires tearing down the old listener, currently QUIC still not support both old and new listeners listening on the same port. The old one will abruptly tear down its connections.
If the config update doesn't requires tearing down the old listener, quic support in-place filter chain update.

**Comment by yfming** [comment]
restart.

**Comment by yfming** [comment]
how envoy handle old and new quic connections when restart.
when restart, if envoy can keep quic connections open to complete old connections.
and if new connections can not still be handled by old workers.
