### ISSUE TITLE
Align metrics to follow Prometheus Best Practices

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#22130]
Hello Envoy community!

Is there any plan to align metrics to follow Prometheus Best Practices like getting zero errors from promtool for the exposed metrics from Envoy?
e.g see below issues reported from promtool check:
[promtool_check_exposed_envoy_metrics.txt](https://github.com/envoyproxy/envoy/files/9092829/promtool_check_exposed_envoy_metrics.txt)

Thanks!

**Comment by tejaswiniVadlamudi** [comment]
Good finding, seems like the below errors can be fixed for good reasons?
- no help text
- should have "_total" suffix
- use base unit "seconds" instead of "days"
- metric names should not contain abbreviated units

**Comment by wbpcode** [comment]
cc @jmarantz

**Comment by wbpcode** [comment]
It would be big change for all the envoy stats users. And in my personal opinion, it would be better to achieve it by some third-party exporter rather than update core envoy.

**Comment by tejaswiniVadlamudi** [comment]
@wbpcode : Is it a big change because of code complexity or is it because of backward compatibility with users & dashboards? 
What do you mean by 3PP exporter, an extra process that filters and exposes Envoy metrics? Do we have one available for use?

**Comment by ggreenway** [comment]
It would be a big change in several ways:

* Changing all the prometheus names would require all envoy users that use prometheus metrics to change monitoring configuration
* The names are generally shared with all stat sinks (statsd, etc). To change the names only for prometheus and not the others would be difficult in the codebase.

I think the suggestion from @wbpcode is to have an intermediary that translates the envoy prometheus output to the desired state by renaming metrics, etc.

**Comment by jmarantz** [comment]
Could we put that translation mechanism into the Prometheus sink code, as an off-by-default option? Why would a third process be needed?

Of course we might not be able to augment the system with help-text for every stat. But changing some units (and their corresponding values) seems feasible (though potentially adding significant CPU cost to an already-costly sink).

**Comment by ggreenway** [comment]
`Could we put that translation mechanism into the Prometheus sink code, as an off-by-default option?`

That's a good idea. We can probably get most of the way there with some simple `ends_with` style rules that transform the name and value.

**Comment by wbpcode** [comment]
cc @jmarantz @ggreenway 

Then  I think a bootstrap extension would be great for this.

**Comment by wbpcode** [comment]
> @wbpcode : Is it a big change because of code complexity or is it because of backward compatibility with users & dashboards? What do you mean by 3PP exporter, an extra process that filters and exposes Envoy metrics? Do we have one available for use?

Sorry for the delay response. I think @ggreenway has given a great explanation.

**Comment by ggreenway** [comment]
> cc @jmarantz @ggreenway
> 
> Then I think a bootstrap extension would be great for this.

I think it would probably be cleaner to add an extension point in `stats_config` in the bootstrap config. But it may be sufficient to make a configuration-driven set of rules for renaming/rewriting stats, similar to tag extraction but with the ability to modify non-extracted portions, and scale the values according (like `ms -> sec`, and multiply by 1000).

Also, while thinking about the best way to configure this, we should keep in mind that for all stats systems except prometheus, there is already an extension point (the stats sink config), so we should try to make things as consistent as possible between the two.

**Comment by tejaswiniVadlamudi** [comment]
@wbpcode, @jmarantz and @ggreenway: Thanks for the heads-up, will be looking for the changes :-)

**Comment by jmarantz** [comment]
Sorry just want to clarify -- I think we have been brainstorming about how such a feature ought to be built, and have not been talking about prioritizing it as a task yet.  @tejaswiniVadlamudi @eoregua  is this something you would take on? I think we could review.

**Comment by tejaswiniVadlamudi** [comment]
@jmarantz : I'm not on top of Envoy code, else might have surely tried. As an observability practitioner, I would encourage Envoy to be warning-free when checked with 'promtool' utility. But do you think it is feasible to write a little converter in Envoy code (maybe configurable through a deployment flag) that can fix a few warnings?

I posted a question in the Prometheus Community to understand the severity of these warnings, see https://groups.google.com/g/prometheus-users/c/6KwfxAki2RY/m/Xzmn9wsaAQAJ.

**Comment by jmarantz** [comment]
Yes I think it's feasible. It's just a chunk of work that needs to be prioritized by someone with skin in the game :)
