### ISSUE TITLE
Bug or misuse not sure : Issue using envoy with upgrade connect and npm

### ISSUE THREAD

**Issue by bnadim** [envoyproxy/envoy#22133]
*Title*: *Issue using envoy with upgrade connect and npm*

*Description*:
I am trying to use envoy as an outgoing proxy, the one that you define through http_proxy env vars.
I can not use it as a "transparent" proxy (aka forwarding) for internal reasons.

For some reasong whenever i try to run an npm install of provided package.json, it never succeed even if i run it 2 or 3 times in a row. You can find attached my envoy config file (envoy-cfg.yaml), package.json, node output and error, and envoy debug logs. In addition i can provide a tcpdump but it's quite heavy. I made 2 run. The second one i kept already downloaded files by npm.

I have noticed that when i set a proxy, npm becomes really aggressive and opens a tcp conversation for each call (over 1000) where as without a proxy it does only open a few tcp conversations.
With and without a proxy, it's using http1/1

I setup a test bed with a local registry to check that remote registry, registry.npmjs.org doesn't create a kind of rate limit and i was able to reproduce my issue.

I tried several tunning parameters but didn't succeed. My latests ones are in the file.

I am using nodejs 18.4.0 with npm 8.12.1. Envoy version is 1.22.2.

If you can help me i would be really grateful. I can provide any additional information required.
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
[github.zip](https://github.com/envoyproxy/envoy/files/9093909/github.zip)

**Comment by wbpcode** [comment]
It seems that you client send a request with connection: close?

```
':authority', 'registry.npmjs.org:443'
':method', 'CONNECT'
'connection', 'close'
```
