### ISSUE TITLE
Improve titles in docs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22151]
currently there are quite a few titles that come up as `<no title>` when you search and others that are poorly differentiated

mostly these should be fairly easy to find and fix, would be good to sweep through before release

**Comment by phlax** [comment]
cc @daixiang0

**Comment by zhxie** [comment]
Have a suggestions here. Many [contrib extensions](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/contrib/contrib.html)' docs do not have titles because they have their own hierarchy [here](https://github.com/envoyproxy/envoy/blob/main/docs/root/api-v3/config/contrib/contrib.rst). Maybe we can remove these specified hierarchy and use `../../extensions/**/v3alpha/*` to include all contrib extensions automatically.

**Comment by phlax** [comment]
>  Maybe we can remove these specified hierarchy a

almost certainly a good idea, but i think we should see it to get a better idea

im currently tidying up docs as much as poss before release - @zhxie @daixiang0  if you were able to PR this suggestion that would be amazing. otherwise i can look at it once i have cleared some of the things im currently working on

**Comment by phlax** [comment]
i ran scrapy against the site latest docs - seems like this issue is not as bad as i thought:

```json

[
{"bad": "https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/contrib/sip/sip"},
{"bad": "https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/contrib/cryptomb/cryptomb"},
{"bad": "https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/contrib/hyperscan/hyperscan"},
{"bad": "https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/matchers/matchers"}
]
```

**Comment by phlax** [comment]
for ref this was the scraper:

```python
import scrapy


class DocsSpider(scrapy.Spider):
    name = 'docs'
    allowed_domains = ['www.envoyproxy.io', 'envoyproxy.io']
    start_urls = ['https://www.envoyproxy.io/docs/envoy/latest/']
    custom_settings = {'ROBOTSTXT_OBEY': False}

    def parse(self, response):
        if not response.css("title") or "no title" in response.css("title")[0].get():
            yield {"bad": response.url}

        for next_page in response.css('a'):
            link = next_page.xpath("./@href").extract()
            skip = (
                not link
                or link[0].startswith("#")
                or link[0].endswith("rst.txt")
                or "/_" in link[0]
                or link[0].startswith("mailto:")
                or (link[0].startswith("http") and "docs/envoy/latest" not in link[0]))
            if not skip:
                print(link[0])
                yield response.follow(next_page, self.parse)

```

**Comment by phlax** [comment]
@daixiang0 im going to work on this as i would like at least a bit of a cleanup before release

**Comment by phlax** [comment]
not sure why my crawler didnt get this page but there are other `<no titles>` 

https://storage.googleapis.com/envoy-pr/7d977b1/docs/intro/arch_overview/security/secpos_requires_trusted_downstream_and_upstream.html

**Comment by daixiang0** [comment]
@phlax sorry for slow response  :( thanks for great job!
