### ISSUE TITLE
Add a metric for nofile usage/max

### ISSUE THREAD

**Issue by dekimsey** [envoyproxy/envoy#22153]
*Title*: Expose envoy's ulimit nofile usage/max

*Description*:
> As an operator, I've had a number of cases where envoy has run afoul of the soft nofile ulimit. I don't appear to have any way to monitor usage from any metrics envoy exposes. Many of my proxies are running in containerized workloads where I don't have easy access to grab this metric either (ECS Fargate). Given how heavily envoy uses fd's, I think I'd be great to expose this.

Related: For what it's worth envoy doesn't try to increase it's ulimit, it runs afoul of the soft limit and dies. Perhaps it could `setrlimit` and bump the soft limit for itself?

**Comment by wbpcode** [comment]
> For what it's worth envoy doesn't try to increase it's ulimit, it runs afoul of the soft limit and dies. Perhaps it could setrlimit and bump the soft limit for itself?

In my personal opinion, I don't think change the limit in the envoy internally is good choice. It may break some resource manage policies that set by the PE/SRE.

**Comment by wbpcode** [comment]
The fd's number used by the envoy sounds like a metric that should provided by the OS/external monitor?

cc @jmarantz

**Comment by dekimsey** [comment]
> In my personal opinion, I don't think change the limit in the envoy internally is good choice. It may break some resource manage policies that set by the PE/SRE.

Understandable. To be clear, I only mean to bump the soft cap to the hard cap (which envoy cannot raise anyway). It's my understanding that's why there are two caps. I'm not an expert on the subject, just a thought. It may be entirely not appropriate.

**Comment by dekimsey** [comment]
> The fd's number used by the envoy sounds like a metric that should provided by the OS/external monitor?

In seem places I can do just that with a bit of effort. We use node_exporter on our ec2 instances, but it doesn't provide per process fd's as that's too noisy. I could drop in a textfile exporter to enumerate our envoy sidecars and expose the information. To my knowledge however, in our containers I don't have any ability to pull this information.

Regarding prior art I'm going to double check my environment, if memory serves we get fd counts from our Java apps' metrics. It's one of the major stats we keep an eye on there. But I understand the JVM is special in everyway.

The root cause (envoy hitting the soft limit) has happened enough I wanted to start this conversation.

**Comment by wbpcode** [comment]
> The root cause (envoy hitting the soft limit) has happened enough I wanted to start this conversation.

cc @mattklein123 Could you take a look for this when you have free time? Thanks.

**Comment by dekimsey** [comment]
Ah, coworker pointed me to it. The JVM has a `-XX:+MaxFDLimit` option that bumps soft limit to equal hard limit automatically. TBH it's unclear to me what/how the kernel expects soft vs. hard limits to be used.
