### ISSUE TITLE
Is it possible to use variable environment in envoy configfile ?

### ISSUE THREAD

**Issue by fredericpougnault** [envoyproxy/envoy#22152]
I want to use environment variable in cors to specify the source adresse.
But I don't know if it is possible.

Regards,

**Comment by wbpcode** [comment]
What do you mean by `source adresse`?

As I know, It's not supported to create cors config by the env for now. In most of cases, the config of envoy is created by a control plane and then send to the envoy. Could you achieve your target by the control plane?

**Comment by fredericpougnault** [comment]
By source address I mean allow_origin_string_match.
I'll generate the config by control plane.
