### ISSUE TITLE
will envoy try to consume tokens from all matched LocalRateLlimit descriptors ?

### ISSUE THREAD

**Issue by uglycow** [envoyproxy/envoy#22175]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>according to the document here [rate limit descriptors](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#config-http-filters-local-rate-limit ),  envoy will try to consume tokens from all matched LocalRateLlimit descriptors.
> but according to the master code, it seems like envoy only check the first matched descriptor

```
OptRef<const LocalRateLimiterImpl::LocalDescriptorImpl> LocalRateLimiterImpl::descriptorHelper(
    absl::Span<const RateLimit::LocalDescriptor> request_descriptors) const {
  if (!descriptors_.empty() && !request_descriptors.empty()) {
    // The override rate limit descriptor is selected by the first full match from the request
    // descriptors.
    for (const auto& request_descriptor : request_descriptors) {
      auto it = descriptors_.find(request_descriptor);
      if (it != descriptors_.end()) {
        return *it;
      }
    }
  }
  return {};
}

bool LocalRateLimiterImpl::requestAllowed(
    absl::Span<const RateLimit::LocalDescriptor> request_descriptors) const {
  auto descriptor = descriptorHelper(request_descriptors);

  return descriptor.has_value() ? requestAllowedHelper(*descriptor.value().get().token_state_)
                                : requestAllowedHelper(tokens_);
}
```

did I take anything wrong?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
Can you point to the mis-leading statement in the docs? This seems to explain it https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#using-rate-limit-descriptors-for-local-rate-limiting.

**Comment by StarryVae** [comment]
Yeah, all matched LocalRateLlimit descriptors will be consumed here in main branch:

https://github.com/envoyproxy/envoy/blob/516b3f304bccf451691224c71a357f9c62840b2b/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L168

**Comment by uglycow** [comment]
so sorry that I checked old code and thanks to your reply  @kyessenov  @StarryVae  , I'll just close this.
