### ISSUE TITLE
Followup items from Dockerhub registry migration

### ISSUE THREAD

**Issue by bndw** [envoyproxy/envoy#2218]
Following the Dockerhub migration from `lyft/envoy` to `envoyproxy/envoy`, the following items are in response to questions that have popped up on Slack.

* Add a notice to [the old registry](https://hub.docker.com/r/lyft/envoy) that tells users about [the new registry](https://hub.docker.com/r/envoyproxy/envoy/)
* Investigate if [the old registry](https://hub.docker.com/r/lyft/envoy) can be redirected to [the new registry](https://hub.docker.com/r/envoyproxy/envoy)

**Comment by mattklein123** [comment]
I have no idea how to do this. Help appreciated.

**Comment by bndw** [comment]
@mattklein123 if you can login to https://hub.docker.com/r/lyft/envoy/, I think just editing the copy _Short Description_ and _Long Description_ to the following would be sufficient:

> This registry has moved to https://hub.docker.com/r/envoyproxy/envoy/

As for the auto redirect (like you did with Github), I think that would require support from Docker folks.

**Comment by mattklein123** [comment]
Added short/long descriptions with warning to each repo. Will try to find someone to help with redirect.

**Comment by bndw** [comment]
Just to be overly safe,

`envoyproxy/envoy` does not have the full tag history that is in `lyft/envoy`. 

If the Dockerhub redirect means that `docker pull lyft/envoy` is effectively translated to `docker pull envoyproxy/envoy`, we must backfill the `envoyproxy/envoy` registry prior to the redirect.

**Comment by mattklein123** [comment]
Yes agreed. The backfill is not that hard as you point out, but let's see if a redirect is even possible. I have a few contacts I can try and I just asked on Twitter.

**Comment by mattklein123** [comment]
I heard back from Docker and it's not possible to do redirects, so just closing this out given that we fixed the notices.
