### ISSUE TITLE
AWS Lambda filter JSON property names don't match the docs

### ISSUE THREAD

**Issue by cthain** [envoyproxy/envoy#22213]
*Description*:
The [AWS Lambda filter doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_lambda_filter) describes the JSON schema for the payload sent to the Lambda function when `payload_passthrough` is set to `false`'; however, the following properties aren't named according to the docs:

- `rawPath` is received by the Lamdba function as `raw_path`
- `queryStringParameters` is received by the Lamdba function as `query_string_parameters`
- `isBase64Encoded` is received by the Lamdba function as `is_base64_encoded`

It's worth noting that the filter does seem to respect the names as documented in the response from the Lambda function. During my testing the filter correctly processes responses with the `statusCode` and `isBase64Encoded` properties set.

*Repro steps*:
The following is a simple Lambda function in Go that prints out the `key`/`value` pairs from the payload received from the request going through the `aws_lambda` filter:

```go
package main

import (
	"fmt"
	"net/http"
	"github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest(i interface{}) (map[string]interface{}, error) {
	response := make(map[string]interface{})
	response["statusCode"] = http.StatusOK
	response["body"] = i
	request, ok := i.(map[string]interface{})
	if !ok {
		// payload_passthrough is true
		return response, nil
	}
	for key, val := range request {
		fmt.Printf("%s = %v\n", key, val)
	}
	if body, ok := request["body"]; ok {
		// payload_passthrough = false
		response["body"] = body
		if encoded, ok := request["is_base64_encoded"]; ok {
			response["isBase64Encoded"] = encoded
		}
	}
	return response, nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

Calling the Lambda function through Envoy

```console
$ curl -s -H 'Content-type: application/json' -d '"hello"' 'localhost:1234?key1=val1&key2=val2'
"hello"
```

Yields the following output in the Lambda log:

```log
START RequestId: 291e69fa-6b61-40e0-90ca-879a24c694a6 Version: $LATEST
body = "hello"
is_base64_encoded = false
raw_path = /?key1=val1&key2=val
method = POST
headers = map[accept:*/* content-length:7 content-type:application/json user-agent:curl/7.80.0 x-forwarded-proto:http x-request-id:505f52d7-5b33-4562-b757-b13ba12d0e6b]
query_string_parameters = map[key1:val1 key2:val]
END RequestId: 291e69fa-6b61-40e0-90ca-879a24c694a6
```

*Admin and Stats Output*:
I can provide these if necessary.

*Config*:
The config for the aws_lambda filter:

```json
. . .
{
  "name": "envoy.filters.http.aws_lambda",
  "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.filters.http.aws_lambda.v3.Config",
    "arn": "arn:aws:lambda:us-west-2:<redacted>:function:-envoy-lambda-test"
  }
},
. . .
```

*Logs*:
I can provide these if necessary.

**Comment by adisuissa** [comment]
cc @mattklein123 @marcomagdy @lavignes @tonya11en

**Comment by suniltheta** [comment]
The aws lambda filter while encoding the [request_response.proto](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/aws_lambda/request_response.proto) into json format is just preserving the proto field names ([json_options.preserve_proto_field_names = true](https://github.com/envoyproxy/envoy/blob/1cf5603dc5239c92e5bc38ef321f59ccf6eabc6e/source/common/protobuf/utility.cc#L530)).

I believe we can update the envoy docs to specify the actual format used here (snake_case).
