### ISSUE TITLE
failed to load MI debugger

### ISSUE THREAD

**Issue by dataknower** [envoyproxy/envoy#22229]
i want to debug envoy with vscode in Mac , after success build with `tools/vscode/generate_debug_config.py //source/exe:envoy-static --args "-c envoy.yaml"`  , i try to start debugger, but got such error below. is there anyone can help me ?
<img width="395" alt="image" src="https://user-images.githubusercontent.com/19550451/179271273-49367b51-59f7-4b64-ac61-46bb767ba441.png">

**Comment by daixiang0** [comment]
It looks like an issue about vscode not about Envoy, have you installed all necessary vscode extension?

**Comment by dataknower** [comment]
> It looks like an issue about vscode not about Envoy, have you installed all necessary vscode extension?

thx and  I found that this is due to vscode configuration error

**Comment by yuzd** [comment]
@dataknower i  have the same error
how to fix it?
help me

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/185734480-ef0a6907-9811-449b-8938-7d2856479a9c.png)

**Comment by shengyuandong** [comment]
> 
haven't fix it yet and  i turn to using envoy's develop container

**Comment by yuzd** [comment]
i am testing in devcontainer
and got this error

![image](https://user-images.githubusercontent.com/16083659/185734719-cd28897e-9bae-40a7-80ef-d2ad18562a35.png)

**Comment by yuzd** [comment]
thanks
i will hava a try.
