### ISSUE TITLE
what's the difference betweeen istio-http/1.1 and http/1.1?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22220]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
what's the difference betweeen istio-http/1.1 and http/1.1?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
It's used in ALPN for this filter https://github.com/istio/api/blob/master/envoy/config/filter/http/alpn/v2alpha1/config.proto. I don't recall the original purpose of inventing a new ALPN, @howardjohn might know.

**Comment by howardjohn** [comment]
The reason for the `istio-` ones is to distinguish between Istio mTLS and application TLS
