### ISSUE TITLE
Improve changelog linting

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22222]
A couple of issues are cropping up in the changelog files

Currently it doesnt check for the text type (ie missing `|`) on the change strings

there is also a regression where it no longer checks for capitalization on the first word

there may be others that we want to add

---

- check structure of changelogs - ie have area/change for every entry
- prevent editing of historical changelogs

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by adisuissa** [comment]
Related issue: #22237
