### ISSUE TITLE
release-tool: removal of entries that share the same category

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#22237]
*Title*: release-tool: removal of entries that share the same category

*Description*:
The release tool (`bazel run //tools/project:release`) removes entries in the changelog if multiple entries belong to the same category.

Example:
https://github.com/envoyproxy/envoy/pull/22227/commits/27e7a013cfc601a7239792d37f69a283a00ecfe8

We should either force a category for each individual entry, or fix the tool to support multiple entries per category.

**Comment by phlax** [comment]
was this not just my bad commit here https://github.com/envoyproxy/envoy/pull/22204/files#diff-6f9c718224c533c13c2c0ba1d5abaab86be9d0cc73808749c77934e9f9b0d5d0L243

i think we just need to lint it better (#22222 )
