### ISSUE TITLE
%GRPC_STATUS_NUMBER% isn't accurate for local reply

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#22243]
*Title*: %GRPC_STATUS_NUMBER% isn't accurate for local reply

*Description*:
We wanna to log gRPC status code in the local reply. In the filter's interface [`sendLocalReply`](https://github.com/envoyproxy/envoy/blob/main/envoy/http/filter.h#L449), it allows caller to enforce the [gRPC status code](https://github.com/envoyproxy/envoy/blob/main/source/common/http/utility.cc#L572-L656) in the response. If we want to reformat the body by using %GRPC_STATUS_NUMBER% with local_reply.body_format, the status code is inaccurate. It will gives the one inferred from the Http Status.

The underlying implementation of GRPC_STATUS_NUMBER operator is [Common::getGrpcStatus](https://github.com/envoyproxy/envoy/blob/main/source/common/grpc/common.cc#L83-L100) and it checks
1. trailers gRPC status
2. headers gRPC status
3. Inferred from info HTTP status
Where the first two aren't in place yet and the third one isn't precious one as gRPC status <-> Http status can be easily [skewed](https://github.com/envoyproxy/envoy/blob/main/source/common/grpc/status.cc) with non-1-to-1mapping.

Say we call sendLocalReply(code=`400`,...,grpc_status=`FailedPrecondition`,...), it %GRPC_STATUS_NUMBER% will see Http Status `400` and log `Internal`.

We want to log the cannonical gRPC status code.

**Comment by phlax** [comment]
cc @cpakulski
