### ISSUE TITLE
Add boost as a dynamically-linked dependency for cachelib

### ISSUE THREAD

**Issue by bryanwux** [envoyproxy/envoy#22250]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Add boost as a dynamically-linked dependency for cachelib*

*Description*:

I am considering developing an alternative http cache implementation using [cachelib](https://github.com/facebook/CacheLib) in contrib extension. However, this will bring many more external dependencies like boost , fbthrift and folly(heavily depends on boost) to envoy. I know that boost has been previously rejected for envoy for some reason. I am wondering is it possible or not to get envoy to use shared libraries, so we can link boost as a shared library instead of having it included statically. If this is possible, how?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @lizan @moderation @htuch

**Comment by ggreenway** [comment]
One of the objections to boost is compile times being extremely long for code that includes boost. I don't think dynamic linking would help with that concern.

**Comment by moderation** [comment]
Boost headers were added as a dep for the Hyperscan input matcher contrib extension at https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl#L549-L561=.  In theory as this is a contrib extenstion, it doesn't affect the standard build - https://github.com/envoyproxy/envoy/pull/19473#issuecomment-1063047509=

On one hand, maybe the impact for contrib extensions isn't that significant. But the counter argument is that we now have a series of contrib extensions that feel like R&D for a particular company and it isn't clear if any of them are being used in production in environments that aren't the particular companies labs. There is overhead of maintaining even these dependencies

**Comment by bryanwux** [comment]
Unfortunately, to build folly whole boost is needed which means only boost headers included is not enough :(
