### ISSUE TITLE
Backport #21972

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22263]
as in title, backport Backport #21972

**Comment by surki** [comment]
@phlax wondering if we have any plan the for the 1.23.1 release soon?
(just checking, as our upgrade is blocked on this)

**Comment by phlax** [comment]
my expectation is around 1 week - but may be slightly longer - i want to cycle through the other release branches first

**Comment by surki** [comment]
> my expectation is around 1 week - but may be slightly longer - i want to cycle through the other release branches first

Thanks

**Comment by phlax** [comment]
backport is here #22446
