### ISSUE TITLE
Command operator for enum string grpc.status.code

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#22307]
*Title*: Command operator for enum string grpc.status.code

*Description*:
The existing command operator %GRPC_STATUS% only provides [the camel case of gRPC status code](https://github.com/envoyproxy/envoy/blob/main/source/common/grpc/status.cc#L88-L126). We are requesting a command operator to support enum string(snake case) for [grpc.status.code](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto) , which is extensively used in many libraries. For example, it would be `"InvalidArgument"` VS `"INVALID_ARGUMENT"`.

**Comment by phlax** [comment]
cc @cpakulski
