### ISSUE TITLE
Extend the admin interface to support requesting CDS, RDS sync/reload

### ISSUE THREAD

**Issue by georgi-d** [envoyproxy/envoy#2230]
I have a use case where I need to add a new cluster and as set of routed to the envoy configuration and then signal envoy to consume the new configuration so I can use new configuration immediately after. 

I wanted to use CDS and RDS for this but currently envoy queries xDS periodically which means that there will be some un-deterministic time before the new clusters and routes take effect. 

I think it would be useful to have /clusters/reload /routes/reload  etc.  functionality in the admin interface which allows deterministic reload/update of the configuration.

I think these methods should return/complete after the reload has completed not just when a sync has been initiated.   

Thanks

**Comment by htuch** [comment]
Would gRPC streaming in the v2 API suffice for you use case?

**Comment by georgi-d** [comment]
Could you elaborate on what you mean by 
> gRPC streaming in the v2 API

I would like if it is possible to send a simple REST request possibly containing JSON body. I would rather avoid having to rely on protocol that requires using a library for encoding the request.

Either requesting a resync over RDS, CDS or directly adding the new configuration over REST would work for me. 

Thanks

**Comment by mattklein123** [comment]
Although this feature is possible, it's a large amount of work, and IMO not worth it when the v2 APIs have been designed to be streaming with ACKs as @htuch mentions. @georgi-d can you please take a look at the v2 streaming APIs to see if that works for you. I think it's unlikely that any of the core Envoy developers are going to add this so if it did get added it would be a (complicated) community addition.

**Comment by georgi-d** [comment]
I read into the v2 streaming API and as far as I understand it it should cover what I want to achieve. 

I will attempt the solution with the v2 API.

Thanks for the reply.

**Comment by mattklein123** [comment]
OK going ahead and closing. Thank you.
