### ISSUE TITLE
Add support for an optional TTL in KeyValueStore

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#22303]
It would be nice to have the [KeyValueStore](https://github.com/envoyproxy/envoy/blob/main/envoy/common/key_value_store.h) support a TTL (time-to-live) for entries.  If a TTL is set, then when the TTL has elapsed, the entry would be removed from the KV store, and if it's a KV store that persists to disk (e.g. [FileBasedKeyValueStore](https://github.com/envoyproxy/envoy/blob/main/source/extensions/key_value/file_based/config.h)), then the entry would be deleted from disk as well.

One use case is for storing xDS resources and evicting them when the TTL has expired.

We can add support for a TTL in a couple ways: 
1. As a first class construct within the KV store, similar to how KV store's support a [flush interval](https://github.com/envoyproxy/envoy/blob/main/source/common/common/key_value_store_base.h#L19) and timer.
2. Leave it up to each KV store implementation to implement TTL support as it sees fit.

Interested in hearing others' thoughts on this.

cc @alyssawilk @goaway @jpsim @RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
Seems like a great idea. Alt-Svc has an explicit TTL so if the KV store itself implement it, that would be simpler.

**Comment by alyssawilk** [comment]
SGTM

**Comment by abeyad** [comment]
This was implemented in https://github.com/envoyproxy/envoy/pull/22884, so I'm closing this issue.
