### ISSUE TITLE
`@envoy//test/extensions/transport_sockets/http_11_proxy:connect_integration_test` is flaky (or always fails?)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22324]
Checking azp analytics the test posted in title appears to always fail (3/3 times in last 14 days)

https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build

recent azp failure:

https://dev.azure.com/cncf/envoy/_build/results?buildId=113339&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=9267

The error log doesnt seem to have any errors:

https://source.cloud.google.com/results/invocations/aaecf512-1507-4b36-86f0-18479974724a/targets/@envoy%2F%2Ftest%2Fextensions%2Ftransport_sockets%2Fhttp_11_proxy:connect_integration_test;shard=1;run=1;attempt=2/log

but the test returns code `134` which im guessing is killed by timeout

https://source.cloud.google.com/results/invocations/aaecf512-1507-4b36-86f0-18479974724a/targets/@envoy%2F%2Ftest%2Fextensions%2Ftransport_sockets%2Fhttp_11_proxy:connect_integration_test;shard=1;run=1;attempt=2/artifacts

its not clear why this test has only run three times, or if that is correct - either way i think there is an issue with this test

resultstore has a massive artefact bundle but i dont have space atm to look in it

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
weird, almost always passes locally, must be a resource bug.  looks like time_system.waitfor doesn't work in this circumstance because of the readDisable.  Have a fix in the works.
