### ISSUE TITLE
`wavm` tests are taking a disproportionately large amount of CI resources

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22331]
despite having max sharding and `enormous` settings some of tests are averaging ~10-11mins others are nearly as bad

![hungry-wavm](https://user-images.githubusercontent.com/454682/180048741-023f4c5c-cd14-49be-b67d-8db080aabd78.png)

(from https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build)

i believe the cause is not using a precompiled wavm  bin - not sure all of our current release/build targets are covered by their binary releases:

https://github.com/WAVM/WAVM/releases

but using a precompiled bin seems to be an option

given the length of time for each of these tests individually it would appear as tho it is being compiled for each, so im wondering if there is something we can do just with bazel to improve

on the upside the tests never seem to fail

**Comment by phlax** [comment]
cc @PiotrSikora

**Comment by phlax** [comment]
i see

> requires building WAVM binary,

could we use the published precompiled one to do that? at least on the supported platforms

this is consuming a lot of test cycles i think

**Comment by PiotrSikora** [comment]
If long running tests are a real problem, then I think we could disable tests with WAVM for now (but keep the build with WAVM to verify that there are no build breakages).

WAVM is probably the first Wasm engine that's going to be removed, anyway. We already have WAMR and WasmEdge (which wasn't added to Envoy yet, but it's supported in Proxy-Wasm C++ Host) that also have option to compile Wasm using LLVM in addition to their custom interpreters and JIT engines, so we don't need to have 3 engines based on LLVM.
