### ISSUE TITLE
Combined RBAC IP filter with Unified Matcher usage

### ISSUE THREAD

**Issue by znqjnny** [envoyproxy/envoy#22336]
Hi! We are trying to do an IP filter for thousands of IPs. We planning to use RBAC for IP filtering and combined it with the Unified Matcher.

We have some questions about RBAC and Unified Matcher:

1. Question about RBAC:
Could you give us some idea about how to extract the IP for matching, and also how to match the IP with the subnet for filtering?

2. Question about UnifiedMatcher
From what I learned about the Unified Matcher, looks like the data structure needs to be built on our own,  if we would like to do a Trie match, we should build with nested matcher_tree using prefix_match_map and exact_match_map. And since we have thousands IP to block, that seems results to a disaster since we need to build the matcher with a subtree for each IP.
I’m wondering do you have any suggestions on how to build this feature efficiently? And please correct me if I’m understanding wrong on it.

3. Question about combining RBAC filter with UnifiedMatcher
We would like to use UnifiedMatcher to enhance the performance of RBAC IP filter matching. But I didn’t find an example of how we put the Unified Matcher in the RBAC configuration. Could you give us an example if possible?

Thanks so much for the help!

**Comment by phlax** [comment]
cc @snowp

**Comment by kyessenov** [comment]
@zhxie for RBAC and unified matcher integration.

Re 2: We have an LcTrie-based IP matcher implemented https://www.envoyproxy.io/docs/envoy/latest/xds/type/matcher/v3/ip.proto#envoy-v3-api-msg-xds-type-matcher-v3-ipmatcher that could represent large IP sets efficiently. 

We don't have any concrete solution for sharing "sub-trees" in the matcher tree in general (e.g. multiple identical OnMatch in prefix/exact map). There was some discussion in the past.

**Comment by zhxie** [comment]
Here is an example for using RBAC with generic matching in network/HTTP RBAC filter which will extract the source IP as inputs for matching.

```yaml
# Avoid using `rules` and use `matcher` instead.
matcher:
  matcher_tree:
    input:
      name: envoy.matching.inputs.source_ip
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
    # Change to `custom_match` if you want to use the IP trie.
    exact_map_match:
      map:
        "127.0.0.1":
          action:
            name: action
            typed_config:
              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
              name: allow-localhost
              action: ALLOW
```

**Comment by znqjnny** [comment]
Thanks so much for your help @kyessenov  and @zhxie ! The information is very helpful

**Comment by znqjnny** [comment]
Hi @zhxie , I met a trouble when I tried to test this feature. During the service up, it returned an error as followed
`
Unable to parse JSON as proto (INVALID_ARGUMENT:(matcher.matcher_tree) custom_match: Proto field is not repeating, cannot start list.):

{"admin":{"address":{"socket_address":{"address":"0.0.0.0","port_value":8001}}},"static_resources":{"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"codec_type":"AUTO","route_config":{"virtual_hosts":[{"routes":[{"match":{"prefix":"/service/1"},"route":{"cluster":"service1"}},{"match":{"prefix":"/service/2"},"route":{"cluster":"service2"}}],"name":"backend","domains":["*"]}],"name":"local_route"},"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","http_filters":[{"typed_config":{"matcher":{"matcher_tree":{"input":{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput"},"name":"envoy.matching.inputs.source_ip"},"custom_match":[{"on_match":{"action":{"typed_config":{"name":"deny-request","@type":"type.googleapis.com/envoy.config.rbac.v3.Action","action":"DENY"},"name":"action"}},"typed_config":{"@type":"type.googleapis.com/envoy.extensions.matching.input_matchers.ip.v3.Ip","cidr_ranges":[{"prefix_len":24,"address_prefix":"192.0.0.0"}],"stat_prefix":"ip_parsing_failed"},"name":"envoy.extensions.matching.input_matchers.ip.v3.Ip"}]}},"@type":"type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC","on_no_match":{"action":{"typed_config":{"action":"ALLOW","name":"allow-request","@type":"type.googleapis.com/envoy.config.rbac.v3.Action"},"name":"action"}}},"name":"envoy.filters.http.rbac"},{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"},"name":"envoy.filters.http.router"}],"stat_prefix":"ingress_http"},"name":"envoy.filters.network.http_connection_manager"}]}],"address":{"socket_address":{"port_value":8080,"address":"0.0.0.0"}}},{"address":{"socket_address":{"address":"0.0.0.0","port_value":8443}},"filter_chains":[{"transport_socket":{"typed_config":{"common_tls_context":{"tls_certificates":[{"certificate_chain":{"inline_string":""}}]},"@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"},"name":"envoy.transport_sockets.tls"},"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"route_config":{"virtual_hosts":[{"domains":["*"],"name":"backend","routes":[{"route":{"cluster":"service1"},"match":{"prefix":"/service/1"}},{"match":{"prefix":"/service/2"},"route":{"cluster":"service2"}}]}],"name":"local_route"},"stat_prefix":"ingress_http","http_filters":[{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"},"name":"envoy.filters.http.router"}],"codec_type":"AUTO","@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"}}]}]}],"clusters":[{"lb_policy":"ROUND_ROBIN","load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8000,"address":"service1"}}}}]}],"cluster_name":"service1"},"type":"STRICT_DNS","name":"service1"},{"load_assignment":{"cluster_name":"service2","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8000,"address":"service2"}}}}]}]},"name":"service2","type":"STRICT_DNS","lb_policy":"ROUND_ROBIN"}]},"layered_runtime":{"layers":[{"name":"static_layer_0","static_layer":{"envoy":{"resource_limits":{"listener":{"example_listener_name":{"connection_limit":10000}}}}}}]}}`

I guess I might misunderstanding the way to put custom_match? Could you please correct my mistake? 

Here I attached my code on filter.
`          http_filters:
            - name: envoy.filters.http.rbac
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                matcher:
                  matcher_tree:
                    input:
                      name: envoy.matching.inputs.source_ip
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
                    custom_match:
                      - name: envoy.extensions.matching.input_matchers.ip.v3.Ip
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.matching.input_matchers.ip.v3.Ip
                          cidr_ranges:
                            #foo ip, leave it with testing. Will add the list of blocking IPs on next step
                            - address_prefix: 192.0.0.0
                              prefix_len: 24
                          stat_prefix: ip_parsing_failed
                        on_match:
                          action:
                            name: action
                            typed_config:
                              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                              name: deny-request
                              action: DENY
                on_no_match:
                  action:
                    name: action
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                      name: allow-request
                      action: ALLOW
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router`

Thanks for helping!

**Comment by zhxie** [comment]
@znqjnny You can check [RBAC sandbox](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/rbac) and [match against port and IP](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_listener#match-against-the-destination-port-and-the-source-ip) for help. You are using `type.googleapis.com/envoy.extensions.matching.input_matchers.ip.v3.Ip` while it is not designed for generic matching, you should change to `type.googleapis.com/xds.type.matcher.v3.IPMatcher` following to the latter example.

@kyessenov @snowp @mattklein123 I think generic matching is designed to cause confusion. There are `custom_match` in both `matcher_list` and `matcher_tree`, but the matcher they use has a different form. The user applied an `InputMatcher` (for `matcher_list`'s `custom_match`), but a `MatchTree` (for `matcher_tree`'s `custom_match`) is required here.

**Comment by znqjnny** [comment]
Thanks so much for guiding me to that @zhxie . I followed the instruction of RBAC sandbox and the example of IP matcher to run the example, but I got an error again with that. Could you please help me to check again what cause the problem?

> [2022-08-08 23:59:50.369][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:35] field 'envoy.extensions.filters.http.rbac.v3.RBAC.matcher' is marked as work-in-progress. API features marked as work-in-progress are not considered stable, are not covered by the threat model, are not supported by the security team, and are subject to breaking changes. Do not use this feature without understanding each of the previous points.

[2022-08-08 23:59:50.369][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:35] message 'xds.type.matcher.v3.Matcher' is marked as work-in-progress. API features marked as work-in-progress are not considered stable, are not covered by the threat model, are not supported by the security team, and are subject to breaking changes. Do not use this feature without understanding each of the previous points.

[2022-08-08 23:59:50.369][1][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy.yaml': Didn't find a registered implementation for 'ip-matcher' with type URL: 'xds.type.matcher.v3.IPMatcher'

[2022-08-08 23:59:50.370][1][info][main] [source/server/server.cc:961] exiting

[2022-08-08 23:59:50.371][1][info][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:570] c-ares library cleaned up.

Didn't find a registered implementation for 'ip-matcher' with type URL: 'xds.type.matcher.v3.IPMatcher'

> static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.rbac
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              matcher:
                matcher_tree:
                  input:
                    name: ip
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
                  custom_match:
                    name: ip-matcher
                    typed_config:
                      "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                      range_matchers:
                      - ranges:
                        - address_prefix: 192.0.0.0
                          prefix_len: 2
                        - address_prefix: 10.0.0.0
                          prefix_len: 24
                        on_match:
                          action:
                            name: internal
                            typed_config:
                              "@type": type.googleapis.com/google.protobuf.StringValue
                              value: internal
                      - ranges:
                        - address_prefix: 0.0.0.0
                        on_match:
                          action:
                            name: tls
                            typed_config:
                              "@type": type.googleapis.com/google.protobuf.StringValue
                              value: tls
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: local_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend
                port_value: 8080

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001

**Comment by znqjnny** [comment]
I also tried to remain the same format as **filter_matcher_chain** rather than use http_filter with RBAC. And it caused a different error.

> 
[2022-08-09 00:44:48.168][1][critical][assert] [source/common/network/utility.cc:491] panic: unset oneof

[2022-08-09 00:44:48.168][1][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x6500000001

[2022-08-09 00:44:48.168][1][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):

[2022-08-09 00:44:48.168][1][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: a866dceb91d0ae0d2f1b45f116463bd33d1a9310/1.24.0-dev/Clean/RELEASE/BoringSSL

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7fccabedd420]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #1: [0x55fc56d40a8e]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #2: [0x55fc56d57425]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #3: [0x55fc56d56623]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #4: [0x55fc56dae99f]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #5: [0x55fc569df3c1]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #6: [0x55fc569da9f9]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #7: [0x55fc554e9291]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #8: [0x55fc554e874d]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #9: [0x55fc554e9b4b]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #10: [0x55fc554e9ccc]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:98] #11: [0x55fc554e611c]

[2022-08-09 00:44:48.169][1][critical][backtrace] [./source/server/backtrace.h:96] #12: __libc_start_main [0x7fccabcfb083]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: a866dceb91d0ae0d2f1b45f116463bd33d1a9310/1.24.0-dev/Clean/RELEASE/BoringSSL

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7fccabedd420]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #1: [0x55fc56d40a8e]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #2: [0x55fc56d57425]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #3: [0x55fc56d56623]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #4: [0x55fc56dae99f]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #5: [0x55fc569df3c1]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #6: [0x55fc569da9f9]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #7: [0x55fc554e9291]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #8: [0x55fc554e874d]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #9: [0x55fc554e9b4b]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #10: [0x55fc554e9ccc]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:98] #11: [0x55fc554e611c]

[2022-08-09 00:44:48.170][1][critical][backtrace] [./source/server/backtrace.h:96] #12: __libc_start_main [0x7fccabcfb083]

Our FatalActions triggered a fatal signal.


`    filter_chain_matcher:
        matcher_tree:
          input:
            name: port
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput
          exact_match_map:
            map:
              "80":
                action:
                  name: http
                  typed_config:
                    "@type": type.googleapis.com/google.protobuf.StringValue
                    value: http
              "443":
                matcher:
                  matcher_tree:
                    input:
                      name: ip
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
                    custom_match:
                      name: ip-matcher
                      typed_config:
                        "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                        range_matchers:
                        - ranges:
                          - address_prefix: 192.0.0.0
                            prefix_len: 2
                          - address_prefix: 10.0.0.0
                            prefix_len: 24
                          on_match:
                            action:
                              name: internal
                              typed_config:
                                "@type": type.googleapis.com/google.protobuf.StringValue
                                value: internal
                        - ranges:
                          - address_prefix: 0.0.0.0
                          on_match:
                            action:
                              name: tls
                              typed_config:
                                "@type": type.googleapis.com/google.protobuf.StringValue
                                value: tls             
`

**Comment by zhxie** [comment]
You should fix your first configuration with

```diff
diff --git a/trie-matcher.yaml b/trie-matcher.yaml
index 5ef1ffedb7..f4f2822eb6 100644
--- a/trie-matcher.yaml
+++ b/trie-matcher.yaml
@@ -43,18 +43,20 @@ static_resources:
                           prefix_len: 24
                         on_match:
                           action:
-                            name: internal
+                            name: envoy.filters.rbac.action
                             typed_config:
-                              "@type": type.googleapis.com/google.protobuf.StringValue
-                              value: internal
+                              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
+                              name: internal
+                              action: ALLOW
                       - ranges:
                         - address_prefix: 0.0.0.0
                         on_match:
                           action:
-                            name: tls
+                            name: envoy.filters.rbac.action
                             typed_config:
-                              "@type": type.googleapis.com/google.protobuf.StringValue
-                              value: tls
+                              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
+                              name: external
+                              action: DENY
           - name: envoy.filters.http.router
             typed_config:
               "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

I recommend you following the [API documentation](https://www.envoyproxy.io/docs/envoy/latest/api/api) and [RBAC sandbox](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/rbac) to configure your Envoy.

BTW, it IS a issue that IP matcher does not support match against HTTP context, I will fix that.

**Comment by znqjnny** [comment]
Thanks a lot for fixing that @zhxie . I tested the RBAC sandbox again with your last merge and modified it as you recommended, and the service is up successfully now.

But when I test the IP blocking feature locally, it doesn't allow/deny as I expected...

I check my local IP is 10.0.0.74 and the subnet mask is 255.255.255.0. So I set the rbac filter as followed, which should allow my connection to pass.
```
          http_filters:
          - name: envoy.filters.http.rbac
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              matcher:
                matcher_tree:
                  input:
                    name: ip
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
                  custom_match:
                    name: ip-matcher
                    typed_config:
                      "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                      range_matchers:
                      - ranges:
                        - address_prefix: 10.0.0.74
                          prefix_len: 24
                        on_match:
                          action:
                            name: envoy.filters.rbac.action
                            typed_config:
                              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                              name: internal
                              action: ALLOW                             
                on_no_match:
                  action:
                    name: action
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                      name: allow-request
                      action: DENY
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
``` 

And tried with `curl -si localhost:10000` to send the request.
However, it returns me `HTTP/1.1 403 Forbidden RBAC: access denied% ` rather than pass the connection.

I also tested with all the prefix_len from 0 to 32, and 0 is working which let it pass the connection and return me `HTTP/1.1 200 OK`. But when I do `curl --header "X-Forwarded-For: 192.168.0.2" http://localhost:10000` which should change it to a different source IP, it also gets passed.

So I'm getting confused about what caused that issue... May I ask you to help me to check on that again?
And I'm wondering if there's a way to output the source ip that is captured by envoy `type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput`, so I can make sure I didn't match it wrongly. 

Thank you so much again as always!

**Comment by zhxie** [comment]
In your first case, you are matching `127.0.0.1` (I assume your `localhost` will be interpreted to `127.0.0.1`, see `/etc/hosts`) against `10.0.0.74/24`, and the result is not matched. The matching falls back to the `on_no_match` branch and the result is DENY.

In you second case, you are capturing `SourceIPInput`, so `X-Forwarded-For` header does not matter.
