### ISSUE TITLE
How to log cookie values in access.log

### ISSUE THREAD

**Issue by helloord** [envoyproxy/envoy#22346]
https://github.com/envoyproxy/envoy/issues/6695
Excuse me, is there a solution for this? Thank you

**Comment by phlax** [comment]
cc @cpakulski

**Comment by cpakulski** [comment]
@helloord I am afraid that there is no direct way of doing it. By direct way I mean an access log formatter. 

I have not tried it, but maybe header-to-metadata filter is what you need: https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/http/http_filters/header_to_metadata_filter.html?#id4.
You need to construct regex to locate SESSIONID and put it into dynamic metadata under the key say `sessionid`. Then in access log you need to use formatter DYNAMIC_METADATA as described here: https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/observability/access_log/usage.html

**Comment by helloord** [comment]
> @helloord I am afraid that there is no direct way of doing it. By direct way I mean an access log formatter.
> 
> I have not tried it, but maybe header-to-metadata filter is what you need: https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/http/http_filters/header_to_metadata_filter.html?#id4. You need to construct regex to locate SESSIONID and put it into dynamic metadata under the key say `sessionid`. Then in access log you need to use formatter DYNAMIC_METADATA as described here: https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/observability/access_log/usage.html

Problem solved, thanks

**Comment by rifler** [comment]
> https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/observability/access_log/usage.html

Can you please provide an example?
