### ISSUE TITLE
Failing to connect to PostgreSQL with Envoy using TLS

### ISSUE THREAD

**Issue by shavros** [envoyproxy/envoy#22347]
*Title*: *SSL connection to PostgreSQL via Envoy*

*Description*:
I want to connect to PostgreSQL via envoy. 
I need SSL connection to be established between the envoy and the database.
For example: I want to use psql command like this: 
`psql -h localhost -p 1999 -d test_db -U postgres`
But I am getting an error:
```
psql: error: connection to server at "localhost" (::1), port 1999 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 1999 failed: FATAL:  connection requires a valid client certificate
connection to server at "localhost" (127.0.0.1), port 1999 failed: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "postgres", database "test_db", no encryption
```

At the same time I can successfully connect to database on port 5432 with command:
`psql 'host=localhost port=5432 dbname=test_db user=postgres password=postgres sslmode=verify-ca sslcert=/opt/certpostgre/client1.crt sslkey=/opt/certpostgre/example.key sslrootcert=/opt/certpostgre/ca.crt'`
and on port which envoy is listening:
`psql 'host=localhost port=1999 dbname=test_db user=postgres password=postgres sslmode=verify-ca sslcert=/opt/certpostgre/client1.crt sslkey=/opt/certpostgre/example.key sslrootcert=/opt/certpostgre/ca.crt'`

In envoy.yaml I use the same certs, that I use in my successful commands. 
Can anyone help me with this case?

[optional *Relevant Links*:]
[envoy.txt](https://github.com/envoyproxy/envoy/files/9158289/envoy.txt) - envoy.yaml with listener on 1999 port
PostgreSQL configuration:
[pg_hba.txt](https://github.com/envoyproxy/envoy/files/9158290/pg_hba.txt) 
[postgresql.txt](https://github.com/envoyproxy/envoy/files/9158291/postgresql.txt)

If you need any additional information I will provide it.

**Comment by phlax** [comment]
@shavros can you post your config please

**Comment by shavros** [comment]
@phlax I attached envoy and PostgreSQL configs? Or what you are asking for?

**Comment by phlax** [comment]
apologies - i didnt see the attachments you added

cc @fabriziomello
