### ISSUE TITLE
foreign_cc/ragel build flakes ~frequently in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22351]
This one has been cropping up intermittently i think causing the release job to fail - eg:

https://dev.azure.com/cncf/envoy/_build/results?buildId=113439&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&s=fbb7e3ed-ed2b-5ffd-2e3f-9e68630afbc3&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=1009

https://source.cloud.google.com/results/invocations/f874b85f-2127-4630-8d24-57d33d774c4f/targets

https://source.cloud.google.com/results/invocations/f874b85f-2127-4630-8d24-57d33d774c4f/log

**Comment by phlax** [comment]
cc @zhxie

**Comment by zhxie** [comment]
Thanks for the reporting. I will take some time to look into the issue. It seems that the error is unexpected and happened randomly, I have never met it in my local Docker environment.
BTW, do you know where I can get the failed Configure.log?

**Comment by phlax** [comment]
> I have never met it in my local Docker environment.

i think its a network flake, and fairly infrequent 

>  BTW, do you know where I can get the failed Configure.log?

im not sure i follow which log you are referring to
