### ISSUE TITLE
State value in Oauth filter

### ISSUE THREAD

**Issue by DanApostol** [envoyproxy/envoy#22363]
Hello, 

I am noticing that the state value in Oauth Authorization Endpoint url is using the url of secured service called by client app, so, for example, if client app calls https://localhost:10000/app1/secured/url1, then the state value is equal with the url encoded format of the url called, aka https%3A%2F%2Flocalhost%3A10000%2Fapp1%2Fsecured%2Furl1.

What can be done to follow the recommendation from [Oauth RFC (section 4.1.1)](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1):

state
         RECOMMENDED.  **An opaque value** used by the client to maintain state between the request and callback.  The authorization server includes this value when redirecting the user-agent back to the client.  The parameter SHOULD be used for preventing cross-site request forgery as described in [Section 10.12](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12).

Thank you in advance for your opinion.

Best regards,
Dan.

**Comment by phlax** [comment]
cc @snowp

**Comment by DanApostol** [comment]
Hi @snowp ,

just curious, any ideas if this topic can enable an upgraded implementation of oauth filter?

Thanks in advance.
Dan.

**Comment by snowp** [comment]
How would this new implementation differ from what we do today? Not immediately clear to me what this change would involve

cc @rgs1

**Comment by DanApostol** [comment]
Hi @snowp and thanks for your quick reply.

IMHO, an opaque value for state param can be an uuid, for example something like 29ce04b3-1b74-4e23-8e84-d0281067db57. The idea is that state will help the oauth filter to distinguish between 2 different sessions trying to authenticate in the same time (of course, not exactly). Right now, having the state equals with the url accessed by the clients is something, IMHO, not right.

All proper oauth implementations I've seen are generating a random value for state parameter. 

Please take a look on the [CSRF](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12) topic on Oauth RFC. 

Some C code example for generating uuids: https://stackoverflow.com/questions/51053568/generating-a-random-uuid-in-c

I hope I've clarified the intentions of the request.

Thank you in advance,
Best regards,
Dan.

**Comment by DanApostol** [comment]
Hello. Any other thoughts about the topic?

Thanks again,
Dan.
