### ISSUE TITLE
Building Envoy version 1.22.x on CentOS 7 and the best approach?

### ISSUE THREAD

**Issue by robejfarr** [envoyproxy/envoy#22365]
Yes CentOS 7 is pretty old, but we need to support it and run Envoy as best we can until it nears the end of it's maintenance window.

Building Envoy version 1.21.x onwards we run into the issues documented here: https://github.com/envoyproxy/envoy-build-tools/blob/main/build_container/CENTOS7_BUILD_STATUS.md with tcp_stats.cc using headers that are generally incompatible with CentOS 7. We do not use the ELRepo CentOS 7 Kernel enhancements.

Using this commit https://github.com/envoyproxy/envoy-build-tools/tree/8b1fc9f975395a90e856503bac17e38ea587921c in the envoy build tools repo we can compile version 1.22.x of Envoy if we comment out tcp_stats.

```
file: source/extensions/extensions_build_config.bzl
213     #"envoy.transport_sockets.tcp_stats":                "//source/extensions/transport_sockets/tcp_stats:config"
```

This is similar to the approach that Istio and others took when they disabled this feature depending on the OS they are building for e.g. https://github.com/istio/istio/issues/35742

I've raised this issue to check if there are any other approaches we should investigate, implications to doing this that we should be aware of or recommendations to try out? @ggreenway I know you worked on the changes if you have any thoughts or anyone else?

Otherwise if there's no other approaches suggested we'll test this change out more thoroughly and then look to update the details at https://github.com/envoyproxy/envoy-build-tools/blob/main/build_container/CENTOS7_BUILD_STATUS.md with this recommendation.

In the future we'll have a look at version 1.23 and see if we can move that envoy-build-tools commit hash further forward (which is probably unlikely) @acarlson0000  FYI.

**Comment by ggreenway** [comment]
If your kernel headers are too old to compile, it seems fine to disable that extension in your build. I don't think it makes sense to change the extension to work with extremely old kernels.

**Comment by narendrapatel** [comment]
Hi @robejfarr 
Were you able to test the version upgrade.
We currently have some systems on Centos 7 and need to upgrade envoy from 1.20 to 1.21+.

**Comment by acarlson0000** [comment]
@narendrapatel - we ended up just building the latest versions and disabling the extensions which don't compile (ie. `tcp_stats` as mentioned in Robs initial PR issue)
