### ISSUE TITLE
`test/common/quic/platform/quic_platform_test` times out and fails

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22382]
example failure:

```console
INFO: 29581 processes: 17191 remote cache hit, 11058 internal, 1 local, 1331 remote.
//test/common/quic/platform:quic_platform_test                          TIMEOUT in 2 out of 2 in 305.0s
  Stats over 2 runs: max = 305.0s, min = 301.8s, avg = 303.4s, dev = 1.6s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-opt/testlogs/test/common/quic/platform/quic_platform_test/test.log
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-opt/testlogs/test/common/quic/platform/quic_platform_test/test_attempts/attempt_1.log
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=113584&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=1025

according to azp analytics this test has failed 1/1 times in the last 14 days

https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build

**Comment by phlax** [comment]
cc @RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
Hm. I don't think I understand that data here:

https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build

This seems to show it only failed once in the last 30 days but shows 0 other runs. Do you understand how to interpret that data? (In particular, I don't think anything has changed with this recently so I don't *think* anything has gotten worse, but who knows :>)

**Comment by phlax** [comment]
im pretty sure i have seen this failing previously so i also dont think its new - but the azp evidence suggests that it never passes

not sure why it shows it as only having run once - i have tried putting all filters on (ie include passing etc) and searching for the failing test - but it never seems to show anything different

it could be that its not a direct target so it shows if it fails but not if it passes - but that is just conjecture

either way  - i think this is test is at least flakey if not permafailing so would be good to address

**Comment by phlax** [comment]
also re azp fail analytics - you can post a link with filters or subpages etc - it always just points back to the main page - otherwise i would have posted what i was actually looking at

**Comment by RyanTheOptimist** [comment]
Hm, I don't think the azp evidence suggests that it never passes, does it? I think it says that it's failed once in the past 30 days. It could have also failed other times, but there is no data either way on that front, annoyingly. If it *never* passed then it would block PRs, right?

The log shows a timeout in the QuicThread test so a deadlock in that test is certainly plausible. I'll do some digging.

(Sorry about the useless URL. I totally missed that. :<)

**Comment by phlax** [comment]
> Hm, I don't think the azp evidence suggests that it never passes, does it? 

it has failed 1/1 times - 0% pass rate

![quic-fail](https://user-images.githubusercontent.com/454682/180852490-d6203703-b940-4922-9efb-d831395bc6fd.png)

**Comment by RyanTheOptimist** [comment]
Heh, sure. But my point is that I'm confident this test has run WAY more than 1 time over the last 30 days.

**Comment by phlax** [comment]
>  I'm confident this test has run WAY more than 1 time over the last 30 days.

i would have thought so too - but that is what im getting from azp - not sure how to understand that
