### ISSUE TITLE
'envoy --version' should provide actual version, ex: 1.5.0

### ISSUE THREAD

**Issue by ikruglov** [envoyproxy/envoy#2239]
*Title*: 'envoy --version' should provide actual version, ex: 1.5.0

*Description*:
currently 'envoy --version' provides you with an SHA which is not much useful for end users. I would expect to see a version such as "1.5.0" there.

Something like:
```
envoy --version
version: 1.5.0
tag: a8507f67225cdd912712971bf72d41f219eb74ed/Modified/RELEASE
```

**Comment by taiki45** [comment]
I'm working on this. I'm thinking just simply put `VERSION` file of which content is `1.6.0.dev`, then read that in build phase. WDYT?

[The first try](https://github.com/taiki45/envoy/commit/479c4636a2b0fe55a41da07ccb10dbe9b7ba98b4) is using `bazel/get_workspace_status` but [it seems bazel only supoprt specific keys](https://github.com/bazelbuild/bazel/blob/3d1a194ff9e76f25f1a7242ff2d021523ba8e4a0/src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java#L352-L357).
So next try will be using genrule. Please tell me any advices if you have.

**Comment by mattklein123** [comment]
Honestly I would probably just hard code it in the code and we can bump it in each release:
https://github.com/envoyproxy/envoy/blob/master/source/common/common/version.h

You could add a new member there called `release_version` or something like that, or potentially rename some of those variables to be more clear.
