### ISSUE TITLE
Lua: request_handle:respond() ignores custom response headers

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#22401]
It's not possible anymore to set custom response headers with `request_handle:respond()`. Example from the [manual](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter):
```
  -- Response directly and set a header from the HTTP call. No further filter iteration
  -- occurs.
  request_handle:respond(
    {[":status"] = "403",
     ["upstream_foo"] = headers["foo"]},
    "nope")
```

Since commit ccd5c74deff305fe7b1b648f682e09368c1e85b1, `respond()` only sets the ":status" header and ignores the other headers like "upstream_foo".

In the code, the headers are only handled in the (now deprecated) "else" branch:
```
void Filter::DecoderCallbacks::respond(Http::ResponseHeaderMapPtr&& headers, Buffer::Instance* body,
                                       lua_State*) {
  if (Runtime::runtimeFeatureEnabled(
          "envoy.reloadable_features.lua_respond_with_send_local_reply")) {
    uint64_t status = Http::Utility::getResponseStatus(*headers);
    callbacks_->sendLocalReply(static_cast<Envoy::Http::Code>(status), body ? body->toString() : "",
                               nullptr, absl::nullopt, HttpResponseCodeDetails::get().LuaResponse);
  } else {
    callbacks_->encodeHeaders(std::move(headers), body == nullptr,
                              HttpResponseCodeDetails::get().LuaResponse);
    if (body && !parent_.destroyed_) {
      callbacks_->encodeData(*body, true);
    }
  }
}
```

**Comment by zuercher** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
Thanks for calling this out.

**Comment by wbpcode** [comment]
cc @StarryVae Would you be able to take a look for this?

**Comment by StarryVae** [comment]
Yes, i will fix this, thanks @wbpcode

**Comment by mpuncel** [comment]
@StarryVae are you still planning on looking into this?

**Comment by StarryVae** [comment]
> @StarryVae are you still planning on looking into this?

Yes, i will push a PR today.

**Comment by mpuncel** [comment]
This issue should be closed, right?
