### ISSUE TITLE
Tests flaking due to dockerhub issues - eg `run_envoy_docker` and sandboxes

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22404]
CI fails fairly frequently due to bad dockerhub endpoint:

```console
Generating script.
Script contents:
ci/run_envoy_docker.sh 'ci/upload_gcs_artifact.sh /source/generated/fuzz_coverage fuzz_coverage'
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /srv/azure-pipelines/_work/_temp/8788096c-b5e6-4a3b-8f8a-3c150786c997.sh
Error response from daemon: Get https://registry-1.docker.io/v2/: EOF

```
https://dev.azure.com/cncf/envoy/_build/results?buildId=113688&view=logs&j=7b6d60aa-b5de-5f9b-678c-063d31881e76&t=0c8bcd19-14ac-5aba-0af8-facf9399c298&l=14

as this seems to be a transient issue that resolves quickly, we could probably mitigate this with a retry in `run_envoy_docker`

**Comment by phlax** [comment]
we could also remove any unnecessary use of it - eg in the artefact upload jobs

**Comment by phlax** [comment]
cc @lizan

**Comment by daixiang0** [comment]
Another idea is that we host image tarball at our side if run in CI env, load it when use since CI image won't change often.

**Comment by phlax** [comment]
> Another idea is that we host image tarball at our side

its not that simple - the docker image is huge and the cache is not much faster than the pulling directly from dockerhub

essentially, it _can_ be faster doing this but iff there are no additonal steps required (a big iff)

see #22093 for an implementation

**Comment by phlax** [comment]
This problem seems to be happening across images and randomly but fairly frequently so ive opened an upstream ticket here https://github.com/docker/hub-feedback/issues/2262

**Comment by daixiang0** [comment]
@phlax seems we need to add retry step to fix flake tests.

**Comment by phlax** [comment]
> @phlax seems we need to add retry step to fix flake tests.

the problem with adding a retry - apart from being an imperfect solution that may/not work, is that the envoy-build image is one of many cases where we are pulling images, so just adding a retry on that is not going to resolve the problem

**Comment by phlax** [comment]
one observation is that the bigger image that its pulling, the more likely to fail - which i think is why we see this more frequently with the envoy-build image and skywalking, jaeger, etc

another point of note here is that while the dockerhub issue is by far the biggest flake atm for verify examples - this can also flake on debian/ubuntu updates and pip downloads 

i think shifting the verify tests to incremental testing would not only reduce the workload/transfer that we are placing on dockerhub, but would also mitigate some of these other transients also
