### ISSUE TITLE
Bazel version 6.0.0-pre.20220630.1 is unstable

### ISSUE THREAD

**Issue by tomjzzhang** [envoyproxy/envoy#22406]
Envoy's bazel version was upgraded to 6.0.0-pre.20220630.1 in https://github.com/envoyproxy/envoy/pull/22295.

This version is prone to crashing (See https://github.com/bazelbuild/bazel/commit/107a54edcf75dc026cf643df82c13fe32a1eb043) and crashed when building [nighthawk](https://github.com/envoyproxy/nighthawk). A crash example can be found [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=113646&view=logs&j=2c70e2d0-f13f-5d14-907c-1dc6364dc4d9&t=36a82f6f-e50d-5d51-945d-346e5386dd14)

Upgrading to the next [release ](https://github.com/bazelbuild/bazel/releases/tag/6.0.0-pre.20220706.4), seems to resolve the issue. 

As a downstream consumer of Envoy, Nighthawk would like to sync bazel versions as closely as possible and as a result would like Envoy to move off of this version.

**Comment by tomjzzhang** [comment]
tagging @mum4k as owner of Nighthawk

**Comment by phlax** [comment]
cc @keith 

@tomjzzhang do you want to raise a PR to address ?

**Comment by keith** [comment]
should be us still, fine to update tho, we can merge https://github.com/envoyproxy/envoy/pull/22412 once it's green
