### ISSUE TITLE
Listeners aren't updated when the LDS config file is copied (as opposed to being moved)

### ISSUE THREAD

**Issue by jvshahid** [envoyproxy/envoy#2241]
*Description*:

We are trying to use file watchers to updated the listeners config, specifically the cert/key of the listener. Until V2 we were using v1 LDS. When the `listeners.yaml` is ~~updated~~ copied (as opposed to moved) envoy fails to recreate the listeners with the new configuration.

*Repro steps*:

The following setup has two listeners configurations each using a different cert/key and specify a different stat prefix (something that we used to do previously with the V1 LDS to force recreation of the listeners since in our setup the path to the cert/key don't change)

Assuming you have the files in [this gist](https://gist.github.com/jvshahid/10e4ffb04cc69addbf7a38a56fd426a9) in `/envoy_config`:

```bash
cd /envoy_config
cp listeners-1.yaml listeners.yaml # creates listeners.yaml which is used in the config
./envoy -c config.yaml --v2-config-only --service-cluster some-cluster --service-node some-node --log-level debug --drain-time-s 2 # start envoy
openssl s_client -connect localhost:61001 </dev/null 2>&1 | grep CN | head -n1 # outputs depth=0 CN = server.1

# switch the configurations

cp listeners-2.yaml listeners.yaml
openssl s_client -connect localhost:61001 </dev/null 2>&1 | grep CN | head -n1 # outputs depth=0 CN = server.1 instead of server.2

# restart envoy to make sure the configuration is correct

pkill -f envoy && ./envoy -c config.yaml --v2-config-only --service-cluster some-cluster --service-node some-node --log-level debug --drain-time-s 2 # restart envoy
openssl s_client -connect localhost:61001 </dev/null 2>&1 | grep CN | head -n1 # outputs depth=0 CN = server.2 
```

**Note**: Replacing the above `cp listeners-2.yaml listeners.yaml` with `mv listeners-2.yaml listeners.yaml` works as expected

*Config*:

Shared above in the repro steps

**Comment by mattklein123** [comment]
@htuch do you mind taking a look a this when you are back from vacay?

**Comment by htuch** [comment]
@jvshahid what happens if you `mv` instead of `cp`? I think we're only watching for move events right now, could improve this.

**Comment by jvshahid** [comment]
@htuch i think we tried that initially, but I cannot tell for sure. I will try it again and let you how know if that worked.

**Comment by ggreenway** [comment]
I think we should probably also watch for IN_CLOSE_WRITE, and possibly IN_CREATE.

**Comment by jvshahid** [comment]
moving the files seems to be working. Is everyone ok if I updated the title of the github issue ?

**Comment by mattklein123** [comment]
@jvshahid go for it.

**Comment by mattklein123** [comment]
@jvshahid in general copy is not safe as it isn't atomic. WDYT about a doc update somewhere to fix this?

**Comment by jvshahid** [comment]
sgtm

**Comment by mattklein123** [comment]
doc fix in https://github.com/envoyproxy/data-plane-api/pull/429
