### ISSUE TITLE
xDS protocol question: when can resources be "forgotten"?

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#22418]
*Title*: *xDS protocol question: when can resources be "forgotten"?*

*Description*:
In the [Subscribing to Resources](https://www.envoyproxy.io/docs/envoy/v1.23.0/api-docs/xds_protocol#subscribing-to-resources) of the xDS protocol spec it says

> However, the server must still provide those resources in the response; due to implementation details hidden from the server, the client may have “forgotten” those resources despite apparently remaining subscribed.

Under what circumstances can this happen? I think I'm hitting one now when Envoy reconnects and gives me its versions of ClusterLoadAssignment in some cases my management server doesn't reply because Envoy already has the right version. I then notice `503 UH` on upstreams. A config dump shows the right number of EDS entries but missing their `endpoints`. They look like this

```json
        {
          "endpoint_config": {
            "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
            "policy": {
              "overprovisioning_factor": 140
            }
          }
        },
```

instead of this

```json
        {
          "endpoint_config": {
            "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
            "endpoints": [
              {
                "locality": {},
                "lb_endpoints": [
                  {
                    "endpoint": {
                      "address": {
                        "socket_address": {
                          "address": "172.30.91.149",
                          "port_value": 8080
                        }
                      },
                      "health_check_config": {}
                    },
                    "health_status": "HEALTHY",
                    "load_balancing_weight": 1
                  }
                ]
              }
            ],
            "policy": {
              "overprovisioning_factor": 140
            }
          }
        },
```

**Comment by zuercher** [comment]
After a cluster change Envoy will issue an EDS request and if it doesn't receive a response within the configured `initial_fetch_timeout` it will start using the cluster with no endpoints, which results in the 503 UH responses.

There is a lengthy discussion here: https://github.com/envoyproxy/envoy/issues/13009

**Comment by phylake** [comment]
Thanks @zuercher for the quick reply. After reading through that discussion I've made a change to always send EDS when CDS changes but I still get `503 UH` as well as increased Envoy CPU usage. It's like sending EDS before Envoy processed the CDS reply and wanted to subscribe is causing a similar issue for a different reason.

**Comment by phylake** [comment]
Thanks @zuercher for confirming the `503 UH` and for the link. I was surprised it was a `UH` because the endpoint data is gone. I would have expected a `UF,URX` like you get when endpoint data is bad. `UH` confusingly told me that Envoy had the endpoint data and was performing a health check that the upstream was failing

**Comment by phylake** [comment]
@zuercher is there any issue sending EDS before Envoy asks for it? I'm wondering if sending EDS after CDS but before the EDS DeltaDiscoveryRequest arrives is ok. I'm using Incremental ADS so I expect the Send calls to arrive in the order I sent them

**Comment by zuercher** [comment]
IIRC the response flags for the 503s are “no healthy upstream” which in this case means no upstreams. 

I think immediately sending a new EDS response after the CDS response is ok, but our control plane is SotW and waits for the EDS request so it’s probably best to test it.

**Comment by phylake** [comment]
When I send EDS right after CDS (before the CDS ACK) I start getting `503 UF,URX`

**Comment by phylake** [comment]
This is why
`// [warning][config] [source/common/config/new_grpc_mux_impl.cc:83] Dropping received DeltaDiscoveryResponse (with version ) for non-existent subscription type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment.`

**Comment by phylake** [comment]
Now I'm hitting a similar issue with SDS. A reconnecting Envoy puts secrets that it already had into `dynamic_warming_secrets`. Because of the following
> On reconnect the Incremental xDS client may tell the server of its known resources to avoid resending them over the network by sending them in [initial_resource_versions](https://www.envoyproxy.io/docs/envoy/v1.21.4/api-v3/service/discovery/v3/discovery.proto#envoy-v3-api-field-service-discovery-v3-deltadiscoveryrequest-initial-resource-versions)

My management server isn't resending secrets that haven't changed. This doesn't happen consistently though

**Comment by phylake** [comment]
@adisuissa @phlax sorry for the direct ping. I found your contributions to this section of the docs. Do you have any insight here?

**Comment by phylake** [comment]
> However, the server *must* still provide those resources in the response; due to
> implementation details hidden from the server, the client may have "forgotten"
> those resources despite apparently remaining subscribed.

@ramaraochavali hoping you can speak to what you wrote and shed some light on this for me

**Comment by adisuissa** [comment]
It seems the issue is with warming resources that are dependent on others. For example, there is CDS->EDS warming where a cluster if first fetched, and not made active (in "warming" mode), and the EDS endpoints are requested. If the EDS response arrives on time, the cluster is made "active", and Envoy can use it. If the EDS response doesn't arrive after some time, the cluster is made "active" but won't have actual endpoints in it.

When Envoy reconnects, do you also observe the `initial_resource_versions` of the EDS as well as the CDS resources?

Relevant issues could also be: #19262, and #14000.

**Comment by phylake** [comment]
> When Envoy reconnects, do you also observe the `initial_resource_versions` of the EDS as well as the CDS resources?

Yes I do and if the versions weren't different then EDS wasn't sent. This led to the `503 UH` after `initial_fetch_timeout`

These two statements in the spec seem contradictory

> On reconnect the Incremental xDS client may tell the server of its known resources to avoid resending them over the network by sending them in `initial_resource_versions`
> ...
> A `resource_names_subscribe` field may contain resource names that the server believes the client is already subscribed to, and furthermore has the most recent versions of. However, the server must still provide those resources in the response; due to implementation details hidden from the server, the client may have “forgotten” those resources despite apparently remaining subscribed.

On an Envoy reconnect I am _not_ sending resources in the DeltaDiscoveryRequest's `resource_names_subscribe` because they're in `initial_resource_versions` with the correct version and Envoy is sometimes "forgetting" them, leading to all sorts of issues

**Comment by phylake** [comment]
@htuch @markdroth I see significant contributions to `xds_protocol.rst` as well. Can you help? As of right now I can't use `initial_resource_versions` which was a significant optimization for reconnecting Envoys

**Comment by adisuissa** [comment]
I'm not certain why those assignment disappear.
Assuming there's no TTL, and that these ClusterLoadAssignments are not fetched from a wildcard, the only thing I can think of is that an update for the Clusters is received (which causes some of the clusters to move to a warming state), and the relevant ClusterLoadAssignments do not arrive on time, and so the problem mentioned in #13009 occurs.

**Comment by markdroth** [comment]
I suspect that the majority of the problem here is the bad behavior in Envoy described in #13009.  Once Envoy implements the caching layer described there, there should no longer be any cases where the client is subscribed to a resource but does not have it locally cached.
