### ISSUE TITLE
Missing Note Section in SXG and VCL Socket interface

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#22443]
*Title*: *I think Note Section should be present docs in SXG and VCL section which describe "`These features are not supported on Windows."`*

*Description*:
urls are 
https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/http/http_filters/sxg_filter#config-http-filters-sxg
https://www.envoyproxy.io/docs/envoy/v1.23.0/configuration/other_features/vcl#config-sock-interface-vcl

**Comment by daixiang0** [comment]
@envoyproxy/envoy-maintainers  please close as it is fixed.
