### ISSUE TITLE
admin page could be a little more user-friendly

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2246]
*Description*:
The admin page has some nice functionality in it, but could be trivially made much easier to use:

- all commands should be links
- mutating commands should be a POST so a crawler doesn't alter state (or quit)
- stats could be just delivered as text rather than html (changing content-type)
- simple table layout

optionally it could be css-styled but just having it be functional would be nice.

E.g. this:

Command | Description
-- | --
[/](http://example.com/) | admin home page
[/certs](http://example.com/certs) | print certs on machine
[/clusters](http://example.com/clusters) | upstream cluster status
[/cpuprofiler](http://example.com/cpuprofiler) | enable/disable the CPU profiler
[/healthcheck/fail](http://example.com/healthcheck/fail) | cause the server to fail health checks
[/healthcheck/ok](http://example.com/healthcheck/ok) | cause the server to pass health checks
[/hot_restart_version](http://example.com/hot_restart_version) | print the hot restart compatability version
[/listeners](http://example.com/listeners) | print listener addresses
[/logging](http://example.com/logging) | query/change logging levels
[/quitquitquit](http://example.com/quitquitquit) | exit the server
[/reset_counters](http://example.com/reset_counters) | reset all counters to zero
[/routes](http://example.com/routes) | print out currently loaded dynamic HTTP route tables
[/server_info](http://example.com/server_info) | print server version/status information
[/stats](http://example.com/stats) | print server stats

Rather than this:

envoy admin commands: /certs: print certs on machine /clusters: upstream cluster status /cpuprofiler: enable/disable the CPU profiler /healthcheck/fail: cause the server to fail health checks /healthcheck/ok: cause the server to pass health checks /hot_restart_version: print the hot restart compatability version /listeners: print listener addresses /logging: query/change logging levels /quitquitquit: exit the server /reset_counters: reset all counters to zero /routes: print out currently loaded dynamic HTTP route tables /server_info: print server version/status information /stats: print server stats

**Comment by mattklein123** [comment]
@jmarantz this sounds interesting but FYI I think the vast majority of people use the CLI on localhost via curl/grep/etc. We will need to retain the current purely text based output. Having a browser friendly output also sounds interesting but I think that should be opt-in or maybe even accessed over a differently configured admin port.

**Comment by jmarantz** [comment]
What I was thinking was not to change the response body at all for any existing handler, but just to add a new "/" handler which would generate HTML.  I'd leave the fallback as is.

I was thinking I'd change the content-type header in the other responses because it's currently text/html and it would look a lot better in browsers if it were text/plain, or in the case of json it should be application/json

**Comment by jmarantz** [comment]
As I dig deeper I find that it's not easy to set content-type or caching policy on admin responses because that's not in the definition of HandlerCb in https://github.com/envoyproxy/envoy/blob/master/include/envoy/server/admin.h .  I'm not sure if it's feasible to change that interface; there are only a couple of usages in Envoy src, but it look like having an admin-handler only return text and status is part of the V2 API definition.  Is that right?

IMO if nothing else we should make the admin handlers have default content-type:text/plain rather than text/html for UI and also XSS protection.

For now I'll go that way but give the internal "/" handler a backdoor to generate HTML, and we can discuss on the PR.

**Comment by mattklein123** [comment]
> I'm not sure if it's feasible to change that interface; there are only a couple of usages in Envoy src, but it look like having an admin-handler only return text and status is part of the V2 API definition. Is that right?

Nope, nothing about admin is currently defined via proto (though we would like to change that). Go wild!
