### ISSUE TITLE
Is it possible to redirect TCP traffic based on the original destination?

### ISSUE THREAD

**Issue by wywan-lv** [envoyproxy/envoy#22462]
I use iptables to 'redir ports' to 15001, which envoy listens on. I want to redirect TCP traffic based on the original destination.
```
if ( ori_dst_ip == "TARGET-IP" )   (e.g. 1.1.1.1)
     redirect to static destination (e.g. 2.2.2.2)
else 
    cluster ORIGINAL_DST  (pass through)
```
When some process sends TCP packet to 1.1.1.1 (configured as TARGET-IP),  it will be redirect to another destination (e.g. 2.2.2.2). When some process sends TCP packet to other destination (e.g. 10.10.10.10), it will pass through to ORIGINAL_DST (10.10.10.10 in this case)

I found TcpProxy filter in API-v3 may help, but it does not support destination configuration. It redirects all the TCP traffic to the specific cluster.

I found some informations about "config.filter.network.tcp_proxy.v2.TcpProxy.DeprecatedV1.TCPRoute" filter, but it does not exist in API-v3 any more.

So, Is it possible to redirect TCP traffic based on the original destination?

Thanks for help.

**Comment by kyessenov** [comment]
Yes, you can accomplish this using:
* `original_dst` listener filter https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/original_dst/v3/original_dst.proto#extensions-filters-listener-original-dst-v3-originaldst,
* `original_dst` load balancer https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/original_dst
* listener filter chain match to separate connections based on the destination address

**Comment by wywan-lv** [comment]
>

**Comment by wywan-lv** [comment]
> Yes, you can accomplish this using:
> 
> * `original_dst` listener filter https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/original_dst/v3/original_dst.proto#extensions-filters-listener-original-dst-v3-originaldst,
> * `original_dst` load balancer https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/original_dst
> * listener filter chain match to separate connections based on the destination address

It works, thanks a lot.   : )
