### ISSUE TITLE
Support for header based stateful session

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#22475]
Currently stateful session supports cookie based [session management](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/stateful_session_filter).

It would be useful to extend this to header based session management as cookies have some assumed default behaviour with browsers and not work well with tabs.

The proposal is to add header based stateful session support in the following ways.
1. Similar to cookie, Envoy can generate the header and encode the host ip:port where caller is expected to pass it on every request. This works similar to cookies except that it is not a special header and hence no default behaviour assumed.
2. Implement an in memory cache (backed by external cache like redis) that Envoy can lookup. 
 
#2 needs more thought on what key should be used and how to provide integration with external cache etc. But #1 is simpler to implement and people who are willing to build client side solution to keep track of the header and pass on every request can benefit from this (This is actually our main use case as we have client specific code that can send the header on every request).

**Comment by ramaraochavali** [comment]
discussed offline with @wbpcode  and he is generally OK with this.

**Comment by alyssawilk** [comment]
cc  @cpakulski as the other co-owner

**Comment by wbpcode** [comment]
#1 is easy to implemented and useful for some cases. But is there a standard way to notify the client to send a special header like cookie? 

Or there will be two configurable header names (one name will be used by the envoy to set response header at first request, one name will be used in the requests) ?

**Comment by ramaraochavali** [comment]
> But is there a standard way to notify the client to send a special header like set-cookie?

I am not aware of any

>or there will be two configurable header names (one name will be used by the envoy to set response header at first request, one name will be used in the requests) ?

I was thinking one header where envoy will set if it is not present and client will use the same header name in subsequent requests. Would it complicate things?

**Comment by wbpcode** [comment]
> I was thinking one header where envoy will set if it is not present and client will use the same header name in subsequent requests. Would it complicate things?

IMO, I think a pair of headers would be more clear.

---

But the key point is if there is no way to notify the client, then only some custom clients that aware the configured special headers can get helps from this header based session. Then may be we shouldn't add it to the core envoy but just keep it as a private extension for yourself?

**Comment by ramaraochavali** [comment]
> But the key point is if there is no way to notify the client, then only some custom clients that aware the configured special headers can get helps from this header based session. 

I think as long as the header name (pair of headers as you described) are configurable, I think it is generic enough. It is exactly similar to cookie, but the header names change.

**Comment by wbpcode** [comment]
> I think as long as the header name (pair of headers as you described) are configurable, I think it is generic enough. It is exactly similar to cookie, but the header names change.

May be as you said, it's does helpful for some users.

**Comment by ramaraochavali** [comment]
@wbpcode Can you please assign this to @Pawan-Bishnoi ?

**Comment by wbpcode** [comment]
Sorry, seems that @Pawan-Bishnoi is not member of this org. So i cannot assign this issue to him.

**Comment by ramaraochavali** [comment]
Ah. I remember. Only few people can add members to the org. @mattklein123 Can you please add @Pawan-Bishnoi  to the org and assign this issue?

**Comment by Pawan-Bishnoi** [comment]
@mattklein123 please assign this to me 😄 
Thank you!

**Comment by cpakulski** [comment]
I think that `stateful_session` filter could be easily extended for this use case. 

If I understood the idea correctly, the difference comparing to the current `stateful_session` is to automatically generate a new name instead of using a hardcoded one coming from the config (https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/http/v3/cookie.proto#envoy-v3-api-msg-type-http-v3-cookie) for each new connection and pass it back to the client via response headers.

**Comment by Pawan-Bishnoi** [comment]
@cpakulski The header name should come from config (similar to cookie name). For example:
```
http_filters:
 - name: envoy.filters.http.stateful_session
   typed_config:
     "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
     session_state:
       name: envoy.http.stateful_session.header
       typed_config:
         "@type": type.googleapis.com/envoy.extensions.http.stateful_session.header.v3.HeaderBasedSessionState
          header:
            name: x-sticky-session-custom-header
            path: /session/v1/
```
