### ISSUE TITLE
CI sync job races

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22478]
If 2 PRs are landed in quick succession the "sync" job fails checking out and trying to commit back to the `envoy-filter-example` repo

**Comment by wrowe** [comment]
Do azure pipelines support serializing a build step, across builds? @lizan would you be familiar?

**Comment by phlax** [comment]
> Do azure pipelines support serializing a build step, across builds?

i dont think so

tbh im wondering about the downstream repo using a submodule for this given it has bazel also - sure it should use bazel to pull in the envoy repo

switching that wouldnt resolve by itself - but we could potentially use a PR (that gets updated) or somesuch to update the downstream rather than checkout/commit/push which is prone to racing

another option is adding a retry/rebase if the push fails

**Comment by phlax** [comment]
this has been resolved
