### ISSUE TITLE
Bootstrapping is not performing when enable xray tracing with service host instead of pod ip for envoy proxy

### ISSUE THREAD

**Issue by shanvipanda02** [envoyproxy/envoy#22479]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shanvipanda02** [comment]
Hi Team,
Our applications are deployed in AWS eks and we are using envoy proxy . To see the trace information, we have added xray Tracer ,when providing service host in daemon-endpoint address , it is returning error like malformed ip address . But when providing the pod ip of xray daemon we can see the trace information.Could any one please suggest how to fix the issue?

**Comment by alyssawilk** [comment]
cc @abaptiste @suniltheta @mattklein123

**Comment by abaptiste** [comment]
Hi,

It sounds like you are using a hostname for the X-ray endpoint.  If so, this is a known issue with the tracer.

In the X-ray [proto](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/trace/v3/xray.proto#L41) file the tracer expects the IP and port where the daemon is bound.  The recommended workaround is to use an `IP:port` value.

The App Mesh [documentation](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html) uses an IP for the X-ray endpoint.

cc: @suniltheta

**Comment by suniltheta** [comment]
This is an enhancement that is need in X-Ray tracer extension. Typically the X-Ray daemon is run as a sidecar of the application. In that case it is easy to specify 127.0.0.1 as the IP address. But in case where daemon is running as a separate service then it is impractical to give the IP address which can change.

**Comment by HLueckhoff** [comment]
One workaround for this problem: create a separate (loop back) listener that then connects to a cluster that does load balancing on top of the xray headless service. In the xray tracer config we simply configure the local IP of the loopback filter (which is stable) - so we don't have to worry about changing IP addresses. Happy to provide sample config if anyone is interested.

**Comment by suniltheta** [comment]
bump
