### ISSUE TITLE
Forward proxy configuration problem

### ISSUE THREAD

**Issue by houhuijian** [envoyproxy/envoy#22492]
I use nginx and envoy to test the proxy. The header passed from the superior contains x-fordwarded-host. In envoy or nginx,  need to configure the host to change to x-fordwarded-host to access it normally. Use nginx to add settings: `proxy_set_header Host $http_x_forwarded_host; `Use envoy to try to increase `host_rewrite_literal: xx.xx.xx` is also possible, but xx.xx.xx is stationary, can it be set to %x_forwarded_host% or there are other ways to achieve my goal, I hope to help solve it

**Comment by alyssawilk** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-host-rewrite-header may be what you're looking for?
