### ISSUE TITLE
How to use cpu usage as a way of resource monitors？

### ISSUE THREAD

**Issue by sjtuzbk** [envoyproxy/envoy#22495]
Envoy's resource monitors only supports memory.:

`extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig`

So why doesn't envoy support CPU as a resource monitor? Now I want to use cpu usage as resource monitor, how to do it?

**Comment by alyssawilk** [comment]
cc @KBaichoo

**Comment by KBaichoo** [comment]
why doesn't envoy support CPU as a resource monitor?
> No one has gotten around to doing so yet.

Now I want to use cpu usage as resource monitor
> I'm curious of the problem you're trying to solve with a CPU resource
> monitor, can you elaborate?

how to do it?
> Would be creating a resource monitor extension for CPU. You could get this
> information from a few places: /proc, getrusage(), netlink. Whether we want
> this per thread, or for the process is another element to dig into; e.g.
> it's possible that a single worker gets saturated but the others are idle. Whether to do cpu usage per client e.g. to prevent one client from dominating.
