### ISSUE TITLE
skywalking-tracing flaked on verify examples

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#22509]
Pretty sure I've seen this before but here's today's logs:'

https://dev.azure.com/cncf/envoy/_build/results?buildId=114129&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=14991

TESTS FAILED:
run_examples@ /home/vsts/work/1/s/ci/verify_examples.sh :39 (./skywalking-tracing)
  > main@ /home/vsts/work/1/s/ci/verify_examples.sh :44

**Comment by alyssawilk** [comment]
cc @phlax

**Comment by wbpcode** [comment]
```
2022-08-02T09:54:31.9626433Z Step 1/1 : FROM apache/skywalking-oap-server:latest@sha256:d8529d0363e3c761337e31ed84cdf0a71ad3ceb68418e9860a3adf8da38cc4e6
2022-08-02T09:54:37.2003073Z Get "https://registry-1.docker.io/v2/": EOF
2022-08-02T09:54:37.2027136Z Service 'skywalking-oap' failed to build : Build failed
```

**Comment by wbpcode** [comment]
Should we change the image pull policy to avoid frequent pulling to the docker hub? cc @phlax

**Comment by daixiang0** [comment]
related to https://github.com/envoyproxy/envoy/issues/22404, I think we can close it since the similar cause.

**Comment by phlax** [comment]
> Should we change the image pull policy to avoid frequent pulling to the docker hub?

that is certainly one of the approaches being considered (cf #22093 )

in the case of the sandboxes - caching his harder (huge amounts of diskspace/transfer involved) - and perhaps the best solution to at least mitigate is to make the testing incremental (cf #21935 )

> I think we can close this since the similar cause.

i agree - im going to change the title of #22404 - but lets focus the attention around these dockerhub issues there - and close the related tickets

(for ref the upstream issue is reported here https://github.com/docker/hub-feedback/issues/2262 - but i think we need to look at our end also and figure out how to reduce our burden on dockerhub)
