### ISSUE TITLE
Health check status could not be updated.

### ISSUE THREAD

**Issue by littlegreyzhang** [envoyproxy/envoy#22506]
*Title*: *Health check status could not be updated.*

*Description*:
>In synchronized health checks, the status should be updated normally and cannot be timed out.

*Repro steps*:
> Inherit and implement the following interfaces.
> ```::Envoy::Upstream::HealthCheckerImplBase::ActiveHealthCheckSession::onInterval()```
> ```
> void NewHealthChecker::NewActiveHealthCheckSession::onInterval() {
>   if (client_->syncSendHealthCheck() != 0) {
>     handleFailure(envoy::data::core::v3::ACTIVE);
>   } else {
>     handleSuccess();
>   }
> }
> ```

>**Note**: The [Problematic function code of envoy](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/health_checker_base_impl.cc#L413)
> ```
> void HealthCheckerImplBase::ActiveHealthCheckSession::onIntervalBase() {
>   onInterval();
>   timeout_timer_->enableTimer(parent_.timeout_);
>   parent_.stats_.attempt_.inc();
> }
> ```
> In my case, synchronous requests are used. When ```onInterval``` is called, the entire process is finished. Then enable ```timeout_timer_```, if ```timeout_time``` < ```interval_time```, it will certainly time out. So the question I want to ask is, can I enable ```timeout_timer_``` In front of ```onInterval```?

**Comment by alyssawilk** [comment]
looking at who touched that code last I don't think anyone is going to be sure, but you could give it a shot and if it doesn't work, have onInterval return a boolean for "should rearm"

**Comment by littlegreyzhang** [comment]
@mattklein123 Maybe you know?
