### ISSUE TITLE
ext_authz failed on verify examples

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#22510]
TESTS FAILED:
run_examples@ /home/vsts/work/1/s/ci/verify_examples.sh :39 (./ext_authz)
  > main@ /home/vsts/work/1/s/ci/verify_examples.sh :44
##[error]Bash exited with code '1'.

https://dev.azure.com/cncf/envoy/_build/results?buildId=114123&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6

given https://github.com/envoyproxy/envoy/issues/22509 I'm wondering if there's an infra issue here?  cc @phlax

**Comment by daixiang0** [comment]
Also docker pull EOF: https://dev.azure.com/cncf/envoy/_build/results?buildId=114123&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=2792

related to https://github.com/envoyproxy/envoy/issues/22404, I think we can close this since the similar cause.

**Comment by phlax** [comment]
> I think we can close this since the similar cause.

yep, agreed - lets focus on #22404 as they are all symptoms of the same cause
