### ISSUE TITLE
Dynamodb filter - request times out if not valid Dynamodb request

### ISSUE THREAD

**Issue by bgardner-noggin** [envoyproxy/envoy#22526]
*Title*: Dynamodb filter, request times out if not valid dynamodb request

*Description*:
> I am using envoy as a proxy for dynamodb to maintain keepalives to minimise KMS costs. However in future, I would like to be able to use this same proxy to proxy other services. If I have the dynamodb filter enabled though, a request which is not a valid dynamodb request, stalls

*Repro steps*:
> If I make a dynamodb request though my proxy, it all works fine, however if I attempt to retrieve the health check (which I am using here to confirm my SSL configuration is correct) then the client hangs until I terminate it.

*Config*:
> > Attached is my listener [listener.zip](https://github.com/envoyproxy/envoy/files/9247465/listener.zip)

*Logs*:
> Using the trace log level for the http component, the working POST to dynamodb shows 
`
[source/common/http/http1/codec_impl.cc:608] [C6] parsing 1312 bytes
[source/common/http/http1/codec_impl.cc:551] [C6] message begin
[source/common/http/conn_manager_impl.cc:304] [C6] new stream
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=Host value=dynamodb.ap-southeast-2.amazonaws.com
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=X-Amz-Target value=DynamoDB_20120810.GetItem
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=Content-Type value=application/x-amz-json-1.0
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=X-Amz-User-Agent value=aws-sdk-php/3.231.12
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=aws-sdk-invocation-id value=a1364024ecc7ea2f9edc567969b40bb8
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=aws-sdk-retry value=0/0
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=X-Amz-Date value=20220803T025121Z
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=X-Amz-Security-Token value=<hidden>
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=Authorization value=AWS4-HMAC-SHA256 <hidden>
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=User-Agent value=aws-sdk-php/3.231.12 OS/Linux/5.18.6-200.fc36.x86_64 lang/php/8.1.8 GuzzleHttp/7
[source/common/http/http1/codec_impl.cc:791] [C6] onHeadersCompleteBase
[source/common/http/http1/codec_impl.cc:509] [C6] completed header: key=Content-Length value=174
[source/common/http/http1/codec_impl.cc:1105] [C6] Server: onHeadersComplete size=11
[source/common/http/conn_manager_impl.cc:909] [C6][S3629974128683865710] request headers complete (end_stream=false):
... headers in here ...
[source/common/http/filter_manager.cc:525] [C6][S3629974128683865710] decode headers called: filter=envoy.filters.http.dynamo status=1
[source/common/http/http1/codec_impl.cc:890] [C6] message complete
[source/common/http/http1/codec_impl.cc:1195] [C6] body size=174
[source/common/http/filter_manager.cc:657] [C6][S3629974128683865710] decode data called: filter=envoy.filters.http.dynamo status=1
[source/common/http/filter_manager.cc:790] [C6][S3629974128683865710] request end stream
[source/common/http/filter_manager.cc:657] [C6][S3629974128683865710] decode data called: filter=envoy.filters.http.dynamo status=0
[source/common/http/filter_manager.cc:69] [C6][S3629974128683865710] continuing filter chain: filter=0x14bc7ee5ee10
[source/common/http/filter_manager.cc:525] [C6][S3629974128683865710] decode headers called: filter=envoy.filters.http.router status=1
[source/common/http/filter_manager.cc:657] [C6][S3629974128683865710] decode data called: filter=envoy.filters.http.router status=3
[source/common/http/http1/codec_impl.cc:658] [C6] parsed 1312 bytes
[source/common/http/http1/codec_impl.cc:608] [C7] parsing 433 bytes
[source/common/http/http1/codec_impl.cc:551] [C7] message begin
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=Server value=Server
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=Date value=Wed, 03 Aug 2022 02:51:21 GMT
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=Content-Type value=application/x-amz-json-1.0
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=Content-Length value=177
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=Connection value=keep-alive
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=x-amzn-RequestId value=<hidden>
[source/common/http/http1/codec_impl.cc:791] [C7] onHeadersCompleteBase
[source/common/http/http1/codec_impl.cc:509] [C7] completed header: key=x-amz-crc32 value=<hidden>
[source/common/http/http1/codec_impl.cc:1379] [C7] status_code 200
[source/common/http/http1/codec_impl.cc:1389] [C7] Client: onHeadersComplete size=7
[source/common/http/filter_manager.cc:1061] [C6][S3629974128683865710] encode headers called: filter=envoy.filters.http.dynamo status=1
[source/common/http/http1/codec_impl.cc:890] [C7] message complete
[source/common/http/filter_manager.cc:1226] [C6][S3629974128683865710] encode data called: filter=envoy.filters.http.dynamo status=1
[source/common/http/http1/codec_impl.cc:1460] [C7] message complete
[source/common/http/filter_manager.cc:1226] [C6][S3629974128683865710] encode data called: filter=envoy.filters.http.dynamo status=0
[source/common/http/filter_manager.cc:69] [C6][S3629974128683865710] continuing filter chain: filter=0x14bc7ee5eea0
[source/common/http/conn_manager_impl.cc:1525] [C6][S3629974128683865710] encoding headers via codec (end_stream=false):
`

> The failing GET on /health shows

`
[source/common/http/http1/codec_impl.cc:608] [C5] parsing 107 bytes
[source/common/http/http1/codec_impl.cc:551] [C5] message begin
[source/common/http/conn_manager_impl.cc:304] [C5] new stream
[source/common/http/http1/codec_impl.cc:509] [C5] completed header: key=Host value=dynamodb.ap-southeast-2.amazonaws.com
[source/common/http/http1/codec_impl.cc:509] [C5] completed header: key=User-Agent value=curl/7.82.0
[source/common/http/http1/codec_impl.cc:791] [C5] onHeadersCompleteBase
[source/common/http/http1/codec_impl.cc:509] [C5] completed header: key=Accept value=*/*
[source/common/http/http1/codec_impl.cc:1105] [C5] Server: onHeadersComplete size=3
[source/common/http/http1/codec_impl.cc:890] [C5] message complete
[source/common/http/conn_manager_impl.cc:909] [C5][S16189860593374715220] request headers complete (end_stream=true):
... headers in here ...
[source/common/http/filter_manager.cc:790] [C5][S16189860593374715220] request end stream
[source/common/http/filter_manager.cc:525] [C5][S16189860593374715220] decode headers called: filter=envoy.filters.http.dynamo status=1
[source/common/http/http1/codec_impl.cc:658] [C5] parsed 107 bytes
`

> So it is not proceeeding to invoke "decode body called". If I disable the dynamodb filter, then the GET to /health works and the logs show 

`[source/common/http/filter_manager.cc:790] [C0][S667946614570923969] request end stream
[source/common/http/filter_manager.cc:901] [C0][S667946614570923969] Sending local reply with details direct_response`

**Comment by bgardner-noggin** [comment]
This is running envoy in a docker container based off of envoyproxy/envoy-contrib:v1.23-latest

**Comment by alyssawilk** [comment]
unfortunately the dynamo filter was moved to contrib as it's unowned. we'd welcome a fix with tests but there's no one I can assign this issue over to :-(

**Comment by MdSahil-oss** [comment]
@alyssawilk Do you think? It's a good-first-issue to start contribution to envoy, if so then assign this issue to me, I would like to start contributing to envoy with this issue.

**Comment by alyssawilk** [comment]
I don't know unfortunately as I'm not familiar with the code.  I'll assign it your way for now, and you can always back out if it turns out to be complex, and thanks for being willing to give it a shot!
