### ISSUE TITLE
support higher granularity weighting in WeightedCluster

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#2253]
Currently [weighted clusters](https://www.envoyproxy.io/docs/envoy/latest/api-v2/rds.proto.html#envoy-api-msg-weightedcluster) must have weights that sum to 100. This limits the minimum percentage of traffic that can be sent to a weighted cluster to 1%.

We'd like to be able to select weights less than 1% (in addition to finer control than 1% increments).

It seems that the existing total weight limit stems from a combination of not wanting to (re)compute the total each time a cluster is selected (`RouteEntryImplBase::clusterEntry`) and the ability to modify cluster weights via the runtime configuration system. Absent runtime configuration of weights, the total weight could be computed in the `RouteEntryImplBase` constructor and then used during selection.

I propose to add a field to the WeightedCluster proto that allows an optional `total_weight` to be specified, defaulting to 100 for backwards compatibility. Would need to remove the <= 100 validation on the weights and update documentation in several places as well. The new total weight would be used in place of `RouteEntryImplBase::WeightedClusterEntry::MAX_CLUSTER_WEIGHT`, but otherwise the existing cluster selection code would remain as is.

(I discarded the idea of making the total weight itself a runtime-configurable value because it requires the runtime configuration and LDS implementation to agree on the value in order to produce valid configurations. I've also assumed removing runtime configuration of cluster weights is not a viable option.)

**Comment by mattklein123** [comment]
@zuercher +1. Unfortunately we've (I) done a poor job of being consistent about random chance %. In some places it's out of 100, in some places out of 10,000. Anyway, this sounds like a reasonable proposal to me.
