### ISSUE TITLE
protobuf NullValue is not properly transcoded

### ISSUE THREAD

**Issue by fdfzcq** [envoyproxy/envoy#22531]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: `google.protobuf.NullValue` is not properly transcoded

*Description*:
While using `envoy.filters.http.grpc_json_transcoder` with envoy image `envoyproxy/envoy:v1.22.1` we noticed that `google.protobuf.NullValue` was transcoded to its literal enum value instead `null` as [its doc](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L83) suggests.

To give an example, we have a gRPC service with the following response message:
``` protobuf
message ConcatResponse {
    string blablabla = 1;
    google.protobuf.NullValue null = 2;
}
```
But when calling the service via a transcoding sidecar, we got
```json
{
 "blablabla": "foobar",
 "null": "NULL_VALUE"
}
```
Maybe this is by design but its inconsistency has proven problematic for us. Setting `always_print_primitive_fields` to `true` hides this field but that's not an option for us either. 

*Repro steps*:
You can run a service with the given protobuf example above.

*Config*:
```json
{
    "name": "envoy.filters.http.grpc_json_transcoder",
    "typed_config":
    {
        "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder",
        "proto_descriptor": "tmp/proto.pb",
        "services":
        [
            "spotify.concat.v1.ConcatService"
        ],
        "print_options":
        {
            "add_whitespace": true,
            "always_print_primitive_fields": true
        },
        "auto_mapping": true,
        "convert_grpc_status": true
    }
}
```

**Comment by alyssawilk** [comment]
cc @qiwzhang @lizan @adisuissa

**Comment by lizan** [comment]
Per [its doc] the message `google.protobuf.NullValue` is intended to use as `oneof` within `google.protobuf.Value`. What if the message is:
```
message ConcatResponse {
    string blablabla = 1;
    google.protobuf.Value null = 2;
}
```

and you set a null there?

This might be a protobuf issue and I didn't find a proper test case in [its implementation](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/util/json_util_test.cc).

**Comment by fdfzcq** [comment]
Thank you @lizan using `google.protobuf.Value` returned the correct JSON null, I'll close the issue then.
