### ISSUE TITLE
redis proxy mode (en-)forcing no eviction and configurable&consistent key->server mapping

### ISSUE THREAD

**Issue by chadm-sq** [envoyproxy/envoy#22551]
This might be a general overview ticket that is split into discrete parts. I consolidate here for discussion.

*Title*: *redis proxy mode with no cluster eviction and configurable&consistent key->server mapping*

*Description*:

Some of us poor souls use Redis as a primary data store, not as a cache.

I'd like to propose a different focus that the redis filter could permit. Namely, 1) different focus on selection of a database host based on a key, and the selection of the server is more tunable and is locked and doesn't misplace data; and 2) a different idea of the load to be balanced, that the load is the bulk of data, not the transit of data through to interchangeable DBs.

---

In the redis-as-cache scheme, db hosts can come and go, with a server addition or subtraction causing the selection ring to be resized and a small fraction of requests to miss cache and be re-homed in the newly-offset host list. The benefit is that db health is mostly irrelevant and the pool is always available, though perhaps incorrect. (A way it can be incorrect is DB host X fails, is removed from the pool, some of its keys are updated on another db host, and then X rejoins the pool, still owning the un-updated values, giving out old results.)

I'd like an explicit configuration setting that values permanence and consistency, over availability and willingness to be wrong. It locks the key-server mapping and doesn't let it mutate. Additionally, when set, configuration settings that are incompatible with predictable key placement, like round-robin load-balancing selection or health-checks causing eviction, can not be set at the same time. I know cluster configuration is kind of far away from the top of the filter configuration.

---

It isn't throughput load that envoy is balancing among interchangeable nodes, in this scheme. The load to be balanced is the bulk of the data, which can not fit in a single host. A cluster could be an element in the configuration of the key mappings, not a whole description of the pool.

I don't want to be too proscriptive about the configuration, but I think it would be nice to have a configuration that can help with the allocation of the slots around the ring, with an eye toward future growth. The very simplest scheme is to define redundant references to the same host many times, naming them such that later they can be split apart. For instance,

```
  dbs:
    - 1.2.3.4:50 alice
    - 1.2.3.4:50 bob
    - 1.2.3.4:50 charlie
    - 1.2.3.4:50 david
    - 9.8.7.6:50 edward
    - 9.8.7.6:50 frances ...
```

And the slots are allocated in order through the db list using *not the address*, but the name, so that later the single host 1.2.3.4:50 can be replicated-duplicated onto another host at different IP addresses of course, and envoy reconfigured at the time the replication is torn down. Now two hosts have (temporarily) a copy of the same data, and each are ready to answer requests. (The extraneous data on each host that will be owned by the other can be cleaned up lazily in the future.)

```
  dbs:
    - 1.2.3.4:50 alice
    - 1.2.3.4:50 bob
    - 1.2.1.2:50 charlie
    - 1.2.1.2:50 david
    - 9.8.7.6:50 edward
    - 9.8.7.6:50 frances ...
```

so that keys selecting alice/bob ring slots still get to the same server, but keys selecting charlie/david go to the 1.2.1.2:50 host, which have a previously-replicated copy of the data. These have one remaining level of passive fast re-sharding to go. Long-planning configurers could preallocate aaaa, aaab, aaac.

So, my request here is that ring slots be nameable or at least splitable. Another scheme could be to do something like [prefix routes](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/redis_proxy/v3/redis_proxy.proto#envoy-v3-api-msg-extensions-filters-network-redis-proxy-v3-redisproxy-prefixroutes) where the leading bits after hashing are used to route.

```
  prefix_routes:
  routes:
    - post-hash-bits-prefix: "0"
      cluster: "cluster_a"
    - post-hash-bits-prefix: "1"
      cluster: "cluster_b"
```
to
```
  prefix_routes:
  routes:
    - post-hash-bits-prefix: "00"
      cluster: "cluster_a"
    - post-hash-bits-prefix: "01"
      cluster: "cluster_a_new"
    - post-hash-bits-prefix: "10"
      cluster: "cluster_b"
    - post-hash-bits-prefix: "11"
      cluster: "cluster_b_new"
```

----

Currently [docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis) say 
> Envoy can act as a Redis proxy, partitioning commands among instances in a cluster. In this mode, the goals of Envoy are to maintain availability and partition tolerance over consistency. ... **Envoy is designed as a best-effort cache**, meaning that it will not try to reconcile inconsistent data or keep a globally consistent view of cluster membership.

Reconciling inconsistent data and keeping global anything are not necessary features of key consistency. Those don't have to be solved first.

*Relevant Links*:

- [Twemproxy cluster keying](https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md#node-names-for-consistent-hashing)

**Comment by alyssawilk** [comment]
cc @msukalski @henryyyang @mattklein123 @weisisea

**Comment by mattklein123** [comment]
At a high level this sounds reasonable to me. I guess my main question is how much of Redis Cluster are we going to reimplement here? Don't they already do a bunch of this stuff?
