### ISSUE TITLE
Thrift Health Checker support

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#22555]
This is a design doc for feedback.

We want to introduce a thrift health checker so thrift only cluster could reflect the health-ness more correctly.

It will be a custom health checker. It sends a thrift request with configed method_name and expect a success response. 
The Thrift server can respond an exception to cause an immediate health check failure.

Here's the proposed thrift.proto

```
message Thrift {
  reserved 1, 5;

  reserved "service_name", "request_headers_to_add";

  // Specifies the method name should be set to each request that is sent to
  // the local thrift host.
  string method_name = 2 [(validate.rules).string = {min_len: 1}];

  // Supplies the type of transport that the Thrift health checker should use. Note that
  // :ref:`AUTO_TRANSPORT<envoy_v3_api_enum_value_extensions.filters.network.thrift_proxy.v3.TransportType.AUTO_TRANSPORT>`.
  // is not supported.
  // [#extension-category: envoy.filters.network]
  filters.network.thrift_proxy.v3.TransportType transport = 3
      [(validate.rules).enum = {defined_only: true}];

  // Supplies the type of protocol that the Thrift health checker should use. Note that
  // :ref:`AUTO_PROTOCOL<envoy_v3_api_enum_value_extensions.filters.network.thrift_proxy.v3.ProtocolType.AUTO_PROTOCOL>`.
  // is not supported.
  // [#extension-category: envoy.filters.network]
  filters.network.thrift_proxy.v3.ProtocolType protocol = 4
      [(validate.rules).enum = {defined_only: true}];
}
```
Note that we need to specify transport and protocol since we don't have
the request body to inspect. AUTO is not a valid option for the same reason.

Unfortunately, we can't use `not_in` for the validator since there's a bug
for foreign enum which triggers the compile error
```

bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/health_checkers/thrift/v3/thrift.pb.validate.cc:62:17: error: unknown type name 'TransportType'; did you mean 'filters::network::thrift_proxy::v3::TransportType'?
        const std::set<TransportType> _Thrift_Transport_NotInLookup = {
                       ^~~~~~~~~~~~~
                       filters::network::thrift_proxy::v3::TransportType
```

An example setting for custom_health_check as a Thrift health checker is shown below:

```
  custom_health_check:
    name: envoy.health_checkers.thrift
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.health_checkers.thrift.v3.Thrift
      method_name: "ping",
      transport: FRAMED
      protocol: BINARY
```

cc @mattklein123 @zuercher @rgs1 @fishcakez @adisuissa

**Comment by alyssawilk** [comment]
cc @zuercher

**Comment by zuercher** [comment]
cc @rgs1 too

**Comment by zuercher** [comment]
I assume this will be a custom health check extension, so no changes to `envoy.config.core.v3.HealthCheck`. If so, I think this is fine.

Also, probably need to explicitly exclude the twitter protocol until it's actually removed. Otherwise the service name becomes necessary.

**Comment by JuniorHsu** [comment]
Yes this is custom health check extension, and thanks for the great suggestion for protocol exclusion, which makes perfect sense. twitter protocol is deprecated and will be removed Q2 2023 so we should be good.

**Comment by JuniorHsu** [comment]
cc @peterl328
