### ISSUE TITLE
Publish binary artefacts to github on tag/release

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22579]
Once we have automated publishing (#22578 ) i think we want to add binary uploads for the raw envoy binary, deb packages, and windows exes to the github release page

Before we can do that we need a solution that we can use for signing the binaries - (cf #14076 )

wrt to deb packages - as a follow on plan is to provide these from an apt repo - the deb signatures need to work with reprepro (or similar) so this may mean that they have to be gpg-signed - the situation is possibly similar with rpms

**Comment by jrauschenbusch** [comment]
@phlax How is this related to [this ticket](https://github.com/envoyproxy/envoy/issues/22196)? Is it a duplicate?

**Comment by phlax** [comment]
> @phlax How is this related to https://github.com/envoyproxy/envoy/issues/22196? Is it a duplicate?

yep - we can probably close both of these - as i mentioned on the other ticket, there is some follow up to do - but this pipeline is now active
