### ISSUE TITLE
Any way to retry mirror-ed traffic or know the failed mirror requests?

### ISSUE THREAD

**Issue by mukundv18** [envoyproxy/envoy#22599]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Any way to retry mirror-ed traffic or know the failed mirror requests?*

*Description*:
>We are using Envoy Proxy as Redis Proxy. Is there a way that the failed mirrored requests can be known so that it can be retried? Also, how to retry failed mirror-ed requests?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
Envoy implementation for mirroring is "fire-and-forget". I think there's room for improvement for telemetry and retrying of mirror-ed requests, but it's a substantial change due to the implementation.
