### ISSUE TITLE
No logs in Envoy Access Logs

### ISSUE THREAD

**Issue by mukundv18** [envoyproxy/envoy#22598]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *There are NO logs in the envoy access logs. How to enable access logging*

*Description*:
>No logs in Envoy access logs with the following configuration. Please suggest if it has to be enabled somewhere or if any config is missing.

```    
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: /Users/path/admin_access.log
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
@mukundv18 which version of Envoy are you using?
