### ISSUE TITLE
question regarding websocket proxying

### ISSUE THREAD

**Issue by SunChero** [envoyproxy/envoy#22592]
my backend support only websocket with binary data, 

can envoy accept websocket connection accept text mode from downstream and convert to binary when talking to upstream ?

something like 

<Client Ws: Text> ---<Envoy WS:Binary> ----<Backend>

Thank you

**Comment by kyessenov** [comment]
Envoy supports websockets. Can you clarify what you mean by text and binary? Envoy can terminate HTTP websocket and then open a TCP stream to a backend.
