### ISSUE TITLE
http inspector filter is not filling `server_name` 

### ISSUE THREAD

**Issue by dhiaayachi** [envoyproxy/envoy#22612]
*Title*: *http inspector filter is not filling `server_name` which prevent from using it in conjunction with `filter_chain_match`*

*Description*:
>When using the HTTP inspector listener filter, the `server_name` is not filled which make it impossible to match on `server_name` in a listener filter match.

*Repro steps*:
> Use a config that have a listener filter ` type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector` and a filter chain match on a `server_name`. Send HTTP traffic with the right host header. It will never match on the filter.
>The expected behaviour is to have the `server_name` being filled by the `HttpInspector` the same way it's filled by the `TLSInspector` extension.

>**Note**: 
It seems to be as trivial as adding parsing the `Host/Authority` header and adding to the socket in [here](https://github.com/envoyproxy/envoy/blob/4350d44f784aa6ab4c6c505b92a5bddde8f1bc8f/source/extensions/filters/listener/http_inspector/http_inspector.cc#L141). Am I missing something?
If it's as easy I can submit a PR to fix this.

**Comment by kyessenov** [comment]
@dhiaayachi `server_name` refers to SNI in TLS and is populated by [TlsInspector](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector). HTTP inspector does not parse anything beyond the first line of HTTP requests.

**Comment by dhiaayachi** [comment]
@kyessenov reading the comment about `server_name` it say:

```
// If non-empty, a list of server names (e.g. SNI for TLS protocol) to consider when determining
  // a filter chain match. Those values will be compared against the server names of a new
  // connection, when detected by one of the listener filters.
```
It give SNI for TLS as an example and not necessarily the only supported protocol.

I see now that it only parse [until the first header](https://github.com/envoyproxy/envoy/blob/4350d44f784aa6ab4c6c505b92a5bddde8f1bc8f/source/extensions/filters/listener/http_inspector/http_inspector.cc#L85). Is there a reason not to change that to parse all the headers (up to certain size) to retrieve the HOST/Authority header?

**Comment by dhiaayachi** [comment]
I'm new to envoy so I'm probably understanding this wrong.

I thought that the http inspector filter is executed for every request before the filter chain match. From what you're saying I understand it's not, and executed only once for every connection. Is that right?

**Comment by kyessenov** [comment]
Yes, listener filters are execute once per connection before the listener parses the bytes on that connection.
