### ISSUE TITLE
rbac: no access to updated connection info on internal listener

### ISSUE THREAD

**Issue by douglas-reid** [envoyproxy/envoy#22617]
We have a (unique?) set up involving internal listeners that need access to the original ssl connection info. To pass the connection info, we use a filter state object with the "shared with upstream" flag and a single purpose network filter that reads the filter state and updates the connection info via `ReadFilterCallbacks`.

This appears to work as expected for some of our HTTP filters (Wasm-based stats filters), but the RBAC filter does not seem to be able to see the updated connection info.

The connection is set in the network filter via:

```
  callbacks_->connection().connectionInfoSetter().setSslConnection(obj->ssl());
```

RBAC checks the ssl connection via:

```
callbacks_->connection()->ssl() ?
```

The Wasm-based stats filters are accessing SSL info via code like:

```
getValue({"connection", "mtls"}, &mtls));
getValue({"connection", "uri_san_local_certificate"},
             &request_info->destination_principal);
getValue({"connection", "uri_san_peer_certificate"},
             &request_info->source_principal);
```

Is there a way to have RBAC see the updated connection info?

Repro is tough, as this involves custom extensions, but the general flow involves 3 filters:
- `istio.filters.network.internal_ssl_forwarder` (network filter: reads filter state and sets connection info)
- `envoy.filters.http.rbac`  (http filter: **cannot** "see" updated connection info )
- `istio.stats`   (wasm http filter: **can** "see" updated connection info)

Example xDS stanza with filters:
```
{
     "name": "inbound-vip|5000||helloworld.default.svc.cluster.local",
     "active_state": {
      "version_info": "2022-08-09T00:40:53Z/29",
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
 ...
       "filter_chains": [
        {
         "filters": [
          {
           "name": "istio.filters.network.internal_ssl_forwarder",
           "typed_config": {
            "@type": "type.googleapis.com/istio.telemetry.internal_ssl_forwarder.v1.Config"
           }
          },
          {
           "name": "envoy.filters.network.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
...
            "http_filters": [
             {
              "name": "envoy.filters.http.rbac",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC",
...
             },
...
            {
              "name": "istio.stats",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
...
             },
...
    },
```

Trace-level output logs from a request:

```
2022-08-09T00:44:25.467799Z     trace   envoy filter    internal_ssl_forwarder: connection ssl set
2022-08-09T00:44:25.467861Z     trace   envoy filter    internal_ssl_forwarder: uriSanPeerCertificate: spiffe://cluster.local/ns/default/sa/sleep
2022-08-09T00:44:25.471295Z     debug   envoy rbac      checking request: requestedServerName: , sourceIP: ..., directRemoteIP: ..., remoteIP: .... ,localAddress: envoy://inbound-vip|5000||helloworld.default.svc.cluster.local, ssl: none, headers: ':authority', 'helloworld:5000' ..., dynamicMetadata: 
2022-08-09T00:44:25.471387Z     debug   envoy rbac      enforced allowed, matched policy none
```

In the RBAC debug logs, I would expect to see: `ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/default/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: ,` instead of:  `ssl: none`

Meanwhile, the stats from the `istio.stats` filter include the proper information:

```
istio_requests_total{source_principal="spiffe://cluster.local/ns/default/sa/sleep" ... destination_principal="spiffe://cluster.local/ns/default/sa/helloworld" ... connection_security_policy="mutual_tls" ...} 1
```

cc: @kyessenov @howardjohn

**Comment by kyessenov** [comment]
Wasm accesses SSL info via: `StreamInfo::downstreamAddressProvider().sslConnection()`. I think it's just missing setter somewhere.

**Comment by kyessenov** [comment]
The problem is that the default implementation of ssl() in Connection uses transport socket directly.
