### ISSUE TITLE
Add ability to retrieved config files from a URL

### ISSUE THREAD

**Issue by jasonmccallister** [envoyproxy/envoy#22627]
Add a `--config-url` option that will download the configuration from a remote URL.

*Description*:
There are a lot of times where it would be nice to retrieve a static configuration file (no XDS) from a remote URL. A use case would be uploading a configuration to S3 and running the plain `envoyproxy/envoy:v1.23-latest`. As it exists today, the only way to get a configuration file into a container is to build your own image, wrapping the envoy image and pushing to a private registry. That process is a little cumbersome and requires extra build steps when the end goal is to have a single file in a container image. 

**Process with out the option:**
1. Create a Github repo
2. Create a Dockerfile and wrap the envoy image
3. Setup CI/CD
4. Deploy wrapped image to private registry
5. Deploy the private image

**Process with the option:** 
1. Setup S3 and upload configuration file
2. Deploy upstream image from Docker Hub and pass `--config-url`

Sure, I'm probably missing a few steps, but the ability to deploy Envoy using the upstream image drastically reduces the complexities just to copy a file into a container.

**Comment by kyessenov** [comment]
In my experience, there's usually a wrapper script that fills a templated initial bootstrap config, starts envoy, and then relies on xDS server for the rest. It should be pretty to write a small script that passes a downloaded file as `--config-yaml`, for example. I think the concern here is that without bootstrap, envoy is not initialized internally and cannot perform normal functions.

**Comment by jasonmccallister** [comment]
That could work as well, but would still require making your own private image that uses FROM envoyprovy right?

IMHO, we should not _need_ to create a private image when we often are just adding a single file to the upstream image; even if it's just to reduce complexity and the number of steps required.

**Comment by kyessenov** [comment]
I meant to pass bootstrap as a literal argument to the docker image with `--config-yaml`. A minimal bootstrap is fairly small and the rest needs an xDS server for dynamic updates.
