### ISSUE TITLE
flake: verify_examples zipkin-tracing

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#22632]
Noticed this a couple of times today:
```
TESTS FAILED:
run_examples@ /home/vsts/work/1/s/ci/verify_examples.sh :39 (./zipkin-tracing)
  > main@ /home/vsts/work/1/s/ci/verify_examples.sh :44
```

**Comment by phlax** [comment]
almost certainly this is a dupe of https://github.com/envoyproxy/envoy/issues/22404

upstream issue is here https://github.com/docker/hub-feedback/issues/2262

**Comment by phlax** [comment]
checking CI im not seeing the docker issue - so this may be genuine separate flake - ill look further

**Comment by phlax** [comment]
this should be resolved
