### ISSUE TITLE
[OAuth2] Timeline for graduation of OAuth2 filter to beta/GA 

### ISSUE THREAD

**Issue by sseetharaman6** [envoyproxy/envoy#22657]
*Title*:  Timeline for graduation of OAuth2 filter to beta/GA 

*Description*:
[OAuth2 filter documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) mentions that it is currently under active development.  The [extensions metadata](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml) specifies the `status` as `alpha` - is there a timeline or milestone by which this filter can be considered `stable` for production use? In other words, when is this expected to graduate to GA? 

Also is there a plan to support additional grant types besides the authz code flow?   
 Relevant: https://github.com/envoyproxy/envoy/issues/14088

**Comment by kyessenov** [comment]
cc @derekargueta @snowp

**Comment by naveeniyengar** [comment]
any timeline for this?

**Comment by deva26** [comment]
@derekargueta @snowp @kyessenov - Would you be able to provide the likely promotion timeline for this filter?

**Comment by kyessenov** [comment]
The criteria are listed here https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#extension-stability-and-security-posture. The main signal for this extension is sufficient burn time in production. If an end-user can report on experience running it in production without issues, the other signals are mostly technical quality.

**Comment by deva26** [comment]
> The criteria are listed here https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#extension-stability-and-security-posture. The main signal for this extension is sufficient burn time in production. If an end-user can report on experience running it in production without issues, the other signals are mostly technical quality.

Serious users aren't ready to try it in production when they see the flag alpha. Aren't we in the `chicken and egg` conundrum?

**Comment by kyessenov** [comment]
@deva26 yes it is, but the first step needs to be done by the interested end-user to provide qualification. We cannot do that alone in OSS without production access.
