### ISSUE TITLE
TCP socket options from upstream cluster config are incorrectly sent down to QUIC

### ISSUE THREAD

**Issue by RenjieTang** [envoyproxy/envoy#22663]
I ran into this issue when I tried speaking QUIC in Envoy-mobile but I think the root cause is from Envoy.

When the [ClusterInfoImpl](https://github.com/envoyproxy/envoy/blob/9141f23079988dc96985d7d5a4992f1849e1e091/source/common/upstream/upstream_impl.cc#L844https://github.com/envoyproxy/envoy/blob/9141f23079988dc96985d7d5a4992f1849e1e091/source/common/upstream/upstream_impl.cc#L844) for HTTP/3 is created, it would fetch the cluster config and potentially parse some [TCP socket options](https://github.com/envoyproxy/envoy/blob/9141f23079988dc96985d7d5a4992f1849e1e091/source/common/upstream/upstream_impl.cc#L106).

Later when we try to create a [QUIC client connection](https://github.com/envoyproxy/envoy/blob/8d513a670006e1ecd06df6c4ef89d4389e102ebb/source/common/quic/envoy_quic_client_connection.cc#L24), the HTTP/3 connection pool would get socket options [from the cluster](https://github.com/envoyproxy/envoy/blob/095f4ca336d3d705e629b207fb2cbbc22d29db8f/source/common/http/http3/conn_pool.cc#L132) and apply them to the underlying UDP socket.

Apparently, socket options like TCPKEEPALIVE are specific to TCP and will fail in QUIC. 

I wonder how we should solve this. Should we move socket option configs out of the cluster config? Or maybe we can add a parameter to specify whether an option can only be applied to a specific socket type?

**Comment by kyessenov** [comment]
cc @danzh2010

**Comment by danzh2010** [comment]
This needs a non-stale label.

**Comment by danzh2010** [comment]
@alyssawilk any thoughts on this?

**Comment by alyssawilk** [comment]
I'd be inclined to allow tagging for TCP-only or UDP-only but I defer to @envoyproxy/api-shepherds

**Comment by htuch** [comment]
Yeah, I don't think we need any API semantic change here. Socket options at the POSIX-level have this weak typing and need to be applied to the correct socket type. So, just proper documentation and validation would make sense IMHO.

**Comment by alyssawilk** [comment]
sorry @htuch are you suggesting that Envoy automatically check which socket option is being set and only apply it to the relevant socket types?  I agree that'd be ideal but it does mean that we either have to exhaustively add a check function for all known socket options and validate them and keep them up to date for all supported platforms, or we have to accept folks will write config for a not-yet-validated one, find it doesn't work, and require a binary update to set their socket option.

maybe there's something in between, like a runtime option folks could set to bridge that gap?

**Comment by htuch** [comment]
I guess I'm not just convinced that there is an API change needed, but happy to see a proposal for one that would make sense.

**Comment by htuch** [comment]
@ggreenway thoughts here? Looking just now at your comment https://github.com/envoyproxy/envoy/issues/22634#issuecomment-1247349596 seems to indicate that it might be hard to really use config guarding as the appropriate mechanism for socket option safety across platforms.
