### ISSUE TITLE
router: Early assertion or set a default value for `headers.Path()`

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#2268]
**Early assertion or set a default value for `headers.Path()`**

**Description**

While playing with `cm_.httpAsyncClientForCluster().send()`, as a beginner, I found that the message's header of `send()` needs to be provided by values at least for keys in these assertions: https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L292-L295.

However, if we don't set the message headers path, it gives us `Segmentation fault: 11` since the `headers.Path()` can be possibly called at (i.e. before the assertion):

1. https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L203
2. https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L239

Do you think to put the `ASSERT(headers.Path())` earlier would be better? or just set a default value (I can only think of '/' as default path) should be sufficient?

Thanks!

**Comment by htuch** [comment]
I would vote for just adding better documentation and/or moving the assertion earlier. A default path probably isn't very useful, as it's probably rare that filter authors want to just hit this up. 

You could also introduce a factory for `Http::Message` that makes it convenient to set path/method/scheme. Less boiler plate is always good.

PRs welcome!

**Comment by mattklein123** [comment]
+1 for more docs. In general, I would like to move to a world where filters only access Envoy via the `Api` interface (which would be provided off of the filter callbacks). We are very far from that now but it would be good to start making progress. This would allow us to more easily support loadable modules and shield filters from internal code changes.

**Comment by mattklein123** [comment]
@dio I'm going to close this out. Please feel free to do doc PRs, etc. to make things easier.
