### ISSUE TITLE
OcAgent trace exporter: Export() failed: UNIMPLEMENTED: unknown service opencensus.proto.agent.trace.v1.TraceService     

### ISSUE THREAD

**Issue by jean13360** [envoyproxy/envoy#22680]
*Description*:
I try to trace with openCensus  but when i enable ocagent_exporter_enabled , i have this error :
OcAgent trace exporter: Export() failed: UNIMPLEMENTED: unknown service opencensus.proto.agent.trace.v1.TraceService     

I think i forgot something but i don't know how 

- filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing: 
            provider :
              name :  envoy.tracers.opencensus
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.OpenCensusConfig
                trace_config:
                    probability_sampler :
                      samplingProbability : 1
                stdout_exporter_enabled : true
                stackdriver_exporter_enabled: false
                zipkin_exporter_enabled: false
                ocagent_exporter_enabled: true
                ocagent_grpc_service :
                    google_grpc :
                      target_uri : otel-grpc-tkgi.orl-outils.k8s.pole-emploi.intra:80
                      stat_prefix: oi169
                incoming_trace_context: ["TRACE_CONTEXT"]
                outgoing_trace_context: ["TRACE_CONTEXT"]

Thx for the help

**Comment by jean13360** [comment]
I use envoy with version 1.23.0

**Comment by wbpcode** [comment]
> OcAgent trace exporter: Export() failed: UNIMPLEMENTED: unknown service opencensus.proto.agent.trace.v1.TraceService

Where is the log from? The envoy tracer or `Oc` server?

**Comment by jean13360** [comment]
> > OcAgent trace exporter: Export() failed: UNIMPLEMENTED: unknown service opencensus.proto.agent.trace.v1.TraceService
> 
> Where is the log from? The envoy tracer or `Oc` server?

the envoy tracer 😥😥

**Comment by wbpcode** [comment]
From the source code of caagent, this is a error return by the server, because the server is not implemented the related grpc service.

```
void Handler::ExportRpcRequest(
    const ::opencensus::proto::agent::trace::v1::ExportTraceServiceRequest
        &request) {
  // TODO: Re-work this to have a single long-running streaming RPC.
  grpc::ClientContext context;
  context.set_deadline(absl::ToChronoTime(absl::Now() + opts_.rpc_deadline));

  auto stream = opts_.trace_service_stub->Export(&context);
  if (stream == nullptr) {
    std::cerr << "OcAgent trace exporter: Export() got a NULL stream.\n";
    return;
  }

  if (!stream->Write(request)) {
    std::cerr << "OcAgent trace exporter: Export() stream broken.\n";
  }

  stream->WritesDone();
  grpc::Status status = stream->Finish();
  if (!status.ok()) {
    std::cerr << "OcAgent trace exporter: Export() failed: "                      <----- here here here
              << opencensus::common::ToString(status) << "\n";
  }
}

```
