### ISSUE TITLE
Bootstrap proto field overrides via CLI

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2269]
In various places, e.g. node ID/locality, stags tags (https://github.com/envoyproxy/envoy/pull/2264), we have adhoc CLI flags to override fields in the bootstrap (or that could exist there).

It would be generally useful to be able to have a flag that could do this generically, e.g. `--bootstrap-override stats_config.extra_tags=some_tag:some_value`. The idea is that you specify some path to the field, such as `stats_config.extra_tags` and then the value.

I think if we use proto text for the value portion and standard field names to describe a `.`-separated path it should be fairly easy to implement with existing proto reflection and parsing support.

See #2264 for the original discussion.

**Comment by kevintchan** [comment]
Hi I'd like to make this happen. Users should be able to specify as many overrides as they would like. For cases where the intention is to append a repeated entry, would it make sense to infer override vs. append depending on whether the proto text was an array or a single value ?

Envoy should exit if bootstrap overrides are present and:
- config is not v2
- validation of bootstrap after override is applied fails (validation only occurs once)

Please let me know if I've missed something, thanks!

**Comment by mattklein123** [comment]
@kevintchan conveniently, this was already implemented: https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-config-yaml

Closing. :)
