### ISSUE TITLE
[Question] Filter for translating gRPC to/from Redis protocol

### ISSUE THREAD

**Issue by vandyvilla** [envoyproxy/envoy#22691]
*Title*: *Filter for translating gRPC to/from Redis protocol*

*Description*:
I am looking into adding a plugin which can convert gRPC request to Redis commands and convert Redis response to gRPC response. The motivation is to expose a gRPC interface and use Redis as backing store. 

After some investigation and prototyping, I am thinking about adding a new filter, which inherits the following: 

1. Http::StreamDecoderFilter: so I can parse header path (via implementing decodeHeaders) and body data (via implementing decodeData) and translate them to Redis command (e.g., get, set). 
2. Network::WriteFilter: so I can intercept Redis response data and call Redis::Decoder to parse the data (via implementing onWrite). 
3. Common::Redis::DecoderCallbacks: so I can access parsed Redis response (via implementing onRespValue) to construct corresponding gRPC response. 

However, I am currently not sure about: 
1. whether inheriting both Http::StreamDecoderFilter and Network::WriteFilter works or should I inherit Http::StreamFilter (since Redis response is not HTTP)? 
2. How to construct gRPC response: on happy path, it is straightforward to construct header, body and trailer based on Redis result. But how about unhappy path, e.g., how do I know when to set gRPC DEADLINE_EXCEEDED assuming onWrite in WriterFilter is only called when there is a response data. 
3. How to send gRPC response to connection: since onRespValue in Common::Redis::DecoderCallbacks has no access to Buffer::Instance data in onWrite, should I directly use WriteFilterCallbacks->connection()->write or I can somehow overwrite Buffer::Instance data in onWrite. 

Any suggestions or comments greatly appreciated!

**Comment by wbpcode** [comment]
I am not sure how can you make a HTTP filter work with a write filter. The HTTP filter is part of HCM which is a terminal read filter.

**Comment by vandyvilla** [comment]
Thanks for the reply. So I probably should use Network::ReadFilter and Common::Redis::DecoderCallbacks, similar to how RedisProxy is implemented. 

My next question is is there any easy way to parse Buffer::Instance into gRPC format, including HttpHeaderMap, etc.

**Comment by soulxu** [comment]
If you use your own HttpFilter and then terminate with an HCM filter, then your upstream request is an HTTP request.  There is no way to let the cluster to send redis request.

Maybe you can try to create your own HttpFilter, it translates the grpc request to redis, then use the redis client send this request to a local address, then you create another listener with a redis filter listening on this local address and process the redis request which send by yourself. Then you can use the envoy cluster to send your redis request out.

**Comment by vandyvilla** [comment]
Thanks Soul! What do you mean by my own HttpFilter, meaning I cannot inherit Http::StreamFilter? Also for another listener with Redis filter, would Network::WriteFilter just work? Do you have any code pointers?

**Comment by soulxu** [comment]
> Thanks Soul! What do you mean by my own HttpFilter, meaning I cannot inherit Http::StreamFilter? Also for another listener with Redis filter, would Network::WriteFilter just work? Do you have any code pointers?

The own HttpFilter meaning the your own filter which inherit Http::StreamFilter. For another listener with Redis filter, I think you needn't any custom code, just use the original redis filter.

**Comment by vandyvilla** [comment]
> 

Yeah, I was thinking about chaining a Http::StreamFilter and RedisFilter. But I am not sure about the above Question 2 and 3.

**Comment by vandyvilla** [comment]
Just want to bump up the thread a bit. I am wondering whether it is possible to use a HTTP filter to decode/encode gRPC requests and a Redis filter to talk to upstream.

**Comment by mattklein123** [comment]
It is possible but it will require a bunch of custom code. There is nothing out of the box that will do this.

**Comment by vandyvilla** [comment]
Thanks Matt! Can you give a bit more pointers on the "custom" code part? I was thinking about implementing a custom filter, but not sure how i should leverage HTTP filter to handle gRPC stream and connect with the Redis filter.

**Comment by mattklein123** [comment]
> Thanks Matt! Can you give a bit more pointers on the "custom" code part? I was thinking about implementing a custom filter, but not sure how i should leverage HTTP filter to handle gRPC stream and connect with the Redis filter.

At a very high level you are going to have to replace the HTTP router filter with a terminal filter which translates incoming HTTP calls to outgoing Redis calls, probably by using the redis filter code directly somehow. I think all the pieces are there but they will have to be put together in a way that makes sense.
