### ISSUE TITLE
build istio envoy proxy fail

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22696]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
ERROR: /home/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/envoy/test/mocks/tracing/BUILD:11:14: Linking external/envoy/test/mocks/tracing/libtracing_mocks.lo failed: (Exit 1): ar failed: error executing command (from target @envoy//test/mocks/tracing:tracing_mocks) /usr/bin/ar @bazel-out/k8-fastbuild/bin/external/envoy/test/mocks/tracing/libtracing_mocks.lo-2.params

ERROR: /home/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/com_github_google_quiche/BUILD.bazel:1891:17: Linking external/com_github_google_quiche/libquic_core_ack_listener_interface_lib.lo failed: (Exit 1): ar failed: error executing command (from target @com_github_google_quiche//:quic_core_ack_listener_interface_lib) /usr/bin/ar @bazel-out/k8-fastbuild/bin/external/com_github_google_quiche/libquic_core_ack_listener_interface_lib.lo-2.params
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by wbpcode** [comment]
IMO, you may create this issue in the `istio/proxy` or `istio/istio`?

**Comment by kyessenov** [comment]
Duplicate of https://github.com/istio/istio/issues/40443
