### ISSUE TITLE
ARM builds are failing (~reliably) on 1.23 branch

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22701]
ARM builds are failing when trying to compile on the 1.23 branch

afaict for a couple of different deps (`qat` and `kafka`) - both use `foreign_cc` to compile

The kafka build fails with a bunch of missing symbols, eg:

```console
ld.lld: error: undefined symbol: mtx_init
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=114930&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=628

The qat lib is failing with:

```console
#include <linux/time_types.h>
```

The errors seem unrelated to the PRs where they are failing, which would seem to imply that something has changed with the container (and/or perhaps the vm image)

**Comment by phlax** [comment]
cc @lizan @soulxu

**Comment by phlax** [comment]
im wondering if this is kernel related and the `arm-large` vm has changed, given that the build image has not

**Comment by mbana** [comment]
Facing the same problem. Please fix this.

**Comment by jasmingacic** [comment]
Same here.
