### ISSUE TITLE
Mac CircleCI tests are flaky

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2271]
*Description*:
Periodically the mac tests fail, and a PR close/open cycle can be used to re-run.  The test that failed for me most recently was:

```
//test/common/http:codec_client_test                                     FAILED in 0.2s
  /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/execroot/envoy/bazel-out/darwin-fastbuild/testlogs/test/common/http/codec_client_test/test.log
```

I don't know which of the codec_client_test methods fail, or how to see the contents of test.log.  I've also tried to re-run with various sanitizers at Google and haven't been able to repro the problem yet.

*Relevant Links*:

Here's a CircleCI failing case: https://circleci.com/gh/envoyproxy/envoy/14854?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jmarantz** [comment]
Dug deeper into log and found this test-method failed:

```
[ RUN      ] IpVersions/CodecNetworkTest.SendHeadersAndClose/1
test/common/http/codec_client_test.cc:269: Failure
Expected equality of these values:
  ""
  TestUtility::bufferToString(data)
    Which is: "HTTP/1.1 200 OK\r\ncontent-length: 0\r\n"
With diff:
@@ -1,1 +1,2 @@
-""
+HTTP/1.1 200 OK\r
+content-length: 0\r\n

test/common/http/codec_client_test.cc:263: Failure
Mock function called more times than expected - returning directly.
    Function call: dispatch(@0x7fff5a0372d0 buffer with size=0)
         Expected: to be called twice
           Actual: called 3 times - over-saturated and active

[  FAILED  ] IpVersions/CodecNetworkTest.SendHeadersAndClose/1, where GetParam() = 4-byte object <01-00 00-00> (1 ms)
```

**Comment by mattklein123** [comment]
If anything I think they have gotten flakier lately. @zuercher do you mind looking into this next week?

**Comment by zuercher** [comment]
Looks like it's two separate things. One is a timing bug similar to what we used to see in connection_impl_test, which is fixable with the same scheme of blocking dispatcher invocations with callbacks that cause an exit.

The second bit is that, sometimes, OS X seems to burp out an extra read event, which causes an extra invocation of `ConnectionImpl::onRead`. It presents the `Http::CodecClient` with the same buffer a second time which fails the test's expectation. It seems that the read buffer is not drained in the event that it doesn't contain a complete header stanza (and the test purposely leaves off the second `\r\n`). The second read event is the result of the connection being closed, AFAICT. Adding a guard in `ConnectionImpl::onReadReady` to skip `onRead` if no bytes were processed by the transport socket corrects this (and doesn't seem to break any other tests), but I'm not entirely sure it's safe.
