### ISSUE TITLE
ability to remove "server" from response trailers in gRPC

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#22719]
In a gRPC application, even though we use " response_headers_to_remove" functionality to remove "server" header, the gRPC trailers still has it.

Response trailers received:
content-type: application/grpc
date: Mon, 13 Jun 2022 21:05:13 GMT
error-code: auth.error
rpc-id: 132f3441-23a7-49f3-ae37-a742b79d40d9
**server: istio-envoy**
x-envoy-upstream-service-time: 4

Is there a way to remove it via any config change?

**Comment by ramaraochavali** [comment]
@lizan @snowp @alyssawilk any thoughts on this?

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-serverheadertransformation. You might need to add a new option if none of those work for you.

**Comment by ramaraochavali** [comment]
Ok. I did read that. Does it work for trailers also or is it only for headers?

**Comment by mattklein123** [comment]
Envoy by default will set server on all responses (headers). If gRPC "trailers" are sent as headers, this is where it will be set.

**Comment by ramaraochavali** [comment]
@mattklein123  one final question on this, if we use `response_headers_to_remove` and remove server header - is that expected to remove in this case also? It is removing from headers but not in this case. Just want to get your thoughts before looking at server transformation

```
          "response_headers_to_remove": [
           "server",
          ],
```

**Comment by mattklein123** [comment]
IIRC the server handling happens later and overrides anything that happens in response_headers_to_remove.

**Comment by ramaraochavali** [comment]
Cool. Thank you. Closing this
