### ISSUE TITLE
Outlier detection enhancement

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#22720]
Currently  envoy outlier detection and ejection will only check the 5xx number. Can it check the TCP reset ?
If envoy receive TCP reset from upstream server for a threshold, can envoy eject the upstream server from cluster ?

**Comment by mattklein123** [comment]
The problem is I'm not sure how we can know whether a TCP reset has occurred. BSD sockets don't expose this information. It might be possible to get this somehow from Linux specific APIs. cc @ggreenway for thoughts.

**Comment by ggreenway** [comment]
It's possible that looking for `errno == ECONNRESET` may work, but I'm not sure if it would be consistent between platforms, or if it works all the time at all. This would need some testing and experimenting.

**Comment by cpakulski** [comment]
@zhangbo1882 Please check https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier.html?#consecutive-local-origin-failure. If you enable [split_external_local_origin_errors](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-split-external-local-origin-errors), TCP resets will go to a separate bucket and outlier detector will eject the upstream server.
