### ISSUE TITLE
Where is the entry and exit point for network requests in envoy？

### ISSUE THREAD

**Issue by He-Jingkai** [envoyproxy/envoy#22739]
I'm trying to understand the code of envoy and measure its running overhead in a specific scenario. Currently, I'm wondering where is the entry and exit point for network requests in envoy. That means which function/class envoy will call at the very first when it reads a request/responce from socket(upstream) and which function/class envoy will call at the very end when it writes a request/responce to socket(downstream).

This might sound a little naive because I'm a beginner. I'd really appreciate it if you could answer my question.

**Comment by pxpnetworks** [comment]
Hi, i'm not a software developer but i think you could have a look at the trace level logs when running Envoy :) (with the -**l trace** flag)
