### ISSUE TITLE
Does request_mirror_policies work for CONNECT requests?

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#22736]
The title says it... i was wondering if this might work since i didnt find anything in the docs..
In my setup it seems like when i enable it on a route with connect_matcher in debug logs it only makes upstream request to the primary cluster but nothing to the secondary cluster under request_mirror_policies . 
( I tried both with terminating the connect or proxying the connect on that route. )

**Comment by soulxu** [comment]
As I test, it doesn't works also. I guess the reason is codec won't know the request is done. I guess that is same reason as the doc said the buffer filter doesn't support also
```
Note that buffering is generally not compatible with upgrades, so if the [Buffer filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/buffer/v3/buffer.proto#envoy-v3-api-msg-extensions-filters-http-buffer-v3-buffer) is configured in the default HTTP filter chain it should probably be excluded for upgrades by using [upgrade filters](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig-filters) and not including the buffer filter in that list.
```
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades

@alyssawilk

**Comment by mattklein123** [comment]
I'm not sure how we could mirror a CONNECT request unless a) we somehow did it in a streaming only mode and b) dropped the response traffic for the mirror connection? Either way it seems kind of confusing.

cc @alyssawilk

**Comment by alyssawilk** [comment]
yeah given shadowing doesn't get kicked off until the request is complete (which for CONNECT is on teardown) I wouldn't expect it to work well.
Arguably if you're doing HTTP/2 connect where you can do unidirectional FIN, if downstream sent FIN first, it could work?  but yeah not well.
