### ISSUE TITLE
codec: support for half-open H2 streams

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#22748]
Current implementation does not handle half-closed HTTP streams well. When a response is received, the stream is assumed to be destroyed (in particular, the underlying connection can be closed if it's drained/idle). This is especially problematic for HTTP CONNECT streams: when tcp_proxy attempts to write end_stream after response is complete for a draining cluster (e.g. via CDS update), a crash occurs.

This is a feature request to support an explicit closure of request stream and delay stream destruction until then.

**Comment by buffalu** [comment]
we (mainly @segfaultdoctor) have been testing envoy with GRPC trying to make sure it'll work for our application. we have the following service file:
```
service ExampleService {
  rpc Echo (Message) returns (Message) {}
  rpc StreamToClient (Message) returns (stream Message) {}
  rpc StreamToServer (stream Message) returns (Message) {}
  rpc EchoStream (stream Message) returns (stream Message) {}
}
```

all of them work except StreamToServer. is this issue and #22754 supposed to address the issues we see with StreamToServer getting dropped on envoy but not directly?

**Comment by kyessenov** [comment]
Yes, the issue is that Envoy considers the response completion as the stream completion, so if the client continues sending data after the upstream server ends its stream, the data is not sent upstream. This happens at the codec level, so there may be some variation in how gRPC SDKs encode streaming semantics in HTTP2.
