### ISSUE TITLE
.python-version without sub version doesn't work with pyenv

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#22746]
*Title*: *.python-version without sub version doesn't work with pyenv*

*Description*:
```
$ pyenv install 3.10
python-build: definition not found: 3.10

The following versions contain `3.10' in the name:
  3.10.0
  3.10-dev
  3.10.1
  3.10.2
  3.10.3
  3.10.4
  3.10.5
  3.10.6
  miniconda-3.10.1
  miniconda3-3.10.1

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

 $ python
pyenv: version `3.10' is not installed (set by {$ENVOY_PATH}/.python-version)
 $ cat .python-version
3.10
```

**Comment by phlax** [comment]
hi @JuniorHsu this isnt really supported and shouldnt be needed - we have moved to using bazel python toolchains for all of our tools

this was readded only because in the github actions it doenst set a version and reads this file - and works with just the minor version set

**Comment by JuniorHsu** [comment]
Thanks @phlax 
no issue for build toolchain. the thing is i use autojump which relies on python, and my pyenv read `.python-version` and fails while I'm in the envoy folder

**Comment by keith** [comment]
Yea if you run any python scripts in dev in the envoy repo this is an issue if you use pyenv. Would it hurt the github action to have the minor version?

**Comment by phlax** [comment]
> Would it hurt the github action to have the minor version?

it just adds maintenance 

if the .python-version file is at issue i would rather we just shift the version into the github action

**Comment by keith** [comment]
Yea probably easier if that's the only place that consumes it, maybe there's some way users could make pyenv ignore it, but then everyone would have to set that up. Locally I've just deleted that file and avoided checking that in

**Comment by phlax** [comment]
>  maybe there's some way users could make pyenv ignore it

i had a quick look for autojump - didnt see an immediate fix, altho i did see others complaining about similar issues.

i came to the conclusion that we probably dont want to support/worry about xyz py utils - so finding a solution for autojump wasnt the best way forward

> Locally I've just deleted that file and avoided checking that in

interesting - i didnt realize this file was causing issue. We originally added it to try and get dependabot to use it - but that didnt work, and by the time i came to remove, the gh action was already using it

i can raise a PR tomorrow to shift this into the action, if noone has done so already
