### ISSUE TITLE
Forward only some outbound requests to a forward-proxy using HTTP CONNECT

### ISSUE THREAD

**Issue by shibin-george** [envoyproxy/envoy#22755]
*Description*:
I have a `squid` forward proxy which is my exit-point to the internet but only for some kind of requests.
I'm trying to find a way to achieve this using the Envoy sidecar running alongside the client-side application container.

Some additional things that will influence how I decide to get this done:
- I want this proxy to be transparent to the application-logic as much as possible:
  - This kinda rules out [this setup](https://github.com/envoyproxy/envoy/blob/main/configs/proxy_connect.yaml)
    - For this to work, the application needs to send a CONNECT request to the envoy listener (in this case, running on port 10001). It would make more sense to rather just let the application directly talk (HTTP CONNECT) to the proxy server directly, bypassing Envoy 🤔 
- But of course, I understand that it cannot be completely transparent to the application since I only want certain requests go via the proxy-server.
  - The easiest way to do this (I am thinking out loud here) would be to add some header to the request on the application side. If Envoy sees that the request has a specific header set, then Envoy HTTP-CONNECTs to the forward-proxy.
  - But for this to work, I need to install a listener that can intercept all outgoing traffic from (and not just ones that are on a particular port like 10001) -> check if header exists -> CONNECT to proxy if header exists, otherwise just let it egress through the default PassthroughCluster.
  - Is this even possible? Any config that could help me get started with this?
  - I tried using the config in #19612 but the listener fails to bind to port 443 (`cannot bind '0.0.0.0:443': Permission denied`)

Appreciate any inputs!

**Comment by soulxu** [comment]
> * But of course, I understand that it cannot be completely transparent to the application since I only want certain requests go via the proxy-server.
>   
>   * The easiest way to do this (I am thinking out loud here) would be to add some header to the request on the application side. If Envoy sees that the request has a specific header set, then Envoy HTTP-CONNECTs to the forward-proxy.
>   * But for this to work, I need to install a listener that can intercept all outgoing traffic from (and not just ones that are on a particular port like 10001) -> check if header exists -> CONNECT to proxy if header exists, otherwise just let it egress through the default PassthroughCluster.
>   * Is this even possible? Any config that could help me get started with this?

You should be able to use iptable to redirect all apps's requests to a listener. Then you can filter chain matching https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchainmatch, for the requests which destination port is 10001, then go the the filter chain which forward the request to the proxy. For other requests, go tot he filter chain which setup dynamic forward proxy.

>   * I tried using the config in [Dynamic setting value of TcpProxy.tunneling_config.hostname #19612](https://github.com/envoyproxy/envoy/issues/19612) but the listener fails to bind to port 443 (`cannot bind '0.0.0.0:443': Permission denied`)
> 
If you want to bind any port less than 1024, then you need root access, there also otherway, you can search on the google.

**Comment by soulxu** [comment]
> * But of course, I understand that it cannot be completely transparent to the application since I only want certain requests go via the proxy-server.
>   
>   * The easiest way to do this (I am thinking out loud here) would be to add some header to the request on the application side. If Envoy sees that the request has a specific header set, then Envoy HTTP-CONNECTs to the forward-proxy.

What is the condition to decide which request goes to the proxy?

>   * But for this to work, I need to install a listener that can intercept all outgoing traffic from (and not just ones that are on a particular port like 10001) -> check if header exists -> CONNECT to proxy if header exists, otherwise just let it egress through the default PassthroughCluster.
>   * Is this even possible? Any config that could help me get started with this?
>   * I tried using the config in [Dynamic setting value of TcpProxy.tunneling_config.hostname #19612](https://github.com/envoyproxy/envoy/issues/19612) but the listener fails to bind to port 443 (`cannot bind '0.0.0.0:443': Permission denied`)

bind to any port less than 1024, you would need the root permission or CAP_NET_BIND_SERVICE

**Comment by shibin-george** [comment]
> What is the condition to decide which request goes to the proxy?
Since I want requests to to certain resources (like key-vaults, storage buckets) to go via the squid proxy, I can modify the application side library (for these resources) to inject a header for requests.
Then, Envoy should detect these headers and tunnel them through the forward-proxy.

**Comment by soulxu** [comment]
> > What is the condition to decide which request goes to the proxy?
> 
> Since I want requests to certain resources (like key-vaults, storage buckets) to go via the squid proxy, I can modify the application side library (for these resources) to inject a header for requests. Then, Envoy should detect these headers and tunnel them through the forward-proxy.

Seems like there is no way to distinguish certain resources, if those request access different services with different domain name, then you can filter them by the `:authority ` through the headers match https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch
