### ISSUE TITLE
Please regenerate RBE toolchain configs

### ISSUE THREAD

**Issue by Wyverald** [envoyproxy/envoy#22758]
**Problem**: Envoy RBE is failing on Bazel@HEAD+Downstream pipeline due to https://github.com/bazelbuild/bazel/commit/3469784a4935c91b4ac22bcfed6be52e6dfec878 ([example failure](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2586#0182a995-9720-43d4-85be-7883b6c255a2))

**What needs to be done**: [envoy-build-tools](https://github.com/envoyproxy/envoy-build-tools) needs to be updated to use the latest rbe_config_gen from [bazel-toolchains](https://github.com/bazelbuild/bazel-toolchains) (at least version 5.1.2 so that it contains https://github.com/bazelbuild/bazel-toolchains/commit/8c717f8258cd5f6c7a45b97d974292755852b658). Then the toolchain configs need to be regenerated, and [this file in Envoy](https://github.com/envoyproxy/envoy/blob/835dc5021aead1989a6e72ff165db91b58b127ff/bazel/repository_locations.bzl#L79-L89) needs to be updated so that Envoy uses the latest envoy-build-tools.

**Comment by phlax** [comment]
@Wyverald can you raise a PR in envoy-build-tools to update

**Comment by mattklein123** [comment]
cc @lizan @keith

**Comment by keith** [comment]
working on this here https://github.com/envoyproxy/envoy-build-tools/pull/181

**Comment by Wyverald** [comment]
gentle ping. Envoy remains broken in the downstream pipeline, and if we can't resolve that soon, we'd need to disable Envoy on Bazel CI.

**Comment by keith** [comment]
I submitted https://github.com/envoyproxy/envoy/pull/22822 to unblock bazel CI

**Comment by keith** [comment]
@Wyverald can you confirm that fixes the next run?

**Comment by Wyverald** [comment]
The next run that includes that fix will be tonight CET, so I'll report back tomorrow. Thanks!

**Comment by Wyverald** [comment]
For some reason, Envoy is still broken: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2601#0182d854-183d-4bcd-b15e-f60f99173f16

@aranguyen do you know why that may be? On line 279 of the logs, it says `Inherited 'build' options: [...] --incompatible_use_platforms_repo_for_constraints=false`, yet later the build still fails on `@bazel_tools//platforms:X` usages (line 292).

**Comment by aranguyen** [comment]
oh hmm..interesting..it looks like the flag did not get overriden somehow. Let me take a look at that and file a bug with configurability team. 

In the meantime, let me see if I can update the following to unblock the CI failures for envoy. 
```
aranguyen-macbookpro:envoy aranguyen$ grep -r "@bazel_tools//platforms" /private/var/tmp/_bazel_aranguyen/d62ce45fc2cda7024a6d68c3c63b8002
/private/var/tmp/_bazel_aranguyen/d62ce45fc2cda7024a6d68c3c63b8002/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:    @bazel_tools//platforms:default_platform will be used most of the time).
/private/var/tmp/_bazel_aranguyen/d62ce45fc2cda7024a6d68c3c63b8002/external/com_google_protobuf/third_party/googletest/BUILD.bazel:    constraint_values = ["@bazel_tools//platforms:windows"],
/private/var/tmp/_bazel_aranguyen/d62ce45fc2cda7024a6d68c3c63b8002/external/com_google_googletest/BUILD.bazel:    constraint_values = ["@bazel_tools//platforms:windows"],
```

**Comment by keith** [comment]
gtest update is here: https://github.com/envoyproxy/envoy/pull/22779, blocked on unrelated issues
bazel toolchains PR is here: https://github.com/envoyproxy/envoy-build-tools/pull/181 was blocked on a windows issue that should be fixed now, so maybe that one will be mergeable today

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/22862

**Comment by keith** [comment]
still needs https://github.com/envoyproxy/envoy/pull/22978 or https://github.com/envoyproxy/envoy/pull/22779

**Comment by meteorcloudy** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4171702/190436618-66fdcaad-c3ec-4929-ba22-3912149c3263.png">

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1256#_

Can we get the gtest fixes merged? Envoy is one of the few projects that're blocking the flip of https://github.com/bazelbuild/bazel/issues/8622

**Comment by keith** [comment]
I've submitted https://github.com/envoyproxy/envoy/pull/23140 to just try to patch it, since updating googletest has some breaking changes it seems like. @meteorcloudy as stated above we are disabling this feature  https://github.com/envoyproxy/envoy/blob/aa1c71d44d1e6259041fd2b037bed773ac1c04ae/.bazelrc#L17-L18 which clearly isn't taking, which sounds a bit risky for actually shipping a bazel update where folks can't disable it
