### ISSUE TITLE
c-ares returning rcode 16 (BADSIG)

### ISSUE THREAD

**Issue by lionelvillard** [envoyproxy/envoy#22766]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:  c-ares returning rcode 16 (BADSIG) when dns resolver rewrites names 

*Description*:
> c-ares returns rcode 16 when Envoy tries resolving the xds_cluster server name. The DNS resolver uses a subset of the CoreDNS rewrite plugin. Note that the DNS resolver works for other application but not c-ares.

It does not work with Envoy 1.22 and earlier versions. It magically works with Envoy 1.23. 

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by mattklein123** [comment]
Sorry I have no idea. I would assume that perhaps something was fixed in a new c-ares version?
