### ISSUE TITLE
Add support for adding externally owned data into Envoy's buffer. 

### ISSUE THREAD

**Issue by genioshelo** [envoyproxy/envoy#2277]
The current evbuffer implementation of Buffer::Instance does not have an API to pass a pointer to externally owned data into the buffer in order to avoid copying. Evbuffer has `evbuffer_add_reference` which allows this functionality, but the Instance interface needs to be modified to take advantage of this.

**Comment by htuch** [comment]
+1, maybe introduce a `add_reference` method to `Buffer` and we can achieve this. FTR, this is needed to support filter's that manage their own memory with zero copy, e.g. a cache filter.

**Comment by mattklein123** [comment]
Note that I would like to completely replace evbuffer with our own buffer class. That is tracked here: https://github.com/envoyproxy/envoy/issues/232
