### ISSUE TITLE
will you add proxy-protocol support?

### ISSUE THREAD

**Issue by lootoos** [envoyproxy/envoy#22790]
in order to be able to get normal IP addresses to the minecraft server.
in order for the server to be able to receive external IP addresses of players.
by the way, nginx supports proxy_protocol (https://imgbb.com/FnpFhPk), will you introduce such functionality in Envoy?

**Comment by zhxie** [comment]
You may refer to [proxy protocol](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol).

**Comment by lootoos** [comment]
I don't know how to program so your option is not suitable for me

**Comment by lizan** [comment]
Envoy does support [proxy protocol](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol). You just need to configure them.

**Comment by lootoos** [comment]
how to include it in Envoy?

**Comment by suniltheta** [comment]
I hope you have discovered [Proxy Protocol Filter (proto)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto). Is there something that can be enhanced on this doc? Were you looking for an example?
