### ISSUE TITLE
Run DCO checker with commit hooks

### ISSUE THREAD

**Issue by hausdorff** [envoyproxy/envoy#2281]
*Title*: *Run DCO checker with commit hooks*

*Description*:
CONTRIBUTING.md [specifies](https://github.com/envoyproxy/envoy/blob/52c6a17616e95c999b165f6700c0ff1ed6fb9d57/CONTRIBUTING.md#dco-sign-your-work) that commits should contain a DCO signoff. It's easy to forget this, and a pain to rebase when you do commit.

A better option is to automatically signoff using git's commit hooks API.

Mesos uses the following workflow to support this across the entire contributor base:

1. When you first clone the repository, you run [bootstrap][bootstrap], a shell script in the project root.
1. This (among other things) causes the git commit hooks in [support/hooks][chs] to be copied into the user's local `.git` folder.
1. Then, when the user attempts to commit, various checks and associated processing is done. (_e.g._, they run linters, formatters, validate the commit message, and so on).

The major gotcha to this approach is to have a graceful error path. In Mesos's approach, if you fail to format the commit message correctly, it will abort, and unless you know that your commit message is squirreled away in places like `.git/COMMIT_EDITMSG`, you might think you have to type it all over again. In this case I believe this can be avoided.

[bootstrap]: https://github.com/apache/mesos/blob/f429cebcbf982efd75966934ac876e99b6c6560e/bootstrap
[chs]: https://github.com/apache/mesos/tree/f429cebcbf982efd75966934ac876e99b6c6560e/support/hooks

**Comment by htuch** [comment]
Is it possible to do this server-side on GH to avoid the need to run bootstrap locally?

**Comment by mattklein123** [comment]
> Is it possible to do this server-side on GH to avoid the need to run bootstrap locally?

Unfortunately not.

**Comment by mattklein123** [comment]
Adding script that sets up a local hook sounds like a great opt-in thing to me. It can run check-format also.

**Comment by hausdorff** [comment]
@mattklein123 Just so I understand: are you saying that it's not possible to have (say) a mergebot that has write permissions modify the commit message to modify the commit message (_e.g._, for a scenario like this) before merging? If so I'm very surprised. That seems like it should be possible.

@htuch I am definitely not anything approaching a lawyer, but it seems to me that the point of DCO checks is that you want the user to say _yes, I can give this code away_. If it's automated, the user isn't signing that code away, no? :) That said, if it is possible to do similar things, this approach be worth considering for other scenarios.

**Comment by htuch** [comment]
I wasn't suggesting automating the actual DCO :) Just having a server-side check to ensure DCO was present before allowing a push to complete.

**Comment by hausdorff** [comment]
Got it, sorry for the confusion.

**Comment by mattklein123** [comment]
> Just so I understand: are you saying that it's not possible to have (say) a mergebot that has write permissions modify the commit message (e.g., for a scenario like this) before merging? If so I'm very surprised. That seems like it should be possible.

Yes it's possibly to have a bot as a test, but that's what we have already. We have the DCO bot, the format bot, etc. GitHub does not allow generic pre-commit hooks server side.

I think the client-side hook would be a good thing to have as it would save people time who forget to fix format, forget DCO, etc.

**Comment by hausdorff** [comment]
Ok I'll put together a simple PR soon.

**Comment by mattklein123** [comment]
Awesome! Thank you.
