### ISSUE TITLE
Support Rich Authorization Requests in the jwt_auth plugin

### ISSUE THREAD

**Issue by krotscheck** [envoyproxy/envoy#22814]
*Title*: *Support Rich Authorization Requests in the jwt_auth plugin*

*Description*:

Alright, ready for some deep dives into authorization theory? Great!

The current behavior of the `jwt_authn` plugin includes a check for an exact string match between the JWT's `aud` claim, and a string in the audience field for the filter configuration. This [audience claim](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3), in authorization parlance, is the list of destinations for whom the token is intended. In other words, I could sign a token for resource server A, and if presented to resource server B that token would be rejected because "hey, that's not meant for me".

This is all well and good, however from the view of us authorization nerds it's a fraught authorization check. The reason is that an audience claim can state "where" a token may be used, but not "what" resource it may be used for or "how" that resource may be modified. The `scopes` claim has historically been used to provide this information, but there is no way to correlate: Assuming two audiences and two scope values, how do we know which scope value is intended for which audience?

```
{
   ....,
   aud: [
      "audience_one",
      "audience_two",
   ],
   scope: "ambiguous_scope_1 ambiguous_scope_2",
}
```

Due to this lack of specificity, the OAuth2 community has (mostly) converged on a new RFC called "[Rich Authorization Requests](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-rar)". The intent here is to provide a more detailed authorization statement on in a JWT, which can answer the how, what, and where of any inbound request. In essence it replaces the `aud` claim with a list of authorization statements, with the `aud` claim being replaced by `locations`. This example is taken directly from the RFC:

```
{
   ...,
  authorization_details:  [
      {
         "type": "account_information",
         "actions": [
            "list_accounts",
            "read_balances",
            "read_transactions"
         ],
         "locations": [
            "https://example.com/accounts"
         ]
      },
      {
         "type": "payment_initiation",
         "actions": [
            "initiate",
            "status",
            "cancel"
         ],
         "locations": [
            "https://example.com/payments"
         ],
         "instructedAmount": {
            "currency": "EUR",
            "amount": "123.50"
         },
         "creditorName": "Merchant A",
         "creditorAccount": {
            "iban": "DE02100100109307118603"
         },
         "remittanceInformationUnstructured": "Ref Number Merchant"
      }
   ]
}
```

There are some concerns with the specification, of course, because it is unnecessarily broad: Most of the [Common Data Fields](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-rar#section-2.2) are optional, and exactly how a token's assembled is largely left to the implementor. Furthermore, the RFC itself only lightly touches on how this should be represented in a JWT:
```
If the access token is a JWT [[RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)], the AS is RECOMMENDED to add
the authorization_details object, filtered to the specific audience,
as a top-level claim.
```

If that wasn't enough, there's already a new specification that builds on OAuth2.1 under draft called [Grant Negotiation and Authorization Protocol (GNAP)](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol) which has its own view of what this specificity should look like. In this case, the [data structure for an authorization statement](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-8) is similar to the above, however the top level field is called `access` instead of `authorization_details`.

So what exactly is this request all about? Adding a `locations` field to the http filter configuration, which will trigger a check of either `authorization_details[].locations` or `access[].locations`.

I hope I didn't bore you!

*Relevant Links*:

* [Rich Authorization Requests (Draft 12)](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-rar)
* [RFC 7519, JSON Web Token](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3)
* [GNAP](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol)
* [envoy jwt_authn filter configuration](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter#config-http-filters-jwt-authn)

**Comment by krotscheck** [comment]
Tagging @qiwzhang and @lizan at @alyssawilk's direction :)

**Comment by lizan** [comment]
This seems to be a case that should be done via RBAC or other authz filter happens after jwt_authn? The validated JWT can be extracted to metadata then authorized by them.

**Comment by krotscheck** [comment]
Depends! If you want to allow all validated traffic into your cluster, then yes you can do that. However, if you want to allow an audience-style filter by envoy that throws out any traffic not explicitly intended for this resource server, and the token uses authorization_details instead of the audience claim, then you'd want to check the `location` claim instead of the `audience` claim.

I'm simply asking for feature parity given that the common JWT structure is evolving.

**Comment by lizan** [comment]
Using another filter doesn't allow all validated traffic into the cluster, they just do another check before the traffic hit clusters.

I'm saying that even today this is doable when you store the JWT payload in a metadata and matches them in RBAC filter, you should be able to match any structured fields including `authorization_details[].locations` or `access[].locations`. Isn't this the feature request is for?

**Comment by krotscheck** [comment]
Huhn- ok, so, that may work. I've forwarded your suggestion to the relevant team.

Given that what I'm asking for can be done with existing filters, that still leaves the question on whether or not jwt_auth should support it natively. I can see an argument either way - on one side, the name of the filter itself clearly references JWT, and should therefore adhere to what's in the JWT claims RFC. Given that JWT's may not be issued by an OAuth2 system (although I'd argue that 99.99% of them are) you can make an argument for purity that the filter should remain restricted to this RFC.

The counter argument is that of general usage: JWT's are canonically issued by OAuth2 systems, which continue to evolve at the pace of RFC's. Updating the filter makes a decent amount of sense, but by that argument we could also build a filter explicitly for Rich Authorization Requests.

What's your take?

**Comment by lizan** [comment]
> (although I'd argue that 99.99% of them are)

There are JWT specs that doesn't necessarily to be issued by an OAuth2 system like the [JWT-SVID](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md) in service-to-service context. :)

I'm not against to add support of the rich authorization to JWT filter itself, but just I want to see how mature this RFC draft is and how the adoption goes. Given that the authorization itself should be already doable within what we have today so it doesn't block prototyping or experimenting.
