### ISSUE TITLE
debug wasm extension

### ISSUE THREAD

**Issue by GOVYANSONG** [envoyproxy/envoy#22836]
I understand that envoy itself can be debugged with devcontainer. Just seek for guidance on how to debug into my own wasm filter implementation while debugging envoy? curious to know if LLDB can be automatically attached to the running wasm filter and magically lookup source map.

**Comment by bryanwux** [comment]
Not sure about LLDB but I think gdb is working.

**Comment by GOVYANSONG** [comment]
There are still dots that need to be connected. We want source code level debugging experience in VSCode and would like to set breakpoint in the vscode and expect program execution flow to hit the breakpoint at some point during debug session. what would be the scope e.g. per project, per workspace, per window etc.? most likely, my own custom wasm filter codebase is located in a separate project from the envoy one (github checkout). the debugger can support multiple targets per single debug session, then how is the coordination with vscode?

**Comment by PiotrSikora** [comment]
AFAIK, there are no Wasm debuggers other than Chrome DevTools, and that obviously doesn't work in Envoy.

**Comment by GOVYANSONG** [comment]
![image](https://user-images.githubusercontent.com/36177352/187090485-40d08676-74cd-44b8-85d4-d084702ab1bd.png)

I did an experiment with lldb and wasi. I was able to set breakpoints on both method name 'main' and '_start', and can debug in source code mode e.g. gui sub-command during lldb debug session. Following is a short description of the setup:

Artifacts:

    hello.c

        * build to wasi

        ../wasi-sdk/wasi-sdk-16.0/bin/clang --target=wasm32-unknown-wasi --sysroot ../wasi-sdk/wasi-sysroot -g -O0 -v -o hello.wasm hello.c

        * verify

        wasmtime hello.wasm

    wrapper.c

        * build

        cc wrapper.c \
            -I ../wasmtime/wasmtime/crates/c-api/include/ \
            -I ../wasmtime/wasmtime/crates/c-api/wasm-c-api/include \
            ../wasmtime/wasmtime/target/release/libwasmtime.a \
            -lpthread -ldl -lm \
            -g \
            -o wrapper
        
        * verify

        ./wrapper

Debug with LLDB

    working folder: artifacts

    instantiate lldb: lldb ./wrapper

    once in lldb debugger:

    (lldb) breakpoint set --name main
	(lldb) breakpoint set --name _start
	(lldb) run
	(lldb) gui

    once in gui mode: press 'h' key to find information about shortcut keys available in the active panel

**Comment by GOVYANSONG** [comment]
![vscode-gdb-01](https://user-images.githubusercontent.com/36177352/187932283-a72a0127-7663-4e0f-a299-548c1726b836.png)
![vscode-gdb-02](https://user-images.githubusercontent.com/36177352/187932290-ede35f52-f5a3-4b2f-9dd5-6e97781cb034.png)

I was able to do source code level debug in vscode with extension beyond-gdb.
