### ISSUE TITLE
chain multiple per route lua filters in typed_per_filter_config

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#22844]
Hi, sorry for the silly question but how to chain multiple per route filters together?
The config below is accepted but only the second envoy.filters.http.lua is loaded.

```
typed_per_filter_config: 
  envoy.filters.http.lua: {'@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute, name: ihp.lua}
  envoy.filters.http.lua:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
    source_code:
      inline_string: |
        function envoy_on_request(request_handle)
          request_handle:logInfo("AAAAAAAAAAAAAAAA.")
        end
```

BR,
Stoyan

**Comment by mattklein123** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
https://github.com/envoyproxy/envoy/blob/main/examples/lua/envoy.yaml

Check this example. 😸 

You may need to configure multiple lua filter with different custom name in `http_filters`. Then, to configure multiple route level lua config in `typed_per_filter_config` and use the custom name as the key.
