### ISSUE TITLE
Datadog tracing: add error message

### ISSUE THREAD

**Issue by dasch** [envoyproxy/envoy#22858]
*Title*: Add error message to Datadog (and possibly other) traces

*Description*:
Right now, the Envoy trace span for a 5xx request, when viewed in Datadog, shows the error message `error: true`, which doesn't really add anything. You have to dig into the payload in order to understand even at a high level what went wrong. I think it would be great to have the error message contain:

1. The status code, and
2. the response flags, and/or the "reasons", i.e. the longer-form description of the flags.

This would aid in real time debugging of systems.

**Comment by mattklein123** [comment]
cc @cgilmour @palazzem
