### ISSUE TITLE
Question: Where can I find a sample envoy config.yaml which showcases the "static" module configuration?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#22863]
Where can I find a sample envoy config.yaml which showcases the "static" module configuration?

I was looking at his document: https://jteso.github.io/envoy/documentation/site/modules/static/ but was not able to find a proper config file to showcase this configuration.

PS: No offence to anyone, but I think the envoy documentation is poorly done. It might make sense to whoever wrote it, but if someone new reads it, it is a pain to put stuff together.  I believe it can be drastically improved if more detailed examples will be added into the docs.

**Comment by daixiang0** [comment]
That is not official I think, please check this [doc](https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-static.html?highlight=static)?

**Comment by ghevge** [comment]
I'm not sure what to pointed me to is what I'm actually looking for. I basically want to transform my envoy instance into a  file server: to serve some images from a volume mapped to my envoy docker image.

**Comment by mattklein123** [comment]
> PS: No offence to anyone, but I think the envoy documentation is poorly done. It might make sense to whoever wrote it, but if someone new reads it, it is a pain to put stuff together. I believe it can be drastically improved if more detailed examples will be added into the docs.

This is not a great way to constructively ask for help and improve things.

I would recommend starting with the 20+ sandbox examples that we have if that is a good way for you to learn.

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/

**Comment by phlax** [comment]
getting back to the original question - Envoy doesnt currently have an extension to serve static files - no idea if the linked extension still works

adding a static web server/extension would be quite cool imho - but there is a long standing discussion about this (cf #378 amongst others) and nobody has been sufficiently motivated to add this

**Comment by bb010g** [comment]
no stalebot

**Comment by bb010g** [comment]
Bump.

**Comment by phlax** [comment]
@bb010g i think the question in this ticket has already been answered - im minded to close it - wondering why you bumped it

**Comment by bb010g** [comment]
@phlax I would still like to see a sample config for basic static file serving.

**Comment by phlax** [comment]
> I would still like to see a sample config for basic static file serving.

im afraid that is not possible as that is not currently a functionality that Envoy offers - please direct any further discussion on that to #378
