### ISSUE TITLE
envoy compile failed 

### ISSUE THREAD

**Issue by GOVYANSONG** [envoyproxy/envoy#22864]
I was trying to generate envoy executable with debug info in my wsl2 ubuntu 20.04 box and got following error:

envoy/tools/vscode$ **./generate_debug_config.py //source/exe:envoy-static --args "-c envoy.yaml" --debugger lldb**
Starting local Bazel server and connecting to it...
WARNING: info command does not support starlark options. Ignoring options: [--@com_googlesource_googleurl//build_config:system_icu=0]
INFO: Analyzed 2 targets (785 packages loaded, 34179 targets configured).
INFO: Found 2 targets...
INFO: Deleting stale sandbox base /home/mk8s/.cache/bazel/_bazel_mk8s/9fc6acfe5af7a3ee0d2ef868edc1b4ab/sandbox
ERROR: /home/mk8s/ws2/envoy/source/exe/BUILD:23:16: Linking source/exe/envoy-static failed: (Exit 1): **gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-dbg/bin/source/exe/envoy-static-2.params**

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/home/mk8s/.cache/bazel/_bazel_mk8s/9fc6acfe5af7a3ee0d2ef868edc1b4ab/execroot/envoy/bazel-out/_tmp/actions/stderr-3) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
INFO: Elapsed time: 172.729s, Critical Path: 115.89s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "./generate_debug_config.py", line 138, in <module>
    debug_binary = build_binary_with_debug_info(args.target)
  File "./generate_debug_config.py", line 41, in build_binary_with_debug_info
    subprocess.check_call(["bazel", "build", "-c", "dbg"] + BAZEL_OPTIONS + targets)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'dbg', '//source/exe:envoy-static', '//source/exe:envoy-static.dwp']' returned non-zero exit status 1.

Environment:
envoy: v1.23.0
os: Linux mk8smaster 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thanks for any assistance

**Comment by daixiang0** [comment]
Which version of your GCC? Could you share more about your env and try running `bazel build -c dbg //source/exe:envoy-static //source/exe:envoy-static.dwp` ?

Test it at local, it works:
```
root:[envoy]$ ./tools/vscode/generate_debug_config.py //source/exe:envoy-static --args "-c envoy.yaml" --debugger lldb
Starting local Bazel server and connecting to it...
WARNING: info command does not support starlark options. Ignoring options: [--@com_googlesource_googleurl//build_config:system_icu=0]
```

**Comment by GOVYANSONG** [comment]
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0. the same version as in devcontainer.  

Run bazel build -c dbg //source/exe:envoy-static //source/exe:envoy-static.dwp:

Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: Analyzed 2 targets (785 packages loaded, 34179 targets configured).
INFO: Found 2 targets...
[928 / 7,476] checking cached actions
ERROR: /home/mk8s/ws2/envoy/source/exe/BUILD:23:16: Linking source/exe/envoy-static failed: (Exit 1): **gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-dbg/bin/source/exe/envoy-static-2.params**

thanks for helping.

**Comment by GOVYANSONG** [comment]
it turned out to be issue on my host ubuntu 20.04 box. after i took following steps to clean up compiler environment, the build succeeded:

deleted from /usr/bin: g++, c++ and cpp (build-essentials and a custom gcc12 build may have installed unwanted binaries)
bazel clean --expunge

cheers.

**Comment by sandeepubyon** [comment]
@GOVYANSONG  Can you provide me the exact commands that you used to make it work? I am also facing the same issue. Thanks

**Comment by GOVYANSONG** [comment]
@sandeepubyon the command is in the original post. my issue was with gcc compiler local to my linux box.
