### ISSUE TITLE
How to specify the python version for bazel build

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#22894]
Currently envoy bazel build can only support python3.10, so I upgrade my local python version to 3.10.
But sometimes I will build some older version envoy which only support python3.6.
How can I specify the python version for bazel build?

**Comment by phlax** [comment]
> Currently envoy bazel build can only support python3.10, so I upgrade my local python version to 3.10.

we use the bazel toolchains from `rules_python` so you shouldnt need to install any particular version in your host

**Comment by zhangbo1882** [comment]
From my understanding, if you build envoy with
 ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.debug.server_only'. It should be ok. 
But if you build envoy with
bazel build   //source/exe:envoy-static --config=docker-clang 
It will meet the python version issue.

**Comment by phlax** [comment]
> But if you build envoy with bazel build

i generally dont build with `run_envoy_docker` and in fact moving to toolchains was in part to not depend on that environment

i dont use `--config=docker-clang` but im wondering if its possible you need to update or rebuild a container image somewhere

**Comment by zhangbo1882** [comment]
I install pyenv so that I can switch to any python version now.
@phlax, which build command will you recommend me to use?

**Comment by phlax** [comment]
as said - you shouldnt need pyenv at all

there are a couple of commands that require host python installed - but any commands that go through bazel should download and use their own python version
