### ISSUE TITLE
Prometheus output of downstream listener per-thread metrics are different for main and worker threads

### ISSUE THREAD

**Issue by murphyjacob4** [envoyproxy/envoy#22906]
In #21756, downstream listener metrics with worker thread fields were setup to be extracted to a Prometheus field. However, this step is not performed if the thread is the main thread. For example, for a non-main thread, we have:

`envoy_listener_downstream_cx_total{envoy_worker_id="0",envoy_listener_address="mylistener"} `

Whereas, for the main thread, we report the following metric name:

`envoy_listener_mylistener_main_thread_downstream_cx_total{}`

This complicates the parsing of metrics. Instead, we should extract both to a field:

```
envoy_listener_downstream_cx_total{envoy_thread_id="worker_0",envoy_listener_address="mylistener"} 
envoy_listener_downstream_cx_total{envoy_thread_id="main_thread",envoy_listener_address="mylistener"} 
```

**Comment by daixiang0** [comment]
The main thread does not handle traffic indeed, so the metric you expected is meaningless I think, or do I miss something important?

**Comment by murphyjacob4** [comment]
> The main thread does not handle traffic indeed, so the metric you expected is useless I think, or do I miss something important?

The main thread handles admin port traffic:
`envoy_listener_admin_main_thread_downstream_cx_total{} 2`
