### ISSUE TITLE
Why does envoy require etags for caching

### ISSUE THREAD

**Issue by oka-tan** [envoyproxy/envoy#22919]
Using the http cache filter with a cache-control header and no etag doesn't seem to work.

Is there any particular reason for this and is there any reason I shouldn't use random uuids as etags?

**Comment by mattklein123** [comment]
cc @toddmgreer @jmarantz

**Comment by oka-tan** [comment]
Never mind, I made a mistake distinguishing between why the caching was working with my minio instance and not my api.

Gzip compression adds a vary header which screws everything up.
