### ISSUE TITLE
Building Envoy (v1.23.1) fails on Ubuntu 22.04.

### ISSUE THREAD

**Issue by wmwsagara** [envoyproxy/envoy#22915]
*Title*: *Building Envoy (v1.23.1) fails on Ubuntu 22.04.*

*Description*:
>I'm doing a clang (v14.0.0) build.

1) Build fails with following error:

ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: output 'source/extensions/filters/http/admission_control/evaluators/_objs/response_evaluator_lib/success_criteria_evaluator.dwo' was not created

ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: Compiling source/extensions/filters/http/admission_control/evaluators/success_criteria_evaluator.cc failed: not all outputs were created or valid
Target //source/exe:envoy-static failed to build

2) Note, I'm building as a normal user. Is root a requirement? I don't see as a requirement in below Build documentation.

3) Dependencies

Bazelisk as Bazel:
wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
chmod +x /usr/local/bin/bazel

Following dependencies installed:
apt-get update
apt-get install clang clang-tools clang-tidy llvm lld
apt-get install golang-go
apt-get install grpc-proto
apt-get install libtool cmake automake autoconf make ninja-build curl unzip virtualenv patch
apt-get install golang-starlark-dev libc-ares2 libc-ares-dev

NOTE: The buildifier and buildozer installed under the build user's home directory ($HOME/go/).
Install buildifier:
go install github.com/bazelbuild/buildtools/buildifier@latest

Install buildozer:
go install github.com/bazelbuild/buildtools/buildozer@latest

4) Build (as normal user)
git clone https://github.com/envoyproxy/envoy.git
cd envoy
git checkout tags/v1.23.1

./bazel/setup_clang.sh

bazel build --jobs=2 --define=no_debug_info=1 --config=clang --verbose_failures \\
-c opt //source/exe:envoy-static 2>&1 | tee Build-Envoy.log

5) Notable issues

INFO: Analyzed target //source/exe:envoy-static (782 packages loaded, 34545 targets configured).

INFO: From Generating C++ proto_library @com_github_cncf_udpa//xds/type/matcher/v3:pkg:
xds/type/matcher/v3/http_inputs.proto:7:1: warning: Import validate/validate.proto is unused.

CMake Warning at CMakeLists.txt:74 (message):
  WITH_GRPC is not set; building without dynamic loading support.

How to enable gROC build?

WITH_GRPC:BOOL=OFF
WITH_CARES:BOOL=OFF
WITH_LIBEVENT:BOOL=OFF

[2,820 / 7,399] Compiling external/envoy_api/envoy/extensions/access_loggers/grpc/v3/als.pb.validate.cc; 2s linux-sandbox ... (2 actions, 1 running)
ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: output 'source/extensions/filters/http/admission_control/evaluators/_objs/response_evaluator_lib/success_criteria_evaluator.dwo' was not created
ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: Compiling source/extensions/filters/http/admission_control/evaluators/success_criteria_evaluator.cc failed: not all outputs were created or valid
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 711.636s, Critical Path: 29.41s
INFO: 2824 processes: 1572 internal, 1250 linux-sandbox, 1 local, 1 worker.
FAILED: Build did NOT complete successfully

6) Full error log

$ bazel build --jobs=2 --define=no_debug_info=1 --config=clang --verbose_failures \
> -c opt //source/exe:envoy-static 2>&1 | tee Build-Envoy.log
Loading: 
Loading: 1 packages loaded
Loading: 1 packages loaded
    currently loading: source/exe
Analyzing: target //source/exe:envoy-static (2 packages loaded, 0 targets configured)
Analyzing: target //source/exe:envoy-static (45 packages loaded, 6 targets configured)
Analyzing: target //source/exe:envoy-static (45 packages loaded, 6 targets configured)
Analyzing: target //source/exe:envoy-static (203 packages loaded, 491 targets configured)
Analyzing: target //source/exe:envoy-static (545 packages loaded, 3227 targets configured)
Analyzing: target //source/exe:envoy-static (631 packages loaded, 6625 targets configured)
Analyzing: target //source/exe:envoy-static (712 packages loaded, 31201 targets configured)
Analyzing: target //source/exe:envoy-static (718 packages loaded, 31317 targets configured)
Analyzing: target //source/exe:envoy-static (718 packages loaded, 31317 targets configured)
Analyzing: target //source/exe:envoy-static (718 packages loaded, 31317 targets configured)
Analyzing: target //source/exe:envoy-static (718 packages loaded, 31317 targets configured)
Analyzing: target //source/exe:envoy-static (776 packages loaded, 32444 targets configured)
INFO: Analyzed target //source/exe:envoy-static (782 packages loaded, 34545 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... ( 1 action running)
INFO: From Generating C++ proto_library @com_github_cncf_udpa//xds/type/matcher/v3:pkg:
xds/type/matcher/v3/http_inputs.proto:7:1: warning: Import validate/validate.proto is unused.
INFO: From Generating Descriptor Set proto_library @com_github_cncf_udpa//xds/type/matcher/v3:pkg:
xds/type/matcher/v3/http_inputs.proto:7:1: warning: Import validate/validate.proto is unused.
[192 / 4,882] Generating C++ proto_library @envoy_api//envoy/config/cluster/v3:pkg; 0s linux-sandbox ... (2 actions, 1 running)
[457 / 5,384] Compiling src/google/protobuf/compiler/cpp/cpp_enum.cc [for tool]; 2s linux-sandbox ... (2 actions, 1 running)
[526 / 5,406] Compiling src/google/protobuf/text_format.cc [for tool]; 3s linux-sandbox ... (2 actions, 1 running)
[558 / 5,406] Compiling src/google/protobuf/compiler/java/java_map_field.cc [for tool]; 0s linux-sandbox ... (2 actions, 1 running)
[593 / 5,406] Compiling src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc [for tool]; 1s linux-sandbox ... (2 actions, 1 running)
[672 / 5,413] Compiling src/google/protobuf/compiler/cpp/cpp_file.cc [for tool]; 2s linux-sandbox ... (2 actions, 1 running)
[805 / 6,564] Compiling src/torque/cfg.cc [for tool]; 3s linux-sandbox ... (2 actions, 1 running)
[860 / 6,564] Compiling src/base/platform/platform-posix.cc [for tool]; 1s linux-sandbox ... (2 actions, 1 running)
INFO: From Executing genrule @io_opentracing_cpp//:generate_version_h:
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/llvm-14/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/llvm-14/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- clang-tidy found: /usr/lib/llvm-14/bin/clang-tidy
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.9EFvAXrb4w
-- Cache values
BUILD_DYNAMIC_LOADING:BOOL=ON
BUILD_MOCKTRACER:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
BUILD_TESTING:BOOL=OFF
CLANG_TIDY_EXE:FILEPATH=/usr/lib/llvm-14/bin/clang-tidy
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
ENABLE_LINTING:BOOL=ON
INFO: From Executing genrule @com_lightstep_tracer_cpp//:generate_version_h:
CMake Warning at CMakeLists.txt:74 (message):
  WITH_GRPC is not set; building without dynamic loading support.

-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/llvm-14/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/llvm-14/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.idbFsMI3O3
-- Cache values
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
DEFAULT_SSL_ROOTS_PEM:STRING=
HEADERS_ONLY:BOOL=ON
WITH_CARES:BOOL=OFF
WITH_DYNAMIC_LOAD:BOOL=ON
WITH_GRPC:BOOL=OFF
WITH_LIBEVENT:BOOL=OFF
INFO: From Generating C++ proto_library @com_google_googleapis//google/devtools/cloudtrace/v2:cloudtrace_proto:
google/devtools/cloudtrace/v2/trace.proto:19:1: warning: Import google/api/annotations.proto is unused.
google/devtools/cloudtrace/v2/tracing.proto:26:1: warning: Import google/protobuf/timestamp.proto is unused.
INFO: From Action external/opencensus_proto/opencensus/proto/agent/trace/v1/trace_service.grpc.pb.h:
bazel-out/k8-opt/bin/external/opencensus_proto/external/opencensus_proto: warning: directory does not exist.
INFO: From Action external/com_google_googleapis/google/devtools/cloudtrace/v2/trace.grpc.pb.h:
bazel-out/k8-opt/bin/external/com_google_googleapis/external/com_google_googleapis: warning: directory does not exist.
google/devtools/cloudtrace/v2/trace.proto:19:1: warning: Import google/api/annotations.proto is unused.
google/devtools/cloudtrace/v2/tracing.proto:26:1: warning: Import google/protobuf/timestamp.proto is unused.
[2,692 / 7,332] Compiling tcmalloc/huge_page_aware_allocator.cc; 2s linux-sandbox ... (2 actions, 1 running)
[2,820 / 7,399] Compiling external/envoy_api/envoy/extensions/access_loggers/grpc/v3/als.pb.validate.cc; 2s linux-sandbox ... (2 actions, 1 running)
ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: output 'source/extensions/filters/http/admission_control/evaluators/_objs/response_evaluator_lib/success_criteria_evaluator.dwo' was not created
ERROR: /usr/local/home/pcsg6/temp/envoy/source/extensions/filters/http/admission_control/evaluators/BUILD:13:17: Compiling source/extensions/filters/http/admission_control/evaluators/success_criteria_evaluator.cc failed: not all outputs were created or valid
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 711.636s, Critical Path: 29.41s
INFO: 2824 processes: 1572 internal, 1250 linux-sandbox, 1 local, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
pcsg6@pcsg6:~/temp/envoy$ 

[optional *Relevant Links*:]
>[Building](https://www.envoyproxy.io/docs/envoy/v1.18.2/start/building)
[Building Envoy with Bazel](https://github.com/envoyproxy/envoy/blob/v1.18.2/bazel/README.md)

Appreciate your help to get this fixed.

Best regards
Sagara

**Comment by mattklein123** [comment]
cc @phlax @keith @lizan
