### ISSUE TITLE
Fine grain logging does not work with JSON log message (%j)

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#22914]
*Description*:
`%j` in the log format string is not evaluated if `--enable-fine-grain-logging` is used.

*Repro steps*:

Start envoy like this:
```
envoy --log-format %j --enable-fine-grain-logging
```

Output:
```
[...]
%j
%j
%j
%j
At least one of --config-path or --config-yaml or Options::configProto() should be non-empty
```

For comparison, logging with `%j` works if fine grain logging is not used.

Start envoy like this:
```
envoy --log-format %j
```

Output:
```
[...]
error initializing configuration '': At least one of --config-path or --config-yaml or Options::configProto() should be non-empty
exiting
At least one of --config-path or --config-yaml or Options::configProto() should be non-empty
```

**Comment by mattklein123** [comment]
cc @botengyao @KBaichoo

**Comment by botengyao** [comment]
I see, %j is the Envoy custom flag added by #15226. Fine-grain logger is only using the default format pattern from spd::log. Will release a PR to make them consistent.
