### ISSUE TITLE
New Feature: Authz filter support in Envoy

### ISSUE THREAD

**Issue by saumoh** [envoyproxy/envoy#2291]
## Authorization (authz) filter support
Add support for external authorization service network and http filters.
## Description
With merge of [external_auth.proto](https://github.com/envoyproxy/data-plane-api/blob/master/api/auth/external_auth.proto),  [network external_auth config](https://github.com/envoyproxy/data-plane-api/blob/master/api/filter/network/ext_authz.proto) and [http external_auth.proto](https://github.com/envoyproxy/data-plane-api/blob/master/api/filter/http/ext_authz.proto), it is time to write the authorization filters in Envoy.

Since this is going to be some what large code change I am opening this issue to start a discussion so that we ensure that we are
* are in agreement on the general design. 
* not doing redundant work,

### SSL
To fill out [principal](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L63) we need to extract the SAN or Subject from the listener's own certificate. This will require extending https://github.com/envoyproxy/envoy/blob/master/include/envoy/ssl/connection.h and adding `uriSanLocalCertificate()` and `subjectLocalCertificate()`

### TCP Filter
At the TCP layer Envoy can send the [prinicial](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L63) by extracting it from the SSL certificate. (provided the connection is TLS|mTLS).
That implies that the external auth filter is NOT invoked on a new TCP connection callback instead it is invoked when a network event `Network::ConnectionEvent::Connected`  is done by [SSL](https://github.com/envoyproxy/envoy/blob/23f9be8a135b8270361c994e0ad5cb1a95d6207b/source/common/ssl/ssl_socket.cc#L95)
That also implies that while the external gRPC Authz server is being called the connection read will be disabled. Should we disable write as well? Once the result is back from the authz gRPC server then the connection will enable (read|write) or it is disconnected (in case the response was a deny).
Obviously the [HTTPRequest](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L79) will be empty.

### HTTP Filter
We should be able to fill out all the details of [HTTPRequest](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L79)
While the call to the external authorization server is in progress the connection will return `FilterTrailersStatus::StopIteration`.
Once the response is back the http connection will either return a 403 or continue decoding.

It is not quite clear to me if and how to fill out the following fields
* [query](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L106); Afaik this is not extracted from the path by the underlying `Envoy::Http::HeaderMap`. May be this is something that should be done at the authz gRPC server?
* [fragment](https://github.com/envoyproxy/data-plane-api/blob/bc54222bc0f8f321fda674d95a6e5ea43b735fd6/api/auth/external_auth.proto#L109)
Could these be derived at the authz gRPC server?

In the first cut of the implementation there won't be any caching. We can add it post merge of the main set of changes.

**Comment by saumoh** [comment]
cc @mandarjog @spikecurtis @mattklein123 @htuch @wora

**Comment by wora** [comment]
gRPC does not use query or fragment according to the current spec, so these fields must be empty.

We originally decided to keep fragment just to be compatible with URL spec, so we can log the full URLs. I don't think we should support applying authz on fragment. If we prefer to simplify the API, we could even drop it from the proto definition.

**Comment by mandarjog** [comment]
Yes, let’s just drop ‘fragment’

**Comment by saumoh** [comment]
@wora how about the query? can the authz server side extract it from the path? (I'll confirm that it's available in the path).
Also, do you foresee using [size](https://github.com/envoyproxy/data-plane-api/blob/893d6eae1f82f8e052706f6fd9e1b9cfe3689be2/api/auth/external_auth.proto#L116) in an authorization check. It's not really informative as it, i think, represents the client side request size and it's not clear to me how it would be used in an authorization decision.
Separately, i see you/ @mandarjog are working on https://github.com/envoyproxy/data-plane-api/issues/367 
would you mind addressing the changes we are discussing to external_auth.proto with that issue thanks!

**Comment by wora** [comment]
The concept of path and query are defined by URL spec. It is better for us to follow established spec.

The size is not useful for authz check, but it is very useful for auditing. One experience I can share is the first feature enterprise customers ask is audit. No authz system will be put into production without auditing. For auditing, a few human friendly attributes should be recorded, even they are not used for authz check. For example, ip address is not used for authz check, but it is often used for forensic analysis.

When @mandarjog and I designed this proto, we prepare it to handle real enterprise workloads. We think the current definition has the right balance.

**Comment by saumoh** [comment]
@mattklein123 @htuch Does the section on the when the TCP filter will be invoked sound ok to you folks. thx.

**Comment by mattklein123** [comment]
@saumoh yes sounds fine, note that the connected event for server connections is not raised for non-TLS connections so you will need to handle both cases (this is legacy behavior due to how libevent bufferevent works).

**Comment by tdeckers** [comment]
Hey guys, how does this related to #779?

**Comment by kflynn** [comment]
Opened #2828 to track further work to fold Ambassador's auth into Envoy.

**Comment by saumoh** [comment]
Closing this as future work is getting tracked in https://github.com/envoyproxy/envoy/issues/2828
