### ISSUE TITLE
build with ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.debug.server_only'  fail

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22938]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
···
WARNING: Download from https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'antlr4_runtimes':
   Traceback (most recent call last):
        File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/antlr4_runtimes/temp3222524729275118446/v4.10.1.tar.gz: GET returned 404 Not Found
ERROR: /source/WORKSPACE:25:25: fetching http_archive rule //external:antlr4_runtimes: Traceback (most recent call last):
        File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/antlr4_runtimes/temp3222524729275118446/v4.10.1.tar.gz: GET returned 404 Not Found
INFO: Repository v8 instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:202:8: in envoy_dependencies
  /source/bazel/repositories.bzl:854:26: in _v8
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_tencent_rapidjson instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:193:34: in envoy_dependencies
  /source/bazel/repositories.bzl:582:26: in _com_github_tencent_rapidjson
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository boringssl instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:157:15: in envoy_dependencies
  /source/bazel/repositories.bzl:264:26: in _boringssl
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_jbeder_yaml_cpp instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:185:32: in envoy_dependencies
  /source/bazel/repositories.bzl:400:26: in _com_github_jbeder_yaml_cpp
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_luajit_luajit instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:187:30: in envoy_dependencies
  /source/bazel/repositories.bzl:1026:26: in _com_github_luajit_luajit
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository proxy_wasm_cpp_sdk instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:219:24: in envoy_dependencies
  /source/bazel/repositories.bzl:1000:26: in _proxy_wasm_cpp_sdk
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_google_flatbuffers instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:226:26: in envoy_dependencies
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_nlohmann_json instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:194:30: in envoy_dependencies
  /source/bazel/repositories.bzl:588:26: in _com_github_nlohmann_json
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_datadog_dd_opentracing_cpp instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:171:43: in envoy_dependencies
  /source/bazel/repositories.bzl:559:26: in _com_github_datadog_dd_opentracing_cpp
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository org_golang_google_protobuf instantiated at:
  /source/WORKSPACE:25:25: in <toplevel>
  /source/bazel/dependency_imports.bzl:25:26: in envoy_dependency_imports
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/io_bazel_rules_go/go/private/repositories.bzl:135:11: in go_rules_dependencies
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/io_bazel_rules_go/go/private/repositories.bzl:292:18: in _maybe
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_curl instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:200:21: in envoy_dependencies
  /source/bazel/repositories.bzl:834:26: in _com_github_curl
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_google_jwt_verify instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:177:34: in envoy_dependencies
  /source/bazel/repositories.bzl:1013:26: in _com_github_google_jwt_verify
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_github_facebook_zstd instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:216:30: in envoy_dependencies
  /source/bazel/repositories.bzl:490:26: in _com_github_facebook_zstd
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository prometheus_metrics_model instantiated at:
  /source/WORKSPACE:9:23: in <toplevel>
  /source/bazel/api_repositories.bzl:4:21: in envoy_api_dependencies
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/repositories.bzl:29:26: in api_dependencies
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/repositories.bzl:9:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_lightstep_tracer_cpp instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:207:30: in envoy_dependencies
  /source/bazel/repositories.bzl:552:26: in _com_lightstep_tracer_cpp
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository org_brotli instantiated at:
  /source/WORKSPACE:13:19: in <toplevel>
  /source/bazel/repositories.bzl:215:16: in envoy_dependencies
  /source/bazel/repositories.bzl:477:26: in _org_brotli
  /source/bazel/repositories.bzl:31:23: in external_http_archive
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_google_cel_cpp/parser/BUILD:19:11: @com_google_cel_cpp//parser:parser depends on @antlr4_runtimes//:cpp in repository @antlr4_runtimes which failed to fetch. no such package '@antlr4_runtimes//': java.io.IOException: Error downloading [https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/antlr4_runtimes/temp3222524729275118446/v4.10.1.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: 
INFO: Elapsed time: 28.972s
INFO: 0 processes.
···
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by daixiang0** [comment]
You can see the error is about dep downloading, I guess it would be network issue, could you try to access those links inside container directly?

If you run it behind proxy server, you need to set proxy env like `HTTP_PROXY` and so on.

**Comment by 13567436138** [comment]
i got 404  as i download the dependency manual

**Comment by 13567436138** [comment]
https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz
you can wget this got 404

**Comment by 13567436138** [comment]
yestoday it is ok,this must be new problem

**Comment by 13567436138** [comment]
aliyun america machine why will there be network problem

**Comment by 13567436138** [comment]
```
[root@localhost ~]# wget https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz 
--2022-09-01 19:36:35--  https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/antlr/antlr4/tar.gz/v4.10.1 [following]
--2022-09-01 19:36:35--  https://codeload.github.com/antlr/antlr4/tar.gz/v4.10.1
Resolving codeload.github.com (codeload.github.com)... 20.205.243.165
Connecting to codeload.github.com (codeload.github.com)|20.205.243.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-01 19:36:36 ERROR 404: Not Found.
```
redirect to https://codeload.github.com/antlr/antlr4/tar.gz/v4.10.1   why?

**Comment by mattklein123** [comment]
cc @phlax
