### ISSUE TITLE
is there a build image for envoy，I build several times ，all failed，and is there a doc for building

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22936]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
is there a build image for envoy，I build several times ，all failed
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
You can build in in container via `./ci/run_envoy_docker.sh "ci/do_ci.sh ${target}"`, all targets can refer to https://github.com/envoyproxy/envoy/tree/main/ci.

Also we have images on dockerhub, please see https://hub.docker.com/r/envoyproxy/envoy.
