### ISSUE TITLE
can anybody provider CMakeLists.txt for envoy，for clion

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22937]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
can anybody provider CMakeLists.txt for envoy，for clion
*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
For IDE, you can use devcontainer by vscode, please see https://github.com/envoyproxy/envoy/tree/main/.devcontainer.

**Comment by 13567436138** [comment]
but i want to use clion vs code is not intelligent of c++ plugin

**Comment by mattklein123** [comment]
I think @lizan had a script for this at some point but per the other comment I would just use vscode.

**Comment by 13567436138** [comment]
vs code can not debug，with error /tmp/Microsoft-MIEngine-Cmd-mjpdm1oo.i4m: line 2: 16812 Aborted                 (core dumped) "/opt/rh/gcc-toolset-11/root/usr/bin/gdb" --interpreter=mi --tty=$DbgTerm < "/tmp/Microsoft-MIEngine-In-wzcnfnkh.urt" > "/tmp/Microsoft-MIEngine-Out-v41sterm.d04"
[root@localhost envoy]#

**Comment by daixiang0** [comment]
Maybe you miss this -- https://github.com/envoyproxy/envoy/tree/main/tools/vscode#generate-debug-config
