### ISSUE TITLE
Looking for a solution to load thousands IP address for IP matcher to block IP

### ISSUE THREAD

**Issue by znqjnny** [envoyproxy/envoy#22930]
Hi, we are trying to do an IP filter for thousands of IPs. We planning to use RBAC for the IP block and combined it with IP matcher to match the IP.
And we realize it is frustrating to put the IP address in the config map static since there're thousands, it would make the configMap very big and would be hard to maintain. 

We are thinking about using java-control-plane to push the IP address dynamically. But we don't know if that's the best solution and if there's any challenge to do in this way.
So we would like to look for a guide if there are any other solutions that work better for thousands of IP case. 

Thank you!

**Comment by soulxu** [comment]
Maybe ECDS can help you https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/extension#config-overview-extension-discovery, it allows the filter config to be dynamic, but it only supports listener filter and HTTP filters.

cc @kyessenov @adisuissa

**Comment by kyessenov** [comment]
ECDS is an option. It does require pushing the entire list on every update because xDS does not have a way to push "delta" per resource. If you want really fine grained deltas for the lists, then a custom extension that can subscribe to its own xDS resource stream is better.

**Comment by znqjnny** [comment]
Thank you for your advice @soulxu  and @kyessenov ! I wonder are there any more examples I can learn about ECDS?

**Comment by soulxu** [comment]
> Thank you for your advice @soulxu and @kyessenov ! I wonder are there any more examples I can learn about ECDS?

@znqjnny here is the API doc for configure ecds https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#envoy-v3-api-msg-config-core-v3-extensionconfigsource, I didn't find any example since it is a quite new feature

**Comment by znqjnny** [comment]
Thanks so much for help @soulxu !
