### ISSUE TITLE
Could I custom upstream child span's kind to CLIENT?

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#22944]
*Title*: Could I custom upstream child span's kind to CLIENT?

*Description*:
I'm using zipkin and enable child span with `start_child_span` in router config. I found the `kind` is `SERVER` when traffic_direction is `INBOUND`. I'm using Envoy as a gateway, so I want the inbound span to be `SERVER` and the child span is `CLIENT`. It seems it follows the http filter trace config from this PR https://github.com/envoyproxy/envoy/pull/2170/files#diff-e3584a650478334f7373c0df344c85d499b5123f5237ce2bbabaad5ee53b899eL751

Is there any way to customize this? Or maybe we should always set it to `CLIENT`(egress)?

[optional *Relevant Links*:]
This can be reproduced with the [zipkin example](https://github.com/envoyproxy/envoy/tree/main/examples/zipkin). And this is the json body for envoy-1:
```
[
  {
    "localEndpoint": {
      "port": 0,
      "serviceName": "envoy-proxy-1",
      "ipv4": "172.18.0.6"
    },
    "parentId": "4865575b60739ef9",
    "shared": true,
    "id": "99a2e42466ec967f",
    "traceId": "4865575b60739ef9",
    "annotations": [
      {
        "timestamp": 1662026117696389,
        "value": "ss"
      }
    ],
    "tags": {
      "response_flags": "-",
      "upstream_cluster": "service_cluster1",
      "peer.address": "172.18.0.4:8080",
      "upstream_cluster.name": "service_cluster1",
      "upstream_address": "172.18.0.4:8080",
      "http.protocol": "HTTP/1.1",
      "http.status_code": "200",
      "component": "proxy"
    },
    "duration": 1637,
    "name": "router service_cluster1 egress",
    "timestamp": 1662026117694751,
    // I want this to be CLIENT for egress span
    "kind": "SERVER"
  },
  {
    "duration": 1702,
    "id": "99a2e42466ec967f",
    "localEndpoint": {
      "ipv4": "172.18.0.6",
      "serviceName": "envoy-proxy-1",
      "port": 0
    },
    "annotations": [
      {
        "timestamp": 1662026117696419,
        "value": "ss"
      }
    ],
    "traceId": "4865575b60739ef9",
    "shared": true,
    "timestamp": 1662026117694651,
    "name": "routeToEnvoy1",
    "kind": "SERVER",
    "parentId": "4865575b60739ef9",
    "tags": {
      "user_agent": "curl/7.61.1",
      "http.method": "GET",
      "request_size": "0",
      "http.protocol": "HTTP/1.1",
      "upstream_cluster": "service_cluster1",
      "http.status_code": "200",
      "response_size": "37",
      "http.url": "http://127.0.0.1:10000/trace/1",
      "downstream_cluster": "-",
      "peer.address": "172.18.0.7",
      "response_flags": "-",
      "upstream_cluster.name": "service_cluster1",
      "guid:x-request-id": "79698dd0-2c31-90cc-b452-fa1c1a217ea6",
      "component": "proxy"
    }
  }
]
```
btw, If I change traffic_direction of envoy-proxy-1:10000 to `OUTBOUND`, both above spans will be CLIENT.

**Comment by mattklein123** [comment]
cc @wbpcode

**Comment by kyessenov** [comment]
Inbound/outbound are most often used for sidecar-type proxy (reverse/regular proxy). For a load balancing proxy like gateway, we were considering adding another listener type that would maybe emit something different (or maybe two spans).  Istio I think configures all gateway to be outbound but that's wrong for egress gateways.

**Comment by wbpcode** [comment]
@tony612 sorry, the zipkin tracer was designed for sidecar mode and have no a perfect support to the `start_child_span`.

I will try to patch it to fix problem.

**Comment by tony612** [comment]
@kyessenov Got it.
@wbpcode Sounds good.
