### ISSUE TITLE
New Feature: Sandboxed lua scripts

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#2294]
*Title*: *Sandboxed Lua scripts*

*Description*:
At present lua script execution is not sandboxed.
Specifically  A script can
1. go into an infinite loop.
2. access file system
3. use a lot of CPU

We should be able to run lua in untrusted mode when desired to support
1. Multi tenancy
2. An Authz server can return a lua script as a cache condition. In order to not trust the  authz server beyond making policy decisions,  the lua response should be run in a sandbox.

This could be achieved by
1. requiring use of lua expressions vs scripts.
2. specifically disabling file system access.
3. High CPU

**Comment by mandarjog** [comment]
@htuch @mattklein123

**Comment by mattklein123** [comment]
@mandarjog I think it's going to be almost impossible to offer fully sandboxed/safe Lua. AFAIK LuaJit does not offer any capability to interrupt after X instructions or whatever, which I think is what you would need to implement this for real.

Anyway, marking help wanted if someone would like to explore this.

**Comment by mbanikazemi** [comment]
@mattklein123 using lua_sethook() [1] one can limit the number of instructions being executed and/or monitor execution of certain calls, etc. Is such an approach worth pursuing?

[1] https://www.lua.org/manual/5.3/manual.html

**Comment by mattklein123** [comment]
@mbanikazemi I'm not familiar. At least when using the JITer once you enter assembly code it's not clear to me how the number of instructions can be easily limited. I'm not sure what LuaJIT does in this area.
