### ISSUE TITLE
Per worker Connection pool size for TCP Proxy filter

### ISSUE THREAD

**Issue by shashank0791** [envoyproxy/envoy#22951]
**Context** - We recently deployed Istio's Envoy (v1.17) as a sidecar process across some of our pre-production fleet. The Envoy Proxy is using TCP_PROXY filter for all in bound and outbound traffic. We are leveraging Envoy for Encryption and proxy for inter-host communication. 
During our tests, we observed that as concurrent connection count increases to 100, Envoy starts dropping the connection requests. Subsequent retries from our client application do succeed in establishing the connection but that increases the end to end time for the requests.

Envoy configuration:
`worker_count: 56` 
`idle_timeout: 1 hour (default)`
`connect_timeout: 1 second`
`tcp_keepalive: disabled`

**Connection overhead increased by more than 2x with Envoy**
Without Envoy in picture, we do not observe retries even at 2K concurrent connection requests. This made us confident that Envoy is adding a much larger overhead than we previously anticipated.
We observed connection time increased by more than 6x (from 200 ms to 1.2 seconds) at just 100 concurrent connection count with Envoy proxy. This indeed triggered connection timeout at Envoy causing Envoy to drop the connection. 
However, at such a low connection count, I presumed Envoy would scale well.

**There are some information that we need in order to proceed with the analysis:**
1. Connection pool size per worker thread
2. Max concurrent connection count that each worker thread can handle.

Can some one please help get this information for us ? I looked at the latest `master` branch code but did not find this information.

**Comment by daixiang0** [comment]
I am curious about `worker_count`, Envoy use `--concurrency` to specify the number of worker thread, or it detects the CPU number and uses it.

In your configuration, it is 56, so is it CPU number in your machine? It may be not a good choice to use so many workers for a sidecar.

You can get the truly number of worker threads from the Envoy log or stats.

**Comment by shashank0791** [comment]
@daixiang0 Yes. In our case, we have set worker count == CPU core count to start our benchmarking. For production we might end up with something smaller. 
It all depends on how quick connection setup takes with Envoy in picture which is why we need more insights into connection pooling

**Comment by moderation** [comment]
I've found this older article from @mattklein123 on the Envoy threading model to be helpful

> One major takeaway however is that from a memory and connection pool efficiency standpoint, it is actually quite important to tune the--concurrency option. Having more workers than is needed will waste memory, create more idle connections, and lead to a lower connection pool hit rate. At Lyft our sidecar Envoys run with very low concurrency so that the performance roughly matches the services they are sitting next to. We only run our edge Envoys at max concurrency.

https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310

**Comment by labilezhu** [comment]
Hope someone can clarify it.
