### ISSUE TITLE
FCDS draining logic

### ISSUE THREAD

**Issue by rakeshdatta** [envoyproxy/envoy#22967]
*Title*: *Filter-Chain Discovery Service: configure draining granularity*

*Description*:
Hello All, I am trying to implement FCDS, where I will be having a bunch of access policies inside a filter chain. Much like a listener is having a bunch of filter chains.

Requirement 1:
When a filter-chain update is received through FCDS, for the connection under HTTP connection manager filter, I dont want them to drain at all. Can I turn off the draining somehow? Is there a setting? 

Requirement 2: 
I want more granular draining, meaning within a filter chain I will check which policy rule config is updated (much like doing filter chain only update in LDS) and just drain the connections which did hit that modified policy.

Need implementation suggestion.

**Comment by mattklein123** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
For requirement 1: I think ECDS for RBAC would avoid draining and just apply to new requests.
For requirement 2: filter chain "owns" all its connections. So if you want something more granular (e.g. something decided by an individual filter) you have to look inside the filter chain. One idea would be to allow ECDS apply retro-actively in some cases. That sounds useful for long-living TCP connections, for example, if only a subset of them need to be denied. Another idea is not to reload xDS filter config at all, and manage policies internally within the filter via a separate subscription model.
