### ISSUE TITLE
vs code debug problem

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22974]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
/tmp/Microsoft-MIEngine-Cmd-winez2b3.5jl: line 2: 11365 Aborted                 (core dumped) "/opt/rh/gcc-toolset-11/root/usr/bin/gdb" --interpreter=mi --tty=$DbgTerm < "/tmp/Microsoft-MIEngine-In-jfdfwozk.ewx" > "/tmp/Microsoft-MIEngine-Out-fda3xgga.2tp"

```
[admin@localhost envoy]$ /opt/rh/gcc-toolset-11/root/usr/bin/gdb -v
GNU gdb (GDB) Red Hat Enterprise Linux 10.2-5.el8
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[admin@localhost envoy]$ 
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) 启动", 
            "type": "cppdbg",
            "request": "launch", 
            "program": "${workspaceFolder}/envoy-debug", 
            "args": [ "-c", "/home/admin/envoy/examples/brotli/brotli-envoy.yaml", "--service-cluster", "brotli"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}", 
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath":"/opt/rh/gcc-toolset-11/root/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

envoy debug binary was build in ubuntu system,I am using centos8 to debug ,will this a prolblem?

envoy was compiled by ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.debug.server_only'
envoy version is release/v1.23

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by 13567436138** [comment]
1: (2471) ->1006^error,msg="Dwarf Error: bad DWP hash table, lookup didn't terminate [in module /build/envoy/source/exe/envoy/envoy.dwp]"

**Comment by daixiang0** [comment]
cross with https://github.com/envoyproxy/envoy/issues/22788
