### ISSUE TITLE
Envoy external auth for gRPC clusters should be once per connection 

### ISSUE THREAD

**Issue by lakamsani** [envoyproxy/envoy#22986]
This is identical to recently auto closed issue:

https://github.com/envoyproxy/envoy/issues/20608

*Description*:

Envoy external auth for backend grpc clusters should behave similar to ngnix sub request.

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

Authentication is performed once per connection on the first RPC. After that all subsequent RPCs on the same connection do not trigger authentication. Thanks.

**Comment by wbpcode** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
It depends entirely on the use case whether this behavior would be correct. Consider the case of another proxy in front of the one doing auth, which multiplexes multiple client requests over one connection. In that case, auth must be done per-request.

This behavior could be added as an option which defaults to disabled. PRs welcome.

**Comment by lakamsani** [comment]
> It depends entirely on the use case whether this behavior would be correct. Consider the case of another proxy in front of the one doing auth, which multiplexes multiple client requests over one connection. In that case, auth must be done per-request.
> 
> This behavior could be added as an option which defaults to disabled. PRs welcome.

That's a fair point. Thanks. Any pointers on where to start for possible PR that would be awesome.

**Comment by ggreenway** [comment]
Main filter code is here: https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/ext_authz

I think the way to do it is to set a [FilterState](https://github.com/envoyproxy/envoy/blob/main/envoy/stream_info/filter_state.h) with `Connection` LifeSpan. This can be set on the `StreamInfo`. New config setting and docs can be added to https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto

**Comment by lakamsani** [comment]
Hi, @ggreenway  started working on this. Need help with the dev env. Posted [here](https://envoyproxy.slack.com/archives/C78HA81DH/p1662932959628399) if you have any thoughts. Thanks.
