### ISSUE TITLE
how to debug envoy

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22982]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
i use ci compile debug binary,but debug with vs code,has errers of dwarf dwp hash table error in dwp file

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
Please check https://github.com/envoyproxy/envoy/tree/main/tools/vscode#generate-debug-config.

**Comment by wbpcode** [comment]
Duplicate with #22974.
