### ISSUE TITLE
OAuth2 filter POST request with expired token

### ISSUE THREAD

**Issue by Alexcei88** [envoyproxy/envoy#23007]
I am using [OAuth2 filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) to protect my backend. I faced with following unpleasant issue.

1. User opens my site
2. User authorizes and gets JWT token for 5 minutes.
3. User works on site for 5 minutes. 
4. Token is expired and user sends POST http method instead of GET method(any save operation on my site)
5. Because the token is expired, Envoy redirects user to IDP, user gets new JWT token, and after that instead of HTTP POST method my backend is recieved HTTP GET method, but initially my site had sent HTTP POST method.

Is there a best way to resolve such behaviour?

**Comment by wbpcode** [comment]
cc @snowp

**Comment by Alexcei88** [comment]
I think when we recieved callback from IDP, we need to send source request further without redirect to browser.

**Comment by Alexcei88** [comment]
Could you add the tag "help wanted" please

**Comment by Alexcei88** [comment]
Could you add the tag "help wanted" please?

**Comment by vikaschoudhary16** [comment]
Why this is closed given that linked PR is still open?
