### ISSUE TITLE
support show http filter ECDS info in config_dump

### ISSUE THREAD

**Issue by zema-MSFT** [envoyproxy/envoy#23008]
*Title*: *support show http filter ECDS info in config_dump*

*Description*:
>I'm using the ECDS to avoid listener drainer when filter configuration changed, but when I checked the config_dump for my filter info in config_dump, there isn't any info for that, the ECDS filter info in config_dump will be like:

`                         
{
              "name": "envoy.filters.http.rbac.xxx",
              "config_discovery": {
               "config_source": {
                "ads": {},
                "initial_fetch_timeout": "0s",
                "resource_api_version": "V3"
               },
               "type_urls": [
                "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
               ]
              }
             }
`
Will envoy support to show ecds config info in config_dump? or if it already supports that could you help to point how to add such info? 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
I think we _did_ implement ECDS in the config dump. It could be not wired into the config_dump output, probably need to investigate a bit further.

**Comment by zema-MSFT** [comment]
hi, @kyessenov   would you ever have time for an investigation on this? thx

**Comment by kyessenov** [comment]
Duplicate of https://github.com/envoyproxy/envoy/issues/20086
