### ISSUE TITLE
how to debug envoy external dependency.set break point in dependency

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#23018]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
how to debug envoy external dependency.set break point in dependency
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by snowp** [comment]
This probably comes down to the tooling you're using, in gdb for example you would be able to set a breakpoint based on a symbol name which should achieve this
