### ISSUE TITLE
debug problem

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#23029]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
1: (48501) 1302: elapsed time 0
1: (48735) ->&"DW_FORM_strp pointing outside of .debug_str section [in module /build/.cache/bazel/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/bin/source/exe/envoy-static]\n"
1: (48735) ->(gdb)

![image](https://user-images.githubusercontent.com/31508490/189036311-3e75710a-abe5-4050-8c94-98f9d0730bb1.png)

initial parameter list，insider has break point。

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by snowp** [comment]
Not clear what the problem is here, can you elaborate?

**Comment by 13567436138** [comment]
if I set break point in contructor of init parameter ,It will show up problem.
