### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lehp** [envoyproxy/envoy#23034]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

Auto-Generate envoy route-config from swaggerfile

I'm currently working on a project to automatically generate route-config for a "service-envoy". I have several ways in mind but can't believe that noone has done that before me. Is there a way to do this the easy way?

 We specifically want to use "pure envoy" and not any frameworks because we have some specific requirements to the config-generation.

**Comment by snowp** [comment]
It's possible that something like this exists, but I can't think of anything at the top of my mind. There are a ton of different implementations that end up generating a route config based on various inputs, most commonly integrating with Kubernetes APIs. I'd guess that some companies probably do this or something similar internally but haven't open sourced it
