### ISSUE TITLE
Give virtual_cluster header matching access to response code

### ISSUE THREAD

**Issue by aetracht** [envoyproxy/envoy#23053]
*Match virtual clusters using response code*: *Expose the response code to the header matching in virtual cluster definitions.*

*Description*:
When trying to get "more perfect" stats for critical routes, it would be useful if we could get per-response-code histograms. This could be accomplished without a combinatoric explosion by exposing the response code as `:code`  pseudo-header in the virtual cluster header matching, like is already done for `:authority`, `:path`, and `:method`.

`range`, `prefix`, or `exact` matches would then be able to select/group the response codes as desired.

**Comment by snowp** [comment]
I believe the virtual cluster matches matches against the request headers when resolving the route, so including the response code here would be pretty involved.

Are you not able to get what you want by looking at the per-code stats for the virtual clusters?

**Comment by MaggieAHewitt** [comment]
This change would allow us to calculate the [Apdex scores ](https://www.techtarget.com/searchitoperations/definition/Application-Performance-Index-Apdex)for virtual clusters. 

More specifically, we need a way to calculate the Satisfied and Tolerating requests where:

```
Satisfied Request = request_duration < satisfied_request_duration and response_code == 200
Tolerated Request = satisfied_request_duration < request_duration  < tolerated_request_duration 
                    and response_code == 200
```

**Comment by snowp** [comment]
Given that virtual cluster matching also wouldn't catch latency thresholds, would perhaps ingesting access logs be a better fit? That way the virtual cluster matching can happen as it does now, and you could evaluate each access log to get the duration + status + virtual cluster?
