### ISSUE TITLE
http/2: further analysis of GOAWAY/draining behavior

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2305]
See this comment thread: https://github.com/envoyproxy/envoy/pull/2295#discussion_r159440920

cc @alyssawilk

**Comment by mattklein123** [comment]
Also related to https://github.com/envoyproxy/envoy/issues/1572.

**Comment by mattklein123** [comment]
@alyssawilk yeah for high RPS cases the race condition is still there. I'm going to do further fixes in this area. Probably #1572 first.

**Comment by alyssawilk** [comment]
Aww, I was hoping for your sake your PR would fix your immediate problem.

So I'm sure that issue captures enough state for you, but I'm still not clear on what the actual plan is =P.  My clarifying question for you, is if the improvements over there are useful long term changes to x-envoy-immediate-health-check-fail or are they workarounds to downstream-Envoy not having proper GOAWAY-health interactions?  If fixing this would remove the necessity for x-envoy-immediate-health-check-fail changes, I'd probably lean on you to do the general purpose solution but if they're both useful changes than obviously expediency wins and go with whatever will make your production environment happy soonest :-)

**Comment by mattklein123** [comment]
It turns out that my change did not actually get deployed (I thought it did). So I will need to wait and see what the effect is. If it doesn't work, my plan was a two-pronged approach:
1) Change how drain/lame-duck works slightly to allow a delay period in which x-envoy-immediate-health-check-fail is sent, but we aren't actually draining connections. This would smooth over the Envoy mesh case very well.
2) Fix http/2 connection pool to allow a list of draining connections with a cap. I still am not super crazy about this solution since it can still easily lead to churning, but with sane/recommended configs it would likely be better.

**Comment by mattklein123** [comment]
@alyssawilk FYI my change did fix our issues, so I don't have any near term plans to work on this. Will leave this open to track.

**Comment by mattklein123** [comment]
Going to close this out as this has not been a real issue. We can reopen if needed with a more specific task.
