### ISSUE TITLE
[Question] Got a upstream host ejected through outlier_detection, but the host still has membership

### ISSUE THREAD

**Issue by drinkbeer** [envoyproxy/envoy#23057]
*Title*: *[Question] Got a upstream host ejected through outlier_detection, but the host still has membership*

*Description*:
>Describe the issue.

I am testing the [outlier_detection](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#failure-percentage) configuration with Redis proxy in our staging environment.

Here is my outlier configuration in the clusters:
```
    outlier_detection:
      base_ejection_time: 300s
      max_ejection_time: 600s
      max_ejection_percent: 100
      interval: 1s
      consecutive_5xx: 1
      failure_percentage_threshold: 1
      enforcing_failure_percentage: 0
      enforcing_failure_percentage_local_origin: 0
      failure_percentage_minimum_hosts: 1
      failure_percentage_request_volume: 1
```

I have 2 proxy hosts, and 4 cache hosts in the staging. What I did was to make one cache host stuck in `BUSY` state using a lua script, and then use a ruby script to send the requests with sequential keys (key name has sequential number so it can evenly distribute the keys to all 4 pods, and hence has the chance to trigger the outlier host through failure rate).

Lua script:
```lua
local i = 0
while (true) do
    local key = "Key-" .. i
    local value = "Value-" .. i
    redis.call('set', key, value)
    i = i + 1
    redis.call('time')
end
```

Command:
```
redis-cli -h vecache-0.vecache-service.arrive-server-staging.svc.cluster.local EVAL "$(cat test.lua)" 0 1500000
```

Ruby script: 
```ruby
require 'redis'

ITERATIONS = 10_000
url = "<the proxy service url>"
rc = Redis.new(url: url)

ITERATIONS.times do |i|
  puts "test_key_#{i}"
  rc.set("test_key_#{i}", "test_value")
end
```

What I observed is, one proxy flagged the cache host with `health_flags::/failed_outlier_check`:

```
vecache::244.76.31.51:6379::cx_active::1
vecache::244.76.31.51:6379::cx_connect_fail::0
vecache::244.76.31.51:6379::cx_total::2
vecache::244.76.31.51:6379::rq_active::0
vecache::244.76.31.51:6379::rq_error::0
vecache::244.76.31.51:6379::rq_success::0
vecache::244.76.31.51:6379::rq_timeout::1
vecache::244.76.31.51:6379::rq_total::151
vecache::244.76.31.51:6379::hostname::vecache-0.vecache-service
vecache::244.76.31.51:6379::health_flags::/failed_outlier_check
vecache::244.76.31.51:6379::weight::1
vecache::244.76.31.51:6379::region::
vecache::244.76.31.51:6379::zone::
vecache::244.76.31.51:6379::sub_zone::
vecache::244.76.31.51:6379::canary::false
vecache::244.76.31.51:6379::priority::0
vecache::244.76.31.51:6379::success_rate::-1.0
vecache::244.76.31.51:6379::local_origin_success_rate::-1.0
```

While another proxy has the cache host with `healthy`:

```
vecache::244.76.31.51:6379::cx_active::3
vecache::244.76.31.51:6379::cx_connect_fail::0
vecache::244.76.31.51:6379::cx_total::3
vecache::244.76.31.51:6379::rq_active::0
vecache::244.76.31.51:6379::rq_error::0
vecache::244.76.31.51:6379::rq_success::0
vecache::244.76.31.51:6379::rq_timeout::0
vecache::244.76.31.51:6379::rq_total::244
vecache::244.76.31.51:6379::hostname::vecache-0.vecache-service
vecache::244.76.31.51:6379::health_flags::healthy
vecache::244.76.31.51:6379::weight::1
vecache::244.76.31.51:6379::region::
vecache::244.76.31.51:6379::zone::
vecache::244.76.31.51:6379::sub_zone::
vecache::244.76.31.51:6379::canary::false
vecache::244.76.31.51:6379::priority::0
vecache::244.76.31.51:6379::success_rate::-1.0
vecache::244.76.31.51:6379::local_origin_success_rate::-1.0
```

The ejection log:
```
# cat /tmp/outlier_events.log
{"type":"CONSECUTIVE_5XX","cluster_name":"vecache","upstream_url":"244.76.31.51:6379","action":"EJECT","num_ejections":1,"enforced":true,"eject_consecutive_event":{},"timestamp":"2022-09-10T06:33:25.679Z"}
{"type":"CONSECUTIVE_5XX","cluster_name":"vecache","upstream_url":"244.76.31.51:6379","action":"UNEJECT","num_ejections":1,"enforced":false,"timestamp":"2022-09-10T06:38:26.029Z","secs_since_last_action":"300"}
```

During the test, the `ejection_active` metric surged, but the membership count didn't change. I thought the problematic host should be kicked out of the hash ring, but seems like it is not because my script still sees `Redis::CommandError`.

<img width="2218" alt="image" src="https://user-images.githubusercontent.com/3954499/189472668-e06bbcf4-0aa9-47fe-aacd-c603bc3eea85.png">

<img width="2209" alt="image" src="https://user-images.githubusercontent.com/3954499/189472734-78965c32-d130-4496-b2ec-753392439544.png">

I thought that once the error rate exceeds the threshold, all the proxies should flag the problematic host as `health_flags::/failed_outlier_check`. Why in my test, only one host is flagged as `failed_outlier_check`?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by snowp** [comment]
Outlier detection is local to the process, there is no communication between different proxies that would allow them all to flag the same host, so this seems to be working as intended. When we say that the host is ejected, we mean that it's marked as unhealthy and thus not considered during load balancing (unless panic mode activates)

**Comment by drinkbeer** [comment]
> Outlier detection is local to the process, there is no communication between different proxies that would allow them all to flag the same host, so this seems to be working as intended. When we say that the host is ejected, we mean that it's marked as unhealthy and thus not considered during load balancing (unless panic mode activates)

The only one proxy flag the cache instance as unhealthy, then other caches may still send requests to the instance, and trigger consecutive 5xx errors, and then trigger the outlier detection again, right? Will this behaviour cause inconsistency between cache instances? For example, 

Scenario1: proxy A has (cache1, cache2, cache3, cache4), proxy B has (cache1, cache2, cache3). The operations:
1. A key `SET` is sent to proxyA and forward to `cache4`
2. A key `GET` is sent to proxyB and found key missing, and then read from DB, then write to `cache2`
3. A key `UPDATE` is sent to proxyB, and updated the payload in `cache2`
4. A key `GET` is sent to proxyA and get payload from `cache4` which is stale
