### ISSUE TITLE
Question regarding filtering metrics

### ISSUE THREAD

**Issue by v-Kris** [envoyproxy/envoy#23051]
*Title*: *Question regarding filtering metrics*

*Description*:
>I'm using the following image `840364872350.dkr.ecr.eu-west-1.amazonaws.com/aws-appmesh-envoy:v1.22.2.1-prod` and after creation of container in AWS ECS, I'd like to test some metrics filters by updating configuration inside the running container. I see there is an `inclusion` / `exclusion` list available from `stats_matcher`.
>
>How to achieve that? What commands or what API calls may I use to update that?

**Comment by 13567436138** [comment]
it sealms you can config in startup args

**Comment by v-Kris** [comment]
yes, I can do that, but what after startup and how to update those settings when the envoy instance is running?

**Comment by snowp** [comment]
Currently this can only be configured in bootstrap, which means that you cannot change this without re-starting the process.  The way this is implemented makes it pretty hard to change this at runtime, as this filter is evaluated when stat handles are created, not when stats are recorded

**Comment by v-Kris** [comment]
Thank you for your answer @snowp 

I'm checking some filters at startup and I noticed that when I create any filter (`inclusion` or `exclusion` list) I don't see any metrics at AWS CloudWatch. For example, even if I create only the following `exclusion` list:

```
stats_config:
 stats_matcher:
  exclusion_list:
    patterns:
      - safe_regex:
          google_re2: {}
          regex: ".*membership_total$"
```
it seems that all metrics are filtered out and nothing is going to AWS CloudWatch.

Am I missing something in that config above?
