### ISSUE TITLE
Kafka caching to prevent broker egress

### ISSUE THREAD

**Issue by abergmeier** [envoyproxy/envoy#23059]
*Title*: *Provide opaque way of reducing broker egress*

*Description*:
We have a scenario, where brokers are hosted in Cloud **A** and consumers are running in Cloud **B**.
Now we have multiple independent consumers in B, that poll the same topic of A.
With every consumer we thus have a linear increase of egress costs of A.
Parameters are:
1. Prevent linear increase in egress costs
2. Keep consumers as independent as possible
3. Do not host another Kafka cluster

# Idea 1:

Have a _proxy_ that can poll messages from a broker (_store_) in B and if that broker does not answer in deadline, fallback to polling from broker in A. All polled messages from A are automatically produced to broker (_store_) in B. Broker (_store_) in B would thus be a Kafka broker shim that would store to Redis.

```mermaid
flowchart LR
  BR(broker)
  CON1(consumer1)
  CON2(consumer2)
  PRX1(proxy1)
  PRX2(proxy2)
  STR(store)
  RED(redis)
  subgraph Cloud A
      BR
  end
  subgraph Cloud B
    CON1
    CON2
    PRX1
    PRX2
    STR
    RED
  end

  CON1-- poll -->PRX1
  CON2-- poll -->PRX2
  PRX1-- 2. poll -->BR
  PRX1-- 3. push polled -->STR
  PRX1-- 1. poll -->STR
  PRX2-- 2. poll -->BR
  PRX2-- 3. push polled -->STR
  PRX2-- 1. poll -->STR
  STR-- store with ttl -->RED
```

From what I can see currently it seems for this to work we would need two components:
1. the _proxy_ (Envoy filter?)
2. a broker shim that can store messages in a backend/Redis (Envoy filter?)

## Pros
- Consumers stay independent. If one _proxy_ fails the other _consumer_ might still work fine. 
## Possible cons
With the independent proxies and communication, there is a chance that due to timings the actual cache hit rate might be less than desired.

# Idea 2:

Thus maybe be better approach would be to have just one instance of the proxy.

```mermaid
flowchart LR
  BR(broker)
  CON1(consumer1)
  CON2(consumer2)
  PRX(proxy)
  STR(store)
  RED(redis)
  subgraph Cloud A
      BR
  end
  subgraph Cloud B
    CON1
    CON2
    PRX
    STR
    RED
  end

  CON1-- poll -->PRX
  CON2-- poll -->PRX
  PRX-- 2. poll -->BR
  PRX-- 3. push polled -->STR
  PRX-- 1. poll -->STR
  STR-- store with ttl -->RED
```

## Pros
- Cache timings are not a problem anymore
## Cons
- Consumers are not that independent anymore
- Introduces single point of failure

**Comment by snowp** [comment]
I'm not sure I understand the problem here enough to comment, this seems pretty specific to a single use case. Is this something general enough to warrant living in OSS? Or are you just looking for feedback on a use case?

cc @mattklein123 as Kafka expert

**Comment by mattklein123** [comment]
cc @adamkotwasinski for further comment. At a high level:
1) This seems like a very specific use case. I'm not sure that Envoy is a good fit here? Seems like you could build a service to do this?
2) I'm skeptical that polling, etc. overhead is really going to cause much egress costs? Is this all really worth it? It seems like most cost will be in the actual message transport which I'm assuming is much larger?

**Comment by adamkotwasinski** [comment]
> brokers are hosted in Cloud A and consumers are running in Cloud B

I believe the common solution in Kafka community would be to setup a Kafka Mirror Maker instance and do mirroring A -> B with consumers connecting to location-matching clusters. This obviously violates the 3rd requirement.

> Idea 1 & 2

As mattklein123 has mentioned, it feels like it could be a parallel service that translates Kafka into Redis and vice-versa.
I feel it's also somehow related to https://github.com/envoyproxy/envoy/issues/15113 as we basically are trying to `transform X into Y and vice-versa`.

In general the implementation, Envoy-based or not would need to handle 3 kinds of requests:
```
* API Versions -> saying it supports APIVer.., Metadata, Fetch (similar to what mesh-filter does now)
* Metadata -> pointing every request to service [e.g. Envoy] instance (similar to what mesh-filter does now)
* poll -> that instead of going to Kafka, goes to Redis - it should be pretty "easy" to implement as every Fetch request contains partition + offset (i.e. "give me record at partition adam-13, offset 333").
```

**Comment by abergmeier** [comment]
> > brokers are hosted in Cloud A and consumers are running in Cloud B
> 
> I believe the common solution in Kafka community would be to setup a Kafka Mirror Maker instance and do mirroring A -> B with consumers connecting to location-matching clusters.

You still have that feeling? All people I have talked to at least want to migrate their clusters to Managed. Seems there is less acceptance to running Datastores yourselves.



> 
> > Idea 1 & 2
> 
> As mattklein123 has mentioned, it feels like it could be a parallel service that translates Kafka into Redis and vice-versa. I feel it's also somehow related to #15113 as we basically are trying to `transform X into Y and vice-versa`.

Indeed seems very related.
 
> In general the implementation, Envoy-based or not would need to handle 3 kinds of requests:
> 
> ```
> * API Versions -> saying it supports APIVer.., Metadata, Fetch (similar to what mesh-filter does now)
> * Metadata -> pointing every request to service [e.g. Envoy] instance (similar to what mesh-filter does now)
> * Fetch -> that instead of going to Kafka, goes to Redis - it should be pretty "easy" to implement as every Fetch request contains partition + offset (i.e. "give me record at partition adam-13, offset 333").
> ```

That would be one way, yes.
What I am wondering what the solution would be to handle failover with Envoy. Say you have a Kafka consumer that does not handle changing Brokers after startup. So when your Cluster C breaks down - how do you make it switch to Cluster D? Is the yet handled by mesh filter?
