### ISSUE TITLE
git push checker uses potentially incompatible clang-format

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2306]
*Description*:
When you set up bootstrap, a pre-push check is installed which calls whatever clang-format is in the environment, which might not be compatible with the Envoy style.

We should be able to override the checking to employ docker or some other mechanism to keep the toolchain under control.

**Comment by rishabhkumar296** [comment]
Hi, I would like to work on this issue. It seems that `clang-format-7` is used for pre-push check as mentioned in `tools/check_format.py`. Does the task involve overriding the `clang-format` version using docker or some other mechanism?

**Comment by mk46** [comment]
I think we should close this now. Since #11222 clang-format-10 is used.
