### ISSUE TITLE
Question regarding ext proc / ExternalProcessor filter in envoy

### ISSUE THREAD

**Issue by newwuhan5** [envoyproxy/envoy#23078]
[2022-09-07 08:18:23.843][2686664][warning][misc] [external/envoy/source/common/protobuf/message_validator_impl.cc:35] message 'envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor' is contained in proto file 'envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto' marked as work-in-progress. API features marked as work-in-progress are not considered stable, are not covered by the threat model, are not supported by the security team, and are subject to breaking changes. Do not use this feature without understanding each of the previous points.

When testing this filter, envoy gives this warning? Any one in the community has used this filter in the PRODUCTION?
- name: envoy.filters.http.ext_proc
typed_config:
"@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
failure_mode_allow: false
async_mode: false
request_attributes:
- user
response_attributes:
- server
processing_mode:
request_header_mode: "" <= What value to use?
response_header_mode: "" <= What value to use?
request_body_mode: "" <= What value to use?
response_body_mode: "" <= What value to use?
request_trailer_mode: "" <= What value to use?
response_trailer_mode: "" <= What value to use?
grpc_service:
envoy_grpc:
cluster_name: ext_proc_cluster

Any issues or any suggestions? Any ideas are appreciated!

**Comment by htuch** [comment]
@newwuhan5 can you clarify what you are asking here? Is this a general query on whether there is significant production use?

**Comment by newwuhan5** [comment]
Thank you for a quick answer to my above question.  Seeing the warning during the runtime of envoy, we are at Fidelity wondering if the envoy ext proc filter with an external processor are mature enough to be used in PRODUCTION.  I took the sample from https://github.com/salrashid123/envoy_ext_proc, and get it running locally.  In terms of features available, it seems there are more to be implemented.

**Comment by htuch** [comment]
@yanavlasov @krajshiva @mpwarres  I think this is something we want to steer towards a more production-hardened stance for our internal needs, but I don't think we can make any claims around maturity.

**Comment by pgeler** [comment]
Few thousand RPS: request/response headers mutation + conditional direct response. Has no experience with body/trailer processing.

**Comment by newwuhan5** [comment]
Thank you for the sharing.  We will trying to use this feature after further testing and analysis.  It looks good.
