### ISSUE TITLE
Envoy doesn't proactively stop TCP connection from establishing when server down

### ISSUE THREAD

**Issue by caoyukun0430** [envoyproxy/envoy#23075]
*Title*: *Envoy doesn't proactively stop TCP connection from establishing when server down*

*Description*:
We have a question about envoy’s capability to proactively stop a TCP connection from establishing when the server is down. Our scenario uses envoy with istio. We have one client sleep pod with envoy proxy as sidecar injected(in-mesh) and one tcp-echo server without the envoy sidecar(outside mesh). Now we are making TCP connection from sleep pod to tcpecho server via netcat cmd.
So two TCP connections are established: **sleep container-----TCP1-----proxy container------TCP2----tcpecho.**

At this time, we scale down tcpecho depolyment replicas to zero, so the server is not alive anymore. NOW if we try to establish a new connection from sleep container to tcpecho server via envoy proxy, this is what is happening as per the tpcdump below:
[172.17.0.9 sleep pod, 172.17.0.7 tcpecho server, 33246 sleep container port, 33248 sleep pod port]
Three-way handshake on TCP1 between sleep container and proxy container established successfully, then the first PSH packet sent outside via TCP2, **finally one RST is returned by envoy to sleep container and then connection TCP1 is closed**.
![image](https://user-images.githubusercontent.com/46762174/189850707-10361ff9-76fa-4e1f-8168-25ae0b404d2f.png)

We have the issue that our client application container has no idea about the proxy in between, which means once it saw the three-way handshake of TCP1 connection established, it wrongly thinks the server is up and running. So the data it starts to send will not be received by server and lost.
**So we want to ask: does envoy has the capability/should envoy proactively stop TCP1 connection from establishing when it sees the server/TCP2 connection is down, instead of waiting for the actual PSH and letting the RST to close the TCP1 connection? Would it still make sense to establish TCP1 connection anyway?**

*Repro steps*:
Install istio 1.14 with envoy 1.22.3, and then install sleep pod inside mesh and tcp-echo server outside mesh. Make netcat request from sleep pod.

*Config*:
```
k get pods -o wide
NAME                                    READY   STATUS    RESTARTS   AGE   IP            NODE            NOMINATED NODE   READINESS GATES
sleep-86dbb6d454-7nt7c                  2/2     Running   0          11d   172.17.0.9    xxxxx   <none>           <none>
tcpecho-5c96cb84b-2hlrc                 1/1     Running   0          20h    172.17.0.7    xxxxx   <none>           <none>
k get svc
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                      AGE
sleep                  ClusterIP      10.110.148.159   <none>        80/TCP                                       12d
tcpecho                ClusterIP      10.111.240.232   <none>        9000/TCP,9001/TCP                            20h

istioctl proxy-config listener sleep-86dbb6d454-7nt7c.istio-system --port=9000 -o yaml
- accessLog:
  - filter:
      responseFlagFilter:
        flags:
        - NR
    name: envoy.access_loggers.file
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      logFormat:
        textFormatSource:
          inlineString: |
            [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
      path: /dev/stdout
  address:
    socketAddress:
      address: 10.111.240.232
      portValue: 9000
  bindToPort: false
  filterChains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: outbound|9000||tcpecho.istio-system.svc.cluster.local
        statPrefix: outbound|9000||tcpecho.istio-system.svc.cluster.local
  name: 10.111.240.232_9000
  trafficDirection: OUTBOUND
```

**Comment by kfaseela** [comment]
cc @soulxu

**Comment by soulxu** [comment]
Hope I understand the issue correctly. I don't think Envoy be able to stop the handshake, we know the upstream status after execute the TCP proxy filter, and actually Envoy execute everything after accept the connection.

**Comment by htuch** [comment]
This doesn't really make sense in general, since as @soulxu points out, you need to know what you're proxying to in order to be able to determine if there are healthy hosts. OTOH, if you are getting your health/assignments via EDS, and this is Istio, there are other options. You could have Pilot initiate a listener drain via LDS if the sidecar only has a single cluster and it's unhealthy to stop accepting new TCP connections. That's probably non-trivial, but I would take that up as a Istio GitHub issue, rather than Envoy.

**Comment by caoyukun0430** [comment]
Thanks @soulxu and @htuch for the explaination! I will close since the answer is quite clear from you.
