### ISSUE TITLE
[OAuth2] Cannot passthrough on authorization header

### ISSUE THREAD

**Issue by yanickbelanger** [envoyproxy/envoy#23080]
*Title*: OAuth2 - Cannot passthrough on authorization header

*Description*:
We're using the envoy.filters.http.oauth2 filter in some of our sidecar proxies for protecting web applications. Since a recent version, the passthrough configuration we are using does not work anymore:
```
              pass_through_matcher:
                - name: authorization
                  prefix_match: Bearer
```
This was needed to let requests issued with existing bearer token (from mobile applications for example) to skip the oauth2 filter. Now when a client issues a request with a bearer token, instead of bypassing the oauth2 filter and routing the request to the upstream service, the client now receives a redirection response.

The bug (or feature?) was introduced in May 2022, this line here seems to be the culprit: 
```
headers.removeInline(authorization_handle.handle());
```
(https://github.com/envoyproxy/envoy/blame/main/source/extensions/filters/http/oauth2/filter.cc#L233)

A potential fix could be to sanitize the authorization header after (instead of before) evaluating the passthrough conditions.

**Comment by bars83** [comment]
Any news?

**Comment by timo-haas-by** [comment]
Waiting for approval.

**Comment by yanickbelanger** [comment]
Thank you guys! Can't wait to remove the workaround we had to setup.
