### ISSUE TITLE
[QUIC]Use of size_t causes arithmetic error

### ISSUE THREAD

**Issue by RenjieTang** [envoyproxy/envoy#23097]
The issue happens [here](https://github.com/envoyproxy/envoy/blob/main/source/common/quic/quic_filter_manager_connection_impl.cc#L136) where we subtract 2 size_t and store the result into a int64_t variable.

When size_t is mapped to uint64_t which is the case for most modern system, the subtraction works ok.
But in 32-bit system, for example x86, size_t is mapped to uint32_t, and the subtraction could result in a large overflow number.

These size_t parameters are actually implicitly casted from [uint64_t](https://github.com/envoyproxy/envoy/blob/main/source/common/quic/send_buffer_monitor.cc#L16), which doesn't seem right.

I think we need to change all the relevant code to use uint64_t instead.

**Comment by RyanTheOptimist** [comment]
cc: @danzh2010

**Comment by danzh2010** [comment]
Subtraction of two unsigned type and converting the result into int64_t should be fine. I won't expect overflow here. But QuicFilterManagerConnectionImpl::updateBytesBuffered() implicitly cast uint64_t to size_t (which can be uint32_t) in x86. Is this what actually causes problem?

**Comment by danzh2010** [comment]
Also a side note, the stream buffers so many data in the send buffer?!

**Comment by RenjieTang** [comment]
Subtraction of 2 uint64_t and storing it into int64_t is fine.
But subtraction of 2 uint32_t and storing it in int64_t will cause problem.

Here's a short sample code:
```int main()
{
    uint32_t a = 1;
    uint32_t b = 2;
    int64_t c = a - b;
    int32_t c2 = a - b;
    
    uint64_t d = 1;
    uint64_t e = 2;
    int64_t f = d - e;
    
    printf("c is %ld \n", c);
    printf("c2 is %d \n", c2);
    printf("f is %ld \n", f);

    return 0;
}```

And here's the output:
```c is 4294967295 
c2 is -1 
f is -1 ```

**Comment by danzh2010** [comment]
Thanks for the example! So the stream isn't buffering huge amount of data, but just the new value is smaller than the old value and they are uint32_t.

`updateBytesBuffered()` should take uint63_t instead.
