### ISSUE TITLE
New example: Request mirroring policy

### ISSUE THREAD

**Issue by asaha123** [envoyproxy/envoy#23119]
*Title*: *Add a sandbox example for request mirroring policy*

*Description*:

I am keen to contribute an example for using [request_mirror_policies](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=mirror). 

Wondering if that would be desirable to be accepted as a contribution?

[Example](https://github.com/envoyproxy/envoy/compare/main...asaha123:envoy:route_mirror_example)

**Comment by phlax** [comment]
hi @asaha123 looks good - we would very much welcome the contribution

i see its missing docs atm - its worth stressing that the examples are primarily documentation - the `verify.sh` script is intended to ensure that the docs still/work

i would be happy to work with you on this

**Comment by asaha123** [comment]
@phlax PR is now created!
