### ISSUE TITLE
improve quic coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#23128]
https://github.com/envoyproxy/envoy/pull/23073 lowered quic coverage to land.  bump up and revert

**Comment by RyanTheOptimist** [comment]
For posterity, the coverage report is here:

https://storage.googleapis.com/envoy-pr/73a6a6f/coverage/source/common/quic/index.html

I'll take a look today at increasing coverage, unless you are already working on this, @alyssawilk?
