### ISSUE TITLE
DSCP carryforward from downstream to upstream path

### ISSUE THREAD

**Issue by ryanlyy** [envoyproxy/envoy#23120]
Hi All,

DSCP can be set by setsockopt(IP_TOS) from application. But after going through sidecar/envoy, DSCP is not set in upstream path using DSCP in IP header from downstream. Of course even we can set it in Cluster using bindConfig but it is static configured instead of using DSCP value from downstream ip header.  

So is there any way envoy can carryforward the DSCP from downstream to upstream path?

Thanks,

**Comment by soulxu** [comment]
I don't think Envoy has such a feature built-in currently. But you could be able to do that by adding a listener filter, which populates the DSCP by `getsocketopt`, and add a socket option to the downstream Socket object. Then upstream will Inherit the socket option from the downstream socket.

https://github.com/envoyproxy/envoy/blob/c622d89efd58c7acf43f3b343bbbca39195e9104/source/common/upstream/cluster_manager_impl.cc#L1697

Envoy also can add a generic listener filter, the filter config can specify which socket option want to populate.

**Comment by ryanlyy** [comment]
Thanks a lot @soulxu , is there example how to adding a listener filter which populates the DSCP and add socket option to the downstream socket? is there envoy code change needed or is there only configurable?

The following is the generic listener filter with socket option:
listener:
- name: listener0
   drain_type: DEFAULT
   address:
       socket_address: { address: 0.0.0.0, port_value: 8080 }
   socket_options:
   - level: 0
      name: 1
      int_value: 20
      state: STATE_PREBIND

**Comment by soulxu** [comment]
You can follow the orignal dst filter how to get option from socket
https://github.com/envoyproxy/envoy/blob/68d7971c2fa86f18748e889d4ba343fcddbe0cd2/source/extensions/filters/listener/original_dst/original_dst.cc#L24

Then follow the original src filter how to add option in the socket
https://github.com/envoyproxy/envoy/blob/68d7971c2fa86f18748e889d4ba343fcddbe0cd2/source/extensions/filters/listener/original_src/original_src.cc#L31

Then you basically doing that two thing in one listener filter, then expect that get what you want.

**Comment by ryanlyy** [comment]
Thanks a lot  @soulxu, so core code is like the following:

Network::FilterStatus OriginalDscpFilter::onAccept(Network::ListenerFilterCallbacks& cb) {
  ENVOY_LOG(debug, "original_dscp: new connection accepted");
  Network::ConnectionSocket& socket = cb.socket();

  if (socket.addressType() == Network::Address::Type::Ip) {
    Network::Socket::OptionsSharedPtr original_sockopt = getOriginalSockopt(sock); // which call sock.getSocketOption(SOL_IP, IP_TOS, &dscp, &dscp_len)
	
	socket.addOptions(std::move(original_sockopt));
	
	return Network::FilterStatus::Continue;
}

**Comment by soulxu** [comment]
> Thanks a lot @soulxu, so core code is like the following:
> 
> Network::FilterStatus OriginalDscpFilter::onAccept(Network::ListenerFilterCallbacks& cb) { ENVOY_LOG(debug, "original_dst: new connection accepted"); Network::ConnectionSocket& socket = cb.socket();
> 
> if (socket.addressType() == Network::Address::Type::Ip) { Network::Socket::OptionsSharedPtr original_sockopt = getOriginalSockopt(sock); // sock.getSocketOption(SOL_IP, IP_TOS, &dscp, &dscp_len) socket.addOptions(std::move(original_sockopt)); }
> 
> return Network::FilterStatus::Continue; }

yea, you are right

**Comment by ryanlyy** [comment]
@soulxu is this function support or not now? thanks a lot

**Comment by soulxu** [comment]
@ryanlyy sorry, not yet, you can implement that simply as above suggestion.

cc @mattklein123 is it something that can be supported by upstream? maybe some generic listener filter populate socket option from downstream socket, the socket option populated are specified in the filter config.

**Comment by soulxu** [comment]
oh, I saw the enhancement label, it probably needs someone work on it.
