### ISSUE TITLE
tools: protoprint.py doesn't handle fully qualified names properly

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#23135]
While working on https://github.com/envoyproxy/envoy/pull/22921, I encountered an issue with the `proto_format` presubmit.  The presubmit check fails in https://github.com/envoyproxy/envoy/pull/22921/files#diff-3aec35493d987a047143be6535109226e876cedb1bb62858b099596b61d267a9 because the proto's fully-qualified name is `.envoy.extensions.config.v3alpha.KeyValueStoreXdsDelegateConfig`, while it contains a field of type `.envoy.config.common.key_value.v3.KeyValueStoreConfig`.  

The `protoprint.py` tool causes the presubmit check to fail because it says the FQN `.envoy.config.common.key_value.v3.KeyValueStoreConfig` should be changed to `config.common.key_value.v3.KeyValueStoreConfig`.  However, if I change it to `config.common.key_value.v3.KeyValueStoreConfig`, compilation fails because the `config` namespace is interpreted relative to the top-level context's namespace of `envoy.extensions.config`, and there is no such thing as `envoy.extensions.config.common.key_value.v3.KeyValueStoreConfig`.

I believe this is a bug in the `protoprint.py` tool, and the tool itself acknowledges that it's tricky to get the FQN normalization correct: https://github.com/envoyproxy/envoy/blob/main/tools/protoprint/protoprint.py#L360-L381.

One option is to fix this bug in the tool.  I'm not sure if there's a good rule we can add to the tool that fixes this issue and doesn't introduce new ones.

Another option is to just allow FQN names.  In chatting with @adisuissa , it seems such conflicts will arise more and more with more code going into `envoy.extensions` and `envoy.contrib`.

Another option is to allow a field to be ignored by the FQN normalizer with some annotation in the comments.

What do you all think?

**Comment by adisuissa** [comment]
I think that what we've seen in the PR falls under "... its root package has a name that collides with one of the packages of the context type", because there's a conflict between "envoy/config" and "envoy/contrib/config", and that might be a place where FQN may be allowed.

If "extensions" and "contrib" were kept in the namespace then FQN could be avoided, but as they are not, there should be a way to differentiate between the packages/types.

**Comment by abeyad** [comment]
> I think that what we've seen in the PR falls under "... its root package has a name that collides with one of the packages of the context type", because there's a conflict between "envoy/config" and "envoy/contrib/config", and that might be a place where FQN may be allowed.
> 
> If "extensions" and "contrib" were kept in the namespace then FQN could be avoided, but as they are not, there should be a way to differentiate between the packages/types.

I think in the case of the PR specifically, the tool seems to be doing the wrong thing.  I believe it's because the check
```
if list(remaining_field_fqn_splits)[:1] != type_context_splits[:1] and (
                len(remaining_field_fqn_splits) == 0
                or remaining_field_fqn_splits[0] in type_context_splits[1:]):
```

is not sufficient to catch cases where the relative namespace conflict starts in the middle of the package name, not in the first element of the package name.

**Comment by phlax** [comment]
> If "extensions" and "contrib" were kept in the namespace then FQN could be avoided, but as they are not, there should be a way to differentiate between the packages/types.

so iiuc the problem arises from the fact that protos in contrib and core are not separately namespaced

im trying to understand if there is an actual namespace clash - ie there are 2 protos trying to claim the same name - or whether this is just a bug in our machinery

**Comment by phlax** [comment]
cc @htuch

**Comment by abeyad** [comment]
> im trying to understand if there is an actual namespace clash - ie there are 2 protos trying to claim the same name - or whether this is just a bug in our machinery

There isn't an actual namespace clash.  There is only one one KeyValueStoreConfig proto in `.envoy.config.common.key_value.v3.KeyValueStoreConfig`.  The top-level context proto in which the KeyValueStoreConfig field declaration is found is in the extensions namespace: `.envoy.extensions.config.v3alpha.KeyValueStoreXdsDelegateConfig`.  The problem in compilation seems to occur if the field is just declared with `config.common.key_value.v3.KeyValueStoreConfig` instead of using the FQN, in which case the compiler resolves `config.common.key_value.v3.KeyValueStoreConfig` to `envoy.extensions.config.common.key_value.v3.KeyValueStoreConfig` which doesn't exist.  The compiler does not seem to attempt to try to resolve the proto type based on the outermost namespace field after that.  I believe in C++, the compiler would subsequently try to resolve the name based on the outermost scope, but it doesn't seem like the proto compiler does that.

Given the limitations in the compiler detecting the correct namespace resolution, I believe this is something we need to fix on the tools level.

**Comment by htuch** [comment]
A few things come to mind:
1. I'm not sure what the purpose of `envoy.extensions.config` is here. Is it `envoy.config` but for extensions? Can someone articulate the rhyme-and-reason for this subtree? This doesn't address the general problem, but I'd like to make sure we're deliberative when introducing new subtrees here.
2. I think the existing namespacing normalization has served us well so far, we will hit limits if the API scales significantly though. We can probably just add an annotation to allow FQDN override and use it in this case - this is simple and should probably work for some time, we can revisit if it's really becoming a pain. The other alternative is to just allow "whatever" or go full FQN everywhere. I think FQN everywhere gets pretty verbose and tiresome for the reader, and we should still be considering the use of .proto directly by developers as a useful use case for these artifacts.
3. This problem is going to have the same shape as C++ namespaces and their qualified references. In C++, we often have `using` declarations to allow local short names for the FQNs, which helps keep things readable. I don't think we have this in proto3.

I think for (2), I would definitely value alternative perspectives - I'm hesitant to think of the xDS protos as write-only artifacts, but maybe there are some other options?

**Comment by abeyad** [comment]
> 1. I'm not sure what the purpose of `envoy.extensions.config` is here. Is it `envoy.config` but for extensions? Can someone articulate the rhyme-and-reason for this subtree? This doesn't address the general problem, but I'd like to make sure we're deliberative when introducing new subtrees here (it's barely used today it seems).

It predates me so I'm not sure the reason.  I did want to follow the conventions of that subtree though, and since there were already numerous API protos in contrib with the `envoy.extensions.config` package, I wanted to follow the same and avoid having to create a different, inconsistent namespace.

> 2. I think the existing namespacing normalization has served us well so far, we will hit limits if the API scales significantly though. We can probably just add an annotation to allow FQDN override and use it in this case - this is simple and should probably work for some time, we can revisit if it's really becoming a pain. The other alternative is to just allow "whatever" or go full FQN everywhere. I think FQN everywhere gets pretty verbose and tiresome for the reader, and we should still be considering the use of .proto directly by developers as a useful use case for these artifacts.

I agree that the consistency is good.  I also definitely see the point of view about using FQN everywhere becoming too verbose to read.  I'm actually of the opposite opinion (probably minority opinion?) in that, whether it's C++ or proto, I prefer the FQN *unless* the symbol resides in the same namespace in which it is found, in which case you only need the name and no qualification.  I just find it easier to quickly think about exactly where I can find that symbol, instead of having to worry about relative namespaces.  But that's just me and I could well be in the minority on this opinion.

I think adding the ability to do an override in the comments that the tool respects makes sense.

**Comment by adisuissa** [comment]
> 1. I'm not sure what the purpose of `envoy.extensions.config` is here. Is it `envoy.config` but for extensions? Can someone articulate the rhyme-and-reason for this subtree? This doesn't address the general problem, but I'd like to make sure we're deliberative when introducing new subtrees here (it's barely used today it seems).

I added this sub-package for extensions that are related to config ingestion (when I added the custom config validators).
