### ISSUE TITLE
rtds: admin /runtime API returns incorrect runtime key

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#23142]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

Admin `/runtime` API returns incorrect runtime key for rtds resources.

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Envoy admin api `runtime` returns incorrect runtime key for the following rtds resource
```
&runtimev3.Runtime{
    Name: "rtds",
    Layer: &structpb.Struct{Fields: map[string]*structpb.Value{
	"circuit_breakers.local_service.default.max_connections": structpb.NewStringValue("1020"),
    }},
},
```
Actual
```
curl -q 0:9901/runtime  | grep -A20 "circuit_breakers.local_service.max_connections"
---
  "circuit_breakers.local_service.max_connections.string_value": {
   "layer_values": [
    "",
    "",
    "1020",
    "",
    "",
    ""
   ],
   "final_value": "1020"
  },
```
Expected
```
curl -q 0:9901/runtime  | grep -A20 "circuit_breakers.local_service.max_connections"
---
  "circuit_breakers.local_service.max_connections": {
   "layer_values": [
    "",
    "",
    "1020",
    "",
    "",
    ""
   ],
   "final_value": "1020"
  },
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by htuch** [comment]
I'm not sure if this is actually a bug yet - can you provide a plain text dump of the runtime endpoint? My suspicion is the Go code is setting the wrong key, probably using a protobuf string WKT rather than scalar string for value, but not sure.
