### ISSUE TITLE
How to make a static config as the client_max_body_size in Nginx

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23144]
I'm trying to replace my Nginx gateway with Envoy.

In my Nginx config, I had `client_max_body_size 500m;`, but I don't know what is the relative config in Envoy.

**Comment by KBaichoo** [comment]
There's currently no way to set this in Envoy apart from using the Buffer filter (and buffering 500mb seems like a bad idea).

Related issue: https://github.com/envoyproxy/envoy/issues/22724
