### ISSUE TITLE
Support hard-coded HTTP responses

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2315]
*Description*:

There are use cases where it is desirable for an HTTP proxy to return a configured HTTP response without proxying to an upstream server.

Some examples:
* If path == `/some_health_check_endpoint`, return a 200.
* If path == `/some_invalid_url_that_clients_are_requesting_nonstop`, return a 404 directly to shield the upstream from overload.

Proposed configuration model:
* Add a new action type, `DirectResponseAction`, that can be used in place of `RouteAction` and `RedirectAction`.
* Let the DirectResponseAction config specify the HTTP response status, an optional reason string, an optional content-type, and an optional response body.

**Comment by brian-pane** [comment]
I can contribute an implementation for this.

**Comment by dnoe** [comment]
@genioshelo might be interested in this.

**Comment by genioshelo** [comment]
Isn't this already possible to do with a filter? Just needs to set the ":status" header on the response.

**Comment by mattklein123** [comment]
It can definitely be done with a filter, but IMO this is a pretty useful core feature to have and I'm in favor of adding it natively to the router since it's relatively simple.

**Comment by mattklein123** [comment]
I think this is done. Closing. @brian-pane LMK if not the case.
