### ISSUE TITLE
Build broken for envoy 1.22.5

### ISSUE THREAD

**Issue by VivekSubr** [envoyproxy/envoy#23156]
*Title*: *Build broken for envoy 1.22.5*

*Description*:
Build failure for envoy 1.22.5, used for istio 1.14

*Repro steps*:
git clone git@github.com:envoyproxy/envoy.git
git checkout 2ba6db6633d24dbe4aa2c5cf8ebba9f84767e3f4
bazel --output_base bazel_out build -c opt envoy

Build fails with error,
source/common/config/watch_map.cc: In member function 'virtual void Envoy::Config::WatchMap::onConfigUpdate(const google::protobuf::RepeatedPtrField<envoy::service::discovery::v3::Resource>&, const google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char> >&, const string&)':
source/common/config/watch_map.cc:215:69: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  215 |       type_url_, reinterpret_cast<std::vector<DecodedResourcePtr>&>(decoded_resources),
      |                                                                     ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build

**Comment by adisuissa** [comment]
This looks similar to: #21060.
Do we need the fix in #21110 to be backported?
cc @keith

**Comment by VivekSubr** [comment]
thank you @adisuissa, that works.

**Comment by wrowe** [comment]
@adisuissa I don't see a backport of #21110 out there, as you authored it did you want to take this, or want to hand it off, before a new series of maintainence branch releases? Would this also need to land on 1.20.x / 1.21.x (still supported till Jan and April respectively) - or did the defect not exist yet?

**Comment by phlax** [comment]
i will backport #21110 if i can to the 1.22 branch as that is a known issue with a resolution

not sure if we want to also backport to 1.21 - im hoping to cut a release of this branch first so probably wont include it unless someone suggests its necessary

**Comment by phlax** [comment]
fixed #23951
