### ISSUE TITLE
Increasing access log on Windows

### ISSUE THREAD

**Issue by simha5009** [envoyproxy/envoy#23165]
Increasing access log on Windows

*Description*: On Windows, we have tried to use the envoyproxy with access_log enabled. Over time, I think there is no default way to rotate the logs for these access logs.

**Comment by adisuissa** [comment]
@wrowe are you aware of this limitation in Windows, and is there a way around it?

**Comment by simha5009** [comment]
Realted: https://github.com/envoyproxy/envoy/issues/23166
