### ISSUE TITLE
Event Tracing for Windows (ETW) support for Windows

### ISSUE THREAD

**Issue by simha5009** [envoyproxy/envoy#23166]
Event Tracing for Windows (ETW) support for Windows

*Description*: I see the logs which are being generated by either access_logs or containers are not compatible with windows ETW.

**Comment by adisuissa** [comment]
cc @wrowe should Envoy access log be compatible with Event Tracing for Windows?

**Comment by simha5009** [comment]
If we enable ETW, I think the access logs can also be generated as ETW events.
