### ISSUE TITLE
Is there a plan to implement async_mode for ext_proc?

### ISSUE THREAD

**Issue by acrazing** [envoyproxy/envoy#23190]
It seems to be `not implemented` since version 1.20, and it has not been implemented yet?

For some reason, I need to print the request and the response body (gzipped) in the access log. The only solution I've found so far is `ext_proc`, but its synchronous mode obviously brings longer response latency. So I wonder, when will its `async_mode` be supported?

**Comment by wbpcode** [comment]
cc @snowp

**Comment by acrazing** [comment]
Is there any updates? @wbpcode

**Comment by TAOXUY** [comment]
reopen

**Comment by shibin-aot** [comment]
any updates on this?
