### ISSUE TITLE
Error report when fetch "com_github_unicode_org_icu" in clang-tidy

### ISSUE THREAD

**Issue by dorisd0102** [envoyproxy/envoy#23191]
Hi,
Error report in clang_tidy:
_

> ERROR: An error occurred during the fetch of repository 'com_github_unicode_org_icu':
>    Traceback (most recent call last):
> 	File "/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
> 		download_info = ctx.download_and_extract(
> Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/unicode-org/icu/archive/release-71-1.tar.gz] to /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_unicode_org_icu/temp3423649212830806507/release-71-1.tar.gz: java.net.SocketTimeoutException: Read timed out
> ERROR: /source/WORKSPACE:13:19: fetching http_archive rule //external:com_github_unicode_org_icu: Traceback (most recent call last):

_

I try to get "https://codeload.github.com/unicode-org/icu/tar.gz/release-71-1.tar.gz%5D%20to%20/build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/com_github_unicode_org_icu/temp3423649212830806507/release-71-1", it report "404: Not Found".

Anyone could help to check this issue? Thanks.

**Comment by keith** [comment]
I think GitHub was having some issues today. The url from the error is working for me now.

**Comment by dorisd0102** [comment]
@keith 
The pipe still  failed:
https://dev.azure.com/cncf/envoy/_build/results?buildId=117201&view=logs&jobId=b7634614-24f3-5416-e791-4f3affaaed6c&j=b7634614-24f3-5416-e791-4f3affaaed6c&t=21e6aa7d-f369-5abd-5e4e-e888cac18e9c
