### ISSUE TITLE
perf: replace evbuffer

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#232]
evbuffer has a lot of extra functionality that we don't need. It also does suboptimal things during reading (calling ioctl, etc.) that are not well tuned for using a fast allocator like tcmalloc.

This is not something we will do short term but just opening this item to track.

**Comment by brian-pane** [comment]
I volunteer to work on this, because the `ioctl` in libevent is surprisingly time-consuming.

**Comment by mattklein123** [comment]
@brian-pane great, will assign this over to you. I would love to see this fixed also but have never had the time. A couple of thoughts as there are solutions that I think don't involve rewriting the entire buffer implementation if you are interested in a shortcut:
- We could try for a patch to libevent itself to have an option to not do the ioctl call. Not sure if they would accept it or not, though seems reasonable to me.
- We could just remove the read() and write() calls from Envoy's buffer interface. Then, we can allocate space directly using reservation, and just call readv()/writev() directly. This has the large added benefit of untangling the FD from the buffer implementation which is needed anyway from some of the FD abstraction work that is happening via the Cisco/VPP folks. 

So I guess in writing this I wonder if maybe it would be a better use of your time to just do my second suggestion above? (If you completely rewrite the buffer implementation I would ask for that to be done anyway).

**Comment by brian-pane** [comment]
+1 for removing the read and write calls from the buffer API. That will enable the buffer implementation and the I/O implementation to evolve separately.

**Comment by brian-pane** [comment]
I was able to remove the `ioctl` call, but it may be a while before I have time to work on a complete replacement of evbuffer. It may make sense to return this issue to "help wanted" state, in case anybody else has time to work on it.

**Comment by mattklein123** [comment]
TBH with the ioctol gone I'm not sure how much it matters anymore and maybe we should just close this. But I marked "help wanted" for now.

**Comment by mattklein123** [comment]
Going to go ahead and close this as I don't think it's a priority anymore. We can revisit if it comes up again.
