### ISSUE TITLE
HTTP Connection Manager Documentation is Missing Psuedo-Headers

### ISSUE THREAD

**Issue by vnayar** [envoyproxy/envoy#23206]
*Title*: *HTTP Connection Manager Documentation is Missing Psuedo-Headers*

*Description*:
The documentation for the HTTP Connection Manager is incomplete with regards to pseudo-headers. The `:scheme` header is documented, but the `:method` and `:path` headers are not.

See: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers

**Comment by adisuissa** [comment]
The `:authority` and `:path` are mentioned in the same doc, but could probably benefit from their own entry.
Contributions are welcome.

**Comment by vnayar** [comment]
> The `:authority` and `:path` are mentioned in the same doc, but could probably benefit from their own entry. Contributions are welcome.

A PR has been prepared here: https://github.com/envoyproxy/envoy/pull/23240
