### ISSUE TITLE
Configurable DSCP Values for HTTP/HTTPS/DNS interfaces

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#23224]
Configurable DSCP Values for HTTP/HTTPS/DNS interfaces

Please suggest, how can we provide Configurable DSCP Values for HTTP/HTTPS/DNS interfaces.
Please let me know from which envoy version this is supported and how can support. if possible please give me an example.

**Comment by adisuissa** [comment]
By DSCP I assume you meant Differential Services.

I'm not familiar with this, but I think one can set this with [SocketOption](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto.html).
https://github.com/istio/istio/issues/40397 mentions that this can be configured in Istio/Envoy, but I don't have the full details.

cc @mattklein123 might know more.

**Comment by soulxu** [comment]
yea, as @adisuissa said, SocketOption is used to set the DCSP flag. if you want to apply to downstream connection, then you can set this to listener address's socket_option. If you wan to apply to upstream connection, then you set this cluster endpoint's address socket option.

**Comment by Gaurav0411GitHub** [comment]
Hi,
Thanks for your support, If you can provide me an example of config dump, that would be helpful for me

**Comment by soulxu** [comment]
@Gaurav0411GitHub there is a similar question https://github.com/envoyproxy/envoy/issues/23200#issuecomment-1254464926, and there are similar config you can reference

**Comment by Gaurav0411GitHub** [comment]
Thanks for our support,
Please give me an sample code to set socket_options with value of istio.

**Comment by soulxu** [comment]
Sorry, I'm not familiar with Istio, you could ask that in the istio community.

**Comment by Gaurav0411GitHub** [comment]
ok no issues, I will ask the exact values from istio community
Could you please confirm me, Can we add socket_options in clusters also?
if yes please give me an example.

**Comment by soulxu** [comment]
You can set that at cluster's upstream_bind_config https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-bindconfig, there is socket_options field, which is same with the listener one.

**Comment by Gaurav0411GitHub** [comment]
ok Thanks
