### ISSUE TITLE
Host header(host:port) in http v1 is not received in the backend service through Envoy.

### ISSUE THREAD

**Issue by praveenchandna** [envoyproxy/envoy#23222]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Host header(host:port) in http v1 is not received in the backend service through Envoy.*

*Description*:
We are running traffic with the Envoy in http v1 and application uses the Host header parameter to extract the Port value. But when we are receiving the request through envoy we only receives the host in the backend POD and the Port value seems missing.

I am attaching the snoops screenshot captured at envoy and backend service.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
![Envoy](https://user-images.githubusercontent.com/87699923/191950988-278daf92-ebcf-46c9-b290-fddb48962f03.jpg)
![backend-service](https://user-images.githubusercontent.com/87699923/191950997-a9b8aaa2-6a13-43a1-be03-db8d1b1dd273.JPG)

**Comment by adisuissa** [comment]
Can you share your config?

**Comment by wbpcode** [comment]
If `strip_matching_host_port` or `strip_any_host_port` are set to `true` in your config?

**Comment by praveenchandna** [comment]
[envoy_config.zip](https://github.com/envoyproxy/envoy/files/9654596/envoy_config.zip)
Please finds the attached config file.
