### ISSUE TITLE
Opentelemetry grpc access logger uses wrong field for instrumentation_library_logs in 1.23.1

### ISSUE THREAD

**Issue by krdln** [envoyproxy/envoy#23234]
*Description*:

Opentelemetry grpc access logger sends out logs using [deprecated `instrumentation_library_logs = 1000` field][deprecated] instead of `scope_logs = 2` field (using opentelemetry proto v0.18).

>  Binary Protobuf senders SHOULD NOT set instrumentation_library_logs. Instead scope_logs SHOULD be set.

This was caused by https://github.com/open-telemetry/opentelemetry-proto/pull/362, which was supposed to not be a breaking change for binary-protobuf clients.

As an effect, opentelemetry access logger in envoy 1.23.1 is only compatible with [opentelemetry collector][collector] from 0.49.0 to 0.57.2 (which implement "instrumentation_library_logs grace period")

**This is a regression from envoy 1.22.3**, which uses opentelemetry proto v0.11, which uses correct field `instrumentation_library_logs = 2` and is compatible with both newer and older collectors.

Note: the issues is no longer present on main, as opentelemetry proto was updated to v0.19 in https://github.com/envoyproxy/envoy/pull/22694 and the correct `scope_logs = 2` is now sent out.

*Repro steps*:
See https://github.com/krdln/repro-envoy-1.23-vs-otel

*Admin and Stats Output*:
n/a

*Config*:
See repro repo

*Logs*:
See repro repo

[deprecated]: https://github.com/open-telemetry/opentelemetry-proto/blob/3c2915c01a9fb37abfc0415ec71247c4978386b0/opentelemetry/proto/logs/v1/logs.proto#L60-L63
[collector]: https://github.com/open-telemetry/opentelemetry-collector

**Comment by shashankram** [comment]
> As an effect, opentelemetry access logger in envoy 1.23.1 is only compatible with [opentelemetry collector](https://github.com/open-telemetry/opentelemetry-collector) from 0.49.0 to 0.57.2 (which implement "instrumentation_library_logs grace period")

I ran into this issue with Envoy v1.23.1 as well. Had to use otel-collector v0.57.2 to get this working. It did not work with the much older versions and also not with v0.61.0.

**Comment by krdln** [comment]
@shashankram This should be fixed in 1.23.2 – released yesterday.
