### ISSUE TITLE
tools/vscode/generate_debug_config.py Failed

### ISSUE THREAD

**Issue by guoyuanchao1202** [envoyproxy/envoy#23239]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Exec `tools/vscode/generate_debug_config.py //source/exe:envoy-static  --args "-c envoy-config.yaml" --debugger lldb` failed

*Description*:
>Describe the issue.
Local OS: Mac M1
I use vscode-remote container to debug envoy, but when i exec `tools/vscode/generate_debug_config.py`, it failed, the detail is: 

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/55007214/192128981-7453377b-f23c-40ee-9994-a60a2a7bca31.png">

could you please help me? thanks!
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daixiang0** [comment]
> do not contain a toolchain support for cpu aarch

I think it is the root cause.

/cc @lizan

**Comment by wbpcode** [comment]
related to #23238

**Comment by phlax** [comment]
>     do not contain a toolchain support for cpu aarch

rules_python provides the python toolchain i think https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl#L120

im a bit confused as to what exactly is failing

**Comment by keith** [comment]
the issue here is actually the cc toolchain, i think we need to define a aarch64 version over here to start https://github.com/envoyproxy/envoy-build-tools/blob/main/toolchains/configs/linux/clang/cc/BUILD

im not going to dig into this one anymore right now though

**Comment by bofeng96** [comment]
Hello. Is there any update?

**Comment by sunqingyong** [comment]
change the default cpu type `kvm64` to `max`.

**Comment by mathetake** [comment]
I believe this is already resolved just by removing the line 
```
build --config=rbe-toolchain-clang-libc++
```

in `~/.bazelrc` inside your devcontainer.

**Comment by zirain** [comment]
@mathetake should we remove `L8` from `.devcontainer/setup.sh`?

**Comment by mathetake** [comment]
sure i think that makes sense
