### ISSUE TITLE
Full 100 continue support

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#2325]
Alas we have some upcoming users of Envoy who want "proper" 100 continue support, where Upstream gets to decide how to handle the Expect; 100-continue header rather than having the proxy strip it.

This would likely be a configured option (off by default to preserve existing behavior) where the Expect-100-continue would be proxied upstream and Envoy could handle getting both sets of response headers.

**Comment by mattklein123** [comment]
Joy. :)

@alyssawilk per our previous conversation, my recommendation is to not expose 100-continue as the first of two decodeHeaders calls. I think this will turn into chaos. I would personally just add a new filter callback that most filters can ignore.

**Comment by alyssawilk** [comment]
+1, I (still) like that plan much better than handling multiple response headers everywhere.
