### ISSUE TITLE
How can I use envoy with consul for service discovery

### ISSUE THREAD

**Issue by pthakkar-tc** [envoyproxy/envoy#23254]
*Title*: Envoy with consul for service discovery

*Description*: 
I would like to know how I can make envoy work with consul. We use hashicorp products and services are exposed to consul service discovery. Please share if there is any example I can refer to. 

Thanks

**Comment by wbpcode** [comment]
To achieve this, it's necessary for xDS server to bridge the consul. This may be as a ref https://github.com/istio-ecosystem/consul-mcp
