### ISSUE TITLE
Remove `mprotect()/rwx`-related patch entry from `bazel/v8.patch`

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#23258]
A patch is introduced by https://github.com/envoyproxy/envoy/pull/23257 to fix  `MemoryAllocator::PartialFreeMemory()` on v8 `10.4.132.18` (https://github.com/envoyproxy/envoy/blob/ad800292a630c273fb548ac6d320522ffdbd2a8a/bazel/repository_locations.bzl#L1053). See https://github.com/envoyproxy/envoy/issues/23243 for more details. 

That patch is copied from https://chromium-review.googlesource.com/c/v8/v8/+/3700352. That commit on v8 upstream is included in `10.5` (can be checked from `10.5-lkgr`: https://chromium.googlesource.com/v8/v8.git/+/refs/heads/10.5-lkgr/src/heap/memory-allocator.cc#407) hence when we adopt 10.5 or higher, we should remove that patch (probably most of the patches will be removed/adapted anyway).

**Comment by dio** [comment]
Seems like we are aiming for 10.7: https://github.com/envoyproxy/envoy/pull/23257#pullrequestreview-1122924600

**Comment by dio** [comment]
@PiotrSikora I tried to upgrade v8, however, I stumbled upon: https://chromium-review.googlesource.com/c/v8/v8/+/3834031. Do you think we need to have this enabled by default too (hence reverting that commit) + adding a flag to enable `V8_USE_ZLIB`?

Note: zlib is enabled by default in 10.7-lkgr: https://github.com/v8/v8/blob/6c8b357a84847a479cd329478522feefc1c3195a/BUILD.gn#L373-L376.

**Comment by PiotrSikora** [comment]
@dio you can ignore it, snapshot compression was never enabled in the Bazel build anyway. Did you run into any issues because of that change?

**Comment by dio** [comment]
@PiotrSikora nope. I asked since previously we patched zlib header path. 

> Did you run into any issues because of that change?

No. Without zlib we're good. Thanks!

**Comment by dio** [comment]
Submitted https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/310 to have proxy-wasm-cpp-host to use newer V8, 10.7.193.13 (with some updated `--test_timeout`s).

**Comment by dio** [comment]
Seems like https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/310 is merged (the updated v8 version is v10.7.193.13). I can set up my own bucket at first to serve the required snapshot for submitting a PR (to upgrade the v8 version for Envoy), but then we need someone who has access to provide the snapshot on [https://storage.googleapis.com/envoyproxy-wee8/](https://storage.googleapis.com/envoyproxy-wee8 (ref: https://github.com/envoyproxy/envoy/blob/e5ec3dad31a0588227586750f77cae7d93c3cdf1/bazel/repository_locations.bzl#L1058) using https://storage.googleapis.com/envoyproxy-wee8/wee8-fetch-deps.sh.

cc. @envoyproxy/wasm-dev

**Comment by PiotrSikora** [comment]
@mpwarres should have access to generate and upload them.

**Comment by mpwarres** [comment]
> @mpwarres should have access to generate and upload them.

Ack, ran out of time to do this today, but will get to it tomorrow.

**Comment by mpwarres** [comment]
The following files have been added to the https://storage.googleapis.com/envoyproxy-wee8 bucket:

v8-10.7.193.13.tar.gz
v8-10.7.193.13-deps.sha256
chromium-base_trace_event_common-521ac34ebd795939c7e16b37d9d3ddb40e8ed556.tar.gz
chromium-icu-20f8ac695af59b6c830def7d4e95bfeb13dd7be5.tar.gz
chromium-zlib-f48cb14d487038d20c85680e29351e095a0fea8b.tar.gz

**Comment by dio** [comment]
Thanks, @mpwarres!
