### ISSUE TITLE
Envoy now rejecting header values with trailing whitespace

### ISSUE THREAD

**Issue by xjtian** [envoyproxy/envoy#23266]
*After upgrading nghttp2 to 1.49.0 (#23014), Envoy is now rejecting header values with trailing whitespace*

*Description*:

nghttp2 v1.49.0 rejects trailing whitespaces in header values to follow validation introduced in [RFC9113](https://datatracker.ietf.org/doc/html/rfc9113#section-8.2.1). This is newly introduced behavior which can break existing deployments of Envoy using HTTP2.

At Lyft, the impact of this change has been significantly increased HTTP2 connection churn (`upstream_cx_destroy_remote`) leading to widespread UC and 503's between our Envoy front proxy and Envoy service mesh sidecars.

*Repro steps*:

Deploy any version of Envoy that uses nghttp2 v1.49.0 and send requests with whitespace-padded header values. These requests should fail but will succeed if Envoy uses v1.48.0.

**Comment by mattklein123** [comment]
Thanks for debugging. Cross reference https://github.com/nghttp2/nghttp2/pull/1792

cc @alyssawilk @RyanTheOptimist @yanavlasov I think we need to default to the previous behavior?
