### ISSUE TITLE
gcp_authn: Cache hands out expired JWT tokens

### ISSUE THREAD

**Issue by fiadliel** [envoyproxy/envoy#23278]
*Description*:
Occasionally we see periods of time where all requests to a particular backend, authenticated using gcp_authn, are considered invalid. The period of time seems to be bursts of less than 60 seconds. On the backend, it reports a 401 error, the text including "The request was not authorized to invoke this service."

This kind of error is usually caused either by an invalid audience, or by an expired token. The bursts of time where this happens suggests that the issue is time-related.

After disabling the cache, the errors disappeared.

Looking at the code, there is a time check at https://github.com/envoyproxy/envoy/blob/6bba2d69a17e4cf374eb09f7f51fbf0f0ce4b7da/source/extensions/filters/http/gcp_authn/token_cache.h#L90 before taking a token from the cache. This check defers to https://github.com/google/jwt_verify_lib/blob/26c22c0ce1bc607eec8fa5dd26b707378adc7a88/src/jwt.cc#L157 which accounts for 60 seconds of clock skew.

I believe there is an issue with this check; it is a correct check for clock skew, as a JWT token consumer. But the cache is actually a producer of tokens, so following Postel's Law, the skew arithmetic (if any) needs to be the opposite direction. The skew value should be at least zero (clients may also account for clock skew), or a negative value.

An equivalent bug is probably present in the jwt_authn filter.

*Repro steps*:
Configure an upstream with the gcp_authn plugin. While I haven't got it running live right now, add an ID token to the cache through a request. 1h40s later (if the token has a 1h lifetime), attempt to use it again. The token should be accepted as valid from the cache, and used on the upstream request.

**Comment by tyxia** [comment]
@fiadliel Thank you very much for the reports and insightful analysis! 
I think it make sense and I will address this issue soon!

**Comment by tyxia** [comment]
@fiadliel Could you take a look at this PR #23366 ? (It seems that I cannot tag you there).
Thanks!

**Comment by tyxia** [comment]
PR https://github.com/envoyproxy/envoy/pull/23366 will address this issue.
We can close this issue as FIXED once that PR is merged.

**Comment by tyxia** [comment]
PR #23366 has been merged. @fiadliel, this issue can be closed as fixed now. Please let me know if you have any questions.
