### ISSUE TITLE
uhv: h2: web socket support

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#23286]
*Title*: uhv: h2: web socket support

*Description*:
The UHV component does not currently support web sockets, specifically the [extended `CONNECT` mechanism](https://www.rfc-editor.org/rfc/rfc8441). After implementing web socket support, the H2 unit and integration tests will need to be reviewed to see which ones can be enabled when using UHV.

**Comment by yanavlasov** [comment]
Fixed by #26526
