### ISSUE TITLE
uhv: unify Transfer-Encoding validation behavior

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#23289]
*Title*: uhv: unify Transfer-Encoding validation behavior

*Description*:
This issue is based on the discussion in the initial [UHV PR](https://github.com/envoyproxy/envoy/pull/22537#discussion_r969784837). Essentially, the way `Transfer-Encoding` is validated cannot be mirrored exactly within UHV because of how http-parser interacts with the H1 codec. The validation behavior should stay consistent when UHV is enabled.

**Comment by yanavlasov** [comment]
Fixed in #27378
