### ISSUE TITLE
Performance when ext_authz enabled with/without endpoint

### ISSUE THREAD

**Issue by Sachin-M-Desai** [envoyproxy/envoy#23284]
*Title*: Performance when ext_authz enabled  

*Description*:
>When ext_authz is enabled and endpoint is reachable we see that there is a performance drop. This is understandable as work is being done to send out requests.
However, when the ext_authz endpoint is down/unreachable, envoy performance shouldn't drop as much as in above case. 

Can envoy perform endpoint reach-ability status check so that performance isnt compromised? If endpoint isnt reachable after, say keepalives fail, ext_authz need not be tried.

Please do suggest any relevant configs in this regards.

TIA

**Comment by yanavlasov** [comment]
Do you have active health check enabled for the ext_authz service?

**Comment by Sachin-M-Desai** [comment]
Thanks for the pointer. With active health check enabled as below, the performance is still subdued.

  - name: ext_authz-http-service
    health_checks:
      - interval: 2s
        timeout: 2s
        unhealthy_threshold: 2
        healthy_threshold: 1
        http_health_check:
          path: "/health-check-authz"
     ....
    load_assignment:
      cluster_name: ext_authz-http-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            health_check_config:
              port_value: 9004
            address:
              socket_address:
                address: 172.17.0.1
                port_value: 9002


Some stats with active health monitoring enabled:
With ext_authz endpoint available we are able to hit traffic rate of 1000 APIs per sec. Envoy CPU peaks at 220%
With no ext_authz endpoint present and health status showing failed, envoy cannot process traffic beyond 400 APIs per sec (attempted 1000 APIs per sec). Interestingly envoy CPU too stays down around 80%

There definitely seems to be some throttling at work. The failure of authz seems to limit the complete throughput and not due to CPU.

**Comment by yanavlasov** [comment]
My guess is that with just a single endpoint health check is not helpful since Envoy will simply go into panic mode for this cluster: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/panic_threshold

In this case Envoy still sends requests to unhealthy service. I suspect these requests are timing out and this long delay is the reason why you see the ceiling in RPS.

I'm unsure what can be done in this case. Adding @snowp for any suggestions

**Comment by snowp** [comment]
By default the panic threshold would be hit, but the threshold is configurable so you should be able to disable it via https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-commonlbconfig

With that, if the endpoint is failing health checks Envoy should immediately respond with a 503

**Comment by Sachin-M-Desai** [comment]
Disabling the panic threshold works for throughput. I see reduced CPU usage after the endpoint has been declared to be unhealthy. 

Running some tests and will share results in this thread.

**Comment by Sachin-M-Desai** [comment]
Thanks a lot for the help. I ran some tests with various scenarios. Here are results, hope it will be of help. 

With ext_authz and access log server present (with and without active health check):

    @1000 RPS, Envoy CPU is around 200%

With ext_authz and access log server absent and NO active health check configured as below

    @1000 RPS, Envoy CPU is around 280%

With ext_authz and access log server absent and active health check configured as below

    @1000 RPS, Envoy CPU is around 170%

With no ext authz and access log config:

    @1000 RPS, Envoy CPU is around 170%

*RPS is API requests per second
