### ISSUE TITLE
Envoy performance degradation with recent releases

### ISSUE THREAD

**Issue by kihaloul** [envoyproxy/envoy#23283]
*Title*: *Envoy performance degradation with recent releases*

*Description*:
It appears that the CPU usage of envoy increases in recent versions. I have performed certain measurements which show that v1.23.1 requires ~20% more CPU to serve the same request rate, compared to v1.17.3.

![image](https://user-images.githubusercontent.com/9484101/192816182-ecbd988a-d6f4-4993-98d9-ef859057cb7e.png)

Measurement method:
I executed one envoy instance on one VM, and http2 clients and servers on another VM.
The envoy was executed with the docker imaged downloaded from dockerhub, e.g. envoyproxy/envoy:v1.17.3, envoyproxy/envoy:v1.23.1 etc.
Envoy was executed with command line arguments: "-c /etc/envoy/envoy.yaml --concurrency 4"
The configuration of envoy was the same in all versions, see attached envoy_net.txt:
[envoy_net.txt](https://github.com/envoyproxy/envoy/files/9666299/envoy_net.txt)

The VM running envoy is a centos 7 VM with 4 cores, kernel is:
`[root@dev ~]# uname -a `
`Linux dev.novalocal 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
The idle CPU usage of the VM running envoy was around 50%.

The clients and the servers were programmed by me, simple http2 clients and servers.
I used 2 servers and 10 clients. 

The CPU usage was recorded with "top -d 10". I used the maximum value from each top iteration.
For the graph I took 4 measurements for each envoy version. For each measurement noted the CPU usage from top and the achieved request rate recorded by the clients. Then I calculated how much CPU would be needed for 4000requests/sec and averaged. The 4000 was just used because it was a round number fairly closed to the measured request rate.

According to the graph, there appears to be a 20% performance degradation between v1.17.3 and v1.23.1.

Do you have any suggestions? Is this performance degradation known? Are there any specific features that seem suspicious to cause the performance degradation?

I will try to get a profile dump to compare between v1.17.3 and v1.23.1, maybe it will give more information.

**Comment by yanavlasov** [comment]
CPU profile comparison would help. We are not aware of any specific issues.

**Comment by kihaloul** [comment]
Hello,

I got two cpuprofiles, one from v1.17.3 and one from 1.23.1. The test parameters were the same as in the initial comment. However this time I built the debug version of envoy, with the command: 
`./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define tcmalloc=gperftools"  ./ci/do_ci.sh bazel.debug.server_only' `

The results can be seen in the following table:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chaloulo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chaloulo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Envoy image | Environment | CPU | Rate (req/s) | CPU for 4000 req/s | Deterioration compared to 1.17.3 | cpuprof filename
-- | -- | -- | -- | -- | -- | --
envoyproxy/envoy:v1.17.3 | dev, centos 7, fixed rate, cpuprof | 237,1 | 2120 | 447,3584906 | 0,00% | envoy_debug_v1.17.3_20221014155657.cpuprof
envoyproxy/envoy:v1.23.1 | dev, centos 7, fixed rate, cpuprof | 241,4 | 1907 | 506,3450446 | 13,19% | envoy_debug_v1.23.1_20221014160228.cpuprof



</body>

</html>
So a v1.23.1 had ~13% worse performance than v1.17.3.

The cpuprofiles for both tests are attached:

[envoy_debug_v1.17.3_20221014155657.cpuprof.zip](https://github.com/envoyproxy/envoy/files/9799687/envoy_debug_v1.17.3_20221014155657.cpuprof.zip)

[envoy_debug_v1.23.1_20221014160228.cpuprof.zip](https://github.com/envoyproxy/envoy/files/9799689/envoy_debug_v1.23.1_20221014160228.cpuprof.zip)

NOTE: I executed pprof to generate the text version of the profiles in the build container of each envoy version. The command I used was for v1.17.3 was:
`pprof -text envoy-static /tmp/dump/envoy_debug_v1.17.3_20221014155657.cpuprof`
and for v1.23.1:
`pprof -text envoy /tmp/dump/envoy_debug_v1.23.1_20221014160228.cpuprof`
For the v1.23.1 pprof execution I got  many errors like the following, I metioning this in case it is of any significance:
`/usr/bin/addr2line: Dwarf Error: Invalid or unhandled FORM value: 0x25.
/usr/bin/addr2line: Dwarf Error: found dwarf version '2049', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '1280', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '1536', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: Could not find abbrev number 106.`

Best regards,

Klearchos

**Comment by yanavlasov** [comment]
Thanks for the profiles. A couple of things to note. It is not very useful to profile debug builds, please profile and compare release builds. Please also generate SVG output for the profiles. It is very hard to interpret pprof text output.

**Comment by kihaloul** [comment]
Thanks!

I attach the SVGs from the debug builds profiling: 
envoy_debug_v1.17.3_20221014155657.cpuprof.svg:
![envoy_debug_v1 17 3_20221014155657 cpuprof](https://user-images.githubusercontent.com/9484101/199015926-2ec48091-c945-4325-bc0c-88ba90aac4ef.svg)

envoy_debug_v1.23.1_20221014160228.cpuprof.svg:
![envoy_debug_v1 23 1_20221014160228 cpuprof](https://user-images.githubusercontent.com/9484101/199015986-714d1048-9763-47fd-b8ce-f711fe7ff5b8.svg)


I will also get new profiles with the release builds.

Best regards,

Klearchos

**Comment by kihaloul** [comment]
Hello,

I got two cpuprofiles with a release build, one from v1.17.3 and one from 1.23.1. The test parameters were the same as in the initial comment. However this time I built the debug version of envoy, with the command:
./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define tcmalloc=gperftools" ./ci/do_ci.sh bazel.release.server_only' 

The results of the test were:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chaloulo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chaloulo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Config | Envoy image | Environment | CPU | Rate (req/s) | CPU for 4000 req/s | Deterioration compared to 1.17.3
-- | -- | -- | -- | -- | -- | --
no lua | envoyproxy/envoy:v1.17.3 | dev, centos 7, fixed rate, cpuprof | 80,8 | 4334 | 74,57314259 | 0,00%
no lua | envoyproxy/envoy:v1.23.1 | dev, centos 7, fixed rate, cpuprof | 91,6 | 4429 | 82,72747799 | 10,93%



</body>

</html>

I attach the profiles, the zip files contain both the cpuprof, the text and the svg files:
[envoy_release_v1.17.3_20221104085631.zip](https://github.com/envoyproxy/envoy/files/9937756/envoy_release_v1.17.3_20221104085631.zip)

[envoy_release_v1.23.1_20221104090720.zip](https://github.com/envoyproxy/envoy/files/9937759/envoy_release_v1.23.1_20221104090720.zip)

Best regards,

Klearchos
