### ISSUE TITLE
Missing distinct oauth filter logging option

### ISSUE THREAD

**Issue by DanApostol** [envoyproxy/envoy#23306]
Cannot configure logging level for Oauth filter

When starting the envoy using --component-log-level option, you cannot set a distinct value for oauth filter.

Two fixes needed:

- add oauth value in Enum in logger.h in the list
#define ALL_LOGGER_IDS(FUNCTION)

- configure new value (oauth instead upstream) in oauth_client.h in the line:
class OAuth2ClientImpl : public OAuth2Client, Logger::Loggable<Logger::Id::upstream> {

Sources were inspected on main branch.

Thank you in advance.
Dan.

**Comment by StarryVae** [comment]
So, is it resonable to fix this, and is any one working on it? if no, i will try to fix.

**Comment by kanurag94** [comment]
I think this is done, should we close this issue? @StarryVae @DanApostol

**Comment by StarryVae** [comment]
yeah, i think we can close it.

**Comment by DanApostol** [comment]
Ok, closed.
