### ISSUE TITLE
how to decode grpc in envoy wasm

### ISSUE THREAD

**Issue by INT2ECALL** [envoyproxy/envoy#23303]
hello,i am using envoy wasm to get grpc stream ,but grpc is using protobuf ,not plain text ,can i decode it using envoy plugin

**Comment by yanavlasov** [comment]
@PiotrSikora for any suggestions

You may also try asking in envoy-dev@googlegroups.com or envoy-dev slack channel.

**Comment by INT2ECALL** [comment]
@yanavlasov @timperrett @pjjw @mkbehr help

**Comment by wbpcode** [comment]
complete proto is necessary. You can read the code of `grpc_json_transcoder` filter which do the translation between grpc and json and could be a ref.

**Comment by INT2ECALL** [comment]
> complete proto is necessary. You can read the code of `grpc_json_transcoder` filter which do the translation between grpc and json and could be a ref.

thank for reply,but i want to decode raw grpc ,i do not have any proto file,this like protoc decode_raw < text.bin

decode data like blow:

1:hello world
2.test

**Comment by wbpcode** [comment]
Then maybe you can write a wasm extension that implement similar feature of `protoc`. Or you can just log all the data to offline files and decode it with `protoc`.

**Comment by INT2ECALL** [comment]
> Then maybe you can write a wasm extension that implement similar feature of `protoc`. Or you can just log all the data to offline files and decode it with `protoc`.

thank
