### ISSUE TITLE
Macros to condition code on log level

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2330]
It would be helpful to have some macros to condition code execution on log level. E.g. code that generates input variable `foo` to an `ENVOY_LOG(debug, "{}", foo)` should not need to execute if we're not at a log level that will emit the log message.

There isn't a huge need for this today, but it's a simple warmup exercise for new Envoy contributors.

@mrice32

**Comment by cpakulski** [comment]
I will try to implement such macros. I am new to this project, so it will be good exercise.

**Comment by mattklein123** [comment]
This is done.
