### ISSUE TITLE
uhv: valdidate IPv6 literals

### ISSUE THREAD

**Issue by ameily** [envoyproxy/envoy#23314]
*Title*: uhv: validate IPv6 literals

*Description*:
The UHV component currently detects IPv6 addresses and verifies that they only contain valid characters (hex and colon characters), but does not validate the actual syntax. Update UHV to validate IPv6 addresses completely. This is related to #22859, but specific to UHV.

**Comment by LithiumSR** [comment]
Hello @ameily and @yanavlasov 
Can this issue be reopened as it still applies?

Thank you

**Comment by kfaseela** [comment]
cc @ameypd
