### ISSUE TITLE
split out HeaderString for common usage

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#23327]
*Title*: *split out HeaderString for common usage*

*Description*:

The HeaderString is heavily optimized for performance and unified the string reference and owned string.
It would be great to split it out from http for common usage.

**Comment by yanavlasov** [comment]
Please provide more details on how you'd like to split it.

**Comment by wbpcode** [comment]
Now, the `HeaderString` is part of `Http::HeaderMap` (and in the http code tree), I think we could just move it to the `envoy/common` for common usage.

**Comment by wbpcode** [comment]
It's pretty simple update, and I can create a minor PR to achieve it.
The community can decide to accept it or not after a very quick review.

**Comment by wbpcode** [comment]
#23341
