### ISSUE TITLE
Build failed on MacOS 13 with Xcode 14.1

### ISSUE THREAD

**Issue by Zheaoli** [envoyproxy/envoy#23359]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

Build failed on MacOS 13 with Xcode 14.1

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

```text
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/v8/src/base/platform/platform-darwin.cc:56:22: error: 'getsectdatafromheader_64' is deprecated: first deprecated in macOS 13.0 [-Werror,-Wdeprecated-declarations]
    char* code_ptr = getsectdatafromheader_64(
                     ^~~~~~~~~~~~~~~~~~~~~~~~
                     use getsectiondata()
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/mach-o/getsect.h:130:14: note: 'getsectdatafromheader_64' has been explicitly marked deprecated here
extern char *getsectdatafromheader_64(
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by ggreenway** [comment]
@envoyproxy/wasm-dev will there be an upstream V8 change we can pull in to fix this?

**Comment by mathetake** [comment]
actually @dio is working on upgrading and fixing macos issue on wasm/v8 https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/310

**Comment by dio** [comment]
Seems like that deprecation is very new :). Probably adding `-Wno-deprecated-declarations` in your `user.bazelrc` could help for now. Since that code is still on v8 main branch: https://github.com/v8/v8/blob/85e384960c27406aac93d88bcffcbe80a1020e9a/src/base/platform/platform-darwin.cc#L56.

```
build:macos --copt='-Wno-error=deprecated-declarations'
```
