### ISSUE TITLE
`//test/integration:multiplexed_integration_test` is flakey in CI (~timeout)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#23375]
Its not immediately clear why/what changed but here is an example of this test timing out/failing:

https://dev.azure.com/cncf/envoy/_build/results?buildId=117975&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=22464

and this seems to be the error:

```console
[  FAILED  ] IpVersionsClientType/TcpProxyOdcdsIntegrationTest.RepeatedRequest/0, where GetParam() = (4-byte object <00-00 00-00>, 4-byte object <00-00 00-00>)
[  FAILED  ] IpVersionsClientType/TcpProxyOdcdsIntegrationTest.RepeatedRequest/1, where GetParam() = (4-byte object <00-00 00-00>, 4-byte object <01-00 00-00>)

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=117975&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=20156

**Comment by ggreenway** [comment]
Related: #23370
