### ISSUE TITLE
httpCall() proxy options support

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#23407]
*Title*: *httpCall() proxy options support*

*Description*:
I want to generate a new request via HTTP proxy to the `https` site. In this case, envoy should send a request with the `CONNECT` method after the TLS channel is established then an HTTP request should be sent.
Now I want to use the form
```
-- Alternative function signature.
local headers, body = handle:httpCall(cluster, headers, body, options)
```
And specify `proxy` in the `options` array-like
```
-- Create a fire-and-forget HTTP call.
local request_options = {["proxy"] = "https://exmple.com:3129/"}
```
Could you implement "proxy" options of httpCall().

**Comment by sergey-safarov** [comment]
Looks like [Http11ProxyUpstreamTransport](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/http_11_proxy/v3/upstream_http_11_connect.proto#extension-envoy-transport-sockets-http-11-proxy) maybe used to relay request via HTTP proxy.
I will try to prepare the envoy config.

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk who has been doing CONNECT work lately

**Comment by alyssawilk** [comment]
as a heads up that transport must (currently) work in conjunction with an HTTP filter which puts metadata in the stream info.  See test/integration/filters/header_to_proxy_filter.cc for a test only filter example of this.  I think it would be lovely to upstream an envoy non-test filter which did this, but the only use case I had was Envoy Mobile.

**Comment by sergey-safarov** [comment]
I am not a Go developer and do not understand how to use his info.
Maybe you have the YAML config file?

**Comment by sergey-safarov** [comment]
I go to relay the request to the upstream envoy forwarding proxy.
For `https` links I will a script for casting HTTP requests between envoys servers.
