### ISSUE TITLE
Cluster: hosts only using last configured host in v2 API

### ISSUE THREAD

**Issue by mstrcd** [envoyproxy/envoy#2340]
I am trying to configure multiple static cluster hosts using v2 api on v1.5.0. 
>   clusters:
>   - name: mock_cluster
>     type: STATIC
>     connect_timeout: 0.25s
>     lb_policy: ROUND_ROBIN
>     hosts:
>     - socket_address: {address: "172.16.42.3", port_value: 8371}
>       socket_address: {address: "172.16.42.5", port_value: 8371}

So far all my testing has shown envoy will only use whichever host is defined last in the list and ignore all others.
I'm not sure if I'm just using the wrong syntax, this is by design (seems unlikely) or there is a bug.

> $  curl http://localhost:9990/clusters
> version_info::static
> mock_cluster::default_priority::max_connections::1024
> mock_cluster::default_priority::max_pending_requests::1024
> mock_cluster::default_priority::max_requests::1024
> mock_cluster::default_priority::max_retries::3
> mock_cluster::high_priority::max_connections::1024
> mock_cluster::high_priority::max_pending_requests::1024
> mock_cluster::high_priority::max_requests::1024
> mock_cluster::high_priority::max_retries::3
> mock_cluster::added_via_api::false
> mock_cluster::172.16.42.5:8371::cx_active::0
> mock_cluster::172.16.42.5:8371::cx_connect_fail::0
> mock_cluster::172.16.42.5:8371::cx_total::0
> mock_cluster::172.16.42.5:8371::rq_active::0
> mock_cluster::172.16.42.5:8371::rq_error::0
> mock_cluster::172.16.42.5:8371::rq_success::0
> mock_cluster::172.16.42.5:8371::rq_timeout::0
> mock_cluster::172.16.42.5:8371::rq_total::0
> mock_cluster::172.16.42.5:8371::health_flags::healthy
> mock_cluster::172.16.42.5:8371::weight::1
> mock_cluster::172.16.42.5:8371::region::
> mock_cluster::172.16.42.5:8371::zone::
> mock_cluster::172.16.42.5:8371::sub_zone::
> mock_cluster::172.16.42.5:8371::canary::false
> mock_cluster::172.16.42.5:8371::success_rate::-1

> $   curl http://localhost:9990/stats
> ...
> cluster.mock_cluster.membership_change: 1
> cluster.mock_cluster.membership_healthy: 1
> cluster.mock_cluster.membership_total: 1
> ...

**Comment by mattklein123** [comment]
Something is broken either in the config or in Envoy. Can you supply the full config in a way that is not rich text formatted?

**Comment by mstrcd** [comment]
I will also note. I am using the envoyproxy/envoy-alpine:v1.5.0 docker image. And using this command to start it:

> /usr/local/bin/envoy -c /config/current/envoy.yaml --v2-config-only --mode serve --base-id 256 --restart-epoch 0

Running with "--mode validate", returns that the config is ok.

[envoy.txt](https://github.com/envoyproxy/envoy/files/1620296/envoy.txt)

**Comment by mattklein123** [comment]
I think it needs to be:
```
hosts: 
    - socket_address: {address: "172.16.42.3", port_value: 8371}
    - socket_address: {address: "172.16.42.5", port_value: 8371}
```

Yay YAML

**Comment by mstrcd** [comment]
Yup, that fixed it. Yay, YAML in deed. Thanks.
