### ISSUE TITLE
How to redirect tcp pocket to envoy

### ISSUE THREAD

**Issue by He-Jingkai** [envoyproxy/envoy#23414]
I deployed envoy **in a container**, and then I added the iptables rules(using **DNAT**) to the host. However, I found that envoy could not find the original address of the tcp packet correctly.

My purpose is to make envoy(PROXY_IP=10.32.0.8) proxy all traffic to the client(CLIENT_IP).

The rule I add to host is:
```shell
# PROXY_IP=10.32.0.8
iptables -t nat -N REDIRECT
iptables -t nat -A REDIRECT -p tcp -j DNAT --to-destination $PROXY_IP:15006

iptables -t nat -N INBOUND_PREROUTING
iptables -t nat -A INBOUND_PREROUTING -p tcp -s $PROXY_IP -j RETURN
iptables -t nat -A INBOUND_PREROUTING -p tcp -j REDIRECT

iptables -t nat -N INBOUND_OUTPUT
iptables -t nat -A INBOUND_OUTPUT -p tcp -s $PROXY_IP -j RETURN
iptables -t nat -A INBOUND_OUTPUT -p tcp -j REDIRECT

iptables -t nat -A OUTPUT -p tcp -d $CLIENT_IP -j INBOUND_OUTPUT
iptables -t nat -A PREROUTING -p tcp -d $CLIENT_IP -j INBOUND_PREROUTING
```

Then, I send a HTTP request to client.

The log of envoy is:
```
2022-10-09T02:51:16.800302Z     debug   envoy filter    original_dst: new connection accepted
2022-10-09T02:51:16.800332Z     trace   envoy filter    original_dst: set destination to 10.32.0.8:15006
```
This means envoy didn't get correct original dst(what it got is the dst after redirect)

My question is **how should I set the redirect rules so that envoy can get the correct original dst**.

**Comment by RyanTheOptimist** [comment]
cc: @phlax do you have any insight here?

**Comment by He-Jingkai** [comment]
This is because envoy uses the `getsockopt(…, SO_ORIGINAL_DST, …)` syscall when obtaining the original dst. This syscall uses the records in the kernel to obtain the original dst before being modified by nat.
This requires that the location where nat is used to forward network packets and the location where envoy runs must be the same linux kernel or container (that is, linux namespace).

**Comment by He-Jingkai** [comment]
I solved this problem using policy routing, by modifying the routing table. This means that network packets are routed to the container where envoy is located, and then nat is used in the container where envoy is located.
I wonder if there is a better solution

**Comment by phlax** [comment]
> do you have any insight here?

no immediate insight im afraid - half following the problem/solution
