### ISSUE TITLE
routing: Adding additional matching conditions and actions. 

### ISSUE THREAD

**Issue by bmadhavan** [envoyproxy/envoy#2342]
**Title:** 
Add `source cidr` along with existing`path` or `prefix` or `regex` as matching parameters.  
Also add `DROP` and `RESET` as a new route action.  

**Description:**
1) There are use cases where we would want to allow/deny only certain users ( i.e. certain source CIDR ) from accessing certain high priority services ( i.e. certain paths ). 
Example:          

        - path: \internal\svc && source-cidr-permitted: 10.5.0.0/16 
    
           then take any action.   

2) Also we would want to DROP or RESET based on path or prefix or Internal-header matches. 
 Examples:

       -  If User-Agent: “xxyyzz” 
       -  If “Referer” header:  “www.zzyy.com” 
       -  path: \private\repo 
       -  path: \internal\svc && source ip != 10.5.0.0/16

**Proposed configuration model:**

- Add a new configuration under routes along with other match conditions with a new field `source-cidr-permitted` and `source-cidr-denied` which when specified will need to satisfied in addition to path/prefix/regex match. This will be an optional field. 

- Add a new configuration under routes with `drop` and `reset` along with current actions like cluster or redirect.  This will be an optional field.

```
 Route config:
  {
        "prefix": "...",
        "path": "...",
        "regex": "…",
        "source-cidr-permitted": [],  ----  New
        "source-cidr-denied": [],     ----  New
        "cluster": "...",
        "cluster_header": "...",
        "weighted_clusters" : "{...}",
        "drop": "...", (boolean)             ----- New
        "reset": "...",  (boolean)           ----- New
        "host_redirect": "...",
        "path_redirect": "...",
        "prefix_rewrite": "...",
        "host_rewrite": "...",
         …...
         ...
 }
```
@khgandhi 

PS: I can work on this based on what we decide.

**Comment by mattklein123** [comment]
@bmadhavan please see https://github.com/envoyproxy/data-plane-api/blob/master/api/auth.proto. My desire is to do all of this functionality in a new auth filter that we will be creating at Lyft this quarter. Can you take a look at that proto and propose changes there? cc @danielhochman @rodaine

**Comment by mattklein123** [comment]
Also, we have no plans to port this work back to v1 config, so if it's possible for you to move to v2 config to consume that would be good.

**Comment by bmadhavan** [comment]
Thanks @mattklein123 Sure. I will look into the auth filter and add my proposal. 
Also, I just used v1 here but will be moving to v2 & hence I am fine with having support only in v2.

**Comment by brian-pane** [comment]
@mattklein123 are you also planning to support non-auth-related CIDR matching by setting a tag that can be used as a matching criterion in any route entry?

My non-auth-related prefix matching use cases are things like this:
```
if source IP matches any of a list of internal corporate network prefixes {
  send the request to the staging cluster
} else {
  send the request to the production cluster
}
```

**Comment by bmadhavan** [comment]
@brian-pane Actually, we do have the same requirement, but will DROP it in the else case.

**Comment by mattklein123** [comment]
@brian-pane our plan on how to do this was to have the IP tagging filter end up setting a header such as `x-envoy-ip-tags` and then do header match routing in the router. We can also consider adding first class tag support to streams (potentially in metadata) if that is interesting. cc @ccaraman

**Comment by brian-pane** [comment]
Thanks, putting the tag in a custom header sounds good to me, as long as the implementation scrubs that header from incoming requests to guard against malicious clients.

**Comment by hennna** [comment]
Does this issue include implementation of source_prefix_ranges in https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/listener/listener.proto#L78?

**Comment by hennna** [comment]
@ccaraman

**Comment by mattklein123** [comment]
@hennna yes, that is what is happening. We might need to clear the route cache in the IP tagging filter if people are going to route on this header. Probably needs a bit of thinking. Unclear if we should do this in all cases. Can discuss.

**Comment by rgs1** [comment]
@hennna @mattklein123 confirmed that configuring IpTaggingFilter and using route.HeaderMatcher to match on `x-envoy-ip-tags` isn't working. In my test case I am using an upstream cluster with the match, not a direct response (fwiw, possibly doesn't make a difference).

I'll dig into it a bit more.

**Comment by rgs1** [comment]
testing out: https://github.com/envoyproxy/envoy/pull/3216
