### ISSUE TITLE
Can we configure multiple socket address for dual stack support at listener side in envoy

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#23429]
*Title*: *Can we configure multiple socket address for dual stack support at listener side in envoy*

*Description*:
At listeners side in envoy we want to give support of dual stack so we are able to configure only ipv4 address like this
"name": "AA_NONSEC_LISTENER_0",
     "active_state": {
      "version_info": "V1",
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "AA_NONSEC_LISTENER_0",
       "address": {
        "socket_address": {
         "address": "X.X.X.X",
         "port_value": 4568,
         "ipv4_compat": true
        }
       },

How can we configure both ipv4 and ipv6 address in listener configuration? Please give me an example also for this.

**Comment by soulxu** [comment]
You can reference the `additional_addresses` field in listener https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#config-listener-v3-listener, it is available on main branch, it will be part of 1.24 release and that will be release very soon.
