### ISSUE TITLE
Support HTTP redirect with dynamic values from the original request. 

### ISSUE THREAD

**Issue by bmadhavan** [envoyproxy/envoy#2343]
*Title*: *Support HTTP redirect with dynamic values from the original request.*

*Description*:
There are use cases where we would want to do a HTTP redirect based on a prefix match but the redirect message would be dynamically determined based on the request message. i.e. change a certain portion of the path but retain the remaining part of path and query string intact. 

An example: 
For a REQ,   www.xyz.com/svc/cat/attr?sound=meow&color=brown
and if `prefix`: /svc/cat  
then   `redirect`:  www.xyz.com/feline/attr?sound=meow&color=brown

The config can look like,
```
"route_config": {
    "virtual_hosts": [
    {
      "name": "125",
      "domains": [
        "www.xyz.com"
      ],
      "routes": [
      {
          "prefix": "/svc/cat",
          "path_redirect": "/feline/%URI_AFTER_PREFIX%"
      }]
    }]
}   
```

@khgandhi

**Comment by mattklein123** [comment]
@bmadhavan sounds reasonable to me. cc @brian-pane who has been also interested in similar features lately. Can you open the data-plane-api PR and we can discuss API design there? Thank you.

**Comment by bmadhavan** [comment]
@mattklein123 I don’t see any new data plane API change needed as `path_redirect` will continue to be a string and no new fields need to be added. The change will mostly be in the envoyproxy repo where we need to parse for the pre-defined substring `%URI_AFTER_STR("cat")%` to create the new redirect msg. Can you give me some pointers if the data-plane-api PR is still needed? If so with what?  Thanks.  
 
 ```
 "redirect": {
        "path_redirect": "/feline/%URI_AFTER_STR("cat")%/some_trailer"
   } 
```

**Comment by mattklein123** [comment]
@bmadhavan I don't think the data-plane-api PR is explicitly needed, however there are complexities around if we do this by default given escaping. E.g., using `%%` to indicate a `%`, etc. @zuercher has been working on stuff like this recently so I will defer to him for comment.

**Comment by bmadhavan** [comment]
Thanks @mattklein123. I did look into @zuercher 's docs PR for envoyproxy/data-plane-api#424 . I will wait here for his comments or create a PR in data-plane-api with docs change for `path_redirect`.

**Comment by zuercher** [comment]
I think it's ok to use %. It'll probably make someone's life rough if they want to put CGI-escape values in their URLs, but they kind of get what they deserve.

Do you need arguments for the the % expressions? The original example didn't have one, but the second version did. I'd prefer the former, since the arguments are a bit of a pain.

**Comment by bmadhavan** [comment]
@zuercher I initially thought having arguments might be cleaner. But as you say arguments are a pain to parse. So, I will go with `/some/prefix/%cat%/some/suffix`. If someone wants to have % they can add a escape like %%. I will raise a docs PR in data-plane-api shortly. Thanks.

**Comment by mnpenner** [comment]
What's the status of this? Can we do dynamic redirects now or no?

I'm trying to redirect users back to where they were before being forced to log in.
