### ISSUE TITLE
AWS Lambda Filter: Behavior with upstream headers

### ISSUE THREAD

**Issue by sdlevi27** [envoyproxy/envoy#23459]
*Title*: *How should the AWS Lambda filter handle upstream headers to the Lambda API*

*Description*:
We have the Lambda filter configured with "payload_passthrough" set to "false".  Per the docs, and the actual code, "then the HTTP request is transformed to a JSON payload with the following schema...".  Part of the request body schema includes the downstream headers.  We see these headers are being correctly passed to the upstream Lambda API as part of the request body, so that part of the filter is working as advertised.

The question is - should Envoy be sending the original downstream request headers to the Lambda API?   We can see that Envoy is forwarding those headers from the trace log.  For example, we're hitting Envoy with a request header of "myheader=foo":

`
[2022-10-12 10:36:22.508][70][debug][router] [source/common/router/router.cc:675] [C3][S4256698969371659058] router decoding headers:
':authority', 'localhost'
':path', '/2015-03-31/functions/arn:aws:lambda:us-east-1:XXXXXXXXXXX:function:myfunction-KgMxYjFU2T52/invocations'
':method', 'POST'
':scheme', 'https'
'myheader', 'foo'
'content-type', 'application/json'
'user-agent', 'PostmanRuntime/7.29.2'
`

A concrete example of this is when a downstream client sends an Authorization header to Envoy.  The Lambda filter is appending the header value to the AWS SigV4 request when invoking the Lambda function, which generates an HTTP 403 error from the Lambda API.  We believe this is due to the Lambda API rejecting the request due to the content of the Authorization header not explicitly matching the SigV4 spec.

If the Lambda filter were to remove the Authorization header from the upstream request, and only inject it in the request body, we believe that would solve the SigV4 error.

**Comment by wbpcode** [comment]
cc @mattklein123

**Comment by suniltheta** [comment]
So if I understood correctly, we would like to have an option to exclude some headers to be included when Lambda extension makes API call towards AWS Lambda?

If this is the case then there was an API added `match_excluded_headers` to [AwsRequestSigning proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/aws_request_signing/v3/aws_request_signing.proto#envoy-v3-api-field-extensions-filters-http-aws-request-signing-v3-awsrequestsigning-match-excluded-headers) an year ago. At that time the support was [marked as TODO](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/aws_lambda/config.cc#L53) for AWS Lambda.

Let us know if this would solve the problem for you if implemented.
