### ISSUE TITLE
downstream peer certificate details in network WASM filter

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#23468]
Is it possible to get downstream peer cert details like SAN etc. in network WASM filter? I have looked at the proxy API https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/proxy_wasm_api.h - could not find any thing.

If it is not available currently, Is it acceptable to add it?

We have a use case to build some logic in  network WASM filter based on client identity.

**Comment by kyessenov** [comment]
You can use `get_property({"connection", "subject_local_certificate"})` and [etc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes) in network Wasm filter context.

**Comment by ramaraochavali** [comment]
Cool. Thank you @kyessenov .
