### ISSUE TITLE
Exposong session stats via admin port.

### ISSUE THREAD

**Issue by Hubert97** [envoyproxy/envoy#23477]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Thoughts and suggestions on new feature that would expose detailed list all TCP/UDP sessions.

*Description*:
I'm writing on behalf of a large company. We have a need to list all TCP/UDP session for debug and observability purposes. The idea would be similar to [Issue #2169](https://github.com/envoyproxy/envoy/issues/21690). The feature would be disabled by default as to not impede work of large clusters.
In stats we want to have :
- rx/tx packets
- dropped packets
- associated backends 
and similar.

The reason we want to consult is that we want to contribute our changes to mainstream in the future and wanted to see how community feels about this kind of feature. How should such feature be enabled etc.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Seems these stats should be provided by the OS or external network monitor.

**Comment by wbpcode** [comment]
cc @jmarantz
