### ISSUE TITLE
Question about release: 1.22.3 2aca584: envoy/VERSION.txt => 1.22.3-dev

### ISSUE THREAD

**Issue by newwuhan5** [envoyproxy/envoy#23487]
We use git submodule like this: git submodule status
2aca584b3bca81622d3b009612f0c7be93eeea34 envoy (v1.22.3)

But envoy/VERSION.txt contains:
1.22.3-dev

Thus, the RELEASE full string looks like this:
"version": "b87295fae172bc56584b65fdb05a05c31acd2ffa/1.22.3-dev/Clean/RELEASE/BoringSSL",

"xxx-dev" can be an issue for us if running in the PRODUCTION even though it's official release.  Anyway to overwrite this version txt?

We do have c++ filters internal to us, requests us to a full envoy build.

**Comment by phlax** [comment]
this was a mistake - release 1.22.5 should have the correct versioning

**Comment by newwuhan5** [comment]
We will upgrade to use 1.22.25 then.  Thank you @phlax  for your quick response!
