### ISSUE TITLE
WASM Plugin on_log method not called with Matching API

### ISSUE THREAD

**Issue by balbifm** [envoyproxy/envoy#23488]
*Title*: WASM Plugin on_log method not called with Matching API

*Description*:
The scenario is having two filters in the same filter chain for a http listener. 
* The first filter rejects the request and a response is returned by it. 
* If the second filter is an _ExtensionWithMatcher_ with an _ExecuteFilterAction_ delegating to a _WASM filter_, and the _WASM filter_ is implementing the on_log method, the method is not invoked. As opposed to having the same scenario but without the _ExtensionWithMatcher_, then the _on_log_ method is correctly invoked.

*Repro steps*:
1. Apply the attached configuration
2. curl -vvv http://localhost:10000/api/get
3. Expected a log entry containing `wasm log examples.http_filter examples.http_filter vm.examples.http_filter: on_log`, but it is not shown.

*Config*:
https://github.com/balbifm/envoy-config/blob/main/envoy.yaml

**Comment by kyessenov** [comment]
CC @mpwarres @snowp
