### ISSUE TITLE
Envoy TLS bridging

### ISSUE THREAD

**Issue by carlskii** [envoyproxy/envoy#2349]
Hi,

This is a getting started question rather than an issue. I'm looking to implement Envoy to secure service-to-service communication between two services. A little bit like this: 

![envoy-tls](https://user-images.githubusercontent.com/555399/34821351-549d3196-f6bb-11e7-8286-897cfb4566a3.png)

Could you point me at some examples or documentation that can get me started with this if there is such a thing.

Thanks

**Comment by zuercher** [comment]
I think this is what you want: https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/service_to_service.html#deployment-type-service-to-service

**Comment by mattklein123** [comment]
Yeah +1 to @zuercher. Envoy has configurable TLS on either the downstream/listener or upstream side of things. E.g., https://www.envoyproxy.io/docs/envoy/latest/api-v2/sds.proto.html#envoy-api-msg-downstreamtlscontext and https://www.envoyproxy.io/docs/envoy/latest/api-v2/sds.proto.html#upstreamtlscontext.

**Comment by mattklein123** [comment]
Closing out. Please let us know if you have further questions.
