### ISSUE TITLE
When envoy grpc call timeout, we found that sometimes the duration is much less than timeout

### ISSUE THREAD

**Issue by wendyfatcat** [envoyproxy/envoy#23499]
Hi, envoy team, in our project, we made a grpc call without retry, and we set the timeout config to 500ms.
In our test, the concurrency is 300. That means there are 300 requests send to envoy the same time.
Every test cases show that there are several requests time out, and we get a error msg "upstream request timeout".
We are debugging the envoy source code, the "timeout_.global_timeout_" in this line is equal to 500ms. 
https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L925

But we found that each time that grpc call timeout, this callback function was executed:
https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L942

and the variable "response_time" in L1128 (see below) is about more than 30% percent that less than 500ms, sometimes 200-300ms.
https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L1128

To the opposite, we also tested the success call, and we found that if one grpc call succeed, the variable "response_time"  in L1572 
sometimes also excceed 500ms, such as 630, 715, etc.
https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L1572

So is that the duration calculated in router.cc not accurate? Which duration can we use to record the real duration? Thank you.

**Comment by wbpcode** [comment]
Hi, could you provide some more context about the test. 
1. The version of Envoy.
2. The config or config_dump of Envoy.
3. How you record the duration?

**Comment by wendyfatcat** [comment]
@wbpcode Thank you for help!

1. Our Envoy version is 1.17.4
2. The config_dump is too long to paste it here. We implemented a filter, and in this filter we made a grpc call (function is similar to ext_authz_grpc_impl) to external service, the grpc timeout config is 500ms, and the connection_timeout to external service is 250ms.
3.  Before sending the grpc request, we use monotonicTime() to record the start time, and use monotonicTime() in the callback function to record the complete time, then the diff is what we needed, we call it "**grpc_duration**". This method is the same as the "**response_time**" calculated in https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L1128. 
In our test, we printed both "**grpc_duration**" and "**response_time**". When grpc call timeout, this two value are the same, and many of them are less than 500ms, even less than 200ms.

**Comment by wbpcode** [comment]
Is it possible just record error? When there are many requests is handled at same time, the log sequence of multiple threads is messy. 🤔

**Comment by wendyfatcat** [comment]
No, grpc callbacks are in different function, all the success calls will execute onSuccess(), and timeout calls will execute onFailure(). We record the duration in both function and use different names, so it cannot mistake.
All the timeout requests will execute router_cc: onResponseTimeout()->onUpstreamTimeoutAbort(),  and the "response_time" in onUpstreamTimeoutAbort() is also not correct.

**Comment by wbpcode** [comment]
Seems it's hard to find out the root cause without more detailed code and log. Could this problem be reproduced in the `ext_authz`?

**Comment by wendyfatcat** [comment]
Let I have a try. It's difficult to reproduce it via ext_authz.
