### ISSUE TITLE
Error when using filter_chain_matcher without StringValue action

### ISSUE THREAD

**Issue by sjguro** [envoyproxy/envoy#23503]
*Title*: Error when using filter_chain_matcher without StringValue action.  

*Description*: 
> We are trying to implement a custom matcher within the filter_chain_matcher which will match on a specific piece of dynamic metadata. This involves using a dynamic matching action rather than the string based static matching (stringValue action) currently used in the filter_chain_matcher. When doing this we can see that the filter_chain_manager_impl only accepts a stringValue action type called “filterChainNameAction” and therefore throws an assertion error from filter_chain_manager_impl(line 591). 
 From this document([Matching Filter Chains in Listeners — envoy 1.24.0-dev-df5152 documentation (envoyproxy.io)](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_listener)) we are able to see that the filter_chain_matcher uses a stringValue action to match to a specific chain. 

*Repro steps*: 
> Replace the action section of filter chain matcher with any other action.  
Note that we are using the typed_config to the BoolValue type. 
Example 
action: 
          name: dynamic_match 
          typed_config: 
            "@type": type.googleapis.com/google.protobuf.BoolValue 
            value: true 

This will throw an error in the filter_chain_manager_impl.cc (line 591) when trying to get the type of the action. 

*Config*: 
filter_chain_matcher: 
      matcher_tree: 
        input: 
          name: dynamic_metadata 
          typed_config: 
            "@type": type.googleapis.com/envoy.extensions.filters.common.matcher.metadata_matcher.v3.DynamicMetadataInput 
        custom_match: 
          name: envoy.matcher.metadata_matcher 
          typed_config: 
            "@type": type.googleapis.com/envoy.extensions.filters.common.matcher.metadata_matcher.v3.MetadataMatcher 
            tenant_matcher: 
              on_match: 
                action: 
                  name: filter_chain_list 
                  typed_config: 
                    "@type": type.googleapis.com/google.protobuf.BoolValue 
                    value: "true" 

*Call Stack*: 
[2022-10-12 19:48:32.127][30495][critical][assert] [external/envoy/envoy/matcher/matcher.h:74] assert failure: dynamic_cast<const T*>(this) != nullptr. 
[2022-10-12 19:48:32.127][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x7716 
[2022-10-12 19:48:32.128][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers): 
[2022-10-12 19:48:32.128][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:92] Envoy version: 281a376c41673b054c31bf55fa4c6f8d5846a649/1.24.0-dev/Modified/DEBUG/BoringSSL 
[2022-10-12 19:48:32.189][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:96] #0: Envoy::SignalAction::sigHandler() [0x561aa4072b28] 
[2022-10-12 19:48:32.189][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:96] #1: __restore_rt [0x7fe2a9ae9980] 
[2022-10-12 19:48:32.243][30495][critical][backtrace] [external/envoy/source/server/backtrace.h:96] #2: Envoy::Server::FilterChainManagerImpl::findFilterChainUsingMatcher() [0x561aa3108311]Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by kyessenov** [comment]
Can you explain the goal of using a bool action? I think the selection expects a string as the value for the filter chain name. Maybe you want a predicate `input == true -> value = chain_name`?

The crash is unfortunate, I'll take a look and make it reject a config instead.

**Comment by sjguro** [comment]
> Can you explain the goal of using a bool action? I think the selection expects a string as the value for the filter chain name. Maybe you want a predicate `input == true -> value = chain_name`?
> 
> The crash is unfortunate, I'll take a look and make it reject a config instead.


The goal is to be able to match to a value within the metadata rather than a static string. For example we could use an action such as

action:
name: dynamic_match
typed_config:
"type": type.googleapis.com/google.protobuf.Metadata
value: <Metadata field>

where the matcher would choose the filter_chain that matches the value in <Metadata field>. In the original issue we are using BoolValue with custom logic just as a way to avoid the static StringValue action.

**Comment by kyessenov** [comment]
Do I get it correctly, that you would like the filter chain name to be a value in some dynamic metadata? Let me think about it. I think the matcher doesn't allow a direct input value without matching, so you'd need to do something "if metadata value == X, then action is X", for every chain name. Would that alternative be OK?

**Comment by kyessenov** [comment]
Thanks @sjguro, I think the most intuitive thing is to define an action that is not just a string but can be computed from metadata. I'll submit a proposal.

**Comment by kyessenov** [comment]
Posted a feature request. I'll work on a draft PR.

**Comment by sjguro** [comment]
Thank you!

**Comment by ssripadham** [comment]
What is the ETA @kyessenov?

**Comment by kyessenov** [comment]
I have a prototype, and now need to get it merged in steps. First PR is #23669 , and then a couple more.

**Comment by ssripadham** [comment]
Change looks good, Is the strategy to implement the feature in 2 parts and this PR is to expose StreamInfo to filterChain matching and the stream Info will contain the dynamic metadata?

**Comment by kyessenov** [comment]
Yeah, first is to propagate stream info. Then we can add an action that reads stream info. Then an input from stream info. I think action is enough for you.

**Comment by ssripadham** [comment]
Would you be able to create a skeleton PR for the second part and share?

**Comment by kyessenov** [comment]
@ssripadham The branch is https://github.com/envoyproxy/envoy/compare/main...kyessenov:envoy:add_format_action?expand=1. I will open once the dependent PR is merged.

**Comment by ssripadham** [comment]
@kyessenov PR1 is approved.

**Comment by ssripadham** [comment]
> @ssripadham The branch is https://github.com/envoyproxy/envoy/compare/main...kyessenov:envoy:add_format_action?expand=1. I will open once the dependent PR is merged.

Seems like this PR has the changes from the first PR included. Where are the new changes located?

**Comment by kyessenov** [comment]
@ssripadham Please report on the success/failure of using the format action extension.

**Comment by ssripadham** [comment]
Thanks for the fixes @kyessenov. We were able to cherry pick your changes, integrate and test it. Are you able to merge the changes into main branch?

**Comment by ssripadham** [comment]
@kyessenov is your PR changes going to be part of Envoy 1.25?

**Comment by phlax** [comment]
@ssripadham the PRs mentioned above that have landed on `main` will be included in 1.25

im wondering if there are reasons to backport them also

**Comment by ssripadham** [comment]
That is cool. Thanks a lot @phlax
