### ISSUE TITLE
How to improve imbalance of  cpu load in threads  caused by http/2 connection?

### ISSUE THREAD

**Issue by lihaomin1010** [envoyproxy/envoy#23514]
We use envoy as gateway. Most of our clients use http2. 
I foundThe problem of  imbalance of threads is very obvious . So I use reuse_port and balance_config param.
But now the cpu load imbalance  of threads still  exists. I thick the main reason is some clients have a lot of http/2 requests, but some have a little. 
I think smaller max_concurrent_stream maybe useful, but con't solve question. Do you have some suggestion about it?

**Comment by wbpcode** [comment]
May be `max_requests_per_connection` for HCM would helpful?

**Comment by wbpcode** [comment]
It's sub field of common_http_protocol_options

**Comment by lihaomin1010** [comment]
Thanks for reply! I will try it
