### ISSUE TITLE
redis pipeline implementation

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#23517]
This is more of question about redis pipeline implementation. When we say redis supports pipeline at [protocol](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis#supported-commands) level, do we support pipeline in its true sense as described [here](https://redis.io/docs/manual/pipelining/#:~:text=Redis%20pipelining%20is%20a%20technique,supported%20by%20most%20Redis%20clients.) in terms of response ordering? 

I see the responses [here](https://github.com/envoyproxy/envoy/blob/ee1026942ad80ca95183dbce3e563b8da350cff4/source/extensions/filters/network/redis_proxy/proxy_filter.cc#L169) are sent as soon as they are received, flushing the old ones.

So if a downstream connection starts a pipeline and sends requests, are the responses to requests blocked because earlier requests are sharded to redis instances which are down (tills ops timeout/connection timeout) or responding slow?

Is that correct interpretation?

**Comment by ramaraochavali** [comment]
@mattklein123 is the above correct understanding?

**Comment by mattklein123** [comment]
IIRC the pipeline will maintain ordering.

**Comment by ramaraochavali** [comment]
Ok. So the code I pointed above seems to respond as soon as the response comes. Is there some other place the ordering is maintained? Can you please point me to that? I know you need to page lot of stuff back, so whenever you get time.

**Comment by mattklein123** [comment]
The problem is solved as you outline: some combination of health checking, timeout tuning, etc.

**Comment by ramaraochavali** [comment]
Thank you @mattklein123. one final question, do you use more than one downstream connections (I guess that would be the case to help improve throughput (use more worker threads) + detect failures fast, but will ask any way)?

**Comment by ramaraochavali** [comment]
Sure no problem. Thank you for the answers.
