### ISSUE TITLE
JWT filter: add disabled metrics

### ISSUE THREAD

**Issue by cboitel** [envoyproxy/envoy#23524]
*Title*: JWT only report `allowed` counter even if disabled on route

*Description*:

As of today, JWT filter increments the `allowed` counter even though no JWT validation has been performed:
- either because filter was disabled on route
- or because no requirement was given (e.g. requirement added only on routes where it is required)

Enhancement would:
- increment `allowed` only if actual verification was performed
- increment `disabled` counter instead if no JWT validation was performed

This would be the opportunity to enhance filter documentation by providing statistics added by filter.

**Comment by wbpcode** [comment]
Sound reasonable to me. cc @lizan

**Comment by qiwzhang** [comment]
SGTM too

**Comment by qiwzhang** [comment]
The code change should be easy and small. @cboitel you can provide a pr and I will help to review it.

**Comment by cboitel** [comment]
Will be glad to do so

**Comment by weissne** [comment]
Sorry, @qiwzhang  & @cboitel, I didn't see your comments until now. My appologies.
Yes, if it's not too much trouble for you then please go ahead.

**Comment by cboitel** [comment]
still looking to update it in the future.

**Comment by cboitel** [comment]
bumping

**Comment by cboitel** [comment]
Bumping

**Comment by cboitel** [comment]
Bumping and planned to be pr on June
