### ISSUE TITLE
Envoy dynamic proxy - terminating ssl working but easily see where to specify the terminated port

### ISSUE THREAD

**Issue by joseret** [envoyproxy/envoy#23531]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Description*:
Trying to create a envoy proxy to terminate tls and then send the terminated stream to a particular port for post processing.
Having troulbe from the docs how best do do that..

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
[dynamic.pdf](https://github.com/envoyproxy/envoy/files/9804874/dynamic.pdf)

**Comment by wbpcode** [comment]
Sorry, but I don't get your quesion clearly. what do you mean by `then send the terminated stream to a particular port for post processing`? Proxy the traffic to upstream server or other things?

**Comment by joseret** [comment]
I want to send terminiated stream to another pod on port 10000 for example
