### ISSUE TITLE
How to generate a token JWT internally in envoyproxy

### ISSUE THREAD

**Issue by Naski86** [envoyproxy/envoy#23535]
Hello.

I'm trying to make a custom plugin to generate and add in header a JWT token, however, I managed through filters to put a harcode token, but I don't know how I should do to generate one, if with lua through libraries or how, as there is hardly any documentation on generation and signing of JWT token inside envoy.

thanks

**Comment by wbpcode** [comment]
I think it's more like a quesion about jwt-lib. You can find lots of jwt lib by the google and integrate it with envoy.

**Comment by Naski86** [comment]
> I think it's more like a quesion about jwt-lib. You can find lots of jwt lib by the google and integrate it with envoy.

Hello, thanks for u answer

Good, if I'm looking at libraries, but all is to validate, not to sign within the same envoy, which I do not see anywhere, and I do not know if it is viable.

I am trying to validate a JWT and call an external uri to make a post, but I am not able to do it.

these is a example

                            
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                  function envoy_on_request(request_handle)
                      request_handle:headers():add("authorization", "danimola")
                                    
                  
                    -- Response directly and set a header from the HTTP call. No further filter iteration
                    -- occurs.
                    request_handle:httpCall(
                    "mamagement.corp",
                    {
                      [":method"] = "POST",
                      [":path"] = "/oauth/token",
                      [":authority"] = "api_header",

                      ["set-cookie"] = { "lang=lua; Path=/", "type=binding; Path=/" }
                    },
                    "hello world",
                    5000)
                  end

**Comment by Naski86** [comment]
but the libs can´t execute inside of the envoy, always call oustisde....

**Comment by wbpcode** [comment]
sorry, I am not sure what is your mean by `call outside`, couldn't we compile and link the lib with envoy to make it part of envoy binary?
May be some wrapper code is necessary to make the lib easy to be called. 🤔

**Comment by Naski86** [comment]
> sorry, I am not sure what is your mean by `call outside`, couldn't we compile and link the lib with envoy to make it part of envoy binary? May be some wrapper code is necessary to make the lib easy to be called. 🤔

yes, I mean, the examples that there are for generation, are always external.
I mean, is there an example of a library that generates it, or should I make one in lua/wasm to generate a Jwt token from envoy?
I just want to get an idea if it is possible or not.

maybe now I explain better what I want to test

**Comment by wbpcode** [comment]
I think there is no exist example for it for now. But it's possible. And lua/wasm is a choice to do that.
