### ISSUE TITLE
Compressor Filter: Weaken Strong ETags

### ISSUE THREAD

**Issue by toddmgreer** [envoyproxy/envoy#23549]
Currently, Compressor filter has two ways of handling compressible responses with etags:
 1. don't compress responses with etags (either strong or weak)
 2. remove strong etags when compressing responses
 
Our products require a different behavior:
 3. weaken strong etags (e.g. `etag: "my_etag"` -> `etag: W/"my_etag"`

To handle all three, I propose to deprecate `ResponseDirectionConfig.disable_on_etag_header` and replace it with an enum:
```
enum EtagBehavior {
  DontCompress,  // Don't compress responses with etags (strong or weak)
  RemoveStrongEtag,  // Remove strong etags when compressing
  WeakenStrongEtag  // Weaken strong etags when compressing
}
EtagBehavior etag_behavior;
```

Note: Additional behaviors I've seen include refusing to compress just strong etags, and renaming strong etags. Using an enum makes it easy to add behaviors as needed.

**Comment by wbpcode** [comment]
cc @KBaichoo
