### ISSUE TITLE
CSFR example port conflict

### ISSUE THREAD

**Issue by ploszpe** [envoyproxy/envoy#23543]
*Title*: *Both 'crossite' and 'samesite' is binding to port 8000 under csfr example*

*Description*:
This issue was introduced in commit 823dc2eb8f19a084ac49413917e1ff6f0224bf97.
Crossite should use port 8002, as it is stated in documetation.

*Repro steps*:
Try to run csfr example.

**Comment by wbpcode** [comment]
#23545

**Comment by phlax** [comment]
i think this is fixed now
