### ISSUE TITLE
How to convert the pb file under envoy/api to pb.go

### ISSUE THREAD

**Issue by zuige970126** [envoyproxy/envoy#23556]
Our envoy project is trying to modify the endpoint_ components.proto, want to use the generated pb.go to overwrite the files that go-control-plane is relative to.

**Comment by wbpcode** [comment]
You can create you owned go-control-plane with `tools/api/generate_go_protobuf.py`

**Comment by zuige970126** [comment]
Thank you for your answer.
We use a lower version of the envoy,  and found that the generated pb.go is quite different from the go-control-plane

**Comment by zuige970126** [comment]
![image](https://user-images.githubusercontent.com/65713439/197093207-e90d06cc-5c40-4d12-9cfb-a4e227d1d83b.png)
![image](https://user-images.githubusercontent.com/65713439/197093247-12ee4166-ea3b-46da-a6f4-cfa89a2412e3.png)
The first picture is the original one of go control plane, and the second picture is produced by generate_go_protobuf.py.
Is the protoc version a problem? How to solve this problem? We want to unify it with the go-control-plan.
We use envoy v1.14.7 release

**Comment by wbpcode** [comment]
> Thank you for your answer. We use a lower version of the envoy, and found that the generated pb.go is quite different from the go-control-plane

Then it's a little hard to create new control plane for you. Maybe you need do update the `tools/api/generate_go_protobuf.py` first to make sure it will pull a similar base version with your envoy.

**Comment by zuige970126** [comment]
The problem may be that the protoc-gen-go version is too low.  generate_go_protobuf.py installs protoc through bazel. Where can modify the protoc version.
