### ISSUE TITLE
prefix keys based on a value in dynamic metadata/filter state in redis

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#23558]
*Title*: prefix keys based on dynamic metadata in redis

*Description*:
We want to build a redis cluster using Envoy proxy for a multi tenant application. We want to prefix the keys supplied by user (during store and retrieve) so that we can build governance. One of the ideas is to have the prefix added in dynamic metadata (probably in a WASM network filter, based on client certificates, which users can build) and configure redis proxy with the key to look for in the dynamic metadata. Redis proxy can prefix the key before it makes call to Redis.

**Comment by wbpcode** [comment]
cc @mattklein123

**Comment by ramaraochavali** [comment]
@wbpcode can you please mark it help wanted?

**Comment by ramaraochavali** [comment]
@wbpcode @mattklein123 WDYT about this? Can you please mark this help wanted? We still need this feature.

**Comment by mattklein123** [comment]
Sure sounds reasonable at a high level but will need some design.

**Comment by ramaraochavali** [comment]
@mattklein123  Here the high level design I am thinking of 

- Introduce a new formatter flag called `key_prefix_formatter`  in the [route](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto#L136) message
- This will honour all applicable the [substitution format strings](https://www.envoyproxy.io/docs/envoy/v1.24.1/configuration/observability/access_log/usage.html?highlight=command%20operator#command-operators) similar to what access log supports
- The key prefix will happen after routing [here](https://github.com/envoyproxy/envoy/blob/4fb3eeb1a12b9005133639e96425fef16816c2a4/source/extensions/filters/network/redis_proxy/router_impl.cc#L85)

So people who want can set them in `FILTER_STATE` via WASM filter (since WASM does not support setting `DYNAMIC_META_DATA`) and Envoy will take care of prefix it before sending it to upstream redis.

**Comment by mattklein123** [comment]
Sure makes sense to me.
