### ISSUE TITLE
Statistics not match

### ISSUE THREAD

**Issue by fizzwu** [envoyproxy/envoy#2356]
*Title*: *Statistics not match*

*Description*:
>I ran up  an envoy instance with a custom ads server, everything works fine, but when I review the stats panel, I found a statistics mismatch, the `downstream_rq_2xx` is more than `downstream_rq_total`

stats log part
>http.admin.downstream_cx_active: 1
http.admin.downstream_cx_destroy: 25
http.admin.downstream_cx_destroy_active_rq: 0
http.admin.downstream_cx_destroy_local: 0
http.admin.downstream_cx_destroy_local_active_rq: 0
http.admin.downstream_cx_destroy_remote: 25
http.admin.downstream_cx_destroy_remote_active_rq: 0
http.admin.downstream_cx_drain_close: 0
http.admin.downstream_cx_http1_active: 1
http.admin.downstream_cx_http1_total: 26
http.admin.downstream_cx_http2_active: 0
http.admin.downstream_cx_http2_total: 0
http.admin.downstream_cx_idle_timeout: 0
http.admin.downstream_cx_protocol_error: 0
http.admin.downstream_cx_rx_bytes_buffered: 104
http.admin.downstream_cx_rx_bytes_total: 14581
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.admin.downstream_cx_total: 26
http.admin.downstream_cx_tx_bytes_buffered: 0
http.admin.downstream_cx_tx_bytes_total: 18129550
http.admin.downstream_cx_websocket_active: 0
http.admin.downstream_cx_websocket_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
http.admin.downstream_rq_2xx: 244
http.admin.downstream_rq_3xx: 0
http.admin.downstream_rq_4xx: 2
http.admin.downstream_rq_5xx: 0
http.admin.downstream_rq_active: 1
http.admin.downstream_rq_http1_total: 124
http.admin.downstream_rq_http2_total: 0
http.admin.downstream_rq_non_relative_path: 0
http.admin.downstream_rq_response_before_rq_complete: 0
http.admin.downstream_rq_rx_reset: 0
http.admin.downstream_rq_too_large: 0
http.admin.downstream_rq_total: 124
http.admin.downstream_rq_tx_reset: 0
http.admin.downstream_rq_ws_on_non_ws_route: 0
http.admin.rs_too_large: 0
http.admin.tracing.tracing.client_enabled: 0
http.admin.tracing.tracing.health_check: 0
http.admin.tracing.tracing.not_traceable: 0
http.admin.tracing.tracing.random_sampling: 0
http.admin.tracing.tracing.service_forced: 0

Check this:
>http.admin.downstream_rq_2xx: 244
http.admin.downstream_rq_http1_total: 124

the `downstream_rq_2xx` is more than `downstream_rq_total`, this makes me confused, is there something wrong with my configuration?

**Comment by mattklein123** [comment]
This was already fixed: https://github.com/envoyproxy/envoy/pull/2127

**Comment by fizzwu** [comment]
Got it, thanks!
