### ISSUE TITLE
connect-udp support (RFC 9298)

### ISSUE THREAD

**Issue by DavidSchinazi** [envoyproxy/envoy#23564]
*Title*:

Add support in Envoy for connect-udp ([RFC 9298](https://www.rfc-editor.org/rfc/rfc9298.html))

*Description*:

Envoy already supports the HTTP CONNECT method, Upgrades, and Extended CONNECT for HTTP/2 and HTTP/3. We would like to add support for connect-udp to allow tunneling UDP securely over HTTP. Along the way we'll also add support for HTTP Datagrams ([RFC 9297](https://www.rfc-editor.org/rfc/rfc9297.html)).

My team at Google is currently working on adding this functionality. Our current expected timeline is to have this completely landed in 2023Q2. Disclaimer: this could change.

*Relevant Links*:
* [RFC 9297](https://www.rfc-editor.org/rfc/rfc9297.html)
* [RFC 9298](https://www.rfc-editor.org/rfc/rfc9298.html)
* [Design Document](https://docs.google.com/document/d/1xVc05ooaui8H-UU65lS4q79ErhncS0Icc1c-HvgVq84/edit)

**Comment by ericorth** [comment]
Update for the sake of creating activity and keeping this open...  I've been working on research and planning for this.  I plan to start adding a bunch more details soon to the design doc David linked above.

**Comment by DavidSchinazi** [comment]
Hi everyone! We believe our [design doc](https://docs.google.com/document/d/1xVc05ooaui8H-UU65lS4q79ErhncS0Icc1c-HvgVq84/edit) is now ready for wider review. @alyssawilk @RyanTheOptimist @snowp @mattklein123 could you let us know what you think please?

**Comment by DavidSchinazi** [comment]
For future reference, marking related PRs: #25925 #26309 #26318

**Comment by enoch-dev** [comment]
any update on this?

**Comment by DavidSchinazi** [comment]
This is progressing nicely, and is currently on track to land this summer.

_**Disclaimer**: as usual, any time estimates are subject to change without notice._

**Comment by enoch-dev** [comment]
great thank you @DavidSchinazi !

**Comment by vparla** [comment]
Good to hear this is progressing !

**Comment by jeongseokson** [comment]
#27714 for CONNECT-UDP support in Envoy was landed last week. There are a couple of minor remaining things to do:

* Add Envoy documentation for CONNECT-UDP
* Add test cases for the forwarding proxy to `udp_tunneling_integration_test.cc` 
* Disable congestion control for QUIC Datagrams

I will update this issue once I complete the to-dos.

**Comment by ohadvano** [comment]
Thanks for this contribution, it looks like great work. Was wondering if supporting raw UDP tunneling was planned to be in the scope of this work (i.e Envoy receiving raw UDP data and proxies it to upstream which is CONNECT-UDP terminating)?

**Comment by DavidSchinazi** [comment]
@ohadvano that sounds like a useful feature, but we haven't put that on our roadmap yet. So while I do think we should get around to this eventually, there is currently no timeline for us doing this.

**Comment by jeongseokson** [comment]
The remaining to-do items listed above are all done and merged to the repo:

* ~~Add Envoy documentation for CONNECT-UDP~~ (#29557)
* ~~Add forwarding proxy test cases to udp_tunneling_integration_test.cc~~ (#29651)
* ~~Disable congestion control for QUIC Datagrams~~ (#28909)

As stated in the documentation, CONNECT-UDP support is still in an alpha status. We will make it more stable using the feature ourselves and preparing for this CONNECT-UDP related talk (https://sched.co/1Rj5y) in the EnvoyCon 2023.

**Comment by DavidSchinazi** [comment]
Thanks for all that work @jeongseokson and everyone else involved! I'm closing this issue to reflect that this is complete. We'll open up a separate issue to discuss getting CONNECT-UDP out of alpha status when the time is right.
