### ISSUE TITLE
better limit proto inclusion to compiled extensions

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#23565]
I noticed looking at Envoy Mobile bloaty traces that it's pulling in, for example, the skywalking trace proto despite building happily if the file is removed.
I'd like to fix the proto files so (like the C++ files) protos for a given extension are only built if the extension is built.

cc @adisuissa @htuch

**Comment by htuch** [comment]
Makes sense, do we need changes to proto files or the BUILD setup? This seems a bug more than anything.
