### ISSUE TITLE
Enhance ALS TCP to support periodic reports when the TCP connection is not closed 

### ISSUE THREAD

**Issue by wu-sheng** [envoyproxy/envoy#23579]
*Title*: *Enhance ALS TCP to support periodic reports when the TCP connection is not closed.*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Currently, the HTTP ALS reports for every HTTP request, and TCP ALS only reports after the connection is closed. 
In the observability case of SkyWalking for Istio mesh, we rely on the ALS to generate the topology map with metrics. But when TCP is set through service mesh, envoy TCP ALS would not report TCP ALS until the connection is closed.
Meanwhile, a lot of TCP connections are running in keep-alive mode, so, it lasts days to not close. As a result, we can't observe the relationship and metrics.
We hope this could be enhanced to add a new option to ALS to support TCP ALS reports periodically. And we should consider a new field in the ALS indicating the reporting mode, a) `end-of-the-session`(same as now), b) `intermediate`/`periodical`(report every several seconds even if the connection is still kept)

cc @cpakulski @dio 
FYI @wbpcode As you are well known SkyWalking using ALS :) 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

- SkyWalking ALS analysis doc, https://skywalking.apache.org/docs/main/next/en/setup/envoy/als_setting/

**Comment by wbpcode** [comment]
Sound reasonable to me. It would be helpful for the users who using raw TCP connections.

**Comment by deva26** [comment]
👍
