### ISSUE TITLE
envoy_reloadable_features_do_not_await_headers_on_upstream_timeout_to_emit_stats deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#23594]
Your change #20072 (router: record upstream request timeout stats for all the cases) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by agrawroh** [comment]
@alyssawilk Thanks, I'll open a PR to remove it.
