### ISSUE TITLE
Provide current config versions via the admin HTTP interface

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2361]
*Description*:

Feature proposal: enhance the HTTP administrative interface to show the versions of all the xDS configurations that Envoy is currently using.

The goal of this is to enable monitoring systems to detect when an Envoy instance hasn't successfully picked up the expected configuration version.

**Comment by mattklein123** [comment]
@brian-pane I believe this is a dup of https://github.com/envoyproxy/envoy/issues/2172. I'm going to close this out in favor of that. LMK if that's not the case.
