### ISSUE TITLE
flake: oauth2 integration test

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#23618]
https://dev.azure.com/cncf/envoy/_build/results?buildId=118871&view=logs&jobId=1439b9f7-a348-5b50-b5fe-ea612ea91241&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=37b0a9be-1a71-50b3-594a-4c04a031247d

[ RUN      ] IpVersionsAndGrpcTypes/OauthIntegrationTest.LoadListenerAfterServerIsInitialized/3
test/integration/fake_upstream.h:497:29: runtime error: member access within address 0x6120004d02c0 which does not point to an object of type 'Envoy::FakeHttpConnection'
0x6120004d02c0: note: object has invalid vptr
 9d 00 00 00  ef 88 03 00 00 00 00 00  b0 8a a5 0d 00 00 00 00  00 62 b7 00 60 60 00 00  28 62 b7 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x4e553c5 in Envoy::FakeHttpConnection::ReadFilter::onData(Envoy::Buffer::Instance&, bool) /proc/self/cwd/./test/integration/fake_upstream.h:497:37
    #1 0xaa34dc4 in Envoy::Network::FilterManagerImpl::onContinueReading(Envoy::Network::FilterManagerImpl::ActiveReadFilter*, Envoy::Network::ReadBufferSource&) /proc/self/cwd/source/common/network/filter_manager_impl.cc:78:48
    #2 0xaa356c0 in Envoy::Network::FilterManagerImpl::onRead() /proc/self/cwd/source/common/network/filter_manager_impl.cc:88:3
    #3 0xa9ea6ad in Envoy::Network::ConnectionImpl::onRead(unsigned long) /proc/self/cwd/source/common/network/connection_impl.cc:340:19
    #4 0xaa06996 in Envoy::Network::ConnectionImpl::onReadReady() /proc/self/cwd/source/common/network/connection_impl.cc:646:5
    #5 0xa9f9fcb in Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) /proc/self/cwd/source/common/network/connection_impl.cc:597:5
    #6 0xaa1cf43 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) /proc/self/cwd/source/common/network/connection_impl.cc:94:54
    #7 0xaa1cc6a in std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #8 0x75f4210 in std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #9 0xa959d9d in decltype(static_cast<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&>(fp)(static_cast<unsigned int>(fp0))) std::__1::__invoke<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int>(Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #10 0xa959c20 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int>(Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5&, unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9
    #11 0xa95992a in std::__1::__function::__func<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5, std::__1::allocator<Envoy::Event::DispatcherImpl::createFileEvent(int, std::__1::function<void (unsigned int)>, Envoy::Event::FileTriggerType, unsigned int)::$_5>, void (unsigned int)>::operator()(unsigned int&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #12 0x75f4210 in std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #13 0xa971d8c in Envoy::Event::FileEventImpl::mergeInjectedEventsAndRunCb(unsigned int) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #14 0xa972734 in Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_1::__invoke(int, short, void*) /proc/self/cwd/source/common/event/file_event_impl.cc:82:16
    #15 0xbb64730 in event_persist_closure /b/f/w/external/com_github_libevent_libevent/event.c:1645:9
    #16 0xbb64730 in event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1704:4
    #17 0xbb44f42 in event_process_active /b/f/w/external/com_github_libevent_libevent/event.c
    #18 0xbb44f42 in event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2047:12
    #19 0xaf06c4c in Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:60:3
    #20 0xa94d5e4 in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:299:19
    #21 0x4e0fa68 in Envoy::FakeUpstream::threadRoutine() /proc/self/cwd/test/integration/fake_upstream.cc:652:16

@vikaschoudhary16 , I think this is the test you added?

**Comment by wbpcode** [comment]
cc @vikaschoudhary16 cc @snowp

**Comment by vikaschoudhary16** [comment]
Will take a look.

**Comment by wrowe** [comment]
Ping @vikaschoudhary16 - this is affecting PR's, and main branch CI validations.

**Comment by vikaschoudhary16** [comment]
> Ping @vikaschoudhary16 - this is affecting PR's, and main branch CI validations.

hey, last couple of days were holidays in India. Would try to send a fix soon.
