### ISSUE TITLE
Add filter that computes health check response based on upstream cluster status

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2362]
*Description*:
Add a new HTTP filter that responds to incoming health checks (e.g., from a load balancer in front of Envoy) with a 200 if and only if at least X% of the servers in each of a specified list of upstream clusters are healthy.

*Motivation*:
This will be useful in situations where a cluster is starting up (or restarting). For example, if an application cluster contains 1,000 hosts, but only a few of those hosts have finished initializing, one might not want the Envoy proxy in front of that cluster to start accepting traffic yet.

*Notes*:
* I see this proposed new filter as being separate from the existing [caching health filter](https://www.envoyproxy.io/docs/envoy/latest/api-v1/http_filters/health_check_filter.html), since they'd work in fundamentally different ways.
* I'm willing to contribute an implementation of this new filter.

**Comment by ggreenway** [comment]
I could see this possibly being another configuration option on the existing hc filter.  This is neither passthrough nor no-passthrough mode.  If that config became an enum instead of bool, this could just be a 3rd value.

**Comment by brian-pane** [comment]
Good point; with the current passthrough and cached options, the existing filter already supports two very different modes of operations, so adding a third probably wouldn't hurt.

**Comment by mattklein123** [comment]
+1 on just adding this into the existing HC filter as an option. SGTM.

**Comment by brian-pane** [comment]
In the data-plane API PR, I ended up making this feature an extension to the filter's current non-pass-through mode, in order to inherit what seems like a useful property of that mode: if Envoy is draining, the filter can just return a 503, regardless of the health of the upstream cluster(s).
