### ISSUE TITLE
config vscode failed when run refresh_compdb.sh

### ISSUE THREAD

**Issue by zonghaishang** [envoyproxy/envoy#23649]
**Ubuntu 20 Parallels Vm (apple mac pro m1)**

``` bash
yiji@yiji:~/opensource/envoy$ tools/vscode/refresh_compdb.sh 

INFO: Repository com_google_protobuf_protoc_osx_x86_64 instantiated at:
  /home/yiji/opensource/envoy/WORKSPACE:13:19: in <toplevel>
  /home/yiji/opensource/envoy/bazel/repositories.bzl:202:25: in envoy_dependencies
  /home/yiji/opensource/envoy/bazel/repositories.bzl:778:30: in _com_google_protobuf
  /home/yiji/opensource/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository com_google_protobuf_protoc_win64 instantiated at:
  /home/yiji/opensource/envoy/WORKSPACE:13:19: in <toplevel>
  /home/yiji/opensource/envoy/bazel/repositories.bzl:202:25: in envoy_dependencies
  /home/yiji/opensource/envoy/bazel/repositories.bzl:778:30: in _com_google_protobuf
  /home/yiji/opensource/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository com_google_protobuf_protoc_linux_aarch_64 instantiated at:
  /home/yiji/opensource/envoy/WORKSPACE:13:19: in <toplevel>
  /home/yiji/opensource/envoy/bazel/repositories.bzl:202:25: in envoy_dependencies
  /home/yiji/opensource/envoy/bazel/repositories.bzl:778:30: in _com_google_protobuf
  /home/yiji/opensource/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>

ERROR: /home/yiji/opensource/envoy/tools/protoxform/BUILD:53:3: While resolving toolchains for target //tools/protoxform:test_proto_targets: No matching toolchains found for types @aspect_bazel_lib//lib:jq_toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@aspect_bazel_lib//lib:jq_toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//tools/protoprint:test_data_env' failed; build aborted: 
INFO: Elapsed time: 6.663s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1157 packages loaded, 8443 targets configured)
    currently loading: @base_pip3_idna//
    Fetching https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protoc-21.7-osx-x86_64.zip
    Fetching https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protoc-21.7-win64.zip
    Fetching https://github.com/protocolbuffers/protobuf/releases/download/v21.7/protoc-21.7-linux-aarch_64.zip
Traceback (most recent call last):
  File "/home/yiji/opensource/envoy/tools/gen_compilation_database.py", line 130, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/home/yiji/opensource/envoy/tools/gen_compilation_database.py", line 24, in generate_compilation_database
    subprocess.check_call([args.bazel, "build"] + bazel_options + [
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//tools/...', '//contrib/...']' returned non-zero exit status 1.

**Comment by keith** [comment]
fixed by https://github.com/envoyproxy/envoy/pull/23677 as long as you also invoke the script with `EXCLUDE_CONTRIB=true ./tools/vscode/refresh_compdb.sh`

I'm looking at the other issues that require excluding contrib

**Comment by keith** [comment]
leaving open for the other issues

**Comment by keith** [comment]
the contrib issues I see around CcInfo missing all appear to be fixed in a newer bazel, so https://github.com/envoyproxy/envoy/pull/23678 is tracking that

**Comment by zonghaishang** [comment]
> fixed by #23677 as long as you also invoke the script with `EXCLUDE_CONTRIB=true ./tools/vscode/refresh_compdb.sh`
> 
> I'm looking at the other issues that require excluding contrib

It works for me, :-) 

There seems to be some alarm, should I ignore it?

```
INFO: Build completed successfully, 7447 total actions
$TEST_TMPDIR defined: output root default is '/tmp/envoy-compdb' and max_idle_secs default is '15'.
WARNING: info command does not support starlark options. Ignoring options: [--@com_googlesource_googleurl//build_config:system_icu=0]
DEBUG: Rule 'python3_10_aarch64-unknown-linux-gnu' indicated that a canonical reproducible form can be obtained by dropping arguments ["ignore_root_user_error"]

// Here is important ??

DEBUG: Repository python3_10_aarch64-unknown-linux-gnu instantiated at:
  /home/yiji/opensource/envoy/WORKSPACE:17:25: in <toplevel>
  /home/yiji/opensource/envoy/bazel/repositories_extra.bzl:17:31: in envoy_dependencies_extra
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/rules_python/python/repositories.bzl:366:26: in python_register_toolchains
Repository rule python_repository defined at:
  /tmp/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/rules_python/python/repositories.bzl:269:36: in <toplevel>
```

**Comment by zonghaishang** [comment]
Before build run with EXCLUDE_CONTRIB=true ./tools/vscode/refresh_compdb.sh from issue https://github.com/envoyproxy/envoy/issues/23649

yiji@yiji:~/opensource/envoy$ bazel build envoy -c dbg
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:envoy (796 packages loaded, 33869 targets configured).
INFO: Found 1 target...
ERROR: /home/yiji/.cache/bazel/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/com_github_datadog_dd_opentracing_cpp/BUILD.bazel:1:11: Compiling src/tracer.cpp failed: (Exit 1): gcc failed: error executing command (from target @com_github_datadog_dd_opentracing_cpp//:dd_opentracing_cpp) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF ... (remaining 47 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_github_datadog_dd_opentracing_cpp/src/sample.h:10,
                 from external/com_github_datadog_dd_opentracing_cpp/src/tracer.h:12,
                 from external/com_github_datadog_dd_opentracing_cpp/src/tracer.cpp:12:
bazel-out/aarch64-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/3rd_party_nlohmann/nlohmann/json.hpp: In instantiation of 'std::string nlohmann::detail::lexer<BasicJsonType>::get_token_string() const [with BasicJsonType = nlohmann::basic_json<>; std::string = std::__cxx11::basic_string<char>]':
bazel-out/aarch64-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/3rd_party_nlohmann/nlohmann/json.hpp:8745:57:   required from 'void nlohmann::detail::parser<BasicJsonType>::parse(bool, BasicJsonType&) [with BasicJsonType = nlohmann::basic_json<>]'
bazel-out/aarch64-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/3rd_party_nlohmann/nlohmann/json.hpp:20882:79:   required from 'static nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer> nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::parse(IteratorType, IteratorType, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::parser_callback_t, bool) [with IteratorType = const char*; typename std::enable_if<std::is_base_of<std::random_access_iterator_tag, typename std::iterator_traits<_InputIterator>::iterator_category>::value, int>::type <anonymous> = 0; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::parser_callback_t = std::function<bool(int, nlohmann::detail::parser<nlohmann::basic_json<> >::parse_event_t, nlohmann::basic_json<>&)>]'
bazel-out/aarch64-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/3rd_party_nlohmann/nlohmann/json.hpp:22700:33:   required from here
bazel-out/aarch64-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/3rd_party_nlohmann/nlohmann/json.hpp:8494:24: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 8494 |             if ('\x00' <= c and c <= '\x1F')
      |                 ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 531.818s, Critical Path: 128.32s
INFO: 695 processes: 14 internal, 681 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by keith** [comment]
that last error is fixed by https://github.com/envoyproxy/envoy/pull/23757
