### ISSUE TITLE
How can I obtain per route downstream statistics? 

### ISSUE THREAD

**Issue by gabrielgiussi** [envoyproxy/envoy#23642]
*Title*: How can I obtain per route downstream statistics? 

*Description*:
By default I'm getting the `downstream_rq_time` histogram in `/stats/prometheus` but it doesn't include any label to identify the route.
Is there any way to include the route as a label to distinguish the latency per route?

**Comment by gabrielgiussi** [comment]
I would like to understand if this wasn't added because the feature wasn't requested or because its performance cost.

If its something we want to add out of the box I would like to work on this, in case you think it should be out of the box I would like to implement it for my use case anyway to any hint on where I could introduce this will be appreciated (also any explanation on why I shouldn't be doing this at all if that's your opinion).

**Comment by KBaichoo** [comment]
Any reason why  [access log](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage) or [tracing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing) won't work for your usecase e.g. to spot e2e latency?

**Comment by gabrielgiussi** [comment]
We currently don't have a backend that supports traces so it would be harder to use envoy tracing.
The access log could be useful, it provides the duration and the path but will require more work to parse and export those logs to an opentelemetry grpc receiver (I found [this doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto) but honestly I don't know what is the opentelemetry part here), envoy statistics on the other hand are already provided as prometheus metrics in /stats/prometheus and I can configure a prometheus receiver in my opentelemetry collector so the integration is much simpler.

Do you know if adding the path was considered and discarded or just never requested as a feature?
I'm aware of the performance issue a label with high cardinality can bring to prometheus, besides the fact that won't be useful at all since won't allow us to group by that label, so if the path would be included in the `downstream_rq_time` we'll have to provide a way to extract the static part, e.g. `/books/edit/1 => /books/edit/id`

**Comment by KBaichoo** [comment]
cc @mattklein123 @jmarantz @stevenzzzz might have more context

**Comment by mattklein123** [comment]
We already allow per-route stats which are opt-in (it works similar to the virtual cluster feature but on a per-route basis where the route must be named).

We could potentially also opt-in for some downstream stats, but keep in mind that sometimes there is no route depending on where things end up returning/failing, so it would be important to think carefully through what the stats actually mean.

Why can't you use upstream per-route stats and/or virtual clusters?

**Comment by gabrielgiussi** [comment]
@mattklein123 

I wasn't aware of the virtual_clusters feature, it seems to be what I need but [the note](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualcluster) says

> Virtual clusters are a useful tool, but we do not recommend setting up a virtual cluster for every application endpoint. This is both not easily maintainable and as well the matching and statistics output are not free.

I do want to have metrics per each endpoint in the app, I'm deploying envoy as a sidecar so I would like to have the metric for the sidecar acting as a server and as a client. Besides that many of the paths must be matched using regex to normalize them removing variable path parts, e.g. `/books/edit/1 => /books/edit/id` (although the regex is simple and backtracking shouldn't be an issue).
Do we have a recommended limit for this? How many endpoints are too much? Is there a way to monitor the cost of such metrics?

Where can I find information about `per-route stats which are opt-in`?

**Comment by mattklein123** [comment]
> Do we have a recommended limit for this? How many endpoints are too much? Is there a way to monitor the cost of such metrics?

This is really a matter of your own infra, TSDB provider, etc. You will have to try it out and see. There is no free lunch here.

> Where can I find information about per-route stats which are opt-in?

IIRC it was added recently on the route config. There is a way to turn on stats on a per route basis.

**Comment by ramaraochavali** [comment]
https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/config/route/v3/route_components.proto.html?highlight=we%20do%20recommend%20setting%20up%20stat%20prefix

**Comment by gabrielgiussi** [comment]
@mattklein123 why the per-route feature was added if virtual_clusters was already implemented? 
I can't understand in which case I should use one or the other, I'm about to use virtual_clusters but it wasn't an educated choice, I just picked one.

**Comment by mattklein123** [comment]
> @mattklein123 why the per-route feature was added if virtual_clusters was already implemented?
I can't understand in which case I should use one or the other, I'm about to use virtual_clusters but it wasn't an educated choice, I just picked one.

I can't remember the exact rationale. @ramaraochavali can provide more info.

**Comment by ramaraochavali** [comment]
VirtualClusters are VirtualHost level and supports only header matches where as the stat prefix at route level can help to get stats for various match conditions including path/prefix etc. The route stat prefix works on matched route so no additional matching conditions required like Virtual Clusters
