### ISSUE TITLE
Utility::PercentEncoding::encode doesn't encode non-ascii character correctly

### ISSUE THREAD

**Issue by boringuy** [envoyproxy/envoy#23653]
*Title*: *Utility::PercentEncoding::encode doesn't encode non-ascii character correctly*

*Description*:
Utility::PercentEncoding::encode() does not handle binary correctly because it ended up getting interpret as "negative" number due to the most significant bit being 1. 

*Repro steps*:
> Utility::PercentEncoding::encode("São Paulo") produces "S%-3D%-5Do Paulo" but it should be "S%C3%A3o Paulo"

>**Note**: N/A

*Admin and Stats Output*: N/A

>**Note**: N/A

*Config*: N/A

*Logs*: N/A

>**Note**: N/A

*Call Stack*: N/A

**Comment by boringuy** [comment]
This is a simple fix and I already update the unit test to reproduce this. I will be submitting PR soon.

**Comment by KBaichoo** [comment]
Thank you for looking into this @boringuy!

**Comment by boringuy** [comment]
The fix is easy but I have not submitted the PR yet because I need to re-read the PR guideline as I have not done it for a while. It should happen this week.
