### ISSUE TITLE
TcpProxy ignoring tunneling_config

### ISSUE THREAD

**Issue by jewertow** [envoyproxy/envoy#23674]
*Title*: *TcpProxy ignoring tunneling_config*

*Description*:
We have an [integration test](https://github.com/istio/istio/blob/master/tests/integration/pilot/tunneling_test.go) in Istio which verifies tunneling TCP over HTTP that is implemented with TcpProxy.tunneling_config.

Basically the test verifies that when an app "a" (with sidecar) sends a request HTTP/1.1 to an app "external" (without sidecar),
the request is handled by sidecar and is tunneled through a CONNECT proxy "external-forward-proxy" (Envoy configured to handle HTTP CONNECT).

Unfortunately that test sometimes [fails](https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080), because TcpProxy listener configured in the "a" sidecar ignores its tunneling_config and a connection is forwarded directly to the cluster "external", instead of "external-forward-proxy" that should tunnel the connection. What's more, the "external" cluster is not bounded to any listener, so this is completely unexpected that the traffic is sent there.

I am sure that proper XDS configuration was sent by a control plane to the sidecar "a", because we have its [config dump](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080/artifacts/pilot-183ddfe9edc14fb6ac1bb3e95/TestTunnelingOutboundTraffic/HTTP1/TLS/sidecar/HTTP-request/_test_context/echo-2-75388-state2385596915/primary-0/a-v1-7d6d5654b5-tsldk_proxy-config.json)
and [access log](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080/artifacts/pilot-183ddfe9edc14fb6ac1bb3e95/TestTunnelingOutboundTraffic/HTTP1/TLS/sidecar/HTTP-request/_test_context/echo-2-75388-state2385596915/primary-0/a-v1-7d6d5654b5-tsldk_istio-proxy.log).

You can see at the end of the access log that connections were routed to the cluster `outbound|86||external.external-1-56115.svc.cluster.local`, while it is not bounded to any listener.
```
[2022-10-21T18:30:23.830Z] "- - -" 0 - - - "-" 173 485 78 - "-" "-" "-" "-" "10.244.0.48:18086" outbound|86||external.external-1-56115.svc.cluster.local 10.244.0.43:52634 10.96.163.147:86 10.244.0.43:33176 - -
[2022-10-21T18:30:23.915Z] "- - -" 0 - - - "-" 173 485 2 - "-" "-" "-" "-" "10.244.0.48:18086" outbound|86||external.external-1-56115.svc.cluster.local 10.244.0.43:52642 10.96.163.147:86 10.244.0.43:33182 - -
[2022-10-21T18:30:23.942Z] "- - -" 0 - - - "-" 173 485 5 - "-" "-" "-" "-" "10.244.0.48:18086" outbound|86||external.external-1-56115.svc.cluster.local 10.244.0.43:52644 10.96.163.147:86 10.244.0.43:33188 - -
```
The upstream host in the log above is `10.96.163.147:86`, so connections should be handled by listener `10.96.163.147_86` and redirected to `outbound|4128|external-svc-tcp|external-forward-proxy.external-1-56115.svc.cluster.local` as you can see in the config dump, but that configuration seems to be ignored and `outbound|86||external.external-1-56115.svc.cluster.local` is used.

So I have a few questions:
1. What may cause ignoring tunneling? I was investigating implementation details and if I correctly understand methods [establishConnection](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/tcp_proxy.cc#L343) and [maybeTunnel](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/tcp_proxy.cc#L458), tunneling should be skipped if an upstream cluster is not healthy, but it's not my case, because you can see in the config dump that the cluster `outbound|4128|external-svc-tcp|external-forward-proxy.external-1-56115.svc.cluster.local` is healthy.
2. Is it possible that the dumped configuration was not yet applied at the time when it was dumped? If so, after what time it should be effectively applied?
3. Do you have any other idea what could be wrong?

Related Istio issue: https://github.com/istio/istio/issues/40812.

*Relevant Links*:

- client [log](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080/artifacts/pilot-183ddfe9edc14fb6ac1bb3e95/TestTunnelingOutboundTraffic/HTTP1/TLS/sidecar/HTTP-request/_test_context/echo-2-75388-state2385596915/primary-0/a-v1-7d6d5654b5-tsldk_app.log)
- "external" app [log](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080/artifacts/pilot-183ddfe9edc14fb6ac1bb3e95/TestTunnelingOutboundTraffic/HTTP1/TLS/sidecar/HTTP-request/_test_context/external-1-56115-state3028039004/primary-0/external-v1-6447dd4b85-bdt85_app.log)
- "external-forward-proxy" [log](https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1583519201685934080/artifacts/pilot-183ddfe9edc14fb6ac1bb3e95/TestTunnelingOutboundTraffic/HTTP1/TLS/sidecar/HTTP-request/_test_context/external-1-56115-state3028039004/primary-0/external-forward-proxy-77785898d8-kspqn_external-forward-proxy.log)

**Comment by kyessenov** [comment]
One possibility is the previous listener hasn't been drained and is still effective. Is the connection somehow persistent?

**Comment by KBaichoo** [comment]
cc @alyssawilk @zuercher

**Comment by alyssawilk** [comment]
Envoy will delay close by default, so connection: close header being respected may depend on a well behaved client.  Does your log show the connection in question being established after the config load?

**Comment by jewertow** [comment]
> Does your log show the connection in question being established after the config load?

In this particular case, a listener which should tunnel connection was updated for the last time at `2022-10-21T18:30:22.794` and after this event, client sent 9 requests within the next 1,5 second and timed out.
In general that test applies Istio configuration and sends requests for the next 10 seconds and then it times out if these requests were not tunneled by an external proxy.

> Envoy will delay close by default

How much time it takes? Is it configurable? Would you suggest to increase the timeout or delay between requests to avoid this delay?

**Comment by alyssawilk** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
covers the delay close timeout.  It's configurable in Envoy but I can't
speak to Istio config.
