### ISSUE TITLE
External Processing Filter

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#23680]
*External Processing Filter for grpc connection*

>When is the "External Processing Filter" going to be covered by a Threat model and ready to use in scenarios where downstream/upstream are not trusted? This filter solves limitations of other filters such as the header/body buffering with Lua and would be really helpful if we can use it.

**Comment by KBaichoo** [comment]
cc @gbrail @snowp @pradeepcrao
