### ISSUE TITLE
Return 429s instead of 503s in adaptive concurrency filter

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#23696]
Hi team, 
When the adaptive concurrency filter of a server is triggered, clients may feel confused that the server is unavailable instead of that the server is proactively rejecting requests. I'm wondering if it makes more sense to change the status to 429s instead of [503s](https://github.com/envoyproxy/envoy/blob/v1.24.0/source/extensions/filters/http/adaptive_concurrency/adaptive_concurrency_filter.cc#L39)? It seems netflix's concurrency limits library uses [429s](https://github.com/Netflix/concurrency-limits/blob/ff90760ebda2af6c09d7e26a6eb58edb67b4ab40/concurrency-limits-servlet/src/main/java/com/netflix/concurrency/limits/servlet/ConcurrencyLimitServletFilter.java#L39).

**Comment by RiverPhillips** [comment]
It would make sense to me if this was [configurable like the global rate limit.](https://github.com/envoyproxy/envoy/blob/ba81ae537e722ad99906599f5d3ad367ca854433/api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto#L123) We could default to 503 but allow users to override it.
