### ISSUE TITLE
Add support for redis' `GEORADIUS` command

### ISSUE THREAD

**Issue by dadadom** [envoyproxy/envoy#2369]
Add support for the `GEORADIUS` (and maybe `GEORADIUS_RO`) redis commands

*Description*:
Redis supports the [`GEORADIUS` command](https://redis.io/commands/georadius) (since version 3.2.0, added together with the other GEO commands) to retrieve items around a given geo point.
Additionally, a read-only version of this command exists, `GEORADIUS_RO` (introduced in redis 3.2.10) which can also be run on read-only redis slaves.

According to the [list of redis commands supported by envoy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis#supported-commands), these two commands are currently unsupported. 

I would like to have these commands, or at least the `GEORADIUS` command, supported by redis.

**Comment by danielhochman** [comment]
Would you be opposed to adding `GEORADIUS_RO` only for now? When adding the initial set of commands I tried to avoid any that could possibly cause a write to another key. Commands that involve multiple keys in a single command context wouldn't work as expected (referring to the `STORE` and `STOREDIST` arguments of `GEORADIUS`). The only command that made it through that was `EVAL` which of course has arbitrary capability and is impossible to reasonably audit for key modifications. When we add hash tagging support for keys I could see adding support for the non-RO version though.

**Comment by dadadom** [comment]
That would be great! For our usecase the `_RO` variant is sufficient and actually preferred.
