### ISSUE TITLE
build error(v1.24.0)

### ISSUE THREAD

**Issue by jiayoukun** [envoyproxy/envoy#23693]
I found a syntax error build to v1.24.0 envoy

The wrong path in \contrib\sip_proxy\filters\network\source\metadata.cc:29

code:  // Eg: Route: <sip:test@pcsf-cfed.cncs.svc.cluster.local;role=anch;lr;transport=udp; \

Please check if the symbol “\” is correct ？

Please timely solve, thank you

**Comment by KBaichoo** [comment]
cc @dorisd0102 @durd07 as extension owner

**Comment by KBaichoo** [comment]
Is this causing a build error? If so can you also include the error in the description? Thank you!

**Comment by durd07** [comment]
@jiayoukun 
Could you please share the build error description and your build env?
This is just one symbol in comments. I don't think it would block the building.

**Comment by jiayoukun** [comment]
@durd07 
error description : 
external/envoy/contrib/sip_proxy/filters/network/source/metadata.cc:29:3: error: multi-line comment [-Werror=comment]
   29 |   // Eg: Route: <sip:test@pcsf-cfed.cncs.svc.cluster.local;role=anch;lr;transport=udp; \
        |   ^
-------------------------------------------------------------
I think the annotation symbol is used incorrectly. Please determine whether the symbol "\" is used correctly.This comment symbol does not exist in the previous line of code.
I actually build istio-proxy because sidecar relies on envoy, so it pulls the latest envoy version. This problem did not occur in older envoy versions 1.23.2, but only in 1.24.0 and 1.25.0-dev.
build env: x86_64  ubuntu20.04
