### ISSUE TITLE
Allow dynamic cluster configuration for redis clusters

### ISSUE THREAD

**Issue by dadadom** [envoyproxy/envoy#2370]
*Title*: Feature Request: Allow redis cluster configuration via CDS

*Description*:
As mentioned in https://github.com/istio/istio/pull/1915, envoy currently does not allow to configure redis clusters via CDS. Trying to do so will result in a respective exception being thrown at https://github.com/envoyproxy/envoy/blob/master/source/common/config/utility.cc#L48

I would like to have the ability to configure redis cluster.

If that is not possible/planned, please add this limitation explicitly to the documentation.

**Comment by mattklein123** [comment]
It's possible, someone just needs to work on it. We can add a clear limitation for now to the docs. cc @danielhochman

**Comment by mattklein123** [comment]
@danielhochman I can fix this as a small work item in the next few days unless you are actively working on this. LMK.

**Comment by danielhochman** [comment]
@mattklein123 i was planning on updating the docs this week and scheduling the work later (need a little guidance on how to do it)

if you want to do it i'd be happy to code review, or if you want to tell me how to approach it and it's a small task i can do it next week.

**Comment by mattklein123** [comment]
@danielhochman you can do it, I will go over it with you.

**Comment by shuoli84** [comment]
Prevent close. still in radar, right? @mattklein123

**Comment by mattklein123** [comment]
Yes, the fix is not hard, someone just needs to do it.
