### ISSUE TITLE
JWT Filter - Add ability to pass JWT authentication failure to another filter

### ISSUE THREAD

**Issue by weissne** [envoyproxy/envoy#23701]
*Title*: 
JWT Filter - Add ability to pass JWT authentication failure to another filter

*Description*:
I'm interested in adding to the existing JWT Authentication filter (envoy.filters.http.jwt_authn)  the ability to pass the JWT authentication failure reason to another filter.

This will allow a filter following the JWT filter to be able to know not only if the JWT was successfully verified or not (which now can be done by setting the “header_in_metatda” / ”payload_in_metadata” and then checking for the JWT header / JWT payload in the metadata), but also the reason why the JWT authentication failed (failure status).

For this a new JwtRequirement type will need to be added; something like “allow_missing_or_failed_with_reason” or “allow_missing_or_failed_with_status”, and a new field to the JwtProvider for defining the key inside the metadata (under the namespace envoy.filters.http.jwt_authn) for which it’s value will be the failure reason and/or status; something like “authentication_failure_reason”.

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/v1.24.0/intro/arch_overview/security/jwt_authn_filter.html?highlight=jwt%20authentication
https://www.envoyproxy.io/docs/envoy/v1.24.0/configuration/http/http_filters/jwt_authn_filter.html?highlight=jwt%20authentication
https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/extensions/filters/http/jwt_authn/v3/config.proto

**Comment by qiwzhang** [comment]
This is a reasonable feature request.  But I will propose a simpler implementation

Just add a field in Provider
```
// Write the failed status string to metadata.
string string failed_status_to_metadata = 111;
```
This will apply to all failed cases.  

You can use this new field and existing "allow_missing_or_failed"  for your usage.

**Comment by weissne** [comment]
Thanks.
Good point that only a new field in the JwtProvider needs to be added.
I just suggest that the name should be, instead of "failed_status_to_metadata", "failed_status_**in**_metadata" (which is probably what you meant) in order  to be aligned with the other fields like "header_in_metadata" and "payload_in_metadata" .

**Comment by qiwzhang** [comment]
SG

**Comment by weissne** [comment]
Hi,
We're currently working on this enhancement and plan on completing it in the near future.
As we want to use the change temporarily until it will be accepted and merged to Envoy we are trying to understand if and how we can generate a "private" version of the go-control-plane which includes the addition that we're making in the proto.
We're currently useing the v0.10.3 go-control-plane and we would like for the changes to be based on it as it's a stable version.

Help with this will be extremely appreciated.

Thanks,
NW

**Comment by weissne** [comment]
@danieldradware has opened a [PR](https://github.com/envoyproxy/envoy/pull/24722 ) with work that we have done for this issue.

**Comment by danieldradware** [comment]
help wanted

**Comment by DieBauer** [comment]
I believe this issue can be closed, this feature is implemented in the linked PR right?

**Comment by danieldradware** [comment]
Yes you can close it, issue is already solved
