### ISSUE TITLE
New feature: Scheme redirect in RedirectAction

### ISSUE THREAD

**Issue by JayH5** [envoyproxy/envoy#2371]
*Title*: Scheme redirect in RedirectAction

*Description*:
Currently (in the routing system) the only way to redirect a request from HTTP to HTTPS is to set the `require_tls` field in a [`VirtualHost`](https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/rds.proto#virtualhost) to true. The problem with this is that it redirects any and all requests to the virtual host to HTTPS. Generally, this is a good idea, but sometimes it is desirable to only redirect certain routes.

For example, my use case is that I'd like all requests to be redirected to HTTPS _except_ for requests to the path `/.well-known/acme-challenge/` so that a different cluster can serve [ACME HTTP challenge](https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.8.3) requests from that path in order to issue certificates for the domain.

It would be useful if [`RedirectAction`](https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/rds.proto#redirectaction) supported a field named something like `scheme_redirect` which could swap the scheme portion of the URL with a new value. That way, the HTTPS redirect could be served only on a specific Route, rather than the virtual host as a whole.

HAProxy has an option that is something like this with its [`redirect scheme`](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-redirect%20scheme) option.

Alternatively, an approach like #2343 could give the flexibility to do this and might produce a solution that is closer to what one would do with Nginx: `return 301 https://$host$request_uri;`

I did ask about this on the Envoy Slack and was told that it would be an easy feature to add. I could try make the code change myself, but wanted to start out with an issue.

**Comment by mattklein123** [comment]
In general this SGTM. @brian-pane has been working in this area lately so might have further thoughts.

**Comment by JayH5** [comment]
I haven't found another (nice) way to do this.

@mattklein123 @brian-pane would it be OK if I tried working on this and went ahead with a data-plane-api PR to add a `scheme_redirect` field to `RedirectAction`?

**Comment by brian-pane** [comment]
Sounds good to me

**Comment by mattklein123** [comment]
+1 from me also.

**Comment by mattklein123** [comment]
fixed
