### ISSUE TITLE
IPv6 link local downstream endpoints not working

### ISSUE THREAD

**Issue by fcrisciani** [envoyproxy/envoy#23719]
*Title*: *IPv6 link local downstream endpoints not working*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Given a cluster with a backend endpoint such:
```
[...]
endpoint {
    address {
       socket_address {
            address: "fe80::1:1%<interface_name>"
             port_value: 1234
        }
     }
}
[...]
```
2 things should happen:
1) Envoy should be able to parse the IPv6 address with scope
2) Envoy should be able to create a socket that correctly sets the `sin6_scope_id` sockaddr_in6 (more info on link local (https://labs.ripe.net/author/philip_homburg/whats-the-deal-with-ipv6-link-local-addresses)

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

- IP parsing issue:
1) Create a cluster with link local IPv6 address and [scope](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses_(with_zone_index))

today Envoy will reject this format.

- Socket for link local IP
1)  Create a cluster with link local IPv6 address

today Envoy will return:
```
D connection [third_party/envoy/src/source/common/network/connection_impl.cc:924] [C6380] connecting to [fe80::1:1]:1234
D connection [third_party/envoy/src/source/common/network/connection_impl.cc:948] [C6380] immediate connect error: Invalid argument
```
The reason is that the kernel wants sin6_scope_id to be set.

**Comment by fcrisciani** [comment]
I validated that the issue is the one mentioned above just adding sin6_scope_id in [utility.cc](https://github.com/envoyproxy/envoy/blob/main/source/common/network/utility.cc#L106) and I was able to reach the downstream endpoint.

**Comment by fcrisciani** [comment]
My proposal for the fix is the following:

1) change the IP parsing to allow to specify the scope
2) when available add the sin6_scope_id to the sockaddr_in6 returned.

**Comment by DavidSchinazi** [comment]
IPv6 link-local identifiers aren't meant to be shared outside of a host. I'd suggest using routable IPv6 addresses such as ULA for your use-case.

**Comment by yanavlasov** [comment]
My sense is that it is reasonable to expect Envoy to work with IPv6 link local addresses, since it is used to simplify network configuration. 

The parsing of Endpoint addresses occurs here: https://github.com/envoyproxy/envoy/blob/489a41f248ebb02bcba3e30788a6c4ba943b678e/source/common/network/utility.cc#L103

It is possible to add support for parsing of the scope at the end of the IPv6 address.

**Comment by DavidSchinazi** [comment]
Reading this again it looks like the link-local identifiers aren't leaving the host - this is just local configuration. So what I said was irrelevant. Please ignore my previous comment, this sounds like a worthwhile addition.
