### ISSUE TITLE
high cpu usage on tls handshack backpressure from http health check timeout

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#23718]
*Title*: *high cpu usage on tls handshack backpressure from http health check timeout*

*Description*:
We notice a host is slow to response to admin port and cpu usage is maxed out on our docker limit.
flamegraph shows > 25% of cpu usages on tls handshake for http health checker timeout.

`Envoy::Upstream::HttpHealthCheckerImpl::HttpActiveHealthCheckSession::onTimeout` tries to close the socket but `ConnectionCloseType::NoFlush` is still try to write bytes out on
https://github.com/envoyproxy/envoy/blob/489a41f248ebb02bcba3e30788a6c4ba943b678e/source/common/network/connection_impl.cc#L143-L147 which needs tls handshake.

We should have a new flag like `ConnectionCloseType::NoFlushAndWrite` (a bad naming I admit) to avoid the back pressure given the cpu is already busy.

*Config*:
The issue is mitigated after we increase timeout to 2 seconds
```json

    "health_checks": [
      {
        "healthy_threshold": 1,
        "http_health_check": {
          "path": "/_/_/health/"
        },
        "initial_jitter": "0s",
        "interval": "5s",
        "interval_jitter": "10s",
        "timeout": "1s",
        "tls_options": {
          "alpn_protocols": [
            "http/1.1"
          ]
        },
        "unhealthy_threshold": 1
      }
```

cc @mattklein123 @adisuissa @fishcakez @PeterL328

**Comment by mattklein123** [comment]
I suppose we could also just stop trying to write pending data in the NoFlush case? Seems like if we are already not caring about flushing and this is causing issues we can just remove it backed by runtime guard?

cc @alyssawilk @ggreenway

**Comment by ggreenway** [comment]
Yeah, I think it makes sense to have a `ConnectionCloseType::Abort` that just closes everything doing the minimum amount of work, with no gracefulness even attempted.

**Comment by mattklein123** [comment]
> Yeah, I think it makes sense to have a ConnectionCloseType::Abort that just closes everything doing the minimum amount of work, with no gracefulness even attempted.

I think my question above was whether NoFlush should just be changed to be the equivalent of your "abort" ?

**Comment by JuniorHsu** [comment]
i have a diff to ci to see if we have test breakage. stay tuned

**Comment by ggreenway** [comment]
Yeah, maybe we should add `Abort` and then file an issue to replace as many `NoFlush`s with `Abort` as possible (possibly 100%).

**Comment by JuniorHsu** [comment]
Thanks ggreenway, I can introduce the `Abort` this week-ish and let's start from there!

**Comment by JuniorHsu** [comment]
@ggreenway  I have a PR https://github.com/envoyproxy/envoy/pull/24401 to introduce `Abourt`

**Comment by JuniorHsu** [comment]
close as #24401 merged. continue with another issue #25116
