### ISSUE TITLE
In a pod injected by istio sidecar, the port number in http requesturl is stripped

### ISSUE THREAD

**Issue by zhanghw0354** [envoyproxy/envoy#23725]
I meet a problem similar to [#19589 ](https://github.com/envoyproxy/envoy/issues/19589) when using istio. When requesting a service like http://10.233.2.174:8080/demo/requesturl with pod injected by sidecar, but in the service the http requesturl is changed to http://10.233.2.174/demo/requesturl, the port number is stripped. I set strip_any_host_port: false,strip_matching_host_port: false,ignore_port_in_host_matching: true in envoy filter, the problem is still not resolved.

**Comment by zhanghw0354** [comment]
The envoy filter I created as below:
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"name":"demo-filter","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"ROUTE_CONFIGURATION","patch":{"operation":"MERGE","value":{"ignore_port_in_host_matching":true,"response_headers_to_remove":["x-envoy-upstream-service-time"]}}},{"applyTo":"NETWORK_FILTER","match":{"context":"ANY","listener":{"filterChain":{"filter":{"name":"envoy.filters.network.http_connection_manager"}}}},"patch":{"operation":"MERGE","value":{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","server_header_transformation":"PASS_THROUGH","strip_any_host_port":false,"strip_matching_host_port":false}}}}]}}
  creationTimestamp: "2022-10-26T09:17:21Z"
  generation: 13
  name: demo-filter
  namespace: istio-system
  resourceVersion: "31435151"
  uid: 425377a8-cb79-4416-8b78-8eebc4feaf79
spec:
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    patch:
      operation: MERGE
      value:
        ignore_port_in_host_matching: true
        response_headers_to_remove:
        - x-envoy-upstream-service-time
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          server_header_transformation: PASS_THROUGH
          strip_any_host_port: false
          strip_matching_host_port: false

**Comment by mattklein123** [comment]
Please open this issue in the Istio project.
