### ISSUE TITLE
Connection pools questions

### ISSUE THREAD

**Issue by trick392** [envoyproxy/envoy#23724]
*Title*: Do worker threads have a cold or warm start to a an upstream server. What is the current load balancing policy of which thread will serve the connection. 

*Description*:
As described by https://www.envoyproxy.io/docs/envoy/v1.24.0/intro/arch_overview/intro/threading_model#arch-overview-threading by default each cpu core gets spun up as a worker thread by default. When serving a new client connection is there a non-zero chance that these threads form a new tcp connection with the upstream service (i.e. cold start and thereby increasing latency) or will these threads always have an active connection to the upstream and therefore never a cold start to the connection pool. 

How does envoy currently load balance which thread serves which request - is it just best effort by the kernel in managing the number of connections?

**Comment by daixiang0** [comment]
Now Envoy has [exact](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-msg-config-listener-v3-listener-connectionbalanceconfig) and [dlb](https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/dlb) connection balancers to do those things, you can search codes to see what happened.

**Comment by trick392** [comment]
awesome thank you @daixiang0 - do you have an answer to whether the connection pool has a cold start to the upstream or not?

**Comment by daixiang0** [comment]
I do not get the meaning of the cold start, as I know Envoy will not visit upstream.

**Comment by KBaichoo** [comment]
We don't currently have preconnect if there's no request to the upstream -- you will run into a cold start problem. See https://github.com/envoyproxy/envoy/issues/21346
