### ISSUE TITLE
IP Geolocation Filter

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#23736]
*Title*: *IP Geolocation Filter*

*Description*:
Introduce a filter for geolocation header decoration of the HTTP request for a trusted client address. That filter will look up a trusted client address from request in a precompiled geolocation database and populate a set of geolocation headers like `x-geo-country`, `x-geo-city`, `x-geo-asn` etc.

*Design document*:
[RFC: IP Geolocation Filter](https://docs.google.com/document/d/1klskyqKxgv5xBq1Xx38x5i5pUx7dkSztaSaoECJovJA/edit?usp=sharing)

**Comment by nezdolik** [comment]
@sc0ttbeardsley @alyssawilk @mattklein123 @rulex123 @petedmarsh please do one more pass on proposal, I have addressed feedback from community and updated the proposal. (could not tag some folks who commented in the doc, did not find their github aliases)

**Comment by sc0ttbeardsley** [comment]
@nezdolik what is the current status of this? I'm interested in it too :)

**Comment by nezdolik** [comment]
@sc0ttbeardsley i will be back from parental leave next Monday and will continue to work on the PR. You are welcome to review the PR :)

**Comment by daum3ns** [comment]
Hello 

I am also wondering on the progress of this. There is [this PR ](https://github.com/envoyproxy/envoy/pull/24318) which is already merged. 

However, if i try to configure this as stated in the [example here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/geoip_filter#configuration-example) i get the following error message:

`
Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.geoip.v3.Geoip for type Any)
`
i tried this with the version 1.26.1. as well as with a build from main branch.

**Comment by nezdolik** [comment]
@daum3ns the filter is still work in progress, maxmind provider part is currently being worked on.

**Comment by hwyuan** [comment]
@nezdolik curious if there are updates on the maxmind provider support :)

**Comment by nezdolik** [comment]
@hwyuan the PR has been opened, but we are at the stage now of evaluating if Maxmind dependency fits all the [Envoyproxy criteria](https://github.com/envoyproxy/envoy/blob/main/DEPENDENCY_POLICY.md#new-external-dependencies) for new core dependencies.
