### ISSUE TITLE
What does it mean when the heap size is much larger than allocated and physical size?

### ISSUE THREAD

**Issue by trstringer** [envoyproxy/envoy#23739]
*Title*: What does it mean when the heap size is much larger than allocated and physical size?

*Description*:

For Envoy memory consumption, I'm seeing a situation where the heap size is a large order of magnitude (in cases, 10x) larger than memory_allocated and memory_physical_size. Here's an example:

* Heap size: 3500 MB
* Allocated: 300 MB
* Physical: 400 MB

Is there any common behavior that would lead to this situation?

Also, are there any guides or documentation on Envoy high memory consumption troubleshooting that I could refer to?

Thank you in advance for any assistance!

**Comment by KBaichoo** [comment]
can you provide more context e.g. where you got each of these numbers from, etc?

**Comment by trstringer** [comment]
I got them from [the memory admin endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--memory), which I believe is an implementation of [admin.v3.Memory](https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/memory.proto).

**Comment by KBaichoo** [comment]
At the end of the day these are just layering tcmalloc measurements which can be found: https://gperftools.github.io/gperftools/tcmalloc.html , other tcmalloc documentation

You can chase the layers in source/common/memory/stats.cc and source/server/server.cc

```
memory_allocated = totalCurrentlyAllocated() = generic.current_allocated_bytes = Number of bytes used by the application.
memory heap size = Memory::Stats::totalCurrentlyReserved = generic.heap_size + tcmalloc.pageheap_unmapped_bytes
physical_bytes = Stats::totalPhysicalBytes = generic.physical_memory_used
```

My hunch is you have a lot of memory unmapped.
