### ISSUE TITLE
Pre built container is based on trusty while the docs mention Ubuntu Xenial base

### ISSUE THREAD

**Issue by sridmad** [envoyproxy/envoy#2374]
https://www.envoyproxy.io/docs/envoy/latest/install/building.html#pre-built-binaries mentions using Ubuntu Xenial Base for the container while the Docker file under CI directory uses Ubuntu:14.04 as base. 

Are the docs wrong or the Dockerfile?
Is there any plan to create a container based on 16.04?

**Comment by mattklein123** [comment]
Currently the build image (https://github.com/envoyproxy/envoy/blob/master/ci/build_container/Dockerfile-ubuntu) is Xenial, but the packaged Ubuntu image with the binary appears to be trusty. 

I don't see any reason to not make it Xenial also to match. @sridmad do you want to do a PR to fix the docker file?
