### ISSUE TITLE
Possibility to change the format of Envoy logs according to user desired format

### ISSUE THREAD

**Issue by kss95** [envoyproxy/envoy#23745]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Possibility to change the format of Envoy logs according to user desired format

*Description*:
> Could you let me know if there a possibility to change the format of Envoy logs to user desired format (Eg: to json with user defined key value pairs)?

**Comment by KBaichoo** [comment]
Which logs is this for? access logs or envoy logs?

See https://github.com/envoyproxy/envoy/issues/2692 which discussed accerss log formatting

**Comment by kss95** [comment]
Thanks for the reply.
The query is for both access logs and envoy logs. Is there the possibility to format logs, based on the syslog format defined by RFC 5424, as below:
{"version": "x.y.z", "timestamp": "YYYY-MM-DDThh:mm:ss.sss±hh:mm", "severity": "severity-level", "service_id": "service name", "message:”message from Envoy"}

**Comment by kss95** [comment]
Hi @KBaichoo/All,
Please let me know if there is any update regarding above query.
Thanks in advance

**Comment by swathikatlaparti** [comment]
Hi All,
Please let us know if there is any update on the query.
Thanks in advance
