### ISSUE TITLE
Emit Prometheus metrics based on headers or dynamic metadata

### ISSUE THREAD

**Issue by skbergam** [envoyproxy/envoy#23742]
I would like to emit Prometheus metrics with custom labels from my envoy proxy. Specifically, I would like to have total request count and latency metrics for all requests, but labeled w/ certain header values:

1.  X-SENDER - this is a request header that tells me who the caller is
2. X-ENDPOINT - this is a response header which tells me the name of the endpoint that was called

What is the best way to do this? I would like to avoid Lua script. I believe I already have metrics being emitted with basic labels like "method", "status_code", etc. I just want to add "x_sender" and "x_endpoint" labels to them.

**Comment by hochuenw-dd** [comment]
Today, the only way is probably creating (not sure if updating existing metrics would work) a new custom metric via a wasm filter. Does it make sense to have feature like this natively supported in envoy itself? @jmarantz @mattklein123
