### ISSUE TITLE
[Question] Does the non-Redis-Cluster mode support detailed commands stats?

### ISSUE THREAD

**Issue by drinkbeer** [envoyproxy/envoy#23759]
*Title*: *Does the non-Redis-Cluster mode support detailed commands stats?*

## *Description*:

Redis protocol supports commands stats in Redis Cluster based on the doc: 
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis#redis-cluster-support.

We are not using Redis-Cluster now. We use xDS and Envoy for service discovery in production. We are now using the `envoy.redis.command.latency.100percentile` metrics from DataDog, but is marked as `Legacy` now. The Envoy commands stats look pretty good.

So the questions: 
1. Does the non-Redis-cluster mode support commands stats? 
2. If not, how difficult is it to add the detailed commands stats for non-Redis-Cluster mode? Could you please give us some guidance for supporting the commands stats in non-Redis-Cluster mode?

**Comment by KBaichoo** [comment]
cc redis experts @weisisea @msukalski @HenryYYang

**Comment by drinkbeer** [comment]
Hey @weisisea @msukalski @HenryYYang, do you have some suggestions about the detailed commands states in non-Cluster mode? Thank you

**Comment by weisisea** [comment]
Hi @drinkbeer, I tried starting Envoy in non-cluster mode using the [sample config file](https://github.com/envoyproxy/envoy/blob/main/examples/redis/envoy.yaml) and was able to see per-command stats:

```
> curl http://localhost:8001/stats\?usedonly\&filter\=redis.egress_redis.command
redis.egress_redis.command.get.error: 1
redis.egress_redis.command.get.success: 2
redis.egress_redis.command.get.total: 3
redis.egress_redis.command.set.success: 1
redis.egress_redis.command.set.total: 1
redis.egress_redis.command.get.latency: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,1.025) P90(nan,1.07) P95(nan,1.085) P99(nan,1.097) P99.5(nan,1.0985) P99.9(nan,1.0997) P100(nan,1.1)
redis.egress_redis.command.set.latency: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
```

Are these stats what you are looking for?

Please also feel free to try out the [Redis filter guide](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/redis) and run `curl localhost:8001/stats` to see all the stats.
