### ISSUE TITLE
Add support for Homa - emerging TCP alternative

### ISSUE THREAD

**Issue by josephjacks** [envoyproxy/envoy#23769]
Would Envoy consider adding support (via filter or more deeply) for @johnousterhout's Homa?

Paper: https://web.stanford.edu/~ouster/cgi-bin/papers/replaceTcp.pdf

Video: https://www.youtube.com/watch?v=qu5WDcZRveo 

Example impl: https://github.com/PlatformLab/HomaModule/blob/master/protocol.md

**Comment by moderation** [comment]
Related Twitter thread at https://twitter.com/JosephJacks_/status/1587270796031844352

**Comment by KBaichoo** [comment]
cc @alyssawilk @mattklein123  @htuch

**Comment by daixiang0** [comment]
@josephjacks @johnousterhout I find it supports gRPC and Envoy already supports gRPC proxy, if there is a benchmark about gRPC + Homa + Envoy, it would be more attractive.
