### ISSUE TITLE
Equivalent to AuthorizationRequest/AuthorizationResponse configs for gPRC ext_authz service?

### ISSUE THREAD

**Issue by mikehuston** [envoyproxy/envoy#23767]
[ext_authz.v3.HttpService](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=authorizationresponse#extensions-filters-http-ext-authz-v3-httpservice) allows me to configure [authorization_request](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=authorizationresponse#extensions-filters-http-ext-authz-v3-authorizationrequest) and [authorization_response](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=authorizationresponse#extensions-filters-http-ext-authz-v3-authorizationresponse) configurations, which I find very useful for ensuring that only allow-listed headers are sent to/from my ext_authz service.

I am now looking to replace my use of HttpService with GrpcService. Is there a way to make the same configurations to a [gRPC extauthz service](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice)? From my read, there is no way to specify this on the GrpcService or any of its proto fields.

Hopefully I am overlooking something obvious and thanks in advance for the help!

**Comment by dio** [comment]
I think this is already issued: https://github.com/envoyproxy/envoy/issues/21535. On-flight PR: https://github.com/envoyproxy/envoy/pull/22877.
