### ISSUE TITLE
Speed up CI/release publishing pipeline

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#23773]
Currently, to release the steps are:

- create a release PR
- wait for it to pass
- land PR
- wait for release branch CI to pass
- release tag is created (automated by previous step)
- wait for tagged branch CI to pass
- :rocket: assets/docker images/docs are published

all in all it can take a very long time, has historically been error-prone, and encourages maintainers to force/push through steps to speed up, which is not unrelated to release errors

we can speed this up by publishing the assets/docker images/docs in the main/release branch when the tag is created

we might still want to run CI against the tagged branch but we can remove any publishing responsibilities from that part of the pipeline

**Comment by phlax** [comment]
cc @lizan @mattklein123

**Comment by lizan** [comment]
+1, or we can shorten tag CI runs to publish + verify, that's what Envoy Gateway does https://github.com/envoyproxy/gateway/blob/main/.github/workflows/release.yaml#L28

**Comment by phlax** [comment]
With #25718 i think this should now be resolved
