### ISSUE TITLE
 Dynamic upstream Socket address and SNI 

### ISSUE THREAD

**Issue by sbanala12** [envoyproxy/envoy#23778]
*Title*:  Upstream Socket address and SNI Dynamically

*Description*:
    I would like to extract the hostname from fqdn and rewrite to upstrem without cluster defination.  Here is flow 

     envoy-apps.training.in.com(fqdn) ----> envoy-apps(hostname) ---> upstream 

Example of Traffic 

https://envoy-apps.training.in.com  ---> envoy-apps ---> upstream

**Comment by phlax** [comment]
@sbanala12 can you clarify what you are trying to do please - perhaps you could show your Envoy config so far

if i understand correctly - you want the upstream cluster to be determined according to the requested hostname ?
