### ISSUE TITLE
The size of the buffer in the filter chain is set inconsistently, which causes problems with grpc transcoder

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#23774]
When a stream is http2, the maximum size of the buffer in the filter chain is derived (surprisingly) from `initial_stream_window_size`

When it's not http2, the maximum size of the buffer comes from `per_connection_buffer_limit_bytes`, which sounds more reasonable from the name, but turns out to still actually be surprising, because that value is intended to be "the maximum size of a single read" not "the maximum size of the stream buffer".

There appears to be no way to directly set the maximum size of the stream buffer.

An undesirable side-effect of this behavior is that `grpc_json_transcoder` caps a message size at whichever of those values is controlling the buffer size, erroring with e.g. `transcoder's internal buffer size exceeds the configured limit: 4210688 > 4194304` if that limit is exceeded.

A quick workaround for this is to include an `http_buffer` filter in the chain with the desired buffer size, but that also adds other behaviors that aren't necessarily desirable (i.e. it prevents streaming of the request/response even if the transcoder isn't handling a request), and clearly should not be necessary.

I propose either of two reasonable fixes for this:
1. Add a configuration option at the top level for setting the stream buffer size (which if unset will default to the current behavior, and must be greater or equal to the value from the current behavior)
2. Add a maximum message size field to grpc_json_transcoder, which calls setDecoderBufferLimit and setEncoderBufferLimit (or two fields so the maximum size can be set independently per direction) if set (and if greater than the current buffer limit).

I'd be happy to implement either of these; some discussion of which is more desirable first would be nice, or maybe someone has a better idea.

(Some prior discussion [in slack](https://envoyproxy.slack.com/archives/C78HA81DH/p1666991566358279).)

**Comment by KBaichoo** [comment]
I'm leaning more in favor of the second solution since it will push the complexity just to where it's needed -- in this case the grpc transcoder filter which might expect a given size for transcoding.

cc @nareddyt

**Comment by nareddyt** [comment]
This is surprising behavior for me too. I always assumed the buffer size would come from `per_connection_buffer_limit_bytes`, but I read the discussion on slack and understand why it's not the case.

As for the proposed solution, I would **not** prefer 2.

`setDecoderBufferLimit` and `setEncoderBufferLimit` change the buffer limits for the entire filter chain. It is nothing specific to gRPC transcoder config. It seems odd to have configuration in a single filter to mutate limits in the chain.

With this approach, would you expect _any_ decoder/encoder filter that buffers data to also expose similar configuration options? For example, [ext_proc](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter) would run into the same issue as the transcoder, so will you introduce a maximum message size field into that filter's config? What if these filters are used together in a single chain, would these calls then override one another?

I'd much rather solve this at the filter manager or level via option 1.

**Comment by KBaichoo** [comment]
I agree, the documentation could be improved in this area. If you look at the protos for example you'd see:
```
// Soft limit on size of the listener’s new connection read and write buffers.
// If unspecified, an implementation defined default is applied (1MiB).
  google.protobuf.UInt32Value per_connection_buffer_limit_bytes = 5
```

In listener.proto, it mentions the specific buffer this configures.

As there's already confusion about this buffer, I think adding another general purpose buffer knob will
push the complexity to even more users. Right now our current approach works well transparently which is great as users having to dig into the guts of Envoy to understand this isn't great. @ravenblackx ran into issues in particular with a filter that expected more data than this automatically allow. 

Now, many filters do use `setDecoderBufferLimit`, etc., for example see buffer filter, ext_authz which do have max sizes. 
I don't see why gRPC transcoding which expects a certain max size shouldn't have a knob. There's also value in
having the filters expectation closer to it in config e.g. for users to better grok vs the config knob being further away.

For example, ext_proc would run into the same issue as the transcoder
>Can you point the exact place here? ISTR that ext_proc  does chunking, etc.

What if these filters are used together in a single chain, would these calls then override one another?
> This is a great point ! I think this can be orthogonal e.g. by changing setDecoderBufferLimit to ensureDecoderBufferLimitIsAtLeast(some value).  I don't know off use cases where we'd explictly shrink this.

**Comment by nareddyt** [comment]
> Now, many filters do use setDecoderBufferLimit, etc., for example see buffer filter, ext_authz which do have max sizes.

I see, I did not realize other filters already had configs for it. I thought this was a one-off solution for the transcoder.

> This is a great point ! I think this can be orthogonal e.g. by changing setDecoderBufferLimit to ensureDecoderBufferLimitIsAtLeast(some value). I don't know off use cases where we'd explictly shrink this.

Also a great point. I like this idea of changing the API to allow setting minimum buffer levels.

OK, with these two points I am happy with your solution 2 as well.

**Comment by ravenblackx** [comment]
Strongly agree that setDecoderBufferLimit should be changed to grow-only to prevent accidental (and again surprising) conflict between filter configs. I can't think of a situation where reducing the buffer max would be a requirement for a filter.

(Though I'm not sure about the name, ensure means more like assert rather than change. increaseDecoderBufferLimitToAtLeast(value), maybe?)

**Comment by ravenblackx** [comment]
I'm going to start work on this probably some time this week, starting with changing `setDecoderBufferLimit` to `setDecoderBufferLimitLowerBound`.

**Comment by ravenblackx** [comment]
Well, the conclusion of that exercise was that replacing setDecoderBufferLimit with a version that only does increases is impractical because so many integration tests rely on it being used to shrink the buffer (and there's no reasonable alternative way to do the right thing.)

One possibility would be to leave setDecoderBufferLimit alone, but discourage its use and encourage (and migrate to) using increaseDecoderBufferLimitTo (or whatever) instead, *and* changing the existing tests to operate with another filter ahead in the chain that calls `setDecoderBufferLimit([a low value])` so that increaseDecoderBufferLimitTo can continue to do what the tests expect of it. But I don't think the effort/value ratio is good there.

Which leaves us with the idea of still adding a maximum message size config field in grpc transcoder, and using setDecoderBufferLimit *carefully* there so it explicitly only does increases, which would solve the issue and feel a bit gross.

**Comment by ravenblackx** [comment]
The inconsistent max buffer size default is still a thing, but the problem it causes with the grpc transcoder filter can now be resolved by setting `max_request_body_size` and/or `max_response_body_size`.
