### ISSUE TITLE
Add support for Consistent Hashing with Bounded Loads

### ISSUE THREAD

**Issue by thekalinga** [envoyproxy/envoy#2377]
**Issue Template**

*Title*: Add support for new load balancing algorithm "Consistent Hashing with Bounded Loads"

*Description*:

Solves the problem of overloaded servers due to consistent hashing at the same time makes sure that a single server is not loaded. The links should provide more context

[optional *Relevant Links*:]
* https://research.googleblog.com/2017/04/consistent-hashing-with-bounded-loads.html
* https://www.youtube.com/watch?v=jk6oiBJxcaA
* https://arxiv.org/pdf/1608.01350.pdf

**Comment by snowp** [comment]
Implemented in https://github.com/envoyproxy/envoy/pull/12529
