### ISSUE TITLE
optional early header mutation before tracing and routing

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#23786]
Inspired by the #23550. It would be helpful to support early header mutation before tracing and routing. 

Especially, by this way, it's possible to bridge different tracing system. For example, envoy enabled tracer B. 

Then when a request with trace headers of tracer A is coming, we can create trace headers of tracer B according to the exist A's headers before the tracing is start.

It's also could be used to do some custom modification to the request headers before routing to avoid unnecessary route entry refresh. For example, if we want to remove a specific prefix of all requests' path and route it based on the result path of modification, we need two searches of route table in previous implementation (one for initial search, one for refresh after modification).

**Comment by wbpcode** [comment]
cc @mattklein123 cc @alyssawilk

**Comment by alyssawilk** [comment]
Definitely we need to be able to handle adding headers and then selecting a route and turning up and down tracing.
For routes, I believe  the canonical way to do this for routes is to have an early filter which tweaks the headers, then clear the route cache at the HCM* which will trigger eventually reselecting the route.  if this doesn't work for tracing I think it'd be easier to adapt route reselection to handle this case than invent a new header modification layer.

decoder_callbacks_->downstreamCallbacks()->clearRouteCache();

**Comment by mattklein123** [comment]
What @alyssawilk says is true, though I think @wbpcode is saying that in some cases this can require 2 route table searches which might be expensive. I think what is being suggested is some type of modification mechanism very early in the request cycle before any filter processing has happened or any route selection has been made.

I'm not clear though on how this would work. @wbpcode can you propose some type of design/API?

**Comment by wbpcode** [comment]
> I think what is being suggested is some type of modification mechanism very early in the request cycle before any filter processing has happened or any route selection has been made.

Exactly, that's what I want. 

And, especially, the tracing system could benefit from it. For example, if an external request is traced by the skywalking APM, and zinkin is used in our inner gateway/mesh, we can covert the `sw8` (header for skywalking tracing) to the `x-b3*` (headers for zipkin) before `traceRequest` is called to avoid generating new trace id or making a different tracing decision.

**Comment by wbpcode** [comment]
I think it would an optional extension to the HCM configuration. This extension will be applied before routing/tracing.

There is a similar extension for HCM for now, `original_ip_detection`. I think this new extension will have similar design.

**Comment by mattklein123** [comment]
>  I think this new extension will have similar design.

At a high level this makes sense to me.
