### ISSUE TITLE
gcc 12 -Wuninitialized build failure

### ISSUE THREAD

**Issue by keith** [envoyproxy/envoy#23783]
```
xternal/com_google_absl/absl/container/internal/inlined_vector.h:447:5: error: '<unnamed>.absl::InlinedVector<char, 128, std::allocator<char> >::storage_.absl::inlined_vector_internal::Storage<char, 128, std::allocator<char> >::data_' is used uninitialized [-Werror=uninitialized]
  447 |     data_ = other_storage.data_;
      |     ^~~~~
./envoy/common/union_string.h: In member function 'virtual void Envoy::Http::RequestHeaderMapImpl::setByReferenceKey(absl::string_view, absl::string_view)':
./envoy/common/union_string.h:61:31: note: '<anonymous>' declared here
   61 |   UnionStringBase() : buffer_(InlinedStringVector()) {
      |                               ^~~~~~~~~~~~~~~~~~~~~
```

When building with gcc 12 on ubuntu 20.04 with `CC=gcc-12 CXX=g++-12 bz build envoy -c opt` (I think the `-c opt` matters for different warnings). on 851606902390f9e650002538114f89ab95596ab4

I'm not sure if this one is real or not but it's coming from here:

https://github.com/envoyproxy/envoy/blob/851606902390f9e650002538114f89ab95596ab4/envoy/common/union_string.h#L61

**Comment by slovdahl** [comment]
Me too on Ubuntu 22.04.

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by kajtzu** [comment]
Happens on RHEL9 derived systems, too, so CentOS, Almalinux, Rocky are affected.

```
% gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-host-pie --enable-host-bind-now --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugs.almalinux.org/ --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --without-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_64=x86-64-v2 --with-arch_32=x86-64 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.1 20220421 (Red Hat 11.3.1-2) (GCC)
```

```
% clang --version
clang version 14.0.6 (Red Hat 14.0.6-4.el9_1)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

What seems to happen is that bazel/envoy_internal.bzl first sets -Werror (line 10) which means that any warnings are treated as errors. This means that -Werror=uninitialized is set and that uninitialized data structures, if found, will interrupt the compilation. The easiest way to get it to work is appending -Wno-error=uninitialized to the array on line 71.

Whether setting this has other unintended consequences w.r.t. use of uninitialized structures is not something that I can say.

All I wanted to do was cleanly build envoy on EL9 outside a container before attempting to figure out what it needs to build inside one. Also, I am not an expert on bazel, this was my first pleasant encounter... :)

See PR #26869

**Comment by kajtzu** [comment]
As an update to this - on EL9, at least, you can compile it cleanly by using clang instead of gcc. If you want or need to compile it with gcc instead, the PR I made will make it work.

Hope this helps most of you subscribed on the ticket.

**Comment by keith** [comment]
can some folks test out https://github.com/envoyproxy/envoy/pull/27002 as a fix? this fixes my original command but I'm still not sure why this changes things
