### ISSUE TITLE
Serving static files to url mapping using Envoy

### ISSUE THREAD

**Issue by justinyjsong** [envoyproxy/envoy#23827]
*Title*: *serve static files to url using Envoy*

*Description*:
I am currently using gRPC server with Envoy in golang. Is there any way to serve http files to specific url using Envoy?

Current workaround is using `net/http` to set up separate server to serve and listen using different port that is different from gRPC server, but was wondering if there is a simpler way to resolve this without setting up different http server to serve files. There seems to be related issue as provided in relevant links, but was wondering what is the current workaround. 

*Example*:
Assume I have a folder named `templates`.
The response I want is `localhost:8080/templates/a.html` gives the file `a.html` from my `templates` folder. 

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/issues/378

**Comment by soulxu** [comment]
maybe this can help you https://github.com/envoyproxy/envoy/issues/23755

**Comment by justinyjsong** [comment]
how do I reroute such that assuming we have three files (a, b, c) under folder named `templates`

so that calling `localhost:8080/templates/` can auto-detect and map all of files from that directory?

**Comment by soulxu** [comment]
Envoy doesn't support that, actually, envoy doesn't support static files. Above it is just a workaround, you can return a static file simply.
