### ISSUE TITLE
CodeQL tcmalloc build failure clang-11

### ISSUE THREAD

**Issue by botengyao** [envoyproxy/envoy#23891]
*Title*: *CodeQL tcmalloc build failure clang-11*

*Description*:
My recent PR ran into a CodeQL build failure for an external `tcmalloc` package. Looks like it is not related to my changes, but not sure about that. Can someone also help investigate? Thank you!

Other than that, we are using clang-11 to build targets in CodeQL pipeline. Should we upgrade it?

```
ERROR: /home/runner/.cache/bazel/_bazel_runner/232997f8e2d32d79d849393f4fd56253/external/com_github_google_tcmalloc/tcmalloc/internal/BUILD:544:11: Compiling tcmalloc/internal/percpu.cc failed: (Exit 1): clang-11 failed: error executing command (from target @com_github_google_tcmalloc//tcmalloc/internal:percpu) /home/runner/work/envoy/envoy/bin/clang11/bin/clang-11 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-stdlib=libc++' -MD -MF ... (remaining 33 arguments skipped)
72external/com_github_google_tcmalloc/tcmalloc/internal/percpu.cc:57:5: error: variable does not have a constant initializer
73    __rseq_abi = {
74    ^            ~
75external/com_github_google_tcmalloc/tcmalloc/internal/percpu.cc:56:1: note: required by 'require_constant_initialization' attribute here
76ABSL_CONST_INIT thread_local ABSL_ATTRIBUTE_WEAK volatile kernel_rseq
77^~~~~~~~~~~~~~~
78external/com_google_absl/absl/base/attributes.h:714:27: note: expanded from macro 'ABSL_CONST_INIT'
79#define ABSL_CONST_INIT [[clang::require_constant_initialization]]
```
[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/actions/runs/3420660896/jobs/5695766220
https://github.com/google/tcmalloc/issues/148
https://github.com/google/tcmalloc/blob/master/tcmalloc/internal/percpu.cc#L57

https://github.com/envoyproxy/envoy/pull/23485

**Comment by botengyao** [comment]
Thanks! My today's main merge doesn't work, and looks like this PR is also impacted https://github.com/envoyproxy/envoy/pull/23835

**Comment by phlax** [comment]
https://github.com/google/tcmalloc/issues/148

**Comment by phlax** [comment]
checking through the actions im wondering why its only triggering on some PRs - i guess depending on what they need to be built - but there are few failing this check

cc @keith im wondering whether we need to back out the last tcmalloc update until we figure out the problem

**Comment by lizan** [comment]
Any reason we pinned at clang 11 for CodeQL?

**Comment by phlax** [comment]
> Any reason we pinned at clang 11 for CodeQL?

i suspect that it just hasnt been updated when the other places its installed were

**Comment by phlax** [comment]
i guess the next question is - if we bump clang can we add back the tcmalloc update - i can give it a try - not sure how we ensure the issue is triggered tho

**Comment by botengyao** [comment]
Great, thanks for fixing it!

**Comment by keith** [comment]
this same error breaks bazel CI https://buildkite.com/bazel/envoy/builds/2118#01849d85-5a46-4688-9dc4-2e30d6659b1b, looking at fixes since upgrading clang is harder there

**Comment by keith** [comment]
trying to bump the clang version for bazel CI here https://github.com/bazelbuild/continuous-integration/pull/1502
