### ISSUE TITLE
Changing the upstream destination in a filter

### ISSUE THREAD

**Issue by rjhuijsman** [envoyproxy/envoy#23919]
*Title*: Changing the upstream destination in a filter

*Description*:
I have requests coming into an Envoy gateway (set up via Istio on Kubernetes). I'd like to write a filter to...
1. Inspect the `host` or `:authority` headers and do some arbitrary business logic (do push-ups, make a charitable donation, [...], you name it - anything that's not a built-in Envoy feature yet).
2. Rewrite the `host` and `:authority` headers to point at a different Kubernetes service than the original destination.
3. Have Envoy's route the request to the rewritten Kubernetes service, rather than to the original.

I've performed that experiment using an [`ExternalProcessor` filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter). I've configured its `mutation_rules` to set `allow_all_routing: true`. I've injected that filter (using Istio) as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: respect-external-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: EXTENSION_CONFIG
      patch:
        operation: ADD
        value:
          name: my-cool-external-filter
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            failure_mode_allow: false
            async_mode: false
            request_attributes:
              - user
            response_attributes:
              - server
            # Need to set 'allow_all_routing' so that we can modify the
            # 'host'/':authority' headers.
            # https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/common/mutation_rules/v3/mutation_rules.proto
            mutation_rules:
              allow_all_routing: true
            # Only process request headers.
            processing_mode:
              request_header_mode: "SEND"
              response_header_mode: "SKIP"
              request_body_mode: "NONE"
              response_body_mode: "NONE"
              request_trailer_mode: "SKIP"
              response_trailer_mode: "SKIP"
            grpc_service:
              envoy_grpc:
                cluster_name: "outbound|18080||my-cool-external-filter.default.svc.cluster.local"
    - applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: my-cool-external-filter # This must match the name above
          config_discovery:
            config_source:
              ads: {}
            type_urls:
              [
                "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor",
              ]
  workloadSelector:
    labels:
      app: my-gateway
```

In the logs I can see that Envoy successfully reaches the external processor, and applies the header changes. However, it does NOT change where the request is routed:

```
2022-11-09T05:23:49.242829Z     debug   envoy ext_proc  Sending headers message
2022-11-09T05:23:49.243730Z     debug   envoy router    [C0][S14754424785057215411] upstream headers complete: end_stream=false
2022-11-09T05:23:49.243766Z     debug   envoy ext_proc  Received request headers response
2022-11-09T05:23:49.243774Z     debug   envoy ext_proc  applying headers response. body mode = NONE
2022-11-09T05:23:49.243785Z     debug   envoy ext_proc  Continuing processing
2022-11-09T05:23:49.243801Z     debug   envoy router    [C118][S15149972645723439778] cluster 'outbound|50051|my-istio-subset|my-original-service.default.svc.cluster.local' match for URL '/mygrpc.HelloWorld/SayHello'
2022-11-09T05:23:49.243838Z     debug   envoy router    [C118][S15149972645723439778] router decoding headers:
':method', 'POST'
':scheme', 'http'
':path', '/mygrpc.HelloWorld/SayHello'
':authority', 'my-rewritten-service.default'
'content-type', 'application/grpc'
'user-agent', 'grpcurl/v1.8.6 grpc-go/1.44.1-dev'
'te', 'trailers'
'x-forwarded-proto', 'http'
'x-request-id', 'e8b5a2bf-e9e4-4263-a3d8-15a0e0843f2b'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '7f4f883773347c029df0aef2af4012ad'
'x-b3-spanid', '9df0aef2af4012ad'
'x-b3-sampled', '0'
'x-forwarded-for', '10.42.1.26'
'x-envoy-internal', 'true'
'x-envoy-peer-metadata', '[...removed for brevity...]'
'x-envoy-peer-metadata-id', 'router~10.42.1.27~my-gateway-98f7d5cb5-9sbsj.default~default.svc.cluster.local'
'x-envoy-decorator-operation', 'my-original-service.default.svc.cluster.local:50051/*'

2022-11-09T05:23:49.243861Z     debug   envoy router    [C118][S15149972645723439778] pool ready
2022-11-09T05:23:49.248309Z     debug   envoy router    [C118][S15149972645723439778] upstream headers complete: end_stream=true
2022-11-09T05:23:49.266867Z     debug   envoy ext_proc  onDestroy
2022-11-09T05:23:49.266881Z     debug   envoy ext_proc  Calling close on stream
2022-11-09T05:23:49.266884Z     debug   envoy ext_proc  Closing gRPC stream
2022-11-09T05:23:49.266906Z     debug   envoy router    [C0][S14754424785057215411] resetting pool request
2022-11-09T05:23:49.283066Z     debug   envoy ext_proc  onDestroy
2022-11-09T05:23:49.283083Z     debug   envoy ext_proc  Calling close on stream
2022-11-09T05:23:49.283085Z     debug   envoy ext_proc  Closing gRPC stream
```

In this experiment I would expect Envoy to route the request to `my-rewritten-service.default` (the updated `:authority`), but I see the request going to `my-original-service.default` instead.

I suppose that I don't understand when and how Envoy makes its routing decision. Why does the router, which comes after my filter, not obey the header change?

In particular, when and how does Envoy make the decision about the destination cluster? This log line...
```
2022-11-09T05:23:49.243801Z     debug   envoy router    [C118][S15149972645723439778] cluster 'outbound|50051|my-istio-subset|my-original-service.default.svc.cluster.local' match for URL '/mygrpc.HelloWorld/SayHello'
```
... shows that Envoy uses the original destination cluster even after my filter is applied. So is the cluster chosen before my filter runs?

The bigger question is: is a filter a reasonable place to try and change the upstream destination of a request?

**Comment by phlax** [comment]
cc @gbrail @pradeepcrao

**Comment by kyessenov** [comment]
Routes are cached in Envoy, and must be explicitly reset by a filter to re-compute if the route matching changes. So the cluster is chosen the first time a route is requested, and I would guess ext_proc does not clear the route.

If you just want to route to IP:PORT, ORIGINAL_DST can also accept a filter override via a filter state. But that does not support EDS/VIP resolution by Envoy.

**Comment by gbrail** [comment]
Yes -- routes are cached in Envoy, and ext_proc does not invalidate the cache by default... but you can ensure that it does by setting the "clear_route_cache" field on the header or body response from your external processing server to the proxy. Most people who have encountered this issue have found that this does the trick, and furthermore I recall that ext_authz uses the same process.

**Comment by gbrail** [comment]
https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/ext_proc/v3/external_processor.proto#L276

**Comment by rjhuijsman** [comment]
That was it! 🎉 

Thank you all for the help! Much appreciated!
