### ISSUE TITLE
automatic Trace Context Fields in OpenTelemetry accesslogger

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#23948]
*Title*: 

automatic Trace Context Fields in OpenTelemetry accesslogger

*Description*:

automatic set trace context fields when using opentelemetry accesslogger as much as possible?

cc @itamarkam as code owner

[optional *Relevant Links*:]

https://opentelemetry.io/docs/reference/specification/logs/data-model/#trace-context-fields

**Comment by phlax** [comment]
cc @AlexanderEllis
