### ISSUE TITLE
Support HTTP/2 METADATA frames

### ISSUE THREAD

**Issue by birenroy** [envoyproxy/envoy#2394]
*Description*:
Add support for parsing, interpreting, and serializing HTTP/2 METADATA frames. METADATA is an extension to the HTTP/2 protocol that will be used to convey information about request and response streams out-of-line.

Google will bring the draft METADATA specification to the IETF for standardization. If the specification is adopted and any changes are made as part of the process, we should update Envoy to match.

*Relevant Links*:
Rough draft METADATA specification: https://docs.google.com/document/d/1DsPjl6qWxhcF28vzJey0xQJ2O2eRKHv7CBXt3EZyDjc/edit?usp=sharing

@alyssawilk @htuch @mattklein123

**Comment by mattklein123** [comment]
@birenroy can you make the doc public? Also, do you know offhand if implementing this can use existing extensibility mechanisms in nghttp2 or if it will require nghttp2 patches?

**Comment by alyssawilk** [comment]
I believe we can implement it with nghttp2's existing extension support.
If we get something through the IETF as an H2 extension (which is plan A) we'd probably want native support for the long haul.

**Comment by birenroy** [comment]
@mattklein123 I've updated the doc link; it should be public now. Sorry about that.

**Comment by mattklein123** [comment]
@tatsuhiro-t ^^^ (FYI)

**Comment by tatsuhiro-t** [comment]
I think METADATA frame can be implemented using nghttp2's API because it does not change HTTP/2 protocol semantics (i.e., it can be freely ignored).

**Comment by tatsuhiro-t** [comment]
Re-reading a draft, requiring successive METADATA frame until END_METADATA might cause a trouble.
nghttp2 has no guarantee to notify all frames to application, so it cannot be sure that the above rule is obeyed.
I don't know how METADATA uses Never indexed stuff, but it would be better to allow interleaving other frames if possible.

**Comment by soya3129** [comment]
> Re-reading a draft, requiring successive METADATA frame until END_METADATA might cause a trouble.
> nghttp2 has no guarantee to notify all frames to application, so it cannot be sure that the above rule is obeyed.
> I don't know how METADATA uses Never indexed stuff, but it would be better to allow interleaving other frames if possible.

Hi @tatsuhiro-t , I am assuming you referred to the following sentence in the draft:

"If the END_METADATA bit is not set, this frame MUST be followed by another METADATA frame."

I can see it is a little misleading. But we don't require METADATA frames to be sent contiguously. I think the sentence tries to say there must be following METADATA frames if  END_METADATA is not set. METADATA can interleave with other frame types. 

It is recommended to send METADATA frames back to back. This way, the peer doesn't need to save the intermediate state for a long time. For some of the METADATA use cases, METADATA is required before any message can be sent or a session can be closed. In those cases, it helps if we submit METADATA as soon as they are available.

**Comment by mattklein123** [comment]
I'm going to close this as this is implemented (to some degree). We can open new issues as needed.
