### ISSUE TITLE
CI: Coverage is currently broken

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#23985]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

CI: Coverage pages 404

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

404 when going to GCS bucket for coverage report using the link given by CI.

*Repro steps*:
> Go to  recent coverage CI output to see the uploaded coverage report. For example: https://github.com/envoyproxy/envoy/pull/23935, we'd get linked to https://storage.googleapis.com/envoy-pr/87dbffb/coverage/index.html which encounters the error below:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: envoy-pr/87dbffb/coverage/index.html</Details>
</Error>
```

**Comment by phlax** [comment]
i have followed this up quite far already - the problem is essentially bazel - the result of the `bazel coverage ...` command/s is returning empty files - not sure why that is but that is how far i got (#23930)

**Comment by KBaichoo** [comment]
Yea looking at the gcs bucket I see:
```
[08:01:51] kbaichoo:87dbffb:0 $ls -al coverage/
total 8
drwxr-x--- 2 kbaichoo primarygroup 4096 Nov 14 20:00 .
drwxr-x--- 5 kbaichoo primarygroup 4096 Nov 14 20:01 ..
-rw-r----- 1 kbaichoo primarygroup    0 Nov 14 20:00 coverage.dat
```

**Comment by phlax** [comment]
at that point we should loads of html files

if you track back the bazel command is outputting the empty dat file

**Comment by phlax** [comment]
i suspect the issue is with `bazel/coverage/collect_cc_coverage.sh` not being updated in line with bazel changes or somesuch

**Comment by phlax** [comment]
tracking trough ci history seems to confirm https://github.com/envoyproxy/envoy/pull/23678 as the culprit

cc @keith

**Comment by phlax** [comment]
and reverting that commit reveals that its not just the upload broken but coverage itself.
