### ISSUE TITLE
Can I add a filter to rewrite the domain name part of an http request?

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#2399]
How to add a filter to rewrite the domain name part of an http request?

*Description*:
Currently, the route decision of Envoy is based on the domain name. But I have a situation that the service name is part of the url, such as http://127.0.0.1/api/${Service_name}/resource. 
I think maybe I could add a filter in Envoy to rewrite the domain name part of the request, so Envoy can make the route decision based on it. 
For example, the above request should be rewritten by the filter to http://${Service_name}/api/${Service_name}/resource.

Is this possible in Envoy filter mechanism?

Thanks

**Comment by mattklein123** [comment]
Two options:

1) Use Lua and rewrite `:path` header before routing.
2) Write C++ filter and alter `:path` header and then call `clearRouteCache()`

**Comment by mattklein123** [comment]
Closing this out. Let us know if you have further questions.

**Comment by zhaohuabing** [comment]
I can use Lua, that's fantastic! Could you please give me a pointer to some documentation about this?

**Comment by mattklein123** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter

**Comment by bechhansen** [comment]
> Two options:
> 
> 1. Use Lua and rewrite `:path` header before routing.
> 2. Write C++ filter and alter `:path` header and then call `clearRouteCache()`

Hi @mattklein123 
I would like to do a filter to rewrite only the path in a Kubernetes cluster. 
Would you recommend the same approach of using a Lua filer?

I would like Envoy to do a path rewrite so a request to http://127.0.0.1/documentation/ would route to http://127.0.0.1/ of the service wrapped by the sidecar.

I have scrutinized the documentation and google but have not been able to find an example of a filter doing path rewrite.

**Comment by antoniogomezalvarado** [comment]
@bechhansen this is pretty old but hopefully someone will benefit from it 😅 

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-demo-filter
  namespace: my-namespace-with-ingress-gateway
spec:
  workloadSelector:
    labels:
      istio: ingress-gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
         name: envoy.filters.http.lua
         typed_config:
             "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
             inlineCode: |
              function envoy_on_request(request_handle)
               local original_path = request_handle:headers():get(":path")
               if original_path then
                 local new_path = string.gsub(original_path, "^/some_path_I_want_to_remove", "")
                 request_handle:headers():replace(":path", new_path)
               end
              end`
