### ISSUE TITLE
Failing to build 1.21.4 (possibly others) due to 404 for protoc-gen-validate

### ISSUE THREAD

**Issue by madpsy** [envoyproxy/envoy#24004]
*Description*:
When trying to build Envoy 1.21.4 (and possibly others), it's fetching an archive which doesn't appear to exist any more:

`WARNING: Download from https://github.com/envoyproxy/protoc-gen-validate/archive/v0.6.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found`

*Repro steps*:
Attempt to build Envoy 1.21.4 (possibly others)

*Admin and Stats Output*:
N/A

*Config*:
N/A

*Logs*:
```WARNING: Download from https://github.com/envoyproxy/protoc-gen-validate/archive/v0.6.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'com_envoyproxy_protoc_gen_validate':
   Traceback (most recent call last):
	File "/build/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/envoyproxy/protoc-gen-validate/archive/v0.6.2.tar.gz] to /build/external/com_envoyproxy_protoc_gen_validate/temp257660383487356965/v0.6.2.tar.gz: GET returned 404 Not Found```

**Comment by phlax** [comment]
thanks @madpsy - just in time for the next 1.21 release - ill address this now

what is odd is that this has not triggered in our CI - did this just start happening ?

the underlying cause is that protoc-gen-validate has moved -> bufbuild

**Comment by madpsy** [comment]
Yup within the past hour (was working earlier today).

**Comment by phlax** [comment]
yep - got it in CI now also - https://dev.azure.com/cncf/envoy/_build/results?buildId=120555&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=116

**Comment by madpsy** [comment]
Thanks for confirming. I'm up for any kind of bodge fix for now (even sed'ing the source in my pipeline) or a patch release version etc. If you have any ideas I'm all ears!

**Comment by keith** [comment]
I thought redirects solve this? Did they delete the release archive?

**Comment by phlax** [comment]
seems so

correcting the url makes the dl work

**Comment by madpsy** [comment]
`curl -v https://github.com/envoyproxy/protoc-gen-validate/archive/v0.6.2.tar.gz` results in a 302 for:

`location: https://codeload.github.com/envoyproxy/protoc-gen-validate/tar.gz/v0.6.2`

which results in a 404

**Comment by phlax** [comment]
@madpsy  fix is in #23997

**Comment by madpsy** [comment]
Not going to recommend anyone does this but I needed a very quick fix so in my Dockerfile I added this after a `git clone`

`RUN sed -i 's#envoyproxy/protoc-gen-validate#bufbuild/protoc-gen-validate#' /source/api/bazel/repository_locations.bzl`

**Comment by sorazy** [comment]
Seeing the same issue on 1.22.5. Can we do a backport for that version too? @phlax

**Comment by phlax** [comment]
fixes for all stable branches are just waiting on CI now to land

**Comment by phlax** [comment]
cc @ggreenway
