### ISSUE TITLE
The UpstreamHttpFilterConfigProviderManagerImpl has same stats prefix as HttpFilterConfigProviderManagerImpl

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#24010]
This might be a cosmetic issue, but it does not look right to have same stats prefix for two different filters:

1) https://github.com/envoyproxy/envoy/blob/6e349d9d6c0a18fadd8f8dc81c74aee1b810ac4e/source/common/filter/config_discovery_impl.h#L516

2) https://github.com/envoyproxy/envoy/blob/6e349d9d6c0a18fadd8f8dc81c74aee1b810ac4e/source/common/filter/config_discovery_impl.h#L542

**Comment by yanjunxiang-google** [comment]
@kyessenov @alyssawilk

**Comment by kyessenov** [comment]
Thinking out loud, the subscriptions are shared, so if the same filter works as both upstream and downstream HTTP, I think it's fine to reuse the prefix, no?

**Comment by yanjunxiang-google** [comment]
IIUC, even the subscriptions can be shared, and the downstream HTTP filter and upstream HTTP filter could get same configurations from control plane, but the two filters are different.They each should have their own stats counters and stats prefix.

**Comment by yanjunxiang-google** [comment]
Not stale. We should change this. Also adding some tests for UpstreamHttpFilterConfigProviderManagerImpl class to fill in the test coverage gap: https://storage.googleapis.com/envoy-pr/01a5070/coverage/source/common/filter/config_discovery_impl.h.gcov.html
