### ISSUE TITLE
When does route timeout start

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#24036]
I just read the doc about route timeout:

> A route [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout) is the amount of time that Envoy will wait for the upstream to respond with a complete response. This timeout does not start until the entire downstream request stream has been received.

Well, it said, "This timeout does not start until the entire downstream request stream has been received.". I just want to know "by whom":

> This timeout does not start until the entire downstream request stream has been received by Envoy?

or

> This timeout does not start until the entire downstream request stream has been received by upstream?

**Comment by zuercher** [comment]
The route timeout starts when the entire downstream request has been received by Envoy.
