### ISSUE TITLE
Path cannot be overwritten when using TCP tunneling

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#24038]
*Title*: Path is hardcoded as "/" and cannot be overwritten when using TCP tunneling

*Description*: When using HTTP upgrades for TCP tunneling it is sometimes required to select a custom path, for HTTP POST request, for instance. Currently path is hard coded as "/" in the source code. Feature suggested is adding an option to overwrite the path by configuration.

[optional *Relevant Links*:]
Slack discussion over this topic: https://envoyproxy.slack.com/archives/C78HA81DH/p1666598752138609

**Comment by soulxu** [comment]
seems simple to support, submit a pr directly https://github.com/envoyproxy/envoy/pull/24045
