### ISSUE TITLE
Send Encoded data for gRPC-JSON transcoding

### ISSUE THREAD

**Issue by justinyjsong** [envoyproxy/envoy#24032]
*Title*: *Handle encoded protobuf data in gRPC-JSON transcoding request*

*Description*:
I have a gRPC-go server running with Envoy for gRPC-JSON transcoding.
Our proto looks like below;

```

package sample.test

message SampleTemplate {
  string name = 1;
  string city = 2;
}

message SampleRequest {
  google.protobuf.Any content = 2;
}

message SampleResponse {
  string sample_response = 1;
}

service SampleService {
  rpc TestSample (SampleRequest) returns (SampleResponse)
  {
    option (google.api.http) = {
      post: "/v1/testSample"
      body: "*"
    };
  }
}
```

Now we can create a request as follows for any object;
```
curl -X POST localhost:8080/v1/testSample -H 'Content-Type: application/json' -d  '{"content": {"name": "temp_name", "city": "city1", "@type": "type.googleapis.com/sample.test.SampleTemplate"}}'
```

Here in this request, I used `anypb.UnmarshalNew()` which requires the type url to be specified in the request with `@type`. 

But instead of passing the JSON (String) to the post, what I want to do is to use the proto3's encode method that is available for each message.

Currently, our team calls post with payload in string;

```
           response = await axios.post("localhost:8080/v1/testSample", payload, {
                headers: {
                    'Content-Type': 'application/json'
                }
            });
```

where `payload` is in a JSON string. So I want to understand how to use `.encode` method from either `SampleTemplate` or `SampleRequest` to handle this without using JSON string while supporting any type for `content`.

Example:
```
const a = SampleTemplate.encode(jsonString);

// Pass this variable 'a' to POST request for gRPC JSON transcoding with type url as a payload to our POST call.
```

**Comment by zuercher** [comment]
To be honest this sounds like a protobuf and/or gRPC question, not an Envoy question.

**Comment by justinyjsong** [comment]
This is related to envoy because, its grpc-json transcoding does not seem to allow conversion of byte object correctly.

**Comment by zuercher** [comment]
Can you show an example of the JSON that isn't correctly handled by Envoy?

**Comment by zuercher** [comment]
But if I understand the question correctly, and by my reading of https://developers.google.com/protocol-buffers/docs/proto3#json, the JSON encoding for an Any message (that isn't one of the special well-known types like google.protobuf.Empty) is a `@type` field alongside the JSON encoded message. So I'm not sure encoding it as `@type` and `bytes` will work for any server that accepts JSON-encoded gRPC.
