### ISSUE TITLE
Image docker.io/envoyproxy/envoy-build-centos not available

### ISSUE THREAD

**Issue by toaler** [envoyproxy/envoy#2404]
The following is failing to pull down envoy-build-centos image from docker.io.

$:~/git/envoy$ IMAGE_NAME=envoyproxy/envoy-build-centos ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
Unable to find image 'envoyproxy/envoy-build-centos:52f6880ffbf761c9b809fc3ac208900956ff16b4' locally
Pulling repository docker.io/envoyproxy/envoy-build-centos
docker: Tag 52f6880ffbf761c9b809fc3ac208900956ff16b4 not found in repository docker.io/envoyproxy/envoy-build-centos.
See 'docker run --help'.

**Comment by sudeeptoroy** [comment]
U can set "IMAGE_ID=latest" along with IMAGE_NAME as a work around

**Comment by mattklein123** [comment]
Sometimes the build images don't all build correctly due to CI timeouts, etc. Using latest is probably a fine workaround per @sudeeptoroy. Going to close this out. Let us know if you have other questions.

**Comment by toaler** [comment]
Even using IMAGE_ID=latest doesn't work:

$ IMAGE_ID=latest IMAGE_NAME=envoyproxy/envoy-build-centos ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
Unable to find image 'envoyproxy/envoy-build-centos:latest' locally
latest: Pulling from envoyproxy/envoy-build-centos
af4b0a2388c6: Pull complete
8e46f47b29c9: Pull complete
205ea7d760f4: Pull complete
0fc9716f7163: Pull complete
cb05888b805a: Pull complete
5b168941ee29: Pull complete
fcd14a268a89: Pull complete
Digest: sha256:0f9e58399a918d74f9d018d28521b99ff108866c87fa4ba80980dc5059eba2c7
Status: Downloaded newer image for envoyproxy/envoy-build-centos:latest
/usr/bin/id: cannot find name for user ID 50093
/usr/bin/id: cannot find name for group ID 50093
/usr/bin/id: cannot find name for user ID 50093
ENVOY_SRCDIR=/source
M	WORKSPACE
M	bazel/get_workspace_status
M	tools/bazel.rc
HEAD is now at b904b8c... filters: remove deprecated type(). (#19)
building using 16 CPUs
gcc/g++ toolchain configured
bazel release build with tests...
Building...
INFO: $TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Extracting Bazel installation...

Failed to write zipped file "/build/tmp/_bazel_bazel/install/f20169627a8110e2cc3d005319e97c94.tmp.61/_embedded_binaries/embedded_tools/jdk/lib/tools.jar": (error: 2): No such file or directory

**Comment by sudeeptoroy** [comment]
Can u confirm if u r using the latest src code.. very recently user is created before the build..

**Comment by toaler** [comment]
My build was based on checking out v1.5.0.  The goal was to build a 1.5.0 binary.  I'm assuming I need to grab the appropriate centos image at the time v1.5.0 was built?
