### ISSUE TITLE
How to debug a wasm error?

### ISSUE THREAD

**Issue by gabrielgiussi** [envoyproxy/envoy#24067]
*Description*:
I wrote a wasm filter in assemblyscript v 0.19.23 and using https://github.com/solo-io/proxy-runtime v 0.1.15 and it loads correctly but the http call is returning a result code 2 and `proxy_on_http_call_response` is never called.

These are the logs
```
[2022-11-17 19:42:08.870][1][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm->host] env.proxy_http_call(33088, 12, 28816, 52, 33152, 0, 31904, 4, 1000, 32000)
[2022-11-17 19:42:08.872][1][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm<-host] env.proxy_http_call return: 2
```

The proxy-runtime source code documents that result code as a [BadArgument](https://github.com/solo-io/proxy-runtime/blob/3cdeddde8e4b21f1691c58fc1ec8358ccfbbbba5/assembly/runtime.ts#L153) but I don't have a clue on which of the arguments could be wrong. This is how the http call looks like
```typescript
let h: Headers = [];
    h.push(makeHeaderPair(":path", "/static/token"));
    h.push(makeHeaderPair(":method", "GET"));
    let cluster = this.getConfiguration();
    log(LogLevelValues.info, "singleton updateConfig! "+cluster);

    let result = this.httpCall(cluster,
      // provide the auth cluster our headers, so it can make an auth decision.
      h,
      // no need for body or trailers
      new ArrayBuffer(0), [],
      // 1 second timeout
      1000,
      // pass us, so that the callback receives us back.
      // once AssemblyScript supports closures, this will not be needed.
      this,
      // http callback: called when there's a response. if the request failed, headers will be 0
      (origin_context: BaseContext, headers: u32, body_size: usize, trailers: u32) => {
        log(LogLevelValues.info, "callback called!");
        let bytes = get_buffer_bytes(BufferTypeValues.HttpCallResponseBody, 0, body_size);
        log(LogLevelValues.info, "token" + String.UTF8.decode(bytes));
        set_shared_data("data", bytes);
      });
``` 

And it is almost identical to [the example from the library](https://github.com/solo-io/proxy-runtime/blob/3cdeddde8e4b21f1691c58fc1ec8358ccfbbbba5/examples/singleton/assembly/index.ts#L24).

I'm using envoy 1.20.

**Comment by gabrielgiussi** [comment]
I removed the authority header because I didn't think it was needed and I thought I've tested putting it back and making no difference, but I've tested again putting the header back and now it is working.
Anyway the question still applies about how should I have debugged this "result 2" if I didn't have the example as a basis, for example where I could find that the authority header is required?

**Comment by gabrielgiussi** [comment]
Another thing that I couldn't find documented is the semantic of the returned value `proxy_action_t` in many of the functions like [proxy_on_http_request_headers](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#proxy_on_http_request_headers).

The assemblyscript sdk [has meaningful names](https://github.com/solo-io/proxy-runtime/blob/3cdeddde8e4b21f1691c58fc1ec8358ccfbbbba5/assembly/runtime.ts#L101-L106) for the different numeric values but it isn't clear the difference between the variants, e.g. `StopIteration` vs `StopAllIterationAndBuffer` vs `StopAllIterationAndWatermark`

**Comment by wbpcode** [comment]
> for example where I could find that the authority header is required?

This is more like a conventional rule. `:path`, `:authority`, and `:method` are required headers for normal http call.

**Comment by wbpcode** [comment]
And If want debug `result 2` (BadArgument), some backgrond knowledge of Envoy is necessary.

You can find `WasmResult::BadArgument` easily from envoy source code. Sometimes a quick `grep` can solve lots of problems.
For example:
```
  // Check that we were provided certain headers.
  if (message->headers().Path() == nullptr || message->headers().Method() == nullptr ||
      message->headers().Host() == nullptr) {
    return WasmResult::BadArgument;
  }
```

**Comment by wbpcode** [comment]
cc @PiotrSikora
