### ISSUE TITLE
envoy process is consuming consistant memory both during idle (no traffic) and drastic memory during traffic with envoy-alpine 1.21.5

### ISSUE THREAD

**Issue by shilpa87-khushi** [envoyproxy/envoy#24095]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *envoy getting OOM killed during load testing*

*Description*:
>We have been using envoy proxy from past 4 years and now the latest version 1.21.5 is giving memory issues during our load tests 
previous version 1.17.4 with v2 config did not had any such issue whereas its getting killed 30min -1 hour after the load starts with continuous heap increase .

Is there anyway to debug the issue as to what is exact reason for such a memory consumption and if anyone can guide on any particular config or factors to looked upon it will be really helpful 

[optional *Relevant Links*:]
>

**Comment by wbpcode** [comment]
A profile would always be helpful for the  performance problem or potential memory leak.

See https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md

**Comment by wbpcode** [comment]
And could you provide your load test config? (And it would also be great if you can try the latest envoy version 1.24.0 first to see if this problem is fixed or not
