### ISSUE TITLE
only apply part of tag extractors to scope prefix of stats

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#24098]
*Title*: *only apply part of tag extractors to scope prefix of stats*

Regex extractors or token extractors are used to extract tag/tag value from the full stat names. However, the commonly used extractors (cluster name, etc.) could only be applied to the scope prefix to avoid calling extraction to every stat.

It means we can store some tags in the scopes and add them to the final Prometheus tags when we output stats with Prometheus format.

Both storage overhead and computation could be optimized.

**Comment by wbpcode** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
This is an interesting idea. But do we have data (flame-graphs) showing that tag-extraction is the bottleneck here?

There's been a lot of optimization around tag-extraction already and it's not clear that working on this can move the needle, at least in the scenarios I looked at.

**Comment by wbpcode** [comment]
Rather than `bottleneck`, I just think this is a point that we could do better.

**Comment by wbpcode** [comment]
If flame graph is necessary, any suggestion to this graph generation? I have no much experience about the performance evaluations of main thread.
