### ISSUE TITLE
` //test/extensions/filters/http/ext_proc:ext_proc_integration_test` is flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#24101]
example failure:

```console

Value of: processor_connection_->waitForNewStream(*dispatcher_, processor_stream_)
  Actual: false (Timed out waiting for new stream.)
Expected: true
Stack trace:
  0xc96bf5: (unknown)
  0xbffd6d: (unknown)
  0x7f52d91914cd: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f52d917821e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f52d915fb1d: testing::Test::Run()
  0x7f52d916060e: testing::TestInfo::Run()
... Google Test internal frames ...

[2022-11-17 18:00:08.573][13960][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x3c1
#0 Envoy::SignalAction::sigHandler() [0x7f52ecec3c90]

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=120849&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=11744

**Comment by phlax** [comment]
cc @mpwarres @gbrail

**Comment by phlax** [comment]
cc @tkovacs2

**Comment by mpwarres** [comment]
cc @pradeepcrao

**Comment by phlax** [comment]
this seems to affect ~all stable branches

example fail on 1.22 branch

```console
FAIL: //test/extensions/filters/http/ext_proc:streaming_integration_test (see /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/filters/http/ext_proc/streaming_integration_test/test_attempts/attempt_1.log)
FAIL: //test/extensions/filters/http/ext_proc:streaming_integration_test (see /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/filters/http/ext_proc/streaming_integration_test/test.log)

FAILED: //test/extensions/filters/http/ext_proc:streaming_integration_test (Summary)
      /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/filters/http/ext_proc/streaming_integration_test/test.log
      /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/extensions/filters/http/ext_proc/streaming_integration_test/test_attempts/attempt_1.log
INFO: From Testing //test/extensions/filters/http/ext_proc:streaming_integration_test:
==================== Test output for //test/extensions/filters/http/ext_proc:streaming_integration_test:
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=121226&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=929

we have been tracking down and fixing other flakes on these branches - im wondering if fixing one issue is exposing another

**Comment by phlax** [comment]
actually - noticing its not the same test (apologies for noise if that is the case)

**Comment by gbrail** [comment]
On my machine, two particular tests in ext_proc_integration_test were failing often enough. 

One is related to the "partial buffering" mode. I'm also working on some issues with that mode in:

https://github.com/envoyproxy/envoy/issues/23652

Furthermore, the PR I submitted to fix that issue eliminates test flakes for one of the two that fails for me:

https://github.com/envoyproxy/envoy/pull/24064

The other test case that fails often seems related to a test that tries to cause a failure during trailer processing. I'm not convinced it's important for ext_proc to try and do that, or to test for it, so I may modify the test case -- I see that someone modified it already to work better in a "deferred processing" scenario.

**Comment by phlax** [comment]
i think this is still an issue

**Comment by gbrail** [comment]
I still think that we can get this resolved if we can find a way to merge Fix
PARTIAL_BUFFERED mode to wait until body is delivered before resuming
headers by gbrail · Pull Request #24064 · envoyproxy/envoy (github.com)
<https://github.com/envoyproxy/envoy/pull/24064>

**Comment by mpwarres** [comment]
Is this flake still occurring? #24064 (mentioned earlier in [comments](https://github.com/envoyproxy/envoy/issues/24101#issuecomment-1364160748) from @gbrail) was recently merged, which might also have addressed this issue.

**Comment by phlax** [comment]
thanks for heads up @mpwarres 

afaict (from azp analytics) this is no longer happening - the only branch with similar issue is 1.22 which is about to go EOL anyway (and its pretty infrequent)

thanks @gbrail
