### ISSUE TITLE
http filter: header mutation filter that could be used as normal downstream filter or upstream filter

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#24100]
*Title*: *http filter: header mutation filter that could be used as normal downstream filter or upstream filter*

*Description*:
`request_headers_to_add` and `response_headers_to_add` and so on in the route are used to mutate request or response headers. However, all these mutations are applied in fixed position.

It would be more flexible because these mutations could run in any position of http filter chain.

~~Partly relate to #23949. IMO, it's too complex to create new `early filter`, but it still make sense to create a http header mutation filter that could run in any position (it could be used as downstream filter or upstream filter).~~

**Comment by wbpcode** [comment]
Hi, @alyssawilk could you take a look to this issue when you have free time? I had make a simple discussion in the #23972 with @kyessenov .

**Comment by alyssawilk** [comment]
yeah flexible header modification filter seems reasonable to me, esp with upstream filters where applying changes in the router may not be "late enough"
If we think it's too complicated to create an early filter are we going to roll that back?

**Comment by wbpcode** [comment]
> yeah flexible header modification filter seems reasonable to me, esp with upstream filters where applying changes in the router may not be "late enough"

Get it. This can also be used to solve the #23972. I will create a PR in the next days.

> If we think it's too complicated to create an early filter are we going to roll that back?
Ignore the `early filter`. This is a expired idea. At that time, I want create new category http filters (early filter) that can be called before route match and tracing start. But finally, I gave up because of the complexity and choose the simple design in the #23949.

**Comment by alyssawilk** [comment]
Right but if it's an expired idea, can we roll the PR back to remove the complexity we don't think we'll use?

**Comment by wbpcode** [comment]
Hmmm, I think we never had a PR that related to the `early filter`? 🤔

The #23949 wasn't a PR to implement `early filter`. It choosen a more simple design and is easy to use or maintain, and it's enough for most scenes.

So, I think there is nothing need to roll back?
