### ISSUE TITLE
Question regarding tcp proxy src ip

### ISSUE THREAD

**Issue by or-adar** [envoyproxy/envoy#24113]
Hi,
I have a use case where I want to use envoy as a proxy to forward TCP & TLS traffic to a service (running in my k8s cluster).
for the following traffic flow: `client -> envoy -> service`
I need the src ip to remain the same (based on the client IP) for TCP & TLS traffic that is meant for my service.
is it possible? how do I configure such thing for TCP proxy? does envoy handles responses on the way back properly (if the src ip is the client's ip and not the host running envoy)

**Comment by wbpcode** [comment]
As far as I know, seems it's impossible? 🤔 

cc @alyssawilk

**Comment by or-adar** [comment]
Great, thanks!
I was actually trying to understand if envoy could be a suitable replacement to stunnel.
Good to know!
