### ISSUE TITLE
How to control the timeout of response from Envoy to downstream

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#24137]
I used Envoy as the gateway of my backend HTTP web servers. Here is a common req/res chain:
```
app --a--> Envoy --b--> web_server --c--> Envoy --d--> app
```
So `a + b` is the request chain, and `c + d` is the response chain.

For now I know we have two kinds of timeout: [http request timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-timeout) and [route timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout).

As my understanding, the http request timeout is the amount of time of `a + b`. But I kind of don't understand what route timeout means. Does it mean the amount of time of `c` or of `c + d`?

I quote:
> A route [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout) is the amount of time that Envoy will wait for the upstream to respond with a complete response.

from [here](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts).

As my understanding, route timeout is the amount of time of `c`, without `d`. Am I right? If so, how to control the timeout of `d`?

**Comment by wbpcode** [comment]
Is there any requirement that need to control the timeout of d?

d is the time that the envoy send response to the client. The client may care about this time. But envoy doesn't care about it.
