### ISSUE TITLE
Measure/Detect client side timeout

### ISSUE THREAD

**Issue by arjunsingriuber** [envoyproxy/envoy#24135]
*Title*: Measure/Detect downstream timeout (client side timeout)

*Description*: 
How can we detect if the caller/client of EnvoyProxy has timed out on a request? Is there a way to detect this from EnvoyProxy?

**Comment by wbpcode** [comment]
If the caller timeout, the caller should cancel the request, right? Then envoy will presume that the caller is timeout.

And if the caller is envoy, an `expect-rq-timeout` header would be also helpful.

**Comment by arjunsingriuber** [comment]
Is there a metric emitted when the caller is timed out and it cancels the request?

**Comment by wbpcode** [comment]
There are no direct stats for it. But `downstream_cx_destroy_remote_active_rq` could be used as a reference.
