### ISSUE TITLE
OpenTelemetry/Tracing Service Name Override

### ISSUE THREAD

**Issue by blakeromano** [envoyproxy/envoy#24159]
The ability to configure the structure of service names for opentelemetry data gathered by envoy.

*Description*:
Currently Envoy only supports one naming convention for services sending opentelemetry data `localEndpoint.ServiceName` and I'd love to see a way to override this default naming convention. Using some sort of syntax like `%SERVICE_NAME%-%LOCAL_ENDPOINT%` to turn it into `ServiceName-localEndpoint`

This could probably be extended to other tracing options as well.

**Comment by kyessenov** [comment]
Could the [custom tags](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#envoy-v3-api-msg-type-tracing-v3-customtag)  help if you use open telemetry attribute names?

I think we could also use the standard naming for the default attributes sent by Envoy (operation name, etc).

**Comment by blakeromano** [comment]
I am not sure how I'd configure that with Istio specifically, regardless I still think that a more simple way to do Tracing Service Name Overrides would be good outside of custom tags.
