### ISSUE TITLE
CI github actions are not associated with repokitteh `/retest`

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#24156]
*Title*: *The new eng-flow work is not associated with repokitteh retest*

*Description*:

Envoy CD/CI has new eng-flow tests like `python_test` or `objc_helloworld` but they are flaky sometimes and could be failed due to test infra issue. (e.g. https://github.com/envoyproxy/envoy/actions/runs/3525319287/jobs/5911893897)

Re-running the test can fix them sometimes (at least both of failures are fixed by re-run), but unfortunately it is not associated with repokitteh retest that the re-run can be triggered by `/retest` and there is no `rerun` job button for people who are not maintainers. https://screenshot.googleplex.com/B2fsiGJSZX8EZdj

Ideally, people should be able to rerun those eng-flow tests via `/retest` comment like normal envoy presubmits

**Comment by tyxia** [comment]
cc @phlax 

Just FYI, I am not sure if it is something that you are in charge of.

**Comment by phlax** [comment]
i think we need this - tracking through the github actions is a PITA

ive changed the title to make it clearer the issue - altho im now wondering if `/retest` works with any of the github actions

@itayd is this something we can address?

**Comment by itayd** [comment]
If there is an endpoint in github's API that allows to retry an action that shouldn't be an issue. I guess this might be it? https://docs.github.com/en/rest/actions/workflow-runs#re-run-a-job-from-a-workflow-run

**Comment by jpsim** [comment]
There isn't a single endpoint, no. Here's how we handle this for the Envoy Mobile repo: https://github.com/jpsim/retest/blob/c158dec0a7f67cb85f8367468dc8a9a75308bb7f/retest.ts#L34-L64

**Comment by jpsim** [comment]
`/retest` now works for GitHub Actions as of #24251 

![9BFA06BB-0571-4EDC-81FB-7E32C8393D4D](https://user-images.githubusercontent.com/474794/204816925-5d3de352-f741-41cf-8a50-0ac88fcb8b44.jpeg)

However it would still be better to move it to Repokitteh which would probably make it kick in faster, since the existing action has a 10-20s delay to spin up the GitHub Actions job that processes the comment.

**Comment by phlax** [comment]
should we close this ticket @jpsim ?

**Comment by jpsim** [comment]
Sure let's close this and we can re-open a new issue if moving the functionality to Repokitteh ever becomes a priority.

**Comment by jpsim** [comment]
> However it would still be better to move it to Repokitteh which would probably make it kick in faster, since the existing action has a 10-20s delay to spin up the GitHub Actions job that processes the comment.

Turns out that the GH Actions `/retest` is pretty much just as fast as the Repokitteh one, so that alone probably isn't a reason to migrate it over.
