### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Envoy in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [envoyproxy/envoy#24183]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking Envoy. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [Ubuntu 20.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-fe4f-4610-8136-0e86d2201bef)
- [Ubuntu 20.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-fe4c-405a-a54f-05dbff615c64)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by wbpcode** [comment]
Hi, @keith could you take a look for this when you have free time? Thanks.

**Comment by keith** [comment]
WIP here https://github.com/envoyproxy/envoy/pull/24237

**Comment by meteorcloudy** [comment]
The fix didn't get into downstream because https://buildkite.com/bazel/envoy/builds/2118#01849d85-5a46-4688-9dc4-2e30d6659b1b is failing and prevented the update of last green commit for Envoy.

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/24270

**Comment by keith** [comment]
looking at the build failure, interesting that it's hit there but not on our CI, maybe a compiler version difference

**Comment by keith** [comment]
the actual build failure is https://github.com/envoyproxy/envoy/issues/23891

**Comment by botengyao** [comment]
We can keep track of this issue here: https://github.com/google/tcmalloc/issues/148

**Comment by keith** [comment]
bumping the clang version for bazel CI here https://github.com/bazelbuild/continuous-integration/pull/1502

**Comment by keith** [comment]
fixed by https://github.com/envoyproxy/envoy/pull/24296
