### ISSUE TITLE
independent filters be made depending on the target

### ISSUE THREAD

**Issue by Naskitu** [envoyproxy/envoy#24189]
hello.

can independent filters be made depending on the target?

For example

   regex: "/.*.test". 
                route:
                  cluster: target
          http_filters:
          - name: envoy.filters.http.jwt_authn
              - name: envoy.grpc_web

   regex: "/.*/hello" 
                route:
                  cluster: target2
          http_filters:
              - name: envoy.cors
              - name: envoy.grpc_web

Thanks

**Comment by wbpcode** [comment]
May be upstream filters could be helpful in the future. Or the https://github.com/envoyproxy/envoy/issues/20867 could be possible solution. But the first one is not ready for production and second one is not implemented for now.

**Comment by Naskitu** [comment]
ok thankius, i check these

sorry for my English :D
