### ISSUE TITLE
Set multiple AWS Lambda Filter credentials

### ISSUE THREAD

**Issue by YasiruShaminda** [envoyproxy/envoy#24196]
>*Title*: *Set multiple AWS Lambda Filter credentials*

Right now, only single credentials can be provided for the aws lambda filter, right? Is it possible to assign Multiple AWS Credentials to it?

**Comment by suniltheta** [comment]
The credentials used by aws lambda filter to sign the requests to obtained from
1. AWS Access key & Secret access key Env variables
2. IMDS metadata store
3. ECS Task metadata

So only a single AWS credentials can be assume by Envoy.  If you want Envoy to assume multiple credentials then the better approach would be to create multiple managed policies, attached them to the same IAM role , then attach that IAM role to credentials supplied to Envoy (Env/Ec2 Instance role/Task Iam Role)
