### ISSUE TITLE
`proxywasm.GetProperty([]string{"request", "path"})` got an empty result and and error in the response processing phase

### ISSUE THREAD

**Issue by dspo** [envoyproxy/envoy#24194]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

zh_CN: 我想获取到上游服务接收到的 request path (被重写后的 path), 但是我用 `proxywasm.GetProperty([]string{"request", "path"}) ` 只得到了一个 空的结果和一个 error.

en: I want to get the request path (rewritten path) received by the upstream service, but I use `proxywasm.GetProperty([]string{"request", "path"}) ` and I only get a empty result and an error.

the error:
```
error status returned by host: not found
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
which version of Envoy are you using ?

**Comment by wbpcode** [comment]
The header name of request path is ":path", not the "path". There is a colon.
