### ISSUE TITLE
Logging to syslog

### ISSUE THREAD

**Issue by clmssz** [envoyproxy/envoy#242]
It would be nice to be able to send access logs directly to a syslog server, making it easier to centralize logs.

**Comment by YvesZHI** [comment]
So does Envoy support syslog now? Could someone show me an example?

**Comment by guoard** [comment]
@phlax
@agrawroh

Is it possible to reopen this issue?

**Comment by phlax** [comment]
@guoard i would suggest open a new issue and ref this one
