### ISSUE TITLE
generate token JWT in envoy

### ISSUE THREAD

**Issue by Naski86** [envoyproxy/envoy#24213]
hello.

I'm trying to make it depend on each regex to use filters for each use case, but at compile time it fails me, 

is it possible to have filters for each "route" ?

**Comment by wbpcode** [comment]
Like https://github.com/envoyproxy/envoy/issues/20867?

And if the title is error?

**Comment by Naski86** [comment]
Yes, I was wrong, 

I think you can't make independent filters depending on the use case.

i close the issue!
thankis!!!

**Comment by Naski86** [comment]
resolved
