### ISSUE TITLE
consider host as active when active health check passes with both active/passive HC are enabled

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#24217]
When we have both active and passive health checks enabled, when host is ejected out of pool by passive health check failure, it will come back to pool only after ejection time is over, even though in between active health checks pass. Consider a case a where the ejection time is 2 min, the host wont be considered again for load balancing even if active health checks detect it healthy after say 30s.

I understand this is done to cover up for cases where active health check may not be going to actual server, Can this made configurable behaviour for services like Redis that wants 
- Early ejection based on passive health checks (with high ejection times)
- Come back to pool based on active health check success (instead of waiting for ejection timeout)?

Any existing config knobs that help this case or any down sides of doing this?

cc: @wbpcode @mattklein123 @snowp

**Comment by mattklein123** [comment]
Seems reasonable to me.

**Comment by ramaraochavali** [comment]
Should we have api config to drive this or runtime override is good enough?

**Comment by ramaraochavali** [comment]
> I would probably just do it always with a runtime guard and see if anyone complains?

+ 1. This is what I was thinking as well. I will push a change.

**Comment by bernardoVale** [comment]
Hi, I was reading the release notes and bumped into this new behavior.

If I understood correctly if an API endpoint starts failing on a specific host and gets ejected by the outlier but the health check remains healthy, Envoy will uneject the host on the next health check evaluation.

Isn't the example above one of the values of using an outlier detector?

**Comment by ramaraochavali** [comment]
This change will not wait for the outlier detection time i.e. if a host is ejected because of outlier detection, it will be ejected for base_ejectoin time * iteration
- with out this change, envoy will wait for that duration before it brings it back to load balancer
- with this change, if a health check passes before that interval, it will consider host as healthy and brings it back.
