### ISSUE TITLE
Make xDS retry backoff configurable

### ISSUE THREAD

**Issue by michaelbor** [envoyproxy/envoy#24236]
*Title: Add configuration parameters for xDS retry backoff strategy*

**This issue is a revival of the same issue that became stale:** https://github.com/envoyproxy/envoy/issues/9332

_Description:_
The gRPC xDS implementation uses hardcoded retry durations for re-establishing the gRPC channel. This introduces a problem when a fast failover is required from one control-plane instance to another.
In our use case, we have multiple control-plane instances in _active-standby_ mode and require a fast failover when "active" fails and the "standby" picks up.

We plan to address the TODO to make the backoff parameters configurable:
```
// TODO(htuch): Make this configurable.
static constexpr uint32_t RetryInitialDelayMs = 500;
static constexpr uint32_t RetryMaxDelayMs = 30000; // Do not cross more than 30s
backoff_strategy_ =
        std::make_unique<JitteredBackOffStrategy>(RetryInitialDelayMs, RetryMaxDelayMs, random_);
```

_Relevant Links:_
https://github.com/envoyproxy/envoy/blob/v1.12.1/source/common/config/grpc_stream.h#L39

**Comment by jaysonjdmello** [comment]
If this issue is available, I would like to work on this enhancement.
