### ISSUE TITLE
why do not customize load balance strategy by developers

### ISSUE THREAD

**Issue by danliznh** [envoyproxy/envoy#24242]
customize load balance strategy by developers

sometimes, in ours system, there is a load balance strategy, we can not configure the load balance strategy in our system to istio's yaml

**Comment by kyessenov** [comment]
Is this a question about Istio? I believe this needs to be asked in Istio forums. DestinationRule should have a field to select a strategy.

**Comment by danliznh** [comment]
> 

i think i should clarify this question, there is a field in dr we can configure a strategy, that is right. but my requirement is we can configure a new strategy we want, i think there is something like filter to support this requirement.
