### ISSUE TITLE
Please clarify type.matcher.v3.RegexMatcher's deprecated but required field: google_re2

### ISSUE THREAD

**Issue by aesophor** [envoyproxy/envoy#24256]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Please clarify type.matcher.v3.RegexMatcher's deprecated but required field: google_re2*

*Description*:
> * Currently, [`type.matcher.v3.RegexMatcher`](envoy/api/envoy/type/matcher/v3/regex.proto) requires that google_re2 should be set.
> * However, this field is marked both **deprecated** and **(validate.rules).message = {required: true}**.
> * Should I expect any changes with v3 RegexMatcher in the future?
> 
> Thanks.

**Comment by junyer** [comment]
From following commit https://github.com/envoyproxy/envoy/commit/0a92cc86e7f8b88d5af0eb2e27b5c7ef64719e56 → PR https://github.com/envoyproxy/envoy/pull/21633 → issue https://github.com/envoyproxy/envoy/issues/21618, it seems to me that @zhxie has been working on making the regular expression engine configurable at runtime. I presume that this work paves the way for plugging in Hyperscan? :D

**Comment by zhxie** [comment]
From the perspective of Protobuf, `google_re2` is required for `engine_type` while `engine_type` is optional for `RegexMatcher`. If the doc looks confusing, we can update the doc and remove the `required` mark anyway.

**Comment by aesophor** [comment]
Thanks for your reply! I really appreciate it.

I'm using envoy proxy 1.21.2.

Initially, I didn't specify `google_re2: {}`, and then I bumped into the following error when I start envoy proxy.
```yaml
cors:
  allow_origin_string_match:
    - safe_regex:
        regex: ...
```

```
caused by StringMatcherValidationError.SafeRegex: embedded message failed validation | caused by field: "engine_type", reason: is required)
```

However, if I specify `google_re2: {}`, then the error vanishes.
```yaml
cors:
  allow_origin_string_match:
    - safe_regex:
        google_re2: {}
        regex: ...
```

I checked [the proto](https://github.com/envoyproxy/envoy/blob/v1.21.2/api/envoy/type/matcher/v3/regex.proto) and find it slightly confusing.
```proto
```

According to [protobuf's official doc](https://developers.google.com/protocol-buffers/docs/proto#oneof):

> **Oneof fields are like optional fields** except all the fields in a oneof share memory

**Comment by zhxie** [comment]
The `engine_type` field is changed from required to optional since v1.24. So if you are using v1.21.2, the `google_re2` field is still required.
