### ISSUE TITLE
Report woker thread cpu usage

### ISSUE THREAD

**Issue by qls152** [envoyproxy/envoy#24255]
*Title*: *Report woker thread cpu usage*

*Description*:
> Does Envoy currently have the function of counting the CPU utilization of each thread? If not, can we provide it?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
I'm not aware of Envoy per-thread performance measurements. I think system perf could probably help here but I've never tried to measure that myself.

**Comment by qls152** [comment]
> I'm not aware of Envoy per-thread performance measurements. I think system perf could probably help here but I've never tried to measure that myself.

I think it would be better to report the cpu utilization of each worker through the stats system, perf can only be used statically to a certain extent.

**Comment by zhangbo1882** [comment]
I think you can use top -H in linux.
