### ISSUE TITLE
Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()

### ISSUE THREAD

**Issue by AmitKatyal-Sophos** [envoyproxy/envoy#24373]
*Title*: *Missing SDS resources error during config update*

*Description*:
We are using the XDS ADS with incremental mode (DeltaStream) instead of stow and observing an error. We have configured the the source of config for the LDS, CDS, RDS and SDS dynamic resources as ADS. We are using the go control plane snapshot cache to set the new configuration snapshot. In case of the change in the listener filter chain configuration, for example, one of the filter chain is being deleted, the corresponding SDS resource entry is also removed from the configuration. 
However, on SDS config update from the go control plane to the envoy proxy, envoy returns the below error.

*'typeUrl [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret](http://type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret) error :code:13 message:\"Missing SDS resources for d0232574-dc99-4599-9b92-6b27f10a520d-mtls-certs in onConfigUpdate()'*

*Attaching below the response from @adisuissa  on the slack channel:*

It seems that the error comes from: https://github.com/envoyproxy/envoy/blob/d142c9d55ae9aab34e9924aa25f20bd27635e060/source/common/secret/sds_api.cc#L150
What I think happens here, is that Envoy deletes the subscription, and doesn't expect an update to the resource to be returned.
I guess the way to improve this is to do something like in RDS (https://github.com/envoyproxy/envoy/blob/5b9183f80d6c7ab38877b8f8f48b152509f49d3e/source/common/rds/rds_route_config_subscription.cc#L122). Please open an issue so we can track this.
[sds_api.cc](https://github.com/envoyproxy/envoy/blob/d142c9d55ae9aab34e9924aa25f20bd27635e060/source/common/secret/sds_api.cc)
<https://github.com/[envoyproxy/envoy](https://github.com/envoyproxy/envoy)|envoyproxy/envoy>envoyproxy/envoy | Added by [GitHub](https://envoyproxy.slack.com/services/B01UCCXGF2T)
[rds_route_config_subscription.cc](https://github.com/envoyproxy/envoy/blob/5b9183f80d6c7ab38877b8f8f48b152509f49d3e/source/common/rds/rds_route_config_subscription.cc)

*Repro steps*:
1. Configure envoy config update in DELTA_GRPC with LDS, SDS as dynamic resources
5. Update the listener configuration such that it results in the deletion of SDS resource
6. On SDS resource deletion, go control plane is sending the resource removal update but envoy is responding with an Missing SDS error.

*Logs*:
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()\" respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"ResourceNamesSubscribe: [] ResourceNamesUnsubscribe: [] InitialResourceVersions: map[]","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.route.v3.RouteConfiguration error :\u003cnil\u003e respNonce: 40","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.listener.v3.Listener error :\u003cnil\u003e respNonce: 41","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.listener.v3.Listener error :\u003cnil\u003e respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.config.route.v3.RouteConfiguration error :\u003cnil\u003e respNonce: 39","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-webserver-certs in onConfigUpdate()\" respNonce: 40","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"ResourceNamesSubscribe: [] ResourceNamesUnsubscribe: [] InitialResourceVersions: map[]","time":"2022-12-05T23:58:09Z"}
{"level":"info","msg":"StreamDeltaRequestFunc: typeUrl type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret error :code:13  message:\"Missing SDS resources for 62ab872c-038e-4311-90bc-74a77cda9f53-mtls-fps in onConfigUpdate()\" respNonce: 40","time":"2022-12-05T23:58:09Z"}

**Comment by AmitKatyal-Sophos** [comment]
@adisuissa , SDS error issue is still there. It is not resolved...I had mention the other issue where same resource was specified in the "subscribe" and "unsubscribe" was due to wrong logging.

For SDS error, you had suggested that we need to improve similar to RDS. That change is still required right ?

**Comment by adisuissa** [comment]
Ok, thanks, reopening.

**Comment by AmitKatyal-Sophos** [comment]
@adisuissa I could see that you have tagged the bug with beginner category, Hence assuming that change is straight forward. Could you please share the reference PR for the similar changes done for any of other resource type listener/route/cluster, or delta stream design doc so that I can go through it once before deciding if I will be able to contribute here.

**Comment by adisuissa** [comment]
The reference code is what you already linked above (here is the entire [function]( https://github.com/envoyproxy/envoy/blob/5b9183f80d6c7ab38877b8f8f48b152509f49d3e/source/common/rds/rds_route_config_subscription.cc#L120-L134)).

**Comment by siddharthkhonde** [comment]
hi. is this still open? I can take a look into this as a beginner.

**Comment by keithmattix** [comment]
@htuch I've started work on this; feels like this might be as simple as not erroring if `len(removed_resources) + len(added_resources) > 0`?

**Comment by adisuissa** [comment]
Hey @keithmattix , thanks for tackling this issue.
I suggest looking at #24492, as there were some comments on the proposed solution.
