### ISSUE TITLE
Where to specificity V8 Runtime flags?

### ISSUE THREAD

**Issue by jlb6740** [envoyproxy/envoy#24399]
v8 has a number of options that are enabled via runtime flags. Is there any way to pass these flags (or flags for a different runtime such as wasmtime) to a prebuilt envoy when envoy is invoked, or are runtime flags for Wasm VMs only based on those baked in when building? If the later .. where are these flags baked in/where can they be modified?

**Comment by alyssawilk** [comment]
cc @PiotrSikora @mathetake @lizan

**Comment by lizan** [comment]
What are runtime flags specifically you're looking at? If those need to be specified at build time look at v8.patch for V8. I'm not sure what is for wasmtime or wavm.

**Comment by jlb6740** [comment]
Thanks @lizan .. not sure how I lost track of this post. I was wanting to experiment with both build and runtime flags for v8. The v8.patch file seems to be specific to the v8 build and I assumed it is applying patches directly to the v8 repository downloaded from https://github.com/v8/v8 (actually https://chromium.googlesource.com/v8/v8). Looking at the patch seems to confirm that. That said, v8 is bought in not by envoy but by proxy-wasm-cpp-host which envoy brings in.  And I notice that proxy-wasm-cpp-host also has a v8.patch file that does a subset of what the v8.patch found in envoy does. Assuming the process for modifying the v8 build is to create a patch file for the v8 source and to replace the current v8.patch file, the question is which v8.patch am I replacing .. the one in envoy repo or the one in proxy-wasm-cpp-host?
