### ISSUE TITLE
float in protobuf.Struct will be parsed as string using YAML

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#24410]
*Title*: float in protobuf.Struct will be parsed as string using YAML

*Description*:

I'm trying to use float in bootstrap.node.metadata, but I found it will be parsed as string as the config_dump shows. After some digging, I think it's related to this PR https://github.com/envoyproxy/envoy/pull/9052. Though the message with explicit float type will be parsed normally, but the float in Struct will be parsed as string.

The config is like:
```yaml
node:
  id: the-id
  metadata:
    num: 20.5
```

*Repro steps*:

I added a test case to verify this: https://github.com/envoyproxy/envoy/compare/main...tony612:envoy:debug-float-md?expand=1#diff-fec0fdd470afff42b4530b291c34e6e9bf5164120d0d6afd8382055c984a44d2. The test will fail:
```
[2022-12-07 04:52:32.780][83726][debug][misc] [external/envoy/test/common/protobuf/utility_test.cc:1624] md, num: string_value: "20.5"

external/envoy/test/common/protobuf/utility_test.cc:1625: Failure
Value of: num_it->second.has_number_value()
  Actual: false
Expected: true
Stack trace:
  0x18ae448: Envoy::ProtobufUtilityTest_YamlLoadMetadataFloat_Test::TestBody()
  0x441e204: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x440ee94: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x43fa0e0: testing::Test::Run()
  0x43fabac: testing::TestInfo::Run()
... Google Test internal frames ...

external/envoy/test/common/protobuf/utility_test.cc:1626: Failure
Expected equality of these values:
  20.5
  num_it->second.number_value()
    Which is: 0
Stack trace:
  0x18ae590: Envoy::ProtobufUtilityTest_YamlLoadMetadataFloat_Test::TestBody()
  0x441e204: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x440ee94: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x43fa0e0: testing::Test::Run()
  0x43fabac: testing::TestInfo::Run()
... Google Test internal frames ...
```

I tried to fix this by checking if the leading char is `0`: https://github.com/envoyproxy/envoy/compare/main...tony612:envoy:debug-float-md?expand=1#diff-83c3505d45397175accd4fce9a905b3c0332290283f769c6dca9f18c00d86608, so we can distinguish `08123`(string) and `8123.1`(float).

If this is indeed a bug and the solution is confirmed, I can send a PR.

**Comment by tony612** [comment]
But then I found only checking `0` is not enough because `+08xxx` and `-8xxx`(and for `09`, both are not numbers) are still string in YAML, but can be converted to double using `YAML::convert`. We can also check both the special cases(like `-0` and `+0`), but I'm wondering if there's a better way 🤔 .

**Comment by alyssawilk** [comment]
cc @adisuissa @htuch

**Comment by tony612** [comment]
@adisuissa We don't need to distinguish int and double in `loadFromYaml`. They are all `number` of `ProtobufWkt::Value` and then we rely on `json` & `protobuf` to parse them to the correct type: int/double(for non-`Struct`) or double(number in `Struct`) in pb. But I do think it's a problem to not distinguish `double` and `string` for `google.protobuf.Struct`. `20.5` is obviously a number instead of a string in YAML and should be `number` in `Struct`.

I'm afraid I have to use YAML because I use YAML to write the Envoy config file and it's difficult for our team to change. And `metadata` in `bootstrap` uses `google.protobuf.Struct`, so we can't use the non-Struct pb message either.

**Comment by tony612** [comment]
ping @alyssawilk @adisuissa

**Comment by tony612** [comment]
@alyssawilk @adisuissa Any new idea?

**Comment by adisuissa** [comment]
I think this can be added, and suggest guarding it with a runtime flag.

**Comment by tony612** [comment]
I'll handle this later(busy with others recently).

**Comment by tony612** [comment]
More notes for people who may hit this problem:

I invested this a bit more. And found the reason [this fuzz](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18977) test failed is YAML spec changes after 1.2. [int of YAML 1.1 spec](https://yaml.org/type/int.html) uses `0[0-7_]+` to represent octal, and 08xx and 09xx is regarded as string. But in [YAML 1.2](https://yaml.org/spec/1.2.2/#1032-tag-resolution), it uses `0o [0-7]+`. But it seems many languages and tools only support `0[0-7_]+` instead of `0o [0-7]+` for octal numbers.

So if we need to return the correct result in `parseYamlNode`, we need to handle some special cases, like `08xxx`, `09xxx`, `[-+]?0\d+\.\d+`, and so on. That will be a little verbose for YAML parsing in Envoy. So I think we can ignore this now until we find a better way.
