### ISSUE TITLE
Add a http filter  to pass the absolute URL to the upstream service

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#24415]
The original issue is reported by #13435 .
In that issue, someone use a LUA script to solve the problem. 
Is it possible to use a HTTP filter to do the same thing as LUA script does ? 
If it is reasonable to use a new HTTP filter, I will add the code for this kind of http filter.

**Comment by alyssawilk** [comment]
There's no current filter which does this.  I would suggest instead of adding a filter, that you add an option to the upstream  codec config, and use that setting here:
https://github.com/envoyproxy/envoy/blob/main/source/common/http/http1/codec_impl.cc#L453

**Comment by zhangbo1882** [comment]
Thanks @alyssawilk

**Comment by sinharaksh1t** [comment]
Looks like this post got closed in December of last year but no PR/commit was referenced in the close message. @zhangbo1882 was this already done or did you decide not to go forward with it?
