### ISSUE TITLE
Envoy/RateLimit - Memory Leak

### ISSUE THREAD

**Issue by GGDEAJ** [envoyproxy/envoy#24420]
Hello Guys,

We have a problem with memoryLeak Ratelimit. 

In the following configuration scenario;
- Application in AWS Fargate Service
  - 4 Task Definition - Each instance with 3072MB of memory and 1024MB of CPU
    - Within each task, we have 3 containers with storage distributed like this;
      - Envoy - 1536MB
      - Envoy/Ratelimit - 1024MB
        - To control the cache we use redis 
      - Datadog - 512MB

- Our **average request is ~50tps (transactions per second)**, at dawn we have several bachs running, so the volume is high.

Before we had a smaller configuration, but we had problems with the envoy/ratelimit server.

**We would like to know if we have a recommended configuration for the volume of requests?**

Regards.

**Comment by alyssawilk** [comment]
cc @mattklein123 @wbpcode

**Comment by mattklein123** [comment]
Sorry not much information to work with here. Please get heap profiles that will help us determine where the leak is coming from. https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/how_to_dump_heap_profile_of_envoy
