### ISSUE TITLE
Dont run (mobile) github actions (for required checks) if there is no need

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#24437]
In #24407 a change was made to not use the `paths` feature in github actions to exclude checks

this was done to ensure that the checks could be `required` for PRs to pass

the problem with this approach is that it pulls a full copy of the repo and is much slower than using githubs paths (which afaict uses its own diff algorithm against the target branch, and perhaps pre-checksout the repo - not sure about this exactly)

in more recent version of the github `actions/checkout` action the default is to pull the repo with a `depth` of 1, so the current `mobile/should_run_ci.sh` script, where it assumes that the full repo is checked out, breaks (this is easy enough to workaround but just hightlights the issue)

i think we can speed this up and reduce the load on CI considerably by reverting to using the `paths` selector and adding the github way of allowing a required check to pass when skipped (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

like the azp way its a bit kludgy but it think it would be quite a bit faster/more efficient

**Comment by phlax** [comment]
cc @jpsim @alyssawilk 

i was going to comment something similar on the PR but it landed before i had gotten round to reviewing it

**Comment by jpsim** [comment]
> i think we can speed this up and reduce the load on CI considerably by reverting to using the paths selector and adding the github way of allowing a required check to pass when skipped (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

Oh nice, I wasn't aware that this was possible.
