### ISSUE TITLE
server.cc considers tcp url with proper ipv6 address as malformated

### ISSUE THREAD

**Issue by yicding** [envoyproxy/envoy#24445]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Envoy fails to parse a tcp url with ipv6 address*

*Description*:
>This is the error:
[2022-12-07 22:32:19.399][8][critical][main] [source/server/server.cc:109] error initializing configuration '/var/lib/envoy/envoy.yaml': malformed url: tcp://[64:aaaa:bbbb:1000::1]:8080

The envoy version is 1.17.0

The related part of envoy.yaml is as below:
  - name: "app_lb"
    connect_timeout: "1s"
    type: "strict_dns"
    dns_lookup_family: "AUTO"
    lb_policy: "ring_hash"
    load_assignment:
      cluster_name: "app_lb"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "[64:aaaa:bbbb:1000::1]"
                port_value: 8080

**Comment by alyssawilk** [comment]
cc @envoyproxy/api-shepherds 
Can you try without the braces and see if that works?

**Comment by yicding** [comment]
> cc @envoyproxy/api-shepherds Can you try without the braces and see if that works?

It fails also. There is a related link:

https://github.com/envoyproxy/envoy/issues/10489

**Comment by yicding** [comment]
Is this a known issue on version 1.17.0?

**Comment by yicding** [comment]
I think method 

std::string hostFromUrl(const std::string& url, absl::string_view scheme,
                        absl::string_view scheme_name)

raises the malformed url exception. I did a UT on it and confirmed it.

Is this a known bug?

**Comment by soulxu** [comment]
This should fixed by https://github.com/envoyproxy/envoy/pull/21359/files
