### ISSUE TITLE
Move postgres_proxy filter to mainline extensions

### ISSUE THREAD

**Issue by kfaseela** [envoyproxy/envoy#24506]
We would like to use the postgres filter support provided by Envoy in production.
While the feature works nicely with standalone envoy, we are having trouble using the same via Istio. (see https://github.com/istio/istio/issues/42380)

For the EnvoyFilter to be supported in Istio, the filter has to be promoted to mainline extensions in Envoy.
Would like to know what does it take for promoting the same.
I think postgres has been in contrib for quite sometime, (https://github.com/envoyproxy/envoy/commits/0ce6cf5fc3b54185b068ac0b6ec2dd5e461fc3cb/api/contrib/envoy/extensions/filters/network/postgres_proxy) , hence would like to know the opinion about moving the same to mainline.

**Comment by kfaseela** [comment]
cc @cpakulski

**Comment by cpakulski** [comment]
I do not know what are exact criteria for accepting an extension to be part of the core code. postgres filter's security posture requires trusted upstream and downstream. Unit and integration tests are quite solid, but fuzz testing is missing. I would be happy to work on improving security posture (if required) and actual move of the code, but need to know the acceptance requirements.

**Comment by kfaseela** [comment]
@mattklein123 @ggreenway any suggestions on this? How do we get maintainers to sponsor?

**Comment by kyessenov** [comment]
@kfaseela Istio explicitly put postgres behind opt-in because there was a lack of interest from the maintainer of both projects to support postgres as a first-class end-user feature of the service mesh. If Istio can commit to delivering postgres, I think it's easier to find interest among Envoy maintainer for the code that would be widely used.

**Comment by kfaseela** [comment]
@kyessenov : many of the users of Istio do have customers who need postgres support. If envoy moves this out of contrib mode, it will be automatically pulled in by istio, helping us to use it via EnvoyFilter. Currently there is no plan to support via standard Istio APIs, but without being available as an EnvoyFilter atleast, Istio cannot make use of this feature to decide whether we would eventually want to mainstream it. So why not move out of contrib mode to help some of the Istio users like us?

**Comment by kyessenov** [comment]
@kfaseela I don't think we have a blockage in Istio here: we can modify Istio OSS to pull from contrib without issues. The reason for contrib is what I described: we need commitment for end-user adoption, with appropriate resources allocated. If it stays as contrib/EnvoyFilter combination, vendors are unlikely to provide support in this area (spoken while wearing my Googler hat).

**Comment by kfaseela** [comment]
> @kfaseela I don't think we have a blockage in Istio here: we can modify Istio OSS to pull from contrib without issues. The reason for contrib is what I described: we need commitment for end-user adoption, with appropriate resources allocated. If it stays as contrib/EnvoyFilter combination, vendors are unlikely to provide support in this area (spoken while wearing my Googler hat).

@kyessenov The current issue was raised here as a follow up to @ramaraochavali 's comment on https://github.com/istio/istio/issues/42380#issuecomment-1344368073 . So are you saying the EnvoyFilter should work with vanila Istio without the need to move this out of contrib?

**Comment by kyessenov** [comment]
I am referring to the fact that Istio can include Envoy contrib extensions into istio/proxy. Whether it should or not is a different matter.

**Comment by mattklein123** [comment]
Per @kyessenov I would raise this issue with the Istio project. Thank you.
