### ISSUE TITLE
`mobile_docs` job fails in CI on PRs from envoy branches

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#24526]
currently the `mobile_docs` job (deploy key step) checks for `!github.event.pull_request.head.repo.fork` to skip if its a PR

this doesnt work for PRs that are created from branches of the envoy repo (eg dependabot PRs which are all now failing this)

im not sure what the `github.event` has inside in this case but im wondering if we can use a +ve condition to only run on a `push` (rather than `pull_request` event)

**Comment by phlax** [comment]
cc @jpsim

**Comment by jpsim** [comment]
Making the SSH key & publish steps only run on `main` here: https://github.com/envoyproxy/envoy/pull/24539
