### ISSUE TITLE
!ENVOY_HOT_RESTART does not reference count across scopes

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2453]
From code inspection, I suspect that when we disable hot restart, two distinct stats scopes will not share underlying counter allocations for same name counters, e.g. "foo.bar" in scope A will not alias "foo.bar" in scope B. This is because when `!ENVOY_HOT_RESTART` we use `Stats::HeapRawStatDataAllocator` (https://github.com/envoyproxy/envoy/blob/dceb8cb557ee6f2dae52f33385b2c08600fea8bc/source/exe/main_common.cc#L65), which doesn't reference count (see https://github.com/envoyproxy/envoy/blob/master/source/common/stats/stats_impl.cc#L183).

This issue need to be first verified and if necessary we need to switch to a reference count backed allocator for `!ENVOY_HOT_RESTART` builds.

**Comment by mattklein123** [comment]
I'm removing the question label as this is definitely a bug when using the heap allocator in production.
