### ISSUE TITLE
python: pip_install deprecated

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#24547]
*Title*: *pip_install deprecated.*

*Description*:
I have started build on fresh Fedora 37 and can see error
> DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.

**Comment by phlax** [comment]
there is a reason that it hasnt been removed - see https://github.com/bazelbuild/rules_python/issues/899

at this point the dev setup doesnt work anyway (arggh!) so we may as well convert it and/or remove the dep it exposes

@sergey-safarov if you want to tack either this or the rust issue (#24548) i would be happy to review

**Comment by sergey-safarov** [comment]
I think need to update `bazel` on my PC.
I may hours used build dates 3 months ago. This maybe already fixed.
