### ISSUE TITLE
include_rustc_srcs deprecated

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#24548]
*Title*: *include_rustc_srcs deprecated*

*Description*:
I have started build on Fedora 37 and can see waring
> DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository
DEBUG: /root/.cache/bazel/_bazel_root/221703495c2e97a5482194eda3ea2f8b/external/rules_rust/rust/repositories.bzl:617:14: include_rustc_srcs is deprecated. Instead see https://bazelbuild.github.io/rules_rust/flatten.html#rust_analyzer_toolchain_repository

**Comment by phlax** [comment]
i have noticed this in CI also - the link doesnt work tho 8/ afaict there is no `rust_analyzer_toolchain_repository` on that page (other than links to it)

i think this link is more helpful https://bazelbuild.github.io/rules_rust/rust_analyzer.html#setup

**Comment by phlax** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
> i think this link is more helpful https://bazelbuild.github.io/rules_rust/rust_analyzer.html#setup

Per the link above, I think this could be fixed with:

```
load("@rules_rust//tools/rust_analyzer:deps.bzl", "rust_analyzer_dependencies")

rust_analyzer_dependencies()
```

But that's not something required for Wasm. It looks that @keith added it for Rust Analyzer support in IDEs.

**Comment by keith** [comment]
@snowp can you fix?

**Comment by sergey-safarov** [comment]
This may be because I use Bazel 3 month old.
i not have tested on current master.

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy/pull/24603
