### ISSUE TITLE
Integrate with OpenCensus stats collection and distributed tracing framework

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#2456]
Google just released [OpenCensus], which is (emphasis mine):

> A single distribution of libraries that automatically collects traces and metrics from your app, displays them locally, and sends them to any analysis tool.
>
>The key features of OpenCensus include:
>
> 1. **Standard wire protocols and consistent APIs for handling trace and metric data.**
> 2. A single set of libraries for many languages, including Java, C++, Go, .Net, Python, PHP, Node.js, Erlang, and Ruby.
> 3. **Included integrations with web and RPC frameworks, making traces and metrics available out of the box.**
> 4. **Included exporters for storage and analysis tools. Right now the list includes Zipkin, Prometheus, Jeager, Stackdriver, and SignalFx.**
> 5. Full open source availability for additional integrations and export options.
> 6. No additional server or daemon is required to support OpenCensus.
> 7. **In process debugging: an optional agent for displaying request and metrics data on instrumented hosts.**

This could potentially be a replacement for all the custom tracing frameworks we support in Envoy.

cc @mattklein123 @alyssawilk @htuch 

[OpenCensus]: http://opencensus.io/

**Comment by mattklein123** [comment]
@PiotrSikora I believe that OpenCensus trace driver support is already being started. I don't see us deleting the other trace providers (at least in the near term) but would love to provide this as an option.

**Comment by mpuncel** [comment]
I'm curious about the interest levels in this as well. Because OpenCensus defines the context propagation format, it seems like getting Envoy to play with that will be critical for anyone who wants to use OpenCensus

**Comment by htuch** [comment]
@bogdandrutu can you provide the latest thinking here FTR.

**Comment by mpuncel** [comment]
As a potentially smaller step supporting the OpenCensus binary trace context propagation format in the existing Zipkin tracer would be useful in contexts with a Zipkin-compatible backend

**Comment by mattklein123** [comment]
Marking help wanted. This should be a straightforward change to add a new OC trace driver.

**Comment by bogdandrutu** [comment]
@g-easy can you please take care of this?

**Comment by g-easy** [comment]
I have a prototype of an OpenCensus trace driver, I'll roll a PR soon.

**Comment by g-easy** [comment]
As per the update, the OpenCensus trace driver is in PR#5387. Please take a look. :)

**Comment by mattklein123** [comment]
I think this is done!
