### ISSUE TITLE
Negative case of upgrade_dependency_manager.validDecodeDependencies() is untested

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#24591]
[This](https://github.com/envoyproxy/envoy/blob/071455b3c7640cf3941640299fd807907bf2d592/source/extensions/filters/network/http_connection_manager/config.cc#L658) code path does not have tests in https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/network/http_connection_manager/config_test.cc

**Comment by shardulsrivastava** [comment]
if this issue is available, I would like to work on this.
