### ISSUE TITLE
EarlyHeaderMutationFactory error cases are untested

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#24590]
The error paths in EarlyHeaderMutationFactory [1](https://github.com/envoyproxy/envoy/blob/071455b3c7640cf3941640299fd807907bf2d592/source/extensions/filters/network/http_connection_manager/config.cc#L458) and [2](https://github.com/envoyproxy/envoy/blob/071455b3c7640cf3941640299fd807907bf2d592/source/extensions/filters/network/http_connection_manager/config.cc#L464) are untested and cause lower coverage number for HCM

Please add test cases in https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/network/http_connection_manager/config_test.cc to cover these conditions.

**Comment by yanavlasov** [comment]
Sample coverage report:
https://storage.googleapis.com/envoy-pr/8b95a67/coverage/source/extensions/filters/network/http_connection_manager/config.cc.gcov.html

**Comment by wbpcode** [comment]
get it. I will add tests this weekend.
