### ISSUE TITLE
build/mobile: RBE fails with arm64 versions of Bazel on macOS

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy#24605]
*Title*: build/mobile: RBE fails with arm64 versions of Bazel on macOS

*Description*:

When building something in the `mobile/` workspace with an arm64 bazel binary on an M1 Mac with RBE enabled, the `protoc` with the wrong architecture is attempted to be run, leading to [this error](https://envoy.cluster.engflow.com/invocation/30cc6fcc-8c30-46b0-b616-48af66cec8a9#console):

> sandbox-exec: execvp() of 'bazel-out/.../com_google_protobuf/protoc' failed: Bad CPU type in executable

*Repro steps*:

On an M1 Mac with EngFlow certs installed at `/path/to/certs/engflow.crt` and `/path/to/certs/engflow.key`:

```
git clone https://github.com/envoyproxy/envoy.git
cd envoy/mobile
./bazelw build \
  --tls_client_certificate=/path/to/certs/engflow.crt \
  --tls_client_key=/path/to/certs/engflow.key \
  --config remote-ci-macos \
  //library/common:envoy_main_interface_lib
```

The build succeeds if this line gets hardcoded to `amd64`: https://github.com/envoyproxy/envoy/blob/367763e5c63c003e495981e98fd9967bbcb86d20/mobile/bazelw#L16

*Admin and Stats Output*:

N/A

*Config*:

N/A

*Logs*:

N/A

*Call Stack*:

N/A

**Comment by phlax** [comment]
protoc (toolchains) was updated here #24546 - not sure if i made some mistake there
