### ISSUE TITLE
Add Envoy to bazelbuild CI

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2461]
We break frequently as Bazel releases roll out. I learnt from recent issues (#4474) that TensorFlow is built under Bazel CI. Looks like we can self-service add our own custom jobs at https://github.com/bazelbuild/continuous-integration/blob/master/docs/owner.md. Opening this issue to track future work here.

@jmillikin-stripe

**Comment by lberki** [comment]
For the record, this is the classical way to make sure that our releases don't break you. It'll probably result in us asking to make changes to your code as we check in incompatible changes, but that's a better place to be at than dumping a month's worth of incompatible changes on you at once.

**Comment by buchgr** [comment]
https://github.com/bazelbuild/continuous-integration/issues/218

**Comment by keith** [comment]
Here's the first step of the config https://github.com/envoyproxy/envoy/pull/6938

**Comment by mattklein123** [comment]
Done
