### ISSUE TITLE
util: ObjectSharedPool will fail on hash collision

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#24617]
When @zyfjeff wrote this @htuch commented:

@[htuch](https://github.com/htuch) htuch [on Mar 6, 2020](https://github.com/envoyproxy/envoy/pull/10042#discussion_r389131531)
Is hashing sufficient here (in the absence of a crypto strong hash)? Should we have hash followed by an equality comparison?

Member
Author
@[zyfjeff](https://github.com/zyfjeff) zyfjeff [on Mar 10, 2020](https://github.com/envoyproxy/envoy/pull/10042#discussion_r390675462)
Yes, there is a need to consider hash conflicts. let me open another PR to perfect here.

However there is still only a hash in this container; no compare.

**Comment by rkscodes** [comment]
I would like to work on this issue, could you help me get started

**Comment by jmarantz** [comment]
Great! I think this should be straightforward. See https://github.com/envoyproxy/envoy/pull/10042/files/1e3af2a17145a5629c75fe9ef1876d747c603275#diff-8d6ae96b81f16d58e760540f3918006d4747d92942a5fae50ed8cea8d5ce7ed9R64

The object store is based on a map from a hash to an object. I am not sure why it wasn't easier to use a flat_hash_map instead, which would expect objects to be comparable instead of just being hashable. Maybe try just doing that? @zyfjeff do you know why it was not done this way in the first place?

To test this I'd store a custom object in the object-store, whose hasher returns 0 always, but has a functional comparison function. It is legal (though not performant) to put objects with those characteristics in a hash_map and it ought to work.

**Comment by rkscodes** [comment]
From the context what I got is, I should change HashFun{}() to flat_hash_map like this. 
```c++
  std::shared_ptr<T> getObject(const T& obj) {
    ASSERT(std::this_thread::get_id() == thread_id_);
    // auto hashed_value = HashFunc{}(obj);
    auto hashed_value = absl::flat_hash_map<size_t, std::weak_ptr<T>>{}(obj);
    auto object_it = object_pool_.find(hashed_value);
    if (object_it != object_pool_.end()) {
      auto lock_object = object_it->second.lock();
      if (lock_object) {
        return lock_object;
      }
    }
```
But `flat_hash_map` doesn't have call operator, so compile fails. How should I do it ?

**Comment by Pawan-Bishnoi** [comment]
> Should we have hash followed by an equality comparison?
@jmarantz I can't see a straightforward way to do the said equality check? 
obj does not seem to have any obvious comparison mechanism, does it 🤔

**Comment by jmarantz** [comment]
We should assume class T supports `operator==` and `operator!=` to make this all work. However the above code does not look correct to me.

You should probably read https://abseil.io/docs/cpp/guides/container as background to understand how the hash tables are used.

Thank you!

**Comment by jmarantz** [comment]
@rkscodes Based on the above you might need some help sorting out how to work this in C++ -- it looks like Pradeep may look at this as well.
