### ISSUE TITLE
Query - Original src listener filter per route

### ISSUE THREAD

**Issue by kumarjp** [envoyproxy/envoy#24616]
*Title*: *Original src listener filter per route*

*Description*:
Is it possible to configure a listener-filter, say for ex, original_source filter, for selected routes only, on Envoy.

**Comment by wbpcode** [comment]
Listener filter is executed before network filter. It's say, when the listener filter is running, there is no any route info.

So, answer is "it's impossible".

**Comment by kumarjp** [comment]
Thanks for the response, .. There is a http filter - envoy.filters.http.original_src, which serves the same purpose but per HTTP connection manager.. Probably, this is the closest i can get.  So, wanted to know if there's a similar one for Routes

**Comment by wbpcode** [comment]
> Thanks for the response, .. There is a http filter - envoy.filters.http.original_src, which serves the same purpose but per HTTP connection manager.. Probably, this is the closest i can get. So, wanted to know if there's a similar one for Routes

Per route http filter chain is not supported for know. See #20867.

But it's possible to make the `envoy.filters.http.original_src` route-level configurable.

**Comment by kumarjp** [comment]
Thanks.

> But it's possible indeed to make the envoy.filters.http.original_src route-level configurable.

Is it supported already or is it something to be implemented?  ( I see compressor per route was implemented recently)

**Comment by wbpcode** [comment]
> Thanks.
> 
> > But it's possible indeed to make the envoy.filters.http.original_src route-level configurable.
> 
> Is it supported already or is it something to be implemented? ( I see compressor per route was implemented recently)

Sorry, it's not implemented for now.

**Comment by kumarjp** [comment]
Thanks.
