### ISSUE TITLE
Question on license of envoy 1.3.0 dependencies

### ISSUE THREAD

**Issue by luisapace** [envoyproxy/envoy#2462]
I've a question on one of the envoy 1.3.0 dependencies: rapidjson  1.1.0 

It's license states: 

**_If you have downloaded a copy of the RapidJSON source code from Tencent, please note that RapidJSON source code is licensed under the MIT License, except for the third-party components listed below which are subject to different license terms.  Your integration of RapidJSON into your own projects may require compliance with the MIT License, as well as the other licenses applicable to the third-party components included within RapidJSON. To avoid the problematic JSON license in your own projects, it's sufficient to exclude the bin/jsonchecker/ directory, as it's the only code under the JSON license.
A copy of the MIT License is included in this file._** 

So my question is:  is the bin/jsonchecker/ directory included in the envoy 1.3.0 binary referenced as:

**_proxy/envoy-1.3.0.tg: 
size:2266298 
object_id:c10f7dcc-4010-4dfe-460a-250a0e1cde1 
sha: 45d667aa64a876ab857853b112f065a8800d3161_**     ?

Thanks.

**Comment by mattklein123** [comment]
@rshriram can you or someone else from IBM answer this? Thank you.

**Comment by rshriram** [comment]
Why ibm? 
Either way, Envoy was approved internally a year ago.

**Comment by mattklein123** [comment]
@rshriram because @luisapace works at IBM and has been emailing me. :)

**Comment by luisapace** [comment]
I'm sorry, but really I do not understand... if I've a question on a package written not by IBM by someone else, why do I have to write to IBM instead of the developers of that package?  Please let me know if you know the answer to my question or not. Thanks a lot for your time.

**Comment by rshriram** [comment]
Short answer: no.
Contents of bazel-envoy/external/com_github_tencent_rapidjson/bin/jsonchecker/ are
```
fail1.json   fail13.json  fail17.json  fail20.json  fail24.json  fail28.json  fail31.json  fail5.json   fail9.json   readme.txt   
fail10.json  fail14.json  fail18.json  fail21.json  fail25.json  fail29.json  fail32.json  fail6.json   pass1.json   
fail11.json  fail15.json  fail19.json  fail22.json  fail26.json  fail3.json   fail33.json  fail7.json   pass2.json   
fail12.json  fail16.json  fail2.json   fail23.json  fail27.json  fail30.json  fail4.json   fail8.json   pass3.json   
```

which are not part of envoy binary.

**Comment by luisapace** [comment]
Great, thanks a lot for your help!

**Comment by alyssawilk** [comment]
I think this answers your question so closing this off, but please reopen if I'm wrong!
