### ISSUE TITLE
slow start config makes few pods have no QPS for sometime.

### ISSUE THREAD

**Issue by anuragagarwal561994** [envoyproxy/envoy#24629]
*Title*: *slow start config issues on few pods*

*Description*:
So earlier before 1.22 there was a bug because of which the slow start was not working in most of the cases.

https://github.com/envoyproxy/envoy/issues/19526

Hence we have recently shifted to 1.24.

We are seeing much better improvements in the working of the config, but still sometimes there are few pods which doesn't behave like other pods.

Before upgrading:
<img width="1585" alt="Screenshot 2022-12-20 at 6 07 58 AM" src="https://user-images.githubusercontent.com/6075379/208554661-50c4cb90-0682-4048-9dd9-5fabc00f6a21.png">

From the above image you can see there are few pods at the bottom. They were coming up and down, because they were not given traffic and suddenly they were given a lot of traffic (this is my presumption). Since the RPM is recorded by the application metrics, I don't have those in a concrete since the application under sudden load doesn't yield metrics, hence I am monitoring using the CPU usages.

After upgrade and changing nothing else in the application or configuration:
<img width="1585" alt="Screenshot 2022-12-20 at 6 14 16 AM" src="https://user-images.githubusercontent.com/6075379/208555316-c505d0c3-1b7c-47d6-a32c-190cd38801b9.png">

We can see that it is still there but in a much less quantity.

<img width="1585" alt="Screenshot 2022-12-20 at 6 15 24 AM" src="https://user-images.githubusercontent.com/6075379/208555441-12040507-5327-4ba6-ba03-55abbc072aad.png">

On zooming further this is how the graphs look closely.

Wanted to understand if I am missing something, we have the default configuration only just that we have slow duration set to 180s

**Comment by mattklein123** [comment]
cc @nezdolik

**Comment by nezdolik** [comment]
@anuragagarwal561994 How many endpoints are there in the cluster? Slow start does not scale well with large number of endpoints, it is based on edf scheduler where hosts in slow start will have high deadline compared to regular hosts and picked up rarely. You could try to increase [min_weight_percent](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster-slowstartconfig), default is 10%. That would increase the weight of host in slow start up to a certain timepoint within slow start window and increase probability of host being selected by edf scheduler.

**Comment by altaiezior** [comment]
This was later resolved when the envoy was upgraded or it was some internal issue, but it works fine now. I am not sure when or how the issue got fixed
