### ISSUE TITLE
Please merge https://github.com/envoyproxy/envoy/pull/24302 into release 1.24

### ISSUE THREAD

**Issue by ceastman-r7** [envoyproxy/envoy#24632]
https://github.com/envoyproxy/envoy/pull/24302 was merged into main but can it be backported into release 1.24 so Istio can pick up the change sooner than later?

Thank you.

**Comment by phlax** [comment]
@ceastman-r7 if you wanted to raise a PR against the `release/v1.24` branch it can be considered for inclusion in next patch release

**Comment by ceastman-r7** [comment]
PR created: https://github.com/envoyproxy/envoy/pull/24851

**Comment by phlax** [comment]
fixed in #24851
