### ISSUE TITLE
Enable/disable Listerner

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#24676]
Now if a listener is added, a socket will be created. So that the TCP health check to the listener will always succeed.  Actually, sometimes there is no health upstream cluster. I do not want the TCP health check succeed in that situation. 
Is it possible to disable a listener ?

**Comment by snowp** [comment]
I don't know about any such mechanism via TCP health checking - the listener would have to close the socket and no longer be bound for a basic TCP health check to fail. Have you considered using a HTTP health check with the https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking-filter filter? That way you could specify that the health check response should be dependent on upstream health

**Comment by zhangbo1882** [comment]
HTTP health check is a solution. But in my case, client cannot use HTTP health check, it can only use TCP health check.
