### ISSUE TITLE
Local Rate Limit With Descriptors: Are tokens from default bucket consumed? 

### ISSUE THREAD

**Issue by diegomazine** [envoyproxy/envoy#24682]
*Title*: *Local Rate Limit With Descriptors: Are tokens from default bucket consumed?*

*Description*:

The docs about [Using rate limit descriptors for local rate limiting](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#config-http-filters-local-rate-limit) states that If there is no matching descriptor entries, the default token bucket is used:

> The local descriptor’s token bucket settings are then used to decide if the request should be rate limited or not depending on whether the local descriptor’s entries match the route’s rate limit actions descriptor entries. If there is no matching descriptor entries, the default token bucket is used.

It gives me the idea that no token would be consumed from the default token bucket if there is a match between the request and the descriptors. However looking at [this comment](https://github.com/envoyproxy/envoy/pull/20869#discussion_r857278484) and evaluating the Local Rate Limiter implementation source code, it looks like [tokens from global bucket are consumed for all requests](https://github.com/envoyproxy/envoy/blob/5ff90255dc64852a0d14d910ffa30eb070b510bc/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L173), even when descriptors match.

To confirm it, I have done some tests, as shown below:

- Global token bucket containing less tokens than the descriptor token bucket:

Envoy configuration:
<img width="943" alt="Envoy Configuration" src="https://user-images.githubusercontent.com/53839801/209372381-3b3b4e14-329b-49e8-bf68-fbc0044ed2ef.png">

Requests:
<img width="956" alt="Requests" src="https://user-images.githubusercontent.com/53839801/209376798-685437bb-35fc-4425-a2a3-d117853ca4dd.png">

In this scenario, although we have configured a rate limit of 5 requests each 30 seconds to client application `app1`, it was able to execute only one, since the global bucket was configured with 1 token each 30 seconds.

- Global token bucket containing more tokens than the descriptor token bucket:

Envoy configuration:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/53839801/209378302-be57ef76-bc5f-4278-b3fd-2c81283dc9e5.png">

Requests:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/53839801/209378549-8ff9f805-7079-43d8-8cf3-660e57a4372e.png">

In this scenario, the client application `app1` was able to execute 2 requests in 30 seconds as allowed by the descriptor rate limit, since the global bucket was configured with 10 tokens each 30 seconds.

Is my understanding correct? If so, maybe the documentation could let this behavior clearer.

In my personal opinion, it makes sense always consume a token from the global bucket, since the main function of the Rate Limit is not allowing more requests than the maximum supported by the endpoint. 

One more question. Considering a scenario where I need to guarantee throughput (requests per second) quotas per application, for example, application `app1` must have the right to make up to 10 requests each second, application `app2` must have the right to make up to 20 requests each second, and all other applications together, up to 100 requests each second. In this case, should I implement a custom local rate limit plugin or a custom global rate limit service?

Many thanks!
Diego

**Comment by diegomazine** [comment]
Giving a little bit more context. 

Since [global bucket tokens are burned before matching descriptors](https://github.com/envoyproxy/envoy/blob/5ff90255dc64852a0d14d910ffa30eb070b510bc/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L173), it is possible that all tokens from global buckets are consumed even when requests are rejected by overrides. E.g:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/53839801/210452493-605c12d8-c9c1-4e36-a36c-3c5b7ad292e0.png">

In this case, the default bucket is configured to receive 5 tokens each 30 seconds and overrides allowing 2 requests each 30 seconds from `app1` and `app2`.

If `app1` sends 5 requests in 30 seconds the first 2 requests are be allowed and the last 3 rejected, as expected.

Nevertheless, since all tokens from the default bucket are burned, requests from `app2` are rejected even when the configured limit is not reached.

<img width="2103" alt="image" src="https://user-images.githubusercontent.com/53839801/210453163-8fa8f5a9-60be-47b6-a054-4fc4f381c7b8.png">

**Comment by htuch** [comment]
@wbpcode @mattklein123

**Comment by wbpcode** [comment]
cc @diegomazine you are right. The logic of local limit is a little complex because the globle token and mutiple descriptor could be used. orz.

> Since [global bucket tokens are burned before matching descriptors](https://github.com/envoyproxy/envoy/blob/5ff90255dc64852a0d14d910ffa30eb070b510bc/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L173), it is possible that all tokens from global buckets are consumed even when requests are rejected by overrides.

right. do you have any ideal to optimize it?

**Comment by diegomazine** [comment]
Hi, @wbpcode! Many thanks for your answer.

I think that we could update the method [`LocalRateLimiterImpl::requestAllowed`](https://github.com/envoyproxy/envoy/blob/5ff90255dc64852a0d14d910ffa30eb070b510bc/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L168) to first match local descriptors (no changes on the sorting algorithm will be necessary), rejecting the request if there is no available token in the matching token buckets. Only then, the number of tokens in the default bucket is validated.

This way, no token from the default token bucket is burned if the request is reject because there is not enough tokens in the matching local descriptor’s token buckets.

**Comment by wbpcode** [comment]
> Hi, @wbpcode! Many thanks for your answer.
> 
> I think that we could update the method [`LocalRateLimiterImpl::requestAllowed`](https://github.com/envoyproxy/envoy/blob/5ff90255dc64852a0d14d910ffa30eb070b510bc/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L168) to first match local descriptors (no changes on the sorting algorithm will be necessary), rejecting the request if there is no available token in the matching token buckets. Only then, the number of tokens in the default bucket is validated.
> 
> This way, no token from the default token bucket is burned if the request is reject because there is not enough tokens in the matching local descriptor’s token buckets.

Then when the global token has a more strict limit, the tokens of local descriptors may be burned even if it's rejected by the global token. 🤔

**Comment by diegomazine** [comment]
I think I got your point. For example:

- Global Rate Limit: 1 request per second
- Descriptor A: 1 request per minute
- Descriptor B: 1 request per minute

If both, descriptors A and B, send simultaneous requests, one of them won't get another chance within that minute. Have I got that right?

Considering that might be valid scenarios that requires burning global tokens before tokens of local descriptors and vice versa, maybe the Local Rate Limit plugin should implement both strategies. By default, global tokens will be burned first.
But if necessary, the plugin might be configured to utilize a greedy strategy that burns tokens of local descriptors first.

**Comment by diegomazine** [comment]
I think I got your point. For example:

- Global Rate Limit: 1 request per second
- Descriptor A: 1 request per minute
- Descriptor B: 1 request per minute

If both, descriptors A and B, send simultaneous requests, one of them won't get another chance within that minute. Have I got it right?

Considering that might be valid scenarios that requires burning global tokens before tokens of local descriptors and vice versa, maybe the Local Rate Limit plugin should implement both strategies. By default, global tokens will be burned first. But, when necessary, the plugin might be configured to utilize a greedy strategy that burns tokens of local descriptors first.

**Comment by sschepens** [comment]
@wbpcode i don't think I get your point, does it actually make sense to have a global bucket smaller than descriptors? It's actually [recommended in the code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L174-L175) that global bucket should be large because it is always consumed.

**Comment by wbpcode** [comment]
> @wbpcode i don't think I get your point, does it actually make sense to have a global bucket smaller than descriptors? It's actually [recommended in the code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L174-L175) that global bucket should be large because it is always consumed.

Sounds reasonable to me. But it would be better to add a NOTE or warn to the end users' doc. I think it's a drawback of current design and implementation.

cc @diegomazine

**Comment by diegomazine** [comment]
Hi @wbpcode,

I have submitted the [PR](https://github.com/envoyproxy/envoy/pull/25139) that updates the local rate limit filter.

Thanks a lot,
Diego
