### ISSUE TITLE
Envoy is not resolving DNS with a wildcard

### ISSUE THREAD

**Issue by nitinmohan87** [envoyproxy/envoy#24694]
*Description*:
>What issue is being seen?

We have an upstream EKS cluster with DNS similar to [this bug fix](https://github.com/c-ares/c-ares/issues/457) in c-ares library (a CNAME record pointing to a wildcard DNS record). Envoy is returning a 503 UH ("no healthy upstream") when proxying requests to this upstream cluster.

Since Envoy uses the c-ares library for [DNS resolution](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/dns_resolution) we believe it could be that Envoy is not using this particular bug fix in the c-ares library which is causing DNS resolution to fail.

FYI - Envoy v1.17.x resolves the same DNS without any issues.

>Describe what should be happening instead of the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Envoy should resolve DNS for records pointing to a wildcard.

*Repro steps*:
* Setup an upstream with DNS similar to [this bug fix](https://github.com/c-ares/c-ares/issues/457) in c-ares library.
* Setup Envoy to proxy requests to this upstream
* Requests to this upstream will fail with 503 UH

*Config*:
* Envoy v1.23 (v.1.24 also has the same bug). We use Envoy through the [Emissary Ingress](https://www.getambassador.io/products/api-gateway) product which is built on Envoy.
* AWS EKS 1.24

*Logs*:
>Include the access logs and the Envoy logs.
```
ACCESS [2022-12-21T21:15:46.477Z] "GET /health-check HTTP/2" 503 UH 0 19 5 - "<IP>"
"curl/7.81.0" "4e84d5b6-a30c-4534-bd21-e1e1d43d35c7" "xxx.example.com" "-"
```
DNS setup
```
$ dig xxx.example.com

;; ANSWER SECTION:
xxx.example.com. 120 IN CNAME *.xxx.test.example.com. <-------------------- Notice the wildcard in the DNS
*.xxx.test.example.com. 150 IN CNAME xxx
xxx. 60 IN A <ip 1>
xxx. 60 IN A <ip 2>
xxx. 60 IN A <ip 3>
```

**Comment by snowp** [comment]
Seems like we're using c-ares version 1.18.1 which was released in 2021, so we probably just need to update c-ares to pick up this fix. Thanks for reporting!
