### ISSUE TITLE
Response Headers not propagated to the filter state when response is invalid

### ISSUE THREAD

**Issue by IssaAbuKalbein** [envoyproxy/envoy#24703]
According to the description of the propagate_response_headers config:
https://github.com/envoyproxy/envoy/blob/23eacb181632df5e7be61f00a09e78bdfc686482/api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#L104
We expect to have response headers saved to the downstream info filter state for consumption by the network filters in all cases, but I see in the implementation that in case of invalid response or end of stream the headers are not propagated:
https://github.com/envoyproxy/envoy/blob/23eacb181632df5e7be61f00a09e78bdfc686482/source/common/tcp_proxy/upstream.h#L173
Is there any reason not to propagate headers in all cases?
@kyessenov ?

**Comment by snowp** [comment]
This is probably just an omission, I can't imagine why we wouldn't want to make this available always. Marking as help wanted

**Comment by 0xquark** [comment]
Hi @snowp @IssaAbuKalbein, I would like to take this issue. Could you brief me a little on this? 
( btw Happy New year 🎉 )

**Comment by IssaAbuKalbein** [comment]
Hi @0xquark,
In the following method:
https://github.com/envoyproxy/envoy/blob/23eacb181632df5e7be61f00a09e78bdfc686482/source/common/tcp_proxy/upstream.h#L173
I suggest moving the call for "parent_.config_.propagateResponseHeaders" in line 177-178, because it is not called in case we have an invalid status code in response headers

**Comment by 0xquark** [comment]
Hey @IssaAbuKalbein Can you check if it's done correctly now? Yess, You are correct if we want to always propagate the headers, regardless of the validity of the response or the status of the stream, we can move the call to parent_.config_.propagateResponseHeaders outside of the if block.
