### ISSUE TITLE
Why L4 filters don't have callbacks to indicate socket is closing?

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#24708]
*Title*: *One line description*

*Description*:
L4 filters API is currently limited to:
onNewConnection, onData, onWrite

Is there a reason why a callback such as "onEndConnection" was not added (i.e before the socket is closing, but after reading/writing is done).

**Comment by snowp** [comment]
You can probably achieve something like this by hooking into the filter destructor, though not sure how that fits into with the timing of when the downstream socket is closed. I would guess nobody has had a use for it so far - is there a specific use case in mind?

**Comment by ohadvano** [comment]
An example use case would be sending an HTTP request to some external upstream to notify that a connection is about to terminate. I thought about using the destructor, but then I get a race condition between the external HTTP server receiving the request and the closing of the socket. I also thought about using using the "end_stream" flag. However in some cases it is never true for, example in case the stream is closed by RST or FIN packets.

**Comment by ohadvano** [comment]
@snowp do you know what would take to add this callback to the code? Should it go some pre discussions or simply submitting a PR and letting the community review would be sufficient?

**Comment by mattklein123** [comment]
This is already supported via:

https://github.com/envoyproxy/envoy/blob/317efa53c6add02fa9533fc8f93f10f590077dca/envoy/network/connection.h#L112

Which you can get to via:

https://github.com/envoyproxy/envoy/blob/317efa53c6add02fa9533fc8f93f10f590077dca/envoy/network/filter.h#L48

**Comment by ohadvano** [comment]
@mattklein123 I have considered this option, but in my particular case I would want to send an async HTTP request in this callback and wait for response before letting the socket close. Using something like the FilterStatus::Continue/StopIteration mechanism would help me solve this problem

**Comment by mattklein123** [comment]
> @mattklein123 I have considered this option, but in my particular case I would want to send an async HTTP request in this callback and wait for response before letting the socket close. Using something like the FilterStatus::Continue/StopIteration mechanism would help me solve this problem

I think this is going to be a large and complicated change, and I'm skeptical it's worth it. What is the use case for having to wait for the HTTP request to return? The socket is already closed.

**Comment by ohadvano** [comment]
@mattklein123 the server I am sending the HTTP request is the same client who initiated the TCP stream. I would like to inform that client with extra metadata information about why the connection will be closed, before it closes, so it can act correspondingly.

**Comment by mattklein123** [comment]
> @mattklein123 the server I am sending the HTTP request is the same client who initiated the TCP stream. I would like to inform that client with extra metadata information about why the connection will be closed, before it closes, so it can act correspondingly.

I think you would be much better off doing some type of tunneling and then pushing a message directly onto the main TCP stream. This type of out of band notification will never be 100% reliable, and as I already mentioned, the change to pause iteration during this type of event will be quite complicated and I don't think there is enough of a use case here to justify the work/risk.
