### ISSUE TITLE
add tests to catch data-plane-api compat regressions

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2471]
Related to https://github.com/envoyproxy/envoy/issues/2466.

This issue will track figuring out some basic sanity tests, much like envoy-filter-example, to help us catch these types of regressions. Some ideas so far:

1) Have an xDS regression test which works with a server (either Go or C++) which floats *behind* the SHA used for data-plane-api in main Envoy. 
2) Have a test in Envoy which loads certain proto descriptors by name (services, top level objects, etc.) with a very explicit warning that if any of them change compat is broken and to stop.
3) Some set of golden JSON/YAML files which need to load with stern warnings about compat. (To some extent I think our example configs are this. They all need to be converted to v2 which is tracked in https://github.com/envoyproxy/envoy/issues/2139).

I would recommend we do (2) immediately as its simple and think about (1) and (3).

cc @envoyproxy/maintainers

**Comment by ramaraochavali** [comment]
@mattklein123 do you still want to add tests for this given that we have added the validation at startup?

**Comment by mattklein123** [comment]
No I think we are good. I will close this. Thanks @ramaraochavali!
