### ISSUE TITLE
Does Envoy guarantee all headers fetch from the Lua/Wasm API to be lowercase?

### ISSUE THREAD

**Issue by RRobot-lm** [envoyproxy/envoy#24718]
AFAIK, from the implementation, it seems Envoy always converts the headers to lowercase in the API.

BTW, when using an API to get a single header value, like https://www.envoyproxy.io/docs/envoy/v1.24.1/configuration/http/http_filters/lua_filter#get, and there are multiple headers in the same name, which header will be guaranteed to be returned, the first or the last?

**Comment by snowp** [comment]
Looks like the lua get() API will combine all the header values for a single key with a , separator. The case of the key would be ignored, so multiple headers with the same case-insensitive name would be collected into one

**Comment by RRobot-lm** [comment]
I see. Can I submit a PR to update the doc about it?

BTW, concat all the values with `,` might not be good when handling headers like `Set-Cookie` which has per-header attributes. Is there a plan to add a new API to return all headers in one call?
