### ISSUE TITLE
Heap profiling not working on WSL2

### ISSUE THREAD

**Issue by VivekSubr** [envoyproxy/envoy#24717]
*Title*: *Heap profiling not working on WSL2*

*Description*:
Heap Profiling envoy on wsl2 yields results that pprof fails to read, with error: "Some binary filenames not available. Symbolization may be incomplete." 

*Repro steps*:
* clone envoy 
* build as stated in doc: bazel build --define tcmalloc=gperftools //source/exe:envoy-static
* run envoy, and dump heap profile via rest api:
curl -X POST http://localhost:15000/heapprofiler?enable=y
wait some time
curl -X POST http://localhost:15000/heapprofiler?enable=n

run pprof on output,
pprof -top envoy-static /var/log/envoy/envoy.prof.0001.heap

*Config*:
admin:
  address:
      socket_address: { address: 127.0.0.1, port_value: 15000 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_0

  clusters:
    - name: cluster_0
      connect_timeout: 30s
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 1447 }

*Logs*:
Attached

**Comment by VivekSubr** [comment]
[envoy.log](https://github.com/envoyproxy/envoy/files/10327253/envoy.log)

**Comment by snowp** [comment]
Are you seeing any of the symbols from the envoy binary being symbolicated? If no, does the binary contain symbols at all? 

Not sure who might be familiar with WSL2 + pprof, maybe one of @wrowe @keith @lizan ?

**Comment by VivekSubr** [comment]
No... attaching the heap profile. 

[envoy.prof.0001.zip](https://github.com/envoyproxy/envoy/files/10327670/envoy.prof.0001.zip)

**Comment by keith** [comment]
in that example it doesn't look like you're explicitly building with debug symbols, can you pass `-c dbg` and see if that helps?

**Comment by VivekSubr** [comment]
@keith 

It looks better with -c dbg, but still get the same error... I think it should be added to the example: https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md

Is this the complete profile? 
[envoy.prof.0001 (2).zip](https://github.com/envoyproxy/envoy/files/10345801/envoy.prof.0001.2.zip)

ivek@LAPTOP-7E1991MU:~$ pprof -text envoy-static envoy.prof.0001.heap
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
File: envoy-static
Type: inuse_space
Showing nodes accounting for 39.42kB, 100% of 39.42kB total
      flat  flat%   sum%        cum   cum%
   39.38kB 99.92% 99.92%    39.38kB 99.92%  [envoy-static]
    0.03kB 0.079%   100%    21.46kB 54.44%  [libc-2.31.so]
         0     0%   100%    19.26kB 48.87%  <unknown>
         0     0%   100%    27.46kB 69.66%  event_base_loop
         0     0%   100%    25.52kB 64.76%  event_persist_closure
         0     0%   100%    27.46kB 69.66%  event_process_active
         0     0%   100%    27.71kB 70.30%  event_process_active_single_queue

**Comment by VivekSubr** [comment]
@haoruolei - sorry, never could get this to work
