### ISSUE TITLE
idle time active health check

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#24729]
Now envoy can be configured with active health check for the upstream hosts periodically. If there are huge number of upstream hosts, the health check traffic will also become huge. 

Actually, if there is continuous traffic for an upstream host, there is no need to do health check for that host with a fixed frequency. 
Is it possible to do health check only when there is no correct business traffic response to that host?
For example, if there is no traffic for 1 second, then do active health check. If there is always traffic to the host (HTTP response 2xx), the host should be considered as healthy without active health check.

**Comment by htuch** [comment]
I'm not sure this solves the scalability problem of active HC in general, since it's really dependent on traffic patterns and a specific notion of upstream health. This is threading the line between outlier detection and active HC while removing much of the distinguishing advantages of active HC. It is a plausible optimization with these caveats. @mattklein123 ?

**Comment by mattklein123** [comment]
Yeah I have thought about an optimization like this, but it really depends on the use case and it would certainly need to be configurable. Without passive health checking configured it wouldn't work at all obviously. I will mark this help wanted.

**Comment by zhangbo1882** [comment]
I propose a PR https://github.com/envoyproxy/envoy/pull/24903. 
Can someone have an initial review to see whether the functionality works as expected ?
I will add test case code.

**Comment by spacewander** [comment]
Is this issue solved by #24903?

**Comment by mattklein123** [comment]
> Is this issue solved by https://github.com/envoyproxy/envoy/pull/24903?

Yes I think so, thanks.
