### ISSUE TITLE
gRPC ext_authz `status_on_error` behavior 

### ISSUE THREAD

**Issue by qixuan-li1** [envoyproxy/envoy#24748]
Hi folks, a question on `status_on_error` behavior for gRPC ext_authz. [The doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#:~:text=client%20request%20header.-,status_on_error,-(type.v3)) says it’s only effective when [there](https://github.com/envoyproxy/envoy/blob/357bf0016ffa0102ed1fc3c51687eb23b9d2305d/source/common/grpc/async_client_impl.cc#L279)’s a network error. However, from my local testing as well as the code here, it looks like it actually kicks in whenever the `grpc-status` header is non-Ok, which might not necessarily be network errors (e.g. `grpc-status` 13 means `internal_error`), is this expected?

**Comment by htuch** [comment]
I think so, I think the idea is it indicates there is some error in communications with the ext_authz server. It even looks like `deny_at_disable` uses this. @esmet @ggreenway @pradeepcrao for confirmation.

**Comment by ggreenway** [comment]
Yes, @htuch is correct. The docs are incorrect, and should be updated.
