### ISSUE TITLE
A proposal of cached health checker extension for Envoy.

### ISSUE THREAD

**Issue by hudayou** [envoyproxy/envoy#24757]
# Background
Envoy is an excellent Sidecar in the field of Service Mesh. The use of modern C++ guarantees its high performance, but also increases the difficulty for developers. Although Envoy also supports redis and thrift customized health checkers. It would be nice to have another custom health checker to enhance its flexibility. We introduce a proposal that allows Envoy to support a cached health checker extension to avoid aggressive and unnecessary health checks.

# Design
By adding the cached health checker extension for Envoy. Users can avoid aggressive and unnecessary health checks.

The specific architecture is as follows:

```
       +---------------------+
       | Envoy               |
       +---------------------+
       |    Singleton        |             psubscribe------------>+-----+
       | CachedHealthChecker +<--------------------------tls----->+REDIS+
       |    HealthStatusMap  |<------------pmessage               +-+---+
       +--------+------------+             get--------------------->+   ^
     OnInterval |            |                                          |set
       +--------+------------+                                +---------+---+
       | ActiveHealthCheck   |                                |HealthChecker|
       +---------------------+                                +-------------+
```

_Looking forward to your ideas/comments on this proposal!_ @mattklein123 @htuch @alyssawilk @lizan thanks.

**Comment by mattklein123** [comment]
Thanks for opening the tracking issue. There isn't enough information in here to comment much one way or the other as to the technical design and whether there will be support for adding this. A few high level questions:
1) Are you targeting this for contrib or core extension? I assume you have no sponsor for core so you are going for contrib? Can you clarify?
2) I skimmed the PR and a few high level comments: a) there is going to be little interest to bring in a new third party dep for redis. Envoy already supports Redis as a protocol so if we move forward with this we will want to use the built-in redis support for talking to redis.
3) Some type of caching system generally makes sense to me, but I would like to see a design that has pluggable caching implementations. Redis might be one, but perhaps someone could also built a gRPC API for example.
4) More fundamentally, is this even needed as opposed to just using EDS to push health state changes directly to each envoy node? It seems like your control plane could actually do all of this redis intregration and push the updates.
5) Please flesh out the overall design much more. It's not really clear to me how the system is primed, what the failure modes are, etc. I would recommend a more complete gdoc with your proposal.

Thanks

**Comment by hudayou** [comment]
1. Can you sponse us for this? Otherwise we can do self-sponsor extensions.
2. The builtin redis is specially designed for load balancing upstream redis servers, it is lacking support of pubsub and select command which is required by us.
https://github.com/envoyproxy/envoy/issues/4424
3. Yep, we can definitely allow more caching solutions to be plugged into it down the road.
4. EDS is good, but directly using a cache will require less indirection in between. We are not replacing EDS, it's just another extension like redis and thrift.
5. I'll do a gdoc a requested.
