### ISSUE TITLE
Metric to monitor the Happy Eyeballs behavior ?

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#24787]
Wondering if there is a way to monitor the Happy Eyeballs behavior... would this be useful information?
For example :
```
// 104.26.15.214:443 BLOCKED on FW //
// initial request //
dns_cache_impl.cc:109] cache miss for host 'dir.bg:443', posting to main thread
dns_cache_impl.cc:307] main thread resolve complete for host 'dir.bg:443': [104.26.15.214:0, 172.67.71.201:0, 104.26.14.214:0]
dns_cache_impl.cc:374] host 'dir.bg:443' address has changed from <empty> to 104.26.15.214:443

multi_connection_base_impl.cc:14] [C7] connections=3
happy_eyeballs_connection_impl.cc:25] C[7] address=0x4525bf03ef18
connection_impl.cc:924] [C8] connecting to 104.26.15.214:443
connection_impl.cc:943] [C8] connection in progress
// 300ms later //
connection_impl.cc:924] [C9] connecting to 172.67.71.201:443
connection_impl.cc:943] [C9] connection in progress
connection_impl.cc:683] [C9] connected


// 2nd request //
dns_cache_impl.cc:102] cache hit for host 'dir.bg:443'
multi_connection_base_impl.cc:14] [C30] connections=3
connection_impl.cc:924] [C31] connecting to 104.26.15.214:443
connection_impl.cc:943] [C31] connection in progress
// 300ms later //
connection_impl.cc:924] [C32] connecting to 172.67.71.201:443
connection_impl.cc:943] [C32] connection in progress
connection_impl.cc:683] [C32] connected
```

This results in envoy_upstream_cx_total counter increasing by 2 when in fact 4 connections are attempted.
Also /clusters shows only the cached host 104.26.15.214 while in fact all connections are established with 172.67.71.201.

Obviously I can log and parse the admin log but this is noisy and requires a lot or resources. 
Prometheus / Envoy AccessLog is preferable I guess.

BR,
Stoyan

**Comment by htuch** [comment]
@RyanTheOptimist @alyssawilk

**Comment by alyssawilk** [comment]
Hm, I agree it'd be useful to have a stat for happy eyeballs connection attempts but I'm not sure if it should be cx_total - the multiplexed connection code will kick off a number of connections but as soon as one is confirmed connected the others are torn down so only one is ever established. That said for non-happy eyeballs connections we do increment that counter for connections which never connect so I could go either way re separate stat or reused stat.  cc @mattklein123 @jmarantz for preference.
If we opt to use the same stat we'd just have to wire cx_total to the MultiConnectionBaseImpl, and increment where we schedule another attempt.
