### ISSUE TITLE
macOS build no longer works: symbol not found in flat namespace '_CFRelease'

### ISSUE THREAD

**Issue by jchadwick-buf** [envoyproxy/envoy#24782]
The current `main` build doesn't seem to work on my macOS setup. When I try to run envoy, I get this:

```
$ bazel run //:envoy
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_john/59b8940ae0b402595b2dfa1425c9a34a/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
INFO: Analyzed target //:envoy (848 packages loaded, 34812 targets configured).
INFO: Found 1 target...
INFO: From BazelWorkspaceStatusAction stable-status.txt:
error: No such remote 'origin'
Target //source/exe:envoy-static up-to-date:
  bazel-bin/source/exe/envoy-static
INFO: Elapsed time: 51.497s, Critical Path: 31.82s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/source/exe/envoy-static
dyld[61319]: symbol not found in flat namespace '_CFRelease'
```

I'm not sure what the last good revision is; if I just switch commits without fully clearing my bazel cache, the problem persists, but if I clear it, builds can take up to 6 hours, making it virtually impossible to test one revision less bisect. I believe it worked at 2681bddd3b1594606adaf2348b6b737939fbc274, but it's hard to know for sure. I'll try a build over there but I want to get this issue out here now since I have someone else saying they are able to reproduce it at `main`.

The specific machine is a MacBookPro18,2 (M1 Max MacBook Pro, 16-inch) with 32 GiB of RAM. It is running macOS Ventura 13.1 (22C65).

**Comment by keith** [comment]
Hrm I don't see this one on the same OS version and hardware. What version of Xcode are you using? Or are you using the command line tools only?

**Comment by jchadwick-buf** [comment]
Only command line tools.

I've made a best effort to bisect this and the first bad commit appears to be 9dcf001a68370d13a1110464234d46057fc0418f. Its parent, 2681bddd3b1594606adaf2348b6b737939fbc274, seems to work. This tracks as I am guessing it has something to do with the abseil changes, particularly around `-framework Foundation`. I don't really fully understand what's going on, though.

**Comment by keith** [comment]
You can try passing `--linkopt=-Wl,-framework,Foundation` as a workaround. I will see if I can repro

**Comment by jchadwick-buf** [comment]
Thanks, that indeed does make the build work again.

I'll be honest that I have no idea how to tell exactly what the problem is caused by, but I can at least say that one other person cloned Envoy and experienced the same issue. Is it possible that maybe something is wrong with Bazel's autodetection of when to add the Foundation framework? I'd put my money on this being an Apple Silicon issue if most people are still on Intel macs.

**Comment by keith** [comment]
So think I understand the issue now, but it's definitely more of a "how did this ever work" question. We can just link this framework always to fix this https://github.com/envoyproxy/envoy/pull/24802

**Comment by keith** [comment]
I think realistically the best solution would be to revert https://github.com/google/cctz/pull/237 and figure out the android issue, but at the moment I can't even reproduce the android issue 🙃
