### ISSUE TITLE
Trying to setup a multi-hop (multiple services) and having affinity using StatefulSession but 2nd hop not working

### ISSUE THREAD

**Issue by joseret** [envoyproxy/envoy#24804]
joseret-macbookpro3:~ joseret$ ~/.istioctl/bin/istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (9 proxies)

Flow is

curl -> ingress-gateway -> sess1-a -> service-b

curl  "http://sess1-a-test.ecom1.joecloudy.com/testcallseq?call1=http://service-b.sess1-a-ns/testcallseq"  --cookie "sess1-a-session-cookie,sess1-b-session-cookie,gateway-session-cookie" -b  sap-sow2-sess1-test-29 --cookie-jar sap-sow2-sess1-test-29 -s

Example always goes to the same sess1-a pod, but service-b a different pod gets used every time.
First one:
host:sess1-a-7dd975b77b-jnmcf
host:service-b-54544bfd47-6n24q

Second one:

host:sess1-a-7dd975b77b-jnmcf
host:service-b-54544bfd47-t5tln/Users/joseret/g/pso/sap2/sap-ariba-gke-provisioning/session-affinity/cookies/sess1-a.yaml

The code passes and save the cookie everytime, but noticed that even though the cookie is there, service-b generates a new one so that one is constantly changing

MTAuNzYuMi4xNTA6ODA4MA==

*Repro steps*:
call curl above and check that pods are the same

*Config*:
[Archive.zip](https://github.com/envoyproxy/envoy/files/10363487/Archive.zip)

*Logs*:

[zlogs.zip](https://github.com/envoyproxy/envoy/files/10363618/zlogs.zip)

>Include the access logs and the Envoy logs.

#HttpOnly_sess1-a-test.ecom1.joecloudy.com	FALSE	/	FALSE	1673043195	sess1-b-session-cookie	MTAuNzYuMi4xNTA6ODA4MA==
#HttpOnly_sess1-a-test.ecom1.joecloudy.com	FALSE	/	FALSE	1673043232	sess1-b-session-cookie	MTAuNzYuMC4xMTQ6ODA4MA==
#HttpOnly_sess1-a-test.ecom1.joecloudy.com	FALSE	/	FALSE	1673043253	sess1-b-session-cookie	MTAuNzYuMS4xMzI6ODA4MA=

logs show it goes in with one HASH and the response comes with a new one - not sure why:
**IN**

{
  "textPayload": "DEBUG:hello_app_v4:testcallseq-headers-detail[Cookie-gateway-session-cookie=MTAuNzYuMi4xNTE6ODA4MA==; sess1-a-session-cookie=MTAuNzYuMi4xNTE6ODA4MA==; sess1-b-session-cookie=MTAuNzYuMi4xNTA6ODA4MA==]",
  "insertId": "mt3aifc3q9mpeuhu",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "cluster_name": "istio-testing",
      "pod_name": "service-b-54544bfd47-6n24q",
      "project_id": "sandbox-test-364913",
      "container_name": "hello-app",
      "namespace_name": "sess1-a-ns",
      "location": "us-central1"
    }
  },
  "timestamp": "2023-01-06T22:10:52.604962426Z",
  "severity": "INFO",
  "labels": {
    "k8s-pod/service_istio_io/canonical-revision": "latest",
    "k8s-pod/pod-template-hash": "54544bfd47",
    "k8s-pod/service_istio_io/canonical-name": "service-b",
    "compute.googleapis.com/resource_name": "gke-istio-testing-nodepool-istio-5566a478-kmfw",
    "k8s-pod/security_istio_io/tlsMode": "istio",
    "k8s-pod/app": "service-b"
  },
  "logName": "projects/sandbox-test-364913/logs/stdout",
  "receiveTimestamp": "2023-01-06T22:10:57.415105313Z"
}

**OUT**
{
  "textPayload": "DEBUG:hello_app_v4:testcallseq-response-cookies-detail:value-[\"MTAuNzYuMS4xMzI6ODA4MA==\"]",
  "insertId": "6q8ot3yxlo937kyg",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "hello-app",
      "pod_name": "sess1-a-7dd975b77b-jnmcf",
      "location": "us-central1",
      "project_id": "sandbox-test-364913",
      "namespace_name": "sess1-a-ns",
      "cluster_name": "istio-testing"
    }
  },
  "timestamp": "2023-01-06T22:11:13.991105076Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-istio-testing-nodepool-istio-243760b8-llft",
    "k8s-pod/security_istio_io/tlsMode": "istio",
    "k8s-pod/service_istio_io/canonical-name": "sess1-a",
    "k8s-pod/service_istio_io/canonical-revision": "latest",
    "k8s-pod/pod-template-hash": "7dd975b77b",
    "k8s-pod/app": "sess1-a"
  },
  "logName": "projects/sandbox-test-364913/logs/stdout",
  "receiveTimestamp": "2023-01-06T22:11:17.389280895Z"
}

**Comment by joseret** [comment]
I tried changing filter to SIDECAR_OUTBOUND and that worked but not sure why.  Any pointers as to how to debug this and see without randomly trying is very appreciated.  if sess1-a has a hash will it keep it per upstream?  I will have to test with another service and call both from sess1-a (service-b and service-c) and they should stay the same

**Comment by htuch** [comment]
The configs are Istio, so you might find it easier to get direct support on their GH. If sharing Envoy configs, best to provide the Envoy YAML.

CC @wbpcode @cpakulski as code owners.

**Comment by wbpcode** [comment]
will the ` sess1-a` proxy the related cookie to the outbound sidecar of `sess1-a`?

**Comment by joseret** [comment]
Not automatically, the application is adding the appropriate cookies to the outbound request and capturing the response cookies and setting them in the application response
