### ISSUE TITLE
SDS secret config not usable for SNI based cert selection with more than two certificates

### ISSUE THREAD

**Issue by char8** [envoyproxy/envoy#24824]
*Title*: SDS secret config not usable for SNI based cert selection with more than two certificates

*Description*:
Related to #24483 which allows a `DownstreamTlsContext` to support multiple TLS certificates via the `tls_certificates` config, with the listener selecting a certificate on handshake based on SNI.

We're trying to use this feature with `tls_certificate_sds_secret_configs`, which according to the docs should support the same number and types of certificates as `tls_certificates`.

When configuring with more than 2 SDS secret configs this way, Envoy rejects the config with a validation error (because the proto has a [`max_items=2` rule](https://github.com/envoyproxy/envoy/blob/ffa7295273834e2c777b1464896397bb05c0f68a/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L258))

there doesn't seem to be another way to provide more than 2 certificates via SDS to a DownstreamTLSListener? The limit was added in https://github.com/envoyproxy/envoy/pull/16605 to only support an ECDSA and a RSA cert via SDS, is that still a limitation for certs provided via SDS or is the fix as simple as removing the validation rule?

*Repro steps*:
- Running `envoyproxy/envoy-dev:317efa53c6add02fa9533fc8f93f10f590077dca` (post the feature above being merged)
- Configure a Listener with a DownstreamTLSContext and more than 2 SDSSecretConfigs
- Rejected Update below (including invalid config)
```
[2023-01-09 11:39:28.992][1][warning][config] [source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) https_listener: Proto constraint validation failed (DownstreamTlsContextValidationError.CommonTlsContext: embedded message failed validation | caused by CommonTlsContextValidationError.TlsCertificateSdsSecretConfigs: value must contain no more than 2 item(s)): common_tls_context {
  tls_params {
    tls_minimum_protocol_version: TLSv1_2
    cipher_suites: "[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]"
    cipher_suites: "[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]"
    cipher_suites: "ECDHE-ECDSA-AES256-GCM-SHA384"
    cipher_suites: "ECDHE-RSA-AES256-GCM-SHA384"
    cipher_suites: "ECDHE-ECDSA-AES256-SHA"
    cipher_suites: "ECDHE-RSA-AES256-SHA"
  }
  alpn_protocols: "h2"
  alpn_protocols: "http/1.1"
  tls_certificate_sds_secret_configs {
    name: "AAAAAAAA-KEY_TYPE_RSA_2048-12"
    sds_config {
      ads {
      }
      resource_api_version: V3
    }
  }
  tls_certificate_sds_secret_configs {
    name: "BBBBBBBBB-KEY_TYPE_RSA_2048-6"
    sds_config {
      ads {
      }
      resource_api_version: V3
    }
  }
  tls_certificate_sds_secret_configs {
    name: "CCCCCCCC-b7f5"
    sds_config {
      ads {
      }
      resource_api_version: V3
    }
  }
}
```

**Comment by KBaichoo** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
@char8 I think that was an oversight in #24483 to not remove the `max_items=2` validation. But I (or someone) needs to validate that it works and add some test coverage for it.

**Comment by ggreenway** [comment]
cc @LuyaoZhong

**Comment by LuyaoZhong** [comment]
Yes, it was an oversignt. 
@char8 Thanks for validating and pointing the bug.
@ggreenway Are you already working on this?

**Comment by LuyaoZhong** [comment]
@ggreenway I submit a PR to fix this issue, if you already have any code we can merge them.
