### ISSUE TITLE
Custom tags in tracing can not be applyed to upstream span correctly

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#24847]
*Title*: *Custom tags in tracing can not be applyed to upstream span correctly*

*Description*:
Custom tags in tracing support request_header and metadata,  and the value of both request_header and metadata are obtained from stream info of filter manager, but upstream span try to obtain these values from upstram stream info, which will cause custom tags in tracing can not be applyed to upstream span correctly.
https://github.com/envoyproxy/envoy/blob/829ed5d51fb27ccf83ed3acd0309037f4c9fc1ac/source/common/router/upstream_request.cc#L162

**Comment by wbpcode** [comment]
IMO, It's expected behaviour. And considering the upstream http filters, it's possbile the upstream stream info will contains upstream specific metadata. 🤔
