### ISSUE TITLE
connect to shared http data stream

### ISSUE THREAD

**Issue by klokane** [envoyproxy/envoy#24869]
*Title*: *http filter which allows "connect to shared datastream". *

*Description*:
We have some continuous data stream which comes from upstream via http(s).
We would like to provide some kind service for downstream which allows share same data among more downstream connections.

How it should work:

* client connects to envoy asking for some http(s) endpoint(path)
* Envoy will check if there is already upstream connection 
  * if not, envoy will connect upstream
  * once upstream is connected, filter will start send stream to client
* if there is another client connection to same endpoint, envoy instead of creating new upstream connection will attach to already created connection and will send same data for both streams
* upstream connection should exists until last client is connected

We've created some concept, based on `StreamFilter` but there is folowing problem: all client connections are finished when very first client disconnect. It seems problem is related to `Router`. 
It seem we need some kind of independent upstream connection which will be connected by individual Filters.

Can I please for some hint how to implement this idea?

**Comment by KBaichoo** [comment]
When subsequent clients connect to the upstream is it expected that they send data? Or is the flow at that point from upstream -> downstream?

From what I understood:

I think one way you could do this is to have global state (or thread local to avoid need for locks) in your filter factory that registers <endpoint, async client wrapper> and have the filter terminate the request and if it finds an existing entry for a stream from that endpoint register to have the data from that stream be pushed to the corresponding downstream. You'd be using the AsyncClient to do the heavy lifting: https://github.com/envoyproxy/envoy/blob/8e06935e0e2740c39d6779be9312afe1566d3b04/source/common/http/async_client_impl.h#L87 

The wrapper on the async client will need to multiplex data as additional downstream connect.

**Comment by klokane** [comment]
> When subsequent clients connect to the upstream is it expected that they send data? Or is the flow at that point from upstream -> downstream?

Downstream is sending simple GET and then it expects to receive current data from upstream (no caching on way).
Like if you switch TV and you are listening to news from point where you connected.

> 
> From what I understood:
> 
> I think one way you could do this is to have global state (or thread local to avoid need for locks) in your filter factory that registers <endpoint, async client wrapper> and have the filter terminate the request and if it finds an existing entry for a stream from that endpoint register to have the data from that stream be pushed to the corresponding downstream. You'd be using the AsyncClient to do the heavy lifting:
> 
> https://github.com/envoyproxy/envoy/blob/8e06935e0e2740c39d6779be9312afe1566d3b04/source/common/http/async_client_impl.h#L87
> 
> The wrapper on the async client will need to multiplex data as additional downstream connect.

What I've to implement to be filter "terminate". Does it mean full functionality like Router has?

**Comment by KBaichoo** [comment]
I think your filter needs to stop the connection to upstream through the router (otherwise we'd start a new stream, you seem to instead want us to tee / connect to the existing stream if available). Instead it is using a AsyncClient stream to fetch the data which can be cloned to multiple downstreams. You probably don't need the full functionality of the router for this filter. 
> What I've to implement to be filter "terminate". Does it mean full functionality like Router has?

**Comment by klokane** [comment]
Yes, router is reason why all other clients are disconnected.
First idea was to implement filter in similar way like Http/Cache Filter. But instead of waiting for cache is full (it is unwanted behavior) we did simple logic

When client connect, filter check for existing connection, if not, pass it to router and send data back to client.
Once next client is connected, Filter realize, there is already connection to endpoint and instead of router it will connect to previous connection and push data to downstream in same way like Http/Cache does. But instead of serving data from cache it is sending same data which are received to first client.

It works fine, but unfortunately until first client (and its router) is still alive.

**Comment by klokane** [comment]
BTW, what about [DelegatingRoute](https://github.com/envoyproxy/envoy/blob/main/source/common/router/delegating_route_impl.h#L18)

It is totaly out, or can be there also possible way to implementation?

**Comment by klokane** [comment]
I'm looking how to utilize `AsyncClient` acording to your sugestion.
Is corect way how it is used in [RemoteDataFetcher::fetch()](https://github.com/envoyproxy/envoy/blob/main/source/common/config/remote_data_fetcher.cc#L32-L46)? via `Filter::.clusterManager()::getThreadLocalCluster()::httpAsyncClient()`

Or do we need to prepare and initialize AsyncClient by ourself?

What happen in case when `AsyncClient` will be created from first created `Filter::clusterManager()` and downstream connection will by finished. Will this AsyncClient continue in work? Cannot happen there that AsyncClient will be in invalid state and it will leads to segfault?

**Comment by KBaichoo** [comment]
The idea is that your filter ends up owning the `AsyncRequest` created from the `AsyncClient` for that given cluster. It will then be responsible for the lifetime of the AsyncRequest. I'm not sure if it's expected in your environment, but cluster draining, etc. would be an edge case to look out for.
> What happen in case when AsyncClient will be created from first created Filter::clusterManager() and downstream connection will be later finished. Will this AsyncClient continue in work?

**Comment by klokane** [comment]
Thank you for your idea, It seem, we move forward. But now there is one problem and we cannot find solution.
First Filter on `decodeHeaders()` is creating shared `Entry` with `AsynClient` but creating instance `AsyncClient` itself is delegated back to  `Filter` because it has access to `ClusterManager` which can create `AsynClient`

In filter factory we save reference to `Server::Configuration::FactoryContext` and later we use `ClusterManager`

Everyhing is working okay, until we send quic request. In given case will happen something strange.


In `Filter::decodeHeaders()` seems to be everything okay, but when we send via `Filter::decoder_callbacks_::dispatcher::post` request back to filter with request to create `AsynClient` we've got segfault.

Reason is that `Server::Configuration::FactoryContext&` si now invalid. In decodeHeaders() it is okay but later in method `createClient()` is reference invalid. I've checked `this` in both `decodeHeaders()` and `createClient()` and it is same.



It can happen that `Server::Configuration::FactoryContext` will change in the middle of request?
Optionaly, is there different way how can I get `ClusterManager` instance to ask it to create AsyncClient?

**Comment by klokane** [comment]
It seems, segfault was caused by some "forgotten" `unique_ptr<>` to another config which also make some manipulation with ClusterManager

**Comment by klokane** [comment]
So it didn't solve it. It is now crashing with lower frequency. 

There are still questions:
It can happen that Server::Configuration::FactoryContext will change in the middle of request?
Optionaly, is there different way how can I get ClusterManager instance to ask it to create AsyncClient?
