### ISSUE TITLE
Why is `uri` a required field for `server_uri` in the ExtAuthZ Proto? 

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#24898]
## Description

As per the [ExtAuthZ Filter Docs](https://github.com/envoyproxy/envoy/blob/8b01b009a50f0e07598fbf8d9f4f1335fe88896e/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L243) both the `uri` as well as `cluster` are marked as **REQUIRED**. [[Link]](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/http_uri.proto#envoy-v3-api-msg-config-core-v3-httpuri)

Why do we need an explicit `uri` if a `cluster` is being provided? I can't find any instances in the code where we are using `uri`. Could it be deprecated/removed to avoid the confusion?

**Comment by KBaichoo** [comment]
cc @ggreenway @pradeepcrao @esmet

**Comment by ggreenway** [comment]
I think in this case it's because it's re-using a proto message that used in multiple contexts, and this field was required in some other context when using this message. I agree it shouldn't be needed here.
