### ISSUE TITLE
Error while running the contrib/exe/envoy-static - init manager Server destroyed

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#24904]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Error while running the contrib/exe/envoy-static - init manager Server destroyed*

*Description*:
>The error that I get is:
command: **$(bazel info bazel-genfiles)/contrib/exe/envoy-static -c test.yaml -l debug**
**[2023-01-12 13:46:57.029][2263826][debug][init] [source/common/init/watcher_impl.cc:31] init manager Server destroyed
unable to bind domain socket with base_id=0, id=0, errno=98 (see --base-id option**)

**I started seeing this issue when I accidentally killed this process running on my unbuntu ec2 instance:**

bazel(envoy) --add-opens=java.base/java.lang=ALL-UNNAMED -Xverify:none -Djava.util.logging.config.file=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/4d40928dbf4a1c6d94f6e14b20916175/javalog.properties -Dcom.google.devtools.build.lib.util.LogHandlerQuerier.class=com.google.devtools.build.lib.util.SimpleLogHandler$HandlerQuerier -XX:-MaxFDLimit -Djava.library.path=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a/embedded_tools/jdk/lib/jli:/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a/embedded_tools/jdk/lib:/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a/embedded_tools/jdk/lib/server:/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a/ -Dfile.encoding=ISO-8859-1 -Xmx3g -jar /home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a/A-server.jar --max_idle_secs=10800 --noshutdown_on_low_sys_mem --connect_timeout_secs=30 --output_user_root=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude --install_base=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/install/9cd28912b0d383fd730bfe34d852618a --install_md5=9cd28912b0d383fd730bfe34d852618a --output_base=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/4d40928dbf4a1c6d94f6e14b20916175 --workspace_directory=/home/vishaldamgude/envoy --default_system_javabase= --failure_detail_out=/home/vishaldamgude/.cache/bazel/_bazel_vishaldamgude/4d40928dbf4a1c6d94f6e14b20916175/failure_detail.rawproto --expand_configs_in_place --idle_server_tasks --write_command_log --nowatchfs --nofatal_event_bus_exceptions --nowindows_enable_symlinks --client_debug=false --host_jvm_args=-Xmx3g --product_name=Bazel --option_sources=host_Ujvm_Uargs:**/home/vishaldamgude/envoy/.bazelrc**

It was working fine before I killed above process.I was testing the built envoy executable with this command $(bazel info bazel-genfiles)/contrib/exe/envoy-static -c test.yaml -l debug and Instead of killing this command's process, I killed the other one.
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by KBaichoo** [comment]
I think the problem is that you triggered the hot restart flow but it wasn't able to rebind as the `SOCKET_ERROR_ADDR_IN_USE` error (98 on Posix) occured: https://github.com/envoyproxy/envoy/blob/93e715e8639c7a88721d480d9b2d30c7e841c3d7/source/server/hot_restarting_base.cc#L63

Might be related to how the process was killed. cc @mattklein123

**Comment by VishalDamgude** [comment]
To resolve this issue, I cloned my forked repo in another folder and did fresh bazel build after running bazel clean --expunge. 
Now it's working fine.
We can close this one.
