### ISSUE TITLE
Overprovisioning factor is ignored when subset load balancing is enabled

### ISSUE THREAD

**Issue by michaelfinch** [envoyproxy/envoy#24916]
*Title*: *Overprovisioning factor is ignored when subset load balancing is enabled*

*Description*:
When subset load balancing is enabled on a cluster, the overprovisioning factor is ignored. For example, if a cluster has two endpoints in priority 0, one endpoint in priority 1, and the overprovisioning factor is 9999, traffic should not be routed to priority 1 if only one of the endpoints in priority 0 becomes unhealthy. This is not the behavior we're seeing. It appears that envoy continues to use the default overprovisioning factor of 140 in this case. Whenever less than 71% of our hosts in priority 0 are healthy, we see traffic spill over into priority 1. I've confirmed with some local tests (detailed below) that this only happens when subset load balancing is enabled. We also disable panic routing.

*Repro steps*:
The following steps use the attached docker-compose.yml file and envoy configurations to repro the issue. The basic setup is one downstream (aka client) and three upstreams that belong to a single cluster. upstream1 and upstream2 are priority 0, and upstream3 is priority 1. The test has subset load balancing enabled with fallback policy `ANY_ENDPOINT`, panic routing disabled, overprovisioning factor set to 9999, upstream1 and upstream3 passing health checks, and upstream2 failing health checks.

1. Start the containers
```
docker compose up
```
2. Confirm upstream1 and upstream3 are healthy, and upstream2 is unhealthy
```
$ > curl -s http://127.0.0.1:10000/clusters | grep some_service | grep -E "health|upstream|:prior"
some_service::172.21.0.4:11001::hostname::upstream1
some_service::172.21.0.4:11001::health_flags::healthy
some_service::172.21.0.4:11001::priority::0
some_service::172.21.0.5:12001::hostname::upstream2
some_service::172.21.0.5:12001::health_flags::/failed_active_hc
some_service::172.21.0.5:12001::priority::0
some_service::172.21.0.3:13001::hostname::upstream3
some_service::172.21.0.3:13001::health_flags::healthy
some_service::172.21.0.3:13001::priority::1
```
3. Send traffic to the client envoy, which will get proxied to the upstream cluster.
```
for i in {1..100}; do
  curl -s http://127.0.0.1:10001/ >/dev/null
done
```
4. Check how many requests went to each envoy
```
# client
$ > curl -s http://127.0.0.1:10000/stats | grep cluster.some_service.upstream_rq_total

# upstream1
$ > curl -s http://127.0.0.1:11000/stats | grep cluster.icanhazip.upstream_rq_total

# upstream2
$ > curl -s http://127.0.0.1:12000/stats | grep cluster.icanhazip.upstream_rq_total

# upstream3
$ > curl -s http://127.0.0.1:13000/stats | grep cluster.icanhazip.upstream_rq_total
```
5. You'll see that with overprovisioning_factor set to 9999 in client_config.yaml, upstream1 ***and*** upstream3 both receive traffic. This mirrors the bug we see in our production environment where the overprovisioning factor is being ignored.
6. You can comment out the subset load balancing config and rerun the test if you want to verify that the bug does not trigger in that scenario.

*Config*:
[docker-compose.txt](https://github.com/envoyproxy/envoy/files/10405109/docker-compose.txt)
[client_config.txt](https://github.com/envoyproxy/envoy/files/10405111/client_config.txt)
[upstream1_config.txt](https://github.com/envoyproxy/envoy/files/10405112/upstream1_config.txt)
[upstream2_config.txt](https://github.com/envoyproxy/envoy/files/10405113/upstream2_config.txt)
[upstream3_config.txt](https://github.com/envoyproxy/envoy/files/10405114/upstream3_config.txt)

**Comment by KBaichoo** [comment]
cc @zuercher @snowp

**Comment by michaelfinch** [comment]
help wanted
