### ISSUE TITLE
Does Envoy support open telemetry based metrics?

### ISSUE THREAD

**Issue by kiranmaiem** [envoyproxy/envoy#24925]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Does Envoy support open telemetry metrics?*

*Description*:
>Our product uses envoy and we don't have Prometheus in our solution. Our observability product accepts open telemetry-based metrics. Would like to know if envoy already supports metrics via open telemetry? if not is there any plan to support it in future?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by KBaichoo** [comment]
cc @itamarkam @yanavlasov

**Comment by moderation** [comment]
/cc @AlexanderEllis

You can use an OpenTelemetry collector to scrape metrics from Envoy end points. See https://opentelemetry.io/docs/collector/configuration/#receivers for config on the Otel side, and https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html?highlight=prometheus#get--stats?format=prometheus for the Envoy side

**Comment by phlax** [comment]
see also https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/opentelemetry

**Comment by kiranmaiem** [comment]
Thanks for the reply. We are also thinking of using OpenTelemetry collector in case there is no direct support in Envoy. Will try that path.
