### ISSUE TITLE
Question about Envoy consistent hash behaviour

### ISSUE THREAD

**Issue by k-raval** [envoyproxy/envoy#24930]
Hi,

I have a set of GRPC servers, lets name them S1, S2, S3. And a set of GRPC clients, lets name them C1, C2, C3. When a client sends something towards servers, we use the Istio/Envoy proxy to do hashing on a GRPC metadata (using trafficPolicy - LoadBalancer - consistentHash of Istio destination rule).

The metadata field on which we hash is a unique value mapping to one particular item. E.g. ItemA, ItemB and ItemC have 3 different unique values. My design is such that each item is being served by one particular server (either S1 or S2 or S3). My requirement is that when any client (whether C1 or C2 or C3) sends a message for a given item, because of hashing algo on a unique value corresponding to that item, they would end up selecting the same server. Idea is that client need not maintain the mapping of items to servers even though in the backend, we would like stickiness of item to a server as long as possible until there is change of hashing due to some event.

e.g. ItemA being served by S1. When C1 sends msg for itemA, it will include unique value X1 as metadata for hashing, which the hashing logic would route to S1. At the same time if C2 sends msg for itemA using the same unique value X1 as metadata for hashing then, it should also end up getting routed to S1. If S1 is no longer available, the hashing logic would start routing the itemA towards S2 or S3, one of them. That is fine. But now, all the clients independently should route the message for itemA towards the same new server. The client can also go down and come back up again and the same behaviour should continue.

I would like the opinion of the experts on whether Envoy hashing support this kind of behaviour ? Do you see it deviating for any particular scenario ? Do you propose any change in configuration to achieve this ?

Thanks in advance.

**Comment by yanavlasov** [comment]
Please take a look at the ring hash or maglev load balancers. https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash

**Comment by k-raval** [comment]
Thanks. 
The Istio consistentHash policy translates to Envoy using Ring hash. So, this question is about ring hash behaviour. 

More specifically, the question is about two different client programs running envoy ring hash algorithm selecting the same target server based on the hashing on a given unique input value.  Is there possibility that the way ring hash has organized the target server pool is different in two programs and hence for the same input, the chosen target could differ ?

**Comment by yanavlasov** [comment]
If two clients send the same hashing value they should be routed to the same endpoint. @snowp for any additional information.

**Comment by k-raval** [comment]
Hi @snowp , awaiting your comments.. thanks.

**Comment by snowp** [comment]
If two clients receive the same endpoint configuration then yeah they should always map to the same host given the same hash value - there is no random input that affects the routing in this case. It might be possible if the list of endpoints was sent in a different order that they are indexed differently in the ring, but I imagine that's under your control

The ring hash + maglev load balancers are designed for this use case where multiple instances should generally (assuming they agree on what hosts appear healthy) agree on load balancing decisions without coordination.
