### ISSUE TITLE
HTTP/2 request not logging DOWNSTREAM_WIRE_BYTES_SENT properly.

### ISSUE THREAD

**Issue by maheshkurund** [envoyproxy/envoy#24975]
*Title*: HTTP/2 request not logging *DOWNSTREAM_WIRE_BYTES_SENT* properly when the downloaded file size is more than the initial window size set by HTTP/2 client.

*Description*:
It is observed that envoy logs request info to access logs while it's still transferring data to downstream HTTP/2 stream and logs incorrect wire bytes. This happens when HTTP/2 client sets initial window size less than the response size.

For example, when the requested file size is 169K, and HTTP/2 client (e.g., nghttp) sets initial window size to 65K then it is observed that access logs will have *BYTES_SENT=169K* and *DOWNSTREAM_WIRE_BYTES_SENT=~65K*. If we request same file by setting the initial window size (>169K), we do see correct wire bytes logged in access logs.

**Comment by jtway** [comment]
@KBaichoo I'm trying to understand exactly why this happens. It does look like the code at least tries to send pending frames. However, it looks like the connection manager will call `doDeferredStreamDestroy()` is being called prior to the pending frames being sent, after all bytes have been read from the upstream.

**Comment by KBaichoo** [comment]
Hi, I suspect it is due to when the codec level stream dies / finishes encoding the stream vs when the HCM stream / filter manager log occurs. One fix might be having the HCM stream be moved to an inactive stream list and have the codec when the stream is fully encoded propagate to the HCM stream that is should be "reaped" (logged, destroyed)

**Comment by KBaichoo** [comment]
Working on fixing this

**Comment by jtway** [comment]
@KBaichoo I was wondering if we had any updates on this? It has proven to be a rather big issue for us.

**Comment by KBaichoo** [comment]
Hi @jtway 

I was working on other tasks as part of my employment. 

Here's a WIP PR for this issue: https://github.com/envoyproxy/envoy/pull/25393
