### ISSUE TITLE
mobile ci: cancel ongoing mobile ci jobs when a new SHA is pushed to a PR

### ISSUE THREAD

**Issue by Augustyniak** [envoyproxy/envoy#24982]
*Title*: *cancel ongoing mobile ci jobs when a new SHA is pushed to a PR*

*Description*:
Canceling ongoing CI jobs in the case of a new SHA being pushed to a given PR should help us the limit the usage of CI that's used to run mobile checks (quite a limited resource). It would be a nice chance no matter whether we decide to eventually run mobile CI checks (instead of returning early from them) or not. Github actions - which are currently used to coordinate mobile CI checks - have an API that should allow us to implement what we want here.

**Comment by Augustyniak** [comment]
cc @jpsim

**Comment by glokta1** [comment]
Hey, if @jpsim doesn't mind, can I have a go at this?
