### ISSUE TITLE
Sanitizing of X-Forwarded-For header

### ISSUE THREAD

**Issue by nbam-e** [envoyproxy/envoy#24999]
*Title*: *Sanitizing of X-Forwarded-For header*

*Description*:
I have some questions regarding remote address resolution and sanitizing.

1. The *custom header original IP detection extension* has a setting [`reject_with_status`](https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/http/original_ip_detection/custom_header/v3/custom_header.proto.html#envoy-v3-api-field-extensions-http-original-ip-detection-custom-header-v3-customheaderconfig-reject-with-status), which allows me to configure that the request should be blocked when the IP header is missing or invalid. The [xff](https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto) extension on the other hand does not appear to have this option. Is this something that is planned for the future or is there some other way you can achieve this behavior with Envoy when using xff (i.e. blocking the request when `X-Forwarded-For` is missing or the trusted entry contains an invalid value instead of implicitly defaulting to the direct remote address)?
2. Is there a way to make Envoy strip untrusted entries/addresses from the XFF header (i.e. entries to the left of the xff_num_trusted_hops-th address) before it is forwarded to the upstream? The [documentation about header sanitizing](https://www.envoyproxy.io/docs/envoy/v1.24.1/configuration/http/http_conn_man/header_sanitizing.html) vaguely mentions that Envoy will *potentially sanitize* the `x-forwarded-for` header, but from my experiments it seems Envoy always forwards the XFF header without any modifications (apart from the appended direct remote address in case of `use_remote_address: true`), e.g. `X-Forwarded-For: <garbage>, <spoofedAddress>` is passed to the upstream as `X-Forwarded-For: <garbage>, <spoofedAddress>, <directRemoteAddress>` (`with use_remote_address: true, xff_num_trusted_hops: 0`).

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/v1.24.1/configuration/http/http_conn_man/header_sanitizing.html
- https://www.envoyproxy.io/docs/envoy/v1.24.1/configuration/http/http_conn_man/headers.html#x-forwarded-for
- https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/http/original_ip_detection/custom_header/v3/custom_header.proto.html#envoy-v3-api-field-extensions-http-original-ip-detection-custom-header-v3-customheaderconfig-reject-with-status
- https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto

**Comment by yanavlasov** [comment]
There are no plans for make a change like this in xff extension. You can file a separate issue to request this change and someone may pick it up, but there is no guarantee that this will happen any time soon.

I do not think there is a way to make Envoy sanitize the xff header the way you need. You can create an extension to do it, i.e. LUA, or again, request a change in an Issue.
