### ISSUE TITLE
envoy_reloadable_features_cares_accept_nodata deprecation

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#25009]
Your change #21027 (DNS: allow propagating DNS responses with no records back to caller (#20890)) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @wanlill

**Comment by sgovinda-ub** [comment]
@KBaichoo  Can I work on this item next?

**Comment by KBaichoo** [comment]
SGTM, thanks @sgovinda-ub
