### ISSUE TITLE
TLS handshake failure with error "no matching filter chain found"

### ISSUE THREAD

**Issue by ZhiminXiang** [envoyproxy/envoy#25002]
I am debugging a TLS failure between my client and envoy (istio ingress gateway).

The error message I found in envoy is `no matching filter chain found`.

The tcpdump I did showed that after getting the TLS handshake ClientHello packet, envoy closed the TCP socket.
```
11	2.144963	1.2.3.4	4.3.2.1	TLSv1	446	Client Hello
12	2.144981	        4.3.2.1	1.2.3.4	TCP	66	443 → 40916 [ACK] Seq=1 Ack=381 Win=66688 Len=0 TSval=2096819372 TSecr=2429176381
13	2.145284	4.3.2.1	1.2.3.4	TCP	66	443 → 40916 [RST, ACK] Seq=1 Ack=381 Win=66688 Len=0 TSval=2096819372 TSecr=2429176381 (socket closed)
```
where we can assume 1.2.3.4 is the client IP and 4.3.2.1 is the envoy IP.

Here are the details of the ClientHello packet: https://gist.github.com/ZhiminXiang/0c6ba920e6ae628afbedc1718236a5b0

And here are the details of the envoy filter config: https://gist.github.com/ZhiminXiang/5cead1ddba88eaaa6f99a5234e095772

Could I get some help to identify if this is something wrong in our client side or some misconfiguration in envoy?

**Comment by ggreenway** [comment]
`no matching filter chain found` indicates that envoy couldn't match this connection to any of the filter-chains you configured on the listener (criteria in `filter_chain_match`). It's not a failure in the TLS handshake. 

Do you have the `tls_inspector` listener filter configured? If not, that's probably what is wrong.

**Comment by ZhiminXiang** [comment]
thanks for taking a look @ggreenway . Yes we do have tls_inspector listener filter configured as follow
```
"listenerFilters": [
            {
                "name": "envoy.filters.listener.tls_inspector",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
                }
            }
        ],
```

The [domain test-domain.example.com](https://gist.github.com/ZhiminXiang/0c6ba920e6ae628afbedc1718236a5b0#file-gistfile1-txt-L87) in the request matched the envoy [filterChainMatch](https://gist.github.com/ZhiminXiang/5cead1ddba88eaaa6f99a5234e095772#file-gistfile1-txt-L3). So I expected the envoy filter should be picked up.

**Comment by yanavlasov** [comment]
Can you post the entire listener config, please?

**Comment by ZhiminXiang** [comment]
@yanavlasov here is the entire listener config https://gist.github.com/ZhiminXiang/49104ba1d96d3f8ad2c00f2deb422f94. thanks for taking a look!

**Comment by yanavlasov** [comment]
The naming of proto fields looks weird. Envoy's proto fields do not use camelcase. How did you obtain it?

**Comment by ZhiminXiang** [comment]
Those listeners were generated by Istio. I dumped by running the `istioctl proxy-config listeners $POD --port 443  -n istio-system -o json`

**Comment by yanavlasov** [comment]
Config looks correct to me. I unfortunately do not have any other suggestions. You can ask on Istio forums as well, to see if someone can offer a suggestion.
