### ISSUE TITLE
envoy_reloadable_features_http_skip_adding_content_length_to_upgrade deprecation

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#25015]
Your change #21990 (http: Do not add content-length: 0 header to UPGRADE requests) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by yeongjukang** [comment]
@KBaichoo @yanavlasov 
Hi, Can I take this one?

**Comment by KBaichoo** [comment]
SGTM feel free to create a PR @yeongjukang !

**Comment by yeongjukang** [comment]
@KBaichoo I made one! thanks.
