### ISSUE TITLE
envoy_reloadable_features_enable_compression_bomb_protection deprecation

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#25011]
Your change #733 (retry: retry immediately on 425 response code and H3 stream reset) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by danzh2010** [comment]
wrong runtime guard and PR number, should be https://github.com/envoyproxy/envoy/pull/19388.
