### ISSUE TITLE
envoy_reloadable_features_local_ratelimit_match_all_descriptors deprecation

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#25016]
Your change #20869 (local rate_limit support match multiple descriptors) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @StarryVae

**Comment by Pawan-Bishnoi** [comment]
If this is up for grabs, I would like to work on this.

**Comment by KBaichoo** [comment]
@Pawan-Bishnoi feel free to! It doesn't seem like @StarryVae has acked it yet.

/assign @Pawan-Bishnoi
