### ISSUE TITLE
envoy_reloadable_features_lua_respond_with_send_local_reply deprecation

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#25017]
Your change #21310 (lua respond with sendLocalReply) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @StarryVae

**Comment by sgovinda-ub** [comment]
@KBaichoo  Can  I work on this task?
