### ISSUE TITLE
Configurable setting of last trusted client IP address

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2503]
*Feature Proposal*:

Add a feature that allows Envoy to use the _N_ th external IP address from the end of X-Forwarded-For as the trusted client IP address, where _N_ defaults to 1 (for backward compatibility) but can be set in the Virtual Host configuration.

*Motivation*:

I have a use case where there may be two trusted proxies with non-RFC1918 addresses in front of Envoy. In that case, the trusted client IP address will be the _second_ external IP address from the end of X-Forwarded-For.

I also anticipate an edge-proxy deployment scenario where nothing in the XFF is trusted.

*Notes*:

I'm willing to contribute an implementation of this feature.

**Comment by mattklein123** [comment]
Sounds reasonable to me!
