### ISSUE TITLE
prometheus2 scrape envoy stats  show no token found , why did I do?

### ISSUE THREAD

**Issue by marsty** [envoyproxy/envoy#2505]
prometheus config
        metrics_path: /stats
        params:
          format: ['prometheus']
the prometheus targets show status down and error is no token found,I know the reason is the metrics format, but how did I do to  solve this problem ?

**Comment by zuercher** [comment]
Can you use curl (or similar) to query the stats endpoint on Envoy? Prometheus is very restrictive about metric names (they may only contain `[A-Za-z0-9:_]` and must start with `[A-Za-z_]`). I suspect one of your metrics has an illegal character that Envoy should be filtering out.

**Comment by marsty** [comment]
I use prom tool check the envoy stats (format prometheus) found that have the same name of the metrics envoy_listener_http_downstream_rq_xx{envoy_response_code_class="2",envoy_http_conn_manager_prefix="ingress_http",envoy_listener_address="0_0_0_0_80"} 0
# TYPE envoy_listener_http_downstream_rq_xx counter
envoy_listener_http_downstream_rq_xx{envoy_response_code_class="4",envoy_http_conn_manager_prefix="ingress_http",envoy_listener_address="0_0_0_0_80"} 4
how did I  change the name ?

**Comment by marsty** [comment]
I have solved, in another thinking of a solution
