### ISSUE TITLE
Breaking logging fields

### ISSUE THREAD

**Issue by DrumSergio** [envoyproxy/envoy#25071]
*Title*: *Breaking logging fields: FILTER_CHAIN_NAME, UPSTREAM_REMOTE_ADDRESS, UPSTREAM_PEER_SUBJECT*

I enabled many fields in the envoy logs (I'm using Ambassador in my cluster) but when I enable any of these fields, the container logs for requests that traverse the proxy are gone.

For instance, I can enable the field `BYTES_RECEIVED` with a key of `bytesReceived` so I can see the logs in Google Cloud Logs Explorer with the following query:

```
resource.type="k8s_container"
resource.labels.container_name="emissary-ingress"
jsonPayload.bytesReceived:*
```

But if I enable any field `FILTER_CHAIN_NAME`, `UPSTREAM_REMOTE_ADDRESS` or `UPSTREAM_PEER_SUBJECT` in my `envoy_log_format` all these logs are gone, even if I change the jsonPayload to a used field. 

I checked and they are indeed legal command operators: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators

I tried debugging the rest of the logs but I haven't found any useful data. It's simply becoming silent when I add any of those fields.

**Comment by yanavlasov** [comment]
It is possible that this is an issue with the Ambassador. If there is admin port enabled on Envoy you can check the config that was pushed to it and look for access log configuration.
