### ISSUE TITLE
Enable metadata sharing between tunnel filters and child filters

### ISSUE THREAD

**Issue by sebv** [envoyproxy/envoy#25086]
*Title*: *Enable metadata sharing between tunnel filters and child filters*

*Description*:

What  I have in mind corresponds to [the terminate_http_in_http2_connect example](https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http_in_http2_connect.yaml). The tunnel listener (`listener_0`) handles http2 requests (with headers), the CONNECT stream is upgraded so that several HTTP requests hit the `decap` internal listener. Because those are separate listeners, with separate filter chains, there is no way to transmit metadata between them (or maybe I am missing something). I would like to collect data from the tunnel http2 headers, set some metadata on the child filter chain, and re-add the headers to the subsequent child requests.

This is one scenario this would enable:
-  A remote workload is producing  HTTPS traffic that you want to intercept, but you don't want to expose the private key to the remote workload.
- The traffic is tunneled (HTTP2/connect)  adding headers to each HTTP2 tunnel request with information that is only available in the remote environment.
- egress gateway receives the tunnel requests, converts headers to metadata, upgrades the stream, and sends the HTTPS requests to an internal `decap` listener.
 - `decap` listener terminates HTTPS and examines the request.
 - The new mechanism would enable a Lua filter to retrieve metadata from the tunnel filter chain and use it to set headers in the child requests.

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk

**Comment by kyessenov** [comment]
This is solved with https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/internal_listener#internal-upstream-transport. Concretely, a filter state object in the tunnel listener marked as `SharedWithUpstreamConnection` is shared with the listener terminating the inner stream.

**Comment by sebv** [comment]
Great thanks! 

Trying to get this to work, Is there a sample config somewhere with:

```
typed_config:
  "@type": type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport
  passthrough_metadata:
  ...
```

**Comment by kyessenov** [comment]
I don't think there's on in this repo, but here's one in istio https://github.com/istio/proxy/blob/master/testdata/cluster/internal_outbound.yaml.tmpl.

**Comment by sebv** [comment]
It looks like only cluster and host metadata can be passed upstream in the current state, so there is probably still a gap there to generalize the functionality. I'll keep an eye on it thx.

**Comment by kyessenov** [comment]
@sebv Yes, that's right, route and request metadata haven't been implemented due to some internal framework limitations. Filter state is supported, and that can be used in place of request metadata.

**Comment by sebv** [comment]
[tunnel_filter_state.tgz](https://github.com/envoyproxy/envoy/files/10526017/tunnel_filter_state.tgz)

Attached is the setup I am using. Trying to pass the MY_CUSTOM_METADATA header into my_custom_meta upstream.

I think what I am missing is where you specify which tunnel state category/field you want to pass other. I don't seem to be able to put anything in `passthrough_metadata` other than cluster or host metadata because it is strongly typed.

**Comment by kyessenov** [comment]
From a quick look at your sample, you're using Lua which doesn't support the filter state out of the box unfortunately. Filter state is not the same as the request dynamic metadata (yes, it's pretty confusing). You might need to make a custom filter to write the filter state until either Lua starts supporting it, or the internal upstream support the request metadata passthrough.
