### ISSUE TITLE
API to edit internal data structure

### ISSUE THREAD

**Issue by lorenzogio97** [envoyproxy/envoy#25095]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

Title: API to read/write internal state of Envoy Proxy and filters
Description:
I'm currently doing my master thesis and I'm searching for some way to edit the state of Envoy Proxy and filters. 
The idea is to migrate a QUIC connection from one Envoy proxy to a new one, in order to simulate a client that moves in an edge computing environment. Regardless QUIC related issues (implement server migration), is there any way to edit internal data structure of envoy related to a QUIC connection? Some API?
Thank you for your help!

**Comment by RyanTheOptimist** [comment]
I don't believe there is any public API for accessing the QUIC connection internals. You could hack around the code in source/common/quic, or else look into the QUICHE code, but that's about it.

**Comment by lorenzogio97** [comment]
Thank you for the answer.
