### ISSUE TITLE
Dynamically decide upstream host in network filters

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25093]
In my setup I have two network filters in my filter chain:

- Custom network filter that in onNewConnection() has some logic to resolve a variable, say "dst"
- TcpProxy filter

I have an upstream that exposes many endpoints, for each option of the variable "dst". For example:

- x1.host.com
- x2.host.com

Is there currently an option in Envoy to dynamically select between x1/x2 based on the resolution of "dst"? Meaning that if "dst" is resolved to "x1" then the tcp proxy will be routed to x1.host.com, similarly if "dst" is resolved to "x2" then the routing will be to x2.host.com

Thanks for helping!

**Comment by RyanTheOptimist** [comment]
cc: @KBaichoo

**Comment by KBaichoo** [comment]
I think you can do dynamic cluster selection with tcp proxy: see https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter#dynamic-cluster-selection

**Comment by ohadvano** [comment]
@KBaichoo I didn't understand from the docs and the implementation what would be the value of the "cluster" field in the tcp proxy filter. Can you help with that?

**Comment by KBaichoo** [comment]
@ohadvano 

The key is defined here: https://github.com/envoyproxy/envoy/blob/ac91620f25b28fe83d9883757eb801171027fd19/source/common/tcp_proxy/tcp_proxy.cc#L41

And it is accessed here: https://github.com/envoyproxy/envoy/blob/ac91620f25b28fe83d9883757eb801171027fd19/source/common/tcp_proxy/tcp_proxy.cc#L156

I think you filter needs to `setData()` on the streamInfo on the Network connection using the given key with your filter to select the upstream: https://github.com/envoyproxy/envoy/blob/ac91620f25b28fe83d9883757eb801171027fd19/envoy/stream_info/filter_state.h#L130

**Comment by ohadvano** [comment]
I see, thanks. What if the clusters are unknown in advance and I would like to make use of the dynamic forward proxy cluster, could it work with that setup?

**Comment by kyessenov** [comment]
@ohadvano There are two mechanisms for unknown upstreams. DFP, like you said, which uses DNS to resolve a hostname. ORIGINAL_DST cluster which uses a known destination IP. For your use case, we use ORIGINAL_DST that programs it to use a header from :authority in HTTP CONNECT downstream, for example, in Istio.

**Comment by ohadvano** [comment]
Thanks @kyessenov, it seems like for using ORIGINAL_DST with override destination, I can either use http headers override or filter state override, but it seems like both can only be an IP address, can you confirm that?
