### ISSUE TITLE
How to genenrate compile_command.json

### ISSUE THREAD

**Issue by Nigelwz** [envoyproxy/envoy#25091]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
Can I know how to generate compile_command.json? 
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by suniltheta** [comment]
https://github.com/envoyproxy/envoy/blob/main/tools/vscode/README.md#refresh-compilation-database
