### ISSUE TITLE
hyperscan in envoy contrib compilation flags missing support for old CPU architectures

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#25099]
hyperscan can support older CPU architectures by using "FAT_RUNTIME": "on"
Was there a reason to NOT support all possible CPU architecture?

Follows an example patch info to add such support:

index 2baab304c9..e2cd395e3c 100644
--- a/contrib/hyperscan/matching/input_matchers/source/BUILD
+++ b/contrib/hyperscan/matching/input_matchers/source/BUILD
@@ -25,6 +25,7 @@ envoy_cmake(
         "BOOST_ROOT": "$EXT_BUILD_ROOT/external/org_boost",
         "BUILD_AVX512": "on",
         "BUILD_AVX512VBMI": "on",
+        "FAT_RUNTIME": "on",
         "BUILD_EXAMPLES": "off",
         "CMAKE_INSTALL_LIBDIR": "lib",
         "RAGEL": "$EXT_BUILD_DEPS/ragel/bin/ragel",

**Comment by RyanTheOptimist** [comment]
cc: @zhxie @soulxu

**Comment by zhxie** [comment]
From the [doc](http://intel.github.io/hyperscan/dev-reference/getting_started.html#cmake-configuration), fat runtime is enabled by default.

**Comment by sambercovici** [comment]
I also saw the documentation. 
Not sure why, envoy will not run on machines without minimum of avx2.
When explicitly turning this flag, envoy will also run on machines supporting sse3.

**Comment by sambercovici** [comment]
@ggreenway  and @zhxie 
Thanks you for the quick turnaround!
