### ISSUE TITLE
OpenTelemetry Tracer: Add spans_dropped metric.

### ISSUE THREAD

**Issue by DanTulovsky** [envoyproxy/envoy#25102]
*Title*: OpenTelemetry Tracer: Add spans_dropped metric.

*Description*:
There is currently a `envoy_tracing_opentelemetry_spans_sent` metric.  Please consider adding `envoy_tracing_opentelemetry_spans_dropped` as well. This would greatly help in understanding where the data is being dropped.

fwiw, I tried changing from the lightstep tracer (envoy version 1.23.3) to the otel-tracer (envoy version 1.24.1) and:

This is the number of spans received from envoy by Lightstep. You can see it goes down.

![image](https://user-images.githubusercontent.com/509887/214085587-9d597e47-1a04-4df8-b530-37607c01a60d.png)

On the other hand the numbers of spans envoy claims to emit is the same (here the dotted line is the lightstep tracer and it's time shifted by an hour. The purple line is the otel tracer. What's important is that they line up exactly:

![image](https://user-images.githubusercontent.com/509887/214085789-78a80273-b1b2-46c8-9382-80a1d888f50b.png)

And so it's not very clear to me where data is being dropped.

Additionally, it would be very useful to be able to change additional settings like:

- buffer size
- flush frequency
- compression (seems to be off right now and `OTEL_EXPORTER_OTLP_COMPRESSION` isn't [supported ](https://github.com/lalitb/opentelemetry-cpp/blob/main/exporters/otlp/README.md)?

I think this will help tune the exporter for various environments.  For example, this is the number of RPCs (not spans) that lightstep receives from the lightstep tracer  (blue line) and, after switch, the otel-tracer (purple line): 

![image](https://user-images.githubusercontent.com/509887/214086521-251ff8ee-ab74-4733-a96f-7f9d411caad8.png)

So more RPCs, but fewer spans.. :/

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
cc: @jmarantz

**Comment by bernardoVale** [comment]
Same problem here, seeing a lot of rx/tx resets. @DanTulovsky can you share how you tweaked `min_flush_spans` ?
