### ISSUE TITLE
Is it possible to partition Redis Cluster with Envoy?

### ISSUE THREAD

**Issue by simonasr** [envoyproxy/envoy#25100]
## Partitioning large Redis Cluster
We are currently approaching a scalability limits with one Redis cluster, which consists of ~700 nodes and a total dataset of ~3TB. 
To address this, we are exploring the possibility of partitioning the Redis cluster using Envoy proxy.
We have attempted to set up a configuration as follows:

```mermaid

flowchart TB
  node_3["Redis Client"]
  node_4["Envoy MAGLEV"]
  node_5["Redis cluster #35;1"]
  node_6["Redis cluster #35;2"]
  node_7["Redis cluster #35;3"]
  node_3 --> node_4
  node_4 --> node_5
  node_4 --> node_6
  node_4 --> node_7

```

While this setup does balance Redis keys across the clusters, majority of the Redis commands gets MOVED redirections 😔

Is it possible to set something like CLUSTER_PROVIDED lb_policy for each Redis cluster in use? 🤔

**Comment by RyanTheOptimist** [comment]
cc: @msukalski  @henryyyang @mattklein123 @weisisea

**Comment by simonasr** [comment]
As a workaround, the issue can be resolved through the implementation of the following configuration:
```mermaid
flowchart TB
  node_1["Redis client"]
  node_2["Envoy MAGLEV"]
  node_3["Envoy #35;1\nCLUSTER_PROVIDED LB"]
  node_4["Redis cluster #35;1"]
  node_5["Envoy #35;2\nCLUSTER_PROVIDED LB"]
  node_6["Redis cluster #35;2"]
  node_7["Envoy #35;n\nCLUSTER_PROVIDED LB"]
  node_8["Redis cluster #35;n"]
  node_1 --> node_2
  node_2 --> node_3
  node_3 --> node_4
  node_2 --> node_5
  node_5 --> node_6
  node_2 --> node_7
  node_7 --> node_8
```

However, this approach leads to increased complexity in configuration and potentially higher routing overhead.

It would be great to use MAGLEV or RING HASH load balancing directly with multiple Redis clusters as if they were single instances 🤞🏻
I am quite new to using Envoy, maybe there is a more convenient method to achieve this?

**Comment by mattklein123** [comment]
I'm not sure I fully understand the deployment and what you are trying to achieve. When you say "redis cluster" do you mean a redis operating in cluster mode? Or do you mean a group of redis hosts operating in standard sharding mode? Can you write something more detailed about what the problem is and what you are trying to achieve?

**Comment by simonasr** [comment]
Hi, thanks for the question! I'll try to explain.

We have a Redis Cluster (cluster-enable=yes) which consists of 768 nodes total.
To move forward we are exploring ways of splitting this large cluster into multiple ones (also cluster-enabled=yes) and distribute load and keys across them.

Here are three examples which we tried:
```mermaid
flowchart TB
  node_1["Client Example 1"]
  node_2["Envoy \nlb_policy MAGLEV"]
  node_3["Client Example 2"]
  node_4["Envoy\nlb_policy RING HASH"]
  node_5["Redis cluster #35;1\ncluster-enable=yes"]
  node_6["Redis cluster #35;2\ncluster-enable=yes"]
  node_7["Redis cluster #35;1\ncluster-enable=yes"]
  node_8["Redis cluster #35;2\ncluster-enable=yes"]
  node_9["Client Example 3"]
  node_10["Envoy\nlb_policy CLUSTER_PROVIDED"]
  node_11["Redis cluster #35;1\ncluster-enable=yes"]
  node_12["Redis cluster #35;2\ncluster-enable=yes"]
  node_1 --> node_2
  node_3 --> node_4
  node_4 --> node_5
  node_4 --> node_6
  node_2 --> node_7
  node_2 --> node_8
  node_9 --> node_10
  node_10 --> node_11
  node_10 --> node_12
```

The first and the second implementations successfully partitions keys across multiple Redis clusters, but Envoy does not cache the map between Redis keys and cluster nodes, resulting in a high number of MOVED redirections for commands received by the clusters.
The third example caches the map between keys and nodes and there is no MOVED redirections, but all the keys goes to one Redis cluster - partitioning (load balancing) does not work here.

Then we implemented the configuration described in my previous [comment](https://github.com/envoyproxy/envoy/issues/25100#issuecomment-1401563643). It uses the MAGLEV lb_policy for the load balancer, which routes traffic to multiple Redis Clusters. Each of these Redis clusters has an Envoy load balancer with the CLUSTER_PROVIDED lb_policy, which allows for caching of the map between keys and nodes. This configuration works as intended, but it seems that there may be a simpler way to achieve the same results.

I hope this explanation is clearer. Let me know if you have any further questions or require more information.

**Comment by mattklein123** [comment]
yeah I don't think we have anything like this built-in today. As a hack, you could use a single Envoy by looping back to the same Envoy to do the 2nd level of hashing? There is the new internal listener which could make this more efficient. That might be good enough for you to get going.

Building this directly into the redis cluster load balancer is possible but would be more work and would likely need some design thought.

**Comment by simonasr** [comment]
Thank you for your reply and your suggestion to use the internal listener. I did not know about the internal listener, but we will definitely give it a try instead of the currently used loopback IP address.

I hope that the feature will eventually be implemented directly into the Redis cluster balancer for more efficient and easier configuration in the future. Thank you again for your support.
