### ISSUE TITLE
local_ratelimit listener filter

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#25116]
*Title*: *local_ratelimit listener filter*

*Description*:
We saw CPU usage could be high if there's too many downstream connections which requesting handshake in a short period. Especially while a host is already busy, there downstream hosts could disconnect by timeout and connect again.

This is the perfect scenario of local rate limit. However, local rate_limit network filter is too late since the filter is involved after handshake.

Therefore, I'd like to move on a local_ratelimit listener filter.
Ideally we want to block too many handshake in a short period but I haven't seen through the implementation.
A possible way is to count all `onAccept` no matter whether it is TLS.
Next step could limit on the `requestedApplicationProtocols` or `detectedTransportProtocol` from `tls_inspector`

cc local ratelimit codeowners @mattklein123 @wbpcode

**Comment by mattklein123** [comment]
Yeah this makes sense to me.
