### ISSUE TITLE
Latest Envoy on Centos 7

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#25127]
looking at https://github.com/envoyproxy/envoy/issues/22365 it looks like latest envoy can't be trivially compile on centos.
trying to run envoy compiled on debian/ubuntu will fail since libc 2.29 or above is not available.

I was able to run latest envoy on centos7 with libc 2.29 compiled on cento 7 into $HOME/opt/glibc-2.29
1) copy envoy to $HOME
2) patchelf --set-interpreter ./opt/glibc-2.29/lib/ld-linux-x86-64.so.2 envoy
3) patchelf --set-rpath ./opt/glibc-2.29/lib:/usr/lib64 envoy
envoy was able to start and pass a few simple tests.

Did anyone try this out? 
Can this be an alternative way to support new envoy releases on centos 7 and centos 8?

**Comment by RyanTheOptimist** [comment]
cc: @phlax

**Comment by phlax** [comment]
>  Can this be an alternative way to support new envoy releases on centos 7 and centos 8?

i think using a custom glibc is a valid way to run Envoy on platforms that do not have a supported version - whether directly on the host, in a chroot, or in a container

personally i would consider using a container if at all possible - the distroless container, for example, has basically just that - ie envoy+glibc - but has a lot of other benefits baked in when compared to running directly on the host

**Comment by sambercovici** [comment]
Thanks!
Sadly, in this case there is no support for running containers on the target.

**Comment by sambercovici** [comment]
So going back to the question.
Would using an image compiled for ubuntu and patching to use a local libc be accepted as a deployment option for "bare metal" centos (7 or 8)?
I see similar challenges as centos7 for centos8
