### ISSUE TITLE
External Processor Filter can gain significant performance by reusing gRPC streams

### ISSUE THREAD

**Issue by tcohen01** [envoyproxy/envoy#25138]
*Title*: External Processor can gain significant performance improvements by reusing streams

*Description*:
Whenever ext_proc clients requests a new stream or closes an existing stream, it should be possible to replace the 'new stream' and 'close stream' operations with getting a stream from a worker-local pool and returning it to the pool.

For horizontal scaling purposes, the pool may close the streams during the get or return stream operations, possibly based on:
* How many transactions the stream handled
* How long it has lived for
* Invalidated by a change in gRPC or cluster configuration

This will greatly amortize the cost of creating and closing streams while not making changes to the API (the streams will still only handle one transaction at a time). 

*Note*: Might be recommended to implement this as a toggleable feature, as existing ext_proc service implementations may close streams in advances, and this could instead harm the performance for these services.

**Comment by tcohen01** [comment]
A couple notes:
* I've observed that coroutine based implementations like golang's and rust tonic's don't suffer as much from short lived streams, but cpp gRPC library is heavily affected by this.
  * Observed by creating dummy servers and benchmarking envoy against them with [hey](https://github.com/rakyll/hey)
* I worked on a dummy ext_proc client in rust and was able to get a significant RPS improvement when comparing stream reuse vs no stream reuse. 

  Since I don't have a project yet I do not want to give any numbers and accidentally oversell or undersell this feature.

  I plan to, sometime in the next two weeks, create a matching dummy server and upload it as a project to easily run benchmarks and compare the two.

**Comment by RyanTheOptimist** [comment]
cc: @snowp

**Comment by tcohen01** [comment]
Here's the test project: [ext_proc_tests](https://github.com/tcohen01/ext_proc_tests)

Around +90% to +120% performance improvement depending in an implementation, though this is a dummy client situation that tests the stream reuse as a main bottleneck. Serving 100 transactions per stream already alleviates the bottleneck.

The implementation in the filter will have some complications over the dummy client, particularly:
* What marks a new transaction? I suggest that RequestHeaders should always imply a new transaction.
* How to close a transaction without closing the stream - waiting for pending responses / ignoring pending responses
  * This could be further complicated if the API adds response types that don't have a 1-1 relation with requests. For example, streaming responses that send a replacement body that is too large to fit in a single gRPC message.
  * In case the server misbehaves due to a bug and doesn't send an expected response, how are the following responses handled? How do we know which response belongs to which transaction?

    Even with rust's correctness, this still poses a reliability issue without assigning transaction IDs and receiving them in the responses.

 I'd still like to see streams being reused, so transaction IDs could prove helpful as they would solve the latter point easily (silently ignoring responses with previous transaction ID,
