### ISSUE TITLE
Response code detail "rejecting_because_detection_failed" is not properly documented

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#25147]
The response code detail "rejecting_because_detection_failed" has a different/wrong name in the documentation: "original_ip_detection_failed".

References:
* Source code: https://github.com/envoyproxy/envoy/blob/main/envoy/stream_info/stream_info.h#L196
* Documentation: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/response_code_details

I think the name in the documentation is better, but I don't know whether the name in the source code can be changed (compatibility).

**Comment by RyanTheOptimist** [comment]
cc: @phlax

**Comment by phlax** [comment]
> I think the name in the documentation is better, but I don't know whether the name in the source code can be changed (compatibility).

i think updating the docs is definitely the easier path - do you want to PR an update @mkauf ?

**Comment by mkauf** [comment]
@phlax yes, I have created a PR.
