### ISSUE TITLE
Go HTTP Filter: fails with cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by mhofstetter** [envoyproxy/envoy#25178]
*Title*: *Go HTTP Filter: fails with cgo argument has Go pointer to Go pointer*

*Description*:
CGO calls from a [Go HTTP Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter) via C-API implementation are failing with `cgo argument has Go pointer to Go pointer` if string or slice arguments are directy passed to C via `unsafe.Pointer`. Due to the [cgo pointer check](https://github.com/golang/go/blob/master/src/runtime/cgocall.go#L393) which panics if Go pointers are detected - e.g. strings which have been created at runtime and aren't string literals. 

An example is the [C-API implementation](https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/source/go/pkg/http/capi_impl.go#L59) of `SendLocalReply` which fails when using it with a `body` which is created at runtime like in the [Go HTTP filter example](https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/test_data/echo/filter.go#L16-L17). The same error would occur for the string-slice `strs` if the headers map would contain an entry. 

I would expect, that all string & slice arguments in the C-API implementation are safe for the pointer check, by using `reflect.StringHeader` & `reflect.SliceHeader` (and passing `data` property as `unsafe.Pointer`) like it's done in other cases.

* `HttpSendLocalReply` -> `body_text`, `headers`, `details`
* `HttpGetHeader` -> `key`
* `HttpSetHeader` -> `key`, `value`
* `HttpRemoveHeader` -> `key`
* ...

**Comment by doujiang24** [comment]
@mhofstetter I don't think it's a bug, go HTTP filter is desired to work with the `GODEBUG=cgocheck=0` ENV variable, which disables the cgo pointer check.

cgo pointer check is used for normal cgo usage, those people don't know the cgo implementation deeply.

The go HTTP filter relies on cgo heavily, and we disable cgo pointer check for better performance and easier usage.
In exchange, we have to make sure cgo pointer safety manually.

I do think we could make sure those cgo pointers safety.

**Comment by mhofstetter** [comment]
@doujiang24 thanks for the clarification.

I'm aware of the `GODEBUG` env var to disable it completely - even though I didn't realized that this is the recommended setting when using Envoy with the Go HTTP filter. Might be worth to add this info to the documentation? Having a second look, I only found it in a [test setup](https://github.com/envoyproxy/envoy/blob/c256b948683b8bd800df80f69f470e1202510242/contrib/golang/filters/http/test/BUILD#L17) of the filter.

**Comment by doujiang24** [comment]
@mhofstetter Yep, it is worth a notification in the doc. I'll create a PR for it soon. Thanks.

**Comment by phlax** [comment]
Given that Envoy crashes if a user omits to set an env var (ie the default) i think this needs more than documentation

**Comment by doujiang24** [comment]
Yep, I'll create another PR to disable `cgocheck` by default in code.

**Comment by doujiang24** [comment]
I had a try, but changing the env in C++ doesn't take effect on the Go side.

Since Go only read the original env list - does not get the env list by using the C  `getenv` API, at least on the UNIX system.
And libc maintains its own env list storage, it may malloc new memory while changing env, so, Go does not honor the changes from C++.

It may need to add a new Go API on the Go side, to disable cgocheck. I'll ask the Go team's suggestion.

**Comment by phlax** [comment]
@doujiang24 ill keep this open for now as i think its still an issue (not sure)

**Comment by doujiang24** [comment]
@phlax  yep, I'll fix it, let's keep it open.

**Comment by spacewander** [comment]
A proposal has been submitted and let's wait for the Go team's reaction.
