### ISSUE TITLE
Remove java_generic_services option from service proto files

### ISSUE THREAD

**Issue by scrocquesel** [envoyproxy/envoy#25172]
*Title*: *Remove java_generic_services option from service proto files*

*Description*:
Since version 2.4.0 (2018) this option has been deprecated and such generated classes should not be used anymore (https://developers.google.com/protocol-buffers/docs/reference/java-generated?hl=en#service).
When using plugin that produce class with the same name, protoc complains about collision and failed.

Such plugins are provided by Quarkus gRPC Mutiny generator and it is not possible to generate Mutiny service from https://github.com/envoyproxy/java-control-plane/tree/main/api

**Comment by RyanTheOptimist** [comment]
cc: @mattklein123

**Comment by mattklein123** [comment]
cc @phlax. Seems fine to me.

**Comment by phlax** [comment]
this also makes sense to me - reading the links we probably do want to remove the service lines

my only apprehension is that afaict they are all/mostly set to `true`  - so removing means a change in current (deprecated) behaviour - im not clear if there is any impact from that

**Comment by phlax** [comment]
@scrocquesel if you wanted to PR the necessary changes we could at least see if it gets past CI and then i guess canvass some more opinions in terms of impact
