### ISSUE TITLE
Don't set x-forwarded-for header in Lua request handler httpCall

### ISSUE THREAD

**Issue by CharlieC3** [envoyproxy/envoy#25190]
*Title*: Don't set x-forwarded-for header in Lua request handler httpCall

*Description*:

I'm trying to use the [Lua httpCall function](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall) to contact the GCP Metadata server and retrieve a service account token, which I can then use to interact with some GCP services mid-request.
The problem is that the `httpCall` function adds an X-Forwarded-For header to any requests it makes, which the [GCP Metadata server explicitly rejects](https://cloud.google.com/compute/docs/metadata/overview#limitations).

Is there any way I can prevent the X-Forwarded-For header from being injected into the `htppCall`, or at least remove it before the requests is sent to the GCP Metadata server?

**Comment by RyanTheOptimist** [comment]
cc: @wbpcode

**Comment by wbpcode** [comment]
An option could be used to prevent the xff adding. However, this option is not exposed to lua.

I marked this to `help wanted` and we will try to add this option to the lua http call.
