### ISSUE TITLE
format error in golang.proto: min_bytes is DEPRECATED, Use min_len.

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#25198]
*Title*: format error in golang.proto: min_bytes is DEPRECATED, Use min_len.

*Description*:
My PR (#25040) needed merging latest main. After doing so I get the following error when trying to push the PR:
```
  Checking format for .github/workflows/tsan.yml - PASS
  Checking format for CODEOWNERS - PASS
  Checking format for OWNERS.md - PASS
  Checking format for api/bazel/api_build_system.bzl - PASS
  Checking format for api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto - ERROR: From ./api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto
ERROR: ./api/contrib/envoy/extensions/filters/http/golang/v3alpha/golang.proto:54: min_bytes is DEPRECATED, Use min_len.
ERROR: check format failed. run 'tools/code_format/check_format.py fix'
```

Could be related to the changes from #25101.

**Comment by adisuissa** [comment]
cc @phlax - who may know more about this.

**Comment by phlax** [comment]
>  who may know more about this

not off hand - my pr linked above only dealt with docs so unlikely to be the cause i think

im trying to understand why it has triggered on this pr - postsubmit seems ok, and the PR seems to be passing now - quite possibly a bad "what changed" algo on the code format script

re the actual problem it looks like an easy fix - cc @wangfakang

**Comment by phlax** [comment]
regarding this triggering in check_format im actually very confused - that script stopped checking proto files quite a while back

i cant find any failed runs either on the PR or in azp - if you can lmk how this issue was triggered im happy to try and repro

**Comment by wangfakang** [comment]
> > who may know more about this
> 
> not off hand - my pr linked above only dealt with docs so unlikely to be the cause i think
> 
> im trying to understand why it has triggered on this pr - postsubmit seems ok, and the PR seems to be passing now - quite possibly a bad "what changed" algo on the code format script
> 
> re the actual problem it looks like an easy fix - cc @wangfakang

OK, Thanks. Let me fix this problem first https://github.com/envoyproxy/envoy/pull/25206. But in my [PR](https://github.com/envoyproxy/envoy/pull/24848), this check is also passed , which is confused.

**Comment by adisuissa** [comment]
> regarding this triggering in check_format im actually very confused - that script stopped checking proto files quite a while back
> 
> i cant find any failed runs either on the PR or in azp - if you can lmk how this issue was triggered im happy to try and repro

Yeah, that's what I found puzzling...
It shouldn't check for proto changes after merging the latest main, but it did.
On top of that, I would've expected that this will be caught during the CI of the original PR.

It could due to a wrong version of the tooling that I'm using, but as this is our proto-format checker I'm not sure what could be wrong.

**Comment by phlax** [comment]
ok - i ~see the problem ill open a separate ticket

**Comment by phlax** [comment]
#25208
