### ISSUE TITLE
Disable mobile tests on release branches

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25205]
The most recent release branch to fork (`release/v1.25`) carries the new mobile CI and has a high tendency towards failure

Im wondering if there is any reason we want these tests to run at all on release branches (altho im not 100% clear about if/how we can make it only target PRs -> `main`)

**Comment by jpsim** [comment]
`mobile/tools/should_run_ci.sh` _should_ be able to check that we're running on a PR towards `main`. Or maybe the heuristic here is only to skip mobile CI jobs if the current branch name is in the format `release-.*-dev` so that it's still useful to have staged PRs touching `mobile/**`.

**Comment by phlax** [comment]
i dont want to impose a `release-x` branch name on all backport PRs but i guess we could automatically skip at that point _and_ bail in the script if it gets that far

>  ... it's still useful to have staged PRs touching mobile/**

im trying to figure out if that is useful - i think the release branches are only used for releasing envoy and mobile releases are handled separately - so trying to think if there is any benefit

**Comment by jpsim** [comment]
> im trying to figure out if that is useful - i think the release branches are only used for releasing envoy and mobile releases are handled separately - so trying to think if there is any benefit

I meant that if I make two PRs `branch2 -> branch1 -> main` it'd be good that the `branch2` PR ran the mobile CI jobs if appropriate even if that PR isn't targeting a `main` base branch.
