### ISSUE TITLE
Turn on Envoy debug log dynamically on-demand by a magic HTTP request header.

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#2521]
*Title*: To turn on Envoy debug log only for some specific requests with some magic header. such as: "envoy-debug:  on"

*Description*:
This will be very useful for debugging in production environment.

**Comment by mattklein123** [comment]
This would be a useful feature. We have already been considering doing work in this area (I believe @ccaraman will do it at some point), mainly around having an `x-envoy-debug-trace` header which will have Envoy return a bunch of information about what it did (what cluster it chose, etc.). I think we could also potentially use this to raise certain debug lines dynamically to "warn" level, but that would require some thinking and work to figure out which ones should be promoted.

**Comment by mandarjog** [comment]
We should x-request-Id with a specific pattern to control turning on debug. The advantage is that these headers  already propagate through the mesh.

**Comment by mattklein123** [comment]
> We should x-request-Id with a specific pattern to control turning on debug. The advantage is that these headers already propagate through the mesh.

Good idea. I like it.

**Comment by ccaraman** [comment]
@qiwzhang What kind of issues are you trying to debug? ex: routing issues?

**Comment by alyssawilk** [comment]
Do we want something specific to logging, or something that controls flags / options in general?    I think it'd be nice to have something more general even if we only implement specific handlers for now.

**Comment by ccaraman** [comment]
For debugging routing issues, there are two features I want to add:
1. Return extra data when a header(tbd) is set:
* list of cluster names 
* If local envoy or the service returned the HTTP status code

2. Similar to the route checking tool, return which cluster the request would route to without fwd the request.

**Comment by evilyeti** [comment]
That would be similar to what CDN providers do for troubleshooting. See here: 

- Akamai [pragma headers](https://community.akamai.com/customers/s/article/Using-Akamai-Pragma-headers-to-investigate-or-troubleshoot-Akamai-content-delivery)
- Fastly [debug headers](https://community.fastly.com/t/deciphering-fastly-debug-header/520)
