### ISSUE TITLE
Jwt authn filter is pass invalid Authorization Bearer

### ISSUE THREAD

**Issue by danieldradware** [envoyproxy/envoy#25239]
*Title*: *Jwt authn filter is pass invalid Authorization Bearer*

*Description*:
>While sending a valid token with space and some characters jwt filter is consider
It as a valid token. (I checked it with Auth0 server and his response for this case is: 
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Bad HTTP authentication header format",
    "errorCode": "Bearer"
})
So in this case the filter should remove all spaces and then will get JwtBadFormat.
Example:
eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJEaW5vQ2hpZXNhLmdpdGh1Yi5pbyIsInN1YiI6Im1pbmciLCJhdWQiOiJhcnlhIiwiaWF0IjoxNjY2MjQ2NjQ0LCJleHAiOjE5NjYyNDcyNDR9.nj2u8hdddD0l5EyzngRHGnqiZMzcwzyLj_MY2s9y2EZVIC35yPCvSQuk3N5Q2cP-KwBzb2p6_KM1UeUVcEVKSDSBS_RVhBxeuYgZLWcLgw4LU0QM23maoz70GgHM_nIIF1jy_dL6NCkmQTjr6UOWXqstzEgPb65uLZw0p4GFYRlHLJZpzTX_upLJR9E8HwoN5TCRqE_DYVDvwtLFUT9W6cwmqnOGckhfVknB9Y18cVXSrNTSs1BxV_Mf4rM4x4kGxYE_16ip3ERRmjBLRsRDDCA5diUdCpSh8eVFAA_gBkep1ou8B7PyyzDQYnP86SXzIkcdduD3rajMtybLq6X-2A .jjjjjjjjjjjjjjjj

*Repro steps*:
> 1. Deploy Envoy env with jwt filter   2. send request with Authorization header and value is Bearer + your token + space + some characters (as mentioned in the example)

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

**Comment by ggreenway** [comment]
cc @qiwzhang @lizan

**Comment by danieldradware** [comment]
Hi @ggreenway  
Thanks for your adding it to bug queue.
There is some approximately estimation time for fix?

@lizan @qiwzhang 
Thanks in advanced
Daniel

**Comment by lizan** [comment]
The [extractor](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/jwt_authn/extractor.cc#L310) only extract token to first non-JWT character.

There's no estimation time for the fix, if you want to do a PR I'm happy to review.

**Comment by danieldradware** [comment]
Hi @lizan 

I'm currently busy and can't handle it now,
Perhaps I will be able to some time in the future.

Regards,
Daniel
