### ISSUE TITLE
Http3 example doesn't work

### ISSUE THREAD

**Issue by lightme16** [envoyproxy/envoy#25251]
*Description*:
I am using config from https://github.com/envoyproxy/envoy/blob/943be5375289eba651748901a71cd77686ae06ed//configs/envoyproxy_io_proxy_http3_downstream.yaml to set HTTP3 support however it doesn't work

```
*   Trying 127.0.0.1:10000...
* connect to 127.0.0.1 port 10000 failed: Connection refused
* Failed to connect to 127.0.0.1 port 10000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 10000: Connection refused
```

*Repro steps*:
- Checkout https://github.com/envoyproxy/envoy/blob/943be5375289eba651748901a71cd77686ae06ed//configs/envoyproxy_io_proxy_http3_downstream.yaml and use as config
- start envoy with `docker run --rm -p 10000:10000/UDP -p 10000:10000/TCP -p 9901:9901 -v ${PWD}/10-http3/envoy-example.yaml:/tmp/envoy.yaml -v ${PWD}/certs/servercert.pem:/tmp/servercert.pem -v ${PWD}/certs/serverkey.pem:/tmp/serverkey.pem envoyproxy/envoy:v1.25.0 -c /tmp/envoy.yaml`
- try to do http3 connection `docker run -it --rm ymuski/curl-http3 curl -v -k  https://127.0.0.1:10000/ `

*Logs*:
https://pastebin.com/iBKnttjr

**Comment by ggreenway** [comment]
I recommend trying to test without docker, or at least with all the components within a single docker container, to rule out docker networking as an issue. If it's still an issue, ensure the ports you expect are open using `netstat` or `ss`.

**Comment by lightme16** [comment]
@ggreenway thanks, your intuition was right. I had some issue with docker's networking on MacOS. I was able to make it work in docker container on Linux instance. 

However, I still can see some issue. E.g Chrome is not able to initialize Http3 connection. However I can able to establish HTTP3 connection with [quiche’s http3-client](https://blog.cloudflare.com/http3-the-past-present-and-future/), e.g `RUST_LOG=debug target/debug/examples/http3-client <MY_HOST>` 
I am following [example](https://github.com/envoyproxy/envoy/blob/943be5375289eba651748901a71cd77686ae06ed//configs/envoyproxy_io_proxy_http3_downstream.yaml) from this repo. TCP listener works, Chrome is able to reach the HTTP2 proxy endpoint. However H3 fallback doesn't happening. This is strange because `alt-svc` header points to the UDP listener. 
Is that expected that Chrome and Envoy's Http3 are not working as expected?

**Comment by ggreenway** [comment]
I would expect Chrome to work with Envoy over http/3. What kind of failure are you seeing? Are the UDP packets not reaching Envoy? Failure to handshake a QUIC connection? Failure to validate the cert?

**Comment by lightme16** [comment]
UPD listener is working fine when sending requests with http3-client or curl. The issue is that  Chrome is not switches to the h3 protocol and keep using h3 while `alt-svc` is sent in the response. When I connect to UDP port directly from CLI it works fine.

**Comment by lightme16** [comment]
seems to be related to https://github.com/envoyproxy/envoy/issues/24103
