### ISSUE TITLE
Please support domain matching in the CORS config

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#2526]
*Description*:
The `envoy.cors` filter injects [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers. Currently the outgoing `Access-Control-Allow-Origin` header is set from a hardcoded set of domains in the Envoy config, so you must know the string-exact name of each domain that will be making requests to the service.

It'd be nice if Envoy could support matching (regex, wildcard, or whatever) on the incoming `Origin` header. If a match is found, then the outgoing `Access-Control-Allow-Origin` would be set to the origin as provided by the client.

This would let CORS be useful for sites on dynamically-generated domain names, for example when using a temporary website instance allocated per Github PR.

*Relevant Links*:
* [Setting `Access-Control-Allow-Origin: *` has security implications](https://stackoverflow.com/questions/43193644/api-vulnerabilities-with-dynamic-cors-headers), so we'd like to avoid it.
* [Example nginx config for CORS with dynamic origins](https://enable-cors.org/server_nginx.html)

**Comment by mattklein123** [comment]
SGTM if anyone would like to work on this.

**Comment by alyssawilk** [comment]
@codesuki in case he's interested :-)

**Comment by codesuki** [comment]
I am down for it. This is a feature I wanted to implement in the beginning. But the earliest I could start to work on it is middle to end of March. So if nobody picks it up until then, I will.
