### ISSUE TITLE
Test flake: QuicHttpIntegrationTests/QuicHttpIntegrationTest.DeferredLogging/IPv6

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#25264]
```
[ RUN      ] QuicHttpIntegrationTests/QuicHttpIntegrationTest.DeferredLogging/IPv6
test/integration/quic_http_integration_test.cc:1206: Failure
Expected: (std::stoi(metrics.at(1))) > (0), actual: 0 vs 0
```

This was added a few days ago in #23648.

cc @pksohn @RyanTheOptimist

**Comment by ggreenway** [comment]
Failing run: https://dev.azure.com/cncf/envoy/_build/results?buildId=126681&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca

**Comment by pksohn** [comment]
I'll open a PR to fix this soon.

**Comment by ggreenway** [comment]
Thanks!
