### ISSUE TITLE
Test flake: //test/extensions/transport_sockets/internal_upstream:internal_upstream_integration_test

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#25271]
```
2023-01-31T20:19:04.3856419Z [ RUN      ] InternalUpstreamIntegrationTest.BasicFlow
2023-01-31T20:19:04.3857404Z test/extensions/transport_sockets/internal_upstream/internal_upstream_integration_test.cc:198: Failure
2023-01-31T20:19:04.3858421Z Value of: waitForAccessLog(access_log2_name_)
2023-01-31T20:19:04.3859531Z Expected: has substring "internal_listener2,internal_listener2,FOO,-"
2023-01-31T20:19:04.3860404Z   Actual: "internal_listener,internal_listener,FOO,BAZ"
```

Test was added a few days ago in #24920

**Comment by ggreenway** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
Tried to run it 10,000 times and it passed :/

**Comment by ggreenway** [comment]
The failure was reported on arm64. Is there any timing component to the result of this test?

**Comment by ggreenway** [comment]
In case there's anything useful, full logs are here: https://dev.azure.com/cncf/envoy/_build/results?buildId=126744&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca

**Comment by kyessenov** [comment]
Don't think it needs to wait for xDS resources since it's not changing them. I'm puzzled why it would fail.

**Comment by ggreenway** [comment]
I wonder if the two access logs end up with the same filename? 

```
std::string TestUtility::uniqueFilename() {
  return absl::StrCat(getpid(), "_", std::chrono::system_clock::now().time_since_epoch().count());
}
```

Maybe on arm64 the clock granularity is lower, such that two subsequent calls to this function get the same value?

**Comment by kyessenov** [comment]
That could be it. We should probably make this utility function more fool proof (maybe using nano/micro second level time).

**Comment by ggreenway** [comment]
Agreed. Appending a random number could also help. Or possibly have a global atomic counter to guarantee unique names within the process (and it includes the PID to guarantee uniqueness across processes).

**Comment by kyessenov** [comment]
Probably fixed but re-open if happens again.
