### ISSUE TITLE
Envoy uses huge amount memory beside low HTTP traffic

### ISSUE THREAD

**Issue by egerkke** [envoyproxy/envoy#25286]
*Title*: *Envoy uses huge amount memory beside low HTTP traffic*

*Description*:
>Hi Ladies and Gents,
>
>Envoy v1.19.1 is installed on a host that:
> - has 46 CPU cores (please see cpu_info in attached zip file)
> - no concurrency parameter was given to Envoy to limit the number of worker threads.
> - no Overload Manager is activated (no envoy.overload_actions.shrink_heap is activated)
> - It continuously receives a very minimal traffic of http (1 request / sec)
> - metrics statistics are gathered in each and every 15th second.
>
>It was observed that Envoy's memory usage is continuously increasing by time, 400+ MBs currently.
>
>Can you please help that:
> - what is actually causing the continuous memory increase?
> - if it is some caching that Envoy does to serve faster the requests than will memory be cleared?
> - what can trigger to release the memory?
> - would you have an estimate what will be the maximum consumed memory?
>
> I attached the running configuration with the cpu info.
>
> Many thanks in advance!
[config.zip](https://github.com/envoyproxy/envoy/files/10557956/config.zip)

**Comment by ggreenway** [comment]
My best guess is that the size of tcmalloc per-core caches are increasing. It's possible that you'll have lower memory usage if you limit concurrency. If you have very little traffic, this should be fine and will likely result in improved performance (fewer workers means fewer connection pools to warm, etc).

How long has your instance of Envoy been running?

**Comment by caixingcheng** [comment]
Hi ggreenway,
Many thanks for your answer. currently the envoy instance has been runing 60 days.
Could you tell us when  the tcmalloc per-core caches will be released, and how to estimate the memory will be used by the envoy base on worker thread number?

BRs

**Comment by ggreenway** [comment]
You can read about how tcmalloc works here: https://google.github.io/tcmalloc/overview.html

Memory use very much depends on configuration and usage pattern. I don't have any general guidance to provide on how much memory use is expected.

But if it is consuming more memory over a period of 60 days, it sounds like there is a memory leak. One thing I would recommend trying is using a newer version of envoy and see if the problem goes away.

**Comment by caixingcheng** [comment]
Hi Greg,

Thanks for your reply.
We continually monitor the memory consumption of the pod for more days, now the memory consumption seem stable.

The "kubectl top" shows a pod cost 406Mi memory.
```
eric-tm-ingress-controller-cr-envoy-dpvnh                         32m          406Mi  
```
And we checked /memory API via the administration interface, it shows the heap size is "216006656" however the "allocated" and the "total_thread_cache" is very low. Do you have any idea of how to reduce this "heap_size"?
```
{
 "allocated": "16354456",
 "heap_size": "216006656",
 "pageheap_unmapped": "8298496",
 "pageheap_free": "57344",
 "total_thread_cache": "92384",
 "total_physical_bytes": "233389030"
}

```

The stats result via administration interface is attach also.
[02-17T16_33_eric-tm-ingress-controller-cr-envoy-dpvnh_stats.log](https://github.com/envoyproxy/envoy/files/10782030/02-17T16_33_eric-tm-ingress-controller-cr-envoy-dpvnh_stats.log)

BRs
