### ISSUE TITLE
ext_authz.failure_mode_allow should optionally append a header on failure

### ISSUE THREAD

**Issue by bgerson-square** [envoyproxy/envoy#25330]
*Title*: 
*failure_mode_allow should optionally append a header on failure*

*Description*:
When using `ext_authz` filters with `failure_mode_allow: true`, requests that could not be completed are allowed to pass through rather than being denied. It would be useful in cases where `ext_authz` filters are used sequentially, for example, to know if a request that has made it <this far> was passed along as a result of an allowed failure vs auth success. 

Appending a header such as `x-envoy-failure-mode-allowed: true` would allow for special handling or custom metric emission for those cases. 

Whether or not to add this header on failures could be configurable, and disabled by default.

**Comment by wbpcode** [comment]
make sense to me.

**Comment by StarryVae** [comment]
If no one is working on this, i can pick it up, thanks.

**Comment by StarryVae** [comment]
> i actually wouldn't mind taking a crack at this myself, have been looking for an opportunity to contribute here and this seems like a good one. i'll try and have a PR up by EOW or comment here if i am unable to do so

Sorry to interrupt, but do you have time to solve this problem now? @bgerson-square

**Comment by StarryVae** [comment]
yeah, thanks.
