### ISSUE TITLE
Can change istio-proxyv2 access log's START_TIME value according to timezone?

### ISSUE THREAD

**Issue by ningyougang** [envoyproxy/envoy#25331]
I used isito with envoy

Below red box part is  `START_TIME` , the whole record is an access log
![image](https://user-images.githubusercontent.com/11749867/216264182-b6bc7acc-47ea-4e21-b0c4-ddce238b0dc3.png)

I want istio access log's `START_TIME` value can be changed according to pod's timezone, e.g.
* if change TZ to Asia/Shanghai, `START_TIME` will use `CST` time.
*  if change TZ to Asia/Seoul, `START_TIME` will use `KST` time.

But it seems it doesn't support, my test as below
After installed `tzdata` package to corresponding istio-proxyv2 image, now can configure any timezone using below `TZ` env, e.g.
```
- name: TZ
   value: Asia/Shanghai
```
I tried `Asia/Shanghai`, `Asia/Seoul` ,  `America/New_York` , above `START_TIME` still uses `UTC` value.

There has any method to change istio-proxyv2 access log's `START_TIME ` value according to `TZ`?

Since `istio-proxyv2` based on `envoy`, so i opened a new issue here.

**Comment by mattklein123** [comment]
Please raise this issue with Istio.

**Comment by zirain** [comment]
@mattklein123 istio does nothing special to Envoy

AFAIK, `%START_TIME%` do not respect `TZ` env, can senior envoy maintainers confirm that.

**Comment by kyessenov** [comment]
Envoy always reports in UTC time zone, there's no option to customize it.  I'm not sure why we need it strongly, since that requires parsing TZ data, etc.

**Comment by ningyougang** [comment]
@kyessenov 

AFAIK, loki logStorage system also print the raw log's timestamp filed using `UTC`, but when show in grafana, it added a another timestamp to user(Its value is `insertion time of the log record`, the value based on `ENV: TZ`).

show example as below
![image](https://user-images.githubusercontent.com/11749867/216527918-ce8e010a-0d91-4352-969a-a4c8e76c3a87.png)
