### ISSUE TITLE
OPTIONS request is passed to the backend 

### ISSUE THREAD

**Issue by fredericpougnault** [envoyproxy/envoy#25335]
OPTIONS request is passed to the backend 

I use CORS with this example https://github.com/envoyproxy/envoy/tree/main/examples/cors/backend 
When I send an OPTIONS request the request is passed to the backend,
I don't understand why envoy is not responding.
Is it normal ?

**Comment by botengyao** [comment]
Which request path are you using? Some route like `prefix: "/cors/open"` doesn't specify the `allow_methods` config from your example.

**Comment by wbpcode** [comment]
Could you provide a more detailed context to this issue. For example, could you provide your test request?

**Comment by fredericpougnault** [comment]
My request is curl -X OPTIONS http://127.0.0.1:8002/cors/restricted -v
*   Trying 127.0.0.1:8002...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8002 (#0)
> OPTIONS /cors/restricted HTTP/1.1
> Host: 127.0.0.1:8002
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< allow: OPTIONS, GET, HEAD
< content-length: 0
< server: envoy
< date: Mon, 06 Feb 2023 08:36:18 GMT
< x-envoy-upstream-service-time: 4
<
* Connection #0 to host 127.0.0.1 left intact

And on the serveur I see this log :
backend-backend-service-1  | 172.30.0.3 - - [06/Feb/2023 08:36:18] "OPTIONS /cors/restricted HTTP/1.1" 200 -

As I understand the backend service doesn't response to preflight request.
The response should be sent by envoy

**Comment by wbpcode** [comment]
Thanks. I think maybe you lost `origin` header in your OPTIONS request and that make cors filter to ignore the request.

**Comment by fredericpougnault** [comment]
When I try with curl -X OPTIONS http://127.0.0.1:8002/cors/restricted -v -H "Origin: http://test.com"

I have the same error

**Comment by wbpcode** [comment]
could you try a `When I try with curl -X OPTIONS http://127.0.0.1:8002/cors/restricted -v -H "Origin: test.envoyproxy.io"`

**Comment by fredericpougnault** [comment]
With this origin I have the good header "access-control-allow-origin: test.envoyproxy.io ".
It is ok for me thank you very much
