### ISSUE TITLE
mobile: compile out unavailable builder functions

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy#25355]
*Title*: *Unavailable engine builder functions should be compiled out*

*Description*:

Currently it's possible to compile out HTTP/3 and admin interface support from Envoy Mobile, however the engine builder APIs are still available, which could possibly lead to crashes if those features are attempted to be used.

Instead, we should compile out those builder functions, making it harder to misuse.

*Relevant Links*: Discussion in https://github.com/envoyproxy/envoy/pull/25352#issuecomment-1416502976

**Comment by wbpcode** [comment]
cc @alyssawilk
