### ISSUE TITLE
How does the fallback policy work with healch_checks in Envoy

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#25358]
I'm using Envoy as the gateway of my backend servers.

I just read the docs of Envoy and I knew that we could control the route rules with the help of `header_to_metadata`. I also knew that Envoy provided a mechanism of `health_checks`, which allows us to check if an endpoint is healthy or not. But when I put the two stuffs together, I'm confused...

I knew that if a request failed on matching the metadata, it would be routed to the endpoint by default only if I configured a fallback endpoint, but if the metadata has been matched to some endpoint which it is being unhealthy, what whould happen? The fallback policy would be applied or an error would be generated immediately?

Here is an example:

    - name: envoy.filters.http.header_to_metadata
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
                  request_rules:
                  - header: x-canary
                    on_header_present:
                      metadata_namespace: envoy.lb
                      key: canary
                      type: STRING
                    on_header_missing:
                      metadata_namespace: envoy.lb
                      key: canary
                      value: "0"
                      type: STRING
                    remove: false
      clusters:
      - name:
        connect_timeout:
        type: STATIC
        lb_subset_config:
          fallback_policy: DEFAULT_SUBSET
          default_subset:
            canary: "0"
          subset_selectors:
          - keys:
            - canary
        load_assignment:
          cluster_name:
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address: <canary_address>
              metadata:
                filter_metadata:
                  envoy.lb:
                    canary: "0"
            - endpoint:
                address:
                  socket_address: <prod_address>
              metadata:
                filter_metadata:
                  envoy.lb:
                    canary: "1"

The config above allows us to control the route rules by `x-canary` in the headers of requests.

Now, I want to configure the `healch_checks`, which can decide if an endpoint is healthy or not. If an endpoint is unhealthy, Envoy would route requests to other endpoints. But what if the unhealthy endpoint is just the matched endpoint?

Let's say a request should be routed to the endpoint "prod address" because of its `x-canary:1`, but at the same time, the endpoint "prod address" is unhealthy. In this case, the Envoy would reply an error to the client or the Envoy would route the request to the endpoint "canary address" regardless of the metadata?

**Comment by botengyao** [comment]
I think if there is no subset metadata match, it will fall back to the default subset.
