### ISSUE TITLE
x-forwarded-client-cert doesn't forward SAN DNS names, only one URIName record is forwarded

### ISSUE THREAD

**Issue by shakti-das** [envoyproxy/envoy#2535]
*Title*: *x-forwarded-client-cert doesn't forward SAN DNS names, only one URIName record is forwarded*

*Description*:
A certificate can support multiple DNS names through SAN but XFCC header is only forwarding URI name type and ignoring all DNS name types.

Example SAN from certificate
X509v3 Subject Alternative Name:
URI:https://example.com, DNS:example.com, DNS:www.example.com

[optional *Relevant Links*:]
Code link: https://github.com/envoyproxy/envoy/blob/568d90b787539e627e58b17f9643c27171b485a8/source/common/ssl/ssl_socket.cc#L266

I am not 100% sure whether it's intended functionality or bug but as per [RFC 2818](https://tools.ietf.org/html/rfc2818#section-3.1), SAN DNS names are useful in TLS verification.

**Comment by mattklein123** [comment]
cc @myidpt @PiotrSikora

**Comment by shakti-das** [comment]
In Linkerd, this was resolved by adding DNS SAN entries directly to the XFCC header (keeping existing values same for backward compatibility). The XFCC now looks like:

`Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;SAN=https://example.com;DNS=example.com;Subject="Test CN"`

Can we look at similar solution in envoy?

**Comment by mattklein123** [comment]
Sure patches welcome. I think you will want to make this behavior configurable per the other values: https://github.com/envoyproxy/data-plane-api/blob/master/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L208.

**Comment by shakti-das** [comment]
Sure, will make the behavior configurable, am working on it, should have a PR in few days.

**Comment by PiotrSikora** [comment]
@shakti-das I'm not saying no, but the linked section of RFC talks about Server Identity, whereas we're talking about forwarding Client Identity. What's the use case here?

**Comment by PiotrSikora** [comment]
I know how this works, I was just wondering whether you have real products validating clients based on the DNS name, or is this a theoretical change.

**Comment by shakti-das** [comment]
We have products which are validating DNS names from SAN and that's when we noticed this missing.
