### ISSUE TITLE
HTTP: Support scheme case-insensitive

### ISSUE THREAD

**Issue by whalecold** [envoyproxy/envoy#25401]
Support scheme case-insensitive

*Description*:
>Describe the issue.

In the [http rfc](https://www.rfc-editor.org/rfc/rfc3986#section-3.1), it describe the scheme
```
Although schemes are case-
   insensitive, the canonical form is lowercase and documents that
   specify schemes must do so with lowercase letters.  An implementation
   should accept uppercase letters as equivalent to lowercase in scheme
   names (e.g., allow "HTTP" as well as "http") for the sake of
   robustness but should only produce lowercase scheme names for
   consistency.
``` 
and i find enovy not  support capital. 
- https://github.com/envoyproxy/envoy/blob/main/source/common/http/header_utility.cc#L188
- https://github.com/envoyproxy/envoy/blob/main/source/common/http/headers.h#L319

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by whalecold** [comment]
if support case-insensitive, we can transfer `_scheme` to lower case [here](https://github.com/envoyproxy/envoy/blob/main/source/common/http/utility.cc#L361)

**Comment by wbpcode** [comment]
cc @alyssawilk @mattklein123

**Comment by mattklein123** [comment]
cc @RyanTheOptimist

**Comment by whalecold** [comment]
Hi, I'm glad to do that, can i submit the pull requests.

**Comment by alyssawilk** [comment]
Thank you, but there's some complications with UHV etc. so if you can wait a few weeks I think it'd be easier for Yan or I to tackle it!

**Comment by whalecold** [comment]
> Thank you, but there's some complications with UHV etc. so if you can wait a few weeks I think it'd be easier for Yan or I to tackle it!

OK

**Comment by alyssawilk** [comment]
https://github.com/envoyproxy/envoy/pull/27581#event-9328457319
