### ISSUE TITLE
How to develop based on some specific version

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#25429]
Hi, this might be a stupid question but this is my first time to try to do some constribution to a open source project so please allow me to ask this question.

I'm trying to develop based on the verson 1.22.4. So I download its released source code and execute commands following the doc: https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#quick-start-bazel-build-for-developers.

I installed `bazel` and executed the command `bazel build -c opt envoy`. But I always got the error: 
```
Starting local Bazel server and connecting to it...
ERROR: /mnt/vdb/home/envoy/.cache/bazel/_bazel_envoy/64b269b4d1abf1b1cdbf72da1b604d43/external/bazel_tools/platforms/BUILD:84:6: in alias rule @bazel_tools//platforms:linux: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /mnt/vdb/home/envoy/.cache/bazel/_bazel_envoy/64b269b4d1abf1b1cdbf72da1b604d43/external/bazel_tools/platforms/BUILD:84:6: Analysis of target '@bazel_tools//platforms:linux' failed
ERROR: /mnt/vdb/home/envoy/envoy/source/exe/BUILD:23:16: errors encountered resolving select() keys for //source/exe:envoy-static
ERROR: Analysis of target '//:envoy' failed; build aborted: 
INFO: Elapsed time: 5.014s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (55 packages loaded, 337 targets configured)
    Fetching repository @local_config_cc; starting
```

However, if I `git clone https://github.com/envoyproxy/envoy.git`, whose branch is the `master`, the command `bazel build -c opt envoy` would be executed successfully.

I don't know why... Is it illegal to do such a development or did I do something wrong?

**Comment by phlax** [comment]
> However, if I git clone https://github.com/envoyproxy/envoy.git, whose branch is the master, the command bazel build -c opt envoy would be executed successfully.

the development HEAD for the project is the `main` branch - not sure if we need to change something to ensure that is cloned as default or whether that is local git config - but i would suggest trying `main`

if you are doing development then i would suggest avoid release branches - generally if you need to backport something it would be by patching `main` first - the 1.22 branch will go EOL in april

**Comment by phlax** [comment]
if you do actually need to develop against a specific version then i would strongly suggest using the `./ci/run_envoy_docker.sh` container as that will ~ensure the build environment is correct

**Comment by wbpcode** [comment]
It would be better to use a .devcontainer to develop and build envoy. **You can use the repo's own .devcontainer or bootstrap a container manually.** 
For example, you can run the envoy build container (you can get the image from the .bazelrc) and mount the source dir to the contianer. Then you can use vscode + remote container plugin to edit the souce code.

And It would be better to use ci/do_ci.sh to run the building or testing. There are too much compile args for Envoy so the raw `bazel build` is not recommend.

**Comment by YvesZHI** [comment]
@phlax   My project has been using Envoy since 2022, I used this version: https://github.com/envoyproxy/envoy/releases/tag/v1.22.5.

Now I want to do some enhancements for the Envoy of my project so I'm thinking that I should do my development based on the version 1.22.5. If I do `git clone https://github.com/envoyproxy/envoy.git` immediately, I don't know which version it is and I don't know if it would cause some other issues because of the change of versions, such as some backward-compatibility issues maybe? That's why I firstly tried to download v1.22.5 and to compile it.
