### ISSUE TITLE
AWS Request Signing Filter: support getting credentials from a file

### ISSUE THREAD

**Issue by michaelfinch** [envoyproxy/envoy#25445]
*Title*: Support getting credentials from a file in the AWS Request Signing Filter.

*Description*:
Currently, the filter only supports getting credentials from environment variables, EC2 instance metadata, and ECS task metadata. The latter two won't work for Envoys deployed outside of AWS, and the first one won't work for environments that don't allow secrets to be stored in env vars. I propose adding a new credential provider that reads credentials from a file.

The format of the file could be something simple like this:
```
{
    "AccessKeyId": "ACCESS_KEY_ID",
    "Expiration": "EXPIRATION_DATE",
    "SecretAccessKey": "SECRET_ACCESS_KEY",
    "Token": "SECURITY_TOKEN_STRING"
}
```
This matches the format of credentials retrieved from instance/task metadata, and would be easier to parse than AWS's standard [credentials file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html). Note: the filter does not use the AWS SDK.

Let me know if this feature would be accepted, in which case I'd be happy to contribute it. Thanks!

*Relevant Links*:
Supported credential providers: https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/aws/credentials_provider_impl.h

**Comment by wbpcode** [comment]
cc @derekargueta @mattklein123

**Comment by suniltheta** [comment]
Hi @michaelfinch, this is a good idea. We can follow the standard AWS convention of the file location `~/.aws/credentials` & format like below.
```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

It is also a good idea to extend this ability to support assuming multiple profile present within the credentials file, which can be done as future enhancements. If you are willing to contribute I can help collaborate and review it.

**Comment by michaelfinch** [comment]
I think that should work for my needs. A few things I want to clarify before I start working on this:
* In my environment the credentials file will be constantly overwritten with new, short-lived credentials. Therefore I'll need the filter to refresh the credentials at an interval (looks like that's already supported in the filter).
* For starters, how about we only read the following fields from the credentials file: `aws_access_key_id`, `aws_secret_access_key`, and `aws_session_token`? All other fields will be ignored.

**Comment by suniltheta** [comment]
Does the configuration file come with a field that specifies the expiration time like mentioned on the issue description? If so then the credentials provider can check if the credentials are expired before fetching them again from the file. If that field is not possible then we can configure a refresh period interval.

I assume the credentials file will be created and maintained by a process that is outside of Envoy?

**Comment by michaelfinch** [comment]
Based on https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html there isn't an expiration field, so I think we'll have to use a static interval. 

Correct, another process will be maintaining the credentials file. We obtain IAM credentials on our hosts by running a CLI command that returns the JSON output I shared in my original message, which is why I was thinking of using that format. But I'm okay with converting to the credentials file format because it seems more commonplace.
