### ISSUE TITLE
Optional mTLS based on request path and Lua filter

### ISSUE THREAD

**Issue by Whiskeyjack079** [envoyproxy/envoy#25447]
*Title*: *Optional mTLS based on request path and Lua filter*

*Description*:

I have a requirement for a service I'm writing, where certain endpoints need to have mutual TLS enabled, but allow other endpoints to not require the client certificate. This is using envoy as a sidecar in a K8S environment.

This, I believe, is working OK, although all the posts I've read indicate it's not possible, as the path information being sent happens after the TLS handshake, which makes sense it'd stop Envoy from doing this.

So I was hoping to validate my setup so far and see if it makes sense - to me I appear to have got the requirement working, except under one circumstance, when TLS session resumption kicks in.

Apologies I can't paste the entire configuration just yet, hopefully the below snippets provide enough of a context.

The envoy sidecar is relatively simple, the HttpConnectionManager part looks like the following:

```
- name: envoy.filters.network.http_connection_manager
  typed_config:
    "@type": ...v3.HttpConnectionManager
    forward_client_cert_details: SANITIZE_SET
    set_current_client_cert_details:
      subject: true
    ...
    http_filters:
      - name: envoy.filters.http.lua
        typed_config:
          inline_code: |
            function envoy_on_request(request_handle)
              [stripped code to get forwarded cert header and subject and check it against a whitelist of valid subjects etc]
              if path ~= nil and path:find("/whitelisted") then
                -- Do not check if client cert validated     
              else
                if request_handle:streamInfo():downstreamSslConnection():peerCertificateValidated() then
                   -- Client certificate was validated
              end
```

On the DownstreamTlsContext, I have VERIFY_TRUST_CHAIN, as well as disable_stateless_session_resumption set to true.

So (prior to setting disable_stateless_session_resumption to true), things work OK initially for a period of time, and then the peerCertificateValidate() method starts to return 'false', despite the same certificate being presented. If I disable TLS session resumption, things work smoothly over time (albeit I've had to disable the similar setting on the client with max_session_keys=0 and other ways for other clients).

I've tracked it down (I think) to it failing when TLS resumption kicks in - in this case Envoy doesn't appear to return true for the peerCertificateValidated(), which to me feels like a bit of a bug - if the initial handshake was validated, and then gets resumed, to me I'd think the peerCertificateValidate() should still return true (despite it maybe not having revalidated if it cached the connection).

So I'm just wondering if my logic above is sound or its a foul hack and shouldn't work / has issues, or if it'd be possible to maintain the peerCertificateValidated information on cached sessions.

**Comment by kyessenov** [comment]
cc @PiotrSikora I think it could be TLS sessions losing some SslConnectionInfo.

**Comment by ggreenway** [comment]
@Whiskeyjack079 I just saw this while searching for something in another issue. I think this is a duplicate of #21235; see commentary there.
