### ISSUE TITLE
How to know whether you are facing an internal error vs destination issue

### ISSUE THREAD

**Issue by dragoscalinescu** [envoyproxy/envoy#25455]
Hello envoy team!

I'm playing around with a more complex envoy configuration.
I'm running a filter chain consisting of a WASM filter, an external processor filter changing the body of the request and an external auth filter which adds some headers.
After these filters, my request is routed to a final (external) destination.

I'm trying to figure out if, as a client, I can tell in case of a failure if there was an internal issue in my envoy (any of the filters failed) or if there were problems at the destination (service unavailable / connection issues).

Ideally I'd have a header set on the response which will let me know that my filters worked fine, is there anything I can use to achieve this?

**Comment by wbpcode** [comment]
There is no a explicit flag to tell you everything. But response flag and response code detaill would always be helpful to determine what is wrong.

A global `response_headers_to_add` could help to set these flag or detail to your response header.

**Comment by dragoscalinescu** [comment]
@wbpcode thanks for your answer, it's very helpful.

I think setting specific response flags, like UH/UF, to my response headers would work.
Can you provide a small example on how this can be achieved?

**Comment by dragoscalinescu** [comment]
Think I got it right

```         route_config:
            name: local_route
            response_headers_to_add:
              - header:
                  key: "response-flags"
                  value: "%RESPONSE_FLAGS%"
