### ISSUE TITLE
ZK filter keeps buffering partial packets and hangs

### ISSUE THREAD

**Issue by Winbobob** [envoyproxy/envoy#25482]
*Title*: ZK filter keeps buffering partial packets and hangs

*Description*:
In [PR#25161](https://github.com/envoyproxy/envoy/pull/25161), we introduce an infinite loop to keep buffer partial packets until all packets in the buffer are complete, then ask ZK filter to decoder these completed packets in order to fix the decoder errors. One issue with this implementation is that if the received packets are always partial, they will be appended to the buffer continuously. Eventually the buffer reaches its limit and the ZK filter will hang since no more data will be read from the socket and ZK filter keeps executing the infinite loop.

*Repro steps*:
Apply [this Envoy config](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter#configuration) to an Envoy which proxy high-QPS ZK traffic.
The client may not be able to establish connections to the ZK cluster or get responses.

*Config*:
Much like the official example [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter).

**Comment by Winbobob** [comment]
One solution is to maintain a separate buffer for the ZK filter.
> Whenever new data appended to the read buffer, it is also "copied" to the ZK filter buffer. Within the ZK filter, whenever it detects a completed packet, the filter decoder the packet and drain the packet. In this case, the ZK filter will not prevent packets from being sent to the ZK service.

**Comment by Winbobob** [comment]
cc @rgs1, @fishcakez, and @JuniorHsu

**Comment by wbpcode** [comment]
cc @snowp as you are the codeowner and maintainer.

**Comment by Winbobob** [comment]
Hi @rgs1, any thoughts about this solutions? Thanks!
> https://github.com/envoyproxy/envoy/issues/25482#issuecomment-1424848870

**Comment by rgs1** [comment]
Hmm, but shouldn't timeouts take care of partial packets? They'd be timing out on the ZK client (and server) side anyway, no?

**Comment by Winbobob** [comment]
> Hmm, but shouldn't timeouts take care of partial packets? They'd be timing out on the ZK client (and server) side anyway, no?

Yes, we noticed some connection timeouts and four-letter words did not get responses. But I think it is not expected, right? Since the infinite loop in the ZK filter block the packets.
