### ISSUE TITLE
Quic listener fails to SSL certificate

### ISSUE THREAD

**Issue by lightme16** [envoyproxy/envoy#25494]
*Description*:
We are using envoy SDS to load certs dynamically. I added http3 quic listener, however envoy listener fails to load the wildcard certificates we are successfully using for TCP listeners.
However, this certificate works fine with the TCP listener. Whic makes me think there is an issue with the way quic listener loads private keys for the certificates.
> [2023-02-11 01:05:07.430][55][warning][quic] [source/common/quic/envoy_quic_proof_source.cc:74] Failed to load private key.
78749282516296:error:03000075:bignum routines:OPENSSL_internal:BAD_ENCODING:external/boringssl/src/crypto/bn_extra/bn_asn1.c:26:
78749282516296:error:1000011f:SSL routines:OPENSSL_internal:PRIVATE_KEY_OPERATION_FAILED:external/boringssl/src/ssl/ssl_privkey.cc:221:

Worth to mention that we have several wildcard certificates and envoy fails to load only one of them. All other certificates works fine with this Quic listner. I and am sure that that wildcard certificate is valid(checked with `openssl`), also as I said it works well for the TCP listener. Please, where any idea how to debug it? What to do?

*Repro steps*:
Do quic request e.g `curl -k --http3 -v https://localhost:4434/foo`

*Config*:
I am using `enovy 1.24`.
Here is a quick listener config:
```json
{
  "name": "outgoing_listener_http3",
  "active_state": {
    "version_info": "1932212207",
    "listener": {
      "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
      "name": "outgoing_listener_http3",
      "address": {
        "socket_address": {
          "protocol": "UDP",
          "address": "0.0.0.0",
          "port_value": 4434
        }
      },
      "filter_chains": [
        {
          "filter_chain_match": {
            "server_names": [
              "example.com"
            ]
          },
          "filters": [
            {
              "name": "envoy.filters.network.http_connection_manager",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                "codec_type": "HTTP3",
                "stat_prefix": "egress_http3",
                "rds": {
                  "config_source": {
                    "api_config_source": {
                      "api_type": "GRPC",
                      "grpc_services": [
                        {
                          "envoy_grpc": {
                            "cluster_name": "xds_cluster"
                          }
                        }
                      ],
                      "transport_api_version": "V3"
                    },
                    "resource_api_version": "V3"
                  },
                  "route_config_name": "outgoing_route"
                },
                "http_filters": [
                  {
                    "name": "envoy.filters.http.health_check",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck",
                      "pass_through_mode": true,
                      "headers": [
                        {
                          "name": ":path",
                          "safe_regex_match": {
                            "google_re2": {
                              "max_program_size": 2147483647
                            },
                            "regex": "/.*/healthcheck"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "envoy.filters.http.buffer",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer",
                      "max_request_bytes": 1000000
                    }
                  },
                  {
                    "name": "envoy.filters.http.grpc_stats",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig",
                      "emit_filter_state": true,
                      "enable_upstream_stats": true
                    }
                  },
                  {
                    "name": "envoy.filters.http.router",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                    }
                  }
                ],
                "add_user_agent": true,
                "http3_protocol_options": {
                  
                }
              }
            }
          ],
          "transport_socket": {
            "name": "envoy.transport_sockets.quic",
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport",
              "downstream_tls_context": {
                "common_tls_context": {
                  "tls_certificate_sds_secret_configs": [
                    {
                      "name": "example.com",
                      "sds_config": {
                        "api_config_source": {
                          "api_type": "GRPC",
                          "grpc_services": [
                            {
                              "envoy_grpc": {
                                "cluster_name": "xds_cluster"
                              }
                            }
                          ],
                          "transport_api_version": "V3"
                        },
                        "resource_api_version": "V3"
                      }
                    }
                  ],
                  "validation_context_sds_secret_config": {
                    "name": "client_certs",
                    "sds_config": {
                      "api_config_source": {
                        "api_type": "GRPC",
                        "grpc_services": [
                          {
                            "envoy_grpc": {
                              "cluster_name": "xds_cluster"
                            }
                          }
                        ],
                        "transport_api_version": "V3"
                      },
                      "resource_api_version": "V3"
                    }
                  }
                }
              }
            }
          }
        }
      ],
      "drain_type": "MODIFY_ONLY",
      "traffic_direction": "OUTBOUND",
      "udp_listener_config": {
        "downstream_socket_config": {
          
        },
        "quic_options": {
          
        }
      }
    },
    "last_updated": "2023-02-11T00:25:51.009Z"
  }
}
```

*Logs*:
> [2023-02-11 01:05:07.426][55][trace][udp] [source/common/network/udp_listener_impl.cc:54] Listener at 0.0.0.0:4434 :socket event: 3
[2023-02-11 01:05:07.426][55][trace][udp] [source/common/network/udp_listener_impl.cc:66] Listener at 0.0.0.0:4434 :handleReadCallback
[2023-02-11 01:05:07.426][55][trace][misc] [source/common/network/utility.cc:630] starting recvmmsg with packets=16 max=1500
[2023-02-11 01:05:07.427][55][trace][misc] [source/common/network/utility.cc:637] recvmmsg read 1 packets
[2023-02-11 01:05:07.427][55][debug][misc] [source/common/network/utility.cc:647] Receive a packet with 1200 bytes from 172.17.0.1:38160
[2023-02-11 01:05:07.428][55][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x479f3f34d500 for 3600000ms, min is 3600000ms
[2023-02-11 01:05:07.429][55][trace][quic] [source/common/quic/envoy_quic_proof_source.cc:101] Getting cert chain for ozviriuk.dev.sr.example.com
[2023-02-11 01:05:07.429][55][trace][quic] [source/common/quic/envoy_quic_proof_source.cc:113] Got a matching cert chain 
[2023-02-11 01:05:07.430][55][trace][quic] [source/common/quic/envoy_quic_proof_source.cc:101] Getting cert chain for ozviriuk.dev.sr.example.com
[2023-02-11 01:05:07.430][55][trace][quic] [source/common/quic/envoy_quic_proof_source.cc:113] Got a matching cert chain 
[2023-02-11 01:05:07.430][55][warning][quic] [source/common/quic/envoy_quic_proof_source.cc:74] Failed to load private key.
78749282516296:error:03000075:bignum routines:OPENSSL_internal:BAD_ENCODING:external/boringssl/src/crypto/bn_extra/bn_asn1.c:26:
78749282516296:error:1000011f:SSL routines:OPENSSL_internal:PRIVATE_KEY_OPERATION_FAILED:external/boringssl/src/ssl/ssl_privkey.cc:221:
[2023-02-11 01:05:07.431][55][trace][udp] [source/common/network/udp_listener_impl.cc:98] Listener at 0.0.0.0:4434 :handleWriteCallback
[2023-02-11 01:05:07.431][55][trace][udp] [source/common/network/udp_listener_impl.cc:54] Listener at 0.0.0.0:4434 :socket event: 3
[2023-02-11 01:05:07.431][55][trace][udp] [source/common/network/udp_listener_impl.cc:66] Listener at 0.0.0.0:4434 :handleReadCallback
[2023-02-11 01:05:07.431][55][trace][misc] [source/common/network/utility.cc:630] starting recvmmsg with packets=16 max=1500
[2023-02-11 01:05:07.432][55][trace][udp] [source/common/network/udp_listener_impl.cc:98] Listener at 0.0.0.0:4434 :handleWriteCallback

**Comment by adisuissa** [comment]
@alyssawilk @danzh2010 can you PTAL?

**Comment by danzh2010** [comment]
Hi there, thanks for reporting the issue! It seems like the [QUICHE private key extractor](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/crypto/certificate_view.h;l=123;drc=8ce391bed5ee336e59ccd87b8869760c30e2aad7;bpv=1;bpt=1) can't parse the PEM string provided by your SDS: https://github.com/envoyproxy/envoy/blob/540e9ca61a473d2e78f4deaa88c9357b92f9369d/source/common/quic/envoy_quic_proof_source.cc#L75. 

If you can get your private key locally, you can tweak tests here: https://github.com/envoyproxy/envoy/blob/540e9ca61a473d2e78f4deaa88c9357b92f9369d/test/common/quic/envoy_quic_proof_source_test.cc#L321-L377 to confirm it is the QUICHE library. And there is a way to debug into bazel external library if needed.

That being said, have you inspected the private key which failed to be loaded?

**Comment by lightme16** [comment]
@danzh2010 thanks! I tried to run test locally but got no luck. Do you have more instructions how to do so? I followed this doc https://github.com/envoyproxy/envoy/blob/main/ci/README.md
I tried to run `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'` on my Mac, but it failed. 
Then I tried to do this from Linux instance in AWS, but the command took around a hour to finish. That is pretty annoying.
Then I tried to re run the command but got another errors:
```
➜  envoy git:(main) ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
No remote cache is set, skipping setup remote cache.
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=x86_64
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
➜  envoy git:(main)                                                   
```
Can you please help me to debug this test with my private key? Thanks

**Comment by danzh2010** [comment]
I never used docker image to run test. Could you follow [this](https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#quick-start-bazel-build-for-developers) one to run test using bazel, e.g. `bazel test [test_target]` ?
