### ISSUE TITLE
When a request being retried, does it counted as active requests as well?

### ISSUE THREAD

**Issue by rafatbiin** [envoyproxy/envoy#25501]
*Title*: *Understanding active requests and active retries*

*Description*:
>I checked we defined both requests(active_requests) and retries(active_retries) in ResourceManager class separately, when we're retrying a request, are we incrementing the active_requests or not? I couldn't find a reference in the code as to how we're calling the callback when we're retrying a request and how it's relating to the connection pool.
as I was looking at implementing retry budget I was confused about these two terminologies. Please help me understand these two gauges. Thanks.

**Comment by wbpcode** [comment]
I did a quick check to the source. Seems both will be incremented.

The retry state in the router will handled the `retries` and the conn pool will handle the `requests` (just like there is a normal request).

**Comment by rafatbiin** [comment]
> wbpcode

Thank you so much for the reply. I had the same idea as well.
