### ISSUE TITLE
`envoy --version` reports old git SHA

### ISSUE THREAD

**Issue by jrajahalme** [envoyproxy/envoy#2551]
*Title*: `envoy --version` reports old git SHA

*Description*:
Re-linking envoy binary no longer updates the git SHA linkstamp shown by `envoy --version`. This may be due to a change in bazel 0.10.0, from the release notes, under *Important changes*:

"- Linkstamping is now a separate and full-blown CppCompileAction,
it's no longer a part of linking command."

*Repro steps*:
```
$ bazel build //source/exe:envoy-static
$ bazel-bin/source/exe/envoy-static --version

bazel-bin/source/exe/envoy-static  version: 97b69ce6a507471180c0585b6742c627962b433b/1.6.0-dev/Clean/DEBUG

$ touch empty-file
$ git add empty-file
$ git commit -a -m "testing."
$ git log --pretty=oneline
35931e6a89f38fe8ad3334e1d13bf056e2464f4d testing.
97b69ce6a507471180c0585b6742c627962b433b test: automatically registering integration ports from listener names (#2536)
...

$ rm bazel-bin/source/exe/envoy-static
$ bazel build //source/exe:envoy-static
$ bazel-bin/source/exe/envoy-static --version

bazel-bin/source/exe/envoy-static  version: 97b69ce6a507471180c0585b6742c627962b433b/1.6.0-dev/Clean/DEBUG
```

Note that the version was not updated even though the binary was relinked.

**Comment by htuch** [comment]
@jmillikin-stripe

**Comment by jrajahalme** [comment]
*Workaround*:

Manually remove `bazel-out/k8-fastbuild/bin/_objs/envoy/external/envoy/source/common/common/version_linkstamp.o` before a build.

Works for the (default) fastbuild in Linux, other architectures may need to replace 'k8-' with something else.

**Comment by jrajahalme** [comment]
@htuch Should this be assigned to someone who knows their Bazel? I've have to rely on the workaround but would rather not.

**Comment by htuch** [comment]
I think we should switch over from the old way of link stamping. We no longer need a Python script for this. @jmillikin-stripe is leading the Bazel efforts, so I'd defer to him on this.
