### ISSUE TITLE
build: new option to build envoy with dynamic stdlib

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#25533]
*Title*: *build: new option to build envoy with dynamic stdlib*

*Description*:

We may need to link a external .so which is built with dynamic stdlib to Envoy when we are develop a custom filter. However, Envoy will link the stdlib statically by default and this may cause unexpected crash, see #8513.

It would be better to add a new option that to allow building envoy with dynamic stdlib to avoid linking multiple stdlibs at same time.

**Comment by wbpcode** [comment]
cc @keith

**Comment by ghostofsparta-69** [comment]
can someone please help me with open source, I'm sort of a novice and really got no idea how to observe large code bases
