### ISSUE TITLE
HTTP CONNECT ForwardProxy / stats: envoy_http_downstream_rq_xx - response class "1" counter increase

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#25548]
Hi, i'm using envoy v1.21.0 with standard ForwardProxy CONNECT termination configs.
However, noticed  that the prometheus metric **envoy_http_downstream_rq_xx** - **response class "1"** counter increases slowly during the day. 
In the access logs all the requests are with **response_code 200**.
Just wonder what will cause this and what it means? Is it a bug or something else...

![image](https://user-images.githubusercontent.com/83286589/218757877-02c0de41-8df9-4b32-b36a-d9cf52ad68c7.png)

BR,
Stoyan

**Comment by wbpcode** [comment]
cc @jmarantz

**Comment by wbpcode** [comment]
May be this is because the status code 100(Continue) or status code 101(Switching Protocols)?

**Comment by wbpcode** [comment]
> i don't see how this is possible because the traffic is HTTP1.1 and HTTP1.0 CONNECT my config: routes:
> 
> ```
>     - match: {connect_matcher: {}}
>       route:
>         cluster: dynamic_forward_proxy_cluster
>         upgrade_configs: [{upgrade_type: CONNECT, connect_config: {}}]
> ```
> 
> also if it was 100, or 101 i believe it also should be logged in the access log like this, but as i said all i see is 200 there.

If a downstream request contains `expect: 100-continue`, then envoy will respond a response (with status 100) first and waiting the request body.
This response (with status 100) will be counted by the stats but no access log.

**Comment by pxpnetworks** [comment]
Understood, thx wbpcode. Wonder if is it possible to log that expect header with **expect_hdr: "%REQ(expect)%"**... i have no prior knowledge what headers the downstream servers put in their CONNECT request..

**Comment by wbpcode** [comment]
> Understood, thx wbpcode. Wonder if is it possible to log that expect header with **expect_hdr: "%REQ(expect)%"**... i have no prior knowledge what headers the downstream servers put in their CONNECT request..

nope. expect header will be removed immediately when the 100-continue response is sent.
