### ISSUE TITLE
` //test/integration:redirect_integration_test` is (very) flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25544]
This is failing pretty regularly - testing it locally and its a real deal flake - sometimes passes, sometimes not

In CI its failing fairly often and causing PRs to fail (eg https://github.com/envoyproxy/envoy/pull/25488#issuecomment-1428730776)

The error as posted on above comment is:

```console
test/integration/redirect_integration_test.cc:704
Expected equality of these values:
1
test_server_->counter("cluster.cluster_0.upstream_internal_redirect_succeeded_total") ->value()
Which is: 0
```

I believe this started with #23648 (after reverting i didnt trigger) cc @pksohn (if not it began at ~same time, apologies)

**Comment by pksohn** [comment]
I'll take a look to see if #23648 is related, thanks.
