### ISSUE TITLE
Broken build on OSX with Bazel 0.9.0

### ISSUE THREAD

**Issue by dignabbit** [envoyproxy/envoy#2555]
*Title*: Broken build on OSX with Bazel 0.9.0

*Description*:
I cannot build current master (`97b69ce6a507471180c0585b6742c627962b433b`) on OSX. Maybe this is related to recent changes from https://github.com/envoyproxy/envoy/pull/2508 ?

*Repro steps*:
```
$ bazel clean --expunge ; bazel build //source/exe:envoy-static --verbose_failures -s
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
...............
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': too many (2) positional arguments in call to configure_osx_toolchain(repository_ctx)
```

This though works:

```
BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 bazel build -c dbg //source/exe:envoy-static --verbose_failures  -s
```
@htuch, any idea?

**Comment by mattklein123** [comment]
I'm pretty sure we only support newest bazel. Please upgrade to 0.10.0. cc @zuercher

**Comment by htuch** [comment]
Yeah, I'm going to close this one out, as I'm certain it's an issue with 0.9 vs. 0.10 compatibility. Please bump. We're definitely aware that this isn't ideal, we have plans in motion to reduce our dependency on Bazel version by eliminating our fork of `bazel/cc_configure.bzl`; once that is done we shouldn't have this same pain point. Feel free to re-open if you want to discuss further.

**Comment by dignabbit** [comment]
Makes sense, thanks!
