### ISSUE TITLE
Consider enabling `-Wshorten-64-to-32` warnings

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy#25557]
*Title*: *Consider enabling `-Wshorten-64-to-32` warnings*

*Description*:

When we build Objective-C targets for Envoy Mobile, we see a few `-Wshorten-64-to-32` warnings in Envoy code.

We should consider fixing and then turning on these diagnostics globally.

For example:

```
envoy/envoy/common/union_string.h:223:34: warning: implicit conversion loses integer precision: 'absl::string_view::size_type' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
--
  | return getStrView(buffer_).size();
  | ~~~~~~ ~~~~~~~~~~~~~~~~~~~~^~~~~~
```

*Relevant Links*:

In https://github.com/envoyproxy/envoy/pull/25551 we silenced these warnings specifically when building Objective-C targets for Envoy Mobile.

**Comment by wbpcode** [comment]
cc @alyssawilk @keith cc @phlax
