### ISSUE TITLE
Redirect on button click

### ISSUE THREAD

**Issue by Rez0k** [envoyproxy/envoy#25574]
Hi,

I am trying to implement istio on an exist product.
In my product there is a button that when you click on it, it will redirect to an auth provider and then redirect back to the app if you have the proper permissions.

Everything is working great without istio but with istio, on the button click I am being redirected to auth provider page and then being redirected back to my app, but I can't get in.

I am not getting any errors, from the logs of the auth provider I am able to login from their side.

Probably envoy doesn't know how to handle with the response headers or the redirect, any ideas how to fix this issue?

If more data from my side is required please let me know.

**Comment by Rez0k** [comment]
More info after debugging:
istio or envoy is striping:
`set-cookie: sessionId=*******; Path=/; Expires=Thu, 16 Feb 2023 ...; HttpOnly; Secure`
from the response headers.
how can I prevent this?

**Comment by adisuissa** [comment]
It is not clear from your description whether [internal-redirect](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#internal-redirects) is enabled, and what is the behavior you are seeing.

Regarding your second comment, if Envoy doesn't pass the entire cookie as part of the response back to the downstream, it may be to an invalid `response_headers_to_remove` config.

**Comment by Rez0k** [comment]
> It is not clear from your description whether [internal-redirect](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#internal-redirects) is enabled, and what is the behavior you are seeing.
> 
> Regarding your second comment, if Envoy doesn't pass the entire cookie as part of the response back to the downstream, it may be to an invalid `response_headers_to_remove` config.

> 

I am using istio so I guess internal-redirect is enabled (?), 
do you know where can I find `response_headers_to_remove` with istio config?

**Comment by adisuissa** [comment]
I'm not very familiar with Istio's configuration. You may be able to find some info at [Istio's github repo](https://github.com/istio/istio).

**Comment by Rez0k** [comment]
> I'm not very familiar with Istio's configuration. You may be able to find some info at [Istio's github repo](https://github.com/istio/istio).

ok. thanks!
