### ISSUE TITLE
What machine do you use to build envoy?

### ISSUE THREAD

**Issue by mariash** [envoyproxy/envoy#25580]
I see in your actions that building envoy task [CI Build step](https://github.com/envoyproxy/envoy/blob/main/.azure-pipelines/bazel.yml#L43) takes ~30m. 

I am currently using GCP e2-standard-16 (16 CPU, 64GB memory, 400GB SSD disk). And it takes 4h to run `ci/run_envoy_docker.sh 'ci/do_ci.sh baze.release'` which builds envoy and runs tests.

What might be the difference? What machine are you all using? Looks like there is a remote bazel ci.

**Comment by daixiang0** [comment]
It would be slow when first time, the following builds would be faster due to cache.

The remote cache is similar like local cache, but shared for more machines.

**Comment by phlax** [comment]
> What might be the difference? What machine are you all using? Looks like there is a remote bazel ci.

yep, CI is using RBE to cache and build which makes a huge difference

as @daixiang0 says this gets a bit easier when your cache is warm, but it does take a rather long time, and caches bust

you might want to use the `bazel.release.server_only` target as that does not run tests after building

**Comment by mariash** [comment]
I see makes sense, we use fresh machine for every build. Thank you for responses.
