### ISSUE TITLE
How to configure trusted_ca under validation_context in envoy.yaml for request with TLS certificate chain 

### ISSUE THREAD

**Issue by abner88888** [envoyproxy/envoy#25588]
*Title*: 
How to configure trusted_ca under validation_context in envoy.yaml for request with **TLS certificate chain**

*Description*:

If client sends a request to server via TLS with certificate chain(eg：**root CA -> CA1 -> certificate**), how does we configure trusted_ca under validattion_context in envoy.yaml on server side ? trusted_ca uses ca_cert.pem **upon CA1** or ca_cert.pem **upon root CA** ? 

I referred to Envoy official document for trusted_ca and there is no clear detailed description for this.

Based on my experience, trusted_ca should use ca_cert.pem **upon root CA** instead of CA1, right?  We always use ca_cert upon root CA for certificate chain, right ? 

what can we configure for trusted_ca with certificate chain scenario to verify peer's certificate ?

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/v1.22.5/api-v3/extensions/transport_sockets/tls/v3/common.proto.html?highlight=trusted_ca#extensions-transport-sockets-tls-v3-certificatevalidationcontext

**Comment by adisuissa** [comment]
According to the [TLS docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#tls) Envoy supports:
```
* Certificate verification and pinning: Certificate verification options include basic chain verification, subject name verification, and hash pinning.
```

Can you please take a look at [this subsection](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#enabling-certificate-verification) and see if it provides a good answer?

**Comment by abner88888** [comment]
@adisuissa   
thanks for your response.  
found  X509_V_FLAG_PARTIAL_CHAIN in 1.25.0 to control verifying full certificates chain or partical chain in envoy.yaml.
