### ISSUE TITLE
is it possible to deprecate the gperftools?

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#25592]
tcmalloc from github.com/google/tcmalloc is used by default on the linux for a long time. Is it possbile to deprecate the gperftools to make the deps more clean?

**Comment by PKizzle** [comment]
Please do not deprecate gperftools as it still the easiest way of running envoy on stock Raspberry Pi OS. Have a look at the discussion in https://github.com/envoyproxy/envoy/issues/23339 or https://github.com/envoyproxy/envoy/issues/15235
