### ISSUE TITLE
`//test/integration:health_check_integration_test` is very flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25607]
CI is failing pretty frequently due to the above test

The first instance of it failing (8/2) in postsubmit is https://dev.azure.com/cncf/envoy/_build/results?buildId=127685&view=results

Error is:

```console
test/integration/health_check_integration_test.cc:683: Failure
Expected equality of these values:
  2
  test_server_->counter("cluster.cluster_1.health_check.success")->value()
    Which is: 1
Stack trace:
  0xbb52f1: Envoy::(anonymous namespace)::TcpHealthCheckIntegrationTest_DisableHCForActiveTraffic_Test::TestBody()
  0x1fce1ac: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1fce06d: testing::Test::Run()
  0x1fcf2c7: testing::TestInfo::Run()
... Google Test internal frames ...

[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_runtime_initialized to: false
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_no_extension_lookup_by_name to: true
[  FAILED  ] IpVersions/TcpHealthCheckIntegrationTest.DisableHCForActiveTraffic/IPv6, where GetParam() = 4-byte object <01-00 00-00> (50 ms)
[ RUN      ] IpVersions/TcpHealthCheckIntegrationTest.SingleEndpointWrongResponseTcp/IPv4


```

I wasnt able to repro locally

I believe it may be related to https://github.com/envoyproxy/envoy/pull/24903

@zhangbo1882 would you mind taking a look

**Comment by zhangbo1882** [comment]
I will take a look.

**Comment by zhangbo1882** [comment]
I tried many times locally, but I cannot reproduce it. 
I checked the code carefully and still cannot find any clues. 
Do we have any methods to troubleshooting it in CI server ?

**Comment by phlax** [comment]
> I tried many times locally, but I cannot reproduce it.

yep, same

>  Do we have any methods to troubleshooting it in CI server ?

not for debugging - but you can see the failed test runs here https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build

its failing pretty frequently

**Comment by phlax** [comment]
fwiw i have managed to trigger this locally, albeit when trying to test something else

```console
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_no_extension_lookup_by_name to: true
[       OK ] IpVersions/ExternalHealthCheckIntegrationTest.SingleEndpointTimeoutExternal/IPv6 (29 ms)
[----------] 6 tests from IpVersions/ExternalHealthCheckIntegrationTest (179 ms total)

[----------] Global test environment tear-down
[==========] 62 tests from 5 test suites ran. (2936 ms total)
[  PASSED  ] 61 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IpVersions/TcpHealthCheckIntegrationTest.DisableHCForActiveTraffic/IPv6, where GetParam() = 4-byte object <01-00 00-00>

 1 FAILED TEST
================================================================================

```

**Comment by phlax** [comment]
CI fails ...

- https://dev.azure.com/cncf/envoy/_build/results?buildId=128658&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=1152

**Comment by phlax** [comment]
@zhangbo1882 im wondering if it would be possible to temporarily revert your change so we can see whether that is the cause

whatever the cause, it flaking CI _a lot_

**Comment by zhangbo1882** [comment]
@mattklein123,  do you have any suggestions about the test failure. I have reviewed the test code and still cannot find any clues.

**Comment by phlax** [comment]
@zhangbo1882 as we are not certain that your PR is the culprit (altho it looks a likely candidate based on when the issue started) can we revert for a few days and see if it goes away ?

its pretty important because it breaks release tests

**Comment by phlax** [comment]
also worth noting - this is flaking on all platforms that are tested afaict - linux amd64/arm64, and windows

**Comment by phlax** [comment]
@zhangbo1882 i have reverted for now as it was causing too much CI breakage - please resubmit - not sure how we can confirm the issue is resolved given the difficulty reproing it

**Comment by zhangbo1882** [comment]
@phlax , I have found the root cause for the occasional CI test failure.
Locally, I just run the test for several times with command:
```
bazel test test/integration:health_check_integration_test --test_arg=--gtest_filter="IpVersions/TcpHealthCheckIntegrationTest.DisableHCForActiveTraffic/IPv4" --runs_per_test 1000
```
It can reproduce the issue. After my fix, the failure will never happen.

**Comment by phlax** [comment]
@zhangbo1882  this is still/again happening im afraid and failing quite a lot of CI

im going to raise a PR to revert again until we are confident that this doesnt break anything

**Comment by phlax** [comment]
example fails:

- https://dev.azure.com/cncf/envoy/_build/results?buildId=129796&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=1101
- https://dev.azure.com/cncf/envoy/_build/results?buildId=129786&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=1108
- https://dev.azure.com/cncf/envoy/_build/results?buildId=129788&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=1fb0b72f-6293-562d-a4d1-bb649223eaca&l=1769

and many more

**Comment by zhangbo1882** [comment]
@phlax , how can I find all the ci failurs for this PR. From the above 3 you mentioned, all failures were related to arm. 
I just want to verify whether it is arm specific.
Thanks.

**Comment by phlax** [comment]
its pretty useless but you can track using azp analytics:

- https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=11&contextType=build
- https://dev.azure.com/cncf/envoy/_test/analytics?definitionId=5&contextType=build

checking through i only see the arm jobs failing

i dont think its arm-specific in the sense of related to the architecture

the reason it became apparent on the arm jobs is that they dont use RBE and at the end of last week they also lost their local cache - so that has brought out any issues

i still think this needs to be addressed - this test was afaict the first to fail when jobs timed out, and i believe fails every time they do

some of our non-public CI which runs pretty frequently always runs non-RBE, no-local-cache - so any issues we are seeing here are turning up elsewhere

the other thing is that its part of the release pipeline (ie jobs that need to succeed when we publish) so its particularly important to rinse out any flakes

afaict there are kinda 2 issues - the first is that its timing out when waiting for the healthcheck to be updated

```console
Value of: TestUtility::waitForCounterEq(statStore(), name, value, time_system_, timeout, dispatcher)
  Actual: false (timed out waiting for cluster.cluster_1.health_check.success to be 2, current value 1)
Expected: true
```

the other is that it seems to be recording unexpected failure:

```console

test/integration/health_check_integration_test.cc:683: Failure
Expected equality of these values:
  0
  test_server_->counter("cluster.cluster_1.health_check.failure")->value()
    Which is: 9
```

in terms of repro - its worth checking here https://github.com/envoyproxy/envoy/blob/main/test/integration/README.md for deflaking advice - i guess you can trigger this with `stress` and/or running in a low powered vm - but its not the easiest or most reliable method

**Comment by zhangbo1882** [comment]
```
test/integration/health_check_integration_test.cc:683: Failure
Expected equality of these values:
  0
  test_server_->counter("cluster.cluster_1.health_check.failure")->value()
    Which is: 9
```
This failure is brought in by the previous timeout
```
Value of: TestUtility::waitForCounterEq(statStore(), name, value, time_system_, timeout, dispatcher)
  Actual: false (timed out waiting for cluster.cluster_1.health_check.success to be 2, current value 1)
Expected: true
```

**Comment by zhangbo1882** [comment]
I use stree tool and still cannot repo.
stress -c 20 (My pc have 20 cores.)
I still do not get the probable reason for the timeout issue. 
```
they dont use RBE and at the end of last week they also lost their local cache
```
What does RBE mean and what's the impact ?

**Comment by zhangbo1882** [comment]
If I change the timeout value to 1ms (the default value is 10s) , I can reproduce the issue.
```
test_server_->waitForCounterEq("cluster.cluster_1.health_check.success", 2, std::chrono::milliseconds(1));
```
```
[Wed Mar 08 02:33:09][#14# ] (main)$bazel test //test/integration:health_check_integration_test --test_arg=--gtest_filter="IpVersions/TcpHealthCheckIntegrationTest.DisableHCForActiveTraffic/IPv4"  --runs_per_test=1000
INFO: Analyzed target //test/integration:health_check_integration_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
FAIL: //test/integration:health_check_integration_test (run 773 of 1000) (see /data/cache/_bazel_stack/5a617312af51e0dbefb3398d3212136c/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/integration/health_check_integration_test/run_773_of_1000/test.log)
FAIL: //test/integration:health_check_integration_test (run 108 of 1000) (see /data/cache/_bazel_stack/5a617312af51e0dbefb3398d3212136c/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/integration/health_check_integration_test/run_108_of_1000/test.log)

FAILED: //test/integration:health_check_integration_test (Summary)
      /data/cache/_bazel_stack/5a617312af51e0dbefb3398d3212136c/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/integration/health_check_integration_test/run_773_of_1000/test.log
      /data/cache/_bazel_stack/5a617312af51e0dbefb3398d3212136c/execroot/envoy/bazel-out/k8-fastbuild/testlogs/test/integration/health_check_integration_test/run_108_of_1000/test.log
Target //test/integration:health_check_integration_test up-to-date:
  bazel-bin/test/integration/health_check_integration_test
INFO: Elapsed time: 162.460s, Critical Path: 99.05s
INFO: 1003 processes: 1 internal, 1002 linux-sandbox.
INFO: Build completed, 1 test FAILED, 1003 total actions
//test/integration:health_check_integration_test                         FAILED in 2 out of 1000 in 1.5s
```

**Comment by zhangbo1882** [comment]
@phlax , is it acceptable to enlarge the default timeout value from 10s to 30s to have a try?

**Comment by phlax** [comment]
what is the default timeout ?

i have opened a PR that increases sharding to handle timeouts (#25956) for other flaking tests, but iiuc this is unrelated to the timeout here (i might be wrong)

**Comment by phlax** [comment]
> is it acceptable to enlarge the default timeout value from 10s to 30s to have a try?

i would have thought, yes - but that is not my area so we will have to check with others

**Comment by zhangbo1882** [comment]
```
void waitForCounterEq(const std::string& name, uint64_t value,
                        std::chrono::milliseconds timeout = TestUtility::DefaultTimeout,
                        Event::Dispatcher* dispatcher = nullptr)

static constexpr std::chrono::milliseconds DefaultTimeout = std::chrono::milliseconds(10000);     
```
The default value is 10s.

**Comment by mattklein123** [comment]
No it is not ok to increase the timeout. This is slowing down ci if it's hitting the timeout. Please fix the test to make it run faster and run reliably. You might also consider using simulated time for the test.

**Comment by mattklein123** [comment]
It looks like the HTTP health check tests are already using simulated time? https://github.com/envoyproxy/envoy/blob/main/test/integration/health_check_integration_test.cc#L214. So maybe that is part of the problem. I'm not sure. You might want to reach out to @jmarantz on Slack who is an expert in these kinds of things.

**Comment by zhangbo1882** [comment]
@mattklein123, I do not think this issue has something with the timeout and my test code. The case is that in integration test, the fake upstream server does not response (I cannot reproduce it locally so I do not know how to debug it).  For integration test, envoy must wait for the response from fake upstream server. 
BTW, TCP/HTTP/GRPC health check tests have already used the simulated time.
