### ISSUE TITLE
Question : Envoy handling of the RST coming from downstream client

### ISSUE THREAD

**Issue by sujeshkumar** [envoyproxy/envoy#25615]
Have a question on Envoy handling of TCP Reset coming from client 
Scneario
- Client http to envoy proxy 
- envoy proxy connected to origin server (http)
- Server is doing chunked transfer or kind of streaming 
- Client disconnects ( say CTRL C)
TCPDump shows Client Sending FIN to envoy 
envoy keep sending any data coming from Origin Server 
Client Sends a RST(Reset) 
But Envoy does not seems to be handling the Reset Immediately , as server is keep sending data , envoy write to client socket fails and results in Close ( which sends FIN to origin server etc ) 

From code reading (source/common/network/connection_impl.cc) looks like its expected ? Can someone pls confirm ?
Is this to make sure that all data from socket is read before closing or to handle any complexity associated with water marking ?

```
  // We never ask for both early close and read at the same time. If we are reading, we want to
  // consume all available data.
  socket_->ioHandle().initializeFileEvent(
      dispatcher_, [this](uint32_t events) -> void { onFileEvent(events); }, trigger,
      Event::FileReadyType::Read | Event::FileReadyType::Write);
```

**Comment by risyou** [comment]
I see similar behaviour from my setup, will anyone confirm if it is expected and the reason behind?

https://github.com/envoyproxy/envoy/pull/12720
