### ISSUE TITLE
Better error response if `Host` doesn't match any known routes

### ISSUE THREAD

**Issue by nelhage-stripe** [envoyproxy/envoy#2562]
**Issue Template**

*Title*: Better error response if `Host` doesn't match any known routes

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.

If I try to make a request for an unrecognized `Host`, I get back an extremely generic `404`:

```
$ curl localhost:10080 -i -H 'Host: unknown-host.example.com'
HTTP/1.1 404 Not Found
date: Thu, 08 Feb 2018 23:50:18 GMT
server: envoy
content-length: 0
```

This is confusing behavior, since an operator looking at the response at the client can't easily distinguish between a genuine 404 from the end server, and an Envoy or client-side `Host` misconfiguration. This caused us a lot of confusion during an incident involving an Envoy rollout, since we spent a lot of time hunting for the apparent 404s in logs from a server that wasn't even receiving them.

At a minimum, I'd love the response body to include a message saying something like `"Envoy: No such route for Host: unknown-host.example.com"`. Ideally, though, I'd prefer an entirely separate HTTP status code, probably something more exotic, to increase debuggability for the operator.

**Comment by mattklein123** [comment]
> This is confusing behavior, since an operator looking at the response at the client can't easily distinguish between a genuine 404 from the end server, and an Envoy or client-side Host misconfiguration.

I'm not claiming this is less confusing, but Envoy will set the `x-envoy-upstream-service-time` header on proxied responses. Additionally, local responses like this would have the `NR` code in the access log. We can definitely consider adding a textual error in this case.

**Comment by alyssawilk** [comment]
I'd lean towards keeping the rc 404 since I think that's the most appropriate comment by the spec.  Have we thought about adding the Server: header on Envoy-generated responses?    That'd help debug-ability as well, and for more than just 404.

**Comment by mattklein123** [comment]
Closing this as this issue is being tracked as part of https://github.com/envoyproxy/envoy/issues/4283
