### ISSUE TITLE
Allow all cookies

### ISSUE THREAD

**Issue by Rez0k** [envoyproxy/envoy#25668]
Hi,

I am using istio with envoy as a sidecar.
I am using external auth provider which set session-id cookie in the response headers if the auth succeeded.

Before istio everything worked fine, but after applying istio with the envoy sidecar the session-id cookie is not reaching as a response header.

I tried creating envoy filter to allow the cookie in the response header to pass, but it does not seems to work.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "cookies", headers:get("set-cookie"))
              end

              function envoy_on_response(response_handle)
                local cookies = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")["cookies"]
                response_handle:headers():add("set-cookie", cookies)
              end
```

I tried applying this yaml to allow set-cookie but it does not work.
any ideas?

**Comment by phlax** [comment]
does this thread help at all?

https://github.com/envoyproxy/envoy/issues/7986

**Comment by Rez0k** [comment]
> does this thread help at all?
> 
> https://github.com/envoyproxy/envoy/issues/7986

I looked on this thread and tried to implement it in my mesh.
But in the thread example, I saw the following code block:

```
server_uri: uri: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/oauth2/auth cluster: outbound|4180||oauth2-proxy.oauth2-proxy.svc.cluster.local timeout: 10s
```

I don't have an internal auth service like oauth2.
My auth provider is external to my mesh.
I want to allow all response cookies coming from my external auth provider.

How can I rewrite the thread solution to match my needs?

Thanks!

**Comment by phlax** [comment]
i think the principle/s should be the same - i would add some debugging to try and figure out what is getting to where in terms of headers

also worth considering is setting up a sandbox using oauth as described in that ticket and then swap out with your provider to see what is different

**Comment by Rez0k** [comment]
> i think the principle/s should be the same - i would add some debugging to try and figure out what is getting to where in terms of headers
> 
> also worth considering is setting up a sandbox using oauth as described in that ticket and then swap out with your provider to see what is different

Can't I create a envoy filter to allow all response cookies to all websites?

**Comment by phlax** [comment]
quite possibly - but iiuc you should be able to achieve your goal with config (not sure)

**Comment by Rez0k** [comment]
> quite possibly - but iiuc you should be able to achieve your goal with config (not sure)

I am new to envoy do you see something wrong with the config I posted in the question above?

**Comment by phlax** [comment]
im afraid its beyond my immediate knowledge - other than reading the related ticket i posted which seems to suggest that what you are trying is doable but maybe requires some specific config/workarounds

**Comment by phlax** [comment]
cc @esmet @pradeepcrao @ggreenway @dio for any insights here

**Comment by Rez0k** [comment]
> cc @esmet @pradeepcrao @ggreenway @dio for any insights here

Thanks for help!
I hope I will be able to fix this
