### ISSUE TITLE
How do you calculate the ideal min_retry_concurrency for your service??

### ISSUE THREAD

**Issue by rafatbiin** [envoyproxy/envoy#25660]
*Title*: *How to know what is the min_retry_concurrency we can safely set*

*Description*:

I was trying to experiment with different [min_retry_concurrency](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers-thresholds-retrybudget) with same retry budget(say 2%) to observe the success rate of both downstream and upstream service but failing to come up with a number where I will not reject transient retry and also protect my upstream from any retry storm in production. from your experience, how did you guys figure out your ideal min_retry_concurrency where it'll not cause unnecessary failure and still safeguard your upstream service? because if you set it too low then at the time you're checking your retry budget, your active requests might go down and you run the risk of rejecting a transient failure request. if you set it too high then your retry budget might not kick in at all. How do you find a balance here?

**Comment by phlax** [comment]
cc @snowp @tonya11en - any advice here ?

**Comment by rafatbiin** [comment]
Currently what we're trying to do is find the upper bound of both `active_requests` and `min_retry_concurrency`  for a given rps settings. 

For finding the upper bound of `active_requests` we're setting `min_retry_concurrency=0` and trying to find the maximum `active_requests` on which we're allowing at least one retry request. 

For finding the upper bound of `min_retry_concurrency` we're setting the ` budget_percent = 0` and trying to find the maximum `min_retry_concurrency` at which the upstream and the downstream services success rate stays at an acceptable limit. 

Then we're trying to configure the retry budget based on these two numbers we found above. Let's say we found the upper bound of `active_requests = 50` and `min_retry_concurrency = 2`, now if we want to allow only `2 active_retries`, we've two options,
1. set min_retry_concurrency = 2
2. set min_retry_concurrency = 1 and set the budget percentage = 2/50*100 = 4%

could you please help confirm if the above methodology makes sense? please suggest any improvements or better ideas if you have any. Thank you.

cc: @snowp @tonya11en @phlax

**Comment by rafatbiin** [comment]
hi @snowp @tonya11en @phlax , any input on this would be appreciated! 🙏

**Comment by rafatbiin** [comment]
hello, @snowp @tonya11en @phlax sorry to bug you again. I'm having difficulty finding a formula here that I can apply across services in a mesh. my objective is, in a normal situation I don't want to reject retries but my retry budget should be such that it'll still safeguard me from a retry storm. From your expertise, how do you think one should calculate `min_retry_concurrency` and `budget_percent` for a service-to-service retry link which achieves the above objective?

**Comment by rafatbiin** [comment]
also, I was reading finagle implementation of retry budget: https://finagle.github.io/blog/2016/02/08/retry-budgets/ -> which uses retry per sec metrics, which is much easier to comprehend and understand than active requests which are unpredictable. with retry per sec, I can easily calculate it for my service and come up with a recommended number. any reason why we didn't choose this implementation?
