### ISSUE TITLE
a configuration yaml file for http static proxy

### ISSUE THREAD

**Issue by Webster-Yang** [envoyproxy/envoy#25676]
Is there a configuration yaml file for http static proxy

**Comment by soulxu** [comment]
@Webster-Yang not quite sure what static proxy you pointed here, if you are looking from HTTP proxy with some static routes, you can take a look at this example https://github.com/envoyproxy/envoy/tree/main/examples/front-proxy, and under the example directory, there are a lot of different examples.

**Comment by phlax** [comment]
if the question is about serving static files, that is not something that Envoy currently does
