### ISSUE TITLE
Resultstore has stopped working (or gone non-public)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25682]
We stream bazel results and resources from CI to resultstore which can be helpful sometimes debugging CI issues, and takes significant resources in terms of time/bandwidth

Now when i try to browse to any pages i get 

```
 Oops, page not found.

Make sure the address is correct. 
```

**Comment by phlax** [comment]
cc @alyssawilk 

@lizan im wondering if this is the latest manifestation of token-bucket api cred changes

**Comment by alyssawilk** [comment]
@KBaichoo I think this relates to the turndown email we got which we thought was a no-op :-/
What's the timeline for just moving over to engflow?

**Comment by KBaichoo** [comment]
@krajshiva has all of the engflow context. Maybe Kirti can run throug the steps to re-enable this.

**Comment by krajshiva** [comment]
Eng-flow RBE is moving slow but we are making progress.
This probably is related with what @alyssawilk mentioned. I have enabled result store API for envoy ci project. Let me know if  result store access is fixed.

**Comment by phlax** [comment]
great that seems to have fixed it, thanks @krajshiva
