### ISSUE TITLE
High CPU when load testing WebSockets with ExtAuthz

### ISSUE THREAD

**Issue by catalin-me** [envoyproxy/envoy#25685]
*Title*: High CPU when load testing WebSockets with ExtAuthz

*Description*:
Our team is load-testing over 5 million concurrent WebSocket connections through Envoy configured to communicate with an ExtAuthz server for request validation. The load test starts, the connections get established, everything starts to run normally and then a sudden spike in CPU for 1-2 minutes. We are trying to find the root cause for this, but are unable to pinpoint the exact reason.

Are there any indications of how the ext_authz requests might be queued up or somehow falling behind in processing?

Any indication of where we should look is of immense value. Thank you very much for your time and patience!

**Comment by phlax** [comment]
@esmet @pradeepcrao @ggreenway @alyssawilk

**Comment by alyssawilk** [comment]
No ideas offhand.  Any chance you can get a flame graph?

**Comment by catalin-me** [comment]
@alyssawilk Unfortunately, I cannot provide a flame graph yet, but I am working on it. Below you can look at the metrics from a 4-hour span where we ran a WebSocket load test that established 1M concurrent connections through Envoy sending and receiving ping-pong messages to and from the upstream test service every 1 second. Envoy is configured with an ext_authz gRPC server with keepalive that handles a no-op validation.

Here are the keepalive configuration parameters for the gRPC ext_authz server:

```
var kasp = keepalive.ServerParameters{
	MaxConnectionIdle:     15 * time.Second, // If a client is idle for 15 seconds, send a GOAWAY
	MaxConnectionAge:      30 * time.Second, // If any connection is alive for more than 30 seconds, send a GOAWAY
	MaxConnectionAgeGrace: 5 * time.Second,  // Allow 5 seconds for pending RPCs to complete before forcibly closing connections
	Time:                  5 * time.Second,  // Ping the client if it is idle for 5 seconds to ensure the connection is still active
	Timeout:               1 * time.Second,  // Wait 1 second for the ping ack before assuming the connection is dead
}
```

Below is a chart showing the active connections reported by the Envoy instances.

<img width="660" alt="Screenshot 2023-03-08 at 12 02 33" src="https://user-images.githubusercontent.com/52822073/223990742-a58b3320-39f3-4a34-999d-bdc5c902306c.png">

There are visible dents in the active connections reported by Envoy. I presume these are from some of the connections from the original client to the upstream service being re-established for some reason (currently investigating further).

Below is a graph of the Envoy CPU spikes.

<img width="1806" alt="Screenshot 2023-03-08 at 11 58 24" src="https://user-images.githubusercontent.com/52822073/223991073-0aec2e53-34b5-4bd6-94a4-334c8875a587.png">

The Envoy instances have periodic CPU spikes, which are mapped 1:1 to the ext_authz server's CPU spikes (seen below).

<img width="1854" alt="Screenshot 2023-03-08 at 11 59 17" src="https://user-images.githubusercontent.com/52822073/223991384-13b2c323-acad-4ccd-b96d-6b580a0ed1f6.png">

My presumption is that at certain times the original client's connections are re-established for unknown reasons at times when the connection pool between Envoy and the ext_authz server is empty due to the timeout settings. I also think that it's normal for Envoy to have these CPU spikes when the connection pool is created or emptied.

Do you have any suggestions regarding what next steps we could take? Any suggestions are highly valuable. Thank you!

**Comment by alyssawilk** [comment]
I mean you could see if any of your monitored stats have correlating spikes, or see if there's anything suspicious in logs (which  you could turn up for one load test) during the high CPU interval, but other than that flame graphs are the way to go.   There's too many things that could be happening otherwise.
