### ISSUE TITLE
question: Dynamic TLS materials for MetricsService cluster

### ISSUE THREAD

**Issue by freddygv** [envoyproxy/envoy#25700]
I would like to configure a [MetricsService](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/metrics_service.proto) stats sink to export metrics from Envoy, but the TLS certificates will not be available at bootstrap time.

After reading docs/issues and running small tests it seems that:
1. Stats sinks such as MetricsService must be defined statically at bootstrap.
2. The cluster for a metrics service stats sink must also be defined statically at bootstrap.
3. An open bug [#19618](https://github.com/envoyproxy/envoy/issues/19618) prevents configuring a static cluster with SDS via ADS.
4. Clusters provided via ADS/CDS with the same name as a static cluster do not overwrite the static cluster.

Given these four points, are there any other options available for providing TLS materials for communication with a stats sink dynamically?

Also if any of those four points are inaccurate, let me know.

Thank you

**Comment by mattklein123** [comment]
As a hack you could loop back to the local Envoy which can do the dynamic loading?

**Comment by freddygv** [comment]
Got that working and it's better than the alternatives, thanks!
