### ISSUE TITLE
Use absl thread annotations

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2571]
In various places we have locks and lock-protected variables, we should use https://github.com/abseil/abseil-cpp/blob/master/absl/base/thread_annotations.h to provide hints to the compiler and sanitizers for `GUARDED_BY` etc.

There's some investigation to be done to find a solution that works cleanly on Clang OS X, see https://github.com/envoyproxy/envoy/pull/2527 for example. Otherwise, it mostly works today and we can use these annotations once OS X is resolved.

We should switch the style guide to require them for new code, and then add missing annotations to existing code once this is in place.

**Comment by jmarantz** [comment]
We now have thread annotations working and usable in the system, and though the entire system hasn't been annotated or converted from std::mutex to absl::Mutex yet, I think this bug can likely be closed.  WDYT?

**Comment by mattklein123** [comment]
SGTM.
