### ISSUE TITLE
Global Load balancing method in Envoy

### ISSUE THREAD

**Issue by Har-IT-TechWide** [envoyproxy/envoy#25712]
Hi 

I wanted to use envoy proxy as a Global load balancing method. is there any way to how to use it?

Exaample: I have 2 LTM endpoints. So i want to use both LTMs in Envoy load balancing Endpoints and I wanted to send the requests to one LTM only If that LTM is Down then all the requests need to go to Other LTM only.

Can any one suggest me the code method if we can use envoy?

**Comment by daixiang0** [comment]
You can check this doc: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancing.
