### ISSUE TITLE
Dynamic route table in HTTP connection manager

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25713]
I would like to apply custom routing mechanism, where unknown routes are inspected mid-flow and then by some custom logic, there would be a routing rule to decide to which upstream cluster to send the request to.

For example, say that there's a pseudo-function that has the following logic:
```
string chooseCluster(string path) {
  if (MeetsInternalBusinessLogic(path))
    return "clusterA";
  else
    return "clusterB";
}
```

The implementation of "MeetsInternalBusinessLogic" is not something that can be managed statically, otherwise I would have manually configured the .yaml by known routes.

I read the documentation and wanted to make sure I follow the correct path here. Can the [Virtual host](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost)'s "matcher" config help here? Would it be possible to write a custom "matcher" that would take the HTTP ":path" as input, and return the required upstream cluster for that HTTP request? Is there any other way to implement this functionality?

Thanks for helping

**Comment by wbpcode** [comment]
May be a custom `inline_cluster_specifier_plugin` implementation could be helpful? This extension could be used to get upstream cluster name according to the HTTP request headers.

**Comment by ohadvano** [comment]
Thanks, is there an example or documentation that you can share regarding this?
