### ISSUE TITLE
tls: support ed25519 for client cert digital signature

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#25727]
Seems that Envoy cannot verify client certificates signed with ed25519 in TLS1.3:

(from server hello)
```
Acceptable client certificate CA names
CN = localhost
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512
Peer signature type: Ed25519
Server Temp Key: X25519, 253 bits
```

**Comment by adazzi93933** [comment]
Here is the envoy debug log when testing with a ed25519 client cert.

[2023-02-24 15:02:14.384][11395773][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:147] [C0] new connection from 127.0.0.1:50183
[2023-02-24 15:02:14.392][11395773][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:233] [C0] remote address:127.0.0.1:50183,TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
[2023-02-24 15:02:14.392][11395773][debug][connection] [source/common/network/connection_impl.cc:656] [C0] remote close
[2023-02-24 15:02:14.392][11395773][debug][connection] [source/common/network/connection_impl.cc:250] [C0] closing socket: 0
[2023-02-24 15:02:14.392][11395773][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:233] [C0] remote address:127.0.0.1:50183,TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
[2023-02-24 15:02:14.392][11395773][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc:120] [C0] adding to cleanup list

**Comment by ldemailly** [comment]
looking at  https://bugs.chromium.org/p/boringssl/issues/detail?id=530&q=Ed25519&can=1 
-> 
https://github.com/grpc/grpc/issues/24252#issuecomment-909916002
->
https://github.com/google/boringssl/blob/master/ssl/extensions.cc#L437
->
https://github.com/google/boringssl/blob/master/ssl/extensions.cc#L482

it seems we might just need to configure  hs->config->verify_sigalgs

is that somewhere in envoy's code?

**Comment by kyessenov** [comment]
Good find. It's not called anywhere. Not sure if this needs to be another
knob in xDS.

**Comment by ldemailly** [comment]
Alain confirmed on a side build (forcing the constant in the defaults, pending actual config option) that it works so yes, it seems "just" a matter of making that list configurable (or tbh, I wouldn't mind either that boringssl included with envoy would just get patched)

**Comment by adazzi93933** [comment]
here are some details ... I struggled a bit with  the envoy/boringssl integration. I first compiled bssl with cmake/ninja on main but envoy has 2 boringssl patches that got in the way. so i used the  main-with-bazel branch to create a boringssl.tar.gz archive.

The patch is simply ...

`✔ XF4P4GJTCF ~/src/envoy/boringssl-git remotes/origin/main-with-bazel > git diff
diff --git a/ssl/extensions.cc b/ssl/extensions.cc
index ba9236035..73f4820e4 100644
--- a/ssl/extensions.cc
+++ b/ssl/extensions.cc
@@ -436,6 +436,7 @@ bool tls1_check_group_id(const SSL_HANDSHAKE *hs, uint16_t group_id) {
 // algorithms for verifying.
 static const uint16_t kVerifySignatureAlgorithms[] = {
     // List our preferred algorithms first.
+    SSL_SIGN_ED25519,
     SSL_SIGN_ECDSA_SECP256R1_SHA256,
     SSL_SIGN_RSA_PSS_RSAE_SHA256,
     SSL_SIGN_RSA_PKCS1_SHA256,`

and in envoy  i referred to it as a file in bazel/repository_locations.bzl...

`diff --git a/bazel/repository_locations.bzl b/bazel/repository_locations.bzl
index 93d4e7fbbc..310a352710 100644
--- a/bazel/repository_locations.bzl
+++ b/bazel/repository_locations.bzl
@@ -109,10 +109,10 @@ REPOSITORY_LOCATIONS_SPEC = dict(
         # 3. Find a commit in BoringSSL's "master-with-bazel" branch that merges <boringssl_revision>.
         #
         # chromium-105.0.5195.37 (linux/beta)
-        version = "098695591f3a2665fccef83a3732ecfc99acdcdd",
-        sha256 = "e141448cf6f686b6e9695f6b6459293fd602c8d51efe118a83106752cf7e1280",
-        strip_prefix = "boringssl-{version}",
-        urls = ["https://github.com/google/boringssl/archive/{version}.tar.gz"],
+        version = "",
+        sha256 = "e1934a2dc400eb3a6f33344d9bd35812e013b695a2734bed77a663170417ef9d",
+        strip_prefix = "boringssl",
+        urls = ["file:///Users/adazzi/src/envoy/boringssl.tar.gz"],`
