### ISSUE TITLE
CI/maintainer PR notifier may be lacking some creds

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25742]
The pr notifier failed today with

```console

github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 13.64.10.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url":

```

altho it should be authenticated as it has:

```console

 10   pr_notifier:
 11     permissions:
 12       contents: read # to fetch code (actions/checkout)                                                                                                                       
 13       statuses: read # for pr_notifier.py                                                                                                                                     
 14       pull-requests: read # for pr_notifier.py   
```

not sure if something is missing here or just a github transient - rerunning worked

**Comment by phlax** [comment]
i havent seen this again, so im guessing this was just a transient and not a permissions/limit issue

**Comment by joycebrum** [comment]
This actually seems like a [Github rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) issue. This part "Authenticated requests get a higher rate limit." makes me think that the api requisitions being made are not authenticated, thus the rate limit is even smaller.

These command https://github.com/envoyproxy/envoy/blob/4cd72b14c4a8162242e4569ccab633bc6fe90c6a/.github/actions/pr_notifier/pr_notifier.py#LL141C44-L141 and https://github.com/envoyproxy/envoy/blob/4cd72b14c4a8162242e4569ccab633bc6fe90c6a/.github/actions/pr_notifier/pr_notifier.py#L132 call the Github api with no BEARER TOKEN, thus the rate limit to this reqs is 60 to core reqs and 10 to search reqs.

When using authenticated reqs, the rate limit is 5000 to core and 30 to search.

**Comment by phlax** [comment]
> ... makes me think that the api requisitions being made are not authenticated, thus the rate limit is even smaller.

yep - i had a similar thought - but not sure what could be missing or whether there was some other cause - i didnt see it before/since

**Comment by phlax** [comment]
arggh pygithub 8/

not sure why we are using the private (and not very pythonic) `requestJsonAndCheck` but it can take a headers arg so i guess we can use that

i think i will shift this script to bazel and use `gidgethub` instead medium term, but for now ill try and fix with what is there

testing this is pretty difficult before it lands i think
