### ISSUE TITLE
`bazel.tsan` tests are very flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25760]
I noticed this previously, but since resolving other flakes this has now become a pretty regular feature

This is easily reproducible locally running the tsan tests - in fact i struggled to ever get them to pass - i will investigate this further

What is interesting is that there are always multiple failures, if any - eg:

```console

/test/extensions/filters/http/rbac:rbac_filter_integration_test          FLAKY, failed in 2 out of 6 in 321.6s
  Stats over 6 runs: max = 321.6s, min = 257.1s, avg = 280.2s, dev = 26.7s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/filters/http/rbac/rbac_filter_integration_test/shard_3_of_4/test_attempts/attempt_1.log
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/filters/http/rbac/rbac_filter_integration_test/shard_4_of_4/test_attempts/attempt_1.log
//test/integration:multiplexed_integration_test                           FLAKY, failed in 2 out of 10 in 312.0s
  Stats over 10 runs: max = 312.0s, min = 201.6s, avg = 260.9s, dev = 34.9s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/multiplexed_integration_test/shard_5_of_8/test_attempts/attempt_1.log
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/multiplexed_integration_test/shard_8_of_8/test_attempts/attempt_1.log
//test/integration:filter_integration_test                              TIMEOUT in 2 out of 13 in 313.4s
  Stats over 13 runs: max = 313.4s, min = 255.0s, avg = 277.8s, dev = 16.9s
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/filter_integration_test/shard_1_of_12/test.log
  /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/bazel-out/k8-dbg/testlogs/test/integration/filter_integration_test/shard_1_of_12/test_attempts/attempt_1.log

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=129052&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137&l=7976

its always the same integration tests that fail, or rather its always _some_ of the same ones, as not all fail every time it does

this seems to point to some underlying test framework issue - or maybe there just are a lot of tsan failures that are not always being exposed for some reason

running the tests individually never seems to trigger anything

**Comment by phlax** [comment]
cc @danzh2010 who i believe has a fix for at least one of the flaking tests

**Comment by phlax** [comment]
highlighting the issue in analytics

![imagen](https://user-images.githubusercontent.com/454682/222472102-2b77c594-a7af-4132-a3c2-f93399bc31dc.png)

**Comment by phlax** [comment]
> in fact i struggled to ever get them to pass

the reason for this was that i was running locally due to not having the `ENVOY_RBE` env var set which meant that `ci/do_ci.sh` ignored my local bazel config

**Comment by phlax** [comment]
reopening this as we are now seeing it a lot without rerunning flakes

**Comment by alyssawilk** [comment]
Closing in favor of opening individual test bugs
