### ISSUE TITLE
Upgrade the LuaJIT version used in Envoy

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#25763]
*Title*: *Upgrade the LuaJIT version used in Envoy*

*Description*:
The current LuaJIT version used in Envoy is 1d8b747c161db457e032a023ebbff511f5de5ec2, which is created on 2020-10-12, more than 2 years ago. Plenty of bugfix and new features happen after that. 

For example, https://github.com/envoyproxy/envoy/blob/6c18a51ea75b8b184e65acdb8364403df4b35e37/tools/code_format/check_format.py#L726-L730 claims that lua_pushlightuserdata is unsafe but this problem is already fixed in the latest LuaJIT.

I recommend upgrading the version to https://github.com/LuaJIT/LuaJIT/commit/a04480e311f93d3ceb2f92549cad3fffa38250ef, which is also the version used in the latest OpenResty: https://github.com/openresty/luajit2/commits/v2.1-20230119.

If this is acceptable, I can work on this and update the [patch](https://github.com/envoyproxy/envoy/blob/main/bazel/foreign_cc/luajit.patch) we apply to the LuaJIT.

**Comment by zuercher** [comment]
Seems reasonable to upgrade.

cc @wbpcode

**Comment by wbpcode** [comment]
SGTM. Do you willing to create a PR for this?

**Comment by spacewander** [comment]
Yes. Please assign it to me.
