### ISSUE TITLE
envoy.filters.http.ext_authz: ability to pass connection metadata in authz request  

### ISSUE THREAD

**Issue by nabam** [envoyproxy/envoy#25762]
*Title*: *Add ability to pass connection metadata in authz request*

*Description*:
External Authorization http extension currently supports passing dynamic filter metadata related to http request. I would like to propose a capability to pass downstream connection dynamic metadata typically added by transport socket extensions.

A particular problem I'm trying to solve is propagation of `envoy.transport_socket.peer_information/peer_identity` from [extensions.transport_sockets.alts.v3.Alts ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/alts/v3/alts.proto.html#extensions-transport-sockets-alts-v3-alts) to the authorization checks.

I see 2 options: 
1. In [ext_authz.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_authz/ext_authz.cc#L46-L66) walk through both `decoder_callbacks_->streamInfo().dynamicMetadata()` and `decoder_callbacks_->connection()->streamInfo().dynamicMetadata()` to populate `filter_metadata` and `typed_filter_metadata` fields in authz request. Request metadata should take precedence in an *unlikely case* when the same namespace is present in both connection metadata and requests metadata. Optionally this behaviour can be only enabled using an extra flag in configuration.

1. Add `connection_metadata_context_namespaces` and `connection_typed_metadata_context_namespaces` fields to [extensions.filters.http.ext_authz.v3.ExtAuthz proto](https://github.com/envoyproxy/envoy/blob/bfa849bc598870033dbbc11ae17c9abb273e19e5/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L87-L107); and add `connection_metadata_context` field to the [auth attribute_context proto](https://github.com/envoyproxy/envoy/blob/42f82c257a049589b5c15788c774342268124921/api/envoy/service/auth/v2/attribute_context.proto#L160).

Happy to implement it myself after discussing the options above.

*Relevant Links*:
- `metadata_context_namespaces` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-extauthz

**Comment by zuercher** [comment]
cc @esmet @pradeepcrao

**Comment by nabam** [comment]
@zuercher this feature request is still relevant? Is there a chance to get some feedback?
