### ISSUE TITLE
Pending Queue as Priority Queue

### ISSUE THREAD

**Issue by eightnoteight** [envoyproxy/envoy#25783]
*Title*: *Convert Pending Queue as a Priority Queue to only drop tier-2 requests during circuit breaking*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Systems go into high load scenarios for various reasons, circuit breaking helps a lot in such scenarios to ensure that systems don't go into cascading outages and will become stable as soon as enough capacity is added.

But the problem is that during that effected period the business would be impacted and sometimes the excessive load would be coming from tier-2 workloads and the capacity required might be exponential, in such cases we tune our load shedding feature flags to cut off all such tier-2 load.

It would be nice to do that load-shedding automatically. Currently the requests are dropped when it reaches max size of the pending queue, if each request priority is taken from a header and use pending queue as a priority queue. it would greatly help in serving tier-1 requests first and if there is enough capacity tier-2 requests as well else drop them.

one other advantage of such priority queue is to priority health checks over normal requests, so that health check requests are given higher priority and it would act as a safe guard before the `healthy_panic_threshold` triggers

**Comment by zuercher** [comment]
cc @snowp

**Comment by dengwxn** [comment]
@0xgirish We're also interested in this feature. Are you able to find any guidance on how to implement this? Thanks!
