### ISSUE TITLE
Envoy does not build behind a proxy

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#2578]
*Title*: Envoy does not build behind a proxy

*Description*:
Normally when behind a proxy one can specify proxy environment (`HTTP_PROXY`, `https_proxy`, etc.) variables which tells git and other tools to use a proxy when making outbound http/-s requests. However, due to parts of the envoy build chain ignoring these settings bazel is unable to pull down external repositories. 

Example of what it looks like:
```
 ERROR: /home/snowp/.cache/bazel/_bazel_snowp/c3ec2354b418a2642552c8e873fd0f54/external/com_lyft_protoc_gen_validate/validate/BUILD:35:1: no such package '@com_github_golang_protobuf//proto': failed to fetch com_github_golang_protobuf: # cd .; git clone https://github.com/golang/protobuf /home/snowp/.cache/bazel/_bazel_snowp/c3ec2354b418a2642552c8e873fd0f54/external/com_github_golang_protobuf
Cloning into '/home/snowp/.cache/bazel/_bazel_snowp/c3ec2354b418a2642552c8e873fd0f54/external/com_github_golang_protobuf'...
fatal: unable to access 'https://github.com/golang/protobuf/': Failed connect to github.com:443; Operation now in progress
2018/02/11 04:40:35 exit status 128
 and referenced by '@com_lyft_protoc_gen_validate//validate:go_default_library'
```

The fix involves updating `io_bazel_rules_go` to a newer version (we need [this](https://github.com/bazelbuild/rules_go/commit/812c172b921cafaa27a58bba2d2cd37ace296b88)) + ensuring that all dependencies use the Skylark `git_repository` instead of the native `git_repository` (see [here](https://github.com/bazelbuild/bazel/issues/3893)). 

I've already started working on this (see https://github.com/lyft/protoc-gen-validate/pull/57 + https://github.com/lyft/protoc-gen-validate/pull/59), so I'm mainly filing this for informational + tracking purposes. Feel free to assign me to this issue.

**Comment by mattklein123** [comment]
@snowp thanks a lot for working on this. I would really love to get this solved once and for all and clearly documented somewhere. cc @jmillikin-stripe

**Comment by snowp** [comment]
Getting a working copy of rules_go into envoy is currently blocked on our unix toolchain. Envoy uses a forked toolchain which defaults to g++ instead of gcc, which means we can't compile the C files that rules_go brings in (see https://github.com/envoyproxy/envoy/issues/839).

This is the current workaround that I've been using internally:

* override rules_go to use version 0.9.0 (I build envoy as a local_repository, so I just override it in my WORKSPACE file)
* override data-plane-api to a version to include https://github.com/envoyproxy/data-plane-api/commit/96289bc92c0b3d87ec9e798076ee50dcf1ad0413 (I just use sed to replace it in `bazel/repository_locations.bzl`)
* build envoy once (this fails, but it puts the rules_go files in the right place)
* `sed -i bazel-project/external/io_bazel_rules_go/go/private/rules/stdlib.bzl -e "s/CC.*$/CC\": \"$(which gcc)\",/g"`
* build envoy again

Alternatively you can point to my branch in this PR, although you'll still need the override for the CC path in rules_go. 

This is super hacky but seems to get everything working. I can push to get the data-plane-api version in envoy bumped to avoid having to override that, but after that I'm not sure how to proceed as long as we need to use `g++` over `gcc` for unix toolchains... I might look into getting Bazel to add a `c_executable` to the cpp fragment that can be used to specify a compiler that's only used for C files.
