### ISSUE TITLE
Configuring BoringSSL with Envoy

### ISSUE THREAD

**Issue by lonials** [envoyproxy/envoy#25803]
*Title*: *Configuring BoringSSL flag with Envoy*

*Description*:
I am looking to use the BoringSSL flag (X509_V_FLAG_USE_CHECK_TIME ) that seems not supported by the envoy as per the documentation. I am trying to change the default CRL time validation logic and looking to increase CRL's validity beyond what is provided in the CRL's nextUpdate field. One idea I got is to write my own [custom_validator_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-certificatevalidationcontext) and provide X509_V_FLAG_USE_CHECK_TIME flag to the X509_STORE_set_flags method in a custom validator. Is there any other easier or alternate way to provide this flag in envoy via runtime configuration? Any info or guidance will be helpful.

**Comment by zuercher** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
I think your only options are to either make a custom validator as you said, or add a config option to the default validator. There's no way to specify different flags via runtime.

**Comment by lonials** [comment]
Thanks for your response. Please provide a documentation link or an example to add a config option to the default validator. I am not able to find it myself, I would like to understand a bit more about this option.

**Comment by ggreenway** [comment]
It would be a PR roughly similar to https://github.com/envoyproxy/envoy/pull/20115
