### ISSUE TITLE
golang filter extension: increase fuzz coverage

### ISSUE THREAD

**Issue by doujiang24** [envoyproxy/envoy#25807]
Seems the fuzz for the ext_proc filter could be a good example to follow up.
https://github.com/envoyproxy/envoy/pull/17636

key points:
1. random downstream request
2. random upstream response
3. random Go filter behavior: sync/async, sleep in Go, GetHeader/SetHeader, and other APIs.

In my opinion,

1 & 2 could be the standard fuzz way, but may not be very useful for golang filter, since golang filter reuses the existing Envoy C++ APIs mostly. But it is still good to have it.

3 might be tailored for golang filter, similar to the [existing basic test filter](https://github.com/envoyproxy/envoy/tree/main/contrib/golang/filters/http/test/test_data/basic).
That is, we have multiple test modes in the test Go filter, https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/test_data/basic/filter.go#L22-L29
And we enable them randomly in the fuzz test. (we only enable some of the patterns in the base test, non-fuzz mode)

**Comment by adisuissa** [comment]
Thanks!
IMHO the ext_proc fuzzer might be an overkill for this use-case, as it uses an integration test, which I'm not sure if needed here (and will decrease performance).
I suggest looking at [ext_authz_fuzz_test](https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/ext_authz/ext_authz_fuzz_test.cc) and the [generic http fuzzer](https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/common/fuzz/http_filter_fuzzer.h) for bullets 1 & 2 above.
We do not have the Go-fuzzing infrastructure in place, and do not know what 3 requires or whether it would make sense just to emulate these behaviors in the fuzz tests for 1 and 2.

**Comment by doujiang24** [comment]
Thanks, @adisuissa 

> I suggest looking at [ext_authz_fuzz_test](https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/ext_authz/ext_authz_fuzz_test.cc) and the [generic http fuzzer](https://github.com/envoyproxy/envoy/blob/main/test/extensions/filters/http/common/fuzz/http_filter_fuzzer.h) for bullets 1 & 2 above.

Great, seems it's a better example to follow up after a quick look, I'll try it.

> We do not have the Go-fuzzing infrastructure in place, and do not know what 3 requires or whether it would make sense just to emulate these behaviors in the fuzz tests for 1 and 2.

The interaction between Go and Envoy could be complicated, since Go could callback Envoy APIs after Envoy invokes into Go.
So, it might be a bit complicated to emulate these behaviors in a MockClass.

Anyway, I think 1 and 2 is a good start for us.
