### ISSUE TITLE
MainCommonTest (pending) breaks SignalsTest when run in same binary in coverage tests.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2580]
*Description*:
 MainCommonTest works fine in coverage tests, but it appears to break SignalsTest when run in the same process.  It appears that MainCommon doesn't completely clean up after itself, most likely due to a bug in SignalAction.  So for now, we can test MainCommon but can't measure its test coverage.

[optional *Relevant Links*:]
MainCommonTest doesn't exist yet, but is in https://github.com/envoyproxy/envoy/pull/2568. Writing this issue now so I can reference it in a TODO in the code.

**Comment by jmarantz** [comment]
pinging the bug to make it not stale.  This is one of several cases where Envoy has some kind of global state that would be good to clean up.

**Comment by mattklein123** [comment]
@jmarantz agreed marking help wanted. You and I will continuing fighting against the statics!
