### ISSUE TITLE
RFC: cache filter should be disable-able

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#25819]
Current state of cache filter is that it can only be configured at the listener level, and, if present, must be configured with a functioning cache implementation.

I am proposing two things:
1. that it should be possible to configure the cache per-route, as a user may wish to have different cache behaviors (or instances) on distinct routes.
2. that it should be possible to configure the cache filter as disabled, for two reasons:
  a. because a likely desirable configuration is to have no cache in envoy by default, but some subset of routes cached (or a cache by default but some subset of routes *not* cached.)
  b. for our use-case, we like to have a common static config with many filters, and configure the filters we want active for a given sidecar via ECDS. When cache filter can't be disabled, it can't be integrated with this system.

My proposed API for this retains the cache filter's current behavior for any existing configuration - if the config is empty, an exception is thrown, and if a cache is configured it is active. The two changes I would make are:
1. make the existing config proto also useable per-route, functioning as a complete override of the listener-level config. I believe this is the best way to do per-route config, as partial overrides are hard to document unambiguously, and this mechanism for overriding is already common in many filters.
2. replace [in the proto](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/cache/v3/cache.proto#L54)
    ```
    google.protobuf.Any typed_config = 1 [(validate.rules).any = {required: true}];
    ```
    with
    ```
    oneof cache_config {
      [(validate.rules).any = {required:true}];
      google.protobuf.Any typed_config = 1;
      bool disabled = 5 [(validate.rules).bool = {const: true}];
    }
    ```
    and make this added option functional.

**Comment by toddmgreer** [comment]
It would be good to support selective overrides. It makes no difference when the per-listener config is `disabled`, but configs with thousands of routes can save a lot of config size by putting site-wide settings in the per-listener config. For example, one may need to specify per-route `key_creator_params`, without wanting to  repeating things in every route. For non-repeated proto fields[1], making them `optional` is simple and clear enough, such that a per-route config can choose which fields to override. Repeated fields are less simple, but I think there's precedent (though I can't remember which filter it's in).

[1] max_body_bytes, key_creator_params, key_creator_params.exclude_scheme, and key_creator_params.exclude_host

**Comment by ravenblackx** [comment]
One filter that allowed partial overrides was the one I wrote, `FileSystemBufferFilter`, and I very much regret doing it that way because:
* It's confusing for users since most filters that support per-route config either do *very limited* per-route config (like just disabling), or completely override the listener-level config, so being different is surprising.
* It's difficult to clearly document what partially overridden config means (again, in part because it's different from the common behavior).
* The implementation becomes tangled and difficult to test (versus complete replacement is very simple).

Plus, in the case of cache filter, it's *probably* quite a small config, that is unlikely to have many custom overrides.

Also, supporting partial overriding would be significantly more complicated in the case of cache because the filter requires a sub-extension (the cache implementation), which means not only would it need to be documented that overrides are being merged, but every sub-extension would need to also be implemented with support for merging partial configs.

Which is *extra* difficult, because unfortunately there's no support for merging configs at config-time, it has to be done per-filter-instance during `decodeHeaders`. The per-route-config doesn't have access to the per-listener-config during its construction. Which makes merging configs expensive anywhere - and in the case of cache filter, which currently instantiates a cache from the config at config-time, would mean there'd need to be another layer of capturing a separate generic proto message for "per-route cache instance dynamic features" and somehow having the cache instance handle that (and maybe select a different cache instance!) for each filter instantiation. Complete override, on the other hand, means that the per-route-config is guaranteed to have access to everything it needs at config-time.

**Comment by toddmgreer** [comment]
We'll need a form of partial override if we want to avoid the complexities with the HttpCache sub-extension (which I agree are major concerns). In particular, we'll need to specify `typed_config` in the per-filter config, and not in the per-route config. I'm in favor of this.

In the deployments I'm involved with, I expect to need to set `key_creator_params` per-route, and everything else per-listener. Repeating the per-listener config in each of many thousands of routes is not desirable.

I don't see a way to avoid some form or merged config.

**Comment by ravenblackx** [comment]
So IMO it is good to *also* allow overriding `typed_config` in the per-route config, so that the user can elect to have different cache versions. But I'm okay with taking that as "one piece" of the config that can be inherited.

Also worth noting that if you do inheritable parent configs, it's no longer okay to use the `mostSpecific` helper function, because there's potential for a user configuring e.g.
```
listener {
  your_filter_config{a:1 b:2 c:3}
  virtual_host {
    your_filter_config{b: 12}
    route {
      your_filter_config{c: 42}
    }
  }
}
```
after which, with inheriting, the user would expect the filter in that route to act with config {a: 1, b: 12, c: 42}, i.e. you have to merge recursively.

**Comment by ravenblackx** [comment]
This model also introduces difficulty for validation, because of the fact that configs can't be merged at config-time, only per filter-instance - if you do it this way there is no way to validate that a required value is set, unless you require that the listener-level config sets values that it doesn't use (which is a problem for `typed_config` right now, in that being required to set a cache instance at the listener level means that you can't have a cache apply only at a higher level.)

You can validate it at filter-time and barf 5xx errors, but what you *want* is to validate it at config-time, which you can't.

If "typed_config unset implies don't cache" is a valid configuration then this issue can resolve itself.

Actually I'm not sure I understand *why* we can't access the virtual_host and listener level configs for the filter during `createRouteSpecificFilterConfigTyped` - if we could then inheritance-based configs would be much much simpler to implement and all my problems with this would evaporate.

**Comment by ravenblackx** [comment]
I mean something like `route->traversePerFilterConfig`, but for traversing the config protos during `createRouteSpecificFilterConfigTyped`, rather than traversing the "final configs" during/after `decodeHeaders` when it's already way too late to be merging configs efficiently.

**Comment by ravenblackx** [comment]
Filed #25903 to try to address the question of whether we can make a variant of `createRouteSpecificFilterConfigTyped` that better supports inheritance-based configuration, so I've paused the inheritance branch of this issue for now. Going for just the disabling aspect instead.

**Comment by ravenblackx** [comment]
The filter now supports disabled state, and the treatment of inheritance is deferred to #25903, so this issue is done.
