### ISSUE TITLE
gRPC HTTP/1.1 reverse bridge and gRPC-JSON transcoding

### ISSUE THREAD

**Issue by aledzu** [envoyproxy/envoy#25815]
*Title*: gRPC HTTP/1.1 reverse bridge and gRPC-JSON transcoding

*Description*:
> In my current setup, I have an HTTP/1.1 server, gRPC and Protobuf agnostic on one side and a gRPC client on another.
>
>I have the following questions:
Is there a filter which is capable of doing the conversion from a gRPC request to an HTTP/1.1 request and transcoding of the body?
Is there a filter which can be combined with reverse_bridge for this purpose?
What would be the steps for developing such a filter?

**Comment by zuercher** [comment]
Envoy has a gRPC bridge, gRPC reverse bridge and gRPC transcoder [filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/http_filters). I think some combination of filters probably does what you're looking for.

**Comment by aledzu** [comment]
How I have the HTTP/1.1 server I have to use reverse-bridge but gRPC transcoder filer "allows a RESTful JSON API client to send requests to Envoy over HTTP and get proxied to a gRPC service", 

so I think it is not possible to combine them?

**Comment by libratiger** [comment]
@aledzu In your case, the best solution maybe upgrade your server from http1.1 to http2， this can reduce many problem.

**Comment by aledzu** [comment]
Yes @libratiger  you are right, but still there is no filter which is capable of transcoding messages between  gRPC client and HTTP server, right?

**Comment by libratiger** [comment]
> Yes @libratiger you are right, but still there is no filter which is capable of transcoding messages between gRPC client and HTTP server, right?

As far as I know, there is no such extension, because in most situation, the hard part is the client can not using the grpc method, but the server can provide。
