### ISSUE TITLE
logging: add mechanism to switch to fine-grained logging in a live server

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#25826]
Fine-grained logging currently has to be enabled on the command-line. There is also an internal  C++ API to flip to a running system to fine-grained mode, but there are two issues with it:
 * it has no call-sites outside tests
 * it has what looks to me like a thread-safety bug, writing a non-atomic bool controlling the logging mode, and referenced by the log macros.

We should remedy these by
 * auditing the flipping of logging modes for thread safety. I think both loggers are thread safe but we should convince ourselves that flipping modes in a live system is also safe, and make it so.
 * we should add a new admin /logging endpoint to flip to and from fine-grained mode,

@KBaichoo FYI

**Comment by KBaichoo** [comment]
cc @botengyao

**Comment by botengyao** [comment]
Thanks! I think it makes sense to add an admin endpoint, will pick this up.
