### ISSUE TITLE
build tcp_stats extension failed caused by compatibility of "tcp_info"

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#25839]
*Title*: *build tcp_stats extension failed caused by compatibility of "tcp_info"*

*Description*:
The struct `tcp_info` member `tcpi_bytes_sent` was added in Linux kernel [4.19-rc1](https://github.com/torvalds/linux/commit/ba113c3aa79a7f941ac162d05a3620bdc985c58d). When running a version prior to that, we will not have access to this member. So we need add some check for it. such as
```
#if LINUX_KERNEL_CODE >= KERNEL_VERSION(4,19,0)
 dosomething for access the member `tcpi_bytes_sent` of  `struct tcp_info`
#endif
```

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
source/extensions/transport_sockets/tcp_stats/tcp_stats.cc: In member function 'void Envoy::Extensions::TransportSockets::TcpStats::TcpStatsSocket::recordStats()':
source/extensions/transport_sockets/tcp_stats/tcp_stats.cc:147:28: error: 'struct tcp_info' has no member named 'tcpi_bytes_sent'; did you mean 'tcpi_bytes_acked'?
  147 |                  tcp_info->tcpi_bytes_sent);
      |                            ^~~~~~~~~~~~~~~
      |                            tcpi_bytes_acked

```

[optional *Relevant Links*:]
https://github.com/torvalds/linux/commit/ba113c3aa79a7f941ac162d05a3620bdc985c58d

**Comment by zuercher** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
Do the kernel headers include a notion of which version they are from? If you can craft a way to detect this at compile time and post a PR, we can consider it. 

But the 4.19 kernel is nearly 5 years old, and adding conditional compilation will make the code and tests more complicated. It may be best to just not compile this extension if your kernel is that old.

**Comment by sky92zwq** [comment]
it occurs on ubuntu 18.04, 
and how to not compile this extention?
