### ISSUE TITLE
tracer: skywalking extension does not create new tracecontext if sw8 header invalid

### ISSUE THREAD

**Issue by JaredTan95** [envoyproxy/envoy#25842]
*Title*: *skywalking extension does not create new tracecontext if sw8 header invalid*

*Description*:
If the envoy received an invalid `sw8` header, skywalking extension will return directly:

https://github.com/envoyproxy/envoy/blob/59d7e70eba4b8fb74088eaa8a19afefe6846d329/source/extensions/tracers/skywalking/skywalking_tracer_impl.cc#L74

Maybe should start a new (entry) span will be more sensible.

**Comment by zuercher** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
Sounds reasonable.

**Comment by wbpcode** [comment]
Yes. cc @StarryVae

**Comment by StarryVae** [comment]
i think this issue can be closed.
