### ISSUE TITLE
Redis proxy example with downstream protocol error after connection

### ISSUE THREAD

**Issue by midnightcodr** [envoyproxy/envoy#25865]
I am following the example at https://github.com/envoyproxy/envoy/tree/main/examples/redis, `docker-compose` brings up both the listener and worker just fine. However, while trying to issue a command (any commands actually, for example, PING, INFO, GET HELLO), the error `downstream protocol error` is returned and redis connection is terminated.

The steps I follow is this: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/redis.html

Been trying to figure out what caused the issue for hours to no avail. Can someone please shed some lights on this? Thanks!

**Comment by zuercher** [comment]
cc @weisisea

**Comment by weisisea** [comment]
Just tried myself and it works on my machine:

```
weisisea@weisisea3 [6:08:54]: ~/github/envoy/examples/redis main
$ docker-compose pull
Pulling proxy ... done
Pulling redis ... done

weisisea@weisisea3 [6:09:03]: ~/github/envoy/examples/redis main
$ docker-compose up --build -d
Creating network "redis_envoymesh" with the default driver
Building proxy
Sending build context to Docker daemon  8.192kB
Step 1/4 : FROM envoyproxy/envoy-dev:latest
latest: Pulling from envoyproxy/envoy-dev
47c764472391: Pull complete
99437f53141e: Pull complete
29eed851ff95: Pull complete
431c7bdb14a9: Pull complete
428974c75bdf: Pull complete
1fd5790b18fd: Pull complete
7c6d744631cc: Pull complete
d2f6ce2252fa: Pull complete
Digest: sha256:b0d164e2dc8870414e18343598fd1dc8d5e43d6363b52cff0dddee586f40fc68
Status: Downloaded newer image for envoyproxy/envoy-dev:latest
 ---> ec47a91ca143
Step 2/4 : COPY ./envoy.yaml /etc/envoy.yaml
 ---> 68e04fbf6969
Step 3/4 : RUN chmod go+r /etc/envoy.yaml
 ---> Running in b2352adbbef4
Removing intermediate container b2352adbbef4
 ---> e93649632878
Step 4/4 : CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "proxy"]
 ---> Running in a228d6d335bc
Removing intermediate container a228d6d335bc
 ---> adc7bbbfd056
Successfully built adc7bbbfd056
Successfully tagged redis_proxy:latest
Building redis
Sending build context to Docker daemon  8.192kB
Step 1/1 : FROM redis@sha256:ed8cba11c09451dbb3495f15951e4afb4f1ba72a4a13e135c6da06c6346e0333
docker.io/library/redis@sha256:ed8cba11c09451dbb3495f15951e4afb4f1ba72a4a13e135c6da06c6346e0333: Pulling from library/redis
461246efe0a7: Pull complete
edee06fdf403: Pull complete
04b7adc9ef61: Pull complete
6f4a4580ec0b: Pull complete
b70fc086369d: Pull complete
242936d47e59: Pull complete
Digest: sha256:ed8cba11c09451dbb3495f15951e4afb4f1ba72a4a13e135c6da06c6346e0333
Status: Downloaded newer image for redis@sha256:ed8cba11c09451dbb3495f15951e4afb4f1ba72a4a13e135c6da06c6346e0333
 ---> 3edbb69f9a49
Successfully built 3edbb69f9a49
Successfully tagged redis_redis:latest
Creating redis_proxy_1 ... done
Creating redis_redis_1 ... done

weisisea@weisisea3 [6:09:19]: ~/github/envoy/examples/redis main
$ docker-compose ps
    Name                   Command               State                                               Ports
------------------------------------------------------------------------------------------------------------------------------------------------------
redis_proxy_1   /docker-entrypoint.sh /usr ...   Up      10000/tcp, 0.0.0.0:1999->1999/tcp,:::1999->1999/tcp, 0.0.0.0:8001->8001/tcp,:::8001->8001/tcp
redis_redis_1   docker-entrypoint.sh redis ...   Up      6379/tcp

weisisea@weisisea3 [6:09:38]: ~/github/envoy/examples/redis main
$ docker run --rm --network host redis:latest redis-cli -h localhost -p 1999 set foo foo
Unable to find image 'redis:latest' locally
latest: Pulling from library/redis
3f9582a2cbe7: Pull complete
241c2d338588: Pull complete
89515d93a23e: Pull complete
65e8ba9473fe: Pull complete
585124038cab: Pull complete
b483de716a47: Pull complete
Digest: sha256:e50c7e23f79ae81351beacb20e004720d4bed657415e68c2b1a2b5557c075ce0
Status: Downloaded newer image for redis:latest
OK

weisisea@weisisea3 [6:09:50]: ~/github/envoy/examples/redis main
$ docker run --rm --network host redis:latest redis-cli -h localhost -p 1999 set bar bar
OK

weisisea@weisisea3 [6:09:55]: ~/github/envoy/examples/redis main
$ docker run --rm --network host redis:latest redis-cli -h localhost -p 1999 get foo
foo

weisisea@weisisea3 [6:10:06]: ~/github/envoy/examples/redis main
$ docker run --rm --network host redis:latest redis-cli -h localhost -p 1999 get bar
bar

weisisea@weisisea3 [6:10:11]: ~/github/envoy/examples/redis main
$ docker run --rm --network host redis:latest redis-cli -h localhost -p 1999 ping
PONG
```

Did you follow https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/redis.html#step-2-issue-redis-commands to issue the commands?

The downstream protocol error could happen if we use `nc` (netcat) or `telnet` to connect to Envoy and then issue the commands. The reason is that Envoy Redis filter currently supports [RESP protocol](https://redis.io/docs/reference/protocol-spec/). `nc` and `telnet` don't know how to encode RESP but `redis-cli` tool encodes commands in RESP.

**Comment by weisisea** [comment]
According to https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#supported-load-balancers:

> Note that if no active health checking policy is [configured](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_hc#config-cluster-manager-cluster-hc) for a cluster, all upstream cluster members are considered healthy, unless otherwise specified through [health_status](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-field-config-endpoint-v3-lbendpoint-health-status).

Since the active health check is not configured in your config file, envoy-redis-2 is still considered as healthy by Envoy and therefore Envoy continues to send commands to it. The command will time out (because envoy-redis-2 is down) and then Envoy will return upstream error. So probably try adding active health check for the cluster.

**Comment by phlax** [comment]
i have been adding more health checks to the examples, mostly for other reasons, but it would probably be helpful to add a healthcheck in this example - i have worked around for now with a `wait` to make CI work

**Comment by midnightcodr** [comment]
@weisisea I'll give health_status a try. In the meanwhile can you share your work-around for the redis example @phlax ? Thank you both.

**Comment by phlax** [comment]
> can you share your work-around for the redis example

its specific to how the examples work - see here https://github.com/envoyproxy/envoy/blob/main/examples/redis/verify.sh#L18

```bash
wait_for 40 bash -c "_redis_cli -h localhost -p ${PORT_PROXY} set baz BAZ | grep OK"
```

what would be better is adding a healthcheck to the redis container so this would not be required
