### ISSUE TITLE
cors filter not working as expected

### ISSUE THREAD

**Issue by oliverjoa** [envoyproxy/envoy#25882]
Hi,

I try to use the cors filter, as shown in the config: 

               "http_filters": [
                  {
                    "name": "envoy.filters.http.router",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                    }
                  }
                ],
                "route_config": {
                  "name": "route",
                  "virtual_hosts": [
                    {
                      "domains": [
                        "*"
                      ],
                      "name": "vhost",
                      "typed_per_filter_config": {
                        "envoy.filters.http.cors": {
                          "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy",
                          "allow_origin_string_match": [
                            {
                            "safe_regex": {
                              "regex": ".*"
                              }
                            },
                            { "contains": "test"
                            }
                          ],
                          "allow_methods": "GET,POST,OPTIONS",
                          "allow_headers": "X-Test",
                          "max_age": "20"
                        }
                      },
                      "routes": [
                        {
                          "direct_response": {
                            "body": {
                              "inline_string": "ok ok ok\n"
                            },
                            "status": 200
                          },
                          "match": {
                            "prefix": "/"
                          }
                        }
                      ]
                    }
                  ]
                },

If I do a request:

curl -s -v -H "Host: www.test2.de" -H "Origin: www.test.de" http://localhost:8002/

I don't get any cors-headers set in the response.

**Comment by oliverjoa** [comment]
I am using: envoyproxy/envoy:v1.25.1

**Comment by zuercher** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
I think you also need to enable the cors filter in the  `http_filters`?

**Comment by oliverjoa** [comment]
I tried that already, didn't help. I could see then that there where some prometheus metrics about origin headers beeing valid/invalid, but it was always zero.

                  {
                    "name": "envoy.filters.http.cors",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy"
                    }
                  },

**Comment by wbpcode** [comment]
And add `-X OPTIONS ` in you `curl` command. Only legal options request will be handled by the cors filter.

**Comment by oliverjoa** [comment]
I tried also OPTIONS requests, also not working.
And in my opinion cors headers should be set also on GET requests, because the browsers don't always do preflight OPTIONS requests.

**Comment by oliverjoa** [comment]
I didn't find any working example with the new "typed_per_filter_config"-key variant. I only found examples with the configuration via the deprecated "cors"-key inside the vhost.

**Comment by wbpcode** [comment]
> 

Both is ok and `cors` field was deprecated.

**Comment by wbpcode** [comment]
> I tried also OPTIONS requests, also not working. And in my opinion cors headers should be set also on GET requests, because the browsers don't always do preflight OPTIONS requests.

could you provide a complete example config, then I can try it in my local env?

**Comment by wbpcode** [comment]
```
curl -X OPTIONS \
  -H "Host: www.test2.de" \
  -H "Origin: www.test.de" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: content-type" \
  http://localhost:8002/
```

**Comment by oliverjoa** [comment]
no change with "Access-Control-Requests*" - headers
here is my config:
[cors-test.tar.gz](https://github.com/envoyproxy/envoy/files/10880685/cors-test.tar.gz)

**Comment by wbpcode** [comment]
@oliverjoa Hi, please update the route matcher to a normal route entry that with a target cluster. The cors cannot work for route with direct response or redirect. Thanks.

After updating the configuration, you can try the request again, I think you will get a expected response.

```
curl -X OPTIONS \
  -H "Host: www.test2.de" \
  -H "Origin: www.test.de" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: content-type" \
  http://localhost:8002/

```

**Comment by oliverjoa** [comment]
Hi,
yes, thanks it works now. Sorry to bother you, but I didn't expect that it does not work with a direct-response.
Thanks.
