### ISSUE TITLE
OAuth2 authentication with Azure

### ISSUE THREAD

**Issue by thailakadre** [envoyproxy/envoy#25905]
I open some time ago an issue (https://github.com/envoyproxy/envoy/issues/25096), that was closed without an answer.
I would like help to use the new versions of envoy and authenticated it using azure.  All details are in the previous issue.

Please, Could someone help me?

Thanks,
Thaila

**Comment by zuercher** [comment]
I'll re-open the old issue. You might try looking for help in the Envoy slack. There are instructions for joining in the project README.
