### ISSUE TITLE
Logging UserAgent Truncates Comments?

### ISSUE THREAD

**Issue by Mutilar** [envoyproxy/envoy#25919]
**Logging UserAgent Truncates Comments?**

My access log filter pulls User Agent via the request header: "**%REQ(USER-AGENT)%**". However this removes any comments (including information about the platform or any other freeform information). 

I see the user agent's "platform" is checked in [user_agent.cc](https://github.com/envoyproxy/envoy/blob/fe55c4f8a9989b10367f86eab224b218d3bdc835/source/common/http/user_agent.cc#LL53-L60C6) to build metrics. But this information doesn't make it to my access logs. Wondering if/why the access log filter only logs the product/version and not the extra comments?

UserAgent standard: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent: "Syntax: User-Agent: (product)/(version) (comment)"

**Comment by mattklein123** [comment]
The user-agent should be the value of the header. It's possible something is getting sanitized so we would need a specific repro/example to comment more.

**Comment by Mutilar** [comment]
On reproducing, we found Envoy did in-fact log the full user-agent header, and the issue lie with in Fluentbit. Closing.
