### ISSUE TITLE
Connection balancing after upstream connection was already created

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25915]
Currently there's an option to add a connection balancer, that is invoked very early in the process chain, right after the socket accepted a new connection and before a handler for the connection is chosen. Would theoretically be possible to re-balance connections in the data processing stage? For example, during a L4/L7 filter? Would it be possible to re-balance in listener filters stage? Thanks

**Comment by zuercher** [comment]
@mattklein123 might have something to add, but this comment on the issue which led to the implementation of connection balancing says it's probably not possible: https://github.com/envoyproxy/envoy/issues/4602#issuecomment-527568295

**Comment by mattklein123** [comment]
I think it would be extremely difficult to implement. Obviously, the earlier in the lifecycle it is done the easier it would theoretically be, but the main problem is that everything is effectively dispatcher local, so the minute you have anything related to the dispatcher you would have to migrate all of it somehow.
