### ISSUE TITLE
Is it possible to call getThreadLocalCluster from main thread?

### ISSUE THREAD

**Issue by suniltheta** [envoyproxy/envoy#25918]
#### Description:

I am working on this issue https://github.com/envoyproxy/envoy/issues/11816 to remove libcurl. I am able to replace the curl usage with `httpAsyncClient` to fetch the metadata.

Only AWS extensions and plugins are dependent on libcurl as of now, there are 3 places where the aws credentials provider is used (https://github.com/envoyproxy/envoy/tree/main/source/extensions/common/aws).

1. extensions/filters/http/[aws_lambda](https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/aws_lambda)
2. extensions/filters/http/[aws_request_signing](https://github.com/envoyproxy/envoy/tree/main/source/extensions/filters/http/aws_request_signing)
3. extensions/grpc_credentials/[aws_iam](https://github.com/envoyproxy/envoy/tree/main/source/extensions/grpc_credentials/aws_iam)

For the first two http filter extensions I am able to call `cluster_manager.getThreadLocalCluster(cluster_name_)` to get `thread_local_cluster` and to eventually call `thread_local_cluster->httpAsyncClient().send(std::move(message), *this, options)` . The first two filters runs on a worker thread. But for the aws iam grpc credentials plugin, on calling `getThreadLocalCluster` I get assert failure at 

https://github.com/envoyproxy/envoy/blob/fe55c4f8a9989b10367f86eab224b218d3bdc835/source/common/thread_local/thread_local_impl.cc#L65-L68

```
[2023-03-03 04:23:51.749][2171546][critical][assert] [source/common/thread_local/thread_local_impl.cc:66]
 assert failure: currentThreadRegisteredWorker(index).
```

If I use a binary built with `-c opt` option and do tools/stack_decode.py, I get the backtrace like below 
https://gist.github.com/suniltheta/43a3bf684d8fe350cb0d083774e2d111  [Raw [gist](https://gist.githubusercontent.com/suniltheta/43a3bf684d8fe350cb0d083774e2d111/raw/f5fba117e1cf3cc78956409a4c79f08b9f3fa44a/gistfile1.txt)]

So my believe is that since aws iam grpc plugin runs on main thread, it is not able to access the thread local cluster. Is it possible that we can access thread local cluster from inside main thread and something that I am doing wrong while I access it?

&nbsp;

Sample config having aws iam grpc credentials plugin: https://gist.github.com/suniltheta/462566777a5490dcb13818f6e20259af [Raw [gist](https://gist.githubusercontent.com/suniltheta/462566777a5490dcb13818f6e20259af/raw/b755f274221b98a6285b2616cb14faded42a262d/gistfile1.txt)]

Changes on my forked repo https://github.com/suniltheta/envoy/blob/dffdf598d8395afea0ad86077cd709b6220e252f/source/extensions/common/aws/metadata_fetcher.cc#L78-L84

I have posted a message on [#envoy-dev](https://envoyproxy.slack.com/archives/C78HA81DH/p1677878388247009) channel as well. They both are the same issue.

**Comment by mattklein123** [comment]
I would have to refresh myself on the code, but there are other filters that call external services on the main thread. I would take a look at one of them to see how they work. For example: https://github.com/envoyproxy/envoy/blob/29af84c696ff3e80ecd0dc5369cd4e6fd50eb186/contrib/client_ssl_auth/filters/network/source/client_ssl_auth.cc#L32

**Comment by suniltheta** [comment]
thanks for the pointer. I will take a look.
