### ISSUE TITLE
grpc_http1_reverse_bridge support stream support stream gRPC calls

### ISSUE THREAD

**Issue by libratiger** [envoyproxy/envoy#25910]
Under some cases, the environment do not support the HTTP2, so we want to transfer the gRPC services into the HTTP1 protocol. so we can reuse the code. [But grpc_http1_reverse_bridge can not support grpc calls now](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_http1_reverse_bridge_filter#grpc-http-1-1-reverse-bridge).

Does this limited by the design ? or we can support it in the future?

**Comment by zuercher** [comment]
I assume you're asking if the grpc http1 reverse bridge will support streaming calls? I don't think that's possible given the semantics of http/1.1 and the bidirectional nature of streaming gRPC.

**Comment by libratiger** [comment]
> I assume you're asking if the grpc http1 reverse bridge will support streaming calls? I don't think that's possible given the semantics of http/1.1 and the bidirectional nature of streaming gRPC.

Yes, this is what i wanted

**Comment by libratiger** [comment]
> I assume you're asking if the grpc http1 reverse bridge will support streaming calls? I don't think that's possible given the semantics of http/1.1 and the bidirectional nature of streaming gRPC.

I can not fully understand why the http1.1 can not support the bidirectional stream? Can you explain more deeply?

**Comment by zuercher** [comment]
I think this document covers it: https://www.rfc-editor.org/rfc/rfc6202

Essentially, it's possible to do this, but it isn't explicitly supported by the http/1.1 standard and there are pitfalls.
