### ISSUE TITLE
Aggregate Cluster: do cluster members share healthcheck connectionpool and data_plane connectionpool?

### ISSUE THREAD

**Issue by xianggao001** [envoyproxy/envoy#25920]
*Title*: *Aggregate Cluster: do cluster members share healthcheck connectionpool and data_plane connectionpool?*

*Description*:
Hi folks, having a question about `Aggregate Cluster`:  it contains 2 clusters: cluster_1 and cluster_2, and we hope to migrate traffic from cluster_1 to cluster_2 (we can't directly use xDS to do the migration). They both have active healthcheck. These 2 clusters will point to the same endpoints, but the 2 clusters have different properties.  Our production machine is kind of at capacity.  Is it possible that these 2 clusters share the same healthcheck connection_pool? or even data_plane connection_pool ?  Thanks!!

**Comment by mattklein123** [comment]
IIRC for aggregate cluster the 2 underlying clusters are independent so they will have independent health checking and connection pools.

**Comment by xianggao001** [comment]
@mattklein123 Thank you Matt! A related question: is there a way to share health checking and connection pools between 2 clusters?  I searched around in Issues and Community Slack and it seems the answer is NO. Thanks!

**Comment by mattklein123** [comment]
No, not currently AFAIK.
