### ISSUE TITLE
Shadowing should add "-shadow" to host, not after port

### ISSUE THREAD

**Issue by christian-posta** [envoyproxy/envoy#2595]
When shadowing traffic, Envoy adds `-shadow` to the end of the host string which is added as the `Host` header.

If you send to http://foobar:8000, Envoy will shadow that traffic and set the Header to `Host: foobar:8080-shadow`

With certain servlet containers (namely, Apache Tomcat), the protocol connector will try and parse the Host header and barf when it tries to parse the port as `8080-shadow` because of the non-integer characters.

Maybe Envoy could set the `-shadow` postfix to the host part of the host/port pair?

**Comment by dio** [comment]
@christian-posta if I understood correctly, you want something like https://github.com/dio/envoy/blob/split-port/test/common/router/shadow_writer_impl_test.cc#L54?

**Comment by christian-posta** [comment]
Yes, exactly right @dio!
