### ISSUE TITLE
``IpVersionsClientType/TcpProxyOdcdsIntegrationTest`` is very flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25978]
This appears to be a new issue, and is happening pretty frequently in coverage runs

The error is:

```console
[2023-03-08 09:59:12.317][672732][trace][main] [source/common/event/dispatcher_impl.cc:125] clearing deferred deletion list (size=8)
test/integration/integration_tcp_client.cc:116: Failure
Value of: payload_reader_->readLastByte()
  Actual: false
Expected: true
Stack trace:
  0x7fdcaa3cfd66: Envoy::IntegrationTcpClient::waitForHalfClose()
  0x97f91e: (unknown)
  0x7fdbddb7e32d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7fdbddb650ae: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7fdbddb4c9ad: testing::Test::Run()
  0x7fdbddb4d49e: testing::TestInfo::Run()
... Google Test internal frames ...
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=130151&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=41410

~I suspect the issue started with https://github.com/envoyproxy/envoy/pull/25801~

**Comment by phlax** [comment]
more failure/s:

- https://dev.azure.com/cncf/envoy/_build/results?buildId=130105&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=41417

**Comment by phlax** [comment]
cc @jrajahalme i initially suspected #25801 but reverting that doesnt seem to have fixed the issue - apologies for noise

**Comment by phlax** [comment]
im seeing this flake pretty frequently - where there is not cache/RBE

```console
//test/integration:tcp_proxy_odcds_integration_test                      FAILED in 2 out of 2 in 39.6s
  Stats over 2 runs: max = 39.6s, min = 38.8s, avg = 39.2s, dev = 0.4s
```

ill try and repro it locally

**Comment by alyssawilk** [comment]
Failure largely in IpVersionsClientType/TcpProxyOdcdsIntegrationTest.RepeatedRequest/0  since I search for test names :-)

**Comment by adisuissa** [comment]
A similar failure in: TcpProxyOdcdsIntegrationTest.RepeatedRequest/1

https://dev.azure.com/cncf/envoy/_build/results?buildId=135310&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881&l=40537

It is the same error, but further investigation needed to see if it is the same underlying issue.

**Comment by phlax** [comment]
also seeing this on 1.26 branch https://dev.azure.com/cncf/envoy/_build/results?buildId=135867&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=67a76341-37f4-5b49-db38-acbb8a59af82&l=215
