### ISSUE TITLE
Documentation: Performance deltas between AWS Graviton2 (aarch64/neoverse-n1) vs Intel

### ISSUE THREAD

**Issue by lowjoel** [envoyproxy/envoy#26004]
*Description*:
Hello there! We (@grab) have been running Envoy as part of our Consul service mesh, and one of the things we were doing was to migrate our fleet onto AWS Graviton2 (c6g/m6g instances). We were running Envoy 1.16.5 (which is old, I'm aware), and we found some performance differences that we'd figure would be worth having awareness about in the larger community if others are planning for the same migration.

I am not entirely sure where we want to go with this -- we could take this as a documentation ticket, but it may also evolve to be a tracking ticket for the performance deltas (if we can find any that's worth working on). Open to suggestions.

### Benchmarking methodology

We set up a pair of services, X and Y. Y exposes an "cat" endpoint over gRPC (basically, replies with whatever it was requested with), X exposes a "load test" endpoint over HTTP (accepting parameters for number of requests to send, concurrency, and size of request). Here, Envoy is only used for communication between X and Y.

We also set up 3 test cases to determine the performance of Envoy: 

| Case | Payload size | requests from X to Y | concurrency |
|------|-----|-----|-----|
| big   |  4MiB ( minus 64 bytes to be respectful of the gRPC maximum request size we've set) | 8 | 2 |
| medium | 32KiB | 1024 | 2 |
| small | 1KiB | 3072 | 4 |

The instance running X was varied, Y was always a c5.large. `ab` was used to call X's load test endpoint with varying tries to keep the total benchmark runtime to be around 3-5 minutes.

### Benchmarking results

"qps" refers to the number of queries between X and Y. The p50 latency is probably more accurately "the maximum of the p50s observed over the test" (and not the p50 of all observations - due to the way the metrics were emitted. Experimental limitation 😓)

| Run | big qps | big p50 latency | medium qps | medium p50 latency | small qps | small p50 latency |
|-----|---------|-----------------|-------------|---------------------|-----------|-------------------|
| Intel c5.large, without Envoy |  31.946 qps | 36.87ms | 1210.245 qps | 1.21ms | 2302.849 qps | 1.71ms |
| Intel c5.large, Envoy | 23.209 qps | 60.8ms | 768.521 qps | 2.28ms | 1170.249 qps | 3.76ms |
| Graviton2 c6g.large, without Envoy | 37.488 qps | 30.08ms | 1378.994 qps | 1.17ms | 2511.519 qps | 1.14ms |
| Graviton2 c6g.large, vanilla Envoy 1.16.5 | 6.411 qps | 297.06ms | 433.370 qps | 4.31ms | 1187.605 qps | 2.68ms |
| Graviton2 c6g.large, Envoy 1.16.5, Clang10, #16104 | 22.301 qps | 58.02ms | 612.071 qps | 2.74ms | 1057.405 qps | 3.8ms |
| Graviton2 c6g.large, Envoy 1.16.5, Clang12, #16104 | 23.650 qps | 65.0ms | 642.657 qps | 2.65ms | 1139.307 qps | 3.84ms |
| Graviton2 c6g.large, Envoy 1.16.5, Clang12, `-mcpu=neoverse-n1`, #16104 | 23.175 qps | 63.1ms | 670.072 qps | 2.71ms | 1170.16 qps | 3.68 ms |

### Observations

1. Running a build with #16104 is absolutely necessary for performance not to tank. This probably is less important now that 1.19+ has it, but was something that took a while to figure and find out.
2. We've tried Clang12 with `-mcpu=neoverse-n1` in an attempt to rule out [LSE being a problem](https://github.com/aws/aws-graviton-getting-started/blob/main/optimizing.md#locksynchronization-intensive-workload). The gain was minor, and I can't tell if it was really improved, or just chance differences (depending on network conditions etc.) That this impacted the small test case most further adds to the mystery.
3. We can't match the performance of Intel on the medium test case in all scenarios, seeing a ~15% reduction in qps.

**Comment by jmarantz** [comment]
that QPS sounds low especially for the small payload.   Any idea why? For the test run without Envoy, was there another proxy taking its place?

Have you taken some flame-graphs?

There are some general notes on benchmarking Envoy that might be worth a look: https://www.envoyproxy.io/docs/envoy/latest/faq/performance/how_to_benchmark_envoy

**Comment by soulxu** [comment]
Hi @lowjoel, 

May I know which intel AWS instance you are using for X? 

Thanks!

**Comment by wbpcode** [comment]
hmmm, seems there is a obvious degradation in the `Graviton2` for big/medium case.

**Comment by lowjoel** [comment]
@jmarantz We don't know yet. I've got some flamegraphs attached here but I don't see any obvious performance bottlenecks. The test run without Envoy was direct IP-to-IP.

Big:
![envoy-v1 16-patched-release-big perf](https://user-images.githubusercontent.com/2505070/224217349-de7c2940-2821-4c3f-845b-f7ceec15b829.svg)

Medium:
![envoy-v1 16-patched-release-medium-v2 perf](https://user-images.githubusercontent.com/2505070/224217395-7d50a449-bb81-49cd-ba4c-70763a348c91.svg)

Small:
![envoy-v1 16-patched-release-small-v2 perf](https://user-images.githubusercontent.com/2505070/224217424-b41c2b6e-e9c9-4c7a-a4fb-e7c92ceeb39e.svg)

@soulxu sorry, I left that out, added in the original table.

**Comment by soulxu** [comment]
> @soulxu sorry, I left that out, added in the original table.

Thanks! May I also ask if have you try `c6i` instance? it is a newer CPU than c5, and query the AWS website, it got the same price with c5. I'm curious if they are the same price, why didn't use the newer CPU which suppose to have better performance

**Comment by lowjoel** [comment]
Ah, we haven't benchmarked against c6i yet. We used c6g because it's supposed to perform at the same level as c5, but at lower costs.

**Comment by soulxu** [comment]
Got it, thanks! The c5 is `2nd Gen Intel® Xeon® Scalable Processors`, the c6i is `3rd Gen Intel® Xeon® Scalable Processors`. If considering the same cost on both intel instances (c6i and c5), probably worth comparing between c6i and c6g.

**Comment by RamaMalladiAWS** [comment]
Yes @lowjoel, I suggest you try C6i and C7g instances and post your perf observations here. It will help us look into Envoy optimizations.

**Comment by lowjoel** [comment]
@RamaMalladiAWS I can try c6i relatively quickly and post some numbers here, but C7g isn't available in ap-southeast-1 yet and setting up all the corresponding control planes in another region isn't something we're able to commit to at the moment.

The main point of this was really about the performance deltas for c6g over c5 -- less about c6i vs c6g.

**Comment by DDxPlague** [comment]
@lowjoel can you share more details about the Envoy and environment configs you're working with? I would love to be able to recreate this on my side and see what we can do to get to the bottom of the performance delta.

**Comment by JulianMarcusSchroeder** [comment]
@lowjoel can you share your envoy config file? I'd like to create a setup like yours and try to recreate the issue.

**Comment by sayap** [comment]
Created https://github.com/sayap/envoy-load-test, and used it to run some load test against c5/c6g/c6i/c7g: (more details in https://github.com/sayap/envoy-load-test/blob/master/results/internal.md): 

| machine type | --concurrency 1 | --concurrency 2 | --concurrency 3 | --concurrency 4 |
| ------------ | --------------- | --------------- | --------------- | --------------- |
| c5.xlarge    |           16501 |           22153 |           23694 |           26657 |
| c6g.xlarge   |           12151 |           20279 |           28087 |           33873 |
| c6i.xlarge   |           24818 |           39716 |           31638 |           40844 |
| c7g.xlarge   |           19071 |           32349 |           42035 |           46742 |

This might explain the performance delta observed by Joel, since that load test didn't push Envoy to fully utilize the 2 vCPUs from c5.large / c6g.large.
