### ISSUE TITLE
What's the recommended way to disable TLS 1.0 for envoy?

### ISSUE THREAD

**Issue by vijayendrabvs** [envoyproxy/envoy#2602]
**Issue Template**
N/a

*Title*: *One line description*
What's the recommended way to disable TLS 1.0 for envoy?

*Description*:
It would be good to be able to disable specific versions of TLS that are supported by envoy - for example, 1.0, 1.1, so only 1.2 would be used in negotiations with clients. Is this currently doable as a configuration in envoy? It wasn't clear from the envoy documentation. If this requires code changes, I'm happy to do them but may need some help/guidance initially. I see some relevant code bits in envoy/source/common/ssl/context_config_impl.cc and can walk through the code path to see where a TLS version black/white list would fit in, but am putting this question out first so I don't end up doing something not required at all.

[optional *Relevant Links*:]
n/a

**Bug Template**
n/a

*Title*: *One line description*
n/a

*Description*:
n/a

*Repro steps*:
n/a

*Admin and Stats Output*:
n/a

**Comment by ggreenway** [comment]
It can be set in TlsParameters via the min and max protocol version: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html#envoy-api-msg-auth-tlsparameters.

**Comment by ggreenway** [comment]
Closing this for now.  I think this ties in with https://github.com/envoyproxy/envoy/issues/2607: having an example config that sets up TLS would probably answer questions like this.
