### ISSUE TITLE
envoy does not log when it fails to listen on a port due to a conflict

### ISSUE THREAD

**Issue by MPalarya** [envoyproxy/envoy#26042]
our envoy failed to listen on configured ports due to a conflict with dynatrace, but no error logs are printed.
The ask is to add logging for such scenarios, so it becomes easier to identify and resolve.

**Comment by suniltheta** [comment]
The expectation in that scenario is that Envoy should reject the listener configuration if that port is already in use. There should be increment in [management](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/mgmt_server.html) stats `update_rejected` and some exception/warning logged.

**Comment by kyessenov** [comment]
What you describe is my expectation as well. Is there no warning at all? Does dynatrace set SO_REUSEPORT as well?

**Comment by jaysonjdmello** [comment]
@suniltheta , it looks like the other application most probably has `SO_REUSEPORT` enabled. In that case,  I am not sure how envoy would have a way of knowing since the kernel allows it.
