### ISSUE TITLE
New Getting Started Documentation

### ISSUE THREAD

**Issue by eflee** [envoyproxy/envoy#2605]
*New Getting Started Documentation*: *A new getting started flow, based on incremental v2 YAML configs.*

*Description*:

- Develop an entire new getting started flow, based on incremental v2 YAML configs, explained roughly line by line with links to the deeper reference docs. 
- Example: Take https://github.com/envoyproxy/envoy/blob/master/configs/google_com_proxy.v2.yaml and show how to run it and explain it line by line. 
- Develop other more complex examples and explain those. The idea is to guide the new user to Envoy in a gradual way, going all the way through a small management server (maybe built on go-control-plane).

**Comment by artbegolli** [comment]
Will be happy to pick this up.
