### ISSUE TITLE
Access log at the beginning of a steam

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#26058]
Is it currently possible to write access log when a connection is made with upstream?
From my testing I can see that access log is only written on an end of a stream. On most cases this is enough, but for long living stream I would like to have another log at the start of the stream, which specifies the destination host and additional metadata which is available.

**Comment by kyessenov** [comment]
There's now periodic reporting, which should probably be used for the long living streams, but it doesn't report on the stream open.

**Comment by ohadvano** [comment]
Thanks @kyessenov, is it theoretically possible to extend this to long living TCP streams as well?
I can try taking this item if there's no potential reason why it shouldn't be feasible.

**Comment by kyessenov** [comment]
Yeah, the periodic reporting is available for both TCP and HTTP streams. I think there's a bit of complexity in reporting on the start:
* upstream might not be available, e.g. if it's using a header to pick an endpoint;
* confusing with respect to the transport socket (do we report on TLS handshake, after handshake, early data?);
* access control might be done first to avoid DoS of the telemetry.

**Comment by ohadvano** [comment]
Oh that's cool, I wasn't aware of this feature for TCP. I can see now by looking at the proto definitions. Should we mention this this in the access log docs? 

Per reporting on stream start, what do you think about reporting after creating a connection with upstream?

**Comment by kyessenov** [comment]
CC @htuch @paul-r-gall 
I think that's reasonable, except for https://github.com/envoyproxy/envoy/issues/9023 issue. It might be useful to report failures to pick an upstream or some codec errors, with some protection against overload.

**Comment by ohadvano** [comment]
Should we also guard this with a config enablement? I mean, stream start access log would not be written unless specified by config

**Comment by ohadvano** [comment]
@kyessenov I created an initial PR to see if I'm going the right direction here.

**Comment by htuch** [comment]
I agree with logging on stream connection (at least optionally). With the RBAC audit log, I think I'm persuaded that it might make sense to have a security specific audit log format and this can be independent of regular logging - I think that audit log should live in the RBAC filter and not HCM.
