### ISSUE TITLE
the upstream receive // path

### ISSUE THREAD

**Issue by qicz** [envoyproxy/envoy#26055]
like envoy doc configured, use `pathSeparatedPrefix` and pre_rewrite is "/":

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2174082/224491482-8e8c5f14-6b9e-46c8-9fb2-5801a12b9aee.png">

the `pathSeparatedPrefix` "/om/backend" would watch 

- /om/backend
- /om/backend/
- /om/backend/v1
- /om/backend?param=true

reference envoy docs: 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2174082/224492159-12a84bfc-306d-43d9-a231-b88c5c8aba58.png">

**but the upstream receive double "/"**

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2174082/224491516-6934d9b5-2e0f-41e0-a14c-211f44b38ab1.png">

the pre_rewrite  is not "/" work fine:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/2174082/224492367-32b19d30-a76e-4d4a-9687-4ac1ffed2a59.png">

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2174082/224492389-581859e2-0f29-4d04-9807-ee2ac79766aa.png">

I think we should trim the double "/"  when the prefix_write is "/" and the prefix is `pathSeparatedPrefix`.

**Comment by kyessenov** [comment]
CC @yanavlasov , seems reasonable to make rewrites produce valid paths.

**Comment by qicz** [comment]
@kyessenov This issue auto closed ptal and label with `no stalebot` , thanks

**Comment by nxy7** [comment]
As far as I'm aware this issue wasn't fixed, but it seems pretty fundamental for routing. Are there any plans to support this features?

**Comment by cpakulski** [comment]
I will work on this issue/bug.
