### ISSUE TITLE
Getting started with V2 Config

### ISSUE THREAD

**Issue by eflee** [envoyproxy/envoy#2606]
*Getting started with V2 Config*: Based on the existing example V2 config, explain how the config variables work, what each of them do, and how to bootstrap your own config

*Description*:
- https://github.com/envoyproxy/envoy/blob/master/configs/google_com_proxy.v2.yaml
- Break the above down in a line-by-line explanation doc.
- Link out to reference for each configuration variable, explaining the most relevant options and standard config.

**Comment by francisu** [comment]
WIP: https://github.com/envoyproxy/data-plane-api/pull/514

**Comment by francisu** [comment]
https://github.com/envoyproxy/data-plane-api/pull/548

**Comment by artbegolli** [comment]
Looks like there's a PR already, can this be closed?
