### ISSUE TITLE
`Too Many Requests` error from https://go.dev

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#26074]
We are getting errors when pulling software from go.dev for making too many requests, eg

https://dev.azure.com/cncf/envoy/_build/results?buildId=130618&view=logs&j=c7eac9df-4f5c-5dcd-24f5-83cdbb7aa27e&t=912ee98a-a98d-52d7-983f-f2606b2d8c63&l=64

**Comment by phlax** [comment]
cc @doujiang24 @wangfakang

**Comment by phlax** [comment]
seems wierd that its trying to download from golang.google.cn - i guess that is how go.dev 's mirrors are working

**Comment by doujiang24** [comment]
those two URLs come from: https://github.com/bazelbuild/rules_go/blob/be272514ad4c3cf0fa78c97e49aacf077340ccfb/go/private/sdk.bzl#L86-L87

maybe we can add more mirrors for it?
