### ISSUE TITLE
Example V2 YAML Configs

### ISSUE THREAD

**Issue by eflee** [envoyproxy/envoy#2607]
*Replicate and convery V1 config examples to V2 YAML*: *More thorough V2 examples*

*Description*:
- https://github.com/envoyproxy/envoy/tree/master/configs
- Convert existing examples over to V2 config.
- V1 is still supported, create a doc that explains the difference in configuration methodologies and links to various examples

**Comment by mattklein123** [comment]
This is a duplicate of https://github.com/envoyproxy/envoy/issues/2139. Let's use the previous issue to track since there has already been some discussion there.
