### ISSUE TITLE
Dynamically updating RBAC network filter

### ISSUE THREAD

**Issue by epb-644** [envoyproxy/envoy#26079]
*Title*: Dynamically updating RBAC network filter without connection draining

*Description*:
>I plan to use Envoy's RBAC Network filter for authorization, and I want to understand the behavior around updating the RBAC's rules and connection draining. Am I understanding correctly that the RBAC filter will drain connections upon any change? If so, is there any way to avoid connection draining when only updating the RBAC filter's rules? In particular I am planning to update the list of principals for the filter, and need to avoid draining connections. 

[optional *Relevant Links*:]
- https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/rbac_filter

**Comment by kyessenov** [comment]
That's not supported unfortunately. Any change in RBAC triggers a drain even if the new RBAC allows existing connections.

**Comment by epb-644** [comment]
I see, thanks @kyessenov. I have a usecase to filter connections on proxy protocol header values, and we want to update the allowlists without draining connections (ideally). Is something like external auth our only option at this time?

**Comment by kyessenov** [comment]
You could try wrapping RBAC into ECDS and updating RBAC config dynamically this way. But that would not retro-actively apply new config to the old connections.

**Comment by epb-644** [comment]
Right, I think we would need it to apply the config to old connections as well.

**Comment by kyessenov** [comment]
This would be a new feature. We were thinking about supporting it in ECDS, but it requires an effort to retrofit the filters to apply to the existing streams.

**Comment by kyessenov** [comment]
Listener filter chain matching work incrementally. If you add/remove chains, only the connections in those chains are affected, regardless of the initial matching logic.
