### ISSUE TITLE
[stats] Enhancement of LazyCompatibleStats<T>, has a centralized life cycle management entity

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#26106]
*Title*: *[stats] Enhancement of LazyCompatibleStats<T>, has a centralized life cycle management entity*

*Description*:
See discussion in https://github.com/envoyproxy/envoy/pull/23921/files/afeda1b609be8dbb4c070a0aec7a31e8bbead22a#r1125540072, 
Right now in the LazyCompatibleStats implementation, to detect if an StatsStruct is instantiated, we used a Gauge as indicator, which has "global var" property. This gauge is named as $scope_prefix.$TypeName.$initialized. e.g. *"cluster.cluster_1.ClusterTrafficStats.initialized"*.  
It works well for XDS caused stats recreation: a Cluster1 gets a new version Cluster1-v2 via CDS, during the creation of Cluster1-v2::ClusterInfoImpl, on seeing the LazyCompatibleStats<T>::initialized_ gauge is >0, Cluster1-v2::ClusterInfoImpl::traffic_stats_ will instantiate the nested ClusterTrafficStats, (and inc the initialized_ gauge to 2). All existing traffic stats will not be "lost" thanks to this mechanism. 

This mechanism doesn't work when a user disables stats by prefix "*inititazed". (which is a really corner case). 

Instead, we could have alternatives to workaround the above limitation: 
1. have a centralized storage layer (global), preferably lives in Store, that keeps tracking of lazy-init enabled scopes, such that when LazyInit instantiate() is called, marks the scope "lazy-inited" and pass that to any future same name scope creation.
2. Make scope life-cycle extensible: on creation of a new scope, if there is an existing scope with the same name, let the new scope instance extend the existing scope's life cycle. (maybe making scope shared?)

**Comment by jmarantz** [comment]
sgtm; you could put this context in the ClusterManager or something, rather than putting it in Stats::Store or making it global or static.

this LazyStatsScope would need to be shared, yeah.

**Comment by stevenzzzz** [comment]
@DiazAlan 
@pradeepcrao

**Comment by stevenzzzz** [comment]
this is resolved in another approach. 
 thanks to @DiazAlan's PR: https://github.com/envoyproxy/envoy/blob/main/source/common/stats/thread_local_store.cc#L602
