### ISSUE TITLE
How to use  LEAST_REQUEST load balancing algorithm of envoy

### ISSUE THREAD

**Issue by Gala-R** [envoyproxy/envoy#26115]
I want to use envoy's LEAST_REQUEST load balancing algorithm to achieve load balancing of business clusters. I deploy envoy as a sidecar withmy container together. External connection requests will first reach envoy, and then envoy will selects upstream services for request forwarding through  LEAST_REQUEST algorithm , but there is a problem, envoy's LEAST_REQUEST algorithm is stateless, when I create a new pod, envoy on the new pod does not have the current cluster upstream service connection status data, so the newly created envoy container is not based on The global connection status of upstream services is used for LEAST_REQUEST algorithm load balancing. Is there any way envoy can solve this problem? After the new envoy node is up, it can synchronize to the latest connection status of the upstream cluster. The following figure is the topology of my service deployment:
![envoy](http://chuantu.xyz/t6/742/1678957920x2890390112.png)

**Comment by kyessenov** [comment]
LeastRequest is a local algorithm, so it makes sense it doesn't have a global picture. You might want to look at https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/load_stats/v3/lrs.proto for collecting global load information

**Comment by Gala-R** [comment]
> 

Does envoy provide an API that can update the local connection status?

**Comment by Gala-R** [comment]
> LeastRequest is a local algorithm, so it makes sense it doesn't have a global picture. You might want to look at https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/load_stats/v3/lrs.proto for collecting global load information

Does envoy provide an API that can update the local connection status?

**Comment by wbpcode** [comment]
Sorry, but I think there is no way to achieve you target for now. 😞

**Comment by Gala-R** [comment]
> Sorry, but I think there is no way to achieve you target for now. 😞

Thank you very much for your reply.
