### ISSUE TITLE
Access log on upstream connect for HTTP requests

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#26136]
This issue is a follow up to https://github.com/envoyproxy/envoy/issues/26058, and https://github.com/envoyproxy/envoy/pull/26094 which added an option to report access log when TCP proxy has successfully made a connection with the upstream.
I would like to add a similar option for HTTP requests.

The problem I'm facing is that the access logs are added to the HTTP filter manager:
https://github.com/envoyproxy/envoy/blob/fa5f548d05da6495c175b5c124292fa0bae215de/source/common/http/filter_manager.h#L985

However, I can't seem to find a callback in HTTP filter manager or HTTP connection manager that signals a successful connection with the upstream. decodeHeaders() would initialize the HTTP filter chain, and the router filter would create UpstreamRequest object, which is the only place I could get to, which has such information about upstream connection.

Seeking help understanding whether I missed something, or what can be done in this case. cc @kyessenov, @htuch.
Considering that there's no callback in FilterManager/HCM, is it reasonable to refactor so access log handlers will be accessible to HTTP filters?

**Comment by kyessenov** [comment]
I don't think we want to tie HTTP log to the upstream connection lifecycle. Requests can be retried, buffered, etc. Maybe we just want the start in `decodeHeaders`. Additionally, we could use some filtering per route or per host, since we often multiplex long streams and short requests in HTTP on the same port.

**Comment by ohadvano** [comment]
I tried adding access log in `decodeHeaders ` but seems like it's not ideal, because some of the data is not resolved yet, for example "%UPSTREAM_HOST%" will be null, and I think that many more data options. Should we settle with this for now?
I didn't get the second part of your comment, can you please explain?

**Comment by kyessenov** [comment]
There's certainly the upstream host selection callback somewhere, I can try to find it later. For the second part, I'm thinking of many virtual hosts in the same HTTP connection manager filter, some of which handle regular short GET requests, and others handling long streaming CONNECT requests. We'd probably want to have periodic/initial report to be applied to the latter.

**Comment by ohadvano** [comment]
I think currently if you choose periodic reporting, then it applies to any request that goes through the HCM. For this we would need to move the definition of periodic request to be per virtual host?

**Comment by ohadvano** [comment]
In filter_manager.cc. Please correct me if I'm wrong, but as I see it, the problem is that practically there are multiple entities in the flow:
1. HCM gets a new stream and creats ActiveStream which contains FilterManager (FilterManager is the entity that currently calls log() to flush access logs). When ActiveStream is created, it adds the access log handles to the FilterManager.
2. When routed filter is created, it creates another FilterManager for upstream filters, but nothing adds access log handles to it, so even if I call on log(), there will be no access log handles to flush the log.

Another problem with calling log() in decodeHeaders is that if there are multiple HTTP filters, it will be called multiple times, more than needed.

Is there a way to know when an upstream connection was made in ActiveStream/HCM?

**Comment by paul-r-gall** [comment]
I also agree with kuat, in that if you log on every upstream host selection or upstream connection created, you'll log multiple times per-request due to retries. I don't think that this is good behavior. I think that you should log once near the beginning of the downstream request. I think you should log either immediately before or immediately after tha `filter_manager_.decodeHeaders(*request_headers_, end_stream);` line in conn_manager_impl.cc.

**Comment by ohadvano** [comment]
The problem with logging near the beginning of a downstream request is that in this stage the flow lacks many important properties. I think that at least we should log after upstream host was resolved. I agree that logging before a successful connection may lead to not wanted repeats, But is there a way to log after a **sucessful** upstream connection?

**Comment by paul-r-gall** [comment]
Consider the following -- you connect to host-A successfully, receive a 5xx, upon which you retry, connecting to host-B instead. Would you log twice? 

We could add a callback from Router::Filter::onUpstreamHostSelected or Router::UpstreamRequest::onPoolReady, which may do what you want. But it still has the double-logging problem.

**Comment by ohadvano** [comment]
That's a good question, but I wouldn't necessarily answer 'no'. It might be a desired feature by users to have logs of failures for the same stream that was retried, because they can decude useful information out of it. Anyways, if we only seek successful requests, then let's just log on encodeHeaders + check for success status code.

**Comment by paul-r-gall** [comment]
Hm, I'm actually a fan of logging on encodeHeaders(..). It indicates that a http data stream has successfully been opened between envoy and the upstream, and especially in the WebSocket and CONNECT cases, it seems like the right thing to do.

**Comment by kyessenov** [comment]
Yeah, response headers are almost like an application-level ACK. We should make it clear that periodic reporting can happen prior to this log entry, since it can be confusing.

I was also looking into how we handle gRPC, and we could potentially log per each message there. Maybe we should implement is so that any HTTP filter can request to log a request at any time.

**Comment by ohadvano** [comment]
I don't know, I feel like response headers is too late. My rational for logging on request start is letting the user know "Envoy is going to access resource X". Periodic logging would be useful for long-living streams. End of stream logging would be useful for knowing the outcome of the stream. 
In my opinion the ideal place to log this would be - once, when the router has successfully made a connection with the upstream, and if it's not feasible, then once, after the router has selected the upstream host. This would indicate that a request is about to take place. The user should check the outcome at end of stream access log (Didn't check if access log has this option but if not, maybe we can add %NUM_RETRIES% or similar so the user can know how many times the request was retried). WDYT?

**Comment by kyessenov** [comment]
I don't have a strong opinion, but I think logging as early as possible (once we have a request ID, etc) also makes sense. That way it is guaranteed to be before any periodic reporting, and it's guaranteed that Envoy has to produce a response eventually, regardless of what happens to the upstream.

I don't think we should couple HTTP logging with upstream connections. The two operate completely independently in Envoy, so it's not a useful signal to correlate them.

**Comment by ohadvano** [comment]
@paul-r-gall what do you think about it? @kyessenov implementation wise, does it mean that it would require to add a callback that the router would call, or is there some callback in HCM/ActiveStream that can be used which I have missed?

**Comment by paul-r-gall** [comment]
You'd probably add a callback in ActuveStreamFilterBase which can then be
called from any filter. I'll take a look again next week.

**Comment by ohadvano** [comment]
@paul-r-gall I'm still not sure that would work because as I described in my previous comment:

> 2. When routed filter is created, it creates another FilterManager for upstream filters, but nothing adds access log handles to it, so even if I call on log(), there will be no access log handles to flush the log.
> 

Therefore, the router filter would call this callback, but it will be associated with the FilterManager that doesn't have the access log handles available. There needs to be some mechanism to access the downstream FilterManager
