### ISSUE TITLE
How to use Proxy protocol v2 in envoy to pass the CN field in the client certificate to the upstream server.

### ISSUE THREAD

**Issue by Gala-R** [envoyproxy/envoy#26140]

**Comment by kyessenov** [comment]
Looking at the config https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/proxy_protocol.proto#envoy-v3-api-msg-config-core-v3-proxyprotocolconfig, I think custom TLVs are not supported. You could maybe manually create TLVs in a custom downstream filter, and then rely on the upstream proxy protocol upstream transport to pass it along.

**Comment by Gala-R** [comment]
> Looking at the config https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/proxy_protocol.proto#envoy-v3-api-msg-config-core-v3-proxyprotocolconfig, I think custom TLVs are not supported. You could maybe manually create TLVs in a custom downstream filter, and then rely on the upstream proxy protocol upstream transport to pass it along.

Thank you very much for your reply.
