### ISSUE TITLE
Envoy possibly generating messages with invalid compression for GRPC JSON transcoding

### ISSUE THREAD

**Issue by banool** [envoyproxy/envoy#26176]
*Title*: Envoy possibly generating messages with invalid compression for GRPC JSON transcoding

*Description*:
I'm trying to use the gRPC JSON transcoder with Envoy. This is working as intended to proxy GRPC requests, but when making requests with curl, it fails. See repro for more.

*Repro steps*:
First off, here is the envoy config: https://gist.github.com/banool/273a97009de2366de158e822e934b17e.

See here the logs of envoy on startup: 

So when I make this request with grpcurl, it works as expected:
```
grpcurl -plaintext -proto crates/aptos-protos/proto/aptos/api/v2/api.proto -import-path crates/aptos-protos/proto -d '{"account_address":"0x1","module_names":["coin"],"raw":true}' 127.0.0.1:51052 aptos.api.v2.ApiV2/GetAccountModules
```
Output: https://gist.github.com/banool/d1e56670ad7eb5b13e5f6c69ed42163d.

However when I make a request with curl, I get this:
```
$ curl -H "Content-Type: application/json" -d '{"account_address":"0x1","modules":["coin"],"raw":true}' -v localhost:51052/aptos.api.v2.ApiV2/GetAccountModules
*   Trying 127.0.0.1:51052...
* Connected to localhost (127.0.0.1) port 51052 (#0)
> POST /aptos.api.v2.ApiV2/GetAccountModules HTTP/1.1
> Host: localhost:51052
> User-Agent: curl/7.86.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 55
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/grpc
< grpc-status: 13
< grpc-message: protocol%20error:%20received%20message%20with%20invalid%20compression%20flag:%20123%20(valid%20flags%20are%200%20and%201),%20while%20sending%20request
< content-length: 0
< date: Mon, 20 Mar 2023 14:47:14 GMT
< x-envoy-upstream-service-time: 1
< server: envoy
<
* Connection #0 to host localhost left intact
```

As you can see, the upstream server (Tonic) says that the request passed through by the proxy uses an invalid compression flag, implying that the message being formed is missing the necessary bytes at the start of the message.

Unfortunately envoy_collect.py doesn't seem to work:
```
$ python envoy_collect.py --envoy-binary `which envoy` --output-path /tmp/debug.tar -c ~/envoy-grpc-gateway.yaml
Traceback (most recent call last):
  File "/private/tmp/googleapis/envoy_collect.py", line 243, in <module>
    sys.exit(envoy_collect(*parser.parse_known_args(sys.argv)))
  File "/private/tmp/googleapis/envoy_collect.py", line 168, in envoy_collect
    modified_envoy_config_path, access_log_paths = modify_envoy_config(
  File "/private/tmp/googleapis/envoy_collect.py", line 82, in modify_envoy_config
    envoy_config = json.loads(f.read())
  File "/Users/dport/.pyenv/versions/3.9.13/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/dport/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/dport/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)
- Stats: https://gist.github.com/banool/dae2e9d4f6c4e0e5435163d91027eeb2
- Clusters: https://gist.github.com/banool/0cc0afbe6f57bc2600a13a0aa3195839
- Routes: https://gist.github.com/banool/ea6b63bd50480b6e6adc5bbdac7ddcbb
- Server_info: https://gist.github.com/banool/c2e293b759aa11339ae8757b39766774

*Config*:
See above.

*Logs*:
See above.

**Comment by alyssawilk** [comment]
I don't think that Envoy does any compresion unless you explicitly configure it on?  ccing transcoder owners,  @qiwzhang @lizan

**Comment by banool** [comment]
I've tried my experiment again and I'm still hitting this problem, any advice?

**Comment by Dao007forever** [comment]
Also having the same problem where the first bit (compression flag) is not 0 or 1.

**Comment by banool** [comment]
I'll check again soon to see if this problem still occurs with that `auto_mapping` flag.
