### ISSUE TITLE
tsan timeouts too low

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#26177]
Various integration tests are failing on tsan due to the default 300s timeout.  all e2e tests should probably just be large to avoid this.
e.g.

https://dev.azure.com/cncf/envoy/_build/results?buildId=131335&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137&l=3134

//test/integration:local_reply_integration_test                         TIMEOUT in 1 out of 2 in 306.4s

https://dev.azure.com/cncf/envoy/_build/results?buildId=131374&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=f1bd857c-4611-5620-0b5a-d15324470098&l=1435
//test/extensions/filters/http/jwt_authn:filter_integration_test        TIMEOUT in 1 out of 6 in 391.3s

//test/integration:sds_dynamic_integration_test                         TIMEOUT in 414.3s

**Comment by phlax** [comment]
increase the sharding i think

altho i think that the pr that just landed that downloads less might help

**Comment by alyssawilk** [comment]
we can also increase sharding but semantically they're large tests: https://testing.googleblog.com/2010/12/test-sizes.html and I think it'll avoid a few problems if we tag them as such.
