### ISSUE TITLE
Unable to do integration test in linux64 system due to  access denied to: /config_dump

### ISSUE THREAD

**Issue by iamjustadd** [envoyproxy/envoy#26199]
[Title] Unable to do integration test in linux64 system due to  access denied to: /config_dump

[Description]
Hi envoy,
I'm currently trying to write an integration test for my customize filter, While in my setup() function, when I called initialize, I always got Error message like:

`[2023-03-21 06:15:10.537][21][debug][http] [source/common/http/conn_manager_impl.cc:939] [C1][S11182445455535709229] request headers complete (end_stream=true):
':authority', 'host'
':path', '/config_dump'
':method', 'GET'

[2023-03-21 06:15:10.537][21][debug][http] [source/common/http/conn_manager_impl.cc:923] [C1][S11182445455535709229] request end stream
[2023-03-21 06:15:10.537][21][debug][connection] [./source/common/network/connection_impl.h:91] [C1] current connecting state: false
[2023-03-21 06:15:10.537][21][debug][admin] [source/server/admin/admin_filter.cc:85] [C1][S11182445455535709229] request complete: path: /config_dump
[2023-03-21 06:15:10.538][21][error][admin] [source/server/admin/admin.cc:359] admin interface, access denied to: /config_dump
[2023-03-21 06:15:10.538][21][trace][http] [source/common/http/filter_manager.cc:1064] [C1][S11182445455535709229] encode headers called: filter= status=0
[2023-03-21 06:15:10.538][21][debug][http] [source/common/http/conn_manager_impl.cc:1564] [C1][S11182445455535709229] encoding headers via codec (end_stream=false):
':status', '405'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Tue, 21 Mar 2023 06:15:10 GMT'
'server', 'envoy'`

The backtrace is:
`test/integration/base_integration_test.cc:721: Failure
Expected equality of these values:
  "200"
    Which is: 0x558ccf8a8141
  response->headers().getStatusValue()
    Which is: "405"
Stack trace:
  0x558ccc2dfdbf: Envoy::BaseIntegrationTest::checkForMissingTagExtractionRules()
  0x558ccc2d4fff: Envoy::BaseIntegrationTest::initialize()
  0x558ccc26d241: Envoy::HttpIntegrationTest::initialize()
  0x558ccc0ffeef: Envoy::Extensions::HttpFilters::JwtAuthn::(anonymous namespace)::LocalJwksIntegrationTest_WithGoodToken_Test::TestBody()
  0x558ccf397fdd: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x558ccf39314d: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x558ccf379d06: testing::Test::Run()
  0x558ccf37a729: testing::TestInfo::Run()
... Google Test internal frames ...

My system is ubuntu16.04 
bazel version 6.1.0

The config used in prependFilter is

`const std::string DefaultConfig = R"EOF(
name: envoy.filters.http.authn
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.authn.v3.Authn
)EOF";`

Code:
`    config_helper_.prependFilter(DefaultConfig);
    initialize();`

Can you give me some help on this? How can I avoid this problem and run my test.

Thanks,
Martin

**Comment by alyssawilk** [comment]
are you aiming your config_dump request at the main listener port or the admin port?  It may be helpful to look at the existing integration tests to see how this works.

**Comment by iamjustadd** [comment]
Hi wilk,
I'm not aiming the config_dump request to anywhere.
It is called by Envoy::BaseIntegrationTest::initialize().
And yes, I'm imitating to write these code like other integration test: just extend the HttpIntegrationTest, implement the setup function , which add a prepend filter and the call initialize which is point to HttpIntegrationTest::initialize();

**Comment by iamjustadd** [comment]
Close this issue, it's an user error.
