### ISSUE TITLE
logging / error handling in golang filters 

### ISSUE THREAD

**Issue by subzerobo** [envoyproxy/envoy#26232]
*Title*: *How to handle errors or emit logs in golang filters*

*Description*:
Is there a standard way to handle/log errors in the filter `ConfigFactory` method?
https://github.com/envoyproxy/envoy/blob/main/examples/golang/simple/config.go#L24

I couldn't find any decent way to write logs or handle errors in the golang filter example.

**Comment by alyssawilk** [comment]
@wangfakang @doujiang24

**Comment by doujiang24** [comment]
Hello @subzerobo , thanks for your asking

It's not recommended to parse config in the `ConfigFactory`, it's better to register a `StreamFilterConfigParser` to parse config.
i.e. https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/test_data/routeconfig/config.go#L38-L53

Also, there is another issue, in the original design, errors should not happen while parsing config, so, just panic to fast fail.

But I have to say it might be overkill, maybe we should change the `Parse` method from
```
Parse(any *anypb.Any) interface{}
```
to
```
Parse(any *anypb.Any) interface{}, error
```

that means
1. the `Parser` could return an error
2. then, return config_id = 0 to C++ side,
3. then, reject the config, which depends on this issue: https://github.com/envoyproxy/envoy/issues/25369

Do you like this design? Thanks!

**Comment by subzerobo** [comment]
Hello @doujiang24 

Thank you for the recommendation. Yeah, sure, I would love that!
