### ISSUE TITLE
Is it possible to filter debug access logs for UDP listeners

### ISSUE THREAD

**Issue by stan-irl** [envoyproxy/envoy#26249]
*Title*: *Is it possible to filter debug access logs for UDP listeners*

*Description*:
I know that theoretically its possible to set a filter on the `access_log` and `proxy_access_log` field but in practice which of these filters will work for UDP. most of them are HTTP specific: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#config-accesslog-v3-accesslogfilter:

```
{
  "status_code_filter": {...},
  "duration_filter": {...},
  "not_health_check_filter": {...},
  "traceable_filter": {...},
  "runtime_filter": {...},
  "and_filter": {...},
  "or_filter": {...},
  "header_filter": {...},
  "response_flag_filter": {...},
  "grpc_status_filter": {...},
  "extension_filter": {...},
  "metadata_filter": {...}
}
```

I just want a way to totally disable the logs because when i enable debug logging for other issues i'm getting millions of useless logs that blow up my infra like this:

```
[2023-03-20 17:42:01.338][17][debug][misc] [source/common/network/utility.cc:675] Receive a packet with 90 bytes from 127.0.0.1:49514
```

I tried `duration_filter` less than 100sec which I was hoping would catch everything but I started getting crashes.

[optional *Relevant Links*:]
>N/A

**Comment by zuercher** [comment]
Looking at how the UDP proxy logs, I think the only access log filter that applies is the `metadata_filter`.  Depending on whether you're using the session or proxy logging the only fields available are defined here: https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc#L305-L342. for The metadata filter, the filter name would be `"udp.proxy.proxy"` or `"udp.proxy.session"` and the path would be `"bytes_sent"` or similar. The UDP proxy doesn't seem to invoke any of the StreamInfo functions that would record durations for requests, so I don't think you can log or filter on duration and none of the metadata it sets is related to duration either.

As an aside, we would like more details on any crashes you encountered configuring access log filters configured in the UDP proxy (or any other extension, for that matter).

This log line

> `[2023-03-20 17:42:01.338][17][debug][misc] [source/common/network/utility.cc:675] Receive a packet with 90 bytes from 127.0.0.1:49514`

looks like an Envoy application log entry. Those are not access logs and they don't support filtering per se. The log level can be controlled by [command line flags](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-l) and the [admin endpoints](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--logging). Application log levels can be set to different values for different components, which might help your debugging.

**Comment by stan-irl** [comment]
Bump

**Comment by zuercher** [comment]
I'm not sure what else to say? UDP access logs can be filtered, but not by duration at this time. I recommend opening a separate issue requesting that as a feature, if you'd like to see support for that.
