### ISSUE TITLE
mobile: future proof compilation correctness of xds related APIs

### ISSUE THREAD

**Issue by Augustyniak** [envoyproxy/envoy#26259]
*Title*: *Future proof compilation correctness of xds related APIs*

*Description*:
With all of the compilation flags that continue to be added to the projects it gets harder and harder to ensure that the project compiles correctly in the case of all possible variations of these flags. `google_grpc` compilation flag/option seems to be one of the most complicated ones. It's enabled by default in debug builds and disabled in release builds. Since our CI builds debug builds only it has no way of catching prod issues.

Figure out how to change the configuration of the project and/or CI so that CI checks are able to catch any issues related to `google_grpc` being disabled/enabled.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/pull/26250

**Comment by caschoener** [comment]
https://github.com/envoyproxy/envoy/blob/main/.github/workflows/mobile-compile_time_options.yml

I see
