### ISSUE TITLE
Replace git_sha_rewriter with Bazel native approach

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2625]
Bazel lost its forced md5 stamping a while back, so we should be able to use a `genrule` and `-Wl,@$(location :label_for_the_file)` in linkopts to replace the https://github.com/envoyproxy/envoy/blob/master/tools/git_sha_rewriter.py hack.

**Comment by htuch** [comment]
See also https://github.com/bazelbuild/bazel/issues/2805.

**Comment by htuch** [comment]
See also https://docs.bazel.build/versions/master/user-manual.html#workspace_status (improved docs on workspace status command) and related documentation issue https://github.com/bazelbuild/bazel/issues/2893.

**Comment by oquenchil** [comment]
Hey,

here's a full example of the workaround while we do the cleanup to support a slightly better way of passing files with options to the linker.
------------------------------BUILD file------------------------------
```
sh_binary(
    name = "build_id_writer",
    srcs = ["build_id_writer.sh"],
)

genrule(
    name = "build_id_flag_generator",
    outs = ["linkopts.lds"],
    stamp = 1,
    cmd = "$(location build_id_writer) > $@",
    tools = ["build_id_writer"],
)

cc_binary(
    name = "bin",
    srcs = ["main.cc"],
    linkopts = ["-Wl,@$(location linkopts.lds)"],
    deps = ["linkopts.lds"],
)
```

------------------------------build_id_writer.sh------------------------------
```
#!/bin/bash

BUILD_ID_OPTION="--build-id=0x"
GIT_COMMIT_HASH=$(grep STABLE_GIT_COMMIT bazel-out/stable-status.txt| cut -f2 -d" ")
echo "$BUILD_ID_OPTION""$GIT_COMMIT_HASH"
```

------------------------------workspace_status.sh------------------------------
```
#!/bin/bash
echo "CURRENT_TIME $(date +%s)"
echo "RANDOM_HASH $(cat /dev/urandom | head -c16 | md5sum 2>/dev/null | cut -f1 -d' ')"
echo "STABLE_GIT_COMMIT $(git rev-parse HEAD)"
echo "STABLE_USER_NAME $USER"
```

-------------------------------
The bazel command line to build the binary would be:
`bazel build --workspace_status_command=./workspace_status.sh :bin`
