### ISSUE TITLE
FileSystemHttpCacheTestWithNoDefaultCache.EvictsOldestFilesUntilUnderCountLimit  flake

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#26261]
[2023-03-22 11:53:43.554][15][info][main] [source/extensions/common/async_files/async_file_manager_thread_pool.cc:41] AsyncFileManagerThreadPool created with id '', with 1 threads
test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc:153: Failure
Expected equality of these values:
  cache_->stats().size_bytes_.value()
    Which is: 15
  file_contents.size() * 2
    Which is: 10
Stack trace:
  0x8bb2bb: Envoy::Extensions::HttpFilters::Cache::FileSystemHttpCache::FileSystemHttpCacheTestWithNoDefaultCache_EvictsOldestFilesUntilUnderCountLimit_Test::TestBody()
  0x16f6cec: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x16f6bad: testing::Test::Run()
  0x16f7e07: testing::TestInfo::Run()
... Google Test internal frames ...

test/extensions/http/cache/file_system_http_cache/file_system_http_cache_test.cc:154: Failure
Expected equality of these values:
  cache_->stats().size_count_.value()
    Which is: 3
  2
Stack trace:
  0x8bb3cf: Envoy::Extensions::HttpFilters::Cache::FileSystemHttpCache::FileSystemHttpCacheTestWithNoDefaultCache_EvictsOldestFilesUntilUnderCountLimit_Test::TestBody()
  0x16f6cec: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x16f6bad: testing::Test::Run()
  0x16f7e07: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] FileSystemHttpCacheTestWithNoDefaultCache.EvictsOldestFilesUntilUnderCountLimit (1024 ms)

**Comment by ravenblackx** [comment]
Resolved by #26612.
