### ISSUE TITLE
During slow start phase, adding a new pod causes a brief surge of traffic for old pods within the slow start window

### ISSUE THREAD

**Issue by BruceMa29** [envoyproxy/envoy#26290]
*Title*: *During slow start phase, adding a new pod causes a brief surge of traffic for old pods within the slow start window*

*Description*:
We discovered this issue during our load testing process. During the startup process, adding a new pod causes a brief surge of traffic for old pods within the slow start window. However, when adding two or more pods, this phenomenon does not occur.

we use DestinationRule，warmupDurationSecs is set 120s， The QPS (Queries Per Second) during load testing was 500.

Below is the traffic monitoring chart during the load testing process.

![image](https://user-images.githubusercontent.com/63951257/227185437-f7d6bfce-c983-40ee-8309-9cfce27544ae.png)

*Question*:

Why is there a surge in traffic and can this phenomenon be avoided?

**Comment by alyssawilk** [comment]
cc @nezdolik

**Comment by nezdolik** [comment]
Hi @BruceMa29, am not familiar with Istio terminology (DestinationRule),  but assume that you have used either RoundRobin or LeastRequest lbs during load testing, since those are the only lb types that support slow start. 
From looking at the graph, the surge occurred 15 seconds before blue endpoint started receiving traffic. Was the blue endpoint spawned up at 18:16 and this is just metric delay of 15 seconds?
Did you observe the same phenomenon of traffic surge without slow start enabled?

**Comment by BruceMa29** [comment]
Hi @nezdolik ,

**Comment by BruceMa29** [comment]
Hi @nezdolik , 

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/63951257/227946742-cd84c5e1-458d-4044-8a0c-d304eeee2811.png">

**Comment by BruceMa29** [comment]
Hi @nezdolik , 

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/63951257/227946742-cd84c5e1-458d-4044-8a0c-d304eeee2811.png">

**Comment by nezdolik** [comment]
Thanks for the information @BruceMa29, i will try to reproduce the issue in the tests.

**Comment by nezdolik** [comment]
@BruceMa29 one more observation with the load test that you were running. You mentioned blue endpoint was spawned up at 18:16:00. Looking at the graph, the traffic started going down for yellow endpoint at 18:15:30 and kept going down for 30 sec. Request rate for green endpoint started increasing 18:15:45 and kept going up for 15 sec till 18:16:00. So increase of rps for green endpoint happened before the blue endpoint was added. Is that correct?

**Comment by BruceMa29** [comment]
Yes, that's correct.

**Comment by BruceMa29** [comment]
@nezdolik Hello, is there any progress in the troubleshooting currently?

**Comment by BruceMa29** [comment]
@nezdolik Thanks for your answer. However, I noticed that there are some differences between our load testing scenarios. In our scenario, the monitoring data is collected every 15 seconds, and the traffic is sustained during the test. In your scenario, the monitoring data is collected every 1 minute, and the traffic is not a stable amount. I am not sure if the above differences are the cause of the differences in the load testing results.
      I will enable debug logging and perform the load test again, and then share the logs with you.

**Comment by BruceMa29** [comment]
@nezdolik Hi, I enabled debug logging for Envoy and conducted load testing on the service, but did not find any logs related to warm-up. There was no difference compared to not using warm-up.

**Comment by BruceMa29** [comment]
@nezdolik Hi, is there any progress in the troubleshooting currently?

**Comment by nezdolik** [comment]
@BruceMa29 did not have capacity yet to run second round of testing, i will get back to you by mid of this week.

**Comment by BruceMa29** [comment]
@nezdolik Thank you very much.

**Comment by nezdolik** [comment]
@BruceMa29 i reran experiments over longer period of time with more stable traffic pattern and 30s metric resolution. I still cannot observe any traffic spike before a new pod is spawned up, rather i see a very small dip for existing endpoints when new endpoint starts taking small % of traffic:
<img width="2579" alt="Screenshot 2023-04-28 at 13 24 20" src="https://user-images.githubusercontent.com/14430883/235142055-6a899dbc-94be-401c-b50c-5ce4f99a0e52.png">
<img width="2601" alt="Screenshot 2023-04-28 at 13 57 50" src="https://user-images.githubusercontent.com/14430883/235142073-bd6eb78b-134b-4924-8fa7-a833341b6b24.png">

Could you attach Envoy config dump (by curling http://{ENVOY_IP}:8001/config_dump of a running load tested instance)?

**Comment by nezdolik** [comment]
@BruceMa29 tested on v1.25.4.

**Comment by BruceMa29** [comment]
@nezdolik  Hi Nezdolii, Would you be able to test it using version v1.22.5？Since I can consistently reproduce this issue, I suspect that it might be related to the version.

**Comment by nezdolik** [comment]
@BruceMa29 apologies, missed the ping. I will rerun the test on v 1.22.5 this week and report back the results.

**Comment by BruceMa29** [comment]
@nezdolik Thanks !

**Comment by nezdolik** [comment]
<img width="2582" alt="Screenshot 2023-05-29 at 13 48 13" src="https://github.com/envoyproxy/envoy/assets/14430883/57127ebd-79b7-487f-894b-9a4671e33a86">
Reran experiment on v 1.22.5. @BruceMa29 do you observe the same traffic spike in production? 
There is little i can help with at this point, unless you could attach envoy config and stats dump that are used in the experiment.

**Comment by nezdolik** [comment]
@BruceMa29 your problem sounds very similar to https://github.com/envoyproxy/envoy/issues/29008, if you don't make use of locality weighted load balancing, check if disabling it helps.

**Comment by BruceMa29** [comment]
@nezdolik thanks very much
