### ISSUE TITLE
Allow regex based descriptor values in Local Rate Limiter

### ISSUE THREAD

**Issue by 91pavan** [envoyproxy/envoy#26303]
Hello all,

I'm trying to setup specific rate limits if the incoming requests contain an Authorization header, but I'm having some difficulties getting that to work. It works well if I set a specific value like you see in the config, but we don't want that. 

Can I add in a regex in the descriptor value? I tried not providing a descriptor value but that didn't work either.

Here is what I have: so far:

    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - request_headers:
                descriptor_key: authorization
                header_name: Authorization
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              descriptors:
              - entries:
                - key: authorization
                  value: test
                token_bucket:
                  fill_interval:
                    seconds: 60
                  max_tokens: 100
                  tokens_per_fill:
                    value: 100
              filter_enabled:
                default_value:
                  numerator: 100
                runtime_key: rate limit reached
              filter_enforced:
                default_value:
                  numerator: 100
                runtime_key: local_rate_limit_enforced
                
Any suggestions as to how to get this working?

**Comment by alyssawilk** [comment]
cc @kyessenov @zhxie

**Comment by zhxie** [comment]
It might be ok to add a string matcher field in the rate limit descriptor entry to support prefix, suffix, regex and so on, which will request some code changes.

**Comment by zhxie** [comment]
I am afraid that we do not have any ability to do logical comparison against rate limit descriptors now.
