### ISSUE TITLE
If secret files are not available when Envoy is started, they are not watched

### ISSUE THREAD

**Issue by zhouxiaobo1990** [envoyproxy/envoy#26312]
*Description*:

I am working on the SDS configuration from the filesystem by following the instruction of [example three](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-three-certificate-rotation-for-xds-grpc-connection).

If `/certs/sds_cert.pem` is there when Envoy is started, everything works. Watch is triggered correctly and secret is updated.

If `/certs/sds_cert.pem` is not there when Envoy is started, watch is not triggered. If I make`/certs/sds_cert.pem` available after Envoy is started, secret is not updated.

*Repro steps*:

1. Follow [example three](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-three-certificate-rotation-for-xds-grpc-connection).
1. Remove `/certs/sds_cert.pem`
1. Start envoy.
1. Add back `/certs/sds_cert.pem`.
1. Secret is not updated.

**Comment by alyssawilk** [comment]
cc @adisuissa @ggreenway

**Comment by soulxu** [comment]
I didn't test that, but I guess that may not consider as a `move`, you can see the note in doc https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#config-core-v3-pathconfigsource

`If watched_directory is not configured, Envoy will watch the file path for moves.`
