### ISSUE TITLE
[Jwt_authn filter] Split metrics of the same type of filter*

### ISSUE THREAD

**Issue by amiozzo** [envoyproxy/envoy#26316]
*Split metrics with the same filter*

>We are using jwt_autn filter to validate the signature of two jwt.  For this, we have two diferentes files to split and identify differents errors and who makes them. (We had a problem in the pass attended in this issue: https://github.com/envoyproxy/envoy/issues/24427)

The question is can we split the metrics using two differents providers of the same filter?

**Comment by alyssawilk** [comment]
cc @qiwzhang
