### ISSUE TITLE
investigate http2 performance under chaos testing under 3% packet loss

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2632]
*Description*:
Dan Tehranian wote in a twilio blog post "Discovering Issues with HTTP/2 via Chaos Testing". About how packet loss creates a latency spike in Envoy under HTTP/2

I haven't dived into this deeply yet, but I wanted to capture the issue so it doesn't get lost.

*Relevant Links*: https://www.twilio.com/blog/2017/10/http2-issues.html

**Comment by tehranian** [comment]
👀

**Comment by mattklein123** [comment]
@jmarantz FYI this behavior is inherent in the HTTP/2 protocol and there is not very much that Envoy can do to improve the situation. The only thing that would help, which I have considered in the past, is allowing the HTTP/2 connection pool to create > 1 connection per upstream hosts. So basically at the cost of memory a user could reduce HOL blocking issues if they desire. I guess we can use this issue to track that?

**Comment by alyssawilk** [comment]
(will be) Fixed by #2557  ;-)

**Comment by mattklein123** [comment]
Going to close this for now as I don't think this is actionable. We are tracking both the QUIC work as well as other items for having multiple h2 connections per upstream host which are both ways around this issue.
