### ISSUE TITLE
picture maybe wrong in the doc

### ISSUE THREAD

**Issue by jingb** [envoyproxy/envoy#26329]
*Title*: *picture maybe in the doc*

*Description*:
>the section resource update in xds protocol description page，there is picture may be wrong.
![image](https://user-images.githubusercontent.com/9337766/227478252-c54f8813-38ae-4c41-aaf5-382138163f2e.png)

[optional *Relevant Links*:]
>[Any extra documentation required to understand the issue.](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-updates)

**Comment by alyssawilk** [comment]
cc @adisuissa @phlax

**Comment by adisuissa** [comment]
It should stay `bar` assuming that a CDS response did not arrive before that step and updated the interested EDS resources.
This change may happen if there was a CDS response that removed the `bar` and added `baz`, but I don't think this is what the diagram meant to convey.

@htuch you added the diagram at #3036. Do you happen to have the source so I'll edit it? If not I can try to recreate/modify the current one.

**Comment by htuch** [comment]
@adisuissa I have shared this with you internally all the xDS sequence diagrams, go for it.
