### ISSUE TITLE
Defect in duplicate query parameter handling in ExtAuthZ when using query_parameters_to_remove and query_parameters_to_add on a CheckResponse

### ISSUE THREAD

**Issue by jweaver-personal** [envoyproxy/envoy#26345]
*Title*: *Defect in duplicate query parameter handling in ExtAuthZ (grpc) when using `query_parameters_to_remove` and `query_parameters_to_add` on a CheckResponse*

*Description*:
There is a defect in duplicate query parameter handling in ExtAuthZ (grpc) when using `query_parameters_to_remove` on a CheckResponse

If you are attempting to proxy a request such as https://site.com/?p=foo&p=bar&p=baz&unwanted=true 
And say remove unwanted in `query_parameters_to_remove` then only ONE of the p query parameters is set on the reconstituted URL. The first one in this case of p=foo so all we get back on the request is https://site.com/?p=foo

The same happens with `query_parameters_to_add` if you set duplicate query parameters only the LAST is taken on the reconstituted URL; including overwriting parameters on the original URL. So  https://site.com/?p=foo and you add p=bar then the reconstituted URL is https://site.com/?p=bar instead of https://site.com/?p=foo&p=bar

**Comment by lizan** [comment]
@esmet @pradeepcrao @ggreenway

**Comment by ggreenway** [comment]
Yep, in both cases, we run the query params through `Http::Utility::parseQueryString()` and make the changes on that. This puts the query params into a `std::map` (not a multimap), so all duplicates get removed. This seems like a bug.

**Comment by gmurray-8372** [comment]
I believe this defect still exists...can it please be reconsidered for getting into Envoy's defect backlog?

**Comment by ggreenway** [comment]
Happy to re-open it, but that doesn't mean someone will fix it.

**Comment by gmurray-8372** [comment]
Thanks @ggreenway !  I'm discussing with my team whether we would decide to provide a PR to address this.

Do you (or does anyone) have any concerns that a possible fix might conflict with (or be rejected because of) [HTTP Parameter Pollution](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution)?

**Comment by ggreenway** [comment]
No, I think a fix would improve the situation with parameter pollution. Right now, the extauthz service only sees one of each named parameter; duplicates are removed. But the duplicates would be sent to the upstream server. Having both extauthz and upstream see the same data is more consistent.

**Comment by gmurray-8372** [comment]
👍 I will discuss with my team.

**Comment by littlecatherine** [comment]
@gmurray-8372 This is a very critical feature for us. Is there any plan to implement it?

**Comment by gmurray-8372** [comment]
@littlecatherine , unfortunately we do not have this on our radar because we found ways to either work around it or ignore it.  Sorry, I know you were hoping for a different answer.

**Comment by littlecatherine** [comment]
> we found ways to either work around it or ignore it

@gmurray-8372 Could you please suggest what workaround you find?

**Comment by gmurray-8372** [comment]
Unfortunately, the workaround is very specific to our codebase.
