### ISSUE TITLE
wrong example in golang filter docs: Unrecognized option

### ISSUE THREAD

**Issue by timebug** [envoyproxy/envoy#26393]
*Title*: *One line description*

*Description*: wrong example in golang filter docs

When I follow the example run this command, get "Unrecognized option" ERROR:

```
$ bazel run @go_sdk//:bin/go build --buildmode=c-shared  -v -o path/to/output/libfoo.so path/to/src/foo
ERROR: --buildmode=c-shared :: Unrecognized option: --buildmode=c-shared
```

and, the following command work fine:

```
$ bazel run @go_sdk//:bin/go build -- --buildmode=c-shared  -v -o path/to/output/libfoo.so path/to/src/foo
INFO: Analyzed target @go_sdk//:bin/go (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
...
```

[optional *Relevant Links*:]

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter.html

**Comment by phlax** [comment]
do you fancy raising a PR to address @timebug

**Comment by timebug** [comment]
> do you fancy raising a PR to address @timebug

@phlax done.
