### ISSUE TITLE
can we have more than one listeners configured in redis proxy

### ISSUE THREAD

**Issue by shankar4322** [envoyproxy/envoy#26406]
*static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 10.10.10.10
        port_value: 1999
   
     socket_address:
        address: 20.20.20.20
        port_value: 1999

so here want to have 2 listeners with different ip and same port

**Comment by lizan** [comment]
You should be able to configure a listener with `additional_addresses` https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-msg-config-listener-v3-listener
