### ISSUE TITLE
Limit reconnection rate for redis clients

### ISSUE THREAD

**Issue by LeonGao91** [envoyproxy/envoy#26400]
*Title*: 
Limit reconnection rate for redis clients

*Description*:
We observe that sometimes when redis cluster nodes are busy (during cluster rolling restart for example), envoy will experience connection/ops timeouts then it will need to reconnect to redis. However, when we have many envoy proxies reconnecting at the same time, the busy redis node will need to deal with client reconnection storm and eventually our system falls into vicious cycle. Here is a [good explanation](https://www.youtube.com/watch?v=6Ctu-xOxz9s) on this redis issue in general.

Currently, when it happens we don't have a good way to mitigate it. We should probably add rate limiting or exponential backoff for the redis client reconnections.

[optional *Relevant Links*:]
An example of a redis cluster node experiencing reconnection storm from envoy
<img width="1085" alt="Screen Shot 2023-03-28 at 3 06 52 AM" src="https://user-images.githubusercontent.com/5714374/228203213-5a6d5b07-23ca-402a-b2c5-1f225a827824.png">

An example of continues timeouts from all envoy instances when it happens:
<img width="1247" alt="Screen Shot 2023-03-28 at 3 24 18 AM" src="https://user-images.githubusercontent.com/5714374/228207313-01e8fa38-a4d4-4c25-84fc-9583c50abea0.png">

**Comment by lizan** [comment]
@msukalski @henryyyang @weisisea

**Comment by LeonGao91** [comment]
I think we can add rate limit with the TokenBucket for the redis client creation, please let me know if it makes sense I can put a draft for it

**Comment by LeonGao91** [comment]
Hi @lizan (or someone else :), I have put a draft to add some protections on the connection rate, please let me know if the idea makes sense to you
