### ISSUE TITLE
Cannot build under ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by SniperCZE** [envoyproxy/envoy#2645]
*Title*: *Envoy loadbalancer cannot compile under Ubuntu 16.04 LTS*

*Description*:
I'm trying to compile Envoy under Ubuntu 16.04. I've installed all required libraries but compilation still ends with errors in etc_authz_lib. Build log in attachment.
[envoy_build.log](https://github.com/envoyproxy/envoy/files/1740083/envoy_build.log)

**Comment by alyssawilk** [comment]
I think you caught us with a broken build :-)

It should be fixed at head by 
https://github.com/envoyproxy/envoy/pull/2646

Can you do a fresh pull and try again?

**Comment by mattklein123** [comment]
I think this is fixed so closing.
