### ISSUE TITLE
Long-lived connection is not closed with `close_connections_on_host_set_change = true` option

### ISSUE THREAD

**Issue by krapie** [envoyproxy/envoy#26459]
*Title*: *Long-lived connection is not closed with `close_connections_on_host_set_change = true` option*

*Description*:
Hi, I'm currently using Envoy proxy(in fact, I'm using Istio) with hash-based load balancing to distribute workloads throughout servers. I'm using both unary and stream gRPC to communicate with client.

Everything is working just fine, but I've faced "split-brain" of connections. Below explains how split-brain of connection occurs.
 
![Screenshot 2023-03-30 at 6 17 36 PM](https://user-images.githubusercontent.com/70474071/228789845-48b34d2b-949b-4628-9500-538fddbd46f8.png)
(Image from: https://docs.google.com/document/d/1yX8qRDXfbcOqNwSpaptFk1ru-bY_yHDLLOVBuLaclR4/edit#heading=h.cvkycohhpnph)

To solve this problem, I've configured `close_connections_on_host_set_change = true` option to drain/close all connections when there is change in cluster membership(host set change) via `EnvoyFilter` in Istio.

But connection wouldn't close even Envoy has been configured to `close_connections_on_host_set_change = true`. I've searched for this for a whole day, and found that `close_connections_on_host_set_change` will not work on gRPC stream because gRPC stream cannot be gracefully drained.

So my question is:
1. Is it possible to enforce force drain/closure of long-lived connections in current envoy?
2. I'm still confused about why long-lived connection(gRPC stream) is not closed. What it means that gRPC stream cannot be gracefully drained?

I'm currently searching for alternative way, where my gRPC server subscribes for xDS(CDS) changes and manually close gRPC stream. But I cannot find any references for retrieving xDS subscriptions or other API/RPCs for upstream cluster changes...

This is duplicate of https://github.com/envoyproxy/envoy/issues/8867, but this issue is closed, so I've renewed this issue.

[optional *Relevant Links*:]
This is references that I found:
- Issue: Support connection termination for hash-based load balancers: https://github.com/envoyproxy/envoy/issues/6730
- RFC for connection termination for hash-based load balancers: https://docs.google.com/document/d/1yX8qRDXfbcOqNwSpaptFk1ru-bY_yHDLLOVBuLaclR4/edit#heading=h.cvkycohhpnph
- PR: upstream: Introducing close_connections_on_host_set_change property: https://github.com/envoyproxy/envoy/pull/7675
- About long-lived connection redistribution on Envoy scale out: https://github.com/envoyproxy/envoy/issues/15283

**Comment by chromakode** [comment]
I'm experiencing this same issue for a similar use-case: consistent hashing long-lived websocket connections for a collaborative document store. When hosts are added to my RingHash lb and the destination for a hash key changes, existing websocket connections never terminate (even with `close_connections_on_host_set_change=true`). This causes split-brain in my application. Ideally, I'd like to be able to force these connections to be closed over my configured drain time period.

@lizan Would you please consider keeping this issue open to track the feature request?
