### ISSUE TITLE
Why do some headers have colon in Access Logging

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#26475]
I just read the doc about Access Logging: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage, and I just found that there is a colon before some headers, such as `%RES(:METHOD)%`, but for the others, such as `%REQ(USER-AGENT)%`, there isn't.
```
 [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
%RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
"%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n
```

Why is there such a difference?

**Comment by dio** [comment]
I think, Envoy normalizes headers to HTTP/2. Those headers prefixed by a colon are HTTP/2 pseudo headers https://www.rfc-editor.org/rfc/rfc7540. There are only four of them: `:method`, `:scheme`, `:authority`, and `:path`. See also: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#scheme.
