### ISSUE TITLE
kotlin_experimental_app seems broken

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#26470]
It's failing on various PRs including:
https://github.com/envoyproxy/envoy/actions/runs/4568616615/jobs/8064048538
https://github.com/envoyproxy/envoy/actions/runs/4565478422/jobs/8063156159

**Comment by alyssawilk** [comment]
@Augustyniak did https://github.com/envoyproxy/envoy/pull/26482 fix this?

**Comment by Augustyniak** [comment]
Yes, it did. Closing.
