### ISSUE TITLE
Wasm failing after unexpected panic

### ISSUE THREAD

**Issue by dragoscalinescu** [envoyproxy/envoy#26485]
Hi envoy team!

I'm using the proxy-wasm rust sdk (an older version as of now, 1.4.0).

I have an issue where some of my replicas reached an invalid state, after running fine for multiple hours. 

```
[critical][wasm] [source/extensions/common/wasm/context.cc:1181] wasm log rtcdp debatch-egress-1 vm_id: panicked at 'unexpected status: 2', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/hostcalls.rs:261:23\n"
[error][wasm] [source/extensions/common/wasm/wasm_vm.cc:38] Function: proxy_on_http_call_response failed: Uncaught RuntimeError: unreachable\n"
" 0: 0x2c01a - __rust_start_panic\n"
" 1: 0x2bffd - rust_panic\n"
" 2: 0x2bfcd - _ZN3std9panicking20rust_panic_with_hook17he2a025723e105e28E\n"
" 3: 0x2b5c1 -_ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hd9f8c213ec91b9d5E\n"
" 4: 0x2b500 - _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h6efd730283875809E\n"
" 5: 0x2bc3f - rust_begin_unwind\n"
" 6: 0x2d3d4 - _ZN4core9panicking9panic_fmt17hb02133958c1e7d35E\n"
" 7: 0x24323 - _ZN10proxy_wasm9hostcalls13get_map_value17h8f76686c8737a7b4E\n"
" 8: 0xa473 - _ZN63_$LT$debatch..Filter$u20$as$u20$proxy_wasm..traits..Context$GT$21on_http_call_response17h38adc080707d07a5E\n"
" 9: 0x1f8ee - _ZN10proxy_wasm10dispatcher10Dispatcher21on_http_call_response17h32cc94c5cad9dc17E\n"
```

As far as I understand, when I attempted to get the status header from a dispatched http call, the response header map was not actually ready.

```
fn on_http_call_response(&mut self, _token_id: u32, _num_headers: usize, body_size: usize, _num_trailers: usize) {
  self.get_http_call_response_header(":status").unwrap_or(String::new());
  ....
}
```

This would not be such a big of an issue by itself, but once this panic showed up, every future request resulted in `503 wasm failed`. I have to restart every faulty pod to make them work again.

Debug logs not showing much (the panic stopped showing after the first time):

```
[2023-03-31 11:59:37.648][65][debug][http] [source/common/http/filter_manager.cc:953] [C68190][S14693529014648669634] Sending local reply with details wasm_fail_stream
[2023-03-31 11:59:37.648][65][debug][http] [source/common/http/filter_manager.cc:930] [C68190][S14693529014648669634] Sending local reply with details wasm_fail_stream directly to the encoder
```

Is this some known issue with older proxy-wasm crate?

**Comment by dragoscalinescu** [comment]
As an update, I tried bumping to the latest proxy-wasm crate, which did not help.

Next I will inspect the `num_headers` field to see if it's 0, in which case I will stop trying to get the response header map. Will come back with updates.

**Comment by ajohnstone** [comment]
The behavior should not be to fail all consecutive requests in an unrecoverable state.
Deleting the wasmplugiin and/or rotating the pods is not a viable solution.

**Comment by dragoscalinescu** [comment]
Checking for the num_headers field before trying to access the header map seems to have helped, not seeing any more wasm_fails. 

However, envoy should handle this situation and not end up in an invalid filter chain state.

**Comment by MengjiaLiang** [comment]
I am seeing the same issue.
The panic of the wasm VM made all coming requests fail as they could not go through the wasm filter anymore.
Is there a way that Envoy can limit the issue inside a single HTTP stream instead of at the VM level?

**Comment by wbpcode** [comment]
see...

**Comment by kyessenov** [comment]
It's possible to re-snapshot VM to a working state, but unfortunately that logic is not implemented in Envoy. Currently, a crash in VM is effectively a downed Envoy, and you need specific probes to detect this condition.
