### ISSUE TITLE
//test/exe:main_common_test is broken in IPv6 only environments

### ISSUE THREAD

**Issue by dnoe** [envoyproxy/envoy#2649]
*Description*:
The recently added //test/exe:main_common_test does not work in IPv6 only environments, because the YAML file used by it uses 0.0.0.0 as a listening address. The test is not parameterized on IP versions in the manner of our other tests.

It can be temporarily worked around by no-oping the test when run in a non-IPv4 supporting environment, but it should be fixed properly to run in IPv4 only, IPv6 only, or dual stacked test environments.

**Comment by alyssawilk** [comment]
There's some utils for mangling but I'd suggest having your config inline, loading it up in the config helper (which already does v4/v6 conversion for you)

ConfigHelper(const Network::Address::IpVersion version,
               const std::string& config = HTTP_PROXY_CONFIG);

And spitting it out to a file
TestEnvironment::writeStringToFileForTest()

if at all possible!

**Comment by jmarantz** [comment]
@hennna who may be looking at this.

**Comment by akonradi** [comment]
I'll take this if nobody is working on it.
