### ISSUE TITLE
Support for Traffic prioritisation/Qos feature in Envoy

### ISSUE THREAD

**Issue by shreerangpande** [envoyproxy/envoy#26506]
We have a use case to prioritise certain traffic based on custom http headers and the max outstanding requests on the pod. Does envoy support such traffic prioritisation/Qos(quality of service) out of the box. If not, can you please suggest an approach to achieve the same in envoy(wasm filters?)

**Comment by mattklein123** [comment]
Would probably need more info on what you are trying to achieve in terms of actual QoS. Envoy today support route / connection pool priority where you can send some requests to a high priority connection pool. Will that work?

**Comment by shreerangpande** [comment]
@mattklein123 in case of a system overload(/congestion), we want to prioritise requests coming from high priority users over lower priority users. The tagging of the users as low or high priority will be available as part of HTTP headers. Can you please share if such a traffic prioritisation is possible in envoy. Also please share documentation on the connection pool priority you were mentioning

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-enum-config-core-v3-routingpriority. You should be able to use route matching to pick the route priority. This is imperfect, but high priority requests can be sent to dedicated connection pools.
