### ISSUE TITLE
Support hash based routing for redis-proxy

### ISSUE THREAD

**Issue by LeonGao91** [envoyproxy/envoy#26511]
*Title*: *Support hash based routing for redis-proxy*

*Description*:
Hi folks! We would like to get some thoughts on adding a hashing based routing to redis proxy, addition to the existing prefix routing mechanism.

Today, envoy supports prefix routing to configure more than one redis cluster, with the shadow-traffic capability. However, the prefix routing depends on the actual value of the keys so it is sometimes not very easy to use (for example the key prefix can be significantly skewed), especially when the team is supporting many different use cases thru envoy+redis without knowing much details on the user key values.

The proposal is to support a hashing slot based routing so we could perform partitioning/shadow traffic based on the hashing value of the keys, which could look something like this:
```
    message HashSlotRoutes {

      message RequestMirrorPolicy {

        string cluster = 1;

        RuntimeFractionalPercent runtime_fraction = 2;
      }

      // hashSlot to route the traffic
      // For example slots 0-4056 routes to cluster A, while 4057-8191 routes to cluster A, lets say we do hash(key, 8192)
      string hashSlot = 1;

      // Upstream cluster to forward the command to.
      string cluster = 2;

      // Indicates that the route has a request mirroring policy.
      repeated RequestMirrorPolicy request_mirror_policy = 4;
    }

    reserved "catch_all_cluster";

    repeated Route routes = 1;

    Route catch_all_route = 4;
  }
```

With this, we could easily split traffic evenly to more than one clusters, or perform shadow-write for a percentage of data, without managing the prefix value of the redis keys.

In the future we could also consider supporting more routing mechanisms (like consistent hashing) which does not need to manage the hashing slots.

**Comment by LeonGao91** [comment]
I was also reading https://github.com/envoyproxy/envoy/issues/25100 where this feature could be useful : )

**Comment by mattklein123** [comment]
Seems like a reasonable proposal if you want to do an API PR and we can discuss there?

**Comment by LeonGao91** [comment]
> Seems like a reasonable proposal if you want to do an API PR and we can discuss there?

Thanks for the response @mattklein123 ! I have put a PR for the proposed API change https://github.com/envoyproxy/envoy/pull/26708
