### ISSUE TITLE
support for automatic retry in CI

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#26519]
A lot of times when CI is running for PR, it fails for the first run, and ``/retest`` does not work until the whole Azure-Pipeline is done. Is it possible to add automatic retry for failed tasks, for say, 2 retries (most of the times, 2nd try works). Seems like this is supported: https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-195-update#automatic-retries-for-a-task

cc @phlax

**Comment by phlax** [comment]
not sure if we want this tbh - it would trigger too many false +ves and for a long job like coverage etc that would be a nightmare

mostly we are rinsing out the flakes, and presubmit which has more caching and doesnt run all tests is now pretty reliable

there are some ongoing issues - which are defo a priority to address - but i dont think would help much

**Comment by ohadvano** [comment]
@phlax maybe enable auto-retry just for the Linux-x64/Linux-Arm/Windows/MacOS stages? From my experience by now, in almost any pipeline run, at least one of them is failing out of flaky tests

**Comment by phlax** [comment]
@ohadvano retrying the entire job is **definitely** not the solution

**Comment by phlax** [comment]
... in fact we want the opposite of this - we have now made postsubmit a lot less flakey (by caching tests) so when a job fails its important to take notice of it and not just `/retest` (regardless of whether the job should be retested or requires a fix)

**Comment by phlax** [comment]
here is a good example of exactly why we dont want this https://dev.azure.com/cncf/envoy/_build/results?buildId=134354&view=results

in this case all of the platform tests failed, but that usually indicates genuine failure - the last thing we want is to trigger them all again.

on the basis that we have just gotten rid of flakey testing - and its a **huge** improvement imho - and that this suggestion is basically flakey testing in another form - im going to close this - but im defo open to suggestions on how we can address the remaining flakes and improve the performance of CI
