### ISSUE TITLE
Make envoy tags usable for golang filter SDK

### ISSUE THREAD

**Issue by fredmaggiowski** [envoyproxy/envoy#26527]
*Title*:

Make envoy tags usable for golang filter SDK

*Description*:

I'm using the golang sdk in my golang filter, but since I'm  using Envoy v1.25.3 I had to reverse engineer the ref to be placed in my go.mod file to be

```
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go v0.0.0-20230112191108-90880d93a9bd
```

It would be nice to be able to specify the same envoy version to make sure they always match, such as 

```
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go v1.25.3
```

**Comment by doujiang24** [comment]
Thanks! I'll figure out a way for it.

/assign @doujiang24

**Comment by doujiang24** [comment]
okay, I found a doc for it (https://go.dev/ref/mod#vcs-version)

If a module is defined in a subdirectory within the repository, that is, the [module subdirectory](https://go.dev/ref/mod#glos-module-subdirectory) portion of the module path is not empty, then each tag name must be prefixed with the module subdirectory, followed by a slash. For example, the module golang.org/x/tools/gopls is defined in the gopls subdirectory of the repository with root path golang.org/x/tools. The version v0.4.0 of that module must have the tag named gopls/v0.4.0 in that repository.

I think we have two choices:

1. the simplest way, move go.mod & go.sum to the root directory of the envoy repo.
2. need another tag for the subdirectory, when we bump a new release, i.e. need another tag `contrib/golang/v1.25.3` when release 1.25.3.

I was thinking it's better under the `contrib/golang`, but seems two tags for each release might be a bit noisy.
I personally prefer the 1 choice.

@phlax WDYT? Thanks!

**Comment by phlax** [comment]
@doujiang24 to clarify - when you say we need another tag do you mean an additional subdirectory and not a git tag

not sure about preference - i think it would be better not to place the go.mod in the root, but maybe thats ok if its part of a public facing api

**Comment by doujiang24** [comment]
Yep, the tag is a git tag, same as [v1.25.4](https://github.com/envoyproxy/envoy/releases/tag/v1.25.4), just use another name, i.e. `contrib/golang/v1.25.4`.

here is a sample, [gopls/v0.11.0](https://github.com/golang/tools/releases/tag/gopls%2Fv0.11.0).

Since we alway recommend the users to, use the same version of Go sdk (in the envoy repo) and envoy binary (compile from c++ code in the envoy repo).
then, we'd better add two git tags per release, that might be a bit noisy.

**Comment by phlax** [comment]
no objection to having a way of tagging go releases - but atm there is a lot of CI linked to tagging etc

we would also need to make it super-clear that its not an envoy tag/release

**Comment by phlax** [comment]
or go with the simplest way

**Comment by doujiang24** [comment]
yep, the simplest way could be better.
In the golang world, tag with the subdirectory prefix, is used for bumping different versions for different modules in subdirectories.
In envoy repo, we only have one golang module need the release tag.

I'll create a PR after https://github.com/envoyproxy/envoy/pull/26579 merged, thank you.
