### ISSUE TITLE
Time-to-first-byte HTTP metric & log variable

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#2654]
*Title*: Time-to-first-byte HTTP metric & log variable

*Description*:
We have a need for this metric but from what I can tell in the documentation & reading the code, it is not available in Envoy. I'm wondering if there would be any interest in adding this feature to the roadmap (if it's not already) or it being contributed? It looks like there's already [plans for it a grpc version](https://github.com/envoyproxy/envoy/blob/4bd671d81ccf04da488ed4a6f574632eea959428/source/common/access_log/grpc_access_log_impl.cc#L147)

*Relevant Links*:
[Envoy Access Logging](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log.html)
[Envoy HTTP Statistics](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/stats.html#config-http-conn-man-stats)

**Comment by mattklein123** [comment]
@derekargueta please sink up with @rodaine who is working on this. There should be no issue in exposing any of the new gRPC fields in the text access log formatter.

**Comment by rodaine** [comment]
Talked with @derekargueta in Slack. The TTFB is currently approximated with the RESPONSE_DURATION placeholder, which is made more accurate (though not 100%) in #2660. Supporting the other times will just require adding/documenting additional placeholders for missing values to match those provided in the ALS.

**Comment by mattklein123** [comment]
I believe this was fixed by @derekargueta
