### ISSUE TITLE
Remove `PATH` from `.bazelrc` `action_envs`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#26565]
One thing i have noticed is that my local RBE use (which uses a different container env to Envoy's CI) tends not to share caches with envoy CI, at least sometimes

as my usage doesnt appear to affect envoy CI or vice-versa i didnt worry about it, it seemed a feature - altho i did wonder

trying to track caching issues i noticed that we currently have `PATH` set as an `action_env` , about which the docs say...

> For example, environments with different $PATH variables won't share cache hits. Only environment variables explicitly whitelisted via --action_env are included in an action definition. Bazel's Debian/Ubuntu package used to install /etc/bazel.bazelrc with a whitelist of environment variables including $PATH. If you are getting fewer cache hits than expected, check that your environment doesn't have an old /etc/bazel.bazelrc file.

not sure if we have it set for legacy reasons or llvm reasons, but i see llvm has PATH specified elsewhere so it doesnt seem necessary, and removing it seems like a generally good idea

**Comment by phlax** [comment]
cc @keith

**Comment by phlax** [comment]
somewhat relatedly the `@envoy_repo` repo rule exposes `PATH` and `VERSION` which im wondering about in relation to caches being blown

in that case `PATH` (which is only meant for no-remote jobs) is the path to `WORKSPACE` not executable path and is derived from the `WORKSPACE` but im wondering the effect

**Comment by keith** [comment]
the problem with PATH is us generally supporting any directory for compilers and things. because of that i think we have to have it unless we solve that another way?

**Comment by phlax** [comment]
if we dont need for it CI, perhaps just documenting that you should set it if you need xyz from PATH with a warning about how it will affect caches i guess

**Comment by phlax** [comment]
another possible approach is to standardize the `PATH` between types of machine

**Comment by phlax** [comment]
thinking about this further - its not an issue for CI because no matter the host it alwasy runs in the ~same container - still not sure this is desirable as it essentially leaks the local env but not a prio in terms of CI
