### ISSUE TITLE
VPP/VCL is re/built on every CI run

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#26575]
This seems to be related to how bazel handles (genrule) outputs

When i run a build locally (with RBE) and then do `bazel clean` and do another build VPP/VCL is pretty clearly being rebuilt, yet bazel says that everything is cached and there are only "internal" actions

I believe that this could be resolved by using  `rules_foreign_cc` to build VPP/VCL but not 100% certain about this

either way, it would be good to address this asap as its causing a lot of unnecessary cycles for ci and devs

**Comment by phlax** [comment]
cc @florincoras @keith

**Comment by florincoras** [comment]
I'm pretty clueless when it comes to bazel but let's see if this can be solved. Ideally it'd be great not to have to move vcl build into `bazel/foreign_cc` since vcl is still only contrib. 

Having said that, I just pulled main latest and build for `//source/exe:envoy-static` and `//contrib/exe:envoy-static` fail to build on my ubuntu 20.04 box because of:

```
CMake Error at CMakeModules/AddZstdCompilationFlags.cmake:23 (CHECK_LINKER_FLAG):
  Unknown CMake command "CHECK_LINKER_FLAG".
```

My cmake version is:
```
$ cmake --version
cmake version 3.16.3
```

Do we need something newer now?

**Comment by phlax** [comment]
i thought we had a specific version, but on closer inspection we pull in the focal version from kitware, which is

```console
cmake version 3.26.1
```

**Comment by phlax** [comment]
@florincoras i have been playing around with the recipe here to see if i could figure out why its not caching properly

my changes didnt seem to help - i think the problem is the dependency on `@com_github_fdio_vpp_vcl//:all`

which bazel cant cache as an output because its basically glob everything

i think this may also be the cause of similar problems in other builds

**Comment by phlax** [comment]
if this is correct, then i think switching to `rules_foreign_cc` is likely to help as i belive it handles this

**Comment by florincoras** [comment]
I just tried a `bazel clean` after a `//contrib/exe:envoy-static` build and it looks like we're rebuilding some foreign_cc, e.g., event, colm, ragel and probably others (still rebuilding). In fact, the whole rebuild is taking a really long time, so I'm wondering now if I'm missing something. Note that I'm building on bare metal.

**Comment by phlax** [comment]
ive come to the conclusion that the problem is this code here:

https://github.com/envoyproxy/envoy/blob/614162755df9444289e15bdd8bad3518c856d89f/bazel/repositories.bzl#L19-L22

not 100% certain but it looks like that is not getting cached properly

re rebuilding - i use RBE so not sure building locally - but might be worth using `--disk_cache` flag - i think that would be preserved after bazel clean and is what we hope to be cached

**Comment by florincoras** [comment]
Thanks for the pointer, that did the trick. However here's my interesting finding after clean and rebuild:

```
Target //contrib/exe:envoy-static up-to-date:
  bazel-bin/contrib/exe/envoy-static
INFO: Elapsed time: 18.679s, Critical Path: 5.38s
INFO: 13732 processes: 8430 disk cache hit, 5299 internal, 2 linux-sandbox, 1 local.
```

In other words, although several components, including those built via foreign_cc (e.g., ragel, hyperscan, ipp_crypto) or those built via genrule (e.g., opentracing and vcl) do show up in logs as doing some work, the whole process takes less than 19s on my box. Previous build that set `--disk_cache` took more than 20 mins:

```
Target //contrib/exe:envoy-static up-to-date:
  bazel-bin/contrib/exe/envoy-static
INFO: Elapsed time: 1315.279s, Critical Path: 446.09s
INFO: 13732 processes: 5299 internal, 8431 linux-sandbox, 1 local, 1 worker.
INFO: Build completed successfully, 13732 total actions
```

**Comment by phlax** [comment]
@florincoras debugging this further and i think shifting to foreign_cc does not make any difference by itself

im still convinced the issue is with the globbing `:all` rule - which is used by most of the rules_foreign_cc targets also

either way all of the foreign cc builds are re-triggered after bazel clean afaict

**Comment by phlax** [comment]
@florincoras debugging this more carefully and its not rebuilding - its using the cache - the output is the cached output

huge apology for noise
