### ISSUE TITLE
Support selecting upstream TLS context to use based on downstream caller

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#2658]
*Title*: *Support selecting upstream TLS context to use based on downstream caller*

*Description*:
Background: 
I would like to deploy an envoy instance to every host in our infrastructure, to be shared by potentially many microservices deployed to the host. I would like envoy to be able to perform TLS on behalf of these microservices (as opposed to with envoy's identity). However this requires a mechanism to allow selecting the TLS context to use when making upstream connections based on which downstream microservice the connection is being made for.

This could be accomplished by adding a "default upstream tls context" either per-listener or per-http-connection manager. If the upstream cluster also has a TLS context configured, that one could take precedence. This would allow me to enforce access control on each listener, either by using a unix socket and file permissions or by configuring downstream TLS context.

Note: this deployment scheme is partly due to constraints in our networking where we can't allocate an IP address per microservice as Kubernetes does, for example. In that case I'd find it preferable to run an envoy per microservice as a sidecar, and I could probably use symlinks or consistent TLS file naming to have each envoy using different TLS credentials to connect to the same upstream cluster definition provided via CDS.

If there's a way to accomplish what I want without this feature I'm all ears for that as well, thanks in advance!

**Comment by mpuncel** [comment]
That would work, but that would likely mean greatly increasing the size of the cluster space, and I don't know if there are implications for that. I'd need a new cluster for every edge in the service dependency graph at a minimum with the naive solution making the cluster set go to N^2. If you have any insight to give on how performance relates to cluster size i'd be interested, for instance if there were 250k clusters (n^2 connections if there are 250 distinct microservices)

I do have a plan to work around this though by running an "ingress envoy" per-host solely for routing inbound traffic, and running a "egress envoy" as a sidecar in each microservice's pod. This way I can use symlinks to make the TLS configuration for each cluster the same in the management server, but i'll get the TLS identities I want. Once our infra can support an IP address per pod we can collapse this to only  have sidecar envoys.

**Comment by mattklein123** [comment]
Yes I can see how the cluster explosion would be problematic here. Unfortunately this would be a a very non-trivial feature to develop based on the split downstream/upstream architecture of Envoy. It would require a lot of thinking on how to do if we were to want to implement it. We can leave this open as a feature request if you like.
