### ISSUE TITLE
When SO_BINDTODEVICE is set in SocketOptions, the error "No such device" is reported.

### ISSUE THREAD

**Issue by zcz-1020** [envoyproxy/envoy#26581]
Recently, we have created an Envoy container using docker, The host network used by Docker. And we want to bind the listener to the specified network interface (eth0) by setting SO_BINDTODEVICE in SocketOptions. The configuration is as follows:
`   socket_options:  { description: "####test envoy###"，state: 0，level: 1，name: 25，buf_value: 'eth0' } 
`
However, an **_No such device_** error is reported. The error content is as follows:
`
[warning][connection] [source/common/network/socket_option_impl.cc:28] Setting 1/25 option on socket failed: No such device
[error][config] [source/server/listener_manager_impl.cc:1034] listener 'listener_0' failed to bind or apply socket options: ListenSocket: Setting socket options failed
`
The _ip addr_ does have this interface:
`
17: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
     .....
`

**Comment by MarcusWichelmann** [comment]
Hi,

we're having exactly the same issue. Did you find a solution for this, or why have you closed this?

**Comment by MarcusWichelmann** [comment]
Okay, we found the solution.

For the record: The string passed to buf_value must be base64 encoded:
```
printf 'vrf-name\0' | base64
```
