### ISSUE TITLE
Generate Compilation database failed on M2 Mac

### ISSUE THREAD

**Issue by escoffier** [envoyproxy/envoy#26595]
*Title*: *Generate Compilation database failed on M2 Mac*

*Description*:
> Open repo with vscode devcontainers, run commmand:
`./tools/vscode/refresh_compdb.sh`, but errors occured:
`ERROR: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: in cc_toolchain_suite rule @envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain: cc_toolchain_suite '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' does not contain a toolchain for cpu 'aarch64'`
it seems that toolchains not support arm64?

**Comment by keith** [comment]
dup of https://github.com/envoyproxy/envoy/issues/23239
