### ISSUE TITLE
Is it possible to make a local rate limit with some header of HTTP request

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#26596]
I'm using Envoy as the gateway of my backend.

The HTTP requests to my backend contain a key-value user info in their headers, for example, the header of some request could contain `x-uesrid: 123`.

What I'm trying to do is to limit the rate of all of http requests with the help of `x-userid`: each user can send 10 times requests in 1 minute.

Does Envoy support this? Could you please show me an example?

**Comment by pxpnetworks** [comment]
Hi, 

Have a look at [https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter](composite_filter)

BR,
Stoyan
