### ISSUE TITLE
Support missing for Starttls socket as inner socket in UpstreamProxyProtocolSocket

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#26592]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Support missing for Starttls socket as inner socket in UpstreamProxyProtocolSocket*

*Description*:
> When starttls socket is configured as inner socket in UpstreamProxyProtocolSocket for the cluster, we are unable to switch to TLS when we call startSecureTransport().

*Repro steps*:
> Below is the config used for cluster transport socket, when an L7 filter (e.g SMTP) invokes startSecureTransport() on UpstreamProxyProtocolSocket as a result of STARTTLS command, the api returns false due to missing implementation.
`transport_socket:
      name: envoy.transport_sockets.upstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config:
          version: V2
        transport_socket:
          name: envoy.transport_sockets.starttls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.UpstreamStartTlsConfig
            tls_socket_config:
              common_tls_context: {}`
>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by mattklein123** [comment]
cc @cpakulski
