### ISSUE TITLE
Add ability to use non-local source IP for outgoing connections.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#2659]
This would allow Envoy to make outgoing connections (at least locally) with the IP of the original client instead of the proxy, in a protocol-agnostic way that's transparent to the upstream.

This should be as easy as adding support for `IP_TRANSPARENT` and `IPV6_TRANSPARENT` socket options.

**Comment by PiotrSikora** [comment]
cc @alyssawilk @costinm @ldemailly @jrajahalme (in case you're working on upstream version of `socketOptions()`).

**Comment by cmluciano** [comment]
@PiotrSikora Are you currently working on this/know anyone that is?

**Comment by ldemailly** [comment]
for outgoing connection isn’t the sourceip the same (the pod’s ip) - or do you mean port ?

**Comment by rlenglet** [comment]
> for outgoing connection isn’t the sourceip the same (the pod’s ip) - or do you mean port ?

I think “outgoing” here means “upstream.”

**Comment by PiotrSikora** [comment]
@cmluciano I'm not and I don't.

@ldemailly it can be for the sidecar (but it doesn't have to if there are multiple IPs on the same machine), it's not for the proxy (in general).

**Comment by dnoe** [comment]
I think this issue might actually be fixed, since we now provide the ability to set arbitrary socket options in the API. We do in fact use this feature at Google to use a non-local source IP for outgoing connections.

@hzxuzhonghu Can you explain your use case in more detail?

**Comment by hzxuzhonghu** [comment]
@dnoe Thanks. I just want to get client src ip in my backend. Can you link how to `set arbitrary socket options in the API. `

**Comment by dnoe** [comment]
There is a field in the bootstrap config that specifies the bind config when connecting to upstreams (it can also be overridden on a per-cluster basis): See `upstream_bind_config` in https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/bootstrap/v2/bootstrap.proto#envoy-api-msg-config-bootstrap-v2-bootstrap

The bind config has a `SocketOptions` message which allows setting arbitrary options: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-socketoption

You can do this for the upstream_bind_config, and also for listeners. Both ultimately use the `SocketOptions` message.

**Comment by hzxuzhonghu** [comment]
Thanks @dnoe

**Comment by hzxuzhonghu** [comment]
@dnoe Do you know how to configure it from istio?

**Comment by dnoe** [comment]
`level = 0` doesn't look right. You probably want the value corresponding to `IPPROTO_TCP`, right?

**Comment by hzxuzhonghu** [comment]
```
0    SOL_IP

6   IPPROTO_TCP
```

I have tried both, but all failed.

**Comment by dnoe** [comment]
Without knowing more about the particular custom option you are trying to set it's hard to be sure. But the error returned from setsockopt system call was "Protocol not available".

**Comment by cmluciano** [comment]
related #5525 #5337

**Comment by chenjiaxi1993** [comment]
> @dnoe Thanks. I just want to get client src ip in my backend. Can you link how to `set arbitrary socket options in the API. `

Have you finally solve this problem to get client source IP address in your backend instead of `127.0.0.1` by using Envoy itself or by Istio?
Thx.

**Comment by hzxuzhonghu** [comment]
No, so i haven't yet used this feature.
