### ISSUE TITLE
Add ability to deliver initial static set of endpoints in CDS update when using EDS

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#2662]
This would prevent Envoy from sending `503 Service Unavailable` responses, in the time between CDS and EDS updates, when Envoy didn't learn about available endpoints yet.

It could be implemented without changing existing API, in a backward-compatible way, by sending CDS update with `type = EDS` and non-empty list of `hosts`.

The question is whether provided list of `hosts` should be used only until first EDS update arrives, or also as a fallback.

cc @louiscryan @jmarantz @htuch @andraxylia @costinm

**Comment by PiotrSikora** [comment]
https://github.com/envoyproxy/envoy/issues/1930 is a different solution of the same problem.

**Comment by jsedgwick** [comment]
What's preferable about this approach compared to the cluster warmup approach in #1930?

It seems that all you get here over cluster warmup is an small decrease in availability lag time for what is a previously nonexistent cluster. The cost is an API hack and whatever headaches come along with determining hosts to provide from your CDS implementation.

Meanwhile, if you really need the immediate consistency, you can always implement ADS and provide CDS/EDS results simultaneously right off the bat.

Your proposed mechanism seems ok for an optional fallback, but I think it shouldn't be the primary solution over cluster warmup. I don't know what the current story around EDS fallback is, though.

**Comment by htuch** [comment]
The context here is Istio 0.7, where they don't have ADS (or v2) yet.

@jsedgwick  If no EDS arrives today, you just have a dead cluster. If you have an EDS response and then the EDS server dies, we just latch the last response forever. I can see a potential use case for this solution to provide a way to fall back on some known endpoints (e.g. like a hospital service for bad requests) when EDS goes away. But, I haven't ever heard someone ask for this, so this issue is a good place to solicit this feedback.

My take is that I think CDS warming is the preferable solution, but if there is community interest in the above behavior for other reasons (e.g. low latency serving from new clusters), then it's worth adding.

**Comment by PiotrSikora** [comment]
@jsedgwick it's not strictly preferable, I think we should have both. Also, ADS doesn't really solve this problem, it just significantly shortens the time between CDS and EDS updates, but it's still non-zero.

The biggest advantage of this solution is that in case EDS is down (e.g. when CDS and EDS are separate services, or when Envoy is using static clusters with EDS), then you can still serve traffic (maybe with sub-optimal load assignments), instead of returning 503s.

Also, as @htuch mentioned, we need to fix 503s in Istio sooner rather than later, and the cost of implementing this solution is quite smaller than cluster warming.

**Comment by mattklein123** [comment]
@PiotrSikora I'm not thrilled about adding this feature when CDS cluster warming IMO is the real solution to this problem and fits really well with how we do LDS, etc. When is a solution needed by? What date do we need to deliver CDS warming before this becomes a real blocker?

**Comment by andraxylia** [comment]
In Istio we could use it by mid-March, when the next release 0.7 is planned.

**Comment by mattklein123** [comment]
@PiotrSikora @andraxylia I would prefer to implement CDS cluster warming. IMO this is a much better solution that a) fits well with how we do LDS and b) also will work for other cluster types including DNS. If I can do warming by mid-march is that sufficient?

**Comment by andraxylia** [comment]
@mattklein123 Mid-march would be great, thank you!

**Comment by mattklein123** [comment]
I'm going to go ahead and close this. I looked at CDS warming and it's not that difficult. I will do it in the next 2 weeks. If I don't deliver we can reopen and reconsider.
