### ISSUE TITLE
Labeling of access logs

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#26639]
With the addition of periodic access logs and start of connection/request access logs, it is now not possible to distinguish between these logs from the log data itself. The proposed enhancement is adding a substitution string ``%ACCESS_LOG_TYPE%`` which can be used in the log format, and it will have a value that uniquely identifies the occurrence of the access log.

For example, periodic HCM access logs, will have ``hcm_periodic`` value, start of connection in TCP Proxy access logs will have ``tcp_connection_start``, etc.. I think it would make sense to defer the decision on the values themselves to the PR itself, so it's easier to discuss the namings.

Implementation-wise, I suggest to add another parameter to  ``log()``
https://github.com/envoyproxy/envoy/blob/674d9a0f4951d4bb0800a18e813612de5361c1cf/envoy/access_log/access_log.h#L92

And to ``format()``
https://github.com/envoyproxy/envoy/blob/674d9a0f4951d4bb0800a18e813612de5361c1cf/envoy/formatter/substitution_formatter.h#L31

Possibly to ``evaluate()`` too, if a relevant filter will be implemented.
https://github.com/envoyproxy/envoy/blob/674d9a0f4951d4bb0800a18e813612de5361c1cf/envoy/access_log/access_log.h#L69

The addition to each one will be an enum value of the various access log types.

While adding ``AccessLogType`` to ``log()`` and ``evaluate()`` in access_log.h is trivial, I wasn't sure if adding this parameter to ``format()`` 100% makes sense, as I saw the substitution formatter being used in contexts not relevant for access log (unless I have misunderstood), such as router's header_formatter. So, I'm not sure if direct reference to access_log from substitution_formatter is valid. One option is adding ``absl::string_view`` parameter instead, which would be the string representation of the enum value, after being converted at ``log()``, but still this adds conceptual context to ``AccessLogType`` by naming, even though not a compile time reference. Is there a way to overcome this?

cc @alyssawilk, @paul-r-gall, @kyessenov

**Comment by kyessenov** [comment]
I think OpenTelemetry convention is to call them `event.name` attributes, per https://opentelemetry.io/docs/reference/specification/logs/semantic_conventions/events/.

**Comment by ohadvano** [comment]
> I think OpenTelemetry convention is to call them `event.name` attributes, per https://opentelemetry.io/docs/reference/specification/logs/semantic_conventions/events/.

Are you referring to the access log type? If so, then I guess that's in the user's hand when constructing their log format, i.e which keys and values to use, and the key can be named ``event.name``

**Comment by ohadvano** [comment]
@alyssawilk I see you have thumbed up the upper comment, however I'm still not sure about the issue I mentioned above - as far as you're concerned, is it legit to add a ``string_view access_log_type`` or ``AccessLogType access_log_type`` parameter to ``format()``  although the ``substitution_formatter`` is somewhat decoupled from access logs?

**Comment by kyessenov** [comment]
IMHO that would be fine, there's already `local_reply_body` that is set to empty in other contexts.

**Comment by alyssawilk** [comment]
I thought @paul-r-gall had suggested adding AccessLogType to the log() function.  Would we need it there and format?

**Comment by ohadvano** [comment]
As I see it, the ``format()`` function would require this info to resolve ``%ACCESS_LOG_TYPE%``. Have I misunderstood @paul-r-gall?

**Comment by paul-r-gall** [comment]
I would expect the use case here would be to do a post-hoc filter of access logs that have been written by the access logger that writes to files (can't remember what it's called).

**Comment by cpakulski** [comment]
Adding an extra param to the list of parameters is definitely one option. But, if in the future there is a need for another formatter which needs information to be fed in the similar way, yet another function parameter would have to be added. 
What if instead of passing a specific access log type you would pass a set or hash table with log attributes. One of the attributes would be LOG_TYPE. And a formatter would be called LOG_ATTR(X), where X would be the name of the attribute to be displayed. So, it would be LOG_ATTR(LOG_TYPE) in your case. The formatter's implementation would look in the passed hash table for "LOG_TYPE" entry and display it. 
Sure, you still need to add extra param, but if there is a need in the future for yet another static string info to be displayed, the change would require modifications in very small number of places.

**Comment by ohadvano** [comment]
Thanks for the suggestion @cpakulski, as per the user experience, I don't see what value ``LOG_ATTR()`` adds over directly referencing the required value, as LOG_ATTR is an implementation detail and not an actual object that the stream maintains, rather than an extra context passed with the log() call itself. Per the implementation, your suggestion makes sense, and would make it easier to extend, although I'm not sure how frequent it would really be required to add more parameters to log() call (the function signature actually didn't change for a long time, seems like many years). It seems like ``LOG_TYPE`` is really a special case where you need to know the location where this log is being recorded from, so in the current state you can't get this from any other parameter, and it seems to me that ideally all the access log info should come from the stream info, headers, etc...

With that said, even though I don't generally rule out the bag of properties idea, I have already put out a PR which I have worked on quite some time, and currently I don't have the cycles to refactor the whole thing. As far as I'm concerned, you can either take over the PR and modify it per your suggestion, or we can refactor this in the future if it would really require adding more parameters (since it's an implementation detail and doesn't change the API or behavior, I don't see why it couldn't be done). Thanks again for looking at this

**Comment by cpakulski** [comment]
I think you are right, that there is a slim chance that a new parameter will be added to the function signature. If you do not mind, please add a comment to consider passing a set/hash of static values instead of individual params, if there is such need in the future.
