### ISSUE TITLE
CROSSTOOL failed to parse

### ISSUE THREAD

**Issue by vbatts** [envoyproxy/envoy#2665]
```shell
bazel --bazelrc=/dev/null build --verbose_failures -c opt //source/exe:envoy-static.stripped.stamped
........
ERROR: java.io.IOException: Could not read the crosstool configuration file 'CROSSTOOL file /root/.cache/bazel/_bazel_root/2cb205078a56d4bfe49d5a502ea39ff3/external/local_config_cc/CROSSTOOL', because of a parser error (249:1: Expected identifier. Found '%')
INFO: Elapsed time: 0.878s
FAILED: Build did NOT complete successfully (5 packages loaded)
```

[optional *Relevant Links*:]
Failed build log https://copr-be.cloud.fedoraproject.org/results/vbatts/envoy/fedora-27-x86_64/00719821-envoy/builder-live.log
CROSSTOOL file contents https://pastebin.com/JvSWH3ut 
related issue on bazel https://github.com/bazelbuild/bazel/issues/4645

Reproduce Steps:
* Start a fedora host or container (f26, f27 or rawhide)
* `git clone https://github.com/vbatts/copr-build-envoy && cd copr-build-envoy`
* `sudo make rebuild`

**Comment by vbatts** [comment]
good on @htuch 
This build was on commit 6d62998a7558dec34e709189b48acc57de7d57d3, not latest HEAD. 
Trying again, but with commit 6d62998a7558dec34e709189b48acc57de7d57d3

**Comment by vbatts** [comment]
that worked!

**Comment by clnperez** [comment]
@vbatts Was that the commit that fixed it (i.e. could I cherry-pick it in)? or just one where it worked? :D

**Comment by vbatts** [comment]
@clnperez sorry, my comment was not clear.
I was trying to build an older commit of envoy with latest bazel at the time (v1.10.1) .That is why got a parse error.

Once I pulled the latest HEAD of envoy, then the build was successful. 

It's less than ideal, but the envoy codebase  is fairly lock-step with bazel releases.

**Comment by clnperez** [comment]
@vbatts that's what i was trying to do as well. i ended up cherry-picking in 95ee420c379942fd692b42c84a1fd5ef4d7035ec and i could do what i wanted :)
