### ISSUE TITLE
SSL performance

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2667]
We've been conducting some Envoy load tests. On a single worker Envoy in an experimental setup and 0-byte gRPC requests at max load, we see a reduction in performance of 33% when comparing non-SSL and SSL cases. With 1MB requests, the performance reduction is 62%.

Unfortunately, the flamegraphs we have were created with internal binaries and I can't directly share them. Some observations though are:
* There is a significant increase in `libc_write` time, proportionally, on 0-byte requests when switch to SSL. This seems to suggest possible buffer fragmentation or loss of scatter-gather efficiency when working with BoringSSL.
* Over 50% of time is spent in SSL operations with 1MB requests. For bandwidth heavy streams, crypto offload or BoringSSL optimizations might be useful.

@PiotrSikora is investigating, we can track progress here.

**Comment by lizan** [comment]
cc @ldemailly
