### ISSUE TITLE
Distributed tracing should use custom inline header retrieval for HTTP

### ISSUE THREAD

**Issue by brianwolfe** [envoyproxy/envoy#26687]
*Title*: *Distributed tracing headers should use constant-time inline header retrieval*

*Description*:
Custom header handles make header retrieval predictably fast for generic HTTP filters. Tracers attempt to abstract away the [TraceContext](https://github.com/envoyproxy/envoy/blob/main/envoy/tracing/trace_context.h) from the underlying [RequestHeaderMap](https://github.com/envoyproxy/envoy/blob/main/envoy/http/header_map.h#L712-L715). This means that they always retrieve headers by key. This abstraction makes it difficult to use the constant-time handles for HTTP header retrieval.

This creates a non-trivial lookup cost for HTTP headers. We can pre-register the headers to avoid creating the HeaderMap on the hot path, but we still have to traverse the Trie on every header modification. This is not nearly as fast as the constant-time lookup we can do in other HTTP Filters.

I have been staring at this for a few days to figure out a simple way to pierce through the abstraction of TraceContext without muddying things too much further. Everything I can think of would pretty tightly couple RequestHeaderMap & TraceContext.

Does anyone else have any ideas (or previous issues/docs) for how we could improve TraceContext/RequestHeaderMap API so that the distributed tracing headers can have constant-time lookups?

**Comment by mattklein123** [comment]
Yeah it would be nice to do this I agree. I don't have any quick ideas. cc @wbpcode

**Comment by wbpcode** [comment]
Sorry for the delay. I missed this issue untill the stale robot post a new event.

This is a helpless compromise for multiple protocols tracing support.

A possible way is make the HTTP a special case and handle it in custom code patch.
It is acceptable for me, especially considering the special status of HTTP.

**Comment by wbpcode** [comment]
I still cannot future out a perfect way to resolve this problem. As you said in the issue description, all possible ways will bind the TraceContext and RequestHeaderMap tightly.

RequestHeaderMap is powerful and be heavily optimized. It's also too complex for simple tracing or non-HTTP modules. The only reason for me to create the `TraceContext` is to simplify re-using of tracers.

So, take a step back, considering the special position of HTTP, I think a hack for HTTP is acceptable. For example, we can add a specific method to the TraceContext to return a optional reference of RequestHeaderMap. It could have a default empty implementation then non-HTTP modules could ignore it completely.

After that, only one or two if checks are necessary if I we want to take the power of custom inline heder.
And we can add some helper class to handle the additional check for all tracers at some position.

(Dynamic casting also a possible way and the interface will be more clean. But the code won't simpler and it needs more runtime overheads.)

**Comment by wbpcode** [comment]
This should be addressed by the #31141. Now, we can mark a trace header as inline header in the bootstrap file and then the inline semantics will be used to accelerate the searching/rewriting.
