### ISSUE TITLE
What is a proper way to make a HTTP or grpc request to some server after receiving a HTTP request from client

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#26692]
I used Envoy as the gateway of my backend. Each request of clients contains a token, which represents a user. So at the backend side, we need to extract the token and validate it. If it's an illegal token, reply an error to the client directly.

I'm thinking if I can do this in Envoy. Let's say that we put the token of client into the header of request. So what Envoy should do is to extract the token from the header of request and send it to a server, which can validate the token, and then Envoy should wait for the response. If the response says the token is valid, Envoy should route the request to upstream clusters. Otherwise, Envoy should reply the client directly with some error info.

For this case, I think the simplest way is to use `extensions.filters.http.lua.V3.Lua`. Meaning that I can do this with a piece of Lua code inside of the config of Envoy. However, I don't know if this is a proper way. As my understanding, Lua is simply a kind of script and there are about 80 thousands clients in my web server for now. I'm worrying about the performance of Lua inside of Envoy...

So is there some better solution to do so? Should I develop a custom http filter and compile my own Envoy?

**Comment by mattklein123** [comment]
I don't think you need to write any custom filter for this. You could do this with one of: lua, ext-authz, ext-proc. I would take a look at those.

**Comment by MinusRF** [comment]
Shouldn't that be handled by upstream server itself, rather than envoy? If you want to respond to client in-certain way upon getting illegal token that you can do using response flag filter. One more way could be Lua, I am using Lua for processing  headers and body of request at a scale similar to yours, didn't see any performance issue.

**Comment by YvesZHI** [comment]
@MinusRF  Thanks. Since Envoy is responsible for RBAC, I'm thinking it might be good to validate tokens of clients in Envoy. So I would try Lua or ext-authz.
