### ISSUE TITLE
golang filter with Apple m1 error

### ISSUE THREAD

**Issue by davidebianchi** [envoyproxy/envoy#26694]
*Title*: *golang filter with Apple m1 error*

*Description*:
When I run the golang filter with my Apple m1, it abort with the following error:

```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
dyld[67105]: symbol not found in flat namespace '_envoyGoFilterHttpContinue'
```

*Repro steps*:
To repro the issue, it's needed an Apple m1.

An example repro code is:

```go
func init() {
	http.RegisterHttpFilterConfigFactory(PluginName, nil)
}
```

**Comment by doujiang24** [comment]
Oh, sorry, I don't have an Apple m1 in hand, will take a look when I have one, may take a few days.

**Comment by mattklein123** [comment]
cc @keith

**Comment by keith** [comment]
@davidebianchi what's in the BUILD file of your repro case? You likely need to explicitly have this target https://github.com/envoyproxy/envoy/blob/0dbb3dcb335fc08ecf5544840602c9e2465f6d0b/contrib/golang/filters/http/source/BUILD#L58-L79 in your `deps` (or maybe the other one in that file). In the future this will be a linker failure for a missing symbol instead of a runtime failure

**Comment by davidebianchi** [comment]
I don't have a BUILD file, I try to use the library to create a filter and I run it with `go run .` (but also with test or build it's the same). It is needed to have a BUILD file on m1?
I try to execute the same on osx not arm, and it works as expected.

**Comment by doujiang24** [comment]
oh, I think it might be expected usage, you should use `go build` to build a so file, like this example:
https://github.com/envoyproxy/envoy/blob/main/examples/golang/docker-compose-go.yaml#L10

and the so file should only work with the envoy binary.

**Comment by davidebianchi** [comment]
Oh sorry, I miss the comment.

Yes the shared object build works, I misdescribed the issue above. The problem is running tests of the plugin which fails with the above error. I suppose it's an issue with the architecture, since using another mac intel the tests run correctly, but maybe I'm wrong.

So, for example a code like this:

```go
package foo

import "github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http"

func init() {
	a()
	http.RegisterHttpFilterConfigFactory("a", nil)
}

func a() string {
	return "ok"
}
```

with a test like this:

```go
package foo

import (
	"testing"
)

func TestConfigFactory(t *testing.T) {
	a()
}
```

will result with

```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
dyld[8735]: symbol not found in flat namespace '_envoyGoFilterHttpContinue'
FAIL    foo     0.108s
```

I simplify the repro and I should test in another architecture, but with my more complex plugin I cannot run the test.

Instead, if I run `go build -o simple.so -buildmode=c-shared .`, the build works but with the warning

```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```

**Comment by doujiang24** [comment]
Hi @davidebianchi , you got that error when using `go test`, without using the envoy binary, right?

that's some kind of reasonable, since the go module requires C functions that exported from Envoy.
```
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http
```

for it works in mac intel, it might be some different behaviour in the go compiler, might be dead code optimization area? I'm not sure about it.
since we don't use really those C functions, in your example, so those related code might be removed by dead code optimization? just a guess.

**Comment by doujiang24** [comment]
> How it could be possible to test the plugin in my use case, do you have any idea

this is how we test the golang filter:
https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/golang_integration_test.cc#L228
but, it might be too heavy to you, it need you to write the test cases in C++.
this is the envoy project test framework.

another option, you could try e2e test, this is how we test the ldap-auth plugin:
https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/golang_integration_test.cc#L228

**Comment by davidebianchi** [comment]
The second link it's the same of the first, I think the correct one is https://github.com/mosn/envoy-go-ldap-auth. I'll try this method, thank you for the support!
