### ISSUE TITLE
Allow max header size configurable via runtime config

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#26690]
Couple of points 

- Would it be OK to make the default value read from a runtime config instead of hardcoding it to 60Kib?
- If we introduce a runtime config - Can the default of the runtime config be changed to a higher value? What would be the considerations (security , memory etc) for choosing that default in Envoy?

Refer https://github.com/envoyproxy/envoy/pull/5859 for more context

**Comment by alyssawilk** [comment]
ooc why configure via runtime rather than use codec config?  It's a bit dangerous to configure config defaults via runtime because then there's a constraint that the runtime config loads before any other configuration that uses that field, or you get unexpected behavioral changes

**Comment by ramaraochavali** [comment]
>ooc why configure via runtime rather than use codec config? It's a bit dangerous to configure config defaults via runtime because then there's a constraint that the runtime config loads before any other configuration that uses that field, or you get unexpected behavioral changes

Got it. The only reason I was thinking of runtime is honestly to see if we can increase the default value of it in Envoy safely without BC issues.  See my second point

**Comment by alyssawilk** [comment]
I think we're past the point we can shift defaults in Envoy, at least not without a super compelling reason.

**Comment by RyanTheOptimist** [comment]
cc: @RyanTheOptimist @yanavlasov @KBaichoo (from https://github.com/envoyproxy/envoy/pull/5859)

**Comment by ramaraochavali** [comment]
> I think we're past the point we can shift defaults in Envoy, at least not without a super compelling reason.

I get that. That is the reason to propose a new runtime config that dictates the default. If that has ordering issues - I think we can close this.

**Comment by KBaichoo** [comment]
> The only reason I was thinking of runtime is honestly to see if we can increase the default value of it in Envoy safely without BC issues.
What is "BC" issues?

I think this is doable given it's already done for max_request_headers_count. See https://github.com/envoyproxy/envoy/blob/353a9a59a7ed8a30433cbab256c3f4c0c23c72cd/source/extensions/filters/network/http_connection_manager/config.cc#L327.

Priority would be:
1. What is explicit config
2. What is runtime provided
3. The current legacy default

It seems more work to be than just configuring the value explicitly, but I don't understand your use case fully for why that's not an option.

**Comment by ramaraochavali** [comment]
> It seems more work to be than just configuring the value explicitly, but I don't understand your use case fully for why that's not an option.

It is definitely an option. Currently Istio does not have API support to set this flag. So I am wondering if we can have a runtime flag(for which Istio has API support) to set it across all sidecars in a mesh deployment. The only other option is to define a custom config (via Envoy filter in Istio).

**Comment by ramaraochavali** [comment]
If there are no objections, exposing this, I can implement it

**Comment by ramaraochavali** [comment]
This is fixed by https://github.com/envoyproxy/envoy/pull/26874
