### ISSUE TITLE
Add Attributes connection.transport_failure_reason

### ISSUE THREAD

**Issue by XinyiZhangAws** [envoyproxy/envoy#26710]
*Title*: *Add Attributes connection.transport_failure_reason along with TLS connection errors*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.
Purposed Attributes
`connection.transport_failure_reason`:
Currently upstream.transport_failure_reason is included in the attributes to indicate the upstream transport failure such as certificate validation failed. But there's no similar ones for downstream connection. Considering [recent PR](https://github.com/envoyproxy/envoy/pull/25322/files) added downstream transport failure reason to access log, it can be added to attributes as well for consistency.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.html#attributes
https://github.com/envoyproxy/envoy/pull/25322/files

**Comment by mattklein123** [comment]
cc @kyessenov

**Comment by ytsssun** [comment]
@mattklein123 could you add a "help wanted" tag to revive this issue?
