### ISSUE TITLE
Clarification about outlier detection and ejection of 100% hosts

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#2671]
**Issue Template**

*Title*: It is not specified in the documentation of the outlier detection what happens when 100% of the hosts are ejected.

*Description*:
Suppose I have `max_ejection_percent` set to 100, and the only host I have returns always 501 (I used httpbin.org/status/501). I have "consecutive_5xx": 5. After sending 100 consecutive requests, I get back all the 100 requests with 501.

The stats show:
```
cluster.httpbin.outlier_detection.ejections_active: 2
cluster.httpbin.outlier_detection.ejections_consecutive_5xx: 8
cluster.httpbin.outlier_detection.ejections_overflow: 0
cluster.httpbin.outlier_detection.ejections_success_rate: 0
cluster.httpbin.outlier_detection.ejections_total: 8
```

The ejections seems to happen, however I do not see anything in the requests behavior - all of them return 501, as without envoy. So the question - what should I expect after the only host is ejected?

The config is attached.

[envoy_config.json.txt](https://github.com/envoyproxy/envoy/files/1754125/envoy_config.json.txt)

**Comment by mattklein123** [comment]
Please see https://www.envoyproxy.io/docs/envoy/latest/faq/lb_panic_threshold which is the likely explanation.

**Comment by vadimeisenbergibm** [comment]
@mattklein123 I see, thanks, now it is clear.
