### ISSUE TITLE
Index out of bounds issue inside proxy protocol parser

### ISSUE THREAD

**Issue by d0znpp** [envoyproxy/envoy#2672]
https://github.com/envoyproxy/envoy/blob/6f910198c37a25c1932e88102915e2e2b1d81ea6/source/common/filter/listener/proxy_protocol.cc#L122-L135

It's possible to cause index out of bounds error when the ```search_index_``` is 0 and the condition ```buf_[search_index_] == '\n'``` is true.

In this case the second condition check ```buf_[search_index_ - 1] == '\r'``` will cause an error because ```search_index_ - 1``` will be equal to -1 and will refer to unexisted index. 

Some more  details about this type of bug: https://cwe.mitre.org/data/definitions/127.html

**Comment by d0znpp** [comment]
Yep. This is good

**Comment by mattklein123** [comment]
OK thanks for confirming. Closing.
