### ISSUE TITLE
add more streaminfo related api for Go extension

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#26722]
*Title*: *add more streaminfo related api for Go extension*

*Description*:
i think some useful data like `downstreamLocalAddress`, `upstreamHost` and so on in Lua extension should be also included in Go extension.

**Comment by StarryVae** [comment]
cc @doujiang24 WDYT? if this is reasonable, can i try to submit a PR, thanks.

**Comment by StarryVae** [comment]
yeah, thanks.

**Comment by StarryVae** [comment]
```
type StreamInfo interface {
	GetRouteName() string
	FilterChainName() string
	// Protocol return the request's protocol.
	Protocol() (string, bool)
	// ResponseCode return the response code.
	ResponseCode() (uint32, bool)
	// ResponseCodeDetails return the response code details.
	ResponseCodeDetails() (string, bool)
	// AttemptCount return the number of times the request was attempted upstream.
	AttemptCount() uint32
	// DownstreamLocalAddress return the downstream local address.
	DownstreamLocalAddress() (string bool)
}
```

here is the interface for `DownstreamLocalAddress`, PTAL, thanks @doujiang24

**Comment by doujiang24** [comment]
It's fine to me for the single API, but we'd better propose a more complete design, so that we can consider them in a consistent way.

yep, it's not an easy work. we only expose a few APIs now, since they are simple.

One thing I was thinking about is, do we need to align the API style like the C++ does?
My answer is, we do not need to keep strict align with the C++ APIs, but it's better to be similar to them, if possible.

**Comment by doujiang24** [comment]
> Do you mean we should propose a more complete design for all streaminfo related api?

yes.

> And the StreamInfo interface now is not similar to C++ APIs?

nope, the current implementation is very similar to C++ APIs.

> And what I want to do is to add more useful APIs to Go extension to make it more feature-rich, since I'm familiar with lua and wasm-related apis before, thanks.

Okay, I think the Go APIs similar to Lua APIs is a proper choice too.

**Comment by StarryVae** [comment]
thanks, so can i complete the `DownstreamLocalAddress` first?

**Comment by doujiang24** [comment]
sure, welcome.

**Comment by StarryVae** [comment]
Hi @doujiang24 , i think `getCurrentTimeMilliseconds` api both in `Lua` and `WASM` may be also useful to `Go` extension, WDYT? And if we add `getCurrentTimeMilliseconds`, it may not an api in `StreamInfo`, but a general api which should be in `FilterCallbacks`?

**Comment by doujiang24** [comment]
I'm not sure it's a proper API. Usually people can get time by `time` package in Go code easily.

**Comment by StarryVae** [comment]
> I'm not sure it's a proper API. Usually people can get time by `time` package in Go code easily.

yeah, thanks.

**Comment by StarryVae** [comment]
https://github.com/envoyproxy/envoy/blob/b896b6dfc266e6a16f7106da2f17f437db1d7f5c/contrib/golang/filters/http/source/go/pkg/http/type.go#L216

Hi, it seems that Trailer related APIs are not all done yet, could i try to pick it up? @doujiang24

**Comment by doujiang24** [comment]
@StarryVae sure, thanks and welcome!
