### ISSUE TITLE
Support separated custom tags for downstream and upstream spans

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#26731]
*Title*: Support separated custom tags for downstream and upstream spans

*Description*:

Now the tracing config is shared for both downstream and upstream spans. So all custom tags will be the same for downstream/upstream spans(SERVER/CLIENT spans in opentracing). This is not convenient in some cases, especially as a Gateway, like:
* Adding custom tags to only upstream spans. But downstream spans will also have the tags. For example the cluster's name.
* Adding custom tags with the same key but different values to both downstream/upstream spans. For example, `my.path` for downstream spans is the downstream HTTP path, but is the route pattern for upstream spans.

For the implementation, I have some simple ideas:
1. Adding a new `upstream_custom_tags` field to [Tracing](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#config-route-v3-tracing) be able to override the whole custom_tags for upstream span.
2. Adding a field `scope`, which can be an enum including `downstream` or `upstream` to specify where the custom tags should be applied.

If this is a reasonable feature request, we can discuss more about the API and implementation. Like I'm wondering if my two solutions are too tight coupling with the upstream/downstream concept given we may have more span types than downstream/upstream spans in theory, then we may need more general solutions.

Any idea?

*The above `downstream`/`upstream` in some places can be replaced with `ingress`/`egress`*

**Comment by mattklein123** [comment]
Sure sounds reasonable if you want to propose something concrete.
