### ISSUE TITLE
Does envoy get the Public IP or Private IP of the client in the x-forwarded-for header ?

### ISSUE THREAD

**Issue by halemanipooja** [envoyproxy/envoy#26756]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: want to understand if envoy get private IP of the client (downstream application) by default

*Description*:
we have a set up where there is a downstream application (client) sending a request to upstream application via envoy and we want to capture the public IP of the client. in the envoy x-forwarded-for header we are seeing only private ip. Our requirement is to get public IP. Is this possible ? or does envoy by default reads private IP ?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
How Envoy handles XFF is for better or worse extremely complicated. Start by reading this: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for.

If Envoy is sitting behind additional proxy hops, you may have to configure other things to make this work as as proxy proto, etc.
