### ISSUE TITLE
Can envoy access log include listener name field

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#26752]
I can not find the listener name field in the access log. 
I think listener name is  important field that can help us troubleshooting case that the incoming packet hit the wrong listener.
For example, there are listeners 0.0.0.0:8443 and 1.1.1.1:8443. 
Now the packet whose destination is 1.1.1.1:8443. We want the packet to hit the 1.1.1.1:8443. Unfortunately, it hit 0.0.0.0.:8443.
If the access log can include the listener name, we can quickly find the issue.

**Comment by zhangbo1882** [comment]
@mattklein123 ,  if you think it is reasonable, I will make the PR.

**Comment by kyessenov** [comment]
Agree it's useful, we added the filter chain name, and the listener name is the next thing missing.

**Comment by zhangbo1882** [comment]
@kyessenov which PR added the filter chain name?

**Comment by kyessenov** [comment]
See f9c9c04faf9
