### ISSUE TITLE
OAuth2 filter: optional HMAC validation

### ISSUE THREAD

**Issue by tomakita** [envoyproxy/envoy#26766]
*Title*: OAuth2 filter: optional HMAC validation

*Description*:

In some cases, when using the OAuth2 filter, it's useful to be able to modify the OAuth ID token immediately after it's returned from the identity provider, and before it's sent to the browser.  For example, if the IdP sends an ID token that is too large to fit in a cookie, we can make it smaller by removing unneeded data from it (e.g. groups that we don't care about for our application).  This is possible with a custom Envoy Lua filter, but it causes HMAC validation to fail within the OAuth filter.

Therefore, it would be nice if HMAC validation were optional -- it would be up to the user to implement their own HMAC validation that happens separately from the OAuth2 filter.  This shouldn't be the default behavior of the filter, but it would be nice if it could be configured that way.

I'm willing to submit a PR for this feature, but I wanted to see if you think it's a good/bad idea first.

Thanks!

**Comment by htuch** [comment]
@snowp
