### ISSUE TITLE
Is LDS handled after CDS/EDS

### ISSUE THREAD

**Issue by 123liuziming** [envoyproxy/envoy#26775]
I know that EDS is handled after CDS, and RDS is handled after LDS. But I can't find the relation between LDS and CDS/EDS in Envoy's source code. Does LDS have to be executed after CDS/EDS in Envoy's source code?

**Comment by 123liuziming** [comment]
How envoy ensures that the CDS/EDS is updated before LDS?

**Comment by htuch** [comment]
The ordering at initialization is specified at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/init.html. At runtime, there is no relationship between CDS and LDS, they are independent subsystem and do not warm on each other. See also issues such as https://github.com/envoyproxy/envoy/issues/5174.
