### ISSUE TITLE
Add OAuth2 introspect with anonymous consumer forwarding to OAuth2 http filter.

### ISSUE THREAD

**Issue by KieronWiltshire** [envoyproxy/envoy#26774]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Very simply, I'd like an OAuth2 introspect filter which I can use on my routes passing additional info such as the subject and scopes as a bearer token with the additional possibility of providing a default subject if the introspection fails, such as "anonymous."

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
Ory Oathkeeper does this well but it's lacking general support.

**Comment by KieronWiltshire** [comment]
After some research I've realised what I'm requesting really is an OAuth2 introspect. I will change the title to represent the actual issue.

**Comment by htuch** [comment]
@snowp

**Comment by KieronWiltshire** [comment]
I should probably add to this that I think the best way to do this would be to allow the ability to introspect the token and create a custom JWT with claims from the introspection response, the payload may look something like this:

```json
{
   ...jwt
   "anonymous": introspect.active,
   "client_id": introspect.client_id,
   "username": introspect.username,
   "scopes": introspect.scopes,
}
```

The question would be, how can the microservice verify the payload? This would likely need envoy to expose JWKS (which I don't think is a bad idea). It may also be a good idea to allow specific routes to allow "anonymous" fallback or not.
