### ISSUE TITLE
OpenTracing: common extension code coverage insufficient without client datadog extension

### ISSUE THREAD

**Issue by dgoffredo** [envoyproxy/envoy#26772]
@wbpcode @Shikugawa @basvanbeek from the [CODEOWNERS][1].

I'm working to remove the OpenTracing dependency from Datadog's tracing extension.

The final PR in a series is <https://github.com/envoyproxy/envoy/pull/26284>. That PR actually removes all references of OpenTracing from the Datadog tracing extension.

As a result, the unit test coverage of `extensions/tracers/common/ot` has fallen below a threshold enforced by the CI checks. This is probably due to Datadog's unit tests no longer covering code in `common/ot`.

Here is a coverage report that includes the modified Datadog code: https://storage.googleapis.com/envoy-pr/ec41b8e/coverage/index.html

Here is a coverage report that does not include the modified Datadog code: https://storage.googleapis.com/envoy-pr/45484d5/coverage/index.html

The only difference in coverage of the `common/ot` source is here:
![diff](https://user-images.githubusercontent.com/5205367/232159893-ae99fc48-bcdd-451a-b8e6-65def9f20e81.png)

That is, <https://github.com/envoyproxy/envoy/blob/4c12d8eda176081a493968709d510065d715347b/source/extensions/tracers/common/ot/opentracing_driver_impl.cc#L68-L75>.

I looked into adding a test case to `common/ot` myself to cover that function, but it's rather involved. It would involve poking `opentracing-cpp`'s `MockTracer` in just the right way. Maybe you can think of a better approach.

[1]: https://github.com/envoyproxy/envoy/blob/4c12d8eda176081a493968709d510065d715347b/CODEOWNERS#L255

**Comment by wbpcode** [comment]
I will check it next week. And if it's a reasonable decreasing, you can mark it in the `KNOWN_LOW_COVERAGER` of `per_file_coverage.sh`.

**Comment by basvanbeek** [comment]
I think it is reasonable to mark as OpenTracing is migrated away from in favor of both OpenTelemetry as well as native instrumentations.

**Comment by dgoffredo** [comment]
I added another test case to increase the coverage.
