### ISSUE TITLE
grpc web max payload size

### ISSUE THREAD

**Issue by Bairou2001** [envoyproxy/envoy#26794]
Is there a way to increase the maximum payload size of grpc web requests in envoy? It seems that the default max is 4mb. I tried adding `max_request_size ` to the `grpc_web` http filter under `typed_config`, but it didn't seem to work (gives the error `Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:max_request_size: Cannot find field.) has unknown fields`). Would really appreciate if anyone can help on this, Thanks!

**Comment by htuch** [comment]
@fengli79 @lizan

**Comment by Bairou2001** [comment]
Closed. sorry about the confusion, it was unrelated to envoy
