### ISSUE TITLE
Description Failed to convert the accesslog proto file

### ISSUE THREAD

**Issue by jiayoukun** [envoyproxy/envoy#26801]
I need to convert the method of accesslog proto file into go method for use, but the following error was reported after I tried to convert. Have you ever encountered it? How to solve it?
Waiting for your reply, thank you!

I'm executing under an envoy/api directory.
$ git submodule update --init --recursive
$ protoc --go_out=. --go-grpc_out=. envoy/config/accesslog/v3/accesslog.proto
udpa/annotations/status.proto: File not found.
udpa/annotations/versioning.proto: File not found.
validate/validate.proto: File not found.

I have installed protoc.
$ protoc --version
libprotoc 22.3

**Comment by htuch** [comment]
The API protos need to be built under Bazel, there's no support for direct invocation via protoc. @kyessenov I think you might have some experience building Go protos IIRC?

**Comment by kyessenov** [comment]
Yeah, you need to include all the dependencies protos with `-I`. Here you are missing protoc-gen-validate and cncf/xds protos.
