### ISSUE TITLE
ext authz may call external authentication in decodeTrailers phase even if it has been called in decodeData phase

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#26809]
*Title*: *ext authz may call external authentication in decodeTrailers phase even if it has been called in decodeData phase*

*Description*:

Ext authz will call external authentication when buffer is full in `decodeData` phase, and it should not be called again in `decodeTrailers` phase. But now `decodeTrailers` will call external authentication again because it just determine the value of `filter_return_` which may be changed before `decodeTrailers`.

https://github.com/envoyproxy/envoy/blob/51964702956d64adcd1df6b8ea132e863fe78e74/source/extensions/filters/http/ext_authz/ext_authz.cc#L155

if this is a bug, i will try to fix, thanks.

**Comment by htuch** [comment]
A cursory looks indicates this might be possible. Can you create a test case to trigger this? It would be needed as a regression in any case for any fix PR. Thanks.

**Comment by StarryVae** [comment]
sure, thanks.

**Comment by StarryVae** [comment]
sorry, it may not be a bug, since `buffer_data_` will be set to false in `continueDecoding` , so `decodeTrailers` will not call external authentication again.

https://github.com/envoyproxy/envoy/blob/635289d8430b01a0e1b5a8e4905b359e1c5bbd1e/source/extensions/filters/http/ext_authz/ext_authz.cc#L445

**Comment by htuch** [comment]
Yep, looks to be the case.
