### ISSUE TITLE
Ensure all caches are blown in scheduled runs

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#26813]
We have recently added scheduled runs that dont cache tests - this at least reruns the tests that are flakey, but it doesnt rebuild anything that hasnt changed

Changing the `VERSION.txt` seems to blow pretty much all caches - perhaps there is more elegant way to do this not sure - but adding some random version suffix to the uncached runs really should put CI through its paces, and ideally highlight problems

**Comment by phlax** [comment]
probably just using an `action_env` is better https://stackoverflow.com/questions/59095711/how-to-force-rebuild-a-package-in-bazel-to-measure-build-time

not sure why but VERSION changes seem to create more issues but maybe its just more noticable when it happens

**Comment by phlax** [comment]
we can reuse `BAZEL_FAKE_SCM_REVISION` for this i reckon

**Comment by phlax** [comment]
checking CI runs on release branches and it seems that not all caches are blown by changing the VERSION, but all tests are

eg, on 1.24

```console
INFO: 28633 processes: 12945 remote cache hit, 9437 internal, 1 local, 6250 remote.

Executed 1087 out of 1087 tests: 1087 tests pass.
```

cc @wbpcode

**Comment by wbpcode** [comment]
is this have a final conclusion? I am forget all context about this. orz.

**Comment by phlax** [comment]
there is a pr here to do it #26814 but tbh im reluctant to land it 

i think it cant as it is as it would create huge pointless caches

im also wondering how beneficial it would be - we get a reasonable flake signal from `main` - and we can also see what is flaking in PRs so probably this isnt needed

ill close this and the PR for now and we can revisit if there is a benefit
