### ISSUE TITLE
Connection pool per stream info for dynamic forward proxy

### ISSUE THREAD

**Issue by sridbv** [envoyproxy/envoy#26817]
*Add a new config parameter connection_pool_per_key_format in cluster proto*

*Description*:
Solving a use-case to create unique connection pool based on the stream info ( request headers & dynamic-metadata ) when using the cluster type "dynamic_forward_proxy". I have a patch developed based on the implementation of "connection_pool_per_downstream_connection".  Request for additional inputs or comments, so as to move forward with raising a PR for the same. Below is an example config. 

connection_pool_per_key_format: "%REQ(:authority)%:%DYNAMIC_METADATA(my.namespace:test)%"

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by sridbv** [comment]
@alyssawilk: noticed you are have some ongoing in DFP, tagging you for your inputs. Also is it possible to add the label area/forward proxy.

**Comment by alyssawilk** [comment]
yeah it would have been nice if the cluster config connection_pool_per_downstream_connection were something extensible, where it would have been a hash on downstream address.  I think as long as we follow convention for how we set these up I think it'd be a nice feature to have

**Comment by alyssawilk** [comment]
one thing to be clear about in the API is if this replaces or extends existing hashing options.  I'd be inclined to extend, but we should be clear in docs.

**Comment by sridbv** [comment]
@alyssawilk Can you give direction on how to move forward to converge on the API ? ( Please note I am newbie to envoy contribution)

**Comment by alyssawilk** [comment]
honestly your best bet is to prototype the change, and get an API shepherd assigned to that PR.
