### ISSUE TITLE
TLS Validation Context (same config) not working on different versions

### ISSUE THREAD

**Issue by lalernehl** [envoyproxy/envoy#26816]
@htuch closed the issue when config v3 still supported: I have the exact same config (v3) working on envoy v1.25.4 but not working on v1.23.1.

Also @ggreenway for visibility.

Please refer to https://github.com/envoyproxy/envoy/issues/26788 for all the details

**Comment by htuch** [comment]
OK, sorry, missed that this was also on 1.23.1 and v3. @ggreenway any thoughts?

**Comment by ggreenway** [comment]
Going to close this and reopen previous, since all the information is there
