### ISSUE TITLE
envoy configuration validate error (v 1.26.0)

### ISSUE THREAD

**Issue by hellower** [envoyproxy/envoy#26822]
#>  docker run --rm -d envoyproxy/envoy:v1.26.0

------ in docker container ------------
#>  root@f7e414ec5303:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
envoy          1       0  0 00:56 ?        00:00:00 envoy -c /etc/envoy/envoy.yaml
root          31       0  0 00:56 pts/0    00:00:00 bash
root          50      31  0 00:57 pts/0    00:00:00 ps -ef

root@f7e414ec5303:/#  envoy --mode validate -c /etc/envoy/envoy.yaml
[2023-04-19 00:57:41.979][51][critical][main] [source/server/config_validation/server.cc:66] error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for name: 'envoy.listener_manager_impl.validation'
root@f7e414ec5303:/#

**Comment by htuch** [comment]
Can you share the config you are using here? @alyssawilk this looks related to the validation listener manager.

**Comment by hellower** [comment]
docker run --rm -d envoyproxy/envoy:v1.26.0
envoy:v1.26.0 docker containers' default  envoy.yaml

I didn't change envoy.yaml at all.

sorry for poor english.

**Comment by hellower** [comment]
root@9254a8c36ddc:/# cat /etc/envoy/envoy.yaml 
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          scheme_header_transformation:
            scheme_to_overwrite: https
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
root@9254a8c36ddc:/#

**Comment by phlax** [comment]
thanks for reporting @hellower 

confirming the issue:

```console
$ docker run --rm  envoyproxy/envoy:v1.26.0 --mode validate -c /etc/envoy/envoy.yaml
[2023-04-21 00:09:48.289][1][critical][main] [source/server/config_validation/server.cc:66] error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for name: 'envoy.listener_manager_impl.validation'
```

its kinda frustrating because we are validating the configs two different ways already so surprised we havent picked this up
