### ISSUE TITLE
Use `FactoryContext` in createRouteSpecificFilterConfig

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#26845]
Currently in Envoy, there are 1) [FactoryContext](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/envoy/server/factory_context.h#L214) and 2) [ServerFactoryContext](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/envoy/server/factory_context.h#L152). They both inherit from same base class and have their own methods. These seems can be simplified. But I am more interested in the specific case below regarding `routeSpecificConfig`: 

For [createRouteSpecificFilterConfig](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/http/common/factory_base.h#L27), it seems ok to just take in `FactoryContext` rather than `ServerContext` based on my code walk, because:
1)  We can get `serverFactoryContext` from `FactoryContext` via [getServerFactoryContext](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/envoy/server/factory_context.h#L221)
2) For routeSpecificConfig, all the way up, the `ServerContext` is actually provided by [context_.getServerFactoryContext()](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/network/http_connection_manager/config.cc#L479) and [here](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/network/http_connection_manager/config.cc#L485) 
3. IIUC,  TODO from @mattklein123 [here](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/envoy/server/factory_context.h#L211) seems indicate that `FactoryContext` is preferred approach

Thus, my questions are:
1) why it is using ServerContext for   [createRouteSpecificFilterConfig](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/http/common/factory_base.h#L27).

2) can [createRouteSpecificFilterConfig](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/http/common/factory_base.h#L27) take in `FactoryContext` rather than `ServerContext`? Anything like lifetime issue prevent from using `FactoryContext` here?

Thanks in advance!

**Comment by wbpcode** [comment]
Answer to question one: FactoryContext has listener level lifetime and is listener dependent. And in the current impl, the route configuration from rds may be shared by multiple different listeners. So it couldn't be listener dependent and only server factory context could be used.

**Comment by wbpcode** [comment]
Answer to question two: it's possible. But we need evaluate the overhead and the gain first. (Additional memory overhead, additional computation, additional config validation)

**Comment by tyxia** [comment]
@wbpcode  Thank you very much for reply and answers! I also have done some research these days. I think changing `createRouteSpecificFilterConfig ` to take in `FactoryContext` is not what I want to do here.

> FactoryContext has listener level lifetime and is listener dependent. And in the current impl, the route configuration from rds may be shared by multiple different listeners. So it couldn't be listener dependent and only server factory context could be used.

Yes, you are right. So, `FactoryContext` is **listener-dependent** while `ServerFactoryContext`/route is **listener-independent** that is shared by multiple listeners.

My question is : 
In [createRouteSpecificFilterConfig](https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/extensions/filters/http/common/factory_base.h#L27) which has `ServerFactoryContext`, Can I store the reference to `FactoryContext` and use this ref later?  There are two potential ways of getting `FactoryContext`. Let's assume I reinterpret_cast from `ServerFactoryContext` to `FactoryContext` in `createRouteSpecificFilterConfig` and discuss if it is safe to use this reference to `FactoryContext` later first:
I am thinking as long as I use that reference for **listener-independent** stuff , it should be safe because those  **listener-independent** stuff should be same  between `ServerFactoryContext` and `FactoryContext`.  **I am wondering if my understanding here is correct?**
For example:
- [ClusterManager](https://github.com/envoyproxy/envoy/blob/f2a6dc5a2cec23353d6acdba7e406809b93fb345/envoy/server/factory_context.h#L113). This is entire server level data. So FactoryContext is  **listener-dependent**, it should be pointing to the same data as other `FactoryContext` and `ServerFactoryContext`

**Comment by wbpcode** [comment]
> Let's assume I reinterpret_cast from ServerFactoryContext to FactoryContext

I think you cann't do this because these is no inherit relationship between server factory context and factory context. And they are complete different two objects. The server factory context is a global singleton in the runtime.

> I am thinking as long as I use that reference for listener-independent stuff

Then why cann't you use the server factory context directly?

**Comment by wbpcode** [comment]
So, take a step back, if your goal is to simplify the API and use `FactoryContxt` in the `createRouteSpecificFilterConfig`, than refactor the rds and make the `route config provider` listener dependent is the only rationaly way, i think. 🤔

**Comment by tyxia** [comment]
@wbpcode regarding `reinterpret_cast`, yea it is a hack for prototyping. The example below kinds explain why it is working in my integration test.   [ClusterManager](https://github.com/envoyproxy/envoy/blob/f2a6dc5a2cec23353d6acdba7e406809b93fb345/envoy/server/factory_context.h#L113) is like `x` that is available in their common base and alive(server level thing). But yes, I am thinking about the proper solution :) 

```
class Base {
public:
    int x;
    Base() : x(100) {}
};

class Child1 : public Base {
public:
    int y;
    Child1() : y(1) {}
};

class Child2 : public Base {
public:
    int z;
    Child2() : z(2) {}
};

int main() {
    Child1 c1;
    std::cout << c1.x << std::endl; 
    Child2* c2 = reinterpret_cast<Child2*>(&c1);
    std::cout << (*c2).x << std::endl; 
    return 0;
}
```

**Comment by tyxia** [comment]
`serverFactoryContext` and `factoryContext` inherit from common base. I think it should not be UB as long as you access to the method in common base. Ultimately , it is just two pointers pointing to same underlying memory. I have a integration test proved that `reinterpret_cast` between `serverFactoryContext` and `factoryContext` works when I accesses the `clusterManager`

But again,  `reinterpret_cast` is an experiment and will not be the solution that i proceed with. Thank you for inputs/insights on RDS! I don't think I will refactor RDS stuff(at least not for now). But I do feel there are too many `contexts` now in Envoy that potentially can be cleaned up. I can give it a try when I have some free cycles.
