### ISSUE TITLE
Clarification - Can retries stay in a given priority?

### ISSUE THREAD

**Issue by JKerwood** [envoyproxy/envoy#26843]
*Title*: *Is there a configuration to do retries only within an initial priority?*

*Description*:
My service is idempotent within priority (region).  I'd like to also do perTryRetires.
Case 1: P0 Healthy P1 Healthy - I believe 100% will go P0
Case 2: P0 1/4 healthy P1 Healthy - Will 100% stay at P0 or will it start moving to P1 automatically?  Possibly set [overprovisioning factor](https://www.envoyproxy.io/docs/envoy/v1.26.0/intro/arch_overview/upstream/load_balancing/overprovisioning#arch-overview-load-balancing-overprovisioning-factor) to 1000?  My volume on this service is low but important.  
Case 3: P0 unhealthy P1 Healthy - I believe 100% will go P1
Case 4: P0 1 healthy P1 Healthy - I'd like 100% to go P0.  If request is slower than PerTryRetry and P0 becomes unhealthy will the retry go to P1?  If so this would break my idempotency.  I'd rather error the retry request and hedge the first call.
Case 5: Similarly coming back to P0.  P0 unhealthy P1 Healthy - I believe 100% will go P1.  If request is slower than PerTryRetry and P0 becomes healthy will the retry go to P0?  If so this would break my idempotency.

*Relevant Links*:
[Priority levels](https://www.envoyproxy.io/docs/envoy/v1.26.0/intro/arch_overview/upstream/load_balancing/priority.html#priority-levels)
[Overprovisioning Factor](https://www.envoyproxy.io/docs/envoy/v1.26.0/api-v3/config/endpoint/v3/endpoint.proto#envoy-v3-api-field-config-endpoint-v3-clusterloadassignment-policy-overprovisioning-factor)

**Comment by htuch** [comment]
I think you might be after https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management.html#retry-plugin-configuration. @snowp

**Comment by JKerwood** [comment]
We use these plugins currently but the documentation doesn't discuss what I'm asking above to my knowledge.  I'm worried about retries and want something like an OriginalPriorityLock if that isn't what the current implementation does.

**Comment by JKerwood** [comment]
Any extra documentation or ideas about a StaticPriorityRetry plugin?

**Comment by JKerwood** [comment]
Anyone have time to talk about this some?  Possibly @snowp since you were mentioned above?
