### ISSUE TITLE
Bug: Ejection algo removes more endpoints than max_ejection_percentage 

### ISSUE THREAD

**Issue by Pawan-Bishnoi** [envoyproxy/envoy#26877]
*Title*: Ejected hosts should always be less than max_ejection_percentage

*Current behaviour*:
> Outlier detection ejects two pods when 3 total are running and max_ejection_percentage is 50%

*Expected behaviour*:
> max_ejection_percentage of 50% should only allow 1 ejection in case of 3 total pods.

[optional *Relevant Links*:]
> [Current algo checks](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#ejection-algorithm) the limits first and ejection happens later -> https://github.com/envoyproxy/envoy/blob/54809a0530b26a33b21f77429be1b87772cca626/source/common/upstream/outlier_detection_impl.cc#L476-L483

Why not check the actual ejected_percentage that we will reach after this ejection? The current behaviour is a little counter-intuitive.

**Comment by htuch** [comment]
FTR existing docs are:
```
// The maximum % of an upstream cluster that can be ejected due to outlier
// detection. Defaults to 10% but will eject at least one host regardless of the value.
```

Seems reasonable to improve precision here, CC @mattklein123

**Comment by Pawan-Bishnoi** [comment]
I can submit the fix if it makes sense. Please assign it to me. Thanks!

**Comment by Pawan-Bishnoi** [comment]
> but will eject at least one host regardless of the value
Any specific reason for this behaviour?

This will make things difficult in case there is only one pod running.

**Comment by Pawan-Bishnoi** [comment]
not stale.

**Comment by htuch** [comment]
@Pawan-Bishnoi what is actionable in this bug?

**Comment by Pawan-Bishnoi** [comment]
@htuch There are two parts to it.

1. We eject atleast one host regardless of max_ejection_percentage
2. max_ejection_percentage is not enforced. Eg. 2/3 pods are ejected when mep=50%. Which is clearly more than 50%. 


The [draft PR](https://github.com/envoyproxy/envoy/pull/27624) aims to fix 2.

**Comment by Pawan-Bishnoi** [comment]
not stale. One PR merged, one in progress.

**Comment by Pawan-Bishnoi** [comment]
not stale. Need to take care of CI failures on the [last PR](https://github.com/envoyproxy/envoy/pull/27909).
