### ISSUE TITLE
invalid value Invalid type URL, unknown type

### ISSUE THREAD

**Issue by xxandjg** [envoyproxy/envoy#26885]
*Title*: *Configuration file running error*

*Description*:
I plan to use Golang to develop an HTTP filter plugin for Envoy, but after building it locally, there was an error running the golang example in Repo

Compilation and operation process
>
>- Building the environment
>   - Apple M1
>   - macos 13.3.1 (22E261)
>   - envoy (v1.26.0)
>
>- Build Command
>
>   ```sh
>    bazel build -c dbg --spawn_strategy=local //source/exe:envoy-static 
>    ```
>
>   ```sh
>    go build -o simple.so -buildmode=c-shared .
>    ```
>
>- Execute Command
>
>   ```sh
>    ../../bazel-bin/source/exe/envoy-static -c ./envoy.yaml
>    ```
>
Error message output by the terminal
>
>- Command execution error
>
>  ```shell
>  [2023-04-24 11:42:08.658][161426][info][main] [source/server/server.cc:408]   envoy.transport_sockets.downstream: envoy.transport_sockets.alts, envoy.transport_sockets.quic, envoy.transport_sockets.raw_buffer, envoy.transport_sockets.starttls, envoy.transport_sockets.tap, envoy.transport_sockets.tcp_stats, envoy.transport_sockets.tls, raw_buffer, starttls, tls
>  [2023-04-24 11:42:08.658][161426][info][main] [source/server/server.cc:408]   envoy.path.rewrite: envoy.path.rewrite.uri_template.uri_template_rewriter
>  [2023-04-24 11:42:08.658][161426][info][main] [source/server/server.cc:408]   envoy.matching.network.input: envoy.matching.inputs.application_protocol, envoy.matching.inputs.destination_ip, envoy.matching.inputs.destination_port, envoy.matching.inputs.direct_source_ip, envoy.matching.inputs.dns_san, envoy.matching.inputs.filter_state, envoy.matching.inputs.server_name, envoy.matching.inputs.source_ip, envoy.matching.inputs.source_port, envoy.matching.inputs.source_type, envoy.matching.inputs.subject, envoy.matching.inputs.transport_protocol, envoy.matching.inputs.uri_san
>  [2023-04-24 11:42:08.682][161426][critical][main] [source/server/server.cc:131] error initializing configuration './envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.golang.v3alpha.Config for type Any): {"static_resources":{"clusters":[{"type":"STRICT_DNS","name":"helloworld_service_cluster","load_assignment":{"cluster_name":"helloworld_service_cluster","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8080,"address":"helloworld_service"}}}}]}]},"lb_policy":"ROUND_ROBIN"}],"listeners":[{"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"http_filters":[{"name":"envoy.filters.http.golang","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config","library_id":"simple","library_path":"/Users/mu/Downloads/attains/be/envoy/examples/golang/simple/simple.so","plugin_name":"simple","plugin_config":{"value":{"prefix_localreply_body":"Configured local reply from go"},"@type":"type.googleapis.com/xds.type.v3.TypedStruct"}}},{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","route_config":{"virtual_hosts":[{"routes":[{"match":{"prefix":"/"},"route":{"cluster":"helloworld_service_cluster"}}],"domains":["*"],"name":"local_service"}],"name":"local_route"},"stat_prefix":"ingress_http"}}]}],"address":{"socket_address":{"port_value":10000,"address":"0.0.0.0"}},"name":"listener_0"}]}}
>  [2023-04-24 11:42:08.684][161426][info][main] [source/server/server.cc:980] exiting
>  Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.golang.v3alpha.Config for type Any): {"static_resources":{"clusters":[{"type":"STRICT_DNS","name":"helloworld_service_cluster","load_assignment":{"cluster_name":"helloworld_service_cluster","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8080,"address":"helloworld_service"}}}}]}]},"lb_policy":"ROUND_ROBIN"}],"listeners":[{"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"http_filters":[{"name":"envoy.filters.http.golang","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config","library_id":"simple","library_path":"/Users/mu/Downloads/attains/be/envoy/examples/golang/simple/simple.so","plugin_name":"simple","plugin_config":{"value":{"prefix_localreply_body":"Configured local reply from go"},"@type":"type.googleapis.com/xds.type.v3.TypedStruct"}}},{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","route_config":{"virtual_hosts":[{"routes":[{"match":{"prefix":"/"},"route":{"cluster":"helloworld_service_cluster"}}],"domains":["*"],"name":"local_service"}],"name":"local_route"},"stat_prefix":"ingress_http"}}]}],"address":{"socket_address":{"port_value":10000,"address":"0.0.0.0"}},"name":"listener_0"}]}}
>  ```
>
>- Error in verifying configuration command
>
>  ```shell
>  ➜  golang git:(v1.26.0) ✗ ../../bazel-bin/source/exe/envoy-static --mode validate -c ./envoy.yaml
>  [2023-04-24 11:42:37.440][161852][critical][main] [source/server/config_validation/server.cc:66] error initializing configuration './envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.golang.v3alpha.Config for type Any): {"static_resources":{"clusters":[{"load_assignment":{"cluster_name":"helloworld_service_cluster","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":8080,"address":"helloworld_service"}}}}]}]},"lb_policy":"ROUND_ROBIN","name":"helloworld_service_cluster","type":"STRICT_DNS"}],"listeners":[{"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","stat_prefix":"ingress_http","http_filters":[{"typed_config":{"library_id":"simple","plugin_config":{"value":{"prefix_localreply_body":"Configured local reply from go"},"@type":"type.googleapis.com/xds.type.v3.TypedStruct"},"library_path":"/Users/mu/Downloads/attains/be/envoy/examples/golang/simple/simple.so","@type":"type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config","plugin_name":"simple"},"name":"envoy.filters.http.golang"},{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"},"name":"envoy.filters.http.router"}],"route_config":{"name":"local_route","virtual_hosts":[{"domains":["*"],"name":"local_service","routes":[{"match":{"prefix":"/"},"route":{"cluster":"helloworld_service_cluster"}}]}]}}}]}],"address":{"socket_address":{"address":"0.0.0.0","port_value":10000}},"name":"listener_0"}]}}
>  ```
>
configuration file
>
>```yaml
># envoy demo with golang extension enabled
>static_resources:
>  listeners:
>  - name: listener_0
>    address:
>      socket_address:
>        address: 0.0.0.0
>        port_value: 10000
>    filter_chains:
>    - filters:
>      - name: envoy.filters.network.http_connection_manager
>        typed_config:
>          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
>          stat_prefix: ingress_http
>          http_filters:
>          - name: envoy.filters.http.golang
>            typed_config:
>              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
>              library_id: simple
>              library_path: "/Users/mu/Downloads/attains/be/envoy/examples/golang/simple/simple.so"
>              plugin_name: simple
>              plugin_config:
>                "@type": type.googleapis.com/xds.type.v3.TypedStruct
>                value:
>                  prefix_localreply_body: "Configured local reply from go"
>          - name: envoy.filters.http.router
>            typed_config:
>              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
>          route_config:
>            name: local_route
>            virtual_hosts:
>            - name: local_service
>              domains: ["*"]
>              routes:
>              - match:
>                  prefix: "/"
>                route:
>                  cluster: helloworld_service_cluster
>  clusters:
>  - name: helloworld_service_cluster
>    type: STRICT_DNS
>    lb_policy: ROUND_ROBIN
>    load_assignment:
>      cluster_name: helloworld_service_cluster
>      endpoints:
>      - lb_endpoints:
>        - endpoint:
>            address:
>              socket_address:
>                address: helloworld_service
>                port_value: 8080
>```

**Comment by wbpcode** [comment]
golang filter is only provided by the binary with contrib extensions. It would be better to build envoy binary with target `//contrib/exe:envoy-static`.

**Comment by xxandjg** [comment]
Hi @wbpcode

**Comment by xxandjg** [comment]
Hi @wbpcode 
I attempted to use the following command for the build operation, but a new error occurred.
>
>
>```shell
>➜  envoy git:(v1.26.0) ✗ bazel build -c dbg --spawn_strategy=local //contrib/exe:envoy-static                                                     
>ERROR: Target //contrib/exe:envoy-static is incompatible and cannot be built, but was explicitly requested.
>Dependency chain:
>    //contrib/exe:envoy-static (e0803d)
>    //contrib/vcl/source:config_envoy_extension (e0803d)
>    //contrib/vcl/source:config (e0803d)
>    //contrib/vcl/source:vcl_interface_lib (e0803d)
>    //contrib/vcl/source:vpp_vcl (e0803d)
>    //contrib/vcl/source:external/libsvm.a (e0803d)
>    //contrib/vcl/source:build (e0803d)   <-- target platform (@envoy//bazel:macos_arm64) didn't satisfy constraint @platforms//os:linux
>INFO: Elapsed time: 0.128s
>INFO: 0 processes.
>FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
>```

**Comment by wbpcode** [comment]
Lots of contrib extensions have constraints to the os/platform. You may need comment these extenstions in the `contrib_build_config.bzl`.

**Comment by xxandjg** [comment]
Thank you, I have successfully built the envoy locally.
