### ISSUE TITLE
An thrift protocol request question

### ISSUE THREAD

**Issue by jiayoukun** [envoyproxy/envoy#26893]
The realization of the work for envoy.filters.network.thrift_proxy:
When a Thrift protocol request goes to the Envoy, the Envoy decodes the request through the ThriftFilter, converts it into a new HTTP request, and sends the HTTP request to the back-end service. When the response from the back-end service arrives, the Envoy converts the HTTP response into the Thrift serialization format and sends it back to the client.
Am I reading this correctly?
Waiting for your reply, thank you!

**Comment by adisuissa** [comment]
cc @JuniorHsu as code-owner.

**Comment by jiayoukun** [comment]
@JuniorHsu 
Waiting for your answer, thank you！

**Comment by JuniorHsu** [comment]
There's no HTTP protocol involved. It's `thrift_proxy` so envoy basically *proxy* the thrift request to the upstream and the thrift response back to the downstream. We can do metrics/load balancing/routing/filter from features of thrift like thrift header or method. The connection model is like HTTP1 at the moment, i.e., ping-pong model.

**Comment by jiayoukun** [comment]
> There's no HTTP protocol involved. It's `thrift_proxy` so envoy basically _proxy_ the thrift request to the upstream and the thrift response back to the downstream. We can do metrics/load balancing/routing/filter from features of thrift like thrift header or method. The connection model is like HTTP1 at the moment, i.e., ping-pong model.

Thank you very much for your reply!
