### ISSUE TITLE
gzip HTTP filter

### ISSUE THREAD

**Issue by fabware** [envoyproxy/envoy#269]
I use envoy as front end proxy, set Accept-Encoding: gzip doesn't work. Content doesn't get compressed.

There seems no document for encoding configuration.

**Comment by mattklein123** [comment]
Envoy is not a origin server and currently does not support any kind of automatic content transformation.

We could implement an HTTP compression filter so that is the feature request here.

**Comment by fabware** [comment]
Noted. Thanks for your clarification.

**Comment by gabriel-sagula-hs** [comment]
Hi @mattklein123, would be possible to see some http filter example?

**Comment by mattklein123** [comment]
@gabriel-sagula-hs there are numerous examples in the existing code base. Can you look at one of those? I would love to have a more self contained example but don't have the time right now. (FWIW many people have written filters with little/no interaction with me so I know it's doable).

**Comment by gabriel-sagula-hs** [comment]
Thanks for the quick response @mattklein123 
We are evaluating few products right now, including Envoy. One thing that is critical for us is to be able to accept gzip. So, I'm trying to write a filter for that.
Are those the examples that you refer to? https://github.com/lyft/envoy/tree/master/source/common/http/filter

Thanks!

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/tree/master/source/server/config/http

**Comment by mattklein123** [comment]
Also here: https://github.com/lyft/envoy/tree/master/source/server/http

Those are the config loaders for all the filters, which you can then search through to the code.

**Comment by gabriel-sagula-hs** [comment]
Thanks Matt for your time. This is very helpful.

**Comment by mattklein123** [comment]
This is being worked on by @gsagula

**Comment by mattklein123** [comment]
Fixed
