### ISSUE TITLE
envoy_reloadable_features_delta_xds_subscription_state_tracking_fix deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#26901]
Your change #23343 (delta-xds: resource state tracking after resource ingestion) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by DiazAlan** [comment]
Talked to Adi offline, I'll take this for him
