### ISSUE TITLE
envoy_reloadable_features_do_not_count_mapped_pages_as_free deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#26902]
Your change #22585 (Fixed heap monitor: discount pageheap free bytes) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by DiazAlan** [comment]
Tragically, I did not implement the flag correctly the first time so it was not exercising the new behavior by default. I uploaded a PR [(27359)](https://github.com/envoyproxy/envoy/pull/27359) to fix this with the correct change. The runtime guard flag has been changed as well. So we can probably close this issue.

**Comment by DiazAlan** [comment]
It was already merged before, will it close this issue if you tagged the PR post merge?

**Comment by alyssawilk** [comment]
oops sorry was paying insufficient attention.  closed
