### ISSUE TITLE
envoy_reloadable_features_unified_header_formatter deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#26910]
Your change #21932 (router: unified header formatters) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by wbpcode** [comment]
friendly ping @alyssawilk 

Six months has passed. 😃 We finally could remove the deprecated formatter.

**Comment by cpakulski** [comment]
I have already started working on removing the runtime guard. Will open PR next week.

**Comment by alyssawilk** [comment]
@wbpcode I filed these via the script but yeah you want to ping the assignee.  Thanks for getting on this @cpakulski  :-)
