### ISSUE TITLE
envoy Buildkite build is broken with bazel 6 

### ISSUE THREAD

**Issue by sgowroji** [envoyproxy/envoy#26913]
CI : https://buildkite.com/bazel/envoy/builds/2376

 Envoy is failing with Bazel@Release, probably because **llvm14** wasn't installed properly https://github.com/envoyproxy/envoy/blob/6bc593a029fe01fe7df257a0a4e1b2cbfd597e08/.bazelci/presubmit.yml#L21

Downstream :  https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2975#0187b105-30f8-4160-ba9c-87133ca13887

Error logs :  
```
ld.lld: error: cannot open /usr/lib/llvm-14/lib/clang/14.0.6/lib/linux/libclang_rt.profile-x86_64.a: No such file or directory
--
  | clang: error: linker command failed with exit code 1 (use -v to see invocation)
  | (02:15:00) INFO: Elapsed time: 54.890s, Critical Path: 0.63s
  | (02:15:00) INFO: 912 processes: 1 remote cache hit, 909 internal, 2 linux-sandbox.
  | (02:15:00) ERROR: Build did NOT complete successfully
  | //test/common/common:matchers_test                              FAILED TO BUILD
  |  
  | Executed 0 out of 132 tests: 1 fails to build and 131 were skipped.
  | (02:15:00) INFO: Build Event Protocol files produced successfully.
  | bazel test failed with exit code 1
  | 🚨 Error: The command exited with status 1

```
Note : Not able to reproduce the error locally.

cc @meteorcloudy

**Comment by phlax** [comment]
@sgowroji those are the same bazel and clang versions we test with in CI, im wondering what is different about either the env or bazel flags that cause it to fail 

mostly we use RBE which would obv make a difference, but some of our CI uses the host clang

**Comment by meteorcloudy** [comment]
Please look into the log in https://buildkite.com/bazel/envoy/builds/2376#0187b0a5-11e8-41dd-9aec-25320bbfc2bb to find more information. And you probably can tweak the https://github.com/envoyproxy/envoy/blob/6bc593a029fe01fe7df257a0a4e1b2cbfd597e08/.bazelci/presubmit.yml#L21 to test out fixes.

/cc @keith

**Comment by phlax** [comment]
cause of issue seems to be https://groups.google.com/g/linux.debian.bugs.dist/c/jFEvS84SakQ

**Comment by keith** [comment]
thanks for the report!
