### ISSUE TITLE
For a small percentage of HTTP2/3 Envoy doesn't read backend's responses and returns 504 timeout

### ISSUE THREAD

**Issue by bartoszp** [envoyproxy/envoy#26933]
*Description*:
We use emissary-ingress 3.5.2 with varnish that caches static content. It looks like Envoy can't read responses from backends for a small percentage of traffic (around 0.002%) when backends properly generate responses.
What's common in such scenario is that the client browser issues many parallel requests for objects.
I'm also attaching Wireshark screenshot where you can see that the backend generates response but envoy refuses to read it.

<img width="1597" alt="Zrzut ekranu 2023-04-25 o 12 49 13" src="https://user-images.githubusercontent.com/917440/234254885-3eb5f8fb-3e08-43ef-9633-bac7b12d601d.png">
<img width="1895" alt="wireshark-1" src="https://user-images.githubusercontent.com/917440/234255120-ce45f8b2-e877-4ead-bf51-872dbd552c72.png">

**Comment by adisuissa** [comment]
Can you provide some details about the configuration for that Envoy? (e.g., is this using both h2 and h3? is health-checking being used?)
cc @alyssawilk

**Comment by bartoszp** [comment]
> Can you provide some details about the configuration for that Envoy? (e.g., is this using both h2 and h3? is health-checking being used?)
> cc @alyssawilk



> Can you provide some details about the configuration for that Envoy? (e.g., is this using both h2 and h3? is health-checking being used?)
> cc @alyssawilk

**Comment by bartoszp** [comment]
@alyssawilk - I've checked it and it response_code_details shows: response_timeout.

As a workaround for this problem I've tried to add 3 retries to upstream, but it doesn't seem to work.
The configuration for envoy is:
```
                            "route": {
                              "cluster": "cluster_varnish_least_request",
                              "prefix_rewrite": "xxx",
                              "priority": null,
                              "retry_policy": {
                                "num_retries": 3,
                                "per_try_timeout": "1s",
                                "retry_on": "5xx"
                              },
                              "timeout": "20.000s",
```
In this case durations shows 1 or 4 second, response_code_details shows upstream_per_try_timeout - it doesn't look like it's retring

**Comment by alyssawilk** [comment]
I guess without a trace I'm not sure how you can tell it's an Envoy problem and not an actual upstream timeout?
