### ISSUE TITLE
Add metadata matching to tcp filter

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#2696]
Currently the tcp filter allows you to route to a cluster, but hard codes an empty `MetadataMatchCriteria` (https://github.com/envoyproxy/envoy/blob/master/source/common/filter/tcp_proxy.h#L148). 

I'd love to be able to specify a `metadata_match` criteria in the tcp_filter config, to avoid me having to generating a unique cluster for each tcp routing I want. Instead, I'd set up a single cluster with various metadata match criteria based on the filter chain.

This seems like an easy enough task to do (just plum through a new config to the tcp_filter), so I'd be happy take a stab at implementing this if it seems like a reasonable idea.

**Comment by ggreenway** [comment]
This sounds reasonable and straightforward. Go ahead and take a stab.
