### ISSUE TITLE
Compilation of envoy 1.24.6 on rocky linux with gcc version 8.5

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#26965]
When I am compiling envoy 1.24.6 on rocky linux with gcc version 8.5. I am getting compilation error like gcc version 9.2 or greater required.
Please confirm is this any kind of limitation that gcc version 9.2 or higher is required on rocky linux to compile envoy 1.24.6

**Comment by adisuissa** [comment]
cc @phlax as area owner

**Comment by phlax** [comment]
@Gaurav0411GitHub could you post the fail logs please ?

The gcc version used in the build image is 9.4.0

```console
$ ./ci/run_envoy_docker.sh gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

so that is what is tested, but i wasnt aware of a limitation on a particular version

**Comment by Gaurav0411GitHub** [comment]
Actually we were using envoy 1.17.4 version that was compiled on gcc version 8.5 but when I have upgraded to envoy 1.23.1 it was simply giving error like gcc version 9.2 or higher version is required so I took gcc 10.2 stable version and i was able to compile successfully.
At this moment I can not share compilation error log on gcc 8.5 so please update this limitation in your documentation also

**Comment by phlax** [comment]
>  please update this limitation in your documentation also

happy to review/raise a PR if i can confirm what the constraints actually are

**Comment by phlax** [comment]
> ...if i can confirm what the constraints actually are

and also why

im aware that there are people building with various compilers/toolchains and in some cases workarounds are neccessary

i suspect in this case its an issue with a dependent lib, but may well be wrong

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/issues/26965#issuecomment-1527374656

**Comment by Gaurav0411GitHub** [comment]
You have updated the latest building guide but actual user should know which minimum gcc version should be used so I think rather than wasting time on compilation minimum gcc version should be mentioned that will be helpful for the user
so please specify minimum gcc version which can be used in compiling envoy

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/issues/26965#issuecomment-1527374656

**Comment by Gaurav0411GitHub** [comment]
which minimum gcc version can be used to compile envoy code?

**Comment by Gaurav0411GitHub** [comment]
What is the end of life of envoy 1.17.4 and envoy 1.21.5 ?

**Comment by Gaurav0411GitHub** [comment]
I am getting the below error logs while i am compiling on gcc 8.5. Could you please help me in this?


bazel --bazelrc=/dev/null build --sandbox_debug --verbose_failures --copt="-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 -DLLVM_USE_SPLIT_DWARF" --define wasm=disabled --config=sizeopt -c opt //source/exe:envoy-static.stripped
INFO: Analyzed target //source/exe:envoy-static.stripped (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/54592e55cbb3b41c11501e7d56ec7ed8/external/com_github_google_tcmalloc/tcmalloc/internal/BUILD:516:11: Compiling tcmalloc/internal/page_size.cc failed: (Exit 1): process-wrapper failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/54592e55cbb3b41c11501e7d56ec7ed8/sandbox/processwrapper-sandbox/2127/execroot/envoy && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-6.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/f0478d8547df16461adab7eb1d945d57/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/root/.cache/bazel/_bazel_root/54592e55cbb3b41c11501e7d56ec7ed8/sandbox/processwrapper-sandbox/2127/stats.out' /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/com_github_google_tcmalloc/tcmalloc/internal/_objs/page_size/page_size.d '-frandom-seed=bazel-out/k8-opt/bin/external/com_github_google_tcmalloc/tcmalloc/internal/_objs/page_size/page_size.o' -gsplit-dwarf -g '-DBAZEL_CURRENT_REPOSITORY="com_github_google_tcmalloc"' -iquote external/com_github_google_tcmalloc -iquote bazel-out/k8-opt/bin/external/com_github_google_tcmalloc -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl '-DABSL_MIN_LOG_LEVEL=4' -fPIC -Wno-deprecated-declarations '-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 -DLLVM_USE_SPLIT_DWARF' -Os '-std=c++17' -Werror -Wno-attribute-alias -Wno-sign-compare -Wno-stringop-overflow -Wno-uninitialized -Wno-unused-function -Wno-unused-result -Wno-unused-variable -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_github_google_tcmalloc/tcmalloc/internal/page_size.cc -o bazel-out/k8-opt/bin/external/com_github_google_tcmalloc/tcmalloc/internal/_objs/page_size/page_size.o)
In file included from external/com_github_google_tcmalloc/tcmalloc/internal/page_size.h:21,
                 from external/com_github_google_tcmalloc/tcmalloc/internal/page_size.cc:15:
external/com_github_google_tcmalloc/tcmalloc/internal/config.h:89:2: error: #error "GCC 9.2 or higher is required."
 #error "GCC 9.2 or higher is required."
  ^~~~~
Target //source/exe:envoy-static.stripped failed to build
INFO: Elapsed time: 1.292s, Critical Path: 0.38s

**Comment by Gaurav0411GitHub** [comment]
Please let me know what is the workaround for this

**Comment by Gaurav0411GitHub** [comment]
If you know the work around for gcc 8.5 error, Please let me know
I have compiled on gcc 11.2. In which I am getting below logs.

[2023-05-12 14:42:05.155][56649][warning][config] [source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) AA_LISTENER_0: Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: X.X.X.X:4568
AA_LISTENER_01: Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: [IPvIP]:4568
AA_SEC_LISTENER_0: Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: X.X.X.X:4569

are these errors or info logs?

**Comment by Gaurav0411GitHub** [comment]
Hi,

I have compiled successfully envoy 1.26.1 version on gcc 11.2 version
envoy 1.26.1 is compatible with gRPC 1.30.3 version and ibprotoc.so.3.12.4.0 ?
While we are upgrading from envoy 1.17.4 to envoy 1.26.1, we are not able to use envoy.filters.network.tcp_proxy.
could you please suggest us should i need to update envoy api or give me reference how can we use envoy.filters.network?

**Comment by phlax** [comment]
Some of the examples provide the updated config you are looking for - eg https://github.com/envoyproxy/envoy/blob/2a63fe20f7dd77062e8ca04ee19bc605bf9e02d5/examples/postgres/envoy.yaml#L14-L18

https://www.envoyproxy.io/docs/envoy/v1.26.1/start/sandboxes/postgres

**Comment by Gaurav0411GitHub** [comment]
Hi,
We have upgraded envoy1.26.1 but we are getting below error
[2023-05-23 12:33:43.456][2411][warning][config] [source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) H2I_NONSEC_LISTENER_0: Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: 10.10.173.135:4568.
Please let mw know how can we solve the problem?
