### ISSUE TITLE
`IpVersions/KeyValueStoreXdsDelegateIntegrationTest.BasicSuccess` is flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#26974]
I have seen this a few times, but infrequently, and only recently

```console

[       OK ] IpVersions/KeyValueStoreXdsDelegateIntegrationTest.BasicSuccess/3 (268 ms)
[ RUN      ] IpVersions/KeyValueStoreXdsDelegateIntegrationTest.BasicSuccess/4
./test/integration/server.h:445: Failure
Value of: TestUtility::waitForCounterGe(statStore(), name, value, time_system_, timeout)
  0x1b977d4: testing::Test::Run()
  0x1b98924: testing::TestInfo::Run()
... Google Test internal frames ...

contrib/config/test/kv_store_xds_delegate_integration_test.cc:360: Failure
Expected equality of these values:
  2
  test_server_->counter("xds.kv_store.load_success")->value()
    Which is: 1
Stack trace:
  0x1b97934: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1b977d4: testing::Test::Run()
  0x1b98924: testing::TestInfo::Run()
... Google Test internal frames ...

contrib/config/test/kv_store_xds_delegate_integration_test.cc:367: Failure
Expected equality of these values:
  "saz"
  getRuntimeKey("baz")
    Which is: ""
Stack trace:
  0x1b97934: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1b977d4: testing::Test::Run()
  0x1b98924: testing::TestInfo::Run()
... Google Test internal frames ...

unknown file: Failure
C++ exception with description "cannot bind '[::1]:45237': Address already in use" thrown in the test body.
[external/com_google_absl/absl/flags/internal/flag.cc : 115]
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=135269&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=67a76341-37f4-5b49-db38-acbb8a59af82&l=213

for some reason im not seeing any trace of this in azp analytics, not sure why

The issue would appear to be running out of (or trying to reuse currently active) ports

**Comment by phlax** [comment]
@alyssawilk this is an arm flake afaict - and is the symptom i was wondering about re the lds_integration test (altho i didnt find evidence so far in that case)

**Comment by adisuissa** [comment]
Thanks @phlax! If I find more related failures I'll post them here, so we can track this.
Do you know if it repeats over the same test?
cc @abeyad who may think of a reason that causes this flake.

**Comment by phlax** [comment]
>  Do you know if it repeats over the same test?

not sure iiuc but we dont test flakily in ci anymore but it is passing other times so we can be fairly sure its a flake - i didnt test locally

**Comment by abeyad** [comment]
Based on the error message, it seems like when we try to [shutdown the fake upstream and restart it](https://github.com/envoyproxy/envoy/blob/4b352da9c8496e536432a82d29b8ba0347c01941/contrib/config/test/kv_store_xds_delegate_integration_test.cc#L351), the restarted fake upstream tries to bind to a port already in use.  I'm guessing the problem may stem from some weird interaction in https://github.com/envoyproxy/envoy/blob/4b352da9c8496e536432a82d29b8ba0347c01941/contrib/config/test/kv_store_xds_delegate_integration_test.cc#L251-L252.

I'll assign this to myself and take a look.

**Comment by abeyad** [comment]
I'm able to reproduce this locally (fails a handful of times in 100 runs).  Will hopefully find the issue and get out a fix soon.
