### ISSUE TITLE
listeners should unlink() unix socket before binding to it

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#2697]
Most listeners don't support listening on unix sockets yet (https://github.com/envoyproxy/envoy/issues/1605), however the admin listener does.

One usability issue with this feature is that if you restart Envoy with the same configuration (including a hot restart) it will fail when it tries to bind to the unix socket. If Envoy calls `unlink()` on the socket just before binding it should fix the problem, although there may an interruption in traffic during a hot restart.

For the admin listener this behavior should be okay.

I might have time this weekend to look at how difficult a PR for this is if there's no opposition to implementing this

**Comment by syml** [comment]
Theoretically for regular unix sockets during hot restarts you could just pass the fd like it is done for regular sockets.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/pull/2701. @jmillikin-stripe can you take this issue into account also when you are doing your PR?

**Comment by jmillikin-stripe** [comment]
https://github.com/envoyproxy/envoy/pull/2701 tweaks the UNIX socket creation to move the `unlink()` into the initial bind, so (1) it can take over from an exited Envoy and (2) it should smoothly pass an open socket to the new Envoy during hot restart.
