### ISSUE TITLE
set listener to read_policy: REPLICA, but still seeing traffic going to master node

### ISSUE THREAD

**Issue by cq-liu** [envoyproxy/envoy#27006]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *set listener to read_policy: REPLICA, but still seeing traffic going to master node*

*Description*:
hi, I set the read_policy: REPLICA, but when I check the commands count to redis using query: avg(rate(redis_commands_total{cmd="get", "192.168.0.0"}[1m])), I still see a lot of commands sending to master node. May I know what could be the reason? Thanks.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by dceravigupta** [comment]
@cq-liu did you find any update on this problem? In my case, I'm seeing the other way around where Envoy is sending GET commands to replica nodes even though I have configure read_policy as MASTER.

I'm using envoy version 1.25.6
