### ISSUE TITLE
Do not reach into absl::strings_internal namespace

### ISSUE THREAD

**Issue by katzdm** [envoyproxy/envoy#2700]
Envoy currently utilizes `absl::strings_internal::memcasecmp()` from the [Abseil](http://github.com/abseil/abseil-cpp) project. This is contrary to the Abseil [Compatibility Guidelines](https://abseil.io/about/compatibility).

> Do not depend upon internal details. This should go without saying: if something is in a namespace or filename/path that includes the word “internal”, you are not allowed to depend upon it. It’s an implementation detail. You cannot friend it, you cannot include it, you cannot mention it or refer to it in any way.

Please remove all references to this API, and refrain from referencing any other symbols within the family of `absl::*_internal:: namespaces`. This will help Abseil to move their project forward in such a way that yours is not broken by future updates.

[Link to `absl::strings_internal::` usage](https://github.com/envoyproxy/envoy/blob/master/source/common/common/utility.cc#L137)

**Comment by athampy** [comment]
Hey @mattklein123, I can work on this.

**Comment by mattklein123** [comment]
@athampy. Cool, have at it.
