### ISSUE TITLE
Cannot drop traceparent header on upstream request

### ISSUE THREAD

**Issue by toddself** [envoyproxy/envoy#27038]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Cannot drop traceparent header on upstream request

*Description*:
When the opencensus tracer is enabled, it adds a `traceparent` header to the request and starts internal tracking of the request, however, it is not possible to remove the `traceparent` header when upstreaming to a host

*Repro steps*:
Repro steps, including configs,are located at https://github.com/toddself/envoy-traceparent-drop

However, configuring envoy to use OpenCensus and then configuring a route with `request_headers_to_remove` to include `traceparent` is the basic summary.

*Admin and Stats Output*:
GitHub said my comment was longer than 65,536 bytes so this data is in a gist:
https://gist.github.com/toddself/15ece3159fc233db16b5a54d01c000ac

(There was no `/routes` url that worked for the admin server, and the links to the docs don't document a `/routes` url either)

*Config*:
Config is located in the https://github.com/toddself/envoy-traceparent-drop repo

*Logs*:

```
{"protocol":"HTTP/1.1","method":"GET","response_code_details":"via_upstream","start_time":"2023-04-27T22:07:36.986Z","response_code":200,"path":"/test"}
```

*Call Stack*:

n/a

**Comment by adisuissa** [comment]
cc @wbpcode @Shikugawa @basvanbeek as OpenCensus code-owners

**Comment by wbpcode** [comment]
sorry, but I didn't get why you want to remove these headers?

`headers_to_remove` works before the tracing headers are injected. so it couldn't used to operate these tracing headers.
But you can try the `envoy.filters.http.header_mutation` filter and configured it as a upstream filter.

**Comment by toddself** [comment]
we have some ... non-optimal upstream servers that don't really like the traceparent headers we are adding.  we want to trace them for other systems we interact with still though.

it seems like `headers_to_remove` though should be capable of removing any header from a given request/response.

we'll give the header mutation filter a shot, thanks for the info!

**Comment by tkennedy1-godaddy** [comment]
as far as when tracing is injected, we notice also that the wasm filters are run prior to the tracing code being added -- is there a way to get the tracing information injected earlier for use in filters?

**Comment by wbpcode** [comment]
> as far as when tracing is injected, we notice also that the wasm filters are run prior to the tracing code being added -- is there a way to get the tracing information injected earlier for use in filters?

Sorry, these is no this way. We can only promise that the headers will be injected before the upstream filters is processed.
Except this, there is no any promise in processing order of tracing injection and downstream filters.
