### ISSUE TITLE
stats: allow combining configured tags with those supplied to counterFromStatNameWithTags

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27030]
The problem I'm facing is being able to add custom tags to a certain metrics, which their value is dynamic. Taking a counter stat for example, I would like to add a tag which its value is only being known at runtime. Ideally, when calling ``inc()``, on a counter, I would also like to provide that tag: ``inc(key, value)`` or ``inc(set_of_tags_with_values)``.

An example use case (although I wouldn't do this, but just to show what I mean in practice), is a call for ``inc("time", getCurrentTime())``, which is placed in ``onNewConnection()``. Here the time value varies, so every time ``onNewConnection()`` is being called, it gets a different value

Would it be possible to add an overload to ``inc()`` as in the example above to cope with this? Otherwise, I'll appreciate help figuring out this problem.

**Comment by kyessenov** [comment]
You can pass a tag vector to the counters, e.g. https://github.com/istio/proxy/blob/master/source/extensions/filters/http/istio_stats/istio_stats.cc#L736. The value can be any StatName, including pool allocated strings.

**Comment by ohadvano** [comment]
Thanks @kyessenov, I'm not sure if I got your suggestion correctly though, can you elaborate on the underlying process when doing so? An example with relevance to the example use case I showed in the original message would be useful (regarding time tag).

**Comment by kyessenov** [comment]
@ohadvano The example doesn't quite make sense, but the way you'd do it is:
1. Create a long living stats scope that holds all metrics with different tag vector combinations.
2. Create a stat name pool to define symbols for tag vector values - ideally during configuration, but can be done per request.
3. Create a stat with `counterFromStatNames` with symbols from the pool.
4. Increment the metric.

Take a look at grpc_stats filter for some examples - it's following this pattern.

**Comment by adisuissa** [comment]
cc @jmarantz

**Comment by ohadvano** [comment]
Thanks @kyessenov, I tried that approach and generally I was able to create a stat, however I encounter some problem which I'm not sure whether it's a bug or I have misunderstood how something works here.

In my .yaml, I am using ``stats_config.stats_tags`` to add general tags to all stats. If I create a stat using the following code, then the stat is created successfully with the general tags list added:

```
Stats::StatName name = config_->statsNamePool().add("test_stat");
config_->statsScope().counterFromStatNameWithTags(name, absl::nullopt).inc();
```

However, if I create the stat using the following code (which adds custom tags), then the ``tagExtractedName()`` is ``"test_stat"``, the ``name()`` is ``"test_stat.test_tag_key.test_tag_val"`` and the tags list only has ``"test_tag_key"`` tag, **omitting all the globally defined tags**:

```
Stats::StatName test_tag_key = config_->statsNamePool().add("test_tag_key");
Stats::StatName test_tag_val = config_->statsNamePool().add("test_tag_val-should-be-some-dynamic-value");
Stats::StatNameTagVector tags{{test_tag_key, test_tag_val}};

Stats::StatName name = config_->statsNamePool().add("test_stat");
config_->statsScope().counterFromStatNameWithTags(name, tags).inc();
```

Any idea why this happens and what can I do to fix this? cc @jmarantz

**Comment by jmarantz** [comment]
What's a *globally defined tag* and how would counterFromStatNameWithTags know about it?

**Comment by jmarantz** [comment]
Sorry, I misunderstood the context. I think you are expecting counterFromStatNameWithTags to combine with the config-based tags and the default tags, but I think that's not what it does.

I think it only uses the default and configured tags when the optional `tags` parameter is omitted.

**Comment by ohadvano** [comment]
> I think you are expecting counterFromStatNameWithTags to combine with the config-based tags

Yes.

> I think it only uses the default and configured tags when the optional tags parameter is omitted.

Seems like it, because when I don't specify the optional tags then I do get the config-based tags.
I am wondering isn't it expected that the tags would be combined?
Is there something that can be done on stat creation to support this merge of tags? (tags from code and config both).
Thanks @jmarantz

**Comment by jmarantz** [comment]
It doesn't seem too difficult but would require some mechanism to control whether the current behavior is preferred or the combined behavior. I would guess the control here should be a new optional flag provided to counterFromStatNameWithTags (and its 3 siblings for gauges, text-readouts, and histograms). It's going to be quite a bit of toil to do this for these 4 methods and the half-dozen or so derived classes of Stats::Scope, but it wouldn't be that hard.

If you decide to embark on this, please be sure to also make a parallel semantic change to isolated_store_impl.cc, which should be kept in sync as that's used for lots of tests.

The code controlling this is here: https://github.com/envoyproxy/envoy/blob/4dd9cbc306aa042eaeef1a14d908cd18adc801ca/source/common/stats/thread_local_store.cc#L428

You can see there it only calls the tag-producer to aggregate the well-known tags with the configured tags if the stat_names are not specified by API.

I can help review this.

**Comment by ohadvano** [comment]
Thanks @jmarantz, I'll try to get to work on this soon. Can we mark this is help-wanted until then so the issue wouldn't close itself?
