### ISSUE TITLE
Inconsistent CVE reporting documentation

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#27053]
*Title*: Inconsistent CVE reporting documentation

*Description*:
On https://github.com/envoyproxy/envoy/blob/main/SECURITY.md#security-reporting-process it says to send an email. If you go to "Create Issue", you get directed to https://github.com/envoyproxy/envoy/security/advisories/new though.

Which should be used to report CVEs these days? Is either fine?

Note: this is basically a nitpick, not a major concern at all

**Comment by adisuissa** [comment]
Thanks for pointing out this inconsistency.
I think the Github vulnerability reporting is a new feature, and we should better document it.

cc @envoyproxy/security-team for thoughts.

**Comment by phlax** [comment]
>  I think the Github vulnerability reporting is a new feature, and we should better document it.

yep, and probably make better use of it
