### ISSUE TITLE
Calculation of maxEjectionPercentage should be based on hosts after ejection, not prior to ejection

### ISSUE THREAD

**Issue by Punakshi** [envoyproxy/envoy#27066]
# Description
Currently, the configuration of the maxEjectionPercentage for hosts for Outlier Detection in Envoy behaves s.t the calculation of ejected hosts is done based on the percentage of ejected hosts prior to next ejection, not after ejection. This means that if the number of unhealthy hosts exceeds the configured max ejection percentage, Envoy will eject a number of hosts equivalent to the percentage of ejected hosts which will be greater than max ejection percentage, in certain scenarios (example scenario mentioned below).
However, this behavior can lead to unexpected ejections of hosts, especially in scenarios where a small number of hosts are being monitored.

## Current Behavior
For example, if there are 3 hosts and the max ejection percentage is set to 67%, if all 3 hosts are marked as unhealthy, all 3 will be ejected. This is because after the ejection of the second host, the percentage of ejected hosts will only be 66.67%, which is less than the configured max ejection percentage of 67%. But because the calculation is done based on the percentage of hosts prior to ejection, the remaining host will also be ejected, resulting in a complete outage.

## Proposed Behavior
To avoid these unexpected ejections, the calculation of ejected hosts should be done based on the percentage of hosts after ejection, not prior to ejection. This would ensure that Envoy only ejects hosts when the percentage of unhealthy hosts falls below the configured max ejection percentage post, and not prior to ejection. This would lead to more predictable behavior and fewer unexpected ejections of hosts.

Reference: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#ejection-algorithm

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/issues/26877

**Comment by Punakshi** [comment]
Closing as issue is already acknowledged and being worked upon in #26877
