### ISSUE TITLE
Reusing build outputs when running coverage

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27064]
I have a build pipeline which runs in a project similar to https://github.com/envoyproxy/envoy-filter-example/tree/main that firsts builds the sources using ``bazel build //internal:envoy``, then runs coverage with ``bazel coverage //internaltests/...``. However, the sources are being built twice, and it seems like the coverage step does not use the already built outputs. Is there a way to make bazel use the build outputs from the first step and only build and run the test code during coverage step?

**Comment by keith** [comment]
You would have to build the envoy executable with coverage enabled, because enabling coverage flips on some compiler flags that invalidates the build outputs. You can try flipping this flag https://bazel.build/reference/command-line-reference#flag--collect_code_coverage for your build command, but that will have an impact on code size, and maybe compiler optimizations, so you wouldn't want to do that for your release builds

**Comment by ohadvano** [comment]
Thanks @keith but I tried this and it doesn't seem to have an effect:
```
bazel build --collect_code_coverage //internal:envoy
bazel coverage //internaltest/...
```

**Comment by phlax** [comment]
my reading of ...

```console
$ git grep coverage .bazelrc
.bazelrc:coverage --config=coverage
.bazelrc:coverage --build_tests_only
.bazelrc:build:coverage --action_env=BAZEL_USE_LLVM_NATIVE_COVERAGE=1
.bazelrc:build:coverage --action_env=GCOV=llvm-profdata
.bazelrc:build:coverage --copt=-DNDEBUG
.bazelrc:build:coverage --test_timeout=390,750,1500,5700
.bazelrc:build:coverage --define=dynamic_link_tests=true
.bazelrc:build:coverage --define=ENVOY_CONFIG_COVERAGE=1
.bazelrc:build:coverage --cxxopt="-DENVOY_CONFIG_COVERAGE=1"
.bazelrc:build:coverage --coverage_support=@envoy//bazel/coverage:coverage_support
.bazelrc:build:coverage --test_env=CC_CODE_COVERAGE_SCRIPT=bazel/coverage/collect_cc_coverage.sh
.bazelrc:build:coverage --test_env=HEAPCHECK=
.bazelrc:build:coverage --combined_report=lcov
.bazelrc:build:coverage --strategy=TestRunner=sandboxed,local
.bazelrc:build:coverage --strategy=CoverageReport=sandboxed,local
.bazelrc:build:coverage --experimental_use_llvm_covmap
.bazelrc:build:coverage --collect_code_coverage
.bazelrc:build:coverage --test_tag_filters=-nocoverage
.bazelrc:build:coverage --instrumentation_filter="//source(?!/common/quic/platform)[/:],//envoy[/:],//contrib(?!/.*/test)[/:]"
.bazelrc:build:test-coverage --test_arg="-l trace"
.bazelrc:build:fuzz-coverage --config=plain-fuzzer
.bazelrc:build:fuzz-coverage --run_under=@envoy//bazel/coverage:fuzz_coverage_wrapper.sh
```

is that

```console
$ bazel build --config=coverage //internal:envoy
...

```

_might_ work

**Comment by keith** [comment]
ah yea since we also add a bunch of custom stuff we need that too, my bad, the flag i mentioned would fix it f or raw bazel only

**Comment by ohadvano** [comment]
yup that worked, thanks @phlax
