### ISSUE TITLE
Incorrect checksum hash in Github Release

### ISSUE THREAD

**Issue by hbagdi** [envoyproxy/envoy#27131]
*Title*: Incorrect checksum hash on GitHub releases

*Description*:

Checksum Hash listed in GitHub release asset is SHA-512 while the one being used is SHA-256.
Example: https://github.com/envoyproxy/envoy/releases/tag/v1.26.1

*Repro steps*:

Download the checksum file.

**Comment by phlax** [comment]
the files are hashed with sha256, and the message is hashed and signed with sha512 (the gpg default)

i think this is a reasonable scheme

**Comment by phlax** [comment]
i think this is an issue of documentation which i will follow up on in #27179 

im gonna close this issue, but if you think there is something we can improve with our signing process @hbagdi please do reopen
