### ISSUE TITLE
Exposing Statistics (Metrics) / Enable Tracing from Golang Filters

### ISSUE THREAD

**Issue by subzerobo** [envoyproxy/envoy#27152]
Is there any way to introduce statistics from the filters that are written using Golang for the envoy proxy? 

the native c filters are able to expose statistics for instance: [aws_request_signing_filte](https://www.envoyproxy.io/docs/envoy/v1.26.1/configuration/http/http_filters/aws_request_signing_filter.html#statistics), but I couldn't find an option for that in the go examples

**Comment by yanavlasov** [comment]
@doujiang24 @wangfakang for comments as owners

**Comment by doujiang24** [comment]
Hello @subzerobo 
There isn't a way yet, but it could be possible, and a bit complicated.
that means we need to declare stats keys in Golang, while parsing the filter config in Golang, and update the stats values during the golang filter processing a stream.

**Comment by doujiang24** [comment]
Hi @subzerobo 

Sorry to mislead you. it does not support stats yet. what I said above is just a bit of design.

> so maybe we need to expose a way to allow developers configure this stats from golang and some methods to update the values for them?

yep, that's it, but it might be a bit complicated to implement it.

**Comment by doujiang24** [comment]
@phlax please add a no stalebot for it, it's useful and we are going to implement it eventually, thanks.

**Comment by doujiang24** [comment]
here are my thoughts:
1. a C++ API to add metrics values (i.e. Counter) dynamically, those metrics values store in the C++ filter config, and return a number type id.
   see basic APIs: envoy/stats/stats_macros.h
2. an Go API that could be used in filter config parse phase, so that Go could invoke that C++ API, to add a metric dynamically, and get a number id as a reference.
3. another C++ API to manipulate those metrics values in the C++ side, it accept the number id as reference. so that another Go API could manipulate those metrics in Go side.

simple conclusion:
people could add metrics dynamically, during parse filter config in Go side.
and manipulate metrics dynamically while processing request.

**Comment by StarryVae** [comment]
WASM extension has already supports metric api and i have tried to implement in our Lua extension, maybe we can refer to wasm as well in go extension?

**Comment by doujiang24** [comment]
@StarryVae Cool, could you please show a simple design?

**Comment by StarryVae** [comment]
> 

cc @doujiang24  sorry for late reply, it's generally similar to this design:

https://github.com/envoyproxy/envoy/blob/2311e03d91b146db83bac4c03f50aed4b7cf5e74/source/extensions/common/wasm/context.h#L251

Here `defineMetric` is just a C++ API to add metrics values(including Counter, Gauge, Histogram) as mentioned above, and `incrementMetric`, `recordMetric` are C++ APIs to manipulate those metrics values. Of course, these metrics are stored in a thread local slot of the C++ filter config.

**Comment by StarryVae** [comment]
> here are my thoughts:
> 
> 1. a C++ API to add metrics values (i.e. Counter) dynamically, those metrics values store in the C++ filter config, and return a number type id.
>    see basic APIs: envoy/stats/stats_macros.h
> 2. an Go API that could be used in filter config parse phase, so that Go could invoke that C++ API, to add a metric dynamically, and get a number id as a reference.
> 3. another C++ API to manipulate those metrics values in the C++ side, it accept the number id as reference. so that another Go API could manipulate those metrics in Go side.
> 
> simple conclusion: people could add metrics dynamically, during parse filter config in Go side. and manipulate metrics dynamically while processing request.

cc @doujiang24  sorry for late reply, it's generally similar to this design:

https://github.com/envoyproxy/envoy/blob/2311e03d91b146db83bac4c03f50aed4b7cf5e74/source/extensions/common/wasm/context.h#L251

Here `defineMetric` is just a C++ API to add metrics values(including Counter, Gauge, Histogram) as mentioned above, and `incrementMetric`, `recordMetric` are C++ APIs to manipulate those metrics values. Of course, these metrics are stored in a thread local slot of the C++ filter config.

**Comment by doujiang24** [comment]
lgtm, do you want to have a try? @StarryVae

**Comment by StarryVae** [comment]
yes, thanks.

**Comment by soellman** [comment]
Is there anything more to do here?

I've successfully used the metrics implementation added in #28689. I initially was confused and thought that this issue was still relevant.

**Comment by doujiang24** [comment]
Oh, it could be close now. cc @phlax Thanks
