### ISSUE TITLE
How to sanitize `x-envoy-original-dst-host` header

### ISSUE THREAD

**Issue by ikimonogakari** [envoyproxy/envoy#27158]
# How to sanitize `x-envoy-original-dst-host` header, which is used in a orignal_dst cluster?

**Description**:
I am setting `x-envoy-original-dst-host` request header to have original_dst cluster to forward to the desired destination.
Based on the [doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-originaldstlbconfig-use-http-header), this header is not removed automatically.
However, I want to remote that header, before sending the request out.

I have investigated into several options:
1. Specify `request_headers_to_remove` in the [route config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-route)
   * Pros:
      * Can apply only to the route which selects the original_dst cluster.
   * Cons:
      * The header is removed before original_dst cluster reads it.
1. Add [`extensions.filters.http.header_mutation.v3.Mutations`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/header_mutation/v3/header_mutation.proto#extensions-filters-http-header-mutation-v3-mutations) filter in the   `upstream_http_filter` of the [`extensions.filters.http.router.v3.Router`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto#extensions-filters-http-router-v3-router).
   * IIUC, this `upstream_filter` will be applied for all routes under the same filter_chains. Although there is [`extensions.filters.http.header_mutation.v3.HeaderMutationPerRoute`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/header_mutation/v3/header_mutation.proto#extensions-filters-http-header-mutation-v3-headermutationperroute), I cannot find where it should be applied in a route config.
   * Also, I cannot confirm this removal will happen after original_dst cluster reads the header.
1. [HTTP header sanitizing](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing)
   * This doesn't include `x-envoy-original-dst-host`, and has no option to add additional headers.
   * Also not clear whether this sanitization happens after original_dst reads.

Any idea about how the removal can be implemented just using config?

**Comment by yanavlasov** [comment]
Option 2 could work. You are correct that it will be removed for all routes with the filter chain, as I do not think we have per route configuration for upstream filters.

**Comment by ikimonogakari** [comment]
Thanks for your reply.

I am still curious where should [`extensions.filters.http.header_mutation.v3.HeaderMutationPerRoute`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/header_mutation/v3/header_mutation.proto#extensions-filters-http-header-mutation-v3-headermutationperroute) be applied then? Not in the upstream filter?
