### ISSUE TITLE
typo in well_known__names.cc: dyanmo_table vs dynamo_table

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#2716]
*Description*:
I'm not sure if this would cause downstream issues if this is fixed.  Typo is in https://github.com/envoyproxy/envoy/blob/b6b15645e1bc740d5280dee4561ff3a3cb0cc5fa/source/common/config/well_known_names.h#L269

**Comment by htuch** [comment]
Probably should fix it, but will leave this open for a little while in case anyone objects.

**Comment by mattklein123** [comment]
I would go ahead and just fix. Thanks @jmarantz
