### ISSUE TITLE
Name of `use_remote_address` is confusing because it's actually about the proxy headers

### ISSUE THREAD

**Issue by jmillikin-stripe** [envoyproxy/envoy#2718]
*Description*:
While debugging mysterious behavior that turned out to be https://github.com/envoyproxy/envoy/issues/2638, I was very confused about how the `use_remote_address` field affected HTTPS behavior. It turns out that this field's true behavior is to set whether the `X-Forwarded-*` headers are trusted or not.

Given that incorrectly trusting these headers can be a security risk, and the strange interactions between `require_tls` and `X-Forwarded-Proto`, it would be nice if the `use_remote_address` field was renamed to something that more accurately described its purpose.

Ideas: `trust_x_forwarded_for`? `trust_downstream_proxy`? Something else in that direction?

**Comment by htuch** [comment]
The style guide doesn't allow for renaming of fields that have been frozen, see https://github.com/envoyproxy/data-plane-api/blob/master/STYLE.md. This is primarily due to JSON/YAML wire format compatibility concerns. Maybe we can improve docs to help reduce confusion, any suggestions here?

**Comment by mattklein123** [comment]
+1, let's not rename this field. It will cause too much pain. Doc improvements greatly appreciated. cc @brian-pane who has also worked in this area recently.
