### ISSUE TITLE
Mobile RBE is failing with `RESOURCE_EXHAUSTED: No available CAS nodes`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27213]
https://github.com/envoyproxy/envoy/actions/runs/4893901771/jobs/8737597271?pr=27211#step:5:271

**Comment by ulfjack** [comment]
Thanks for the bug report. There was a brief cluster outage at the time of the build, after which the cluster recovered and was able to serve traffic again.

There was a combination of issues that happened at around the same time and caused an unusually long delay in worker startup during which those workers were not accepting file uploads:
- Just before the build, AWS was unable to provision spot instances in the regions the cluster is running in
- The cluster automatically provisioned on-demand instances to cover for that time
- A few minutes later, spot instances became available again, and started to pull the docker image used for these builds from the on-demand instances; instances pull the most recently used docker image *before* they start accepting work or file uploads
- However, the cluster shut down the on-demand instances before the docker image transfer could complete
- The spot instances then fell back to pulling the docker image from Dockerhub (which took ~5 minutes as the image is ~12 GB in size)
- At that point, some of the instances became available and the cluster recovered

We are taking steps to reduce the likelihood of this happening again in the future.

**Comment by ulfjack** [comment]
The new release was rolled out a while ago. This can be closed now (looks like I don't have permissions to do so).
