### ISSUE TITLE
Support for Multicast messages in service to service communication

### ISSUE THREAD

**Issue by srujann** [envoyproxy/envoy#2721]
This is a feature request to be able to send a multicast request to all instances of a service using Envoy with Service Discovery. 

This would be useful for cases like a fully replicated cache, where cache update one node needs to be multicasted to all other nodes.

Desired behavior:
- Multicast request indicated to envoy probably through a header.
- Usable with gRPC (HTTP2).
- Request can be best effort without any retries by default or with configurable retries. Any failure to one of the multicast nodes would return request failure.

**Comment by htuch** [comment]
How does service discovery figure into this?

**Comment by srujann** [comment]
I wasn't clear about this earlier. The intention is that multicast request would be sent with service name and Envoy would query service discovery for all instances of this service to use that as destination pool of multicast request.

**Comment by htuch** [comment]
Sounds like an interesting feature. I think a design doc or more detailed inline proposal would be the next step here.

**Comment by mattklein123** [comment]
@srujann agree with @htuch that a design doc would be useful here. This isn't hard to implement but it's not trivial either. I would probably implement along the lines of the shadow writer in the router and create the ability to fire and forget the request to all of the healthy backends.
