### ISSUE TITLE
provide generic ability to set additional attributes for generated cookies

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#27234]
Currently there is no ability to set additional attributes like `SameSite=None` and `Secure` for the cookies generated by Envoy. 

It would be good to add a generic ability to customize the cookie.

Couple of approaches

-  Add a new field in [Cookie](https://github.com/envoyproxy/envoy/blob/a3ac3e4d6bbebaf3e107f526ae0857020f98d963/api/envoy/type/http/v3/cookie.proto#L19) like `append_additional_attributes`  which is a string field that people can set following cookie conventions. Envoy can append them while generating cookie. This has risk of these not following the formatting standard , so the onus is not user to configure properly
- Add a new field in  [Cookie](https://github.com/envoyproxy/envoy/blob/a3ac3e4d6bbebaf3e107f526ae0857020f98d963/api/envoy/type/http/v3/cookie.proto#L19) like `enable_additional_attributes` when this is set to true, Envoy would pass the generated cookie in the initial request as is to upstream allowing it to modify with additional attributes and use the same if it is available in upstream headers, when sending it back to downstream. 

Any other approaches?

Previous related issue https://github.com/envoyproxy/envoy/issues/12970

**Comment by ramaraochavali** [comment]
The same can be implemented for stateful sessions.

**Comment by RyanTheOptimist** [comment]
cc: @wbpcode @cpakulski

**Comment by cpakulski** [comment]
Do cookie attributes represent a finite set of keywords? 
If yes, then they may be represented as enum, instead of user entered string (as you indicated this is error prone).

**Comment by ramaraochavali** [comment]
>Do cookie attributes represent a finite set of keywords?

They are finite but hard to configure via Enum I guess

How about second approach?

**Comment by wbpcode** [comment]
I Prefer the Enum one or just create a new message `CookieProperties` or something.

**Comment by ramaraochavali** [comment]
> I Prefer the Enum one or just create a new message CookieProperties or something.

@wbpcode Are you thinking of supporting well known/mostly used attributes as Enum?

**Comment by wbpcode** [comment]
> > I Prefer the Enum one or just create a new message CookieProperties or something.
> 
> @wbpcode Are you thinking of supporting well known/mostly used attributes as Enum?

Yes.

**Comment by ramaraochavali** [comment]
I think this `CookieAttributes` may be better than Enum and is more extensible. We can have a `repeated CookieAttributes` and whatever is specified, we can append to the cookie.  WDYT?

**Comment by wbpcode** [comment]
both enum and new message are acceptable for me. 😸

**Comment by amol2311** [comment]
@ramaraochavali I was following #12970,  so with this change how can I use this cookie attribute , could you pls provide some sample to use it? is it something we can directly use in destination rule or need to write envoy filter?

**Comment by ramaraochavali** [comment]
You can not use directly with Destination rule. You have to use envoy filter and update the config generated by Istio
