### ISSUE TITLE
Weighted load balancing

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2725]
We have a need for weighted LB that respects the (v2) locality weighting in addition to endpoint weighting. This needs to work initially for RR and Maglev LB, but eventually we would like any implementation to generalize to all LBs (at least at the locality level). This issue will track design discussion and implementation work. 

We can weight RR via replication of hosts in the queue, at the expense of some memory use. Similarly, while populating the Maglev table, a similar approach can be taken.

One fundamental design question is whether we have true two-level hierarchical weighted LB (first pick locality, then pick endpoint within locality) or flat LB (combined locality weight and intra-locality endpoint weight for a single weight). Flat LB is conceptually simple, but may be expensive in terms of memory cost when we have a wide range of LB weights that combined weighting would imply. By having true hierarchical LB, we also get "for free" locality weighted LB for LBs that don't support weighting. The downside is we will need to implement at least a simple weighted locality LB and a consistent hash locality LB to support affinity and non-affinity second-level LBs.

I think based on the above it makes sense to do hierarchical LB. If this makes sense, I can work on weighted RR as a first step.

@mattklein123 @zuercher @alyssawilk WDYT?

**Comment by mattklein123** [comment]
> I think based on the above it makes sense to do hierarchical LB. If this makes sense, I can work on weighted RR as a first step.

Agreed. I think we should do a first stage locality weighting pass during selection that I think should be easily generalizable across all LBs.

@htuch for 2nd level weighting, do you mind updating this with our offline convo? (Maglev and Ketama are both straightforward, RR is straightforward at the expense of memory, LR is tricky and the crappy implementation we have now needs to be replaced).

**Comment by htuch** [comment]
From earlier conversations with @mattklein123:
*  Basically for ketama just use the weights to adjust the replication factor for each host. For Maglev, during table population round robin use the weights to alter how often a host is used for selecting a slot.
* I haven’t thought about it that much but I think the power of 2 load balancer could be made to more correctly work with weights by biasing the selection based on both active requests and host weight. You could model it pretty easily to see how well it works.
