### ISSUE TITLE
xadd with * adding two same data entries for one command in redis envoy proxy

### ISSUE THREAD

**Issue by shankar4322** [envoyproxy/envoy#27273]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: xadd with * adding two same data entries for one command*

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
i am using below config for my redis i.o communication through envoy for redis db
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/redis_proxy_filter

i am on streams data.
below are the streams commands.
xadd stream * name alex age 20
if i execute below commands on redis node directly ,then  it writes only one recordin the stream but if i add  using xadd
through envoy redis proxy its creating 2 records one duplicate and one original .
below is sample commands output.
is this a bug in envoy for streams or does anyone faced similar issue and got it working?
10.10.84.127:10001> XADD TESTSTREAM *  Name Alex Age 20
"1683632600580-1"
10.10.84.127:10001> XLEN TESTSTREAM
(integer) 2
10.10.84.127:10001> XRANGE TESTSTREAM - +
1) 1) "1683632600580-0"
   2) 1) "Name"
      2) "Alex"
      3) "Age"
      4) "20"
2) 1) "1683632600580-1"
   2) 1) "Name"
      2) "Alex"
      3) "Age"
      4) "20"
10.10.84.127:10001>

**Comment by shankar4322** [comment]
any updates here??
please check it asap

**Comment by weisisea** [comment]
It seems that XADD is currently not supported in Envoy:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/common/redis/supported_commands.h

We should expect to receive "unsupported command" error when sending XADD to Envoy.

Could 10.10.84.127:10001 be Redis server instead of Envoy?

**Comment by shankar4322** [comment]
we modified that file to add those few streams commands and recompiled and using it.
its in envoy not redis server

**Comment by weisisea** [comment]
Could you please paste the content of Envoy config file? I wonder whether the Redis server is also being used as a mirror, causing the command to be executed twice. Could you please also try `INCR` command and see whether it can also be executed twice?

**Comment by shankar4322** [comment]
10.10.10.10:1001> SET mykey "10"
OK
10.10.10.10:1001> get mykey
"10"
10.10.10.10:1001> INCR mykey
(integer) 11
10.10.10.10:1001> get mykey
"12"

you are right its adding 2 times for INCR command as well

**Comment by weisisea** [comment]
It seems that in the configuration, you are using the same redis cluster as mirror upstream. Could you please try removing **request_mirror_policy** from the configuration?

**Comment by shankar4322** [comment]
@weisisea thanks for the solution . it works .
