### ISSUE TITLE
Get "upstream connect error" from dispatch_http_call method in wasm

### ISSUE THREAD

**Issue by LugiaChang** [envoyproxy/envoy#27311]
*Title*: *"upstream connect error or disconnect/reset before headers. reset reason: connection termination" from dispatch_http_call method in wasm plugin*

*Description*:
>I call a `dispatch_http_call` in the `on_configure` stage of my wasm plugin to retrieve the business routing configuration. However, in `on_http_call_response`, I **sometimes** receive the error "upstream connect error or disconnect/reset before headers. reset reason: connection termination". I'm sure my upstream server didn't crash, so I'm not sure what's causing this.
I'm not sure if this issue should be raised on the proxy-wasm-rust-sdk side, but it seems like there may also be a problem with the tinygo.

*Code*:
```
fn on_configure(&mut self, _: usize) -> bool {
      if let Some(config_bytes) = self.get_plugin_configuration() {
          if str::from_utf8(&config_bytes).is_err() {
              return false;
          }
          let t: WasmConfiguration = serde_json::from_str(str::from_utf8(&config_bytes).unwrap()).unwrap();
          
          let rsp = self.dispatch_http_call(t.cluster.as_str(), 
              vec![
                      (":method", "GET"),
                      (":path", t.path.as_str()),
                      (":authority", t.host.as_str()),
                      ("accept", "*/*"),
                      ("x-wasm-plugin-config-name", t.name.as_str()),
                  ], 
              None, 
              vec![], 
              Duration::from_secs(5));
          
          self.wasm_configuration = Rc::new(t);

          match rsp {
              Ok(_) => {
                  return true;
              }
              Err(st) => {
                  warn!("http call status: {:?}", st);
                  return false;
              }
          }
      } else {
          return false;
      }
  }
...
...
fn on_http_call_response(
        &mut self,
        _token_id: u32,
        _num_headers: usize,
        _body_size: usize,
        _num_trailers: usize,
    ) {
        let config_bytes: Vec<u8> = match self.get_http_call_response_body(0, _body_size) {
            Some(config_bytes) => config_bytes,
            None => {
                panic!("no http call response");
            }
        };
        let rsp: Result<PluginConfiguration, serde_json::Error> = serde_json::from_str(str::from_utf8(&config_bytes).unwrap());
        match rsp {
            Ok(t)=> {
                self.configuration = Rc::new(t);
            }
            Err(e) => {
                panic!("data:{} err:{}", str::from_utf8(&config_bytes).unwrap(), e)
            }
        }
        
    }
```
*Output*:
>I panic when I got error.
```
2023-05-10T06:29:12.167376Z	critical	envoy wasm	wasm log zonesvr-mesh-935388: panicked at 'data:upstream connect error or disconnect/reset before headers. reset reason: connection termination err:expected value at line 1 column 1', src/lib.rs:62:17
2023-05-10T06:29:12.167705Z	error	envoy wasm	Function: proxy_on_http_call_response failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0x29f55 - __rust_start_panic
  1:  0x29f38 - rust_panic
  2:  0x29f08 - _ZN3std9panicking20rust_panic_with_hook17hb09154fa23e06c37E
  3:  0x29521 - _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h6091c197f0d08bf0E
  4:  0x29460 - _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h004afb3e6a867c40E
  5:  0x29b9f - rust_begin_unwind
  6:  0x2b22a - _ZN4core9panicking9panic_fmt17h9e229748e3ae9f9dE
  7:  0xda8e - _ZN70_$LT$route..HttpHeadersRoot$u20$as$u20$proxy_wasm..traits..Context$GT$21on_http_call_response17h85e4c5782c224c75E
  8:  0x1d543 - _ZN10proxy_wasm10dispatcher10Dispatcher21on_http_call_response17h0a7ab49d79b48ea3E
  9:  0x20fcf - proxy_on_http_call_response
```

**Comment by LugiaChang** [comment]
> If you run envoy at trace level, you should see the reason for envoy connection termination.

I will try. 
Another question is whether the retryOn setting in the route will take effect on the HTTP requests initiated in wasm?

**Comment by LugiaChang** [comment]
> If you run envoy at trace level, you should see the reason for envoy connection termination.
<img width="813" alt="image" src="https://github.com/envoyproxy/envoy/assets/22168057/4bb9e15f-bb65-41f5-8c87-d5661a194b30">
I got "remote close". 
My upstream is an http server written in golang. I noticed that after each request, the server does not actively maintain the connection and instead displays a TIME_WAIT state by `netstat -an`. Is this because wasm still uses old connections, resulting in errors? Would setting an IdleTimeout for the server have any effect?

**Comment by kyessenov** [comment]
Interesting, TIME_WAIT might mean there's a kernel level problem due to how istio rewrites packets (see https://github.com/istio/istio/issues/36765). This happens with multiple ports on the same IPs, which can get mixed up between connections. 

The best way around L4 issues is to use better application level framing. If you switch to h2, you might have a better luck with Envoy recognizing a broken connection.

**Comment by LugiaChang** [comment]
> Interesting, TIME_WAIT might mean there's a kernel level problem due to how istio rewrites packets (see [istio/istio#36765](https://github.com/istio/istio/issues/36765)). This happens with multiple ports on the same IPs, which can get mixed up between connections.
> 
> The best way around L4 issues is to use better application level framing. If you switch to h2, you might have a better luck with Envoy recognizing a broken connection.

I'm sorry, I don't fully understand yet. Do you mean switch dispatch_http_call to http2? 
My http server does not have an istio-proxy sidecar. The istio kernel issue is on the client(wasm) side?

**Comment by xugy99** [comment]
Hi @LugiaChang , I see almost the identical issue as you saw, may I know how you resolved this issue eventually?

**Comment by harish1996** [comment]
> No, the async calls don't use retries, timeouts, or any other route-specific settings. 

I am curious whether retries work if we specify it through the headers like the ones mentioned in https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#http-headers-consumed-from-downstreams ?
