### ISSUE TITLE
Set Build Flags for V8 ?

### ISSUE THREAD

**Issue by rahulchaphalkar** [envoyproxy/envoy#27326]
*Title*: *How to set build flags that are available in v8?*

*Description*:
V8's BUILD.bazel has several flags available for building it, as seen here https://github.com/v8/v8/blob/main/BUILD.bazel#L131
What is the best way to configure these flags while building envoy? Is there a way to pass these to the v8 build?

One way would be to utilize v8.patch file, however that would hardcode these flag settings.

Related Question - If a new bazel flag for v8 is added via v8.patch, how would one enable that from envoy while building?

**Comment by RyanTheOptimist** [comment]
cc: @phlax

**Comment by rahulchaphalkar** [comment]
I think I've found the way - 

- Add envoy bazel build options/flags via `bazel/BUILD` 
- Add macros/rules to `bazel/envoy_build_system.bzl` and `bazel/envoy_select.bzl` 
- Change `v8.patch` to have v8's BUILD.bazel contain `select` statements to configure sources/deps (somewhat similar to `--define=no_debug_info=1` is supported in v8).

**Comment by phlax** [comment]
sounds reasonable - i wasnt sure of the answer to your question, altho had a quick look - but this seems a good way forward

cc @mpwarres @PiotrSikora

**Comment by mpwarres** [comment]
Duplicate of #27710
