### ISSUE TITLE
access opaque_config in lua filters

### ISSUE THREAD

**Issue by nmnellis** [envoyproxy/envoy#2733]
*Title*: *Access opaque_config in lua filters*

*Description*:
> It is stated that you can add opaque_config to routes that require per-route filtering but it does not seem that lua filters have access to the opaque_config values.

[optional *Relevant Links*:]
>opaque_config commit https://github.com/envoyproxy/envoy/commit/d162bcca9b60da4726f85ff5258b86df5f6729f1
> initial per route filter issue https://github.com/envoyproxy/envoy/issues/413

**Comment by nmnellis** [comment]
@dio comments from slack
I think this is an opportunity to add that to v2 (since I'm not aware we have v2 support for `opaque_config`). And I guess the opaque config should be explicitly "fetched" from the current route.

e.g. in here: https://github.com/envoyproxy/envoy/blob/master/source/common/http/filter/lua/lua_filter.h#L238

We should call the:

```c++
Router::RouteConstSharedPtr route = decoder_callbacks_.callbacks_->route();
    if (route != nullptr) {
      const Router::RouteEntry* route_entry = route->routeEntry();
      auto opaque_config = route_entry->opaqueConfig();
    }
```


And populate that `opaque_config` to the lua world.

**Comment by dio** [comment]
I think after skimming the doc, we can use [metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto.html#core-metadata) instead.

**Comment by mandarjog** [comment]
If it is easily possible we should support both opaque config and metadata. Else full use of lua filters is immediately predicated on v2. Doing any serious experimentation needs access to the currently selected route and related info.

**Comment by htuch** [comment]
`opaque_config` is v1 only and deprecated. I would vote to make this a v2 only feature, v1 is going to turned down in coming months/releases, so we should avoid adding complexity and engineering work that has a limited life span.

**Comment by htuch** [comment]
Does someone want to own this work or should I mark this help wanted?

**Comment by mattklein123** [comment]
The main issue here is going to be figure out the right mapping from metadata to Lua but I think this should be relatively easily doable using a Lua table.

**Comment by dio** [comment]
@mattklein123 Nice insight on Lua table indeed. What was in my mind: simple API just like `headers:get` but with filter and key `metadata:get("foo.bar.meta", "foo")` by adding `MetadataMapWrapper::luaGet`, calling `Config::Metadata::metadataValue()` inside it, but obviously that's not enough.

**Comment by dio** [comment]
@nmnellis @mattklein123 I put a preliminary work on this at https://github.com/envoyproxy/envoy/pull/2775 if you have time please have a look. Thanks!
