### ISSUE TITLE
Mobile android tests are permafailing since bazel 6.2 upgrade

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27339]
It wasnt immediately apparent as the ci can be a bit flakey anyway, but it seems the bazel 6.2 upgrade has broken the mobile java toolchain (on mac at least)

im not too familiar with the setup here, but will see if i can find any clues

**Comment by phlax** [comment]
cc @daixiang0 @alyssawilk @keith

**Comment by phlax** [comment]
fail log https://github.com/envoyproxy/envoy/actions/workflows/mobile-android_tests.yml?query=branch%3Amain

**Comment by phlax** [comment]
https://github.com/bazelbuild/rules_java/issues/64

https://github.com/bazelbuild/bazel/issues/17085

**Comment by phlax** [comment]
i guess we can close this - the upgrade has been reverted for now - pr to upgrade again is here #27353

**Comment by alyssawilk** [comment]
@phlax as a follow up we should turn up E-M CI for deps bumps

**Comment by phlax** [comment]
> as a follow up we should turn up E-M CI for deps bumps

yeah, i added that for bazel version in my pr to revert the revert #27353

**Comment by alyssawilk** [comment]
yay!  you're the best :-)
