### ISSUE TITLE
golang filter: add FilterState API

### ISSUE THREAD

**Issue by doujiang24** [envoyproxy/envoy#27365]
Here is the API design:
```
type StreamInfo interface {
	filterState() FilterState
}

type StateType int
type LifeSpan int
type StreamSharing int

var (
	StateTypeMutable StateType = 0
	// more

	LifeSpanRequest LifeSpan = 0
	// more

	SharedWithUpstreamConnection StreamSharing = 0
	// more
)

type FilterState interface {
	SetString(key, value string, mutable StateType, lifespan LifeSpan, streamSharing StreamSharing)
	GetString(key string) string
}
```

similar to the C++ API: https://github.com/envoyproxy/envoy/blob/main/source/common/stream_info/filter_state_impl.h#L15
but, we only support string as value now, for the simple implementation as the first step.

use case, for example:
we could set value into filterstate with `SharedWithUpstreamConnection`, then, it could be shared through internal listener.
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters

**Comment by StarryVae** [comment]
sure, i will try to do this, thanks. ❤️

**Comment by StarryVae** [comment]
A small question, `std::shared_ptr<Object> data`, should we create a class  that inherits from `Object`? and what should this class look like? thanks. cc @doujiang24

**Comment by StarryVae** [comment]
Just like this ?

```
class GoState : public StreamInfo::FilterState::Object {
public:
  GoState(std::string& value) : value_(value) {}
  const std::string& value() const { return value_; }

private:
  const std::string value_;
};
```

**Comment by doujiang24** [comment]
yep, that's it. @StarryVae

**Comment by doujiang24** [comment]
implemented in https://github.com/envoyproxy/envoy/pull/27513 and https://github.com/envoyproxy/envoy/pull/27864, closing it.
