### ISSUE TITLE
Failed building wasm filter in examples/wasm-cc as root

### ISSUE THREAD

**Issue by MrHate** [envoyproxy/envoy#27363]
*Title*: *Failed building wasm filter as root*

*Description*:
When I was reproducing the example in `examples/wasm-cc`, [one step](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/wasm-cc#step-3-compile-the-updated-filter) was to build the *update* version wasm filter binary by running `docker compose -f docker-compose-wasm.yaml up --remove-orphans wasm_compile_update`. The guide says, `export UID` is required for bazel's certain cache mechanism unfamiliar to me. Without doing this, building failed for permission issue. While after exporting `UID`, building still failed and complained `usermod: UID '0' already exists`.

Is there any solution except for switching to a non-root user?

*Relevant Link*:
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/wasm-cc

**Comment by ggreenway** [comment]
cc @phlax @mpwarres @mathetake @lizan

**Comment by phlax** [comment]
putting aside the wisdom of running and building essentially untrusted code as root

the entrypoint for the build container in the examples is a bit hacky https://github.com/envoyproxy/envoy/blob/84641e16b1ca556f3d7dde0b105cca66a398176a/examples/shared/build/build-entrypoint.sh#L5-L8

and assumes the user doesnt exist already - which in most cases is a fair assumption

wrt to switching to root - that would require something different as root already exists - obv we could just remain as root and there would be no need to change any perms etc - but im not sure thats something we want to add

**Comment by MrHate** [comment]
> putting aside the wisdom of running and building essentially untrusted code as root
> 
> the entrypoint for the build container in the examples is a bit hacky
> 
> https://github.com/envoyproxy/envoy/blob/84641e16b1ca556f3d7dde0b105cca66a398176a/examples/shared/build/build-entrypoint.sh#L5-L8
> 
> and assumes the user doesnt exist already - which in most cases is a fair assumption
> 
> wrt to switching to root - that would require something different as root already exists - obv we could just remain as root and there would be no need to change any perms etc - but im not sure thats something we want to add

Thanks very much for replying.
An alternative way I found to build my wasm binary is to use [proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk).
