### ISSUE TITLE
Consolidate mobile github workflows

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27372]
Currently there are 15 separate mobile workflows

This makes it near impossible to track the path of CI (not helped by githubs limited ui) and means the jobs are not run in any dependent fashion (ie not running expensive jobs if cheap ones fail)

As we move more of envoy's ci into github - this will make the job harder unless we consolidate these

Ideally once we have removed azp from the equation we will end up with something like `shared prechecks` -> `optional envoy build` / `optional mobile build` -> `optonal envoy checks` / `optional mobile checks` and limited to 2/3 workflows so you can easily track the progress

**Comment by phlax** [comment]
cc @alyssawilk @RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
Sounds like a good idea. I'm not sure how to do this, but it sounds good to me!

**Comment by phlax** [comment]
With the envoy CI im looking to do something similar to what we have in azp, but using workflow triggers (as github doesnt have stages as such)

Ideally we do something like:

`env` -> `prechecks` -> `main workflows`

The key difference (which is quite significant) is that we switch the workflows to not trigger on pull_request/push, the workflows instead need to be triggered by the preceeding workflow

For the current mobile setup that could work quite well as most of the jobs run a `should_run_ci.sh` step - we would then run this in `env` (or `prechecks`) and instead decide what to trigger from there (i need to check this more fully)

It would also allow us to prime caches for the build image - altho its not entirely clear whether there are the same benefits for azp <> github

**Comment by phlax** [comment]
a kinda related issue is that the mobile ci desperately needs some caching set up

pring this am to fix a separate issue and all of the mobile ci is failing trying to download go libs

this could ~easily be fixed with caching

**Comment by alyssawilk** [comment]
mmm, I'm Ok doing more combining but one thing I really dislike about main github workflows is sometimes a job fails to not test reasons and I have to wait an hour and a half before coverage finishes before I can rerun. not as bad for mobile as all the jobs are faster, but can we make sure we don't bring the bad along with the good when we consolidate?
