### ISSUE TITLE
B3 sampled header not used

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#2738]
According to https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers.html#x-b3-sampled the `X-B3-Sampled` flag is used to determine whether spans are reported, and the value is consistently propagated to downstream services.

However currently it does not appear that this header is being used - and is set to always sample when [injecting the context in requests](https://github.com/envoyproxy/envoy/blob/master/source/common/tracing/zipkin/zipkin_tracer_impl.cc#L36).

Is there any reason the header is not supported? If not, will look to create a PR for this.

The reason for looking at it was I am using prometheus to scrape metrics from a service (deployed within Istio), and currently the HTTP request scraping the metrics is being traced. Is there anything else I should try?

**Comment by objectiser** [comment]
Ideally I would like to exclude the "/metrics" endpoint from being traced - not sure if there is any plan/requirement to support such a feature for other reasons?

**Comment by mattklein123** [comment]
@objectiser no reason its not implemented. Feel free.

**Comment by objectiser** [comment]
Ok thanks. Thought it best to create a separate issue for the scrape endpoint exclusion - would appreciate your thoughts on that aswell.
