### ISSUE TITLE
Max_requests_per_connection: 1 does not disable keep-alive connections as reported in docs

### ISSUE THREAD

**Issue by lorenzogio97** [envoyproxy/envoy#27385]
*Title*: *Max_requests_per_connection: 1 does not disable keep-alive connections as reported in docs*

*Description*:
As I explained better in #26473 ([my post](https://github.com/envoyproxy/envoy/issues/26473#issuecomment-1546594212)), I'm looking for a way to drop an established connection at some moment in time. I have tried using Connection:close header, but envoy ignores it. 
Looking at Envoy documentation, I found **"max_requests_per_connection"** value inside config.core.v3.HttpProtocolOptions message. Documentation reports:

> max_requests_per_connection
> 
>     Optional maximum requests for both upstream and downstream connections. If not specified, there is no limit. Setting this parameter to 1 will effectively disable keep alive. For HTTP/2 and HTTP/3, due to concurrent stream processing, the limit is approximate.

Disabling keep-alive means that it should use a single TCP connection for every request, without reusing existent ones, but it is still using always the same TCP connection. I used wireshark to check TCP connection and it is always the same, both downstream and upstream. 
I didn't use _max_requests_per_connection_ value inside Cluster because it's deprecated and the documentation doesn't mention "downstream connection" in that case. 

*Repro steps*:
Set _max_requests_per_connection_ to 1 and make many HTTP request. The request will be routed correctly and served by the configured cluster. But you will always use the same TCP connection. I tested making HTTP GET request using RESTED extension inside both Chrome and Firefox, and I tried also using Requests Python library. I configured the cluster using XDS Java API. In my tests, cluster was added for first time, no connections to upstream were in progress before. My idea (if I make it work) is to change cluster configuration introducing max_requests_per_connection=1 when I want that clients that use this cluster disconnects from Envoy (drop downstream connection). 
I attach the dynamic configuration of the two test cluster that I created running on Envoy. 

*Config*:
```
   "dynamic_active_clusters": [
    {
     "version_info": "181282ed55cfa02556454ea4f84bc7debdb290c9185d43505b9bbd5f44082694",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "lorenzo-echo",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "load_assignment": {
       "cluster_name": "lorenzo-echo",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "172.17.0.3",
              "port_value": 80
             }
            }
           }
          }
         ]
        }
       ]
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "common_http_protocol_options": {
         "max_requests_per_connection": 1
        },
        "explicit_http_config": {
         "http_protocol_options": {}
        }
       }
      }
     },
     "last_updated": "2023-05-13T16:18:04.770Z"
    },
    {
     "version_info": "95b0d5f4ba4e990edef335e73f2b0ee8faac13840f69316a1be19544da25e2e9",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "lorenzo-echo2",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "load_assignment": {
       "cluster_name": "lorenzo-echo2",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "172.17.0.4",
              "port_value": 80
             }
            }
           }
          }
         ]
        }
       ]
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "common_http_protocol_options": {
         "max_requests_per_connection": 1
        },
        "explicit_http_config": {
         "http_protocol_options": {}
        }
       }
      }
     },
     "last_updated": "2023-05-13T16:18:07.779Z"
    }
   ]
  }
```

**Comment by lorenzogio97** [comment]
Any suggestions? I need at least if this is the right behaviour or I did some mistake in configuration. Thanks

**Comment by ggreenway** [comment]
Yes, this is expected to work, and there are some tests validating it.

> In my tests, cluster was added for first time, no connections to upstream were in progress before. My idea (if I make it work) is to change cluster configuration introducing max_requests_per_connection=1 when I want that clients that use this cluster disconnects from Envoy (drop downstream connection).

This is not how envoy works. A configuration update will only apply to new connections/requests; it will not re-configure already-established connections/requests.

**Comment by lorenzogio97** [comment]
> Have you tried testing with a static configurations that sets `max_requests_per_connection: 1` to validate that this setting is working correctly?

In the meantime I have used another solution for my project. But thanks for explaining me how Envoy applies new configurations.
