### ISSUE TITLE
Ext_Auth payload change

### ISSUE THREAD

**Issue by valentinegu** [envoyproxy/envoy#27386]
*Title*: Ext_Auth payload change

*Description*:
In external authorization scenario envoy seems to be replacing non-utf-8 payload to `!`,
as per commit 664f3fce4730544f34ae767e10150fb6be11cdc6 this behavior is expected on strings but instead seen on all payload

*Envoy Version* 1.24.5 

*Repro steps*:
Send non-utf8 payload through Envoy configured with External authorization 
> *Example using `NC`*
> `echo -ne "
>POST /post HTTP/1.1\n\
>Host: demo.test\n\
>Connection: close\n\
>Content-Type: application/txt\n\
>Content-Length: 4\n\n\
>$(echo -ne $'\x1a\xc1\x0e\x43')" | nc 127.0.0.1 80`

Above example should be a float with value of `142.754` but instead when passed through Envoy we get `0x1a210e43` (`0xc1` was converted to `!`).
Setting ``envoy.reloadable_features.service_sanitize_non_utf8_strings`` to false allows the original payload to reach Ext_Authz service.

*Config*:
>{
>    "name": "envoy.filters.http.ext_authz",
>    "typed_config": {
>        "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
>        "http_service":
>        {
>            "server_uri":
>            {
>                "uri": "...",
>                "cluster": "...",
>                "timeout": "0.500s"
>            },
>        },
>        "with_request_body": {
>            "max_request_bytes": 10240,
>            "allow_partial_message": true
>        },
>        "status_on_error": { 
>            "code": "NotAcceptable"
>        },
>        "transport_api_version": "V3",
>    }
>}

**Comment by ggreenway** [comment]
All content that is represented as `string` in a protobuf must be utf-8. If you have non-utf-8 body, you should set `pack_as_bytes` to true in your config (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html), and then the body will be set in a `bytes` field instead of a string, and thus will not need to be modified.

**Comment by weissne** [comment]
To clarify, as seen in the reproduction steps above, the Ext Authz is configured to send to the target over Http and **not** over GRPC.
In this case, setting  _pack_as_bytes_ to true in the config does not send the body content at all.

Here's an example:
Request sent:
echo -ne "POST /post HTTP/1.1\r\nHost: httpbin.kwaf-demo.test\r\nConnection: close\r\nContent-Type: application/octet-stream\r\nContent-Length: 4\r\n\r\n$(echo -ne $'\x1a\xc1\x0e\x43')" | nc 127.0.0.1 32102

pcap of request: [request.zip](https://github.com/envoyproxy/envoy/files/12093947/request.zip)

pcap of Ext Authz request: [extAuthRequest.zip](https://github.com/envoyproxy/envoy/files/12093951/extAuthRequest.zip)


Screen capture of the Ext Authz Configuration: [Envoy-ExtAuthz-Conf](https://github.com/envoyproxy/envoy/assets/49511015/725d389c-ea78-4bff-b72f-3d8157f96af1)

**Comment by ggreenway** [comment]
Thanks for clarifying that this is for http, not grpc, service configurations.

I see why the body is getting mangled as reported, when `pack_as_bytes` is set to false, and that's a fixable bug.

I have not been able to reproduce what you're reporting where when `pack_as_bytes` is true you don't get the body at all.

**Comment by ggreenway** [comment]
Oh, I think the second issue is https://github.com/envoyproxy/envoy/issues/27220, which is already fixed (but not yet in a release), which is why I couldn't reproduce.
