### ISSUE TITLE
dependency: gcovr 3.4

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#2739]
*dependency*: Investigate updating to gcovr 3.4

*Description*: gcovr 3.4 was recently released ([release notes](https://github.com/gcovr/gcovr/releases/tag/3.4)). There are work arounds in the code for gcovr 3.3 bugs that are outlined at https://github.com/envoyproxy/envoy/blob/43df022ad90bdf62c1d254c3ad65653c8a2b823a/ci/do_ci.sh#L127-L135

Question is should we investigate 3.4 or stay on 3.3 until gcovr is replaced which is covered in https://github.com/envoyproxy/envoy/issues/1000

**Comment by mattklein123** [comment]
Realistically I'm not sure how soon coverage is really going to change. @moderation I would just do the upgrade if you feel like it. Thank you!

**Comment by htuch** [comment]
Bazel team are working on fixing coverage to support lcov atm, so there is reason to suspect we might get lcov in the medium term.

**Comment by keith** [comment]
FYI I'm updating gcovr to 3.4 in this PR https://github.com/envoyproxy/envoy/pull/7391 (4.1 is out but it would require quite a few more changes) but I didn't revisit this comment, so that's something we could do after merging

**Comment by lizan** [comment]
We're no longer using gcovr.
