### ISSUE TITLE
Dynamic HTTP Statistics Lost After Changing The Scrape Way 

### ISSUE THREAD

**Issue by fenngwd** [envoyproxy/envoy#2741]
Statsd were used to received stats info from envoy before, but when I changed the scrape way to scrape it by prometheus directly, I lost dynamic http statistics info such as upstream_rq_time in no any other config changed situation.

Did I forget to update any configuration?
Thanks!

**Comment by mattklein123** [comment]
Currently timers are not emitted in any of the pull stats endpoints (`/stats`). See https://github.com/envoyproxy/envoy/issues/1965.

**Comment by mattklein123** [comment]
I believe this was answered. Closing.

**Comment by fenngwd** [comment]
@mattklein123 Thanks a lot! Your answer helped me!!
