### ISSUE TITLE
Not draining existing connection if filter chain or listener updates through lds

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27411]
I can see in the [listener_filters doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/listener_filters.html#filter-chain-only-update) that in case LDS updates a listener with a new config that only applies to a specific filter chain, it would only drain connections that are using those filter chain, however my question is - can this draining be avoided at all? Meaning that existing connections would use the current filter chain configs, and new connections that would match with the filter chain would get the new filter chain configurations. Thanks.

**Comment by kyessenov** [comment]
I think the filter chain update necessarily means the older version must be eventually retired - that could be changed but that could be surprising since it was always this way.

An out of band config mechanism might be better - using ECDS or something else to configure listener filter without modifying LDS.

**Comment by ohadvano** [comment]
Thanks @kyessenov! That's a good idea I was not familiar with. Two questions - first is why the ECDS is not listed in the [xDS configuration doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration)? Is it because it's WIP or not-stable or something?

Second and the more important Q to understand if I could use this feature - If I use LDS that responds with a listener config that itself contains other xDS configurations, for example using SDS for a filter chain transport socket, or the ECDS for HCM - is this supported? In other words - can I combine LDS with SDS + ECDS, considering that SDS and ECDS configs are nested within LDS resources?

**Comment by kyessenov** [comment]
@ohadvano ECDS is fairly stable - it's been used in Istio for Wasm delivery and lots of rough edges have been ironed out. I think it's already integrated with listener filters. @adisuissa has also proposed another xDS called ODS for fine-grained objects which might be a better fit.

You can combine transitively xDS resources by using resource warming. The warming mechanism stalls the application of LDS until all the dependencies are resolved.

**Comment by ohadvano** [comment]
Thanks Kuat, I do have some more questions about how LDS behaves with nested xDS resources, but I'll open another issue as it's not 100% related to the draining problem I mentioned at first.

One other question though - is it currently possible to somehow respond with ECDS resources with some flag that causes the connections attached to a listener/filter-chain to drain? A use case for example would be some config update that would mitigates some security issue.

**Comment by ohadvano** [comment]
Thanks
