### ISSUE TITLE
Add stat_prefix option to RateLimit filter

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [envoyproxy/envoy#27421]
*Title*: *Add stat_prefix option to RateLimit filter*

*Description*:
When using [RateLimit](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter) envoy filter:
```
type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
```
we might want to distinguish between metrics produced by different filters of the same type. 

Currently, there is no option to specify `stat_prefix` for `RateLimit` filter to configure different tag that should be appended to the metric. 

Adding `stat_prefix` property is inspired by a similar filter that has this option - ExtAuthz.

*Relevant Links*:
[ExtAuthz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto) - check `stat_prefix` property

**Comment by ggreenway** [comment]
cc @esmet @mattklein123

**Comment by StarryVae** [comment]
👀 if needed, i can try to take it up, thanks.

**Comment by ggreenway** [comment]
I think it's a reasonable idea. PRs welcome!

**Comment by StarryVae** [comment]
can we also reopen this? i will submit a PR, thanks. cc @ggreenway @mattklein123
