### ISSUE TITLE
(ideally) Turn down handling of invalid YAML for runtime

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#27434]
switching our runtime to proto parsing made it clear there's a bunch of corner cases of bad yaml we currently support. It'd be nice to turn down the workarounds so my plan is to
ENVOY BUG for a quarter, and see if anyone responds
runtime remove support
entirely remove support after the 6m release window

if folks need to support ill formed yaml, we'll leave the hacks in and document that they're necessary long term.

**Comment by howardjohn** [comment]
Hi, we ran into this. Unfortunately we expose a `map[string]string` API to users since that was sufficient originally.

Do you think this is workable by attempting to parse the strings as numbers/bools before we pass to envoy, or a new API type would be needed? I am just not really familiar with all the types of things that may be exposed in Envoy's runtime API that may make the parsing attempts unreliable. Just matching `true` and `false` or something seems easy, but if there is a field that someone may want to set the string `"true"` or whatever it may be problematic?

It is an obscure low-level API for us so its not too bad to deprecate it if it will be needed, just would prefer to avoid it if you think the parsing approach would be reliable moving forward?

**Comment by alyssawilk** [comment]
I think we could attempt to parse things before we hand them to envoy but if you agree that's plausible I'd suggest just flipping that flag for now and seeing if other people hit the same pain point.  If it's just Istio and you can do checks to submit properly formed yaml I'd say it's worth it but if a bunch of other users have the same problem we'll probably just support the legacy hacks, hacky though they may be.  Sound reasonable?

**Comment by kyessenov** [comment]
Istio passes bootstrap as JSON, not YAML. Is JSON parsing also affected?

**Comment by alyssawilk** [comment]
same thing largely if you pass a number in quotes in JSON or YAML, proto will parse it as a string rather than a number. We then manually check all strings to see if their values pass atio checks, ditto do hacks for fractions and floats and booleans.  This tracking issue is to determine if we can turn down that second pass, which requires passing in the correct data types from the get go.

**Comment by kyessenov** [comment]
Proto requires that large numbers are passed at strings since numbers are floats in JSON. I don't think we can dis-allow that. I'm not sure about bools as strings.

**Comment by kyessenov** [comment]
Looks like bools as strings are prohibited, so there would be some impact on Istio. I think it can be handled downstream since this is mostly runtime keys, and we know which keys are there.

**Comment by ramaraochavali** [comment]
> and we know which keys are there.

We have an API in Istio that would let people to add runtime flags themselves. So we do not know what they are upfront.

**Comment by kyessenov** [comment]
@ramaraochavali In most cases, we do, since there is a list in the source code. There are a few EnvoyFilter-based cases that introduce their own runtime keys (rate limit). Is the latter what you are worried about?

**Comment by ramaraochavali** [comment]
@kyessenov I am worried about this [api](https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L499). So we have to keep checking that list in the code

**Comment by howardjohn** [comment]
Not stale. For now we are correctly typing bools, but anything else will trigger this: https://github.com/istio/istio/pull/45869/files

**Comment by milton0825** [comment]
Hi we unfortunately expose `map[string]string` as an API to users at Lyft as well. It would be great if we can hide the legacy path behind a flag so that we can migrate at our own pace.

**Comment by alyssawilk** [comment]
Sounds good - thanks very much for updating here.  The plan is to disable by flag, and remove after 6 months if and only if there are no blocking concerns.  I'll make sure to CC you when it's turned off-by-default so you can enable internally, and check in before any flag removal to ensure it won't be problematic!

**Comment by JuniorHsu** [comment]
we're hitting this as well
```
 [external/envoy/source/common/runtime/runtime_impl.cc:335] envoy bug failure: false. Details: Runtime YAML appears to be setting fractions as strings. Support for this is planned to removed in an upcoming release. If you can not fix your YAML and need this to continue working please ping on https://github.com/envoyproxy/envoy/issues/27434
[ key:internal_key value: string_value: "{\"denominator\": \"TEN_THOUSAND\", \"numerator\": 10000}"
]
```

here' s the config, which is JSON instead of YAML
```
              "runtime_fraction": {
                "default_value": {
                  "denominator": "TEN_THOUSAND"
                },
                "runtime_key": "internal_key"
              }
```

looks like we're preferring to unquote `TEN_THOUSAND` or put a number?

**Comment by JuniorHsu** [comment]
> looks like we're preferring to unquote `TEN_THOUSAND` or put a number?

sorry for false alarm.
talking internally and we discuss this before, which is due to our runtime setup instead of json

**Comment by alyssawilk** [comment]
For those following along, the (runtime guarded) disable landed so please update your yaml and let me know if there are any problems.
