### ISSUE TITLE
Envoy TLS config causes SSL WRONG_VERSION_NUMBER error

### ISSUE THREAD

**Issue by ngalagali3** [envoyproxy/envoy#27441]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Envoy TLS config causes SSL WRONG_VERSION_NUMBER error

*Description*:
I've set up an Envoy config which connects to Trino on localhost port 11610. It adds TLS configs and redirects to a host. When I call the API, I see the envoy logs resolve the host to the correct IP address, but I get this error:

```
[source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C29] handshake expecting read
[2023-05-17 04:14:24.357][911][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:198] [C29] handshake error: 1
[2023-05-17 04:14:24.357][911][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C29] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2023-05-17 04:14:24.357][911][debug][connection] [source/common/network/connection_impl.cc:208] [C29] closing socket: 0
However, when I call the endpoint directly using curl (and provide all the TLS certs) it works as expected.
```

I'm using Envoy version 1.15, and it's supposed to support TLSv1.2 and 1.3. The server I'm trying to connect to also supports those TLS versions. Here is my Envoy config for TLS:

```
tls_context:
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: /etc/cacerts.pem
            tls_certificates:
              - certificate_chain:
                  filename: "/etc/client.pem"
                private_key:
                  filename: "/etc/client-key.pem"
        hosts:
        - socket_address:
            address: trino-gateway.path.com
            port_value: 443
```

I want to see where the TLS configs are being added in the call being made. However, that isn't printing out in the logs.

I'm outputting the highest level of logging - trace but I don't see the certificates getting added to the request. Is there a way to get more details on it?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ggreenway** [comment]
That version of envoy is very old and not supported anymore. Does it still reproduce on a newer version?

As you noted, the log message is indicating that the server presented a TLS protocol version that envoy doesn't support with this configuration. I'd recommend capturing the handshake with wireshark and figuring out what version is actually being sent, to help narrow down the issue.
