### ISSUE TITLE
It may cause getOriginalDst return nullptr when enabled transparent and disabled IPv6

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#27448]
*Title*: *getOriginalDst return nullptr when enabled transparent and disabled IPv6*

*Description*:

`supportsIpTransparent` return true need the OS support both `IP_TRANSPARENT` and `IPV6_TRANSPARENT` options. However, network communication within data centers is usually disabled for IPv6, so I think in getOriginalDst, it should only be based on the ipversion of the current sock, rather than both IPv4 and IPv6.

https://github.com/envoyproxy/envoy/blob/main/source/common/network/utility.cc#L366-L395
![image](https://github.com/envoyproxy/envoy/assets/8215757/71d51da5-327f-4854-813d-617982b1d73a)

**Comment by soulxu** [comment]
I guess you mean the `supportsIpTransparent` wil always return false when ipv6 diabled, due to it can't create ipv6 socket at
https://github.com/envoyproxy/envoy/blob/2a63fe20f7dd77062e8ca04ee19bc605bf9e02d5/source/common/api/posix/os_sys_calls_impl.cc#L168-L171

It seems a bug should be fixed.

**Comment by wangfakang** [comment]
> I guess you mean the `supportsIpTransparent` wil always return false when ipv6 diabled, due to it can't create ipv6 socket at
> 
> https://github.com/envoyproxy/envoy/blob/2a63fe20f7dd77062e8ca04ee19bc605bf9e02d5/source/common/api/posix/os_sys_calls_impl.cc#L168-L171
> 
> It seems a bug should be fixed.

yeah. `supportsIpTransparent` should only be based on the ipversion of the current sock, rather than both IPv4 and IPv6.
