### ISSUE TITLE
What are the cases where connections drain due to xDS updates?

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27452]
I am trying to figure out all the possible cases where connections would drain due to some xDS update, and for some I couldn't properly understand, so will appreciate the community help with this. Some use cases:

1. Using LDS, where some of the filter chains in the listener config have SDS config (downstream transport TLS that uses SDS to fetch secrets). After a while, the certificate is refreshed from the SDS. Does it cause connections that currently use the filter chain to drain? Will only new connections get the new certificate?
2. Using LDS, and after a while there's a listener update which is identical to the previous listener config, only a single filter chain is removed from the filter chains of that listener - will all the listener connections drain, or just those of the specific filter chain.
3. Similar to second question - only here there's an update to the filter chain config, instead of its removal - for example adding/removing a filter to/from the chain. In this case - will all the listener connections drain? Only those of the specific filter chain? Or otherwise, no drain but only new connections get the updated filter chain config?
4. Using LDS with filter chain that has HCM with HTTP filters that are configured by ECDS - in this case, does connections that use the filter chain drain if any of the filters in the HCM chain get config updated?
5. Same concept question for only RDS update within some specific filter chain.
6. Using LDS where some filter chain has downstream TLS context with ``tls_certificate_sds_secret_configs``, after a while the list of SDS certificates is updated with a new SDS certificate or removed SDS certificate. Does this cause the connection of the filter chain to drain?

Thanks for helpers, sorry for the blast of questions.

**Comment by ohadvano** [comment]
cc @adisuissa maybe you could help with some of these as with your expertise in xDS

**Comment by ohadvano** [comment]
Still relevant

**Comment by ohadvano** [comment]
Still relevant
no stalebot

**Comment by ohadvano** [comment]
Still relevant

**Comment by AmitKatyal-Sophos** [comment]
@ohadvano Could you please share your findings ?
