### ISSUE TITLE
mobile CI can fail due to BEP uploads

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27459]
Mobile coverage can fail (flakely) with:

```console
ERROR: The Build Event Protocol upload failed: All 4 retry attempts failed. DEADLINE_EXCEEDED: DEADLINE_EXCEEDED: deadline exceeded after 14.999902701s. [closed=[], open=[[buffered_nanos=27500, remote_addr=envoy.cluster.engflow.com/54.197.155.115:443]]] DEADLINE_EXCEEDED: DEADLINE_EXCEEDED: deadline exceeded after 14.999902701s. [closed=[], open=[[buffered_nanos=27500, remote_addr=envoy.cluster.engflow.com/54.197.155.115:443]]]
```

https://github.com/envoyproxy/envoy/actions/runs/5005354480/jobs/8969195350#step:6:109

When i was testing a fix for mobile coverage in #27425 i hit a similar error and added `--legacy_important_outputs=false` on advice from the interwebs and that appeared to fix - iirc i was testing running the cov tests in RBE at the time

I may have seen it once or twice after while testing

**Comment by phlax** [comment]
seems this can happen on any of the jobs

**Comment by phlax** [comment]
this is still an issue https://github.com/envoyproxy/envoy/actions/runs/5333398770/jobs/9663823955#step:5:171

**Comment by phlax** [comment]
surfacing offline coversation

this may be fixed by adding `--legacy_important_outputs=false` to https://github.com/envoyproxy/envoy/blob/main/mobile/.bazelrc#L155

cc @Unnar

**Comment by Unnar** [comment]
Just to clarify, the fix would be to add `--bes_upload_mode=fully_async` not `--legacy_important_outputs=false`

**Comment by phlax** [comment]
thanks for clarification - bad copypasta - updated
