### ISSUE TITLE
mongo decoding error: invalid mongo op 2010

### ISSUE THREAD

**Issue by DavadDi** [envoyproxy/envoy#2745]
**mongo decoding error: invalid mongo op 2010**

[2018-03-07 13:54:40.083][3963593][info][mongo] source/common/mongo/proxy.cc:243] mongo decoding error: invalid mongo op 2010

> OP_COMMAND | 2010 | Cluster internal protocol representing a command request.
[MongoDB Wire Protocol](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/)

Should this command be supported ?

```
$ cat conf/mongodb.yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_mongodb
    address:
      socket_address: { address: 0.0.0.0, port_value: 10001 }
    filter_chains:
    - filters:
      - name: envoy.mongo_proxy
        config:
          stat_prefix: mongodb_proxy
          access_log: /tmp/mongodb_access.log
      - name: envoy.tcp_proxy
        config:
          stat_prefix: tcp_proxy
          cluster: mongo_proxy
          idle_timeout: 1.5s
          max_connect_attempts: 5
  clusters:
  - name: mongo_proxy
    connect_timeout: 0.25s
    type: static
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 27017 }}]
```

**Comment by danielhochman** [comment]
In what context does this occur? As the Mongo docs suggest, this is a cluster internal command. It wouldn't be difficult to add support, but the use case and a repro would be helpful.

**Comment by DavadDi** [comment]
@danielhochman  I use the Mongodb admin tools  [Robo 3T](https://robomongo.org/), maybe the tools send  OP_COMMAND for some purpose.  I am not sure our client will use this command or not. But I found something useful from the [page](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/) 
> WARNING
>
> OP_COMMAND and OP_COMMANDREPLY are cluster internal and should not be implemented by clients or drivers.
> 
> Changed in version 3.6: The OP_COMMAND and OP_COMMANDREPLY format and protocol are deprecated and may be removed in a future release of MongoDB.

**Comment by mattklein123** [comment]
Sure we can support this if someone wants to implement. Marking "help wanted."

**Comment by cpakulski** [comment]
@mattklein123 I will implement this.

**Comment by mattklein123** [comment]
@cpakulski OK will add you to org so I can assign.
