### ISSUE TITLE
Excluding metrics scrape endpoint from tracing

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#2746]
Currently `HttpTracerUtility::isTracing` returns a decision regarding whether a particular invocation should be traced - which includes checking whether the request is a health check.

As mentioned in https://github.com/envoyproxy/envoy/issues/2738#issuecomment-370901239, wondering whether we should support configuring a metrics scrape endpoint for exclusion from tracing?

**Comment by mattklein123** [comment]
Is this for Envoy? Or the backend service?

**Comment by objectiser** [comment]
It would be for the backend service. Currently we can skip tracing generated by the service itself for certain endpoints (e.g. /metrics), but when proxied - the proxy is generating the traces still.

**Comment by mattklein123** [comment]
@objectiser I think I would recommend actually adding some type of route property that allows turning off tracing for a certain route. Would that work? It feels less like a special case to me.

**Comment by objectiser** [comment]
@mattklein123 Sounds like a good solution. I can see how it would work in pure envoy proxy - with the inbound listener being configured to not trace the `/metrics` path.

However not sure how this would be used from istio route rules - the examples I have seen all seem to specify the destination service, whereas for the prometheus scrape use case, the rule would need to be for all services. Any thoughts on this? Or maybe I need to raise this on istio project to find out if your suggested solution could be made to work with their rules.

**Comment by mattklein123** [comment]
> However not sure how this would be used from istio route rules - the examples I have seen all seem to specify the destination service, whereas for the prometheus scrape use case, the rule would need to be for all services. Any thoughts on this? Or maybe I need to raise this on istio project to find out if your suggested solution could be made to work with their rules.

At least naively I would assume that a route rule could be injected everywhere even if it ends up routing to the same backend cluster, albeit with a different setting to turn of tracing. If that won't work I suppose we can adding path exclusion rules to the connection manager tracing config, though that feels not great to me so if we can avoid it that would be nice. Can you talk to the Istio people and then circle back?

**Comment by objectiser** [comment]
Will do.

**Comment by mattklein123** [comment]
Going to close this out for now. @objectiser once you finish talking with the Istio folks can you open a more explicit feature request issue and we can discuss there? Thank you.

**Comment by rahulraykor** [comment]
@mattklein123 :
To disable tracing in envoy for a route I have made the overall_sampling to 0% still it is generating traces in Jaeger. Can you please help in disabling tracing for this route.

**Comment by objectiser** [comment]
@rahulraykor would be good if you could open a new issue that provides more details about your configuration and an example of the tracing your are seeing.
