### ISSUE TITLE
Add retry policy for reset connections with idempotent requests

### ISSUE THREAD

**Issue by JonathanO** [envoyproxy/envoy#2747]
*Description*:
If a connection is reset after a request has been sent then the request can often be safely retried if the method was one of GET/HEAD/PUT/DELETE/OPTIONS, or was a POST with no body and an "Expect: 100-continue" header.

It should be possible to configure a retry policy that will retry under those circumstances.

*Relevant Links*
As per the discussion in #2715 

*Discussion*
Would it be useful to do this by adding configuration to allow a different response status code to be generated in this case? That way as well as a retry policy, it'd also be possible to instead pass the error up to the application to deal with.

Should this also happen with request timeouts?

**Comment by htuch** [comment]
@JonathanO assigning to you for now to drive this conversation. Seems a reasonable feature to me, although I'm not sure if everything you describe in that list is technically idempotent (POST).

**Comment by mattklein123** [comment]
In general, Envoy does not deal with idempotency since app developers nearly always get it wrong. I have no objection to adding a retry policy such as "idempotent_requests" that adheres to the above rules as long as its clearly documented that the application developers may not adhere to the rules.
