### ISSUE TITLE
Issues with route timeout configuration

### ISSUE THREAD

**Issue by thaleslimao** [envoyproxy/envoy#27492]
Hello

I am trying to set my route timeout to use 60s value:

          routes:
          - match:
              prefix: "/"
            route:
              cluster: load_balancer_3
              timeout: 60s
              idle_timeout: 60s
              
Envoy version: v1.26.1 

Although, when I am receiving its response... I am getting 15s default value

We are completely uploaded and fine
Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 504
< date: Mon, 08 Mai 2023 20:15:11 GMT
< content-type: text/plain
< content-length: 24
< server: envoy
<
Connection #0 to host left intact
upstream request timeout
real 0m15,655s
user 0m0,025s
sys 0m0,010s
I need to envoy wait 60s for the request

Could you help me ?
Thank you

**Comment by wbpcode** [comment]
Hi, could you provide a complete example config to make the community could reproduce this problem easily? thanks.
