### ISSUE TITLE
Need a way to use envoy.extensions.filters.http.ext_authz.v3.ExtAuthz for both requests and responses.

### ISSUE THREAD

**Issue by schulmanworks** [envoyproxy/envoy#27523]
From what I can tell, the envoy.extensions.filters.http.ext_authz.v3.ExtAuthz only gets triggered when a request goes through the filter chain. When a response comes back, this seems to be skipped. Is there a way to run this in both cases? It would be helpful for be because I would like to use code in my ExtAuthz server to check headers in the response.

**Comment by kyessenov** [comment]
Have you seen https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor? It might be a better fit.

**Comment by schulmanworks** [comment]
Can you use this to reject messages as well?

**Comment by schulmanworks** [comment]
@kyessenov I looked into ext_proc, however I am nervous that it is not in release and does not have security support at this time. Is there no way to get the ext_authz filter to run in both directions?

**Comment by kyessenov** [comment]
Yes, I'm pretty sure as it was designed primarily to authorize the request headers.
ext_proc is currently actively being improved so I think it's highly likely it's going to be safe enough to use soon.

**Comment by schulmanworks** [comment]
Is there a target for a stable release at this point or is "soon" as good
as it gets right now? Also thank you for your help.

**Comment by kyessenov** [comment]
Maybe @yanjunxiang-google  or @tyxia  can speak in detail, but ext_proc is a core filter - and the more it is used, the faster it'll mature.

**Comment by yanjunxiang-google** [comment]
Yeah, there is ongoing work to turn ext_proc filter into stable.  I don't have a date, but "in several weeks" probably is a good estimate.

**Comment by schulmanworks** [comment]
Thanks a bunch! That is a reasonable enough estimate for me to use this now
and take the update when it comes.
