### ISSUE TITLE
Understand upstream connect behaviour

### ISSUE THREAD

**Issue by wdauchy** [envoyproxy/envoy#27528]
*setup description*:

We are trying to understand the upstream connect behaviour
- tests were done with envoy 1.26.x.
- the setup has 32 cores, so 32 workers.
- the [preconnect config is not specified](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-preconnectpolicy). So we assume there is no preconnect behaviour
- upstream connections are http1.1 with keepalive

*problem*:

- we are seeing some connections from envoy which stays unused for several seconds:
![image](https://github.com/envoyproxy/envoy/assets/104408/6c77f2c9-83b7-4b1d-8755-9cfd006f4baf)
- then the backend closes it after 10s, resulting in write errors when envoy decides to use this connection around the same time
- the happens for a small part of the traffic but enough to trigger retry overflow on some requests (resulting in 503)
- we know we can adapt idle timeout on envoy side to avoid this behaviour

*questions*:

While we know we could lower the idle timeout, we are a bit surprised to see some connections being open without being used right away (for 10s in this example).

- If we assume there is no preconnect behaviour, what could explain this?
- Is there a way to avoid opening connections which are not used right away?

note: we tried to turn connection debug on, but the traffic is so high that it is hard to find any useful info.
would you have any other suggestion to further debug this issue?

Thanks in advance for your time,

**Comment by wbpcode** [comment]
> If we assume there is no preconnect behaviour, what could explain this?

It's pool of connections. If some requests coming in and the number of connection not reach the limit of max connection and there are no enough idle connections, some new connections will be created to service these requests.
And after these requests are completed, all connections will be stored into the pool, waiting for new requests. So, except the clients send the requests with a extreamly stable rate, there must be some idle connections at some timepoints.

**Comment by wbpcode** [comment]
> Is there a way to avoid opening connections which are not used right away?

You can set the max connection number of the pool according to your accually workload. Or HTTP2 could be used which will ensure only one connection is created for one host.
Or you can create an aggressive idle timeout policy to destroy these idle connection intimely.

**Comment by wdauchy** [comment]
Thanks for your answer.

> It's pool of connections. If some requests coming in and the number of connection not reach the limit of max connection and there are no enough idle connections, some new connections will be created to service these requests.
And after these requests are completed, all connections will be stored into the pool, waiting for new requests. So, except the clients send the requests with a extreamly stable rate, there must be some idle connections at some timepoints.

Keeping a connection open after being used is fine. My analysis however shows there are some new connections created without being used immediately. The dump shows one of them with a delay of 10s before being used.
My question is more why would envoy create connections without using them right away.

> Or you can create an aggressive idle timeout policy to destroy these idle connection intimely.

it does not explain why would new connection being created without being used.

**Comment by wbpcode** [comment]
sorry, I mis-understood you quesion. then could you provide more complete example configuration to help we to reproduce this problem? Thanks.
