### ISSUE TITLE
Why is max_connections not a constraint for Envoy health check?

### ISSUE THREAD

**Issue by johnf3** [envoyproxy/envoy#27549]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Why is max_connections not a constraint for Envoy health check?*

*Description*:
>We have 2 VMs (virtual machine) connected by Envoy to Envoy gRPC connection. On the client VM, the Envoy serves as forward proxy, and on the server VM, the Envoy on it serves as a reverse proxy. Now this Envoy mesh got 1 tcp connection. When I am adding the active health check, it got 2 connections. We can see from here that the health check is creating the 2nd connection. And all the other services use the 1st connection between Envoy proxy.

However, when I try to set the circuit_breakers max_connections from 2 to 1 on SE Envoy, the connections now are still always 2. Now what does max_connections here really mean? Why it can not constrain the real number of tcp connection?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
> Why is max_connections not a constraint for Envoy health check?

It's hart to say why. I think it is designed that way. The health checker will manage it's connection by itself and all other connections are managed by the connection pool.
