### ISSUE TITLE
Register custom Inline Header

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#27540]
**Background**
When I introduced CEL matcher in PR #27527 (draft needs clean-up/handling of parsed expression before being ready for review), initially I add celDataInput factory as part of `http/matching/inputs` and it caused the failure in test `ConnectionManagerUtilityTest, RemoveRefererIfMultipleEntriesAreFound`

**Root cause:** 
- as part of `http/matching/inputs` and`inputs_lib` ,  `common/expr:evaluator_lib` is included.  
- `inputs_lib` is linked by `conn_manager`. Thus, `evaluator_lib` is linked  in `conn_manager_utility_test.cc` test.
- `referer` header is already statically registered there. So there will always only single entry of referer added. See  #27532

**Potential fix/workaround:**
 - #27531 , moving the registration to function scope fixes the issue
 - Creating a separate library for cel matcher dataInput, instead of being part of `inputs_lib`  that will be linked by `conn_manager`.
 
**Some thoughts:**
- `RemoveRefererIfMultipleEntriesAreFound` is not very robust. In the future, It will fail if any links to such static registration. So, I have #27532 to check and fail earlier to manifest the failure reason
- I feel cel matcher dataInput is part of `inputs_lib` unless we want to avoid link of `common/expr` in inputs_lib and normal path.

**Comment by tyxia** [comment]
@kyessenov , I would like to learn your thoughts on this. Thanks!

**Comment by wbpcode** [comment]
> I feel cel matcher dataInput is part of inputs_lib unless we want to avoid link of common/expr in inputs_lib and normal path.

I think the new cel data input and matcher should be added in the `source/extensions` as a seperated lib. We do lots of work to move modules to the `extensions` to ensure we will have a lightweight core, even the build-in LBs and listener factory.
Specific to this new extension, I think it would be better to place it to `source/extensions` directly. Then we needn't move it again in the future.

**Comment by tyxia** [comment]
@wbpcode  My main point is that cel data input should be part of `http/matching/inputs.h` (thus, inputs_lib) along with other httpMatchingInput 

I am onboard with the ongoing trend is moving to `source/extensions`, but I think whole inputs_lib should be moved and cel data input is part of this movement, which can be done in a separate PR for reducing tech debt.

**Comment by htuch** [comment]
I think we probably want to be sensitive to the fact that some Envoy uses cases, e.g. Envoy Mobile, care a lot about the size of the binary, so we should probably be able to build without CEL. CC @alyssawilk 

So, this probably motivates the CEL libraries for data input being independent link targets and ideally not a required HCM dependency.

**Comment by wbpcode** [comment]
Compared to current inputs in the `input_lib`, I think the cel input/matcher is more like a custom input/matcher that should be defined in independent lib and **could be disabled separatedly** in the `extensions_build_config.bzl`, just like other custom input/matchers that we may have in the future.

**Comment by tyxia** [comment]
@htuch @wbpcode 
Fair point. Introduction of CEL matcher does add extra dep/link,  so I am ok to move it outside of input_lib for the concerns like size, linking etc.

**Comment by kyessenov** [comment]
Agree that we need to allow disabling CEL input in the core code for the same reason why CEL should not be directly referenced in envoy headers. It's an optional feature.

**Comment by tyxia** [comment]
This issue has been resolved.

Thanks all for comments and inputs!
