### ISSUE TITLE
Pre-establish upstream connections (connection prefetching)

### ISSUE THREAD

**Issue by bmadhavan** [envoyproxy/envoy#2755]
*Title*: *Pre-establish upstream connections so that connections will be warmed up for future requests*

*Description*:
Envoy can be deployed in use cases where establishing a new upstream connection is expensive w.r.t time (~300ms RTT). Since requests are typically queued for this duration, results in increased response times.    

*Proposal*:
Pre-establish few upstream connections every time the number of free upstream connections falls below a specific threshold. 

PS: I can work on this if it is reasonable.

**Comment by mattklein123** [comment]
Is this for tcp_proxy? HTTP/1 connection pools? 

In general I don't have any major objection to this feature, though once at steady state I wonder how useful it really is with HTTP connection pools (tcp_proxy is a different issue). 

The main issue I see with this feature is that it makes it more likely that requests will race with an upstream idle timeout.

**Comment by bmadhavan** [comment]
Our use case is for HTTP/1 connection pools. 
I agree with you that during steady state the impact of this will be much less (except for bursts). But will be quite handy during hours of the day when the requests rates either go down or starts ramping up from off peak hours....

**Comment by mattklein123** [comment]
@bmadhavan sure SGTM. I would recommend making it configurable in the HTTP1 specific protocol options in the cluster proto and potentially defaulting to disabled.

**Comment by htuch** [comment]
This is also desirable for alternative transports (e.g. transports that need to negotiate sandbox permiters) that have high latency connection establishment.

**Comment by bmadhavan** [comment]
@mattklein123 Thank you. Sure, I will make it configurable & disabled by default.

**Comment by spenceral** [comment]
I am interested in picking this up.

**Comment by alyssawilk** [comment]
Oh hey, there's an issue for this.
I'm not going to back-tag all the connection pool refactors, but I should have tagged #12973 and #12758 and now I know to close this off when predictive prefetch is done.
