### ISSUE TITLE
Failed to build in ./ci/run_envoy_docker.sh on arm64 platform

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#27569]
*Title*: *Failed to build in ./ci/run_envoy_docker.sh on arm64 platform*

*Description*:
>Describe the issue.

When I built envoy on Apple M1 (arm64 platform) via `./ci/run_envoy_docker.sh`, I got the error:
```
external/com_github_google_tcmalloc/tcmalloc/internal/percpu_tcmalloc.h:665:9: error: expected ':' or '::' before '[' token
  665 |       : [end_ptr] "=&r"(end_ptr), [cpu_id] "=&r"(cpu_id),
      |         ^
```

Some searches lead me to the issue: https://github.com/google/tcmalloc/issues/156
According to the issue, we need to upgrade the GCC in the envoy-build-ubuntu docker image to 11.1 at least.
The current GCC used in the image is:
```
./ci/run_envoy_docker.sh gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by phlax** [comment]
> According to the issue, we need to upgrade the GCC in the envoy-build-ubuntu docker image to 11.1 at least.

i dont think we want to add a requirement for this at this stage as it will make it harder to compile on various platforms that dont have the most recent gcc

would be good to find a solution to make this work for arm/gcc tho

**Comment by spacewander** [comment]
I switch to clang. If the GCC version can't be changed, we may need to patch tcmalloc to disable some implementations. I am not sure whether this will bring some side effects. BTW, GCC 11.1 is released 2 years ago, so upgrading GCC is OK IMHO.

**Comment by phlax** [comment]
>  GCC 11.1 is released 2 years ago, so upgrading GCC is OK IMHO.

its more about distro compatibility - eg https://github.com/envoyproxy/envoy/issues/26965

**Comment by phlax** [comment]
ideally we dont use any host binaries at all tbh, we are looking at shifting to using a bazel llvm toolchain, but im not sure about gcc
