### ISSUE TITLE
Envoy Upgradation activity

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#27571]
*Description*:
>we have upgraded envoy 1.17.4 to envoy 1.26.1, but we are getting error
[2023-05-23 12:33:43.446][2411][warning][config] [source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) AA_NONSEC_LISTENER_0: Only IPv6 address '::' or valid IPv4-mapped IPv6 address can set ipv4_compat: 10.10.173.135:4568

Could you please give me reference of code, how can we set cluster and listener addresses in envoy.
Or please let me know what needs to be changed at API level

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/issues/23429#issuecomment-1274145123

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#config-listener-v3-listener

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-address

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-socketaddress

**Comment by Gaurav0411GitHub** [comment]
Thanks for your support, I have already seen this.
Could you please give me example of C++ code in which we can set listener and cluster configuration

**Comment by phlax** [comment]
im not aware of any code examples to do this - not to say there arent any - but the links above are the `latest` api docs (you might also want to check the version-specific docs) 

from reading the error message, surely its just a matter of setting the address and port separately

**Comment by Gaurav0411GitHub** [comment]
Thanks for your support, I could able to solve this problem by converting ipv4 address into Ipv4-Mapped IPV6 address.
In envoy 1.26.1 version 
{
  "source_address": {...},
  "freebind": {...},
  "socket_options": [],
  "extra_source_addresses": [],
  "additional_source_addresses": []
}

extra_source_addresses and additional_source_addresses are added recently from envoy 1.24.1 version. Could you please give me sample c++ code exmaple in which you are filling extra_source_addresses and additional_source_addresses
