### ISSUE TITLE
Adding correlation between downstream and upstream connection

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27576]
After some recent debugging I noticed that there's no trace log that would be able to correlate between downstream connection and upstream connection. For debugging purposes, I believe it would be useful if there was some log similar to ``[C20] Attached to downstream connection [C19]``. I find it sometimes hard to manually figure out which upstream connection is associated with which downstream connection.

**Comment by wbpcode** [comment]
Sounds reasonable to me. But note the when retry happens, the upstream connection will be changed. But it would be possible to add only single log when the upstream connection ready in the `upstream_request.cc`.

**Comment by ohadvano** [comment]
> It would be possible to add one line log when the upstream connection ready in the upstream_request.cc.

I understand the problem with changing the upstream, but if I only log this in case connection is ready, does it miss the purpose of correlating connection when debugging? I mean, usually you would look at these logs when something's not working, and it may also be that the connection couldn't be established.
