### ISSUE TITLE
Build `cmake` jobs locally (non-RBE) in CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27574]
Mostly the RBE workers are 2-core, whereas (for the build jobs) in CI the vms are far more powerful

Some of the `cmake` jobs (ie `foreign_cc`) can take a long time to build, and dont shard in the way that normal bazel builds do

in CI this results in the high-powered machines sending the jobs off to low-powered machines and waiting, often a long time

not all the CI machines are more powerful, so in those cases we want to ensure it still uses RBE for the build

**Comment by phlax** [comment]
cc @zhxie - in CI the hyperscan build still takes ~700s, this would probably make it more like ~1-200s, with the caveat that if multiple cmake jobs are being rebuilt it will create some contention on the host machine

cc @florincoras - this is the issue i mentioned previously, the vpp build is now pretty fast so not sure if its worthwhile in this case but ill experiment to get a better picture of current ci timings

cc @keith not sure exactly how to acheive this - i guess we want a `select` that either works off `num_cores` or  a custom bazel flag

**Comment by keith** [comment]
for now i think it would be easiest to just force all `cmake` jobs to not use remote exec, seems like not a huge problem

**Comment by phlax** [comment]
> seems like not a huge problem

the problem is in the `checks` stage - they are low-powered and if we were to make them compile all of these they would take hours
