### ISSUE TITLE
local_ratelimit will not send response header when filter_enbaled is 100 but filter_enforced is 0

### ISSUE THREAD

**Issue by vaxilicaihouxian** [envoyproxy/envoy#27591]
envoy.filters.http.local_ratelimit set filter_enabled to 100% and filter_enforced to 0%.
The server response will not add header `x-local-rate-limit: true`.
But I found that doc said `Specifies a list of HTTP headers that should be added to each response for requests that have been rate limited. This occurs when the filter is either enabled or fully enforced`

[doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-local-ratelimit-v3-localratelimit)

<img width="963" alt="image" src="https://github.com/envoyproxy/envoy/assets/8603593/bca07c8b-1a3b-403d-9471-23d02b77f1a1">

**This response can be very useful before the rate limit really block the request for config testing.**

Here is the config:
```
"http_filters": [
             {
              "name": "envoy.filters.http.local_ratelimit",
              "typed_config": {
               "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
               "type_url": "type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit",
               "value": {
                "stat_prefix": "http_local_rate_limiter",
                "token_bucket": {
                 "max_tokens": 1,
                 "tokens_per_fill": 1,
                 "fill_interval": "10s"
                },
                "filter_enabled": {
                 "default_value": {
                  "numerator": 100
                 },
                 "runtime_key": "local_rate_limit_enabled"
                },
                "filter_enforced": {
                 "default_value": {},
                 "runtime_key": "local_rate_limit_enforced"
                },
                "response_headers_to_add": [
                 {
                  "header": {
                   "key": "x-local-rate-limit",
                   "value": "true"
                  },
                  "append": false
                 }
                ]
               }
              }
             }
]
```

**Comment by vikaschoudhary16** [comment]
In case filter is not enforced, `request_headers_to_add_when_not_enforced` can be used.

**Comment by vikaschoudhary16** [comment]
xref: https://github.com/envoyproxy/envoy/pull/28270
