### ISSUE TITLE
gRPC for Envoy

### ISSUE THREAD

**Issue by arkadysafety** [envoyproxy/envoy#2761]
Hi,

I have finally managed to deploy gRPC services running behind Envoy and normally communicate on local, but on AWS it i seem cant make a call from gRPC service 1 to gRPC service 2. 

Im getting this error:
received the unexpected content-type "text/plain"

Locally everything works just fine. Looks like while making a call it transforms request header into text/plain.

**Comment by htuch** [comment]
There's not enough information here to be able to diagnose. It doesn't seem like a bug, so I'm going to close this out and suggest providing a more detailed description to envoy-users@googlegroups.com for community assist.
