### ISSUE TITLE
Support FIPS compliant binary for ARM

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#27620]
*Title*: Support FIPS compliant binary for ARM

*Description*:
Previously, Envoy only provides FIPS-compliant binaries for Linux-x86_64. Since CMVP Certificate [#4407](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4407) has already been tested with ARM, we  can now also provide FIPS-compliant binaries. 

[optional *Relevant Links*:]
* CMVP Certificate [#4407](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4407)
* [Istio ztunnel provides FIPS boringssl binaries for arm.](https://github.com/istio/ztunnel#building)

**Comment by kyessenov** [comment]
Is it not FIPS compliant already?

**Comment by zhaohuabing** [comment]
Currently we don't build FIPS-compliant binaries for ARM.
