### ISSUE TITLE
Dynamic Cluster Definitions for gRPC Services

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#2762]
For the  gRPC services that Envoy acts as a client, for example Metrics, ExtAutz etc have to be defined in the bootstrap configuration as static clusters. It would be good if these services can come from CDS so that Control Plane can truly control the configurations of these cluster definitions.

**Comment by htuch** [comment]
This seems reasonable for things other than CDS itself (i.e. we want to rule out user misconfiguration and catch it early). With that proviso, are you planning on working on this?

**Comment by mattklein123** [comment]
I have strong reservations about adding this feature because it will require a tremendous amount of defensive coding for when one of these clusters suddenly goes away. Do we really need this? If so we might need to introduce some type of concept of a cluster that must be delivered in the initial fetch and then cannot be deleted or something like that.

**Comment by htuch** [comment]
It's true that today we validate cluster existence in construction (https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/async_client_manager_impl.cc#L17) and don't have a good story for recovery if the cluster goes away. With that said, a lot of this will be hidden under the `Grpc::AsyncClient` abstraction and code performing metrics, ext_authz will mostly just need to deal with normal gRPC errors and we could have some fairly standard pattern for this. 

I'd second the question of whether it's really needed. We should motivate any complexity like this with concrete use cases.

**Comment by mattklein123** [comment]
I definitely agree we can handle the errors, but IMO it's a super confusing user experience that no one should actually be doing, but will end up doing by accident, so it will require defensive coding and add to our support burden.

**Comment by mandarjog** [comment]
This has resulted in a breaking change in behaviour for Istio. Pilot delivers mixer cluster information via CDS today. Istio proxy recently started using `AsyncClientFactoryImpl`. 
```  mixer_check_server:
    circuit_breakers:
      default:
        max_pending_requests: 10000
        max_requests: 10000
    connect_timeout_ms: 1000
    features: http2
    hosts:
    - url: tcp://istio-mixer.istio-system:15004
    lb_type: round_robin
    name: mixer_check_server
    type: strict_dns
```
I can update Istio to configure this via bootstrap, but the more number of things we add there, upgrades become difficult.

For now, I will change Istio to use bootstrap for mixer, but it would be good to allow CDS.
@lizan

**Comment by mandarjog** [comment]
For ref: https://github.com/istio/istio/issues/4257

**Comment by saumoh** [comment]
cc @spikecurtis

**Comment by mattklein123** [comment]
If we want to drop this restriction, we will need a full audit of all error handling required. I would also argue that dropping the restriction itself should be an option which defaults to false, given how confusing the behavior will be if the cluster for one of these services suddenly goes away.

**Comment by spikecurtis** [comment]
The concrete use case is that we want to be able to enable `ext_authz` via the xDS APIs. If the auth cluster has to be in the static bootstrap, we have to redeploy in order to start using it.

Just spitballing here: could we define the cluster inline with the filter config?

**Comment by mattklein123** [comment]
> Just spitballing here: could we define the cluster inline with the filter config?

Possible, but large/complex change. I think dropping the requirement on a case by case basis is probably fine, but the error handling needs to be considered and tested for.

**Comment by lizan** [comment]
Another spitballing: Are we going to put same restriction to proposed [http_uri](https://github.com/envoyproxy/data-plane-api/pull/538) definition? It will have same risk that the cluster can suddenly go away. The same risk also exists for Http::AsyncClient too, why we only put the restriction for gRPC cluster definitions? I agree we need auditing error handling but it still shouldn't restrict gRPC async client manager from using dynamic clusters. Can we optionally turn off this restriction by a flag?

**Comment by mattklein123** [comment]
Yes I think we can potentially relax the requirement on a per-component basis as long as the correct error handling (and diagnostics) are in place.

**Comment by mattklein123** [comment]
I think this is largely done. We can track additional issues with specific tickets.
