### ISSUE TITLE
Envoy SDS for AWS and Consul

### ISSUE THREAD

**Issue by ArkadyB** [envoyproxy/envoy#2767]
Hi,

Having successfully launched service mesh on local with docker-compose i cant seem to port my solution to aws. strict/logical DNS service discovery works perfect when i run my microservices locally and can address each service with its given docker-compose name/network name. With AWS we have multicluster system where each services is not guaranteed to run next to the dependant one. Am i right is have no other open than implementing SDS? Is there any existing solution for Consul? 

Thanks for help!

**Comment by htuch** [comment]
Folks have done Envoy integrations for Consul. See http://timperrett.com/2017/05/13/nomad-with-envoy-and-consul for example. CC: @timperrett

**Comment by dnoe** [comment]
If you haven't already joined, #envoy-users on the Envoy Slack (see https://github.com/envoyproxy/envoy/blob/master/README.md for instructions to join) is also a great resource.

**Comment by mattklein123** [comment]
Closing this out. We can discuss on envoy-users@ if needed.
