### ISSUE TITLE
Swagger UI hosting

### ISSUE THREAD

**Issue by jhspaybar** [envoyproxy/envoy#2770]
**Issue Template**

*Title*: Swagger UI hosting for json/rest -> proto/grpc

*Description*:
It is now possible to perform json/rest->proto/grpc mapping. I'd also like the ability to host a swagger UI exposing those json/rest endpoints. As I understand it, Envoy doesn't want to get into the world of generic file server so it isn't possible to generate a static UI and have envoy serve it at the moment either.

[optional *Relevant Links*:]
An example of this is in grpc-gateway https://github.com/grpc-ecosystem/grpc-gateway

**Comment by htuch** [comment]
@jhspaybar I think your second point is a reasonable statement of where we are today. Would it be reasonable to put a minimal web server behind Envoy (as an upstream, possibly inside the same container) to support this in your architecture? Alternatively, we do support some very minimal direct file serving now via https://github.com/envoyproxy/data-plane-api/blob/91e0504c777d280d5d51ff6ca1ffa701c19978fb/envoy/api/v2/route/route.proto#L124.

**Comment by jhspaybar** [comment]
I could have an upstream serving the static content, but I'd prefer not to. Looking at the DirectResponse, it doesn't look like I could plug an entire directory in, so I'd need to map file by file for all js/css/img assets?

**Comment by mattklein123** [comment]
Closing as answered. Please feel free to comment on https://github.com/envoyproxy/envoy/issues/378 if you want to continue the conversation on more complex static file serving.
