### ISSUE TITLE
Should StreamAccessLogs be defined as bidirectional stream RPC to support closing client ghost streams

### ISSUE THREAD

**Issue by maorlipchuk** [envoyproxy/envoy#27712]
*Title*: Use bidirectional stream for StreamAccessLogs to support closing client idle streams

*Description*:
Regarding a system that maintain a server that supports envoy requests from anonymous clients, some of the clients might leave ghost streams that might reflect on the server memory and performance. 
The current client streaming RPC, declared in the StreamAccessLogs proto, leave the server without a way to enforce any keepalive functionality or close the client stream manually.
If StreamAccessLogs will be declared as bidirectional stream RPC then the server can initiate closing on idle client streams

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/accesslog/v2/als.proto#L27

**Comment by phlax** [comment]
cc @mattklein123 @davinci26
