### ISSUE TITLE
Add profiling information for Wasm module with v8 config using VTune Profiler

### ISSUE THREAD

**Issue by rahulchaphalkar** [envoyproxy/envoy#27710]
*Title*: *Add profiling information for Wasm module with v8 config using VTune Profilerr*

*Description*:
Envoy currently does not show any profiling data for wasm functions when profiled with VTune. Adding support for VTune for v8 config will enable the user to gain performance insights into their wasm filters.

I am happy to contribute by creating a PR. Let me know if more details are needed here.

**Comment by phlax** [comment]
cc @kyessenov @mpwarres

**Comment by rahulchaphalkar** [comment]
Any update on this?

**Comment by mpwarres** [comment]
Sure, would be happy to review a PR. What values are involved in enabling V8 VTune profiling support, and how do you envision representing this in Envoy Wasm config?

**Comment by rahulchaphalkar** [comment]
Thanks @mpwarres .
My PR plans on enabling VTune support as a build flag passed to Envoy, similar to `bazel build --define vtune_profile=True envoy`, and based on this flag, enabled additional hooks in `v8.patch` file. 
I have added new build flags based off of this issue https://github.com/envoyproxy/envoy/issues/27326#issuecomment-1545947630

**Comment by rahulchaphalkar** [comment]
Hi @mpwarres , I have submitted a PR for this change https://github.com/envoyproxy/envoy/pull/27890
