### ISSUE TITLE
Is retry on grpc status code "UNKNOWN" supported ?

### ISSUE THREAD

**Issue by deveshkandpal1224** [envoyproxy/envoy#27740]
While reviewing this doc https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on I do see a bunch of grpc status codes that are called out. Is my understanding correct that "UNKNOWN" is not a supported status code for retry ?

**Comment by deveshkandpal1224** [comment]
@alyssawilk @mattklein123 - is my understanding correct that envoy will only retry for these scenarios https://github.com/envoyproxy/envoy/blob/main/source/common/router/retry_state_impl.cc#L191-L243 and ignore any other GRPC status code that may not be stated here -> https://grpc.github.io/grpc/core/md_doc_statuscodes.html ?

**Comment by alyssawilk** [comment]
I believe that's correct, though I think it'd be fine to extend it to include UNKNOWN if you'd like.  This is just the set folks have needed so far.
