### ISSUE TITLE
Empty lua filter on HTTP listener caused envoy memory to double

### ISSUE THREAD

**Issue by Champ-Goblem** [envoyproxy/envoy#27759]
### Some background on the setup:

We are attempting to move external authorization and IP-based RBAC to the Istio gateway and away from the individual sidecar proxies in the service mesh so that these security filters continue to work in cases where the sidecar proxies are not injected.

Our setup has a wildcard domain set on the Istio gateway level. Each individual domain under the wildcard domain is set on a virtual service which then maps to a specific service.

In terms of envoy configuration, this setup leads to an envoy listener with an HTTP connection manager filter that matches the wildcard domain. The virtual services create multiple virtual host routes that match the specific domains under the wildcard domain umbrella.

The problem with this configuration is when trying to apply external authorization or RBAC, we end up applying the rules to all domains under the wildcard domain rather than on each individual domain (virtual route). Browsing through the Envoy Proxy issues pointed to a solution making use of dynamic metadata in order to enable/disable these specific security filters https://github.com/envoyproxy/envoy/issues/12556#issuecomment-736855821.

### Getting it working:

In order to run the above lua function to set the dynamic metadata on the streamInfo API, there had to be some basic lua function that already exists on the listener to override the contents. We added a dummy lua filter that performed no processing on the request but allowed it to be easily overwritten.

As an Istio Envoy Filter that looked like the below:

```jsx
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
        portNumber: 8443
    patch:
      operation: INSERT_FIRST
      value:
        name: ext-authz.set-metadata
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              -- Empty lua function
            end
```

This leads to a listener filter chain like so:

```jsx
{
          "filter_chain_match": {
           "server_names": [
            "*.example.com"
           ]
          },
          "filters": [
           {
            "name": "envoy.filters.network.http_connection_manager",
            "typed_config": {
             "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
             "stat_prefix": "outbound_0.0.0.0_8443",
             "rds": {
              "config_source": {
               "ads": {},
               "initial_fetch_timeout": "0s",
               "resource_api_version": "V3"
              },
              "route_config_name": "https.443.gw-tls.gw.istio-system"
             },
             "http_filters": [
              {
               "name": "ext-authz.set-metadata",
               "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua",
                "inline_code": "function envoy_on_request(request_handle)\n  -- Empty lua function\nend\n"
               }
              },

              ...

         },
```

Then on the virtual route, we would set up an envoy filter patch that would use the `LuaPerRoute` filter to override the lua function on the listener and thus set the dynamic metadata:

```jsx
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: some.domain.exmaple.com:443
          route:
            name: default
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.lua:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
            name: ext-authz.set-metadata
            source_code:
              inline_string: |-
                function envoy_on_request(request_handle)
                  request_handle:streamInfo():dynamicMetadata():set("ext_auth", "authz","test");
                end
```

This dynamic metadata could then be matched via the `filter_enabled_metadata` fields of the external auth/RBAC filters.

### The problem:

When setting the empty lua filter, without applying any specific `LuaPerRoute` filters, we saw the memory of the gateway instances all double. The below graph illustrates the change in memory usage (in MiB) of the gateways when the empty lua function was applied at 22:30:

![image](https://github.com/envoyproxy/envoy/assets/19267423/6ad65c8c-cb72-4eeb-8891-3ed5cceb4d70)

The envoy filter was removed at 22:40 causing the function to be deleted from the config, after restarting the gateways the memory usage went back to its previous value.

The above illustrates two issues:

1. The inability to easily configure ext-auth and RBAC filters on the route level so that these are not applied to all traffic destined for a wildcard domain
2. Applying a dummy lua function that doesn't perform any processing on the request causes memory usage to double 

Is there an easy solution to enable/disable, or even set security filters on the per route level? That way they aren't applied to all traffic destined for some top-level domain.

In the case of memory usage, such a drastic increase for a function that does no processing doesn't seem right, is this expected behavior?

Thank you in advance if anyone can provide any pointers or alternative ideas

**Comment by kyessenov** [comment]
I don't think per-route enablement is the problem with Lua. My guess is that each instance of Lua filter is likely taking a fixed amount of resources and when multiplied by the number of the filter chains, the overhead is significant. Envoy has to instantiate a filter even if only one route is using it.

You could probably get better performance with Wasm. Istio configures Envoy to create a single shared VM instance per plugin that is cloned/CoW and can better utilize memory AFAIK. However, I see you need to write dynamic metadata and that's missing from Wasm ABI.

**Comment by kyessenov** [comment]
Yes, that would be fine to support per-route override for set-metadata, that sounds quite reasonable. In general for your question, Istio doesn't have a reliable way to attach filters to hosts/routes exclusively. EnvoyFilter is likely to break during upgrades, especially if you decide on using k8s Gateway APIs later on. One way around this is to push the selection down to the filter, for example using ExtensionWithMatcher with ext_authz that performs its own matching and disables itself when necessary.
