### ISSUE TITLE
Changing clear_route_cache from ext_proc server CommoneResponse into a more meaningful name

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#27772]
*Title*: *Changing clear_route_cache from ext_proc server CommoneResponse into a more meaningful name*

*Description*:
clear_route_cache:
https://github.com/envoyproxy/envoy/blob/d29dcb1ce058edcfcd80737c0a097f776b6759fa/api/envoy/service/ext_proc/v3/external_processor.proto#L291

is a flag in ext_proc server response specific to downstream client request.  For ext_proc server response to upstream response  message, this flag should never be set.

Suggesting change this API for better naming. Please check below discussion for details:
https://github.com/envoyproxy/envoy/pull/27657#discussion_r1213264831

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yanavlasov** [comment]
This is not just about naming. The flag for clearing route cache is only applicable for ext_proc responses to request headers processing. The proto API needs to be changed to only provide this flag in the responses to request headers processing.

**Comment by yanjunxiang-google** [comment]
@tyxia

**Comment by yanjunxiang-google** [comment]
@htuch @yanavlasov

**Comment by htuch** [comment]
This seems broadly a good idea. @gbrail can you weigh in on these changes and the original motivation for placement in a common message? Thanks.
