### ISSUE TITLE
External authentication must HTTPS if Envoy using certificate?

### ISSUE THREAD

**Issue by Haim-Barilan** [envoyproxy/envoy#27789]
Hi,

I have envoy configured and running with Lets Encrypt certificate.

I have also .net core http service for external authentication running on the same machine.

If I send a request to one of the routes, I got response 404 with no certificate in the response.
Without external authentication everything works as expected.

Same service works as expected in local docker-compose without certificate and all setup is plain HTTP.

**Comment by ravenblackx** [comment]
I'm not sure what the question is here. Could you elaborate, and include some relevant configuration files?

**Comment by Haim-Barilan** [comment]
I'm closing the question since it was a misunderstanding of the docs from my side.
Thanks.
