### ISSUE TITLE
generic proxy: initial stats support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#27801]
*Title*: *generic proxy: initial stats support*

*Description*:
Add initial simple stats support to generic proxy.

**Comment by wbpcode** [comment]
cc @LaurenLiu123

**Comment by liulanyi** [comment]
Hi @wbpcode  I will take this task. Thanks

**Comment by liulanyi** [comment]
Hi @wbpcode  I will take this task. Thanks
