### ISSUE TITLE
NO_TRAFFIC_INTERVAL constant causes deployments to needlessly take at least a minute

### ISSUE THREAD

**Issue by ikatson** [envoyproxy/envoy#2782]
We use AWS load balancer in front of envoy, which is used as a sidecar. Envoy proxies all external traffic into our local application.

When the application comes up for the first time, envoy waits 60 seconds between healthcheck attempts because of NO_TRAFFIC_INTERVAL constant, which is used in case there's no external traffic into the cluster. 

However, there can be no external traffic at this point, as for it to come, the healthcheck needs to become healthy at least once.

What can we optimize to workaround this? Ideally, we'd like to be able to tune the NO_TRAFFIC_INTERVAL timeout ourselves to disable this behavior.

Here's the config we use, note the ```envoy.health_check``` http_filter that is the endpoint that is served to AWS load balancer.

```static_resources:
  clusters:
    name: local_tomcat
    connect_timeout: 0.1s
    health_checks:
    - healthy_threshold: 2
      http_health_check:
        path: "/app/status"
      interval: 5s
      timeout: 5s
      unhealthy_threshold: 3
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080
    lb_policy: LEAST_REQUEST
    type: STATIC
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          http_filters:
            - name: envoy.health_check
              config:
                cluster_min_healthy_percentages:
                  local_tomcat:
                    value: 100
                endpoint: "/healthz"
                pass_through_mode: false
            - name: envoy.router
          route_config:
            name: localhost_proxy
            virtual_hosts:
            - domains: "*"
              name: localhost_proxy
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_tomcat
                  timeout: 60s
        
      tls_context: {...}
    name: localhost_proxy
```

**Comment by mattklein123** [comment]
@ikatson when Envoy initializes, it does a single HC pass, regardless of the no traffic interval, which should be able to quickly determine backend health. Can you make sure you are not seeing this behavior? If not there is a bug somewhere.

**Comment by ikatson** [comment]
@mattklein123 we worked around it by starting envoy sidecar ONLY when the application has come up.
So essentially, the envoy script looks smth like.

```
until application_is_up; do
    sleep 1
done
exec envoy
```

So the issue is when the envoy starts up before the application, the first health check does not succeed, and the next one is only run 60 seconds after, which is too long

**Comment by mattklein123** [comment]
OK. The NO_TRAFFIC_INTERVAL stuff is kind of a hack. We should probably make it configurable. I'm switching this over to enhancement/help wanted.
