### ISSUE TITLE
change log level for gateway TLS cert problem

### ISSUE THREAD

**Issue by taitelman** [envoyproxy/envoy#27839]
*Title*: *raise TLS parse warning log level*

*Description*:

I badly rotated my istio gateway HTTPS cert secret. The certificate was corrupted (will show later how) .
istio ingress gateway pod reported (v1.16.4):
```
Jun 6 18:03:21 xxx-ingressgateway-7c5c96bbc-8cf7t istio-proxy warning envoy config	gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load certificate chain from <inline> 
```
and it kept using the older (valid in-memory) certificate until a pod reboot.
 
any request sent to such (badly configured) mesh will get an SSL handshake error:
```
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
```

if you want to reproduce simply take two pem files 
and connect them badly to one file that will look like:
```
-----BEGIN CERTIFICATE-----
MIIGaTCCBVGgAwIBAgISBN9zjJPJo/TDv12Msdaz2Hm4A0GCSqGSIb3DQEBCwUA
MDIxCzAJBgN1YTAlVTMRYwFAYDV4KEw1MZX...
EgAjnpN/MnNPjwvJSw==
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
CJ5yJu5zlzyZM3AvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBME1q4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFO.....
-----END CERTIFICATE-----
```

and save it as your istio gw TLS  secret 

**Describe alternatives you've considered**
I want to raise the log level to an `error` . current warning is not very descriptive. may want to add "future SSL handshakes will fail."  the problem is the code doesn't really differentiate between SSL problem and other issues.
so maybe one should add an additional log.error printout closer to the cert parser code.

source: https://github.com/envoyproxy/envoy/blob/522f0551adf70a9fa27edf7088de0c6d2d14d63f/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc#L128

Alternatively improve `istioctl analyze` to detect such condition ?

**Comment by taitelman** [comment]
see also https://github.com/istio/istio/issues/22530

**Comment by ravenblackx** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
Anything involving `istioctl` should be raised with istio, not here.

The log line you linked to is printed for any xDS update failure, not just certificates. We could add additional logging around certificates updates though.

I think you can watch for metrics for this type of failure by looking for the following: 

```
sds.<name>.update_attempt: 1
sds.<name>.update_failure: 0
sds.<name>.update_rejected: 0
sds.<name>.update_success: 1
```
