### ISSUE TITLE
Backend health provided by EDS doesn't work properly with stateful session/override health status

### ISSUE THREAD

**Issue by bbassingthwaite** [envoyproxy/envoy#27830]
*Title*: Backend health provided by EDS doesn't work properly with stateful session/override health status

*Description*:

We use EDS (over ADS) to dynamically control cluster load assignments and we control the health of each member from the management server. In our use case we use the HDS (Health Discovery Service) to collect endpoint health and will propagate this health status via EDS. We also use StatefulSession using an HTTP cookie and use `overrideHostStatus` with `HEALTHY`, `UNKOWN` and `DEGRADED`.  Since upgrading to Envoy 1.26 from Envoy 1.22, we now have an issue where stateful sessions no longer work.

#24094 introduced a change that uses `healthStatus()` instead of `coarseHealth()` which introduced this issue. Setting the `envoy.reloadable_features.validate_detailed_override_host_statuses: false` resolves the issue for us but this isn't a permanent solution.  

It seems that endpoint health delivered by EDS doesn't properly work with this change. For example, when an endpoint is marked as unhealthy via EDS `coarseHealth()` properly returns `Unhealthy` but `healthStatus()` returns `HealthStatus.HEALTHY`

*Repro steps*:
Running on Envoy 1.26 but change was introduced in 1.25. Use StatefulSession/Cookie and update endpoint health with EDS from healthy to unhealthy.

cc @wbpcode

**Comment by wbpcode** [comment]
I will check it in next days. Thanks for the report.
