### ISSUE TITLE
Validation of supported Ciphers

### ISSUE THREAD

**Issue by pramodrj07** [envoyproxy/envoy#27832]
*Title*: *Validation of supported Ciphers*

*Description*:
> Need help in verifying if the list of supported Ciphers is precise

*Repro steps*:
> The list of Ciphers supported by boringSSL is  - https://stackoverflow.com/questions/74828846/is-there-a-list-of-which-ciphers-suites-boringssl-lib-supports. I have added all these into the TLSContext and can verify that it all these are present in the admin config

Steps
>
$ run the testssl.sh tool (Unsure if this is a precise tool to run) against running envoy instance
$ git clone git@github.com:drwetter/testssl.sh.git
$ cd testssl.sh
$ ./testssl.sh localhost:8443

Got the below result as output
Testing server's cipher preferences

Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
SSLv2
 -
SSLv3
 -
TLSv1
 -
TLSv1.1
 -
TLSv1.2 (server order)
 x02     NULL-SHA                          RSA        None        None     TLS_RSA_WITH_NULL_SHA
 x0a     DES-CBC3-SHA                      RSA        3DES        168      TLS_RSA_WITH_3DES_EDE_CBC_SHA
 x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA
 x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA
 x9c     AES128-GCM-SHA256                 RSA        AESGCM      128      TLS_RSA_WITH_AES_128_GCM_SHA256
 x9d     AES256-GCM-SHA384                 RSA        AESGCM      256      TLS_RSA_WITH_AES_256_GCM_SHA384
 xc013   ECDHE-RSA-AES128-SHA              ECDH 253   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
 xc014   ECDHE-RSA-AES256-SHA              ECDH 253   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
 xc02f   ECDHE-RSA-AES128-GCM-SHA256       ECDH 253   AESGCM      128      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH 253   AESGCM      256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 xcca8   ECDHE-RSA-CHACHA20-POLY1305       ECDH 253   ChaCha20    256      TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLSv1.3 (no server order, thus listed by strength)
 x1302   TLS_AES_256_GCM_SHA384            ECDH 253   AESGCM      256      TLS_AES_256_GCM_SHA384
 x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH 253   ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256
 x1301   TLS_AES_128_GCM_SHA256            ECDH 253   AESGCM      128      TLS_AES_128_GCM_SHA256

>*Note*: I would like to know if the data is precise or if i should use any other tool such as Nmap to verify that these ciphers' support from client application
sharing.

**Comment by pramodrj07** [comment]
@alyssawilk @PiotrSikora

**Comment by ggreenway** [comment]
@pramodrj07 I don't understand what you're asking for help with. I've never heard of this `testssl` tool so I can't tell you if it is useful or not.

**Comment by pramodrj07** [comment]
> @pramodrj07 I don't understand what you're asking for help with. I've never heard of this `testssl` tool so I can't tell you if it is useful or not.

@ggreenway - I am asking if these are the set of Ciphers that envoy supports. 
I am not exactly asking the authenticity of the tool(testssl) itself. If there is any other tool that you recommend, I would be happy to give it a shot.

**Comment by ggreenway** [comment]
Got it. I don't think there's a way to get the full list of supported ciphers from envoy. You might be able to get the same version of boringssl that envoy is using (which changes over time) and query it somehow. You can also try known ciphersuite names in a tls context configuration. If loading the config doesn't produce an error, that cipher suite is supported.

**Comment by pramodrj07** [comment]
> n also try known ciphersuite names in a t

Perfect. This makes sense. Ty for the help 👍🏽
