### ISSUE TITLE
HTTPS Passthrough with host name filtering

### ISSUE THREAD

**Issue by maoudia-via** [envoyproxy/envoy#27831]
*Title*: *Can I configure Envoy to perform TLS passthrough while at the same time filtering egress traffic by host name*

*Description*:
I am trying to filter traffic originating from a client  behind an envoy proxy and going to known hosts that I don't necessarily control.
The filtering should happen by host name (SNI). 
I have tried using the network RBAC filter with no luck. Also that filter seems to only support destination ip addresses. 
Is there a known way to achieve what I am trying to do ? 
-----------               -----------                  -------------------
| client  |  --------> | Envoy | -----------> | nytimes.com| 
-----------               -----------                  -------------------

-----------               -----------                  --------------------------------
| client  |  --------> | Envoy | -----X-----> | forbiddenwebsite.com| 
-----------               -----------                  --------------------------------

I also want to extend this to general TCP traffic. Is this achievable ?
A configuration example would be much appreciated !

**Comment by maoudia-via** [comment]
Thank you for your answer.
I have the following configuration:

`
static_resources:
  listeners:
  - name: listener_443
    address:
      socket_address: {address: 0.0.0.0, port_value: 443}
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    filter_chains:
    - filters:
      - name: envoy_rbac
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          stat_prefix: "allowed_"
          rules:
            action: ALLOW
            policies:
              "allow":
                principals:
                  - any: true
                permissions:
                - and_rules:
                    rules:
                    - requested_server_name:
                        contains: "nytimes.com"
                    - destination_port: 443
`
However, when looking the the logs I see the following:
- CONNECTION_TERMINATION_DETAILS  is rbac_access_denied_matched_policy[none]
- REQUESTED_SERVER_NAME is empty.

It looks like the requested_server_name is not captured.

**Comment by ravenblackx** [comment]
This is why I said to pay special attention to the bit about prerequisites in the linked doc. (Bold added.)

> The behavior of this field may be affected by how Envoy is configured as explained below.
> 
> If the [TLS Inspector](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector#config-listener-filters-tls-inspector) filter is not added, **and if a FilterChainMatch is not defined for the [server name](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-field-config-listener-v3-filterchainmatch-server-names)**, a TLS connection’s requested SNI server name will be treated as if it wasn’t present.
> 
> A [listener filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/listener_filters#arch-overview-listener-filters) may overwrite a connection’s requested server name within Envoy.

And in the linked example:
```
 - filter_chain_match:
   server_names: "api.example.com"
```
