### ISSUE TITLE
Support for hedged requests 

### ISSUE THREAD

**Issue by jacktuck** [envoyproxy/envoy#2784]
Could hedged requests (or backup requests in finagle) be supported?

https://www2.cs.duke.edu/courses/cps296.4/fall13/838-CloudPapers/dean_longtail.pdf

> Hedged requests. A simple way to
> curb latency variability is to issue the
> same request to multiple replicas and
> use the results from whichever replica
> responds first. 

![image](https://user-images.githubusercontent.com/8209433/37336546-a0dc698c-26a9-11e8-8f69-905a2ff542a9.png)

**Comment by mattklein123** [comment]
For others searching for this, this is AKA "request racing." We have had many requests for this feature over the life of Envoy but it's never quite bubbled up to high enough priority for someone to implement. Marking help wanted. It's very doable but also non-trivial.

**Comment by htuch** [comment]
@mpuncel assigned.

**Comment by gaocegege** [comment]
Hi is there any progress here?

**Comment by gunta** [comment]
+1

**Comment by christian-posta** [comment]
https://www.envoyproxy.io/docs/envoy/v1.12.2/intro/arch_overview/http/http_routing#request-hedging
