### ISSUE TITLE
Connection limit per client filter

### ISSUE THREAD

**Issue by juan-vg** [envoyproxy/envoy#27853]
*Title*: Add support for limiting number of connections per each client

*Description*:
>Envoy has the capability to limit the absolute number of connections via the network connection limit filter. It would also be useful to be able to limit the number of connections per each client, specifically on a per filter chain basis or based on some descriptors from the request.

**Comment by ravenblackx** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
sorry when you say per client, I'm not sure exactly what you mean. Can you elaborate a bit?

**Comment by juan-vg** [comment]
Sure! Client means IP address. Therefore, this filter should limit the number of concurrent connections from each source IP address. As a use case: limit the number of connections to a proxied DB from the same origin while still allowing connections from new/not-limited, different sources. 

Don't hesitate to let me know if you have more doubts or suggestions!
