### ISSUE TITLE
[question] Can envoy drain existing connection on eds host removal?

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#27863]
I am using tcp-proxy with envoy,without active health check.I want to drain existing upstream and downstream connection when eds host removal,because the upstream service may still work but not serve as expect.

**Comment by ravenblackx** [comment]
cc @adisuissa

**Comment by pyrl247** [comment]
@adisuissa  Thanks for reply. These options can not help.
For example:
1. There art 3 hosts ,ep1,ep2,ep3,and no active health check.
2. Make a new connection with tcpproxy: downstream1 -> envoy -> ep1.
3. Update eds as ep2,ep3(remove ep1).
We expect the connection betweent downstream1 and envoy to close when ep1 is removed.
