### ISSUE TITLE
Update_Attempt stat for Static Cluster

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#2786]
We have defined a static cluster called test and the stats for this cluster show as shown below

```
cluster.test.update_attempt: 86
cluster.test.update_empty: 0
cluster.test.update_failure: 0
cluster.test.update_success: 86
```
Not sure, why the `update_attempt` stat is showing as 86 and that too for a static cluster, looks like a bug to me.

**Comment by mattklein123** [comment]
Not sure why this is happening. Someone will need to investigate.

**Comment by ramaraochavali** [comment]
@mattklein123 I did some investigation today and here are my findings. This does not happen for cluster type STATIC. This happens for static clusters of type `STRICT_DNS` or `LOGICAL_DNS`. 
This happens because of the [code](https://github.com/envoyproxy/envoy/blob/e765c2c6762aaf04fabf21beb16f367d0760dcc5/source/common/upstream/upstream_impl.cc#L666) . I think this update should be moved [here](https://github.com/envoyproxy/envoy/blob/e765c2c6762aaf04fabf21beb16f367d0760dcc5/source/common/upstream/upstream_impl.cc#L691) when there is actually change in hosts and we are updating the list. Similarly the [success increment](https://github.com/envoyproxy/envoy/blob/e765c2c6762aaf04fabf21beb16f367d0760dcc5/source/common/upstream/upstream_impl.cc#L673) should be moved after the update call. 

If the update just means DNS resolution - probably we can leave it like the way it is.

**Comment by mattklein123** [comment]
@ramaraochavali `update_attempt` means a DNS resolution attempt. I think it's working as designed. If you agree feel free to close. Thank you.

**Comment by ramaraochavali** [comment]
@mattklein123 thanks. Will close it.
