### ISSUE TITLE
Jwt Authentication filter falsely authenticates invalid JWT made up of a valid JWT followed by a space and additional characters

### ISSUE THREAD

**Issue by danieldradware** [envoyproxy/envoy#27877]
*Title*: *Jwt Authentication filter falsely authenticates invalid JWT made up of a valid JWT followed by a space and additional characters*

*Description*:
>When sending a valid token followed by a space and some other character, the JWT Authentication filter considers it as a valid token. 
I checked this same thing with Auth0 server and its response for this case was:
{
   "statusCode": 400,
   "error": "Bad Request",
   "message": "Bad HTTP authentication header format",
   "errorCode": "Bearer"
})
In addition, RFC 7519 implies that adding non-Base64URL characters after a valid JWT token makes it invalid. Thus, if I will add space and after that some character or if I will add in the end of valid token some non-Base64 characters like ### (without any space)
The JWT Authentication filter however will consider these types of tokens as valid token

*Repro steps*:
> 1.	Deploy Envoy env with jwt filter 
> 2.	send request with Authorization header and value is Bearer + your token + space + some characters (as mentioned in the example)

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Solution*:
>source/extensions/filters/http/jwt_authn/extractor.cc
>In code we suggest to remove all lines from "ending" variable to the end of function and instead return "value_str.substr(starting) [delete lines 327-332]
>
![image](https://github.com/envoyproxy/envoy/assets/117576776/92e505fa-4464-4643-88c1-20921e9898d7)
>According to RFC7519 in this case the token is invalid and currently this function “cuts out” the non-Base64URL part and passes the token only which it itself is valid.
So, in this case we want to return the complete token (including the non-Base64 part) and then Envoy will mark it as invalid token.

**Comment by danieldradware** [comment]
@lizan @larrywest

**Comment by danieldradware** [comment]
Hi @lizan 

Please your advise

Thanks
Daniel

**Comment by danieldradware** [comment]
I already opened a PR with fix to this issue.
@lizan @larrywest can you please activate this issue again till I will get your permit to push the fix?
Thanks
Daniel

**Comment by weissne** [comment]
@danieldradware Thanks for opening a PR for this.
@lizan - Can you please review it ? (https://github.com/envoyproxy/envoy/pull/28678)

**Comment by sambercovici** [comment]
@yanavlasov - Can you please review (https://github.com/envoyproxy/envoy/pull/28678) ?
