### ISSUE TITLE
Access log command operators return value

### ISSUE THREAD

**Issue by searedsee** [envoyproxy/envoy#27901]
I am using the %CONNECTION_TERMINATION_DETAILS% access log command operator for holding a Message variable with connection termination details in json_format access log (like below).

When there is no termination happening, the value emitted by this is null in the logs. Instead of null can I have it emit an empty string? As I have logging requirements for values to be either empty strings or 0 for integers when the value is not available.

          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": [type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog](http://type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog)
                log_format:
                  json_format:
                    ApplicationProtocol: "%REQ(:SCHEME)%"
                    Message: "%CONNECTION_TERMINATION_DETAILS%"

Thanks!!

**Comment by KBaichoo** [comment]
See: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators

Particularly 
> Note that if a value is not set/empty, the logs will contain a - character or, for JSON logs, the string "-". For typed JSON logs unset values are represented as null values and empty strings are rendered as "". [omit_empty_values](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/substitution_format_string.proto#envoy-v3-api-field-config-core-v3-substitutionformatstring-omit-empty-values) option could be used to omit empty values entirely.

`omit_empty_values` might work for your use case

**Comment by searedsee** [comment]
@KBaichoo omit_empty_values will remove the field completely but in my case I want the field to be emitted with "" instead of null. Any other suggestions? I didn't find any other way to achieve this and I am thinking I should take care of the nulls on post processing side (fluentd) but it will add overhead..

**Comment by KBaichoo** [comment]
I don't think there's a way to do exactly what you want with just config then; this might require post-processing.

cc @ohadvano if you have any ideas since you've worked on this area
