### ISSUE TITLE
golang filter: add lock in the Go side to avoid concurrency race

### ISSUE THREAD

**Issue by doujiang24** [envoyproxy/envoy#27914]
Since people may use multiple goroutines to process the same stream, so, there might be concurrency happens.

fields we should protected:
1. Go side `headerMapImpl.headers` and concurrency for read/write this map.
2. C++ siede `httpRequestInternel.strValue`, see a example: https://github.com/mosn/envoy-go-extension/pull/64/files
3. maybe others.

**Comment by maguro** [comment]
Many thanks @StarryVae!  Is this issue considered done?

**Comment by StarryVae** [comment]
yeah, it is basically done by this pr #27959

**Comment by doujiang24** [comment]
consider done in https://github.com/envoyproxy/envoy/pull/27959
