### ISSUE TITLE
Question: Override upstream response headers in successful ExtAuthz response

### ISSUE THREAD

**Issue by shamsimam** [envoyproxy/envoy#27922]
*Title*: Override upstream response headers in successful ExtAuthz response

*Description*:

As per documentation: the configuration, `allowed_client_headers_on_success`, on the ExtzAuth http service controls which headers will be _added_ to the client’s response on success. This configuration _appends_ the headers to the upstream response. Is it possible to instead _override_ the upstream response header using a header from the authorization response headers instead?

As an example: if authorization response header is `foo: bar` and upstream response header is `foo: baz`, including `foo` via `allowed_client_headers_on_success` causes the eventual response emitted to the client includes value from authorization and upstream responses: `foo: baz, bar`. Is it possible to have the response emitted to the client be only the header be `foo: bar`.

[optional *Relevant Links*:]

> [allowed_client_headers_on_success on AuthorizationResponse](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-field-extensions-filters-http-ext-authz-v3-authorizationresponse-allowed-client-headers-on-success)

**Comment by KBaichoo** [comment]
cc @tyxia @ggreenway 

as ext_athz code owners

**Comment by shamsimam** [comment]
@ggreenway  Thank you very much for the suggestion of using {{headers_to_remove}}. We got it to work and remove the CORS response headers emitted by the upstream backend. The CORS response headers from the ExtAuth filter successfully make it to downstream.
