### ISSUE TITLE
Access logs - log headers returned from external auth server?

### ISSUE THREAD

**Issue by omerlh** [envoyproxy/envoy#27937]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Access logs - log headers returned from external auth server?*

*Description*:
We are using envoy external auth with custom server to authenticate requests. The server returns the user identity in a header, and I would like this header to be part of the audit log. 
Can I use `%REQ(X?Y):Z%` to access headers set by the external auth server?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/access_log#format-dictionaries
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter

**Comment by KBaichoo** [comment]
Can I use %REQ(X?Y):Z% to access headers set by the external auth server?
> Yes that should work as documented
%REQ(X?Y):Z%
An HTTP request header where X is the main HTTP header, Y is the alternative one, and Z is an optional parameter denoting string truncation up to Z characters long. The value is taken from the HTTP request header named X first and if it’s not set, then request header Y is used. If none of the headers are present ‘-’ symbol will be in the log.
src: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log

**Comment by omerlh** [comment]
I just checked and using %REQ(X?Y):Z% will not work - envoy will not log this header

**Comment by j2gg0s** [comment]
You now have:
- downstream reqeust & response
- upstream request & response
- auth request & response

You want to log downstream request with user identify in auth response?
Maybe you should add this auth response header to downstream request.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-authorizationresponse

**Comment by omerlh** [comment]
Yep, this is what I did. The header is added to the request and passed to the upstream service but when trying to access it in the access log all I see is null

**Comment by j2gg0s** [comment]
> Yep, this is what I did. The header is added to the request and passed to the upstream service but when trying to access it in the access log all I see is null

@omerlh You can show the specific configuration?

**Comment by omerlh** [comment]
Sorry! This is working as expected now :) Keeping the config for reference in case anyone notice similar case in the future
