### ISSUE TITLE
grpc access logging/metrics: add option to cycle streams

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2795]
There is no good way to tell long running gRPC streams that they need to cycle due to upstream GOAWAY. We should add the ability to cycle the streams on a per-time basis to workaround this. Another option is to add the ability for streams to register for GOAWAY notification, and if applicable they could then cycle at the "app" level. E.g., The access log implementation could see that a GOAWAY was received and make a new stream. We can investigate the right option here.

**Comment by htuch** [comment]
@mattklein123 I'm a bit confused. When we get an upstream GOAWAY, shouldn't the H2 stream close and the various use sites receive a remote close?

**Comment by btc** [comment]
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#goaway-frame

> Sent by servers to clients to indicate that they will no longer accept any new streams on the associated connections. This frame includes the id of the last successfully accepted stream by the server. Clients should consider any stream initiated after the last successfully accepted stream as UNAVAILABLE and retry the call elsewhere. Clients are free to continue working with the already accepted streams until they complete or the connection is terminated.

> Servers should send GOAWAY before terminating a connection to reliably inform clients which work has been accepted by the server and is being executed.

It seems in gRPC, Go away doesn't signal stream termination. It merely prevents new stream creation.

**Comment by mattklein123** [comment]
@htuch no, GOAWAY is just an indication to not create new streams, not to terminate existing ones. (This is related to what @btc mentions but not specific to Go).

There are 2 separate issues here. 

1) For Envoys that are sending long running streams (access log, metrics, etc.), in the current implementation when we shutdown we don't cleanly end the stream. We just reset it. This is related to shutdown hooks that @mrice32 is going to work on.
2) For Envoys that are receiving long running streams as a proxy (say the Envoy sitting in front of the access log service), there is no ability currently to indicate that a connection/stream needs to be drained that is long running. This is because in the current code, "drain close" decisions take place at the end of responses, which will never happen in this case. We likely need to decide if we want to add the ability to also send GOAWAY on connections that have ongoing streams that might never end.

On the receiving side, if we get a GOAWAY, we could add a stream decoder level event that lets the "app level" (access logger) know that the connection is no longer valid. In this case, it could just reconnect and make a new stream.
