### ISSUE TITLE
envoy 1.26.0 fails to build on Redhat 8.4

### ISSUE THREAD

**Issue by zipsantro** [envoyproxy/envoy#27961]
We are interested on building using source tar ball and followed the steps mention in envoy/bazel/README.md. It failed to proceed with compilation with below error. 
Build config - 
```
OS: Red Hat Enterprise Linux release 8.4 (Ootpa)
user.bazelrc: build --config=clang
LLVM+clang: clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04
``` 

Build error
```console
$ bazel build -c opt envoy
INFO: Analyzed target //:envoy (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/24436e864e1ac7ab906c0253abe83400/external/antlr4_runtimes/BUILD.bazel:3:11: Compiling runtime/Cpp/runtime/src/BailErrorStrategy.cpp failed: (Exit 1): gcc failed: error executing command (from target @antlr4_runtimes//:cpp) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 24 arguments skipped)
```

**Comment by phlax** [comment]
it looks like its using `gcc` not `clang` - is `clang` on `$PATH` ?

**Comment by zipsantro** [comment]
Yes, clang in path and being referred to `/usr/bin/clang`

**Comment by phlax** [comment]
i am running locally with just that in the `user.bazelrc` - it didnt fail so far but can take a long time

without `clang` in `PATH` i got a lot of errors

perhaps try running with `ci/do_ci.sh release.server_only` as that will setup env vars - although not 100% how it would work in your env

the ~more supported way to build is with the build container - but im guessing you want to build for a different glibc version

**Comment by phlax** [comment]
(re running locally this is with a debian bullseye base but not the standard container)

**Comment by nikita96** [comment]
Facing this issue from envoy 1.25.0
Earlier versions are built successfully on linux 8.4

**Comment by nikita96** [comment]
I followed below steps to build envoy 1.26.2 : 

1. Install Bazel
`sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-$([ $(uname -m) = "aarch64" ] && echo "arm64" || echo "amd64")`
`sudo chmod +x /usr/local/bin/bazel`

2. Install cmake
`yum install cmake`

3. Install clang
`yum install clang`

4. Install ninja
`yum install ninja-build`

5. Install external dependencies as mentioned in bazel README
`sudo wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz`

6. Download and extract envoy 1.26.2 tar ball

7.  Run following command to setup clang
`bazel/setup_clang.sh <PATH_TO_EXTRACTED_CLANG_LLVM>`
`echo "build --config=clang" >> user.bazelrc`

8. Build envoy 
`bazel build -c opt envoy`

Error snippet is as follows : 
INFO: Analyzed target //:envoy (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/14f0c640799f93c0c82a089b9eaec88b/external/com_google_absl/absl/base/BUILD.bazel:83:11: Compiling absl/base/internal/spinlock_wait.cc failed: (Exit 1): clang-11 failed: error executing command (from target @com_google_absl//absl/base:spinlock_wait) /usr/bin/clang-11 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 53 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_google_absl/absl/base/internal/spinlock_wait.cc:22:
In file included from external/com_google_absl/absl/base/internal/spinlock_wait.h:24:
In file included from external/com_google_absl/absl/base/internal/scheduling_mode.h:21:
In file included from external/com_google_absl/absl/base/config.h:86:
external/com_google_absl/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."
#error "C++ versions less than C++14 are not supported."
 ^
1 error generated.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.913s, Critical Path: 0.46s
INFO: 82 processes: 64 internal, 18 linux-sandbox.
FAILED: Build did NOT complete successfully

These are the steps I could figure out from the envoy build documentation and I am stuck at this error. Any help would be much appreciated.

Also, let me know if any other information from my setup is needed to understand this issue.

**Comment by nikita96** [comment]
Added a couple of build flags to envoy build command to resolve the above mentioned error.

Command used :
`bazel build -c opt envoy --cxxopt=-std=c++17 --host_cxxopt=-std=c++17`

Now facing a different error : 
INFO: Analyzed target //:envoy (1 packages loaded, 4215 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/14f0c640799f93c0c82a089b9eaec88b/external/com_github_google_tcmalloc/tcmalloc/internal/BUILD:544:11: Compiling tcmalloc/internal/percpu.cc failed: (Exit 1): clang-11 failed: error executing command (from target @com_github_google_tcmalloc//tcmalloc/internal:percpu) /usr/bin/clang-11 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 34 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_github_google_tcmalloc/tcmalloc/internal/percpu.cc:57:5: error: variable does not have a constant initializer
    __rseq_abi = {
    ^            ~
external/com_github_google_tcmalloc/tcmalloc/internal/percpu.cc:56:1: note: required by 'require_constant_initialization' attribute here
ABSL_CONST_INIT thread_local ABSL_ATTRIBUTE_WEAK volatile kernel_rseq
^~~~~~~~~~~~~~~
external/com_google_absl/absl/base/attributes.h:714:27: note: expanded from macro 'ABSL_CONST_INIT'
#define ABSL_CONST_INIT [[clang::require_constant_initialization]]
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/nbenvoy/source/exe/BUILD:24:16 Linking source/exe/envoy-static failed: (Exit 1): clang-11 failed: error executing command (from target @com_github_google_tcmalloc//tcmalloc/internal:percpu) /usr/bin/clang-11 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 34 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 245.221s, Critical Path: 35.57s
INFO: 1407 processes: 483 internal, 924 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by phlax** [comment]
this might help https://github.com/envoyproxy/envoy/issues/26965

**Comment by nikita96** [comment]
Hi @phlax,
I am constantly facing below error now. Any suggestions on it's resolution?

ERROR: /root/.cache/bazel/_bazel_root/14f0c640799f93c0c82a089b9eaec88b/external/com_googlesource_googleurl/url/BUILD:12:11: Compiling url/url_idna_icu.cc failed: (Exit 1): clang-15 failed: error executing command (from target @com_googlesource_googleurl//url:url) /usr/bin/clang-15 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_googlesource_googleurl/url/url_idna_icu.cc:14:10: fatal error: 'unicode/uidna.h' file not found
#include <unicode/uidna.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/nbenvoy/source/exe/BUILD:24:16 Linking source/exe/envoy-static failed: (Exit 1): clang-15 failed: error executing command (from target @com_googlesource_googleurl//url:url) /usr/bin/clang-15 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 32.319s, Critical Path: 11.06s
INFO: 93 processes: 31 internal, 62 linux-sandbox.
FAILED: Build did NOT complete successfully

Do I need to install ICU manually?

**Comment by phlax** [comment]
can i ask why its not possible to just use the build container and follow the documented way

is there a need to use redhat specifically?

**Comment by nikita96** [comment]
The product which consumes envoy has support only for redhat. Hence we need to build it on rhel.

**Comment by nikita96** [comment]
I am now able to build envoy v1.26.2 successfully. 
I picked below directory and files from envoy github(tag v1.26.2), replaced in my source code tar and then built it.
```
.bazelci/
.bazelignore
.bazelrc
.bazelversion
```

Apparently, there is a code difference in all these files present in v1.26.2 source code tar and github repository with tag v1.26.2. Not sure if this was intentional.
For example, .bazelversion file in v1.26.2 source code tar contains 5.1.1 whereas .bazelversion file in github repository with tag v1.26.2 contains 6.1.0.
After pulling in the right bazel configurations, build was successful.

**Comment by phlax** [comment]
Apparently, there is a code difference in all these files present in v1.26.2 source code tar and github repository with tag v1.26.2.

this is not correct

```console
$ wget -q -O - https://github.com/envoyproxy/envoy/archive/refs/tags/v1.26.2.tar.gz | tar zxfO - envoy-1.26.2/.bazelversion
6.1.0
```

either way - if you have resolved your issue, can we close this ticket ?

**Comment by phlax** [comment]
> The product which consumes envoy has support only for redhat. Hence we need to build it on rhel.

flagging that you _dont_ need to build on the same OS as the target - the only thing that does need to be compatible is the glibc version

**Comment by nikita96** [comment]
Yes, we can close the issue
