### ISSUE TITLE
Server process end lifecycle and object lifetime management

### ISSUE THREAD

**Issue by mrice32** [envoyproxy/envoy#2802]
*Description*: We've run into a few situations internally where we would like to be able to create objects that will be destroyed at server shutdown or simply be notified of server shutdown.  It's been difficult to do this in the context of a statically registered factories because the statically registered component is never destructed or notified of shutdown, and the elements it produces generally share their lifetime with the config that they are associated with rather than the process itself.  Our use cases revolve around the graceful shutdown of shared, long-lived clients that dispatch RPCs asynchronously.  I think this is a broad problem that may motivate an Envoy-wide solution rather than something that we put together in a proprietary context.  If there is an existing solution to this problem in Envoy, feel free to chime in.

cc @htuch @mattklein123 @jmarantz @rohitbhoj

**Comment by mattklein123** [comment]
@mrice32 this SGTM. I think there are a few options here:
1) Build shutdown notification into the singleton manager, which is already built into the server.
2) Allow shutdown registration on the server instance generically. Basically, have some type of `ShutdownNotifierCallback` and allow this to be registered on the server.

**Comment by jmarantz** [comment]
Also I wonder if we can/should distinguish server lifetime from process lifetime vs listener lifetime.

And in the context of unit tests, would we consider server lifetime to actually be the life of the test method?

**Comment by htuch** [comment]
We also want to do a graceful GOAWAY by doing a clean gRPC stream/client shutdown for xDS when we start server drain. So, whatever we build in this space should do that. I think option (2) in @mattklein123 would support this, in particular if we get callbacks at start of drain.

**Comment by mattklein123** [comment]
This is related also to https://github.com/envoyproxy/envoy/issues/2795

**Comment by mrice32** [comment]
Are there any objections with going with option 2 in the interest of flexibility?

**Comment by mattklein123** [comment]
@mrice32, no, I would do option 2. I think it will eventually allow us to register for different types of events as has already been mentioned (drain start, drain finish, etc.).

**Comment by jmarantz** [comment]
This sounds great.

I'm thinking also about how this all works in the context of unit tests, where I expect servers to be brought up & down multiple times in a single process.  Should these callbacks be re-established in each test?  And if that's going to happen should they be cleaned up between each test?

Assuming the singleton manager @mattklein123 is https://github.com/envoyproxy/envoy/blob/master/source/common/singleton/manager_impl.h I think the one issue is the lifetime of the singleton manager itself.  There's some support in there for doing test-related factory replacement (https://github.com/envoyproxy/envoy/blob/c481a8cd64ce81300dabd4aefd7851eb2b9fb5b9/include/envoy/registry/registry.h#L61) but it seems complicated.  It'd be nice to have a total fresh start at the beginning of each test method.

**Comment by mattklein123** [comment]
My assumption is that anything we do here is not using statics, since it will be registered explicitly with the server. So I think we should be fine between tests since we have a fresh server in each one?

**Comment by htuch** [comment]
We'd still like to see something like this for Google use cases, CC @eziskind.

**Comment by eziskind** [comment]
Here is a proposed API for [option 2](https://github.com/envoyproxy/envoy/issues/2802#issuecomment-372895692) mentioned above:

```
typedef std::function<void()> ShutdownNotifierCallback;

class ShutdownNotifier {
public:
  // Register a callback function that will be invoked just before the server
  // instance is shutdown. Specifically it will be invoked on the main thread
  // just before calling exit on the main thread dispatcher.
  void registerCallback(ShutdownNotifierCallback cb);
}
```

Does this sound reasonable?

**Comment by jmarantz** [comment]
nit: prefer 'using' to typedef.

What is the new class for? Can we just have registerShutdownCallback() on Server?

**Comment by eziskind** [comment]
> What is the new class for? Can we just have registerShutdownCallback() on Server?

I meant this to be an abstract class (updated the code snippet to make the method a pure virtual one) so it'll be easier to expose via the [filter factory context](https://github.com/envoyproxy/envoy/blob/df3d47f478c29188d22b517d1a0d05793dfe2c62/include/envoy/server/filter_config.h#L36) to allow extensions to register for these callbacks. For the implementation we could make the InstanceImpl class implement this interface.

**Comment by htuch** [comment]
@eziskind it would be good to be able to get callbacks attesting to the full server shutdown cycle, including when we start draining, when done draining, heading out the door, etc. Maybe the CB should have some state enum as a parameter?

I'm not sure what the existing `DrainManager` provides here, but my ultimate test of design is "could we handle https://github.com/envoyproxy/envoy/issues/2802#issuecomment-373114407"?

**Comment by jmarantz** [comment]
I like @htuch's suggestion: can we extend it to also include startup phases, e.g. when we start running the main dispatcher loop?

**Comment by eziskind** [comment]
Ok, how about this more general API:

```
class ServerLifecycleNotifier {
public:
  enum class Stage {
    // The server instance main dispatcher loop has started
    Startup,

    // The server instance is being shutdown and the main thread dispatcher is about to
    // exit.
    Shutdown
  };

  // Callback invoked when a the server reaches a certain lifecycle stage.
  using StageCallback = std::function<void()>;

  // Register a callback function that will be invoked on the main dispatcher thread when
  // the specified stage is reached.
  virtual void registerCallback(Stage stage, StageCallback cb) = 0;
}
```

**Comment by htuch** [comment]
@eziskind or just have a single lifecycle callback that take stage as an arg, either way works.

I'd like a TODO at least to add some early shutdown intercept state, so maybe rename `Shutdown` to `ShutdownExit` or something.
