### ISSUE TITLE
Wrong TLS version is coming in client Hello

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#28026]
We are using latest stable envoy 1.26.1
We are taking envoy config dump and TLS version is coming as TLSv1_2 but in client hello it is coming as TLS1.0
 "tls_params": {
             "tls_minimum_protocol_version": "TLSv1_2",
             "cipher_suites": [
              "ECDHE-ECDSA-AES128-GCM-SHA256",

So if we have configured TLSv1_2 so why it is coming as TLS1.0 in wireshark logs?

![image](https://github.com/envoyproxy/envoy/assets/113907674/f584545c-a15a-4a70-a82a-5078875dbee1)

In Record Layer TLS 1.0 version is coming that is wrong version

**Comment by zuercher** [comment]
I think this article addresses what you're seeing: https://www.analysisman.com/2021/06/wireshark-tls1.2.html

**Comment by Gaurav0411GitHub** [comment]
Thanks
