### ISSUE TITLE
Build with bazel.release.server_only error with latest code

### ISSUE THREAD

**Issue by candleflame** [envoyproxy/envoy#28037]
When I local build envoy docker by following this [doc](https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build)

I try to build with `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'` this command, and run `docker build -f ci/Dockerfile-envoy -t envoy .` to build docker.  I got this error message

```
Sending build context to Docker daemon  502.3kB
Step 1/50 : ARG BUILD_OS=ubuntu
Step 2/50 : ARG BUILD_TAG=20.04
Step 3/50 : ARG ENVOY_VRP_BASE_IMAGE=envoy-base
Step 4/50 : FROM scratch AS binary
 --->
Step 5/50 : COPY ci/docker-entrypoint.sh /
 ---> 876a80516633
Step 6/50 : ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml
 ---> 8f752ec4e3a5
Step 7/50 : ARG TARGETPLATFORM
 ---> Running in cb098afd2bd5
Removing intermediate container cb098afd2bd5
 ---> f1613288215f
Step 8/50 : ENV TARGETPLATFORM="${TARGETPLATFORM:-linux/amd64}"
 ---> Running in 9b76957a5e16
Removing intermediate container 9b76957a5e16
 ---> 647d7cb7bb62
Step 9/50 : ADD "${TARGETPLATFORM}/release.tar.zst" /usr/local/bin/
ADD failed: file not found in build context or excluded by .dockerignore: stat linux/amd64/release.tar.zst: file does not exist
```

The build target is
```
linux/
└── amd64
    ├── build_envoy_release
    │   ├── envoy
    │   ├── envoy.dwp
    │   ├── schema_validator_tool
    │   └── su-exec
    └── build_envoy_release_stripped
        └── envoy
```

But from the [docker file](https://github.com/envoyproxy/envoy/blob/main/ci/Dockerfile-envoy), the output of building should be
```
linux/
└── amd64
    ├── release.tar.zst
    └── schema_validator_tool
```

Is there anything wrong with the build step or the docker file?

**Comment by candleflame** [comment]
From this [commit](https://github.com/envoyproxy/envoy/commit/d4f3bf2f02d97b4a9ab6dd1fee2652bb8e7f9137), looks `bazel.release` will have the `release.tar.zst` file. how about the `bazel.release.server_only` command?

**Comment by phlax** [comment]
@candleflame these two targets are now not consistent with each other

i raised a PR (#27573) but that kinda stalled as i wasnt clear if/how the `server_only` target was currently used or the impact of changing it

using the `ci/do_ci.sh release` target should work, with a couple of cavets

you will need to put the artefacts in the correct place before building Docker (see https://github.com/envoyproxy/envoy/blob/37f764e056505632ae12a22d215fa46305be4053/.azure-pipelines/stage/publish.yml#L138-L151for how this is done in CI)

its slower as it runs tests first - you could potentially comment out the tests

**Comment by phlax** [comment]
> Will it work if I copy these files to make them together to 

probably, yes, as long as the artefacts are in the correct places - the tarball needs to be in the correct place and structured correctly also

here is an example of what CI produces (probs requires azp login) https://dev.azure.com/cncf/_apis/resources/Containers/20234667/bazel.release?itemPath=bazel.release%2Fx64%2Fbin%2Frelease.tar.zst
