### ISSUE TITLE
How to develop a custom http filter

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#28033]
I'm trying to develop a custom http filter from zero.

So first I think I need to create a new proto file and put it in `api/envoy/extensions/filters/http/my_filter/v3/config.proto`. But then I don't know what to do for the next step.

It seems that each proto file has its own `BUILD` file, in which noted `# DO NOT EDIT. This file is generated by tools/proto_format/proto_sync.py.`. So I tried to execute the command `./tools/proto_format/proto_sync.py api/envoy/extensions/filters/http/my_filter/v3/`, but I got an error: `ModuleNotFoundError: No module named 'api_proto_plugin'`.

Can someone guide me how to develop a custom http filter from zero?

**Comment by j2gg0s** [comment]
A real world example: https://github.com/istio/proxy/blob/master/BUILD

**Comment by YvesZHI** [comment]
@ohadvano   Well, I followed the `README.md` so I executed the commands as below:
```
git submodule update --init
bazel build //http-filter-example:envoy
```

But I got an error: 
```
Starting local Bazel server and connecting to it...
ERROR: /home/envoy/workspace/envoy-filter-example/WORKSPACE:3:17: fetching local_repository rule //external:envoy: java.io.IOException: The repository's path is "{ENVOY_SRCDIR}" (absolute: "/home/envoy/workspace/envoy-filter-example/{ENVOY_SRCDIR}") but it does not exist or is not a directory.
ERROR: Error computing the main repository mapping: no such package '@envoy//bazel': The repository's path is "{ENVOY_SRCDIR}" (absolute: "/home/envoy/workspace/envoy-filter-example/{ENVOY_SRCDIR}") but it does not exist or is not a directory.
```

It seems that `path: {ENVOY_SRCDIR}` in the file `WORKSPACE` is incorrect...
