### ISSUE TITLE
FilterChainMatch criteria 

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#28039]
application_protocols matching criteria is an array. Is it true if all elements are matched, or is it true if one of them is matched?

**Comment by j2gg0s** [comment]
I think it's `OR`, see [findFilterChainForApplicationProtocols](https://github.com/envoyproxy/envoy/blob/main/source/extensions/listener_managers/listener_manager/filter_chain_manager_impl.cc#L668)

Example for http1.1 or h2c:
cat l.json| jq '.[].filterChains[].filterChainMatch' | pbcopy
```json
{
  "transportProtocol": "raw_buffer",
  "applicationProtocols": [
    "http/1.1",
    "h2c"
  ]
}
```

**Comment by liuqi-sun** [comment]
> 

Thank you

**Comment by liuqi-sun** [comment]
> I think it's `OR`, see [findFilterChainForApplicationProtocols](https://github.com/envoyproxy/envoy/blob/main/source/extensions/listener_managers/listener_manager/filter_chain_manager_impl.cc#L668)
> 
> Example for http1.1 or h2c: cat l.json| jq '.[].filterChains[].filterChainMatch' | pbcopy
> 
> ```json
> {
>   "transportProtocol": "raw_buffer",
>   "applicationProtocols": [
>     "http/1.1",
>     "h2c"
>   ]
> }
> ```

Thank you
