### ISSUE TITLE
which tag to refer in blackduck check vulnerabilities 

### ISSUE THREAD

**Issue by ssm6498** [envoyproxy/envoy#28049]
In BlackDuck where we can check vulnerabilities. Will it be okay to refer "lyft/envoy "

*Description*:
n BlackDuck where we can check vulnerabilities. Will it be okay to refer "lyft/envoy "

**Comment by phlax** [comment]
@ssm6498 im afraid im not familiar with blackduck, although i know that some users are tracking envoy with it

i think probably you would be better asking for support from blackduck

**Comment by ssm6498** [comment]
Thanks for the response.

**Comment by ssm6498** [comment]
thanks
