### ISSUE TITLE
What is the End of Life of patch release 1.23.10?

### ISSUE THREAD

**Issue by nikita96** [envoyproxy/envoy#28048]
I have recently upgraded envoy from v1.23.0 to v1.23.10. This [document](https://github.com/envoyproxy/envoy/blob/main/RELEASES.md) mentions the EOL of base versions of envoy. Where can I find the EOL dates for patch releases?

**Comment by phlax** [comment]
Perhaps we should clarify this, but the EOL for the v1.23.x series is the EOL date set for 1.23.0

**Comment by nikita96** [comment]
Alright. Thanks for the quick help!

**Comment by phlax** [comment]
closing this out as there is not anything immediately actionable
