### ISSUE TITLE
Can I deploy envoyproxy to a production server use docker images

### ISSUE THREAD

**Issue by cl51287** [envoyproxy/envoy#2804]
I find the docs say "The Envoy build system uses Bazel. In order to ease initial building and for a quick start, we provide an Ubuntu 16 based docker container that has everything needed inside of it to build and statically link envoy, see ci/README.md.", can I deploy envoyproxy to a production server use docker images?

**Comment by taion809** [comment]
Yes, the container that is shipped to hub.docker.com/envoyproxy/envoy contains a production ready build of envoy.

The container itself is very minimal (I don't mean size) so you need to decide if thats how you want to deploy envoy-with-docker, alternatively you can pull the envoy binary from the docker image and build your own container.

**Comment by cl51287** [comment]
I found there are no versions in hub.docker.com/envoyproxy/envoy, is that latest version a release version(v1.5.0)?

**Comment by cl51287** [comment]
I get a version `d00361232086d0044e5ce93968f4b4657fa22be5/1.6.0-dev/Clean/RELEASE` from https://hub.docker.com/r/envoyproxy/envoy latest version, I found ,it is a dev version, not a release version, which version shoud i pull?

**Comment by taion809** [comment]
You can pull the latest tagged image and be fine, the master branch is supposed to be production ready.  At the time of this comment the latest version is `9d4ca6dbc8808daf8dc4d8fdf52094191444af98`

```
docker pull envoyproxy/envoy:9d4ca6dbc8808daf8dc4d8fdf52094191444af98
```

**Comment by cl51287** [comment]
Helped a lot, thanks

**Comment by mattklein123** [comment]
Cool, closing as answered.
