### ISSUE TITLE
Docker: improve docker experience for first time users

### ISSUE THREAD

**Issue by taion809** [envoyproxy/envoy#2805]
*Title*: Docker: improve docker experience for first time users

*Description*:
The current docker image, while functional, is not as simple of a first-time user experience compared to other products.

For example, if you compare other projects on hub.docker.com you'll see that the docker image for envoy lacks readme details and modification points from the container itself (meaning you need to rebuild the container or create a new container entirely to customize anything).

My proposal is to spend some time fleshing out the provided docker container and provide the following:
  - Update the hub.docker.com/envoyproxy/envoy descriptions with usage instructions
  - Default templated XDS-enabled configuration file (or a hello-world config file)
  - use dockerize  (or some alternative) to pull in environment variables as template variables for a configuration file
  - Add opinionated `CMD` and `ENTRYPOINT` directives.

*Relevant Links*:
  - https://hub.docker.com/_/consul/
  - https://hub.docker.com/_/redis/
  - https://hub.docker.com/_/nginx/

[Edit]: This is something I can take on if no one else has bandwidth.

**Comment by mattklein123** [comment]
@taion809 sounds awesome! Rock on!

**Comment by bndw** [comment]
@taion809 Happy to divide and conquer on this one and thanks for bringing it up!

**Comment by taion809** [comment]
@bndw SGTM.

I'm a bit busy this week so I'm not sure I can be helpful until the weekend/next week.  My first pass intention was to update the release scripts to pull in the `config/google_com_proxy.v2.yaml` configuration for the "hello world" version.

Example:
```Docker
FROM ubuntu:16.04
LABEL MAINTAINER="Envoy Maintainers <someemail@github.com>"

ENV diversion=1.2.1
ENV loglevel=info

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y wget ca-certificates \
    && apt-get autoremove

RUN wget https://github.com/Yelp/dumb-init/releases/download/v${diversion}/dumb-init_${diversion}_amd64.deb \
    && dpkg -i dumb-init_${diversion}_amd64.deb

RUN mkdir -p /etc/envoy

COPY /tmp/envoy.bin /usr/local/bin/envoy
COPY config/google_com_proxy.v2.yaml /etc/envoy/envoy.yaml

EXPOSE 80
EXPOSE 9901

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD [ "/usr/local/bin/envoy", "--v2-config-only", "-l", "${loglevel}", "-c", "/etc/envoy/envoy.yaml" ]
```

**Comment by shuoli84** [comment]
Also please add release tags. Now all images with hash tag, it is not clear which is 1.6.0 stable release.

**Comment by taion809** [comment]
@llitfkitfk 
try `docker pull envoyproxy/envoy:v1.6.0`

The dockerhub listing has a limited number of tags its able to show.

**Comment by taion809** [comment]
Going to close this issue, I think we've made good on a better docker image with perhaps some more work to be done but those should be specifically identified in another issue :)
