### ISSUE TITLE
envoy ignores "Keep-Alive: timeout=X" from upstream's response

### ISSUE THREAD

**Issue by fxposter** [envoyproxy/envoy#28105]
*Title*: envoy ignores "Keep-Alive: timeout=X" from upstream's response

*Description*:
When envoy proxies an http1 request to some upstream and that upstream sends response with `Connection: keep-alive` and `Keep-Alive: timeout=SECONDS` - it [means](https://http.dev/keep-alive) that the upstream will most likely close the connection after the specified amount of seconds.
Envoy on the other hand thinks that the connection is valid and it can use it until idle_timeout is reached. When this happens - usually envoy sends the new request to this connection, gets remote reset and reports 503 to the client (unless retries are configured for resets).
I didn't find any code that is related to handling keep-alive in envoy source, so I wonder whether this was/is an intentional decision to not support this functionality?

**Comment by zuercher** [comment]
`Keep-Alive` with parameters was removed from http/1.1 (see https://www.rfc-editor.org/rfc/rfc2068.html#section-19.7.1.1), and the header doesn't seem to be discussed much in the subsequent superseding RFCs.

In general, I think any time an upstream server closes an HTTP connection you run the risk of the upstream reset error unless the close happens after a response containing `connection: close`. Even if Envoy attempted to honor a `keep-alive: timeout=30` header, it's would be very difficult to get Envoy and the upstream to agree on when the 30s had elapsed. Any request sent close to the boundary might end up arriving at the upstream just after it issues its RST, leading to the error.

In practice, I think it's best to set idle timeouts on the Envoy side and have the upstream use the default (persistent) connection behavior for http/1.1. If that's not possible for some reason, then I'd set Envoy idle timeouts shorter than the server's desired keep-alive time, such that Envoy always closes the connection before the upstream server.

**Comment by fxposter** [comment]
I do agree that from the load balancer perspective such timeout in response header is not a predictable thing, but the problem is that `keep-alive: timeout=5` is the default behaviour in node.js :(
