### ISSUE TITLE
Golang filters defined in listeners configured from xDS

### ISSUE THREAD

**Issue by maguro** [envoyproxy/envoy#28129]
I have a golang filter defined in a listener configured from xDS. I'm getting the following error when the plug-in is loaded; the proxy restarts.

    ==1==ERROR: ThreadSanitizer failed to allocate 0x2050000 (33882112) bytes at address 11e3de49c0000 (errno: 12)

I'm not sure if this use case is supported.  If so, I'll submit a self contained example.  mtia!

V1.26.2

**Comment by doujiang24** [comment]
Yep, that's supported. please upload a reproducible example, Thanks!

**Comment by maguro** [comment]
Ooof, I built the filter with `-trace`.   

https://github.com/cilium/cilium/issues/6566
