### ISSUE TITLE
Dynamically select upstream cluster in TCP Proxy network filter based on Proxy Protocol TLV headers

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/envoy#28128]
I'm trying to explore how I can use a TLV Header value from Proxy Protocol to select upstream cluster in TCP Proxy. So far I haven't found any documentation or code doing something similar. Is this currently supported? Is writing a custom Wasm network filter the way to go? Looks like if I can set `envoy.tcp_proxy.cluster` from my custom filter it will work.

Background:
I'm using Envoy (using Istio Ingress Gateway) as a reverse proxy and I want to automatically route connections coming through AWS Private Link. We can extract VPC Endpoint ID from Proxy Protocol TLV Headers and I want to use that to route to an upstream cluster (which is a local kubernetes Service). For public connections I'm using SNI based routing however for Private Links I want to route based on VPC Endpoint ID (to avoid creating a private DNS record).

**Comment by gitanuj** [comment]
I tried using Unified Matching API but looks like `envoy.extensions.matching.common_inputs.network.v3.FilterStateInput` just returns the underlying state's `serializeAsString` representation which for proxy protocol listener filter doesn't include TLV headers. 

I'm now trying to see if I can somehow use Unified Matching on dynamic metadata (since proxy protocol filter can emit TLV header value as dynamic metadata).

**Comment by soulxu** [comment]
The Cluster's endpoint can be selected by the metadata https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-lbendpoint, is that help for your case if you only use one cluster but with multiple endpoints, and choice the endpoint based on the metadata?

**Comment by gitanuj** [comment]
I'm using Istio Ingress Gateway to route to local kubernetes services based on a PPv2 TLV Header. As I understand Istio uses VirtualService to add a Kubernetes Service as an upstream cluster to Envoy and it doesn't define any endpoints in this case (may be because these are kubernetes services so routing is handled by kube-proxy). So I can't rely on metadata match for endpoints.

**Comment by kyessenov** [comment]
Unified matching cannot set a dynamic metadata or a filter state to control tcp_proxy. What it can do is to select a tcp_proxy filter chain from a list given a metadata for TLV. If you want the former, you'd need a custom filter (or a Wasm/lua/golang script modulo the limitations of the runtimes).

**Comment by gitanuj** [comment]
@kyessenov Currently proxy_protocol filter allows emitting TLVs as dynamic metadata. Would it make sense if proxy_protocol filter could set filter state using a custom key? Tcp_proxy filter only relies on filter state `envoy.tcp_proxy.cluster` to route to upstream cluster. This way proxy_protocol filter can influence upstream cluster.

Otherwise the only other solution without having to recompile Envoy currently is writing a custom WASM filter (Lua isn't supported at L4 and [Golang L4 filter doesn't support continueReading() to chain other filters yet](https://github.com/envoyproxy/envoy/issues/25906#issuecomment-1619364129)).

**Comment by gitanuj** [comment]
Looks like this is currently not possible with all the extension mechanisms

1. Wasm doesn't support setting filter state (created issue [here](https://github.com/envoyproxy/envoy/issues/28673))
2. Golang network filter doesn't work as a non terminal filter. Also it is a WIP and doesn't even compile without directly referencing the code. (cc @antJack)
3. Lua doesn't support L4

Is there any other way I could intercept `onNewConnection` before tcp_proxy filter and set `envoy.tcp_proxy.cluster` filter state? One option is to do what `sni_cluster` filter is doing by adding a native filter and recompiling the proxy. However I'm trying to see if it is possible to achieve this without recompiling envoy.

**Comment by guybrushthre** [comment]
Have you ever figured this out?

**Comment by dzacball** [comment]
@guybrushthre I followed @gitanuj's tracks and was able to make this work using the wasm foreign function he created in his [PR](https://github.com/envoyproxy/envoy/pull/29320). So now, after you have used  the proxyprotocol listener filter
```
        {
         "name": "envoy.filters.listener.proxy_protocol",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol",
          "rules": [
           {
            "tlv_type": 32,
            "on_tlv_present": {
             "metadata_namespace": "envoy.lb",
             "key": "proxyproto_tlv_0x20"
            }
           }
          ],
          "allow_requests_without_proxy_protocol": true
         }
        },
```
that adds any TLVs specified to the flow as metadata, you can write a wasm plugin that decides (based on the metadata) what the target cluster should be, and then using the foreign function, you can actually set `envoy.tcp_proxy.cluster`, and have the tcp proxy send the traffic to whatever destination you set up in the wasm plugin.

**Comment by dzacball** [comment]
but lol, I just realised I could have simply used https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/set_filter_state. 
```
on_new_connection:
- format_string:
    text_format_source:
      inline_string: outbound|2040||some-target-cluster-based-on-%DYNAMIC_METADATA(envoy.lb:proxyproto_tlv_0x20)%.svc.cluster.local
  object_key: envoy.tcp_proxy.cluster
```

**Comment by SiiiTschiii** [comment]
An example with proxy-wams using `set_envoy_filter_state` to select an upstream proxy: https://github.com/SiiiTschiii/wasmerang

This thread helped me a lot! Thank you

**Comment by luistilingue** [comment]
@dzacball do I need to only use the `set_filter_state` or do I need to do what you said [here](https://github.com/envoyproxy/envoy/issues/28128#issuecomment-2661033225) and then apply the `set_filter_state` ?

My scenario is the following:

Legacy clients (TCP only) connect to CloudFlare -> AKS (envoy/istio) -> services (upstream) in k8s.

So, I need to make routing decision based on PP2_TYPE_AUTHORITY (0x02) TLV sent from CF to Envoy properly route to a backends clusters.

**Comment by dzacball** [comment]
@luistilingue you need to use the proxyprotocol listener filter as described in https://github.com/envoyproxy/envoy/issues/28128#issuecomment-2661033225, and then use `set_filter_state`. After that, you can use tcp [proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter) to route the traffic to the destination you specified using `set_filter_state`.
