### ISSUE TITLE
1.26.2 assets are not named in accordance to previous releases.

### ISSUE THREAD

**Issue by ednxzu** [envoyproxy/envoy#28146]
*Title*: *latest release assets are not named in accordance to previous releases*

*Description*:
1.26.2 assets aren't named the same as all the previous releases, which complicates the automation of installation and deployment (ansible roles in our case) . It'd be nice to have a homogeneous naming to simplify automation.

Sorry if this shouldn't have been an issue, I wasn't sure where else to put it.

**Comment by phlax** [comment]
> 1.26.2 assets aren't named the same as all the previous releases

yeah this was a mistake

thanks for opening this ticket - it was on my todo list to resolve

**Comment by phlax** [comment]
this should be resolved from 1.26.3 - aplogies for any inconvenice we are working hard to stabilize the release process/es

https://github.com/envoyproxy/envoy/releases/tag/v1.26.3
