### ISSUE TITLE
Intermittent High latency from envoy to Redis clusters 

### ISSUE THREAD

**Issue by LeonGao91** [envoyproxy/envoy#28150]
*Title*: *Intermittent High latency from envoy to Redis clusters *

*Description*:
Hi Folks! I want to share an issue we encountered and see if someone has any ideas on it..

We use Envoy as a proxy for Redis clusters. From time to time, we observe latency spikes drastically such as below, and active requests are piling up at the same time.

![Screen Shot 2023-06-26 at 10 49 28 PM](https://github.com/envoyproxy/envoy/assets/5714374/3b278a62-3fa3-4568-a44d-40fe98bfd772)

![Screen Shot 2023-06-26 at 10 55 28 PM](https://github.com/envoyproxy/envoy/assets/5714374/191c13d3-4641-4701-81d9-0517780b167b)

However, during the incident, the redis cluster and envoy proxies are not busy (around 30%~40% CPU usage, and the network is lightly used)
Also, the latency **sharply** dropped to the stable state when we **refresh the client connections**. It seems that it has something to do with the client connections and pending requests.

Any thoughts are welcomed!

**Comment by kyessenov** [comment]
CC @weisisea

**Comment by LeonGao91** [comment]
In case anyone is interested, it is due to the imbalanced connections to the envoy workers. We have deployed https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#config-listener-v3-listener-connectionbalanceconfig this setting and no longer see tail latencies.
