### ISSUE TITLE
OAuth2 backchannel renewal

### ISSUE THREAD

**Issue by bigglesandginger** [envoyproxy/envoy#28162]
*OAuth2 backchannel renewal*: *Renew authentication token via backchannel*

*Description*:
>When an authentication token has expired and the user makes a request, the OAuth layer makes a renewal request via the Identity Provider's (IdP) backchannel.  Reason being that AJAX requests cannot deal with a redirect to login with the IdP.

**Comment by kyessenov** [comment]
I'm not sure I understand the feature request. Are you proposing a new functionality in oauth2 filter?

**Comment by bigglesandginger** [comment]
When I use Apache HTTPd with mod_oauth2, the proxy layer seems to manage renewing the access token (the client does need to poke the proxy layer with a timely message, paying attention to the expiry time), the renewal seems to happen between the proxy layer and the IdP.  When I switched to trying out Envoy (due to the annoyance of having to compile httpd with mod_oauth for ARM takes a long time), it seems to want to totally manage the access token thus alleviating the need to pass a Bearer Token for the client, etc, however, the AJAX calls I am making from our client layer to the api layer through the envoy proxy layer will fail once the token expires, as Envoy seem to require the AJAX layer to log into the IdP again.  Thus I imagine it is not using whatever information is in the token to allow renewal on the backchannel.

I do not know OAuth2 protocols, so if I am misusing terms that is because I simply want to use OAuth not write OAuth, if that makes sense.

As I "understand", it seems that the envoy oauth2 feature is missing the renewal capability, or I am missing how to use this feature?

**Comment by kyessenov** [comment]
CC @mattklein123 @derekargueta who probably know more about oauth2 than me.

**Comment by kanurag94** [comment]
AFAIK, the oauth2 filter doesn't refresh the id token using the refresh token. It just sets the cookie expired date and use the standard user auth code flow to get the tokens again when it's expired.
