### ISSUE TITLE
automate coverity scan uploads

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2817]
It looks like coverity scan might be gone. We will need to replace it with some other static analysis tool. Need to investigate which one.

**Comment by PiotrSikora** [comment]
[Clang Static Analyzer](https://clang-analyzer.llvm.org/) was pretty decent when I was using it years ago.

**Comment by caniszczyk** [comment]
sigh, I'll see if I can find something else, codeclimate is beautiful but doesn't support C/C++

**Comment by mattklein123** [comment]
Another one I found on Twitter: http://fbinfer.com/

Not sure how easy any of these will be to integrate with Bazel.

**Comment by PiotrSikora** [comment]
Looks that Coverity Scan is back.

**Comment by mattklein123** [comment]
@PiotrSikora yeah I saw. I'm going to change this title to track automating coverit uploads. We need to figure out how to do that. Potentially we can have a CI job that just runs on master commit.

**Comment by caniszczyk** [comment]
LGTM reached out and apparently supports C/C++ in beta and willing to help out: https://lgtm.com/

I may play with it over the next week or so to see how it works, however, all these tools aren't perfect by any means.

**Comment by sjvs** [comment]
Hi guys. I tried adding Envoy to our C/C++ beta, but it's not entirely clear what the best way to build your code is. It'd be great if you could give me some pointers — happy to help! Here's an example on how we set up rsyslog for lgtm analysis: https://github.com/rsyslog/rsyslog/pull/2548.

**Comment by mattklein123** [comment]
I think we can just do https://github.com/envoyproxy/envoy/tree/master/ci#coverity-scan-build-flow on master commits. Will move this into 1.7.0 milestone. If anyone in the community wants to help with this, that would be great.

**Comment by mattklein123** [comment]
I'm going to close this as I think we are going to invest in LGTM/semmle.
