### ISSUE TITLE
is It OK to add more data(fg, caught time, src ip, port, dst ip, port) in Tap Trace?

### ISSUE THREAD

**Issue by coolg92003** [envoyproxy/envoy#28183]
*Title*: *is It OK to add more data(fg, catched time, src ip, port, dst ip, port) in Tap Trace?*

*Description*:
Hi Expert,
Recently, I try http filter "type.googleapis.com/envoy.extensions.filters.http.tap.v3.Tap", and got below two issues:
1) I can't get the source ip, port, and dest ip port, and caught time(request/response)
2) Can't specify the the user specified export ip and port, like Trace, such as zipkin,9441

Therefore, I expect:
1) per trace_id(fg, "trace_id": "2062011462271729763"), add (src ip, port, dst ip and port)
{
 "http_streamed_trace_segment": {
  "trace_id": "2062011462271729763", 
**--new start
  srcip: 10.10.10.99
  srcport: 4567
  dstip:10.10.11.99
  dstport:8080
  request caught time:1233333
--new end**
  "request_headers": {
   "headers": [
    {
     "key": ":authority",
     "value": "127.0.0.1:8022"
    },

  "trace_id": "2062011462271729763",
**--new start
    response caught time:1233333
--new end**
  "response_headers": {
2) sinks target
http_filters:
          - name: envoy.filters.http.tap.cfx
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.tap.v3.Tap
              common_config:
                static_config:
                  match_config:
                    http_request_headers_match:
                      headers:
                      - name: x-call-trace-id
                        present_match: true
                  output_config:
                    streaming: true
                    sinks:
                    - format: JSON_BODY_AS_STRING
 --new start
add the similar from below:
                      file_per_tap:
                        path_prefix: /etc/envoy/
to
                      dst_cluster:
                        cluster_name: trace_tap_cluster
 --new stop
                    max_buffered_rx_bytes: 1000000
                    max_buffered_tx_bytes: 1000000

[optional *Relevant Links*:]
See attachment for my envoy configuration and current tap output
1) Envoy yaml:
cat ftapenvoy.yaml
node:
  id: front-envoy
  cluster: front-proxy

admin:
  profile_path: /etc/envoy/zipkin/envoy.prof
  access_log_path: /etc/envoy/envoy_admin_access.log
  address:
    socket_address:
       address: 0.0.0.0
       port_value: 9902

layered_runtime:
  layers:
  - name: admin
    admin_layer: {}

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8022
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service1
                decorator:
                  operation: check_server1
          http_filters:
          - name: envoy.filters.http.tap.cfx
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.tap.v3.Tap
              common_config:
                static_config:
                  match_config:
                    http_request_headers_match:
                      headers:
                      - name: x-call-trace-id
                        present_match: true
                  output_config:
                    streaming: true
                    sinks:
                    - format: JSON_BODY_AS_STRING
                      file_per_tap:
                        path_prefix: /etc/envoy/
                    max_buffered_rx_bytes: 1000000
                    max_buffered_tx_bytes: 1000000
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: service1
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9922
2) cat _2062011462271729763.json
{
 "http_streamed_trace_segment": {
  "trace_id": "2062011462271729763",
  "request_headers": {
   "headers": [
    {
     "key": ":authority",
     "value": "127.0.0.1:8022"
    },
    {
     "key": ":path",
     "value": "/trace"
    },
    {
     "key": ":method",
     "value": "GET"
    },
    {
     "key": ":scheme",
     "value": "http"
    },
    {
     "key": "user-agent",
     "value": "curl/7.61.1"
    },
    {
     "key": "content-type",
     "value": "application/json"
    },
    {
     "key": "accept",
     "value": "application/json"
    },
    {
     "key": "add-by-cliff",
     "value": "content-added-by-cliff"
    },
    {
     "key": "x-call-trace-id",
     "value": "1"
    },
    {
     "key": "content-length",
     "value": "26"
    },
    {
     "key": "x-forwarded-proto",
     "value": "http"
    },
    {
     "key": "x-request-id",
     "value": "3bc05595-1feb-4524-85fc-9e41013f5b12"
    }
   ]
  }
 }
}
{
 "http_streamed_trace_segment": {
  "trace_id": "2062011462271729763",
  "request_body_chunk": {
   "truncated": false,
   "as_string": "{\"name\":\"cliff_test body\"}"
  }
 }
}
{
 "http_streamed_trace_segment": {
  "trace_id": "2062011462271729763",
  "response_headers": {
   "headers": [
    {
     "key": ":status",
     "value": "200"
    },
    {
     "key": "content-type",
     "value": "application/json"
    },
    {
     "key": "content-length",
     "value": "23"
    },
    {
     "key": "server",
     "value": "Werkzeug/2.0.3 Python/3.6.8"
    },
    {
     "key": "date",
     "value": "Mon, 26 Jun 2023 18:17:36 GMT"
    },
    {
     "key": "x-envoy-upstream-service-time",
     "value": "4"
    }
   ]
  }
 }
}
{
 "http_streamed_trace_segment": {
  "trace_id": "2062011462271729763",
  "response_body_chunk": {
   "truncated": false,
   "as_string": "{\"server\":\"Flask cfx\"}\n"
  }
 }
}

 
thanks 
Cliff

**Comment by kyessenov** [comment]
CC @daixiang0

**Comment by coolg92003** [comment]
thanks @kyessenov , I can help on test.

**Comment by daixiang0** [comment]
@xu1zhou could you talk a look?

**Comment by xu1zhou** [comment]
Hi, @coolg92003 , Can you reformat the configuration you provided in yaml firstly? It's hard to get your intention with unformatted text. thx.

**Comment by coolg92003** [comment]
Hi @xu1zhou,
do you want the envoy configuration file with yaml format? or
you want the my expected output with yaml format?

Also, I can't attached the file here. Can I send email to you?
thanks
Cliff

**Comment by xu1zhou** [comment]
Comment support markdown format, you can use "```"  enclose the configuration with correct indent. Here is an example:

```yaml
envoy.conf content

```

**Comment by coolg92003** [comment]
[ftapenvoy.zip](https://github.com/envoyproxy/envoy/files/11997891/ftapenvoy.zip)

**Comment by coolg92003** [comment]
Hi @xu1zhou 
I have attached my Envoy configuration file, you can dump have a look.
thanks
Cliff

**Comment by coolg92003** [comment]
![Expectoutput](https://github.com/envoyproxy/envoy/assets/12623728/4b322f7c-d9af-4fc8-9d10-63a5b334cc3e)

**Comment by coolg92003** [comment]
The marked with red line is expected new added fields.
For trace_id, use the existed logical. in Tap http fields, once the "streaming" is set as true
For "caught request/Response time", it will use system time
For below four fields
  source_ip: 10.10.10.1
  source_port: '65537'
  dst_ip: 10.10.10.3
  dst_port: '8080'
I don't have idea on how to get them :(

Also, this need add flag in "output_config" of  tap HTTP filter 
Trace_time:false(default)
     if it is true, output the request/response caught time
Connection_info:false(default)
     if it is true, output source_ip/port and dst_ip/port
Still studying ......
thanks
Cliff

**Comment by coolg92003** [comment]
![possibleEnvoyConfigforNewTap](https://github.com/envoyproxy/envoy/assets/12623728/7607c1cd-bb58-43ac-9bc8-0f0c1bb7dad4)
Hi @xu1zhou @daixiang0 
Would you review this configuration and above output? 
Please let me know whether it is doable
thanks
Cliff

**Comment by coolg92003** [comment]
Any response?

**Comment by coolg92003** [comment]
Hi @daixiang0 ,  @xu1zhou @timperrett,
After latest study, I figure out code changes for message caught time
1.Changes in Configuration of LDS:
![caughtTimeConfigFlag](https://github.com/envoyproxy/envoy/assets/12623728/6da216c8-0906-474e-94f7-759b5f584ab5)

2. output in final file
![caughtTimeOutpu](https://github.com/envoyproxy/envoy/assets/12623728/f39d813a-800b-4d2e-882a-e0e3d7ce07ab)

3. code changes
[cliffEnvoy3.pdf](https://github.com/envoyproxy/envoy/files/12076813/cliffEnvoy3.pdf)

would you please let me know for any issue?
thanks
Cliff

**Comment by daixiang0** [comment]
> 

Good job, you can post a PR and request for review, sorry that I am busy for other things:(

**Comment by coolg92003** [comment]
hi @daixiang0 
Great thanks!
Let me have a try.
Cliff

**Comment by coolg92003** [comment]
hi @daixiang0 ,
I just submit PR as below:
https://github.com/envoyproxy/envoy/pull/28472
Please let me know anything needed.
Appreciated your help!
Cliff

**Comment by coolg92003** [comment]
hi @daixiang0 ,
Would help find someone to approve below changes?
https://github.com/envoyproxy/envoy/pull/28472
thanks
Cliff

**Comment by coolg92003** [comment]
hi @daixiang0 
Would you help me on this PR? I spent lots of time on test code. :(
https://github.com/envoyproxy/envoy/pull/28472

great thanks!!!
Cliff

**Comment by coolg92003** [comment]
Http tap class big pic for reference in attachment
[httpTapClass.xlsx](https://github.com/envoyproxy/envoy/files/12384370/httpTapClass.xlsx)

**Comment by coolg92003** [comment]
Caught time Request is submitted by https://github.com/envoyproxy/envoy/pull/28472

**Comment by coolg92003** [comment]
downstream connection address:
https://github.com/envoyproxy/envoy/pull/29420
