### ISSUE TITLE
Passing limit overrides from one filter to local_rate_limit filter

### ISSUE THREAD

**Issue by rakeshdatta** [envoyproxy/envoy#28194]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Making local_rate_limit filter use tenant overrides*

*Description*:
>
Requirement:
- the ability to override local_rate_limit filter (and any other out-of-the-box network/http filter) configs, with tenant-specific filter configs.

The solution I tried and tested:
- When a downstream connection is received, a listener/network/HTTP filter finds the tenant-id that came in the connection metadata and figures out the tenant-specific local rate limit config. Snaps it to dynamic metadata/filter state.
- When a local_rate_limit filter is hit next, it checks for the presence of the tenant overrides in dynamic metadata. If present, local_rate_limit filter uses that to construct the limiter object that is used for the connection going forward. If not, the local_rate_limit filter config is used as a default.

Questions:
- For per-connection rate-limiting the above seems to be reasonable. Any thoughts?
- Is there a more generic solution for standard filters using tenant-id overrides, that I can leverage?
- For 'non' per-connection rate-limiting, the token bucket is maintained at the filter/filter-chain level. If I have to introduce a tenant override, I have to create a per-tenant token bucket. Seems like some code needs to be written there. Is there any out-of-the-box or better solution? We don't want to keep modifying the standard filter code to use tenant overrides.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by rakeshdatta** [comment]
@mattklein123 Requesting help. Thanks!

**Comment by kyessenov** [comment]
The feature request looks reasonable. There were several requests for "dynamic" token bucket creation if you search for the issues. You can accomplish what you want if you know the entire list of tenants and then create a descriptor for it and an individual bucket for each tenant.

**Comment by rakeshdatta** [comment]
Hi @kyessenov Thanks for the reply. Let me float a PR on the local_rate_limit PR on that proposal.
Having said that, could u plz help me with the other query I had above:
- Is there a more generic solution for standard filters using tenant-id overrides, that I can leverage? We don't want to keep modifying the standard filter code to use tenant overrides.

**Comment by rakeshdatta** [comment]
@kyessenov any suggestions?

**Comment by rakeshdatta** [comment]
> Hi @kyessenov Thanks for the reply. Let me float a PR on the local_rate_limit PR on that proposal. Having said that, could u plz help me with the other query I had above:
> 
> * Is there a more generic solution for standard filters using tenant-id overrides, that I can leverage? We don't want to keep modifying the standard filter code to use tenant overrides.

@kyessenov any suggestion?
