### ISSUE TITLE
gRPC-JSON transcoder mapping issue

### ISSUE THREAD

**Issue by heywoodj** [envoyproxy/envoy#28217]
I currently have an instance of Envoy, version 1.18.2, set up to handle the the translation of a JSON REST HTTP 1.1 request to a gRPC HTTP 2.0 back end service following the guide below.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter

---

In my scenario the proto files are of the following structure, 

message TestRequest {      
        TestObject TestObject  = 1; 
        **map<string, namespace.Object1> testData = 2;** 
        repeated Objects objects = 3;                              
}

message Object1
{
    string string1 = 1;
    repeated Object2 object2s = 2;
    repeated Object3 object3s = 3;
    repeated Object4 object4s = 4;
    …
}

If I make a request using the following JSON structure with no child objects specified in the 'testData' map type,

{
    "objects": [
        ….
    ],
    "testObject": {
        ....
    },
    "testData": {
        "MyTestData": {}
    }
}

I can see the message body being passed through in the backend service logs, below, which indicates configuration, and the compiled .pb file, are set up correctly.

"message":{"testObject": {..,}, "testData":[{"key":"MyTestData","value":{}}],"objects": [{...}]}

---

If I make a request using the following JSON structure with a child object specified in the 'testData' map type

{
    "objects": [
        ….
    ],
    "testObject": {
        ....
    },
    "testData": {
        "MyTestData": {
             "object2s": [],
             .....
         }
    }
}

The logs in the backend service show the request body passed through as null, which seems to indicate an issue during the transcoding process in this scenario. 

"message": null

---

I am able to make a successful call directly with the same JSON using grpCurl.
Does the 'gRPC-JSON transcoder' support such a complex model structure?
Are there any logs that the transcoder outputs anywhere? It is a complete black box to me currently, thus I'm unable to diagnose any further.

**Comment by kyessenov** [comment]
The mapping from map to an array is not a valid JSON encoding of a protobuf AFAIK. Protobuf uses key-value pairs as a representation so the value is always unique for a key.

CC @lizan

**Comment by kyessenov** [comment]
Nevermind, I didn't parse it correctly. JSON looks fine actually - so would need to investigate further.

**Comment by heywoodj** [comment]
This issue can be closed now, it was an issue unrelated to the transcoder.
