### ISSUE TITLE
claim_to_headers - JWT with Polish letter claim cause strange char in header

### ISSUE THREAD

**Issue by BobakMariusz** [envoyproxy/envoy#28230]
*Title*: claim_to_headers - JWT with Polish letter claim cause strange char in header*

*Description*:

When I use claim_to_headers and this claim has Polish letter for example "ł" cause that 
In forwarded header I have wrongly decoded char for example I get Marek Ogarek-MikoÅ�aj but expected: Marek Ogarek-Mikołaj

*Repro steps*:

claim_to_headers:
    - header: x-user-name
      claim: name

JWT:

{
....
"name": "Marek Ogarek-Mikołaj",
...
}

**Comment by kyessenov** [comment]
Generally, Envoy does not try to sanitize character encoding unless it passes through protobuf somewhere. Are you sure it's Envoy and not your terminal rendering? Is this UTF-8 or latin1 at the source?

**Comment by BobakMariusz** [comment]
Well It's UTF-8, I'm using Envoy throught Istio (so under the hood Istio configure Envoy), and when I'm pass header x-user-name by myself like that:
"x-user-name: Marek Ogarek-Mikołaj" - it's properly printed and stored, but when I'm using thorugh the Envoy it's cause that strange char.
Reproducing should be simple.

**Comment by BobakMariusz** [comment]
I think I have found problem and it seems it's on spring boot side.
