### ISSUE TITLE
In Java, the newly added `value_bytes` field in `envoy.config.core.v3.HeaderValue` conflicts with the `value` field.

### ISSUE THREAD

**Issue by socar-brad** [envoyproxy/envoy#28243]
*Title*: In Java, the newly added `value_bytes` field in `envoy.config.core.v3.HeaderValue` conflicts with the `value` field.

*Description*:
Java automatically creates a field that can be accessed as a ByteString for a string field by appending the suffix `Bytes`.
Therefore, both the `value` field and the `value_bytes` field will generate the same fields as `getValueBytes`.
So the field names are duplicated and the corresponding protobuf message is not built in Java.

<img width="903" alt="Screenshot 2023-07-05 at 5 20 14 PM" src="https://github.com/envoyproxy/envoy/assets/42597502/1b88d0e5-fc0e-44e6-b4aa-3163f0e50756">

**Comment by kyessenov** [comment]
This is a recently introduced field in https://github.com/envoyproxy/envoy/pull/27865.

I think it was unexpected that Java protobuf would have an issue with `value_bytes`. I'm not familiar with the specific of Java protobuf. cc @yanjunxiang-google @htuch 

We are still within the 14 days window from the merge of the PR that added the field, so the simplest thing to do might be to rename it now.

**Comment by yanjunxiang-google** [comment]
Ok, let me rename it as value_in_bytes

**Comment by yanjunxiang-google** [comment]
This is the PR to change value_bytes into value_in_bytes: 
https://github.com/envoyproxy/envoy/pull/28245

**Comment by yanjunxiang-google** [comment]
How can we capture this kind of the issues in the future, like Java proto compiler has some special requirements?

**Comment by yanjunxiang-google** [comment]
And, BTW, @socar-brad , I am not familiar with the Java proto compiler. Quick question, should the ByteString accessor for value_bytes field be getValueBytesBytes() instead of getValueBytes()?

**Comment by socar-brad** [comment]
Thank you very much for the quick fix. But there is no option in the Java proto compiler to use a different naming instead of getValueBytes().

I'm not familiar with Java protobuf compiler. Maybe I think the option in the link below is the whole of the current protobuf compiler.

https://github.com/protocolbuffers/protobuf/blob/9609f42dd7600b89868d07b089ef6d98f03ef84e/src/google/protobuf/descriptor.proto#L388-L507

**Comment by adisuissa** [comment]
This issue has been fixed in #28245.
