### ISSUE TITLE
support LB_TYPE field in access log

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/envoy#28256]
*Title*: support LB_TYPE field in access log

*Description*:
>Currently access log does not support LB_TYPE, If accepted, I can complete this.

https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
Can you explain what LB_TYPE is? Is that the upstream cluster load balancer field? You can populate the cluster name in the access log, wouldn't that be enough?

**Comment by tmsnan** [comment]
> 

Yes，It can directly indicate the load balancing strategy used by the cluster, and can distinguish whether to use SubsetLoadBalancer. The cluster field needs to query the config_dump interface to confirm which load balancing strategy is used.

**Comment by kyessenov** [comment]
Ok, so it's literally the upstream cluster lb_type field. It sounds reasonable but also very specific, not sure if there was another field that queries upstream cluster xDS config added before.
