### ISSUE TITLE
CommonTlsContext.alpn_protocols function for DownstreamTlsContext and UpstreamTlsContext

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#28262]
*Title*: *CommonTlsContext.alpn_protocols function for DownstreamTlsContext and UpstreamTlsContext*

*Description*:
What does CommonTlsContext.alpn_protocols do for DownstreamTlsContext and UpstreamTlsContext? 
For DownstreamTlsContext, is it used to verify the alpn of the client? If the match fails, the tls handshake fails?

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-commontlscontext

**Comment by kyessenov** [comment]
ALPN is a standard field in TLS https://datatracker.ietf.org/doc/html/rfc7301. It's supposed to be negotiated between the client and the server (first matching in the list wins).

**Comment by kyessenov** [comment]
Yeah, I think it's the literal ALPN set in Hello messages - my memory is fuzzy and would need to look at the code.

The filter chain match field matches on the peer presented ALPN. The idea there was "sniff" TLS, and then adjust what the server does based on ALPN in hello message, see comment here https://github.com/envoyproxy/envoy/blob/c53f81a43f44c7a3ea56bdda4a82044dbd78aafe/api/envoy/extensions/matching/common_inputs/network/v3/network_inputs.proto#L89.
