### ISSUE TITLE
How Do I Compile the data-plane-api into a Linux Static Library?

### ISSUE THREAD

**Issue by lennonchan** [envoyproxy/envoy#28263]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *How Do I Compile the data-plane-api into a Linux Static Library?*

*Description*:
>Describe the issue.
How Do I Compile the data-plane-api into a Linux Static Library?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
data plane api are protobufs. What language are you compiling them to? You need to generate the protobufs in that language and link them in.

**Comment by lennonchan** [comment]
C++ language

**Comment by kyessenov** [comment]
There are bazel targets in `api/` directories, one for each language. There is no "all protos" in C++, but there is a descriptor set defined here https://github.com/envoyproxy/envoy/blob/main/api/BUILD#L358. You would need to do the same for `*_cc_proto` targets, and then force link them statically.

**Comment by lennonchan** [comment]
I am just getting started with Bazel. Could you please help me with a detailed explanation on how to proceed? My requirement is to use C++ language to obtain xds data from Istio and parse it into the model defined in the data-plane-api. I used the compilation command `bazel build envoy/service/discovery/v3:pkg_cc_grpc ` and compiled libpkg_cc_grpc.a and libpkg_cc_grpc.so. Can these two libraries meet my requirements?
