### ISSUE TITLE
Is Degraded health working for gRPC

### ISSUE THREAD

**Issue by qudongfang** [envoyproxy/envoy#28287]
*Description*:

> Envoy supports marking certain endpoints as degraded, meaning that they are able to receive traffic, but should only receive traffic once there are not sufficient healthy hosts available.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#degraded-health

I want to know if this is also supported for gRPC.

**Comment by kyessenov** [comment]
gRPC is normally treated as http/2 traffic, so the HTTP controls apply like usual. So the answer is yes.

**Comment by qudongfang** [comment]
> gRPC is normally treated as http/2 traffic, so the HTTP controls apply like usual. So the answer is yes.

Theoretically, Yes.
Just that I couldn't find the evidence in the Enovy source code.

- [http/health_checker_impl.cc](https://github.com/envoyproxy/envoy/blob/a0620080acf46534675bc6484c8127ff1c2d0898/source/extensions/health_checkers/http/health_checker_impl.cc#L357) checks `response_headers_->EnvoyDegraded()`
- [grpc/health_checker_impl.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/health_checkers/grpc/health_checker_impl.cc) does not.

**Comment by qudongfang** [comment]
I noticed that you worked on these 2 health checkers. can you help to clarify this? @alyssawilk

**Comment by botengyao** [comment]
@qudongfang Yes, degraded only work for [http](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking.html#degraded-health) health checker right now. gRPC is mainly following this service contract https://github.com/grpc/grpc/blob/master/doc/health-checking.md

```
message HealthCheckResponse {
  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
    SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
  }
  ServingStatus status = 1;
}
```

**Comment by qudongfang** [comment]
Thanks for all your help, I'll close this issue.
