### ISSUE TITLE
No connection close notifications for HTTP/1.1 downstream with UDS

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2829]
Connections created for UDS listeners don't generate explicit `EV_CLOSED` events in libevent. Instead, they signal connection close as `EV_READ | EV_WRITE`, relying on a failed `EV_READ` to detect close. This is problematic in pipelined HTTP/1.1 connections, where read has been disabled between requests, since no `EV_READ` is seen. See https://github.com/envoyproxy/envoy/blob/28cca62a9de32c73793d3415b9c5e7dbe95feeb1/source/common/http/conn_manager_impl.cc#L257.

Will disable tests of this condition for now, since the behavior is essentially that we don't support UDS + early connection notifications.

**Comment by mattklein123** [comment]
I don't think this can be fixed so let's track specific issues that come up instead (like the recent admin tap issue).
