### ISSUE TITLE
Is dispatcher thread-local?

### ISSUE THREAD

**Issue by kingluo** [envoyproxy/envoy#28293]
That is, could I call `dispatcher.post()` from another thread? I need to put a task into the worker thread from another thread.

**Comment by kyessenov** [comment]
Yes, that's a normal way how thread local storage works, it posts from main thread to worker threads with an updated value.

**Comment by kingluo** [comment]
> Yes, that's a normal way how thread local storage works, it posts from main thread to worker threads with an updated value.

Thanks for your reply. And I just confirmed this fact in my coding. BTW, you mean the main thread posts xds update to the worker thread, right?

Another side question is whether the post is done by a locked queue and eventfd in Linux, and the worker thread will handle the post callbacks in batch, right?

**Comment by kyessenov** [comment]
I think it's edge triggered. It's using libevent for event management, but I don't recall the details.
