### ISSUE TITLE
Envoy Proxy + Keydb Cluster - not able to utilize all cores

### ISSUE THREAD

**Issue by javedsha** [envoyproxy/envoy#28314]
*Title*: *When running envoy proxy in front of keydb cluster with multithreading on, keydb cpu utilization is not going above 100.*

*Description*:
I am using Envoy as a proxy (side car) to Keydb Cluster. With multithreading on (server-threads = 4), and Envoy concurrency set to 4, the keydb cpu utilization doesn't go above 100. In htop I expect to see keydb using ~400% CPU.

Tried generating high throughput via Memtier (48 vcores, 64 gb RAM), but keydb still uses ~100% CPU, and hardly any increase in throuhput, but Latency increases a lot.

I also found the min-clients-per-thread setting which is set to 140 by default. I changed this to 4, as with envoy proxy running on 6 instances, number of client connections is close to 20. But this doesn't help.

*Envoy Config (main parts)*:
{
  "static_resources": {
    "listeners": [
      {
        "name": "keydb_listener",
        "address": {
          "socket_address": {
            "address": "0.0.0.0",
            "port_value": 6380
          }
        },
        "filter_chains": [
          {
            "filters": [
              {
                "name": "envoy.redis_proxy",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy",
                  "stat_prefix": "keydb_stats",
                  "prefix_routes": {
                    "catch_all_route": {
                      "cluster": "KeyDbCluster"
                    }
                  },
                  "settings": {
                    "op_timeout": "1s",
                    "enable_redirection": true,
                    "enable_command_stats": true,
                    "read_policy": "MASTER"
                  }
                }
              }
            ]
          }
        ]
      }
    ],
    "clusters": [
      {
        "name": "KeyDbCluster",
        "connect_timeout": "15s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "CLUSTER_PROVIDED",
        "cluster_type": {
          "name": "envoy.clusters.redis",
          "typed_config": {
            "@type": "type.googleapis.com/google.protobuf.Struct",
            "value": {
              "cluster_refresh_rate": "30s",
              "cluster_refresh_timeout": "10s",
              "redirect_refresh_interval": "5s",
              "redirect_refresh_threshold": 5
            }
          }
        },
        "load_assignment": {
          "cluster_name": "KeyDbCluster",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "127.0.0.1",
                        "port_value": 6380
                      }
                    }
                  }
                }
              ]
            }
          ]
        }
      }
    ]
  }
}

*KeyDb config - main parts:*
port 0
cluster-enabled yes
cluster-config-file /nodes.conf
cluster-node-timeout 5000
appendonly no
save 3600 1
tls-auth-clients yes
tls-replication yes
tls-cluster yes
server-threads 3
server-thread-affinity true
min-clients-per-thread 4

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by alyssawilk** [comment]
can you add a bit more detail here to explain why you think Enovy is the bottleneck?  Do you see CPU saturation without Envoy in the way?  Are you sure you're sending enough QPS you'd expect to still saturate?
