### ISSUE TITLE
continueEncoding may not work correctly when filter return StopAllIterationAndBuffer in encodeHeaders

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#28326]
*Title*: *continueEncoding may not work correctly when filter return StopAllIterationAndBuffer in encodeHeaders*

*Description*:

when a http L7 filter return `StopAllIterationAndBuffer `in `encodeHeaders` phase, and it will call `continueEncoding` after a while(it may wait for a async http call response), so the filter chain will iterate from current filter. Then if the filter return `StopIterationNoBuffer` in `encodeData` phase and return `Continue` in `encodeTrailers` phase, the filter will call `commonContinue` again, finally, the filter will be called again in `encodeData` phase since `iterate_from_current_filter_` (https://github.com/envoyproxy/envoy/blob/bd836c22030b20624142c78fc16773d4bb2e582e/source/common/http/filter_manager.cc#L74) are always true and it will return here(https://github.com/envoyproxy/envoy/blob/bd836c22030b20624142c78fc16773d4bb2e582e/source/common/http/filter_manager.cc#L1313), the following filters' `encodeData` will not be called, and the response will be blocked.

**Comment by StarryVae** [comment]
i think we can set `iterate_from_current_filter_` to false at the beginning of `commonContinue` to solve this problem.

**Comment by alyssawilk** [comment]
cc  @KBaichoo

**Comment by StarryVae** [comment]
@KBaichoo PTAL, thanks.

**Comment by KBaichoo** [comment]
Is the issue:
1. We StopAllIterationAndBuffer in encodeHeaders
2. Continue (after callback) which invokes continueEncoding
3. continueEncoding invokes encodeData and encodeTrailers within the same call?

The blockage seems to align with the API:
https://github.com/envoyproxy/envoy/blob/8876882b5db9fd0c8d3ddc1b883061d234c92f1a/envoy/http/filter.h#L153-L155

**Comment by StarryVae** [comment]
yes, continueEncoding invokes encodeData and encodeTrailers, if `encodeData` return `StopIterationNoBuffer`, data phase will be blocked, but it will go to `encodeTrailers` phase, and if `encodeTrailer` return `Continue`, just as what i said above, the filter will call `commonContinue` again, , finally, the filter will be called again in `encodeData` phase since `iterate_from_current_filter_`(https://github.com/envoyproxy/envoy/blob/bd836c22030b20624142c78fc16773d4bb2e582e/source/common/http/filter_manager.cc#L74) are always true and it will return here(https://github.com/envoyproxy/envoy/blob/bd836c22030b20624142c78fc16773d4bb2e582e/source/common/http/filter_manager.cc#L1313), the following filters' encodeData will not be called, and the response will be blocked.

**Comment by StarryVae** [comment]
friendly ping @KBaichoo

**Comment by KBaichoo** [comment]
Can you provide a prototype demonstrating this? I tried modifying  the test

```
bazel test //test/extensions/filters/http/kill_request:crash_integration_test --test_arg="-l trace" --test_filter=*EncodeContinueAddsCrashContextIfNoneExists*
```

which has a filter that does `StopIterationNoBuffer` and it doesn't run into this issue described. 

Thank you

**Comment by StarryVae** [comment]
https://github.com/hango-io/envoy-proxy/blob/main/source/filters/http/dynamic_downgrade/dynamic_downgrade_filter.cc

this is a dynamic downgrade filter that can demonstrate this bug, it will return `StopAllIterationAndBuffer in encodeHeaders(`https://github.com/hango-io/envoy-proxy/blob/9180fb5b82ee4805ed80c415275659cdb88809e7/source/filters/http/dynamic_downgrade/dynamic_downgrade_filter.cc#L287), and calls `continueEncoding`(https://github.com/hango-io/envoy-proxy/blob/9180fb5b82ee4805ed80c415275659cdb88809e7/source/filters/http/dynamic_downgrade/dynamic_downgrade_filter.cc#L351) here, it will go to encodeData and return `StopIterationNoBuffer`(https://github.com/hango-io/envoy-proxy/blob/9180fb5b82ee4805ed80c415275659cdb88809e7/source/filters/http/dynamic_downgrade/dynamic_downgrade_filter.cc#L324). Then it will go to encodeTrailer and return `Continue`.

**Comment by KBaichoo** [comment]
I think I understand your the issue now, thanks for the pointers. I *think* this is a filter issue, as the API for StopIterationNoBuffer says we need to call `continueEncoding()`.
See:
https://github.com/envoyproxy/envoy/blob/8876882b5db9fd0c8d3ddc1b883061d234c92f1a/envoy/http/filter.h#L152-L155

If you want the drained buffer to contuinue the filter chain, consider draining it and returning continue, or out of stack doing a continueEncoding() call explicitly by the user.

The encodeTrailer's  `commonContinue()` is nested on top of the original `continueEncoding()` commonContinue which set  https://github.com/envoyproxy/envoy/blob/bd836c22030b20624142c78fc16773d4bb2e582e/source/common/http/filter_manager.cc#L74 to true.

If you explicitly made the continueEncoding call as API instructs then the above would be set back to false which would continue to the next filter.

**Comment by StarryVae** [comment]
yes, it is the problem! 👍 and if this can fix this?

```
  if (stoppedAll()) {
    iterate_from_current_filter_ = true;
  } else {
    iterate_from_current_filter_ = false;
  }
```
if so, i will submit a PR, thanks. cc @KBaichoo

**Comment by StarryVae** [comment]
> i think we can set `iterate_from_current_filter_` to false at the beginning of `commonContinue` to solve this problem.

or we can set `iterate_from_current_filter_` to false at the beginning of `commonContinue`?

**Comment by KBaichoo** [comment]
I'm hesitant to make this change this area since we are violating the expectations of what the filter API says (e.g. the desired behavior != API guaranteed behavior which makes me view this more as a bug in the filter).

From above:
https://github.com/envoyproxy/envoy/blob/8876882b5db9fd0c8d3ddc1b883061d234c92f1a/envoy/http/filter.h#L152-L155 

Namely `calling continueDecoding()/continueEncoding() MUST be called if continued filter iteration is desired. ` but we NEVER make a call to either of those.

**Comment by StarryVae** [comment]
emm, 😕 but if the filter want to replace the body, it can only return ` StopIterationNoBuffer` and wait for the `end_stream` to be true, however, if response has trailers, `end_stream` in `encodeData` phase will never be true, so i have no idea how can i call `continueEncoding`?

**Comment by KBaichoo** [comment]
Sorry for the delay.

if the filter wants to drain the body can it not just `buffer.drain(buffer.length())` and return `Continue`? The empty buffer should not be encoded but it should make it through to next filters?

If the filter wants to replace the body it could drain the buffer as above and inject what it needs or do a `StopIterationAndBuffer` if it needs to make an async call to get the replacement -- yes it'd be buffering nothing.

How do those work for your use case?

**Comment by StarryVae** [comment]
" If the filter wants to replace the body it could drain the buffer as above and inject what it needs or do a StopIterationAndBuffer if it needs to make an async call to get the replacement "  ----   sorry, i am confused about this, as i know, if the filter wants to replace the whole body, it should return `StopIterationAndBuffer` or `StopIterationNoBuffer` until `end_stream` is true and replace the body, return `Continue`, but if response has trailers, `end_stream` in `encodeData` phase will never be true, so the filter will go to `encodeTrailer` phase and return `Continue`.

**Comment by StarryVae** [comment]
in my case, it needs to make an async call to get the replacement, so i make an async call in `encodeHeaders` phase and return `StopAllIterationAndBuffer `, and when the async call returns, it will get the replacement and  call `continueEncoding` to go to the `encodeData` to replace the body.

**Comment by KBaichoo** [comment]
> in my case, it needs to make an async call to get the replacement, so i make an async call in encodeHeaders phase and return StopAllIterationAndBuffer , and when the async call returns, it will get the replacement and call continueEncoding to go to the encodeData to replace the body.

In your case IIUC you have the full response available after  encodeHeader async call does continueEncoding() after a `StopAllIterationAndBuffer`, this starts `encodeData` where you apply the replacement  -- can't you switch the filter to "drop any body coming to it" after it's applied the replacement using the drain method above?

**Comment by StarryVae** [comment]
i think i know what you mean, after the body replacement i can always drain the body and return `Continue`, so there is no need to return Stop in `encodeData`, thanks a lot ❤️ @KBaichoo

**Comment by KBaichoo** [comment]
Glad you can fulfill your use case :)
