### ISSUE TITLE
Connection draining on SDS update

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#28386]
In case I'm using LDS, where some of the filter chains in the listener config have SDS config (downstream transport TLS that uses SDS to fetch secrets). After a while, the certificate is refreshed from the SDS. Does it cause connections that currently use the filter chain to drain? Will only new connections get the new certificate?

**Comment by soulxu** [comment]
there is no draining, only the new connection will use the new certificate

**Comment by ohadvano** [comment]
Thanks
