### ISSUE TITLE
Envoy memory leak

### ISSUE THREAD

**Issue by amolbms** [envoyproxy/envoy#28396]
*Title*: Envoy memory leak

*Description*:
We are using Envoy as an edge proxy for accessing backend capacity. We have xDS service built using go-control-plane to provide dynamic configs.  We have custom filters for admission control, authentication etc. Recently we noticed as our number of routes starts to go above 2K there is a memory leak in Envoy. Envoy startup requires 1.7GB of memory and within 3 days it jumps to above 3GB. 
![image](https://github.com/envoyproxy/envoy/assets/116984700/af4c1d3c-a285-46aa-9c35-455b3cb0c0fe)

*Repro steps*:
We have tried disabling xDS update with no traffic routed to these instances, but we still see the memory leak. We have gathered memory stats but it turned out to be not useful as the "total_physical_bytes" show 1.3GB of memory vs process memory from "top" is above 3GB. We captured heap dump but it does not account for the extra process memory, and it matches what admin stats memory shows. This extra memory might be not coming from TCMalloc allocated memory. We do have few lua filters which we can try removing. Can you provide guidance on how we can investigate this further?

*Admin and Stats Output*:
Here is memory stats from admin endpoint. 
{
"allocated": "1118031664",
"heap_size": "10133438464",
"pageheap_unmapped": "8775655424",
"pageheap_free": "152100864",
"total_thread_cache": "93160",
"total_physical_bytes": "1376099358"
}

Envoy version: 1.26.1

**Comment by alyssawilk** [comment]
@yanavlasov throwing this not your way to own, but can you suggest next steps for debugging for them?
cc @adisuissa for possible xDS issues

**Comment by nitgoy** [comment]
Another detail to add for our use case that might be relevant is that we use a lot of filter chains (one for each of our user facing endpoints). In above case we have around ~3k such filter chains initialized. The most surprising part is that we see envoy leaking memory without any traffic or xDS updates.

**Comment by amolbms** [comment]
Thanks @adisuissa  for suggestions. I have started run without filter chain. I will update my findings. Yes, we see this memory spike without traffic/xDS updates. We provide initial config through xDS and then stop the xDS server.

**Comment by haoruolei** [comment]
Adding some more data points here. We did memory dumps with both gperftools and tcmalloc following the instructions. What we found is that the in-use space didn't change a lot in a span of 4-5 days (less t
![profile 06302030](https://github.com/envoyproxy/envoy/assets/109187153/4cc2405a-124d-440a-bcb7-6976f39975a6)
![profile 07051400](https://github.com/envoyproxy/envoy/assets/109187153/a065c993-4448-4445-a8f7-57f946c09add)
![profile diff](https://github.com/envoyproxy/envoy/assets/109187153/67bed56b-28bc-4973-87e1-1ddd225342ae)
han 1GB). However, the envoy process memory usage increased and went up to more than 3GB. I attached 3 pprof graphs: 2 individual graphs on 6.30 and 7.5, one graph their diff.

**Comment by haoruolei** [comment]
Also share the graphs based on memory metrics queried from envoy admin interface, and envoy process memory usage in the same time period. Allocated memory and physical memory didn't change a lot. But the heap size and unmapped page size kept climbing. What's interesting is that the trends doesn't explain the sudden "jump" in process memory usage.

![Figure_1](https://github.com/envoyproxy/envoy/assets/109187153/4aed9f50-eb53-4c6c-9f36-1aa92467ede0)

<img width="826" alt="Screenshot (29)" src="https://github.com/envoyproxy/envoy/assets/109187153/83d6eee2-afdb-4f2b-8e9a-ce78c1609f95">

**Comment by quyenhoang96** [comment]
I have a same problem with image: 
```
envoyproxy/envoy:v1.26-latest
```
<img width="1705" alt="Screenshot 2023-07-21 at 21 44 08" src="https://github.com/envoyproxy/envoy/assets/120354221/6911feec-affb-48a0-81a0-a8368f0138e7">

**Comment by amolbms** [comment]
We investigated the issue and found it to be due to huge page bloat. TCMalloc uses huge page and we found during the memory jump below traces,
I see the trace khugepaged-61      [001] ..... 664191.724013: mm_collapse_huge_page_isolate: scan_pfn=0x13da00, none_or_zero=275, referenced=237,
writable=1, status=succeeded
khugepaged-61      [001] ..... 664191.724017: <stack trace>
=> trace_event_raw_event_mm_collapse_huge_page_isolate
=> __collapse_huge_page_isolate
=> collapse_huge_page
=> khugepaged_scan_pmd
=> khugepaged_scan_mm_slot
=> khugepaged
=> kthread
=> ret_from_fork  

TCMalloc suggests to set the max_ptes_none to 0, TCMalloc suggests setting this value to 0 (it is 511 by default). Default value can cause significant bloat and we found it not stabilizing even after running for few days. https://github.com/google/tcmalloc/blob/master/docs/tuning.md#system-level-optimizations
After setting max_ptes_none to 0, we no longer see the memory bloat. Does Envoy see any downside to setting this value? Is it recommended setting for Envoy?
