### ISSUE TITLE
ssl connection error rate increases after #24923

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#28415]
*Title*: *ssl connection error rate increases after #24923*

*Description*:
Denote connection sr = `ssl.connection_error/ssl.handshake`
Our ingress hosts' sr are usually > 99%

During our recent deployment based on https://github.com/envoyproxy/envoy/commit/3f198ba35873bba736374ea568fcfa6c4d903215,  the sr dropped to < 95% for those ingress hosts without cdn in front.
sr recovers after we manually revert #24923

we did not flip `enforce_rsa_key_usage`

**Comment by JuniorHsu** [comment]
cc author @tyxia

**Comment by tyxia** [comment]
Hi @JuniorHsu , as you can see, `enforce_rsa_key_usage` is not enabled in that PR, though adding stats counter [was_key_usage_invalid ](https://github.com/envoyproxy/envoy/blob/bd241eb77506f06f715b890e5b999beb70dd2972/source/extensions/transport_sockets/tls/context_impl.cc#L567)to track the misuse key usage.
However, that PR also reports the error in [failure reason](https://github.com/tyxia/envoy/blob/1fc1f036e3b725d0b9a6f3c6ac3fe41314608e17/source/extensions/transport_sockets/tls/ssl_socket.cc#L232) for general SSL_ERROR_SYSCALL. 

I am wondering what is the failure/error reason for the increased error rate you saw?

**Comment by JuniorHsu** [comment]
Hello @tyxia,
It's non immediately to tell the reason of increased error since the debug log is flooding.
I sample one host, connection error increased from 3 to 30 but there's 3.8k line said
`TLS error:SSL_ERROR_SYSCALL error has occured, which indicates the operation failed externally to the library. This is typically |errno| but may be something custom if using a custom |BIO|. It may also be signaled if the transport returned EOF, in which case the operation's return value will be zero.` Also 35k line like `TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer` but should be normal i guess.

(a) does it mean we have this issue before #24293? However your PR reports the issue?
(b) any suggestion to dig more?

**Comment by JuniorHsu** [comment]
I tweet some code to show log only in 
https://github.com/tyxia/envoy/blob/1fc1f036e3b725d0b9a6f3c6ac3fe41314608e17/source/extensions/transport_sockets/tls/ssl_socket.cc#L250

most of the failure reason is 
```
TLS error:SSL_ERROR_SYSCALL error has occured, which indicates the operation failed externally to the library. This is typically |errno| but may be something custom if using a custom |BIO|. It may also be signaled if the transport returned EOF, in which case the operation's return value will be zero.
```

< 10% is
`TLS error: 268435613:SSL routines:OPENSSL_internal:INAPPROPRIATE_FALLBACK`
and 
`TLS error: 268436502:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN`

**Comment by tyxia** [comment]
Yes. `SSL_ERROR_SYSCALL` is exact error that is added in https://github.com/envoyproxy/envoy/pull/24923.

Based on its [comment](https://github.com/google/boringssl/blob/6bd1e1504670dc96a76eb9858da4117bba586a41/include/openssl/ssl.h#L509) and envoy behavior that it will result in `PostIoAction::Close`. I think it is real error/failure.

I would also add ssl expert @ggreenway and @davidben  here to shed more lights on this error.

**Comment by ggreenway** [comment]
I think the only change in that PR related to these errors is in reporting: https://github.com/envoyproxy/envoy/pull/24923/files#diff-1b6d3bf54cf9bad48dd67ac9d0f87897b0669000cd0076573c4d5396733ee4d2R101

The `SSL_ERROR_SYSCALL` case previously went to `default`, but that has the same set of actions, just slightly different error reporting. But in either case it should be reported as an error.

**Comment by JuniorHsu** [comment]
Thanks @tyxia and @ggreenway!

Looks like handshake error due to `SSL_ERROR_SYSCALL` is hidden until @tyxia's work.
Next step could be more informative log given `errno` doesn't give us anything [here](https://github.com/tyxia/envoy/blob/1fc1f036e3b725d0b9a6f3c6ac3fe41314608e17/source/extensions/transport_sockets/tls/ssl_socket.cc#L207-L231) and we're using non-special amazon host.

Does envoy have utility to get BIO message as the [comment](https://github.com/google/boringssl/blob/6bd1e1504670dc96a76eb9858da4117bba586a41/include/openssl/ssl.h#L509) suggests?

**Comment by JuniorHsu** [comment]
one more observation, 
`(ssl.handshakes + ssl.session_reuse)/ downstream_cx_total` is very similar with or without the patch, which is good.
However, `downstream_cx_destroy_local` goes up with the pr, which surprises me.

**Comment by ggreenway** [comment]
> one more observation,
> `(ssl.handshakes + ssl.session_reuse)/ downstream_cx_total` is very similar with or without the patch, which is good.
> However, `downstream_cx_destroy_local` goes up with the pr, which surprises me.

That surprises me too. How much does `downstream_cx_destroy_local` increase by, as a percentage of total connections?

@tyxia I wonder if we should revert that change until we can figure out why it's causing this?

**Comment by tyxia** [comment]
That PR doesn't have functional change except error reporting for `SSL_ERROR_SYSCALL`.  For `SSL_ERROR_SYSCALL` case, the behavior has always been return `PostIoAction::Close`.

 So technically it should not cause `downstream_cx_destroy_local` . I think it will be great that we can confirm it is caused by that PR first before reverting.  Also if we want to revert, I think we can just revert `SSL_ERROR_SYSCALL` part as enable_ras_key (which is not enabled) has been asked by ssl team for a quite while. I can take care of this revert but I would like to confirm the cause here first.

**Comment by ggreenway** [comment]
I agree that it doesn't look like the PR should cause this behavior change; I looked it over again. But I'm worried we're missing something. 

@JuniorHsu can you provide more details about the setup in which you're seeing this behavior change? And any other details you can provide that might help prove or disprove that this change is causing it?

**Comment by JuniorHsu** [comment]
Let's talk about stats first.
while `ssl.connection_error` consistently get 700 more than other hosts, `downstream_cx_destroy_local` get +900 then other hosts. 
As for the rate, while `1- ssl.connection_error/ssl.handshakes` goes from 99%+ to 95%, `1-downstream_cx_destory_local/downstream_cx_total` remains the same, although the rate is around 80% and fluctuate so hard to tell.

Therefore it's hard to judge for me

About the setup, that is the ingress cluster without CDN in front. 
We revert to https://github.com/envoyproxy/envoy/commit/a0620080acf46534675bc6484c8127ff1c2d0898 + nghttp2 patch while we find stats regression on https://github.com/envoyproxy/envoy/commit/3f198ba35873bba736374ea568fcfa6c4d903215

Let me know if anything could help from our side

**Comment by JuniorHsu** [comment]
It's hard to make judgement since `downstream_cx_destroy_local` is fluctuated because of the traffic volume, probably idle timeout? The amplitude is 30% so hard to tell if the patch have impact if only revert one pr in single host since SSL_ERROR_SYSCALL only have 5% impact here.

The first time we deployed 1az of ingress hosts so the trend is easier to tell. There might be other factor like outlier detection or zone awareness yeah.

We could check tomorrow to see if we have more finding or way to tackle.

**Comment by tyxia** [comment]
I think that `1-downstream_cx_destory_local/downstream_cx_total` remains the same is a good signal. Let's focus on downstream_cx related stats and try to control the variables in the experiments if possible

**Comment by tyxia** [comment]
@ggreenway  Sure I will reverted the part related to syscall errors logging.
syscall error hanlding is not core part of tjat PR. It was added to surface the error information for testing in that PR

**Comment by ggreenway** [comment]
For future reference, here are debug logs for this happening. This is a remote-close case: I was testing with curl, and I killed the curl mid-request.

```
[2023-08-28 15:25:07.823][734886][debug][conn_handler] [external/envoy/source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:157] [Tags: "ConnectionId":"87"] new connection from 127.0.0.1:41336
[2023-08-28 15:25:07.830][734886][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:247] [Tags: "ConnectionId":"87"] remote address:127.0.0.1:41336,TLS error:SSL_ERROR_SYSCALL error has occured, which indicates the operation failed externally to the library. This is typically |errno| but may be something custom if using a custom |BIO|. It may also be signaled if the transport returned EOF, in which case the operation's return value will be zero.
[2023-08-28 15:25:07.830][734886][debug][connection] [external/envoy/source/common/network/connection_impl.cc:250] [Tags: "ConnectionId":"87"] closing socket: 0
[2023-08-28 15:25:07.830][734886][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:247] [Tags: "ConnectionId":"87"] remote address:127.0.0.1:41336,TLS error:SSL_ERROR_SYSCALL error has occured, which indicates the operation failed externally to the library. This is typically |errno| but may be something custom if using a custom |BIO|. It may also be signaled if the transport returned EOF, in which case the operation's return value will be zero.
[2023-08-28 15:25:07.830][734886][debug][conn_handler] [external/envoy/source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc:121] [Tags: "ConnectionId":"87"] adding to cleanup list
```

This condition is counted in `remote_close` stats.
