### ISSUE TITLE
Zone-aware load balancing incorrectly handles mismatched local and upstream localities

### ISSUE THREAD

**Issue by AdamEAnderson** [envoyproxy/envoy#28419]
*Zone-aware load balancing incorrectly handles mismatched local and upstream localities*

*Description*:
The zone-aware load balancing structures setup process depends on the order of localities within a `HostsPerLocality&`.
The order is stable in that it orders correctly based on the `LocalityLess` comparator and that the current envoy's local locality must always be first (if present).
If the number of local and upstream zones is different, zone-aware load balancing is automatically disabled.
However, if there are an equal number of localities in both the local and upstream, and some but not all of the localities do not match when put in sorted order, there can be a variety of bugs/odd behavior.

*Bug 1*
```
L = local envoy
U = upstream host

Zone A: 1L, 1U
Zone B: 1L, 0U
Zone C: 0L, 1U
```
Let's pick the zone-aware min cluster size as 2. Since upstream and local have the same number of localities, zone-aware load balancing is enabled.

Case 1: let zone A be the current envoy's local zone. Then zone-aware routing is enabled and in `LocalityRoutingState::LocalityDirect` routing mode, so all traffic goes to the upstream host in zone A.

Case 2: let zone B be the current envoy's local zone. Then zone-aware routing is disabled because there are no healthy upstream hosts in the current envoy's local locality. So traffic is balanced evenly between the upstream in zone A and the upstream in zone C.

If both local envoys are sending traffic at the same rate, then the upstream host in zone A will get twice as much traffic as the one in zone C.

Repro is in a unit test that establishes the current behavior [here](https://github.com/envoyproxy/envoy/commit/8b21feb0358e8bf59d9c1422a11b222bab0c7c34#diff-4b68067770bca7ef0b1482db82128aa8dfb1bccac9474ebe015f77b1f52c1a10R1288-R1350).
The reason this happens is because zone-aware routing is enabled for some envoys in the local cluster, and disabled for others. Meanwhile, the zone-aware load balancing code expects all envoys in the local cluster to also be using zone-aware load balancing.

*Bug 2*
This one is similar, but instead relies on envoy collapsing the `HostsPerLocality&` vector in sorted order (dropping localities with no hosts), and then comparing localities 1:1 when calculating zone-aware load balancing residual weights.

| Zone | Local count | Upstream count | expected residuals | actual residuals |
|---|---|---|---|---|
| A | 2 | 1 | 0% | 0% |
| B | 2 | 0 | N/A | N/A |
| C | 1 | 3 | 20.83% | 4.17% |
| D | 1 | 3 | 20.83% | 20.83% |
| E | 0 | 1 | 12.5% | 0% |
| Totals | 6 | 8 | 54.17% | 25% |

Let's look at this from the perspective of one of the envoys in zone A.

The per-locality host information will leave out localities without any hosts, so the order of sorted localities is:
```
local:    ABCD
upstream: ACDE
```
Locality load balancing is enabled because there are enough healthy hosts and the same number of localities in the upstream and downstream host sets.
First we will compute how much traffic we can send to the local zone: `(1/8)/(2/6) = 3/8 = 37.5%`.
The rest of the traffic will then be routed cross-zone weighted by the residuals.
However the residuals, due to how the localities are sorted, are the ones listed under the `actual residuals` column.
So the despite zones C and D being interchangeable (same number of local and upstream hosts), zone D will receive 5x as much traffic from the two local envoys in zone A.

Repro is a unit test that establishes the current behavior [here](https://github.com/envoyproxy/envoy/commit/8b21feb0358e8bf59d9c1422a11b222bab0c7c34#diff-4b68067770bca7ef0b1482db82128aa8dfb1bccac9474ebe015f77b1f52c1a10R1352-R1460).

*Bug 3*
This one is very minor and mostly unrelated to the above two.

[This comment](https://github.com/envoyproxy/envoy/blob/bd241eb77506f06f715b890e5b999beb70dd2972/source/common/upstream/load_balancer_impl.cc#L673-L674) (cc @htuch) is totally correct, there is an off-by-one error here.

The threshold is sampled as:
```
uint64_t threshold = random_.random() % state.residual_capacity_[number_of_localities - 1];
```
but the condition on the while is:
```
threshold > state.residual_capacity_[i]
```
This gives a small amount of weight (`1/total_residual_capacity`) incorrectly to the first upstream locality and takes the same amount away from the last upstream locality with non-zero residual capacity.

Consider, for instance, if `threshold` was randomly rolled as `0`, but `state.residual_capacity_[0] = 0`. Then we would be picking the current envoy's local locality for routing even though we've already ruled that out after the initial sampling [here](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L650-L655).

The fix is to replace the loop condition with:
```
threshold >= state.residual_capacity_[i]
```
Then the residual buckets are chosen as:
```
Bucket 1: [0, state.residual_capacity_[0] - 1]
Bucket 2: [state.residual_capacity_[0], state.residual_capacity_[1] - 1]
...
Bucket N: [state.residual_capacity_[N-2], state.residual_capacity_[N-1] - 1]
```
where an interval `[a,b]` includes both `a` and `b`

*Proposal*
The last bug is a simple one-line fix.

The other two have two potential solutions:
1. In `ZoneAwareLoadBalancerBase::earlyExitNonLocalityRouting()` [here](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L549-L580), loop over both the local and upstream `HostsPerLocality` and disable locality-based routing if the first host in each locality bucket does not match between the local and upstream hosts per locality.
2. In `ZoneAwareLoadBalancerBase::regenerateLocalityRoutingStructures()` [here](https://github.com/envoyproxy/envoy/blob/bd241eb77506f06f715b890e5b999beb70dd2972/source/common/upstream/load_balancer_impl.cc#L489-L492), instead of calculating locality percentages separately calculate them together by adding space into each percentages list so that each percentage entry matches the locality between the upstream and downstream percentages. We would add space based on the locality of the first host in each `HostsPerLocality` locality bucket, assuming that all other hosts in that locality are in the same zone. We'd also need an array of size `num_upstream_localities` to reverse the mapping from combined locality index to upstream locality index.

Approach 1 would solve the problem, but we'd have to introduce a dependency in the locality structures setup on the locality field of individual hosts within the host set.

Approach 2 would use the same piece of information, but would fix the bug in a way that extends rather than reduces functionality. With this fix, zone-aware routing would work for the following previously-broken cases:
1. *No upstream host in the local locality.* With the combined percentage calculations, this case would be handled as `LocalityRoutingState::LocalityResidual` with `state.local_percent_to_route_ = 0`. We'd be able to correctly calculate the residual capacities so that locality-aware routing would still be fair for all localities. This case would allow the scenario in bug 1 to look like: `A -> A (100%), B -> C (100%)`, fixing that bug gracefully.
2. *Upstream and local host set can have different numbers of localities.* Because we now dynamically expand the local and upstream percentages, after reconciliation the two percentage lists will have the same size no matter how many localities are in the local or upstream host set. The rest of the locality-aware routing algorithm depends only on the upstream host set, so a different number of local vs upstream localities will have no effect there.

In my opinion, both of these are major wins for zone-aware routing support in envoy. In actual production environments, many backend services are scaled differently based on expected load. In a typical cloud environment with 3 zones within the same region, you might have a mix between services with a minimal number of replicas (usually 2 to ensure HA) and services that need more replicas to meet demand (>=3 replicas).

Case 1 that's solved above by Approach 2 will fix the 2x2 routing failure and allow users to employ zone-aware load balancing between 2-replica services without risk of traffic imbalance due to zone mismatch.

Case 2 that's solved above by Approach 2 will allow many smaller services in a microservices architecture (usually each microservice is deployed with 2 replicas for HA) to use zone-aware routing while sending traffic to high-capacity services that typically have replicas in each zone. This traffic type (few replicas -> many replicas) is probably the most common locality traffic pattern in a typical modern microservices architecture.

*Next steps.*
I am happy to own fixing all three of these bugs.

I wanted to solicit opinions and feedback on the above and make sure we're on the same page with desired approach for fixing it.

For those interested, here is my work in progress [branch](https://github.com/envoyproxy/envoy/compare/main...AdamEAnderson:envoy:zone-aware-bugfixes) to fix all three issues.

**Comment by wbpcode** [comment]
cc @mattklein123
