### ISSUE TITLE
Question: how do I specify Paths (i.e. /healthecheck) in config.endpoint.v3.Endpoint.HealthCheckConfig

### ISSUE THREAD

**Issue by Ghilteras** [envoyproxy/envoy#28448]
*Title*: Question: how do I specify Paths (i.e. /healthecheck) in config.endpoint.v3.Endpoint.HealthCheckConfig

*Description*:
I would like to add a path like /healthcheck to the `config.endpoint.v3.Endpoint.HealthCheckConfig` on my Endpoints but looks like I can only specify address and port

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-endpoint-healthcheckconfig

**Comment by wbpcode** [comment]
You can only speicify the path in the configuration of cluster health checker. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#config-core-v3-healthcheck-httphealthcheck

The `config.endpoint.v3.Endpoint.HealthCheckConfig` is just used to override the health check address.

**Comment by botengyao** [comment]
Right, #28375 is relevant, looks like we can extend this to override the global one for different endpoints in the same cluster.

**Comment by Ghilteras** [comment]
Thank you guys, we can use the health check config at cluster level and only override the address at endpoint level for now just fine :) for me this can be closed, but if you want to keep it open feel free to do so

**Comment by botengyao** [comment]
Feel free to close this. Thanks!
