### ISSUE TITLE
add ECDS support for composite filter

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#28463]
Currently composite filter does not support ECDS. This feature request is to add support for config_discovery in addition to existing [typed_config](https://github.com/envoyproxy/envoy/blob/19d52b87b5a2b225d56b832e2810605f13de4bff/api/envoy/extensions/filters/http/composite/v3/composite.proto#L38)

This allows users to leverage ECDS for composite filters (like WASM filters in Istio)

**Comment by ramaraochavali** [comment]
@kyessenov

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/envoy/pull/29289? cc @ramaraochavali

**Comment by ramaraochavali** [comment]
yes. We can close this
