### ISSUE TITLE
Cluster-level retries for gRPC Service in External Processor Filter

### ISSUE THREAD

**Issue by ankoh** [envoyproxy/envoy#28475]
We started using the External Processor Filter for injecting routing headers within a service mesh.
The external processor filter provides us with fine-granular request routing without introducing a reverse proxy, and this is great.
What I am worried about, though, is the missing retry policy for ext_proc requests.

From a resiliency perspective this sounds dangerous. Should the single external processor request fail for whatever reason (network hiccup, external processor goes down, stale ingress gateway cluster), then we're left with either failing the request completely (A) or falling back to defaults (B). (A) hits availability unnecessarily especially for crashes and continuous deployments, (B) weakens the overall routing to mere soft hints which shifts the burden to our services.

I skimmed through the [filter](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_proc/ext_proc.cc) and wondered about the complexity of contributing support for retries.

I found the following related issues, some of which were just closed by the stalebot (ext_authz should be conceptually quite close):
- https://github.com/envoyproxy/envoy/issues/5974
- https://github.com/envoyproxy/envoy/issues/17918
- https://github.com/envoyproxy/envoy/issues/25751
- https://github.com/envoyproxy/envoy/issues/23301
- https://github.com/envoyproxy/envoy/issues/9396

So I am wondering, are there any stronger opinions on how this should be done?
1. Contributing general retry policies for upstream clusters sounds like an endeavour that would bleed into many more places than just the ext_proc filter, probably raising enough architectural questions that this should better be done by the core contributors?
2. I saw that [config.core.v3.GrpcService.EnvoyGrpc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice) actually already contains a **retry_policy** property, but the documentation states that this is currently only used for xDS gRPC streams. Could we maybe just teach the ext_proc filter to use this retry_policy defined there?

I'd appreciate any feedback on the feasibility here and we'd love to help if we can.

**Comment by nahk-ivanov** [comment]
Given that `ext_proc` is using gRPC streaming, I'm wondering, if per-cluster retries will help, given https://github.com/envoyproxy/envoy/issues/3594#issuecomment-401206136

**Comment by ggreenway** [comment]
This was added in #32241
