### ISSUE TITLE
Envoy rejecting OPTIONS request with ":path" set to "*" (asterisk)

### ISSUE THREAD

**Issue by pradpras** [envoyproxy/envoy#28481]
***Title*: *Envoy rejecting OPTIONS request with ":path" set to "\*" (asterisk)***

*Description*: 
Request format
>     :method: OPTIONS
>     :path: *
>     :scheme: http

Envoy debug logs indicates that the request is rejected.

> [2023-07-19 10:54:16.569][1102][debug][http] [source/common/http/filter_manager.cc:996] [C18][S6397826585462938420] Sending local reply with details **absolute_path_rejected**

Envoy source code indicates that only relative paths are supported. So it expects the first character of the ":path" pseudo-header to be "/"
https://github.com/envoyproxy/envoy/blob/v1.26.2/source/common/http/conn_manager_impl.cc#L1155C6-L1155C23

Why is it so?

**Comment by lizan** [comment]
While that part of code is to reject absolute path, the OPTIONS request with `*` path is not absolute path. But we don't support it either. What do you expect Envoy to respond to that request?

**Comment by pradpras** [comment]
We are no expecting envoy to respond to the request locally. We are looking proxying OPTIONS request via envoyproxy to the destination.
