### ISSUE TITLE
Question: How to avoid Ext Authz flow for request with Authorization header

### ISSUE THREAD

**Issue by maragunde93** [envoyproxy/envoy#28486]
*Title*: How to avoid Ext Authz flow for request with Authorization header

*Description*:
I am using envoy proxy v1.21.0 within Istio.

I want to route requests that don't have the 'Authorization' header to a specific authentication flow (using [Ext Authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto)), and avoid the flow for requests that contain an 'Authorization' header (the header validity will be checked later with Istio)

I have the Ext Authz flow already working, and I have added a Composite filter to detect if the Authorization header is there or not, this is kind of working:
![image](https://github.com/envoyproxy/envoy/assets/74361193/c692095a-b0cc-434b-b3c6-a48a5bde6ab2)

The issue is that as you can see in the image I am using an `exact_match_map` to comparte with 'ey', which of course won't work. I have tried to use the `prefix_match_map` which would make this work but when I do that the application throws an error:

![image](https://github.com/envoyproxy/envoy/assets/74361193/5322d30e-6c33-40d6-a2b3-6c2cccfb8b13)
![image](https://github.com/envoyproxy/envoy/assets/74361193/54f2ee83-7d31-4396-aedc-2d3d2dca4084)

I check in the envoy docs and that matcher seems to be available for v1.21.0.

I also tried to use the `custom_match` but couldn't find much documentation on how to use it for this case.

My questions are:
1. Why I am getting this error when using the `prefix_match_map`
2. Is there a way I can achieve this with the `custom_match` (any docs or code would greatly help)
3. Is there a more efficient way to do this?

Thanks!

**Comment by lizan** [comment]
For 3, consider use [per route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthzperroute) configuration to disable for a routes?

**Comment by maragunde93** [comment]
Thanks for the response. I was able to make this work by **checking the Authorization header in a LUA inline script in envoy_on_request, and then setting a custom header if the Authorization header wasn't sent**. 

```LUA
if headers:get("Authorization") == nil then
  request_handle:headers():add("x-oidc-flow", "true")
end
```


It is important to put in the correct order the HTTP_FILTERS since my LUA script was being executed after the composite action at the start.

The composite filter checks is similar of what I sent before, like:

```yaml
xds_matcher:
  matcher_tree:
    input:
      name: request-headers
      typed_config:
        .............
       header_name: x-oidc-flow   # custom header set with LUA script
   exact_match_map:
     map:
       "true":
           # redirect with  ExtAuthz
```
