### ISSUE TITLE
SipTraTest.TraCompleteRetrieveRsp is flaky

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#28524]
https://dev.azure.com/cncf/envoy/_build/results?buildId=143509&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc&l=4353

@durd07 @nearbyfly @dorisd0102

**Comment by durd07** [comment]
I will check it now.

**Comment by durd07** [comment]
@lizan please help to close this issue as it has been solved.
Thanks.
