### ISSUE TITLE
upstream connect error or disconnect/reset before headers service unavailable

### ISSUE THREAD

**Issue by lps0535** [envoyproxy/envoy#2853]
*Description*:
>I've just started exploring Envoy but I am stuck in "Getting Started" with Envoy.
https://www.envoyproxy.io/docs/envoy/latest/start/start 

I downloaded the Dockerfile and google_com_proxy.v2.yaml in the same folder and after that I ran 
these 3 commands: 
$ docker build -t envoy-google-test:v1 .
$ docker run -d -p 10000:10000 envoy-google-test:v1
$ curl -v localhost:10000

Now when I run curl command I get this error "upstream connect error or disconnect/reset before headers service unavailable". Envoy should redirect to google but I'm getting the above error.
Few days back when I tried it was running, don't know what I'm doing wrong.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
cluster.service_google.bind_errors: 0
cluster.service_google.external.upstream_rq_503: 3
cluster.service_google.external.upstream_rq_5xx: 3
cluster.service_google.lb_healthy_panic: 0
cluster.service_google.lb_local_cluster_not_ok: 0
cluster.service_google.lb_recalculate_zone_structures: 0
cluster.service_google.lb_subsets_active: 0
cluster.service_google.lb_subsets_created: 0
cluster.service_google.lb_subsets_fallback: 0
cluster.service_google.lb_subsets_removed: 0
cluster.service_google.lb_subsets_selected: 0
cluster.service_google.lb_zone_cluster_too_small: 0
cluster.service_google.lb_zone_no_capacity_left: 0
cluster.service_google.lb_zone_number_differs: 0
cluster.service_google.lb_zone_routing_all_directly: 0
cluster.service_google.lb_zone_routing_cross_zone: 0
cluster.service_google.lb_zone_routing_sampled: 0
cluster.service_google.max_host_weight: 0
cluster.service_google.membership_change: 1
cluster.service_google.membership_healthy: 1
cluster.service_google.membership_total: 1
cluster.service_google.retry_or_shadow_abandoned: 0
cluster.service_google.ssl.connection_error: 0
cluster.service_google.ssl.fail_no_sni_match: 0
cluster.service_google.ssl.fail_verify_cert_hash: 0
cluster.service_google.ssl.fail_verify_error: 0
cluster.service_google.ssl.fail_verify_no_cert: 0
cluster.service_google.ssl.fail_verify_san: 0
cluster.service_google.ssl.handshake: 0
cluster.service_google.ssl.no_certificate: 0
cluster.service_google.ssl.session_reused: 0
cluster.service_google.update_attempt: 28
cluster.service_google.update_empty: 0
cluster.service_google.update_failure: 0
cluster.service_google.update_success: 28
cluster.service_google.upstream_cx_active: 0
cluster.service_google.upstream_cx_close_notify: 0
cluster.service_google.upstream_cx_connect_attempts_exceeded: 0
cluster.service_google.upstream_cx_connect_fail: 3
cluster.service_google.upstream_cx_connect_timeout: 0
cluster.service_google.upstream_cx_destroy: 0
cluster.service_google.upstream_cx_destroy_local: 0
cluster.service_google.upstream_cx_destroy_local_with_active_rq: 0
cluster.service_google.upstream_cx_destroy_remote: 0
cluster.service_google.upstream_cx_destroy_remote_with_active_rq: 0
cluster.service_google.upstream_cx_destroy_with_active_rq: 0
cluster.service_google.upstream_cx_http1_total: 3
cluster.service_google.upstream_cx_http2_total: 0
cluster.service_google.upstream_cx_max_requests: 0
cluster.service_google.upstream_cx_none_healthy: 0
cluster.service_google.upstream_cx_overflow: 0
cluster.service_google.upstream_cx_protocol_error: 0
cluster.service_google.upstream_cx_rx_bytes_buffered: 0
cluster.service_google.upstream_cx_rx_bytes_total: 0
cluster.service_google.upstream_cx_total: 3
cluster.service_google.upstream_cx_tx_bytes_buffered: 0
cluster.service_google.upstream_cx_tx_bytes_total: 0
cluster.service_google.upstream_flow_control_backed_up_total: 0
cluster.service_google.upstream_flow_control_drained_total: 0
cluster.service_google.upstream_flow_control_paused_reading_total: 0
cluster.service_google.upstream_flow_control_resumed_reading_total: 0
cluster.service_google.upstream_rq_503: 3
cluster.service_google.upstream_rq_5xx: 3
cluster.service_google.upstream_rq_active: 0
cluster.service_google.upstream_rq_cancelled: 0
cluster.service_google.upstream_rq_maintenance_mode: 0
cluster.service_google.upstream_rq_pending_active: 0
cluster.service_google.upstream_rq_pending_failure_eject: 3
cluster.service_google.upstream_rq_pending_overflow: 0
cluster.service_google.upstream_rq_pending_total: 3
cluster.service_google.upstream_rq_per_try_timeout: 0
cluster.service_google.upstream_rq_retry: 0
cluster.service_google.upstream_rq_retry_overflow: 0
cluster.service_google.upstream_rq_retry_success: 0
cluster.service_google.upstream_rq_rx_reset: 0
cluster.service_google.upstream_rq_timeout: 0
cluster.service_google.upstream_rq_total: 0
cluster.service_google.upstream_rq_tx_reset: 0
cluster.service_google.version: 0
cluster_manager.active_clusters: 1
cluster_manager.cluster_added: 1
cluster_manager.cluster_modified: 0
cluster_manager.cluster_removed: 0
cluster_manager.warming_clusters: 0
filesystem.flushed_by_timer: 0
filesystem.reopen_failed: 0
filesystem.write_buffered: 1
filesystem.write_completed: 1
filesystem.write_total_buffered: 0
http.admin.downstream_cx_active: 2
http.admin.downstream_cx_destroy: 0
http.admin.downstream_cx_destroy_active_rq: 0
http.admin.downstream_cx_destroy_local: 0
http.admin.downstream_cx_destroy_local_active_rq: 0
http.admin.downstream_cx_destroy_remote: 0
http.admin.downstream_cx_destroy_remote_active_rq: 0
http.admin.downstream_cx_drain_close: 0
http.admin.downstream_cx_http1_active: 1
http.admin.downstream_cx_http1_total: 1
http.admin.downstream_cx_http2_active: 0
http.admin.downstream_cx_http2_total: 0
http.admin.downstream_cx_idle_timeout: 0
http.admin.downstream_cx_protocol_error: 0
http.admin.downstream_cx_rx_bytes_buffered: 431
http.admin.downstream_cx_rx_bytes_total: 819
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.admin.downstream_cx_total: 2
http.admin.downstream_cx_tx_bytes_buffered: 0
http.admin.downstream_cx_tx_bytes_total: 4385
http.admin.downstream_cx_websocket_active: 0
http.admin.downstream_cx_websocket_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
http.admin.downstream_rq_1xx: 0
http.admin.downstream_rq_2xx: 1
http.admin.downstream_rq_3xx: 0
http.admin.downstream_rq_4xx: 0
http.admin.downstream_rq_5xx: 0
http.admin.downstream_rq_active: 1
http.admin.downstream_rq_http1_total: 2
http.admin.downstream_rq_http2_total: 0
http.admin.downstream_rq_non_relative_path: 0
http.admin.downstream_rq_response_before_rq_complete: 0
http.admin.downstream_rq_rx_reset: 0
http.admin.downstream_rq_too_large: 0
http.admin.downstream_rq_total: 2
http.admin.downstream_rq_tx_reset: 0
http.admin.downstream_rq_ws_on_non_ws_route: 0
http.admin.rs_too_large: 0
http.admin.tracing.tracing.client_enabled: 0
http.admin.tracing.tracing.health_check: 0
http.admin.tracing.tracing.not_traceable: 0
http.admin.tracing.tracing.random_sampling: 0
http.admin.tracing.tracing.service_forced: 0
http.async-client.no_cluster: 0
http.async-client.no_route: 0
http.async-client.rq_direct_response: 0
http.async-client.rq_redirect: 0
http.async-client.rq_total: 0
http.ingress_http.downstream_cx_active: 1
http.ingress_http.downstream_cx_destroy: 2
http.ingress_http.downstream_cx_destroy_active_rq: 0
http.ingress_http.downstream_cx_destroy_local: 0
http.ingress_http.downstream_cx_destroy_local_active_rq: 0
http.ingress_http.downstream_cx_destroy_remote: 2
http.ingress_http.downstream_cx_destroy_remote_active_rq: 0
http.ingress_http.downstream_cx_drain_close: 0
http.ingress_http.downstream_cx_http1_active: 1
http.ingress_http.downstream_cx_http1_total: 2
http.ingress_http.downstream_cx_http2_active: 0
http.ingress_http.downstream_cx_http2_total: 0
http.ingress_http.downstream_cx_idle_timeout: 0
http.ingress_http.downstream_cx_protocol_error: 0
http.ingress_http.downstream_cx_rx_bytes_buffered: 363
http.ingress_http.downstream_cx_rx_bytes_total: 831
http.ingress_http.downstream_cx_ssl_active: 0
http.ingress_http.downstream_cx_ssl_total: 0
http.ingress_http.downstream_cx_total: 3
http.ingress_http.downstream_cx_tx_bytes_buffered: 0
http.ingress_http.downstream_cx_tx_bytes_total: 573
http.ingress_http.downstream_cx_websocket_active: 0
http.ingress_http.downstream_cx_websocket_total: 0
http.ingress_http.downstream_flow_control_paused_reading_total: 0
http.ingress_http.downstream_flow_control_resumed_reading_total: 0
http.ingress_http.downstream_rq_1xx: 0
http.ingress_http.downstream_rq_2xx: 0
http.ingress_http.downstream_rq_3xx: 0
http.ingress_http.downstream_rq_4xx: 0
http.ingress_http.downstream_rq_5xx: 3
http.ingress_http.downstream_rq_active: 0
http.ingress_http.downstream_rq_http1_total: 3
http.ingress_http.downstream_rq_http2_total: 0
http.ingress_http.downstream_rq_non_relative_path: 0
http.ingress_http.downstream_rq_response_before_rq_complete: 0
http.ingress_http.downstream_rq_rx_reset: 0
http.ingress_http.downstream_rq_too_large: 0
http.ingress_http.downstream_rq_total: 3
http.ingress_http.downstream_rq_tx_reset: 0
http.ingress_http.downstream_rq_ws_on_non_ws_route: 0
http.ingress_http.no_cluster: 0
http.ingress_http.no_route: 0
http.ingress_http.rq_direct_response: 0
http.ingress_http.rq_redirect: 0
http.ingress_http.rq_total: 3
http.ingress_http.rs_too_large: 0
http.ingress_http.tracing.client_enabled: 0
http.ingress_http.tracing.health_check: 0
http.ingress_http.tracing.not_traceable: 0
http.ingress_http.tracing.random_sampling: 0
http.ingress_http.tracing.service_forced: 0
listener.0.0.0.0_10000.downstream_cx_active: 1
listener.0.0.0.0_10000.downstream_cx_destroy: 2
listener.0.0.0.0_10000.downstream_cx_total: 3
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_1xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_2xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_3xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_4xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_5xx: 3
listener.admin.downstream_cx_active: 2
listener.admin.downstream_cx_destroy: 0
listener.admin.downstream_cx_total: 2
listener.admin.http.admin.downstream_rq_1xx: 0
listener.admin.http.admin.downstream_rq_2xx: 1
listener.admin.http.admin.downstream_rq_3xx: 0
listener.admin.http.admin.downstream_rq_4xx: 0
listener.admin.http.admin.downstream_rq_5xx: 0
listener_manager.listener_added: 1
listener_manager.listener_create_failure: 0
listener_manager.listener_create_success: 4
listener_manager.listener_modified: 0
listener_manager.listener_removed: 0
listener_manager.total_listeners_active: 1
listener_manager.total_listeners_draining: 0
listener_manager.total_listeners_warming: 0
server.days_until_first_cert_expiring: 2147483647
server.live: 1
server.memory_allocated: 3191144
server.memory_heap_size: 4194304
server.parent_connections: 0
server.total_connections: 2
server.uptime: 135
server.version: 14290373
server.watchdog_mega_miss: 5
server.watchdog_miss: 5
stats.overflow: 0

*Config*:
>Include the config used to configure 
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite: www.google.com, cluster: service_google }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }

**Comment by lps0535** [comment]
I put in clusters:
dns_lookup_family: V4_ONLY
and it worked.

**Comment by mattklein123** [comment]
Hmm, I guess that is still required in some cases. I will revert.

**Comment by lps0535** [comment]
Hi @mattklein123 
I'm unable to figure out what's the issue, but this error pops out sometimes and sometimes it doesn't.

**Error: "upstream connect error or disconnect/reset before headers"**

What's the problem in this config file?

**Config File**:
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 3000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/" }
                route: { prefix_rewrite: "/", cluster: serviceA }
          http_filters:       
          - name: envoy.grpc_json_transcoder
            config:
                proto_descriptor: "/etc/proto.pb"
                services: ["Errors"]
                print_options:
                    add_whitespace: false
                    always_print_primitive_fields: true
                    always_print_enums_as_ints: false
                    preserve_proto_field_names: false
          - name: envoy.router
            config: {}
                           
          
  clusters:
  - name: serviceA
    connect_timeout: 1.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 10.104.3.32
        port_value: 50054
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902

**Error**: "upstream connect error or disconnect/reset before headers"

I've run the envoy using the same config "N" times and out of N times it works for N/3 times and fails for rest. Why is it so ?

I've tried adding the following as mentioned in other threads but it's not helping. Is there some permanent workaround to this?

dns_lookup_family: V4_ONLY
max_requests_per_connection: 1



**Response Header:** 
content-length →57
content-type →text/plain
date →Wed, 21 Mar 2018 19:45:57 GMT
server →envoy
503 Service Unavailable


Help Really Appreciated.
Thanks
