### ISSUE TITLE
Proto format tools cannot handle .proto files relocation [CI]

### ISSUE THREAD

**Issue by nishikinocurtis** [envoyproxy/envoy#28549]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Proto format tools cannot handle .proto files relocation*

*Description*:
I am making a relocation of a customized .proto file under api/envoy/config. But the proto_format.sh fix failed at the second  last task (fetch_normalized_api_changes), reporting:

```bash
ERROR: /home/qiutong/envoy/tools/proto_format/BUILD:148:8: Executing genrule //tools/proto_format:normalized_api_changes failed: (Exit 1): bash failed: error executing command (from target //tools/proto_format:normalized_api_changes) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/home/qiutong/.cache/bazel/_bazel_qiutong/3e8cd0c39078090b29ea9ff643cee4b4/sandbox/linux-sandbox/5409/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/proto_format/fetch_normalized_changes.runfiles/envoy/tools/proto_format/fetch_normalized_changes.py", line 76, in <module>
    sync(
  File "/home/qiutong/.cache/bazel/_bazel_qiutong/3e8cd0c39078090b29ea9ff643cee4b4/sandbox/linux-sandbox/5409/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/proto_format/fetch_normalized_changes.runfiles/envoy/tools/proto_format/fetch_normalized_changes.py", line 35, in sync
    change, path = line.split()
ValueError: too many values to unpack (expected 2)
Target //tools/proto_format:proto_sync failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

I modified the fetch_normalized_changes.py to dump what is generated in line 35, and get:

```bash
['M', 'api/envoy/config/bootstrap/v3/BUILD']
['M', 'api/envoy/config/bootstrap/v3/bootstrap.proto']
['R', 'api/envoy/config/rerouting/rerouting.proto', '->', 'api/envoy/config/rerouting/v3/rerouting.proto']
```

It seems that the relocation would cause git to generate an R-type changelog, which cannot be handled by the script.

*Repro steps*:
Relocate any .proto file under `api/` and execute `tools/proto_format/proto_format.sh fix`.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
Not applicable

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by phlax** [comment]
@nishikinocurtis this script doesnt work optimally - it kinda works "good enough" for our CI

a related issue is that if you add a proto file but dont hook it up correctly, it removes the file rather than fixing the BUILD config - which can be surprising/unhelpful if you dont expect that

i would be open to reviewing any PRs to improve this tooling, otherwise it will probably have to wait a while before it gets attention

**Comment by nishikinocurtis** [comment]
@phlax Thank you for replying.

I am working on this issue, but I was wondering how to write test for my added code since it is not a brand-new tool as is in the procedure described in tools/README.md.

**Comment by phlax** [comment]
in terms of python, most of the tooling involved has moved to https://github.com/envoyproxy/toolshed which is pretty well tested

the code remaining here is not as well tested (or at all), and is mostly waiting to be moved
