### ISSUE TITLE
postgres: statements are not parsed when using upstream SSL (with plain downstream)

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#28548]
#23990 added support for doing Envoy to upstream encryption (when downstream is plain), however after encryption is enabled on the upstream we never move back to `InSyncState` so command parsing doesn't happen. I think it should happen here:

https://github.com/envoyproxy/envoy/blob/main/contrib/postgres_proxy/filters/network/source/postgres_filter.cc#L261

after `startUpstreamSecureTransport()` succeeds. 

cc: @cpakulski

**Comment by cpakulski** [comment]
Hmm, I remember doing lots of manual testing with upstream starttls and observing traffic but maybe I missed something. Let me check.

**Comment by rgs1** [comment]
Oh, traffic flows just fine -- it works great doing the upstream encryption 👌 . However, no stats are generated due to the lack of statement parsing (possibly because of the missed state transition I referenced before), plus the integration test doesn't check statements stats either fwiw.

**Comment by rgs1** [comment]
Tangentially related #28553.
