### ISSUE TITLE
Windows ltsc2022 docker image does not have powershell

### ISSUE THREAD

**Issue by etinquis** [envoyproxy/envoy#28544]
*Title*: Windows ltsc2022 docker image does not have powershell

*Description*:
I have my own dockerfile that's based on either the regular envoy-windows or envoy-windows-ltsc2022 based on environment.  When using the ltsc2022 image, powershell commands don't work.

*Repro steps*:
This works [envoyproxy/envoy-windows:v1.26.3]:
```
docker run --rm -it --entrypoint powershell envoyproxy/envoy-windows:v1.26.3
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\>
```
This works [mcr.microsoft.com/windows/servercore:ltsc2022]:
```
docker run --rm -it --entrypoint powershell mcr.microsoft.com/windows/servercore:ltsc2022
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\>
```
This does not work [envoyproxy/envoy-windows-ltsc2022:v1.26.3]:
```
docker run --rm -it --entrypoint powershell envoyproxy/envoy-windows-ltsc2022:v1.26.3
docker: Error response from daemon: container ad142bf57f45d069a08f88e562744d8601d35436352bc507a65211f4829b8d9d encountered an error during hcs::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2).
```

Is there a reason that powershell would be missing in ltsc2022?

**Comment by etinquis** [comment]
Looks like it might be a messed up PATH

```
docker run --rm -it --entrypoint cmd envoyproxy/envoy-windows:v1.26.3

Microsoft Windows [Version 10.0.17763.4499]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>where powershell
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
C:\>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\
OpenSSH\;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;c:\Program Files\envoy;
```

```
docker run --rm -it --entrypoint cmd envoyproxy/envoy-windows-ltsc2022:v1.26.3

Microsoft Windows [Version 10.0.20348.1787]
(c) Microsoft Corporation. All rights reserved.

C:\>where powershell
'where' is not recognized as an internal or external command,
operable program or batch file.
C:\>echo %PATH%
C:\Windows\system32;C:\Windows;;c:\Program Files\envoy
```

**Comment by phlax** [comment]
> Why is that?

size - iirc even the nanoserver is unexpectedly large or a container image

**Comment by etinquis** [comment]
I guess my question is more why aren't they consistent.

**Comment by phlax** [comment]
cc @davinci26 @wrowe

**Comment by davinci26** [comment]
afaik this is a question for the Microsoft folks. I am not affiliated with Microsoft so take my answer with a grain of salt. Nanoserver was the blessed image due to the size (it is order of magnitudes less) to use for Envoy.

**Comment by davinci26** [comment]
You might be able to install PowerShellCore in your Nanoserver container

**Comment by etinquis** [comment]
@davinci26 The base images are different between `envoyproxy/envoy-windows` (servercore) and `envoyproxy/envoy-windows-ltsc2022` (nanoserver).  I currently have one dockerfile that was meant to swap between envoy images based on platform, but I wasn't expecting so much of a difference between ltsc2019 and ltsc2022 as to be different base windows server images.  That difference likely means that I either have to build the envoy images from the repo myself to make them consistent, or write a set of setup scripts for each and figure out which I'm running on while building my image.

What I'm getting at is that the current setup assumes that users aren't making the same assumption that I am, that envoyproxy/envoy-windows and envoyproxy/envoy-windows-ltsc2022 are compatible base images for their own images.

**Comment by phlax** [comment]
@etinquis as a short term workaround perhaps we can rename the nano image to something with nano in the name

not sure re supporting only one type of image, i guess there is a reason, we defo dont want to add any more

**Comment by phlax** [comment]
related #28588
