### ISSUE TITLE
Gzip filter compresses content when Accept-Encoding header is not present in request

### ISSUE THREAD

**Issue by joshuarubin** [envoyproxy/envoy#2855]
It looks like this is intended behavior as it is tested. However, the [documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/gzip_filter.html#config-http-filters-gzip) states:
> By default compression will be skipped when:
> 
> A request does NOT contain accept-encoding header.

https://github.com/envoyproxy/envoy/blob/a36fc3e8f2d64b86dbd2103f9143ac3515c16fba/source/common/http/filter/gzip_filter.cc#L193

https://github.com/envoyproxy/envoy/blob/a5550892f40cb8a3eb17477967ac27cbf63a61ba/test/common/http/filter/gzip_filter_test.cc#L195

**Comment by danielhochman** [comment]
cc @gsagula

**Comment by yudiandreanp** [comment]
It happened on our deployment environment. We expected no compression without the header, but envoy still compressed it.
I thinks it's a bug.

https://tools.ietf.org/html/rfc2616#page-103
The RFC also says that the proxy should use any encoding if no Accept-Encoding header specified:

> If no Accept-Encoding field is present in a request, the server MAY
>    assume that the client will accept any content coding. In this case,
>    if "identity" is one of the available content-codings, then the
>    server SHOULD use the "identity" content-coding, unless it has
>    additional information that a different content-coding is meaningful
>    to the client.

**Comment by gsagula** [comment]
@yudiandreanp @joshuarubin The filter should not compress the content when no Accept-Encoding is present. I'll work on the fix.

Thanks for reporting the issue.
