### ISSUE TITLE
Full text for RESPONSE_FLAGS in access logs

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#28572]
The ``%RESPONSE_FLAGS%`` access log flag will output additional information in values which may not be understood (most of them) unless [referring to the docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage). This feature request is for additional flag ``%RESPONSE_FLAGS_FULL%`` that would support the same flags, but will full text description in pascal case. For example, ``UH`` would map to ``UnhealthyUpstream``.

**Comment by mattklein123** [comment]
Sure sounds good.
