### ISSUE TITLE
Huge latency spike for more number of requests with payload sizes. [ext_proc filter]

### ISSUE THREAD

**Issue by shibin-aot** [envoyproxy/envoy#28593]
*Latency Spike for high RPM*

I developed a ext_proc filter to add some extra processing for request and response headers and data.
But, while testing it with payloads and high RPM i noticed a sudden spike in the latency.
The latency is so high that the production deployment is impossible with the ext_proc code at this point.

I researched and understood that currently the requests and responses are send in a synchronous mode, which is causing the spike in latency. I have seen there are feature requests raised previously. But, can anyone suggest me a way. If async is the only option, when does the development completes?

**Comment by tyxia** [comment]
@shibin-aot 
async mode development is completed, it is rename to observability_mode though https://github.com/envoyproxy/envoy/blob/b5bc27399d723806bab993895e64f9295c863016/api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto#L255
