### ISSUE TITLE
How to use envoy api in my own project?

### ISSUE THREAD

**Issue by swhoro** [envoyproxy/envoy#28612]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: How to use envoy api in my own project?

*Description*:
>For example, I want to develop a simple control plane(CPP project) which only serve a endpoint discovery service, then I need this file:
https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/endpoint/v3/eds.proto
Howerver, this file depends on `google/api`, `udpa`, `validate` and others. If I compile all these `*.proto` to `*.cc *.h` and later compile all these `*.cc` to `*.o` and link them, it may take a very long time.
So I want to ask is there a simpler way to achive this?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
it's a bit weird to develop a control plane by the CPP because typically we never expect extream performance on the control plane.

But if you still want it, you may could use bazel in your project and add the envoy into your dependency list. Then you can import the eds lib by `@envoy_api//envoy/service/endpoint/v3:pkg_cc_proto`. The bazel will ensure only the necessary part to be compiled.

**Comment by swhoro** [comment]
> it's a bit weird to develop a control plane by the CPP because typically we never expect extream performance on the control plane.
> 
> But if you still want it, you may could use bazel in your project and add the envoy into your dependency list. Then you can import the eds lib by `@envoy_api//envoy/service/endpoint/v3:pkg_cc_proto`. The bazel will ensure only the necessary part to be compiled.

thank you
 In fact, I only used cmake before, so I am not familiar with bazel.
Besides, if I want to use it in a golang project, should I use bazel too?

**Comment by wbpcode** [comment]
If golang is used, please use our pre-compiled https://github.com/envoyproxy/go-control-plane directly.

**Comment by swhoro** [comment]
> If golang is used, please use our pre-compiled https://github.com/envoyproxy/go-control-plane directly. And go mod could be used.

thank you
