### ISSUE TITLE
PostgreSQL-aware filter

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#2861]
Probably we can add a PostgreSQL-aware filter? Especially on handling the conn pooling (the infamous "FATAL:  remaining connection slots are reserved for non-replication superuser connections" often happens when client tries to pool the conn inside the client directly).

Similar with:
- [pgpool](http://www.pgpool.net/docs/latest/en/html/intro-whatis.html)
- [crunchy-proxy](https://github.com/CrunchyData/crunchy-proxy)
- [pgbouncer](https://pgbouncer.github.io/) + [query-routing](https://aws.amazon.com/blogs/big-data/query-routing-and-rewrite-introducing-pgbouncer-rr-for-amazon-redshift-and-postgresql/)

**Comment by zuercher** [comment]
It's certainly possible to implement a PostgreSQL filter. Let's use this ticket to put together a set of features you'd like to see and to gauge interest.

**Comment by dio** [comment]
I'd like to see what `crunchy-proxy` has, the most wanted perhaps these two:

- ability to route messages based on the SQL command type - writes are sent to a master and reads are sent to replicas in a round-robin fashion
- connection pooling

**Comment by mdamt** [comment]
* routed queries
* weighted reads

**Comment by F21** [comment]
I would love to see support for SSL (Postgres calls it SSL instead of TLS), so that operators of PostgreSQL do not need to maange and rotate the TLS certificates.

**Comment by loewenstein** [comment]
@f21 so in that case the client would be just any postgres client doing SSL, i.e. no client side proxy? With sidecar this wouldn't be postgres specific, would it? I.e. plain text to proxy, TLS between proxies and then plain text again to postgres (or any other) server.

**Comment by dio** [comment]
I have started a very early design doc here: https://docs.google.com/document/d/15iXAIJN1QFV3Dz86yybyqhgEMpY7wae2bZeKPyFZG5Y

**Comment by F21** [comment]
@loewenstein At the moment, I am just interested in having TLS between proxies, because automating certificates issuance and rotation for database services in Kubernetes is not an easy problem to solve. I was not able to find anything in the envoy or istio docs, but does istio's TLS still work if the layer 7 protocol does not currently have a filter (ex: postgres protocol or mysql protocol).

@dio Will the design work with distributed DBs that uses the postgres or mysql protocols, but are clustered and distributed themselves? For example CockroachDB using the postgres protocol and TiDB using the mysql protocol.

**Comment by dio** [comment]
@F21 hopefully those systems could benefit from having a proxy in front of it, while query-routing probably is not a concern, but things like: stats, connection-pooling and query-rewriting might give plus points. If you have comments, inputs or anything please let me know will be very appreciated. Thanks!

**Comment by blaggacao** [comment]
This proposal feels like putting wings on coelacanthiforms! Very very nice!

**Comment by sjvanrossum** [comment]
Working on it. The experimental extension mentioned above was scrapped and what I'm writing for the PR is a connection manager, like HttpConnectionManager and ThriftProxy, with a filter chain to leave room for extension (enabling us to address design goal 7 in the doc as a sub-extension).
Expect the base of that (MVP as suggested by Matt Turner) to be opened as a PR within the next two weeks. ;)

I took a peak under the hood at TCP and HTTP connection pooling, but haven't come up with a solid plan for implementation yet.

**Comment by codervinod** [comment]
Have we made any progress on this FR? I am planning to work on this as we need it for my current project. If someone has started work, please reach out so that we can collaborate.

**Comment by sjvanrossum** [comment]
Yep, I'm implementing this. I had planned to wrap up the PR two weeks back, but got caught up in my day to day.

@hagmonk that syntax is a neat way to hint or specify envoy specific connection properties.
@dio do we have any solid requirements for specifying envoy connection properties? Seeing as we can stuff them in different places, we could allow various implementations of routers to exist.

**Comment by hagmonk** [comment]
@sjvanrossum is there a repo containing your work so far that some of us can poke at? I'm sure whatever state it's in, we have enough interested parties here to provide some feedback :)

**Comment by dio** [comment]
@sjvanrossum I'm afraid we don't have it yet. Think we can specify.

**Comment by rshriram** [comment]
if you repurpose the mysQL filter, you could stuff this retry info in the SQL comments and do the appropriate thing in the SQL filter.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/issues/9107 for a stats only filter proposal. I would suggest we start there and then extend with other features as resources become available.

**Comment by mattklein123** [comment]
Given that we landed initial support in https://github.com/envoyproxy/envoy/pull/10642 I think it makes sense to close this and we should open individual issues for discrete future features. Awesome work everyone! cc @cpakulski
