### ISSUE TITLE
Can new request in old connections  see the new http filter chain？

### ISSUE THREAD

**Issue by Eiji911** [envoyproxy/envoy#28656]
Title: Can new request in old connections  see the new http filter chain？

Description:
If only http filter config  update via LDS，the connections owned by these destroying filter chains will be draineds. Before draining，can new request of the old connections see the new  http filter config？

**Comment by wbpcode** [comment]
I think the answer is nope.

**Comment by Eiji911** [comment]
For Http  Filter chain only update， when does envoy drain a old conenction？ 
In my test，Envoy will and 'conenction:close' header as  soon as an old connection recevied.
 it is not completely match what  said in 
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining#arch-overview-draining

![image](https://github.com/envoyproxy/envoy/assets/137666922/6b3c62ad-cab8-4978-9cd5-158f9aa1adfe)

**Comment by wbpcode** [comment]
After a quick check to the source code, the behavior for HTTP1.1 and HTTP2 is minor different.
For the HTTP1.1, envoy will add the `connection:close` immediately.

**Comment by Eiji911** [comment]
> After a quick check to the source code, the behavior for HTTP1.1 and HTTP2 is minor different. For the HTTP1.1, envoy will add the `connection:close` immediately.

so, when does an  old connection  close depends on the timing an  new request arrive or  after draing-timeout period.
