### ISSUE TITLE
difference or association between istio/proxy and envoyproxy/envoy?

### ISSUE THREAD

**Issue by ribribrib2** [envoyproxy/envoy#28676]
Who can answer this question? What is the difference or association between [istio/proxy](https://github.com/istio/proxy) and [envoyproxy/envoy](https://github.com/envoyproxy/envoy)? Thank you.

**Comment by j2gg0s** [comment]
istio uses a fork of envoy, add some filters.

see this: https://github.com/istio/proxy/blob/master/scripts/update_envoy.sh

**Comment by htuch** [comment]
Closing with https://github.com/envoyproxy/envoy/issues/28676#issuecomment-1655386950 as the answer.
