### ISSUE TITLE
envoy-1.27: unable to build envoy as root (was: bazel build -c opt envoy not working on release branch)

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#28670]
found similar issue #23065 back in 2022 was fixed, here the failing due to following code: https://github.com/envoyproxy/envoy/blob/3c0b60a5bb6394c237fb26e299298787b62b8097/bazel/repositories_extra.bzl#L17C10-L17C10

ps. obviously the same issue in main branch

**Comment by ohadvano** [comment]
cc @phlax

**Comment by phlax** [comment]
> found similar issue https://github.com/envoyproxy/envoy/issues/23065 back in 2022 was fixed

it wasnt fixed, we added a workaround temporarily to allow any downstreams to fix their builds

the workaround is still there (`ignore_root_user_error`) but is no longer the default

you can continue using the workaround by editing the `WORKSPACE` file, but the much better solution is to fix your build so as not to run as root inside the build container

**Comment by ohadvano** [comment]
> it wasnt fixed, we added a workaround temporarily to allow any downstreams to fix their builds

Would it be somehow possible to control that flag in a downstream build without modifying core Envoy?

**Comment by phlax** [comment]
> Would it be somehow possible to control that flag in a downstream build without modifying core Envoy?

as discussed offline - i dont think its possible to flip this switch without editing the `WORKSPACE` file, as it is a "repository" level settting, not a build flag. I may be wrong about this, but this is my understanding

**Comment by phlax** [comment]
this is (some of) the bazel docs related to repositories https://bazel.build/extending/repo

its possible that you could define `rules_python` using a custom rule, altho im not entirely clear how to do it

tbh tho this feels like a red herring when the source of the problem is obvious

**Comment by pgeler** [comment]
certainly help wanted

**Comment by phlax** [comment]
@pgeler what further help do you require?

i think this ticket should close - the real solution is _not running as root_ but the workaround is described otherwise

**Comment by pgeler** [comment]
I don't see a solution, my understanding, enforcement of root, in the envoy build script exactly preventing overriding it from custom rules. So for now we just patching the root enforcement, but it would be better if envoy can provide a custom flag which we can pass to bazel at envoy build time.

**Comment by phlax** [comment]
> I don't see a solution, my understanding, enforcement of root, in the envoy build script exactly preventing overriding it from custom 

this is not enforced by envoy - its enforced by `rules_python`

> So for now we just patching the root enforcement, but it would be better if envoy can provide a custom flag which we can pass to bazel at envoy build time.

there is not a simple flag that can be passed at build time afaiaa - but happy to be proven wrong (i posted links above for anyone interested in figuring that out)

enabling this - ie working around the enforcement by `rules_python` is not a priority - as much as it may not be the responsibility of `rules_python` to enforce this, _running as root is a bad idea_

**Comment by pgeler** [comment]
my understanding of `ignore_root_user_error = False` is exact enforcement. Unfortunately I'm not a bazel expert either, but it should be a better way of doing such configs, could be something like this https://github.com/bazelbuild/rules_python/releases and one of the recent patches https://github.com/bazelbuild/rules_python/pull/1114/files 🤔

**Comment by phlax** [comment]
> my understanding of ignore_root_user_error = False is exact enforcement. 

that is the default - and one we are ~happy to go with

changing this in your `WORKSPACE` is trivial

>  it should be a better way of doing such configs, could be something like this https://github.com/bazelbuild/rules_python/releases and one of the recent patches https://github.com/bazelbuild/rules_python/pull/1114/files 🤔

its not immediately clear what this does

checking here tho - nothing is jumping out that suggests configurability 

https://github.com/search?q=repo%3Abazelbuild%2Frules_python%20ignore_root_user_error&type=code

at the end of the day, i wonder why so much energy is put into trying to workaround this - why not just fix your build so you dont need to use `root` - this is also generally pretty trivial

**Comment by pgeler** [comment]
> enabling this - ie working around the enforcement by `rules_python` is not a priority - as much as it may not be the responsibility of `rules_python` to enforce this, _running as root is a bad idea_

there are multiple reasons why it's simpler for us to do this, and from security perspective we are using multistage builds, so I guess the vote here to give flexibility... and I appreciate everybody time, that is why I would keep it open with `help wanted`, so that I believe solution for the people with good bazel knowledge should be simpler than the discussion here ;)

**Comment by phlax** [comment]
how about raising an  issue upstream - to either ask if/how to configure this as a build option, or if not currently possible then whether it could be added

i dont see anything actionable from an Envoy pov

i made my thoughts clear upstream when this change was introduced, but at the end of the day - its not something i want to fight against or even workaround

**Comment by phlax** [comment]
i would definitely be happy to review a PR if you want to raise on that would make this configurable

**Comment by zengyuxing007** [comment]
> ok, as a workaround it's possible for us to use custom WORKFLOW and pass an argument registration of the extensions:
> 
> ```
> ...
> load("@envoy//bazel:repositories_extra.bzl", "envoy_dependencies_extra")
> 
> envoy_dependencies_extra(ignore_root_user_error = True)
> ...
> ```
> 
> this solution is working for our use case where custom WORKFLOW is defined.
> 
> however, to make it beneficial for original WORKFLOW use-cases it would be interesting to see if it's possible to define args on the main WORKFLOW and pass it as something like(seem more question for bazel capabilities and if envoy want such flag exposed):
> 
> ```
> ...
> load("@envoy//bazel:repositories_extra.bzl", "envoy_dependencies_extra")
> 
> envoy_dependencies_extra(ignore_root_user_error = args.ignore_root_user_error)
> ...
> ```

This works, it seems like it's also added by default under mobile/WORKSPACE.
