### ISSUE TITLE
Multi-threaded health checks

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#28699]
*Title*: *Multithreaded health checks*

*Description*:
Currently Envoy's health checks are all performed on the main thread (wonderfully explained in [this blog post](https://blog.envoyproxy.io/envoy-threading-model-a8d44b922310)). This seems to be one of the main scalability bottlenecks of a single Envoy proxy that we encounter at Block. Worker threads scale very well to increasing thread counts but there is no way to scale threads out for health checks. We've observed that beyond a certain active health checking load, the main thread can become too busy and health checks will artificially time out, resulting in Envoy considering all endpoints to be unhealthy. Envoy often can't recover on its own from this state. For rough numbers we see issues around 20k endpoints and a 5 second health check interval in our simulations (there are probably many other variables that affect this number).

While there are ways around this problem (e.g. reducing number of endpoints being health checked, increasing health check intervals, delivering health status via xDS), offering a way to scale health checks to more threads would be a great out-of-the-box solution for making a single envoy proxy scale to more endpoints.

**Comment by htuch** [comment]
Have you considered centralized health checking via HDS with this very large number of endpoints? I'm wondering if there are other issues at this scale of HC which could be solved structurally. Not opposed to the feature request though.
