### ISSUE TITLE
How to configure the transport_socket for the upstream connections using Incremental ADS in the bootstrap

### ISSUE THREAD

**Issue by whutwhu** [envoyproxy/envoy#28708]
How to configure the transport_socket for the upstream connections using Incremental ADS in the bootstrap

*Description*:
We are currently implementing Incremental ADS for Envoy to serve as the data plane for our services. Envoy works as a sidecar alongside its main service, and the security resources (certificates, keys, CA bundle) are shared between Envoy and its main service.

However, we are facing challenges when configuring the transport_socket in Envoy's bootstrap for the upstream connections. Since the clusters are dynamically subscribed from the control plane, there is no cluster specified in the bootstrap. We can only set up one listener for outbound requests from the source application. As a result, the first outbound request triggers the ADS subscriptions from Envoy, which include the [VirtualHost](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost), [Cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster), and [ClusterLoadAssignment](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint.proto#envoy-v3-api-msg-config-endpoint-v3-clusterloadassignment).

We would appreciate any suggestions or guidance on how to configure the transport_socket for the upstream connections using Incremental ADS in the bootstrap. Thank you for your help!

**Comment by htuch** [comment]
Can you share some config examples to illustrate the problem? Thanks.

**Comment by whutwhu** [comment]
Hey @htuch! The bootstrap configuration is provided below, and in our specific example:
1. Envoy is set to listen on `/export/var/outbound.sock` for the outbound traffic originating from its main service. 
2. Using ads, vhds in rds, and odcds, the first outbound request to the virtual host triggers the necessary subscriptions from the control plane.

In our current scenario, we are unsure about the appropriate location to configure the transport_socket for the upstream cluster in the bootstrap.

// bootstrap.yaml:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_outbound
  address:
   pipe:
     path: /export/var/outbound.sock
  filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
         "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
         stat_prefix: outbound_http
         codec_type: AUTO
         http_filters:
           - name: envoy.filters.http.on_demand
             typed_config:
               "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
               odcds:
                 source:
                   ads: {}
           - name: envoy.filters.http.router
             typed_config:
               "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
         rds:
           config_source:
             path_config_source:
               path: /export/content/envoy_rds.yaml
           route_config_name: "global"


// Below is  `/export/content/envoy_rds.yaml`
resources:
  - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: "global"
    vhds:
      config_source:
        resource_api_version: V3
        ads: {}

**Comment by htuch** [comment]
Can't you put the transport socket in the `Cluster` delivered via CDS rather than bootstrap?

**Comment by whutwhu** [comment]
It is possible to make it work by depending on a control plan that includes TLS information to deliver the transport socket within the cluster. However, this would result in additional data being stored in the control plan, such as certificate, key, and context information for all services.

An alternative option is to consider placing the transport socket in the bootstrap. This approach would be more convenient for our specific use case since TLS information is readily available during the bootstrap generation. Before proceeding, we seek the guidance and advice on the best and standard approach. Could you please confirm whether configuring the transport socket in the bootstrap is feasible? Or if there is any other solution? Thank you!

**Comment by htuch** [comment]
You can still generate and provide certs locally with SDS (and filesystem-based SDS). This means you can separate the cluster and secret configuration as different concerns.

**Comment by whutwhu** [comment]
@htuch thanks for the guidance!

**Comment by htuch** [comment]
NP. I'm going to close this out, feel free to reopen if you still have issues.
