### ISSUE TITLE
A question about service discovry

### ISSUE THREAD

**Issue by cl51287** [envoyproxy/envoy#2872]
I found the "Service discovery" is used to find the members of the clusters to envoy, and decide which cluster will be requested when a request visit envoy use a domain. But before this request visit envoy, the client must know the address of this domain first, Whether we must deploy a service discovery system in the client system in order to find the address of this domain? So, we must have two Service discovery system in our architecture

**Comment by cl51287** [comment]
Thx, i have joined slack. You mean i will deploy a envoy at the client system, and modify the dns to envoy, let the client find the domain via Enovy DNS, or configure hosts modify the domain to localhosts?

**Comment by zuercher** [comment]
One way is deploy an envoy alongside the client system, with the domain configured as "localhost" (or just "*") and configure the client to make requests to http:\/\/localhost. But it really depends on what you're trying to accomplish.

**Comment by cl51287** [comment]
Thanks for your answer.
