### ISSUE TITLE
command operator for the current time in access logging

### ISSUE THREAD

**Issue by chairmank** [envoyproxy/envoy#28736]
*Description*:

I see that there is a `%START_TIME%` command operator to get the start time of a stream, but I don't see any way to get the current system time in log messages that are emitted when `access_log_flush_interval` or `flush_access_log_on_connected` are enabled. This feature would be useful for timestamping events in the lifetime of a stream.

*Relevant Links*:
* https://github.com/envoyproxy/envoy/issues/26639

**Comment by htuch** [comment]
The stream is likely over at the point at which the logs are emitted though. Can you clarify the use case here? Thanks.

**Comment by chairmank** [comment]
I am using Envoy to proxy gRPC streams that can last for hours or even days. I need to observe these streams in the access log while they are in progress, so I have set `flush_access_log_on_new_request` and `access_log_flush_interval` in `access_log_options`. This logging configuration works as expected, but the log messages are difficult to interpret and search without a current timestamp field.

**Comment by chairmank** [comment]
Sorry, I don't understand that question. Can you please clarify? Are you asking about the Envoy configuration that I am using, or how I am collecting/searching logs after they are emitted by Envoy?

**Comment by htuch** [comment]
Envoy config

**Comment by chairmank** [comment]
I am using [`HttpConnectionManager`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager) with one access log of type [`StderrAccessLog`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/stream/v3/stream.proto#envoy-v3-api-msg-extensions-access-loggers-stream-v3-stderraccesslog) that uses JSON format.

**Comment by htuch** [comment]
Ack, the reason I ask is that some access log implementations can add the timestamp OOB. In this case, I think maybe what you want is EMIT_TIME for the access log, i.e .when it's written by Envoy to the access log buffer. Since the flush happens post-template processing, it will be hard to do something like FLUSH_TIME. Does this make sense for your use case?

**Comment by chairmank** [comment]
Yes. Including EMIT_TIME in the access log would make sense for my use case.

**Comment by IssaAbuKalbein** [comment]
@htuch Is there anyone working on supporting EMIT_TIME operator command?
If nobody working on this, I can try to add this feature.

**Comment by htuch** [comment]
@IssaAbuKalbein assigned to you.

**Comment by IssaAbuKalbein** [comment]
@htuch I've created this PR [[Access Log] Add EMIT_TIME command operator #31162](https://github.com/envoyproxy/envoy/pull/31162)
Can you take a look, please?
