### ISSUE TITLE
`//test/integration:tcp_proxy_odcds_integration_test` is flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#28730]
Ive been seeing this with seemingly increasing frequency - altho its possible it was just never fixed

```console
[ RUN      ] IpVersionsClientType/TcpProxyOdcdsIntegrationTest.RepeatedRequest/2
./test/integration/server.h:444: Failure
Value of: TestUtility::waitForCounterEq(statStore(), name, value, time_system_, timeout, dispatcher)
  Actual: false (timed out waiting for tcp.tcpproxy_stats.on_demand_cluster_attempt to be 10, current value 9)
Expected: true
Stack trace:
  0xb2e4fc: Envoy::(anonymous namespace)::TcpProxyOdcdsIntegrationTest_RepeatedRequest_Test::TestBody()
  0x1eb6e5c: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1eb6cfc: testing::Test::Run()
  0x1eb7e4c: testing::TestInfo::Run()
... Google Test internal frames ...
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=144658&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=67a76341-37f4-5b49-db38-acbb8a59af82&l=515

**Comment by phlax** [comment]
cc @ggreenway

**Comment by phlax** [comment]
https://dev.azure.com/cncf/4684fb3d-0389-4e0b-8251-221942316e06/_build/results?buildId=149568&tracking_data=ew0KICAic291cmNlIjogIlNsYWNrUGlwZWxpbmVzQXBwIiwNCiAgInNvdXJjZV9ldmVudF9uYW1lIjogIm1zLnZzcy1waXBlbGluZXMucnVuLXN0YXRlLWNoYW5nZWQtZXZlbnQiDQp9

**Comment by alyssawilk** [comment]
also all yuchen.  @kyessenov can you take a look?
