### ISSUE TITLE
Matching L4 attributes, like destination IP, in routes

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#28737]
*Title*: Matching L4 attributes, like destination IP, in routes

*Description*:
I would like the ability to match l4 attributes (in particular, destination IP) in routes.

The use case here is we are a service mesh for Kubernetes. We want to match on ClusterIP traffic, but sometimes we match `Host` header via `domains` in RDS, so we need to transition. This transition is not a point in time, but based on a users action (i.e. can happen dynamically and at any time).

So user request is `curl 1.2.3.4 -H "Host: foo"`. 

* State 1: Listener 0.0.0.0, match RDS match domain `foo`
* State 2: match 1.2.3.4, RDS match domain `*`

We need to transition between these states smoothly. Note bind_to_port=false and original_dst is used

The obvious answer is to just add a new listener on 1.2.3.4 (we use bind_to_port=false). The issue is new requests will already have matched to 0.0.0.0, so if we remove the RDS config those connections will start getting 404s and maybe never recover.

We want users to smoothly transition to the new config. Because the L4 matching is orthogonal/before the domain matching, this seemingly cannot be done.

**Comment by htuch** [comment]
You can already match on dynamic metadata, can that support this scenario with a filter that populates as needed?

**Comment by howardjohn** [comment]
I think that would likely work for some cases but we have an issue with domains behind higher precedence than any other route matches - we want IP to be highest precedence

**Comment by htuch** [comment]
You want this in `VirtualHost` then right? I wonder if you could use the generic `matcher`?

**Comment by howardjohn** [comment]
To be a bit more clear:

Today:

```
virtual_hosts:
- domains: [a, b, c]
  routes: ... route A ...
- domains: [d]
  routes: ...route B ...
```

Desired:

```
virtual_hosts:
- domains: [a, b, c]
  routes: ... route A ...
- destination_ips: [d address]
  routes: ...route B ...
```

With `destination_ips` having precedence over `domains`. Syntax doesn't matter, this is probably not the right API, just conceptually.

Generic matcher we maybe could but I think it would mean moving to a single virtual host instead of many? I am not sure the implication of that. So it would be something like this:

```
virtual_hosts:
- matcher:
    match IP:
      d address => route B
      else =>
        match domain
          [a,b,c] => route A
          else => 404
```

That may actually be fine (assuming we can match on the IP, but that seems easy to fix if not), although I am not sure the implications on moving from the old model to this.

One thing in particular is I had always hoped that we could eventually incrementally update the virtual hosts independently (not quite VHDS since we wouldn't want on-demand, but close) which this would break. But I have also said the same about collapsing from multiple listeners to one large listener with `matcher` for a long time and we still don't actually do incremental listener updates.... so maybe its not such a great argument :slightly_smiling_face:

**Comment by htuch** [comment]
I think maybe give the generic matcher a try. I worry a little bit about adding static match capabilities with precedences, since they will vary between users and then we need to provide flexible precedence, which is already solved by the tree structure in generic matchers. Look at what happened in filter chain matchers to see how complicated this becomes.
