### ISSUE TITLE
Improve docs and/or process of building a Docker image from release

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#28755]
The ci `release` target and Docker build have been changed and the docs no longer reflect accurately the steps needed to build a docker image

The docker build expects a tarball in the right place and structured correctly, so we need to update the docs to reflect that

Also, in general, the best Docker image to build is the `distroless` variant - so we should probably document that also

**Comment by nezdolik** [comment]
+1 on the stale docs, could not build the docker image for quite some time following the docs

**Comment by phlax** [comment]
funny - i was just thinking about this

ill try and get to it this week

**Comment by nezdolik** [comment]
lmk if i could help, am figuring out how to build right now :)

**Comment by phlax** [comment]
best advice is to see what it does in ci

the slight issue is that currently only the `release` path builds the correct tarball - i will update `release.server_only` asap to work ~the same

then its a case of making the tarball be in the right place
