### ISSUE TITLE
Flakiness in Session Affinity feature - Request with cookie are sent to different backend after a while.

### ISSUE THREAD

**Issue by pramodrj07** [envoyproxy/envoy#28756]
*Title*: *Observed flakiness in the Session Affinity feature*

*Description*:
The request with a cookie is routed to expected backend and is working correctly. But after a while, some requests are being routed to different backend. (This is quite rare but happens like 5% of the time). Also quite often we see that a request without a cookie is still routed (with the same route) to the same backend and is not load balanced across other backends.

*Admin and Stats Output*:
> 
> "route": {
> "weighted_clusters": {
> "clusters": [
> {
> "name": "some_cluster",
> "weight": 100
> }
> ],
> "total_weight": 100
> },
> "host_rewrite_literal": "",
> "timeout": "30s",
> "hash_policy": [
> {
> "cookie": {
> "name": "session-cookie",
> "ttl": "25s"
> }
> }
> ],
> "idle_timeout": "60s"
> }

*Config*: Below is an example, but I am using a control-plane similar to the one in the go-control plane.
> static_resources:
> listeners:
> name: listener_0
> address:
> socket_address:
> address: 0.0.0.0
> port_value: 5000
> filter_chains:
> filters:

> name: envoy.http_connection_manager
> typed_config:
> "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
> stat_prefix: ingress_http
> drain_timeout: 2s
> route_config:
> name: local_route
> virtual_hosts:
> - name: local_service
> domains:
> - "*"
> routes:
> - match:
> prefix: "/"
> route:
> cluster: example_proxy_cluster
> http_filters:

> name: envoy.filters.http.stateful_session
> typed_config:
> "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
> session_state:
> name: envoy.http.stateful_session.cookie
> typed_config:
> "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
> cookie:
> name: session-cookie
> ttl: 25s
> transport_socket:
> name: envoy.transport_sockets.starttls
> typed_config:
> "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.StartTlsConfig
> tls_socket_config:
> common_tls_context: {}

> clusters:

> name: some_cluster
> transport_socket:
> name: envoy.transport_sockets.starttls
> typed_config:
> "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.UpstreamStartTlsConfig
> tls_socket_config:
> common_tls_context: {}
*Logs*:
>Envoy-logs - Did not see any cookie-related information apart from the cookies mentioned in the requests.
Access-Logs - Cookies are present under the route-action.

NOTE - Also it would be great to verify if this is the expected behavior currently and if we plan to change

**Comment by pramodrj07** [comment]
@lizan @cpakulski @wbpcode

**Comment by wbpcode** [comment]
Hi, could you provide some more context? For example, what lb type is used? And how you fire the requests (curl or broswer)?

**Comment by wbpcode** [comment]
@pramodrj07 sorry for the delayed response. I just missed your last response.

> We are using "RING HASH" as Lb type.

Seems both stateful session filter and ring hash are used by you and same cookie name is used which will make the behavior of Envoy be wierd. The stateful session filter will provide a stateful session affinity, and the ring hash will provide the soft session affinity (by hash ring).

**Comment by pramodrj07** [comment]
@wbpcode - no worries. Ty for the reply. I think the above configuration is a bit incorrect. I see cookies only at 2 places in the admin config. I have pasted them below. It seems like the Stateful session filter does not have the cookie. 

1.  {
       "name": "envoy.http.stateful_session.cookie",
       "category": "envoy.http.stateful_session",
       "type_urls": [
        "envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState"
       ]
      },
      {

2.  "route": {
           "weighted_clusters": {
            "clusters": [
             {
              "name": "/$serviceRoutingConfig$/Gateway/test-customer-system/gateway-01/$rule$/test-customer-system-http-route-custom-rule-0-match-0-custom.com/$backendService$/test-customer-system/echo-custom/80/$backendPool$/test-customer-system/echo-custom/80/$location$/westus/$interface$/eth0",
              "weight": 100
             }
            ]
           },
           "host_rewrite_literal": "",
           "timeout": "30s",
           "hash_policy": [
            {
             "cookie": {
              "name": "ApplicationCookieName",
              "ttl": "86401s"
             }
            }

I think we are not using the same cookie at 2 places now. My bad for confusion. With this conifg, we see that the soft session affinity is still breaking after 20 or so requests.

**Comment by wbpcode** [comment]
There are too much factors that may result in different load balancing results. It would be better to evaluate these factors one by one.

Specific to the ring hash, there are two different modes: 1) passive mode: envoy takes a cookie that's present in the cookies header and hashes on its value. 2) generated mode Envoy generates and sets a cookie with an expiration (TTL) on the first request.
If you send requests without cookie, envoy will generated one, and if the client could handle the `set-cookie` headers, the generated cookie will be used to keep the session. If your client couldn't handle the `set-cookie` headers and your requests without related cookie, I think the session affinity won't work.

And the change/update of backend endpoints list will also effect the result of the load balancing.

**Comment by gregbanks** [comment]
so, just to be clear, is this an issue (i.e., will stateful sessions be honored) to be concerned about if a round robin, random, or least request load balancing policy is configured (i.e., not ring hash or maglev)?

**Comment by wbpcode** [comment]
If round robin and stateful session are configured, then:

> But after a while, some requests are being routed to different backend.

This depends the TTL of stateful session. stateful session will ignore the expired cookie value. (stateful session will record a expire time in the cookie value and validate it when receiving a cookie.)

> Also quite often we see that a request without a cookie is still routed (with the same route) to the same backend and is not load balanced across other backends.

If this still happen when round robin is used, then you need to ensure if the client will handle the `set-cookie` header first.

---

It say I still didn't get enough context to make a conclusion.

**Comment by pramodrj07** [comment]
> This depends the TTL of stateful session. stateful session will ignore the expired cookie value. (stateful session will record a expire time in the cookie value and validate it when receiving a cookie.)

I see. This is a bit confusing to me. We do have a huge ttl in each cookie. Is a value of 10000s good enough for a test that run within a couple of mins.?

> If this still happen when round robin is used, then you need to ensure if the client will handle the set-cookie header first.

our client has the capability to handle `set-cookie` header.

**Comment by wbpcode** [comment]
> I see. This is a bit confusing to me. We do have a huge ttl in each cookie. I presume a value of 10000s as TTL is good enough for a test that run within a couple of mins.?

If round robin and stateful session are used, and the cookie ttl is a very long time, but the session affinity is invalid in a short time, then, yeah, it's a problem need to do deeper investigate.
Could you provider a complete config_dump file or example .yaml that could reproduce this problem?

> our client has the capability to handle set-cookie header.
If stateful session are used, Envoy will set a new cookie into response of every request that didn't contains session cookie. The the client could handle `set-cookie` header, will it add the cookie to the request? Then the subsequent requests will be routed to same backend?

**Comment by pramodrj07** [comment]
@wbpcode - This is the config we have. Please do let me know if you need any further logs/configs

**Comment by wbpcode** [comment]
> @wbpcode - This is the config we have. Please do let me know if you need any further logs/configs

I think it has no stateful session config, so the your provided latest config is used to test the ring hash (soft session affinity)?

**Comment by pramodrj07** [comment]
> > @wbpcode - This is the config we have. Please do let me know if you need any further logs/configs
> 
> I think it has no stateful session config, so the your provided latest config is used to test the ring hash (soft session affinity)?

Yes, that's correct. Only the Soft session affinity currently. My bad if it was confusing.

**Comment by wbpcode** [comment]
Hmmm, I will try it in my local env when I get some free time. 🤔  But I think the tech should be simple and clear. It just calculate a hash value from the cookie value and select a host from the hash ring.

**Comment by pramodrj07** [comment]
> Hmmm, I will try it in my local env when I get some free time. 🤔 But I think the tech should be simple and clear. It just calculate a hash value from the cookie value and select a host from the hash ring.

I agree with you. It's supposed to be simple. But i am seeing this flakiness after some time. That's what is bothering me.

**Comment by wbpcode** [comment]
I have tested the ring hash in my local env and a brower is used as the client. Seems everything work well.

**Comment by pramodrj07** [comment]
> I have tested the ring hash in my local env and a brower is used as the client. Seems everything work well.

That's great. Would you mind walking me through the setup on how you verified if it is hitting the same backend? I used the go's http client and i am seeing the same flakiness.
