### ISSUE TITLE
Ability to specify unit/precision of access log duration

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#2877]
*Title*: Ability to specify unit/precision of access log duration

*Description*:
Durations are hard-coded to milliseconds, it would be super convenient to be able to specify the unit i.e. seconds so that `3` milliseconds is logged as `0.003`. Additionally, from the code, it appears that the duration is stored using `chrono::nanoseconds` so it shouldn't be difficult to provide precision control from `ns` and up (our previous system provides ns precision and we're working for on-par drop-in replacement for logging). An example of the final result is that someone could specify seconds-unit but with nanosecond precision.

Somewhat related to issue #2709 - I'm willing to provide an implementation.

**Comment by moadi** [comment]
@htuch does this only apply to `START_TIME`, or can I use this mechanism to format other duration entries too? looking at the docs it only seems to specify that we can format `START_TIME`

**Comment by htuch** [comment]
@moadi I think you are right; PRs welcome.
