### ISSUE TITLE
[ext_authz] Removing any query parameters results in corruption if query parameters are repeated

### ISSUE THREAD

**Issue by turettn** [envoyproxy/envoy#28787]
*Title*: Removing any query parameters results in corruption if query parameters are repeated

*Description*:
Normally, if the query parameters portion of a request has a repeated value (e.g. `?a=b&a=c`), the upstream service receives the unmodified query parameters.

However, if the ext_authz service attempts to removes ANY query parameter on an [OKResponse](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#envoy-v3-api-msg-service-auth-v3-okhttpresponse), the only the first value for a repeated key is retained. 

*Repro steps*:
With a ext_authz server returning an OKResponse with no options set, I send a request to a backend:

```
curl "http://localhost:8080/api/v1/english/test?a=b&a=c" | jq
```

The server is set up to return:

```
			Path:         html.EscapeString(req.URL.Path),
			RawQuery:     html.EscapeString(req.URL.RawQuery),
			QueryParams:  req.URL.Query(),
```

And I get

```
  "Path": "/api/v1/english/test",
  "RawQuery": "a=b&amp;a=c",
  "QueryParams": {
    "a": [
      "b",
      "c"
    ]
  },
```

Once I modify the OKResponse to remove a query parameter:

```go
	return &auth.CheckResponse{
		Status: &rpcstatus.Status{
			Code: int32(codes.OK),
		},
		HttpResponse: &auth.CheckResponse_OkResponse{
			OkResponse: &auth.OkHttpResponse{
				QueryParametersToRemove: []string{"asdf"},
			},
		},
	}
```

I can repeat my original request, and now I get:

```
  "RawQuery": "a=b",
  "QueryParams": {
    "a": [
      "b"
    ]
  },
```

*Unit Test*:

If I add the following unit test to `ext_authz_test.cc`, it fails:

```c++
TEST_P(HttpFilterTestParam, ImmediateOkResponseWithRepeatedUnmodifiedQueryParameters) {
  const std::string original_path{"/users?leave-me=alone&leave-me=in-peace"};
  const std::string expected_path{"/users?leave-me=alone&leave-me=in-peace"};
  const Http::Utility::QueryParamsVector add_me{};
  const std::vector<std::string> remove_me{"remove-me"};
  queryParameterTest(original_path, expected_path, add_me, remove_me);
}
```

**Comment by htuch** [comment]
@esmet @tyxia @ggreenway looks like a bug that should be fixed, multiple query parameters appear legit.
