### ISSUE TITLE
ecds: upstream http filters use invalid clusterManager

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#28795]
While implementing ECDS support for upstream network filters, I encountered that ``server_context`` holds invalid reference to ClusterManager object, as well ``TransportSocketFactoryContext& factory_context`` if called on ``factory_context.serverFactoryContext()``.

These are at the following ctor of ``ClusterInfoImpl``:
https://github.com/envoyproxy/envoy/blob/87b282d7c1a17190aabf406857378233f33c7e24/source/common/upstream/upstream_impl.cc#L1018-L1023

Upstream HTTP filters with ECDS use this reference in ``getSubscription`` along the ECDS path. Therefore currently it won't work and cause Envoy to crash.

It seems like this is a known issue, as commented here and referencing the issue #26653:
https://github.com/envoyproxy/envoy/blob/87b282d7c1a17190aabf406857378233f33c7e24/envoy/server/transport_socket_config.h#L39

I created draft integration tests for both HTTP upstream filters and network upstream filters to verify that it happens in both:
#28792, #28776.

I will attempt to modify the interface in a way that also takes the ClusterManager reference explicitly, instead of using the one from the server context. For downstream filters ECDS this problem does not happen as there the ClusterManager reference is valid.

*Repro steps*:
Run the integration tests in the branches referenced above.

*Logs*:
In debug build: ``[source/server/server.cc:178] assert failure: config_.clusterManager() != nullptr.``
In regular build (as in CI): 
```
[./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
[./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[./source/server/backtrace.h:92] Envoy version: 0/1.28.0-dev/test/RELEASE/BoringSSL
[./source/server/backtrace.h:96] #0: __restore_rt [0x7f7dac745420]
[./source/server/backtrace.h:96] #1: std::__1::allocate_shared<>() [0x14991ea]
[./source/server/backtrace.h:96] #2: Envoy::Filter::FilterConfigProviderManagerImplBase::getSubscription() [0x149672f]
```

**Comment by htuch** [comment]
Makes sense to me CC @alyssawilk
