### ISSUE TITLE
OAuth2 State Parameter Issue

### ISSUE THREAD

**Issue by lamc** [envoyproxy/envoy#28811]
*Title*: *OAuth2 State Parameter Issue*

*Description*:
> I have updated my envoyproxy config from v1.16.0 v3alpha oauth2 filter to the example provided for v1.27.0 to have oauth flow for one of my mesh components -- however I see an issue where the state parameter has the wrong protocol.  Prior to upgrading the version, the state parameter would be https -- however after version upgrade to v1.27.0 it always is set to http. 

I was looking to see if anyone had any insight or if there are any discrepancies in the oauth2 filter api code? Any help is greatly appreciated!

**Comment by htuch** [comment]
Not sure the exact change, but you could have a look at https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history and https://github.com/envoyproxy/envoy/commits/main/source/extensions/filters/http/oauth2.

CC @derekargueta @mattklein123

**Comment by lamc** [comment]
I see in the commented section in the oauth2 filter code that the scheme is defaulted to https, but it doesn't seem to be the case though https://github.com/envoyproxy/envoy/blob/release/v1.27/source/extensions/filters/http/oauth2/filter.cc#L405

In order to fix the issue I was having, I had to add [this](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-schemeheadertransformation) `scheme_header_transformation` to overwrite it from http to https.
