### ISSUE TITLE
Envoy request retry whenever all conditions are met at the same time

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#28831]
*Envoy request retry whenever all conditions are met at the same time*

*We have to following question-using RetryPolicy we want requests to be retried whenever multiple conditions are met at the same time and not only one of them. For example, we want to retry the request if status code is 400 and some request/response header is present. It seems like whenever only one of the condition is met, that is sufficient for retry. Doing AND when validating the conditions instead of OR should do the job. Is there a way to do it?*

**Comment by htuch** [comment]
Can you share an example config fragment? Thanks.
