### ISSUE TITLE
Add into dynamic metadata the filter name that generate a local replay

### ISSUE THREAD

**Issue by juanmolle** [envoyproxy/envoy#28834]
Add into dynamic metadata the filter name that generate a local replay

It could be useful lo allow http_connection_manager add metadata for the filter name that stop iteration and generate a local replay
That metadata could be consumed by access_log or eventually other custom filter

**Comment by htuch** [comment]
I think this seems reasonable. I'm not sure if dynamic metadata is the right choice or whether it should be some kind of loggable stream attribute though.

**Comment by ramaraochavali** [comment]
FILTER_STATE may be better because DYNAMIC_METADATA is not accessible from WASM filters or any other new stream attributes

**Comment by juanmolle** [comment]
Interesting I thought dynamic_metadata was accessible, anyway I have read it could have performance impact, and probably FILTER_STATES could be a better place. Is it possible to access any data from wasm filter? apparently, accessing from wasm to write or read add "wasm." namespace.
