### ISSUE TITLE
Envoy request retry based on request header

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#28832]
*Envoy request retry based on request header*: 

*We are facing the following issue-using RetryPolicy we want to retry a request whenever a request header is present(not header from the upstream). In the envoy documentation (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on) only "retriable-headers" is present(regarding headers from the upstream) but using XDS config in control plane, in the library for routes there is a field "RetriableRequestHeaders: headers,"(Golang) which is not documented. It seems like it does not work and the request is not retried whenever specified request headers are present. We specified also "RetryOn: "retriable-status-codes,retriable-request-headers,retriable-headers"". Is this correct or something else must be done?*

**Comment by htuch** [comment]
The retriable request headers are documented at https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy. From the wording, the headers need to be in the request but this alone does not force a retry.
