### ISSUE TITLE
Is it possible to log the info of response header?

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#28855]
I've known how to use Access Logging to log info of requests in Envoy. For example we can configure the logging of Envoy with `%RESPONSE_CODE% %RESPONSE_FLAGS%` so that we could see the info of responses.

My question is if it's possible to log the other info of response, such as the header of response?

Let's say that the upstream endpoint generate a HTTP response, whose header contain a pair of custom key value `key:value`. Is it possible to log the `key:value`?

**Comment by htuch** [comment]
Yes, see the `%RESP(..)%` format string at https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#format-strings.
