### ISSUE TITLE
data-plane-api sync is failing due to branch protections

### ISSUE THREAD

**Issue by jbohanon** [envoyproxy/envoy#28882]
*Title*: data-plane-api sync is failing due to branch protections

*Description*:
>Describe the issue.

In the [logs](https://github.com/envoyproxy/data-plane-api/actions/runs/5789582998/job/15690918494) for the [envoyproxy/data-plane-api](https://github.com/envoyproxy/data-plane-api) sync action, we can see that the push is failing due to branch protection. Due to this, this read-only mirror has not been updated since June 3

**Comment by KBaichoo** [comment]
cc @phlax might this be related to https://github.com/envoyproxy/data-plane-api/pull/629? Should the App be syncing these instead of manual sync?

**Comment by pgeler** [comment]
@phlax +1 just curious if there is something to make it happen, we are using data-plane-api as dependency for our service implementations and changes for v1.27 are beyond Jun 3rd.

**Comment by phlax** [comment]
>  just curious if there is something to make it happen

i just need to find time to switch branch protetcion -> rulesets

**Comment by phlax** [comment]
cc @htuch i guess this means the data-plane-api repo _is_ used

**Comment by phlax** [comment]
this should now be fixed
