### ISSUE TITLE
Support sending headers with HTTP health checks

### ISSUE THREAD

**Issue by jakerobb** [envoyproxy/envoy#2888]
*Description*:
Thanks to some legacy cruft, my health check endpoint will return a 400 error if it is invoked without a specific set of HTTP headers.

This is an enhancement request to allow me to specify one or more headers to be included when Envoy calls the health check endpoint.

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto.html#envoy-api-msg-core-healthcheck-httphealthcheck

**Comment by dio** [comment]
@jakerobb how do you want to specify the values of the required headers? Do you think setting it in the config will suffice your requirement? 

e.g.

```js
{
  "host": "...",
  "path": "...",
  "service_name": "...",
  "headers": { "additional-header-key-1": "value-1", "additional-header-key-2": "value-2"}
}
```

**Comment by jakerobb** [comment]
Something like that would be perfect. I'm using a home-built xDS based on java-control-plane, so I can provide whatever the API supports.
