### ISSUE TITLE
Is there any debuginfo package for envoy?

### ISSUE THREAD

**Issue by isshe** [envoyproxy/envoy#28887]
*Title*: *missing debuginfo of envoy*

*Description*:
I'm trying to track envoy issues, but the debug information is missing.

**Comment by KBaichoo** [comment]
cc @phlax 

What version of Envoy are you looking for debuginfo for?

**Comment by phlax** [comment]
the dbg Docker images are probably the best place to start https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=debug

we dont publish the dbg images on our release page but we probably should

**Comment by isshe** [comment]
OK, thank you!

I have a few more questions:
- Is there an official source RPM package available?
- Where can I obtain the compilation parameters for your production build of Envoy? 
- How did you build the RPM package? Are there SPEC files or the like? could you give it to me?

thank you
