### ISSUE TITLE
gcp_authn: Support Cloud Run X-Serverless-Authorization header for authorization

### ISSUE THREAD

**Issue by fiadliel** [envoyproxy/envoy#28894]
*Support X-Serverless-Authorization header for GCP authorization*

Google Cloud Run supports the `X-Serverless-Authorization` header in addition to the `Authorization` header, for supporting server-to-server connections, preferring to validate the IAM identity from the `X-Serverless-Authorization` header, if it exists. See https://cloud.google.com/run/docs/authenticating/service-to-service

It is often useful to have two authorization communications channels; one for the immediate server-to-server link, and another for authorizing the original caller, which is often expected in the `Authorization` header. Using the new header would free up the `Authorization` header for such uses. 

As this is a backwards-incompatible change (there could be other consumers for this token than Cloud Run), it should either be a configurable parameter, or allow a fallback via runtime feature + deprecation period.

**Comment by KBaichoo** [comment]
cc @tyxia  @yanavlasov

**Comment by tyxia** [comment]
Hi @fiadliel , Thanks for using gcp_authn_filter! 

I agree it is useful and valuable to support `X-Serverless-Authorization`. I think our team does't have bandwidth for this at the moment. That will be great and very welcomed if you want to contribute to this filter. I can help with any questions, code review and so on.

Please let me know if you have any other questions

**Comment by fiadliel** [comment]
Hi @tyxia 
I started looking at this, and realised (if only I'd checked the documentation fully) you already can set the header (`token_header` field). So the plugin has the flexibility to support this already! The only question is whether it would be a good idea to change the default (rocking the boat vs having a better default for the long term).

WDYT? I'm personally thinking the change isn't worth the cost/compatibility issues.

**Comment by tyxia** [comment]
Great! I would say let's keep the default unchanged since this filter has been widely used. Any custom behavior can be defined based on own use case.

Please let me know if you have any other questions/needs.
