### ISSUE TITLE
Wrong ttl used when respect_dns_ttl is set

### ISSUE THREAD

**Issue by kanongil** [envoyproxy/envoy#28925]
I have an upstream with `type: STRICT_DNS` and `respect_dns_ttl: true`. However, when I change the DNS entry, envoy *does not update the origin IP* as expected.

I have done a quick debug, and it appears that envoy uses the TTL from the CNAME resolved entry in the DNS response, instead of the base entry TTL. For example with an `entry.example.com` upstream and the observed below response:

```
dig entry.example.com
…
;; ANSWER SECTION:
entry.example.com.	10 	IN	CNAME	host1.example.com.
host1.example.com.	86400	IN	A	1.2.3.4
```

Here I can observe that envoy chose the value `86400` for ttl, rather than `10`. I can confirm this with `upstream` debug logging, which returns something like this when envoy starts:

```
[2023-08-09 12:04:43.386][233471][debug][upstream] [source/extensions/clusters/strict_dns/strict_dns_cluster.cc:149] DNS hosts have changed for entry.example.com
[2023-08-09 12:04:43.386][233471][debug][upstream] [source/extensions/clusters/strict_dns/strict_dns_cluster.cc:177] DNS refresh rate reset for entry.example.com, refresh rate 86400000 ms
```

I would expect envoy to refresh it as a normal DNS client would, ie. after 10s.

This was tested with v1.27.0 on Linux.

### Cause investigation

I expect this is an issues with the c-ares resolver interface. Looking at the logic, it seems that the `cnames` field in the [`ares_getaddrinfo`](https://c-ares.org/ares_getaddrinfo.html) response is completely ignored:

https://github.com/envoyproxy/envoy/blob/27218f51ba9a9fe5932deb26a949aadc7387e883/source/extensions/network/dns_resolver/cares/dns_impl.cc#L202-L228

The correct way to handle this, is probably to use the minimum TTL of all CNAME entries and the `ai_ttl` of the used node.

It could potentially be a problem with the apple resolver as well.

**Comment by KBaichoo** [comment]
cc @yanavlasov

**Comment by kanurag94** [comment]
I would like to work on this if no one else has started

**Comment by KBaichoo** [comment]
Thank you @kanurag94 , I don't know of anyone else who has started working on this.

**Comment by kanurag94** [comment]
Thank you so much @KBaichoo for assigning this. I will start working on it :)
