### ISSUE TITLE
`/retest` is not retriggering failed Azure pipelines

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#28934]
Example PRs where this happened: 
https://github.com/envoyproxy/envoy/pull/28906
https://github.com/envoyproxy/envoy/pull/28900

That leaves two ways to retrigger:
1. Only if you have permissions (e.g. envoy maintainers), you can do so by clicking on the failing workflow, then in the right corner, select "re-run failed actions".
2. Push a "dummy" commit to your branch to trigger re-run of the workflows.

Only a few people can do (1) and (2) is a bit inconvenient.

**Comment by phlax** [comment]
i have begun some work on this here https://github.com/envoyproxy/toolshed/pull/796
