### ISSUE TITLE
Support sinking histogram in stats_sink.wasm

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#28938]
For now, for the stats_sink.wasm, only counter and gauge are supported but not histogram. We need to flush histogram to wasm plugins as well.

https://github.com/envoyproxy/envoy/blob/0f566c4e1c3a1cc72b3ed70d131c565fb1a73090/source/extensions/common/wasm/context.cc#L237-L326

https://github.com/envoyproxy/envoy/blob/432723825f8aa2e2ef29535a2cb1992b2aa4ec58/source/extensions/common/wasm/ext/envoy_proxy_wasm_api.h#L82-L123

test: https://github.com/envoyproxy/envoy/blob/0f566c4e1c3a1cc72b3ed70d131c565fb1a73090/test/extensions/stats_sinks/wasm/wasm_stat_sink_test.cc

**Comment by TAOXUY** [comment]
@kyessenov

**Comment by kyessenov** [comment]
Is this an ABI limitation or incomplete implementation? cc @mpwarres

**Comment by TAOXUY** [comment]
> Is this an ABI limitation or incomplete implementation? cc @mpwarres

Thanks @kyessenov! By reading the code, seems the later one and we just need to add encoding/decoding for histogram.

**Comment by TAOXUY** [comment]
To support a minimal histogram, we could only support [ParentHistogram](https://github.com/envoyproxy/envoy/blob/9c1dcef98fe3982e26ec9e24ccd19de39862949d/envoy/stats/histogram.h#L154){intervalStatistics()}, [HistogramStatistics](https://github.com/envoyproxy/envoy/blob/9c1dcef98fe3982e26ec9e24ccd19de39862949d/envoy/stats/histogram.h#L34-L89){supportedQuantiles(), computedQuantiles() , sampleCount()}
