### ISSUE TITLE
Error " no such target '@platforms//os:visionos': target 'visionos' not declared in package 'os' " with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [envoyproxy/envoy#28940]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3228#0189dd37-12dc-421c-898d-e93a47ff31e7

Platform : Multiple

Logs
```

(02:19:19) ERROR: /var/lib/buildkite-agent/builds/bk-docker-222l/bazel-downstream-projects/envoy/test/integration/BUILD:1248:14: every rule of type cc_test implicitly depends upon the target '@platforms//os:visionos', but this target could not be found because of: no such target '@platforms//os:visionos': target 'visionos' not declared in package 'os' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/2f5de6899e69895d54bf6e9ca19ff1db/external/platforms/os/BUILD (Tip: use `query "@platforms//os:*"` to see all the targets in that package)
(02:19:20) ERROR: Analysis of target '//test/integration:integration_test' failed; build aborted: Analysis failed
```

By upgrading the "platform" version to 0.0.7 which adds "visionos" support. https://github.com/bazelbuild/bazel/pull/18905#issuecomment-1670976366

CC Greenteam  @comius

**Comment by keith** [comment]
looks like our platforms is coming from rules_rust, so once https://github.com/bazelbuild/rules_rust/pull/2111 merges we can update that to fix this issue

**Comment by sgowroji** [comment]
Hi Team or @keith , Looks like https://github.com/bazelbuild/rules_rust/pull/2111 is merged. Can we update it for envoy. Thanks

**Comment by keith** [comment]
thanks for the reminder https://github.com/envoyproxy/envoy/pull/29068
