### ISSUE TITLE
Ability to configure a custom metric name prefix for Open Telemetry stats sink

### ISSUE THREAD

**Issue by dceravigupta** [envoyproxy/envoy#28962]
*Title*: *Ability to configure a custom metric name prefix for Open Telemetry sink*

*Description*:
We are currently using dogstatd stats sink which allows to configure a custom metric name prefix. We wanted to migrate to open telemetry stats sink but seems like it doesn't have such support and hence would break our telemetry as all our metrics will get renamed.

Wondering if it is possible to add support for it to allow seamless migration from one stats sink to another?

![image](https://github.com/envoyproxy/envoy/assets/32182026/6a811326-5073-446e-a013-9fdc57c45daa)
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#config-metrics-v3-dogstatsdsink

**Comment by ohadvano** [comment]
Should be possible, assigned this on me
