### ISSUE TITLE
Regarding envoy api dependency compatibility problem

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#28963]
We have upgraded envoy 1.17.4 to envoy 1.26.1. I have made below corresponding api dependency and it's version. But we are not able to find envoy api dependency in envoy 1.26.1 corresponding udpa. 

I have collected this table data from the below link
https://www.envoyproxy.io/docs/envoy/v1.26.1/intro/arch_overview/security/external_deps
https://www.envoyproxy.io/docs/envoy/v1.17.4/intro/arch_overview/security/external_deps

<img width="443" alt="Capture" src="https://github.com/envoyproxy/envoy/assets/113907674/9d8b1c67-d040-4f05-be34-6972596cfe9c">

Please let us know what is the corresponding udpa api for envoy 1.26.1

**Comment by phlax** [comment]
udpa is (gradually) being renamed to xds - check the xds dep here https://www.envoyproxy.io/docs/envoy/v1.26.1/intro/arch_overview/security/external_deps#external-dependencies-api

**Comment by Gaurav0411GitHub** [comment]
Thanks for your help for udpa.
I need help for protoc-gen-validate-0.10.1 also there is only validate folder but previously we were using gogoproto and validate folder so from where I can take gogoproto folder in protoc-gen-validate-0.10.1

**Comment by yanavlasov** [comment]
1. gogo support was removed from protoc-gen-validate. https://github.com/bufbuild/protoc-gen-validate/pull/340 You can ask in gogo forums about its status
2. You need to generate them using protobuf compiler. This is gRPC doc: https://grpc.io/docs/languages/cpp/basics/
3. I assume it is the same as 2

**Comment by Gaurav0411GitHub** [comment]
Thanks for your suggestion.
I am new for gRPC and protocol buffers. Please give me some steps to install protoc compiler and generating files

**Comment by Gaurav0411GitHub** [comment]
Is there anyway to compile all the dependencies at once and generating *.cc and *.h file? Please ping me that steps so that we can get in simple way?

**Comment by yanavlasov** [comment]
It depends on what build system you are using. The https://grpc.io/docs/languages/cpp/basics/ explains how to use CMake. If you use bazel you can use build macros that Envoy is using, check out how https://github.com/envoyproxy/nighthawk for example.

**Comment by Gaurav0411GitHub** [comment]
Thanks for your help
I have generated envoy api and envoy api dependencies after compiling I am getting below compilation error

envoy/data/tap/v2alpha/wrapper.pb.cc:93:6: error: ‘::descriptor_table_udpa_2fannotations_2fstatus_2eproto’ has not been declared
   &::descriptor_table_udpa_2fannotations_2fstatus_2eproto,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
envoy/data/tap/v2alpha/wrapper.pb.cc:93:6: note: suggested alternative: ‘descriptor_table_google_2fprotobuf_2fstruct_2eproto’
   &::descriptor_table_udpa_2fannotations_2fstatus_2eproto,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      descriptor_table_google_2fprotobuf_2fstruct_2eproto

I have just generated these files so I can't declare these structures so please help me how can I resolve this error
