### ISSUE TITLE
Statsd global prefix

### ISSUE THREAD

**Issue by Lookyan** [envoyproxy/envoy#2897]
**Add global prefix for all statsd metrics**

*Description*:
For now, we have the only option to send all metrics with 'envoy.' prefix. But it will be useful to have an option to send all metrics to special branch, for example, 'resources.envoy...'

**Comment by alyssawilk** [comment]
@Lookyan flagging this as help wanted for now, but were you planning on picking it up?

**Comment by Lookyan** [comment]
If somebody wants to do it, it will be perfect. Otherwise I'll come back to it in following 2-3 months.

**Comment by athampy** [comment]
I can work on this
