### ISSUE TITLE
Default Behaviour on upstream

### ISSUE THREAD

**Issue by balu-ce** [envoyproxy/envoy#28991]
*Title*: *Default Behaviour on upstream*

*Description*:

- We are using istio to our application and envoy proxy is running as sidecars
- we want request external api call to the outside world from our applications(calling https request) , below are my questions

1. Do envoy intercept this traffic ?
2. If intercept, will the envoy creates a new socket connection for the https request
3. Is it perform any iptables nat forward operation

Rest of the question , will ask in the thread based on the response

**Comment by yanavlasov** [comment]
This looks like an Istio related question. Please ask in Istio forums.
