### ISSUE TITLE
Retrieve endpoints received by EDS

### ISSUE THREAD

**Issue by Lookyan** [envoyproxy/envoy#2899]
**Retrive endpoints received by EDS**

For now, I don't see any feature to get endpoints mapped to clusters (added via EDS). 

Maybe we should add it to admin page of envoy?

**Comment by dio** [comment]
Seems like it is similar to https://github.com/envoyproxy/envoy/issues/2421?

**Comment by htuch** [comment]
Yes, dupes #2421, closing out. @Lookyan you can follow that issue for progress (there are PRs in flight to that end from @jsedgwick).
