### ISSUE TITLE
Slow start mode "expires" when more members added to the cluster.

### ISSUE THREAD

**Issue by palmobar** [envoyproxy/envoy#29008]
*Title*: *Slow start mode "expires" when more members added to the cluster.*

*Description*:
> When a new member joins the cluster and slow start is configured the current pod which still should be in slow start are getting all the request that they would as if the slow start window finished already. One picture is worth a thousand words so please see the attached screenshot:

<img width="840" alt="Screenshot 2023-08-14 at 16 57 57" src="https://github.com/envoyproxy/envoy/assets/95422414/5622d5f8-7d2a-428d-905d-c08d737f7463">

You can see that the red line starts gradually which is what I'd expect from a slow start however once the new pod (member) is added (the green line) the amount of requests directed to the red line suddenly jumps. The slow starts is configured for 300s but the "jolt" happens within a bit more than one minute from the start.

*Repro steps*:
> kubectl scale --replicas=2 deploy/aiohttp-service; sleep 75; kubectl scale --replicas=3 deploy/aiohttp-service

```
   "ISTIO_VERSION": "1.17.3",
   "version": "43cd81989c499d2382fd80ac077b14d728fe41eb/1.25.7-dev/Clean/RELEASE/BoringSSL",
```

edit: fixed my english a bit

**Comment by palmobar** [comment]
This is somewhat related to #28512 so I'm going to highlight @nezdolik (I hope that's okay).

**Comment by nezdolik** [comment]
@palmobar i believe this issue has been reported by Istio users before and i was not able to reproduce the problem with vanilla Envoy setup, so more information from your side will be useful. Could you provide:
* All the slow start configuration you are using (slow_start_window, aggression, min_weight_percentage)
* Load balancer type
* Was there any change in red pod health status during the slow start window?

**Comment by palmobar** [comment]
@nezdolik There was no change in pod's health (there is no health check configured at all, except the istio's injected sidecar has readiness probe defined), please see the cluster's configuration (taken from envoy's dump) on the bottom. I believe the relevant bit is that one:

```
      "round_robin_lb_config": {
       "slow_start_config": {
        "slow_start_window": "300s"
       }
      }
```

The istio configuration looks like the following:

```
$ kubectl get destinationrule/aiohttp-service -o yaml # removed uninteresting bits (like annotations and labels) for brevity
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
[...]
spec:
  host: aiohttp-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      warmupDurationSecs: 300s
```

```
    {
     "version_info": "2023-08-14T14:19:53Z/53",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|8080||aiohttp-service.default.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|8080||aiohttp-service.default.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "default_original_port": 8080,
         "services": [
          {
           "name": "aiohttp-service",
           "host": "aiohttp-service.default.svc.cluster.local",
           "namespace": "default"
          }
         ],
         "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/destination-rule/aiohttp-service"
        }
       }
      },
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "protocol": "istio-peer-exchange"
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "tls_params": {
            "tls_minimum_protocol_version": "TLSv1_2",
            "tls_maximum_protocol_version": "TLSv1_3"
           },
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {
             "match_subject_alt_names": [
              {
               "exact": "spiffe://cluster.local/ns/default/sa/default"
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.8080_._.aiohttp-service.default.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
         }
        }
       }
      ],
      "round_robin_lb_config": {
       "slow_start_config": {
        "slow_start_window": "300s"
       }
      }
     },
     "last_updated": "2023-08-14T14:19:53.526Z"
    },
```

Please let me know if there is any information or experiment I can provide/do so that it would help you to navigate/reproduce this issue

**Comment by palmobar** [comment]
Also inspired by your question(s) I checked if during the expriment the pods change the state and it doesn't look like they do (e.g. the pod doesn't go into not ready state):

```
k get po --watch
[...]
aiohttp-service-99857644c-5wpzp   0/2     Pending   0          0s
aiohttp-service-99857644c-5wpzp   0/2     Pending   0          0s
aiohttp-service-99857644c-5wpzp   0/2     Init:0/1   0          0s
aiohttp-service-99857644c-5wpzp   0/2     PodInitializing   0          1s
aiohttp-service-99857644c-5wpzp   1/2     Running           0          2s
aiohttp-service-99857644c-5wpzp   2/2     Running           0          3s
aiohttp-service-99857644c-2gd7b   0/2     Pending           0          0s
aiohttp-service-99857644c-2gd7b   0/2     Pending           0          0s
aiohttp-service-99857644c-2gd7b   0/2     Init:0/1          0          0s
aiohttp-service-99857644c-2gd7b   0/2     PodInitializing   0          2s
aiohttp-service-99857644c-2gd7b   1/2     Running           0          3s
aiohttp-service-99857644c-2gd7b   2/2     Running           0          3s
```

<img width="1386" alt="Screenshot 2023-08-16 at 10 43 29" src="https://github.com/envoyproxy/envoy/assets/95422414/d7b38e81-a545-4834-b108-f6e2aa76f6e4">

**Comment by palmobar** [comment]
I started playing a bit more with pods around and found something very very weird, so where there is no slow start defined and I scale up deployment in a succession 1 -> 2 -> 3 you can see that the pods receive immediatelly their fair share of traffic like so (these tails on the left are due to how prometheus calculates each data point based on a time span of a range vector):
<img width="918" alt="without-slow-start" src="https://github.com/envoyproxy/envoy/assets/95422414/3f263da1-e2fc-4da3-a560-775b77f79300">

Now when slow start is in effect I'd expect to see something similar but the new pods would be ramping up slowly (over the slow start window) but instead I see this behaviour:
<img width="755" alt="with-slow-start" src="https://github.com/envoyproxy/envoy/assets/95422414/c9a006a7-2a62-47dd-ac86-f8a340c89b96">

and this:
<img width="935" alt="Screenshot 2023-08-16 at 13 47 20" src="https://github.com/envoyproxy/envoy/assets/95422414/8372557e-9b1a-4e2e-8cc6-3cd31ffc4980">

so it looks like when a new pod joins the cluster the older pod suddenly receives more traffic which is very very unexpected. Also when 1 pod is running and 2nd one joins then it immediatelly receives 50% of the traffic. When the 3rd pod joins then it ramps up slowly but the older pod all of a sudden is getting circa. 60% of the traffic (the second pod is receiveing around 30% of the traffic) and the third pod is receiving the rest while slowly ramping up.

**Comment by svenmueller** [comment]
We are seeing the same behavior (version 1.17.2)

**Comment by nezdolik** [comment]
@palmobar looking at your config you are using locality weighted load balancing. Are the 3 pods from the experiment in the same locality?

**Comment by palmobar** [comment]
@nezdolik sorry for the slow answer but I was on family holidays with little access to the outside world.

How am I using locality weighted load balancing? In the config I can see `locality_weighted_lb_config": {}` which would mean that it's not set? Last time I was checking weights they're always the same for each pod.

**Comment by nezdolik** [comment]
Hi @palmobar, no worries. Are you able to curl `clusters` admin endpoint on Envoy pod?(E.g. `curl http://{$ENVOY_POD_IP}:8001/clusters`) and verify that all endpoints for the cluster from test belong to same priority and locality? (or attach the output for cluster here so i could verify). 
[LocalityWeighhtedLbConfig](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/cluster/v3/cluster.proto#L595) proto message does not have any fields, so when `locality_weighted_lb_config` field is configured it enables locality weighted load balancing in conjunction with supplied load balancing weights and localities for endpoints: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight

**Comment by palmobar** [comment]
@nezdolik
I was already looking into that before in this ticket here: https://github.com/envoyproxy/envoy/issues/28512

Here is the clusters for the cluster on which I can reproduce the issue. Looks like the envoy port is only on localhost so I did this (I changed the ip addresses). There are three pods in the cluster:

```
$ istioctl dashboard envoy aiohttp-service-99857644c-4g94z --browser=false
$ curl -LSs http://localhost:15000/clusters | grep aiohttp-service
outbound|8080||aiohttp-service.default.svc.cluster.local::observability_name::outbound|8080||aiohttp-service.default.svc.cluster.local
outbound|8080||aiohttp-service.default.svc.cluster.local::default_priority::max_connections::4294967295
outbound|8080||aiohttp-service.default.svc.cluster.local::default_priority::max_pending_requests::4294967295
outbound|8080||aiohttp-service.default.svc.cluster.local::default_priority::max_requests::4294967295
outbound|8080||aiohttp-service.default.svc.cluster.local::default_priority::max_retries::4294967295
outbound|8080||aiohttp-service.default.svc.cluster.local::high_priority::max_connections::1024
outbound|8080||aiohttp-service.default.svc.cluster.local::high_priority::max_pending_requests::1024
outbound|8080||aiohttp-service.default.svc.cluster.local::high_priority::max_requests::1024
outbound|8080||aiohttp-service.default.svc.cluster.local::high_priority::max_retries::3
outbound|8080||aiohttp-service.default.svc.cluster.local::added_via_api::true
outbound|8080||aiohttp-service.default.svc.cluster.local::eds_service_name::outbound|8080||aiohttp-service.default.svc.cluster.local
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::cx_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::cx_connect_fail::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::cx_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::rq_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::rq_error::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::rq_success::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::rq_timeout::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::rq_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::hostname::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::health_flags::healthy
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::weight::1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::region::eu-west-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::zone::eu-west-1b
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::sub_zone::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::canary::false
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::priority::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::success_rate::-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::local_origin_success_rate::-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::cx_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::cx_connect_fail::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::cx_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::rq_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::rq_error::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::rq_success::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::rq_timeout::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::rq_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::hostname::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::health_flags::healthy
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::weight::1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::region::eu-west-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::zone::eu-west-1c
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::sub_zone::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::canary::false
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::priority::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::success_rate::-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::local_origin_success_rate::-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::cx_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::cx_connect_fail::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::cx_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::rq_active::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::rq_error::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::rq_success::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::rq_timeout::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::rq_total::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::hostname::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::health_flags::healthy
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::weight::1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::region::eu-west-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::zone::eu-west-1c
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::sub_zone::
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::canary::false
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::priority::0
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::success_rate::-1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::local_origin_success_rate::-1
```

The wights are:
```
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.1:8080::weight::1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.8:8080::weight::1
outbound|8080||aiohttp-service.default.svc.cluster.1.2.3.4:8080::weight::1
```

**Comment by nezdolik** [comment]
Ok, so clearly there are multiple localities (zones) involved in this scenario. Will you be able to correlate which endpoint from the test/graph belonged to which zone? That would help to better craft the test to reproduce the issue programmatically. 
Slow start does not work perfectly with cross priority, cross locality load balancing.

**Comment by palmobar** [comment]
I think you might be onto something here, look at this graph:

<img width="996" alt="Screenshot 2023-09-27 at 17 52 31" src="https://github.com/envoyproxy/envoy/assets/95422414/5f7d6de8-3f5f-45a0-863e-15f367abbc92">

The first two lines are:

* **red**: zone _eu-west-1c_
* **green**: zone _eu-west-1a_

The third line (a new pod introduced to the cluster:

* **teal**: zone _eu-west-1b_

this line is jumping up to receive 33% of the traffic immediatelly (no warmup period applies) but the other pods decrease by equal amounts so it's like warmup was never in effect.

The fourth line (purple) is the same zone as the red line:

* **purple**: zone _eu-west-1c_

You can see that the red line "jumps up" but also the purple line will get more traffic than the other pods, in here it looks like the wormup is in effect (to a degree at least).

The gold line is the same zone as purple and red:

* **gold**: zone _eu-west-1c_

In here it looks like warmup is in effect, red and. purple pods "jump up" (same zone) other pods gradually lose share of the traffic.

**Comment by palmobar** [comment]
@nezdolik so am I right in thinking that istio turns on [locality load balancing](https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/) by default which causes the slow start to be calculated separately for each locality?

After adjusting my `DestinationRule` in the following way the slow start feature works exactly as described:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  name: aiohttp-service
  namespace: default
spec:
  host: aiohttp-service
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
      simple: ROUND_ROBIN
      warmupDurationSecs: 180s
```

**Comment by nezdolik** [comment]
@palmobar i know little about Istio, but looking at Envoy config yes, locality weighted load balancing does not work well with slow start for your specific scenario.

**Comment by palmobar** [comment]
@nezdolik should the documentation be updated to reflect that? It's not obvious for us mere mortals ;>

**Comment by nezdolik** [comment]
@palmobar definitely the docs need to be updated. Will do it next week.

**Comment by briansonnenberg** [comment]
@nezdolik To understand fully, is it an implementation issue or a design limitation that locality lb does not work with slow start in this case?
