### ISSUE TITLE
SSH proxy support for SSH inspection

### ISSUE THREAD

**Issue by BenAgai** [envoyproxy/envoy#29029]
Hi,
I'm considering using Envoy proxy for security operations over web/SSH traffic.
Regarding SSH, I wanted to ask what is the procedure to support SSH proxy via Envoy?

I would like to perform SSH inspection, and wanted to know if you have any recommendations on how it can be done with Envoy.
In addition, Is it possible for it to be done via runtime plugins (in Go for example) to avoid re-compiling Envoy?

Thanks!,
Ben

**Comment by yanavlasov** [comment]
Envoy does not currently support termination of SSH protocol. At best you can implement a TCP proxy without inspection.

Yes, it is possible to add a network filter that can terminate SSH and allow deep inspection. Envoy does support HTTP filters written in Go, but not Network filters, yet. You can write a network filter in C++ or languages that WASM supports.

**Comment by yanavlasov** [comment]
@doujiang24  @wangfakang  @StarryVae  For Go support of Network filers 

There are no plans to support SSH proxy that I'm aware of

**Comment by StarryVae** [comment]
i think Go extension has alreay supports network filters.cc @doujiang24
