### ISSUE TITLE
Questions about xDS API flow

### ISSUE THREAD

**Issue by whutwhu** [envoyproxy/envoy#29043]
There are two common xDS API flows:

1. Fetch from Listener and Cluster as root during startup, followed by fetching dependent RouteConfiguration and ClusterLoadAssignment configurations.
2. On-demand vhds and cds updates using the on demand filter with :authority header. The flow involves vhds triggering cds, and cds is driven by routes defined in vhds.

Question 1:
For 1. If there are 1000 listeners, will the Envoy instance fetch all 1000 listeners, potentially resulting in Envoy listening on 1000 ports?

Question 2:
For 2. Why can't we trigger RDS based on vhds, creating the flow: vhds (VirtualHost) -> RDS (RouteConfiguration) -> CDS (Cluster) -> EDS (ClusterLoadAssignment)? Instead of incorporating all route data into vhds, segregating the routing information into a separate layer can offer improved maintenance and easier updates.

**Comment by yanavlasov** [comment]
On 1 yes, Envoy will fetch all listeners and listen on all their ports.

@adisuissa to comment on the 2nd question.

**Comment by whutwhu** [comment]
@yanavlasov @adisuissa thank you for the information!

**Comment by whutwhu** [comment]
For 2. I'm curious whether it's possible to utilize LDS in a setup where RDS is initiated by LDS, deviating from the conventional flow that starts with VHDS. This would result in the sequence: LDS -> RDS -> CDS -> EDS.
In a scenario involving 1000 RouteConfiguration, each one named after a service, the difficulty arises in applying LDS. This involves creating a Listener entry with a fictional port, enabling the establishment of 1000 filter chains. Each filter chain would be named according to its respective service name, thereby aligning with the names of corresponding RDS instances. Is this approach viable, which is related with Matching Filter Chains in Listener?
