### ISSUE TITLE
Bug found in dns_cache_impl for dynamic_forward_proxy

### ISSUE THREAD

**Issue by yiyibaoguo** [envoyproxy/envoy#29087]
*Title*: *503 response with no_healthy_upstream when multiple request with same authority header at the same time*

*Description*:
>When multiple request with same authority header, sometimes some request return 503 response with no_healthy_upstream from envoy. No_healthy_upstream 503 is not expected.

*Repro steps*:
> multiple request with same authority header at the same time
required to reproduce the bug.

*Config*:
>      "filter_chains": [
        {
          "filters": [
            {
              "name": "envoy.filters.network.http_connection_manager",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                "stat_prefix": "test",
                "rds": {
                  "route_config_name": "rds_route",
                  "config_source": {
                    "resource_api_version": "V3",
                    "path_config_source": {
                      "path": "/envoy/config/rds.json",
                      "watched_directory": {
                        "path": "/envoy/config/"
                      }
                    }
                  }
                },
                "request_timeout": "15s",
                "http_filters": [
                  {
                    "name": "envoy.filters.http.dynamic_forward_proxy",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig",
                      "dns_cache_config": {
                        "name": "dynamic_forward_proxy_cache_config",
                        "host_ttl": "7200s"
                      }
                    }
                  },
                  {
                    "name": "envoy.router",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                    }
                  }
                ],
              }
            }
          ]
        }
      ]

*code snapshot*:
Base on below work flow, it seems to be invalid order for setAddress and runAddUpdateCallbacks function:
**worker thread 1:**
    1) receive request with authority header 192.20.20.20:8285
    2) cache miss and trigger main thread load dns cache
    3) setAddresses --- here first_resolve_complete_ is set true
    if worker thread 2 is try to loadDnsCacheEntry for the request, cache hit, but run into host info not found situation due to runAddUpdateCallbacks is done after this
    4) runAddUpdateCallbacks

**worker thread 2:**
    1) receive request with authority header 192.20.20.20:8285
    2) cache hit --- condition 1: host found from dns cache & condition 2: firstResolveComplete is true
    3) host not found during router filter decode stage and 503 response with unhealthy_upstream is return

**'first_resolve_complete_ flat is set true' should occur after host info updated done by runAddUpdateCallbacks**
[code analysis snapshot.pptx](https://github.com/envoyproxy/envoy/files/12368119/code.analysis.snapshot.pptx)

**Comment by yanavlasov** [comment]
@yanjunxiang-google as area owner

**Comment by belyalov** [comment]
+1

Sounds like a race between thread local LB and DNSResolveComplete callback

**Comment by yiyibaoguo** [comment]
https://github.com/yanjunxiang-google could you help check it?

**Comment by yiyibaoguo** [comment]
@yanjunxiang-google 
Thanks for your reply and support, I will prepare the code change later.

**Comment by coolg92003** [comment]
hi @yanjunxiang-google,
I have created an PR for this issue.
Please have a look and let me know for any comments
https://github.com/envoyproxy/envoy/pull/29764
thanks
Cliff

**Comment by yiyibaoguo** [comment]
@yanjunxiang-google 
Based on the change [](https://github.com/envoyproxy/envoy/pull/29764)
we see test case failure. Due to limit knowledge for these part, when you get time, could you help check if the code change is ok or not? if yes, help give your comments about how to change the test part. thanks!

**Comment by yiyibaoguo** [comment]
https://github.com/envoyproxy/envoy/pull/30506
