### ISSUE TITLE
Hot restart should support configurable socket address

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#2908]
Hot restart currently uses a hard-coded address in the abstract namespace for unix domain sockets. This has the advantage that it allows hot-restart between different containers. However, it has the disadvantage that there are no permissions on abstract namespace unix domain sockets.

Envoy should support configuring a filesystem path for it's hot-restart UDS so that normal filesystem permissions can be used. This would most-likely be specified as a command-line argument.

*Relevant Links*:
http://man7.org/linux/man-pages/man7/unix.7.html

**Comment by mattklein123** [comment]
@ggreenway I'm just going to mark this help wanted. If you plan on working on this can you remove the tag and assign it?

**Comment by ggreenway** [comment]
I'll probably get to it eventually, but not for awhile. I'll leave it help-wanted for now, and claim if/when I'm ready to work on it.

**Comment by mk46** [comment]
Hi @ggreenway, Is this feature ready to implement or implemented? If not then I would like to implement it.

**Comment by ggreenway** [comment]
I don't believe anybody is working on it. Feel free to work on it.

**Comment by mk46** [comment]
@ggreenway Hi, Is it good to stay with hardcoded added if it's not specified by command-line argument?
 CL argument should take file permission along with path?

**Comment by ggreenway** [comment]
> @ggreenway Hi, Is it good to stay with hardcoded added if it's not specified by command-line argument?

Yes. By default, it must be compatible with older versions of envoy.

> CL argument should take file permission along with path?

Yes, that makes sense to me.

**Comment by mk46** [comment]
@ggreenway Please take a look at #12712.
