### ISSUE TITLE
envoy_reloadable_features_oauth_header_passthrough_fix deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#29097]
Your change #23489 (outh2: passthrough of authorization header when filter is matched) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @timo-42

**Comment by kanurag94** [comment]
@alyssawilk @timo-42 I can take up the cleanup if no one else is working on it. Thanks

**Comment by timo-42** [comment]
I will work on it, today or tomorrow.
