### ISSUE TITLE
repo reorg: codify if/when core code can depend on extensions

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2910]
We likely can never compile out tcp_proxy and hcm. Need to codify this and check in CI.

**Comment by htuch** [comment]
Ideally we can have `check_format` validate this via Bazel dep graph analysis.

**Comment by alyssawilk** [comment]
should we just leave them in core and say they're required plugins, or leave them in extensions and just comment / doc that they're special cased?
