### ISSUE TITLE
v1.27.0 fails to build golang network filter

### ISSUE THREAD

**Issue by or-adar** [envoyproxy/envoy#29168]
I'm experimenting with the new golang network filter in v1.27.0

I've created some baisc repo that implement all of the necessary functions and interfaces
and I got to the point where I want to start building the project to ".so" file to be used with my envoy instance,

however, when I try to build my project in c-shared mode I'm getting the following error:
`/go/pkg/mod/github.com/envoyproxy/envoy@v1.27.0/contrib/golang/filters/network/source/go/pkg/network/capi.go:30:10: fatal error: api.h: No such file or directory`,
the file is indeed not a part of the module when imported (although it does appear to exist in this repo but not when imported)
could there be something that I'm missing?

**Comment by RyanTheOptimist** [comment]
cc: @doujiang24 @wangfakang

**Comment by antJack** [comment]
seems that this fix pr forget the `contrib/golang/filters/network/source/go/pkg/network/capi.go` file, https://github.com/envoyproxy/envoy/pull/28722/files
