### ISSUE TITLE
Send ratelimit request to ratelimit service on response flow with hits_addend

### ISSUE THREAD

**Issue by PeterL328** [envoyproxy/envoy#29161]
*Title*: Send ratelimit request to ratelimit service on response flow with hits_addend for reporting purpose.

*Description*:
Context: We have a use case that involves internally using the OpenAI API and using Envoy to send the request to OpenAI servers. We want to [rate-limit on the # token-consumed](https://platform.openai.com/docs/guides/rate-limits/overview) per each OpenAI API request on a user-level. The token consumed is calculated by the token used in request + response body. The total token consumed (request + response) will be sent as part of the response back from OpenAI API so we would like to take this token-consumed number and send to the ratelimit sidecar via the ratelimit filter (using the [hits_addend](https://github.com/envoyproxy/envoy/pull/28939) field). 

We think to achieve the above, three work items need to be completed:
1) Update ratelimit filter to support sending hits_addend
- I've started by landing this [PR](https://github.com/envoyproxy/envoy/pull/28939) so ratelimit grpc client supports hits_addend.
2) Update ratelimit filter so it can be configured to send request to sidecar on response flow.

cc: @sc0ttbeardsley @JuniorHsu @fishcakez

Any thoughts on the problem?
Do you think the proposed solution is a good approach or are there better ways to achieve?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
cc: @esmet @mattklein123 @yanavlasov

**Comment by lizzzcai** [comment]
Hi @PeterL328 , as discussed [here](https://github.com/envoyproxy/envoy/issues/12969#issuecomment-1691292079), do you think rate limiting on the sum of `Prompt text and count` and `The max_tokens` (max number of generated token) in the `request` should be simple and enough here? 

For item 3, for example I have a limit of 500 tokens/min, there is a request with 300 tokens in prompts and max_tokens: 300 (total token 600), the request should be rejected. However, if the max_tokens is 200 (total tokens: 500), it should proceed.

**Comment by yanavlasov** [comment]
@PeterL328 Can you help me understand the proposal better, please? If I understand it correctly, you are proposing that each request has a cost which is computed by the server and sent back to Envoy in the response. The rate limit filter needs to report this cost to the rate limiting service, so it can properly update the amount of used cost for the descriptor. Is this correct?

**Comment by PeterL328** [comment]
Hi @yanavlasov

I've removed the 3rd bullet point in my original post since I believe it's not needed anymore. but the first two points still I think is required.

Yea the full request cost (calculated by counting the token in the request body and the token in the response body) is only known when we get the response back from OpenAI. We want to report this cost to the ratelimit service (sidecar).

Currently ratelimit filter will only report cost to the sidecar on request flow. I believe we want to report on the response flow.

**Comment by PeterL328** [comment]
hi @lizzzcai,
I've response to your question in the other thread. I think using the `max_tokens` is fine but it will not be accurate as I think that is just to set an upper bound of what OpenAI can use for the response body.

**Comment by yanavlasov** [comment]
I see. I think what you are looking for is better handled by the new rate limit quota service, since it already has load reporting built in, but it is still not completed. Adding it to the RLS will make it even less efficient, since it will now cost 2 RPCs per request.

If you want to proceed with this, then it a new service needs to be defined (or existing service extended with a new method, not sure if this is supported for backward compatibility) with a new method to report load. Otherwise you have a response that needs to be discarded.

Also note that rate limiting service as defined today is unary. It means that load report will go a different server. If the load report needs to go to the same server that received the first request, then the API needs to be changed to streaming.

**Comment by lizzzcai** [comment]
> hi @lizzzcai, I've response to your question in the other thread. I think using the `max_tokens` is fine but it will not be accurate as I think that is just to set an upper bound of what OpenAI can use for the response body.

Thanks @PeterL328 for your response. Agree that the total consumed token in the response will be more accurate. In your use case, you also expect the reporting which will require accurate data. For my use case, I just need to rate limit the TPM(token per min) so the upper bound of the request should be enough for us.

**Comment by ChuckCrawford** [comment]
We are particularly interested in that first work item: 

> Update ratelimit filter to support sending hits_addend

Which would enable configuring [RateLimit](https://www.envoyproxy.io/docs/envoy/v1.27.0/api-v3/config/route/v3/route_components.proto.html#config-route-v3-ratelimit) messages like so:

```yaml
      rate_limits:
        - actions:
            - 
            - 
          hits_addend: 4
          stage: 1
        - actions:
```

To enable counting a single "expensive" request as multiple hits.

A few quick questions:
* Should we open a separate issue to track this [since it seems less complex than the full ask here]?
* Since @PeterL328 has done some of the initial work under https://github.com/envoyproxy/envoy/pull/28939; is the remaining work something a new contributor might be able to handle? Is there another way we could help?

**Comment by PeterL328** [comment]
Hi @ChuckCrawford,

> Should we open a separate issue to track this [since it seems less complex than the full ask here]?

I think it's probably better to open a new issue for you ask. This issue is more about discussing making calls to ratelimit sidecar on response flow.

> Since @PeterL328 has done some of the initial work under https://github.com/envoyproxy/envoy/pull/28939; is the remaining work something a new contributor might be able to handle? Is there another way we could help?
You can wait for someone to pickup your issue but it may take long time. If you want it in open source sooner, probably can get started on your own. Whoever gets assigned to you issue maybe can help, you can also tag me for assistance.

**Comment by PeterL328** [comment]
@yanavlasov 

Just to be clear, when you say service in your previous post. I assume you mean envoy filters not sidecar service correct?

> I think what you are looking for is better handled by the new rate limit quota service, since it already has load reporting built in, but it is still not completed

I see, do you mean this one https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_quota_filter.html?

> Adding it to the RLS will make it even less efficient, since it will now cost 2 RPCs per request.

The second request we think will be made during the response flow (i.e during encoding) and maybe can be non-blocking since we discard the ratelimit response from the sidecar.

Is my understanding correct that both ratelimit filter and ratelimit quota filter can talk to the same [ratelimit sidecar](https://github.com/envoyproxy/ratelimit) but additional work is required to support my use case with ratelimit quota filter?

**Comment by yanavlasov** [comment]
> @yanavlasov
> 
> Just to be clear, when you say service in your previous post. did you mean envoy filter or sidecar service? If you meant service not filter, is the rate limit quota service based off of [ratelimit sidecar](https://github.com/envoyproxy/ratelimit)?
> 
I meant sidecar service. The the rate limit quota service is not based on the https://github.com/envoyproxy/ratelimit it is a different API altogether. The sidecar service is not yet developed unfortunately.

> > I think what you are looking for is better handled by the new rate limit quota service, since it already has load reporting built in, but it is still not completed
> 
> I see, do you mean this one https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_quota_filter.html?
> 
> > Adding it to the RLS will make it even less efficient, since it will now cost 2 RPCs per request.
> 
> The second request we think will be made during the response flow (i.e during encoding) and maybe can be non-blocking since we discard the ratelimit response from the sidecar.

Sure. But this will need new API and I'm unsure the existing rate limit API can be changed in a backward compatible way.

> 
> Is my understanding correct that both ratelimit filter and ratelimit quota filter can talk to the same [ratelimit sidecar](https://github.com/envoyproxy/ratelimit) but additional work is required to support my use case with ratelimit quota filter?

I think rate limit quota filter will need a new sidecar service. I'm unsure how much of the existing ratelimit sidecar can be reused.

**Comment by ishaan-jaff** [comment]
@PeterL328 @lizzzcai @yanavlasov @ChuckCrawford 

i'm the maintainer of LiteLLM we allow you to **maximize your throughput/increase rate limits** -  load balance between multiple deployments (Azure, OpenAI)
**I believe litellm can be helpful here - and i'd love your feedback if we're missing something** 

Here's how to use it
Docs: https://docs.litellm.ai/docs/routing


```python
from litellm import Router

model_list = [{ # list of model deployments 
    "model_name": "gpt-3.5-turbo", # model alias 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-v-2", # actual model name
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-functioncalling", 
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "vllm/TheBloke/Marcoroni-70B-v1-AWQ", 
        "api_key": os.getenv("OPENAI_API_KEY"),
    }
}]

router = Router(model_list=model_list)

# openai.ChatCompletion.create replacement
response = router.completion(model="gpt-3.5-turbo", 
                messages=[{"role": "user", "content": "Hey, how's it going?"}])

print(response)
```

**Comment by PeterL328** [comment]
Going to close the issue for now. 
Internally we have an envoy filter that makes grpc calls to ratelimit sidecar on response flow but seems it will be tricky to open source it as it's a very specific need from us.

Maybe someone can open another issue to add support for hits addend in ratelimit envoy filter since kind of a separate issue.

**Comment by RyoYang** [comment]
@PeterL328 Peter, thanks for your contribution on this. Could you please give us a simple example on how to use the hits_addend to achieve TPM limite in rate limit sidecar? Thanks!

**Comment by zirain** [comment]
@RyoYang may https://github.com/envoyproxy/envoy/pull/34184 help you.

**Comment by brightbyte** [comment]
> [@PeterL328](https://github.com/PeterL328) Peter, thanks for your contribution on this. Could you please give us a simple example on how to use the hits_addend to achieve TPM limite in rate limit sidecar? Thanks!

I am also interested in this for use with the Wikipedia API. Some of our endpoints can be very expensive depending on the request parameters, and it would be useful to account for that in rate limiting.

Envoyproxy accepts hits_addend in the rate limit configuration, and the RLS protocol also suppotrs it, but I can't get envoy to actually use the information from the config and send it to the rate limit service...
