### ISSUE TITLE
Performance issue with Balsa Parser

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#29203]
*Title*: Performance issue with Balsa Parser

*Description*:

Since we are going to migrate from http-parser to Balsa Parser (#21245, #28896), I did some quick benchmarking recently and found that Balsa Parser is 10% slower than the current http-parser implementation, though it claims to have similar performance.

```
# http-parser
All done 5496764 calls (plus 64 warmup) 3.493 ms avg, 18322.5 qps
# Balsa Parser
All done 5058443 calls (plus 64 warmup) 3.795 ms avg, 16861.4 qps
```

The benchmarking is performed with Envoy running in a pinned single thread, echoing back 1kB headers with Fortio from 64 concurrent connections, no filter except HCM and HTTP router, full CPU load.

I also made a draft [commit](https://github.com/envoyproxy/envoy/commit/2c3a7a768f8fd4d8e92c06574eda936e6956b67e) with llhttp implementatoin, a successor of http-parser, which has been mentioned a lot of times, e.g., #5155, #9033 and #15814. The result looks good.

```
# http-parser
All done 5496764 calls (plus 64 warmup) 3.493 ms avg, 18322.5 qps
# llhttp
All done 5626763 calls (plus 64 warmup) 3.412 ms avg, 18755.8 qps
```

Note that I did **not exactly** follow the [What are best practices for benchmarking Envoy?](https://www.envoyproxy.io/docs/envoy/latest/faq/performance/how_to_benchmark_envoy.html) article when collecting this benchmarking data.

I know that enable Balsa Parser will let us support some requested features, do you think we can add an API option to support different parsers instead of using runtime guard to introduce a new one and deprecate the old one?

**Comment by RyanTheOptimist** [comment]
cc: @bencebeky @birenroy

**Comment by RyanTheOptimist** [comment]
cc: @diannahu
