### ISSUE TITLE
How to get more QUIC stats?

### ISSUE THREAD

**Issue by triplewy** [envoyproxy/envoy#29220]
I am currently comparing Envoy QUIC performance with that of our Nginx QUIC implementation and Envoy performs slightly worse in terms of download speed. In order to debug Envoy, I'd like to access more QUIC connection stats, particularly congestion-control related stats such as pacing_rate, estimated_bandwidth, etc.

I noticed that Envoy has a [tcp stats transport socket extension](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tcp_stats/v3/tcp_stats.proto#extension-envoy-transport-sockets-tcp-stats) that gets various TCP socket metrics. Is there a way to get equivalent QUIC metrics?

The Envoy Extension API seems a bit hard to work with QUIC because a QUIC connection can essentially only be accessed via HTTP filters; Network filters do not provide access to the QUIC connection after connection creation ([Documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchain)).
>For QUIC listeners, network filters other than HTTP Connection Manager (HCM) can be created, but due to differences in the connection implementation compared to TCP, the onData() method will never be called. Therefore, network filters for QUIC listeners should only expect to do work at the start of a new connection (i.e. in onNewConnection()). HCM must be the last (or only) filter in the chain.

While the HTTP filter API provides a way to get the underlying Network Connection via the [StreamFilterCallbacks interface](https://github.com/envoyproxy/envoy/blob/main/envoy/http/filter.h#L336), the [Network Connection interface](https://github.com/envoyproxy/envoy/blob/main/envoy/network/connection.h#L81) is quite limited. The Network Connection interface only provides functions to get `lastRoundTripTime` and `congestionWindowInBytes`.

Thus, in order to get more QUIC stats to debug, would I have to modify the Network Connection interface to provide a function to get more connection stats?

**Comment by RyanTheOptimist** [comment]
cc: @jmarantz @danzh2010 @alyssawilk @RyanTheOptimist

**Comment by danzh2010** [comment]
I'm curious about the comparison. Nginx QUIC and QUICHE might use different congestion control and flow control properties like initial cwnd, flow control window. What's your experiment setup?
 
Today you should be able to use a network filter to get estimated smooth RTT and bandwidth from the connection's StreamInfo object after the Connected event. 

And we are working on exporting QUIC transport level stats into a protobuf. But the initial plan is to do it in an internal extension point.

**Comment by danzh2010** [comment]
cc @steveWang

**Comment by triplewy** [comment]
> I'm curious about the comparison. Nginx QUIC and QUICHE might use different congestion control and flow control properties like initial cwnd, flow control window. What's your experiment setup?

We are currently instrumenting Nginx and Envoy more to get more transport stats such as pacing rate, etc. Both Nginx and Envoy are using BBR and both are using the Google QUICHE library. Will update you more as we get more metrics.

> Today you should be able to use a network filter to get estimated smooth RTT and bandwidth from the connection's StreamInfo object after the Connected event.

In the future, is it possible to add an interface to get all the socket info rather than separate methods for RTT and Cwnd? Currently, the connection implementation calls the TCP_INFO getsockopt to get socket info, so I think it could be doable to simple return the entire TCP_INFO struct rather than a single field?

**Comment by triplewy** [comment]
@danzh2010 After doing a lot of congestion control instrumentation and monitoring in Envoy, we were unable to correlate pacing rate with client download speed which is quite befuddling. One thing we did find is that the Envoy metric `envoy_listener_udp_downstream_rx_datagram_dropped` is very high. However, we have been unable to correlate this metric with the udp queue metrics available from `/proc/net`

**Comment by triplewy** [comment]
I also have a question on `packets_to_read_to_connection_count_ratio` [(Documentation)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/quic_config.proto#envoy-v3-api-msg-config-listener-v3-quicprotocoloptions)
>([UInt32Value](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#uint32value)) A multiplier to number of connections which is used to determine how many packets to read per event loop. A reasonable number should allow the listener to process enough payload but not starve TCP and other UDP sockets and also prevent long event loop duration. The default value is 32. This means if there are N QUIC connections, the total number of packets to read in each read event will be 32 * N. The actual number of packets to read in total by the UDP listener is also bound by 6000, regardless of this field or how many connections there are.

Each listener worker in our setup has around 3k active QUIC connections. If the upper bound is 6000, then would that lead to only 2 UDP packets read per event loop. Is this intended behavior?

**Comment by danzh2010** [comment]
> 

> Each listener worker in our setup has around 3k active QUIC connections. If the upper bound in packets read is 6000, then would that lead to only 2 UDP packets read per event loop. Is this intended behavior?

In this case you may want a higher Envoy concurrency to spread out the connections. Reading processing too many connections on 1 worker will make your event loop long.

**Comment by danzh2010** [comment]
> @danzh2010 After doing a lot of congestion control instrumentation and monitoring in Envoy, we were unable to correlate pacing rate with client download speed which is quite befuddling. One thing we did find is that the Envoy metric `envoy_listener_udp_downstream_rx_datagram_dropped` is very high. However, we have been unable to correlate this metric with the udp queue metrics available from `/proc/net`. We have GSO and GRO both turned on for UDP.

envoy_listener_udp_downstream_rx_datagram_dropped means packets dropped in kernel receive buffer. I don't know if packet drops are reported to `/proc/net`, but I think you can spot UDP receive error in `netstat`. You may want to config SO_RCVBUF on the listener socket with a larger value.

**Comment by danzh2010** [comment]
And GRO is not very helpful for an egress heavy server.

**Comment by triplewy** [comment]
> In this case you may want a higher Envoy concurrency to spread out the connections. Reading processing too many connections on 1 worker will make your event loop long.

Currently we set the concurrency to be 1 thread per CPU core. Is there any reason to cap the number of packets read to 6000? The documentation does not give explanation for this number.

**Comment by danzh2010** [comment]
> > In this case you may want a higher Envoy concurrency to spread out the connections. Reading processing too many connections on 1 worker will make your event loop long.
> 
> Currently we set the concurrency to be 1 thread per CPU core. Is there any reason to cap the number of packets read to 6000? The documentation does not give explanation for this number.
> 

1 worker per CPU is sensible. But this also means you are either running the machine too hot (what's the QPS?), or not using QUIC's multiplexing effectively. In Envoy both QUIC and TCP limit the payload each connection gets to process in each event loop to make the event loop duration short (< 1ms). A long duration mean delay in timed events and I/O.

> Edit: After increasing the concurrency 4x we still found the download speed did not match Nginx. Moreover, we still see `envoy_listener_udp_downstream_rx_datagram_dropped` in the thousands per second but cannot see any abnormal output from `ss` or `netstat`. `netstat` shows only tens of receive errors for all UDP sockets. At this point, I'm at a loss at what to track because the congestion control paramaters between Envoy and Nginx are practically the same and artificially increasing Envoy's initial cwnd in order to boost the pacing rate does not lead to any better results. It makes me think that the issue is on the receive side, especially considering the high `envoy_listener_udp_downstream_rx_datagram_dropped`. But we cannot confirm any high UDP drops through linux tools.
> 
> When using `ss -uln`, we can see that the Send-Q is always 0 for all listeners but Recv-Q periodically has numbers in low thousands. Does this mean that Envoy is not processing UDP rx packets fast enough?

Did you observe high loss rate on client side if your client can export that?  
Did you config SO_RECVBUF socket option? envoy_listener_udp_downstream_rx_datagram_dropped is more a result of small receive buffer. Most kernel's UDP receive buffer has small default value, i.e. 32kB, whereas a ideal listening UDP socket should have ~O(Mb) receive buffer.

**Comment by danzh2010** [comment]
Also before diving into congestion control parameters, is your initial flow control window for stream and connection in Envoy line up with Nginx?

**Comment by triplewy** [comment]
@danzh2010 After discussion with colleagues, we think the issue may be more on the sending side. Our QPS per Envoy instance is around 700 qps. We do not see much loss from the client side, though we do see some retransmits from the sending side, albeit the median retransmit bytes is 0, whereas we see a clear performance difference for the median request so I don't think it's a retransmit issue either. The flow control settings are all default, but I'm assuming flow control would not impact the sending side?

The egress rate per Envoy instance is around 150 mbps, which is pretty small for the amount of QPS. But the requests that do have the biggest performance gap are the requests with payload that is higher than a few KB. For instance, the most impacted request that we see has an average payload between 40-100KB.

I think the issue may be more on the sending side because we set the initial cwnd to be 256 for Envoy (to trigger artificially high pacing rate), and see that the client receives the entire response body (for the 100KB response-size request) in less time than the RTT between the client and Envoy. This suggests that Envoy does not need to wait for an ACK to send the entire payload and thus the issue may be purely how fast Envoy can send the packets.

We are planning to setup a testbed with larger request payloads to further test Envoy's send capabilities. In any case, would it also be possible to set up a call to discuss this in more depth? Our team deals with a lot of QUIC traffic and we are heavily invested in making the move from Nginx to Envoy work so we want to fix this issue.

**Comment by danzh2010** [comment]
> @danzh2010 After discussion with colleagues, we think the issue may be more on the sending side. Our QPS per Envoy instance is around 700 qps. We do not see much loss from the client side, though we do see some retransmits from the sending side, 

What is sending side? Envoy? I was suspecting packets get dropped in Envoy recv-Q, so I was interested in packet retransmission by the client. 

> I think the issue may be more on the sending side because we set Envoy's initial cwnd to be 256 (to trigger artificially high pacing rate), and see that the client receives the entire response body (for the 100KB response-size request) in less time than the RTT between the client and Envoy. This suggests that Envoy does not need to wait for an ACK to send the entire payload and thus the issue may be purely how fast Envoy can send the packets.
> 

How did set the initial cwnd for QUIC? We internally did cwnd boostrapping via a network filter. I'm wonder if your approach indeed takes effect or not.

> We are planning to setup a testbed with larger request payloads to further test Envoy's send capabilities. In any case, would it also be possible to set up a call to discuss this in more depth? Our team deals with a lot of QUIC traffic and we are heavily invested in making the move from Nginx to Envoy so we want to fix this issue.

Sure thing! I can also loop in QUIC folks more involved in congestion control. But I'd like to know more about the experiment setup.

**Comment by danzh2010** [comment]
>  The flow control settings are all default, but I'm assuming flow control would not impact the sending side?

You are right, Envoy's flow control shouldn't affect egress performance.

**Comment by triplewy** [comment]
> What is sending side? Envoy? I was suspecting packets get dropped in Envoy recv-Q, so I was interested in packet retransmission by the client.
Yes Envoy is sending side. Perhaps there are some packets dropped in recv-q, we are taking a look at that, but I don't think that's the root cause. Also the client does not show higher loss for Envoy compared to Nginx.

> How did set the initial cwnd for QUIC? We internally did cwnd boostrapping via a network filter. I'm wonder if your approach indeed takes effect or not.
I forked the google/quiche repo and changed `kInitialCongestionWindow` in quic_constants.h. Now we knew it took into affect as we are logging the pacing rate of each request and could see the pacing rate increase.

> Sure thing! I can also loop in QUIC folks more involved in congestion control. But I'd like to know more about the experiment setup.

Would a time next week work? We are currently doing an AB test on production traffic, comparing Nginx and Envoy side-by-side. Everything is the same apart from the proxies themselves (same nodes, same network, same traffic patterns, etc). We plan on setting up the local testbed by next week too.

**Comment by danzh2010** [comment]
> Would a time next week work? We are currently doing an AB test on production traffic, comparing Nginx and Envoy side-by-side. Everything is the same apart from the proxies themselves (same nodes, same network, same traffic patterns, etc). We plan on setting up the local testbed by next week too.

Let's find a timeslot on Slack with my ID https://envoyproxy.slack.com/team/UDR2MA31P

**Comment by triplewy** [comment]
@danzh2010 Do you have a development guide for google/quiche with Envoy? I'm having trouble generating code symbols in Vscode Dev Container for google/quiche so it makes modifying google/quiche pretty difficult

**Comment by danzh2010** [comment]
> @danzh2010 Do you have a development guide for google/quiche with Envoy? I'm having trouble generating code symbols in Vscode Dev Container for google/quiche so it makes modifying google/quiche pretty difficult

Do you mean building Envoy with modified QUICHE code? You can override the QUICHE dependency via https://bazel.build/external/advanced#overriding-repositories. 

Does this mean the previous result is with unmodified initial cwnd?

**Comment by triplewy** [comment]
@danzh2010 I will check out that bazel documentation, thanks! I was also wondering how you setup your IDE for QUICHE code. I'm a bit confused on how to generate the symbols in Vscode for QUICHE.

> Does this mean the previous result is with unmodified initial cwnd?
The previous result is with modified cwnd. It seems that there is some packet processing delay with Envoy. I was able to do some tests using a load generator and found that Envoy had higher latency for just connect time. We calculated through wireshark and pcap analysis that Envoy had an average latency of 30ms to process the INITIAL packet whereas our Nginx implementation only took an average of 10ms. 

The latency increases as we ramp up the request load. So now I'm trying to instrument QUICHE to measure the packet processing time to see if the issue is QUICHE taking too long to process the packet or Envoy not sending packets fast enough (perhaps an event loop issue).

**Comment by triplewy** [comment]
> 30ms latency from packet observed by wireshared to being processed by Envoy?

Yes. From the INITIAL packet received to INITIAL packet reply, Envoy takes an average 30ms when the request load is around 30qps. I will try to setup proxygen to see if they have similar results because that will give us some open-source to open-source comparison

**Comment by triplewy** [comment]
It appears that the packet processing latency increases in relation to `envoy_listener_worker_downstream_cx_active`. But the CPU usage is not high so I don't think CPU overload is the issue.

**Comment by danzh2010** [comment]
What's the avg number of envoy_listener_worker_downstream_cx_active? 
And could you try to turn off GRO?

**Comment by triplewy** [comment]
In our load test, `envoy_listener_worker_downstream_cx_active` is at 100 because we are running 100 curl commands in parallel to Envoy.

I turned off GRO which decreased curl transfer_time but increased ttfb. Connect time did not change much. I think the issue may be the packet sending logic, perhaps the event loop. To confirm this, I am trying to measure the per-connection processing latency for the INITIAL packet and the time elapsed between receive INITIAL packet and send INITIAL packet.

**Comment by danzh2010** [comment]
Connect time has to do with the handshake. Did you use an async ProofSource?

**Comment by danzh2010** [comment]
And I'd highly recommend fixing `envoy_listener_udp_downstream_rx_datagram_dropped`

**Comment by triplewy** [comment]
> Connect time has to do with the handshake. Did you use an async ProofSource?

We use the default proof_source_config

> And I'd highly recommend fixing `envoy_listener_udp_downstream_rx_datagram_dropped`

In our load testing setup, `envoy_listener_udp_downstream_rx_datagram_dropped` is 0. But in our production environment serving user requests, `envoy_listener_udp_downstream_rx_datagram_dropped` is very high. But to clarify, we are still seeing significant latency difference in our load testing setup between our in-house QUIC implementation and Envoy.

**Comment by danzh2010** [comment]
You can also check event loop using these 2 metrics: https://sourcegraph.com/github.com/envoyproxy/envoy/-/blob/envoy/event/dispatcher.h?L41-42
