### ISSUE TITLE
Ability to log client cipher-suites in SSL

### ISSUE THREAD

**Issue by stew675** [envoyproxy/envoy#29222]
*Title*: *Log the cipher suites a client sends during a SSL/TLS handshake*

*Description*:
This is somewhat similar to the existing DOWNSTREAM_TLS_CIPHER field found here: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage.html

During a TLS handshake a client sends a list of all the TLS ciphers that it supports, and from that a list Envoy SSL library negotiates a suitable ciphers set to establish the connection with the client.

DOWNSTREAM_TLS_CIPHER reports just the negotiated cipher suite, rather than the full set that the client offers.  The full client cipher suite set can be obtained with **SSL_get_client_ciphers(ssl())** 

The proposal is to add a new logging field, (possibly _DOWNSTREAM_TLS_CIPHER_LIST_ ?) and allow that to log a comma separated string of the names of all the cipher suites that the client sends.

The use case for this is to allow for network admins to easily identify client software/applications that are still attempting to use insecure and out of date cipher suites and take remedial action as part of a larger security audit for such.

I have almost completed developing a (internal to our company at present) PR to add this functionality to Envoy, and wanted to know if something like this is already in progress, and if not, whether the wider community find such functionality useful.

[*Relevant Links*:]

https://www.openssl.org/docs/man1.1.1/man3/SSL_get_client_ciphers.html

**Comment by RyanTheOptimist** [comment]
cc: @ggreenway

**Comment by stew675** [comment]
@ggreenway I was digging into the BoringSSL source code investigating an implementation of this, and found that BoringSSL doesn't support the **SSL_get_client_ciphers()** call.  It appears that the client cipher list is processing within the handshake code, but later implementations seem to have actively removed the storage of the client cipher list.

As a result, any change to support this would first need to expand upon BoringSSL's functionality.  We first need to establish why this functionality isn't supported though.  Was that for security concerns?

**Comment by ggreenway** [comment]
I don't work directly on BoringSSL, so I don't have any knowledge about why that chnage was made. Sorry.

**Comment by stew675** [comment]
The following ticket has been logged with the BoringSSL team to determine if SSL_get_client_ciphers() can be implemented in a formal capacity (rather than attempting to use a customised version of BoringSSL).  I'm waiting for an assessment on that to determine if we can proceed with this effort.

https://bugs.chromium.org/p/boringssl/issues/detail?id=648
