### ISSUE TITLE
docs: C++ API release note for extension developers

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#2925]
*Description*:
Add a C++ API release note or version history, preferable with migration notes if desired. The C++ API (those in `include/envoy`) changes frequently and it is hard to catch up if extensions lives outside of envoy repository.

At least a breaking change to extensions (filters, access logs, http tracers, transport sockets, etc) API should be documented.

*Relevant Links*:
#2919

**Comment by htuch** [comment]
@lizan this is a good idea. Can we wait until we have https://github.com/envoyproxy/envoy/issues/2934 done? That way, we can add this without further reducing velocity, since today, many changes that aren't full features don't need to do updates to the docs repo.

**Comment by lizan** [comment]
SGTM. No hurry at all.
