### ISSUE TITLE
Setting the port value dynamically

### ISSUE THREAD

**Issue by nadeshpa** [envoyproxy/envoy#29251]
I am using Envoy as a sni_dynamic_forward_proxy. This proxy does not terminate TLS, it just checks the SNI and forwards the request to that host. All of this is happening on port 443.

But all of my requests are not going to 443, there are some other ports. So I want to use that port while forwarding the request. I found there is an option of `envoy.upstream.dynamic_port` as mentioned here - https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter#dynamic-host-and-port-selection

But is there some example on how to use it?

**Comment by ohadvano** [comment]
Hi, the dynamic port is an option that is controlled by the filter state. That means that you would need to implement some filter that would set that filter state key with the port value for the flows which you wish you override the port for.

**Comment by RyanTheOptimist** [comment]
cc:  @rshriram @lizan

**Comment by nadeshpa** [comment]
I looked at the Lua filters and WASM filters too. 

I think Lua filter operates only on HTTP requests, so not useful in my specific use case. Because I am looking to read the 'Client Hello' in TLS handshake.

For WASM filters - I think they work at network level/ per connection level too.  can they set the filter state `envoy.upstream.dynamic_port` ? Does it need this PR - https://github.com/envoyproxy/envoy/pull/29320 to go in to support that?

**Comment by kyessenov** [comment]
We can use #29320 for Wasm, but we also need to register the filter state to allow its dynamic creation. 
I've started populating it https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_filter_state#well-known-filter-state, but I didn't see the one mentioned.

We can also add it to Lua and Go - it's the same principle.
