### ISSUE TITLE
should go extension support header operation in body phase?

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#29260]
*Title*: *should go extension support header operation in body phase?*

*Description*:
inspired by #28587 , should go extension also support header operation in body phase? since some filters may need to change headers according to some content from body.

**Comment by StarryVae** [comment]
cc @doujiang24

**Comment by doujiang24** [comment]
yep, I do think the golang extension already support it.
Go could return `StopAndBufferWatermark` in `DecodeHeaders`, then Go will receive data in `DecodeData` and could still write headers before `Continue`.
Golang extension is designed to be able do the same thing(almostly) align to C++.

**Comment by StarryVae** [comment]
oh, i see, we can store the headers in the filter object just like what C++ do 🤣 .
