### ISSUE TITLE
Selective TLS bumping

### ISSUE THREAD

**Issue by BenAgai** [envoyproxy/envoy#29275]
Hi,
I have a question regarding selective TLS bumping.
I run Envoy proxy, performing TLS bumping on incoming connections, where proper certificate is provided based on the SNI in the client hello message.

I wanted to ask if its possible to perform selective TLS bumping according to the SNI value?
i.e if I see SNI of www.google.co.il I don’t want the proxy to perform the TLS bumping and instead let the TLS traffic go through it without inspection.

I tried to use FilterChainMatch with the relevant SNI and destination IP values, but instead of not performing TLS bumping, the connection is closed by the proxy.
I’m probably doing something wrong, and I would like to know if it is possible to be done through Envoy.

Thanks,
Ben

**Comment by ohadvano** [comment]
It sounds possible, what is your setup?
If I understand correctly, you would need two filter chains, one that has the downstream TLS context and one that doesn't.
Match the filter chain based on the SNI value, route to the one that terminates if the SNI requires termination, and route to the one that doesn't otherwise.

**Comment by BenAgai** [comment]
Hi @ohadvano,
First thank you for the quick response!

Below is the setup I’m trying to build:
![proxy-setup drawio](https://github.com/envoyproxy/envoy/assets/28253368/8a35032d-aac1-47c0-b7a0-29bd45c3e6a1)

 
Good to know that my direction is correct, using filter chains with matchs.
I can indeed create two chains where one matches the bypass list, providing non-TLS downstream context and
another one not matching the bypass list, providing TLS downstream context.

Few more questions regarding this setup:
1. Do I need to provide two different filter chains and matches for upstream connections context as well?

2. Can I use envoy to validate the certificate presented to the upstream connection through configuration?

3. Assuming my bypass SNI list is update in runtime and I use the xDS API to update envoy. Does it mean that when envoy is updated with the new filter chains configuration, envoy terminates all currently existing sessions (for example websocket connections) or will the update be seamless without affecting current sessions?

Sorry for bothering you with so many questions, I’m just very interested in using Envoy :)
Thanks!

**Comment by ohadvano** [comment]
1. I'm not sure I understand the question - are you interested in upstream filter chains?
2. Do you mean validate the certificate that the peer server presents? If so, then yes. [UpstreamTlsContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-upstreamtlscontext) has ``common_tls_context`` config where you can set options for peer cert validation.
3. Envoy will drain all connections that are using a filter chain that was updated, and will not drain connections that are using other filter chains

**Comment by BenAgai** [comment]
1. I will try to explain. Assuming proxy detected that the SNI from the client side is in the bypass list, it provides a non-TLS downstream context. Does the proxy needs to provide non-TLS context to the upstream using filter chains as well in order to make sure the second setup in my diagram is applied?
2. Thanks!
3. Wonderful. Just to be sure, the way Envoy differentiate between filter chains is using their names right?

**Comment by ohadvano** [comment]
1. I think that yes, otherwise Envoy will do TLS handshake and the TCP payload will also have TLS Client hello.
3. I didn't look at the code of this yet but I think it's based on the config hash.

**Comment by BenAgai** [comment]
I see.
@ohadvano  thank you very much for the explanation, it was very helpful.
Have a good day!

**Comment by BenAgai** [comment]
Hi @phlax ,
you can close this task.
Thank you all
