### ISSUE TITLE
Raw UDP tunneling origination

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#29277]
Recently connect-UDP support has been added in #23564. I would like to add Envoy capabilities to originate a tunnel from raw UDP. The use case would be listening for UDP datagrams using a UDP listener, and tunneling upstream to HTTP/2 or HTTP/3 server that supports the [Proxying UDP in HTTP RFC](https://www.rfc-editor.org/rfc/rfc9298.html). The aim is to first complete tunneling using HTTP/2 and capsules, and afterwards proceed to HTTP/3 upstream.

In the current state, the UDP proxy filter receives UDP Datagrams from the listener and is capable of selecting upstream route cluster based on the 4-tuple. Before creating the upstream socket, the UDP proxy creates a ``UdpProxyFilter::ActiveSession`` object, that maintains the upstream socket and applies the socket options (if needed) as well as closing the session due to idle timeout. The ``ActiveSession`` will be the base for the raw UDP tunneling implementation.

Apart from tunneling, there's also an interest to support per-session extensible operations, for example, we would like to have a variation of the ``dynamic_forward_proxy`` for UDP, where the destination host and port are retrieved from a ``FilterState`` (this is just brought as an example, and will not be elaborated in this issue).
The problem is that UDP listener filters only support the following API: ``virtual FilterStatus onData(UdpRecvData& data) PURE;``.
Therefore, we cannot perform operations which will be invoked once per upstream session. 
For that cause, UDP Session FIlters will be introduced to support this. The session filters will be similar to how TCP filters functions, they will be a read and write filters and will have functions that are called once when session is created, when new downstream datagram is received and when an upstream datagram is received. For not putting too much detail into the same issue thread, and since this concept can be a standalone, I'll separate the design details of session filters to another issue (see #29278), however the tunneling feature is a parent to the UDP session filters.

Another problem needs to be solved is what Envoy should do in case it receives a UDP Datagram during a tunneling flow, but is waiting for an asynchronous callback to be called, two examples:
- In the dynamic forward proxy case as mentioned above, the session will wait for the DNS resolution to complete
- In upstream tunnel creation, receiving the CONNECT response headers as well as the TCP connection establishment is asynchronous

One option would be dropping the UDP Datagrams as UDP does not guarantee reliability anyways. However, dropping datagrams in such cases further degrades the user experience as by-design it would require some datagrams to be retransmitted.
For that cause, each session will maintain a datagrams buffer, which will be limited by configuration (limited by number of datagrams and/or by number of total bytes). By default, there will be no buffering unless specified by config. The buffer will be enqueued in one of the following scenarios:
- TCP tunnel is establishing and waiting for successful response CONNECT headers
- The upstream tunnel watermark callbacks were called, back pressuring Envoy. As opposed to the TCP case where we could stop reading from the downstream connection socket, for UDP the downstream socket is also the listener socket, therefore we would need some other handling for watermark callbacks. In that case a session would buffer the datagrams received.

Lastly, the tunneling feature will be implemented similar to how it was done for TCP tunneling. The ``ActiveSession`` will be refactored to support two operation modes, either the current UDP upstream or tunneling upstream. The UDP upstream will have the same behavior as in its current state. The tunneling upstream will hold a ``Router::UpstreamRequest`` object.

![image](https://github.com/envoyproxy/envoy/assets/49730675/e33ff1e8-717f-487f-89de-86a9c3beea76)

In this diagram, ``Filter#1`` and ``Filter#2`` are arbitrary custom filters that Envoy users can add to the session filter chain. The ``CapsuleFilter`` will be provided by Envoy source as a filter that is responsible to encapsulate and decapsulate UDP datagrams based on the capsule protocol. For HTTP/3 upstream, the filter will be redundant as it will use QUIC Datagrams. Envoy will enforce that if HTTP/2 is used for UDP tunneling, then the capsule filter is the last in the session filter chain.

The following PRs are the roadmap for implementation:
- [x] Add the API describing the design above to the UDP proxy filter as non-implemented (hide)
- [x] Add UDP session filter interface and filter factory, unit tests
- [x] Apply UDP session filters in the UDP proxy, integration tests, docs
- [x] Add callbacks to inject datagrams to filter chain, to allow in-filter buffering
- [x] Refactor ``ActiveSession`` to ``ActiveSession`` as base and ``UdpActiveSession`` to inherit
- [x] Implement ``CapsuleFilter`` for tunneling over HTTP, integration tests
- [x] Dynamic foward proxy session filter implementation, tests
- [x] Add ``UpstreamTunnel`` implementation that handles upstream codec, unit tests
- [x] Add ``TunnelingActiveSession`` which uses the ``UpstreamTunnel``, add API, docs, integration tests

cc @DavidSchinazi, @mattklein123, @danzh1989, @RyanTheOptimist

**Comment by DavidSchinazi** [comment]
cc @jeongseokson and @asingh-g since the related PRs are relevant to our current documentation and testing efforts

**Comment by ohadvano** [comment]
All tasks are done, thanks for reviewers
