### ISSUE TITLE
UDP session filters

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#29278]
This is a feature tracking issue for adding UDP session filters support.

Originated by UDP Tunneling #29277, this comes to support use cases where it's required to run extensible operations with a UDP session affinity.
While UDP listener filters support ``onData``, it's sometimes required to perform certain operations only on session start, and when a datagram is received from upstream.
For example, we would like to have a variation of the ``dynamic_forward_proxy`` for UDP, where the destination host and port are retrieved from a ``FilterState`` (this is just brought as an example, and will not be elaborated in this issue).

For that cause, I am planning to add support for UDP session filters. These kinds of filters could be turned by configuration, and if configured, they will be applicable to any upstream UDP session.

The filters will support the following API:

ReadFilter:
```
/**
 * Called when a new UDP session is first established. Filters should do one time long term
 * processing that needs to be done when a connection is established. Filter chain iteration
 * can be stopped if needed.
 * @return status used by the filter manager to manage further filter iteration.
 */
virtual ReadFilterStatus onNewSession() PURE;

/**
 * Called when UDP datagram is read and matches the session that manages the filter.
 * @param data supplies the read data which may be modified.
 * @return status used by the filter manager to manage further filter iteration.
 */
virtual ReadFilterStatus onData(Network::UdpRecvData& data) PURE;
```

WriteFilter:
```
/**
 * Called when data is to be written on the UDP session.
 * @param data supplies the buffer to be written which may be modified.
 * @return status used by the filter manager to manage further filter iteration.
 */
virtual WriteFilterStatus onWrite(Network::UdpRecvData& data) PURE;
```

The functions will return ``ReadFilterStatus``/``WriteFilterStatus``:
```
enum class ReadFilterStatus {
  // Continue to further session filters.
  Continue,
  // Stop executing further session filters.
  StopIteration,
};
```

The callbacks that the filters will be initialized with, will (at first version) provide the underlying session ID and the stream info that will be generated per-session.

```
class FilterCallbacks {
public:
  virtual ~FilterCallbacks() = default;

  /**
   * @return uint64_t the ID of the originating UDP session.
   */
  virtual uint64_t sessionId() const PURE;

  /**
   * @return StreamInfo for logging purposes.
   */
  virtual StreamInfo::StreamInfo& streamInfo() PURE;
};
```

The following PRs are the roadmap for implementation:

- [x] Add UDP session filter interface, filter config, factory interface and unit tests
- [x] Refactor UDP proxy to allow clean adding of UDP session filters
- [ ] Apply UDP session filters, integration tests, docs

cc @DavidSchinazi, @mattklein123, @danzh1989, @RyanTheOptimist

**Comment by DavidSchinazi** [comment]
cc @jeongseokson and @asingh-g since the related PRs are relevant to our current documentation and testing efforts
