### ISSUE TITLE
http: not proxying 413 correctly 

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#2929]
*Description*:
In the case envoy is proxying large HTTP request, even upstream returns 413, the client of proxy is getting 503.

*Repro steps*:
A sample envoy config is [here](https://gist.github.com/lizan/14fdcdebc332088eb03501dcbffdf48f).

```
$ curl -v http://127.0.0.1:8080 --data @envoy.log
> POST / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 28576635
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 413 Payload Too Large
< content-length: 17
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:10:27 GMT
< server: envoy
< connection: close
<
* we are done reading and this is set to close, stop send
* Closing connection 0
```
is hitting directly to listener with buffer filter, results 413.

However,
```
curl -v http://127.0.0.1:8000 --data @envoy.log
> POST / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 28576635
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:10:21 GMT
< server: envoy
< connection: close
<
```
will results 503, the port 8000 is proxying to 8080, which should return 413 too.

`envoy.log` above could be substitute with any large file (mine is 28MB), if you use smaller file (around 10K) which could fit in the TCP buffer, the port 8000 will return 413 correctly:

```
curl -v http://127.0.0.1:8000 --data @STYLE.md
> POST / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 11450
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 413 Payload Too Large
< content-length: 17
< content-type: text/plain
< date: Thu, 29 Mar 2018 02:15:29 GMT
< server: envoy
< x-envoy-upstream-service-time: 0
<
```

From the trace log below, it looks like when envoy write to upstream and it fails, it immediately result 503 without trying to read if the server already sent back the response.
```
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:322] [C1] parsed 1048576 bytes
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/connection_impl.cc:386] [C2] socket event: 2
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/connection_impl.cc:454] [C2] write ready
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:67] [C2] write returns: 524288
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:67] [C2] write returns: -1
[2018-03-28 19:02:10.131][23666][trace][connection] source/common/network/raw_buffer_socket.cc:70] [C2] write error: 32 (Broken pipe)
[2018-03-28 19:02:10.131][23666][debug][connection] source/common/network/connection_impl.cc:134] [C2] closing socket: 0
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:305] [C2] parsing 0 bytes
[2018-03-28 19:02:10.131][23666][trace][http] source/common/http/http1/codec_impl.cc:322] [C2] parsed 0 bytes
[2018-03-28 19:02:10.131][23666][debug][client] source/common/http/codec_client.cc:81] [C2] disconnect. resetting 1 pending requests
[2018-03-28 19:02:10.131][23666][debug][client] source/common/http/codec_client.cc:104] [C2] request reset
[2018-03-28 19:02:10.131][23666][trace][main] source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=1)
[2018-03-28 19:02:10.131][23666][debug][router] source/common/router/router.cc:464] [C1][S12280405291311848063] upstream reset
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S12280405291311848063] encoding headers via codec (end_stream=false):
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   ':status':'503'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'content-length':'57'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'content-type':'text/plain'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'date':'Thu, 29 Mar 2018 02:02:10 GMT'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'server':'envoy'
[2018-03-28 19:02:10.132][23666][debug][http] source/common/http/conn_manager_impl.cc:972] [C1][S12280405291311848063]   'connection':'close'
[2018-03-28 19:02:10.132][23666][trace][connection] source/common/network/connection_impl.cc:323] [C1] writing 153 bytes, end_stream false
[2018-03-28 19:02:10.132][23666][trace][http] source/common/http/conn_manager_impl.cc:1031] [C1][S12280405291311848063] encoding data via codec (size=57 end_stream=true)
[2018-03-28 19:02:10.132][23666][trace][connection] source/common/network/connection_impl.cc:323] [C1] writing 57 bytes, end_stream false
```

Thanks @JimmyCYJ who originally find this with adding test in istio for #2919.

**Comment by mattklein123** [comment]
@lizan sorry but I don't fully grok the flow here. Can you more fully spell out who is talking to who with a small ASCII diagram? I don't quite understand who is disconnecting, etc.

**Comment by lizan** [comment]
No one is disconnecting, we have two envoy listeners above, I just pushed double proxy in one config.

The diagram:
```
+----------------+      +-----------------+
|Listner A (8000)|+---->|Listener B (8080)|+----> (dummy backend)
+----------------+      +-----------------+
```

Listener B is configured with buffer filter so when a request larger than `max_request_bytes: 512` bytes coming in, it returns 413 (expected).

The 4 cases I did test:
1. post relatively small (11KB) data to Listener B -> 413 (expected)
2. post large (28MB) data to Listener B -> 413 (expected)
3. post relatively small (11KB) data to Listener A -> 413 (expected)
4. post large (28MB) data to Listener A -> 503 (SHOULD be 413)

**Comment by mattklein123** [comment]
Do you have the full logs? Does listener A receive the 413 response? IIRC we should send that response and not send a 503.

**Comment by lizan** [comment]
https://gist.github.com/lizan/01807d956f10d3974a93a384551357b6

From the log, listener B writes 413 response, but router of listener A doesn't try to read when its write fails, so it results 503.

**Comment by mattklein123** [comment]
Why is the write failing though? Is it because listener B has already closed the connection? If so not really sure we can do much about this. I don't think it would happen if not on localhost. Also, you could try, but I don't think this would be an issue over HTTP/2 as the connection would not be torn down.

**Comment by lizan** [comment]
> Why is the write failing though?

Since upstream (listener B) already sent 413 and closed the connection, before listener A finish writing, as back pressure applied. @alyssawilk to confirm if my understanding is correct.

**Comment by mattklein123** [comment]
Your understanding is correct. When Envoy needs to send a response to a request that is not complete over HTTP/1.1, it must close the connection (this is not true for HTTP/2 where it just resets).

The issue is that on the receive side, it's a timing race between when we try to write and when we receive the read event (if write was blocked, we might get read/write ready at the same time, and IIRC we process read first, but if write is not blocked it will just attempt to write immediately and fail). Over loopback, it's very likely to lose this race. It will never happen over the real network.

I'm not quite sure how to fix this if we wanted to. I suppose in the connection impl if we try to write and it fails we could try to read and dispatch any data read, before failing due to the write failure.

**Comment by lizan** [comment]
We process write first:
https://github.com/envoyproxy/envoy/blob/master/source/common/network/connection_impl.cc#L412

I'll try this over network (not loopback) and get back to you.

**Comment by mattklein123** [comment]
Hmm. I feel like we used to process read first, but then we switched it for some reason I now don't remember. :) @PiotrSikora might remember.

**Comment by lizan** [comment]
If this is over network, 5 out of 10 tries I did get 503 instead of 413.

**Comment by mattklein123** [comment]
Hmm. Yeah I guess the race can still be lost at high throughout. The only
solution I can think of is to try to read and dispatch any data on write
failure.

**Comment by PiotrSikora** [comment]
@mattklein123 we changed it because of the combined `read|write` events raised by the kernel (https://github.com/envoyproxy/envoy/pull/1896), but that's unrelated and changing order wouldn't fix this issue.

This issue is happening, because Envoy acting as a server (i.e. listener B in @lizan's example) closes downstream connection with pending (unread) data, which results in TCP `RST` packet being sent downstream.

Depending on the timing, downstream (i.e. listener A in @lizan's example) might be able to receive and proxy complete HTTP response before receiving TCP `RST` packet (which erases low-level TCP buffers), in which case client will receive response sent by upstream (`413 Request Body Too Large` in this case, but this issue is not limited to that response code), otherwise client will receive `503 Service Unavailable` response generated by listener A (which actually isn't the most appropriate response code in this case, but that's a separate issue).

The common solution for this problem is to half-close downstream connection using `::shutdown(fd_, SHUT_WR)` and then read downstream until `EOF` (to confirm that the other side received complete HTTP response and closed connection) or short timeout.

cc @alyssawilk @ggreenway

**Comment by mattklein123** [comment]
Yup I understand the problem (and thanks for reminding me of the ordering issues).

If we want to do a server side change to fix, I like the idea of adding a connection close type which does the following:
1) Does a half close
2) Disables reading (to provide TCP back pressure)
3) Sets some timeout
4) Then does full close

I would rather not get into the dance of waiting for the other side to close which might never happen.

**Comment by alyssawilk** [comment]
+1 to this.  We're going want this delay-close semantics in the long run anyway, as when we're done serving a response it's nice to get the final TCP_INFO with all the loss, rtt, and timing info.

**Comment by mattklein123** [comment]
OK SGTM. Will switch this to bug/help wanted.

**Comment by lizan** [comment]
@PiotrSikora I'm not sure whether this is server-side (Listener B) issue, if you use curl as client, it can always read 413 from Listener B, regardless loopback or not. If `RST` erases low-level TCP buffers, then curl cannot read 413 in some cases as well, right?

**Comment by lizan** [comment]
Disregard my previous comment, curl sees `Connection reset by peer` in a few cases.

FWIW, using HTTP2 between Envoys will let envoy proxy 413 correctly, though in this case the client curl (to Listener A) I see
`* We are completely uploaded and fine` even the POST body is huge (like 150MB), this means the flow control isn't work at some point so curl could write the entire body. @alyssawilk?

**Comment by mattklein123** [comment]
The default h2 flow control windows in Envoy are huge. (Like 256MiB). They can be configured.

**Comment by alyssawilk** [comment]
@lizan not totally following your last comment.  If you think this is flow control related, feel free to ping me on chat and I'll try to sort things out

**Comment by AndresGuedez** [comment]
Hi All,

I am preparing a PR with a mitigation for the client read/close race as per the approach outlined by @mattklein123 above.

There is a second problem identified in this issue whereby Envoy initiates connection tear down without allowing the read socket buffer to be drained when connection closes are picked up via write()s. I will tackle this next, although I think it should be done under a new issue unless anyone objects.
