### ISSUE TITLE
consider making security properties a per-type-url thing

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#29305]
on https://github.com/envoyproxy/envoy/pull/29173 we're adding functionality to ext_authz to be an upstream filter, which is much higher risk than a small change to a filter.

Previously we've added per-route capabilities to filters which may also be higher risk. 

It'd be nice to have a given legacy use of a filter/extension to be stable, but have a new, higher-risk use case be considered less vetted.

**Comment by phlax** [comment]
assigning myself for the validation side - i probs need to clarify expectations/spec

**Comment by alyssawilk** [comment]
Per offline discussions we're going to go with
upstream_stats as a tag on filters which have the category "envoy.filters.http.upstream" so that we can have one alpha and the other GA
