### ISSUE TITLE
Is it possible to change certificate content in transport socket (to upstream) dynamically

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#29319]
Hi, we have the following question-using custom_handshaker_extension can we override only one of the tls handshake steps instead of overriding the whole process or extending it? Is the way to do it by rebuilding the envoy binary or there is another way(because there are no examples)? What we are trying to achieve is to change the transport socket certificate content attached on a dynamic forward proxy cluster(for example based on some information from the incomming http request). We also checked transport socket matches but it seems like they do not work for our scenario.

**Comment by phlax** [comment]
cc @mattklein123 @alyssawilk @ggreenway

**Comment by soulxu** [comment]
It seems like the certificate provider match your case, but it doesn't implement yet https://github.com/envoyproxy/envoy/issues/19308

**Comment by alyssawilk** [comment]
I don't think there's much you can do other than transport socket matches.  If you provide an example of what you're doing @ggreenway @danzh2010 are more familiar with the code and may be able to advise.

**Comment by ggreenway** [comment]
Are you just trying to select a TLS certificate dynamically, but no other changes to the handshake? If so, that's been discussed some over the years but never implemented. It would be a reasonable extension point to add.

With what is implemented now, I believe you'd need to implement the entire handshaker to get this functionality.

**Comment by DimitarHKostov** [comment]
@ggreenway Yes, we only want to select tls certificate dynamically and preserve the default tls handshake behaviour.
