### ISSUE TITLE
CustomResponseFilter: allow to proxy the response body intact

### ISSUE THREAD

**Issue by ozkar99** [envoyproxy/envoy#29331]
Currently, the `CustomResponse` filter (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/custom_response/v3/custom_response.proto) only allows 2 types of response policies for a match:

LocalResponsePolicy ( https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/custom_response/local_response_policy/v3/local_response_policy.proto ): Which supports a way to change the response body with a `DataSource`.

RedirectResponsePolicy ( https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/custom_response/redirect_policy/v3/redirect_policy.proto): Which supports a way to respond with an HTTP redirect response.

However, there is no way to proxy the body of the response as sent by the upstream to the client.

Would it be reasonable to add a `PassthruResponsePolicy` which would allow the `CustomResponse` filter to add/remove/modify response headers while keeping the body intact?

---------------

Our use case is injecting headers on certain response codes while keeping the body intact for the client.

**Comment by phlax** [comment]
cc @pradeepcrao @yanavlasov

**Comment by pradeepcrao** [comment]
Hi @ozkar99, sorry for the late response. This looks like a reasonable [`envoy.http.custom_response`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/custom_response/v3/custom_response.proto#extension-category-envoy-http-custom-response) extension to add. I will be happy to review the changes if you add it.

**Comment by ozkar99** [comment]
Sounds, good! this is something I would love to tackle, unfortunately, it might take a bit of time to implement as its fairly low priority in our needs currently.

(In case someone else is reading the thread and needs this feature don't wait for me)
