### ISSUE TITLE
Golang filter: the filter is bypassed silently if a wrong name is configured

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#29332]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Currently, when there is no registered filter for the configured name, the golang filter will be bypassed.
https://github.com/envoyproxy/envoy/blob/74bfcb0b591bb692db0b9b0700b4822ef8a6d777/contrib/golang/filters/http/source/go/pkg/http/filtermanager.go#L50-L55

If people provide a wrong name by mistake, it may bring some problems:
1. the filter will not take effect without any notification
2. if there is some security policy in the filter, the wrong configuration will cause a security leak.

Maybe we could add an error log if the filter is missing?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @doujiang24

**Comment by doujiang24** [comment]
yep, an error log should be added, PR welcome & thanks~

**Comment by spacewander** [comment]
Assign to me
