### ISSUE TITLE
extensions: allow for pluggable health checkers 

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2933]
Would be generally useful and also needed to full cleanup/compile out Redis. For reference see https://github.com/envoyproxy/envoy/pull/2926.

**Comment by dio** [comment]
Interested in this (in a sense of understanding the concept) and how you will approach it. I want to learn it! However, I have no concrete approach yet. Just a guessing: 

1. We create the same layout of health checkers just like what we have with filters, e.g.

```
`-- health_checkers
    `-- redis_health_checker
        |-- BUILD
        |-- config.cc
        |-- redis_health_checker.cc
        `-- redis_health_checker.h
```

2. Register the factory (e.g. with a new base called `HealthCheckerExtensionFactory`) to the `FactoryRegistry` by ideally `HealthCheck::HealthCheckerCase` (or a map of `name` -> `HealthCheckerCase`).

3. Then, in that `HealthCheckerFactory::create`'s switch-case we return:

```c++
return Registry::FactoryRegistry<HealthCheckerExtensionFactory>::getFactory(
               convertToName(hc_config.health_checker_case()))
        ->create(hc_config, cluster, runtime, random, dispatcher);
```

And throw if not found.

**Comment by mattklein123** [comment]
@dio yeah basically exactly right. We would add a new HC option here: https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/health_check.proto#L119

Which is basically, "extension_health_checker" which just has a well known name and a Struct config. Then, we would translate the existing Redis configuration into an "extension_health_checker" and ultimately deprecate it.
