### ISSUE TITLE
Dynamic update of TLS certificate

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#29357]
Dear Envoy team,

I would like to propose a new feature that would greatly enhance its capabilities and bring significant value to my operations. The feature involves the dynamic selection of TLS certificates when using the dynamic forward proxy. Currently, the TLS handshake behaviour selects a default certificate which is set on Cluster level, consequently, cannot be changed dynamically per request.

This feature would greatly help to maintain security, especially in multi-tenant environments, where each tenant might have their own unique certificates. It would also help in scenarios where certificates may need to be rotated or updated frequently.

Thank you for considering my request.

Best Regards,
Dimitar

**Comment by phlax** [comment]
cc @mattklein123 @alyssawilk @ggreenway

**Comment by alyssawilk** [comment]
no objections, but I don't think any of the maintainers would be able to pick this up.  We'd be happy to review if someone on your end can do so though.

**Comment by ggreenway** [comment]
Related discussion: #29319

Yes, I think this makes a lot of sense as an extension. It would also be a great candidate for having a lua extension, for embedding small bits of custom logic for cert selection.

PRs welcome if anyone wants to work on this.

**Comment by IliyanVidenov** [comment]
Could you extend the gRPC filter instead? We can't use Lua due to its limitations, such as buffering.
