### ISSUE TITLE
Make integration tests compatible with repo reporg (#2911)

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#2935]
Here's my first pass ideas on how to get the tests co-located with code - other ideas and constructive criticism welcomed!

Right now we have a mix of tests-per-filter (lua_integration_test.cc, cors_filter_integration_test.cc, etc) and testing filters per-protocol (e.g. buffer tests in all three of  [http2_][upstream_]integration_test.cc files.

For things like lua/cors that have standalone tests we can just move them now.

For tests in [http2_][upstream_]integration_test.cc, I think we could easily have a test param base class ProtocolIntegrationTest where GetParam(0) is IP version, GetParam(1) is upstream protocol and GetParam(2) is downstream protocol, then we can move things like the buffer filter and health check filter to their own files without losing coverage or creating 12 new test files (one test per filter per protocol)

Finally for tests like 100Contine that need "a filter" we make it easier to add, register, and test custom test filters, move over to those, then remove the dependencies from the "extension" filters.

**Comment by alyssawilk** [comment]
@htuch @mattklein123 per discussion on whichever of Matt's migration PRs we discussed this on :-P

**Comment by mattklein123** [comment]
@alyssawilk in general SGTM. Two comments/questions:
1) It seems OK that we can depend on some extensions for integration tests, but as you say probably worth codifying when that is OK and in other cases using test filters.
2) When we move integration tests to the extension directory, where will they live? My preference is to put them directly in the test folder alongside the unit tests. I know we had talked about putting them in a subdirectory of integration but IMO the further split there isn't that useful?

**Comment by alyssawilk** [comment]
Interested in your thoughts on 1.  I think tcp proxy filter and http connection manager are OK for sure, as they're already documented as required.  I think with our current tests we can probably get away without other dependencies - what did you have in mind?

Keeping integration tests with the unit tests in the filter directories SGTM.  I'd lean towards keeping the "core" integration tests (http/h2 functionality) together but don't have strong feelings about where.

**Comment by mattklein123** [comment]
> Interested in your thoughts on 1. I think tcp proxy filter and http connection manager are OK for sure, as they're already documented as required. I think with our current tests we can probably get away without other dependencies - what did you have in mind?

I don't have any real ideas here. I think we can just see how things go and be flexible. I guess my thinking is that certain extensions don't require complicated third party dependencies and are generally useful as fully working real examples. Even if someone doesn't compile them into their final server binary via bazel define, it seems reasonable to require that they are used in a full test run. (As opposed to say Lua which I think we should allow fully compiling out).

> Keeping integration tests with the unit tests in the filter directories SGTM. I'd lean towards keeping the "core" integration tests (http/h2 functionality) together but don't have strong feelings about where.

IMO just keep them where they are. I think for things that are fully independent (Lua, Cors, Squash, etc.) I would prefer to just keep them in the associated extension test folder next to the unit tests.

**Comment by alyssawilk** [comment]
Cool, I like third party deps as a first pass on gating factor.  All of "our" code in the integration tests seems totally reasonable and this lets us not pull all of *everyone's* code. 

I think it'd be nice at some point to have an easy target for "run all the integration tests in all the directories" for major changes, but that can be done well with test tags regardless of where we stick code/tests and it is pretty low on my priority list given testing test/... is still pretty darned fast.

**Comment by alyssawilk** [comment]
Actually I think this one is good enough - we don't have test filters per se but we can add them as needed
