### ISSUE TITLE
If two listeners can have the same ip but listen to different network adapters?

### ISSUE THREAD

**Issue by xunhuangxu** [envoyproxy/envoy#29358]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: If two listeners can have the same ip but listen to different network adapters?

*Description*:
>What happens if I modify the source code so that two listeners can have the same ip:port but listen to isolated network adapters?
[optional *Relevant Links*:]

>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @KBaichoo @alyssawilk

**Comment by KBaichoo** [comment]
While I haven't used this setup myself, you might be able to use SocketOptions: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#envoy-v3-api-msg-config-core-v3-socketoption to bind particular devices using SO_BINDTODEVICE to the listener. 

I would make sure you have different https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-stat-prefix between listeners with the same address so the stats aren't conflated. You may run into additional hurdles with this setup.

**Comment by soulxu** [comment]
I guess that won't since we have a check like this https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc#L1053

**Comment by soulxu** [comment]
> I guess that won't since we have a check like this
> 
> https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc#L1053

nvm, we also have check for skip the check for address which bind to port
https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_impl.cc#L1160-L1161

**Comment by xunhuangxu** [comment]
> While I haven't used this setup myself, you might be able to use SocketOptions: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#envoy-v3-api-msg-config-core-v3-socketoption to bind particular devices using SO_BINDTODEVICE to the listener.
> 
> I would make sure you have different https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-stat-prefix between listeners with the same address so the stats aren't conflated. You may run into additional hurdles with this setup.

As you said, I can make two listeners with the same address listen to different network devices by setting different socket options using SO_BINDTODEVICE. However, envoy rejects a second listener with the same address.

**Comment by xunhuangxu** [comment]
> > I guess that won't since we have a check like this
> > https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc#L1053
> 
> nvm, we also have check for skip the check for address which bind to port
> 
> https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_impl.cc#L1160-L1161

Yes, you're right. However, what makes me curious is that the Envoy supports using socket options to enable the listener to listen to a network device. Why does the Envoy have to keep the address unique? If two network devices have the same address, the two listeners should be able to listen to the same address of the two network devices, respectively.

**Comment by xunhuangxu** [comment]
> > > > I guess that won't since we have a check like this
> > > > https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc#L1053
> > > 
> > > 
> > > nvm, we also have check for skip the check for address which bind to port
> 
> correct myself, it won't skip the check when the port is non-zero.
> 
> > > https://github.com/envoyproxy/envoy/blob/420f77c8f5da683c5b91f7a8b4c679e9ecaa8a31/source/extensions/listener_managers/listener_manager/listener_impl.cc#L1160-L1161
> > 
> > 
> > Yes, you're right. However, what makes me curious is that the Envoy supports using socket options to enable the listener to listen to a network device. Why does the Envoy have to keep the address unique? If two network devices have the same address, the two listeners should be able to listen to the same address of the two network devices, respectively. Could this scenario be supported? [#29358 (comment)](https://github.com/envoyproxy/envoy/issues/29358#issuecomment-1702446650)
> 
> I guess Envoy doesn't think about to support this case in the past. Even if we delete that check, I think it sill won't work, since we have a lot of places use the address as the key to find the listener.
> 
> But we support ipv6 with scope id, the scope id is identify the interface for the ipv6, I haven't tried that, it supposed to work I guess.

It's a great honor to have your quick answer. I still have some questions.
As you mentioned, Envoy uses address as the key to find listeners in many places. Is it in the format of ip:port or address? I see that duplicate addresses are determined by comparing address objects to see if they are equal? If an address object is used to search for a listener, can I add an attribute to the address object to implement IP address:port overlap?
