### ISSUE TITLE
Add 'thrift_to_metadata' HTTP Filter for Thrift Multiplexing

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#29371]
*Title*: *Add 'thrift_to_metadata' HTTP Filter for Thrift Multiplexing*

*Description*:
We propose the addition of a new HTTP filter, 'thrift_to_metadata,' to Envoy Proxy, aimed at enhancing Thrift multiplexing by putting Thrift payloads embedded within HTTP POST bodies, which is compatible with Apache thrift[1]. This filter's primary function is to extract essential metadata, such as method names, frame sizes, and related details, from the HTTP body (which is a thrift payload) and store them in filter metadata. This capability is critical for other filters to achieve more precise metrics, security, rate limiting, and routing with respect to thrift metadata.

Moreover, we could extract information from payload to have extension similar to thrift proxy filters, so we could embedded filter like payload_to_metadata into the proposed filter.

[optional *Relevant Links*:]
[1] https://github.com/apache/thrift
[2] https://github.com/envoyproxy/envoy/blob/34c68f9e87907e4259c13635cab7ad010bb2fc62/source/extensions/filters/network/thrift_proxy/metadata.h#L57
[3] https://www.envoyproxy.io/docs/envoy/latest/configuration/other_protocols/thrift_filters/payload_to_metadata_filter

**Comment by phlax** [comment]
cc @zuercher
