### ISSUE TITLE
Why downstream_cx_active is a Gauge metric and downstream_cx_total Counter?

### ISSUE THREAD

**Issue by Aracki** [envoyproxy/envoy#29387]
How it comes that `downstream_cx_active` can be higher than `downstream_cx_total`?

According to https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats, total should be the sum of all connections, and active should be just the active ones. 

In my example `downstream_cx_active` is showing 2k active connections, but rate of `downstream_cx_total` is like ~3 connection per second.

What's the general idea behind these two metrics exposed by Envoy and how do you monitor it?

**Comment by pxpnetworks** [comment]
I think this is completely normal the rate of new connections to be lower than the active ones (as new connections come and go).
If you look just at the **downstream_cx_total** (without a rate function) what is the value?

**Comment by Aracki** [comment]
`downstream_cx_total` is ~2mil.

I was confused as I haven't realised new connections "come and go" that quickly. Thanks!
