### ISSUE TITLE
Envoy external grpc filter handlers

### ISSUE THREAD

**Issue by VladislavAtanasov** [envoyproxy/envoy#29419]
*Title*: *How to get response headers and status code in a grpc external processing filter?*

*Description*:
> Each request only hit pb.ProcessingRequest_RequestHeaders handler. We cannot enter the handlers to try to tweak the HTTP  response code and response headers even when we set all configs to send response to "SEND". How can we achieve the attitude of Lua envoy_on_response handler in grpc? 

[optional *Relevant Links*:]
> We are using this example https://github.com/salrashid123/envoy_ext_proc/blob/main/grpc_server.go

**Comment by wbpcode** [comment]
cc @tyxia

**Comment by VladislavAtanasov** [comment]
Is there a way to get and change the response codes and headers via https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto http Envoy Ext Authorization filter?

**Comment by tyxia** [comment]
Sorry missed this issue earlier.

ext_proc support the mutation of response header.  There is several examples in `http/ext_proc/ext_proc_integration_test.cc`. For example: test `GetAndSetHeadersOnResponse`

You don't need to set the`set_response_header_mode(ProcessingMode::SEND)`. Its [default mode](https://github.com/envoyproxy/envoy/blob/6ba0ef69686011e1fb8d92471f8c839e34973f98/api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto#L28) is SEND unless it is set to SKIP

**Comment by VladislavAtanasov** [comment]
Is there an example for the golang version of the grpc external processing filter

**Comment by tyxia** [comment]
I am not aware of golang version of ext_proc filter. I think majority of Envoy proxy is written in c++.

Maybe you can look at https://github.com/envoyproxy/envoy/tree/main/contrib/golang/filters/http but I haven't look at this folder before

**Comment by VladislavAtanasov** [comment]
Sorry, I meant that is there an example for that External Processor - https://github.com/envoyproxy/go-control-plane/blob/main/envoy/extensions/filters/http/ext_proc/v3/ext_proc.pb.go

**Comment by VladislavAtanasov** [comment]
We have tried using field "MutationRules" in https://github.com/envoyproxy/go-control-plane/blob/main/envoy/extensions/filters/http/ext_proc/v3/ext_proc.pb.go to allow mutating ":status" header but we still dont have access to the response code from the target system and cannot modify it. Is there an equivalent of the of the approach mentioned above in this processing filter
