### ISSUE TITLE
envoy-1.27: ext_proc raw_value field processing on header mutation instructed by the service

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#29424]
as part of envoy-1.27 new mutation field was introduced, which seem has very specific handling in ext_proc filter other than other parts of the system.

even though when envoy sending data is very clear the intent of the `envoy.reloadable_features.send_header_raw_value` flag. aka checking if field to be encoded in utf-8, but on receiving side checking this flag seem odd and just increasing complexity of migration from one version of messaging to another as well as introducing ambiguity and overhead.

refering source code is follow: https://github.com/envoyproxy/envoy/blob/4cac633a3b4d243e89d96753ad9510ac2a172f2c/source/extensions/filters/http/ext_proc/mutation_utils.cc#L164C18-L164C18

so to us simple change of mentioned condition to `if (sh.header().has_raw_value()) {` will simplify running environment migration tremendously as well as minimize overhead of checking runtime flags etc.

PS. Also as in general, it seems that the plugin has different handling of mutation rules other than rest of the platform and other filters which are using same `config.core.v3.HeaderValue` type, and more we going in this direction is more complication it became to use different components in synergy.

**Comment by phlax** [comment]
cc @gbrail @stevenzzzz @tyxia @mattklein123 @htuch

**Comment by stevenzzzz** [comment]
Thanks for the ping. 

My understanding is that the runtime feature flags indeed requires some migration work done at the external server side. 
And this feature flag is one-off thing once the migration is done. your suggestion looks good to me, that it by default prefers raw_value. 

note I don't know if there is a deprecation plan already or not tho. @yanjunxiang-google 
But I think the in the final shapre, there won't be a "value" in the headerValue definition.

**Comment by yanjunxiang-google** [comment]
The "value" will be kept in the headerValue definition.

However, Envoy ext_proc filter will only send and receive the header value in the "raw_value" field once the runtime flag is removed.

**Comment by chrislovecnm** [comment]
@pgeler et al https://github.com/envoyproxy/envoy/issues/31555
