### ISSUE TITLE
Optimize EDS stream allocation

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2943]
Today, EDS attempts to open one stream per cluster to the management server when not being multiplexed over ADS. EDS streams support subscribing to more than one cluster, so this should not be necessary if the `ApiConfigSource` points to the same management server.

This is actually very noticeable when we have a large number of clusters. It shows up as stream resource exhaustion in H2 (https://github.com/envoyproxy/envoy/issues/2941) as well as in internal performance benchmarks of configuration scalability.

The fix seems pretty easy, just need to do some level of aggregation similar to what ADS does.

**Comment by costinm** [comment]
Please provide an option to turn this on/off - Istio has code to deal with multiple clusters per connection, but
 we'll need to test against the new envoy implementation.

**Comment by htuch** [comment]
Reopened, since we rolled back the original PR.

**Comment by antoniovicente** [comment]
It would be good to get this fixed soon.
