### ISSUE TITLE
What does "join" mean in the doc of Tracing

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#29442]
I understand what `x-request-id` is. It is generated by Envoy and can be passed to all of upstream endpoints.

But now I want to trace requests starting from clients, I read the doc: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing

It seems what I need is the `x-client-trace-id`.

The doc says:

> Client trace ID joining: The x-client-trace-id header can be used to join untrusted request IDs to the trusted internal x-request-id.

I kind of don't understand what "to join untrusted request IDs to the trusted internal x-request-id" means.

I've tried to insert `x-client-trace-id` into headers of requests of clients and I configured `%REQ(X-REQUEST-ID)%` and `%REQ(X-CLIENT-TRACE-ID)%` in the log. And I just found that they were simply what they were.

I thought that "to join" meant to combine the two IDs into one or something like this...

So did I misunderstand something?

**Comment by j2gg0s** [comment]
My understand:
- We don't want to directly use request-id from untrusted clients.
- So we generate a new request id as root span
- x-client-trace-id will be attribute of new span

We do not use the client request-id directly, but associate it as an attribute with our newly generated trace.
