### ISSUE TITLE
Enable wasmtime features with bazel build flags

### ISSUE THREAD

**Issue by rahulchaphalkar** [envoyproxy/envoy#29456]
*Title*: *Enable wasmtime features with bazel build flags*

*Description*:
Is there a good way to enable wasmtime crate's features via bazel's build flags when building Envoy?
The way I'm thinking is, add appropriate `config_setting` in `envoy/bazel/BUILD`, say
```
config_setting(
    name = "custom_build",
    values = {"define": "custom_flag=true"},
)
```

Then add configurable build attribute to `envoy/bazel/external/wasmtime.BUILD` in `crate_features` - 
```
rust_static_library(
    name = "rust_c_api",
    srcs = glob(["crates/c-api/src/**/*.rs"]),
    crate_root = "crates/c-api/src/lib.rs",
    edition = "2018",
    proc_macro_deps = [
        "@proxy_wasm_cpp_host//bazel/cargo/wasmtime:wasmtime_c_api_macros",
    ],
    crate_features = select({
        "@envoy//bazel:custom_build":
    [
        "custom-feature",
    ],
    "//conditions:default": [],
    }),
    deps = [.
.
.
]
```

Then make a few changes in wasmtime repo, namely,

- Add `custom-feature` to `c-api` crate in `wasmtime/crates/c-api/Cargo.toml`  
- conditionally enable (`[target.'cfg(custom-feature = "true")'.dependencies.wasmtime]`) the feature in `wasmtime` crate.

[Additional info:]
I'm able to enable features for wasmtime from envoy's bazel build flags if i manually modify in proxy-wasm-cpp-host repo, `proxy-wasm-cpp-host/bazel/cargo/wasmtime/remote/BUILD.wasmtime-13.0.0.bazel` by adding configurable build attribute i.e. `select` statement to `crate_features`.
However, these build files in proxy-wasm are generated by cargo-raze, hence this doesn't seem like a good solution, as any update to wasmtime will regenerate these build files.

I've reviewed this existing issue to find relevant information https://github.com/envoyproxy/envoy/issues/21634#issuecomment-1151790006

**Comment by rahulchaphalkar** [comment]
@PiotrSikora since this involves `proxy-wasm-cpp-host`.
I tried modifying `bazel/cargo/wasmtime/Cargo.toml` in `proxy-wasm-cpp-host` and regenerating the build files, but I still lacked the plumbing from bazel build flags to conditionally enabling cargo features.

**Comment by wbpcode** [comment]
cc @mpwarres
