### ISSUE TITLE
UpstreamNetworkExtensionDiscoveryIntegrationTest.BasicSuccessWithTtl flake

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#29453]
Detected with compile time options:

```
[ RUN      ] IpVersionsClientType/UpstreamNetworkExtensionDiscoveryIntegrationTest.BasicSuccessWithTtl/1
libc++abi: terminating with uncaught exception of type Envoy::EnvoyException: Negative duration passed to durationToTimeval(): -1
================================================================================
INFO: Elapsed time: 2367.553s, Critical Path: 935.38s
INFO: 18561 processes: 5757 remote cache hit, 8075 internal, 4729 remote.
@envoy//test/integration:upstream_network_filter_integration_test        FAILED in 10.7s
```

cc @ohadvano

**Comment by ohadvano** [comment]
Did you run it locally or is this from CI?

**Comment by kyessenov** [comment]
This is from CI.

**Comment by alyssawilk** [comment]
Tagging @ohadvano since it looks like he wrote the test.
Please do prioritize the fix - flaky tests slow down work for everyone as CI can take hours to run with enough failures.  thanks so much!

**Comment by ohadvano** [comment]
Ack, I'll try to prioritize this, although I looked in the past month and didn't see a real failures for this test. I'll try to get to this next week after the UDP tunneling work.
