### ISSUE TITLE
How to define routes based on the match with the modulo operation using header or query parameter values

### ISSUE THREAD

**Issue by whutwhu** [envoyproxy/envoy#29462]
Can we define [routes](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-route) to different clusters based on the match with the modulo operation using header or query parameter values? For example:

>   routes: [
       {
          "match": { headers[“header_name”] % 4: 0},
          "route":  { "cluster":  "cluster|0” }
       },
       {
          "match": { headers[“header_name”] % 4: 1},
          "route":  { "cluster":  "cluster|1” }
       },
       {
          "match": { headers[“header_name”] % 4: 2},
          "route":  { "cluster":  "cluster|2” }
       },
       {
          "match": { headers[“header_name”] % 4: 3},
          "route":  { "cluster":  "cluster|3” }
       }
     ]

What configurations can I make use of? Any ideas? Thanks!

**Comment by wbpcode** [comment]
It's not supported for now and it's hard to say it's a generic feature.

But I think there are multiple ways to extend envoy to support that (you can do that in you own folk or even contribute it to community):
1. New http filter. See this for how http filter could overwrite the route. https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_filters#filter-route-mutation
2. New dynamic cluster speicifier. See https://www.envoyproxy.io/docs/envoy/latest/configuration/http/cluster_specifier/cluster_specifier for example.

**Comment by whutwhu** [comment]
Thanks! @wbpcode
