### ISSUE TITLE
how i can get the upstream ip address in envoyfilter for all outbound traffics.

### ISSUE THREAD

**Issue by amankumarcs** [envoyproxy/envoy#29474]
*Title*: How i can get the upstream IP address in ENVOYFILTER for all outbound traffic?

*Description*:
In inbound, we can use the functions streamInfo:downstreamLocalAddress() and streamInfo:downstreamDirectRemoteAddress() to obtain the source and destination information. However, to fetch the upstream address, is any specific function available?

**Comment by wbpcode** [comment]
I think you can get related info from `streamInfo::upstreamInfo()` after the upstream host is selected.

**Comment by amankumarcs** [comment]
> I think you can get related info from `streamInfo::upstreamInfo()` after the upstream host is selected.

But @wbpcode I need this logic in outbound_sidecar which means if any request is going from the service then the first event will be triggered in outbound_sidecar before the upstream host is selected. is there any way I can do this?

**Comment by wbpcode** [comment]
>  I need this logic in outbound_sidecar which means if any request is going from the service then the first event will be triggered in outbound_sidecar before the upstream host is selected. is there any way I can do this?

Sorry, could you explain your scenario in more detail? I didn't get it clearly.

**Comment by amankumarcs** [comment]
> before the upstream host is selected.

let’s say i have two k8s services service1 and service2 where service1 is communicating with service2. so what I need is when service1 sends an outbound request the traffic will be captured in the SIDECAR_OUTBOUND filter and here I need downstream service ip which I can get by using downstreamLocalAddress(). but I need the service2  upstream address as well. because I need source and destination service IP and compute in Opa sidecar. In your previous answer, you mentioned using `streamInfo::upstreamInfo()`. However, it won't work as you won't receive any data. This is because you are trying to capture the upstream IP before the upstream host is selected. I hope you now have clarity about my problem.

**Comment by wbpcode** [comment]
I am not very sure what you mean. But I guess the upstream http filters may helpful to you. By the upstream http fitlers, you can do some more logics after the upstream host is selected.

https://github.com/envoyproxy/envoy/blob/main/source/docs/upstream_filters.md
