### ISSUE TITLE
Pre-submit pipeline is no longer visible for some users

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#29481]
Ive had a couple of reports from contributors unable to view the presubmit pipeline

postsubmit seems to work ok - and afaict the auth config is identical

**Comment by phlax** [comment]
cc @ohadvano

**Comment by phlax** [comment]
cc @wbpcode

**Comment by ohadvano** [comment]
btw specific I can view specific runs, if I got the link to those runs, I can't view the list of all runs in the pipeline

**Comment by phlax** [comment]
closing this as it appears to have magically fixed itself
