### ISSUE TITLE
How to trace request with two Envoys in a call flow

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#29482]
Let's say the call flow is as below:
```
client ---> Envoy (generate a x-request-id) ---> server1 ---> Envoy (generate another x-request-id) ---> server2
```
As my understanding, `x-request-id` is used to trace request. But in the case above, two different `x-request-id`s will be generated. In this case, how could Envoy trace the request? Or must I use `x-client-trace-id` to trace request?

**Comment by j2gg0s** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto


generate_request_id
([BoolValue](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#boolvalue)) Whether the connection manager will generate the [x-request-id](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-request-id) header if it does not exist. This defaults to true. Generating a random UUID4 is expensive so in high throughput scenarios where this feature is not desired it can be disabled.

preserve_external_request_id
([bool](https://developers.google.com/protocol-buffers/docs/proto#scalar)) Whether the connection manager will keep the [x-request-id](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-request-id) header if passed for a request that is edge (Edge request is the request from external clients to front Envoy) and not reset it, which is the current Envoy behaviour. This defaults to false.
