### ISSUE TITLE
Add oauth2 filter state/nonce support

### ISSUE THREAD

**Issue by bryanmcq-db** [envoyproxy/envoy#29526]
*Title*: *Add oauth2 filter state/nonce support*

*Description*:
Currently, the oauth2 filter does not implement state/nonce support. in #8571, the original filter author @derekargueta noted:

> one open question I have for now is the handling of state - randomly generated nonce in the 302 redirects that, when redirected back, should match the initial nonce. The caveat is that when redirected back, it is not guaranteed (if anything, highly unlikely) to land back on the same Envoy that generated the nonce. One possibility is to store it in a browser cookie (httpOnly, secure, etc.) so that when the user-agent is redirected back to Envoy, it carries that cookie with it which can be validated against the query parameter.

The OAuth RFC and threat model also note that this is an important best practice (see relevant links below).

From the OAuth threat model doc:
> The client should utilize the "state" request parameter to send the
   authorization server a value that binds the request to the user
   agent's authenticated state (e.g., a hash of the session cookie used
   to authenticate the user agent) when making an authorization request.
   Once authorization has been obtained from the end user, the
   authorization server redirects the end-user's user agent back to the
   client with the required binding value contained in the "state"
   parameter.

> The binding value enables the client to verify the validity of the
   request by matching the binding value to the user agent's
   authenticated state.

The OAuth filter would ideally implement this, to protect against the attack described in the link. Our security team called this out as a security gap as part of considering using this filter.

Are there any issues / concerns with adding support for this, or would a patch be welcome if someone writes the code to support it?

*Relevant Links*:
* https://datatracker.ietf.org/doc/html/rfc6819#section-5.3.5
* https://www.rfc-editor.org/rfc/rfc6749#section-10.12

**Comment by wbpcode** [comment]
cc @mattklein123

**Comment by andrefurlan-db** [comment]
Hi, any updates on this?

**Comment by ramaraochavali** [comment]
@alyssawilk Can you please mark this help wanted?

**Comment by prakash24** [comment]
> Hi, any updates on this? This filter is also utilized by the envoy gateway project and is most likely used in many production setups. The current insecure behavior of setting the state parameter to the request uri makes this filter unusable.

Can we use csrf filter as as workaround for this issue? We need this filter to be implemented in order to allow OIDC at Istio-Gatwaey.

**Comment by zhaohuabing** [comment]
This issue can be closed because it's implemented in #35919 .
