### ISSUE TITLE
add support of owned string in the `FieldType` of ObjectReflection

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#29531]
*Title*: *add support of owned string in the `FieldType` of ObjectReflection*

*Description*:

Now the `FieldType` only support string view and number. It's impossible to return a string that has independent lifetime.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
Maybe the `InlineString` is a possible solution for this requirement.

cc @kyessenov

**Comment by kyessenov** [comment]
TLVs are stored as inlined character arrays, we could use string views, no? If we don't keep the field values trivial, we would have to provide more memory management, and possible bugs with it.
