### ISSUE TITLE
Throwing incompatible issue with dynamic_ot using Jaeger-client-cpp v0.6.0 plugin

### ISSUE THREAD

**Issue by Prasoon6667** [envoyproxy/envoy#29537]
*Title*: *Throwing incompatible issue with dynamic_ot using Jaeger-client-cpp v0.6.0 plugin*

*Description*:
When I use jaeger-client-cpp plugin with envoy for tracing it shows error:-

`Filesystem config update rejected: Error adding/updating listener(s) auth_proxy_listener_https: opentracing: failed to load dynamic library: opentracing: versions of opentracing libraries are incompatible
proxy-front-envoy-1  | auth_proxy_listener_http: opentracing: failed to load dynamic library: opentracing: versions of opentracing libraries are incompatible
proxy-front-envoy-1  |
proxy-front-envoy-1  | [2023-09-10 07:01:32.870][43][debug][config] [source/common/config/filesystem_subscription_impl.cc:61] Failed configuration:`

Does envoy removed support for Jaeger-client-cpp? 

Is it because Jaeger-client-cpp in v0.6.0 uses OpenTracing 1.6.0

**Comment by adisuissa** [comment]
cc @wbpcode @Shikugawa @basvanbeek as opentracing tracer extension owners.

FWIW there is currently a plan to deprecate opentracing as the upstream project is frozen (#27401).

**Comment by wbpcode** [comment]
Yeah, because the `OPENTRACING_ABI_VERSION` is updated to `3` in the  OpenTracing 1.6.0.
