### ISSUE TITLE
The subversion of protobuf3 is important for envoy proxy? 

### ISSUE THREAD

**Issue by PoisWu** [envoyproxy/envoy#29546]
*Title*: *The subversion of protobuf3 is important for envoy proxy? *

*Description*:
> I realize that the [release of protobuf](https://github.com/protocolbuffers/protobuf/releases) is quite often, roughly once per 2 weeks. I would like to know which version of proto3 is used by envoy? I'm asking the question because I found that in the project, [proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk), the implementation is based on proto3 v.3.9.1 whereas the newest proto3 version is v.24.3 and I would like to know that a program is build on top of proto3 v3.9.1 can talk to envoy properly or not. I guess the proto3 version is important because some files have been removed/renamed such as `google/protobuf/generated_message_table_driven.h` which is in proto3 v3.9.1 whereas it can not be found in v.24.3. 

[optional *Relevant Links*:]
> ref of proto3 v.3.9.1 in the description https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/sdk_container.sh#L40
> More detail documentation of proxy-wasm-cpp-sdk which is not yet merged to the main branch can be found here: 
> -  https://github.com/mpwarres/proxy-wasm-cpp-sdk/blob/doc/docs/api_overview.md
> - https://github.com/mpwarres/proxy-wasm-cpp-sdk/blob/doc/docs/building.md

**Comment by adisuissa** [comment]
I think you are asking which version of protobuf is used.
Envoy currently uses protobuf 23.4 (see [here](https://github.com/envoyproxy/envoy/blob/35babc42015c0cfbac20d28c549544ff232f6637/bazel/repository_locations.bzl#L832) for the bazel repo, and the [version](https://github.com/envoyproxy/envoy/blob/35babc42015c0cfbac20d28c549544ff232f6637/bazel/repository_locations.bzl#L3) at the top of the file).
We attempt to keep the dependencies up to date, though some upgrades are more challenging than others.

RE the proxy-wasm-cpp-sdk repo, IIUC the code itself uses [protobuf v3.17.3](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/921039ae983ce053bf5cba78a85a3c08ff9791e5/bazel/repositories.bzl#L35). It seems that this version is somewhat old (2021), and could probably be updated.

@mpwarres may know more about the versions of proxy-wasm-cpp-sdk

**Comment by adisuissa** [comment]
> Thank you for your reply. It was really clear. My last question is that, for example: A program `A` use protobuf3 v:3.x.y try to communicate with envoy:v1.27 using protobuf3 v23.1, is there any possibility that an error occurs?

Sorry, I may be misunderstanding your qeustion.
[proto3](https://protobuf.dev/programming-guides/proto3/) defines the schema syntax. [Protobuf](https://github.com/protocolbuffers/protobuf) implements the tooling to parse these schemas.
2 binaries can use different versions of protobuf, but the schema (proto definitions) will stay the same, and both should be able to understand them independently. Moreover, they will be able to pass the instances (protos) between the binaries and process them (convert them to an object in the appropriate programming language).

**Comment by mpwarres** [comment]
Thanks, filed proxy-wasm/proxy-wasm-cpp-sdk#159 to address. Even though v3.9.1 is quite old, as @adisuissa mentioned it is wire compatible with other versions. Internal implementation differences with the version used by Envoy, such as `google/protobuf/generated_message_table_driven.h`, shouldn't pose an issue since proxy-wasm-cpp-sdk and emscripten will compile them to Wasm.

The one case I'm less sure about is if you are using proxy-wasm-cpp-host NullVm as your runtime, in which case I think your plugin code (compiled to a native library, not Wasm) might need to link with the same protobuf library as the rest of Envoy.

**Comment by PoisWu** [comment]
I see! Thank you for your responses. It’s much appreciated. I understand better now the subtle difference between proto3 and protobuf. 

> The one case I'm less sure about is if you are using proxy-wasm-cpp-host NullVm as your runtime, in which case I think your plugin code (compiled to a native library, not Wasm) might need to link with the same protobuf library as the rest of Envoy.

You may be right. Since it's my first time using proxy-wasm-cpp-sdk, I'm learning therefore how to read the error message and thank you for the hint.
