### ISSUE TITLE
URL normalization

### ISSUE THREAD

**Issue by Lookyan** [envoyproxy/envoy#2956]
*URL normalization*

*Description*:
Can't find an URL normalization option (https://en.wikipedia.org/wiki/URL_normalization). 

Now we have an option prefix rewrite for vhosts. For example we can replace `/service-hello` with `/` and proxy to root address of service. But in case of `/service-hello -> /` replacement if we request to this address: http://envoy:8888/service-hello/_healthz then we will get a request to http://helloservice//_healthz 
It would be nice if we had this feature of URL normalization if we don't have one.

**Comment by dio** [comment]
> But in case of /service-hello -> / replacement if we request to this address: http://envoy:8888/service-hello/_healthz then we will get a request to http://helloservice//_healthz

@Lookyan could you elaborate more on this? Thank you!

**Comment by Lookyan** [comment]
@dio at least I want to have a feature of multiple slash replacement with one slash during proxying to upstream. 
So, we can have URL like this: http://smth//a/b///c
And we should make a request to this URL in this case: http://smth/a/b/c

**Comment by dio** [comment]
@Lookyan got it. Sorry I didn't get that additional slashes.
