### ISSUE TITLE
Golang filter implementation issue

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#29574]
Hi Envoy team,

We found the following issue: following the documentation here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter.html after implementing the StreamFilter interface and building the shared object, in the logs it says the following: 

[2023-09-11 11:41:06.976][7][warning][config] [source/common/config/new_delta_subscription_state.cc:288] delta config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ADMIN: Didn't find a registered implementation for 'envoy.filters.http.golang' with type URL: 'envoy.extensions.filters.http.golang.v3alpha.Config'
demo: Didn't find a registered implementation for 'envoy.filters.http.golang' with type URL: 'envoy.extensions.filters.http.golang.v3alpha.Config'
mtls: Didn't find a registered implementation for 'envoy.filters.http.golang' with type URL: 'envoy.extensions.filters.http.golang.v3alpha.Config'

The Envoy configuration gets rejected because of this. Here is a code snippet with the Golang filter configurations:

golangFilterConfig, err := anypb.New(&golangFilter.Config{
		LibraryId:   "my-plugin-id",
		LibraryPath: "/simple.so",
		PluginName:  "my_plugin",
	})
	
I checked and the shared object 'simple.so' exists on the given absolute path(/simple.so).

The implementation of the interface is the following: 

type filter struct {
	api.PassThroughStreamDecoderFilter
	api.PassThroughStreamEncoderFilter

	callbacks api.FilterCallbackHandler
	//path      string
	config *config
}

func (f *filter) OnLog() {

}

func (f *filter) OnDestroy(reason api.DestroyReason) {

}

func (f *filter) DecodeHeaders(header api.RequestHeaderMap, endStream bool) api.StatusType {
	return api.Continue
}

func (f *filter) DecodeData(data api.BufferInstance, endStream bool) api.StatusType {
	return api.Continue
}

func (f *filter) DecodeTrailers(trailer api.RequestTrailerMap) api.StatusType {
	return api.Continue
}

func (*filter) EncodeHeaders(header api.ResponseHeaderMap, endStream bool) api.StatusType {
	return api.Continue
}

func (*filter) EncodeData(data api.BufferInstance, endStream bool) api.StatusType {
	return api.Continue
}

func (*filter) EncodeTrailers(trailer api.ResponseTrailerMap) api.StatusType {
	return api.Continue
}

Do you have any insight what might be the issue? Any help would be highly appreciated.

**Comment by StarryVae** [comment]
Maybe the golang extension is not supported in the envoy version you used.

**Comment by DimitarHKostov** [comment]
I tried with versions 1.26 and 1.27 of envoy. Btw, I'm using the envoy base docker image: 
FROM envoyproxy/envoy:v1.26-latest as envoy..

**Comment by StarryVae** [comment]
emm, maybe the version you used do not include contrib extensions, you can try this `envoyproxy/envoy:contrib-<version>`.

![image](https://github.com/envoyproxy/envoy/assets/23182024/30767c43-30fd-44a9-837f-14147d96493c)
