### ISSUE TITLE
Support custom LcTrie fill_factor on IPTaggingFilter

### ISSUE THREAD

**Issue by relvira** [envoyproxy/envoy#29579]
*Title*: *Support custom LcTrie fill_factor on IPTaggingFilter*

*Description*:

We are intending to use the IPTaggingFilter to decorate requests flowing through Envoyproxy with information like Country or [AS Number ](https://en.wikipedia.org/wiki/Autonomous_system_(Internet)). This requires mapping the entire IPv4 dataset to the AS Number who owns a given CIDR, which results in about 300k CIDRs and 75k AS Numbers.

This causes the LcTrie to yield an error and envoy to not want to load the ip tags list:

```
[2023-09-08 02:48:05.916][3678203][warning][config] [external/envoy/source/common/config/filesystem_subscription_impl.cc:60] Filesystem config update rejected: The input vector has '498709' CIDR range entries. LC-Trie can only support '262144' CIDR ranges with the specified fill factor.
```

As noticed on https://github.com/envoyproxy/envoy/blob/main/source/common/network/lc_trie.h#L58 the `fill_factor` can be customised. This means we could update the IPTaggingFilter to allow a new attribute in the proto to account for a larger `LcTrie` [here](https://slack-github.com/slack/envoy/blob/master/source/extensions/filters/http/ip_tagging/ip_tagging_filter.cc#L55).

Is there any other option to achieve our needs, or does this sound like a feasible feature to implement?

**Comment by adisuissa** [comment]
I don't think there's a way to change the trie size without introducing this to the config and the code.

cc @alyssawilk @JuniorHsu as codeowners of the IP-Tagging filter.

**Comment by alyssawilk** [comment]
yeah I think if you need to support a larger fill factor you're going to need to tweak the code and add tests.  Happy to review if you do so!
