### ISSUE TITLE
OpenTelemetry tracer - Hability to configure a custom sampler

### ISSUE THREAD

**Issue by joaopgrassi** [envoyproxy/envoy#29578]
*Description*:

The OpenTelemetry project defines the concept of a [Sampler API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler). A sampler allows controlling the spans you send to your observability backend, resulting in many benefits, such as lowering costs.

A sampler is associated with a `TracerProvider` in OpenTelemetry and there's a few [built-in samplers](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers).

In Envoy, we have the [OpenTelemetry tracer](https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry), which can be seen as similar to the `TracerProvider` in OTel. The OTel tracer in Envoy is not flexible in regards to sampling. It only "forwards" the tracing decision that is passed down from Envoy via the `Tracing::Decision tracing_decision`. From my understanding that's a "custom" thing, that is also based on an "request id" https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/request_id/uuid/v3/uuid.proto#envoy-v3-api-field-extensions-request-id-uuid-v3-uuidrequestidconfig-use-request-id-for-trace-sampling. Meaning, this is not really "compliant" with what the OpenTelemetry project defines.

Users of OTel might want to control sampling in different ways, following the samplers that the OTel project defines. Moreover, observability vendors might also want to offer their own samplers which aligns with the decisions done by monitoring Agents for example, resulting in a higher chance of having complete traces, and be able to achieve things such as extracting metrics from spans.

By having the flexibility to configure a custom sampler in the OpenTelemetry tracer in Envoy, users have then full control on the volume of data it produces.

*Feature request*

1. Introduce a new interface inside the `opentelemetry` folder for a sampler. The interface would follow the [Sampler interface](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler) as defined in the OpenTelemetry specification. It would leverage the Envoy extension framework.

2. When `startSpan` is called, the OpenTelemetry tracer in Envoy would then check if it was configured with a custom sampler. If it was, it defers the sampling decision to it, otherwise it falls back to the current behavior of using the `Tracing::Decision tracing_decision`.

3. This then allows anyone (Cloud vendors, Observability back-ends etc) to define their own samplers in a new folder `tracers/opentelemetry/samplers`

4. Allow the sampler to be configured by the user: Something like this:

```yaml
tracing:
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      sampler:
        name: envoy.opentelemetry.samplers.ParentBasedSampler
```

I believe the addition of this interface will benefit everyone and will open up for a lot of great opportunities in the observability space for Envoy.

**Comment by adisuissa** [comment]
A high-level question: is the sampling interface unique to Open-Telemetry? Can it be used by other tracers?

cc @mattklein123 @wbpcode @htuch as main tracing extension owners

**Comment by joaopgrassi** [comment]
> A high-level question: is the sampling interface unique to Open-Telemetry? Can it be used by other tracers?

That's a good question. I think the idea would very much like apply to all tracers, not just the OTel, because of the fact they all implement the same Driver interface, thus the same functionality could be integrated there. 

What I'm not sure if it makes sense. For ex, the XRay Tracer has its own sampling logic (it reads it from a JSON file), so that definitely does not seem to apply. I can't speak for the Datadog one as well, since it seems it forwards the spans to their agent, which may/may not do sampling there. 

`dynamiac_ot` is getting deprecated (IIUC) given we want to remove the dependency. Then we are left with `opencensus`, `zipkin` and `skywalking`.

I'm probably biased, but the way I see, more and more people are adopting OTel - both users and observability vendors and I believe OTel is going to be the de facto solution for observability in general. 

So, my response would be: It would apply to _some_ tracers in Envoy, but I'm not sure it makes sense to invest in other tracers at this point.

**Comment by htuch** [comment]
If the sampler extensions in OT only make use of as inputs data available to all tracers, then it seems fine to make it generic. If there are any gymnastics then OT specific is the way to go.

**Comment by joaopgrassi** [comment]
Also, the OTel sampler spec is particular in for example what it should return and how that return is used. That may not apply to all tracers. For ex, `ShouldSample` returns a `SamplingResult`. That contains a set of attributes that should be added to the span. Not sure if this would be OK change in the existing tracers.

**Comment by htuch** [comment]
OK, sounds like making it OT specific is the right option.

**Comment by samohte** [comment]
I am interested in working on this issue. I think it would be best to introduce a generic Sampler interface following the opentelemetry specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler
An "AlwaysOnSampler" can be added as reference implementation.

**Comment by samohte** [comment]
I opened a PR and appreciate your feedback.
