### ISSUE TITLE
Mutation rules do not allow specific header modifications from external processor

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#29573]
Hi Envoy team, 

we found the following issue: using external processor(with GRPC) we want to be able to modify the 'host' header, internal 'x-envoy-* headers etc. The two properties that we are interested in are 'allow-envoy'(for the internal envoy headers) and 'allow-all-routing'. After changing the values of the two properties to true we still can not add/override the mentioned headers from the external processor. Here is a code snippet with the configurations we use for the external processor:

externalProcessingFilterConfig, err := anypb.New(&extProc.ExternalProcessor{
		ProcessingMode: processingMode,
		MessageTimeout: durationpb.New(DefaultTimeoutInSeconds * time.Second),
		GrpcService:    &grpcService,
		MutationRules: &mutation_rulesv3.HeaderMutationRules{
			AllowEnvoy:      &wrapperspb.BoolValue{Value: true},
			AllowAllRouting: &wrapperspb.BoolValue{Value: true},
		},
	})
	
In the external processor server in the HeaderResponse -> CommonResponse -> HeaderMutation -> SetHeaders it says in the documentation: "Add or replace HTTP headers. Attempts to set the value of any “x-envoy“ header, and attempts to set the “:method“, “:authority“, “:scheme“, or “host“ headers will be ignored.". It seems that this contradicts with the MutationRules for the external processing filter. Here is a snippet of the configuration: 

headersResponse := &pb.HeadersResponse{
		Response: &pb.CommonResponse{
			HeaderMutation: &pb.HeaderMutation{
				SetHeaders:    headersToSet, //in the docu for this field it says we can not override the desired headers
				RemoveHeaders: headersToRemove,
			},
			ClearRouteCache: true,
		},
	}
	processingResponse := &pb.ProcessingResponse{
		Response: &pb.ProcessingResponse_RequestHeaders{
			RequestHeaders: headersResponse,
		},
	}

	return processingResponse
	
Do we miss something? Any help will be highly appreciated.

**Comment by adisuissa** [comment]
I think these types of headers are intentionally immutable.
cc @yanjunxiang-google @tyxia to confirm.

**Comment by yanjunxiang-google** [comment]
Do you have the envoy ext_proc filter configured with allow_all_routing and allow_envoy?

**Comment by DimitarHKostov** [comment]
Yes, both are set to true. Is there a known issue in any version of envoy when it comes to this properties?

**Comment by yanjunxiang-google** [comment]
Let me try to reproduce the issue.

**Comment by yanjunxiang-google** [comment]
I created an test and it is ok to modify the host header and add x-envoy-xxx headers. Please check this PR:

https://github.com/envoyproxy/envoy/pull/29886

Could you please let me know the ext_proc response you are sending back which contains the header mutation?   

BTW, if you want to modify the "host" header, you should just send back the "host" header with a new value, and leave the "append" to be false. That way the "host" header will be modified.  You can not remove "host" header, then add a new "host" header. "remove" operation is not allowed for "host" header.
