### ISSUE TITLE
Request http2 configuration option to specify SETTINGS_MAX_HEADER_LIST_SIZE

### ISSUE THREAD

**Issue by JLofgren** [envoyproxy/envoy#2958]
*Title*:
I would like a way to configure an HTTP2 max header size that envoy should advertise to upstream peers.

*Description*:
Http/2 has a settings frame that may include the SETTINGS_MAX_HEADER_LIST_SIZE. If this value is set by a server, it is an indication to the client that they should not attempt to send a header larger than that max size or the server will throw an error. If the value is not explicitly declared by the server, then the client should feel free to send arbitrarily long headers.

I am dealing with a misbehaving client implementation that enforces an arbitrary default max header size even when the server has not specified any limit. If I could have Envoy advertise a sufficiently large max header size, that would be an acceptable workaround.

**Comment by srikailash** [comment]
Hello @mattklein123, i have a PR ready for this. Let me know if this https://github.com/envoyproxy/envoy/commit/0479c8ac934a93dc31027e176d6645127e7bb080 looks good. Thanks!

**Comment by mattklein123** [comment]
@srikailash please just open a PR if you would like code reviewed.

**Comment by mk46** [comment]
@mattklein123 I don't think anyone is working on this and want to open a PR.

**Comment by sohamchari** [comment]
Hi @JLofgren, I would like to take up this issue. Looking forward to my contribution!

**Comment by alyssawilk** [comment]
I think this is accomplished via https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/core/v3/protocol.proto#L546 
@sohamchari please let me know if I'm incorrect and I'll reopen
