### ISSUE TITLE
`quic_protocol_integration_test` is extremely flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#29595]
3 out of the last 10 postsubmit runs have failed with a `quic_proto` flake

im also seeing many similar incidents on presubmit

its not clear exactly what the issue is but this is the summary

```console

[  FAILED  ] DownstreamProtocols/ProtocolIntegrationTest.LargeRequestMethod/IPv6_Http3Downstream_HttpUpstreamBalsaParserNghttp2NoDeferredProcessingLegacy, where GetParam() = 24-byte object <01-00 00-00 02-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00>

 1 FAILED TEST
================================================================================
INFO: Elapsed time: 702.659s, Critical Path: 393.72s
INFO: 35229 processes: 20853 remote cache hit, 12946 internal, 1 local, 1429 remote.
//test/integration:quic_protocol_integration_test                        FAILED in 1 out of 16 in 95.0s
  Stats over 16 runs: max = 95.0s, min = 71.3s, avg = 81.6s, dev = 6.5s

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=149058&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc&l=3486

**Comment by phlax** [comment]
cc @danzh2010

**Comment by danzh2010** [comment]
This is not an HTTP/3 issue. ProtocolIntegrationTest.LargeRequestMethod with HTTP upstream is flaky. I would repro with HTTP/2 downstream as well:
$ bazel test test/integration:protocol_integration_test --test_filter="*LargeRequestMethod/*Http2Downstream_HttpUpstream*"  -c opt  --runs_per_test=2000,

I saw the upstream socket received a read error ECONNRESET:
```[2023-09-13 15:06:38.509][28][trace][connection] [source/common/network/raw_buffer_socket.cc:39] [Tags: "ConnectionId":"2"] read error: Connection reset by peer, code: 9
```

But I don't know why the fake upstream close the socket with this error.

**Comment by phlax** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=149128&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc&l=3347

**Comment by botengyao** [comment]
Checking in for the root cause, it may be related to the recent added feature to detect RST from the peer.

**Comment by danzh2010** [comment]
> Checking in for the root cause, it may be related to the recent added feature to detect RST from the peer.

Any related PR?

**Comment by botengyao** [comment]
https://github.com/envoyproxy/envoy/pull/28817

**Comment by danzh2010** [comment]
https://github.com/envoyproxy/envoy/pull/28817 looks suspicious as it introduced SO_LINGER=0 socket option. @botengyao could you please take a look at this issue?

**Comment by danzh2010** [comment]
/assign @botengyao

Feel free to redirect it if needed.

**Comment by botengyao** [comment]
> #28817 looks suspicious as it introduced SO_LINGER=0 socket option. @botengyao could you please take a look at this issue?

Thanks @danzh2010, Looking into the details, I suspect it is more a test problem, because we didn't distinguish the close type at connection level before, but right now it cannot if the connection is reset by the peer.

**Comment by botengyao** [comment]
I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.

**Comment by danzh2010** [comment]
> I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.

Is this an issue of the upstream connection discard data upon RST or the downstream connection send RST in an undesired case?

**Comment by botengyao** [comment]
> > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> 
> Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?

It's a issue from upstream read. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before. 

I am not sure why `invalid :method` will lead upstream send rst, but I suspect it is a fragment mismatch to act as passive RST.

**Comment by danzh2010** [comment]
> > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > 
> > 
> > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> 
> It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> 

I'm not sure if the payload with RST is still reliable or not.  

> I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.

One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.

**Comment by botengyao** [comment]
> > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > 
> > > 
> > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > 
> > 
> > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> 
> I'm not sure if the payload with RST is still reliable or not.
> 
> > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> 
> One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.

Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fixed PR to deflake it. https://github.com/envoyproxy/envoy/pull/29616

**Comment by danzh2010** [comment]
> > > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > > 
> > > > 
> > > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > > 
> > > 
> > > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> > 
> > 
> > I'm not sure if the payload with RST is still reliable or not.
> > > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> > 
> > 
> > One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.
> 
> Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fix PR to deflake it. #29616

Should the receiver continue processing the payload as #29616 does in light of RST? I'm not sure about this. I suspect the payload can be a partial response.

**Comment by botengyao** [comment]
> > > > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > > > 
> > > > > 
> > > > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > > > 
> > > > 
> > > > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> > > 
> > > 
> > > I'm not sure if the payload with RST is still reliable or not.
> > > > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> > > 
> > > 
> > > One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.
> > 
> > 
> > Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fix PR to deflake it. #29616
> 
> Should the receiver continue processing the payload as #29616 does in light of RST? I'm not sure about this. I suspect the payload can be a partial response.

Yes, there is a `do {recv()} while` loop in the wrapped transport socket. It will lead to [data, data, RST bit] from the socket `recv`. Before when I read the RFC and RST should always come as a single bit and discard the segment, but there may be buffered data before RST in the wrapped transport socket.

**Comment by danzh2010** [comment]
> > > > > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > > > > 
> > > > > > 
> > > > > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > > > > 
> > > > > 
> > > > > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> > > > 
> > > > 
> > > > I'm not sure if the payload with RST is still reliable or not.
> > > > > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> > > > 
> > > > 
> > > > One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.
> > > 
> > > 
> > > Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fix PR to deflake it. #29616
> > 
> > 
> > Should the receiver continue processing the payload as #29616 does in light of RST? I'm not sure about this. I suspect the payload can be a partial response.
> 
> Yes, there is a `do {recv()} while` loop in the wrapped transport socket. It will lead to [data, data, RST bit] from the socket `recv`. Before when I read the RFC and RST should always come as a single bit and discard the segment, but there may be buffered data before RST in the wrapped transport socket.

Are you sure if the incoming payload comes as [data, data, RST bit] , the RST bit will bubble up after finishing reading the preceding data? What if one of the packets before RST gets lost? I doubt the receiving endpoint will wait for the retransmission and then bubble up the read error?

**Comment by botengyao** [comment]
> > > > > > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > > > > > 
> > > > > > > 
> > > > > > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > > > > > 
> > > > > > 
> > > > > > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> > > > > 
> > > > > 
> > > > > I'm not sure if the payload with RST is still reliable or not.
> > > > > > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> > > > > 
> > > > > 
> > > > > One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.
> > > > 
> > > > 
> > > > Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fix PR to deflake it. #29616
> > > 
> > > 
> > > Should the receiver continue processing the payload as #29616 does in light of RST? I'm not sure about this. I suspect the payload can be a partial response.
> > 
> > 
> > Yes, there is a `do {recv()} while` loop in the wrapped transport socket. It will lead to [data, data, RST bit] from the socket `recv`. Before when I read the RFC and RST should always come as a single bit and discard the segment, but there may be buffered data before RST in the wrapped transport socket.
> 
> Are you sure if the incoming payload comes as [data, data, RST bit] , the RST bit will bubble up after finishing reading the preceding data? What if one of the packets before RST gets lost? I doubt the receiving endpoint will wait for the retransmission and then bubble up the read error?

[data, data, rst bit] is for the wrapped socket not the sys socket, looking at this while loop: https://github.com/envoyproxy/envoy/blob/16da1981d89aecdbfcaa3ffedc36879f32d37cdb/source/common/network/raw_buffer_socket.cc#L16-L46

There maybe 2 or more loop for `recv`, and the last `recv` will lead to RST.

**Comment by botengyao** [comment]
> > > > > > > > > > I see, it is possible that we will get data + rst in from the wrapped transport socket since there is a do {} while loop. We should trigger the onRead if there is any processed data. Raising a PR.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Is this an issue of the upstream connection discarding data upon RST or the downstream connection sending RST in an undesired case?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's a issue for reading from upstream. Envoy is discarding from read side leading to 503 error. RST is not actively triggered by Envoy, ie, setting SO_LINGER=0 from Envoy. Without handling RST in Envoy, we can still get the reset from peer (from upstream), and we treat it as a normal close before.
> > > > > > > 
> > > > > > > 
> > > > > > > I'm not sure if the payload with RST is still reliable or not.
> > > > > > > > I am not sure why `invalid :method` will lead upstream send RST, but I suspect it is a fragment mismatch to act as passive RST.
> > > > > > > 
> > > > > > > 
> > > > > > > One can specify RST bit in Linux using SO_LINGER=0 + close(), I'm wondering if this the reason upstream send RST.
> > > > > > 
> > > > > > 
> > > > > > Yes, but the flake is not caused by actively setting by Envoy, and it is from the detection part. I already have the fix PR to deflake it. #29616
> > > > > 
> > > > > 
> > > > > Should the receiver continue processing the payload as #29616 does in light of RST? I'm not sure about this. I suspect the payload can be a partial response.
> > > > 
> > > > 
> > > > Yes, there is a `do {recv()} while` loop in the wrapped transport socket. It will lead to [data, data, RST bit] from the socket `recv`. Before when I read the RFC and RST should always come as a single bit and discard the segment, but there may be buffered data before RST in the wrapped transport socket.
> > > 
> > > 
> > > Are you sure if the incoming payload comes as [data, data, RST bit] , the RST bit will bubble up after finishing reading the preceding data? What if one of the packets before RST gets lost? I doubt the receiving endpoint will wait for the retransmission and then bubble up the read error?
> > 
> > 
> > [data, data, rst bit] is for the wrapped socket not the sys socket, looking at this while loop:
> > https://github.com/envoyproxy/envoy/blob/16da1981d89aecdbfcaa3ffedc36879f32d37cdb/source/common/network/raw_buffer_socket.cc#L16-L46
> > 
> > There maybe 2 or more loop for `recv/read`, and the last `read` will lead to RST.
> 
> Those data from proceeding read/recv() also can be partial response, right?

It is possible, but whenever we get RST, there will be no more data from peer and we should close. [rfc793](https://www.ietf.org/rfc/rfc793.txt) for `If the RST bit is set`.
