### ISSUE TITLE
Deprecate/remove alts transport socket

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#29598]
We believe there are no external users of this extension so the currently plan is to remove it after the 6 month deprecation cycle.   Please let us know if this is a problem.

**Comment by barbarity** [comment]
Hi, We are currently using it in our production environment in more than 200 sites.

Where does the assumption of no use come from?

We just noticed by a major issue with it in v1.26.5 and found out this, I don't think many customers would find out before it's too late.
