### ISSUE TITLE
How should I proxy the gRPC services of Hyperledger Fabric peer and orderer nodes in two different kubernetes clusters through Envoy?

### ISSUE THREAD

**Issue by JasonCeng** [envoyproxy/envoy#29599]
*Title*: *How should I proxy the gRPC services of Hyperledger Fabric peer and orderer nodes in two different kubernetes clusters through Envoy?*

*Description*:
>I have two kubernetes clusters to deploy Hyperledger Fabric peer and orderer nodes, but they can't connect to each others by p2p connection, how should I proxy the gRPC services of Hyperledger Fabric peer and orderer nodes in two different kubernetes clusters through Envoy? Thanks in advance!

[optional *Relevant Links*:]
>[hyperledger fabric docs](https://hyperledger-fabric.readthedocs.io/en/latest/whatis.html)

**Comment by adisuissa** [comment]
I'm not sure we can help much here, as it is dependent on the deployment model and exact configurations that are being used. Technically speaking, the proxy needs to be able to receive connections from network1, and create a connection in network2.
