### ISSUE TITLE
Content-Encoding: snappy returns an Empty Response

### ISSUE THREAD

**Issue by smoore-resideo** [envoyproxy/envoy#29609]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
I am attempting to use leverage Cortex Metrics for centralized monitoring of multiple clusters. I have cortex installed on the centralized cluster with Istio for the ingress, when I attempt to configure the remote_write from the secondary cluster to the centralized one the secondary prometheus fails to write to the centralized one.

I discovered that upon testing whenever I use `Content-Encoding: snappy` the `curl` returns `Empty Response`. If I change the `Content-Encoding` to `gzip` the request is handled and forwarded to the correct pod.

I appreciate any help.

*Repro steps*:
> 
Test Request
```
 cat <<EOF | curl   -v -H 'Content-Type: application/x-protobuf' - -H 'Content-Encoding: snappy' --data-binary @- https://$CORTEX_INGRESS/api/v1/push 
  # TYPE some_metric counter
  up{label="somelabel"} 42
  # TYPE another_metric gauge
  # HELP another_metric Just an example.
  another_metric 2398.283
  EOF
EOF
```

Test Response
```
*  SSL certificate verify ok.
> POST /api/v1/push HTTP/1.1
> Host: some.host
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/x-protobuf
> Accept-Encoding: *
> Content-Encoding: snappy
> Content-Length: 156
>
* upload completely sent off: 156 out of 156 bytes
* Empty reply from server
```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by adisuissa** [comment]
> _Description_: I am attempting to use leverage Cortex Metrics for centralized monitoring of multiple clusters. I have cortex installed on the centralized cluster with Istio for the ingress, when I attempt to configure the remote_write from the secondary cluster to the centralized one the secondary prometheus fails to write to the centralized one.
> 
> I discovered that upon testing whenever I use `Content-Encoding: snappy` the `curl` returns `Empty Response`. If I change the `Content-Encoding` to `gzip` the request is handled and forwarded to the correct pod.
> 

From your description it is unclear if when `snappy` content-encoding is used the request is forwarded or not to the pod.
Do you see any errors on the Envoy side?
Can you run Envoy with trace/debug logs?
Also what is Envoy's config?
