### ISSUE TITLE
Golang filter: remove the lock in the headerMapImpl 

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#29617]
Currently, we have lock protection in most operation in the headerMapImpl.

This feature provides few advantages:
1. The Go's std http.Header is not concurrent safe. So if concurrent access to the header is needed, the developer may already add the lock by themselves.  It would be great to align the code with the Go's official implementation if the cost is low.
2. It's rare for the developer to access the header concurrently. Otherwise, the Go developer will make the Header concurrent safe.

At the same time, it has brought some troubles:
1. Performance cost. Even the fast path of the mutex is similar to atomic operation, but an atomic operation is still an extra operation. And most of time we don't need to pay this cost.
2. Complex code. First of all, we need to add lock protection to many header operations. Secondly, we may add lock protection to the Data buffer operations for the same reason we keep the lock protection in the header part. Last, by not least, complex code will cause buggy code. For instance, the current `Value` method is not concurrent safe because we return the slice without lock protection.
3. Potential deadlock. See `Range` method.
4. Extra copy. See `RangeWithCopy` method.

I would recommend getting rid of the lock and telling users that the headerMapImpl is not concurrent safe as the official Go's implementation. This way is more maintainable.

**Comment by spacewander** [comment]
CC @doujiang24

**Comment by doujiang24** [comment]
Background of why it's added:
Since the `Concurrent map writes` panic is not recoverable in golang runtime, that will lead to the Envoy process crash, which might be a bit of overhead punishment for a plugin developer.

I'm not against removing it, but we need to balance the overhead while people using it as a plugin developer, not a Golang application developer as normal.
i.e. well-documented risk notification, or concurrent detect just like the golang runtime, but before the runtime panics.

**Comment by doujiang24** [comment]
@spacewander Cool~
First of all, I think it's a good solution to drop the lock.

I prefer to allow modification during iterating.

for the performance, `Get` API in the pure Go side might not be the key important thing.
We also care about the performance for init a header map.

we could choose a map implementation, depending on the performance benchmark, i.e.
1. init 20 key-value pairs header map
2. Get read performance in such a map.

**Comment by spacewander** [comment]
@doujiang24 
Here is the benchmark:
```go
package benchmarks

import (
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/cornelk/hashmap"
	tidwall "github.com/tidwall/hashmap"
)

const (
	SIZE = 20
)

func getSlices() [][]string {
	m := make([][]string, SIZE)
	for i := 0; i < SIZE; i++ {
		k := strings.Repeat(strconv.Itoa(i), 10)
		v := strings.Repeat(strconv.Itoa(i), 10)
		m[i] = []string{k, v}
	}

	return m
}

func BenchmarkInit_GoMap(b *testing.B) {
	data := getSlices()
	for i := 0; i < b.N; i++ {
		m := make(map[string][]string, SIZE)
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			m[k] = []string{data[j][1]}
		}
	}
}

func BenchmarkInit_GoMapLock(b *testing.B) {
	data := getSlices()
	lock := sync.Mutex{}
	for i := 0; i < b.N; i++ {
		m := make(map[string][]string, SIZE)
		lock.Lock()
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			m[k] = []string{data[j][1]}
		}
		lock.Unlock()
	}
}

func BenchmarkInit_CornelkHashMap(b *testing.B) {
	data := getSlices()
	for i := 0; i < b.N; i++ {
		m := hashmap.NewSized[string, []string](SIZE)
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			m.Set(k, []string{data[j][1]})
		}
	}
}

func BenchmarkInit_TidWallHashMap(b *testing.B) {
	data := getSlices()
	for i := 0; i < b.N; i++ {
		m := tidwall.New[string, []string](SIZE)
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			m.Set(k, []string{data[j][1]})
		}
	}
}

func BenchmarkRead_GoMap(b *testing.B) {
	data := getSlices()
	m := make(map[string][]string, SIZE)
	for j := 0; j < SIZE; j++ {
		k := data[j][0]
		m[k] = []string{data[j][1]}
	}

	var res []string
	for i := 0; i < b.N; i++ {
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			res = m[k]
			if res[0] != data[j][1] {
				b.Fail()
			}
		}
	}
}

func BenchmarkRead_GoMapLock(b *testing.B) {
	data := getSlices()
	lock := sync.RWMutex{}
	m := make(map[string][]string, SIZE)
	for j := 0; j < SIZE; j++ {
		k := data[j][0]
		m[k] = []string{data[j][1]}
	}

	var res []string
	for i := 0; i < b.N; i++ {
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			lock.RLock()
			res = m[k]
			lock.RUnlock()
			if res[0] != data[j][1] {
				b.Fail()
			}
		}
	}
}

func BenchmarkRead_CornelkHashMap(b *testing.B) {
	data := getSlices()
	m := hashmap.NewSized[string, []string](SIZE)
	for j := 0; j < SIZE; j++ {
		k := data[j][0]
		m.Set(k, []string{data[j][1]})
	}

	var res []string
	for i := 0; i < b.N; i++ {
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			res, _ = m.Get(k)
			if res[0] != data[j][1] {
				b.Fail()
			}
		}
	}
}

func BenchmarkRead_TidWallHashMap(b *testing.B) {
	data := getSlices()
	m := tidwall.New[string, []string](SIZE)
	for j := 0; j < SIZE; j++ {
		k := data[j][0]
		m.Set(k, []string{data[j][1]})
	}

	var res []string
	for i := 0; i < b.N; i++ {
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			res, _ = m.Get(k)
			if res[0] != data[j][1] {
				b.Fail()
			}
		}
	}
}

```

```
$ go test -cpu 1 -bench=.
goos: darwin
goarch: arm64
pkg: github.com/cornelk/hashmap/benchmarks
BenchmarkInit_GoMap          	1000000	     1072 ns/op
BenchmarkInit_GoMapLock      	1000000	     1083 ns/op
BenchmarkInit_CornelkHashMap 	 443350	     2661 ns/op
BenchmarkInit_TidWallHashMap 	 969040	     1096 ns/op
BenchmarkRead_GoMap          	6137194	      194.7 ns/op
BenchmarkRead_GoMapLock      	4452048	      270.9 ns/op
BenchmarkRead_CornelkHashMap 	3534392	      338.9 ns/op
BenchmarkRead_TidWallHashMap 	4520848	      265.1 ns/op
PASS
ok  	github.com/cornelk/hashmap/benchmarks	10.835s
```

In the non-concurrent test, regular Map/Map with lock/tidwall's hashmap have similar init performance, and tidwall's hashmap is slightly 2% faster than Map with lock in read, while regular map is the fastest.

**Comment by doujiang24** [comment]
looks like `tidwall` has better performance.

> but it doesn't support modifying the key during the Range. So if we need to use it, we have to disable modifying during iterating.

but it lacks capability.

how about "add concurrent detection just like the golang runtime" with the regular map?
we just panic before golang runtime.

**Comment by spacewander** [comment]
I have added two more groups:
1. use sync.Map (GoMapAtomic)
2. use home-made concurrent detector implemented with atomic (GoSyncMap)

And rerun the test in amd64 machine:
```
 ￥ go test -cpu 1 -bench=.
goos: linux
goarch: amd64
pkg: github.com/spacewander/benchmark
cpu: 12th Gen Intel(R) Core(TM) i7-12700H
BenchmarkInit_GoMap              1000000              1156 ns/op
BenchmarkInit_GoMapAtomic         950929              1262 ns/op
BenchmarkInit_GoMapLock          1029072              1143 ns/op
BenchmarkInit_GoSyncMap           200858              5819 ns/op
BenchmarkInit_CornelkHashMap      364845              3275 ns/op
BenchmarkInit_TidWallHashMap      868758              1316 ns/op
BenchmarkRead_GoMap              6248847               210.0 ns/op
BenchmarkRead_GoMapAtomic        3328274               334.7 ns/op
BenchmarkRead_GoMapLock          3857452               300.1 ns/op
BenchmarkRead_GoSyncMap          3008115               406.9 ns/op
BenchmarkRead_CornelkHashMap     5505070               220.0 ns/op
BenchmarkRead_TidWallHashMap     5356521               219.2 ns/op
PASS
```

Conclusion:
1. Both the third party hashmap perform almost as fast as the go map in the read test on amd64 machine
2. cornelk/hashmap is still much slower than the go map in the init test
3. the performance is architecture-dependent.

**Comment by spacewander** [comment]
Here is the home-made detector:
```
func markAccess(flag *int32) {
	if atomic.LoadInt32(flag) != 0 {
		panic("concurrent operation detected")
	}
	atomic.StoreInt32(flag, 1)
}

func unmarkAccess(flag *int32) {
	atomic.StoreInt32(flag, 0)
}

func BenchmarkInit_GoMapAtomic(b *testing.B) {
	data := getSlices()
	for i := 0; i < b.N; i++ {
		m := make(map[string][]string, SIZE)
		var flag int32
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			markAccess(&flag)
			m[k] = []string{data[j][1]}
			unmarkAccess(&flag)
		}
	}
}

func BenchmarkRead_GoMapAtomic(b *testing.B) {
	data := getSlices()
	m := make(map[string][]string, SIZE)
	var flag int32
	for j := 0; j < SIZE; j++ {
		k := data[j][0]
		markAccess(&flag)
		m[k] = []string{data[j][1]}
		unmarkAccess(&flag)
	}

	var res []string
	for i := 0; i < b.N; i++ {
		for j := 0; j < SIZE; j++ {
			k := data[j][0]
			markAccess(&flag)
			res = m[k]
			unmarkAccess(&flag)
			if res[0] != data[j][1] {
				b.Fail()
			}
		}
	}
}

```

**Comment by spacewander** [comment]
> Here is the home-made detector:
> 
> ```
> func markAccess(flag *int32) {
> 	if atomic.LoadInt32(flag) != 0 {
> 		panic("concurrent operation detected")
> 	}
> 	atomic.StoreInt32(flag, 1)
> }
> 
> func unmarkAccess(flag *int32) {
> 	atomic.StoreInt32(flag, 0)
> }
> 
> func BenchmarkInit_GoMapAtomic(b *testing.B) {
> 	data := getSlices()
> 	for i := 0; i < b.N; i++ {
> 		m := make(map[string][]string, SIZE)
> 		var flag int32
> 		for j := 0; j < SIZE; j++ {
> 			k := data[j][0]
> 			markAccess(&flag)
> 			m[k] = []string{data[j][1]}
> 			unmarkAccess(&flag)
> 		}
> 	}
> }
> 
> func BenchmarkRead_GoMapAtomic(b *testing.B) {
> 	data := getSlices()
> 	m := make(map[string][]string, SIZE)
> 	var flag int32
> 	for j := 0; j < SIZE; j++ {
> 		k := data[j][0]
> 		markAccess(&flag)
> 		m[k] = []string{data[j][1]}
> 		unmarkAccess(&flag)
> 	}
> 
> 	var res []string
> 	for i := 0; i < b.N; i++ {
> 		for j := 0; j < SIZE; j++ {
> 			k := data[j][0]
> 			markAccess(&flag)
> 			res = m[k]
> 			unmarkAccess(&flag)
> 			if res[0] != data[j][1] {
> 				b.Fail()
> 			}
> 		}
> 	}
> }
> ```

Change the detector to use CAS improves the performance, but it's still not faster than Map with lock. As map with lock in the fast path is just a detector.
