### ISSUE TITLE
StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBodyPartially is flaky

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#29625]
The test `StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBodyPartially` in `//test/extensions/filters/http/ext_proc:streaming_integration_test` seems to be flaky.
An example: https://dev.azure.com/cncf/envoy/_build/results?buildId=149245&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=67a76341-37f4-5b49-db38-acbb8a59af82&l=4490

```
[ RUN      ] StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBodyPartially/IPv4_EnvoyGrpc_WithDeferredProcessing
test/extensions/filters/http/ext_proc/streaming_integration_test.cc:351: Failure
Value of: client_response_->headers()
Expected: http status is "200"
  Actual: 24-byte object <B0-CC E8-01 00-00 00-00 A8-D1 E8-01 00-00 00-00 20-D2 E8-01 00-00 00-00> (of type Envoy::Http::ResponseHeaderMap), which has status code 500
Stack trace:
  0x1d9e288: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1d9e128: testing::Test::Run()
  0x1d9f278: testing::TestInfo::Run()
... Google Test internal frames ...

```

**Comment by adisuissa** [comment]
@yanjunxiang-google can you PTAL?

**Comment by yanjunxiang-google** [comment]
Thanks for reporting the issue. Yes, there is a bug in this test. 
Please check https://github.com/envoyproxy/envoy/pull/29628 for the root cause and fix.

**Comment by alyssawilk** [comment]
@yanjunxiang-google is this fixed and should be closed out?

**Comment by yanjunxiang-google** [comment]
Yes, this issue is fixed. Let's close it.
