### ISSUE TITLE
Golang extension support route/cluster metadata related api

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#29622]
*Title*: *Golang extension support route/cluster metadata related api*

*Description*:

it seems that golang extension does not support route/cluster metadata related api yet, which maybe a useful api.

**Comment by StarryVae** [comment]
And it seems that `getProperty` has already been supported, so we can support route/cluster metadata also in `getProperty` just like what wasm do. cc @doujiang24 @spacewander

**Comment by doujiang24** [comment]
@StarryVae do you mean the current getProperty already supports getting route/cluster metadata? or need some improvements?

**Comment by StarryVae** [comment]
we need some improvements.

**Comment by spacewander** [comment]
@StarryVae 
Do you mean implementing https://github.com/envoyproxy/envoy/blob/782bb0c102ffbd9880615526c54c00301a6f3f82/contrib/golang/filters/http/source/golang_filter.cc#L1417 and serialize the map/list style in a JSON string, or something else?

**Comment by StarryVae** [comment]
Nope, i think route/cluster metadata is not supported yet, and could we support it in `getProperty`? @spacewander

**Comment by spacewander** [comment]
> Nope, i think route/cluster metadata is not supported yet, and could we support it in `getProperty`? @spacewander

I haven't given it a try, but according to the code:

The metadata is fetched in https://github.com/envoyproxy/envoy/blob/fc6342a95b48c3c8de0262085798c3a4369aa062/source/extensions/filters/common/expr/context.cc#L359-L371

The current serialization code in `getProperty` doesn't support Map or List, so we can get the metadata only when the metadata is a string.

Here is a relative test:
https://github.com/envoyproxy/envoy/blob/fc6342a95b48c3c8de0262085798c3a4369aa062/contrib/golang/filters/http/test/test_data/property/filter.go#L95
