### ISSUE TITLE
Oauth2: encrypt access token and client token in the cookie

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#29656]
*Title*: *Oauth2: encrypt access token and id token in the cookie*

*Description*:
Currently, the access token and id token are stored in the cookies. An HMAC secret is used to verify the tokens. It can be enhanced to also use a shared secret(potentially the same secret used by HMAC) to encrypt the tokens.

**Comment by ggreenway** [comment]
cc @derekargueta @mattklein123

**Comment by loewenstein** [comment]
I would be interested to see this feature. @zhaohuabing would you consider reopening this issue?

**Comment by zhaohuabing** [comment]
> I would be interested to see this feature. @zhaohuabing would you consider reopening this issue?

Yes, but I don't have the permission.

**Comment by loewenstein** [comment]
Actually, this would be covered by https://github.com/envoyproxy/envoy/issues/23508 which is still open, wouldn't it?

**Comment by zhaohuabing** [comment]
@KBaichoo Could you please label it as no stalebot? It's still valid. Thanks!
