### ISSUE TITLE
Why envoy response different result from different pod?

### ISSUE THREAD

**Issue by chutian52** [envoyproxy/envoy#29658]
*Description*:
I had checked [flow_control](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control), and we used default settings.

step 1 :when we use curl in envoy pod
```
curl --location 'http:/10.1.62.209:95/material/picture/upload' \
--header 'x-custom-sso: true' \
--header 'Authorization: XT3G6Q1MXvo9r6udULIgOGeDUjNPHG%2B29DneuXYqdCbhvV9uldRljm%2BCATwsN%2FEaSBWfYEo8j1hgUmM1cu07C037PL2j2U2IHzuG2sJU%2B7WQ4FUpatSfIonzWTWTzFIoqEAFNk238wQ80TOEhIlWuIL6zEO5T07TBda1OZNdOlI%3D' \
--form 'file=@"/opt/detail.jpg"'
```
it response
<img width="746" alt="image" src="https://github.com/envoyproxy/envoy/assets/11222742/56901d47-f91a-44f6-8e1a-991a4cee67ab">

step 2: use curl in other pod
```
curl --location 'http:/10.1.62.209:95/material/picture/upload' \
--header 'x-custom-sso: true' \
--header 'Authorization: XT3G6Q1MXvo9r6udULIgOGeDUjNPHG%2B29DneuXYqdCbhvV9uldRljm%2BCATwsN%2FEaSBWfYEo8j1hgUmM1cu07C037PL2j2U2IHzuG2sJU%2B7WQ4FUpatSfIonzWTWTzFIoqEAFNk238wQ80TOEhIlWuIL6zEO5T07TBda1OZNdOlI%3D' \
--form 'file=@"/opt/detail.jpg"'
```
it response 
<img width="733" alt="image" src="https://github.com/envoyproxy/envoy/assets/11222742/ed71ddf4-af35-4cf9-abb1-949c2a6ab668">

`10.1.62.209`  is host mechine ip.

envoy's version is 1.14.1

**Comment by ggreenway** [comment]
Without knowing what is different between the two pods, I can't say what is going on here.

Version 1.14 has been unsupported for a very long time.

**Comment by chutian52** [comment]
@ggreenway Thanks.
First curl return http status 413
