### ISSUE TITLE
Envoy external grpc filter cannot change response code

### ISSUE THREAD

**Issue by VladislavAtanasov** [envoyproxy/envoy#29657]
Title: How to get response headers and status code in a grpc external processing filter?

Description:

Each request only hit pb.ProcessingRequest_RequestHeaders handler. We cannot enter the handlers to try to tweak the HTTP response code and response headers even when we set all configs to send response to "SEND". How can we achieve the attitude of Lua envoy_on_response handler in grpc?

[optional Relevant Links:]

We are using this grpc filter https://github.com/envoyproxy/go-control-plane/blob/main/envoy/extensions/filters/http/ext_proc/v3/ext_proc.pb.go#L278

**Comment by IliyanVidenov** [comment]
Hi Envoy team,

We are experiencing the same technical issue, and we are wondering when a fix for this would be released.

Best Regards,
Iliyan
