### ISSUE TITLE
golang filter: cached length is not updated

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#29661]
The length field in httpBuffer is not updated in the write operations:
https://github.com/envoyproxy/envoy/blob/782bb0c102ffbd9880615526c54c00301a6f3f82/contrib/golang/filters/http/source/go/pkg/http/type.go#L333

The headerNum/Bytes fields in headerMapImpl also have the same issue. However since the `ByteSize` method is rarely used and keep the headerBytes up-to-date is tough, I would recommend to remove it:
https://github.com/envoyproxy/envoy/blob/782bb0c102ffbd9880615526c54c00301a6f3f82/contrib/golang/filters/http/source/go/pkg/http/type.go#L49

CC @doujiang24

**Comment by doujiang24** [comment]
Nice catch, totally agreed!
