### ISSUE TITLE
Rewrite AccessLogformatter with parser library

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#2967]
We're doing a lot of manual crufty stuff with substrings and parentheses matching to parse out the require format strings. We should probably switch to some formal grammar for the access log format strings (e.g. EBNF) and use a parser library or generator (e.g. yacc). This issue will track improvements here.

CC: @mattklein123 @derekargueta

**Comment by sriduth** [comment]
Hello! I've been looking into this and have something basic that works (passes the existing tests for formats) [here](https://github.com/sriduth/envoy/commit/1e1cda8f18aeb157f707184834bb3179f982707d). Access log formatter has been stable for as long I remember, but if this is something to be worked on I'd love to take it up!

**Comment by htuch** [comment]
@sriduth this looks great. I think you're using lex/yacc here. Did you have a look around to see if there is anything more modern for C++, e.g. parser combinators, that makes sense?

I think with some amount of Bazel integration and refactoring of common parsing conecrns, lex/yacc could be reasonable to drop in if that's the best option.

**Comment by sriduth** [comment]
Thanks @htuch! Yup -  I've used bison and flex for the scanner and parser. I did look at other parsing libraries as well but I know too less to make a good call on how to select a library, so I thought I'd go with the most established libraries.

I also found these bazel rules: https://github.com/jmillikin/rules_bison and https://github.com/jmillikin/rules_flex which look to be maintained and also saw that https://github.com/envoyproxy/sql-parser/tree/master/src/parser was using bison & flex.

I'll investigate more and report back on other parsing libraries.

**Comment by kyessenov** [comment]
FYI there's an ANTLR parser generator, too: https://github.com/google/cel-cpp/blob/master/bazel/antlr.bzl

**Comment by htuch** [comment]
Yeah, I think there are multiple considerations:
1. How well this integrates with Bazel.
2. How much boiler plate there is.
3. How close to a pure grammar we can get as developers. I.e. ease of use.
4. How well supported the library is. Ideally have something rock solid; parsers are security sensitive and we want something that has seen a lot of use.

**Comment by sriduth** [comment]
I didn't know there was a c++ backend for antlr!

A friend pointed me to https://www.boost.org/doc/libs/1_71_0/libs/spirit/doc/html/index.html. Found these as well:

- https://github.com/LPeter1997/CppCmb
- https://github.com/taocpp/PEGTL

All of the above seem to define the grammar using datastructures in C++ instead of files having EBNF style rules.

I think from a robustness perspective - antlr, (bison & flex) stand out and among those IMHO antlr is easier to use as it rolls the lexer and parser into one.

**Comment by htuch** [comment]
I think Boost is out, for sure, since we have historically shied away from bringing Boost into Envoy. 

If we take ANTLR, does this mean we have Java in our build process? Bazel is Java based, but I do have a slight concern over build performance. Looks like there is Bazel integration at https://github.com/marcohu/rules_antlr.

PEGTL seems the more mature/active of the parser combinator libraries. I like parse combinators, but that's an aesthetic opinion, other factors probably matter more.

**Comment by dio** [comment]
FWIW, @kyessenov's https://github.com/envoyproxy/envoy-wasm/pull/345/files

**Comment by kyessenov** [comment]
That was fast @dhi. Re: Java dependency -- is this a big deal? Bazel is written in Java so the build process already implicitly depends on Java. The reason for ANTLR in my PR is simple: there is a formal G4 grammar that is shared between several languages, so it makes total sense to use the same parser runtime.

**Comment by htuch** [comment]
@kyessenov I have no strong opinions, I'm curious to learn more. Did adding ANTLR have any measurable impact on build performance?

**Comment by sriduth** [comment]
I tried integrating antlr during the weekend using bazel referring to the link @kyessenov shared (https://github.com/google/cel-cpp/blob/master/bazel/antlr.bzl)

I ported the base grammar and implemented a listener (all tests are failing) - but here are some numbers for build times.

`bazel clean` and then `time bazel test //test/common/access_log:access_log_formatter_test `

Without antlr:

```
INFO: Build completed successfully, 1553 total actions
0.14s user 0.11s system 0% cpu 9:37.72 total
```

With antlr:

```
INFO: Build completed, 1 test FAILED, 1704 total actions
0.10s user 0.15s system 0% cpu 10:03.59 total
```

after changing grammar: 
```
INFO: Build completed, 1 test FAILED, 13 total actions
0.01s user 0.01s system 0% cpu 12.599 total
```

**Comment by htuch** [comment]
Is that 2 minutes extra just because you modified a grammar entry, or because your build now depends on ANTLR and it forced the full build?

Are these incremental or clean builds?

**Comment by sriduth** [comment]
Ah sorry, I should have mentioned it. For the first tow I run `bazel clean` followed by the `bazel test`.

The last one is an incremental build where I change the grammar definition.

**Comment by derekargueta** [comment]
Just to throw my 2 cents in, I was planning on using [Ragel](http://www.colm.net/open-source/ragel/) to parse the ASCII Memcached codec, which is what [McRouter](https://github.com/facebook/mcrouter) uses to accomplish [the same task](https://github.com/facebook/mcrouter/blob/master/mcrouter/lib/network/McAsciiParser.rl). I'm not sure how it compares to parsing libraries like ANTLR as I don't often use parsing libraries. We obviously should have 1 well-supported parsing library, so whatever is decided upon here I'll likely also use for parsing ASCII protocols elsewhere.

**Comment by sriduth** [comment]
A summary of the parsers discussed:

| Library        | Type | Bazel           | Security | Perf | Develpment |
| ------------- |:-------------:| -----:|--------|------|------|
| bison & flex     | code generator | yes | TBD | https://github.com/envoyproxy/sql-parser/ | Will need to know flex & bison syntax |
| antlr      | code generator      |   yes | TBD | Not measured | Has a well documented syntax with many examples (https://github.com/antlr/grammars-v4/tree/master/memcached_protocol) |
| PEGTL | parser combinator      |    no | TBD | Not measured | Parser expressed as C++ templates |

@derekargueta found this - https://github.com/antlr/grammars-v4/tree/master/memcached_protocol

**Comment by htuch** [comment]
@rshriram do you know how hard it would be to move the SQL parser to ANTLR? I'm encouraged by ANTLR based on the research that @sriduth has done.

**Comment by rshriram** [comment]
I investigated it in the past. It was hard to come by some full fledged C++ parser for SQL stuff with antlr. Also that parser code was forked from another OSS project, and hacked to get all the parser callbacks, etc. So, its going to be a bit of rewrite.

**Comment by htuch** [comment]
OK, I don't think we need to have precisely on parser generator, as long as the vast bulk of stuff lands on ANTLR or Bison/Flex then we're good. I definitely prefer having 2 to N :) If ANTLR is easier to work with, we should probably recommend this for most purposes.

**Comment by sriduth** [comment]
Hello everyone! A quick update: I've implemented the access log formatter using antlr [here](https://github.com/sriduth/envoy/commit/6053d5bae0567e69ccf0f9f042c48550845a09a1).

To compare the generated parsers, I will try to implement a benchmark  for https://github.com/mysql/mysql-workbench/tree/8.0/library/parsers/grammars based on what we have here: https://github.com/envoyproxy/sql-parser/tree/master/benchmark.

**Comment by rshriram** [comment]
I now remember the other reason for going to the bison thing.. the license in the mysql parser https://github.com/mysql/mysql-workbench/blob/8.0/library/parsers/grammars/MySQLLexer.g4#L4
I dont know the implications it has on our license (apache). Would be good to get some legal advice. If its okay to do so, then we are good as we can happily skip the custom bison/flex with something official from mysql.

**Comment by htuch** [comment]
@caniszczyk would be great to get CNCF license help with ^^ if you can tag the right person. Thanks.

**Comment by sriduth** [comment]
I found the link to the MySQL workbench grammar from here: https://github.com/antlr/grammars-v4/tree/master/sql/mysql. There is an alternative grammar for MySQL 5.{6,7} which has an MIT license.

Blog post by the company that made the MIT licensed parser: http://blog.ptsecurity.com/2018/01/mysql-grammar-in-antlr-4.html

**Comment by kyessenov** [comment]
There are a couple of San violations in ANTLR 4.7.1 runtime. You might want to carry over the patches here https://github.com/envoyproxy/envoy-wasm/blob/master/bazel/antlr.patch. 4.7.2 also has some issues, but I haven't looked into patching that release.

**Comment by sriduth** [comment]
Will do @kyessenov!

**Comment by sriduth** [comment]
An update on the benchmarking task - I managed to hack together a benchmark app for the ANTLRv4 parser here: https://github.com/sriduth/sql-parser. Running the benchmark comman as follows: `bin/benchmark --benchmark_repetitions=100 --benchmark_filter=tpc-h-14 --benchmark_counter_tabular=true`

ANTLRv4 is significantly slower:

YACC:

|         benchmark                     |                 time               |         cpu         |                Iterations           |    Counters                          | 
|------------------------------|--------------------------------|------------------|---------------------------|------------------------------| 
| tpc-h-14.sql-tokenize_mean   |          5266 ns               |          5266 ns |           100             |  num_chars=316 num_tokens=59 | 
| tpc-h-14.sql-tokenize_median |        5209 ns                 |          5210 ns |           100             |  num_chars=316 num_tokens=59 | 
| tpc-h-14.sql-tokenize_stddev |         143 ns      |    143 ns |           100    |  num_chars=0 num_tokens=0 |                                      | 
| tpc-h-14.sql-parse_mean      |            12749 ns            |         12750 ns |           100             |  num_chars=316 num_tokens=59 | 
| tpc-h-14.sql-parse_median    |          12551 ns              |         12553 ns |           100             |  num_chars=316 num_tokens=59 | 
| tpc-h-14.sql-parse_stddev    |            577 ns              |           577 ns |           100             |  num_chars=0 num_tokens=0    | 

ANTLR:

|         benchmark                     |                 time               |         cpu         |                Iterations           |    Counters                          | 
|------------------------------|--------------------------------|------------------|---------------------------|------------------------------| 
| tpc-h-14.sql-tokenize_mean   |        48268 ns     |         48263 ns |          100  |  num_chars=316 num_tokens=61 | 
| tpc-h-14.sql-tokenize_median |       48147 ns      |         48149 ns |           100 |  num_chars=316 num_tokens=61 | 
| tpc-h-14.sql-tokenize_stddev |        2944 ns      |          2941 ns |           100 |  num_chars=0 num_tokens=0    | 
| tpc-h-14.sql-parse_mean      |         71359433 ns |      71358019 ns |           100 |  num_chars=316 num_tokens=61 | 
| tpc-h-14.sql-parse_median    |       69351796 ns   |      69354641 ns |           100 |  num_chars=316 num_tokens=61 | 
| tpc-h-14.sql-parse_stddev    |        4541768 ns   |       4543874 ns |           100 |  num_chars=0 num_tokens=0    | 

Performance related discussion: https://github.com/antlr/antlr4/issues/2584 - Ill try to implement some of the improvements suggested there and investigate the reason for the performance difference.

**Comment by yanavlasov** [comment]
+1 on replacing what we have today with ANTLR generated parser, since we already use in Envoy anyway. I think the formatter code is getting less and less readable.

**Comment by kyessenov** [comment]
There have been some improvements in C++ ANTLR runtime lately thanks to @jcking. He might be interested in the above performance numbers if there's some low hanging fruit before the next release.

**Comment by yanavlasov** [comment]
We also do not care about performance in this specific case as parsing happens when config is ingested, which is not performance critical path.
