### ISSUE TITLE
Isolation of upstream and downstream using linux netns (network namespaces)

### ISSUE THREAD

**Issue by ebik-economia** [envoyproxy/envoy#29675]
*Title*:  Isolation of upstream and downstream zones using linux netns (network namespaces)

*Description*:
I would like to have listeners in different network namespace, so that I can apply agressive firewall rules, or special dynamic routing tricks, while keeping connections to upstream servers simple (i.e. not filtered) and also without need to think about exceptions for firewall so that upstream connections won't be filtered. It would also enable infrastructure programs (ssh, monitoring, ...) to listen on same port as envoy, because envoy would listen in different network namespace.

*Example usage*:

Zone external: ip netns "external" - external interface with dynamic routing table, firewall, and **listener addresses**
Zone trusted: default netns - envoy control plane (localhost:9901 listener), default routing table for envoy host (software upgrades etc.), and **typically also origin of connections to upstream servers**, also ssh, monitoring, and other programs may listen on usual ports in this namespace, without colliding with envoy listeners. 

[optional *Relevant Links*:]
https://man7.org/linux/man-pages/man8/ip-netns.8.html
https://man7.org/linux/man-pages/man2/setns.2.html
This would probably need separated process(thread) for listener(s), which will pass accepted sockets to workers that will be in cluster namespace, because AFAIK one process(thread) is in one (network) namespace in any given time.

**Comment by ggreenway** [comment]
Having a separate thread for listeners would be a large change to how Envoy works.

If someone wants to propose a design, we can discuss and see if it's feasible.

**Comment by soulxu** [comment]
> _Example usage_:
> 
> Zone external: ip netns "external" - external interface with dynamic routing table, firewall, and **listener addresses** Zone trusted: default netns - envoy control plane (localhost:9901 listener), default routing table for envoy host (software upgrades etc.), and **typically also origin of connections to upstream servers**, also ssh, monitoring, and other programs may listen on usual ports in this namespace, without colliding with envoy listeners.
> 
Do you mean the main thread in the zone trusted? and some worker threads in the zone external and some worker threads in the zone trusted?

**Comment by ebik-economia** [comment]
I guess so. Mainly workers that handles listener sockets in zone external, they will pass handling of the request to worker in zone trusted, where upstream servers reside.
I did not dig deeply into implementation, other than that I use it in some small python script, which is passed filedescriptor from one netns for sending reply back, while acting in another netns (to monitor some upstream servers for L3/ipvs loadbalancing). That teased me enough to wonder how easy/hard it will be to span multiple netns in envoy.
