### ISSUE TITLE
Access_logs are missing if we trigger kill to envoy process immediately after a request 

### ISSUE THREAD

**Issue by bkura** [envoyproxy/envoy#29682]
Hi,
In our scenario, we are trying to gracefully kill all the containers in an edge machine after processing all the requests (FYI we are achieving it by setting the envoy in drain state).

Now as soon as the last request processing is done and a response is sent back to upstream, we are triggering a kill command to envoy process.

Now in this scenario, sometimes we aren't seeing the logs of this last request/response being logged by the envoy.

we want to understand why the envoy is not flushing the logs before killing itself.

(Anyone has any idea why there are missing logs in such cases?)

Thanks in advance!

**Comment by bkura** [comment]
So, my theory here is that the envoy Stdout sink is an async process for performance and various reasons.
but as it is async in nature and we are triggering the kill immediately, envoy isn't getting a chance to flush logs out. hence killing all its process.

if that is the cause, then the access_log_manager should handle this gracefully and make sure it flushes out all the pending/remaining logs in the buffer to the stdout and kill itself.

let me know if this assumption is right and also help fix it.
if this assumption isn't right please let us know what could be the reason for such log losses.

**Comment by bkura** [comment]
@ggreenway yes we are sending SIGTERM

What is the signal that is supposed to pass in order it to work properly?

And FYI: the envoy is moved to drain state soon after receiving the request from downstream.

**Comment by ggreenway** [comment]
Any signal besides SIGKILL is supposed to work (because SIGKILL is handled 100% by the kernel; processes are never notified of this signal).

It sounds like there's possibly a bug there. If possible, can you capture all the syscalls at shutdown, in the failing case, using `strace`? That would help in figuring out what's going on.

**Comment by bkura** [comment]
sure, will try to that, but I'm not sure I can get that

is there anything else that can help debug the issue

**Comment by ggreenway** [comment]
If you're terminating envoy while there's an active request, the solution is to wait until there aren't any active requests. It's likely that the request isn't being fully processed if you're sending SIGTERM during request handling; it's more than just access logs that are missing.

**Comment by bkura** [comment]
Thanks @ggreenway will check it again and get back, if that is the case

**Comment by bkura** [comment]
Hey @ggreenway, we think the request is getting served, but only the log is missing, that too if the listeners are in draining state, so could it be possible that there is a bug in logging when listeners are in drain state?
