### ISSUE TITLE
Decoding buffer is not linked to the current request (buffer accounting)

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#29697]
The request decoding buffer does not use the account of the request. This means that the buffer accounting feature does not work properly. Currently the memory that is used by the request decoding buffer is not tracked.

The buffer is returned by `StreamDecoderFilterCallbacks::decodingBuffer()`, and the account is returned by `StreamDecoderFilterCallbacks::account()`. `Envoy::Buffer::Instance::bindAccount()` can be used to link a buffer with an account.

It's also interesting that the accounting feature currently only exists for decoding (requests), not for encoding (responses). I think it should also be implemented for responses: `StreamEncoderFilterCallbacks::encodingBuffer()` should use the account that is returned by `StreamEncoderFilterCallbacks::account()` (new method).

See also #15791.

**Comment by ggreenway** [comment]
cc @KBaichoo

**Comment by KBaichoo** [comment]
The buffer is returned by StreamDecoderFilterCallbacks::decodingBuffer(), and the account is returned by StreamDecoderFilterCallbacks::account(). Envoy::Buffer::Instance::bindAccount() can be used to link a buffer with an account.
> The tagging of the memory occurs during the codec phase e.g. attributing the bytes in the system to a particular stream. 
> So for example if a downstream request comes and is parsed as some HTTPX stream we will tag those bytes as being charged to that account. Similarly for response from the upstream.  The Slices that move around know the paarticular account, etc. that they're charged to.

HTH,
Kevin

**Comment by mkauf** [comment]
@KBaichoo : Thank you for the explanation. I have overlooked that the slices in a buffer can have an account, too.

Unfortunately, it seems that this does not work as intended. The slices of the default decoding buffer do not have an account. I have found this with "debugging-by-printf" and the test scenario of #29581.

**Comment by KBaichoo** [comment]
Let's consolidate discussion in that one issue then since it's coupled.
