### ISSUE TITLE
Tap filter on Cluster

### ISSUE THREAD

**Issue by coolg92003** [envoyproxy/envoy#29722]
*Title*: *Add Tap filter on Cluster*

*Description*:
>In envoy,
Tap  has been implemented in transport of LDS and CDS;
and also tap has been implemented in HTTP filter of HTTP connection manager on LDS.
However, envoy provides the **ability** to change _**HTTP header and body in LDS and RDS**_(only for HTTP header), the the HTTP message dumped on LDS is **different** between LDS and CDS if use this ability. Although transport tap can do message dump on both LDS and CDS, the key disadvantage is that it can't filter HTTP message per request(this is really needed when call load), like HTTP request or response header. For transport tap,  this can be understood because it is raw message.
Therefore, is it possible to give a interface in CDS to dump message?

[optional *Relevant Links*:]
>check this picture for possible place(connectionPool).
![Capture_http_tap](https://github.com/envoyproxy/envoy/assets/12623728/177fce92-f2f2-4acc-a8e7-8db8460fd3a2)

Since I am not expert in envoy, any other good thought?
thanks,
Cliff

**Comment by ggreenway** [comment]
Yep, that could be a useful feature to be able to tap on the upstream side as well. PRs welcome if anyone wants to work on that.

**Comment by coolg92003** [comment]
hi @ggreenway ,
Do you know who is expert on Cluster?
To be honest, I want to do it, but I don't know where to start.
thanks
Cliff
