### ISSUE TITLE
How to merge the features related to golang filter to my version of envoy

### ISSUE THREAD

**Issue by SoaringPhoenix** [envoyproxy/envoy#29753]
Hi, I'm currently using envoy as a gateway as well as a sidecar in our organization right now.

I'm willing to use the features of golang filter on my envoy gateway. But there are circumstances that I'm can't update my envoy to the latest version.

My version of envoy is v1.24.10, and my istio version is v.1.16.6. Since the newer versions of istio requires the newer versions of kubernetes and the version of istio and envoy should be related. Since I can't easily update my kubernetes version, cause it's for the whole organization. I can't easily update the version of my istio and envoy.

So v1.24.10 is as far as I can go for my envoy. So is it possible to merge all the commits related to the golang filter to my version of envoy while I can continue using the current v1.24.10 version of envoy. If it is, I'm more than thrilled to know which commits should I merge to my envoy, thank you!

@wangfakang 
@doujiang24 
@spacewander

**Comment by spacewander** [comment]
@SoaringPhoenix 
You can backport the whole golang filter from https://github.com/envoyproxy/envoy/tree/main/contrib/golang, and ensure the tests under it are all passed.

**Comment by SoaringPhoenix** [comment]
> @SoaringPhoenix You can backport the whole golang filter from https://github.com/envoyproxy/envoy/tree/main/contrib/golang, and ensure the tests under it are all passed.

So the /contrib/golang directory contains all the features related to golang filter, is it so?
I can just copy the whole directory to my project, is it feasible? And what about istio, are there commits there to be backported as well?

**Comment by spacewander** [comment]
> I can just copy the whole directory to my project, is it feasible? 

You need to build Envoy & run the test in the directory.

> And what about istio, are there commits there to be backported as well?

You can use EnvoyFilter to distribute the golang filter configuration.

**Comment by doujiang24** [comment]
there are also some more directories:
https://github.com/envoyproxy/envoy/tree/main/api/contrib/envoy/extensions/filters/http/golang/v3alpha
https://github.com/envoyproxy/envoy/tree/main/api/contrib/envoy/extensions/filters/network/golang/v3alpha
https://github.com/envoyproxy/envoy/tree/main/api/contrib/envoy/extensions/router/cluster_specifier/golang/v3alpha

and, part of https://github.com/envoyproxy/envoy/blob/main/contrib/contrib_build_config.bzl, please grep the `golang` keyword.

Also, there are three golang extensions: HTTP filter extension, network filter extension, and cluster_specifier extension.
You can not need them all, you could pick some of them.

It should be workable, but may need some time, maybe one or two days to make them work.

**Comment by shubham1172** [comment]
@doujiang24 I have been following https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#customize-extension-build-config, can you please share how to add these API directories to `extensions_build_config.bzl`? I added a section for contrib extensions, but where do these API directories go?

```bzl
CONTRIB_EXTENSIONS = {
    # Go
    "envoy.filters.http.golang":                        "//contrib/golang/filters/http/source:config",
}
```

Build command - `bazel build envoy --override_repository=envoy_build_config=custom-build`

**Comment by doujiang24** [comment]
@shubham1172 I think it shoud be a bazel related issue, but I'm just a beginner bazel user, you'd better read the doc more.

re the directories, these might be your wanted.
1. https://github.com/envoyproxy/envoy/tree/main/contrib/golang
2. https://github.com/envoyproxy/envoy/tree/main/api/contrib/envoy/extensions/filters/http/golang/v3alpha

**Comment by shubham1172** [comment]
Thanks, for others who stumble here - if one is using bazel, contrib APIs are already a part of the build. I was configuring my bzl file incorrectly. Here is the delta that worked.

```diff
EXTENSIONS = {
+    #
+    # Go contrib
+    #
+    "envoy.filters.http.golang": "//contrib/golang/filters/http/source:config",

    #
    # Access loggers
    #
    "envoy.access_loggers.file": "//source/extensions/access_loggers/file:config",
...
- CONTRIB_EXTENSION_PACKAGE_VISIBILITY = ["//:contrib_library"]
+ CONTRIB_EXTENSION_PACKAGE_VISIBILITY = ["//visibility:public"]
```
