### ISSUE TITLE
Is it possible to bind multiple IPs to the upstream binding configuration of the Envoy cluster?

### ISSUE THREAD

**Issue by xunhuangxu** [envoyproxy/envoy#29754]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Is it possible to bind multiple IPs to the upstream binding configuration of the Envoy cluster?

*Description*:
As shown in the following figure, is it possible for the upstream binding configuration of the Envoy cluster to support binding of multiple IP addresses?
For example, when I need to access the endpoint through the proxy IP address, I need to set the source ip in BindConfig of the cluster to the proxy IP so that the request can be correctly returned. Currently, multiple  source IP addresses are not supported. How can I set multiple source addresses?
![image](https://github.com/envoyproxy/envoy/assets/55660218/fe693dc4-5729-4b0a-bf00-8a10d63c73c7)

[optional *Relevant Links*:]
[>Any extra documentation required to understand the issue.](https://www.envoyproxy.io/docs/envoy/v1.25.2/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-bindconfig)

**Comment by ggreenway** [comment]
I don't think I understand your use case. You want to have multiple source addresses available; what rules would you use to determine which one is used for each connection?

**Comment by xunhuangxu** [comment]
> I don't think I understand your use case. You want to have multiple source addresses available; what rules would you use to determine which one is used for each connection?

Simply put, the two endpoints of the cluster are in different network environments. Therefore, different proxies are required to access them, that is, different source IP addresses are required. As for your question, the two endpoints have different network segments. Can we select different source addresses according to the destination network segments?
