### ISSUE TITLE
Unable to parse JSON as proto (INVALID_ARGUMENT:Unable to parse number (.yml)

### ISSUE THREAD

**Issue by nbari** [envoyproxy/envoy#29784]
Following the quickstart guide I downloaded the demo `envoy-demo.yaml`, and moved it to a temp dir,  but I renamed the file to `envoy.yml` (notice the extension `.yml` instead of `.yaml`)

Running:
   
    $ envoy --mode validate -c envoy.yml

or 

    $ envoy  -c envoy.yml

prints the whole config but with a message on top:

    [2023-09-23 10:59:16.439][16780][critical][main] [external/envoy/source/server/config_validation/server.cc:62] error initializing configuration 'envoy.yml': Unable to parse JSON as proto (INVALID_ARGUMENT:Unable to parse number.

If I use the extension `.yaml` works as expected, but wondering if this behavior is by design and expected?. if yes could the error message please be changed?

This is the version I am using in debian:

     envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

**Comment by ravenblackx** [comment]
cc @yanavlasov
