### ISSUE TITLE
systemd unit file example with --hot-restart-epoch

### ISSUE THREAD

**Issue by wxmeng04** [envoyproxy/envoy#29794]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *systemd unit file example*

*Description*:
> As described in the official document, `Ease of operation is one of the primary goals of Envoy. In addition to robust statistics and a local administration interface, Envoy has the ability to “hot” or “live” restart itself.` However it's not easy for a normal user to prepare a systemd unit file. In our project, we don't need python and we are not intended to install python only for hot-restart of envoy. Is it possible to share an example of unit file for hot restart without python?
As per official documentation below, it seems it's not mandatory to use the python script to hot start envoy and the py script is  only required when using monit, runit, etc. But it's still not clear how to hot start without using a python script. If an systemd unit file is provided as example, it's highly appreciated!
```
Typically, Envoy will be hot started for config changes and binary updates. However, in many cases, users will wish to use a standard process manager such as monit, runit, etc. We provide /restarter/hot-restarter.py to make this straightforward.
```

**Comment by ravenblackx** [comment]
I think the closest thing you're likely to get to a simple "not using the python script" example is, ironically, another python script, [here](https://github.com/envoyproxy/envoy/blob/main/test/integration/hotrestart_handoff_test.py); an integration test that I recently added, which shows an example set of the params you need to pass to provoke a hot restart.

If you can translate that premise into a systemd unit file it would be a welcome contribution to documentation!

**Comment by wxmeng04** [comment]
> I think the closest thing you're likely to get to a simple "not using the python script" example is, ironically, another python script, [here](https://github.com/envoyproxy/envoy/blob/main/test/integration/hotrestart_handoff_test.py); an integration test that I recently added, which shows an example set of the params you need to pass to provoke a hot restart.
> 
> If you can translate that premise into a systemd unit file it would be a welcome contribution to documentation!
Below is part of my installation script but without hot-restart. I met one major problem when increasing the restart counter as unit file seems not supporting to change env viarable in it. In any case let me try.
```
cat <<- EOF > /etc/systemd/system/envoy.service
[Unit]
Description=Envoy Proxy ${VERSION}
After=network-online.target
Wants=network-online.target
AssertPathExists=${INSTALLDIR}/etc/envoy.yaml

[Service]
Type=simple

Environment="ENVOY_CONFIG_FILE=${INSTALLDIR}/etc/envoy.yaml"
Environment="ENVOY_RESTART_EPOCH=0"

User=envoy
Group=envoy
ReadOnlyDirectories=/
ReadWriteDirectories=-${INSTALLDIR}/log
ReadWriteDirectories=-${INSTALLDIR}/etc
ReadWriteDirectories=-/dev/shm/

ExecStartPre=${INSTALLDIR}/envoy-contrib-${VERSION}-linux-x86_64 -c ${INSTALLDIR}/etc/envoy.yaml --mode validate
ExecStart=${INSTALLDIR}/envoy-contrib-${VERSION}-linux-x86_64 -c \$ENVOY_CONFIG_FILE --log-path ${INSTALLDIR}/log/envoy.log --restart-epoch \$ENVOY_RESTART_EPOCH
ExecReload=/bin/kill -s HUP \$MAINPID

LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
```

**Comment by phlax** [comment]
@wxmeng04 if you have a working systemd unit example, esp for hot-restart, it would be great to add it to the docs

we also have some deb packages that we build (not yet publish) which i think could benefit from this

**Comment by wxmeng04** [comment]
> @wxmeng04 if you have a working systemd unit example, esp for hot-restart, it would be great to add it to the docs
> 
> we also have some deb packages that we build (not yet publish) which i think could benefit from this

Noted! I will be working on it and may take some time. But by the way, why envoy don't process the SIGHUP signal by itself as many other daemons do? Meantime I have to specify `Type` as simple because envoy seems not supporting start as a deamon.

If envoy will work as a general purpose gateway, systemd support shall be a must.

**Comment by phlax** [comment]
probably worth raising this issue as a separate ticket i think
