### ISSUE TITLE
On demand cluster discovery per route is not working

### ISSUE THREAD

**Issue by balu-ce** [envoyproxy/envoy#29797]
*Title*: *On demand cluster discovery per route is trowing error*

*Repro steps*:

```listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: ingress_all_routes
            virtual_hosts:
            - name: multi-dc-cluster
              domains: ["*"]
              routes:
              - name: default
                match: {prefix: "/*"}
                route:
                  cluster_header: "xds_cluster"
                typed_per_filter_config:
                  envoy.filters.http.on_demand:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.PerRouteConfig
                    odcds:
                      source:
                        resource_api_version: V3
                        api_config_source:
                          api_type: DELTA_GRPC
                          transport_api_version: V3
                          grpc_services:
                            envoy_grpc:
                              cluster_name: xds_cluster

          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
  

*Logs*:
> Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].routes[0].typed_per_filter_config[0].value): invalid value Invalid type URL

Envoy Version: 1.18.2

**Comment by ravenblackx** [comment]
http.on_demand is disabled by default [here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_build_config.bzl#L156-L170)

You can apparently enable them per [this doc](https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#L730-L734), or if you're not building it yourself you'll need to find an image that includes the filters you want to use.

**Comment by balu-ce** [comment]
@ravenblackx I am using envoy version of 1.18.2 not as a container. can you suggest some ways to enable this

**Comment by ravenblackx** [comment]
Apparently I'm completely wrong about this, the disabled-by-default comment refers to only one filter, not the block of filters below the comment, so instead I too am baffled as to why your config isn't parsing.

**Comment by ravenblackx** [comment]
Looks like there's another issue with approximately the same problem, too, https://github.com/envoyproxy/envoy/issues/29836

**Comment by ravenblackx** [comment]
Ah, in this case it's the version - at v1.18 on_demand.v3 [doesn't have](https://github.com/envoyproxy/envoy/blob/release%2Fv1.18/api/envoy/extensions/filters/http/on_demand/v3/on_demand.proto) a `PerRouteConfig`

First release it's in is `v1.23`
