### ISSUE TITLE
New extension: set filter state

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#29813]
Similar to the set_metadata extension, there's a need to set the filter state value via an extension in order to implement more advanced use cases:

1. Propagate host_header from CONNECT as the original destination host in the upstream internal listener.
2. Propagate source IP to the upstream internal listener to enforce policy on the internal listener.
3. Propagate downstream peer TLS URL SAN to the internal listener for the policy enforcement.
4. Set downstream SNI as the upstream SNI.
5. Override ALPN via a mapping (h2 -> istio-h2).

These use cases have been realized in Istio via custom extensions, but they all fit the same pattern of unconditional filter state object update with a simple expression (e.g. access log template variables or CEL), and don't require the heavy machinery and overhead of Lua or Wasm.

I'm willing to implement this in envoy but looking for a code co-owner. @envoyproxy/envoy-maintainers, @yanjunxiang-google or anyone else interested.

Ref: #29681

**Comment by gitanuj** [comment]
This sounds like a great idea! Would it be possible to use this for setting filter state to something like `prefixstring<DYNAMIC_METADATA>suffixstring` where `<DYNAMIC_METADATA>` is emitted by a previous filter? (I'm specifically interested if I can use dynamic metadata emitted by proxy protocol listener - based on TLV header)

That is the whole reason I have to use a custom WASM filter!

**Comment by kyessenov** [comment]
Yeah, I think `prefixstring%DYNAMIC_METADATA(com.test.my_filter:test_object:inner_key)%suffixstring` would work.

**Comment by ohadvano** [comment]
Great addition IMO, I could do the after work to add UDP session filter afterwards, so was pleased to see that you already implemented it in a way that uses common code, thanks!
Just a general note, are you going to enforce the rule key names? I was hoping that not - so external extensions can use this filter for not "well-known" keys (i.e. custom extension FS keys).

**Comment by kyessenov** [comment]
The keys have a registration mechanism, and I think it makes sense for external extensions to define their keys via this mechanism. Otherwise, it's not clear what C++ type to use to instantiate it. We could create some new dynamic way to register a key, like what Wasm does, but it's clunky and the static mechanism is good enough for now.

**Comment by ohadvano** [comment]
Sorry, not sure I understand. What prevents me from setting FS object with some arbitrary key as I want in filter A then consume the value of that key in consecutive filter B?
What kind of registration is required?

**Comment by kyessenov** [comment]
@ohadvano 
Filter B needs to declare REGISTER_FACTORY for the object factory for the key. Hopefully, add a note here https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_filter_state#well-known-filter-state so it's not hidden in the code base. See https://github.com/envoyproxy/envoy/pull/29782 for example.

**Comment by ohadvano** [comment]
I see, wasn't familiar with the object factory, thanks
