### ISSUE TITLE
WASM : wasmtime/wamr/wavm support in official build

### ISSUE THREAD

**Issue by sujeshkumar** [envoyproxy/envoy#29827]
WASM: wasmtime/wamr/wavm support in official build

*Description*:

Official build of envoy does not support wasmtime/wamr/wavm runtime ( effectively making only v8 as active one ) .
Is there any specific reason why these are not supported in official build ? 
Is it due to potential issues building them together in binary or security related issues ?

envoy.wasm.runtime.wamr: [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime/)-based WebAssembly runtime. This runtime is not enabled in the official build.

envoy.wasm.runtime.wavm: [WAVM](https://wavm.github.io/)-based WebAssembly runtime. This runtime is not enabled in the official build.

envoy.wasm.runtime.wasmtime: [Wasmtime](https://wasmtime.dev/)-based WebAssembly runtime. This runtime is not enabled in the official build.

**Comment by alyssawilk** [comment]
AFIK the main barrier to wasm is it missing testing and docs.  cc @mpwarres @lizan as owners to comment more

**Comment by sujeshkumar** [comment]
@mpwarres @lizan - any thoughts ..? if I enable wasmtime as part of the build (in the envoy fork I am using) , do you see any security issue(s)/stability issues ?

**Comment by mpwarres** [comment]
On the proxy-wasm side, I'm not aware of issues with building the engines together (proxy-wasm-cpp-host supports a [multiengine](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/b7e690703c7f26707438a2f1ebd7c197bc8f0296/bazel/BUILD#L55) build config), or specific issues blocking those runtimes from being used. @PiotrSikora may know if there are any historical issues.

As @alyssawilk pointed out, we still need to improve documentation and testing before WasmFilter can move out of alpha.

**Comment by PiotrSikora** [comment]
> AFIK the main barrier to wasm is it missing testing and docs. cc @mpwarres @lizan as owners to comment more

@alyssawilk I don't believe there was ever any issue with testing Wasm, since it had sufficient test coverage from the very first PR, and while the documentation is probably still missing, the lack of it applies the same to V8 as to the other Wasm engines.

As @mpwarres mentioned, there are no technical reason not to support them all in a single build, since we do that in Proxy-Wasm C++ Host, so it's really about justifying the need for the alternative Wasm engines in the official build... Why do you prefer Wasmtime instead of V8?

**Comment by sujeshkumar** [comment]
wasmtime seems to be faster compared to v8 ( and probably safer in terms of security as well)

**Comment by phlax** [comment]
> it's really about justifying the need for the alternative Wasm engines in the official build.

my concern here would be increased build times, larger binaries, and larger potential attack surfaces - im wondering if there is realistically ever a need for more than one engine in a build

**Comment by sujeshkumar** [comment]
I don't think there is really a practical need for more than one engine in a build , but some may prefer one engine vs another due to various reasons . 
<< larger potential attack surfaces >> This really depends on the kind of engine being used right ?

**Comment by PiotrSikora** [comment]
> wasmtime seems to be faster compared to v8 ( and probably safer in terms of security as well)

Any data points?
