### ISSUE TITLE
Filesystem config update failure: Unable to parse JSON as proto

### ISSUE THREAD

**Issue by martha889** [envoyproxy/envoy#29836]
*Title*: *One line description*
Filesystem config update failure: Unable to parse JSON as proto. This is happening after upgrading from v1.12 to v1.14

*Description*:
Filesystem config update failure: Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[2].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.health_check.v3.HealthCheck for type Any)

This is the config:
```
http_filters:
233         - name: envoy.filters.http.local_ratelimit
234           typed_config:
235             "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
236             stat_prefix: http_local_rate_limiter
237         - name: envoy.filters.http.header_to_metadata
238           typed_config:
239             "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
240         - name: envoy.filters.http.health_check
241           typed_config:
242             "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
243             pass_through_mode: false
244             headers:
245               - name: ":path"
246                 exact_match: "/http_health_check"
247         - name: envoy.filters.http.router
```
Tried editing a few things, looks like the typed_config key value is causing problems.
Any help would be appreciated. Thanks!

**Comment by phlax** [comment]
hi @martha889 what version of Envoy are you testing with ?

can you check that you are following docs matching the version - if so we can folllow up

**Comment by phlax** [comment]
apologies - i just read ...

> v1.12 to v1.14

unfortunately we no longer support either of those versions - current latest is 1.27.0 - we can proabably help if you run into issues upgrading
