### ISSUE TITLE
Docs - Configuration observability page has no mention on how to configure tracers

### ISSUE THREAD

**Issue by joaopgrassi** [envoyproxy/envoy#29838]
*Description*:

The [Observability](https://www.envoyproxy.io/docs/envoy/v1.27.0/configuration/observability/observability) page under "Configuration reference" has no mention of the tracers available in Envoy nor how to configure them. 

The only thing it's available is the proto documentation for [HTTP Tracers](https://www.envoyproxy.io/docs/envoy/v1.27.0/api-v3/config/trace/trace) but IMO that is not helpful if you are starting and want to configure things. I had a hard time figuring out how the yaml should look like and it was a lot of trial and error. Finally I found some test/sample app out there that helped me make it work.

It would be nice if we could list all the available tracers we have in Envoy and show how they can be configured.

**Comment by phlax** [comment]
> not helpful if you are starting and want to configure things.

would you be able to PR any improvements to this page? 

> I had a hard time figuring out how the yaml should look like and it was a lot of trial and error. Finally I found some test/sample app

i try to encourage full bootstrap snippets covering as much config as possible - if there is some config/s we can add for this i would be happy

> It would be nice if we could list all the available tracers we have in Envoy and show how they can be configured.

perhaps we need to expand a section here with pages for individual tracers

some have sandboxes - which are generally the best way to get started so maybe that is a better way to exemplify configs
