### ISSUE TITLE
Consider removing yapf

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#29850]
Im not a big fan of enforced formatting - at least when it comes to python and have a strong preference for standards linting

i went with yapf because it was at least configurable - not sure how much is due to our config but the result is pretty awful

the software itself is not well designed and when integrating to `code.check` i had to do various things to prevent it using huge amounts of unnecessary resources

afaict at least in recent iterations doing `import yapf` brings a lot of unwanted/unexpected behaviour - and eg because protodoc lints rst and therefore has the side-effect of just importing yapf in the import chain - i think its slowing things down

**Comment by phlax** [comment]
cc @htuch @moderation

**Comment by phlax** [comment]
i noticed due to a flakey fail when building in the website repo - which may/not have been an OOM, and may/not have been related if it was

**Comment by moderation** [comment]
I'm a fan of enforced formatting and `go fmt`, `zig fmt`, `deno fmt`  seem to be generally accepted as good ideas with minimal to no config needed. I like `black` but I recall you not liking that either. There is a slightly different implementation of `black` called [`blue`](https://blue.readthedocs.io/en/latest/). 

But maybe we should look at [Ruff](https://docs.astral.sh/ruff/). It is a new Python linter written in Rust that should be 10-100x faster and consume less resources.

**Comment by phlax** [comment]
> ... It is a new Python linter written in Rust that should be 10-100x faster and consume less resources.

so even if i dont like the result at least it doesnt do a yapf 8/

i can look at these - its only for in-repo code - in toolshed where most of the py is now its quite happily getting a strict flake8/mypy/docfmt

tbh - for the bits that are remaining at this point i think i would prefer black over what we have

my main issue with all of them boils down to - sometimes you need to express complex logic - ie you dont want to break it out to methods/properties/functions/classes elsewhere - it needs to be expressed in one place

for this kinda situation i use code like:

```python
do_something = (
   some_outcome
   if some_condition or other_condition
   else (perhaps
            if lateral_concern
            else default))
```

similar with complex loops/generators

ive yet to find a formatter that doesnt turn this into illegible nonsense which defeats the point of expressing it in this way - and at least for me results in breaking it up

**Comment by phlax** [comment]
hmm - its flaking pretty hard with my current website plan

```console
4:09:07 PM:     from yapf.pytree import pytree_utils
4:09:07 PM:   File "/opt/buildhome/.cache/bazel/_bazel_buildbot/9a72ce7fe51e5e46a147640bcd3de03b/sandbox/processwrapper-sandbox/386/execroot/envoy-website/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/envoy/tools/protodoc/protodoc.runfiles/base_pip3_yapf/site-packages/yapf/pytree/pytree_utils.py", line 30, in <module>
4:09:07 PM:     from yapf_third_party._ylib2to3 import pygram
4:09:07 PM:   File "/opt/buildhome/.cache/bazel/_bazel_buildbot/9a72ce7fe51e5e46a147640bcd3de03b/sandbox/processwrapper-sandbox/386/execroot/envoy-website/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/envoy/tools/protodoc/protodoc.runfiles/base_pip3_yapf/site-packages/yapf_third_party/_ylib2to3/pygram.py", line 29, in <module>
4:09:07 PM:     python_grammar = driver.load_grammar(_GRAMMAR_FILE)
4:09:07 PM:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4:09:07 PM:   File "/opt/buildhome/.cache/bazel/_bazel_buildbot/9a72ce7fe51e5e46a147640bcd3de03b/sandbox/processwrapper-sandbox/386/execroot/envoy-website/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/envoy/tools/protodoc/protodoc.runfiles/base_pip3_yapf/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 252, in load_grammar
4:09:07 PM:     g.load(gp)
4:09:07 PM:   File "/opt/buildhome/.cache/bazel/_bazel_buildbot/9a72ce7fe51e5e46a147640bcd3de03b/sandbox/processwrapper-sandbox/386/execroot/envoy-website/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/envoy/tools/protodoc/protodoc.runfiles/base_pip3_yapf/site-packages/yapf_third_party/_ylib2to3/pgen2/grammar.py", line 95, in load
4:09:07 PM:     d = pickle.load(f)
4:09:07 PM:         ^^^^^^^^^^^^^^
```

https://app.netlify.com/sites/envoy-website/deploys/651595fa39ad0b0008625bc0#L254

probs ill have to at least something to disable rst checking in website docs build

**Comment by phlax** [comment]
thinking about using a rust tool a bit more - the benefit of using python has been that we can override/integrate the various tools file discovery

having said that - it has been mostly to resolve issues like the one im flagging here so if the underlying tool is fast anyway the point maybe moot

ill do some experimenting with envoy.code.check - initially at least to prevent unwanted yapf imports, and we can figure from there
