### ISSUE TITLE
Binary size difference between v1.24 and v1.25?

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#29856]
*Title*: *Binary size difference?*

*Description*:
I've been building Envoy for years with `./ci/run_envoy_docker.sh "./ci/do_ci.sh bazel.release.server_only"`. I noticed in v1.25 I can't find the `build_release_stripped` folder and the Envoy binary I can find is about 8x larger than I'm used to seeing. I've looked through the other build targets and only found `bazel.sizeopt.server_only` which made almost no difference. Hoping to get some help getting back to ~60MB builds

**Comment by suniltheta** [comment]
If you build on the current main you would find the binary as a tar.gz in under `/build/envoy/x64/envoy_binary.tar.gz` given you have set `ENVOY_DOCKER_BUILD_DIR=~/build` like mentioned in https://github.com/envoyproxy/envoy/blob/main/ci/README.md#on-linux

**Comment by phlax** [comment]
@phylake i will take a look at this - i made some changes to adjacent code - but i didnt think this should be affected - ill check

**Comment by phylake** [comment]
Just tried this again. The only tar.gz I find is this
```
ubuntu@ip-10-0-0-80:~/envoy$ sudo find /tmp/envoy-docker-build/ -path "*.tar.gz"
/tmp/envoy-docker-build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/rules_pkg/tests/testdata/tar_test.tar.gz
```

The envoy executable I find is here
```
ubuntu@ip-10-0-0-80:~/envoy$ sudo find /tmp/envoy-docker-build/ -type f -path "*envoy"
/tmp/envoy-docker-build/envoy/source/exe/envoy/envoy
```

and it's a whopper compared to v1.24 built the same way

```
ubuntu@ip-10-0-0-80:~/envoy$ ls -alh /tmp/envoy-docker-build/envoy/source/exe/envoy/envoy
-r-xr-xr-x 1 root docker 448M Sep 29 18:33 /tmp/envoy-docker-build/envoy/source/exe/envoy/envoy
```

**Comment by phlax** [comment]
im guessing its something to do with a change in flags - ideally you want it building with `-c opt` - im _guessing_ the larger bins are fastbuild - but not sure

**Comment by phylake** [comment]
I build with `bazel.sizeopt.server_only` which should have set [`COMPILE_TYPE="opt"`](https://github.com/envoyproxy/envoy/blob/v1.25.9/ci/do_ci.sh#L114) but the binary is still 434MB
