### ISSUE TITLE
socket_option_impl calls strerror on the wrong value

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#2986]
In source/common/network/socket_option_impl.cc, some of the logging calls strerror(). In the case where the socket option isn't available at compile-time, it correctly passes ENOTSUP, which is fine. In the case that setsockopt() fails, strerror is passed the return value (-1) instead of the value in errno.

**Comment by cmluciano** [comment]
@ggreenway Can you assign this issue to me?
