### ISSUE TITLE
ext_proc: Allow multiple set-cookie response headers

### ISSUE THREAD

**Issue by Ronnie-personal** [envoyproxy/envoy#29861]
*Title*: *ext_proc: Allow multiple set-cookie response headers*

*Description*:
When ext_proc receives multiple set-cookie response headers, all set-cookie headers should be returned to the caller (client). The set-cookie header should not be overwritten by the last set-cookie header.

[optional *Relevant Links*:]
The issue is also mentioned in https://github.com/envoyproxy/envoy/issues/8649#issuecomment-1340109538

Is this code [new_header->set_value](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_proc/mutation_utils.cc#L68) causing the issue?

**Comment by ravenblackx** [comment]
I think you're right, and replacing set_value with addCopy would do the desired.

@gbrail @stevenzzzz for codeowner opinions.

**Comment by gbrail** [comment]
Is Envoy not doing the right thing here, or is this a question of usage? The ext_proc protocol uses a "HeaderValueOption" message for header changes, which supports the ability to overwrite a header with a new value or append the value to an existing header. The filter should be able to support either use case.

**Comment by gbrail** [comment]
Looking at the code in "mutation_utils.cc" that processes header options, I can see that the "append" flag of the HeaderValueOption structure is being honored, but the new "append_action" field is not being checked. It looks like when this field was added to the proto, the new behavior wasn't applied throughout the codebase. Same probably goes for the "keep_empty_value" flag.

This would be a good and important thing to clean up...

Also, given the large number of options and rules around header modifications now, there should be a single library somewhere that implements them all.

**Comment by stevenzzzz** [comment]
@Ronnie-personal do you want to shoot a PR?

**Comment by stevenzzzz** [comment]
also ping @tyxia @yanjunxiang-google @yanavlasov

**Comment by yanjunxiang-google** [comment]
It looks to me if ext_proc server send response with append 
 = true, then it shoud work: https://github.com/envoyproxy/envoy/blob/c36f2c7798fc738f0cd15d7fca1e4c1ceb2308e9/api/envoy/config/core/v3/base.proto#L380

**Comment by Ronnie-personal** [comment]
> @Ronnie-personal do you want to shoot a PR?

Thanks for your comments, I'm working on this issue.

**Comment by Ronnie-personal** [comment]
> It looks to me if ext_proc server send response with append = true, then it should work with the current code:
> 
> https://github.com/envoyproxy/envoy/blob/c36f2c7798fc738f0cd15d7fca1e4c1ceb2308e9/api/envoy/config/core/v3/base.proto#L380
> 
> We can deal with change the default value of this field in ext_proc filter to be true and honor append_action in later cleanups.

@yanjunxiang-google  Thanks for the triage!
I would like to add two tests:
**Test 1** involves passing multiple 'Set-Cookie' response headers in HeaderMutations from the external processor server to the ext_proc filter with HeaderValueOption.append set to true. The expected outcome is multiple 'Set-Cookie' headers.

 In **Test 2**, HeaderValueOption.append is set to false, and the expected result is to see only one 'Set-Cookie' header.

Could you please inform me where I should add the test cases—either in `test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc` or `test/extensions/filters/http/ext_proc/filter_test.cc`? Are there any **existing similar tests** that I can use as a reference?

**Comment by Ronnie-personal** [comment]
> Looking at the code in "mutation_utils.cc" that processes header options, I can see that the "append" flag of the HeaderValueOption structure is being honored, but the new "append_action" field is not being checked. It looks like when this field was added to the proto, the new behavior wasn't applied throughout the codebase. Same probably goes for the "keep_empty_value" flag.
> 
> This would be a good and important thing to clean up...
> 
> Also, given the large number of options and rules around header modifications now, there should be a single library somewhere that implements them all.

  @gbrail 
  Could you provide guidance on where you envision adding the new code library in the project's directory structure? Which folder or directory would be the most suitable home for this library?

Are there any naming conventions or guidelines you'd recommend for naming the code file that will contain this header modification library? Having a consistent and descriptive name can help with clarity and maintainability.

Are there any existing code libraries within the project that serve as good examples or templates for organizing and structuring this new library? Learning from existing practices can be valuable when creating a new component.

**Comment by yanjunxiang-google** [comment]
> > It looks to me if ext_proc server send response with append = true, then it should work with the current code:
> > https://github.com/envoyproxy/envoy/blob/c36f2c7798fc738f0cd15d7fca1e4c1ceb2308e9/api/envoy/config/core/v3/base.proto#L380
> > 
> > We can deal with change the default value of this field in ext_proc filter to be true and honor append_action in later cleanups.
> 
> @yanjunxiang-google Thanks for the triage! I would like to add two tests: **Test 1** involves passing multiple 'Set-Cookie' response headers in HeaderMutations from the external processor server to the ext_proc filter with HeaderValueOption.append set to true. The expected outcome is multiple 'Set-Cookie' headers.
> 
> In **Test 2**, HeaderValueOption.append is set to false, and the expected result is to see only one 'Set-Cookie' header.
> 
> Could you please inform me where I should add the test cases—either in `test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc` or `test/extensions/filters/http/ext_proc/filter_test.cc`? Are there any **existing similar tests** that I can use as a reference?

HI, @Ronnie-personal 

There are existing test to verify the "append = true" or "append = faluse" behavior. You can check below:
https://github.com/envoyproxy/envoy/blob/f04ac9ddce9f569ba22c9d26d4958b99bed31a1b/test/extensions/filters/http/ext_proc/mutation_utils_test.cc#L52

Specially, you can check the two headers: "x-append-this" and "x-replace-this" in the expected headers:
https://github.com/envoyproxy/envoy/blob/f04ac9ddce9f569ba22c9d26d4958b99bed31a1b/test/extensions/filters/http/ext_proc/mutation_utils_test.cc#L158

**Comment by Ronnie-personal** [comment]
> > > It looks to me if ext_proc server send response with append = true, then it should work with the current code:
> > > https://github.com/envoyproxy/envoy/blob/c36f2c7798fc738f0cd15d7fca1e4c1ceb2308e9/api/envoy/config/core/v3/base.proto#L380
> > > 
> > > We can deal with change the default value of this field in ext_proc filter to be true and honor append_action in later cleanups.
> > 
> > 
> > @yanjunxiang-google Thanks for the triage! I would like to add two tests: **Test 1** involves passing multiple 'Set-Cookie' response headers in HeaderMutations from the external processor server to the ext_proc filter with HeaderValueOption.append set to true. The expected outcome is multiple 'Set-Cookie' headers.
> > In **Test 2**, HeaderValueOption.append is set to false, and the expected result is to see only one 'Set-Cookie' header.
> > Could you please inform me where I should add the test cases—either in `test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc` or `test/extensions/filters/http/ext_proc/filter_test.cc`? Are there any **existing similar tests** that I can use as a reference?
> 
> HI, @Ronnie-personal
> 
> There are existing test to verify the "append = true" or "append = faluse" behavior. You can check below:
> 
> https://github.com/envoyproxy/envoy/blob/f04ac9ddce9f569ba22c9d26d4958b99bed31a1b/test/extensions/filters/http/ext_proc/mutation_utils_test.cc#L52
> 
> Specially, you can check the two headers: "x-append-this" and "x-replace-this" in the expected headers:
> 
> https://github.com/envoyproxy/envoy/blob/f04ac9ddce9f569ba22c9d26d4958b99bed31a1b/test/extensions/filters/http/ext_proc/mutation_utils_test.cc#L158

@yanjunxiang-google  Thanks for the prompt reply and thanks for sharing the tests!
Sorry I have a dumb question about the existing tests, does it test the request headers or response headers?

**Comment by Ronnie-personal** [comment]
@gbrail 
 I would like to follow up on the questions posted in https://github.com/envoyproxy/envoy/issues/29861#issuecomment-1742287575
 
 I will update `mutation_utils.cc` to honor HeaderValueOption.append_action.
 I'm very happy to work on the common library if you could provide more guidance.
 
 Thanks

**Comment by yanjunxiang-google** [comment]
HI, @Ronnie-personal ,

For the above mutation_utils_test.cc, it is unit test which test mutation logic: MutationUtils::applyHeaderMutations(mutation, headers,...)
The headers can be either request or response headers. It does not matter here.

If you set "append" to true, then the headers will be appended as it is even though they are identical. This is by the API design.

**Comment by Ronnie-personal** [comment]
@yanjunxiang-google  Thanks for the reply, it's very helpful!

> If you set "append" to true, then the headers will be appended as it is even though they are identical. This is by the API design.

In my upstream API, I set two response headers:
Set-Cookie: SomeValue
Set-Cookie: AnotherValue

In my API client, we see four response headers:
Set-Cookie: SomeValue
Set-Cookie: SomeValue
Set-Cookie: AnotherValue
Set-Cookie: AnotherValue

Could you please confirm this is the expected behavior? So ext_proc add the duplicate copy of the cookie?

**Comment by yanjunxiang-google** [comment]
This is not expected. I suspect you have same headers in your original header
Set-Cookie: SomeValue
Set-Cookie: AnotherValue
Then you ext_proc server header mutation added them which cause two copies of it.

Anyway, I recommend you go through the code here to understand the logic: 
https://github.com/envoyproxy/envoy/blob/9f8b7ea19b7fe7edd4e7f339b3509b7741db0ac1/source/extensions/filters/http/ext_proc/mutation_utils.cc#L114

**Comment by tyxia** [comment]
I agree with Yanjun's comment above. I think the problem is that your original request already has 
Set-Cookie: SomeValue
Set-Cookie: AnotherValue

It is expected append behavior in Envoy for `set_cookie` that multiple duplicate headers. So the question should be 
: Why you ext_proc sever want to add the exact same header as original request?

Regarless, I think you can leverage `ADD_IF_ABSENT ` but not `APPEND_IF_EXISTS_OR_ADD`  to resolve your issue.
