### ISSUE TITLE
Decompressor filter not compatible with gRPC transcoder

### ISSUE THREAD

**Issue by fdfzcq** [envoyproxy/envoy#29872]
*Decompressor filter is not compatible with gRPC-JSON transcoder*

*Description*:
The decompressor filter in envoy today adds some trailers not supported by gRPC

*Repro steps*:
* Run envoy with [decompressor filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/decompressor_filter) and [grpc-json-transcoder filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#envoy-v3-api-msg-extensions-filters-http-grpc-json-transcoder-v3-grpcjsontranscoder), you can see the configuration used below
* Send a json request compressed with gzip results in a 404, uncompressed request worked
```
2023/09/11 14:54:45 ':status', '404'
2023/09/11 14:54:45 'content-type', 'text/plain; charset=utf-8'
2023/09/11 14:54:45 'grpc-status', '12'
2023/09/11 14:54:45 'grpc-message', 'Expected path but is missing'
2023/09/11 14:54:45 'x-envoy-upstream-service-time', '4'
2023/09/11 14:54:45 'date', 'Mon, 11 Sep 2023 14:54:45 GMT'
2023/09/11 14:54:45 'server', 'envoy'
```
* After some wireshark debugging I see that the payload resulted in 404 had trailer headers, and that seems to have confused the gRPC service.
![Screenshot 2023-09-27 at 12 03 47](https://github.com/envoyproxy/envoy/assets/5684684/fedb1e0c-aaf9-4aad-994a-71654f5088f1)
* I then added a lua filter to strip trailers `x-envoy-decompressor-small-compressed-bytes` and `x-envoy-decompressor-small-uncompressed-bytes` and the compressed request yielded a 200

Are these trailers used anywhere else in envoy or is it safe to remove them in requests? If so one solution ahead could be making these trailers configurable? 

*Admin and Stats Output*:
(I don't think this is needed here, but do ping me if you need this)

*Config*:
```
{
  "staticResources": {
    "listeners": [
      {
        "address": {
          "socketAddress": {
            "address": "0.0.0.0",
            "portValue": 8090
          }
        },
        "filterChains": [
          {
            "filters": [
              {
                "name": "envoy.filters.network.http_conection_manager",
                "typedConfig": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                  "statPrefix": "ingress_http",
                  "routeConfig": {
                    "name": "local_route",
                    "virtualHosts": [
                      {
                        "name": "backend",
                        "domains": [
                          "*"
                        ],
                        "routes": [
                          {
                            "match": {
                              "prefix": "/",
                              "grpc": {}
                            },
                            "route": {
                              "cluster": "grpc",
                              "timeout": "60s"
                            },
                            "requestHeadersToAdd": [
                              {
                                "header": {
                                  "key": "grpc-timeout",
                                  "value": "3S"
                                },
                                "appendAction": "OVERWRITE_IF_EXISTS_OR_ADD"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  },
                  "httpFilters": [
                    {
                      "name": "envoy.filters.health_check",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck",
                        "passThroughMode": false,
                        "clusterMinHealthyPercentages": {
                          "grpc": {
                            "value": 100
                          }
                        },
                        "headers": [
                          {
                            "name": ":path",
                            "stringMatch": {
                              "exact": "/_ping"
                            }
                          }
                        ]
                      }
                    },
                    {
                      "name": "envoy.filters.http.decompressor",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor",
                        "decompressorLibrary": {
                          "name": "small",
                          "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip"
                          }
                        }
                      }
                    },
                    {
                      "name": "envoy.filters.http.lua",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua",
                        "defaultSourceCode": {
                          "inlineString": "\nfunction envoy_on_request(request_handle)\n\trequest_handle:trailers():remove(\"x-envoy-decompressor-small-compressed-bytes\")\n\trequest_handle:trailers():remove(\"x-envoy-decompressor-small-uncompressed-bytes\")\nend\n"
                        }
                      }
                    },
                    {
                      "name": "envoy.filters.http.grpc_http1_bridge",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_http1_bridge.v3.Config",
                        "upgradeProtobufToGrpc": true
                      }
                    },
                    {
                      "name": "envoy.filters.http.grpc_json_transcoder",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder",
                        "protoDescriptor": "tmp/proto.pb",
                        "services": [
                          "spotify.concat.v1.ConcatService"
                        ],
                        "printOptions": {
                          "addWhitespace": true,
                          "alwaysPrintPrimitiveFields": true
                        },
                        "autoMapping": true,
                        "convertGrpcStatus": true,
                        "maxResponseBodySize": 5242880
                      }
                    },
                    {
                      "name": "envoy.filters.http.router",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                      }
                    }
                  ],
                  "localReplyConfig": {
                    "mappers": [
                      {
                        "filter": {
                          "statusCodeFilter": {
                            "comparison": {
                              "value": {
                                "defaultValue": 400,
                                "runtimeKey": "key_b"
                              }
                            }
                          }
                        },
                        "bodyFormatOverride": {
                          "jsonFormat": {
                            "code": 3,
                            "details": [],
                            "message": "%LOCAL_REPLY_BODY%"
                          },
                          "omitEmptyValues": true,
                          "contentType": "application/json"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }
        ]
      }
    ],
    "clusters": [
      {
        "name": "grpc",
        "type": "LOGICAL_DNS",
        "connectTimeout": "1s",
        "loadAssignment": {
          "clusterName": "grpc",
          "endpoints": [
            {
              "lbEndpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socketAddress": {
                        "address": "host.docker.internal",
                        "portValue": 5990
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "healthChecks": [
          {
            "timeout": "1s",
            "interval": "100000s",
            "unhealthyThreshold": 5,
            "healthyThreshold": 2,
            "grpcHealthCheck": {},
            "noTrafficInterval": "100000s"
          }
        ],
        "typedExtensionProtocolOptions": {
          "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
            "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
            "explicitHttpConfig": {
              "http2ProtocolOptions": {}
            }
          }
        }
      }
    ]
  },
  "admin": {
    "address": {
      "socketAddress": {
        "address": "0.0.0.0",
        "portValue": 9901
      }
    }
  }
}
```

*Logs*:
(I don't think this is needed here, but do ping me if you need this)

**Comment by ravenblackx** [comment]
It looks to me like making those trailers configurably-excluded would be a valid thing to do, and maybe desirable anyway.

But it seems more problematic, and surprising, that the transcoder filter breaks in the presence of irrelevant trailers - are you sure that's the problem, and not, e.g. `content-length` header being present and correct when you send uncompressed but [absent](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/decompressor/decompressor_filter.h#L180) when decompress has occurred?

**Comment by ravenblackx** [comment]
Welp, looks like you're right: https://github.com/akka/akka-grpc/issues/1172 which they fixed by not sending trailers.

Might it make more sense to have the grpc transcoder filter handle this situation better?

It's strange that unexpected trailers can cause a problem given that the grpc transcoder [doesn't even look at the trailers](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L607), but their presence does change the flow so probably I'm just missing something there.

**Comment by ravenblackx** [comment]
Ah, of course, the problem is that the filter *passes the trailers through unchanged*, so they get to the actual grpc handler which can theoretically accept any trailers. So stripping trailers in the transcoder doesn't make sense because they *might be* meaningful to the upstream.

So it's not that it's incompatible with gRPC transcoder, it's that it's potentially incompatible with a gRPC upstream, I think?

And as such, configurably turning off the addition of irrelevant trailers seems like a very reasonable option.

@kbaichoo as owner of decompressor, for more knowledgable thoughts.

**Comment by fdfzcq** [comment]
Thanks for looking into this so quick! @ravenblackx I think the debug log shows that the trailers were forwarded to upstream, and maybe one bug in the gRPC transcoder filter is that it doesn't remove trailers incompatible with HTTP2.

**Comment by fdfzcq** [comment]
I might be misreading, but seems like request trailers aren't supported by the protocol according to https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md and https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2

**Comment by ravenblackx** [comment]
You're right, in light of that it seems like the more appropriate thing as a fix would be to drop all trailers in the transcoder filter (or I guess make that configurable with options drop, pass through or reject, since probably someone relies on trailers passing through, and the spec doesn't suggest that trailers are *forbidden*, just that they're not expected)

But *also* making the added trailers optional in the decompressor filter seems reasonable too!

@qiwzhang as codeowner of grpc_transcoder_filter, for more knowledgable thoughts on this.

**Comment by KBaichoo** [comment]
Agreed that if it's unexpected by the protocol (and doesn't work with your upstream) that we should do some sanitization. It seems more general in the grpc_transcoder_filter imo than in the decompressor.

cc @nareddyt  regarding grpc_transcoder_filter.

**Comment by nareddyt** [comment]
> (or I guess make that configurable with options drop, pass through or reject, since probably someone relies on trailers passing through, and the spec doesn't suggest that trailers are forbidden, just that they're not expected)

Yes we'll probably need to expose these options to prevent breaking behavior changes. Even though the spec doesn't expect trailers, www.hyrumslaw.com :)

I'm curious, what gRPC backend are you using? AFAIK Google's gRPC backends do **not** reject requests due to trailers in the request. One of our envoy-based projects has integration tests with decompressor + transcoder, and they all work.

https://github.com/GoogleCloudPlatform/esp-v2/blob/master/tests/integration_test/compression_test/compression_test.go

I can add this configurability in either case, but I'm consider how feasible it is to integration test this behavior.

Also I want to point out - for this situation where the decompressor sits in front of the transcoder, it makes sense to have the transcoder sanitize input to match the spec. However, if there are other filters that sit after the transcoder, this fix will not help. (though I can't think of any other filters off the top of my head that add request trailers)

**Comment by nareddyt** [comment]
Disregard my comment about the integration test. That is actually testing response compression, not request decompression. Please do let me know if Google's gRPC server also rejects trailers in the request.

**Comment by fdfzcq** [comment]
@nareddyt thank you for looking into this. Yes we are using Google gRPC, to be specific https://github.com/grpc/grpc-java
