### ISSUE TITLE
The filter chain of encodeData is paused when filters add trailers

### ISSUE THREAD

**Issue by cqi1217** [envoyproxy/envoy#29879]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
When I configure a decompressor filter and a Json to Metadata filter for upstream response, my request will be stalled until timeout. From the log looks like it is because decompressor calls addEncodedTrailers() in the encodeData(), which causes Json to Metadata filter(I have a local patch to support response) paused at encodeData() and encodeTrailer() is not called.

some investigation: In the response side if filterA adds trailers and filterB returns StopInteration in EncodeData, `commonHandleAfterDataCallback` will return in the file_manager::EncodeData and skip handling EncodeTrailer for filterB at the last data chunk, i.e, end_stream==true.

There was a fix https://github.com/envoyproxy/envoy/pull/18055/files but it only fixed decodeData, encodeData still has the issue.
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

In the response filter chain, add decompressor filter first and then add another filter which will return StopInteration in EncodeData if end_stream==false; and it will be blocked on the second filter until timeout.

**Comment by cqi1217** [comment]
@KBaichoo @mattklein123

**Comment by JuniorHsu** [comment]
From prior art we need a runtime guard and it's unclear how large the scope is. If we want to get unblocked, are we able to make trailer optional in the decompression filter?

**Comment by JuniorHsu** [comment]
Let's keep it open. @KBaichoo or @zuercher  could you help to open? Thanks.
I could work on this while I get a chance.
