### ISSUE TITLE
support allowed methods in routes

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#29889]
Currently if we match on ":method" and if the incoming method is not part of the route, we return 404. We would like to list allowed methods in route, which is used before route matching and returns 405.

**Comment by zuercher** [comment]
We'd have to be careful not to break existing configurations with this change.

That said, in one of our configs, we have what we'd consider our default route configured to match `GET` with path prefix `/` followed by a catch-all route (just path prefix of `/`) that returns a 405.
