### ISSUE TITLE
sslVerifyClientStatus=optional equivalent in envoy-proxy?

### ISSUE THREAD

**Issue by alnhk** [envoyproxy/envoy#29885]
*Title: sslVerifyClientStatus=optional equivalent in envoy-proxy?*

Just like in nginx, we can implement mTLS (optional by using this below example :
```
        ssl_client_certificate /etc/nginx/root-ca/acme-ca-bundle.pem;
        ssl_verify_client optional;

 location / {
            if ($ssl_client_verify != SUCCESS) {
                return 400 "No required SSL Certificate was sent";
                break;
            }
        }

```

In the above example, how do we implement in envoy-proxy, yes googled and found this  mtls in envoy - https://github.com/salrashid123/envoy_mtls 
yet trying to understand if theres condition to ignore mTLS for "/healthcheck" and enforce mTLS for "/" ? Please share an example., we understand there is flag `only_verify_leaf_cert_crl` which is boolean true or false, yet, wanted to know if there's condition if set to `false` as default and make "/" mTLS enforced ?

**Comment by zuercher** [comment]
I don't think it's possible to do this in Envoy.

The general pattern would be to configure multiple `FilterChainMatch` entries for a single listener (the first entry that matches the connection is used). With this pattern you can have have a single listener that routes TLS requests to one network filter chain and non-TLS requests routed to a different network filter chain (see the [tls inspector example](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/tls-inspector)). In that case, you could configure the non-TLS chain with an HTTP connection manager that only responded to `/healthcheck` and configure the TLS filter chain to respond to `/`.

However, I don't see any support for detection of mTLS in the tls inspector, so I don't think you can apply the same pattern for your use case.
