### ISSUE TITLE
my service failed with 503 err and msg "upstream connect error or disconnect/reset before headers"

### ISSUE THREAD

**Issue by c52662** [envoyproxy/envoy#2990]
## my service failed with 503 err and msg "upstream connect error or disconnect/reset before headers"

Hi,

I deployed istio 0.6.0 on a K8s cluster version 1.8.3, and the official sample BookInfo worked fine on the cluster. I have written my own service named "hello-test" in python and manually injected istio sidecar (enovy-debug).  

Now I'm trying to deploy two instances of "hello-test" hoping every one sends a hello message(in HTTP GET request) to each other and waits response from peer.

But I get the http 503 response and error message "upstream connect error or disconnect/reset before headers". 

BTW, they work fine if I run two instances directly in K8s cluster whitout any istio sidecar, so i guess it has nothing to do with my code or service.yaml config file 

Is this an envoy config issue? Or some other?
Can someone please take a look?

Thanks!

### Here is the yaml file content of my service before injection:
```yaml
##########################################################   
#one instance named hello-test-a   ---- service-a.yaml
##########################################################   
apiVersion: v1
kind: Service
metadata:
  name: hello-test-a
  namespace: default
  labels:
    app: hello-test-a
spec:
  selector:
    app: hello-test-a
  ports:
  - name: http
    port: 41302
    targetPort: 41302    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-test-a
        version: v1
    spec:
      nodeSelector:
        kaml: support
      containers:
      - name: hello-test-a
        image: capu-svr:5000/hello-test
        command: ["/bin/bash"]
        args:
        - -c
        - cd /home/capu/dist/hello-test; ./hello-test hello-test-a hello-test-b
        ports:
        - containerPort: 41302        
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-test-a
  annotations:
    kubernetes.io/ingress.class: "istio"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /123/req-from-hello-test-b
        backend:
          serviceName: hello-test-a
          servicePort: 41302
---

**Comment by mattklein123** [comment]
@c52662 I would recommend asking this question over at the Istio project.

**Comment by c52662** [comment]
@mattklein123 OK, Thanks!
