### ISSUE TITLE
golang filter: DecodeData called twice - last time w/ empty buffer

### ISSUE THREAD

**Issue by maguro** [envoyproxy/envoy#29901]
# golang filter: `DecodeData` called twice - last time w/ empty buffer

Disclaimer: I'm new to Envoy filter writing.

I have a Golang filter that modifies the contents the body.  My `DecodeData` method reads the bytes from the buffer, alters them such that the body is a different size, then calls `Set(modifiedBody)` on the buffer and returns `api.Continue`.   I notice two things.

- the body is not modified
- `DecodeData` is called twice, the first integer is the length of the buffer
  1)  `DecodeData(1090, false)`
  2)  `DecodeData(0, true)`

I'm not sure if this is a bug or ignorance on my part.  I'm happy to create a self contained example if what I'm reporting seems bizarre.

**Comment by zuercher** [comment]
DecodeData can definitely be called multiple times. The boolean flag (`endStream`) indicates when you're receiving the last call for a given request. I'm not certain if it always makes a final call of `DecodeData(0, true)`, but it's probably best to handle either case as the behavior may change in the future. You should also assume that you might receive multiple calls with data and `endStream` false.

`BufferInstance.Set` appears to be implemented. I tested it quickly by modifying the [go http filter example](https://www.envoyproxy.io/docs/envoy/v1.27.0/start/sandboxes/golang-http#install-sandboxes-golang-http) and it worked as expected. Note that modifying data in `DecodeData` will modify the request being sent to the upstream server (if any). If you want to modify the response to the client you need to implement `StreamEncoderFilter` and modify data in `EncodeData`, as in the [example](https://github.com/envoyproxy/envoy/blob/main/examples/golang-http/simple/filter.go#L81).

**Comment by maguro** [comment]
Thanks!  I'll take a look at my code.

**Comment by maguro** [comment]
Ok, I double checked and the upstream server is not getting the modified body.  I added a "debug" upstream filter that logs the contents of the body and it's not getting a modified body either.

**Comment by doujiang24** [comment]
body data modification should be work, please provide more information.
yep, a self-contained example would be better.
