### ISSUE TITLE
When is it planned to move the docker build container from ubuntu 20.04 to 22.04?

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#29929]

**Comment by phlax** [comment]
good question. i think out-of-the-box this would change which glibc versions we support

if that is correct then we need to think in terms of supported distros before making a decision

cc @lizan

**Comment by phlax** [comment]
@sambercovici was there a specific reason for asking ?

**Comment by sambercovici** [comment]
I am looking on compiling for arm64 and especially looking for gcc support for SIMD like SVE and SVE2 
Ubuntu 20.04 gcc does not support it. Ubuntu 22.04 does.
