### ISSUE TITLE
http3 access_log omissions

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#29930]
*Title*: *http3 access_log omissions*

*Description*:
We found when we sent 20 successfully completed test requests to an http3 endpoint, it was logging only 5-10 of them.

In a slack thread in envoy-dev, Alyssa pointed at #23648 which has a runtime flag in it; we tried changing that runtime flag to false from its default of true, and the issue was remedied.

It was not easy to reproduce this issue in other contexts - when I tried to repro in an integration test, logging was complete regardless of the flag. The current hypothesis is that the test client was terminating racily-before sending the 'ack' for the requests, so when it was sent the log entry appears, but when there was no 'ack' the log entry is (incorrectly) dropped. In the integration test, since the client was local, perhaps the race was always being won by the sending of the loopback packet.

I believe the behavior should be that, in the event of the final ack (perhaps even several acks) being dropped, the log should still record success after a short timeout.

@RyanTheOptimist @pksohn

**Comment by alyssawilk** [comment]
Paul's out today so I'll flip this false to give him time to debug/fix

**Comment by ravenblackx** [comment]
@pksohn I think this still needs attention.

**Comment by pksohn** [comment]
Yes, we'll get to this soon, thanks.

**Comment by ravenblackx** [comment]
If this is fixed the flag should probably also be flipped back?

**Comment by pksohn** [comment]
Yup, I'm planning to flip the flag back after canarying it internally.
