### ISSUE TITLE
Unable to build envoy@master with data-plane-api@master

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#2994]
It seems `@envoy_api//envoy/config/filter/http/ext_authz/v2` doesn't exist (it is moved to `v2alpha` since this commit: https://github.com/envoyproxy/data-plane-api/commit/f88047c0d470352ad1bf6a97dd64155bc65047a0).

Potential fix: https://github.com/envoyproxy/envoy/issues/2851#issuecomment-378438723 (thanks @yuval-k!).

*Repro steps*:
1. Fetch `envoyproxy/envoy@master` HEAD
2. Build it by overriding the `envoy_api` with the HEAD of `envoyproxy/data-plane-api@master`.

*Logs*:

https://circleci.com/gh/envoyproxy/envoy/37630

```
ERROR: /build/tmp/_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/external/envoy/source/extensions/filters/http/ext_authz/BUILD:13:1: no such package '@envoy_api//envoy/config/filter/http/ext_authz/v2': BUILD file not found on package path and referenced by '@envoy//source/extensions/filters/http/ext_authz:ext_authz'

ERROR: Analysis of target '@envoy//test/integration:legacy_json_integration_test_lib' failed; build aborted: no such package '@envoy_api//envoy/config/filter/http/ext_authz/v2': BUILD file not found on package path
```

**Comment by mattklein123** [comment]
@dio @saumoh @gsagula can someone please do a PR to fix master?

This pain will end once @htuch merges data-plane-api into this repo.

**Comment by saumoh** [comment]
if @dio or @gsagula are not already working on this then I can pick it up.

**Comment by dio** [comment]
I'm pushing it now 🙂. Just a quick check building in my local.
