### ISSUE TITLE
Can I build outside of/without the envoyproxy/envoy-build-centos docker container

### ISSUE THREAD

**Issue by shauneq** [envoyproxy/envoy#2995]
*Title*: *Can I build outside of/without the envoyproxy/envoy-build-centos docker container*

*Description*:
I see that run_envoy_docker.sh pulls down envoyproxy/envoy-build-centos from docker hub and build inside that container.   Is it possible to build outside of the docker container?  I realize I may be asking for a world of hurt, but our issue is that our builds must completely isolated from the internet and we build inside our own build container.   I know there are workarounds like archiving the envoyproxy/envoy-build-centos image, but before I do that, I just want to know if there is an alternative to building inside the container.  This is the first time I have seen this required for third party source.  Usually the steps are ./configure and make and your own system and tools are used.

**Comment by mattklein123** [comment]
Closing as answered.
