### ISSUE TITLE
GRPC Status Code not correctly set on AuthZ flow and different behaviour between "application/grpc" and "application/grpc-web-text+proto"

### ISSUE THREAD

**Issue by timo-affinityclick** [envoyproxy/envoy#29960]
*Title*: GRPC Status Code not correctly set on AuthZ flow and different behaviour between "application/grpc" and "application/grpc-web-text+proto"

*Description*:

We use GRPC with AuthZ and also have a GRPC-Web filter active.

Our Golang code for the AuthZ filter is returning a denied response when the version (our app version, determined through a header) the client is using is outdated.

```
deprecatedVersionResponse = &auth.CheckResponse{
		Status: &status.Status{Code: int32(code.Code_FAILED_PRECONDITION), Message: errVersionNotSupported},
		HttpResponse: &auth.CheckResponse_DeniedResponse{
			DeniedResponse: &auth.DeniedHttpResponse{
				Status: &envoy_type.HttpStatus{
					Code: envoy_type.StatusCode_PreconditionFailed,
				},
			},
		},
	}
```

When a curl client hits that endpoint with "application/grpc" we see:

```
< HTTP/2 200
< grpc-status: 2
< content-type: application/grpc
< date: Wed, 04 Oct 2023 19:13:05 GMT
< server: envoy
```

**Note the grpc-status is changed from 9 to 2 and there is no grpc-message.**

When a curl client hits the endpoint with "application/grpc-web-text+proto" we see:

```
< HTTP/2 200
< grpc-status: 9
< grpc-message: SOME_MESSAGE
< status: 412
< content-type: application/grpc-web-text+proto
< date: Wed, 04 Oct 2023 19:14:15 GMT
< server: envoy
```

We would expect the grpc-status to match in both cases and for both cases also to have the grpc-message exposed.

I have tested this on versions 1.16.1 and 1.27.0

**Comment by zuercher** [comment]
Since the grpc-web filter seems to be a straightforward no-op when the content-type is application/grpc I'd say this might have something to do with the ext_authz filter (or possibly your config or auth service).

cd @esmet @tyxia @ggreenway

**Comment by ggreenway** [comment]
I believe envoy tries to do some rewriting of responses if they are of the grpc content-type, and that may be what's causing this difference. grpc-web content-type would not get this rewriting.
