### ISSUE TITLE
itoa within Envoy configuration

### ISSUE THREAD

**Issue by epb-644** [envoyproxy/envoy#30041]
*Title*: *Is there an integer-to-string (itoa) function available within Envoy configuration?*

*Description*:
> We are using the [proxy_protocol.v3.ProxyProtocol](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol) listener filter to store the header's TLV in dynamic metadata. This worked great for us so far, and the values just happened to be encoded as ASCII so they were readable in our logs and configuration.
> Now we have a usecase to receive and parse a header that is an unsigned 32 bit integer. Is there a way within Envoy configuration to convert this dynamic metadata value to a human-readable string? 
> Basically, we need an `itoa` function within Envoy configuration.

[optional *Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol

**Comment by kyessenov** [comment]
I don't think there's a general way to convert binary data in Envoy logs. I'd suggest that the data is sanitized as early as possible, that means the producer of the dynamic metadata should interpret the binary data as integers at the production site. Perhaps, another field in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto#extensions-filters-listener-proxy-protocol-v3-proxyprotocol-keyvaluepair that indicates the type of the binary data? Strings in protobuf must be UTF-8 so I suspect it's already broken for the raw binary data unless it's using `bytes` or Base64 encoding.
