### ISSUE TITLE
[Overload] Active requests resource monitor

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#30046]
As part of https://github.com/envoyproxy/envoy/issues/12419, I would like to introduce resource monitor for global count of active requests in overload manager.
The rationale is described in https://github.com/envoyproxy/envoy/issues/12419.
Active requests accounting logic lives in codec clients, so overload manager dependency will be propagated at this level.
This will be a proactive resource monitor (similar to [active downstream connections monitor](https://github.com/envoyproxy/envoy/pull/23361)), which means resource pressure will be checked inline instead of being evaluated periodically in overload manager.
When threshold is saturated Envoy will enter overloaded state and invoke a fixed overload action, it will stop accepting new requests. Upon completion of an active request, resource usage for global counter will be decremented in overload manager, which in turn will let in new subsequent request.
Tagging  @KBaichoo @alyssawilk @yanavlasov here to validate high level design proposal.

**Comment by alyssawilk** [comment]
SGTM
