### ISSUE TITLE
TSAN error triggered by std::string race in FakeRawConnection::write in builds from Centos docker container

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#3005]
This is the same as #944. This is still happening in builds in the centos docker container.

It appears this is an issue with the centos devtoolset toolchain.

See:
https://bugzilla.redhat.com/show_bug.cgi?id=1546704
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by ggreenway** [comment]
I've found no way to fix this without recompiling the standard library. Closing.

**Comment by ggreenway** [comment]
This is supposed to be fixed in CentOS 8, when it is released.

**Comment by mattklein123** [comment]
@ggreenway if possible can you specify how you fixed it in case anyone else wants to also fix it?

**Comment by ggreenway** [comment]
I stopped building on CentOS entirely.
