### ISSUE TITLE
Throws 'grpc-status', '12' when using domain name with service name it works

### ISSUE THREAD

**Issue by Prasoon6667** [envoyproxy/envoy#30070]
*Title*: *Throws 'grpc-status', '12' when using domain name*

*Description*:
> I have front running outside Kubernetes cluster, I am configuring opentelemetry tracing to it. Opentelemetry collector is running inside the k8s cluster. When I give domain name log shows 'grpc-status', '12' but with the same config when I run the envoy inside k8s cluster and give local service name and port it is sending spans to opentelemetry collector. 

envoy version: envoyproxy/envoy:v1.27.0    

*Config*:
> cluster config:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: opentelemetry_collector
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: opentelemetry_collector
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ${OTEL_ADDRESS}
                    port_value: ${OTEL_PORT}

lds config:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: auth_proxy_listener_http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: ${HTTP_PORT}
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              tracing:
                provider:
                  name: envoy.tracers.opentelemetry
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                    grpc_service:
                      envoy_grpc:
                        cluster_name: opentelemetry_collector
                      timeout: 1s
                    service_name: front-envoy
              route_config:
                name: local_route
                virtual_hosts:
                  - name: upstream
                    domains:
                      - "*"
                    routes:
                    -----
                    
 ingress:-
 
 apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: otel-test
  namespace: observability
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: otel-test-opentelemetry-collector
          port: 4317
          protocol: h2c
  virtualhost:
    fqdn: otel-test.com
    tls:
      secretName: ingress-default-cert

*Logs*:
>opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][67][debug][connection] [source/common/network/connection_impl.cc:948] [C5] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][pool] [source/common/conn_pool/conn_pool_base.cc:291] trying to create new connection
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][pool] [source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][67][debug][connection] [source/common/network/connection_impl.cc:967] [C5] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][68][debug][connection] [./source/common/network/connection_impl.h:98] [C1] current connecting state: true
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.425][73][debug][router] [source/common/router/router.cc:690] [Tags: "ConnectionId":"0","StreamId":"14483004215633223044"] router decoding headers:
opentelemetry-front-envoy-1  | ':method', 'POST'
opentelemetry-front-envoy-1  | ':path', '/opentelemetry.proto.collector.trace.v1.TraceService/Export'
opentelemetry-front-envoy-1  | ':authority', 'opentelemetry_collector'
opentelemetry-front-envoy-1  | ':scheme', 'http'
opentelemetry-front-envoy-1  | 'te', 'trailers'
opentelemetry-front-envoy-1  | 'content-type', 'application/grpc'
opentelemetry-front-envoy-1  | 'x-envoy-internal', 'true'
opentelemetry-front-envoy-1  | 'x-forwarded-for', '172.31.0.2'
opentelemetry-front-envoy-1  |
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][79][debug][client] [source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"2"] connecting
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][68][debug][client] [source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"1"] connecting
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][68][debug][connection] [source/common/network/connection_impl.cc:948] [C1] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][79][debug][connection] [source/common/network/connection_impl.cc:948] [C2] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][68][debug][connection] [source/common/network/connection_impl.cc:967] [C1] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][pool] [source/common/http/conn_pool_base.cc:78] queueing stream due to no available connections (ready=0 busy=0 connecting=0)
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][pool] [source/common/conn_pool/conn_pool_base.cc:291] trying to create new connection
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][pool] [source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][http2] [source/common/http/http2/codec_impl.cc:1605] [Tags: "ConnectionId":"6"] updating connection-level initial window size to 268435456
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][connection] [./source/common/network/connection_impl.h:98] [C6] current connecting state: true
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][client] [source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"6"] connecting
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][connection] [source/common/network/connection_impl.cc:948] [C6] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][http2] [source/common/http/http2/codec_impl.cc:1605] [Tags: "ConnectionId":"7"] updating connection-level initial window size to 268435456
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][connection] [./source/common/network/connection_impl.h:98] [C7] current connecting state: true
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][client] [source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"7"] connecting
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][connection] [source/common/network/connection_impl.cc:948] [C7] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][77][debug][connection] [source/common/network/connection_impl.cc:967] [C6] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][79][debug][connection] [source/common/network/connection_impl.cc:967] [C2] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.426][73][debug][connection] [source/common/network/connection_impl.cc:967] [C7] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.433][74][debug][http2] [source/common/http/http2/codec_impl.cc:1605] [Tags: "ConnectionId":"8"] updating connection-level initial window size to 268435456
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.433][74][debug][connection] [./source/common/network/connection_impl.h:98] [C8] current connecting state: true
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.433][74][debug][client] [source/common/http/codec_client.cc:57] [Tags: "ConnectionId":"8"] connecting
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.433][74][debug][connection] [source/common/network/connection_impl.cc:948] [C8] connecting to 10.222.17.180:80
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.433][74][debug][connection] [source/common/network/connection_impl.cc:967] [C8] connection in progress
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.483][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:155] dns resolution without records for manhattan-api.wms-uat.devops.ohlogistics.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.483][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:155] dns resolution without records for shopify-api.wms-uat.devops.ohlogistics.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.484][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:278] dns resolution for shopify-api.wms-uat.devops.ohlogistics.com completed with status 0
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.484][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:112] async DNS resolution complete for shopify-api.wms-uat.devops.ohlogistics.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.484][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:163] DNS refresh rate reset for shopify-api.wms-uat.devops.ohlogistics.com, refresh rate 5000 ms
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.537][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:155] dns resolution without records for woocommerce-api.wms-core-pg.npaz.ohl.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.538][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:278] dns resolution for woocommerce-api.wms-core-pg.npaz.ohl.com completed with status 0
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.538][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:112] async DNS resolution complete for woocommerce-api.wms-core-pg.npaz.ohl.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.538][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:163] DNS refresh rate reset for woocommerce-api.wms-core-pg.npaz.ohl.com, refresh rate 5000 ms
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.702][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:155] dns resolution without records for otel-test.wms-infra-blue-eus.npaz.ohl.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.704][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:278] dns resolution for otel-test.wms-infra-blue-eus.npaz.ohl.com completed with status 0
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.704][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:112] async DNS resolution complete for otel-test.wms-infra-blue-eus.npaz.ohl.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.704][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:163] DNS refresh rate reset for otel-test.wms-infra-blue-eus.npaz.ohl.com, refresh rate 5000 ms
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.803][60][debug][connection] [source/common/network/connection_impl.cc:695] [C0] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.803][60][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"0"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.804][60][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"0"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.804][60][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"0"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.804][60][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"5115567610999886236"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.822][60][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:278] dns resolution for manhattan-api.wms-uat.devops.ohlogistics.com completed with status 0
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.823][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:112] async DNS resolution complete for manhattan-api.wms-uat.devops.ohlogistics.com
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.823][60][debug][upstream] [source/extensions/clusters/logical_dns/logical_dns_cluster.cc:163] DNS refresh rate reset for manhattan-api.wms-uat.devops.ohlogistics.com, refresh rate 5000 ms
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][71][debug][connection] [source/common/network/connection_impl.cc:695] [C3] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][79][debug][connection] [source/common/network/connection_impl.cc:695] [C2] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][79][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"2"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][71][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"3"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][79][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"2"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][79][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"2"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.846][71][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"3"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][71][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"3"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][71][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"10482387932740156988"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][79][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"9221043107495459294"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][67][debug][connection] [source/common/network/connection_impl.cc:695] [C5] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][67][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"5"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][73][debug][connection] [source/common/network/connection_impl.cc:695] [C7] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][73][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"7"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][67][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"5"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][67][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"5"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][67][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"13908334028172398003"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][73][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"7"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][73][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"7"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.847][73][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"14483004215633223044"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][77][debug][connection] [source/common/network/connection_impl.cc:695] [C6] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][68][debug][connection] [source/common/network/connection_impl.cc:695] [C1] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][77][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"6"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][68][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"1"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][81][debug][connection] [source/common/network/connection_impl.cc:695] [C4] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][81][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"4"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][77][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"6"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][68][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"1"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][68][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"1"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][81][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"4"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][81][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"4"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][77][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"6"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][77][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"10154506552088034706"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][68][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"223119805621023921"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.851][81][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"10544147708367589109"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.870][74][debug][connection] [source/common/network/connection_impl.cc:695] [C8] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.870][74][debug][client] [source/common/http/codec_client.cc:88] [Tags: "ConnectionId":"8"] connected
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.870][74][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [Tags: "ConnectionId":"8"] attaching to next stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.870][74][debug][pool] [source/common/conn_pool/conn_pool_base.cc:182] [Tags: "ConnectionId":"8"] creating stream
opentelemetry-front-envoy-1  | [2023-10-10 13:10:24.870][74][debug][router] [source/common/router/upstream_request.cc:562] [Tags: "ConnectionId":"0","StreamId":"1575837063188313264"] pool ready
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][client] [source/common/http/codec_client.cc:128] [Tags: "ConnectionId":"0"] response complete
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][client] [source/common/http/codec_client.cc:136] [Tags: "ConnectionId":"0"] waiting for encode to complete
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][router] [source/common/router/router.cc:1437] [Tags: "ConnectionId":"0","StreamId":"5115567610999886236"] upstream headers complete: end_stream=true
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][router] [source/common/router/upstream_request.cc:469] [Tags: "ConnectionId":"0","StreamId":"5115567610999886236"] resetting pool request
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][client] [source/common/http/codec_client.cc:158] [Tags: "ConnectionId":"0"] request reset
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][pool] [source/common/conn_pool/conn_pool_base.cc:215] [Tags: "ConnectionId":"0"] destroying stream: 0 remaining
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][http] [source/common/http/async_client_impl.cc:123] async http request response headers (end_stream=true):
opentelemetry-front-envoy-1  | ':status', '200'
opentelemetry-front-envoy-1  | 'content-type', 'application/grpc'
opentelemetry-front-envoy-1  | 'grpc-status', '12'
opentelemetry-front-envoy-1  | 'date', 'Tue, 10 Oct 2023 13:10:26 GMT'
opentelemetry-front-envoy-1  | 'server', 'envoy'
opentelemetry-front-envoy-1  |
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][http2] [source/common/http/http2/codec_impl.cc:1350] [Tags: "ConnectionId":"0"] stream 1 closed: 0
opentelemetry-front-envoy-1  | [2023-10-10 13:10:25.237][60][debug][http2] [source/common/http/http2/codec_impl.cc:1414] [Tags: "ConnectionId":"0"] Recouping 0 bytes of flow control window for stream 1.

**Comment by kyessenov** [comment]
Is there something different in authority header maybe?
