### ISSUE TITLE
v1.26.5 is not tagged

### ISSUE THREAD

**Issue by masa213f** [envoyproxy/envoy#30080]
Hi,

It looks like the releaase PR for the v1.26.5(https://github.com/envoyproxy/envoy/pull/29695) has been merged,
but the `v1.26.5` tag has not been tagged yet. (Also the Releases is not created yet.)
Is the content of envoy v1.26.5 fixed at [`d3663038baad00278ca6d2663f7859a913b96d73`](https://github.com/envoyproxy/envoy/commit/d3663038baad00278ca6d2663f7859a913b96d73)?

Regards,

**Comment by phlax** [comment]
yet - we had a couple of hitches with release, resolving those now - 1.26 should be available fairly soon

**Comment by phlax** [comment]
re fix - the release/v1.26 branch has the patches already

**Comment by masa213f** [comment]
@phlax 
Thank you! I have confirmed that v1.26.5 has been released.
