### ISSUE TITLE
Detecting HTTP status (or HTTP response timeout) in `encodeTrailers` handler

### ISSUE THREAD

**Issue by crazyboycjr** [envoyproxy/envoy#30114]
*Title*: *Detecting HTTP status (or HTTP response timeout) in `encodeTrailers` handler*

*Description*:
Hi folks, I wonder if there's a reliable way to simply detect HTTP response timeout in `encodeTrailers` handler function of HTTP filters.

The challenge here is that we may easily check timeout by examining http status from `ResponseHeaderMap` (the input argument for `encodeHeaders`), but in `ResponseTrailerMap` (the input argument for `encodeTrailers`), it is not the case. One idea is to use a `has_timeout` flag to indicate if a previous request was timed out. This flag is set in `encodeHeaders` and read in `encodeTrailers`. But there could be multiple responses, and a later response could overwrite the `has_timeout` flag before the response comes in `encodeTrailers`.

Using stream local data (i.e., `encoder_callbacks_->streamInfo().filterState()->getDataMutable("key_name")`) leads to hashmap lookup by string key, which is not very ideal.

I also considered `encoder_callbacks_->streamInfo().setResponseFlag()` and then query it in `encodeTrailers`. But I wasn't able to find out if the response flag will be override by envoy itself before it gets to `encodeTrailers` or even be overwritten by a later response header of the same stream (this is similar if using stream local data) before the `encodeTrailers` is called.

[optional *Relevant Links*:]
Context, I'm implementing a custom HTTP filter, which parses some specific tag in the HTTP response. The tag unfortunately could be in either header or trailers. If the response was considered timeout, any subsequent processing for this tag should be skipped.

**Comment by crazyboycjr** [comment]
> I also considered encoder_callbacks_->streamInfo().setResponseFlag() and then query it in encodeTrailers. But I wasn't able to find out if the response flag will be override by envoy itself before it gets to encodeTrailers or even be overwritten by a later response header of the same stream (this is similar if using stream local data) before the encodeTrailers is called.

I just recently realized that a `streamInfo` is per-request or per-response metadata (Stream in HTTP/2 context). There's no way for it to be override by another response. The `UpstreamRequestTimeout` will be set in the StreamInfo's response flag if the a timer triggers. So the solution should be simple. Just to check `encoder_callbacks_->streamInfo().hasResponseFlag()` would be sufficient.

Feel free to close the issue if my understanding is correct.

**Comment by kyessenov** [comment]
I think this is right - a flag should be set to indicate an error and then the filter should receive the callback with the stream info that has it. This needs to be validated, as the ordering of these things is not always consistent.
