### ISSUE TITLE
Supports setting the `:scheme` header of upstream requests based on upstream crypto

### ISSUE THREAD

**Issue by johnlanni** [envoyproxy/envoy#30134]
*Title*: *Supports setting the scheme header of upstream requests based on upstream encryption*

*Description*:

My scenario is that Envoy receives gRPCs(encrypted) requests and proxies gRPC (not encrypted) request to a .NET service. The .NET gRPC framework checks the :scheme header, if the request is not encrypted, but the :scheme is https, the request will fail.

I solved the problem by setting the HCM option scheme_header_transformation to http, but this option has a side effect of setting the XFP header to http, which makes it impossible to determine the Envoy downstream protocol through the XFP header.

As @alyssawilk  commented [here](https://github.com/envoyproxy/envoy/issues/14587#issuecomment-1758483713), we may need to extend the cluster configuration options to set the scheme based on upstream crypto instead of defaulting to XFP.

**Comment by johnlanni** [comment]
I'm interested in implementing this feature if you guys think it's needed.
cc @alyssawilk

**Comment by alyssawilk** [comment]
I don't think it's needed but I think it's completely fine to add.  cc @yanavlasov because it's sorta header sanitization
