### ISSUE TITLE
Windows CI is OOMing

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#30146]
```
LINK : fatal error LNK1102: out of memory
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=152223&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=12401

**Comment by phlax** [comment]
this is happening fairly frequently now

https://github.com/envoyproxy/envoy/pull/30180

cc @akshaysngupta

**Comment by phlax** [comment]
tried to post a link but copying links from azp now appears to be kaput (at lest for me/my browser)

**Comment by phlax** [comment]
this is now a huge problem - its failing presubmit *a lot*

**Comment by phlax** [comment]
worth flagging we are seeing quite a few (possibly) related errors in other platforms

this one is on mac

```console

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/private/var/tmp/_bazel_runner/3d1a7f52fd47fc9a8db71770aacd13e5/server/jvm.out')

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=153654&view=logs&j=fa3d3e18-6969-5713-c3e7-3581195704fd&t=fff59c4a-2c2a-5a2a-459d-115161029c78

ive seen an uptick of similar on linux recently i believe

bazel abruptly going away *can* be an OOM symptom - so this is not conclusively a more general problem, and certainly a lot rarer - either way it would be good to rule out our CI spinning out in some way

**Comment by akshaysngupta** [comment]
For other OSes (mac), following seem relevant:
* https://github.com/bazelbuild/bazel/issues/3020 - suggested to upper bound concurrent job count
* https://github.com/buchgr/bazel-remote/issues/664 - suggested to increase limit on open files using ulimit

**Comment by phlax** [comment]
the latter _might_ be specific to bazel-remote which is an implementation of bazel cache (we use it for arm)

**Comment by phlax** [comment]
perhaps not tho

**Comment by phlax** [comment]
but is linux specific

we dump jvm.out (not usually v helpful tho) in the linux ci - probably we can dump dmesg or similar to get a handle on what is going on (assuming the vm hasnt frozen)

**Comment by akshaysngupta** [comment]
also, possible to request a larger agent sku ? since many OSes might facing memory crunch

**Comment by phlax** [comment]
its pretty infrequent everywhere else

and for the linux machines are all self-hosted already - they are sizable machines

on the linux side there is some difference between arm and x86 wrt RBE/local running - arm run local is much larger but ironically is more susceptible to this type of problem

the jvm.out issue is a client issue - im not clear on the win side whether its a client or RBE worker problem

**Comment by phlax** [comment]
@akshaysngupta we have our answer:

```console
INFO: From Compiling src/core/ext/transport/binder/client/channel_create_impl.cc:
   Creating library bazel-out\x64_windows-opt\bin\source\exe\envoy-static.lib and object bazel-out\x64_windows-opt\bin\source\exe\envoy-static.exp
LINK : fatal error LNK1102: out of memory
ERROR: C:/source/source/exe/BUILD:25:16: Linking source/exe/envoy-static.exe failed: (Exit 1102): link.exe failed: error executing command (from target //source/exe:envoy-static) 
  cd /d C:/build/tmp/execroot/envoy

```

on a boosted vm 8(

seems @yanavlasov was correct its OOMing in the bazel worker - not sure what we can do about that
