### ISSUE TITLE
StreamInfo - Need time_to_connect stat for TCP proxy

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#30148]
*Title*: StreamInfo - need time_to_connect stat for TCP Proxy

*Description*:
Short lived TCP Proxy connections sometimes take a while to complete in prod. We have no way to know if it was due to a long time to connect or if the upstream application server was at fault. It would be good to have a stat that measures the time it took to connect to the upstream endpoint. Custom access loggers can use this info for logging. We could also plug this into the existing access logs if we wish to.

cc @krajshiva @jmarantz

**Comment by jmarantz** [comment]
@KBaichoo would you have time to look at adding this?
