### ISSUE TITLE
Refresh compilation databases failing in devcontainer environment (Apple M1)

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#30152]
*Title*: Refresh compilation databases failing in devcontainer environment

*Description*:
Failing to generate compilation database in devcontainer via vscode.
```
tools/vscode/refresh_compdb.sh

ERROR: /build/.cache/bazel/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: in cc_toolchain_suite rule @envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain: cc_toolchain_suite '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' does not contain a toolchain for cpu 'aarch64'
```

Spec:
- Apple M1 Max (macOS Sonoma)

*Repro steps*:
1. Following devcontainer setup: https://github.com/envoyproxy/envoy/tree/main/.devcontainer#how-to-use

**Comment by mou-ren** [comment]
I meet this issue too, how to fix it

**Comment by jason9015** [comment]
I meet this issue too, how to fix it

**Comment by lusains** [comment]
I meet this issue too, how to fix it
