### ISSUE TITLE
Exclusion duplicates from clusters endpoints for DNS resolution optimization

### ISSUE THREAD

**Issue by stais** [envoyproxy/envoy#30189]
*Title*: *Exclusion duplicates from clusters endpoints for DNS resolution optimization*

*Description*:
It seems Envoy gets DNS resolution for every endpoint from available clusters in configuration. But this is not efficient in cases where endpoints are the same in multiple clusters. For example, I have a configuration of 10 clusters where endpoint is exact the same in all of them, but only port changes. In this case, Envoy will make 10 exactly same DNS queries for that endpoint, while it could do only one.

I am using Envoy 1.26.2 and all clusters have STRICT_DNS configured.

**Comment by wbpcode** [comment]
Yeah, because in most cases, we expect the different clusters have different endpoint. Not sure if this is a general scenario, if it is, I think we can try to do some optimizations.

**Comment by stais** [comment]
I have not check the code, but I guess that Envoy currently takes the list of destinations from the clusters and parses them. It should be a nice optimization to remove same entries and keep only the unique ones.

**Comment by nirvanagit** [comment]
Are we planning to do any optimizations?
