### ISSUE TITLE
Possible optimization in AsyncClientManager with message comparison

### ISSUE THREAD

**Issue by DiazAlan** [envoyproxy/envoy#30196]
***Description***:
Currently we have a few filters, Rate Limit, Ext_proc, Ext_authz that rely on the async client manager. When these filters are created on a request, the filter will send the GrpcService proto to the AsyncClientManager to get a cached client from an internal map. Previously, this was hashing the entire proto on every single request when trying to find the client. This was fixed in a previous PR [29199](https://github.com/envoyproxy/envoy/pull/29199).

So for us, one of our projects was showing Ext_authz using about ~4.2% of our cpu. After the PR, this dropped the usage down to about 2% which is significant improvement. But we still see a bulk of the filter creation time in the CPU is being taken up by comparing the message itself within the find. 

I wanted to throw this out to the open source community to see if we can come up with a good idea of how we can possibly save some of this time since I'm sure many folks can be invested in the optimization of these filters.

***Context***:
The previously mentioned PR that had the first fix stored the config within a wrapper object found here. [GrpcServiceConfigWithHashKey](https://github.com/envoyproxy/envoy/blob/6ef1bb476da8d050347b462b2d8efa1cddeb420f/envoy/grpc/async_client_manager.h#L35) This object will pre compute the hash on creation so that we don't need to hash the config on each request. But while it skips the hash, it still uses the original config for the comparison.

***Possible Solution***:
A possible idea I had for this would be to maybe have some sort of singleton class that has some sort of config -> unique identifier map which the GrpcServiceConfigWithHashKey object will call on creation to get a smaller unique ID associated to that config. And we use that unique identifier internally instead of the actual config itself. Maybe using the [ObjectSharedPool ](https://github.com/envoyproxy/envoy/blob/main/source/common/shared_pool/shared_pool.h) for this? What do people think? A concern I have for this idea would be how to prune unique IDs that are not being used to avoid creating an ever growing list of IDs.

**Comment by kyessenov** [comment]
It sounds like you're looking for perfect hashing with no collisions. Maybe using cryptographic hash is a simpler solution here?

CC @tyxia
