### ISSUE TITLE
What is the proper way to send additional data to upstream from network filter

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#30236]
*Title*: *How to send some additional data from Network Filter*

*Description*:
I want to send some additional data from function like `OnData`  to upstream which has not come from downstream. How can I do that? I have tried using `ReadFilterCallbacks::injectReadDataToFilterChain`, but it doesn't appear to send any data.

**Comment by kyessenov** [comment]
CC @yskopets

**Comment by psramkumar** [comment]
you can consider adding LUA script to add more header  as below
`
http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inlineCode: >
                        -- LUA Script to add required HEADERS extracted from mode data
                        function envoy_on_request(request_handle)
                          headers = request_handle:headers()
                          headers:add("newKey", "newValue")
                        end
`

**Comment by cpakulski** [comment]
This code definitely works in postgres:
https://github.com/envoyproxy/envoy/blob/main/contrib/postgres_proxy/filters/network/source/postgres_filter.cc#L243

It is used to send data generated by postgres filter, not received from downstream. Be careful with ownership of the buffer (create your own buffer).
