### ISSUE TITLE
Propagate route metadata in ext_authz filter

### ISSUE THREAD

**Issue by ikimonogakari** [envoyproxy/envoy#30252]
Propagate [route metadata](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L294) in ext_authz filter through [`metadata_context_namespaces`
](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L105)

*Description*:
We want to propagate some per-route config through ext_authz http filter, to the external authentication service.

I know ext_authz has [`context_extension`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L377) in `CheckSettings` in the `ExtAuthzPerRoute` config. However, `context_extension` only supports string value, but no proto or struct. It is hard to inject structured data there.

My proposal is to have ext_authz http filter also checks the route's metatdata for `metadata_context_namespaces` in [Filter::initiateCall](https://github.com/envoyproxy/envoy/blob/379a2c4ba3bd54f83641bc85d4f3eb1b944d8b54/source/extensions/filters/http/ext_authz/ext_authz.cc#L53). If the namespace does exist, it then sends the matched data to the external service as well.

I can implement this feature and necessary tests on my own. Just want to learn if there is any design decision was made not to do so initially, before I start the work.

Another discussion about the implementation is that what should the correct priority of different metadata be? Currently, `request_metadata` has higher priority than `connection metadata`. What priority should the `route metadata` has? I suppose it should have the lowest?

**Comment by kyessenov** [comment]
I think it's fair to send route metadata - but it's very different from the request metadata so it's probably not a good idea to mix them. 

CC @tyxia @ggreenway

**Comment by ikimonogakari** [comment]
Do you mean not to use `metadata_context_namespaces` for the purpose of route metadata?

It is simple to have different filed for namespaces for route metadata in ext_authz's config. However, in ext_authz's RPC definition, they are still mixed with namespaces with other metadata (request and connection) in [the `metadata_context` field of `CheckRequest.AttributeContext`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/auth/v3/attribute_context.proto#L184).

Are you saying we want route metadata be sent in a different field in `CheckRequest.AttributeContext`?

**Comment by kyessenov** [comment]
> Are you saying we want route metadata to be sent in a different field in `CheckRequest.AttributeContext`?

Yes, I meant to say that route metadata should be a separate field in both CheckRequest and the ext_authz config.

**Comment by tyxia** [comment]
When connection metadata was added in https://github.com/envoyproxy/envoy/pull/27612, there was the discussion with @ggreenway  whether new namespace for connection is needed. The rational of not having new field is : Internally, it is more about implementation details, externally to ext_authz server it is just look as filter metadata, route's namespace `envoy.filters.http.router`

@kyessenov  if I miss any significant difference for route case here that should alter a new field?

**Comment by kyessenov** [comment]
@tyxia This is asking to propagate xDS metadata, not the stream dynamic metadata, so it is qualitatively different. We usually don't mix them together in Envoy AFAIK.

**Comment by tyxia** [comment]
Sure, they are from different source, but down to the underlying proto definition, they are just same?  `filter_metadata` and `typed_filter_metadata`.

I think I am totally fine we don't want to mix them, i am more curious about the downside of mixing them if they are same proto.

**Comment by ikimonogakari** [comment]
I think the issue is how to deal the conflict value of the same namespace under request, connection, and route metadata.

I guess what kyessenov means is that, route metadata is compiled into the config, either static or dynamic from xDS. It may not consider the colision with request or connetion metadata which the extensions generated. And since the source and purpose are different, both of them can be useful.

Unlike request and connection, they all generated during the request processing, if the namespace colloids, they most likely have similar value for the same purpose, and request metadata is generated more recently, which can be more important.

Correct me if I am wrong. I will implement this feature by completely seperating request/connection metadata against route metadata.

**Comment by tyxia** [comment]
I think collision probably is not the concern as route metadata is not already mixed in request/connection metadata in Envoy (as Kuat mentioned)and will be under its own `envoy.filters.http.router` namespace to ext_authz server.

But I don't have object to separate them.  cc @ggreenway who is also the code owner and has reviewed PR connection metadata
