### ISSUE TITLE
Export tcmalloc pageheap metrics as stats

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#30317]
*Title*: *Export pageheap related metrics as stats*

*Description*: Currently [pageheap related metrics](https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/memory.proto#admin-v3-memory) are only accessible via admin console. Exporting such metrics would allow users to gain insights into their proxies memory profile, one such use case is for example to understand if  "envoy.reloadable_features.count_unused_mapped_pages_as_free" runtime key should be off or on for memory accounting in [fixed_heap_resource_monitor](https://github.com/envoyproxy/envoy/blob/f665e30845d675a218b4f1019d965029734c9fda/source/extensions/resource_monitors/fixed_heap/fixed_heap_monitor.cc#L31) to better protect against memory related resource attacks.

**Comment by KBaichoo** [comment]
That's a great idea! See also https://github.com/envoyproxy/envoy/issues/30280#issuecomment-1770962734.
