### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':

### ISSUE THREAD

**Issue by merkey** [envoyproxy/envoy#30311]
*Title*: build envoy v1.26.4 failed due to fetch repo:bazel_gazelle_go_repository_tools failed.

*Description*:
when i build envoy v1.26.4 on ubuntu 22.04 LTS via command: bazel build envoy -c opt
follow error appear :

~/workspace/envoy$ bazel build envoy -c opt
Starting local Bazel server and connecting to it...
INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  /home/minlin/workspace/envoy/WORKSPACE:25:25: in <toplevel>
  /home/minlin/workspace/envoy/bazel/dependency_imports.bzl:31:25: in envoy_dependency_imports
  /home/minlin/.cache/bazel/_bazel_minlin/67f9c548817b7d5080b6392a559fb5d1/external/bazel_gazelle/deps.bzl:75:24: in gazelle_dependencies
Repository rule go_repository_tools defined at:
  /home/minlin/.cache/bazel/_bazel_minlin/67f9c548817b7d5080b6392a559fb5d1/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
**ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':**
   Traceback (most recent call last):
        File "/home/minlin/.cache/bazel/_bazel_minlin/67f9c548817b7d5080b6392a559fb5d1/external/bazel_gazelle/internal/go_repository_tools.bzl", line 85, column 17, in _go_repository_tools_impl
                fail("list_repository_tools_srcs: " + result.stderr)
Error in fail: list_repository_tools_srcs: fork/exec /tmp/go-build717123858/b001/exe/list_repository_tools_srcs: permission denied
ERROR: /home/minlin/workspace/envoy/WORKSPACE:25:25: fetching go_repository_tools rule //external:bazel_gazelle_go_repository_tools: Traceback (most recent call last):
        File "/home/minlin/.cache/bazel/_bazel_minlin/67f9c548817b7d5080b6392a559fb5d1/external/bazel_gazelle/internal/go_repository_tools.bzl", line 85, column 17, in _go_repository_tools_impl
                fail("list_repository_tools_srcs: " + result.stderr)
Error in fail: list_repository_tools_srcs: fork/exec /tmp/go-build717123858/b001/exe/list_repository_tools_srcs: permission denied
ERROR: /home/minlin/.cache/bazel/_bazel_minlin/67f9c548817b7d5080b6392a559fb5d1/external/com_envoyproxy_protoc_gen_validate/BUILD.bazel:18:11: no such package '@org_golang_google_protobuf//types/pluginpb': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': list_repository_tools_srcs: fork/exec /tmp/go-build717123858/b001/exe/list_repository_tools_srcs: permission denied
 and referenced by '@com_envoyproxy_protoc_gen_validate//:protoc-gen-validate_lib'
ERROR: Analysis of target '//:envoy' failed; build aborted:
INFO: Elapsed time: 27.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (849 packages loaded, 34559 targets configured)
    Fetching repository @org_golang_google_protobuf; Restarting.
    Fetching repository @com_github_lyft_protoc_gen_star; Restarting.
    Fetching repository @bazel_gazelle_go_repository_config; Restarting.

*Repro steps*:
1.git clone -b v1.26.4 git@github.com:envoyproxy/envoy.git
2.entry envoy root path and run bazel build envoy -c opt

anyone konws how to fix it? thanks.

**Comment by kyessenov** [comment]
Not sure I can see the root cause. Try passing `--verbose_failures` to bazel. It could be some temporary server failure.

**Comment by merkey** [comment]
> Not sure I can see the root cause. Try passing `--verbose_failures` to bazel. It could be some temporary server failure.

no more help info print after add --verbose_failures, seems some package was missing when preparing the env, this issue appears immediately after  extract go_toolchains

**Comment by merkey** [comment]
root cause is identified, the /tmp folder is mount with noexec options and make go can't have exec permission by default in /tmp.

WA: 
remount /tmp with exec: `mount -o remount,exec /tmp`
