### ISSUE TITLE
Implement a code freeze prior to release

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#30327]
In the last couple of days prior to releasing 1.28.0 we landed various PRs that created (mostly test) issues

I think we should consider a code freeze - perhaps something short like 3 days in which _only_ release-critical fixes get landed

**Comment by phlax** [comment]
> Would it make sense or be viable to cut a branch something like v1.28.proposed or proposed1.28 three days

that sounds like a great plan tbh

i think it would allow dev to continue and would mean things that are proposed for inclusion can get run on main first

probably we could figure some strategy that made release a bit less painful - ie by running versioned ci beforehand

**Comment by kyessenov** [comment]
Yes, "freeze" doesn't send the right signal, branching early and letting it bake a little works fine in Istio, for example.

**Comment by alyssawilk** [comment]
yeah I like this better as it doesn't negatively impact developer velocity the way a freeze does.
