### ISSUE TITLE
access-log - add state to %RESPONSE_FLAGS% / %RESPONSE_FLAGS_LONG% to indicate request was reset by downstream

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#30323]
*access-log - support logging downstream request reset for http2*

*Description*:
In http/1.1 downstream "reset" request by closing the connection. This is logged in access-log via %RESPONSE_FLAGS% / %RESPONSE_FLAGS_LONG% - DownstreamConnectionTermination / DC

**In http/2 downstream reset of the stream is handled, silently. We should have a new state logged on %RESPONSE_FLAGS% / %RESPONSE_FLAGS_LONG% - DownstreamRequestReset / DRR**

see: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage.html %RESPONSE_FLAGS% / %RESPONSE_FLAGS_LONG%

**Comment by kyessenov** [comment]
Sounds reasonable, the reset frame is probably not recorded internally, but it seems useful for cancelled requests.
