### ISSUE TITLE
Add "extension_name" parameter for non-test targets

### ISSUE THREAD

**Issue by mrice32** [envoyproxy/envoy#3032]
*Description*:
The new extension refactor has made our site-specific modifications much easier.  However, it might make it even better if there was an "extension_name" parameter for non-test targets as well.  That would mean a build across the entire repo would not build unwanted extensions because the targets would not exist.  Are there any concerns about doing something like this?

**Comment by mattklein123** [comment]
@mrice32 why would they build? Bazel dependency tracking should take care of it. No?

**Comment by mrice32** [comment]
Sorry, I should've been more clear.  I'm talking about if you were to run `bazel build //source/...`, I think bazel will attempt to build all targets - including ones that aren't used by any binaries.  Our internal CI does this (as does Envoy CI IIUC).  If this is atypical for site-specific deployments in the Envoy community, we're happy to just handle it internally.

**Comment by mattklein123** [comment]
@mrice32 I see. I can't speak for others, but for our production build we just build our exe target and let bazel figure out the rest.

**Comment by mattklein123** [comment]
@mrice32 I'm going to close this for now. Feel free to reopen if you still want this and we can discuss.
