### ISSUE TITLE
envoy/network/socket.h socket options don't always work on Windows

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#30360]
I found this while debugging a test on cluster_manager_impl_test.cc.  In particular, when creating a SocketOption that isn't supported on Windows: https://github.com/envoyproxy/envoy/blob/01ae32ba5c6aec8ab810549f804c2dc67061fe81/test/common/upstream/cluster_manager_impl_test.cc#L4291

When that code runs on Windows CI, you don't get an error saying the option isn't available on Windows, instead if the given socket option isn't available, an empty `SocketOptionsImpl` is created instead: https://github.com/envoyproxy/envoy/blob/7db0b4a299730e9c4dd4872788bd56cc7b11018a/envoy/network/socket.h#L47-L51

This means that the socket options which are hashed to form a key for finding the right connection pool end up hashing to the same value, causing the test to fail.  I fixed the test by using socket options that are available on Windows too.

But the concern is that b/c it silently "fails" by creating an empty SocketOptionsImpl, we won't know that the option wasn't applied on the given platform and won't know that we should instead be using a different socket option for that platform.

It seems like envoy/network/socket.h mainly covers Linux/Unix socket options but not the various Windows ones.  This might be something that the Windows maintainers are interested in tackling for the Windows platform.

**Comment by kyessenov** [comment]
CC @grantbarry29
