### ISSUE TITLE
Regarding upgradation of envoy api and envoy api dependencies from envoy 1.17.4 to envoy 1.26.4

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#30409]
As per the below link of envoy dependencies 
https://www.envoyproxy.io/docs/envoy/v1.26.4/intro/arch_overview/security/external_deps#external-dependencies-build

I have added below all dependencies 
opencensus-proto-0.4.1
xds-46e39c7b9b4321731ebe247f2e176fdf0518d76e
client_model-147c58e9608a4f9628b53b6cc863325ca746f63a
opentelemetry-proto-0.19.0
googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1
protoc-gen-validate-0.10.1

I have used envoy api which is coming along with envoy 1.26.4. For using envoy api we make envoyapi.so so that we can use inside our c++ project but we are getting compilation error in envoyapi.so

I am attaching here my compilation error. Please help me in solving compilation error.

 
[compile.txt](https://github.com/envoyproxy/envoy/files/13070093/compile.txt)

**Comment by alyssawilk** [comment]
cc @phlax @envoyproxy/dependency-shepherds

**Comment by Gaurav0411GitHub** [comment]
kindly provide resolution
