### ISSUE TITLE
detect if per_connection_buffer_limit_bytes is configured correctly

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3043]
How do people go about properly configuring `per_connection_buffer_limit_bytes`? One way I can think of is by monitoring how often 413s happen. But that wouldn't really tell you if you connections are frequently stalling due to waiting on their buffer to be flushed out.

I couldn't find any counter that reflects when the network buffer is full and connections have to wait. If there really isn't anything, I am thinking of adding something to give some visibility into this -- unless there's another proxy metric that could help.

**Comment by mattklein123** [comment]
@rgs1 See all the stats with "flow_control" in them. We have pretty copious stats for flow control stop/start in both downstream/upstream direction.

**Comment by rgs1** [comment]
ah -- missed those. i think:

**Comment by mattklein123** [comment]
Closing as answered.
