### ISSUE TITLE
stateful session: add strict mode to header based stateful session

### ISSUE THREAD

**Issue by cpakulski** [envoyproxy/envoy#30475]
I am working on a use case where load balancing decision is completely shifted towards clients. Clients choose endpoints and encode the desired endpoint via header and use stateful session filter. The issue is, that if a chosen endpoint is not available, Envoy chooses a different endpoint based on cluster's LB algorithm, which is not desirable. The use case requires that Envoy returns error if desired endpoint is not available.

I coded a prototype which simply adds `strict` flag to header-based stateful session api and uses the same return path as when a cluster cannot find a healthy host: https://github.com/envoyproxy/envoy/compare/main...cpakulski:envoy:strict_stateful

@wbpcode as owner of stateful session - WDYT?

**Comment by wbpcode** [comment]
This feature sounds pretty good to me. But I am thinking maybe this should be a configuration of upstream Cluster?

IIRC, in previous discussion with @htuch, we both agreed on that it should be the upstream cluster to determine whether a override host could be selected or not (See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-override-host-status).

Then, similarly, it should be upstream cluster to determine whether to re-select host or return null when override host is invalid.

**Comment by Pawan-Bishnoi** [comment]
overrideHostStatus and strict_mode have different functions imo.

overrideHostStatus controls if a _host is in valid state_ to be considered for LB decision
strict_mode decides _what to do_ if it is not.

**Comment by cpakulski** [comment]
I think that the strict flag could be in both places: at the filter and at the cluster level, but the more I think about it, it probably makes more sense to have it at the filter level.

When the setting is at the filter level, it is possible to build two filter chains to serve stateful sessions - one where strict routing is required and other one when strict is not required (LB will choose the next available endpoint) and point them to the same cluster. If the setting is at the cluster level, that scenario requires two clusters.

Another argument to keep it closer to filter is that `strict` routing makes sense only for header based stateful sessions. When stateful session is based on cookies, there is assumption that cookie is generated by Envoy, not user. Having strict setting at the cluster level would interfere with cookie-based stateful routing, because if indicated endpoint is not available, a client must send another request without cookie to select a new host. That scenario is not intuitive and may confuse administrators.

But as @Pawan-Bishnoi indicated, both settings can co-exist. If strict is set at the filter level, by using cluster's overrideHostStatus setting, a user could define if cluster should still try that endpoint if it is in UNHEALTHY or DEGRADED state or immediately return 503 without trying.

**Comment by cpakulski** [comment]
I am glad we are in agreement. Such discussions are always very valuable.
