### ISSUE TITLE
Issue when using Envoy with External_Processing filter for using gRPC with unix sockets or windows named pipe IPC with gRPC service

### ISSUE THREAD

**Issue by csronakpadaliya** [envoyproxy/envoy#30526]
I tried to use external_processing filter to call gRPC service from envoy,

**envoy-exte_proc.yaml**
...........
http_filters:
  - name: envoy.filters.http.ext_proc
        typed_config:
          '@type': "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
          allow_mode_override: true
          processing_mode:
            request_header_mode: "SEND"
            response_header_mode: "SKIP"
            request_body_mode: "NONE"
            response_body_mode: "NONE"
            request_trailer_mode: "SKIP"
            response_trailer_mode: "SKIP"
          grpc_service:
            envoy_grpc:                  
              cluster_name: grpc
............

clusters:
- name: grpc
  type: STATIC
  connect_timeout: 50s
  http2_protocol_options: {}
  load_assignment:
    cluster_name: grpc
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 172.25.112.1
              port_value: 6666 

..........

I configured my gRPCservice using below code files,

**Program.cs**
using DataMapperGrpcExternalService.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.DependencyInjection;

namespace DataMapperGrpcExternalService
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            builder.WebHost.ConfigureKestrel(serverOptions =>
            {
                if (OperatingSystem.IsWindows())
                {
                    serverOptions.ListenNamedPipe("MyPipeName");
                }
                else
                {
                    var socketPath = Path.Combine(Path.GetTempPath(), "socket.tmp");
                    serverOptions.ListenUnixSocket(socketPath);
                }

                serverOptions.ConfigureEndpointDefaults(listenOptions =>
                {
                    listenOptions.Protocols = HttpProtocols.Http2;
                });
            });
            // Add services to the container.
            builder.Services.AddGrpc();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            app.MapGrpcService<GreeterService>();
            app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

            app.Run();
        }
    }
}

**greet.proto**
syntax = "proto3";

option csharp_namespace = "DataMapperGrpcExternalService";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}

**GreeterService.cs**
using DataMapperGrpcExternalService;
using Grpc.Core;
using Microsoft.Extensions.Logging;

namespace DataMapperGrpcExternalService.Services
{
    public class GreeterService : Greeter.GreeterBase
    {
        private readonly ILogger<GreeterService> _logger;
        public GreeterService(ILogger<GreeterService> logger)
        {
            _logger = logger;
        }

        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            return Task.FromResult(new HelloReply
            {
                Message = "Hello " + request.Name
            });
        }
    }
}

but getting below error while calling this greet service from POSTMAN,
![image](https://github.com/envoyproxy/envoy/assets/119849754/1670dcf4-f461-4671-ae0c-3388813172e7)

**Comment by alyssawilk** [comment]
cc @gbrail @stevenzzzz @tyxia

**Comment by gbrail** [comment]
I'm not sure that I understand what you're trying to do here, but it looks like maybe you're trying to use the ext_proc filter to call an arbitrary gRPC service (the "Greeter" service, in this case). The ext_proc filter communicates using a particular gRPC service (link below), which you need to implement.

In other words, the cluster that the filter is configured to use needs to implement this particular service:

[api/envoy/service/ext_proc/v3/external_processor.proto](https://github.com/envoyproxy/envoy/blob/e9366f2b34be537b1b30ed17a4fd75b4715b5990/api/envoy/service/ext_proc/v3/external_processor.proto#L1)

There is a growing list of examples here:

https://github.com/GoogleCloudPlatform/envoy-processor-examples

**Comment by himanshuz2** [comment]
I scoured all examples and documentation for implementation of this service.proto in dotnet.  Adding this comment to help getting started.

Some of the options in the documentation and proto file are more clear when we look at this document below.  
[](https://docs.solo.io/gloo-edge/1.0.0/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extproc/extproc.proto.sk/)

allow_mode_override: true is not yet implemented

Another important point is that the following need to be changed to BUFFERED for currently supported implementation to manipulate request and response body.  It is different enumeration for Headers and Body.  For Headers it is NONE or SKIP whereas for the Body it is one of BodySendMode, NONE, BUFFERED, STREAMED or BUFFERED_PARTIAL

So to process body the Envoy config must set the request_body_mode (response_body_mode if you want to process response body) to BUFFERED  this.   NONE is the default. 
STREAMED mode is not currently supported, BUFFERED_PARTIAL is for large messages and works only if you service can process body message in chunks at a time.

request_body_mode: "BUFFERED"
response_body_mode: "BUFFERED"

**Comment by tyxia** [comment]
> So to process body the Envoy config must set the request_body_mode (response_body_mode if you want to process response body) to BUFFERED this. NONE is the default. STREAMED mode is not currently supported.

It is true that you need to configure body_mode to something other than default NONE, but one thing to clarify: STREAMED mode is supported.
