### ISSUE TITLE
how to open window login

### ISSUE THREAD

**Issue by y-shevchenko** [envoyproxy/envoy#30559]
*How to open window login*

*Description*:
>How to open the login window in the browser?

![Screenshot from 2023-10-27 14-26-33](https://github.com/envoyproxy/envoy/assets/91674914/86f1cada-9802-447c-922e-67d2a2d662bc)

**Comment by lizan** [comment]
Can you elaborate your question? It doesn't look relevant.

**Comment by y-shevchenko** [comment]
> Can you elaborate your question? It doesn't look relevant.

I am using an external authorization server
I would like to have an authorization pop-up window when going to the site, and after successful authorization I would be taken to my site

**Comment by lizan** [comment]
Your server (or the ext authz server) need to add [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header to the response to the browser.
