### ISSUE TITLE
HTTP and TCP filters on a single listener

### ISSUE THREAD

**Issue by bndw** [envoyproxy/envoy#3056]
#### HTTP and TCP filters on a single listener

*Description*:
I'm attempting to configure a single listener to service both TCP (redis) and HTTP traffic in `v1.5.0`, but receiving protocol errors. I've tried reordering the filters.

Is this working as designed?

**Comment by mattklein123** [comment]
This won't work today. It's possible in the future we can do this via filter chain matching as well as protocol inspection via a listener. See also https://github.com/envoyproxy/envoy/pull/2949.

**Comment by bndw** [comment]
Thanks for the clarification, protocol inspection is a more accurate/concise way of framing the question, thanks. Just found these related issues https://github.com/envoyproxy/envoy/issues/527, https://github.com/istio/istio/issues/1426

**Comment by mattklein123** [comment]
Closing as answered.
