### ISSUE TITLE
use external processing filter in envoy which uses grpc service implemented in dotnet core over socket interface

### ISSUE THREAD

**Issue by csronakpadaliya** [envoyproxy/envoy#30562]
I implemented **external_processing** filter in envoy. Here is my question that the envoy handle socket interface settings that were implemented in the gRPC service implemented in the dotnet core?

using DataMapperGrpcExternalService.Services;
using Grpc.Core;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.DependencyInjection;

namespace gRPCService
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            
           builder.WebHost.ConfigureKestrel(serverOptions =>
           {
               if (OperatingSystem.IsWindows())
               {
                  serverOptions.ListenNamedPipe("MyPipeName");
               }
               else
               {
                   var socketPath = Path.Combine(Path.GetTempPath(), "socket.tmp");
                   serverOptions.ListenUnixSocket(socketPath);
               }
    
               serverOptions.ConfigureEndpointDefaults(listenOptions =>
               {
                   listenOptions.Protocols = HttpProtocols.Http2;
               });     
            });

            // Add services to the container.
            builder.Services.AddGrpc();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            app.MapGrpcService<GreeterService>();
            app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

            app.Run();
        }
    }
}

**Comment by lizan** [comment]
You need to configure a cluster that points to your service (via UDS, or TCP), and then configure the [ext_proc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor) filter to use that cluster as external processing service. Does this answer your question?
