### ISSUE TITLE
custom_response filter does not include upstream response headers

### ISSUE THREAD

**Issue by cqi1217** [envoyproxy/envoy#30572]
*Title*:
custom_response.local_response_policy.v3.LocalResponsePolicy does not include upstream response headers

*Description*:
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/custom_response/local_response_policy/v3/local_response_policy.proto
From the response_headers_to_add description: **This allows the response policy to append, to add or to override headers of the original response**. However When I use it, I find some upstream response headers are lost.

*Repro steps*:
required to reproduce the bug.

Config this custom_response.local_response_policy filter and let upstream have some self-defined response headers; those headers are not sent to clients.

**Comment by cqi1217** [comment]
@yanavlasov @pradeepcrao do you have any idea about this behavior?
I have a draft change which stores the upstream headers and readds them to new response. https://github.com/envoyproxy/envoy/pull/30542

**Comment by pradeepcrao** [comment]
You should not need the changes in #30542. I will investigate this today and update this issue.

**Comment by pradeepcrao** [comment]
> You should not need the changes in #30542. I will investigate this today and update this issue.

Strike that. I completely missed the issue here.  #30542 looks like a good start, but I would prefer that we just use the modify_headers lambda to preserve the original headers. I can comment on your PR if you want to continue working on it, or make the changes myself if you don't.

**Comment by cqi1217** [comment]
@pradeepcrao could you make the change actually I am not that familiar with this part of the code? Thanks.

**Comment by lboynton** [comment]
We are also noticing this bug. Can this be reopened?

**Comment by rudrakhp** [comment]
@yanavlasov @pradeepcrao can we reopen the issue? I can come up with a PR for this. We have a related [discussion](https://github.com/envoyproxy/gateway/discussions/7062) in downstream gateway.
