### ISSUE TITLE
Outlier Detection for TCP

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#3058]
*Title*: *Support outlier detection for TCP mode*

*Description*:
TCP is currently supported for active health checking, but is not supported for passive health checking. There are a few ways that this could be implemented. I'm thinking the simplest check would be TCP connection failures (this is what HAProxy does for layer4 health [observing](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.2-observe)). But we might also be able to check on connection failures or something.

**Comment by ggreenway** [comment]
tcp_proxy currently does support outlier detection. See bb069d5a8ff2620c1fb8bd0391491582908f276b. 

Did you observe this not working as expected? Or is the documentation wrong somewhere?

**Comment by bplotnick** [comment]
Ah sorry about that. I did not observe this, it was based purely on documentation. It looks like consecutive 5xx will map to tcp connection failures and do what I want.

I think the part of the documentation that says `...or an event that would cause the HTTP router to return one on the upstream’s behalf (reset, connection failure, etc.)` covers this. Though I may submit a PR to explicitly call out TCP in the documentation.

**Comment by ggreenway** [comment]
Documentation PRs are always greatly appreciated! Sorry the docs weren't clear on this.
