### ISSUE TITLE
how to find a correct version for @buf/envoyproxy_envoy.bufbuild_es

### ISSUE THREAD

**Issue by smhmayboudi** [envoyproxy/envoy#30605]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *how to find a correct version for @buf/envoyproxy_envoy.bufbuild_es*

*Description*:
>Describe the issue.

I have a commit sha 6b9db09c69965d5bfb37bdd29693f8b7f9e9e9ec. I want to add the correct package to my package.json, however, I could not find the relation between the commit sha of GitHub and the commit sha of buf.build.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by lizan** [comment]
@phlax do we push our api to buf in our CI?

From the docs seems this is managed by Buf but not us, so I'm not clear what's their tagging policy.

**Comment by phlax** [comment]
> do we push our api to buf in our CI?

not that im aware of

@adisuissa may have some more context

**Comment by adisuissa** [comment]
We don't push to the Buf registry.
Looking at https://buf.build/envoyproxy/envoy/activity/commit/b65e310e14a04242a123570d4fec3894
I think this is done by a bot ("bufsystem"). Not sure how to map a specific BSR update to an Envoy Github PR, but if this is a one-of, consider looking through https://buf.build/envoyproxy/envoy/activity/ to find the correct mapping.
