### ISSUE TITLE
Question: Resetting stream after sending local reply

### ISSUE THREAD

**Issue by emdgit** [envoyproxy/envoy#30606]
I'd like to know if there's a way to reset a stream right after local reply was sent from a custom http filter. Calling `StreamDecoderFilterCallbacks::resetStream()` after `StreamDecoderFilterCallbacks::sendLocalReply()` leads to an error because the request is already completed. The goal is in some cases to send local reply to a downstream and then forcefully reset stream. 

Server deals ok if a client closes a connection after recieving the entire response but if it doesn't close I need it to be immediately closed and with `LocalClose` type. Please give me a hint if it could be done via HttpFilter's API, or maybe this case is somehow configurable using timeouts.

**Comment by lizan** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
I'm not quite sure what you want to be doing.  The stream is closed after you sendLocalReply so there's nothing to reset.  If you want to not send a local reply downstream you can use onLocalReply and return ContinueAndResetStream to not actually send the local reply?
