### ISSUE TITLE
Using Envoy Tap and handling data returned via the POST /tap

### ISSUE THREAD

**Issue by 3goats** [envoyproxy/envoy#30638]
Hi,

I used [this](https://github.com/salrashid123/envoy_tap) really helpful example to get me started with the Envoy tap feature. This all seems to work as per the example, however I'm struggling to do anything useful with the data that gets returned. The example makes the following comment: 

"One glaring thing i omitted in this repo is how to parse the JSON data back on the admin listener.

It seems envoy returns a new line delimited pretty-printed JSON back!...i have no idea how to effectively parse that in golang...there is certainly away...if you know it, LMK"

Is there an example/way I can easily parse the data into a Golang data structure so I can do something with it ?

**Comment by lizan** [comment]
You can use protojson to parse it into corresponding protobuf types.

**Comment by 3goats** [comment]
Thanks - are there any examples for this ?
