### ISSUE TITLE
Regarding using envoy api and envoy api dependencies in envoy 1.26.4

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#30637]
I want to make libenvoyapi.so in which I am including below 
envoy api-> which is downloading along with envoy 1.26.4
envoy api dependencies->
      client_model-147c58e9608a4f9628b53b6cc863325ca746f63a
      opencensus-proto-0.4.1
      xds-46e39c7b9b4321731ebe247f2e176fdf0518d76e
      protoc-gen-validate-0.10.1
      opentelemetry-proto-0.19.0
      googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1
I have taken these dependencies according to the mentioned in below url
https://www.envoyproxy.io/docs/envoy/v1.26.4/intro/arch_overview/security/external_deps#external-dependencies-build

But I am still getting compilation error like  in opencensus and googleapis
8080:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/metrics/v1/metrics_service.pb.cc:114:6: error: ‘::descriptor_table_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto’ has not been declared
8087:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/metrics/v1/metrics_service.pb.cc:115:6: error: ‘::descriptor_table_opencensus_2fproto_2fmetrics_2fv1_2fmetrics_2eproto’ has not been declared
8094:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/metrics/v1/metrics_service.pb.cc:116:6: error: ‘::descriptor_table_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto’ has not been declared
8104:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/trace/v1/trace.pb.cc:627:6: error: ‘::descriptor_table_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto’ has not been declared
8121:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/metrics/v1/metrics.pb.cc:498:6: error: ‘::descriptor_table_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto’ has not been declared
8143:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/trace/v1/trace_service.pb.cc:173:6: error: ‘::descriptor_table_opencensus_2fproto_2fagent_2fcommon_2fv1_2fcommon_2eproto’ has not been declared
8150:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/trace/v1/trace_service.pb.cc:174:6: error: ‘::descriptor_table_opencensus_2fproto_2fresource_2fv1_2fresource_2eproto’ has not been declared
8157:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/trace/v1/trace_service.pb.cc:175:6: error: ‘::descriptor_table_opencensus_2fproto_2ftrace_2fv1_2ftrace_2eproto’ has not been declared
8164:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/opencensus-proto-0.4.1/src/opencensus/proto/agent/trace/v1/trace_service.pb.cc:176:6: error: ‘::descriptor_table_opencensus_2fproto_2ftrace_2fv1_2ftrace_5fconfig_2eproto’ has not been declared
8172:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8180:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8186:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/target.pb.cc:483:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2factor_2eproto’ has not been declared
8193:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/target.pb.cc:484:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2fcommon_2eproto’ has not been declared
8200:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/query_drive_activity_response.pb.cc:133:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2faction_2eproto’ has not been declared
8207:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/query_drive_activity_response.pb.cc:134:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2factor_2eproto’ has not been declared
8214:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/query_drive_activity_response.pb.cc:135:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2fcommon_2eproto’ has not been declared
8221:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/query_drive_activity_response.pb.cc:136:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2ftarget_2eproto’ has not been declared
8229:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.cc:1066:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2factor_2eproto’ has not been declared
8236:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.cc:1067:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2fcommon_2eproto’ has not been declared
8243:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.cc:1068:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2ftarget_2eproto’ has not been declared
8252:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8258:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/alertcenter/v1beta1/alertcenter.pb.cc:775:6: error: ‘::descriptor_table_google_2fapi_2fannotations_2eproto’ has not been declared
8265:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/alertcenter/v1beta1/alertcenter.pb.cc:776:6: error: ‘::descriptor_table_google_2fapi_2fclient_2eproto’ has not been declared
8272:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/alertcenter/v1beta1/alertcenter.pb.cc:780:6: error: ‘::descriptor_table_google_2frpc_2fstatus_2eproto’ has not been declared
8284:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8290:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/label_permission.pb.cc:79:6: error: ‘::descriptor_table_google_2fapi_2fresource_2eproto’ has not been declared
8297:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/drive_activity_service.pb.cc:65:6: error: ‘::descriptor_table_google_2fapi_2fannotations_2eproto’ has not been declared
8304:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/drive_activity_service.pb.cc:66:6: error: ‘::descriptor_table_google_2fapi_2fclient_2eproto’ has not been declared
8311:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/drive_activity_service.pb.cc:67:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2fquery_5fdrive_5factivity_5frequest_2eproto’ has not been declared
8314:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/drive_activity_service.pb.cc:68:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2factivity_2fv2_2fquery_5fdrive_5factivity_5fresponse_2eproto’ has not been declared
8318:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8324:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/label.pb.cc:299:6: error: ‘::descriptor_table_google_2fapi_2ffield_5fbehavior_2eproto’ has not been declared
8332:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/label.pb.cc:300:6: error: ‘::descriptor_table_google_2fapi_2fresource_2eproto’ has not been declared
8339:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/label.pb.cc:301:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2flabels_2fv2_2fcommon_2eproto’ has not been declared
8346:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/label.pb.cc:302:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2flabels_2fv2_2ffield_2eproto’ has not been declared
8356:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/activity/v2/action.pb.h:1708:22: error: ‘typedef class google::apps::drive::activity::v2::Create_New google::apps::drive::activity::v2::Create::New’ conflicts with a previous declaration
8362:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/requests.pb.cc:161:6: error: ‘::descriptor_table_google_2fapi_2ffield_5fbehavior_2eproto’ has not been declared
8369:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/requests.pb.cc:162:6: error: ‘::descriptor_table_google_2fapi_2fresource_2eproto’ has not been declared
8376:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/requests.pb.cc:163:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2flabels_2fv2_2flabel_2eproto’ has not been declared
8383:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/requests.pb.cc:164:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2flabels_2fv2_2flabel_5fpermission_2eproto’ has not been declared
8391:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/field.pb.cc:632:6: error: ‘::descriptor_table_google_2fapi_2ffield_5fbehavior_2eproto’ has not been declared
8398:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/field.pb.cc:633:6: error: ‘::descriptor_table_google_2fapps_2fdrive_2flabels_2fv2_2fcommon_2eproto’ has not been declared
8405:/imsgit_local/work/g2gupta/GIT_1/ims_common/envoy/thirdparty/src/api/envoy_api_dependencies_v5/googleapis-114a745b2841a044e98cdbb19358ed29fcf4a5f1/google/apps/drive/labels/v2/field.pb.cc:635:6: error: ‘::descriptor_table_google_2ftype_2fdate_2eproto’ has not been declared

I am attaching here complete output of compilation
[compile.txt](https://github.com/envoyproxy/envoy/files/13217544/compile.txt)

We were using the same in envoy 1.17.4 but we are getting these compilation in envoy 1.26.4 
Please let me know how can I resolve such kind of errors

**Comment by lizan** [comment]
I have no idea without the actual build config / source you have with this. I suspect it's some protobuf internal thing or you are missing some compiler flags.

**Comment by Gaurav0411GitHub** [comment]
I have also reported the issue in protobuf
https://github.com/protocolbuffers/protobuf/issues/14504.
Protobuf team is saying to report the same issue in envoy repository.

**Comment by Gaurav0411GitHub** [comment]
It's ok, if we leave this compilation error.
I have generated *.cc and *.h files for all envoy api and external dependencies mentioned in the below page
https://www.envoyproxy.io/docs/envoy/v1.26.4/intro/arch_overview/security/external_deps#external-dependencies-build
Now could you pleas give me steps for just creating a library like libenvoyapi.so from envoy api and external dependencies

**Comment by Gaurav0411GitHub** [comment]
Kindly help in the above matter

**Comment by Gaurav0411GitHub** [comment]
Kindly help in the above matter

**Comment by Gaurav0411GitHub** [comment]
Kindly help in the above matter
