### ISSUE TITLE
Getting a "Client reset the request stream" while using "External-Processing" filter in envoy for call gRPC service implemented in dotnet core

### ISSUE THREAD

**Issue by csronakpadaliya** [envoyproxy/envoy#30631]
I use external-processing envoy filter for call gRPC service to handle request/response headers/body. Here i attach my envoy.yaml file.

static_resources:
  
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              typed_per_filter_config:
                envoy.filters.http.cors:
                  '@type': "type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy"
                  allow_origin_string_match:
                    - safe_regex:
                        regex: \*
                  allow_methods: 'GET,POST,PUT,PATCH,DELETE,OPTIONS'
                  allow_headers: >-
                    hmac,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Access-Control-Allow-Origin,total
                  allow_credentials: true
                  max_age: '1728000'
              routes:
              - match:
                  prefix: "/WeatherForecast"
                route:
                  cluster: service1
                response_headers_to_add:
                - header:
                    key: Access-Control-Expose-Headers
                    value: '*'
                
              - match:
                  prefix: "/v2/pet"
                route:
                  host_rewrite_literal: petstore.swagger.io
                  cluster: service_petstore_io
                response_headers_to_add:
                  - header:
                      key: "Access-Control-Expose-Headers"
                      value: "*"
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
          - name: envoy.filters.http.ext_proc
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
              failure_mode_allow: false
              
              allow_mode_override: true
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SKIP"
                request_body_mode: "NONE"
                response_body_mode: "NONE"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"

              grpc_service:
                envoy_grpc:                  
                  cluster_name: grpc
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: grpc
    type: STATIC
    connect_timeout: 5s
    http2_protocol_options: 
      connection_keepalive: 
        interval: 60s
        timeout: 10s
        connection_idle_interval: 10s
    load_assignment:
      cluster_name: grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.25.112.1
                port_value: 6666

  - name: service1
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.25.112.1
                port_value: 5017

  - name: service_petstore_io
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_petstore_io
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: petstore.swagger.io
                    port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: petstore.swagger.io

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

but when i make a POST call to envoy from postman on URL="http://localhost:10000/v2/pet" with body

{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

it shows below error on console of gRPC service

![download](https://github.com/envoyproxy/envoy/assets/119849754/9ce82fa4-8ab8-4782-929c-4a9de056abeb)

**Comment by lizan** [comment]
cc @gbrail @stevenzzzz @tyxia

**Comment by himanshuz2** [comment]
Can you try with response_body_mode: "BUFFERED" in your ext_proc filter configuration?
