### ISSUE TITLE
The token bucket is shared across all workers but not thread safe.

### ISSUE THREAD

**Issue by maoyutao** [envoyproxy/envoy#30654]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/bandwidth_limit_filter.html#bandwidth-limit

The HTTP Bandwidth limit filter uses a token bucket shared across all workers, but a note in [TokenBucketImpl](https://github.com/envoyproxy/envoy/blob/f967781f639675619e7b7255b8993f373bb68af1/source/common/common/token_bucket_impl.h#L11) says it is not thread safe.

**Comment by StarryVae** [comment]
yes, although `TokenBucketImpl` is not thread safe, but we add a `mutex` here:

https://github.com/envoyproxy/envoy/blob/55a95a171c1371b2402e9c8e2092f5b0ca02462d/source/common/common/shared_token_bucket_impl.h#L45
