### ISSUE TITLE
golang filter: Envoy segfault when the DecodeHeaders returns status code Stop and the request doesn't have body

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#30688]
*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Write a go plugin, which returns `StopAndBuffer` as the `api.StatusType`, and the request doesn't have a body (`endStream` is true).
It seems Envoy segfault when it tries to access fields relative to the body, which is nullptr in this case.

Suggestion: 
treat `StopAndBuffer` as `Continue` if `endStream` is true in DecodeHeaders.

**Comment by lizan** [comment]
@doujiang24 @wangfakang @StarryVae

**Comment by doujiang24** [comment]
@spacewander Nice catch, do you have time to create a PR for it? thanks~

**Comment by spacewander** [comment]
> @spacewander Nice catch, do you have time to create a PR for it? thanks~

Yes. I will fix it next week.
