### ISSUE TITLE
[erlang 25.3.2] getting erl_crash.dump after build erlang 25.3.2 with VS22  with error in do_boot, load_failed

### ISSUE THREAD

**Issue by ssm6498** [envoyproxy/envoy#30707]
*Title*: *[erlang 25.3.2] getting erl_crash.dump after build erlang 25.3.2 with VS22 with error in do_boot, load_failed*

*Description*:
getting below errors in rabbitmq logs:
{"init terminating in do_boot",{load_failed,[supervisor,proc_lib,lists,logger_simple_h,logger_config,logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,error_logger,erl_parse,erl_lint,erl_eval,code_server,code,application_master,application_controller,application,error_handler]}} 
init terminating in do_boot ({load_failed,[supervisor,proc_lib,lists,logger_simple_h,logger_config,logger_backend,logger_server,logger_filters,logger,kernel,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,error_logger,erl_parse,erl_lint,erl_eval,code_server,code,application_master,application_controller,application,error_handler]}) 
Crash dump is being written to: erl_crash.dump...done

This issue is faced after using Visual Studio 22 in erlang build process
Is Visual Studio 22 is supported in erlang 25.3.2?

**Comment by lizan** [comment]
How is this relevant to Envoy? wrong repo?

**Comment by ssm6498** [comment]
Yes. Apologizes, by mistake pasted on wrong repo
