### ISSUE TITLE
Increase in UF,URX after upgrade from 1.24 to 1.25

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#30706]
*Title*: *Increase in `UF,URX` after upgrade from 1.24 to 1.25*

*Description*:
We upgraded from 1.24 to 1.25 and multiple services were impacted by `503 UF,URX` so we had to revert

I searched for this response flag and any general performance related issues and found nothing. Any ideas? Below is a graph of the impact before reverting

<img width="1344" alt="image" src="https://github.com/envoyproxy/envoy/assets/220817/dbfea206-8f54-4547-a0ed-eb16d1daab11">

**Comment by lizan** [comment]
Do you have debug logs from those request? cc @alyssawilk

**Comment by phylake** [comment]
No I don't. I'm not sure I can get them either with how many services were affected and the level of impact

**Comment by alyssawilk** [comment]
Yeah I'm afraid there's not enough information for us to go on.  If you can do a minimal canary, or maybe even repro the issue with any internal loadtests / replay tests you have, getting command line logs or access logs would likely help quite a bit.

**Comment by phylake** [comment]
I got some logs for this. No debug logs around the access logs though. The all report `upstream_reset_before_response_started{connection_failure}`

They come from a variety of clients to a variety of upstreams. I'm not seeing anything in common other than the error itself

**Comment by alyssawilk** [comment]
That sounds like the upstream doesn't like something that Envoy's sending,
something which we can't really debug from the Envoy side.  Any chance your
upstreams log why they're disconnecting?

My next suggestion was going to be taking a look at the release notes for
1.25
<https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.25/v1.25.0>
and flipping any reloadable flags in the release, as functional changes to
the data plane are generally runtime guarded, but looking at the release
I'm really unclear on what would have caused any behavioral change.  Still
you could give it a shot?

**Comment by phylake** [comment]
I think I'll leave this one as a mystery and probably an issue in compiling Envoy. I went to v1.26 and the issue went away. So did #29856 even though I didn't change the CI target

I really appreciate your support @alyssawilk
