### ISSUE TITLE
LDS loading times with large number of listeners (10K+)

### ISSUE THREAD

**Issue by andreycpp** [envoyproxy/envoy#30723]
*Title*: LDS loading times with large number of listeners (10K+)

*Description*:
We're evaluating use of envoy for a scenario where we'd like to run large number of listeners each with unique configuration (think multi-tenant environment with listener per tenant). We're interested in parameters like initial load times as well as individual listener updates.

So far in testing with [go-control-plane](https://github.com/envoyproxy/go-control-plane/blob/main/internal/example/README.md) as well as just yaml files we can see that:

- It takes envoy ~5 minutes to load a simple config with 10K listeners. About 10 minutes for 20K listeners, so on.
- It takes envoy ~couple seconds to update individual listener.

The individual listener update times are great, but we're worried about initial load times for situations of cold boot and at higher scale (think 50K listeners ~25 minutes of wait). We also tested very simple config, and I'd expect larger configs take more time.

Is there any ongoing work or ideas on how to improve config loading and/or understanding where the main slowness may be coming from?

In above test we can observe envoy sitting at 100% (perhaps it's main thread that does config processing).

**Comment by andreycpp** [comment]
Thanks @niax for sharing! In my current experiment I'm actually using 1 cluster.

Here's a primitive change to go-control-plane's example that I'm testing with: https://github.com/envoyproxy/go-control-plane/compare/main...andreycpp:go-control-plane:test_xds_scale.

This creates 10K listeners binding them to ports 10000-19999 on loopback. There's also a generated envoy yaml file with 10K listeners showing very similar load times compared to xDS.

**Comment by andreycpp** [comment]
Thanks @yanavlasov . Which component do you suggest to profile (Envoy, xDS?) and what kind of profiling shall I run / any instructions on how to do it? Thanks!

**Comment by yanavlasov** [comment]
Envoy
