### ISSUE TITLE
Question: Any existing mechanism for L7 Filter determining L4 session reusing

### ISSUE THREAD

**Issue by EltonzHu** [envoyproxy/envoy#30720]
*Title*: *Question: Any existing mechanism for L7 Filter determining L4 session reusing*

*Description*:
Does anyone know how to determine if the current request being processed by an Envoy http filter is reusing the session or not?

**Comment by yanavlasov** [comment]
I assume you mean reusing TLS session. This property is not presently exposed to HTTP filters.
