### ISSUE TITLE
Stream response header timeout support

### ISSUE THREAD

**Issue by Joon-L** [envoyproxy/envoy#30753]
*Title*: *Envoy support for stream response header timeout*

*Description*:
> We have many upstream applications that uses SSE (server-sent events) which will return response headers early and stream events later as the server pushes them. For these streams, we want to timeout early in the case where upstream is not responding with response headers within a certain timeframe (basically similar to [request_headers_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-headers-timeout) but for response headers).
We cannot rely fully on the [stream_idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-idle-timeout) as this interval between events can be longer than what we expect for the header to arrive.

Does Envoy today support such timeout configurations? If not, would this feature request something be reasonable for Envoy to support in the future?

**Comment by KBaichoo** [comment]
Does Envoy today support such timeout configurations? If not, would this feature request something be reasonable for Envoy to support in the future?
> I don't think we have something that handles this case. A patch for this would certainly be welcomed :).

**Comment by arulthileeban** [comment]
I'd be interested in creating a patch for this. To open the discussion, should we build this as a timeout config (timeout if no server response in X mins. Once response is delivered, suspend timeouts for Y mins) or a SSE specific config?
