### ISSUE TITLE
Redis proxy filter should have an option to convert ZMSCORE to multiple ZSCORE calls

### ISSUE THREAD

**Issue by ziggythehamster** [envoyproxy/envoy#30767]
`ZMSCORE` was introduced in Redis 6.2.0. The following two exchanges are equivalent:

```
redis> ZMSCORE key one two three
1) "1"
2) "2"
3) "3"
```

```
redis> ZSCORE key one
"1"
redis> ZSCORE key two
"2"
redis> ZSCORE key three
"3"
```

In the case where Envoy is talking to versions of Redis <6.2.0 and versions >=6.2.0, having the option to configure one Redis to emulate `ZMSCORE` by issuing multiple `ZSCORE`s (potentially in a `MULTI`/`EXEC`) would be helpful, particularly for those using Envoy as a transition mechanism between clusters running different major versions of Redis. `ZMSCORE` can be implemented as a Lua script in the older versions of Redis, but Lua scripts don't play well with Envoy.

**Comment by KBaichoo** [comment]
cc @weisisea
