### ISSUE TITLE
How to add a self-defined gcc/g++ (may be arm-32 or other self defined build toolchains) build toolchains ?

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#30777]
We want to cross-compile envoy to other platform by self-defined toolchains. 
Do we have some officials recommend way or guild? 

Currently we were trying to modify this BUILD & builtin_include_directory_paths in local path 
"bazel-envoy/external/local_config_cc" .  And trying to modify the cc_toolchain_config configurations to some local gcc building toolchain. But seems a lot of c++ header file not found issues. 
So any suggestions?

**Comment by KBaichoo** [comment]
cc @phlax @keith

**Comment by wufanqqfsc** [comment]
we faced such issue now ,compiler seems ok , now but we faced link issue:
https://github.com/envoyproxy/envoy/issues/31212
