### ISSUE TITLE
Configuring flow control to prevent outofmemory

### ISSUE THREAD

**Issue by praneetpushpal** [envoyproxy/envoy#30779]
Need a clarification with flow control.

We are using envoy proxy and we have some upstream which are actually slow, sometimes taking upto 22 seconds:

[2023-10-23T08:37:01.659Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 529 7 4006 4006 "-" "grpc-go/1.56.2" "77cab6b6-0638-430e-b59a-4c3b3029b3b5" "localhost:8887" "172.16.95.212:8080"
[2023-10-23T08:37:02.273Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 685 7 3392 3392 "-" "grpc-go/1.56.2" "f5042724-1468-41a8-b6d5-75a5af0370b7" "localhost:8887" "172.16.95.212:8080"
[2023-10-23T08:36:42.770Z] "POST /test.sl.EventDB.v1.EventDB/Create HTTP/2" 200 - 498 7 **22895 22895** "-" "grpc-go/1.56.2" "5ae72910-3b33-4957-969d-731710bc3206" "localhost:8887" "172.16.95.212:8080"

envoy counter increasing with time:

downstream_cx_rx_bytes_buffered: 78252
downstream_cx_rx_bytes_buffered: 21600
downstream_cx_rx_bytes_buffered: 21600
downstream_cx_rx_bytes_buffered: 21600
downstream_cx_rx_bytes_buffered: 71942
downstream_cx_rx_bytes_buffered: 170274
downstream_cx_rx_bytes_buffered: 1134517
downstream_cx_rx_bytes_buffered: 682432
downstream_cx_rx_bytes_buffered: 3349588
downstream_cx_rx_bytes_buffered: 9399489
downstream_cx_rx_bytes_buffered: 15503287
downstream_cx_rx_bytes_buffered: 12460896
downstream_cx_rx_bytes_buffered: 10434389
downstream_cx_rx_bytes_buffered: 11567799

In such a case envoy is buffering, resulting in out of memory.

In order to protect envoy we wanted to bring in flow control. The doubt is if we configure initial_stream_window_size and per_connection_buffer_limit_bytes to be less than the size of request, will envoy reject such requests?

For example: if I configure initial_stream_window_size as 1 MB and my request is 2 MB will envoy reject such requests?

Irrespective of the upstream slowness we want to protect **envoy serving the incoming requests without buffering.**
 Please give your valuable suggestions

**Comment by praneetpushpal** [comment]
@alyssawilk If you can help please

**Comment by botengyao** [comment]
> For example: if I configure initial_stream_window_size as 1 MB and my request is 2 MB will envoy reject such requests?

I think Envoy will not reject the request. Instead, it will allow the request to be sent in chunks up to the window size with pressure/flow control.

Configuring `per_connection_buffer_limit_bytes` in listener may take more effect, like it will apply pressure to the client peer at L3/4 level. When the buffer limit is reached, Envoy calls `readDisable` on the connection to disable further reading of data from the connection, and the read will resume when the buffer is drained to low water mark. You can try it with your tests. Thanks!

**Comment by htuch** [comment]
@KBaichoo

**Comment by KBaichoo** [comment]
The doubt is if we configure initial_stream_window_size and per_connection_buffer_limit_bytes to be less than the size of request, will envoy reject such requests?
> unless you have a buffering filter or something similar within the filter chain, setting these < request size should still be ok as there will be backpressure from either HTTP2 flow control or TCP.
