### ISSUE TITLE
More undocumented stats

### ISSUE THREAD

**Issue by ofek** [envoyproxy/envoy#3077]
cc @taiki45 @mattklein123

Also, is https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/stats#http2-codec-statistics actually rooted at `cluster.<cluster_name>.http2.`? We're getting stats like `cluster.xds-grpc.http2.header_overflow` and never `http2.`.

`server.watchdog_miss` and `server.watchdog_mega_miss`
https://github.com/envoyproxy/envoy/blob/9045478cbf1006c22fbfae49c8ac675b36740923/source/server/guarddog_impl.h#L34

``cluster.upstream_cx_idle_timeout``
https://github.com/envoyproxy/envoy/blob/c2ce08e3f5902916d79a816a893e32a4b65f6da1/include/envoy/upstream/upstream.h#L305

``cluster.update_rejected`` and `http.rds.update_rejected` (not sure about link)
https://github.com/envoyproxy/envoy/blob/98a9d17ada3b88beb3b597276fbeee095e75aa96/include/envoy/config/subscription.h#L88

``http.rds.update_empty``
https://github.com/envoyproxy/envoy/blob/24297974e479929568115a3dbce06c4e8f698f5a/source/common/router/rds_impl.h#L70

These (the `lds` may be a tag? I can't find `lds` in any other metrics):
```
listener_manager.lds.update_attempt
listener_manager.lds.update_failure
listener_manager.lds.update_rejected
listener_manager.lds.update_success
listener_manager.lds.version
```

Many `tcp` stats:

``tcp.downstream_cx_rx_bytes_total``
https://github.com/envoyproxy/envoy/blob/9271200ee1799c5cddf9785c5a63d0634cfcbf02/source/extensions/filters/network/tcp_proxy/tcp_proxy.h#L37

``tcp.downstream_cx_rx_bytes_buffered``
https://github.com/envoyproxy/envoy/blob/9271200ee1799c5cddf9785c5a63d0634cfcbf02/source/extensions/filters/network/tcp_proxy/tcp_proxy.h#L38

``tcp.idle_timeout``
https://github.com/envoyproxy/envoy/blob/9271200ee1799c5cddf9785c5a63d0634cfcbf02/source/extensions/filters/network/tcp_proxy/tcp_proxy.h#L45

``tcp.upstream_flush_total``
https://github.com/envoyproxy/envoy/blob/9271200ee1799c5cddf9785c5a63d0634cfcbf02/source/extensions/filters/network/tcp_proxy/tcp_proxy.h#L46

``tcp.tcp.upstream_flush_active``
https://github.com/envoyproxy/envoy/blob/9271200ee1799c5cddf9785c5a63d0634cfcbf02/source/extensions/filters/network/tcp_proxy/tcp_proxy.h#L47

Also, no docs about stats rooted at `http_mixer_filter.` nor `tcp_mixer_filter.`.

**Comment by ofek** [comment]
Bump

**Comment by numerodix** [comment]
fwiw I had a look and all the stats reported in this issue are now present in the docs:

source/server/guarddog_impl.cc:
`watchdog_miss`
`watchdog_mega_miss`
https://www.envoyproxy.io/docs/envoy/latest/operations/performance.html?highlight=watchdog_miss

include/envoy/upstream/upstream.h:
`upstream_cx_idle_timeout`
https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html?highlight=upstream_cx_idle_timeout

include/envoy/config/subscription.h:
`update_attempt`
`update_success`
`update_failure`
`update_rejected`
`version`
https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/mgmt_server.html?highlight=update_rejected

include/envoy/upstream/upstream.h:
`update_empty`
https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html?highlight=update_empty

common/tcp_proxy/tcp_proxy.h:
`downstream_cx_rx_bytes_total`
`downstream_cx_rx_bytes_buffered`
`idle_timeout`
`upstream_flush_total`
`upstream_flush_active`
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter.html?highlight=downstream_cx_rx_bytes_total

The strings `http_mixer_filter` and `tcp_mixer_filter` don't exist in the codebase. I can't even find any history for them using `git log -S http_mixer_filter`

@ofek @mattklein123

**Comment by numerodix** [comment]
> Also, is https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/stats#http2-codec-statistics actually rooted at cluster.<cluster_name>.http2.? We're getting stats like cluster.xds-grpc.http2.header_overflow and never http2..

This is quite correct, also for `http1.`. They are rooted under the cluster. I've pushed #13464 to update this.

**Comment by mattklein123** [comment]
OK let's close this and open individual tracking issues for doc bugs which are easier to resource. Thank you!
