### ISSUE TITLE
OpenTelemetry tracer – Provide initial span attributes to samplers

### ISSUE THREAD

**Issue by samohte** [envoyproxy/envoy#30803]
*Title*: *Provide initial span attributes to OpenTelemetry samplers*

*Description*:
The OpenTelemetry project defines the concept of a [Sampler API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler). A sampler API was added to Envoy in  [#30259](https://github.com/envoyproxy/envoy/pull/30259) .

The sampler API allows to provide initial span attributes to a sampler so they can be considered for sampling decisions. This is currently not implemented in Envoy’s OpenTelemetry tracer.

The [OpenTelemetry semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-spans) define semantic conventions for HTTP client and server Spans. There is a list of attributes which should be provided to samplers. 
Such attributes are commonly used by samplers, e.g.:
- filter out some requests using the path/address (e.g. health checks).
- doing url based sampling: Consider a scenario where a sampler wants to allow N requests / minutes. 90% of all request are going to /path1, the remaining ten percents are going to /path2 and /path3. A sampler may want to sample N/3 requests for every path.
- consider request method (GET, POST, ..) for sampling decisions. GET and POST might have a different meaning in REST APIs (even is path is equal). GET is used to query an info, POST is used to update an info.

The scope of this issue is to create a set of initial span attributes when a span is started and provide it to a configured sampler via the already existing API.

*Relevant Links*:
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler
- https://opentelemetry.io/docs/specs/semconv/http/http-spans

**Comment by htuch** [comment]
@joaopgrassi @wbpcode

**Comment by joaopgrassi** [comment]
Yep, @samohte and I are working together on tracing things 👍
