### ISSUE TITLE
[ext_proc] support routing decision based on first body chunk

### ISSUE THREAD

**Issue by johnsiu** [envoyproxy/envoy#30810]
*Title*: *Add support for external processor to make routing decision based on first body chunk*

*Description*:
>Header mutation is required to make routing decision. When `request_body_mode` is `STREAMED`, any header mutation returned by the external processor in `BodyResponse` is ignored (https://github.com/envoyproxy/envoy/blob/v1.28.0/source/extensions/filters/http/ext_proc/processor_state.cc#L255-L275), unless `request_header_mode` is `SEND` and we already have the full body at the time when the external processor returns the `HeadersResponse` (https://github.com/envoyproxy/envoy/blob/v1.28.0/source/extensions/filters/http/ext_proc/processor_state.cc#L131-L140)
I can understand header mutation is too late after we've already passed the header further down the filter chain, but it's not too late on the first body chunk, so it should be feasible and opens up many use cases to be supported using ext_proc.

[*Relevant Links*:]
> Similar to https://github.com/envoyproxy/envoy/issues/2635, but use ext_proc.

**Comment by htuch** [comment]
>  I can understand header mutation is too late after we've already passed the header further down the filter chain, but it's not too late on the first body chunk, so it should be feasible and opens up many use cases to be supported using ext_proc.

In streamed mode it is, headers are sent to the backend before the first body chunk is sent. CC @tyxia @yanjunxiang-google

**Comment by tyxia** [comment]
@johnsiu  Can you try to use buffer mode (i.e., ProcessingMode::BUFFERED) instead of STREAMED mode? It supports apply header mutation on body response.

**Comment by johnsiu** [comment]
The use case is we need to proxy bidirectional streaming gRPC calls and the client needs to have received some response frames from the server before it can finish sending all request frames, so buffered mode won't work because the server can't respond before receiving a request frame.
