### ISSUE TITLE
ExtAuthz request with duplicated headers

### ISSUE THREAD

**Issue by qixuan-li1** [envoyproxy/envoy#30815]
Hi, I’m using gRPC extauthz filter in Envoy. Does anyone know how envoy parses headers into the [CheckRequest](https://github.com/envoyproxy/envoy/blob/dcdda09c0871be7a13fff8be4a644e0cebd16bf6/api/envoy/service/auth/v3/external_auth.proto#L40) sent to extauthz cluster? For example, suppose I have a client that sends multiple duplicated Host headers, what does the [host field](https://github.com/envoyproxy/envoy/blob/dcdda09c0871be7a13fff8be4a644e0cebd16bf6/api/envoy/service/auth/v3/attribute_context.proto#L126) look like?  Will Envoy comma concatenate them? 

cc: @dio

**Comment by htuch** [comment]
In general, I think https://github.com/envoyproxy/envoy/blob/dcdda09c0871be7a13fff8be4a644e0cebd16bf6/api/envoy/service/auth/v3/attribute_context.proto#L116 answers this.

The host header has specific rules around this, see https://httpwg.org/specs/rfc9112.html#request.target.

**Comment by qixuan-li1** [comment]
Thanks @htuch, is it possible to make this more explicit to note to which RFC does the handling of duplicated header names conform? Searching on the internet, I assume the value will be a comma separated list of values based on [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2)?

**Comment by htuch** [comment]
Right. Feel free to propose proto comment or documentation updates in a PR to clarify for future readers.

**Comment by htuch** [comment]
@qixuan-li1 are you planning on working on this documentation improvement?

**Comment by qixuan-li1** [comment]
Sure, will have a PR on this.
