### ISSUE TITLE
May the metrics upstream_cx_total decrease

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#30822]
I'm reading the official doc: https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats, and I find that `upstream_cx_total` means "Total connections".

I'm kind of confused by this description. 

So it counts the number of all of connections since Envoy is started (case A)? Or it counts the number of connections real time (case B)?

For case A, `upstream_cx_total` will never decrease, whereas for case B, `upstream_cx_total` could decrease.

I'm trying to figure it out because I can't understand when the health check mechanism uses no_traffic interval.

I found the source code of health check:
```
std::chrono::milliseconds HealthCheckerImplBase::interval(HealthState state,
                                                          HealthTransition changed_state) const {
  // See if the cluster has ever made a connection. If not, we use a much slower interval to keep
  // the host info relatively up to date in case we suddenly start sending traffic to this cluster.
  // In general host updates are rare and this should greatly smooth out needless health checking.
  // If a connection has been established, we choose an interval based on the host's health. Please
  // refer to the HealthCheck API documentation for more details.
  uint64_t base_time_ms;
  if (cluster_.info()->trafficStats()->upstream_cx_total_.used()) {
    // interval
  } else {
    // no_traffic interval
  }
```

If the case A is applied, it means no_traffic interval won't be used anymore once a request is routed to the endpoint. Buf if the case B is applied, it means health check will use no_traffic interval as long as `upstream_cx_total` become 0.

**Comment by botengyao** [comment]
Right, `upstream_cx_total` will always increase as a counter, and I don't find it is latched anywhere. So case A is right, and you are right for health check no_traffic interval.
