### ISSUE TITLE
The dns_qurey_timeout (DynamicForwardProxy.DnsCacheConfig) timer firing early

### ISSUE THREAD

**Issue by vermajit** [envoyproxy/envoy#30853]
**Envoy Version: v1.27**

We are seeing a weird behavior wrt **dns_query_timeout** in DynamicForwardProxy DnsCacheConfig. 
The timeout value is set to 5s (have used both the default and have also tried setting it explicitly) 

We see following pattern across pods and environments
1) Entry not in cache - DNS query fires up (in the code I can also see a timeout timer getting enabled)
2) **Timeout timer fires almost immediately rather than after 5 seconds**
3) DNS query is cancelled, and an un-resolved DNS entry is added to cache
4) DNS refresh is attempted based on dns_refresh_rate config (5s in our case) and this time everything works as expected

We are seeing this behavior for all new entries not in the cache. Other timers in Envoy that we are aware of seems to be working fine (e.g. cache refresh, cache TTL etc.) 

Attaching a screenshot of the log
![dns-new](https://github.com/envoyproxy/envoy/assets/41348210/f3a6e1f2-ec82-44da-bb70-8ab3b53bc6f9)

**Comment by htuch** [comment]
@alyssawilk @RyanTheOptimist

**Comment by alyssawilk** [comment]
Hey sorry about the delay in responding.  Is this a consistent thing (timeout then resolve) or intermittent?  I've been unable to repro and looking at the code I'm at a bit of a loss.  Just sent a draft PR to log alarm timing in case that's the problem but I could definitely use more info for debugging.

**Comment by vermajit** [comment]
@alyssawilk Thanks for looking into this. This behavior is consistent in our setup. We have been investigating this on our end and have some more context now. 

We have two different setups. We see this problem in one of the setups but not in other.  

### Static Setup (Problem not seen/reproducible here)

Very simple setup. Static envoy config with 2 static listeners, with single filter chain per listener.  Filter chain in each listener is configured with dynamic fwd proxy filter.

For same amount and type of load as in other setup we do not see the DNS timer issue here.  

### Dynamic Setup (Problem is consistently reproducible here)

We have two dynamic listeners, each listener with thousands of filter chains (~10k ballpark). In this model each filter chain represents a tenant (in first setup the tenancy model is architected differently). We use LDS with FCOU to update the filter chains whenever a tenant's config gets updated. The entire listener is resupplied even if just one filter chain had any change (The DeltaDiscoveryResponse message size runs into couple hundred megabytes in this case).  Envoy takes minutes to apply any update. 

It is in this case that we see the DNS timeout issue. 

Upon revisiting the logs, we noticed another useful pattern. From screen shot pasted above we see
1) 19:57:39 - cache miss for host (worker thread 82)
2) 19:57:51 - starting main thread resolve (main thread)
3) 19:57:51 - resolution timeout (main thread)

There is 12 second gap between (1) and (2) indicating heavy main thread contention. Could this cause the timer to mis-behave?
When does the timer start? Looking at the code it seems to start on (2) but am I reading the code, right? 
Or could this trigger some other race condition? 

We are aware of scale constraints of this setup but don't have a clear insight on how it is causing this observed DNS behavior.

**Comment by alyssawilk** [comment]
yeah if you have heavy thread contention I wouldn't trust any of these log timestamps - they're logged without flushing immediately so if there's actually a 10s delay in between 1 and 3 I'd assume the logs simply didn't flush in a timely fashion and there's actually a 5s delay between resolve start and resolution.
(you can force log flushing but AFIK that ends up being expensive which is why it's not done for debug and trace logs)

**Comment by vermajit** [comment]
@alyssawilk  Thanks for confirming. Makes sense now.  I was able to simulate this on our static setup as well by triggering a simple timer-based function on main thread that would put main thread to sleep for few secs.

**Comment by vermajit** [comment]
Are there existing metrics or signals any recommended method that would allow us to measure and track load or contention on main thread? 
In a running system what signals are available to inform me that main thread has not become the bottleneck ?

**Comment by alyssawilk** [comment]
not main thread specific but in general I'd look at loop duration https://www.envoyproxy.io/docs/envoy/latest/operations/performance which I think you need to compile on
