### ISSUE TITLE
Move http filter WASM onLog() from being triggered by log() to being trigger by onStreamComplete()

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#30859]
*Problem*
WASM doesn't support emitting dynamicMetadata in log time which can be consumed by AccessLogger. To fix that, we propose to move the http filter WASM onLog() from being triggered by log() to being trigger by onStreamComplete()

*Context*
- This is the current [execution flow](https://github.com/envoyproxy/envoy/blob/940a54b612595ee1cd4cc4e625ac914d8eb1f97e/envoy/http/filter.h#L773-L775) of HTTP filter so `log()` is followed by `onStreamComplete()`. 
- This is the [execution order](https://github.com/envoyproxy/envoy/issues/14767#issuecomment-766304699) of `AccessLog`s  so  accessLogger are put before http filters(inherited accessLog) within the accessLog execution order?
- Wasm doesn't inherit [onStreamComplete](https://github.com/envoyproxy/envoy/blob/940a54b612595ee1cd4cc4e625ac914d8eb1f97e/source/extensions/common/wasm/context.h)

Because of those,  wasm writes dynamicMetadata in onLog later than AccessLogger access dynamicMetadata

**Comment by TAOXUY** [comment]
@kyessenov @mpwarres @PiotrSikora

**Comment by spacewander** [comment]
So after this change, the time cost of the `onLog` will be accounted as the request process time?

**Comment by htuch** [comment]
This seems to be a breaking change for existing users, what's the impact likely to be?

**Comment by kyessenov** [comment]
@htuch `onStreamComplete` is called right before `log` so the impact on the filter itself is minimal. See https://github.com/envoyproxy/envoy/blob/180960108843f9867a4ec9a26533df5570cb9c99/source/common/http/conn_manager_impl.cc#L342. The main issue is with the data transfer between filters, e.g. if a Wasm filter was expecting some data from another filter, it may not get it if it is called earlier. If we need to support both the production and the consumption of data in `OnLog`, there is no other way to achieve without adding an ABI call - which is also a breaking change.

**Comment by TAOXUY** [comment]
> This seems to be a breaking change for existing users, what's the impact likely to be?

I think it should be backwards compatible and we basically move the onLog to OnStreamComplete. The wasm filter won't inherit AccessLog anymore.

**Comment by TAOXUY** [comment]
> So after this change, the time cost of the `onLog` will be accounted as the request process time?

No. It is after stream is finished.

**Comment by Elliot-xq** [comment]
I am working on this request.
