### ISSUE TITLE
golang filter: the case of header name should be unified

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#30861]
## Background

Currently, the header API treats header as case sensitive, which is different from the standard. For example:

With Go code:
```
	header.Set("Pet", "cat")

	lp, _ := header.Get("pet")
	up, _ := header.Get("Pet")
	return &api.LocalResponse{
		Msg: fmt.Sprintf("Pet: %s, pet: %s", up, lp),
	}
```

Hit it with the `curl http://127.0.0.1:10000 -H 'pet: dog'` will display `{"msg":"Pet: cat, pet: dog"}`.
However, according to the standard, both `up` and `lp` should be `cat`.

Therefore, we need to unify the case in the header API.

## Solution

We can unify the header to the lowercase. Since all the headers fetched from the Envoy is lowercase, we don't need to touch them during initing headers. What we need to do is to change the passed headers to lowercase if they are not, except the `GetRaw` API.

The alternative solution is to convert the headers into CanonicalMIMEHeaderKey format, which is used by Go. The advantage of the alternative solution is that we don't need to convert lowercase to CanonicalMIMEHeaderKey when we pass the header to `http.Header`. However, not all headers fetched from the Envoy will pass to `http.Header`.

CC @doujiang24

**Comment by doujiang24** [comment]
We use lowercase in the C++ side:
https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/source/golang_filter.cc#L695

The problem is: that we use the raw header in the Go side cache, in the `Set` API.

> What we need to do is to change the passed headers to lowercase if they are not

I think it's good to do it in the `Set` API.
But I'm not sure about always lowercase in the `Get` API, a little worried about the performance, maybe some benchmark results could help us.
I prefer to lowercase in the `Get` API too, when the performance cost is low enough.

**Comment by spacewander** [comment]
> But I'm not sure about always lowercase in the Get API, a little worried about the performance, maybe some benchmark results could help us.

It seems the developer can specify a lowercase name by herself, but it doesn't.
For example, Consider there is a plugin that allows the user to configure a header name to fetch a credential. To always ensure the name is lowercase, the developer needs to either

"force the user to use the lowercase name when validating the configuration"

or

"do the lowercase before passing the header to the `GET` API".

Both solutions require the developer to write extra code, which is caused by our violation of the HTTP standard.

 It would be worse if the developer think this behavior is guaranteed by us and doesn't do the lowercase by herself. This assumption is reasonable because the Go standard library already provides the guarantee.

Go will use CanonicalMIMEHeaderKey to ensure the header name is case-insensitive:
https://github.com/golang/go/blob/12051f7d95ef6e97d1be0cab8a3583ad38ec1dcd/src/net/textproto/header.go#L34

It will a pitfall if we don't obey the HTTP standard and the Go's default behavior.

>  What we need to do is to change the passed headers to lowercase if they are not, except the GetRaw API.

If the developer needs better performance, they can use `GetRaw`, just like accessing the Go header map directly.

**Comment by doujiang24** [comment]
Okay, let's always lowercase the header name.

```
BenchmarkStrFooBar-12           30421788                33.32 ns/op
BenchmarkStrFooBarFooBar-12     22582392                52.81 ns/op
BenchmarkStrfoobar-12           160176190                7.261 ns/op
BenchmarkStrfoobarfoobar-12     100000000               11.80 ns/op
```
And, here is a simple benchmark result, it's fast when strings are already lowercase.

**Comment by spacewander** [comment]
> Okay, let's always lowercase the header name.
> 
> ```
> BenchmarkStrFooBar-12           30421788                33.32 ns/op
> BenchmarkStrFooBarFooBar-12     22582392                52.81 ns/op
> BenchmarkStrfoobar-12           160176190                7.261 ns/op
> BenchmarkStrfoobarfoobar-12     100000000               11.80 ns/op
> ```
> 
> And, here is a simple benchmark result, it's fast when strings are already lowercase.

Great! I will submit a PR later.
