### ISSUE TITLE
Why missing origin is a request invalid on envoy CSRF Filter?

### ISSUE THREAD

**Issue by carloosamarante** [envoyproxy/envoy#30877]
*Title*: Why missing origin is a request invalid on envoy CSRF Filter?

*Description*:
Hello everyone,
I'm a little confused about blocking requests that have "missing origin" on the envoy CSRF filter. I did some tests to understand the process of when the origin is null and when the missing origin metric count occurs. And looking at the browser context, as by default it sets the origin, if the origin is not filled, it will come up as null, and in this case, I understand that it should be blocked (it doesn't even count as missing origin). Now when we make a manipulated request without passing the origin field, then it counts as missing origin and counts as an invalid request too. My doubt is, as CSRF is a vulnerability that occurs through the victim's browser, the origin field will always exist, even if it is null, so it would not be included in the case of missing origin. Does it make sense to block requests with missing origin? Or am I forgetting something?

*Relevant Links*:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/csrf/csrf_filter.cc#L104-L107

**Comment by htuch** [comment]
@wbpcode @daixiang0

**Comment by carloosamarante** [comment]
Hi guys, any thoughts about this situation?

**Comment by daixiang0** [comment]
Please check https://github.com/envoyproxy/envoy/commit/f84dd5c40e4d225d3ab1068671098d94bd61aadc, I do not know more.

**Comment by carloosamarante** [comment]
Thanks for the reply @daixiang0.

@rgs1 Could you help us with this doubt?

**Comment by rgs1** [comment]
> Now when we make a manipulated request without passing the origin field

Can you describe this use case a bit more? It sounds like you are suggesting that's a legit case outside the browser, but CSRF is for in-browser path so maybe you have to skip this filter for certain requests?

**Comment by carloosamarante** [comment]
Sure! In my scenario, I'm thinking about the endpoint receiving requests from:  another external server, mobile client, and browser client. By always expecting the origin, the two first cases would be denied.
(The manipulated requests that I did it was just to simulate the first case)

**Comment by carloosamarante** [comment]
Hi @rgs1 any thoughts about it?

> Sure! In my scenario, I'm thinking about the endpoint receiving requests from: another external server, mobile client, and browser client. By always expecting the origin, the two first cases would be denied. (The manipulated requests that I did it was just to simulate the first case)
