### ISSUE TITLE
Respect accept header in gRPC-JSON transcoder

### ISSUE THREAD

**Issue by gigi** [envoyproxy/envoy#30888]
*Title*: *gRPC-JSON transcoder ignores accept header*

*Description*:
Hi,
We aim to utilize the gRPC-JSON transcoder to offer a REST API to our clients. Our preference is to use protobuf as the serialization format rather than JSON. While it operates with the Content-Type: application/x-protobuf header, the response consistently appears as JSON. Is there a way to instruct the gRPC-JSON transcoder to return proto binary when the Accept: application/x-protobuf header is provided?

Thank you.

**Comment by htuch** [comment]
@nareddyt @lizan

**Comment by nareddyt** [comment]
Can you provide sample requests/responses you see?

gRPC JSON transcoder is really meant to transcode JSON requests. We've never tested with protobuf as the request/response format, and IMO is outside the scope of the extension.

BTW gRPC is just protobuf with a body frame prefix + headers + trailers. If you need protobuf responses, why not just chop off the frame from the gRPC body data?

Ref: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

> Response → (Response-Headers *Length-Prefixed-Message Trailers) / Trailers-Only
> Length-Prefixed-Message → Compressed-Flag Message-Length Message

**Comment by gigi** [comment]
Im trying to 

Here is demo.proto rpc:
```proto
service DemoV1Service {
  rpc Ping(PingRequest) returns (PingResponse) {
    option (google.api.http) = {post: "/demo/v1/ping"};
  }
...
}
```

Here is curl command
```bash
curl -v -X POST -H "Content-Type: application/x-protobuf" -H "Accept: application/x-protobuf" http://localhost:9090/demo/v1/ping
*   Trying 127.0.0.1:9090...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /demo/v1/ping HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/8.1.2
> Content-Type: application/x-protobuf
> Accept: application/x-protobuf
> 
< HTTP/1.1 200 OK
< content-type: application/json
< grpc-accept-encoding: identity,deflate,gzip
< grpc-encoding: identity
< date: Tue, 21 Nov 2023 09:08:27 GMT
< x-envoy-upstream-service-time: 5
< grpc-status: 0
< grpc-message: OK
< content-length: 62
< server: envoy
< 
{
 "timestamp": "2023-11-21T09:08:27.782Z",
 "pong": "pong"
}
* Connection #0 to host localhost left intact
```
> If you need protobuf responses, why not just chop off the frame from the gRPC body data?

Who should chop in this case? Every client, server, gateway? And how to `google.api.http` should work in this case?

Thanks
