### ISSUE TITLE
What does max_pending_requests mean for non-HTTP traffic

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#30890]
I'm learning how to use CircuitBreaker in Envoy.

I just read the doc and I found two configs:

> max_connections
> ([UInt32Value](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#uint32value)) The maximum number of connections that Envoy will make to the upstream cluster. If not specified, the default is 1024.
> 
> max_pending_requests
> ([UInt32Value](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#uint32value)) The maximum number of pending requests that Envoy will allow to the upstream cluster. If not specified, the default is 1024. This limit is applied as a connection limit for non-HTTP traffic.

I just can't understand what "This limit is applied as a connection limit for non-HTTP traffic." means.

For HTTP traffic, `max_pending_requests` means that "The maximum number of pending requests that Envoy will allow to the upstream cluster.", right?

But for non-HTTP traffic, it says "as a connection limit". Now I'm confused.

If `max_pending_requests` is a connection limit for non-HTTP traffic, then what does `max_connections` mean for non-HTTP traffic. Are they the same for non-HTTP traffic?

**Comment by cpakulski** [comment]
> This limit is applied as a connection limit for non-HTTP traffic.

Based on my experiments I think that this is not what happens. But `max_connections` and `max_pending_requests` are somehow related.

I have a test setup where `max_connections` is 10 and `max_pending_requests` is 3. (notice that `max_connections` is larger than `max_pending_requests`). In practice it means that a cluster may have maximum 10 TCP sessions opened at any given time. `max_pending_requests` defines that max 3 sessions may "wait" for upstream connection. "pending" is a transitory state and once upstream handshake completes, a "pending" request becomes a connection.

In the second test, I had `max_connections` set to 3 and `max_pending_requests` set to 10. In this case I was never able to queue more than 3 pending requests. It seems that when a new session is queued as pending request, it is also counted as connection. So in practice `max_pending_requests` is `min(max_pending_requests, max_connections)`. 

I will double check the logic in the code and update documentation. Thanks for catching it!

**Comment by htuch** [comment]
@alyssawilk

**Comment by alyssawilk** [comment]
I believe max_pending_requests becomes max_pending_connections, limiting the number of not-yet-established connections separately from max_connections

**Comment by cpakulski** [comment]
@alyssawilk I cannot find `max_pending_connections` in the code or in api.

After tracing under gdb the logic for TCP conn pool seems to be:
- check if number of connections in the cluster is lower than max_connections
- if yes, create connection pool. Check number of pending requests is lower than `max_pending_requests`
- if yes, call TcpActiveClient which increments max_connections counter: https://github.com/envoyproxy/envoy/blob/main/source/common/conn_pool/conn_pool_base.cc#L775
