### ISSUE TITLE
Build Error in Mac Sonoma

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#30917]
Generating upb protos for :httpbody_proto failed: (Exit 1): protoc.exe failed: error executing command (from target @com_google_googleapis//google/api:httpbody_proto) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/com_google_protobuf_protoc_osx_aarch_64/protoc.exe '--upbdefs_out=bazel-out/darwin_arm64-fastbuild/bin/external/com_google_googleapis/' ... (remaining 3 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
**dyld[1559]: symbol not found in flat namespace '_CFRelease'**
--upbdefs_out: protoc-gen-upbdefs: Plugin killed by signal 6.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.745s, Critical Path: 0.33s
INFO: 9 processes: 9 internal.

Has any one seen this error on Mac Sonoma(14.1.1) ?

**Comment by htuch** [comment]
@ggreenway

**Comment by ggreenway** [comment]
Builds for me; not sure what the issue is.

**Comment by ramaraochavali** [comment]
what protoc and xcode version s are you using?

**Comment by ramaraochavali** [comment]
@keith @phlax do you have idea by any chance?

**Comment by ramaraochavali** [comment]
Nevermind. Upgrading Xcode fixed the issue.
