### ISSUE TITLE
Lua: Lua support cluster specifier extension

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#30913]
*Title*: *Lua support cluster specifier extension*

*Description*:
Lua support cluster specifier plugin extension to enable selecting cluster dynamically by lua code.

and why we need a new lua cluster specifier plugin instead of lua HTTP filter:

https://github.com/envoyproxy/envoy/pull/31034#issuecomment-1831116876

**Comment by StarryVae** [comment]
please help to check if this feature is valuable cc @wbpcode @mattklein123 , i can try to contribute this, thanks.

**Comment by StarryVae** [comment]
I think it is a distinct cluster specifier extension.

**Comment by htuch** [comment]
I don't think we ever implemented this for C++ extensions, so you'd need to start with that. CC @markdroth .

**Comment by markdroth** [comment]
I assume that we're talking about the [`RouteAction.cluster_specifier_plugin` field](https://github.com/envoyproxy/envoy/blob/a665198afc25215fc0c9faba43feccfec93bd437/api/envoy/config/route/v3/route_components.proto#L1059)?  If so, then I think that's correct -- Envoy does not currently support this extension even in C++.

There were a bunch of folks at Google talking about potentially implementing this.  @pianiststickman may have more info.

**Comment by wbpcode** [comment]
This extension point is supported and we have a contrib implementation now. (Golang)

**Comment by StarryVae** [comment]
yes, router cluster specifier has been supported in c++ and golang, i will try to support it in lua.
