### ISSUE TITLE
kafka request rewriter support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#30949]
*Title*: *kafka request rewriter support*

Current kafka broker extension provide the ability to modify response on demand. But in some scenario, request modification may also necessary.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
@adamkotwasinski

**Comment by adamkotwasinski** [comment]
Yeah my first idea is to add "namespace" support for requests i.e. people using proxy fleet to access kafka who are using topic `topic` are really using `prefix.topic`. With rewriter support and multiple proxy fleets we could then separate multiple usecases.
This is just an example! Another idea is compressing payloads or adding headers. 
I'll try to have a look after February (I'll be pretty busy around January).

/assign @adamkotwasinski
