### ISSUE TITLE
kafka: extended rewriter support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#30950]
*Title*: *[One line description](kafka: extended rewriter support)*

Current kafka rewriter is hard coded and be controlled by specific fields in the kafka broker. It would be great to create a new extension point to support custom rewriters that could work like a L7 filter.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
cc @adamkotwasinski

**Comment by adamkotwasinski** [comment]
@wbpcode Yeah, that's an excellent idea - I think HTTP filters are doing something like that, so it could be done. This feature would link to both request & rewrite because sometimes with requests we want to do both ways (e.g. prefix a topic with name).

/assign @adamkotwasinski
