### ISSUE TITLE
Hash+mod header matching

### ISSUE THREAD

**Issue by PapaCharlie** [envoyproxy/envoy#30962]
*Title*: hashing + modding for header matching

*Description*:
There are a number of options for header matching but one that seems to be missing is matching based on the hash of the header's contents. Such matching could be used to implement partitioning as an alternative to the existing [`range_match`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L2257) which would evenly but deterministically distribute traffic between partitions.

The required fields to expose such an API would be the following:
```proto
message HashMatcher {
  // The hash algorithm to use when hashing the header's value
  enum HashAlgorithm {
    CRC32 = 1;
    FNV1A = 2;
    ...
  }

  // Allows changing how the header is interpreted. If ommitted, the default
  // behavior should be to pick a default HashAlgorithm and treat the header
  // as a string
  oneof header_type {
    // If specified, the entire header will be treated as a string and hash
    // with the given algorithm.
    HashAlgorithm string_algorithm = 1;
    // If specified, the header will only be matched if represents an integer
    //  in base 10 notation (like IntRange).
    HashAlgorithm int_algorithm = 2;
  }

  // The computed hash will be modded by this value this when matching.
  int modulus = 2;

  // This matcher will only match if the result of hashing and modding the
  // header matches this value.
  int match = 3;
}
```
Introducing such an API in a generic way means clients do not need to compute the partition themselves. It is important to make this transparent to the client as they may not know they are talking to a partitioned service, how many partitions there are, or which hashing algorithm to use etc... However, it should be clear exactly which algorithm Envoy is using to make sure that it can be deterministically recalculated offline. That way, when the data is partitioned it can be partitioned in the same way requests are routed.

In the future, this API could be extended with a regex to extract a substring of the header before hashing.

**Comment by KBaichoo** [comment]
cc @kyessenov @zuercher

**Comment by PapaCharlie** [comment]
Hey folks, I was wondering if I can help this proposal in any way, maybe in terms of implementing anything or opening a PR? This is something that's blocking the migration to Envoy for LinkedIn as we need it to replace the existing service discovery system, so we'd be very happy to help or contribute whatever's necessary to see this through to the end. At the very least, it'd be nice to come to an agreement on what the new `HeaderMatcher` API should look like. This way the conversation can also be opened with the gRPC team as soon as possible while work on the implementation for Envoy gets going.

**Comment by KBaichoo** [comment]
cc @yanavlasov @alyssawilk as well

**Comment by PapaCharlie** [comment]
ACK makes sense! Happy to help with the implementation. Before I jump in though, I do want to get at least a rough 👍 on the new API? What do you think, does it make sense?

**Comment by alyssawilk** [comment]
Honestly the best way to get traction is to send out a PR - this sort of thing is reviewed by API shephards so you could just do a PR with TODO: implement, and get your API shephard review stamp then implement the code.
