### ISSUE TITLE
opentelemetry tracer: Move to `alpha` stability?

### ISSUE THREAD

**Issue by joaopgrassi** [envoyproxy/envoy#30976]
*Title*: *What is the process to move an extension out of `wip` stability*

*Description*:

The OpenTelemetry tracer is been present in Envoy for over a year (#20281) and I was wondering what is required/process to move it towards `alpha` and at some point to `stable`. Same goes to the security posture, which today is `unknown`. 

I tried looking it up, but apart from the [extension policy](https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md), I didn't find much.

**Comment by zirain** [comment]
+1 for this

**Comment by KBaichoo** [comment]
cc @htuch as codeowner for what's the missing gaps in otel to be marked stable.

**Comment by htuch** [comment]
@joaopgrassi do you have thoughts on https://github.com/envoyproxy/envoy/issues/30976#issuecomment-1821238490?

**Comment by joaopgrassi** [comment]
I just saw there's already an issue for this #24672. Since there's quite some discussion there, I think it's best to close this and continue there.
