### ISSUE TITLE
What will be overridden by retry_budget in config.cluster.v3.CircuitBreakers.Thresholds

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#30974]
I'm reading the doc about the circuit breaker: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto.html#envoy-v3-api-msg-config-cluster-v3-circuitbreakers-thresholds

There is a note for `retry_budget`:

> If this field is set, the retry budget will override any configured retry circuit breaker.

I can't understand what it means. What will be overridden exactly?

**Comment by KBaichoo** [comment]
I think this this refers to 
> max_retries:
([UInt32Value](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#uint32value)) The maximum number of parallel retries that Envoy will allow to the upstream cluster. If not specified, the default is 3.

See original PR: https://github.com/envoyproxy/envoy/pull/9069.
