### ISSUE TITLE
Start logging on Retry

### ISSUE THREAD

**Issue by himanshuz2** [envoyproxy/envoy#30984]
I need help with this question.

I want to be able to configure logging such that request and response headers and body are logged if the first try call to upstream is not successful.  

I looked at the options under Access Logging and Tap I don't want to log all requests and response and I don't want to invoke tap from Admin.

If it is possible to invoke a web hook or gRPC when an error is returned by upstream and send the request and response to that gRPC/Webhook.

**Comment by KBaichoo** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
I don't think that hook exists but it's not a bad one to add
