### ISSUE TITLE
How to configure a retry policy when the service is unavailable when envoy uses External Authorization

### ISSUE THREAD

**Issue by zzjjian** [envoyproxy/envoy#30985]
Envoy may occasionally experience service unavailability when using extended external authentication services (grpc status code is 14)
I checked the GrpcService_EnvoyGrpc_ config and the cluster level config, not found the retry policy for grpc request(GrpcService_EnvoyGrpc_  only support retry policy for xds).

If not support retry policy for external authentication service,  have any other suggestions to reduce the issue of unavailability of service

**Comment by tyxia** [comment]
@zzjjian  Can you try `envoy::config::core::v3::RetryPolicy`?

Will something similar to [this]( https://github.com/envoyproxy/envoy/blob/e829b9ab789dbacc8e3a4b7a5bd3f899de20093e/source/extensions/access_loggers/common/grpc_access_logger.h#L97) works for you in EnvoyGrpc
