### ISSUE TITLE
How to use Hazelcast Cache Plugin

### ISSUE THREAD

**Issue by himanshuz2** [envoyproxy/envoy#30997]
This is merged but I can't find a practical envoy configuration for implementing a Cache Plugin other than the file system cache plugin.

**Comment by KBaichoo** [comment]
Hi, this feature is not merged AFAIK (https://github.com/enozcan/hazelcast-envoy-http-cache). It might be better to ask in the repo above about usage.

**Comment by himanshuz2** [comment]
Thanks, I will put this question in the issues of the above repo.
