### ISSUE TITLE
Little traffic being sent to non active lb_endpoint

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/envoy#30998]
*Title*: *Little traffic being sent to non active lb_endpoint*

*Description*:
Hello Envoy Team!

I'm using envoy version 1.27.1 and I am having a strange behaviour.

I have a cluster wirh 2 lb_endpoints, one is with priority equals to 0 and another equals to 1, with that in mind I think 100% of all HTTP request should go to the endpoint with the lower priority and the other one should be used as a fallback in case for instance a health check fails for the endpoint with the lower priority.

I am scrapping the metrics generated by envoy and plotting it in Grafana. Sometimes the endpoint with the high priority receives some requests and I cannot see any sign of unhealthy action. For instance, for the total of 30k requests in the active endpoints 2 requests go to the fallback endpoint. I'm having trouble to identify why envoy is sending requests for something that is 100% healthy all the time.

I'm running the app in kubernetes (aws eks) and the outlier dectection is disabled so I only have active healthchecking. In the front I have a AWS Elastic Load Balancer.

What could be possible scenarios where Envoy sends traffic to inactive endpoints?

If you need anymore info please reach me and thanks a lot for your time!

**Comment by KBaichoo** [comment]
I'm running the app in kubernetes (aws eks) and the outlier dectection is disabled so I only have active healthchecking. In the front I have a AWS Elastic Load Balancer.
> Is the traffic you're setting at the fallback health check traffic or application traffic?

**Comment by leandrocurioso** [comment]
Application traffic.

**Comment by leandrocurioso** [comment]
I think that can be something related do the DNS resolution.

By the way  we are using STRICT_DNS and as mentioned here:
[service_discovery#arch-overview-service-discovery-types-strict-dns](https://www.envoyproxy.io/docs/envoy/v1.27.2/intro/arch_overview/upstream/service_discovery#arch-overview-service-discovery-types-strict-dns)

"If multiple DNS names resolve to the same IP, health checking will not be shared. This means that care should be taken if active health checking is used with DNS names that resolve to the same IPs: if an IP is repeated many times between DNS names it might cause undue load on the upstream host."

Maybe when the elastic balancer is being scaled AWS behind the scenes AWS  do something with the IP list from for the balancer DNS. 

Until envoy do another DNS resolution some traffic will be sent to non active endpoint. What happens inside AWS is a total black box for us.

Any thoughts about it?

**Comment by leandrocurioso** [comment]
@cpakulski 

Sorry to bother you again man, but do you have any insights about what I detailed above? Also if you are not the expert about that part, do you know anyone who could give me some thoughts about it?

This is super critical to me because we are running envoy in a application with avg 20k tps and the stakeholders are not happy to see traffic in a endpoint that is inot supposed to receive load. (active and passive health check are not setting as unhealthy)

**Comment by cpakulski** [comment]
How many IP addresses are involved here in total (across 2 priorities)?

Since you noted that you use DNS, it would be helpful to check if a fallback endpoint does not become active endpoint for a short time? Or maybe during update priority zero becomes empty for a short time and traffic shifts to priority 1 for that short time. I do not know, just guessing. Can you monitor Envoy's clusters: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-clusters
and maybe something pops up there.
What load balancer type is used in those clusters?

**Comment by leandrocurioso** [comment]
@cpakulski Thanks for reaching out!

We are using AWS ALB Ok I will monitor the /clusters. Is there anything in particular that I should look?

**Comment by cpakulski** [comment]
I think that sending traffic to fallback IPs happens during transitory state (maybe when DNS refresh happens) which lasts for a short time. I am guessing. What is rate of your requests? Those few requests which go to fallback IPs, what percentage of total traffic do they represent? Can you find out if there is any regularity when traffic goes to fallback IP?, say every X number of secs?

**Comment by leandrocurioso** [comment]
@cpakulski 

I have in average 20k TPS and less then 1% is going to the fallback. Let's say 3 only three requests. (super little)

What we could notice is that when the traffic is high, AWS scale out and in the ALB and these requests being sent to the fallback happen at this moment.

Is not tied to time interval is more like high peaks of traffic.
