### ISSUE TITLE
Regarding making libenvoyapi.so using envoy api and envoy api dependencies of envoy 1.26.4

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#30993]
I want to make libenvoyapi.so using envoy api and envoy api dependencies which are mentioned in below dependency page
https://www.envoyproxy.io/docs/envoy/v1.17.4/intro/arch_overview/security/external_deps.

Please help me in making this libenvoyapi.so. I will load this libenvoyapi.so into my executable

**Comment by KBaichoo** [comment]
cc @phlax

**Comment by phlax** [comment]
the linked version has not been supported for some time

wrt building a `.so` from envoy - that is not something im aware of an existing build pattern for - but if you figure it out please do post back here

**Comment by phlax** [comment]
(i guess it would be related/determined to/by the app you were building for etc)
