### ISSUE TITLE
Design Proposal: Add SigV4A signing to AWS Request Signing extension

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#31000]
*Title*: *Add SigV4A signing to AWS Request Signing extension*

*Description*:
Short proposal to incorporate SigV4A signing in the AWS Request Signing extension.

This extension currently supports SigV4 only.

The proposal would be to extend the signing extension to support SigV4A. This would require the following changes:
- Addition of an optional flag 'signing_algorithm'. This would default to aws_sigv4 for backwards compatibility, but allow selection of aws_sigv4a
- Addition of sigv4a key derivation code, based on (but not dependent upon) https://github.com/awslabs/aws-c-auth/blob/main/source/key_derivation.c
- Modification of the signing process to add a path for SigV4A signature generation

I believe it 'should' be possible to reuse existing ECDSA libraries in the envoy code base for the actual asymmetric signature creation. 

This provides the ability for envoy to generate region independent signatures, removing the need for hardcoding of region strings into the signing algorithm. This then allows for more consistent envoy configurations across regions and transparent failover to downstream AWS endpoints.

@suniltheta @mattklein123

**Comment by suniltheta** [comment]
Is this a drop in replacement for SigV4 where it would enhance the security posture, assuming no change on authorization service? Or it should be an opt-in feature that Envoy users should choose to enable?

**Comment by nbaws** [comment]
SigV4 would still be supported natively and the default, just that SigV4A would now be an option. SigV4A allows you to specify wildcarded region strings and will be accepted by any SigV4A supported AWS endpoint. Therefore the same envoy proxy configuration could be used in any region with SigV4A supported services, but also the user could transparently fail between regions downstream with the envoy configuration remaining non-region specific.

**Comment by mattklein123** [comment]
Sure sounds great to me!

**Comment by suniltheta** [comment]
Matt, Can you help include help wanted tag? so that this won't be closed by stalebot.

**Comment by nbaws** [comment]
code complete, PR is pending some additional test cases

**Comment by nbaws** [comment]
code complete
