### ISSUE TITLE
What is the behavior of retry_policy by default

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31003]
I'm reading the doc about retry_policy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-virtualhost-retry-policy

I don't know what the behavior of retry_policy is. If I don't configure `retry_policy` explicitly, what would happen? Is it that no retry gonna happen, or that some retry policy by default gonna be applied? If there is some retry_policy by default, how can I disable it (never retry)?

**Comment by KBaichoo** [comment]
If I don't configure retry_policy explicitly, what would happen? Is it that no retry gonna happen, or that some retry policy by default gonna be applied?
> I think it's no retry by default unless configured.

See also: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#arch-overview-http-routing-retry for more details.
