### ISSUE TITLE
Active connections not coming down in envoy

### ISSUE THREAD

**Issue by Harif-Rahman** [envoyproxy/envoy#31011]
*Title*: *Envoy cx active connection is not coming down eventhough the request rate is normal*
*Description*:
Envoy version :1.25.0
We are using enovy as side car proxy we have configured the below clusters.

  listener :  
    - name: freno_listener
      enable_reuse_port: false
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8189
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http_freno
            tracing:
              client_sampling:
                value: 100
              random_sampling:
                value: 0
              overall_sampling:
                value: 100
            route_config:
              name: freno
              virtual_hosts:
              - name: freno_service
                domains: ["*"]
                routes:
                - match: { prefix: "/" }
                  route:
                    cluster: freno
                    auto_host_rewrite: true
                    timeout: 0.2s
                    retry_policy:
                      retry_on: 5xx
                      num_retries: 3
                      per_try_timeout: 0.05s
            http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                dynamic_stats: true
                start_child_span: true

   - name: freno
      connect_timeout: 0.2s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      dns_lookup_family: V4_ONLY
      common_lb_config: { healthy_panic_threshold: { value: 0 } }
# All the criteria below will be evaluated for each request and the connection
#   will be opened when any one of the conditions below matches
      circuit_breakers:
        thresholds:
        - max_retries: 3
          track_remaining: true
          max_connections: 40
          max_pending_requests: 40
# Host returning consecutive errors will be ejected and will be brought back
#   after the ejection time calculated based on the number of failures
      outlier_detection:
        base_ejection_time: 3s
        split_external_local_origin_errors: true
        consecutive_local_origin_failure: 10
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 5
          keepalive_interval: 5
          keepalive_time: 300
      health_checks:
         timeout: 0.05s
         interval: 60s
         unhealthy_threshold: 1
         healthy_threshold: 1
         http_health_check:
           path: "/leader-check"
      load_assignment:
        cluster_name: freno
        endpoints:
          - lb_endpoints:
            - endpoint:
                health_check_config:
                  port_value: "8189"
                address:
                  socket_address:
                    address: "frenoeks-blue.freshdesk.internal"
                    port_value: "8189"
            - endpoint:
                health_check_config:
                  port_value: "8189"
                address:
                  socket_address:
                    address: "frenoeks-green.freshdesk.internal"
                    port_value: "8189"

<img width="1545" alt="image" src="https://github.com/envoyproxy/envoy/assets/48013254/4c8fdd9c-8c4e-4106-825f-b61a39a013b0">

<img width="1621" alt="image" src="https://github.com/envoyproxy/envoy/assets/48013254/ff931ffe-80b9-4c33-a784-762cf991bd07">

Questions:

1) I need to understand why the cx_active connection is not coming down even when the request rate is very normal.
2) We are observing the cx_active crossing the circuit breaker max connection even though the request rate is very normal.
3) Also the cx_open for the freno cluster is open when it crosses the max connection of 40 and we are not observing any 503 even though the circuit breaker is open.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yanavlasov** [comment]
Envoy keeps connections to the upstream hosts open so they can be reused for future requests. These connections are closed when either an idle or connection timeouts occur.

**Comment by Harif-Rahman** [comment]
I agree that connections will not come down immediately and also we found an issue where one of the endpoint ip is mapped to other layer which shouldnt be routed and we are going to fix that .
But eventhough the circuit breaker is open why i am getting 2xx?

**Comment by yanavlasov** [comment]
You also have maximum of 40 pending requests. It is likely that you did not exceed this threshold.

**Comment by Harif-Rahman** [comment]
I understand that the request can be in pending state but in this case why the circuit breaker is open (cx_active= 1) ?

**Comment by Harif-Rahman** [comment]
My bad sry it was cx_open=1, even though the circuit breaker is open why i am getting 2xx?
