### ISSUE TITLE
HTTP2 SETTINGS parameter handling

### ISSUE THREAD

**Issue by BenPope** [envoyproxy/envoy#3101]
*Description*:
I noticed that setting `max_concurrent_streams` doesn't always seem to work.  The problem seems to stem from checking whether to add the parameter to the frame based on whether the parameter is default (`2^32-1`) or not.  However, the other end of the connection may not be aware of envoys default and its own may not be the same.  Setting the value explicitly in the configuration to `2^32-1` doesn't help either.  I've resorted to setting the value to `2^32-2`.

I spotted the problem specifically when setting `envoy.http_connection_manager.http2_protocol_options.max_concurrent_streams`, the parameter isn't sent in the `SETTINGS` frame if it is left to default or explicitly set to the default value.

It may be better to always send the parameter.  I'm not sure what are the implications on the ack for the `SETTINGS` frame.

I don't know if the problem is limited to `max_concurrent_streams`.

[*Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/1255ac81f6af588a4f0d7daa03e1b9cd8a330130/source/common/http/http2/codec_impl.cc#L607

**Comment by mattklein123** [comment]
@BenPope I came to the same conclusion as part of https://github.com/envoyproxy/envoy/issues/3076. (This is a more succinct description of one of the issues.) If you want to keep this open to track that's fine otherwise we can just use https://github.com/envoyproxy/envoy/issues/3076 to track.

**Comment by BenPope** [comment]
Happy to mark as duplicate.  FYI, go uses ~1000 concurrent streams by default.

Dupe: #3076
