### ISSUE TITLE
add connectionPoolCallbackLatency to access log

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#31013]
*Title*: *add connectionPoolCallbackLatency to access log*

*Description*:
> `connectionPoolCallbackLatency` has been recorded here https://github.com/envoyproxy/envoy/blob/2de016d1007aabff202220b8177167c9ab3e8c6a/source/common/router/upstream_request.cc#L569
, and i want to add it to access log to know the upstream pending time of a request when connections are not available in time.

**Comment by KBaichoo** [comment]
This would be a great enhancement.

**Comment by StarryVae** [comment]
yeah and i will submit a pr thanks.
