### ISSUE TITLE
Print upstream response in debug logs

### ISSUE THREAD

**Issue by nemethloci** [envoyproxy/envoy#31010]
*Title*: *Print upstream response in debug logs*

*Description*:

When debugging is turned on, Envoy is printing the downstream request and response and also the upstream request, but not the upstream response. In order to help debugging (ie: in case an invalid header is returned by the upstream) this would help a lot.

**Comment by sgovinda-ub** [comment]
@nemethloci  Can you please assign this to me.

**Comment by nemethloci** [comment]
@sgovinda-ub: sorry, but I don't seem to have the permission to assign tickets.

**Comment by nemethloci** [comment]
@sgovinda-ub : have you ever made any progress with this?
