### ISSUE TITLE
Can we limit the length of access log

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31028]
We can set the format of the access log of Envoy. The default format is
```
[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
%RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
"%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n
```

In my case, `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%` could be very long. If I don't want to store the complete log, is there some way to do so?

For example, the complete `%REQ(:PATH)%` could be `/example/xxx?a=b&c=d&e=f&g=h`, but I only want to store `/example/xxx?` in my log file.

**Comment by KBaichoo** [comment]
I think you may be able to limit it by doing something like: `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH):256%`

**Comment by suniltheta** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto Is this something that you would consider using?
