### ISSUE TITLE
Removing a path prefix with grpc_json_transcoder

### ISSUE THREAD

**Issue by lusayaa** [envoyproxy/envoy#31020]
I have a grpc service for which I'm using the [grpc_json_transcoder](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#extensions-filters-http-grpc-json-transcoder-v3-grpcjsontranscoder) and would like to route multiple path prefixes to the grpc service.

For simplicity, I'm starting out with the `helloworld.proto` example and the sample envoy config from the [documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#route-configs-for-transcoded-requests). When I call `localhost:51051/say?name=me`, it will route it to the grpc server correctly. 

I would like to be able to also call `localhost:51051/my_prefix/say?name=me` to that same service without changing the service proto.

What is the right way to go about this?

Since the grpc_json_transcoder expects the [grpc-like path](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#extensions-filters-http-grpc-json-transcoder-v3-grpcjsontranscoder) for non per-route configs,  I can't just add another `match: {prefix: "/my_prefix"}`.

I tried using a per-route config. However, that doesn't seem to apply the filter, but redirect/route right away:
```
admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9902}

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: {address: 0.0.0.0, port_value: 51051}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              # NOTE: by default, matching happens based on the gRPC route, and not on the incoming request path.
              # Reference: https://envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#route-configs-for-transcoded-requests
              - match: {prefix: "/my_prefix/say"}
                route: {cluster: grpc, timeout: 60s}
                typed_per_filter_config:
                  envoy.filters.http.grpc_json_transcoder:
                    "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder"
                    proto_descriptor: "protos/helloworld.pb"
                    services: ["helloworld.Greeter"]
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: false
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: grpc
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 50051
   ```

**Comment by StarryVae** [comment]
for the config above, `envoy.filters.http.grpc_json_transcoder` is not added to `http_filters`, so it will not go to this filter.
