### ISSUE TITLE
Is there some kind of priority between health check and outlier detection

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31037]
I've known how health check works independently and how outlier detection works independently. But if I configure both of them together, I don't know how they would work together.

If an endpoint is ejected by outlier detection but it is still marked healthy by health check, what would happen? Will it be marked unhealthy immediately in terms of health check? Will the requests of health check continue being sent to it? If it is marked unhealthy by outlier detection but is marked healthy by health check, what would happen?

If an ejected endpoint by outlier detection should rejoin into the cluster in terms of outlier detection but it is marked unhealthy by health check, what would happen? Does it mean that requests of downstream couldn't be routed to it until it is marked healthy? If so, it seems that the endpoint has to wait `max(outlier_detection.interval, health_check.interval * health_check.healthy_threshold)`?

In a word, both of outlier detection and health check can eject/rejoin an endpoint from/into a cluster, but I'm confused by them because as my understanding, they may make opposite decisions and they may set different time-relative configurations. In these cases, which mechanism has the higher priority?

In the doc https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier, it says,

> An ejected host will automatically be brought back into service after the ejection time has been satisfied. Generally, outlier detection is used alongside [active health checking](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking) for a comprehensive health checking solution.

But for me it's kind of hard to use them together...

**Comment by ramaraochavali** [comment]
https://www.envoyproxy.io/docs/envoy/v1.28.0/intro/arch_overview/upstream/outlier.html#grpc - If both are enabled, a successful health check will uneject the host - This is the the only dependency when both are enabled
