### ISSUE TITLE
MySQL filter generating wrong stats

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31039]
*Description*:
I was running [mysql filter sandbox](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/mysql#mysql-filter). Although the [commands run in the example](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/mysql#step-2-issue-commands-using-mysql) had no apparent error, the stats generated [here](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/mysql#step-3-check-egress-stats) have `mysql.egress_mysql.queries_parse_error: 2` . Can anyone tell me what it is like that? Is this a bug?

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/mysql_proxy_filter

**Comment by yanavlasov** [comment]
Adding code owners @rshriram @venilnoronha

**Comment by soulxu** [comment]
gentle ping @rshriram @venilnoronha
