### ISSUE TITLE
LocalReplyConfig: Remove the constraint that the filter field in ResponseMapper must be set

### ISSUE THREAD

**Issue by tmsnan** [envoyproxy/envoy#31035]
https://github.com/envoyproxy/envoy/blob/2de016d1007aabff202220b8177167c9ab3e8c6a/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L947

Currently, the `filter` field in Envoy must be set and matched, which poses challenges when attempting to modify all `localreply` . Hence, it is proposed to make the `filter` field optional, allowing for successful matching when the filter is not set.

**Comment by StarryVae** [comment]
https://github.com/envoyproxy/envoy/blob/2de016d1007aabff202220b8177167c9ab3e8c6a/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L947C55-L947C55

**Comment by StarryVae** [comment]
https://github.com/envoyproxy/envoy/blob/2de016d1007aabff202220b8177167c9ab3e8c6a/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L947
