### ISSUE TITLE
Error building an Envoy Docker image

### ISSUE THREAD

**Issue by BenAgai** [envoyproxy/envoy#31048]
Hi,
I wanted to test code modifications I made to envoy.
In order to build Envoy image I found the below guide:
https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build

Before following the guide with the code modifications, I first wanted to see that I can successfully build the newest tag of envoy (v1.28.0).
I cloned envoy repo, switched to v1.28.0 tag and followed the above guide.

I encountered the following error:
![envoy-build-error-1-28-0-tag](https://github.com/envoyproxy/envoy/assets/28253368/159117ad-afcd-4481-a920-549c11bb1070)

According to the guide the command should run as root but the error describes the root being the issue.
How can I proceed from here?

Thanks!

**Comment by suniltheta** [comment]
You might find this comment useful https://github.com/envoyproxy/envoy/issues/28670#issuecomment-1657185156

where you would update `./WORKSPACE` file to replace `envoy_dependencies_extra()` with `envoy_dependencies_extra(ignore_root_user_error=True)`

**Comment by BenAgai** [comment]
Hi @suniltheta ,
Thanks it solved the issue.

Will the above work around be part of the main code base?

**Comment by suniltheta** [comment]
It won't be. Envoy's recommendation is to build it as non-root user. So it is encouraged to setup your build system to run as non-root user.

**Comment by BenAgai** [comment]
I see, thanks.
@suniltheta , sorry to bother but I have another question.

According to the below guide, it is not clear how I can create a docker image of Envoy with costum tag:
https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build

Do  you know by any chance, how it can be done?
