### ISSUE TITLE
Question - how to regenerate protobufs after removal of generate_go_prototobuf.py?

### ISSUE THREAD

**Issue by VivekSubr** [envoyproxy/envoy#31044]
*Title*: *How to regenerate protobufs after removal of generate_go_prototobuf.py?*

*Description*:
tools/api/generate_go_prototobuf.py used to be a simple way to regenerate protobufs for envoy, but now it's been removed in favor of ci/do_ci.sh... but it doesn't seem to be equivalent?

I build envoy with 'bazel build envoy' and try to execute this script (ci/do_ci.sh api.go), and it exits with message "No go proto targets found'. 

Could someone provide a set of commands for regenerating all the protobufs?

**Comment by karlhjm** [comment]
> _Title_: _How to regenerate protobufs after removal of generate_go_prototobuf.py?_
> 
> _Description_: tools/api/generate_go_prototobuf.py used to be a simple way to regenerate protobufs for envoy, but now it's been removed in favor of ci/do_ci.sh... but it doesn't seem to be equivalent?
> 
> I build envoy with 'bazel build envoy' and try to execute this script (ci/do_ci.sh api.go), and it exits with message "No go proto targets found'.
> 
> Could someone provide a set of commands for regenerating all the protobufs?

@VivekSubr hello I meet the same problem, cannot regenerate protobufs , how did you solve it？

**Comment by VivekSubr** [comment]
@karlhjm - sorry karl, I just manually patched the generated code.

There's apparently a bazel target to regenerate the protobufs, but I don't know anything more
