### ISSUE TITLE
Dynamic warming cluster lasts about 75s

### ISSUE THREAD

**Issue by littlejiancc** [envoyproxy/envoy#31053]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

Dynamic warming cluster lasts about 75s

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

When I add service into envoy xDS server, the response is 503 NC. AND I found that it takes about 75s for the cluster to change from warming state to active state.

envoy build in docker

```
envoy --version
envoy  version: edd69583372955fdfa0b8ca3820dd7312c094e46/1.23.1/Clean/RELEASE/BoringSSL
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

```
...
"dynamic_warming_clusters": [
    {
     "version_info": "24",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "service-3g3aLod3tDPBXQD3626-align_flRrz7Xj6-dataProvider",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "lb_policy": "RING_HASH",
      "ring_hash_lb_config": {
       "hash_function": "MURMUR_HASH_2"
      },
      "load_assignment": {
       "cluster_name": "service-3g3aLod3tDPBXQD3626-align_flRrz7Xj6-dataProvider",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "11.64.0.5",
              "port_value": 42939
             }
            },
            "hostname": "11.64.0.5"
           }
          }
         ]
        }
       ]
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "explicit_http_config": {
         "http2_protocol_options": {
          "max_outbound_frames": 1000000
         }
        }
       }
      }
     },
     "last_updated": "2023-11-27T03:43:58.586Z"
    }
...
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

[config.json](https://github.com/envoyproxy/envoy/files/13469896/config.json)

*Logs*:
>Include the access logs and the Envoy logs.
[envoy.log](https://github.com/envoyproxy/envoy/files/13469820/envoy.log)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by littlejiancc** [comment]
@yanavlasov another question
From the example config, if the cluster type is STRICT_DNS, and the endpoint of a dynamically registered service is the IP address, Will this affect the duration of cluster warming? 
```
...
"dynamic_warming_clusters": [
    {
     "version_info": "24",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "service-3g3aLod3tDPBXQD3626-align_flRrz7Xj6-dataProvider",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "lb_policy": "RING_HASH",
      "ring_hash_lb_config": {
       "hash_function": "MURMUR_HASH_2"
      },
      "load_assignment": {
       "cluster_name": "service-3g3aLod3tDPBXQD3626-align_flRrz7Xj6-dataProvider",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "11.64.0.5",
              "port_value": 42939
             }
            },
            "hostname": "11.64.0.5"
           }
          }
         ]
        }
       ]
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "explicit_http_config": {
         "http2_protocol_options": {
          "max_outbound_frames": 1000000
         }
        }
       }
      }
     },
     "last_updated": "2023-11-27T03:43:58.586Z"
    }
...
```

**Comment by adisuissa** [comment]
Please see if disabling `wait_for_warm_on_init` (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto) solves your issue.

**Comment by littlejiancc** [comment]
@adisuissa Thank you very much！

**Comment by littlejiancc** [comment]
@adisuissa hi！
I have disabled wait_for_warm_on_init, and received 503 no healthy upstream, and it lasted about 75s, but in envoy container, I went to telnet upstream service during 503, which was successful.
My question is if telnet is successful, why does it return 503?

**Comment by littlejiancc** [comment]
As @yanavlasov  said, it is indeed a DNS resolution problem!
