### ISSUE TITLE
Add time spent reading request headers to downstream timings

### ISSUE THREAD

**Issue by fcfort** [envoyproxy/envoy#31064]
Add the time between `StreamInfo::startTime` and the time to finish reading request headers to downstream timings (roughly here: [source/common/http/conn_manager_impl.cc#L1187](https://github.com/envoyproxy/envoy/blob/1ef48e62bfff7be0403d6609eb9f57e17907bcc2/source/common/http/conn_manager_impl.cc#L1187).

This will aid observability of time spent in the proxy by exposing how much time was spent reading request headers.

**Comment by yanavlasov** [comment]
I assume you want this exposed as an access log substitution variable.

**Comment by fcfort** [comment]
Having it available in `DownstreamTiming` is sufficient for my use case, since from there I can access it in an HCM Access Logger via the `StreamInfo` of the request.
