### ISSUE TITLE
flake in udp DynamicForwardProxyIntegrationTest.BasicFlow

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#31089]
FAIL: //test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy:dynamic_forward_proxy_filter_integration_test (see /build/bazel_root/base/execroot/envoy/bazel-out/k8-opt/testlogs/test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/dynamic_forward_proxy_filter_integration_test/test.log)

https://dev.azure.com/cncf/envoy/_build/results?buildId=156588&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=d1a98671-b7ba-5fbf-f06c-ff337c010df4&l=150

[ RUN      ] IpVersions/DynamicForwardProxyIntegrationTest.BasicFlow/IPv6
test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_integration_test.cc:157: Failure
Value of: fake_upstreams_[0]->waitForUdpDatagram(request_datagram)
  Actual: false (Timed out waiting for UDP datagram.)
Expected: true
Stack trace:
  0xb582d0: Envoy::Extensions::UdpFilters::UdpProxy::SessionFilters::DynamicForwardProxy::(anonymous namespace)::DynamicForwardProxyIntegrationTest_BasicFlow_Test::TestBody()
  0x1f9c3fc: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1f9c2bd: testing::Test::Run()
  0x1f9d4d7: testing::TestInfo::Run()
... Google Test internal frames ...

**Comment by alyssawilk** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=156594&view=logs&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&t=573d8780-d7b9-52e3-b4e0-a89886b0b9ff

**Comment by phlax** [comment]
this is happening **a lot** - would be really good to resolve before we cut 1.29

**Comment by ohadvano** [comment]
@alyssawilk I was just working on a fix, no need to disable :) Will appreciate a review, if possible
