### ISSUE TITLE
Regarding envoy and it's all dependencies

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#31104]
When I am downloading envoy through below command
git clone --branch v1.26.4 https://github.com/envoyproxy/envoy.git

It downloads only envoy and it does not download all dependencies, which are mentioned in this page
https://www.envoyproxy.io/docs/envoy/v1.26.4/intro/arch_overview/security/external_deps#external-dependencies-build

I know I can download all dependencies separately but when I am downloading dependencies separately and generating *.cc and *.h files. these are giving compilation error.

Is there any way to download envoy, gRPC, Protobuf and envoy api dependencies so that we can avoid incompatible issues?

**Comment by yanavlasov** [comment]
You only need docker in order to build Envoy. See https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#building-envoy-with-the-ci-docker-image

During build bazel will download all external dependencies that are needed.

**Comment by yanavlasov** [comment]
Yes, bazel will download it from URLs that are specified in dependency definitions https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl

bazel caches downloaded artifacts locally. I'm not aware of an existing way to download them from some other location.

**Comment by Gaurav0411GitHub** [comment]
I wan to use for rocky linux. This docker image is for linux machine

**Comment by Gaurav0411GitHub** [comment]
When I am compiling envoy with bazel with below command
bazel --bazelrc=/dev/null build --sandbox_debug --verbose_failures --copt="-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 -DLLVM_USE_SPLIT_DWARF" --define wasm=disabled --define tcmalloc=disabled --define signal_trace=disabled --config=sizeopt -c opt //source/exe:envoy-static.stripped

I am getting below warning
INFO: From Action external/opencensus_proto/opencensus/proto/agent/trace/v1/trace_service.grpc.pb.h:
bazel-out/k8-opt/bin/external/opencensus_proto/external/opencensus_proto: warning: directory does not exist.
INFO: From Action external/com_google_googleapis/google/devtools/cloudtrace/v2/trace.grpc.pb.h:
bazel-out/k8-opt/bin/external/com_google_googleapis/external/com_google_googleapis: warning: directory does not exist.

How can I resolve this error?
