### ISSUE TITLE
misuse envoy.reloadable_features in aws credential fetching

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#31119]
*Description*:
#30626 introduces `envoy.reloadable_features.use_libcurl_to_fetch_aws_credentials` which is default enabling http async client by putting the flag to `FALSE_RUNTIME_GUARD`

This is confusing and aggressive with the goal of runtime flag.

ideally we might consider the opposite way, i.e.,
(a) introduced ``envoy.reloadable_features.use_http_client_to_fetch_aws_credentials`` and default disable
(b) flip the runtime flag in months
(c) remove runtime flag in another months later

in current stage, we probably want to put it to `RUNTIME_GUARD` as it's 1 month old. 
Thought?

**Comment by suniltheta** [comment]
Are you suggesting we change the runtime flag to `envoy.reloadable_features.use_http_client_to_fetch_aws_credentials` and keep the default as `true`, is that correct?

**Comment by JuniorHsu** [comment]
yes we want to have some headroom to verify the flag before the feature is enabled by default

**Comment by suniltheta** [comment]
Let me get this change created. Thank you for catching this before it is released.

**Comment by jwillker** [comment]
@suniltheta Seems like the 1.30 version doesn't change this flag to true.
I didn't find anything related to this in the 1.30 Changelog: https://github.com/envoyproxy/envoy/blob/4b0495bb6bf09f97292a8b30b2e97b71cda59256/changelogs/1.30.0.yaml

I'm wrong or does the 1.30 version have this flag set to true?

**Comment by suniltheta** [comment]
it is not set to true. There are some bugs that need to be fixed which are in flight https://github.com/envoyproxy/envoy/pull/34138
