### ISSUE TITLE
Can our home-brew xDS servers to operate without remembering the non-existing resources requested by the client and still function correctly with Envoy clients?

### ISSUE THREAD

**Issue by logstashbugreporter** [envoyproxy/envoy#31117]
*Title*: 
Can our home-brew xDS servers to operate without remembering the non-existing resources requested by the client and still function correctly with Envoy clients?

*Description*:
Since my previous issue remains unresolved but got closed, I've opened a new one in the hope of obtaining answers. We've developed an internal xDS server to work with our custom service discovery clients and Envoy.

Regarding our home-brew xDS server, if it returns an error message and doesn't track the resource for non-existing requests, would it still function correctly with Envoy clients for our internal service discovery? From my understanding, Envoy sends another subscription request if the previous one doesn't yield a route, and this happens with the subsequent request from upstream. I'd appreciate a confirmation on this. Thanks! I understand that this approach may marginally increase the long-tail (99.9999%:) latency in extremely rare cases. 

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/issues/31071

**Comment by yanavlasov** [comment]
Adding @adisuissa for any comments

**Comment by adisuissa** [comment]
I would advise against anything that is not part of the protocol, as it may change in the future and your system won't work well.
