### ISSUE TITLE
client observes UC and server observes DC during istio-ingressgateway shutdown

### ISSUE THREAD

**Issue by nirvanagit** [envoyproxy/envoy#31149]
*Title*: *client observes UC and server observes DC during istio-ingressgateway shutdown when istio-ingress is setup as AUTO_PASSTHROUGH proxy*

*Description*:
Longer requests result in UC (client) DC (server) when istio ingressgateway is shutting down.

On further analysis found that the connections on istio ingressgateway do not drain, even though envoy proxy is in draining. We increased the drain duration to 300s but even that did not help. The connections remained in active state (until a connection breached max request per connection threshold we have set). And the moment envoy comes out of the draining state, and is killed by pilot-agent, we observe UC/DC.

>What issue is being seen?
Envoy should gracefully shutdown all the connections before being killed by pilot-agent after the draining sequence is complete.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
1. Fortio job with delay of 5 seconds
2. Istio ingress proxy with TLS Passthrough, with drain duration of 300s and no pre stop hook.
3. Run fortio job, and shutdown ingress proxy

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by soulxu** [comment]
@nirvanagit it seems like you should submit this to the Istio community, after triage by the istio community, if this ensure something cause by the Envoy, then we can come back to discuss the issue.

**Comment by soulxu** [comment]
> Thanks @soulxu - but I wanted to confirm, when envoy says draining is implemented by HTTP CONNECTION MANAGER, does it mean that draining is not available for AUTO PASSTHROUGH scenarios, which works at TCP ?

We have drainning for http. But I don't `AUTO PASSTHROUGH`, this should be a term from Istio side. Better to check with istio

**Comment by soulxu** [comment]
@nirvanagit I will close this issue, but please free feel to open up again if you have more questions, or if you get something new from Istio side, then welcome to back Envoy side to ask questions. Thanks!
