### ISSUE TITLE
Support struct values for fields in OTEL AccessLogger

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#31148]
*Description*:
 the existing otel logger's request format is static by the body and attributes field(the struct layout is defined at the config time). I am wondering if we can make that dynamic by supporting struct values for fields in OTEL AccessLogger

**Comment by soulxu** [comment]
cc @htuch

**Comment by htuch** [comment]
Is the idea to use header formatter variables?

**Comment by htuch** [comment]
Can you propose a proto change to make this concrete?

**Comment by TAOXUY** [comment]
Thanks @kyessenov! 

Yeah, that's our further ask. Essentially we could generate multiple logs(audit log) per access dynamically so we want to the forerunner extension can fully control the OTEL request generation, instead of using the current static declarative way.

**Comment by htuch** [comment]
Thanks. I think having a concrete proto change (even if only a sketch in a comment) would be a useful way to clarify what is being proposed.

**Comment by TAOXUY** [comment]
Thanks Kuat!

For
https://github.com/envoyproxy/envoy/blob/da09811ed0fe920b4beb9223a5e160d3587a47bc/api/envoy/extensions/access_loggers/open_telemetry/v3/logs_service.proto#L26-L49

I am thinking introducing a field maybe called
```
// When the field is set, the  the OTel AccessLogger will assume a base64-encoded OTel request binary is set in this filterState so it will add this request in the batch after reading and decoding. 
// When this field is used, `resource_attributes`, `body` or `attributes` shouldn't be set.
 string filter_state_for_otel_request_injection =6;
```

Why we need this?
1. we may have multiple audit logs dynamically generated for single request so this static declarative configuring approach for request generation will no longer be effective.
2. we don't need to worry about https://github.com/envoyproxy/envoy/issues/31148
3. we don't need to worry about https://github.com/envoyproxy/envoy/issues/30017
4. minor: we potentially set  OTel fields(other than Resource Attributes, LogRecord.body, LogRecord.body.attributes) that are not exposed by OTel AccessLogger config.

**Comment by htuch** [comment]
For https://github.com/envoyproxy/envoy/issues/31148#issuecomment-1847695179, I feel this speaks to limitation in ProxyWasm and our ABI (CC @mpwarres @PiotrSikora). Why can't we have better ABI-level support for logging/tracing/stats that can approach what is needed for OTLP?

I'm actually super confused on this thread though, it started off as some ask about OT access loggers, and now it's about Wasm ABIs?

**Comment by kyessenov** [comment]
@htuch The original issue did not have the full context. The logs are being produced by a Wasm extension, and need to be exported via OTLP to a different resource (not the request log, multiple entries per log).

**Comment by PiotrSikora** [comment]
I'm definitely missing some context, but what's missing in Wasm's `proxy_log`?

What's the exact ask that would make Wasm work for OTEL AccessLogger?

**Comment by kyessenov** [comment]
@PiotrSikora Ability to send structured logs (https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto), meaning key-value attribute, resource attributes, and structured body.

Also, ability to register OTLP for Wasm, and route `proxy_log` to it.
