### ISSUE TITLE
HTTP listener returns empty response

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/envoy#31177]
Hi I am using a control plane-based dynamic configuration setup. I am trying to create an HTTP listener(not HTTPS), when I apply the configurations through the control plane, the config is correctly added to the envoy config. But when I send the HTTP request I get this 

`curl "http://test.something.com:9080/test-api-with-multiple-port-listener/v1.0.0/user/user123/playlist/watch-later"`

I get this: `curl: (52) Empty reply from server`

This is the config dump [1] of this setup. Could someone help me why this behavior is occurring I could not find any problem in this dump that prevents a http request. 

Thanks.
[1]: [http-config.json](https://github.com/envoyproxy/envoy/files/13555566/http-config.json)

**Comment by soulxu** [comment]
@Tharsanan1 better to have envoy log, you can run Envoy with parameter "-l debug"

**Comment by Tharsanan1** [comment]
@soulxu I've attempted it with debug-enabled deployment, but I don't see any logs related to this HTTP request in the logs. Usually, when we receive curl: (52) Empty reply from server, it means the server is listening for HTTPS, but we provided an HTTP request, correct? In this case, I intend to listen for HTTP requests, so I haven't added any transport_socket related configurations to the specific HTTP listener. I assume that will prompt Envoy to listen for HTTP requests. I hope we don't have to set any other special properties to specify that this listener should listen for HTTP, not HTTPS. Could you please take a look at the config dump and let me know if there are any issues with the configuration? Thanks.

**Comment by Tharsanan1** [comment]
@soulxu I found the problem. In the configuration I had "filter_chain_match" field. After removing that http started to work. Thanks. I ll close the issue
