### ISSUE TITLE
W3C trace with XRay Extension

### ISSUE THREAD

**Issue by DeeptiGuptaP** [envoyproxy/envoy#31176]
Hello Team,

We are using Envoy Image 1.26.x with Otlp w3c tracer to send traces to another envoy with X-ray tracer. We are hoping that traces would connect for the request being generated from w3c envoy to X-ray but we don't see any parent trace id.

To provide more detail on the flow:

- Envoy1 is the upstream, it's the virtual gateway that will send a health check request to Envoy2. This is done in Otel and we 
can see that the last trace is indicating an egress to the health check endpoint of Envoy2. 
- Envoy2 is the downstream, we can see in the trace that there is an incoming request hitting the healthcheck endpoint. 
However, the parent span coming from the VG is not recorded in the span.

We have tried confirming with new AWS Q chat bot if this is supported and the answer was "when a trace is generated using an OpenTelementry SDK instrumented with the AWS X-Ray SDK, the W3C Trace Context will connect as the parent span of the X-Ray segments" so we think the trace should connect ideally.

Thinking if this could be something related to older X-ray sdk version incorporated in envoy code? 

Regards,
Deepti Gupta

**Comment by soulxu** [comment]
cc @wbpcode if he can help on this

**Comment by soulxu** [comment]
cc @abaptiste @suniltheta

**Comment by suniltheta** [comment]
The XRay extension in Envoy is not yet updated to support W3C trace format.
@soulxu can you please add help wanted & aws tag?
