### ISSUE TITLE
Is it possible to synchronize requests

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31187]
I'm trying to develop a custom http filter. I want to do something as below:

Let's say that three requests are coming. The first one does some heavy calculation. And the other two requests need the result of that calculation to continue.

So I made a `std::vector` to store the requests. Once the calculation is done, all of requests in the `std::vector` will continue. Here is What I did:
```
std::vector<MyCustomHttpFilter *> vec;
enum State {NIL, ON_FLIGHT};
State state = NIL;
FilterHeadersStatus MyCustomHttpFilter::decodeHeaders(RequestHeaderMap& headers, bool end_stream) {
    lock();
    if (state == NIL) {
        state = ON_FLIGHT;
    } else if (state == ON_FLIGHT) {
        vec.push_back(this);
        return StopIterationAndBuffer;
    }
    unlock();
    res = doHeavyCalculation();
    lock();
    for (auto filter : vec) {
        filter->doSomething(res);
        filter->callback_->continueDecoding();
    }
    state = NIL;
    unlock();
}
```
In a word, if the calculation has begun but not yet finished, all of requests will be pushed into a vector, they will continue once the calculation is done.

However, I just tested my code and got a segmentation fault on an ASSERT: `dispatcher_->isThreadSafe()`, which is located at https://github.com/envoyproxy/envoy/blob/b58d31272913fa8bb1bd1b69b0102d710c97d431/source/common/event/timer_impl.cc#L30C24-L30C24. As my understanding, I got this because `filter->callback_->continueDecoding();` in invoked on the current thread, which is not the original thread of these filters in the `std::vector`. It seems that this is how Envoy works: **a work ALWAYS belongs to a single thread.** (There has no some mechanism like `work stealing` in Envoy?)

So I want to know if my design has any possibility to be achieved? Or it can't be achieved?

**Comment by soulxu** [comment]
There isn't work stealing in the Envoy. The reason is the vector is a global variable, and the first request and the other two requests was processed by a different thread, but you put `two requests` into the vector, then you fetch them out in the first request's thread.

You can store some lambda function for the other two requests which execute a post (dispatcher->post()) in the dispatcher on their thread. The posted function can resume the process of those two requests.
