### ISSUE TITLE
Support standard Forwarded header

### ISSUE THREAD

**Issue by PSanetra** [envoyproxy/envoy#31198]
*Support standard Forwarded header*

*Description*:
As far as I can see envoy currently just supports the "non-standard" `X-Forwarded-*` headers. It would be nice to support also the standard [Forwarded header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded).

*Use case*
Keycloak has added support for the `Forwarded` header with version [21.0.0](https://www.keycloak.org/2023/02/keycloak-2100-released.html#_support_for_the_standard_forwarded_header_when_running_behind_a_reverse_proxy) and advices reverse-proxies to override this header.

Related contour issue: https://github.com/projectcontour/contour/issues/5991

**Comment by soulxu** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
I don't think anyone on the maintainers crew has cycles to pick this up but we're happy to take PRs improving Envoy's standards compliance!
