### ISSUE TITLE
Upstream connection retry on different host

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#31217]
I'm trying to configure a behavior where in case an upstream connection fails for host ``host1.com`` (for example - ``tcp_proxy`` creates a TCP connection and fails due to timeout), and retry is configured, the next attempted host (for the same downstream connection) will be a different host (for example ``host2.com``). So always there's an attempt to establish connection with a primary host within a cluster, and retry on secondary hosts.

I scraped the config trying to understand whether this is currently possible, and allegedly it is not, but wanted to ask here to make sure I am not missing such functionality before I turn to other alternatives or implementing such option, thanks.

**Comment by soulxu** [comment]
@ohadvano have you tried to add health checks to the cluster? https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#envoy-v3-api-msg-config-core-v3-healthcheck

**Comment by suniltheta** [comment]
Is Aggregate Cluster https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster something that is already on your radar?

**Comment by ohadvano** [comment]
@suniltheta thank you, this seems like a good direction. However, I'm trying to understand what may cause fallback to the second cluster? My goal is only fall back to the secondary cluster if the request failed on the first try (assuming an upstream connection is retried multiple times).

If I understand correctly, the fall back depends only based on health checks. In other words, if no health checks are defined, the primary cluster would always get picked?

**Comment by suniltheta** [comment]
In my case I have seen fallback happen with passive health check configured (active health check not configured during testing). Is passive health check (outlier detection) something that you would consider configuring? Let me know if passive health checking didn't trigger the fallback to secondary cluster from your testing.

**Comment by ohadvano** [comment]
I did not test this direction yet, will give it a try and update. Thanks again

**Comment by suniltheta** [comment]
Checking if @cpakulski has any suggestion based on the behavior that you are seeing here.

What is your traffic rate? Does it have enough time within the ejection internal to determine that even the priority 1 endpoints are unhealthy?
I see that you are not configuring interval too low like seen on https://github.com/envoyproxy/envoy/issues/31070

Also, the over provisioning factor etc come into picture, which might require some math on determining the rate of traffic. that gets shifted. Also there is possibility of panic mode that gets enabled.

**Comment by ohadvano** [comment]
What do you mean about rate of traffic? I'm referring to the same downstream connection. I other words, I have a downstream connection with a retry on upstream connection. With the config above, I'm expecting to see upstream attempts to ``[fakehost1.com, fakehost2.com, realhost.com]``, but in reality I see ``[fakehost1.com, fakehost1.com, fakehost2.com, fakehost2.com, repeating fakehost2.com for as many retries I configure]``.

Is my expectation incorrect?

**Comment by suniltheta** [comment]
oh, I see that just the retry of failed request is not going to preferred priority hosts. I believe this is something to do with retry predicate that we can set? To say if current priority doesn't satisfy then on retry pick a different host.

Is this something that you already looked into? https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/retry/priority/previous_priorities/v3/previous_priorities_config.proto

I have not dealt with predicate configuration myself. So I am not exactly sure how to configure it properly.

**Comment by ohadvano** [comment]
In my case I'm not dealing with HTTP rather than ``tcp_proxy``, I don't think this is configurable there. What bothers me is that once a host is declared outlier, it shouldn't be picked, unless I'm misunderstanding something
