### ISSUE TITLE
Multiple definition of 'typeinfo for Envoy::Network::NetworkListenSocket<Envoy::Network::NetworkSocketTrait<(Envoy::Network::Socket::Type)0> >

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#31212]
*Description*:
we faced some link issues when do cross build using our self-defined tool-chain.  
And local build is ok, but when we were using the cross tool chain we faced this issue , i think this may be a bug for envoy.

arm-cortexa15-linux-gnueabihf-gcc @bazel-out/arm32-fastbuild/bin/source/exe/envoy-static-2.params)
 error: bazel-out/arm32-fastbuild/bin/source/server/config_validation/libserver_lib.lo(server.o): 
 multiple definition of 'typeinfo for Envoy::Network::NetworkListenSocket<Envoy::Network::NetworkSocketTrait<(Envoy::Network::Socket::Type)0> >'
 bazel-out/arm32-fastbuild/bin/source/exe/libmain_common_lib.lo(main_common.o): previous definition here
 error: bazel-out/arm32-fastbuild/bin/source/server/config_validation/libserver_lib.lo(server.o): multiple definition of 'typeinfo for Envoy::Network::NetworkListenSocket<Envoy::Network::NetworkSocketTrait<(Envoy::Network::Socket::Type)1> >'
 bazel-out/arm32-fastbuild/bin/source/exe/libmain_common_lib.lo(main_common.o): previous definition here
 error: bazel-out/arm32-fastbuild/bin/source/server/config_validation/libserver_lib.lo(server.o): multiple definition of 'typeinfo name for Envoy::Network::NetworkListenSocket<Envoy::Network::NetworkSocketTrait<(Envoy::Network::Socket::Type)0> >'
 bazel-out/arm32-fastbuild/bin/source/exe/libmain_common_lib.lo(main_common.o): previous definition here
 error: bazel-out/arm32-fastbuild/bin/source/server/config_validation/libserver_lib.lo(server.o): multiple definition of 'typeinfo name for Envoy::Network::NetworkListenSocket<Envoy::Network::NetworkSocketTrait<(Envoy::Network::Socket::Type)1> >'
 bazel-out/arm32-fastbuild/bin/source/exe/libmain_common_lib.lo(main_common.o): previous definition here

**Comment by soulxu** [comment]
gentle ping @keith
