### ISSUE TITLE
Compilation Failure on Amazon Linux 2 with GCC 11 and Envoy v1.25.9 BoringSSL FIPS

### ISSUE THREAD

**Issue by kpramesh2212** [envoyproxy/envoy#31237]
### Issue Summary

I am encountering a compilation failure when attempting to build Envoy v1.25.9 on Amazon Linux 2 using GCC 11. The issue appears to be related to a version mismatch with Clang.

### Steps to Reproduce

1. Clone Envoy repository.
2. Checkout version v1.25.9.
3. Run the following command for compilation:
   ```bash
   bazel build --copt="-Wno-error=uninitialized" -c opt envoy --action_env=CC=/usr/bin/gcc --action_env=CXX=/usr/bin/g++ --define no_debug_info=1 --config=sizeopt --define boringssl=fips

### Expected Results

I expected the compilation to be successful, as it was in version v1.25.8.

### Actual Results

The compilation fails with the following error message:

```
      |                               ^~~~~~~~~~~~~~~~~~~~~
ERROR: /home/ec2-user/.cache/bazel/_bazel_ec2-user/221703495c2e97a5482194eda3ea2f8b/external/boringssl_fips/BUILD.bazel:25:8: Executing genrule @boringssl_fips//:build failed: (Exit 1): bash failed: error executing command (from target @boringssl_fips//:build) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by clang)
clang: /lib64/libtinfo.so.5: no version information available (required by clang)
/home/ec2-user/.cache/bazel/_bazel_ec2-user/221703495c2e97a5482194eda3ea2f8b/sandbox/linux-sandbox/3965/execroot/envoy/external/boringssl_fips /home/ec2-user/.cache/bazel/_bazel_ec2-user/221703495c2e97a5482194eda3ea2f8b/sandbox/linux-sandbox/3965/execroot/envoy
ERROR: Clang version doesn't match.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmp/envoy/source/exe/BUILD:24:16 Linking source/exe/envoy-static failed: (Exit 1): bash failed: error executing command (from target @boringssl_fips//:build) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 271.997s, Critical Path: 43.51s
INFO: 2483 processes: 83 internal, 2398 linux-sandbox, 1 local, 1 worker.
FAILED: Build did NOT complete successfully
```

### Environment Information

    Operating System: Amazon Linux 2
    Compiler: GCC 11
    Envoy Version: v1.25.9

### Additional Information

I suspect this commit (https://github.com/envoyproxy/envoy/commit/c0eeaf82f93e8f28a3df3a51b31d37dadbb557c6) may have upgraded the Clang version from 7 to 12, causing a major version upgrade in the patch release. This behavior was not observed in v1.25.8.

**Comment by wbpcode** [comment]
Yeah. I think you are right. And this could be resolve by upgrade glibc or build envoy in a build container.

**Comment by wbpcode** [comment]
cc @keith

**Comment by dwj300** [comment]
Can we re-open this? We're struggling to build for AL2 as it still uses glibc2.26
