### ISSUE TITLE
Custom header set by ext_proc isn't used by cluster_header when selecting a cluster at route level 

### ISSUE THREAD

**Issue by Will00038** [envoyproxy/envoy#31241]
*Title*: *Custom header set by ext_proc isn't used by cluster_header when selecting a cluster at route level*

*Description*:
Hi ! First of all, I'd like to clarify that I'm new to Envoyproxy, so the issue may have been already mentioned but I didn't find anything on the subject. My sincere apologies if I'm mistaken.

What I'm trying to achieve :
I'm trying to use envoy with filters and a custom filter that computes the target endpoint after analysing the request
 
So I went with the following solution :
An incoming request goes through the custom filter (ext_proc) to set a custom header with a value that refers to a cluster's name that is later used to select a cluster using cluster_header. 

The selected cluster will point to a static target meaning that clusters will already be enumerated.

But the custom header's value doesn't seem to be taken in account by `cluster_header` when resolving at route level
I also tried using `response_headers_to_add` at `HttpConnectionManager` level to add a custom header 
It seems that cluster_header only refers to headers that were originally received by envoy 

I'm not sure that this is the best way to implement this as I don't fully grasp Envoy's capabilities
Any suggestion is welcomed

Thank you

**Comment by wbpcode** [comment]
Route will selected before the filter chain is executed by default.
But you can clear the route cache to force envoy re-select a new route after modified http request headers in the ext_proc filter by the `clear_route_cache` field. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ext_proc/v3/external_processor.proto#service-ext-proc-v3-commonresponse

**Comment by Will00038** [comment]
Yes that's it, thank you for the answer !

**Comment by wengyao04** [comment]
Hi, we have a similar issue. In our use case

client -> global-external-processor -> per-route-external-processor -> upstream-cluster

we use a header match to decide the upstream destination, like "x-backend: xxx", this header is calculated in the global-external-processor. We set clear_route_cache to true in the global-external-processor (when it process request header). After that it recalcute the route but it does not hit the per-route-external-processor anymore. 

Could I have any suggestions about it ? Thanks !!
