### ISSUE TITLE
Memory usage (or possible leak?) in ubuntu-20.04-based containers

### ISSUE THREAD

**Issue by zigmund** [envoyproxy/envoy#31248]
*Title*: Memory usage (or possible leak?) in ubuntu-20.04-based containers

*Description*:
We're using envoy v1.28 as redis cache proxy, deployed as sidecar container in Kubernetes. Used [distroless image](https://hub.docker.com/layers/envoyproxy/envoy/distroless-v1.28.0/images/sha256-8d93b24b167364f769ac9dac11ddc48631c7f9fb54213794acfdd5ebf5bbafdd?context=explore) - everything worked fine. Switched to [usual (non-distroless) image](https://hub.docker.com/layers/envoyproxy/envoy/v1.28.0/images/sha256-1a7335610e70a7579f2fee9b8c0f3bb2c7f22b72e52381ff749e5b9df3692883?context=explore) for the reason and saw pretty aggressive memory growth (`container_memory_working_set_bytes`). I've checked [Dockerfile](https://github.com/envoyproxy/envoy/blob/main/ci/Dockerfile-envoy) - envoy binary is the same between usual and distroless images. Made few test image builds and deployments - using ubuntu 20.04, 22.04 and debian 12.2 - saw the issue only in ubuntu-20.04-based image.

All instances without any load:
<img width="1898" alt="image" src="https://github.com/envoyproxy/envoy/assets/1713091/99747dea-dd33-4d60-a9df-7981d97aa9a8">

*Repro steps*:
Start 2 deployments of envoy in kubernetes using config provided.
- One from `envoyproxy/envoy:distroless-v1.28.0` image.
- Second from `envoyproxy/envoy:v1.28.0` image.
Observe memory growth in second deploy using `container_memory_working_set_bytes` metric.

*Admin and Stats Output*:
/stats: https://gist.github.com/zigmund/a472462002d7041aee9da24e568c2a96
/clusters: https://gist.github.com/zigmund/456472f4c4baab9a0d3346797e265fae
/routes: `404 Not Found`
/server_info: https://gist.github.com/zigmund/cdf4d70e38fd722acfef76f56db4f84b

*Config*:
https://gist.github.com/zigmund/f83803c0c86cd08e4e047a782c9a1231

*Logs*:
https://gist.github.com/zigmund/6a49c5f98a03ffb1563a9bd236921c7a

**Comment by phlax** [comment]
> saw the issue only in ubuntu-20.04-based image

im wondering if this is related to Envoy at all in this case, and i guess what we could do about it

i would advise against using the Ubuntu container for anything other than dev (im aware its posted as the default)

we could probably switch the image to ubuntu 22.04 i should think

**Comment by zigmund** [comment]
@phlax i don't know exactly, but seems the issue is related to libc version, shipped with Ubuntu 20.04.

Looks like the easiest way to fix it - upgrade base image to Ubuntu 22.04.

**Comment by phlax** [comment]
> Looks like the easiest way to fix it - upgrade base image to Ubuntu 22.04.

if you want to raise a PR we can at least let CI build/test the image and figure it out from there

**Comment by zigmund** [comment]
@phlax, I'll take a look tomorrow.
