### ISSUE TITLE
PRs with lots of commits will not load in github, showing unicorn instead.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#3125]
*Description*:
This is really a github issue, but listing it as an Envoy issue because it's affecting our development flow.  There is no public github tracker on the github scalability issue, but I thought I'd use this issue to track interaction with github support on it.

Examples of PRs that have exploded are: #2932 and #3059.

**Comment by jmarantz** [comment]
Original report sent to github:

>It looks like after a medium-size PR has enough comments and commits, it unicorns. https://github.com/envoyproxy/envoy/pull/3059 is an example of such a PR.
>
> There is a large number of comments, but not an outrageous number. Is there some scalability issue in github that needs to be sorted out?

**Comment by jmarantz** [comment]
Response from Tiara (support@github.com):
>Hi Joshua,
>
>Thank you for reaching out to GitHub Support, and sorry for the trouble here.
>
>We're currently investigating other similar reports regarding this issue, and I've added your report to our list.
>
>While we can't share a specific ETA just yet, we'll be sure to update you as soon as there's any news to share.
>
>Best regards,
>Tiara 
>GitHub Support

**Comment by jmarantz** [comment]
Follow-up from me:
>Thanks -- is there a github issue about github we could follow?

**Comment by jmarantz** [comment]
Response from Tiara:
>Hi again Joshua,
>
>I'm afraid our issue tracker is internal, so I don't have a public facing issue that you can follow -- but we will definitely update you when we can, though!
>
>If you need to merge that pull request soon, we recommend using git merge locally on the command line as a workaround. We apologize for any inconvenience, and thank you for your patience.
>
>Do let us know if there's anything else we can do to help.
>
>Best regards,
>Tiara 
>GitHub Support

**Comment by jmarantz** [comment]
Follow-up from me:
>Thanks.  It would be helpful to know...if you have discovered & can share this...is this a scalability issue related to the commit-count, comment-count, or both?
>
>The workaround you suggested might be helpful at some point, but it's a complicated multi-person project with tons of code-review scrutiny and the person who created this PR does not have write-access; it must be merged by an OWNER.  And we haven't really finished iterating on the PR yet.  So right now we have a situation where the PR owner has made a new version of the CL to workaround, but that quickly unicorned as well, making me think this was more about the commit-count (he cloned all the commits).

**Comment by jmarantz** [comment]
Response from John (GitHub Staff):
>Hi Joshua,
>
>I'm afraid I'm not able to provide much more detail here, but it does appear that the issue relates to the size of the pull request (you could call this the commit count) but this is not the only factor :)
>
>Our engineers are looking into this though and we'll be sure to let you know once we have any news to share.
>
>Have a great day further!
>
>Cheers,
>John 
>GitHub Support

**Comment by mrice32** [comment]
I reported this as well, and I got a few slightly different suggestions for those interested:
```
We're continually seeing a unicorn with the following accompanying text:
"
This page is taking way too long to load.
Sorry about that. Please try refreshing and contact us if the problem persists.
"
The PR in question is this one: https://github.com/envoyproxy/envoy/pull/3059.

We've already closed and reopened this PR once, but again, after a few review cycles, it became unreachable (I've tried refreshing many times throughout the day). Is there anything we can do to preserve our comments and alleviate this issue now and in the future?

Thank you!

Matt Rice
```

Response:
```
Hi Matt,

Thanks for writing to GitHub support and sorry for the trouble!

We have received a few similar reports regarding big pull requests. I can confirm that our team is working on fixing this problem, and I've added your report to that issue.

Unfortunately I won't be able to provide an estimated time on when this might get fixed. We know this is not ideal, but hope you understand.

Is there anything we can do to preserve our comments and alleviate this issue now and in the future?

You should be able to use our API to get a copy of the comments in this pull request:

https://developer.github.com/v3/pulls/comments/#list-comments-on-a-pull-request

https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

If you have any question regarding using API we can definitely offer more detailed instructions.

Unfortunately I'm not sure if there's anything you can do on your part to view this pull request normally.

One thing you could try is viewing this PR in Incognito window or logged out.

I was actually able to view the PR you linked because I don't have write access to this repository, so GitHub will try to load less things for me such as edit buttons and so on. Of course this won't allow you to merge the pull request and so on, but perhaps it would help for you to look at its content?

Lastly, while we are working on consistently supporting large pull requests, you might consider keeping pull requests relatively short for now to avoid running into this again.

I hope this helps clear things up, and please let us know if you have any other questions.

Best 🕶
Cici
GitHub Support
👉Find support and come learn with other GitHub users in our new GitHub Community Forum!
```

**Comment by jmarantz** [comment]
Follow-up from me:

>Can you tell me at least how long this problem has been present? I don't
know if this was always a limitation for github that we've just started
bumping into on a regular basis, or whether this is a transient issue.
>
> The suggested workaround doesn't, as far as I can tell, address the problem
of continuing an ongoing code-review conversation.
>
>We hope a remedy arrives soon.

**Comment by jmarantz** [comment]
And reply from github:

>This is not an expected limitation of our system, though it's hard for us to pinpoint when this exact issue cropped up since we haven't nailed down the specific cause yet.
>
>We've been making improvements to the pull requests feature regularly to handle larger PRs with more commits and more timeline events, like comments and reviews. We also resolved a large number of size-related issues with PRs recently, but as you're experiencing there's more work to do.
>
>The team is actively investigating and we'll follow up as soon as we have news to share.

**Comment by ldemailly** [comment]
This happens on/off with a number of istio PRs too - for some reason though, using incognito window usually allows to load the content/see it

**Comment by mattklein123** [comment]
Calling this fixed for now given the recent perf updates shipped by GH.

**Comment by potemkin-git** [comment]
This issue still exists 2 years later.

Same use case: large PR (273 files, +20k lines, -15k lines), 417 pending comments
Same issue: 504 Bad Gateway on comments POST.

![image](https://user-images.githubusercontent.com/18307823/75247995-81770b80-57d3-11ea-9dc5-fb5036f87689.png)

**Comment by chloerice** [comment]
^Same, I've just pull an all nighter finishing review of a large PR leaving over 60 comments and I'm unable to submit it for review 😞 https://github.com/Shopify/polaris-react/pull/2725/files

**Comment by ds-clearago** [comment]
Still same issue in our private repo... PR with 15 commits, Showing 243 changed files with 2,295 additions and 1,465 deletions.

Interestingly the compare view works just fine, but not the PR view.

✅ works fine: https://github.com/.../.../compare/CL-2025
❌ 🦄 unicorn: https://github.com/.../.../pull/2774

Incognito doesn't help...

**Comment by EdAtomicRaccon** [comment]
Hi,

Same here on a large PR.
48 files changed. +15k lines, -142 lines.
39 pending comments.
We just lost a lot of comments today.

**Comment by stevehillsTB** [comment]
I also saw the unicorn today with a PR containing 411 files changed.

**Comment by fadulalla** [comment]
As a workaround, you can navigate to the "files" part manually and mark as many conversations as you can as resolved (use the commit filter to see previous conversations) and then the PR body should load.

Just append "/files" to get to the files section:
https://github.com/account/repo/pull/1000/files

Obviously this isn't for everyone, but in our case, most of the conversations were actually resolved, just not marked as resolved. It's amazing how nearly 5 years later and github still can't handle mere 300 comments.

**Comment by yohira0616** [comment]
Same Problem Caused.

Conversation 247
Commits 31
File Changed 265
+12,712, -2710 

to avoid(workaround) https://github.com/envoyproxy/envoy/issues/3125#issuecomment-1456056787 is works! thanks
