### ISSUE TITLE
How to track the order of req response in Network Filters

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31274]
This is intended for authors of database filters. I am trying to generate audit logs from databases fitlers (like- pg, mysql etc). I want to track the req/response status. If I get a response from upstream server, how can I be certain what was the corresponding request for the response? Do they always come in order?

**Comment by wbpcode** [comment]
which proxy or filter you mean? Then we can ping it's owner.

**Comment by shiponcs** [comment]
> which proxy or filter you mean? Then we can ping it's owner.

Postgres/MySQL proxy filter

**Comment by wbpcode** [comment]
cc @cpakulski

**Comment by cpakulski** [comment]
As I explained on the slack, you have to rely on the protocol spec (postgres, mysql). So, for example, if the postgres filter has sent 1 message to the server, the next reply must be response to that request. If postgres protocol allows to send to the server several requests, most likely the server is going to send the same number of responses, so you can correlate. Basically this is sort of FIFO.
