### ISSUE TITLE
Limit X-Forwarded-For headers to approved CIDR blocks only

### ISSUE THREAD

**Issue by robd003** [envoyproxy/envoy#31296]
*Title*: Ignore X-Forwarded-For unless client IP is in approved ACL of CIDR blocks

*Description*: The issue with relying on X-Forwarded-For is that those can be forged easily. If there was a way to restrict the existing X-Forwarded-* headers so they only applied to certain IP ranges that would be great. If we could have a built-in option to dynamically load IP ranges from CloudFlare upon start (with a refresh once a week) that would be a really fantastic solution.

[optional *Relevant Links*:]
https://datatracker.ietf.org/doc/html/rfc7239
https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/
https://www.cloudflare.com/ips/

**Comment by wbpcode** [comment]
Basically, a trusty hop should be set to select a IP from the xff list. By this way, we can ensure the IP should be a trusty IP. Is there any reason that this trusty hop couldn't be used or cannot meet your requirement?

And the `original_ip_detection` now is an extendable extension point. You can create a new extension for you requirement or extend current xff extension.

**Comment by robd003** [comment]
Can we keep this ticket open?
