### ISSUE TITLE
Envoy - redis clusters via aggregate cluster not working, authorization is missing "(error) NOAUTH Authentication required". 

### ISSUE THREAD

**Issue by yakov-kolkhi** [envoyproxy/envoy#31301]
Hi Team :)

as part of fallback purposes, we trying to setup 2 redis databases in our envoy proxy and make one of them as primary.
After while we succeeded setting up 2 listeners against 2 clusters and everything working properly :)
for example:
listeners - 
![Screenshot 2023-12-12 at 15 27 25](https://github.com/envoyproxy/envoy/assets/85568726/62668cbc-07cf-4e2f-b251-9026b2ae3a69)
clusters(the second cluster is similar) - 
![Screenshot 2023-12-12 at 15 31 18](https://github.com/envoyproxy/envoy/assets/85568726/b9c784fd-cebb-4125-b9d5-184e0f27fbee)
looking good:
![Screenshot 2023-12-12 at 15 36 43](https://github.com/envoyproxy/envoy/assets/85568726/d54c8a65-b19d-4e44-93c5-6161ba43fec6)

now i try to setup the fallback cluster included both as you wrote in the docs:
![Screenshot 2023-12-12 at 15 38 45](https://github.com/envoyproxy/envoy/assets/85568726/8dbbd64d-96ad-4ae8-9c15-4e5e02d4a37c)
the only part I am not 100% sure is here, the listener part for the new aggregated cluster(I assumed it is the same as before):
![Screenshot 2023-12-12 at 15 43 11](https://github.com/envoyproxy/envoy/assets/85568726/93e74995-5e02-4013-80e1-c247a807b490)
ok so now the issue is that I cant do my commands on the databases and it looks like it's not passing the "auth_password"?
![Screenshot 2023-12-12 at 15 47 37](https://github.com/envoyproxy/envoy/assets/85568726/484fc121-b1ad-476d-88d3-090122b17e8d)

please if you need any more information i will happily add more but the setup is very minimalistic and simple so i am not sure how deeper i can dive here but i will try. 

i am using envoyproxy/envoy:v1.28-latest
something wrong with my setup? i am doing something wrong? there is an issue with the aggregated cluster and the redis authorization?

thank you very much, 
jacobk.

**Comment by wbpcode** [comment]
For now, the backend cluster of redis proxy must be redis type cluster because the custom redis conn pool need read password/user from the cluster.

**Comment by yakov-kolkhi** [comment]
yes, this is what i thought, tnx man appreciate it :) @wbpcode
