### ISSUE TITLE
Group metrics by CIDR in tcp_stats transport socket

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#31315]
*Description*
[tcp_stats](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tcp_stats/v3/tcp_stats.proto) exports the kernel TCP info metrics such as RTT and restransmit
The TCP connecrtions sharing the same transport socket will update the same scope of metrics.

For downstream transport socket, the CIDR defined scope could greatly leverage the value of the metrics, 

In the real world, self defined CIDR could be a remarkable signal of
 
* physical zones (US, Europe, etc)
* source of network provider (AS1, AS2...)
* clould provider (gcp, aws...)

This applies to the upstream transport socket use case as well.

*Alternatives*

As downstream, listener filter chain matches can define the matcher of downstream CIDR and define TCP stats transport socket with independent scope name.
As upstream, the target CIDRs can be splits and each of them is materialized in a single cluster.

However, it's verbose to adopt unique filter chain/cluster just for CIDR.
The footprint is signifantly higher and the federation of filter chains and clusters (aggregated cluster) are not mature.

**Comment by lambdai** [comment]
@kyessenov  Do you think it would be useful in the ingress gateway deployment?

In a multicluster env, you may want to distinguish the downstream peers from neighbor clusters and distant clusters while providing the same listener.

**Comment by kyessenov** [comment]
Yeah, it makes sense to group stats by something other than the listener that handles them. Envoy doesn't have a simple way to add extra tags to the native stats. You could try extending `tcp_stats` with additional dynamic tags using per-connection metadata, and have something else populate that metadata. 

If you're using istio stats, you could latch the extra metadata onto the connection metrics. Either way would work, but both require some work.

**Comment by wbpcode** [comment]
cc @jmarantz
