### ISSUE TITLE
flake: IpVersionsClientType/UpstreamNetworkExtensionDiscoveryIntegrationTest.ConfigDumpWithFilterConfigRemovedByTtl/3 is flaky

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#31340]
A recent run in what looks like an unrelated PR (https://github.com/envoyproxy/envoy/pull/30761) failed in linux asan with:
```
[ RUN      ] IpVersionsClientType/UpstreamNetworkExtensionDiscoveryIntegrationTest.ConfigDumpWithFilterConfigRemovedByTtl/3
libc++abi: terminating with uncaught exception of type Envoy::EnvoyException: Negative duration passed to durationToTimeval(): -2
AddressSanitizer:DEADLYSIGNAL
```

I no longer have the detailed test log. The test is found in https://github.com/envoyproxy/envoy/blob/62a10e97ae6678a9fd7e3c4bf8740b59aa3cedb3/test/integration/upstream_network_filter_integration_test.cc#L539

which was committed in https://github.com/envoyproxy/envoy/pull/29240

**Comment by jmarantz** [comment]
Detailed failure log: https://dev.azure.com/cncf/envoy/_build/results?buildId=157648&view=logs&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=1002ac43-da84-5fae-70b2-98833b702d09&s=4735f34d-f4c8-5014-59d3-e506321c9f00

**Comment by ohadvano** [comment]
Not sure how to address this one because I tried running this asan test locally multiple times (for 2000+ iterations) and non failed.
It looks like the build you linked is from pre-submit, possibly some other change is related?

**Comment by phlax** [comment]
the only instance im seeing in postsubmit ci is on the 1.28 branch rather than main - not sure it its in some way fixed or whether it triggered due to less cache etc

**Comment by phlax** [comment]
having said that this test (not sure if same issue) does seem to be failing here and there in presubmit https://dev.azure.com/cncf/envoy/_build/results?buildId=159022&view=logs&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&s=4f7d954b-a765-565f-91a2-c04870dab43f&t=573d8780-d7b9-52e3-b4e0-a89886b0b9ff&l=274
