### ISSUE TITLE
Bad default stat prefix

### ISSUE THREAD

**Issue by ofek** [envoyproxy/envoy#3135]
Looking here https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/stats#tracing-statistics

It seems the default `stat_prefix` for admin is `admin.tracing`:

```
http.admin.tracing.tracing.client_enabled: 0
http.admin.tracing.tracing.health_check: 0
http.admin.tracing.tracing.not_traceable: 0
http.admin.tracing.tracing.random_sampling: 0
http.admin.tracing.tracing.service_forced: 0
```

Due to our regular expressions being greedy (no way around that), Envoy extracts the stat prefix as just `admin` and gets the metric name wrong:

```
# TYPE envoy_http_tracing_tracing_client_enabled counter
envoy_http_tracing_tracing_client_enabled{envoy_http_conn_manager_prefix="admin"} 0
```

We need to change the default to something else.

cc @mrice32 @jmarantz

**Comment by mattklein123** [comment]
This is just a bug: https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc#L688
