### ISSUE TITLE
Is it possible to use the body content to match a request?

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/envoy#31379]
I need to get the request body and match the request for a clusters 

Is it possible to do that with  envoy?

@cpakulski

**Comment by leandrocurioso** [comment]
😅

**Comment by wbpcode** [comment]
Seems I had responded this question on the slack channel. See https://envoyproxy.slack.com/archives/C78M4KW76/p1702637284591219.

Pasted response here in case some others may also want to know this.

> It a little hard to do that directly today. There are some possible alternatives:
>  - Custom http filter to stop filter chain and buffer the whole body, and mutate the routing result according to the body content.
>  - Do the above logic by lua filter.

> The althernative would use lua filter. You can write some scripts like following example to get body first, then set flag to request headers, then the route will be refreshed automatically.



```
function envoy_on_request(request_handle)
  local body = request_handle:body()
  -- do someting to parse attributes from body
  request_handle:headers():add("key", "attributes from body that used to match route")
end
```

**Comment by leandrocurioso** [comment]
You are totally right @wbpcode thanks again and closing the issue.
