### ISSUE TITLE
more easy way to get `LocalInfo`

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#31406]
this's found when doing https://github.com/envoyproxy/envoy/pull/31319, I'm not sure if there's an easy way to get `LocalInfo`.

cc @kyessenov

**Comment by kyessenov** [comment]
@wbpcode maybe we should turn localinfo into a pinned singleton as well?

**Comment by wbpcode** [comment]
What you mean by `easy way` specifically? Could you provide some more detailed context?

> @wbpcode maybe we should turn localinfo into a pinned singleton as well?

Will this help? I am not sure. Now we can access local info by `server_context.localInfo()` directly. If we turn the local info to a pinned singleton, then we need access it by `server_context.singletonManager().getTyped<LocalInfo>(...)`. Seems it cannot simplify the using.

**Comment by wbpcode** [comment]
I think the only way to simplify the using of local info is to create a actual global singleton. But it is not recommended now because of the envoy mobile (which may have multiple server instances and global singleton may bring unexpected contention).

**Comment by zirain** [comment]
> What you mean by easy way specifically?

`localinfo` lives in `CommonFactoryContext`, I'm sure it's diffcult to get a context in somewhere.

**Comment by wbpcode** [comment]
> > What you mean by easy way specifically?
> 
> `localinfo` lives in `CommonFactoryContext`, I'm sure it's diffcult to get a context in somewhere.

Yeah, I agree with you. I have similar annoyance with you sometimes. But it's not easy to resolve this problem for now. See my last comment.

A possible solution that I could think of is creating a new global singleton that only be compiled in the non-mobile build. And non-mobile modules could use this singleton. If mobile-related modules mis-use this singleton, there would be a compile error.
But I need discuss this with @alyssawilk first and she is on her vocation.

**Comment by alyssawilk** [comment]
Had this conversation offline but Envoy style generally leans towards explicit plumbing access through function calls and strongly against mutable singletons and while I used to argue with @mattklein123 about it myself I've become a convert over time =P
