### ISSUE TITLE
Add the ability to run scheduled workflow jobs on CI without requiring `request`

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#31416]
This came up when trying to migrate the Traffic Director workflow to the new CI framework: https://github.com/envoyproxy/envoy-ci-staging/blob/main/.github/workflows/mobile-traffic_director.yml

See https://github.com/envoyproxy/envoy/pull/31405 for attempts to this migration.  _mobile_ci_container.yml requires a `request` but the Mobile Traffic Director workflow is based on a schedule so the `request` section doesn't strictly apply.

Disabling the Mobile Traffic Director workflow for now since it's not really super important for the Envoy Mobile project right now, and will re-enable once this bug is resolved.

**Comment by phlax** [comment]
just looking at this now - its essentially the same problem that mobile-release currently has, so will try and fix this asap - that was already at top of my todos

ive added some additional code paths to accomodate this for now (in dev pr and toolshed), mostly its working altho will take a bit to clear up - once we have it working properly ill try and integrate into existing workflows/actions
