### ISSUE TITLE
How to log cookie values in access.log in istio envoy

### ISSUE THREAD

**Issue by ankitmahajan507** [envoyproxy/envoy#31415]
#22346 , #6695

Hi, Can someone pls share the example for the same. I have set the filter and logs format but in logs, value is still null

Filter yaml

spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.header_to_metadata
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
          request_rules:
          - cookie: test1_id
            on_header_present:
              key: test1_id
              metadata_namespace: userInfo
              type: STRING
          - cookie: test2_id
            on_header_present:
              key: test2_id
              metadata_namespace: userInfo
              type: STRING

Logs format:

"test1_id": "%DYNAMIC_METADATA(userInfo:test1_id)%",
"test2_id": "%DYNAMIC_METADATA(userInfo:test2_id)%"

**Comment by StarryVae** [comment]
it seems that the config you provide has no problem, can you also provide your test request?
