### ISSUE TITLE
Listing all external dependencies version/licence(s) for Envoy

### ISSUE THREAD

**Issue by aallrd** [envoyproxy/envoy#31427]
I have to list all the external dependencies of an `envoy` static binary, with their version and license(s).

I have a `bazel` build command used to produce this `envoy` static binary with many 'filters' and 'options':
```
bazel \
  --output_base=output_base \
  build \
  --define google_grpc=disabled  \
  --@envoy//bazel:http3=False     \
  --@envoy//source/extensions/wasm_runtime/v8:enabled=false \
  [...]
  @envoy//source/exe:envoy-static
```

I have tried to play with the `query` command of `bazel` but I am not able to get what I want using it.

Do you know a way to get the output I need ?

Thank you.

**Comment by wbpcode** [comment]
cc @phlax may have some input?

**Comment by phlax** [comment]
> Do you know a way to get the output I need ?

its not clear to me what your needs are, but i think using bazel query is most likely the answer

we have various tooling that works with the deps but they are either using bazel query under the hood or just parsing bazel config in a way that doesnt discriminate what is actually being used

**Comment by moderation** [comment]
I'm sure you have seen this but the total list is generated on each build at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/external_deps.html#external-dependencies. I think you are after a specific custom build output of the same which makes sense. It would be good to find a `bazel query` command that could generate the specific dependencies programatically

**Comment by aallrd** [comment]
I am indeed looking for an output similar as https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/external_deps.html#external-dependencies, but for my custom build of envoy.
Right now I am manually reviewing the above list, discarding the components I think I have disabled during the build.
Do you have a link to how the above list is generated ? Is it using a `bazel query` command ?

**Comment by phlax** [comment]
There is a tool here for generating the docs

https://github.com/envoyproxy/envoy/blob/main/tools/docs/generate_external_deps_rst.py

it gets data from this target https://github.com/envoyproxy/envoy/blob/e17f491376d75ab8dbef40279acf5550cde4ceca/tools/docs/BUILD#L24

this doesnt use bazel query - it parses the starlark data as json - so it doesnt discriminate what is used from what is there

possibly you want to do a combination - ie figure out the deps that you are using with query, and then use above data to generate metadata etc
