### ISSUE TITLE
[Redis] Add support for ECHO command

### ISSUE THREAD

**Issue by dceravigupta** [envoyproxy/envoy#31459]
https://redis.io/commands/echo/

**Comment by wbpcode** [comment]
@weisisea @mattklein123

**Comment by weisisea** [comment]
It should be straightforward to support ECHO command, similar to how PING command is handled:
https://github.com/envoyproxy/envoy/blob/ac42a62d6b8a2599c9a6101b6bb0bd11220c63e6/source/extensions/filters/network/redis_proxy/command_splitter_impl.cc#L623-L630

To handle ECHO command, we just need to copy the message in the request to the response.

Please feel free to send a PR.
