### ISSUE TITLE
Is it possible to use TLS per endpoint level?

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/envoy#31473]
**Hi Envoy Team,**

Today I know that we have the TLS config for a clusterlevel and this will be replicated to all endpoints. I'm using STRICT_DNS and would like to know if is possible to have TLS for a endpoint level.

**Example:**

- Cluster A have 3 endpoints;
- 1 one them works with TLS and the other 2 not;

**Any ideas?**

**Comment by marcosmariano** [comment]
@lizan I saw that this issue https://github.com/envoyproxy/envoy/issues/8016 sounds like this one. Would you happen to have any idea how to solve it?

**Comment by wbpcode** [comment]
cc @ggreenway

**Comment by soulxu** [comment]
@leandrocurioso have you tried this https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-transportsocketmatch ?

**Comment by marcosmariano** [comment]
> @leandrocurioso have you tried this https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-transportsocketmatch ?

We are trying it now... and  It's working!!
Thank you so much @soulxu !!

**Comment by leandrocurioso** [comment]
It solved the problem thanks a lot guys!
