### ISSUE TITLE
Comment of APPEND_IF_EXISTS_OR_ADD in HeaderAppendAction can not match actual behavior

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#31480]
*Title*: *Comment of APPEND_IF_EXISTS_OR_ADD in HeaderAppendAction can not match actual behavior*

*Description*:

https://github.com/envoyproxy/envoy/blob/6273573560def8329a32584016b6884c7924dc5c/api/envoy/config/core/v3/base.proto#L349

in fact, it will always add a same header instead of appending the specified value to the  existing values for headers not predefined inline.

**Comment by wbpcode** [comment]
I think the APPEND here is mean to add a new field with same name.

**Comment by tyxia** [comment]
Thanks for looking into this!

Yea, i agree with @wbpcode . 
I think it is just that Envoy implements `APPEND` differently for predefined inline header and other headers.

I left an [comment with the suggestion](https://github.com/envoyproxy/envoy/pull/31489/files#r1437180467)
