### ISSUE TITLE
Envoy opentelemetry exporter using stream rpc, however opentelemetry proto is unary rpc

### ISSUE THREAD

**Issue by rinfx** [envoyproxy/envoy#31497]
When I use envoy to forward requests to my java grpc server, I found envoy send data twice
![image](https://github.com/envoyproxy/envoy/assets/25995563/e76940bf-1c91-4dd0-aae6-16ccd246a34f)

**Comment by adisuissa** [comment]
From this info it is a bit challenging to reproduce. Can you have some minimal configuration that repros the issue?

**Comment by rinfx** [comment]
I have found the root cause. When I use opentelemetry tracer to export spans to my java grpc server, data frames don't have the "End Stream" flag. However, the java grpc server only handle requests when received a data frame with "End Stream" flag.
The code is:
https://github.com/envoyproxy/envoy/blob/v1.28.0/source/extensions/tracers/opentelemetry/grpc_trace_exporter.h#L72C46-L72C46

Now my question is "Why the end_stream param is always false?"

**Comment by rinfx** [comment]
The opentelemetry proto is a unary service:
![image](https://github.com/envoyproxy/envoy/assets/25995563/ba2ab0eb-249b-497b-99f2-a18be3abc8c8)

**Comment by htuch** [comment]
This seems familiar https://github.com/envoyproxy/envoy/pull/29011

The PR never landed it seems @ashishb-solo

**Comment by ashishb-solo** [comment]
ARGH sorry. That pull request fell completely off my radar. I'll do my best to try resurrecting it pushing an update sometime this week.
