### ISSUE TITLE
Golang: support calling user's finalizer when destroying the config

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#31516]
*Title*: *Golang: support calling user's finalizer when destroying the config*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Sometimes a plugin needs to clean up the allocated resource when its configuration is destroyed.
What about adding a hook for user in
https://github.com/envoyproxy/envoy/blob/e485fa5a995fb1de1efb34d0e5bbb05b27325fbd/contrib/golang/filters/http/source/go/pkg/http/config.go#L102

For example,
```
cfg, ... := configCache. LoadAndDelete(...)
if finalizer, ok := cfg.(Finalizer); ok { finalizer.Finalize() }
```

CC @doujiang24 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by doujiang24** [comment]
It might be better to add Golang standard GC finalizer on the config, in the `StreamFilterConfigParser.Parser` method, when some delay could be tolerated.
Thoughts?

**Comment by spacewander** [comment]
Thanks. User-defined finalizer already satisfies my requirement.
