### ISSUE TITLE
Envoy forward invalid header http2 request to upstream server

### ISSUE THREAD

**Issue by dezenxi** [envoyproxy/envoy#31529]
*Description*:
As I know, the PR #23267/ #23266 intended to keep compatibility on legacy test and system.
However, it still does not follow to standard [RFC9113](https://datatracker.ietf.org/doc/html/rfc9113#section-8.2.1)

Moreover, according to https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.6
    Intermediaries that process HTTP requests or responses (i.e., any
    intermediary not acting as a tunnel) MUST NOT forward a malformed
    request or response. 

So should envoy reject the invalid/malformed http2 request by default? or at least envoy should have a parameter/flag which allows turn on/off of http2 validation?

**Comment by soulxu** [comment]
I guess the UHV is going to help here. 
https://github.com/envoyproxy/envoy/issues/10646

cc @yanavlasov

**Comment by dezenxi** [comment]
Hi @soulxu ,
I still see the lines of fixed code in latest main
https://github.com/envoyproxy/envoy/blob/2f8e1a36ed808d760d6f791cdfc8f8cd568a1ad7/source/common/http/http2/codec_impl.cc#L1801C1-L1804C81

Seems @yanavlasov commit did not touch that part. 

Regards,
Duong
