### ISSUE TITLE
--log-format unix timestamp epoch 

### ISSUE THREAD

**Issue by curuvija** [envoyproxy/envoy#31524]
Is there a way to set unit timestamp epoch using `--log-format`? I cannot find any idea based on the docs here https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-log-format.

**Comment by wbpcode** [comment]
Hmmm, seems this was an old problem and IIRC matt had some comments. But I forget the issue link.

cc @mattklein123
