### ISSUE TITLE
extendable response flag support

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#31532]
response flag is a super great feature to indicate internal envoy status. It's very helpful to debugging envoy. 

However, we always need to edit the core code base if we want to add a new flag by a filter. This is not friendly for third-party extension to re-use this feature.

**Comment by ohadvano** [comment]
I was going to the same, while thinking how to add flow details which are 3rd party. I thought about adding a method to ``StreamInfo`` such as ``addAdditionalResponseFlag(const std::string flag)`` that would be aggregated when the command operator is being resolved to output
If that makes sense I can take this item

**Comment by wbpcode** [comment]
Ideally, the response flag should be an enum type rather than arbitrary string. Considering the extendibility, an registrable integer would be better choice.

A third party extension could register a new flag by a macro and a unique integer index will be allocated for the new flag.

And we can reuse the current `setResponseFlag` method which could be called multiple times safely and all flags will be stored in the stream info.

**Comment by ohadvano** [comment]
> A third party extension could register a new flag by a macro and a unique integer index will be allocated for the new flag.

Can you elaborate? not sure I understand the proposed technique

**Comment by wbpcode** [comment]
I mean a way like current inline header registration. Here is some quick draft code:

```
class CustomResponseFlagRegistry {
public:
  struct CustomResponseFlag {
    uint32_t flag_index_{};
  };

  static CustomResponseFlag registerFlag(absl::string_view flag_string,
                                         absl::string_view flag_string_long) {

    RELEASE_ASSERT(!CustomResponseFlagSet().contains(flag_string), "Flag already registered");

    auto flag_index = newFlagIndex();

    customResponseFlagSet().emplace(flag_string);
    customResponseFlagArray().emplace_back(flag_string, flag_string_long);

    return {flag_index};
  }

  std::pair<absl::string_view, absl::string_view> getFlagString(uint32_t flag_index) {
    RELEASE_ASSERT(flag_index > StreamInfo::ResponseFlag::LastFlag,
                   "Custom flag index must be greater than the last default flag");

    flag_index -= (StreamInfo::ResponseFlag::LastFlag + 1);

    if (flag_index < customResponseFlagArray().size()) {
      return {absl::string_view(customResponseFlagArray()[flag_index].first),
              absl::string_view(customResponseFlagArray()[flag_index].second)};
    }

    return {"", ""};
  }

  using CustomResponseFlagSet = absl::flat_hash_set<std::string>;
  using CustomResponseFlagArray = std::vector<std::pair<std::string, std::string>>;

  static uint32_t newFlagIndex() {
    return CustomResponseFlagArray().size() + StreamInfo::ResponseFlag::LastFlag + 1;
  }

  static CustomResponseFlagSet& customResponseFlagSet() {
    MUTABLE_CONSTRUCT_ON_FIRST_USE(CustomResponseFlagSet);
  }

  static CustomResponseFlagArray& customResponseFlagArray() {
    MUTABLE_CONSTRUCT_ON_FIRST_USE(CustomResponseFlagArray);
  }
};

#define REGISTER_CUSTOM_RESPONSE_FLAG(flag_string, flag_string_long)                               \
  const auto flag_string##_flag =                                                                  \
      CustomResponseFlagRegistry::registerFlag(flag_string, flag_string_long);                     \
  const uint32_t flag_string = flag_string##_flag.flag_index_;

#define CUSTOM_RESPONSE_FLAG(flag_string) flag_string##_flag.flag_index_

```

**Comment by wbpcode** [comment]
I think this require at least two PRs. If you are not in a hurry, I will do it by myself, and you can help to review it to see if it meet your actual requirement.

**Comment by wbpcode** [comment]
https://github.com/envoyproxy/envoy/pull/31719
