### ISSUE TITLE
An error occurred during the fetch of repository 'org_boost':

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31560]
*Title*: *Envoy CI build failed*

*Description*:
I've run `./ci/run_envoy_docker.sh './ci/do_ci.sh release.server_only'` and it fails with 
```bash
ERROR: An error occurred during the fetch of repository 'org_boost':
   Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz] to /build/bazel_root/base/external/org_boost/temp17115150572769371411/boost_1_78_0.tar.gz: Checksum was 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff but wanted 94ced8b72956591c4775ae2207a9763d3600b30d9d7446562c552f0a14a63be7
ERROR: /source/WORKSPACE:13:19: fetching http_archive rule //external:org_boost: Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz] to /build/bazel_root/base/external/org_boost/temp17115150572769371411/boost_1_78_0.tar.gz: Checksum was 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff but wanted 94ced8b72956591c4775ae2207a9763d3600b30d9d7446562c552f0a14a63be7
```
This similar error occurs when I try to build with: 
```bash
bazel build //contrib/exe:envoy-static --sandbox_debug --verbose_failures
```
But if I only build `envoy` instead of `//contrib/exe:envoy-static`, it succeeds:  `bazel build envoy`

I am using VM hosted in windows machine. Here's is the details of the VM system:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by pavanrangain** [comment]
Same is the issue with 1.26.x branches. Will this be back ported ti those release branches too ?

**Comment by phlax** [comment]
@pavanrangain are you up for raising PRs against supported branches? 

we can skip 1.25 now i think

/backport

**Comment by pavanrangain** [comment]
@phlax Thanks for looking into this.  Looks like its no more occurring even with released tags being built like v1.26.6. May be the checksum issue is fixed in repos from where these dependencies were pulled ?

**Comment by phlax** [comment]
backports are here #31707 #31706 - i didnt look at 1.26 yet

**Comment by phlax** [comment]
backport for 1.26 is in https://github.com/envoyproxy/envoy/pull/32214
