### ISSUE TITLE
[Question] How to extract client certificate from the TLS handshake at the istio gateway level using envoy filter

### ISSUE THREAD

**Issue by SachinHg** [envoyproxy/envoy#31568]
*Title*: *Extract client certificate from TLS handshake using envoy filter*

*Description*:

I am trying to mimic Nginx' behaviour where it extracts the client certificate and saves it as [ssl_verify_client](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client). The saved value of certificate can further be injected as a custom header before the request is sent to the target service.  
I tried writing  envoy filters following examples elsewhere which did not achieve what I need as I was unable to extract the certificate from TLS handshake.

Could someone here help me with this ?

Thanks

**Comment by adisuissa** [comment]
cc @lizan @ggreenway as TLS experts.

I'm assuming this can be added to the TLS extension, but don't know what it entails.

**Comment by ggreenway** [comment]
The cert details are stored in the header [x-forwarded-client-cert](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html#x-forwarded-client-cert). Is that what you're looking for?
