### ISSUE TITLE
How does retry policy of Envoy work in a micro-service backend

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31597]
I have such a micro-service backend as below:
```
app --> envoy1 --> server1 --> envoy2 --> server2
```
I configure retry_policy in the envoy1 and I can set retry times too in the server1, which is developed with Springboot. As all we know, modern frameworks, such as Springboot, support retry mechanism.

If I enable retry_policy of the envoy1 and use retry mechanism of the server1, it doesn't seem that this is good because it's duplicated.

In a word, I don't know when we use the retry_policy of Envoy and when we use the retry mechanism of endpoints (server1, server2 etc).

Furthermore, in a chain of request, if each node enables retry mechanism, I think it's dangerous because it may cause an explosion of retry even though Envoy supports circuit breaker to avoid too many retry requests...

**Comment by adisuissa** [comment]
Sorry, I'm not sure I full understand the question.
Configuration of a distributed system with multi-components is challenging, if elements such as retry mechanism are used. I guess in the case described above, the retry can be set on any of the steps between the app and server2 and its up to the owner of the system to decide where to configure retries.

**Comment by YvesZHI** [comment]
@adisuissa  Here is an example:
```
app --> envoy1 ---> server1 ---> envoy2 ---> server2`
```
The `server1` is a web service, which coded like this:
```
@RestController
class UserController {
    @PostMapping("/userinfo")
    User setUserInfo(@RequestBody User user) {
        return sendReqToServer2(user, retry = 3);  // this will send a http request to the envoy2
    }
}
```
As you see, when I send a http request to the `server1` , it will generate a http request and send it to the `server2` through the `envoy2`. And there is a parameter `retry = 3`, which means that if the http status code of the response coming from the `envoy2` is not 200, the `server1` will retry maximum 3 times.

Now if I configure `retry_policy` in the `envoy1` (num_retries = 3), it means that this gonna make maximum 3 * 3 retries. And if I configure `retry_policy` in the `envoy2` (num_retries = 3), it means that this gonna make maximum 3 * 3 * 3 retries. You see, the retry is exploding.

My backend is typical micro-service, so I'm asking if there is some solution about retry_policy from the official Envoy.

It doesn't seem that setting retry in the `server1` is not a good idea? Because I think the max_retries/retry_budget of the circuit breaker in Envoy couldn't limit this kind of retry, am I right?
