### ISSUE TITLE
Scorecard is unable to parse Dockerfiles correctly

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#31604]
We are getting a bunch of false positives wrt Dockerfile hash pinning

Surprisingly, it seems as though scorecard is unable to handle multi-stage docker builds correctly

**Comment by phlax** [comment]
cc @mmorel-35

**Comment by mmorel-35** [comment]
You might want create an [issue ](https://github.com/ossf/scorecard-action/issues) on ossf/scorecard-action

**Comment by phlax** [comment]
let me confirm the issue properly first

**Comment by phlax** [comment]
upstream issue/s https://github.com/ossf/scorecard/issues/2906

**Comment by phlax** [comment]
@mmorel-35 we have a stack of these 30+ - almost certainly this is why we dont have a higher score (altho its looking pretty good at this point)
