### ISSUE TITLE
Support FIPs crypto from WASM plugin

### ISSUE THREAD

**Issue by juanmolle** [envoyproxy/envoy#31615]
Support FIPs crypto from WASM plugin

Extend envoy capabilities to allows wasm filter use fips compliant crypto APIs

Related 
https://github.com/envoyproxy/envoy-wasm/issues/188
https://github.com/WebAssembly/wasi-crypto

**Comment by adisuissa** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
@juanmolle ProxyWasm API relies on the host to set up the TLS connections using the Envoy cluster definitions. If you have a FIPS build of Envoy, the modules will also be FIPS compliant. WASI is a distinct set of ABIs that are disjoint from ProxyWasm.

**Comment by juanmolle** [comment]
@kyessenov Thanks for the reply, my question is regarding other crypto operations we could need to do in a wasm filter like Hash, cert validation, etc.
Should the wasm itself find a FIP compliant library or the host provides APIs to perform those operation

**Comment by kyessenov** [comment]
ProxyWasm doesn't do any networking directly, it delegates to the host. You can read some of these attributes using `get_property` and [connection attributes](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#connection-attributes). You could implement TLS in Wasm using raw network calls in theory, but don't think anyone has done it in practice.

**Comment by juanmolle** [comment]
In case I need to implement a custom jwt authz policy in wasm, and need to validate the token, the library to do it should be FIPs. Is not an operation the wasm could delegate to the host, and if envoy is built for FIPs, the filter will be FIPs compliant too automatically?

**Comment by kyessenov** [comment]
IANAL - I think it's possible to make it FIPS compliant since you can use Envoy's FIPS cryptomodule, but you definitely have to certify the system as a whole.

**Comment by ramaraochavali** [comment]
@kyessenov The question that @juanmolle is asking is - if a WASM extension uses RUST libraries like simple JWT that are used to validate JWT + other crypto operations - how can we ensure they are FIPS compliant? They do not use boring SSL crypto operations. My understanding is the libraries used in filter needs to be FIPS compliant themselves. Is n't it the case?

**Comment by juanmolle** [comment]
I'm thinking to not use crypto library in WASM at all. instead of that, expose the already envoy FIPS library to the wasm through an API (an old issue is asking the same https://github.com/envoyproxy/envoy-wasm/issues/188 ). As an example if you need to validate a signature in LUA you can use the API https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#verifysignature which is using the FIPS module in the host.

**Comment by ramaraochavali** [comment]
That makes sense. But we need to expose those cryptographic primitives in the host calls which the WASM filter can make use of. @kyessenov  WDYT about this? It is not networking related TLS calls - it is more of app specific calls like validating JWT etc.

**Comment by patricio78** [comment]
> I'm thinking to not use crypto library in WASM at all. instead of that, expose the already envoy FIPS library to the wasm through an API (an old issue is asking the same [envoyproxy/envoy-wasm#188](https://github.com/envoyproxy/envoy-wasm/issues/188) ). As an example if you need to validate a signature in LUA you can use the API https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#verifysignature which I think is using the FIPS module in the host.

I've tried using the WASI crypto module that's mentioned in the issue, but it fails to load the WASM module due to the missing crypto imports.

**Comment by kyessenov** [comment]
I really can't answer this question. First, I'm not sure what the compliance requirements on JWT library is, I'm only aware of boringssl TLS certification. Second, FIPS requires the final binary to be signed and verified which I think is not possible with Wasm at all since it's not even a regular architecture. Please consult third parties that issue FIPS compliance, not engineers.

**Comment by patricio78** [comment]
We need the host to expose the cryptography functions so they can be called from the Wasm module. So I'd like to know whether those functions are exposed through wasi crypto, or as ffi, so they can be called from the Wasm module.

**Comment by kyessenov** [comment]
@patricio78 yeah that would be a reasonable way to be FIPS compliant if you use FIPS module from the host and expose it to Wasm via ABI. ProxyWasm doesn't have it though.

**Comment by patricio78** [comment]
> @patricio78 yeah that would be a reasonable way to be FIPS compliant if you use FIPS module from the host and expose it to Wasm via ABI. ProxyWasm doesn't have it though.

What about wasi-crypto ?

**Comment by PiotrSikora** [comment]
> Aparently there is already a set of capabilities available https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#envoy-v3-api-msg-extensions-wasm-v3-capabilityrestrictionconfig may be they can be extended
> 
> Ref: The capability names are given in the [Proxy-Wasm ABI](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT). Additionally, the following WASI capabilities from [this list](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md#modules) are implemented and can be allowed: fd_write, fd_read, fd_seek, fd_close, fd_fdstat_get, environ_get, environ_sizes_get, args_get, args_sizes_get, proc_exit, clock_time_get, random_get.

Capability restrictions limit which functions and/or hostcalls are available to Proxy-Wasm plugins, but they don't implement anything.

In order for wasi-crypto and/or custom crypto functions to work, they need to be implemented either directly in `proxy-wasm-cpp-host` or in a custom Envoy extension and exposed as Proxy-Wasm custom functions.

cc @mpwarres

**Comment by ramaraochavali** [comment]
>  or in a custom Envoy extension and exposed as Proxy-Wasm custom functions.

@PiotrSikora Do you have any reference to such custom function implementations as custom Envoy extension?

**Comment by kyessenov** [comment]
@ramaraochavali What Piotr is saying I think, is that your best option is to register crypto primitives from boringssl in [foreign.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/foreign.cc). Because it's an extension to ABI, these modules will only run on Envoy.

**Comment by ramaraochavali** [comment]
I see. Thank you. That seems a simpler option
