### ISSUE TITLE
DC causes coredump in my custom http filter

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31627]
I developed a custom http filter, a request with a custom header can make the filter send a http request to another server and do something with the response.  Many requests with the same custom header can use the same response.
```
Http::FilterHeadersStatus decodeHeaders(Http::RequestHeaderMap& headers) {
    custom_header = extractCustomHeader(headers);
    statusResponse = responseList.getStatus(custom_header);
    if (statusResponse == DONE) {  // the response has been received and stored, use it immediately
        doJob(responseList[custom_header], headers)
        return Http::FilterHeadersStatus::Continue;
    } elseif (statusResponse == NIL) {  // the response hasn't been found in the responseList, so send a request to the server to get one
        asyncSendRequestToServer(custom_header);
    } elseif (statusResponse == ONFLIGHT) {  // the request to the server has been sent but the response hasn't been received
        filterList.insert(this);
        return Http::FilterHeadersStatus::StopAllIterationAndBuffer;
    }
    ...
}

void onSuccess() {  // get response from the server successfully
    for_each (auto filter : filterList) {
        filter->getCallBacks()->dispatcher().post(
            [filter, headers]() {filter->doJob(response, headers);}
        );
    }
}
```

As you see, if some request with the custom header has sent the request to the server but the response hasn't been received, all of requests with the same custom header will be stored in a list `filterList`. After the response received, all of filters in the list can execute `doJob`.

It seems that everyting works fine. However, I just found if the client disconnects, which means the flags of Envoy would be `DC`, my http filter could get segmentation fault. I guess a `DC` would make its filter (one element in the `filterList`) be released. That's why I get segmentation fault. It seems that I need some mechanism of Envoy, which can tell me which filter has been released. Is there such a kind of mechanism?

**Comment by adisuissa** [comment]
It would be good to run this with ASAN and see what exactly causes the seg-fault.
Generally speaking, the filter's lifetime is the request's lifetime. After the request is no longer needed, the filter will be removed.

I suggest looking at the ext-proc filter is it seems to be doing something similar to what you are describing, if I understand correctly.
