### ISSUE TITLE
Unable to parse JSON as proto (INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoy.config.trace.v3.DatadogConfig'):

### ISSUE THREAD

**Issue by sujeets-toast** [envoyproxy/envoy#31649]
**Issue Template**

Datadog not working in windows container as sidecar. I used as Linux container it's working for me.

**Description:**
I am trying to run envoy, Datadog and dotnet application as sidecar. I am able to create the and run the container with envoy as sidecar without Datadog. But when adding the Datadog tracing i am gating the below issue in windows container.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/datadog.proto#config-trace-v3-datadogconfig

**Error:**
```shell
[2024-01-04 22:42:07.291][1896][critical][main] [source/server/server.cc:141] error initializing config '  .\envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoy.config.trace.v3.DatadogConfig'):
```
**Full yaml**

```shell
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9902
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: true
          request_id_extension:
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              use_request_id_for_trace_sampling: false
          tracing:
            provider:
              name: envoy.tracers.datadog
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.DatadogConfig
                collector_cluster: datadog_agent
                service_name: sa-envoy-proxy-web-service
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              # path: /dev/stdout
              # log_format:
              #   text_format_source:
              #     inline_string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH):256% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" \"%RESP(X-AMZN-RequestId)%\" \"%REQ(X-DATADOG-TRACE-ID)%\" \"%REQ(X-DATADOG-PARENT-ID)%\"\n"
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend_service
              domains:
              - "*"
              routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: sa-envoy-proxy-cluster
          http_filters:
          - name: envoy.filters.http.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
              pass_through_mode: false
              headers:
                - exact_match: /healthcheck
                  name: :path
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              suppress_envoy_headers: true
          use_remote_address: true
  clusters:
  - name: sa-envoy-proxy-cluster
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: sa-envoy-proxy-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.89.194.61 # application host ip
                port_value: 80
                
  - name: datadog_agent
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: datadog_agent
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 8126

admin:
  # access_log_path: "./logs/logs.txt"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9201
```

**Envoy Dockerfile**
```shell
FROM envoyproxy/envoy-windows:v1.28-latest
# FROM envoyproxy/envoy-windows:v1.19-latest
EXPOSE 5000
EXPOSE 9201
EXPOSE 9202
COPY envoy.yaml './envoy.yaml'
COPY start_envoy.ps1 './start_envoy.ps1'
ENTRYPOINT ["powershell.exe", "./start_envoy.ps1"]
```

**Reference Url:**
https://docs.datadoghq.com/tracing/trace_collection/proxy_setup/?tab=envoy

**Comment by adisuissa** [comment]
cc @cgilmour @dgoffredo

**Comment by dgoffredo** [comment]
I don't know why that would happen, and am not familiar with Windows.

The only Windows references that I see are in the unit tests of some of the tracers, including Datadog's:
```
david@ein:~/src/envoy/test/extensions/tracers$ git grep -i windows
common/ot/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
common/ot/BUILD:    tags = ["skip_on_windows"],
datadog/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
datadog/BUILD:    tags = ["skip_on_windows"],
dynamic_ot/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
dynamic_ot/BUILD:    tags = ["skip_on_windows"],
dynamic_ot/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
dynamic_ot/BUILD:    tags = ["skip_on_windows"],
opencensus/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
opencensus/BUILD:    tags = ["skip_on_windows"],
opencensus/BUILD:    # TODO(wrowe): envoy_extension_ rules don't currently exclude windows extensions
opencensus/BUILD:    tags = ["skip_on_windows"],
```

Might there be some policy in Envoy like "if the unit tests are skipped for a component, then exclude it also from the release build"?

**Comment by phlax** [comment]
its specifically excluded i think see here https://github.com/envoyproxy/envoy/blob/78814130c7427236bf222824f03d813be00f9694/bazel/repositories.bzl#L9-L17

**Comment by dgoffredo** [comment]
Thanks, @phlax. That explains that.

We haven't tested [dd-trace-cpp][1] on Windows. It probably wouldn't be _too_ much trouble to get it working, but Datadog has not received many requests for C++ on Windows, and I don't (yet) have a Windows development environment.

I've created [an issue][2] in dd-trace-cpp to track this. I don't know what its priority will be.

[1]: https://github.com/DataDog/dd-trace-cpp
[2]: https://github.com/DataDog/dd-trace-cpp/issues/84

**Comment by sujeets-toast** [comment]
Hi, Any update on this issue?

**Comment by dgoffredo** [comment]
My teammate and I are playing with Windows builds (via CMake and Bazel, respectively). There is quite some work to do, and it is not a priority, but we are chipping away at it. Yesterday I was unable to get Envoy to build on Windows (`quiche` has been causing trouble), so I'll have to revisit that. There's also the question of whether the particular Windows toolchain used for Envoy releases will accept dd-trace-cpp's code. Mine and my teammate's setups disagree on whether the code should compile.

- [PR][1] for my attempt at building on Windows via Bazel, with the goal of dd-trace-cpp Windows builds for Envoy.
- [PR draft][2] for my teammate's attempt at building on Windows via CMake.

Is this a blocker for you, @sujeets-toast? If so, you might consider using Envoy's [OpenTelemetry][3] tracing extension in the interim. The Datadog Agent can be [configured][4] to listen on an [OTLP][5] interface, which then you can designate as the "collector" in the OpenTelemetry configuration. I can't find an example of this, but it should be possible.

[1]: https://github.com/DataDog/dd-trace-cpp/pull/85
[2]: https://github.com/DataDog/dd-trace-cpp/pull/87
[3]: https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry
[4]: https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent
[5]: https://opentelemetry.io/docs/specs/otel/protocol/
