### ISSUE TITLE
New target for CI based binary build

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31672]
*Title*: *Adding new target for ./ci/do_ci.sh to build contrib-debug image*

*Description*:
Can we achieve the same as `bazel build -c dbg //contrib/exe:envoy-static` achieves using `./ci/do_ci.sh`? But, in [ci/README.md](https://github.com/envoyproxy/envoy/tree/main/ci#on-linux), I can see two different targets- `debug` and `dev.contrib`, but what if I want to achieve the output combining  these two targets as the command does mentioned earlier? But when run `ENVOY_DOCKER_IN_DOCKER=1 ./ci/run_envoy_docker.sh './ci/do_ci.sh docker'`, I still get the intended image `envoyproxy/envoy-contrib-debug-dev`. 

Moreover, can we build for target `dev.contrib` binary with 0 test running? 

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build

**Comment by phlax** [comment]
probably the easiest is to use the default path - both the docs you referenced need some work and may not be up-to-date

```console
$ ./ci/do_ci release.server_only
```

this creates the following (without running tests)

```console
$ tar tf ~/Downloads/release.tar.zst 
dbg/
dbg/envoy
dbg/envoy-contrib
dbg/envoy-contrib.dwp
dbg/envoy.dwp
envoy
envoy-contrib
utils/
utils/su-exec

```

its built with `-c opt` - not sure if that matters 

obviously this has a bit more than you want in it 

if we were to adapt any targets it would be this one i think, the others are ~deprecated or at least need some updating

**Comment by shiponcs** [comment]
Thanks @phlax 
I have run dbg/envoy-contrib to debug by attaching it CLion and set some break points but they are not hit. But when I built the envoy-contrib with bazel in local machine by passing -c dbg, the breakpoints are properly hit. What could be the reason?

**Comment by phlax** [comment]
not sure tbh - when you tried debugging i assume you extracted the binary from the tarball - did you also extract the dwp file?

i believe that file needs to present (adjacent i think) for debugging to work

if its not possible to debug using the standard build im wondering whether its any use including the dbg build there

**Comment by shiponcs** [comment]
> when you tried debugging i assume you extracted the binary from the tarball - did you also extract the dwp file?
Yes, I have extracted release.tar.zst. No, I didn't extract dwp file. 
>i believe that file needs to present (adjacent i think) for debugging to work.
Yes file were present- I opened the Clion in the root dir of envoy. It worked as expected when I use my own built debug binary. I just replaced the binary and it didn't work. 
> if its not possible to debug using the standard build im wondering whether its any use including the dbg build there
If binary is created with proper debug symbols, it should work I believe.

**Comment by phlax** [comment]
i think you need to extract the dwp file and ensure its placed adjacent to the envoy binary (not 100% i didnt try it)
