### ISSUE TITLE
Envoy accepting new connections after the draining is started

### ISSUE THREAD

**Issue by pramodrj07** [envoyproxy/envoy#31670]
*Title*: *Is the behavior of Envoy accepting new connections after it has entered draining an expected behavior? *

*Description*:
> I see that when initiating a new connection when Envoy is already in drain mode is going through and i am getting back the expected response. 

*Repro steps*:
> 1. Install the envoy.
> 2. make a curl command to the admin endpoint - curl -X POST "http://localhost:9901/drain_listeners?graceful"
> 3. Verify that draining is initiated from the envoy logs.
> 3. initiate the connection to the envoy as before and verify it is going through

>. Would like to like to know if this is expected behavior or has anyone seen this behavior and have taken corrective actions. We are using envoy version 1.23

**Comment by zhangbo1882** [comment]
By default, Envoy will discourage requests for some period of time (as determined by [--drain-time-s](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-drain-time-s)) but continue accepting new connections until the drain timeout.

**Comment by phlax** [comment]
> We are using envoy version 1.23

heads up @pramodrj07 that 1.23 has not been supported for some time
