### ISSUE TITLE
Design Proposal: Refactor region_provider_impl code and use within aws_request_signer extension

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#31676]
Title: Reuse region_provider_impl code within aws_request_signer extension

Description:
Short proposal to consolidate region code within the aws_request_signer extension

The aws_request_signer extension supports only mandatory region specification within the Envoy configuration. This proposal aims to create consistency between aws_request_signer and grpc_credentials aws_iam extensions, to allow region to be retrieved outside of the Envoy configuration aligned with the AWS SDK behaviour.

This proposal aims to:
- Change the region specifier protobuf to optional instead of mandatory
- If signing_algorithm = AWS_SIGV4A, require the region field and raise EnvoyException if not present. This is because current implementation using a region_set for AWS_SIGV4A has undefined behaviour in the AWS SDK at present (ie, there is no environment or config specifier for a region_set)
- If signing_algorithm = AWS_SIGV4 and region is not present in envoy configuration, pull region from environment or config file, aligned with the AWS SDK behaviour
- If still not found, raise EnvoyException during config parsing stage

To achieve this, there would be some code refactoring required:
- Creation of a profile provider, which has similar refresh/timer behaviour as the credential provider. The profile provider would have a chain of sources, which are called in the same order as the AWS SDK
- Move profile/config parsing code from credential provider and into the profile provider
- Modify the credential provider to call out to profile provider
- Modify the grpc_credentials aws_iam region handling code to also use profile provider

There would be no behavior change to existing Envoy users of this extension.

@suniltheta @mattklein123 @ivitjuk @lavignes

**Comment by suniltheta** [comment]
I like the idea to make the behavior of aws request signing filter to align with aws iam grpc plugin, *i.e.,* to make region field optional.

We can start with picking the usecase one by one and address those.

**Comment by nbaws** [comment]
will close as PR looks to be merged
