### ISSUE TITLE
Is it possible to see the payload and/or the headers of requests going through the envoy?

### ISSUE THREAD

**Issue by Sumu-Ning** [envoyproxy/envoy#31683]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Is it possible to see the payload and/or the headers of requests going through the envoy?*

*Description*:
> We are considering the possibility of monitoring duplicate requests between different services to identify the opportunities for caching in case some service owner does not realize it. We are thinking about grabbing the request content somewhere in our service mesh, hash it and persist it for further analysis. I am wondering whether it is possible to do so at the envoy level (We will need to access the request payload / headers to calculate the hash)? If possible, we might sample such operation at a small percentage, so hopefully, it does not impact the performance too much. Thank you!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zhangbo1882** [comment]
You can configure the access log to show the header.

**Comment by Sumu-Ning** [comment]
>You can configure the access log to show the header.

But we still cannot access the request body in access log, I think? @zhangbo1882

**Comment by Sumu-Ning** [comment]
> you might also want to look at the tap filter https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter

Thank you @phlax ! Does the tap filter output support sinking to some customized processor? We don't want to log the raw content for security and privacy reasons.

**Comment by phlax** [comment]
not sure i didnt use it before but my reading of the docs here is that you can either use/implement a sink or stream from an admin endpoint https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/tap/v3/common.proto#envoy-v3-api-msg-config-tap-v3-outputsink

**Comment by Sumu-Ning** [comment]
Thank you, I will take a closer look!
