### ISSUE TITLE
drain connection per listener

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#31690]
Currently envoy can only drain all listeners. 
It seems that we can not drain a specify listener ?
In our environment, there are several available zones. Sometimes we need to exit the traffic from one available zone for some maintenance work for  a specify VIP (abc.com), we need to drain the specify listener to make the client recreate new connections to other available zone to avoid traffic impact. 
envoy1 and envoy2 are both the member of abc.com, when we exit traffic, we will disable envoy1 from the member of abc.com.

client--->abc.com--->envoy1 (available zones 1)--->server1

client--->abc.com--->envoy2 (available zones 2)--->server2

But if client has a long-living connection, although we disable envoy1 from abc.com (FQDN layer), the client will still send traffic to envoy1. If we can drain the listener in envoy1, envoy1 will send HTTP-CLOSE to client and client will recreate a new connection and to envoy2.

**Comment by zhangbo1882** [comment]
If it is a reasonable feature request, I can help implement it.

**Comment by kyessenov** [comment]
Envoy can drain individual filter chains in the listeners. It does a structural diff on LDS update, so only affected filter chains are drained.

**Comment by zhangbo1882** [comment]
@kyessenov , so when I want to drain a specify listener, which API should I use to make the drain happen?
I know that we can use admin interface to drain all listeners. (https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html#post--drain_listeners?graceful)

**Comment by kyessenov** [comment]
@zhangbo1882 Are you asking for an admin API to drain per listener? I don't think that exists. I was referring to LDS-driven drain.

**Comment by zhangbo1882** [comment]
@kyessenov , yes, I am asking for an admin API to drain per listener. 
In our environment, we always do the traffic migration for a specify VIP from one available zone to another. That means we need drain the connection per the specify listener to make all clients do not send the traffic to the old envoy.
