### ISSUE TITLE
High CPU usage when oghttp2 enabled

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#31710]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:  High CPU usage in envoyproxy when `oghttp2` lib is enabled by default.

*Description*:

We saw high CPU usage in envoyproxy when `oghttp2` lib is enabled by default in https://github.com/envoyproxy/envoy/pull/31086. `recv-q` was piling up and connection hang.

We did CPU profiling and saw `oghttp2` was using most of resource:
```
File: envoy
Type: cpu
Showing nodes accounting for 30.25s, 96.25% of 31.43s total
Dropped 349 nodes (cum <= 0.16s)
      flat  flat%   sum%        cum   cum%
    14.35s 45.66% 45.66%     14.36s 45.69%  http2::adapter::OgHttp2Session::WriteForStream
    11.95s 38.02% 83.68%     11.95s 38.02%  http2::PriorityWriteScheduler::MarkStreamNotReady
     1.30s  4.14% 87.81%     14.70s 46.77%  http2::adapter::OgHttp2Session::Send
     1.17s  3.72% 91.54%      1.17s  3.72%  Envoy::Logger::Registry::allLoggers
     0.65s  2.07% 93.60%      1.39s  4.42%  Envoy::Logger::Registry::getLog
     0.57s  1.81% 95.42%      0.57s  1.81%  quiche::getVerbosityLogThreshold
     0.17s  0.54% 95.96%      0.17s  0.54%  send
     0.04s  0.13% 96.09%      0.65s  2.07%  std::__1::__function::__func::operator()
     0.02s 0.064% 96.15%      0.19s   0.6%  Envoy::Router::Filter::decodeHeaders
     0.01s 0.032% 96.18%      0.59s  1.88%  Envoy::Network::ConnectionImpl::onFileEvent
     0.01s 0.032% 96.21%      0.76s  2.42%  event_base_loop
     0.01s 0.032% 96.25%      0.70s  2.23%  event_process_active_single_queue
         0     0% 96.25%     30.40s 96.72%  <unknown>
         0     0% 96.25%      0.16s  0.51%  Envoy::Api::OsSysCallsImpl::send
         0     0% 96.25%      0.41s  1.30%  Envoy::Event::FileEventImpl::assignEvents()::$_1::__invoke
         0     0% 96.25%      0.25s   0.8%  Envoy::Http::Http2::ConnectionImpl::dispatch
         0     0% 96.25%      0.39s  1.24%  Envoy::Network::ConnectionImpl::onReadReady
         0     0% 96.25%      0.19s   0.6%  Envoy::Network::ConnectionImpl::onWriteReady
         0     0% 96.25%      0.31s  0.99%  Envoy::Network::FilterManagerImpl::onContinueReading
         0     0% 96.25%      0.19s   0.6%  Envoy::Network::IoSocketHandleImpl::write
         0     0% 96.25%      0.19s   0.6%  Envoy::Network::IoSocketHandleImpl::writev
         0     0% 96.25%      0.19s   0.6%  Envoy::Network::RawBufferSocket::doWrite
         0     0% 96.25%      0.72s  2.29%  Envoy::Server::WorkerImpl::threadRoutine
         0     0% 96.25%      0.72s  2.29%  Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda(void*)#1}::__invoke
         0     0% 96.25%      0.72s  2.29%  clone
         0     0% 96.25%      0.20s  0.64%  http2::HeadersPayloadDecoder::StartDecodingPayload
         0     0% 96.25%      0.23s  0.73%  http2::Http2DecoderAdapter::ProcessInput
         0     0% 96.25%      0.23s  0.73%  http2::Http2DecoderAdapter::ProcessInputFrame
         0     0% 96.25%      0.23s  0.73%  http2::Http2FrameDecoder::StartDecodingPayload
         0     0% 96.25%      0.23s  0.73%  http2::adapter::OgHttp2Session::ProcessBytes
         0     0% 96.25%      0.23s  0.73%  http2::adapter::OgHttp2Session::ProcessBytesImpl
         0     0% 96.25%      0.72s  2.29%  start_thread
```

Here is the profiling data
[profile (7).pb.gz](https://github.com/envoyproxy/envoy/files/13866659/profile.7.pb.gz)

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by milton0825** [comment]
@alyssawilk @birenroy

**Comment by birenroy** [comment]
I think we need to remove the stream ID from the set here:
https://github.com/google/quiche/blob/6e74ac6e87436ef19c44a0784921b8311025dad4/quiche/http2/adapter/oghttp2_session.cc#L632

I will attempt to repro the issue in a unit test and get a fix in ASAP.

**Comment by birenroy** [comment]
@diannahu and I narrowed this issue down, and I have a repro in a unit test. The code defect is different from what I originally thought.

**Comment by RyanTheOptimist** [comment]
@birenroy with 31788 landed, we can close this, right?

**Comment by birenroy** [comment]
Yes, thank you for handling the QUICHE merge, @RyanTheOptimist.

**Comment by RyanTheOptimist** [comment]
Awesome! Thanks for the fix!
