### ISSUE TITLE
TCP Challenge Ack and envoy SO_REUSEADDR 

### ISSUE THREAD

**Issue by mchandler-plato** [envoyproxy/envoy#31729]
*Title*:  TCP Challenge Ack and envoy SO_REUSEADDR 

*Description*:
Plato is using envoy in L2 mode behind a AWS NLB (no preserve source ip & proxy protocol, no cross zone) and we have been seeing our average request time for hitting envoy (returning 404) spike to over a second every now and then.

Tracing this down I have found that the amazon linux 2 (kernel 5.10) that envoy is running on is sending a challenge ack causing the client to wait a second and then restart the tcp connection (same port) and every thing works fine their after. With the way the NLB from AWS is configured it is doing NAT and using the same ip for hitting the envoy host every time but the strange thing is that wireshark (i.e. tcpdump) traces dont show that the port was reused recently but still the linux kernel is triggering a tcp challenge ack. 

The one thing that has made this issue almost disappear is disabling `SO_REUSEADDR` by disabling `enable_reuse_port` in envoy listener.

Note: envoy is running in k8s with host networking enabled on a 2 core ec2 node to it self.
 
Has any one seen this before? 
Is there any other envoy settings that might cause the linux kernel to trigger this bad behavior?

**Comment by phlax** [comment]
cc @mattklein123 @alyssawilk
