### ISSUE TITLE
Broken config for ring hash LB with minimum_ring_size of 0

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#31724]
Ring hash load balancer config with `minimum_ring_size` set to 0 is accepted however it results in host selection always failing.

Envoy need to have config validation that either rejects minimum_ring_size value of 0 or uses the default value of 1024 in this case.

**Comment by phlax** [comment]
cc @wbpcode @nezdolik

**Comment by antoniovleonti** [comment]
Hello, I'm beginning work on this.
