### ISSUE TITLE
The mobile release CI job has been failing on CI for the last few weeks

### ISSUE THREAD

**Issue by abeyad** [envoyproxy/envoy#31731]
This seems related to the CI framework refactor.

https://github.com/envoyproxy/envoy-ci-staging/actions/workflows/mobile-release.yml

Don't see any helpful error messages but sometimes it seems to fail on gpg signing.

cc @phlax

**Comment by phlax** [comment]
yeah - im aware - i just didnt get to it - ill try and fix this week

**Comment by abeyad** [comment]
no worries, you don't need to treat it as super urgent since it's not blocking anyone right now, but within the next few weeks would be great.  thanks @phlax !

**Comment by abeyad** [comment]
mobile release is still failing: https://github.com/envoyproxy/envoy-ci-staging/actions/runs/7784862169

**Comment by abeyad** [comment]
@phlax there is renewed interest for the Maven repository publish - any ideas on what the issue might be?

**Comment by phlax** [comment]
@abeyad apologies it took so long to follow up on this - the reason for failure is that staging repo doesnt have the keys (phew!) to actually publish

checking maven and the correct ci and this seems to be working as expected

**Comment by phlax** [comment]
yeah not on staging - ie https://github.com/envoyproxy/envoy/actions/workflows/mobile-release.yml

**Comment by abeyad** [comment]
so will staging always be the source of publishing to maven?

**Comment by phlax** [comment]
it never will - thats kinda the point - it doesnt have the keys - only this repo does

**Comment by abeyad** [comment]
> it never will - thats kinda the point - it doesnt have the keys - only this repo does

understood... so the goal is to always continue to publish maven artifacts from the staging repo which has the correct private keys?

**Comment by abeyad** [comment]
and yup, looks like it's working: https://central.sonatype.com/search?q=envoy%20mobile
Last artifact published 3 hours ago.

Thanks @phlax !
