### ISSUE TITLE
Adaptive Concurrency stats should use histogram instead of gauge

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [envoyproxy/envoy#31752]
Most of adaptive concurrency stats use the  gauge kind ([see here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.h#L31-L37)). This means that, while the adaptive concurrency evaluation window is typically once every 100ms, the gauage value is typically read much less than that (e.g. once per 30 seconds), meaning that we get one sample out of every 300, which eliminates a lot of granularity.

I believe a better choice for most of these stats should be a histogram. I'm struggling to extract any value out of these metrics with their present granularity. 

Any thoughts on that?

I can open the PR if there is an agreement

**Comment by phlax** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
Upgrading to a histogram makes sense to me, though we might want to leave the gauge in place also so that existing users get continuity, though as Abdul noted the previous gauge was pretty low-res.

@tonya11en may have more informed opinions about the utility of a histogram here.

**Comment by tonya11en** [comment]
I think it would help to know why you want to monitor the gradient value. Can you tell us more about why you want to know the gradient value? I agree that the metric isn't very helpful, but a histogram isn't much better. 

I assume you're trying to understand the behavior of the concurrency limit? If so, you'd likely be better off looking at the sampled RTT value and how it changes through time. I'll stand by for more details.

**Comment by AbdulRahmanAlHamali** [comment]
Thanks for the response folks. I'm enabling adaptive concurrency for a few services owned by different teams on my end, and I want to provide them with a dashboard that they can look at and understand why shedding is happening when it happens. This helps with confidence, but also can help teams distinguish between when adaptive concurrency is shedding rightfully, or when a bug in the implementation is causing the shedding.

I tried using the sample rtt value as well as tony suggested. In fact, I recreated the gradient formula in PromQL:

```
avg(clamp_min(clamp_max(envoy_http_adaptive_concurrency_gradient_controller_min_rtt_msecs{}*1.25/envoy_http_adaptive_concurrency_gradient_controller_sample_rtt_msecs{}, 2.0), 0.5))
```

but the sample rtt is also a gauge, so it suffers the same lack of granularity. We're seeing instances of shedding, where this value is barely moving

**Comment by tonya11en** [comment]
> Thanks for the response folks. I'm enabling adaptive concurrency for a few services owned by different teams on my end, and I want to provide them with a dashboard that they can look at and understand why shedding is happening when it happens. This helps with confidence, but also can help teams distinguish between when adaptive concurrency is shedding rightfully, or when a bug in the implementation is causing the shedding.
> 
> 
> 
> I tried using the sample rtt value as well as tony suggested. In fact, I recreated the gradient formula in PromQL:
> 
> 
> 
> ```
> 
> avg(clamp_min(clamp_max(envoy_http_adaptive_concurrency_gradient_controller_min_rtt_msecs{}*1.25/envoy_http_adaptive_concurrency_gradient_controller_sample_rtt_msecs{}, 2.0), 0.5))
> 
> ```
> 
> 
> 
> but the sample rtt is also a gauge, so it suffers the same lack of granularity. We're seeing instances of shedding, where this value is barely moving 

This filter's default values are awful. I'd recommend:
- changing the min_concurrency value to something like 25-50 (default is 3!). You ideally want to set this to whatever your "steady state" active requests are. This is by far the most important thing to change. 
- Change the default interval from 100ms to 500ms or even 1000ms. These values are more reasonable and make that sample RTT gauge more useful because the value isn't changing so much.
- Change the aggregate percentile to the percentile you want to keep stable, so p90 or p95 instead of the default p50. 

Also, do you have retries enabled with the previous host predicate? This is needed because the min rtt calculation can cause load shedding. See the note in the filter docs about this.

**Comment by AbdulRahmanAlHamali** [comment]
> changing the min_concurrency value to something like 25-50 (default is 3!). You ideally want to set this to whatever your "steady state" active requests are. This is by far the most important thing to change.

Yeah, I've found it too low as well, but it seems to work so I didn't want to mess with it. We have retries on 503s so the shedding baseline that we have is inconsequential. 

> Change the default interval from 100ms to 500ms or even 1000ms. These values are more reasonable and make that sample RTT gauge more useful because the value isn't changing so much.

True, that would make the metrics much better, but in terms of behaviour, could you elaborate why you think it's more reasonable? 100ms seems good enough to allow adaptive concurrency to quickly react to spikes

> Change the aggregate percentile to the percentile you want to keep stable, so p90 or p95 instead of the default p50.

Good callout. I remember it being p90 for some reason, but now that I look at the docs I see p50. I'll experiment with the different options to see which works best.

> Also, do you have retries enabled with the previous host predicate? This is needed because the min rtt calculation can cause load shedding. See the note in the filter docs about this.
Yup, I'm retrying in another layer for that exact reason.

So, you don't think that changing the sample rtt (and possibly the gradient) to histograms is a good idea?

**Comment by tonya11en** [comment]
> True, that would make the metrics much better, but in terms of behaviour, could you elaborate why you think it's more reasonable? 100ms seems good enough to allow adaptive concurrency to quickly react to spikes

With a larger interval, you are more likely to get more samples and have a more stable rtt calculation. It's much less likely to have dramatic swings, especially for tails like p90/95. This results in more stable load shedding behavior.

> So, you don't think that changing the sample rtt (and possibly the gradient) to histograms is a good idea?

I just don't think the information it gives will be actionable. Gradient and sample rtt values will show up as changes to the concurrency limit. Increasing the sampling interval to 500-1000ms will make the changes less frequent as well.
