### ISSUE TITLE
OCSP Stapling

### ISSUE THREAD

**Issue by zetaj** [envoyproxy/envoy#3178]
*Title*: *OCSP Stapling*

*Description*:
>We are trying to use Envoy as secure ingress layer. Just wondering if envoy v1.6.0 support this feature or is there any plan to have it in coming feature?

**Comment by mattklein123** [comment]
Not supported currently. cc @PiotrSikora @ggreenway

**Comment by ggreenway** [comment]
It's on my list of things I'd like to support eventually, but I have no firm plans yet.

**Comment by dontreboot** [comment]
@ggreenway Is this something that is planned for near future?

**Comment by ManishMehta** [comment]
@ggreenway @PiotrSikora Refreshing this thread.
What are one's options today if s/he wanted OCSP stapling with Envoy?

**Comment by zerocool-kor** [comment]
+1

**Comment by marsom** [comment]
+1

**Comment by ericmoret** [comment]
Any update on that front? This seems a rather important security feature.

**Comment by zuercher** [comment]
As I mentioned in the last Envoy community meeting, I wrote up a design doc describing how this could be implemented in Envoy. I'm soliciting comments and will also post this in the Envoy Slack.

https://docs.google.com/document/d/14Ji0Vq7Xbe9LXM6IsWQo8mgEnOB8Bo6TH75sSmFbCEE/edit

**Comment by ggreenway** [comment]
Fixed in #12685
