### ISSUE TITLE
Redis Fault-Injection knobs

### ISSUE THREAD

**Issue by lafikl** [envoyproxy/envoy#3179]
This is a feature request for adding fault injection knobs that understands Redis' protocol.
I believe this level of granularity is beneficial for the following reasons:
Redis is used in so many use cases in a single process, for example, you would find a single service using it for session storage, rate limiting, caching, and/or kicking off background jobs.
So having the ability to scope the faults to a specific command is desirable, to limit the testing to an individual use case at a time.

Such knobs should provide the following fault modes:
- Latency
- Response Drop
- Empty response
- Blackhole (leaving a command hanging without replying)

The blast radius of these faults can be limited by:
- Command to the match the fault for. For example `HGET`
- Client IP:Port. This should be longest common prefix matching to allow for subnet matching as well.
- Percentage to apply to the matching selection rules.

*Relevant Links*:
What I'm describing is in nature the same things I've built in [RedFI](http://openfip.github.io/redfi), so if you take a look at it you would understand the ideas.

**Comment by mattklein123** [comment]
I think this was done by @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg
