### ISSUE TITLE
The  %RESPONSE_FLAGS% section in the access_log doc is not up-to-date

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#31790]
*Title*: *The  %RESPONSE_FLAGS% section in the access_log doc is not up-to-date*

*Description*:
>Describe the issue.

There are some flags, which are defined in the code, don't show up in the  %RESPONSE_FLAGS% section of the access_log doc https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/observability/access_log/usage.rst

For example, the `RFCF` and `NFCF` flags are represented in https://github.com/envoyproxy/envoy/blob/8b906359d07571929e17429ff65128125dcbf297/source/common/stream_info/utility.h#L16, but not in https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/observability/access_log/usage.rst

**Comment by phlax** [comment]
@spacewander would you be able to PR a fix for this ?

**Comment by spacewander** [comment]
> @spacewander would you be able to PR a fix for this ?

OK, I will submit the PR later.
