### ISSUE TITLE
Please stop publishing unreleased versions to Docker Hub

### ISSUE THREAD

**Issue by sathieu** [envoyproxy/envoy#31836]
v1.29.0 is not yet released, but Docker images are here: https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=v1.29.0

This leads to using devel version when using tools like renovate or dependabot.

**Comment by phlax** [comment]
hi - @sathieu thanks for bringing this to our attention - this is my fault testing the release ill delete these images now

**Comment by phlax** [comment]
seems deleting the images is not as straightforward as i thought - release is due today - not 100% yet if we will meet the deadline but its imminent. What i will do is make sure this doesnt happen in future. Apologies

**Comment by phlax** [comment]
closing this as the correct images are now in place and remedy going forward needs to be applied elswhere

**Comment by phlax** [comment]
this has unfortunately happened again (apologies i thought i had fixed it) but only for 1.26 branch - i will delete the pushed images now
