### ISSUE TITLE
LC Trie: support nested prefixes in sublinear worst-case time

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#3188]
*Description*:
This is a more detailed version of a TODO comment I put in PR [2614](https://github.com/envoyproxy/envoy/pull/2614). When I added nested prefix support to the LC trie implementation, I took the shortcut of putting nested prefixes in a list under their parent prefix. That works well in many cases, but there are some real-world situations where this can lead to performance problems: for example, someone adding a short prefix to an existing large set of prefix/tag combinations.

One potentially simple solution would be to preprocess the input list of prefixes by:

1. Inserting all the prefixes into a binary trie,
1. Iterating through the trie to apply each prefix's tag(s) to its descendants,
1. Pushing all the prefixes to the leaves ([example](https://raminaji.wordpress.com/unibit-tries/)),
1. And finally extracting the resulting prefix/tags combinations from the leaves of the binary trie and using those as the input to the LC trie construction algorithm. (Because these new prefixes are the leaves of a trie, they're guaranteed to be non-overlapping.)

I'm willing to contribute an implementation for this.

**Comment by mattklein123** [comment]
@brian-pane sounds reasonable to me though as other perf discussions we have had it would be nice to have a benchmark so we can compare to make sure the extra complexity is really worth it.
