### ISSUE TITLE
Make stats sink flush more flexible

### ISSUE THREAD

**Issue by mrice32** [envoyproxy/envoy#3190]
*Description*: There are use cases for stats sinks that want to export a small subset of Envoy's statistics.  The `Hystrix` sink that's currently in development is a good example of this.  Right now, each flush generates a `flushCounter()` call into the sink (and a latch on the value) for each `Counter` defined in Envoy.  The behavior is similar for gauges.  For sinks that just want to query small numbers of stats on each flush, I was thinking it might make sense to be able to disable the counter and gauge loops [here](https://github.com/envoyproxy/envoy/blob/master/source/server/server.cc#L108) based on a configuration option.  The sinks would ultimately grab these counters and gauges from the server's stats store or stats structs that are available through the server interface (like cluster and listener stats).  If we want sinks to be more independently configured, we could make this configured on a per-sink basis and omit these calls only if all sinks explicitly disable it?  I just wanted to float this proposal to see if there were any objections to adding this option.  Furthermore, if anyone has other ideas for making Envoy more amenable to these sorts of sinks, I'd be interested to hear them.

cc @trabetti @jmarantz

**Comment by mattklein123** [comment]
@mrice32 one other feature I would really like and we would use at Lyft is some way to actually flush different stats at different intervals. E.g., high priority stats could be flushed at 500ms interval, but only for very few stats, vs. a longer flush interval for less critical stats.

**Comment by mrice32** [comment]
@mattklein123 would this be a user-configurable bunch of stats?  Or would Envoy have a specific set of stats that are designated as "high priority"?

I have another rough idea of something that would be nice for sinks that want to heavily filter stats (and/or link them to other proprietary representations of stats): a registration mechanism such that sinks are notified when stats are created and destroyed.  Ideally, this could be batched to reduce overhead, but I would need to spend some time thinking about how we could build this such that it wouldn't have really bad perf implications.

**Comment by mattklein123** [comment]
> @mattklein123 would this be a user-configurable bunch of stats? Or would Envoy have a specific set of stats that are designated as "high priority"?

I was thinking user configurable, probably allowing prefix/regex selection.

> I have another rough idea of something that would be nice for sinks that want to heavily filter stats (and/or link them to other proprietary representations of stats): a registration mechanism such that sinks are notified when stats are created and destroyed. Ideally, this could be batched to reduce overhead, but I would need to spend some time thinking about how we could build this such that it wouldn't have really bad perf implications.

Yeah that would be useful also.

**Comment by mattklein123** [comment]
This is complete.
