### ISSUE TITLE
Http request rate limiter is not accurate

### ISSUE THREAD

**Issue by zhiyong-gayang** [envoyproxy/envoy#31921]
# Overview
This package setups a local repro of incorrect http request rate limit behavior.
[429repro.zip](https://github.com/envoyproxy/envoy/files/14005954/429repro.zip)

- docker-compose.yaml start a single enovy instance and a backend service (echo), the backend service is part of the envoy samples (envoy/examples/shared/echo)
- envoy_config_generate.go generates the envoy config file to repro this issuse.
    - it generates 5000 filter chains and each match on server names and each one has http rate limit filter and bandwidth limit filter.
    - each filter chain has its own metric prefix so to generate different metrics.
    - stats_sinks to mock metrics are consumed.
- traffic.go generate consistent traffic to repro this issue.

# Lcoal Setup (on ubuntu20.04)

## Install Dnsmasq for dns resolve, so to send requests to match all the filter chains.
```
sudo systemctl disable --now systemd-resolved
sudo apt install dnsmasq
echo "address=/example.com/127.0.0.1" >> /etc/dnsmasq.conf
sudo systemctl restart dnsmasq
```
## Install go
```
curl -O https://dl.google.com/go/go1.20.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
```

## generate envoy config
```
go run envoy_config_generate.go
```

# Repro steps

## start
```
docker-compose up -d
```
Test if envoy started successfully:

curl https://echo-100.example.com:8000 -ik

## generate consistent traffic for all endpoints
go run traffic.go -duration=300s -count=5000 -interval=10ms

## generate accuate QPS for single endpoint to repro the local request rate limit issue
The rate limit is 100, we test with 70.

Use load testing tool [labench](https://github.com/microsoft/LaBench) to generate accuate QPS load:

The labench config is:
```
RequestRatePerSec: 70
Duration: 60s
Clients: 50
RequestTimeout: 100s
ReuseConnections: true
Protocol: HTTP/1
Request:
  HTTPMethod: POST
  URL: https://echo-1.example.com:8000/
```

# Result
```
timeStart = 2024-01-21 08:35:38 +0000 UTC
Protocol: HTTP/1
ExpectedInterval = 14.285714ms, Detected OS timer resolution = 100ns
Using sleeping ticker
Ticks=4200, TimelyTicks = 4200, MissedTicks = 0, 100.00% good
Sends=4200, TimelySends = 4200, LateSends   = 0, 100.00% good

Errors:
485 = Expected 200 got 429

timeEnd   = 2024-01-21 08:36:49 +0000 UTC

{SuccessRate: 88.45%, Throughput: 70.00 req/s, AvgRequestTime: 0.06 ms, Connections: 50, RequestRate: 70, RequestTotal: 4200, SuccessTotal: 3715, ErrorTotal: 485, TimeElapsed: 1m0.000911936s}
```

# Invesigations
This repro needs large number of filter chains to generate large metrics and both http request rate limter and bandwidth limiter which rely on timer on main thread to fulfill the tokens.

During the testing, we observed from the debug logs, the rate limiter callback "LocalRateLimiterImpl::onFillTimerHelper" sometimes are not invoked, and tokens are not fullfilled, that's why rate limiter enforced while QPS is still below the limit.

We suspect main thread is too busy to process the metrics and limiters, and not react on limiter callback timely.

I'd like understand the root cause and options how to address this issue, thanks.

**Comment by zuercher** [comment]
I think the first place to look is the various "miss" metrics and the dispatcher stats, which are referenced [here](https://www.envoyproxy.io/docs/envoy/latest/operations/performance.html). Those should indicate if the event loop that drives the timers is being overwhelmed.

**Comment by zhiyong-gayang** [comment]
@zuercher 
Thanks for replying.

This is the dispatcher stats for main thread, I do see loop_duration_us has high latency on P95/99, but how to tell if this is overwhelmed.

server.dispatcher.loop_duration_us: P0(20,3) P25(45.75,50.60351089588378) P50(50.9,70.09872611464968) P75(64.75,110.60303514376999) P90(145,219.78504672897202) P95(**3237.5,2978.3777777777773**) P99(**953500,112751.69491525435**) P99.5(956750,127103.8461538466) P99.9(959350,961705.8333333322) P100(960000,1100000)

server.dispatcher.poll_delay_us: P0(79,4) P25(134.16666666666666,140.8989501312336) P50(166.25,166.88505747126436) P75(197.1875,199.06435349940688) P90(219,221.5118829981719) P95(236.49999999999994,241.98909657320868) P99(353.9,297.0531249999999) P99.5(356.95,353.97857142857123) P99.9(359.39,1083.913999999997) P100(360,3900)

**Comment by zhiyong-gayang** [comment]
Does anyone can give more suggestions?

**Comment by zhiyong-gayang** [comment]
Up.
