### ISSUE TITLE
Redis filter with Socks capabilities

### ISSUE THREAD

**Issue by DimitarHKostov** [envoyproxy/envoy#31925]
Hello Envoy team,

can the Redis filter be extended with SOCKS capabilities and be used as a a plugin? I see that at the moment that for "MOVED" and "ASK" responses from a Redis cluster a DNS config is required to resolve not known hosts. It would be great if that can happen through SOCKS proxy. Can you give an opinion on the topic?

**Comment by zuercher** [comment]
cc @msukalski @henryyyang
