### ISSUE TITLE
how to config envoy using nginx configure file

### ISSUE THREAD

**Issue by xsyl1124** [envoyproxy/envoy#31928]
# cat aa.meng.com.conf 
server {
    listen 80; 
    server_name aa.meng.com;
    #root  html/aa.meng.com;
    access_log logs/aa.meng.com_access.log main;
    error_log  logs/aa.meng.com_error.log;

    client_max_body_size 4096m;

    location / {
        proxy_pass         http://172.16.103.175:81;
        proxy_http_version 1.1;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
}
cat bb.meng.com.conf 
server {
    listen 80; 
    server_name bb.meng.com;
    #root  html/bb.meng.com;
    access_log logs/bb.meng.com_access.log main;
    error_log  logs/bb.meng.com_error.log;

    client_max_body_size 4096m;

    location / {
        proxy_pass         http://172.16.103.175:82;
        proxy_http_version 1.1;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
}

how to config envoy using these nginx files ?

**Comment by zengyuxing007** [comment]
This requires a translator, and writing one of these is not easy, and requires familiarity with nginx and envoy both .

**Comment by phlax** [comment]
not sure how much benefit there would be to automatically translating the config in this way - it would require quite a lot of design choices - features are not directly compatible/comparable, and there is often more that one way to achieve a given goal
