### ISSUE TITLE
All mobile iOS tests are flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#31957]
Any of our CI that uses ios is flaking frequently

This regularly fails PRs and `main`

**Comment by phlax** [comment]
I think this needs to be tackled urgently - either by resolving whatever the cause is or disabling/making non-required until it has been

**Comment by phlax** [comment]
cc @fredyw

**Comment by phlax** [comment]
afaict in many cases the underlying issue is DNS related - seems like the apple machines are struggling to resolve common addresses

**Comment by fredyw** [comment]
Looking at [this](https://github.com/envoyproxy/envoy/blob/8f0e1eaaf30964080da754ae052cc428c17c5087/.github/workflows/mobile-ios_build.yml#L45), it looks like the tests run on a standard runner. @phlax Is it possible to upgrade it to use a large runner?

**Comment by phlax** [comment]
its possible - but will increase our "bill" quite a bit

can you submit a PR to update the runner and we can figure out from there

**Comment by fredyw** [comment]
After switching to a large runner, I can see a big improvement in the test time.

Before: https://github.com/envoyproxy/envoy/actions/runs/8632518646/job/23667884484 (less than 10 minutes)
After: https://github.com/envoyproxy/envoy/actions/runs/8636475238/job/23676726086 (20-30 minutes)
