### ISSUE TITLE
http compressor filter should skipped when response has content-range header

### ISSUE THREAD

**Issue by jiangshantao-dbg** [envoyproxy/envoy#31956]
*Description*:
The HTTP/1.1 spec (RFC2616) requires ranges to apply to the content-encoded content:
- from Section 14.35.1: "Byte range specifications in HTTP apply to the sequence of bytes in the entity-body ..."
- from Section 7.2.1: "entity-body := Content-Encoding( Content-Type( data ) )"

when enable http compressor filter with a host, the client request with range protocol, and  the upstream return range content with header Content-Range. the content will be compressed which will not satisfy the protocol. the range-content is for entity-body which should not be compressed.

the http protocol suggest:
If a 206 (Partial Content) response contains a Content-Range header field with a range unit (Section 2) that the recipient does not understand, the recipient MUST NOT attempt to recombine it with a stored representation. A proxy that receives such a message SHOULD forward it downstream.

ref: [content-range](https://httpwg.org/specs/rfc7233.html#header.content-range)

**Comment by toddmgreer** [comment]
Regardless of the Content-Range header, we shouldn't compress 206 responses. Compressing a 206 response produces a response that has no defined meaning.
