### ISSUE TITLE
envoy_reloadable_features_dfp_mixed_scheme deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#31973]
Your change #27407 (dns: changing cache keys to include port to avoid issues) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
@yanavlasov @krajshiva this one is blocked on google yes?  AFIK we never closed the loop upstream

**Comment by krajshiva** [comment]
The problem call site is fixed here https://github.com/envoyproxy/envoy/pull/27641 and is imported so we should be good to use new code. I will verify with the team once more by pinging them.

**Comment by krajshiva** [comment]
actually there is another team that also has dependency on it. will check with them.

**Comment by alyssawilk** [comment]
@krajshiva ping on this?

**Comment by alyssawilk** [comment]
ping :-)

**Comment by alyssawilk** [comment]
Hey @krajshiva can you circle back on this so we can remove it?
