### ISSUE TITLE
envoy_reloadable_features_enable_connect_udp_support deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#31975]
Your change #27714 (http: add CONNECT-UDP support) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by jeongseokson** [comment]
I just found out this has been assigned to me! Sorry for my late follow-up, I will start working on this once I finish a few other high-priority tasks.

**Comment by jeongseokson** [comment]
The runtime flag has been deprecated in the #34979. Feel free to close this issue @alyssawilk
