### ISSUE TITLE
Adding “IP source” (x-forwarded-for)  to Envoy Prometheus metrics. For example: envoy_cluster_external_upstream_rq{}

### ISSUE THREAD

**Issue by jvergara-runbuggy** [envoyproxy/envoy#31990]
*Title*: *Adding “IP source” (x-forwarded-for)  to Envoy Prometheus metrics. For example: envoy_cluster_external_upstream_rq{}*

*Description*:
 Right now when we get Prometheus metrics from envoy like "envoy_cluster_external_upstream_rq", we get the following variables in the metrics:
> envoy_cluster_external_upstream_rq{envoy_response_code="200",envoy_cluster_name="cluster_127_0_0_1_8500_ambassador"} 1449

I would like to be able to have the "IP source" added to this type of metrics - so Prometheus based histograms, other stats and alerts could be created based on the "IP source".

So ideally, we should get something like this in the envoy metrics:

> envoy_cluster_external_upstream_rq{envoy_response_code="200",envoy_cluster_name="cluster_prom_grafana_monitoring_80_monitoring", x_forwarded_for=127.124.123.7} 162

Is that possible?

**Comment by zuercher** [comment]
Putting an IP address in the metric labels will cause cardinality issues with the metrics both in Envoy and in Prometheus.
