### ISSUE TITLE
Add hooks that are called in ScopeTrackerScopeState's constructor and destructor

### ISSUE THREAD

**Issue by wu-bin** [envoyproxy/envoy#32012]
*Add hooks that are called in ScopeTrackerScopeState's constructor and destructor*: 

*Description*:
I'm working on project to break down cpu and memory usage of a (Google internal) Envoy server by some properties of a connection.  It roughly works like this: Suppose each connection in my Envoy server has property X, and I want to know how much Envoy cpu and memory are used by different values of X, e.g. when X is 'priority', and potential values of 'priority' is one of ['HIGH', 'MEDIUM', 'LOW'], the question becomes how much Envoy cpu and memory is used by connections with 'HIGH', 'MEDIUM' or 'LOW' priorities, respectively. This can be addressed by doing a combination of two things:

1. When a envoy worker thread starts running code on behalf of a connection, set the connection's priority value in a thread-local variable. When the thread finishes working on behalf of a connection, unset the thread-local variable.

2. Periodically sample the cpu(via SIGPROF) and memory(via TCMalloc sampling). Each time a sample is recorded, the sampling callback will read the thread-locals and declare the sampled cpu/memory is used by the corresponding property. e.g. In the SIGPROF handler, if the thread-local says priority=HIGH, the sampled cpu usage is used by high priority connections. The sampled usage is then aggregated for human consumption.

(2) is an implementation outside of open source Envoy. For (1), I found `Envoy::ScopeTrackerScopeState` already exists, it already tracks the starting and stopping of execution of connections code, all I need is to add hooks that are called in its constructor and destructor. I propose:

- Add a `Envoy::ExecutionContext` class, which has activate and deactivate methods called when ScopeTrackerScopeState constructs and destructs.
- Add a `Envoy::ScopedExecutionContext` RAII class, to ensure ExecutionContext's activate and deactivate methods are always called in pairs.
- Add a `Envoy::ConnectionExecutionContextFilterState`, which wraps a `Envoy::ExecutionContext` and can be installed on a connection. If a connection has this filter state installed, the wrapped ExecutionContext will be notified when the connection starts and finishes running.

This has been implemented in https://github.com/envoyproxy/envoy/pull/31937, this issue is filed per a review comment from the PR.

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk @zuercher @abeyad @penguingao

**Comment by wu-bin** [comment]
PR https://github.com/envoyproxy/envoy/pull/31937 has been merged.
