### ISSUE TITLE
Typos in ext_proc documentation

### ISSUE THREAD

**Issue by sanjaypujare** [envoyproxy/envoy#32029]
*Title*: *Documentation issues in ext_proc proto comments*

*Description*:
In the file https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/ext_proc/v3/external_processor.proto there are 2 or 3 issues (copy paste typos)

- on line 94 above response_body the comment starts with "A chunk of the HTTP request body" which should be response body
- on line 112 for the response_trailers field it says "If there are no trailers on the original downstream request..."  which should be "If there are no trailers on the original upstream response..."
- not sure about this on line 114 which says "...is set before the request headers are sent.." : should this be "...is set before the response headers are sent..."

*Repro steps*:
See https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/ext_proc/v3/external_processor.proto

**Comment by phlax** [comment]
@sanjaypujare would you be able to PR the changes you are proposing?

**Comment by tyxia** [comment]
Thanks, @sanjaypujare.

https://github.com/envoyproxy/envoy/pull/32031 should fix this.
