### ISSUE TITLE
New filter for transparent encryption of cookies

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [envoyproxy/envoy#32066]
*Title*: *New filter for transparent encryption of cookies*

*Description*:

Some cookies might contain confidential data, e.g. OAuth `access_token`

see https://github.com/envoyproxy/envoy/issues/23508
see https://github.com/envoyproxy/envoy/issues/29656

Envoy could make sure that those cookies are encrypted before they are send to the user and decrypted before the request is handled.

In case of `Oauth`, the confidential cookies like `access_token` would only be stored encrypted.

Our proposal would be a new filter (e.g. `EncryptedCookies`) which transparently handles cookie encryption. The filter would need 2 inputs:

* A list of cookie names that should be encrypted
* A secret used to encrypt/decrypt the cookies

Open Questions:

* Naming of the filter
* Finding a sponsor
* Selecting a proper encryption algorithm
* Similarites to the [Header Mutation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_mutation_filter) filter
* Performance implications

**Comment by ramaraochavali** [comment]
We can enhance this to headers as to handle cases where people can encrypt [stateful session header](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/stateful_session_filter)
cc: @wbpcode

**Comment by loewenstein** [comment]
Thanks @zuercher for triaging. What is the usual process for moving this forward?

**Comment by zuercher** [comment]
Sorry missed this question.

I think there's two parts to this. 
1. Some kind of document that provides clarity on the algorithm(s) to be used for encryption, what additional libraries will be needed to support those algorithms, etc. I *think* it should be possible to use the existing Secret Discovery Service mechanisms to be obtain the necessary secret material, but you should confirm that based on the proposed algorithms and should discuss any changes needed in SDS before you start work. I don't think this needs to be particularly long, it just needs to flesh out some details and consider paths for future enhancements (e.g., if someone want to add support for a different encryption algorithm how would it be configured; probably want to make it possible to do this vs having to revamp the API objects later). This would get published here and probably also on the Envoy Slack workspace for discussion. You can solicit advice on Slack as well, for instance in selecting an encryption algorithm.
2. Is to follow the steps in [CONTRIBUTING.md](https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md) and the [EXTENSION_POLICY.md](https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md). In particular, to be included in the main line Envoy build, you'll need a maintainer to sponsor the work. (Sorry, but I'm not available.)

**Comment by derekargueta** [comment]
Adding this functionality to the Header Mutation might be appropriate, I'm moving my query param modification PR to be a part of that filter since it operates on the `:path` header. Although I'm considering directly implementing encrypted coookies into the OAuth filter as a direct option, in which case idk how much use this filter would get.

**Comment by wbpcode** [comment]
> Although I'm considering directly implementing encrypted coookies into the OAuth filter as a direct option

If the oauth2 token is the core scenario, I think this is OK.

**Comment by zhaohuabing** [comment]
> > Although I'm considering directly implementing encrypted coookies into the OAuth filter as a direct option
> 
> If the oauth2 token is the core scenario, I think this is OK.

I can start working on the oauth2 filter to encrypt the token cookies. We don't have to overcomplicate things to introduce a new filter.

**Comment by zhaohuabing** [comment]
[[OAuth2: PKCE(Proof Key for Code Exchange)](https://github.com/envoyproxy/envoy/pull/37849#top) [lays the groundwork for the oauth2 ID and access token encryption](https://github.com/envoyproxy/envoy/pull/37849#discussion_r1919417387). I plan to address this issue after it's done. @arkodg @denniskniep

**Comment by zhaohuabing** [comment]
OAuth2 token cookie encryption is done in https://github.com/envoyproxy/envoy/pull/39059 cc @denniskniep
