### ISSUE TITLE
Main thread blocked by parsing trace message only and no time for handling other events when enable admin tap

### ISSUE THREAD

**Issue by yiyibaoguo** [envoyproxy/envoy#32068]
*Title*: *Main thread blocked by parsing trace message only and no time for handling other events *

*Description*:
> When I 1) config tap filter with admin_config, 2) POST config via /tap and start background traffic with 3000 request/per second , then I see memory increasing always, and no response from admin port. (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter.html)
In this situation, stop tap is expected. However, no response from admin port.

*Repro steps*:
> reference attached slides for detail
[main thread only busy handling active event about trace call back.pptx](https://github.com/envoyproxy/envoy/files/14064484/main.thread.only.busy.handling.active.event.about.trace.call.back.pptx)

**Comment by zuercher** [comment]
cc @daixiang0

**Comment by coolg92003** [comment]
hi @zuercher ,
would you also add enventbase tab?
As we investigated, the event base code in main thread process logical has potential issue.
thanks
Cliff

**Comment by coolg92003** [comment]
Hi @alyssawilk,
I think transport tap has the similar issue.
what is your comment?
thanks
CLiff

**Comment by alyssawilk** [comment]
I think largely we should start farming out requests to a separate thread pool but I don't think any of the current maintainers can pick that up.  we'd be happy to review contributions though

**Comment by coolg92003** [comment]
Hi @alyssawilk,
It is great hear from u! 
we can try to contribute it. two questions:
1) Are your prefer to a separate thread pool? 
I prefer to send directly from working threads, as you know it cost lots CPU for thread context switch with the lots of threads
2) If sending tapped messages from each thread, which below are your prefer?
UDP, (the small maintained cost and high performance)
GRPC(need more resource)

thanks
Cliff

**Comment by alyssawilk** [comment]
not sure on design questions -I'm not terribly familiar with tap code.  re-pinging TAP owners, @mattklein123 @daixiang0

**Comment by yiyibaoguo** [comment]
still wait for owner's comments

**Comment by xu1zhou** [comment]
In my opinion, grpc tap solution is a better way to resolve main thread admin tap performance issue. Ericsson had propose their solution on last year [EnvoyCon](https://www.youtube.com/watch?v=rRWiFh7Bnps&list=PLj6h78yzYM2MqGbKnePGT3p9h17VgciyO&index=13), which can be a good example for you to refer.

**Comment by yiyibaoguo** [comment]
@xu1zhou thanks for your comments, and we can study above solution later.
