### ISSUE TITLE
Add an option to disable `MGET` splitting in Redis (to avoid performance penalty)

### ISSUE THREAD

**Issue by hedgesky** [envoyproxy/envoy#32069]
Hello :wave:
I have a question regarding splitting Redis `MGET` commands into multiple `GET` ones (implemented [here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/redis_proxy/command_splitter_impl.h#L268)). Would it be possible to add a configuration option to disable this behavior?

Let me describe the use case. We're adding Envoy as a proxy to a Redis Cluster. Our app sends MGET requests with dozens of keys like `{my_user_id}:key1`, `{my_user_id}:key2`, etc. As the user id is the same in all the keys, all of them are guaranteed to be hashed to the same slot.

With a regular Redis Cluster, only one command is executed (the `MGET` one). With Envoy, however, the MGET is split into N separate `GET` requests, which incurs a noticeable performance hit. Having an option to disable splitting would allow us to avoid that penalty.
UPD. A similar issue seems to apply to `DEL`, `EXISTS`, `TOUCH`, and `UNLINK` commands ([source](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/common/redis/supported_commands.h#L48)).

*Relevant links*:
- This performance issue was also mentioned in https://github.com/envoyproxy/envoy/issues/19436#issuecomment-1009555950
- [The implementation of MGET splitting in Envoy](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/redis_proxy/command_splitter_impl.h#L268)
- [Redis MGET command documentation](https://redis.io/commands/mget/)

**Comment by zuercher** [comment]
cc @weisisea @mattklein123

**Comment by deveshkandpal1224** [comment]
I think this would also benefit this github issue ( not splitting the MGET request to individual GET request ) -> https://github.com/envoyproxy/envoy/issues/31038.

**Comment by weisisea** [comment]
This makes sense. One idea is that for a multi-key command, we can calculate the hash of the keys and send the command without splitting to the target Redis node if all the key hashes are the same.

**Comment by weisisea** [comment]
@zuercher could you please advise on how to add the label "help-wanted"? It seems that I wasn't able to find a way to add the label. Thanks!
