### ISSUE TITLE
master com_google_cel_cpp: no matching function for call to 'operator delete'

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#32080]
*Title*: *no matching function for call to 'operator delete'*

*Description*:
> I try to build a `main` branch on Fedora 38 aarch64 host. and got error
```
external/com_google_cel_cpp/base/memory.h:92:7: error: no matching function for call to 'operator delete'
```
> Build log
ERROR: /tmp/envoy/source/extensions/access_loggers/filters/cel/BUILD:11:19: Compiling source/extensions/access_loggers/filters/cel/cel.cc failed: (Exit 1): process-wrapper failed: error executing command 
  (cd /home/build/.cache/bazel/_bazel_build/221703495c2e97a5482194eda3ea2f8b/sandbox/processwrapper-sandbox/2208/execroot/envoy && \
  exec env - \
    BAZEL_COMPILER=clang \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    CC=clang \
    CXX=clang++ \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/build/.cache/bazel/_bazel_build/install/690906d82aa78975b597bd4f0948f7cd/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/home/build/.cache/bazel/_bazel_build/221703495c2e97a5482194eda3ea2f8b/sandbox/processwrapper-sandbox/2208/stats.out' /usr/bin/clang-16 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/aarch64-opt/bin/source/extensions/access_loggers/filters/cel/_objs/cel_lib/cel.d '-frandom-seed=bazel-out/aarch64-opt/bin/source/extensions/access_loggers/filters/cel/_objs/cel_lib/cel.o' -gsplit-dwarf -g -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -DENVOY_ADMIN_FUNCTIONALITY -DENVOY_ENABLE_QUIC -DENVOY_ENABLE_FULL_PROTOS -DENVOY_ENABLE_YAML -DENVOY_ENABLE_HTTP_DATAGRAMS -DENVOY_MOBILE_ENABLE_LISTENER -DENVOY_MOBILE_XDS -DENVOY_GOOGLE_GRPC -DNGHTTP2_STATICLIB '-DBAZEL_CURRENT_REPOSITORY=""' -iquote . -iquote bazel-out/aarch64-opt/bin -iquote external/com_google_absl -iquote bazel-out/aarch64-opt/bin/external/com_google_absl -iquote external/com_github_gabime_spdlog -iquote bazel-out/aarch64-opt/bin/external/com_github_gabime_spdlog -iquote external/com_github_fmtlib_fmt -iquote bazel-out/aarch64-opt/bin/external/com_github_fmtlib_fmt -iquote external/com_google_protobuf -iquote bazel-out/aarch64-opt/bin/external/com_google_protobuf -iquote external/utf8_range -iquote bazel-out/aarch64-opt/bin/external/utf8_range -iquote external/com_github_cyan4973_xxhash -iquote bazel-out/aarch64-opt/bin/external/com_github_cyan4973_xxhash -iquote external/envoy_api -iquote bazel-out/aarch64-opt/bin/external/envoy_api -iquote external/com_google_googleapis -iquote bazel-out/aarch64-opt/bin/external/com_google_googleapis -iquote external/com_envoyproxy_protoc_gen_validate -iquote bazel-out/aarch64-opt/bin/external/com_envoyproxy_protoc_gen_validate -iquote external/com_googlesource_code_re2 -iquote bazel-out/aarch64-opt/bin/external/com_googlesource_code_re2 -iquote external/com_github_cncf_xds -iquote bazel-out/aarch64-opt/bin/external/com_github_cncf_xds -iquote external/opencensus_proto -iquote bazel-out/aarch64-opt/bin/external/opencensus_proto -iquote external/com_github_jbeder_yaml_cpp -iquote bazel-out/aarch64-opt/bin/external/com_github_jbeder_yaml_cpp -iquote external/boringssl -iquote bazel-out/aarch64-opt/bin/external/boringssl -iquote external/envoy -iquote bazel-out/aarch64-opt/bin/external/envoy -iquote external/com_github_google_quiche -iquote bazel-out/aarch64-opt/bin/external/com_github_google_quiche -iquote external/com_googlesource_googleurl -iquote bazel-out/aarch64-opt/bin/external/com_googlesource_googleurl -iquote external/com_github_openhistogram_libcircllhist -iquote bazel-out/aarch64-opt/bin/external/com_github_openhistogram_libcircllhist -iquote external/com_github_nlohmann_json -iquote bazel-out/aarch64-opt/bin/external/com_github_nlohmann_json -iquote external/com_github_google_flatbuffers -iquote bazel-out/aarch64-opt/bin/external/com_github_google_flatbuffers -iquote external/com_google_cel_cpp -iquote bazel-out/aarch64-opt/bin/external/com_google_cel_cpp -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf_nowkt -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf_lite -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_align -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/stubs/_virtual_includes/lite -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/port_def -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_allocation_policy -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_config -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/arena_cleanup -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/string_block -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/varint_shuffle -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/io -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/io_win32 -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/gzip_stream -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/stubs/_virtual_includes/stubs -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/printer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/zero_copy_sink -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/io/_virtual_includes/tokenizer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/any_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/descriptor_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/empty_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/struct_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/wrappers_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/_virtual_includes/protobuf -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/protobuf -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/api_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/source_context_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/type_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/field_mask_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/compiler/_virtual_includes/importer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/delimited_message_util -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/differencer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/field_mask_util -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/json_util -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/json -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/parser -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/descriptor_traits -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/lexer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/message_path -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/zero_copy_buffered_stream -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/untyped_message -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/type_resolver_util -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/descriptor_legacy -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/unparser -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/json/_virtual_includes/writer -Ibazel-out/aarch64-opt/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/time_util -Ibazel-out/aarch64-opt/bin/source/common/common/_virtual_includes/logger_impl_lib_standard -Ibazel-out/aarch64-opt/bin/source/common/common/_virtual_includes/thread_impl_lib_posix -Ibazel-out/aarch64-opt/bin/source/common/api/_virtual_includes/os_sys_calls_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_export_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_logging_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_quiche/_virtual_includes/quiche_common_platform_default_quiche_platform_impl_command_line_flags_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_quiche/_virtual_includes/quiche_common_platform_default_quiche_platform_impl_flag_utils_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_quiche/_virtual_includes/quiche_common_platform_default_quiche_platform_impl_reference_counted_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_quiche/_virtual_includes/quiche_common_platform_default_quiche_platform_impl_testvalue_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_quiche/_virtual_includes/quiche_common_platform_default_quiche_platform_impl_prefetch_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quic_base_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_flags_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_mem_slice_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_platform_iovec_impl_lib -Ibazel-out/aarch64-opt/bin/source/common/quic/platform/_virtual_includes/quiche_time_utils_impl_lib -Ibazel-out/aarch64-opt/bin/external/com_github_google_flatbuffers/_virtual_includes/flatbuffers -Ibazel-out/aarch64-opt/bin/external/com_github_google_flatbuffers/src/_virtual_includes/flatbuffers -isystem external/com_github_gabime_spdlog/include -isystem bazel-out/aarch64-opt/bin/external/com_github_gabime_spdlog/include -isystem external/com_github_fmtlib_fmt/include -isystem bazel-out/aarch64-opt/bin/external/com_github_fmtlib_fmt/include -isystem bazel-out/aarch64-opt/bin/external/envoy/bazel/foreign_cc/zlib/include -isystem external/com_github_jbeder_yaml_cpp/include -isystem bazel-out/aarch64-opt/bin/external/com_github_jbeder_yaml_cpp/include -isystem external/boringssl/src/include -isystem bazel-out/aarch64-opt/bin/external/boringssl/src/include -isystem bazel-out/aarch64-opt/bin/external/envoy/bazel/foreign_cc/event/include -isystem external/envoy/bazel/external/http_parser -isystem bazel-out/aarch64-opt/bin/external/envoy/bazel/external/http_parser -isystem bazel-out/aarch64-opt/bin/external/envoy/bazel/foreign_cc/nghttp2/include -isystem external/com_github_openhistogram_libcircllhist/src -isystem bazel-out/aarch64-opt/bin/external/com_github_openhistogram_libcircllhist/src -isystem external/com_github_nlohmann_json/include -isystem bazel-out/aarch64-opt/bin/external/com_github_nlohmann_json/include -isystem external/com_github_nlohmann_json/external/nlohmann_json_lib -isystem bazel-out/aarch64-opt/bin/external/com_github_nlohmann_json/external/nlohmann_json_lib '-DABSL_MIN_LOG_LEVEL=4' -fdebug-types-section -fPIC -Wno-deprecated-declarations '-std=c++17' -Wall -Wextra -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -Wformat -Wformat-security -Wvla -Wno-deprecated-declarations -Wreturn-type -ggdb3 -fno-limit-debug-info -Wgnu-conditional-omitted-operand -Wc++2a-extensions -Wrange-loop-analysis -DTCMALLOC -DENVOY_OBJECT_TRACE_ON_DUMP -DENVOY_HOT_RESTART -DENVOY_ADMIN_HTML -DENVOY_STATIC_EXTENSION_REGISTRATION -DENVOY_GOOGLE_GRPC -DENVOY_HANDLE_SIGNALS -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c source/extensions/access_loggers/filters/cel/cel.cc -o bazel-out/aarch64-opt/bin/source/extensions/access_loggers/filters/cel/_objs/cel_lib/cel.o)
In file included from source/extensions/access_loggers/filters/cel/cel.cc:1:
In file included from ./source/extensions/access_loggers/filters/cel/cel.h:12:
In file included from ./source/extensions/filters/common/expr/evaluator.h:7:
In file included from ./source/extensions/filters/common/expr/context.h:11:
In file included from external/com_google_cel_cpp/eval/public/cel_value.h:37:
external/com_google_cel_cpp/base/memory.h:92:7: error: no matching function for call to 'operator delete'
      ::operator delete(static_cast<void*>(p), n * sizeof(T),
      ^~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/new:155:6: note: candidate function not viable: no known conversion from 'unsigned long' to 'std::align_val_t' for 2nd argument
void operator delete(void*, std::align_val_t, const std::nothrow_t&)
     ^
/usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/new:153:6: note: candidate function not viable: requires 2 arguments, but 3 were provided
void operator delete(void*, std::align_val_t)
     ^
/usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/new:144:6: note: candidate function not viable: requires 2 arguments, but 3 were provided
void operator delete(void*, const std::nothrow_t&) _GLIBCXX_USE_NOEXCEPT
     ^
/usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/new:180:13: note: candidate function not viable: requires 2 arguments, but 3 were provided
inline void operator delete  (void*, void*) _GLIBCXX_USE_NOEXCEPT { }
            ^
/usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/new:130:6: note: candidate function not viable: requires 1 argument, but 3 were provided
void operator delete(void*) _GLIBCXX_USE_NOEXCEPT
     ^
1 error generated.
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 15416.109s, Critical Path: 72.26s
INFO: 2353 processes: 146 internal, 1 local, 2206 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

*Repro steps*:
To start build used command
```
bazel build --config=clang -c opt envoy --subcommands --jobs 1 --verbose_failures --sandbox_debug
```

**Comment by sergey-safarov** [comment]
I have build `protobuf` master branch using instructions.

https://github.com/protocolbuffers/protobuf/blob/main/src/README.md

**Comment by sergey-safarov** [comment]
As workaround i have compiled envoy using command
```
bazel build \
  --config=libc++ \
  -c opt \
  envoy \
  --subcommands \
  --jobs 1 \
  --verbose_failures \
  --sandbox_debug --copt="-Wno-changes-meaning"
```

**Comment by alyssawilk** [comment]
@tyxia @yanavlasov @phlax

**Comment by phlax** [comment]
i think this may be fixed by https://github.com/envoyproxy/envoy/pull/31872 and is probably a ~dupe of https://github.com/envoyproxy/envoy/issues/31856

**Comment by haoruolei** [comment]
Is there any update for this issue? Seems like the newest 1.29.2 build still fails
