### ISSUE TITLE
Local Rate limit Filter - Dynamic Descriptor 

### ISSUE THREAD

**Issue by asialea** [envoyproxy/envoy#32082]
*Title*: *Local Rate limit Filter - Token Bucket per User*

*Description*:
 I am looking to use the local rate limit filter to apply limits at a per user basis on a given route. I was looking to use ether filter state or request metadata to do so. Looking at the documentation I am not able to find examples of how to use a key from filter state or metadata as a descriptor. Does anyone know if it's even possible to set a dynamic value here? Thanks!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by asialea** [comment]
Update - tried doing something like the following using a key from our filter state and it did not work. Looks like substitution format strings are not recognized. I see there are some older issues opened with the same ask. Is there any particular reason why this is not supported? Also looks like the network local ratelimit filter does not have the option to specify descriptors at all

`
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED  
                descriptors:
                - entries: # https://github.com/envoyproxy/envoy/issues/19895
                  - key: client_ip
                    value:  "%FILTER_STATE(talon_operation_event.SourceIp)%"
                  token_bucket:
                    max_tokens: 100
                    tokens_per_fill: 100
                    fill_interval: 1s

`

**Comment by wbpcode** [comment]
The entry value of descriptor should be a raw string value. The local rate limit filter will generate a value based on the https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit configuration and the generated value will be used to match the value in the descriptors.

**Comment by asialea** [comment]
> The entry value of descriptor should be a raw string value. The local rate limit filter will generate a value based on the https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit configuration and the generated value will be used to match the value in the descriptors.

Okay, so substitution format string is not supported in descriptor value for local ratelimit filter. I see there are some older issues with this ask. Do you know if anyone has attempted to take a stab at implementing this? or if there is a reason why this should not be supported.

**Comment by wbpcode** [comment]
Basically, the entries keys and values is used to identify a rate limit rule uniquely. So, I don't know in which case it should be a variable. What is the final effect and what scenario will need it?

**Comment by asialea** [comment]
> Basically, the entries keys and values is used to identify a rate limit rule uniquely. So, I don't know in which case it should be a variable. What is the final effect and what scenario will need it?

Trying to find a way to create a separate token bucket per identitifier based on a given request metadata field. For example, if I wanted to allow 10k RPS per userId.

**Comment by wbpcode** [comment]
From the configuration perspective, keep the value be absent means we want to do rate limit for every unique value, like 10k PRC per user id or per user ip.

See https://github.com/envoyproxy/ratelimit?tab=readme-ov-file#example-8

**But it's not supported for now for local rate limit because the possible uncontrollable memory overhead and the implementation complexity.**

@kyessenov do you think this requirement make sense? should we try to add it to local rate limit?
