### ISSUE TITLE
Logical DNS and health checks / outlier detection

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#32088]
How does health checks / outlier detection works with a Logical DNS cluster?
Assuming I have a logical DNS cluster that has a single host ``host.com`` that in time will return 5 different IPs due to DNS round robin, and there's health check, outlier detection set for that cluster. Will I have 5 different health checks (for each of the IPs)? Assuming that yes - what if just one of the IPs fail health check - is the hostname itself considers unhealthy, or only that IP (meaning that new connections to that cluster can still go to one of the other 4 valid IPs)?
Thanks

**Comment by alyssawilk** [comment]
cc @pradeepcrao
