### ISSUE TITLE
[feature request] Stateful retry in TCP proxy

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#32095]
The existing TcpProxy retry is useful by performing a LB decision,
however, there are a couple of scenarios that we want stateful retry in TcpProxy, 
especially when LB is not adequate e.g.

Choose an insecure transport as the backup;
Choose another fallback cluster upon on-demand CDS failure;
Choose a remote cluster 

Note that the degraded scenario may want different transport socket,
and they are obviously not the best initial decision.

A trivial approach is to add a fallback cluster in TcpProxy,
but the generic method is to add 
1) a fallback policy which can mutate the downstream info
2) an optional Tcp cluster_specifier_plugin[1]  which consumes downstream info

Note that 2) is optional. 
Without 2, if a connect fallback policy is allowed to update the PerConnectionCluster key,
a new cluster could be selected by invoking a [getRegularRouteFromEntries](https://github.com/envoyproxy/envoy/blob/5c821febbbba530315295a3c3dd3481364f89890/source/common/tcp_proxy/tcp_proxy.cc#L41C20-L202C2
) call.

Thoughts?

[1] cluster_specifier_plugin
([string](https://developers.google.com/protocol-buffers/docs/proto#scalar)) Name of the cluster specifier plugin to use to determine the cluster for requests on this route. The cluster specifier plugin name must be defined in the associated [cluster specifier plugins](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#envoy-v3-api-field-config-route-v3-routeconfiguration-cluster-specifier-plugins) in the [name](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/extension.proto#envoy-v3-api-field-config-core-v3-typedextensionconfig-name) field.

**Comment by ohadvano** [comment]
Any chance this is similar to this issue: https://github.com/envoyproxy/envoy/issues/31217?

It was suggested there to use aggregate cluster and priorities

**Comment by lambdai** [comment]
Thank you @ohadvano 
I tried, but aggregate cluster does not work in my secenario.
I forgot to mention the high priority cluster is original_dst type cluster,
the aggregated cluster ochestrates the endpoints of the subclusters.
where the initial endpoints does not present.

**Comment by ggreenway** [comment]
I think adding a generic extension, which can affect the next host selection, makes sense. Can you propose an interface for it?

**Comment by lambdai** [comment]
Thank you for the feedback. 
Let's me generalize my in house solution to the extension style

**Comment by lambdai** [comment]
not stale
