### ISSUE TITLE
 dynamically set hostname using dynamic metadata but failed

### ISSUE THREAD

**Issue by littlejiancc** [envoyproxy/envoy#32103]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
dynamically set hostname using dynamic metadata, but get empty
*Description*:
>Describe the issue.
according to the issue https://github.com/envoyproxy/envoy/issues/19612 to dynamic setting value of TcpProxy.tunneling_config.hostname, but get empty

envoy version

`envoy  version: b5ca88acee3453c9459474b8f22215796eff4dde/1.28.0/Clean/RELEASE/BoringSSL`

envoy config
```
{
 "name": "loopback_listener",
 "address": {
  "socket_address": {
   "address": "127.0.0.1",
   "port_value": 10008
  }
 },
 "filter_chains": [
  {
   "filters": [
    {
     "name": "tcp",
     "typed_config": {
      "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
      "stat_prefix": "tcpproxy",
      "cluster": "external_proxy_cluster",
      "access_log": [
       {
        "name": "envoy.access_loggers.file",
        "typed_config": {
         "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
         "path": "logs/proxy.log",
         "log_format": {
          "text_format_source": {
           "inline_string": "%DYNAMIC_METADATA(tunnel:address)%\n"
          }
         }
        }
       }
      ],
      "tunneling_config": {
       "hostname": "%DYNAMIC_METADATA(tunnel:address)%"
      }
     }
    }
   ]
  }
 ]
}
```

```
{
  "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
  "name": "52fs1l-to-o019sv",
  "type": "STRICT_DNS",
  "connect_timeout": "10s",
  "transport_socket": {
   "name": "envoy.transport_sockets.internal_upstream",
   "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport",
    "passthrough_metadata": [
     {
      "kind": {
       "host": {}
      },
      "name": "tunnel"
     }
    ],
    "transport_socket": {
     "name": "envoy.transport_sockets.raw_buffer",
     "typed_config": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
     }
    }
   }
  },
  "load_assignment": {
   "cluster_name": "52fs1l-to-o019sv",
   "endpoints": [
    {
     "lb_endpoints": [
      {
       "endpoint": {
        "address": {
         "socket_address": {
          "address": "127.0.0.1",
          "port_value": 10008
         }
        },
        "hostname": "127.0.0.1"
       },
       "metadata": {
        "filter_metadata": {
         "tunnel": {
          "address": "xx.xx.xx.xx:80"
         }
        }
       }
      }
     ]
    }
   ]
  }
```

proxy.log
![image](https://github.com/envoyproxy/envoy/assets/23724009/f46d1052-aae6-4f75-9125-8e0258fb42ed)

I'm not sure if it's a config error or if there's any way to debug it.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
cc @kyessenov

**Comment by siddharthkhonde** [comment]
@littlejiancc is this still open? I can take a look into this as a beginner.

**Comment by littlejiancc** [comment]
> @littlejiancc is this still open? I can take a look into this as a beginner.

@siddharthkhonde yes, it's still open

**Comment by littlejiancc** [comment]
help wanted

**Comment by kyessenov** [comment]
Hi there, this is because you are not using InternalListener. The passthrough metadata only works when using internal addresses and internal listeners, not 127.0.0.1.

**Comment by littlejiancc** [comment]
@kyessenov Thank you for your response. I upgrad the version of Envoy and then use InternalListener, and it works.
