### ISSUE TITLE
Adding a new ext_proc mode: OPTIMAL-STREAMED to reduce the amount of gRPC calls

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#32110]
*Title*: Adding a new ext_proc mode: OPTIMAL-STREAMED to reduce the amount of gRPC calls

*Description*:

STREAMED mode has the issue that if the data chunks are small and traffic is slow, it may cause Envoy to send one gRPC for each chunk which only carries a couple of bytes payload to the ext_proc server. And thousands of gRPCs are sent for data. This is very inefficient. So there might be a need to implement a new body mode: OPTIMAL-STREAMED, which is to buffer the body chunk to some extent, like 16k, then send. Thus This new mode is basically buffer the data up to 16k, then send to the ext_proc server if one the following meets:
i) buffer reach 16k;
ii) end_stream true received;
iii) trailer received.
iv) a timer fire up.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
cc @gbrail @stevenzzzz @tyxia @mattklein123 @htuch @yanavlasov
