### ISSUE TITLE
Update http-filter-example 

### ISSUE THREAD

**Issue by sundarms** [envoyproxy/envoy#32111]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Update http-filter-example repo

*Description*:
I was trying to write a filter and following https://github.com/envoyproxy/envoy-filter-example/tree/main/http-filter-example
But this seems to be outdated and need to be revisited and fixed.
As per slack conversation https://envoyproxy.slack.com/archives/C78HA81DH/p1706594250162759 
Yan Avlasov mentioned build is failing for filter example.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
Filter example https://github.com/envoyproxy/envoy-filter-example/blob/main/http-filter-example/http_filter_config.cc#L14C46-L14C82
Was wondering if this is still upto date and correct way to create a filter?
When i look at other filter implementation i see they are deriving from Common::FactoryBase ex, https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/bandwidth_limit/config.h#L16

**Comment by alyssawilk** [comment]
cc @phlax @yanavlasov
