### ISSUE TITLE
Add per-policy metrics to the RBAC filter

### ISSUE THREAD

**Issue by henrymwang** [envoyproxy/envoy#32129]
*Title*: Add per-policy metrics to the RBAC filter

*Description*:
The RBAC filter exposes the effective policy ID through dynamic metadata which can then be logged with access logging, however we would like to expose this as a metric to get per-policy granularity since we sample access logs. The idea would be to add a new set of metrics which get incremented per-policy for both enforced and shadow-enforced rules.

The filter uses `http.<stat_prefix>.rbac` as its metric namespace already so we'd be adding a new set of metrics, example below:

```
http.<stat_prefix>.rbac.policy.<policy name>.allowed: 0
http.<stat_prefix>.rbac.policy.<policy name>.denied: 0
http.<stat_prefix>.rbac.<optional shadow_stat_prefix>.policy.<shadow policy name>.shadow_allowed: 0
http.<stat_prefix>.rbac.<optional shadow_stat_prefix>.policy.<shadow policy name>.shadow_denied: 0
```

I can prepare a patch for this if it sounds reasonable.

**Comment by alyssawilk** [comment]
cc @yangminzhu @yanavlasov

**Comment by henrymwang** [comment]
@alyssawilk could you add no stalebot to this issue? Implementation is ongoing in https://github.com/envoyproxy/envoy/pull/32313
