### ISSUE TITLE
IpVersions/Http2FrameIntegrationTest.CloseConnectionWithDeferredStreams/IPv4_Oghttp2 is very flaky 

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#32132]
I've seen this test failing quite regularly in CI. Here's a recent example:

https://dev.azure.com/cncf/envoy/_build/results?buildId=161090&view=logs&jobId=d1f76054-8f79-554b-6f4a-11d6a63b8e00&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=33c64725-b304-5065-9740-0ce244fa1a25

**Comment by RyanTheOptimist** [comment]
Seems to be failing quite regularly in TSAN. Here's [another failure from just now](https://dev.azure.com/cncf/envoy/_build/results?buildId=161260&view=logs&jobId=d1f76054-8f79-554b-6f4a-11d6a63b8e00&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=33c64725-b304-5065-9740-0ce244fa1a25):

```
[ RUN      ] IpVersions/Http2FrameIntegrationTest.CloseConnectionWithDeferredStreams/IPv6_Oghttp2
./test/integration/server.h:445: Failure
Value of: TestUtility::waitForCounterEq(statStore(), name, value, time_system_, timeout, dispatcher)
  Actual: false (timed out waiting for http.config_test.downstream_rq_rx_reset to be 20000, current value 0)
Expected: true
Stack trace:
  0x3ae60d7: Envoy::IntegrationTestServer::waitForCounterEq()
  0x334992a: Envoy::Http2FrameIntegrationTest_CloseConnectionWithDeferredStreams_Test::TestBody()
  0xaa64278: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0xaa49d6b: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0xaa2d5b9: testing::Test::Run()
  0xaa2e3f2: testing::TestInfo::Run()
... Google Test internal frames ...

[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_runtime_initialized to: false
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_http2_use_oghttp2 to: true
[external/com_google_absl/absl/flags/internal/flag.cc : 115] RAW: Restore saved value of envoy_reloadable_features_no_extension_lookup_by_name to: true
[  FAILED  ] IpVersions/Http2FrameIntegrationTest.CloseConnectionWithDeferredStreams/IPv6_Oghttp2, where GetParam() = 8-byte object <01-00 00-00 01-00 00-00> (138323 ms)
```

**Comment by phlax** [comment]
and another https://dev.azure.com/cncf/envoy/_build/results?buildId=161333&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=33c64725-b304-5065-9740-0ce244fa1a25&l=1225

this one is pretty high priority i think its failing PRs **a lot** also

**Comment by phlax** [comment]
![image](https://github.com/envoyproxy/envoy/assets/454682/b62a07ba-a200-4593-8853-6411fac5bb31)

**Comment by phlax** [comment]
@RyanTheOptimist @birenroy im wondering if we should revert https://github.com/envoyproxy/envoy/pull/32078 (this is where the flake started afaict) while we figure out the issue

**Comment by birenroy** [comment]
I'm trying to reproduce the issue. Running the test for 1000 iterations under TSAN with our internal tooling has not reproduced the problem.

I'm also trying in a github checkout at the tip of tree, but that is taking longer to run.

**Comment by RyanTheOptimist** [comment]
Fixed viaf https://github.com/envoyproxy/envoy/pull/32232
