### ISSUE TITLE
io_uring tests not executed in coverage CI

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#32149]
Coverage CI is failing because coverage is too low in source/common/io. https://dev.azure.com/cncf/envoy/_build/results?buildId=161211&view=logs&jobId=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&t=573d8780-d7b9-52e3-b4e0-a89886b0b9ff @phlax tracked this down to a problem where this code is not being executed on our CI hosts.

**Comment by phlax** [comment]
>  a problem where this code is not being executed on our CI hosts.

i think the problem is with the RBE workers

**Comment by soulxu** [comment]
This is fixed by setting the container as priviledged https://github.com/envoyproxy/envoy-build-tools/pull/323
