### ISSUE TITLE
Go Filter: gRPC Field Extraction & proto message logging filter

### ISSUE THREAD

**Issue by jgrnrt** [envoyproxy/envoy#32144]
***Title***: GRPC Field Extractions - Support for google wrappers

***Description***:
Hello,
thank you for your hard work. We are sadly forced to use the google wrappers in our proto messages. Is there any chance, that you could implement field extraction for those?
We are mostly using google.protobuf.StringValue, google.protobuf.Any and google.protobuf.BytesValue.

The current error we are getting is:
leaf node 'Id' must be numerical/string or timestamp type

***Workaround we tried***:
We also tried to implement a go http filter, that tries to unmarshal the request body in the DecodeData method. It throws no error, but my field extractions are nil.
Testing it locally works without problems. Also testing it in the envoy filter works with a dummy request (in the filter itself, not sending one to the envoy). 
I'm not quite sure, what buffer.bytes() returns (when a grpc request comes in) in the go filter.

I'm also getting different errors with different methods sending the grpc request. 
Sending the requests with grpcurl or with the grpc-go-client results in an unmarshalling error: "proto: cannot parse invalid wire-format data".

When i'm sending the request with postman, i don't receive an unmarshalling error. But the fields are still nil.

I hope if you could implement the google wrappers for the field extraction filter, it would mean, that we don't need to dig deeper into the workaround problem.

*Relevant Links*:
wrappers: https://protobuf.dev/reference/protobuf/google.protobuf/
other wrapper link https://protobuffet.com/protodocs/google/protobuf/wrappers.proto/

Thank you

**Comment by alyssawilk** [comment]
cc @adisuissa @yanavlasov ?

**Comment by adisuissa** [comment]
I don't fully grok what the problem is, can a repro be provided?
Also is this a config issue or an go-filter (/contrib/golang/) issue?

**Comment by jgrnrt** [comment]
Sorry for any confusion. I've provided 2 problems. 
## 1. Problem - gRPC Field Extraction Capabilities
The gRPC Field Extraction Filter only accepts following primitive types: string, uint32, uint64, int32, int64, sint32, sint64, fixed32, fixed64, sfixed32, sfixed64, float, double as target fields. Stated [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_field_extraction/v3/config.proto).

Our protobufs are using google wrappers, which aren't primtive types.
```
message Message{
    google.protobuf.StringValue iD = 1 
}
```

That's when i get the error: "leaf node 'iD' must be numerical/string or timestamp type".
Or maybe I'm doing something wrong, was someone able to extract a field with a google wrapper?

## 2. Problem - go-Filter request/response body
As a workaround I've tried to implement a go filter. Which is supposed to unmarshal the body.

```
import (
    proto "google.golang.org/protobuf/proto"
    pb "messagepb"
)

// DecodeData or EncodeData Method
func (f *filter) DecodeData(buffer api.BufferInstance, endStream bool) api.StatusType {

    if endStream {

        api.LogInfo("starting decoding grpc:")
        body := buffer.Bytes()

        // empty object
        Message := &pb.Message{}

        if err := proto.Unmarshal(body, Message); err != nil {
            api.LogInfof("err: %v", err)
        }
        
        api.LogInfof("\nExtracted fields: %v\n", Message)
        api.LogInfof("id: %v\n", Message.GetiD())
    }
    return api.Continue
}
```

### Errors sending requests

#### 1. Sending with grpcurl or with own grpc-go-client:
`Unmarshalling error: proto: cannot parse invalid wire-format data`

#### 2. Sending with Postman results in no unmarshalling error

But all three methods return with the same extracted fields:

```
Extracted fields:   ___________   (blank, no fields)

iD: <nil>
```

**Comment by doujiang24** [comment]
> ## 2. Problem - go-Filter request/response body
> As a workaround I've tried to implement a go filter. Which is supposed to unmarshal the body.
> 
> ```
> import (
>     proto "google.golang.org/protobuf/proto"
>     pb "messagepb"
> )
> 
> // DecodeData or EncodeData Method
> func (f *filter) DecodeData(buffer api.BufferInstance, endStream bool) api.StatusType {
> 
>     if endStream {
>         api.LogInfo("starting decoding grpc:")
>         body := buffer.Bytes()

you could print the body into log for debugging:
```
api.LogDebug(fmt.Sprintf("data: %s", body))
```

> 
>         // empty object
>         Message := &pb.Message{}
> 
>         if err := proto.Unmarshal(body, Message); err != nil {
>             api.LogInfof("err: %v", err)
>         }
>         
>         api.LogInfof("\nExtracted fields: %v\n", Message)
>         api.LogInfof("id: %v\n", Message.GetiD())
>     }

Should not ignore the buffer when end_stream is false.
Envoy support streaming processing, you have to buffer the streaming data when you want to get the whole body, i.e. buffering them into the `filter` struct, since the golang filter instance is per request.

>     return api.Continue
> }
> ```
> 
> ### Errors sending requests
> #### 1. Sending with grpcurl or with own grpc-go-client:
> `Unmarshalling error: proto: cannot parse invalid wire-format data`

Does this error message from this line?
```
api.LogInfof("err: %v", err)
```

> 
> #### 2. Sending with Postman results in no unmarshalling error
> But all three methods return with the same extracted fields:
> 
> ```
> Extracted fields:   ___________   (blank, no fields)
> 
> iD: <nil>
> ```

I think using golang filter should be a workable solution, since we are using the standard golang for unmarshalling.

**Comment by jgrnrt** [comment]
> buffering them into the filter struct

I don't understand what you mean. I need the complete bufferbody to unmarshal it with `proto.Unmarshal(body, Message)` or not?

I've now created a global var bufferedBytes bytes.Buffer. I'm writing the whole buffer.Bytes to it. 
Or should I try a different approch?

This is an example byte slice, which has 2 stringValue wrapper objects: 
```
[0 0 0 0 42 10 40 10 18 10 16 116 101 120 116 115 116 114 105 110 103 118 97 108 117 101 50 26 18 10 16 116 101 120 116 115 116 114 105 110 103 118 97 108 117 101 49]
byte slice: *
(

textstringvalue2
textstringvalue1
```
The Stringvalue2 is at the first position, I'm not sure if that is relevant. It shouldn't matter, because they're supposed to be fields.

Thanks to your answer, I used to get the output (only with Postman) at `Message.GetID().GetValue()`, but `Message.GETID()` was still \<nil\>. And the Message object was blank at `api.LogInfof("\nExtracted fields: %v\n", Message)`. 

Afterwards I tried to get the remaining methods working and now I receive the `Unmarshalling error: proto: cannot parse invalid wire-format data` with all request methods i send. 
I sadly couldn't revert to the old state, where the `Message.GetID().GetValue()` used to work.

Here is the new example code: 
```
func (f *filter) DecodeData(buffer api.BufferInstance, endStream bool) api.StatusType {

	api.LogInfof("buffered bytes: %s", buffer.Bytes())
	bufferedBytes.Write(buffer.Bytes())
	//buffer.Reset() // not sure if this is necessary here? i tried it with and without reset

	if endStream {

		byteSlice := bufferedBytes.Bytes()
		api.LogInfof("byte slice: %v", byteSlice)
		api.LogInfof("byte slice: %v", string(byteSlice))


		api.LogInfo("starting decoding grpc:")

		 // empty object
		Message := &pb.Message{}

		if err := proto.Unmarshal(body, Message); err != nil {
		 api.LogInfof("err: %v", err)
		}
		
		api.LogInfof("\nExtracted fields: %v\n", MessageRequestHeader )
		api.LogInfof("id: %v\n", MessageRequestHeader.getMessageFirstID()))
                api.LogInfof("id: %v\n", MessageRequestHeader.getMessageFirstID().GetValue()))

		bufferedBytes.Reset()
		buffer.Reset()
	}

	return api.Continue
}
```
I'm using a slightly different protodefinition.
```service MessageChannelService {
   rpc Message (MessageRequest) returns (MessageResponse);
}

message MessageRequest {
    MessageRequestHeader healthCheckRequestHeader = 1 [(validate.rules) = {message:{required:true}}];
}

message MessageRequestHeader {
    google.protobuf.StringValue messageFirstID = 1 [(validate.rules) = {string:{max_len:50},message:{required:true}}];
    google.protobuf.StringValue messageSecondID = 3 [(validate.rules) = {string:{max_len:50},message:{required:true}}];
}
```

This should be the Postman Message:


```
{
    "messageRequestHeader": {
        "messageFirstID": {
            "value": "velit"
        },
        "messageSecondID": {
            "value": "magna ut aute"
        }
    }
}
```

I'm not really sure, why it's not capable of unmarshalling the request. Maybe proto can't find the keys in the body. Do you have another idea?

**Comment by doujiang24** [comment]
@jgrnrt Here is an example that buffer the whole streaming data at stream request level:
```
type filter struct {
	api.PassThroughStreamFilter
	wholeData []byte
}

func (f *filter) decodeData(buffer api.BufferInstance, endStream bool) api.StatusType {
	f.wholeData = append(f.wholeData, buffer.Bytes()...)
	api.LogDebug(fmt.Sprintf("data: %s", f.wholeData))
	if endStream {
                 // now, there is the whole data of a request
		MessageRequestHeader := &pb.MessageRequestHeader{}

		if err := proto.Unmarshal(body, MessageRequestHeader); err != nil {
			api.LogInfof("err: %v", err, ", data: %s", f.wholeData)
		}
	}
}
```

I'm not familiar with how Postman works, if it encoding data just like the golang's `proto.Marshal(MessageRequestHeader)`, I do think it works, since golang feature is using a full featured golang.
Maybe you could try to compare the bytes in logs, between what Envoy got(Postman send) and the result from `proto.Marshal`?

**Comment by jgrnrt** [comment]
@TAOXUY In the documentation it says that only the request can be extracted. Is it also possible to extract the responses?
I'd also like to log the MessageResponse.
`rpc Message (MessageRequest) returns (MessageResponse);`

**Comment by jgrnrt** [comment]
@doujiang24 Thank you for your answer. 

> `if err := proto.Unmarshal(body, MessageRequestHeader); err != nil {`

I guess, that you meant f.wholeData instead of body?

Were you able to get this working on your end? Using my provided protodefintion, i still get the same error. 
`proto: cannot parse invalid wire-format data`

I've also noticed something else using the gRPC field extraction filter. If you use the DecodeData-Method to print the extracted Map in `if endstream { //print map from f.callbacks.StreamInfo().DynamicMetadata().Get(extractionfilter)}` I was able to receive the Map with a Postman request. When using grpcurl or the go client, i had an empty map.
I afterwards switched to the OnLog Method, were i was able to receive the maps from all requests.

**Comment by TAOXUY** [comment]
> @TAOXUY In the documentation it says that only the request can be extracted. Is it also possible to extract the responses? I'd also like to log the MessageResponse. `rpc Message (MessageRequest) returns (MessageResponse);`

It doesn't support now.

This filter is used to extract some req message fields on critical path for access control. If you are looking into logging some req/resp fields, we are developing the [proto message logging](https://github.com/envoyproxy/envoy/blob/d5425493807773c8d527e9376cfd2b9588c9c415/api/envoy/extensions/filters/http/proto_message_logging/v3/config.proto) filter.

**Comment by doujiang24** [comment]
> > `if err := proto.Unmarshal(body, MessageRequestHeader); err != nil {`
> 
> I guess, that you meant f.wholeData instead of body?

yes.

> 
> Were you able to get this working on your end? Using my provided protodefintion, i still get the same error. `proto: cannot parse invalid wire-format data`

nope, I haven't tried.
could you please provide a minial & runable example for testing, i.e. a golang example with source code to trigger a request to envoy, so that I can run it on my side. I'm not familar with the case you are testing.

> 
> I've also noticed something else using the gRPC field extraction filter. If you use the DecodeData-Method to print the extracted Map in `if endstream { //print map from f.callbacks.StreamInfo().DynamicMetadata().Get(extractionfilter)}` I was able to receive the Map with a Postman request. When using grpcurl or the go client, i had an empty map. I afterwards switched to the OnLog Method, were i was able to receive the maps from all requests.

Do you mean using `gRPC field extraction filter` together with `golang filter`? I do think they could work well together.
Could you provide the configurations used? I do not quite understand what you mean.

**Comment by jgrnrt** [comment]
@TAOXUY Is there an approximate ETA, when this filter will be implemented?

**Comment by TAOXUY** [comment]
Hi @jgrnrt , we are actively working it and it should be soon IMHO. No ETA yet.

@dchakarwarti

**Comment by jgrnrt** [comment]
@doujiang24 I've made a [fork](https://github.com/jgrnrt/envoy/tree/main/examples/golang-http) and used the sandbox for testing. Just clone the repo and run the commands as in the sandbox [documentation](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/golang-http). Or only download the compiled library.

### gRPC Go-Filter Field Extraction
Now you can send a grpcurl request with grpcurl to let it decode with the go filter.

```
Error: err: proto: cannot parse invalid wire-format data%!(EXTRA string=, data: %s, []uint8=[0 0 0 0 15 10 13 10 11 97 110 105 109 32 97 108 105 113 117 97])
HelloRequest:
```
### gRPC Field Extraction Filter with Go Filter
It works very good. But I think that, it only reliable works with the OnLog-function. 
As stated last time, I had problems extracting all the fields, when I used it in the DecodeData-method (with different methods of sending requests). 
But everything works in the OnLog-function.
I didn't provide a configuration, because I think that I will switch to the proto-message-logging-filter in near future.

I guess that the [proto message logging](https://github.com/envoyproxy/envoy/blob/d5425493807773c8d527e9376cfd2b9588c9c415/api/envoy/extensions/filters/http/proto_message_logging/v3/config.proto)-filter is going to work out of the box in a go-filter, right? Or will you need to make some adjustments as well?

**Comment by doujiang24** [comment]
@jgrnrt Sorry for the late. I'm on a long vacation, don't have much free time.

the `wholeData` is a gRPC Message, it prefix 5-byte header(Compressed Flag + Message Length), so, we need to strip them before `Unmarshal`, like this:
```
proto.Unmarshal(f.wholeData[5:], HelloRequest)
```

it works on my side.

**Comment by jgrnrt** [comment]
@doujiang24 
I already tried stripping the byte slice in the past, but I didnt try starting from index 5. Thank you for finding out the prefix size. It works for me as well. 
I wish you a good vacation. 

@TAOXUY Could you leave a message here and close the issue once you have released the proto message logging filter?
