### ISSUE TITLE
Clarification on TRY_NEEDS_AUDIT

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#32152]
*Title*: Seeking clarification on TRY_NEEDS_AUDIT

*Description*: As per title - I've done some scouring of issues trying to find the background of TRY_NEEDS_AUDIT. I've found this one https://github.com/envoyproxy/envoy/issues/14320 and this one https://github.com/envoyproxy/envoy/issues/10878

My question is quite simple: I'm working on aws_request_signing extension and want to remove these for cleanup. Is it sufficient to remove exceptions from within the extension and replace with correct handling eg absl::StatusOr? If that is achieved, is it ok to remove these macro wrappers? My knowledge of the threading model is so far non-existent so it would be good to understand whether the guidance of 'no exceptions on the main thread' applies here.

If I could get some clarification I can also make some dev docs updates to reflect the conversation.

Thanks!

**Comment by alyssawilk** [comment]
removing exceptions would be 10000% fantastic.
The original plan with Envoy exceptions was to allow them.  This was found to be problematic on the data plane so the next plan was to remove them on the data plane but allow them on the control plane (which is where "needs audit" comes from - it's for code sites where it's unclear if it was control or data plane).  This has been problematic we'd love to remove overall.

**Comment by nbaws** [comment]
That makes sense to me. I'm in the process of removing these from the AWS related code. One thing I found was that some exceptions are coming from data plane json processing, particularly the get* methods: https://github.com/envoyproxy/envoy/blob/44fc4213ed5012bae19bf7462d3e58e0783fccbe/source/common/json/json_internal.cc#L519

While it looks like the way around it is to use the getValue method which doesnt appear to throw, it probably makes sense to deprecate the throwable methods somehow so they don't keep getting used in the data plane.
