### ISSUE TITLE
transport_socket_matches different filter chains or set alpn_protocols in tls_context in HCM

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#32179]
We have a use case that a cluster which accepts http and non-http protocols.
However, in the upstream envoy, we want to send `alpn` bits in tls `transport_socket`

That is, we want to set
```
        "common_tls_context": {
          "alpn_protocols": [
            "h2"
          ],
```
for http traffic but not non-http traffic, so upstream envoy is able to use it to match different filter chain.

We want to avoid dup clusters, i.e., every protocol has its corresponding cluster, since that would dup the health check too.

We also see [trasnport_socket_matches](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-transport-socket-matches) but looks like we can't have multiple rules for one host except health check, which has [trasnport_socket_match_criteria](https://github.com/envoyproxy/envoy/blob/00536345a1f49ef19c1869253c7ce4d24be5ab58/api/envoy/config/core/v3/health_check.proto#L428)

We're looking to see if there's a way to set `alpn_protocols` in tls_context in HCM otherwise we might need a new http filter to hack the bytes.

Suggestion/feedback are welcome. Thanks!

**Comment by JuniorHsu** [comment]
Looks like it's not supported currently so we're working on a new http filter transport_socket_mutation

**Comment by ravenblackx** [comment]
@lizan might know if there's an easier way? Or @greenway? I'm not sure if this is more a TLS thing or a transport_socket thing.
