### ISSUE TITLE
envoy memory increasing high with big crl.pem file

### ISSUE THREAD

**Issue by catherye** [envoyproxy/envoy#32187]
The envoy momory usage increasing from 70Mi to 269Mi with crl.pem size about 4.6MB.

**Description:**
When the crl.pem with about 4KB, the envoy memory usage about 70Mi.
But when user did a chain revoke operations, the crl.pem increased to 4.6MB, and the corresponding envoy memory increasing to 269Mi, and even caused envoy crashed when reach to the container memory limitation.

**Reproduced step:**
1) The envoy configure like below:
  sds_int_validation_context.yaml: |-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: int_validation_context
        validation_context:
          trusted_ca:
            filename: /certs/sds/current/cacert.pem
          **crl:
            filename: /certs/sds/current/crl.pem**
          only_verify_leaf_cert_crl: true
          watched_directory:
            path: /certs/sds

2) replace the crl.pem with attachment and restart envoy process
3) check the envoy memory usage

**Comment by ggreenway** [comment]
Is that CRL used in multiple tls transport sockets? Or are there multiple certs on the tls transport socket?

**Comment by catherye** [comment]
Hi @ggreenway 
Yes, this CRL used in multiple tls transport socket,  and only cacert.pem and crl.pem used for TLS transport socket. 

Is the memory usage related to the number of server listen on or TLS conneciton established?
In this envoy container, there are 5 kinds cluster play as server listen on, and more than 100 connections esatabled.

Br
Catherine

**Comment by zsummer215** [comment]
Hi @ggreenway, would you please help check this issue?

**Comment by ggreenway** [comment]
Sorry, I'm not going to have time to look into this for awhile.
