### ISSUE TITLE
Make match_delegate filter a  dual filter

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#32194]
*Title*: Make match_delegate filter a  dual filter

*Description*:
It is useful to have match_delegate filter also working in upstream filter chain. So it is valuable to convert it into a dual filter.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yanjunxiang-google** [comment]
Currently the match_delegate filter is a downstream only filter:

https://github.com/envoyproxy/envoy/blob/14faf9d16c1082a2d8f2f65e4eb69a23db49e5e1/source/common/http/match_delegate/config.h#L106
It contains specific downstream filter logic in function: MatchDelegateConfig::createFilterFactoryFromProtoTyped():
https://github.com/envoyproxy/envoy/blob/14faf9d16c1082a2d8f2f65e4eb69a23db49e5e1/source/common/http/match_delegate/config.cc#L277

Need to convert this routine to be able to work for both downstream and upstream filter.
BTW, in dual_filter, there is a 'dual_info' in parameter list of  createFilterFactoryFromProtoTyped(..., dualInfo dual_info, Server::Configuration::ServerFactoryContext& context)  to distinguish between downstream or upstream filter. However the 'context' is now the ServerFactoryContext.   To call downstream filter routines, a Server::Configuration::FactoryContext parameter is required.

Please check: https://github.com/alyssawilk/envoy/blob/main/source/docs/upstream_filters.md for some details on how to convert a downstream filter into dual filter.

**Comment by wbpcode** [comment]
Sorry, but I am busy recently because internal business. So, there is no new progress.

**Comment by yanjunxiang-google** [comment]
Sure, adding @snowp

**Comment by yanjunxiang-google** [comment]
This is the PR https://github.com/envoyproxy/envoy/pull/32777
