### ISSUE TITLE
Make priority/locality overprovision factor configurable

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#3222]
*Title*: *Make priority/locality overprovision factor configurable*

*Description*:
Currently the priority/locality weighting load balancer will spill over traffic from one priority or locality to another if the first choice one is partially unhealthy, according to a fixed overprovision factor of 1.4. This is an awesome feature! However, since I'm migrating from a legacy traffic shaping system (which doesn't have this feature) to Envoy, I'd like to start out with this feature disabled so it matches current expectations

**Comment by mattklein123** [comment]
Agree it would be great to make this configurable. cc @htuch @alyssawilk

**Comment by mattklein123** [comment]
This is done.
