### ISSUE TITLE
Reconnecting AsyncTcpClient

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#32222]
Currently, when calling ``connect()`` of ``AsyncTcpClient`` after the remote closed the connection, a seg fault will occur. This is because when the remote disconnects, the connect timeout object is disposed:
https://github.com/envoyproxy/envoy/blob/966edc2cb92c95d7df1bf7d3d23b3ac17a21f2cd/source/common/tcp/async_tcp_client_impl.cc#L112

Therefore when calling ``connect()`` again, the object is invalid:
https://github.com/envoyproxy/envoy/blob/966edc2cb92c95d7df1bf7d3d23b3ac17a21f2cd/source/common/tcp/async_tcp_client_impl.cc#L46C3-L46C17

The question is - is the ``AsyncTcpClient`` meant to be resilient for remote disconnect? Can it be used to reconnect?
Either case - I think we should prevent this seg fault, either by allowing calling ``connect()`` one again if the underlying connection is closed, or explicitly not allowing calling ``connect()`` twice regardless, and the interface should be explicit about it.

cc @botengyao

**Comment by alyssawilk** [comment]
I don't think the client was meant for multiple connections.  I think it'd be fine to improve error handling or add reconnect features.
