### ISSUE TITLE
Compressor and decompressor window_bits set to 15 leads to periodically truncated data

### ISSUE THREAD

**Issue by Stono** [envoyproxy/envoy#32221]
I'm trying to transparently compress response data between services on my (Istio) mesh. 
To do this, I have a compressor filter on destination services and a decompressor on the source services.

I discovered that setting `window_bits` to 15 on both of them results in periodically truncated data.  This script loops through the same call and you can see how the data was truncated for one of them:

<img width="718" alt="Screenshot 2024-02-06 at 11 56 58" src="https://github.com/envoyproxy/envoy/assets/1486729/c0de7b84-15ad-434c-9f36-869a0382b973">

This _does not_ happen if i set the compressor window bits to 14 or lower.  

The documentation on https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/compression/gzip/decompressor/v3/gzip.proto.html#extensions-compression-gzip-decompressor-v3-gzip says 

> The decompression window size needs to be equal or larger than the compression window size 

So "larger" seems to be true, but "equal to" - not so much.

*Repro steps*:
Here are two gists for the two filters:

- https://gist.github.com/Stono/6385d379c7e24ac32fcf96e1310e7227
- https://gist.github.com/Stono/33820818ad2423abd8abd3450dcb0ede

**Comment by alyssawilk** [comment]
cc @kbaichoo @mattklein123

**Comment by KBaichoo** [comment]
Hmm, from the https://www.zlib.net/manual.html it seems like those parameters should be ok. 

Do you have any Envoy stats, or logs that occur on decompression showing any errors with your reproduction?

**Comment by Stono** [comment]
Hey sorry for the delay, as i've been coming back to this in bits and bobs.
No errors in the envoy logs, everything looks "normal" at debug level.
I've tried all sorts of different configurations in case it was some other weird interaction with things we're doing and haven't found anything at all.  The only thing that "fixes" it is a window_size of <= 14.

Not sure where else to go with it to help you debug!

**Comment by Stono** [comment]
Just realised i was logging from the compressor side there, and it's the decompressor side that would likely show any errors.  Will have another stab tomorrow.

**Comment by jessebye** [comment]
@Stono we just ran into a problem that is similar to this. Most gzipped requests are fine, but then some are truncated. We have our `window_bits` set to 15 as well. Did you manage to grab those decompressor logs?

**Comment by Stono** [comment]
Nope, and I haven't been able to recreate it since!

**Comment by jessebye** [comment]
Strange... I'm also confused how this would happen. We applied the compressor globally using an `EnvoyFilter` and had no issue for hundreds of our endpoints, but *one* endpoint gave back truncated responses. Removing the filter solved the issue, but now we're back to a lot of uncompressed responses.
