### ISSUE TITLE
OTEL Environment resource detector is unsafe/non-compliant due to error handling

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#32225]
*Title*: OTEL Environment resource detector is unsafe/non-compliant due to error handling

*Description*:
When configuring a resource detector over XDS, the config is rejected if there is no env var set: `Error adding/updating listener(s) 0.0.0.0_9080: Environment variable doesn't exist: OTEL_RESOURCE_ATTRIBUTES`.

This causes two issues: ability to use it safely, and OTEL compliance.

**Safe usage**: As an XDS server, I generally do not know all the environment variables a pod does or does not have access to. And in general, I think most servers are trying to avoid client-context-aware XDS resources to improve performance/caching/etc. This means I cannot reasonably set this configuration over XDS, unless I _know_ all clients will set this variable, which is quite hard to guarantee. This makes it unsafe to ever use this field. This, IMO, is quite different from most of XDS in general (I won't say _all_, since its a huge API!) - with the exception of ability to bind to a port, most things are safe for an xds server to push down to a client.

Rejected config can cause widespread outages. For example, if we added this to our control plane and pushed everywhere, 99.9% of clients probably do not set this env var, and thus will get NACKs and fail to startup or fail to get new updates.

**OTEL compliances**

The OTel [spec for resource detectors](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/resource/sdk.md#detecting-resource-information-from-the-environment) says:

> Resource detection logic is expected to complete quickly since this code will be run during application initialization. Errors should be handled as specified in the [Error Handling principles](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/error-handling.md#basic-error-handling-principles). Note the **failure to detect any resource information MUST NOT be considered an error**, whereas an error that occurs during an attempt to detect resource information SHOULD be considered an error.

(emphasis mine)

Additionally, the [Error Handling principles](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.29.0/specification/error-handling.md#basic-error-handling-principles) it links says:

> The API or SDK MAY fail fast and cause the application to fail on initialization, e.g. **because of a bad user config** or environment, but **MUST NOT cause the application to fail later at run time, e.g. due to dynamic config settings** received from the Collector.

The latter case, dynamic config settings, is what is triggered here.

Specifically to OTEL_RESOURCE_ATTRIBUTES, all of the other SDKs ignore it being unset. And this is even when a user explicitly writes code like `UseEnvResources()`.

---

For these two reasons, I would propose this is case does not result in rejected config. If need-be, this could be an option in the config, though I personally think its fine to just change the behavior for everyone for the reasons above.

**Comment by joaopgrassi** [comment]
I'm working on a PR to change it. 👍

**Comment by joaopgrassi** [comment]
PR is there.
