### ISSUE TITLE
stats release assert in thrift proxy

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#32234]
We start hitting a release assert and crash, which indicates unwanted behavior.
https://github.com/envoyproxy/envoy/blob/66b3c5e8512e66398bb82fc4117bcfe1fb2a98f6/source/common/stats/symbol_table.cc#L497

This occurs after we have a stats change https://github.com/envoyproxy/envoy/pull/31816

We already have`cluster.{CLUSTER}.thrift.upstream_resp_exception_local`.
In that PR, we're adding more stats with the prefix like `cluster.{CLUSTER}.thrift.upstream_resp_exception_local.timeout`. Unsure how it impacts the stats name set and decoder map.

One more hint is it seems to happen only in the draining stage, where some `ThreadLocalObject` are released and trigger this stats increment. 

I attached bt here [stats_abort_bt.log](https://github.com/envoyproxy/envoy/files/14185913/stats_abort_bt.log)

**Comment by alyssawilk** [comment]
cc @zuercher

**Comment by zuercher** [comment]
@JuniorHsu are you working on a fix?

**Comment by jmarantz** [comment]
The fix for this is usually ensuring that the Stats::Scope in which the offending stat was allocated outlives any possible uses of it. The fact that scopes are now held as shared_ptr may help manage this.

**Comment by JuniorHsu** [comment]
> The fix for this is usually ensuring that the Stats::Scope in which the offending stat was allocated outlives any possible uses of it. The fact that scopes are now held as shared_ptr may help manage this.

currently it's held by reference yeah
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/config.cc#L32

**Comment by jmarantz** [comment]
Anything is plausible but it would greatly complicate many call sites. I think we should just fix the bug and add testing to make sure this case gets covered.

This function isn't returning a stat, it's turning a numeric symbol (a StatName is really an encoded array of small integers which map to string tokens) into a string. It's typically used when extracting the stat name as a string. In this case it looks like a new stat is being constructed (or re-constructed) as part of a teardown process, where some of the support infrastructure is in a state of destruction. That's from a quick read of the stack trace and knowing nothing of Thrifty.

This class of problems where we get that assert usually happens due to order-of-declaration issues. We have to make sure the SymbolTable outlives the Store, the Store outlives the Scopes, etc.

**Comment by JuniorHsu** [comment]
Looks like the fix is to make the stats user own (like [shadow](https://github.com/envoyproxy/envoy/blob/55751292f59c203101884190b215ae6b0227a460/source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.h#L270#L270)) a shared pointer of [RouterStat](https://github.com/envoyproxy/envoy/blob/55751292f59c203101884190b215ae6b0227a460/source/extensions/filters/network/thrift_proxy/router/router.h#L128) which includes stat name sets tho it doesn't own symbol_table and scope?

**Comment by jmarantz** [comment]
the refs to these stats all need to outlive the stats system. I'm a little worried that just throwing shared_ptr at this  won't be sufficient; I don't want folks to go down a rabbit hole.

Can we avoid reporting these stats during shutdown?

**Comment by JuniorHsu** [comment]
Avoid reporting if `Upstream::ClusterManager::isShutdown()` returns true?
https://github.com/envoyproxy/envoy/blob/main/envoy/upstream/cluster_manager.h#L324

Network filter could check this I think.

Not super familiar if this signal is early enough to prevent crash.

**Comment by jmarantz** [comment]
That sounds racy. What if the shutdown occurs right after your call to isShutdown and before you access stats?

I'm not remembering what causes this shutdown flow to work really well but I'm sure it's not that test. I feel like this ultimately is going to be solved by looking at your various support structures and making sure their order of declaration matches the lifetime needs.

**Comment by JuniorHsu** [comment]
> I feel like this ultimately is going to be solved by looking at your various support structures and making sure their order of declaration matches the lifetime needs.

I have a hunch that we should go back to let stats owner own a shared_ptr of stats since common practice of filters is filter owns filter_config which owns the stats name sets. Otherwise I'm not super sure what could a network filter own. 

Or should we own our scope by `createScope` like https://github.com/envoyproxy/envoy/pull/30931 as shadow request could have as long as the lifecycle of thread local storage?

**Comment by jmarantz** [comment]
agreed: I think source/extensions/geoip_providers/maxmind/geoip_provider.h is a good model; seems like it was a similar symptom.
