### ISSUE TITLE
lds and cds dynamic resources configuration for envoy is not working

### ISSUE THREAD

**Issue by tahakhasam** [envoyproxy/envoy#32251]
*Title*: *lds and cds dynamic resources configuration for envoy is not working*

*Description*:
We have created an envoy pod and we have a given a configuration like this:
node:
  id: envoy_ingress_id
  cluster: envoy_ingress_cluster
dynamic_resources:
  cds_config:
    resource_api_version: V3
    path: cds/cds.yaml
  lds_config:
    resource_api_version: V3
    path: lds/lds.yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

both these paths are empty dirs and we update these files using a configmap_watcher and recreate the new file
which is registered by the envoy as well

so this log is seen with debug
[2024-02-06 16:50:24.096][21][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: lds.yaml
[2024-02-06 16:50:24.096][21][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: lds.yaml

but even after this the configuration is not updated
and neither any configuration logs pertaining to configuration update is seen
 Could you please check this and also let us know if we are missing something.

**Comment by alyssawilk** [comment]
cc @adisuissa

**Comment by phlax** [comment]
also worth checking the related sandbox https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/dynamic-configuration-filesystem

**Comment by tahakhasam** [comment]
we had tried with secrets when they were actually populated from the start and even then envoy picked up on it but the configuration was still not updated. could you explain on what basis will the new configuration change happen if the watcher was able to capture a change as in live traffic needs to stop or any specific change for cds or lds or any change will affect the configuration update?

**Comment by phlax** [comment]
the only thing im aware of is how it detects the fs change

> Envoy only updates when the configuration file is replaced by a file move, and not when the file is edited in place.

https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem#configuration-dynamic-from-filesystem

does the sandbox i posted above work for you? im reasonably confident it should as its tested in CI

**Comment by tahakhasam** [comment]
Thanks it works now

**Comment by fangchaooo** [comment]
The issue still exist.
I do this:
1. normal file create

  ```
  node:
    cluster: simview-cluster
    id: an-unique-id
  
  dynamic_resources:
    lds_config:
      path: conf/lds.yml
    cds_config:
      path: conf/cds.yml
  
  
  admin:
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 19000
  ```
  
  ```
  cds ....etc
  lds..... etc
  ```

2. mv lds cds file
```
touch /tmp/lds.yml (empty file)
touch /tmp/cds.yml (empty file)

mv /tmp/lds.yml lds.yml
mv /tmp/lds.yml cds.yml
```
3. find nothing to change
`curl -s http://localhost:19000/config_dump > /home/envoy.txt   ` find the config is normal (the step 1 config, not step 2)

Is there any memory for envoy dynamic_resources? Or if envoy find error config (like step2 empty), it use last memory config?
