### ISSUE TITLE
Should the docker image have bazel 0.12.0?

### ISSUE THREAD

**Issue by ambuc** [envoyproxy/envoy#3225]
*Title*: Should the docker image have bazel 0.12.0?

*Description*:
I think the version of bazel in the docker image is stuck at 0.10.0, whereas locally I'm running 0.12.0. Do we intentionally pin the version at 0.10.0 somewhere? Or are we intending to keep the bazel version inside the image at the latest? We might need to rebuild the image.

I think this might account for a bit of testing weirdness I'm seeing locally where https://github.com/envoyproxy/envoy/commit/2d744738c8ba57c189ac5444b3e48f45c442c8ee extracts a bit of :logging_lib into :minimal_logging_lib in a way that breaks on local bazel.coverage runs but not on circleci.com.

```
jbuckland@ ~/gh/envoy
$ bazel version
Extracting Bazel installation...
 ...........
Build label: 0.12.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Aug 4 01:22:27 +50246 (1523462001747)
Build timestamp: 1523462001747
Build timestamp as int: 1523462001747
```
```
jbuckland@ ~/gh/envoy
$ ./ci/run_envoy_docker.sh 'bazel version'
.
Build label: 0.10.0
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Nov 9 04:43:10 +50056 (1517474666590)
Build timestamp: 1517474666590
Build timestamp as int: 1517474666590
```

**Comment by htuch** [comment]
I think this is because we haven't rebuilt the base image in a while, and we don't automagically bump when the Bazel latest changes. We should just do a force rebuild on CI and bump the CircleCI SHA.

**Comment by mattklein123** [comment]
Note that https://github.com/envoyproxy/envoy/issues/3177 will need to be fixed before we can build a new build imagine. Can you potentially look into that?

**Comment by mattklein123** [comment]
This is fixed.
