### ISSUE TITLE
Excessive Memory Consumption in EnvoyProxy During Continuous snapshot updated for the same node

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/envoy#32266]
*Title*: *Excessive Memory Consumption in EnvoyProxy During Continuous snapshot updates for the same node*

*Description*:

In my Kubernetes (k8) setup, I'm utilizing Envoy Proxy along with the Gatewayspec Httproute, and I've developed a controller for managing this Custom Resource (CR). Upon any updates to this CR, my controller generates a snapshot of the state of the world in XDS. To ensure each snapshot version is unique, I generate a random number between 0 and 100000000 during snapshot creation.

During the reconciliation process, the controller updates the snapshot with the latest state of the world using the method described in the [Go-Control-Plane Repository](https://github.com/envoyproxy/go-control-plane/blob/bac45794d399d1af65f0af7f6cd53ca4972f5a8f/pkg/cache/v3/simple.go#L78).

The issue arises when I load approximately 4000 HttpRoutes into the Kubernetes cluster, triggering around 4000 reconcile events, each of which calls the SetSnapshot method. Consequently, I observe a significant increase in router memory usage, reaching approximately ~800MB. Surprisingly, even after 10 minutes following the completion of the loading process, the memory consumption remains consistently high. However, upon restarting the router, the memory usage drops to around ~300MB.

During router restarts, only the final snapshot from the controller is retrieved. However, when the router is active, and I continuously load HttpRoutes into the cluster, the router receives the snapshot continuously with updated state of the world which is expected. 

My concern is whether the EnvoyProxy implementation retains all received snapshots instead of discarding the older ones upon receiving new snapshots. The observed behavior of increasing memory usage suggests that EnvoyProxy might be storing all received snapshots, leading to excessive memory consumption.

**Comment by ravenblackx** [comment]
@adisuissa ?
