### ISSUE TITLE
cel cleanup: upgrade and remove patch to fix macos

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#32261]
#32148 is adding a patch to fix macOS. This should become unnecessary after CEL is upgraded to https://github.com/google/cel-cpp/commit/16ca259aeea2330998f3665c289267a82a738d46 or newer.

However, there's an issue with absl:  latest CEL uses absl/base:no_destructor, which was added to absl on 2023-11-08, but envoy is on absl 20230802.1. So an absl upgrade will be required before CEL can be upgraded.

**Comment by kyessenov** [comment]
I have tried to update CEL. We also need to update googleapis. More importantly is this:

```
external/com_google_cel_cpp/common/sized_input_view.h:535:40: error: designated initializers are a C++20 extension [-Werror,-Wc++20-designator]
               OperationInput{.copy = {.src = &other.range_, .dest = &range_}}))
```

Are we close to C++20 as a minimum in Envoy? If not, I'd have to go and undo some C++20 changes in CEL CPP.
