### ISSUE TITLE
Is cross compiling envoy for linux:aarch64 on an linux:amd64 machine possible?

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#32279]
Envoy can be compiled on linux:aarch64 host targeting linux:aarch64 platform
Can envoy artifacts compile on linux:amd64 host targeting linux:aarch64 platform?
IF so, please point to documents/issues/links showing how to do this?

**Comment by phlax** [comment]
yes, but imhe its unfeasibly slow

our ci does actually build the release docker containers for arm on x86 - essentially by using `binfmt`

its not so hard to get a cross arch env running with docker using binfmt, i think you can use it outside of docker (eg using chroot or similar) by i dont recall trying it

**Comment by sambercovici** [comment]
@phlax , I am able to start compiling as you described via running the ubuntu build container with --platform "linux/arm64"
It is as you said is excruciating slow as bazel and the compilers are running under arm64 with cpu emulation.

I was asking if there is a way to run the compilation in an linux/amd64 system while asking the compilers to generate an  linux/aarch64 object and binaries. I may be wrong, but think that something similar may be done when compiling mobile targets

**Comment by phlax** [comment]
it may be possible (ie at bazel level) - see related discussion here https://stackoverflow.com/questions/62182539/cross-compile-c-project-for-arm64-with-bazel

i didnt track through but my guess is that any cross compilation method on linux is going to be using qemu at some level and is likely to have similar perf to using binfmt/docker/etc
