### ISSUE TITLE
Envoy does not use previously sent RouteConfiguration when initial_fetch_timeout value is changed inside Rds config

### ISSUE THREAD

**Issue by jparklab** [envoyproxy/envoy#32283]
*Title*: *Envoy does not use previously sent RouteConfiguration when initial_fetch_timeout value is changed inside Rds config*

*Description*:

 Based on [Resource warming](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol.html#resource-warming) section on the envoy documentation, envoy is expected to use the previously sent `RouteConfiguration` while warming up a `Listener` and management does not need to send the `RouteConfiguration` if there is no change. However, when a field inside `Rds` field in the `Listener`, including [`initial_fetch_timeout`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#envoy-v3-api-msg-config-core-v3-configsource) field, is changed in a `Listener`, Envoy does not use the previously sent `RouteConfiguration` and wait for management server for the `RouteConfiguration`. 

  This can cause Envoy to time out while waiting for the `RouteConfiguration`, and finishes `Listener` warming without the `RouteConfiguration`. Once a `Listener` is warmed up without `RouteCofiguration`, Envoy responds to requests to the route with 404(NR) responses until it is restarted or the `RouteConfiguration` is updated and management server sends the updated `RouteConfiguration` to Envoy.

 This happens because Envoy does not use `existing_provider` in https://github.com/envoyproxy/envoy/blob/v1.26.6/source/common/rds/route_config_provider_manager.cc#L82 if the hash value of rds configuration changes which prevents Envoy from using previously sent `RouteConfiguration`

 Can we update Envoy to use `existing_provider` when `initial_fetch_timeout` value is changed? Although we do not need to change it often, we sometimes need to change the value, and we want to avoid restarting envoy proxies whenever we need to update `initial_fetch_timeout` value.

*Repro steps*:

This can be reproduced by running an envoy proxy that uses ADS to fetch configurations from a management server, and change initial_fetch_timeout value in ConfigSource in a listener. I have a simple management server to reproduce the issue, and can provide it if helps.

**Comment by jparklab** [comment]
> Curious, what is the reason for dynamically changing `init_fetch_timeout` ?

We have multiple envoy proxies as edge proxies connected to the same management server receiving configurations for more than a few thousands of services, and we see a large number of fetch timeouts when we restart the management server since all of the envoy proxies reconnects. We want to adjust `init_fetch_timeout` to avoid fetch timeouts (we are also considering rearchitecturing,  however, that's a longer term goal for us).

The parameter will be updated when we release the change to the management server, and envoy proxies will get the updated value dynamically when it fetches updated `listener` configurations

**Comment by ravenblackx** [comment]
@alyssawilk I think (as codeowner on router)

**Comment by alyssawilk** [comment]
I suspect this is more of an RDS issue so tagging @adisuissa for thoughts

**Comment by akainu11** [comment]
Hi, @jparklab @adisuissa do you know if anyone is currently working on this issue? If not I would like to give it a try. Also, since I am fairly new with Envoy, could you point me in the right direction within the codebase to fix this bug and the general approach I could take? Thanks!

**Comment by srivatsav1998** [comment]
Hi, I am interested in working on this issue. Please let me know if this is still available.

I am new to this repository and would appreciate your sharing resources around the issue and starting pointers.

**Comment by iamkishan98** [comment]
Hi @jparklab, I am new to open source, want to work on good first issue types. I would love to work on this issue, if still available.

**Comment by cpakulski** [comment]
Backported to:
1.32: https://github.com/envoyproxy/envoy/pull/37749
1.31: https://github.com/envoyproxy/envoy/pull/37844
1.30: https://github.com/envoyproxy/envoy/pull/37846
