### ISSUE TITLE
v1.26-latest untagged from Dockerhub

### ISSUE THREAD

**Issue by simon-connektica** [envoyproxy/envoy#32301]
*Title*: v1.26-latest untagged from Dockerhub

*Description*:
The tag `v1.26-latest` is no longer available on Dockerhub, we first noticed this issue this morning.

*Repro steps*:
```
$ docker pull envoyproxy/envoy:v1.26-latest
Error response from daemon: manifest for envoyproxy/envoy:v1.26-latest not found: manifest unknown: manifest unknown
```
Pulling this tag has been working for 1 year at least, suddenly broke this morning.

**Comment by phlax** [comment]
> Pulling this tag has been working for 1 year at least, suddenly broke this morning.

huge apology @simon-connektica this is a very temporary situation - i published incorrect images and immediately removed them - there wasnt an easy way to revert to correct images.

this should be resolved in the next hour or so - just waiting on release CI

**Comment by simon-connektica** [comment]
Ok thanks a lot! We'll try again in an hour or two!

**Comment by phlax** [comment]
this should now be fixed (https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=1.26) apologies again for disruption

**Comment by simon-connektica** [comment]
Looks good, thanks!
