### ISSUE TITLE
Latest release (v1.29) truncates cookies when using gRPC web feature

### ISSUE THREAD

**Issue by xanather** [envoyproxy/envoy#32319]
Only the first cookie is received by the gRPC backend, all other cookies are dropped. Very easy to replicate.

Reverting to 1.28 fixes the problem.

Use the example provided here: https://grpc.io/docs/platforms/web/basics/

**Comment by kyessenov** [comment]
I'm not aware of a specific change, but it is probably something to do with header validation.

CC @lizan @yanavlasov

**Comment by xanather** [comment]
Will take a deeper look today at this.

**Comment by xanather** [comment]
OK so, after some investigation and some trace logging, there was a change made somewhere (or an improvement) where instead of the 'cookie' metadata being directly passed through (with comma seperators in its value for multiple cookies), its instead translated into a set of metadata entries with the same key (gRPC supports this) for each cookie.

I'll close this in a week if this was expected, maybe should be documented somewhere?

**Comment by xanather** [comment]
Also personal sidenote, I support the new functionality, I think it better makes use of how gRPC headers work, its just that this was a breaking change.
