### ISSUE TITLE
How can I make a custom load balancer policy?

### ISSUE THREAD

**Issue by nikhilro** [envoyproxy/envoy#32318]
Hey there,

I'm looking to make a custom load balancer policy. I want to route the request to an available machine. Each request is a long-lived task and none of the [built-in policies](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-loadbalancingpolicy-policy) work for our exact use case.

I currently have a node script that queries for an available worker and then proxies to that IP. Would like to bring this "discovery" logic to Envoy. 

I tried to look for examples in `source/extensions/load_balancing_policies` but all they seem dense. Eg. the `random` one links to impl outside the folder. I really just want to customize the `chooseHost` function for the request forwarding decision.

Would appreciate pointers on exactly what's needed!

P.S. I know I could potentially use health checks to hide some workers from Envoy but that doesn't work for another reason that's specific to us. I unfortunately do need a custom load balancer policy.

Thanks,
Nikhil

**Comment by kyessenov** [comment]
I think you have two possible designs here:

1. Have a "cluster" or a pool of workers managed via CDS and EDS, that determine the lifecycle of the upstream machines. You can look at the stateful sessions HTTP filter on how to override the upstream host selection via a downstream filter, that can have your custom logic.

2. Fully unmanaged upstream. You can look at "original_dst" upstream load balancer that simply doesn't load balance. A downstream filter can explicitly set the upstream destination. You have to rely on "the wire" means to expire existing connections, e.g. via max age, or idle timeouts.

CC @tonya11en

**Comment by tonya11en** [comment]
It's unclear what you actually need the host selection behavior to be. Can you elaborate on the specifics here, so we can understand why the existing LB policies won't work?

If the existing policies truly don't work, I'll endorse option 2 above.

**Comment by nikhilro** [comment]
Happy to elaborate. I ended up finding a bandaid solution for now, hence the delayed response. Would still like to use Envoy though.

We make voicebots people can put behind phone numbers. For a new call, Twilio sends us a websocket request and we direct that call to one of the available machines. There is a strict constraint where each machine can only handle 1 call, it needs 1 GPU. We've thought about making the whole system stateless but unfortunately that adds latencies that we can't afford. So, for now, that one call is pinned to that one machine and that machine should reject any new calls.

I would like to use Envoy to do the routing on incoming websocket connections to one of the available machines. The way this discovery happens right now is, I put the incoming request's uuid (generated) on a queue, one of the machine picks it up, announces to the load-balancer it will take it and load-balancer starts proxing. Would like to embed this logic into Envoy. 

Does that make sense?

**Comment by nikhilro** [comment]
Quick bump if anyone has thoughts :)

**Comment by tonya11en** [comment]
> We make voicebots that people can put behind phone numbers. For a new call, Twilio sends us a websocket request and we direct that call to one of the available machines. There is a strict constraint where each machine can only handle 1 call, it needs 1 GPU. We've thought about making the whole system stateless but unfortunately that adds latencies that we can't afford. So, for now, that one call is pinned to that one machine and that machine should reject any new calls.

I'm not sure that a custom LB policy is the place to do this. Load balancing algorithms generally assume that there are multiple load balancers forwarding traffic to the backends and aren't really cut out for this kind of state tracking you are trying to do. 

It sounds like a custom filter is that way to go for what you're trying to do.

**Comment by nikhilro** [comment]
I'm not expecting LB to track state. I'm just expecting to pass it an IP for each request that comes in. The state tracking will live outside of the LB. 

Could you link me to custom filter doc? Nothing immediately came up and I was guided to something that felt like filtering incoming requests.

**Comment by nikhilro** [comment]
Thanks team, will take a look. It seems hard enough that not going to be on immediate roadmap but soon--our shitty implementation with node `http-proxy` will work for next 3 weeks. A lot more support than I would've expected for a free open-source project 😄
