### ISSUE TITLE
Initializing events on downstream TCP Keep-Alive

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#32358]
The use case I'd like to support is being able to set a separate idle timeout for connections that receive TCP keep-alive, i.e. the current idle timer will be reset in TCP keep-alive is received from the downstream (even if no data is received). Additionally, there'll be another idle timer that disregards the TCP keep-alive. So for example, if a downstream client doesn't set keep alive, the connection will be closed due to idle timeout after 5 minutes, but if the downstream client sends TCP keep alives, it would be closed after 30 minutes.

Additionally, I'd like that network filters would be able to get called back on downstream keep-alive messages.
After reviewing the current API, I'm not sure if this is possible, and not sure if it's possible to register a file event for this cause, but will appreciate insights about this - is it possible to add such support?

**Comment by kyessenov** [comment]
@ohadvano My first question would be if a user space program can see the TCP keep alive pings from the kernel. I'd also wonder about the motivation for this feature - application-level pings usually perform better if you can have them.

**Comment by kyessenov** [comment]
CC @ggreenway

**Comment by ggreenway** [comment]
I'm pretty sure there's no way for userspace to find out that the kernel saw a keepalive. But if you can find a way to get this information, post here and we can discuss further.

**Comment by ohadvano** [comment]
Thanks for your help
