### ISSUE TITLE
Elevated `server closed the stream without sending trailers` after `enabling oghttp2`

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#32371]
*Title*: Elevated `server closed the stream without sending trailers` after `enabling oghttp2`

*Description*: 
We are seeing elevated level of `server closed the stream without sending trailers` in [grpc-go](https://github.com/grpc/grpc-go/blob/05db80f1185060521de1b0c24f06faf9c9003354/internal/transport/http2_client.go#L1175) after enabling `oghttp2` via
`envoy.reloadable_features.http2_use_oghttp2`.

*Repro steps*:
1. Enable `oghttp2` by setting `envoy.reloadable_features.http2_use_oghttp2` to true.
2. Run GRPC service with Envoy version of `20c7368afa9d686a109f9601ae1b9b6028b74b0a`.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by milton0825** [comment]
cc: @birenroy

**Comment by birenroy** [comment]
Do you have any log output from a grpc-go client? That would help us with debugging.

**Comment by milton0825** [comment]
So it seems like the GRPC client is not expecting a data frame with END_STREAM flag set. I am wondering where in envoy could be touching the flag.

**Comment by birenroy** [comment]
I wasn't able to find any `server closed the stream without sending trailers` in the logs you attached. Are you still able to reproduce the problem?

It would also be helpful to know the failure rate before and after enabling oghttp2. Are we talking 0.1%? 1%? 10%?

**Comment by milton0825** [comment]
Those are the logs from `grpc-go` client after I enabled:
```
GRPC_GO_LOG_VERBOSITY_LEVEL=99
GRPC_GO_LOG_SEVERITY_LEVEL=info
```

I can still see `server closed the stream without sending trailers` error message returned from `grpc-go` in the app.

The failure rate was ~0.001% and increase to the level of 0.1%.

**Comment by milton0825** [comment]
@birenroy any other information you need from me?

**Comment by birenroy** [comment]
Sorry for the delay. An increase from 0.001% to 0.1% might be difficult to reproduce, and therefore difficult to track down, especially if the reproduction involves running a complete gRPC service through an Envoy.

I am working on some cleanup to the HTTP/2 codec in https://github.com/envoyproxy/envoy/pull/32378; I'd like to revisit this after that PR.

**Comment by birenroy** [comment]
@milton0825 Now that https://github.com/envoyproxy/envoy/pull/32378 has been merged, would you be able to try enabling the oghttp2 feature again?

**Comment by milton0825** [comment]
It seems like https://github.com/envoyproxy/envoy/pull/32378 is just code clean up. Is it going to fix the issue?

**Comment by birenroy** [comment]
It simplifies the flow of HTTP/2 protocol events through the Envoy codec layer. At the very least, it will make the issue easier to investigate if we can reproduce the bug.
