### ISSUE TITLE
TLS inspector usage for mysql and postgres kind of usecases

### ISSUE THREAD

**Issue by deveshkandpal1224** [envoyproxy/envoy#32387]
*Title*: TLS inspector usage for mysql and postgres kind of usecases

*Description*:
- We have a usecase where a client connects to a mySQL server. The call path looks as follows: `client -> envoy -> squid / outbound proxy -> mySQL`.
- We have explicit allow listing configured on SQUID that checks if the domain you are trying to connect to is allowed or not.
- We don't want the client to explicitly set https_proxy, hence we use envoy's `tunneling_config` with `tcp_proxy` filter to perform auto connect.
- The tunneling_config requires usage of `%REQUESTED_SERVER_NAME%` to grab the server name and issue a CONNECT request on behalf of the client. 
- In order to grab `%REQUESTED_SERVER_NAME%` we need tls_inspector. However, it seems based on [this](https://github.com/envoyproxy/envoy/issues/21044) issue, tls_inspector does not play well with mysql protocol. Same issue is observed with postgres as well.

Is there a solution / recommendation available for this problem ? Appreciate any help in this regard!

**Comment by kyessenov** [comment]
There's no issue with the inspector when TLS on the wire to the proxy is known a-priori. The referenced issue occurs for permissive TLS, when a proxy may or may not receive TLS handshake from a client.
