### ISSUE TITLE
aws_request_signing: Support signing to be included in query string parameters

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#32388]
*Title*: *aws_request_signing: Support signing to be included in query string parameters*

*Description*:
Design proposal to allow aws_request_signing extension to add signing in query string parameters. For VPC Lattice use cases, it is possible to provide signing in query parameters and leave the Authorization header intact. This proposal addresses this scenario.

Change required:

- Additional api option to specify query string signing (default: no, aligned with current behaviour)
- Change to signer_base, sigv4_signer_impl and sigv4a_signer_impl to support adding the signature to query string 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

@suniltheta

**Comment by suniltheta** [comment]
sounds good! thanks
