### ISSUE TITLE
Return ResponseFlags in response headers

### ISSUE THREAD

**Issue by MAnyKey** [envoyproxy/envoy#3239]
It would be nice for a non-edge proxy to return ResponseFlags in response headers (e.g. x-envoy-response-flags). That way downstream clients could know the status of the envoy upstreams and that information could be used in monitoring.

**Comment by MAnyKey** [comment]
So, just to clear things up: are you interested in merging PR which just adds ResponseFlags to response headers?

**Comment by mattklein123** [comment]
@MAnyKey in general I want to look in aggregate at the problem space of having an option in which Envoy can return extended information in headers. This is things like response flags, upstream cluster routed to, timings, etc.

**Comment by mattklein123** [comment]
Let's track in the context of https://github.com/envoyproxy/envoy/issues/4283 which should cover this.
