### ISSUE TITLE
Extract username from basic auth http filter

### ISSUE THREAD

**Issue by fgouteroux** [envoyproxy/envoy#32419]
Hi,

I would ask for an update of the basic auth http filter (https://github.com/envoyproxy/envoy/pull/30079) to extract the username in a header or metadata.

The use case is the following, after user auth success I need to add the username in the request header that will be used by the application after. Ideally if we can choose the header name, it will be perfect.

Maybe something like:
```
users:
  inline_string: |-
      user1:{SHA}hashed_user1_password
      user2:{SHA}hashed_user2_password
  set_username_header: X-Scope-OrgID
```

cc @zhaohuabing

**Comment by zhaohuabing** [comment]
Hello, could you please assign this issue to me?
