### ISSUE TITLE
Extensions mismatch between metadata and config_dump

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/envoy#32429]
*Description*:
I tried to disable some extensions using [--disable-extensions](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-disable-extensions) flag. I referred the [extensions_metadata.yaml](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml) file and constructed each extension with `{category}/{extension name}` as instructed.
When running Envoy I got `failed to disable unknown extension` warning for each one of the following extensions:

* envoy.config_subscription/envoy.config_subscription.aggregated_delta_grpc_collection
* envoy.http.custom_response/envoy.http.custom_response.local_response_policy
* envoy.http.custom_response/envoy.http.custom_response.redirect_policy
* envoy.matching.http.input/envoy.matching.inputs.query_params
* envoy.upstreams/envoy.upstreams.tcp.tcp_protocol_options

When checking the extensions list in config_dump I noticed that indeed the above extensions are not in the list, and there are other extensions with a slight different name:
* metadata: https://github.com/envoyproxy/envoy/blob/ffe2c75d93d8dd643b90a6c473aa68aabcd92a2b/source/extensions/extensions_metadata.yaml#L1650-L1654
config_dump: 
  ```json
  {
         "name": "envoy.config_subscription.delta_grpc_collection",
         "category": "envoy.config_subscription"
  }
  ```
  extension name is different here.
* metadata: https://github.com/envoyproxy/envoy/blob/ffe2c75d93d8dd643b90a6c473aa68aabcd92a2b/source/extensions/extensions_metadata.yaml#L1628-L1634
config_dump: 
  ```json
  {
         "name": "envoy.extensions.http.custom_response.local_response_policy",
         "category": "envoy.http.custom_response",
         "type_urls": [
          "envoy.extensions.http.custom_response.local_response_policy.v3.LocalResponsePolicy"
         ]
  }
  ```
  extension name is different here.
* metadata: https://github.com/envoyproxy/envoy/blob/ffe2c75d93d8dd643b90a6c473aa68aabcd92a2b/source/extensions/extensions_metadata.yaml#L1621-L1627
config_dump: 
  ```json
  {
         "name": "envoy.extensions.http.custom_response.redirect_policy",
         "category": "envoy.http.custom_response",
         "type_urls": [
          "envoy.extensions.http.custom_response.redirect_policy.v3.RedirectPolicy"
         ]
  }
  ```
   extension name is different here.
* metadata: https://github.com/envoyproxy/envoy/blob/ffe2c75d93d8dd643b90a6c473aa68aabcd92a2b/source/extensions/extensions_metadata.yaml#L1428-L1434
config_dump: 
  ```json
  {
         "name": "query_params",
         "category": "envoy.matching.http.input",
         "type_urls": [
          "envoy.type.matcher.v3.HttpRequestQueryParamMatchInput"
         ]
  }
  ```
   extension name is different here.
* metadata: https://github.com/envoyproxy/envoy/blob/ffe2c75d93d8dd643b90a6c473aa68aabcd92a2b/source/extensions/extensions_metadata.yaml#L1298-L1302
config_dump: 
  ```json
  {
         "name": "envoy.upstreams.tcp.tcp_protocol_options",
         "category": "envoy.upstream_options"
  }
  ```
   extension category is different here.

There can be more cases as I didn't go over all extensions.

**Comment by kyessenov** [comment]
There's a test that is supposed to verify the config dump node against the build manifest. It's possible some extensions have aliases or were excluded from that test.

**Comment by shahar-h** [comment]
@kyessenov I guess that you referred to [this](https://github.com/envoyproxy/envoy/blob/3d0f5fd2e3a98227db0fa99aa0646f743ad6ff3e/test/exe/check_extensions_against_registry_test.cc) test?

I don't see any extensions exclusions or aliases there. Is it possible that it doesn't work as intended or it isn't running?
