### ISSUE TITLE
Extensions included in official build

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/envoy#32431]
*Description*:
I noticed that there are some extensions which appear on [extensions_metadata.yaml](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml) but are not included in official build: envoy.wasm.runtime.wamr, envoy.wasm.runtime.wasmtime and envoy.wasm.runtime.wavm (also stated [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/wasm#wasm-runtime)).
https://github.com/envoyproxy/envoy/blob/49425f55aa9212a64b3390909160c41dc22ff349/source/extensions/extensions_metadata.yaml#L1320-L1343

Is it supposed to be like that? In case it does, do I have some other way to programmatically get all extensions which are part of official build?

**Comment by kyessenov** [comment]
These wasm runtimes cannot be all included at the same time, for technical reasons. The official build includes only one of them, v8 I think.

To get the full list of extensions, there are two ways:

1. You can start the Envoy process, and it'll print the keys for all built-in extensions
2. You can check Node message in xDS and it has a list of extensions as well.

**Comment by shahar-h** [comment]
* Are there any other extensions in extensions metadata that are excluded from official build?
* Can I get excluded extensions from the code or I have to run Envoy to achieve that?
