### ISSUE TITLE
`@envoy//test/common/memory:memory_release_test ` is very flakely TIMEOUTing

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#32447]
Quite a few PRs are failing compile-time-options with a TIMEOUT on posted test

postsubmit seems to be mostly passing but its hitting a lot of PRs

i think the change that created the issue is here https://github.com/envoyproxy/envoy/pull/30353

https://dev.azure.com/cncf/envoy/_build/results?buildId=162619&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=4122df52-7ea9-5745-8c7d-f6b6f2c73149&l=134

**Comment by phlax** [comment]
cc @nezdolik

**Comment by phlax** [comment]
cc @ohadvano

**Comment by nezdolik** [comment]
@phlax i will create revert patch and open a test patch (later) to try out various parameters of memory allocation size with CI environment. cc @KBaichoo @yanavlasov

**Comment by KBaichoo** [comment]
Might be related to compile time options (looking at a sample of failed test):

- https://dev.azure.com/cncf/envoy/_build/results?buildId=162620&view=results 
- https://dev.azure.com/cncf/envoy/_build/results?buildId=162609&view=logs&j=e08c1e20-d729-552d-2215-5529dbdb5756 
- https://dev.azure.com/cncf/envoy/_build/results?buildId=162619&view=logs&s=4f7d954b-a765-565f-91a2-c04870dab43f&j=e969334a-0e55-5c18-ac96-8b546753391e 
- https://dev.azure.com/cncf/envoy/_build/results?buildId=162029&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=4122df52-7ea9-5745-8c7d-f6b6f2c73149 

I think the system doesn't work as expected with gperftools/tcmalloc; it might make sense to just enable it for tcmalloc/tcmalloc so we can get more deployment experience with this and figure out the gperftools piece as a follow up or a todo.

**Comment by anvo1115** [comment]
@nezdolik , will you fix https://github.com/envoyproxy/envoy/pull/30353 for merging into [envoyproxy:main](https://github.com/envoyproxy/envoy/tree/main)

**Comment by nezdolik** [comment]
@anvo1115 am working on fixing it in https://github.com/envoyproxy/envoy/pull/32589, for now memory releasing will not be supported for gperf tcmalloc. I work on the fix on my free time (is not part of my daily job).

**Comment by phlax** [comment]
im wondering if there is a better issue to track - this one was for the ci issue which was resolved by reverting
