### ISSUE TITLE
tcp_stats RTT buffer per request in lua

### ISSUE THREAD

**Issue by anuragagarwal561994** [envoyproxy/envoy#32475]
*Title*: *Need rtt between upstream / downstream per host in lua per request*

*Description*:
> In our service we have multiple clients and it is a latency critical application. We get a timeout from the client lets say 200 ms in the request. We dynamically configure this timeout for an individual request using lua module.

This works for most of the cases, but here we are using static values for network buffers which means RTT time with downstream and RTT time with upstream.

Our clients can be present in different locations and regions. So for example if our server is in oregon we might also get request from los angeles.

What we wanted was to dynamically get the RTT metrics using SRTT algorithm, we checked and found the metrics is available using tcp_stats under cx_rtt_us which is what we want, but this is available to us as metrics and also only at the listener level. We wanted to track this at a host level and be able to use the value. Similarly for cluster we need this information, basis on which we can reduce our timeouts -> timeout - RTT upstream - RTT downstream when sending it to the upstream so it can help respond within time and we stay under the dynamic SLA.

[optional *Relevant Links*:]
> This metrics is exposed by GLB https://cloud.google.com/load-balancing/docs/https/custom-headers under client_rtt_msec, we wanted a similar functionality but with envoy if possible.

**Comment by lizan** [comment]
cc @wbpcode

**Comment by anuragagarwal561994** [comment]
@wbpcode @lizan any updates here?

**Comment by wbpcode** [comment]
Sorry for the delay.

What you mean by `per host`? Per endpoint? I think maybe it's possible to expose stats value to lua. But not sure if it's possible to add the `per host` level stats support.

**Comment by anuragagarwal561994** [comment]
@wbpcode I get what are the challenges associated with this, especially when we are dealing from the perspective of the listener. 

So I would want to highlight what my use-case is, we have a edge envoy proxy and we have 2 setups:
* calls coming directly from the users like you and me, which is load-balanced by a global load balancer
* calls coming from some from different aggregator servers, lets say these are oreganisations like us who are off loading their user traffic to us

So we can divide them saying a client to server call and server to server call.

Now when I am using a global load balancer like google's, it is giving me its RTT between client and GLB and I only need to RTT between GLB and my proxy which I can define behind a single listerner not an issue.

My problem arises in the second server to server case where no GLB is involved and the requests are directly routed to envoy proxy, in this case we have different hosts (subdomain) and single listener for them. Some of them may be calling from the same region others may be from a nearby region or might be in the same google infra and their RTT duration might not be consistent.

Hence using a single listener tcp metrics won't give us usable enough data to be more optimal in responding back within stipulated time duration. Hence I wanted to understand if there is a better way this can be handled, may be we need to  make some changes in the way we have currently designed things.

**Comment by anuragagarwal561994** [comment]
@wbpcode anything you could think on this

**Comment by anuragagarwal561994** [comment]
@wbpcode any progress / updates on this?

**Comment by wbpcode** [comment]
What a huge delay!!! Sorry about that (ping me at slack if I forget to respond again)

I think what you want is per virtual host level TCP RTT stats? It's a little hard to do that in current `tcp_stats` extension. And the community has no plan to support virtual host level TCP stats for now. cc @jmarantz 

There are some possible solutions in my mind:
1. additional stats extension to record the per virtual host level stats if you have the ability to extend the Envoy.
2. We can provide the RTT per request in the access log with a new command formatter. (It's much easy and controllable to extend a the new log formatter, rather than extend our stats system.)

Sorry again for my delay.
