### ISSUE TITLE
AsyncTcpClient - reconnect events do not propagate onEvent

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#32500]
When using ``Tcp::AsyncTcpClientImpl``, in case the upstream disconnected, and a reconnect attempt is made (by calling ``connect()`` again, new events are not propagated to the callbacks, i.e. when ``onEvent(event)`` is called in the ``AsyncTcpClientImpl``, it won't call ``callbacks_->onEvent(event);``

I think this is because on the first time of disconnect, ``callbacks_`` is disposed:

https://github.com/envoyproxy/envoy/blob/f29c560425aec5ad50a8c5a24d94ec78a9c0875c/source/common/tcp/async_tcp_client_impl.cc#L130

@botengyao

**Comment by botengyao** [comment]
Yes, the callback is cleared when the connection is closed and it is a reference. We need to set the callbacks again to call connect() after the connection is disconnected. [ref.](https://github.com/envoyproxy/envoy/blob/f29c560425aec5ad50a8c5a24d94ec78a9c0875c/envoy/tcp/async_tcp_client.h#L44)

**Comment by ohadvano** [comment]
Got it, so this is by design I understand
