### ISSUE TITLE
Integrating Rust binaries in tracer extensions

### ISSUE THREAD

**Issue by hoolioh** [envoyproxy/envoy#32502]
*Title*: Integrating Rust binaries in tracer extensions

*Description*:
Hi envoy team, as you might know Datadog is currently integrating a tracer into envoy. As a result of a company initiative to harmonize implementations that are common to the different tracers implemented inside the company we'd have the need to use this common modules into the dd-trace-cpp project. The language of choice for those common modules is Rust which means we'd need to either compile Rust code inside envoy project or importing a precompiled binary during the compilation of the extension. I've tried to look for another extensions using any of the aforementioned mechanisms to integrate Rust code but, unfortunately, I had no luck. So Is there a way to integrate Rust code/libraries in a tracer?
Aside from that I've found this [PR](https://github.com/envoyproxy/envoy/pull/2252), with that we could build a dynamic library which will include the cpp tracer and the rust parts to be loaded upon envoy initialization right?

*Relevant Links*:
https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/datadog
https://github.com/envoyproxy/envoy/pull/2252

**Comment by lizan** [comment]
We currently don't have a mechanism for dynamic load and Rust support, but I'd be excited to see Rust code build inside Envoy and linking to binary. There was a discussion regards to dynamic loadable modules in https://github.com/envoyproxy/envoy/issues/2053 as well.

**Comment by hoolioh** [comment]
@lizan when you say you'd be excited to see Rust code build an linking to a binary you mean that the rust module should be embedded in the envoy project, built from source and linked as part of the envoy compilation (just as the tracer) right?
Would it be acceptable, as a first approach, to import a static library during the datadog tracer compilation and link to it?
