### ISSUE TITLE
Docker build results in "chown: changing ownership of '/build': Permission denied"

### ISSUE THREAD

**Issue by medavisjr** [envoyproxy/envoy#32505]
I'm trying to build the latest release (v1.29.1) of Envoy with BoringSSL FIPS-compliant mode. But regardless of what flags I'm using, or how simple the build params are, I always receive this error: `chown: changing ownership of '/build': Permission denied`.

This seems to be coming from `envoy-build-ubuntu` container that `./ci/run_envoy_docker.sh` spins up to perform the build.

*Repro steps*:
Environment is CentOS 7.9
Docker version 20.10.17

Running the following commands as `root`. It's very simple, just cloning branch v1.29.1 to source code and then running the build as described in https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build

```
mkdir -p src/envoy

cd src/envoy

git clone --depth 1 --branch v1.29.1 https://github.com/envoyproxy/envoy.git .

./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define boringssl=fips" ./ci/do_ci.sh release.server_only'
```

Even if I just run `./ci/run_envoy_docker.sh './ci/do_ci.sh release.server_only'` it still results in the same error:

```
chown: changing ownership of '/build': Permission denied
```

**Comment by lizan** [comment]
The default build temp directory is `/tmp/envoy-docker-build`, is that directory writable in your host machine? If not set ENVOY_DOCKER_BUILD_DIR to somewhere writable.

**Comment by medavisjr** [comment]
Hi @lizan, thanks for the reply! That directory does exist and is writable to `root`:

```
[root@host envoy-docker-build]# pwd
/tmp/envoy-docker-build
[root@host envoy-docker-build]# ls -al
total 4
drwx------.  2 root root    6 Feb 21 13:59 .
drwxrwxrwt. 19 root root 4096 Feb 22 15:16 ..
```
