### ISSUE TITLE
Received malformed Request headers in external processor http filter, I get wrong key for value. 

### ISSUE THREAD

**Issue by divyasriram90** [envoyproxy/envoy#32549]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Received malformed Request headers in external processor http filter, I get wrong key for value. *

*Description*:
>I have implemented the external processor filter in Go using grpc, the control comes to the Go lang grpc server, but the request headers are malformed like this:
pb.ProcessingRequest_RequestHeaders &{headers:{headers:{key:":authority"  3:"localhost:8801"}  headers:{key:":path"  3:"/v2/pet"}  headers:{key:":method"  3:"POST"}  headers:{key:":scheme"  3:"https"}  headers:{key:"content-type"  3:"application/json"}  headers:{key:"authorization"  3:"Bearer gateway"}  headers:{key:"user-agent"  3:"PostmanRuntime/7.36.3"}  headers:{key:"accept"  3:"*/*"}  headers:{key:"postman-token"  3:"1ce7e46c-73d6-4ce8-8b3a-f6097fd98157"}  headers:{key:"accept-encoding"  3:"gzip, deflate, br"}  headers:{key:"content-length"  3:"26"}  headers:{key:"x-forwarded-proto"  3:"https"}  headers:{key:"x-request-id"  3:"515b2ebf-6870-4369-a709-0bbf385781e1"}}}
Instead of value key I get "3" as the key.

*Repro steps*:
>I have followed similar to this approach https://github.com/ekkinox/ext-proc-demo/tree/main

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

**Comment by mattklein123** [comment]
Hmm, not sure. Seems like a proto compilation issue. cc @kyessenov @yanavlasov

**Comment by yenki** [comment]
I am in the exact same situation. It's more that cosmetic in my case. My external process sets a new header with key/value. Unfortunately envoy receives the new header and sets the key put the value is always an empty string. I agree it seems like a proto issue. How can I make sure my proto match the Envoy version. I am using v1.29.1

**Comment by yenki** [comment]
Ok I rolled back to version 1.25.11. The problem is gone now cc:@divyasriram90
I would like to understand what we have to do to get external processors to work with 1.29.
