### ISSUE TITLE
Support subseconds in custom access log format

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#3256]
*Title*: *Support subseconds in custom access log format*

*Description*:
Currently the default access log format [includes](https://github.com/envoyproxy/envoy/blob/master/source/common/common/utility.cc#L280) milliseconds. However, when defining a custom `%START_TIME%`, we're restricted to only what `strftime`/`put_time` provides, which does not include anything below second. It would be nice to be able to have subsecond/millisecond support in the custom time format.

This was brought up by @derekargueta in #2907, but I didn't see an issue for this. This also might be obviated by #2967.

In the short term, I don't see a clean solution to this. We could hack around it by providing a new token like `%f` (this is what python uses in its `strftime` for microseconds), which we could remove and replace like is done in the default format. Otherwise, we'll have to implement it custom in #2967

**Comment by mattklein123** [comment]
I think this is fixed.
