### ISSUE TITLE
Option to update overload_manager stop_accepting_requests_scale_percent manually

### ISSUE THREAD

**Issue by sekar-saravanan** [envoyproxy/envoy#32597]
*Title*: *Option to update stop_accepting_requests_scale_percent manually*

*Description*:
With help on overload_manager configuration, we can able to overload_actions.stop_accepting_requests partially, if cpu threshold breached (resource_monitors.injected_resource)
Here the stop_accepting_requests_scale_percent will be calculate with below formula
```
Sets the action state to 0 when the resource pressure is below the scaling_threshold,  
(pressure - scaling_threshold)/(saturation_threshold - scaling_threshold) when scaling_threshold < pressure < saturation_threshold,  
and to 1 (saturated) when the pressure is above the saturation_threshold.”  
https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager.html#triggers
```

In our cases, it's not giving the the result efficiently. cpu and stop_accepting_requests_scale_percent is in the state of flip-flop pattern. Some testing result give below.
```
scaling_threshold = 65
saturation_threshold = 100

block_percent = (pressure - scaling_threshold)/(saturation_threshold - scaling_threshold)

RPS     CPU%    stop_accepting_requests_scale_percent
---     ---     -----
1K      4       0
5K      18      0
10K     37      0
15K     57      0
20K     71      17  [(71 - 65)/(100 - 65) = 17]
        70      14  [(70 - 65)/(95 - 65) = 14]
        45      0   
        83      51  [(81 - 65)/(95 - 65) = 51]
        48      0
        79      40  [(79 - 65)/(95 - 65) = 40]
        55      0
25K     92      77  [(92 - 65)/(95 - 65) = 77]
        57      0
        96      88  [(96 - 65)/(100 - 65) = 88]
        49      0
        99      97  [(99 - 65)/(100 - 65) = 97]
```

In order to gradually blocking/releasing the request, we planning to calculate the stop_accepting_requests_scale_percent manually. We need option to update the this config in envoy. Is it currently possible ?

**Comment by mattklein123** [comment]
cc @KBaichoo

**Comment by KBaichoo** [comment]
>We need option to update the this config in envoy. Is it currently possible ?
You might be able to do this using https://github.com/envoyproxy/envoy/blob/main/source/extensions/resource_monitors/injected_resource/injected_resource_monitor.h#L20 though you'd then need an additional program maintaining the file generation that contains the CPU usage and could dampen that. 

How are you computing CPU usage?

**Comment by sekar-saravanan** [comment]
we are calculating based on cpuacct.usage. 

```
start=$(cat /sys/fs/cgroup/cpu/cpuacct.usage)
sleep 10
end=$(cat /sys/fs/cgroup/cpu/cpuacct.usage)
allocated=$(cat /sys/fs/cgroup/cpu/cpu.shares)

diff=$(($end - $start))
usage=$(printf '%.2f\n' $(echo $diff / 10000000 | bc -l))
usage_percent=$(printf '%.2f\n' $(echo $usage / $allocated | bc -l))
```
