### ISSUE TITLE
Modify ext_authz to correctly encode non-utf-8 header values

### ISSUE THREAD

**Issue by antoniovleonti** [envoyproxy/envoy#32607]
*Title*: *Modify ext_authz to correctly encode non-utf-8 header values*

*Description*:

Right now, ext_authz only correctly encodes headers whose values are valid utf-8. This is because the [header map field](https://github.com/envoyproxy/envoy/blob/bc0190146f08458ac5a58af5b3545b24660fa8f8/api/envoy/service/auth/v3/attribute_context.proto#L119) uses a string for the value, which requires utf-8 compliance. Otherwise it will generate errors when the receiving service tries to decode the value.

Currently, to ensure the value is valid utf-8, header values get sanitized [here](https://github.com/envoyproxy/envoy/blob/bc0190146f08458ac5a58af5b3545b24660fa8f8/source/extensions/filters/common/ext_authz/check_request_utils.cc#L141-L142) before being added to the proto. Any characters that are not valid utf-8 get replaced with `!`.

Ideally, we could figure out a way to start sending the header value's raw bytes, but I'm not sure how difficult that would be while also maintaining backward compatibility with the current behavior. I understand that ext_authz has a lot of users, so I wanted to discuss how we could achieve this as safely as possible.

@tyxia
@yanjunxiang-google 
@yanavlasov

**Comment by tyxia** [comment]
Thanks @antoniovleonti !

+ @ggreenway, I think we have agreed on the long-term approach of using raw bytes raw_value and we want to initiate this effort.

One thing we want to discuss is migration strategy or the plan of keeping backward compatibility. In ext_proc, we are doing runtime guard approach that deprecate the old behavior in ~ 6months. Is it feasible to implement a similar approach in ext_authz, considering it has been in existence for a much longer period?

If the migration effort is too high or we can not effectively mandate that ext_authz servers out there accept raw bytes, one alternative approach is doing this via config option: Default behavior is still using old approach and raw bytes approach can be enabled via config. 

We want to reach consensus on this within OSS community before kicking off the implementation.  We would appreciate any insights or feedback!

**Comment by ebyerly** [comment]
Three references:

* _Why do we sanitize the headers now?_ [CVE "gRPC client produces invalid protobuf when an HTTP header with non-UTF8 value is received."](https://github.com/envoyproxy/envoy/security/advisories/GHSA-9g5w-hqr3-w2ph)
* _What does the HTTP spec say about header field value and field content encoding?_ https://www.rfc-editor.org/rfc/rfc9110.html#name-field-values: "Historically, HTTP allowed field content with text in the ISO-8859-1 charset [ISO-8859-1], supporting other charsets only through use of [RFC2047] encoding. Specifications for newly defined fields SHOULD limit their values to visible US-ASCII octets (VCHAR), SP, and HTAB. A recipient SHOULD treat other allowed octets in field content (i.e., obs-text) as opaque data."
* _The Envoy message is used for both HTTP and gRPC requests; does gRPC have a more permissive expectation for header encoding?_ https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md: 
"Note that HTTP2 does not allow arbitrary octet sequences for header values so binary header values must be encoded using Base64 as per https://tools.ietf.org/html/rfc4648#section-4. Implementations MUST accept padded and un-padded values and should emit un-padded values."

We're already exceeding spec by accepting UTF-8 encoded headers. Do we want Envoy to return requests as malformed if the UTF-8 sanitization cannot be performed losslessly?

**Comment by antoniovleonti** [comment]
> ... Add a new boolean config token `headers_as_bytes` ...

This seems like the easiest solution to the immediate problem.

> We're already exceeding spec by accepting UTF-8 encoded headers. Do we want Envoy to return requests as malformed if the UTF-8 sanitization cannot be performed losslessly?

I think there would be a performance hit here. I'm not sure how significant that would be. Either way, we could add a boolean config token elsewhere that checks UTF-8 compliance before adding headers to the HeaderMap (default to false).

> A recipient SHOULD treat other allowed octets in field content (i.e., obs-text) as opaque data.

I'm curious what's meant by opaque data in this context.

**Comment by tyxia** [comment]
Yes, config option rmake sense to me as ext_authz has broader customer base.

**Comment by ggreenway** [comment]
> We're already exceeding spec by accepting UTF-8 encoded headers. Do we want Envoy to return requests as malformed if the UTF-8 sanitization cannot be performed losslessly?

I'm not sure what you mean here. Non-utf8 header values are definitely supported in http/1.1, at least older versions. We can't reject these requests.
