### ISSUE TITLE
Can Envoyproxy support the VIP(virtual IP) or IP failover directly?

### ISSUE THREAD

**Issue by minjunjiang** [envoyproxy/envoy#32651]
*Title*: *Can Envoyproxy support the VIP(virtual IP) or IP fail-over directly?*

*Description*:
>Here is our use case: we are trying to use the Envoyproxy as the reverse proxy for our services, and one of the Envoyproxy instance will work as the entry/endpoint to allow the customer to visit/access.

>But I  we will face the IP failover issue(out of service) once this Envoyproxy instance crashed.
The typical solution can be make use of keepalived to support the VIP and IP fail-over detection.

>For some reason it's not convenient for us to introduce new tool such as keepalived, can somehow the envoyproxy directly support such kind of use-case/scenario?

Thanks in advance.  

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
How VIPs work is generally a function of the VIP itself and how it performs health checking. This is outside the scope of Envoy. If you are asking if Envoy has support for BGP and can health check other Envoy nodes and decide to publish routes, no it doesn't currently support that.

**Comment by minjunjiang** [comment]
> How VIPs work is generally a function of the VIP itself and how it performs health checking. This is outside the scope of Envoy. If you are asking if Envoy has support for BGP and can health check other Envoy nodes and decide to publish routes, no it doesn't currently support that.

Thank you so much for your kindly reply.

**Comment by ahmet2mir** [comment]
@mattklein123 are you opposed to such support ?
I wrote https://github.com/ahmet2mir/herald but it's a pure L4 support and still need something on top like envoy for higer level decision.

In kubernetes world we have [MetalLB](https://github.com/metallb/metallb), [Cillium](https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane/)   & [Calico](https://www.tigera.io/blog/advertising-kubernetes-service-ips-with-calico-and-bgp/) to support BGP. 

Currently we use ExaBGP coupled to Envoy OR Haproxy, but i'm still unsatified by the level of "check" and failover, i love envoy. We drop Metallb on our kube and use Haproxy for container world.

On BGP side you could have a "daemon" acting as a router or a simple "speaker" (like exabgp, metallb, Herald); if you look at the code https://github.com/ahmet2mir/herald/blob/main/pkg/speaker/speaker.go it's a very dummy conf. Then with [ECMP](https://fr.wikipedia.org/wiki/Equal-cost_multi-path_routing) it's bgp itself that decide if the route is "up" or not, not envoy, envoy just ensure integrity, if the service is "down", it could stop leak the route and bgp will withdraw it

I could imagine a gobgp service running somwhere (herald embed it but it could be outside) and envoy just contact it to leak route and ensure health (to avoid configuring BGP peers, it could be frrouting, gobgp, or whatever exposing a socket/api).

WDYT ? I could propose an issue describing more in depth or it's completly out of scope ?
