### ISSUE TITLE
OpenCensus tracer does not support B3 single header

### ISSUE THREAD

**Issue by rafal-dudek** [envoyproxy/envoy#32661]
*Description*:
OpenCensus tracer should support not only multi B3 headers, but also single B3 header in both incoming_trace_context and outgoing_trace_context: https://github.com/envoyproxy/envoy/blob/d9048ad4a75ce00c13b9f06ebad45a938427b3ec/api/envoy/config/trace/v3/opencensus.proto#L44-L45
Most of the applications using B3 headers support both formats of the incoming and outgoing B3 headers, but some of them might support only one of them (like this OpenCensus supports only multi headers).
Some of the applications in our company support only single B3 outgoing header (while accepting both formats for incoming traffic).

*Relevant Links*:
There is a similar feature implemented for Zipkin Tracer: https://github.com/envoyproxy/envoy/issues/4289
but we cannot use it, because we are using Google Cloud Trace (stackdriver).

B3 single header standard: https://github.com/openzipkin/b3-propagation/tree/master?tab=readme-ov-file#single-header

**Comment by kyessenov** [comment]
Unfortunately, Open census is sunset and cannot receive patches upstream. We are looking how to support stackdriver clients.
