### ISSUE TITLE
Envoy doesn't recognize http2 connection needs to be terminated

### ISSUE THREAD

**Issue by Pchelolo** [envoyproxy/envoy#32670]
*Title*: Envoy doesn't recognize http2 connection needs to be terminated

*Description*:
I'm using envoy sidecar to route GRPC traffic between k8s with fairly straightforward config. When I kill upstream service I expect all the persistent http2 connections to it to be terminated and requests start failing instantly with UNAVAILABLE. However instead I'm seeing request timing out with either `http2.remote_reset` or `upstream_per_try_timeout` reaching the per-try timeout. What's even more surprising, even setting up tcp_keepalive does not help envoy understand the connection needs to be terminated. 

Am I missing some obvious setting or it's a bug?

*Logs*:

Here's example trace logs I get in this situation.

```
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:1213] [C17] recv frame type=0"
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:38] [C17] read error: Resource temporarily unavailable"
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:1213] [C17] recv frame type=8"
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:1187] [C17] about to recv frame type=1, flags=5, stream_id=31"
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:2233] [C17] track inbound frame type=1 flags=4 length=2 padding_length=0"
"Mar 1, 2024 @ 08:21:50.203","[2024-03-01 16:21:50.203][144][trace][http2] [external/envoy/source/common/http/http2/codec_impl.cc:2233] [C17] track inbound frame type=6 flags=0 length=8 padding_length=0"
"Mar 1, 2024 @ 08:21:50.188","[2024-03-01 16:21:50.188][144][trace][connection] [external/envoy/source/common/network/connection_impl.cc:563] [C17] socket event: 2"
"Mar 1, 2024 @ 08:21:50.188","[2024-03-01 16:21:50.188][144][trace][connection] [external/envoy/source/common/network/connection_impl.cc:674] [C17] write ready"
"Mar 1, 2024 @ 08:21:50.188","[2024-03-01 16:21:50.188][144][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:67] [C17] write returns: 182"
"Mar 1, 2024 @ 08:21:50.187","[2024-03-01 16:21:50.187][144][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:181] [C17] creating stream"
"Mar 1, 2024 @ 08:21:50.187","[2024-03-01 16:21:50.187][144][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:264] [C17] using existing fully connected connection"
"Mar 1, 2024 @ 08:21:50.187","[2024-03-01 16:21:50.187][144][trace][connection] [external/envoy/source/common/network/connection_impl.cc:478] [C17] writing 24 bytes, end_stream false"
```

**Comment by Pchelolo** [comment]
> My first thoughts is that the upstream is being terminated abrupted s.t. the connection teardown gracefully. This leads to Envoy thinking the connection exists and using it for streams which timeout, etc. Eventually Envoy figures out that the connection is terminated.

In this case I'm using golang GRPC and call both GracefulShutdown on the server and the Shutdown. However, my thinking is that it shouldn't matter - in case of networking issue or node crashing there will be no graceful termination, and downstream will keep timing out calling non-existent dead pod. This will have huge effect on p99 latency.

> What keepalive configuration do you use?

I've added tcp_keepalive with keepalive_probes: 3, keepalive_time: 10, keepalive_interval: 10, but that did not make any difference.

**Comment by KBaichoo** [comment]
golang GRPC and call both GracefulShutdown on the server and the Shutdown. However, my thinking is that it shouldn't matter
> In this case, the resets are probably due to racing if the GRPC server sends goaway frames and the proxy had in-flight request and the GRPC server as resetting existing streams / new streams after the goaway.

downstream will keep timing out calling non-existent dead pod. This will have huge effect on p99 latency.
> You can remediate this using health checks, outlier detection, hedging, etc.

**Comment by Pchelolo** [comment]
> In this case, the resets are probably due to racing if the GRPC server sends goaway frames and the proxy had in-flight request and the GRPC server as resetting existing streams / new streams after the goaway.

The resets persist long past the server completely disappearing and definitely not sending anything anymore.

> You can remediate this using health checks, outlier detection, hedging, etc.

Outlier detection doesn't work here since reset doesn't result in any grpc status and thus is not mapped to http 5xx.
Hedging only works in response to a request timeout - so it would not have any effect here - we still will need to wait for a request to non-existent upstream to timeout first.
I will try using active health checks - that will probably do it. 

My main point though is that this should be easier - it seems like a very common situation and it's not clear why envoy keeps a connection to a completely non-existent upstream. Shouldn't TCP connection being terminated just terminate the http/2 connection as well?

**Comment by KBaichoo** [comment]
My main point though is that this should be easier - it seems like a very common situation and it's not clear why envoy keeps a connection to a completely non-existent upstream. Shouldn't TCP connection being terminated just terminate the http/2 connection as well?

> If you're not using health information (passive or active) or changing EDS to tell Envoy to not speak to a given backend, it will continue to load balance to those backends. TCP doesn't always terminate cleanly with a FIN / ACK, and Envoy might just attempt to open another connection if a backend closed a connection

**Comment by Pchelolo** [comment]
I see, thank you for your responses. I'll try to implement active health checks
