### ISSUE TITLE
Golang HTTP filter—handle httpheader and httpbody in one function

### ISSUE THREAD

**Issue by Hectorsong** [envoyproxy/envoy#32673]
Hello, It seems that there are DecodeHeaders function to parse HttpHeader and DecodeData function to parse HttpBody in the Golang HTTP filter examples. 
Suppose I need to parse and validate the value from the http request body and put it in the http request header, and I just want to parse httpheader and httpbody in one function, what should I do?

**Comment by doujiang24** [comment]
You can buffer the header into the filter instance, filter manager will create a filter instance per request.
And it's safe to read/write the header, before returning api.Continue back to Envoy, that means Envoy will pass the header to the next C++ filter.

Here is an example:
```
type filter struct {
	api.PassThroughStreamFilter
	callbacks api.FilterCallbackHandler
	header    api.RequestHeaderMap
}

func handler(header api.RequestHeaderMap, body api.BufferInstance) api.StatusType {
	return api.Continue
}

func (f *filter) DecodeHeaders(header api.RequestHeaderMap, endStream bool) api.StatusType {
	if endStream {
		return handler(header, nil)
	}

	f.header = header
	return api.StopAndBuffer
}

func (f *filter) DecodeData(buf api.BufferInstance, endStream bool) api.StatusType {
	// Now, the buf means the whole body data.
	return handler(f.header, buf)
}
```
