### ISSUE TITLE
Envoy loose listener and cluster when connection to control plane is lost.

### ISSUE THREAD

**Issue by someshsumantwilio** [envoyproxy/envoy#32688]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Envoy loose listener and cluster when connection to control plane is lost.*

*Description*:
We have an incident in which some of the envoy agent lost the listener and cluster when the connection to control plane is lost. Control plane cert was expired and thats when the envoy agent were not able to connect to control plane. Once the connection to control plane is restored we saw that envoy listener and cluster config were restored and envoy got the correct no of listener and cluster. We are getting the listener and cluster from ADS from control plane. 
We observed this in envoy version 1.25.9 version. We wanted to check if we have observed this behaviour or if this have been fixed in the higher version. 

*Repro steps*:
We were not able to reproduce this after the incident.

**Comment by KBaichoo** [comment]
cc @adisuissa in case you've seen this before
