### ISSUE TITLE
tooling: should not need to include from source/

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#3270]
**Issue Template**

*Title*: *One line description*

*Description*:
>In  the comments in #2921 @mattklein123 noted that it was surprising we were including from "source/".  There are two files that do that
```
./source/common/ratelimit/ratelimit_impl.h:#include "source/common/ratelimit/ratelimit.pb.h"
./test/integration/ratelimit_integration_test.cc:#include "source/common/ratelimit/ratelimit.pb.h"
```
The latter can just have the reference removed, but `ratelimit_impl.h` picks up a generated protobuf header from `source/` the proto header is definitely needed, and the build system does not pick it up without the `source/` prefix. Lots of other protobuf headers are picked up in Envoy without the `source/` prefix so we just need to figure out what's different about this one.

**Comment by jmarantz** [comment]
once this is resolved, `source/` can be removed from tools/common.py as a legal header prefix.

**Comment by taion809** [comment]
It appears that ratelimit.proto exists in `source/common/ratelimit` instead of the `api/` directory.  I checked the `source/` directory and it is the only protobuf file left which is why you'd notice the discrepancy with other profobuf files.

```
➜ find ./source -name '*.proto'
./source/common/ratelimit/ratelimit.proto
```

It looks quite similar to `api/envoy/service/ratelimit/v2/rls.proto`

**Comment by mattklein123** [comment]
@taion809 see https://github.com/envoyproxy/envoy/issues/1034
