### ISSUE TITLE
lldb can't show any debug info, debugging symbols are missing?

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#32700]
I'm trying to debug Envoy in the official dev container.

I used VSCode as my IDE and official `devcontainer.json` to start the dev container of Envoy.

After entering the dev container, I executed the command `tools/vscode/generate_debug_config.py //source/exe:envoy-static --args "-c envoy.yaml" --debugger lldb` and `tools/vscode/refresh_compdb.sh`.

Then I pressed `F5` to debug.

It kind of works except that I can't see any debug info, such as `frame info` or `print  <variable>`.

<img width="960" alt="image" src="https://github.com/envoyproxy/envoy/assets/27804279/0442abcd-6d86-4b1b-aee4-37d01b3f52e1">

As you see, I can't see any value on the top right corner (Local, Static and Global are all empty) and executing ``p argc` in the debug console gave me the error about "undeclared identifier".

It seems that debugging symbols are missing?

**Comment by KBaichoo** [comment]
cc @phlax as you might have more experience with the devcontainer.

**Comment by phlax** [comment]
i dont use vscode so only from hacking the docker setup

@YvesZHI most debug issues come down to the `.dwp` file not being present **and adjacent** to the envoy binary - could that be the case here?

**Comment by YvesZHI** [comment]
@phlax  Well, it seems that `dwp` files are there.
Here is the `launch.json` which contains debug info.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "lldb //source/exe:envoy-static",
            "program": "/build/.cache/bazel/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/bazel-out/k8-dbg/bin/source/exe/envoy-static",
            "sourceMap": {
                "/proc/self/cwd": "/workspaces/envoy",
                "/proc/self/cwd/external": "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/external",
                "/proc/self/cwd/bazel-out": "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/bazel-out"
            },
            "cwd": "${workspaceFolder}",
            "args": [
                "-c",
                "envoy.yaml"
            ],
            "type": "lldb",
            "request": "launch"
        }
    ]
}
```

In the directory `/build/.cache/bazel/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/bazel-out/k8-dbg/bin/source/exe/`, there are the bin file `envoy-static`, a file `envoy-static.dwp` and a directory `_dwps`, which contains many `.dwp` files.

Besides, in the `.devcontainer/Dockerfile`, I tried to change `ENV ENVOY_STDLIB=libstdc++` to `ENV ENVOY_STDLIB=libc++`, but nothing changed.

**Comment by phlax** [comment]
probably the best thing is to test the officially built bins to see if they work as expected

if you look here:

https://dev.azure.com/cncf/envoy/_build/results?buildId=164418&view=artifacts&pathAsName=false&type=publishedArtifacts

and download `release/x64/bin/release.tar.zst` that has the following files:

```console
dbg/
dbg/envoy
dbg/envoy-contrib
dbg/envoy-contrib.dwp
dbg/envoy.dwp
```

if they work as expected then the issue is with vscode setup, otherwise i guess there is an issue with our build

**Comment by fredyw** [comment]
I have a fix in https://github.com/envoyproxy/envoy/pull/32800. It looks like there's something broken with the DWP generation (`bazel build //source/exe:envoy-static.dwp`)

![image](https://github.com/envoyproxy/envoy/assets/1539871/79af24ed-d719-4f0e-86c8-55d987509f11)
