### ISSUE TITLE
Separate example/sandboxes to their own repo

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#32737]
The examples create a lot of dependency noise in the envoy repo, which apart from being annoying is a constraint on adding more examples.

The reasons for not separating these previously is that we want to keep the CI coupled and that they are used in creation of docs

I think these issues are surmountable. For CI we can pull in the examples repo (at HEAD) and run the ci we currently do in envoy, and in the examples repo we can pull in latest envoy docker image on change. Similarly for docs we can just pull in the examples when we build the docs.

This should be fairly straightforward but will require some bazel, CI and dependabot setup

**Comment by phlax** [comment]
cc @mattklein123 @mmorel-35

**Comment by DavidGoodwin** [comment]
the docs need updating - e.g. https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/setup#clone-the-envoy-repository - is still referencing `.... https://github.com/envoyproxy/envoy.git` and should instead point to  `.... https://github.com/envoyproxy/examples.git`

**Comment by phlax** [comment]
are you up for creating a PR @DavidGoodwin ?

**Comment by DavidGoodwin** [comment]
> are you up for creating a PR @DavidGoodwin ?

I'll try, but if you come back asking me to reword my commits to match something, or something else, I'm going to lose interest.

I'm just trying to scope out envoy for whether it could work for $employer ...
