### ISSUE TITLE
Envoy Retries: Propagate response header to next request

### ISSUE THREAD

**Issue by ankoh** [envoyproxy/envoy#32735]
Hi all, thanks for this amazing project and all your efforts.

We're using Envoy as part of a service mesh (Istio) for a larger database service.
We recently started using Envoy retries to implement load-shedding for cluster subsets (retry + previous host predicate).
So far, we're quite happy with it, but we identified a perfect opportunity to make retries more powerful in general.

**Would you oppose a PR that would copy a certain response header, let's say either `x-envoy-retry-state` or a dynamic one, from the response as header into the next request?**
This would allow services to carry over non-stale information that is relevant to the request to the next node that is picking it up.

We currently cannot implement that ourselves through the filter chain since retries are kept in the router.
I skimmed through the code this morning and got the impression that such a change would only add a few lines around the location where the current `x-envoy-attempt-count` is added (+ tests & setting, of course).
https://github.com/envoyproxy/envoy/blob/cbefd8c84edbf9e39daa6f598619ca41ec486894/source/common/router/router.cc#L700

We'd be very happy to drive such a PR but I thought I'd rather probe the general sentiment towards such a change first.
Thank you!

**Comment by KBaichoo** [comment]
cc @alyssawilk @wbpcode

**Comment by alyssawilk** [comment]
> We currently cannot implement that ourselves through the filter chain since retries are kept in the router.

I think you actually can as long as you use an upstream filter - mind checking those out and seeing if it meets your need?

**Comment by ankoh** [comment]
@alyssawilk Do you mean with a custom filter? We're a bit hesitant to roll our own since we haven't been running custom envoys in our mesh. Does that mean you would rather see that as something similar to the `HeaderMutation` upstream filter instead of baked into the router?

**Comment by alyssawilk** [comment]
yeah making header mutation optionally upstream (if it's not) and adding retry / redirect logic to it seems reasonable.  cc @wbpcode for thoughts
