### ISSUE TITLE
Elevated connection increase when preconnect policy is turned on

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#32753]
*Title*: Elevated connection increase when preconnect policy is turned on

*Description*:
We enabled [preconnect policy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster-preconnectpolicy) by setting `per_upstream_preconnect_ratio=1.05` on a upstream cluster that uses HTTP1.1. We saw huge increase of connection to the upstream cluster:

<img width="1474" alt="image" src="https://github.com/envoyproxy/envoy/assets/6065051/37fc1629-692e-4e42-87e2-7279e690d2d6">

blue: upstream_cx_total (~10 to 80k )
green: upstream_rq_total

*Repro steps*:
- `v1.29.1`

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by alyssawilk** [comment]
Sorry for the long delay.  If I provided a logs patch would you be able to send me results of those extra log lines?

**Comment by milton0825** [comment]
@alyssawilk we are moving away from the preconnect so probably won't be able to test the patch
