### ISSUE TITLE
dynamic direct response

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#32765]
When route's [direct response](https://www.envoyproxy.io/docs/envoy/v1.29.1/api-v3/config/route/v3/route_components.proto.html#config-route-v3-route) is used to read and respond from a file, Envoy reads it during construction of RouteEntry and serves the same. In some cases, we would like it to re-read and return the updated content when file is changed. 

Should we add a new flag, like `dynamic` when set to `true` will reload whenever the route is invoked?

**Comment by ramaraochavali** [comment]
cc: @wbpcode  WDYT?

**Comment by KBaichoo** [comment]
>like dynamic when set to true will reload whenever the route is invoked?

I think we'd want to watch the file for change via inotify vs loaded it on every route invocation which sounds much more expensive.

**Comment by ramaraochavali** [comment]
> I think we'd want to watch the file for change via inotify vs loaded it on every route invocation which sounds much more expensive.

Fair enough. That is even better.
