### ISSUE TITLE
oauth2: on refresh, upstream/request cookies appended rather than replaced

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#32771]
*Title*: *oauth2: upstream/request cookies appended rather than replaced*

*Description*:
In the oauth2 filter, when the token is refreshed with `forward_bearer_token` enabled, the new Cookie header is appended appended rather than replacing the existing cookies. This means that both the old (likely expired) BearerToken cookie and the new, refreshed BearerToken cookie will be present. This is debatably in violation of [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.4), which says

>    When the user agent generates an HTTP request, the user agent MUST
>    NOT attach more than one Cookie header field.

I say "debatably" because the spec specifies user agent and you could argue that Envoy is not operating as a user agent in this scenario. However, upstreams may be relying on this behavior and may have things like anti-request-smuggling behavior that will reject duplicate cookie headers - in fact, Envoy itself would only take the first header, which in this case would be the old (non-refreshed token).

*Repro steps*:
The simplest way is to enable `forward_bearer_token`, enable `use_refresh_token`, (disable `reloadable_features.oauth_use_standard_max_age_value` to work around https://github.com/envoyproxy/envoy/issues/30053), and view the upstream headers

**Comment by KBaichoo** [comment]
cc @Alexcei88 who added refresh token support in https://github.com/envoyproxy/envoy/pull/24684

**Comment by Alexcei88** [comment]
It's very strange, because I don't see the problem in the code.

**Comment by bplotnick** [comment]
@Alexcei88 I already have a fix PR out, let me know what you think: https://github.com/envoyproxy/envoy/issues/32771
