### ISSUE TITLE
" not found in config dump" when clicking from the admin UI

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#32794]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: " not found in config dump" when clicking from the admin UI
*Description*:
If you click the configdump button in the UI you get sent to `/config_dump?resource=&mask=&name_regex=`.
This always displays `not found in config dump`.

Either it should not set the query params, or empty query params should be treated the same as unset I think

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by nezdolik** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
Yes I've noticed this too. I'm pretty sure this worked a while ago and was a regression.

**Comment by jmarantz** [comment]
as a workaround you can hand-edit the query-params in the browser url-bar to erase them and get the default /config_dump behavior.

**Comment by jmarantz** [comment]
@ggreenway 

Trying to assign to @turettn but apparently not part of the org.

**Comment by turettn** [comment]
I just got an e-mail: `"phlax" added you to the "Envoy Proxy - CNCF" team "assignable"`

Maybe try to assign me again?

**Comment by jmarantz** [comment]
worked. thanks @phlax
