### ISSUE TITLE
Errors and success in response_flags: DC

### ISSUE THREAD

**Issue by erickbitso** [envoyproxy/envoy#32797]
*Title*: *My server shows some traces with response_flags:DC, some of them are marked as errors and some of them are successful*

*Description*:
I'm using Istio so perhaps this is an istio specific problem and not an envoy one, still I thought to ask here. Our envoy proxy traces show that sometimes we get some requests with response_flags:DC, I'm aware as per the documentation that these are downstream disconnections. However what I don't understand is why some of them are marked as an error where as some others are marked as successful, they even have a 200 status response. 

Questions:
- What is the reason for this?
- Under which circumstances does a response_flags:DC request can be successful and in which cases can it be marked as an error?

```
# Span tags of a failed request with response_flags:DC (no HTTP status code)

{
	component: proxy
	error: true
	downstream_cluster: -
	request_size: 0
	response_flags: DC
	response_size: 0
	span {
		kind: server
	}

}

# Span tags of a successful request with response_flags:DC

{
	component: proxy
	downstream_cluster: -
	request_sizd: 0
	response_flags: DC
	response_size: 238257
	span {
		kind: client
	}
}
```

I see many requests from Android clients with response_flags:DC marked as an error and AFAIK (please correct me if I'm wrong) these disconnections are normal, so them being marked as errors affect our SLOs. I wonder if the Android client close the sockets gracefully would it not be marked as an error in envoy? So is it considered best practice to manage client disconnections in the HTTP client?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by nezdolik** [comment]
@erickbitso please check with istio first, is hard to tell from this config which Envoy tracing extension you are using

**Comment by erickbitso** [comment]
Sure, I can do that but the extension I'm using is Tracing.Datadog

**Comment by nezdolik** [comment]
cc @cgilmour @dgoffredo @dmehala as Datadog tracer extension owners.

**Comment by dgoffredo** [comment]
This might be related to the bug addressed in https://github.com/envoyproxy/envoy/pull/31669. The crux of the issue is a mismatch between how Envoy marks spans as errors and how Datadog marks spans as errors. The correspondence was broken by changes that I made, but the correspondence is restored in the linked pull request. The change was backported onto the [v1.27][1] and [v1.28][2] release branches. The backports were likely not yet consumed by Istio; to get the fix, upgrade Istio to its latest minor version, if possible.

[1]: https://github.com/envoyproxy/envoy/pull/31703
[2]: https://github.com/envoyproxy/envoy/pull/31704

**Comment by dgoffredo** [comment]
To determine whether a given Istio version contains the fix, you can use a tool that I wrote: https://github.com/dgoffredo/fetch-istio-envoy

You're looking for [special `if` statements][1] in `Span::setTag` that handle the "error" tags.

For example, [Istio 1.20.3][2] contains the fix:
```console
david@ein:~/src/fetch-istio-envoy$ bin/fetch-istio-envoy 1.20.3
/tmp/tmp.w7wQFP9Wtr
david@ein:~/src/fetch-istio-envoy$ grep -A 3 -B 3 'error\.reason' /tmp/tmp.w7wQFP9Wtr/envoy-file
      span_->set_error(true);
    }
  } else if (name == Tags.ErrorReason) {
    // Envoy conveys information about an error by setting the "error.reason"
    // tag.
    // Here we translate into the dd-trace-cpp equivalent.
    span_->set_error_message(value);
david@ein:~/src/fetch-istio-envoy$
```
As does Istio 1.19.7:
```console
david@ein:~/src/fetch-istio-envoy$ bin/fetch-istio-envoy 1.19.7
/tmp/tmp.BVtbWslIUH
david@ein:~/src/fetch-istio-envoy$ grep -A 3 -B 3 'error\.reason' /tmp/tmp.BVtbWslIUH/envoy-file
      span_->set_error(true);
    }
  } else if (name == Tags.ErrorReason) {
    // Envoy conveys information about an error by setting the "error.reason"
    // tag.
    // Here we translate into the dd-trace-cpp equivalent.
    span_->set_error_message(value);
david@ein:~/src/fetch-istio-envoy$ 
```
But not Istio 1.18.7:
```console
david@ein:~/src/fetch-istio-envoy$ bin/fetch-istio-envoy 1.18.7
/tmp/tmp.3aNx61SXOQ
david@ein:~/src/fetch-istio-envoy$ grep -A 3 -B 3 'error\.reason' /tmp/tmp.3aNx61SXOQ/envoy-file
david@ein:~/src/fetch-istio-envoy$ 
```

[1]: https://github.com/envoyproxy/envoy/blob/3c84a245c056ae5bd74309d766091f33d9190071/source/extensions/tracers/datadog/span.cc#L65-L77
[2]: https://github.com/istio/istio/releases/tag/1.20.3

**Comment by erickbitso** [comment]
Ah, much appreciated @dgoffredo , I am actually in the process of upgrading istio so I will report back soon!
