### ISSUE TITLE
ECDS: support request pausing to avoid spammy XDS reuqests

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#32795]
*Title*: ECDS: support request pausing to avoid spammy XDS reuqests
*Description*:
Most types have a 'pause' to pile up requests for subresources and avoid doing N requests for N resources. This seems missing for ECDS

This could be as simple as https://github.com/envoyproxy/envoy/blob/da1a7d2ed07c6c60e7e0b05430337465ed91a03e/source/common/listener_manager/lds_api.cc#L50-L53 adding ECDS here

cc @zirain @kyessenov 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by nezdolik** [comment]
cc @adisuissa

**Comment by adisuissa** [comment]
I think it is possible to add, just need to know which "parent" types need to pause them (I'm aware of RDS and LDS, but I guess there are other types that may need that).

FWIW this works only for ADS, which I think Istio uses to fetch ECDS resources, but should double check your use-case.
