### ISSUE TITLE
How to build from github

### ISSUE THREAD

**Issue by Karthikdasari0423** [envoyproxy/envoy#32808]
*Title*: *How to build envoy from github*

*Description*:
I don't see any documentation to build envoy from github

Can someone please help me to build envoy from github(by cloning repo)
I am using Ubuntu 22.

**Comment by nezdolik** [comment]
@Karthikdasari0423 please take a look at this guide: https://www.envoyproxy.io/docs/envoy/latest/start/building/local_docker_build
