### ISSUE TITLE
golang-http-filter：an unknown error

### ISSUE THREAD

**Issue by Hectorsong** [envoyproxy/envoy#32806]
Hello, this error occurs when I use the following shell command to compile the go plugin library, I use the code from the Main branch and the envoy-release-v1.29 branch.

Shell command: 
docker-compose -f docker-compose-go.yaml run --rm go_plugin_compile

Errors:
[root@MiWiFi-RA81-srv golang-http]# docker-compose -f docker-compose-go.yaml run --rm go_plugin_compile
[+] Building 0.0s (0/0)                                                                                                  
[+] Building 0.0s (0/0)                                                                                                  
  #   github.com/envoyproxy/envoy/contrib/golang/common/go/api_impl
In file included from vendor/github.com/envoyproxy/envoy/contrib/golang/common/go/api_impl/capi_impl.go:30:
vendor/github.com/envoyproxy/envoy/contrib/golang/common/go/api_impl/api.h:1:1: error: expected identifier or '(' before '.' token
    1 | ../api/api.h
      | ^
cgo-gcc-prolog: In function '_cgo_fdb86200d1f7_Cfunc_envoyGoFilterLog':
cgo-gcc-prolog:46:3: error: unknown type name 'uint32_t'
cgo-gcc-prolog:53:2: warning: implicit declaration of function 'envoyGoFilterLog' [-Wimplicit-function-declaration]
cgo-gcc-prolog: In function '_cgo_fdb86200d1f7_Cfunc_envoyGoFilterLogLevel':
cgo-gcc-prolog:62:3: error: unknown type name 'uint32_t'
cgo-gcc-prolog:68:11: warning: implicit declaration of function 'envoyGoFilterLogLevel' [-Wimplicit-function-declaration]

**Comment by doujiang24** [comment]
> In file included from vendor/github.com/envoyproxy/envoy/contrib/golang/common/go/api_impl/capi_impl.go:30:

The `vendor` path looks unexpected, do you have vendor in your local side?
Please remove it and have another try.

**Comment by Hectorsong** [comment]
It seems that the relative path in vendor was invalid, such as 
(1)"../../../../../../common/go/api/api.h" in file "./vendor/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http/api.h",  
(2) "../api/api.h" in file "./vendor/github.com/envoyproxy/envoy/contrib/golang/common/go/api_impl/api.h"

Then, I copied the file "./vendor/github.com/envoyproxy/envoy/contrib/golang/common/go/api/api.h" to the above two paths, and the problem was solved. 

Thanks a lot!
