### ISSUE TITLE
OAuth2 filter: supports forwarding ID tokens to upstream web service via the Authorization header bearer scheme

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#32805]
*Title*: *OAuth2 filter: supports forwarding ID tokens to upstream web service via the Authorization header bearer scheme*

*Description*:
OAuth2 filter has a `forward_bearer_token` configuration knob. If enabled, it forwards access tokens to the upstream web service via the Authorization header bearer scheme. Could we also add a knob to forward ID tokens via the Authorization header?  This would allow the JWT filter or applications to utilize ID tokens for JWT-based authentication or other authorization purposes. 

Related discussion in Envoy Gateway: https://github.com/envoyproxy/gateway/discussions/2425#discussioncomment-8722381

**Comment by nezdolik** [comment]
cc @lizan @mattklein123 @derekargueta

**Comment by zvlb** [comment]
I think this issue can help me with my case.

I want save Authorization Header from request. But if `forward_bearer_token=false` Authorization Header deleted from requests(

**Comment by evilr00t** [comment]
👀 Hi guys, any update on this one?

**Comment by derekargueta** [comment]
@nezdolik can we nostale this? On my radar, wrapping up https://github.com/envoyproxy/envoy/issues/2098 first

**Comment by johnvox** [comment]
Reopen. I have a usecase for example I want the IDToken Retreived by envoy forard to an application that do validation over the IDToken (not AccessToken) (ArgoCD).
With this ArgoCD will get automatically claims to validate RBAC
