### ISSUE TITLE
Route matches on headers match on envoy-added headers

### ISSUE THREAD

**Issue by frankh** [envoyproxy/envoy#32817]
*Title*: *Route matches on headers match on envoy-added headers*

*Description*:
I have the following route match
```
"routes": [
            {
              "match": {
                "prefix": "/path",
                "headers": [
                  {
                    "name": "x-forwarded-for",
                    "present_match": true
                  }
                ]
              },
```
This match is true for every request to /path, not just those with `X-Forwarded-For` set, because envoy itself sets the X-Forwarded-For header

I feel like envoy should be checking this header before adding/modifying it itself

*Repro steps*:
Include a header match for any header than envoy adds/modifies itself, e.g.
```
{
  "name": "x-forwarded-for",
  "present_match": true
}
```

**Comment by nezdolik** [comment]
cc @alyssawilk @mattklein123
