### ISSUE TITLE
It is possible to change the response_type  of OAUTH2 authorization request?

### ISSUE THREAD

**Issue by jean13360** [envoyproxy/envoy#32816]
Hi ,

I use the envoy 1.29-latest and OAUTH2 extension type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
And i see in the HTTP call that envoy always send response_type=code

It's normal ? ans it's possible to change this value ?

Thx

**Comment by nezdolik** [comment]
Hi @jean13360, could you provide more detail about the desired behavior?

**Comment by jean13360** [comment]
Yes

Normally with Oauth2 , when you do an authorization , one parametes is response_type . 
This parameters tells the authorization server which grant to execute (https://auth0.com/docs/authenticate/protocols/oauth).

And this parameters can have multiple value like response_type=id_token token

It's possible to change the parameters response_type in envoy during the authorization phase ? 

Thx

**Comment by derekargueta** [comment]
Basically the Authorization Code grant is the only supported flow (well also refresh technically), it's hard-coded in here:
https://github.com/envoyproxy/envoy/blob/b47fc6648d7c2dfe0093a601d44cb704b7bad382/source/extensions/filters/http/oauth2/filter.cc#L138


we could look into supporting the Implicit grant flow (`id_token` and `token`). It's considered less secure than Authorization Flow but if it's the desired configuration we should be able to support it.

**Comment by derekargueta** [comment]
We can repurpose this ticket to "Support OAuth 2.0 Implicit Grant"?

**Comment by derekargueta** [comment]
worth noting `response_type=token` is deprecated[1] and being removed in the new OAuth 2.1 spec [2].

[1] https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-24#name-implicit-grant
[2] https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-10#name-removal-of-the-oauth-20-imp
