### ISSUE TITLE
GCP Authentication Filter should be able to support dynamic audience provided at request time

### ISSUE THREAD

**Issue by neilalberg** [envoyproxy/envoy#32831]
*Title*: GCP Authentication Filter should be able to support dynamic audience provided at request time

*Description*:
Currently, the gcp_authn filter generates JWT tokens with the audience provided by the Cluster metadata of the destination service. Cluster metadata is static and cannot be changed after Envoy startup. 

I am working on a GCP feature which uses a dynamic forward proxy to forward traffic to GCP service destinations. However, gcp_authn cannot be used with a dynamic forward proxy cluster as the audience cannot be set on the dynamic forward proxy cluster when not all service destinations are known ahead of time. 

I am proposing the following options to address this:

- Add an optional string field to the gcp_authn filter to specify the audience, which supports format specification to read dynamic values from request headers and/or dynamic metadata

- Add an optional string field to the gcp_authn filter to specify a request header to use as the audience

- Add an optional field to the gcp_authn filter which specifies that the Host/:authority request header should be used as the audience

I'm happy to make the appropriate code changes needed to support this and appreciate any feedback.

*Relevant Links*:
gcp_authn docs:
https://github.com/envoyproxy/envoy/blob/v1.29.2/docs/root/configuration/http/http_filters/gcp_authn_filter.rst

The gcp_authn.proto that I am proposing changes to:
https://github.com/envoyproxy/envoy/blob/v1.29.2/api/envoy/extensions/filters/http/gcp_authn/v3/gcp_authn.proto#L24

Where the audience field is read by the gcp_authn filter:
https://github.com/envoyproxy/envoy/blob/v1.29.2/source/extensions/filters/http/gcp_authn/gcp_authn_filter.cc#L50

**Comment by tyxia** [comment]
Hi Neil, the proposed change make sense to me. It was designed to be static by intention as we don't have dynamic use case at that moment. 
Actually I did scope this as one of future work in the doc I shared with you internally.
