### ISSUE TITLE
Where could i configure max_response_headers_kb 

### ISSUE THREAD

**Issue by zhanghaohao** [envoyproxy/envoy#32862]
*Title*: *Where could i configure max_response_headers_kb*

*Description*:
I met an issue when using envoy gateway as proxy for my backend service.
When i make a request, my backend service will respond envoy with a **big header** (over 100KB), and envoy throws out an error:

`Error dispatching received data: http/1.1 protocol error: headers size exceeds limit`

I researched and found that **max_response_headers_kb** is the param that i need to configure.
But i could not find any document on how to configure this param in envoy (or EnvoyPatchPolicy).
Would you please provide any help here ?

*Issue Link*:
https://github.com/envoyproxy/envoy/issues/5810
https://github.com/envoyproxy/envoy/issues/5626

**Comment by nezdolik** [comment]
cc @alyssawilk @mattklein123

**Comment by alyssawilk** [comment]
I don't think it was ever implemented.  Previously I think there were limits imposed by the codec but after switching over to balsa I think we could implement this feature

**Comment by zhanghaohao** [comment]
@alyssawilk i am trying to update MAX_RESPONSE_HEADERS_KB in source/common/http/http1/codec_impl.h to a larger number (e.g. **3000**). 
And then i compile a new envoy image by leveraging Bazel. 
Do you think this image could work ?

**Comment by bencebeky** [comment]
Yes, that looks right to me. This compile-time parameter predates me, and is obeyed by BalsaParser and http-parser alike.
