### ISSUE TITLE
feature proposal: Reset downstream connection as overload action

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#32900]
*Title*: *One line description*

### Description
 In our deployment, Envoy is used as a multitenancy tcp proxy  that 
* majority of the peers are fast. 
   The downstream connection and upstream connection do not trigger flow control. Bytes could be written to the wire on both directions.
* A few downstream or upstream workload could be really slow.
   As the reason is not a transient link saturation, the flow control is not expected to recover soon.

We tried to limit memory usage by setting [per_connection_buffer_limit](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-per-connection-buffer-limit-bytes), however, it is proved to me not working well because there is no best value to reach throughput (when not throttled) and flow controlled. 

We also tried setting the downstream connection limit, but the number of benigned connections are usually huge. 

For the same reason, stop accepting connections largely impact the benigned connections instead of the connections under flow control.

###  Proposal

In this scenario, reset the connections that are using high memory is the preference.

Although indepedent filters could maintain buffers implicitly, and upstream/downstream connection peers (not even 1:1 when a H2 tunnel chimes in), 
I find tracking the read_buffer and write_buffer within the downstream connection are effective.

When the connections are under active flow control due to either slow downstream or slow upstream,
the corresponding read_buffer or write_buffer was likely accumulated.

There might be concerns about resetting spiking connections, however, it's always less damaging than an Envoy crash due to container OOM.

###  Implementation

I had a version adding a buffer account within TcpProxyFilter, and plumb the account to downstream connection buffer.
TcpProxy provide a callback of `ResetStream` which merely close the downstream connection. 
However, when I write this, I realize the filter chain or connection itself is probably an alternative owner of the account.

The details of buffer account can be found in the existing [reset-stream](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#reset-streams) 
overload action which applies to h2 stream instead of downstream connection.

**Comment by nezdolik** [comment]
cc @KBaichoo @nezdolik :)

**Comment by KBaichoo** [comment]
This sounds reasonable to add drop-connection for tcp proxy usecase based on buffer accounting.

For the connections that get dropped, any concerns about whether they'd be able to ever complete your workflow? e.g lets say the issue is you're downloading a large file but the client is just permanently slow but between the proxy and the upstream is very fast. If your buffer size to the upstream is very permissive then we can accumulate bytes in the proxy, trigger a reset and often fail for this client due to their slow drain speed.

**Comment by lambdai** [comment]
I think that's a valid concern. 
Only from the dimension of buffer balance, we cannot distinguish spiking buffer usage with the a freezing connection.
@dastbe also raised the concern if reset never resolve the issue.

To some extend this action is probably reasonable when the heap is jeopardizing the envoy prcoess, 
where OOM killer is about to kick off.

I can imagine this action should be combined with high fixed_heap threshold, 
and maybe replaced if a disk cache filter can be introduced.  But resetting the noisy connection is probably the 
of the available actions if not the only one.
