### ISSUE TITLE
When is `ConnectionManagerImpl` destroyed

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#32903]
I'm learning about metrics of Envoy and I just found `downstream_cx_destroy`. I don't understand what it means.

It seems that it will be increased when the destructor of `ConnectionManagerImpl` is called.

The class `ConnectionManagerImpl` is to manage some http connections as its name implies. But I don't know when its desctructor will be called.

**Comment by lambdai** [comment]
The HTTP ConnectionManagerImpl is network filter for http1 and http2 traffic.
You can imagine this filter  created after a connection is accepted by Envoy and destroyed after the downstream connection is closed.

ConnectionManager manages multiple http requests that are either pipelined or multiplexed in the same connection
