### ISSUE TITLE
redis: add support for stream commands (xread, xadd etc)

### ISSUE THREAD

**Issue by danielnorberg** [envoyproxy/envoy#32928]
*Title*: Redis stream command support

*Description*:
Envoy should proxy [stream commands](https://redis.io/commands/?group=stream) instead of responding "unsupported command".

This would be useful when utilizing redis streams via an envoy proxy.

Most of the stream commands only take a single key and can be trivially routed to the appropriate shard.

Some stream commands (e.g. `XREAD` and `XREADGROUP`) take multiple keys. A reasonable behavior could be to route the entire command to the shard corresponding to the first key in the arguments. Cluster-mode redis instances will reject commands where not all keys map to the same shard. However, non-cluster mode redis instances (sharded over by envoy) would not reject such commands. To catch this case envoy itself would need to verify that all keys of the command shard to the same instance.

*Relevant Links*:
* Redis Streams: https://redis.io/docs/data-types/streams/
* Stream commands: https://redis.io/commands/?group=stream

**Comment by nezdolik** [comment]
cc @msukalski @weisisea
