### ISSUE TITLE
Add Lua APIs to access downstream TLS session info

### ISSUE THREAD

**Issue by skssfo** [envoyproxy/envoy#3296]
*Description*:
Allow Lua script to access downstream TLS session info and add them as header information on the requests going upstream.
Some of the info that are of interest to the upstream services are (using the mod_ssl terminology here - https://httpd.apache.org/docs/2.4/mod/mod_ssl.html) :

SSL_PROTOCOL, SSL_SESSION_ID, SSL_CIPHER, SSL_CIPHER_USEKEYSIZE

I posted this earlier in the envoy-users group and got a suggestion to raise an enhancement request. 
https://groups.google.com/forum/#!topic/envoy-users/MuQH6SAqL7I

**Comment by daurnimator** [comment]
As a general solution, could the `SSL*` pointer be exposed to lua so that existing OpenSSL/BoringSSL libraries (e.g. https://github.com/wahern/luaossl/) can be used to inspect the structure?

**Comment by mikegrass** [comment]
I'm looking at implementing support in envoy for this -- it looks like a good starting point. My initial impression is that having this information exposed via the LUA API would be nice, but in many cases it is more convenient to expose this as custom request headers (https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/http_conn_man/headers#config-http-conn-man-headers-custom-request-headers), and to have variable names that are available for access logs available for request headers as well.

https://github.com/envoyproxy/envoy/pull/1708 already set precedent here for exposing file access log variables as dynamic request header variables.
https://github.com/envoyproxy/envoy/pull/6144 exposed (some) downstream TLS session information as variables for file access logs.

I'm looking for feedback on whether continuing these trends by exposing more downstream TLS session information to both access logs and dynamic request header variables is the right path. Notably, as envoy continues to pick up steam as a preferred front proxy over, e.g., nginx,  having support for variables similar to what nginx provides (http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables) seems like a win.

In short, I'd like to pick up this issue and potentially expand the scope of it to exposing dynamic variables about the downstream tls connection for access logging and upstream request header injection.

Thoughts?

Here's a rough roadmap outlining how I'm thinking of making progress on this:

- [ ] Add accessors for more TLS session information to the [`Envoy::Ssl::ConnectionInfo`](https://github.com/envoyproxy/envoy/blob/5e5b65ee40fb35ef4f64aceebd67978a318d65f9/include/envoy/ssl/connection.h) base class and concrete implementations in the [`Envoy::Extensions::TransportSockets::Tls::SslSocket`](https://github.com/envoyproxy/envoy/blob/5e5b65ee40fb35ef4f64aceebd67978a318d65f9/source/extensions/transport_sockets/tls/ssl_socket.h#L42) classes.
- [ ] Extend [`Envoy::AccessLog::StreamInfoFormatter`](https://github.com/envoyproxy/envoy/blob/5e5b65ee40fb35ef4f64aceebd67978a318d65f9/source/common/access_log/access_log_formatter.cc#L279) to expose more downstream TLS session information as dynamic variables for access logging.
- [ ] Extend [`Envoy::Extensions::AccessLoggers::HttpGrpc`](https://github.com/envoyproxy/envoy/blob/5e5b65ee40fb35ef4f64aceebd67978a318d65f9/source/extensions/access_loggers/http_grpc/grpc_access_log_impl.cc#L202-L220) to include additional downstream TLS session information.
- [ ] Extend [`Envoy::Router::StreamInfoHeaderFormatter`](https://github.com/envoyproxy/envoy/blob/814dd9facff27391a42744309f7765dc94971e40/source/common/router/header_formatter.cc#L167) to support the same downstream TLS session information variables as done for access logs.
- [ ] Complete the [current `TODO`](https://github.com/envoyproxy/envoy/blob/65c05cad96db7f7874e1e5a2b70829dcfad10e88/source/extensions/filters/common/lua/wrappers.h#L115) in [`Envoy::Extensions::Filters::Common::Lua::SslConnectionWrapper`](https://github.com/envoyproxy/envoy/blob/65c05cad96db7f7874e1e5a2b70829dcfad10e88/source/extensions/filters/common/lua/wrappers.h#L108) to expose common additional TLS session information to the LUA API.
- [ ] Optionally, as @daurnimator suggested, expose the raw `const SSL*` to the LUA API so it is accessible to LUA modules.
- [ ] In parallel, tests for the above.

Variables that, in the short term, I would prioritize implementing include:

| Envoy Variable Name | Nginx Analog | Description |
|----------------------------------|----------------------|---------------------------------------------------------------------------------------|
| `%DOWNSTREAM_TLS_SESSION_ID%` | `$ssl_session_id` | returns the session identifier of an established TLS connection |
| `%DOWNSTREAM_TLS_CIPHER%` | `$ssl_cipher` | returns the standard IETF name for the set of ciphers used in the established TLS connection |
| `%DOWNSTREAM_TLS_PROTOCOL%` | `$ssl_protocol` | returns the protocol (e.g., TLSv1.2, TLSv1.3) used in the established TLS connection |
| `%DOWNSTREAM_PEER_FINGERPRINT_256%` | `$ssl_client_fingerprint` | returns the hex-encoded SHA256 fingerprint of the client certificate for an established TLS connection |
| `%DOWNSTREAM_PEER_SERIAL%` | `$ssl_client_serial` | returns the serial number of the client certificate for an established TLS connection |
| `%DOWNSTREAM_PEER_ISSUER%` | `$ssl_client_i_dn` | returns the "issuer DN" string of the client certificate for an established TLS connection according to RFC 2253 |
| `%DOWNSTREAM_PEER_SUBJECT%` | `$ssl_client_s_dn` | returns the "subject DN" string of the client certificate for an established TLS connection according to RFC 2253 |
| `%DOWNSTREAM_PEER_CERT%` | `$ssl_client_escaped_cert` | returns the client certificate in the PEM format (urlencoded) for an established TLS connection |
| `%DOWNSTREAM_PEER_CERT_V_START%` | `$ssl_client_v_start` | returns the start date of the client certificate |
| `%DOWNSTREAM_PEER_CERT_V_END%` | `$ssl_client_v_end` | returns the end date of the client certificate |
| `%DOWNSTREAM_PEER_CERT_V_REMAIN%` | `$ssl_client_v_remain` | returns the number of days until the client certificate expires |

**Comment by mattklein123** [comment]
At a high level this seems reasonable to me, though there is some overlap with `x-forwarded-client-cert` that I think needs to be reconciled so we don't duplicate information. @PiotrSikora any thoughts here?

**Comment by abhishek-jain11** [comment]
Hi
I am trying to access issuer certificate in LUA filter. Can anyone please help me on how to do it?

**Comment by Kalimero66** [comment]
+1... Any progress on this topic. I need to access downstream cipher suites and pass that info as a header to upstream. Would be great to have a pointer to some doc/examples.

**Comment by mattklein123** [comment]
I believe this was done
