### ISSUE TITLE
gRPC async client uses cluster name as authority

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#3297]
We found that google gRPC async client uses the cluster name as the authority header. That triggers an obscure error in nghttp2 if the cluster happens to use a non-valid character (as defined by https://github.com/nghttp2/nghttp2/blob/842509dab604e6cc62f7fb98d448294c6ec85763/lib/nghttp2_http.c#L307). We should either restrict cluster name to legit h2 authority, or use some other authority value.

**Comment by kyessenov** [comment]
cc @qiwzhang @lizan

**Comment by kyessenov** [comment]
Funky things happen if you use legit host header according to nghttp2 (e.g. `a~b`) but that does not match `*` wildcard. Apparently, `*` does not capture `a~b`.

**Comment by mandarjog** [comment]
For reference the [istio issue](https://github.com/istio/istio/issues/5331#issuecomment-386751524) that encountered this problem.

**Comment by mattklein123** [comment]
I'm going to close this out for now. Let's reopen a feature request if we want a way to override this behavior.
