### ISSUE TITLE
[docs] v1.29.2 changelog not available on `latest` tagged version of site

### ISSUE THREAD

**Issue by jbohanon** [envoyproxy/envoy#32974]
*Title*: [docs] v1.29.2 changelog not available on `latest` tagged version of site

*Description*:
The changelog for 1.29.2 are not available in the latest tagged version of the docs site ([link](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.29/v1.29.2)), but is available for the v1.29.2 tagged version of the site ([link](https://www.envoyproxy.io/docs/envoy/v1.29.2/version_history/v1.29/v1.29.2)). This is a bit misleading/just odd since the latest tagged release in GH is v1.29.2.

**Comment by phlax** [comment]
i can update this now
