### ISSUE TITLE
Use `BAZEL_BUILD_EXTRA_OPTIONS` to setup Bazel remote cache

### ISSUE THREAD

**Issue by Winbobob** [envoyproxy/envoy#32989]
## Title
Use `BAZEL_BUILD_EXTRA_OPTIONS` to setup Bazel remote cache

## Description
The [example command](https://github.com/envoyproxy/envoy/blob/main/ci/README.md#:~:text=./ci/run_envoy_docker.sh%20%22BAZEL_BUILD_EXTRA_OPTIONS%3D%27%2D%2Dremote_cache%3Dhttp%3A//127.0.0.1%3A28080%27%20./ci/do_ci.sh%20release%22) mentioned in this README does not work well when you need to specify the header for remote cache.

This is because both `basic` and `bearer` AuthN schemes need the quotes to group the content and use quotes here can be tricky. Especially there are already [two layers of quotes](https://github.com/envoyproxy/envoy/blob/main/ci/run_envoy_docker.sh#L63) with in `./ci/run_envoy_docker.sh`.

## Proposal
Update this README:
- for simply Bazel remote cache options, especially without quotes, we use the `BAZEL_BUILD_EXTRA_OPTIONS` env variables.
- for complex Bazel remote cache options, especially with quotes, we add/append the options to the `user.bazelrc` files.

**Comment by htuch** [comment]
@phlax

**Comment by phlax** [comment]
@Winbobob sgtm

we have been gradually shifting configs into `.bazelrc` and away from env vars or cli flags for the reasons you point out and many others also

are you up for raising a PR to adjust the dev docs?

the readme you linked is pretty hopelessly out of date - its on my agenda to do some work on dev docs - but for now i think its the best place (for ref there is also bazel/README amongst others)

**Comment by Winbobob** [comment]
Cool, thank you for the confirmation! I can create the PR.

**Comment by moderation** [comment]
After a couple of years of enjoying the Google RBE, my builds now download GBs of `*.dwo` files and the builds are now super slow and serial. 
![image](https://github.com/envoyproxy/envoy/assets/246317/244181cd-a3ab-4d91-b618-71d410d89f3f)
I'm guessing my `~/.bazelrc` is out of date but haven't been able to work out the right commands

**Comment by phlax** [comment]
@moderation the easiest way to use RBE ive found is to place just the credentials in `user.bazelrc` - ie:

```bazelrc
build --google_credentials=./gcloud.token
```

and then after doing `export ENVOY_RBE=1` use the `ci/do_ci.sh` targets

this is the closest to what ci is doing

using bazel directly you want something like:

```bazelrc
build --remote_instance_name=projects/envoy-ci/instances/default_instance
build --remote_cache=grpcs://remotebuildexecution.googleapis.com
build --remote_executor=grpcs://remotebuildexecution.googleapis.com
build --jobs=40
```

depending on the toolchain you want you probably also need something like:

```bazelrc
build --config=rbe-toolchain-clang-libc++
```
