### ISSUE TITLE
503 no healthy upstream error

### ISSUE THREAD

**Issue by ritesh58** [envoyproxy/envoy#33000]
Hi Team,
 
We need an urgent help. We are getting 503 no healthy upstream error intermittently from istio gateway. Seeing your release note which has the same bug stated fixed in envoy version which comes with istio version 1.21 , we upgraded the istio to latest version but the error is still here. Our whole infrastructure is impacted by it. Help will be greatly appreciated.
 
We use Azure Kubernetes.

one Error from istio-proxy also pasted in the comments
![erroristio](https://github.com/envoyproxy/envoy/assets/3917151/d6c1c278-13bf-4e8c-bd6d-b1f744983404)

**Comment by ritesh58** [comment]
![erroristio](https://github.com/envoyproxy/envoy/assets/3917151/fafd167d-2a69-4968-ba58-e4c421dd16fc)

**Comment by htuch** [comment]
There's really not enough information here to be able to triage or debug this.
