### ISSUE TITLE
How to accurately measure processing latency?

### ISSUE THREAD

**Issue by ldb** [envoyproxy/envoy#33001]
*Description*:

I am trying to measure processing latency introduced by envoy. Specifically the overhead of filter chains, primarily on the request but also on the response path. Depending on what filters are used, e.g external-authorization, JWT authentication, requests could be delayed by quite a bit and this is essentially the time I am trying to measure.

Access Logs give us the following numbers already:

- `%DURATION%` Total duration in milliseconds of the request from the start time to the last byte out.
- `%REQUEST_DURATION%` Total duration in milliseconds of the request from the start time to the last byte of the request received from the downstream.
- `%REQUEST_TX_DURATION%` Total duration in milliseconds of the request from the start time to the last byte sent upstream.
- `%RESPONSE_DURATION%` Total duration in milliseconds of the request from the start time to the first byte read from the upstream host.
- `%RESPONSE_TX_DURATION%` Total duration in milliseconds of the request from the first byte read from the upstream host to the last byte sent downstream.
- `%ROUNDTRIP_DURATION%` Total duration in milliseconds of the request from the start time to receiving the final ack from the downstream.

What I am missing is a `REQUEST_PROCESSING_DURATION` that measures the time from start time to first byte out to the upstream.

Preferrably the same also exists for the response, i.e `RESPONSE_PROCESSING_DURATION` that measures between the first byte in from upstream to first byte out to downstream.

These numbers added would make up the roundtrip latency introduced just by request processing and would help very much in benchmarking filters.

Another question: Is there a way to get these numbers exposed as metrics, ideally with upstream cluster annotations?

[Envoy Access Log Documentation](https://www.envoyproxy.io/docs/envoy/v1.29.0/configuration/observability/access_log/usage.html)

**Comment by htuch** [comment]
@wbpcode @zuercher @eziskind

**Comment by wbpcode** [comment]
SGTM. Maybe we can add a %REQUEST_FULL_TX_DURATION% to record that.

**Comment by ldb** [comment]
> Maybe we can add a %REQUEST_HEADER_TX_DURATION% to record that.

That would be a good start, but does not quite capture my use case, because yes, body processing also needs to be taken into account.

> But I think the exist %REQUEST_TX_DURATION% are more appropriate for your requirement.

It does not, unfortunately, because what I want to know is the delta between start time (first byte in) and starting to send the request upstream (first byte out upstream).

Now that I think about it, there could also be some response processing involved, so there also could also be a measurement between first byte in from upstream and first byte out to downstream.

For now, `REQUEST_PROCESSING_DURATION` is the thing I am mostly interested in, as we do most processing on the request side.

![Screenshot 2024-03-26 at 12 29 54](https://github.com/envoyproxy/envoy/assets/10501668/527c8182-7db3-4dff-9657-37e0bcc28c92)

**Comment by akashjain971** [comment]
Does newly introduced `COMMON_DURATION` should solve your usecase?
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators
