### ISSUE TITLE
Can we pass data volume to ext_authz

### ISSUE THREAD

**Issue by joelmathew003** [envoyproxy/envoy#33029]
*Title*: *Is it possible to send bytes sent/received through `ext_authz`*

*Description*:
I want my external authorization to receive information about bytes sent/received to make a decision. Is there some way to do this in `envoy.filters.http.ext_authz` and `envoy.filters.network.ext_authz`? Or any workaround that may help? I see that we may be able to work around this by adding additional headers with the needed info using the http lua filter, but don't see anything similar in network filter.

**Comment by htuch** [comment]
Authorization decision have to be made on the earliest bytes in the request headers or the request body. See https://github.com/envoyproxy/envoy/blob/3717be0b78a9b9601eddfc912db42cb30ead9094/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L74 for how to include request body. If you want to inspect further, consider using ext_proc.
