### ISSUE TITLE
Add variant to SchemeHeaderTransformation to set scheme based on upstream transport

### ISSUE THREAD

**Issue by wtzhang23** [envoyproxy/envoy#33020]
*Description*:
With an additional field in [SchemeHeaderTransformation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-schemeheadertransformation) `use_upstream_scheme`, the Router HTTP filter will use the upstream transport socket's protocol to set the scheme.

Examples:
* `client --HTTP--> envoy --HTTPS--> server`:  `:scheme == https`
* `client --HTTPS--> envoy --HTTP--> server`: `:scheme == http`

*Implementation*:
Add an optional boolean to `HttpConnectionManagerConfig` and set scheme to `host->transportSocketFactory().implementsSecureTransport()` if that boolean is defined and is true

*Relevant Links*:
* [PR](https://github.com/envoyproxy/envoy/pull/19583) removed deprecated field `envoy.reloadable_features.preserve_downstream_scheme`
* Mitigation for [this](https://github.com/envoyproxy/envoy/issues/18095) issue no longer applies
* Affects requests to C# grpc servers as demonstrated in [this](https://github.com/istio/istio/issues/34448) issue

**Comment by htuch** [comment]
Seems reasonable to me. @ggreenway

**Comment by wtzhang23** [comment]
I can try and give this a shot

**Comment by leosarra** [comment]
I also think this is reasonable and I'm interested in using it.
If needed I can assist in the code changes

**Comment by wtzhang23** [comment]
Briefly took a deeper look and believe toggling this option is better in the [Router](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto#envoy-v3-api-msg-extensions-filters-http-router-v3-router) HTTP Filter (e.g. a new field `upstream_override_scheme = true`). I've come to two alternatives closer aligned to the title of this request, but I'm not a fan of either:
* Pass the `SchemeHeaderTransformation` config to the Router filter. This may already exist indirectly, but I'm relatively new to the codebase (my understanding is that the HTTP filters only have access to the callbacks configured by the HTTPConnectionManager). The con is where the config is defined is decoupled from where it is implemented (the Router filter).
* Add the `SchemeHeaderTransformation` config as a field for the Router filter's configuration. The con is it may make configuring the `HTTPConnectionManager` more confusing as setting `use_upstream_scheme` there would be meaningless there. Some configuration validation could solve this con.

Thoughts? This is also my first time looking into the actual source code of the proxy instead of writing extensions so I might be completely off.

**Comment by leosarra** [comment]
I agree that the router filter is the place where it makes most sense to have the option.
Although, given the presence of the other scheme-related options in the ConnectionManager, I think it is fine to add the new field in the ConnectionManager instead.

**Comment by wtzhang23** [comment]
Makes sense. In my draft PRs, I added a field `use_transport_scheme` in `scheme_header_transformation` because I thought there might be a use-case where someone wants to use the client transport to set the scheme as well; e.g.:
`client --https but scheme == http--> envoy --scheme + xfp = https--> server` but I feel uncomfortable about this as coupling the two configs in different locations may restrict future variants. I can attempt to make a PR with an explicit bool in the Router filter when I have the time.
