### ISSUE TITLE
Large request payload makes geoip filter wrongly trim decodeData

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#33021]
*Title*: *Large request payload makes geoip filter wrongly trim decodeData*

*Description*:
While request payload is large, the upstream service could received truncated bytes, i.e., the remaining filters behind geoip could miss some`decodeData` events.

Here's what we think:
While the filter does async lookup, it asks filter manager to stop iteration but not stop the world.
https://github.com/envoyproxy/envoy/blob/dbbe285538d2710b620f0086184377b6e4d9d8c5/source/extensions/filters/http/geoip/geoip_filter.cc#L67

However, `decodeData`s probably come after and we return `Continue`
https://github.com/envoyproxy/envoy/blob/dbbe285538d2710b620f0086184377b6e4d9d8c5/source/extensions/filters/http/geoip/geoip_filter.cc#L71

by the comments which unlock `decodeHeaders` to the remaining filters
https://github.com/envoyproxy/envoy/blob/667e96312130ac2bcbb7c1c598f4d63746d6f0c4/envoy/http/filter.h#L127

Therefore, we have two side effect
(a) the header is not set before `decodeData` sent out
https://github.com/envoyproxy/envoy/blob/dbbe285538d2710b620f0086184377b6e4d9d8c5/source/extensions/filters/http/geoip/geoip_filter.cc#L88

(b) while we code `continueDecoding` again, filter manager fails to handle the events correctly, which triggers the bug we observed.
https://github.com/envoyproxy/envoy/blob/dbbe285538d2710b620f0086184377b6e4d9d8c5/source/extensions/filters/http/geoip/geoip_filter.cc#L93

Un-equipping geoip filter resolved the issue.

--

So we have two bugs I think
(i) https://github.com/envoyproxy/envoy/blob/dbbe285538d2710b620f0086184377b6e4d9d8c5/source/extensions/filters/http/geoip/geoip_filter.cc#L67

we should use `StopAllIterationAndWatermark` in geoip filter to stop the world so we could set headers ready

(ii) although this might be only side effect of filter event mishandling but `continueDecoding` could make the data truncated and IIRC this is not the first time we hit the similar issue. Might need filter management expert to weigh in.

**Comment by htuch** [comment]
@yanavlasov @alyssawilk @KBaichoo

**Comment by JuniorHsu** [comment]
we've verified that `StopAllIterationAndWatermark` work as expected

**Comment by alyssawilk** [comment]
yeah that sounds like a reasonable fix to me.  cc  @nezdolik @ravenblackx as geoip owners.

**Comment by JuniorHsu** [comment]
cool we can work on a patch and let's go from there. thanks alyssa
