### ISSUE TITLE
Memory leak uploading multipart files on HTTP/2 (not in HTTP1.1)

### ISSUE THREAD

**Issue by zanettea** [envoyproxy/envoy#33056]
*Title*: *Leak uploading multipart files on HTTP/2*

*Description*:
The memory increases during upload of files using HTTP/2
If the upload is terminated the memory is not freed.
By forcing HTTP1/1 protocol the memory is constant.

The issue is present since quite a long time ( https://github.com/kyma-project/kyma/issues/11303 )

*Repro steps*:
`
curl --max-time 300 -i -X POST -H "Content-Type: multipart/form-data" -F "myFile=@500m-file" https://endpoint/upload
`
(adding the flag `--http1.1` the issue does not occur)

**Comment by htuch** [comment]
Can you share the Envoy configuration being used? Thanks. CC @yanavlasov @KBaichoo

**Comment by zanettea** [comment]
Here is it: [envoyconfig.json](https://github.com/envoyproxy/envoy/files/14720066/envoyconfig.json)

**Comment by zanettea** [comment]
I've made a local setup to reproduce the issue. Below the steps description:

* generate a large file to stream: `dd if=/dev/zero of=file10GB bs=1024 count=10485760`
* start a "slow" consumer : `npx envoy-memory-issue-test`
* ensure to have the [envoy.json](https://github.com/envoyproxy/envoy/files/14722266/envoy.json) config file in place
* run envoy: `docker run --rm -it --network=host -v $(pwd)/envoy.json:/envoy.json envoyproxy/envoy:debug-v1.28.1  -c envoy.json --log-level debug`
* check initial memory usage `curl localhost:9902/memory`:
```
{
 "allocated": "7533768",
 "heap_size": "12582912",
 "pageheap_unmapped": "0",
 "pageheap_free": "3481600",
 "total_thread_cache": "100592",
 "total_physical_bytes": "22585822"
}
```
* start loading the big file using HTTP2: `curl --http2-prior-knowledge -vvv -F 'file=@file10GB' http://localhost:10000/upload`
* the new memory usage is (287MB):
```
{
 "allocated": "272528864",
 "heap_size": "276824064",
 "pageheap_unmapped": "0",
 "pageheap_free": "401408",
 "total_thread_cache": "100592",
 "total_physical_bytes": "286531038"
}
```

Some observations:
* at some point the amount of memory stops growing and is stable, however at a very high level
* starting multiple connections, every new stream adds more or less the same amount of memory usages (~250MB)
* the physical memory is not leaked. It remains allocated for a while then drops, probably drops after an heap GC
* HTTP1.1 does not show the issue (flow control ensures the memory consumption is constant and low)

**Comment by zanettea** [comment]
Ok, looks like the default value for http2 initial windows size is an insane 256MB. Why is so far from the standard (65k)?
