### ISSUE TITLE
dns_lookup_family has auto in v2, v4_only in v1 as the default.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#3306]
According to https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster#config-cluster-manager-cluster, 
> If this setting is not specified, the value defaults to v4_only.

According to https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#enum-cluster-dnslookupfamily,
>  Enum Cluster.DnsLookupFamily
...
AUTO
 (DEFAULT) ⁣

This could introduce some surprises/things broken for users in transition from v1 to v2.

Probably related to https://github.com/envoyproxy/envoy/issues/2853.

**Comment by mattklein123** [comment]
@htuch thoughts on this? I remember we discussed this a while back but I don't recall what we actually said about it.

**Comment by mattklein123** [comment]
I'm going to close this as answered. Unfortunately I don't think we can change this now though I agree it was a poor choice (@ccaraman just ran into this at Lyft). If you feel like doing a doc warning PR that would be appreciated.

**Comment by htuch** [comment]
@mattklein123 I don't remember what the reasoning here was, it probably was just an oversight. I agree that the best we can do is docs. I also think I need to fix my gmail filters to spot these kinds of questions, I totally missed this.
