### ISSUE TITLE
CORS filter sets the access-control-expose-headers header even when the origin is not allowed

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#33086]
*Title*: *CORS filter sets the access-control-expose-headers header even when the origin is not allowed*

It appears that this issue stems from https://github.com/envoyproxy/envoy/pull/33051.

The `is_cors_request_` variable is now being set to true when origin_allowed is false.

Previously, in the code prior to this PR, `is_cors_request_` was set to false when origin_allowed was false.

Is this behavior expected, or is it a bug?

**Comment by htuch** [comment]
@wbpcode @daixiang0

**Comment by arkodg** [comment]
cc @cpakulski

**Comment by cpakulski** [comment]
I am investigating it.

**Comment by cpakulski** [comment]
I think that the fact that headers were not added for not matching requests was side effect, not indented action. Anyways, I fixed it to bring previous behaviour and added unit test to enforce that logic.
