### ISSUE TITLE
Unable to remove entire priority through EDS

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#3312]
Suppose Envoy has been previously configured with EDS with two localities, L1 and L2 with priorities 0 and 1 respectively. Sending an EDS update that only contains L1 does not remove L2 from the cluster. 

Looking at the code, this is because in `EdsClusterImpl::onConfigUpdate` we look at all the priorities found in the new config and iterate over the priority sets corresponding to those priorities on the cluster, leaving any other priority set untouched. As a result we ignore (i.e. don't remove) priorities that are not present in the incoming config update. 

I'd expect removing an entire priority from EDS to work the same way as removing any other group of hosts. 

Failing test case: https://github.com/snowp/envoy/commit/c892cac9181284044ec7bf5d129a8d1e063aa474

Filing this mostly for informational purposes as I'm already working on getting this fixed.

**Comment by mattklein123** [comment]
@alyssawilk @htuch  FYI

**Comment by htuch** [comment]
One thing to keep in mind when working on any fix @snowp is that priorities are currently intended to be "dense". I think there is some assumption that we have priority [0..n] without any gaps where n is the highest. It might be fine to have sparse priorities, but you might hit some gotchas as well.

**Comment by snowp** [comment]
That property of the priorities makes fixing this pretty simple: If envoy currently has N priorities but receives an update with `M < N` priorities, then priorities `M, ... N` are no longer referenced and should be removed. 

Related to this: do we verify that priorities are dense? I definitely see code that would behave strangely (or just break) if that wasn't true, so I'd expect Envoy to reject the update if the priorities are not sequential?
