### ISSUE TITLE
Cannot log trace id

### ISSUE THREAD

**Issue by inssein** [envoyproxy/envoy#33129]
We are using the OpenTelemetry tracer, which auto injects `Traceparent` and `Tracestate` headers which is awesome. However, we also want Envoy to log the trace id.

Today, our logs use `%REQ(X-REQUEST-ID)%` as the trace id, but this is not helpful because request id and trace id seem to be distinct concepts in Envoy.

I tried adding a Lua script that could do this for us, but it seems that the `Traceparent` header is not yet available. 

Logging `%REQ(TRACEPARENT)%` works but is not desirable because we don't need the other data in our logs.

Any thoughts on how else we could accomplish getting the trace id into our logs?

P.S: https://github.com/envoyproxy/envoy/issues/30052 would also potentially work for us

**Comment by yanavlasov** [comment]
Adding various tracer owners for comment: @mattklein123 @wbpcode @alexanderellis @basvanbeek

**Comment by WojciechKuk** [comment]
trace-id is the substring of traceparent.
you can use `%REQ(X?Y):Z%` notation, where Z means max number of chars.

so `%REQ(TRACEPARENT):35%` will give you string with `00-<trace-id>` value.

unfortunately, there is no parameter to omit first 3 chars - should be something like `):3:32%`
