### ISSUE TITLE
Unable to retrieve route-level filter configuration with on-demand filter

### ISSUE THREAD

**Issue by maoyutao** [envoyproxy/envoy#33152]
I am using the on-demand plugin and have a custom plugin placed after it. I've noticed that when the first request triggers the on-demand plugin to obtain a new virtual host, calling resolveMostSpecificPerFilterConfig in my custom plugin fails to retrieve the route-level configuration.

I have confirmed that the dispatched route configuration contains the route-level plugin configuration, and that this configuration can be normally retrieved on the second request.

Steps to reproduce:

Configure Envoy to use the on-demand plugin and a custom plugin.
Send the first request, triggering the on-demand plugin to obtain a new virtual host.
In the custom plugin, call resolveMostSpecificPerFilterConfig to try to retrieve the route-level configuration.

Expected result:
After the first request, the route-level configuration should be retrievable in the custom plugin.

Actual result:
After the first request, the route-level configuration cannot be retrieved in the custom plugin. However, it can be normally retrieved on the second request.

Environment:
Envoy version: 1.28

**Comment by yanavlasov** [comment]
Adding @kyessenov @dmitri-d as codeowners

**Comment by maoyutao** [comment]
https://github.com/envoyproxy/envoy/blob/f580ed067db0f2a48085aa33e45a3a9cf5e36bfe/source/extensions/filters/http/on_demand/on_demand_update.cc#L206


Does this mean that the on-demand filter only supports GET requests?
@kyessenov @dmitri-d
