### ISSUE TITLE
[tracing] Add contextual info (type of service) into Tracing::Span::InjectContext interface. 

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#33167]
*Title*:  Add contextual info (type of service) into Tracing::Span::InjectContext interface. 

*Description*:
Right now the Envoy Span::injectContext takes two parameters, the trace_context (headers), and an often times omitted upstream hostDescription pointer. 

Considering a proxy may have many side streams, e.g. some being grpc servers, some being http servers. 
The upstream host description oftentimes is not enough to provide enough information for the span to decide what to inject, e.g. to propagate to a http-server, a Span may want to inject the x-cloud-trace-context header; while if the upstream is a grpc server, the span may want to inject a grpc-trace-bin header instead. 

Let's add a third parameter to injectContext api, e.g. service_type, to provide better contextual information.

**Comment by stevenzzzz** [comment]
@wbpcode would like to know how you think.

**Comment by stevenzzzz** [comment]
@botengyao @yanavlasov as well.

**Comment by wbpcode** [comment]
SGTM to this requirement. But rather than third parameter, I prefer a single new context that includes host, cluster_info, etc. (upstream context?)

**Comment by botengyao** [comment]
Thanks @stevenzzzz! This also looks reasonable to me.

**Comment by stevenzzzz** [comment]
sounds good. let's add a context data structure for it. but noteworthy the callsites of this methods tho: would need some plumbing work if we want to get more info into the context. (we can do it incrementally).
