### ISSUE TITLE
HttpConnectionManager doesn't forward the request body to wasmplguin in case of failures like no_healthy_upstream

### ISSUE THREAD

**Issue by harsha-konda** [envoyproxy/envoy#33196]
*Title*:  HttpConnectionManager doesn't forward the request body to wasmplguin in case of failures like no_healthy_upstream  for outbound calls to upstream from envoy

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

- I have a wasm plugin (on the oubound calls ) that has some logging and metrics based on the request headers and body in golang deployed on istio. It works as expected in cases where the request and response are succesfully proxied(ie. with 200 status code). 

- However in a scenario where the upstream envoy cluster might not have any ips then the connection manager uses a local reply to respond with `no_healthy_upstream`. In this situation the body is not passed to the wasmplugin , but the headers are passed. 

Could you suggest any way in which i can make sure that envoy passes the request body back to the wasmplugin? I changed the priority of my http filters such that wasm plugin is the first in the chain for the http_connection_manager. However that didn't help with this.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

here's my plugin and its deployed on a service with istio mesh.

```
package main

import (
	"errors"
	"fmt"
	"github.com/tetratelabs/proxy-wasm-go-sdk/properties"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
	"os"
	"regexp"
	"strconv"
	"strings"
)
func main() {
	proxywasm.SetVMContext(&vmContext{})
}

type vmContext struct {
	types.DefaultVMContext
}

type pluginContext struct {
	types.DefaultPluginContext
	metrics *Metrics
}

func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
	return &pluginContext{
		metrics: NewMetrics(),
	}
}

func (ctx *pluginContext) NewHttpContext(contextID uint32) types.HttpContext {

	return &httpContext{contextID: contextID, pluginContext: ctx}
}

type httpContext struct {
	types.DefaultHttpContext
	contextID      uint32
	requestHeaders *[][2]string
	requestBody    *[]byte
	pluginContext  *pluginContext
}

func (ctx *httpContext) OnHttpRequestHeaders(_ int, endOfStream bool) types.Action {
	proxywasm.LogInfof("WASM plugin Handling request endofstream %t", endOfStream)
	// Get the actual request headers from the Envoy Sidecar
	requestHeaders, err := proxywasm.GetHttpRequestHeaders()
	if err != nil {
		proxywasm.LogCriticalf("failed to get request headers: %v", err)
		return types.ActionContinue
	}

	body, err := proxywasm.GetHttpRequestBody(0, 100000)
	if err != nil {
		proxywasm.LogErrorf("failed to get request body: %v", err)
	}
	proxywasm.LogInfof("body %s", string(body))

	ctx.requestHeaders = &requestHeaders
	return types.ActionContinue
}

func (ctx *httpContext) OnHttpRequestBody(bodySize int, endOfStream bool) types.Action {
	proxywasm.LogInfof("WASM plugin Handling response body %d - %t", bodySize, endOfStream)

	body, err := proxywasm.GetHttpRequestBody(0, bodySize)
	if err != nil {
		proxywasm.LogErrorf("failed to get request body: %v", err)
		return types.ActionContinue
	}
	ctx.requestBody = &body
	proxywasm.LogInfof("body %s", string(body))

	return types.ActionContinue
}

func (ctx *httpContext) OnHttpResponseHeaders(numHeaders int, endOfStream bool) types.Action {
	proxywasm.LogInfof("WASM plugin Handling response headers")

	hrs,_ := proxywasm.GetHttpResponseHeaders()

	for _, hrs := range hrs {
		proxywasm.LogInfof("response header %s - %s", hrs[0], hrs[1])
	}

	return types.ActionContinue
}
```
>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by harsha-konda** [comment]
i have also posted this issue on istio github https://github.com/istio/istio/issues/50135

**Comment by harsha-konda** [comment]
Hi @yanavlasov , is there any workaround to get the body ?

**Comment by yanavlasov** [comment]
Unfortunately not.
