### ISSUE TITLE
Startup failure with `pthread_create failed: Operation not permitted`

### ISSUE THREAD

**Issue by zakhenry** [envoyproxy/envoy#33247]
*Title*: *Startup failure with `pthread_create failed: Operation not permitted`*

*Description*:

More of a help request - I'm attempting to upgrade an Envoy instance from 1.25.0 to 1.29.2 and finding that it now fails to start with an assert. Relevant long lines from latest main:

```
[2024-04-01 21:42:40.506][1][critical][backtrace] [./source/server/backtrace.h:112] Envoy version: 014a68f303074fb743b780548ac58d2e1340ec53/1.30.0-dev/Clean/RELEASE/BoringSSL
[2024-04-01 21:42:40.506][1][critical][backtrace] [./source/server/backtrace.h:127] Caught Segmentation fault, suspect faulting address 0x0
E0401 21:42:40.488786132       1 thd.cc:157]                           pthread_create failed: Operation not permitted
[2024-04-01 21:42:40.505][1][critical][assert] [source/common/common/posix/thread_impl.cc:147] assert failure: false. Details: Unable to create a thread with return code: 1
Our FatalActions triggered a fatal signal.
```

Note the ordering above is not necessarily correct due to logging infrastructure reasons.

Locally, with docker I do not get this issue, and also I don't get it in my CI infrastructure - only in an instance deployed to AWS ECS. Where might I start looking to diagnose this issue as I've come up empty trying to find similar situations encountering the same issue.

From what I can tell the return code `1` indicates an `EPERM` error, but I haven't change anything regarding permissions or the envoy user etc.

Also tried the latest `main` version to see if that helped but same result (slightly better error message as shown above)

**Comment by soulxu** [comment]
@zakhenry I wasn't sure the reason, just some random thoughts, have you tried to run the privileged container? Maybe just check the container has enough permission first.

**Comment by soulxu** [comment]
cc @phlax if he saw something similar in the CI job.

**Comment by phlax** [comment]
i didnt see this before - you definitely shouldnt require a `privileged` container (or any special caps)

it seems related to running with realtime scheduling

there is a similar discussion here https://stackoverflow.com/questions/9313428/getting-eperm-when-calling-pthread-create-for-sched-fifo-thread-as-root-on-lin

 i would try running the binary directly (ie no container) on the problem platform and see what gives with that

**Comment by zakhenry** [comment]
Thanks for the ideas both, to update we managed to find a correlation for this issue which was that our version of docker in ECS was incompatible with envoy 1.29.0. For now we're pinning at 1.28.0 until we can upgrade our ECS AMIs
