### ISSUE TITLE
Envoy Unable to Cache the Response from Upstream Service

### ISSUE THREAD

**Issue by darshak-patel** [envoyproxy/envoy#33266]
I am trying to Cache the response coming from upstream client in envoy using FileSystemCache in Envoy v1.29.2 but envoy is not caching the response.

Upstream client is not returning the cache-control header so i have written following lua script in order to add Cache-Control header in response header.

name:
envoy.filters.http.cache
typed_config:
"type": type-googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig
typed_config:
"type": type.googleapis.com/envoy.extensions.http.cache.file_system_http_cache.v3.FileSystemHttpCacheConfig
manager_config:
thread_pool:
thread_count:
20
cache_path: /app1

name: envoy.filters.http.lua
typed_config:
"type": type-googleapis.com/envoy.extensions.filters.http.lua.v3. Lua
default_source_code:
inline_string: I
- Called on the response path.
function envoy_on_response(response_handle)
print( response_handle:headers(): get("x-envoy-upstream-service-time"))
response_handle: headers(): replace( "cache-control", "max-age=3600')
end

I have added lua script filter after the cache filter in http_filters path so that in response path lua filter add the cache-control header first and then cache filter execute.

I noticed when I hit any route configured to return direct response back from envoy, caching works fine, but when I hit a route which receives the response from Upstream client then caching doesn't work.

**Comment by soulxu** [comment]
Close this one, since it duplicates with https://github.com/envoyproxy/envoy/issues/33267
