### ISSUE TITLE
Envoy unable to Cache the Response from Upstream Service

### ISSUE THREAD

**Issue by darshak-patel** [envoyproxy/envoy#33267]
I am trying to Cache the response coming from upstream client in envoy using FileSystemCache in Envoy v1.29.2 but envoy is not caching the response.

Upstream client is not returning the cache-control header so i have written following lua script in order to add Cache-Control header in response header.

name:envoy.filters.http.cache
typed_config:
 "type": type-googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig
 typed_config:
  "type": type.googleapis.com/envoy.extensions.http.cache.file_system_http_cache.v3.FileSystemHttpCacheConfig
  manager_config:
   thread_pool:
    thread_count:20
  cache_path: /app1

name:envoy.filters.http.lua
typed_config:
 "type": type-googleapis.com/envoy.extensions.filters.http.lua.v3. Lua
 default_source_code:
inline_string: I

-- Called on the response path.
function envoy_on_response(response_handle)
print( response_handle:headers(): get("x-envoy-upstream-service-time"))
response_handle: headers(): replace( "cache-control", "max-age=3600')
end
I have added lua script filter after the cache filter in http_filters path so that in response path lua filter add the cache-control header first and then cache filter execute.

I noticed when I hit any route configured to return direct response back from envoy, caching works fine, but when I hit a route which receives the response from Upstream client then caching doesn't work.

**Comment by soulxu** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
cc @ravenblackx

**Comment by ravenblackx** [comment]
Not to the question, but I'm pretty sure you don't need 20 cache file management threads. I haven't done a performance analysis of any kind but I'd be surprised if anything more than 2 makes a positive difference.

For the question, I think you probably need to investigate what else is in the headers of the response (and maybe request) for the things that aren't caching.

[Here](https://github.com/envoyproxy/envoy/blob/34f8b3703cdd5ef81c7c1ef9811ed0c4537cd6c1/source/extensions/filters/http/cache/cacheability_utils.cc#L34-L58) is a set of things that will prevent caching from the request headers side, and [here](https://github.com/envoyproxy/envoy/blob/34f8b3703cdd5ef81c7c1ef9811ed0c4537cd6c1/source/extensions/filters/http/cache/cacheability_utils.cc#L60-L79) is the set of things in response headers. (Status code must be one of "200", "203", "204", "206", "300", "301", "308", "404", "405", "410", "414", "451", "501"; must not have a Vary header unless other stuff is configured to match.)

**Comment by darshak-patel** [comment]
@ravenblackx I thought request and response caching are two different things in envoy, but as per your answer if some headers that are coming into request can affect the response caching, is that correct?

**Comment by ravenblackx** [comment]
Authorization headers prevent caching. ([here](https://sourcegraph.com/github.com/envoyproxy/envoy@0fbb643131c342943c95e9f5e6f36611105c9716/-/blob/source/extensions/filters/http/cache/cacheability_utils.cc?L55))

**Comment by darshak-patel** [comment]
Is there a way to cache the response if request consists authorization header? Because we have a JWT validation policy in place which authenticates the user and then allow access to cache response.

**Comment by darshak-patel** [comment]
Validation is happening before the cache filter but the problem is the upstream service also does the jwt validation so I can't remove the authorization header

**Comment by ravenblackx** [comment]
One option would be to move the authorization header away (e.g. onto `x-tmp-authorization`), before the cache filter, then move it back again after. Or you could alter the cache filter to have a configurable `allow_authorization_header` value that alters the behavior where I linked. There's no simple way to do what you want with the filter as it is now.

**Comment by darshak-patel** [comment]
Sorry, I couldn't get the point you are trying to explain with Or clause here(allow_authorization_header). Can you explain more on this?

Also, is it mandatory to send the cache-control header in request? I noticed if I don't send this header then envoy updates the cached Response on each hit.

**Comment by ravenblackx** [comment]
The `allow_authorization_header` suggestion was, if you can do C++, you could modify the code of the cache filter to make it optionally support the behavior you want it to have, that it currently does not have. Ignore that suggestion if C++ is not your thing - in that case either shuffling headers around or changing your requirements would be your best bet.

My understanding is no, it's not mandatory to send the cache-control header in requests, but there does need to be one in responses.

This sort of thing is going further outside my area of expertise, which is the implementation of the file cache extension and to a lesser extent the implementation of the cache filter. Once it gets to the topic of how http caches are supposed to work in general I'm a lot less confident, and you'd get better advice from maybe @toddmgreer .

**Comment by darshak-patel** [comment]
@ravenblackx / @toddmgreer I think envoy docs should clearly mention this case where if the request header contains Authorization header then envoy won't cache the response. If you see the docs, there is no information about the Authorization header.
[https://www.envoyproxy.io/docs/envoy/v1.29.2/configuration/http/http_filters/cache_filter#config-http-filters-cache](https://www.envoyproxy.io/docs/envoy/v1.29.2/configuration/http/http_filters/cache_filter#config-http-filters-cache)

**Comment by toddmgreer** [comment]
Currently, CacheFilter won't cache responses with Authorization headers. Ideally, this should be overridden by explicit `cache-control: public` response headers. Patches welcome!
