### ISSUE TITLE
Envoy as a generic CONNECT (http tunnel/explicit) proxy

### ISSUE THREAD

**Issue by marc-barry** [envoyproxy/envoy#33263]
*Title*: *When using Envoy as a generic CONNECT proxy it leads upstream connection failures (UpstreamConnectionFailure/UF) under minimal load*

*Description*:

I have a configuration whereby Envoy acts as a generic CONNECT proxy to domains (i.e. similar to how some use Squid). This will allow it to run locally and set the HTTP/HTTPS proxy settings (i.e. sometimes done by environment variables HTTP_PROXY/http_proxy, HTTPS_PROXY/http_proxy... and sometimes simply done in system settings of the underlying OS). The idea is that requests like the following will leverage the proxy for HTTP/HTTPS requests leaving the host. Here are some example `curl` requests to illustrate:

- `http_proxy=http://127.0.0.1:10080 https_proxy=http://127.0.0.1:10080 curl -I -X GET https://www.cnn.com`
- `curl -I -X GET https://www.cnn.com --proxy http://127.0.0.1:10080`
- `curl -I -X GET https://api.github.com --proxy http://127.0.0.1:10080`

I have a config (attached) which works with `curl` as illustrated below:

```
curl -I -X GET https://api.github.com --proxy http://127.0.0.1:10080
HTTP/1.1 200 OK
date: Tue, 02 Apr 2024 13:48:56 GMT
server: envoy

HTTP/2 200
server: GitHub.com
date: Tue, 02 Apr 2024 13:48:53 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With
etag: W/"4f825cc84e1c733059d46e76e6df9db557ae5254f9625dfe8e1b09499c449438"
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
x-ratelimit-limit: 60
x-ratelimit-remaining: 52
x-ratelimit-reset: 1712068457
x-ratelimit-resource: core
x-ratelimit-used: 8
accept-ranges: bytes
content-length: 2262
x-github-request-id: D0CC:3419:24ACC60:3C24383:660C0CC8
```

`curl` shows you that the `CONNECT` was a `200` and then it is able to send the actual request over the TCP connection (and negotiate TLS) with a status of `200`. This is what the expected outcome is.

But when I increase the traffic level by pointing my web browser at the proxy or by writing a script to increase load the result is a high number of **`503`** status codes with the response flag of **`UF`** which is also known as **`UpstreamConnectionFailure`**. The essence of my setup involves matching requests for HTTP and then having a `CONNECT` matcher which sends it to a dynamic forward proxy which uses DNS resolution to establish a TCP connection with the correct upstream.

I can't see any issues with the configuration and have looked through all the references (i.e. see the relevant links) for example configurations. Probably the most relevant one is https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http3_connect_udp_dns_resolution.yaml since it uses DNS resolution (although it is geared towards HTTP/3 and I'm really targeting HTTP/1.1).

I have attached the current running config dump in the hopes that someone can direct me towards what might be causing the issue. As I understand, Envoy will keep connections open the upstreams and will reuse these as part of connection pooling. In many cases one gets a **`DC/DownstreamConnectionTermination `** response flag which is what is expected for `CONNECT` termination but there are far more **`UF`** (for many times the same IP:port combination). I have also included logging in the configuration so that the method, response flag...among other things are logged.

[config_dump.json](https://github.com/envoyproxy/envoy/files/14837690/config_dump.json)

*Relevant Links*:

- https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http1_connect.yaml
- https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http2_connect.yaml
- https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http3_connect_udp_dns_resolution.yaml

**Comment by soulxu** [comment]
@marc-barry do you have envoy log? It can be get by adding parameter "-l debug" to cmd

**Comment by marc-barry** [comment]
@soulxu I ran it with debug info and it created a massive volume of logs which took some time to understand. In the end the issues seemed to point to a networking problem. We had been having some networking problems with our development setup under our Docker container environment and so I decided to test if that was the causing factor. I tested the above configuration with a few Docker setups but you can reproduce my issue using the following type of container setup:

- Run the Docker container with Envoy inside and the configuration I provided using https://orbstack.dev/ on a macOS device (i.e. a MacBook). I is worth noting that my development machine is Apple silicon based (i.e. M1).
- Start the container with something like `docker run -p 10080:80 -p 10443:443 -p 18443:8443 -p 9901:9901` to expose the ports on the MacBook.
- Follow the instructions under https://support.apple.com/en-ca/guide/mac-help/mchlp2591/14.0/mac/14.0 for changing your "Secure web proxy (HTTPS)" setup to something like http://127.0.0.1:10080.

It is at the point of changing the proxy settings when a flurry of logs and upstream connection failures happen. I was suspicious that this was a container routing problem on my local host due to some unknown network configuration reason.

In order to rule out the network issues I decided to leverage https://lima-vm.io/ which is something that I tend to use when developing code targeting specific kernels or kernel features. I started a VM which supports containers and then tested the same thing as above with the Lima setup and Envoy works exactly as expected.

Thus, I inadvertently thought this was an Envoy issue when it was actually a network stack issue that I had misidentified. I thought that the connection failures where the result of Envoys dynamic forward proxy implementation and the scale of requests I was sending to Envoy.

Is there something you would like me to do in regards to collecting more information about the problematic setup or updating some documentation to help others who may hit this in the future?

**Comment by marc-barry** [comment]
I'm closing as this is not an issue was the result of https://github.com/envoyproxy/envoy/issues/33263#issuecomment-2037116232.
