### ISSUE TITLE
max_requests behavior in cluster circuit_breaker

### ISSUE THREAD

**Issue by sharma-mona** [envoyproxy/envoy#33279]
*Title*: *behavior of max_requests in cluster circuit_breaker*

*Description*:
> When max_requests limit is reached, the http request is immediately failed instead of queuing up till the max_pending_requests limit. This behavior is different from the max_connections limit wherein, on hitting the limit, the request is queued. This results in inconsistent behavior.

We noticed this while switching to http2 for upstream connections. Currently, with http1, we have following circuit breakers in place:

circuit_breakers:
  thresholds:
     max_connections: 128

For http2, we have changed the circuit breaker to use max_requests as follows:

circuit_breakers:
  thresholds:
     max_requests: 128
http2_protocol_options: {}

In http1 case, the downstream clients could send more than 128 concurrent requests and all requests will succeed with no overflow. In http2 case, only 128 requests succeed, rest all fail with overflow. Logs show "max streams overflow".

The only way I can make the circuit_breaker work is with following config. I can now send more than 128 concurrent requests and all succeed.
circuit_breakers:
  thresholds:
     max_requests: 128
     max_connections: 1
http2_protocol_options:
    max_concurrent_streams: 32

max_concurrent_streams is set to 32 because concurrency=4. However, this results in higher latency if all 128 concurrent requests come on one downstream http2 connection.

Why does envoy not queue up the request on hitting max_requests limit?

**Comment by soulxu** [comment]
cc @wbpcode

**Comment by soulxu** [comment]
@sharma-mona have you tried `max_pending_requests`?

**Comment by sharma-mona** [comment]
@soulxu  Since max_pending_requests is not set, it defaults to 1024. Also, I have tried explicitly setting it to 2048  like so but does not help.

```
circuit_breakers:
   thresholds:
       max_requests: 128
       max_pending_requests: 2048
http2_protocol_options: {}
```
