### ISSUE TITLE
Envoy does not forward GRPC keep alive

### ISSUE THREAD

**Issue by visan-csdisco** [envoyproxy/envoy#33289]
*Title*: *Envoy does not forward GRPC keep alive*

*Description*: We have multiple services deployed which are using envoy proxies as sidecars.
These services communicate with each other over grpc.

The infrastructure setup is:
``
 Grpc Client -> Envoy Client Proxy -> Envoy Server Proxy -> Grpc Server
 ``

We are using a **bidirectional** grpc streaming communication from the client to the server so that a request stream as well as a response stream on the client side.

Even though the server streams the responses periodically, we can see **that after 5 minutes** the stream gets reset and the connection killed.

This is due to the [stream_idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-idle-timeout) on the envoys and the fact that the client sent an initial request and then it does nothing for 5 minutes on the request stream.

On the response stream, responses are streaming constantly from the server.

We tried enabling GRPC keep alives on both client/server, but from what we see the envoys are not forwarding the keep alives to downstream/upstreams.

The only thing that worked for us was to disable the **stream_idle_timeout** by setting it to 0s or by adding a grpc client interceptor that would periodically send empty messages to the server.

This seems like a common use case, so we have the following questions:

1) Why are the envoys not forwarding the keep alives? Is this because of HTTP2 semantics? 
     From what we could see is that envoys reply to the keep alives, but they don't hop on to the next connection section.

2) What can we do besides disabling the **stream_idle_timeout** ? We don't want it disabled as it could leak connections.

3) Is there any way or setting that we can use?

Attached architecture scheme:
![image (2)](https://github.com/envoyproxy/envoy/assets/121261964/9713f39c-a229-4252-9a70-b61e80f5a85d)

**Comment by phlax** [comment]
cc @mattklein123  who might have some insights here

**Comment by visan-csdisco** [comment]
@phlax/ @mattklein123  Can you help us with the above?

**Comment by phlax** [comment]
apologies that you have not received a response @visan-csdisco - i dont know the answer and it wasnt immediately obvious who to ask

i have noticed other issues have come up around `stream_idle_timeout` so it might be worth looking existing issues
