### ISSUE TITLE
Should we skip setting the composite filter state if it is in upstream chain?

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#33343]
*Title*: Should we skip setting the composite filter state if it is in upstream chain?

*Description*:
Currently composite filter is only available in downstream.
Work is done to convert it as dual filter (https://github.com/envoyproxy/envoy/pull/33013) so it can be configured in both downstream and upstream.

The below code is setting the action_name in filter state:
https://github.com/envoyproxy/envoy/blob/d07b522e68d0f1c53e4e76d61445a892626ff285/source/extensions/filters/http/composite/filter.cc#L143

Should we skip the filter state update when the composite filter is in upstream filter chain?

For more details about this, please check discussion under:  https://github.com/envoyproxy/envoy/pull/33013#issuecomment-2037413823

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by juanmolle** [comment]
IMHO if there are concerns and due to we are getting closer to the 1.30 release, we could skip it in case the filter is in upstream mode. In case there is a valid use case and the information is needed we can enable it.

The motivation to add that info is to know what action was executed in access_log.

**Comment by yanjunxiang-google** [comment]
add @tyxia

**Comment by yanjunxiang-google** [comment]
@juanmolle ok, let me skip it in the next PR.

**Comment by juanmolle** [comment]
@yanjunxiang-google  Yes exactly, the intention is to allows logging and in our specific case be consume by a custom wasm filter.

**Comment by phlax** [comment]
@juanmolle i can add you to the assignable team if you are happy to be assigned prs/issues

**Comment by juanmolle** [comment]
Sure, no problem

**Comment by htuch** [comment]
It seems reasonable to have some record passed down the filter chain of what matches, regardless of downstream or upstream. Different match criteria will be stable or not across retries, the onus would be on whoever uses this sensibly. There should be different filter states tracked for each instance of composite filter to avoid any conflation across the instance state.

**Comment by yanjunxiang-google** [comment]
Yeah,  that's a good observation that if there are one composite filter in downstream and one in upstream, we need to make sure the filter state won't conflate.  So,  we probably can give different key names for upstream and downstream, something like:
envoy.extensions.filters.http.composite.matched_actions.downstream
envoy.extensions.filters.http.composite.matched_actions.upstream
https://github.com/yanjunxiang-google/envoy/blob/521973001d7958c1262da19caaf6375bd397dc87/source/extensions/filters/http/composite/filter.cc#L146
https://github.com/yanjunxiang-google/envoy/blob/521973001d7958c1262da19caaf6375bd397dc87/source/extensions/filters/http/composite/filter.h#L20

The alternative is to skip updating the filter state for now if composite filter is in upstream. And do something like above if anyone cares about it.

**Comment by juanmolle** [comment]
I guess a collision could happens only if someone use the same filter_name for 2 filters, no matter if are both downstream or upstream. Adding a suffix in case of upstream could eventually help, specially if we would like to change the information, for example adding a counter to indicate if there were retries. (I prefer to not change downstream key name because it was released in 1.29)
skipping it until we have a real use case sounds reasonable to me

**Comment by yanjunxiang-google** [comment]
SGTM

**Comment by juanmolle** [comment]
I'm thinking in loud, could between retries change the matching? in that case it could populate for a call 2 filter_name, one of them failed, the first one,  it generates the retry and the second matching success, that info could be useful.

**Comment by yanjunxiang-google** [comment]
I don't have an answer for this.  So, if we have to support filter state in upstream, we need to sort out below:
1) require the composite filters configured in downstream and upstream have different names ---- currently it is not enforced.
2) If there are multiple retires, how to store  the filter state? Should the last one win, or keep all the intermediate ones?
