### ISSUE TITLE
Unable to parse envoy access log attribute value to  int from string using CEL formatter

### ISSUE THREAD

**Issue by darshak-patel** [envoyproxy/envoy#33352]
I’m currently utilizing envoy v1.29.2 and need to perform metric calculations using the x-envoy-upstream-service-time header. However, I’m encountering a challenge where I receive a string value for this header, whereas I require it to be in integer format for my calculations. Therefore, I opted to utilize the CEL formatter to handle type conversion, but I’m facing some difficulties in implementing it. Could you provide assistance or guidance in resolving this issue?

Expression: %CEL(int(response.headers['x-envoy-upstream-service-time']))%

Error: Incorrect configuration: %CEL(int(response.headers['x-envoy-upstream-service-time']))%. Couldn't find valid command at position 0

**Comment by phlax** [comment]
cc @kyessenov @zirain

**Comment by JonathanO** [comment]
I suspect this is because https://github.com/envoyproxy/envoy/blob/7b6b507850ed6a369ba162b53eaba99f5c57c7ca/source/common/formatter/substitution_formatter.cc#L41C54-L41C71 disallows `)` in the subcommand of a formatter, causing it to reject function calls in CEL.

**Comment by darshak-patel** [comment]
Is there a way i can add %REQUEST_TX_DURATION% and %RESPONSE_TX_DURATION% to get envoy latency in access log (json_format)?

**Comment by darshak-patel** [comment]
> I suspect this is because https://github.com/envoyproxy/envoy/blob/7b6b507850ed6a369ba162b53eaba99f5c57c7ca/source/common/formatter/substitution_formatter.cc#L41C54-L41C71 disallows `)` in the subcommand of a formatter, causing it to reject function calls in CEL.

Does it mean we cannot convert any string value to int using CEL?

**Comment by darshak-patel** [comment]
?
