### ISSUE TITLE
On-demand filter in Envoy not working with POST requests

### ISSUE THREAD

**Issue by maoyutao** [envoyproxy/envoy#33384]
I have been using the OnDemand plugin in Envoy and I've encountered an issue during testing.

When the first request is a GET request, everything works as expected and the request returns a 200 status code. However, when the first request is a POST request, Envoy returns a 404 status code.

I suspect the issue might be related to this part of the code: https://github.com/envoyproxy/envoy/blob/f580ed067db0f2a48085aa33e45a3a9cf5e36bfe/source/extensions/filters/http/on_demand/on_demand_update.cc#L206

There is no description of this behavior in the documentation. I would like to know if this is due to incorrect usage on my part or if the plugin indeed only supports GET requests.

Environment:
Envoy version: 1.28

**Comment by RyanTheOptimist** [comment]
cc: @dmitri-d @htuch @kyessenov

**Comment by htuch** [comment]
Yeah, seems so from that code and looking at `on_demand_integration_test.cc`, I don't see any POST tests, so I would consider this unsupported.
