### ISSUE TITLE
Is it possible to build the customized http filter as a shared library

### ISSUE THREAD

**Issue by minjunjiang** [envoyproxy/envoy#33380]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Is it possible to build the customized http filter as a shared library？
In other words, can we deploy customized filters separately so that the deployed envoy can dynamically load them?

*Description*:
>Describe the issue.

As I know, basically, if we create some customized http filters then we need to build them among with the envoy, before deploy the envoy.
Which is not convenient in our case, we want to build the customized filters separately after the envoy was deployed, and let the envoy instance to load them dynamically.
Can current envoyproxy support this kind of scenario?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
cc: @phlax @alyssawilk

**Comment by phlax** [comment]
>  In other words, can we deploy customized filters separately so that the deployed envoy can dynamically load them?

not afaiaa.

This question has come up previously - i think it would require a stable ABI to be possible (cc @mattklein123 )

**Comment by minjunjiang** [comment]
Thanks for your reply, can [Golang plugin](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/golang_filter#golang)  do this job?

**Comment by phlax** [comment]
iiuc your question - i think yes you can compile your go plugin separately (and after the fact) to compiling Envoy itself

cc @doujiang24 for any further insight on this

**Comment by doujiang24** [comment]
yep, you could compile Golang plugin into shared library, and load into Envoy process on demand at runtime.
Here is the doc of Golang http plugin: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter

**Comment by minjunjiang** [comment]
THANK YOU!
