### ISSUE TITLE
can envoy health check re-use traffic connection

### ISSUE THREAD

**Issue by futangw** [envoyproxy/envoy#3341]
**Issue Template**

*Title*: *One line description*
can envoy health check re-use traffic connection

*Description*:

I had set up two envoys as client/server and both of them are using only 1 working thread (--concurrency 1). I also set http type health check for them. I want the http HC and traffic use only one connection (that means the http HC re-use traffic connection). Is it possible? 

I'm using envoy  version: 4dd49d8809f7aaa580538b3c228dd99a2fae92a4/1.6.0/Clean/RELEASE

thanks.

**Comment by mattklein123** [comment]
Closing as answered.
