### ISSUE TITLE
How to use Custom Response Filter or Local Reply Modification Config to modify response based on upstream service response body or using command operator such as %RESPONSE_CODE_DETAILS% in Envoy?

### ISSUE THREAD

**Issue by darshak-patel** [envoyproxy/envoy#33414]
I want to modify the response return by envoy either based on upstream service response body or using command operator such as %RESPONSE_CODE_DETAILS% in envoy, but I am not able to find appropriate example for it.

In case of expired jwt, envoy returns "jwt is expired" response body from codec api, but I don't want to return the body as it is and want to modify before sending it to client. Example, 401 is very generic error code and expired token and invalid token both can have separate error message for better understanding.

**Comment by RyanTheOptimist** [comment]
CC: @yanavlasov @zuercher

**Comment by zuercher** [comment]
Presuming that this is a local reply generated by Envoy's jwt_authn filter, some kinds of modifications can be made with  [local_reply_config](https://www.envoyproxy.io/docs/envoy/v1.29.3/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-local-reply-config). If that's not sufficient, you're left with using some other filter to inspect and modify the response. Possibilities include the lua filter, writing a custom WASM filter, or writing a custom C++ filter.

**Comment by darshak-patel** [comment]
Let's say if response is generated by jwt_auth filter of envoy then it will always set status code as 401 and response body will be based on the fault name such as "Jwt is expired" or "signature is invalid" something like that. My question here is how local_reply_config can understand if the error is "jwt is expired" then go and pick this error format and if error is "invalid signature" go and pick this error message.I know one way is to write lua filter that can extract the body and check if body is this then add this header so local_reply_config filter can do check based on header and status code, but I don't want to go this way because it can add some latency. Is there any other way possible?

**Comment by darshak-patel** [comment]
Anyone can help on this please?
