### ISSUE TITLE
Mobile/Android tests is extremely flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#33429]
This is pretty much permafailing on `main` (and PRs) - afaict its not actually permafailing as i have seen instances where it appears to pass on `/retest`

Either way this fails in the vast majority of runs (currently _all_ on `main`) so i think needs to be addressed

**Comment by phlax** [comment]
cc @abeyad @fredyw

**Comment by phlax** [comment]
Error is:

```console
 E
Time: 1.314
There was 1 failure:
1) successful sending of trailers(test.kotlin.integration.ReceiveTrailersTest)
expected: 0
but was : 1
	at test.kotlin.integration.ReceiveTrailersTest.successful sending of trailers(ReceiveTrailersTest.kt:96)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2024-04-10 00:35:09 --
```

https://github.com/envoyproxy/envoy/actions/runs/8624059511/job/23638413480#step:8:768

**Comment by fredyw** [comment]
I'll take a look.
