### ISSUE TITLE
ci/do_ci.sh reports an error when /bin/bash version less than 4.0

### ISSUE THREAD

**Issue by xocodergit** [envoyproxy/envoy#33426]
*Title*: 
`ci/do_ci.sh` reports an error when /bin/bash version less than 4.0

*Description*:
`ci/do_ci.sh` reports an error when /bin/bash version less than 4.0 since `;&` is available in versions higher than Bash 4.0
```bash
$ NUM_CPUS=9 ./ci/do_ci.sh  api.go
ENVOY_SRCDIR=/Users/zehuan.szh/work/code/asm-dep/envoy
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=arm64
BUILD_DIR not set - defaulting to ~/.cache/envoy-bazel
Setting test_tmpdir to /Users/zehuan.szh/.cache/envoy-bazel/tmp.
LLVM_ROOT not found, not setting up llvm.
Skip setting up Envoy Filter Example.
building using 9 CPUs
building for arm64
CI_TARGET=api.go
./ci/do_ci.sh: line 285: syntax error near unexpected token `;'
```
which is pointed this line:
```bash
        ...
              -c fastbuild @envoy_api//envoy/...
        if [[ -n "$ENVOY_API_ONLY" ]]; then
            exit 0
        fi  
        ;& <----- the ;& is available after bash 4.0.

    api.go)
        setup_clang_toolchain
        GO_IMPORT_BASE="github.com/envoyproxy/go-control-plane"
        GO_TARGETS=(@envoy_api//...)
        ...
```

*Repro steps*:
This problem is easy to reproduce on Mac OS. As of MacOS 14.4, the version of /bin/bash is 3.2.57.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

If this should be fixed, I'd happy to take it.

**Comment by phlax** [comment]
> If this should be fixed, I'd happy to take it.

not sure about this - i would rather not remove the switch fallthrough

afaict macos will never update the bash version as they are not allowed to by license, and i definitely dont think we want to restrict all bash usage to a very old bash version, when by far the majority of usage is on linux

what should work and is the canonically supported way to use the ci functions is to build using the Docker build container - ie `./ci/run_envoy_docker.sh` - not a mac user so not 100% but i believe that should work as expected across platforms.

our mac ci - ie which runs on the host - avoids this problem by not calling `do_ci.sh` and issuing bazel commands directly

**Comment by phlax** [comment]
thinking further on this and doing a little research - i think the fix here is documentation

you can install a newer (ie supported with bug fixes) version of bash using brew afaict - if anything i think documenting that would be the "fix"

**Comment by xocodergit** [comment]
> > If this should be fixed, I'd happy to take it.
> 
> not sure about this - i would rather not remove the switch fallthrough
> 
> afaict macos will never update the bash version as they are not allowed to by license, and i definitely dont think we want to restrict all bash usage to a very old bash version, when by far the majority of usage is on linux
> 
> what should work and is the canonically supported way to use the ci functions is to build using the Docker build container - ie `./ci/run_envoy_docker.sh` - not a mac user so not 100% but i believe that should work as expected across platforms.
> 
> our mac ci - ie which runs on the host - avoids this problem by not calling `do_ci.sh` and issuing bazel commands directly

I agree with your point of view, Linux is indeed the main usage scenario. And there is really no need to be compatible with an older version of Bash. But many developers do use MacOS for development work, and I thought it might make the process smoother if we added a "wrapper" to call the actual logic. Its logic might look like: Try using /bin/ bash to execute, if its version is too low, an error will be reported and a document link will be given.

**Comment by phlax** [comment]
not sure where we would put such a wrapper - but open to suggestions on this

does using the build container work - that is the supported CI path?

as said above i think the fix is that if you want to run on a macos host with no containers then you need to update your bash version

**Comment by xocodergit** [comment]
> not sure where we would put such a wrapper - but open to suggestions on this

we can add a script maybe called `ci.sh`, its content may looks like:
```
#!/bin/bash

# Step 1: Define DEFAULT_SHELL with a default value if it's not set
DEFAULT_SHELL="${DEFAULT_SHELL:-/bin/bash}"

# Check if $DEFAULT_SHELL actually exists and is executable
if [ ! -x "$DEFAULT_SHELL" ]; then
    echo "Error: $DEFAULT_SHELL does not exist or is not executable."
    exit 1
fi

# Check if the DEFAULT_SHELL points to bash explicitly
if [[ "$DEFAULT_SHELL" == */bash ]]; then
    # Step 2: Check the version of DEFAULT_SHELL if it's bash
    SHELL_VERSION=$("$DEFAULT_SHELL" --version | grep -o '[0-9]\+\.[0-9]\+' | head -1)
    MAJOR_VERSION=$(echo $SHELL_VERSION | cut -d. -f1)

    if [ "$MAJOR_VERSION" -lt 4 ]; then
        echo "Your bash version is $SHELL_VERSION. A version >= 4.0 is required."
        exit 1
    fi
else
    echo "Note: DEFAULT_SHELL is not bash. Skipping version check."
fi

# Step 3: Use DEFAULT_SHELL to execute ci/do_ci.sh with all current script's parameters
"$DEFAULT_SHELL" ci/do_ci.sh "$@"

# Use "$@" to pass all the arguments received by the current script to the ci/do_ci.sh

```

> does using the build container work - that is the supported CI path?

Using a build container is indeed a good way to prevent compatibility problems. However, there are scenarios where build containers may not be suitable:
- For well-known reasons, Chinese developers cannot access some dependencies from websites like *.google.com, among others. Even though many developers use VPNs to let their PCs bypass the Great Firewall, many VPNs won't proxy the traffic out from the containers. Therefore, building on the host is the easiest way to start development on Envoy for them.
- Although building and running Envoy in a build container is not a problem for someone who isn't bothered by network issues, containers running on Docker for MacOS are unable to connect from the host. This can make local testing somewhat annoying.

> as said above i think the fix is that if you want to run on a macos host with no containers then you need to update your bash version

Exactly, but on the M1 Mac, after running brew install bash, the binary will be placed in /opt/homebrew/Cellar/bash/5.2.26/bin/bash rather than replacing /bin/bash. but our script always claims the explainer explicit by `#/bin/bash`. (not sure if there is a way to inplace update the /bin/bash)

**Comment by phlax** [comment]
> (not sure if there is a way to inplace update the /bin/bash)

yep, replacing `/bin/bash` with `/bin/env bash`


re ci.sh - that would be my least favourit option - it wouldnt be tested in ci (despite the name) and would add considerable maintenance overhead - esp given it wasnt tested

**Comment by xocodergit** [comment]
> > (not sure if there is a way to inplace update the /bin/bash)
> 
> yep, replacing `/bin/bash` with `/usr/bin/env bash`

I'd say this is indeed a graceful approach. It will allow the script to run according to which bash. 

> re ci.sh - that would be my least favourit option - it wouldnt be tested in ci (despite the name) and would add considerable maintenance overhead - esp given it wasnt tested

that make sense.

**Comment by phlax** [comment]
@xocodergit if you want to raise a PR to update occurrences of `#!/bin/bash` in repo scripts i would be happy to review

there are quite a few - they can be found with:

```console
$ git grep -E '^#!/bin/bash' -- ":(exclude).azure*"  ":(exclude)examples"
```

i guess its mostly the ones in `ci/` that are required to allow `do_ci.sh` to work - perhaps also `bazel/` 

what wont work out of the box is any bash flags - so ...

```bash
#!/bin/bash -e
```

would need to be converted to

```bash
#!/usr/bin/env bash

set -e
```
