### ISSUE TITLE
Allow filters to write through downstream filters only

### ISSUE THREAD

**Issue by alanconway** [envoyproxy/envoy#3343]
*Title*:  Allow filters to write through downstream filters only

*Description*:

A  Network::Filter that does protocol translation can intercept and replace  data going up or down stream in onData and onWrite. However sometimes onData may need to write downstream, e.g. to respond to a downstream event that is not reflected in the upstream protocol. Also the filter may need to write timer-based downstream heartbeats that are independent of the upstream protocol. 

The existing Connection::write() function goes through the entire write filter chain , starting at the top and including the current filter. This is not what we want - we only want the write to be seen by filters downstream of the current one.

> On Sat, May 5, 2018 at 12:19 PM, Matt Klein <mklein@lyft.com> wrote:
> 
> The correct solution here is to add functionality to the network filter callbacks to perform writes. You can model this after how HTTP filters work when encoding headers, data, etc.
> 
> I.e., in https://github.com/envoyproxy/envoy/blob/master/include/envoy/network/filter.h you will need to add write() to ReadFilterCallbacks, and you might need to add WriteFilterCallbacks, with a write function. Optimally, the Connection accessor would be made constant, so any modifiers to the connection need to operate through the callbacks which can handle filter iteration. This will be a bit of work, but not too terrible.
> 
> 

*Relevant Links*: motivated by https://github.com/alanconway/envoy-amqp/

**Comment by ggreenway** [comment]
One possible generalization of the idea is to have queues between each filter (in both directions).  I can imagine something like having the gzip filter and a protocol translation filter both in a chain, and when either filter has enough data, it should be able to pass what it has to the next filter in the chain.

**Comment by alanconway** [comment]
From an API perspective I was thinking to leave onRead() and onWrite() as the way filters communicate but to provide a way to "manufacture" read/write events that are only visible to  up- or down-stream filters.
I only care about write but it makes sense to be symmetric.

As to implementation I'm not sure if we need some form of queue between filters or just a way to find the right place in the existing filter chain to start propagating the event.

**Comment by mattklein123** [comment]
@alanconway per the convo we had on envoy-dev, I think you want to mimic how we do things in the HTTP filter chain which takes into account which filter is actually making the call through the callbacks provided by the filter manager. I think we want to add a write() function into the callbacks provided to the filters, which can then be used to perform writes correctly through the filter chain. This was why I also recommended making networking filters also have only a const Network::Connection, so that all modifying operations have to occur through callback API functions. 

Let me know if this makes sense or you need me to provide more pointers.

**Comment by alanconway** [comment]
It makes sense in theory, I have yet to dig into the details.

**Comment by mattklein123** [comment]
Calling this fixed via https://github.com/envoyproxy/envoy/pull/6750
