### ISSUE TITLE
ConsistentHashing: provide use_hostname_for_hashing for eds based discovery.

### ISSUE THREAD

**Issue by fcantournet** [envoyproxy/envoy#33430]
To achieve stable consistent hashing over endpoints in ringhash/maglev when using EDS we need something similar to use_hostname_for_hashing.

In e.g: kubernetes using statefulsets you have endpoints with a stable identity, but whose IP might change during rollouts.

If you use `use_hostname_for_hashing` and STRICT_DNS with the records for each endpoint you can achieve stable consistent hashing during rollouts, with minimal re-shuffling.

Can we make `use_hostname_for_hashing` work with EDS by using the `hostname` field of Endpoint ?

**Comment by RyanTheOptimist** [comment]
cc: @htuch @mattklein123 

It looks like the eds cluster is currently unowned according to CODEOWNERS.md:
`/*/extensions/clusters/eds/ @UNOWNED @UNOWNED`
But perhaps that just needs to be updated?

**Comment by htuch** [comment]
@adisuissa
