### ISSUE TITLE
Better handling hot restart failure

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#33446]
*Description*:

Envoy hot restart works most of the time, but the hot restart attempt would be rejected if the parent is not fully initialized.

The current implentation is, 
the child [mutates the parent's initialization state flag to not-initialized](https://github.com/envoyproxy/envoy/blob/8f0e1eaaf30964080da754ae052cc428c17c5087/source/server/hot_restart_impl.cc#L73-L82), and 
[reset to intialized after child is ready](https://github.com/envoyproxy/envoy/blob/8f0e1eaaf30964080da754ae052cc428c17c5087/source/server/hot_restart_impl.cc#L111-L115).

However, if the child exits early, e.g. terminated before the child is fully ready,
the parent state stucks in "not-initialized" forever, 

**and all the following hot restart attempt would fail.**

What do you think if we more aggressively restore the parent's ready state?
For example, if the child envoy exit gracefully (and more safe considtions), restore the parent state to the initialized.

**Comment by RyanTheOptimist** [comment]
cc: @ravenblackx @mattklein123

**Comment by ravenblackx** [comment]
This sounds generally desirable to me.
(Also, see https://github.com/envoyproxy/envoy/pull/33216 for an incoming related change.)
