### ISSUE TITLE
Anti-Virus scanning of payload

### ISSUE THREAD

**Issue by arminabf** [envoyproxy/envoy#33469]
**Anti-Virus scanning of request payload**

*Description*:

For requests to be scanned, an outcall to an external serivce should be made and payload to be transfered to the specific endpoint. The data communication between Envoy and external service is either based on ICAP (as generic interface) or based on gRPC (similar to ext_proc).

On virus detection, envoy aborts the request with configurable status code (403, 500) and freely choosable response message (e.g. HTML or JSON document).

**Comment by RyanTheOptimist** [comment]
You could certainly implement a filter to do this. If you'd like to contribute it to Envoy you can find more information about how to contribute here:

https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md
