### ISSUE TITLE
udp: enabling GRO cause performance regression

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#33474]
We observed massive MSG_TRUNC in recvmsg call, causing huge packet loss. 
```
[source/common/network/io_socket_handle_impl.cc:308] Dropping truncated UDP packet with size: 42500. recvmsg called with msghdr: msg_iov {iovec.iov_len = 24000,}, msg_iovlen 1, msg_flags 32, msg_controllen 56, flags 32.
```

Each recvmsg() call is supplied with a 24000B read buffer (~16 packets), which is probably not enough if more than 16 packets with the same network 5-tuple are concatenated by GRO.  It seems that a 64kB read buffer (which is the GRO max read size) is always expected by recvmsg. This is a bit counter intuitive because the caller doesn't know how much concatenated packets to expect but is responsible to supply a big enough buffer.

**Comment by danzh2010** [comment]
@wu-bin

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk @abeyad
