### ISSUE TITLE
Allow using downstream negotiated application protocol with upstream with TcpProxy + Tls

### ISSUE THREAD

**Issue by fedya-at-db** [envoyproxy/envoy#33491]
*Title*: *Allow using downstream negotiated application protocol with upstream with TcpProxy + Tls*

*Description*:
We're trying to use a TcpProxy filter with a TlsContext to do tls proxying, but ran into some difficulty matching downstream and upstream negotiated http protocols via alpn. Some scenarios:
* If downstream and upstream TlsContexts don't set alpn, downstream and upstream may default to using h1 which could be suboptimal.
* If downstream TlsContext sets alpn="h2,http/1.1" and upstream doesn't set one, downstream may choose h2 and upstream may default to h1, giving you protocol mismatch errors.
* If downstream and upstream TlsContexts both set alpn="h2,http/1.1" then if downstream doesn't support h2 and chooses h1, but upstream selects h2 there'll still be protocol mismatch errors.

From what we can tell the right way to fix this is to have 2 filter chains and use the application_protocol filter chain match clause along with the TlsInspector filter, and route to clusters configured with alpn for the matching protocol only. What you present downstream needs to match your server's capabilities as there's no protocol translation possible here, but that's within our control.

On the other hand with http_connection_manager you may set http_protocol_options on a cluster and use the setting [use_downstream_protocol_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#envoy-v3-api-msg-extensions-upstreams-http-v3-httpprotocoloptions-usedownstreamhttpconfig) to allow matching the downstream and upstream protocol. When using the TcpProxy filter however this isn't read (which makes sense), but it would still be useful to allow matching application_protocol negotiated with downstream with what's presented to the upstream via alpn.

Could there be a similar option on [UpstreamTlsContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#envoy-v3-api-msg-extensions-upstreams-http-v3-httpprotocoloptions-usedownstreamhttpconfig) along the lines of `use_downstream_application_protocol`? In theory even the above `use_downstream_protocol_config` could be read if it's set on the cluster, but that may be less clear since alpn is part of TlsContext config.

cc @agrawroh

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk @zuercher @ggreenway

**Comment by alyssawilk** [comment]
I think having an option to propagate ALPN makes total sense.  I'd go so far as to say I'd be fine defaulting that behavior on if there's both downstream and upstream TLS for tcp proxy and runtime guarding (and only adding a knob if someone doesn't want it) but that might be worth a second opinion (cc @RyanTheOptimist @ggreenway )

**Comment by RyanTheOptimist** [comment]
Sounds reasonable to me!

**Comment by ggreenway** [comment]
Sounds good to me
