### ISSUE TITLE
Envoy 1.23.12 restarts due to OOM when clusters exceed 6K

### ISSUE THREAD

**Issue by sridharjprakasam** [envoyproxy/envoy#33509]
*Title*: *Envoy 1.23.12 restarts due to OOM when clusters exceed 6K*

*Description*:
Envoy 1.23.12 running with 4GB RAM with a upstream cluster size of ~6K frequently restarts due to OOM.
Increased memory from 4GB to 8GB but still envoy couldn't hold long.

This issue was observed more recently where upstream cluster size exceeded 5K.
Overflow and reset counters looks normal.
Is there any known memory leak that is identified in 1.23.12 version or any limitations on number of upstream clusters envoy can handle.

Any help is appreciated.

**Comment by adisuissa** [comment]
I'm not aware of anything.
Can you provide more details on what is the configuration that is being used?
Will it be possible to get a heap-dump before the OOM?

**Comment by sridharjprakasam** [comment]
envoy connects to a GRPC service that generates & supplies routing resources via xDS.
Increased memory to 12GB and envoy seems to be running fine for past 4 days without any OOM with an upstream cluster count of >6K

1.23.12 version doesn't have a /heap_dump endpoint on admin interface, doc suggests to build a custom version from envoy source with tcmalloc.
Is there a variant of 1.23.12 built with tcmalloc available already to leverage for heap dump

**Comment by phlax** [comment]
@sridharjprakasam 1.23.x is no longer supported and hasnt been for some time - could you test if the issue you are seeing is still present in any of the currently supported versions
