### ISSUE TITLE
Expose metrics per vhost

### ISSUE THREAD

**Issue by stevesloka** [envoyproxy/envoy#3351]
*Title*:  Expose metrics such as latency & rps by VHost

*Description*:
I am looking for a way to visualize metrics by VHost or Route. Currently, they are exposed per cluster.  I did a quick ask in Slack and found that other users are parsing through the access logs and deriving this information from them. I'd prefer to see if there's a way to have them come through the included metrics mechanism that exists today. 

I'm curious if anyone has similar needs in their environments, what places in the code would need to be touched, and if I could help possibly implement a PR.

**Comment by mattklein123** [comment]
This comes up occasionally. The reason we don't do this by default is cardinality explosion. The closest thing we have today to this feature is "virtual clusters": https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-virtualcluster

That might be good enough for what you need.

I don't have any objections to metrics per vhost or per route, but I think it needs to be opt-in so users can control their own cardinality. This would like be an option on both the vhost/route as to whether dynamic stats should be emitted. It would be a pretty straightforward change.

**Comment by ggreenway** [comment]
Also, when SNI is finished (PR in progress right now), if you setup your config such that there is a virtual-listener per vhost (instead of defining vhosts in the http-conn-manager), you'll get stats per vhost. But not per route.

**Comment by stevesloka** [comment]
Thanks @mattklein123 & @ggreenway, going to look through those options and see if we can get the metrics we need.

**Comment by ramaraochavali** [comment]
Virtual clusters seems to be on per header basis. Is it possible to extend it based on path regex?

**Comment by ramaraochavali** [comment]
@mattklein123 This can be closed now
