### ISSUE TITLE
Support annotating stats/metrics with downstream TLS context

### ISSUE THREAD

**Issue by kiambogo** [envoyproxy/envoy#33520]
*Title*: *Support annotating stats/metrics with downstream TLS context*

*Description*:

It would be useful to support the downstream stats/metrics collectors (e.g. `downstream_rq_total`) to offer TLS context as a label, allowing the counters to be labeled with information about the downstream client/caller. A usecase of this is being able to monitor traffic/load on a client-level through metrics directly from Envoy instead of needing to pass client identity information to the upstream to handle this. 

I suspect that the label value can be made configurable to work off different parts of the TLS context, similar to the way that logging supports it:
`%DOWNSTREAM_PEER_URI_SAN%`: use the URI SAN as the label value
`%DOWNSTREAM_PEER_SUBJECT%`: use the CN as the label value

Metric cardinality may be a concern, but this can and should be left up to the operator to manage. A logical default (no client/TLS context information present in the metrics) can safeguard from tripping up those who do not desire this functionality. 

Example of Prometheus metric produced today:
```
envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix="ingress_https"} 0
```

Example of desired metric, including TLS context:
```
envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix="ingress_https", downstream_tls="foo.bar"} 0
```
In this example, a downstream client with a TLS context containing `foo.bar` (whether as the CN, SAN, URI, etc..) made a request to the `ingress_https` connection manager.

**Comment by jmarantz** [comment]
Would this suggestion mean that a new stat will be added that includes a name controlled by clients? That's what it seems like. That would need to be a config-controlled option, not on by default.

**Comment by kiambogo** [comment]
> Would this suggestion mean that a new stat will be added that includes a name controlled by clients?

I was thinking that this would be a label on the existing stats (from a Prometheus perspective -- not sure what this would look like for other stats), rather than an unique stat for each name controlled be a client. 

Agreed that this makes most sense to be enabled through a config-controlled option and not on by default, especially that this could cause a large stat/metric cardinality and could cause problems if folks are not expecting it when upgrading Envoy.

**Comment by jmarantz** [comment]
A new label in Prom means a new stat in Envoy. So this is something you would really only want when debugging, or if clients are trusted.

**Comment by kiambogo** [comment]
> A new label in Prom means a new stat in Envoy. So this is something you would really only want when debugging, or if clients are trusted

Got it. 

Agreed on that front. My usecase is mostly understanding peer-to-peer request volume within a closed network of hundreds of services (what is the identity of clients making requests at what volume). In this scenario clients can be considered trusted.

**Comment by kiambogo** [comment]
Could we have this labelled as "help wanted" or "no stalebot" to keep this opened?
