### ISSUE TITLE
support proxy protocol v2

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#3352]
Envoy currently supports PROXY protocol v1. The AWS NLB product only supports sending PROXY protocol v2. v2 is a binary format, v1 was human readable.

**Comment by ungureanuvladvictor** [comment]
@mattklein123 is still something you are looking to track long term?

**Comment by mattklein123** [comment]
@ungureanuvladvictor this was already implemented in https://github.com/envoyproxy/envoy/pull/3668

**Comment by ungureanuvladvictor** [comment]
Oh, missed that one. Will take a look at it.
