### ISSUE TITLE
File based buf slice: is it possible?

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#33538]
I experimented resetting memory heavy connection on TcpProxy described in https://github.com/envoyproxy/envoy/issues/32900
This does not work in all types of connections. Some workload are in the cycle of recreating long connections and be reset.

One of the alternative approach is to temporarily store the in memory buf in file until during high memory pressure. 

```
class Slice {
public:
  using Reservation = RawSlice;
 
 struct SizedStorage {
    astd::unique_ptr<uint8_t[]>  mem_{};
    size_t len_{};
  };
}
```

After a quick exploration of Buffer::Slice, I find that the internal implementation of storage is  in memory `std::unique_ptr<uint8_t[]>;`,
but the majority use cases are either copying to or from this heap spaces instead of referring a pointer to any range within.

If we can sort out the usage of `mem_`, I think it should be possible to store `mem_` in a file on high memory presure 
and load to heap when accessing it.

Was there a discussion on this topic? Thanks.

**Comment by adisuissa** [comment]
cc @yanavlasov
