### ISSUE TITLE
ads: nonce is ignored when empty response arrives, resulting in a 503 responses.

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy#3355]
When running gloo's integration tests, we noticed an issues that seems to be ADS related. (i was able to reduce it to a consistently failing e2e test,  here https://github.com/solo-io/gloo/blob/per-role-config/test/local_e2e/eds.go#L119)

It seems that an ADS Request is ignored. I believe that this is the scenario that causes it:
1. Cluster with EDS is added (envoy is synced with Cluster and ClusterLoadAssignment)
2. Cluster with EDS is removed
3. At this point:
3.1 go-control-plane sends a DiscoverResponse with the new ClusterLoadAssignment that has an empty list. 
3.2 in Envoy (probably because the cluster is removed already) there are no watchers for this response and it is ignored.
3.3 Envoy does *not* update the nonce to the nonce from the response.
4. A new cluster with EDS is added
5. go-control-plane updates envoy on the new cluster
6. Envoy sends a ClusterLoadAssignment discovery request with the cluster name.
7. request is *ignored* by go-control-plane as it thinks it is a stale nonce (as described here: https://github.com/envoyproxy/envoy/blob/master/api/XDS_PROTOCOL.md#resource-updates).
8. Since there is no EDS response the cluster 'warm-up' is never finished and is not available. all requests to that cluster return 503.

Note: I am not sure why, I only got this to reproduce when another non-eds cluster was added as well.

To fix this, I made the following patch, Where I update the nonce regardless if the resource list is empty:
https://github.com/yuval-k/envoy/commit/340a2652c439087e0e40e931015d3f2cca5412a2
(docker image is also available)

Before opening a PR and adding tests, I wanted to make sure with everyone that this is indeed the right solution. and maybe get some more insights about whats the best approach here.

Happy to provide more information as needed, as I have a consistently reproducing test locally.

**Comment by htuch** [comment]
Thanks for the bug report @yuval-k. I agree this is broken and your patch gets us towards a solution. If you can open a PR with what you have there, I'll leave some comments; I think we should also be sending a NACK and an error message back to the management server in some of the other branches (including the ones you call out).

**Comment by yuval-k** [comment]
@htuch I'm not sure how to add a unit test, as I need to check the state of `api_state_` (the variables that contains the nonce) which is private in GrpcMuxImpl. What's the best practice here? make the test class a friend? or create a const getter?

**Comment by htuch** [comment]
https://github.com/envoyproxy/envoy/blob/master/test/common/config/grpc_mux_impl_test.cc already expects on the resulting `DiscoveryRequest`, which is where the nonce should be present. I think that's a totally reasonable granularity to add the test at.
