### ISSUE TITLE
Add optional support for watching for "Modified" filesystem events

### ISSUE THREAD

**Issue by weissne** [envoyproxy/envoy#33560]
*Title*: *Add optional support for watching for "Modified" filesystem events*

*Description*:
>We have the need to recognize "Modified" filesystem events that are raised when certificates are updated in our monitored "path_config_source" defined for our Secrets configuration (we use "sds_config")
>We would like to do this by setting a new boolean field named "watch_for_modified" inside the config.core.v3.PathConfigSource 
e.g.
message PathConfigSource {
  string path = 1 [(validate.rules).string = {min_len: 1}];
  WatchedDirectory watched_directory = 2;
  **bool watch_for_modified = 3;**
}

The field will be optional and only when set to true will the Modified filesystem event be accepted by the watcher and will trigger it's callback.

**Comment by adisuissa** [comment]
Thanks for your suggestion!
Can you specify which filesystem events that trigger the callback at the moment you are trying to avoid?

**Comment by weissne** [comment]
Thanks for your response.

Sorry for not clarifying this, but I'm not trying to avoid filesystem events that trigger the callback now.
The idea here is to enable, in addition to the existing "Moved" filesystem event that is watched and triggers a callback, also the watch of "Modified". 
We need this because the "**Modified**" filesystem event is triggered, **instead of "Move"**, when certificates are updated in our monitored "path_config_source" defined for our Secrets, because of the way it's done, which we don't have control over.

**Comment by weissne** [comment]
@adisuissa - Can you please share your thoughts on this following my clarifcation?
I would be happy to implement this if possible.

**Comment by weissne** [comment]
Accidently closed the issue :)
Reopening...
