### ISSUE TITLE
`%CEL` formatting: serialize CelMap values

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#33567]
*Title*: `%CEL` formatting: serialize CelMap values

*Description*:
When serializing structured fields like `%DYNAMIC_METADATA(com.test.my_filter)%`, we will log: `{"test_key": "foo", "test_object": {"inner_key": "bar"}}`

When serializing structured fields in CEL, we get `"CelMap value"`

It would be nice to serialize these as JSON objects instead
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by howardjohn** [comment]
Hmm, it doesn't always happen

```
%CEL(xds.upstream_host_metadata)%
```

results in 

```
"filter_metadata { key: \"envoy.filters.listener.original_dst\" value { fields { key: \"local\" value { string_value: \"10.244.0.47:9080\" } } } } filter_metadata { key: \"envoy.transport_socket_match\" value { fields { key: \"tunnel\" value { string_value: \"http\" } } } } filter_metadata { key: \"istio\" value { fields { key: \"workload\" value { string_value: \"productpage-v1;bookinfo;productpage;v1;Kubernetes\" } } } }"
```

but I guess this is probably not a CelMap value since I cannot extract it (`%CEL(xds.upstream_host_metadata['envoy.filters.listener.original_dst'])%`)

**Comment by adisuissa** [comment]
Seems that CelMap isn't supported.
cc @kyessenov who may have more information here.

**Comment by howardjohn** [comment]
This still happens
