### ISSUE TITLE
Healthcheck connection draining causing CPU spike

### ISSUE THREAD

**Issue by someshsumantwilio** [envoyproxy/envoy#33566]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Healthcheck connection draining causing CPU spike*

*Description*:
We are observing a spike in CPU in our application for certain duration. Screen shot attached. 

We also observed that during the CPU spike, health-check are draining and are recreated. Since health-check uses TLS connection which might cause CPU spike during handshake when health-check are draining and recreated. We verfied that most of the CPU usage is from envoy process.

We checked the [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining) for draining and found below are the scenario when draining can happen.

1. The server is being [hot restarted](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart#arch-overview-hot-restart).

2. The server begins the graceful drain sequence via the [drain_listeners?graceful](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-drain) admin endpoint.

3. The server has been manually health check failed via the [healthcheck/fail](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-healthcheck-fail) admin endpoint. See the [health check filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking-filter) architecture overview for more information.

4. Individual listeners are being modified or removed via [LDS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration#arch-overview-dynamic-config-lds).

We analyzed all the senario and we found none of this is happening to envoy. We are not sure why draining is happening for healthcheck.

1. We verified that envoy is not being restart.
2. We verified that server did not started the drain sequence via admin port because other listener are not draining and only healthcheck connection are draining.
3. We have verified that server did not manually trigger the healthcheck fail.
4. We verified that individual listener are not being modified or removed by checking the timestamp of the envoy started and last updated time in listener. 

None of the above seems to cause the draining the healthcheck connection. We are not sure why the healthcheck connection is getting drain. 

We need help in finding the root cause of draining. 

CPU Spike.
<img width="1418" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/1d7418e6-4068-4323-8679-0b9525a3bf81">

Draining healthcheck connection.
<img width="1417" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/b229430f-fa41-4a79-bea7-e20c152181eb">

Active Healthcheck 
<img width="1420" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/a5f4aa02-b367-4e38-9cab-46592eb93bef">

Total request to healthcheck.
<img width="1421" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/4bead094-205c-4733-9274-eda02f01dd88">

Envoy CPU usage in individual host

<img width="1423" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/40992446-ba99-44ba-92c2-facc9fe24852">

[optional *Relevant Links*:]
[Draining](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining)

**Comment by someshsumantwilio** [comment]
@adisuissa  Please find the screen shot of the CPU profiling.

<img width="1423" alt="image" src="https://github.com/envoyproxy/envoy/assets/129303937/4d92c9c7-4451-4135-b374-5363ae74e8a4">

**Comment by adisuissa** [comment]
Can you please send the health-check configuration you are using?
Also will it be possible to look at the Envoy trace log around the time of the issue?

I wonder if there's a max-connection duration knob somewhere that is set to a default value, but at the moment it is challenging to debug without more info.

**Comment by someshsumantwilio** [comment]
We are using below healthcheck configuration and we have attached the trace log file when the issue is happening.

```
{
          "name": "healthcheck-listener",
          "active_state": {
            "version_info": "HO9f3188be99cbbb0ed9fb440400e5f1ba-20240220.221537",
            "listener": {
              "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
              "name": "healthcheck-listener",
              "address": {
                "socket_address": {
                  "address": "0.0.0.0",
                  "port_value": 17006
                }
              },
              "filter_chains": [
                {
                  "filters": [
                    {
                      "name": "envoy.filters.network.http_connection_manager",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                        "stat_prefix": "healthcheck-listener-stats",
                        "route_config": {
                          "name": "healthcheck-routes",
                          "virtual_hosts": [
                            {
                              "name": "healthcheck",
                              "domains": [
                                "*"
                              ],
                              "routes": [
                                {
                                  "match": {
                                    "path": "/voice-callmetadata-processor-opa"
                                  },
                                  "route": {
                                    "cluster": "healthcheck-voice-callmetadata-processor-opa",
                                    "prefix_rewrite": "/healthcheck",
                                    "timeout": "1s"
                                  }
                                },
                                {
                                  "match": {
                                    "path": "/voice-callmetadata-processor"
                                  },
                                  "route": {
                                    "cluster": "healthcheck-voice-callmetadata-processor",
                                    "prefix_rewrite": "/healthcheck",
                                    "timeout": "1s"
                                  }
                                }
                              ]
                            }
                          ]
                        },
                        "http_filters": [
                          {
                            "name": "envoy.health_check",
                            "typed_config": {
                              "@type": "type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck",
                              "pass_through_mode": true,
                              "cache_time": "1s"
                            }
                          },
                          {
                            "name": "envoy.filters.http.router",
                            "typed_config": {
                              "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                            }
                          }
                        ],
                        "http_protocol_options": {},
                        "access_log": [
                          {
                            "name": "envoy.file_access_log",
                            "typed_config": {
                              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                              "path": "/var/log/twilio/envoy/healthcheck_listener_access.log",
                              "log_format": {
                                "text_format_source": {
                                  "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" \"%REQ(T-Request-Id?I-Twilio-Request-Id):34%\" \"%UPSTREAM_CLUSTER%\"\n"
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ],
                  "transport_socket": {
                    "name": "tls",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
                      "common_tls_context": {
                        "tls_certificate_sds_secret_configs": [
                          {
                            "name": "spiffe://prod.svc.twilio.com/realm/us1/role/voice-callmetadata-processor",
                            "sds_config": {
                              "api_config_source": {
                                "api_type": "GRPC",
                                "grpc_services": [
                                  {
                                    "envoy_grpc": {
                                      "cluster_name": "spire_agent"
                                    }
                                  }
                                ],
                                "rate_limit_settings": {
                                  "max_tokens": 5,
                                  "fill_rate": 4
                                },
                                "transport_api_version": "V3"
                              }
                            }
                          }
                        ]
                      },
                      "require_client_certificate": false
                    }
                  }
                }
              ],
              "listener_filters": [
                {
                  "name": "envoy.filters.listener.tls_inspector",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
                  }
                }
              ]
            },
            "last_updated": "2024-02-20T22:15:37.656Z"
          }
        },
        ```
        
   
[envoy_trace.tar.gz](https://github.com/envoyproxy/envoy/files/15378311/envoy_trace.tar.gz)

**Comment by someshsumantwilio** [comment]
Do we have any update on issue?

**Comment by someshsumantwilio** [comment]
Do we have any update on issue?

**Comment by adisuissa** [comment]
A CPU profile will help in understanding which functions are spending the most time during that spike.
At the moment I don't have the bandwidth to run this with the same config that you have provided.

FWIW, the trace logs are quite large, and it is unclear when there was a spike in CPU usage.
Please try to look at what's happening just before the spike occurs (e.g., were there connections that got dropped, was there some timeout that happened just before the spike started).

**Comment by someshsumantwilio** [comment]
@adisuissa At this point we know why we have a CPU spike. We are having a CPY spike because we have a lot of healthcheck draining. We are trying to understand why and wanted to check if you can help us in figuring out why we have heathcheck draining which is causing CPU spike. 

We checked the [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining) for draining and found below are the scenario when draining can happen but none of this is occuring in our service mesh. 

The server is being [hot restarted](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart#arch-overview-hot-restart).

The server begins the graceful drain sequence via the [drain_listeners?graceful](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-drain) admin endpoint.

The server has been manually health check failed via the [healthcheck/fail](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-healthcheck-fail) admin endpoint. See the [health check filter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking-filter) architecture overview for more information.

Individual listeners are being modified or removed via [LDS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration#arch-overview-dynamic-config-lds).

![image](https://github.com/user-attachments/assets/abe98f09-8a06-45d4-acc4-19a995ecb61c)
![image](https://github.com/user-attachments/assets/876ed45b-8fb1-4ea9-8b85-99707ea957f9)
