### ISSUE TITLE
`%CEL` formatting cannot call functions due to overly restrictive regex 

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#33569]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: `%CEL` formatting cannot call functions due to overly restrictive regex 

*Description*:
Access log formats are validated against this regex: https://github.com/envoyproxy/envoy/blob/0f5c22c6caa5ee6f1bf06ee1a76874af52976050/source/common/formatter/substitution_formatter.cc#L40

This does not permit `%CEL(size(upstream))%`, or other CEL expressions with `)` in them. These should be allowed

**Comment by adisuissa** [comment]
Thanks for reporting this!
cc @wbpcode @kyessenov

**Comment by kyessenov** [comment]
CC @zirain 
The fix needs to escape parenthesis I think inside `%CEL(...)%`.
