### ISSUE TITLE
UriTemplateMatcher requires trailing slash for zero path segment matches

### ISSUE THREAD

**Issue by jaellio** [envoyproxy/envoy#33571]
*Title*:  UriTemplateMatcher requires trailing slash for path match

*Description*:

When setting the uri template to `/foo/bar/**` I would expect the path `/foo/bar` to match without a trailing slash. [As defined](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/match/uri_template/v3/uri_template_match.proto#extensions-path-match-uri-template-v3-uritemplatematchconfig), `**` matches 0 or more path segments. The matcher is expecting a trailing slash on the matching path when  `**` is the last operator and segment in the template. `/foo/bar` is not considered a valid path match but `/foo/bar/` is considered valid.

*Repro steps*:

I added the following tests to `test/extentions/path/match/uri_template/library_test.cc` on main to confirm my findings.

```cc
TEST(MatchTest, TestTextGlob) {
  const std::string yaml_string = R"EOF(
      name: envoy.path.match.uri_template.uri_template_matcher
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
        path_template: "/bar/buzz/**"
)EOF";

  Router::PathMatcherSharedPtr matcher = createMatcherFromYaml(yaml_string);
  EXPECT_EQ(matcher->uriTemplate(), "/bar/buzz/**");
  EXPECT_EQ(matcher->name(), "envoy.path.match.uri_template.uri_template_matcher");

  EXPECT_TRUE(matcher->match("/bar/buzz/")); // passes
  EXPECT_TRUE(matcher->match("/bar/buzz")); // fails
}
```

**Comment by adisuissa** [comment]
Thanks for reporting!
cc @alyssawilk @yanjunxiang-google as codeowners

**Comment by jaellio** [comment]
I think I was incorrect, and this is the expected behavior. `/allow/admin` and `/allow/admin/` are two different resources. Therefore, the user would need two different template rules to allow access to both of those resources. Please correct me if I am wrong! Closing for now!
