### ISSUE TITLE
enhancement: oauth2 filter supports retries to improve communication stability with OAuth2 severs

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#33572]
*Title*: *enhancement: oauth2 filter supports retries to improve communication stability with OAuth2 severs*

*Description*:
EG user reported: we are frequently seeing routes hosted by the Gateway fail with a 401, returning an error OAuth flow failed.. Looking at the logs it seems this occurs where Envoy decides to re-use an existing long-lived connection to our OIDC issuer. Failures seem to correlate with Envoy picking connections that are in the order of 50 minutes old.

Allowing retries after failing to send requests to OAuth2 server can solve this problem.

[optional *Relevant Links*:]
EG issue: https://github.com/envoyproxy/gateway/issues/3178

**Comment by adisuissa** [comment]
cc @derekargueta @mattklein123 as codeowners

**Comment by zhaohuabing** [comment]
@derekargueta I found some similar issues. They're not from the Oauth filter but I think they're still valid.
https://github.com/envoyproxy/envoy/issues/14981
https://github.com/istio/istio/issues/47037

**Comment by derekargueta** [comment]
@zhaohuabing are you still planning on providing a PR for this issue?

**Comment by zhaohuabing** [comment]
@derekargueta yes, please assign it to me. Thanks!

**Comment by zhaohuabing** [comment]
@derekargueta I opened a PR to fix this issue. Could you please help reopen it?
