### ISSUE TITLE
[wasm][wamr] Enable WAMR jit.  And bring llvm back?

### ISSUE THREAD

**Issue by lum1n0us** [envoyproxy/envoy#33591]
WAMR is planning to enable aot/jit mode which have already been implemented in [proxy-wasm-host](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/bazel/external/wamr.BUILD). Current interpreter mode will be replaced (to minimize maintenance).

And I noticed there are some issues, https://github.com/envoyproxy/envoy/pull/32872, are discussing using pre-compiled llvm binaries. I am wondering if WAMR has to switch to pre-compiled llvm binaries on system or keep using local compiled llvm libraries?

**Comment by adisuissa** [comment]
@kyessenov @mpwarres maybe you can provide some insights.

**Comment by phlax** [comment]
@lum1n0us i removed wavm (on advice) and with it the llvm compile - this has sped up our CI considerably

if we bring back the wavm build/tests i would ask that we avoid compiling llvm - even downloading it takes a lot of time as its large, and we have the same libs already available in the host (preferably we use a hermetic llvm but we dont have that set up atm)

**Comment by mpwarres** [comment]
@phlax I don't think @lum1n0us is suggesting bringing back wavm, this is about WAMR, which is a separate Wasm runtime, but also uses LLVM. But point taken about avoiding the llvm compile.

**Comment by lum1n0us** [comment]
Got it.

**Comment by lum1n0us** [comment]
What if the Wamr required LLVM version is different with system installation？Shall we ask developers and CI to download and install a [llvm release](https://github.com/llvm/llvm-project/releases)？
