### ISSUE TITLE
Add EDS to /config_dump

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#3362]
This is a follow up from https://github.com/envoyproxy/envoy/pull/3340. We should add EDS support also to the config_dump admin endpoint. Some thought needs to be put into how this will be managed given that on its own showing EDS output disjoint from cluster output is not that useful. If a cluster is an EDS cluster, should we dump the EDS configuration as a nested item in the cluster output?

Note that host information is available in the /clusters endpoint which is why this was not implemented with as high of an urgency.

**Comment by hennna** [comment]
@htuch looks like there is an existing issue regarding eds config dump. mattklein123@ I was looking into getting a dump of effective eds weights but it seems that the /clusters endpoint dumps the endpoint weight. What would it take to get more eds info into the /clusters endpoint?

**Comment by htuch** [comment]
I've had other folks ask for this as well. Would be great to get someone to take on this work.

I think even disjoint from cluster, there is some value here.

**Comment by mattklein123** [comment]
Agreed we should fix this and get EDS into config_dump. @hennna do you want to pick this up?

**Comment by hennna** [comment]
It doesn't look like there's much time in the coming weeks. But are there parts of the code I can familiarize myself with to see how much work is involved?

**Comment by hennna** [comment]
We also may be able to dump this information in the control plane.

**Comment by mattklein123** [comment]
@hennna take a look at `ConfigTracker` and its use around the code base for allowing dumping of RDS, etc. When I originally opened this issue, I think was concerned about EDS being disjoint from CDS, but TBH, I don't think it matters as the `cluster_name` is embedded in the EDS/CLA response. I think "all you need to do" is just plumb the right tracker into the EDS machinery and then allow dumping.

**Comment by HeathLee** [comment]
Any update on the progress?

**Comment by htuch** [comment]
@Rainton will be working on this over the summer.

**Comment by htuch** [comment]
@mattklein123 re: "If a cluster is an EDS cluster, should we dump the EDS configuration as a nested item in the cluster output?"

How about we make EDS standalone `ClusterLoadAssignment` and only do this for EDS clusters in the config dump?

**Comment by mattklein123** [comment]
> How about we make EDS standalone ClusterLoadAssignment and only do this for EDS clusters in the config dump?

Yes see https://github.com/envoyproxy/envoy/issues/3362#issuecomment-562691796. I think we should just do an independent dump here as the dump will have the cluster name, so IMO it's not needed to have it be nested.

**Comment by htuch** [comment]
#11577 implemented this capability.
