### ISSUE TITLE
envoy_reloadable_features_token_passed_entirely deprecation

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#33627]
Your change #28678 (Bugfix issue 27877 jwt token with space is valid) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @danieldradware

**Comment by danieldradware** [comment]
Hi @adisuissa,
So should I delete my code from runtime guard?

**Comment by adisuissa** [comment]
> Hi @adisuissa, So should I delete my code from runtime guard?

Yes, removing the runtime-guard, and the non-used code-paths. Please also add a release note.
