### ISSUE TITLE
gRPC HTTP/1.1 bridge could map gRPC codes to HTTP response codes

### ISSUE THREAD

**Issue by dmateusp** [envoyproxy/envoy#33664]
**gRPC HTTP/1.1 bridge could map gRPC codes to HTTP response codes:** 

Currently the gRPC HTTP/1.1 bridge sets the HTTP response code to 503 for any non-0 gRPC codes, it would be great to use a sensible mapping to HTTP response codes instead.

*Description*:
> [The mapping](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc#L110) in the bridge could be changed to set the HTTP response code based on the mapping you can find in the comments of [googleapis/google/rpc/code.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto) instead of using 503. In our case it would be useful to return these codes for monitoring / logging on our GCP load balancer.

*Relevant Links*
> See [gRPC HTTP bridge docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_http1_bridge_filter#grpc-http-1-1-bridge) "the filter switches the HTTP response code to 503"

**Comment by derekargueta** [comment]
I think this would be a good idea
