### ISSUE TITLE
connections are not uniformly spread across the workers

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#33707]
*Description*:
While the number of data plane connections is low, we observed the cpu load is very imbalanced across workers, i.e., cpu, which bounds the qps to be specific.

During our 1 client 1 host load test with 2 connections and 3 workers:
(a) we have 2 workers are serving in 70% of the experiments, for example 50.87%, 48.98%, 0.12% cpu load for 3 workers
(b) only 1 worker is serving for other 30% of the experiments

While we set another experiments of 17 connections, 3 workers:
here's several samples of cpu loads each workers
- 19, 57, 23
- 28, 40, 31
- 48, 18, 35

Therefore we could see it's more balanced.

The impact of imbalanced distribution is that while we test 1-1 load test on 10k expected qps, we could reach 10k if we got 2 workers but only reach 6k for 1 worker.

One of our work around is to set [max_concurrent_streams](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-max-concurrent-streams) to generate more connections but it escalates the tcp competition. Also consider to limit the lifetime of each connection so we won't stick to an unhealthy connection distribution.

**Comment by zhangbo1882** [comment]
Could you help use the connection balance feature to have a try ?
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto.html#envoy-v3-api-msg-config-listener-v3-listener-connectionbalanceconfig

**Comment by JuniorHsu** [comment]
looks like the only connection balance extension is in `contrib` and depending on hardware. however it's nontrivial to test `contrib` from us and we have heterogeneous hardware so it's not the best time to test now unfortunately :(
