### ISSUE TITLE
Question: How can we defer bootstrap extension to be run after envoy server completely starts?

### ISSUE THREAD

**Issue by ppourali** [envoyproxy/envoy#33708]
*Title*: *Defer bootstrap extension to be run after envoy server completely starts*

*Description*:
I am currently working on creating a [Bootstrap Extension](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-field-config-bootstrap-v3-bootstrap-bootstrap-extensions) which is supposed to be instantiated at Envoy startup time. However, since this Bootstrap extension is heavy (wrt CPU and Memory), I want to first the let the Envoy Server to be Fully initialized and then initialize the bootstrap extension. That is instead of:
```
BootstrapExtension is initialized ...
[main] starting main dispatch loop
```

I want to see:
```
[main] starting main dispatch loop
BootstrapExtension is initialized ...
```
 
Is this possible? If yes, how? e.g., Using some lifecycle notifier callback on the server context (I tried but I think it did not work) or some WaitForEventX.

Thanks,
Parsa

**Comment by ppourali** [comment]
I was expecting this to work, but for some reason it doesn't:
```
server_context_->lifecycleNotifier().registerCallback(Startup, [&] {//Do Something ...;});
```

**Comment by wbpcode** [comment]
You can post the initialization of your extension to the main dispatcher after the `onServerInitialized` is called.

**Comment by ppourali** [comment]
Thanks a lot for your response. This `onServerInitialized` is exactly what I did but I think it is just the logs that are not in order. So can I conclude that `[main] starting main dispatch loop` is not meant to be reflecting the server startup complete state?

**Comment by wbpcode** [comment]
If the main dispatch loop is started, then the server initialization and startup must was completed. Because the start the main dispatch loop is the last step of server startup.

Note `onServerInitialized()` is not executed in the dispatch loop but be executed when the server initialization is near to complete on the main thread.

**Comment by ppourali** [comment]
Got it! All I needed to know was that if the `listeners` and `clusters` are already loaded on the `onServerInitialized` or should I strictly wait for the `starting main dispatch loop`. Based on your response, I conclude that when `onServerInitialized` is happening the `listeners` and `cluster` are ready to handle requests.

Thanks.

**Comment by ppourali** [comment]
Thanks @wbpcode 
Sorry I am still having some issue with this. Based on your reply above:
> You can post the initialization of your extension to the main dispatcher after the `onServerInitialized` is called.

how can I defer the initialization of the extension to main dispatcher or more strictly how can I defer the initialization of my extension to be the very last step (even after main dispatch loop is started?) ?

**Comment by wbpcode** [comment]
When the onServerInitialized is calling, you can call the post() method of the main dispatcher to post the actual initialization logic to the event loop.

Then when the main dispatcher is started. The posted logic will be executed.

**Comment by ppourali** [comment]
Nice, this is what I did:
```
  server_context_->mainThreadDispatcher().post([this] {
// some code to be deferred using post.
}
```

Thanks for the help.
