### ISSUE TITLE
tls: add histogram measuring ssl negotiation latency

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#33705]
*Title*: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#tls-statistics has no latency histograms, and they would be helpful for debugging connection latency issues.

I'd like to hear if, when addressing this bug, there are a few other counters/histograms we should add.

**Comment by kyessenov** [comment]
This issue probably subsumes https://github.com/envoyproxy/envoy/issues/33608
