### ISSUE TITLE
Failed to load MI Debugger

### ISSUE THREAD

**Issue by ShenFeng312** [envoyproxy/envoy#33717]
I'm trying to debug envoy using VSCode but I'm getting the following error
![image](https://github.com/envoyproxy/envoy/assets/49786112/56119b46-7a05-4485-861c-9eabaf127ed2)

**Comment by ShenFeng312** [comment]
Failed to load MI Debugger:Dwarf Error: wrong unit_type in
compilation unit header (is DW_UT_split_compile (0x05), should be DW_UT_type (0x02)) [in module/build/.cache/bazel/_bazel_vscode/-2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/bazel-out/k8- dbg/bin/source/exe/_objs/envoy_main_entry_lib/main.pic.dwo](from file-exec-and-symbols "/build/.cache/bazel/_bazel_vscode/-2d35de14639eaad1ac7060a4dd7e3351/execroot/envoy/bazel-out/k8- dbg/bin/source/exe/envoy-static")

**Comment by ShenFeng312** [comment]
How can I fix this error?

**Comment by ShenFeng312** [comment]
![image](https://github.com/envoyproxy/envoy/assets/49786112/11ac7df5-b5cd-4b48-ba11-9145625fc819)

**Comment by wbpcode** [comment]
could you try the lldb? Seems that the current build flags is not friendly to the gdb.

**Comment by wbpcode** [comment]
cc @phlax

**Comment by ShenFeng312** [comment]
> could you try the lldb? Seems that the current build flags is not friendly to the gdb.

I tried debugging with lldb, but it causes a spike in my Docker CPU usage, eventually leading to unresponsiveness in Docker.

**Comment by wufanqqfsc** [comment]
Seems it works in our local env.

1.VScode configuration:
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Envoy",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/bazel-bin/source/exe/envoy-static",
      "args": ["-c", "path/to/your/envoy.yaml"],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}

2.Make sure GDB was installed on your host.
I faced the same "MIDebuggerPath" issue. But after re-install the gdb , vscode debug works well.

**Comment by ShenFeng312** [comment]
![image](https://github.com/envoyproxy/envoy/assets/49786112/9edab444-4a3a-443a-97cb-e31ec5289cb4)

> gcc version could be a factor (from reading this https://sourceware.org/bugzilla/show_bug.cgi?id=27354)
> 
> what version are you testing with? is it >= 11.1 ? is it the gcc in the envoy build container - which i think is 11.4?

![image](https://github.com/envoyproxy/envoy/assets/49786112/729cae14-be10-4e6c-a52a-b7e39bdc6c1b)

**Comment by phlax** [comment]
>  However, this image is provided by Envoy.

i suspect you need to rebuild your vscode env or similar - the current Envoy image contains gcc 11.4

**Comment by ShenFeng312** [comment]
![image](https://github.com/envoyproxy/envoy/assets/49786112/6f365da5-c565-468d-b270-158d214e893b)
![image](https://github.com/envoyproxy/envoy/assets/49786112/b6d8f122-9a88-4d4d-99e9-cb53aa000e41)
After upgrading gdb to 11.2, this issue has been resolved. Thanks everyone for your help.
@phlax @wbpcode @wufanqqfsc

**Comment by shulin-sq** [comment]
@ShenFeng312 by any chance can you share how you got gdb 11.2? I am unable to upgrade to it via apt-get

perhaps the dockerfile should be updated?
