### ISSUE TITLE
Envoy filter to intercept and inspect gRPC messages

### ISSUE THREAD

**Issue by MichelSkr** [envoyproxy/envoy#33732]
Envoy inspect grpc message and route based on extracted field

Hello Team, 

I have a scenario where a client sends  grpc messages to a server through envoy that acts as a router/load balancer.

client -- grpc--> envoy router --grpc--> server

I want envoy to intercept the grpc message,  retrieve a field from the grpc message and route based on that field.

Is there a way/filter to achieve this?

**Comment by tonya11en** [comment]
You'll likely want to do something like:

1. Use the [gRPC field extraction filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_field_extraction/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-grpc-field-extraction-v3-grpcfieldextractionconfig) to pull out the field and put it in the dynamic metadata for the request.
2. Configure your routes to match on [dynamic_metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_field_extraction/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-grpc-field-extraction-v3-grpcfieldextractionconfig).

**Comment by MichelSkr** [comment]
@tonya11en  thanks for the suggestion.
I used the grpc_field_extraction filter and I can extract the needed field as can be seen from my log files 

`injected dynamic metadata `envoy.filters.http.grpc_field_extraction` with `fields {
  key: "recognition_init.resources.language"
  value {
    list_value {
      values {
        string_value: "en-US"
      }
    }
  }
}`

I have created a dynamic_metadata under route match as follow

`                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: /nuance.nrc.v1.NRC/
                      grpc: {}
                      dynamic_metadata:
                      - filter: envoy.filters.http.grpc_field_extraction
                        path:
                        - key: recognition_init.resources.language
                        value:
                          list_match:
                            one_of:
                              string_match:
                                exact: "en-US"                       
                    route:
                      cluster: nrc_cluster1`

But my requests never match any route and fail.

`[2024-04-25 23:53:28.838][21][debug][router] [source/common/router/router.cc:452] [Tags: "ConnectionId":"38","StreamId":"1671998142108399431"] no route match for URL '/nuance.nrc.v1.NRC/Recognize'
[2024-04-25 23:53:28.838][21][debug][http] [source/common/http/filter_manager.cc:985] [Tags: "ConnectionId":"38","StreamId":"1671998142108399431"] Preparing local reply with details route_not_found`

anything wrong/missing with my config?

**Comment by MichelSkr** [comment]
I had to add a lua filter to the config.
the lua filter that I added was failing and didn't do anything but somehow after adding the lua the route matching started to work.

I noticed Others had similar problem https://github.com/envoyproxy/envoy/issues/19910 and might be related to route caching.

seems lua filter enforces a refresh to the route config
