### ISSUE TITLE
Add connection ID and related header formatters

### ISSUE THREAD

**Issue by rcio** [envoyproxy/envoy#3373]
Hi,

I use envoyproxy as a grpc load balancer to route request from client to upstream grpc servers. For some security considerations I want to trace every connection from client, so need a unique connection id per envoy instance to set into upstream headers when routing requests.

It's kind like [`$connection_id`](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_connection) in nginx's `ngx_http_core_module`, but I can't find something similar in envoy doc, Does it exists?

**Comment by mattklein123** [comment]
Doesn't exist currently, though wouldn't be very difficult to add. Going to move this issue over to a feature request.

**Comment by mattklein123** [comment]
I think this was added.
