### ISSUE TITLE
dependencies of envoy 1.3.0

### ISSUE THREAD

**Issue by luisapace** [envoyproxy/envoy#3375]
Hi, 
I've a general question on the envoy 1.3.0; I need to know what are its dependencies (compile and runtime); now I've seen that there are some dependencies listed at:

https://github.com/envoyproxy/envoy/blob/v1.3.0/docs/requirements.txt

plus, I see other packages listed at:

https://github.com/envoyproxy/envoy/blob/v1.3.0/docs/install/requirements.rst 

Do they all are dependencies of envoy? are there other dependencies not listed in those files?

Thanks a lot.

**Comment by junr03** [comment]
The first link you provided are the dependencies needed to build the documentation.

The second link are the dependencies to build envoy itself.

**Comment by luisapace** [comment]
Thanks! so, there are no other additional deps, am I correct?

**Comment by luisapace** [comment]
thanks a lot!
