### ISSUE TITLE
Why add user home in devcontainer

### ISSUE THREAD

**Issue by ShenFeng312** [envoyproxy/envoy#33758]
![image](https://github.com/envoyproxy/envoy/assets/49786112/35287df1-c72c-4070-9e9d-cd547f2241c3)

**Comment by wbpcode** [comment]
cc @lizan

**Comment by phlax** [comment]
@ShenFeng312 im guessing the idea is for accessing any user configs, but my feeling is that its probably not necessary, at least as the default.

relatedly i wonder what the utiltity of the CAPs above are - they essentially allow the container to root the host (altho i guess mitigated by running as non-root).

im perhaps not the best person to review as i dont use vscode myself - but would be happy to review any cleanups to this setup - as far as i can

**Comment by ShenFeng312** [comment]
@phlax 
Can you tell me what tools you use for development? I'm not particularly keen on using VSCode either. However, it seems like the official documentation mainly covers VSCode-related topics. I'm doing development on Ubuntu desktop. Also, the files generated by Envoy compilation are too large. The envoy-build volume is occupying around 20GB of disk space (possibly more; I deleted the previous container due to issues).

**Comment by phlax** [comment]
> Can you tell me what tools you use for development?

mostly emacs, but im not going to recommend doing that unless you are already an emacs user

> ... the files generated by Envoy compilation are too large.

i think that is pretty unavoidable, especially if you want a debug build

> The envoy-build volume is occupying around 20GB of disk space ...

the default/recommended way of running is with `./ci/run_envoy_docker.sh` this mounts a temp volume from fs (default is `/tmp/envoy-docker-build`) - i `export ENVOY_DOCKER_BUILD_DIR=/home/phlax/bazel_cache` before using this way to ensure i reuse cache and dont fill my `/tmp` directory
