### ISSUE TITLE
[Questions] Why envoy access log not support size limit & rotation ?  And is there any good practice for this access log & envoy binary debug log ? 

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#33767]
Seems there is no such log file size limit & rotation configurations supported by Envoy ？ 

Is there any good practice for these log file collection ?

**Comment by wbpcode** [comment]
`logrotate` is good choice for this requirement. You can set the `postrotate` in the logrotate config to 

```
kill -USR1 `pgrep envoy`
```

Then the logrotate will send a signal to envoy to force envoy to reopen the log file after logrotate moved the old one.

**Comment by wufanqqfsc** [comment]
> logrotate

Thanks very much @wbpcode  ,this logrotate seems a good choice.
