### ISSUE TITLE
Connection attribute connection.transport_failure_reason doesn't work as expected

### ISSUE THREAD

**Issue by liubnu** [envoyproxy/envoy#33796]
Refer to issue https://github.com/envoyproxy/envoy/issues/26710 and commit https://github.com/envoyproxy/envoy/commit/6b4c8f031d0f0f05bec6ce37aedcca20cf9d0a14. 

Doc link https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#arch-overview-attributes.

The `DOWNSTREAM_TRANSPORT_FAILURE_REASON` is not passed to connection attribute `connection.transport_failure_reason`.

**Comment by wbpcode** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
Can you elaborate what is not passed as the attribute? The attribute is just an accessor, so it is probably missing data in the internal data structures in Envoy.
