### ISSUE TITLE
http health check unstable behavior

### ISSUE THREAD

**Issue by maxlavr** [envoyproxy/envoy#33823]
*Title*: *why http health check status 200, but health_flags failed_active_hc* 

*Description*:
> 
<img width="1383" alt="Снимок экрана 2024-04-26 в 19 45 04" src="https://github.com/envoyproxy/envoy/assets/23142902/6578c34b-20d7-4adc-a6b9-3ac5ac26c4be">

*Repro steps*:
> envoy v1.20.7

*Admin and Stats Output*:
>/clustes cluster's upstreams  constantly changes from healthy to unhealthy 

*Config*:
<img width="336" alt="Снимок экрана 2024-04-26 в 21 03 01" src="https://github.com/envoyproxy/envoy/assets/23142902/b5c30cc7-8efc-468e-8406-ad9ec910a559">

*Logs*:
> screenshot in description

Either I don’t fully understand the logic of processing health checks or there is another explanation why the response returned 200, but flag = failed_active_hc, help me please

**Comment by adisuissa** [comment]
If I read the [code correctly](https://github.com/envoyproxy/envoy/blob/f9c14577ae2f07ccf0586de71a3d3e83deae3eb8/source/extensions/health_checkers/http/health_checker_impl.cc#L325) the debug log line prints the host state before processing the result.
