### ISSUE TITLE
OAuth2 Filter - ID Token Cookie Too Large

### ISSUE THREAD

**Issue by joberdick** [envoyproxy/envoy#33825]
*Title*: *It's possible ID token is too large for cookie*

*Description*:
Our IDP can return large amounts of data in ID tokens. This is causing SSO to fail with the filter as the ID token is never present
![image](https://github.com/envoyproxy/envoy/assets/33881653/5bd33ac8-3af8-4085-9163-6e3baa8e5a80)

![image](https://github.com/envoyproxy/envoy/assets/33881653/a6be58e7-c915-47f8-85e0-1e1d5b81d8a2)

Can we either breakup the cookies to support larger payloads, or allow an option to exclude the ID token from the cookies?

*Repro steps*:

1. Setup Filter for SSO
2. Add over 4KB of payload to the ID token on the token issuer
3. Login with the filter and observe failure

**Comment by adisuissa** [comment]
cc @derekargueta @mattklein123 as codeowners

**Comment by derekargueta** [comment]
Making IdToken configurably opt-out sounds reasonable and simple

**Comment by joberdick** [comment]
Hi, @derekargueta are we able to prioritize this one?

**Comment by derekargueta** [comment]
PR posted
