### ISSUE TITLE
`io_uring` test fails with newer kernel (arm?)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#33829]
I rebuilt the arm VM image we use to provision CI pools with in azp.

This created an error:

```console
test/common/io/io_uring_impl_test.cc:366: Failure
Expected equality of these values:
  static_cast<char*>(iov1.iov_base)[0]
    Which is: '\0'
  'a'
    Which is: 'a' (97, 0x61)
Stack trace:
  0x988eb8: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x988d54: testing::Test::Run()
  0x989fc4: testing::TestInfo::Run()
... Google Test internal frames ...

test/common/io/io_uring_impl_test.cc:383: Failure
Expected equality of these values:
  static_cast<char*>(iov3.iov_base)[0]
    Which is: '\0'
  'e'
    Which is: 'e' (101, 0x65)
Stack trace:
  0x988eb8: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x988d54: testing::Test::Run()
  0x989fc4: testing::TestInfo::Run()
... Google Test internal frames ...

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=169003&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00&l=219

in order to workaround the problem we disabled the failing test on arm (https://github.com/envoyproxy/envoy/pull/33822)

i suspect this is not actually related to arm and is just the updated VM - ie the same thing will most likely happen when we update the x86 image

**Comment by phlax** [comment]
cc @soulxu

**Comment by phlax** [comment]
the update (to Ubuntu jammy) switched kernel 6.2 -> 6.5

**Comment by soulxu** [comment]
let me check
