### ISSUE TITLE
Move datadog example (Docker) out of `/source`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#33846]
Currently the datadog extension has a docker demo in the `/source` directory

To say this is unexpected would be to put it mildly - and unless im mistaken this is not part of the source at all.

If this is a demo then it should be moved to `/examples` and have the relevant documentation/testing added

**Comment by phlax** [comment]
cc @dmehala @mattklein123

**Comment by dmehala** [comment]
no stalebot

**Comment by phlax** [comment]
brilliant thanks so much @dmehala that is really appreciated - i can help with creating a sandbox
