### ISSUE TITLE
Referenced video in README.md is not available

### ISSUE THREAD

**Issue by httpdigest** [envoyproxy/envoy#33851]
*Title*: *YouTube video about Lyft introducing Envoy in 2017 is not available*

*Description*:
In trying to learn more about the history of Envoy, I saw that in the README.md of this repository here, [under the Documentation section](https://github.com/envoyproxy/envoy?tab=readme-ov-file#documentation) there is a mention of a YT video:

> Watch [a video overview of Envoy](https://www.youtube.com/watch?v=RVZX4CwKhGE) ([transcript](https://www.microservices.com/talks/lyfts-envoy-monolith-service-mesh-matt-klein/)) to find out more about the origin story and design philosophy of Envoy

But that does not seem to exist (anymore). Is there a replacement YT video id for it?

**Comment by adisuissa** [comment]
Thanks for letting us know!
Seems that the original movie was removed from https://www.microservices.com/talks/lyfts-envoy-monolith-service-mesh-matt-klein/

Will be fixed by #33852.
