### ISSUE TITLE
no such package '@com_github_axboe_liburing//' building Envoy docker image

### ISSUE THREAD

**Issue by isaaccarrington** [envoyproxy/envoy#33862]
Commit id being built - 35d00a5e59a1a4c71de368c55c7318d487d86108
Command run `./ci/run_envoy_docker.sh './ci/do_ci.sh release'`
Error output
```
...
Analyzing: 3018 targets (1620 packages loaded, 47535 targets configured)
ERROR: /build/bazel_root/base/external/envoy/bazel/foreign_cc/BUILD:11:15: no such package '@com_github_axboe_liburing//': error globbing [**] op=FILES: /build/bazel_root/base/external/com_github_axboe_liburing/man/IO_URING_VERSION_MINOR.3 (Too many levels of symbolic links) and referenced by '@envoy//bazel/foreign_cc:liburing'
ERROR: Analysis of target '//test/common/io:io_uring_worker_factory_impl_test' failed; build aborted: 
INFO: Elapsed time: 652.907s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1620 packages loaded, 47535 targets configured)
ERROR: Couldn't start the build. Unable to run tests
./ci/do_ci.sh: line 122: pushd: bazel-testlogs: No such file or directory
```

Output of `bazel version`
```
Bazelisk version: development
Build label: 6.5.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 23 16:45:22 2024 (1706028322)
Build timestamp: 1706028322
Build timestamp as int: 1706028322
```

Machine details:
MacBook Pro
14 inch, 2021
Chip: Apple M1 Pro
MacOS: Sonoma 14.4.1

**Comment by phlax** [comment]
cc @soulxu

**Comment by phlax** [comment]
@isaaccarrington can you build with the immediately previous commit ?

**Comment by phlax** [comment]
actually - i was thinking it was this PR that had landed - https://github.com/envoyproxy/envoy/pull/33833

not sure, but i think this may be related to the workaround i added for one of the tests breaking

**Comment by phlax** [comment]
either way - im reasonably confident that https://github.com/envoyproxy/envoy/pull/33833 will fix this

**Comment by phlax** [comment]
@isaaccarrington i have landed the likely fix if you can confirm we can close this ticket

**Comment by isaaccarrington** [comment]
@phlax unfortunately almost exact same error.
```
ERROR: /build/bazel_root/base/external/envoy/bazel/foreign_cc/BUILD:11:15: no such package '@com_github_axboe_liburing//': error globbing [**] op=FILES: /build/bazel_root/base/external/com_github_axboe_liburing/man/IO_URING_VERSION_MAJOR.3 (Too many levels of symbolic links) and referenced by '@envoy//bazel/foreign_cc:liburing'
ERROR: Analysis of target '//test/common/io:io_uring_worker_factory_impl_test' failed; build aborted: 
INFO: Elapsed time: 62.105s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1611 packages loaded, 51816 targets configured)
ERROR: Couldn't start the build. Unable to run tests
./ci/do_ci.sh: line 122: pushd: bazel-testlogs: No such file or directory
```
I went for a fresh clone of the whole repo and confirmed your fix is present
```user@MacBook-Pro-14 envoy % git log | grep 88388
commit e096fa40ef98571120a865397b15e188388bc30a
commit bdd2f63fafd7688388fb7e32bb209f2687af46e2
```

**Comment by isaaccarrington** [comment]
Thanks @phlax but unfortunately the same error
```
ERROR: /build/bazel_root/base/external/envoy/bazel/foreign_cc/BUILD:11:15: no such package '@com_github_axboe_liburing//': error globbing [**] op=FILES: /build/bazel_root/base/external/com_github_axboe_liburing/man/io_uring_minor_version.3 (Too many levels of symbolic links) and referenced by '@envoy//bazel/foreign_cc:liburing'
ERROR: Analysis of target '//test/common/io:io_uring_worker_factory_impl_test' failed; build aborted: 
INFO: Elapsed time: 1300.859s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1536 packages loaded, 30331 targets configured)
ERROR: Couldn't start the build. Unable to run tests
./ci/do_ci.sh: line 122: pushd: bazel-testlogs: No such file or directory
```
I actually cloned the repo fresh
Ensured you change is there
```
git log | grep 88388                             
commit e096fa40ef98571120a865397b15e188388bc30a
commit bdd2f63fafd7688388fb7e32bb209f2687af46e2
```
and deleted `/tmp/envoy-docker-build`

**Comment by phlax** [comment]
hmm, i see, thanks for checking

thinking more - i think that its not arm-specific as we run that command in our arm ci - so im thinking its more to do with mac

i dont have a mac to test with but i think there is some parts of the code that require `select` in their `BUILD` targets to ensure only linux triggers that code - there are some already, but most likely more are required

would be happy to review (insofar as i can) any PRs to fix that

if you got chance to test any of the release branches that would be helpful as we might be able to ~bisect the change

**Comment by soulxu** [comment]
not sure whether this PR is going to help https://github.com/envoyproxy/envoy/pull/33107

**Comment by soulxu** [comment]
> not sure whether this PR is going to help #33107

emm...no, you failed on another test '//test/common/io:io_uring_worker_factory_impl_test'

**Comment by PatrikValo** [comment]
Hello guys, I hit the same issue when I was running `./ci/run_envoy_docker.sh './ci/do_ci.sh release.server_only'` on my M3 MacBook.

I think it might be related to case insensitive fs on macOS - https://github.com/axboe/liburing/issues/978#issuecomment-1957418286. Creating case sensitive APFS fs and mounting it to container via ENVOY_DOCKER_BUILD_DIR could help.
