### ISSUE TITLE
Envoy crashes when encounters an error in config validate mode

### ISSUE THREAD

**Issue by cpakulski** [envoyproxy/envoy#3389]
Run envoy in "--mode validate" and it crashes when processing several example configs
from "configs" source code directory.

For example:
envoy-static -c configs/envoy_double_proxy.json --mode validate

**Comment by cpakulski** [comment]
@mattklein123 Assign it to me, please.

**Comment by mattklein123** [comment]
Done. Thank you @cpakulski!

**Comment by mattklein123** [comment]
@cpakulski can you check https://github.com/envoyproxy/envoy/issues/2881 also. I'm guessing both will be resolved by this work. Thank you!

**Comment by cpakulski** [comment]
@mattklein123 No problem.

**Comment by cpakulski** [comment]
@mattklein123 #2881 you asked me to check is caused by different problem than here. It  is similar to #3083 and is caused by https://github.com/envoyproxy/envoy/blob/master/source/server/config_validation/dispatcher.cc#L21. I will fix it in separate PR as it touches different parts of code.

**Comment by mattklein123** [comment]
> I will fix it in separate PR as it touches different parts of code.

Awesome, thanks.
