### ISSUE TITLE
GrpcService CallCredentials loads credentials from filesystem

### ISSUE THREAD

**Issue by incfly** [envoyproxy/envoy#3392]
**Issue Template**

*Title:  Add a `FileBasedMetadataCredentialsPlugin` to load credential from a file as CallCredentials*

*Description*:

**What we want to do**
Envoy recently adds the support,  to implement customized CallCredentials as MetadataCredentialsPlugin, https://github.com/envoyproxy/envoy/pull/3161.

We'd like to add an implementation of `FileBasedMetadataCredentialsPlugin` (just an illustrative name)which can:

1. Configured with a path to the credentials file.
1. When `FileBasedMetadataCredentialPlugin::GetMetadata` is invoked, the plugin reads the credential file, and populates the metadata with the file's content.
1. The outcome is that every xDS request includes this credential as metadata header.

**Use Case**
For our use case,
1. We run envoy on Kubernetes. And Kubernetes mounts [a credential file](https://github.com/mikedanese/community/blob/6e209490c441d8df84b6b5d8e352c0e2491a41bd/contributors/design-proposals/auth/bound-service-account-tokens.md)(in format of a JWT) into the envoy container file system.
1. Envoy sends SDS request to an identity server to get Istio key and certificate.
1. The SDS service will be configured with `FileBasedMetadataCredentialsPlugin` proposed above, and load the credential from the file, put in the metadata header.
1. The identity server then can verify the credential and authenticate the envoy, issue the key cert.

That describes Istio workload identity provisioning process. However,

- The JWT credential is provided by native Kubernetes, anyone who wants  make Envoy xDS requests including this Kubernetes-credentials can benefit from such feature.
- Potentially, it can be used beyong Kubernetes as long as a platform can provide a bootstrap credential as a file.

[optional *Relevant Links*:]

1. [Kubernetes JWT design doc](https://github.com/mikedanese/community/blob/6e209490c441d8df84b6b5d8e352c0e2491a41bd/contributors/design-proposals/auth/bound-service-account-tokens.md)

**Comment by incfly** [comment]
Add @mattklein123 @lizan @htuch to review the feature request.

**Comment by incfly** [comment]
Friendly ping :)

I've also provided a prototype, just for the illustrative purpose, https://github.com/envoyproxy/envoy/compare/master...incfly:file-token?expand=1

Thanks!

**Comment by mattklein123** [comment]
@incfly I don't know enough about this to have an opinion. @lizan WDYT?

**Comment by lizan** [comment]
The plugin is fairly simple, just reading token from local file and use it as gRPC metadata. The requirement is from Istio, but the logic is not istio specific at all.
