### ISSUE TITLE
Query - Regarding custom TLS handshaker to load the certs from the cache.

### ISSUE THREAD

**Issue by AmitKatyal-Sophos** [envoyproxy/envoy#33923]
I would like to use the custom TLS handshaker to load the certs from the cache (instead of using SDS). Could someone please share the details on how to get started.

**Comment by adisuissa** [comment]
More information can be found at: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#custom-handshaker-extension
