### ISSUE TITLE
Change the upstream port for the HTTP dynamic forward proxy

### ISSUE THREAD

**Issue by marc-barry** [envoyproxy/envoy#33945]
*Title*: *Change the upstream port for the HTTP dynamic forward proxy*

*Description*:

We use https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy and have a setup with listeners on non-standard ports. Due to certain restrictions we cannot run the dynamic forward proxy on standard web ports like `80`, `443` and `8443`. Instead, we have settled on using the following listener ports as an alternative:

- `10080` in place of `80`
- `10443` in place of `443`
- `18443` in place of `8443`

The issue we face is that it appears that the dynamic forward proxy setup using https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy and https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/clusters/dynamic_forward_proxy/v3/cluster.proto#envoy-v3-api-msg-extensions-clusters-dynamic-forward-proxy-v3-clusterconfig seem to use the listener port for upstream connection with no apparent way to override the upstream port.

As an example, let's assume we have the following `curl` command:

```
curl -I -X GET http://api.github.com:10080/ --resolve 'api.github.com:10080:127.0.0.1'
```

For this case, Envoy will set the `:authority` to `api.github.com:10080` and hence forwarding by the dynamic forward proxy cluster will be to the IP address of `api.github.com` and port `10080`. But we really want it to be forwarded to port `80` instead. I understand that Envoy is working as expected but I'd like a way to be able override the upstream port and cannot seem to figure out how to do so.

We also leverage https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.html#sni-dynamic-forward-proxy and have the exact same problem. It uses [Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication) (SNI) as the value of the target host instead. But it supports `port_value` as documented under https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/sni_dynamic_forward_proxy/v3/sni_dynamic_forward_proxy.proto#extension-envoy-filters-network-sni-dynamic-forward-proxy. I would like the same for the HTTP dynamic forward proxy.

I'm wondering if there is a way to accomplish this.

*Relevant Links*:

- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/sni_dynamic_forward_proxy/v3/sni_dynamic_forward_proxy.proto#extension-envoy-filters-network-sni-dynamic-forward-proxy
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy

**Comment by phlax** [comment]
cc @rshriram @lizan @mattklein123 @alyssawilk

**Comment by marc-barry** [comment]
I tried adding an HTTP Lua filter to see if I could modify the ":authority" and it appears to have worked. We really don't want to introduce Lua into our system but this allowed me to test out an option if there is no native configuration way to do this with Envoy. If doing it with code is the only way then we'd much prefer to use the HTTP WASM filter as you can pass dynamic configuration into the filter and we prefer to write Go and compile to WASM. I'm still hoping there is a native way to do this without code.

Here's the code that simply always replaces the upstream port with `80` to see if it was possible. I didn't figure out how to pass dynamic port mappings to the script such as mentioned in the description of this issue.
```lua
-- Define the Lua filter
function envoy_on_request(request_handle)
    -- Retrieve the destination address and port
    local authority_header = request_handle:headers():get(":authority")
    local destination_address, existing_port = authority_header:match("^(.-):?(%d*)$")

    -- If there's an existing port, remove it
    if existing_port then
        authority_header = destination_address
    end

    local destination_port = "80" -- Change this to the desired upstream port

    -- Modify the destination port
    request_handle:headers():replace(":authority", authority_header .. ":" .. destination_port)
end
```

**Comment by marc-barry** [comment]
We decided to rewrite the Lua as Go code and output WASM and load it as a HTTP WASM filter which also accepts a configuration which is like the `port_value` which exists in the SNI dynamic forward proxy. This is the best solution that we could come up with at this time. We are hopeful we missed something within the Envoy configuration.

**Comment by marc-barry** [comment]
I'm closing this as we have a solution with a WASM filter. It works for our needs as there is no way to make this work with standard Envoy configuration.
