### ISSUE TITLE
Add custom Envoy cluster-specific Prometheus label

### ISSUE THREAD

**Issue by arazdolski** [envoyproxy/envoy#33940]
*Title*: *Add custom Envoy cluster-specific Prometheus label*

*Description*:

I would like to create a custom Prometheus label on the Envoy cluster to use later in the PromQL expression to make more fine-grained alerts. Every cluster should have its own value. I expect to get metric e.g. `envoy_cluster_lb_healthy_panic{custom_label="test"} 0`. What parameter in cluster configuration can I use? How to include this parameter in Envoy stats to push it to Prometheus as a label with value?

I found https://github.com/envoyproxy/envoy/issues/29294 issue, tried to define `alt_stat_name`, but if it is defined (e.g. `alt_stat_name: hello_world`), then `envoy_cluster_name` label is overwritten by the value of `alt_stat_name`

*Relevant Links*:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-metadata
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto

**Comment by arazdolski** [comment]
Envoy version is 1.27.2

**Comment by adisuissa** [comment]
I'm not a Prometheus expert, but I think there's the CLUSTER_NAME tag that should be populated in the cluster's stats.

Can you please take a look [here](https://github.com/datawire/ambassador-docs/blob/master/docs/edge-stack/1.12/topics/running/statistics/envoy-statsd.md) and see if it gets you in the right direction?

**Comment by arazdolski** [comment]
Currently, I have Envoy metrics exposed to Prometheus on path `/metrics` and port 9109 using listener on `/stats/prometheus`. And I don't see how enabling statsd would solve my problem 🤔 

Initially, I was thinking of using stats_tags from stats_config, but this resource is common for all clusters and I need to define a label (tag) per cluster.

**Comment by adisuissa** [comment]
cc @jmarantz may have more information, or be able to direct this to the right person.
