### ISSUE TITLE
aws: assert in debug for async credential providers

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#33962]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Assertion failure in debug build due to accessing timer outside of main thread

*Description*:
Tracking issue for fixing assertion failure in AWS request signing extension.

*Repro steps*:
Using aws-request-signing-filter.yaml and enabling runtime guarded feature   envoy.reloadable_features.use_http_client_to_fetch_aws_credentials, then sending a request to envoy.

**Comment by phlax** [comment]
cc @derekargueta @suniltheta @mattklein123 @marcomagdy

**Comment by nbaws** [comment]
pr coming to address this issue
