### ISSUE TITLE
OpenTelemetry metrics sink and access logger - Ability to configure OpenTelemetry Resource via Resource Detectors

### ISSUE THREAD

**Issue by evantorrie** [envoyproxy/envoy#33970]
*Title*: *Support OpenTelemetry Resource detectors for Otel Metrics sink*

*Description*: The OpenTelemetry project defines the concept of a [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md). It is a bag of attributes that can be configured in different ways in OpenTelemetry, via environment variables, explicitly in code or via [Resource detectors](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#detecting-resource-information-from-the-environment).

Issue #28929 and its resolution #29547 added support in the [OpenTelemetry Tracer configuration](https://github.com/envoyproxy/envoy/blob/e2998e1332cddb12f3d35db1e6f7d9459b643e86/api/envoy/config/trace/v3/opentelemetry.proto#L45-L51)  for "Resource Detectors".

1. However, the OpenTelemetry Logger implementation, while allowing [configurable resource attributes](https://github.com/envoyproxy/envoy/blob/e2998e1332cddb12f3d35db1e6f7d9459b643e86/api/envoy/extensions/access_loggers/open_telemetry/v3/logs_service.proto#L34-L37) does not support resource detectors.

2. The OpenTelemetry Metrics sink does not seem to support allowing [configurable resource attributes](https://github.com/envoyproxy/envoy/blob/e2998e1332cddb12f3d35db1e6f7d9459b643e86/api/envoy/extensions/access_loggers/open_telemetry/v3/logs_service.proto#L34-L37) - not even `service.name` (please correct me if I'm wrong).

The OpenTelemetry Resource concept applies across all telemetry signals - traces, metrics and logs. It would be great to see if we can unify the different signal types in Envoy such that the OpenTelemetry Resource configuration is specified once, and then inherited by the three different signal generators.

Failing that, at least unifying support for each signal type to be able to specify a set of resource detectors (specifically the Environment Resource Detector which can set resource attributes from environment variables as defined in the OpenTelemetry specification) would greatly help in identifying the metrics and logs as emanating from the same underlying Envoy instance.

*Relevant Links*: #28929 - Adding Resource Detectors to OpenTelemetry Tracer

**Comment by phlax** [comment]
cc @alexanderellis @htuch

**Comment by phlax** [comment]
cc @joaopgrassi

**Comment by joaopgrassi** [comment]
I didn't dig into details of how OTel metrics and logs are collected/recorded in Envoy. This would be another benefit if we would use the OTel SDK in Envoy instead of having a somewhat custom implementation of it. 

Having said that, maybe it's possible to "move out" the concept of resource detector from the tracer package/module so other signals can be used? I'm not sure if that's possible..

**Comment by evantorrie** [comment]
Yes, ideally there would be some sort of global setting for OpenTelemetry Resource, and the trace/metrics/logging OpenTelemetry exporters would refer to that when initializing themselves, so that the resource information gets associated with each set of outgoing telemetry data.

**Comment by evantorrie** [comment]
@joaopgrassi I think this is still important.  Is it possible to label this as `help wanted`?

**Comment by joaopgrassi** [comment]
I can't add labels or re-open. @wbpcode can you please reopen? Thank you!

**Comment by hzhang4-sc** [comment]
This will be a super useful feature. The prometheus receiver can automatically attach the needed resource labels to envoy metrics, such as pod_name/node_name/node_ip/deployment_name. OTLP sink has many advantages over the Prometheus sink, but the resource detection is kind of a blocker here. It would be great the OTLP sink can support it too.
