### ISSUE TITLE
503 UC does not get reported as a span.

### ISSUE THREAD

**Issue by Stono** [envoyproxy/envoy#33990]
Where a connection failed, a span is not recorded in Jaeger.  From a users perspective this results in us seeing metrics for failures (503's) then going to try and investigate them, and not finding any spans.

*Description*:
More details are on https://github.com/istio/istio/issues/50875, I was just asked to raise it here.

**Comment by wbpcode** [comment]
hmmm, I believe in normal case the span should be created and reported. Is your request a request from downstream or side request that created by the async client of Envoy?

**Comment by Stono** [comment]
Sorry I never got back to you here, completely missed the question.

> hmmm, I believe in normal case the span should be created and reported. Is your request a request from downstream or side request that created by the async client of Envoy?

<img width="491" alt="Screenshot 2024-06-27 at 09 54 44" src="https://github.com/envoyproxy/envoy/assets/1486729/56c5aa32-cdf2-4d84-97ca-e7aaf504256c">

The span does not get recorded when the connection to an external host here gets a reset, eg `upstream reset: reset reason: connection termination`.
