### ISSUE TITLE
Support for sending response body, headers, and status code to client on Extauthz filter CheckStatus::Error

### ISSUE THREAD

**Issue by mikehuston** [envoyproxy/envoy#34005]
*Title*: Support for sending response body, headers, and status code to client on Extauthz filter CheckStatus::Error

*Description*:
Allow both http and grpc extauthz filters to support sending response headers and status code from the extauthz service to the client on extauthz 5xx response. I'm looking for https://github.com/envoyproxy/envoy/pull/24845, for both HTTP and gRPC extauthz filter impls.

What scenarios it enables:
* [Response headers] When our extauthz service returns 5xx, it'd be extremely useful for downtime debugging and error attribution to pass internal metadata about the errored request (such as token type used, customer identifier, high level error category) to our Envoy access logs (we will remove these internal headers before sending the response to the client).
* [Status code] clients can distinguish between 500 (internal error, don't retry) and 503 (temporarily unavailable, retry)
* [Body] a custom response body that contains a unique request identifier and/or error message will help customers and us determine next steps of action for errored requests.
* [Response headers] It will allow us to send headers to the client such as `Retry-After` for 503

*Relevant Links*:
https://github.com/envoyproxy/envoy/pull/24845

**Comment by phlax** [comment]
cc @agrawroh @esmet @tyxia @ggreenway
