### ISSUE TITLE
Basic Auth Filter should include `WWW-Authenticate` header in its 401 response

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#34015]
A server using [HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) will respond with a [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) Unauthorized response to a request for a protected resource. This response must include at least one WWW-Authenticate header and at least one [challenge](https://developer.mozilla.org/en-US/docs/Glossary/Challenge), to indicate what authentication schemes can be used to access the resource (and any additional data that each particular scheme needs).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

**Comment by phlax** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
SGTM.

**Comment by arkodg** [comment]
@zhaohuabing looks like there is extra work needed here from EG side, and is available on `v0.0.0-latest` and should be available in the next release ?
