### ISSUE TITLE
per cluster HTTP filter config

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#34021]
*Title*: *per cluster HTTP filter config*

*Description*:

Now the Envoy provide route/virtual host level HTTP filter config support. By this way, the same filter could behaves differently for different route or virtual host.

But in our scenarios, we may also want to support a `service` level filter. And the closest abstraction in the Envoy would be the per cluster HTTP filter config. 

We can support this in our private fork. But also wonder if this a reasonable requirement for the community or if others may have similar requirement.

**Comment by wbpcode** [comment]
cc @mattklein123 

cc @zhaohuabing for suggestion from envoy-gateway
cc @kyessenov for suggestion from istio

**Comment by zhaohuabing** [comment]
While per-cluster filter could be valuable, per-route filter seems sufficient for EG's current need. I'm not aware of any requirements for per-cluster filter in EG.

@wbpcode Could you provide some concrete examples of use cases where per-cluster would be essential? This would help others evaluate the necessity of this feature.

**Comment by kyessenov** [comment]
From Istio, service doesn't correspond to an upstream cluster. From a general perspective, "upstream cluster" configs are notoriously low-level and don't map well to service ownership (e.g. VIP or domain name).

**Comment by wbpcode** [comment]
> From Istio, service doesn't correspond to an upstream cluster. From a general perspective, "upstream cluster" configs are notoriously low-level and don't map well to service ownership (e.g. VIP or domain name).

Get it. I agree mesh needn't that. Esp considering that in most cases, the VH could be treat an abstraction of service (VIP, K8S server, domain...)

**Comment by wbpcode** [comment]
> While per-cluster filter could be valuable, per-route filter seems sufficient for EG's current need. I'm not aware of any requirements for per-cluster filter in EG.
> 
> @wbpcode Could you provide some concrete examples of use cases where per-cluster would be essential? This would help others evaluate the necessity of this feature.

In our scenarios, we may want to use specific filter config for specific backend service. In the gateway scenario, the VH or routes cannot be mapped one-to-one to a backend service.
So, I am looking a new way to support the per-service-filter-config. Although in fact, the cluster couldn't be mapped one-to-one to a backend service. But I don't find a better way. orz.

Anyway, if the community is no interested in this, I will pend it up. :)
