### ISSUE TITLE
ratelimit

### ISSUE THREAD

**Issue by richard6ats** [envoyproxy/envoy#34022]
package envoy.config.ratelimit.v3;

import "envoy/config/core/v3/config_source.proto";
import "envoy/config/core/v3/grpc_service.proto";

import "udpa/annotations/status.proto";
import "udpa/annotations/versioning.proto";
import "validate/validate.proto";

where can I find these proto?

**Comment by phlax** [comment]
in the envoy case the protos are defined in the `api/` directory

for udpa and (i think) validate they are defined over in the xds repo (https://github.com/cncf/xds)

**Comment by phlax** [comment]
correction - the validate proto is here https://github.com/bufbuild/protoc-gen-validate
