### ISSUE TITLE
CredentialInjectorIntegrationTest.InjectCredential flake

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#34040]
https://dev.azure.com/cncf/envoy/_build/results?buildId=170034&view=logs&jobId=767be981-567e-57d8-68c3-2140ede0a0bd&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00

**Comment by wbpcode** [comment]
cc [vikaschoudhary16](https://github.com/vikaschoudhary16)

**Comment by vikaschoudhary16** [comment]
working on it
