### ISSUE TITLE
Support metadata input in Mathching API

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#34092]
*Title*: *Support metadata input in Matching API*

*Description*:
The [Matching API](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api) currently doesn't support Metata Input. It would be valuable if Envoy could support it.

For instance, we prefer using Matcher over RBAC rules for authorization due to its flexibility. However,  while [ RBAC allows specifying metadata as the principal](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-principal), the matcher API currently lacks this capability, limiting use cases such as JWT claims as principals.

The supported Matching Inputs: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api#extension-category-envoy-matching-http-input

@arkodg

**Comment by kyessenov** [comment]
Sure, this would be a great addition, and can follow similar code to filter state input.

**Comment by vikaschoudhary16** [comment]
Hey @zhaohuabing Are you working to implement it?

**Comment by zetaab** [comment]
@vikaschoudhary16 when you start implementing this, my use case is that I would like to use JWT claim like "email": "foo@bar.com" for RBAC. Also I would like to use JWT []string claims. That can be like "roles": ["foo", "bar"]. If these array claims are forwarded to backends, these will be shown in headers as base64 encoded. It is pretty difficult to do authorization for base64 encoded string. So is there somekind of shortcut to base64 decode and check is there value in array?

**Comment by vikaschoudhary16** [comment]
@zetaab I have tested changes in the likes PR. If there is a claim like "roles": ["foo", "bar"] in the token, matcher which is added in the linked PR is able to authorize on specific claims like foo allowed and bar denied etc.

>So is there somekind of shortcut to base64 decode and check is there value in array?

You can test with my PR your usecase, if you want to give it a quick try. Functionally it should be working.

**Comment by yaroslavros** [comment]
This would also be extremely useful for ExtensionWithMatcher to allow doing things such as setting HTTP headers depending on a specific JWT match.
Looking forward to seeing this included in the mainline code.

**Comment by yaroslavros** [comment]
I can confirm that this patch indeed works nicely with ExtensionWithMatcher filter. For example, I can trigger HeaderMutation based on a specific metadata match (envoy.extensions.matching.common_inputs.network.v3.DynamicMetadataInput input with type.googleapis.com/envoy.extensions.matching.input_matchers.metadata.v3.Metadata custom_match under single_predicate).
