### ISSUE TITLE
HTTP/1 balsa parser prematurely purges parsed headers resulting in status monitor failure

### ISSUE THREAD

**Issue by RenjieTang** [envoyproxy/envoy#34096]
During [UpstreamHttp11ConnectSocket::isValidConnectResponse()]( https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/extensions/transport_sockets/http_11_proxy/connect.cc#L23), a framer is used under the hood to parse the header. Later its statusCode() is used to determine validity.

However, when the response header contains `content-length: 0`, [BalsaParser::MessageDone()](https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/common/http/http1/balsa_parser.cc#L356) will be invoked which purges the parsed header. Later when statusCode() is called, since the header is empty, the default 0 status code is returned and the response is mistaken as invalid.

This bug is sneaky because when `content-length` isn't present, the framer will [wait](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L719) to read more data until the connection close, and thus  MessageDone() is never called.

I think the correct fix should be to not reset the header when the framer is [cleared](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L80), because the header is owned by the BalsaParser.

**Comment by RyanTheOptimist** [comment]
@bencebeky

**Comment by alyssawilk** [comment]
Also, looks to me like onStatus is returning the reason phrase, not the status code?

**Comment by bencebeky** [comment]
> During [UpstreamHttp11ConnectSocket::isValidConnectResponse()](https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/extensions/transport_sockets/http_11_proxy/connect.cc#L23), a framer is used under the hood to parse the header. Later its statusCode() is used to determine validity.
> 
> However, when the response header contains `content-length: 0`, [BalsaParser::MessageDone()](https://github.com/RenjieTang/envoy/blob/5d797fb4ef04d67b68a8c5c947cb64e9473d073c/source/common/http/http1/balsa_parser.cc#L356) will be invoked which purges the parsed header. Later when statusCode() is called, since the header is empty, the default 0 status code is returned and the response is mistaken as invalid.
> 
> This bug is sneaky because when `content-length` isn't present, the framer will [wait](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L719) to read more data until the connection close, and thus MessageDone() is never called.
> 
> I think the correct fix should be to not reset the header when the framer is [cleared](https://github.com/google/quiche/blob/ee237e96f18ef123af9992f74645a8a0ce9ef6ef/quiche/balsa/balsa_frame.cc#L80), because the header is owned by the BalsaParser.

Thank you for raising this issue.

I don't think the right approach is to not reset BalsaHeaders along with BalsaFrame. BalsaParser is designed to parse multiple messages, so it makes sense to reset BalsaHeaders and BalsaFrame at the same time. I propose saving the value of the status code when the headers are parsed, and keeping it either until the first byte of the next message is parsed, or as long as possible, until the headers of the next message are parsed.

Another approach would be not to reset BalsaFrame and BalsaHeaders when parsing the message is complete. I think as long as we only need access to a single integer, it is better to reset them early, because they take up memory, but this would also be a viable approach if more state would need to be accessed.

**Comment by alyssawilk** [comment]
is it just the single integer?  looks like isHttp11 also refers to headers, as does contentLength and possibly others (I stopped at n=2).  I think it'd be safer to keep headers around rather than trying to latch all of the fields and hope we don't forget to do so in future.

**Comment by bencebeky** [comment]
> is it just the single integer? looks like isHttp11 also refers to headers, as does contentLength and possibly others (I stopped at n=2). I think it'd be safer to keep headers around rather than trying to latch all of the fields and hope we don't forget to do so in future.

Oh thanks, that's a very good point.
