### ISSUE TITLE
Unable to see Trace Id in Access Logs when request is rate limited (429)

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#34102]
`%REQ(traceparent)%` is not working when request is rate limited

cc @wbpcode

**Comment by wbpcode** [comment]
Yeah. We can extend the substitution formatter to output the trace id and span id (downstream request span id) from the active span directly. As far as I know, the active span is part of the `HttpFormatterContext` now?

**Comment by zirain** [comment]
ok, will add a new formatter `%TRACE_ID%`.
