### ISSUE TITLE
VHDS in Route configuration does not support ADS

### ISSUE THREAD

**Issue by rettuna** [envoyproxy/envoy#34122]
*Title*: *VHDS in Route configuration does not support ads*

*Description*:
I have only an `Incremental: AggregatedDiscoveryService.DeltaAggregatedResources` server configured. I want the envoy to pull the virtual hosts using the ADS. But I get this error
```
err:vhds: only 'DELTA_GRPC' is supported as an api_type.
```
My config
```
{
		"name": "myrouteconfig0",
		"vhds": {
			"config_source": {
				"ads": {}
			}
		}
	}
```

If I change the config to use DELTA_GRPC then envoy doesn't use the ADS RPC to query virtual hosts and expects an incremental VHDS host to listen for Virtual host requests.

**Comment by ravenblackx** [comment]
@dmitri-d or @htuch maybe knows stuff about vhds.

**Comment by htuch** [comment]
https://github.com/envoyproxy/envoy/issues/12742 is the explanation I think, @dmitri-d to confirm.
