### ISSUE TITLE
CI failing frequently "The Build Event Protocol upload failed"

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#34151]
5 CI runs in a row failed with this error ([example](https://dev.azure.com/cncf/envoy/_build/results?buildId=170399&view=results))

It's also been happening frequently in PR CI runs, requiring a lot of extraneous `/retest`.

**Comment by phlax** [comment]
hopefully fixed by #34716 cc @alyssawilk

**Comment by alyssawilk** [comment]
also theoretically fixed internally, but I think we should leave the async mode on as I think we never want BES failures to result in CI failures
