### ISSUE TITLE
AMQP/HTTP bridge

### ISSUE THREAD

**Issue by alanconway** [envoyproxy/envoy#3415]
*Title*: AMQP/HTTP bridge for envoy

*Description*:

AMQP (http://www.amqp.org/) is a popular standard protocol for messaging middleware. It supports many patterns of asynchronous message exchanged (brokered queues, peer-to-peer, routed etc.) including the request-response pattern used by HTTP. The idea is to bridge between AMQP request/response and HTTP. Other messaging patters possible in AMQP are out of scope.

The bridge would be in 2 halves: 
1. Receiving AMQP requests, forwarding as HTTP, translating HTTP responses back to AMQP
2. Receiving HTTP requests, forwarding as AMQP translating AMQP responses back to HTTP

Each half can be deployed independently allowing Envoy to behave as an AMQP to HTTP bridge or a HTTP to AMQP bridge. Both halves could be deployed in the same Envoy instance to make it behave like a limited (request/response only) AMQP router, since there are full-featured AMQP routers already out there that probably isn't a major use case. 

The bridge will be implemented as a pair of filters, or a single filter that can be configured to work in either mode. The filter will do a simple, fixed translation from AMQP to HTTP and back. Users of the bridge will rely on Envoy's existing HTTP features to get interesting routing and transformation behaviour on the HTTP side of the bridge.

*Goals*

* Envoy can accept and initiate AMQP connections (act as AMQP client or server)
* Allow all existing Envoy HTTP routing/rewriting features on the HTTP side of the bridge.
* Flexible mapping/routing of AMQP addresses to HTTP host + path using Envoy's existing URL rewriting and routing abilities
* Run-time sync between incoming AMQP links and Envoy service discovery (needs more thought)

*Use cases*

* HTTP tunneling over a routed AMQP network using http://qpid.apache.org/components/dispatch-router
* HTTP client access to AMQP requset/response services
* AMQP client access to HTTP servers
* (AMQP request/response tunneling over HTTP - possible but not clear that anyone wants that.)

*Relevant Links*

There is an incomplete work in progress at https://github.com/alanconway/envoy-amqp

**Comment by alanconway** [comment]
@mattklein123 question - the extension source is all under source/extensions, but the configuration is under api/ Should new extensions follow this pattern, or bundle their configuration .proto files with their source?

**Comment by mattklein123** [comment]
> @mattklein123 question - the extension source is all under source/extensions, but the configuration is under api/ Should new extensions follow this pattern, or bundle their configuration .proto files with their source?

This is an inconsistency I don't love, but I would just follow along w/ the others for now.

**Comment by alanconway** [comment]
@mattklein123 The envoy doc suggests it supports pipelining but my first attempt didn't work. I have multiple request messages coming in on the AMQP side of a connection, and I simply concatenated the corresponding HTTP requests on the HTTP side. Envoy only processed the first one and dropped the rest. It's very likely I'm doing something wrong, should that work?  

The AMQP side expects to be able to send as many requests as it likes and correlate the responses as they flow back, so it ends up heavily pipelined  on the HTTP side. For now I've throttled it back to a single request-response at a time but that's not ideal performance-wise. I'm not (yet) using envoy's codec so I'm doing HTTP 1.1 directly - not ideal and maybe part of my problem.

**Comment by mattklein123** [comment]
The HTTP/1.1 client does not perform pipelining. The server also does not actual pipeline, rather it applies back pressure while processing requests to avoid head of line blocking resource constraint situations.

**Comment by alanconway** [comment]
Gotcha. At the back-end of an AMQP network, my amqp_server filter does
potentially do a bunch of illegal pipelining because it's aggregating
requests from many sources and not bothering to check if they're
idempotent, I'm seeing occasional problems that may be related to that.
Sounds like I should slow the flow with AMQP credit and pass requests up to
envoy one-by-one.

**Comment by jmin911** [comment]
This is useful.

**Comment by alanconway** [comment]
Not forgotten, but on hold, I'm in the process of presentations &
discussions with other interested parties to gather feedback before taking
it further, but it is still a going concern. I'm always interested in
feedback from the envoy perspective.

**Comment by cmluciano** [comment]
Can we add the "no stalebot" label to this issue @envoyproxy/maintainers
