### ISSUE TITLE
router: regex path matcher doesnt work with filters that change the path

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy#3417]
When using regex in the route matcher, one cannot use filters that change the request path (json-grpc transcoder for example). 

The reason is this ASSERT:
https://github.com/envoyproxy/envoy/blob/01fef5ba2d09c3b501ee89b645998a47e70cd44d/source/common/router/config_impl.cc#L655

This assert makes sure the path still matches. the problem with it that this assert is performed even if the path does not need to be rewritten (which is checked in the base class: https://github.com/envoyproxy/envoy/blob/01fef5ba2d09c3b501ee89b645998a47e70cd44d/source/common/router/config_impl.cc#L380).

Two options come to mind on how to fix this:
- option 1: remove the ASSERT
- option 2: refactor out lines 380-383 to a method (needPathRewrite() ?) and call it in RegexRouteEntryImpl::finalizeRequestHeaders

Thoughts?

**Comment by mattklein123** [comment]
@yuval-k I vote for option (2) as I think it is less magical. You want to do a patch?

@zuercher @rshriram any opinions?

**Comment by yuval-k** [comment]
I can do the patch. Going on vacation so might take a few days.
