### ISSUE TITLE
Unable to access filter state from with Golang filter

### ISSUE THREAD

**Issue by asialea** [envoyproxy/envoy#34183]
*Title*: *Unable to access filter state from with Golang filter*

*Description*:
Hi team, facing a strange issue attempting to access filter state from within the golang http filter. We have a listener filter which sets keys in both both dynamic metadata and filter state which is successfully accessed by other c++ filters in the chain. When attempting to access these same keys from within the http golang filter, dynamic metadata is empty and the keys do not exist in the filter state.

Any pointers would be appreciated.

[optional *Relevant Links*:]

https://github.com/envoyproxy/envoy/blob/416cd425d50d3bc54c18ea134835a07ec21370d7/contrib/golang/filters/http/source/go/pkg/http/filter.go#L306

**Comment by doujiang24** [comment]
Hello @asialea 

> which is successfully accessed by other c++ filters in the chain

could you please show some related key C++ code? i.e. how they get the values.

And could you please try the [Lua http filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter) to get the dynamicmetadata?

I think there might be some difference to get values which is setted by a listener filter

**Comment by asialea** [comment]
Sure so here is a code snippet on how these values are set inside our custom listener filter

```
Network::FilterStatus Filter::onAccept(Network::ListenerFilterCallbacks& cb) {
  StreamInfo::FilterState& filter_state = cb.filterState();
  FilterStateUtils::setFilterState(filter_state, key, value, StateType::ReadOnly, LifeSpan::Connection);
  cb.setDynamicMetadata(filter_name, metadata);
}
```

Here is the setFilterState method used above
```
static void setFilterState(StreamInfo::FilterState& filter_state, std::string key, std::string value, StateType state_type, LifeSpan life_span) {
            if (state_type == StateType::Mutable || !filter_state.hasDataWithName(key)) {
                filter_state.setData(key,
                                    std::make_shared<Router::StringAccessorImpl>(value),
                                    state_type,
                                    life_span);
            } else {
                ENVOY_LOG(warn, "FilterStateUtils: Not allowed to call setData() twice on same data name '{}' with ReadOnly state", key);
            }
        }
```

Here is the code on how the state is retrieved in a custom http filter later on in the chain. These same values from filter state is also able to be accessed by the access logger using FormatStrings

```
Http::FilterHeadersStatus CustomFilter::decodeHeaders(Http::RequestHeaderMap& headers, bool) {
  const StreamInfo::FilterStateSharedPtr& filter_state = decoder_callbacks_->streamInfo().filterState();
  auto id= FilterStateUtils::getFilterStateStringData(filter_state, key);
}
```

Here is the getFilterStateStringData method used above
```

        static std::string getFilterStateStringData(const StreamInfo::FilterState& filter_state, absl::string_view key) {
            auto filter_state_object = filter_state.getDataReadOnly<Router::StringAccessor>(key);
            if (filter_state_object == nullptr) {
                return EMPTY_STRING;
            }

            return std::string(filter_state_object->asString());
        }
```

**Comment by doujiang24** [comment]
okay, I see. we should use `Router::StringAccessorImpl` & `Router::StringAccessor` instead of `GoStringFilterState`, it could be better compatibility.
@StarryVae Are you interested to improve it?
