### ISSUE TITLE
Support sending tapped streams into a single file sink in tap filter

### ISSUE THREAD

**Issue by hwyuan** [envoyproxy/envoy#34188]
*Title*: *Support sending tapped streams into a single file sink in tap filter*

*Description*:
The current tap filter allows specifying a `file_per_tap` sink, where each tapped stream will output to a different file object. Is it possible to allow tapped streams to share a single file object as the sink? this could make it easier to consume the output of the tap filter in file systems.

[optional *Relevant Links*:]
[>Any extra documentation required to understand the issue.
](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/tap/v3/common.proto#envoy-v3-api-msg-config-tap-v3-filepertapsink)

**Comment by ravenblackx** [comment]
@xu1zhou
