### ISSUE TITLE
Document format of fingerprint_sha256 vs verify_certificate_hash

### ISSUE THREAD

**Issue by llchan** [envoyproxy/envoy#3419]
*Title*: *Document format of fingerprint_sha256 vs verify_certificate_hash*

*Description*:
It would be helpful to document the format of the client cert hashes in both the `verify_certificate_hash` fields [here](https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v2/api/v2/auth/cert.proto#auth-certificatevalidationcontext) and the `fingerprint_sha256` field in the client ssl auth REST server [response](https://www.envoyproxy.io/docs/envoy/v1.6.0/configuration/network_filters/client_ssl_auth_filter#config-network-filters-client-ssl-auth-rest-api). It seems to me like the former expects the output from openssl that looks like "AA:BB:CC:DD:..." vs the latter expects the same thing without colons and lowercased "aabbccdd...".

Medium-term, it would be nice if both components supported a common set of formats and normalized as needed.

**Comment by PiotrSikora** [comment]
@llchan I've added support for the "standard" hex-encoded SHA-256 hashes and updated docs for `verify_certificate_hash` in #3437. Let me know if you think there is anything else missing.

**Comment by mattklein123** [comment]
Closing, thanks @PiotrSikora!
