### ISSUE TITLE
dependencies of proxy/envoy-0e1d66377d9bf8b8304b65df56a4c88fc01e87e8.tgz

### ISSUE THREAD

**Issue by luisapace** [envoyproxy/envoy#3420]
Hi, 
I need to use Diego and so I've to use proxy/envoy-0e1d66377d9bf8b8304b65df56a4c88fc01e87e8.tgz

because included by Diego as a blob (see https://github.com/cloudfoundry/diego-release/blob/v2.1.0/config/blobs.yml)

To do that I've to analyze the source code of Diego and all compile and runtime dependencies chain to verify that - both - code and licenses do not have any problem.

So I've tried to discover the dependencies of envoy as I've done in the past - for 1.3.0 - searching the file equivalent to 
https://github.com/envoyproxy/envoy/blob/v1.3.0/docs/install/requirements.rst 

But I cannot find any requirements.rst file like that in the https://github.com/envoyproxy/envoy/tree/0e1d66377d9bf8b8304b65df56a4c88fc01e87e8 downloaded code.

Could you please help me on this? What are the compile and runtime dependencies needed to compile and run that level of envoy? 

Thanks.

**Comment by luisapace** [comment]
Hi, could you please tell me if there are any news on this question? I apologize to ask you again, but without your answer I'm not able to proceed, so I'll appreciate if you can give me an answer. Feel be free to ask other details if you need. Thanks.

**Comment by PiotrSikora** [comment]
Everything in [repository_locations.bzl](https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl) and [build_recipes](https://github.com/envoyproxy/envoy/tree/master/ci/build_container/build_recipes).

**Comment by mattklein123** [comment]
Closing as answered.
