### ISSUE TITLE
Question: Can I use envoy as a tcp proxy for multiple backends?

### ISSUE THREAD

**Issue by ashish235** [envoyproxy/envoy#3421]
Hi team,

Total newbie here! 

I 'm not trying to envoy as a side-car (which I get from the blogs I read on envoy) but mostly as reverse proxy with health check and load-balancing for tcp connection. The connection is Grpc based. I 've using haproxy for a long time and thought of introducing some exciting to my stack. :) So that I can later introduce features like rate-limiting etc. 

What I want is something like this. 
```
Client ---> Envoy ---> Server1
                  ---> Server2
                  --->  Server-n.
```

Now, I spent a full day with the documentation but could no where come close to a configuration, my docker doesn't start with my configurations (sighs). I think the configuration is difficult to do and I couldn't get the APIs, xDS and management server concepts. 

Can someone please help me out?

Thanks.

**Comment by mattklein123** [comment]
@ashish235 for such a general query I think you might have better luck in Slack.

**Comment by mattklein123** [comment]
Closing out. Please reopen if you have a specific bug to track, but for general user questions we prefer slack or envoy-users@. Thank you.
