### ISSUE TITLE
Which metrics stands for parallel requests from Envoy to cluster

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#34262]
I want to monitor how many parallel requests are generated by Envoy to a cluster per second.

I've read the official doc about metrics of cluster but I can't find any relative metrics about parallel requests.

I know there is a `upstream_rq_active`, but I don't think this is what I need. I need to monitor the number of parallel requests per second, I don't think parallel requests and active requests are the same thing.

Does Envoy support such a kind of metrics?

**Comment by zuercher** [comment]
All the upstream cluster stats are documented [here](https://www.envoyproxy.io/docs/envoy/v1.30.1/configuration/upstream/cluster_manager/cluster_stats).

`upstream_rq_active` represents the number of active requests at the moment stats are collected/emitted. We don't have a mechanism to track the maximum value over a period, which is think what you want.
