### ISSUE TITLE
kick out expired connections

### ISSUE THREAD

**Issue by penghuazhou** [envoyproxy/envoy#34275]
*Title*: *One line description*
kick out expired connections

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.
How to kick out expired connections when envoy accesses LBs outside the K8S cluster and some connections keep accessing timeout? For example, if an endpoint has 10 connections, 1 connection is abnormal, and 9 connections are normal, this abnormal connection keeps requesting timeout and the server does not return RST.

**Comment by penghuazhou** [comment]
> Seems like you need to enable [health checking](https://www.envoyproxy.io/docs/envoy/v1.30.1/intro/arch_overview/upstream/health_checking.html#health-checking) for your upstream cluster. You might also consider [outlier detection](https://www.envoyproxy.io/docs/envoy/v1.30.1/faq/load_balancing/transient_failures.html#outlier-detection).

@zuercher , But in this case， there only on endpoint，so outlier detection can not use for this case. If client send business request every second, as keepalive_time should 1s to send probe，so it also can not use for this case.

**Comment by zuercher** [comment]
It sounds like perhaps you're using DNS to find a kubernetes service endpoint. I think in this case STRICT_DNS [cluster type](https://www.envoyproxy.io/docs/envoy/v1.30.1/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-cluster-type) should be used, not LOGICAL_DNS. Also on the cluster object, you might want to look at the dns_refresh_rate and dns_failure_refresh_rate or respect_dns_ttl. 

You never said what protocol is in use, but if it's HTTP, you can set the cluster's [typed_extension_protocol_options](https://www.envoyproxy.io/docs/envoy/v1.30.1/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions) to add idle timeouts set a max connection duration, etc. You can set the cluster's max_requests_per_connection to 1 to force connections to be closed after each request to prevent connection reuse.
