### ISSUE TITLE
transport socket extension: gRPC TSI based ALTS support

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#3429]
*Description*:

The proposal is to upstream the [ALTS](https://cloud.google.com/security/encryption-in-transit/application-layer-transport-security/) support based on [gRPC TSI (transport socket interface)](https://github.com/grpc/grpc/blob/master/src/core/tsi/transport_security_interface.h) implementation to Envoy main repo.

The current implementation have two part:
- gRPC TSI based `TransportSocket` implementation which may be reused to implement other gRPC based transport security (e.g. TLS)
- ALTS specific `TransportSocketConfigFactory` to instantiate the `TransportSocket`.

cc @alyssawilk @htuch 

[optional *Relevant Links*:]
Existing implementation:
https://github.com/istio/proxy/tree/master/src/envoy/alts

**Comment by alyssawilk** [comment]
I believe this falls neatly under our new extension policy, so I think this should be good to go.

**Comment by danzh2010** [comment]
I think this is not done yet.
