### ISSUE TITLE
Cannot get logging to work from a Go filter

### ISSUE THREAD

**Issue by hitman-codehq** [envoyproxy/envoy#34318]
*Title*: *I cannot get logging to work from a Go filter*

*Description*:
I am trying to get logging to work with the envoy/examples/golang-http example, but I cannot make it work. I am using the following configuration in the envoy.yaml file.

    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

Then, in envoy/examples/shared/envoy/Dockerfile I use the following startup command:

CMD ["/bin/sh", "-c envoy.yaml --log-level debug"]

But I never get any debug logs. It's also not 100% clear if I am editing the correct Dockerfile, or where the run_envoy.sh file referenced by the Dockerfile is coming from. It's quite an opaque process and I have wasted 2 hours trying to get this to work.

I need to get some calls to fmt.Printf() working in the Go code so that I know what's going on in the callback routines.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by doujiang24** [comment]
> CMD ["/bin/sh", "-c envoy.yaml --log-level debug"]

It seems an invalid command, could you confirm the docker container is running?

For the logging, `fmt.Printf()` will write to stdout, you could see the logs in the stdout of the docker container.

**Comment by hitman-codehq** [comment]
Hmm I'm not sure what I was doing wrong, but when I left this for a couple of weeks and came back to it, it was working perfectly. My apologies for the false alarm.
