### ISSUE TITLE
Missing releases for envoy-windows docker images

### ISSUE THREAD

**Issue by dimo414** [envoyproxy/envoy#34324]
The [documentation](https://www.envoyproxy.io/docs/envoy/v1.30.1/start/install.html#install-envoy-on-windows) indicates that there are recent Envoy images for Windows:

> You can run Envoy using the official Windows Docker image.
> ```
> docker pull envoyproxy/envoy-windows:v1.30.1
> docker run --rm envoyproxy/envoy-windows:v1.30.1 --version
> ```

However it appears only releases up to 1.28.0 and 1.27.2 have actually been published to Docker Hub: https://hub.docker.com/r/envoyproxy/envoy-windows/tags

I know there is some question about the [status of Windows support](https://github.com/envoyproxy/envoy/issues/28588), however the existing documentation for these releases indicates it's still supported. It would be great if images and/or binaries could be made available for any releases that includes Windows support, and for the documentation and changelogs to reflect which releases lack Windows support.

**Comment by dimo414** [comment]
The last update on #28588 was that Microsoft was staffing keeping the lights on. Did that change?

**Comment by phlax** [comment]
@dimo414 as mentioned elsewhere if there are users that require a Windows Envoy build i would suggest setting up a downstream project with any required workarounds etc and the necessary CI

**Comment by dimo414** [comment]
Thanks, I appreciate that staffing Windows support may be infeasible, but it would be great if the published documentation could be corrected to reflect that. I'm not sure which elsewhere's you're referring to, but the documentation still indicates Windows is supported.

**Comment by phlax** [comment]
update PR landed https://github.com/envoyproxy/envoy/pull/34328

**Comment by dimo414** [comment]
Thanks! It would also be helpful if this change was captured in the changelogs of [1.27.3](https://www.envoyproxy.io/docs/envoy/v1.27.3/version_history/v1.27/v1.27.3) and [1.28.0](https://www.envoyproxy.io/docs/envoy/v1.28.0/version_history/v1.28/v1.28.0) - those are the first places I looked for information about support being dropped.

If it's possible to correct the older releases' docs like [1.27.3](https://www.envoyproxy.io/docs/envoy/v1.27.3/start/install.html#install-envoy-on-windows) as well, as they still suggest these images exist.

**Comment by dimo414** [comment]
Go away stalebot

**Comment by phlax** [comment]
@dimo414 im going to close this as there are no further actions

the releases are immutable - so there wont be any updates to existing releases that had the windows docs but no image - the latest docs on each branch have been updated
