### ISSUE TITLE
http: want max-connection-duration variant that will only send Connection:close responses and never drain from proxy

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#34356]
*Title*: http: want max-connection-duration variant that will only send Connection:close responses and never drain from proxy

*Description*:
Currently, when max-connection-duration is reached for H1, the proxy will send a Connection:close response on the next response. However, if the client does not close the connection within the drain timeout, the conection will be forcibly closed.

This creates a scenario where a client that was idle may try to initiate a new request on the connection while Envoy is closing it. If this request is a POST it is likely not to be retried.

I would like a variant of max-connection-duration that never closes the connection from the server side, and only relies on the client to close the connection on the next Connection:close. This suites the use-case of where we have scaled up the number of Envoys able to handle a request, but the clients are keeping live connections to the original, smaller set of Envoys, and their connections never get redistributed to the new Envoys. In this scenario, if there are no requests, then we don't really have a connetion distribution problem, so it's fine to just leave the connection open until the next request.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by jmarantz** [comment]
This would be no worse than the configuration *not* including max-connection-duration, right?

I'm not suggesting never to drain for any reason; just not to drain based on this new variant of max-connection-duration.

One way to implement this I guess is to have a separate drain-timeout that we use for max-connection-duration, defaulting to the main drain-timeout.

**Comment by kyessenov** [comment]
I see, so you want to separate max-connection-duration handling from the drain sequence. LDS-driven drain will work as before. That makes sense to me.

**Comment by krajshiva** [comment]
+1
