### ISSUE TITLE
Question on how to build envoy with prebuild dependencies

### ISSUE THREAD

**Issue by georgi-d** [envoyproxy/envoy#3436]
I have been trying to run the steps for the [Production environment](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#production-environments) build from the documentation.

If I understand this correctly and the `ci/WORKSPACE` is a working example I should be able to:

```
% cd /home/projects/
% git clone https://github.com/envoyproxy/envoy.git
% cd envoy/ci
   #  place dependencies in /home/projects/ci/prebuild/thirdparty_build
% bazel build --package_path /home/projects/envoy //source/exe:envoy-static
```
When I run these steps I get the following error:
```
ERROR: error loading package '': Encountered error while reading extension file 'bazel/repositories.bzl': no such package '@envoy_api//bazel': Traceback (most recent call last):
        File "/home/projects/envoy/bazel/repositories.bzl", line 116
                ctx.symlink(ctx.path(ctx.attr.api).dirname.g...), ...)
        File "/home/projects/envoy/bazel/repositories.bzl", line 116, in ctx.symlink
                ctx.path(ctx.attr.api)
Unable to load package for @envoy//api:BUILD: not found.
ERROR: error loading package '': Encountered error while reading extension file 'bazel/repositories.bzl': no such package '@envoy_api//bazel': Traceback (most recent call last):
        File "/home/projects/envoy/bazel/repositories.bzl", line 116
                ctx.symlink(ctx.path(ctx.attr.api).dirname.g...), ...)
        File "/home/projects/envoy/bazel/repositories.bzl", line 116, in ctx.symlink
                ctx.path(ctx.attr.api)
Unable to load package for @envoy//api:BUILD: not found.
INFO: Elapsed time: 0.566s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Could you let me know what am I missing?

Thanks

**Comment by georgi-d** [comment]
Can I get an update on this question?

Thanks

**Comment by georgi-d** [comment]
@htuch  Could you answer this question?

Thanks

**Comment by htuch** [comment]
@georgi-d you have to have literally `bazel build --package_path %workspace%:<path to Envoy source tree> //source/exe:envoy-static`, i.e. the `%workspace%:` needs to be there.

**Comment by georgi-d** [comment]
@htuch Thanks for the reply.

I tried adding %workspace% and now it seems to start working but still fails:

```
% bazel build --package_path %workspace%:/home/projects/envoy //source/exe:envoy-static
Extracting Bazel installation...
..........................
Loading:
Loading: 0 packages loaded
DEBUG: /home/.cache/bazel/_bazel_username/82e6adcfecaf6358cfa23f1a6d8e8c04/external/io_bazel_rules_go/proto/def.bzl:133:3: You no longer need to call proto_register_toolchains(), it does nothing
Loading: 0 packages loaded
    currently loading: source/exe
Loading: 0 packages loaded
    currently loading: source/exe
Loading: 0 packages loaded
    currently loading: source/exe
Analyzing: target //source/exe:envoy-static (1 packages loaded)
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': no such package '@envoy//bazel': /home/.cache/bazel/_bazel_username/82e6adcfecaf6358cfa23f1a6d8e8c04/external/envoy must be an existing directory
INFO: Elapsed time: 17.824s
FAILED: Build did NOT complete successfully (2 packages loaded)
```

**Comment by htuch** [comment]
@georgi-d the workspace in `ci/WORKSPACE` is setup for the CI environment and its paths (see the absolute path `/source` in the `local_repository` for Envoy). You'll need to modify to use this outside Docker or in your environment.

**Comment by georgi-d** [comment]
@htuch Thanks again,

I was able to proceed further by overriding the envoy repository location
```
bazel build --package_path %workspace%:/home/projects/envoy --override_repository=envoy=/home/projects/envoy //source/exe:envoy-static
```
Now the bazel finds the packages and starts the compilation.

I think it would be very helpful if a more detailed description was present in the documentation. At least explaining that the `local_repository` location needs to be updated or overridden on the command line.

**Comment by htuch** [comment]
@georgi-d PRs welcome; since you have direct experience doing this you might be best positioned to add the bridging text from the user perspective here.

**Comment by georgi-d** [comment]
@htuch  I will prepare a pull request.
