### ISSUE TITLE
MongoProxy filter update is required.

### ISSUE THREAD

**Issue by eottabom** [envoyproxy/envoy#34365]
*Title*: *MongoProxy filter update is required*

*Description*:

Currently, the MongoProxy filter does not work with 3.6 or later versions.
The following error occurs in the Envoy log.

"mongo decoding error: invalid mongo op 2013"

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/mongo_proxy/proxy.cc#L341

Mongo DB has the following opcode.

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/mongo_proxy/codec.h#L25-L34

https://www.mongodb.com/docs/manual/reference/mongodb-wire-protocol/

OP_MSG has been added since Mongo db 3.6.
https://www.mongodb.com/docs/v3.6/reference/mongodb-wire-protocol/

In the past, similar problems have been fixed.
https://github.com/envoyproxy/envoy/issues/2745

**Comment by zuercher** [comment]
cc @mythra @giantcroc

**Comment by eottabom** [comment]
@zuercher 

Similar issues have been registered before.

https://github.com/envoyproxy/envoy/pull/5053
https://github.com/envoyproxy/envoy/issues/5648
https://github.com/envoyproxy/envoy/issues/31810

But it's not progressing any further.

The Special Envoy should consider this matter.

MongoDB is being used a lot.
https://db-engines.com/en/ranking

**Comment by Mythra** [comment]
Yeah this is an unfortunate position of the mongodb filter. Most of the actual companies have pulled out of using the mongo filter (or are on older forks of mongo) today.

Updating the mongo functionality to include the new op-codes, and other functionality required for current mongo is a pretty massive underlying change. We can definitely keep it working and updated in terms of envoy side of things, but no one has had time to devote to doing all the updates for newer mongo versions yet (and there hasn't been much drive from the folks who did/are using it historically).

**Comment by Mythra** [comment]
I'd definitely be interested in providing support if someone wanted to take on adding this support starting with the opcodes, but I unfortunately don't have the time unfortunately at the moment to write all the code for it.

**Comment by eottabom** [comment]
@Mythra

If so, will the support for mongo filter be discontinued in the future?

Do you have no plans in the future?

**Comment by eottabom** [comment]
Please let me know if you have any future plans for mongo filter.

**Comment by zuercher** [comment]
Someone who wants support for this will have to step up and make the necessary changes. 

I’m going to close this in favor or #31810 since it has some references to PRs that might help if someone picks this up.
