### ISSUE TITLE
OpenTelemetry access logger support extension formatters

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#34374]
[Access log formatters](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/formatter/formatter) is supported in file access logger, but not in OpenTelemetry access logger.

there's two options here:
1. add `formatters` into [OpenTelemetryAccessLogConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto#envoy-v3-api-msg-extensions-access-loggers-open-telemetry-v3-opentelemetryaccesslogconfig)
2. enable all `formatters` by default.

WDYT?

**Comment by zuercher** [comment]
cc @itamarkam @yanavlasov

**Comment by itamarkam** [comment]
I don't have a strong opinion here, but if in the file access logger you need to specify the formatters explicitly, then it makes sense in OTel as well IMO.
WDYT @yanavlasov?

**Comment by wbpcode** [comment]
>. I don't have a strong opinion here, but if in the file access logger you need to specify the formatters explicitly, then it makes sense in OTel as well IMO.

👍

**Comment by zirain** [comment]
fixed by #34469
