### ISSUE TITLE
Passive TLS inspector

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#34396]
*Title*: Passive TLS inspector

*Description*:
Envoy currently provides a tls_inspector. This is handy for many use cases.

One use case it is _not_ great for is proxying arbitrary traffic, and logging TLS attributes (generally, the SNI). Use of the inspector causes blocking until enough data is read, which will never happen for server-first protocols like mysql.

Instead, I would like a 'passive' inspector. Data will flow through as-normal, but if it is found to be TLS, some state is stored. Eventually, I would expect to be able to log the SNI on connection termination using the standard access logger

**Comment by hobbytp** [comment]
@howardjohn can I understand that it will also benefit StartTLS handling?

**Comment by howardjohn** [comment]
I don't know much about StartTLS but I think that is unrelated and already supported by envoy

**Comment by howardjohn** [comment]
Can we reopen this?
