### ISSUE TITLE
The possibility to extend Envoy metrics to emit custom-metrics in addition to the Envoy existing built-in metrics.

### ISSUE THREAD

**Issue by ppourali** [envoyproxy/envoy#34415]
*Title*: *The possibility to extend Envoy metrics to emit custom-metrics in addition to the Envoy existing built-in metrics.*

*Description*:
Envoy already emits many metrics in the `stats` endpoint. Can we add some extra/custom metrics for our bootstrap extension to it? If yes, any *how-to* link?

To give you context, I have a bootstrap extension that I want to emit custom metrics within that extension process. I was think of using something like the code below but it does not work.

```

// Envoy::Server::Configuration::ServerFactoryContext* server_context_;

Envoy::Stats::CounterSharedPtr counter =
      new Envoy::Stats::NullCounterImpl(
          server_context_->serverScope().symbolTable());
  counter->add(n);
  counter->incRefCount();

  server_context_->serverScope()
      .store()
      .createScope("mycustomerextentionmetric")
      ->store()
      .counters()
      .push_back(counter);
```

Thanks,
Parsa

**Comment by jmarantz** [comment]
there's some discussion of the stats architecture here: https://github.com/envoyproxy/envoy/blob/main/source/docs/stats.md

This is not really a how-to guide to add new stats but it might be a good start, as well as grepping around the source.

It also might be interesting to explore the codebase using the sourcegraph tool, e.g. with this as a starting point: https://sourcegraph.com/github.com/envoyproxy/envoy/-/blob/source/common/stats/utility.h?L95:16&popover=pinned

**Comment by ppourali** [comment]
Thanks Joshua for the links. I ended up using adding the metric using 

```
scope_ = server_context_->scope().createScope("mymetric")
stats_ = {ALL_TCP_PROXY_STATS(POOL_COUNTER(*scope), POOL_GAUGE(*scope))};
```

from my extension and it worked. I think the important part is to keep the pointer to the created scope and the stat itself alive for the lifetime of the server since they seem to be a RefPointer.

Thanks,
Parsa

**Comment by praveenjindal62** [comment]
@ppourali  I have similar requirement, could you please guide me how to add custom metric to envoy ?
