### ISSUE TITLE
Inconsistent behavior between Base64::decode() and Hex::decode().

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#3442]
`Base64::decode()` returns `EMPTY_STRING` when input is wrong.
`Hex::decode()` throws exception when input is wrong.

Both should behave the same. Any preference which behavior is adopted?

I have slight preference for returning `std::vector<uint8_t>{}` from `Hex::decode()`.

cc @mattklein123

**Comment by mattklein123** [comment]
@PiotrSikora no real preference. I would look at the call sites and just see which type of error handling is cleaner.
