### ISSUE TITLE
What's the single Envoy instance memory cost in your production environment ? 

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#34467]
*Title*: *What's the single Envoy instance memory cost  in your production environment ? *

*Description*:
>As we know envoy instance will be widely deployed in the sidecar container as proxy when using in service mesh cases, so do we have any memory resource optimization best practice can be shared ? 
We are trying to using Envoy in the Embedded system which with limit memory resource , so memory cost optimization is an important thing for us.

So what's the memory cost for since envoy instance in your production env , any optimization practice can be shared ?

**Comment by wufanqqfsc** [comment]
@adisuissa  thanks for your comments.
For item1: We reduce our single instance memory cost to about 30M after remove the unnecessary extensions for us. 
For Item2 : we will check further.
And this Item3: any tools can be shared for memory check ?  
The current memory per instance cost already meet our target , but we want to know the limits of single instance after optimize

**Comment by adisuissa** [comment]
pprof is the typical tool used.
This doc may also help: https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/how_to_dump_heap_profile_of_envoy
