### ISSUE TITLE
Status Details Pass Through for LocalResponsePolicy

### ISSUE THREAD

**Issue by dspencer12** [envoyproxy/envoy#34465]
*Title*: *Status Details Pass Through for LocalResponsePolicy*

*Description*:

When using a local response policy (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/custom_response/local_response_policy/v3/local_response_policy.proto) to alter responses before returning them to the client, the `RESPONSE_STATUS_DETAILS` field in the access logs is empty.

In some cases, it's useful to preserve `RESPONSE_STATUS_DETAILS` as this can aid debugging failed requests.

Proposing to modify https://github.com/envoyproxy/envoy/blob/main/source/extensions/http/custom_response/local_response_policy/local_response_policy.cc#L81 to something like:

```
const absl::optional<std::string>& details = encoder_callbacks->streamInfo().responseCodeDetails();
encoder_callbacks->sendLocalReply(code, body, mutate_headers, absl::nullopt, details.has_value() ? *details : "");
```

If the current behavior needs to be preserved as the default, we could introduce a boolean option that controls whether the status details are passed through, or dropped.

I would like to work on this feature, but would first like to confirm if we should make this behavior configurable?

**Comment by dspencer12** [comment]
@pradeepcrao Please could you take a look at this issue and let me know what you think? Thanks!

**Comment by pradeepcrao** [comment]
Hi Daniel, 

Sorry for the late response. The original response code details might not be the right thing to return in this case as the local response policy is overriding the original response. 

It might make sense to make this configurable (https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/http/custom_response/local_response_policy/v3/local_response_policy.proto#L27) to either send back the original response code details, or have a new value defined for the `LocalResponsePolicy`.

**Comment by dspencer12** [comment]
Thanks Pradeep, that sounds good to me. I'll let you know when I have a PR for this change
