### ISSUE TITLE
Envoy and ACl

### ISSUE THREAD

**Issue by g0a019a** [envoyproxy/envoy#34473]
*Title*: *Integrate ACL to Envoy*

*Description*:
>Hi Team I am trying to make ACL enable for envoy and did envoy configuration in json file.However I am getting an error for Suppressed: redis.clients.jedis.exceptions.JedisDataException: unsupported command 'CLUSTER' in Lettuce client. 
Without ACL it doesn't gave me this error.After passing ACL credentails I am getting this error. Can someone help me in this.

**Comment by g0a019a** [comment]
What config changes should I make to work it? 
In envoy documentation it says 

> "Envoy proxy tracks the topology of the cluster by sending periodic [cluster slots](https://redis.io/commands/cluster-slots) commands to a random node in the cluster," however with ACL it seems it is failing. 

<img width="940" alt="Screenshot 2024-06-02 at 3 20 17 PM" src="https://github.com/envoyproxy/envoy/assets/95848012/9f973b03-9550-42ba-b0e0-32ecc1c08d64">

**Comment by adisuissa** [comment]
cc @msukalski @henryyyang @mattklein123 @weisisea as code-owners.

**Comment by weisisea** [comment]
Could you please share your configurations?

I suspect that the upstream auth username and password are not configured properly:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/redis_proxy/v3/redis_proxy.proto.html#extensions-filters-network-redis-proxy-v3-redisprotocoloptions
