### ISSUE TITLE
Add ability to strip out failure response details in JWT Authentication filter

### ISSUE THREAD

**Issue by arulthileeban** [envoyproxy/envoy#34474]
*Title*: *Add ability to strip out failure response details in JWT Authentication filter*

*Description*:

> When a request fails the verification process of the JWT Authentication filter, the failure reason is sent back in the body of the response along with www-authenticate header containing error="invalid_token". This might lead to unintended leakage of data to a malicious user in certain cases. A boolean config "strip_failure_response" could be introduced which upon setting would only return a 401 without any additional details to downstream.

**Comment by adisuissa** [comment]
cc @taoxuy as code-owner
