### ISSUE TITLE
Expose more details for protocol errors

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#34472]
In our production envrinoment, sometimes we meet such 502 error in access log.  Can envoy expose more details which kind of protocol errors?

```
response_code="502", response_code_details="upstream_reset_before_response_started{protocol_error}", response_flags="UPE"}
```

**Comment by adisuissa** [comment]
Can you please provide more details on what are your expectations in this case?
cc @alyssawilk

**Comment by zhangbo1882** [comment]
@adisuissa , we can see many details about the protocol error from the doc https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/response_code_details#http1-details.
But from access log, I can not get it.

**Comment by zhangbo1882** [comment]
From my first comment, the response_code_details is "upstream_reset_before_response_started{protocol_error}"
My question is that which kind of protocol error.

**Comment by alyssawilk** [comment]
gotcha.  yes more details are welcome
