### ISSUE TITLE
Document using **container** image in **read-only** vs. read-write mode

### ISSUE THREAD

**Issue by enspritz** [envoyproxy/envoy#34499]
*Title*: Document using **container** image in **read-only** vs. read-write mode

*Description*: 

A) Document the ins and outs of running the `envoyproxy/envoy` container in read-only mode vs. read-write mode. What is best practice, especially from a security standpoint. For example, even if the container itself is read-only, does  `/tmp` still need to be mounted read-write?

B) Genericize away from "Docker" language in favor of "Container" and "OCI". So for the main page in the docs, the title might be "Using the Envoy container image". For SEO, of course it's worth to emphasize Docker early and often, but also mention Podman and whatever else. We are using Envoy with both podman and docker here, and are looking to eventually discard Docker altogether.

[optional *Relevant Links*:]
Page in the documentation,  version 1.30.1 (current at time of this writing): [Using the Docker Envoy image](https://www.envoyproxy.io/docs/envoy/v1.30.1/start/docker)

Thanks!

**Comment by phlax** [comment]
hi @enspritz regarding A - i would welcome any PR that clarifies how to run in read-only mode

Not sure i follow exactly about `/tmp` - the build container mounts this and its absolutely necessary (esp if in readonly mode) - for the runtime image it would depend on how you set it up.

regarding using generic container language im a bit more ambivalent - we test, and therefore can support running in Docker.

for example, there was an issue someone raised regarding permissions trying to run with podman (this was for the build container) which is not tested or supported and there are less of us with the skills/experience to debug or support resolving such issues

**Comment by enspritz** [comment]
@phlax Thanks -- Your input is exactly the kind of knowledge that will bolster the documentation. The doc page cluster in question concerns running the container and not building, so we can keep scope narrowed to that. It's clear about how to run the container as well as the user ID the daemon runs as, it's default value, how to change it and the effects of doing so, but says nothing re: read-only vs. read-write mode, which from a security standpoint is a conspicuous absence. Lemme attempt a PR to address that.
