### ISSUE TITLE
ext_proc: Improve the test coverage on matching_utils

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#34496]
From coverage report the matching_utils.h 's coverage is only 76.2% which is way below threshold.
https://storage.googleapis.com/envoy-pr/27f6f9d/coverage/source/extensions/filters/http/ext_proc/index.html
https://storage.googleapis.com/envoy-pr/27f6f9d/coverage/source/extensions/filters/http/ext_proc/matching_utils.cc.gcov.html

This issue has been hidden because other components in ext_proc have relatively high coverage.

**Comment by tyxia** [comment]
/assign @jbohanon 

Since this file was added by you, could you please address this issue.

Improving the coverage will be very helpful (1)to validate the correctness of matching_utils and (2) make other ext_proc's developers life easy: slightly below threshold in other components will trigger coverage error that blocks development

**Comment by jbohanon** [comment]
Thanks for assigning; I will get a chance to broaden this coverage sometime in the next couple weeks
