### ISSUE TITLE
Provide a way to attach dynamic data to Host object

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#34529]
*Title*: *Provide a way to attach dynamic data to Host object*

*Description*:
I'm prototyping a new LB policy that will calculate host weights for WRR locally, based on custom headers attached to the backend responses.

The LB policy needs to keep dynamic internal data on per host basis, similar to [HostDescription::metadata()](https://github.com/envoyproxy/envoy/blob/cdb18db458d8d022319ff5b39d2566b00e80ea70/envoy/upstream/host_description.h#L117)

I think [FilterState](https://github.com/envoyproxy/envoy/blob/cdb18db458d8d022319ff5b39d2566b00e80ea70/envoy/stream_info/filter_state.h#L53) serves similar purpose, but it doesn't attach to a Host.

Are there better alternatives, or would it be possible to attach dynamic data (similar to FilterState) to a `Host` or `HostDescription`?

**Comment by tonya11en** [comment]
Are you trying to do something where the upstream hosts report their load via response headers and scale weights based on this? If so, it's the same as the ongoing conversation in https://github.com/envoyproxy/envoy/issues/20907.

Otherwise, if you're implementing a custom LB extension are you not able to modify the Host objects in the implementation or keep some mapping of host->derived weight?

**Comment by efimki** [comment]
Yes, I'm trying to implement a [ClientSideWeightedRoundRobin](https://github.com/envoyproxy/envoy/blob/cdb18db458d8d022319ff5b39d2566b00e80ea70/api/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.proto#L38) LB Policy that would use [LoadMetricStats](https://github.com/envoyproxy/envoy/blob/cdb18db458d8d022319ff5b39d2566b00e80ea70/envoy/upstream/host_description.h#L199) collected by an upstream filter that extracts them from response headers in the format of [OrcaLoadReport](https://github.com/cncf/xds/blob/main/xds/data/orca/v3/orca_load_report.proto).

**Comment by efimki** [comment]
Are you suggesting to extend `Host` object specifically in custom LB extension or something else? 
Keeping some mapping of host->derived is certainly an option, but seems a bit clunky.
