### ISSUE TITLE
 Envoy regression after version upgrade: listener update time increase and unstable XDS connection

### ISSUE THREAD

**Issue by haoruolei** [envoyproxy/envoy#34531]
**Title**:  Envoy regression after version upgrade: listener update time increase and unstable XDS connection

**Description**:
 Hi Envoy team, I'm reaching out regarding some performance regressions observed after upgrading envoy from 1.26.6 to 1.29.2. Here are our service settings:
1. Envoy with SotW ADS
2. Custom ADS server with newest Envoy go-control-plane to create and update Envoy resources
3. In total around 4000 Envoy clusters/routes with frequent updates
4. 10+ filters per filter chain, some of them are discovered through ECDS

Here are some symptoms of the system degradation:
1. Listener config update time has doubled from 10-13s to 23-29s. This is from envoy debug lines. e.g:
```
[2024-06-03T22:37:43.629636Z][Envoy][24][debug][config]gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener accepted with 2 resources with version cde80a8b-f548-4c3e-a157-5978b6a07a9f
[2024-06-03T22:37:43.629639Z][Envoy][24][debug][config]gRPC config update took 30322 ms! Resources names: http-listener,http-private-listener
```
2. envoy_server_dispatcher_loop_duration metric has increased a lot. Below is a comparison of p50 values with envoy 1.26 (orange) and 1.29 (purple) in the same time frame getting updates from the same ADS server.
<img width="677" alt="Screenshot (86)" src="https://github.com/envoyproxy/envoy/assets/109187153/c93d68ce-acbc-4885-bc92-e4195b95aff1">

3. gRPC connection to control plane keeps close and reopening. This can be seen from envoy_control_plane_connected_state metric.
<img width="681" alt="Screenshot (87)" src="https://github.com/envoyproxy/envoy/assets/109187153/8508d759-cbd6-4582-93fd-19e4777729e5">

Below are example logs when the disconnection happens. Envoy debug log:

```
[2024-06-03T22:37:43.629636Z][Envoy][24][debug][config]gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener accepted with 2 resources with version cde80a8b-f548-4c3e-a157-5978b6a07a9f
[2024-06-03T22:37:43.629639Z][Envoy][24][debug][config]gRPC config update took 30322 ms! Resources names: http-listener,http-private-listener
[2024-06-03T22:37:43.649212Z][Envoy][24][debug][config]Decreasing pause count on discovery requests for type.googleapis.com/envoy.config.listener.v3.Listener (previous count 1)
[2024-06-03T22:37:43.649240Z][Envoy][24][debug][config]Resuming discovery requests for type.googleapis.com/envoy.config.listener.v3.Listener
[2024-06-03T22:37:43.732662Z][Envoy][24][debug][connection][Tags: "ConnectionId":"1"] onAboveWriteBufferHighWatermark
[2024-06-03T22:37:43.757947Z][Envoy][24][debug][connection][Tags: "ConnectionId":"1"] onBelowWriteBufferLowWatermark
[2024-06-03T22:37:43.760731Z][Envoy][24][debug][connection][Tags: "ConnectionId":"154103"] closing socket: 0
[2024-06-03T22:37:43.760796Z][Envoy][24][debug][client][Tags: "ConnectionId":"154103"] disconnect. resetting 1 pending requests
[2024-06-03T22:37:43.760804Z][Envoy][24][debug][client][Tags: "ConnectionId":"154103"] request reset
[2024-06-03T22:37:43.760816Z][Envoy][24][debug][pool][Tags: "ConnectionId":"154103"] destroying stream: 0 remaining
[2024-06-03T22:37:43.760836Z][Envoy][24][debug][router][Tags: "ConnectionId":"0","StreamId":"7555028093046997324"] upstream reset: reset reason: connection termination, transport failure reason: 
[2024-06-03T22:37:43.760859Z][Envoy][24][warning][config]StreamAggregatedResources gRPC config stream to xds_cluster closed: 13, 
```
go-control-plane gPRC logs have two types of errors
```
INFO: [transport] [server-transport 0xc0001d8900] Closing: EOF
INFO: [transport] [server-transport 0xc0001d8900] loopyWriter exiting with error: write tcp 127.0.0.1:8081->127.0.0.1:14283: write: connection timed out
```
or 
```
INFO: [transport] [server-transport 0xc00918a000] Closing: read tcp 127.0.0.1:8081->127.0.0.1:25491: read: connection timed out
INFO: [transport] [server-transport 0xc00918a000] loopyWriter exiting with error: transport closed by client
```

**Ruled Out Theories:**
We have explored several possible theories and tried to address the issue. Posting some details as well in case it helps.

1. DeltaXDS
Given the increased listener update time, we have switched to DeltaXDS from SotW. Unfortunately this didn't help to alleviate the regression.

2. XDS static cluster settings
Envoy documentation has suggested to Configuring either TCP keep-alives or HTTP/2 keepalives in the cluster that connects to the management server to maintain healthy connections: [link](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/mgmt_server.html#management-server-unreachability)
From our experiments, neither more nor less aggressive keepalive settings solved the issue. We still observed frequent XDS connection close.

3. Config size
Another theory is that Envoy config size expanded after the upgrade and overwhelmed the connection or Envoy itself. We have compared the sizes of Clusters/Listeners/Routes/TypedExtensionConfigs between 1.26 and 1.29, and there're no significant changes.

**Possible Rootcause:**
The issue seems to be narrowed down to the listener update time increase itself. We did some experiments to see if we can target certain types of filters causing the latency. Here are some findings:
a. When removing all 14 filter types and only leaving the http router filter, listener update time is 9-11s. 
b. When adding just one of the 14 filter types, the listener update time increased slightly between 0-2s.
c. When all 14 filters are enabled, the listener update time is stacked up to 23-29s.
d. For comparison, when all 14 filters enabled but with Envoy 1.26, total listener update time is 11-14s.

**We don't see a single filter that has oversized impact but when all of them added up, the listener update time got 14s+ slower. Another interesting behavior we noticed is that whenever listener update time goes above 20s, XDS connection started to close unexpectedly. This behavior is consistent regardless of exact filter combinations.**

We're hoping to get some help from the Envoy community on this issue. Please let us know if you need more information, thanks!

**Comment by adisuissa** [comment]
Thanks for providing the info.

A few questions/comments:
> a. When removing all 14 filter types and only leaving the http router filter, listener update time is 9-11s.

I assume 9-11s is the listener update time when using Envoy v1.29. What is it when using Envoy v1.26?

> b. When adding just one of the 14 filter types, the listener update time increased slightly between 0-2s.
> c. When all 14 filters are enabled, the listener update time is stacked up to 23-29s.

If adding a single filter adds 0-2 secs, then (assuming linearity) 14 filters will add 0-28secs.
I wonder if there are different additional timings for different filter types, or is it just an additional time for all the filters.

I'm trying to understand why the disconnect happens. Envoy doesn't initiate a disconnect, so I wonder if there's something else in play here.
Can you run the test with trace-level logs?
Also are you using an EnvoyGrpc or GoogleGrpc ADS config?

**Comment by haoruolei** [comment]
Hi @adisuissa Thanks for your questions. Please see below for details.

> > a. When removing all 14 filter types and only leaving the http router filter, listener update time is 9-11s.
> 
> I assume 9-11s is the listener update time when using Envoy v1.29. What is it when using Envoy v1.26?
> 
The listener update time with all filters enabled for Envoy v1.26 is 11-14s, which is comparable to v1.29 with all filters disabled.
> > b. When adding just one of the 14 filter types, the listener update time increased slightly between 0-2s.
> > c. When all 14 filters are enabled, the listener update time is stacked up to 23-29s.
> 
> If adding a single filter adds 0-2 secs, then (assuming linearity) 14 filters will add 0-28secs. I wonder if there are different additional timings for different filter types, or is it just an additional time for all the filters.
> 
We do see differences in added time for different filter types. Some filters added only 500ms. Some of the filters with more significant overhead are: 1. JWT filters (~2s) 2. ExtAuthz filters (~2s) 3. Http Local Ratelimit filters (~2s)
> I'm trying to understand why the disconnect happens. Envoy doesn't initiate a disconnect, so I wonder if there's something else in play here. Can you run the test with trace-level logs? Also are you using an EnvoyGrpc or GoogleGrpc ADS config?

I have shared some debug logs in the original post. We have also ran with trace logs but there were a lot of noises. Please let me know if there're specific logs that you're looking for. And we're using the default Grpc config, which I believe is EnvoyGrpc.

Please let me know if there're anything missing. Thanks!

**Comment by adisuissa** [comment]
I think that a cpu-profiling may help in understanding where the time is spent.

**Comment by haoruolei** [comment]
> I think that a cpu-profiling may help in understanding where the time is spent.

sounds good. I'll collect some CPU profiling data.

**Comment by haoruolei** [comment]
> > I think that a cpu-profiling may help in understanding where the time is spent.
> 
> sounds good. I'll collect some CPU profiling data.

 Update: thanks for the patience. I haven't got the time to get CPU profilling. will work on it in the next week.

**Comment by haoruolei** [comment]
Finally able to get the CPU profiling working after addressing some blockers. Please see below for some initial data. I'll see if there's more that I can get. Also please let me know about specific data you're looking for. Thanks!
[text.txt.txt](https://github.com/user-attachments/files/17123021/text.txt.txt)
![callgraph svg](https://github.com/user-attachments/assets/a57b089d-3db3-443d-be6a-451317a7eb91)
