### ISSUE TITLE
Add metadata field to LocalityLbEndpoints

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#34530]
Add a metadata field to the [LocalityLbEndpoints](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto.html#config-endpoint-v3-localitylbendpoints) proto that would either be inherited by each LbEndpoint it contains or used for various things like `transport_socket_match`. This would dramatically reduce the size of the serialized EDS resources in situations where all of the endpoints in a locality have identical metadata fields.

## Motivation
It's currently possible to add metadata to an [LbEndpoint](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto.html#config-endpoint-v3-lbendpoint) proto for use in transport socket matching. This causes a significant increase in the size of each serialized protobuf.

An LbEndpoint without metadata is **28 bytes**:
```
endpoint:{address:{socket_address:{address:"192.168.1.2"  port_value:8080}}}  health_status:HEALTHY  load_balancing_weight:{value:1}
```

Adding a modest 2 fields of metadata increases this size by 600% to **168 bytes**:
```
endpoint:{address:{socket_address:{address:"192.168.1.2"  port_value:8080}}}  health_status:HEALTHY  metadata:{filter_metadata:{key:"envoy.transport_socket_match"  value:{fields:{key:"txallen_example.bar.identifier"  value:{string_value:"1234567890"}}  fields:{key:"txallen_example.foo.identifier"  value:{string_value:"1234567890"}}}}}  load_balancing_weight:{value:1}
```

In situations where every endpoint in a locality would share the same metadata fields, we should have the option to add metadata to the LocalityLbEndpoints that will be inherited by each  LbEndpoint contained within. This would _significantly_ benefit control planes serving/storing 1M+ EDS resources where a bunch of endpoints are duplicating metadata.

**Comment by adisuissa** [comment]
I think this is a valid request. Would need to clarify what happens when metadata is defined for both the LocalityLbEndpoints  and the LbEndpoint (probably override semantics, unless this is defined as a locality-level metadata rather than a shared-endpoints metadata).

cc @envoyproxy/api-shepherds for visibility

**Comment by tonya11en** [comment]
> I suggest we just follow the same pattern that we use everywhere else: we support metadata at both the LocalityLbEndpoint and LbEndpoint levels, and filters can use data from both places as appropriate.

Alrighty then. I'll get on it. Thanks folks!
