### ISSUE TITLE
Golang HTTP Filter: Scan Response Body and send a Local Reply

### ISSUE THREAD

**Issue by jgrnrt** [envoyproxy/envoy#34569]
*Title*: Golang HTTP Filter: Scan Response Body and send a Local Reply

*Description*:
Hello,
I somehow can't come up with a solution with myself. I have a forward envoy proxy. My Client sends a request to the envoy. And envoy is now supposed to scan the upstream response body and if there is any bad stuff, it's supposed to send a local reply.
Or maybe another way set the buffer to something else. But I also want to change the http statuscode and the grpc statuscode.

I thought of something like this:

```
func (f *filter) EncodeHeaders(header api.ResponseHeaderMap, endStream bool) api.StatusType {
	f.header = header

	return api.Continue
}

func (f *filter) EncodeData(buffer api.BufferInstance, endStream bool) api.StatusType {
	if (buffer contains stuff i dont like) {
		return f.sendLocalReplyInternal()

		or something like this:

		http Status = 404
		grpc status = 1 (like local reply)
		buffer.SetString("reset")
		return api.StopNoBuffer
	}
	return api.Continue
}

func (f *filter) sendLocalReplyInternal() api.StatusType {
	body := "response contains bad stuff"
	f.callbacks.SendLocalReply(400, body, nil, 1, body)
	return api.LocalReply
}
```

Setting the header obviously didn't work, because it's already gone, when i change it in the EncodeData-Method. Same with the LocalReply-Method this also wont work. 

Thank you in advance.

@doujiang24 

Sincerely,

Jeremy

**Comment by doujiang24** [comment]
@jgrnrt Golang HTTP Filter support streamingly processing header & data, just like Envoy C++ filters.

After returning `Continue`, Envoy may send the header to client.
```
func (f *filter) EncodeHeaders(header api.ResponseHeaderMap, endStream bool) api.StatusType {
	f.header = header

	return api.Continue
}
```

So, you need to use `StopAndBuffer` or `StopAndBufferWatermark`.
1. `StopAndBuffer` means Envoy will buffer all data, and invoke `EncodeData` when all data ready,
2. while `StopAndBufferWatermark` means streaming processing.

**Comment by jgrnrt** [comment]
This worked flawlessly. Thank you a lot.
