### ISSUE TITLE
Documentation generated from .proto file doesn't specify if something is an array/repeated

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#3458]
For instance, from https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster:

```
hosts
(core.Address) If the service discovery type is STATIC, STRICT_DNS or LOGICAL_DNS, then hosts is required.
```

It would be useful if the type said `repeated core.Address`, so similar.

**Comment by mk46** [comment]
I would like to take up this. @ggreenway Could please suggest where to start? I think need to modify `tools/protodoc/protodoc.py`

**Comment by ggreenway** [comment]
That would be great if you could work on this. I don't know where the docs are generated from, so I can't offer much guidance. @htuch did you write this originally?

**Comment by htuch** [comment]
Yes, protodoc.py, thanks for taking this on @mk46.
