### ISSUE TITLE
persist x-request-id when sanitized

### ISSUE THREAD

**Issue by guydc** [envoyproxy/envoy#34589]
*Title*: persist original x-request-id when sanitized

*Description*:
Envoy currently supports several options for the x-request-id header processing:
- Sanitize the header for [external requests](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-request-id)
- Sanitize the header and generate a new x-request-id (`generate_request_id`), ensuring that the x-request-id value is valid and sufficiently unique to correlate envoy requests with backend requests. 
- Preserve the client-provided x-request-id header (`preserve_external_request_id`)

The value of the client-provided x-request-id header is known to the client, and can be useful for correlation of client request and envoy requests. Users may want to:
- Sanitize and set the Envoy-generated value
- Forward and/or log the original x-request-id value. 

To achieve this, Envoy can save the original x-request-id header value to a new header, such as `x-envoy-parent-request-id`, `x-envoy-forwarded-request-id`, when it's sanitized.

**Comment by adisuissa** [comment]
cc @alyssawilk

**Comment by guydc** [comment]
update: it's possible to achieve the desired behavior with the `early_header_mutation` feature.
