### ISSUE TITLE
Let HTTP filters increase downstream connection buffer limit

### ISSUE THREAD

**Issue by toddmgreer** [envoyproxy/envoy#34597]
Title: Let HTTP filters increase downstream connection buffer limit

I need a way to increase the downstream connection buffer limit from an HTTP filter, in order to fully receive a response from upstream, even if the downstream connection backs up. (I'm aware that this will increases OOM risks, and will be mitigating those risks.)

My proposed solution is to:
 1. Add Envoy::Network::Connection::setWriteBufferLimit to set only the write buffer limit, and
 2. either
   a. have Envoy::Http::StreamFilterCallbacks::connection return a mutable Network::Connection, or
   b. add Envoy::Http::StreamFilterCallbacks::setDownstreamConnectionWriteBufferLimit.

The mutable Connection seems better to me, because otherwise we may want to add ways to read the limits, and to set the read limit. Are there any other approaches that seem better?

**Comment by adisuissa** [comment]
cc @alyssawilk @KBaichoo

**Comment by alyssawilk** [comment]
hm, generally I agree on wider APIs, but I could imagine folks creating lifetime issues with direct access to close so in this case I lean towards having a wrapper API.  ccing @RyanTheOptimist @yanavlasov for thoughts

**Comment by RyanTheOptimist** [comment]
> hm, generally I agree on wider APIs, but I could imagine folks creating lifetime issues with direct access to close so in this case I lean towards having a wrapper API. ccing @RyanTheOptimist @yanavlasov for thoughts

Yeah, I'd be inclined to keep a narrow API in this case to avoid potential issues like @alyssawilk mentions. If we find ourselves needing to add a bunch of these, we can certainly revisit.
