### ISSUE TITLE
Debug assertion in Delta XDS (!requested_resource_state_.empty)

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#34594]
Note: this was originally reported privately

*Description*:
[Crash logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/51437/integ-security-multicluster_istio/1798734714706595840/artifacts/security-41b48aa1f1474eb7be02ba/_suite_context/servers-1-33440-state-1815181452/remote/jwt-server-df9fbbc9d-rh742_istio-proxy.previous.log) and [another with the same issue](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/51437/integ-security-multicluster_istio/1798734714706595840/artifacts/security-41b48aa1f1474eb7be02ba/_suite_context/istio-state-2092744599/primary/istio-ingressgateway-66d9c85f89-2296d_istio-proxy.previous.log)
Version:  Envoy f4930b1ffd7c7bffec32e73f4b7c8482a72dc23a (but Istio build). From yesterday. 
[Core dump](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/51437/integ-security-multicluster_istio/1798734714706595840/artifacts/security-41b48aa1f1474eb7be02ba/_suite_context/istio-state-2092744599/primary/istio-ingressgateway-66d9c85f89-2296d_core.proxy)

The assertion has been there for a year. We do not always run these tests, so it's likely not a recent regression in Envoy.

Unfortunately, our control plane logs were truncated so we do not have the exact XDS info going on at the time. Probably I can run the test a few more times and get it if it helps. I do know that at the time of the trash, the last XDS push should have been approx 15s prior.

cc @keithmattix

**Comment by keithmattix** [comment]
I have a sneaking suspicion this is related to #34334; notice my [comment](https://github.com/envoyproxy/envoy/issues/34334). I need to refresh myself on the flow, but that debug assert is probably failing because of a poor assumption

**Comment by adisuissa** [comment]
Thanks for reporting this.
I'll follow up on @keithmattix's comment next week (should have more time to dig into this).

**Comment by howardjohn** [comment]
Here is another similar one: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/51437/integ-security-multicluster_istio/1808249482240856064/artifacts/security-c60cc84e078248b3836601/_suite_context/echo1-4-84959-state-4060061412/remote/migration-vistio-df6bc8969-rsrmr_istio-proxy.previous.log

in `isInitialRequestForLegacyWildcard` this time. There is a [core dump](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/51437/integ-security-multicluster_istio/1808249482240856064/artifacts/security-c60cc84e078248b3836601/_suite_context/echo1-4-84959-state-4060061412/remote/migration-vistio-df6bc8969-rsrmr_core.proxy).

**Comment by keithmattix** [comment]
Not stale /cc @adisuissa

**Comment by howardjohn** [comment]
Not stale, can we re-open?
