### ISSUE TITLE
`shadowAppendedHost` is too restrictive, breaking valid IPv6 host headers

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#34596]
*Description*:
`shadowAppendedHost` expects at most 1 colon in `Host`. It has a debug assertion if this is not correct.

per https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2, IPv6 addresses are legal host headers, and all clients will set them:

```
$ curl [::1]:8080 -v
> Host: [::1]:8080
```

This triggers a debug assertion.

The assertion should be removed at minimum, and possible the function improved to handle these other use cases (though, tbh, not sure -shadow appending makes sense on an IP)

**Comment by adisuissa** [comment]
Thanks for reporting this!
I assume [this](https://github.com/envoyproxy/envoy/blob/54266a082654f21b409f9d0af53a009bdd31b9de/source/common/router/shadow_writer_impl.cc#L21) is the failing assertion.
cc @paul-r-gall and @alyssawilk

**Comment by howardjohn** [comment]
Oops forgot the link, yep that is the one

**Comment by alyssawilk** [comment]
Looks like this predates @paul-r-gall and he's out so I'l pick up.
as this is a longstanding bug it's unlikely to merit backports though
