### ISSUE TITLE
Support BoringSSL's SSL_OP_CIPHER_SERVER_PREFERENCE option in Envoy Common TLS configuration

### ISSUE THREAD

**Issue by mamathavit** [envoyproxy/envoy#34604]
*Title*: *Need support for setting boringSSL's SSL_OP_CIPHER_SERVER_PREFERENCE flag in Envoy to change the cipher suite order preference*

*Description*:
When enabling TLS for listeners, I need an option to enable/disable preference of client cipher suites order. This option is available in boringSSL but not exposed in Envoy. The name of the option is SSL_OP_CIPHER_SERVER_PREFERENCE.

Below is a snippet of the option's description:
```
// If configuring a server, one may also configure equal-preference groups to
// partially respect the client's preferences when
// |SSL_OP_CIPHER_SERVER_PREFERENCE| is enabled. Ciphers in an equal-preference
// group have equal priority and use the client order. This may be used to
// enforce that AEADs are preferred but select AES-GCM vs. ChaCha20-Poly1305
// based on client preferences. An equal-preference is specified with square
// brackets, combining multiple selectors separated by |. For example:
//
//   [TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256|TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256]
//
// Once an equal-preference group is used, future directives must be
// opcode-less. Inside an equal-preference group, spaces are not allowed.
//
```

I checked the documentation and did not find any reference w.r.t supporting the server/client order preference for cipher suites. Please share related documentation link if it is already supported.

*Relevant Links*:
This is the link in boringSSL that has described the option - https://boringssl.googlesource.com/boringssl/+/f0bdf5c9a10ba7172001aece1ed4908830eebea2/include/openssl/ssl.h#1432:~:text=//%20%7CSSL_OP_CIPHER_SERVER_PREFERENCE%7C%20is%20enabled.%20Ciphers%20in%20an%20equal%2Dpreference

**Comment by adisuissa** [comment]
cc @ggreenway for TLS expert comments

**Comment by ggreenway** [comment]
Sure, makes sense to allow that. PRs are welcome for adding this feature.

**Comment by wufanqqfsc** [comment]
one more question here, why not we add a new optional sslctx_options parameter list for extensions.transport_sockets.tls.v3.TlsParameters , so that we can set any options for the SSL context.

**Comment by ggreenway** [comment]
> one more question here, why not we add a new optional sslctx_options parameter list for extensions.transport_sockets.tls.v3.TlsParameters , so that we can set any options for the SSL context.

A few reasons:

* BoringSSL does not guarantee that the flag values won't change eventually; it does not promise a stable ABI
* Some of the options are already set by Envoy based on other config, and it would be complicated to specify what happens in the case of a conflict (or even figure out if there is a conflict)
* Aside from the flag in this issue, I don't think there are any other interesting options to set that don't already have explicit config

**Comment by wufanqqfsc** [comment]
@ggreenway  thanks for your comments. 
In our case we may need more options to set such as these different TLS version options set for different uc.
SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3|SSL_OP_NO_TLSv1|SSL_OP_NO_TLSv1_1|SSL_OP_SINGLE_DH_USE or 
SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3|SSL_OP_NO_TLSv1|SSL_OP_NO_TLSv1_1|SSL_OP_NO_TLSv1_2|SSL_OP_SINGLE_DH_USE
so we plan to add such an options extension and setting these values to SSL Context object.

**Comment by mamathavit** [comment]
Hi Team. Glad to see that this is being looked at. Need one clarification. Since this option is not currently exposed in Envoy, what is the default behavior? Will the client cipher order preference be considered?

**Comment by ggreenway** [comment]
> Hi Team. Glad to see that this is being looked at. Need one clarification. Since this option is not currently exposed in Envoy, what is the default behavior? Will the client cipher order preference be considered?

The current setting is to use the server's preference in all cases.

**Comment by ggreenway** [comment]
> @ggreenway thanks for your comments. In our case we may need more options to set such as these different TLS version options set for different uc. SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3|SSL_OP_NO_TLSv1|SSL_OP_NO_TLSv1_1|SSL_OP_SINGLE_DH_USE or SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3|SSL_OP_NO_TLSv1|SSL_OP_NO_TLSv1_1|SSL_OP_NO_TLSv1_2|SSL_OP_SINGLE_DH_USE so we plan to add such an options extension and setting these values to SSL Context object.

The protocol version flags aren't needed; those can already be configured in Envoy, and the docs indicate that use of `SSL_CTX_set_max_proto_version` and `SSL_CTX_set_min_proto_version` is the better way to set this. BoringSSL doesn't have any support for the super-old versions (like SSLv2) at all, so those flags don't do anything. Same with `SSL_OP_SINGLE_DH_USE`; it doesn't have any effect at all in BoringSSL.
