### ISSUE TITLE
Help requested isolating an asan bug

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#34619]
*Title*: *Help requested isolating an asan bug*

*Description*:

I am seeing an issue when compiling tests using asan option. static constexpr absl::string_view members of a class declared in the same namespace appear to be being corrupted somehow during optimisation, only when using asan build.

I'd like to isolate this further so I can either a) determine if it's just something I'm doing dumb or b) log it with the llvm/asan team. 

I've tried to repro it on godbolt with no luck https://godbolt.org/z/84PYn1P44 , using clang14 and the same compiler options I can find from our build output, but maybe I'm missing a library.

The following trivial tests can demonstrate the issue:

https://github.com/envoyproxy/envoy/compare/main...nbaws:envoy:asan_bug

What we are testing is that a static constexpr absl::string_view gets correctly copied. When this is run using dev test, the copy works fine. When run using asan the end() is corrupted but only when referenced from the same namespace, not directly from the test case. AFAIK a reference to a static constexpr should work without instantiating the class.

*Repro steps*:

```
./ci/run_envoy_docker.sh './ci/do_ci.sh asan //test/extensions/common/aws:sigv4a_signer_impl_test'
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=x86_64
Setting test_tmpdir to /build/tmp.
Skip setting up Envoy Filter Example.
building using 16 CPUs
building for x86_64
clang toolchain with libc++ configured: clang-libc++
bazel ASAN/UBSAN debug build with tests
Building and testing envoy tests //test/extensions/common/aws:sigv4a_signer_impl_test
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [clang]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
WARNING: The following configs were expanded more than once: [clang]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
Loading: 1 packages loaded
Analyzing: target //test/extensions/common/aws:sigv4a_signer_impl_test (2 packages loaded, 0 targets configured)
...
[3,489 / 3,490] Testing //test/extensions/common/aws:sigv4a_signer_impl_test; 0s processwrapper-sandbox
FAIL: //test/extensions/common/aws:sigv4a_signer_impl_test (see /build/bazel_root/base/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/common/aws/sigv4a_signer_impl_test/test.log)
Target //test/extensions/common/aws:sigv4a_signer_impl_test up-to-date:
  bazel-bin/test/extensions/common/aws/sigv4a_signer_impl_test
INFO: Elapsed time: 58.890s, Critical Path: 52.04s
INFO: 6 processes: 1 internal, 5 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 6 total actions
//test/extensions/common/aws:sigv4a_signer_impl_test                     FAILED in 0.8s
  /build/bazel_root/base/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/common/aws/sigv4a_signer_impl_test/test.log

Executed 1 out of 1 test: 1 fails locally.
/source/bazel-testlogs /source
/source
[ssm-user@ec2-3-25-187-70 envoy]$ tail -100 /opt/bazel_root/base/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/common/aws/sigv4a_signer_impl_test/test.log

[ RUN      ] SigV4ASignerImplTest.SignDateHeader
[       OK ] SigV4ASignerImplTest.SignDateHeader (25 ms)
...
[       OK ] SigV4ASignerImplTest.QueryStringDefault5s (26 ms)
[----------] 20 tests from SigV4ASignerImplTest (527 ms total)

[----------] 4 tests from ExampleTest
[ RUN      ] ExampleTest.Test1
test/extensions/common/aws/sigv4a_signer_impl_test.cc:507: Failure
Expected equality of these values:
  std::distance(a, b)
    Which is: -109706
  22
Stack trace:
  0x3424996: Envoy::Extensions::Common::Aws::(anonymous namespace)::ExampleTest_Test1_Test::TestBody()
  0xa80c6a5: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0xa7d3743: testing::Test::Run()
  0xa7d52b8: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] ExampleTest.Test1 (41 ms)
[ RUN      ] ExampleTest.Test2
[       OK ] ExampleTest.Test2 (0 ms)
[ RUN      ] ExampleTest.Test3
test/extensions/common/aws/sigv4a_signer_impl_test.cc:519: Failure
Expected equality of these values:
  a.size()
    Which is: 0
  22
Stack trace:
  0x34252bb: Envoy::Extensions::Common::Aws::(anonymous namespace)::ExampleTest_Test3_Test::TestBody()
  0xa80c6a5: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0xa7d3743: testing::Test::Run()
  0xa7d52b8: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] ExampleTest.Test3 (10 ms)
[ RUN      ] ExampleTest.Test4
[       OK ] ExampleTest.Test4 (0 ms)
[----------] 4 tests from ExampleTest (52 ms total)

[----------] Global test environment tear-down
[==========] 24 tests from 2 test suites ran. (579 ms total)
[  PASSED  ] 22 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] ExampleTest.Test1
[  FAILED  ] ExampleTest.Test3

 2 FAILED TESTS
```

**Comment by alyssawilk** [comment]
I don't think it's going to be easy to get traction sorting out a test-bug but cc @toddmgreer as he's my go-to for weird C++ problems :-)

**Comment by nbaws** [comment]
thanks :) really I just wanted to get it tracked somewhere or at least find out what I'm doing wrong. Seems super weird to me though.

**Comment by toddmgreer** [comment]
I'm stumped.

It seems like SigV4ASignatureConstants::SigV4AAlgorithm is referring to one object in SigV4AKeyDerivation::begin(), and a different one in SigV4AKeyDerivation::end(). This sort of thing smells like an ODR violation, but I can't see any relevant ODR violation, and even if there is one, it would be weird for two references in the same cpp file to be different. (unless asan somehow does something weird to make ODR violations show up?)

The only other way i can see for this to happen is if something is somehow overwriting SigV4AAlgorithm's data members.

To check for the former, I suggest printing or logging `&SigV4ASignatureConstants::SigV4AAlgorithm` in `SigV4AKeyDerivation::begin()` and `SigV4AKeyDerivation::end()`. If they aren't identical, that's the problem.

To check for the former, I suggest using a debugger or printf/log style debugging to track down where exactly SigV4AAlgorithm is getting changed.

Maybe try running this under ubsan? tsan, if your test has multiple threads?

**Comment by nbaws** [comment]
Gave up trying to solve this. It's occurring during clang optimisation as best as I can tell.
