### ISSUE TITLE
Flake in IpVersions/DirectResponseIntegrationTest.DefaultDirectResponseFile/IPv6

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#34626]
[ RUN      ] IpVersions/DirectResponseIntegrationTest.DefaultDirectResponseFile/IPv6
test/integration/direct_response_integration_test.cc:100: Failure
Expected equality of these values:
  "dummy-updated"
  updated_response->body()
    Which is: "dummy"
Stack trace:
  0xbafc8b: Envoy::DirectResponseIntegrationTest::testDirectResponseFile()
  0x20fc52c: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x20fc3ed: testing::Test::Run()
  0x20fd6e7: testing::TestInfo::Run()
... Google Test internal frames ...

My guess is it's a race between the file being updated / processed, and needs a stat counter it can sync on.  @ramaraochavali can you please take a look?

**Comment by alyssawilk** [comment]
ping!
https://dev.azure.com/cncf/envoy/_build/results?buildId=172685&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00&l=355

**Comment by alyssawilk** [comment]
2 more failures on CI today.  I'll try to disable for now

**Comment by ramaraochavali** [comment]
@alyssawilk Sorry. I missed this ping. I will take a look
