### ISSUE TITLE
Disable a specific endpoint using EDS

### ISSUE THREAD

**Issue by bmadhavan** [envoyproxy/envoy#3466]
**Disable a specific endpoint using EDS ** ( Question )

*Title*: *I have a use case where I would want to disable a specific endpoint and re-enable it back*

*Description*:
I am trying to implement a request where I have to disable an endpoint ( via EDS ) for sometime and then re-enable it back.  I am planning to implement this using a new field under `lb_endpoints` like `disabled` to mark the endpoint. I want the weights to be immediately adjusted accordingly.  

Based on looking into the code I could think of 2 approaches for the same. I would request some opinion as to which one is cleaner and better. Thanks in advance.    

Option 1) 
Handle this at the EDS config update and chuck the endpoint out if it is not enabled. 
[https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/eds.cc#L83]
This way it is treated as an EDS update without the endpoint, so that priority and everything else will be recalculated. 

Option 2) 
Allow this to be added as an eligible host, do HC etc. but handle it by denying any new requests to the endpoint.  
Based on my analysis this might have to be handled at few more places like the following, 
* Skip priority calculation at BaseDynamicClusterImpl::updateDynamicHostList() for the host if it is disabled.
* Healthchecks will be sent out for them but when workers are updated about the `healthy_hosts` I can create another list that will be a subset of this... something like `healthy_enabled_hosts`
i.e. ClusterManagerImpl::ThreadLocalClusterManagerImpl::updateClusterMembership()
* Some changes in the locality_lb_endpoints to handle endpoints that are disabled. 
I am not sure if I have missed any other things that need to be updated. 

Appreciate any pointers or if there is any other current mechanism to achieve the use case.

**Comment by htuch** [comment]
@bmadhavan does https://github.com/envoyproxy/envoy/issues/3276 address your conerns?

**Comment by mattklein123** [comment]
@htuch from my read, I think just setting `health_status` to unhealthy would do the trick? https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/endpoint/endpoint.proto#L51

**Comment by htuch** [comment]
It would, at the expense of mucking up the health stats.

**Comment by bmadhavan** [comment]
Thanks @htuch @mattklein123 for the pointers.
 From what I understand #3276 does it for all the endpoints in a cluster. (i.e. pretty much controls as a cluster level setting). 
My use case requires it to be controlled at each endpoint level so setting `health_status` is much more close to handling my requirement here. 
Again, thank you very much !

**Comment by mattklein123** [comment]
Cool, closing.
