### ISSUE TITLE
Why can't Envoy log the Connection in header

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#34667]
My clients send HTTP requests to my Envoy containing the `Connection: keep-alive` in header.

I'm trying to log the header so I configure the log as below:
```
[{name: envoy.access_loggers.stdout, typed_config: {"@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog, log_format: {text_format_source: {inline_string: "%REQ(CONNECTION)% ... 
```
As you see, I tried to use `%REQ(CONNECTION)%` to log the `Connection` in header of request. However, it seems that I always get an empty output `-`. I'm sure that the client has set `Connection: keep-alive` in its request header.

Why can't Envoy log the Connection in header?

**Comment by alyssawilk** [comment]
Envoy clears hop by hop headers per the HTTP spec and it's almost certainly doing so before logging. cc @yanavlasov
