### ISSUE TITLE
Enabling HTTP 2 for upstream server, the response time of concurrent requests is forming a waterfall model adding up the time of other concurrent request

### ISSUE THREAD

**Issue by parasharsh** [envoyproxy/envoy#34669]
We have Envoy acting as a reverse proxy for upstream services. One of the upstream services is NGINX which serves the static resources for the UI. We have enabled HTTP2 on Envoy without SSL. 
For Envoy static resources are configured as below 
connect_timeout: 1s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: myservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3221
                
    Observation 
1. Concurrent requests are hitting the NGINX at the same time and NGINX is taking almost 0 ms to response back (based on NGINX logs)
2. In Evnoy access logs
     1. First requests take a few milliseconds (61 in the attached image) showing 0 for upstream service 
      2. Second request onward takes much longer showing approx same time as earlier request for upstream service response time.  (for 2nd request upstream service time is 61 ms )
      3. Due to this the overall response time of second requests onwards starts building up and shows like waterfall times.
      
![image](https://github.com/envoyproxy/envoy/assets/3704164/bbea3753-b03e-4b07-9000-393c2a326ad4)

**Comment by parasharsh** [comment]
Changing the msx_concurrent_streams to 1 reduces the upstream service time to near 0. So is it that envoy is handling the http2 response sequentially? Isn't this a bug ?  
    http2_protocol_options:
      max_concurrent_streams: 1

**Comment by alyssawilk** [comment]
Envoy definitely handles HTTP/2 requests in parallel - not sure what the cause of the latency here is but I suggest some time with envoy logs and wireshark.

**Comment by parasharsh** [comment]
Envoy logs clearly show that upstream response processing is done sequentially.  If the concurrent streams per connection is set as 1 then the requests are processed in parallel. Upstream server response time is 0 ms as it's on the same VM and serving static files. So some bug with Envoy ?
