### ISSUE TITLE
`failure_mode_allow=true` is not fully supported for the grpc authz server.

### ISSUE THREAD

**Issue by konstantin-baidin-y42** [envoyproxy/envoy#34705]
*Title*: `failure_mode_allow=true` is not fully supported for the grpc authz server.

*Description*:
There is inconsistency in how the `failure_mode_allow=true` option is applied to external authorization servers depending on the protocol: http and grpc.

In case of http authz server, any 5xx statuses lead to accepting the incoming request (fail-open).

In case of grpc authz server, statuses like 14 (Unavailable) lead to rejecting the incoming request. If there is any grpc proxy between envoy and authz server, then this proxy can return 14 (Unavailable) when authz server is unavailable. It leads to the fail-close behaviour even when `failure_mode_allow` is enabled. As a result, we have random rejections while with `failure_mode_allow` we want the opposite - don't reject requests because of random failures.
 
Expected behaviour is to use failue_mode_allow when receiveng grpc statuses like 2 (Unknown), 13 (Internal), 14 (Unavailable).

The following PR https://github.com/envoyproxy/envoy/pull/4199 was intended to handle these cases when `failure_mode_allow=true` and authz server is unhealthy, but it was solved for HTTP authz server only.

*Repro steps*:
1. Configure envoy to have `failure_mode_allow=true`
2. Make the authz server to return grpc status 14 (Unavailable)
3. Perform http request to a service in the cluster
4. Envoy returns 403 (fail-close), while it was expected to perform fail-open.

**Comment by alyssawilk** [comment]
cc @esmet @tyxia @ggreenway

**Comment by konstantin-baidin-y42** [comment]
Hello, I tested it manually with logging level tracing and found that responses with error status codes are processed in the `GrpcClientImpl::onSuccess` callback instead of the `GrpcClientImpl::onFailure`. So I added a check of the status code and similar actions as in the onFailure callback.
I made a PR with a draft of the fix. Can you please take a look? https://github.com/envoyproxy/envoy/pull/34951

**Comment by konstantin-baidin-y42** [comment]
Since my fix was reverted in https://github.com/envoyproxy/envoy/pull/35637, can you please re-open this issue again? @ggreenway 
Or should I create a duplicate one?

**Comment by konstantin-baidin-y42** [comment]
Also, do I understand right that this time I should create the same PR, just with the runtime guard to be false by default as I did initially?

**Comment by ggreenway** [comment]
You'd need to make it with a config setting to control the behavior, which defaults to the old behavior. Runtime flags are meant to be temporary.
