### ISSUE TITLE
honor connection_pool_per_downstream_connection in tcp conn-pool

### ISSUE THREAD

**Issue by Pawan-Bishnoi** [envoyproxy/envoy#34762]
*Title*: connection_pool_per_downstream_connection is only read in [httpConnPoolImpl](https://github.com/envoyproxy/envoy/blob/63621d07e0088b5dce076b3436ab0e1e8367f568/source/common/upstream/cluster_manager_impl.cc#L1993-L1997) today. Which means this flag can't be used with filters relying on [tcp_pool](https://github.com/envoyproxy/envoy/blob/63621d07e0088b5dce076b3436ab0e1e8367f568/source/common/upstream/cluster_manager_impl.cc#L1087) (eg. thrift_proxy) 

*Description*:
the flag is a cluster level flag and should be honored in thrift_proxy etc (which uses tcppool)

**Comment by Pawan-Bishnoi** [comment]
the original PR where this flag was added: https://github.com/envoyproxy/envoy/pull/12812 / https://github.com/envoyproxy/envoy/issues/12370

**Comment by tyxia** [comment]
This PR for this issue has been assigned.

The area should be tcp connection pool and thrift proxy is application

**Comment by Pawan-Bishnoi** [comment]
keep open
