### ISSUE TITLE
configure OTEL of access log to export using HTTP

### ISSUE THREAD

**Issue by ShyunnY** [envoyproxy/envoy#34767]
*Title*: *configure OTEL of access log to export using HTTP*

*Description*:
> When I configured access log in envoy, I selected OpenTelemetryAccessLogConfig extension. I found that this extension can only configure gRPC to export logs through `common_config`. Is there any other way to export logs using HTTP?

**Comment by tyxia** [comment]
I think the answer is no. That is gRPC specific. ref: (1)grpc.v3.CommonGrpcAccessLogConfig
(2)https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/grpc/v3/als.proto#envoy-v3-api-msg-extensions-access-loggers-grpc-v3-commongrpcaccesslogconfig


cced code owner: @itamarkam @yanavlasov

**Comment by itamarkam** [comment]
The OTel access logger is based on the gRPC access logger. so I don't think that HTTP is possible (unless there's a way to configure it using the gRPC config).
Side note: does Envoy have an HTTP access logger?

**Comment by ShyunnY** [comment]
> OTel 访问记录器基于 gRPC 访问记录器。所以我认为 HTTP 是不可能的（除非有办法使用 gRPC 配置来配置它）。 附注：Envoy 有 HTTP 访问记录器吗？

I see. Is there some other better way to achieve my goal?

**Comment by itamarkam** [comment]
I remember that I set it up to send the streaming logs to a non streaming endpoint and it worked (just resets the connection every time it sends some logs). Maybe that's a good starting point.

**Comment by ShyunnY** [comment]
> I remember that I set it up to send the streaming logs to a non streaming endpoint and it worked (just resets the connection every time it sends some logs). Maybe that's a good starting point.

This seems like a good idea, thanks

**Comment by ShyunnY** [comment]
Thanks everyone, I solved the problem based on your responses.
I will close this issue
