### ISSUE TITLE
Envoy proxy not respecting headers added within Gateway API

### ISSUE THREAD

**Issue by chrxmvtik** [envoyproxy/envoy#34795]
*Title*: Envoy proxy not respecting headers added within Gateway API

*Description*:
We are using Cilium as CNI with envoy proxy and Gateway API upfront, we want to set custom headers for envoy proxy, as example we want to set 'x-envoy-upstream-rq-timeout-ms' header.

We added this header in HTTPRoute resource of Gateway API and we can see, that it is actually attached when we inspect app logs.

However envoy proxy is not respecting this header that is dynamically set with Gateway API and we receive a 504 upstream timeout error.

**Comment by tyxia** [comment]
@chrxmvtik  Can you share more details?

How to repro and which area in Envoy you are suspecting. Do you only see the problem with `x-envoy-upstream-rq-timeout-ms` or only with x-envoy header or more headers in genearl.

**Comment by tyxia** [comment]
I think this issue requires more details before we can further triage.

@chrxmvtik  Please ping back when you have more information. Thanks!
