### ISSUE TITLE
Question about request_mirroring#disable_shadow_host_suffix_append

### ISSUE THREAD

**Issue by rkbalgi** [envoyproxy/envoy#34814]
Hi Team, I'm trying to test the disabling of "-shadow" suffix which was done as a part of https://github.com/envoyproxy/envoy/pull/31930. I'm using the latest docker build of envoy - d79f6e8d453ee260e9094093b8dd31af0056e67b/1.30.2/Clean/RELEASE/BoringSSL
```json            
virtual_hosts:
            - name: backend
              domains:
              - "localhost:10000"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster-a
                  auto_host_rewrite: true
                  request_mirror_policies:
                    - cluster: cluster-a-mirror
                      disable_shadow_host_suffix_append: true
```

I get an error -
`Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT: invalid JSON in  envoy.config.bootstrap.v3.Bootstrap @  static_resources.listeners[0].filter_chains[0].filters[0].typed_config.<any>.route_config.virtual_hosts[0].routes[0].route.request_mirror_policies[0]:  message envoy.config.route.v3.RouteAction.RequestMirrorPolicy, near 1:4959   (offset 4958):  no such field:  'disable_shadow_host_suffix_append') has unknown fields`

Am I using this the right way?

**Comment by tyxia** [comment]
Closed issue per comment https://github.com/envoyproxy/envoy/issues/34814#issuecomment-2178801821
