### ISSUE TITLE
Does envoy supports configuring upstream application layer protocol?

### ISSUE THREAD

**Issue by ikimonogakari** [envoyproxy/envoy#34845]
I am currently using Envoy as an HTTP proxy to proxy tcp stream to the upstream.

```
client [CONNECT] --> Envoy --[TCP stream]--> upstream
```

Currently, after handling the initial CONNECT request, Envoy just blindly forward the inner stream to the upstream using a TCP connection.

I know there is an option to customize my own [transport_socket](https://github.com/envoyproxy/envoy/blob/d8821370842dea5b01a458f6225b223f025f5300/api/envoy/config/cluster/v3/cluster.proto#L1085). But in theory, that only affects the transport layer protocol. What I am trying to do, is to add another application layer protocol, such as HTTP, to wrap the stream being proxied through envoy.
```
Envoy --[HTTP[TCP stream]]--> upstream
```
I did some research on the config for Clusters, but had no luck. Can someone instruct me how to achieve such functionality in Envoy?

**Comment by tyxia** [comment]
Hi @ikimonogakari , have you tried TCP Proxy https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/listener_filters.html#tcp-proxy-filter

**Comment by ikimonogakari** [comment]
Please clarify a little bit more?
Which usage are your referring to?
1. In the incoming listener, add tcp_proxy filter.
   1. I don't think this works. The incoming traffic is wrapped under an HTTP CONNECT, we need HCM filter to decode the request. IIUC, HCM and tcp_proxy filter cannot exist at the same listener filter chain.
1. In the incoming listener, points to a cluster which points to an internal listener.
   1. In the internal listener, add tcp_proxy filter.
   2. I also cannot figure out how this can work to add a new HTTP wrapper using HCM or other filters to the egress TCP stream.
