### ISSUE TITLE
implement scheme_redirect

### ISSUE THREAD

**Issue by aguilbau** [envoyproxy/envoy#3484]
In a [route.RedirectAction](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#route-redirectaction), it should be possible to specify the scheme that will be used.
For now, the option to swap the scheme with **https** is available, with the `https_redirect` option.

However, if one wants to use arbitrary scheme, it is not possible.

My use case is that I want to redirect https to http.

**Comment by cpakulski** [comment]
@mattklein123 I do not mind working on this, but would need a bit more info about what has to be done.

**Comment by nickolaev** [comment]
I believe that after merging #4570 and closing #3060, this one is obsolete.
@mattklein123 shall we close it?

**Comment by mattklein123** [comment]
Yup, thanks.
