### ISSUE TITLE
Status of Access Log Service

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#3485]
What is the current status of ALS? The protos are marked as experimental (https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/accesslog/v2/als.proto#L29) but I can't find any issues tracking an implementation. Is it functional?

**Comment by mattklein123** [comment]
@snowp the status is tracked here: https://github.com/envoyproxy/envoy/issues/743 so I will close this is a dup.

The TL/DR is that a bunch of people are using ALS in production already (including Lyft) so it really just needs a doc pass. I think @rodaine has gotten pulled off to work on other stuff so I will probably try to take it over the finish line next week.
