### ISSUE TITLE
Callback for request cancelled from client

### ISSUE THREAD

**Issue by zhiyong-gayang** [envoyproxy/envoy#34878]
If the request is cancelled from client, is there callback functions we can use to do some cleanup work?

StreamFilter only provide decode/encode header/data/trailer, I don't see any function for request cancel.

**Comment by mattklein123** [comment]
There are callback events for resets which should work for this.

**Comment by zhiyong-gayang** [comment]
@mattklein123 Can you share an example how to use reset events in network/http filters?
