### ISSUE TITLE
Support matching route metadata in the HTTP RBAC filter

### ISSUE THREAD

**Issue by henrymwang** [envoyproxy/envoy#34913]
*Title*: Support matching on route metadata in the HTTP RBAC filter

*Description*:

We have two types of routes which exist on the same routing table and want to be able to apply RBAC rules based on the route metadata to allow for fine-grained RBAC based on route type, https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-route. Currently the RBAC filter only supports matching on dynamic metadata which is added by previous filters or based on headers and while we could rewrite route metadata to dynamic metadata by using the Lua filter, we would like to avoid coupling the two filters together.

This is similar to https://github.com/envoyproxy/envoy/pull/13269, which adds support for deriving ratelimit descriptors in the ratelimit filter from route metadata.

The approach would be:

1. add another field to the RBAC Principal / Permission protobufs to specify fetching the request's dynamic metadata or from the route metadata

2. update the `MetadataMatcher` to use `info.route()->metadata()` instead if the metadata source is set to `route`, https://github.com/envoyproxy/envoy/blob/d79f6e8d453ee260e9094093b8dd31af0056e67b/source/extensions/filters/common/rbac/matchers.cc#L251

We can prepare a patch for this if it sounds reasonable.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mathetake** [comment]
relevant: https://github.com/envoyproxy/envoy/issues/34092

**Comment by agrawroh** [comment]
@wbpcode Should we close this now?
