### ISSUE TITLE
questions about upstream connect error or disconnect/reset before headers%

### ISSUE THREAD

**Issue by corn1ng** [envoyproxy/envoy#3492]
**Issue Template**

*Title*: *One line description*

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.
i want to  run an example of envoy. and i typed 

$ docker pull envoyproxy/envoy:latest
$ docker run --rm -d -p 10000:10000 envoyproxy/envoy:latest
$ curl -v localhost:10000

but there is an error of `upstream connect error or disconnect/reset before headers%`

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

 i am  using docker for mac 18.03.1-ce

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)
cluster.service_google.bind_errors: 0
cluster.service_google.external.upstream_rq_503: 8
cluster.service_google.external.upstream_rq_5xx: 8
cluster.service_google.lb_healthy_panic: 0
cluster.service_google.lb_local_cluster_not_ok: 0
cluster.service_google.lb_recalculate_zone_structures: 0
cluster.service_google.lb_subsets_active: 0
cluster.service_google.lb_subsets_created: 0
cluster.service_google.lb_subsets_fallback: 0
cluster.service_google.lb_subsets_removed: 0
cluster.service_google.lb_subsets_selected: 0
cluster.service_google.lb_zone_cluster_too_small: 0
cluster.service_google.lb_zone_no_capacity_left: 0
cluster.service_google.lb_zone_number_differs: 0
cluster.service_google.lb_zone_routing_all_directly: 0
cluster.service_google.lb_zone_routing_cross_zone: 0
cluster.service_google.lb_zone_routing_sampled: 0
cluster.service_google.max_host_weight: 0
cluster.service_google.membership_change: 1
cluster.service_google.membership_healthy: 1
cluster.service_google.membership_total: 1
cluster.service_google.retry_or_shadow_abandoned: 0
cluster.service_google.ssl.connection_error: 0
cluster.service_google.ssl.fail_verify_cert_hash: 0
cluster.service_google.ssl.fail_verify_error: 0
cluster.service_google.ssl.fail_verify_no_cert: 0
cluster.service_google.ssl.fail_verify_san: 0
cluster.service_google.ssl.handshake: 0
cluster.service_google.ssl.no_certificate: 0
cluster.service_google.ssl.session_reused: 0
cluster.service_google.update_attempt: 382
cluster.service_google.update_empty: 0
cluster.service_google.update_failure: 0
cluster.service_google.update_no_rebuild: 0
cluster.service_google.update_success: 382
cluster.service_google.upstream_cx_active: 0
cluster.service_google.upstream_cx_close_notify: 0
cluster.service_google.upstream_cx_connect_attempts_exceeded: 0
cluster.service_google.upstream_cx_connect_fail: 8
cluster.service_google.upstream_cx_connect_timeout: 7
cluster.service_google.upstream_cx_destroy: 0
cluster.service_google.upstream_cx_destroy_local: 0
cluster.service_google.upstream_cx_destroy_local_with_active_rq: 0
cluster.service_google.upstream_cx_destroy_remote: 0
cluster.service_google.upstream_cx_destroy_remote_with_active_rq: 0
cluster.service_google.upstream_cx_destroy_with_active_rq: 0
cluster.service_google.upstream_cx_http1_total: 8
cluster.service_google.upstream_cx_http2_total: 0
cluster.service_google.upstream_cx_idle_timeout: 0
cluster.service_google.upstream_cx_max_requests: 0
cluster.service_google.upstream_cx_none_healthy: 0
cluster.service_google.upstream_cx_overflow: 0
cluster.service_google.upstream_cx_protocol_error: 0
cluster.service_google.upstream_cx_rx_bytes_buffered: 0
cluster.service_google.upstream_cx_rx_bytes_total: 0
cluster.service_google.upstream_cx_total: 8
cluster.service_google.upstream_cx_tx_bytes_buffered: 0
cluster.service_google.upstream_cx_tx_bytes_total: 0
cluster.service_google.upstream_flow_control_backed_up_total: 0
cluster.service_google.upstream_flow_control_drained_total: 0
cluster.service_google.upstream_flow_control_paused_reading_total: 0
cluster.service_google.upstream_flow_control_resumed_reading_total: 0
cluster.service_google.upstream_rq_503: 8
cluster.service_google.upstream_rq_5xx: 8
cluster.service_google.upstream_rq_active: 0
cluster.service_google.upstream_rq_cancelled: 0
cluster.service_google.upstream_rq_maintenance_mode: 0
cluster.service_google.upstream_rq_pending_active: 0
cluster.service_google.upstream_rq_pending_failure_eject: 8
cluster.service_google.upstream_rq_pending_overflow: 0
cluster.service_google.upstream_rq_pending_total: 8
cluster.service_google.upstream_rq_per_try_timeout: 0
cluster.service_google.upstream_rq_retry: 0
cluster.service_google.upstream_rq_retry_overflow: 0
cluster.service_google.upstream_rq_retry_success: 0
cluster.service_google.upstream_rq_rx_reset: 0
cluster.service_google.upstream_rq_timeout: 0
cluster.service_google.upstream_rq_total: 0
cluster.service_google.upstream_rq_tx_reset: 0
cluster.service_google.version: 0
cluster_manager.active_clusters: 1
cluster_manager.cluster_added: 1
cluster_manager.cluster_modified: 0
cluster_manager.cluster_removed: 0
cluster_manager.warming_clusters: 0
filesystem.flushed_by_timer: 0
filesystem.reopen_failed: 0
filesystem.write_buffered: 0
filesystem.write_completed: 0
filesystem.write_total_buffered: 0
http.admin.downstream_cx_active: 1
http.admin.downstream_cx_destroy: 0
http.admin.downstream_cx_destroy_active_rq: 0
http.admin.downstream_cx_destroy_local: 0
http.admin.downstream_cx_destroy_local_active_rq: 0
http.admin.downstream_cx_destroy_remote: 0
http.admin.downstream_cx_destroy_remote_active_rq: 0
http.admin.downstream_cx_drain_close: 0
http.admin.downstream_cx_http1_active: 1
http.admin.downstream_cx_http1_total: 1
http.admin.downstream_cx_http2_active: 0
http.admin.downstream_cx_http2_total: 0
http.admin.downstream_cx_idle_timeout: 0
http.admin.downstream_cx_protocol_error: 0
http.admin.downstream_cx_rx_bytes_buffered: 83
http.admin.downstream_cx_rx_bytes_total: 83
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.admin.downstream_cx_total: 1
http.admin.downstream_cx_tx_bytes_buffered: 0
http.admin.downstream_cx_tx_bytes_total: 0
http.admin.downstream_cx_websocket_active: 0
http.admin.downstream_cx_websocket_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
http.admin.downstream_rq_1xx: 0
http.admin.downstream_rq_2xx: 0
http.admin.downstream_rq_3xx: 0
http.admin.downstream_rq_4xx: 0
http.admin.downstream_rq_5xx: 0
http.admin.downstream_rq_active: 1
http.admin.downstream_rq_http1_total: 1
http.admin.downstream_rq_http2_total: 0
http.admin.downstream_rq_non_relative_path: 0
http.admin.downstream_rq_response_before_rq_complete: 0
http.admin.downstream_rq_rx_reset: 0
http.admin.downstream_rq_too_large: 0
http.admin.downstream_rq_total: 1
http.admin.downstream_rq_tx_reset: 0
http.admin.downstream_rq_ws_on_non_ws_route: 0
http.admin.rs_too_large: 0
http.async-client.no_cluster: 0
http.async-client.no_route: 0
http.async-client.rq_direct_response: 0
http.async-client.rq_redirect: 0
http.async-client.rq_total: 0
http.ingress_http.downstream_cx_active: 0
http.ingress_http.downstream_cx_destroy: 8
http.ingress_http.downstream_cx_destroy_active_rq: 0
http.ingress_http.downstream_cx_destroy_local: 0
http.ingress_http.downstream_cx_destroy_local_active_rq: 0
http.ingress_http.downstream_cx_destroy_remote: 8
http.ingress_http.downstream_cx_destroy_remote_active_rq: 0
http.ingress_http.downstream_cx_drain_close: 0
http.ingress_http.downstream_cx_http1_active: 0
http.ingress_http.downstream_cx_http1_total: 8
http.ingress_http.downstream_cx_http2_active: 0
http.ingress_http.downstream_cx_http2_total: 0
http.ingress_http.downstream_cx_idle_timeout: 0
http.ingress_http.downstream_cx_protocol_error: 0
http.ingress_http.downstream_cx_rx_bytes_buffered: 0
http.ingress_http.downstream_cx_rx_bytes_total: 636
http.ingress_http.downstream_cx_ssl_active: 0
http.ingress_http.downstream_cx_ssl_total: 0
http.ingress_http.downstream_cx_total: 8
http.ingress_http.downstream_cx_tx_bytes_buffered: 0
http.ingress_http.downstream_cx_tx_bytes_total: 1528
http.ingress_http.downstream_cx_websocket_active: 0
http.ingress_http.downstream_cx_websocket_total: 0
http.ingress_http.downstream_flow_control_paused_reading_total: 0
http.ingress_http.downstream_flow_control_resumed_reading_total: 0
http.ingress_http.downstream_rq_1xx: 0
http.ingress_http.downstream_rq_2xx: 0
http.ingress_http.downstream_rq_3xx: 0
http.ingress_http.downstream_rq_4xx: 0
http.ingress_http.downstream_rq_5xx: 8
http.ingress_http.downstream_rq_active: 0
http.ingress_http.downstream_rq_http1_total: 8
http.ingress_http.downstream_rq_http2_total: 0
http.ingress_http.downstream_rq_non_relative_path: 0
http.ingress_http.downstream_rq_response_before_rq_complete: 0
http.ingress_http.downstream_rq_rx_reset: 0
http.ingress_http.downstream_rq_too_large: 0
http.ingress_http.downstream_rq_total: 8
http.ingress_http.downstream_rq_tx_reset: 0
http.ingress_http.downstream_rq_ws_on_non_ws_route: 0
http.ingress_http.no_cluster: 0
http.ingress_http.no_route: 0
http.ingress_http.rq_direct_response: 0
http.ingress_http.rq_redirect: 0
http.ingress_http.rq_total: 8
http.ingress_http.rs_too_large: 0
http.ingress_http.tracing.client_enabled: 0
http.ingress_http.tracing.health_check: 0
http.ingress_http.tracing.not_traceable: 0
http.ingress_http.tracing.random_sampling: 0
http.ingress_http.tracing.service_forced: 0
listener.0.0.0.0_10000.downstream_cx_active: 0
listener.0.0.0.0_10000.downstream_cx_destroy: 8
listener.0.0.0.0_10000.downstream_cx_total: 8
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_1xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_2xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_3xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_4xx: 0
listener.0.0.0.0_10000.http.ingress_http.downstream_rq_5xx: 8
listener.0.0.0.0_10000.no_filter_chain_match: 0
listener.admin.downstream_cx_active: 1
listener.admin.downstream_cx_destroy: 0
listener.admin.downstream_cx_total: 1
listener.admin.http.admin.downstream_rq_1xx: 0
listener.admin.http.admin.downstream_rq_2xx: 0
listener.admin.http.admin.downstream_rq_3xx: 0
listener.admin.http.admin.downstream_rq_4xx: 0
listener.admin.http.admin.downstream_rq_5xx: 0
listener.admin.no_filter_chain_match: 0
listener_manager.listener_added: 1
listener_manager.listener_create_failure: 0
listener_manager.listener_create_success: 4
listener_manager.listener_modified: 0
listener_manager.listener_removed: 0
listener_manager.total_listeners_active: 1
listener_manager.total_listeners_draining: 0
listener_manager.total_listeners_warming: 0
runtime.admin_overrides_active: 0
runtime.load_error: 0
runtime.load_success: 0
runtime.num_keys: 0
runtime.override_dir_exists: 0
runtime.override_dir_not_exists: 0
server.days_until_first_cert_expiring: 2147483647
server.live: 1
server.memory_allocated: 3310240
server.memory_heap_size: 4194304
server.parent_connections: 0
server.total_connections: 0
server.uptime: 1905
server.version: 3029724
server.watchdog_mega_miss: 0
server.watchdog_miss: 0
stats.overflow: 0
cluster.service_google.upstream_cx_connect_ms: No recorded values
cluster.service_google.upstream_cx_length_ms: P0(nan,0) P25(nan,243.333) P50(nan,250) P75(nan,255) P90(nan,258) P95(nan,259) P99(nan,259.8) P99.9(nan,259.98) P100(nan,260)
http.admin.downstream_cx_length_ms: No recorded values
http.admin.downstream_rq_time: No recorded values
http.ingress_http.downstream_cx_length_ms: P0(nan,3) P25(nan,243.333) P50(nan,250) P75(nan,255) P90(nan,258) P95(nan,259) P99(nan,259.8) P99.9(nan,259.98) P100(nan,260)
http.ingress_http.downstream_rq_time: P0(nan,2) P25(nan,243.333) P50(nan,250) P75(nan,255) P90(nan,258) P95(nan,259) P99(nan,259.8) P99.9(nan,259.98) P100(nan,260)
listener.0.0.0.0_10000.downstream_cx_length_ms: P0(nan,3) P25(nan,243.333) P50(nan,250) P75(nan,255) P90(nan,258) P95(nan,259) P99(nan,259.8) P99.9(nan,259.98) P100(nan,260)
listener.admin.downstream_cx_length_ms: No recorded values

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by taion809** [comment]
Hey @corn1ng 
I wasn't able to reproduce this myself.

Can you try checking that you're able to connect to google from your container?

For example:
```
docker run --rm -ti envoyproxy/envoy bash
apt-get update && apt-get install -y curl
curl -IL https://google.com
```

You should see a `200 OK` response.

**Comment by corn1ng** [comment]
Hey @taion809 
i am in china so i  cant connect to google directly you know .
so i modify Google to baidu . but  i also get the 503

**Comment by mattklein123** [comment]
This sounds like a docker issue to me. I would take a look at your docker networking. Going to go ahead and close this. Reopen if you have further questions.

**Comment by jeteon** [comment]
I also experience similar behaviour when running the standard demo Docker image on Mac OS X. It seems to happen for any HTTPS upstream. If I manually run network calls from within the container the requests seem to work okay.

**Comment by butters-mars** [comment]
Same issue with me on mac os x. Is there any progress with this issue?

**Comment by mefarazath** [comment]
I faced the same problem. I changed the 'connect_timeout' value to a higher value(15s) as per @jeteon's suggestion and it worked for me.

Working yaml for me
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.google.com
                  cluster: service_google
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 15.0s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: google.com
          port_value: 443
    tls_context: { sni: www.google.com }
```

**Comment by atarlov** [comment]
I get the same issue: upstream connect error or disconnect/reset before headers 

curl to google from container works, 200 OK return

**Comment by sharkmao** [comment]
I also encountered the same issue

`$ curl -v localhost:10000
* Rebuilt URL to: localhost:10000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 10000 (#0)
> GET / HTTP/1.1
> Host: localhost:10000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Sat, 30 Mar 2019 07:39:48 GMT
< server: envoy
< 
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers
`

**Comment by sumitpathak24** [comment]
I got the same issue, is there a solution to this issue.
curl to google or upstream service return 200.

**Comment by ajit555db** [comment]
> I also experienced similar behaviour when running the standard demo Docker image on Mac OS X. It seemed to happen for any HTTPS upstream. If I manually ran network calls from within the container the requests seem to work okay.
> 
> It turns out that in my case the timeouts were too aggressive for the network connection I had. Things were fine with HTTP but the TLS handshake made connecting take too long.

after increasing the connect_timeout, my issue too vanished.
