### ISSUE TITLE
Impossible to parse stat tags with clusters containing `.` in the name

### ISSUE THREAD

**Issue by keithmattix** [envoyproxy/envoy#34976]
*Description*:

Because envoy uses `.` as the delimeter for stats, reliably extracting stat tags for clusters (or any resource) whose name contains a `.` is impossible. Take a cluster name like `outbound|443||api.facebook.com`. If you try to create a stat tag that extracts the cluster name and turns it into a label, you may be tempted to write something like: `^cluster\\.((.+)\\.)`. However, what will happen if the metric is `cluster.outbound|443||api.facebook.com.circuitbreakers.high.rq_open`? This regex will think the cluster name is `outbound|443||api.facebook.com.circuitbreakers.high`!!. It stands to reason that if regex from a plain text string is the only way to do transformations on stats, there should be a way to delineate something like the cluster/resource name from the metric name itself

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#circuit-breakers-statistics

**Comment by htuch** [comment]
@jmarantz

**Comment by keithmattix** [comment]
FYI @ravenblackx pointed me to [alt-stat-name](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-alt-stat-name) which we're considering adopting in Istio. But would be good to get official direction from upstream Envoy on resolving this. Perhaps a warning should be added to the docs if nothing can be done in the metrics engine

**Comment by keithmattix** [comment]
We were able to get past this in Istio via a combination of alt_stat_name and the %UPSTREAM_CLUSTER_RAW% stream formatter 👍🏾
