### ISSUE TITLE
Envoy & otel tracing samplers

### ISSUE THREAD

**Issue by dormullor** [envoyproxy/envoy#35016]
Hello everyone,
As far as i know, the default envoy OTEL sampler is "always_on", means, it will send a span for every request.
Since we use OTEL library on other services like nginx for example. i would like to set the nginx to a ratio based sampler and then envoy and all other services will use the "parentbased_always_off". ( if a trace exist, send a span, if not, do nothing )

https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_traces_sampler
 
Is there a way to configure other samplers in envoy ?

**Comment by htuch** [comment]
@wbpcode @Shikugawa @basvanbeek
