### ISSUE TITLE
How source_cluster is propagated to upstream service

### ISSUE THREAD

**Issue by s-krawczyk** [envoyproxy/envoy#35015]
*Description*:
I try to use rate_limit with actions. Configured descriptor like below:

``
route:
            rate_limits:
            - actions:
              - source_cluster: {}
              - 
``
That does not work. I am not getting any source_cluster. How this value flow from downstream service to upstream (destination) one? Is it a header? Does it even work? Any help or example would be helpful. Already sped 3 days on it. Reading source code etc. I would appreciate any direction. I want to use it for local rate limit.

*Relevant Links*:
[>Any extra documentation required to understand the issue.](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter#example-1)
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action

**Comment by htuch** [comment]
@wbpcode @mattklein123 

Are you setting the same source cluster in the Envoy CLI and in the config? It's a little unclear from the OP.
