### ISSUE TITLE
Advice request: CDS cluster addOrUpdateCluster

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#35065]
*Title*: *Some questions on CDS*

*Description*: 
Relevant to https://github.com/envoyproxy/envoy/issues/35022 - we have a dynamic cluster added for the purposes of credential fetching in the aws request signing extension.

Currently we handle callbacks for `Upstream::ClusterUpdateCallbacks:onClusterAddOrUpdate` and `Upstream::ClusterUpdateCallbacks:onClusterRemoval`. 

During initialisation we call `clusterManager().addOrUpdateCluster()` to add this dynamic cluster. This occurs on the main thread.

`Upstream::ClusterUpdateCallbacks:onClusterAddOrUpdate` is used during initial instantiation to kick off periodic credential refresh.

We're seeing these clusters disappear during CDS update as per the issue above. The _simple_ fix is to readd them again in `Upstream::ClusterUpdateCallbacks:onClusterRemoval` callback

Questions:

1. Is there a way to create these clusters initially that prevents them being destroyed by a CDS update? From best I can tell, because they're added via API they are implicitly destroyable. https://github.com/nbaws/envoy/blob/46fda6c348f4b39bbf5df86d0722f8f35b572dd8/envoy/upstream/cluster_manager.h#L236-L237
2. ~Is `clusterManager().addOrUpdateCluster()` thread safe - ie can I call it from a worker thread, or does it have to be posted to main thread.~ - Tested this, no it isn't
3. As we receive `Upstream::ClusterUpdateCallbacks:onClusterRemoval` once for all worker threads, it's not possible to determine if we're in the process of already readding a cluster without some kind of locking. It appears that `clusterManager().addOrUpdateCluster()` will exit early if the cluster is already in the process of initialisation or warming https://github.com/nbaws/envoy/blob/46fda6c348f4b39bbf5df86d0722f8f35b572dd8/source/common/upstream/cluster_manager_impl.cc#L805 . Is it safe for me to call `clusterManager().addOrUpdateCluster()` once per worker thread, in the knowledge that repeated calls will not result in multiple repeated clusters being created (due to the early exit)? 

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/pull/35062/files#diff-3d45a55c8f415956866de60b357e7065f147e878e29b79ce3f086425affaa4b0R260

**Comment by htuch** [comment]
@adisuissa

**Comment by nbaws** [comment]
Closing - I've handled this with some locking and it seems safe.
