### ISSUE TITLE
Documentation Update (lua)

### ISSUE THREAD

**Issue by GHOSTKILLER123** [envoyproxy/envoy#35071]
*Title*: *Doc Update*

*Description*:
>From a user perspective it is ideal to have sample configs on the doc itself. Also having explicit reference to integrate with Lua filter helps any first time user

*Relevant Links*:
>https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter
>https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples

**Comment by htuch** [comment]
@phlax

**Comment by phlax** [comment]
hi @GHOSTKILLER123 - we have some lua examples in the examples section of the docs - i would be happy to review any improvements to the reference docs

**Comment by GHOSTKILLER123** [comment]
Hi @phlax , this update I am talking about is more inline with users being able to access it directly from the envoy md5 file itself without having to explicitly search for it in the actual documentation. Let me know what you feel about it. 
We have multiple parties within my organization using envoy and they do seem to have certain "uneasiness" finding for example configs, they do eventually find it but the idea is to make it more friendly and seamless, and any new developer does not have knowledge to navigate through the doc to find what they want. Just a thought if we could provide direct references.

**Comment by phlax** [comment]
>  access it directly from the envoy md5 file itself

not sure i follow - i think the docs are the correct place to show examples/configs tho
