### ISSUE TITLE
AWS Sigv4a Signing does not work

### ISSUE THREAD

**Issue by shulin-sq** [envoyproxy/envoy#35078]
*Title*: *AWS Sigv4a Signing does not work*

*Description*:
The recently added signing support for sigv4a does not seem to be working. Unfortunately due to the opaqueness of sigv4, it's difficult to pinpoint which part of the logic is incorrect.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter

I have set this up both as sigv4 and sigv4a on the same machine, but only the former works.

The environment I am running on is fargate, and I'm using the credentials accessible from the $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variable.

*Repro steps*:
my config follows the sample one in the doc and I am using the upstream cluster filter.

```
          "name": "envoy.filters.http.aws_request_signing",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning",
           "service_name": "vpc-lattice-svcs",
           "region": "*",
           "use_unsigned_payload": true,
           "match_excluded_headers": [...]
           "signing_algorithm": "AWS_SIGV4A"
```

The resulting headers _look_ right but result in `InvalidSignatureException`

from tap:
```
    {
     "key": "x-amz-content-sha256",
     "value": "UNSIGNED-PAYLOAD",
     "raw_value": ""
    },
    {
     "key": "x-amz-security-token",
     "value": "redacted",
     "raw_value": ""
    },
    {
     "key": "x-amz-date",
     "value": "20240706T040500Z",
     "raw_value": ""
    },
    {
     "key": "x-amz-region-set",
     "value": "*",
     "raw_value": ""
    },
    {
     "key": "authorization",
     "value": "AWS4-ECDSA-P256-SHA256 Credential=redacted/20240706/vpc-lattice-svcs/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-region-set;x-amz-security-token, Signature=redacted",
     "raw_value": ""
    }
```
(unsure if this matters, but I don't see a host header in the tap, only authority. I tried removing the host header from the signed headers list but that didn't fix the issue. Neither did trying to use this as a query param instead of authorization header). 

switching the config to:

```
          "name": "envoy.filters.http.aws_request_signing",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning",
           "service_name": "vpc-lattice-svcs",
           "region": "us-west-2",
           "use_unsigned_payload": true,
           "match_excluded_headers": [...]
           "signing_algorithm": "AWS_SIGV4"
```

on the same machine results in a successful request.

**Comment by htuch** [comment]
@nbaws

**Comment by nbaws** [comment]
could you please confirm if this problem is still occurring in latest dev release? If so, please let me know the version tested.
sigv4a key derivation was bugged and has been fixed in https://github.com/envoyproxy/envoy/pull/34377

**Comment by shulin-sq** [comment]
@nbaws thank you, patching that fix in seems to have fixed the issue.
