### ISSUE TITLE
Increased DNS Timeouts After Upgrading to v1.31.0

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#35117]
## Description

We have observed an increase in DNS timeouts after upgrading our Dev/Staging environment from [v1.30.2](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.30/v1.30.2) to [v1.31.0 (Dev)](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.31/v1.31.0). All other factors, including traffic load, remained unchanged. We suspect this issue might be related to the recent major version upgrade of c-ares [[Reference](https://github.com/envoyproxy/envoy/pull/33711/files)].

**DNS Resolver Events:**

An uptick in the DNS timeouts after switching to **v1.31.0** which goes away once we move back to **v1.30.2**,

![image](https://github.com/envoyproxy/envoy/assets/12120828/81b126a3-b5d0-481a-ad40-0813694a1b23)

Number of DNS resolutions (didn't change),

<img width="1027" alt="Screenshot 2024-07-05 at 10 43 45" src="https://github.com/envoyproxy/envoy/assets/12120828/8bf2d031-1879-4b34-acf6-7229407f89cd">

cc @alyssawilk @deveshkandpal1224

**Comment by nezdolik** [comment]
cc @yanavlasov @mattklein123

**Comment by alyssawilk** [comment]
Huh.  Would it be possible to run an experiment with the version downgraded back down?  If so  we could downgrade Envoy's dependency but I think we'd have to file with cares to fix the underlying problem

**Comment by arulthileeban** [comment]
This could be related: https://github.com/c-ares/c-ares/pull/542, which is part of the c-ares v.1.20.0 release. AFAIK Envoy uses the defaults for timeouts. Should we bump the defaults internally and/or expose it through an [option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/resolver.proto#config-core-v3-dnsresolveroptions)?

**Comment by agrawroh** [comment]
> This could be related: [c-ares/c-ares#542](https://github.com/c-ares/c-ares/pull/542), which is part of the c-ares v.1.20.0 release. AFAIK Envoy uses the defaults for timeouts. Should we bump the defaults internally and/or expose it through an [option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/resolver.proto#config-core-v3-dnsresolveroptions)?

@arulthileeban Thanks for the pointers. **Re:** DNS Timeouts, I tried doing that [here](https://github.com/envoyproxy/envoy/pull/30612) and am happy to re-open this PR and scope it to c-ares only for now.

**Comment by alyssawilk** [comment]
Sure we can go with that or I can land https://github.com/envoyproxy/envoy/pull/35335 which attempts to just restore prior behavior.  thoughts?

**Comment by agrawroh** [comment]
@alyssawilk You can merge your changes and I'll also re-open my PR as I think it's good for users to have these values configurable (we might need to up it more on our end)

**Comment by agrawroh** [comment]
@alyssawilk We tried back-porting your changes to set the previous defaults but we are still seeing the timeouts issue. I even tried to increase the timeout to 10s and am still noticing similar spikes. It looks like something else changed either around how we are reporting the timeouts or in the c-ares.

<img width="1369" alt="Screenshot 2024-07-25 at 17 19 47" src="https://github.com/user-attachments/assets/427ed121-8367-4ce8-aaa5-8157dd7a6b87">

The graph is from **~30 days** showing two set of spikes when we tried out rolling the new version without your changes at first and then after including the timeout changes.

**Comment by alyssawilk** [comment]
Could you try cherrypicking out https://github.com/envoyproxy/envoy/pull/33711/files (git revert or what have you) and see if that addresses the problem?

**Comment by agrawroh** [comment]
> Could you try cherrypicking out https://github.com/envoyproxy/envoy/pull/33711/files (git revert or what have you) and see if that addresses the problem?

@alyssawilk Yes, reverting the c-ares version bump does solve the timeouts issue. Unfortunately, we want the [udp_max_queries](https://github.com/envoyproxy/envoy/pull/33551) feature which is only available in the new version :(

**Comment by alyssawilk** [comment]
I spun up GDB and verified that channel timeout is getting set correctly in cares
(gdb) print channel->timeout
$8 = 5000
so the "supposed fix" looks like it worked.
without being able to reproduce the error rate I think I'm effectively stymied.  You might have to go poke the cares folk and ask them what else changed between the two versions which might have caused this, sorry :-/

**Comment by deveshkandpal1224** [comment]
@agrawroh - apologies for being late to the party, I just spot checked our envs and i'm not seeing DNS timeouts with 1.31-Dev. Is there a config_dump available that you can share for comparison ?

**Comment by agrawroh** [comment]
Just a hunch, could it be related to this issue?

https://github.com/c-ares/c-ares/commit/a070d78

I saw on the Dev channel that the issue was fixed upstream and we patched it,

https://github.com/envoyproxy/envoy/pull/35511

**Comment by alyssawilk** [comment]
cc @yanavlasov @adisuissa as we're discussing c_ares issues right now

**Comment by adisuissa** [comment]
Might be.
From looking at https://github.com/c-ares/c-ares/issues/571 I do see some references to timeouts, but not sure if its the same root cause.

FWIW, the fix will be part of Envoy v1.31.1, and Envoy-dev should already be using c-ares v1.21.0.
