### ISSUE TITLE
proposal: introduce START_TIME_LOCAL and EMIT_TIME_LOCAL for local time zone in access_log

### ISSUE THREAD

**Issue by doujiang24** [envoyproxy/envoy#35116]
_Originally posted in https://github.com/envoyproxy/envoy/issues/23260#issuecomment-2122534085_

The current time format is already complicated, i.e.
```
%START_TIME(%Y/%m/%dT%H:%M:%S%z)%
%START_TIME(%s.%3f)%
```

New command operators might be simpler, similar to `time_local` in [NGINX](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format)

I'd like to have a try if it's okay.

**Comment by nezdolik** [comment]
cc @zuercher

**Comment by doujiang24** [comment]
@mattklein123 @alyssawilk @wbpcode PTAL, thanks!

**Comment by wbpcode** [comment]
SGTM.
