### ISSUE TITLE
[QUESTION] use cluster healthcheck makes upstream delay

### ISSUE THREAD

**Issue by liyehaha** [envoyproxy/envoy#3512]
*Description*:
>
version: 1.7
when cluster healthcheck enabled, upstream servers will delay to response.

*Config*:
health_checks:
    - timeout:
        seconds: 10
      interval:
        seconds: 5
      unhealthy_threshold: 3
      healthy_threshold: 3
      tcp_health_check: {}

**Comment by mattklein123** [comment]
@liyehaha sorry, can't parse the question here.
