### ISSUE TITLE
Network::Utility::getLocalAddress performance is bad in multi-threads

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#35137]
When running benchmark with nighthawk on quic, it found that the quic client side spend a lot of time on the `Network::Utility::getLocalAddress`

![image](https://github.com/envoyproxy/envoy/assets/1070455/b645248d-2bac-4a2d-8e5a-c952448aabff)

The throughput can't be raised after concurrency 30
![image](https://github.com/envoyproxy/envoy/assets/1070455/91f99ad9-840b-4c3a-8bfd-e444a45076a0)

If the `Network::Utility::getLocalAddress` was removed, it get much better
![image](https://github.com/envoyproxy/envoy/assets/1070455/a8781665-0235-4acb-af0d-9329ff5db7c5)

The flamegraph also changed.
![image](https://github.com/envoyproxy/envoy/assets/1070455/175969da-390c-4406-a177-6fd08e205aa0)

the nighthawk is running as below:
`nighthawk_client --rps 100 --connections 20000 --duration 30 --concurrency <concurrency> -v warn --protocol http3 --address-family v4 --request-body-size 0 --request-method GET --max-requests-per-connection 1 --timeout 120 --max-active-requests 100000 https://www.example.com:13333/`

Thinking of there are two ways to fix this:
* cache the `Network::Utility::getLocalAddress`
* only bind to any address(0.0.0.0).

Looking for feedback on which way is better.

**Comment by nezdolik** [comment]
cc @jmarantz @wbpcode

**Comment by jmarantz** [comment]
@RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
@danzh2010 Did this issue get fix by your recent IP caching change?

**Comment by danzh2010** [comment]
The expensive call is getifaddrs() which should be fixed by @abeyad 's ongoing work of moving away from getLocalAddress() and use connected UDP socket instead. My IP caching change is for a different issue where Address::Instance object creation is too expensive.

**Comment by abeyad** [comment]
This issue should be fixed by https://github.com/envoyproxy/envoy/pull/35652, but @soulxu could you kindly verify?
