### ISSUE TITLE
downstream_rx_datagram_dropped shows big number with big jump when running UDP traffic.

### ISSUE THREAD

**Issue by nev888** [envoyproxy/envoy#35142]
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped shows big number and jumps up with really big numbers when running UDP traffic.
Collecting the stats during few minutes:
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped:  68763983128
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 210235537380
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 210235537380
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 210235537380
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 211333341100
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 212764708258
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 215293879136
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 215973672978 (last one after stopping udp traffic)
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 215973672978
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 215973672978
listener.<IP:PORT>.udp.downstream_rx_datagram_dropped: 215973672978

If the counter displays number of datagrams dropped for a specific listener?  These numbers don't look realistic from traffic perspective. There are not  that many traffic at all.

We are using envoy as L7 load balancer for sip traffic. On client side (downstream) traffic is received on TCP/UDP, traffic is load balanced to the application Pod (upstream) over GRPC. 

[stats.txt](https://github.com/user-attachments/files/16167024/stats.txt)
[server_info.txt](https://github.com/user-attachments/files/16167027/server_info.txt)
[clsuters.txt](https://github.com/user-attachments/files/16167028/clsuters.txt)

Envoy code is extended with our own for the specific use case we have.

**Comment by nezdolik** [comment]
cc @mattklein123 @danzh2010

**Comment by danzh2010** [comment]
Please adjust your listen socket's receive buffer size; https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http3#downstream-stats

**Comment by nev888** [comment]
Thanks @danzh2010, 
If  kernel’s UDP listen socket’s receive buffer isn’t large enough, Is it possible it causes other issues? We came across this counter value while investigating a memory leak.

**Comment by danzh2010** [comment]
> Thanks @danzh2010, If kernel’s UDP listen socket’s receive buffer isn’t large enough, Is it possible it causes other issues? We came across this counter value while investigating a memory leak.

It will become bandwidth limitation, but not memory leak.

**Comment by nev888** [comment]
Any recommendation how big it should be? currently it's ~9.5mb.

**Comment by danzh2010** [comment]
> Any recommendation how big it should be? currently it's ~9.5mb.

This depends on your bandwidth, and the Linux kernel doubles the number your supplied via setsockopt.

Also please keep in mind that the stats is accumulative.

**Comment by nev888** [comment]
One more question, Do you have any idea why the counter number is not in sync with traffic rate?
First measurement is 68763983128, few mins later it became 210235537380. 
I had running traffic for few hours, traffic rate were ~40 call/sec. I have generated truncated UDP traffic for few mins too but not even close to those numbers I see in the counter.  
All the generated traffic could have reached ~2million max, and not all of it were UDP, only half of it.

**Comment by danzh2010** [comment]
I don't know the ingress rate of your service. Assuming it's 5min range, you have ~400M packet drops per sec. You can check `netstat -p udp` to confirm the numbers are consistent with what kernel sees.

**Comment by nev888** [comment]
The previous stat were from a Pod which is not running anymore.
I have a different pod with these stats:
`listener.IPv4_PORT.udp.downstream_rx_datagram_dropped: 61610884148229`
`#kernel
IpInReceives                    3021072            0.0
IpInDelivers                    3021072            0.0
IpOutRequests                   3020920            0.0
TcpActiveOpens                  17                 0.0
TcpPassiveOpens                 93                 0.0
TcpEstabResets                  7                  0.0
TcpInSegs                       1023               0.0
TcpOutSegs                      871                0.0
TcpOutRsts                      32                 0.0
UdpInDatagrams                  690                0.0
UdpInErrors                     3019359            0.0
UdpOutDatagrams                 690                0.0
UdpInCsumErrors                 3019359            0.0
TcpExtTCPHPHits                 174                0.0
TcpExtTCPPureAcks               203                0.0
TcpExtTCPHPAcks                 317                0.0
TcpExtTCPAbortOnData            10                 0.0
TcpExtTCPAbortOnClose           7                  0.0
TcpExtTCPRcvCoalesce            9                  0.0
TcpExtTCPOrigDataSent           437                0.0
TcpExtTCPDelivered              454                0.0
IpExtInOctets                   779239070          0.0
IpExtOutOctets                  779149461          0.0
IpExtInNoECTPkts                3021072            0.0`

**Comment by danzh2010** [comment]
nstat only shows incremented values since last run, please use 'nstat -a'. And I didn't see the result had dropped packets count. Can you use `netstat -p udp`?

**Comment by danzh2010** [comment]
Which UDP extension are you using?

**Comment by nev888** [comment]
> nstat only shows incremented values since last run, please use 'nstat -a'. And I didn't see the result had dropped packets count. Can you use `netstat -p udp`?

`Tue Jul 16 07:39:46 CEST 2024
listener.IPv4:Port.udp.downstream_rx_datagram_dropped: 89237114699`
[nstat-2024-07-16_07-39.txt](https://github.com/user-attachments/files/16244986/nstat-2024-07-16_07-39.txt)
 
I don't have net netstat, I can use ss though.
[udp-sockets-2024-07-16_10-59.txt](https://github.com/user-attachments/files/16247597/udp-sockets-2024-07-16_10-59.txt)

**Comment by nev888** [comment]
> 114699

We don't use any UDP extension.

**Comment by danzh2010** [comment]
> > Which UDP extension are you using?
> 
> We don't use any UDP extension.

Are you using UDP Proxy?

**Comment by nev888** [comment]
No,

**Comment by danzh2010** [comment]
Can you share your UDP listener config?

**Comment by nev888** [comment]
Here the config for the listener 
[udp_listener.txt](https://github.com/user-attachments/files/16253368/udp_listener.txt)

**Comment by danzh2010** [comment]
If you are using raw UDP, why do you need this?

```
       "connection_balance_config": {
        "exact_balance": {}
       },
```

**Comment by nev888** [comment]
This config is intended for TCP listeners. On the controller side both UDP and TCP are configured with the same config that's why we have this here.

**Comment by danzh2010** [comment]
UDP listener other than QUIC is connectionless, you probably don't need that.

**Comment by nev888** [comment]
Yep, in UDP case we have no use for it. Do you think this might have anything to do with the counters problem?

**Comment by danzh2010** [comment]
Not sure. I'm not familiar with raw UDP listener interaction with connection_balance_config.  It is the cause, you may see a warning log about packet being dropped in only some of threads (not all) in Envoy log.

**Comment by shakedm** [comment]
I see a similar problem with a set up to test UDP in envoy. the dropped datagrams are in the tens of billions per second while the in traffic is just a couple hundred thousands, could be a counter issue? 
any idea if it's from envoy collecting the metrics or deeper down?

**Comment by nev888** [comment]
.
