### ISSUE TITLE
response header manipulation for DirectResponseAction

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#3520]
*Title*: header manipulation for DirectResponseAction

*Description*:
Our goal here is when we return an HTML file in a `DirectResponseAction` (i.e. a Forbidden page), to have it's `content-type` set to `text/html`. By default it's `text/plain`, rendering incorrectly in the browser. This could be done by setting the `content-type` response header but there is no way to specify response headers for _just_ a `DirectResponseAction` that I can identify ([proto struct](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L656)). Another solution is to have Envoy infer the content-type for `DirectResponseAction`s using the filesystem.

Currently, response headers can be modified at 1) the entire route configuration ([doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto#routeconfiguration)), 2) the virtual host level ([doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-virtualhost)), or 3) in a single RouteAction ([doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction)) which doesn't cover DirectResponseAction since they are "side-by-side".

Potential steps to resolve this are either
1) move the `response_headers_to_add` options from the [`RouteAction`](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L309) to the [`Route`](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L116) so that these options can apply regardless if the action is a `RouteAction`, `DirectResponseAction`, `RedirectAction` or any other future actions (preferred IMO but breaks the API)
2) Add `response_headers_to_add` options to `DirectResponseAction`, (and potentially) `RedirectAction`, and other future actions
3) Support the ability to detect content-type for `DirectResponseAction` based on filename extension if loading from file (easy but only solves a very narrow use-case, in this case ours)

This isn't a strict requirement we have to meet, but a feature that would be useful.

cc @rgs1 @brian-pane

**Comment by mattklein123** [comment]
I'm in favor of (1). We can't do a move, but we can add and deprecate.
