### ISSUE TITLE
HTTP/2 "PING" message does not reset timeout counter for routes

### ISSUE THREAD

**Issue by krootee** [envoyproxy/envoy#3522]
*Description*:
Envoy v1.6.0 route timeout ignores "PING" messages that are sent over the channel to keep it alive.
As results only option to keep a connection from being closed is to increase default timeout.
Our use case - gRPC server call that could take up to 90 seconds to produce reply (heavy calculations).

*Repro steps*:
Create Java gRPC server/client and configure "keep alive" (that would be sending "PING" messages every 10 seconds).
Observe that default Envoy configuration would close the connection after 15 seconds (default timeout) and "PING" messages are ignored.

**Comment by mattklein123** [comment]
In general, HTTP/2 PING is connection level and not stream level, so I don't think it's appropriate to use PING frames as a way of resetting the request timeout. Why not just raise your route timeout?

**Comment by krootee** [comment]
Yes - we raised timeout in this case, but then how "timeout" is different from "idle_timeout" parameter? 
Reading documentation I got the feeling that "idle_timeout" was for stream level and "timeout" was for connection level.

What about handlers that could take minutes to execute with the duration that could fluctuate due to the amount of data?

**Comment by mattklein123** [comment]
I'm not sure which timeouts you are referring. Please link to docs/protos. We plan on adding data frame timeouts in the future: https://github.com/envoyproxy/envoy/issues/1778

**Comment by mattklein123** [comment]
Closing. Please reopen if you have further questions.
