### ISSUE TITLE
OAuth2 filter: state/nonce support to prevent CSRF

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#35232]
*Title*: *state/nonce support to prevent CSRF*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

In the current implementation, the `state` parameter is only used to store the original request path. According to [ OAuth 2.0 Threat Model and Security Considerations](https://datatracker.ietf.org/doc/html/rfc6819#section-5.3.5), appending a nonce to the `state` parameter can prevent attackers from injecting their own access token into a victim's sessions via CSRF attack. The attack can result in victims saving their sensitive data in the attacker's account.

To implement this, the generated nonce can be stored securely , either in a secure cookie similar to the access token or in a shared storage like [Redis](https://github.com/envoyproxy/envoy/issues/35233). 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

- https://datatracker.ietf.org/doc/html/rfc6819#section-5.3.5
- https://github.com/envoyproxy/envoy/issues/29526

@arkodg @missBerg

**Comment by KBaichoo** [comment]
cc @mattklein123 @derekargueta

**Comment by derekargueta** [comment]
This is a dupe of https://github.com/envoyproxy/envoy/issues/29526
