### ISSUE TITLE
OAuth2 filter: Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#35230]
*Title*: *OAuth2 filter: Proof Key for Code Exchange (PKCE)*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

PKCE (Proof Key for Code Exchange) is an extension to the OAuth 2.0 authorization code flow that can prevent the authorization code interception attack. Implementing it can significantly enhance the security of the [OAuth2 filter ](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) .

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

[Proof Key for Code Exchange by OAuth Public Clients](https://www.rfc-editor.org/rfc/rfc7636)

@arkodg @missBerg

**Comment by missBerg** [comment]
I know some might say because the request is coming from server side PKCE isn't necessary, however, it improves the overall security posture of the implementation.

**Comment by KBaichoo** [comment]
cc @mattklein123 @derekargueta

**Comment by zhaohuabing** [comment]
@KBaichoo Could you please label it as no stalebot? It's still valid. Thanks!
