### ISSUE TITLE
Disabling all endpoints though EDS using health_status: "UNHEALTHY" flag does not work.

### ISSUE THREAD

**Issue by bmadhavan** [envoyproxy/envoy#3528]
**Bug Template**

*Title*: *Disabling all endpoints though EDS using health_status: "UNHEALTHY" flag does not work. 

*Description*:
I am using the health_status: "UNHEALTHY" flag in endpoint config to disable specific endpoints learnt using EDS. This works greats if some of the endpoints are set to UNHEALTHY thru EDS. If I try to set all the endpoints as UNHEALTHY, the logic breaks and I see that HTTP requests are actively load balanced across all the disabled endpoints.   

*Repro steps*: 
Change the EDS service cluster config to set both endpoints as `UNHEALTHY` like: 

`  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 172.17.0.3
            port_value: 80
      health_status: "UNHEALTHY"
      load_balancing_weight: 5
    - endpoint:
        address:
          socket_address:
            address: 172.17.0.6
            port_value: 80
      health_status: "UNHEALTHY"`

*Admin and Stats Output*:
`root@559b017ef645:/# curl localhost:8001/clusters
eds_service::default_priority::max_connections::1024
eds_service::default_priority::max_pending_requests::1024
eds_service::default_priority::max_requests::1024
eds_service::default_priority::max_retries::3
eds_service::high_priority::max_connections::1024
eds_service::high_priority::max_pending_requests::1024
eds_service::high_priority::max_requests::1024
eds_service::high_priority::max_retries::3
eds_service::added_via_api::false
eds_service::172.17.0.3:80::cx_active::0
eds_service::172.17.0.3:80::cx_connect_fail::0
eds_service::172.17.0.3:80::cx_total::0
eds_service::172.17.0.3:80::rq_active::0
eds_service::172.17.0.3:80::rq_error::0
eds_service::172.17.0.3:80::rq_success::0
eds_service::172.17.0.3:80::rq_timeout::0
eds_service::172.17.0.3:80::rq_total::0
eds_service::172.17.0.3:80::health_flags::/failed_eds_health
eds_service::172.17.0.3:80::weight::5
eds_service::172.17.0.3:80::region::
eds_service::172.17.0.3:80::zone::
eds_service::172.17.0.3:80::sub_zone::
eds_service::172.17.0.3:80::canary::false
eds_service::172.17.0.3:80::success_rate::-1
eds_service::172.17.0.6:80::cx_active::0
eds_service::172.17.0.6:80::cx_connect_fail::0
eds_service::172.17.0.6:80::cx_total::0
eds_service::172.17.0.6:80::rq_active::0
eds_service::172.17.0.6:80::rq_error::0
eds_service::172.17.0.6:80::rq_success::0
eds_service::172.17.0.6:80::rq_timeout::0
eds_service::172.17.0.6:80::rq_total::0
eds_service::172.17.0.6:80::health_flags::/failed_eds_health
eds_service::172.17.0.6:80::weight::1
eds_service::172.17.0.6:80::region::
eds_service::172.17.0.6:80::zone::
eds_service::172.17.0.6:80::sub_zone::
eds_service::172.17.0.6:80::canary::false
eds_service::172.17.0.6:80::success_rate::-1
root@559b017ef645:/#
root@559b017ef645:/#
root@559b017ef645:/#
root@559b017ef645:/# curl -v http://localhost:80/ufehttpsvc/getbytes/10
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /ufehttpsvc/getbytes/10 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost
> Accept: */*
>
< HTTP/1.1 200 OK
* Server envoy is not blacklisted
< server: envoy
< date: Fri, 01 Jun 2018 22:50:28 GMT
< content-type: application/octet-stream
< content-length: 11
< last-modified: Wed, 26 Jul 2017 18:50:11 GMT
< etag: "5978e463-b"
< accept-ranges: bytes
< x-envoy-upstream-service-time: 1
<
HelloWorld
* Connection #0 to host localhost left intact
root@559b017ef645:/# curl localhost:8001/clusters
eds_service::default_priority::max_connections::1024
eds_service::default_priority::max_pending_requests::1024
eds_service::default_priority::max_requests::1024
eds_service::default_priority::max_retries::3
eds_service::high_priority::max_connections::1024
eds_service::high_priority::max_pending_requests::1024
eds_service::high_priority::max_requests::1024
eds_service::high_priority::max_retries::3
eds_service::added_via_api::false
eds_service::172.17.0.3:80::cx_active::1
eds_service::172.17.0.3:80::cx_connect_fail::0
eds_service::172.17.0.3:80::cx_total::1
eds_service::172.17.0.3:80::rq_active::0
eds_service::172.17.0.3:80::rq_error::0
eds_service::172.17.0.3:80::rq_success::1
eds_service::172.17.0.3:80::rq_timeout::0
eds_service::172.17.0.3:80::rq_total::1
eds_service::172.17.0.3:80::health_flags::/failed_eds_health
eds_service::172.17.0.3:80::weight::5
eds_service::172.17.0.3:80::region::
eds_service::172.17.0.3:80::zone::
eds_service::172.17.0.3:80::sub_zone::
eds_service::172.17.0.3:80::canary::false
eds_service::172.17.0.3:80::success_rate::-1
eds_service::172.17.0.6:80::cx_active::0
eds_service::172.17.0.6:80::cx_connect_fail::0
eds_service::172.17.0.6:80::cx_total::0
eds_service::172.17.0.6:80::rq_active::0
eds_service::172.17.0.6:80::rq_error::0
eds_service::172.17.0.6:80::rq_success::0
eds_service::172.17.0.6:80::rq_timeout::0
eds_service::172.17.0.6:80::rq_total::0
eds_service::172.17.0.6:80::health_flags::/failed_eds_health
eds_service::172.17.0.6:80::weight::1
eds_service::172.17.0.6:80::region::
eds_service::172.17.0.6:80::zone::
eds_service::172.17.0.6:80::sub_zone::
eds_service::172.17.0.6:80::canary::false
eds_service::172.17.0.6:80::success_rate::-1`

*Config*: Trimmed to just EDS config. 
`
 "clusters":[{
           "name": "eds_service",
           "connect_timeout": "0.25s",
    	   "type": "EDS",
           "eds_cluster_config": {
              "eds_config": {
              "path": "/etc/server_eds.yaml"
              }
           }
       }]
`

Just want to know if this is expected or a bug (I feel). 

I will debug a little more to see if I can find the root cause.

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/faq/lb_panic_threshold

**Comment by bmadhavan** [comment]
Thanks @mattklein123 That definitely answers my question. 
Just curious to know if there is any history associated with having such a setting & also why it shd be enabled by default ?

**Comment by mattklein123** [comment]
@bmadhavan I think the FAQ and linked documentation is clear on what the motivation is. Do you have specific questions?

**Comment by bmadhavan** [comment]
Sorry for the delay.
For our use case where envoy is used as an edge proxy, I could not think of a very common situation where this is true - `a situation in which host failures cascade throughout the cluster as load increases.` But I am sure this might be a common situation in service mesh use case and hence the setting is made as a default.

**Comment by mattklein123** [comment]
@bmadhavan the same situation occurs for edge proxies as well. In fact, this logic was implemented way back when Envoy was only used as an edge proxy at Lyft. I'm going to go ahead and close this as answered.
