### ISSUE TITLE
Address::Instance equality implemented through string compare

### ISSUE THREAD

**Issue by curiouserrandy** [envoyproxy/envoy#3529]
**Issue Template**

*Title*: Address::Instance equality implemented through string compare

*Description*:
The currently implementations of Address::Instance (Ipv4instance, Ipv6Instance, and PipeInstance) all inherit from InstanceBase, which implements operator== as:

  bool operator==(const Instance& rhs) const override { return asString() == rhs.asString(); }

This works, but is a) dependent on the derived classes having a 1-1 mapping between string representations and unique instances, and b) not a very efficient method of computing equality for Ipv4 and Ipv6 addresses.  If we implement any algorithms that need to scale and compare Instances frequently, the string compare cost could be significant.

Unfortunately, the current method has the advantage of working (modulo (a) above) on all derived classes of Address::Instance, current&future, core envoy and downstream specializations as it is defined in terms of methods on Instance.  Individual derived types could use RTTI to determine if the type being compared to was a known type, and implement the comparison in a more efficient fashion if it was.  If it is desirable that RTTI be avoided, a visitor design pattern could be implemented on the Instance to do double dispatch on the types of the two objects being compared.   However, this involves a non-trivial change to the interface of the abstract base class.

@htuch : I hadn't figured out when we were talking what the implications of "We should do this upstream" were.  Given the above paragraph, do you have any prefereces?

**Comment by htuch** [comment]
I think it would be reasonable to `dynamic_cast` to the specific type and then make use of internal representation for an efficient comparison, i.e. RTTI. Equality is actually the "case for RTTI" in the style guide that provides the argument in the affirmative :)
