### ISSUE TITLE
Routing cookie enhancements

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#3532]
When issuing routing cookies, we may want to limit the cookie to the paths specified in the route match.

Also given I can't think of a good reason for them to be accessible from Javascript I think we should probably flag them HttpOnly by default.

**Comment by akonradi** [comment]
This sounds like a good idea, though we can't just stick the path from the route into the Set-Cookie `path` directive since the spec does prefix matching only. What about adding an explicit path configuration option?

**Comment by alyssawilk** [comment]
Yeah, I think that's the way we'd have to go.  I've sent you the httponly side since I know I care about that.  You want to take path, or should I flag as help wanted for now?

**Comment by akonradi** [comment]
Please flag it as help wanted, this'll make a good starter bug for someone.

**Comment by alyssawilk** [comment]
Actually if we're just adding path to ttl etc I'll do it in #3533 after my next meeting
