### ISSUE TITLE
SNI value set by auto-sni feature is not influenced by host header mutation

### ISSUE THREAD

**Issue by leosarra** [envoyproxy/envoy#35330]
*Title*: SNI value set by auto-sni feature is not influenced by host mutation

*Description*:
I have found a potential issue with the interaction between `auto_sni` and `host_literal_rewrite` (but not limited only to this type of host header manipulation) in Envoy. When both are set, the SNI value is determined based on the original request header before the host rewrite occurs.
This behavior can lead to SNI mismatches, potentially causing TLS handshake failures in setups that rely on correct SNI values after host rewrites.
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end
```
The behavior was noticed in the Istio community after one of the recent releases was shipped with auto-sni on by default.
https://github.com/istio/istio/issues/50126

*RCA*: 
The issue stems from the order of operations in Envoy's request handling:

- `auto_sni` is processed early, setting the SNI based on the original host header (or `override_auto_sni_header` if that one is set). [code](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L579-L609)
- Header manipulation based on route host options like `host_literal_rewrite`, occurs later in the flow and will update the request just before it is forwaded. code [here](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L723) and [here](https://github.com/envoyproxy/envoy/blob/main/source/common/router/config_impl.cc#L921)
- The SNI value is not updated to reflect these changes.

Is this behavior intentional or an oversight?
Do you think it would make sense to add an option to have host header manipulation at route level to affect auto-sni?
Would it make more sense to always have route-level host header manipulation (such as host_literal_rewrite) affect auto-sni?

I'm willing to implement the necessary changes to address this issue if you think it is a useful change.

**Comment by yanavlasov** [comment]
I think this change makes sense to me. It would need to be flag protected to allow fallback for people who might rely on the old behavior.

@ggreenway @alyssawilk for more comments.

**Comment by alyssawilk** [comment]
yeah runtime guard and config knob iff anyone relies on the old behavior SGTM

**Comment by leosarra** [comment]
FYI I have pushed a draft PR that contains the needed changes (#35566).
I will move it in review status once I have the new tests in place.
