### ISSUE TITLE
envoy_reloadable_features_normalize_host_for_preresolve_dfp_dns deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#35372]
Your change #30784 (dfp: Insert correct preresolved hostname key in DNS cache) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.

**Comment by alyssawilk** [comment]
@abeyad ping?

**Comment by abeyad** [comment]
Sorry, I missed this somehow, will work on it
