### ISSUE TITLE
Extend the functionality of max_connection_duration + drain_timeout

### ISSUE THREAD

**Issue by Winbobob** [envoyproxy/envoy#35391]
*Title*: *Extend the functionality of `max_connection_duration` and `drain_timeout` by introducing `drain_timeout_jitter` and `drain_percentage`.*

*Description*:
We are looking into ways to balance long-lived HTTP downstream connections. `max_connection_duration` + `drain_timeout` can be used for this purpose. However, we think its functionality could be extended and be more flexible. Assume this scenario: one client establishes many connections almost at the same time, once the connection duration limit reaches and there are no active streams, all connections will be drained in a short period, which may cause high latency for later requests since establishing connections need some time.

Proposal:
- Introduce `drain_timeout_jitter`, default to 0. If it is set to > 0, not all connections will be drained at the same time and if the jitter is long enough new connections have already been established and the impact of client could be minimal. 

- Introduce `drain_percentage`, default to 1. If it is set to (0,1), only a certain percentage of connections will be drained this time. For other connections, the connection duration will be reset and wait for the next round of drain.

*Relevant Links*:
https://github.com/envoyproxy/envoy/issues/15283

**Comment by Winbobob** [comment]
cc @alyssawilk and @mattklein123, any thoughts?

**Comment by alyssawilk** [comment]
I think for H2 it still works, it just may not establish many connections.
e.g. if you have 100 streams and want 10% prefetch ratio you need to prepare for 10 extra streams and will have 1 extra connection.  If you have 5000 streams you'll have 5 extra connections

**Comment by Winbobob** [comment]
> So the problem here is you have a high traffic service, you have a set connection drain time, and all your connections drain around the same time resulting in a bunch of lag all at the same time instead of spread out lag?

Not exactly. The problem is that we want to balance long-lived HTTP downstream connections. And the PreconnectPolicy only works for upstream connections. So looks like we still need to implement the jitter function.

**Comment by Winbobob** [comment]
Thank you for the confirmation! No problem at all! I really should highlight the downstream in the description.

**Comment by Winbobob** [comment]
This issue is not stale, I will try to work on the implementation.

**Comment by dragonmushu** [comment]
@Winbobob, @alyssawilk was there any workaround or solution built for adding a jitter to max connection duration?

**Comment by Winbobob** [comment]
https://github.com/envoyproxy/envoy/issues/42410 is discussing the same thing,

**Comment by Winbobob** [comment]
Hi @dragonmushu, the implementation (https://github.com/envoyproxy/envoy/pull/45101) was merged recently. It should be included in envoy 1.39, thanks.
