### ISSUE TITLE
DateFormatter only provide second level precision for absl format

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#35404]
This is because two problems:
1. `time_t` is used when calling the `absl::FormatTime`. The `time_t` only provide second level precision.
2. The time cache. The cache is updated in second level. And the code will get the cached string and replace sub-second part to sub-second of current timepoint. But the code only handle the specifier `%f` and don't handle absl format (actually it's not easy to handle it, this means we maybe shouldn't use time cache for dynamic format string).

**Comment by wbpcode** [comment]
cc @dio @mattklein123

**Comment by doujiang24** [comment]
> START_TIME can be customized using a [format string](https://en.cppreference.com/w/cpp/io/manip/put_time).

IIUC, the [doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage) does not mention support the fractional second format in `absl::FormatTime`, instead it only mention the `%f` format.
So, it's safe to cache by seconds, thoughts?

**Comment by wbpcode** [comment]
The default format that used by Envoy is `%Y-%m-%dT%H:%M:%E3SZ` but current `DateFormtter` even cannot support it correctly.

And the `DateFormatter` has tell it could support absl::FormatTime in its comments.

https://github.com/envoyproxy/envoy/blob/9537fce85d4f919d4b16de280f0ddf5b0130b8b5/source/common/common/utility.h#L43

So, I am inclined this is a code bug rather than a users-aware bug? If someone want to use this utility class, he may get unexpected result.
