### ISSUE TITLE
does envoy 1.7 now support TLS1.3?

### ISSUE THREAD

**Issue by futangw** [envoyproxy/envoy#3544]
**Issue Template**

*Title*: *does envoy 1.7 now support TLS 1.3*

*Description*:
Hi, 

Looks the BoringSSL already support TLS1.3 draft 28, right?
https://boringssl.googlesource.com/boringssl/+/56c4ed9ad78bcabdf84dd8d872666f4877c0dac6

And the envoy already has some update for BoringSSL:
https://github.com/envoyproxy/envoy/pull/3507/files/09aa244703bc9ed04c84deb73f6c568887bc1aed

So can I ask if the envoy now support TLS1.3? Or is there any config update is needed?

Today I downloaded the last envoy-alpine (3e95560ba8ab098689a97329fd23ade992b33718/1.7.0-dev/Clean/RELEASE) and set up a connection between 2 envoys (via http HC), but I still see them using TLS1.2.

![image](https://user-images.githubusercontent.com/24800972/40963383-eeb62e0e-68da-11e8-92e5-22252ba5c994.png)

thank for your kind response.

**Comment by mattklein123** [comment]
@PiotrSikora

**Comment by PiotrSikora** [comment]
@futangw it's supported, but not enabled by default (TLSv1.3 RFC wasn't published yet). You can enable it with [`tls_maximum_protocol_version: TLSv1_3`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto#auth-tlsparameters).

**Comment by moderation** [comment]
@futangw I can confirm it is working. With the version of boringssl we have in the repo only Draft 23 is supported. If you upgrade that dependency to the `master with bazel` branch at https://boringssl.googlesource.com/boringssl/+/master-with-bazel, Envoy will negotiate both Draft 23 and Draft 28 (which is the final approved draft).

**Comment by davidben** [comment]
Draft 28 is not quite the final draft either. The version number will change one more time on the wire to 0304. (Also we'll add the server random downgrade hardening which can't be added until the final version.)

**Comment by futangw** [comment]
@mattklein123 @PiotrSikora @moderation @davidben 
Thanks a lot for the information. With adding config of 'tls_maximum_protocol_version', I can see the TLS version is 1.3 now.
