### ISSUE TITLE
feature/accesslog: Stream formatters for client cert chain auditing

### ISSUE THREAD

**Issue by keithmattix** [envoyproxy/envoy#35452]
*Title*: *Stream formatters for cert chain elements*

*Description*:
To my knowledge, it's not possible to log any information (e.g. fingerprints, serial numbers) about the full downstream cert chain that a listener receives (in an mTLS scenario). This information is useful for auditing the actor that made a request during a potential breach. A stream formatter like `%DOWNSTREAM_PEER_CHAIN_FINGERPRINTS_(256|1)%` would be sufficient. If there's no opposition to this feature, I'll happily submit a PR.

**Comment by soulxu** [comment]
cc @wbpcode

**Comment by soulxu** [comment]
@keithmattix Does the `%DOWNSTREAM_PEER_CERT%` match your case, it seems to dump the cert to the access log. https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log

**Comment by keithmattix** [comment]
> @keithmattix Does the `%DOWNSTREAM_PEER_CERT%` match your case, it seems to dump the cert to the access log. https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log

All of the existing stream formatters only return the information for the leaf cert. This feature request would return fingerprints for all certs sent in the client cert bundle

**Comment by wbpcode** [comment]
SGTM.
