### ISSUE TITLE
use re2 for the substitution formatter parsing and prefer the string view

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#35466]
*Title*: *use re2 for the substitution formatter parsing and prefer the string view*

*Description*:

Compared to the std::regex, re2::RE2 has much better performance. And re2::RE2 provides better string view support. Using se the re2::RE2 to replace the std::regex and preferring the string view when doing the parsing could improve parser's performance greatly.

I made a dirty patch and get initial results. Here is the comparation:

Before:
```
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BM_AccessLogFormatterSetup            75744 ns        75605 ns         9401
```

After:
```
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BM_AccessLogFormatterSetup             8617 ns         8601 ns        80261
```

There is almost 10x speed up.

**Comment by wbpcode** [comment]
cc @jmarantz cc @mattklein123

**Comment by kyessenov** [comment]
+1, a generated parser might be even better but the grammar should be simple enough to handle without it.
