### ISSUE TITLE
Access log's timestamps are still in UTC regardless a containter's timezone?

### ISSUE THREAD

**Issue by hawran** [envoyproxy/envoy#3546]
Hi,
I'm trying to configure envoy (as a docker container) to use my format string and I've noticed a strange behaviour:

**1. All timestamps use UTC.**
Finally I've managed to persuade the image to use my timezone, hence envoy uses timestamps using my localtime.
However:

**2. When I try to set up my access log's format (for a http connection manager), all timestamps are still in UTC.**

What am I missing?

Regards,
hawran

**Relevant Links**:
The image used:
https://hub.docker.com/r/envoyproxy/envoy/tags/ 9a047dca7e3cdaf0f85239c499f63ee2b688160d
Access log Formatting:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/file.proto
https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#config-access-log-format

PS: Is there any possibility to use whatever second fractions (mili / micro / nano ) for the `%START_TIME%` command operator as is described for the command line formatter parameter? (as mentioned [here](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-log-format)?)

*Could this help?*
https://github.com/envoyproxy/envoy/blob/6f6d0fa23261df1b6c96e033da569c4755e9f48f/source/common/common/utility.cc#L250
https://github.com/envoyproxy/envoy/blob/4380526a1d5fa62e59464fdd86599a74126812ab/source/common/access_log/access_log_formatter.cc#L416
https://github.com/envoyproxy/envoy/blob/ead0de979c339f2dfb209ebdd1c93ee1ef7c7d74/source/common/access_log/access_log_formatter.h#L223

**Comment by mattklein123** [comment]
UTC is by design. Trust me, you really want UTC.

For partial seconds see https://github.com/envoyproxy/envoy/pull/3269

**Comment by hawran** [comment]
OK, thank you.

**Comment by liyehaha** [comment]
I really don't want UTC

**Comment by emike922** [comment]
I wonder, is it expected that "normal" logs still print in local TZ?
I might prefer it if they were consistent with access logs / always used UTC...

```
2022-05-03T03:15:11.858713Z     info    envoy main      initializing epoch 0 (base id=0, hot restart version=disabled)
...
[2022-05-03T11:21:38.233Z] "GET /status/418 HTTP/1.1" 418 - via_upstream - "-" 0 135 24 23 "-" "curl/7.66.0" "d67b0b2a-7c9e-43f0-a94f-8750e2cfdea6" "httpbin:8000" "172.17.0.10:80" outbound|8000||httpbin.istio-system.svc.cluster.local 172.17.0.6:35658 10.107.66.204:8000 172.17.0.6:44732 - default
```
Note, this is not from vanilla Istio but from another distro which includes timezone files.
