### ISSUE TITLE
How to configure a RDS in a static listener?

### ISSUE THREAD

**Issue by mcfongtw** [envoyproxy/envoy#35477]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Description*:
We are new to XDS and have a couple questions on RDS.  We have a running version of static configuration that envoy runs on, and we are trying to upgrade one of the service using dynamic route. So far, have a working version of configuring dynamic routes in a new dynamic listener as all of the examples we have found. However, we are wondering if we could have the dynamic routes configured in a static listener? Does dynamic route (RDS) needs to associate with a dynamic listener (LDS)?

Thanks and Regards,

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by soulxu** [comment]
you can use the 'rds' field in http connection manager filter https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager, I found there is an example config clip (although it isn't fully example for RDS), you may reference how to use the rds field: https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/extension#id1
