### ISSUE TITLE
Adding HTTP service support for Envoy external processing

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#35488]
*Title*: Adding HTTP service support for Envoy external processing

*Description*:
Currently Envoy ext_proc filter can only talk to a gRPC service to do external processing.  There is a need for ext_proc filter to be able to talk to a raw HTTP service to do the external processing.
This issue tracks the work needed to send HTTP messages to carry headers(request/response) to the side stream server.
Sending body or trailers using HTTP message will be tracked by a separate effort.

**Comment by yanjunxiang-google** [comment]
It is planned to have multiple incremental PRs to support this feature:

1) API to add the API service
2) Adding ext_proc HTTP client
3) Refactor the ext_proc filter code to be able to support either gRPC client or HTTP client based on filter configuration.
4) Adding ext_proc HTTP service testing framework.
5) Adding integration test to test ext_proc filter <----> HTTP service end-to-end.

**Comment by soulxu** [comment]
cc @gbrail @stevenzzzz @tyxia @mattklein123 @htuch @yanavlasov

**Comment by yanjunxiang-google** [comment]
The processing flow works this way:

When Envoy needs to send call out messages to the side stream server, either header, body , or trailer, Envoy construct a ProcessingRequest proto message.
This ProcessingRequest message is transcoded into a JSON text. This JSON text is then added as a body to a HTTP "POST" message. This HTTP message is sent to the side stream HTTP server.
The HTTP server receives the "POST" message. Transcoding the body, i.e, a JSON text, into a ProcessingRequest message.
The HTTP server then performs normal header/body/trailer mutation as existing, and put them into a ProcessingResponse proto message.
The HTTP server then transcode the ProcessingResponse into JSON text, and sends back a 200 response with this JSON text as body.
After receives the 200 response, Envoy then convert the body from JSON text back to a ProcessingResponse proto message. Then continue processing this ProcessingResponse.
Overall, the ext_proc gRPC and HTTP share identical state machine. The only difference is that in the transport layer, one using gRPC, and the ProcessingRequest/ProcessingResponse messages are sent as proto messages. The other sends messages using HTTP, with the ProcessingRequest/ProcessingResponse proto messages are transcoded into JSON text, and encoded as the body in the HTTP messages.

**Comment by yanjunxiang-google** [comment]
#35740 fixed the issue.
