### ISSUE TITLE
Adjust the order of http headers

### ISSUE THREAD

**Issue by ArcticUnicorn** [envoyproxy/envoy#35495]
Title: Adjust the order of http headers

Description:
I tried to adjust the order of the http headers，i would like to move the traceid, spanid and parentspanid to the front of the HTTP header. Http header  is transmitted according to the adjusted order of the http header.No other changes are made to the overall process of Envoy.  I have attempted to use both Lua filters and the Wasm plugins mechanism to achieve this problem,  but unfortunately, I have tried both of these methods and have not been able to resolve this issue.
Does anyone have any suggestions for this?

**Comment by alyssawilk** [comment]
yeah envoy stores headers in a map and is going to output them based on that.  I don't think there's a mechanism to guarantee ordering and I think it's dangerous to rely on header orders in any case.

**Comment by ArcticUnicorn** [comment]
Following the above question, why doesn't Envoy use an ordered map when storing headers? That's puzzling. The results of wireshark packet capture show that the order of headers is fixed every time, as shown in Figure1. It seems that the headers have a fixed order. What operation is done?
![Uploading wiresharkcapture.png…]()

**Comment by ArcticUnicorn** [comment]
> yeah envoy stores headers in a map and is going to output them based on that. I don't think there's a mechanism to guarantee ordering and I think it's dangerous to rely on header orders in any case.
Following the above question, i think the order of the headers does not affect the service. Also, that's puzzling, the results of wireshark packet capture show that the order of headers is fixed every time, as shown in Figure1. It seems that the headers have a fixed order. What operation is done?
![wiresharkcapture](https://github.com/user-attachments/assets/88dc1b73-5680-43c7-90cb-9cca7a1bd8cd)
