### ISSUE TITLE
 OAuth2 filter:  add domain to token cookies

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#35490]
*Title*: * OAuth2 filter:  add domain to token cookies*

*Description*:
The OAuth2 filter stores ID and access tokens in cookies without specifying Domain. It would be super useful if a domain could be specified, then users don't have to login every subdomains.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Envoy Gateway issue: https://github.com/envoyproxy/gateway/issues/3919

**Comment by soulxu** [comment]
cc @derekargueta @mattklein123
