### ISSUE TITLE
Enabling envoy.restart_features.upstream_http_filters_with_tcp_proxy breaks //test/extensions/upstreams/tcp/generic:config_test

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#35509]
Mock expectations are not correct.

Introduced by #32991

It looks like a just a config test problem. Does not affect any integration tests.

@vikaschoudhary16

**Comment by alyssawilk** [comment]
@yanavlasov ooc why is this a problem?  AFIK there's no expectation for default-false flags to pass all tests when true.

**Comment by yanavlasov** [comment]
How can you tell if a enabling a flag to true does not break Envoy in some horrible way if not all tests pass?

I think there should be an expectation that enabling flag to `true` does not break any tests. Otherwise it is not possible to reason whether this breakage is something that is just test related or something that truly breaks Envoy. If some tests depend on the 'false' value to work they should set it explicitly.

**Comment by alyssawilk** [comment]
This particular test flag is for a WIP feature.  I think any false flag is high risk and it's up to the person deploying it to do risk assessment including deciding if the tests need to pass.
