### ISSUE TITLE
Add s390x build status in README

### ISSUE THREAD

**Issue by namrata-ibm** [envoyproxy/envoy#35518]
We have setup a job for building Envoy-static on s390x in OSU infra: https://ibmz-ci.osuosl.org/job/Envoy_IBMZ_CI/
And similar to ppc , we are looking forward to add s390x build badge to README.

Currently we are running the job daily, would you be willing to provide a build hook for regular triggers on merge?

I can raise a PR to update README, could you please your thoughts.

**Comment by soulxu** [comment]
cc @phlax @alyssawilk

**Comment by alyssawilk** [comment]
SGTM, feel free to raise a PR. I'd suggest if you want it listed you include a point of contact and/or link to the build, that way if folks hit trouble they have a point of contact and if they get no response we know it's no longer supported

**Comment by namrata-ibm** [comment]
Thank you @alyssawilk 
I will add link to the build and we will be monitoring the CI closely for any failures.

**Comment by phlax** [comment]
hi @namrata-ibm - re the event hook, we have an existing bot setup that triggers builds/sync/etc in other repos, so if its in a github repo this might be useful, otherwise lmk and i can help set up any required auth etc

**Comment by namrata-ibm** [comment]
hi @phlax Jobs are currently setup on Jenkins : https://ibmz-ci.osuosl.org/job/Envoy_IBMZ_CI
If you could help in adding webhook in Envoy Github repo for above Jenkins, builds should be automatically triggered whenever new commits are merged.
We can discuss more over email if required.
Thank you for your support!

**Comment by phlax** [comment]
are you on the envoy slack? feel free to DM me there (@phlax)
