### ISSUE TITLE
UUIDv7 support for X-Request-Id field

### ISSUE THREAD

**Issue by Hexta** [envoyproxy/envoy#35522]
*Title*: *UUIDv7 support for X-Request-Id field*

*Description*:
Adding UUIDv7 support for `X-Request-Id` field will allow to improve search by `X-Request-Id` performance through the access logs thanks to time sortability of UUIDv7 values.

[optional *Relevant Links*:]
https://www.rfc-editor.org/rfc/rfc9562.html#name-uuid-version-7

**Comment by soulxu** [comment]
cc @alyssawilk
