### ISSUE TITLE
flake in TcpTunnelingIntegrationTest.UpstreamHttpFiltersPauseAndResume

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#35523]
[ RUN      ] IpAndHttpVersions/TcpTunnelingIntegrationTest.UpstreamHttpFiltersPauseAndResume/IPv4_Http3Downstream_HttpUpstreamHttpParserNghttp2NoDeferredProcessingLegacyWithUpstreamHttpFilters
test/integration/tcp_tunneling_integration_test.cc:954: Failure
Value of: tcp_client_->write("hello", true)
  Actual: false (Failed to complete write or unexpected disconnect. disconnected_: true bytes_drained: 10 bytes_expected: 10)
Expected: true
Stack trace:
  0x5633ea055a44: Envoy::(anonymous namespace)::TcpTunnelingIntegrationTest_UpstreamHttpFiltersPauseAndResume_Test::TestBody()
  0x5633edae0f15: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x5633edadbcad: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x5633edac2574: testing::Test::Run()
  0x5633edac2f97: testing::TestInfo::Run()
... Google Test internal frames ...

**Comment by vikaschoudhary16** [comment]
@alyssawilk ran following command multiple times:
```
bazel test  -c dbg  //test/integration:tcp_tunneling_integration_test --config=libc++ --test_filter=*IpAndHttpVersions/TcpTunnelingIntegrationTest.UpstreamHttpFiltersPauseAndResume/IPv4_Http3Downstream_HttpUpstreamHttpParserNghttp2NoDeferredProcessingLegacyWithUpstreamHttpFilters* --notest_keep_going --runs_per_test=100 -t-
```
Not able to get the test failed even once. Can you please review my command once? Also would appreciate any tips on how I can reproduce this.

**Comment by alyssawilk** [comment]
I'd definitely go up to 2k/4k.  it that doesn't get you anywhere you could alwys use the scoped test logger to turn up logging for that test so next it fails CI we have debug info, then you can close it off as "can't repro" :-)

**Comment by alyssawilk** [comment]
failed again on CI
https://dev.azure.com/cncf/envoy/_build/results?buildId=177371&view=logs&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=1002ac43-da84-5fae-70b2-98833b702d09&l=932
so looks like it's repeatable there at least.

**Comment by phlax** [comment]
this is still happening pretty frequently

**Comment by vikaschoudhary16** [comment]
oh, will retry
