### ISSUE TITLE
thread-safety-reference-return warning

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#35558]
Although the lock is in assertion but clang 12 complains on

https://github.com/envoyproxy/envoy/blob/main/source%2Fcommon%2Fstats%2Fthread_local_store.h#L418-L426

```
source/common/stats/thread_local_store.h:425:14: warning: returning variable 'central_cache_' by reference requires holding mutex 'parent_.lock_' [-Wthread-safety-reference-return]
  425 |       return central_cache_;
      |              ^
```

**Comment by soulxu** [comment]
cc @phlax

**Comment by phlax** [comment]
currently supported clang is clang-14 - any other version YMMV

**Comment by amit-k-yadav** [comment]
I am seeing the same error with clang 18.1.8 during a bazel build (Bazel version - 7.1.2)

**Comment by amit-k-yadav** [comment]
@krinkinmu  thanks the flag worked and I could build without an issue. 

@phlax  I am not building from `main` but from a specific commit - https://github.com/envoyproxy/envoy/commit/e3ed5a7
