### ISSUE TITLE
Query Parameter Routing wit same prefix

### ISSUE THREAD

**Issue by DennisRutjes** [envoyproxy/envoy#3556]
*Title*: *Query Parameter Routing*

*Description*:
>Recently Query Parameter Routing has been introduced, however multiple mappings with the same prefix but different name/value pairs for the routing are not honered.
I am using Ambassador en use
      envoy_override:
        query_parameters:
        - name: service
          value: GetMap

[optional *Relevant Links*:]
> e.g. the folowing configuration :
prefix: /test , query_parameters name=service,value=getmap => rewrite /server/getmap
prefix: /test , query_parameters name=service,value=getcapabilities=> rewrite /server/getcapabilities

the request : 
/test?service=getmap should route to server/getmap
/test?service=getcapabilities should route to server/getcapabilities

Are there any options to differnet routeson same prefix URL?

With kind regards,

Dennis Rutjes

**Comment by DennisRutjes** [comment]
Looks like ambassador uses an 1.3 forked version of envoy wil liook into that first closing for now

**Comment by jpfaria** [comment]
Dennis,

It did not work for me. Did it work for you?

Ambassador Version: 0.39.0 
Envoy Version: 1.7.0

`getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  pricing_prc-role-v351_v3_mapping
      prefix: /pricing/prc-role/v3/
      service: prc-role-v351.pricing:80
      tls: false
      envoy_override:
        query_parameters:
          - name: brand
            value: brand1`
