### ISSUE TITLE
SPIFFE: support JWK set bundle format

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#35567]
Implement support for SPIFFE bundle format in the SPIFFE validator: https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Trust_Domain_and_Bundle.md#4-spiffe-bundle-format

This allows de-coupling of the identity system from the xDS control plane, and the trust bundles can be updated independently.

**Comment by briansonnenberg** [comment]
[WIP PR](https://github.com/envoyproxy/envoy/pull/36190)
