### ISSUE TITLE
Understanding the purpose of GetConfigTracker() on admin interface.

### ISSUE THREAD

**Issue by ppourali** [envoyproxy/envoy#35582]
*Title*: *What is the purpose of GetConfigTracker() on admin interface?*

*Description*:

Hi all, 

We are currently exploring options to get Config update notifications and found that there is an GetConfigTracker() on the server_context.admin().

The documentation is not clear what this map is. Can we add our own callbacks to be run when the config is updated? e.g., when listeners are updated do xyz().
https://github.com/envoyproxy/envoy/blob/main/source/server/admin/config_tracker_impl.h

To give you more context: We have a bootstrap extension from which we want to get notified on the config updates (mostly listeners updates from xds) and perform some operation (within the bootstrap extension instance). I know that there is an xds configtracker extension for this purpose too. However, from our Bootstrap extension instance, we do not seem to be easily have access to the xds configtracker extension instance or the xds config tracker extension instance does not seem to have access to the bootstrap extension instance to call an operation on it. Therefore, I think this configtracker() on the admin() interface which is accessible from the Bootstrap extension instance (i.e., `Server_factory_context.admin().config_tracker()` ) might be something of interest for us.

Thanks,
Parsa

**Comment by RyanTheOptimist** [comment]
@jmarantz

**Comment by RyanTheOptimist** [comment]
cc: @ohadvano
cc: @wbpcode

**Comment by jmarantz** [comment]
I do not know the origin of that function, or that it even existed. But my guess is that it was added a very long time ago to the admin interface, but probably shouldn't be there. It looksl ike it might be better suited to be on the Server object?

@mattklein123 @htuch for the history of that.

**Comment by htuch** [comment]
Config tracker was introduced in https://github.com/envoyproxy/envoy/commit/24297974e479929568115a3dbce06c4e8f698f5a. What is preventing the xDS config tracker updates from a bootstrap extension?

CC @adisuissa

**Comment by ppourali** [comment]
On a more general note, is there any way to get the xds_config_tracker_extension instance from a bootstrap extension instance or vice versa (i.e., get the bootstrap extension instance from the  xds_config_tracker_extension instance ) ? Do these two have somehow visibility/navigability to each other?
