### ISSUE TITLE
Improving ip tagging filter

### ISSUE THREAD

**Issue by cqi1217** [envoyproxy/envoy#35629]
*Title*: Allow setting tags in a custom header

*Description*:
Now in ip tagging filter, all tags will be put into a fixed header. It would be better to add a custom header field in the proto then users can export tags to the custom header.

[optional *Relevant Links*:]
A draft pr: https://github.com/envoyproxy/envoy/pull/35628

**Comment by adisuissa** [comment]
cc @alyssawilk @JuniorHsu as codeowners
