### ISSUE TITLE
hot restart envoy

### ISSUE THREAD

**Issue by jvrahav** [envoyproxy/envoy#35635]
*Title*: *Hot Restart Envoy*

*Description*:
>I have envoy running as a pod where the envoy config is mounted as a volume from a configmap. When i change the configmap, the config file in pod is updated. However the envoy process is not restarted. I had to send a sighup signal to the container to restart the envoy process

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RyanTheOptimist** [comment]
@ravenblackx

**Comment by ravenblackx** [comment]
I don't really know much about pods. I don't believe updating a config file is expected to trigger hot_restart though (or any kind of restart), there's a whole mess of stuff you're supposed to do for hot restart. I'd be surprised if sighup to a container triggers the hot restart either, I would expect it to just provoke a regular restart.

If your goal is to live-update config changes, you most likely want to be using xds, not trying to hot restart.

**Comment by ravenblackx** [comment]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration

**Comment by ravenblackx** [comment]
If you don't want to set up xds (it's not super simple) hot restart is an option but it's also not super simple, especially with containerization. https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart#arch-overview-hot-restart - if your containers aren't too complicated you might be lucky enough that hot-restarter.py will work for your needs.
