### ISSUE TITLE
Use retry to work around ARM servers being reaped on AZP

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#35640]
We regularly see CI failures from ARM servers with errors like:

`
##[error]We stopped hearing from agent i-073d51e31827d7d90. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
`

Evidently this is because we use discount arm servers on azp and they can get reaped when its busy. Long term, we could migrate off of AZP and to GitHub.

However we could use retries to work around this in the short term.

**Comment by mathetake** [comment]
this is getting serious - in https://github.com/envoyproxy/envoy/pull/35626, the arm64 job failed four times in a row failed, and each looks like running forever from GitHub UI hence `/retest` doesn't work while it appeared (correctly?) failure on Azure UI
