### ISSUE TITLE
STRICT_DNS cluster with empty hosts prevents envoy initialization from completing

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#3566]
*Description*:
Envoy does not complete startup if there is a STRICT_DNS cluster with an empty hosts array. It never gets as far as opening listeners.

*Repro steps*:
Start envoy configured to load the following cluster via CDS:
```
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: "the_cluster"
    connect_timeout: 2s
    lb_policy: RANDOM
    type: STRICT_DNS
    hosts:  []
```

**Comment by ggreenway** [comment]
The cause is that parent_onPreInitComplete() is called when the first DNS resolution completes for the cluster. But if there are no resolutions to perform, this is never called.

**Comment by mattklein123** [comment]
IMO we should just treat zero hosts for a strict cluster as a config error.

**Comment by ggreenway** [comment]
> IMO we should just treat zero hosts for a strict cluster as a config error.

On the other hand, it's valid for static clusters to have empty hosts. I ran into this due to a machine-generated config, and I didn't notice the empty hosts.

On a related note, it was painful to debug why envoy was stuck during startup. To increase visibility/debugability, I was thinking of adding a timer and printing a log message every 5s naming which clusters are still blocking init. Thoughts?

**Comment by mattklein123** [comment]
> On the other hand, it's valid for static clusters to have empty hosts. I ran into this due to a machine-generated config, and I didn't notice the empty hosts.

Sorry, I don't completely follow. Shouldn't that be a config error also if it's not?

> On a related note, it was painful to debug why envoy was stuck during startup. To increase visibility/debugability, I was thinking of adding a timer and printing a log message every 5s naming which clusters are still blocking init. Thoughts?

Sure, that sounds useful. Though, I feel like we should do it more generically as part of the init manager so we can output other blocks as well around RDS, etc.?

**Comment by mattklein123** [comment]
> Also, I've found it useful to allow an empty hosts array.

Got it. OK. Out of curiosity why? If you want to allow empty hosts that's fine, we can just fix the bug.

**Comment by ggreenway** [comment]
> Out of curiosity why?

One fewer conditional in generating the config. When I'm deciding which clusters to create, I don't have to consider whether they have any hosts in them. I only have to consider which hosts there are when filling in the hosts-array.

**Comment by mattklein123** [comment]
OK. I'm fine either way, we can just fix the bug.

**Comment by futangw** [comment]
@mattklein123 
If the CDS file without host, the envoy would memory leak. i'm using envoy 1.6.
example cds file:
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: grpc1
  connect_timeout: { nanos: 250000000 }
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN

- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: grpc2
  connect_timeout: { nanos: 250000000 }
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN

Here's a piece of dump of envoy process, the memory keeps increasing.

Tue Oct 23 20:53:24 UTC 2018
root       603  0.1  0.4  93320 36840 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:54:24 UTC 2018
root       603  0.1  0.4  94344 37104 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:55:24 UTC 2018
root       603  0.1  0.4  94344 37104 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:56:24 UTC 2018
root       603  0.1  0.4  94344 37368 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:57:24 UTC 2018
root       603  0.1  0.4  94344 37368 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:58:24 UTC 2018
root       603  0.1  0.4  94344 37368 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 20:59:24 UTC 2018
root       603  0.1  0.4  94344 37632 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:00:24 UTC 2018
root       603  0.1  0.4  94344 37632 ?        Sl   17:33   0:14 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:01:24 UTC 2018
root       603  0.1  0.4  94344 37632 ?        Sl   17:33   0:15 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:02:24 UTC 2018
root       603  0.1  0.4  94344 37896 ?        Sl   17:33   0:15 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:03:24 UTC 2018
root       603  0.1  0.4  94344 37896 ?        Sl   17:33   0:15 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:04:24 UTC 2018
root       603  0.1  0.4  95368 38160 ?        Sl   17:33   0:15 envoy -c tas-core.json --service-cluster test --service-node test1
Tue Oct 23 21:05:24 UTC 2018
root       603  0.1  0.4  95368 38160 ?        Sl   17:33   0:15 envoy -c tas-core.json --service-cluster test --service-node test1

**Comment by futangw** [comment]
@ggreenway @mattklein123 I had confirmed even with 'hosts: []' in cds file, the memory leak also exists.

**Comment by WIgor** [comment]
I've caught almost the same problem. Empty hosts leads to partial configuration (only clusters were loaded), no listeners and routes. 

Errors in log about misconfiguration would be great.
