### ISSUE TITLE
How to build and got a small envoy binary?

### ISSUE THREAD

**Issue by zhongtianq** [envoyproxy/envoy#35668]
I use the docker image: envoyproxy/envoy-build-ubuntu to build envoy.
I got the envoy binary about 400MB, which is much larger than the binary in envoyproxy/envoy:devxxxx.
How can i get the small binary(<50MB)?  

Here is my cmd: 
export PATH=/opt/llvm/bin:$PATH
export CC=clang
export CXX=clang++
bazel --output_base=target build -c opt  --verbose_failures=true //:envoy --config=sizeopt --repository_cache=/tmp/bazel_repo_cache

**Comment by phlax** [comment]
what target are you building?

i think you want `//source/exe:envoy-static.stripped`

**Comment by zhongtianq** [comment]
> what target are you building?
> 
> i think you want `//source/exe:envoy-static.stripped`

Thank you for your response. I have a follow-up question regarding why envoy-static.stripped can be used as the target，as I only found envoy-static in the //source/exe:BUILD file ？

**Comment by zhongtianq** [comment]
> > what target are you building?
> > i think you want `//source/exe:envoy-static.stripped`
> 
> Thank you for your response. I have a follow-up question regarding why envoy-static.stripped can be used as the target，as I only found envoy-static in the //source/exe:BUILD file ？

It seems to be a bazel rule, i found it
