### ISSUE TITLE
redis_proxy: add support for external authentication

### ISSUE THREAD

**Issue by dbarbosapn** [envoyproxy/envoy#35673]
## Feature overview

Redis proxy users may want to create advanced authentication methods.
For example, the official [Azure SDK extension for Redis](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis) allows to authenticate to a Redis server using Microsoft Entra ID token-based authentication, by passing a token in the password argument of the `AUTH` command periodically, based on token expiration.
This PR introduces a way to support external authentication via a gRPC service with additional support for expiry of such authentication (e.g. for token-based authentication).
This way we keep it extensible for **any** advanced authentication methods users might want to develop.

### FAQ: Why not use the _ext_authz_ filter?
The cost/latency impact by using the _ext_authz_ filter is much bigger than the proposed design. That's because instead of being called on every request, the current design only calls the external dependency on **AUTH** commands. Not only that, but also we would have to decode the Redis protocol twice, if we used a separate filter.

**Comment by adisuissa** [comment]
cc @msukalski @henryyyang @mattklein123 @weisisea as codeowners of the redis-proxy filter

**Comment by dbarbosapn** [comment]
@adisuissa what's the best way to get traction on this?
We'd love to have this on next release 🙇

**Comment by dbarbosapn** [comment]
@adisuissa Are there other CODEOWNERS we could tag to review the PR?
Maybe @phlax knows?

Any help is appreciated 😃 

Thank you!

**Comment by phlax** [comment]
i think @mattklein123 is the reviewer you want
