### ISSUE TITLE
Why the HTTP filter will be destructed even when encodeData returns StopIterationAndBuffer?

### ISSUE THREAD

**Issue by jokerwyt** [envoyproxy/envoy#35679]
Why the HTTP filter will be destructed even when encodeData returns StopIterationAndBuffer?
It might be a bug since a filter should not be destroyed when it's still needed for future processing. 
Could anyone familiar with that provide me with some clues? Thank you so much!

My code is:

```cpp
FilterDataStatus AppnetFilter::encodeData(Buffer::Instance &data, bool end_of_stream) {
    ENVOY_LOG(info, "[Appnet Filter] encodeData not done in one time, req_appnet_blocked_={}", this->req_appnet_blocked_);
    return FilterDataStatus::StopIterationAndBuffer;
}
```

Output
```
[2024-08-12 17:46:48.585][612617][info][filter] [appnet_filter/appnet_filter.cc:163] [Appnet Filter] encodeData not done in one time, req_appnet_blocked_=false
[2024-08-12 17:46:48.587][612617][info][filter] [appnet_filter/appnet_filter.cc:90] [Appnet Filter] ~AppnetFilter
```

**Comment by jokerwyt** [comment]
Let me provide more background:

I am going to send an async HTTP request to an external cache server in `encodeData()`. And I have to wait for the response back. Therefore, I need to stop the filter processing and resume it in the external HTTP response callback (which is implemented as a method of my filter). If the filter is destructed, the callback will be called on a destroyed object, which will cause segmentation fault immediately.

**Comment by adisuissa** [comment]
cc @yanavlasov

**Comment by jokerwyt** [comment]
@adisuissa  @yanavlasov Could you please take a look? I think this is an important issue for those who want to develop things based on HTTP filters. Thanks for your effort!
