### ISSUE TITLE
Does Envoy Redis proxy support Sentinel deployment?

### ISSUE THREAD

**Issue by outsinre** [envoyproxy/envoy#35727]
*Title*: *Redis Sentinel Support*

*Description*:
>I found Envoy Redis proxy support vanilla Redis and Redis Cluster. But when I tried to proxy Sentinel, error is returned:
>
> **unsupported command 'sentinel'**

**Comment by adisuissa** [comment]
Contributions are welcome!

cc @weisisea @mattklein123 as codeowners
