### ISSUE TITLE
In which envoy version was LuaConfig was introduced?

### ISSUE THREAD

**Issue by Mehul-Jaiswal** [envoyproxy/envoy#35733]
*Title*: *In which envoy version was LuaConfig was introduced?*

*Description*:
>in which version of envoy was this introduced: `type.googleapis.com/envoy.extensions.router.cluster_specifiers.lua.v3.LuaConfig`

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by adisuissa** [comment]
IIUC it was added in https://github.com/envoyproxy/envoy/commit/57f23d3092956972f2c23f869280310c7a65ca33.
This was added to Envoy v1.29.0 (see https://github.com/envoyproxy/envoy/blob/56fcd4dcbf05b9f3b53ac8b245adbdf3a59c15a3/changelogs/1.29.0.yaml#L373).

**Comment by Mehul-Jaiswal** [comment]
Thank you, one more question which the most stable version for LuaConfig to use?

**Comment by adisuissa** [comment]
> Thank you, one more question which the most stable version for LuaConfig to use?

I'm assuming the most recent one will be.

> Also how can we add timeouts in this? Need different timeouts based on the header

I guess so, PRs welcome
