### ISSUE TITLE
Extend TLS inspector to capture JA3n and JA4

### ISSUE THREAD

**Issue by kashyap-db** [envoyproxy/envoy#35739]
*Title*: Extend TLS inspector to capture JA3n and JA4

*Description*:
[This issue](https://github.com/envoyproxy/envoy/issues/16622) 3 years ago requested the JA3 feature. JA3 is no longer effective and gets permuted after [Chrome 110](https://github.com/net4people/bbs/issues/220) making it ineffective. Also JA4 has now been released. JA4 is a much more effective way of identifying malicious activity than IP address.

See the [original issue](https://github.com/envoyproxy/envoy/issues/16622) for a detailed motivation for this.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/issues/16622
https://github.com/FoxIO-LLC/ja4
https://github.com/net4people/bbs/issues/220
https://security.stackexchange.com/questions/273101/why-the-ja3-hash-changed-everytime-refresh-the-webpage

**Comment by ggreenway** [comment]
PRs welcome for adding this!

**Comment by agrawroh** [comment]
@ggreenway Should we add a new field called `tls_fingerprinting` alongside `enable_ja3_fingerprinting` [here](https://arc.net/l/quote/gajmujec) and deprecate the latter in favor of the newly added field later. 

JA3/JA4 could be set as an ENUM:
```
tls_fingerprinting: {
  enable: BOOL,
  engine: ENUM { JA3 = DEFAULT, JA3S, JA4}
}
```

**Comment by ggreenway** [comment]
@envoyproxy/api-shepherds can help with how to structure the config. If you're going to use an enum, I think having a default value of `none`, and not having a bool to enable/disable, is simpler.

I'd also be fine with just adding more booleans for `enable_ja3s_fingerprinting` and `enable_ja4_fingerprinting`.

**Comment by kashyap-db** [comment]
Minor clarification JA3s (server fingerprinting) is different from [JA3n](https://tls.browserleaks.com/json) (what we want). JA3n just sorts the  Client Hello SSL Extensions.
