### ISSUE TITLE
Detect Memory leaks in Envoy

### ISSUE THREAD

**Issue by dinesh-murugiah** [envoyproxy/envoy#35741]
Hi 

Title
How to Detect Memory leaks in Envoy

Description
i am trying to expand feature of the Envoy redis proxy to support pubsub and blocking and other admin commands 
thereby it will be closer to features when compared to enterprise solutions 
During this development i am running in to memory leaks , i am yet to write test cases for all the code intrduced 
is there a better/simpler way to detect memory leaks . 

i tried to use it with valgrind , but valgrid seems to report problems in many other libraries linked and i am not able to make it provide reliable output

i tried tcmalloc by enable --config tcmalloc=gperftools , when running the heap profile generated with pprof i am not able to get symbols properly

I have enabled asan in the build statically using following option

bazel build     --config=clang     --config=libc++     -c dbg     --copt=-O0     --strip=never     --copt=-fsanitize=address   --copt=-fno-common     --copt=-fno-sanitize-recover=all     --copt=-g3     --linkopt=-fsanitize=address     --copt=-DADDRESS_SANITIZER=1   --copt=-fno-sanitize=undefined    --linkopt=-fno-sanitize=undefined     --define tcmalloc=disabled 

this also does not seems to provide any output for a know leak(running without fix) which i fixed in later builds

request some guidance in better way to detect memory leak and right configs to enable during builld and steps to collect data

**Comment by adisuissa** [comment]
cc @nezdolik @KBaichoo @jmarantz  who may have some experience in tracking memory leaks

**Comment by jmarantz** [comment]
Usually we get pretty good memory-leak traces from running unit tests with a default build (fastbuild). 

How was it that you discovered you had a memory leak in the first place?

**Comment by KBaichoo** [comment]
+1 on how you found out you had memory leaks.

See also https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html#get--memory for getting some memory stats -- presumably from your leak a graph of these numbers should just be going up, and https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-memoryallocatormanager for configuring the memory allocator manager which might be useful for your usecase.

Note that TCMalloc doesn't give memory back to the OS by default if you're using some OS level metric for monitoring the memory leak in which case the memory allocator manager configuration would be useful.

**Comment by nezdolik** [comment]
I have experience tracking memory leaks (since i create some of them :) ). If you think that a certain piece of code has a memory leak, you could write a test that invokes that codepath and then run a test like this (with --config=clang-asan or  --config=asan depending on your compiler settings):
``` 
bazel test --config=clang-asan //test/extensions/geoip_providers/maxmind:geoip_provider_test  --cache_test_results=no --verbose_failures --jobs=64 --test_output=all --action_env="GTEST_COLOR=1" --test_arg='-l trace' --experimental_ui_max_stdouterr_bytes=101182188 --sandbox_debug --runs_per_test=1
```

**Comment by dinesh-murugiah** [comment]
Hi all
Thanks for all the info shared , please apologise for missing to follow this thread and responding to it
Since we have not written may test cases for the changes we have done on top of existing redis proxy , we were not able to use the Envoys test framework

we prioritised quick prototyping , so we landed in this problem , But we were able to figure out the required bazel build configs to make binaries to test memory leak and sanity using valgrind and ASAN

Valgring build 
bazel build --config=clang --config=libc++ --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++ -c dbg --copt=-O0 --copt=-g3 --copt=-fno-inline --strip=never --define tcmalloc=disabled --define signal_trace=disabled --announce_rc //source/exe:envoy-static

Asan Builds
bazel build --config=clang --config=libc++ --config=clang-asan -c dbg --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++ --strip=never --define tcmalloc=disabled --define signal_trace=disabled --action_env=ENVOY_ASAN=1 --action_env=CC --action_env=CXX --announce_rc //source/exe:envoy-static --subcommands --verbose_failures

with these builds along with external functional automations we were able to catch all memory leaks and crashes , we have introduced more than arround 40+ commands to the Redis proxy

Late Q4 we plan to write Change Review proposals to community to try to upstream the changes

Thanks

**Comment by jmarantz** [comment]
Sounds good. When you get around to writing PRs to upstreaming the changes you'll want to make sure you have coverage for all your new features in unit tests. Thanks!
