### ISSUE TITLE
Support scraping Prometheus metrics from proxied endpoints

### ISSUE THREAD

**Issue by grantr** [envoyproxy/envoy#3575]
## Scenario

I'm using Istio with Envoy on Kubernetes. I use Prometheus to gather metrics from containers in the service mesh. I'd like to autoscale my Kubernetes workloads using a combination of Envoy metrics and custom metrics gathered by Prometheus.

Prometheus turns out to be a poor solution for this problem. Responsive autoscaling requires access to low latency and high frequency usage metrics, but normal Prometheus scraping intervals are too slow for this purpose. Ideally we want metrics with 1-second freshness at 1-second intervals, and Prometheus isn't designed to scrape thousands of pods at these frequencies. A push solution would be more suitable for low-latency metrics, but push metrics inconveniently require configuration in the metrics-producing container (containers must be told where to push their own metrics and how to connect securely).

Envoy provides push metrics (the gRPC metrics protocol or statsd) that would be perfect for responsive autoscaling, but can only emit its own metrics through this mechanism. I need to autoscale based on custom metrics produced by the container also.

## Suggested solution

Today we can use Envoy to gather health checks from proxied endpoints, but we need a separate scraping system such as Prometheus to gather metrics directly from those endpoints.

It would be convenient if Envoy could gather metrics from a scrape endpoint in standard Prometheus format, store those metrics using its existing stats storage primitives, and integrate them into whatever stats delivery mechanism is configured (metrics server, statsd, or Prometheus scrape endpoint).

Ideally the code for this feature could be shared with Envoy's existing health checking code.

Envoy's configuration could be extended to define the scrape path, scrape interval, and a list of metric name globs (or regexes) for an endpoint. I expect this configuration would be similar to the existing health check configuration.

**Envoy would not be expected to persist metrics to permanent storage.** Envoy should only implement metrics collection and forwarding. A separate metrics storage system would collect from Envoy if persistent metrics storage is desired.

## Benefits of this feature

Containers can expose stats in standard Prometheus format without requiring any configuration or awareness of the metrics collection mechanisms used by the system. It's easier for Envoy to scrape these endpoints at high frequencies than Prometheus due to the lower number of endpoints managed per Envoy instance (in my Istio scenario, one endpoint per instance), Envoy's lack of persistent storage, and Envoy's high-performance architecture.

Metrics storage systems and other consumers can use the single Envoy stats provider to gather all service mesh metrics, including Envoy-generated and workload-generated metrics.

Metrics collection configuration can be controlled entirely by the service mesh operator (via Envoy configuration) without requiring cooperation from the workload author. This uniform control simplifies the operator's task of configuring metrics consumers.

**Comment by mattklein123** [comment]
@grantr this is an interesting idea. I've marked this issue "design proposal" since I think if we want to go this direction we should have a full design doc. If you feel like doing that doc, go for it.
