### ISSUE TITLE
Upstream health checks threading model

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#35773]
I tried looking it up in docs, but didn't find (please help referring if it exist): Are Envoy upstream health checks performed per-worker, or are they running globally from the main thread, and results are posted to workers?
I'd assume the latter, but wanted to make sure

**Comment by botengyao** [comment]
Yes, health checks are performed on the main thread, and then posted to the thread local configs.

**Comment by botengyao** [comment]
@ohadvano no sure, but feel free to add any docs. Thanks!
