### ISSUE TITLE
Add User-Agent to jwks http requests

### ISSUE THREAD

**Issue by yerkulees** [envoyproxy/envoy#35785]
*Title*: Add User-Agent to jwks http requests

*Description*:
Requests to get the jwks url fail because the requests lack a user-agent header. This is a requirement from the IDP. I'm currently using Envoy Gateway in EKS. 

The below request fails, I'd like to add a user-agent to get that working.

```
[2024-08-21 22:46:23.522][1][debug][router] [source/common/router/router.cc:750] [Tags: "ConnectionId":"0","StreamId":"17207847609171885090"] router decoding headers:
':path', '/path/oauth/jwks'
':authority', 'auth.url.dev'
':method', 'GET'
':scheme', 'http'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.100.4.34'
'x-envoy-expected-rq-timeout-ms', '10000'
```

**Comment by KBaichoo** [comment]
cc @tyxia as code owner

**Comment by Athishpranav2003** [comment]
I guess I can work on this issue

**Comment by Athishpranav2003** [comment]
Incase of programs what should we mention in the UA string? Some generic browser UA string or the go library we are using?

**Comment by tyxia** [comment]
@Athishpranav2003 I think it is still open. Your help/contribution would be appreciated. Thanks!

**Comment by Athishpranav2003** [comment]
I will work on it this week ✌️

**Comment by Athishpranav2003** [comment]
@KBaichoo @tyxia could you guys please check this. I am not sure how i can test it.
