### ISSUE TITLE
1.31 docs missing warning about envoy.filters.http.upstream_codec

### ISSUE THREAD

**Issue by shulin-sq** [envoyproxy/envoy#35816]
*Title*: *1.31 docs missing warning about envoy.filters.http.upstream_codec*

*Description*:

in 1.31 you must configure upstream_codec with a type_config

```
-          "name": "envoy.filters.http.upstream_codec"
+          "name": "envoy.filters.http.upstream_codec",
+          "typed_config": {
+            "@type": "type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec"
+          }
```

likely after this commit https://github.com/envoyproxy/envoy/commit/c1123b5c064e1d99f44c7359469805326b9f811f

but it was not called out in https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.31/v1.31.0

it's an easy fix but just wanted to note it somewhere if anyone else runs into this. I'm not sure if 1.31 docs can be updated at this point?

**Comment by phlax** [comment]
hi - the 1.31.0 docs cant be updated - but we can update them for the next 1.31 patch release

probably we missed the boat adding a changelog but i think we should add something to the upstream_codec documentation
