### ISSUE TITLE
Add ppc64le and s390x support for Binaries/Images for envoy-openssl

### ISSUE THREAD

**Issue by Swapnali911** [envoyproxy/envoy#35825]
Reference #[221](https://github.com/envoyproxy/envoy-openssl/issues/221)

**Request:**
Please add P&Z binaries/images to the releases page at https://github.com/envoyproxy/envoy-openssl/releases alongside x86 binaries.

**Benefit:**
Including P&Z binaries/images will improve accessibility for users on these platforms and ensure better support for a wider range of architectures.

**Dependency :** https://github.com/knative/infra/issues/344

Creating issue under envoy to get help/inputs from envoy community

cc : @rishikakedia @valen-mascarenhas14 @dilipgb

**Comment by phlax** [comment]
@Swapnali911 im afraid i have no idea what "P&Z" refers to - can you elaborate?

**Comment by Swapnali911** [comment]
@phlax here P&Z refer to IBM ppc64le and s390x platforms. Sorry for the confusion.

**Comment by phlax** [comment]
k - so iiuc this relates to s390x binaries

Envoy as a project doesnt support s390x so we are unlikely to add release binaries for this format.

We are however willing to accomodate and help where we can with downstream projects - so i would suggest setting up a downstream to handle these releases

cc @namrata-ibm

**Comment by phlax** [comment]
also realizing these require openssl support so would be downstream of that project also cc @tedjpoole  @jwendell

**Comment by Swapnali911** [comment]
Looks like https://github.com/knative/infra/issues/344 is closed and they have moved to the downstream. So this requirement no longer required. Hence closing the issue.
 
Thanks @phlax  for your inputs
