### ISSUE TITLE
high latencies in grpc requests when going through envoy

### ISSUE THREAD

**Issue by robertlemmen** [envoyproxy/envoy#3583]
Hi everyone,

we have a GRPC client and server service as part of our system, hosted on google cloud kubernetes. Between these two are a ingress controller using contour and envoy, and an esp. In our production system, we are observing high latency intervals that come an go. we removed the esp but that did not make a big difference, but when bypassing the envoy proxy, latencies immediately improve. Other interesting bits are that the latencies seem to correlate with the request load, although the envoys are pretty idle and the actual traffic is relatively low (~20rq/s). It also seems that a restart of the client service helps for a while, but after 30min to one hour the problem re-surfaces. It also appears that sometimes there is a 5min "comb" structure in the latency pattern

Please see the two attached plots, one is with the envoy proxy, one is bypassing it. "maba" refers to the client service and "maus" to the server. Please ignore the red lines, this was an attempt to extract data directly frmo envoy logs that didn't work so well. The solid line on the second page is the 99 percentile. Notice how well the "maba" latencies envelop the "maus" latencies in the "good" case, and how disassociated they are when going through envoy?

[leaks-all-over-the-place-and-5min-spikes.pdf](https://github.com/envoyproxy/envoy/files/2088955/leaks-all-over-the-place-and-5min-spikes.pdf)
[no-envoy-no-esp-good.pdf](https://github.com/envoyproxy/envoy/files/2088956/no-envoy-no-esp-good.pdf)

I appreciate that this issue does not have enough information, but it's a complicated setup and I don't really know where to start. please let me know what further information is required to investigate and resolve this.

**Comment by lizan** [comment]
What is your median latency in both case (not 99 percentile, see below). And if it is possible, can you provide your Envoy config and stats/log (See [here](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md) for how to collect)? What is the latency graph you see in Google Cloud Console in Endpoints section?

>  It also appears that sometimes there is a 5min "comb" structure in the latency pattern.

The high latency every 5 mins is likely from ESP, which check your API call against [Google Service Control](https://cloud.google.com/service-control/overview) and caches the result for [5 minutes](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/service_control/aggregated.cc#L55) by default. Though there are only few calls with high latency, in the low throughput (~20rq/s) scenario, it will push 99 percentile latency significantly.

**Comment by robertlemmen** [comment]
hi lizan, thanks for getting back to me! I am currently setting up a test system in which I can experiment better. I'll get back with more results from that, as well as the envoy config/stats.

In the meantime: the median latencies are in the 100ms range, but we are really interested in the upper end of the quantile range to make our system more predictable. I also suspect the ESP as the source of the 5min comb structure, but note that we are seeing the same problems even when we bypass the esp from envoy/ingress. An example is the attached, which also shows another curiosity: the problem appears and disappears quite randomly and suddenly.
[no-esp.pdf](https://github.com/envoyproxy/envoy/files/2101260/no-esp.pdf)
