### ISSUE TITLE
repo layout: singular vs plural naming

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#3584]
Seems ecently (after 1.6.0) we introduced some naming inconsistency in Envoy API for extensions.

In API, everything is singular except [`grpc_credentials`](https://github.com/envoyproxy/envoy/tree/master/api/envoy/config/grpc_credentials/), but in `{source,test}/extensions` everything is plural.

My suggestion is we can make at least rename `api/config/grpc_credentials` to singular as it is only v2alpha, and then potentially (optionally) rename extensions in `{source,test}/extensions` to singular. It's impossible to make Extensions API plural as packages like `api.config.filter` is frozen.

Then we should make a note in STYLE.md or REPO_LAYOUT.md.

Thoughts? @mattklein123

**Comment by mattklein123** [comment]
Personally, I would just rename `grpc_credentials to singular in API to be consistent and leave the source code as is, since I don't think it's worth the churn, but I don't feel that strongly about it.

**Comment by lizan** [comment]
Initially I thought it might make CODEOWNERS file simpler for new extensions, but it looks hard so I don't feel strongly either for renaming {source,test}/extensions.
