### ISSUE TITLE
No response code details in upstream_log access logs for each attempt to upstream

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#35871]
*Title*: *No response code details in upstream_log access logs for each attempt to upstream*

*Description*:
>We have configured upstream_log in envoy.filters.http.router filter. We wanted to log each failed attempt to upstream to find out what is the reason for failure. 
But we see that when upstream cluster responds with 5xx error, the upstream_log prints empty values for some of the fields like: 
response_code_details: null
retry_count: 0

In 2 upstream request attempts it gives above values in both log entries.

Envoy prints 5xx response_code though in upstream log. 
And the envoy.filters.network.http_connection_manager filter level access logs prints below values:
response_code_details: via_upstream
retry_count: 2

We would like to have these 2 fields in upstream logs as well As it provided useful info while debugging any issue with upstream cluster.

So, Is this an expected behavior or a bug in upstream_log implementation?

(see our access log config below)

*Repro steps*:
> Tested with envoy version 1.30.4 with below config for upstream_log.

*Admin and Stats Output*:

*Config*:
   
```name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          dynamic_stats: true
          start_child_span: true
          suppress_envoy_headers: false
          upstream_log:
          - name: envoy.access_loggers.file
            filter:
              or_filter:
                filters:
                  - status_code_filter:
                      comparison:
                        op: GE
                        value:
                          default_value: 500
                          runtime_key: access_log.access_error.status
                  - status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 0
                          runtime_key: access_log.access_error.status
                  - traceable_filter: {}
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
              log_format:
                formatters:
                - name: envoy.formatter.req_without_query
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.formatter.req_without_query.v3.ReqWithoutQuery
                json_format:
                  type: "upstream_log"
                  response_code: "%RESPONSE_CODE%"
                  response_code_details: "%RESPONSE_CODE_DETAILS%"
                  connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%"
                  response_flags: "%RESPONSE_FLAGS%"
                  upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                  upstream_remote_address: "%UPSTREAM_REMOTE_ADDRESS%"
                  x_request_id: "%REQ(X-REQUEST-ID)%"
                  upstream_cluster: "%UPSTREAM_CLUSTER%"
                  retry_count: "%UPSTREAM_REQUEST_ATTEMPT_COUNT%"```
 
*Logs*:
>Include the access logs and the Envoy logs.

**Comment by ggreenway** [comment]
`UPSTREAM_REQUEST_ATTEMPT_COUNT` is only valid on the downstream request and can be logged there. 

For `RESPONSE_CODE_DETAILS`, as you can see from the docs, they're referring to the details about the response code sent back to the downstream client, so that is also only applicable on downstream access logs.

> HTTP response code details provides additional information about the response code, such as who set it (the upstream or envoy) and why.

So you probably need to configure both downstream and upstream logs, and you can link them by request id or `%STREAM_ID%`.

**Comment by VishalDamgude** [comment]
Thanks @ggreenway for clarifying.
