### ISSUE TITLE
quic test flaky

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#35928]
https://dev.azure.com/cncf/envoy/_build/results?buildId=178965&view=logs&jobId=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&j=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&t=b9aeef91-fdf0-5be6-08f0-d544c00fc771

**Comment by phlax** [comment]
another failure here https://dev.azure.com/cncf/envoy/_build/results?buildId=179065&view=logs&j=76424b50-4542-51d2-ddfa-1b282263c744&t=ee414bb6-1c71-528f-760c-893708054276&l=3205

**Comment by phlax** [comment]
and another https://dev.azure.com/cncf/envoy/_build/results?buildId=179091&view=logs&j=b6a93b2f-c9eb-5004-2b80-f11f3e41d6df&t=b9aeef91-fdf0-5be6-08f0-d544c00fc771&l=2184

@RyanTheOptimist this is happening very frequently - wondering who to ask to look at the issue

**Comment by RyanTheOptimist** [comment]
@danzh2010 can you take a look?
