### ISSUE TITLE
Mobile iOS tests are ~permafailing

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#35944]
these tests seem to have failed on almost all of the last few postsubmit runs

i see it failing very frequently in PRs also

**Comment by phlax** [comment]
cc @fredyw

**Comment by fredyw** [comment]
Looking at https://github.com/envoyproxy/envoy/actions/workflows/mobile-ios_tests.yml, it seems to be quite fine. There were a couple of failures, but overall it's looking good. There was an issue with the S3 token expiration last week, but that got fixed by the EngFlow team.

**Comment by phlax** [comment]
see here https://github.com/envoyproxy/envoy/commits/main/

its more/less a permafail on `main` (where it is always tested, and not skipped)

**Comment by phlax** [comment]
but personally im retesting this very often on PRs

**Comment by fredyw** [comment]
Looking at the test failures, they were all mostly timeout tests, which I suspect is a similar issue we had last time with the networking when running on EngFlow remote execution. I think it might be happening again.
