### ISSUE TITLE
Dynamically replace the ADS (xDS) server

### ISSUE THREAD

**Issue by adisuissa** [envoyproxy/envoy#35956]
*Dynamically replace the ADS (xDS) server*

*Description*:
In a given deployment there may be a need to dynamically modify and change the ADS (xDS) server that Envoy connects to.
This is useful, for example, in cases where the xDS management server needs to go offline due to some maintainence.
Currently, it is impossible to dynamically modify the server, as the configuration is only provided in the bootstrap config, and only read once.

We suggest adding a `setAdsConfigSource(const envoy::config::core::v3::ApiConfigSource& config_source)` method to the Envoy's instance, that allows to dynamically set the ADS configuration to be used.
If the config is valid, Envoy will disconnect from the current ADS server, and create a connection as described in the given config-source. The rest of the xDS-protocol will work just as if Envoy was resuming its connection to the originally configured server after disconnecting from it.

As a first step, this will only support changing to an xDS-server of the same type (i.e., keeping the mode to either SotW or Delta-xDS). In the future this can be relaxed.

**Comment by ramaraochavali** [comment]
> We suggest adding a setAdsConfigSource(const envoy::config::core::v3::ApiConfigSource& config_source) method to the Envoy's instance, that allows to dynamically set the ADS configuration to be used.

Curious, what is the workflow to call this method when there is a desire to switch?

**Comment by adisuissa** [comment]
> Curious, what is the workflow to call this method when there is a desire to switch?

The current design requires access to the Envoy's [Server-Instance](https://github.com/envoyproxy/envoy/blob/main/envoy/server/instance.h). It will be somewhat similar to the way the [xDS-context](https://github.com/envoyproxy/envoy/blob/c85c065660e76c768aa318906aff622dd3e87761/envoy/local_info/local_info.h#L54) can be updated.
It can be invoked in cases where Envoy is used as a library in a process.
