### ISSUE TITLE
Can I import an proto which would be used in the function decodeData of a http filter

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#35965]
I'm developing a custom http filter, which will do some process with a defined message from a proto file. Here is some detail:

```
syntax = "proto3";

package pkg;

message UserInfo {
    int64 uid = 1;
    string name = 2;
}
```

When a http request is passing my custom http filter, I will fetch some info from the http body and generate a `UserInfo` object and do some other things.

So basically I need two things:
1. How to compile the proto file while compiling the Envoy so that I can use the relative `.h` and `.cc` immediately in the function `decodeData` of the custom http filter?
2. I need to use some protobuf functions in the function `decodeData`, how to include the relative protobuf headers in the `cc` file of the custom http filter? Can I include immediately `#include <google/protobuf/io/zero_copy_stream_impl.h>`?

**Comment by phlax** [comment]
@YvesZHI to make headers or sources available to your code you need to add them as deps in the relevant `BUILD` file

to include the protobuf headers you need to do similar - see https://github.com/envoyproxy/envoy/blob/main/source/common/protobuf/BUILD for how Envoy brings these in - you either need to do the same or dep on the targets there
