### ISSUE TITLE
Backport of bypass overload manager flag to envoy 1.29

### ISSUE THREAD

**Issue by singamL887** [envoyproxy/envoy#35985]
*Title*: *One line description*
Backport of bypass_overload_manager flag to envoy 1.29

*Description*:
bypass_overload_manager flag bypasses probes from overload manager stop_accepting_connections/requests actions when envoy reached the configured heap limit. 

https://github.com/briansonnenberg/envoy/commit/96a43c3fbd35ed3e2e1d9bb4e06ce054dd4c3bf8

Backporting it to the envoy v1.29

[optional *Relevant Links*:]

https://github.com/envoyproxy/envoy/issues/23843

**Comment by phlax** [comment]
cc @nezdolik 

@singamL887 if you raise a PR im happy to review it

**Comment by cancecen** [comment]
I created a PR for this since I am the author of the change in main.

**Comment by nezdolik** [comment]
@cancecen you are creating backport because is not possible to upgrade to latest version (where this feature is included)?

**Comment by cancecen** [comment]
@nezdolik I am not sure - I am not working with the author of this issue, I just wanted to address this since I am the author of the original PR.

**Comment by cancecen** [comment]
It's not really a fix - it's an enhancement on the existing overload manager functionality. Let me know how you want to proceed here, I can close my backport PR (linked above).

**Comment by phlax** [comment]
> It's not really a fix - it's an enhancement 

tbh, then i think its not covered by our support/stable branches policy, and best way forward is to close
