### ISSUE TITLE
Help needed to get started extending envoy L7 protocol with MQTT and also its WASM capabilities

### ISSUE THREAD

**Issue by algermissen** [envoyproxy/envoy#36006]
*Title*: *Help needed to get started extending envoy WASM capabilities*

*Description*: I am planning to extend envoy to proxy MQTT at layer 7 (similar to how HTTP is proxied) and not just at layer 4. Once I have that in place, I want to implement MQTT-Request and -Response filter capabilities for WASM so that I can chain WASM filters for MQTT Requests and responses.

Can someone help me and share references / issues / or any other pointers that help me get started?

For example, I found this #35420 and wonder if that discussion provides the latest state of the whole WASM integration?

Also, which existing integration is the best to look at / use as basis to implement MQTT requests and responses so that I have onMqttRequest(...)  abd onMqttResponse(...) handler functions?

Any help would gladly be appreciated.

I am also happy to contribute the source code back to the code base if accepted.

**Comment by phlax** [comment]
cc @mpwarres @lizan

@algermissen might be worth asking on Envoy slack
