### ISSUE TITLE
GoLang filter stabilization question

### ISSUE THREAD

**Issue by Daniel-Eisenberg** [envoyproxy/envoy#36026]
Hi all,

I saw in your documentation that "The Go plugin API is not yet stable", I wanted to ask what is missing for that filter to be stable and if there is a known timeline for the required changes.

Thanks!

**Comment by doujiang24** [comment]
The Go plugin API in 1.31.0 is stable enough, there are no known required breaking changes now.
And it may only need some small tweaks even when there is a breaking change.

There is a issue https://github.com/envoyproxy/envoy/issues/31685, the main remaing work should be doc.

**Comment by ravenblackx** [comment]
(Closing because the question is answered, and I think if there's more to be said it should probably be on the linked tracking issue.)

**Comment by Daniel-Eisenberg** [comment]
Thank you for the reponse!

**Comment by denniskniep** [comment]
@doujiang24 will the golang filter then be moved to core-image ?
Currently its still in the [contrib-image](https://www.envoyproxy.io/docs/envoy/v1.31.0/start/install#install-contrib) as far as I know
