### ISSUE TITLE
[Question] How should i write LDS name via a gRPC request

### ISSUE THREAD

**Issue by Skylark-hjyp** [envoyproxy/envoy#36042]
*Title*: *How should i write LDS name via a gRPC request*

*Description*:
Hey,  
If i want to retrieve a specific LDS (Listener Discovery Service) resource via a gRPC request, how should i write the LDS resource name? Assuming my service name is "echo" and the port is 50010.

I try `echo:50010`，but receive null.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ravenblackx** [comment]
@adisuissa or @lambdai might be able to answer.
