### ISSUE TITLE
Question: Why is `use_refresh_token` is disabled by default in oauth2 filter?

### ISSUE THREAD

**Issue by kanurag94** [envoyproxy/envoy#36045]
*Title*: *Why is `use_refresh_token` [disabled by default in oauth2 filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#envoy-v3-api-field-extensions-filters-http-oauth2-v3-oauth2config-use-refresh-token)?*

*Description*:
> Most of the oauth/ oidc provider have an option to select if refresh token should be sent in the response. With the `use_refresh_token` option, we have a way to disable using refresh token, however if the same is not sent in response there is no need to generally disable it. We could keep the default behavior of this flag to be `true` by default.

I wished to understand, apart from unknowingly using the refresh token and thus a security implication, what are the reasons to not have it enabled by default?

**Comment by kanurag94** [comment]
cc @Alexcei88

**Comment by ravenblackx** [comment]
I would guess the two most likely reasons are:
1. bool automatically defaults to false and if you want to change that behavior you have to wrap the field and write a bunch of extra code and it's a pain (and we dislike negative-named fields because e.g. `!disable_whatever` is easy to misread)
2. if the field and behavior didn't exist in the first version of the filter, we tend to make the default match the old behavior for the sake of backwards compatibility even when it makes the config frustrating to use.

@derekargueta to comment with actual knowledge rather than guesses.

**Comment by Alexcei88** [comment]
@ravenblackx , @kanurag94  second statement is right.

> I would guess the two most likely reasons are:
> 
> 1. bool automatically defaults to false and if you want to change that behavior you have to wrap the field and write a bunch of extra code and it's a pain (and we dislike negative-named fields because e.g. `!disable_whatever` is easy to misread)
> 2. if the field and behavior didn't exist in the first version of the filter, we tend to make the default match the old behavior for the sake of backwards compatibility even when it makes the config frustrating to use.
> 
> @derekargueta to comment with actual knowledge rather than guesses.

the second statement is right. It was made to support the old behaviour. I think the refresh token feature is already pretty stability and we can turn on by default. The changes will be required minimal.

**Comment by kanurag94** [comment]
Thanks @ravenblackx and @Alexcei88 

I agree we can enable it by default which is closer to general oauth plugins behavior.
May you please let me know if you are going to take up the changes or I can open a PR for review.

**Comment by Alexcei88** [comment]
I would be happy, if you create PR. I will take a look.

**Comment by kanurag94** [comment]
@wbpcode may you please help me reopen this issue and connected PR https://github.com/envoyproxy/envoy/pull/36065

**Comment by ngorantla-equinix** [comment]
@Alexcei88 We're using OAuth2 filter at L7 layer for Authentication purpose, we wanted to extend the user session using a refresh_token, we have a bunch of asynchronous Ajax calls they all try to get new accessToken using refresh_token, but only first one is successful.
This case cookie is not updated with new value comes from successful token call.
