### ISSUE TITLE
Outbound rate limiting in requests per second per domain + queue management?

### ISSUE THREAD

**Issue by bern548456** [envoyproxy/envoy#36076]
Hello,

I'm trying to use Envoy proxy in forward proxy mode for HTTP and HTTPS requests.
I'm looking for a way to set a rate limit in terms of requests per seconds per domain (without knowing the visited domains in advance).
Envoy proxy can restrict requests with a local or a global rate limiter which is great!
However, I'd like to process all requests instead of rejecting requests exceeding the rate limit for a given domain (which Envoy does not seem to provide). I also would like to preserve the requests order.

Sadly, to my knowledge Envoy does not support queuing of requests. 
How could I do this ? Any input would be appreciated.  

Best regards

**Comment by ravenblackx** [comment]
I suspect the answer for this might be you'd need to make a custom filter for it - my company has a queue filter like what you need internally but it uses our own system for metrics so is unfortunately not suitable for simply pushing into `contrib`. The fact that we have that custom filter leads me to suspect that there isn't a readily available pre-existing way to do it, though the filter is quite old so it's possible another option has been added since that filter was created.

@alyssawilk to confirm/deny that adding a new filter is probably the only way to achieve that.

**Comment by bern548456** [comment]
Thanks for your quick response and feedback. I will definitely consider creating a custom filter, perhaps extending the existing local rate limit filter, to get off to a good start.

I'm still hesitating between using a separte component (e.g.: redis) to store queues and rate limiting info (to avoid local memory exhaustion), or doing everything locally (for ease of use and better performances). But since there would only be a unique proxy instance (even if it's multi-threaded), I'd be inclined to go for the local in-memory option (and not the redis one) - ok, that would require synchronization and thread-safe mechanisms.

One of the difficulties is that the number of visited domains and requests sent per domain can quickly use too much memory. This is why I would consider using a global rate limiter (for all incoming requests and domains) that would help restrict the growth of each domain's queue if necessary. And yes, each domain would still have its own rate limiter. Perhaps this (the global rate limiter) could be adjusted at runtime, as a backpressure mechanism. I don't want to process all requests as quickly as possible but rather find a compromise.

All in all, I'm well aware this could be complex to implement which is why I'm still thinking about it ;).

**Comment by alyssawilk** [comment]
I agree with Raven I don't think you can do this in Envoy today.  Arguably if you use the dynamic forward proxy module, you might be able to do something close to this taking advantage of various connection and stream limits, but I don't think there's per-host controls anywhere else.  I think it would be generically useful so fine to add to existing rate limit filters if you can overcome the design challenges you thoughtfully call out.
