### ISSUE TITLE
Should getLastAddressFromXFF() handle comma-separated lists without spaces too?

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3607]
I just bumped into https://github.com/envoyproxy/envoy/pull/3587/commits/035a8168e45e0cafc2c6b4c8701b47c283139fff where `Utility::appendXff()` went from generating `x-forwarded-for` with a comma plus a space as the separator, to just a comma (no spaces).

Does that mean that `Utility::getLastAddressFromXFF()` needs to handle both types of separators (with and without spaces)? The IP tagging module certainly breaks when there's no space after the comma...

Happy to send a PR if the desired behavior is to handle both cases (I am looking up what's actually valid for XFF values...). 

@mattklein123, @alyssawilk thoughts?

**Comment by rgs1** [comment]
Looks like both cases (space and no space) are valid in HTTP lists:

https://tools.ietf.org/html/rfc7239#section-7.1

**Comment by mattklein123** [comment]
Ugh. Yes, we definitely need to handle both cases. cc @danielhochman this might require another rollback. We might want to just revert https://github.com/envoyproxy/envoy/commit/035a8168e45e0cafc2c6b4c8701b47c283139fff while we sort this out.

**Comment by rgs1** [comment]
@mattklein123 something like https://github.com/envoyproxy/envoy/pull/3610 perhaps?
