### ISSUE TITLE
Support building on MacOS aarch64 devcontainer

### ISSUE THREAD

**Issue by DieBauer** [envoyproxy/envoy#36088]
Building Envoy on MacOS M1/2/3 fails with the bazel toolchain not supporting the aarch64 target in Devcontainers. 

I'm opening this issue here, to track progress.

> the issue here is actually the cc toolchain, i think we need to define a aarch64 version over here to start https://github.com/envoyproxy/envoy-build-tools/blob/main/toolchains/configs/linux/clang/cc/BUILD
> im not going to dig into this one anymore right now though

_Originally posted by @keith in https://github.com/envoyproxy/envoy/issues/23239#issuecomment-1332783412_

**Comment by zirain** [comment]
FYI: https://github.com/envoyproxy/envoy/issues/23239#issuecomment-2089609237
