### ISSUE TITLE
Clarify how resource hint updates work in xDS protocol

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#3617]
We're running into some problems where Envoy might not receive endpoints for a new cluster added in CDS. We're using java-control-plane for our xDS server.

The issue seems to be the following:

If we add a new cluster (and therefore update CDS and EDS), we save a new xDS snapshot into java-control-plane's cache, which triggers all of the relevant xDS responses. There's a race here between the EDS response and CDS response.

In the happy case, the CDS response is sent first, and Envoy sends a new EDS request with updated resource hints to request the endpoints for the new cluster. Then, the control plane responds with all of the endpoints based on the new set of resource hints.

However, what commonly happens is that an EDS response is sent by the control plane before Envoy has a chance to update the resource hints, so we end up in a state where Envoy knows about the new cluster, has sent updated EDS resource hints, but doesn't get the endpoints for the new cluster and java-control-plane won't respond because the version in the DiscoveryRequest matches the server version.

The xDS docs touch on the subject of updating resource hints here: https://github.com/envoyproxy/envoy/blob/master/api/XDS_PROTOCOL.md#resource-updates. In particular this sentence:
```
For example, if Envoy is at EDS version X and knows only about cluster foo, but then receives a CDS update and learns about bar in addition, it may issue an additional DiscoveryRequest for X with {foo,bar} as resource_names.
```
To me that implies that the management server can and should send multiple responses for the same version X if it notices that the resource hints have changed, but it isn't exactly spelled out. We're also unsure if Envoy will properly handle getting multiple responses with the same version, does it look in the response for new resources even if the version is repeated?

**Comment by mattklein123** [comment]
@htuch @nt thoughts here?

**Comment by htuch** [comment]
Yeah, I see the race here. The management server could just reply to the EDS request that happens following CDS, even though it has already responded. Envoy should do the right thing here, the first response at version X would have been ignored (it didn't know about the cluster), the second response (still at version X) will then be processed. The unknown resources in the first response will have been discarded by Envoy, so they don't factor into the processing of the second response.
