### ISSUE TITLE
contrib: go version should be upgraded to 1.22, not the latest 1.23

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#36246]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: contrib: go version should be upgraded to 1.22, not the latest 1.23

*Description*:
>Describe the issue.

Since https://github.com/envoyproxy/envoy/commit/52bd9ba77afd457ebe83e36f8612159cfefbb05f#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6, the minimal Go version requirement is upgraded to 1.23, due to the Go's release policy:

> Each major Go release is supported until there are two newer major releases.

The two latest major Go releases are 1.23 and 1.22.

I guess that commit wants to use the latest Go release directly. However, 1.23 was released on 2024-08-13, just a month ago. Not every big Go project has been switched to this version. For instance, Istio is still using Go 1.22: https://github.com/istio/istio/blob/d0874414804e8842e8341c7d9c7eee74440cba7a/go.mod#L3. For projects that are already using Go 1.23, they haven't used it for a long time. For instance, k8s just upgraded to Go 1.23 a week ago: https://github.com/kubernetes/kubernetes/commit/65ef53139012dee36c08f558604dea48af170e11.

 It's risky to force the user of Envoy Go to use an edge version as the minimal version. For example, we (the Ant Group Inc.) have a project called HTNN(https://github.com/mosn/htnn) that depends on the envoy Go module. If we upgrade to a Go version released just a month ago, we might be challenged by the aggressive adoption.

Hence I recommend upgrading the Go version to 1.22, which both satisfies the Go's release policy and doesn't affect the adoption of Envoy Golang filter.

CC @veggiemonk 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by veggiemonk** [comment]
Hi @spacewander, thank you for letting me know. 

I had no reason to choose 1.22 over 1.23 but I think it makes sense to revert to 1.22. 
Before opening a PR, I asked about it slack `envoy-go` channel. @doujiang24 gave me the 👍 so I did.
I mainly wanted to upgrade the Go version in the tests as some of them were still on 1.18. 

By the way, `htnn` seems like a cool project :)
