### ISSUE TITLE
Add per-verb local rate limiter

### ISSUE THREAD

**Issue by leosarra** [envoyproxy/envoy#36254]
*Title*: Add per-verb local rate limiter

*Description*:
Currently, Envoy's [local rate limit filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-local-ratelimit-v3-localratelimit) applies limits uniformly across all HTTP methods for a given route or virtual host.
However, while playing around with this feature internally we realized that different HTTP verbs may require different rate limiting policies. For example:

GET requests might be allowed at a higher rate than POST requests
PUT and DELETE requests might need stricter rate limiting than GET requests
Some verbs might not require rate limiting at all

It would be great if the existing local rate limiter is enhanced to set some per-verb limits, with this enhancement we could provide users with more fine-grained control over their traffic management.
Do you feel this is something that makes sense and that is feasible?

**Comment by zuercher** [comment]
cc @wbpcode

**Comment by wbpcode** [comment]
I think you could be achieved by the `header_value_match` (method will be tread as header `:method`) in the `RateLimit`. Note the local rate limit also supports the rate limit descriptor, get more detail from https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-local-ratelimit-v3-localratelimit
