### ISSUE TITLE
health: busy main thread makes health check timer inaccurate

### ISSUE THREAD

**Issue by liulanyi** [envoyproxy/envoy#36295]
In my environment, configuration volume is quite large (about 100M), sometimes I see it takes main thread about 10s to process the configuration. Also stats calculation seems also very heavy, takes about 5s.  This seems make the health check timer inaccurate and not work as expect.

I feel like health check is quite important, is it possible to move health check in another thread?

**Comment by jmarantz** [comment]
I think health-checks do not run on the main thread. See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking-filter .

You have to configure the health-checking filter. The health check *overrides* (`/healthcheck/fail` and `/healthcheck/ok`) run on the main thread but those are not the health checks.

**Comment by jmarantz** [comment]
You might be thinking of the admin `/ready` endpoint? I guess that can't be used for health-checking for the reasons you describe; it's OK to use that to wait until a new server is serving.

Assigning back to reporter for clarification.
