### ISSUE TITLE
Envoy default fallback route

### ISSUE THREAD

**Issue by idomic** [envoyproxy/envoy#36303]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
As title, I'm using the URL for service matching, and I'd like to have a default fallback if no service was matched. I couldn't figure from the documentation how to achieve this easily.

So if I have serviceA and it exist it'll route to serviceA, if it doesn't exist, it'll route to an existing URL/static page.

Right now whenever the service doesn't exists it simply returns a 404.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by jmarantz** [comment]
Does https://stackoverflow.com/questions/58894457/how-to-configure-fallbacks-in-envoyproxy help?
