### ISSUE TITLE
Feature request: support TCP keepalive for downstream sockets

### ISSUE THREAD

**Issue by ikatson** [envoyproxy/envoy#3634]
We use AWS NLB in front of envoy, and it has a 350s idle timeout.
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout

If the client makes a HTTP/1.1 keep-alive connection to that NLB, sends a request and then sends another one > 350s later, the client will get a connection reset.

We expose that to the internet, so we don't control the clients. However, it looks like envoy's listener could set SO_KEEPALIVE on accepted sockets, so that we can then tune the kernel to send those keepalives more frequently than 350 seconds, and the connection will keep working even if it's idle.

Edit: looks like on linux you can set keepalive parameters like TCP_KEEPCNT, TCP_KEEPIDLE, TCP_KEEPINTVL, in which case you won't need to alter the kernel settings, if envoy supports configuring these.

**Comment by mattklein123** [comment]
@ggreenway I had thought we already implemented this for listeners, but it looks like only upstream clusters right now. Is that right?

**Comment by ggreenway** [comment]
It's on my TODO list to implement for listeners. Someone else implemented it for upstreams already. The needed work is to create the config, and then pipe it through to the existing code for setting the correct sockopt.

**Comment by ikatson** [comment]
Just FYI, we hard-coded some setsockopt() calls into our envoy fork, and it solved the NLB connection reset problem.

**Comment by lwhile** [comment]
@ggreenway  @mattklein123 

Does the feature included in the version v1.7.0?

**Comment by ggreenway** [comment]
@lwhile To my knowledge this hasn't been implemented yet. However, generic socket option support was added. On a Listener, you can set socket_options. You'll have to figure out the kernel socket option numbers and exact values, but I think it will work. See https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/lds.proto.

**Comment by ikatson** [comment]
@ggreenway are the socket options set only on listening socket or also on accept'ed ones? Cause what's needed here is the latter

**Comment by ggreenway** [comment]
I don't know off the top of my head.

**Comment by skyrocknroll** [comment]
We are bitten by this.

**Comment by adinunzio84** [comment]
I think we ran into this too while running Istio on AKS:
kubernetes/client-go#527

**Comment by lychung83** [comment]
Setting socket option for listener actually works. Assuming unix-like environment, configuration looks like follows.

listeners {
    socket_options {
    # SOL_SOCKET = 1
    # SO_KEEPALIVE = 9
        level: 1
        name: 9
        int_value: 1
        state: STATE_LISTENING
    }
    # IPPROTO_TCP = 6
    # TCP_KEEPIDLE = 4
    # TCP_KEEPINTVL = 5
    socket_options {
        level: 6
        name: 4
        int_value: 60
        state: STATE_LISTENING
    }
    socket_options {
        level: 6
        name: 5
        int_value: 60
        state: STATE_LISTENING
    }
}

**Comment by codervinod** [comment]
Will this also send Keep-Alive headers in http response so that http1.1 clients can negotiate timeout with server? Example app:
![image](https://user-images.githubusercontent.com/7387542/75701856-58d69200-5c69-11ea-9440-e1c9f44cd568.png)

**Comment by mattklein123** [comment]
This is possible using socket options as described.
