### ISSUE TITLE
Make `/coverage` and `/docs` work in new CI

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#36356]
one of the things that wasnt included in first iteration of github migration is the publishing of docs and coverage

this is necessary for `/docs` and `/coverage` commands to work on PRs

readding should not be so hard - it requires some creds and setup for the gcs_upload script

**Comment by phlax** [comment]
cc @ravenblackx

**Comment by ravenblackx** [comment]
As a local workaround in the meantime (that takes ages because it rebuilds everything in coverage mode):
```
bazel coverage [the test of test targets you expect to cover the thing you're checking]
(find bazel-out/k8-fastbuild/testlogs/ -name "coverage.dat" | xargs genhtml -o ~/coverage && cd ~/coverage && python3 -m http.server)
```

**Comment by ravenblackx** [comment]
Also probably worth noting here that the CI coverage failure is currently difficult to see the important details; doing a log search for `lower than limit` seems to be the only way I can get the useful info to appear, which is pretty unhelpful if you don't already know what to look for.

**Comment by phlax** [comment]
that is actually really easy - ill raise a PR now ...
