### ISSUE TITLE
Oauth2 cookie_domain not used for IdToken or RefreshToken, causes Oauth flow to be retriggered

### ISSUE THREAD

**Issue by malsbat** [envoyproxy/envoy#36370]
Problem:
- Configure the cookie_domain field of https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#extensions-filters-http-oauth2-v3-oauth2credentials to be e.g. foo.com.  
- Execute the oauth flow against a.foo.com.
- Visit b.foo.com: the IdToken and RefreshToken are not sent by the browser.  The domain of those cookies is a.foo.com and not the configured foo.com.  The BearerToken and other cookies are sent correctly.
- This triggers the oauth flow again as the OauthHMAC calculation is not correct.

It looks like https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/oauth2/filter.cc#L760 is missing a StrCat for the id_token_ and refresh_token_ cases.

**Comment by kyessenov** [comment]
CC @derekargueta @mattklein123

**Comment by ZJfans** [comment]
> 抄送@derekargueta @mattklein123

hi，can I try to fix this, I think we can set the domain for IdToken or RefreshToken here, https://github.com/ZJfans/envoy/blob/Oauth2_cookie_domain/source/extensions/filters/http/oauth2/filter.cc#L787-L790

**Comment by mchen391** [comment]
Just want to bump this up - we are seeing the same issue in the new release v1.32.0.

**Comment by skiptomyliu** [comment]
fixed in https://github.com/envoyproxy/envoy/issues/37154
