### ISSUE TITLE
Istio proxy access log %REQUESTED_SERVER_NAME% value has string "invalid"

### ISSUE THREAD

**Issue by kpanic9** [envoyproxy/envoy#36375]
*Description*:
After upgrading to Istio 1.23.2 the Istio proxy access log %REQUESTED_SERVER_NAME% contains string invalid.

Log value From Istio 1.23.1: `"requested_server_name":"outbound_.8080_._.<k8s-service>"`
Log value From Istio 1.23.2: `"requested_server_name":"invalid:outbound_.8080_._.<k8s-service>"`

*Repro steps*:

- Update Istio version to 1.23.2
- Configure mesh to include `requested_server_name` in the access log.
```
meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: |
      {
        .....
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        ...
      }
```

- Send couple requests to a workload and check the access log

**Comment by kyessenov** [comment]
I think this is the fix for https://github.com/envoyproxy/envoy/security/advisories/GHSA-p222-xhp9-39rc. Istio uses an invalid SNI by default for upstream clusters, so now it's a warning in the log records.

**Comment by kpanic9** [comment]
Nice, Thanks for checking!
