### ISSUE TITLE
gRPC-JSON transcoder: should support /<package>.<service>/<method> HTTP paths

### ISSUE THREAD

**Issue by chuhlomin** [envoyproxy/envoy#3637]
*Title*: gRPC-JSON transcoder: should support `/<package>.<service>/<method>` HTTP paths

*Description*:
JSON transcoder should work for `/<package>.<service>/<method>` paths.

If no `option (google.api.http) path` is set then HTTP calls does not work.

If `option (google.api.http) path` is set to `/<package>.<service>/<method>` then it breaks GRPC calls.

https://github.com/chuhlomin/envoy-json-trancoding-grpc#envoy-responses-summary

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter
- https://www.envoyproxy.io/docs/envoy/latest/api-v1/http_filters/grpc_json_transcoder_filter#config-http-filters-grpc-json-transcoder-v1

*Repro steps*:
https://github.com/chuhlomin/envoy-json-trancoding-grpc/blob/master/README.md

*Config*:
https://github.com/chuhlomin/envoy-json-trancoding-grpc/blob/master/envoy/envoy.json

*Logs*:
Logs for case when no `option` defined:
https://gist.github.com/chuhlomin/710192f826bb33ee438c56bf3c1972a6

**Comment by mattklein123** [comment]
Is this a duplicate of https://github.com/envoyproxy/envoy/issues/3631? @lizan

**Comment by lizan** [comment]
Yes, thanks for detailed description @chuhlomin

**Comment by lizan** [comment]
read the logs, this is not a duplicate, #3631 is for adding support for `/<package>.<service>/<method>`, this is saying that even `/<package>.<service>/<method>` is specified the transcoder doesn't work.

**Comment by dio** [comment]
@lizan @chuhlomin do you think if we can fix the case in the third row of the [response summary](https://github.com/chuhlomin/envoy-json-trancoding-grpc#envoy-responses-summary) by skipping creating transcoder when the content-type is `application/grpc` will be good enough?

**Comment by lizan** [comment]
@dio I think it is the opposite, the transcoder was not created (I haven't investigated why) when `/<package>.<service>/<method>` is specified. The gRPC backend received JSON request and returned that error.

**Comment by chuhlomin** [comment]
I think it does make sense to disable transcoder if content-type is `application/grpc`.
When GRPC client sends GRPC request to GRPC server, transcoder should not stand in the way.

**Comment by dio** [comment]
@chuhlomin could you help us to test the changeset here: https://github.com/envoyproxy/envoy/pull/3664. I have tested it but I think we need your verification (functional wise) as well.

**Comment by dio** [comment]
I think since this #3664 is merged, can we say that this is fixed @chuhlomin?

**Comment by chuhlomin** [comment]
Yes, looks good now.
Thanks!
