### ISSUE TITLE
The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version

### ISSUE THREAD

**Issue by mosorio0829** [envoyproxy/envoy#36384]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: ***The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version***

*Description*:

Hi everyone, I trying to configure Istio global rate limit but I am getting the following errror:

warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: V2 (and AUTO) xDS transport protocol versions are deprecated in grpc_service {
  envoy_grpc {
    cluster_name: "outbound|8081||ratelimit.istio-ingress.svc.cluster.local"
  }
  timeout {
    seconds: 2
  }
}
. **The v2 xDS major version has been removed and is no longer supported**. You may be missing explicit V3 configuration of the transport API version, see the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3.
0.0.0.0_443: V2 (and AUTO) xDS transport protocol versions are deprecated in grpc_service {
  envoy_grpc {
    cluster_name: "outbound|8081||ratelimit.istio-ingress.svc.cluster.local"
  }
  timeout {
    seconds: 2
  }
}
. The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version, see the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3

I have checked the documentation and forums and this v2 xDS version was decomissioned long time ago. The envoyfilters filter-ratelimit and filter-ratelimit-svc are not specifying any v2 version and either the ratelimit service. 

My istio version is:

**client version**: 1.23.0
**control plane version**: 1.20.2
**data plane version**: 1.20.2 (30 proxies)

To my understanding this version should be using the v3. Could you please provide any advise for this? 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
I think you need to set [transport_api_version](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/ratelimit/v3/rls.proto#envoy-v3-api-msg-config-ratelimit-v3-ratelimitserviceconfig) to `V3`.
