### ISSUE TITLE
Why does http_connection_manager not use the stream id sent by the client?

### ISSUE THREAD

**Issue by jjtyro** [envoyproxy/envoy#3640]
*Title*: *Why does http_connection_manager not use the stream id sent by the client?*

*Description*:    
>In the test, I found that in the user request data received by the upstream service, the http2 stream id is 1, but the client request stream id is 3. And then, the upstream service checking if stream id larger than 1, when not true, it throw exception .    
> How to let http_connection_manager use client's stream id to upstream? or there have some config parameter to setting stream id startup number?      

*Envoy Build SHA*    
> [4dd49d8](https://github.com/envoyproxy/envoy/commit/4dd49d8809f7aaa580538b3c228dd99a2fae92a4)

*Http2 Packages*    
* receive from client     
```  
Stream: DATA, Stream ID: 3, Length 5
    Length: 5
    Type: DATA (0)
    Flags: 0x01
    0... .... .... .... .... .... .... .... = Reserved: 0x0
    .000 0000 0000 0000 0000 0000 0000 0011 = Stream Identifier: 3
    [Pad Length: 0]
    Data: 0a 03 78 78 78
    Padding: <MISSING>
```  
* Sent to upstream 
```  
Stream: DATA, Stream ID: 1, Length 5
    Length: 5
    Type: DATA (0)
    Flags: 0x01
    0... .... .... .... .... .... .... .... = Reserved: 0x0
    .000 0000 0000 0000 0000 0000 0000 0001 = Stream Identifier: 1
    [Pad Length: 0]
    Data: 0a 03 78 78 78
    Padding: <MISSING>
```

**Comment by mattklein123** [comment]
Envoy does not do a 1:1 proxy between downstream and upstream. If you want that, you should use tcp_proxy.

**Comment by jjtyro** [comment]
Thanks!
Ok,I understand. I think so after asked this question some time. 
Is there have some way to setting stream id startup number?

**Comment by mattklein123** [comment]
> Is there have some way to setting stream id startup number?

No (and I doubt we would ever add this).

**Comment by jjtyro** [comment]
Ok, I known.
