### ISSUE TITLE
`lb_zone_cluster_too_small` metrics emitted when zone aware routing is turned off

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#36425]
*Title*: `lb_zone_cluster_too_small` metrics emitted when zone aware routing is turned off

*Description*:

We are seeing envoyproxy continue to emit [lb_zone_cluster_too_small](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#load-balancer-statistics) metrics even when
zone aware routing is turned off by setting `upstream.zone_routing.enabled=0` 

We observe this issue in v1.29.4

*Repro steps*:
 - Set runtime configuration: `upstream.zone_routing.enabled=0`
 - Curl admin endpoint: `curl -s 0:9901/stats | grep lb_zone_cluster_too_small`

*Admin and Stats Output*:
```
curl -s 0:9901/stats | grep cluster.< redacted >.lb_zone_cluster_too_small
cluster.< redacted >.lb_zone_cluster_too_small: 81
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by kyessenov** [comment]
This is a counter so it is cumulative from the process start. If you disable a feature at runtime, the counter will remain. It will only be deleted when the cluster upstream definition is deleted.
