### ISSUE TITLE
Is there a way to specify backup for Cluster endpoints.

### ISSUE THREAD

**Issue by manikandan231280** [envoyproxy/envoy#36444]
*Title*: *Is there a way to specify backup for Cluster endpoints.*

*Description*:
 I am new to Envoy. How do i treat some endpoints as a backup and envoy forwards no ingress traffic to these servers unless all other endpoints that are not marked as “backup” fail the health check.

**Comment by kyessenov** [comment]
You're probably looking for priority levels https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority?

**Comment by manikandan231280** [comment]
How do i configure Priority levels so that the traffic goes to P1 only when all the nodes under P0 becomes unhealthy. I think currently the traffic sent to both P0 and P1 based on the number of healthy nodes under P0 ?

**Comment by manikandan231280** [comment]
"help wanted"
