### ISSUE TITLE
Support for future Redis versions Vs. ValKey

### ISSUE THREAD

**Issue by AnirKulk** [envoyproxy/envoy#36459]
Title: Is there any discussion around whether the Envoy Redis filter plans to remain (in the future) compatible with Redis or the Open source "equivalent" ValKey project?

Description:
Is there any discussion around whether the Envoy Redis filter plans to remain (in the future) compatible with Redis or the Open source "equivalent" ValKey project?

**Comment by alyssawilk** [comment]
pinging @msukalski @henryyyang @weisisea for commentary

**Comment by AnirKulk** [comment]
@msukalski  / @HenryYYang  / @weisisea can you please comment?

**Comment by weisisea** [comment]
Thanks for the question!

Valkey is currently compatible with existing Redis clients including Envoy Redis filter. As far as I know, in the Valkey open source community, there is no plan to diverge the client interface for the time being. Using `CLUSTER SLOTS` command to discover cluster topology will continue to be supported by Valkey.

However, it's possible in the future that Redis introduces commands that Valkey doesn't support or vice versa. If that happens, we may need to enhance the Redis filter to be able to detect whether it's talking to Redis or Valkey and then process commands accordingly. If there is a more drastic divergence in the client interface (e.g., using different commands to discover cluster topology and the responses have different formats), we may need to create a new filter for Valkey.
