### ISSUE TITLE
UNAVAILABLE: Credentials failed to obtain metadata 842 failures

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#36466]
Error: ERROR: Failed to query remote execution capabilities: UNAVAILABLE: Credentials failed to obtain metadata
842
Error: ERROR: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
843
Warning: WARNING: The following configs were expanded more than once: [remote-ci, ci]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.

https://github.com/envoyproxy/envoy/actions/runs/11191172987/job/31113772593
https://github.com/envoyproxy/envoy/actions/runs/11193706233/job/31119341784
https://github.com/envoyproxy/envoy/actions/runs/11210026449/job/31156213002

cc @phlax

**Comment by phlax** [comment]
this _should_ be fixed now - i cycled the keys this morning
