### ISSUE TITLE
Error while building Envoy 1.31.0 from sources

### ISSUE THREAD

**Issue by learnsomethingtoday** [envoyproxy/envoy#36464]
I am trying to build Envoy **1.31.0** from sources in my Linux machine with Bazel version 6.5.0, and I am stuck with the below error :
`ERROR: /builds/envoy/test/envoy/source/extensions/transport_sockets/alts/BUILD:128:17: While resolving toolchains for target //source/extensions/transport_sockets/alts:handshaker_cc_grpc_pb: No matching toolchains found for types @com_github_rules_proto_grpc//protobuf:toolchain_type.`

I also tried to run in debug mode to see if i could get any reasons for the failure and this is the extra log i got :
`INFO: ToolchainResolution:   Type @com_github_rules_proto_grpc//protobuf:toolchain_type: target platform @local_config_platform//:host: No toolchains found.`

I have not modified any files from the Envoy 1.31.0 package.

Could not find any way to get through this error, any help is appreciated.
Thanks.

**Comment by alyssawilk** [comment]
@phlax @keith any thoughts on this one?

**Comment by phlax** [comment]
that toolchain is registered here https://github.com/envoyproxy/envoy/blob/b4f6137c6ea53d503971aa9e973ee9f40346fd97/bazel/dependency_imports.bzl#L176

im guessing that isnt being called in the WORKSPACE setup for some reason

**Comment by learnsomethingtoday** [comment]
dependency_imports.bzl file is loaded only after repositories_extra.bzl is loaded, as per WORKSPACE file.

Is this the reason in any case? Just a thought

https://github.com/envoyproxy/envoy/blob/b4f6137c6ea53d503971aa9e973ee9f40346fd97/WORKSPACE#L19

https://github.com/envoyproxy/envoy/blob/b4f6137c6ea53d503971aa9e973ee9f40346fd97/WORKSPACE#L27

**Comment by phlax** [comment]
are you just building from the envoy repo "WORKSPACE" or your own? 

if the former then its not a misconfiguraiton in the WORKSPACE file unless you changed something there - i may have misunderstood the problem

**Comment by learnsomethingtoday** [comment]
I was able to surpass this error, it was due to an undiscovered bug in my driver file, it was trying to edit the repositories_extra.bzl file.

Thanks @phlax @alyssawilk for your time, closing the issue!
