### ISSUE TITLE
lua: trailers() always returns nil if it's called before reading body

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#36507]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

lua: trailers() always returns nil if it's called before reading body

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

When calling `trailers()` before reading body, this method will always return nil whether there are trailers or not.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

With configuration:

```yaml
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(handle)
                                     local trailers = handle:trailers()
                                     local always_wrap_body = true
                                     local body = handle:body(always_wrap_body)                  
                                    ...
```

The returned trailers are nil.

However, if we change the order to:

```
                                     local always_wrap_body = true
                                     local body = handle:body(always_wrap_body)     
                                     local trailers = handle:trailers()    
```

Now we can read the trailers.

It's reasonable because Envoy may want to handle the body first and then handle the trailers, which share the same stream. But it would be better to mention this order requirement in the docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#trailers.

**Comment by wbpcode** [comment]
I will prefer treat this as a bug. But I have no enough bandwidth to fix lua recently.

But at least, an additional mention at docs would be great.
