### ISSUE TITLE
bazel build //source/exe:envoy-static, error for org_golang_google_grpc

### ISSUE THREAD

**Issue by yuansx** [envoyproxy/envoy#3652]
[root@localhost envoy]# bazel build --package_path %workspace%:/root/src/envoy/ //source/exe:envoy-static
INFO: Build options have changed, discarding analysis cache.
External dependency cache directory /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25
make: Entering directory `/root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps'
No need to rebuild /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/cares.dep.env
No need to rebuild /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/benchmark.dep.env
No need to rebuild /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/libevent.dep.env
No need to rebuild /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/gperftools.dep.env
No need to rebuild /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/luajit.dep.env
Building in /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/luajit.dep.build, logs at /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/luajit.dep.log
Successful build of /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/luajit.dep
cat: /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/nghttp2.dep.env: No such file or directory
Building in /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/nghttp2.dep.build, logs at /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/envoy_deps_cache_fbe7fd77b8354b9a6f47b8e24c1a5f25/nghttp2.dep.log
ERROR: /root/.cache/bazel/_bazel_root/b4ce55150c2905dc1fa0886156c33084/external/io_bazel_rules_go/proto/BUILD.bazel:21:1: no such package '@org_golang_google_grpc//': failed to fetch org_golang_google_grpc: 2018/06/09 23:04:16 unrecognized import path "google.golang.org/grpc"
 and referenced by '@io_bazel_rules_go//proto:go_grpc'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: no such package '@org_golang_google_grpc//': failed to fetch org_golang_google_grpc: 2018/06/09 23:04:16 unrecognized import path "google.golang.org/grpc"
INFO: Elapsed time: 47.221s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (248 packages loaded)

all the error message, I don't know how to fix it. who can tell me how to do, thanks

**Comment by alonlong** [comment]
ENVOY_SRCDIR=/source
INFO: $TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
...............
Cloning into '/build/envoy-filter-example'...
remote: Counting objects: 850, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 850 (delta 28), reused 9 (delta 7), pack-reused 820
Receiving objects: 100% (850/850), 97.91 KiB | 99.00 KiB/s, done.
Resolving deltas: 100% (762/762), done.
Note: checking out '4b6c55b726eda8a1f99e6f4ca1a87f6ce670604f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 4b6c55b... cleanup: move filter wrapper into Http namespace. (#49)
building using 2 CPUs
gcc/g++ toolchain configured
bazel release build...
Building...
INFO: $TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
DEBUG: /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/io_bazel_rules_go/proto/def.bzl:138:3: You no longer need to call proto_register_toolchains(), it does nothing
ERROR: /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/io_bazel_rules_go/proto/BUILD.bazel:21:1: no such package '@org_golang_google_grpc//': failed to fetch org_golang_google_grpc: 2018/06/23 11:38:14 unrecognized import path "google.golang.org/grpc"
 and referenced by '@io_bazel_rules_go//proto:go_grpc'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: no such package '@org_golang_google_grpc//': failed to fetch org_golang_google_grpc: 2018/06/23 11:38:14 unrecognized import path "google.golang.org/grpc"
INFO: Elapsed time: 197.996s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (248 packages loaded)

**Comment by alonlong** [comment]
I have the same issue

**Comment by bengol** [comment]
got this error too

**Comment by xiaoma2100** [comment]
got this error too
