### ISSUE TITLE
oauth2 filter: option to allow errors and pass through

### ISSUE THREAD

**Issue by mchen391** [envoyproxy/envoy#36523]
*Title*: Provide an option to allow errors and pass through

*Description*:

Today, there is a `deny_redirect_matcher`, which is useful for APIs where redirecting does not make sense (e.g. AJAX endpoint). For endpoints that are listed in `deny_redirect_matcher`, the behavior would be:
1. If access token exists and valid, succeed and pass to next filter
2. If access token is expired and refresh token exists, attempt to refresh the access token and set it to cookies
3. If refresh failed or refresh token is absent, `sendLocalReply` with an error message "OAuth flow failed."
 
While local reply is customizable using [local reply modification](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply), we still run into a use case where upstream service wants to handle the error themselves, i.e. we need an option that makes the 3rd bullet above become:
* If refresh failed or refresh token is absent, _pass through_

Similarly, in JWT authentication filter, there is a JWT requirement rule called `allow_missing_or_failed` ([doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtrequirement)), with which any missing or invalid jwt will pass through so the upstream service can handle the error themselves.

**Comment by alyssawilk** [comment]
cc @derekargueta @mattklein123 for thoughts/comments

**Comment by mchen391** [comment]
We are still looking forward to this feature to support use cases where authentication is not mandatory. Please review this if possible. Thank you!

**Comment by mchen391** [comment]
@alyssawilk / @derekargueta  / @mattklein123 Sorry for the ping, but this feature was again brought up and started to become a huge blocker for us to enable the OAuth filter for more interfaces. We are willing to make contributions ourselves to make this happen, but I want to get some opinions on whether this feature sounds okay to the community. Please let me know if you have any concerns or opinions on this feature so that we can take them into consideration when making the change. Thank you!
