### ISSUE TITLE
Can't build using docker :  ./clang.bazelrc: Permission denied

### ISSUE THREAD

**Issue by rbahegne** [envoyproxy/envoy#36548]
***Envoy build fail with `/source/ci/../bazel/setup_clang.sh: line 22: ./clang.bazelrc: Permission denied`***

*Description*:
I'm trying to build envoy on Rocky linux 8

*Repro steps*:
```
cd
git clone https://github.com/envoyproxy/envoy.git
 cd envoy/
./ci/run_envoy_docker.sh './ci/do_ci.sh release.server_only'
```

ouput :
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=x86_64
Setting test_tmpdir to /build/tmp.
/source/ci/../bazel/setup_clang.sh: line 22: ./clang.bazelrc: Permission denied
```

>**Note**:  Since Docker is not available on Rocky it use automatically the docker emulation by podman, but i don't think it is related.
My user is called Rocky and has admin access, envoy is clone in the home directory.

**Comment by phlax** [comment]
i _think_ this is related to podman

i believe the issue is that the user you are running as inside the container doesnt have permissions to write in the repo directory

run_envoy_docker.sh has some mangling to ensure that the user matches inside/outside the container to ensure the container user can write there

**Comment by rbahegne** [comment]
You are right, in fact Selinux in enabled in permissive mode on my setup and because of that Podman enable also selinux. I think Selinux does not make any difference about the permissive mode and therefore prevent any file creation in its container.

**Comment by rbahegne** [comment]
OK in fact Selinux does not have anything to do with it. Shutting it down did not changed anything.

My error message changed to 
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
✔ docker.io/envoyproxy/envoy-build-ubuntu@sha256:2dd96b6f43c08ccabd5f4747fce5854f5f96af509b32e5cf6493f136e9833649
Trying to pull docker.io/envoyproxy/envoy-build-ubuntu@sha256:2dd96b6f43c08ccabd5f4747fce5854f5f96af509b32e5cf6493f136e9833649...
Getting image source signatures
Copying blob 4f784d60e1ef done   | 
Copying blob edaedc954fb5 done   | 
Copying blob a8f2f733eac6 done   | 
Copying blob 327373459e9d done   | 
Copying blob 2d45f6e7824b done   | 
Copying blob 3d0fdce632cd done   | 
Copying config ffa1fcac45 done   | 
Writing manifest to image destination
chown: changing ownership of '/build': Operation not permitted
```

Which look like a regression from,`/source/ci/../bazel/setup_clang.sh: line 22: ./clang.bazelrc: Permission denied ` if i look at `run_envoy_docker.sh`.


I'm sure how it happened, at some point out of frustration i ran `sudo ./ci/run_envoy_docker.sh './ci/do_ci.sh dev'`
Maybe it is related but i purged all cache so i don't really understand.

Anyway you sound right about Podman, but what i do not understand is that i managed to launch successfully the build under WSL in rocky linux as well so with podman as well. The build was taking forever due to lack of memory and i can't assign more ressource to the WSL VM.

Any one successfully built envoy using Podman ?

**Comment by phlax** [comment]
in general we would discourage building as root - you would need to make some adjustments for that to work also (to `rules_python` in particular)

the better scheme is to ensure that the user (ie uid) inside the container matches the uid of the user that downloads the repo outside of the container

**Comment by rbahegne** [comment]
Maybe some podman expert could make it work but i give up.

I got a ubuntu env with a proper docker and it compile right out of the box.
