### ISSUE TITLE
--hot-restart-version prints unexpected tcmalloc string with large stat size

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#3655]
The text output from --hot-restart-version should match the output from the admin API for the hot restart version.

When the size crosses a large threshold, a string from tcmalloc is output, which makes the string no longer match the API output.

```
$ envoy --hot-restart-version --max-stats 8765239
tcmalloc: large alloc 1419976704 bytes == 0x1c26000 @  0xb0d5ba 0xb90aeb 0x619344 0x46b035 0x46ac21 0x476950 0x46bd14 0x415fac 0x7fb81b09c830
9.200.8765239.127.options=capacity=8765239, num_slots=4382629 hash=228984379728933363
```

**Comment by ggreenway** [comment]
Related: https://github.com/gperftools/gperftools/issues/360

Workaround is to set the following environment variable:

`TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=50000000000`

The specific value just needs to be a number large enough that the message isn't printed; this specific value isn't important.

**Comment by YaminiGoel** [comment]
@ggreenway I am using Google Colab, there I set  `!TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=21329330176 ` and then run my python script in the same cell. Later as I run the script I get the same error that was appearing before setting `TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD`. 

The error is:
`
tcmalloc: large alloc 21329330176 bytes == 0x18e144000 @  0x7f736dbc2001 0x7f736b6f6b85 0x7f736b759b43 0x7f736b75ba86 0x7f736b7f3868 0x5030d5 0x506859 0x504c28 0x506393 0x634d52 0x634e0a 0x6385c8 0x63915a 0x4a6f10 0x7f736d7bdb97 0x5afa0a`

Kindly help me here.

**Comment by ggreenway** [comment]
I recommend setting the environment variable much larger. Add several more zeros in the end.

**Comment by mattklein123** [comment]
Going to close this out as `--max-stats` is going away soon and not worth fixing. cc @fredlas
