### ISSUE TITLE
cpu & heap profile result is incorrect

### ISSUE THREAD

**Issue by bergen4** [envoyproxy/envoy#36551]
firstly, i use this command to get cpu and heap profile:

**kubectl exec -n "$NS" "$POD" -c istio-proxy -- curl -X POST -s "http://localhost:15000/${PROFILER}profiler?enable=y"**

then, i use pprof tool get the result, but the result only show the consumption of the libc library, but not the consumption of envoy itself.

what should i do?

![WeChatdc6109d8413e6d3f9a4c4b772648bb06](https://github.com/user-attachments/assets/ccf6bc07-ce50-4c95-9e0b-04deea927a2c)
![WeChat8e554a55a5bc9289c1985a3d69e7e61c](https://github.com/user-attachments/assets/383218ea-3d26-4745-b0bb-1283b4daef88)

**Comment by kyessenov** [comment]
This usually indicates that pprof cannot find the executable to resolve the symbol. See wiki https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#istio-121-and-older.

New builds use tcmalloc where I think it works differently and does not have the same issue.

**Comment by johnlanni** [comment]
@kyessenov By the way, do you know why Istio decided to deprecate gperftool's tcmalloc after version 1.21?

**Comment by kyessenov** [comment]
Overload manager requires tcmalloc. You can choose to vendor Istio with a different Malloc.

**Comment by johnlanni** [comment]
@kyessenov Got it, thanks
