### ISSUE TITLE
envoy_reloadable_features_exclude_host_in_eds_status_draining deprecation

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#36604]
Your change #30622 (upstream: exclude draining hosts from eds) introduced a runtime guarded feature. It has been 6 months since the new code has been exercised by default, so it's time to remove the old code path. This issue tracks source code cleanup so we don't forget.
cc @milton0825

**Comment by Sanchit-20** [comment]
Hi @alyssawilk I'm interested to work on this, could you please assign this me?
