### ISSUE TITLE
/config_dump does not round-trip back to proto

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#3665]
If we take the JSON emitted by `/config_dump` and attempt to convert back to proto, e.g.
```
envoy::admin::v2alpha::ConfigDump config_dump;
MessageUtil::loadFromJson(response->body(), config_dump);
```
an exception is raised. A likely candidate is that the emitted JSON has a mix of camelCase and snake_case field names. The `preserve_proto_field_names` option in `JsonPrintOptions` is ignored for embedded Any messages by the Protobuf library's JSON conversion method. See also the recently raised https://github.com/google/protobuf/issues/4771.

**Comment by htuch** [comment]
CC @mrice32 @ambuc

**Comment by htuch** [comment]
It also helps to apply the following patch to avoid conflating camel/snake case inside filter Structs:
```
diff --git a/source/common/protobuf/utility.cc b/source/common/protobuf/utility.cc
index 7dc6bc9f2..9882bd523 100644
--- a/source/common/protobuf/utility.cc
+++ b/source/common/protobuf/utility.cc
@@ -106,6 +106,7 @@ std::string MessageUtil::getJsonStringFromMessage(const Protobuf::Message& messa
 void MessageUtil::jsonConvert(const Protobuf::Message& source, Protobuf::Message& dest) {
   // TODO(htuch): Consolidate with the inflight cleanups here.
   Protobuf::util::JsonOptions json_options;
+  json_options.preserve_proto_field_names = true;
   ProtobufTypes::String json;
   const auto status = Protobuf::util::MessageToJsonString(source, &json, json_options);
   if (!status.ok()) {
```

**Comment by mrice32** [comment]
Was this supposed to be closed?

**Comment by htuch** [comment]
No, this should still be open, the underlying fix isn't there, we #3671 was just an intermediate PR to warn that things are about to change here as we go to 1.7.0.

**Comment by htuch** [comment]
This is currently blocked on https://github.com/lyft/protoc-gen-validate/issues/15 FWIW, we need to bump protobuf library once we have the fix for `Any` field preservation, and that opens a can-of-worms around PGV and its Go proto rules.

**Comment by mrice32** [comment]
^Sorry, should've been more clear - I was pointing out that the PR *did* close it, and it shouldn't have.
