### ISSUE TITLE
Golang HTTP filters and Prometheus

### ISSUE THREAD

**Issue by maguro** [envoyproxy/envoy#36677]
*Title*: Sharing a `Registerer` amongst Golang HTTP filters

*Description*:

I'd like to write a Golang HTTP filter that will field Prometheus scrapes.   I'd like this filter to provide a `Registerer` that can be shared with the other Golang HTTP filters.

Is it possible to use `DynamicMetadata` for this purpose?

**Comment by tyxia** [comment]
@maguro What is `Registerer `? You probably want to share more details about this.

`DynamicMetadata` and `FilterState` are the common ways of sharing data between http filters

**Comment by maguro** [comment]
A `Registerer` is a Prometheus registry of metrics.  My idea is to have one filter create an instance of this registry and the other filters can register their metrics in this shared registry.

**Comment by tyxia** [comment]
add @doujiang24 who is Envoy golang expert

**Comment by doujiang24** [comment]
`Registerer` is a global interface variable in the Envoy instance, not per request, right?

You are free to share global variables between Golang filters, as long as the Golang filters are complied into a single so file together, just like share global variables between normal Golang modules, since it's full-featured Golang supported.

**Comment by maguro** [comment]
Sounds good.  Thanks!

**Comment by maguro** [comment]
> You are free to share global variables between Golang filters, as long as the Golang filters are complied into a single so file together, just like share global variables between normal Golang modules, since it's full-featured Golang supported.

So, I'm sure that I'm just being dense, but how do I register multiple filters in the same SO plugin file?

**Comment by doujiang24** [comment]
@maguro Just put multiple golang filters source code into a single Go project, and compile them into a single so file.

The key is import multiple `RegisterHttpFilterFactoryAndConfigParser` in your main.go project.
https://github.com/envoyproxy/envoy/blob/main/contrib/golang/filters/http/test/test_data/action/config.go#L11

**Comment by maguro** [comment]
Thanks!
