### ISSUE TITLE
Enable Setting TCMalloc Soft Memory Limit

### ISSUE THREAD

**Issue by ryansmick** [envoyproxy/envoy#36680]
*Title*: *Enable Setting TCMalloc Soft Memory Limit*

*Description*:
Google’s TCMalloc offers the [ability to set a soft memory limit](https://sourcegraph.com/github.com/google/tcmalloc@f9f84f7d93a51ad1d70b5dd3a693cbce8c29bd82/-/blob/tcmalloc/tcmalloc.cc?L301:31-301:40) in code. It works by attempting to release pages from the Page Heap if a new allocation from the OS puts tcmalloc’s total memory footprint above the soft limit. For users of Google’s TCMalloc, this seems to be an alternative to the shrink_heap action in overload manager, and we’d like to evaluate it as such.

It seems the only way to set this limit in TCMalloc is to call [this function](https://sourcegraph.com/github.com/google/tcmalloc@f9f84f7d93a51ad1d70b5dd3a693cbce8c29bd82/-/blob/tcmalloc/tcmalloc.cc?L301:31-301:40), and I don’t see any calls of this in envoy. Would it be possible to update envoy to support setting this soft limit in TCMalloc, perhaps via a bootstrap configuration or an environment variable?

**Comment by tyxia** [comment]
Add @nezdolik who has worked on this a lot in the past, IIRC

**Comment by nezdolik** [comment]
Sounds like a reasonable feature, we could extend [MemoryAllocatorManager](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto.html#config-bootstrap-v3-memoryallocatormanager) api for this.
