### ISSUE TITLE
Function is executed twice by passing to macro RETURN_IF_NOT_OK

### ISSUE THREAD

**Issue by congrab** [envoyproxy/envoy#36697]
In the invocation of the macro RETURN_IF_NOT_OK in the following code snippet, extracted from [envoy/source/common/common/callback_impl.h:52](https://github.com/envoyproxy/envoy/blob/eff3ed3143d0b229e0ea5b2d65608c375d26afa5/source/common/common/callback_impl.h#L52)
```absl::Status runCallbacks(CallbackArgs... args) {
    for (auto it = callbacks_.cbegin(); it != callbacks_.cend();) {
      auto current = *(it++);
      RETURN_IF_NOT_OK(current->cb_(args...));
    }
    return absl::OkStatus();
  }
```

it expands to 

```absl::Status runCallbacks(CallbackArgs... args) {
    for (auto it = callbacks_.cbegin(); it != callbacks_.cend();) {
      auto current = *(it++);
      if(!current->cb_(args...).ok()) {
        return current->cb_(args...); // ---> POTENTIAL BUG here
      }
    }
    return absl::OkStatus();
  }
```

the statement `current->cb_(args...);` in invoked twice may lead to potential bug.

**Comment by mkauf** [comment]
This bug has already been fixed by #35482.

**Comment by congrab** [comment]
thank @mkauf , 
but I see this in v1.31.2. the change should be back ported to the previous releases, right?
it has been fixed quite a long time ago.

**Comment by mkauf** [comment]
@congrab 

> the change should be back ported to the previous releases, right?

Only nominated and approved fixes will be backported. See [Backports](https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#backports) in `RELEASES.md`.
