### ISSUE TITLE
Best option for HTTP Listener Filter

### ISSUE THREAD

**Issue by leandrocurioso** [envoyproxy/envoy#36737]
**Hi Envoy Team =D**

Guys I need to develop a HTTP listener filter to handle murmur3 hash, the idea is pretty simple, basically when the request arrives I need to:
1 .Get a value from a header let’s called X-Murmur3;
2. Calculate the murmur3 hash;
3. Pass the hash to the next filter. This can be as dynamic metadata or inject a new header inside the request, since the last filter (router matcher) could apply its logic;

I already have some filters made with lua that work ok but in this case performance is crucial.

Doing some research I noticed that it will not be able to use a native lua script because this hash has some requirements like a x64 architecture to be calculated and the lua runtime works on x32. I know that there are libraries in lua that I could use but this will lead to somehow using luarocks to manage the dependency that needs to be compiled with envoy but that is a penalty I would like not to take (maintaining my own envoy build). 

We are talking about 300k concurrent TPS running in a kubernetes cluster.

My project is made in golang and I also use the controlplane you guys provide to work with it. (xDS generation).

I also noticed some possibilities:

1. Use envoy contrib build with golang filter but as I read it, it's for now pretty experimental and I would not go that way too.
I also saw that you guys have a lib to create go wasm but is deprecated since it leads to memory leak from tiny go usage.
Use ext proc, but this will introduce IO and not a preferred way;

2. I noticed that there is a thread in git talking about proxy wasm that basically seems that it is a path that is not getting the best attention for now.

**My question is:**

What do you guys recommend for me to do? I can handle languages like, lua, go, c++, rust.

If you could also link an example repo/docs to follow on how to start with would be awesome!

**Thanks a lot for your attention and time to try to help me!**

**Comment by kyessenov** [comment]
I think you should explore a Proxy Wasm solution since it has native 64-bit types that would enable the optimized instruction set for computationally heavy code.

**Comment by leandrocurioso** [comment]
@kyessenov thanks for your reply!

Which are my options to work with wasm? (Language)

Could you send me the link to an example project?
