### ISSUE TITLE
Add HTTP headers for request mirroring

### ISSUE THREAD

**Issue by KoJJang** [envoyproxy/envoy#36739]
Add HTTP headers for request mirroring in Envoy

**Description:**
AFAIK, the only way to distinguish a mirroring request from a origin request is whether or not the `-shadow` suffix is present in the host header. It would be nice to have the ability to add or remove a separate HTTP header to make the distinction more convenient.

**Proposed Improvements:**
Provide `request_headers_to_add` or `request_headers_to_remove` functionality for the mirroring request.

**Comment by mattklein123** [comment]
Makes sense to me.
