### ISSUE TITLE
admin: add mechanism to administer Envoy programmatically

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#3674]
*Description*:
>The admin-port offers privileged access (e.g. /quitquitquit) to the Envoy, and is not well protected. It should be possible to start Envoy without opening that up, and while still retaining programmatic access to the admin information -- assuming extra code is linked into the Envoy binary that provides some more secure access mechanism.

**Comment by htuch** [comment]
@shuoli84 it's conceivable we could add this to the `Node` identifier, but it does feel a bit hacky. Are you aware of https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=admin%20port#cmdoption-admin-address-path ? This will provide the port on the filesystem, which can be communicated via any bespoke mechanism to the rest of your environment.

If it becomes a common pattern that the management server (which is logically distinct from the monitoring/control aspects of some Envoy deployments, i.e. it serves config, there are other jobs that do monitoring/control) needs to know the admin port, we could put it in `DiscoveryRequest`. I'd like to hear a bit from the community about this.

**Comment by shuoli84** [comment]
@htuch Maybe a more general way? E.g, add a meta section in envoy's config, and embed it in node info. The meta is just a tag value dict or wrapper.

**Comment by jmarantz** [comment]
In addition to the Admin::request() method I added on June 19th, I'm queuing up a change to make that accessible from MainCommonBase.

After that, I'm planning on allowing a command-line disable of the admin port -- you'd still need to specify one in the config but it would be ignored.

**Comment by htuch** [comment]
Why do we need a CLI disable for the admin port? It's probably most consistent with existing configuration strategy to just disable this in the bootstrap config (e.g. by eliding the admin network config section) than explicit overrides; in general we should probably aim to push as much as possible into bootstrap rather than CLI, since it's always possible to override bootstrap via the CLI flag and you have more flexibility for other config generation systems that don't want to set CLI flags.

**Comment by jmarantz** [comment]
Works for me.

**Comment by jmarantz** [comment]
ping to keep this alive.

**Comment by fredlas** [comment]
Fixed by #4486, I believe.

**Comment by mattklein123** [comment]
Yeah this is done.
