### ISSUE TITLE
Support header based override for route level idle_timeout

### ISSUE THREAD

**Issue by itsLucario** [envoyproxy/envoy#36742]
*Title*: *Support header-based override for route level idle_timeout*

*Description*:
As of today, the route level upstream req timeout and upstream req per-try timeout can be overriden using the header [x-envoy-upstream-rq-timeout-ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-upstream-rq-timeout-ms), [x-envoy-upstream-rq-per-try-timeout-ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-upstream-rq-per-try-timeout-ms) 
This helps to override the timeout values via envoy filters or via headers dynamically. 

The request here is to support overriding route level idle timeout via header. This will help to override the idle timeout values dynamically. 

Ref: [idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout)

This idle_timeout value can't be changed at all, even with a custom C++ envoy filter (the route entry is immutatble). It can only be set permanently through the config.

Suggestion: Use similar approach to the one used for upstream request timeouts. This will allow you to override the idle_timeout via a custom header.

**Comment by ramaraochavali** [comment]
idle_timeout is for connections not for requests - do not know how it will work if it is set via header

**Comment by itsLucario** [comment]
Thanks for the resposne @ramaraochavali 

There are two different idle_timeout right! 

`HttpProtocolOptions.idle_timeout`
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout

`RouteAction.idle_timeout`
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout

I'm talking about the `RouteAction.idle_timeout`. This is for stream right!

**Comment by mattklein123** [comment]
Makes sense to me.
