### ISSUE TITLE
Support for golang-network plugin filter to act as nonterminal filter 

### ISSUE THREAD

**Issue by rishabh78** [envoyproxy/envoy#36796]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

**Title**: *Support for golang-network plugin filter to act as nonterminal filter  *

**Description**:
>The golang-network filter  plugin is terminal by design . We have a use case where I want to use it along with tcp_proxy filter . Is it possible to make it non- terminal 

https://github.com/envoyproxy/examples/blob/main/golang-network/envoy.yaml#L14

**Comment by doujiang24** [comment]
It's a known TODO, but we do not have much time to implement it yet.
Please see: https://github.com/envoyproxy/envoy/issues/25906#issuecomment-1615117709

**Comment by nezdolik** [comment]
@rishabh78 is this issue a duplicate of https://github.com/envoyproxy/envoy/issues/36829 ?

**Comment by rishabh78** [comment]
Yes, Will close this and use other ticket for reference. Duplicate ticket

**Comment by rishabh78** [comment]
Duplicate
