### ISSUE TITLE
golang: add ability to refresh route cache once we change the request

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#36848]
*Title*: *golang: add ability to refresh route cache once we change the request*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Sometimes, we want to change the matched route by modifying the header, but not decided by the final header status. For example, considering that the client's request path is `/disney/api`, and the path sent to the upstream is `/api/`, but we want to change the matched route as `/user/api/`:

```
		header.SetPath("/user/api/") // path used to match the new route
		f.callbacks.ClearRouteCache()
		header.SetPath("/api/") // path used by the upstream
```

For now, as Envoy will only refresh the route cache after decoding headers, the final header status `/api/` is used to match the new route.

Therefore, I propose adding a new method `RefreshRouteCache()`, which clears the route cache and rematch the route. With this new method:

```
		header.SetPath("/user/api/") // path used to match the new route
		f.callbacks.RefreshRouteCache()
		header.SetPath("/api/")
```

The `/user/api/` is used to match the new route.

CC @doujiang24 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by doujiang24** [comment]
lgtm, let's do it.
