### ISSUE TITLE
Which kind of status should be returned after sendLocalReply

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#36873]
I'm developing my custom HTTP filter to do some validation for HTTP requests.
```
Http::FilterHeadersStatus decodeHeaders(Http::HeaderMap& headers, bool) {
    if (header_validation_failure()) {
        callback->sendLocalReply();
        return Http::FilterHeadersStatus::???;  // which status should be returned here??? 
    }
    Http::FilterHeadersStatus::Continue;
}

Http::FilterDataStatus decodeData(Buffer::Instance&, bool) {
    if (data_validation_failure()) {
        callback->sendLocalReply();
        return Http::FilterDataStatus::???;  // which status should be returned here??? 
    }
    Http::FilterDataStatus::Continue;
}
```
As you see, if the validations fail in `decodeHeader` or in `decodeData`, I want to send a local reply to client immediately, and the current request shouldn't be held by Envoy or be passed to remaining filter anymore. But I don't know which kind of status should be returned.

**Comment by nezdolik** [comment]
you can return `StopIteration` for both decodeHeaders/Data after sending local reply.
