### ISSUE TITLE
Extension Deprecation Request: grpc_credentials/aws_iam GRPC credential extension

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#36910]
*Title*: Request to initiate deprecation of grpc_credentials/aws_iam GRPC credential extension

*Description*:
Per https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md#removing-existing-extensions I wish to deprecate extension code from source/extensions/grpc_credentials/aws_iam

This extension is fundamentally incompatible with the use of async http in source/extensions/common/aws , which was implemented to deprecate the use of curl in Envoy. It is not possible to remove the curl dependency while this plugin is still in use.

This extension was contributed by AWS appmesh team, and they are supportive of deprecation as appmesh is also on a no-further-development path. This notice hopes to elicit input from other possible users of the extension.

**Comment by nezdolik** [comment]
cc @suniltheta @mattklein123

**Comment by nbaws** [comment]
@mattklein123 keen to move this one forward. @suniltheta is across this request.

**Comment by ggreenway** [comment]
This is the last bit of work needed to remove curl as an Envoy dependency.

**Comment by nbaws** [comment]
@ggreenway what is the preferred way to mark as deprecated? as per https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md it states
```
Extension factory is modified to emit a deprecation warning.
```

Is there an example I can follow for this?

**Comment by ggreenway** [comment]
That's a good question. The only prior art I've found on this is opencensus. Here's a related change on that (but it looks like it had already been marked as deprecated. Looks like it just deprecated every field, and as long as at least one is required, using the extension will trigger the deprecated-feature warning. https://github.com/envoyproxy/envoy/pull/33912

**Comment by ggreenway** [comment]
@envoyproxy/api-shepherds any further advice on the correct way to deprecate an entire extension (not specific fields and messages)?

**Comment by nbaws** [comment]
ty @ggreenway !

**Comment by kubrickfr** [comment]
Hello! Just to be clear: this means that no replacement will be provided? I'm currently using aws_iam in my project, do I need to find a replacement?

**Comment by nbaws** [comment]
Hi @kubrickfr, thank you for your feedback - it is specifically what I was looking for.
Could you provide some information about your use case? When this extension was developed, it was to target a GRPC service behind an AWS SigV4 authenticated service. Is that similar to the use case that you have?

**Comment by kubrickfr** [comment]
@nbaws I modified the aws_auth extension to use sigv4 to authenticate against my own service. It's a bit dirty but it pre-signs STS getCallerIdentity headers, and sends them to the control plane as a proof of identity.

By the way, the extension seems broken already in 1.32, it can't get credentials from the instance metadata (but I didn't check the build options, maybe it's already building without curl by default?)

**Comment by nbaws** [comment]
@kubrickfr In 1.32 you should still be able to use the extension by setting the envoy_reloadable_features_use_http_client_to_fetch_aws_credentials runtime flag, as per https://github.com/envoyproxy/envoy/blob/ffc0437633b142062a2de3eb2bd24f4996b12ded/changelogs/1.32.0.yaml#L98

For your use case, are you configuring envoy using a GRPC server behind your authenticator service?

**Comment by kubrickfr** [comment]
Thanks for the tip @nbaws !
> For your use case, are you configuring envoy using a GRPC server behind your authenticator service?
that is what I'm doing indeed.

**Comment by kubrickfr** [comment]
Does this deprecation mean that now envoy only support static credentials to connect to a control plane? (mTLS is a form of static credentials)

**Comment by nbaws** [comment]
@kubrickfr Im not familiar with the capabilities of the rest of the grpc suite. However I am investigating whether it is possible to add pluggable authentication support (including aws sigv4/a) to the envoy grpc implementation. This will not be a quick PR but I will comment here if I come up with a solution.
