### ISSUE TITLE
golang: expose add{Decoded,Encoded}Data so that people can add data when processing headers/data/trailers

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#36911]
*Title*: *golang: expose add{Decoded,Encoded}Data so that people can add data when processing headers/data/trailers*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

We would like to provide a way to add extra data when processing headers/data/trailers. For example, turn a headers only request into a request with a body, add more data when processing trailers, and so on.

The `add{Decoded,Encoded}Data` serves our purpose well so we want to expose this method in Go, like:

```
f.callbacks.DecoderFilterCallbacks().AddData([]byte("blah"), true)
# equal to `addDecodedData(Instance "blah", true)
f.callbacks.EncoderFilterCallbacks().AddData([]byte("blah"), true)
# equal to `addEncodedData(Instance "blah", true)
```

Here I expose all the arguments of `add{Decoded,Encoded}Data` as only the callers know what arguments should be passed inside.

CC @doujiang24 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by doujiang24** [comment]
sounds good, let's do it.

**Comment by spacewander** [comment]
> By the way, can I modify request headers according to request body?( for later routes use)

@lwabish 
Yes. You could take a look at how we provide `DecodeRequest` to modify request headers with body in the Envoy Go wrapper: https://github.com/mosn/htnn/blob/9f234b90e7cea687cd828003edf115e295c97432/api/pkg/filtermanager/filtermanager.go#L644
