### ISSUE TITLE
Implement a Token Introspection (RFC 7662) HTTP Filter 

### ISSUE THREAD

**Issue by supercairos** [envoyproxy/envoy#36931]
*Token Introspection (RFC 7662)*: *Implement an HTTP Filter to verify external token*

*Description*:
> Allow external OAuth2/OIDC token to be valided via the Token Introspection api in order for envoy to act as a Identity Aware Proxy (IAP)

*Relevant Links*:
> https://datatracker.ietf.org/doc/html/rfc7662
> https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

**Comment by nezdolik** [comment]
Please get familiar with our extension policy: https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md

**Comment by nezdolik** [comment]
cc @tyxia @mattklein123 @TAOXUY (as oauth, jwt extension owners who may be interested in this proposal)
