### ISSUE TITLE
would envoy close the downstream connection when removing one upstram backend server?

### ISSUE THREAD

**Issue by bigjordon** [envoyproxy/envoy#36958]
*Description*:

   | <--downstream-> | <----------upstream-------------> |

Change config from:
 ................................./---------**weight 50**--------->  1.1.1.1 
client ----  -----  envoy 
 ................................\\---------weight 50----------> 1.1.1.2
                         to:
................................../---------**weight 0**--------->  1.1.1.1
client -----------  envoy 
 ................................ \\---------weight 100----------> 1.1.1.2

As shows,  at the beginning,  client has a long mysql connection to 1.1.1.1 via envoy. After change  weight of server 1.1.1.1,1 to 0, will envoy disconnect the link between client and envoy?

**Comment by KBaichoo** [comment]
Can you provide some more concrete details?e.g.  what config is being used?

**Comment by bigjordon** [comment]
I used a product and I don't know its configuration, but I know it uses Envoy. Is it possible to disconnect the link in front under certain configurations?

**Comment by bigjordon** [comment]
it may depents
