### ISSUE TITLE
Delta XDS: Upon reconnection, proxy never requests CDS

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#36951]
*Title*: Upon reconnection, proxy never requests CDS

*Description*:
This is likely related to https://github.com/envoyproxy/envoy/issues/33607 and/or https://github.com/envoyproxy/envoy/issues/34334, but has different symptoms.

We are observing a proxy reconnect to our control plane and never request CDS again.

Control plane logs:
```
2024-11-01T05:55:57.004730Z     info    delta   ADS: "10.244.0.200:58776" b-v1-874fc9979-h2mwg.echo-2-85025-122 terminated with stream closed
2024-11-01T05:55:57.004816Z     info    ads     Client closed connection b-v1-874fc9979-h2mwg.echo-2-85025-122
2024-11-01T05:55:57.275049Z     info    delta   ADS: new delta connection for node:b-v1-874fc9979-h2mwg.echo-2-85025-170
2024-11-01T05:55:57.275824Z     info    delta   EDS: PUSH request for node:b-v1-874fc9979-h2mwg.echo-2-85025 resources:167 removed:0 size:30.0kB empty:32 cached:135/1
67 filtered:0
2024-11-01T05:55:57.278127Z     info    delta   LDS: PUSH request for node:b-v1-874fc9979-h2mwg.echo-2-85025 resources:134 removed:25 size:372.7kB filtered:0
2024-11-01T05:55:57.278848Z     info    delta   NDS: PUSH request for node:b-v1-874fc9979-h2mwg.echo-2-85025 resources:1 removed:0 size:1.1kB
2024-11-01T05:55:57.280931Z     info    delta   RDS: PUSH request for node:b-v1-874fc9979-h2mwg.echo-2-85025 resources:83 removed:0 size:44.3kB cached:83/83 filtered:
0
```

(Note the missing `CDS: PUSH request`)

[Proxy config dump](https://storage.googleapis.com/istio-prow/logs/integ-ds_istio_postsubmit/1852220996065431552/artifacts/pilot-59bdff402a834619ad8601c9d/TestTraffic/instanceip/localhost_IP_with_localhost_sidecar/_test_context/echo-2-85025-state3169978015/primary-0/b-v1-874fc9979-h2mwg_proxy-config.json) -- note there is a warming cluster sent at a 05:55:53.961Z (4s prior to reconnect). I am not sure why; its a DNS cluster so perhaps the DNS resolution failed for some reason

[Full test logs](https://prow.istio.io/view/gs/istio-prow/logs/integ-ds_istio_postsubmit/1852220996065431552)

**Comment by sschepens** [comment]
Maybe it's best to disable `wait_for_warm_on_init` on DNS clusters? after all those initializations don't really depend on the controlplane like EDS clusters 🤔

**Comment by howardjohn** [comment]
Wow, i am shocked to see that actually.

From a control plane implementer perspective, the behavior I want in the system is this:
* given a sequence of state changes, a proxy can disconnect and reconnect at any point and experience the same behavior as if it had stayed connected throughout.
* At all points in time, I can continue to update the proxy with new configuration. If there are configuration issues, they are exposed as NACKs _and_ limited to as small a blast radius as possible (i.e. reject 1 cluster, not ALL of them, etc)

This violates both of these; the reconnections trigger a blockage of updates

**Comment by sschepens** [comment]
> At all points in time, I can continue to update the proxy with new configuration. If there are configuration issues, they are exposed as NACKs and limited to as small a blast radius as possible (i.e. reject 1 cluster, not ALL of them, etc)

I think envoy **explicitly disallows sending configurations at all points in time**, if you send some configuration you have to wait for the proxy to ACK or NACK those configurations to be able to send some more configurations (of the same type). From Envoy's point of view, you can only send configurations when there's an outstanding DiscoveryRequest, when you respond to that Request, there is no longer an outstanding request and you should wait until there is one.

> given a sequence of state changes, a proxy can disconnect and reconnect at any point and experience the same behavior as if it had stayed connected throughout.

I'm not entirely convinced in this case this is actually true. How long did the test case waited for CDS to reconnect? Would it have been enough to wait for the Cluster to end warming? I'm not sure if the reconnection here is actually the culprit, maybe the culprit is just the cluster warming. If the cluster finished warming maybe then the CDS request is re-sent? It's also unclear what de DNS timeout is, so I'm not sure how long the test should wait either.

Maybe there is an issue with reconnections if there are warming resources in envoy, I'd have to check the reconnection flow to see what happens.

**Comment by howardjohn** [comment]
> I think envoy explicitly disallows sending configurations at all points in time, if you send some configuration you have to wait for the proxy to ACK or NACK those configurations to be able to send some more configurations (of the same type). 

Envoy accepts more config even before its ACK. It may not fully _apply_ it yet, but it at least queues it up to apply when ready.

> From Envoy's point of view, you can only send configurations when there's an outstanding DiscoveryRequest, if you respond to that Request, there is no longer an outstanding request and you should wait until there is one.

Agreed, which is why I view it as a bug that it never requests CDS.

> I'm not entirely convinced in this case this is actually true. How long did the test case waited for CDS to reconnect?

Over 1 minute, which maybe means the bug is the cluster is stuck warming rather than anything around reconnection.

**Comment by sschepens** [comment]
> Envoy accepts more config even before its ACK. It may not fully apply it yet, but it at least queues it up to apply when ready.

Sure it does, but it probably makes for lots of unwanted behaviour to send configurations this way 🤔  at least it has on our experience, java-control-plane (and maybe go-control-plane) doesn't do that.

**Comment by howardjohn** [comment]
After looking at more logs of test failures, I actually think the real issue we are seeing is not exactly the issue title, but rather that clusters are stuck warming. I am still not convinced "Never request CDS if warming" is right, but sounds like this was the behavior forever -- it only became an issue for us when our clusters started getting stuck warming!

I will try to get some more info on that

**Comment by howardjohn** [comment]
Not stale
