### ISSUE TITLE
ext_proc does not honour HeaderAppendAction

### ISSUE THREAD

**Issue by davidjumani** [envoyproxy/envoy#36982]
*Title*: *ext_proc does not honour HeaderAppendAction*

*Description*:
>What issue is being seen? Describe what should be happening instead of

When running envoy with the ext_proc filter and pointing to a server that returns header mutation, envoy does not honour the `AppendAction` field but only the deprecated `Append` field as mentioned in the [HeaderValueOption docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto.html#config-core-v3-headervalueoption).
Despite setting AppendAction to any supported value, envoy only overwrites the existing header or appends to it if append is true.

This is because the relevant code change is yet to be made in ext_proc despite the updated API
[Link](https://github.com/envoyproxy/envoy/blob/release/v1.32/source/extensions/filters/http/ext_proc/mutation_utils.cc#L168-L182) to the code that only checks the value of append

ext_proc server snippet :
```
func returnResponse(key string, value string, appendAction HeaderValueOption_HeaderAppendAction) *service_ext_proc_v3.HeadersResponse {
	return &service_ext_proc_v3.HeadersResponse{
		Response: &service_ext_proc_v3.CommonResponse{
			HeaderMutation:  &service_ext_proc_v3.HeaderMutation{
				SetHeaders: []*core_v3.HeaderValueOption{
					{
						Header: &core_v3.HeaderValue{
							Key: key, 
							RawValue: []byte(value)
						},
						AppendAction: appendAction,	
	                                        // Append: &wrapperspb.BoolValue{Value: true},
					},
				},	
			},
		},
	}
}
```

**Comment by jewertow** [comment]
I fixed the same issue in ext_authz some time ago, so I could take it if no one is working on it yet.

**Comment by tyxia** [comment]
@jewertow sure please go ahead thanks

**Comment by agrawroh** [comment]
@tyxia We need this as well and I tried taking a stab at it. Would appreciate if you could take a look at the PR.

**Comment by yanjunxiang-google** [comment]
This issue had been there for a while and multiple folks asked ext_proc to support the append_action.

There had been several attempts which are trying to support it, but later on facing the backward compatibility issue, and have to abandon the efforts eventually.
The main reason of the backward compatibility issue is that ext_proc right now is the only one which are taking "append" default value as false, while everyone else are taking it as true.  If ext_proc default value of "append" is "true", then it's easy to support append_action at same time keep it backward compatible.  The logic will be:

If append.has_value()
   take append.value()
else 
   take append_action value

With this logic, if neither append, nor append_action is encoded, it took append_action default which is append_if_exist_or_add. That will be same as append = true. Thus keep it backward compatible if ext_proc filter is changed to have default append value to be "true".

**Comment by yanjunxiang-google** [comment]
BTW,  the ext_proc servers must be changed to always explicitly encode "true" or "false" in the "append" field: https://github.com/envoyproxy/envoy/blob/86ca8d764bbdd9738610c78debe86a8289bf267d/api/envoy/config/core/v3/base.proto#L469.  i.e, do not rely on the Envoy ext_proc filter default value interpretation of "append" if it is not encoded.
