### ISSUE TITLE
Query on how envoy utilizes the existing connections or creating a new connection

### ISSUE THREAD

**Issue by sakatkoori** [envoyproxy/envoy#37004]
Need help in understanding when envoy creates a new connection towards upstream or reuse the existing connection.

We have a scenario, where the connection is idle for some random time and when a new request comes to connect to upstream then envoy is reusing the port which belongs to the earlier idle connection then we are seeing the issue https://github.com/istio/istio/issues/38982

So, wanted to understand when will create a new connection towards upstream and when will reuse the connection.

**Comment by shreemaan-abhishek** [comment]
I'm interested too.

**Comment by KBaichoo** [comment]
Upstream = collection of endpoints

For a given endpoint, envoy will open a new connection if there's no available connection with capacity for a request. A connection has capacity if it can take a new stream (http request - response) on it. Draining connections are not considering as having capacity.

> envoy is reusing the port which belongs to the earlier idle connection then we are seeing the issue
What port is envoy re-using, the source port? It's entirely this might be related to having different time_waits between the system(s) communicating.

**Comment by sakatkoori** [comment]
@KBaichoo Thanks for the response, yes, source port is being reused
