### ISSUE TITLE
Expose Protocol identification API in Lua scripts

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#3704]
*Description*:
While it is possible to identify the type of protocol (H1/H2 etc) and whether TLS is used on a given request using c++ API in filters, Lua does not expose this.  It would be useful to expose this information in Lua so that Lua filter can make some decisions.

**Comment by dio** [comment]
@ramaraochavali for my own education, while the type of protocol can be inferred from `RequestInfo`, how to check whether TLS is being used in current request?

Probably I could extend the `RequestInfo` wrapper here https://github.com/envoyproxy/envoy/pull/3627 to return the protocol (e.g. the API maybe something like: `request_handle:requestInfo():protocol()`) but not sure about the flag for TLS.

**Comment by ramaraochavali** [comment]
@dio yes. I think it is from this API https://github.com/envoyproxy/envoy/blob/master/include/envoy/network/connection.h#L182.
Are you actively working on the above PR?

**Comment by ramaraochavali** [comment]
@dio sorry..I just checked the PR, looks like  you are working actively on it. I will follow the PR on the progress,

**Comment by dio** [comment]
😬yeah, it was stale a bit. Will try to cover this use-case too.
