### ISSUE TITLE
Add an option to disable nonce in the OAuth2 filter

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#37049]
>  cognito login page doesn't handle state value properly and the nonce doesn't stay in the state but gets raised directly to the url parameter and when coming back to callback nonce has disappeared from the state. In their documentation they do not support urlencoded json state values (and I guess this extends to any format, json just so common that it was mentioned).

xref: https://github.com/envoyproxy/envoy/issues/36871

**Comment by KBaichoo** [comment]
cc @derekargueta
