### ISSUE TITLE
support for regex matching in certificate uri validation

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#3705]
Currently cert URI validation checks for exact match. Can we support match via regex supplied by a config option in HttpConnectionManager proto?

**Comment by mattklein123** [comment]
I think this would be part of the TLS context config, not the HCM, unless I'm misunderstanding what you are asking for?

**Comment by ramaraochavali** [comment]
Sorry. It is TLS context config only, specifically [here](https://github.com/envoyproxy/envoy/blob/6d3d5d72986c2131a40268467c3ddcc57ef7bbc7/api/envoy/api/v2/auth/cert.proto#L202).

Please assign this to me. I will work on it.

**Comment by ramaraochavali** [comment]
@mattklein123 Please assign this to me.

**Comment by mattklein123** [comment]
cc @PiotrSikora @ggreenway

**Comment by ramaraochavali** [comment]
@PiotrSikora we are actually thinking of making the SAN validation generic enough for SPIFFE URIs. Do you have any suggestions of how to make this generic inaddition to / instead of regex validation? Any better options?

**Comment by PiotrSikora** [comment]
Do you really need full regex or is the trailing wildcard enough? See #1272.

**Comment by rshriram** [comment]
Why not wildcard prefixes just like the SNI stuff ?

**Comment by ramaraochavali** [comment]
@PiotrSikora Thanks for the pointer. We are not very clear whether trailing wild card will alone would be sufficient.
For example if we have a SPIFFE URI as
 spiffe//trust-domain/*ns*/test-namespace/*svc*/test-svc/*env*/some-env/*pod*/na-x/*region*/us-east-2
and we want our validation to ensure
- It starts with spiffe//<<trust-domain>>
- It has key value pairs specifying the name-space, svc,env,pod and region (the highlighted ones in the above URI) to appear in the same order
So  that is why I proposed regex validation.

Regarding the proto structure, if we want regex, do not we need two fields with either of them being used for validation? I agree with @ggreenway's suggestion in the PR that we should enforce this at the proto/config validation level. Or do you think we should just take both and pass the validation if either of them goes through? I did not understand your comment about single field though? Are you suggesting to reuse the same array for regex as well and some how figure out that it should be validated for regex?

 I am open to other ideas though if it simplifies things. I have closed the current PR so that it can be discussed here and will open a fresh PR with the outcome.

@rshriram SNI looks like is not [currently](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/auth/cert.proto#L291) implemented. Are you referring to some thing else? I may be missing some thing here...

**Comment by rshriram** [comment]
No. i was suggesting things along the lines of *.foo.com, *.com, etc..
Looking at this from a different angle, why can't we take the X509 style approach and split this into multiple fields, such that we can state richer stuff like spiffe/*/ns/test-namespace/svc/test-svc/... or spiffee//trust-domain/ns/*/svc/test-svc etc. I understand that this is turning the simple SAN string into a more implementation specific validation system but if it yields a richer function set, we could make this a one of.. 
```
oneof
  verify_subject_alternate_name string
  spiffeID SpiffeeID

where 
message SpiffeeID
  trust-domain string // could be exact or *
  namespace string
  service string
  env string
  pod string
  ...
```

With a bit of work, we could even turn this message SpiffeeID into a generic bag of key-value attributes extracted from the SAN by parsing the spiffee string (i.e. type spiffee, trust-domain=x, ns=test-namespace) and then the spiffee message could simply have attributes to match on (ignoring other attributes)

**Comment by PiotrSikora** [comment]
@rshriram that's a good point, but then, I'd argue that this should be kept SPIFFE-specific and we should add `spiffe` field/message to the `CertificateValidationContext` for that, instead of adding it as generic regex.

I'm not sure if that's something that Envoy is interested in supporting, though? cc @mattklein123 @htuch @ggreenway

**Comment by ramaraochavali** [comment]
@rshriram I agree having generic bag of key-value attributes extracted from the SAN with a configuration suggesting what to validate looks like a clean solution. But then as @PiotrSikora mentioned, do we want to be SPIFFE specific here and introduce those fields in Envoy `CertificateValidationContext`?  The regex was considered so that the validation need not be SPIFFE specific.

**Comment by htuch** [comment]
Are regexes going to be a security minefield here? A single character mistake or complexity in hard-to-read   regex could make it much more widely scoped than intended. I agree with the position that limit to SPIFFE and have domain semantics.

**Comment by ramaraochavali** [comment]
Ok. Sounds like we are all agreeing to move towards SPIFFE specific validation here. I will close this issue and create a fresh issue with the details.
