### ISSUE TITLE
Can envoy support other Ciphersuites for mTLS beyond the default set?

### ISSUE THREAD

**Issue by HOchacha** [envoyproxy/envoy#37081]
I'm working with Envoy to set up mTLS in a specific environment and am curious about the flexibility of ciphersuite selection. I understand that Envoy comes with a default set of ciphersuites for mTLS, but my use case requires other options outside of these defaults. 

```
[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]
[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
```
also, i know that envoy deny to use ECDSA in mTLS. 

so i want to customize the default set, but there was no clue to fix it in `source/extensions/transport_sockets/tls/context_impl.cc'
Is it possible to configure Envoy to use custom ciphersuites, or are we limited to the predefined set? 

ref default ciphersuites from [https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto)

**Comment by wufanqqfsc** [comment]
Not sure is there any other way for this , at least in our case we directly add our custom cipher suites to a new data fields  for our own envoy branch, and then set to the ssl context. Seems works well.

**Comment by yanavlasov** [comment]
@ggreenway to see if there is an easier way to configure client cipher suites.

**Comment by ggreenway** [comment]
I don't think I understand the question. Are you wanting to configure which cipher suites are used on an upstream tls transport socket, or are you trying to modify a fork of envoy to have different defaults? If it's the former, does it not work to set `cipher_suites` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto?
