### ISSUE TITLE
UPSTREAM_HOST_NAME for DFP cluster returns the port with the hostname while other clusters return the hostname only

### ISSUE THREAD

**Issue by IssaAbuKalbein** [envoyproxy/envoy#37095]
*Title*: *UPSTREAM_HOST_NAME for DFP cluster returns the port with the hostname, while other clusters return hostname only*

*Description*:
We're using Dynamic Forward Proxy cluster in our setup in addition to Strict DNS clusters and we need to have the upstream host name (DNS name) in our access log.
We had tried to use UPSTREAM_HOST_NAME and we saw inconsistency in its returned value:
- For Strict DNS cluster: We're getting the DNS name only as expected.
- For Dynamic Forward Proxy cluster: We're getting the DNS name with the port value.

Is this the expected behavior? Do we have a way to get DNS name in all clusters without the port?
cc. @wbpcode

**Comment by yanavlasov** [comment]
This is by design. DFP cluster returns host name with port because it needs to create different connection pools for requests that go to different destination ports.

**Comment by IssaAbuKalbein** [comment]
Thanks @yanavlasov for the quick response.
Do we have a way to get DNS name only without the port in all clusters? or at least to have the hostname with the port in all for consistency in the logs?

**Comment by yanavlasov** [comment]
I do not think there is a way right now. You can create and enhancement request to add UPSTREAM_HOST_NAME_WITHOUT_PORT variable.

**Comment by IssaAbuKalbein** [comment]
Thanks @yanavlasov 
I've created this PR for adding UPSTREAM_HOST_NAME_WITHOUT_PORT variable: #37114 
Appreciate if you could take a look.
