### ISSUE TITLE
Support Opentelemetry logging for Filter output

### ISSUE THREAD

**Issue by DieBauer** [envoyproxy/envoy#37146]
*Title*: Support Bootstrap logging format for OpenTelemetry

*Description*:
Currently the Application Logging format is either [JSON, or text.](https://github.com/envoyproxy/envoy/blob/v1.32.1/api/envoy/config/bootstrap/v3/bootstrap.proto#L104) 

For access logs we can already configure [opentelemetry sink](https://www.envoyproxy.io/docs/envoy/v1.32.1/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto#extension-envoy-access-loggers-open-telemetry). For application logging it would be great to have an Opentelemetry sink option as well so emitted logs are added to our OpenTelemetry stack out-of-the-box instead of shipped by another plugin that reads from file or stdout. 

[optional *Relevant Links*:]
https://opentelemetry.io/docs/specs/otel/logs/#direct-to-collector

**Comment by kyessenov** [comment]
CC @TAOXUY
