### ISSUE TITLE
What is the recommended way to make Envoy configs configurable via values.yaml in Helm?

### ISSUE THREAD

**Issue by kondratyevd** [envoyproxy/envoy#37178]
Hello Envoy team,

I am deploying Envoy proxy in Kubernetes as part of a Helm chart.

**What I have currently:**
A single static Envoy configuration in `envoy.yaml`, which is mounted to Envoy Deployment pods via a ConfigMap.

**What I would like to be able to do:**
My setup has multiple use cases that would require small modifications to Envoy configuration (for example, to deploy it at different Kubernetes clusters). I would like to make Envoy configurable from the main Helm configuration file (`values.yaml`) without duplicating `envoy.yaml` for every use case. This would include things like:
- values of single parameters in Envoy configuration, such as cluster URL and port number;
- adding entire configuration blocks, such as new filters (these could be either supplied explicitly as a JSON object or included/excluded conditionally based on some boolean parameter).

The main motivation is to:
- avoid duplication of parameters in both `envoy.yaml` and `values.yaml`;
- avoid the need to supply a separate `envoy.yaml` for every use case - most of the configuration would be the same between them.

What is the recommended / best way to achieve this?

Thank you!

**Comment by soulxu** [comment]
I'm not familiar with Helm, if you put the envoy.yaml in the ConfigMap, the values.yaml can't be used to change the envoy.yaml's content in the ConfigMap?

**Comment by soulxu** [comment]
cc @phlax if he familiar with helm

**Comment by phlax** [comment]
im assuming you are asking about deploying envoy with https://github.com/envoyproxy/gateway/ (i dont think there are any other published helm charts)

if that is the case their documentation is here https://gateway.envoyproxy.io/latest/install/install-helm/#helm-chart-customizations

if the question is about how to use helm more generally (eg you are creating your own helm charts) then i think you would need to ask for support from the helm community
