### ISSUE TITLE
Error with Dynamic Configuration for DNS Filter in Listener Filters

### ISSUE THREAD

**Issue by sefaphlvn** [envoyproxy/envoy#37173]
Hello Envoy team,

I’m encountering the following error when trying to define a DNS filter under listener_filters using config_discovery:

```
[2024-11-15 19:00:28.143][119127102][warning][config] [./source/extensions/config_subscription/grpc/xds_mux/subscription_state.h:116] Config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) dnstestPVZ2Wb: UDP listener filter: dnstestPVZ2Wb-lisfilPSRw97 is configured with unsupported dynamic configuration
```

It appears that the DNS filter in the listener_filters section is being rejected when configured with dynamic discovery.

Is this a known limitation of Envoy, or is there a workaround to support DNS filter configuration dynamically under listener_filters?

Thank you in advance for your help!

Envoy version: 1.32.1
ads, delta-grpc

**Comment by yanavlasov** [comment]
ECDS is not supported by UDP listeners filters at this point.

**Comment by sefaphlvn** [comment]
Thank you for the response.

Could you please let me know if there are any plans to support ECDS for UDP listener filters in the future? If so, is there a tentative timeline or roadmap for this feature?

Having ECDS support for UDP listener filters would be very useful for our use case, and it would help us plan our implementation accordingly.

Thank you again for your assistance!
