### ISSUE TITLE
opentelemetrytracer: Dynatrace sampler adds invalid span attributes

### ISSUE THREAD

**Issue by samohte** [envoyproxy/envoy#37199]
*Title*: *Dynatrace sampler adds invalid span attributes*

*Description*:
Dynatrace sampler calculates a sampling exponent for requests. This sampling exponent should always be lower than 15 and is used to calculate the span attributes `sampling.threshold` and `supportability.atm_sampling_ratio`. However, there is a scenario which results in a sampling exponent larger than 31. This causes an overflow and leads to invalid values.

**Comment by samohte** [comment]
I will provide a fix for this issue.

**Comment by soulxu** [comment]
cc @wbpcode
