### ISSUE TITLE
tracing: Global (overall) sampling decision can override existing propagated sampling status

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#3720]
During a review of https://github.com/envoyproxy/envoy/pull/3708#discussion_r197721215 it appears that the current logic for determining whether a request should be traced potentially overwrites an existing (propagated) sampling decision based on the `overall_sampling` percentage.

For example, if we have two services A and B, where A calls B. When the request is received by A it sets the sampling status to true - however when the request is received by service B (ingress proxy - with overall sampling of 0.1%), there is a good chance that the service will override the previous sampling decision to be false.

With the current approach used by the zipkin tracer, to only reference this sampling decision when starting a new trace instance, then this issue won't cause a problem. However if a tracer makes use of this sampling decision on mid trace instance points, then it could lead to trace instances being randomly truncated.

It would however change the `x-request-id` as it flowed through the services - which could also be confusing if the end user is relying upon that value for correlation with other recorded information.

If the aim of the overall sampling override is to cap the decision made by the `random` and `client` sampling options, then the same can be achieved by moving the statement inside the preceding conditional block.

**Comment by ydzhou** [comment]
Has this been fixed?

**Comment by objectiser** [comment]
@ydzhou Yes I believe the problem was fixed.
