### ISSUE TITLE
Authorization headers on gRPC-web request aren't forwarded.

### ISSUE THREAD

**Issue by hectim** [envoyproxy/envoy#3722]
*Title*: Authorization headers in the metadata aren't passed from envoy. 

*Description*:
Trying to pass requests with authorization headers through envoy and authenticate them afterwards, but if I add an Authorization header to my grpc-web request and send it, the header is missing from the metadata coming out of envoy. 

We're using Improbable's grpc-web client, but they do mention that they aliased `grpc.Metadata` to their own library `BrowserHeaders`. Surely they thought this was safe to do so I'm not sure if this is the problem. 

I've tried X-Authorization and other common remappings, but none seem to work and I can't find anything in the docs. Is there a special way to get that header to be passed?

relevant improbable doc: 
>https://github.com/improbable-eng/grpc-web/blob/master/ts/docs/concepts.md#metadata

**Comment by mattklein123** [comment]
@fengli79

**Comment by mancini0** [comment]
I'm encountering the same issue with envoy 1.7.0 when setting Authorization: Negotiate headers at the WeightedCluster level.

**Comment by hectim** [comment]
I can't seem to get any Authorization headers from envoy even if I just set a static header in the config

    request_headers_to_add:
        header:
            key: "authorization"
            value: "Bearer test"

unless I'm doing something fundamentally wrong, but I see things like ":authority", "x-request-id", "x-forwarded-proto", etc

    func (s *MyServer) CreateThing(ctx context.Context, in *library.Thing) (out *library.Thing, err error) {
         md, _ := metadata.FromIncomingContext(ctx)
         fmt.Println("metadata", md)
         .....
    }

**Comment by hectim** [comment]
After recreating a very simple example of the failure, we got it working by just adding `authorization` to the cors headers. There might still be a bug when you provide `request_headers_to_add` with just the right combination it will eat the headers but I can't seem to reproduce it at the moment. 

    route:
        cluster: local_service_grpc
            cors:
                allow_origin: ["*"]
                allow_headers: content-type, x-grpc-web, authorization

Closing as resolved
