### ISSUE TITLE
Reason for not having a DownstreamHttp11ConnectSocket

### ISSUE THREAD

**Issue by FH-30** [envoyproxy/envoy#37242]
*Title*: *Reason for not having a DownstreamHttp11ConnectSocket*

*Description*:
> Is the reason why there is an UpstreamHttp11ConnectSocket but no DownstreamHttp11ConnectSocket because there are no other filters aside from the http filter which requires the information parsed out of the HTTP CONNECT method? If I were to implement a DownstreamHttp11ConnectSocket that would parse out such information and set them under a struct in the Connection object, would this feature be useful for Envoy?

**Comment by soulxu** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
The reason the one exists and not the other is that someone wrote it and there was a maintainer sponsor.
All Envoy features are driven by user demand and the existing documented-somewhere extension policy :-)
