### ISSUE TITLE
Missing Docs for v1.32.1

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#37258]
## Description

It seems like we are missing docs for **v1.32.1**. The latest I see is **v1.32.0** [here](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.32/v1.32). It's been a while since v1.32.1 was released and the [main homepage](https://www.envoyproxy.io/) also points to it.

**Comment by phlax** [comment]
the docs are present - what is missing is the changelog in the `latest` docs - an easy fix
