### ISSUE TITLE
[health checker] Validate that required fields are greater than 0

### ISSUE THREAD

**Issue by brirams** [envoyproxy/envoy#3729]
*Description*:
While protobuf validation exists for things like [interval and timeout](https://github.com/envoyproxy/envoy/blob/84cacd2a5598f8b7d50fe0ccd3ef8a6deecfc2fc/api/envoy/api/v2/core/health_check.proto#L27) in cluster health checking configuration, there is [no check 
for whether values passed in make sense](https://github.com/envoyproxy/envoy/blob/84cacd2a5598f8b7d50fe0ccd3ef8a6deecfc2fc/source/common/upstream/health_checker_base_impl.cc#L19). Setting the interval to something nonsensical like 0 makes the process spin in an error loop so would be a lot more straightforward to have envoy fail fast in cases like these.

**Comment by dio** [comment]
@brirams do you think adding, e.g. for `interval`,

```js
  // The interval between health checks.
  google.protobuf.Duration interval = 2
      [(validate.rules).duration = {required: true, gt: {seconds: 0}}];
```

is enough? Or do you have a sensible min value in mind?

**Comment by mattklein123** [comment]
@dio agree with that fix.

**Comment by brirams** [comment]
coming back to this a bit late but that definitely seems reasonable. Thanks!
