### ISSUE TITLE
downstream circuit breakers

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#373]
2 different levels:
1) Phase 1, don't do keep alive (for example in HTTP connection manager filter).
2) Phase 2, immediately close connections when they are received.

Remaining items:
- [ ] Stats
- [ ] Docs

**Comment by rshriram** [comment]
Can you elaborate phase 2 please? Circuit breakers as such makes sense when calling dependencies. At downstream level, its more of handshaking pattern (assuming the other end is Envoy). If not, it boils down to throttling/load shedding does it?

**Comment by mattklein123** [comment]
This is primarily for Envoys that are acting as edge proxies. It's a defense in depth measure to help with too many incoming connections. The 2 phase approach allows it to be graceful in phase 1 before becoming "shed load as fast as possible" in phase 2.

**Comment by mattklein123** [comment]
@dnoe assigning to you.

**Comment by anticpp** [comment]
We are facing the 'too many open files' problem as an edge service, which are the same problem as this issue.

We have built an gRPC service mesh with envoy in our system, and we use a front envoy(as edge) routing client side gRPC requests.

I wonder how do you solve this scenario in your solution? Using some else h2-proxy, etc, nginx? 

However, I prefer to use a global unified solution.

**Comment by alyssawilk** [comment]
Ah, a third phase of this would be when over [a configured file descriptor limit?] to simply stop accepting new incoming connections. It's drastic, but better than crashing when under DoS attack, and will likely be implemented as part of this issue.

**Comment by mattklein123** [comment]
@anticpp I will say that in general, incoming connections can be generally controlled pretty well by having appropriate upstream circuit breakers, downstream idle timeouts, and a high enough FD limit for the process.

With that said, I would love to make progress on this issue, but it hasn't gotten resourced yet.

**Comment by alyssawilk** [comment]
I believe our team plans to pick it up in Q2
1) feel free to beat us to it and
2) please don't bet your production environment on it!

**Comment by eziskind** [comment]
Here's a draft design doc for an "Overload Manager" component for Envoy that would help address this: https://docs.google.com/document/d/1NXHAYibd6N7B4PVrukhACqzNK7WUZHWDSil9maeG1c8/edit?usp=sharing

Comments welcome!
@mattklein123 @htuch @alyssawilk

**Comment by htuch** [comment]
LGTM; left some minor comments on the doc but the overall design looks very solid.

**Comment by mattklein123** [comment]
+1 this looks great.

**Comment by mattklein123** [comment]
@eziskind I add stats/docs open items to the issue description for tracking.

**Comment by eziskind** [comment]
Remaining item is to implement overload actions in the connection manager.

**Comment by mattklein123** [comment]
@eziskind should we close this issue as complete and track further work in new issues? I think the main feature is done?

**Comment by eziskind** [comment]
@mattklein123 I'm working on overload action to stop accepting new network connections, mentioned in [this comment](https://github.com/envoyproxy/envoy/issues/373#issuecomment-376225147). After that I think we can call this done.

**Comment by mattklein123** [comment]
Per previous comment, calling this done. We can track further overload actions in new issues.
