### ISSUE TITLE
Outlier detection docs are outdated

### ISSUE THREAD

**Issue by Parvathy-Geetha** [envoyproxy/envoy#3730]
Title: Outlier detection docs are outdated

Description:
Either the explanation for things like ejections_enforced_consecutive_5xx needs to include semantics for TCP.. or that it should have entirely different statistics

https://www.envoyproxy.io/docs/envoy/v1.5.0/configuration/cluster_manager/cluster_stats.html

**Comment by mattklein123** [comment]
Closing per comment in https://github.com/envoyproxy/envoy/pull/4822. We can reopen if needed.
