### ISSUE TITLE
Move Golang Extension from contrib to main extensions

### ISSUE THREAD

**Issue by itsLucario** [envoyproxy/envoy#37300]
*Title*: *Moving Golang Extension from contrib to main extensions*

*Description*:
> Golang is a widely used language and very easy to implement envoy filter extensions using the Envoy's Golang extension. 
- Do we foresee moving Golang extension from contrib to main extension. I'm not aware of the requirements to mark a extension as contrib or main extension, any details on this would also help.
- Also from a stability point of view, where do we see the golang extension as of today?

We are currently looking into adopting Golang extensions for our use cases and use it in production. So any detail would really help and much appreciated.

[*Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/golang_filter

**Comment by doujiang24** [comment]
@itsLucario Thanks for your insteresting in Golang extension.

We do plan to move it to main, there is a issue, but sorry for busying to not make it done yet.
Moving to main is still high priority in our TODO list.

I think it's stable enough to use it in production, see: https://github.com/envoyproxy/envoy/issues/31685#issuecomment-2354469227

**Comment by itsLucario** [comment]
Awesome 🚀 ! 
Thanks for the update @doujiang24 and great to hear it's in priority TODO 😄 
Looking forward to seeing it in standard extensions.
