### ISSUE TITLE
Add X-Forwarded-Port header

### ISSUE THREAD

**Issue by saturnism** [envoyproxy/envoy#3732]
*Title*: Add X-Forwarded-Port header

*Description*: Some applications rely on x-forwarded-* headers to regenerate the application URLs. E.g., the original request URI is `http://my-service:8080`, Enovy proxy may have set `x-forwarded-proto` header to `http`, which could be interpreted to port `80`. The generated URI by the destination service may be misled to generate a URI that reads `http://my-service:80` since it doesn't know the original port. 

The original port should be passed via the `X-Forwarded-Port` header.

**Comment by rfyiamcool** [comment]
+1

**Comment by mattklein123** [comment]
Sounds reasonable. Marking help wanted.

**Comment by dio** [comment]
I want to clarify this a little bit. 

Is the value of `X-Forwarded-Port` the same as the port value of the selected upstream host (that serves the service)? 

Or it is per definition like on AWS?

> The X-Forwarded-Port request header helps you identify the port that the client used to connect to the load balancer.

https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-port

Thanks!

**Comment by mattklein123** [comment]
@dio yeah we want the listener/client port, similar to x-forwarded-for, x-forwarded-proto, etc. The thing we need to decide is whether this header is turned on via config option. I would say yes, because many/most deployments don't care about this and I would argue that users shouldn't have to pay for the extra header if they don't want it.

**Comment by pantianying** [comment]
I think this is the problem of Envoy himself. I want to know why it hasn't been resolved yet.

**Comment by zhangguanzhang** [comment]
Is this still the case in january 2021 , 😢 @mattklein123 @phlax

**Comment by visit1985** [comment]
@mattklein123 

> The thing we need to decide is whether this header is turned on via config option.

When your client is not using the default port defined for the protocol specified in `x-forwarded-proto`, envoy has to add a `x-forwarded-port` header. Otherwise the server (in my case spring-boot) will build `location` headers with missing port.

> many/most deployments don't care about this

Most deployments aim to use standard ports and don't run into this issue.

> users shouldn't have to pay for the extra header if they don't want it

Users don't see and shouldn't care about this header as it is only added to the upstream request.

**Comment by mattklein123** [comment]
For everyone complaining about "why isn't this done yet," it's because someone has to do the work. We should add the feature and have it be opt-in configured as I don't think most people care about this information and we shouldn't force the perf degradation on everyone.

**Comment by wbpcode** [comment]
May be request_headers_to_add and  %DOWNSTREAM_LOCAL_PORT% can cover this ?

**Comment by lambdai** [comment]
> May be request_headers_to_add and %DOWNSTREAM_LOCAL_PORT% can cover this ?

My two cents: theorically DOWNSTREAM_LOCAL_PORT is a L4 attribute and it's not expected to be updated during the life of downstream connection. X-forwarded-Port is per http stream attributes. These two ports should be independent.

**Comment by alyssawilk** [comment]
@lambdai when you say they should be independent what do you mean?  AFIK they refer to the same numeric port so I think the proposed solution would work.

**Comment by lambdai** [comment]
> @lambdai when you say they should be independent what do you mean? AFIK they refer to the same numeric port so I think the proposed solution would work.

Oh, this issue is about how Envoy can produce(or push) new X-forwared-Port value.
I was thinking about consuming(pop from) X-forwarded-Port. 
Yeah, adding new headers should work.

**Comment by sherifkayad** [comment]
Are there any updates on this issue folks?

**Comment by wbpcode** [comment]
@sherifkayad @rdelcampog 

> May be request_headers_to_add and %DOWNSTREAM_LOCAL_PORT% can cover this ?

can this make sense to you?

**Comment by sherifkayad** [comment]
@wbpcode I need to try this out and tell you .. not sure what should I expect by this configuration .. can you maybe explain more about which headers this config adds?

**Comment by wbpcode** [comment]
You can add the downstream port to the `X-Forwarded-Port` header by following config:
```
request_headers_to_add:
- header
    key: X-Forwarded-Port
    value: "%DOWNSTREAM_LOCAL_PORT%"
```

**Comment by sherifkayad** [comment]
@wbpcode in order to configure that with Istio I couldn't find any docs / way how to do it. Do you happen to know how it can be done?

**Comment by wbpcode** [comment]
> @wbpcode in order to configure that with Istio I couldn't find any docs / way how to do it. Do you happen to know how it can be done?

May be this can help https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers

**Comment by rdelcampog** [comment]
> @sherifkayad @rdelcampog
> 
> > May be request_headers_to_add and %DOWNSTREAM_LOCAL_PORT% can cover this ?
> 
> can this make sense to you?

Nope, when trying to access a K8s Service called "dominio" that is listening on port 8080 (http://dominio:8080) from a Pod (with the sidecar), the response that I received from the Spring Actuator (that will use caller address) is:

<img width="653" alt="imagen" src="https://user-images.githubusercontent.com/4947468/155718257-efd064e3-ea4d-4c30-b766-3c43d731c24e.png">

The %DOWNSTREAM_LOCAL_PORT% will still be 8080 as the Service is listening on port 8080 and forwarding traffic to Pod port 8080.

**Comment by abhi93104** [comment]
@sherifkayad @rdelcampog 

> May be request_headers_to_add and %DOWNSTREAM_LOCAL_PORT% can cover this ?

I was facing the same issue with Springboot admin and Istio. Springboot admin actuator api calls are failing due to incorrect port management by Istio sidecar. But I have fixed this issue by using envoy lua filter. Here is the code. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: actuator-x-forward-port-header
  namespace: dev-team # as defined in meshConfig resource.
spec:
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              if string.match(path, "/actuator") then
                local localAddressWithPort = request_handle:streamInfo():downstreamLocalAddress()
                local t={}
                for str in string.gmatch(localAddressWithPort, "([^"..":".."]+)") do 
                   table.insert(t, str)
                end
                request_handle:headers():add("X-Forwarded-Port", t[#t])
              end
            end
 
```

Using this for /actuator* path url I am able to add "X-Forwarded-Port" with correct downstream port. Now the communication is working perfectly fine between SBA and Istio.
