### ISSUE TITLE
How to pause a WebSocket handshake request in an HTTP native filter and either continue or reject it in an asynchronous callback?

### ISSUE THREAD

**Issue by AcherTT** [envoyproxy/envoy#37328]
*Title*: *How to pause a WebSocket handshake request in an HTTP native filter and either continue or reject it in an asynchronous callback?*

*Description*:
  I'm working on an Envoy HTTP native filter. In the filter's decodeHeaders function, I initiate an asynchronous request and return FilterHeadersStatus::StopIteration. In the asynchronous callback, I modify the headers and decide whether to call decoder_callbacks_->continueDecoding or decoder_callbacks_->sendLocalReply.

  However, during WebSocket debugging, I observed that the client's handshake request does not pause as expected. Instead, it seems to proceed and connect to the backend service. It appears that StopIteration does not effectively pause or reject the HTTP handshake request for the WebSocket connection.

  I found the following statement in the documentation:
"Buffering is generally not compatible with upgrades, so if the Buffer filter is configured in the default HTTP filter chain it should probably be excluded for upgrades by using upgrade filters and not including the buffer filter in that list."

Does this imply that I cannot pause WebSocket requests in the same way as regular HTTP requests? Is there any solution to handle this scenario?

**Comment by RyanTheOptimist** [comment]
@yanavlasov @zuercher

**Comment by zuercher** [comment]
I'd look at the ext_authz http filter, which does something similar.
