### ISSUE TITLE
Add per-filter spans for distributed tracing

### ISSUE THREAD

**Issue by kosamson** [envoyproxy/envoy#37339]
*Title*: Add per-filter spans for distributed tracing

*Description*:
Certain API Gateway products enable debugging transactions as they are processed by the data plane at a granular policy or filter level. One example is Google's [Apigee Edge](https://docs.apigee.com/api-platform/get-started/get-started) which supports the [Trace tool](https://docs.apigee.com/api-platform/debug/using-trace-tool-0). The Apigee Trace tool allows for troubleshooting client-to-Apigee, Apigee-to-target, and intra-Apigee (between Apigee policies) transaction flows.

In Envoy, the [distributed tracing filter(s)](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing) allow for the two former scenarios, but I do not see support for tracing intra-Envoy flows such as a transaction being processed by a series of L4/L7 filters. As of now, I see that Envoy emits one span for a transaction passing through the data plane to an upstream cluster and potentially more spans for remote service calls as part of an HTTP filter such as [External Authorization](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter) or [Rate Limiting](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter).

It would be great if Envoy could emit more granular ([internal](https://opentelemetry.io/docs/concepts/signals/traces/#internal)) spans for each filter processed as part of a single transaction. This would enable easier troubleshooting in scenarios such as determining which synchronous filter(s) are adding latency to the overall transaction. For the most granular data, this might require each filter to implement its own tracing logic. However, it could be useful to generalize some tracing behavior managed by the Envoy worker thread across all L4/L7 filters such that we can at least get processing duration data for each filter.

**Comment by kosamson** [comment]
Some alternatives I have used to troubleshoot potential intra-Envoy latency issues is by using the `%COMMON_DURATION(START:END:PRECISION)%` command operator in Envoy [access logging](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage). This helps narrow down if latency is introduced by a downstream/upstream peer or by Envoy itself. However, this does not provide enough granular information as to what might be causing latency if it *is* caused by Envoy.

**Comment by kosamson** [comment]
To have closer parity to the Apigee Trace tool, maybe it might be worth considering adding this per-filter data to the [Tap filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter)? It would be ideal if for each filter, we can see both:
1. Overall processing time (useful for troubleshooting latency)
2. Request/response data (headers and payload) before/after the filter processes the transaction (useful for troubleshooting malformed requests/responses impacting business logic)

**Comment by RyanTheOptimist** [comment]
@wbpcode

**Comment by wbpcode** [comment]
Nothing is free, more detailed tracing means more overhead in the key path and more complex code base, I think we cannot accept further decrease of the envoy performance.

And in most cases, most users needn't this because the filter of envoy basically is super fast. And if there is performance problem, `perf` would be more useful than the filter level tracing.

Of course, I am not mean the feature is senseless, I only mean it may doesn't deserve the overhead and investment. I think the best althernative would be the `ExecutionContext`.

The `ExecutionContext` provides very fine grained probes (include filter level) that could be extended to record the overhead of per filter. By default, the `ExecutionContext` is compiled out but it's easy to enable it if it's required.

**Comment by kosamson** [comment]
> Nothing is free, more detailed tracing means more overhead in the key path and more complex code base, I think we cannot accept further decrease of the envoy performance.
> 
> And in most cases, most users needn't this because the filter of envoy basically is super fast. And if there is performance problem, `perf` would be more useful than the filter level tracing.
> 
> Of course, I am not mean the feature is senseless, I only mean it may doesn't deserve the overhead and investment. I think the best althernative would be the `ExecutionContext`.
> 
> The `ExecutionContext` provides very fine grained probes (include filter level) that could be extended to record the overhead of per filter. By default, the `ExecutionContext` is compiled out but it's easy to enable it at the third-party building if it's required.

Thank you for the reply, I appreciate the feedback and information on this feature suggestion.

If more detailed tracing will add more overhead/latency to the key data plane path, then I agree that it probably is not worth adding (unless it was in some sort of "debug" binary of some sort).

I am not familiar with the `perf` and `ExecutionContext` features/components, but let me do some research to see if this would satisfy what I am looking for.

For `ExecutionContext`, I found this [GitHub issue](https://github.com/envoyproxy/envoy/issues/32012) which explains it in detail, but I am not sure what you mean by `perf`. Did you mean to refer to [`envoy-perf`](https://github.com/envoyproxy/envoy-perf)?

**Comment by wbpcode** [comment]
re to `perf`

I mean the linux perf tool 🤣

**Comment by kosamson** [comment]
marking this closed for now since I am not actively looking at this. once I take a look at @wbpcode's recommendations I'll report back here and re-open
