### ISSUE TITLE
Add Endpoints to Admin API Config Dump

### ISSUE THREAD

**Issue by liamawhite** [envoyproxy/envoy#3739]
*Title*: Add Endpoints to Admin API Config Dump

*Description*:
The config dump currently has clusters, listeners, routes and bootstrap. We would like include endpoints as its the last bit of dynamic config we don't have visibility into.

**Comment by ramaraochavali** [comment]
@liamawhite  Issue already exists https://github.com/envoyproxy/envoy/issues/3362

**Comment by liamawhite** [comment]
I knew I had seen something, somewhere! My search skills have failed me.
