### ISSUE TITLE
Implement the GRPC-Web spec.

### ISSUE THREAD

**Issue by fengli79** [envoyproxy/envoy#374]
Implements the GRPC web spec: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

**Comment by fengli79** [comment]
I'm going to implement this soon, could you help to assign this to me?

**Comment by mattklein123** [comment]
@fengli79 before writing a ton of code, can you provide a rough implementation outline? From my limited understanding it seems like this will be an optional filter?

**Comment by mattklein123** [comment]
@fengli79 should we close this as complete for now? Or do you want to leave this open to track further follow ups?

**Comment by fengli79** [comment]
There's one more thing left. I need to create a PR for error handling. We can close this after that.

**Comment by mattklein123** [comment]
@fengli79 can we close this out now? Anything else immediate being tracked?

**Comment by fengli79** [comment]
Yes, we can close it. It's ready to use.
Further features can be tracked by separate issues.
