### ISSUE TITLE
Investigate build performance

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#3741]
Non-scientifically, I think it takes a lot longer to compile Envoy now. Part of it is we have more code, but I also kind of suspect we've had some regressions somewhere in general compile perf. 

I'm looking for an intrepid volunteer who might like to look into this, both by actually tracking/investigating CI perf and also investigating potential improvements.

**Comment by mattklein123** [comment]
Possibly related, not sure: https://github.com/envoyproxy/envoy/issues/3292

**Comment by htuch** [comment]
I think by examining master CI build times on CircleCI and walking back through history with some moving average filter, it should be possible to identify the PR that caused this. Alternatively, it might be completely unrelated to our code and related to Bazel version bump, so once the guilty PR and associated date is identified, we should look at Bazel release dates as well.

**Comment by zuercher** [comment]
I wrote a script to collect build times from successful master branch release jobs. It's pretty slow, since it has to scan backwards through the builds looking for the right branch/job combination. I'll post the data when I've collected the last 200 or so.

**Comment by zuercher** [comment]
See https://docs.google.com/spreadsheets/d/16XAf1lzEdSl2gOr6-zM-TytGSmtuciDbNjrOh77HOuI/edit?usp=sharing

Unfortunately, it's pretty noisy and the moving averages don't really show an obvious culprit. Maybe someone else can make more of it.

**Comment by lizan** [comment]
@zuercher Do you have a script to get release build timings from CI? If so can you update the spread sheet numbers with recent builds with remote cache enabled?

**Comment by zuercher** [comment]
Yes. I can do that.

**Comment by zuercher** [comment]
@lizan I've updated the data in the spreadsheet. Since there's only been about 260 builds since the last time I did this, I ended up just updating the existing data, since it's contiguous. It's still highly variable, but definitely faster.

**Comment by lizan** [comment]
Thanks @zuercher! Yes I expected it to be even higher variable, due to variable cache hit rate caused by changes, happy to see it improved quite a bit.

**Comment by mattklein123** [comment]
Closing as this issue is not directly actionable.
