### ISSUE TITLE
Failed to build envoy with following error: unable to find valid certification path to requested target for http_archive

### ISSUE THREAD

**Issue by newwuhan5** [envoyproxy/envoy#37469]
When I try to build 1.32.1, I got following errors:

```
  /build/bazel_root/base/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':
   Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp269037764182601366/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: /source/WORKSPACE:17:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp269037764182601366/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp269037764182601366/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Any idea on how to fix this issue?

export IMAGE_NAME=company-docker-hub/envoyproxy/application_folder/envoy-build-ubuntu
export IMAGE_ID=f94a38f62220a2b017878b790b6ea98a0f6c5f9c
export ENVOY_SOURCE_DIR=${HOME}/envoy

The image rebuilt with added root ca certificates, plus bazel version 6.5.0, which is the matching version of release/v1.32.1

release tag: release/v1.32.1

**Comment by ggreenway** [comment]
It looks like your build machine's trusted CA bundle doesn't trust the certificate for `storage.googleapis.com`. Either there was a temporary issue with that domain, or you are using a trust bundle that doesn't include a CA that is needed.

**Comment by newwuhan5** [comment]
@ggreenway Greg, thank you for your response.  That's what originally thinking as well, in addition, we did build the ubuntu build image with added root ca certs.  Moreover, if shell into the container, using following command:

curl -fSL https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz -o dd4080.tar.gz

It works fine.  
The issue occurs when going through the WORKSPACE, the bazel failed to pull the above tar gz file without valid certificate.

The question here is: Is there a way to configure bazel to use the ca certs located in /etc/ssl/certs.

**Comment by akhilsingh-git** [comment]
This error indicates that Bazel’s HTTP fetcher is failing due to TLS certificate validation issues—specifically, it’s not trusting the certificate chain returned by storage.googleapis.com. Even though curl works fine inside the container, that’s because curl uses your system’s CA bundle at /etc/ssl/certs. Bazel, on the other hand, relies on the Java runtime’s trust store by default, which may not include the same CA certificates as your system’s OpenSSL-based trust store.

Key Insight:
Bazel’s external repository downloads are performed by a Java process that checks certificates against the Java trust store ($JAVA_HOME/lib/security/cacerts). Even if you have system CA certificates installed (like ca-certificates on Ubuntu) and curl works, Bazel might not trust the same CAs unless they’re also present in the Java trust store.

Steps to Fix
	1.	Update the Java Trust Store:
Add the required root CA certificates to the JDK’s trust store. For example:

keytool -import -alias customca -keystore $JAVA_HOME/lib/security/cacerts -file /path/to/your/ca.pem -storepass changeit -noprompt

Note:
	•	$JAVA_HOME should point to the Java installation Bazel is using.
	•	changeit is the default trust store password for many Java distributions.
After adding the CA, rebuild your image or restart your build environment so that Bazel runs with the updated trust store.

	2.	Verify Certificates:
Run a command like:

keytool -list -v -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit | grep "Your CA Name"

to ensure your CA is now in the Java trust store.

	3.	Check Bazel Version and Java Environment:
You mentioned you’re using Bazel 6.5.0 to match Envoy 1.32.1. Ensure that the Java version you’re using with Bazel is pointing to the correct trust store location. Some container images might have multiple Java installations.
	4.	Alternative Approaches:
	•	Use --host_jvm_args: You can try passing a custom trust store to Bazel using:

bazel --host_jvm_args=-Djavax.net.ssl.trustStore=/path/to/updated/cacerts build //source/exe:envoy-static

This explicitly tells Bazel which trust store to use.

	•	Check Network/Proxy Settings: Ensure no corporate proxy or MITM scenario requires adding more specific CA certs.

Why Curl Works But Bazel Doesn’t
	•	Curl: Uses the system’s CA certificates (often found in /etc/ssl/certs), which you’ve already updated or which are standard and trust storage.googleapis.com.
	•	Bazel’s Java process: Uses the Java trust store which is separate from the system CA bundle. Unless you update this store, Bazel will fail SSL checks that curl can pass.

**Comment by newwuhan5** [comment]
@akhilsingh-git Thank you very much for your insight.  Here are the couple of issues I found:

-- Added company's root ca jdk cacerts:
/build/bazel_root/install/20da5ab742b8d3d499c34fdafcd3c8b8/embedded_tools/jdk/lib/security/cacerts

*****************
Errors:
*****************
FATAL: corrupt installation: file '/build/bazel_root/install/20da5ab742b8d3d499c34fdafcd3c8b8/embedded_tools/jdk/lib/security/cacerts' is missing or modified.  Please remove '/build/bazel_root/install/20da5ab742b8d3d499c34fdafcd3c8b8' and try again.

-- Added "--host_jvm_args=-Djavax.net.ssl.trustStore=/etc/ssl/certs/cacerts" to bazel
In this case, I noticed that bazel started a local bazel server, which once again, not using above switch.  This seems the default behavior of bazel.  The latest change on envoy is to fetch jdk like:

# Its better to fetch too little rather than too much, as whatever is
# actually used is what will be cached.
# Fetching is mostly for robustness rather than optimization.
FETCH_TARGETS=(
    @bazel_tools//tools/jdk:remote_jdk11
    //bazel/rbe/toolchains/...
    //tools/gsutil
    //tools/zstd)

My questions are: 
Is there anyway to using pre-installed jdk, on ubuntu build image and instruct the bazel to use that jdk, not using the above dynamically fetched one.  

Second question is above "Starting local Bazel server and connecting to it...", which seems running as a separate server.  How to modify the Baze server start routine to using specfic jdk (such as pre-installed one with added company's root ca).

Anyone can help, really appreciate it!

**Comment by newwuhan5** [comment]
Here is the solution posted here, in case someone has same issue:

In the docker build image, added following ENV:
ENV JVM_TRUSTSTORE="--host_jvm_args=-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts"

In toplevel, bazel call:
/usr/local/bin/bazel ${JVM_TRUSTSTORE} --options

This will override the bazel default java cacerts.  The /etc/ssl/certs/java/cacerts contains all the ca certs relevant to your company.  This could be a general solution for any other bazel projects for your company.  This will resolve the issue of "unable to find valid certification path to requested target".

I went a little bit further to be more useful as a solution.  These should be optional:

/usr/local/_bazel                                                  <= download the bazel binary
ln -sf /usr/local/_bazel /usr/local/bin/bazel        <= Normal bazel call

Additional bazel_jvm with overridden jvm truststore
echo "/usr/local/_bazel  ${JVM_TRUSTSTORE}" > /usr/local/_bazel_jvm
ln -sf /usr/local/_bazel_jvm /usr/local/bin/bazel_jvm

chmod +x /usr/local/bin/bazel /usr/local/bin/bazel_jvm

These provide the option to call bazel and bazel_jvm, the latter is useful for non-nested deps whereas you can use:
/usr/local/bin/bazel ${JVM_TRUSTSTORE} --options for the nested deps.
