### ISSUE TITLE
Build Envoy with Golang Filter from Contribution Package

### ISSUE THREAD

**Issue by aabfalterer** [envoyproxy/envoy#37476]
I'm trying to build Envoy with the Golang filter included in the binary and I'd like to avoid including any other additional extension filter.

I attempted using the following command:

`./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--//contrib/golang/filters/http/source:enabled=true" ./ci/do_ci.sh release.server_only'`

However, this approach wasn't successful.

My questions are:

- Is there a recommended way to build Envoy with just the Golang filter from the contribution package using the Bazel build system?
- Is there a way to achieve this using a Docker build mechanism? If so, could you please provide some guidance or examples?

Any insights or suggestions would be greatly appreciated.

**Comment by aabfalterer** [comment]
I would like to kindly ask the maintainers of the golang filter extension, @doujiang24, @wangfakang, @StarryVae, @spacewander, and @antJack, for help

**Comment by phlax** [comment]
@aabfalterer assuming you want to build the normal build target i think you would need to edit `source/extensions/extensions_build_config.bzl` 

otherwise - you can build the contrib target and disable any you dont want to include

**Comment by aabfalterer** [comment]
@phlax Many thanks for the hint. I was able to enable the golang filter with the following change (based on v1.32.0)

```
diff --git a/source/extensions/extensions_build_config.bzl b/source/extensions/extensions_build_config.bzl
index 104ca2e63d..f0ef8e1c23 100644
--- a/source/extensions/extensions_build_config.bzl
+++ b/source/extensions/extensions_build_config.bzl
@@ -542,7 +542,7 @@ EXTENSIONS = {
 # need to directly reference Envoy extensions.
 EXTENSION_CONFIG_VISIBILITY = ["//:extension_config", "//:contrib_library", "//:mobile_library"]
 EXTENSION_PACKAGE_VISIBILITY = ["//:extension_library", "//:contrib_library", "//:mobile_library"]
-CONTRIB_EXTENSION_PACKAGE_VISIBILITY = ["//:contrib_library"]
+CONTRIB_EXTENSION_PACKAGE_VISIBILITY = ["//visibility:public"]
 MOBILE_PACKAGE_VISIBILITY = ["//:mobile_library"]

 # Set this variable to true to disable alwayslink for envoy_cc_library.
````

````
diff --git a/source/extensions/extensions_build_config.bzl b/source/extensions/extensions_build_config.bzl
index 7d3cdbad71..104ca2e63d 100644
--- a/source/extensions/extensions_build_config.bzl
+++ b/source/extensions/extensions_build_config.bzl
@@ -187,6 +187,7 @@ EXTENSIONS = {
     "envoy.filters.http.wasm":                          "//source/extensions/filters/http/wasm:config",
     "envoy.filters.http.stateful_session":              "//source/extensions/filters/http/stateful_session:config",
     "envoy.filters.http.header_mutation":               "//source/extensions/filters/http/header_mutation:config",
+    "envoy.filters.http.golang":                        "//contrib/golang/filters/http/source:config",

     #
     # Listener filters
````
