### ISSUE TITLE
remove orca headers after it's parsed to avoid it's leaked to clients

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#37520]
*Title*: *remove orca headers after it's parsed to avoid it's leaked to clients*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
cc @efimki

**Comment by efimki** [comment]
I can see it useful in some scenarios, but not in all. 

For example, getting ORCA headers to the client is very useful for debugging and observability. 

Is there an existing way to configure the route to remove / override arbitrary response header?

**Comment by wbpcode** [comment]
> I can see it useful in some scenarios, but not in all. 
> 
> 
> 
> For example, getting ORCA headers to the client is very useful for debugging and observability. 
> 
> 
> 
> Is there an existing way to configure the route to remove / override arbitrary response header?

yeah. Although it requires users to do additional configuration. But maybe it is also fine.
