### ISSUE TITLE
REQ(HOST) does not work in access log format string

### ISSUE THREAD

**Issue by xfye** [envoyproxy/envoy#3757]
*Description*:

envoy version:
 - 2e3adc3d3bb5b4c7be0b9001197f7c86000b6dd3/1.7.0-dev/Clean/RELEASE
 - 3f59fb5c0f6554f8b3f2e73ab4c1437a63d42668/1.7.0/Clean/RELEASE

I have configured "%REQ(HOST)% in access log format string. 

I'm sure the client sent request with HOST header but envoy does not record HOST header in access log at all.

My access log config:

```
           "access_log": [
            {
             "config": {
              "format": "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%-_-%REQ(remote_user?remote_user):20%-_-%START_TIME%-_-%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%-_-%RESPONSE_CODE%-_-%BYTES_SENT%-_-%REQ(HOST)%-_-%REQ(USER-AGENT)%-_-%REQ(X-FORWARDED-FOR)%-_-%UPSTREAM_HOST%-_-%RESPONSE_CODE%-_-%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%-_-%DURATION%-_-%RESPONSE_FLAGS%\n",
              "path": "/var/log/envoy/envoy-access.log"
             },
             "name": "envoy.file_access_log"
            }
           ],
```

**Comment by mattklein123** [comment]
You need to use `:authority` (Envoy normalizes everything to http/2 headers)

**Comment by xfye** [comment]
Thanks, it works. Close this issue.

**Comment by sanjeewa-malalgoda** [comment]
I'm having similar issue when i  configure ext-authz as follows. Here also i do not get method name to authz server side. Do you have any idea? How do we set authority here?

          - name: envoy.ext_authz
            config:
              http_service:
                server_uri:
                  uri: http://127.0.0.1:9763/api-import-export-2.2.0-v0/validate-service
                  cluster: ext-authz
                  timeout: 0.25s
                path_prefix: /api-import-export-2.2.0-v0/validate-service
                allowed_request_headers: 
                - Authorization 
                authorization_headers_to_add:
                - key: Method
                  value: "%REQ(method)%"
