### ISSUE TITLE
Add Chinese Documentation link based on Envoy 1.7

### ISSUE THREAD

**Issue by rootsongjc** [envoyproxy/envoy#3762]
## Add Chinese Documentation based on Envoy 1.7

The service mesh community named [ServiceMesher](http://www.servicemesher.com) in China translated the Envoy's official documentation this month. See it in [GitHub](https://github.com/servicemesher/envoy). Thanks to our [27 contributors](https://github.com/servicemesher/envoy/graphs/contributors). We'd like to add the link http://www.servicemesher.com/envoy/ to this repo's README.md.
Compared to the [this](https://github.com/lixiangyun/envoyproxy_doc_ZH_CN) translation, we have such advantage:
- the lastest docs
- a big community to maintain the doc
- keep eyes on the doc's update
- graceful translations

**Comment by mattklein123** [comment]
@rootsongjc if these docs are more up to date and maintained I'm all for replacing what we link to now with this. @lizan can you take a quick look here and advise?

**Comment by lizan** [comment]
Thanks @rootsongjc! Yes, I took a quick look and it looks nice and up-to-date to 1.7. Feel free to open a PR to swap the link.
