### ISSUE TITLE
runtime: allow additional override layers

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#3774]
Currently, runtime allows an override based on the `service-cluster` only.

This works well except in the case that we want to set a value globally for some other logical collection of envoys.

One implementation might look like an additional list of `override` directories, and merge them in order:
```
{
  "symlink_root": "/srv/runtime/current",
  "subdirectory": "envoy",
  "override_subdirectory": "envoy_override"
  "override_order": [
     "fooservice",
     "user-facing",
     "tier0",
  ],
}
```

This would give us a merge of:
```
/srv/runtime/current/envoy
/srv/runtime/current/envoy_override/fooservice
/srv/runtime/current/envoy_override/user-facing
/srv/runtime/current/envoy_override/tier0
```

i.e. setting the `override_order` would remove the implicit `service-cluster` override. If it's needed, specify it explicitly in the desired spot in the merge order.

It could be argued that any further override capability should be handled by the runtime deployment system, distributing merged runtime bundles based on some kind of per-service manifest. However, since we already allow an override capability, and it would be nice make it more flexible.

**Comment by mattklein123** [comment]
This has been implemented with the new generic layers system.
