### ISSUE TITLE
Remove invalid h/2 response headers

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#3788]
Currently when Envoy receives a h/2 response with Connection specific headers (like `keep-alive`) it will fail with: `Invalid HTTP header field was received`

This is due to [nghttp explicitly disallowing these headers](https://github.com/nghttp2/nghttp2/blob/842509dab604e6cc62f7fb98d448294c6ec85763/lib/nghttp2_http.c#L206). This is in accordance with the h/2 spec: https://tools.ietf.org/html/rfc7540#section-8.1.2.2 , which states that these headers should not be present in h/2 messages.

It seems like Envoy should be stripping these headers when converting a h/1.1 response into a h/2 response, or maybe just blindly strip these for h/2 given that they'll cause a protocol error downstream.

**Comment by mattklein123** [comment]
@snowp AFAIK we do this, but maybe some of the logic is broken. Feel free to fix: https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_utility.cc#L300. Also check conn_manager_impl.cc for other modifications of Connection header. I thought we cleared it for h2 but maybe not.

**Comment by snowp** [comment]
Ah, it looks like keep-alive and other proxy headers are removed from request headers (https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_utility.cc#L44), but not from response headers. Does it seem reasonable to remove the same headers in the response?

**Comment by mattklein123** [comment]
@snowp I would search the code for the headers to see what is happening where, but yes, we should definitely fix to the spec if this is causing issues. I really thought we already strip Connection header somewhere, since we have lots of cases at Lyft of HTTP/1.1 upstreams going to H2 and we don't see issues. Which headers are explicitly causing you issues?

**Comment by snowp** [comment]
We ran into an issue with nginx or rails setting the keep-alive header on the response, e.g. `keep-alive: timeout=60`. 

If we look at nghttp2 it's clear that there are several headers shouldn't be sent for h2, but they're technically still valid for h/1.1. Wondering if we should be stripping them for all responses or just h2? Looks like we do all requests for request headers, so maybe we should do the same for response headers.

disallowed response headers fields in nghttp2: https://github.com/nghttp2/nghttp2/blob/842509dab604e6cc62f7fb98d448294c6ec85763/lib/nghttp2_http.c#L282

**Comment by mattklein123** [comment]
Ah I see. OK, I think we are dealing with the `Connection` header but not those. Sure feel free to go ahead and do a PR to remove the rest of it's an H2 downstream. Thank you!
