### ISSUE TITLE
Redis key hashing 

### ISSUE THREAD

**Issue by georgasa** [envoyproxy/envoy#3794]
**Issue Template**

*Title*: *Key hashing with Redis cluster*

*Description*:
Hello,

I'm using a redis cluster configured as described here (https://redis.io/topics/cluster-tutorial) while I'm using Envoy in front of my application to act as proxy. The cluster config is shown below:

  "cluster_manager": {
    "clusters": [
      {
        "name": "rtdb",
                "lb_type": "ring_hash",
        "type": "static",
        "connect_timeout_ms": 2500,
        "hosts": [
          {
            "url": "tcp://169.254.2.35:6390"
          },
                  {
            "url": "tcp://169.254.2.37:6392"
          },
          {
            "url": "tcp://169.254.2.41:6394"
          }
        ]
      }
When issuing a command (e.g. set "foo" "bar"), Envoy does its own hasing and sends the key to a specific Redis node. But Redis has also its own hashing algorithm so the key will may be MOVED into another node from the one that Envoy "knows". So when I want to retrieve the "foo" key, Envoy searches in the incorrect node and can't get he value back, as it receives a MOVED indication from Redis. So my question is, how can I "synchronize" both hashing algortihms in order to get consistent data, or at least how could I disable the hashing in Redis cluster and leave only Envoy to do the key distribution?

By the way, when I substituted envoy with https://github.com/eleme/corvus everything went smooth. So I'm trying to understand the difference between envoy and corvus in order to choose the best solution for my deployment.

Many thanks

**Comment by mattklein123** [comment]
Envoy Redis and clustered Redis are not compatible. (Envoy doesn't support clustered Redis). See here for more info: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis

**Comment by georgasa** [comment]
Thanks for your prompt response. I had already read this but was not obvious (at least to my eyes) that the topic was referring to non-clustered Redis only. So I got confused with the double hashing (from envoy and Redis). Thanks for clarifing this crucial info.
