### ISSUE TITLE
Add new external_deps in pgv_cc_proto_library gives 'Argument list too long' on osx

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#3795]
*Description*:

Adding a new entry to `external_deps` of this [`pgv_cc_proto_library`](https://github.com/dio/envoy/blob/da90483bf543072f88f747f55691289d815e6c6f/api/bazel/api_build_system.bzl#L130-L134) in `api/bazel/api_build_system.bzl` gives 'Argument list too long' error on osx, but not on linux https://circleci.com/gh/envoyproxy/envoy/69111.

*Repro steps*:

1. Uncomment this [line](https://github.com/dio/envoy/blob/da90483bf543072f88f747f55691289d815e6c6f/api/bazel/api_build_system.bzl#L134).
2. `bazel build @envoy_api//envoy/...` on osx

*Logs*:

- https://circleci.com/gh/envoyproxy/envoy/69110
- https://circleci.com/api/v1.1/project/github/envoyproxy/envoy/69110/output/105/0?file=true

```
Action failed to execute: java.io.IOException: Cannot run program "/usr/bin/sandbox-exec" (in directory "/private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/sandbox/darwin-sandbox/1303/execroot/envoy"): error=7, Argument list too long
INFO: Elapsed time: 759.004s, Critical Path: 64.94s
```

**Comment by zuercher** [comment]
I did some more research on this, since the error seems to imply this is a problem with /usr/bin/env (and a coreutils replacement is available in homebrew). Forcing "genv" doesn't fix the problem, because this is the result of limit.h's ARG_MAX (c.f. http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html) being set to 262144. ARG_MAX affects exec so it's the exec statement in the command that triggers this problem.

In this case, our build attempts to `exec env - <ENV VARS> bazel-out/host/bin/external/com_google_protobuf/protoc <args>` with (in my case) 286954 bytes of args. The args are composed of 13 unique arguments with a huge amount of repetition:

```
   1 '--plugin=protoc-gen-validate=bazel-out/host/bin/external/com_lyft_protoc_gen_validate/darwin_amd64_stripped/protoc-gen-validate'
   1 '--validate_out=lang=cc:bazel-out/darwin-fastbuild/genfiles/external/envoy_api'
 289 -Ibazel-out/darwin-fastbuild/genfiles/external/com_github_gogo_protobuf
1445 -Ibazel-out/darwin-fastbuild/genfiles/external/com_google_protobuf/src
 289 -Ibazel-out/darwin-fastbuild/genfiles/external/com_lyft_protoc_gen_validate
 289 -Ibazel-out/darwin-fastbuild/genfiles/external/envoy_api
 578 -Ibazel-out/darwin-fastbuild/genfiles/external/googleapis
 289 -Iexternal/com_github_gogo_protobuf
1445 -Iexternal/com_google_protobuf/src
 289 -Iexternal/com_lyft_protoc_gen_validate
 289 -Iexternal/envoy_api
 578 -Iexternal/googleapis
   1 external/envoy_api/envoy/admin/v2alpha/config_dump.proto
```

**Comment by wrowe** [comment]
This remains an issue on Windows, with a much smaller character limitation than OS/X.

The protoc utility allows us to pass an @argsfile input reference, just as the compiler and linker support. It appears even that Bazel's invocation of the protoc generator in the built-in rules uses this construct, so it should be possible to extend Envoy's build to support this.

We are unable to unwind the dependency chain to //test/common/router:config_impl_test_lib and pass a tags=["skip_on_windows"] sentinel. While the api_proto_library invoked by the envoy_proto_libary supports the tags=[] argument to native.protoc_library, the additional steps pgv_cc_proto_library, api_py_proto_library, and native.alias calls will not accept tags to avoid compilation.

Until one issue or the other is addressed, it isn't possible to get Envoy on Windows integrated for CI running the appropriate //test/... steps.

**Comment by wrowe** [comment]
This remains an issue on Windows.
