### ISSUE TITLE
status code 0 appears in envoy ingress access log

### ISSUE THREAD

**Issue by jinuxstyle** [envoyproxy/envoy#3798]
Hello,

We found some envoy ingress log with status code 0, and it appears at the rate of around 1%. A piece of logs are shown in following picture.

![image](https://user-images.githubusercontent.com/4818028/42365113-23d42236-8130-11e8-9bd2-ca3e98e66300.png)

Could you share some insights on this?

And any advise on how to debug this kind of issue?

Thanks

**Comment by dio** [comment]
@rgs1 probably has insights on this.
 
https://envoyproxy.slack.com/archives/C78HA81DH/p1530051956000217

**Comment by rgs1** [comment]
We have them in our logs too, but at a much much lower rate. Havden't dug into it yet though.

**Comment by mattklein123** [comment]
See the documentation in https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#configuration specifically about %RESPONSE_CODE%

**Comment by rgs1** [comment]
@mattklein123 ah, thanks!

**Comment by jinuxstyle** [comment]
We have found the reason why envoy reported status code 0 in our case:

We have following service access flow:

client -> nginx -> envoy -> service

We have the nginx set a timeout for the requests, when the service takes longer time than the timeout, then nginx closes the connection to envoy due to timeout, so the envoy could not send back the response to client. Thus envoy reports the status code 0 in ingress access log.

**Comment by sjatlyft** [comment]
Curious, as I am investigating access logs for security detection, shouldn't the proper response code be 408?
