### ISSUE TITLE
Async Kubernetes resolver

### ISSUE THREAD

**Issue by Bplotka** [envoyproxy/envoy#3799]
[Feature Request / Design proposal]

*Description*:
Envoy `Cluster` configuration seems to have a placeholder for custom resolvers.
 [`SockerAddress.ResolverName`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto#envoy-api-field-core-socketaddress-resolver-name). We would like to propose "Kubernetes Resolver" similar to this: https://github.com/Bplotka/go-k8sresolver but in C++ and available for envoy through `SocketAddress.ResolverRname`.

I added "Async" word in title, because I think it is must-have to use it with `STRICT_DNS` or `LOGICAL_DNS` and I can see pending issue to block async custom resolvers: https://github.com/envoyproxy/envoy/issues/3553 instead of actually define async hooks for `Resolver` interface.

So, currently I see 2 major unknowns:
- `Resolver` interface is limited to sync resolution only. (As an outcome `LOGICAL_DNS` and `STRICT_DNS` cannot (?) use it right now)
-  Such resolver requires certain auth against Kube API. Either additional configuration or basing on envvars would be required to use such resolver. 

*Relevant Links*:
[Short discussion on slack](https://envoyproxy.slack.com/archives/C78M4KW76/p1530832645000238)
[Issue to block async custom resolvers](https://github.com/envoyproxy/envoy/issues/3553)

Any ideas how to allow this? Would you be ok to add such extremely useful Kubernetes integration that allows to completely avoid DNS? 
Or maybe the correct way is to use some control plane that does Kuberenetes Resolution and inject IP, port to `STRICT` Cluster discovery? 

BTW, thanks for Envoy! Such a good work!

**Comment by htuch** [comment]
See also the trailing discussion in https://github.com/envoyproxy/envoy/issues/1477. I think we should ideally make the address resolvers async (and I have some vague notion that we could make at least strict DNS an implementation detail of address resolvers rather than being its own cluster type).

**Comment by mattklein123** [comment]
I agree that it would be nice to make an async resolver. With that said, I'm not sure we want to support k8s directly in Envoy given the plethora of k8s Envoy integrations that are already available in the community.

**Comment by Bplotka** [comment]
hmm? Can you give some example what is the "state of the art" of solving this use case using envoy? 

Apart from running whole Istio and Ambassador (:

**Comment by mattklein123** [comment]
Rotor from turbine labs would be a good option. You could also run just Pilot from Istio. There is also Contour from Heptio, Gloo from solo.io, and probably others at this point.

**Comment by Bplotka** [comment]
Thanks for directions! I think you can open new issue for async resolver as a separate thing. I am closing this one. Thanks for feedback! 

Awesome work with Envoy. (:
