### ISSUE TITLE
HttpIntegrationTest methods should time out instead of waiting forever

### ISSUE THREAD

**Issue by mkbehr** [envoyproxy/envoy#3809]
The integration test framework makes it hard to send requests that might, e.g., be rejected by a decoder filter. HttpIntegrationTest::waitForNextUpstreamRequest will happily spin forever in that case. That method and similar ones should time out instead.

**Comment by mattklein123** [comment]
I don't think we should generically timeout in all cases, as that will introduce timing issues in tests. Feel free to add a variant that times out if it helps you.

**Comment by alyssawilk** [comment]
I think a blanket change from codec_client_->waitForDisconnect(); <-- hang forever to

ASSERT_TRUE(codec_client_->waitForDisconnect()); <-- 5s timeout
would be a net win.  We'd have to do auditing to make sure subfunctions also exited correctly but if we used ABSL_MUST_USE_RESULT we could verify at compile time we didn't miss any.

**Comment by mattklein123** [comment]
@alyssawilk agreed, I just don't want to rely on timeouts generically.

**Comment by mkbehr** [comment]
Would it work to time out by default but with an optional argument to not time out, or do you mean something else by "generically"?

**Comment by mattklein123** [comment]
What I'm saying is that I don't want the default behavior to be that timeouts somehow lead to tests passing. What @alyssawilk has proposed (timeout and fail) I agree it much better than hang, but that still leaves the default as timeout/fail vs. timeout and maybe pass. I think it's fine for the test writer to be able to opt-in to timeout and not fail in specific cases where that makes sense.

**Comment by alyssawilk** [comment]
Do you have any concrete examples of where you think it makes more sense to time the whole test out rather than fast-fail?  Or perhaps we can give the ABSL_MUST_USE_RESULT variant a try and see if there's any corner cases where an infinite timeout makes sense.

**Comment by mkbehr** [comment]
ABSL_MUST_USE_RESULT will break all the existing uses for anything that returns void but it should prevent the scenario where the test ignores a timeout and passes when it should fail. That scenario could still happen if a test calls something that returns a pointer like sendRequestAndWaitForResponse, stores it, and then doesn't try to dereference it in some branch, but I'd expect that to be a pretty rare case.

**Comment by mkbehr** [comment]
Which is to say, if I'm understanding @mattklein123 right, there's the concern that we add the interface for

`ASSERT_TRUE(codec_client_->waitForDisconnect());  // 5s timeout`

but somebody accidentally writes

`codec_client_->waitForDisconnect();  // Now this can time out and the test won't fail`

but if waitForDisconnect is ABSL_MUST_USE_RESULT then the second example there won't compile.

**Comment by mattklein123** [comment]
Yes exactly that's my concern that I want to prevent.

**Comment by mattklein123** [comment]
Done
