### ISSUE TITLE
Support mutable metadata for endpoints 

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3810]
This is a follow-up for #3803. In our clusters, metadata for endpoints mutate as we do deploys (e.g.: version). Given how we implement our EDS service, a removal might be missed so we need support for mutable metadata. Also, a removal isn't always desirable because it might be too expensive, especially if it triggers a drain.

This issue is to explore support for mutable metadata.

**Comment by htuch** [comment]
You'll need to ensure that `BaseDynamicClusterImpl::updateDynamicHostList` returns true to have it do the LB rebuild that is required when subset information changes. I think this might be enough for what you need, but will defer to @zuercher on how the subset LB updates happen.

**Comment by rgs1** [comment]
@htuch yup — testing exactly that. Thanks!
