### ISSUE TITLE
Support TLS session resumption when originating TLS connections

### ISSUE THREAD

**Issue by julia-stripe** [envoyproxy/envoy#3817]
**Issue Template**

Envoy supports TLS session resumption when serving TLS connections, but not when originating them.

*Description*:

When Envoy serves TLS requests, it supports TLS session resumption. However, Envoy **clients** do not appear to support TLS session resumption. (unless I'm misinterpreting what I'm seeing in Wireshark, which is possible! If Envoy actually does support this I'd love to know how to enable it.)

This is causing a problem for us in our production use of Envoy in cases where we have a few thousand Envoy clients connecting to the same TLS Envoy server to do healthchecks. What happens is:

* it's very expensive to do TLS handshakes, so many of the TLS handshakes time out
* once a client does succeed in establishing a TLS connection, that connection will later time out and be closed (because the server is too busy doing other TLS handshakes and is unable to serve healthchecks in a timely fashion)
* when the client tries to reestablish the TLS connection, it needs to start from scratch
* repeat forever. this process continuously uses 100% of the server's CPU doing TLS handshakes and we never get into a state where every client has established a TLS connection to the server

The Envoy servers we're running are m3.larges, and while those aren't huge, it does seem like it should be possible to establish a few thousand TLS connections to an m3.large within a few minutes and do healthchecks at a low rate (1/minute).

**Comment by mattklein123** [comment]
@PiotrSikora can you advise here?

**Comment by PiotrSikora** [comment]
This is on my TODO list, but yeah, Envoy currently doesn't support session resumption when acting as a client. I don't have any ETA for it either.

cc @ggreenway

**Comment by julia-stripe** [comment]
@PiotrSikora how much work do you think it would be to implement if we wanted to contribute it?

**Comment by PiotrSikora** [comment]
@julia-stripe did you start working on this, by any chance? If not, I'll work on it this week.

**Comment by julia-stripe** [comment]
not yet! i don't think I'll get to it this week so that would be amazing.

**Comment by amukherj1** [comment]
Given that this change #4791 was merged way back, should this issue still be open?

**Comment by amukherj1** [comment]
Given that this change #4791 was merged way back, should this issue still be open? @PiotrSikora @mattklein123

**Comment by PiotrSikora** [comment]
This should be closed, thanks @amukherj1!

Fixed via #4791.

**Comment by amukherj1** [comment]
One minor point in addition is that the documentation at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl states:

    Session resumption: Server connections support resuming previous sessions via TLS session tickets (see RFC 5077). 
    Resumption can be performed across hot restarts and between parallel Envoy instances (typically useful in a front proxy configuration).

The statement *typically useful in a front proxy configuration* is a bit misleading. This is also useful in east-west traffic that requires TLS origination/termination.
