### ISSUE TITLE
improve syscall API wrappers

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#3819]
Per discussion in #3813 it'd be good if the doRead call didn't latch errno several levels away from where the actual syscall was performed.  We should change the APIs to return {rc, errnno} in some form to better futureproof in case the intermediate function calls add their own errno-corrupting debug logging.

We could also get really fancy and insist that errno is latched via fix_format fixes, as also discussed there.

**Comment by mattklein123** [comment]
@venilnoronha go for it!

**Comment by venilnoronha** [comment]
@PiotrSikora that's next in the plan of action. Briefly, I wanted to start off one level higher to keep the PRs smaller.

**Comment by alyssawilk** [comment]
I think the final fix was solid, and we forgot to close this one out.  Thanks!
