### ISSUE TITLE
debug envoy on MacOS with lldb/gdb

### ISSUE THREAD

**Issue by neicunlideyu** [envoyproxy/envoy#3826]
I want to debug envoy on MacOS, so I take following actions:
1.  I build envoy binary with command `bazel build  -c dbg --apple_generate_dsym //source/exe:envoy-static`
2.  `lldb -p {pidOfEnvoy}`,  set breakpoint `breakpoint set --name onConnectionEvent`

but the source code doesn't show when break point is hit. Is this supported on MacOS with bazel build? If supported, what option should I add to build phrase?

What's more, can I debug envoy with Xcode?

**Comment by mattklein123** [comment]
@zuercher ?

**Comment by zuercher** [comment]
Last I looked bazel does not preserve the dsym files for c++ code and without those files lldb cannot do source level debugging.

I expect using Xcode would have the same problem, but I've not tried.

There's a workaround suggested in bazelbuild/bazel#2537. I don't know if anyone's tried it, though I plan to give it a whirl the next time I want a debugger.

**Comment by drao9** [comment]
https://medium.com/@dirao/debugging-envoyproxy-on-osx-a3ebe87dc916

**Comment by acpower7** [comment]
^thanks, but doesn't work for latest version of babel (0.23)
