### ISSUE TITLE
data-plane-api proto definitions cause name conflict in c#

### ISSUE THREAD

**Issue by skwasiborski** [envoyproxy/envoy#3827]
Api definitions for data plane api contain messages that cause naming conflict when used by protoc to build c# classes. There are two instances of the problem:

1. pacakge: envoy.api.v2 contains message Cluster which ends up being class Envoy.Api.V2.Cluster at the same time there exists a package: envoy.api.v2.cluster which ends up as namespace Envoy.Api.V2.Cluster. This is not allowed in c# and causes compilation error.
2. The same problem occurs with package: envoy.api.v2 message: listener and package: envoy.api.v2.listener

This can be easily solved by setting "option csharp_namespace = ..." on the envoy.api.v2.cluster/listener packages.

If it is ok I can make a PR with this change - as far as I know it will be transparent to all non c# users of the definitions.

**Comment by mattklein123** [comment]
@skwasiborski sure please just do a PR. Thank you!
