### ISSUE TITLE
health_check: request header formatting does not use dynamic request info

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#3835]
*Title*: *health_check: request header formatting does not use dynamic request info*

*Description*:
Using the [command operators](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#custom-request-response-headers) in [http_health_check.request_headers_to_add](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#core-healthcheck-httphealthcheck) will not work as intended. Specifically, for `%UPSTREAM_METADATA()%`, the lookup will fail and be replaced with an empty string.

For `%DOWNSTREAM_LOCAL_ADDRESS%` it segfaults... but this one (and the other DOWNSTREAM ones) doesn't actually make sense because there is no downstream for healthchecks (or the downstream is envoy itself?)

The problem boils down to the fact that the `RequestInfo` object is never populated with the current request info. https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_checker_impl.cc#L159

(I haven't confirmed this, but based on the reading of the code `%START_TIME%` will also be wrong. It will always be the time that the REQUEST_INFO object was constructed)

*Repro steps*:
The simplest repro is to add the header to the health checker tests:

```diff
diff --git a/test/common/upstream/health_checker_impl_test.cc b/test/common/upstream/health_checker_impl_test.cc
index dc041e7..a8befdc 100644
--- a/test/common/upstream/health_checker_impl_test.cc
+++ b/test/common/upstream/health_checker_impl_test.cc
@@ -290,6 +290,9 @@ public:
             key: user-agent
             value: CoolEnvoy/HC
           append: false
+        - header:
+            key: downstream-local-address
+            value: "%DOWNSTREAM_LOCAL_ADDRESS%"
     )EOF";

     health_checker_.reset(new TestHttpHealthCheckerImpl(*cluster_, parseHealthCheckFromV2Yaml(yaml),
```

A more realistic repro is to use `UPSTREAM_METADATA` with EDS endpoints that actually have metadata.

**Comment by mattklein123** [comment]
Yeah I think we can do better here pretty easily. Marking bug/help wanted.

**Comment by dio** [comment]
Have a rough idea on fixing this as suggested by the title, i.e. 
1. Construct `RequestInfo` object and set `onUpstreamHostSelected()` whenever `onInterval` is called.  
2. Handle `DOWNSTREAM_*`by checking if `request_info.downstreamLocalAddress()` is `nullptr` then return empty string.

However I find it challenging to mock host `metadata()` call to return metadata object to test the `UPSTREAM_METADATA` header formatter for health check call.
