### ISSUE TITLE
rolling update with envoy

### ISSUE THREAD

**Issue by dnivra26** [envoyproxy/envoy#3860]
*Title*: *What is the best way to do a rolling update with envoy?*

*Description*:
We have envoy setup as a side car container to each pod in our services. Now whenever there is a config change for envoy (configmap change) and we do a helm update.
We see a spike in 503s and then eventually it goes away. 
Before envoy refreshes it set of hosts(dns_refresh_rate 5s), does it still send requests to the pods being terminated or already terminated? If so, how to cleanly do rolling update when there is a config change?

**Comment by rshriram** [comment]
You could play around with drain times but YMMV based on the types of clients (long running vs short lived connections). Alternatively, look at using the XDS APIs to update state programmatically.
