### ISSUE TITLE
Add datadog tracing driver to envoy

### ISSUE THREAD

**Issue by cgilmour** [envoyproxy/envoy#3861]
I'm Caleb, from Datadog's APM team. We've been looking at adding distributed tracing to the proxy
applications used internally and by our customers.

We have already developed a [plugin](https://github.com/DataDog/dd-opentracing-cpp/blob/46edff8f2f5483e4774b299bdcf683720ac95c6d/examples/envoy-tracing/front-envoy.yaml#L61-L68) that works with Envoy based on the existing `dynamic.ot` tracing option, but find it a bit limiting.
Additional plugin steps are a bit inconvenient for users, and even more difficult for things that wrap a prebuilt envoy binary in a container image (eg: istio).

Would you be open to a contribution that adds datadog's tracer as a direct option in envoy, alongside the existing zipkin and lightstep tracers?

We have reviewed the _Envoy extension policy_ document and understand the expectations for the initial submission and ongoing maintenance.

**Comment by objectiser** [comment]
No objections although would be interested to hear in what way the dynamic ot approach was limiting in case it could be enhanced to be more generally useful?

**Comment by rnburn** [comment]
I expect the main problem is making the tracer plugins available on the docker images that build on Envoy like Istio.

There's a similar issue with [ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/third-party-addons/opentracing.md) which only supports Zipkin and Jaeger right now, but where we'd also like to add arbitrary vendor support.

**Comment by cgilmour** [comment]
Thanks for the prompt and supportive response, @mattklein123 

@rnburn that's really good to know up-front. I'll dig into that implementation and keep those requirements for tracers in mind before making a submission.

@objectiser the case that Ryan mentioned is spot on.
I don't have suggestions for related improvements / enhancements yet, but that may come up later on!

**Comment by tedsuo** [comment]
@cgilmour in the long run, it would be great to solve the plugin/driver packaging problem. Baking in tracers in doesn't really scale. (especially when tracers and envoys may want to version independently from each other).

There's no reason we can't deploy plugins as separate tiny images, and link them in, except currently there is no guidance from docker as to how to do it. IMHO, half the point of istio and other platforms is to manage this kind of glue.

**Comment by cgilmour** [comment]
Hi, I've been actively working on this, and have changes almost ready to PR.
(We want to test internally, and it'll need a rebase before submitting.)

I don't have a solution for the plugin/driver packaging problem that was mentioned, but if that's something that happens in the future, feel free to @ me on issues or PRs and I'll be able to keep our part of it up-to-date with that.
