### ISSUE TITLE
ext_authz filter is messing up "content_length" header

### ISSUE THREAD

**Issue by michalholecek** [envoyproxy/envoy#3865]
When envoy receives a request with body length of e.g. 5, the req. headers are:
```
[2018-07-16 15:59:23.776][22489][debug][http] source/common/http/conn_manager_impl.cc:455] [C0][S3713373574215004266] request headers complete (end_stream=false):
':authority', '0.0.0.0:777'
':path', '/'
':method', 'POST'
'user-agent', 'curl/7.52.1'
'accept', '*/*'
'content-length', '5'
'content-type', 'application/x-www-form-urlencoded'
```
then it sends this request to the ext_authz filter without body so the "content_length" header is supposed to be 0. But instead of 0 envoy sets it to "0,5" (0, original content length). This causes any http server to respond "400 Bad request".
Here are the headers from envoy debug log: 
```
[2018-07-16 15:59:23.776][22489][debug][router] source/common/router/router.cc:304] [C0][S18143179754686772766] router decoding headers:
':method', 'POST'
':path', '/'
':authority', '0.0.0.0:777'
':scheme', 'http'
'content-length', '0,5'
'x-request-id', 'f6238991-b127-4cec-aadd-0ef8a35e3508'
'x-forwarded-proto', 'http'
'accept', '*/*'
'content-type', 'application/x-www-form-urlencoded'
'user-agent', 'curl/7.52.1'
'x-envoy-internal', 'true'
'x-forwarded-for', '172.17.0.1'
'x-envoy-expected-rq-timeout-ms', '200'
```
these are received by external auth service.

**Comment by mattklein123** [comment]
cc @saumoh @gsagula

**Comment by gsagula** [comment]
@michalholecek  Thanks for reporting it. I will take a look at and get back to you.

**Comment by gsagula** [comment]
`envoy//test/integration:websocket_integration_test TIMEOUT` seems to be not related to my changes. I will retry it later.
