### ISSUE TITLE
Exit on xDS Permission Denied Errors

### ISSUE THREAD

**Issue by kmyerson** [envoyproxy/envoy#3870]
Exit on xDS Permission Denied Errors

If the management server responds to a DiscoveryRequest with a gRPC error code, Envoy will retry the request. For some error codes, a retry might not make sense.

We're interested in having Envoy exit if the management server returns an Unauthenticated or PermissionDenied error. This would allow a wrapper layer/process around Envoy to reset credentials, for example by rebuilding the bootstrap config, and then restart Envoy to try again.

Whether this behavior is active would need to be configurable, with the feature being off by default.

@htuch

**Comment by mattklein123** [comment]
Hmm. I'm not sure how I feel about this. Is this opening a can of worms? Are there other cases in which someone might ask to exit? I'm mainly wondering if the wrapper/process monitor could be looking at stats during startup and tear down envoy and restart it if it sees this?

**Comment by kmyerson** [comment]
Thanks for the suggestion Matt. I chatted with @mrice32 about it and we think watching stats should be a reasonable solution, although we might want to build a mechanism to programmatically access stats, similar to #3674 .
