### ISSUE TITLE
Question: is it possible to build envoy-filter-example using envoyproxy/envoy-build ?

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#3875]
Envoy Filter Example: https://github.com/envoyproxy/envoy-filter-example
Envoy Docker Build: https://www.envoyproxy.io/docs/envoy/latest/install/sandboxes/local_docker_build

**Comment by ronenschafferibm** [comment]
I managed to build envoy-filter-example by following these steps:

1. Update envoy submodule as done in the [README](https://github.com/envoyproxy/envoy-filter-example/blob/master/README.md)
```
git submodule update --init
```

2. Replace line 5 in [`envoy-filter-example/envoy/ci/run_envoy_docker.sh`](https://github.com/envoyproxy/envoy/blob/5ec8b37da9de5893c04f75bbf2820014c62ea529/ci/run_envoy_docker.sh#L5):
```
. ci/envoy_build_sha.sh
```
with:
```
SCRIPT_DIR_PATH="`dirname \"$0\"`"
. "$SCRIPT_DIR_PATH"/envoy_build_sha.sh
```

3. Build the example with docker by running the script `'./ci/do_ci.sh build'` inside docker:
```
$ pwd
~/envoyproxy/envoy-filter-example
$ ./envoy/ci/run_envoy_docker.sh './ci/do_ci.sh build'
```
alternatively, one can run `bazel` directly inside docker (instead of running the script):
```
$ ./envoy/ci/run_envoy_docker.sh 'bazel build //:envoy'
```


4. Run `echo2_integration_test`
```
$ ./envoy/ci/run_envoy_docker.sh './ci/do_ci.sh test'

==================== Test output for //:echo2_integration_test:
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
WARNING: Perftools heap leak checker is active -- Performance may suffer
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from IpVersions/Echo2IntegrationTest
[ RUN      ] IpVersions/Echo2IntegrationTest.Echo/0
[       OK ] IpVersions/Echo2IntegrationTest.Echo/0 (74 ms)
[----------] 1 test from IpVersions/Echo2IntegrationTest (74 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (74 ms total)
[  PASSED  ] 1 test.
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 8348 reachable heap objects of 2297124 bytes
================================================================================
//:echo2_integration_test                                       (cached) PASSED in 0.7s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 2 total actions

```

**Comment by kuroneko25** [comment]
Just curious did you do anything to copy the binary out from the container at the end of the build?

**Comment by ronenschafferibm** [comment]
The `source` and `build` directories are shared with the container. At the end of the build, the binary is placed in one them. So I didn't need to copy it out from the container

**Comment by CalbeeMing0530** [comment]
> The `source` and `build` directories are shared with the container. At the end of the build, the binary is placed in one them. So I didn't need to copy it out from the container

According to your tutorial, there is no problem in building, but the compiled binary file cannot be found. We can learn from the run_envoy_docker.sh that the default binary file storage path is "/tmp/ envoy-docker-build/envoy/". After building successful The folder is not updated. Can you tell me where can I find the binary file?
