### ISSUE TITLE
assert in health checker causing crash

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3877]
Started seeing this with a build from master from 5 days ago (when i picked https://github.com/envoyproxy/envoy/commit/e71850074e1779ab84838006b8c559722eaae29e):

```
[2018-07-17 01:47:01.484][13434][critical][assert] external/envoy/source/common/upstream/health_checker_impl.cc:119] assert failure: !response_headers_.    
```

Still no repro, saw it twice now.

**Comment by rgs1** [comment]
Probably a false positive, given it was with a `fastbuild`, so closing for now.

**Comment by BenPope** [comment]
I've seen this too, with envoy v1.7.1.  I also have an ASAN trace, which may be related:
```c++

**Comment by mattklein123** [comment]
Moving over to bug/help wanted. Thanks for the call stack @BenPope
