### ISSUE TITLE
Envoy sometimes returns response body to HEAD requests

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#3932]
*Description*:
RFC 7231 says that servers should not respond with a body to HEAD requests, but Envoy does

*Repro steps*:
`curl -XHEAD <envoy_url>` when it has no healthy upstreams, you'll see a `upstream connect error or disconnect/reset before headers` response body.

Note that using `--head` instead of `-XHEAD` in curl omits the response body but shows a `Excess found in a non pipelined read: excess = 57 url = /foo (zero-length body)` warning.

This is a minor issue but causes some surprising noise in our deploy system's logs as it performs health checks with HEAD while the service Envoy is deployed alongside is down.

Envoy version: c92a3017017dfa31241dec13dc6a1479090318d0/1.8.0-dev/Clean/RELEASE

**Comment by zyfjeff** [comment]
I can start this one,  mainly for the `Utility::sendLocalReply` modification

**Comment by dio** [comment]
I remember had some difficulties on making "expect true" for `request->complete()` (on test) to work for `HEAD` requests when the body is empty.

**Comment by zyfjeff** [comment]
@dio code implementation and integration testing can be submitted separately?

**Comment by dio** [comment]
@zyfjeff as long as the introduced changes don't break the integration tests, probably that is fine.

**Comment by zyfjeff** [comment]
@dio  thanks, I'm going to make a pr

**Comment by zyfjeff** [comment]
@dio 
When I was doing integration testing, it seemed that I had encountered the problem you said, response->complete() could not make "expect true"  #3985 

Do you know how to solve it?

**Comment by dio** [comment]
@zyfjeff no, not yet. Following #3985, guess you are already in the right direction and you have @mattklein123 and @alyssawilk with you 🙂
