### ISSUE TITLE
Upstream request stats don't add up

### ISSUE THREAD

**Issue by frankh** [envoyproxy/envoy#3943]
*Description*:

The cluster upstream request statistics broken down by http status code don't add up to the total.

when I go to `http://<envoy-admin>/admin/proxy/stats` I get:

```
...
cluster.service_primary.upstream_rq_200: 7713
cluster.service_primary.upstream_rq_2xx: 7713
cluster.service_primary.upstream_rq_304: 21
cluster.service_primary.upstream_rq_3xx: 21
cluster.service_primary.upstream_rq_403: 746
cluster.service_primary.upstream_rq_404: 734
cluster.service_primary.upstream_rq_4xx: 1480
cluster.service_primary.upstream_rq_500: 2573
cluster.service_primary.upstream_rq_5xx: 2573
...
cluster.service_primary.upstream_rq_total: 12122
...
```

Adding up rq_5xx, rq_4xx, rq_3xx, and rq_2xx gets me 11787, however rq_total is 12122.

There's no obvious stat for where the missing 335 have gone, the closest I can find is "upstream_cx_destroy_local_with_active_rq: 338"

I am shadowing requests, and the shadowed requests *do* add up, which makes it very difficult to compare the number of errors between the primary and shadow clusters

*Admin and Stats Output*:
Full stats output: https://gist.github.com/frankh/c7e6623ce29b300eddd9e8c0bfe4524c

*Config*:
I don't believe there's anything relevant in the envoy config, but will post sanitised version if requested.

**Comment by ramaraochavali** [comment]
@mattklein123  probably this is same as #3950 and can be closed via https://github.com/envoyproxy/envoy/pull/4055 I guess.

**Comment by mattklein123** [comment]
It might be the same, but also that rq_total doean't include requests that don't result an an HTTP response code. See also https://github.com/envoyproxy/envoy/pull/3995. Anyway still closing. :)
