### ISSUE TITLE
Stats - upstream_rq_5xx don't add up with 2xx and rq_total

### ISSUE THREAD

**Issue by tak2siva** [envoyproxy/envoy#3950]
Total
>cluster.external_app1_http.upstream_rq_total: 37988

2xx
>cluster.external_app1_http.upstream_rq_200: 37981
>cluster.external_app1_http.upstream_rq_2xx: 37981

5xx
>cluster.external_app1_http.upstream_rq_503: 7303
>cluster.external_app1_http.upstream_rq_5xx: 7303

Retries
>cluster.external_app1_http.upstream_rq_retry: 0
>cluster.external_app1_http.upstream_rq_retry_overflow: 0
>cluster.external_app1_http.upstream_rq_retry_success: 0

There are around 7k `5xx` and 0 `retries`.
So how come the `2xx` count is pretty much same as `rq_total` ??

Shouldn't it be like `rq_total` - `5xx` (i.e) 37k - 7k ~= 30k `2xx`  ?
How are those 7k `5xx` not subtracted in `2xx`

[Full Stats Link](https://gist.github.com/tak2siva/25a9bc1c0139a5220a82e663a6021224)

--------------------------------------------------------------------------------------------------
**Additional Info:**

I have a setup like this in k8s

       ( front proxy ) ->       [ Envoy Sidecar ]   ->    [   Envoy Sidecar   ]
                                  [ Gateway]                [external_app_1]                          

Above is the log for `Gateway Envoy Sidecar`

**Comment by mattklein123** [comment]
Hmm. This seems odd. Not sure off the top of my head but will take a look at the full stats dump later.

**Comment by danielhochman** [comment]
What revision of Envoy are you running @tak2siva?
