### ISSUE TITLE
Add capability to skip stat-name truncation for not-hot-restart case

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#3965]
*Description*:
>Limited stat-name sizes are needed in the hot-restart case to allow friendlier allocation in fixed-size shared-memory block. They probably just get in the way for the non-hot-restart case. Note that when heap-stats are used as overflow for shared-mem stats, they should be truncated the same way.

**Comment by ambuc** [comment]
@htuch You can assign this to me.

**Comment by ambuc** [comment]
@jmarantz @htuch Let's close this issue as unwanted -- as-is, heap-allocated stats don't truncate. This issue would require us to flip that behavior yet again, truncate heap-allocated stats by default, and then require a CLI flag to not truncate stat names.
