### ISSUE TITLE
Inserting downstream trailers when upstream has no trailers

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#3966]
I was playing around with a filter that bridge grpc -> http/1.1 (opposite direction to the bridge that already exists in envoy) and I couldn't figure out how to insert trailers into a downstream h/2 response when the upstream response is h/1.1. It seems like the `encodeTrailers` cb is not invoked (presumably because the h/1.1 response doesn't have any trailers). 

Hopefully I'm missing something and this is already doable. If not, would it be reasonable to add this functionality?

**Comment by mattklein123** [comment]
Unfortunately I don't think this is possible today. Have a look how `addEncodedData()` is implemented. We would want to add something similar along the lines of `addEncodedTrailers()`. I don't think it would be that hard to implement.
