### ISSUE TITLE
Add a RBAC TCP filter

### ISSUE THREAD

**Issue by yangminzhu** [envoyproxy/envoy#3993]
*Title*: Add a RBAC TCP filter

*Description*:
Add a RBAC (Role-Based-Access-Control) TCP filter. This is needed to support authorization for non-HTTP protocol.

*Relevant Links*:
The RBAC HTTP filter is added in #3455 

some open questions:
We could either add a new config proto for the TCP filter that includes fields only available in TCP or just reuse the existing [config proto](https://github.com/envoyproxy/envoy/blob/028387a3b0746deaf011ea50104692dfbb8b8d2f/api/envoy/config/rbac/v2alpha/rbac.proto#L48) introduced for HTTP filter, and only a subset of the fields are supported in this case.
I prefer the second option but not sure if there is any preference in Envoy when a filter is implemented for both HTTP and TCP.

/cc @liminw @lizan @rodaine @mattklein123

**Comment by lizan** [comment]
+1 to reuse existing [config proto](https://github.com/envoyproxy/envoy/blob/028387a3b0746deaf011ea50104692dfbb8b8d2f/api/envoy/config/rbac/v2alpha/rbac.proto#L48), which is designed to be generic IIRC (so it wasn't scoped in http package). Of course some of its field (e.g. header matcher) won't be supported in TCP.

**Comment by mattklein123** [comment]
+1 to reuse and we can make the HTTP specific things empty. We do this elsewhere in cases like access logging and a few other places.

**Comment by liminw** [comment]
+1 to reuse. The [rbac proto](https://github.com/envoyproxy/envoy/blob/028387a3b0746deaf011ea50104692dfbb8b8d2f/api/envoy/config/rbac/v2alpha/rbac.proto#L48) is designed to be generic. Also the [rbac engine implementation](https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/common/rbac) is designed to be shared for different filter implementations.
