### ISSUE TITLE
Kubernetes service account authentication - Token expired error

### ISSUE THREAD

**Issue by vvinod1310** [envoyproxy/envoy#3996]
*Title*: *Kubernetes service account authentication*

*Description*:
> I am trying to validate the JWT token of a Kubernetes service account using Envoy jwt_authn http filter and Envoy throws a JwtExpired status error. 

Kubernetes service account tokens are non-expiring tokens and don't have an expiry field defined and this defaults to 0 while parsing the JWT token. However the following piece of code while validating the token throws an error with JwtExpired status. 

https://github.com/envoyproxy/envoy/blob/cc4845b01f71f3e12b359d1ce099a22d4fe61526/source/extensions/filters/http/jwt_authn/authenticator.cc

`  if (jwt_.exp_ < unix_timestamp) {
    doneWithStatus(Status::JwtExpired);
    return;
  }`

Could this code rather be the following to cater to kubernetes service accounts?

`  if (jwt_.exp_> 0 && jwt_.exp_ < unix_timestamp) {
    doneWithStatus(Status::JwtExpired);
    return;
  }`

Please clarify.

Many thanks.

**Comment by qiwzhang** [comment]
@vvinod1310 Yes,  we can change the code as you described.   Please file a PR for it. Thanks
