### ISSUE TITLE
IpVersions/EchoIntegrationTest.AddRemoveListener/IPv6 is flaky

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#3997]
*Description*:
on master 028387a3b0746deaf011ea50104692dfbb8b8d2f run:
`bazel test --runs_per_test=100 //test/integration:echo_integration_test`

will result 2 runs out of 100 `TIMEOUT`, with `"-l trace"` got 8 out of 100.

**Comment by mattklein123** [comment]
I've seen this also on my own machine.

**Comment by zuercher** [comment]
I poke around this a bit yesterday evening and it seems to be a race in the AddRemoveListenerTest between the RawConnectionDriver making a connect attempt and the actual listener socket being closed.

It seems like sometimes the listener socket close concurrently with the RawConnectionDriver's connect attempt. The RawConnectionDriver's ConnectionImpl sees a successful connection (write event triggers onWriteReady and getsockopt returns no error) and then writes the initial data. No further events occur and the RawConnectionDriver waits in Dispatcher::run until the test times out.

When the test passes, the connect either happens before or after the socket close which either leads to an immediate connect failure or a deferred one, and in both those cases the test terminates successfully.

**Comment by alyssawilk** [comment]
This was failing enough today I'd back disabling first and debugging later, if anyone is willing to own debug
