### ISSUE TITLE
Expose retries with trace tags and extra response info/logs

### ISSUE THREAD

**Issue by charliezgc** [envoyproxy/envoy#4048]
**Issue Template**

*Title*: Is there a way to know retries have occurred in an egress HTTP request?

*Description*:
>We are using a LUA script to generate custom trace reports for each ingress/egress HTTP requests and it would be very beneficial to capture the retry events in requests and put them in report. Does envoy already provide some features for this, such as a response header to indicate retry counts?

**Comment by ramaraochavali** [comment]
The following stats on the cluster that you are trying to hit should help you
upstream_rq_retry: 
upstream_rq_retry_overflow: 
upstream_rq_retry_success:

**Comment by mattklein123** [comment]
IIRC each retry would be shown in the upstream access logs, but I don't think we explicitly indicate that it is a retry today (though that would be useful).

**Comment by charliezgc** [comment]
Stats or logs won't be able to tie the retry indication to a request. We are trying to show retry activities in distributed tracing. The ideal case would be an entry in response header that says the request has been tried.

**Comment by mattklein123** [comment]
@charliezgc I agree and have thought about this also. I think that we should indicate retries both as tracing tags (including the retry number) as well as possibly in the extra response info work that @junr03 is working on. Will move this over to enhancement.

**Comment by mattklein123** [comment]
This was fixed. There are now retry trace tags.
