### ISSUE TITLE
Make official process for doing point releases

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4052]
1) Branch procedure
2) Make sure CI runs on branch
3) Make sure when branch is tagged, docker images, etc. get pushed.

**Comment by taion809** [comment]
I think there are some good ideas we could steal from some other projects.

For example:
- Istio :: https://github.com/istio/istio/blob/master/release/create_github_release.sh
- Kubernetes :: https://github.com/kubernetes/kubernetes/tree/master/build
- Etcd :: https://github.com/coreos/etcd/tree/master/scripts
- Jaeger :: https://github.com/jaegertracing/jaeger/tree/master/scripts/travis

I think istio's release process seems to be the closest match.

**Comment by bndw** [comment]
Can someone help me understand why the `v1.7.1` tag didn't make it to Dockerhub? I don't see any code for skipping the publish if its a point release, AFAIK Circle gets the tag event and we run [docker_tag.sh](https://github.com/envoyproxy/envoy/blob/master/ci/docker_tag.sh)

**Comment by htuch** [comment]
@bndw this seems like something we should fix, given 1.7.1 was a security release. I'm going to next hop route to @ggreenway who is Envoy maintainer on-call this week, if this ends up being non-trivial one of the maintainers will pick it up.

**Comment by bndw** [comment]
@mattklein123 did you do anything different when creating the [v1.7.1 release](https://github.com/envoyproxy/envoy/releases/tag/v1.7.1) that would have caused it to not be picked up by CircleCI?

**Comment by mattklein123** [comment]
There was no v1.7.1 container built because the current process relies on a master build to have already created the container. We need to fix the tagging process to also do the build so it will work off a branch.

**Comment by bndw** [comment]
OK now this makes sense. `v1.7.1` was never brought into `master` but rather lives in [stable/v1.7.1](https://github.com/envoyproxy/envoy/tree/stable/v1.7.1) and the current [Docker publishing code](https://github.com/envoyproxy/envoy/blob/master/ci/docker_push.sh#L9-L15) only cares about `master`. 

If we enable Docker image publishing for branches other than `master`, here are a couple considerations
* We must have process in place to prevent history rewriting, squash and merging, etc, else we'll have orphaned Docker image tags in Dockerhub
* We should consider if we want to push images for _all_ branches or _some_. e.g. _should we only publish `master` and `stable/*` branches?_
* We should consider if including the branch name into the Docker tag is a good idea

**Comment by mattklein123** [comment]
@bndw I don't have a strong opinion here. Do you want to make a proposal based on what you think the community would most expect?

**Comment by mattklein123** [comment]
I just posted this to #envoy-users in Envoy slack. Please let me know if anyone has any feedback.

```
Hi Envoy users: I'm trying to finally fix our story around both 1) doing point releases and 2) making the official release docker images easier to find given poor searching on docker hub. This is related to https://github.com/envoyproxy/envoy/issues/4052. In the context of (2), I'm considering making 2 new hub repos here: https://cloud.docker.com/u/envoyproxy/repository/list, "envoy-tagged" and "envoy-alpine-tagged". We would switch our scripts to drop our tagged releases in these repos, as opposed to being mixed in with the master builds we do now. Any thoughts on this? I'm trying to break as few people as possible but make the tagged releases more discoverable. Thank you for your feedback!
```

**Comment by bndw** [comment]
A similar approach with two dockerhub repos, inspired by (2), could be as follows:

### envoyproxy/envoy
Images tagged for official Envoy releases. The `latest` tag points to the latest Envoy release.

Examples:
* `envoyproxy/envoy:v1.9`
* `envoyproxy/envoy:latest` -> `envoyproxy/envoy:v1.9`

### envoyproxy/envoy-dev
Images tagged with the GITSHA for every commit in master. The `latest` tag points to the HEAD of master

Examples:
* `envoyproxy/envoy:36f39c746eb7d03b762099b206403935b11972d8`
* `envoyproxy/envoy:latest` -> `envoyproxy/envoy:c24e26fda60096a68baccc6255c2ee083095b5a4`


I believe this approach would solve the main issue of _too many tagged images in dockerhub and we can't find anything_, while maintaining an intuitive Docker experience.

**Comment by mattklein123** [comment]
I hashed out ^ with @bndw in slack and this makes sense to me unless there are community objections. I will start working on this in parallel.
