### ISSUE TITLE
Is there a way to run envoy proxy on service fabric

### ISSUE THREAD

**Issue by tkumark** [envoyproxy/envoy#4058]
Is there a way to run envoy proxy on service fabric with windows cluster. I would like to use it as a reverse proxy. I have see similar Traefik https://github.com/jjcollinge/traefik-on-service-fabric. I would prefer to use envoy if possible

**Comment by mattklein123** [comment]
I think there is since MSFT announced Envoy on service fabric but I don't know the details: @vturecek ?
