### ISSUE TITLE
add the awesome blue-green deployment example to examples?

### ISSUE THREAD

**Issue by paulkarayan** [envoyproxy/envoy#4069]
**Issue Template**

*Title*: *shall I add the awesome blue-green deployment example to examples?*

*Description*:
I loved having the examples/"sandboxes" as I was getting started in understanding Envoy. 

Wanted to know if you'd like me to submit a new sandbox based on this killer writeup:
https://blog.turbinelabs.io/incremental-blue-green-deploys-fde90b0ebdab

I ask because among my crowd, this would be the biggest reason to move to using Envoy, so why not showcase it? 
Thanks.

**Comment by mattklein123** [comment]
@paulkarayan sure! More examples are great.
