### ISSUE TITLE
failed to build release binary using centos docker image

### ISSUE THREAD

**Issue by fengye87** [envoyproxy/envoy#4088]
I'm using the following command to build release binary (under Ubuntu 16.04):

```shell
git checkout v1.7.1
IMAGE_NAME=envoyproxy/envoy-build-centos ./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS=--copt=-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 ./ci/do_ci.sh bazel.release.server_only'
```

It failed with the following message constantly:

```
ERROR: /source/source/exe/BUILD:21:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1): envoy_cc_wrapper failed: error executing command 
  (cd /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/execroot/ci && \
  exec env - \
    PWD=/proc/self/cwd \
  /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/local_config_cc/extra_tools/envoy_cc_wrapper -o bazel-out/k8-opt/bin/source/exe/envoy-static -pthread '-Wl,--hash-style=gnu' -static-libstdc++ -static-libgcc -Wl,@bazel-out/k8-opt/genfiles/external/envoy/bazel/gnu_build_id.ldscript -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,@bazel-out/k8-opt/bin/source/exe/envoy-static-2.params)
collect2: error: ld returned 1 exit status
Target //source/exe:envoy-static failed to build
```

Could someone please help me out?

**Comment by PiotrSikora** [comment]
> ```
> git checkout v1.7.1
> IMAGE_NAME=envoyproxy/envoy-build-centos ./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS=--copt=-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 ./ci/do_ci.sh bazel.release.server_only'
> ```

That works fine for me, perhaps you're running out of disk space?

> I don't think the CentOS build image has been built in a while and it's possible it doesn't work for some reason. @ggreenway @lizan @PiotrSikora have looked at this recently.

Hence [my suggestion to drop it completely](https://github.com/envoyproxy/envoy/issues/3937).

**Comment by fengye87** [comment]
@PiotrSikora You're right, it works if I build it using an instance (I'm using aws EC2 instances) with a larger disk. Strange though, the error message didn't say anything about insufficient disk space.

Thank you for your help. I'm closing this issue.
