### ISSUE TITLE
Configurable retry codes

### ISSUE THREAD

**Issue by nicktrav** [envoyproxy/envoy#4103]
Internally, we have some clients that currently rely on some bespoke, legacy
retry behavior, whereby an HTTP/1.1 request can be retried on a 429 response
code. Ideally, we'd like to be able to move this retry logic out of the clients
and into the proxy-layer (i.e. Envoy) and still preserve the same behavior in
the event the server returns a 429.

Below are some options we'd like to pitch.

The first would involve adding a new field to the `RouteAction.RetryPolicy`
proto, `retryable_codes`, that would contain one or more HTTP response codes
(as integers) that are deemed retryable for the request.

In addition to this, we could create a new policy, say `"retryable-codes"`,
which expects either an accompanying request header (e.g.
`X-envoy-retryable-codes: 429,503`), or entry in the route configuration with
the retryable codes (as per above).

Another option, which is probably a non-starter, would be to add the specific
retry policy we need, `"retriable-429"`, but this feels a little too specific
and brittle.

Open to thoughts on how we might go about this. Thanks!

cc: @mpuncel @snowp

**Comment by snowp** [comment]
I'm a fan of the new header, it seems very flexible. Maybe also make the retry codes configurable in `RetryPolicy` so it can be configured through RDS without injecting headers?

**Comment by wjessop** [comment]
I love the idea of being able to specify response codes for retry behaviour:

```
retry_policy:
  retry_on: connect-failure
  retryable_codes: 503,418
  num_retries: 3
```

Or even just:

```
retry_policy:
  retry_on: connect-failure,503,418
  num_retries: 3
```

I don't fully understand the idea behind x-envoy-retryable-codes though. This was mentioned as being a request header, but it seems like the place the knowledge about wether something should be retryable or not should be the proxy or the upstream service.

As an aside, I also think getting rid of the gateway-error policy would be a good idea. IMO it's presence suggests that retrying non-503 errors is a safe thing to do.

**Comment by nicktrav** [comment]
I'll just chime in to mentioned we're still playing around with some ideas on this proposal and will hopefully offer up a patch soon. Feel free to assign this me for now.

> This was mentioned as being a request header, but it seems like the place the knowledge about wether something should be retryable or not should be the proxy or the upstream service.

@wjessop - totally agree with you _in principle_ here in that ideally retry configuration should live in the proxy layer. The reason we're proposing this is to attempt to provide feature parity between Envoy and our existing polyglot HTTP client libraries that all make extensive use of HTTP response codes to determine when to retry.

**Comment by wjessop** [comment]
Thanks for the reply @nicktrav. In this situation being able to have both methods of configuration would be great, though the ability to ignore re-try headers set from downstream of Envoy would be essential for us as I could see that having them enabled for public facing infra could be a DoS risk.

**Comment by dunjut** [comment]
I like this proposal. In our legacy systems, a custom proxy component replies http 570 indicating clients to retry another instance, when such components going into graceful upgrade process. 502 and 503 codes aren't used in this scenario because that would cause ambiguity.

**Comment by wjessop** [comment]
Did this get fixed? If not then it's still a valid issue and I don't think should be closed.
