### ISSUE TITLE
config_dump  returns output in random order

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4122]
Currently config_dump returns configs in random as they are defined as a [map](https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v2alpha/config_dump.proto#L30) in the proto. 
Is there any better way to to make output more deterministic via protos? Otherwise can we enforce some ordering while displaying?

**Comment by mattklein123** [comment]
IIRC there is a way to have proto do consistent serialization but I forget the details right now and I don't have time to go poking through the code (check proto utilities). @htuch do you remember?

**Comment by htuch** [comment]
I'm not sure this is possible in the presence of maps, e.g. https://gist.github.com/kchristidis/39c8b310fd9da43d515c4394c3cd9510. I think for this reason, maps should be avoided in our admin API endpoint output.

**Comment by mandarjog** [comment]
Maps keys can be optionally sorted to make diffing easier. The question is should this be done inside the config_dump endpoint or is it better left to the client that is consuming the output.

If it is not too expensive, determnistic json output is preferred.

**Comment by htuch** [comment]
@mandarjog where is the option to have proto do this? I don't see it in `JsonPrintOptions`.

**Comment by htuch** [comment]
Also, I'd question what value maps bring to any of our endpoint output, can someone articulate this?

**Comment by mattklein123** [comment]
I don't think the maps add any value. I would just switch them all to lists.

**Comment by ramaraochavali** [comment]
@mattklein123 assign this to me. I will work on it

**Comment by lizan** [comment]
Even we make them lists, the output won't be deterministic in many places where the config is dumped from `std::unordered_{set,map}` internally, (I'm sure routes are backed by unordered_set of pointers, not sure for others). It is still better the client consuming the output do a semantic comparison.

**Comment by htuch** [comment]
@lizan from the client perspective, this is unsatisfying, since we use these protos to serialize to JSON and output for humans. Humans aren't very good at comparing large unordered lists 💩

**Comment by lizan** [comment]
Right, so I would suggest use (or should we make one?) a client side tool to sort them instead of doing admin output, to keep admin endpoints lightweight.

**Comment by yangminzhu** [comment]
I'm trying to sync Istio with the latest envoy API, Is it always guaranteed that the [`bootstrap`, `listener`, `cluster`, `routes`] will always appear in the `Configs` in this specific order?

cc @liamawhite

**Comment by ramaraochavali** [comment]
@yangminzhu It is always guaranteed to return in the order [bootstrap, cluster, listener, routes] (lexicographic order) as documented [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/admin/v2alpha/config_dump.proto)

**Comment by ramaraochavali** [comment]
@htuch I guess this issue can closed via https://github.com/envoyproxy/envoy/pull/4197 unless you would like some thing else to be done here.

**Comment by htuch** [comment]
Well, there are other maps for stats (https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v2alpha/clusters.proto#L49), but I think this is a reasonable step and we can open new issues if folks object.

**Comment by ramaraochavali** [comment]
Yeah. I saw that. Let me see if I can fix that as well this week.
