### ISSUE TITLE
health_check: active healthchecking thundering herd during cluster warming

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#4132]
*Title*: *health_check: active healthchecking during warming scalability concern*

*Description*:
*This issue is partly a theoretical issue as i've not yet directly observed issues this as a cause of issues, but i have seen it exacerbate existing ones. However, I believe it is possible for it to cause issues directly*

In troubleshooting an active healthchecking issue, I noticed that jittering healthchecks does not apply to the initial healthchecks for cluster warming. In steady-state this is not an issue, but during startup or restart, this causes a pretty significant amount of healthcheck traffic.

Given that Envoy restarts are often correlated in time (e.g. a fleet restart), and that endpoints are frequently colocated with other endpoints, this can cause a thundering herd of healthcheck traffic against single servers.

My immediate thought is to allow for jittering cluster warmup checks. However, the tradeoff here would be that startup would take some time before clusters are marked healthy. (In fact, I believe this is what HAProxy does).

Perhaps we can have another two parameters. Something like `unchecked_interval` (is it really an interval?) and have this respect `interval_jitter_percent`. The difference here is that the `base_time_ms` would be 0 I think.

CC: @julia-stripe

**Comment by mattklein123** [comment]
Yeah I think it's fine to add optional jitter to the initial HC round for a cluster, with the caveat that startup itself might take longer. I would start here, but for larger clusters you might also need to program the ability for a subset of hosts to respond to the first check before continuing with init...

**Comment by julia-stripe** [comment]
This may be contributing to an issue we're currently seeing with Envoy where sometimes we see `upstream connect error or disconnect/reset before headers` errors when a cluster changes size. My belief about what's happening is:

1. we add / remove a host from a cluster with many clients
2. when the new cluster is being warmed, CPU load increases significantly, presumably because many TLS connections are being established
3. some connections fail to be established, leading to that error message (?)

I'm not 100% sure that's what's happening but that's my current hypothesis.

**Comment by bplotnick** [comment]
@julia-stripe, I wasn't able to repro what you are describing, which (correct me if i'm wrong) seems to be that it re-healthchecks all the endpoints in the cluster when an endpoint is added. I had a cluster where I added an endpoint and only the new endpoint is healthchecked. Skimming https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc, this seems to be consistent with what I am seeing.

@mattklein123, the subsetting thing you are describing relates to my proposal in #4280. If the healthchecking is delegated to endpoint rather than the cluster, then we could have the cluster warming consist just of adding the references to endpoints, which may or may not have been healthchecked. As they become healthchecked, they enter the loadbalancing set. This would simplify the CDS update logic as well. Am i missing something?

I've also been running more tests with HAProxy (our current system) and it appears that they initially will route to the endpoints before the first healthcheck. This isn't documented AFAIK, but it is discussed on [this thread](https://www.mail-archive.com/haproxy@formilux.org/msg12359.html). This is an interesting approach, and one that might be worth discussing. I'm honestly not sure what the "right" approach is.

**Comment by bplotnick** [comment]
@julia-stripe i think i misunderstood what you were saying. You're saying that adding a new endpoint to the clusters causes all the envoy clients to connect to it at the same time.

I definitely see this and it definitely is a problem

**Comment by mattklein123** [comment]
Will switch this to help wanted since I do think adding initial health checking jitter makes sense, though the implementation definitely needs some thinking.
