### ISSUE TITLE
QueryParams should be a real class with correct parsing & serialization

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#4142]
*Description*:
>QueryParams are just a map, but there's no central control or testing of parsing, serialization, escaping, etc.

See TODO in https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/query_params.h

This may help ultimately with https://github.com/envoyproxy/envoy/issues/2098 , though I personally don't understand the context for that particular enhancement request.

@rotan96 may look at this.

**Comment by rotan96** [comment]
I was thinking to do the parsing of the url within the QueryParams class (basically move the code from Utility::parseQueryString to QueryParams::parseQueryString). If I do that I would probably need a query_params.cc file to implement everything, would I need to move the file out of the /include folder and if so where should it go?

Or should I just keep the parseQueryString/other more complicated functions outside of the QueryParams class?

**Comment by rotan96** [comment]
Hi stale bot I am working on this (how do I un-stale this)
