### ISSUE TITLE
IpVersions/RoleBasedAccessControlNetworkFilterIntegrationTest.Allowed/IPv4 is flaky

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#4146]
I've seen a couple of flakes on CI, all of the form

[ RUN      ] IpVersions/RoleBasedAccessControlNetworkFilterIntegrationTest.Allowed/IPv4
test/extensions/filters/network/rbac/integration_test.cc:92: Failure
Expected equality of these values:
  1U
    Which is: 1
  test_server_->counter("tcp.rbac.allowed")->value()
    Which is: 0
[  FAILED  ] IpVersions/RoleBasedAccessControlNetworkFilterIntegrationTest.Allowed/IPv4, where GetParam() = 4-byte object <00-00 00-00> (54 ms)

@yangminzhu would you be up for taking a look?  Perhaps the counter() should be a  waitForCounter variant?

https://github.com/envoyproxy/envoy/blob/master/test/integration/README.md#reproducing-test-flakes may help reproducing/verifying

**Comment by yangminzhu** [comment]
Thanks for the report alyssawilk, let me try to fix this.
