### ISSUE TITLE
more granular 5xx retry policy (again)

### ISSUE THREAD

**Issue by wjessop** [envoyproxy/envoy#4163]
*Title*: *A blanket 5xx retry policy is not granular enough*

*Description*:

This is similar, but not quite the same as [this issue](https://github.com/envoyproxy/envoy/issues/2300).

What I'd like to do is to have a retry policy that allows me to automatically re-try 503 errors, but not 502 or 504 errors which I consider unsafe to retry automatically. We don't want to serve re-try able 503 errors to customers, but we don't want to re-try other non-idempotent 5xx errors.

[Current envoy config options](https://www.envoyproxy.io/docs/envoy/v1.6.0/configuration/http_filters/router_filter.html#x-envoy-retry-on) seem to make this impossible.

This split seems to match with (my reading of at least) [the RFC](https://tools.ietf.org/html/rfc7231#section-6.6.4) which mentions no retry for anything other than a 503, and describes the 502 and 504 status codes in such a way that suggests to me that the proxy cannot guarantee them to be idempotent.

Additionally, the removal of the section `If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response` between [RFC 2616](https://tools.ietf.org/html/rfc2616#section-10.5.4) and [7231](https://tools.ietf.org/html/rfc7231#section-6.6.4) to me would suggest that a 503 is considered try able even with no Retry-After header set, but that's a detail.

**Comment by mattklein123** [comment]
@wjessop I think this is covered by https://github.com/envoyproxy/envoy/issues/4103. If you agree can you close?

**Comment by wjessop** [comment]
I've commented there and will close this, thanks!
