### ISSUE TITLE
Use lld as linker

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#4170]
As a part of tool chain revisit (#4159, #4158) and also as a part of (#3741). We should consider use [LLD](https://lld.llvm.org/) as default linker. LLD is at least twice faster than gold linker, we have more than 300 test target to link so this will improve CI performance.

Options:
1. Use lld everywhere (it works with gcc)
2. Use lld where clang is used (sanitizers)

A sample benchmark of linking `envoy-static` is here:

gold w/o threads (current):
`12.01s user 1.32s system 99% cpu 13.358 total`

gold w/ threads:
`14.24s user 6.97s system 180% cpu 11.762 total`

lld w/o threads: 
`3.63s user 1.15s system 99% cpu 4.805 total`

lld w/ threads:
`8.64s user 11.24s system 709% cpu 2.802 total`

**Comment by mattklein123** [comment]
@lizan +1 I think we should switch to lld everywhere, especially if we switch the release build over to clang.

**Comment by mattklein123** [comment]
This is done.

**Comment by lizan** [comment]
@mattklein123 This is done for 2., I would like to still keep this open for 1.?

**Comment by mattklein123** [comment]
Ah ok. SGTM.

**Comment by htuch** [comment]
@lizan what if we do this; we point `tools/bazel.rc` at a shell script that detects if `lld` is present and uses that by default, otherwise falls backs to `ld`?
