### ISSUE TITLE
IP socket options may be applied to UDS upstream host connections

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#4175]
While investigating https://oss-fuzz.com/v2/testcase-detail/6542943040045056, @anirudhmurali and I figured out that we were applying IP socket option (specifically the `source_address` in `upstream_bind_config`) to a UDS host. This seems broken.

We can either flag this during config loading or silently ignore/warn at runtime as a resolution. I haven't done a deep dive yet into the code, but I think it might be the case that we don't know until something like EDS whether a host is IP or UDS (does EDS force IP only? can't remember). Could we have a mix of IP and UDS hosts in a cluster? @mattklein123

**Comment by mattklein123** [comment]
> We can either flag this during config loading or silently ignore/warn at runtime as a resolution. I haven't done a deep dive yet into the code, but I think it might be the case that we don't know until something like EDS whether a host is IP or UDS (does EDS force IP only? can't remember). Could we have a mix of IP and UDS hosts in a cluster? @mattklein123

TBH I don't remember. Someone will need to look at the code. I don't see any reason why EDS can't expose a UDS host or a mix of hosts.

**Comment by htuch** [comment]
IIRC, we merged a PR that supported mixed UDS/TCP hosts, so will close this one out.
