### ISSUE TITLE
Envoy CI should use an updated GCC version

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#4177]
**Envoy CI should use an updated GCC version**

*Description*:
[My PR](https://github.com/envoyproxy/envoy/pull/4154) seems to be failing only on Envoy CI's GCC builds, but not on the Clang builds. The offending snippet of code is this guy from `test/tools/router_check/router.cc`:

```
    using checkerFunc = std::function<bool(ToolConfig&, const std::string&)>;
    const std::unordered_map<std::string, checkerFunc> checkers = { 
        {"cluster_name", [this](auto&... params) -> bool { return compareCluster(params...); }}, 
        {"virtual_cluster_name",
         [this](auto&... params) -> bool { return compareVirtualCluster(params...); }}, 
        {"virtual_host_name",
         [this](auto&... params) -> bool { return compareVirtualHost(params...); }}, 
        {"path_rewrite", [this](auto&... params) -> bool { return compareRewritePath(params...); }}, 
        {"host_rewrite", [this](auto&... params) -> bool { return compareRewriteHost(params...); }}, 
        {"path_redirect",
         [this](auto&... params) -> bool { return compareRedirectPath(params...); }}, 
    };  
```

I'm able to build locally on `GCC 7.3.0` and Clang, but I'm unable to investigate the versioning on the CI machines due to the fact that we don't output the compiler versions in the log. The issue seems to be the same as the one discussed in [this stackoverflow post](https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc).

Trying the snippet of code from stackoverflow on various GCC compilers on godbolt shows that the bug is fixed in GCC 7.1. There are 2 different requests in this ticket:

1. Output the compiler version in the CI logs.
2. Update the GCC version if needed on the CI workers.

*Relevant Links*:

- https://github.com/envoyproxy/envoy/pull/4154

- https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc

*Log snippet*:
Here's a snippet from the CI failures in the PR to save you a few clicks:
```
test/tools/router_check/router.cc: In instantiation of 'Envoy::RouterCheckTool::compareEntriesInJson(const string&)::<lambda(auto:1& ...)> [with auto:1 = {Envoy::ToolConfig, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]':
/usr/include/c++/5/functional:1856:44:   required from 'static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Res = bool; _Functor = Envoy::RouterCheckTool::compareEntriesInJson(const string&)::<lambda(auto:1& ...)>; _ArgTypes = {Envoy::ToolConfig&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]'
/usr/include/c++/5/functional:2255:19:   required from 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = Envoy::RouterCheckTool::compareEntriesInJson(const string&)::<lambda(auto:1& ...)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = bool; _ArgTypes = {Envoy::ToolConfig&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]'
/usr/include/c++/5/bits/stl_pair.h:145:64:   required from 'constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = const char (&)[13]; _U2 = Envoy::RouterCheckTool::compareEntriesInJson(const string&)::<lambda(auto:1& ...)>; <template-parameter-2-3> = void; _T1 = const std::__cxx11::basic_string<char>; _T2 = std::function<bool(Envoy::ToolConfig&, const std::__cxx11::basic_string<char>&)>]'
test/tools/router_check/router.cc:85:5:   required from here
test/tools/router_check/router.cc:76:91: error: cannot call member function 'bool Envoy::RouterCheckTool::compareCluster(Envoy::ToolConfig&, const string&)' without object
         {"cluster_name", [this](auto&... params) -> bool { return compareCluster(params...); }},
```

**Comment by tonya11en** [comment]
I'm happy to look into this over the weekend if nobody is able to get to it, but a pointer in the right direction would be appreciated.

**Comment by PiotrSikora** [comment]
@tonya11en it's [gcc 5.4.0 in the Ubuntu build image used on CircleCI](https://github.com/envoyproxy/envoy/blob/706e26238268fe76c45e2690928aa012869ed679/ci/build_container/build_container_ubuntu.sh#L26).

**Comment by mattklein123** [comment]
Adding a more recent GCC target is tracked here: https://github.com/envoyproxy/envoy/issues/3149. Unfortunately, like the current clang upgrade/switch discussion, I don't think it's appropriate for us to completely move away from GCC 5 without some discussion. People build/use Envoy on some pretty old systems and it's unclear to me if we should stop supporting GCC 5 (though I would love to add at least one target that builds with newer GCC). @tonya11en my recommendation is to make the other PR buld with GCC 5 for now.

**Comment by mattklein123** [comment]
Closing this as we are already tracking newer GCC in #3149
