### ISSUE TITLE
Circuit breakers per host or relative to the number of hosts.

### ISSUE THREAD

**Issue by markusthoemmes** [envoyproxy/envoy#4203]
*Title*: Circuit breakers per host or relative to the number of hosts.

*Description*:
Is there a specific reason why the circuit breakers are only available on a per cluster level vs. being available on a per host level?

In my specific use-case, I'm implementing a platform (Function as a Service style), where each of the hosts in a cluster has veeeery tight concurrency constraints. If you take the idea to the extreme, each of the hosts is only allowed 1 request at a time. The second important bit here, is that for such a platform, the number of hosts changes rapidly, possibly even sub-second. A general, static, per cluster setting therefore does not really cut it.

I could solve this today by immediately returning 503 for every request before the first request is finished, but that's wasting lots of resources for state the router effectively already has. For this to work on a per-router state level, we'd need to implement `maximum_requests_per_host`.

I can see "maximum pending requests" and "maximum connections" being useful to have on a per host level as well, even for general, not so extreme cases like the one described above.

So: Would it make sense to implement these more granular circuit-breakers or is there an alternative path to solving this without having to hit the hosts until I get a 503?

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking

**Comment by mattklein123** [comment]
There is no particular reason, it's just not implemented this way. I will switch this over to enhancement.

**Comment by brunsgaard** [comment]
Is this idea just fully abandoned, we are having the same usecase as @markusthoemmes.

Is there a better way to do per pod (k8s) circuit breakers? For long running (~2sec) and very CPU intensive grpc calls and a very scalable environment? Ideas are welcome ;)
