### ISSUE TITLE
Propagate attempt count in request headers

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4210]
We're interested in having the upstream attempt count be included in the request headers, e.g. something like `-x-envoy-attempt-count` which starts at 1 with the first request and is incremented once per retry. Our motivation for this is to provide this information to some of our existing systems that rely on this for their caching strategy. 

Seems like this was also [proposed/implemented for gRPC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exposed-retry-metadata), so it's probably a generally useful feature.

In terms of implementation I imagine this being a simple incrementing value maintained in the `Router`. Not completely sure where this would be configured, `VirtualHost` maybe?

**Comment by zyfjeff** [comment]
Is this issue still no one is working?  If yes then i can start this one

**Comment by snowp** [comment]
@zyfjeff I have not started this, so assuming the maintainers are okay with this enhancement it should be up for grabs.

**Comment by mattklein123** [comment]
@zyfjeff @snowp yes this sounds generally useful to me, but I think we need it to be a configurable option as some users might not want this behavior for either performance or security reasons.

**Comment by snowp** [comment]
@zyfjeff Are you still planning on handling this? If not, we can get somebody on our end to implement this

**Comment by zyfjeff** [comment]
@snowp I haven't start, I'm working on another issue

**Comment by snowp** [comment]
No problem, I'll put something together
