### ISSUE TITLE
SIGBUS errors during startup

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#4235]
*Description*:
We're seeing sporadic `SIGBUS` errors in Istio test suite during startup (see: https://github.com/istio/istio/issues/8133).

I suspect it might be full and/or too small `/dev/shm` partition, but we should be able to catch this sooner and provide some useful error instead of a `SIGBUS`.

*Call Stack*:
```
Caught Bus error, suspect faulting address 0x7fdbf98e2028
Backtrace thr<0> obj</home/bootstrap/go/bin/envoy> (If unsymbolized, use tools/stack_decode.py):
thr<0> #0 0xc739fe Envoy::BlockMemoryHashSet<>::initialize()
thr<0> #1 0xc6feec Envoy::BlockMemoryHashSet<>::BlockMemoryHashSet()
thr<0> #2 0xc6bfc5 Envoy::Server::HotRestartImpl::HotRestartImpl()
thr<0> #3 0x812fbf Envoy::MainCommonBase::MainCommonBase()
thr<0> #4 0x813ca1 Envoy::MainCommon::MainCommon()
thr<0> #5 0x812061 std::make_unique<>()
thr<0> #6 0x811a6b main
thr<0> obj</lib/x86_64-linux-gnu/libc.so.6>
thr<0> #7 0x7fdbf9af582f (unknown)
thr<0> obj</home/bootstrap/go/bin/envoy>
thr<0> #8 0x585078 _start
end backtrace thread 0
```

**Comment by fredlas** [comment]
If the problem was in fact completely specific to shared memory, it might be essentially fixed by #5910. (There is still some shared memory, but it's just a tiny bit, for locking purposes).
