### ISSUE TITLE
issue with update_empty stat on clusters

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4241]
Let us say we have 5 EDS clusters registered with Envoy. When an Endpoint for a particular cluster (cluster_1) changed, if a management server sends EDS update with resource list as (cluster_1), Envoy updates it stats correctly but it also increments `update_empty` stat for rest of the clusters. 
It is because it fires an empty config update at this line 
https://github.com/envoyproxy/envoy/blob/master/source/common/config/grpc_mux_impl.cc#L218
Is this intentional behaviour? If it is intentional, I think it is pretty confusing to update other clusters stats indicating that empty update has come where as the intention of management server is not that.

**Comment by htuch** [comment]
@ramaraochavali yeah, this behavior is a bit confusing. `GrpcMuxImpl` treats both CDS and EDS the same, where CDS subscribes with a single watch and EDS with many watches, one per cluster. You want this empty behavior for CDS but not EDS.

I'd consider this a bug, are you interested in taking a look at fixing? It should only be fixed for RDS/EDS, LDS/CDS should maintain their existing behaviors (there really are two classes of xDS effectively).

**Comment by ramaraochavali** [comment]
Yes. I have a working fix for it. I will push a PR
