### ISSUE TITLE
Add request_headers_to_remove

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#4249]
*Title*: *Add request_headers_to_remove*

*Description*:
We [have](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto.html) `request_headers_to_add`, `response_headers_to_add`,  and `response_headers_to_remove`. `internal_only_headers` is related, but not exactly the same as `request_headers_to_remove`.

**Comment by PiotrSikora** [comment]
I'm going to add this, unless you've already started.

**Comment by bplotnick** [comment]
Great! I haven't started
