### ISSUE TITLE
Link against libc++ in the official builds.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#4251]
Similarly to  #4158, #4170 and #4159, investigate and/or consider using libc++ instead of libstdc++ and friends.

cc @lizan @htuch

**Comment by htuch** [comment]
@PiotrSikora I have some vague memory about libc++ being less mature and generally usable on Linux than OS X from the early days of the Clang migration, but can't find any issues that cover this. Definitely worth re-examining.

**Comment by ggreenway** [comment]
Last time I looked into it I found the the same thing as @htuch.

**Comment by lizan** [comment]
FWIW: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/e8pJRHLisIg

Actually I found `--define=force_libcpp=enabled` doesn't actually link to libc++, the flag is only provided at link time, though libstdc++ and libc++ is not ABI compatible. Also, prebuilt libraries are built against libstdc++.

**Comment by lizan** [comment]
I think now is a good timing to revisit on this, we don't have prebuilt dependency anymore and have ability to statically link with libc++.

Pros:
- there's significant memory benefit to the strings in libc++. (by @jmarantz)
- #7647 to unblock upgrading build infra to ubuntu 18.04 which was discussed before. Consistent C++ standard library for different distros.

Cons:
- Breaks existing ABI compatibility with dynamic_ot tracers.

Shall we discuss this in the next community meeting? cc @envoyproxy/maintainers

**Comment by mattklein123** [comment]
In general I like the idea of a consistent stdlib everywhere, but what does the production usage of libc++ look like? Is it stable? Agreed let's discuss on the next call.

**Comment by lizan** [comment]
Recap from community meeting:
- No objection to switching so far
- re stability: Chrome uses it in all OSs, macOS uses it by default, Google using it heavily internally.
- Might need to release as a separate image for a while as it breaks backward compatibility (ref. #7582)

**Comment by lizan** [comment]
#7728 is another bug that caused by libstdc++ in current release. While std::regex is not doing much better job in libc++ anyway, having a consistent standard library with the fuzzing infra seems a win here.

**Comment by PiotrSikora** [comment]
FWIW, we shipped Istio linked against libc++ yesterday. I'll report if we see any issues, but we didn't run into any during testing.

**Comment by lizan** [comment]
Just tagging https://github.com/tetratelabs/getenvoy-package/issues/35 here, yes we're already aware the dynamic_ot plugins needs rebuild.

**Comment by PiotrSikora** [comment]
All Istio releases since 8/13 have been linked against libc++, and the only issue that we've run into was #8106, so I don't think there should be any stability concerns anymore.

**Comment by lizan** [comment]
Thanks @PiotrSikora to confirm that. I will try releasing a separate set of image with libc++ soon (hopefully within 1.12 release).

@envoyproxy/maintainers how do we want to treat this against the deprecation policy? The breaking part is the dynamic_ot plugin (which has to built against same c++ standard library variant).

**Comment by htuch** [comment]
I don't think this violates the deprecation policy, we don't have any strong ABI guarantees provided today, most of the policy covers API and functional behavior of the proxy. CC @alyssawilk.

In the future, I think we should have a strong ABI and stability of the filter API. I think this is going to come to us via the WASM NullVM interface that @PiotrSikora and @jplevyak are working on, rather than any major explicit initiative.
