### ISSUE TITLE
Consider unix socket addresses to be internal

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#4259]
Consider unix socket addresses to be internal

**problem**
Our Envoy mesh design configures Envoy to listen for egress requests over a unix socket. We found that Envoy ignores retry headers in this configuration because it does not consider the requests to be internal.

**context**
Envoy decides whether each incoming request is "internal" or not, based on a variety of criteria (the best description on this seems to be [https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-for](here)).

If a request is *not* internal, some request headers are [sanitized](https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_utility.cc#L129), for instance `x-envoy-retry-on` which influences retry behavior.

The logic to decide whether a request is internal seems complex and therefore it's unclear what the solution should be. Part of the solution would probably involve patching [https://github.com/envoyproxy/envoy/blob/master/source/common/network/utility.cc#L212](isInternalAddress) to consider unix addresses to be internal, although that might be controversial for some setups.

It also seems like we might want a configuration option to ignore x-forwarded-for when deciding if a request is internal and just use the remote address, since `x-forwarded-for` and the `use_remote_address` config option seem to be mainly relevant to edge proxy contexts

**Comment by ggreenway** [comment]
I would be in favor of adding configuration for which network addresses are considered internal, and including an option for if UDS should be included.

**Comment by mpuncel** [comment]
I think there's one additional piece that would be needed because it seems like Envoy always looks at the last address from `X-Forwarded-For`. We'd want a mode where Envoy looks at the remote address instead and does not append to `X-Forwarded-For` (because that wouldn't make sense for a unix socket address)

**Comment by snowp** [comment]
I have some time to implement this. 

Where would such a config option make the most sense? The HCM config? `use_remote_address` lives there, which similarly affects the internal/external decision.

**Comment by mattklein123** [comment]
@snowp yeah I think that would be the best place. cc also @brian-pane who has done work on this area. Unfortunately this whole area (internal vs. external) is a minefield of potentially disastrous regressions so we need to be super careful and fully consider all the cases.
