### ISSUE TITLE
Bazel 0.17.0 not in core homebrew for Mac

### ISSUE THREAD

**Issue by cmluciano** [envoyproxy/envoy#4267]
**Issue Template**

*Title*: Mac builds time out if bazel brew pkg is not found

*Description*:
The Bazel homebrew package is currently missing for any version post 0.15.2 . @moderation found the [upstream problem](https://github.com/Homebrew/homebrew-core/pull/31396) is that the Bazel team has not enabled core homebrew packages outside of their own tap. 

The Mac build will currently attempt a bazel compile from source if it the homebrew install fails. If this takes over 10 min, it will fail the whole build.

I'm wondering if we should leverage the working Bazel tap for now in order to prevent the timeouts until the core homebrew repo is updated.

Thoughts? @htuch @ggreenway @moderation

**Comment by zuercher** [comment]
I don't follow. The mac build seems to be working fine right now using 0.15.2.

**Comment by cmluciano** [comment]
ok will close for now
