### ISSUE TITLE
Send Proxy Protocol to Upstream over L4

### ISSUE THREAD

**Issue by apsega** [envoyproxy/envoy#4277]
*Title*: *Send Proxy Protocol to Upstream over L4*

*Description*:
I couldn't find that Envoy Proxy supports sending Proxy protocol to upstreams over L4. This is needed if I have Nginx Ingress Controller under NAT and Envoy Proxy as an edge L4 proxy in front of Kubernetes clusters. In that way my Nginx Ingress controllers would get the correct X-Real-IP and X-Forwarded-For values.

*Relevant Links*:
HAProxy send-proxy docs: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.2-send-proxy

**Comment by ggreenway** [comment]
Duplicate: #1031
