### ISSUE TITLE
Different unit of timestamp in metrics_service in linux and macos

### ISSUE THREAD

**Issue by lomik** [envoyproxy/envoy#4278]
*Description*:
Envoy sends a different value for timestamps to metrics_service in linux and macos: nanos in linux and micros in macos.
Problem reproduced in 1.7.0 and in current master.

*Repro steps*:
Sample "metrics_service" and envoy config are here: https://github.com/lomik/envoy-issue/tree/master/metric_service_timestamp

Macos output:
```
&io_prometheus_client.Metric{Label:[]*io_prometheus_client.LabelPair(nil), Gauge:(*io_prometheus_client.Gauge)(nil), Counter:(*io_prometheus_client.Counter)(nil), Summary:(*io_prometheus_client.Summary)(0xc0001d61b0), Untyped:(*io_prometheus_client.Untyped)(nil), Histogram:(*io_prometheus_client.Histogram)(nil), TimestampMs:1535464990220755}

# TimestampMs:1535464990220755
```

Linux output:
```
&io_prometheus_client.Metric{Label:[]*io_prometheus_client.LabelPair(nil), Gauge:(*io_prometheus_client.Gauge)(0xc420026818), Counter:(*io_prometheus_client.Counter)(nil), Summary:(*io_prometheus_client.Summary)(nil), Untyped:(*io_prometheus_client.Untyped)(nil), Histogram:(*io_prometheus_client.Histogram)(nil), TimestampMs:1535465054722145763}

# TimestampMs:1535465054722145763
```

**Comment by lizan** [comment]
@jmarantz Can you take a look on this? cc @zuercher for macOS.

**Comment by jmarantz** [comment]
This is already being addressed in https://github.com/envoyproxy/envoy/pull/4288 ?

**Comment by zuercher** [comment]
I think assignees need to be members of the org. Leaving it unassigned for now.
