### ISSUE TITLE
Framework for Richer Information in Responses

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#4283]
*Title*: *Framework for Richer Information in Responses*

*Description*:
Envoy contains a lot of rich information for every request and response. Some of this information is currently not easily accessible to service owners looking to understand the network topology, or debug problems. If this information were shared with trusted clients via response headers and body, it could provide for a richer debugging experience. Additionally, certain information could help downstream clients have more elegant behavior, e.g when receiving a response with x-envoy-overloaded, the client could back off.

There have been several issues in the community that speak to the same problem space. This issue tracks a framework to house setting up and configuring the richer information options, not necessarily all the potentially supported options. Some of the relevant issues are:

- https://github.com/envoyproxy/envoy/issues/3239
- https://github.com/envoyproxy/envoy/issues/1178
- https://github.com/envoyproxy/envoy/issues/4092
- https://github.com/envoyproxy/envoy/issues/2562

*Relevant Links*: @junr03 has written a [design document](https://docs.google.com/document/d/19IVF6SzuCYUa5K-jO22qTKCcc4qY4ckjxDXp3GE2RvE/edit#) that goes into a detailed proposal, please read and comment freely.

**Comment by junr03** [comment]
@vilobhmm do you mind adding details of the proposed functionality we discussed last week, and sharing a link to your document?

**Comment by vilobhmm** [comment]
@junr03 : Here is the doc link for Reverse Proxy Response Propagation to downstream

https://docs.google.com/document/d/1TR9i_yD9FI73PSP73OVytJhsR6T2npMw9SfaSDS5ajw/edit#

**Comment by cmluciano** [comment]
@vilobhmm Can you share that doc with the [envoy-dev mailing list](https://groups.google.com/forum/#!forum/envoy-dev)

**Comment by htuch** [comment]
To satisfy #1472 (which I'm going to close as dupe of this issue), we need to make sure that SSL failures have more fine grained error information reflected in responses. @vilobhmm can you amend your proposal to capture this? CC @ldemailly.

**Comment by vilobhmm** [comment]
@htuch : Will do. Thanks!

**Comment by vilobhmm** [comment]
@cmluciano : Here is the link. https://docs.google.com/document/d/1fMEK80KlpHcL4CwhniOupgQu4MDsxK4y4dKhthjjCMA/edit

Shared it via envoy-dev mailing list as well

**Comment by vilobhmm** [comment]
@htuch : Amended the design doc to capture the failure scenario reported in #1472

**Comment by vilobhmm** [comment]
CC @ldemailly

**Comment by junr03** [comment]
@mergeconflict another data point for this specific feature request: https://blog.linkerd.io/2018/06/19/debugging-production-issues-with-linkerds-diagnostic-tracing/. I think that feature is pretty interesting, as it expands on the one hop idea.

I know that Lyft would find this incredibly useful.

Looking forward to chatting.

**Comment by mergeconflict** [comment]
I've started working on this for really real.
/assign @mergeconflict

**Comment by spenceral** [comment]
@mattklein123 would you be opposed to the addition of `%RESPONSE_FLAGS%` and `%RESPONSE_CODE_DETAILS%` as supported dynamic values for [custom request/response headers](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers)?

I'd like to add them to get a cheap win here if it doesn't negatively impact the broader objective.

**Comment by mattklein123** [comment]
> I'd like to add them to get a cheap win here if it doesn't negatively impact the broader objective.

Sure we are generally fine with adding new variables.

**Comment by mattklein123** [comment]
Fixed by #11007. Please open new issues with specific requests.
