### ISSUE TITLE
implement "b3 single" header format

### ISSUE THREAD

**Issue by adriancole** [envoyproxy/envoy#4289]
*Title*: implement "b3 single" header format

*Description*:
We should permit at least parsing the more compressed "b3" header format, if not making it possible to propagate it downstream.

ex.  `b3: 4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-1`

This is the same format as will be used in the w3c tracestate

Details are here: https://github.com/openzipkin/b3-propagation/issues/21
Example implementation is here: https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3SingleFormat.java https://github.com/openzipkin/brave/blob/master/brave/src/test/java/brave/propagation/B3SingleFormatTest.java

**Comment by zyfjeff** [comment]
Is this issue still open and no one is working?  If yes then i can start this one

**Comment by zyfjeff** [comment]
@adriancole Need to make it configurable, or automatic identification using "b3 single" header format  or b3, if is the automatic identification, then b3 single header and b3 which higher priority?

**Comment by adriancole** [comment]
single header wins
https://github.com/openzipkin/b3-propagation/blob/master/README.md#http-encodings

**Comment by zyfjeff** [comment]
@htuch  please assign to me, i will take some time to implement the recently
