### ISSUE TITLE
when Cluster using EDS service to fectch endpoints ,can't using DNS name in endpoint address

### ISSUE THREAD

**Issue by leader-us** [envoyproxy/envoy#4290]
when Cluster using EDS to fetch endpionts ,I can't using DNS names in endpoint address ,

resource_names: "test-cluster"
type_url: "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
response_nonce: "2705"
error_detail {
  code: 13
  message: "**Unknown address resolver: service1. Consider setting resolver_name or setting cluster type to** \'STRICT_DNS\' or \'LOGICAL_DNS\'"
}

is there any choise ?

**Comment by dio** [comment]
@leader-us you can either resolve the domain in your management server or do complete CDS response. 

Related: https://github.com/envoyproxy/go-control-plane/issues/87#issuecomment-400739949

**Comment by leader-us** [comment]
Thanks，May be support DNS name in EDS endpoints will better

**Comment by dio** [comment]
@leader-us yes true. We hope we can support it eventually. PR is welcome.

**Comment by techpavan** [comment]
Looks like this is still open. Can someone please confirm if so?
