### ISSUE TITLE
Envoy doesn't add headers in case of Gateway Timeout

### ISSUE THREAD

**Issue by pugachAG** [envoyproxy/envoy#4317]
*Description*:

Envoy doesn't add headers specified in the route configuration in case of upstream timeout.

*Repro steps*:

Send request to upstream which doesn't respond within specified route timeout.

Expected: envoy adds headers specified under `response_headers_to_add`

Actual: envoy doesn't add any headers:

```
          'server' => 'envoy',
          'content-length' => '24',
          'Reason' => 'Gateway Timeout',
          'URL' => 'http://authxserver.service/infra_test/idempotent',
          'HTTPVersion' => '1.1',
          'content-type' => 'text/plain',
          'date' => 'Fri, 31 Aug 2018 13:21:31 GMT',
          'Status' => 504
```

*route config*:

```
    {
     "match": {
      "regex": "^/(infra_test/idempotent|/iam/issue-refresh-token|identity/user-exists/.*)"
     },
     "route": {
      "cluster": "authxserver.prod.cluster",
      "timeout": "0.500s",
      "retry_policy": {
       "retry_on": "5xx",
       "num_retries": 2,
       "per_try_timeout": "0.150s"
      },
      "response_headers_to_add": [
       {
        "header": {
         "key": "x-envoy-authxserver-endpoint-type",
         "value": "3"
        }
       }
      ]
     }
```

**Comment by zyfjeff** [comment]
When upstream timeout, the response should be returned by envoy, and response_headers_to_add should be understood to refer to the addition of header to the content returned by upstream.

**Comment by zyfjeff** [comment]
I looked at the code, the current implementation will only add the header when the upstream response is waited.

https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L638

**Comment by lizan** [comment]
Yeah it could be an enhancement, note filters before router could respond to the request too, so the change might be wide. @zuercher (per TODO in the code above) thoughts?

**Comment by mderazon** [comment]
I think the same happens for 503 errors.
Problem with this is that in case of CORS headers not being added in the response, browser shows a CORS error in console and it often obscures the real issue that caused the 504/503.
People think it's a CORS issue, when it's really something wrong with the upstream service

**Comment by majames** [comment]
Has there been any movement on this? I'm also experiencing the timeout issue being masked as a CORs error in the browser because of this and it would be great if there was someone workaround for fixing!

**Comment by mattklein123** [comment]
cc @alyssawilk this might be a good one to look at as you continue your quest to unify a bunch of handling around local replies.

**Comment by alyssawilk** [comment]
I suspect it's easy enough to move the code around and apply to the new (unified) local response path.  Do you think response headers to add should be added unilaterally (runtime guarded) even on local responses, or configured for [only when proxied | all local responses]?

The other complication I can think of would be caching, making sure we have the right APIs for if headers should be added before insert or applied to cache hits as headers are sent upstream if there's no one correct answer to what users want there.  cc @toddmgreer for thoughts on that.

**Comment by alyssawilk** [comment]
Alternately we could just expect folks dup their headers into the local reply content modification.  if so maybe a FAQ for that?

**Comment by mattklein123** [comment]
> I suspect it's easy enough to move the code around and apply to the new (unified) local response path. Do you think response headers to add should be added unilaterally (runtime guarded) even on local responses, or configured for [only when proxied | all local responses]?

My thinking was that we could have common code that both the local reply path and router call to add the response headers, based on the currently snapped/cached route. Agreed this should be runtime guarded, but IMO we could do it unilaterally. Variants of this bug have been opened a ton of times and I think it's the behavior people expect.

> The other complication I can think of would be caching, making sure we have the right APIs for if headers should be added before insert or applied to cache hits as headers are sent upstream if there's no one correct answer to what users want there. cc @toddmgreer for thoughts on that.

Yeah I agree this is complicated. My thinking here though is since the cache filter is not a local reply, it would be acting as the router for cached responses, and could do what it wants in terms of adding headers before or after caching?

**Comment by alyssawilk** [comment]
So the plan would be doing route-based local header modifications and local reply mapper modifications on local responses?

I'm fine with default on with a runtime guard given if folks complain we can always make it configurable after the fact - better than starting with complexity if you don't think it's needed.

**Comment by mattklein123** [comment]
> So the plan would be doing route-based local header modifications and local reply mapper modifications on local responses?

Yeah. Basically just take the code that the router already uses, and move it somewhere common.

> I'm fine with default on with a runtime guard given if folks complain we can always make it configurable after the fact - better than starting with complexity if you don't think it's needed.

+1

**Comment by toddmgreer** [comment]
> Yeah I agree this is complicated. My thinking here though is since the cache filter is not a local reply, it would be acting as the router for cached responses, and could do what it wants in terms of adding headers before or after caching?

If "local reply" means "reply generated by sendLocalReply", then CacheFilter doesn't send local replies. If it just means a reply based on in-process (at the time) state, then CacheFilter will often send local replies.

I don't think CacheFilter should decide whether to add custom headers before or after caching--what would it base the decision on? If you want to add a response header that will be the same for future responses from cache, add it before/upstream of CacheFilter. If the response gets cached, the added headers will be present in all responses (possibly from multiple Envoys) based on that cache entry. If you want to add a response header that may be different in every response, add it after/downstream of CacheFilter. 

Perhaps it should be a HeaderInjectionFilter, and the config can say where it goes?

**Comment by mattklein123** [comment]
> If "local reply" means "reply generated by sendLocalReply", then CacheFilter doesn't send local replies. If it just means a reply based on in-process (at the time) state, then CacheFilter will often send local replies.

The latter, like the router filter.

> Perhaps it should be a HeaderInjectionFilter, and the config can say where it goes?

This is more complicated than I would like, given that we have had this functionality for a long time in the router filter and are trying to make it consistent for local replies. IMO it would be simpler to just say that the cache filter acts like the router and just adds the headers post-caching and pre-response.

**Comment by alyssawilk** [comment]
It may be a bit more complicated than that, as I think (may be misremembering) when doing cache validation the filter sends the upstream headers, then the cached body.  If that's true we should just be careful there's no path where we apply them twice.

**Comment by mattklein123** [comment]
> It may be a bit more complicated than that, as I think (may be misremembering) when doing cache validation the filter sends the upstream headers, then the cached body. If that's true we should just be careful there's no path where we apply them twice.

Good point. Perhaps there is nothing to do if we assume that the router will add the headers and they get cached?

**Comment by toddmgreer** [comment]
> > It may be a bit more complicated than that, as I think (may be misremembering) when doing cache validation the filter sends the upstream headers, then the cached body. If that's true we should just be careful there's no path where we apply them twice.
> 
> Good point. Perhaps there is nothing to do if we assume that the router will add the headers and they get cached?

Exactly.

**Comment by toddmgreer** [comment]
> > > It may be a bit more complicated than that, as I think (may be misremembering) when doing cache validation the filter sends the upstream headers, then the cached body. If that's true we should just be careful there's no path where we apply them twice.
> > 
> > 
> > Good point. Perhaps there is nothing to do if we assume that the router will add the headers and they get cached?
> 
> Exactly.

In successful cache validation, the upstream will respond with a 304, the router filter will add custom headers, and the new custom headers will replace the previously cached ones.

**Comment by mattklein123** [comment]
Perfect, sounds like a plan. :)
