### ISSUE TITLE
v1.7.1 missing from Dockerhub

### ISSUE THREAD

**Issue by bndw** [envoyproxy/envoy#4324]
#### Missing `v1.7.1` tag in Dockerhub

*Description*:
The [latest release of Envoy](https://github.com/envoyproxy/envoy/releases/tag/v1.7.1) appears to be missing its release tags in Dockerhub, `envoyproxy/envoy:v1.7.1` and `envoyproxy/envoy-alpine:v1.7.1`.

I've attempted to manually dig through the Circle history but haven't been able to locate the job corresponding to the tag event.

*Repro steps*:

```
docker pull envoyproxy/envoy:v1.7.1
Error response from daemon: manifest for envoyproxy/envoy:v1.7.1 not found
```

```
docker pull envoyproxy/envoy-alpine:v1.7.1
Error response from daemon: manifest for envoyproxy/envoy-alpine:v1.7.1 not found
```

**Comment by lizan** [comment]
dup of https://github.com/envoyproxy/envoy/issues/4052

**Comment by bndw** [comment]
Whoops, I searched `v1.7.1` in issues but it didn't surface that. I'll close this out, thanks @lizan
