### ISSUE TITLE
how to config envoy as a Origin server for static content ? just like nginx

### ISSUE THREAD

**Issue by BlackPineapple** [envoyproxy/envoy#4325]
*Description*:
>It's my first time to use envoy, someone told me that envoy can be a origin server for static content, but i can't find the related information about it. Can someone tell me where can i get the information about how to config envoy as a origin server for static content ? I shall be very grateful.

**Comment by zyfjeff** [comment]
Envoy is not a web server. It is a modern reverse proxy, similar to haproxy, and nginx is a web server with reverse proxy functionality.
