### ISSUE TITLE
header_to_metadata filter does not work with old style websockets

### ISSUE THREAD

**Issue by bmetzdorf** [envoyproxy/envoy#4327]
Looks like the header_to_metadata HTTP filter does not work with old style websocket connections.

This means that old style websocket connections cannot use header values via header_to_metadata for subset load balancing.

Probably because
```
ConnectionManagerImpl::ActiveStream::decodeHeaders(ActiveStreamDecoderFilter* filter,
  HeaderMap& headers, bool end_stream)
```
is called after the old style websocket check.

Related: https://github.com/envoyproxy/envoy/pull/3633

@rgs1 @zuercher @alyssawilk @ggreenway What do you think?

**Comment by alyssawilk** [comment]
AFIK no filters work with old style websocket connections.   That was one of the motivating factors for new style websockets :-)

In addition, old style websockets are deprecated and so may be removed with the next Envoy build (1-2 months), so I'd strongly encourage moving over and seeing how the new ones work out for you

**Comment by bmetzdorf** [comment]
Thanks @alyssawilk. I remember that @ggreenway mentioned that to me before, but I think I just got confused since the router filter (including adding metadata) actually does work for the old style websocket connections.

I'll work on switching over to the new upgrade methods.
