### ISSUE TITLE
Bazel is the Worst Build System，why not supply makefile for build

### ISSUE THREAD

**Issue by zengyuxing007** [envoyproxy/envoy#4330]
**Issue Template**

*Title*: *One line description*

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.

when now this project using  bazel build system, and  using a lot of thirdparty  dependences,
run bacel build, get these dependences under github is very slowly!!!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by htuch** [comment]
@zengyuxing007 I understand the frustration you're expressing, but we made the call to move to Bazel as the canonical build system last year and there is large amount of complexity and maintenance burden in maintaining multiple build systems. Not to mention the Envoy "business logic" that we've baked into our Bazel build system over this period (e.g. the extension management system).

So, again, appreciate the thought but I'm going to close this issue as non-actionable. Feel free to reach out to me on Slack or e-mail and we can discuss further your particular situation.

**Comment by steakknife** [comment]
Bazel seems decent
https://news.ycombinator.com/item?id=9256844

Maybe under the venier of religulous, fact-free b&m-ing, there's spots of sequential tasks that could be concurrently pipelined to move as fast as say, picking at random, cmake + ninja? (Builds should always be able to run silently on rooftops and throw poison arrows.)
