### ISSUE TITLE
clean up management of durations in timer_impl

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#4332]
*Description*:
> In #4257 there was at one point a refactoring which moved TimerImpl::enableTimer(), which includes this:

```
      std::chrono::microseconds us = std::chrono::duration_cast<std::chrono::microseconds>(d);
      timeval tv;
      tv.tv_sec = us.count() / 1000000;
```

bringing it to the attention of @dnoe , who commented:

```
The conversion factors here could be more readable by using duration cast:

auto secs = std::chrono::duration_cast<std::chrono::seconds>(d);
auto usecs = std::chrono::duration_cast<std::chrono::microseconds>(d - secs);
tv.tv_secs = secs.count();
tv.tv_usecs = usecs.count();
```

I didn't want to rewrite the code as I was just moving it; and then I wound up unmoving it so it really isn't part of #4257, but I'm jotting this down as tech-debt.

**Comment by ranchowang** [comment]
can i do this ? @mattklein123

**Comment by mattklein123** [comment]
@ranchowang sure go for it

**Comment by mattklein123** [comment]
Done
