### ISSUE TITLE
healthcheck: Allow non-200 status codes as healthy HTTP healthchecks

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#4367]
*Title*: *healthcheck: Allow non-200 status codes as HTTP healthchecks*

*Description*:
We have certain services that do not return a 200 on a successful healthcheck. The most common one I've seen is returning an HTTP 204. Envoy marks these as unhealthy because it is checking [explicitly](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_checker_impl.cc#L180) for a 200

I think a good default would be 2xx or 3xx is considered healthy. Whether a given status code should be considered healthy is up for debate, but i think this is pretty standard for proxies right now, and so i think it makes sense to do this.

For extra credit, we can have configuration for what constitutes healthy. e.g. regex check on the body of the response.

**Comment by venilnoronha** [comment]
Just to add, a couple of useful `isNxx` functions are available [here](https://github.com/envoyproxy/envoy/blob/73dfedc95f484ccb31d80a8363c2db1bae51cef5/source/common/http/codes.h#L70-L74).

**Comment by bartebor** [comment]
There are environments like kubernetes, where any 2xx response is considered healthy. We have many applications returning 204 as it has minimal size. This makes it hard to use envoy, because we would need to deploy healthcheck changes in many applications. 
I understand you want to retain your 200-only healthcheck policy, but would you consider making this behaviour configurable?

**Comment by mattklein123** [comment]
Yes we can definitely make this configurable.

**Comment by bartebor** [comment]
How would you like to have this behaviour configured? Possibly the simplest way would be to add a boolean, default `false`, field to `HttpHealthCheck` such as `expect_2xx`. I don't think there is a need to specify individual HTTP codes, but who knows...

I could probably make a PR with implementation.

**Comment by mattklein123** [comment]
@bartebor I know we have had other requests for configurable HC codes, so TBH it wouldn't be that bad to allow it to be fully configurable. What about just a repeated list of acceptable codes?

**Comment by bartebor** [comment]
I'm fine with that. Would an `expect_codes` array of ints do?

**Comment by mattklein123** [comment]
@bartebor yup SGTM

**Comment by ggreenway** [comment]
I think it's more common to express this as a range, because the common settings are:
 
* 200 only
* exactly code X (such as 204)
* any 2xx or 3xx
* any 2xx, 3xx, or 4xx

For each of the above, expressing it as a range is as-good or better. Or if you need extreme flexibility, a `repeated` range.

**Comment by mattklein123** [comment]
Yeah sure, range SGTM.

**Comment by bartebor** [comment]
Ok, so now we have more options, and it becomes a little bit complicated. We could:
- make expected code set a string, something like `"2xx, 301-307, 401"` - this is quite readable, but one must know string syntax and we would need a parser (should not be a big deal though)
- `repeated` messages `HttpCodeRange` with either individual or wider range of codes; this objects could expose `oneof` properties for individual `int code` , `bool any_2xx`, `bool any_3xx`, and maybe `{int from, int to}` - this is the most flexible and well-defined approach

I would prefer some form of latter approach.

Which one would be in line with Envoy API guidelines?

**Comment by mattklein123** [comment]
@bartebor I would probably just use https://github.com/envoyproxy/envoy/blob/master/api/envoy/type/range.proto#L18. Technically you could make a new `UInt64Range` type if you want, but I would just do a repeated list of ranges and keep it simple.

**Comment by bartebor** [comment]
Thanks for your suggestions. Now it's time to dive into coding and make it work. I'll get back with a PR when it's ready.
