### ISSUE TITLE
Allow healthcheck on different port for non-EDS cluster types

### ISSUE THREAD

**Issue by bobzilladev** [envoyproxy/envoy#439]
The http healthcheck will allow a path but not a port, which is problematic for existing Dropwizard-based services which by default to have the healthcheck endpoint on a separate admin port. There are also instances of proxies where a tcp check is being done to check the health of the proxy but the traffic is going over different ports.

Envoy would need a healthcheck_port in the static configuration and the SDS API to support being a drop-in replacement for HAProxy under these conditions.

http://www.dropwizard.io/1.0.6/docs/manual/core.html#health-checks

**Comment by mattklein123** [comment]
Please see linked PR for a first attempt at this. Needs cleanup.

**Comment by mpuncel** [comment]
I'd like to +1 this feature, we have a few cases where we'd like to be able to health check a port that's different from the "traffic port"

**Comment by mpuncel** [comment]
I looked through the previous PR. It sounds like the idea to add a "health check address" to each endpoint in EDS was uncontroversial but figuring out a clean design for specifying an alternate health check port when using strict or logical DNS (and probably static hosts) was difficult.

Would it be reasonable to add the "health check address" config option to EDS first, and then follow up with the other ways of specifying cluster membership later on?

**Comment by mattklein123** [comment]
@mpuncel yes, at this point I think it's reasonable to just make this happen for EDS only which I think would not be too hard. I would add alternate HC port information to https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/endpoint/endpoint.proto#L19 most likely. If you want to tackle I would do a data-plane-api PR and we can discuss the details there.

**Comment by dio** [comment]
@mpuncel, if you're not on this, may I try to propose a fix for this case?

**Comment by mpuncel** [comment]
@dio go for it!

**Comment by mattklein123** [comment]
@dio is there any reason this is not fixed by https://github.com/envoyproxy/envoy/pull/3007? I noticed you said "partially fixed." It seems fixed to me?

**Comment by mattklein123** [comment]
@dio OK fair enough we can keep it open to track.

**Comment by dio** [comment]
Currently, for `STATIC`, `STRICT_DNS` and `LOGICAL_DNS`, a cluster member (a host of `hosts`) is defined as a `core.Address`. In order to accommodate alternative health check port for each host, could we have an alternative type (`oneof`?) of declaring host? Probably just `core.Address + health_check_port` just like what we have with `endpoint` (to allow defining host members as a collection of `endpoints` instead of `core.Address`-es). Thoughts?

**Comment by mattklein123** [comment]
@dio yes I think we can add oneof and not break wire compatibility. I think what you propose makes sense to me. @htuch @WDYT?

**Comment by dio** [comment]
If we change https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/cds.proto#L158 to the following:

```proto
  message Host {
    oneof host_descriptor {
      option (validate.required) = true;

      core.Address address = 1;
      endpoint.Endpoint endpoint = 2;
    }
  }

  repeated Host hosts = 7;
```

will it break wire compatibility?

Since I guess repeated `oneof` is not a thing: https://github.com/google/protobuf/issues/2592#issuecomment-284540212

**Comment by mattklein123** [comment]
Yes I think it will break wire compatibility. You may need to add a new repeated hosts field and deprecate the old hosts addresses field or something like that. That is probably a better long term solution.

**Comment by bobzilladev** [comment]
This is still an important one for our organization, fwiw.

**Comment by mattklein123** [comment]
@bobzilladev AFAIK this is implemented already for EDS, just not for non-EDS. Right @dio? Maybe we should change the title.

**Comment by htuch** [comment]
@mattklein123 do we even need this for non-EDS, given that we can embed `ClusterLoadAssignment` in `Cluster` now?

**Comment by mattklein123** [comment]
@htuch AFAIK implementation of that was never finished, right? I think just the config was added. @dio ?

**Comment by dio** [comment]
@mattklein123 yes for EDS it is there. 

While for the `ClusterLoadAssignment` inside `Cluster` the config is added https://github.com/envoyproxy/envoy/pull/3504.

Sorry for the delay in the implementation. I'll start again next week.

**Comment by dio** [comment]
Update: https://github.com/envoyproxy/envoy/pull/3783 is part of this effort.

**Comment by dio** [comment]
Update. I have submitted: https://github.com/envoyproxy/envoy/pull/3864 to fix this.
