### ISSUE TITLE
DogStatsdSink to support Prefixes

### ISSUE THREAD

**Issue by Tang8330** [envoyproxy/envoy#4390]
**Issue Template**

*Title*: DogStatsdSink to support Prefixes

*Description*:
Currently, StatsD sink supports Prefixes override for users that do not want metrics to start with `Envoy`.

DogStatsd does not. Proto for DogStatsd: https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/metrics/v2/stats.proto#L193

Statsd sink support: https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/metrics/v2/stats.proto#L185

**Comment by htuch** [comment]
@taiki45 do you have any thoughts on this ask?

**Comment by taiki45** [comment]
@htuch I think the sink should support prefixes. I can take this after docs tasks.
