### ISSUE TITLE
Feature Request: Versioning support for filters

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#4391]
*Title*: *Versioning support for filters*

*Description*:
Statically linked Envoy filters are registered as various factories such as `NamedListenerFilterConfigFactory` and `NamedHttpFilterConfigFactory`.
All factories implement `virtual std::string name() PURE;` function that identifies its name.

When envoy calls control plane using XDS, it passes along the [`Node`](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/base.proto#L40) proto. `build_version` and `metadata` inform the control plane about the specific envoy and the kind of configuration the control plane should generate.

Out of this `build_version` is a property of the binary and meta data is whatever was placed in the `bootstrap` config at the start.

In order for the control plane to generate correct config for each filter, it must know 
1. The specific version of the filter that is being configured.
2. Filters that are statically configured in the particular envoy build.

At present `build_version` represents both these things in an inexact way.

**Use case**
Consider a backwards incompatible change in a filter configuration, at present it is not possible to know directly from the binary the version of config that a filter expects.  The workaround is to shove it in the bootstrap config, but this is backwards. Filters and their versions are a property of the build and therefore should not be specified by configuration. 

**Proposal**
1.
Add the following to all the filter config factories. Existing filters will not need to change code.
When a filter needs to avail of version, it should start returning a version.
```c++
virtual std::string version() { return ""; }
```
Filter versions should be manually maintained by the filter author.

2. 
Add filter versions that maps filter name ==> version to `Node`
```proto
map<string, string> filter_versions = 6;
```

**Comment by mandarjog** [comment]
@PiotrSikora

**Comment by htuch** [comment]
This seems reasonable. A few additional considerations:
1. What relationship does filter version have to the filter opaque config proto version (e.g. `v2alpha`)? Is this implied? Could we just use proto version?
2. It's appealing to make the filter version opaque from a design minimalism perspective, but might an ordering between versions be useful to allow for the notion that "anything >= v1.3 is acceptable"?

**Comment by rshriram** [comment]
Ooh this is a nice way to tackle the versioning issues in istio. And in terms of version comparisons, I think that’s enabling the filter author to inject old and new configs which while nice, opens up the door for more complexity at filter level doesn’t it? I guess we could always start with version==101 kind of stuff.

**Comment by mandarjog** [comment]
1. Could be an implementation detail or recommendation.
2. I think we should require a proper `semver` compatible version. It is much cleaner for the control plane to use it in version constraints.

**Comment by htuch** [comment]
If we go the path of semver, we should make the range type for the map `int x int x int`.

**Comment by htuch** [comment]
Reopening, we should do this.

**Comment by htuch** [comment]
@mandarjog are you going to drive this?

**Comment by htuch** [comment]
@mandarjog going to close this one out, as I have a concrete proposal that addresses the above at https://github.com/envoyproxy/envoy/issues/5405.
