### ISSUE TITLE
Immediately drain connections from hosts not in service discovery, as an option

### ISSUE THREAD

**Issue by bobzilladev** [envoyproxy/envoy#440]
When a host is removed from service discovery Envoy will still send it traffic until the healthcheck goes bad. We'd want a configuration to have it start draining connections immediately. Probably along with a minimum-hosts configuration as a sanity check if service-discovery ever lost its mind.

Our discovery always shows all instances, but there's an 'active' flag on whether to send traffic or not, a notion of "in the load balancer". That is used to filter generated HAProxy configurations or other load balancers. For envoy SDS I just omit any host that isn't 'active', so an option would be to have a similar 'active' flag on the SDS API vs an "obey service discovery" on the cluster config.

In a normal deployment we leave up the old fleet for a time to be able to quickly switch back in case of problems. The old fleet is taken out of load balancer but left alive. If monitoring finds a box going bad or rebooted it is also taken out of the load balancer out to be replaced/investigated. In both cases we don't want any customer traffic going to those hosts. I understand there's a mechanism to force-fail the envoy healthcheck but it'd be nice not to have to add that when service-discovery is already saying not to send traffic there.

**Comment by alexkrishnan** [comment]
Am I correct that this behavior could be modified [in upstream_impl](https://github.com/lyft/envoy/blob/b8174db216e430194b99d311c7658049566915bb/source/common/upstream/upstream_impl.cc#L319) possibly to read [a new property of cluster](https://github.com/lyft/envoy/blob/b8174db216e430194b99d311c7658049566915bb/include/envoy/upstream/upstream.h#L210)?

**Comment by mattklein123** [comment]
I believe this is fixed by https://github.com/envoyproxy/envoy/pull/3302. LMK if not and we can reopen.
