### ISSUE TITLE
Log when XDS is performed at startup

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4405]
A common issue people seem to be having is that Envoy sits around forever during startup due to an issue with their XDS setup. It would be good to log something like "waiting for initial xDS data" during startup to make it clear to people why Envoy is seemingly not working.

**Comment by htuch** [comment]
@snowp we already log a lot of info at trace level, are you asking to promote log level? Or, could we add a stats gauge indicating something useful? Or some other admin handler?

**Comment by snowp** [comment]
Yeah, I was thinking of promoting this to info so that people see it without having to restart Envoy with a different log level. 

If we can get more use out of an admin handler of some sort I'd be open to that, but I'm not sure what more information you'd expose. Maybe which xDS types are still pending?

**Comment by htuch** [comment]
@snowp yeah, literally a `/server_state` handler that gives you some value from an enum. Or maybe we could externalize this on the `/healthz`? Not sure. If you want to add some sparing logs at info level, that could be alright, but we are trying to minimize log spew.

**Comment by snowp** [comment]
Still interested in having this, I think a new endpoint would be good. Something easy like 

```
enum { PRE_INIT, INIT, INITALIZED }
```

which correspond to pre InitManager, during InitMananger and after all the init callbacks have run would be nice (which I think is when Envoy starts listening on its listeners?). Anything else that might be interesting to include?

Is json serialized protobuf the preferred way of outputting data now?

Gonna try to squeeze in the time to get this done, it would be really nice for us from an ops perspective to detect stuck Envoys.

**Comment by snowp** [comment]
Looking into this I'm realizing that there's already `/server_info` which kinda serves a similar purpose:

```
~:0 curl localhost:1111/server_info
envoy 3bf98f7f957d169bf6bde5930941b28872e15cae/1.9.0-dev/Modified/DEBUG live 40076 40076 0
```

("live" will change to "draining" once `healthcheck/fail` is called). Maybe there should be a single endpoint with structured data about the server state? Would it make sense to redo `/server_info` to use a proto, or would we want to add a new endpoint that uses a proto that would eventually replace it?

**Comment by mattklein123** [comment]
@snowp yeah there is no particular reason the output of this endpoint is this way. It could move to proto/json if you want to do the work. As long as people can use something like jq in scripting output to extract the data it's fine to change IMO.
