### ISSUE TITLE
Building Bazel with CI Docker image: cannot touch /build/bazel.sentinel

### ISSUE THREAD

**Issue by grgustaf** [envoyproxy/envoy#4411]
*Title*: Building Bazel with CI Docker image: cannot touch /build/bazel.sentinel

*Description*:
When I first cloned envoy and followed the "Building Bazel with CI Docker image" instructions on a shared lab machine, it worked fine, and all tests passed I think. Later, my coworker did the same thing on the same box. Now when I try to do it again, I get this output:

```bash
$ ./ci/run_envoy_docker.sh  './ci/do_ci.sh bazel.dev'
ENVOY_SRCDIR=/source
touch: cannot touch '/build/bazel.sentinel': Permission denied
```
I added `set -x` to the top of the `run_envoy_docker.sh` and I see it results in this docker command:
```bash
docker run --rm -t -i -e http_proxy=http://myproxy https_proxy=https://myproxy
  -u root:root -v /tmp/envoy-docker-build:/build -v /home/grgustaf/envoy:/source -e
  NUM_CPUS --cap-add SYS_PTRACE envoyproxy/envoy-build-ubuntu:61b385[snip]
  /bin/bash -lc 'groupadd --gid 1002 -f envoygroup && useradd --uid 1002 --gid 1002
  --no-create-home --home-dir /source envoybuild && su envoybuild -c "cd source &&
  ./ci/do_ci.sh bazel.debug.server_only"'
```
Note that it's substituted my user id 1002 in three places on that command line.

If I replace `cd source` with `/bin/bash` and poke around in the container I see this:
```bash
$ ls -ld /build
drwxrwxr-x 5 1001 1001 4096 Sep 12 08:32 /build
```
1001 is my coworker's uid. I'm not sure where that's coming from but I'm supposing it involves the fact that the docker daemon is shared between us, but I'm not sure. Maybe there is a way for me to fix this by creating my own workspace or something? But it seems like the envoy script may be making some false assumptions.

I can get farther by hacking that docker commandline to say --uid 1001 instead, but I think I then just see other problems.

*Repro Steps*:
Not 100% sure, but I suspect just have two different users try to run the command:
```bash
$ ./ci/run_envoy_docker.sh  './ci/do_ci.sh bazel.dev'
```
on the same machine in their own envoy trees.

I'm on Ubuntu 16.04.5.

**Comment by zuercher** [comment]
I think if you set the `ENVOY_DOCKER_BUILD_DIR` environment variable to distinct values for different users it should work. The default value (if left unset) is /tmp/envoy-docker-build and that's where /build in the docker container is mapped.

You could also just install the dependencies listed in bazel/README.md and run bazel directly without the docker container.

**Comment by grgustaf** [comment]
You're right, that solves it. Thank you. I'm such a newbie to Docker I don't know which way is up.

**Comment by zuercher** [comment]
Great. If shared build hosts using docker is a common thing, we might want to switch the default value for that environment variable to include the current user or uid. But I expect for development most people will build directly.
