### ISSUE TITLE
Lua HTTP Filter Cookies missing from Headers

### ISSUE THREAD

**Issue by oahayder** [envoyproxy/envoy#4428]
**Issue Template**

*Title*: *Lua HTTP Filter Cookies missing from Headers*

*Description*:

Trying to extract cookies from the incomming headers however they aren't in ```request_handle:headers()```.

I know that they are a part of the request because downstream apps can access the cookies.

We're trying to forward the cookie headers to a downstream auth service via the following code:

```
    local edge_headers = {
        [":method"] = "POST",
        [":path"] = "/edge",
        [":authority"] = http_host,
    }

    for header, value in pairs(request_handle:headers()) do
        local normalized_header = header:match("^[:]*(.+)")
        edge_headers["Edge-" .. normalized_header] = value
    end

    local response_headers = request_handle:httpCall(
        cluster,
        edge_headers,
        "",                             -- empty body
        {{ edge_processors_timeout_ms }}
    )
```

Is there some special trick with cookie access in the proxy code?

**Comment by htuch** [comment]
@oahayder I'm a bit confused about what is upstream and what is downstream in your example. Normally, in Envoy, the client is the downstream and the backends are the upstreams. Can you clarify? There should be no need for any special treatment to access cookies, they should appear to filters as normal headers.

**Comment by oahayder** [comment]
Apologies this was user error. Thanks for looking @htuch
