### ISSUE TITLE
Brotli Compression support in envoy

### ISSUE THREAD

**Issue by nrshrivatsan** [envoyproxy/envoy#4429]
**Issue Template**

*Title*: *HTTP Compression Brotli support*

*Description*:
>Desired behavior 

- Envoy is capable for decompressing HTTP payload using Brotli compression/decompression algorithm

*Relevant Links*:
> https://github.com/google/brotli 
> https://quixdb.github.io/squash-benchmark/#results
> *https://github.com/google/brotli/tree/master/c*
@bmadhavan  @unicell @khgandhi @
/new-feature

**Comment by htuch** [comment]
@jmarantz I've heard you talk about Brotli compression a few times in the past, do you want to weigh in on how this might play out in Envoy?

**Comment by nrshrivatsan** [comment]
@jmarantz 
> create the mechanism to brotli-compress/decompress on-the-fly,

Thanks! cc @htuch

**Comment by mattklein123** [comment]
+1 on generalizing the gzip filter into a general compression/decompression filter.

**Comment by valarauca** [comment]
+1 on generalizing gzip filter into a general compression/decompression.

Also if `zstd` could be included, it provides similar trades-offs to brotli as it also uses similar encoding schemes for compressed data.

**Comment by rojkov** [comment]
I started to work on this. The current status can be seen in https://github.com/rojkov/envoy/commits/brotli
So far I've managed to hack the gzip filter to use brotli compression instead of gzip.
