### ISSUE TITLE
stat to monitor and alert on management server disconnections

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4449]
Currently if Envoy is disconnected from management server, there is not a good stat that we can rely on to alert. `upstream_rq_5xx` and `upstream_cx_connect_fail` come close to indicating the problem. But they get incremented for every retry that Envoy makes to connect to the management server.If we have to alert on these we need to alert on probably sufficiently large to avoid spurious alerts on intermittent disconnections. How about adding a `management_server.disconnection_duration_ms` stat that tells for how much time Envoy is disconnected from Management Server. This may help to predictably alert on long disconnection durations. I know this is not a standard cluster metric but in the absence of a standard cluster metric that we can use to monitor long running streams can we add this custom one for management server?

Any other suggestions?

**Comment by htuch** [comment]
Let's leave this issue open for discussion. I think a gauge could be reasonable as you suggest.

**Comment by mattklein123** [comment]
Yeah FWIW I think a gauge might be simpler vs. a time. Basically are we currently connected to the management server or not. One other option with existing stats is couldn't you alarm on rate of change of stream creation to the management server? If it's cycling/churning alarm if above some threshold?

**Comment by ramaraochavali** [comment]
We could alert based on some threshold but threshold needs to be tuned and is an indirect way. I think a direct stat will be more predictable.

**Comment by ramaraochavali** [comment]
@mattklein123 @htuch  are we good with adding a gauge that indicates whether Envoy is connected to control plane or not? If yes, please assign this to me. I will work on this.

**Comment by ramaraochavali** [comment]
My thinking is it will be under the scope `control_plane.connected_state` and will live at GrpcMux https://github.com/envoyproxy/envoy/blob/master/include/envoy/config/grpc_mux.h. I know it will definitely work for ADS and I am guessing (have not looked at it yes) will work for other subscriptions also as GrpcSubscriptionImpl uses GrpcMux for other subscriptions as well. Does it work?

**Comment by htuch** [comment]
@ramaraochavali this seems reasonable to me, thanks.

**Comment by mattklein123** [comment]
SGTM also
