### ISSUE TITLE
Differentiate ingress/egress traffic when acting as a sidecar

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#4461]
*Title*: Differentiate ingress/egress traffic when acting as a sidecar

*Description*:
Envoy should be able to differentiate ingress and egress traffic (e.g. based on labels in the configuration) and act upon them (e.g. drain ingress listeners, but not egress - see #4460).

cc @nmittler

**Comment by mattklein123** [comment]
@PiotrSikora you probably already know about this but this is related to https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/lds.proto#L103 which I added a while ago to deal with exactly this case. Do you need additional functionality above that?

**Comment by mattklein123** [comment]
@ramaraochavali implemented this I believe.

**Comment by kyessenov** [comment]
TrafficDirection on listener is used for that.
