### ISSUE TITLE
docs: arch docs for SDS

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4471]
We should have arch docs for SDS, both as a high level topic, and in all the cases where we talk about other xDS.

cc @qiwzhang @lizan @PiotrSikora @JimmyCYJ any interest in picking this up?

**Comment by lizan** [comment]
I think it is better to have this doc before 1.8.0 release.

**Comment by lizan** [comment]
Thanks for @qiwzhang picking this up.

**Comment by mattklein123** [comment]
Done! Thank you @qiwzhang!
