### ISSUE TITLE
update to clang-7

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#4477]
*Description*:
LLVM 7 is released. Consider update the build tool chain to clang-7.

cc @PiotrSikora

**Comment by PiotrSikora** [comment]
I have this done and pending in my local tree already, but I'm waiting until 7.0 packages are published on `apt.llvm.org` (right now it still installs pre-release snapshots for `clang-7 llvm-7 lldb-7`) before opening a PR.

Feel free to assign this to me, thanks.
