### ISSUE TITLE
Performance numbers of TCP Load balancing long lived sessions

### ISSUE THREAD

**Issue by techwizardg** [envoyproxy/envoy#4478]
This is not an issue and not sure where to ask and hence posting it here.

We are planning to use envoy proxy as TCP Load balancer for long lived sessions and so wanted some information on performance numbers and the hardware details on which this benchmarking exercise was done.

**Comment by mattklein123** [comment]
@techwizardg the project unfortunately does not provide official perf data: https://www.envoyproxy.io/docs/envoy/latest/faq/how_fast_is_envoy
