### ISSUE TITLE
Can't build master on OSX

### ISSUE THREAD

**Issue by nickolaev** [envoyproxy/envoy#4483]
I am trying to build the latest HEAD (94f5ed6972d1d47d1af1f7a347dac907282e5895) on my MacBook and I get build errors.

After bisecting I found that the last good known commit is 6ce3e1f45005c37e4a951470ee0bcf0381738e76.

The next 75e54d072fa190ab78b9795f9ed7a98e1d2d33a3, which introduces some seemingly irrelevant and small changes in the API protobuffer for `core` and `router` is failing with:

```
 error=7, Argument list too long
```
Seems like the protoc gets an almost endlesly recursive list of include paths `-I`. The full log is here:
https://pastebin.com/yK46cJCP

I've tried `bazel clean --expunge` and changet the bazel version fron 0.15.2 to 0.17.1 but nothing helped. Any ideas?

**Comment by mattklein123** [comment]
@nickolaev sorry for the trouble, this revert will fix it: https://github.com/envoyproxy/envoy/pull/4482
