### ISSUE TITLE
configure component log level 

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4492]
In some scenarios we want to start Envoy with debug logging enabled for some of the sub components in some environments to debug issues. Current CLI does not support this and it is would not be very user friendly to support this CLI layer.

How about supporting it in bootstrap config?

**Comment by ramaraochavali** [comment]
Yes. We want subcomponents to also be set. I am OK setting it in CLI also but was thinking it would make CLI cumbersome. I am fine either way

**Comment by ramaraochavali** [comment]
@mattklein123  are you suggesting that we should enhance the existing flag to support that as well like 
-l debug - to enable debug across the board
-l config:debug,upstream:debug - to enable for specific sub components?

**Comment by mattklein123** [comment]
@ramaraochavali yeah I think something like that would be best and was roughly what I was thinking. Can you potentially provide a firm proposal of what the CLI would look like so we can all discuss? Switching to design proposal.

**Comment by ramaraochavali** [comment]
@mattklein123  Here are the proposed options I could think of with a slight preference to option 2 as it would be more flexible and  clear. But open to other ideas as well.
**Option #1** 
Enhance the existing -l flag to support both global log level and sub component log levels. And only one of them can be specified
-l <log-level>  : Continue work the same way it is working today
-l comma separated list of `component_name:level`. So the components specified here would be applied with the log level specified and other components would take default log level.
For example `-l upstream:debug,config:trace` would enable `debug` for `upstream`, `trace` for `config` and `info` for rest of the components.

**Option #2**
- l <log-level> : No change to this behaviour
Introduce another CLI
-component_log_level or -cl : comma separated list of `component:level`.
So for example 
`-l trace -cl upstream:debug,config:info`
This would enable all components run in trace mode except upstream in debug and config in info mode.

**Comment by mattklein123** [comment]
Yeah I like option 2. @envoyproxy/maintainers any opinions?

**Comment by htuch** [comment]
@mattklein123 @ramaraochavali +1 on component level configurability. I think it would be ideal to be able to modify this at subcomponent granularity at runtime (via admin console). This would be very helpful when debugging live systems without massive performance impact of putting everything at `-l trace` for example.

**Comment by mattklein123** [comment]
@htuch this is already possible at runtime via the `/logging` admin endpoint.
