### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by DemantT** [envoyproxy/envoy#4494]
I clone code from https://github.com/envoyproxy/envoy.git ,
and then build it with " ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release' " 
but failed, the failed message is:

root@ubuntu:/home/T/envoy/envoy# ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
No remote cache bucket is set, skipping setup remote cache.
ENVOY_SRCDIR=/source
HEAD is now at 3e5b733... cleanup: match NOT_IMPLEMENTED_GCOVR_EXCL_LINE change (#53)
building using 20 CPUs
gcc/g++ toolchain configured
bazel release build with tests...
Building...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: no such package '@org_golang_x_net//context': failed to fetch org_golang_x_net: 2018/09/21 07:07:07 unrecognized import path "golang.org/x/net"
INFO: Elapsed time: 64.420s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (287 packages loaded)

anyone can help me about this problem???

**Comment by htuch** [comment]
@DemantT are you able to fetch from golang.org in the Docker container?

**Comment by zuercher** [comment]
You can experiment with that by running `./ci/run_envoy_docker.sh 'bash'` (which will give you a command line in the docker container).

**Comment by daganibhanu** [comment]
Is this something related to [https://github.com/golang/lint/issues/397](url). ? I see the issue being solved in latest version i.e 1.8.1dev, but I'm facing the same issue on 1.7.1 which is stable version. 
I guess the bazel rules must have been changed? or can someone help me in understanding the change/fix?
