### ISSUE TITLE
CentOs build error

### ISSUE THREAD

**Issue by vpiduri** [envoyproxy/envoy#4495]
**Bug Template**

*Title*: *CenOS build image fails*

*Description*:
>"Your toolchain has set _GLIBCXX_USE_CXX11_ABI to a value that uses a std::string " "implementation that is not thread-safe. This may cause rare and difficult-to-debug errors " "if std::string is passed between threads in any way. If you accept this risk, you may define " "ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 in your build."
 #error "Your toolchain has set _GLIBCXX_USE_CXX11_ABI to a value that uses a std::string "

[optional *Relevant Links*:]
>This is the command I have run 

IMAGE_NAME=envoyproxy/envoy-build-centos ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'

Question: Can you please let us know how do we include this ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 in the Basel build options

I have modified BAZEL_OPTIONS but there is no effect. Thanks for your help !

**Comment by htuch** [comment]
@vpiduri you might want to set this in `SOURCE_DIR/.bazelrc` as a `--copt="-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 "` build option, see https://docs.bazel.build/versions/master/user-manual.html#bazelrc.
