### ISSUE TITLE
typed  metadata (cluster, route) in Envoy?

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#4513]
**Issue Template**

*Title*: Having a typed metadata interface help to get/manage config data in metadata.

*Description*:
> We have the use case that some config data goes into a cluster's metadata, the config data is actually a big Protobuf message which we have a helper class wrapped around it to provide sanity check,  helpers for type conversion,  convenience accessors of some fields etc, which is really helpful. 
I think if we could have a feature that:

* Create a TypedMetadataFactory, which may have the following interface:
    * <T> DeserializeFromStruct(protobuf.Struct&).
    * key();  -- This key could be a filter name, or something else (e.g., "com.google.gfe3.serviceProto" which may not have a corresponding filter.
    * Register this factory with its key().
* For all the layers that has the "const Metadata & metadata() const" (clusterInfo, RouteEntry etc), create a correspoding Factory, e.g., CLusterTypedMetadataFactory. 
* In each layer object's impl, have a convenient method which populate the typed_metadata{key: Value} in the ctor, or have a lazy initialize (e.g., if not in the dict, create when requested).
* Since registering the factory is optional, we can register factory only for data we are interested in.
* For each impl, have a <T>typedMetadata(key) method, which returns the class we have registered, or nullptr if no such registration found.

It will be really useful.

more ideas are welcomed.

**Comment by mattklein123** [comment]
@curiouserrandy I thought this is what you have been working on with the typed metadata work? Am I off?

**Comment by curiouserrandy** [comment]
It's the same mechanism, but a different location.  I implemented RequestInfo::perRequestState() and someone else is working on perConnectionState, but this is per-cluster.  

The implementation class could certainly be re-used (though it should be renamed since it's currently called FilterState).

**Comment by mattklein123** [comment]
OK makes sense. That SGTM.

**Comment by stevenzzzz** [comment]
the perRequestState seems provided a good tool for this feature, the difference is that this time the structured data/object is not generated by another filter, but from a config, and hopefully by the *DS that reloads the {cluster, filter, route}.metadata.

**Comment by htuch** [comment]
I've chatted with @stevenzzzz offline and I'm persuaded by the motivation. This design (or something like it) would address the problems of consistency and duplicated work that occur if you repeatedly transform the metadata into a type representation across the filter chain.

One question I have is why restrict this to just metadata? What we're really doing is building up an object on each xDS resource update that is a function of the new config. This could be anything, including the metadata, e.g. maybe you want to also use service info as an input.

Another is if there is anyone else out there that shares the problem of wanting to transform metadata into a typed object and share it across their filter chains (or other Envoy extensions)? Ideally we would make sure they are bought into this design.

**Comment by mattklein123** [comment]
I don't have a specific use case for this feature but IMO it makes a lot of sense and seems sufficiently general to me, FWIW.

**Comment by stevenzzzz** [comment]
I talked with @htuch and he agreed we can proceed on this rough idea. I will come up with an more detailed design doc, thanks @htuch!

**Comment by stevenzzzz** [comment]
I have a proposed design doc, comments welcome.

https://docs.google.com/a/google.com/document/d/e/2PACX-1vTHbr68I2_XeAcBxgqSPls0_7I6lDRzJYnaHUDvQGIaRkL1WZ1VixA3U8KvV7hjiFPRFQimSweGDFxj/pub

**Comment by stevenzzzz** [comment]
sorry, should've create the link with a personal account. Link updated:
https://docs.google.com/document/d/1AKA_5iMSR6WZaDbjQfLFbK9maO_la_MZgVtYdD9gWtA/edit?usp=sharing

**Comment by rshriram** [comment]
Please make the doc public..

**Comment by stevenzzzz** [comment]
Hey @rshriram are you looking at 
https://docs.google.com/document/d/1AKA_5iMSR6WZaDbjQfLFbK9maO_la_MZgVtYdD9gWtA/edit?usp=sharing 
?
