### ISSUE TITLE
RBAC: expose SNI as a parameter in permission

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#4515]
**Issue Template**

*Title*: Expose SNI as a parameter in the permission block

*Description*:
Currently, we expose destination IP/port/HTTP headers. WE need to also expose the SNI value.

cc @yangminzhu

**Comment by rshriram** [comment]
@venilnoronha says he wants to take a crack at this.

**Comment by yangminzhu** [comment]
@rshriram @venilnoronha 
Are you planning to add this as a first-class field in [Permission rule](https://github.com/envoyproxy/envoy/blob/4d149e6d1550694ab2cc44aa6d97b7294286aaf7/api/envoy/config/rbac/v2alpha/rbac.proto#L99) and the RBAC filter finds out the SNI from the connection (or somewhere else, I'm not familiar about this part)?

**Comment by venilnoronha** [comment]
@yangminzhu yes, that's right.
