### ISSUE TITLE
Envoy exit with [2018-09-24 22:28:05.101][21934][critical][main] source/server/server.cc:78] error initializing configuration './tc01_envoy-ratelimit.json': Unable to parse JSON as proto (INVALID_ARGUMENT:admin.address: invalid value "tcp://0.0.0.0:8901" for type type.googleapis.com/envoy.api.v2.core.Address):

### ISSUE THREAD

**Issue by huxiaobabaer** [envoyproxy/envoy#4524]
**Issue Template**

*Title*: *[2018-09-24 22:28:05.101][21934][critical][main] source/server/server.cc:78] error initializing configuration './tc01_envoy-ratelimit.json': Unable to parse JSON as proto (INVALID_ARGUMENT:admin.address: invalid value "tcp://0.0.0.0:8901" for type type.googleapis.com/envoy.api.v2.core.Address):*

*Description*:
[!65 01:09:10 ]# envoy --version
envoy  version: 845923714078e5a3528e85d4b58f2cc95850a1c6/1.8.0-dev/Distribution/RELEASE

[2018-09-24 22:28:05.101][21934][critical][main] source/server/server.cc:78] error initializing configuration './tc01_envoy-ratelimit.json': Unable to parse JSON as proto (INVALID_ARGUMENT:admin.address: invalid value "tcp://0.0.0.0:8901" for type type.googleapis.com/envoy.api.v2.core.Address):

**Comment by huxiaobabaer** [comment]
My json file is
{
  "listeners": [
    {
      "name": "internal-api",
      "address": "tcp://0.0.0.0:8701",
      "filters": [
        {
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "webapp-ingress",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "webapp",
                  "domains": ["*"],
                  "routes": [
                    {
                      "timeout_ms": 0,
                      "prefix": "/apps/internal/api/transformation",
                      "auto_host_rewrite": true,
                      "cluster": "webapp",
                      "rate_limits": [
                        {
                          "actions": [
                            {
                              "type": "generic_key",
                              "descriptor_value" : "internal_api_transformer"
                            }
                          ]
                        },
                        {
                          "actions": [
                            {
                              "type": "destination_cluster"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "timeout_ms": 0,
                      "prefix": "/apps/internal/api/notification",
                      "auto_host_rewrite": true,
                      "cluster": "webapp",
                      "rate_limits": [
                        {
                          "actions": [
                            {
                              "type": "generic_key",
                              "descriptor_value" : "internal_api_notification"
                            }
                          ]
                        },
                        {
                          "actions": [
                            {
                              "type": "destination_cluster"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "rate_limit",
                "config": {
                    "domain": "zuora"
                }
              },
              {
                "name": "grpc_http1_bridge",
                "config": {}
              },
              {
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://0.0.0.0:8901"
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "ratelimit_service",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "features": "http2",
        "hosts": [ { "url": "tcp://localhost:8081" } ]
      },
      {
        "name": "webapp",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://localhost:8301"
          }
        ]
      }
    ]
  },
  "rate_limit_service": {
    "type": "grpc_service",
    "config": {
      "cluster_name": "ratelimit_service"
    }
  }
}

**Comment by zyfjeff** [comment]
You look is v1 configuration file format, this is now does not support, please use the v2 version of the configuration format

reference: [front-envoy.yaml](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/front-envoy.yaml)

**Comment by junr03** [comment]
@zyfjeff is correct. Please convert your configuration to v2. You can use [this bazel](https://github.com/envoyproxy/envoy/blob/e999cfaccfc5a0fc99d16d7ed7f1248f60546a73/tools/v1_to_bootstrap.cc#L2) tool to do so.

I will close this issue, as the problem source is known. Let us know if you have any other questions.

**Comment by huxiaobabaer** [comment]
@junr03 Could you please point me the doc how to use [v1_to_bootstrap.cc](https://github.com/envoyproxy/envoy/blob/e999cfaccfc5a0fc99d16d7ed7f1248f60546a73/tools/v1_to_bootstrap.cc#L2). Do i need to compile it by myself?  I don‘t have any c/c++ background.
