### ISSUE TITLE
unbalanced high/low write buffer watermark callbacks

### ISSUE THREAD

**Issue by polivbr** [envoyproxy/envoy#4541]
**Issue Template**

*Title*: unbalanced high/low write buffer watermark callbacks

*Description*:
Full disclaimer: I barely understand this code and I could be completely off base, but this is what I've found...

I've discovered an issue with passing concurrent server-streaming GRPC requests through the Istio Ingress Gateway (which uses Envoy), in which some of the streams from the server, through Envoy, and back to the client, will hang. After a lot of troubleshooting, I believe I've narrowed it down to unbalanced calls to the high/low write buffer watermark callbacks. It seems that if the connection is already blocked, a newly created stream will have its high watermark callbacks invoked one too many times, and thus when an attempt is made to unblock it, it never actually unblocks.

It seems to me that the culprit is in Envoy::Http::ConnectionManagerImpl::newStream(). If the connection is above the high watermark, it calls the high watermark callbacks on the new stream. However, these callbacks have already been called as a result of calling addCallbacks().

```
StreamDecoder& ConnectionManagerImpl::newStream(StreamEncoder& response_encoder) {
  if (idle_timer_) {
    idle_timer_->disableTimer();
  }

  ENVOY_CONN_LOG(debug, "new stream", read_callbacks_->connection());
  ActiveStreamPtr new_stream(new ActiveStream(*this));
  new_stream->response_encoder_ = &response_encoder;

  ////// ------ Invocation #1 --------------------
  ////// addCallbacks() will result in callHighWatermarkCallbacks() being invoked
  new_stream->response_encoder_->getStream().addCallbacks(*new_stream);
  
new_stream->buffer_limit_ = new_stream->response_encoder_->getStream().bufferLimit();

  ////// ------ Invocation #2 --------------------
  // Make sure new streams are apprised that the underlying connection is blocked.
  if (read_callbacks_->connection().aboveHighWatermark()) {
    new_stream->callHighWatermarkCallbacks();
  }

  new_stream->moveIntoList(std::move(new_stream), streams_);
  return **streams_.begin();
}
```

If I comment out this second invocation, everything behaves as expected with no errors or hangs.

As I stated above, I barely understand this code and the interaction between the different components, so my assessment may very well be incorrect, but there is definitely an issue with streams being disabled and never re-enabled when there is sufficient back pressure.

If you need more information or if there is anything else I can do to assist, please let me know.

**Comment by mattklein123** [comment]
Yikes this sounds bad. Thanks for the outstanding report and investigation. I'm tagging @alyssawilk who can hopefully triage this tomorrow in case we want to get a fix in before we tag 1.8.0 (@alyssawilk if you are too busy LMK and I can take a look also). Thank you!

**Comment by polivbr** [comment]
Thank you for the quick response! If there's anything I can do to assist, please let me know.

**Comment by alyssawilk** [comment]
I think there may be a bug here but I don't think it's solely in the HCM. 

On inspection it seems plausible that both the h2 codec and the HCM are as you say giving duplicate notification of high watermark callbacks: 
  if (connection_.aboveHighWatermark()) {
    stream->runHighWatermarkCallbacks();
  }
in ServerConnectionImpl::onBeginHeaders plus the 
if (read_callbacks_->connection().aboveHighWatermark()) {
    new_stream->callHighWatermarkCallbacks();
  } 
in the HCM.  I'm leery of simply removing the check in the HCM without either fully paging back in how H1 handles this, or having a working integration test of network backup.  I'm trying to hack something together where we force small kernel buffer sizes and use the current backup tests (which do trigger stream flow control) but I'm having a heck of a time triggering this code path in actual test even with an artificially low SO_SNDBUF.

**Comment by polivbr** [comment]
I have a test app that I was using to trigger this bug:

https://github.com/polivbr/istio-stream-hang

Basically, the client sends concurrent down the same GRPC connection, each of which results in the server sending back very large streams of data in response. In the case where the server and Istio gateway are on the same 10GB network and the client is on a separate 1GB network, this test is able to trigger the bug in seconds. 

I'd attach the logs I used to troubleshoot, but they're massive. I'm happy to prune out relevant bits if you can let me know what would be helpful.
