### ISSUE TITLE
docs: arch docs for retry plugins

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4544]
Some example configurations for the built-in plugins would be great. cc @snowp

**Comment by snowp** [comment]
I can handle this, feel free to assign.

Where would it make sense to add these docs? Inline with the proto defs or on its own page? I’m not very familiar with how the docs are set up in general

**Comment by mattklein123** [comment]
@snowp I would probably do the following:

- Add an overview of configurable retries here: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http_routing#retry-semantics
- Then maybe a new section on custom retry configuration plugins under here (at the same level as route matching, etc.)? https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/http_conn_man

I think have a few config examples of the built-in plugins and a brief description of what a retry plugin can do would be awesome!
