### ISSUE TITLE
Refactor fd() callback in transport sockets to a generalized I/O handle.

### ISSUE THREAD

**Issue by sbelair2** [envoyproxy/envoy#4546]
**Issue Template**

*Title*: *Transport socket callback fd() needs to be generalized to an I/O handle for more generalized connections*

*Description*:
Back towards the end of 2017 the transport_socket interface was introduced. In  PR #2116, which added the transport_socket interface, @mattklein123 had the following comments:
"Not all transport sockets are going to have a fd. Can this be removed from the interface somehow? (I haven't yet looked in detail at how the rest of the code is factored). In now reading more of the PR, I guess this is due to the fact that fundamentally we are passing FDs around from listeners. I suppose at some point we may need to turn this into some type of generic handle but this is probably ok for now. Just thinking out loud." 

As we prepare for the integration of VPP with Envoy, the issue of the generalizing of the fd is a central one, since that interface extends beyond that of a socket.

**Comment by junr03** [comment]
@mattklein123 @alyssawilk @htuch iirc there is someone involved in the VPP work that has been working towards this generalization/refactor, right? Just want to assign the right person to this issue

**Comment by htuch** [comment]
I think @sbelair2 is the right person to assign to.

**Comment by danzh2010** [comment]
Talked with @sbelair2 about cooperating on IoHandle. We plan to have initial PR: https://github.com/envoyproxy/envoy/pull/5177 checked in and I will extend the interface in PR: https://github.com/envoyproxy/envoy/pull/5171 as next step. There might be a bulky PR later to actually replace direct usage of fd with calls to IoHandle interfaces which I'm half way through.

**Comment by mattklein123** [comment]
I think this is actually done! Thanks @florincoras!
