### ISSUE TITLE
what should I do for adding a new function

### ISSUE THREAD

**Issue by DemantT** [envoyproxy/envoy#4554]
I want to add a new plugin to filter some bad url or something, can I add a custom function in this code?just like a plugin
What should I do?

**Comment by junr03** [comment]
Hi, without more details it is unclear to me where your proposed functionality would go (or if this is functionality that envoy might already have), i.e in a separate filter, as an enhancement of an existing filter. So a few more details would be helpful.

In terms of adding new functionality via an extension, if you think the added functionality would be of use to the community as a whole we have an explanation of our [extension directory layout](https://github.com/envoyproxy/envoy/blob/master/REPO_LAYOUT.md#sourceextensions-layout), and a document explaining the process of [adding a new extension](https://github.com/envoyproxy/envoy/blob/master/GOVERNANCE.md#extension-addition-policy).

**Comment by DemantT** [comment]
@junr03 Sorry, I didn't make myself clear，I want to add a new plugin for filter something I want  .
I want to know whether envoy support adding custom plugins like nginx  and how

**Comment by ggreenway** [comment]
Yes, you can add custom code as a filter, either at the http or network level. I'd start with https://www.envoyproxy.io/docs/envoy/latest/extending/extending.

**Comment by DemantT** [comment]
@ggreenway yes,I have found it , But an error was reported when compiling the http filter example，Have you ever met one？？

**Comment by DemantT** [comment]
@ggreenway  my err msg is
 build error no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'
I build it on macOS
