### ISSUE TITLE
Envoy Lua filter request_handle get http method and path

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy#4557]
Hi,

Is there any way I can get HTTP method(GET/POST etc) and the request path(context path) from the request_handle object?

Thanks

**Comment by mattklein123** [comment]
Yes they are contained in the `:method` and `:path` pseudo headers.

**Comment by rbkumar88** [comment]
Thanks that worked..Another question.while I am writing a custom filter instead of Lua..can cluster_manager.h httpAsyncClientForCluster be used to call any other cluster (which is defined-basically want to do an ext http call) apart from the one which is currently being processed by the filter. Say am calling a route(belonging to cluster A) for which a custom filter is called, inside which I want to call a route(belonging to cluster B). is that possible?

**Comment by mattklein123** [comment]
Yes it's possible. See other example filters. We do this in quite a few places.

**Comment by mattklein123** [comment]
See this filter which does something similar: https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/network/client_ssl_auth

**Comment by rbkumar88** [comment]
Can I create a "network" filter like client ssl auth and parse the response from RestApiMatcher and set it in some object and use it on a custom "http" filter. Is that possible, if so, do we have any examples already.

**Comment by enzoferrari** [comment]
U think? U from?
