### ISSUE TITLE
Support to be able to write customized string message to RequestInfo and AccessLog

### ISSUE THREAD

**Issue by qiannawang** [envoyproxy/envoy#4563]
**Issue Template**

*Title*: Support a method of  RequestInfo to set customized message, which can then be propagated to the AccessLog.

*Description*: 
The RequestInfo currently only supports to set the response flag via setResponseFlag(), which then converted to the response_flags field of the access log. In our use case, the filter needs to write customized message to the access log. 

It will be helpful to support to set a customized string message, e.g., via setResponseMsg(string msg), which is then propagated to the StreamAccessLogsMessage.

**Comment by mattklein123** [comment]
This sounds reasonable to me as a high level concept, along with a set of access log extractors. Though, I wonder if this could be done today with the existing metadata concepts we have? cc @zuercher @ggreenway

**Comment by qiannawang** [comment]
@mattklein123 can we take this one and start to implement the feature?

**Comment by mattklein123** [comment]
@qiannawang what about the existing metadata? We already have an extractor for that. Do you really need any code changes here? Filters can already add abstract metadata on request info and then print it.

**Comment by ggreenway** [comment]
Yes, I think this can be done with dynamic metadata already. See https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#config-access-log-format for how to extract the metadata into the logs, and https://github.com/envoyproxy/envoy/blob/master/include/envoy/request_info/request_info.h#L305 for how to set the metadata from a filter.

**Comment by qiannawang** [comment]
That helps!
