### ISSUE TITLE
prometheus fails to scrape metrics

### ISSUE THREAD

**Issue by jinuxstyle** [envoyproxy/envoy#4568]
We are trying to use envoy native support for promethues metrics, but prometheus fails to scrape the metrics because our cluster name contains characters '@' and '=', like following:

`xlsoa.example.greeter@v=v2.2.1`

It works fine previously when using statsd exporter which replaces all the illegal characters for prometheus(https://github.com/prometheus/statsd_exporter/blob/master/exporter.go#L252). The converted metric name is as below:

`# HELP envoy_cluster_xlsoa_example_greeter_v_v2_2_1_update_success_counter Metric autogenerated by statsd_exporter.`

But now, when using envoy native support for prometheus metrics, envoy doesn't replace all the illegal characters to match the regex required by prometheus(https://prometheus.io/docs/concepts/data_model/).

We expect envoy can convert the metric name to match the regex required by prometheus, what do you think?

**Comment by ggreenway** [comment]
Shouldn't the cluster name be a label, like `envoy_cluster_update_success_counter{cluster="xlsoa.example.greeter@v=v2.2.1"}`, or similar?

**Comment by jinuxstyle** [comment]
Yes, it should be a label. I checked the metrics for cluster "xlsoa.example.greeter@v=v2.2.1" again, and it looks envoy only extracted the part before the first dot as the value of label envoy_cluster_name.
```
# TYPE envoy_cluster_example_greeter@v=v2_2_1_update_success counter
envoy_cluster_example_greeter@v=v2_2_1_update_success{envoy_cluster_name="xlsoa"} 1
```
The expected metric should be:

```
envoy_cluster_update_success{envoy_cluster_name="xlsoa.example.greeter@v=v2.2.1"} 1
```

**Comment by ggreenway** [comment]
I think this is caused by https://github.com/envoyproxy/envoy/issues/4357

**Comment by jinuxstyle** [comment]
The issue is informative. Thanks.
