### ISSUE TITLE
[Discussion] How to convince the boss to use envoy

### ISSUE THREAD

**Issue by wrfly** [envoyproxy/envoy#4574]
**How to convince our team leader to use envoy**

*Description*:
I read envoy's docs and used it in my testing environment, it works great, but how to convince the team leader to use it? They thought envoy is new, cannot trust it, and the team needs to make extra efforts to write c++ for implementing the new features or fix bugs, but I think new features are not essentially and bugs can be fixed by the community. Their point is, whether envoy can be trusted. Is there any big company really use it in the production environment? What if envoy cannot handle our business and what should we do?

BTW, the company use Nginx for now and have a big Nginx configuration file. We know that Nginx has some problem with dynamic port listening, need to reload (I'm not sure with the performance) and nginx's configuration is not quite maintainable easily.

Hope someone knows envoy well can answer the questions, thanks.

**Comment by ramaraochavali** [comment]
>>Is there any big company really use it in the production environment? 
https://www.envoyproxy.io/ - Go through this link and search for "USED BY" that tells who all are using Envoy in production

**Comment by wrfly** [comment]
Hi @ramaraochavali , this is obvious, but the boss still cannot trust it since there is no public blogs or something like that shows that these companies use envoy

**Comment by dio** [comment]
I believe @nrshrivatsan can help to answer this 🙂.

**Comment by nrshrivatsan** [comment]
## Reasons to use Software LBs

- Horizontal Scalability
- Vendor Neutral
- Lowered TCO (Capex & Opex)

## Why Envoy
- C++ is excellent for Network and HTTP processing
- Envoy's [filter designs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/network_filters) are modular and open for modification
- C++ provide performance 
- Envoy's resource utilizations are frugal compared to Hardware LBs
- Horizontal scaling of Envoy on Kubernetes works like a charm 
- [SDKs](https://medium.com/solo-io/introducing-the-envoy-operator-for-kubernetes-d59dc75e6d8c) for Kubernetes are available for free


Hope this helps @wrfly

**Comment by nrshrivatsan** [comment]
Why use Software LBs

- Horizontal scalability
- Vendor Neutrality
- Observability

Why Envoy

- C++

**Comment by wrfly** [comment]
Thanks @nrshrivatsan 

I know that Nginx can hot load some lua scripts as its sub-logic-processor, such as insert some user token(en/decode or encrypt), traffic to different endpoints by the user's token or some complex logic, I'm not sure this is right(use Nginx as a framework and the project management is quite annoying, you know, scripts...)

But is there any way for envoy to do this? By writing extensions? I haven't write any extension so I'm not sure about that. Besides, according to the documents, I know that envoy can modify the header and lead the traffic to different clusters via the header matcher, so it means that envoy can fit into our business, right?

From my understanding, envoy's configuration is quite complex and flexible, and that makes envoy powerful, so it can win Nginx in edge-router, service mash or other sides? I think we can drop the Lua scripts in Nginx if envoy can do that for us.

Thanks a lot.

**Comment by nrshrivatsan** [comment]
@wrfly  

- Envoy support hot-restarts [Blog link](https://blog.envoyproxy.io/envoy-hot-restart-1d16b14555b5  )
- Envoy Lua support is [in flight](https://github.com/envoyproxy/envoy/issues/3296).
- Envoy was designed to be a Programmable L7 Proxy - ground up with support for GRPC at control plane in a cloud-native-way. PDLC of SLB is so sound it has been automated : [Envoy-Operator](https://github.com/solo-io/envoy-operator)

PS -  Personally I don't like to answer tech-comparison questions as it might be VERY subjective friend :-)
