### ISSUE TITLE
Investigate crash introduced in #4382

### ISSUE THREAD

**Issue by AndresGuedez** [envoyproxy/envoy#4583]
*Description*:
Code merged in https://github.com/envoyproxy/envoy/pull/4382 is causing a SEGV in source/common/network/connection_impl.cc:586. 

My comment from #4581:
>As @junr03 pointed out, it seems the delayed close timeout callback is being issued after a ConnectionImpl::closeSocket() call which resets the connection_stats_ pointer has occurred. This points to an interesting race since destruction of the ConnectionImpl should lead to disarming the timeout, so it's possible the onDelayedCloseTimeout() cb is triggering while the ConnectionImpl is in the deferred deletion stage.

**Comment by AndresGuedez** [comment]
@junr03 Can you provide steps to reproduce? I just want to verify my assumptions are correct about the timing that caused this.

A comprehensive fix should be a nullptr check for _connection_stats__ in `ConnectionImpl::onDelayedCloseTimeout()` along with disabling the delayed close timer in `ConnectionImpl::closeSocket()`.

**Comment by junr03** [comment]
I agree with your timing comment (re: the cb being triggered while we are in deferred deletion), and with your proposal to fix.

Unfortunately this was happening in production boxes, so I don't have local repro steps.

Thanks for looking into it @AndresGuedez

**Comment by mattklein123** [comment]
@AndresGuedez per @junr03 your assessment is correct. I verified via the crashing call stack and code inspection. I agree the right fix is disabling the timer in `closeSocket()`. I would recommend creating a crashing test and then fixing the bug.
