### ISSUE TITLE
jwt_authn filter Jwt header [alg] field value is invalid

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy#4584]
Hi,

I know this filter is still not released yet. But when I try to validate a JWT token with  the following  header
```
{
  "kid": "xyz",
  "alg": "RS512"
}
```
, it fails saying "Jwt header [alg] field value is invalid" 
Is this expected, if so how to get around this.

Thanks
Bharath

**Comment by lizan** [comment]
Only `ES256` and `RS256` is supported algorithm currently. @qiwzhang I think we should explicitly document it.

@rbkumar88 are you trying to use JWT with RS512?

**Comment by qiwzhang** [comment]
Yes,  only ES256 and RS256 are supported in the current implementation.  

The code is here:  https://github.com/google/jwt_verify_lib/blob/master/src/jwt.cc#L67

You are welcomed to enhance it.

**Comment by rbkumar88** [comment]
Sure thanks for the help. Is this filter configurable(enable/disable) or overrideable at route level like buffer filter?

**Comment by qiwzhang** [comment]
Currently it doesn't take config from route table.   But its requirement is based on the RouteMatch:

https://github.com/envoyproxy/envoy/blob/d101ae7decfdae148f53ea9d2220444c726dfbfd/api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto#L309
