### ISSUE TITLE
Envoy http filters have the *same* order in decode and encode methods

### ISSUE THREAD

**Issue by qiannawang** [envoyproxy/envoy#4599]
**Issue Template**

*Title*:  Request and response go through the same http filter order in the chain

*Description*:
We've found that, in the http filter chain, the request and response (to and from the upstream end point) go through the same filter order. 

Filters are added to decode and encode in the same order: https://github.com/envoyproxy/envoy/blob/b90fd4bd470e2c48c3f3c6614835bb001cc6b230/source/common/http/conn_manager_impl.h#L313

and the encode filter chain goes through in that order: https://github.com/envoyproxy/envoy/blob/b90fd4bd470e2c48c3f3c6614835bb001cc6b230/source/common/http/conn_manager_impl.cc#L1018

This seems unexpected, as we thought the decode and encode had the reverse order of the http filters. For example, we config in bootstrap yaml file in the http_filters:
X
Y
Z

The decode order is X, Y, Z, and we thought the encode order was Z, Y, X. but turned out this is not true.

This unexpectation introduces problems to our system, e.g., by measuring the rrt of the request in some filter, header stripping, gzip, etc. 

Should we consider to fix the order and make it reverse in encode chain?

**Comment by stevenzzzz** [comment]
this is surprising and yet true. 
I think the straightforward solution is when adding to encode_filters_, use moveIntoList instead of moveIntoListLast().

**Comment by mattklein123** [comment]
This is an unfortunate oversight that I'm kicking myself for right now. Oops! :cry: 

The code fix itself is easy, and I agree should be done. The problem here is whether anyone is depending on this odd behavior. I suspect not since no one has complained about it before, but I think we probably have to make this behavior opt-in with some type of deprecation period in which we would do the switch. Though I guess we can send email and solicit feedback on just changing it.

**Comment by qiannawang** [comment]
I would like to contribute to the fix. Opt-in feature sounds a better solution for me because:
1) it can avoid to break anyone;
2) it help a faster release.  

What do you think?

**Comment by mattklein123** [comment]
Yes I think that's the way to go. I think it should be straightforward. The only tests I can think of that might break are the conn_manager_impl multiple filter tests, but you will need to add some new tests anyway.

**Comment by htuch** [comment]
@mattklein123 would a HCM filter config field to control behavior make sense, with eventual deprecation? I think we want to have folks experience the correct behavior by default as soon as is reasonable.

**Comment by mattklein123** [comment]
> @mattklein123 would a HCM filter config field to control behavior make sense, with eventual deprecation? I think we want to have folks experience the correct behavior by default as soon as is reasonable.

Yeah that's what I suggested above.

**Comment by htuch** [comment]
@mattklein123 just wanted to validate we're talking about filter config vs. CLI.

**Comment by mattklein123** [comment]
Oh yes I meant config, not CLI.

**Comment by curiouserrandy** [comment]
Have we looked at this behavior for network (L4) filters?  Glancing at the code without experience, it seems like the same problem (both read and write filters put on the end of the chain, both executed in start-to-end order.)

**Comment by qiannawang** [comment]
is FilterManagerImpl::addWriteFilter the place adding the write filters to the network filter chain?

https://github.com/envoyproxy/envoy/blob/fdfa5bde3343372ad662a830da0bdc3aea806f4d/source/common/network/filter_manager_impl.cc#L14

I believe the change is to replace  emplace_back with emplace_front when adding the write filters.

**Comment by mattklein123** [comment]
@qiannawang yes that's right.

**Comment by qiannawang** [comment]
Which proto is a good place to add a field to config the order of write filters?

@htuch suggested http_connection_manager.proto for http filters, what about tcp ones?

**Comment by htuch** [comment]
@qiannawang you want the HCM proto for L7 filters and the Listener FilterChain for L4.

**Comment by mattklein123** [comment]
@qiannawang are you planning on doing another PR for network filters as well?

**Comment by qiannawang** [comment]
Yes. Do you have any suggestion of the change to network filters?

**Comment by mattklein123** [comment]
I would put a similar deprecated boolean field here: https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/listener/listener.proto#L157 to go along with the filters?

**Comment by qiannawang** [comment]
Close this issue as the fixes have been enabled (by default). The cleanup will be tracked by a new ticket, as explained in https://github.com/envoyproxy/envoy/pull/4889#issuecomment-438121554
