### ISSUE TITLE
routes: RouteMatch runtime keys do not take effect after snapshot updates

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#4607]
*Description*:
RouteMatch runtime keys are frozen to the values calculated in the RouteEntryImplBase constructor due to:
https://github.com/envoyproxy/envoy/commit/bcc7a96d9e66bc0f70e3ed52161ec3471f835bdb#diff-e1ba5ba2b98b12e1bd4aaa74e9b61a80R352

Since `loader_.snapshot().featureEnabled` is not being called, the value is frozen once the object is created. The impact here is that a user will have to reload the Envoy config for the value to take effect, creating extra burden in failover scenarios.

**Comment by tonya11en** [comment]
I'll be submitting a PR to fix this shortly.

CC @danielhochman

**Comment by tonya11en** [comment]
@htuch we had discussed representing the fractional percent runtime value as a JSON/YAML string in https://github.com/envoyproxy/envoy/pull/4217#discussion_r214192442.

My concern with continuing to do that for this fix is that we'll have to parse the string into a protobuf before calculating if the feature is enabled for every route match. See what's happening in:
https://github.com/envoyproxy/envoy/commit/bcc7a96d9e66bc0f70e3ed52161ec3471f835bdb#diff-e1ba5ba2b98b12e1bd4aaa74e9b61a80R416

On the other hand, I don't think it's ok to change the way this is configured again. Looking for any thoughts on this. I'll still go ahead and implement a first-pass fix and make any changes as needed.

**Comment by htuch** [comment]
Yeah, we don't need to change this. I think that the lack of atomicity here isn't as serious - it probably only happens over a short window if doing automated update and so won't affect that much traffic.

**Comment by tonya11en** [comment]
#4632 fixes this.
