### ISSUE TITLE
 134/5000 Do you intend to add the member health check configuration per cluster using route, for example: "/ health"?

### ISSUE THREAD

**Issue by fernandodiassp** [envoyproxy/envoy#4614]
I really like envoy, but I think the lack of http check per member of the cluster makes a lot of people keep using haproxy.

**Comment by snowp** [comment]
Envoy supports HTTP health checking: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/health_checking

**Comment by fernandodiassp** [comment]
I know the envoy has health check, but in my case the check has to check every member of the cluster.
Currently the envoy allows me to register only one host (check url) for cluster checking.
In my case I have 1 cluster with 5 servers.
The http check should be for each of these servers, automatically removing them from the cluster if they are not healthy.

If it were on Haproxy it would be:

listen App_Lab_20013
    bind *: 20013
    mode http
    option forwardfor
    option httpchk GET / healthcheck HTTP / 1.0
    balance roundrobin
    timeout check 2s
    server server1 10.40.0.36:20013 check inter 3000 fall 3 rise 2
    server server2 10.40.0.37:20013 check inter 3000 fall 3 rise 2
    server server3 10.40.0.38:20013 check inter 3000 fall 3 rise 2
    server server4 10.40.0.39:20013 check inter 3000 fall 3 rise 2
    server server5 10.40.0.40:20013 check inter 3000 fall 3 rise 2

**Comment by mattklein123** [comment]
@fernandodiassp what you are describing is how Envoy works. Please take a look at the docs again.

**Comment by fernandodiassp** [comment]
632/5000
Hello Matt, what I found in the closest documentation would be

"**http_health_check**" in the "https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#envoy-api-msg-core-healthcheck-httphealthcheck" link.

But in the documentation itself says that if you do not inform a "host" it will consider the name of the cluster (informing only one host does not solve my problem), what I need it to consider in checking is the cluster members.

If I am mistaken please send me an example, where it is possible to perform an http health check (passing an api check route) to each member of a cluster.

Below is an image of the sent my example config and envoy logs:

![cds](https://user-images.githubusercontent.com/5703163/46553137-1d3c6a80-c8b3-11e8-94bd-96717ac6e8fa.JPG)

![eds](https://user-images.githubusercontent.com/5703163/46553026-d189c100-c8b2-11e8-8506-8bdf8e021f31.jpg)

![2018-10-01 16_51_39](https://user-images.githubusercontent.com/5703163/46552703-dac65e00-c8b1-11e8-8d08-d2913cb793ff.png)

In my understanding, the expected log would be:

http://10.40.0.29:8787/swagger
http://10.40.0.36:8787/swagger
http://10.40.0.37:878/swagger
http://10.40.0.38:878/swagger
http://10.40.0.39:878/swagger

Each server above is a member of the cluster informed in the config.
