### ISSUE TITLE
[v1.8.0 (Oct 4, 2018) deprecation] turn down v1 API

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4617]
#3847 (config: making v2-config-only a boolean flag) introduced a deprecation notice for v1.8.0 (Oct 4, 2018). This issue tracks source code cleanup.

**Comment by alyssawilk** [comment]
Ok, command line config is gone, and docs links are pruned.
I started in on removing all the v1 API docs, but unfortunately if we're going to keep the REST APIs around for one more version that gets fairly hairy given some things like v1SDS don't have docs outside of the v2 tree.  I think this is done enough for this release, and we should do some more clean up after we cut 1.9.
