### ISSUE TITLE
[v1.8.0 (Oct 4, 2018) deprecation] Remove deprecated old style websockets

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4619]
#3867 (websocket: deprecating old style websocket) introduced a deprecation notice for v1.8.0 (Oct 4, 2018). This issue tracks source code cleanup.

**Comment by alyssawilk** [comment]
My thought was to do a small PR removing the config option, wait a week, and see who missed the deprecation notice.

As far as you know @ggreenway @rshriram am I good to go here?
