### ISSUE TITLE
SIGUSR1 only reopens access log

### ISSUE THREAD

**Issue by yegoratpinterest** [envoyproxy/envoy#4631]
*Title*: SIGUSR1 only reopens access log

*Description*:
>When using logrotate it's not possible to avoid 'copytruncate' option for the application log only; access log can be rotated using USR1.

*Repro Steps*
> Rename application log, killall -SIGUSR1 envoy on the running box. Application log won't change.

**Comment by mattklein123** [comment]
@yegoratpinterest sorry I'm not sure what you are asking here. Do you mean that Envoy should also try to reopen the application log file when it gets SIGUSR1? If so that makes sense I'm just trying to make sure I understand.

**Comment by yegoratpinterest** [comment]
Sorry for the confusion @mattklein123 . You are correct, Envoy should reopen the application log on SIGUSR1.
I can make the change if you guys up to it.

**Comment by ggreenway** [comment]
If envoy is logging to a file (set by CLI option), it will already re-open on SIGUSR1. If envoy is logging to /dev/stderr (the default), I don't know if there's a way to re-open; I'm unfamiliar with that bit of unix.  See `--log-path` on https://www.envoyproxy.io/docs/envoy/latest/operations/cli.

**Comment by mattklein123** [comment]
Yeah if we are already opening --log-path on SIGUSR1 it seems like that is what we should be doing? As @ggreenway says I'm not sure it's possible to reopen stderr or if it makes sense to do so?

**Comment by yegoratpinterest** [comment]
Sorry, my bad.
Please close this ticket.
