### ISSUE TITLE
tls: refactor tls tests

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#4635]
*Description*:
From #4566 review:
- [ ] use v2 config
- [ ] use `bssl::UniquePtr` wherever possible
- [ ] read from file using `TestEnvironment::readFileToStringForTest`
- [ ] extract cert / private key read to a function

**Comment by lizan** [comment]
@ramaraochavali do you want to take this?

**Comment by ramaraochavali** [comment]
@lizan Yes. Please assign it to me
