### ISSUE TITLE
How to run multi envoy process on one linux server

### ISSUE THREAD

**Issue by huxiaobabaer** [envoyproxy/envoy#4640]
*Title*: *One line description*
How to run multi envoy process on one linux server

*Description*:
I am not using docker container.
I have the need to want to start two envoy processes on one linux server.

Steps:
1) create two folder on a centos server
/root/envoy1 and /root/envoy2
2) scp envoy binary (built on centos7) to the server under /root/envoy1 and /root/envoy2
3) Prepare config.yaml files with diff ports 
4) Start envoy from folder 1. it works well
/root/envoy1/envoy -c /root/envoy1/config.yaml --service-cluster myapp1 --service-node myapp1 
5) Start envoy from folder 2. Nothing happens. And there is no screen output and log for further information
/root/envoy2/envoy -c /root/envoy2/config.yaml --service-cluster myapp2 --service-node myapp2

Any suggestion?

**Comment by moderation** [comment]
@huxiaobabaer from `envoy --help`. Works well and I run multiple Envoy's on a single host.

```
   --base-id <uint32_t>
     base ID so that multiple envoys can run on the same host if needed
```

**Comment by huxiaobabaer** [comment]
@moderation What is the default value of base id if not specified? TKS

**Comment by moderation** [comment]
I don't believe there is a default. I start with 0 and count up from there.From 0 to 4294967295 works.

**Comment by huxiaobabaer** [comment]
Thank you very much for your help!!! @moderation
