### ISSUE TITLE
jwt-authn exception

### ISSUE THREAD

**Issue by githubYasser** [envoyproxy/envoy#4651]
**Issue Template**

*Title*: *jwt-authn exception*

*Description*:
>Im using the jwt-authn http-filter for validating JWT. Im using the version 2 API reference of envoy and the following envoy image version tag : fdfa5bde3343372ad662a830da0bdc3aea806f4d

>Im getting following exception : 
[critical][main] source/server/server.cc:80] error initializing configuration '/etc/front-envoy.yaml': Didn't find a registered implementation for name: 'envoy.jwt_authn'

*config*:
```
- name: envoy.jwt_authn
            config:
```
      
Am i using the wrong name ?

thanks

**Comment by qiwzhang** [comment]
It should be:  envoy.filters.http.jwt_authn

**Comment by githubYasser** [comment]
thank you , working now.
