### ISSUE TITLE
Not able to make  x-envoy-upstream-rq-timeout-ms if we have both egress and ingress envoy in service mesh

### ISSUE THREAD

**Issue by skyrocknroll** [envoyproxy/envoy#4654]
**Issue Template**

*Title*: *Not able to make  x-envoy-upstream-rq-timeout-ms if we have both egress and ingress envoy in service mesh*

*Description*:
We are facing the exact same issue  discussed in this thread. https://groups.google.com/forum/#!topic/envoy-users/lf2up8V2Cn8

is it possible to provide an flag so that the egress envoy does not strip the ` x-envoy-upstream-rq-timeout-ms` and ingress envoy receives the header and respects the timeout header.

**Comment by rfkm** [comment]
@mattklein123 
Could you keep this open please? 
Fixing this would be helpful for us since we have some APIs which require long timeout because it serves binaries, and it is hard to set timeout in every hops.

**Comment by rene-m-hernandez** [comment]
Hi all, please see my latest comment: https://groups.google.com/d/msg/envoy-users/lf2up8V2Cn8/7ItTCWBQBwAJ
