### ISSUE TITLE
docs: version history linting

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4657]
https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/version_history.rst

Modify check/fix format to lint this file:

- ~100 col line breaks
- All items start with lower case subsystem followed by colon
- Alpha order for subsystems within the section
- Maybe even an approved list of subsystems for consistency

**Comment by M4rk9696** [comment]
Hi, can I take up this issue?

**Comment by mattklein123** [comment]
@M4rk9696 yes please!

**Comment by M4rk9696** [comment]
I've linted the column length to 100, but there are cases where the length of the cross reference is
greator than 100.  

eg)
`envoy_api_field_config.filter.network.http_connection_manager.v2.HttpConnectionManager.request_timeout`

I understand that they were named to be meaningful, but these seem to be too big to fit. Below is a screenshot of another reference.

<img width="962" alt="screen shot 2018-11-24 at 5 13 24 pm" src="https://user-images.githubusercontent.com/20227996/48968125-5cb04900-f010-11e8-919b-7e6af39a0b36.png">

> Maybe even an approved list of subsystems for consistency

I've attached the list of subsystems currently mentioned in the version history. I'm new to the 
project so I don't have a complete idea of all the subsystems which are available, so I'll
remove some of the obvious inconsistencies like

- rate-limit
- ratelimit

- tcp proxy
- tcp_proxy

[subsystem_list_current.txt](https://github.com/envoyproxy/envoy/files/2612231/subsystem_list_current.txt)

**Comment by mattklein123** [comment]
Yeah we aren't going to be able to line break everything to 100 col. Thanks for working on this!

**Comment by M4rk9696** [comment]
I'm a bit caught up at work so I don't think I'll be able to finish this.

**Comment by mattklein123** [comment]
As exposed by https://github.com/envoyproxy/envoy/pull/9354, one thing we should cover here is common typos around ref link, which include extra spaces which make the refs not actually render.

**Comment by mk46** [comment]
Hi @mattklein123, Can we increase the width of the page? 
line break doesn't work because of the big words.
My changes look like this
![envoy](https://user-images.githubusercontent.com/52198964/78863230-b45d2200-7a56-11ea-862b-06d8b5acc811.jpg)

Can I take up this issue?

**Comment by moderation** [comment]
@mk46 the docs started off super narrow. They then changed to full width. They then changed backed to super narrow.  I prefer wide and I think it is more mobile friendly.

**Comment by mk46** [comment]
@moderation I also prefer full width but waiting for @mattklein123 response.

**Comment by mattklein123** [comment]
Can we please open another issue to talk about docs width? I actually don't care. @lucperkins reverted the width change so we can discuss there.

**Comment by mk46** [comment]
Hi @mattklein123,I opened [10726](https://github.com/envoyproxy/envoy/issues/10726).Let's discuss about this.

**Comment by lucperkins** [comment]
Excessively long line lengths do readers a tremendous disservice and are universally regarded as a no-no amongst technical writers and UX specialists. I'd recommend keeping paragraph line lengths roughly where they are and using word wrapping/breaking for words that exceed that: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/.

**Comment by mattklein123** [comment]
@alyssawilk did most of this so I'm closing this. Thank you!
