### ISSUE TITLE
Question: `UNAVAILABLE` vs `RESOURCE_EXHAUSTED` when rate limited (`OVER_LIMIT`)

### ISSUE THREAD

**Issue by nikolay-pshenichny** [envoyproxy/envoy#4660]
I am seeing `grpc-status: 14` (`UNAVAILABLE`) in the responses from Envoy when a request was "rate limited" (ie. rate limiting service responded with `OVER_LIMIT`).

[HTTP to gRPC Status Code Mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md) states that the HTTP Status Code `429` should be mapped to `UNAVAILABLE`.
But [Google Cloud's documentation](https://cloud.google.com/apis/design/errors#generating_errors) suggests mapping it to `RESOURCE_EXHAUSTED`.

Returning a `RESOURCE_EXHAUSTED` status code may potentially make things easier, especially if a client side has Retries configured for the `UNAVAILABLE` status codes.

I am trying to understand if returning `UNAVAILABLE` is the correct behavior or I may have configured something incorrectly?
And also, If that is the correct behavior (including the backwards compatibility reasons) will it make sense to have the response status code configurable somewhere in the [Rate Limit Service Configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/ratelimit/v2/rls.proto#envoy-api-msg-config-ratelimit-v2-ratelimitserviceconfig)?

**Comment by mattklein123** [comment]
Right now Envoy follows the status code mapping as specified, so it is the expected behavior at least as the spec defines it.

We can consider having the mappings be configurable I suppose?
