### ISSUE TITLE
rate limiting service definition in bootstrap configuration

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4669]
currently rate limiting service needs to be defined in bootstrap configuration. Can we move this to filter configuration, similar to how external_auth is configured (or support both?), so that we can configure it dynamically via management server?

**Comment by mattklein123** [comment]
@ramaraochavali yes, this is a historical artifact that should be cleaned up. Ultimately, we should move all of https://github.com/envoyproxy/envoy/tree/master/source/common/ratelimit into the extensions directory where it can be commonly shared with the various filters that use it. I think now that we have the singleton manager, we can still have a single rate limit client shared by all filters, that is also able to work with CDS. If you want to work on this can you put together a short design proposal just to make sure we are all on the same page?

**Comment by ramaraochavali** [comment]
@mattklein123 Thank you. Sure I will let you know if I can pick this up and create the design proposal.

**Comment by mattklein123** [comment]
> Do you think we should have RateLimitServiceConfig both in boostrap config and the rate limit filter config? or should we deprecate in bootstrap config and enabled only in filter config(similar to how external auth works)?

I would deprecate and make it look just like ExtAuth (maybe there can even be code sharing, not sure).

> it seems you are suggesting that remove explicit rateLimitClient method and move it to singleton manager 

Yup exactly, there will end up being no RateLimit code directly in the Envoy core at that point (on server or anything else). See some examples here: https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/http_connection_manager/config.cc#L66. It's pretty straightforward to use and should work perfectly for this use case across both the HTTP and network filters.

**Comment by ramaraochavali** [comment]
Ok. Great. I plan to do it two steps then
1. Move all the rate limiting stuff to extensions with Singleton manager. At this point, there is no functional change but would enable the next steps.
2. Deprecate bootstrap rate limit config , introduce it to filter config and make it work like ext authz. At this point I will see if there is any code sharing possible across ext authz and rate limiting (which seems like it will be, at high level)

**Comment by ramaraochavali** [comment]
Looked at it in detail today, we need to add `BootStrapConfig`/ `RateLimitServiceConfig` to `FactoryContext` so that rate limit filter can lookup BootStrap or it's own filter config, build client and register to singleton manager. Is it OK to add `BootStrapConfig` to `FactoryContext`?

Is there any other way?

**Comment by mattklein123** [comment]
Sorry I don't understand why we need any bootstrap config for rate limit service. The idea is to have it all be configured by the filter. Is the issue that filters might configure different rate limit services such that the singleton manager doesn't work? IMO, I would actually require that all filters have the same RL service config and fail config if this is not the case. This can be checked by tracking the current config in the singleston manager. If anyone cares about this it can be relaxed in the future?

**Comment by ramaraochavali** [comment]
Yes. Agree. I am not thinking that filters would have different rate limit services. In the final state of this implementation, we would remove RLS config from bootstrap and move it to filters. However in the interim, if I have to move the current `rateLimitClient` construction to extensions, I need BootStrapConfig available there - otherwise for some period of time, we need to have keep the code in /source/common/ratelimit and remove it when we fully migrate to the final stage. My idea is to move every thing now so that we have code at one place. Can we do it any other way without actually passing the bootstrap to extensions so that ratelimit client is built at extension?

**Comment by ramaraochavali** [comment]
I think we can probably add RateLimitServiceConfig to Singleton Manager and use it in the extensions. So currently it gets added from BootStrapConfig from the main code and the client construction in extension can use the same now (after moving the existing code to extensions) and later when we remove BootStrapConfig, it will be added from filter config. That way we can move the code to extensions now it self. 
So looks like we can do it in two steps as 

1. Move all the rate limiting stuff to extensions with Singleton manager. At this point, there is no functional change but would enable the next steps. Here Singleton Manager will have `RateLimitServiceConfig` will be added to Singleton Manager from core code and client will be constructed using it and registered with Singleton Manager from extensions.
2. Deprecate bootstrap rate limit config , introduce it to filter config and make it work like ext authz. At this point I will see if there is any code sharing possible across ext authz and rate limiting (which seems like it will be, at high level).  
I think this should work. WDYT?

**Comment by mattklein123** [comment]
Yup I think that makes sense. Thank you!

**Comment by HeathLee** [comment]
The latest documentation still has the rate limit configuration in [bootstrap section](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/ratelimit/v3/rls.proto) (both v2 and v3), should it be deleted?
