### ISSUE TITLE
//test/integration:h1_capture_direct_response_fuzz_test is flaky in tsan

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#4676]
https://circleci.com/gh/envoyproxy/envoy/105201
https://circleci.com/gh/envoyproxy/envoy/105096

Seems happening often, @htuch?

**Comment by htuch** [comment]
@lizan I'll take this and work on it tomorrow. It turns out the fuzzers are a never ending supply of bugs, it's surprising to be seeing them hit on the limited test corpus though.

**Comment by htuch** [comment]
@eziskind knows the root cause and is working on a fix, reassigning.

**Comment by mattklein123** [comment]
I think this is fixed.
