### ISSUE TITLE
Pre-built bazel toolchain

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#4677]
*Title*: *Pre-built bazel toolchain*

*Description*:
There are a number of [requirements](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers) for building Envoy, and they change somewhat frequently, so it's hard to keep up. This is particularly tricky with newer versions of the packages, which might not be available in a given package manager.

One option is to just build in a docker container, which we already support. But this has its own set of tradeoffs (e.g. bazel caching is tricky to get right).

Bazel apparently has a way to depend on pre-built [toolchains](https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain). To be perfectly honest, I have no idea how this would look like in practice or what the tradeoffs are. So hopefully someone here knows more than I do 😄 

One open question is how this affects development dependencies differently from build dependencies. Specifically, i'm thinking about `clang-format`, which you'll probably want to run outside of the bazel build.

[optional *Relevant Links*:]
@jmillikin-stripe wrote a little bit about this https://john-millikin.com/bazel-toolchains#prebuilt-toolchains

**Comment by bplotnick** [comment]
I'd still like to see this happen. Building in a docker container still can be painful, but it's not trivial to install all the tools on the systems, especially some of the newer ones that might not be packaged.

**Comment by jmillikin-stripe** [comment]
Installing and configuring a Clang toolchain across multiple OSes is extremely difficult, and relies on actively changing internal bits of the Bazel configuration API. I don't think any of the Envoy maintainers have enough time to maintain such a custom toolchain. Certainly it's not worth doing if the Docker approach works well enough to get by on for now.

**Comment by bplotnick** [comment]
I see. I wasn't aware of the difficulty.

Is it possible to do it piecemeal? e.g. packaging up things like Ninja or libtool or whatever but use the system version of clang?

If not then i'll close this issue and we can revisit at a later time.

**Comment by jmillikin-stripe** [comment]
Downloading Ninja is practical because it's static, self-contained, and there are official binary builds. I think it could be made into a Bazel toolchain pretty easily.

Libtool is much more difficult because, in typical GNU style, it drops a bunch of components all over the filesystem and relies on other libraries to be available to the dynamic loader.

In general I think it's more practical to keep using Docker for now, because Envoy's dependencies change often and only a few contributors understand the Bazel toolchain model (vs Docker, which is just a big chroot).

**Comment by bplotnick** [comment]
Ok thanks for the info. I'll close this until we find a dedicated person that wants to take this on and own it 😄
