### ISSUE TITLE
Method to override filter-generated responses

### ISSUE THREAD

**Issue by aschran** [envoyproxy/envoy#4692]
Method to override filter-generated responses:
Need a way to override filter-generated local replies in filters higher up the chain.

*Description*:
Filters sometimes use `sendLocalReply` to create locally generated responses. For example, the Envoy router will send a 503 with body text `upstream connect error or disconnect/reset before headers` if it can't connect.

It seems like there's no great way to:
- detect when a lower level filter has generated a local reply (vs. getting the same response from upstream)
- if it has done so, replace the response

Am I missing something? If not, is this functionality worth adding?

A more specific example: when the error above is generated by the Envoy router code, we want to use a higher level filter to redact it, because we don't want specific internal information about failures (i.e. that a request failed with 503 because upstream died vs. some other reason) to be shown to clients. Right now I am looking for `UpstreamConnectionFailure` and `UpstreamConnectionTermination` in the `StreamInfo` response flags to detect this, but that's kind of brittle because if the router code ever changes how it uses those flags or adds more flags, my code will break if it's not simultaneously updated. Then, to replace the error message in the response body I am draining the buffer passed to `MyFilter::encodeData` and putting my own contents in there, but the problem is that the content length appears to already be fixed by that point, so I am left with a bunch of gross looking filler spaces in the response.

There must be a better way to do this, right? Looking forward to hearing from the experts. :)

**Comment by mattklein123** [comment]
I think this is a dup of https://github.com/envoyproxy/envoy/issues/1178? Also related to https://github.com/envoyproxy/envoy/issues/4283. If you agree can we close and track in those issues? I agree this is something that we need to add.

**Comment by aschran** [comment]
Yes, I think those issues cover my request, ty! If there's a better existing approach than the response flags and encoder hacks I'm using now that would be cool, but if the answer is just, "it's a known feature request," I'm happy!
