### ISSUE TITLE
bazel/README.md references "envoy-static.stripped.stamped" which doesn't exist

### ISSUE THREAD

**Issue by tehranian** [envoyproxy/envoy#4695]
*Title*: `bazel/README.md` references `envoy-static.stripped.stamped` which doesn't exist

*Description*:
From the instructions for building a Release Build at https://github.com/envoyproxy/envoy/blame/master/bazel/README.md#L333 :

> bazel --bazelrc=/dev/null build -c opt //source/exe:envoy-static.stripped.stamped

But when I run this I get:
```
ERROR: no such target '//source/exe:envoy-static.stripped.stamped': target 'envoy-static.stripped.stamped' not declared in package 'source/exe' defined by /jenkins/src/envoy/source/exe/BUILD
```

From https://github.com/envoyproxy/envoy/blob/master/ci/do_ci.sh#L17, looks like the correct instructions for a release build are to build `//source/exe:envoy-static` (line 20), then run `strip` on the resulting binary (line 32)?

Please confirm and I'm happy to update the README with corrected instructions. Thanks!

**Comment by htuch** [comment]
I think this was in https://github.com/envoyproxy/envoy/pull/3021, @jmillikin-stripe can probably provide the insight. Yeah, I think a doc fix is the right thing here.

**Comment by jmillikin-stripe** [comment]
Yes, the docs are out of date -- `//source/exe:envoy-static.stripped` is the correct path. You can append `.stripped` to any C++ binary target to get a stripped output, no need to strip manually.
