### ISSUE TITLE
//test/common/ssl:utility_test appears broken for me in clean checkout

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#4703]
*Description*:
>I wonder if this is a time-zone issue or maybe the cert file is now a day older:
```
[ RUN      ] UtilityTest.TestDaysUntilExpiration
test/common/ssl/utility_test.cc:55: Failure
Expected equality of these values:
  270
  Utility::getDaysUntilExpiration(cert.get())
    Which is: 269
[  FAILED  ] UtilityTest.TestDaysUntilExpiration (0 ms)
```

It also is failing in CI on unrelated PRs. This appears to be related to @ramaraochavali 's #4686 

I'm also not sure if that's somehow measuring against the current time. I peeked at the code and didn't see how it was pulling the current time; maybe it's in
```
ASN1_TIME_diff(&days, &seconds, nullptr, X509_get_notAfter(cert))
```

*Repro steps*: `bazel test //test/common/ssl:utility_test`

**Comment by ramaraochavali** [comment]
@jmarantz  @lizan  has fixed it alredy. The PR for the fix https://github.com/envoyproxy/envoy/pull/4701.
