### ISSUE TITLE
Support multi tenant route configuration selection based on HTTP attributes

### ISSUE THREAD

**Issue by AndresGuedez** [envoyproxy/envoy#4704]
*Problem Statement*

Envoy currently supports route configuration isolation in multi tenant environments by allowing a Listener FilterChain to specify a FilterChainMatch based on IP, TCP and TLS layer attributes.

When tenancy can be determined via these types of attributes, a FilterChain can be instantiated with a corresponding HttpConnectionManager RouteConfiguration proto (via static config or RDS) that corresponds to the tenant.

This issue tracks a design proposal to also support tenant differentiation via HTTP layer attributes, such that a single Listener -> HttpConnectionManager filter can be used to process requests for multiple tenants, each of which must be assigned its own RouteConfiguration.

*Design Proposal*

The [design proposal](https://docs.google.com/document/d/1PMy5NWWq1A5YIgauc_mV0mZuWv0ZWcpLTYlUMQs0O1U/edit?usp=sharing) extends Envoy with a Scoped Route Discovery Service API, which supports creating route configuration "scopes" indexed via a dynamically generated key extracted from HTTP layer attributes.

The proposed enhancement can be used to satisfy other use cases as well, such as #4690.

**Comment by htuch** [comment]
This has +1 from me and other Googlers, so looking for community input.

**Comment by mattklein123** [comment]
+1. I had one question about SRDS vs. building directly into RDS, and it seems to me the real problem is incremental delivery. There was discussion in the doc about field deprecation for this approach which I didn't fully understand and might be clarified a bit.

**Comment by AndresGuedez** [comment]
@htuch @mattklein123 thanks for the reviews and feedback.

I responded to comments in the doc and made some adjustments based on the feedback. I have been tied up with other work, but will be starting with implementation work on this shortly.

**Comment by htuch** [comment]
LGTM, anyone else wants to weigh in before we move forward? CC @envoyproxy/maintainers

**Comment by AndresGuedez** [comment]
Implementation work is ongoing. I am working on tests for the first PR which I am targeting for next week, although US holidays and a higher priority task are likely to delay this until the week after.

**Comment by mattklein123** [comment]
@AndresGuedez is this issue done or is there further work to do?

**Comment by AndresGuedez** [comment]
@stevenzzzz is working on two more PRs for this: #7451 is out for review now.

**Comment by wbpcode** [comment]
Although this scheme can well classify route configurations based on HTTP attributes, I am a bit skeptical about whether it really works for multi-tenant scenarios. For example, if I have five hundred tenants, different tenants have only one plugin with different configurations, and all other configurations are the same. So based on this solution, I need to create five hundred scopes, copy all the configurations to five hundred copies, and only one plugin configuration is different in all copies. @mattklein123 @AndresGuedez

**Comment by htuch** [comment]
@wbpcode this is probably a distinct problem to what SRDS wants to solve. I think you're interested in deduplication of shared configuration across distinct `RouteConfiguration`s. That's pretty interesting to think about. There are also alternatives, e.g. using lazy loading via SRDS when implemented, and only having the working set of configurations in memory, reducing the need to scale to very large numbers of configurations.

**Comment by mattklein123** [comment]
I think this is done so closing this and we can track other improvements in new issues.
