### ISSUE TITLE
format: check/fix braces for all control statements

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4706]
See https://github.com/envoyproxy/envoy/commit/c4291868bacc3be92f36dd4bfe2aa616dacbb2ba#commitcomment-30879761.

I would have though clang-format could do this, or maybe clang-tidy, but I've never seen such an option. cc @jmarantz @lizan

**Comment by lizan** [comment]
clang-tidy can do this: [readability-braces-around-statements](https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html), not ware of any clang-format option can do.

**Comment by mattklein123** [comment]
Nice! Turn it on. :)

**Comment by lizan** [comment]
addressed in #4666
