### ISSUE TITLE
Stronger API semantic versioning guarantees

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#4710]
Today, we use proto namespaces to express versioning, with `v2alpha` reserved for experimental protos and `v2` for stable.

By "stable", we mean that protos are subject to the normal restrictions on wire-level backwards compatibility for proto, see https://github.com/envoyproxy/envoy/blob/master/api/STYLE.md, and that any field removal or semantic change is subject to Envoy's breaking change policy, see https://github.com/envoyproxy/envoy/blob/master//CONTRIBUTING.md#breaking-change-policy.

So far, most field removals have been done in support of alternative API features with supersets of removed functionality. This allows config translators in xDS generation pipelines to continue to function. 

There are two problems we have with the above:
1. There is no stated API guarantee that we won't remove support for features at the semantic level across Envoy releases. This means that if Envoy consumer X offers feature A in their own APIs to their customers with a guarantee of N years support, and Envoy turns down A in a 3 month cycle deprecation cycle, then the Envoy consumer can't offer its stronger API guarantees to its customers.
2. It's difficult to reason about API status based on Envoy release version, since this is not expressed directly in the protos or wire format.

I think we should have a stronger policy statement for (1), e.g. "you can only remove in favor of superset capabilities that can be mechanically translated to" and for (2) start to make use of `.v3` or `.v2.1` etc. to version at proto level.

**Comment by htuch** [comment]
For consideration by @envoyproxy/maintainers and community.

**Comment by mattklein123** [comment]
> I think we should have a stronger policy statement for (1), e.g. "you can only remove in favor of superset capabilities that can be mechanically translated to" and for (2) start to make use of .v3 or .v2.1 etc. to version at proto level.

Yes I think this makes sense. In practice, I think this is largely what we have done, though it hasn't been codified. (When we did v2, I know there were a few small things that were dropped from v1, but those were things that we hard a strong feeling that only Lyft was using).

If someone wants to codify this into a PR change to https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md#breaking-change-policy that would be great, or I can draft something when I'm back in 2 weeks.

As part of this work, I do think we should have some policy/verbiage on feature removal. I.e., I don't think we should say that we will never remove features. Removing things may make sense over the lifetime of the project. For this we should have a procedure in which we ask for community comment, perhaps give X months notice, etc. Needs more thinking.

**Comment by htuch** [comment]
@mattklein123 SGTM, will work on a PR next week to codify the semantic no break for `v2`. I think the idea is that if we do feature removal, at the API level, we must bump to `v2`+.

I think for practical purposes, we should always say something like "v2 + <Envoy point release version>" when referring to an Envoy API state, since that is the clearest characterization of the expected field semantics. This is not reflected in any structured way in the protos however.
