### ISSUE TITLE
ads protocol violation makes Envoy hang for 5 mins before closing stream

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4716]
*Description*:
We have a EDS type of cluster defined in bootstrap config that uses ADS for discovery.
  - name: zipkin_cluster
    connect_timeout: 0.25s
    type: EDS
    eds_cluster_config:
      eds_config: {ads: {}}
      service_name: zipkin
    lb_policy: LEAST_REQUEST

When Envoy starts and there are network issues and connection to management server is fragile, we see the following behaviour
- Because this cluster is defined in bootstrap, Envoy tries to establish ADS stream and get its Endpoints.
- Initial Stream is established but management server was not able to send the response back because of network issue.
- We have a Cluster Scraper background task that sends clusters to Envoy continuously in the background. Since there is an established stream, it sends Clusters
- However Envoy was expecting ClusterLoadAssignment response and it treats this as a protocol violation and does not respond back.
- Envoy stuck in this mode for 5 mins (stream-idle-timeout) and disconnects, which allows the communication to reestablish. 

See the highlighted log lines below.

*Logs*:
2018-09-18T09:14:27.673+0000 info source/server/configuration_impl.cc:60 loading 0 listener(s)
2018-09-18T09:14:27.673+0000 warning source/common/config/grpc_mux_impl.cc:41 Unable to establish new stream
2018-09-18T09:14:27.673+0000 warning source/common/config/grpc_mux_impl.cc:240 gRPC config stream closed: 14, no healthy upstream
2018-09-18T09:14:27.673+0000 info source/server/configuration_impl.cc:50 loading 0 static secret(s)
2018-09-18T09:14:27.673+0000 info source/server/server.cc:206 transport_sockets.upstream: envoy.transport_sockets.capture,raw_buffer,tls
2018-09-18T09:14:27.673+0000 info source/server/server.cc:203 transport_sockets.downstream: envoy.transport_sockets.capture,raw_buffer,tls
2018-09-18T09:14:27.673+0000 info source/server/server.cc:200 tracers: envoy.dynamic.ot,envoy.lightstep,envoy.zipkin
2018-09-18T09:14:27.673+0000 info source/server/server.cc:198 stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
2018-09-18T09:14:27.674+0000 info source/common/upstream/cluster_manager_impl.cc:111 cm init: initializing secondary clusters""}"
2018-09-18T09:14:27.674+0000 info source/server/server.cc:418 starting main dispatch loop
2018-09-18T09:14:27.674+0000 info source/server/configuration_impl.cc:116 loading stats sink configuration
**2018-09-18T09:15:01.513+0000 warning source/common/config/grpc_mux_impl.cc:167 Ignoring unknown type URL type.googleapis.com/envoy.api.v2.Cluster
2018-09-18T09:20:01.461+0000 warning source/common/config/grpc_mux_impl.cc:240 gRPC config stream closed: 13**
2018-09-18T09:20:01.561+0000 info source/common/upstream/cluster_manager_impl.cc:130 cm init: initializing cds

**Comment by ramaraochavali** [comment]
I think it is better to reset the stream when such protocol issue happens, so that it can establish connection immediately with out waiting for stream_idle_timeout. 
Also is there a way to to control the stream_idle_timeout for AsyncClient and Stream used for ADS?

**Comment by htuch** [comment]
@ramaraochavali I think the correct behavior here is for Envoy to accept Clusters earlier. It should always be listening for Clusters/Listeners, even if the ClusterManager isn't initialized yet; these early assignments should be stored for later initialization. It seems fragile to have the management server needing to be aware of the minutae of Envoy's initialization sequence.

**Comment by htuch** [comment]
@ramaraochavali I think we could have ClusterManager/ListenerManager listen-and-accumulate at construction.

I think ADS specific stream timeouts aren't possible today. This is because we instantiate the HTTP async client using a synthetic configuration that doesn't look at the HCM or router settings. We'd probably want some additional setting in `ApiConfigSource`; there exists https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/config_source.proto#L49, maybe we could repurpose it for gRPC?

**Comment by ramaraochavali** [comment]
@htuch Ok. So we need to change the initialisation of ClusterManager/ListenerManager. I will see when I can get to it. Let us keep this issue open for that.
Regarding ADS stream timeouts, thinking further I am not sure if we want to configure a lower value because it is long running stream with possible periods of in activity and lower value could make it disconnected quite regularly and a higher value may not help in this case? So leaving it as is may be better? I think some thing weird happend on this occasion which kept the stream hanging for 5 mins - ideally ADS would detect the loss of connection immediately, right? - Any thoughts?

**Comment by ramaraochavali** [comment]
@htuch Another similar thing happened at one point to us, after the initial stream established, no exchange happened - So cluster scraper also could not send any clusters because of network. And the stream timed out after 5 mins, after that every thing is normal. So I am guessing, does the stream get in to some hung state? Why the network disconnection is not detected and ADS restablish the connection that it typically does? There is no log indicating disconnection and after 5 mins it times out - makes me think that it is in some kind of hung state. Any thoughts on this as well?

**Comment by ramaraochavali** [comment]
Ok. Thank you. Will check the TCP settings part but I doubt because with the same settings we did not see any issues till now. Is there any to know if it the case of stream hang after establishment? While based on what I have seen in these two instances, I am positive that it could the case, but not sure how to confirm that. Will let you know if I find any thing.

**Comment by htuch** [comment]
@ramaraochavali not that I know of. If it's not network level, it's likely related to some race or interaction with Envoy init. If you can capture the network activity when this happens it would be awesome.

**Comment by ramaraochavali** [comment]
@htuch Ok. Sure..Will let you know what I can find.
