### ISSUE TITLE
Make gRPC response code configurable when rate limiting occurs

### ISSUE THREAD

**Issue by nikolay-pshenichny** [envoyproxy/envoy#4735]
Current envoy implementation returns `UNAVAILABLE` if a gRPC call was rate-limited (rate limit service responded with `OVER_LIMIT`). This behavior matches the [HTTP to gRPC Status Code Mapping](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md) , but may not always be what a "client" wants to see ( [Google Cloud documentation](https://cloud.google.com/apis/design/errors#generating_errors) suggests mapping 429 to `RESOURCE_EXHAUSTED`).

***Use cases***:
- a client service needs to know more details in order to pick the right retry policy, or not retry the call at all.
- a service owner needs to know more details about why a gRPC call failed.

***Feature request details***:

This feature request is to make the gRPC response code configurable for the scenarios when a gRPC call was rate-limited by Envoy on the server-side.

Suggested config option names: `rate_limited_response_code` or just `response_code`
Suggested choices: `UNAVAILABLE` (default) and `RESOURCE_EXHAUSTED`
Suggested location for the new config option: [config.ratelimit.v2.RateLimitServiceConfig](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/ratelimit/v2/rls.proto#L12)  

***Relevant Links***:

- triggered by - https://github.com/envoyproxy/envoy/issues/4660
- [Google Cloud documentation. Generating Errors.](https://cloud.google.com/apis/design/errors#generating_errors)

**Comment by venilnoronha** [comment]
I'd like to work on this.

**Comment by ramaraochavali** [comment]
@venilnoronha How are you planning to fix this? Are you planning to introduce the config in rate limiting service configuration for this specific status and return the status accordingly or are you planning to provide a higher level config that selects one of grpc code state mapping that applies to all services/status codes?

**Comment by venilnoronha** [comment]
I'm thinking in the direction of a generic status mapping approach, as there are a few statuses that map to `UNAVAILABLE`. See https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.

**Comment by lizan** [comment]
Looks like gRPC C core does map 429 to `RESOURCE_EXHAUSTED`:
https://github.com/grpc/grpc/blob/master/src/core/lib/transport/status_conversion.cc#L82

But Java and Go does map 429 to `UNAVAILABLE`:
https://github.com/grpc/grpc-java/blame/master/core/src/main/java/io/grpc/internal/GrpcUtil.java#L305
https://github.com/grpc/grpc-go/blob/cfb96008516cbda549042f43fdd23befea331172/internal/transport/http_util.go#L91

This is confusing so I would recommend to double check with gRPC maintainers.

Aside from that, it might be useful anyway by adding a response status (HTTP/gRPC) in `RateLimitResponse`, so the rate limit service can override the status code Envoy send to downstream.

**Comment by ramaraochavali** [comment]
@lizan Yes, We should check with gRPC maintainers and sort that confusion. On the Envoy side implementation instead of doing specific status code mappings at specific services as needed, can we have couple of well known mappings and allow the user to choose one via CLI/bootstrap? This may be more generic than implementing some thing specific to rate limit. WDYT?

**Comment by lizan** [comment]
@ramaraochavali Given the only deviation is mapping of HTTP 429 Too Many Requests, I doubt there is a need for generic code mapping override. IMO making rate limit service respond custom status code is more usable in long term, just like we added header there before.

**Comment by ramaraochavali** [comment]
@lizan See the status mapping here in Envoy https://github.com/envoyproxy/envoy/blob/15706964a29e595c045a5d7ef0646d04f347dcc1/source/common/grpc/status.cc#L6. It maps currently maps 429, 502,503 and 504 to UNAVAILABLE as per https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md. However this https://cloud.google.com/apis/design/errors#generating_errors maps 504 to DEAD_LINE_EXCEEDED for example. Should we handle that difference as well?
Related issue https://github.com/envoyproxy/envoy/issues/3619
