### ISSUE TITLE
perf: export mutex contention in a stat

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#4742]
*Description*:
>A fairly significant effort is spent in Envoy avoiding mutex contention. And abseil mutexes actually track this, but we don't export the data. See https://github.com/abseil/abseil-cpp/blob/5b70a8910b2e6fb0ce5193a41873139a126d2f7f/absl/synchronization/mutex.h#L955 which should be fairly easy to hook into stats.

This would enable us to evaluate how much contention are we getting currently and what would we get in the face of proposed changse.

@ambuc do you want to take a look in your spare time?

**Comment by ambuc** [comment]
Yes, please assign this issue to me.
