### ISSUE TITLE
header map: allow extensions to statically register O(1) headers

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#4815]
Right now if we want an O(1) header it has to be added to the core header map. This is unfortunate for extension writers who might want this perf boost but either can't add it due to private code, or as we move away from having extensions modify the core code in any way, will be blocked from adding it.

I believe it should be possible to allow extension O(1) headers to be added. A rough implementation outline is:
1) Allow the struct of O(1) headers to be variable sized and zero initialized.
2) Each O(1) header is statically registered with a handle and a slot index into the array, as well as the lookup trie.
3) Allow extensions to statically register and get their own slot.

**Comment by cpakulski** [comment]
I can implement it if this functionality is still needed.

**Comment by mattklein123** [comment]
@cpakulski I would like to implement this, but it will take some thinking on how to do it. I think roughly there needs to be some way for core code / extensions to statically register headers and return some type of map slot ID (it would be opaque) with potentially the well named functions just wrappers around known IDs. All of the registered headers would determine the size of the O(1) memory block and the ID is an index into the block.

Anyway, ^ is my rough thinking, but I haven't tried to implement it. It will be tricky.

**Comment by cpakulski** [comment]
@mattklein123 Thanks for explaining. Let me analyze the code and come up with prototype. I assume that because of the direct impact on the performance, O(1) is most crucial factor here,.

**Comment by mattklein123** [comment]
> I assume that because of the direct impact on the performance, O(1) is most crucial factor here

Generally yes, but the main thing that I like about this is we can likely shrink the size of the header block to just the headers that are actually used in the code. There are a bunch of them that are only used by extensions I think.

With that said, I know there have been other proposals for header map performance options including perfect hashes vs. the trie and some other stuff. cc @brian-pane @jmarantz

**Comment by cpakulski** [comment]
I am looking at https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/header_map.h. Please correct me if I am wrong - the goal here is to add to the map only whatever is used in core code and allow extensions to add their headers dynamically. Lookup must be O(1).

**Comment by mattklein123** [comment]
Yes that is the rough idea. I'm not sure if it's easily possible. I think it is, but it needs some thinking on approaches.

**Comment by jmarantz** [comment]
IMO the first thing to do is to create a microbenchmark for header_map, so
we can talk quantitatively about performance under various scenarios. I
keep meaning to write one but have not gotten the chance to. I would be
happy to be a reviewer on the code if you want to take it on.

Josh

**Comment by cpakulski** [comment]
Sounds like good idea. I am staring to work on this.

**Comment by jmarantz** [comment]
@cpakulski I totally overlooked that there is already a header-map microbenchmark:
test/common/http:header_map_impl_speed_test

I'm hoping you saw that before spending too much time writing a new one. Results on my machine:
```
-----------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations
-----------------------------------------------------------------------
HeaderMapImplCreate                8.39 ns         8.39 ns     73354336
HeaderMapImplSetReference/0        25.3 ns         25.3 ns     27578107
HeaderMapImplSetReference/1        31.5 ns         31.5 ns     22165460
HeaderMapImplSetReference/10       83.4 ns         83.4 ns      8373176
HeaderMapImplSetReference/50        229 ns          229 ns      3061350
HeaderMapImplGet/0                 4.35 ns         4.35 ns    160782605
HeaderMapImplGet/1                 9.31 ns         9.31 ns     74677256
HeaderMapImplGet/10                63.4 ns         63.4 ns     11028053
HeaderMapImplGet/50                 197 ns          197 ns      3563356
HeaderMapImplGetInline/0           1.14 ns         1.14 ns    611897825
HeaderMapImplGetInline/1           1.15 ns         1.15 ns    610605605
HeaderMapImplGetInline/10          1.14 ns         1.14 ns    611158958
HeaderMapImplGetInline/50          1.15 ns         1.15 ns    610537037
HeaderMapImplSetInline/0           3.98 ns         3.98 ns    175216922
HeaderMapImplSetInline/1           3.99 ns         3.99 ns    175586002
HeaderMapImplSetInline/10          3.99 ns         3.99 ns    175655634
HeaderMapImplSetInline/50          3.98 ns         3.98 ns    175240321
HeaderMapImplGetByteSize/0         2.07 ns         2.07 ns    338555664
HeaderMapImplGetByteSize/1         3.44 ns         3.44 ns    203524965
HeaderMapImplGetByteSize/10        24.3 ns         24.3 ns     28826868
HeaderMapImplGetByteSize/50         121 ns          121 ns      5786364
HeaderMapImplIterate/0             1.63 ns         1.63 ns    428487410
HeaderMapImplIterate/1             2.29 ns         2.29 ns    305500510
HeaderMapImplIterate/10            14.6 ns         14.6 ns     47703528
HeaderMapImplIterate/50            74.3 ns         74.3 ns      9385966
HeaderMapImplLookup/0              10.8 ns         10.8 ns     64510342
HeaderMapImplLookup/1              10.8 ns         10.8 ns     64453395
HeaderMapImplLookup/10             10.8 ns         10.8 ns     64509337
HeaderMapImplLookup/50             10.8 ns         10.8 ns     64422839
HeaderMapImplRemove/0              28.0 ns         28.0 ns     24980636
HeaderMapImplRemove/1              33.8 ns         33.8 ns     20670170
HeaderMapImplRemove/10             85.7 ns         85.7 ns      8156818
HeaderMapImplRemove/50              231 ns          231 ns      3024086
HeaderMapImplRemoveInline/0        48.4 ns         48.4 ns     14418240
HeaderMapImplRemoveInline/1        47.9 ns         47.9 ns     14616045
HeaderMapImplRemoveInline/10       48.6 ns         48.6 ns     14406439
HeaderMapImplRemoveInline/50       49.0 ns         49.0 ns     14296428
HeaderMapImplPopulate               288 ns          288 ns      2428871
```

**Comment by cpakulski** [comment]
Thank you! I was mostly analyzing implementation code hoping to write benchmark in few days. Good timing!

**Comment by mattklein123** [comment]
> There will be a new API to add (register) a header for O(1) lookup. I assume that registration will happen when an extension is used (via configuration). If an extension is not used, registration for O(1) lookup will not happen, even though extension code is compiled-in. Is this correct assumption?

This needs some thinking but the way I have been thinking about this is that the registration would happen as part of the static extension initialization somehow.

> Continuing on the same note. If during the run-time, the configuration changes and extension is not used any more, it should de-register its headers from O(1) lookup, correct?

It would probably be simpler initially to just have this be a static/compiled thing based on which extensions are loaded. IMO it will be a lot simpler to implement, but I admit I haven't thought through it in a lot of detail.

cc @jmarantz on ^ and whether as part of this work we also want to take a look at testing a perfect hash table vs. the trie.

**Comment by jmarantz** [comment]
I think the trie would be easier to make init-time configurable, where every filter that was initialized would have a chance to add something to the global trie.

With gperf, at least, this needs to be a build-time step where you start with a text file with your keywords and it compiles it into a hash-table implementation that never collides.

I agree with Matt that doing this at static-init time is important because you want to get the table set up before any requests start coming in on multiple threads. We don't want to take a lock for the trie.

It's also worth considering absl::flat_hash_map for the table; it might be pretty fast, and also easy to add to during startup.

**Comment by cpakulski** [comment]
> I agree with Matt that doing this at static-init time is important because you want to get the table set up before any requests start coming in on multiple threads. We don't want to take a lock for the trie.

It makes things much easier to initialize at startup and there is no need for locks/synch objects. 
Is there any compile-time config file which controls which extensions are compiled-in?

**Comment by jmarantz** [comment]
I think the way it works is that statically constructed objects in the filter impl run some code that populates a filter-name -> factory map, and you could at that time add new header names to the trie or whatever.

So it's kind of assembled at link time.

**Comment by cpakulski** [comment]
@jmarantz Thank you for explaining. It makes sense.

As far as I understand, one of the goals of implementing this is to reduce the size of the header block. From comments above:

> Generally yes, but the main thing that I like about this is we can likely shrink the size of the header block to just the headers that are actually used in the code. There are a bunch of them that are only used by extensions I think.

I think that the size of the header block will not shrink, if all compiled filters register their O(1) headers at startup. Basically all O(1) headers for all filters would be registered. In order to reduce the size of the header block, registration should happen in run-time based on configuration or in compile/link time based on some sort of config file.

**Comment by jmarantz** [comment]
This would still benefit deployments that only linked the extensions they wanted to support.

**Comment by mattklein123** [comment]
> This would still benefit deployments that only linked the extensions they wanted to support.

This and also IMO more importantly it would allow custom extensions to get O(1) lookup for custom headers.

**Comment by mattklein123** [comment]
See also https://github.com/envoyproxy/envoy/issues/8795. It might be possibly to also pre-fetch the slots for headers that certain components care about, like tracing tags, logging, and actually remove a bunch of the O(N) get calls. cc @stevenzzzz @antoniovicente @jmarantz

**Comment by cpakulski** [comment]
Sounds good. I have a clear understanding if this issue now.

**Comment by jmarantz** [comment]
See also https://github.com/envoyproxy/envoy/issues/8795 and https://github.com/envoyproxy/envoy/pull/9261/
