### ISSUE TITLE
Allow changing prefix of xDS REST URLs

### ISSUE THREAD

**Issue by berlinsaint** [envoyproxy/envoy#4824]
**Issue Template**

*Title*: *One line description*

*Description*:
 when implement xDS service myself, for example , i will implement interface` POST /v2/discovery:clusters`
, when integrate it to our code , for some reasons, we must give it a urlprefix,  `/api/v2/discovery:clusters`,
so how can i configure this prefix in the `envoy.yaml`, i find that only support for` ip`, or a` hostname`, not support for an `url`..

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
IIRC this is not currently possible but could be added. I thought that maybe a hack/workaround would be to proxy XDS through Envoy itself and do a prefix rewrite, but I don't think that will work well during startup.
