### ISSUE TITLE
Envoy cannot parse non-alphanumeric characters if not urlencoded

### ISSUE THREAD

**Issue by exiaohao** [envoyproxy/envoy#4854]
*Description*:
Enovy cannot parse Chinese characters in GET requests. (I not sure if other request method have same problem)

*Envoy version*
`82e3541b0cd847724d5088e888ea90fc3f0cb418/1.8.0-dev/Clean/RELEASE`

When envoy received a GET request with Chinese characters like this:
```
$ curl -v http://my-envoy/?message=你好
*   Trying 100.65.128.251...
* Connected to 100.65.128.251 (100.65.128.251) port 80 (#0)
> GET /?message=你好 HTTP/1.1
> Host: 100.65.128.251:80
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< content-length: 0
< connection: close
<
* Closing connection 0
```

Envoy log:
```
[2018-10-25T07:24:18.643Z] "- - HTTP/1.1" 0 - 0 0 0 - "-" "-" "-" "-" "-"
[2018-10-25T07:24:18.878Z] "- - HTTP/1.1" 0 - 0 0 0 - "-" "-" "-" "-" "-"
[2018-10-25T07:24:20.721Z] "- - HTTP/1.1" 0 - 0 0 0 - "-" "-" "-" "-" "-"
...
```

It seems that envoy cannot parse requests with non-urlencoded Chinese characters. 

I know http standard does not allow double-byte character in requests, it must be urlencoded. But we cannot control clients' behavior, is that any way to compatible it?

**Comment by mattklein123** [comment]
> I know http standard does not allow double-byte character in requests, it must be urlencoded. But we cannot control clients' behavior, is that any way to compatible it?

No, not currently. This would require a change to upstream http_parser which I think would end up being very difficult to get them to take.

**Comment by haoxinst** [comment]
https://url.spec.whatwg.org/#concept-url-query

clients' behavior should follow the standards.

**Comment by exiaohao** [comment]
@mattklein123 I've reported issue to ***http-parser***, it would be great if you could help solve it, thx. question label is not suitable in this issue, enhancement label is better.

@haoxinst It's not just a scientific project, but a client-oriented product. As a service provider, we can give out a message explicitly rather than status 400.

**Comment by mattklein123** [comment]
I'm going to go ahead and close this as won't fix as it's against RFC spec. If you can convince http-parser to change (extremely doubtful) we can revisit.

**Comment by sanya2022** [comment]
@cl51287 Hello. Did you find a resolution for this problem?

**Comment by cl51287** [comment]
@sanya2022 No, we let the user urlencode the request
