### ISSUE TITLE
retry of rate limited requests

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4855]
Currently Envoy returns `UnAvailable` to client if a request is rate limited by the rate limited service. However if client Envoy's retry policy says  that `UnAvailable` requests need to retried, the rate limited request will be retried. And once https://github.com/envoyproxy/envoy/issues/4735, we could probably configure it to return `RESOURCE_EXHAUSTED`, But `RESOURCE_EXHAUSTED` can it self be a valid retry options for other cases.
Retry of rate limited requests may not be required. There are couple of options here
1. We could adjust retry policy to exclude `RESOURCE_EXHAUSTED` - but as mentioned above it may be desirable to retry requests that are returned with `RESOURCE_EXHAUSTED` for other reasons.
2. When request is rate limited, Envoy sends a header `x-envoy-ratelimited` similar` to `x-envoy-overloaded` and Envoy can skip retries.

**Comment by mattklein123** [comment]
@ramaraochavali at Lyft we don't run into this as we do very limited rate limiting between services in the mesh (mostly use rate limiting at the edge), but agree this is something we can handle better. I agree something like an x-envoy-ratelimited header could make sense here, or potentially a retry policy that handles this better? Feel free to put together a proposal!

**Comment by ramaraochavali** [comment]
@mattklein123 Sorry for the delay here. Assign this to me,  I will come up with a proposal and follow up with the implementation whenever I get time.

**Comment by mattklein123** [comment]
IMO I think option 1 is better. I really don't think we should be default retrying rate limiting requests.

**Comment by mattklein123** [comment]
@ramaraochavali sorry value in providing which option? In general I would prefer to not retry rate limited requests by default at all. If someone wants to opt-in, I guess that's OK, but I don't recommend it.

**Comment by ramaraochavali** [comment]
@mattklein123 I was referring to supporting the value of even the opt-in behaviour. Was thinking should we just go ahead not retry at all? But as you mentioned, opt-in may be OK if some one wants to use it.

**Comment by mattklein123** [comment]
@ramaraochavali I'm confused. Aren't you implementing this because you want to retry rate limited requests? Or you don't want to retry rate limited requests?

**Comment by ramaraochavali** [comment]
@mattklein123 Sorry for the confusion  :-). We do not want to retry rate limited requests. But they are being retried because we have `retry-grpc-policy` policy that includes both `UNAVAILABLE` and `RESOURCE_EXHAUSTED` (and ratelimit server returns currently `UNAVAILABLE` gRPC code. I want to stop that and make it opt-in. So if a request is rate limited, it has to be explicit choice if it has to be retried irrespective of its gRPC status code.
