### ISSUE TITLE
Help Wanted: How to resolve this node affinity with Envoy?

### ISSUE THREAD

**Issue by cvigo** [envoyproxy/envoy#4897]
*Description*:

We provide some gRPC services that unfortunately have to have node affinity between `BeginTransaction` and `Commit` API Calls.

The Consumer API calls sequence is typically:

 1. `BeginTransaction()` returns `txnID`
 2. `DoStuff(txnID, moreParams...)`
 3. `DoStuff(txnID, moreParams...)`
 4. `...`
 5. `Commit(txnID)`

Consumers can be multithreaded processes that make simultaneous calls to my API, so they might be using hundreds of Transactions at any point in time.

I set up the cluster according to the basic Service to Service plus front proxy described [here](https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/front_proxy) 

If I use Envoy proxy as my Service entry point, `BeginTransaction` should be routed to any healthy node in the cluster, but it must ensure that subsequent calls that use the returned `txnID` are routed to the same node.

Passing any context info in http headers, or in whatsoever part of the messages, is acceptable in my case.

I made some progress using Ring Hash balancer

In the envoy proxy server (look for "hash"):

    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: http2
              stat_prefix: ingress_http #just for statistics
              route_config:
                name: local_route
                virtual_hosts:
                - name: samplefront_virtualhost
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/mycompany.sample.v1"
                      grpc: {}
                    route:
                      cluster: sampleserver
                      hash_policy:
                        header:
                          header_name: "x-session-hash"
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: sampleserver
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: ring_hash
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: sampleserver
            port_value: 80 #Connect to the Sidecard Envoy
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

My consumers create a random hash just before the `BeginTransaction()` call and I make sure it is sent in the `x-session-hash` header every single time until the `Commit(txnId)` call.

It works but it has just one nasty effect:

When I scale up the cluster, adding more nodes, Envoy rebalances the cluster and divert some traffic to the new joiners. This works as expected and started in the documentation. The issue is that some of those traffic divertions might happen (and actually happen) right in the middle of my "transactions", so they are lost.

Is there any way of sorting this out, just configuring Envoys in the right way?

**Comment by lizan** [comment]
This sounds like a case when you want use gRPC streaming. If you use gRPC streaming by aggregating the API calls with same txnId into one gRPC stream, then they will be routed to same node behind Envoy.
