### ISSUE TITLE
AsyncClient returned by httpAsyncClientForCluster() does not follow lb_policy defined for cluster

### ISSUE THREAD

**Issue by shivanshu21** [envoyproxy/envoy#4899]
*Title*: *AsyncClient returned by httpAsyncClientForCluster() does not follow lb_policy defined for cluster*

*Symptom*:
LB Policy configured on a test cluster is RING_HASH, and I observed it was honoured by all calls going through HTTP Connection manager.
But any Async call sent using AsyncClient returned by httpAsyncClientForCluster() from a filter is **not following the same LB policy**. Is this the expected behavior?

*Description*:

Here is what is causing the problem:

In file `upstream/cluster_manager_impl.cc` the constructor of `struct ClusterEntry` is called for each cluster defined in the config when envoy starts up.

 In its initializer list it invokes the constructor of `Http::AsyncClientImpl` to create http_async_client_ for the cluster. http_async_client_ is returned by httpAsyncClientForCluster()  and is used for making Async calls. 

`Http::AsyncClientImpl` creates `AsyncStreamImpl` which creates a mock `Router::ProdFilter router_` and sets a bunch of mock objects on it. One of the mock objects is `struct RouteEntryImpl` which defines `const Router::HashPolicy* hashPolicy() const override { return nullptr; }`.

*During an async call*, when `upstream/thread_aware_lb_impl.cc` chooseHost()  is called, it tries to `computeHashKey()` but in the absence a HashPolicy, it does this:

`const uint64_t h = hash ? hash.value() : random_.random();`

Do you think there a way to make async calls start following the lb_policy for the cluster?

**Comment by mattklein123** [comment]
It does follow the LB policy, the issue is that AsyncClient/Stream doesn't correctly implement the hash policy interface. I think this should be pretty straightforward to fix by sharing the code w/ the normal router filter.

**Comment by shivanshu21** [comment]
I want to take this up.

**Comment by shivanshu21** [comment]
@mattklein123 

I Looked into the code to find ways of implementing hash policy interface in AsyncClient/Stream. HashPolicy is available in route entry as seen before. But it appears like AsyncClient does not receive any information on route or route entry during construction. Route and RouteEntry are a part of StreamDecoderFilterCallbacks. AsyncClient is constructed inside ClusterManager where this information is not present. Please let me know if I am missing something here.

**Here is one possibility to implement hashPolicy interface in AsyncClient/Stream** 

AsyncClient::send() receives an HTTP::MessagePtr which is a pointer to Protobuf::Message. In our case, it carries a header map.
We can add some headers to the HeaderMap in HTTP::MessagePtr to indicate which hash policy object should be constructed inside AsyncClient/Stream/RouteEntry (cookie/header/ip hash) and what is the value of said header or cookie name etc.

If these headers are not present, the code will continue the present behavior. Each Async Call will have to explicitly set these headers in order for the call to go through the proper hash policy.

Can you recommend any other way for doing this, or is this fine?

**Comment by mattklein123** [comment]
> Can you recommend any other way for doing this, or is this fine?

I don't think that is the way to go. Ultimately, the router filter will call back into the AsyncStream for all of the things that it needs when constructing its LBContext. You will need to plumb out the various data that it expects such that the computations look normal to the router filter. Unless I'm missing something I think this should be fairly easily doable.

**Comment by shivanshu21** [comment]
@mattklein123 Sorry about the delay in response.

I am probably missing some link here. I am relatively new, hence the repetitive questions. 

The way I see it, *there is no way to access the correct HashPolicy object from within Async client or even the aforementioned //mock router filter//* as it is not the main router filter that is used to call decodeHeaders()/decodeData() here, it is a separate filter created per async client.

1. When an Async call is made using send() method, it creates an `AsyncRequestImpl` which inherits from `AsyncStreamImpl`.
2. `Router::ProdFilter router_` Is a member of `AsyncStreamImpl`. The decodeHeaders() and decodeData() called to make the actual request are called on this object.
3. When `AsyncStreamImpl` object is created, it calls `router_.setDecoderFilterCallbacks(*this);` This sets Route and RouteImpl inside router_ to dummy values.
4. decodeHeaders/decodeData *will have no way to access HashPolicy* which is stored in the main filter. The filter they are called for is separate and has its own dummy RouteEntry.

Regarding LBContext:
decodeHeaders() calls getConnPool().
LBContext is sent when getConnPool() calls config_.cm_.httpConnPoolForCluster(route_entry_->clusterName(), route_entry_->priority(),protocol, this);
LBContext is the "this" pointer to httpConnPoolForCluster() call. Again it will be the pointer to `Router::ProdFilter router_` which has dummy Route and RouteImpl. Please refer `upstream/cluster_manager_impl.cc ClusterManagerImpl::httpConnPoolForCluster`


It looks like some input param has to be added to send() to add HashPolicy right at the time the Async call is made. What am I missing?

**Comment by mattklein123** [comment]
I would need to look into things in more detail, but I think the key here is that we will need to create a dynamic route for each request that can provide the right hash values. This would be owned by the stream and then router can access it. So there will be some small refactoring needed.

**Comment by mandarjog** [comment]
@lizan This is the issue I was talking about. For consistent hashing to work minimally we need to specify `routeAction.HashPolicy.connection_properties.source_ip` in the current context.
Since asynClient is detached from the normal routing, this could be a synthetic route.
