### ISSUE TITLE
[question] streaming gRPC requests or responses and JSON transcoder 

### ISSUE THREAD

**Issue by ngrigoriev** [envoyproxy/envoy#4900]
*Title*: *Is it possible to deal with the streaming gRPC requests or responses using JSON transcoder and avoid buffering?*

*Description*:
JSON transcoder seems to be doing a great job of, essentially, allowing people to have a service that only implements gRPC-based API to be accessible via both gRPC and REST/JSON. As we know, gRPC has a streaming feature that can be used for the request, response or both. The documentation for the transcoder clearly says that, if I understand it correctly, a streaming request would become an array and the same happens to the response. Thus, the streams would be buffered and converted into a single request/response.

From what I understand, the thing closest to gRPC streaming over HTTP/2 in HTTP < 2.0 world are multipart messages. Is it possible to use the filter (or develop such a filter) that would transcode the streamed gRPC messages to JSON and send them as parts of a multi-part request or response? 

I suspect it may be a long shot. I think it would be great to do something like this, or state it clearly that it is beyond the limits of what can be done with the filter.

Thanks!

**Comment by lizan** [comment]
> a streaming request would become an array and the same happens to the response.

This is right, while

> Thus, the streams would be buffered and converted into a single request/response.

is not always true. The gRPC-JSON filter converts each array element (gRPC frame) when they are available and send to upstream/downstream. In HTTP/2 this will be DATA frames, in HTTP/1.1 this will be chunked transfer encoding.

**Comment by ngrigoriev** [comment]
@lizan 

But a chunk does not really mean a complete fragment, while MIME part does. In HTTP/2 case it would be just a bunch of DATA frames carrying a complete protobuf message.

Anyway, the next question is: does the transcoder buffer the entire message or sends the data as it comes? Lets consider the example when the server sends back a gRPC stream - stream of protobuf messages. Will transcoder wait before the end of stream (or the end of some kind of buffer) before sending out the first byte? Or will it convert the first message to JSON and send it back to the client as a set of one or more chunks?

**Comment by lizan** [comment]
@ngrigoriev It would buffer each message in the stream, but not the entire request/response. It wouldn't wait for end of stream before sending out first byte in streaming case.

**Comment by ngrigoriev** [comment]
Thanks for the clarification, I am going to try it this way to see how it behaves. Probably will post a little demo :)

**Comment by lizan** [comment]
Closing as answered, feel free to open another issue or comment on this one to follow up.
