### ISSUE TITLE
websocket upgrade on a per route basis

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#4921]
*Title*: *websocket upgrades cannot be done on a per route basis*

*Description*:
https://github.com/envoyproxy/envoy/pull/4745 removed `use_websocket` from the route config. This means that now websocket upgrades are now only configurable on a http conn man basis. In order to preserve functionality envoy would need to allow upgrades on a per route basis.

**Comment by mattklein123** [comment]
@alyssawilk are you able to take this one? IMO we should have capability here to what we had previously?

**Comment by junr03** [comment]
@alyssawilk @mattklein123 opening this issue to track what I was talking to both of you today. For Lyft, the current state is ok. However, I am not sure if anyone else in the community was dependent on this feature. This deprecation removed existing functionality, rather than just deprecating the field.

**Comment by alyssawilk** [comment]
Happy to add it if we think it's worthwhile.

**Comment by mattklein123** [comment]
@alyssawilk yeah I think definitely useful. Some folks do not want to expose WS upgrades globally, but want to allow it on a per-route basis.

**Comment by alyssawilk** [comment]
Oh man, so I managed to slog through splitting the hcm proto in to multiple files to avoid dependency loop issues hcm->rcs->route->hcm but looking at the similar problem with the includes directory I think we're either have to violate style and do a bunch of pre-declares and file splitting, or we could just say you can enable websocket on a per-hcm basis and override-disable on a per-route basis.

Lyft folks, you OK with this as a workaround or should I keep fighting the good fight in include/?
