### ISSUE TITLE
Can or should decodeData() be triggered before decodeHeaders() continues?

### ISSUE THREAD

**Issue by qiannawang** [envoyproxy/envoy#4925]
**Issue Template**

*Title*: Can or should decodeData() be triggered before decodeHeaders() continues?

*Description*:
By reading both the comment of FilterHeadersStatus::StopIteration [1] and HCM code [2], it looks like a continue from the decode data (i.e., FilterDataStatus::Continue) will trigger the iteration to the filter chain. This made our Envoy binary crash because we called both FilterDataStatus::Continue from decodeData() and continueDecoding(). Is it true that we should not call continue logic *twice*?

Having that said, it seems more reasonable to me if the Envoy does not iterate decodeData() until decodeHeaders() continues. In addition, the current logic (if I understood correctly) would be easier to make mistakes by developers (like what we did) and crash Envoy.

[1]  https://github.com/envoyproxy/envoy/blob/9ca12b8c1790a7c8af3df9298876e4c5fbfebe1c/include/envoy/http/filter.h#L28
[2]  https://github.com/envoyproxy/envoy/blob/9ca12b8c1790a7c8af3df9298876e4c5fbfebe1c/source/common/http/conn_manager_impl.cc#L1396

**Comment by mattklein123** [comment]
Yes you should not call continue twice. Please feel free to add whatever documentation/asserts/etc. would have helped avoid this.

**Comment by qiannawang** [comment]
Did you mean it is an expected behavior that FilterDataStatus::Continue from decodeData() to trigger decodeHeaders continue? If yes, can you provide an example or the motivation of this use case?

**Comment by mattklein123** [comment]
No, it's just a programmer error that is not being asserted on, failed, etc. There should be more asserts, etc. added to the HCM code. In general the HCM code is light on error checking of bad filter behavior (there are various relevant TODOs in the code).

**Comment by mattklein123** [comment]
> Did you mean it is an expecting behavior that FilterDataStatus::Continue from decodeData() triggers decodeHeaders continue? If yes, can you provide an example or the motivation of this use case?

And sorry, I misread this. Yes, this is expected behavior. The use case here is that you filter wants to stop filter iteration until it looks at body (and possible change body) and then continue iteration to subsequent filters, which most get headers, then data, etc.

The idea is that you only call continueDecode/Encode if you are doing it from an async callback, and not from within a filter direct callback.

**Comment by qiannawang** [comment]
Thanks for the explanation of the use case. I will take my proposal back of simplifying the filter. It makes sense to depend on the developer to make sure no more than one continue. Adding more assert would help though.

**Comment by htuch** [comment]
@mattklein123 this use case is pretty subtle and not very obvious to filter authors. How can we make this flow clearer?

**Comment by mattklein123** [comment]
> @mattklein123 this use case is pretty subtle and not very obvious to filter authors. How can we make this flow clearer?

As I already mentioned I think we can have more asserts when filters do the wrong thing as well as more verbose documentation.
