### ISSUE TITLE
Expose downstream cert details in gRPC access logs

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4926]
We're interested in having downstream cert details (OUs, CNs, SANs) be included in the gRPC access log. We'd be interested in both sides of the TLS handshake, so we want details about both the client cert used to establish the connection and details about the server cert that was used by Envoy.

To accomplish this, we'd probably have to expose either the `Ssl::Connection` or some smaller data structure containing the necessary data on `StreamInfo`. This would allow any access log to include this information, including the gRPC access log.

The access log would have to be extended. Here's a suggestion: 

```
message CommonCertDetails {
  string ou = 1;
  string cn = 2;
  repeated san = 3;
}

message CertDetails {
  // Details about client cert.
  CommonCertDetails peer_certificate = 1;
  // Details about local server cert.
  CommonCertDetails local_certificate = 2;
}
```

This could then be included on the `data.accesslog.v2.AccessLogCommon` proto with a `downstream_cert_details` field. 

cc @worldwise001 (let me know if i forgot anything)

**Comment by lizan** [comment]
> To accomplish this, we'd probably have to expose either the `Ssl::Connection` or some smaller data structure containing the necessary data on `StreamInfo`. This would allow any access log to include this information, including the gRPC access log.

This sounds reasonable, while `Ssl::Connection` is named "connection", it is actually a bunch of properties of TLS connection info after I factored out transport socket. So we can just rename it and put into StreamInfo/FilterState (TLS transport socket should be able to write it with "write once" semantics).

**Comment by worldwise001** [comment]
I am happy to take this over from @snowp instead since I made the original request to him, and am willing to take a crack at this.

**Comment by snowp** [comment]
We're still planning on adding this, just haven't gotten around to it yet.

**Comment by snowp** [comment]
@worldwise001 Will you be able to pick this up anytime soon? If not, we can get this marked as help wanted in case someone else wants to pick it up, it seems like a generally useful feature.

**Comment by mattklein123** [comment]
Fixed
