### ISSUE TITLE
nan appearing in /stats histogram values 

### ISSUE THREAD

**Issue by yob** [envoyproxy/envoy#4936]
We've deployed contour 0.7 as an ingress controller on GKE, which uses envoy 1.7.0. We also run the datadog agent in the cluster to collect metrics, and have configured it to collect envoy metrics using the `/stats` endpoint.

Most data that's returned in the `/stats` response is appearing in datadog, however most of the histogram data does not. Here's a snapshot of the histogram data: note the `nan` values. 

```
# curl -s "10.36.2.211:8002/stats" | grep P0
cluster.aemo-api/aemo-feed-prod/80/da39a3ee5e.external.upstream_rq_time: P0(nan,25) P25(nan,27) P50(nan,30.5) P75(nan,36) P90(nan,112) P95(nan,116) P99(nan,119.2) P99.9(nan,119.92) P100(nan,120)
cluster.aemo-api/aemo-feed-prod/80/da39a3ee5e.upstream_cx_connect_ms: P0(nan,0) P25(nan,0) P50(nan,1.03333) P75(nan,1.1) P90(nan,2.06) P95(nan,2.08) P99(nan,2.096) P99.9(nan,2.0996) P100(nan,2.1)
cluster.aemo-api/aemo-feed-prod/80/da39a3ee5e.upstream_cx_length_ms: P0(nan,30000) P25(nan,30250) P50(nan,30500) P75(nan,30750) P90(nan,30900) P95(nan,30950) P99(nan,30990) P99.9(nan,30999) P100(nan,31000)
cluster.aemo-api/aemo-feed-prod/80/da39a3ee5e.upstream_rq_time: P0(nan,25) P25(nan,27) P50(nan,30.5) P75(nan,36) P90(nan,112) P95(nan,116) P99(nan,119.2) P99.9(nan,119.92) P100(nan,120)
cluster.contour.upstream_cx_connect_ms: P0(nan,2) P25(nan,2.025) P50(nan,2.05) P75(nan,2.075) P90(nan,2.09) P95(nan,2.095) P99(nan,2.099) P99.9(nan,2.0999) P100(nan,2.1)
cluster.service_stats.external.upstream_rq_time: P0(1,1) P25(1.03333,1.02715) P50(1.06667,1.05429) P75(1.1,1.08144) P90(2.06,1.09773) P95(2.08,2.04451) P99(2.096,3.0922) P99.9(2.0996,10.761) P100(2.1,35)
cluster.service_stats.upstream_cx_connect_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.9(nan,0) P100(nan,0)
cluster.service_stats.upstream_rq_time: P0(1,1) P25(1.03333,1.02715) P50(1.06667,1.05429) P75(1.1,1.08144) P90(2.06,1.09773) P95(2.08,2.04451) P99(2.096,3.0922) P99.9(2.0996,10.761) P100(2.1,35)
cluster.weather-prod/weather/80/da39a3ee5e.external.upstream_rq_time: P0(nan,4) P25(nan,137.361) P50(nan,173.182) P75(nan,284.464) P90(nan,482.111) P95(nan,622.25) P99(nan,906.9) P99.9(nan,3216.9) P100(nan,3300)
cluster.weather-prod/weather/80/da39a3ee5e.upstream_cx_connect_ms: P0(nan,0) P25(nan,0) P50(nan,1.03538) P75(nan,1.09962) P90(nan,11.6) P95(nan,26.3) P99(nan,51.66) P99.9(nan,63.666) P100(nan,64)
cluster.weather-prod/weather/80/da39a3ee5e.upstream_cx_length_ms: P0(nan,20000) P25(nan,20394.5) P50(nan,20789.1) P75(nan,22519.2) P90(nan,25140) P95(nan,29918.7) P99(nan,41708.8) P99.9(nan,59667) P100(nan,60000)
cluster.weather-prod/weather/80/da39a3ee5e.upstream_rq_time: P0(nan,4) P25(nan,137.361) P50(nan,173.182) P75(nan,284.464) P90(nan,482.111) P95(nan,622.25) P99(nan,906.9) P99.9(nan,3216.9) P100(nan,3300)
http.admin.downstream_rq_time: P0(1,0) P25(1.03333,1.01441) P50(1.06667,1.04383) P75(1.1,1.07324) P90(2.06,1.09089) P95(2.08,1.09678) P99(2.096,2.09756) P99.9(2.0996,7.0761) P100(2.1,25)
http.ingress_http.downstream_cx_length_ms: P0(nan,20) P25(nan,141.987) P50(nan,229.5) P75(nan,422.5) P90(nan,518.714) P95(nan,638.643) P99(nan,1661) P99.9(nan,9816.1) P100(nan,9900)
http.ingress_http.downstream_rq_time: P0(nan,0) P25(nan,134.952) P50(nan,170.758) P75(nan,280.893) P90(nan,479.8) P95(nan,608.167) P99(nan,904.9) P99.9(nan,3214.9) P100(nan,3300)
http.ingress_https.downstream_cx_length_ms: P0(nan,120) P25(nan,133.333) P50(nan,140) P75(nan,230) P90(nan,282) P95(nan,286) P99(nan,289.2) P99.9(nan,289.92) P100(nan,290)
http.ingress_https.downstream_rq_time: P0(nan,26) P25(nan,28) P50(nan,31.5) P75(nan,37) P90(nan,112) P95(nan,116) P99(nan,119.2) P99.9(nan,119.92) P100(nan,120)
http.stats.downstream_cx_length_ms: P0(0,0) P25(0,0) P50(2.1,0) P75(3.075,0) P90(5.04,2.09345) P95(5.07,3.07248) P99(5.094,22.56) P99.9(5.0994,93.2187) P100(5.1,130)
http.stats.downstream_rq_time: P0(0,0) P25(0,0) P50(1.03333,0) P75(1.08333,0) P90(2.04,1.04713) P95(2.07,1.08128) P99(2.094,2.06565) P99.9(2.0994,6.0664) P100(2.1,35)
listener.0.0.0.0_8002.downstream_cx_length_ms: P0(0,0) P25(0,0) P50(2.05,0) P75(3.05,0) P90(5.04,2.08768) P95(5.07,3.06889) P99(5.094,22.56) P99.9(5.0994,92.8853) P100(5.1,130)
listener.0.0.0.0_8080.downstream_cx_length_ms: P0(nan,20) P25(nan,141.987) P50(nan,229.5) P75(nan,422.5) P90(nan,518.714) P95(nan,638.643) P99(nan,1661) P99.9(nan,9816.1) P100(nan,9900)
listener.0.0.0.0_8443.downstream_cx_length_ms: P0(nan,120) P25(nan,133.333) P50(nan,140) P75(nan,230) P90(nan,282) P95(nan,286) P99(nan,289.2) P99.9(nan,289.92) P100(nan,290)
```

The datadog envoy code appears to skip any histogram value that includes nan (see https://github.com/DataDog/integrations-core/blob/63db044b05a39802e6e378233f69b447a3288ea2/envoy/datadog_checks/envoy/parser.py#L116), which may explain why we're not seeing the histogram data on our dashboards.

I can see mention of nans in some issues (like https://github.com/envoyproxy/envoy/pull/3445), but I'm not clear if it's expected for them to appear, and what they indicate.

Is there something I can change that will avoid the nan values, so datadog can collate the data for me?

**Comment by yob** [comment]
Thanks, so maybe this should be an issue I open in the datadog integration repo then?

If we look at this line:

```
cluster.weather-prod/weather/80/da39a3ee5e.upstream_rq_time: P0(nan,4) P25(nan,137.361) P50(nan,173.182) P75(nan,284.464) P90(nan,482.111) P95(nan,622.25) P99(nan,906.9) P99.9(nan,3216.9) P100(nan,3300)
```

What do the first and second numbers for each percentile indicate?

Is there value in datadog collecting the second values (4, 137.361, 173.182, 284.464, 482.111, etc), even if all the first values are `nan`?

**Comment by ramaraochavali** [comment]
Yes. First value represents the value of the histogram in that interval
(from last time it collected, right now it is 1 min) and second value
represents the cumulative value( from the envoy start) - So it depends on
what you are looking for

**Comment by yob** [comment]
Apologies for cluttering your issue tracker with questions. If there's somewhere else I can direct these, please let me know.

> Yes. First value represents the value of the histogram in that interval (from last time it collected, right now it is 1 min) and second value represents the cumulative value( from the envoy start)

Ah. This is super helpful to know, thanks.

The cluster I'm testing with is roughly  serving a request every few seconds. I notice that if I manually fetch the stats from envoy in a slow loop, I occasionally get a line that has a value for both numbers in the histograms:

```
cluster.weather-prod/weather/80/da39a3ee5e.upstream_rq_time: P0(1000,1) P25(1025,147.969) P50(1050,200.161) P75(1075,323.938) P90(1090,462.669) P95(1095,565.715) P99(1099,940.9) P99.9(1099.9,2462.92) P100(1100,4500)
```

> First value represents the value of the histogram in that interval (from last time it collected, right now it is 1 min)

You mention a collection interval of 1 min, but when I immediately requested the stats after getting the above line I got more `nan`s.

```
cluster.weather-prod/weather/80/da39a3ee5e.upstream_rq_time: P0(nan,1) P25(nan,147.971) P50(nan,200.155) P75(nan,323.931) P90(nan,462.663) P95(nan,565.709) P99(nan,940.886) P99.9(nan,2462.91) P100(nan,4500)
```
Does fetching the stats via HTTP reset the interval?

**Comment by ramaraochavali** [comment]
Sorry. The default flush interval is 5 sec (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/bootstrap/v2/bootstrap.proto.html?highlight=stats%20flush) not 1 min (that is how we configured our Envoy :-)) as I mentioned earlier. You can change it so you get better histogram values as per your needs.

> Does fetching the stats via HTTP reset the interval?

No. It does not. It resets based on the above flush interval.

**Comment by yob** [comment]
> The default flush interval is 5 sec

ahhh. So, if I was to have no requests in a 5 second interval then I'd be getting a `nan` for the first value in each percentile?

... and if datadog was only fetching the stats every 20 seconds, I'd only be recording values for about 1/4 of the stats intervals?

**Comment by ramaraochavali** [comment]
> So, if I was to have no requests in a 5 second interval then I'd be getting a nan for the first value in each percentile?

Yes

>  if datadog was only fetching the stats every 20 seconds, I'd only be recording values for about 1/4 of the stats intervals?

Yes.
Ideally both should match IMO.

**Comment by ramaraochavali** [comment]
@mattklein123 I think this can be closed as it is working as designed and all questions have been answered.

**Comment by yob** [comment]
thanks for your help :heart:
