### ISSUE TITLE
how to  dynamicly config route to match the header of the request to select the instance

### ISSUE THREAD

**Issue by wansuiye** [envoyproxy/envoy#4961]
**Issue Template**
in multi-tenant scene, instances of a service may have different label, we could config roure configuration for every instance to match header, however the config is troublesome and we should update the config in its life-cycle. so if exist a way to config it easy?

*Title*: *One line description*

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by utkarsh-simha** [comment]
If I understand correctly, the requirement is to route to a specific instance of a service dynamically?

One solution, as you mentioned is to use `cluster_header: foo` to route dynamically based on the value of the given header `foo`. If the configuration needs to be updated, you can use a control plane to do so

The other solution is to use subset load balancing which allows you to build subsets based on key-value "tags". Each service instance can be tagged with a unique ID. You route your request to a cluster which defines your service where the service instances are endpoints. Now, you can choose a specific instance of a service by providing the value for the key using a header, and use the header-to-metadata filter to convert the header to the subset load balancer metadata.

**Comment by xiaoma2015** [comment]
> If I understand correctly, the requirement is to route to a specific instance of a service dynamically?
> 
> One solution, as you mentioned is to use `cluster_header: foo` to route dynamically based on the value of the given header `foo`. If the configuration needs to be updated, you can use a control plane to do so
> 
> The other solution is to use subset load balancing which allows you to build subsets based on key-value "tags". Each service instance can be tagged with a unique ID. You route your request to a cluster which defines your service where the service instances are endpoints. Now, you can choose a specific instance of a service by providing the value for the key using a header, and use the header-to-metadata filter to convert the header to the subset load balancer metadata.

@utkarsh-simha   I  understand  the dynamicly not just this mean. but we can  dynamicly route the request to the right instance  accordingly to its tags. for example:
