### ISSUE TITLE
How to build a dynamic_opentracing plugin for Envoy

### ISSUE THREAD

**Issue by Oberon00** [envoyproxy/envoy#4963]
*Description*:
In issue #4140 it is mentioned that a "A specific build process is required for the dynamic loading [of opentracing plugins] to work.". Is there any documentation of this build process? Are independent vendors even supposed to provide binary opentracing plugins for envoy? Background: I want to build such a plugin, and am thinking about what the best way to package or deploy it would be.

*Relevant Links*:
PR #2252
Issue #4140

**Comment by mattklein123** [comment]
@rnburn would be great to get some docs on this or if there are docs better links?

**Comment by rnburn** [comment]
Envoy statically links in the standard C++ library by default. The _specific build process_ is referring to the additional steps that need to be taken to work with a statically linked standard library. (See this [SO post](https://stackoverflow.com/questions/47841812/how-to-support-dynamic-plugins-when-statically-linking-in-standard-libraries/47926025#47926025) for background).

Basically what you need to do is to use a version script when linking to keep symbols from being exported. You can look at Jaeger's [build-plugin.sh](https://github.com/jaegertracing/jaeger-client-cpp/blob/master/scripts/build-plugin.sh) script to see an example of how to set it up.
