### ISSUE TITLE
Allow setting `retry_policy` at the VirtualHost level

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#4964]
Curretly, `retry_policy` can only be set at the `RouteAction` level:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L598

We've got a lot of routes and we need to set the same `retry_host_predicate`  for all of them. Does it sound reasonable to allow setting `retry_policy` at the `VirtualHost` level globally for all routes?

cc: @snowp

**Comment by rgs1** [comment]
@snowp @mattklein123 if it sounds reasonable, i'll send in a PR.

**Comment by mattklein123** [comment]
+1

**Comment by snowp** [comment]
Yeah, there's been talk about adding this earlier but nobody ever got around to it. Go for it.
