### ISSUE TITLE
Command Line Options in Admin Interface

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4994]
Is there a value in displaying command line options with which Envoy started in Admin interface? If yes, should it a new end point like `/options` or should it be part of `/server_info` ?

**Comment by mattklein123** [comment]
I could see this being potentially useful, though, to play devil's advocate the CLI options can also be seen by just looking at the process tree. If this would be used operationally I have no objection but I would prefer to otherwise not add something "nice to have."

**Comment by ramaraochavali** [comment]
Yes. The CLI options can be looked at process tree. It is little more cumbersome/additional steps if not impossible. The operational flow we typically follow in pre prod envs, when issue comes is, we go to admin and see stats and check other details. At this point if we want to know, what command line options it is running, it would be little easier to look at the admin endpoint. While this is not super critical but useful. I am definitely open to what others think and if it is maintenance overhead than the benefit it provides, I am OK to close this.

**Comment by moderation** [comment]
Where I ran into this was running Envoys as sidecars in Kubernetes. Our environment is very locked down. We can't exec into the containers. There is no access to the underlying OS. So there is no accessible way to peruse the process tree.

I understand this isn't the typical situation but it will become more common particularly in Enterprise environments. It is a pet peeve at the moment that almost every k8s related YAML, Helm chart assumes the developer is also the cluster admin and there is unfettered access to the internet.

**Comment by ramaraochavali** [comment]
If we decide to add it which one do you prefer? separate end point `/options` or part of `/server_info` ?

**Comment by mattklein123** [comment]
I don't have a strong opinion. @envoyproxy/maintainers?

**Comment by alyssawilk** [comment]
mild preference for separate end point but either is fine.

**Comment by htuch** [comment]
Since server_info is now proto, I think it's fine to add this there. If this was non-proto, I would be inclined the other way.

**Comment by ramaraochavali** [comment]
oh.. I did not know that I can use bot. Will do in future :-)
