### ISSUE TITLE
logger: consider using spdlog's async mode

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#4995]
*Description*:
>@gabime (author of spdlog) suggests in #4977  "consider using sodlog's async loggers. If used with single backing thread (the default), no locking is needed at all, and throughput would be stable even if some sink fails or delays (e.g. disk becomes slow). I think it might be important for a process like Envoy.
> If the log queue becomes full, It can configured to drop oldest messages or block (see the docs)

*Relevant Links*: https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging

**Comment by htuch** [comment]
I don't think we should use async logging. Here are the reasons:
1. These are debug logs; we want synchronous logging to match behavior with output.
2. These are debug logs; performance does not matter. In production, these are turned off, during debug performance is not an issue.

**Comment by mattklein123** [comment]
+1 to what @htuch said.

**Comment by gabime** [comment]
If logging is never used in production (I see many ```ENVOY_LOG(error/fatal/info,.. )``` in the codebase , are they all switched off in production?) then I agree, it might be an overkill.

**Comment by jmarantz** [comment]
@gabime default loglevel is 'info' and anything that is spewed with any frequency is below that severity.

The noise in the logs is pretty low.  Closing for now.
