### ISSUE TITLE
failing health checks when control plane disconnected

### ISSUE THREAD

**Issue by dfjones** [envoyproxy/envoy#5005]
In #4510 a metric was added to indicate whether Envoy is connected to the control plane. It would be great if there was a way to configure Envoy to fail its own health check when this metric indicates a disconnect.

We found ourselves writing something external to monitor this and call the healthcheck fail admin endpoint. If Envoy could do this internally that would be a bit simpler.

**Comment by itayd** [comment]
fix for ^ incoming. sorry for the noise.
