### ISSUE TITLE
b3 headers are duplicated

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5017]
After we upgraded to Envoy we are observing that all `x-b3-*` headers are duplicated and with different values. **It breaks our production**. 

Look like the commit  with this PR https://github.com/envoyproxy/envoy/pull/4712, is causing the issue. 

Any configuration change we need to make?

**Comment by ramaraochavali** [comment]
@zyfjeff Can you please take a look and help with it?

@rmichela can you please provide the sample headers we are seeing here?

**Comment by mattklein123** [comment]
cc @objectiser

**Comment by moderation** [comment]
I can confirm that I'm seeing the duplicate `x-b3-*` headers in my development environment. This is using a hello world Go app and sending traces to a Jaeger cluster.

**Comment by ramaraochavali** [comment]
@moderation Thanks for confirming. We see it with Zipkin cluster.

@mattklein123 what do you think about reverting this commit till the issue is fixed if it is going to take time?

**Comment by zyfjeff** [comment]
@ramaraochavali  @mattklein123 
I will fix this problem immediately.

**Comment by mattklein123** [comment]
Fixed.
