### ISSUE TITLE
TCP connection is closed when HTTP upstream returns a 503 & retries are enabled

### ISSUE THREAD

**Issue by julia-stripe** [envoyproxy/envoy#5023]
*Title*: TCP connection is closed when HTTP upstream returns a 503

*Description*:

When a HTTP upstream returns a 503 *and* retries are enabled, Envoy closes the TCP connection to the upstream (with a `FIN` packet). This is really confusing because it *doesn't* happen when retries are disabled, which makes me think that it may be a bug in Envoy.

This is similar to https://github.com/envoyproxy/envoy/issues/5022 but it's different enough (a `FIN`, not a `RST`, and the behavior depends on the HTTP headers sent) that I decided to open a separate issue.

*Repro steps*:

To start Envoy & the upstream server:

```
git clone https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d
cd 41fdc36f96b33c1e0e1708376fb7540d
ruby ./server.rb # start a server that always returns 503s
envoy -c ./envoy-config.yaml  --service-cluster test --service-node test
```

To cause the connection to be closed after each request:

```
curl localhost:8190 -i -H "x-envoy-retry-on: 5xx" -H "x-envoy-max-retries: 1"
```

To make a similar request that *doesn't result in the connection being closed:

```
curl localhost:8190 -i
```

*tcpdump*

* [tcpdump-503s.pcap](https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/tcpdump-503s.pcap). Note that every connection is closed almost immediately by Envoy after the response is received. 
* [tcpdump-503s-no-retry.pcap](https://gist.github.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/tcpdump-503s-no-retry.pcap). Note that in this packet capture almost all of the requests happen over the same TCP connection.

The only difference between these two packet captures is retry HTTP headers -- they're running with exactly the same Envoy configuration & server.

*Admin and Stats Output*:

In this gist:

https://gist.github.com/julia-stripe/ced04325aa7ce299a2304f7374b236c0

*Config*:

https://gist.githubusercontent.com/julia-stripe/41fdc36f96b33c1e0e1708376fb7540d/raw/5b574fe26d9f7cd29139f53bcdf711870c4af5e7/envoy-config.yaml

**Comment by mattklein123** [comment]
Yeah as described this is likely a bug. Will need some research so marking help wanted.

**Comment by julia-stripe** [comment]
My guess from looking through the code is that the connection is being reset here:

https://github.com/envoyproxy/envoy/blob/6b56612bb39d92451452d564efa797e45a6184bd/source/common/router/router.cc#L768-L770

I don't really understand what the `end_stream` boolean is supposed to signify there, but my best guess is that the intention of that code is to reset the HTTP/2 stream in the case of a retry (why?), and that in the HTTP/1 case this results in the TCP connection being closed.

**Comment by mattklein123** [comment]
`end_stream` indicates whether it is a header-only response or not. If `end_stream` is false, we must reset the upstream stream to indicate that we no longer care about potentially large amounts of body data.

What I suspect is happening here is that in some code paths, HTTP/1.1 responses are raised as headers with `end_stream` as false, followed by an empty body with `end_stream` as true. It might also be that your server is actually sending a body with the response. Do you know? Either way, we end up in a situation similar to the other ticket you opened. HTTP/2 solves this case also.

Now, if we are in a situation in which there is no HTTP/1.1 body (can you confirm) it's possible we can do a code change to make sure that response gets raised as end_stream = true and then we wouldn't reset/close the stream which for HTTP/1.1 results in connection close.

**Comment by julia-stripe** [comment]
Can confirm that:

1. The content length of the HTTP response from the upstream is 0 (the body is empty)
2. `end_stream` is being set to false
3. The line where `end_stream` is being set to `false` in this case is https://github.com/envoyproxy/envoy/blob/6b56612bb39d92451452d564efa797e45a6184bd/source/common/http/http1/codec_impl.cc#L718 

> we must reset the upstream stream to indicate that we no longer care about potentially large amounts of body data.

I'm confused about this -- why do we need to reset the upstream stream when the request is meant to be retried, but not if retries are turned off? It seems to me like Envoy should behave the same way  regardless of whether the request is retried.

I checked that https://github.com/envoyproxy/envoy/compare/master...julia-stripe:avoid-closing-503s?expand=1 partially fixes this issues (when retries are on & the content-length is 0, the connection is no longer closed), but the retries on / retries off behaviour still doesn't match when the body is nonempty.

**Comment by mattklein123** [comment]
> I'm confused about this -- why do we need to reset the upstream stream when the request is meant to be retried, but not if retries are turned off? It seems to me like Envoy should behave the same way regardless of whether the request is retried.

When retries are disabled, we proxy the 503, with body or not. Thus, nothing is reset. If we are retrying, we must cancel the upstream response so that we can start a new one. They are very different paths.

If there is no body, the appropriate fix here is not in the router, it would be in the HTTP/1.1 codec or the codec client (would need to be investigated) to make sure that the response is raised is a header only response with end_stream = true. If you look at the HTTP/1.1 codec there is already some logic there to deal with cases like this (I can't remember if on the request or response path or both).

**Comment by julia-stripe** [comment]
>  If we are retrying, we must cancel the upstream response so that we can start a new one. They are very different paths.

Why are the paths so different? I think there's some basic fact about Envoy's design I'm missing. Is there an invariant like "there can be only be one upstream request at a time per request that Envoy is handling"?

The patch I linked (https://github.com/envoyproxy/envoy/compare/master...julia-stripe:avoid-closing-503s?expand=1) is in the HTTP/1.1 codec -- does that look right to you?

**Comment by mattklein123** [comment]
> Why are the paths so different? I think there's some basic fact about Envoy's design I'm missing. Is there an invariant like "there can be only be one upstream request at a time per request that Envoy is handling"?

It's the same reason as why we close HTTP/1.1 connections that timeout. It's the simplest thing to do. If we don't reset the stream, what do we do with it? We need to back hole the data, have an extra timeout, etc. It's a lot of logic for no good reason.

> The patch I linked (https://github.com/envoyproxy/envoy/compare/master...julia-stripe:avoid-closing-503s?expand=1) is in the HTTP/1.1 codec -- does that look right to you?

Yes at quick glance that patch looks correct. I would work on some tests and then we can discuss further in code review. This is the only fix we can reasonably do here. For responses with body we will continue to reset the stream, and the best solution is to move to HTTP/2 if this type of performance is important to you.
