### ISSUE TITLE
Trailers can't be added in Lua filter if the upstream response did not have any trailers

### ISSUE THREAD

**Issue by bjaglin** [envoyproxy/envoy#5048]
As of Envoy 1.8.0, the `trailers()` function exposed in Lua returns `nil` (as [documented](https://github.com/envoyproxy/envoy/blob/8389aa27bed76aab26664a3b6ec9e6dc604829fa/source/extensions/filters/http/lua/lua_filter.h#L181)) if the original stream [did not contain any trailer](https://github.com/envoyproxy/envoy/blob/8389aa27bed76aab26664a3b6ec9e6dc604829fa/source/extensions/filters/http/lua/lua_filter.h#L181). This makes it impossible to add a trailer afterwards as the script can't get hold on a wrapper handle.

**Comment by bjaglin** [comment]
I am guessing that updating the API to return an empty header object in that case (instead of `nil`) is not an option as it will be a breaking change. The only backward-compatible thing I can think of would be to add some kind of `resetTrailers()` function that would:
- create a wrapper if there isn't already one
- remove all pairs in the existing wrapper otherwise

If anyone has a workaround that does not involve a custom Envoy build until we can agree on how implement this (like having another filter init a dummy trailer somehow), I am all ears!

**Comment by mattklein123** [comment]
Yeah I think the only way to do this is going to be able to do the equivalent of calling addDecoded/EncodedTrailers() in the C++ filter API (filter.h). This would need to be done in the context of headers if end_stream is true, or in the body if end_stream is true. I think it's doable, but this is going to require some thinking on the right API to expose to allow this to happen. 

@bjaglin there is no way to do this with Lua without code changes. This can be done using a C++ filter today without code changes to Envoy core.
