### ISSUE TITLE
Additional header modification options

### ISSUE THREAD

**Issue by taion809** [envoyproxy/envoy#5050]
*Title*: *Additional header modification options*

*Description*:
Today a we have the following header modification options:
  - request_headers_to_add
  - request_headers_to_remove
  - response_headers_to_add
  - response_headers_to_remove

I am proposing that another set of options be added
  - request_headers_to_set
  - response_headers_to_set

This new set of options would allow for deduplicating headers, the behavior today is that `request_headers_to_add` will append headers.  I have also tried combining `response_headers_to_add` and `response_headers_to_remove` to achieve the same behavior but the order in which these happen will remove the header instead of replacing.

**Comment by mattklein123** [comment]
>  I have also tried combining response_headers_to_add and response_headers_to_remove to achieve the same behavior but the order in which these happen will remove the header instead of replacing.

Although I don't have any objection to set options, should we just change the order to remove before add? It doesn't really make sense the other way around and I can't think of any reason not to swap it?

**Comment by taion809** [comment]
I think flipping the order of operations solves my immediate need :D

ref: #5052

**Comment by zuercher** [comment]
There's also an `append` flag in `core.HeaderValueOption` that helps with this, I think.

**Comment by taion809** [comment]
this was closed by #5050

thanks!
