### ISSUE TITLE
Access header values by name from header modification options

### ISSUE THREAD

**Issue by taion809** [envoyproxy/envoy#5051]
**Issue Template**

*Title*: *Access header values by name from header modification options*

*Description*:
Today it is not possible to rename or set a header value based on the value of an existing header.  I propose adding `%REQ("header_key")%` to the header parser.  This will allow us to automatically upgrade legacy headers in older applications.

https://github.com/envoyproxy/envoy/blob/818fc0cef0b00d0dfa849c721b49177f110fff1a/source/common/router/header_formatter.cc#L210

**Comment by mohammadMahdavi** [comment]
I also want to rename the existing heather. Is there any solution?
