### ISSUE TITLE
Stats inconsistency between membership_healthy and cluster health_flags

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#5056]
**Stats inconsistency between membership_healthy and cluster health_flags**

*Description*:
A change between bacaa4cdcbf94a8b110b783ae5e72cd2947a8432...5da782c8503aa2664ceac1995628d161bbaa6441 resulted in number of hosts at Lyft falsely reporting `membership_healthy` values as 0. We are running 5da782c8503aa2664ceac1995628d161bbaa6441.

When looking at the `health_flags` for a particular service we get:
```
tallen@jobschedulernormal-production-iad-0a352b11f4f80d603:~$ envoy-clusters | grep dborchestrator | grep health_flags
dborchestrator::10.0.42.21:9211::health_flags::healthy
```

However, at the same time we also see:
```
tallen@jobschedulernormal-production-iad-0a352b11f4f80d603:~$ envoy-stats | grep cluster.dborchestrator.membership_healthy
cluster.dborchestrator.membership_healthy: 0
```

This might have to do with https://github.com/envoyproxy/envoy/pull/5009, but we're not 100% sure at the moment. We're currently still investigating.

**Comment by mattklein123** [comment]
cc @rgs1

**Comment by rgs1** [comment]
@tonya11en does it eventually converge?

**Comment by rgs1** [comment]
@tonya11en quick way to test if it's #5009 would be by setting:

```
      common_lb_config:
        update_merge_window: 0s
```

**Comment by rgs1** [comment]
@tonya11en these stats might be helpful:

```
cluster_updated
cluster_updated_via_merge
update_merge_cancelled
update_out_of_merge_window
```

https://github.com/envoyproxy/envoy/blame/master/docs/root/configuration/cluster_manager/cluster_stats.rst#L22

**Comment by rgs1** [comment]
I am also wondering if the cluster is being frequently added/removed/added via CDS? Because if a cluster is removed, we cancel pending updates. If it's then immediately added again and its endpoints are populated from existing ones (because they haven't been drained yet), they could be stale...

**Comment by mattklein123** [comment]
FYI I looked at this a little bit and I'm doubtful update merging has anything to do with this, as update merging only prevents updates from going to the workers, it doesn't prevent updates on the main thread, which is where the stats are computed, AFAICT.

I do wonder if this is somehow due to hot restart and the old process writing 0 into the stat or something like that. I would try a fresh start also and see if it works then.

**Comment by danielhochman** [comment]
it correlated with the deploy of https://github.com/envoyproxy/envoy/compare/bacaa4cdcbf94a8b110b783ae5e72cd2947a8432...5da782c8503aa2664ceac1995628d161bbaa6441. though if it is a hot restart bug i guess it it could be due to the previous deploy's diff.

**Comment by mattklein123** [comment]
Yeah based on that diff, cluster merging does look very suspicious, though I don't see how it could cause the stat discrepancy. Admittedly, I did not look at the code for very long and maybe I am missing something. If we have a host that repros, can we check whether it happens every time? Does it happen without hot restart? Does turning off merging fix it?

**Comment by rgs1** [comment]
I can think of two ways for this bug to happen:

1) we are failing to fire the merged updates (we'd know if the above stats — `cluster_updated_via_merge`, etc — are not being incremented)
2) `addMemberUpdateCb` is called, but `prioritySet().hostSetsPerPriority()` is not up to date: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L536

**Comment by rgs1** [comment]
Also, we've only used merged updates with the subset LB, which will reconstruct the `hostSetsPerPriority` on every HC change:

https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/subset_lb.cc#L254

If other LBs rely on seeing _every_ HC change to keep `hostSetsPerPriority` up to date, things won't work...

**Comment by tonya11en** [comment]
I just checked back on that same box and the stats fixed themselves. Looking for another instance of this.

**Comment by mattklein123** [comment]
I'm going to go ahead and close this out. Please reopen if we think there is an issue here and we have some more info.
