### ISSUE TITLE
Add circuit breaker for max pending connections 

### ISSUE THREAD

**Issue by julia-stripe** [envoyproxy/envoy#5057]
*Title*: Add circuit breaker for max pending connections 

*Description*:

We've repeatedly seen an issue where Envoy will establish hundreds of connections all at once to an upstream. If those connections are TLS connections, this is extremely expensive and can overwhelm the upstream.

Right now there are [circuit breakers](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#cluster-circuitbreakers) for max pending requests and max connections, but it's easy to imagine a cluster which can easily support 1000 connections to it in a steady state but cannot easily handle 1000 new connections all at once, because establishing tls connections is much more expensive than maintaining them.

Do you all think it would make sense to add a `max_pending_connections` circuit breaker and default it to some lower value than `max_connections` by default? I'm not familiar with the circuit breaker code so I don't have a sense for how easy this would be to implement.

**Comment by mattklein123** [comment]
Yup this makes sense to me. I think it should be easy to add if you take a look at how the circuit breakers work in the connection pools. @snowp recent HTTP/2 connection pool refactor to make it work more similarly to HTTP/1 will also make this super easy.
