### ISSUE TITLE
Multiple Certificate Validation within a single Cluster

### ISSUE THREAD

**Issue by rayepudi** [envoyproxy/envoy#5067]
we're trying to connect to two different end points within a single cluster using load balancing for a fail over scenario. How can we configure multiple certificates within a single cluster for validation_context.

**Comment by PiotrSikora** [comment]
You can't. There was some talk about allowing more specific `CertificateValidationContext` inside `Endpoint` resource, but there is no code for it yet.

cc @lizan @JimmyCYJ @qiwzhang @htuch

**Comment by htuch** [comment]
Yeah, I think adding per-endpoint CVC makes sense here.
