### ISSUE TITLE
stats: names that require truncation cannot be looked up a second time.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5068]
*Description*:
> @junr03 reports that when a name gets truncated, a subsequent lookup fails, e.g. from https://github.com/envoyproxy/envoy/blob/cdd62383da5159261395f29ad17d06a6b8a1486e/source/extensions/filters/http/dynamo/dynamo_filter.cc#L226

**Comment by jmarantz** [comment]
This testcase added to thread_local_store_test.cc appears to repro:
```
class TruncatingAllocTest : public StatsThreadLocalStoreTest {
  class TruncatingHeapAlloc : public HeapStatDataAllocator {
   public:
    bool requiresBoundedStatNameSize() const override { return true; }
  };

 protected:
  void SetUp() override {
    store_ = std::make_unique<ThreadLocalStoreImpl>(options_, truncating_heap_alloc_);
    // Do not call superclass SetUp.
  }

  TruncatingHeapAlloc truncating_heap_alloc_;
};

TEST_F(TruncatingAllocTest, LookupTruncated) {
  const uint64_t max_name_length = options_.maxNameLength();
  const std::string name_1(max_name_length + 1, 'A');
  EXPECT_LOG_CONTAINS("warning", "is too long with", {
      Counter& counter = store_->counter(name_1);
      EXPECT_EQ(&counter, &store_->counter(name_1));
    });
}
```

**Comment by mattklein123** [comment]
For context for eveyone else , it's not the subsequent lookup. It's a race condition around the fact in the current code, we don't index on the truncated name, and end up creating the truncated stat in the central store every time. That means a user of the previous allocated stat will crash. Right @jmarantz?

**Comment by jmarantz** [comment]
probably; something is going wrong anyway, but @junr03 wrote to me via DM 
```
If the table name is super long and we truncated the name we end up trying to inc a null ptr
```
which is not exactly what I saw with this testcase. But whatever, if the testcase is accurate enough we'll just fix whatever's broken.

**Comment by mattklein123** [comment]
Yeah I'm pretty sure it's the race condition above. Anyway, let's try this out which I think will fix the issue.
