### ISSUE TITLE
Migrate header_formatter_test.cc to use Route prototype fields

### ISSUE THREAD

**Issue by taion809** [envoyproxy/envoy#5077]
*Title*: *Migrate header_formatter_test.cc to use Route prototype fields instead of RouteAction*

*Description*:
>This is a tech debt issue: `request_headers_to_add` and `response_headers_to_remove` are both deprecated fields in RouteAction, there are a number of tests still using this that need to be migrated to the appropriate Route prototype.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/master/test/common/router/header_formatter_test.cc

**Comment by zyfjeff** [comment]
If no one is doing it, I am happy to do it.
