### ISSUE TITLE
fuzzing support

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#508]
We should start adding fuzz testing (probably using llvm). Some thinking needs to be put into how to get the most value out of this. (Which granularity to fuzz, etc.). At minimum it would be nice to fuzz not only the HTTP codecs, but also all the way through the downstream HTTP connection manager processing. Doing this in a sane way which also yields good coverage is not going to be trivial. Also need to figure out how/when to run the tests.

@PiotrSikora would you like to own this? (At least in terms of getting some stuff started and then educating the rest of us on best practices so that we can all contribute).

**Comment by PiotrSikora** [comment]
Yes, please assign this to me.

**Comment by htuch** [comment]
@amb7 suggested we take a look at http://lcamtuf.coredump.cx/afl/.

**Comment by dnoe** [comment]
Would this be something that runs during CI or is it too heavyweight?

**Comment by htuch** [comment]
We could definitely do some light fuzzing in CI (time boxed fuzzing of X
mins), and then a heavier duty fuzz in nightly runs or elsewhere.

**Comment by mattklein123** [comment]
Assuming we get accepted to CNCF we will have have more resources to apply to CI for things like fuzzing/perf/etc. We should still plan for what we ultimately want to do though.

**Comment by htuch** [comment]
@PiotrSikora is this still on your radar, or should we tag "help wanted"?

**Comment by htuch** [comment]
I've started work on the new project setup for https://github.com/google/oss-fuzz. I'm working through a bunch of build issues, as we need to build Envoy in a Docker image with an oss-fuzz supplied compiler (looks to be clang-6.0) and its own set of CFLAGS/CXXFLAGS (including `-stdlib=libc++`). Will track progress here.

**Comment by htuch** [comment]
FTR the following pertinent restrictions exist in oss-fuzz today:
* Single process model (https://github.com/google/oss-fuzz/blob/master/docs/faq.md#can-i-launch-an-additional-process-eg-a-daemon-from-my-fuzz-target)
* We are restricted to `/tmp` for filesystem access (https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md#file-system)
* No network, including loopback (https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md#network-access)

This implies that we can't make use of any of our existing integration tests with a fuzz frontend, it probably makes sense to focus on some unit tests for inspiration as well as new fuzz areas.

I'm going to start with just a simple `Envoy::Base64` utility fuzzer to get the infrastructure in place (the encode/decode function are a direct match for the fuzz inputs https://llvm.org/docs/LibFuzzer.html#fuzz-target).

Following this, we can focus on configuration (protobuf) ingest and protocol handling on the data plane as the low hanging targets of interest. Any other suggestions welcome as well.

**Comment by mattklein123** [comment]
@htuch the no network restriction is pretty unfortunate. I wonder if we could somehow fuzz/inject a fake client directly into the normal Envoy process maybe via a custom transport socket implementation?

**Comment by htuch** [comment]
https://github.com/envoyproxy/envoy/pull/3493 just merged with the string lib fuzzing.

**Comment by mattklein123** [comment]
Calling this complete. We can open individual issues on fuzzing tasks.
