### ISSUE TITLE
Static build takes 479 MB

### ISSUE THREAD

**Issue by rvansa** [envoyproxy/envoy#5112]
**Issue Template**

*Title*: *Static build takes 479 MB*

*Description*:
Following https://github.com/envoyproxy/envoy/blob/master/bazel/README.md I've build the server from `master`, using optimized build - `bazel build //source/exe:envoy-static -c opt`. The resulting binary takes 479 MB - isn't this excessive for a lightweight proxy?

**Comment by mattklein123** [comment]
You will need to strip the symbols. See also: https://github.com/envoyproxy/envoy/issues/4695 if you would like to fix that issue with a PR.

**Comment by rvansa** [comment]
Thank you. Stripped variant (21 MB) seems reasonable.
