### ISSUE TITLE
Add access log response flag for downstream request cancel

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#5119]
*Title*: *Add access log response flag for downstream request cancel*

*Description*:
If a downstream client cancels an HTTP request (for instance if the per try timeout is hit), server-side access logs show a "0" response code and no health flags. Example:

```
[2018-11-26T03:17:43.818Z] "POST /foo HTTP/2" 0 - 32 0 450 <snip>
```

This is signifying that the request terminated before a response code was sent (because the client hung up), which seems like a nice case for a response flag.

**Comment by htuch** [comment]
@mpuncel seems reasonable, so you want to work on this?
