### ISSUE TITLE
Envoy specifying ciphers

### ISSUE THREAD

**Issue by jbrongtr** [envoyproxy/envoy#5121]
*Title*: Specifying Envoy ciphers

*Description*:
The issue that we are facing is figuring out how to only allow certain cipher suites to be used with envoy. Is there someway to pass this information in when deploying or will we need to "build" envoy with the specified suites?

[This](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/ssl.html?highlight=ciphers) link to the doc's mention that its possible,  but its a little vague on how to do so. Im hoping to use this specification with istio.

**Comment by moderation** [comment]
@jbrongtr There is some additional documentation at https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html?highlight=cipher that might help.

**Comment by htuch** [comment]
+1 to what @moderation writes, this is the right way to do it for Envoy. If this answers your question, LMK and we can close this out.

**Comment by jbrongtr** [comment]
Hey htuch,

I saw that documentation too. To me that looks like code that you would put into the build of envoy; would that assumption be correct? When you click on [auth.TlsParameters](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/auth/cert.proto#L17), at the top of that page, it even brings you to the section of api code.

Im unsure of how to let the envoy proxies know, that i only want them to use a few specific ciphers suites. Using envoy in a kube cluster, it would be awesome if i could pass it a values.yaml file or something similar to let it know what i want.

Thank you for the quick response too!

**Comment by htuch** [comment]
These can be configured for listeners and clusters in Envoy's bootstrap or xDS APIs, see https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview. There should be no need to rebuild.

**Comment by moderation** [comment]
As @htuch points out the documentation refer to the configuration. No rebuild is necessary. Here is a snippet of sample config for a cluster.
``` YAML
  clusters:
  - connect_timeout: 1s
    hosts:
    - socket_address:
        address: abs.twimg.com
        port_value: 443
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    name: twimg_abs
    tls_context:
      common_tls_context:
        alpn_protocols: h2
        tls_params:
          tls_maximum_protocol_version: TLSv1_3
          tls_minimum_protocol_version: TLSv1_2
          cipher_suites: "[ECDHE-RSA-AES256-GCM-SHA384|ECDHE-RSA-AES128-GCM-SHA256]"
      sni: abs.twimg.com
    type: LOGICAL_DNS
``

**Comment by jbrongtr** [comment]
Excellent! Thank you both for the help and the snippit. Could you provide an example of cipher suites in the listener portion of the config?

**Comment by hnasr** [comment]
This is the only location on the whole wide web Internet where I found a sample YAML envoy config showcasing TLS  parameters. Thank you!

What I was searching for is this parent key which is not mentioned anywhere in the doc unfortunately, which turns out to be `tls_params` 

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html
