### ISSUE TITLE
subset load balancer optimize

### ISSUE THREAD

**Issue by andyyin** [envoyproxy/envoy#5130]
Description:

The envoy subset does not satisfy all scenarios. Not all subset keys require fallback to DEFAULT_SUBSET. Can it be optimized to configure fallback_policy for subset keys separately?

E.g
{ "subset_selectors": [
     { "keys": [ "version" ] },
     { "keys": [ "stage", "hardware_type" ] }
]}

Optimized
{ "subset_selectors": [
     { "keys": [ "version" ] , "fallback_policy": NO_FALLBACK},
     { "keys": [ "stage", "hardware_type" ] , "fallback_policy": DEFAULT_SUBSET}
]}

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#envoy-api-msg-cluster-lbsubsetconfig

**Comment by zuercher** [comment]
I think it's a feasible change. Probably the `SubsetLoadBalancer::ValueSubsetMap` would need to become a struct to encapsulate the `map<HashedValue, LbSubsetEntryPtr>` and an optional fallback policy specific to the subset.

**Comment by nezdolik** [comment]
Want to give it a try

**Comment by nezdolik** [comment]
@zuercher please correct me if am wrong, to my understanding extending `SubsetLoadBalancer::ValueSubsetMap` will not work.
In `SubsetLoadBalancer::ValueSubsetMap` matching is performed on key-value pairs from route metadata. 
So if route metadata has values for keys that are not present in `SubsetLoadBalancer::ValueSubsetMap`, we will not be able to lookup corresponding fallback policy.
If instead we use trie-like structure (for optimal lookups, similar to `SubsetLoadBalancer::ValueSubsetMap`) that does matching only based on selector keys?
One more challenge for introducing fallback policy per selector is that we will need to keep track of multiple "default subsets". 
For example if on top level config we have fallback policy` "ANY"` and for some selector we have fallback policy `"DEFAULT_SUBSET"`.
What do you think of suggested approach? Started wip pr for the change: https://github.com/envoyproxy/envoy/pull/6124
