### ISSUE TITLE
consider using libdeflate instead of libzlib

### ISSUE THREAD

**Issue by mvrhov** [envoyproxy/envoy#5131]
**Issue Template**

*Title*: libdeflate, faster zlib replacement

*Description*:
libdeflate is supposed to be a faster & offer better compression at the same level alternative to zlib, it also offers more compression levels, which is not necessary here, while retaining the decompression compatibility.
Unfortunately it's api is not compatible with the one from zlib

[optional *Relevant Links*:]
https://github.com/ebiggers/libdeflate

**Comment by htuch** [comment]
@gsagula WDYT?

**Comment by gsagula** [comment]
I don't know much about `libdeflate`, but considering that `zlib` project has not been very active lately and IIRC it still has an open issue with the size of sliding window, I would look into alternatives.
I'm working on https://github.com/envoyproxy/envoy/issues/4445, a generic compression filter that will make it easier to plug other compression libraries. We could try it out when I finish it.

@mvrhov Did you benchmark it yourself? I couldn't find a comparison in there project, other than statements saying that it is faster.

**Comment by mvrhov** [comment]
We haven't had time to test it yet. However for as is it more important in having smaller file size because we store a lot of xml and json data gzipped, that the browsers can still decompress than the speed.

**Comment by gsagula** [comment]
IMO, If performance is the reason for changing this library, we need to make sure that the replacement will produce better results before doing any work. WDYT? Another thing that we need to consider here is that Envoy, in order to reduce latency, it flushes on every data frame which sacrifices the compression a bit. It seems that for your case, the compression engine should be doing the opposite.

**Comment by mvrhov** [comment]
I agree with what have you written. My answer might not have been clear enough. We store the gzipped files on disk and then ATM we configure the nginx to serve them as is.
As we are in a process of redesigning some of the infrastructure I've discovered the above mentioned libdeflate and also the envoy

**Comment by gsagula** [comment]
Thanks for elaborating it. I'm not sure that Envoy can serve static files yet. There is an open issue for that https://github.com/envoyproxy/envoy/issues/378.
