### ISSUE TITLE
Migrate ext_auth away from alpha config

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#5138]
We need to lock the config as people are starting to use this filter in production.

**Comment by gsagula** [comment]
I will work on this one as soon as https://github.com/envoyproxy/envoy/pull/4947 gets merged. Thanks!

**Comment by mattklein123** [comment]
@gsagula is still planning on doing this soon I think.

**Comment by gsagula** [comment]
@mattklein123 Yes, it's done. I changed the documentation. I think it's more clear, but I'm sure that grammar still needs some work. Let me send the PR.
