### ISSUE TITLE
runtime: add admin endpoint to view/modify loaded values

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#514]
Will be generally useful to have admin endpoint to:

- list/view loaded values
- modify/add values (this will need to trigger a reload just like inotify, and can probably be implemented as an additional override layer).

**Comment by mattklein123** [comment]
@rodaine this is a good ramp up issue for you. Let's chat offline.

**Comment by jsedgwick** [comment]
@mattklein123 do we still want to do the write side of this now in light of #2763?

**Comment by mattklein123** [comment]
@jsedgwick yes we should still do this. Security is orthogonal.

**Comment by mattklein123** [comment]
(Though the modification endpoint should be a POST)

**Comment by jsedgwick** [comment]
@mattklein123 should you be able to add/modify runtime values if there is no backing on-disk runtime set up (and therefore the default runtime is empty)? I don't know enough about how this feature is used to determine whether that would be a useful capability or not.

**Comment by mattklein123** [comment]
Optimally, having this available also for the "null" runtime impl would be nice, as people could override settings for testing even without using the full disk version.

**Comment by jsedgwick** [comment]
Yeah, sounds right. Will do.
