### ISSUE TITLE
docs: FAQ/doc on Resiliency features

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5143]
On the similar lines of the LB overview documentation issue #5081, I think the we need a basic overview of resiliency features Envoys supports with links to the detailed explanation of each of those features.
This should probably include
- Retries (With a high level overview of how http and gRPC status codes are treated and how they are mapped etc)
- Circuit Breaking
- Outlier Detection
- Global Rate limiting

**Comment by ramaraochavali** [comment]
@mattklein123  What do you think about this?

**Comment by mattklein123** [comment]
i think this sounds awesome! :)

**Comment by ramaraochavali** [comment]
Assign this to me. I will write first draft but probably need your help

**Comment by mattklein123** [comment]
I think this is done. Thanks!
