### ISSUE TITLE
tools: clang-tidy times out in CI

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5144]
*Description*:
>In my experience, clang-tidy often fails with a message like:
```
1725398 warnings generated.
1751654 warnings generated.
disk space at end of build:
Filesystem      Size  Used Avail Use% Mounted on
none            826G  458G  368G  56% /
tmpfs            35G     0   35G   0% /dev
tmpfs            35G     0   35G   0% /sys/fs/cgroup
/dev/nvme1n1    826G  458G  368G  56% /etc/hosts
shm              30G     0   30G   0% /dev/shm
udev             35G   12K   35G   1% /dev/tty
tmpfs            35G     0   35G   0% /sys/firmware
ci/build_setup.sh: line 111:   196 Hangup                  ./run_clang_tidy.sh
Too long with no output (exceeded 10m0s)
```
Do we need to extend the timeout for this phase, or shard the clang-tidy phase?

*Relevant Links*: https://circleci.com/gh/envoyproxy/envoy/128331?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by htuch** [comment]
I think we maybe can just get clang-tidy to be more verbose? This seems to be an idle timeout rather than a hard timeout.

**Comment by jmarantz** [comment]
It would be great if we could scrape that log too for actionable issues (e.g. new errors). I have to scour it manually.

**Comment by lizan** [comment]
This is one of mystery in CircleCI for me, I have been debugging this with @auni53 before and couldn't figure out. It doesn't reproduce whenever I tried SSH with clang-tidy run.

The error log says it hangs at:
https://github.com/envoyproxy/envoy/blob/6c2c7b5ca026dfd77e70826b1474feaaabaf8ec1/ci/build_setup.sh#L111 which is the `cleanup` method but not clang-tidy itself.

**Comment by lizan** [comment]
OK I figured out why it happens, due to the inefficient way that clang-tidy-diff runs clang-tidy. With large diff involved this happens easily. Will work on a fix shortly.
