### ISSUE TITLE
No traces on Jaeger UI  in envoy-jaeger examples

### ISSUE THREAD

**Issue by pltanhthu** [envoyproxy/envoy#5163]
**No traces on Jaeger UI  in envoy-jaeger examples**

*Description*:
 I run the sandbox envoy-jaeger example and the envoy works fine when receiving requests but there is no trace shown in Jaeger UI. Only services' name is shown in UI, but nothing for dependencies or traces. Could you please point me if I missing something? Below is the docker logs for jaeger. Thanks. 

*Logs*:
jaeger_1       | {"level":"info","ts":1543511060.305409,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
jaeger_1       | {"level":"info","ts":1543511060.3056395,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":0}}
jaeger_1       | {"level":"info","ts":1543511060.3088524,"caller":"tchannel/builder.go:97","msg":"Enabling service discovery","service":"jaeger-collector"}
jaeger_1       | {"level":"info","ts":1543511060.3089623,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"127.0.0.1:14267"}
jaeger_1       | {"level":"info","ts":1543511060.3100307,"caller":"all-in-one/main.go:208","msg":"Starting agent"}
jaeger_1       | {"level":"info","ts":1543511060.3102233,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
jaeger_1       | {"level":"info","ts":1543511060.3115144,"caller":"all-in-one/main.go:270","msg":"Starting jaeger-collector TChannel server","port":14267}
jaeger_1       | {"level":"info","ts":1543511060.311629,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
jaeger_1       | {"level":"info","ts":1543511060.3117423,"caller":"all-in-one/main.go:288","msg":"Starting jaeger-collector HTTP server","http-port":14268}
jaeger_1       | {"level":"info","ts":1543511060.3119621,"caller":"all-in-one/main.go:415","msg":"Archive storage not created","reason":"Archive storage not supported"}
jaeger_1       | {"level":"info","ts":1543511060.3431392,"caller":"all-in-one/main.go:326","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
jaeger_1       | {"level":"info","ts":1543511060.7319453,"caller":"all-in-one/main.go:376","msg":"Registering metrics handler with jaeger-query HTTP server","route":"/metrics"}
jaeger_1       | {"level":"info","ts":1543511060.731998,"caller":"all-in-one/main.go:382","msg":"Starting jaeger-query HTTP server","port":16686}
jaeger_1       | {"level":"info","ts":1543511060.7320323,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
jaeger_1       | {"level":"info","ts":1543511061.309149,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
jaeger_1       | {"level":"info","ts":1543511061.309212,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"127.0.0.1:14267"}
jaeger_1       | {"level":"info","ts":1543511061.3099022,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"}

**Comment by htuch** [comment]
@rnburn any thoughts here?

**Comment by rnburn** [comment]
Not sure. Maybe @isaachier can help or try asking on https://gitter.im/jaegertracing/Lobby

**Comment by objectiser** [comment]
@pltanhthu Can you confirm you ran the example using the instructions [here](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_tracing#running-the-sandbox)?

Once you have performed one or more requests, when you open the Jaeger UI, on the search page - what are the list of services in the `Service` dropdown? If the UI is already started before performing the requests, then just refresh the search page to get an uptodate list of services.

Without changing any other default values, if you select `front-proxy` from the service dropdown, then you press `Find Traces` you are not seeing any trace instances?

**Comment by pltanhthu** [comment]
Hi @objectiser , I ran the jaeger-tracing example with a small change in port (from "8000:80" to "8005:80") in front-proxy in docker-compose.yaml. Hope that it is not reason for the issue. And after i sent a request "curl localhost:8005/trace/1", I got the hello message. I refreshed Jaeger UI and I just got the list of services, but I didnt see neither traces nor dependencies. Below is the Jaeger UI I got. 

![image](https://user-images.githubusercontent.com/11585812/49284583-e470da00-f48c-11e8-8e7d-274d11379ee2.png)

![image](https://user-images.githubusercontent.com/11585812/49284496-b2f80e80-f48c-11e8-8b8b-d4595b59b0c7.png)

**Comment by objectiser** [comment]
@pltanhthu Ok thanks -after starting a fresh environment, could you run a single request and then run the following command:
```
curl localhost:16686/api/traces?service=front-proxy
```
and attach the output to this issue.

**Comment by pltanhthu** [comment]
hi @objectiser, here is the output: 

 {"data":[{"traceID":"14c7cc4ee267dd26","spans":[{"traceID":"14c7cc4ee267dd26","spanID":"669203e8ab34d70d","operationName":"checkStock","references":[{"refType":"CHILD_OF","traceID":"14c7cc4ee267dd26","spanID":"7ea61c3b0643b829"}],"startTime":1543592993641276,"duration":2121,"tags":[{"key":"component","type":"string","value":"proxy"},{"key":"guid:x-request-id","type":"string","value":"c3464f4b-5e0f-9b17-a305-498c90b35511"},{"key":"http.url","type":"string","value":"http://localhost:9000/trace/2"},{"key":"http.method","type":"string","value":"GET"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"user_agent","type":"string","value":"python-requests/2.18.4"},{"key":"http.protocol","type":"string","value":"HTTP/2"},{"key":"request_size","type":"string","value":"0"},{"key":"upstream_cluster","type":"string","value":"local_service"},{"key":"http.status_code","type":"string","value":"200"},{"key":"response_size","type":"string","value":"89"},{"key":"response_flags","type":"string","value":"-"},{"key":"span.kind","type":"string","value":"client"}],"logs":[],"processID":"p1","warnings":null},{"traceID":"14c7cc4ee267dd26","spanID":"14c7cc4ee267dd26","operationName":"checkAvailability","references":[],"startTime":1543592993633971,"duration":11619,"tags":[{"key":"component","type":"string","value":"proxy"},{"key":"guid:x-request-id","type":"string","value":"c3464f4b-5e0f-9b17-a305-498c90b35511"},{"key":"http.url","type":"string","value":"http://localhost:8005/trace/1"},{"key":"http.method","type":"string","value":"GET"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"request_size","type":"string","value":"0"},{"key":"upstream_cluster","type":"string","value":"service1"},{"key":"http.status_code","type":"string","value":"200"},{"key":"response_size","type":"string","value":"89"},{"key":"response_flags","type":"string","value":"-"},{"key":"span.kind","type":"string","value":"client"}],"logs":[],"processID":"p2","warnings":null},{"traceID":"14c7cc4ee267dd26","spanID":"7ea61c3b0643b829","operationName":"checkStock","references":[{"refType":"CHILD_OF","traceID":"14c7cc4ee267dd26","spanID":"8a06d5d76dd1e895"}],"startTime":1543592993640770,"duration":3465,"tags":[{"key":"component","type":"string","value":"proxy"},{"key":"guid:x-request-id","type":"string","value":"c3464f4b-5e0f-9b17-a305-498c90b35511"},{"key":"http.url","type":"string","value":"http://localhost:9000/trace/2"},{"key":"http.method","type":"string","value":"GET"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"user_agent","type":"string","value":"python-requests/2.18.4"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"request_size","type":"string","value":"0"},{"key":"upstream_cluster","type":"string","value":"service2"},{"key":"http.status_code","type":"string","value":"200"},{"key":"response_size","type":"string","value":"89"},{"key":"response_flags","type":"string","value":"-"},{"key":"span.kind","type":"string","value":"client"}],"logs":[],"processID":"p3","warnings":null},{"traceID":"14c7cc4ee267dd26","spanID":"8a06d5d76dd1e895","operationName":"checkAvailability","references":[{"refType":"CHILD_OF","traceID":"14c7cc4ee267dd26","spanID":"14c7cc4ee267dd26"}],"startTime":1543592993635444,"duration":9998,"tags":[{"key":"component","type":"string","value":"proxy"},{"key":"guid:x-request-id","type":"string","value":"c3464f4b-5e0f-9b17-a305-498c90b35511"},{"key":"http.url","type":"string","value":"http://localhost:8005/trace/1"},{"key":"http.method","type":"string","value":"GET"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"http.protocol","type":"string","value":"HTTP/2"},{"key":"request_size","type":"string","value":"0"},{"key":"upstream_cluster","type":"string","value":"local_service"},{"key":"http.status_code","type":"string","value":"200"},{"key":"response_size","type":"string","value":"89"},{"key":"response_flags","type":"string","value":"-"},{"key":"span.kind","type":"string","value":"client"}],"logs":[],"processID":"p3","warnings":null}],"processes":{"p1":{"serviceName":"service2","tags":[{"key":"ip","type":"string","value":"172.27.0.4"}]},"p2":{"serviceName":"front-proxy","tags":[{"key":"ip","type":"string","value":"172.27.0.2"}]},"p3":{"serviceName":"service1","tags":[{"key":"ip","type":"string","value":"172.27.0.3"}]}},"warnings":null}],"total":0,"limit":0,"offset":0,"errors":null}

**Comment by objectiser** [comment]
@pltanhthu This is strange - so the data looks like it is being collected by the backend. Can you do the same steps, but this time use the following URL in the browser: `http://localhost:16686/search?service=front-proxy`

Let me know if you now see the trace instances.

**Comment by objectiser** [comment]
@pltanhthu Looks like it is some form of UI bug - could you raise an issue in https://github.com/jaegertracing/jaeger-ui listing details of your environment (especially browser) and the details you just mentioned.

If you have time, it might be worth experimenting with trying to isolate the query parameter(s) in the URL that is causing the problem, and add any findings to the jaeger-ui issue. Also if there is any errors showing up in your browser web console.

**Comment by isaachier** [comment]
I doubt it is a UI bug. It might make sense to investigate further using logging, but the plugin has no way to configure log level at this time (defaults to null logger). Either way, please submit an issue to https://github.com/jaegertracing/jaeger and provide details so we can investigate it.

**Comment by moderation** [comment]
I believe this issue was fixed by https://github.com/envoyproxy/envoy/pull/5249
