### ISSUE TITLE
question: debugging access log format problems

### ISSUE THREAD

**Issue by cmluciano** [envoyproxy/envoy#5193]
*Title*: question: debugging access log format problems

*Description*:
The access log formatter does not appear to work without a null terminator \n . #87 was closed with an [update to the docs](https://github.com/envoyproxy/envoy/pull/93/files) noting the need for a newline separator. It makes sense to not enforce the newline when inserting a custom format, but a colleague and I found it difficult to determine that this may have been the problem since no leveled logging printed that there may be a problem. 

I also tried validating with the [config-checker tool](https://github.com/envoyproxy/envoy/blob/master/test/tools/config_load_check/config_load_check.cc) , but it did not complain about the missing \n. 

The JSON logger now automatically adds newlines with #5024 but the regular logger still can fail silently due to a bad format. Are there any potential logs or warnings that should catch these types of format problems, and if not would a PR to add some trace logs around this validation be accepted?

*Repro steps*:
1. Use curl get against an Envoy proxied web address with the custom access logger listed below and log-level set to trace.
2. Note that even with trace logging enabled, no warnings are printed and the access log is not displayed at all.

*Config*:

```yaml
format: "[%START_TIME%] %PROTOCOL% %BYTES_RECEIVED% %BYTES_SENT% %RESPONSE_FLAGS% %UPSTREAM_HOST% %UPSTREAM_CLUSTER% %REQUESTED_SERVER_NAME%"
```

**Comment by cmluciano** [comment]
@htuch @ggreenway looks like you both have merged things recently into the access log code. 

Do either of you have any opinions on this?

**Comment by mattklein123** [comment]
@cmluciano can you propose a potential change here? From a quick read I'm not sure I fully grok the issue.

**Comment by ggreenway** [comment]
Is there any reasonable use-case for not having a newline in the format? I'd be fine with automatically adding a newline at the end if one isn't present.

**Comment by cmluciano** [comment]
@mattklein123 @ggreenway  Yes the change I had in mind was validation that a newline is present and either logging or automatically adding one. Without the newline we don't see any error messages and access logging is non functional. 

The change would be similar to #5024

**Comment by ggreenway** [comment]
That seems fine to me. If anyone comes up with a valid use-case for no-newline, you can put it behind a new config bit.

**Comment by htuch** [comment]
Automatically adding a new line if not present seems fine to me as well.
