### ISSUE TITLE
provide ppc64le release binaries

### ISSUE THREAD

**Issue by clnperez** [envoyproxy/envoy#5196]
**Title: provide ppc64le release binaries**

*Description*:
I'm hoping to figure out a way we can get binaries for ppc64le built and hosted by the envoy community. I've been building binaries myself for the past year or so, to be consumed by Power users of istio. Now that it seems that all the bazel + luajit issue are ironed out, it would be great if we could agree on a way to have this be automated.

We could provide the community with a public VM via either OSU or Unicamp (in Brazil). If someone is familiar with using Circle with an outside system (and if one could be another architecture), this could also be hooked into your build process.

I'm also open to other ideas.

**Comment by mattklein123** [comment]
@clnperez we would be happy to post GitHub events to an external build hook if you want to run builds on master pushes.

**Comment by cmluciano** [comment]
I'm helping @clnperez with getting this up and running. Can we reopen this?

**Comment by cmluciano** [comment]
Not stale, we just gained access to the test VM for this issue today so we should be able to fulfill this issue soon.

So far we have tests and builds passing on 18.04 with clang/gcc. The only remaining issue is getting a working bazel-0.22.0 binary.

**Comment by cmluciano** [comment]
We have had successful builds in our internal system since March 13th. Now we just need to determine how to get remote builds working for Circle on the external build machine we have setup.

**Comment by cmluciano** [comment]
Good news, i just received access to the [Oregon State Power9 Jenkins service](https://powerci.osuosl.org/). This IBM partner provides a similar service for Tensorflow & Docker. 

I'm tweaking the job now and will let it run for a few days before requesting the build hook integration.

**Comment by cmluciano** [comment]
Ok I have master building successfully on ppc64le machines with Ubuntu 16.04. I still have to test with newer versions of gcc/clang but so far so good. I'm also working with the OSU lab to integrate the [docker custom build environment](https://plugins.jenkins.io/docker-custom-build-environment) plugin. This should replicate the custom build container with all deps preinstalled process that we use with CircleCI.

You can view the pipeline [here](https://powerci.osuosl.org/job/pipeline-build-envoy-master/).
