### ISSUE TITLE
Allow optionally forwarding the client cert if one is provided

### ISSUE THREAD

**Issue by predmore** [envoyproxy/envoy#5212]
Allow a client cert to be optionally provided and its details forwarded to the cluster.

*Description*:
Right now Envoy only forwards client cert information (through `forward_client_cert_details`) if a validation context is provided. We would like to allow clients to optionally validate through client certs by having the details forwarded to the backing service that, itself, does the validation. This is not currently possible because the client cert details are only forwarded if a client cert is required.

This change would allow client cert details to be forwarded if the property is set to `SANATIZE_SET` regardless of whether the client cert is required.

**Comment by mattklein123** [comment]
This makes sense to me. @PiotrSikora @lizan any concerns here?

**Comment by PiotrSikora** [comment]
Sounds fine to me.

**Comment by lizan** [comment]
SGTM

**Comment by predmore** [comment]
Thanks, what’s the process to help get this prioritized or implemented?

**Comment by mattklein123** [comment]
Do a PR!

**Comment by PiotrSikora** [comment]
Note: this is effectively a subset of #5501, i.e. `validate_client_certificate: false`.

**Comment by predmore** [comment]
Yeah, it looks like #5501 would solve this problem.
