### ISSUE TITLE
0.0.0.0:0 Cluster Endpoints with Logical_DNS

### ISSUE THREAD

**Issue by codyja** [envoyproxy/envoy#5225]
*Title*: *0.0.0.0:0 Cluster Endpoints with Logical_DNS*

*Description*:
When using LOGICAL_DNS in CDS, would it be possible to output the IPs of all the discovered endpoints when hitting /clusters? Currently it appears to only show 0.0.0.0:0. I just need a way to show an accurate list of all the endpoints behind a LOGICAL_DNS cluster. If I switch to static_dns, I do see all the hosts behind that DNS record, but can't really use static_dns because it's a big pool of endpoints behind the DNS record, but only returns 10 entries each query. I found this note here about why it's currently all zeros too.

test-cluster::default_priority::max_connections::1024
test-cluster::default_priority::max_pending_requests::1024
test-cluster::default_priority::max_requests::1024
test-cluster::default_priority::max_retries::3
test-cluster::high_priority::max_connections::1024
test-cluster::high_priority::max_pending_requests::1024
test-cluster::high_priority::max_requests::1024
test-cluster::high_priority::max_retries::3
test-cluster::added_via_api::false
test-cluster::0.0.0.0:0::cx_active::1
test-cluster::0.0.0.0:0::cx_connect_fail::15
test-cluster::0.0.0.0:0::cx_total::25
test-cluster::0.0.0.0:0::rq_active::4
test-cluster::0.0.0.0:0::rq_error::27
test-cluster::0.0.0.0:0::rq_success::0
test-cluster::0.0.0.0:0::rq_timeout::0
test-cluster::0.0.0.0:0::rq_total::16
test-cluster::0.0.0.0:0::health_flags::healthy
test-cluster::0.0.0.0:0::weight::1
test-cluster::0.0.0.0:0::region::
test-cluster::0.0.0.0:0::zone::
test-cluster::0.0.0.0:0::sub_zone::
test-cluster::0.0.0.0:0::canary::false
test-cluster::0.0.0.0:0::success_rate::-1

Here's the note in the code.
https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/logical_dns_cluster.cc#L98-L101
`if (!logical_host_) {
            // TODO(mattklein123): The logical host is only used in /clusters admin output. We used
            // to show the friendly DNS name in that output, but currently there is no way to
            // express a DNS name inside of an Address::Instance. For now this is OK but we might
            // want to do better again later.`

Thank you for looking and consideration!

**Comment by mattklein123** [comment]
Yeah would be nice to make this better. Marking help wanted. I can try to take a look at this when I tackle https://github.com/envoyproxy/envoy/issues/1606 since it's tangentially related.

**Comment by mattklein123** [comment]
I just looked at this in the context of https://github.com/envoyproxy/envoy/issues/1606 and found my old comment as it is indeed relevant. I will fix this, it's not hard.
