### ISSUE TITLE
Allow reading filter config from disk

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5237]
Tracks adding support for specifying a `DataSource` as filter config, allowing Envoy to read the filter config from disk instead of requiring it to be fully specified in the listener config.

**Comment by junr03** [comment]
@snowp just to clarify, are you suggesting elevating filter chains to their own FDS (filter discovery service) API?

**Comment by snowp** [comment]
That's one of the options (@bplotnick suggested something like this). The other suggestion by @htuch  was to just let us set a DataSource as the config and have Envoy load that:

```
htuch [3:21 PM]
hmm

we could do something like this pretty transparently I think
whether a `Struct` or `Any`
we would take the object and first see if it's a `DataSource`
if so, we add an indirection, where we then go and fetch the underlying object and interpret that as the filter config
totally doable without breaking backwards compat or adding any new interface
```

(from #envoy-dev)

**Comment by htuch** [comment]
@snowp did you want his one to age out or do you have concrete plans to work on it? Should we tag help wanted? It seems totally reasonable to me.

**Comment by snowp** [comment]
I don't have concrete plans to work on it, mostly because my attention is spent elsewhere. I think marking this as help wanted makes sense

**Comment by mattklein123** [comment]
This will be fixed by FCDS implicitly so closing as a dup: https://github.com/envoyproxy/envoy/issues/7867
