### ISSUE TITLE
Use simTime for HTTP integration tests

### ISSUE THREAD

**Issue by venilnoronha** [envoyproxy/envoy#5240]
*Title*: Use `simTime` for HTTP integration tests

*Description*:
Currently, the [HttpProtocolIntegrationTest](test/integration/http_protocol_integration.h) heirarchy runs tests using the `realTime` system. This can possibly cause flakes on slower machines, so, it'd be good to switch over to `simTime`.

*Relevant Links*:
See #5223 and [this comment](https://github.com/envoyproxy/envoy/pull/5223#issuecomment-445034362).

/cc @jmarantz

**Comment by jmarantz** [comment]
Not just slower machines; also machines that are busy doing multiple tasks as well; a thread you expect to wake up and do something within a bounded time may not get a chance depending on the OS and the other scheduled tasks.
