### ISSUE TITLE
exporting traces is broken with latest docker release

### ISSUE THREAD

**Issue by dmichel1** [envoyproxy/envoy#5241]
*Description*:
When running through the examples provided at
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/zipkin_tracing.html no traces show up in the zipkin UI.

When I change the docker version tag from `latest` to `v1.8.0` in the below files traces start to show up. I don't see any errors when running on `latest` that would explain no traces to be sent. 

`front-proxy/Dockerfile-service`
`front-proxy/Dockerfile-frontenvoy`

**Comment by mattklein123** [comment]
cc @objectiser

**Comment by objectiser** [comment]
This issue is also affecting the jaeger-tracing example.

Looks like it was caused by https://github.com/envoyproxy/envoy/commit/43fc77901ee8a1608239daaa51b531f922628083.

cc @jmarantz

**Comment by jmarantz** [comment]
I can take a look; is there an easy way to express this as a unit test?

**Comment by objectiser** [comment]
Not sure - there are unit tests at the various levels (conn_manager_impl, http_tracer_impl, zipkin_tracer) - but looks like there must be some gap in testing. Don't think there are any e2e tests, which might be needed.

**Comment by jmarantz** [comment]
E.g. is there a way to tell if this is working without necessarily installing and learning zipkin?

**Comment by objectiser** [comment]
The way I isolated the specific SHA was to update the docker image tag [here](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/Dockerfile-frontenvoy#L1) and [here](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/Dockerfile-service#L1).

Then using the instructions in the [jaeger-example](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_tracing#running-the-sandbox) to test it out - or you can use the zipkin-example that was mentioned originally.

Only thing I do slightly different from the instructions is I use the following curl command instead:
```
curl -v localhost:8000/trace/1
```

**Comment by jmarantz** [comment]
Thinking about this -- not having re-reviewed the commit yet, it seems the most likely introduced bug is that a NullTracer is used when it shouldn't be. I'll take a look at that first.
