### ISSUE TITLE
what IDE your team use

### ISSUE THREAD

**Issue by xiaoma2100** [envoyproxy/envoy#5264]
Hi all,
what IDE your team use for C++? the source insight and VS 2017 is support not good like those code.

class TagProducer {
public:
  ~TagProducer() {}
  std::string produceTags() const PURE;
  int other_member_;
};

typedef std::unique_ptr<const TagProducer> TagProducerPtr;

TagProducerPtr tag_producer_;

it is can NOT list the members of tag_producer_  automatic, is there any IDE support list this kind of members?

**Comment by auni53** [comment]
Not at all helpful to you, but most of our team uses vim or emacs. Finding cross-inheritance members is a huge pain-point, though eased a little bit by internal tooling.

**Comment by lizan** [comment]
I use CLion, with [a script](https://github.com/lizan/bazel-cmakelists) to generate CMakeLists.txt for CLion to index codes.

**Comment by xiaoma2100** [comment]
thanks all, I will try CLion.

**Comment by doodlesbykumbi** [comment]
@lizan how exactly do you use that script with envoy ? gist please :)

**Comment by lizan** [comment]
@doodlesbykumbi In envoy directory:
1. `bazel-cmakelists --targets //test/...` 
1. wait until it finishes (it is a full build so it is time consuming)
1. open the directory with CLion

**Comment by doodlesbykumbi** [comment]
@lizan tried it. failed. i guess there's a bunch of dependencies on OSX missing 🤷‍♂️

**Comment by lizan** [comment]
@doodlesbykumbi Hmm, if you can do `bazel build //test/...` then the script shouldn't fail. I use it on macOS everyday.
