### ISSUE TITLE
RBAC: envoy.filters.http.rbac source_ip principal does not seem to work together with external loadbalancers in front proxy configuration

### ISSUE THREAD

**Issue by rispa** [envoyproxy/envoy#5267]
*RBAC: envoy.filters.http.rbac source_ip principal does not seem to work together with external loadbalancers in front proxy configuration*

*Summary: The envoy.filters.http.rbac source_ip principal seems to be using the "raw" source ip, making it unusable in a edge/front proxy configuration when there are additional loadbalancers in front of it. Are we missing something?*

*Description*:
We are testing envoy as edge/front proxy, and we have a cloud loadbalancer in front of it. The cloud loadbalancer is actually adding two hops in front of the envoy, and we are therefore setting "xff_num_trusted_hops: 2" which makes the "x-envoy-external-address" be set to the correct address. 

Then we add configuration to whitelist/blacklist network ranges for virtualhosts, using a per filter config for envoy.filters.http.rbac, and in it setting a rule to allow only certain network ranges using the source_ip principal.

When running the envoy in trace mode, it seems to confirm that the source ip that is actually used to match with the allowed networks, is the "raw" source ip, meaning it is the previous hop in the cloud loadbalancer set-up, making the filter fail, or always be successful if we add the loadbalancer ips to the list of allowed source_ips.

Eg: "[2018-12-10 16:38:27.988][000029][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:62] checking request: remoteAddress: LOAD_BALANCER_IP:SOME_PORT, localAddress: 10.99.0.2:8443"

Running latest from 2018-12-10, 1.9.0 (pending): envoyproxy/envoy@sha256:67114c50c0013842929da2e3281f946629d045a110da698fdee6f887d4926a1c

Are we missing some configuration to make the rbac filter affect the "real" client source ip (ie the same ip as "x-envoy-external-address" is set to)? If not, I guess this question has more turned into a feature request, if that makes sense? As otherwise this rbac filter is not usable in such a set-up. Also, is there any work-around for now?

Best regards,
Richard Spangberg

**Comment by zuercher** [comment]
I'm not very familiar with the RBAC code, but it looks like the [IPMatcher](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/common/rbac/matchers.cc#L120) only looks at the connection's immediate local or remote address and there's presently no way to configure it to use the x-envoy-external-address or any other header.

**Comment by rispa** [comment]
@zuercher Ok, that corresponds to the behaviour we observed. Thanks for looking into this! I guess this would a non-trivial thing to fix properly?

**Comment by mattklein123** [comment]
@zuercher @rispa yes, we should have a variant of IP matcher that actually uses the `StreamInfo` remote address vs. the connection level remote address. The stream level remote address for HTTP streams will be the correctly populated remote addressed based on XFF processing, etc.

**Comment by yangminzhu** [comment]
/cc @yangminzhu 
This is a good use of RBAC at edge proxy, I guess Istio will have similar issue when enabling RBAC on ingress, will do some investigation to see how to use the correct remote address.

**Comment by mmpei** [comment]
@yangminzhu does envoy support this case now? or any workaround?

**Comment by mmpei** [comment]
it has supported now.

**Comment by anpryl** [comment]
@mmpei can you please share link or configuration example?

**Comment by tinder-mattheworlove** [comment]
bump

We currently have this issue trying to use Envoy as an edge proxy. The remoteAddress used to compare against source_ip should honor the flags and settings set in the HTTP connection manager. Very curious if someone has an implementation/setup that works!

**Comment by yangminzhu** [comment]
@mmpei  Would you mind to clarify a little bit what do you mean for "it has supported now", Are you referring to the RBAC filter?

@anpryl @tinder-mattheworlove I'm afraid this is not supported by the RBAC filter because it's hard-coded to use the immediate source IP instead of the remote IP based on the XFF processing.

 @mattklein123 What do you think if we add a `remote_ip` in addition to the [source_ip](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/rbac/v3/rbac.proto#L223-L224) and use the `downstreamRemoteAddress()` to compare the value, this should be a small and straightforward change. could you assign this to me? Thanks.

**Comment by anpryl** [comment]
@yangminzhu JFYI, we combined `rbac` filter with `ip_tagging` filter to achienve ip blacklisting for entire virtual hosts and ip whitelisting per routes(we need it in some cases)

**Comment by mattklein123** [comment]
> @mattklein123 What do you think if we add a remote_ip in addition to the source_ip and use the downstreamRemoteAddress() to compare the value, this should be a small and straightforward change. could you assign this to me? Thanks.

Yes this makes sense to me.
