### ISSUE TITLE
data-plane-api and go-control-plane are out of sync on ServerInfo

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#5269]
The PR  https://github.com/envoyproxy/data-plane-api/commit/c38054d891dd23ad2939d54cc62269491f680e4f makes Istio fail in a test: https://circleci.com/gh/istio/istio/266566?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link:

> Error: unknown field "command_line_options" in envoy_admin_v2alpha.ServerInfo

The go-conrol-plane is not updated with the field "command_line_options"

cc @ramaraochavali

**Comment by zuercher** [comment]
I don't think this is really an Envoy issue. Also, folks are working on a sync already: envoyproxy/go-control-plane#134
