### ISSUE TITLE
Clarify and simplify the ADS and xDS over gRPC implementations

### ISSUE THREAD

**Issue by fredlas** [envoyproxy/envoy#5270]
The current implementations of xDS over gRPC and ADS are hard for someone new to the code to understand, or at least, hard for this particular new someone :)

Here is the situation: there is GrpcMuxImpl, GrpcSubscriptionImpl, GrpcMuxSubscriptionImpl, and GrpcManagedMuxSubscriptionImpl. GrpcSubscriptionImpl owns both a GrpcMuxImpl and a GrpcManagedMuxSubscriptionImpl. GrpcManagedMuxSubsciptionImpl holds a reference to the GrpcMuxImpl its owner owns, and also owns a GrpcMuxSubscriptionImpl.

What does someone who wants to write code that uses an xDS client, or ADS client, do? The answer is use GrpcSubscriptionImpl or GrpcMuxImpl, respectively, but I had a very hard time figuring that out, even after talking with people who already got it.

The Subscription interface sounds like it should be the conceptual attachment point for all users of xDS. That made me expect ADS would also operate through GrpcSubscriptionImpl: that you would create something like a GrpcMuxImpl as the single object actually communicating with the server, but then you would associate your Subscriptions to it and interact only with them. I was therefore confused when I realized that every newly created GrpcSubscriptionImpl would create a new gRPC stream.

The GrpcMux abstract interface has comments saying it can be used for either single xDS or ADS, but that's not quite true: single xDS uses GrpcSubscriptionImpl. That class is basically a wrapper around GrpcMux, but that's an implementation detail that should be hidden from the user. Since you wouldn't expect something called mux to need to be involved when you only want to work with a single thing, it's confusing to see this class suggested for xDS.

GrpcSubscriptionImpl is just a wrapper around GrpcMuxSubscriptionImpl. That is to mediate between two cases: whether the Subscription should own the GrpcMux (single xDS), or it should not (ADS). I don't think a wrapper class is the right way to do that. Rather, maybe GrpcSubscriptionImpl could have an additional absl::optional<GrpcMuxPtr> field, and the grpc_mux_ field that exists in both classes could be a reference in the new single class. (Or it could just be a shared_ptr; not sure if that would be considered justified in this case).

Adding comments to the implementations will certainly help a lot. However, I think an overhaul of the class names would also greatly help, along with the GrpcMuxSubscription refactor mentioned above. I opened this as an issue rather than just getting started on making changes so we could discuss 1) if the renames/refactor are a good idea, and if so 2) what exactly to rename to. To get things started, I propose
GrpcMuxImpl->AdsMuxImpl
GrpcSubscriptionImpl->XdsSubscriptionImpl
GrpcMuxSubscriptionImpl->deleted
GrpcManagedMuxSubsciptionImpl->not yet sure, but I suspect it can be pulled into XdsSubscriptionImpl in the same way I'm proposing for GrpcMuxSubscriptionImpl.

Also, I wonder: could GrpcMuxCallbacks and SubscriptionCallbacks be merged? The only difference is that SubscriptionCallbacks' onConfigUpdate takes typed resource protos. What if we had only SubscriptionCallbacks, and ADS gave GrpcMux several of them, one for each type? I think they would fit naturally as a field of ApiState. Maybe this idea should be considered separately, though.

I know that is a lot to digest, but please let me know what you think!

**Comment by dmitri-d** [comment]
I largely agree with the above. Not sure re: using ```absl::optional``` (thanks for pointing this out, didn't know something like this existed in C++) -- it looks to me like an analogue ```Option/Maybe``` monad, which I don't think is a great fit here. Switching to ```std::shared_pointer``` and perhaps providing two constructors (one instantiating mux in place, another taking it as a parameter) would work, I think.

Still thinking re: callbacks.

**Comment by htuch** [comment]
I agree that naming could be improved. Some concrete feedback:

* `GrpcMuxImpl->AdsMuxImpl`: I don't think this one is valid. We use the gRPC mux for EDS subscriptions (and probably RDS in the future as well) to mux the same resources.

* `GrpcSubscriptionImpl->XdsSubscriptionImpl`: I don't think this one is that helpful, as there are multiple xDS subscription implementations, for filesystem (FilesystemSubscriptionImpl) and also for REST (HttpSubscriptionImpl). So, this one isn't valid.

* I'll defer to you and @dmitri-d on what you want to do with the managed mux subscriptions. These are a very recent introduction to the xDS class structure, so there are few dependencies. Feel free to restructure to whatever makes sense.

I don't think we should merge the callbacks. The key thing missing here from the proposal is that, just like with the `XdsSubscriptionImpl` point above, the subscription callbacks are used for non-gRPC xDS subscriptions, i.e. filesystem and HTTP.

**Comment by fredlas** [comment]
>shared_pointer
Ok, nice to hear some support for the shared_ptr approach. I definitely agree, I think I've just been a little bit conditioned to avoid introducing new uses of shared_ptr whenever possible!

>AdsMuxImpl, EDS
Ah ha, that did not occur to me. In that case, I think simplifications in other places and good comments should be enough to clear things up about this class.

>XdsSubscriptionImpl
Yeah, I guess I was implicitly thinking only in terms of gRPC. That reminds me, though: the v1 API implementations over in common/upstream, like CdsSubscription, have similarly overly broad names. I've opened them a couple of times thinking they might be relevant to what I'm doing. Should they perhaps be specified in their names as v1?

>callbacks
I don't think the non-gRPC implementations would interfere/be interfered with. The proposal is to replace GrpcMuxCallbacks with (multiple) SubscriptionCallbacks. I don't think the SubscriptionCallbacks interface, or any of its users, would need to change.

**Comment by htuch** [comment]
On shared_ptr, I think this makes sense if there is genuinely a multi-owner scenario, e.g. one owner might disappear and the other owners still need to retain the object. If there is a canonical owner, which outlives any other owners, we should just take a pointer/reference and not manage ownership.

On v1 API implementations, we're going to nuke these at the next release, so I think the shelf life of this code is < 1 month. I recommend just letting it age out.

On `GrpcMuxCallbacks`, if you replace with `SubscriptionCallbacks`, I don't think you have sufficient type-level information at the call site to do this. You need to supply the typed instantiation at places like https://github.com/envoyproxy/envoy/blob/3d1d3f7b1fb46a36f69b90539557a81232c3c6e2/source/common/config/grpc_mux_impl.cc#L236. However, you only have the type URL, not the C++ type here.

**Comment by fredlas** [comment]
Agreed about shared_ptr. I think it depends on whether the following is sensible: in ADS initialization you create a shared_ptr<GrpcMux>, create the various xDS subscriptions that will be multiplexed by it, give them all the shared_ptr, and then drop the original copy of the shared_ptr. But then there's also the multiple EDSes thing. I'll have to look into that.

If that is not a good approach, then yeah, the current where anyone doing something that involves GrpcMux should own that GrpcMux is as it should be.

Good to hear about the v1 stuff; deletion is always a good solution when possible!

Gah, I think I see now about the callbacks. It's so close: if GrpcMuxWatch and ApiState were to become also templated, it would work... but then you'd have to do something, probably hacky, about the fact that you would then be wanting to hold various template instances in the api_state_ map.

**Comment by htuch** [comment]
Re: shared_ptr, I think this makes sense if-and-only-if the xDS subscription lifetimes need to outlive their creating objects, so depends on where you see the object structure & lifetimes going here.

**Comment by fredlas** [comment]
I think the upshot was that there is at least some opportunity here for cleanup. I'm hoping to get to it in the course of working on #5466 / #4991.

**Comment by fredlas** [comment]
After some discussion with @jmarantz and someone else, I see the problems more clearly. I think if we simultaneously change 1) the way xDS/ADS are understood at the documentation/conceptual level, and 2) some class names down in the implementation, we can greatly clarify things.

The name ADS can confuse people, because pattern matching makes you think it's a service for discovering 'A'. Thinking about that, I realized ADS doesn't really need a name of its own. Why not present xDS/ADS as just: "xDS is a service for Envoy to discover its various resources. You can either send all of your resources in one xDS stream, or you can break it out by resource type into multiple xDS streams."

Beyond removing a confusing term, I think this presentation (plus some renames and comments) would make the implementation's structure much easier to comprehend. I was looking for an xDS implementation, and an ADS implementation that multiple xDSes could plug into. If GrpcMux was named something like GrpcXdsContext, it would be more natural for e.g. ClusterManager to be dealing with it. As in, it's not clear why ClusterManager is muxing gRPC, but it's natural to need an GrpcXdsContext to have a functioning xDS stream (thanks Josh for this idea).

**Comment by htuch** [comment]
I'm pretty strongly against dropping ADS as a term at this point, it's already pretty widely used inside Envoy and various other projects and has a generally understood public meaning.

**Comment by fredlas** [comment]
Wasn't the same true when SDS was renamed to EDS? This would be simpler than that: rather than a name change, it would be a recognition that a term already in use (xDS) already naturally covers what had been presented as a special separate version of that thing.

**Comment by htuch** [comment]
@fredlas if there is significant community support for this (i.e. others find it terribly confusing and would prefer instead to use xDS for both aggregated and non-aggregated), then we can consider this, I don't want to be a blocker. My personal take is that ADS serves a useful role in describing a concrete service endpoint and mode of operation for xDS, but language is a tool for communication and we should adapt it to best serve the needs of its speakers.

**Comment by ramaraochavali** [comment]
+1 to what @hutch said - I think ADS is pretty widely used and have well understood meaning.  And regarding SDS -> EDS I think since it was done very early in the v2 life cycle (probably right from v2 API it self @htuch please correct me here, if this wrong) , it did not impact much.

**Comment by fredlas** [comment]
I have a mostly-done implementation of aggregated delta xDS that is built along the lines of the "GrpcXdsContext" approach described above. It entails de-templatizing the existing xDS code, which is by itself a nice (and surprisingly simple!) cleanup. Once everything is de-templatized and that implementation is submitted, I will look at reimplementing vanilla xDS in the same style as the new implementation. They might even be able to share additional code.

**Comment by fredlas** [comment]
The aggregated delta implementation mentioned above is now "done", in that a week or two ago it reached the point of having all the features I wanted, and passing all tests. I still have to merge some recent work around there back in, but I should be opening a PR for it pretty soon.

**Comment by fredlas** [comment]
The ultimate goal this issue is describing is the replacement of the existing gRPC xDS implementation (GrpcMuxImpl, GrpcSubscriptionImpl, GrpcMuxSubsciprtionImpl) with a single unified (delta+SotW) chunk of code based on what I'm implementing for delta (#4991). And, it has become clear that the only way for the delta implementation to avoid adding some unnecessary ugliness is to make that unification happen.

So, at this point, this issue is essentially a duplicate / sub-item of #4991.
