### ISSUE TITLE
support configuring a fraction of mirror traffic 

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#5273]
Currently, `request_mirror_policy` [0] only supports to config modes:

a) `runtime_key` not set, so 100% of requests get mirrored
b) `runtime_key` is set, so it relies on the runtime key to determine the percentage of traffic

We have a need for a third mode which is:

c) allow setting the percentage via a config key (e.g.: `default_percentage`)

Does this sound reasonable? If so, I'll send a PR.

[0] https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L622

**Comment by mattklein123** [comment]
@rgs1 +1 we have done many PRs similar to this. Take a look through config history and I think you will find several things to model on.

**Comment by rgs1** [comment]
We could add a new field that is either a `RuntimeUInt32` [0] or a `RuntimeFractionalPercent` [1], and have it take precedence over the `runtime_key` field which will become deprecated. Something like https://github.com/envoyproxy/envoy/commit/bcc7a96d9e66bc0f70e3ed52161ec3471f835bdb.

[0] https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/base.proto#L106
[1] https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/base.proto#L233

**Comment by mattklein123** [comment]
@rgs1 definitely do a fractional percent for new code. Thanks!

**Comment by rgs1** [comment]
@mattklein123 @zuercher something like https://github.com/envoyproxy/envoy/pull/5295?
