### ISSUE TITLE
how to configuration envoy redis cluster 

### ISSUE THREAD

**Issue by dzhyw** [envoyproxy/envoy#5276]
how to configuration envoy redis cluster , can you give me a example?

**Comment by ramaraochavali** [comment]
Here is a sample on how it can be configured https://github.com/envoyproxy/envoy/blob/892168c1dbbc7e6f7b94181b5cb29150667e81e6/test/config/integration/server.json#L429

**Comment by mattklein123** [comment]
@danielhochman a Redis example would be cool
