### ISSUE TITLE
hds: Envoy not respecting HDS protocol when requesting health checks

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#5279]
Envoy is [sending a HealthcCheckRequest message](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_discovery_service.h#L166) when requesting healthchecks but it should be sending a HealthcCheckRequestOrEndpointHealthResponse per [proto definition](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/discovery/v2/hds.proto#L55).

**Comment by mattklein123** [comment]
@htuch what's the impl status of HDS?

**Comment by sschepens** [comment]
@mattklein123 I think HDS is mostly working, been trying to test it and found out this issue when trying to make it work with a control plane. With this fix everything seems to be working OK.
