### ISSUE TITLE
Add query_parameter_to_metadata and query_parameter_to_header http filters

### ISSUE THREAD

**Issue by kh-chang** [envoyproxy/envoy#5291]
*Title*: *Add query_parameter_to_metadata and query_parameter_to_header http filters*

*Description*:
Currently there is a header -> metadata filter (header_to_metadata) and similar filters for other mapping can be useful:
1) query param -> metadata
2) query param -> header 

*Relevant Links*
https://github.com/envoyproxy/envoy/issues/5281

**Comment by kh-chang** [comment]
@lizan @qiannawang @bochunz

**Comment by bochunz** [comment]
is it possible to rename that existing filter? If not, seems like adding the additional config that handles query param will make the filter name awkward.
