### ISSUE TITLE
grpc -> http/1.1 filter

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5300]
We run a filter internally that converts gRPC requests into HTTP/1.1 requests. This is used to allow apps that do not have good gRPC support handle requests sent from an gRPC client, allowing call sites to be uniform regardless of the gRPC capabilities of the upstream. 

The filter works like this:

1) Determine whether the filter should be applied based on filter metadata.
2) If applicable, convert the `content-type` into the desired header. For us this is `application/x-protobuf`
3) Strip the length prefix from the body (ie drain the first 5 bytes)
3) Send the request to an http/1.1 upstream cluster
4) If the content type does not match `application/x-protobuf`, respond with a header only response
with a useful `grpc-message` and `grpc-status: 2`
5) Set response content type to `application/grpc`
5) If the response code was not 200, map it to appropriate `grpc-status` code
6) Otherwise, buffer entire body, compute length and insert length prefix into the start of the buffer
7) Insert trailers to set `grpc-status`

This is essentially the opposite of the gRPC HTTP/1.1 bridge, providing gRPC support to the server instead of the client. It only works for unary calls. 

There seemed to be some interest from people in having this upstreamed, so figured I'd put this up to see if it's worth adding. 

fyi @lita @junr03

**Comment by lizan** [comment]
Yeah there seemed to be interest for this. Have you considered do opposite of gRPC-Web instead of http-bridge? It has a standardized protocol spec and better support for half-duplex streamings.

**Comment by mattklein123** [comment]
@snowp yeah I do think there is general community interest in such a thing, we have discussed having this at Lyft also.

**Comment by snowp** [comment]
@lizan Considered something like gRPC-Web but we've got years of protobuf RPC infra that predates gRPC, so it's been useful for us to have this filter support our old proto-over-http clients that aren't gRPC aware. I think it makes sense for gRPC-Web to do this, but for us having to replace all the clients is a ton of work, so we'd prefer a simpler alternative. 

I'll clean up what we have internally and get a PR up.

**Comment by lizan** [comment]
@snowp I meant "gRPC -> gRPC-web" to support gRPC aware client to issue HTTP/1.1 (gRPC-web) request. But yeah if you have tons of server already doing proto-over-HTTP then probably that is fine.

**Comment by snowp** [comment]
Ah yeah, that’s what I meant as well. We do have both clients and servers
that conform to this.

**Comment by mattklein123** [comment]
@snowp what do you mean by an actual maintainer? You mean a current maintainer to sponsor? Yes I'm happy to do that.

**Comment by snowp** [comment]
@mattklein123 Yep that's what I meant, please excuse my poor wording :)
