### ISSUE TITLE
Minimal support for multiplexed transport connections

### ISSUE THREAD

**Issue by jrajahalme** [envoyproxy/envoy#5301]
Envoy currently relies on 1:1 correspondence between `ConnectionImpl` and a connection accepted by a listener. This is too rigid for use cases where multiple logical connections are transported over a single socket. Cases like this include, for example, UDP based transports, tunneling protocols, etc.

Ongoing work on IoHandle abstraction (#5171, #5171) are required enablers for transport multiplexing, but is not sufficient without some additional work.

A Listener is required to accept the multiplex itself, but creating a ConnectionImpl for it may not be required, as regular (HTTP, TCP proxy) etc. filter chains should only see the demultiplexed traffic. Taking a cue from how the proxy protocol listener filter performs initial I/O on a new connection before passing the connection on to the connection handler, it is possible to handle all I/O for the multiplex in a listener filter. To then create new Connections as they appear over the multiplex, a new `newConnection()` _listener filter callback_ is required.

The actual I/O on such multiplexed connections needs to be performed using a specialized `TransportSocket` that works in concert with the multiplex listener filter, buffering the data for the multiplexed connections and providing the means of writing data back to the multiplex in the reply direction.

To be fully functional the multiplex must support connection closure and possibly half-closed semantics. @mattklein123 has suggested elsewhere that timeouts maybe sufficient for connection close handling in cases where the underlying protocol provides no indication of connection closing.

The purpose of this issue is to gather initial feedback on the design before issuing a PR. To be clear the intent of this discussion at the moment is limited to the addition of the single `newConnection()` _listener filter callback_ that is to perform similarly to the internal connection handler behavior when a listener filter chain completes. The only difference is that after such callbacks the listener filter chain is not required to complete.

I have prototyped the concepts discussed here so I have some level of confidence that this actually works :-)

**Comment by jrajahalme** [comment]
@mattklein123 I'm integrating Envoy with kTLS where connection pay-loads from a container are redirected to Envoy before hitting the TCP layer. The TCP and TLS handshakes happen normally between the original connection endpoints, but the unencrypted payload traffic is forwarded to Envoy using TCP sockets that have been set up for the sole purpose of redirection. Payloads from a number of app connections are multiplexed over these pre-established redirect sockets by prepending them with the connection 5-tuple and frame length.

From the Envoy viewpoint the details of the frame header etc. are not that interesting, but the fact that multiple connections are multiplexed over a single socket is, as that collides with the current assumption of 1:1 correspondence between a ConnectionImpl and a file descriptor. I envision that the current IoHandle work, when merged, will allow implementation of 'virtual IO handles' that map to the multiplex header instead of an actual  file descriptor.

The new listener filter callback being proposed here provides one critical piece of the puzzle: The ability of a single accepted socket to "spawn" multiple Envoy Connections. Using multiple filter chains and filter chain matching it is also possible that such Connections be configured with different (network) filter chains. This is why the model of a listener filter spawning multiple Connections is a better fit than, e.g., a network filter doing the same.

Functionally, this is a very small change, as the `newConnection()` currently happens implicitly at the end of the listener filter chain. So the most trivial implementation using this new callback calls with the accepted socket as a parameter and it and then returns `StopIteration` from the listener filter. This would result in the exactly same behavior as if the filter returned `Continue` without calling the new callback. Actual multiplexing cases are more complex and require use of a specialized `TransportSocket`.

One somewhat open question in the scheme is the management of the event loop for the multiplexed connections, but this is something that must be solved for the generalized `IoHandle` independently anyway.

It seems to me that UDP listeners could benefit from this approach as well, if a single accepted UDP socket receives traffic from multiple sources that each should get their own network&http filter chain.

**Comment by mattklein123** [comment]
@jrajahalme cool thanks for the explanation. Yes I agree this makes sense and that it might ultimately overlap with the QUIC work. cc @envoyproxy/quic-dev 

Please make sure to have a test listener filter that demonstrates the new functionality. Optimally we would even have an integration test that fakes the multiplexing to demonstrate the real end goal.

**Comment by alyssawilk** [comment]
@jrajahalme a related thing I believe we're going to want (and will upstream as much as anyone else wants) is to handle incoming TCP being muxed out the back over H2 (probably using CONNECT?) and then demuxed at an upstream Envoy.  The fun thing there is that basically every H2 stream will turn into its own Network::Connection which can be read from or written to as if it were socket.

This basically allows a transparent proxy at the edge to forward TLS to a terminating proxy without using up all the ephemeral ports.  Even better if we can do it over QUIC to avoid head of line blocking.  I don't think this requires a special listener, but I suspect there may be some design overlap so I'd be interested in helping on reviews if you tackle any of this.

**Comment by mattklein123** [comment]
We have made a lot of changes in this area so let's open new issues on specific changes needed.

**Comment by moderation** [comment]
Interesting blog post and orange site comments about NGINX and kTLS - https://news.ycombinator.com/item?id=30902744
