### ISSUE TITLE
Filter returning StopIterationAndWatermark still gets 413 Payload Too Large errors

### ISSUE THREAD

**Issue by kellycampbell** [envoyproxy/envoy#5302]
*Title*: Watermarked buffering doesn't seem to work with ext_authz filter

*Description*:

I'm trying to figure why Envoy is sending a 413 when it seems like the watermark buffer should be preventing that. I'm using an ext_authz filter configured via https://github.com/datawire/ambassador

I've read through this documentation already: https://github.com/envoyproxy/envoy/blob/master/source/docs/flow_control.md

I think the basic problem stems from `ConnectionManagerImpl::ActiveStreamDecoderFilter::requestDataTooLarge` not considering the `StopIterationAndWatermark` case correctly.

If you search across the envoy project for places that can send 413, the only function that does that is `requestDataTooLarge` in conn_manager_impl.cc

The condition in that is:

```c++
  if (parent_.state_.decoder_filters_streaming_) {
    onDecoderFilterAboveWriteBufferHighWatermark();
  } else {
    sendLocalReply(Code::PayloadTooLarge, ...);
  }
```

Searching the code for that state variable `decoder_filters_streaming_` shows it's only set in `ConnectionManagerImpl::ActiveStream::addDecodedData` which comes from a plugin calling that with the `streaming` param set to true. Most plugins like ext_authz and jwt_authn don't use that since they just want the original request to stream if authentication passes.

Based on the flow_control.md document and other comments within the source code such as in filter.h and ratelimit.cc, I expected that a 413 would not happen if a plugin returns `StopIterationAndWatermark` vs. `StopIterationAndBuffer`.

*Relevant Links*:

I first ran into this issue with running a bazel remote cache and reported related request which includes some debug logging here: 
https://github.com/datawire/ambassador/issues/1036

**Comment by mattklein123** [comment]
@kellycampbell it's also set via a call to `commonHandleAfterDataCallback()`. I think this should be working so this might need some more debugging?

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by kellycampbell** [comment]
@mattklein123 thanks for the quick response. Sorry for my mistakes. I missed that `buffer_was_streaming` param. I also failed to account for the initialization to `true` in the header file.

I didn't look too closely at the datawire fork until now, but that has a really different set of code for this.

https://github.com/datawire/envoy/blob/master/source/common/http/conn_manager_impl.cc#L1603

I will investigate the differences and retest with the envoyproxy version instead.

**Comment by kellycampbell** [comment]
Looks like it does work with the most recent envoy builds from envoyproxy. 

I only did some cursory research on the differences between ambassador master and envoyproxy master, but didn't pinpoint the cause.

Here's a log of 100MB file that uploaded without error:
```
[2018-12-15 01:35:50.206][000049][debug][router] [source/common/router/router.cc:323] [C736][S14271036388356826473] router decoding headers:
':authority', 'bazel-cache.eng.mydomain.com:443'
':path', '/cas/ac32fbb4ee9e0bcf3a4b54c9372e080d8c950587700b06540ed2d5e7160da837'
':method', 'PUT'
':scheme', 'http'
'accept', '*/*'
'content-length', '107929600'


ACCESS [2018-12-15T01:35:50.068Z] "PUT /cas/ac32fbb4ee9e0bcf3a4b54c9372e080d8c950587700b06540ed2d5e7160da837 HTTP/1.1" 200 - 107929600 0 73040 231 "100.102.94.128" "-" "09cbb49d-33bf-42dd-a053-d76ad29e1eb0" "bazel-cache.eng.mydomain.com:443" "100.71.158.68:8080"
```
