### ISSUE TITLE
Bug: continueDecoding calls the wrong filter for decodeData() calls

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#5311]
*Description*:

In this specific case: there are 3 decode filters. The second filter calls addDocodeData() in its decodeHeaders() call. The buffered data should be passed to the 3rd filter, not to the 2nd filter since it is added by the second filter.

This is correct if all filters are "continued". But it is not correct if the first filter is stopped and continued with continueDecoding() call.

*Repro steps*:

This PR https://github.com/envoyproxy/envoy/pull/5310 added a test that will not pass.

**Comment by qiwzhang** [comment]
The problem is with zero byte buffer.  The filter decodeData() is called with zero byte buffer even after end_stream. This causes some filters to raise assertions.  

There is a one line change in #5310 ;  not to call doData() if buffer size is 0. 

But it still has in-consistent behaviors.    When decoder->decodeData(zero_byte_data), in all "continue" case, decodeData() is called for all filters.  But in "stop" and "continue" case, decodeData() is NOT called for the filters after "stop".  This behavior is verified by test case in "ZeroByteDataFiltering".

**Comment by qiwzhang** [comment]
@mattklein123 @htuch is this fix OK?

**Comment by qiwzhang** [comment]
Another attempt to fix this issue:  https://github.com/envoyproxy/envoy/pull/5350

@mattklein123  @alyssawilk @htuch could you take a look?

**Comment by qiwzhang** [comment]
Here is the detail of the issue; 

add 3 decoder filters,

1) filter[0]->decodeHeaders() returns STOP, and is continued with ContinueDecoding,
2) the filter[1]->decodeHeader() adds decodeData() and continue,
3) filter[2]->decodeHeaders() is called, then filter[2]->decodeData() is called,
4) filter[1]->decodeData() is called with zero byte buffer.

Step 4) is not expected. it is wrong.

**Comment by qiwzhang** [comment]
Here is the calling graph:  

"wrapper" refers to ConnectionManagerImpl::ActiveStreamFilter
```
filter0->decodeHeaders(),  stopped
   filter0->callback->continueDecode()
   wraper0->commonContinue
          wraper0->decodeHeaders()  {
                 filter1->decodeHeaders ()
                       addDecodeData()
                 filter2->decodeHeaders()
                 wrapper1->commonContinue() since it detects data is added by filter1  {
                      wrapper1->doData()
                          wrapper1->decodeData(filter1,..)
                                filter2->decodeData()
                }  // end of wrapper1->commonContinue
             }  // end of wrapper0->decodeHeaders
             wraper0->doData() is called
                   filter1->decodeData()      // this is wrong. it causes crash.
```

**Comment by qiwzhang** [comment]
The root of issue is:  there is only one buffer for a stream. Any filters can add data to this buffer. We lost the info of which filters add the data.

Specifically, the problem in this [line](https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L1472)

If commonContinue() is called nestly (one inside another);  the inner call detects who adds the data, and call the proper decodeData() to consume it.  But outer layer doesn't know, it continue to call decodeData().

**Comment by qiwzhang** [comment]
This bug causes grpc_json_transcoder filter to crash (hit assertion) if there is another filter in front and does "StopIteration" and "continueDecoding".

**Comment by qiwzhang** [comment]
This is another attempt to fix this:  https://github.com/envoyproxy/envoy/pull/5360

@mattklein123 @htuch PTAL

**Comment by mattklein123** [comment]
@qiwzhang I need to spend time looking into this to better understand the underlying problem. I'm sorry but I won't be able to do this for a few days. If @alyssawilk can look sooner I will defer to her otherwise I will get back to you then. In the meantime, in your description above in https://github.com/envoyproxy/envoy/issues/5311#issuecomment-448717480, can you be clear about where end_stream is set? It's very important to understand that.

**Comment by alyssawilk** [comment]
Hah, wish I could be more help. I took a look at the current implementation, convinced myself it couldn't work as advertised (despite @qiwzhang sensibly adding tests which proved it worked), and had to download and gdb my way though the patch before I figured out how it worked.  Props to @qiwzhang for tackling a really complicated issue but I'm pretty sold we want Matt's review on this one.

**Comment by qiwzhang** [comment]
@mattklein123 I updated the [comment](https://github.com/envoyproxy/envoy/issues/5311#issuecomment-448717480) with end_stream value.

**Comment by qiwzhang** [comment]
@mattklein123  Here is the PR to implement your idea. https://github.com/envoyproxy/envoy/pull/5393
