### ISSUE TITLE
Runtime Docker image improvements

### ISSUE THREAD

**Issue by JayH5** [envoyproxy/envoy#5325]
*Title*: Improvements to the runtime Docker images

*Description*:
This is a tracking issue for proposed improvements to the runtime Docker images for Envoy. I spoke to Matt briefly at EnvoyCon and he told me there isn't really a single person responsible for the Docker images and that contributions would be welcome.

While there isn't anything critically wrong with the existing images, I think they could be refined in some ways. Spinning up an Envoy Docker container is probably one of the most common ways that people first interact with Envoy, so it is important that they work well. And while it seems like few of the companies that are core users of Envoy use these Docker images in production (e.g. Lyft uses binaries, not Docker), some popular downstream projects (e.g. Heptio Contour) do.

The [`docker-library/official-images` repo](https://github.com/docker-library/official-images) where the majority of the top-level Docker images (e.g. `FROM ubuntu`, `FROM golang`) are built from provides some [guidelines](https://github.com/docker-library/official-images#review-guidelines) for image best practices. While the Envoy project may not want to use _all_ of those guidelines, I think they provide a good starting point. I've also worked a bit on some of the "official images" (mostly the Python one) and so am familiar with how things are done there.

Some initial work could be:
- [x] Add a simple entrypoint script (as shown in the official-images guide)
- [ ] Ensure no unnecessary packages are in the images (i.e. the images are "minimal")
- [ ] Ensure all images are based on official or reasonably official images (e.g. the Alpine image is currently based on a community-maintained image with glibc for Alpine--is this ok?) and not the `latest` tags.
- [ ] Provide a simple way to run Envoy as a non-root user
- [ ] Consistent story around configuration with environment variables (e.g. there's a `$loglevel` variable that is quite ad-hoc and in a lot of cases probably unused).

Some further work could be:
- Add some basic tests?
- Improve the [build process](https://github.com/envoyproxy/envoy/blob/890f1f13179e74d4b728599da66466acf0338762/ci/do_ci.sh#L43-L48)?
- Move to Ubuntu 18.04 base?
- Use more of Bazel's Docker build tools ([`rules_docker`](https://github.com/bazelbuild/rules_docker))?
- Run security scans against images?
- Get images published as part of the "official images"?

These are just some suggestions and can, of course, be changed. As of writing, I haven't run these by anybody yet, but I thought it best just to get the ball rolling. I'll open a PR or two to start.

Note that this issue is just about the runtime images for now. I haven't looked into the build image yet but could work on that eventually as well if there's interest.

*Relevant Links*:
[`docker-library/official-images` review guidelines](https://github.com/docker-library/official-images#review-guidelines)
PR #2850 (seems like the last attempt at something like this), and corresponding issue which is very similar: #2805

**Comment by alyssawilk** [comment]
Very cool, thanks for diving in on this!
Ok if I assign this issue your way, or is "help wanted" more appropriate?

**Comment by JayH5** [comment]
@alyssawilk yes, please assign it to me.

**Comment by moderation** [comment]
@JayH5 This looks great. I had a simpler idea that I referenced at https://envoyproxy.slack.com/archives/C78HA81DH/p1542913012403100. The specific diff is at https://slack-files.com/T5CALEVRN-FEB9ZV207-93db8e17ef. Just with these simple changes the image size of 157MB (uncompressed) drops to 119MB.

**Comment by JayH5** [comment]
@moderation thanks. Yeah, the Ubuntu devs made some improvements to the image size in 18.04. Even smaller are the Debian "slim" images (e.g. `debian:stretch-slim` is around 55MB uncompressed) that many of the official images use. Getting the image super small is a bit of a rabbit hole, though.

I'm just planning to chip away at this and Ubuntu 18.04 probably makes sense in terms of changing as little as possible.

Is there a reason the Docker images don't already use 18.04? Is it just that nobody has got around to it yet?

**Comment by moderation** [comment]
@JayH5 I think it is because no one got around to it. A lot of people (including me) roll our own container image to meet company requirements. I think sticking with Ubuntu 18.04 makes sense. In the past I've looked at https://hub.docker.com/r/bitnami/minideb/ which looks promising.

**Comment by JayH5** [comment]
@moderation ah there seems to be a bitnami image for everything 😅. Those do look good and conceptually (and size-wise) similar to the slim Debian images. For Envoy, _technically_ all we need is an image with glibc and a CA cert bundle, so even something like [`distroless/base`](https://github.com/GoogleContainerTools/distroless/tree/master/base) could work too...

> A lot of people (including me) roll our own container image to meet company requirements.

I'd be interested in hearing more about these requirements and whether some of them could be satisfied in the official image?

**Comment by redbaron** [comment]
bot, leave this issue alone

**Comment by vmpn** [comment]
Commenting on this thread is it covers moving to 18.04 Ubuntu base.

There are vulnerabilities in 16.04 base image that are addressed in 18.04.  I am happy to provide details via secure channel if that helps.
