### ISSUE TITLE
gRPC HTTP/1.1 bridge doesn't support content-type application/grpc+proto

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#5328]
*Description*:

I found that gRPC HTTP/1.1 bridge doesn't support `content-type` like `application/grpc+proto`. This can be verified from the code https://github.com/envoyproxy/envoy/blob/25b143c9813671c320561f8b0b8b31d7e0a3dac4/source/extensions/filters/http/grpc_http1_bridge/http1_bridge_filter.cc#L27

As [grpc doc](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) shows, `application/grpc` and `application/grpc+proto{or custom}` are all valid. Because of this problem, this filter can't add stats for some normal gRPC requests if they have the header `application/grpc+proto`.

Is this expected? Or should we change this to support more gRPC implementations?

I'm happy to send a PR for this issue if needed.

**Comment by alyssawilk** [comment]
I think we just didn't have any use cases of that yet, but reading the linked doc it looks like we should be more flexible there.  If you're up for doing the pr, I think that'd be great!

/ccing @lizan as our resident gRPC expert
