### ISSUE TITLE
grpc-web filter not setting http status code from grpc status

### ISSUE THREAD

**Issue by jwahlin** [envoyproxy/envoy#5331]
I'm using the grpc-web filter and it isn't setting the http status appropriately from the gRPC status. The gRPC status is coming through the response in the trailers since we're using http2. 

To replicate the issue, use the grpc-web filter and send a grpc-web request through Envoy that should fail. The grpc-status will be non-zero, but the http status will show 200. I expect envoy to translate the grpc-status trailer to an http status.

**Comment by qiwzhang** [comment]
@fengli79 ?

**Comment by fengli79** [comment]
@jwahlin, the grpc status is encoded as response body instead of the http/http2 response code.

[https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
](url)
`HTTP/2 related behavior (specified in gRPC over HTTP2)

stream-id is not supported or used
go-away is not supported or used`

**Comment by fengli79** [comment]
> Thanks for taking a look at this. I do see the grpc-status included in the response trailers. Just to clarify, you're saying that regardless of the grpc-status, the http status is intended to stay at 200, is that right?
Correct.
> 
> I'm not sure how the stream-id and go-away changes are related.
They only exist between envoy and your grpc server. Your downstream is using http to talk with envoy, although its can be http2, but semantically it's http in grpc-web, stream id and go-away is not visible there.

**Comment by jwahlin** [comment]
Thanks for the information. When we use http (and the grpc_http1_bridge), the grpc-status does affect the http status. When we use http2, the grpc-status does *not* affect the http status. Are there any plans to add a grpc_http2_bridge that sets the http2 status based on the grpc-status?

**Comment by jwahlin** [comment]
Thanks for your time!
