### ISSUE TITLE
[Question] Meaning of [C~] character included in connection log and stream log etc

### ISSUE THREAD

**Issue by nakabonne** [envoyproxy/envoy#5359]
*Title*: *[Question] Meaning of [C~] character included in connection log and stream log etc*

*Description*:
You could see a character string [C (number)] as follows in Envoy's log. Would you tell this meaning?
I think logs with the same id are logs in the same connection since I recognize it's like a connection id, but is it right?
Thanks.

```
[2018-12-20 01:52:58.930][000011][debug][router] [source/common/router/router.cc:322] [C0][S539228372188944921] router decoding headers:
```

**Comment by mattklein123** [comment]
Yes that's right, it's an internal connectoin ID.

**Comment by nakabonne** [comment]
Helped a lot, thanks!
