### ISSUE TITLE
Thread safety assertion complications after #5072

### ISSUE THREAD

**Issue by AndresGuedez** [envoyproxy/envoy#5390]
#5072 replaced the static accessor to `Thread::currentThreadId()` with a [ThreadFactory](https://github.com/envoyproxy/envoy/blob/master/include/envoy/thread/thread.h#L38) that exposes a virtual [currentThreadId()](https://github.com/envoyproxy/envoy/blob/master/include/envoy/thread/thread.h#L51) function.

This new approach to obtaining the current thread's ID introduces a significant hurdle to writing thread safety assertions (e.g., `ASSERT(owner_thread_id_ == staticGetCurrentThreadId())`), since the `ThreadFactory` instance must now be accessible to classes implementing such assertions.

I explored making the `ThreadFactory` available via the `Singleton::Manager`, but there is a [circular dependency](https://github.com/envoyproxy/envoy/blob/master/source/common/singleton/manager_impl.h#L18) that prevents a simple/clean change to expose it as a singleton.

**Comment by mattklein123** [comment]
@AndresGuedez I think this is one place where I would be fine having a static singleton, since I agree we should make this as simple as possible. cc @jmarantz

**Comment by jmarantz** [comment]
I think we should be able to plumb API wherever it is needed rather than using a Singleton, no?

**Comment by mattklein123** [comment]
That would be preferable, but if it's a big hindrance to people writing thread assertions, I would rather make it easy.

**Comment by jmarantz** [comment]
I didn't understand exactly what you meant by staticGetCurrentThreadId().  Can't you just do owner_thread_id_->isCurrentThreadId() ?

**Comment by mattklein123** [comment]
I think that's just an example of what @AndresGuedez wants to write, which is effectively what we used to be able to do.

**Comment by jmarantz** [comment]
There are two methods on ThreadFactory: createThread and currentThreadId.

From my understanding, thread creation doesn't happen in too many different places in Envoy, but maybe saving the thread ID in order to detect a thread-switch does?

In any case what I was thinking was that API -- originally conceived I think as a layer for extensions -- should be made pretty easy to get to to from just about anywhere. And in addition to ThreadFactory would also provide various API capabilities (Filesystem, TimeSource) that we want to be able to swap out for tests etc.

See also https://github.com/envoyproxy/envoy/issues/5126 for more discussion.

If all else fails we can have a global API lazy-static singleton similar to createAPIForTests.

**Comment by AndresGuedez** [comment]
> I didn't understand exactly what you meant by staticGetCurrentThreadId(). Can't you just do owner_thread_id_->isCurrentThreadId() ?

As an example, see https://github.com/envoyproxy/envoy/pull/5243/commits/7441143d9da63374888458920a072bfc28f326af for a not-yet-merged commit backing out thread safety assertions after I pulled in #5072 from a master merge.

**Comment by jmarantz** [comment]
Andres can you try owner_tid_->isCurrentThreadId()?  I'm not seeing where owner_tid_ is set though; you'd need a ThreadSystem to populate that.

**Comment by AndresGuedez** [comment]
> Andres can you try owner_tid_->isCurrentThreadId()? I'm not seeing where owner_tid_ is set though; you'd need a ThreadSystem to populate that.

This is the core issue; previously, I was initializing the `owner_tid_` via a static function:

`Constructor() : owner_tid_(Thread::currentThreadId())`

Now, I would have to pass the `ThreadFactory` or the TID itself to the constructor, which to me seems an unreasonable burden for the purpose of writing this type of assertion.

**Comment by jmarantz** [comment]
Actually it's not really a problem to have a static ThreadSystem -- we are still injecting it in MainCommonBase, and we should just set the static variable there from the ctor param (and clear it in MainCommonBase's destructor).
