### ISSUE TITLE
Non-const access to HTTP filter buffer

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5394]
Certain filters (such as the new one to be introduced in #5315) rely on being able to mutate the body after it's been buffered, e.g. in order to insert a prefix based on payload size. The current workaround for this is to maintain a separate buffer, which is not ideal due to missing out on the flow control that the internal filter buffer is used for and also the additional code complexity of maintaining a separate buffer. 

Would it be reasonable to expose a non-const pointer to the HTTP filter buffer similar to how the const pointer is exposed?

**Comment by mattklein123** [comment]
@snowp I don't think we can make the buffer non-const, since other filters may have see the buffer which I think would be very confusing. See the conversation here: https://github.com/envoyproxy/envoy/issues/5166. I think if we had that it would work for your case?

**Comment by snowp** [comment]
Yeah that sounds like it would cover the encoding case. It definitely seems better than to give full access to the buffer. 

Thoughts how this could be accomplished for the decoding case where the intention is to hit `envoy.router`?  I had the idea to instantiate a `Router::ProdFilter` and call `encodeData` directly with the modified buffer, but haven't explored that at all. 

My motivation for for the decoding case is thinking ahead to how I can get `envoy.grpc_http1_bridge` or another filter to inject the gRPC frame into a downstream HTTP/1.1 request.

**Comment by mattklein123** [comment]
> One approach that might work would be to return something like ContinueBufferAllData from the encode/decodeHeaders call, which would make the HCM buffer the entire data before calling onData for the filter in question.

I can see how this would be an OK thing to offer, but I think I don't fully understand your use case. Am I understanding that you want to stream headers through all the filters but not the data? Why not just buffer everything then?

**Comment by snowp** [comment]
Yeah, thinking about this some more I think the easiest way to do this is to just buffer everything in a previous filter, using `envoy.buffer` or something similar. Me wanting to just buffer the data was just because that's what I've been doing with the current implementation, but now I realize that buffering the whole thing is the easier solution.

**Comment by mattklein123** [comment]
You can also just do full buffering in your filter. That's totally fine. Many other filters do this if they need to buffer. IMO I would not rely on another filter being installed if you need to buffer. Since HCM does the buffering, the request will only be buffered once.

**Comment by snowp** [comment]
My thinking was that by buffering in my own filter I'd not be able to insert a prefix into the buffered data due to only having const access, while by buffering in a previous filter I'd only ever see a single `onData` and could therefore modify the entire data. Maybe I'm missing something? 

I think technically the filter API allows a single filter to install several `StreamFilters`, so maybe that would be be an option if I'm relying on multiple filters?

**Comment by snowp** [comment]
That does seem like a nice solution as it essentially means that only a single filter can ever get write access to the buffer at a given time. 

 It also seems fairly easy to implement: just keep track of the latest filter that's seen data and ASSERT/throw if any other filter calls the non-const function.

**Comment by mattklein123** [comment]
Yeah I think that seems good to me and pretty easy to understand. Do you want to give it a go and see how it feels when you prototype it?
