### ISSUE TITLE
Structured version and feature reporting

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#5405]
Today, Envoy reports a human readable build version in `Node` messages when sending xDS requests, and also provides this in the `SeverInfo` message on the admin console. This is restrictive, since it does not provide detailed information on build details (e.g. was the build FIPS compliant?), version information needs to be parsed out of a string, it's not possible to know which extensions were included, etc.

A full treatment of the existing limitations and a proposal to evolve Envoy's feature/build/version proposal is available at:

https://docs.google.com/document/d/1RlYIzW-R1AtQSJlxAJlIpJEDnLM3a74pCIMrGwAqtNc/edit?usp=sharing

This is an early draft, looking to get feedback and evolve this to meet the community's needs.

CC @mattklein123 @PiotrSikora @mpuncel @snowp @mandarjog

**Comment by snowp** [comment]
@htuch Access to the doc is restricted, mind opening it up?

**Comment by htuch** [comment]
@snowp sorry, I did this via my Google corp account; can you just request access and I will grant? Sames goes for anyone else, happy to provide access once you request.

**Comment by ggreenway** [comment]
@htuch Please move the doc to a world-readable location.

**Comment by htuch** [comment]
@ggreenway I can't do this without losing comment history; my bad. I will take into account https://github.com/envoyproxy/envoy/pull/5454 in future design docs and will do a public document once a design emerges.

**Comment by htuch** [comment]
Closing out in favor of #6271
