### ISSUE TITLE
Envoy ported on windows platform

### ISSUE THREAD

**Issue by icaas** [envoyproxy/envoy#5407]
**Envoy compile problem on windows platform(Microsoft Windows [version 10.0.17134.407])**

*Title*: *Envoy ported on windows platform*

*Description*:
>I'm using the tag1.9.0 to do the windows platform porting.Everything is ok,but except the errors as follow:
ERROR: E:/usx-sge-service/envoy/source/exe/BUILD:52:1: C++ compilation of rule '//source/exe:envoy_main_entry_lib' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(161): CreateProcessWithExplicitHandles("E:\VSBuildTools\2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EH(...)): command is longer than CreateProcessW's limit (32768 characters)
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 712.438s, Critical Path: 67.71s
INFO: 602 processes: 602 local.
FAILED: Build did NOT complete successfully

the command line as follow:
>PS E:\envoy> bazel --output_base=E:\bazel-envoy-build build  --cxxopt=/wd4819 --cxxopt=/W2 --cxxopt=/wd4624 --cxxopt=/wd4244 --cxxopt=/wd4200 --cxxopt=/wd4267	--cxxopt=/wd4309 --cxxopt=/wd4838	//source/exe:envoy-static

Can anyone give me some advice?

**Comment by mattklein123** [comment]
cc @sesmith177. The Windows port is not yet fully upstreamed so I would imagine we are not yet ready to support building on master?

**Comment by icaas** [comment]
@sesmith177 Thanks for your response, I will try it according to your advise.
