### ISSUE TITLE
Building envoy on OS X

### ISSUE THREAD

**Issue by sterchelen** [envoyproxy/envoy#5410]
I'm trying to build envoy on OS X mojave `10.14.2 (18C54)` without success.

Here is the executed command :
`bazel build --incompatible_package_name_is_a_function=false --action_env=PATH=/usr/local/bin:/opt/local/bin:/usr/bin:/bin //source/exe:envoy-static`

Here is the result: 
```shell
INFO: Invocation ID: 9d5adc00-d36e-4957-b2c0-3f984d6cdc44
/private/var/tmp/_bazel_nicolassterchele/19b5387e66de067346e6f0614dfa8b23/external/envoy_deps/./repositories.sh: line 8: md5: command not found
External dependency cache directory /private/var/tmp/_bazel_nicolassterchele/19b5387e66de067346e6f0614dfa8b23/external/envoy_deps_cache_
./build_and_install_deps.sh: line 12: sysctl: command not found
make: the `-j' option requires a positive integral argument
```
I guess that there is specifics commands for linux that is not available on darwin... Am I right ?

**Comment by moderation** [comment]
What version of Bazel are your running? You should upgrade to 0.21.0 if you are on something earlier. There were some recent changes for MacOS using that build that work. I build with `bazel build -c opt //source/exe:envoy-static.stripped` and `.bazelrc` is:
```
import %workspace%/tools/bazel.rc
build --announce_rc
build --define google_grpc=disabled
build --define signal_trace=disabled
build --action_env=PATH=/bin:/opt/local/bin:/usr/bin:/usr/local/bin
```

**Comment by sterchelen** [comment]
In fact, getting last version of master resolved it. Thanks.
