### ISSUE TITLE
create easier way to get a core dump locally and in CI

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#5412]
I was trying to debug the hot restart test and get a core dump, and it took me an embarrassingly long time to figure out how to do it under bazel (the main issue was that my shell `ulimit` settings don't transfer to the test invocation I think because bazel is running the test and not my shell). It would be really nice if we could do two things:
1) Have a better way to get a core dump from a test run locally. Perhaps this is a run_under thing (per @htuch) that correctly sets up ulimit and also make sets the core dump output location to something known and then sets it back, and I guess also deals with sandboxing correctly (i.e., gives you very clear instructions on how to look at the core dump with the right symbols/binary).
2) Also enables this in CI somehow where we could get a core dump saved as an artifact with the binary that created it.

**Comment by lizan** [comment]
@mattklein123 re: 1) after #8488 you can run test binary outside bazel without anything special (just invoke `bazel-bin/test/<binary>`). only general core dump configuration are needed.

**Comment by mattklein123** [comment]
Cool SGTM will close. Thank you!
