### ISSUE TITLE
debug: use debug version of malloc for debugging

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5423]
*Description*:
>To make it easier to catch simple memory violations use the debug version of tcmalloc when compiling for debug. This will scribble over memory at allocation and when freeing, so that dereferencing pointers in uninitialized memory, or referencing freed memory will often segv.

This may be somewhat redundant with asan -- and definitely redundant with valgrind, but can help catch problems before CI, in development -- at least for those who compile with debugging.

**Comment by jmarantz** [comment]
Note: this is explicitly controllable from the bazel command-line now, but we'd still like to have this on by default for fastbuild and debug. However, limitations in bazel select are still vexing.

Some discussion on https://stackoverflow.com/questions/53947289/bazel-select-help-configuring-tcmalloc-debug

**Comment by jmarantz** [comment]
@htuch any advice or assistance here would be appreciated :)

**Comment by htuch** [comment]
@jmarantz chaining/nesting seems the way to go based on the SO thread. Another approach could be to do this via `.bazelrc`, at least in terms of providing sensible default that could then be overriden for each build mode.
