### ISSUE TITLE
Cluster stats appear only for the clusters not added via api, in the administration interface

### ISSUE THREAD

**Issue by vadimeisenbergibm** [envoyproxy/envoy#5444]
Istio uses 35381896313b5f5c5d899e3dfeeae16f05c4f972/1.9.0-dev/Clean/RELEASE. I see that /stats returns only stats for the cluster that was not added via api. /clusters returns stats for all the clusters. Is this by design?

**Comment by ramaraochavali** [comment]
It could be because Istio is filtering stats using `stats_matcher`config https://github.com/istio/istio/pull/10184. Please check the proxies bootstrap config - Can you see if stats matcher is enabled?

**Comment by vadimeisenbergibm** [comment]
Yes, stats matcher is enabled. Thanks @ramaraochavali, now it is clear, closing the issue.
