### ISSUE TITLE
main: print error messages to std::cerr from exception text

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5453]
Currently there are a few places in the code with the pattern:

```
  std::cerr << message;
  throw new EnvoyException(message);
```

These should all be changed to eliminate the stream-out command from the throw site, and instead stream out the exception text from main_common.cc when it's caught.

**Comment by rishabhkumar296** [comment]
Hi, I would like to take this up as my first issue. Does this task also involve removing `std::cerr` where it is used with `EnvoyException` to print the error messages?

**Comment by jmarantz** [comment]
I think we still want to log the errors when the exceptions are caught. But we don't need to log them when they are thrown.

**Comment by rishabhkumar296** [comment]
Hi, I was able to identify 5 instances where errors were logged along with throwing an exception after running `git grep 'std::cerr'`. PR created for the same.

**Comment by jmarantz** [comment]
When submitting attempt #2, can you audit all the exception catching done in Envoy to make sure we are logging the failures? Also I think we should probably be using ENVOY_LOG rather than std::cerr.

**Comment by mattklein123** [comment]
We should be printing the failure here IMO: https://github.com/envoyproxy/envoy/blob/master/source/exe/main.cc#L27. I'm not sure that we should use ENVOY_LOG() since some of the messages are general pre-start messages, and I don't think logging is gauranteed to be configured, but we can see how it goes. I think we can use your new random main testing setup for doing tests around this @jmarantz?

**Comment by rishabhkumar296** [comment]
@jmarantz I ran a quick `git grep 'catch ('` and there are instances where the failures are not logged once it is caught. I would prefer to fix it in a separate PR. I have a general query related to the parameter LEVEL in ENVOY_LOG - how to choose between 'warn' and 'critical' levels in ENVOY_LOG?

**Comment by jmarantz** [comment]
Right; std::cerr should be used for errors that are caught in main().  Those can be tested by adding new cases to test/integration/run_envoy_test.sh -- it should be pretty easy to add to that.

I count 48 instances of " try {" under source/... "*.cc", which probably should be audited. They don't all have to be echoed to stderr, e.g. in grpc_mux_impl.cc I see
```
  } catch (const EnvoyException& e) {
    for (auto watch : api_state_[type_url].watches_) {
      watch->callbacks_.onConfigUpdateFailed(&e);
    }
    ::google::rpc::Status* error_detail = api_state_[type_url].request_.mutable_error_detail();
    error_detail->set_code(Grpc::Status::GrpcStatus::Internal);
    error_detail->set_message(e.what());
  }
```
this is probably fine...the error is saved in error_detail which is likely sufficient.

If there are cases where the errors that were being streamed to cerr which are being caught somewhere other than main(), we could probably ENVOY_LOG them and test them in a unit test with EXPECT_LOG_CONTAINS.

RE  "warn" vs "critical" -- to me a warning means that the request will be processed despite having found a potential problem, whereas higher severities mean that the request cannot be processed. But @mattklein123 may have other semantics in mind.

RE "fix in a separate PR" -- we should make sure that whatever messages are removed from the throw-site are added to the catch-site in one PR.

**Comment by mattklein123** [comment]
We shouldn't do this for every catch, at least not right now. Right now I would only target the early startup prints to `std::cerr`, before the server runs. I think these are just the ones you already identified. The error can be printed in main in the top level catch block before run.
