### ISSUE TITLE
Docs: release docs repo links point to master

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#5458]
Links from RST docs using `:repo:` always point to the current `master` on github. This can lead to broken links for released version documentation. Example from the 1.8.0 docs:

https://www.envoyproxy.io/docs/envoy/v1.8.0/install/ref_configs#install-ref-configs has a link to https://github.com/envoyproxy/envoy/blob/master/configs/envoy_service_to_service.template.json, which doesn't exist anymore. The correct link in this case would be https://github.com/envoyproxy/envoy/blob/v1.8.0/configs/envoy_service_to_service_v2.template.yaml.

The config that generates these URLs is here: https://github.com/envoyproxy/envoy/blob/02659d411332e9f20d229f482931c15304ea17fd/docs/conf.py#L44.

**Comment by mattklein123** [comment]
I fixed this a while ago.
