### ISSUE TITLE
Add format fix for java proto options

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5477]
With #5369 the presence of some java options are required in all proto files, verified by `check_format.py`. Since these are fairly simple additions, we should add a format fix step to `check_format.py` that adds these in. 

The following snippet was used to add the options to existing files and might serve as inspiration for adding them this fix to `check_format.py`.

```
cd api
for f in $(find . -name "*.proto")
do
  sed -i -e '/^option\sjava_multiple_files\s=/d' $f
  sed -i -e "/^package\s/a option java_multiple_files = true;" $f
  sed -i -e '/^option\sjava_package\s=/d' $f
  cmd='grep -Po "^package \K.*(?=;$)" '"${f}"
  sed -i -e "/^package\s/a option java_package = \"io.envoyproxy.$(eval $cmd)\";" $f
done
```

**Comment by jmarantz** [comment]
@snowp do you want to take this?

**Comment by snowp** [comment]
Yeah i'll take this, should be easy enough

**Comment by jmarantz** [comment]
Cool; I can review. Can you also add a test in check_format_test_helper.py? Thanks :)
