### ISSUE TITLE
Header Aware Fault Injection

### ISSUE THREAD

**Issue by snakescott** [envoyproxy/envoy#5493]
*Title*: *Header Aware Fault Injection*

*Description*:
Add ability to do header matching in the fault filter. This would allow for example injecting faults only into (header identified) low priority traffic 

*Relevant Links*:
[Fault filter docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/fault_filter)

**Comment by mattklein123** [comment]
IIRC the fault filter allows for route specific configuration. I think you can just do a header match route, and then have a fault config for that route?

**Comment by snakescott** [comment]
actually i misread the docs, this is available already:

https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/config/filter/http/fault/v2/fault.proto#envoy-api-msg-config-filter-http-fault-v2-httpfault 

happy mistake!
