### ISSUE TITLE
decomp admin.h/admin.cc

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#5505]
The admin handler and tests are getting out of control. We should decomp these files into multiple independent files for different handlers, the filter, etc.

https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.h
https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc

**Comment by laphets** [comment]
Hello, I'd like to pick up this issue, but how can I get start with it?

**Comment by jmarantz** [comment]
Awesome! I'm not sure exactly where you are starting from; can you build envoy and run the tests? Can you start up a server and interactively explore the admin console?

Feel free to ping this bug or use the Slack channel to ask questions.

**Comment by laphets** [comment]
@jmarantz Sure, I have built envoy locally and see the admin console. I'm now trying to get familiar with some terminology like `NetworkFilter`, `ListenerFilter` with envoy.

**Comment by laphets** [comment]
@jmarantz Yes, I have already built it, and see the admin console! I'm now trying to get familiar with the abstract class of `AdminImpl` and `AdminFilter`

**Comment by mattklein123** [comment]
Yes I think this makes sense, though optimally I would end up with each handler in its own file, so not sure of the best class structure to make this happen. (If the handlers could end up mostly static that might be best).

**Comment by rulex123** [comment]
@laphets I could pick this up and help out, unless you are actively working on it?!

**Comment by jmarantz** [comment]
WDYT of also trying to move away from buffering the entire admin output in memory, and instead streaming it out via transfer-encoding:chunked ?

**Comment by jmarantz** [comment]
I think this is mostly done now. The chunking idea is captured better in https://github.com/envoyproxy/envoy/issues/16139 , so closing this.
