### ISSUE TITLE
Question: add rate limit header_values action with route added headers

### ISSUE THREAD

**Issue by medalliaerlich** [envoyproxy/envoy#5521]
*Title*: *Question: add rate limit header_values action with route added headers*

*Description*:
We have an Envoy setting in which request headers sometimes come in the request sometimes are set in a Lua HTTP filter and sometimes are set in the `request_headers_to_add` route property.

The problem here is that we want to use the header_value in a rate-limit action regardless of where the header was set, but when it's set in the route property, it seems that the actual value assignment is done in the Router filter, which, obviously runs after the rate-limiter, so we cannot use it.

Is there any way to enforce the header assignment by route that is accessible by the Rate Limiter service?

We currently work around this by using `generic_key` and static values which has the issue reported at https://github.com/envoyproxy/envoy/issues/5489

Thanks

**Comment by mattklein123** [comment]
Currently there is no way to do this. The reason headers are appended in the router is that is when the final routing decision is made (since filters might change the route). I can't think of a quick/easy way to fix your case so I'm marking design proposal.

One possibility might be to add the headers to add in route metadata and maybe always do it from Lua? I can't remember if Lua can see route metadata but I think it can.

**Comment by medalliaerlich** [comment]
Hi Matt, thanks for the response. Can you look the referenced issue as well? It'd help us workaround this.

Regarding your proposal, I'm not sure I understood your proposal, can you share an example?
But if the metadata is set after the RL is checked, I think the outcome will be the same, right?

On the other side, we cannot do it on Lua, as the header value, we want to add depends on the matched route. Am I right?

**Comment by mattklein123** [comment]
> Regarding your proposal, I'm not sure I understood your proposal, can you share an example?
But if the metadata is set after the RL is checked, I think the outcome will be the same, right? On the other side, we cannot do it on Lua, as the header value, we want to add depends on the matched route. Am I right?

Sorry I don't have time for a fully formed example/analysis. I think it should be possible to run the Lua filter prior to the RL filter and possibly do everything via route metadata, but I'm not sure.

**Comment by medalliaerlich** [comment]
And about the referenced issue (https://github.com/envoyproxy/envoy/issues/5489), could that be done?
