### ISSUE TITLE
Override http status code on 'upstream overflow'

### ISSUE THREAD

**Issue by sterchelen** [envoyproxy/envoy#5531]
*Title*: *Override http status code on 'upstream overflow'*

*Description*:
We want to override http status code when we are facing an `upstream overflow`. Actually it returns a 503. Is it possible to change that behavior ?

**Comment by mattklein123** [comment]
Not currently. We have a bunch of work planned around allowing user's to customize error responses which I think would cover this case. See https://github.com/envoyproxy/envoy/issues/1178 and related issues.

**Comment by sterchelen** [comment]
Thanks @mattklein123 ... I find a workaround using Lua script.

**Comment by vgomprakash** [comment]
@sterchelen , I am also looking for this feature to become available on Envoy. Can you share some sample Lua Scripts that you used for custom error messages, will be of great help

> Thanks @mattklein123 ... I find a workaround using Lua script.

**Comment by sterchelen** [comment]
I was able to override http status code. The body is not overwritable...
