### ISSUE TITLE
Support streaming HttpBody proto?

### ISSUE THREAD

**Issue by npuichigo** [envoyproxy/envoy#5540]
The support for handling google.api.HttpBody is cool, especially when I want to directly reply http response with audio `content_type`. I notice that streaming case is remained to be done, so may I ask you when will that be supported? It's really use for me in implementing speech synthesis because l can transfer large audio data to client by clipping them into audio clips with chunked audio/mp3 `content_type`.

**Comment by mattklein123** [comment]
@lizan

**Comment by lizan** [comment]
@npuichigo we don't have specific timeline to implement that. That is useful so if you're interested feel free to open a PR and I can help you with that.

**Comment by npuichigo** [comment]
@dio

**Comment by npuichigo** [comment]
any update?

**Comment by npuichigo** [comment]
I tried to add the logic of httpbody streaming in grpc-gateway repo, and maybe I can try to implement that in envoy. (https://github.com/grpc-ecosystem/grpc-gateway/pull/1088/files) Can you give me some advice?

**Comment by belyalov** [comment]
Is this issue about this to-be-done part?
https://github.com/envoyproxy/envoy/blob/404d73c73c08b8d470b3ead6395cbc9c531f199d/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L521-L525

**Comment by lizan** [comment]
@belyalov yes the part of code you're referring is right.

> As for workaround for "misbehaves" upstream - seems we can just ignore content-type for messages except first?

I think this is fine, as long as we clearly document it.

**Comment by npuichigo** [comment]
@belyalov Many thanks if you can help to fix this.😀

**Comment by npuichigo** [comment]
@lizan by the way, is this kind of transcoder can be directly used in ambassador or istio?
