### ISSUE TITLE
Make SSL impl (i.e. boringssl vs openssl) pluggable

### ISSUE THREAD

**Issue by bdecoste** [envoyproxy/envoy#5545]
Title: Make SSL impl (i.e. boringssl vs openssl) pluggable

Description:
Overall goal is to support the existing boringssl implementation as well as other ssl implmentations such as openssl. In order to support alternate ssl libraries, boringssl must be able to be compiled out with only bazel configuration changes. In order to support compiling out boringssl the following steps need to be accomplished:
1) decouple common/ssl from common/network (completed)
2) move boringssl dependencies to extensions. 
3) decouple extensions/transport_sockets/ssl from server

Parallel implementation of extensions/transport_sockets/openssl is underway. 

Relevant Links
1) https://github.com/envoyproxy/envoy/pull/5403
2) https://github.com/envoyproxy/envoy/pull/5543
3) WIP

**Comment by rojkov** [comment]
I'm interested in this issue and would like to help with it.

So far I have prepared a couple of patches to Envoy bringing in OpenSSL support (https://github.com/rojkov/envoy/tree/openssl).

Basically

* I moved the code of the TLS transport socket and tls_inspector to the `boringssl` subfolders of the respective extensions;
* copied OpenSSL implementations of the extensions from https://github.com/bdecoste/envoy-openssl to the `openssl` subfolders with minor changes;
* copied the boringssl compatibility layer from https://github.com/bdecoste/openssl-cbs and https://github.com/bdecoste/bssl_wrapper to `source/extensions/common/boringssl_compat` (with minor changes);
* added a bazel option to build Envoy either with boringssl (default) or openssl.

So, in this experimental branch the extensions `//source/extensions/transport_sockets/tls` and `//source/extensions/filters/listener/tls_inspector` are just very short headers conditionally including either boringssl or openssl "plugins". It causes huge code duplicity though.

Currently all the unit tests pass when Envoy is built against boringssl. I started to fix the tests for the openssl builds (by now fixed the tls_inspector tests).

@bdecoste @lizan @PiotrSikora  Could you please add some comments on what is the current plan? Does my work make any sense? How can I help if it doesn't?

cc @ipuustin @mythi

**Comment by PiotrSikora** [comment]
The plan of record is for Envoy to officially support only BoringSSL, and OpenSSL being available as a third-party extension (which is what @bdecoste is working on). This allows supporting features that are implementation specific, e.g. BoringSSL's `CRYPTO_BUFFERS`, `SSL_PRIVATE_KEY_METHOD`, OpenSSL's engines, and not tying TLS transport to the common interfaces.

**Comment by rojkov** [comment]
Ok, somehow I missed the point about availability of OpenSSL support as a pluggable third-party extension. I presume the easiest way to do that is to follow [the custom envoy filter example](https://github.com/envoyproxy/envoy-filter-example) and to have a similar repository importing Envoy as a git submodule. WDYT?
