### ISSUE TITLE
content length header is auto-inserted for empty bodies

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#5554]
*Title*: after a regular HTTP filter removes content-length header in `encodeHeaders`, it is still present in the response

*Description*:
This only happens for requests with an empty body.
If there is a body, then removing content-length header from a filter works as expected.

Discovered here https://github.com/istio/istio/issues/10783 for envoy 2a2ad48a7d4b57512bc10a9593e852fe950b1c8d

**Comment by kyessenov** [comment]
Several filters set content length explicitly (gzip, I think). I'm not sure where content-length is auto-set to 0 for empty bodies, but I can imagine this can cause a conflict. It's not a critical issue, since the difference between an empty body with content length 0 and just an empty body is minor.

**Comment by alyssawilk** [comment]
grepping through the code base I see insertContentLength in a few places, and I'm curious which one you're hitting.
we insertContentLength when we sendLocalReply (generally Envoy sending error messages,which makes sense as we know the body size)
we insertContentLength(0) on the upgrade path, for a bunch of complicated reasons to do with how Upgrades work
then finally there's 3 filters which insertContentLength: json_transcoder_filter, lua_filter and http1_bridge_filter - I assume you're hitting one of these?

**Comment by alyssawilk** [comment]
oh no, my bad, I missed the most important one since it was using encodeHeader directly, which is the HTTP/1 codec will tag 0 length bodies on the way out iff it has an end stream.  If this is what you're hitting this is definitely WAI as it's done only if we've already gotten an end stream when we're serializing the headers to the wire (all filters have had a chance to append body at that point)

**Comment by kyessenov** [comment]
@alyssawilk : @PiotrSikora found the exact source line which I assume is the same one you are seeing. I think this is a non-issue, as it only affects filters which want to erase content-length for empty response bodies, and that's the kind of behavior that does not need to be supported even if it is allowed by filter APIs.

**Comment by alyssawilk** [comment]
Cool.  I'll close this out for now then - feel free to repoen if you determine it's problematic!

**Comment by jschlichtholz** [comment]
I would request to reopen this issue since it causes problems for us and, more importantly, does not comply with RFC 7230:

> A server MUST NOT send a Content-Length header field in any response a status code of 1xx (Informational) or 204 (No Content).

https://tools.ietf.org/html/rfc7230#section-3.3.2

**Comment by alyssawilk** [comment]
I'd be more than happy to fix it for response codes where it is not legal.

Is it causing problems in general or just for those? Changing Envoy to not add it for legitimate cases would likely cause problems for someone else, so would be a fairly high risk change.

**Comment by jschlichtholz** [comment]
We just saw problems with responses that have a 204 response code. Everything else I would consider a bug on our side.
