### ISSUE TITLE
IPs not set if version never changes

### ISSUE THREAD

**Issue by billybanfield** [envoyproxy/envoy#5555]
*Title*: IPs not set if version never changes 

*Description*:
We are using a control-plane based on the go-control-plane project. We are using ADS to serve resources to envoy over gRPC. When the clusters/endpoints do not change from the initial version, Envoy does not correctly associate the IPs it receives from the control-plane with the clusters. Envoy receives the IPs and acknowledges them in the logs, but the IPs do not appear in the /clusters endpoint and attempts to route to these clusters fail with 503. Forcing a new version in the control-plane triggers envoy to correctly associate the IPs it receives with the cluster. 

*version* 5d25f466c3410c0dfa735d7d4358beb76b2da507/1.8.0/Clean/RELEASE
This has been confirmed to also occur with the docker image for v1.9.0 but does not occur with the image for v1.7.0

*Repro steps*:
* Start dummy service
* Start control plane
* Start Envoy
* Try to route to dummy service -> 503
* add new service, verify version changed in log
* Try to route to dummy service -> 200

logs and output attached (ips redacted) 
[clusters.txt](https://github.com/envoyproxy/envoy/files/2742364/clusters.txt)
[clusters_after.txt](https://github.com/envoyproxy/envoy/files/2742376/clusters_after.txt)
[envoy-config.txt](https://github.com/envoyproxy/envoy/files/2742366/envoy-config.txt)
[envoy_log.txt](https://github.com/envoyproxy/envoy/files/2742367/envoy_log.txt)

**Comment by mattklein123** [comment]
cc @snowp any thoughts on this one?

**Comment by snowp** [comment]
I've seen similar things happen before when the EDS update was dropped due to XDS ordering, but not sure if this is the same thing. 

@billybanfield could you also provide the output from /stats after the initial update?

**Comment by snowp** [comment]
Tried reproducing this with 1.8 against the java control plane (just because I have that synced down) and couldn't reproduce when it served EDS and CDS with the same version on startup.

One thing I noticed is this stat:
```
cluster_manager.active_clusters: 52
```

Do you actually have 52 clusters? If so, are you only seeing this with that many clusters or is this reproducible with a small number of clusters as well?

**Comment by billybanfield** [comment]
This does reproduce for me with the go-control-plane with only 1 cluster. Was easier to setup in a larger environment at the time. Here is output from a run with just 1 cluster.

IPs redacted. 
[clusters.txt](https://github.com/envoyproxy/envoy/files/2760851/clusters.txt)
[clusters_after.txt](https://github.com/envoyproxy/envoy/files/2760852/clusters_after.txt)
[logs.txt](https://github.com/envoyproxy/envoy/files/2760853/logs.txt)
[stats.txt](https://github.com/envoyproxy/envoy/files/2760854/stats.txt)
[stats_after.txt](https://github.com/envoyproxy/envoy/files/2760855/stats_after.txt)

**Comment by mattklein123** [comment]
cc @junr03 who might have some ideas re: go control plane if that is somehow related.

**Comment by mattklein123** [comment]
@billybanfield is it possible for you to come up with a self-contained repro potentially using docker compose?

**Comment by junr03** [comment]
@billybanfield I will take at the data you have posted, and see if I have ideas. Matt's proposal would be super helpful if you can create it.

**Comment by billybanfield** [comment]
@junr03 @mattklein123 apologies, haven't had time to get to this, may be able to in the next week or so

**Comment by billybanfield** [comment]
@junr03 @mattklein123 repro here: https://github.com/billybanfield/envoy-5555-repro

**Comment by billybanfield** [comment]
hey @junr03 @mattklein123 I believe I've confirmed the existence of some issue here, seems we can remove the stale bot here?

**Comment by mattklein123** [comment]
marking help wanted. cc @snowp in case he has time to take a quick look.

**Comment by snowp** [comment]
Tracked this down to an issue where updating an overprovisioning factor while prevent host updates from being made to a host set - this means that the first update which sets the OP factor does not update the hosts, but the subsequent call does as the OP factor is the same as the initial update.

Will put up a fix today
