### ISSUE TITLE
test: infrastucture should make it easier to generate valid configs

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5556]
Currently when you write a test that requires a valid Envoy configuration, you need to make two variants of it and switch on whether you're running in ipv6 or ipv4 mode.

It should be super-easy to write a test that requires configuration without thinking at all about ip-mode. Both in bash and c++.

**Comment by alyssawilk** [comment]
Josh: this is just a problem for bash yes?  I thought we already had this for C++ but if you're not happy with  how the config utils work I'd like to understand more!

**Comment by jmarantz** [comment]
I think the patterns are stronger in Bash but they could be simpler in C++ too. For example tests that are not specifically aimed at config-files should not need to have a config-file in testdata/ or similar. They should be able to just instantiate things and override any options that are of interest.

Most tests are agnostic to ipvX and shouldn't need to parameterize based on it.

But I agree that the patterns in C++ are established enough that this isn't a major productivity drain; just saying it could be cleaned up a little.
