### ISSUE TITLE
config: convert example, documents and tests to typed_config (Any)

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#5558]
Follow up of #4475.

**Comment by lizan** [comment]
Will working on this when I have time, feel free to take.

**Comment by mattklein123** [comment]
@yanavlasov is this still on your radar? cc @derekargueta

**Comment by yanavlasov** [comment]
Yes, working on it this week.

**Comment by mattklein123** [comment]
Awesome thanks

**Comment by mattklein123** [comment]
I think this is done.
