### ISSUE TITLE
How to been notified cluster warming up complete when health checker enabled?

### ISSUE THREAD

**Issue by tony-shi** [envoyproxy/envoy#5560]
**Issue Template**

*Title*: *Warming cluster lost traffic with health checker enabled*

*Description*:
As the xds protocol overview has mentioned, the correct order of xds protocol should be CDS、EDS、RDS when we need to add a new cluster for envoy to router to.
However, when should the xds manager server to make sure that a cluster has been fully warmed up then notify our downstream users they can safety start?
When EDS has been acked by the envoy, the cluster may hasn't been really warmed up if we configured a Health checker. 
I have noticed that, cluster_manager.h has provide a addThreadLocalClusterUpdateCallbacks(ClusterUpdateCallbacks& callbacks) function to let user register callbacks for cluster lifecycle events. When this ClusterUpdateCallbacks.onClusterAddOrUpdate(ThreadLocalCluster& cluster) been triggered, it means the cluster has really been warmed up in the thread registered.
In my opinion, whenever this callback has been triggered, the cluster has already been warmed up almost completely(may be some thread hasn't begin to run the routine provided in  createOrUpdateThreadLocalCluster() logic, but it has been added to their dispatcher event list and will be run before the future incoming request processing), so we can let the downstream to send some request which will be used the new cluster without worry about traffic lost.
The problem is that, how can the manage server or the downstream been notified in time when the new  cluster warmed up? The eds ack will not work,since the health checker may hasn't been finished.
In our prod environment, drop traffic is deadly forbidden.
I haven't find any build in mechanism to ensure this. May be I misunderstand the xds protocol or cluster warming up timeline?

**Comment by mattklein123** [comment]
This is related to https://github.com/envoyproxy/envoy/issues/5174. @tony-shi can you potentially discuss in the context of that issue and close this as a duplicate?

**Comment by tony-shi** [comment]
Sure! Sorry for bother~
