### ISSUE TITLE
Produce and host JSON schema

### ISSUE THREAD

**Issue by itaysk** [envoyproxy/envoy#5564]
I am working on some tooling that involves Envoy configuration, and need to rely on JSON schema for validation. 
I currently produce usable schema from the source at: https://github.com/envoyproxy/envoy/blob/master/source/common/json/config_schemas.cc but it would be nice to have a ready to use JSON document. 
Once we had that we should host outside it the git repo so tools can just reference it under a predictable URL.

**Comment by mattklein123** [comment]
@itaysk the JSON scheme is only used for Envoy's v1 config, which is going away. I would recommend not building any new tooling that targets it. Please use the new v2 config which is based on proto/JSON/YAML.

**Comment by itaysk** [comment]
thanks for the pointing me in the right direction.
I take it that there aren't any plans to incorporate this (maybe as part of CI) and host the resulting schemas (example: http://schemastore.org/json/) ?

**Comment by lizan** [comment]
There are tools to generate JSON schema from proto IDL so you might be able to use that, and additionally PGV rules.

**Comment by itaysk** [comment]
OK thanks for the prompt replies!

**Comment by long1eu** [comment]
@itayd did you managed to get the json schema?
