### ISSUE TITLE
grpc: add status access log filter

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#5567]
grpc: add status access log filter

*Description*:
Add an access log filter that works based on grpc status codes, similar to the [http status code filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto#envoy-api-msg-config-filter-accesslog-v2-statuscodefilter)

**Comment by crockeo** [comment]
I'm interested in taking on this issue, but I'm completely new to the project, so some direction would be appreciated. From a preliminary search I found:

1. [List of gRPC status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)
2. [StatusCodeFilter definition](https://github.com/envoyproxy/envoy/blob/master/source/common/access_log/access_log_impl.h#L47)

It looks like I would have to define a new `GRPCStatusCodeFilter` proto, build out the class in `access_log_impl.h` / `access_log_impl.cc`, hook it into `FilterFactory::fromProto`, and do the non-functionality related changes, like tests and config validation. Is there anything else I should look out for?

**Comment by mattklein123** [comment]
@crockeo thanks for working on this. This sounds reasonable to me. Yeah I think human readable names for the codes would be really nice!

**Comment by crockeo** [comment]
Is there a canonical way to use CI builds to target individual tests? I keep running into compiler differences between Clang and GCC, but full CI builds + tests take prohibitively long on my laptop (>2hrs).
