### ISSUE TITLE
Stronger typing in load_balancer_impl

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5570]
With the work on degraded lb (https://github.com/envoyproxy/envoy/pull/5367) the code now has a lot of different `std::vector<uint32_t>` types: degraded/healthy load, degraded/healthy availability. The lack of typing here makes working on this code somewhat painful, as passing the wrong type leads to subtle errors that take a while to debug. 

It would be nice to improve the typing here to make the compiler do the work to enforce that the right variables are used. 

One option is to use phantom types for this, eg:

```
template<class T, class... Ts>
struct Phantom : T {
	template<class... S>
	explicit Phantom(S&&... v) : T(std::forward<S>(v)...) {}
};

struct Load {};
typedef Phantom<std::vector<uint32_t>, Load> PriorityLoad;

struct Health {};
struct Degraded {};

typedef Phantom<PriorityLoad, Health> HealthPriorityLoad;
typedef Phantom<PriorityLoad, Degraded> DegradedPriorityLoad;

void priority(PriorityLoad pl) {}
void healthPriority(HealthPriorityLoad hl) {}

int main() {
	HealthPriorityLoad hpl{1, 2};
	priority(hpl); // works because HealthPriorityLoad : PriorityLoad
	healthPriority(hpl);
	PriorityLoad pl{3,4};
	priority(pl);
	healthPriority(hpl); // doesn't work since PriorityLoad isn't a HealthPriorityLoad
	return 0;
}
```
(https://ideone.com/h7E7MO)

this would allow using `HealthPriorityLoad` for more generic types that use `PriorityLoad` for reusable functions while still being able to differentiate it from `DegradedPriorityLoad` for more specific functions. 

Using the wrong type yields an error like:

```
prog.cpp:26:8: error: could not convert ‘pl’ from ‘PriorityLoad {aka Phantom<std::vector<unsigned int>, Load>}’ to ‘HealthPriorityLoad {aka Phantom<Phantom<std::vector<unsigned int>, Load>, Health>}’
  bar(pl);

``` 
using gcc.

Open for other suggestions as well, just figured I'd start out with a concrete proposal.

**Comment by mattklein123** [comment]
@snowp big +1 from me. Anything we can do to make this code easier to understand and less error prone to edit would be a huge plus. This sounds good to me. Something also to think about is whether we can reduce code duplication and huge param lists. I've commented before, but I feel like now we have a lot of duplication of similar logic which makes it even harder to understand and follow.
