### ISSUE TITLE
How can I dynamically change the host HTTP header?

### ISSUE THREAD

**Issue by klarose** [envoyproxy/envoy#5575]
*Title*: How can I dynamically change the host HTTP header?

*Description*:

I want to dynamically overwrite my upstream host without necessarily understanding the exact upstream host ahead of time. For example, imagine that the request gets to my envoy with my hostname as the host, but then i want to forward it somewhere algorithmically determined. I can't overwrite the host/authority header in the lua filter or using something like the authz filters because it's an inline header. I tried with ext_authz, but it just ignores or appends the header to the existing one.

Any suggestions? I could write an http filter that takes one header then maps it onto headers.Host() explicity explicitly, I guess, but if somebody has already solved this, I'd rather not write an extension.

Note: eventually I'll likely use incremental xDS for this in the long term, but I'll need to build a control plane for that, so as a solution it's not short term. I'm looking for something I can do quickly.

**Comment by mattklein123** [comment]
You should be able to overwrite it using Lua. You may have to remove then add, I can't remember.
