### ISSUE TITLE
Upgrade gabime/spdlog dependency to 1.3.0

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#5585]
Title: Upgrade gabime/spdlog dependencies

Description:
spdlog has been recently been updated to `1.3.0` and has undergone significant changes. Release notes are [here](https://github.com/gabime/spdlog/releases/tag/v1.3.0).

When attempting to upgrade to `1.3.0` by modifying `bazel\repository_locations.bzl` 
```python
    com_github_gabime_spdlog = dict(
        sha256 = "78786c641ca278388107e30f1f0fa0307e7e98e1c5279c3d29f71a143f9176b6",
        strip_prefix = "spdlog-1.3.0",
        urls = ["https://github.com/gabime/spdlog/archive/v1.3.0.tar.gz"],
    ),
```
Envoy fails to build with the following error.
```
In file included from bazel-out/k8-opt/bin/source/common/common/_virtual_includes/assert_lib/common/common/assert.h:5:
bazel-out/k8-opt/bin/source/common/common/_virtual_includes/minimal_logger_lib/common/common/logger.h:80:59: error: no member named 'level_names' in namespace 'spdlog::level'
  std::string levelString() const { return spdlog::level::level_names[logger_->level()]; }
                                           ~~~~~~~~~~~~~~~^
1 error generated.
```
I believe this error comes from this commit - https://github.com/gabime/spdlog/commit/0ce670e45aa2791d299ee1eaa6ca19ef0a2006b3

/cc @zuercher who fixed fmt and spdlog on prior updates.

**Comment by rishabhkumar296** [comment]
Hi, I would like to work on this issue.
