### ISSUE TITLE
stale endpoint with old ip address still exists after changing endpoint ip address

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#5614]
We are using v1.7 currently. I found the issue where if i change ip address of the endpoint and then do localhost:8001/clusters it shows old ip for the endpoint as well. I do see log message from eds saying "membership update for TLS cluster ep1". Restarting envoy resolved the issue. 

ep1::10.0.0.1:8080    // old ip 
ep1::10.0.0.2:8080   // new ip

**Comment by mattklein123** [comment]
Please try on master and report back. Thank you!
