### ISSUE TITLE
Performance improvement in data-path - proposal

### ISSUE THREAD

**Issue by zachidan** [envoyproxy/envoy#5620]
*Background:*
In my investigation, I have found that there is a significant impact of a user-space proxy (i.e., envoy) in terms of performance degradation. That is, if we could move the data from the client egress socket directly to the envoy egress socket w/o sending it through the envoy user-space proxy, we can get a significant performance improvement (e.g., tens of percents in a synthetic benchmark) for buffers of 16KB and up.

In many use-cases, envoy needs ONLY the meta-data of the message and does NOT need to read the data itself. so, we actually do not need to pass the data through envoy proxy and we can just forward it in the kernel from the client socket directly to the envoy egress socket.

*Proposal:*
I would like to suggest to add a simple logic into envoy which forwards the data (if it is large enough - 16K and up) in the kernel from the client socket to the envoy egress socket by using the *splice* syscall.

Is this interesting ? If yes, just let me know and I'll prepare a PR.

**Comment by mattklein123** [comment]
@zachidan this has come up before, but the architecture of Envoy (decoupling of upstream and downstream) will make it very difficult to actually do this without a large number of changes. If you are interested in trying to make this happen, I would suggest producing a small design document on how you would go about the change and we can all evaluate?

**Comment by zyfjeff** [comment]
@zachidan I am very interested in this, I have also researched before, but I found that envoy will modify the original buffer anyway, so there is no way directly do splice directly.

**Comment by zachidan** [comment]
@mattklein123 I think that for **tcp_proxy** listener it is straightforward because there is 1:1 mapping between the downstream socket and the upstream socket. I agree that for **http** listener it is a bit more complicated but still feasible because we just need to _splice_ the data of each message/frame.

However, there is some constraint when a **TLS** is used:

- TLS termination: we couldn't use _splice_ because we need to let envoy to decrypt the data.
- TLS origination: in order to use _splice_ with TLS origination, envoy needs to switch to kernel TLS (kTLS).

In the bottom line: _splice_ can be used without TLS or with TLS origination + kTLS.

Any thoughts ?

**Comment by mattklein123** [comment]
The complications go beyond TLS even for basic tcp_proxy due to filters. There can be filters that run before tcp_proxy that can buffer, etc. There really is no easy way to do this without quite a bit of special casing. I think if you start to actually do the change you will see the problems. Feel free to put together a design doc on the proposed changes if you like. It's possible, but it will require a lot of changes, special casing, and complexity.
