### ISSUE TITLE
jwt_authn filter token expansion proposal

### ISSUE THREAD

**Issue by ricochet** [envoyproxy/envoy#5632]
*Title*: *jwt_authn filter support of applying token expansion to custom headers*

*Description*:
>The OAuth token validated by the jwt_authn filter may contain information that needs to be passed to the sidecar's service. If the key-values can be expanded  to the config context, then features such as custom headers could apply the value of a given key.

*Example:* The JWT token may contain the following keys

```
"zid": "acme",
"client_id": "App",
"cid": "App",
"azp": "App",
"grant_type": "password",
"user_id": "5372de47-43b5-4e35-b46e-c360f7b1b1a3",
"origin": "uaa",
"user_name": "userId",
"email": "uderId@acme.com",
"auth_time": 1505828048,
"rev_sig": "31cde6d",
"iat": 1505828048,
"exp": 1821188048,
"iss": "http://localhost:8080/uaa/oauth/token",
```

A consumer may have the following config and expect the value of of "zid" to apply to their custom request header such as:
```
request_headers_to_add:
    - header:
        key: "x-tenant-id"
        value: "%zid%"
```

*Use case:* Multitenancy

The oauth token may include the tenant ID. A primary benefit of using a sidecar proxy for authentication is to be able to  remove related libraries within the service.  For that to work, we need to surface the tenantId in a header so that operations within the service can be tenant specific. 

The key that surfaces the tenantID may not be consistent across cloud meshes. In our case the key is "zid", aka the zone id. Some systems use the key "tenant". The headers that are used to express the tenant zone are also inconsistent.

*Relevant Links*:
>Cases where tenantID is passed as a header: 

* X-Tenant-ID
    * https://github.com/zalando/restful-api-guidelines/pull/325
    * https://bugs.launchpad.net/glance/+bug/1308413
    * Atlassian landlord plugin: https://ecosystem.atlassian.net/browse/LAND-12
* X-TenantID
    * https://developer.ibm.com/answers/questions/463379/invalid-tenant-id-null-cannot-be-empty/
    * http://fizzylogic.nl/2016/01/24/make-your-spring-boot-application-multi-tenant-aware-in-2-steps/
* X-ID-TENANT-NAME
    * https://docs.oracle.com/en/cloud/paas/app-container-cloud/apcsr/Authentication.html
* X-Identity-Zone-Id
    * http://docs.cloudfoundry.org/api/uaa/version/4.9.0/#creating-an-identity-zone

**Comment by ricochet** [comment]
I'm up for taking this on if this is a good idea. Thoughts? @qiwzhang @lizan

**Comment by qiwzhang** [comment]
Sound good to me.  Please go ahead. Thanks.

**Comment by lizan** [comment]
@ricochet So I think the idea is to extract JWT token into metadata and let router to add them to request via formatting it like `%DYNAMIC_METADATA(NAMESPACE:KEY*):Z%`? That sounds good to me.

**Comment by zachmarshall** [comment]
I am working on this with @ricochet. I've found that a lot of what we need is already present, but please correct any misunderstanding I might have.

It seems the jwt filter already places the parsed oauth token into dynamic metadata: https://github.com/envoyproxy/envoy/blob/851859b7a214bad1c66043e49dff2f04b417608b/source/extensions/filters/http/jwt_authn/filter.cc#L46

So it's just a matter of getting it out of there and into a header. And it seems one could generally do that with a lua filter, right? I think this generally should be possible and I've written up the code to do so. However, I'm using envoy via Istio and unfortunately Istio always places my lua filter before the jwt filter so I can't really validate this.

**Comment by qiwzhang** [comment]
@lizan mentioned that router supports adding header from dynamic metadata, with format like `%DYNAMIC_METADATA(NAMESPACE:KEY*):Z%`. 
If its KEY can be a path, like jwt_issuer.your_payload_field.sub_field.  it should work since payload is stored as Struct in dynamic metadata.
