### ISSUE TITLE
Move tests in http[2]_[upstream]integration into a protocol_integration_test.cc

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#5638]
I think it'd be nice to have one location for tests that are run for the HTTP/H2 rather than adding the definition to integration_test and adding TEST_Ps to 3 different files.  It can be nice to see that you failed test only in the h2 test file, but I think with the pretty print naming protocol integration test has it's good enough even if we move, and it'd make writing HTTP1/H2 tests that much easier.

Throwing this to the community before I go embark on moving a bunch of stuff around.

**Comment by mattklein123** [comment]
Sounds great to me!
