### ISSUE TITLE
Envoy sending http2 GOAWAY for large responses

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#5643]
We're seeing an issue where large HTTP/2 responses will intermittently be cut off during encoding.

Envoy sends a GOAWAY to the upstream, ending the stream early. This results in some downstream HTTP/1.1 clients receiving a partial response, causing deserialization errors.

This seems to be happening for large (6MB+) responses, for example:

 ```
2019-01-18_00:52:59.59735 'content-length', '6404479'
```

The flow we're seeing this in is:

Ruby HTTP/1.1 client -> egress envoy -> ingress envoy -> jetty HTTP/2 server

The upstream cluster is configured to always use HTTP/2.

http2 trace logs for the ingress Envoy:
https://gist.github.com/snowp/46d00bed8e1ee7d368b96c091d4a025d

On the Java side we're seeing the GOWAY with `frame_size_error` as the returned error. 

Unsure whether this is an Envoy issue or a misbehaving upstream. It sounds like it's an issue with max frame/response size, but I'm not aware on any such limits that would apply here.

This is running a relatively old (Nov 29th) Envoy version: dd2b1d457e97cfd266673489fb8dd7c948bd0d7b

We'll give this a go on a more recent version, but wanted to raise this for now to see if anyone as any ideas what might be going on.

Non-zero stats for the upstream cluster: 
```
cluster.local_app_http.external.upstream_rq_200: 432
cluster.local_app_http.external.upstream_rq_2xx: 432
cluster.local_app_http.external.upstream_rq_completed: 432
cluster.local_app_http.http2.tx_reset: 15
cluster.local_app_http.membership_change: 1
cluster.local_app_http.membership_healthy: 1
cluster.local_app_http.membership_total: 1
cluster.local_app_http.upstream_cx_active: 1
cluster.local_app_http.upstream_cx_destroy_local_with_active_rq: 7
cluster.local_app_http.upstream_cx_destroy_with_active_rq: 7
cluster.local_app_http.upstream_cx_http2_total: 58
cluster.local_app_http.upstream_cx_protocol_error: 7
cluster.local_app_http.upstream_cx_rx_bytes_buffered: 9
cluster.local_app_http.upstream_cx_rx_bytes_total: 120741315
cluster.local_app_http.upstream_cx_total: 58
cluster.local_app_http.upstream_flow_control_paused_reading_total: 14
cluster.local_app_http.upstream_flow_control_resumed_reading_total: 13
cluster.local_app_http.upstream_rq_200: 432
cluster.local_app_http.upstream_rq_2xx: 432
cluster.local_app_http.upstream_rq_completed: 432
cluster.local_app_http.upstream_rq_pending_failure_eject: 62
cluster.local_app_http.upstream_rq_pending_total: 63
cluster.local_app_http.upstream_rq_total: 2407
cluster.local_app_http.upstream_rq_tx_reset: 15
cluster.local_app_http.external.upstream_rq_time: P0(6,6) P25(6.025,8.01076) P50(6.05,9.04776) P75(6.075,14.4643) P90(6.09,51) P95(6.095,232.5) P99(6.099,1590) P99.5(6.0995,6595) P99.9(6.0999,9359) P100(6.1,9400)
cluster.local_app_http.upstream_cx_connect_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
cluster.local_app_http.upstream_cx_length_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,31300) P95(nan,121500) P99(nan,294300) P99.5(nan,297150) P99.9(nan,299430) P100(nan,300000)
cluster.local_app_http.upstream_rq_time: P0(6,6) P25(6.025,8.01076) P50(6.05,9.04776) P75(6.075,14.4643) P90(6.09,51) P95(6.095,232.5) P99(6.099,1590) P99.5(6.0995,6595) P99.9(6.0999,9359) P100(6.1,9400)
```

These errors seem to show up as `cx_protocol_error`.

**Comment by mattklein123** [comment]
Are you using the newest Jetty version possible? It would be nice to rule out any bug there that has already been fixed. Does Jetty use Netty for h2?

**Comment by snowp** [comment]
Yeah we're using the latest released version of Jetty (9.4.14.v20181114). Jetty does not use Netty, it's got its own implementation: https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-http2

We haven't seen any issues with H/2 using Netty (through grpc-java), but not sure if we've been seeing
the same kind of response sizes there.

**Comment by mattklein123** [comment]
I would wager this is a Jetty bug, but obviously hard to tell without obtaining and sorting through a full protocol back and forth.

**Comment by snowp** [comment]
Yeah that's what I suspect as well. Having issues reproducing this while tapping the data with `socat`, so debugging this is proving rather difficult. We might just end up switching back to http/1.

I take it there's not much that can be done to improve how Envoy reports this error?

**Comment by harshavardhana** [comment]
We are seeing something similar, let us know what kind of information that is needed to address here?
