### ISSUE TITLE
Confirm / document DynamoDB filter

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#5655]
*Title*: Confirm that the DynamoDB still works in the v2 only Envoy and if so document it

*Description*: The DynamoDB filter does not have v2 API documentation and is missing `*.proto` files.

*Relevant Links*:
On the documentation [page](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/dynamodb_filter)  the link [v2 API reference](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpfilter-name) which does not include detail for DynamoDB.

Unlike other http filters at https://github.com/envoyproxy/envoy/tree/master/api/envoy/config/filter/http there is no `*.proto` file for DynamoDB

*Other*: Original Slack [question](https://envoyproxy.slack.com/archives/C78M4KW76/p1547771137386300).

**Comment by mattklein123** [comment]
IIRC it's because there is no configuration for the filter. Yes it works with v2.
