### ISSUE TITLE
audit out of memory error handling for libraries

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#567]
In general we do not handle OOM errors in Envoy and assume that the process should crash. There is a valid concern that libraries might return OOM errors when they are not actually out of memory. We should take a look at cases where this might happen and potentially add more paranoia checking.

cc @htuch

**Comment by htuch** [comment]
Also, I think that where we do have OOM at the libc level, we should at least throw an exception or crash. It seems we risk entering dangerous territory if we don't. E.g. we reach a near OOM kill scenario, silently ignore an error and leak a buffer with uninitialized data.

**Comment by mattklein123** [comment]
For C++ allocations we should throw an exception and will crash.

For C allocations, we obviously won't. Note that from previous experience, libevent seems like it handles OOM conditions, but there are missing cases and it will end up crashing. It's possible this has been fixed in 2.1.

**Comment by mattklein123** [comment]
I haven't looked, but optimally we could install some kind of OOM handler in tcmalloc that would handle both C++ and C allocations and then we could definitely crash in all cases.
