### ISSUE TITLE
runtime feature guarding

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#5693]
Per discussion over on #5441 it'd be good to have a globally accessible framework guarding high risk features, as well as tooling to handle the lifetime of migration from old code to new, which matches what we do for config guarding including warning/hard-fail (see #5559) and scripts to advance from warning to defaut-off to filing clean-up issues.

Plan A is to use Envoy's existing run-time, but make it a singleton to make it easy for any code in Envoy to check in on the status of the relevant features. 

Eventually it'd be nice if flags could also pulled over a discovery service, as well as set via command line for those of us who are used to flag based features

This issue covers both the code changes and tooling changes as one without the other isn't particularly usable.  

I'm going to stick this on the agenda for next week's community meeting, but I'd appreciate folks in the community and @envoyproxy/maintainers weighing in early and often with thoughts of how to make this useful and easy to use.

**Comment by mattklein123** [comment]
@alyssawilk should we consider this issue done for the initial version? Or is there more work to do that we want to track here?

**Comment by alyssawilk** [comment]
There's 1-2 TODOs left -  handling deprecation as we do for deprecated protos, and adding a sweep of our code + auto-fatal-ification to the release scripts to make it "safe" to remove old code paths.

**Comment by mattklein123** [comment]
@alyssawilk sg. Should we move to 1.11.0 milestone and finish it up there?

**Comment by alyssawilk** [comment]
I don't know that anyone pays attention to milestones but I guess the feature flips are done here, and deprecation will be done in the next release when we might have features to deprecate :-P.  Filed a new issue and I'll close this off
