### ISSUE TITLE
Support for redis cluster protocol

### ISSUE THREAD

**Issue by HenryYYang** [envoyproxy/envoy#5697]
**Support for redis cluster protocol**

*Description*:
The redis cluster protocol has been implemented in Redis 3.0 or greater.  It is a distributed implementation with a well understood trade off between availability, scalability and best effort consistency.

Supporting this protocol in envoy will provide similar benefit as the original redis proxy.  It's a valuable protocol to support for applications that desires a different trade off as the current redis proxy.  It's also the protocol used by most major cloud offerings (AWS elasticache, Azure Cache, Google Memorystore .. etc).

*Proposal*:
Due to the different discovery mechanism, we should create a new redis cluster proxy.  

The initial discovery endpoint point will be specified as a STATIC, STRICT_DNS or LOGICAL_DNS clusters.  On initial connection, the proxy will use the [CLUSTER SLOTS](https://redis.io/commands/cluster-slots) command to retrieve the cluster topology from the cluster.

Subsequently the cluster topology will be maintained and updated based on MOVE and ASK redirections, or active health check.
For more details see [redis cluster spec](https://redis.io/topics/cluster-spec)

If eventual consistency is acceptable, read from replicas will be supported through configuration.  If there's no major objections, I'll begin working on a PR for this.

**Comment by mattklein123** [comment]
@HenryYYang I think this would best be served by a short design doc before submitting a PR. It's not completely clear to me how this is going to flow together. For example, you are going to implement a new cluster type for this that will understand how to fetch the cluster topology? Etc. I also have a general question on the benefit Envoy can provide here. For example, if we are using a redis clustering protocol, I assume Envoy at that point is only being used for stats effectively? Or is the idea that the client doesn't need to understand clustering, they can just talk to Envoy, and then Envoy will do the clustering protocol? Etc. Anyhow, I think this can all be covered in a short design doc. Thank you. cc @danielhochman

**Comment by HenryYYang** [comment]
The idea is that the client don't need to understand clustering, they just talk to envoy as if it's a single redis instance.  For things like python servers where there're typically multiple processes on each host, this can pipeline the redis commands and reduce the number of connections on redis, so there're performance gain as well.  Further more this can be combined with other capabilities of envoy like health check, circuit breaking, prefix routing ... etc.  
Let me put together a short design doc.

**Comment by mattklein123** [comment]
@HenryYYang SGTM, looking forward to the doc.

**Comment by HenryYYang** [comment]
Here's the [draft design doc](https://docs.google.com/document/d/1PDgbANLceC6ZerQXb3LqCPifHRxJuiCeojI86Gcnb5M/edit?usp=sharing)

**Comment by mattklein123** [comment]
@HenryYYang please make the doc world accessible for comments. Thank you!

**Comment by HenryYYang** [comment]
It's world accessible for comments now.

**Comment by HenryYYang** [comment]
Please try again.

**Comment by mattklein123** [comment]
This plan looks good, with the caveat that we won't be able to add Redis cluster specific clusters or load balancers to Envoy core. This will require new extension points. Assuming you are willing to do all of this work (incrementally in small PRs) this sounds like a very exciting addition to Envoy!

cc @htuch for doc comments on extension points for clusters and load balancers. LB extension is already tracked in https://github.com/envoyproxy/envoy/issues/5598. We need a new tracking issue for cluster extension.

**Comment by htuch** [comment]
+1 on extension points for new cluster and LB types. After chatting with gRPC-LB folks, they also want to add the ability to have the address of the endpoint delivered in an opaque form, e.g. `/some/path`, then resolved via a custom resolver to a set of endpoints (i.e. not a single one as done by the resolver extension today), then LBed against, so I think there is some common interest here.

**Comment by msukalski** [comment]
@HenryYYang, @mattklein123, and @htuch -- I've just joined Workday, and I've been asked to extend Envoy to be Redis cluster-aware (Scott C., Sajith K., and Adam K. all say "Hi, Matt!"). Henry's proposal looks great, and I would love to contribute to the effort (including the new cluster and LB extensibililty types), if you can use the help!

**Comment by radykal-com** [comment]
Hi,

I'm just trying to configure envoy proxy in all our php-fpm servers to proxy a RedisCluster with 3 masters and 3 replicas. I'm unable to make it work, I can connect to envoy but all commands return MOVED, like it is unable to map the keyspace and send the commands to the correct node.

After reviewing all the documentation regarding Redis I cannot figure out how to configure it for the RedisCluster. Can someone provide with an example yaml?

**Comment by lvht** [comment]
@radykal-com please enable the `enable_redirection` flag.

![image](https://user-images.githubusercontent.com/2030591/58997211-201aa100-882e-11e9-8a1b-2eee2ceadc40.png)

**Comment by radykal-com** [comment]
Thanks you so much!
