### ISSUE TITLE
envoy with poor performance when dealing with load balance gRPC traffic

### ISSUE THREAD

**Issue by zbye** [envoyproxy/envoy#5700]
**Issue Template**

Envoy get worse performance when deploy several back-end service instances then only one service instance.

*Description*:
Hello.
we found envoy has relatively poor performance when dealing with load balance gRPC traffic with  several backend service instances.  Clients access to Envoy using grpc, and Envoy forwards requests to back-end service using grpc.

We get the surprising result as follows : 

- [1 envoy + 1 service instance:   70000 QPS ] 

- [1 envoy + 2 service instance:   60000 QPS ] 

- [1 envoy + 3 service instance:   55000 QPS ] 

also, we have tried various load balance strategies such as rr,least_request； 
So, I was wondering is it still a weakness or a bug for envoy to deal with load balancing grpc traffic for prime time ???

*Config*:
**the envoy configs as follows:**
admin:
  access_log_path: /home/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9992 }

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: greeter_route     # configure the greeter service routes
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: greeter_service
          http_filters:
          - name: envoy.router      # enable the Router filter
            config: {}
  clusters:
  - name: greeter_service     # register the Greeter server
    connect_timeout: 5s
    type: STATIC
    lb_policy: LEAST_REQUEST
    http2_protocol_options: {}      # enable http2 protocol
    hosts: [{ socket_address: { address: 10.187.160.239, port_value: 6565 }}, { socket_address: { address: 10.187.160.240, port_value: 6565 }} ]

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by zbye** [comment]
I did further test and get the result and  still got abnormal results, as follows:
(1) envoy +   grpc-service instance A,      QPS is 10000;
(2) envoy +   grpc-service instance B,      QPS is 10;;
(3) envoy +    2 instances (A and B) ,    QPS is less than 10, A and B both have incoming traffic ;
I tried various load balancing algorithms such as round_robin/random/least_request and  was confused about the results of the experiment .

is it a weakness or even a bug for envoy to  balance gRPC traffic for multiple backend instances ?  Hope for some guidance or ideas about the question, thanks a lot !!

@mattklein123  @jmarantz @htuch

**Comment by htuch** [comment]
I think seeing some Linux `perf` derived flame graphs would be useful in the different scenarios and comparing. See http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html for how to get these.

**Comment by zbye** [comment]
thanks. we have record the experimental data and haven't find  anything abnormal .

System  Parameters and resource usage data
--
the virtual machine deploying envoy | 32 core, 32G memory   | cpu 350%, memory 0.6%;
the virtual machine deploying service | 8 core, 8G memory    | cpu 35%, memory 40%

Are there any references or explanations for grpc load balance ?

Thanks for helping.

**Comment by zbye** [comment]
![grpc](https://user-images.githubusercontent.com/5737494/53062770-e5019580-34fc-11e9-9f67-54c0e3e759ab.png)

**Comment by htuch** [comment]
gRPC load balancing is no different to normal HTTP/2 load balancing. Do you have maybe circuit breaking kicking in? Is there something very distinct between A and B when it comes to the nature of traffic?

**Comment by zbye** [comment]
Thanks for your time and patience. 

I have disable the circut breaking according to the Envoy documentation (https://www.envoyproxy.io/docs/envoy/latest/faq/disable_circuit_breaking); 
Also, The backend-services are the same except for different processing time of incoming requests. 

One possible solution maybe implement the grpc-service  in other programming languages and do the stress testing again; 

**The configuration file is as follows(attachment):**
admin:
  access_log_path: /home/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9992 }
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: greeter_route     # configure the greeter service routes
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: greeter_service
          http_filters:
          - name: envoy.router      # enable the Router filter
            config: {}
          access_log:
          - name: envoy.file_access_log
            config:
              path: /home/ingress_http.log
  clusters:
  - name: greeter_service     # register the Greeter server
    connect_timeout: 5s
    type: static
    http2_protocol_options: {}      # enable http2 protocol
    hosts: [{ socket_address: { address: 10.187.160.237, port_value: 6565 }}, { socket_address: { address: 10.187.160.240, port_value: 6565 }}]
    circuit_breakers:
      thresholds:
        priority: HIGH
        max_connections: 1000000000
        max_pending_requests: 1000000000
        max_requests: 1000000000
        max_retries: 1000000000



10.187.160.237 and 10.187.160.240 are virtual machines deploying  two backend-services.


[envoy.txt](https://github.com/envoyproxy/envoy/files/2884378/envoy.txt)

**Comment by htuch** [comment]
How is your client generating load? If it has a single thread, it will be waiting for completions before sending an additional request potentially. This means, that if you have a slow backend, its processing time will dominate and force the total QPS down to its throughput.

**Comment by htuch** [comment]
Also CC @oschaaf, who is our resident expert on load generation.

**Comment by zbye** [comment]
thanks @htuch 

I checked the client/backend-service programs again and didn't found anything wrong. My colleagues did the test using different programs get the same result, we use multiple clients  which send requests over 100+ connections.

so, i'm confused about what causes the performance degradation:  
1. How envoy handles incoming requests from a single connection established by client ? does it forwards requests to multiple backend services serially?
2. Does a "slow backend-service" will block envoy’s load balancing process ? From the perspective of cpu usage, the cpu usage dropped from 350% to 20~50% (32 cores) when start a "slow backend-service" connected with envoy.  

![111111](https://user-images.githubusercontent.com/5737494/53172198-b7f9d380-361f-11e9-8238-69a99b8d9c79.png)



we're evaluating envoy’s performance as an front proxy and  longing for your help. thanks a lot. @oschaaf @mattklein123

**Comment by htuch** [comment]
@zbye for (1) Envoy will split requests from the client across multiple backends in parallel and handle them concurrently with HTTP/2 (which is what's happening if we have client/backend gRPC). For (2), if you are using least request LB, see https://github.com/envoyproxy/envoy/issues/4481. You probably want to definitely use RR if you are testing with a few backends.

**Comment by zbye** [comment]
Okay, thanks !

Some of the test results are as follows: 

![2222](https://user-images.githubusercontent.com/5737494/53251910-b5b77800-36f8-11e9-9287-4511217cdb03.png)

![3333](https://user-images.githubusercontent.com/5737494/53252830-c963de00-36fa-11e9-939c-2023d6a8abad.png)


possible reasons for pic2: 
1), There exists some problems with clients, for example clients can’t provide enough concurrent requests. I'll check the client program again and do further tests.
2), Envoy doesn't have good extensibility for load balancing grpc traffic yet right now, but the probability is very small.

**Comment by mattklein123** [comment]
> Envoy doesn't have good extensibility for load balancing grpc traffic yet right now, but the probability is very small.

FWIW, many, many folks use Envoy to load balance gRPC at high performance. I'm fairly certain this is an issue with your test setup.
