### ISSUE TITLE
Envoy as Redis proxy: does that affect throughput?

### ISSUE THREAD

**Issue by jwang0830** [envoyproxy/envoy#5746]
*Title*: *Envoy as Redis proxy: does that affect throughput?*

*Description*:
We're currently using the open source Redis version (not cluster mode) and are considering switching to Envoy as a Redis proxy with the hope of more horizontal scalability to handle more traffic. Based on some simple load testing, it seemed that the throughput didn't improve after introducing Envoy as a proxy (a.k.a the number of timeout errors didn't decrease as a result, if anything, it increased slightly). I wonder if that's a false expectation from us or maybe we didn't use Envoy properly.

For context, our current redis setup is one primary + one replica. Our throughput is at the scale of thousands reads per second + thousands writes per second + close to hundreds of large batch reads and writes. Error rate ranges between 1%-3%.

Would appreciate any insights you could provide. Thanks!

**Comment by HenryYYang** [comment]
The Redis proxy shards both the read/write commands to multiple Redis instances, it doesn't handle replica.  Since you only have 1 primary, there's nothing for Redis proxy to horizontally scale to.

Also can you share some details on your test setup and how you're generating the load please?  Depends on the key/value size and the size of your batch, Redis might not be the bottleneck here.

**Comment by jwang0830** [comment]
Thanks for your reply!

To provide more context: one primary + one replica is the setup with the open source Redis (no Envoy). Our setup with Envoy in test is two nodes behind the proxy (which should handle both read and write requests in my understanding). 

We're generating the load using JMeter (apache's load testing tool), which hits an endpoint handled by test machines that then talk to Redis (hosted on different machines). The key/value size are both < 1KB, though the batch size is quite big, ranging from thousands to couple thousands.

**Comment by HenryYYang** [comment]
The number of operations per second would be a good measure.  I'd suggest limit the batch size to <1000 in general.  The larger your batch size the larger the buffer that's needed and the longer other requests have to wait.

But before you do that, I'd suggest that you monitor you network bandwidth, cpu and memory on both the client machine and redis first.  Then you can figure out the bottleneck and scale accordingly.
