### ISSUE TITLE
Move ssl implementation-based integration tests into extensions/integration

### ISSUE THREAD

**Issue by bdecoste** [envoyproxy/envoy#5762]
Title: Move ssl implementation-dependent integration tests into extensions/integration

Description: Some of the tests in test/integration/ssl_integration_test.cc (e.g. SslCertificateIntegrationTest family) are dependent on Boringssl-specific behavior. Specifically, the tests depend on the exposure of SSL_CLIENT_HELLO and the SSL_early_callback_XXX functions. With openssl replacing boringssl the connection fails as expected but the tests fail because they are based on the ability of boringssl to fail early and set the proper stats/events

**Comment by lizan** [comment]
+1 to move them to extension/transport_socket/tls
