### ISSUE TITLE
Management Server Identification

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5770]
Some times we would like to know to which management server instance, the running Envoy is connected to debug certain scenarios. Currently there is no provision to do that.

The proposal is to include a opaque identifier in `DiscoveryResponse` (similar to opaque identifier in `Node` of `DiscoveryRequest`) that management server can populate and send. On the Envoy side we can push a gauge stat indicating the management server identifier.

What do you think about this? Would you think it would be generally useful or leave it to the management server to figure that out by some logging etc.

**Comment by mattklein123** [comment]
At the API level this SGTM, however I'm not sure we should output this as a numeric gauge given that it's likely to be a string. Can this be output as some sort of admin endpoint? Potentially as part of config_dump?

**Comment by htuch** [comment]
Yeah, I think this should be a `Struct` or something, essentially a JSON object we can dump out on admin. Also related somewhat to https://github.com/envoyproxy/envoy/issues/5405 (but in the other direction..).

**Comment by ramaraochavali** [comment]
@mattklein123  Agree with using(rather misusing) numeric stat for this. I guess it is out of desperation rather than a perfect fit. If new textual stat is available that would be awesome.

Let us add api and output it to config_dump in v1 for management server identification. Once that stat type is available we could just output it to stat as well (which would be very easy thing to do).

If this plan makes sense, please assign this to me.

**Comment by mattklein123** [comment]
Yes let's start with the API change and go from there.
