### ISSUE TITLE
stats: New type(s) of Metric

### ISSUE THREAD

**Issue by fredlas** [envoyproxy/envoy#5790]
Gauges are currently being repurposed for not-particularly-gaugey things, like [hashes](https://github.com/envoyproxy/envoy/blob/4e0b252a0b642e8ac669170130e2202244a53320/source/common/config/grpc_mux_subscription_impl.h#L58) and [booleans](https://github.com/envoyproxy/envoy/blob/4e0b252a0b642e8ac669170130e2202244a53320/source/common/config/grpc_stream.h#L61).

In #4974 I proposed separating these out into a new, more intentionally opaque, stats type. In #5770, @mattklein123 further proposed another type for text strings. This issue will be for 1) discussion of whether to do this and 2) tracking the work if so.

The current stats, which have some significant optimizations applied to their implementations, are all int64s. Does anyone who is familiar with the stats implementation immediately see any likely issues with introducing stats that aren't int64s? Would these strings have to have a maximum, or even fixed length?

Also, let's start the discussion of what to call them. I think it would be fun and useful to keep the physical control panel metaphor of "gauge" going, so I suggest Readout for the text one. For the opaque one, though, I think by its nature can't have a particularly good name, so I suggest just Opaque.

@ggreenway @jmarantz @mattklein123 @ramaraochavali 

(Also: I am considering trying to remove set() from Gauge, or at least making it test-only. However, I haven't yet inspected all of the Gauge::set() users closely enough to know for sure if it would be reasonable.)

**Comment by jmarantz** [comment]
RE variable-length stats: yes, but only after you resolve #4974 . In the meantime you can do one of several things:

- make a new stats base type that fits in the footprint of an existing Counter, which gives you a couple of uint64s worth of characters, which might be enough.
- make a finite table of string-values in the binary and store an index to them in the hash value. You'd have to never re-use indices in this table.
- do the same but store a sha signature in the stat object, which you could then map back to a string. This would not require keeping a stable order over time.

RE the name of this new type: would it make sense to call this "Enum" or does that not capture the use-cases?

The goal of this is to apply different semantics to how they are updated across processes; is that right? What semantics would you use for Gauges vs these new things?

**Comment by fredlas** [comment]
The temporary solution is probably not worth any work, given that no text stats even exist yet, so it would be either option 1, or text stats should just be blocked on #4974.

> RE the name of this new type: would it make sense to call this "Enum" or does that not capture the use-cases?

Unfortunately, the new non-text types intended uses are kind of all over the place. The three representative examples I've found (so far) are bools (good for Enum), version numbers (passable but not great), and hashes (that would be an enum with quite a lot of possible values!)

> The goal of this is to apply different semantics to how they are updated across processes; is that right? What semantics would you use for Gauges vs these new things?

Correct. It only separates the problematic ones out from the "real" gauges, rather than 100% solving the problem, but at least gauges can be handled cleanly with more confidence (just sum old+new, just like counters). Whatever we do, we will need to manually inspect each of the weird ones' "meanings" to determine how they should migrate. The closest thing to a sane blanket policy would be to have these special ones be like std::optionals, and say that the new process copies the old process's value until the new process has filled its own version with a value. Even that would require inserting that optional/nullopt logic everywhere, though.

**Comment by mattklein123** [comment]
@fredlas if possible can you add the results of your search here in this issue? I think it would frame the discussion if we know what stats we are talking about. From my perspective, I think we probably need some type of "string" type, maybe a type of gauge that doesn't sum (is this a new type or just a param in the constructor?), maybe bool? I think it would be easier to discuss if we had the complete picture though. Thank you so much for doing this due diligence.

**Comment by jmarantz** [comment]
What are the operational differences? To me one critical difference is that all of the variants you suggest cannot be accumulated arithmetically. Opaque seems a good name, or maybe Symbolic?

**Comment by fredlas** [comment]
envoy/src/source/common/config/filesystem_subscription_impl.h
66 stats_.version_.set(HashUtil::xxHash64(message.version_info()));

envoy/src/source/common/config/grpc_mux_subscription_impl.h
58 stats_.version_.set(HashUtil::xxHash64(version_info));

envoy/src/source/common/config/grpc_stream.h
61 control_plane_stats_.connected_state_.set(1);
73 control_plane_stats_.pending_requests_.set(queue_size);
104 control_plane_stats_.connected_state_.set(0);

envoy/src/source/common/config/http_subscription_impl.h
92 stats_.version_.set(HashUtil::xxHash64(request_.version_info()));

envoy/src/source/common/runtime/runtime_impl.cc
229 stats.num_keys_.set(values_.size());
275 stats_.admin_overrides_active_.set(values_.empty() ? 0 : 1);

envoy/src/source/common/upstream/cluster_manager_impl.cc
607 cm_stats_.active_clusters_.set(active_clusters_.size());
608 cm_stats_.warming_clusters_.set(warming_clusters_.size());

envoy/src/source/common/upstream/health_checker_base_impl.cc
145 stats_.healthy_.set(local_process_healthy_);
146 stats_.degraded_.set(local_process_degraded_);

envoy/src/source/common/upstream/resource_manager_impl.h
55 open_gauge_.set(canCreate() ? 0 : 1);
60 open_gauge_.set(canCreate() ? 0 : 1);

envoy/src/source/common/upstream/upstream_impl.cc
641 info_->stats().membership_total_.set(hosts);
642 info_->stats().membership_healthy_.set(healthy_hosts);
643 info_->stats().membership_degraded_.set(degraded_hosts);
1182 info_->stats().max_host_weight_.set(max_host_weight);

envoy/src/source/extensions/filters/network/client_ssl_auth/client_ssl_auth.cc
77 stats_.total_principals_.set(new_principals->size());

envoy/src/source/server/listener_manager_impl.cc
858 stats_.total_listeners_draining_.set(draining_listeners_.size());
881 stats_.total_listeners_draining_.set(draining_listeners_.size());

envoy/src/source/server/listener_manager_impl.h
148 stats_.total_listeners_warming_.set(warming_listeners_.size());
149 stats_.total_listeners_active_.set(active_listeners_.size());

envoy/src/source/server/overload_manager_impl.cc
62 active_gauge_.set(0);
72 active_gauge_.set(1);
76 active_gauge_.set(0);
229 pressure_gauge_.set(usage.resource_pressure_ * 100); // convert to percent

envoy/src/source/server/server.cc
129 server_stats_->live_.set(!fail);
149 server_stats_->uptime_.set(time(nullptr) - original_start_time_);
150 server_stats_->memory_allocated_.set(Memory::Stats::totalCurrentlyAllocated() +
152 server_stats_->memory_heap_size_.set(Memory::Stats::totalCurrentlyReserved());
153 server_stats_->parent_connections_.set(info.num_connections_);
154 server_stats_->total_connections_.set(numConnections() + info.num_connections_);
155 server_stats_->days_until_first_cert_expiring_.set(
240 server_stats_->concurrency_.set(options_.concurrency());
241 server_stats_->hot_restart_epoch_.set(options_.restartEpoch());
253 server_stats_->version_.set(version_int);

**Comment by fredlas** [comment]
Yeah, accumulation being nonsensical is definitely the number one differentiator here.

Doing all this with just a new constructor param could be a very good idea; it would be a way smaller change. So, you'd just have a bool accumulatable(), and have the hot restart logic be based on its value?

With that approach on the table, the question of whether to split out an opaque and/or bool type comes down to whether people feel the more accurate typing is worth the extra complexity. I would lean towards yes if we're already planning to add a text type regardless, but having "counter, gauge {accumulatable=true,false}, string" would certainly also be a reasonable design.

**Comment by ramaraochavali** [comment]
I think having  string type would be a valuable addition. Some thing like `server.version` could potentially benefit from it apart from the other use case about management server identification we were discussing in #5770

**Comment by mattklein123** [comment]
Subclassing sounds fine to me. Great thanks for the list @fredlas. Looking at this, I think if we can get a bool type (which you already started) and a string type (per @ramaraochavali) I think we will be all set. And then probably some type of non-accumulating gauge.

FWIW, these are the ones I'm most concerned about and will need some thinking on what we do about them from an operational perspective:
```
envoy/src/source/common/upstream/upstream_impl.cc
641 info_->stats().membership_total_.set(hosts);
642 info_->stats().membership_healthy_.set(healthy_hosts);
643 info_->stats().membership_degraded_.set(degraded_hosts);
```

Technically, I think these can be summed between both processes, since it really is the added state of both processes, however, from an operational perspective, I'm concerned that users are going to have dashboards, etc. that are going to break when during hot restart we see double the target hosts. This is why you see a bunch of comments in that file about refreshing the gauge during hot restart. This comment is not immediately actionable, but please keep it in mind so we can all discuss once the plumbing is in place.

**Comment by fredlas** [comment]
The stats classes are carefully implemented in a way to enable hot restart... but they don't themselves actually implement any of the hot restart handover functionality, right? In that case, I don't think subclassing is the most natural approach. Subclassing should be "I'm a type of Foo that behaves in this Foo-like but different way", whereas this is "Bar should do its processing on some Foos in one way, and others in another, but the Foos themselves don't behave differently during this processing." Put in concrete Envoy terms, if someone isn't using hot restart, then these two classes would be identical.

What if rather than splitting all non-accumulatable Gauge types out into another thing, we introduce the ability to have various transfer logics, and think about it that way? I think just "accumulate" and "maximum" might cover all current gauges, but we could leave it open to e.g. "minimum", "always take parent value", etc being added.

The new string type should be fine for the hashes. With hashes and bools taken care of, all of the remaining "weird" gauges would be legitimate numerical values. It would then be a pretty clean interface: your gauges are still all gauges; you're just specifying an enum for hot restart behavior for each of them.

**Comment by mattklein123** [comment]
Having some type of enum param to indicate transfer logic sounds good to me. My general advice is to keep this as simple as possible and just implement exactly what we need for the stats that we have. We can always expand things later.

**Comment by fredlas** [comment]
Agreed. I'm imagining the entirety of the implementation to look like

```
static Metric::combine(Metric m1, Metric m2, CombineLogic logic) {
  switch(logic) {
  case ACCUMULATE:
    return m1 + m2;
  ...
```

Perhaps we will end up with only the 'accumulate' and 'maximum' types, and never add a 3rd, but even in that case I think the "ways metrics can be combined" enum is nice to clearly convey how a given gauge works.

**Comment by fredlas** [comment]
Non-shared-memory stats was done without this, and there isn't currently any movement towards unreverting the BoolIndicator PR, so let's close this for now.
