### ISSUE TITLE
Add response header limiting

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#5810]
Other half of #5626.

Roadmap:
- [ ] Add response header limiting
- [ ] Add max_response_headers_kb configurable field
- [ ] Add extra checks to the codec

**Comment by auni53** [comment]
@mattklein123 

Could you weigh in on where in conn_manager_impl.cc this check should go?

Assuming it'll go in ActiveStream::encodeHeaders, I was thinking prior to draining (L1148), or prior to the stats call (L1220). Not sure how important the exact location is, but I'm assuming I'll check the response headers size and change the response if it exceeds the limit. As well, the 431 error would be inaccurate, so I'll have to figure out what response would be appropriate.

**Comment by auni53** [comment]
Basically, there can be malicious backends e.g. in our use case; so ya, protecting against upstream that does something bad. There's already response limiting present, just based on whatever the codecs limit it to. We want a configurable knob akin to the request one I just added, to turn the limit up as well adding testing for that.

We could reset stream in http2 and send 50X (i'll confirm) in http1.

**Comment by mattklein123** [comment]
I think the this likely needs to be done directly in both the HTTP/1.1 and HTTP/2 codecs, but client side. For HTTP/2 I think this is basically already done, it just needs to be done client side also. And then we need to do something similar for HTTP/1. The reason I think it needs to be done here is this is the only place that can protect against unlimited memory usage for headers. I think if we do it here, we can just raise a client-side reset which would result in a 5xx/reset/etc. so I think this would work out well?

**Comment by zhanghaohao** [comment]
/reopen 
Any progress on this proposal ?
