### ISSUE TITLE
Stats: Envoy "upstream_rq_xxx" stats are inconsistent across hot-restart

### ISSUE THREAD

**Issue by srinivasganapathy** [envoyproxy/envoy#5819]
We are running Envoy proxy version 1.8 and are having inconsistency reported across hot-restarts.
Looked around the documentation and discussion boards, there isn't much of discussion around this level of inconsistency.
So it may turn out that we are missing some config/cmd line parameters.

Below is the output of "ps" command:
=========================
[root@localhost ~]# ps -eaf | grep envoy | grep -v grep
envoy     8827  7787  0 17:22 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py /opt/envoy/bin/start_envoy.sh
envoy     8832  8827  1 17:22 ?        00:00:13 /opt/envoy/bin/envoy --restart-epoch 0 --log-path /var/log/<mydir>/envoy/stdout.log --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info
[root@localhost ~]#

Below is the output of "stats", everything looks correct
===================================
[root@localhost ~]# curl localhost:9903/stats | grep -e "upstream_rq_[[:digit:]]" | tee 2>err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18013    0 18013    0     0  4214k      0 --:--:-- --:--:-- --:--:-- 5863k
[sanitized].external.upstream_rq_200: 6512
[sanitized].external.upstream_rq_201: 36
[sanitized].external.upstream_rq_2xx: 6548
[sanitized].external.upstream_rq_503: 867
[sanitized].external.upstream_rq_5xx: 867
[sanitized].retry.upstream_rq_503: 18
[sanitized].retry.upstream_rq_5xx: 18
[sanitized].upstream_rq_200: 6512
[sanitized].upstream_rq_201: 36
[sanitized].upstream_rq_2xx: 6548
[sanitized].upstream_rq_503: 867
[sanitized].upstream_rq_5xx: 867

Will do an hot-restart now:
=================

When the hot-restart is in progress, below is the ouput of "ps" command
===============================================
[root@localhost ~]# ps -eaf | grep envoy | grep -v grep
envoy     8827  7787  0 17:22 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py /opt/envoy/bin/start_envoy.sh
envoy     8832  8827  1 17:22 ?        00:00:15 /opt/envoy/bin/envoy --restart-epoch 0 --log-path /var/log/<mydir>/envoy/stdout.log --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info
envoy    30086  8827  1 17:44 ?        00:00:00 /opt/envoy/bin/envoy --restart-epoch 1 --log-path /var/log/<mydir>/envoy/stdout.log --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info
[root@localhost ~]#

Hot-restart is completed now, see "ps" output, restart-epoch is 1:
==========================================
[root@localhost ~]# ps -eaf | grep envoy | grep -v grep
envoy     8827  7787  0 17:22 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py /opt/envoy/bin/start_envoy.sh
envoy    30086  8827  1 17:44 ?        00:00:01 /opt/envoy/bin/envoy --restart-epoch 1 --log-path /var/log/<mydir>/envoy/stdout.log --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info
[root@localhost ~]#

Below is the output of "stats" after hot-restart:
==============================
[root@localhost ~]# curl localhost:9903/stats | grep -e "upstream_rq_[[:digit:]]" | tee 2>err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17191    0 17191    0     0  4060k      0 --:--:-- --:--:-- --:--:-- 5596k
[sanitized].external.upstream_rq_200: 7864
[sanitized].external.upstream_rq_2xx: 7900
[sanitized].upstream_rq_200: 7864
[sanitized].upstream_rq_2xx: 7900
[root@localhost ~]#

It can be clearly observed that:
====================
1. After hot-restart, we are loosing important counters other than "upstream_rq_200" and "upstream_rq_2xx". We are missing 503, 5xx, 401, 4xx etc..
2. The values are inconsistent, "upstream_rq_2xx" value is "7900" while "upstream_rq_200" value is "7864", they do not add up either
3. We have also had a situation where "upstream_rq_4xx" value is "1" while "upstream_rq_404"  value is "2"

Questions:
=======
Version 1.8 has been doing very well for us in meeting our functional and performance requirement, but our upstream health determination is running into issues because of counter inconsistency after hot-restart, we rely heavily on hot-restart in our development.
Error seem to be very basic and it is possible we have missed some config parameters, so it would be helpful if you let us know.
Else, please let us know what additional information is needed in-order to debug this and fix them in upcoming release.

**Comment by srinivasganapathy** [comment]
Thanks for your quick response, another question we have:
Will the new architecture changes coming up with #4974 , will this change fix the current inconsistency with "/stats" API ?

**Comment by mattklein123** [comment]
I'm not sure which inconsistency you are talking about, but if it's stats not showing up from the old process, yes, this will not happen anymore. With all of that said though, direct usage of the `/stats` endpoint is for local debugging and none of this should matter for large scale production use.

**Comment by srinivasganapathy** [comment]
Thanks for the quick response again, the inconsistency referred to was the below snippet from my original communication :
        >>The values are inconsistent, "upstream_rq_2xx" value is "7900" while "upstream_rq_200" value is "7864", they do not add up either
        >>We have also had a situation where "upstream_rq_4xx" value is "1" while "upstream_rq_404" value is "2"

"upstream_rq_2xx" value is 7900 and "upstream_rq_200" value is 7864 and we do not know what is the difference value 36.
"upstream_rq_4xx" value is 1 while "upstream_rq_404" is 2, this is quite interesting and reversed in nature. This has the potential to put our calculations to a negative value.

For the 2xx case, if the missing stat shows up (lets say upstream_rq_201 or upstream_rq_202) - that should fill the difference we are seeing
However, for the 4xx case, something seem to have broken

From your reply and with the new design in place for stats(#4974) coming up in 1.10 version, we may see accurate values. 

It would be good if you can let us know the probable ETA for 1.10 version and will 1.10 address #4974.
Thanks again,
Srini

**Comment by thevks** [comment]
> What is happening is here is an artifact of how shared memory stats work and the `/stats` endpoint. Roughly, counters and gauges are kept in shared memory. When the new process creates a stat, it looks in shared memory for a counter/gauge of the same name. If one is found, it "attaches" to it, and suddenly you will get all of that data. If the new process never creates/accesses the stat, it will never be created in the new process, and the new process will never know about it, and it will not show up in `/stats`.
> 
> In practice, from an operational standpoint, this shouldn't matter, since counters are flushed before hot restart and you should have accurate information in your TSD. However it is true that if you look at `/stats` it will be inconsistent.
> 
> This is not something we are going to fix. We are planning on completely doing away with keeping stats in shared memory which should make this problem go away when it is implemented. See #4974. cc @fredlas @jmarantz

@mattklein123 
As you mentioned, if envoy child process sees any dynamic counter (say 503) after hot restart, it should add up to its shared memory value. In that case, counter value should be incremental to shared memory value. 
However, I see decreased counter values in come cases. 
Would you please confirm this behavior? Is it a defect?

**Comment by jmarantz** [comment]
I think even without hot-restart you can see a difference in the /stats view like
```
[sanitized].external.upstream_rq_200: 7864
[sanitized].external.upstream_rq_2xx: 7900
```
Each stat value lives in its own atomic, and the /stats endpoint iterates through them. There could easily be 36 requests in between when upstream_rq_200 and upstream_rq_2xx are sampled.

I'm not saying that's what happened in your case, but I think you want to be mindful about the fact that the /stats endpoint does not give you a consistent view across stats.

**Comment by thevks** [comment]
> I think even without hot-restart you can see a difference in the /stats view like
> 
> ```
> [sanitized].external.upstream_rq_200: 7864
> [sanitized].external.upstream_rq_2xx: 7900
> ```
> Each stat value lives in its own atomic, and the /stats endpoint iterates through them. There could easily be 36 requests in between when upstream_rq_200 and upstream_rq_2xx are sampled.
> 
> I'm not saying that's what happened in your case, but I think you want to be mindful about the fact that the /stats endpoint does not give you a consistent view across stats.

@jmarantz 
I understand this inconsistency. 
However, I need to understand stats behaviour after hot restart. If a counter is having some value before hot restart (say 1000), I expect after hot restart it should always have increased value (1000+ or so, unless counter overflows). But in my observation, in some cases, I do see the counters are having lower values (say 200) compared to values prior to hot restart. My guess is that counter value (after hot restart) is not getting added to shared memory value (prior to hot restart).

**Comment by jmarantz** [comment]
OK I see. I don't think there's a defect; this is just how the system works.

In your case, before hot-restart, rq_2xx  was the sum of rq_200 and rq_201. After hot-restart, there were no 201 responses and an artifact of the UI is that it doesn't show any stats that haven't been updated since hot-restart. The rq_201 responses are actually *still there* in shared memory but the stat is not in the list of stats emitted from the /stats endpoint.

I think this is WAI for now. In #4974 we'll change from using shared-memory for stats, to sending all the stats from the old process to the new one, and in so doing we may wind up re-populating the lists of stats to emit as you might expect, but I don't know if that's 100% determined yet.

**Comment by thevks** [comment]
> OK I see. I don't think there's a defect; this is just how the system works.
> 
> In your case, before hot-restart, rq_2xx was the sum of rq_200 and rq_201. After hot-restart, there were no 201 responses and an artifact of the UI is that it doesn't show any HTTP Response stats that haven't been updated since hot-restart. This is because there are potentially hundreds of response codes, but usually few are accumulated in practice. The rq_201 responses are actually _still there_ in shared memory but the stat is not in the list of stats emitted from the /stats endpoint.
> 
> I think this is WAI for now. In #4974 we'll change from using shared-memory for stats, to sending all the stats from the old process to the new one, and in so doing we may wind up re-populating the lists of stats to emit as you might expect, but I don't know if that's 100% determined yet.

@jmarantz, @mattklein123.
I understand the behaviour - where counter will be shown only as part of appropriate HTTP response. 

However, I am asking the case, when counters are appearing after hot restart but their values are lesser than what it was before hot restart.

**Comment by jmarantz** [comment]
I agree that seems unfortunate. Did you observe that case? I could not find it in what you wrote above.

I would also phrase your description of the behavior differently:

> counters will only show up in the stats output if an HTTP response has occurred in the child process.

This is subtly different from what you said. But I realize this might not be your main point. And apologies if I missed in your description a case where a single counter decreased in value across hot-restart. Can you remind me?

**Comment by thevks** [comment]
> I agree that seems unfortunate. Did you observe that case? I could not find it in what you wrote above.
> 
> I would also phrase your description of the behavior differently:
> 
> > HTTP response-code counters will only show up in the stats output if an HTTP request handled in the _new_ process resulted in that response code.
> 
> This is subtly different from what you said. But I realize this might not be your main point. And apologies if I missed in your description a case where a single counter decreased in value across hot-restart. Can you remind me?

>>And apologies if I missed in your description a case where a single counter decreased in value across hot-restart. Can you remind me?

Yes, this exactly what I am talking about. Sometimes, counters are having decreased value across hot-restart. This is not reproducible always, however I observed it.

**Comment by thevks** [comment]
@jmarantz, @mattklein123 

I could able to reproduce the scenario:

1) **Envoy is running with epoch ‘0’**
----------------------------------------
    [root@localhost ~]# ps -eaf | grep envoy | grep -v grep

   envoy      388  7450  0 09:13 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py 
  /opt/envoy/bin/start_envoy.sh

  envoy      393   388  2 09:13 ?        00:00:24 /opt/envoy/bin/envoy --restart-epoch 0 --config-path 
  /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info

2) **The “/stats” API output before hot restart:**
----------------------------------------------------
  [root@localhost ~]# curl "http://localhost:9903/stats" | grep "upstream_rq_[[:digit:]]" | tee 2>err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18587    0 18587    0     0  2579k      0 --:--:-- --:--:-- --:--:-- 3025k

cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_200: 1979
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_201: 24
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_2xx: 2003
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_400: 2
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_404: 9
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_4xx: 11
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_503: 13616**
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_5xx: 13616**
cluster.4sAES710T0OotUjItVgKdw.retry.upstream_rq_503: 3
cluster.4sAES710T0OotUjItVgKdw.retry.upstream_rq_5xx: 3
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_200: 1979
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_201: 24
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_2xx: 2003
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_400: 2
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_404: 9
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_4xx: 11
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_503: 13616**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_5xx: 13616**

3) **Trigger hot-restart and wait for drain to complete - Secondary process is created with epoch ‘1’:**
----------------------------------------------------------------------------------------------------
[root@localhost ~]# ps -eaf | grep envoy | grep -v grep

envoy      388  7450  0 09:13 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py /opt/envoy/bin/start_envoy.sh

envoy      393   388  2 09:13 ?        00:00:24 /opt/envoy/bin/envoy --restart-epoch 0 --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info

envoy    22300   388  3 09:31 ?        00:00:00 /opt/envoy/bin/envoy --restart-epoch 1 --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info


4) **Hot-restart and draining completed:**
-------------------------------------------
[root@localhost ~]# ps -eaf | grep envoy | grep -v grep

envoy      388  7450  0 09:13 ?        00:00:00 /usr/bin/python /opt/envoy/bin/envoy_hot_restarter.py /opt/envoy/bin/start_envoy.sh

envoy    22300   388  1 09:31 ?        00:00:00 /opt/envoy/bin/envoy --restart-epoch 1 --config-path /opt/envoy/config/envoy.yaml --parent-shutdown-time-s 80 --drain-time-s 75 --log-level info


5) **The “/stats” API output after hot restart:**
-------------------------------------------------
[root@localhost ~]# curl "http://localhost:9903/stats" | grep "upstream_rq_[[:digit:]]" | tee 2>err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16530    0 16530    0     0  4391k      0 --:--:-- --:--:-- --:--:-- 5380k

cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_200: 3947
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_2xx: 3971
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_200: 3947
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_2xx: 3971

6) **Introduced some 5xx by making cluster down and take the “/stats”:**
----------------------------------------------------
[root@localhost ~]# curl "http://localhost:9903/stats" | grep "upstream_rq_[[:digit:]]" | tee 2>err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17519    0 17519    0     0  6099k      0 --:--:-- --:--:-- --:--:-- 8554k

cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_200: 4028
cluster.4sAES710T0OotUjItVgKdw.external.upstream_rq_2xx: 4052
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_503: 390**
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_5xx: 390**
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_200: 4028
cluster.4sAES710T0OotUjItVgKdw.upstream_rq_2xx: 4052
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_503: 390**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_5xx: 390**


Please observe the behavior of step 2 and step 6 outcome. In summary, here are the values of 503 and 5xx counters calues

**Before hot restart** 
----------------------
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_503: 13616**
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_5xx: 13616**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_503: 13616**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_5xx: 13616**

After hot restart
------------------
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_503: 390**
cluster.4sAES710T0OotUjItVgKdw.**external.upstream_rq_5xx: 390**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_503: 390**
cluster.4sAES710T0OotUjItVgKdw.**upstream_rq_5xx: 390**


You can see 503 and 5xx counters are having decreased value from 13616 down to 390.

**Comment by mattklein123** [comment]
I think what is happening here is that since there are no 503/5xx when the new process starts up, it does not attach to the shared memory stats slot. When the old process shuts down, it deletes the slot. Then when you introduce 503/5xx in the new process it allocates a new slot from scratch.

This is working as intended with the current shared memory system.
