### ISSUE TITLE
time: Pass TimeSource rather than TimeSystem around.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5820]
TimeSystem leaks the Libevent API, so it would be better if it were loss broadly visible.

TimeSystem adds only one API: createScheduler, which is used only in the Dispatcher. So there's no need for all the Envoy code to be aware of it and the Libevent API.

It is necessary to expose the Libevent API, however to the SimulatedTimeSystem. This may become easier to reason about when we have an abstraction over Libevent.

Per discussion with @mattklein123

**Comment by mattklein123** [comment]
> This may become easier to reason about when we have an abstraction over Libevent.

We do have pretty complete abstraction, dispatcher. :) Per offline convo, I think what we can do here is instead of creating timers off of `TimeSystem`, have a `DispatcherFactory` which makes dispatchers. And then we can have a `LibEventRealTimeDispatcher`, `LibEventSimTimeDispatcher` which derives from the real dispatcher but overrides the timer creation functions, etc. I think this would be pretty clean and not too hard?

**Comment by jmarantz** [comment]
Actually the API already creates dispatchers, so I think we're already there, and with the changes in #5845 plus another 20-file diff I have stashed, the API will be the only way to create a DispatcherImpl.

**Comment by jmarantz** [comment]
I'm partway through a PR that does this, but I ran into a situation that requires an aesthetic choice that I want some feedback on before I go further.

In this PR I changed every place, mostly tests, that created a DispatcherImpl, to do so via Api::allocateDispatcher(). Since the API knows the TimeSystem, and almost no other prod classes have access to the time system, this feels like a good change, and the resulting code is more readable and is not exposed to the existence of TimeSystem.

However, there is a subclass of DispatcherImpl, ValidationDispatcher, in source/server/config_validation/dispatcher.h .  That dispatcher either needs to receive the TimeSystem as an arg, or we need to make API (and its mock) responsible also for allocating ValidationDispatcher, which requires an additional dependency from API to DNS and possibly other things.

Alternatively we can continue to provide method `API::TimeSystem& timeSystem()` and just call it significantly less.

Thoughts?

**Comment by mattklein123** [comment]
> However, there is a subclass of DispatcherImpl, ValidationDispatcher, in source/server/config_validation/dispatcher.h . That dispatcher either needs to receive the TimeSystem as an arg, or we need to make API (and its mock) responsible also for allocating ValidationDispatcher, which requires an additional dependency from API to DNS and possibly other things.

Could you just make a `ValidationApi` which is a sub-class of `Api` that knows how to do this correctly?

**Comment by jmarantz** [comment]
A subclass of Api::Api or of Api::ApiImpl? If of Api::Api, would create the ValidationApi and where would the TimeSystem come from?

I also noted that the call-stack where a ValidationDispatcher is created also has a Dispatcher (the main thread dispatcher). DispatcherImpl is constructed with a TimeSystem but doesn't currently save it, but it obviously could without extra dependencies.

So we could solve this problem also by providing the Dispatcher interface with a timeSystem() API in addition to a timeSource() API. That would be pretty easy.

**Comment by mattklein123** [comment]
I was thinking a subclass of Api::ApiImpl, but I haven't looked at the code enough to have a solid opinion. I guess my preference here is to try to fix the validation case in as targeted a way as possible without polluting the primary interfaces.

**Comment by jmarantz** [comment]
I agree with the targeted approach, otherwise the current state of the code is really as good as it gets. I've just plumbed this in through.

The next challenge is LIstenerImpl, whose relationship with DispatcherImpl is expressed in terms of libevent structures, notably DispatcherImpl::base(), which is not in the Dispatcher pure API. This works fine in the production code, but not in tests. In tests, there is a TestListenerImpl, which just has a mocked method for getLocalAddress(), which is a protected method of BaseListenerImpl.

This can be resolved in a few ways:
 - dynamic_cast the result of API::allocateDispatcher into a concrete LIstenerImpl - this is the most expedient but the grossest
 - try to isolate all libevent use in an abstract base class pattern, and add access to the abstract base class for those to the Dispatcher interface.

The latter IMO would be a good way to go but would probably blow out this PR in complexity, so I'm thinking dynamic_cast for now.  WDYT?

**Comment by mattklein123** [comment]
> The latter IMO would be a good way to go but would probably blow out this PR in complexity, so I'm thinking dynamic_cast for now. WDYT?

It's hard for me to comment here without looking at a PR. I would say just go for the simplest option for now and we can discuss in code review? I see you opened a PR so I will take a look.

**Comment by mattklein123** [comment]
I think this is fixed.
