### ISSUE TITLE
Support for request hedging (racing) on per try timeout

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#5841]
*Title*: *Support for request hedging (racing) on retry timeout*

*Description*:
This issue is similar to #2784 (which discusses support for sending multiple simultaneous requests and using the first response to manage tail latency) however specifically pertains to handling of a timed out request. This would allow for sending a comparatively lower overall request volume than straight up hedging while being resilient to slow upstreams. It's essentially the same per try timeout behavior in place today, except the original request will not be canceled and the first response received can be used.

I imagine it would make sense to implement #2784 first since that seems like less of an architectural change to the router and then add options to only send the extra requests when the per try timeout is hit.

I'm interested in taking it on

**Comment by snowp** [comment]
@htuch @mattklein123 Thoughts on this "hedge on timeout" feature? If this makes sense I'll be working with Mike to come up with an design for configuring this + proposed implementation

**Comment by htuch** [comment]
@mpuncel I invited you to envoyproxy org so I can assign you the issue.

**Comment by mpuncel** [comment]
Sounds good! The idea with the timeout approach is that you can cut tail latency while not multiplying traffic volume as much as you would with proactive hedging. Also if request processing time grows organically to surpass the timeout threshold then requests won't fail (although you'll get unnecessary load so you need a mechanism to find this situation and adjust the timeout appropriately)

**Comment by mattklein123** [comment]
@mpuncel @snowp this sounds great to me. This has been a feature that has been requested for quite some time. I don't think it should be TOO difficult :), as I did setup the router code to decouple upstream requests from downstream requests quite a long time ago, but it will definitely be a complex change. Please make sure to have some integration tests. All of the cool simulated time work that @jmarantz has been doing should make this a lot easier to test as an integration test.

**Comment by mpuncel** [comment]
doc: https://docs.google.com/document/d/1OsDjLtKUweQS0kEQDWs9VF4l46_leQ74dk-G2oQJoNI/edit?usp=sharing

**Comment by mpuncel** [comment]
I ran into an issue here I'm not sure how to resolve. It looks like today per try timeouts are only retried if `retry_on` includes either `5xx` or `gateway-error`. That's because of this case here: https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L264.

My change is making retries on per try timeouts that do not have a reset at all. I have 3 options to decouple these retries from resets: 
1) keep the existing logic where the per try timeout is only retried if you're retrying 5xx or gateway error. 
2) add a new retry_on case like `per-try-timeout`
3) always retry per try timeout (subject to the number of retries remaining).

1) is probably surprising from a user experience perspective. If i'm setting a per try timeout, isn't that implying I want it to be retried? What does 5xx have to do with a timeout?
2) is probably the cleanest solution, but will cause divergent behavior between hedged per try timeouts and normal per try timeouts if we don't want to change behavior for existing users. I'm not sure if we'd be able to reconcile the two ever because we would have to break backwards compatibility.
3) Is the option i'd go with if we could start from the beginning and would be safe if it only applies to the hedged per try timeout case, but again would result in a divergence of behavior between non-hedged vs hedged per try timeouts.

**Comment by tommyulfsparre** [comment]
Sorry for coming in late with a drive by comment(should I have opened a separate issue?) but curious if it would be possible or even a good idea to have a hedging policy configured based on the percentile of the overall request latency?
This would require Envoy to support latency monitoring which might be too expensive? 

Basically this would be a more adaptive approach then setting `per_try_timeout` with the downside of the added complexity.

**Comment by mattklein123** [comment]
@tommyulfsparre I would recommend opening a separate issue on your request, sounds interesting but I think a bit different then what we are looking at here.

**Comment by mattklein123** [comment]
@mpuncel TBH I don't recall the history of how we got to where we are today. I think the general idea is that we want to make sure that even if we specify a per try timeout, we only retry in cases where the user explicitly opts in.

> My change is making retries on per try timeouts that do not have a reset at all. I have 3 options to decouple these retries from resets:

I don't quite follow this. Why does your change effect this behavior? Is it because you are going to hedge/retry on a per try timeout?

**Comment by mpuncel** [comment]
@mattklein123 yeah. Before this change, there is never a retry that is not in response to a reset (even if in the timeout case it's a local reset).

After further thought, I think it makes sense to keep the `RETRY_ON_5XX or RETRY_ON_GATEWAY_ERROR` condition. Basically pretends it's a 504.

**Comment by hongzimao** [comment]
Just opt in to check the progress of this development. Is this ready to pull the latest code and try out now? 

Also, to clarify, when one of the duplicated requests responds, will we cancel other replicas? 

Thanks for the great work!

**Comment by snowp** [comment]
Yeah we're running with this feature in production, and yes the other requests will be reset. Whether this results in request cancelation on the server side will depend on how your server handles resets.

**Comment by hongzimao** [comment]
Thanks for the reply @snowp! By "reset" do you mean the load balancer will send a special signal to the server side? Does the server side envoy have a separate port for "reset" traffic (I would imagine the duplicated request is queued before reset)? This might be a trivial question but I want to understand more about the underlying implementation.

Are there a few entry points to how this feature is implemented and used (e.g., any wiki)? Thank you!

**Comment by snowp** [comment]
iirc for http 1.1 a reset means that envoy closes the connection (I could be wrong here), while for http/2 it means that it sends a RST_STREAM frame to the server. It would be up to the server to handle this - there's no out of band communication of resets
