### ISSUE TITLE
API build system should use different repo name than com_github_gogo_protobuf

### ISSUE THREAD

**Issue by cstrahan** [envoyproxy/envoy#5851]
The API build system's dependencies (more accurately, the choice of repository name thereof) causes a name collision. See `com_github_gogo_protobuf` defined here:

https://github.com/envoyproxy/envoy/blob/98a441f153fbecf3f7fc4c6135ed1bbcf9c7e49f/api/bazel/repositories.bzl#L200-L259

We have custom build of Envoy in which we support filters written in Go. One of our filters (written in Go) recently took a dependancy on `github.com/gogo/protobuf`. As a result, our `gazelle` generated `go_repository`s expects `@com_github_gogo_protobuf` to name a Go package repository, but the definition from envoy's API clashes, and manifests as errors like:

> ERROR: Analysis of target '//:gm-proxy' failed; build aborted: no such package '@com_github_gogo_protobuf//types': BUILD file not found on package path

Envoy should use a different name, as it causes problems for any build system incorporating both envoy and a Go project that both use `github.com/gogo/protobuf`.

**Comment by htuch** [comment]
@jmillikin-stripe what's your thoughts on this? IIRC you educated us on the best practice of picking these names back in the day.

**Comment by jmillikin-stripe** [comment]
Envoy and Gazelle are both following the Bazel naming best practices. When upstream has no Bazel configs and two different repos want different build content, you'll get a collision like this.

I don't understand why `envoy/api/bazel/repositories.bzl` is defining GoGo dependencies, though. Has part of the Go control plane been upstreamed into the Envoy main repo? If so, Envoy should use https://github.com/bazelbuild/bazel-gazelle to define the Go dependencies.

**Comment by htuch** [comment]
I think the Go stuff is there for API validation purposes. @kyessenov do you have more context on this?

**Comment by jmillikin-stripe** [comment]
If Envoy used rules_go's Gazelle to define its Go dependencies, then there wouldn't be a mismatch.

**Comment by cstrahan** [comment]
@jmillikin-stripe 

> If Envoy used rules_go's Gazelle to define its Go dependencies, then there wouldn't be a mismatch.

Perhaps that could be done for the Go codegen; how would the other languages (C++/Python/etc) be handled? Is there a label with which to refer to the proto directly, like `@com_github_gogo_protobuf//gogoproto:gogo.proto`? If so, `gogo_proto_cc` et al could be factored out of that repo. If not, I'm not sure what the "blessed" was is to solve this.

For the sake of making the general problem explicit, we have:

* A project written in one language, and it's repo includes one or more protos.
* Multiple third party projects written in other languages want to use those protos, too.

In general, how should this be handled in bazel? If the repo in question _solely_ contained the proto, it would be trivial: have `@com_github_gogo_protobuf` simply export a tree of proto files. But in our case, what do we do? We want to build the Go project that hosts the proto file(s), and logically that build should be identified under `@com_github_gogo_protobuf`. But then, we also want to do codegen for other languages, and each of those "should" go under `@com_github_gogo_protobuf`. Trying to make all of these targets coexist in one bazel repo is infeasible, though.

The first obvious place to look for precedent on how this should be handled, IMO, is in protobuf. The `*.proto`s are all hosted in [the C++ project](https://github.com/protocolbuffers/protobuf)'s source tree. Now, I know that the Go protobuf library also needs at least `descriptor.proto`, `plugin.proto`, and all of the well known types (`any.proto`, `struct.proto`, etc). So how are those pulled in?

They're simply [vendored](https://github.com/golang/protobuf/tree/master/ptypes).

So I don't know if the takeaway is that each project should have a copy of the upstream protos in their source tree, or if there simply hasn't been enough thought given to how this scenario should be handled in bazel.

**Comment by jmillikin-stripe** [comment]
Gazelle will generate the `proto_library` target, so you can depend on that proto target directly from the Envoy repository. This would let you define the C++ and Python targets from the Envoy repo.

You can also put the C++ and Python targets into a diff-formatted patch, and list it like this:
```python
go_repository(
    name = "com_github_gogo_protobuf",
    sha256 = GOGOPROTO_SHA256, 
    strip_prefix = "protobuf-" + GOGOPROTO_RELEASE, 
    url = "https://github.com/gogo/protobuf/archive/v" + GOGOPROTO_RELEASE + ".tar.gz",
    patches = ["@envoy_api//bazel:gogo_protobuf_cc_py.diff"],
)
```

I don't have a good answer for the general problem of "diamond dependency on third-party code without BUILD files". In the specific case of Go upstreams, the Gazelle tool intends to be a one-stop shop for generating BUILD and we can use it to make our lives easier here.

**Comment by cstrahan** [comment]
@htuch et al, could we re-open this? I missed the first stale bot message... but this is still a problem for me (and anyone doing something similar to what I'm working on).

**Comment by htuch** [comment]
@cstrahan reopened; do you have some sense on where we should be steering this issue? I see a lot of good discussion on the root cause above but I don't know what is actionable.

**Comment by zanes2016** [comment]
I believe we're also experiencing this issue when a third-party added a dependency on gogo/protobuf. 

```
ERROR: /root/.cache/bazel/_bazel_root/6f6133ece88806ce1513398e26791cf1/external/envoy_api/envoy/api/v2/BUILD:47:1: no such package '@com_github_gogo_protobuf//': BUILD file not found on package path and referenced by '@envoy_api//envoy/api/v2:eds_go_grpc'
ERROR: Analysis of target '//ads:ads' failed; build aborted: no such package '@com_github_gogo_protobuf//': BUILD file not found on package path
INFO: Elapsed time: 5.007s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 1 target configured)
```

Is there a work-around for this?

**Comment by cstrahan** [comment]
@zanes2016 Please report on my bazel issue here: https://github.com/bazelbuild/bazel/issues/9275

The sooner bazel project management realize this is a problem, the sooner they can fix things.
