### ISSUE TITLE
test: put test into unnamed namespace as much as possible

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#5856]
*Description*:
There is no reason tests are not in unnamed namespace unless needed by `FRIEND_TEST`, they don't need external linkage. It also saves about 10% of compiling / linking time for the test.cc and binary based on my quick experiment with GCC.

**Comment by Sai-Adarsh** [comment]
> 
> 
> _Description_:
> There is no reason tests are not in unnamed namespace unless needed by `FRIEND_TEST`, they don't need external linkage. It also saves about 10% of compiling / linking time for the test.cc and binary based on my quick experiment with GCC.

@lizan i'm interested with the issue, could you guide me through?

**Comment by lizan** [comment]
@Sai-Adarsh Thanks, I have some sample [here](https://github.com/envoyproxy/envoy/commit/6a2d2dc24c717a6497849dcb7d427c4b93a3020a), basically just put the whole test into a `namespace {` and `}` across all test files (and remove global `static` if there are), try build and test.

**Comment by solodynamo** [comment]
Seeing it inactive for a couple of weeks have opened a supporting PR for this issue.
