### ISSUE TITLE
Server State in Discovery Request

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5872]
In some cases, we would like know if Envoy is fully initialized from the management server perspective to respond. As an example, when Envoy disconnects and reconnects to a new management server(which does not yet have discovery data) as described in https://github.com/envoyproxy/envoy/issues/5168, we would like not send empty cluster load assignments. If we do it generically, we will be hit by https://github.com/envoyproxy/envoy/issues/5862 - making Envoy initialization stuck.
So we would like not to respond with empty CLAs when Envoy is fully LIVE otherwise we would send empty CLA to make envoy initialize it self.

Currently  there is no reliable way to determine if Envoy is fully initialized or it is disconnected from management server instance and reconnected to another. Version and Nonce empty ness can be one indication to figure out whether is disconnected from one instance and reconnected to another instance. But it does fully indicate that Envoy is LIVE.

Can we expose server state defined here https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v2alpha/server_info.proto#L19 in the Discovery Request? or is there any way this can be achieved with current protocol?

**Comment by htuch** [comment]
I'm trying to understand the first paragaph; you say you want to wait for Envoy to be live, but don't want to warm it? This isn't how Envoy initialization works today, so not sure how the rest of the ask here can function.

I think we should just fix #5168 without resorting to management server special sequencing, this is an Envoy-side issue.

**Comment by mattklein123** [comment]
FWIW @snowp did add init status to `/version_info` IIRC.

**Comment by ramaraochavali** [comment]
@htuch Here is my proposal in short, if server state is available in `DiscoveryRequest`

- When the request comes for `ClusterLoadAssignments`, I would check if Envoy is in `PRE_INITIALIZING` state and if yes I would just send empty CLA if discovery information is not available. So the initialization would continue. However as we are discussing about adding application level timeout #5862, if it is added - this is not required. Envoy would not be stuck with initialization even if we do not respond here.
- If the server is already LIVE, I would skip sending empty `ClusterLoadAssignments` so that existing end points wont be cleared. Whenever there is updated endpoints they will flow through normally to Envoy. If we fix #5168 (which I think we should) this handling is not required.

So looks like if we fix both #5862 and #5168 we do not need to do any special handling based on Envoy state in management server.

Do you think would it be useful to send Envoy state in any other scenarios? If not probably we can close this.

@mattklein123  yes, it was already added to `/server_info`

**Comment by mattklein123** [comment]
> Do you think would it be useful to send Envoy state in any other scenarios? If not probably we can close this.

My preference would be to close this out for now and fix the other issues until a time in which we can't solve a problem without this any other way? Basically I think we should try to keep the xDS semantics as simple as possible.

**Comment by ramaraochavali** [comment]
Makes sense. Will close this now and wait for those fixes.
