### ISSUE TITLE
Atomicity behavior of /reset_counters API  

### ISSUE THREAD

**Issue by thevks** [envoyproxy/envoy#5874]
Query on atomicity behavior of /reset_counters API  

We are using 1.8 version of envoy in our product and the integration is really doing good.
However, I need to understand the behavior of **/reset_counters** API little more. Does this API always guarantee that counters are being reset atomically - especially the cumulative counters of like 2xx, 5xx?

So in a running system if 5XX is sum of 503 and 504 counters -  is it possible that 503, 504 and 5xx counters (together in a group) are not being reset atomically?

Expectation is that at any point of time, the 5XX counter should always show correct value as the addition of 503 and 504 counters, even in case counters are being reset very frequently.

Any possibility, if this expectation goes wrong?

**Comment by mattklein123** [comment]
It's just a for loop that runs through the counters and resets them individually, so it's definitely not atomic on a global level.

**Comment by thevks** [comment]
Thanks for the response..

**Comment by thevks** [comment]
Does the **/reset_counters** API reset the shared memory or not?

**Comment by thevks** [comment]
@mattklein123 
What is the behaviour of /reset_counters API? Does it reset the whole sort of counters, even if they are not appearing (for the time being) in the context of newly created envoy process, after hot_restart?
