### ISSUE TITLE
Forwarded header in place of X-Forwarded-* headers

### ISSUE THREAD

**Issue by adityats2020** [envoyproxy/envoy#5889]
From the [docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-for), Envoy adds `X-Forwarded-` headers before forwarding the request upstream. The [RFC Spec](https://tools.ietf.org/html/rfc7239) however indicates `Forwarded` header is the standard and other `X-Forwarded-` headers are non standard.
Here is a quote from the spec.

> A common way to disclose this information is by using the non-standard header fields such as X-Forwarded-For, X-Forwarded-By, and X-Forwarded-Proto.  There are many benefits to using a standardized approach to commonly desired protocol function: not least is interoperability between implementations.  This document standardizes a header field called "Forwarded" and provides the syntax and semantics for disclosing such information.

Nginx also recognizes this header as standard: https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

Can someone clarify on why Envoy chose to use `X-Forwarded-` headers? If I am looking at an incorrect source, please point me to the correct one.

**Comment by mattklein123** [comment]
> Can someone clarify on why Envoy chose to use `X-Forwarded-` headers? If I am looking at an incorrect source, please point me to the correct one.

Because `x-forwarded-*` is very widely supported across the industry. That's not to say that we can't have a config option to us `forwarded` instead, but that's a different enhancement request.

**Comment by robd003** [comment]
Can we re-open this?
