### ISSUE TITLE
Support for retry policy per cluster

### ISSUE THREAD

**Issue by Y0Username** [envoyproxy/envoy#5891]
Support for retry policy configuration per cluster:

Right now retry policy is supported per route and it doesn't play along well with WeightedClusters.
If I want different clusters to adapt different retry policies, it's not possible with the current configuration. 

According to @htuch, when an Envoy retries a failed request, it will retry on the same cluster in the list of WeightedClusters. If the retries are going to the same cluster, retry policy per cluster config makes more sense than per route.

 Is this something that you guys are considering of adding as a feature at all?

**Comment by mattklein123** [comment]
> If the retries are going to the same cluster, retry policy per cluster config makes more sense than per route.

I'm not sure I full understand the request here. Can you clarify with an example?

**Comment by Y0Username** [comment]
Hi @mattklein123, 

Currently the retry policy is applied at the route level. If I have a WeightedCluster in the route and I want each cluster to respect a different retry policy, there's no way to do it. 

It would make sense if retry policy is configured under the cluster for following reasons:
1. When the user has multiple clusters(within a route) with different versions of the software, the user might want different retry policies for each version of the software.
2. When the envoy retries a failed request; it will retry to the same cluster instead of picking a different cluster from the list of WeightedCluster (this implicitly means that the retry policy is applied per cluster).

So the current configuration has all the clusters under a route being configured with the same retry policy. Would it be possible to move retry policy under cluster configs?

**Comment by mattklein123** [comment]
> Would it be possible to move retry policy under cluster configs?

I'm not sure this makes sense, since we still need retrie policies to be route/vhost specific. I think it would be better to consider adding override retry policies to the weighted cluster route construct if that is desired. cc @rshriram for thoughts on this.
