### ISSUE TITLE
hot-restart while management server is unstable causes 404/503 to clients

### ISSUE THREAD

**Issue by unixsurfer** [envoyproxy/envoy#5894]
*Description*:

We performed a hot-restart in envoy (running in egress mode) in order to use a different port on the management servers. The hot-restart took place across several servers at once and we received alerts from applications with an increase of  404 or 503 responses from envoy. 

We know that during the hot-restart process, the old instance stops accepting new connections and starts draining existing as soon as the new instance gets at least one response from the management server and it doesn't matter if it's a **success** or a **failure** according to https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/init.

During the restart, our management servers were overloaded and not responding on time. Moreover, some application servers couldn't connect to management servers as we didn't have firewall holes in place for the new port.

So, we ended up in a situation where the old instance was already draining connections but the new instance wasn't yet ready to serve traffic as requests for routes/clusters were failing. This situation led to an outage in our case. Envoy during normal operation is resilient to connectivity issues and outages within the management servers as it continues to serve requests using a cached copy of the xDS configuration. 

During our post-mortem process, we tried to find ways to make the hot-restart process resilient to management outages. The hot-restart process of envoy is quite complex and as a result, we couldn't come up with a solution, which doesn't require changing the internals of Envoy.

One possible way to make the hot-restart process resilient to management outage is to copy xDS configuration during the initialization phase in case requests to management servers are failing. 

We would like to hear your opinion on the aforementioned idea.

**Comment by mattklein123** [comment]
> One possible way to make the hot-restart process resilient to management outage is to copy xDS configuration during the initialization phase in case requests to management servers are failing.

This will end up being extremely complicated and potentially impossible if for example some config option has been deprecated. Unfortunately there really is no way around considering your management system a tier 0 service IMO.

**Comment by unixsurfer** [comment]
> > One possible way to make the hot-restart process resilient to management outage is to copy xDS configuration during the initialization phase in case requests to management servers are failing.
> 
> This will end up being extremely complicated and potentially impossible if for example some config option has been deprecated.

In this particular case, we didn't move to a newer version that could have rejected the config due to an option being deprecated. In case someone moves to a newer that may deprecate some options, then I **do** expect from that person to do the sensible thing to test the configuration against the newer version in a staging environment.

> Unfortunately there really is no way around considering your management system a tier 0 service IMO.

One of the major benefits of having data and control plane is the clear separation between them in regard to availability. The data plane can still operate while the control plane is unavailable. If we treat control plane as tier 0 then we break this very fundamental property of Service Mesh. I can't speak on behalf of all users of envoy in Service Mesh environments, but I can image many users don't want to lose that ability to have an operational data plane while controlplane is unavaiable.

**Comment by mattklein123** [comment]
> One of the major benefits of having data and control plane is the clear separation between them in regard to availability. The data plane can still operate while the control plane is unavailable. If we treat control plane as tier 0 then we break this very fundamental property of Service Mesh. I can't speak on behalf of all users of envoy in Service Mesh environments, but I can image many users don't want to lose that ability to have an operational data plane while controlplane is unavaiable.

The control plane is a tier 0 service in the sense that it is required to scale up / restart Envoys. If you utilize industry standard deployment processes (canary, rolling upgrade, etc.) you will not run into an issue here, and this is what we recommend. Basically, the complexity of doing what you ask is more likely to lead to an outage than using standard processes. 

If you want to build higher availability, you could consider having another sidecar, proxying the xDS API calls, and persisting them to disk (or something like that) but I very strongly recommend against doing that.

**Comment by unixsurfer** [comment]
> > One of the major benefits of having data and control plane is the clear separation between them in regard to availability. The data plane can still operate while the control plane is unavailable. If we treat control plane as tier 0 then we break this very fundamental property of Service Mesh. I can't speak on behalf of all users of envoy in Service Mesh environments, but I can image many users don't want to lose that ability to have an operational data plane while controlplane is unavaiable.
> 
> The control plane is a tier 0 service in the sense that it is required to scale up / restart Envoys.

I agree, and this issue was a very good exercise for us as we patched our controlplane in a certain way, which yielded 10x more capacity. But, we can't do have 100% uptime; even 99.99% is quite difficult to achieve. Thus, the initial request/question to make hot-restart of envoy resilient to outages in the controlplane. Envoy does that already during normal operation, so it sacrifices consistency for availability which is an acceptable trade-off for the specific scenario.

> If you utilize industry standard deployment processes (canary, rolling upgrade, etc.) you will not run into an issue here, and this is what we recommend.

I would be very much interested in knowing how you are doing rolling restarts on envoy.

> Basically, the complexity of doing what you ask is more likely to lead to an outage than using standard processes.

I trust your expertise on this but I don't quite understand your last argument as I am not very familiar with the internal of envoys. What outages do you foresee?


> If you want to build higher availability, you could consider having another sidecar, proxying the xDS API calls, and persisting them to disk (or something like that) but I very strongly recommend against doing that.

I agree that solution isn't very appealing. 

Another option, for which I would like to hear your opinion.
In Figure 3 from https://blog.envoyproxy.io/envoy-hot-restart-1d16b14555b5, we could adjust the initialization order in such way that it will do step 3(start drain) if requests for xDS are not failing, and if they do then abort the hot-restart, so the old instance remains alive.

Last but not least, I really appreciate your responses and  valuable input. Thank you very much.

**Comment by mattklein123** [comment]
> I would be very much interested in knowing how you are doing rolling restarts on envoy.

This is dependent on your provisioning system. It's no different than canary, rolling or zonal deployment of anything else.

> we could adjust the initialization order in such way that it will do step 3(start drain) if requests for xDS are not failing, and if they do then abort the hot-restart, so the old instance remains alive.

This is potentially doable, but would require a fair amount of thought, and I'm not sure it's worth the extra complexity.

**Comment by alyssawilk** [comment]
I tend to agree that if your management server is down, it'd be better to improve reliability / resiliency there, or have control plane backup like config cached on disk.

That said, not having looked at the hot restart code at all, would it be plausible make that logic pluggable?    Then if folks want to go the other route and try to make Envoy resiliant they can, without making an already complicated area of code more complicated in the main repo.

**Comment by mattklein123** [comment]
> That said, not having looked at the hot restart code at all, would it be plausible make that logic pluggable? Then if folks want to go the other route and try to make Envoy resiliant they can, without making an already complicated area of code more complicated in the main repo.

It's certainly possible, and I would be happy to review a proposal, but I think this will be a significant amount of work and my intuition tells me that it's not cost effective vs. improving the resiliency of the rest of the components in the system (deploy, management, etc.).
