### ISSUE TITLE
rq_error stat on cluster

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5905]
We are debugging a retry failure with reset. Here is what is happening
- The request is sent to Server Envoy. The local service returned 503. 
- The Server Envoy Stats `upstream_rq_5xx` is incremented.
- The Server Envoy sends back http status code `200` and gRPC status code `Unavailable`
- The Client Envoy retries the request `upstream_rq_retry` is incremented for the Cluster
- The retry fails with upstream reset. No 5xx is incremented on the Client Envoy.
- The actual client is returned with `UnAvailable` with message `upstream connect error or disconnect/reset before headers`.
 
Looking at the code in router.cc, I suspect it is getting in to this if condition. 

https://github.com/envoyproxy/envoy/blob/cdcdfa6914f88b537122ed039fd0de5f78c0f209/source/common/router/router.cc#L575

I am not able to confirm it because the host level stat is updated. AFAIK, host level stats does not go stat sinks and the Envoy in question has been restarted - so we lost the host level stats. There are no other stats on Client I could use to confirm why the retry failed - any other stats could help me figure that out?

Is there a specific reason why this stat is only incremented at host level but not at cluster level?

**Comment by mattklein123** [comment]
> Is there a specific reason why this stat is only incremented at host level but not at cluster level?

Probably just an oversight.

**Comment by ramaraochavali** [comment]
Ok. I will fix it to add it to the cluster as well then.

**Comment by ramaraochavali** [comment]
/ assign ramaraochavali
