### ISSUE TITLE
stats_flush_interval ignored

### ISSUE THREAD

**Issue by fkowal** [envoyproxy/envoy#5935]
Hi

When envoy loses connection to the control-plane it starts sending 2 metrics every second:

envoy.test-service.global.XX.test-service_12345.cluster.envoy-control-xds.upstream_cx_length_ms:2|ms
envoy.test-service.global.XX.test-service_12345.cluster.envoy-control-xds.upstream_cx_connect_ms:1|ms

It stops respecting the [status_flush_interval](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/bootstrap/v2/bootstrap.proto.html?highlight=stats_flush_interval)

**Comment by mattklein123** [comment]
For statsd (which I assume you are using), histograms are flushed immediately.
