### ISSUE TITLE
Envoy build fails unable to load package

### ISSUE THREAD

**Issue by krishamb** [envoyproxy/envoy#5937]
**Issue Template**

*Title*: Unable to load package for '@com_lyft_protoc_gen_validate//bazel:pgv_proto_library.bzl' during bazel build

*Description*:

I am getting the following errors repeatedly for multiple packages during bazel build. I did bazel sync and it resolved few but still getting the following. Can we have a clean working scripts for dependencies ?

ERROR: Skipping '//source/exe:envoy-static': error loading package 'source/exe': in /source/bazel/envoy_build_system.bzl: in /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/envoy_api/bazel/api_build_system.bzl: Unable to load package for '@com_lyft_protoc_gen_validate//bazel:pgv_proto_library.bzl': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: error loading package 'source/exe': in /source/bazel/envoy_build_system.bzl: in /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/envoy_api/bazel/api_build_system.bzl: Unable to load package for '@com_lyft_protoc_gen_validate//bazel:pgv_proto_library.bzl': BUILD file not found on package path
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.

*Repro steps*:
  ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
 docker build container for Ubuntu in darwin
Os Version:-
 Darwin C02XN3ZZJGH6 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

*output*
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
No remote cache bucket is set, skipping setup remote cache.
ENVOY_SRCDIR=/source
HEAD is now at 6c0625c... integration: make test use 3-arg base class ctor (#69)
building using 6 CPUs
clang/clang++ toolchain configured
bazel fastbuild build with tests...
Building...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/command.profile'
INFO: Invocation ID: 15f8a4bd-9656-45a7-b4de-3722bc4a7d41
ERROR: Skipping '//source/exe:envoy-static': error loading package 'source/exe': in /source/bazel/envoy_build_system.bzl: in /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/envoy_api/bazel/api_build_system.bzl: Unable to load package for '@com_lyft_protoc_gen_validate//bazel:pgv_proto_library.bzl': BUILD file not found on package path
WARNING: Target pattern parsing failed.
ERROR: error loading package 'source/exe': in /source/bazel/envoy_build_system.bzl: in /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/envoy_api/bazel/api_build_system.bzl: Unable to load package for '@com_lyft_protoc_gen_validate//bazel:pgv_proto_library.bzl': BUILD file not found on package path
INFO: Elapsed time: 6.262s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: source/exe

**Comment by pitiwari** [comment]
i am also hitting the same issue, we just moved from 1.7 to 1.9

**Comment by krishamb** [comment]
Can someone guide us on this package issue ? Greatly appreciate your help.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pitiwari** [comment]
was able to resolve it by editing the WORKSPACE file

**Comment by krishamb** [comment]
Can you share what you edited and where is the file ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pitiwari** [comment]
below is my workspace file. I removed some lines to make it work

workspace(name = "envoy")

local_repository(
    name = "envoy",
    path = "envoy",
)

load("@envoy//bazel:repositories.bzl", "envoy_dependencies")
load("@envoy//bazel:cc_configure.bzl", "cc_configure")

envoy_dependencies()
cc_configure()

load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
api_dependencies()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
