### ISSUE TITLE
Support for X-Forwarded-Host header

### ISSUE THREAD

**Issue by pedro-tramontin** [envoyproxy/envoy#5940]
*Title*: *Support for X-Forwarded-Host header*

*Description*:
Today envoy does not seem to forward the original host in a X-Forwarded-Host header, it just rewrites the original one and apparently there is no way to get the original host back again.
I found a reference for this header in the source code but it seems it is not being used anywhere else: (https://github.com/envoyproxy/envoy/blob/bbf5674c2c9a901ec4e964e4dd1d845516e672b2/source/common/http/headers.h#L71)

**Comment by pedro-tramontin** [comment]
Hello, I would like to try to add this feature and need some guidance.
Does it make sense to check for the options host_rewrite and auto_host_rewrite and copy the original host to X-Forwarded-Host header when the change is about to happen?
Should there be any configuration that enable/disable this header?

**Comment by mattklein123** [comment]
@pedro-tramontin SGTM. I'm not sure if we want to config guard it or not. On one hand, I think it would be OK to not config guard if we only set when a host mutation happens as you point out. On the other hand, it's possible that upstreams are not expecting us to set it and we might break them. @envoyproxy/maintainers any thoughts?

**Comment by yanniszark** [comment]
Hi all!
This is a feature we (Arrikto) would like to have in Envoy, as it's something we rely upon to build correct URLs even with multiple proxies in the request's journey.

I am really unfamiliar with advanced C++ code, but I read through the docs and tried to take a stab at it.

According to [MDN's definition for X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host):

>The X-Forwarded-Host (XFH) header is a de-facto standard header for identifying the original host requested by the client in the Host HTTP request header.

A simple example to illustrate:

```

 +----------+
 |          |
 |   App    |
 |          |
 +----------+
      ^ Host: app.namespace.svc.cluster.local
      | X-Forwarded-Host: example.com
 +----------+
 |          |
 |  Envoy   |
 |          |
 +----------+
      ^
      | Host:example.com
      |
      |
     User

```

So the algorithm for this functionality is:

If request host/authority is changed when the request is proxied, set x-forwarded-host to old x-forwarded host + old host:
`x-forwarded-host = append(x-forwarded-host, host)`

After reading through the Envoy architecture, I see that HTTP Connection Manager converts bytes to HTTP and passes traffic through an HTTP Filter Chain.
The Router HTTP Filter should be the one responsible for making the decision to change a request's host/authority, so I am looking into it.

After reading the architecture documents and comparing it with the code structure, I was very happy to find out that things where very nicely organized (kudos to maintainers) and I managed to make some progress.

In particular, this part seems interesting:
https://github.com/envoyproxy/envoy/blob/1a8fac91951d4a3bc3f7fcc96f5adc86a8dab6fb/source/common/router/router.cc#L524

What I plan to do is:
1. Parse request's host/authority.
2. Get corresponding cluster for route.
3. Get cluster's hostname.
4. If cluster's hostname is different from request's host/authority, add the x-forwarded-for header.

@pedro-tramontin @mattklein123 any tips / directions would be highly welcome.
This is very new territory for me :smile:

**Comment by mattklein123** [comment]
IMO we don't need to do any parsing here as we pass through the host unchanged in almost all cases. We only need to (optionally) set the header when we do one of the header mutation functions?

**Comment by lambdai** [comment]
@pedro-tramontin (since you are assigned) and @arun-vasudev (since you are the author of the latest PR) Are you still working on this?
Any update?

**Comment by arun-vasudev** [comment]
I will address the review comments and upload a new patch by April 18. @lambdai. I had lost track of this!

**Comment by blained3** [comment]
@arun-vasudev Has the patch been released?

**Comment by tbarrella** [comment]
Hi @arun-vasudev, do you still intend to work on this?

**Comment by arun-vasudev** [comment]
Hi @tbarrella, I will send out the new patch in a day or so. Was busy at work.

**Comment by Ido-Itz** [comment]
Hi folks. I was wondering if this is still planned. Any new updates on this topic?
Really looking forward to this feature

**Comment by arun-vasudev** [comment]
I am working on it again!
