### ISSUE TITLE
Draft PRs: use github's new draft PR feature to reduce CI load

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#5957]
*Draft PRs*: *use github's new draft PR feature to reduce CI load*

*Description*:
Github introduced [Draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/) as a way to create PRs that are a WIP. The maintainers were wondering if this could be used as a heuristic by repo kitteh to reduce the CI load on open PRs. For example, as long as the PR is a draft PR we could run no/or a subset of CI jobs.

**Comment by itayd** [comment]
There is an SOW item where we always launch a minimal set of CI, and upon requirement (a-la-🔬) , launch the rest.

IIUC, you want to add another layer - running an even more minimal set of tests on drafts?

**Comment by mattklein123** [comment]
> IIUC, you want to add another layer - running an even more minimal set of tests on drafts?

Yeah exactly, if possible.

**Comment by itayd** [comment]
I think it is - there is a minimal set of tests that will always run, then if a PR is non-draft more tests are run, and if 🔬 , all tests are run. I consider this part of the SOW.

**Comment by itayd** [comment]
That said, this only can be done if GitHub has any indication that a PR is draft in the API.

**Comment by itayd** [comment]
I'm working on it
