### ISSUE TITLE
Local Bazel builds with libc++ are broken.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#5966]
Per discussion in https://github.com/envoyproxy/envoy/pull/5875#discussion_r256319464, local Bazel builds with `--config libc++` are broken since https://github.com/envoyproxy/envoy/pull/5875, though they seem to work fine on the CI.

cc @htuch @lizan

**Comment by lizan** [comment]
@PiotrSikora what error are you seeing?

**Comment by PiotrSikora** [comment]
```
/very/long/file/path.h: fatal error: 'string' file not found
#include <string>
```
when building dependencies, i.e. it seems that c++ default includes are not included, somehow.

You should be able reproduce this yourself with `--config libc++` (and to rule out that this is an issue with my setup... but it works fine if I revert the offending PR).

**Comment by lizan** [comment]
It doesn't break on my env:
```
$ bazel-bin/source/exe/envoy-static --version

bazel-bin/source/exe/envoy-static  version: 80272535b9ba38027a1280af5c4daf766cea590e/1.10.0-dev/Clean/DEBUG/BoringSSL

$ ldd bazel-bin/source/exe/envoy-static
        linux-vdso.so.1 (0x00007ffe4d7b6000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f745592a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7455726000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7455509000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7455205000)
        libc++.so.1 => /usr/lib/x86_64-linux-gnu/libc++.so.1 (0x00007f7454f41000)
        libc++abi.so.1 => /usr/lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007f7454d0d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7454af6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7454757000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7455b32000)
```

**Comment by PiotrSikora** [comment]
What's your env?

```
$ cat /etc/debian_version
9.7
```
```
$ sudo apt-get install -y clang-7 libc++-7-dev libc++abi-7-dev
...
```
```
$ export CC=clang-7
$ export CXX=clang++-7
$ env | grep ^C
CC=clang-7
CXX=clang++-7
```
```
$ bazel clean --expunge
$ bazel shutdown
$ bazel version
...
Build label: 0.22.0
...
```
```
$ bazel build --config libc++ //source/...
...
In file included from external/com_google_absl/absl/numeric/int128.cc:15:
external/com_google_absl/absl/numeric/int128.h:28:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
```

Am I missing anything? As you can see, there are no compiler flags in my env, and I commented out everything in `$HOME/.bazelrc`, so I don't have any custom flags nor cache there either.

**Comment by lizan** [comment]
Interesting, with
```
$ export CC=clang-7
$ export CXX=clang++-7
```

I can reproduce:
```
In file included from external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_generator.cc:35:
external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_generator.h:40:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
```

With:
```
$ export CC=clang
$ export CXX=clang++
$ export PATH=/usr/lib/llvm-7/bin:$PATH
```

It doesn't break.

**Comment by PiotrSikora** [comment]
I can reproduce with and without `$PATH` (I had it before, but removed it to minimize steps required to reproduce).

Did you `bazel clean --expunge` and disable your Bazel caches? Perhaps something keyed on `$PATH` in still cached in your env?

**Comment by PiotrSikora** [comment]
Oh, wait, I didn't notice the `clang` vs `clang-7` change. Let me test that just to make sure.

**Comment by lizan** [comment]
Yes `clang` vs `clang-7` seems make the difference, I do set PATH to `/usr/lib/llvm-7/bin` in both case.

**Comment by PiotrSikora** [comment]
OK, this is bizarre, but `CC=clang CXX=clang++` works, and `CC=clang-7 CXX=clang++-7` doesn't. I'll send PR to fix that.

**Comment by PiotrSikora** [comment]
(that == instructions)

Thanks for the help, @lizan!
