### ISSUE TITLE
Locality weighting in Maglev inconsistent with other LBs

### ISSUE THREAD

**Issue by mergeconflict** [envoyproxy/envoy#5982]
The way Maglev currently implements weighting for any given host and locality is: `effective_weight = host_weight * locality_weight`. This is nice and simple, but it's inconsistent with how the other LBs implement locality weighting. A simple example:

* Locality _A_: locality_weight = 1
     * contains 100 hosts, each with host_weight = 1
* Locality _B_: locality_weight = 1
    * contains 50 hosts, each with host_weight = 1

The way Maglev figures it, the effective weight for all hosts is 1: they all get equal traffic. But the way all other LBs figure it, and what users expect (per [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/locality_weight), assuming healthy hosts) is that _A_ should be getting the same traffic as _B_, no matter how many hosts happen to be in each locality: consequently, each of the 50 hosts in _B_ should be taking twice as much traffic as each of the 100 hosts in _A_.

Judging by https://github.com/envoyproxy/envoy/issues/2725#issuecomment-370586299, we meant to do this at some point, but didn't.

The correct math is to sum the locality weights, and sum the host weights within each locality, to get the right proportions. For example, given:

* Locality _A_: locality_weight = 2
    * Host _a_: host_weight = 3
    * Host _b_: host_weight = 5
* Locality _B_: locality_weight = 7
    * Host _c_: host_weight = 11
    * Host _d_: host_weight = 13

The sum of locality weights = 9, the sum of host weights in _A_ is 8, and the sum of host weights in _B_ is 24, which gives us effective weights:

* Host _a_: (2/9) * (3/8) ~= .083
* Host _b_: (2/9) * (5/8) ~= .139
* Host _c_: (7/9) * (11/24) ~= .356
* Host _d_: (7/9) * (13/24) ~= .421

**Comment by htuch** [comment]
Yeah, I think this is legit broken; @snowp do you have any thoughts?

**Comment by mattklein123** [comment]
I suspect no one has ever used weighted maglev in production but I'm not sure.

**Comment by snowp** [comment]
Yeah I agree, this seems like a bug. I assume Maglev doesn't allow for the tiered host selection we do for the other LBs (priority -> locality -> host), but we should still make sure the overall host weighting is consistent when using locality weighting.

**Comment by mergeconflict** [comment]
Cool, I'll work on this. I'm actually doing it for RingHashLB first, and I plan fix it in Maglev after.

**Comment by htuch** [comment]
There's two ways we could do it with Maglev/Ring hash LB. We could either use two tables, doubling memory use, but allowing more granular weighting for a given ring size, or what we do today, a single table with an effective weight function that expresses locality weight correctly. I think the latter is a more reasonable evolution of what we have, but maybe one day someone would prefer the two table solution.

What we can't do is have an EDF WRR scheduler for the first-level locality pick, since this needs to be deterministic and hash based.
