### ISSUE TITLE
JWT Verification by the public key in client certificate

### ISSUE THREAD

**Issue by bnlcnd** [envoyproxy/envoy#5990]
*Title*: *How Envoy support the JWT (for signature) verification via the client public key in the cert.*

*Description*:
>I am trying to set up the Envoy to do the JWT verification. The JWT presents a JWS. From my understanding, a signature should be verified by the server via the public key of the client who sent the request. A normal process would be:
1) the client use its private key to sign the JWS header and payload
2) the client send the request with the JWT
3) the server somehow get the certificate of the client and extract the public key
4) the server use the public key to verify the signature.

But the documentations about the JWT is very limited. There is no any example about how to make the yaml config to allow the Envoy to extract the client public key and use it. It seems that the Envoy can only get the key from JWKS service or use a inline string. Using a inline string is very confusing to me. How can the Envoy use just one pre-defined JWK to verify a client's signature? The Envoy shouldn't know what certificate the client will present.

So, my question will be:
1) whether and how Envoy support the mutrual TLS which allow the client to present the certificate.
2) how to verify the client certificate in Envoy. without a CA, how Envoy define a trusted key store or certificate store to verify the certificate of the client
3) how to setup Envoy to extract the client certificate as the public key to verify the JWS in the JWT
4) if I have to use the remote JWKS, how to link a remote JWK with the client who is sending the request for verification

**Comment by qiwzhang** [comment]
@bnlcnd I would recommend you to read auth0 and JWT related documents first.  I believe many of your questions can be answered by them.  For the questions on how to use JWT filter, it has some [examples](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/jwt_authn_filter.html?highlight=jwt#remote-jwks-config-example), they will help.
