### ISSUE TITLE
grpc-json transcoder: Large response triggers internal server error

### ISSUE THREAD

**Issue by warhammerkid** [envoyproxy/envoy#6004]
*Title*: *Large gRPC responses converted to JSON get an internal server error response*

*Description*:
>I'm using the grpc-json transcoder filter and when I attempt to send a proto response which when serialized is probably ~2.5 MB, I get a 200 response with a `grpc-message` of `Internal Server Error` and the `rs_too_large` stat counter gets incremented. I changed the `per_connection_buffer_limit_bytes` config for the downstream cluster to 50 MB, but that doesn't appear to fix the issue.

Is there a config option that can raise the buffer high watermark in this case so that we can raise the response limit?

**Comment by mattklein123** [comment]
Related to https://github.com/envoyproxy/envoy/issues/5012.

IIRC if you have an HTTP/2 downstream you might need to tune the per stream buffer, but I think this defaults to something really big. I agree we need more documentation on how to configure this properly. cc @lizan @alyssawilk who might have quicker thoughts without looking through the code.

**Comment by lizan** [comment]
@warhammerkid what is the `grpc-status`? Do you use streaming?

**Comment by warhammerkid** [comment]
I can't believe I missed the fact that `per_connection_buffer_limit_bytes` can be set on the cluster **AND** the listener. Moving my limit setting from the downstream cluster to the listener fixes my issue. If I throw in a buffer filter is it possible to use that to lower the request limit for DoS protection while still allowing the server response size to be much larger? Are there any other consequences of raising the listener buffer limit?

@lizan I'm not currently using streaming and the `grpc-status` was a 2.

**Comment by alyssawilk** [comment]
AFIK the DoS potential is pretty much it.  It affects a few different buffers (listener write buffer, HCM request / response buffers, etc.) but a buffer filter should mitigate the DoS opportunities as you say.

Docced up a bit in #6059 - please take a look and let me know if I can make that more clear and/or helpful

**Comment by warhammerkid** [comment]
Thanks so much for the help on this question!
