### ISSUE TITLE
http: Expose request/response total bytes in encoder/decoder callbacks

### ISSUE THREAD

**Issue by fcfort** [envoyproxy/envoy#6006]
I am attempting to implement a feature to record total request or response size for a given stream, that is not just body size or header size. I would like to be able to access that data in filters (via `streamInfo()`), in the same way that `StreamInfo` currently records body bytes via `bytesSent()` and `bytesReceived()` (see code [here](https://github.com/envoyproxy/envoy/blob/14bea3b8b3bfafc5149244f41b12c4eb1e7d2bce/source/common/http/http2/codec_impl.cc#L500) and [here](https://github.com/envoyproxy/envoy/blob/14bea3b8b3bfafc5149244f41b12c4eb1e7d2bce/source/common/http/conn_manager_impl.cc#L803)). 

I'm at somewhat of an impasse wrt how to implement this. I don't think there is a great interface at the moment between `http2/codec_impl` and `conn_manager_impl` that will allow me to accomplish this. 

I think we'd need to add some kind of call into `ConnectionManagerImpl::ActiveStream` that would allow us to receive the frame's size in bytes, but I'm having difficult figuring out how that fits into `ActiveStream`'s behavior.

My only thought so far to add a pair of methods in `StreamDecoder` like `encode` and `decode` that would be called from `http2/codec_impl.cc's ConnectionImpl::onFrameReceived` method (and the H1 equivalent) and provide the length of the data. The name feels very general though, and its behavior (recording stats into `StreamInfo`) would not make a lot of sense for our current use case.

Any help on how to approach this? Or alternative ways of accomplishing this?

**Comment by mattklein123** [comment]
I haven't though it through in detail, but I would probably add some new type of opt-in stream callbacks that are called with full framing data. You could implement this for HTTP/1 also pretty easily. Then the callback can do whatever it wants with the explicit size information (I assume you are trying to use this from a filter?).

**Comment by fcfort** [comment]
Right yeah, I'm trying to use the data recorded in the `StreamInfo` object in a filter.

What do you mean when you say "opt-in stream callbacks"? 

Basically what I'd like is some callbacks for the active stream that is passed from `conn_manager_impl` to the H1/H2 `codec_impl`s so that when the codecs see a chunk of data they directly pass that chunk of data (but really I just need the size of that data) into the callback, which is then executed in the context of the active stream so that it can make calls into its `StreamInfo` object.

Is that more or less what you were suggesting?

**Comment by mattklein123** [comment]
> Is that more or less what you were suggesting?

Basically, yes. I think the question is whether you really need it to go into stream info, or you just need the callback in your filter? I'm not crazy about making everyone pay this extra computation/storage tax since I think almost no one will care about it.

**Comment by fcfort** [comment]
Well really I just need it in the filter. My idea was to make something analogous to `StreamInfo.bytesReceived` and `StreamInfo.bytesSent` for both headers and the entire request or response.

The reason I thought it might be useful is that other clients of Envoy might also want to access the total size of the request/response or the size of the headers in the same way that clients can get the size of the body in filters via `bytesReceived`/`bytesSent`.

If you don't think that's the case, I'm happy to only implement it the via the filters and not via `StreamInfo`, but I'm not sure what such a solution would look like.

**Comment by mattklein123** [comment]
> If you don't think that's the case, I'm happy to only implement it the via the filters and not via `StreamInfo`, but I'm not sure what such a solution would look like.

I think either way you are going to have to add a new codec callback that can give you frame size information. Then you can either wire that from the HCM and stick the result in stream info, or you can allow access to that information from opt-in filter callbacks. I don't have a super strong opinion either way.
