### ISSUE TITLE
Continue with Listener creation even if one listener in the list fails

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#6010]
This is similar to what has been done for CDS here https://github.com/envoyproxy/envoy/pull/5806 but for LDS. If a listener fails for some reason, we would stop the listener creation and throw exception, half of the listeners would have been created by that time. I think it makes sense to continue with other listeners in the list.

Thoughts?

**Comment by mattklein123** [comment]
@ramaraochavali I agree we should be consistent here.

**Comment by ramaraochavali** [comment]
Ok. Cool. Will fix this.
