### ISSUE TITLE
[feature request]OutlierDetection: reset or cap number of times host has been ejected.

### ISSUE THREAD

**Issue by difro** [envoyproxy/envoy#6016]
The outlier ejection algorithm says following:
https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/outlier#ejection-algorithm

> The number of milliseconds is equal to the outlier_detection.base_ejection_time_ms value multiplied by the number of times the host has been ejected. This causes hosts to get ejected for longer and longer periods if they continue to fail.

But currently there is no way to reset or cap this "number of times the host has been rejected" count.
Once the host has been confirmed healthy again, I'd like to manually mark it as healthy, so that I do not have to wait ever-growing seconds/minutes/hours until the host gets unejected.

Or maybe there can be some configurarable setting(outlier_detection.max_ejection_time ?) where one can set maximum number of m-seconds the host can be ejected for ?

**Comment by difro** [comment]
I'd like to tackle this, by adding ```outlier_detection.max_ejection_time``` (maximum time that a host will be ejected for. Default is 0 which means no maximum limit)

Can anyone tag this, so it doesn't get stale..

**Comment by mattklein123** [comment]
@difro sgtm

**Comment by Taiters** [comment]
Hey, is this currently being worked on? I'd be happy to pick this up if not.

Another useful setting here would be a duration before resetting back to the base ejection time. E.g. If 24hrs have passed since the last ejection for a host, return to the base_ejection time (Essentially resetting `num_ejections`)

**Comment by difro** [comment]
@Taiters ah. sorry couldnt find time and never finished the patch and forgot about it.  It's all yours.  Your suggestion sounds good to me.
