### ISSUE TITLE
mysql_integration_test flakes

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#6051]
IpVersions/MySQLIntegrationTest.MySQLUnitTestMultiClientsLoop/0 failure observed on ASAN

test/extensions/filters/network/mysql_proxy/mysql_integration_test.cc:192: Failure
Expected equality of these values:
  counter
    Which is: 6
  CLIENT_NUM
    Which is: 10

@rshriram @venilnoronha could one of you see if you can repro and deflake?

I suspect you may need the equivalent of waitForCounterEq

https://github.com/envoyproxy/envoy/tree/master/test/integration#reproducing-test-flakes may help

**Comment by alyssawilk** [comment]
Also on  compile_time_options https://circleci.com/gh/envoyproxy/envoy/171624

**Comment by venilnoronha** [comment]
@alyssawilk thanks for fixing this!
