### ISSUE TITLE
single cluster with dynamic endpoints

### ISSUE THREAD

**Issue by jcr010910** [envoyproxy/envoy#6076]
@zuercher @PiotrSikora 

how can i create single cluster with different endpoints based on route URL?

using ORIGINAL_DST with x-envoy-original-dst-host is working fine but i want to get the upstream endpoint **without** modifying iptable.

looking for **single** cluster to handle both requests:
http://local.envoy/endpoint1/foo --> forward to upstream endpoint1 (192.168.1.1:80)
http://local.envoy/endpoint2/foo --> forward to upstream endpoint2 (192.168.1.2:80)

**Comment by ramaraochavali** [comment]
When you use `x-envoy-original-dst-host`, you do not have to modify iptables. You just have to set the ip address of the server in this header

**Comment by jcr010910** [comment]
> When you use `x-envoy-original-dst-host`, you do not have to modify iptables. You just have to set the ip address of the server in this header

you are right. thank you!

now, is there a way now to convert `http://local.envoy/endpoint1/foo` to `x-envoy-original-dst-host=endpoint1`

**Comment by ramaraochavali** [comment]
No. It expects IP address.

**Comment by jcr010910** [comment]
does it mean I can convert `http://local.envoy/192.168.1.1/foo` to `x-envoy-original-dst-host=192.168.1.1`
I'm thinking of use request_headers_to_add with key=x-envoy-original-dst-host but how can I pass the IP address as the value?

**Comment by ramaraochavali** [comment]
See this example https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/original_dst#original-destination-host-request-header

**Comment by jcr010910** [comment]
that link says: "For example if a request has to be routed to a host with IP address 10.195.16.237 at port 8888, the request header value should be set as 10.195.16.237:8888."

but in my case, the IP address is unknown to me, it may be `http://local.envoy/192.168.1.1/foo` or `http://local.envoy/192.168.1.2/foo` (may be different IPs)

**Comment by ramaraochavali** [comment]
Sorry for the delay here. If you do not know IP address and port upfront you can not use `x-envoy-original-dst-host` header. Probably I am not understanding your use case better, can you please explain a bit?

**Comment by jcr010910** [comment]
@ramaraochavali 

In front-proxy example comes with envoy, it has 3 envoy instances where the front-envoy forwards the request to either `service1 `cluster or `service2 `cluster. it's simple and clear.

In my case, I will have about 100  services (`service1`, `service2`, `service3 `, ...etc) and envoy sidecar will be installed for each service. I'm looking for a way to call these services from front-envoy without creating a new cluster for each service in the front-envoy config file. Instead if the url has `service1` it will use `service1` as upstream but if it has `service2` in the url, it forwards the call to service2 instead.

Thanks in advance!

**Comment by binpatel31** [comment]
@jcr010910 can you share the example if you were able to forward request dynamically as you expected?
