### ISSUE TITLE
user defined variables in config file

### ISSUE THREAD

**Issue by jcr010910** [envoyproxy/envoy#6077]
@zuercher @PiotrSikora 

we can use %START_TIME% variable to reference the request start time.
can i create my own variables in yaml config and reference them in the same manner?
ex: %environment%

**Comment by davidnarayan** [comment]
As far as I know there isn't a way to create user defined variables in standard YAML. However, you could use something like [jsonnet](https://jsonnet.org) to generate templates and configs with user defined variables.
