### ISSUE TITLE
python formatter should enforce consistency of quotes

### ISSUE THREAD

**Issue by dprotaso** [envoyproxy/envoy#6098]
*Title*: 
python formatter should enforce consistency of quotes

*Description*:
The python formatter should enforce consistent use of either single or double quotes for strings.

*Relevant Links*:
Formatter didn't catch it here: https://github.com/envoyproxy/envoy/pull/6049#discussion_r260445208

**Comment by Frodox** [comment]
bump

**Comment by dprotaso** [comment]
Bump

**Comment by Frodox** [comment]
Bump
