### ISSUE TITLE
Update documentation to include Redis proxy hashtagging support

### ISSUE THREAD

**Issue by szabado** [envoyproxy/envoy#6112]
*Title*: Update documentation to include Redis proxy hashtagging support

*Description*:
The Envoy docs say that Hash Tagging is not supported for the Redis proxy, but they seem to have been added by #5623, unless I'm mistaken? 

I haven't dived into the PR to figure out how to use it; some documentation would be great if possible?  If they're not ready for use or I'm just missing something that'd also be good to know.

*Relevant Links*:
[The docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis)

**Comment by mattklein123** [comment]
cc @maximebedard I think this is just a doc bug.
