### ISSUE TITLE
add per-cluster histograms with remaining timeout budget

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#6122]
Since timeouts are dynamic (e.g. controllable via header values), it is difficult to observe how close requests are to hitting the timeout in production.

A histogram of remaining timeout budget would allow the user to identify latencies that are trending towards the timeout cliff as well as identify poorly tuned timeouts.

Likely a percentage histogram would be the most useful stat, i.e. p95 of requests to upstream are within 80% of their timeout budget.

Also see [#6121: add computed-timeout header](https://github.com/envoyproxy/envoy/issues/6121).

**Comment by gumpt** [comment]
I'm working on this right now, will have a patch shortly.
