### ISSUE TITLE
IpVersions/SslTapIntegrationTest tests flaky

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#6127]
Looks like we had about 7 CI failures overnight, and when I spot checked half they were all the ssl_integration_test

Two example failures from 2 different runs:

https://circleci.com/:vcs_type/organizations/:org/settings[ RUN      ] IpVersions/SslTapIntegrationTest.RequestWithJsonBodyAsString/IPv4
unknown file: Failure
C++ exception with description "Unable to parse JSON as proto (INVALID_ARGUMENT:Unexpected end of string. Expected a value.

^): " thrown in the test body.
[  FAILED  ] IpVersions/SslTapIntegrationTest.RequestWithJsonBodyAsString/IPv4, where GetParam() = 4-byte object <00-00 00-00> (298 ms)

[ RUN      ] IpVersions/SslTapIntegrationTest.TruncationWithMultipleDataFrames/IPv4
test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc:505: Failure
Expected equality of these values:
  trace.socket_buffered_trace().events().size()
    Which is: 0
  2
[  FAILED  ] IpVersions/SslTapIntegrationTest.TruncationWithMultipleDataFrames/IPv4, where GetParam() = 4-byte object <00-00 00-00> (109 ms)

**Comment by alyssawilk** [comment]
Oh sweet, fix in flight already.   Huzzah!

**Comment by dnoe** [comment]
Interestingly enough, I am seeing this flake occur at a higher volume in the Google imported Envoy. There, we are running only the IPv6 version of this test. With open source upstream Envoy a run of 1000 tests had 15 failures. My 1000 runs internally was failing more than a quarter of the time. Most of the failures for IpVersions/SslTapIntegrationTest.TruncationWithMultipleDataFrames/IPv6 are:

```
third_party/envoy/src/test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc:505 Expected equality of these values:   trace.socket_buffered_trace().events().size()     Which is: 0   2
--
```

For IpVersions/SslTapIntegrationTest.TwoRequestsWithBinaryProto/IPv6 the typical failure case looks like:

```
third_party/envoy/src/test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc:458
Expected equality of these values:
  second_id
    Which is: 163
  trace.socket_buffered_trace().connection().id()
    Which is: 0
third_party/envoy/src/test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc:459
Expected: (trace.socket_buffered_trace().events().size()) >= (2), actual: 0 vs 2
```

**Comment by dnoe** [comment]
With these two tests disabled I ran 1000 tests successfully, but with a 5000 test run there are a few more aborts which correspond to the other flake mentioned above:

```
[ RUN      ] IpVersions/SslTapIntegrationTest.RequestWithJsonBodyAsString/IPv6
Unhandled exception:
    @     0x557fc0e89e46  Envoy::StackTrace::terminateHandler()
    @     0x557fc1bc0bc6  __cxxabiv1::__terminate()
    @     0x557fc1bc0bf3  std::terminate()
    @     0x557fc1bc0cdf  __cxa_throw
    @     0x557fc13e82e5  Envoy::MessageUtil::loadFromJsonEx()
    @     0x557fc13e818f  Envoy::MessageUtil::loadFromJson()
    @     0x557fc13e8b38  Envoy::MessageUtil::loadFromFile()
    @     0x557fbd5d56a8  Envoy::Ssl::SslTapIntegrationTest_RequestWithJsonBodyAsString_Test::TestBody()
    @     0x557fc1a0a28e  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x557fc19fdb52  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x557fc19ef103  testing::Test::Run()
    @     0x557fc19ef888  testing::TestInfo::Run()
    @     0x557fc19efe03  testing::TestSuite::Run()
    @     0x557fc19f856a  testing::internal::UnitTestImpl::RunAllTests()
    @     0x557fc1a0d0ae  testing::internal::HandleSehExceptionsInMethodIfSupported<>()
    @     0x557fc19ff722  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x557fc19f828a  testing::UnitTest::Run()
    @     0x557fc0e89fa1  RUN_ALL_TESTS()
    @     0x557fc0e89d9b  Envoy::TestRunner::RunTests()
    @     0x557fc0e89580  main
    @     0x7f2951977bbd  __libc_start_main
    @     0x557fbd5cc029  _start
terminate called after throwing an instance of 'Envoy::EnvoyException'
  what():  Unable to parse JSON as proto (generic::invalid_argument: Unexpected end of string. Expected a value.

^): 
```

3/5000, so this one is quite rare:

`integration:ssl_integration_test FAILED in 3 out of 5000 in 40.3s`

**Comment by dnoe** [comment]
10000 runs pass with all three of these tests disabled, so that's the extent of the flaky ones.

**Comment by mattklein123** [comment]
This is the diff that fixes this. I will work on getting the larger PR merged this morning unless we want to only do a PR with this fix:

https://github.com/envoyproxy/envoy/pull/6105/commits/27cb0bc9f660db62f00ef3f0ba6496d81735bba6

**Comment by dnoe** [comment]
I tried out applying just that fix internally was able to do 10000 runs with no issues. So that fix looks great.

If you're able to get the larger PR merged in the next few hours I'm inclined to wait, otherwise it's probably worth doing a PR with just that fix ASAP.

**Comment by mattklein123** [comment]
@dnoe IMO the larger PR is ready to go, if there are more substantial comments from @lizan and @htuch I will split it out. Hopefully they can review soon.
