### ISSUE TITLE
Add names and alias to resource

### ISSUE THREAD

**Issue by brian-avery** [envoyproxy/envoy#6128]
*Title*: *Add names and alias to resource*

*Description*:
In xDS, every resource has a name that’s used to identify the resource. Currently, this resource name is implemented in the individual protocol i.e. VirtualHost, RouteConfig, Listener, etc. I propose that we add a resource name to the Resource message in order to create a common place for the resource names passed in the xDS protocol. In designing the virtual host discovery service, we’ve also found that there is a potential for aliases to the names of resources. In the case of the virtual host discovery service, each of the domains constitutes a separate alias.

To handle these cases, I propose extending the message Resource to match the following: 

message Resource {
  // The resource level version. It allows xDS to track the state of individual
  // resources.
  string version = 1;

  // The resource being tracked.
  google.protobuf.Any resource = 2;

  //The name of the resource being tracked
  string name = 3;

  //Aliases of the resource name
  repeated string aliases = 4;
}

[optional *Relevant Links*:]

**Comment by brian-avery** [comment]
@htuch @dmitri-d

**Comment by htuch** [comment]
I think this is reasonable. What I think makes sense is to file a PR and update https://github.com/envoyproxy/envoy/blob/master/api/XDS_PROTOCOL.md#incremental-xds with this (or some new section on aliases). In particular, I'd like to explicitly describe how resources can be subscribed and unsubscribed to via aliases.

**Comment by htuch** [comment]
FWIW, `name` is introduced in https://github.com/envoyproxy/envoy/pull/5519 and is likely to land soon.

**Comment by brian-avery** [comment]
Thanks Harvey
