### ISSUE TITLE
asan test timeout

### ISSUE THREAD

**Issue by dprotaso** [envoyproxy/envoy#6131]
See: https://circleci.com/gh/envoyproxy/envoy/174482

I wonder if this is flakey?
> //test/extensions/filters/network/mysql_proxy:mysql_integration_test    TIMEOUT in 315.0s

**Comment by alyssawilk** [comment]
[----------] 3 tests from IpVersions/MySQLIntegrationTest
[ RUN      ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/0
[       OK ] IpVersions/MySQLIntegrationTest.MySQLStatsNewSessionTest/0 (181 ms)
[ RUN      ] IpVersions/MySQLIntegrationTest.MysqLoginTest/0
Terminated
================================================================================

@rshriram @venilnoronha any thoughts?  I hadn't seen this one before so hopefully it's pretty rare.

**Comment by silentdai** [comment]
I also see it occasionally. 2 out of 10 in estimation.
- Does the CI have some dashboard so that we can understand the pass rate in the last X days?
- Can we remove it from compile_time_options?
