### ISSUE TITLE
RateLimiting – send request headers upstream

### ISSUE THREAD

**Issue by lvijay** [envoyproxy/envoy#6141]
*Title*: Rate Limiting Server can send HTTP request headers upstream

*Description*:

Envoy issue #3555 [1] added support in the Rate Limiting Service's proto for sending Response HTTP Headers to the invoking client (similar to, say, Twitter's API of `x-rate-limit-limit: 100`).

The intention of this issue is to have similar support in the Envoy [rls.proto][1] except specify a list of headers which Envoy will send to the Upstream server.

#### Why is this useful?

Sending request headers to the upstream server is useful when adding Rate Limiting to a system which already has its own Rate Limiting implementation.  To gradually move out of the old rate limiting system to the new, the upstream service can be configured to switch off its rate limiting when it receives a request header from Envoy's RLS.  A request that goes through Envoy's RLS would send a request header, say, `x-rls-rate-limited: true`, which Envoy would forward to the upstream server.  The upstream server would not do its own internal rate limiting when this header is present.

[optional *Relevant Links*:]

* Similar in spirit to #3555.
* request to raise this as an issue was discussed in the envoy-users list.  [Link][2]

[1]: https://github.com/envoyproxy/envoy/blob/4a5f858/api/envoy/service/ratelimit/v2/rls.proto#L94
[2]: https://groups.google.com/d/msg/envoy-users/d8K4zv0Vnxc/Tp4Hr7bWBQAJ

**Comment by nandu-vinodan** [comment]
I would like to take this up, can we reopen this ?

**Comment by dio** [comment]
@nandu-vinodan done. Please send the PR when it is ready. Good luck!

**Comment by lvijay** [comment]
@alyssawilk this issue may be closed.  it was fixed by #8565.
