### ISSUE TITLE
FaultInjection - per Request Match or Upstream Cluster

### ISSUE THREAD

**Issue by RameshRM** [envoyproxy/envoy#6145]
**Issue Template**

*Title*: Fault Injection filter works only for all the Requests, unable to specify `matching cluster` or `headers` match.

*Description*:
I am trying to setup `fault injection` customizable per `upstream` cluster or `request headers` match as described in the docs. I am using `FROM envoyproxy/envoy:latest` docker image. THe fault injection works for all the requests but not for a selected `upstream | headers match`. 

Can you share an example or point me to the right docs. 

Thx

**Comment by venilnoronha** [comment]
You can find the configuration spec for upstream cluster/header matching at https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/fault/v2/fault.proto#envoy-api-msg-config-filter-http-fault-v2-httpfault.
