### ISSUE TITLE
Bazel build failed in foreign_cc

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#6159]
**Bug Template**

*Title*: Bazel build failed in foreign_cc

*Description*:
With latest tree, and with bazel 0.21.0,   when "bazel build //souce/...", I got

bazel build //source/exe:envoy-static
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/qiwzhang/github/envoyproxy/envoy/tools/bazel.rc
ERROR: /home/qiwzhang/.cache/bazel/_bazel_qiwzhang/85114b85e3290f3d9d9a93c62b41d7d0/external/envoy/bazel/foreign_cc/BUILD:86:1: in cmake_external rule @envoy//bazel/foreign_cc:yaml: 
Traceback (most recent call last):
        File "/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/85114b85e3290f3d9d9a93c62b41d7d0/external/envoy/bazel/foreign_cc/BUILD", line 86
                cmake_external(name = 'yaml')
        File "/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/85114b85e3290f3d9d9a93c62b41d7d0/external/rules_foreign_cc/tools/build_defs/cmake.bzl", line 47, in _cmake_external
                cc_external_rule_impl(ctx, attrs)
        File "/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/85114b85e3290f3d9d9a93c62b41d7d0/external/foreign_cc_impl/framework.bzl", line 209, in cc_external_rule_impl
                _define_out_cc_info(ctx, attrs, inputs, outputs)
        File "/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/85114b85e3290f3d9d9a93c62b41d7d0/external/foreign_cc_impl/framework.bzl", line 627, in _define_out_cc_info
                cc_common.create_compilation_context(ctx = ctx, headers = depset([outpu...]), <2 more arguments>)
unexpected keyword 'ctx', for call to method create_compilation_context(headers = unbound, system_includes = unbound, includes = unbound, quote_includes = unbound, defines = unbound) of 'cc_common'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis of target '@envoy//bazel/foreign_cc:yaml' failed; build aborted
INFO: Elapsed time: 1.483s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (213 packages loaded, 4783 targets configured)
    Fetching @com_github_gperftools_gperftools; Patching repository
    Fetching @com_github_nghttp2_nghttp2; fetching
    Fetching @com_github_c_ares_c_ares; fetching
    Fetching @com_github_circonus_labs_libcircllhist; fetching
    Fetching @boringssl; fetching
    Fetching @com_github_madler_zlib; fetching

BTW,  I also tried with bazel 0.23.0. Same issue

Any clues?

**Comment by lizan** [comment]
Did you try `bazel clean --expunge`? 0.21 doesn't work with latest, but 0.22 or 0.23 should work and they are tested in CI.

**Comment by qiwzhang** [comment]
Thanks.   It works now after "bazel clean --expunge"
