### ISSUE TITLE
Stats for pending request/retry circuit breaking values

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#6163]
As far as I can tell, there's currently no way to know how close Envoy is to triggering circuit breaking for for pending requests or retries, since no stat is emitted for number of reqs in pending/retry state.

It would be great to have stats that allow monitoring the circuit breaking resource usage without having to enable them, to allow a sensible value to be selected by observing these stats.

Stats already exists for active conns/requests, so it would be nice to have this for all the circuit breakers.

**Comment by snowp** [comment]
Naively this would be implemented by adding stats to router/conn pool where these resources are incremented/decremented, but would it perhaps make sense to add gauges to `ResourceManager` to track the current resource count? We could then more easily config flag these stats to avoid adding additional stats for each upstream cluster.

**Comment by snowp** [comment]
@mattklein123 Thoughts here?

**Comment by mattklein123** [comment]
@snowp sure makes sense to me, I like the idea of adding them to `ResourceManager` directly if possible.

**Comment by spenceral** [comment]
I am going to work with @snowp on this.
