### ISSUE TITLE
Should sendLocalReply send error response in JSON format?

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#6166]
*Title*: Should sendLocalReply send error response in JSON format

*Description*:
For JSON API,  client code is expecting the error response in JSON format.  If the response is in plain text, it will crash many client codes.    

Should sendLocalReply() send error in JSON format instead of plain text if a request has JSON content-type?

**Comment by zyfjeff** [comment]
If no one do it, please assign to me @dio

**Comment by mattklein123** [comment]
I'm going to close this and we can track in https://github.com/envoyproxy/envoy/issues/1178
