### ISSUE TITLE
Envoy listener bind error on hot restart causes  seg faults some times

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#6171]
We are seeing occasional seg faults after hot restart when there is a port conflict in creating dynamic listeners.

Here is the log before crash

2019-03-05 03:14:33.943 [source/server/listener_manager_impl.cc:943] all dependencies initialized. starting workers
2019-03-05 03:14:33.991 [source/server/listener_manager_impl.cc:871] listener 'egress_listener_1' failed to listen on address '127.0.0.1:12080' on worker

At this time `listener_manager.total_listeners_draining` stat is incremented and `envoy.listener_manager.listener_removed` is *not* incremented. 

Based on the above, I am _guessing_, it is getting in to some kind of race condition at this line across all workers with little reading of this code while erasing active_listener

https://github.com/envoyproxy/envoy/blob/4808f9e6f8af7577249c2c55646d81ab5c0e2787/source/server/listener_manager_impl.cc#L999

Does any one has seen this kind of issue?

**Comment by ramaraochavali** [comment]
Looking at a bit more, It seems possible race condition is already handled here, by ensuring the remove logic is called atmost once.

https://github.com/envoyproxy/envoy/blob/4808f9e6f8af7577249c2c55646d81ab5c0e2787/source/server/listener_manager_impl.cc#L931

Not sure what is causing this? @mattklein123  any ideas to look for here?

**Comment by mattklein123** [comment]
Do you have a stack trace or core dump?

**Comment by ramaraochavali** [comment]
@mattklein123  unfortunately we do have that. But this seems to be reasonably consistent - So I will see if I can get more additional debug information.

**Comment by ramaraochavali** [comment]
@mattklein123  I tried upgrading Envoy and trying to reproduce. But on the latest version this is not reproducible. We can close this.

**Comment by ramaraochavali** [comment]
Closing the issue.
