### ISSUE TITLE
tools: compilation database generation fails

### ISSUE THREAD

**Issue by ipuustin** [envoyproxy/envoy#6172]
*Title*: `tools/gen_compilation_database.py` fails.

*Description*:

Trying to generate the compilation database (on clean master branch) fails.

*Repro steps*:

```
$ tools/gen_compilation_database.py 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142    0   142    0     0    142      0 --:--:-- --:--:-- --:--:--   142
100 10753    0 10753    0     0   5821      0 --:--:--  0:00:01 --:--:-- 5149k
INFO: Invocation ID: e45910e5-9815-4786-a7dd-014018b9dd1a
ERROR: Analysis of aspect '//bazel-compilation-database-0.3.1:aspects.bzl%compilation_database_aspect of //api/test/validate:pgv_test' failed; build aborted: no such package 'envoy/config/health_checker/redis/v2': BUILD file not found on package path
```

`git bisect` shows that https://github.com/envoyproxy/envoy/commit/cef00ce0ed87af6d1e77283c7232ba95078cc934 is the first "bad" commit.

**Comment by ipuustin** [comment]
@mergeconflict: I guess that may be due to the remote reference to `envoy_api`?

**Comment by ipuustin** [comment]
It turns out that reverting https://github.com/envoyproxy/envoy/commit/cef00ce0ed87af6d1e77283c7232ba95078cc934 fixes the problem. However, https://github.com/envoyproxy/envoy/issues/5909 will break then again.

Might be that after we get this figured out we want to add compilation database generation to CI:

```diff
diff --git a/ci/README.md b/ci/README.md
index 15fcee177..e6f390321 100644
--- a/ci/README.md
+++ b/ci/README.md
@@ -96,6 +96,7 @@ The `./ci/run_envoy_docker.sh './ci/do_ci.sh <TARGET>'` targets are:
 * `check_spelling`&mdash; run `misspell` on entire project.
 * `fix_spelling`&mdash; run and enforce `misspell` on entire project.
 * `check_spelling_pedantic`&mdash; run `aspell` on C++ and proto comments.
+* `compilation_database`&mdash; generate compilation database.
 * `docs`&mdash; build documentation tree in `generated/docs`.
 
 # Testing changes to the build image as a developer
diff --git a/ci/do_ci.sh b/ci/do_ci.sh
index 3ee4e4090..e555a6fd9 100755
--- a/ci/do_ci.sh
+++ b/ci/do_ci.sh
@@ -331,6 +331,10 @@ elif [[ "$1" == "docs" ]]; then
   echo "generating docs..."
   docs/build.sh
   exit 0
+elif [[ "$1" == "compilation_database" ]]; then
+  echo "generating compilation database (with default options)..."
+  ./tools/gen_compilation_database.py
+  exit 0
 else
   echo "Invalid do_ci.sh target, see ci/README.md for valid targets."
   exit 1
```

**Comment by mergeconflict** [comment]
Very strange... I just messed around with this for a bit and noticed a few things:

* First of all, you're right, reverting cef00ce does appear to fix it, although I can't understand why.
* The error message you got is `no such package 'envoy/config/health_checker/redis/v2'` but that is apparently nondeterministic. I'm seeing a similar error right now, but it complains about `envoy/service/ratelimit/v2` instead. If you remove any of these dependencies from the list, it will just complain about a different one next time.
* This diff seems to help a bit, in that it allows `bazel test //api/test/validate:pgv_test` to run:

```diff
diff --git a/api/bazel/api_build_system.bzl b/api/bazel/api_build_system.bzl
index c68ccbdf6..e7df87846 100644
--- a/api/bazel/api_build_system.bzl
+++ b/api/bazel/api_build_system.bzl
@@ -145,7 +145,7 @@ def api_cc_test(name, srcs, proto_deps):
     native.cc_test(
         name = name,
         srcs = srcs,
-        deps = [_LibrarySuffix(d, _CC_SUFFIX) for d in proto_deps],
+        deps = [Label(_LibrarySuffix(d, _CC_SUFFIX)) for d in proto_deps],
     )
```

**Comment by lizan** [comment]
@ipuustin the compilation database generation is used in clang_tidy CI run so it is tested in every PR. What version of bazel are you using? Did you try bazel clean --expunge before run it?

**Comment by ipuustin** [comment]
@lizan: yes, I did run `bazel clean --expunge`. The working tree was also clean (`git clean -fdx`). I'm using bazel 0.22.0 on Fedora 29. I think @mergeconflict got the issue reproduced too? I need to check the options and targets used by `clang_tidy` db generation.

**Comment by lizan** [comment]
@ipuustin #6229 should have fixed this (and run in clang-tidy CI).

**Comment by ipuustin** [comment]
@lizan I can confirm that this works now. Thanks! Closing the issue.
