### ISSUE TITLE
Current master build fails on LuaJit

### ISSUE THREAD

**Issue by robertpanzer** [envoyproxy/envoy#6188]
*Title*: The current build of master fails.

*Description*:
I pulled the latest master and tried to build.
After a `bazel clean --expunge` the build breaks at a very early stage.

Building with `bazel build //source/exe:envoy-static` gives this error:
```
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/home/robert/.cache/bazel/_bazel_robert/f53035c79fe3a38f252a2a5d1464c7c1/external/com_github_luajit_luajit/src'
HOSTCC    host/minilua.o
/home/robert/.cache/bazel/_bazel_robert/f53035c79fe3a38f252a2a5d1464c7c1/external/local_config_cc/extra_tools/envoy_cc_wrapper  -O2 -fomit-frame-pointer -Wall  -DLUAJIT_ENABLE_LUA52COMPAT  -I. -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/minilua.o host/minilua.c
Assembler messages:
Fatal error: can't create host/minilua.o: Read-only file system
Makefile:691: recipe for target 'host/minilua.o' failed
make[1]: *** [host/minilua.o] Error 1
make[1]: Leaving directory '/home/robert/.cache/bazel/_bazel_robert/f53035c79fe3a38f252a2a5d1464c7c1/external/com_github_luajit_luajit/src'
Makefile:112: recipe for target 'src/luajit' failed
make: *** [src/luajit] Error 2
cp: cannot stat '/tmp/tmp.C83bga9crU/./luajit': No such file or directory
```

The full build log is here:
[build.log](https://github.com/envoyproxy/envoy/files/2935735/build.log)

**Comment by dio** [comment]
@robertpanzer in what platform are you on?

**Comment by robertpanzer** [comment]
Oh yes, I am sorry, I completely forgot to mention this.
I am on Ubuntu 18.04.2 LTS.

**Comment by robertpanzer** [comment]
Strange that the build seems to pass on OS X though.
Both environments are on 908213c3d4f3301cc1df463fe31a070bc5068701.

**Comment by dio** [comment]
@robertpanzer I think this is bazel related (linux-sandbox).

I can reproduce your case, and have a silly workaround: to force that dir to be writable.

in your case, 

```
$ bazel build --sandbox_tmpfs_path=/run/shm --sandbox_writable_path=/home/robert/.cache/bazel/_bazel_robert/f53035c79fe3a38f252a2a5d1464c7c1 //source/exe:envoy-static
```

The `--sandbox_tmpfs_path=/run/shm` is probably not required.

And do `bazel clean --expunge` before running it.

@lizan should have a better idea of this.

**Comment by htuch** [comment]
How wide spread is this? Did we miss it in CI because we are building unsandboxed? I plan on removing the unsandboxed flags in the context of the coverage CI in any case.

**Comment by robertpanzer** [comment]
@dio I just managed to build it with the command you posted, and I could indeed remove the `--sandbox_tmpfs_path` flag. 
Thank you!

@htuch I probably can't answer this, I am still a complete noob at Bazel :) (or maybe rather :( )

**Comment by robertpanzer** [comment]
So for other users stumbling over this, a generally working command that doesn't have any dependencies on my local setup would look like this:
```
bazel build --sandbox_writable_path=$(bazel info output_base) //source/exe:envoy-static
```

**Comment by lizan** [comment]
Hmm, I wasn't able to reproduce this on Debian 9, will try to repro on Ubuntu 18.04.

**Comment by lizan** [comment]
@robertpanzer which bazel version are you on?

**Comment by cmluciano** [comment]
@lizan I'm able to replicate this on Ubuntu 18.04 - 4.18.0-15-generic with bazel 0.23.1

**Comment by lizan** [comment]
#6202 should fix this, please try out as CI won't reproduce the problem.

**Comment by robertpanzer** [comment]
I was on Bazel 0.22.0.
I can confirm that the build works now also with this version of Bazel on the latest master (8c12b21aaa6cdfe63233075045a5b56fdff6da30)
