### ISSUE TITLE
Redis latency stats coming as 0 when latency is less than 1 ms

### ISSUE THREAD

**Issue by rammantripragada** [envoyproxy/envoy#6194]
*Title*: *Redis latency stats coming as 0 when latency is less than 1 ms*

*Description*:
Our redis server command latencies P50, P90 are under 1 milliseconds. Currently redis stats unit is in milliseconds due to which P50, P90 stats are coming as 0.

>*redis.redis_test.command.set.latency: P0(0,0) P25(0,0) P50(0,0) P75(0,0) P90(0,0)...*

Proposed solution :
Add a new config parameter to redis network filter config, which when set will result in latency stats in microseconds. By default latency stats will be in milliseconds to support backward compatibility and existing users. 

 > static_resources:
 >listeners:
 > - name: listener_0
 >   address:
 >     socket_address: { address: 127.0.0.1, port_value: 12000 }
 >   filter_chains:
 >      filters:
 >       name: envoy.redis_proxy
 >       config:
 >         stat_prefix: redis_test
 >         *latency_in_micros: true*
 >         cluster: redis_service
>          settings: { op_timeout: 1000s, enable_hashtagging: false }

I have made these changes and can raise a PR for this. With this change the latency are displayed in microseconds for redis latency stats. Below is the stats in that case in microseconds:

>*redis.redis_test.command.set.latency: P0(65,49) P25(80,75.8235) P50(88.25,199.997) >*P75(101.25,487.972) P90(155,866.644)...

**Comment by rammantripragada** [comment]
@ramaraochavali

**Comment by mattklein123** [comment]
This makes sense to me.

**Comment by rammantripragada** [comment]
@mattklein123 @dio I will raise PR for this. Thanks.
