### ISSUE TITLE
SSL handshake is case-sensitive

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#6199]
*Title*: *SSL handshake is case-sensitive*

*Description*:
For a wildcard cert `*.bar.com`, requests to `foo.bar.com` work but fail with `Foo.bar.com`, `FOO.bar.com` and the like.

I don't have an endpoint you can hit. I "fixed" this by adding

```std::transform(server_name_.begin(), server_name_.end(), server_name_.begin(), ::tolower);```

to [`ConnectionSocketImpl::setRequestedServerName`](https://github.com/envoyproxy/envoy/blob/v1.8.0/source/common/network/listen_socket_impl.h#L115-L117) but I'm not so sure I didn't break something else.

*Repro steps*:

Working request
```
$ curl -vvv https://foo.bar.com
*   Trying 123.123.123...
* TCP_NODELAY set
* Connected to foo.bar.com (123.123.123) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.bar.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET / HTTP/1.1
> Host: foo.bar.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json;charset=UTF-8
< content-length: 18
< date: Wed, 06 Mar 2019 21:26:33 GMT
< x-envoy-upstream-service-time: 15
< server: envoy
<
* Connection #0 to host foo.bar.com left intact
{"message":"pong"}%
```

Failing request
```
$ curl -vvv https://Foo.bar.com
*   Trying 123.123.123.123...
* TCP_NODELAY set
* Connected to Foo.bar.com (123.123.123.123) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

*Admin and Stats Output*:
N/A

*Config*:
The endpoint was configured dynamically with Contour. I can rebuild my cluster and grab the relevant sections of config if it's needed but I think this is easily reproducible.

*Logs*:
The key logs that helped me track this down were
```
[2019-03-06 21:26:31.523][43][debug][filter] source/extensions/filters/listener/tls_inspector/tls_inspector.cc:73] tls inspector: new connection accepted
[2019-03-06 21:26:31.528][43][debug][filter] source/extensions/filters/listener/tls_inspector/tls_inspector.cc:126] tls:onServerName(), requestedServerName: Foo.bar.com
[2019-03-06 21:26:31.528][43][debug][main] source/server/connection_handler_impl.cc:193] closing connection: no matching filter chain found
```

*Call Stack*:
N/A

**Comment by PiotrSikora** [comment]
Thanks! This is indeed an issue, though the transformation to lowercase should be applied throughout the codebase for server names (e.g. imagine the opposite case, with certificate for `*.BAR.COM` and request for `foo.bar.com`).

**Comment by mattklein123** [comment]
@PiotrSikora do you think we should config guard this or always lowercase? I would be concerned someone might be depending on this?

**Comment by lizan** [comment]
I don't think we should guard, both [X.509 RFC](https://tools.ietf.org/html/rfc5280#section-7.2) and [SNI RFC](https://tools.ietf.org/html/rfc6066#section-3) states it has to be case-insensitive comparison. Algorithms are described in [RFC 5890](https://tools.ietf.org/html/rfc5890#section-2.3.2.4).

**Comment by PiotrSikora** [comment]
@mattklein123 always lowercase, IMHO, since per [RFC4343](https://tools.ietf.org/html/rfc4343) domain names are case-insensitive, so we shouldn't be rejecting uppercase.

**Comment by phylake** [comment]
This seems like a bug based on the above RFCs

**Comment by mattklein123** [comment]
SGTM then let's just fix.

**Comment by derekargueta** [comment]
I'd imagine we want to preserve the original casing, i.e. for logging, and just make the comparisons case-insensitive, no?

**Comment by PiotrSikora** [comment]
I'd just lowercase everything, but I don't feel too strongly about it.

**Comment by wkochman** [comment]
Hi,

Is there any plan to fix this issue?

Thx

**Comment by ggreenway** [comment]
Nobody has said they are working on it, but a PR to fix this would be appreciated.
