### ISSUE TITLE
Not able to build envoy from tag:1.9.0

### ISSUE THREAD

**Issue by Dheeraj-GitHubTaazaa** [envoyproxy/envoy#6206]
Hi Team, 
i am trying to build the Envoy from tag 1.9.0 and am getting below error 
![image](https://user-images.githubusercontent.com/48286718/53958204-687ad380-4106-11e9-8cc4-989c92a0d208.png)

Please help me resolve this as i need to decide if we can use this tool or not ?

thank you 
Dheeraj Kumar

**Comment by lizan** [comment]
We don't have full support on Windows yet, @sesmith177 might be able to help you.
