### ISSUE TITLE
Feedback mechanism when Endpoints are changing [question]

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#6212]
**Issue Template**

I am investigating the feasibility of using Envoy as the gateway/reverse proxy in a distributed systems framework at Microsoft.

We have a system that fail's over primary replicas to a new node within a few milliseconds. When this happens, the fastest way to identify the new endpoint is for the client to "pull" the new location when the old endpoint returns an error code. For this to work, the client has to write code that triggers a http endpoint which we can use as a signal to "pull" the new endpoint location and configure envoy correctly.

Without the pull model, all nodes in the cluster learn about the new endpoint in 5 seconds and hence Envoy would eventually be configured to route to the correct endpoint on all the nodes. (There is 1 envoy on each node).

I am trying to improve this mechanism to instead re-configure Envoy as soon as the new endpoint becomes available, rather than having to wait for the 5 second interval we have. In order to write simpler clients who don't have to signal to "pull" the new endpoint, is there a way for Envoy to provide a notification when an endpoint returns a 404 or other connection related error code so that we can proactively do a 'pull' without involving the client?

Looking forward to some ideas here.

Thanks!

**Comment by mattklein123** [comment]
@sumukhs there is nothing built-in to do this today, however why not just use gRPC streaming discovery and push updated endpoints when they are ready?

**Comment by sumukhs** [comment]
@mattklein123 - We have a central service which runs on a single node (with secondary replicas on other nodes) that learns about the updated endpoints first. On this particular node, it is possible to push the update to envoy using gRPC ASAP.

However, the other nodes in the cluster discover this update after a configured interval (5 seconds) through a reliable broadcast message we send out. We could reduce this interval to a smaller value, but at the cost of too many updates when a whole node goes down, taking down many services. The batching is done to reduce the number of broadcasts being processed.

So if a client was connected to an envoy proxy on a random node, it would take ~5 seconds to receive the updated endpoints. This latency is okay for nodes if there are no active clients to the service, but I am looking for ways to improve this time for nodes that do have an active client connected.

One option I was thinking of exploring was to add an envoy filter that identifies an error code corresponding to 'HTTP endpoint missing' and signals our process on the local node to "pull" the required update immediately from the central service. This way, client critical envoy's get their updates immediately, while other envoy processes get them lazily. Do you see any fundamental issues with this approach?

**Comment by mattklein123** [comment]
> Do you see any fundamental issues with this approach?

I think that could work without too much complexity. I still wonder why you require broadcasts vs. just everyone getting streamed updates, but I obviously don't understand the details of your architecture.

**Comment by sumukhs** [comment]
Thanks. Are there pointers to examples of writing such filters?

**Comment by mattklein123** [comment]
@sumukhs I might take a look at the health check filter, as it is an encoding filter that inspects headers which I think is mostly what you need.
