### ISSUE TITLE
Bootstrap config BASE_CONFIG missing cluster connect_timeout

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#6213]
in (src/test/config/utility.cc), const std::string ConfigHelper::BASE_CONFIG, the config is missing a connect_timeout field in the "cluster_0" field. Presumable required, though I'm not sure where the validation is. This should be easy to fix, but I'm not sure there should be additional tests added to prevent these hard-coded configs from fulling out of date in the future.

Error:
```
E0307 11:30:28.978241  123426 server.cc:87] [main] error initializing configuration '/usr/local/google/_blaze_auni/0e0083681b1bec721984fcf0f695aa26/execroot/google3/_tmp/gfe3_context_test_1/bootstrap.json': Field 'connect_timeout' is missing in: name: "cluster_0"
hosts {
  socket_address {
    address: "::1"
    port_value: 0
  }
}
```

My helper function:  
```
  Envoy::OptionsImpl CreateEnvoyConfig() {
    testing::NiceMock<Envoy::Stats::MockIsolatedStatsStore> stats_store;
    Envoy::Api::ApiPtr api_ptr(Envoy::Api::createApiForTest(stats_store));
    Envoy::ConfigHelper config_helper(Envoy::Network::Address::IpVersion::v6, *api_ptr);
    Envoy::OptionsImpl test_options("cluster_name", "node_name", "zone_name", spdlog::level::info);
    const std::string bootstrap_path = Envoy::TestEnvironment::writeStringToFileForTest(
              "bootstrap.json", Envoy::MessageUtil::getJsonStringFromMessage(config_helper.bootstrap()));
    return test_options;
  }
```

**Comment by auni53** [comment]
@dio shouldn't this be a bug?

Also I'm pretty confused by this, I tried to fix the bootstrap by adding a `connect_timeout` field to the cluster_0 segment, and that caused segfaults with proto validation errors...

**Comment by dio** [comment]
@auni53 OK, updated.
