### ISSUE TITLE
Unable to build nghttp2 while compiling envoy

### ISSUE THREAD

**Issue by SorinS** [envoyproxy/envoy#6217]
**Envoy compilation problem**

*Title*: *nghttp2 compilation fails*

*Description*:
>Environment:
- Amazon Linux AMI  running kernel 4.14.97-90.72.amzn2.x86_64
- bazel 0.23.1
- java-1.8.0-openjdk-devel
- ninja-build 1.7.2
- go 1.9.4
- cmake 3.6.2
- envoy cloned from git at tag v1.9.0
Running: bazel build //source/exe:envoy-static
yields:

    Package version: 1.34.0
    Library version: 31:1:17
    Install prefix:  /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/thirdparty_build
    Target system:   Linux
    Compiler:
      Build type:     RelWithDebInfo
      C compiler:     /usr/bin/cc
      CFLAGS:         -O2 -g  -ggdb3 -fno-omit-frame-pointer -O2 
      C++ compiler:   /usr/bin/g++
      CXXFLAGS:       -O2 -g  -ggdb3 -fno-omit-frame-pointer -O2 
      WARNCFLAGS:      -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wwrite-strings -Wshadow -Winline -Wnested-externs -Wfloat-equal -Wundef -Wendif-labels -Wempty-body -Wcast-align -Wclobbered -Wvla -Wpragmas -Wunreachable-code -Waddress -Wattributes -Wdiv-by-zero -Wconversion -Wformat-nonliteral -Wmissing-field-initializers -Wmissing-noreturn -Wsign-conversion -Wunused-macros -Wunused-parameter -Wredundant-decls -Wno-format-nonliteral
      CXX1XCXXFLAGS:  -std=c++11
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7.14
      Library version:2.7.14
      Cython:         CYTHON_EXECUTABLE-NOTFOUND
    Test:
      CUnit:          FALSE (LIBS='')
      Failmalloc:     ON
    Libs:
      OpenSSL:        FALSE (LIBS='')
      Libxml2:        FALSE (LIBS='')
      Libev:          FALSE (LIBS='')
      Libc-ares:      TRUE (LIBS='/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/thirdparty_build/lib/libcares.a')
      Libevent(SSL):  FALSE (LIBS='')
      Spdylay:        FALSE (LIBS='')
      Jansson:        FALSE (LIBS='')
      Jemalloc:       FALSE (LIBS='')
      Zlib:           TRUE (LIBS='/usr/lib64/libz.so')
      Boost::System:  
      Boost::Thread:  
    Third-party:
      http-parser:    
      MRuby:          0
      Neverbleed:     0
    Features:
      Applications:   OFF
      HPACK tools:    OFF
      Libnghttp2_asio:OFF
      Examples:       OFF
      Python bindings:OFF
      Threading:      ON

-- Configuring incomplete, errors occurred!
See also "/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeError.log".

real	0m7.146s
user	0m5.574s
sys	0m1.299s
make: *** [/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep] Error 1
make: Leaving directory `/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps'
DEBUG: /home/ec2-user/Dev/envoy.git/bazel/repositories.bzl:94:5: External dep build exited with return code: 1
DEBUG: /home/ec2-user/Dev/envoy.git/bazel/repositories.bzl:96:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
ERROR: /home/ec2-user/Dev/envoy.git/bazel/repositories.bzl:259:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis failed
INFO: Elapsed time: 18.527s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 128 targets configured)
    Fetching @envoy_deps; fetching 7s

The CMakeError.log shows:

ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wlanguage_extension_token failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_75b40"
[1/2] Building C object CMakeFiles/cmTC_75b40.dir/src.c.o
FAILED: CMakeFiles/cmTC_75b40.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wlanguage_extension_token   -Wlanguage-extension-token -o CMakeFiles/cmTC_75b40.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wlanguage-extension-token'
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wmissing_variable_declarations failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_048cd"
[1/2] Building C object CMakeFiles/cmTC_048cd.dir/src.c.o
FAILED: CMakeFiles/cmTC_048cd.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wmissing_variable_declarations   -Wmissing-variable-declarations -o CMakeFiles/cmTC_048cd.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wmissing-variable-declarations'; did you mean '-Wmissing-declarations'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wunreachable_code_break failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_f434f"
[1/2] Building C object CMakeFiles/cmTC_f434f.dir/src.c.o
FAILED: CMakeFiles/cmTC_f434f.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wunreachable_code_break   -Wunreachable-code-break -o CMakeFiles/cmTC_f434f.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wunreachable-code-break'; did you mean '-Wunreachable-code'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wheader_guard failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_dfc81"
[1/2] Building C object CMakeFiles/cmTC_dfc81.dir/src.c.o
FAILED: CMakeFiles/cmTC_dfc81.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wheader_guard   -Wheader-guard -o CMakeFiles/cmTC_dfc81.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wheader-guard'
ninja: build stopped: subcommand failed.

But, if I:
cd /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0

and do: 
cmake .  && make
all looks good: 

Scanning dependencies of target nghttp2
[  4%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_pq.c.o
[  8%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_map.c.o
[ 13%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_queue.c.o
[ 17%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_frame.c.o
[ 21%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_buf.c.o
[ 26%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_stream.c.o
[ 30%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_outbound_item.c.o
[ 34%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_session.c.o
[ 39%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_submit.c.o
[ 43%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_helper.c.o
[ 47%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_npn.c.o
[ 52%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_hd.c.o
[ 56%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_hd_huffman.c.o
[ 60%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_hd_huffman_data.c.o
[ 65%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_version.c.o
[ 69%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_priority_spec.c.o
[ 73%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_option.c.o
[ 78%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_callbacks.c.o
[ 82%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_mem.c.o
[ 86%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_http.c.o
[ 91%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_rcbuf.c.o
[ 95%] Building C object lib/CMakeFiles/nghttp2.dir/nghttp2_debug.c.o
[100%] Linking C shared library libnghttp2.so
[100%] Built target nghttp2

I can provide logs, etc if needed. 
Appreciate any help...
Thank you...

**Comment by lizan** [comment]
What is the gcc or clang version are you using? Note we only support GCC 7+ or Clang/LLVM 7+.

It is recommended to start with docker based build.

**Comment by SorinS** [comment]
Hi, 
Thank you for responding, here is it: 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-libsanitizer --enable-gnu-indirect-function --enable-libcilkrts --enable-libatomic --enable-libquadmath --enable-libitm --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

And:

clang --version
clang version 7.0.1 (Amazon Linux 2 7.0.1-1.amzn2.0.2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Thank you...

**Comment by SorinS** [comment]
Steps to reproduce:

On EC2, use amzn2-ami-hvm-2.0.20190228-x86_64-gp2 (ami-02da3a138888ced85) and the run:

sudo yum group install "Development Tools"
sudo yum install java-1.8.0-openjdk-devel
sudo yum install ninja-build
sudo yum install golang
sudo yum install clang
sudo ln -s /usr/bin/ninja-build /usr/bin/ninja

curl -L -O -k https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-installer-linux-x86_64.sh
chmod +x ./bazel-0.23.1-installer-linux-x86_64.sh 
sudo ./bazel-0.23.1-installer-linux-x86_64.sh
curl -O https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
tar -zxf cmake-3.6.2.tar.gz 
cd cmake-3.6.2 && sudo ./bootstrap --prefix=/usr/local && sudo gmake && sudo make install && cd ..
git clone https://github.com/envoyproxy/envoy.git envoy.git
cd envoy.git/
git checkout v1.9.0
bazel build //source/exe:envoy-static

**Comment by SorinS** [comment]
It seems that it fails at pthread detection:

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_890fe"
[1/2] Building C object CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_890fe
FAILED: cmTC_890fe 
: && /usr/bin/cc  -ggdb3 -fno-omit-frame-pointer -O2   CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o  -o cmTC_890fe  -rdynamic && :
CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o: In function `main':
/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

But, I can compile that no problems using:

gcc -lpthread -o pthread pthread.c 

Something missing in the build configuration?

Thank you,

**Comment by SorinS** [comment]
Full log: 

cat /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeError.log 
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_890fe"
[1/2] Building C object CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_890fe
FAILED: cmTC_890fe 
: && /usr/bin/cc  -ggdb3 -fno-omit-frame-pointer -O2   CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o  -o cmTC_890fe  -rdynamic && :
CMakeFiles/cmTC_890fe.dir/CheckSymbolExists.c.o: In function `main':
/home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_56986"
[1/2] Building C object CMakeFiles/cmTC_56986.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_56986
FAILED: cmTC_56986 
: && /usr/bin/cc  -ggdb3 -fno-omit-frame-pointer -O2  -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTC_56986.dir/CheckFunctionExists.c.o  -o cmTC_56986  -rdynamic -lpthreads && :
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.


Performing C SOURCE FILE Test C_FLAG__Wshorten_64_to_32 failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_cf61f"
[1/2] Building C object CMakeFiles/cmTC_cf61f.dir/src.c.o
FAILED: CMakeFiles/cmTC_cf61f.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wshorten_64_to_32   -Wshorten-64-to-32 -o CMakeFiles/cmTC_cf61f.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wshorten-64-to-32'
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wextended_offsetof failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_8f4ab"
[1/2] Building C object CMakeFiles/cmTC_8f4ab.dir/src.c.o
FAILED: CMakeFiles/cmTC_8f4ab.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wextended_offsetof   -Wextended-offsetof -o CMakeFiles/cmTC_8f4ab.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wextended-offsetof'; did you mean '-Winvalid-offsetof'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wlanguage_extension_token failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_ef12f"
[1/2] Building C object CMakeFiles/cmTC_ef12f.dir/src.c.o
FAILED: CMakeFiles/cmTC_ef12f.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wlanguage_extension_token   -Wlanguage-extension-token -o CMakeFiles/cmTC_ef12f.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wlanguage-extension-token'
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wmissing_variable_declarations failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_0cbd4"
[1/2] Building C object CMakeFiles/cmTC_0cbd4.dir/src.c.o
FAILED: CMakeFiles/cmTC_0cbd4.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wmissing_variable_declarations   -Wmissing-variable-declarations -o CMakeFiles/cmTC_0cbd4.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wmissing-variable-declarations'; did you mean '-Wmissing-declarations'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wunreachable_code_break failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_888fb"
[1/2] Building C object CMakeFiles/cmTC_888fb.dir/src.c.o
FAILED: CMakeFiles/cmTC_888fb.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wunreachable_code_break   -Wunreachable-code-break -o CMakeFiles/cmTC_888fb.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wunreachable-code-break'; did you mean '-Wunreachable-code'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_FLAG__Wheader_guard failed with the following output:
Change Dir: /home/ec2-user/.cache/bazel/_bazel_ec2-user/0a49c6981bc062896411a4ce6a7ff661/external/envoy_deps_cache_f60283ef847e688d220ce2f1633c4979/nghttp2.dep.build/nghttp2-1.34.0/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja-build" "cmTC_40276"
[1/2] Building C object CMakeFiles/cmTC_40276.dir/src.c.o
FAILED: CMakeFiles/cmTC_40276.dir/src.c.o 
/usr/bin/cc    -ggdb3 -fno-omit-frame-pointer -O2  -DC_FLAG__Wheader_guard   -Wheader-guard -o CMakeFiles/cmTC_40276.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wheader-guard'
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }

**Comment by SorinS** [comment]
If any more information is needed, I would be more than happy to oblige. 
Please help. Thank you

**Comment by SorinS** [comment]
Any ideas?
