### ISSUE TITLE
[feature request] Lua Network Filter

### ISSUE THREAD

**Issue by liadav** [envoyproxy/envoy#6264]
**Lua Network Filter feature request: Implement Network Filter that supports lua code callbacks for onData, onWrite, onNewConnection**

*Description*:
>There is no way to add custom light-weight general network filters without compiling a different fork of Envoy. My suggestion is to add a new NetworkFilter that supports lua code for the NetworkFilter callbacks: onData, onWrite, etc. The implementation can be very similar to the implementation of HTTP Lua filter.

**Comment by jmarantz** [comment]
and just for reference, https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter is an HTTP filter.

**Comment by zyfjeff** [comment]
@liadav6 
Are you doing this? I am very interested in this, can I participate in it?

**Comment by kant777** [comment]
why is this closed? what are some of the way to implement tcp proxy filter other than c++?

**Comment by jmarantz** [comment]
It got auto-closed since no one had commented on it.

**Comment by jmarantz** [comment]
@kant777 if you want to work on this I could re-open and assign to you.

**Comment by kant777** [comment]
I dont know c++. nor I dont understand the architecture of envoy fully. so I would like to understand the complexity of what I am dealing with before I can embark on such task
