### ISSUE TITLE
When a gRPC method returns a stream, the HTTP1 status code always returns 200 OK.

### ISSUE THREAD

**Issue by jbf154** [envoyproxy/envoy#6270]
*Title*: When a gRPC method returns a stream, the HTTP1 status code always returns 200 OK.

*Description*:
>When invoking a gRPC service method that returns a stream of some message, the HTTP 1.x status code is always 200 OK and the response payload an empty JSON array.  This is when using the **envoy.grpc_json_transcoder** and supplying the protobin file generated from the .proto file.

*Steps to Reproduce*
>Create a simple .proto service like below:
```
	rpc Print(google.protobuf.Empty) returns (stream StringMessage) {
	   option (google.api.http) = {
	       get: "/v1/example/print"
	   };
	}
```
>Implement the service in Java which always throws an **UNAUTHENTICATED** StatusException:
```
    @Override
    public void print(Empty request, StreamObserver<StringMessage> responseObserver) {
        responseObserver.onError(Status.UNAUTHENTICATED.asException());
    }
```
>Use a REST client (like Postman) to hit the service through a properly configure instance of Envoy Proxy (with envoy.grpc_json_transoder enabled and pointed to the proto descriptor).  Note that even though the HTTP1 response header "**grpc-status: 16**" is present, the HTTP1 status code is still 200.

*Workaround*
>You can work around this issue by returning a message type which wraps a **repeated** message field.  This limits the HTTP2 clients to processing the repeated items only after all of the responses are sent.

**Comment by lizan** [comment]
This is due to the limitation of HTTP 1, which must encode the status at the beginning of the stream, while gRPC may send the status at the end of the stream.

**Comment by jbf154** [comment]
@lizan, is the stream not buffered in Envoy such that the headers aren't sent back to the HTTP 1 client until after the grpc-status is received?  I don't think Envoy can return the response body back to the HTTP 1 client until it has reached the end of the stream anyways.

**Comment by lizan** [comment]
No, in streaming case envoy doesn't buffer the stream until grpc-status, that's the limitation of transcoding streaming, you'll have to encode the error in the body if desired. Response trailer will be omitted.

**Comment by jbf154** [comment]
This behavior was also brought up in issue #5011 and it was supposed to be looked in to, but never was.  Basically, if the trailers are sent right away (before any response is sent back) wouldn't it be possible to correctly set the HTTP 1 status code?

**Comment by mittalvikas** [comment]
I am also stuck at this point, any suggestions?
