### ISSUE TITLE
Sporadic UH during host updates

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#6287]
We've been seeing occasional requests fail with UH during deploys when using active health checking.

In this case we have 4 hosts that all have equal weighting (2 in each locality, with same locality weighting and same priority):

L1 has hosts A B
L2 has hosts C D

This is followed by a bunch of empty priorities (probably not relevant, but mentioning for the sake of completeness).

A rolling restart (no overlapping downtime, verified by looking at the hc logs) of the hosts in L2 result in calls from downstream failing with UH. Looking at the active health check logs for the downstream, we see the hosts in L2 go unhealthy, but neither A nor B have a failing health check event in the health check log. 

This is a low traffic setup, so we just see one failure, and by the time the next call is made everything is back to normal.

This kinda seems like we're routing a request while we're in some intermediate state where we end up routing to a `HostSet` with no hosts, but I don't have a great explanation as to why that might happen. @htuch Any clue what might be going on?

We're seeing this on dfbb069d634884e386130dc1b74ef0ff2d4657b0

**Comment by snowp** [comment]
I'll note that we're also using the retry plugins which could technically modify priority load, but I don't think we retry UH at all, nor are we seeing any indication in the upstream access logs that there are previous failed calls that lead into a final UH.

**Comment by htuch** [comment]
@snowp sorry, no idea; we use a combination of passive HC and EDS delivered HC, with the active HC taking place outside of the serving Envoys, so don't have much experience with Envoy active HC.

**Comment by snowp** [comment]
Ok, I'll keep digging into this on our end. I was hoping there was something obvious about how TLS hosts/LBs were updated that would explain this kind of inconsistency, but doesn't sound like it

**Comment by snowp** [comment]
I believe this to be due to a race between when the list of healthy/degraded host list and the healthy/degraded per locality map is created: since we query for `host->health()` twice per host, it's possible for a single host to be inconsistently placed, which makes it possible for a priority to be selected
even though there are no healthy hosts in the healthy_hosts_per_locality map.

I'll get a PR to address this once I verify that it fixes the issue on our end.

**Comment by mattklein123** [comment]
@snowp how can that happen when all of the processing happens on the main thread? I don't think there is a possibility of interleaving any of that processing?

**Comment by snowp** [comment]
It seems like the subset LB partitions the host list based on health, which I believe would happen on the worker threads, though I could be wrong

 That said, my fix (whenever a host list partitioning is happening, only read health() once per host) didn't seem to work so I'm back to trying to dig into what's happening here.

**Comment by mattklein123** [comment]
OK I see if related to subset LB (I think what I said is true for everything else?). I can poke around next week if you can't find anything, though you have been working with this code much more than me recently!

**Comment by snowp** [comment]
Tracked this down to an issue related to degraded hosts: turns out the app was declaring itself degraded on boot, and the version of Envoy predated my addition of degraded health check events :(

Issue is that we're always using the locality scheduler for healthy localities, even if we're attempting to route to degraded hosts. I'll get a PR up with a fix
