### ISSUE TITLE
max_connect_attempt_interval for tcp_proxy

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy#6291]
Title: max_connect_attempt_interval for tcp proxy

Description:
There is a max_connect_attempts field, does envoy have a field to control the interval between the connect attempts.

**Comment by zyfjeff** [comment]
@mattklein123  Please assign to me,  I'm interested in TCP proxy

**Comment by mattklein123** [comment]
@zyfjeff FYI you can assign yourself using the bot.

/assign @zyfjeff
