### ISSUE TITLE
How to set up develop environment on mac using clion or vs code

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/envoy#6297]
I am a beginner of envoy, I want to add function to realize my business need, But I do not known how to set up develop environment on mac using clion or vs code, is there a document
describing how to do it ?

**Comment by MarcinFalkowski** [comment]
We had some success with CLion using this tool to generate CMakeLists.txt: https://github.com/lizan/bazel-cmakelists

Clone thie tool, go to envoy sources directory and run:
`<bazel-cmakelists dir>/bazel-cmakelists --targets //source/exe:envoy-static //test/...`
Then open envoy directory in CLion. All files/classess should load properly and you will be able to use all CLion's "smart" navigation features. 

Another problem on Mac is debugging with breakpoint support. We tried remote debugging with docker and gdb-server, but it is very slow. Someone claims that they successfully setup native debugging on Mac and VSCode, but we didn't try it yet: https://medium.com/@dirao/debugging-envoyproxy-on-osx-a3ebe87dc916

Of course you should also read and follow all the steps from this docs: https://github.com/envoyproxy/envoy/blob/master/DEVELOPER.md, especially https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers

**Comment by mattklein123** [comment]
@lizan any interest in doing some docs in the repo on your dev setup? It would be a nice thing for the community.

**Comment by lizan** [comment]
Thanks @MarcinFalkowski that's what I usually does, I only do smart navigation stuff and use auto completion in CLion. I haven't been able to use debugger for a while (didn't need either).

**Comment by ramaraochavali** [comment]
If you want to use vscode, this https://medium.com/@dirao/debugging-envoyproxy-on-osx-a3ebe87dc916 is useful.

**Comment by jmarantz** [comment]
@zplinuxlover sounds like we have a few actionable suggestions for you. Please re-open if you have further follow-up questions.

**Comment by mattklein123** [comment]
@jmarantz optimally I would like to get some of this in a dev doc in the repo somewhere. Can we use this to track that doc work potentially? It would be nice to have instructions for people who want to use both CLion and VScode (I think anyone else is on their own ;).

**Comment by sness** [comment]
Has there been any progress on a doc for this?  I tried the cmake option but I encountered some odd errors with headers when I did this.  What are the best practices for developing and debugging envoy with breakpoints on a mac laptop?

**Comment by jmarantz** [comment]
Reopening to reflect that instructions for different options for macos dev should be checked in as docs.

**Comment by jpeach** [comment]
CLion support the JSON [compilation database](https://www.jetbrains.com/help/clion/compilation-database.html). I tried this and it seemed to index everything, but was still unable to resolve any envoy symbols.

CLion ends up building 2 duplicate file trees - one for the checked-out source tree and one for the symlinked bazel tree. It believes that only the bazel tree is part of the project (i.e. has build targets), which I suppose is correct, but it's confusing. It can't resolve symbols no matter which file tree you use.

**Comment by lizan** [comment]
FWIW, I recently switched from CLion to VSCode + clangd, this set up works well so far. I'll try to blog the whole setup, but in short just use compilation database with vscode-clangd plugin with**out** default C/C++ plugin.

**Comment by aattuluri** [comment]
> FWIW, I recently switched from CLion to VSCode + clangd, this set up works well so far. I'll try to blog the whole setup, but in short just use compilation database with vscode-clangd plugin with**out** default C/C++ plugin.

@lizan It would be great if you can share details about your set up (if not blog then some raw instructions would do). I am trying to build wasm extensions for envoy and haven't had success in debugging the envoy code.

**Comment by yanickxia** [comment]
@MarcinFalkowski  today , try to rebuild cmake, will be hang at bazel `query`

```bash
<bazel-cmakelists dir>/bazel-cmakelists --targets //source/exe:envoy-static 

......

['bazel', '--host_jvm_args=-Xmx8g', 'query', '--noimplicit_deps', 'attr("copts", "", deps(kind("cc_.* rule", //source/exe:envoy-static)))', '--output', 'xml']
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
```

wait 1 hour, but not end...

**Comment by ngtuna** [comment]
I got no luck with this. My mac (8 core, 16GB ram) always running out of memory with `<bazel-cmakelists dir>/bazel-cmakelists --targets //source/exe:envoy-static`, even though `bazel build` got success. Any hint ?

**Comment by jpeach** [comment]
> I got no luck with this. My mac (8 core, 16GB ram) always running out of memory with `<bazel-cmakelists dir>/bazel-cmakelists --targets //source/exe:envoy-static`, even though `bazel build` got success. Any hint ?

IIRC you can use a `user.bazelrc` to limit how many resources bazel uses on the build host. Here's an [example](https://github.com/jpeach/envoy-build/blob/master/user.bazelrc).

**Comment by ngtuna** [comment]
Nice it works thank you @jpeach Sorry I'm new to Bazel

**Comment by stlava** [comment]
I'm still trying to work the through the same out of memory issue when using `bazel-cmakelists`. However, has anyone actually been successful building the envoy binary on macos with dbg symbols for use with gdb? I don't quite follow how cmake factors into this other than setting up the project for CLion.

**Comment by ngtuna** [comment]
@stlava take the [example](https://github.com/jpeach/envoy-build/blob/master/user.bazelrc) @jpeach mentioned above and append it to <envoy-folder>/.bazelrc then you don't get memory issue anymore.

**Comment by stlava** [comment]
Yup, I've tried that but I still run out of memory even with 16gb. I'm now attempting to build fewer extensions in the hopes that decreases the memory consumption of the build.

**Comment by xjtian** [comment]
@stlava did you get anywhere with this? I had the same problem and gave up. It seems like bazel will eat an unlimited amount of memory.

**Comment by stlava** [comment]
No, I wasn't able to get it working. I ended up just using VSCode with the docker container method and it works reasonably well albeit a resource hog even after the first build. I'm not convinced that the native dbg build on osx actually produces gdb symbols, at least I was never able to get it to do so.

**Comment by xpahos** [comment]
Script uses 21GB of RAM. I generated a file but indexing is no so good.

[CMakeLists.txt](https://github.com/envoyproxy/envoy/files/6448768/CMakeLists.txt)

**Comment by agrawroh** [comment]
I tried using **42G** RAM and am still hitting the OOM-ing issue :(

```bash
export BAZEL_STARTUP_ARGS="--host_jvm_args=-Xmx42g --host_jvm_args=-Xms24g"; ../bazel-cmakelists/bazel-cmakelists --targets //source/exe:envoy-static
```
