### ISSUE TITLE
stats: TLS-cache leaks stats when clusters are removed.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#6306]
Whenever a cluster is removed from Envoy via xDS update, the ThreadLocalStore::Scope will be cleaned up, and the corresponding CentralCacheEntry objects will also be deleted.

However, there are also TlsCacheEntry objects for each thread, and those will continue to reference any stats that were created for clusters, and there does not appear to be any mechanism to reclaim those map entries or GC away the stat objects themselves, which are kept alive by a shared_ptr.

I believe a cleanup could be engineered by post()ing a GC request to each thread at the time the Scope is deleted.

**Comment by mattklein123** [comment]
@jmarantz unless I am misunderstanding something, this is already implemented for the current code, so I do think that what you have in the other PR would be potentially considered a regression? See https://github.com/envoyproxy/envoy/blob/628d1668d7dc9244e3a8fa3d3fbabca23e92e23d/source/common/stats/thread_local_store.cc#L195

**Comment by jmarantz** [comment]
Thanks Matt; I totally missed that. I'll just fix this now in #6207 and invalidate this bug.

It does mean I need to store the rejected stat names as shared_ptr<std::string> to avoid duplicating the string stat-names for each thread.
