### ISSUE TITLE
stats: Remove FakeSymbolTableImpl and related helpers

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#6307]
The goal of [FakeSymbolTableImpl ](https://github.com/envoyproxy/envoy/blob/master/source/common/stats/fake_symbol_table_impl.h) is to put the SymbolTable API in place. That will enable us to incrementally transform all places in the Envoy codebase where stat-names are constructed to pre-allocate at startup all StatNames constituent strings. 

Once the real Symbol TableImpl is in place, encoding strings into symbols requires taking a symbol-table lock, so we don't want to do that in the hot-path.

So FakeSymbolTableImpl allows us to deploy the Symbol API without worrying about lock contention.

Once there are no more hot-path encoding of strings into SymbolTable, we can swap in SymbolTableImpl and delete FakeSymbolTableImpl.

**Comment by mattklein123** [comment]
I guess we won't be able to clean this up until 1.16 so moving this out.

**Comment by jmarantz** [comment]
agreed; we should bake with the default being real symbol tables, but the 'fakes' being available for a release first.

**Comment by mattklein123** [comment]
@jmarantz I think we can clean all of the old code up now? WDYT?

**Comment by jmarantz** [comment]
Yes, working on it. It's easy to nuke all that code. Hopefully also easy to review.
