### ISSUE TITLE
Linker option `-fuse-ld=gold` may accidentally get enforced for `clang++`

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/envoy#6314]
Possible bug in genrule_repository / _genrule_environment()

Consider https://github.com/envoyproxy/envoy/blob/dba462267df2f881f676ed7eb0c31637f646add2/bazel/genrule_repository.bzl#L109
It looks like `-fuse-ld=gold` gets force added for clang++ whereas it looks like this was
only meant to be performed for `g++`

This may cause trouble with trying to perform asan/tsan/etc runs with `clang++` & `ld.lld`

**Comment by htuch** [comment]
Yep, this seems broken to me. @lizan @PiotrSikora @jmillikin-stripe do you recall the provenance of this?

**Comment by lizan** [comment]
`genrule_repository` is only used for FIPS BoringSSL and QUICHE so I don't think this is causing problem, and mixed use of lld and gold shouldn't cause problem with ASAN/TSAN.

**Comment by oschaaf** [comment]
Well, I did see errors like https://gist.github.com/oschaaf/978765bce763c823264d789035fa31b2, but I'm not 100% that that is attributable to what is reported here. I do know that this error will not occur when consistently enforcing `ld.ldd` usage. 
It's just that I thought the observation was worth reporting, because reading the comments, it seemed like enforcing `ld.gold` when `clang++` is involved looks like it was not the original intent when reading the comments.

**Comment by jmillikin-stripe** [comment]
That check was added in https://github.com/envoyproxy/envoy/pull/1884 -- that might have been before we were building with clang++ (vs just clang).

**Comment by jmarantz** [comment]
Are we in agreement that this is a problem? Who should own it?

**Comment by lizan** [comment]
@oschaaf what is your environment and the revision you're building? bazel itself does also add gold flags.

**Comment by oschaaf** [comment]
I was running via docker to get the sanitizers operational in CI over at envoy-perf/nighthawk:
https://github.com/envoyproxy/envoy-perf/pull/38/files#diff-46c5b50ff7d54293b9113c7502fc4a3dR74

The docker image is `envoyproxy/envoy-build:b3995b7c5e3846f80f6f09436043ec4c8c8f762a`.
The envoy last Envoy version I tried was https://github.com/envoyproxy/envoy/commit/0286b82280d33d39b5fec7dbc6be34d2fc943c7d

(ps - there's currently a hack in place to work around: https://github.com/envoyproxy/envoy-perf/pull/38/files#diff-46c5b50ff7d54293b9113c7502fc4a3dR41)

**Comment by lizan** [comment]
@oschaaf from https://github.com/envoyproxy/envoy-perf/pull/38/files#diff-46c5b50ff7d54293b9113c7502fc4a3dR74 I don't see anywhere that you're setting `-fuse-ld=lld`? in envoy repo we do it here https://github.com/envoyproxy/envoy/blob/3d3f3afb14d5ff395d71ef546f95a42e5b40057f/ci/build_setup.sh#L67

**Comment by jmillikin-stripe** [comment]
Independent of where `-fuse-ld=lld` is being set, the original question ("is `clang++` supposed to activate special cases intended for GNU GCC's `g++` command") remains.

The comment around the relevant line describes it as a workaround for ancient versions of GCC, so I think the answer is clearly "it should not apply to `clang++`.

**Comment by oschaaf** [comment]
@Lizan Sorry, I should have mentioned that earlier, but when reverting to the hack I mentioned above, I effectively threw in the towel, and backed out my (messy) attempts to get the right flags passed down to all dependencies.

**Comment by lizan** [comment]
@jmillikin-stripe yeah I agree that it should not apply to `clang++` though I don't think we're actually hitting that code path.

**Comment by lizan** [comment]
@oschaaf I experienced same issue during updating to clang-8, had to modify cc_wrapper.py to force LLD. See #6534 for details.

**Comment by oschaaf** [comment]
@lizan thanks for the heads-up!
