### ISSUE TITLE
Swagger/OpenAPI generated documentation from gRPC-JSON transcoder

### ISSUE THREAD

**Issue by mattbailey** [envoyproxy/envoy#6334]
*Title*: *Generating swagger or openapi json from gRPC-JSON transcoder*

*Description*:
> The REST API that is derived from gRPC-JSON is somewhat unknown. Can envoy generate swagger or openapi documentation from transcoding in the same way that `grpc-gateway` `protoc` tooling does? Then either serve it up from `/openapi.json` and/or request the spec from envoy's v2 API somehow?
> #501 suggests this might have been an idea, I can't find any other references to it.

*Relevant Links*:
> Mentioned by @mattklein123 at the end of this issue thread: #501
> Sort of relevant: #2770

**Comment by mattklein123** [comment]
cc @lizan seems like an interesting potential enhancement.

**Comment by mattbailey** [comment]
Is there a current-best-practice way to currently inspect the request/response shape of the generated API transcoding filter?

**Comment by lizan** [comment]
Yeah it is an interesting enhancement. @mattbailey can we just re-use the [`protoc-gen-swagger`](https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger) from grpc-gateway, and serve the generated `openapi.json`, if so probably just add docs for that is enough.

**Comment by mattbailey** [comment]
> Yeah it is an interesting enhancement. @mattbailey can we just re-use the [`protoc-gen-swagger`](https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger) from grpc-gateway, and serve the generated `openapi.json`, if so probably just add docs for that is enough.

@lizan that was my initial approach, but I have no way of knowing that `protoc-gen-swagger`, which is intended to document protoc-gen-gateway's transcoding, produces the same API. Although it was modeled after it, gRPC-JSON doesn't use `protoc-gen-gateway` under the hood right?

Might be enough for a stop-gap, but I'd be worried changes in envoy or `protoc-gen-gateway/swagger` either do now, or may in the future, create subtle changes in the transcoder or the swagger.

**Comment by codyaray** [comment]
Any more thought on this? Would be interested in it

**Comment by mattbailey** [comment]
I think this is even more relevant now with the addition of the `auto_mapping` feature: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/transcoder/v2/transcoder.proto.html?highlight=auto_mapping

Since protoc-gen-swagger apparently just leaves endpoints out entirely if they don't have annotations.

**Comment by dzolotusky** [comment]
@lizan @mattbailey is there any update on this? I'd be happy with some documentation on how to generate this manually for now. Though, I don't think that that exists at the moment.

**Comment by lizan** [comment]
@mattbailey Fix for #3383 is merged yesterday.

**Comment by mattbailey** [comment]
> @mattbailey Fix for #3383 is merged yesterday.

Yeah, and it's awesome, been watching it, I just haven't checked whether it maps to what is generated by protoc-gen-swagger yet.

**Comment by dzolotusky** [comment]
OK, thanks. It'd be great to have something simpler than using protoc-gen-swagger, but that's a good start for now.

**Comment by isururanawaka** [comment]
Any update on this? we are using envoy proxy to convert gRPC to REST and we need to have swagger based interactive API documentation

**Comment by mattbailey** [comment]
I'm still personally using protoc-gen-swagger, and we've centralized our proto files which seems to have a number of benefits. It still would be extremely handy, of course.

**Comment by gektor0856** [comment]
it still relevant in 2022, any updates?

**Comment by gektor0856** [comment]
> it still relevant in 2022, any updates?

May be usefull  - resolved by [gnostic tool](https://github.com/google/gnostic).Using [protoc-gen-openapi](https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi) it can produce openapi spec from proto file
