### ISSUE TITLE
Move XDS_PROTOCOL.md into sphinx docs

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6338]
https://github.com/envoyproxy/envoy/blob/master/api/XDS_PROTOCOL.md

We should port this into the sphinx docs. It will be more discoverable, allow direct ref linking, etc.

cc @htuch @ramaraochavali

**Comment by ramaraochavali** [comment]
@mattklein123  I will take it when I get some time.

**Comment by mattklein123** [comment]
@ramaraochavali awesome no rush. Thank you!

**Comment by htuch** [comment]
+1, this makes sense, will need to make sure the sequence diagrams etc. transfer over.
