### ISSUE TITLE
upstream_rq_total is not consistent during H1 and H2 circuit breaking

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6350]
For the HTTP/1 connection pool, we increment upstream_rq_total even if the request ends up being circuit broken. For the HTTP/2 connection pool we do not. 

This is confusing and we should fix this to be consistent, one way or the other.

cc @danielhochman @junr03

**Comment by spenceral** [comment]
I can do this, I was just touching nearby code. I'll get @snowp to help me if I need backup.
