### ISSUE TITLE
Redis Proxy supports pipelined commands, but does not batch commands to Upstream

### ISSUE THREAD

**Issue by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [envoyproxy/envoy#6365]
Envoy supports Redis pipelined commands, but does not batch commands. By batching, I mean when non-pipelined or pipelined commands are sent through Envoy, Envoy should not send them upstream to Redis until a certain number of commands has been received, and then write them to the connection buffer for a particular upstream Redis in one go.

Here are our scenarios and how we handle them currently:

- Pipelined - One or more packets with as many commands as fit
- Redis - Individual packets for each command
- Multiple Clients (workers on same instance for example), same Envoy- Individual packets for each command (or pipelined set of commands)

What we would like is that if Envoy receives `GET 1`, `GET 2`, `GET 3` as discrete commands, they still get pushed up to Redis in the same packet. 

Moreover, if we have multiple clients that are sending in Redis commands pipelined or not, they also get batched. For example if client #1 send `GET 1`, `GET 2` and client #2 sends `GET 3 GET 4 GET 5` in a pipeline, Envoy, assuming the buffer is big enough, should send all of these up in the same packet.

This is closer to what systems like Twemproxy do, and should be substantially faster. In my development VM, a preliminary implementation yielded a 3-5x improvement in throughput and latency.

I'll put up a PR for this next week and hopefully do some real-world performance testing next week or week after.

**Comment by mattklein123** [comment]
@FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg I talked about this offline with @HenryYYang but can you describe how you are going to handle low rate requests? Are we going to use a flush timer? Some other algorithm? Otherwise this makes a lot of sense to me in high rate scenarios.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
There are two general approaches we could take:
1) Use a timer and to flush the buffer periodically (say, every 1ms at the longest) and also flush the buffer at request/data time if it exceeds a certain length.
2) Flush the buffer if it over a certain size, and handle low frequency requests by keeping the track of the number of currently buffered requests and comparing that to pending requests. If there are equal numbers of buffered and pending requests, flush.

## Approach 1: Timer

We decided to not go with this approach due to worrying about the overhead of a timer. I'm not very experienced with c++- if we did something like `timerfd_create` and added the file descriptor to the event loop, would that be lower overhead? Then we would flush if buffer length is exceeded in `ClientImpl::makeRequest`, and then always flush on timer callback firing.

## Approach 2: State Machine with Counters

Keep track of three states:

- Encoder buffer length
- number of pending requests
- number of buffered requests (assuming single thread, otherwise could be atomic counter)

When the client makes a request via `ClientImpl::makeRequest`, we want to flush if:

- Encoder buffer is > threshold
- number of pending requests == 0
If we flush, we set # buffered requests to zero, and if we do not flush, we increment it.

To handle low frequency requests, when the data received from upstream Redis fires `ClientImpl::onData`, we want to flush if we have a single buffered request and single pending request, and then set number of buffered requests to zero. Below are a few examples of how this works- MR is makeRequest, OD is onData, buffer max size is 192 bytes, and we give the values of the variables at the end of the operation.

```
Operation - # pending_requests - # buffered_requests - buffer_size - Write-Occurred

1) Single request

Start	0	0	0	-	
MR	1	0	0	Yes	
OD	0	0	0	No	

2) 2 requests, with the second request arriving before upstream responds
					
Start	0	0	0	-	
MR	1	0	0	Yes	
MR	2	1	64	No	
OD	1	1	0	Yes	
OD	0	0	0	No	
	
3) 4 requests, with the buffer_size limit being reached				
					
Start	0	0	0	-	
MR	1	0	0	Yes	
MR	2	1	64	No	
MR	3	2	128	No	
MR	4	0	0	Yes	(Full buffer)
OD	3	0	0	No	
OD	2	0	0	No	
OD	1	0	0	No	
OD	0	0	0	No	
```

The disadvantage of this method is that we have have potentially smaller batches- any request that comes in when nothing is buffered or pending will always get sent in a batch of one, even if other data is very close behind. If we have steady traffic and can tolerate a small delay on intermittent requests, and the timer overhead is low, that might be preferable.

**Comment by mattklein123** [comment]
I would recommend starting with the timer until you prove there is a performance problem. It's substantially simpler and Envoy has all of this built-in already as an abstraction. The main thing I don't know is what the typical timer frequency is on libevent/most versions of linux, but we can take a look at that. There is quite a bit of similar code in Envoy today, but the algorithm is roughly:
1) If buffer is currently 0 and adding to buffer, set timer for x ms.
2) If buffer is > 0, do nothing, timer is already set.
3) If buffer is > X, immediate flush, cancel timer if set.

**Comment by HenryYYang** [comment]
I think the logic of the 2nd approach is preferable.  

Essentially we send the buffered request to redis under the following conditions:
1) The upstream have already respond to all requests sent, at this point since the connection is essentially free, it make sense to flush what we have.  This also take care of the low request rate issue.
2) The buffered requests have reached the configured buffer size, we've succeed in batching the requests, also make sense to flush what we have.

To accomplish this, we just need to check for the above 2 conditions when the request is enqueue(makeRequest) and when we finish processing the redis response(onData).

This algorithm also have the following properties:
1) If the request rate is low, then it's equivalent to sent the flush timer = 1 RTT without actually using a timer.
2) As the RTT increase under load, the batch size will naturally increase and approach the configured buffer/batch size.
3) The worst case scenario is if the request rate is less than the RTT, at that point we lost pipelining and turn the client into strictly request response.  But both algorithm will suffer a similar problem.

We can tweak the algorithm to more proactively send more requests to make sure we have a certain number of batches in the pipeline or adaptively increase the batch size.  These improvements can complicated things and can probably should be a future improvements.

**Comment by mattklein123** [comment]
OK, I still think the timer is simpler, but I'm not going to argue it. SGTM.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
I've implemented the timer version here: https://github.com/envoyproxy/envoy/pull/6452

I plan on testing later this week in our redis benchmark environment against both mainline and the non-timer approach before considering merging anything, of course. Local testing in my VM indicated the timer version was significantly faster than non-timer-batching, but I don't trust my environment that much!

**Comment by mattklein123** [comment]
Fixed
