### ISSUE TITLE
Envoy deployment unsuccessful  Error : value length must be at least " '\x01' " bytes

### ISSUE THREAD

**Issue by adhanoti** [envoyproxy/envoy#6380]
I am running envoy using docker-compose and getting below error :

front-envoy_1  | [2019-03-26 07:43:06.652][000007][critical][main] [source/server/server.cc:86] error initializing configuration '/etc/front-envoy.yaml': Proto constraint validation failed (HttpConnectionManagerValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]):

Detailed logs are below :-

[root@kd-server-master front-proxy]#  docker-compose logs
Attaching to front-proxy_front-envoy_1
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:206] initializing epoch 0 (hot restart version=10.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363 size=2654312)
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:208] statically linked extensions:
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:210]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:213]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:216]   filters.listener: envoy.listener.original_dst,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:219]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:221]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:223]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.zipkin
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:226]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.capture,raw_buffer,tls
front-envoy_1  | [2019-03-26 07:43:06.647][000007][info][main] [source/server/server.cc:229]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.capture,raw_buffer,tls
front-envoy_1  | [2019-03-26 07:43:06.650][000007][info][main] [source/server/server.cc:271] admin address: 0.0.0.0:8000
front-envoy_1  | [2019-03-26 07:43:06.651][000007][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)
front-envoy_1  | [2019-03-26 07:43:06.651][000007][info][config] [source/server/configuration_impl.cc:56] loading 1 cluster(s)
front-envoy_1  | [2019-03-26 07:43:06.652][000007][info][upstream] [source/common/upstream/cluster_manager_impl.cc:136] cm init: all clusters initialized
front-envoy_1  | [2019-03-26 07:43:06.652][000007][info][config] [source/server/configuration_impl.cc:67] loading 1 listener(s)
front-envoy_1  | [2019-03-26 07:43:06.652][000007][critical][main] [source/server/server.cc:86] error initializing configuration '/etc/front-envoy.yaml': Proto constraint validation failed (HttpConnectionManagerValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]):
front-envoy_1  | [2019-03-26 07:43:06.657][000007][info][main] [source/server/server.cc:507] exiting

The yaml file which i am using is :-
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress
          route_config:
           name: local_route
           virtual_hosts:
           - name: backend
             domains:
             - "*"
             routes:
             - match:
                 prefix: "/"
               route:
                 cluster: httpbin_https
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: httpbin_https
    connect_timeout: 2.5s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: httpbin_https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.178.254.190
                port_value: 30815
    tls_context:
      common_tls_context:
        alpn_protocols: "h2"
        tls_certificates:
          certificate_chain: { "filename":"/etc/clientcert.pem" }
          private_key: { "filename": "/etc/clientprivatekey.pem" }
        validation_context:
          trusted_ca:
            filename: /etc/servercert.crt
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000

docker-compose.yaml :- 
version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
      - ./clientcert.pem:/etc/clientcert.pem
      - ./clientprivatekey.pem:/etc/clientprivatekey.pem
      - ./servercert.crt:/etc/servercert.crt
    networks:
      - envoymesh
    expose:
      - "443"
      - "8001"
    ports:
      - "443:443"
      - "8000:80"
networks:
  envoymesh: {}

Kindly let us know  if we missed anything here.

**Comment by adhanoti** [comment]
Using release envoy-1.8.0

**Comment by crisonyx** [comment]
Seeing similar issues, If I go back to the last docker tag (36f39c746eb7d03b762099b206403935b11972d8) is starts to work again for me.

**Comment by mattklein123** [comment]
Please see https://github.com/envoyproxy/envoy/pull/6376 and related issues. You need to use a version of the repo/configs/images that match. We are working to make this more clear in the docs you are looking at.
