### ISSUE TITLE
interface for overwriting end_stream during encode

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#6383]
We have a use case where we want to concatenate the response of multiple Upstream calls in our filter back to the client. The calls happen sequentially so the end of the stream of the first response tries to close the stream and the filter. The 2nd upstream call is an async call. It would be good if we can have an API provided to filter that can set the state of the stream and state of the filter based on that. We already have working code which is taking production traffic, we wanted to propose a design for doing this.

**Comment by mattklein123** [comment]
See https://github.com/envoyproxy/envoy/blob/8fb00ba4348dcbc30a012890393bf8471f119bdf/include/envoy/http/filter.h#L529 which I recently added which might do what you need.

**Comment by pitiwari** [comment]
Thanks @mattklein123. I was reading through the function comments and it says "filters should generally only return FilterDataStatus::StopIterationNoBuffer from their encodeData". 

Is this a hard requirement ? we dont want to buffer any data, we want to send the data as soon as we get data from each upstream so that time to first byte to the client is lower

**Comment by mattklein123** [comment]
@pitiwari maybe I don't understand what your use case is. Can you describe in more detail?

**Comment by pitiwari** [comment]
Thanks @mattklein123 .

The use case we are looking for, is when our filter gets the response from the 1st service ( an upstream cluster) based on this response while parsing the data in Filter’s EncodeData() we would want to make an aync call to a different service and stitch the response back to the client. We don’t want to buffer the response from the 1st service till the response from the 2nd service.

**Comment by mattklein123** [comment]
@pitiwari take a look at https://github.com/envoyproxy/envoy/blob/792e70dc0291a8d99a1783dfc27af5325f863a8a/source/extensions/filters/http/fault/fault_filter.cc#L458

It's slightly hacky, but it will do what you want. Basically, temporarily buffer the data, then write it out from an immediate callback with end stream not set, then you can control things when you get your async call data.
