### ISSUE TITLE
 disk issues while running envoy tests

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#6388]
We recently moved to 1.9 from 1.7. We are seeing disk space issues in running envoy tests in cicd. We are using ci/run_envoy_docker.sh After analyzing different folders we found _bazel_bazel is using around 50gig for each run. I wanted to know what is taking so much space and if there is any way of optimizing the space issues. Below is the df-h while our tests r running 

# df -h _bazel_bazel
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        985G   41G  895G   5% /build
# pwd
/build/tmp

**Comment by mattklein123** [comment]
cc @lizan who is also looking at disk space issues in CI

**Comment by lizan** [comment]
One big reason of using large disks are static linking all test targets, each non-stripped mostly static linked test is more than hundred MB, with 200+ test targets it costs tens of GB.
If you're interested in optimize, see https://github.com/envoyproxy/envoy/issues/1407.
