### ISSUE TITLE
represent_ipv4_remote_address_as_ipv4_mapped_ipv6 is unreferenced

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#6405]
This is mentioned in runtime at https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/runtime and proto at https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-represent-ipv4-remote-address-as-ipv4-mapped-ipv6, but I don't see this used anywhere.

**Comment by htuch** [comment]
Should this be nuked? I can't recall the original PRs involved here.

**Comment by mattklein123** [comment]
This never got implemented, though this did come up again this morning in the context of allowing easier IPv4 -> IPv6 migrations. Maybe leave it in and unimplemented for now? (Runtime docs could be removed though.)
