### ISSUE TITLE
Respect x-envoy-max-retries set to 0, despite if num_policy in RetryPolicy is NULL

### ISSUE THREAD

**Issue by lita** [envoyproxy/envoy#6407]
*Title*: *respect x-envoy-max-retries set to 0, despite if num_policy is NULL*

*Description*:
A service has set `x-envoy-max-retries` to 0, but noticed retries happening to the upstream service. After debugging, we noticed that the [num_policy in our EDS data was not set.](https://github.com/envoyproxy/data-plane-api/blob/4af3ed0740ce913c62afbe7f74d10f0b3738ec3d/envoy/api/v2/route/route.proto#L807-L810)

This created the unexpected result of retries happening, even though a service owner expected there to be none.

This is due to the fact that the code takes the [max of either the RetryPolicy value or the header value](https://github.com/envoyproxy/envoy/blob/21b3e6576260640e74b1d311cdea65bd30c04a3b/source/common/router/retry_state_impl.cc#L85).

This seems like [expected behavior](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-max-retries) but @mattklein123 believes it is a bug. So filing an issue here so we can start a conversation.

*Repro steps*:
1. Set `num_policy` RetryPolicy to NULL.
2. Send a request with `x-envoy-max-retries` to 0.

**Comment by mattklein123** [comment]
TBH I don't remember why I originally wrote the code to take the max between the header and the route config. I think for retries the header should override the config if it's set. @snowp WDYT?

**Comment by snowp** [comment]
Agree that the header should take precedence, we were very confused as to why it was doing a max. 

Being able to set it to zero from the header seems super useful, as it lets a client explicitly disable retries for a route that retries by default.

**Comment by mattklein123** [comment]
OK let's fix. Will mark help wanted, should be trivial.

**Comment by spenceral** [comment]
> should be trivial

Sounds right up my alley. I can fix this.

**Comment by mattklein123** [comment]
@spenceral great thanks. Take a look at the docs that @lita linked as they will need fixing also, and we should do a release note as well about this change. I don't think we need to config guard as IMO the current behavior is confusing and is not what people expect.
