### ISSUE TITLE
Audit and fix non-POD static members.

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#641]
As discovered in #640, the concern over static member construction/destruction order is not just hypothetical. The style guide disallows this in https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables. So, we should probably cleanup this up. 

A starting point would be `grep -r "static const"` and figuring out which are POD and not. There's also non-const static members to chase.

**Comment by mattklein123** [comment]
I'm calling this done. We are doing the right thing now and can clean things up as they cause actual issues.
