### ISSUE TITLE
Building on macOS is failing due to missing cmake

### ISSUE THREAD

**Issue by whitlockjc** [envoyproxy/envoy#6414]
*Title*: Building on macOS is failing due to missing cmake

*Description*:
>Building via Bazel on macOS High Sierra (10.13.x) fails due to missing cmake

I have been following [Building Envoy with Bazel](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md) and I've followed all the appropriate steps.  However, whenever I attempt to build _(`bazel build //source/exe:envoy-static`, it fails with the following:

```
...
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_notyou/f90d91dd38f8f339759546202a6533fd/external/envoy/bazel/foreign_cc/BUILD:112:1: error executing shell command: '/bin/bash -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory  and dependencies directory  for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify '--sandbox_debug' Bazel command line flag.

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
...
PATH=/private/var/tmp/_bazel_notyou/f90d91dd38f8f339759546202a6533fd/sandbox/darwin-sandbox/1/execroot/envoy:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
...
__________________________bazel-out/host/genfiles/external/envoy/bazel/foreign_cc/zlib/logs/CMake_script.sh: line 46: cmake: command not found

_____ END BUILD LOGS _____
rules_foreign_cc: Build script location: bazel-out/host/genfiles/external/envoy/bazel/foreign_cc/zlib/logs/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/host/genfiles/external/envoy/bazel/foreign_cc/zlib/logs/CMake.log

Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.542s, Critical Path: 0.39s
INFO: 1 process: 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

I have already created a `~/.bazelrc` file with the `build --action_env=PATH="..."` in it.  I have also tried running `bazel build` with `--action_env=PATH` and `--action_env=PATH="..."`, both to no avail and resulting in the same results.  What's interesting is no matter how I invoke `bazel build`, `PATH` in the `BUILD LOGS` **never** reflects the value of `PATH` provided to `--action_env`.  It doesn't seem like `--action_env=PATH` is getting propagated to `zlib` when building.

**Comment by lizan** [comment]
Where do you have cmake installed? Possibly due to https://github.com/bazelbuild/rules_foreign_cc/issues/225

**Comment by whitlockjc** [comment]
I think you're right, this is likely the cause.  So it's less an issue with Envoy and more an issue `rules_foreign_cc`.  If you can identify a workaround based on the information in the linked issue, feel free to keep this open to track any work that might land in Envoy but if not, feel free to close it as I'll cc myself on the linked issue.  Thanks.

**Comment by moderation** [comment]
I'm compiling on macOS without issue. I have the following line in my `.bazelrc` that I _think_ might have been added to address this issue:

`build --action_env=PATH=/bin:/opt/local/bin:/usr/bin:/usr/local/bin`

My cmake is installed via brew and is at `/usr/local/bin/cmake`
