### ISSUE TITLE
Does %RESPONSE_DURATION% include duration for ext_authz filter

### ISSUE THREAD

**Issue by hanyu-liu** [envoyproxy/envoy#6415]
A quick question. In the document, %RESPONSE_DURATION% is `Total duration in milliseconds of the request from the start time to the first byte read from the upstream host.`

Can I know if it is the total duration of all upstreams, including the ext_authz filter? Or is it just the duration of upstream in the routing part?

https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log

Thanks.

**Comment by mattklein123** [comment]
IIRC it's just the upstream routing part. cc @snowp @mpuncel

**Comment by snowp** [comment]
Yeah the duration is tracked by the router filter, so work done in previous filters will not be included.
