### ISSUE TITLE
Building an Envoy Docker image fail

### ISSUE THREAD

**Issue by snodl** [envoyproxy/envoy#6424]
*Title*:  building myself Envoy binary, and putting that in a clean Ubuntu container fail

*Description*:
I follow this steps to build binary from master branch:
$ pwd
src/envoy
$ ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'

Error logs:
1. compiling logs
Set "importmap" to different paths in each library.
This will be an error in the future.
GoLink: warning: package "github.com/golang/protobuf/ptypes/timestamp" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/timestamp:go_default_library
    @io_bazel_rules_go//proto/wkt:timestamp_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
**ERROR: /source/source/server/config_validation/BUILD:81:1: C++ compilation of rule '//source/server/config_validation:server_lib' failed (Exit 4): envoy_cc_wrapper failed: error executingcommand** 
  (cd /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/execroot/ci && \
  exec env - \
    HOME=/tmp/fake_home \
    PATH=/bin:/usr/bin:/usr/lib/llvm-7/bin \
    PWD=/proc/self/cwd \
    PYTHONUSERBASE=/tmp/fake_home \

2. finish logs
Execution platform: @bazel_tools//platforms:host_platform
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 2368.789s, Critical Path: 113.12s
INFO: 1362 processes: 1362 local.
FAILED: Build did NOT complete successfully

**Comment by rvm-segfault** [comment]
What was the resolution here? I'm seeing this error while trying to build v1.10.0 in an Ubuntu Docker container.

**Comment by renana** [comment]
Same here. It would be good to provide more information on the solution.

**Comment by rvm-segfault** [comment]
So to build this locally on my mac I need to increase the memory available to my docker container. By default docker seems to be limited to 2Gb of memory. To be able to compile the release binary and run the tests I had to bump it all the way up to 10GB. 

https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container****
