### ISSUE TITLE
Support for script loading in Envoy Redis filter

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#6439]
As I understand it, the Redis filter will today attempt to serve as a transparent hashing proxy, which means that operations has to be hashable in order to work with it. We have a use case where we'd like to ensure that a given script has been loaded into the backing Redis, so that calls to `EVALSHA` can be hashed against the backing instances. While this could be handled out of band of the Redis filter, it would greatly simplify things operationally for us if it'd possible to either 

1) have first class support for script loading in the filter: for example, Envoy could ensure that if a call to `EVALSHA` fails due to `NOSCRIPT`, then the script will be loaded into the Redis instance. This would require Envoy to be aware of the script contents itself.
2) support some form of "command broadcast", allowing us to issue a `SCRIPT LOAD` to all backing hosts. This would allow us to handle the `NOSCRIPT` ourselves by broadcasting the script to all backing instances. 

Happy to consider other ideas as well, these were just the first that came to mind.

cc @szabado

**Comment by szabado** [comment]
I'm not sure about other client libraries, but in Go there's a function Run that basically implements option 1: https://godoc.org/github.com/go-redis/redis#Script.Run, not sure about in other client libraries. That's what I used to satisfy our use case.

I feel like the broadcast option makes the most sense with the rest of the filter behavior? Having it remember the script seems very non transparent. That's just my two bits though

**Comment by mattklein123** [comment]
cc @danielhochman @HenryYYang @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg @maximebedard @msukalski for thoughts.

2 thoughts come to mind from me:
1) Some type of broadcast functionality sounds interesting to me. Perhaps this is a command we invent that allows a sub-command to be broadcast, or certain commands can be configured for broadcast.
2) What if we allow certain commands to be run every time a new connection is created by the proxy. I think this would cover this use case very nicely.

**Comment by snowp** [comment]
I think the "on new connection" suggestion works pretty well here and would transparently solve the issue on our end. WDYT @szabado ?

**Comment by HenryYYang** [comment]
This problem is currently supported by using the [hash tag](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#envoy-api-field-config-filter-network-redis-proxy-v2-redisproxy-connpoolsettings-enable-hashtagging)

The downside of this is that it doesn't allow envoy to spread the load on multiple nodes.  If we do need to spread the load, then a per connection call would be better than a broadcast.  In the broadcast approach, if a new node is added after broadcast, we'll still need to handle the NOSCRIPT case.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
How do you handle scripts now in the case where adds a shard (ie pre-redis cluster)?

I would leery of doing provisioning work in the proxy; I feel like that would be better managed by the provisioning workflow. If a shard is added, all necessary scripts should be there to begin with.

**Comment by snowp** [comment]
@FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg Currently the scripts are loaded by the app whenever we establish a connection to Redis (so essentially the same that we're talking about having Envoy do). In our case the script is app specific logic, so it's not something we'd add to general purpose provisioning.

The main benefit I see to having this be done by Envoy/the client is that you avoid depending on Redis provisioning when iterating on scripts. Being able to just update app/Envoy config is much faster than filing a ticket to the DBAs to get Redis re-provisioned. 

Our non-Envoy based solution to loading the script would be to maintain separate direct connections to Redis to load the scripts into each individual Redis instance manually, as even that would be easier than to tie this to provisioning.
