### ISSUE TITLE
how to use envoy to proxy thrift request

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/envoy#6448]
how can i use envoy to proxy thrift request, 
is there an example config for thrift?

**Comment by mattklein123** [comment]
@zuercher

**Comment by zplinuxlover** [comment]
can you offer a detailed config file for envoy thrift?

**Comment by sribalakumar** [comment]
@zplinuxlover Any luck on this ? Will help if there is any example configuration.
