### ISSUE TITLE
feature: Route Config debugging/introspection

### ISSUE THREAD

**Issue by mergeconflict** [envoyproxy/envoy#6453]
Some proxies provide a useful debugging feature for administrators, where you can query the proxy for how it would route a request.

* The input to this query is an HTTP request, encoded somehow (some thoughts on that below).
* If Envoy could route this request, the output should contain at least the name of the cluster that the request would be routed to, if it were sent "for real." It might also be useful to report one of the individual upstreams from that cluster.

There's already a route table check tool in the Envoy source (cc @hennna), but it fits in a different spot in the lifecycle: it lets you validate a static route configuration against a set of expectations. The proposed feature, in contrast, would let an administrator peek into xDS at runtime.

There's also already an experimental `/config_dump` route in the admin endpoint, but for any substantial route configuration, it will probably be too challenging for an administrator to mentally emulate how Envoy might actually route a given request. It could be paired with the route table check tool for a more assistance, but that probably requires a pretty savvy admin and a bit of scripting.

The two design points that I think are probably worth discussing a bit are authorization and how to encode the input and output. My proposal, as a starting point:

* For authorization, we sidestep the issue by implementing this feature in the admin endpoint. The assumption is, if you can see :9901 (and, for example, issue `/quitquitquit`, view all certificates, etc.) then you should also be trusted to see this route debugging info. So I'll suggest that we introduce a new `route_debug` handler in `AdminImpl` (naming suggestions are very welcome!).

* Assuming we implement this as a REST interface in the admin endpoint, the next question is how to encode the request (since routing decisions could be made on the basis of the request URI, headers and potentially even body). My thought is to just expect a urlencoded request URI to be sent a query param, and then for the rest of the request (including the request method) to be sent as-is, assuming that's possible... For example, if the original request you wanted to test was:
    ```
    POST /v1/rides HTTP/1.1
    Host: api.lyft.com
    Content-Type: application/json

    { "ride_type" : "lyft", ... }
    ```
    then you'd issue the route debug query like:
    ```
    POST /route_debug?uri=https%3A%2F%2Fapi.lyft.com%2Fv1%2Frides HTTP/1.1
    Host: <your envoy here>
    Content-Type: application/json

    { "ride_type" : "lyft", ... }
    ```

* I figure the response could be a simple JSON structure, like:
    ```json
    {
        "cluster": "foo",
        "example_upstream": "192.168.69.1:8888"
    }
    ```

Thoughts? (attn @mattklein123 @htuch) Thanks!

**Comment by mattklein123** [comment]
@mergeconflict as I mentioned in Slack, I would personally rather talk about this in the context of https://github.com/envoyproxy/envoy/issues/4283. I think it makes more sense to holistically look at this as an example "extra debug response data." 

Basically we would allow configuration in an HCM of:
1) Match on a specific header to return routing data.
2) Various security/internal/external checks if applicable.
3) Then allow configuration of populating response data/headers etc. with routing data.

This can all be done as an option for the "extra data work" that can be enhanced with initial filters/outputs later.

We could certainly do this is an admin endpoint (each HCM will need to register an admin endpoint for this task) but it feels like something that would be superseded later by the more general system? 

If we think that the admin endpoint will remain generally useful happy to continue to consider this.

**Comment by mergeconflict** [comment]
I'd be totally happy to not do this under admin -- I much prefer matching on a special header, like `X-Envoy-Debug` or something -- piggybacking on admin was just the simplest solution we could think of to the authorization problem.

Any thoughts on how to restrict use of the header?

**Comment by mattklein123** [comment]
> Any thoughts on how to restrict use of the header?

I would take a look through the linked design docs (which admittedly I haven't read in a while) and also maybe discuss with @junr03 to get his thoughts as he has been planning on working in this area off and on for a while but hasn't gotten time.

My general thinking is we can do a few different options:
1) Have configuration to only allow using the header on "internal" (trusted) requests.
2) Potentially allow an additional set of RBAC style matchers on the incoming "filter" for the extra data that would allow us to be a lot more flexible in how users allow/deny use of this feature? (Perhaps this can be tied into RBAC also, though I'm not sure if we should depend on a filter to do this so perhaps it's a subset of rules built directly into HCM processing.)

This definitely will require some thinking and a concrete proposal but it would be really great to get started on the general framework for "extra data." I would love to make this happen as I think this feature framework will be huge for users, and your concrete example can just be our initial use case to drive the design.

**Comment by htuch** [comment]
I think there is still value for the Google use case (and possibly others) of having the ability to perform dynamic route inspection out-of-band. Imagine that you manage a fleet of proxies on behalf of another party, and someone performing debugging has only access to the control plane (and /adminz), but not direct access to the data plane. It seems inherently useful to be able to have Envoy be able to perform a hi-fidelity evaluation of its route configuration via some /adminz handler or configuration plane RPC for this use case.

I agree that more broadly, there is a lot of overlap with data plane HTTP response codes and debug, it would be great to somehow unify this. Maybe we could have some way to have /adminz as an alternate request injection point? But this seems full of potential ACL and role/permissions dangers, since you might not want to grant the ability to inject data plane traffic to the role of control plane debugger.

**Comment by mattklein123** [comment]
> Maybe we could have some way to have /adminz as an alternate request injection point?

Yeah that seems scary.

If there is interest in having this be an admin output and not have it be on the request path for operational reasons, no objection from me. Can we try to write the code in such a way that most of it can be shared when we do the inline option that would allow users to return advanced data?

**Comment by mergeconflict** [comment]
> If there is interest in having this be an admin output and not have it be on the request path for operational reasons, no objection from me. Can we try to write the code in such a way that most of it can be shared when we do the inline option that would allow users to return advanced data?

Definitely. I just sent a meeting invite for next Monday (@mattklein123 @junr03 @htuch @alyssawilk @PiotrSikora) to try to hammer out a plan. I think I understand the use case Harvey describes, where our deployment allows SREs access to the control plane but not the data plane, and I also believe that richer L7 response information is something we really care about...

**Comment by mergeconflict** [comment]
Ok, after some discussion last week with @mattklein123, @junr03 and a few of us from Google, I think we came to the conclusion that the feature we're looking for here is probably different from #4283 and friends. However, there's still a pretty big design space to explore, with tradeoffs that I know I personally don't quite understand well enough yet. I'll try to capture the considerations here:

* Google uses Envoy in a multi-tenant fashion, where different listeners are configured to route traffic for different customers. My initial design above suggested packaging up an HTTP request somehow as input, to run through the route config, but I realized that doesn't really seem sufficient -- we have to determine the correct listener first. That involves matching against all the criteria in [listener.FilterChainMatch](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto.html#listener-filterchainmatch). So, for example, we'd need a way to take the port number as input as well, among other things.

* We probably care about supporting other protocols. At least QUIC, but you could imagine this being useful for any protocol supported by Envoy...

* We'd really like to avoid writing code to "mimic" how requests are routed; at best that would duplicate the real routing logic, and at worst it would give different answers. That implies that we need some way to construct a dummy request to send through the normal flow. The dummy request would still need to be handled slightly differently, though: most importantly, it shouldn't be sent upstream; the response would be synthesized by Envoy. Additionally, we may want to ignore dummy requests in logging and stats.

* We've discussed the admin interface being the place where you issue these routing queries. That has a well understood, simple security model. But it also means that we'd need to build a way of synthesizing dummy requests that the admin interface can use. Another alternative, at least for HTTP, is having the user synthesize the dummy requests on their own (that is, the user interface would effectively be curl, or similar). That's much simpler in a way, but it also requires a different auth mechanism, so that arbitrary attackers can't just send a simple debug header to introspect an Envoy's configuration.

* Another argument for using the admin interface as the starting point, rather than making the user send their own dummy requests: in some use cases at Google, where Envoy is set up for an Andromeda SDN, it's not easy to just inject traffic into a customer's data plane. And we can't ask the customer to do it for us.

Those are our thoughts on this for now... @htuch, let me know if I missed anything. Thanks!

**Comment by htuch** [comment]
Here's a strawman, I'll rely on @mattklein123 to tell me how crazy it is. Let's say that as well as instantiating listeners on workers, we also instantiate them for admin console. But, we give them an isolated stats store/log, and for something like HCM, we do something to ensure the router never is able to speak to a real upstream. 

Then, we have an RPC protocol for admin console which looks something like:
```
message ResolveRequest {
  FilterChainMatchCriteria matcher = 1;
  bytes payload = 2;
}
```

The `payload` is the initial wire bytes for a connection. This is capable of capturing H1 and H2, since they can send the connection/request preamble without having any server reply. I assume it also works for QUIC.

Then, we just run through the full connection handling. We know this is structurally safe in terms of not contributing to access log or stats, it doesn't allow injecting traffic into the data plane, and it's fully generic.

The interface would be a CLI tool that essentially acts as a proxy wrapper around `curl` or whatever tool is generating the underlying H1/H2/QUIC, and generates these RPC messages.

There's a lot I don't like about ^^, but I'll throw it out there to discuss.

**Comment by mergeconflict** [comment]
Alright, I've got an actual proposal (along with a half-baked implementation that I'll bake a bit more before sharing). I want to build a portion of @junr03's original design, after all. Specifically:

* The "Request Header match filter" and related config (at least in HCM, maybe also vhost and route);
* Support for the `x-envoy-add-upstream-cluster` request header and `x-envoy-upstream-cluster` response header;
* One additional request header not present in Jose's design: something like `x-envoy-do-not-forward`. If this request header is present, Envoy will not forward the request upstream, it will just respond locally with an empty 204 or 200, but should still append any applicable response headers (such as `x-envoy-upstream-cluster`) to that empty response. This avoids any possible ill effects of sending debug requests upstream.

The admin interface is totally uninvolved in this. We originally expected we'd need to tie in there, but we now believe we can work around any odd Google-specific virtual networking issues without touching it.

@mattklein123 @junr03 @htuch @alyssawilk @PiotrSikora @eziskind - does this seem sane?

**Comment by mergeconflict** [comment]
Jose's original design doc is here: https://docs.google.com/document/d/19IVF6SzuCYUa5K-jO22qTKCcc4qY4ckjxDXp3GE2RvE

**Comment by mattklein123** [comment]
@mergeconflict big +1 on roughly that proposal, which is similar to what I was going to suggest in response to the admin proposal (do not forward). I think trying to have this happen within the confines of admin is going to end up a bit nutty and I would love to avoid it.

**Comment by htuch** [comment]
I'm also on board, this is a nice low touch approach. We're still adding a "do not forward" capability here to router, but it's a pretty lightweight change to what exists today.

**Comment by mattklein123** [comment]
I think having do not forward is generally useful, and will play in well with other features we want in the future, so I think it's a big win either way.

**Comment by alyssawilk** [comment]
Is do not forward substantially different from the router's existing direct response path?  Can we refactor that to do what we're looking for here?

**Comment by mergeconflict** [comment]
> Is do not forward substantially different from the router's existing direct response path? Can we refactor that to do what we're looking for here?

Not substantially different at all; my work-in-progress impl is just a few additional lines of code in the router.

**Comment by xocodergit** [comment]
@mergeconflict Hi dan, your proposal in this Issue is greate and thanks to your contribution, it looks very useful. I've read your code and noticed I need to create and install it manually, since I really not well known about Envoy, I totally have no idea about how to do these things, If there are any example or documentations i would very appreciated

**Comment by nitishm** [comment]
Question: Can this be done using WASM filters?
