### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by kvkk** [envoyproxy/envoy#6456]
**Issue Template**

*Title*: Connection issues with grpc server when using envoy with TLS

*Description*:
>I got a java client talking to a python grpc server. I deployed envoy to act as a load balancer. Everything was working after a little bit of tweaking when TLS is not enabled. Once I added TLS context, I started seeing ALPN negotiation failed issue. I added alpn_protocols:[h2] in my envoy config which pushed me to next blocker. Now I am seeing *RPC failed: Status{code=UNAVAILABLE, description=upstream connect error or disconnect/reset before headers, cause=null}* error. 
I got all these services (java client app, envoy, python server) running on OpenShift environment. 
My config yaml:
*
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              require_tls: ALL
              routes:
              - match: { prefix: "/" }
                route: { cluster: python-server, timeout: 60s}
          http_filters:
          - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
            certificate_chain: { "filename": "/envoy_server.cert" }
            private_key: { "filename": "/envoy_server.key" }
          alpn_protocols: [ "h2" ]
          validation_context:
            trusted_ca:
              filename: /python-server.cert.pem
  clusters:
  - name: python-server
    connect_timeout: 15s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    lb_policy: LEAST_REQUEST
    hosts: [{ socket_address: { address: python-server, port_value: 10000 }}]
*
Any pointers are appreciated

**Comment by Duanzhiwei** [comment]
I encountered a similar problem, did you solve it?
