### ISSUE TITLE
X-Envoy-Internal Documentation Inconsistent

### ISSUE THREAD

**Issue by dfjones** [envoyproxy/envoy#6457]
*Description*:
The latest Envoy documentation describes the expected behavior of how X-Envoy-Internal is decided.

The notes at the end of XFF section say this:

> XFF is what Envoy uses to determine whether a request is internal origin or external origin. If use_remote_address is set to true, the request is internal if and only if the request contains no XFF and the immediate downstream node’s connection to Envoy has an internal (RFC1918 or RFC4193) source address. If use_remote_address is false, the request is internal if and only if XFF contains a single RFC1918 or RFC4193 address.

My takeaway here is: when `use_remote_address=false` only the XFF header is used to decide if the request is internal or external. 

However, a few lines above this we have Example 5:

> Example 5: Envoy as an internal proxy, receiving a request from an internal client
Settings:
use_remote_address = false
xff_num_trusted_hops = 0
Request details:
Downstream IP address = 10.20.30.40 (address of the internal client)
XFF is not present
Result:
Trusted client address = 10.20.30.40
X-Envoy-External-Address remains unset
X-Envoy-Internal is set to “true”

This example makes it seem like when `use_remote_address = false` and XFF is absent, the remote address will be used to determine that `X-Envoy-Internal` is set to "true".

From my testing the first quote accurately describes the behavior and Example 5 is misleading/incorrect.

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for

**Comment by mattklein123** [comment]
@dfjones yeah that's a doc bug, your assessment is correct. Can you potentially fix the docs?

**Comment by artbegolli** [comment]
shotgun
