### ISSUE TITLE
bazel hangs in coverage build

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#6474]
Example: https://circleci.com/gh/envoyproxy/envoy/192832?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link from https://github.com/envoyproxy/envoy/pull/6467

I think this is an issue with the circleci codecov and not the change, as the change just modifies a comment.

**Comment by mattklein123** [comment]
I think this is a bazel issue. @lizan I mentioned this recently and I've been seeing this a fair amount. Any idea here?

**Comment by lizan** [comment]
This should now fixed by https://github.com/envoyproxy/envoy/pull/6752.
