### ISSUE TITLE
upstream destroy stats missing from HTTP conn pools

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6478]
Was just doing some debugging and realized that the following stats are not incremented in the HTTP connection pools, but only the TCP connection pool:

```
upstream_cx_destroy
upstream_cx_destroy_local
upstream_cx_destroy_remote
```

This is confusing and we should fix. I don't recall the history here but I'm guessing these were implemented for the TCP connection pool and never ported over. I think we could easily have a shared utility function that helps us unify this logic across the pools.

**Comment by HashedDan** [comment]
I would be happy to take this one!

**Comment by mattklein123** [comment]
Please do @HashedDan!
