### ISSUE TITLE
Max header size

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#6480]
*Title*: *Why the 60K cap?*

*Description*:
I'm curious about [this comment](https://github.com/envoyproxy/envoy/blob/v1.9.0/source/common/http/conn_manager_impl.cc#L610-L617)

> Check for maximum incoming header size. Both codecs have some amount of checking for maximum header size. For HTTP/1.1 the entire headers data has be less than ~80K (hard coded in http_parser). For HTTP/2 the default allowed header block length is 64k. In order to have generally uniform behavior we also check total header size here and keep it under 60K. Ultimately it would be nice to have a configuration option ranging from the largest header size http_parser and nghttp2 will allow, down to 16k or 8k for envoy users who do not wish to proxy large headers.

The `min()` of 80K and 64K is 64K. Can you elaborate on what "generally uniform behavior" is? I'm not sure where this reduction of 4K is coming from. Any reason not to use 64K?

**Comment by mattklein123** [comment]
cc @auni53 for comment who recently worked in this area.

**Comment by auni53** [comment]
Significant changes have occurred in this area. If you look at my latest PRs, the limit is now configurable up to a max of 96 KiB. I can't speak for when that change will be put out, but it should make it into the next release whenever that is.

As for why the conservative approach for limiting? It's an attack vector, so it makes sense to only support what we're 100% won't break. Part of my work included a bunch of extra tests around that.

**Comment by phylake** [comment]
> As for why the conservative approach for limiting? It's an attack vector, so it makes sense to only support what we're 100% won't break

And subtracting 4K gave that 100% guarantee? Not trying to be pedantic, btw. I have a need to raise it in a previous version of envoy so I'm trying understand the rationale and if I'm going to break anything.

**Comment by auni53** [comment]
Ah, I have no idea or justification for the 60K limit. If you want to raise it on this release you should probably just cherrypick my PRs; I don't remember exactly what breaks when and what needs to be configured.

**Comment by phylake** [comment]
Thanks for the help @auni53!

**Comment by ashish-sparrows** [comment]
Is **Max header size** is configurable is any recent release?

**Comment by ramaraochavali** [comment]
Yes it is . Please check [max_request_headers_kb](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-max-request-headers-kb)

**Comment by ashish-sparrows** [comment]
@ramaraochavali  any example how to set it?

**Comment by ramaraochavali** [comment]
unfortunately I could not find an example. But you have to set on http_connection_manager config
