### ISSUE TITLE
Document Websockets support w.r.t. HTTP/2

### ISSUE THREAD

**Issue by jamessynge** [envoyproxy/envoy#6528]
Websocket support over HTTP/2 was added via work on issue #1630, but the Envoy documentation continues to imply that the support is only for HTTP/1. It would be helpful if the documentation were updated accordingly.

See: https://www.envoyproxy.io/docs/envoy/v1.5.0/intro/arch_overview/websocket.html?highlight=websocket

**Comment by alyssawilk** [comment]
I think you may have picked up an old version. Does this address your docs request?
https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/websocket.html?highlight=websocket

**Comment by jamessynge** [comment]
Oh, darn. I used this service called "google" to find docs, and forgot to look for the latest version. Sigh.

**Comment by alyssawilk** [comment]
I feel your pain - the number of times Google has pointed me at v1 docs and Harvey has gently corrected me....  :-P

**Comment by jamessynge** [comment]
Maybe we should update the docs to point to the official RFC?

**Comment by jamessynge** [comment]
I.e. point to https://tools.ietf.org/html/rfc8441
instead of https://tools.ietf.org/html/draft-mcmanus-httpbis-h2-websockets-02

I'll send a PR
