### ISSUE TITLE
Feature Request: Exchange arbitrary metadata between sidecars at connection time

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#6532]
*Title*: *Exchange arbitrary metadata during TLS handshake or some other process*

*Description*:
In order for Envoy to produce rich telemetry about details of source and destination workloads, we need a mechanism to exchange this information.

As an example, Istio telemetry produces highly dimensioned metrics that identify source and destination of the traffic. The metrics are dimensioned using source and destination metadata such as NodeID and labels associated with the pods or VMs.

For HTTP this can be achieved easily by forwarding the node metadata to destination in a well-known header, and the destination responding with its own header.
Even though the above solution works, it needlessly sends the same information over and over with every request.

For TCP this does not work, and we have to rely on ip address to metadata mapping at the destination and source. 

Options:
1. When mTLS is used, it gives us a way exchange this metadata up front.
If there is a way to add metadata during TLS handshake, it works.
2. Use Ha`Proxy protocol` to exchange this information. Not sure if it works both ways.
3. https://www.akamai.com/us/en/multimedia/documents/technical-publication/tls-aux-associating-auxiliary-data-tls-connections.pdf

**Comment by mandarjog** [comment]
@PiotrSikora

**Comment by gargnupur** [comment]
Exploring if TCP over HTTP/2 metadata frames can be used to implement this...

We would need both these issues fixed for that afaik:
1) https://github.com/envoyproxy/envoy/issues/1630
2) https://github.com/envoyproxy/envoy/issues/2394

**Comment by gargnupur** [comment]
/cc @alyssawilk 

To use TCP over HTTP/2 metadata frames, looks like support for TCP over HTTP(https://github.com/envoyproxy/envoy/issues/1630) is a blocker right now.

We are going to explore TLS extension path for which https://github.com/envoyproxy/envoy/issues/173 is currently a blocker..

Ref: @kyessenov  has a great doc on metadata exchange https://docs.google.com/document/d/1bWQAsrBZguk5HCmBVDEgEMVGS91r9uh3SIr7D7ELZBk/edit.

**Comment by mandarjog** [comment]
A required PR to enable "network filters for upstream" https://github.com/envoyproxy/envoy/pull/7503

**Comment by gargnupur** [comment]
@mandarjog : I think this can be closed now...
