### ISSUE TITLE
Feature Request: add response code details for sendLocalReply

### ISSUE THREAD

**Issue by eziskind** [envoyproxy/envoy#6542]
http://go/gh/envoyproxy/envoy/pull/6530 is adding a "response code details" field to the StreamInfo so that access logs can determine whether a response came from the upstream or envoy itself because of a sendLocalReply. To provide better context, calls to sendLocalReply should include a response code details string to set in the StreamInfo.

Related to #1178

**Comment by eziskind** [comment]
@alyssawilk fyi

**Comment by alyssawilk** [comment]
My end goal (which is up for debate all by itself) is to have every call site of sendLocalReply associated with a custom string response code details.  In-house we use said string both in debug headers (sent to trusted IPs which let you see for every response exactly what line of code triggered the response handling) as well as access logs.

I think this would be super useful for access logs, as well as the details field for the proxy-status* header (by default, the details field probably only supplied to debug IPs).  Given our immediate needs were using our own in-house non-standards-compliant rc_details header, what I wanted to sign up for was making sure the very detailed string was present in StreamInfo.   That said, exposing this in access logs or debug-response headers (which gets us access logs for free) would be super useful and I might be up for that if we can avoid it being too much extra work.  Easiest would be a temporary x-envoy-debug-details-are-going-away-soon while IETFers iterate on proxy status, but that's probably too hacky to be a good interim solution.  Next easiest would be access logs, if someone else has strong feelings about how it should be exposed and wants to field bike-shedding.  Least easy and most churn would probably be proxy-status, but that does get us response headers to debug IPs as well as details in access logs for responses sent to debug IPs.

Thoughts?  @mattklein123 @junr03 @PiotrSikora 

*https://tools.ietf.org/html/draft-nottingham-proxy-status-00

**Comment by PiotrSikora** [comment]
I'd recommend implementing `Proxy-Status` (as-is), assuming that we're willing to follow changes in the IETF draft. This might require having an undocumented config option, since the header values might change, but it's probably not worse than having `x-envoy-debug-details-are-going-away-soon`.
