### ISSUE TITLE
feature request: limiting with bandwidth

### ISSUE THREAD

**Issue by yutongp** [envoyproxy/envoy#6551]
Hi, 

would like to check if envoy could support similar feature like this:
https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/#limit_bandwidth
to limit on bandwidth for tcp connection.

related to: #6276 

Thanks.

**Comment by mattklein123** [comment]
No, not currently. I did recently add response bandwidth limiting for the HTTP fault filter. It would not be difficult to do something similar for TCP but would require some work.
