### ISSUE TITLE
Missed upstream disconnect (503) not retried with 5xx or retriable-status-codes and "503"

### ISSUE THREAD

**Issue by jaygorrell** [envoyproxy/envoy#6575]
*Title*: *Missed upstream disconnect (503) not retried with 5xx or retriable-status-codes set to "503"*

*Description*:
>Upstream disconnects as described in https://github.com/envoyproxy/envoy/issues/6190 are not retried with `retriable-status-codes` (set to 503) or even with `5xx`.

**Comment by jaygorrell** [comment]
Looks like this is related to https://github.com/envoyproxy/envoy/issues/5876, which went stale. Feel free to reopen that if it makes more sense instead.

**Comment by htuch** [comment]
@jaygorrell reopened https://github.com/envoyproxy/envoy/issues/5876, let's continue discussion there, thanks.
