### ISSUE TITLE
data-plane-api lack tracing.operation_name: ingress

### ISSUE THREAD

**Issue by chainhelen** [envoyproxy/envoy#6598]
***Title***: *data-plane-api lack tracing.operation_name: ingress*

***Description*:**
>When I send Ads to all local envoy dynamiclly，I find that lacking tracing.operation_name: ingress

***Repro steps*:**
```
import (  
        ...
    http_conn_manager "github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2"
        ...
)
    listenFilterHttpConn.Tracing = &http_conn_manager.HttpConnectionManager_Tracing{
        OperationName:  http_conn_manager.INGRESS,  
        RandomSampling: &_type.Percent{Value: 1.0},
    }

    listenFilterHttpConnConv, err := util.MessageToStruct(listenFilterHttpConn)
```

***Config dump*:**
I expect 
```
    tracing:
        operation_name: ingress
        random_sampling: 1.0
``` 

but  in fact, as below
```
    tracing:
        random_sampling: 1.0
```

***Guess*:**
I guess， maybe  
```
OperationName HttpConnectionManager_Tracing_OperationName `protobuf:"varint,1,opt,name=operation_name,json=operationName,proto3,enum=envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager_Tracing_OperationName" json:"operation_name,omitempty"`
```
`omitempty` cause this promble, becase `http_conn_manager.INGRESS` is 0 in actually.

**Comment by htuch** [comment]
@chainhelen that sounds right; is this an actual problem for you or were you curious as to why it wasn't appearing?

**Comment by chainhelen** [comment]
@htuch Thx for your reply.

I expect
```
    tracing:
        operation_name: ingress
        random_sampling: 1.0
```
but in fact, as below
```
    tracing:
        random_sampling: 1.0
```
En, I just care，does this affect the final effect for envoy?

**Comment by htuch** [comment]
@chainhelen no, Envoy will fill in the default when the proto is parsed from the wire (or YAML).

**Comment by chainhelen** [comment]
@htuch ok, get it.Thx for your reply
