### ISSUE TITLE
Change headers after encodeData.

### ISSUE THREAD

**Issue by panzhongxian** [envoyproxy/envoy#6600]
Can I change HTTP headers like "Content-Length" after encodeHeaders?

 The length changed after encodeData, but I can't change headers even if I stored the pointer of headers' reference passed in encodeHeaders().

I found a similar scene in gzip_filter, which remove the Content-Length in encodeHeaders(). But this will cause chunked http response. So, what can I do change the header according to body. 

Thanks.

**Comment by htuch** [comment]
@mattklein123 @alyssawilk is there a clean way to do this?

**Comment by mattklein123** [comment]
Once you call `encodeHeaders()` the headers may be written to the wire, so they cannot be changed after that fact. If you need to change the headers you need to buffer until you know the final header values and then they can be continued.
