### ISSUE TITLE
Unable to parse :: (INVALID_ARGUMENT:rate_limit_service) in the envoy:latest version

### ISSUE THREAD

**Issue by rashidfornajah** [envoyproxy/envoy#6615]
*Title*: *Unable to parse :: (INVALID_ARGUMENT:rate_limit_service)*

*Description*:
>The latest version of Envoy is unable to parse the yaml with rate_limit_service. With below version it is working fine:
image: envoyproxy/envoy:628d1668d7dc9244e3a8fa3d3fbabca23e92e23d

*Config*:
>rate_limit_service:
    grpc_service:
        envoy_grpc:
            cluster_name: rate_limit_cluster
        timeout: 0.25s

*Logs*:
>envoy_1     | [2019-04-17 06:21:52.089][1][critical][main] [source/server/server.cc:90] error initializing configuration '/tmp/envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:rate_limit_service: Cannot find field.):

**Comment by htuch** [comment]
@rashidfornajah the configuration example you provide here is not clear enough to diagnose the issue, but I'm guessing this relates to the deprecation of RLS in bootstrap config in https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated#version-1-9-0-dec-20-2018?

**Comment by rashidfornajah** [comment]
@htuch if RLS is deprecated in bootstrap config then please explain how to use it?

**Comment by htuch** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/thrift_filters/rate_limit_filter.html?highlight=rate%20limit describes how to add a filter, the config for this is in https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/thrift/rate_limit/v2alpha1/rate_limit.proto#envoy-api-msg-config-filter-thrift-rate-limit-v2alpha1-ratelimit.
