### ISSUE TITLE
Using request_headers_to_ad to set Host header, the port value is removed!?

### ISSUE THREAD

**Issue by alessandro-vincelli** [envoyproxy/envoy#6633]
I'm trying to perform this configuration:
`        request_headers_to_add:
            - header:
                key: "Host"
                value: "127.0.0.1:10000"
              append: false
`
But on the http request the "Host" header lost the value port:
"Host": "127.0.0.1"
Is this an intentional Envoy behavior? Or I'm using a wrong configuration?
Thanks in advance.
Alessandro

**Comment by htuch** [comment]
I think you probably want to use `host_rewrite` instead of `request_headers_to_add`. The `host` header is special and has a bunch of interactions with HTTP connection manager and the codecs.

**Comment by alessandro-vincelli** [comment]
Thanks hutch, Evoy it works correctly, my fault, the header was override by another system.
