### ISSUE TITLE
Maintain consistent Jinja versions

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#6634]
We specify Jinja version both in `repository_locations.bzl` and various `requirements.txt` in the repository. Ideally we keep these in sync, e.g. to deal with security releases. 

Ideally we can do this mechanically (e.g. presubmit check, single source of truth).

**Comment by moderation** [comment]
In theory we can set environment variable for the requirements.txt files that we have - https://github.com/pypa/pip/blob/master/docs/html/reference/pip_install.rst#id33.

Is there a place in the repo where we can specify for example a Jinja2, protobuf, grpc, six and MarkupSafe version and then have referenced by the relevant `bazel/repository_locations.bzl` and the `requirements.txt` files?

**Comment by htuch** [comment]
Another possible approach would be to import `repository_location.bzl` into the virtenv setup script; Since Skylark (.bzl) is a subset of Python, we could import it directly and access the definitions in this file.

**Comment by phlax** [comment]
i think this is resolved, closing
