### ISSUE TITLE
Timeout in fault_filter_integration_test

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#6635]
Timeout seen in this branch build: https://circleci.com/gh/envoyproxy/envoy/200487?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Seems to get stuck in `Protocols/FaultIntegrationTestAllProtocols.HeaderFaultConfig/IPv4_Http2Downstream_HttpUpstream`

**Comment by mattklein123** [comment]
cc @jmarantz I think this is related to what I was DMing you about yesterday. Let's chat when you are back in the office.

**Comment by mattklein123** [comment]
I think this is fixed with my recent changes.
