### ISSUE TITLE
Add a new xDS (Token Discovery Service) and an http filter to inject security tokens into proxied requests

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#6639]
*Title*: 

Proposal to add a new `xDS` (`Token Discovery Service`) and an http filter to inject security tokens into proxied requests.

*Description*:

One of the common problems that every IT company has to solve is finding a way to gradually modernize their infrastructure.

While it seems compelling to turn every new service into API, add client authentication and so on, there is always a heritage of legacy systems that is a pain to update (to play nicely with the new world).

In particular, adding support for client authentication usually implies both source code changes and secret management on client side.

It would be a smarter choice to offload credential injection onto a side car proxy instead.

*Proposal*:

- Add a new HTTP filter to inject security tokens into proxied requests
- Add a new `xDS` (`Token Discovery Service`) to facilitate credential management and rotation

To be clear, `Token Discovery Service` is only responsible for delivering fresh security tokens, how they get obtained is out of scope.

The solution can be useful to a wide range of users:
- more tech savvy companies could integrate `Token Discovery Service` with a tool like Vault
- others could put `TDS` data into a static file and still benefit from credential rotation

**Comment by htuch** [comment]
@yskopets could SDS perform this role?

**Comment by qiwzhang** [comment]
@htuch no, current SDS only works for SSL certificates. It needs to add a new secret type for fetching JWT token.

**Comment by htuch** [comment]
I think extending it to cover other secret types would be the recommended approach. The advantage of is we don't create another very similar API for a similar class of resources. If you're integrating with Vault, this would make sense whether this is tokens or certs.

**Comment by qiwzhang** [comment]
@yskopets It can be easily implemented by using either GrpcAsyncClient or HttpAsyncClinet together with InitManager.  Not need to follow Envoy Subscription model.

**Comment by htuch** [comment]
@qiwzhang yes, this is possible. However, I know at least one other use cases (@JimmyCYJ) where folks are interested in pulling in authentication credentials via SDS, so this seems a reasonable extensions to SDS. By making SDS more readily consumable by filters and other extensions, we avoid having to reinvent things like secret rotation lifecycle handling, cross-thread sharing and develop a common framework for reference counting objects. OTOH, this is probably a bit of work to make work well.

**Comment by mattklein123** [comment]
@yskopets do you mind describing your use case in a bit more detail, perhaps with a concrete user flow? It's not clear to me how the secrets are being fetched. Is it per-request? Cached somehow? Etc. It's hard to tell what would be the best solution without more detail IMO.

**Comment by yskopets** [comment]
@qiwzhang I like Envoy Subscription model because it can be backed by a static file

**Comment by yskopets** [comment]
@mattklein123 I had 2 scenarios in my mind:

1) legacy application running in a datacenter needs to talk to a new service in the cloud that requires OAuth token.

    Infrastructure in the datacenter is Puppet-based, almost all configuration is happening through static files generated by Puppet.

    The preferred solution would be to let Puppet periodically re-generate a static file with token data. 
    
    It's a responsibility of Puppet/cron to re-generate the file before the previous token expires. 

    Envoy will be configured to use that file as a source of `TDS`. HTTP filter will inject the token "as is" into every outgoing request.

2) application that is running on Kubernetes needs to talk to 3rd party api that requires OAuth token.

    In the context of k8s we have a CRD that represents application's request for an OAuth token and a k8s controller that generates OAuth tokens and puts them into k8s Secrets.

    It's responsibility of k8s controller to regenerate the token before the previous one expires. 

    The preferred solution would be to change the format of data stored in a k8s Secret - from plain secret (right now) to a file in the format of `TDS`.

    k8s Secret will be mounted as a file, Envoy will configured to use that file as a source of `TDS`. HTTP filter will inject the token "as is" into every outgoing request.

**Comment by mattklein123** [comment]
@yskopets if you agree https://github.com/envoyproxy/envoy/issues/6654 can cover this, can we close this and track there?
