### ISSUE TITLE
C++14/17 upgrade compiler requirements

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#664]
There are some features in 14/17 that would be useful. It's unclear what is a reasonable minimum compiler version. We should start thinking about what an upgrade path would look like, first probably to 14.

**Comment by htuch** [comment]
It would be good to spec out both a valid version of `clang` and `gcc` at the same time. `clang` would be good for #443 and saner compiler error messages.

**Comment by mattklein123** [comment]
Agreed. Let's discuss soon.

**Comment by dnoe** [comment]
This will be useful: http://en.cppreference.com/w/cpp/compiler_support

Looks like the minimum to support all C++14 features is GCC 5.0/Clang 3.4.
The minimum to support all C++17 features is GCC 7, and Clang supports everything but splicing maps and sets as of version 5 which is not yet formally released.  Almost all of the C++17 features are available by version 4, however, so we might want to pick a restricted set of C++17 features for now if we want any C++17 at all.

**Comment by htuch** [comment]
That's a neat resource. I'd also be interested in understanding the baseline `lib[std]c++` version for various features. I think the regex issue in earlier versions of `gcc` isn't just about compiler version but also `libstdc++` support. 

I hit this when trying to build and test with Clang 3.4 and the older `libstdc++` on my workstation. Usually the compiler and standard libraries are somewhat closely versioned, but it's possible to get into situations where this isn't the case it seems.

**Comment by mattklein123** [comment]
Yes, it's incredibly frustrating. For example, GCC 4.8 will compile std::regex but then it crashes at runtime.

I think C++17 is probably too new, but starting to allow C++14 seems reasonable if we want to have a minimum of GCC 5.

**Comment by dnoe** [comment]
Looks like there is an option to statically link libstdc++ as of gcc 4.5
with the -static-libstdc++ compiler option.  This maybe a possible solution
especially since  I understand the default is to statically link Envoy
anyway. I think it is possible for Clang as well (on Linux) with a
different option.

On Apr 1, 2017 21:31, "Matt Klein" <notifications@github.com> wrote:

Yes, it's incredibly frustrating. For example, GCC 4.8 will compile
std::regex but then it crashes at runtime.

I think C++17 is probably too new, but starting to allow C++14 seems
reasonable if we want to have a minimum of GCC 5.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/lyft/envoy/issues/664#issuecomment-290958464>, or mute
the thread

**Comment by htuch** [comment]
Yeah, that will decouple from the runtime environment but we still need to ensure the toolchain itself has the right library - standard installs will likely but it's possible to get into weird situations when you have multiple toolchains on the same machine and they either share libraries or flags are incorrectly set. So, as long as we specify clearly the baseline versions of `lib[std]c++` I think we're all good there.

BTW, for Bazel, here's the static link story https://bazel.build/versions/master/docs/be/c-cpp.html#cc_binary.linkstatic, there are 3 levels of dynamic/static to select between.

**Comment by mattklein123** [comment]
The cmake build already statically links libstdc++ for this reason. Presumably the bazel build does also, but I haven't been tracking how close we are to parity there yet.

**Comment by htuch** [comment]
Not yet with Bazel, it's only linking in "mostly static" configuration right now, I'll take an action item to add this in the next few days.

**Comment by mattklein123** [comment]
@dnoe @htuch now that we are basically telling people to use GCC > 5 (and using 5.4 in CI) I think we can turn on C++14 if we want. What does this mean for G internal builds?

**Comment by dnoe** [comment]
@htuch and I will discuss offline and get back to you.

**Comment by dnoe** [comment]
We'll need a little bit longer to make this move internally - perhaps the end of the quarter.  Is that OK with you?

**Comment by mattklein123** [comment]
Sure, I'm in no rush on this at all, was just going through and cleaning up issues.

**Comment by mattklein123** [comment]
@dnoe @htuch anyone else, thoughts at this point on moving minimum required compiler to GCC 5+ and turning on C++14?

**Comment by ggreenway** [comment]
I'm in favor of this change.

**Comment by mattklein123** [comment]
Calling this done as we just moved to C++14. C++17 won't likely happen for a while.
