### ISSUE TITLE
Add `injectDataToFilterChain(data, end_stream)` methods to NetworkFilter callbacks

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#6640]
*Title*: Similarly to HTTP use case, add `injectDataToFilterChain(data, end_stream)` methods to NetworkFilter callbacks

*Description*:

Recently, new methods have been added to `StreamFilterCallbacks` in order to support low bandwidth simulation (see #6242):

* `StreamDecoderFilterCallbacks::injectDecodedDataToFilterChain(data, end_stream)`
* `StreamEncoderFilterCallbacks::injectEncodedDataToFilterChain(data, end_stream)`

It would be useful to have methods with the same semantics in the context of NetworkFilters as well.

Example use cases include:

* low bandwidth simulation at L4 (see #5942)
* piping request/response data through an out-of-process filter (see #5209)

**Comment by mattklein123** [comment]
@yskopets thanks for opening, I just checked and yes, you are correct, we will need these new APIs to do similar things as what we are doing for HTTP. Conveniently, the implementation should be much easier. Will mark help wanted.

**Comment by yskopets** [comment]
@mattklein123 Great! I will try to implement it
