### ISSUE TITLE
bootstrap and xDS should have separate support for allow unknown fields

### ISSUE THREAD

**Issue by fuqianggao** [envoyproxy/envoy#6651]
Currently, --allow-unknown-fields is false by default. Any unknown fields in bootstrap will be caught early and xds response sent by management server with unknown fields will be rejected. 

It would be helpful if we can have separate control of allow unknown fields for bootstrap and xds. This way, typos in bootstrap can still be caught early by not allowing unknown fields on bootstrap; while management server can set new fields in the xds and not worry that an Envoy running in an older build will reject the config by allowing unknown fields on xds.

**Comment by htuch** [comment]
+1, this is really important when dealing with security fix releases as well.

**Comment by mattklein123** [comment]
+1 makes sense to me.

**Comment by htuch** [comment]
Still in progress on a low priority thread.
