### ISSUE TITLE
Panic mode on cluster membership changes?

### ISSUE THREAD

**Issue by akropp-stripe** [envoyproxy/envoy#6653]
*Description*:
We are investigating some odd panic routing metrics that envoy is emitting. As far as we can tell nothing is actually _wrong_ with our request pipelines, but we want to trace this down as its causing spurious alerts.

We can clearly correlate cluster membership changes:

![image](https://user-images.githubusercontent.com/42393871/56398377-0630ea80-61fd-11e9-8855-513321ede936.png)

With panic routing

![image](https://user-images.githubusercontent.com/42393871/56398385-0e892580-61fd-11e9-9d47-212e3b3b7f4c.png)

Our stats all say that all attempted health checks passed, there are no failures:

![image](https://user-images.githubusercontent.com/42393871/56398768-34afc500-61ff-11e9-9ae5-31ec02bc2253.png)

We added health check event logging and can see that we get

```
add_healthy_event:	{	
   first_check:	 true	
}	
```
When the cluster membership changes.  

I was opening this issue to see if there was any insight as to what could be causing this, or suggestions into debugging attempts.

Our relevant cluster configuration looks like:

```
"dynamic_active_clusters": [
    {
     "version_info": "d63a8ee91ca7f647e623c3c5113a61d62be6fc23e09dbd2b73a7dc85a2e50e37",
     "cluster": {
      "name": "internal_cluster",
      "type": "STRICT_DNS",
      "connect_timeout": "2s",
      "health_checks": [
       {
        "timeout": "3s",
        "interval": "4s",
        "unhealthy_threshold": 2,
        "healthy_threshold": 2,
        "http_health_check": {
         "path": "/healthcheck"
        },
        "no_traffic_interval": "4s",
        "event_log_path": "/var/log/envoy_health_event.log"
       }      
      "http2_protocol_options": {},
      "upstream_connection_options": {
       "tcp_keepalive": {
        "keepalive_time": 120
       }
      },
      "load_assignment": {
       "cluster_name": "apiori",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "def.dns.entry",
              "port_value": 10652
             }
            }
           },
           "load_balancing_weight": 50
          },
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "abc.dns.entry",
              "port_value": 10652
             }
            }
           },
           "load_balancing_weight": 50
          }
         ]
        },
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "xyz.dns.entry",
              "port_value": 10652
             }
            }
           },
           "load_balancing_weight": 100
          }
         ],
         "priority": 1
        },
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "xyz.dns.entry",
              "port_value": 10652
             }
            }
           },
           "load_balancing_weight": 100
          }
         ],
         "priority": 2
        }
       ],
       "policy": {
        "overprovisioning_factor": 198
       }
      }
     },
     "last_updated": "2019-04-18T21:13:33.619Z"
    },
```

When we do cluster changes via a connected CDS we update the clusters LB endpoints to point to different dns entries, but otherwise everything stays the same.

We are on envoy version:  ```envoy 0/1.9.0-dev//RELEASE live 1394162 3549119 1```
Thanks!

**Comment by snowp** [comment]
I think it's possible to trigger panic mode on cluster updates since hosts are initially unhealthy when they are added to the cluster, and won't go healthy until they've been health checked. 

Are you able to look at the membership_total/membership_healthy stats? I think that would let you confirm wether this is happening

**Comment by akropp-stripe** [comment]
Hmm, I do see that sometimes total membership/healthy status seems to vary during these cluster changes, but its not always consistent across all our fleet.

**Comment by snowp** [comment]
Currently no, but I've been thinking that it would make sense to only count a host towards panic mode/priority spillover after it's first health check. This would also work better with dynamic deployments like Kubernetes that might add a bunch of new hosts before removing the old ones. @mattklein123 does this seem like a reasonable thing to do?

You might also be getting bit by #6625, where unhealthy hosts will remain in a cluster if they were healthy when the update happened. In this case however I'd expect you to see the panic mode enabled for longer after the update happened.

**Comment by akropp-stripe** [comment]
So we don't have any "unhealthy" hosts. All our hosts are healthy, per all the metrics and health event logging. It seems kind of odd to me that swapping in new DNS values for a cluster could cause a panic.  Are there any strategies to avoid this? We'd like to be able to have our internal alerting fire on panic, but if it happens every time we update a cluster its not a meaningful metric for us

**Comment by snowp** [comment]
I think the way other people are getting around this is by having enough hosts in their clusters that panic mode won't trigger. There are certainly changes we can make to this to make it better (as mentioned earlier in this thread), but right now new hosts are going to join the pool as unhealthy.

**Comment by akropp-stripe** [comment]
Ok, thanks for the info.  It'd be great to be able to pre-warm hosts before putting them in, because in the scenario where we use DNS to point to NLB's or other logical collections of hosts when you swap a value in there's not enough "hosts" to maintain a healthy minimum.
