### ISSUE TITLE
envoy crash in ConnectionImpl::dispatch 

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#6656]
We are seeing intermittent crashes on envoy 1.7, unfortunately image that is running is not having debug symbols but we have trace logs and from what it seems like dispatch is called with data of length 0 and it crashes ConnectionImpl::dispatch(Buffer::Instance& data) , since we can see the entry print of the function but not the exit print. I wanted to check if we have any known issues. Below are the trace logs as well as dispatch function 

{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=User-Agent value=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0\n","stream":"stderr","time":"2019-04-18T18:02:39.889559456Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Accept value=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\n","stream":"stderr","time":"2019-04-18T18:02:39.889561871Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Accept-Language value=de,en-US;q=0.7,en;q=0.3\n","stream":"stderr","time":"2019-04-18T18:02:39.889564178Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=upgrade-insecure-requests value=1\n","stream":"stderr","time":"2019-04-18T18:02:39.889566422Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Referer value=https://www.bing.com/\n","stream":"stderr","time":"2019-04-18T18:02:39.889568613Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=dnt value=1\n","stream":"stderr","time":"2019-04-18T18:02:39.889570826Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Cookie value=dp1=bkms/in607b2073^u1f/Christiane5e99ecf3^tzo/-785cb8c783^reg/%5Ebibo%3DBX%2304%2F18%2F2019%232%23S0%23%233%23BX%23S0%2341%5E607b2073^u1p/Y290dG9uZW1tYTE05e99ecf3^bl/DE607b2073^expt/00015556089267165da94f1f^pbf/%238000e000008180020000005e99ecf3^; nonsession=BAQAAAWoZJLj4AAaAAJ0ACF6Z7PMwMDAwMDAwMAFkAARemezzIzAwYQAIAB1c4EZzMTU1NTYwOTc2MHg0MDE0OTMyODQ5MjZ4Nzd4MlkAMwAJXpns8zY0NzExLERFVQDLAAJcuMB7NjAAQAAMXpns82NvdHRvbmVtbWExNAAQAAxemezzY290dG9uZW1tYTE0AMoAIGYeuvMxZjY3OWMzZDE2OTBhYzg4ZGFkZjU3ODlmZmZlN2IyZgAEAAxeU8RxY290dG9uZW1tYTE0AJwAOF6Z7PNuWStzSFoyUHJCbWRqNndWblkrc0VaMlByQTJkajZBSGtZU25ENWVMb3d5ZGo2eDluWStzZVE9PdTSZ1XrIVI8qAGB+yPNehFPSqEC; ns1=BAQAAAWoZJLj4AAaAAKUADV6Z7PMxMzE2Njc3OTIwLzA7ANgAXF6Z7PNjODh8NjAxXjE1NTE0NzAxOTI2NTVeWTI5MGRHOXVaVzF0WVRFMF4xXjN8Mnw1fDR8N3wxMV4xXjJeNF4zXjEyXjEyXjJeMV4xXjBeMV4wXjFeNjQ0MjQ1OTA3NZujdWOhmQNItFRCH2YQFPL61gLn; npii=btguid/1f679c3d1690ac88dadf5789fffe7b2f5e99eb24^cguid/1f68303b1690aada3850a871fab46a085e99eb24^; cid=pCDGgQXAbF9t5cxq%23309104687; ak_bmsc=A417B7851D8FC0360FCCCAC2D043AE8248F7B3C6B46B00001CB4B85C0EC44F70~plO9WdsYsyRY8uAxdHZuHCZ4/UB2uF5pgVT7lmPhfk4b8z7cJqAwmtZnXEY8TMqyT4e++q3E5wCK4p0oQCBqzdq2CzBhzDB07fl7mcHEJqAtHA3x+M+0OEL9Rvh+O+yZHQzoZDii6ig7Cr1MMGZgVqrKPrbwbHSM/m28vv+ipXCxz7Kt3lUVRLIMghHrOMatwrI8LaXplzC5W3R6ozdi3FXMSUQL4LzhwXGbtqzQmxcXA=; bm_sv=E55DAA5F1B10269FF9E85F8826AC180F~oi1wEEnPevW7z9Wck2ZVfuh60exOdvLeleVTwZeviK9nL/OI+Y4Vy7kLJ2nKa+FXt3RA5LFcXoSNf6k1CSR4Mi09bX2y0zl4K37zJ1vN0giN6w1vy6KkNHPHiMAMdT8W5NsmBA9AasBFbJnKBcD0oA==; s=CgAD4ACBcugrzMWY2NzljM2QxNjkwYWM4OGRhZGY1Nzg5ZmZmZTdiMmYA7gCiXLoK8zMGaHR0cHM6Ly93d3cuZWJheS5kZS9zY2gvaS5odG1sP19vZGt3PWJ1eGJhdW0ra3Vuc3RzdG9mZisyNXgyNSZfb3NhY2F0PTAmX2Zyb209UjQwJl90cmtzaWQ9bTU3MC5sMTMxMyZfbmt3PWJ1eGJhdW0ra3Vuc3RwZmxhbnplK3B5cmFtaWRlJl9zYWNhdD0wI2l0ZW01ZDdhZGQ1ODNlBzXve/g*; ebay=%5Esbf%3D%2340800000000100000000000%5Ecv%3D15555%5Ejs%3D1%5E; JSESSIONID=54209FC43FE064D866D2A15A9773E708; cssg=1f679c3d1690ac88dadf5789fffe7b2f\n","stream":"stderr","time":"2019-04-18T18:02:39.889585231Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-eBay-Akamai-9 value=94.16.69.131\n","stream":"stderr","time":"2019-04-18T18:02:39.889597504Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Pragma value=no-cache\n","stream":"stderr","time":"2019-04-18T18:02:39.889599972Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-EdgeConnect-Session-Id value=5cfad2175cb8bbbf15594058\n","stream":"stderr","time":"2019-04-18T18:02:39.8896022Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Client-Continent-Code value=85\n","stream":"stderr","time":"2019-04-18T18:02:39.88960449Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=x-true-client-accept-encoding value=gzip, deflate, br\n","stream":"stderr","time":"2019-04-18T18:02:39.889606729Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Client-loc value=DE\n","stream":"stderr","time":"2019-04-18T18:02:39.889608947Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-Akamai-CONFIG-LOG-DETAIL value=true\n","stream":"stderr","time":"2019-04-18T18:02:39.889611171Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=TE value=chunked;q=1.0\n","stream":"stderr","time":"2019-04-18T18:02:39.889613366Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Connection value=TE\n","stream":"stderr","time":"2019-04-18T18:02:39.889615594Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Accept-Encoding value=gzip\n","stream":"stderr","time":"2019-04-18T18:02:39.889617765Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Akamai-Origin-Hop value=2\n","stream":"stderr","time":"2019-04-18T18:02:39.889627178Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Via value=1.1 v1-akamaitech.net(ghost) (AkamaiGHost), 1.1 akamai.net(ghost) (AkamaiGHost)\n","stream":"stderr","time":"2019-04-18T18:02:39.889629966Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-Forwarded-For value=94.16.69.131, 72.247.179.134\n","stream":"stderr","time":"2019-04-18T18:02:39.889632394Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Host value=www.ebay.de\n","stream":"stderr","time":"2019-04-18T18:02:39.889634625Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Cache-Control value=no-cache, max-age=0\n","stream":"stderr","time":"2019-04-18T18:02:39.889636822Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=Connection value=keep-alive\n","stream":"stderr","time":"2019-04-18T18:02:39.889639043Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-eBay-Client-TLS-Version value=CLIENT.SSL.VERSION+\", \"+CLIENT.IP.SRC\n","stream":"stderr","time":"2019-04-18T18:02:39.88965073Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-EBAY-POP-ID value=UFES1-FRA\n","stream":"stderr","time":"2019-04-18T18:02:39.889653489Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:373] [C116507] headers complete\n","stream":"stderr","time":"2019-04-18T18:02:39.889655744Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:292] [C116507] completed header: key=X-eBay-Client-IP value=95.101.79.30   \n","stream":"stderr","time":"2019-04-18T18:02:39.88965785Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:555] [C116507] message complete\n","stream":"stderr","time":"2019-04-18T18:02:39.889660071Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][http] external/envoy/source/common/http/conn_manager_impl.cc:797] [C116507][S7941023311758530869] request end stream\n","stream":"stderr","time":"2019-04-18T18:02:39.889662185Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][http] external/envoy/source/common/http/conn_manager_impl.cc:463] [C116507][S7941023311758530869] request headers complete (end_stream=true):\n","stream":"stderr","time":"2019-04-18T18:02:39.889665943Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][filter] errorhandler_filter.cc:88] Function Entry: UFESErrorHandlerFilter::decodeHeaders\n","stream":"stderr","time":"2019-04-18T18:02:39.88972932Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/conn_manager_impl.cc:669] [C116507][S7941023311758530869] decode headers called: filter=0x386f450 status=0\n","stream":"stderr","time":"2019-04-18T18:02:39.889731423Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/conn_manager_impl.cc:669] [C116507][S7941023311758530869] decode headers called: filter=0x3643450 status=0\n","stream":"stderr","time":"2019-04-18T18:02:39.889733661Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/conn_manager_impl.cc:669] [C116507][S7941023311758530869] decode headers called: filter=0x31bf450 status=0\n","stream":"stderr","time":"2019-04-18T18:02:39.889735867Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][router] external/envoy/source/common/router/router.cc:256] [C116507][S7941023311758530869] cluster 'cache-pop-1-80' match for URL '/itm/Buchsbaum-kuenstlich-Pyramide-Kunstpflanze-60-cm-Buxus-/160829700689'\n","stream":"stderr","time":"2019-04-18T18:02:39.889738612Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][router] external/envoy/source/common/router/router.cc:323] [C116507][S7941023311758530869] router decoding headers:\n","stream":"stderr","time":"2019-04-18T18:02:39.889741001Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:105] No of ready  connection 6\n","stream":"stderr","time":"2019-04-18T18:02:39.889817604Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:106] No of busy   connection 30\n","stream":"stderr","time":"2019-04-18T18:02:39.889819719Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:107] Total active connection 138\n","stream":"stderr","time":"2019-04-18T18:02:39.88982183Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][pool] external/envoy/source/common/http/http1/conn_pool.cc:111] [C112266] using existing connection\n","stream":"stderr","time":"2019-04-18T18:02:39.889823969Z"}
{"log":"[2019-04-18 18:02:39.889][76][debug][router] external/envoy/source/common/router/router.cc:1007] [C116507][S7941023311758530869] pool ready\n","stream":"stderr","time":"2019-04-18T18:02:39.889826724Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:333] [C112266] writing 3176 bytes, end_stream false\n","stream":"stderr","time":"2019-04-18T18:02:39.889828915Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/conn_manager_impl.cc:669] [C116507][S7941023311758530869] decode headers called: filter=0x3692dc0 status=1\n","stream":"stderr","time":"2019-04-18T18:02:39.889831131Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:333] [C116507] parsed 2966 bytes\n","stream":"stderr","time":"2019-04-18T18:02:39.889833339Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:239] [C116507] readDisable: enabled=true disable=true\n","stream":"stderr","time":"2019-04-18T18:02:39.88983545Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:396] [C112266] socket event: 2\n","stream":"stderr","time":"2019-04-18T18:02:39.88983761Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:464] [C112266] write ready\n","stream":"stderr","time":"2019-04-18T18:02:39.889839757Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:63] [C112266] write returns: 3176\n","stream":"stderr","time":"2019-04-18T18:02:39.889841846Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:396] [C116507] socket event: 2\n","stream":"stderr","time":"2019-04-18T18:02:39.889845761Z"}
{"log":"[2019-04-18 18:02:39.889][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:464] [C116507] write ready\n","stream":"stderr","time":"2019-04-18T18:02:39.88984798Z"}
{"log":"[2019-04-18 18:02:39.892][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:396] [C115784] socket event: 3\n","stream":"stderr","time":"2019-04-18T18:02:39.89252286Z"}
{"log":"[2019-04-18 18:02:39.892][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:464] [C115784] write ready\n","stream":"stderr","time":"2019-04-18T18:02:39.892527744Z"}
{"log":"[2019-04-18 18:02:39.892][76][trace][connection] external/envoy/source/common/network/connection_impl.cc:434] [C115784] read ready\n","stream":"stderr","time":"2019-04-18T18:02:39.892529978Z"}
{"log":"[2019-04-18 18:02:39.892][76][trace][connection] external/envoy/source/common/network/raw_buffer_socket.cc:21] [C115784] read returns: 0\n","stream":"stderr","time":"2019-04-18T18:02:39.892532087Z"}
{"log":"[2019-04-18 18:02:39.892][76][debug][connection] external/envoy/source/common/network/connection_impl.cc:458] [C115784] remote close\n","stream":"stderr","time":"2019-04-18T18:02:39.892534266Z"}
{"log":"[2019-04-18 18:02:39.892][76][debug][connection] external/envoy/source/common/network/connection_impl.cc:140] [C115784] closing socket: 0\n","stream":"stderr","time":"2019-04-18T18:02:39.892566502Z"}
{"log":"[2019-04-18 18:02:39.892][76][trace][http] external/envoy/source/common/http/http1/codec_impl.cc:305] [C115784] parsing 0 bytes\n","stream":"stderr","time":"2019-04-18T18:02:39.892571126Z"}
{"log":"[2019-04-18 18:02:39.897][76][critical][main] external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)\n","stream":"stderr","time":"2019-04-18T18:02:39.897699184Z"}
{"log":"[2019-04-18 18:02:39.897][76][critical][backtrace] bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr\u003c76\u003e obj\u003c/usr/local/bin/envoy\u003e (If unsymbolized, use tools/stack_decode.py):\n","stream":"stderr","time":"2019-04-18T18:02:39.897868709Z"}
{"log":"[2019-04-18 18:02:39.898][76][critical][backtrace] bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr\u003c76\u003e #0 0xbe9c7b (unknown)\n","stream":"stderr","time":"2019-04-18T18:02:39.898293958Z"}
{"log":"[2019-04-18 18:02:39.898][76][critical][backtrace] bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr\u003c76\u003e #1 0xc20195 (unknown)\n","stream":"stderr","time":"2019-04-18T18:02:39.898304096Z"}

// below is the dispath function 

void ConnectionImpl::dispatch(Buffer::Instance& data) {
  ENVOY_CONN_LOG(trace, "parsing {} bytes", connection_, data.length());

  // Always unpause before dispatch.
  http_parser_pause(&parser_, 0);

  ssize_t total_parsed = 0;
  if (data.length() > 0) {
    uint64_t num_slices = data.getRawSlices(nullptr, 0);
    Buffer::RawSlice slices[num_slices];
    data.getRawSlices(slices, num_slices);
    for (Buffer::RawSlice& slice : slices) {
      char faulty_header[]="\r\nApp Name";
      char *ptr = static_cast<char*>(slice.mem_);
      // check if header with name "App Name" exists
      // if it does then replace space with - in it
      // minimum length of the slice should be length of faulty header including \r\n and \0 in the end (8+3)
      for(size_t i= 5;slice.len_ >= sizeof(faulty_header)-1 && i<slice.len_-4;i++){
         if(strncasecmp(ptr+i-5,faulty_header,sizeof(faulty_header)-1) == 0){
             ENVOY_CONN_LOG(debug, "fixing faulty header {}", connection_,std::string(faulty_header));
             ptr[i]='-';
         }
      }
      total_parsed += dispatchSlice(static_cast<const char*>(slice.mem_), slice.len_);
    }
  } else {
    dispatchSlice(nullptr, 0);
  }

  ENVOY_CONN_LOG(trace, "parsed {} bytes", connection_, total_parsed);
  data.drain(total_parsed);
}

**Comment by htuch** [comment]
@pitiwari does the problem existing 1.10? It's kind of hard to say what might be going on with an Envoy this old.
