### ISSUE TITLE
Support of Linker option `-fuse-ld=gold` for enabling Clang CFI schemes

### ISSUE THREAD

**Issue by qiang-nutanix** [envoyproxy/envoy#6685]
**Issue Template**

*Title*: *Support of Linker option `-fuse-ld=gold` for CFI*

*Description*:

Quoted from http://clang.llvm.org/docs/ControlFlowIntegrity.html:  "Clang includes an implementation of a number of control flow integrity (CFI) schemes, which are designed to abort the program upon detecting certain forms of undefined behavior that can potentially allow attackers to subvert the program’s control flow."

To enable Clang’s available CFI schemes, the build need to use the flag -fsanitize=cfi, which requires link-time optimization (LTO) -flto, and the linker used must support LTO, for example via the gold plugin.

**Comment by SunilAgrawal** [comment]
+1 

This, and the SafeStack option in CLang (https://clang.llvm.org/docs/SafeStack.html), will definitely improve the overall security of Envoy.

**Comment by lizan** [comment]
By default (if `--linkopt=lld` isn't supplied to bazel) gold is the default linker.

You can add compiler flag and linker flag via `--copt=` and `--linkopt=`, did that work? If so a PR to .bazelrc for a CFI config is welcomed.

**Comment by qiang-nutanix** [comment]
@lizan, So, I made change pasted at the bottom. But running docker build with bazel.dev failed with below error, I wasn't able to find config.log from the mounted /build folder. Can you tell me where I can find the config.log or the build logs? also, can you see any issue with my change?

...
checking whether the C compiler works... no
configure: error: in `/tmp/tmp.5knV6iKtkT':
configure: error: C compiler cannot create executables
See `config.log' for more details
...

diff --git a/.bazelrc b/.bazelrc
index 97b52a4..ec5354a 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -63,3 +63,10 @@ build:libc++ --define force_libcpp=enabled
 
 # Test options
 test --test_env=HEAPCHECK=normal --test_env=PPROF_PATH
+
+# Clang CFI
+build:clang-cfisan --linkopt -flto
+build:clang-cfisan --linkopt -fsanitize=cfi
+
+# Clang safe-stack
+build:clang-sssan --linkopt -fsanitize=safe-stack
diff --git a/ci/build_setup.sh b/ci/build_setup.sh
index 9941d1b..48eede9 100755
--- a/ci/build_setup.sh
+++ b/ci/build_setup.sh
@@ -64,7 +64,7 @@ if [[ -f "/etc/redhat-release" ]]
 then
   export BAZEL_BUILD_EXTRA_OPTIONS="--copt=-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1 --action_env=PATH ${BAZEL_BUILD_EXTRA_OPTIONS}"
 else
-  export BAZEL_BUILD_EXTRA_OPTIONS="--action_env=PATH=/bin:/usr/bin:/usr/lib/llvm-8/bin --linkopt=-fuse-ld=lld ${BAZEL_BUILD_EXTRA_OPTIONS}"
+  export BAZEL_BUILD_EXTRA_OPTIONS="--action_env=PATH=/bin:/usr/bin:/usr/lib/llvm-8/bin ${BAZEL_BUILD_EXTRA_OPTIONS}"
 fi
 
 # Not sandboxing, since non-privileged Docker can't do nested namespaces.
diff --git a/ci/do_ci.sh b/ci/do_ci.sh
index fa4f1db..6aa975b 100755
--- a/ci/do_ci.sh
+++ b/ci/do_ci.sh
@@ -155,7 +155,7 @@ elif [[ "$1" == "bazel.dev" ]]; then
   # This doesn't go into CI but is available for developer convenience.
   echo "bazel fastbuild build with tests..."
   echo "Building..."
-  bazel build ${BAZEL_BUILD_OPTIONS} -c fastbuild //source/exe:envoy-static
+  bazel build ${BAZEL_BUILD_OPTIONS} -c fastbuild --config=clang-cfisan //source/exe:envoy-static
   # Copy the envoy-static binary somewhere that we can access outside of the

**Comment by qiang-nutanix** [comment]
@lizan:

At .bazelrc, I added below 2 lines at the end:
build:clang-cfisan --linkopt -flto
build:clang-cfisan --linkopt -fsanitize=cfi

At ci/build_setup.sh,
I removed --linkopt=-fuse-ld=lld from BAZEL_BUILD_EXTRA_OPTIONS, and replaced
bazel build ${BAZEL_BUILD_OPTIONS} -c fastbuild //source/exe:envoy-static
with
bazel build ${BAZEL_BUILD_OPTIONS} -c fastbuild --config=clang-cfisan //source/exe:envoy-static

But, the bazel.dev docker build failed with errors:

`
checking for gcc... /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/external/local_config_cc/extra_tools/envoy_cc_wrapper
checking whether the C compiler works... no
configure: error: in `/tmp/tmp.5knV6iKtkT':
configure: error: C compiler cannot create executables
See `config.log' for more details
`

Any issues with change? Where do I get more info from the build failure? I couldn't find the config.log from mounted /build folder.

**Comment by lizan** [comment]
@qiang-nutanix I think you need both linkopt and copt.

I was able to build with extra options: `--copt=-fsanitize=cfi --linkopt=-fsanitize=cfi --copt=-flto --linkopt=-flto --copt=-fvisibility=hidden --copt=-Qunused-arguments --linkopt=-Qunused-arguments`, (without lld)

**Comment by qiang-nutanix** [comment]
@qiang-nutanix, I got errors when I use the extra options you used, am I missing something?

[38/41] Linking C executable minigzip64
[39/41] Linking C executable example64
[40/41] Linking C executable minigzip
[41/41] Linking C executable example
FAILED: : && /build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/external/local_config_cc/extra_tools/envoy_cc_wrapper  -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fco
lor-diagnostics -fno-omit-frame-pointer -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -flto -fsanitize=cfi -fvisibility=hidd
en -Qunused-arguments  -O2 -g -DNDEBUG  -fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -lstdc++ -lm -flto -fsanitize=cfi -Qunused-arguments CMakeFiles/example64.dir/test/example.o  -o example64  -
rdynamic libz.so.1.2.11 -Wl,-rpath,/tmp/tmp.a58tWBm7Os && :
/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/com_github_madler_zlib/test/example.c:6389: error: undefined reference to 'zlibVersion'
/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/com_github_madler_zlib/test/example.c:28682: error: undefined reference to 'zlibVersion'
/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy/external/com_github_madler_zlib/test/example.c:28682: error: undefined reference to 'zlibCompileFlags'
/tmp/lto-llvm-82f347.o:ld-temp.o:function main: error: undefined reference to 'compress'
/tmp/lto-llvm-82f347.o:ld-temp.o:function main: error: undefined reference to 'uncompress'
