### ISSUE TITLE
ares_library_cleanup() won't be called if an exception occurs in MainCommonBase constructor.

### ISSUE THREAD

**Issue by curiouserrandy** [envoyproxy/envoy#6689]
*Title*: ares_library_cleanup() won't be called if an exception occurs in MainCommonBase constructor.

*Description*:
The MainCommonBase constructor sets up some global state; specifically, it calls ares_library_init() as its first line.  That global state is reset in ~MainCommonBase via ares_library_cleanup().   If an exception is thrown from a function called from the MainCommonBase constructor (as happens if there is an envoy configuration error), the init function will be called by the cleanup function won't be.  That may be problematic for tests that use MainCommonBase which may be testing invalid envoy configs--there will be global state droppings in place after a construction attempt that throws.

(I don't know the ares library so I don't now how important this is--I ran into this tracing a similar problem with the thread singleton factory, but I expect that problem to be fixed by pull request #6658 .]

https://github.com/envoyproxy/envoy/blob/master/source/exe/main_common.cc#L53
https://github.com/envoyproxy/envoy/blob/master/source/exe/main_common.cc#L101

@jmarantz

**Comment by jmarantz** [comment]
Are you sure this is a problem? I'm not an C++ exception expert but a little searching found this:

https://www.geeksforgeeks.org/exception-handling-and-object-destruction-in-c-set-1/

**Comment by curiouserrandy** [comment]
Pretty sure, yes.  That example throws an exception after construction, and my concern is with exceptions thrown *from the constructor*.  

Think of it this way: If an exception is thrown from the constructor, if you call the destructor it won't know how much of the object has been constructed or not.  Putting it a slightly different way, either the constructor itself has to cleanup on the way out (via its own try block), or the constructor and destructor need to coordinate so that cleanup can happen in the destructor, and the former keeps related code more closely together.  

And on the experimental side, I was lead to filing this bug by logging in ThreadFactorySingleton::set() that showed that it was being called from the constructor and not from the destructor, which means the destructor wasn't being called.

Whether or not we care in this particular cae (i.e. what problems are caused by ares_library_init() staying active) I couldn't say.

**Comment by curiouserrandy** [comment]
Also, the example you give, if you scroll down, shows exactly the behavior I describe: when a throw occurs from in the constructor, the destructor isn't called.  

(Sorry I didn't read through the entire example before replying.)

**Comment by mattklein123** [comment]
Yeah this is a bug. The fix is simple, just put cares c-ares construct/destruct in its own holder object, and hold that in the larger main class. C++ will always destruct something that is fully destructed, even if a parent constructor throws.

**Comment by jmarantz** [comment]
Maybe CSmartPtr would do the job: https://github.com/envoyproxy/envoy/blob/master/source/common/common/c_smart_ptr.h

**Comment by alyssawilk** [comment]
@htuch unsure if you can fix two bugs with one PR, but figured I'd tag this as another ares issue

**Comment by htuch** [comment]
@alyssawilk great idea, I can do this.
