### ISSUE TITLE
Log cookie value in access log

### ISSUE THREAD

**Issue by fttyX** [envoyproxy/envoy#6695]
Hi.
Quick question: now to log cookie value in envoy access log?

For example, I have cookie SESSIONID, passing it with curl as --cookie "SESSIONID=1234-abcd-1234-abcd" and having %REQ(SESSIONID)% in access log format, but getting "-" in log. Is %REQ(SESSIONID)% just for headers? How to get request/response cookie value there?

(In nginx it is $cookie_SESSIONID/$upstream_cookie_SESSIONID log format variables).

Thanks in advance.

**Comment by junr03** [comment]
%REQ(X?Y):Z% and its response counterpart %RESP(X?Y):Z% work on http headers (docs on them [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#command-operators)). This means that if you are modifying the Cookie header with curl the header you want to print is Cookie.

**Comment by fttyX** [comment]
@junr03 Thank you, however this prints out all cookie headers (list of keys and values). Is there any way to print out just one specific cookie value?

**Comment by fttyX** [comment]
Also, I found out, that if you have several cookies set, one by one, then REQ/RESP returns just the first cookie.

For example, my upstream sets two cookies, SESSIONID and PAGEID. If I add to log format %RESP(SET-COOKIE)% I get just SESSIONID cookie information. But if, for some reason, SESSIONID cookie is not set, then I get the next, PAGEID cookie info in log, which is wrong.

Is it really supposed to work that way? Currently, looks like you cannot rely on cookies data at all.

Maybe there's some other way to get cookies values? (with metadata, or anything)

**Comment by dio** [comment]
> if you have several cookies set

@fttyX could you give me an instance of it? I can try to validate it. Thanks!

**Comment by fttyX** [comment]
> > if you have several cookies set
> 
> @fttyX could you give me an instance of it? I can try to validate it. Thanks!

For example, if I do curl request to website foo.example.com, I get response cookies like that:

```
set-cookie: SESSIONID=4b140519-3f72-53af-c0cd-63cf125a5cf4; Max-Age=315360; Domain=.example.com; Path=/; Expires=Sat, 18 May 2019 03:17:00 GMT
set-cookie: PAGEID=5ydu1PjDgZo; Max-Age=3600; Domain=foo.example.com; Path=/; Expires=Tue, 14 May 2019 12:41:00 GMT
```

What I want here, is to put 4b140519-3f72-53af-c0cd-63cf125a5cf4 to envoy log.

**Comment by helloord** [comment]
> > > 如果您设置了多个 cookie
> > 
> > 
> > @fttyX 你能给我一个例子吗？我可以尝试验证它。谢谢！
> 
> 例如，如果我向网站 foo.example.com 发出 curl 请求，我会得到如下响应 cookie：
> 
> ```
> set-cookie: SESSIONID=4b140519-3f72-53af-c0cd-63cf125a5cf4; Max-Age=315360; Domain=.example.com; Path=/; Expires=Sat, 18 May 2019 03:17:00 GMT
> set-cookie: PAGEID=5ydu1PjDgZo; Max-Age=3600; Domain=foo.example.com; Path=/; Expires=Tue, 14 May 2019 12:41:00 GMT
> ```
> 
> 我在这里想要的是将 4b140519-3f72-53af-c0cd-63cf125a5cf4 放入特使日志。

Is there a solution?

**Comment by helloord** [comment]
> @junr03谢谢，但是这会打印出所有 cookie 标头（键和值列表）。有没有办法只打印出一个特定的 cookie 值？
@junr03 Is there a solution?

**Comment by helloord** [comment]
> > > if you have several cookies set
> > 
> > 
> > @fttyX could you give me an instance of it? I can try to validate it. Thanks!
> 
> For example, if I do curl request to website foo.example.com, I get response cookies like that:
> 
> ```
> set-cookie: SESSIONID=4b140519-3f72-53af-c0cd-63cf125a5cf4; Max-Age=315360; Domain=.example.com; Path=/; Expires=Sat, 18 May 2019 03:17:00 GMT
> set-cookie: PAGEID=5ydu1PjDgZo; Max-Age=3600; Domain=foo.example.com; Path=/; Expires=Tue, 14 May 2019 12:41:00 GMT
> ```
> 
> What I want here, is to put 4b140519-3f72-53af-c0cd-63cf125a5cf4 to envoy log.

Is there a solution?

**Comment by helloord** [comment]
> @junr03 Thank you, however this prints out all cookie headers (list of keys and values). Is there any way to print out just one specific cookie value?

@junr03 Is there a solution?
