### ISSUE TITLE
HTTP2 flow control

### ISSUE THREAD

**Issue by MSex** [envoyproxy/envoy#6727]
My use case is using envoy as a sidecar for a gRPC server streaming fast produced data to a slow client. The default behavior for envoy in this case was to buffer a huge amount of data and so it allocates a lot of memory. To configure flow control so to limit the memory usage it was necessary to set _http2_protocol_options.initial_stream_window_size_ in both the _cluster_ and the _http_connection_manager_ filter.

I have two issues/questions: 

1- Why it was necessary to set the value in both places since in this case the stream is only one direction?
2- Since using envoy in a sidecar for microservices is a very common use case, the default value for _initial_stream_window_size_ should be smaller (now it is 256MiB). My sugestion it should be equal the minimum possible value: 65535 bytes.

In any case, thanks for your help.

**Comment by mattklein123** [comment]
@MSex unfortunately there is a lot of historical baggage around the flow control defaults. @alyssawilk and I would both like to change some of them, but it's a hard thing to do at this point without a lot of thought. For now if you feel like it, please feel free to add more verbiage and warnings to https://www.envoyproxy.io/docs/envoy/latest/faq/configure_flow_control. Much appreciated.
