### ISSUE TITLE
//test/integration/... requires compiling all extensions

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6736]
I have noticed that when testing `//test/integration/...` it compiles all extensions. I think this is probably because there is some server test in there that also compiles all extensions, but I'm not sure.

Optimally, we should be able to run these tests without having to compile any extra extensions beyond potentially core ones like router, HCM, etc. This is useful on platforms that won't support all extensions.

cc @junr03

**Comment by yanavlasov** [comment]
The only test that needs to compile all extensions is `//test/integration:run_envoy_test`. This test seems to test that envoy process fails with bogus command line parameters. This should work with envoy without any extensions at all, I think. Unless I'm missing something the solution is to create another target that builds the server without any extensions.

```
$ bazel query "rdeps(//test/integration/..., //source/exe:envoy-static)"
//test/integration:run_envoy_test
//source/exe:envoy-static
Loading: 0 packages loaded
$
```

**Comment by mattklein123** [comment]
@yanavlasov I think there are a couple of others like the hot restart test that use the full binary. But yeah, the solution is to build the binary twice, one the real version and one the light version. Note that @jmarantz already has a custom binary going for the hot restart test.
