### ISSUE TITLE
Rename the existing header 

### ISSUE THREAD

**Issue by mohammadMahdavi** [envoyproxy/envoy#6739]
**Issue Template**

*Title*: *Rename the existing heather*

*Description*:
>I want to rename the exiting header in envoy configuration but I cant find any related document expect [Access header values by name from header modification options] (https://github.com/envoyproxy/envoy/issues/5051) where has no response. Is there any solution for this requirement in envoy?

**Comment by derekargueta** [comment]
@mohammadMahdavi can you clarify what you mean by "rename existing header"? Are you talking about a scenario where you have a request with header `A: foobar` and want to rename it to `B: foobar`? If so, I don't think there's a configuration option for this, you can accomplish it with a simple filter or Lua snippet.

**Comment by ngrigoriev** [comment]
Personally I think that it should be achieved by adding a header with the value of another header and removing the specific header(s).
I have a case for it too. My API Gateway (based on Ambassador) will receive the Authorization header and process it. I do not want my backend APIs to be aware of the actual bearer token, I will provide them the required values in separate headers. Yet, for some cases (like calling OAuth2 /userinfo endpoint) they may need the original bearer token. To make it clean, I would like to create another header "x-userinfo-token" or something like it, populate it with the value of the original Authorization header and then drop the original Authorization header.
