### ISSUE TITLE
stats: don't leak obsolete stats across hot restart

### ISSUE THREAD

**Issue by fredlas** [envoyproxy/envoy#6756]
Stats previously "migrated" across hot restart by simply living in shared memory. With PR #5910, they will instead be passed in messages from hot restart parent to child. In the current implementation, the merging of a parent's counter value into the child is indistinguishable (from the stats system's point of view) from the actual child Envoy legitimately add()ing to that stat. The result is that an obsolete counter name, which would previously have been dropped due to the child simply never attaching to that piece of shared memory, will stick around forever in the child.

Suggestions so far:
from @mattklein123:
> The simplest solution would be to just not add to counters that don't exist yet in the new process. However, if we do this, and we are sending deltas, we may actually lose data. The other option would be to somehow store deltas for unknown counters through the hot restart drain period, and then if they are still not attached by the time the parent shuts down, we just abandon the counter deltas.

from me:
> Maybe a clean way would be to let everything be the way it currently is in this PR, but add a flag bit "used by this process" that would be set by any interaction (other than merging) with the stat. Then, at the end of the hot restart, get rid of all stats without that flag set.
> [...there could be a performance issue...]
> I wonder if it's possible to repurpose the existing Used flag, which is already getting set by all stat modifications, and which currently (going by my not-too-deep look just now) doesn't actually appear to be doing all that much.

**Comment by mattklein123** [comment]
@fredlas I'm marking this a bug and going to assume you are going to work on it as a near-term follow up, right?

**Comment by fredlas** [comment]
Correct, I will start on it now, now that #5910 looks unlikely to significantly change further.

**Comment by fredlas** [comment]
One important piece of info: do we consider the child accessing a stat's .value() to be enough to want to keep it, or should the child need to modify the value?

**Comment by mattklein123** [comment]
> One important piece of info: do we consider the child accessing a stat's .value() to be enough to want to keep it, or should the child need to modify the value?

Optimally the thing we key off of is creation, not access or modification. This would be similar to the previous behavior, and I think optimal from a performance perspective. 

Keep in mind that if you add and then delete, you probably need to setup some type of temporary scope, because stats cannot be deleted from the root scope IIRC. This is why I still think it might be better to not add at all if the child has not yet created a stat.

**Comment by mattklein123** [comment]
@fredlas I thought of what I think is a pretty slick solution to this problem, let me know what you think:
1) Create a new scope off of the root when you hot restart.
2) Put all parent stats in this scope.
3) Delete the scope at the end of hot restart.

I'm pretty sure that due to reference counting, if another scope references the same stat it won't go away, otherwise it will. WDYT? cc @jmarantz

**Comment by jmarantz** [comment]
SGTM. I suppose the scope doesn't need to include a prefix.

**Comment by fredlas** [comment]
That does sound very clean. I still don't understand exactly what scopes and stores are, and how they relate and differ, especially given some of the spooky behavior shown in thread_local_store_test.cc. So, I'm not sure I would be able to implement that approach in a reasonable amount of time. I implemented the "hold the deltas" approach yesterday evening and this morning; maybe that can be a stopgap until someone can do this one? (There will not be any incompatibility issues).

**Comment by mattklein123** [comment]
@fredlas can you potentially sync up with @jmarantz in person? I think the scope method I outline would be very easy to implement and also easy to test.

**Comment by jmarantz** [comment]
We just chatted f2f -- I think we should be good with your approach now.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/6850
