### ISSUE TITLE
Configure Envoy from the Envoy filter

### ISSUE THREAD

**Issue by ashwini-vasanth** [envoyproxy/envoy#6758]
**Issue Template**

*Title*: *Configure Envoy (Clusters/endpoints and certificates) from the Envoy filter *

*Description*:
> We have implemented a custom filter for Envoy to do some specific processing with regard to routing. In our use case, the Envoy filter contains all the information necessary to configure the Envoy clusters and certificates. The filter fetches the data from a Server which does not support xDS.  Could you please let me know if there is a way to  dynamically configure Envoy from the Envoy filter?

**Comment by mattklein123** [comment]
I would look into adding a cluster cluster extension which is now possible. See https://github.com/envoyproxy/envoy/pull/6446

**Comment by ashwini-vasanth** [comment]
Thank you so much for the quick reply @mattklein123  This sounds like a great approach for us to apply configuration at a cluster level. I will investigate this further. The current model were are following is to leave core envoy untouched and develop filters based on envoy_filter_example. If we wanted to configure Envoy from the filter, would that mean the filter would have to speak the xDS protocol? We also need to configure certificates for TLS termination (Downstream TLS context). We have a requirement to program these certificates dynamically as downstream clients get added and this will not be cluster specific. So I was wondering if there exists a mechanism that would allow adding this configuration too.
