### ISSUE TITLE
Envoy accepts any upstream certificate as long as the CA is trusted

### ISSUE THREAD

**Issue by jmjolysc** [envoyproxy/envoy#6763]
**Envoy accepts any upstream certificate as long as the CA is trusted**

*Description*:
Envoy **v1.10.0** has no way to validate the subject's CN on a certificate. In fact, Envoy accepts any upstream, non-expired certificate as long as it has been signed by a whitelisted `trusted_ca`.

Even though it is possible to verify the alternative names on an upstream certificate (`verify_subject_alt_name`), Envoy seems to have no configuration option to check whether the main name (CN) on a certificate is valid. Is that behavior expected?

Here is a configuration example:
```
tls_context:
  common_tls_context:
    validation_context:
      trusted_ca:
        filename: /etc/pki/tls/certs/my_trusted_ca.crt
  sni: wrong-cert.example.com
```

Besides, when specifying alternative names within the validation context, Envoy fails to connect to the upstream server if the name doesn't appear on the alternative name list, although it is the subject's CN on the certificate.

This is what `curl` would respond (sanitized) to an invalid certificate signed by a trusted CA:
```
curl https://wrong-cert.example.com -vvv --cacert /etc/pki/tls/certs/my_trusted_ca.crt
*   Trying 10.10.123.123...
* TCP_NODELAY set
* Connected to wrong-cert.example.com (10.10.123.123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/my_trusted_ca.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=MI; L=whatever; O=someOrg; OU=Engineering; CN=some-wrong-cert.example.com
*  start date: Nov 12 05:51:46 2018 GMT
*  expire date: Nov  9 05:51:46 2022 GMT
*  subjectAltName does not match wrong-cert.example.com
* SSL: no alternative certificate subject name matches target host name 'wrong-cert.example.com'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (51) SSL: no alternative certificate subject name matches target host name 'wrong-cert.example.com'
```

Is that behavior consistent on your side? Did I overlook any additional options? Thanks.

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/ssl
https://www.envoyproxy.io/docs/envoy/v1.10.0/api-v2/api/v2/auth/cert.proto#envoy-api-msg-auth-certificatevalidationcontext

**Comment by mattklein123** [comment]
@lizan @PiotrSikora

**Comment by lizan** [comment]
> Even though it is possible to verify the alternative names on an upstream certificate (verify_subject_alt_name), Envoy seems to have no configuration option to check whether the main name (CN) on a certificate is valid. Is that behavior expected?

Yes it is. The configuration example you provided does no validation other than trusted CA, so it won't validating other field.

> Besides, when specifying alternative names within the validation context, Envoy fails to connect to the upstream server if the name doesn't appear on the alternative name list, although it is the subject's CN on the certificate.

This is also expected, the use of X.509 Common Name is deprecated in RFC 2818 (published in 2000!), and many of clients already dropped support of validating DNS name against CN years ago (e.g. Chrome >= [58](https://www.chromestatus.com/feature/4981025180483584) and Firefox >= 48)

**Comment by jmjolysc** [comment]
Thank you @lizan, I really appreciate the detailed explanation. I'll start validating the upstream certificates with `verify_subject_alt_name`.

**Comment by sachinshaji** [comment]
@lizan @jmjolysc
May I ask question here. I am trying to use a self-signed certificate, I need to make envoy trust the self signed certificate(I use security policy which fails due to the certificate validation error). Is it possible to make envoy trust the self signed certificate I use. Could you guide me through some documentation if you have it handy.
