### ISSUE TITLE
How to build envoy binary on Mac and then run in kubernetes cluster as part of the istio proxy image

### ISSUE THREAD

**Issue by honghzzhang** [envoyproxy/envoy#6769]
Please see my post in istio forum for more background:
https://discuss.istio.io/t/how-to-build-istio-proxy-image-on-mac/2104

Basically, I have built envoy binary on Mac, and then built istio proxy image on top of the envoy binary (with GOOS=linux), but the proxy image was not usable when I installed istio on linux based kubernetes cluster (exec format error). 

This could be a common use case for people who develop on Mac, but want to run on (linux based) Kubernetes cluster.  How do we build envoy binary on Mac which can be used in Kubernetes cluster environment? Thank you for any pointers!

**Comment by moderation** [comment]
The binary built on a Mac using Bazel is built for that platform and won't run in Linux. In theory you could build Linux binaries on a Mac using the Docker method outlined at https://github.com/envoyproxy/envoy/tree/master/ci#building-and-running-tests-as-a-developer
