### ISSUE TITLE
http: connection: close header is not sent when HCM is in draining state

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6802]
This probably regressed at some point years ago, and has been this way for a while, but we just realized that when the HCM is in the draining state (not closing) for HTTP/1, we don't set the "Connection: close" header on outgoing responses. To match the behavior of the double GOAWAY from HTTP/2, we should be setting this header and giving clients the time to not reuse the connection or pipeline.

```
mklein@localhost:~/Source/envoy$ git diff
diff --git a/source/common/http/conn_manager_impl.cc b/source/common/http/conn_manager_impl.cc
index 8c804ba1b..ee6d42761 100644
--- a/source/common/http/conn_manager_impl.cc
+++ b/source/common/http/conn_manager_impl.cc
@@ -1286,7 +1286,7 @@ void ConnectionManagerImpl::ActiveStream::encodeHeaders(ActiveStreamEncoderFilte
     connection_manager_.stats_.named_.downstream_rq_response_before_rq_complete_.inc();
   }
 
-  if (connection_manager_.drain_state_ == DrainState::Closing &&
+  if (connection_manager_.drain_state_ != DrainState::NotDraining &&
       connection_manager_.codec_->protocol() != Protocol::Http2) {
     // If the connection manager is draining send "Connection: Close" on HTTP/1.1 connections.
     // Do not do this for H2 (which drains via GOAWAY) or Upgrade (as the upgrade
```

cc @alyssawilk for any comment.

**Comment by mattklein123** [comment]
@alyssawilk FYI someone at Lyft is going to fix this as a learning bug. @lita can you tag them?

**Comment by alyssawilk** [comment]
Oh, even better!
I think my only comment is pointing to my TODO by decodeHeaders about the connection: close code being pretty fragile.  So if your learning Lyfter has any interest in a follow-up bug they could look at that too ;-)

**Comment by lita** [comment]
yup! @jyotimahapatra

**Comment by jyotimahapatra** [comment]
Hi @alyssawilk , Nice to meet you here. I am new here and trying to fix this starter issue.
I am trying to write a test that repros the situation and then perform the mentioned fix. Matt mentioned in a different forum that this situation occurs in a race condition situation when using pipelining in a H1 connection.
All code paths today set the `drain_state_` to `DrainState::Closing` and I am trying to figure out a code path that will cause it to stay in `Draining` state at the intended code line.

**Comment by mattklein123** [comment]
Looks like fixed in https://github.com/envoyproxy/envoy/pull/6848

**Comment by jyotimahapatra** [comment]
Looking at the test, looks like keep-alive is what I was looking for to repro the situation. Good learning for me.

**Comment by mattklein123** [comment]
@jyotimahapatra this is the line that repros: https://github.com/envoyproxy/envoy/pull/6848/files#diff-ed63d9053f7d0b3777c96f2aaf8f2f2fR4178

**Comment by jyotimahapatra** [comment]
Yes. I got that part right.
I couldn't get this part right. Without the keepalive the drainstate was getting set to Closing already.
`HeaderMapPtr headers{new TestHeaderMapImpl{
        {":authority", "host"}, {":path", "/"}, {":method", "GET"}, {"connection", "keep-alive"}}};`

**Comment by mattklein123** [comment]
I haven't checked, but I don't think that should be required. Keep alive is assumed for HTTP/1.1. cc @kmyerson

**Comment by jyotimahapatra** [comment]
I see. Ok. i will get the branch and debug through it. It will be a good exercise for me

**Comment by jyotimahapatra** [comment]
@alyssawilk you mentioned a follow up bug. I could attempt that if you can put some problem statement for me. :)
