### ISSUE TITLE
What is the difference between Locality and Priority?

### ISSUE THREAD

**Issue by rnd4222** [envoyproxy/envoy#6809]
What is the difference between [Locality](https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/load_balancing/locality_weight) and [Priority](https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/load_balancing/priority)?
When should I use one or another (or both)?
Thanks.

**Comment by alyssawilk** [comment]
Locality is more about location.  Perhaps you want to send more traffic to locations closer to your Envoy instance.  Priority is more about failover.  "Ideally I'd like to send my traffic to A/B in my top priority but if they're overloaded/unhealthy spill over to C/D"

**Comment by rnd4222** [comment]
@alyssawilk thanks for your reply. So locality is more like automatic, location-based priority?
