### ISSUE TITLE
How to use the RDS service to update routing configuration in envoy's thrift proxy filter

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/envoy#6811]
I am using envoy thrift filter to proxy thrift rpc request, but when reviewd the envoy code , I do'nt known how to use RDS to update thrift route configuration, can you give me an example about it ?

**Comment by alyssawilk** [comment]
RDS is used for updates to HTTP route configuration* so I don't think that's what you want.
I as thrift is a network filter you can update thrift routes with a full LDS update but I'm not sure if there's any finer grained update
@brian-pane @zuercher 

*https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto#envoy-api-msg-routeconfiguration
