### ISSUE TITLE
Log and count unknown proto fields

### ISSUE THREAD

**Issue by mergeconflict** [envoyproxy/envoy#6818]
Deprecated proto fields are currently logged as a warning or an error in `MessageUtil::checkForDeprecation`, and counted in `SnapshotImpl::deprecatedFeatureEnabled`. We should probably do the same thing for unknown proto fields in `MessageUtil::checkUnknownFields` when not in strict mode.

**Comment by htuch** [comment]
See also https://github.com/protocolbuffers/protobuf/issues/5967, where we track the necessary work on protobuf side to support this for JSON/YAML. We can only do this for proto configuration files today, which is only a partial solution.

**Comment by ramaraochavali** [comment]
Would it be useful to add these counts as stats? NBD, but generally it would be difficult search through logs for a fleet of envoys

**Comment by htuch** [comment]
I think both stats and warning-level logs would be good. I agree that we need stats for monitoring to alert on.

**Comment by htuch** [comment]
I think I can address this in the context of #6651
