### ISSUE TITLE
tsan caught ares cleanup shutdown bug

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#6839]
https://pastebin.com/FKsvL1sM

from

https://circleci.com/gh/envoyproxy/envoy/211476?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

tl;dr looks like both google's grpc code and DnsResolverImpl want to do ares cleanup.

Not super high pri as it's a shutdown bug but worth fixing if for no other reason to keep CI happy

**Comment by htuch** [comment]
This is because we are independently initializing and shutting down c-ares in `DnsResolverImpl`, which can race with gRPC. I'll do a PR to fix today. AFAICT, this is fairly rare race, I'm seeing it 1/1000 frequency locally.
