### ISSUE TITLE
bazel: expand linkstamp beyond binary rules.

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy#6859]
bazel: expand linkstamp beyond binary rules.

Description: `linkstamp` is currently used by the `VersionInfo` class to stamp envoy binaries. This is a robust mechanism. However, there are two current problems with it:
1. It is poorly documented and understood. https://github.com/bazelbuild/bazel/issues/2893
2. `linkstamp` is not available for non-binary rules. Thus if the `version_info_lib` is compiled outside of a top-level binary rule the linker will not be able to find symbols defined by the linkstamp rule. For now this is resolved by https://github.com/envoyproxy/envoy/pull/6803. However, it would be great to use the same, robust `linkstamp` mechanism we use for binary rules.

**Comment by junr03** [comment]
cc @htuch lmk if this is sufficient for the bazel folks, or if you'd like me to open an issue against bazel.

**Comment by htuch** [comment]
@junr03 it's sufficient for me to share, thanks. I think if we want action on the Bazel front though, it would be good to have a tracking issue in their GH.
