### ISSUE TITLE
IpVersions/LoadStatsIntegrationTest.LocalityWeighted/IPv4 timing out coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#6874]
AFIK reverting 6761 got us from pretty deterministic failure to generally passing but I've seen 2 failures since

https://circleci.com/gh/envoyproxy/envoy/213854?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
https://circleci.com/gh/envoyproxy/envoy/213482?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by mattklein123** [comment]
I think this should be fixed via https://github.com/envoyproxy/envoy/pull/6784

**Comment by alyssawilk** [comment]
Sadly looks like it wasn't (though please to sanity check my times)

Via #6784
lizan merged commit 27b3e48 into envoyproxy:master 3 days ago

Sat, May 11, 8:07 PM (2 days ago)
https://circleci.com/gh/envoyproxy/envoy/215476?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
[ RUN ] IpVersions/LoadStatsIntegrationTest.LocalityWeighted/IPv4

The suggestion was it was picking up stale stats previously but that doesn't sound right to me - the test in question is doing an infinite wait on getting stats, and then checking equivalence.  It isn't doing a wait-until-stats-are-the-expected value.  If it weren't a coverage run I'd wonder if some request went astray and screwed up the wait clauses but that's less likely to impossible to happen on the coverage runs because everything runs serially. Meanwhile it may have looked deflaked in #6784 because it's hard to repro locally.

**Comment by alyssawilk** [comment]
Yay, @mattklein123 caught one of these.  Logging says:

[ RUN      ] IpVersions/LoadStatsIntegrationTest.LocalityWeighted/IPv4
Waiting for load stats stream.
Waiting for load stats request.
Done waiting.
Starting response.
Updating assignments.
Sending traffic.
Waiting for load stats request 2.
