### ISSUE TITLE
Filter API to override origin/backend mapping

### ISSUE THREAD

**Issue by canselcik** [envoyproxy/envoy#6883]
Hi,

I am looking for a way for a filter to intercept a request and alter its mapping to a backend host from one to the other.

Could someone point me to a similar example or to the right filter API? 

Thanks.

**Comment by mattklein123** [comment]
@canselcik I think we will need more details about your use case to provide guidance.

**Comment by canselcik** [comment]
@mattklein123 Thank you for your reply. Let me elaborate on my use-case.

I am basically trying to create a "host override" plugin that allows certain user-agents to override (for debugging purposes) the the mapped origin for the current transaction.

Let's say I have a cluster with servers A, B and C. A request comes in and is mapped to A. I would like to have the ability to look at a header and override that mapping to B or C.

Similar to the [TSHttpTxnServerAddrSet](https://docs.trafficserver.apache.org/en/8.0.x/developer-guide/api/functions/TSHttpTxnServerAddrSet.en.html?highlight=tshttptxnserver#c.TSHttpTxnServerAddrSet) API provided by Apache Traffic Server.

**Comment by mattklein123** [comment]
Take a look at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/original_dst.html#original-destination-host-request-header. I think that is roughly what you need?

**Comment by canselcik** [comment]
@mattklein123 Thank you, that definitely looks like it is almost exactly what I am looking for.

One question I would have about the original destination cluster type would be if doing this would require setting up a second cluster with the exact same set of hosts that I might want to override to?

**Comment by mattklein123** [comment]
> One question I would have about the original destination cluster type would be if doing this would require setting up a second cluster with the exact same set of hosts that I might want to override to?

No I don't think so. I think it can be arbitrary but I haven't used this code myself. cc @ramaraochavali who can likely advise.

**Comment by ramaraochavali** [comment]
@canselcik  You do not need a second cluster, You can have only  one `ORIGINAL_DST_CLUSTER` cluster and set this header in the request and that should route the request to the desired host.

**Comment by canselcik** [comment]
Thanks @mattklein123 and @ramaraochavali. Looks like `ORIGINAL_DST_CLUSTER` will work nicely and we can drop the `x-envoy-original-dst-host` on the request to enforce who gets to utilize this feature and on which hosts.
