### ISSUE TITLE
Is it possible to turn off the deprecation log?

### ISSUE THREAD

**Issue by zqzzq** [envoyproxy/envoy#6907]
**Issue Template**

*Title*: *One line description*

*Description*:
I use envoy by istio, and I found a lot of this kind of log in my logs :
```
[2019-05-11 07:03:08.700][23][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/
envoy/blob/master/DEPRECATED.md for details.
```
This makes it hard for me to find the logs I really want to see. So Is it possible to turn off these logs?

**Comment by mattklein123** [comment]
The field above was actually undeprecated so if Istio updates Envoy it should go away. cc @alyssawilk about potentially making this warning optional. It seems like something we probably don't want to do.

**Comment by alyssawilk** [comment]
Yeah, Istio had also asked if we could at least limit it to one log per field (for repeated entries), which is totally reasonable but not on anyone's TODO list.  I don't think we want to allow turning them down completely but if someone wants to limit them I think that's fine.
