### ISSUE TITLE
Add a new extension point that would allow to mutate configuration before it gets applied  

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#6909]
*Title*: Add a new extension point that would allow to mutate configuration before it gets applied

*Context*:
- Consider a use case where a company that uses Envoy-based Service Mesh wants to extend configuration generated by the Control Plane
- Specifically, it might want to apply a cross-cutting concern across the entire mesh, e.g. machine learning or WAF

*Proposal*:
- Add a new extension point that would allow to mutate configuration before it gets applied
- It will be implemented by custom extensions
- Users will be able to activate those custom extensions via bootstrap config

*Example*:
- Consider an example where a company wants to apply machine learning to HTTP traffic
- A company would need to
    - develop a custom extension that mutates given LDS configuration by injecting extra filters (with ML logic) into a filter chain
    - build a custom Envoy binary with that extension included
    - provide a bootstrap config that instructs Envoy to pass LDS configuration through that extension
- To turn the solution Into a reusable product, custom extension might be driven by its own xDS API

*Goals*:
- Facilitate a new usage scenario where a primary Control Plane (i.e., Istio, Consul Connect) could be accompanied by auxiliary Control Plane(s), e.g. one for machine learning, another for WAF, etc
- Facilitate new Envoy-based products that 
    - could stay more focused
    - could complement each other
    - could be combined with existing Control Planes

*Alternatives considered*:
- Although it might seem a better choice to mutate/aggregate configuration inside the Control Plane, that approach has its own drawbacks
    - Existing Control Plane implementations do not have much in common and do not assume extensibility in that sense
    - Running an extra component (responsible for mutation/aggregation) in between Envoy and Control Plane brings another sort of complexity

**Comment by mattklein123** [comment]
In general I really like this idea. I think there are some open questions around how we persist state and do merging such that if we have potentially N independent config sources, and each config source is potentially its own stream if config data, in what order does merging happen and who is responsible for doing it? @yskopets would you be willing to put together a slightly more detailed design doc for the feature? cc @htuch @fredlas for other comments/suggestions.

**Comment by yskopets** [comment]
@mattklein123 Sure, I will prepare the doc.

**Comment by fredlas** [comment]
No idea if this is actually going to be relevant, but: the integration test framework has something that sounds like this, in ConfigHelper::addConfigModifier. Maybe that can be a helpful reference for how it could be done, although maybe as a test-only thing it's too quick and dirty.

**Comment by htuch** [comment]
I think one approach would be to add a filter chain to `ApiConfigSource`, specifying the list of config transformation filters and their opaque config. Some of this gets quite self-referential though, so we need to figure out how to limit the complexity.

+1 to design doc, I think the general idea is a sound one and I've heard this request from other xDS users.

**Comment by yskopets** [comment]
@mattklein123 @htuch @fredlas Please take a look at a [design doc](https://docs.google.com/document/d/1RMpDwU6A6KkgbvtguFYccpygZ_4id9pfnEYbTzJ4DA0/edit?usp=sharing)

**Comment by htuch** [comment]
@yskopets I've left some feedback on your doc. Overall, I like the motivation and where this is going, this is pretty awesome. My main concern with the current proposal is "action at a distance". We have a bunch of configuration in bootstrap that then effectively overrides individual xDS APIs. Envoy's existing APIs are tree structured, and the configuration for EDS, for example, is not in the bootstrap but embedded in the `ConfigSource` of a `Cluster`. 

I would prefer to stick with this and be able to reason locally about configuration sources and their transformation. I think it's still possible to make this work quite nicely; e.g. if you want to insert an EDS transformer, you might first need to insert a CDS transformer to give you a hook point on EDS.

**Comment by mattklein123** [comment]
Left a few comments in the doc, also generally LGTM. We can continue discussion in the doc. Thank you for working on this.

**Comment by yskopets** [comment]
@htuch Ok, I will rework the proposal.

**Comment by mattklein123** [comment]
@yskopets out of curiosity do you know roughly when you plan on implementing this? We are interested in using this at Lyft in the next 3-6 months and wanted to get a rough idea of your thinking on timing.

**Comment by yskopets** [comment]
@mattklein123 I could start working on this in a couple weeks. 1 day per week.

**Comment by mattklein123** [comment]
@yskopets awesome sounds good. We can keep in touch and potentially help out regarding timing.

**Comment by mattklein123** [comment]
Note for watchers that we are trying to handle this as part of the v3/UDPA API work. @yskopets it would be great if you could sync up with @htuch at some point to make sure we have all of the federation use cases covered that you care about.

**Comment by htuch** [comment]
@yskopets we're making concrete forward progress on some xDS improvements related to federation at https://docs.google.com/document/d/1m5_Q9LUlzvDdImP0jqh1lSTrLMldsApTQX6ibbd3i7c/edit?ts=5ec2fd8a# FYI. It doesn't solve the immediate problem here but it provides some building blocks, e.g. authority delegation.

**Comment by htuch** [comment]
I'm wondering if this kind of functionality would be best homed out of proxy, perhaps in something like https://github.com/envoyproxy/xds-relay?
