### ISSUE TITLE
Overriding trace sampling configuration on a per route basis

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#6915]
*Description*:
When the envoy proxy is used as an ingress gateway for multiple endpoints/services it would be useful to set trace sampling parameters on a per service/endpoint basis. If defined, these would override the global values set at the filter level.

Proposal would be to add a trace sampling config to the [route](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-route).

**Comment by mattklein123** [comment]
@objectiser sounds reasonable to me.
