### ISSUE TITLE
subset lb: support matching any value in list metadata

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#6921]
Currently the subset lb treats the value of each metadata key as an opaque `Value`, comparing the comparing the hash of the value specified in the routing metadata with the hash of the corresponding value in the host metadata.

It would be useful to have the subset lb treat a `ListValue` metadata on the host as providing any of the list values as a value to the metadata key:

Given a host with metadata `labels: [label1, label2]` it would match both `labels: label1` and `labels: label2` criteria.

Today this is representable by adding `label1: true, label2: true` and matching on the individual keys, but this means that the cluster subsets need to be updated whenever a label is added, which requires rebuilding the cluster.

Implementing this should hopefully be fairly easy: if this is enabled for a given subset key and the host has a `ListValue` for this key, add a subset value for each element in the list. Some care will have to be taken to ensure that things work correctly when a single host contains multiple values for the same metadata key, as I believe the current invariants ensure that there is only a single value per key for each host.

**Comment by rgs1** [comment]
fwiw this as asked about early this year: https://groups.google.com/d/topic/envoy-users/WMt9Ob0NKkg/discussion
