### ISSUE TITLE
Reduce or make configurable dynamic header growth factor

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#6925]
We do simple doubling in `HeaderMapImpl` when computing `newCapacity()` today. This is wasteful, as we head towards the header limits and we might be able to implement some function that provides a gentler approach or make this configurable.

**Comment by htuch** [comment]
CC @fpesce

**Comment by dnoe** [comment]
An integration with the overload manager's resource monitoring could be worth exploring here too - the growth factor could use different levels of aggressiveness depending on memory pressure.

**Comment by mandarjog** [comment]
I have observed this behaviour while testing with Slowlaris clients and I confirmed with @fpesce.
The memory growth per new connection was much higher that the 4k headers that I was sending.

**Comment by dnoe** [comment]
@eziskind FYI for the overload manager integration idea.

**Comment by mattklein123** [comment]
FWIW I think we can likely just do away with the doubling, I think it's only useful for HTTP/1 since HTTP/2 will raise complete headers AFAIK. I'm not sure what the best option would be, but probably just increase to what is needed plus some rounding.

**Comment by dnoe** [comment]
With the fuzz coverage working again and not hung up on `valid()` assertion we can have the confidence to reduce this after https://github.com/envoyproxy/envoy/pull/6923.

**Comment by mattklein123** [comment]
This no longer applies as we rely on InlinedVector for this behavior now.
