### ISSUE TITLE
time: plumb in time-source rather than calling time(nullptr)

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#6953]
in server/server.cc, start_time_ is initialized with time(nullptr) -- we should use TimeSource, there and elsewhere.

**Comment by dichen16** [comment]
Hi @jmarantz ,
I'd like to take it !

**Comment by jmarantz** [comment]
Great! Looking forward to helping out with reviews.

**Comment by jmarantz** [comment]
Cross referencing an earlier attempt at this: https://github.com/envoyproxy/envoy/pull/7166

**Comment by dichen16** [comment]
still working on it

**Comment by NickLarsenNZ** [comment]
@jmarantz @dichen16  @derekargueta 
Should this issue be closed now that the PR has been merged, or is there more to do on it?

**Comment by jmarantz** [comment]
yes thanks!

**Comment by derekargueta** [comment]
There's still 3 other cases of `time(nullptr);`

https://github.com/envoyproxy/envoy/blob/4b69ef3d2da17f1239ae76367fc217c84118ef2d/source/server/server.cc#L60
https://github.com/envoyproxy/envoy/blob/4b69ef3d2da17f1239ae76367fc217c84118ef2d/source/server/server.cc#L193
https://github.com/envoyproxy/envoy/blob/c5f4302325223765b660f0f366ce25bf8570e7a5/test/common/router/router_upstream_log_test.cc#L313 (this one's just a test, but using TimeSource can help make it more accurate and not rely on a generous 300 second window for the test expectation)

**Comment by derekargueta** [comment]
I was thinking a nice follow-up after fixing these is to add a `time(nullptr)` check to `check_format.py`
