### ISSUE TITLE
Read back what port Envoy actually bound to

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#6959]
*Title*: *Read back what port Envoy actually bound to*

*Description*:
This is a somewhat half-baked idea, but we have a use-case where we want to set up a bunch of Envoy listeners (in the 100s), but we don't want to worry about having to allocate ports statically.

We don't want to have the control plane worry about what ports are free, and even if it did know, it would be (almost) impossible for the control plane to assign the ports to Envoy without there existing a race condition where something else binds to the port.

One way to do this is to tell Envoy "bind to any port" and then ask it back what port it ended up binding to. This is actually somewhat possible right now by giving Envoy a `port_value` of `0` and reading it back in the `/listeners` admin endpoint. However the `/listeners` admin endpoint doesn't tell us _which_ address corresponds to _which_ listener.

It feels like it would simply be an extension of the `/listeners` endpoint.

https://github.com/envoyproxy/envoy/issues/3010 sounds like it might be related, but I don't know the exact use-case internally at google (@alyssawilk)

**Comment by mattklein123** [comment]
@bplotnick yeah we should just make the `/listeners` endpoint better. This has come up several times. AFAIK write now it's only used for testing, so we should be able to make it better and fix the tests.

**Comment by ramaraochavali** [comment]
How about using '/config_dump' and parse [ListenersConfigDump](https://github.com/envoyproxy/envoy/blob/cbd8d57e9fc2921d26236db24b6bf91246ba3b4f/api/envoy/admin/v2alpha/config_dump.proto#L51) ?

**Comment by alyssawilk** [comment]
#3010 was more about upstream clusters - there are networks which associate different ephemeral port ranges with different QoS so that was more about upstream egress getting classified correctly.  Even if we had a similar feature for listeners I think if you're looking at many listeners and so many ranges you'd still run into trouble, so binding to 0 and having better information on /listeners sounds like the right fix to me.

**Comment by kaisen** [comment]
@ramaraochavali unfortunately `/config_dump` will only show a port value of 0 instead of the actual port that Envoy listens on.

**Comment by ramaraochavali** [comment]
Ok. Thank you. I did not notice that. So should we enhance /config_dump to
add the port?

**Comment by kaisen** [comment]
@ramaraochavali Adding the bound port to /config_dump would work as well. I don't really have a preference either way. Both would solve my issue of determining the actual bound port for a listener.
