### ISSUE TITLE
403 Forbidden when sending Upgrade: h2c to cluster configured with H1 & H2

### ISSUE THREAD

**Issue by gnz00** [envoyproxy/envoy#6972]
When a cluster has been configured with both H/1.1 & H/2 protocol options, Envoy returns a `403 Forbidden` response when sent a H2 upgrade request over H/1.1.

It isn't clear why Envoy returns a 403, I believe that Envoy should either:
- attempt to upgrade the request to H/2 _(resulting in 503 in scenario below)_
- ignore the upgrade and continue the request as H/1.1 _(resulting in 200 in scenario below)_

This is loosely related to #1502 and the lack of support for H/2 upgrades to upstream, but is a separate issue as I would expect H/2 to attempt a prior knowledge H/2 request to the upstream (resulting in a 503) or ignore the upgrade and use H/1.1.

***Example Requests***
In these requests, H/1.1 works as expected and H/2 fails as expected, however, `Upgrade: h2c` has an unexpected response of 403.

Sending an HTTP/1.1 request:
```bash
$ curl -v --http1.1 -H"Host: my-service.local" localhost:9900
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9900 (#0)
> GET / HTTP/1.1
> Host: my-service.local
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Thu, 16 May 2019 18:46:43 GMT
< cache-control: private
< content-type: text/plain
< vary: Accept-Encoding
< content-length: 36
< x-envoy-upstream-service-time: 165
< server: envoy
<
Hello from us-west-2!
```

Sending an HTTP/1.1 request with `Upgrade: h2c`:
```bash
$ curl -v --http2 -H"Host: my-service.local" localhost:9900
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9900 (#0)
> GET / HTTP/1.1
> Host: my-service.local
> User-Agent: curl/7.64.1
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
< HTTP/1.1 403 Forbidden
< date: Thu, 16 May 2019 18:46:47 GMT
< server: envoy
< connection: close
< content-length: 0
<
* Closing connection 0
```

Sending an HTTP/2 request:
```bash
$ curl -v --http2-prior-knowledge -H"Host: my-service.local" localhost:9900
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9900 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f806a008400)
> GET / HTTP/2
> Host: my-service.local
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 503
< content-length: 95
< content-type: text/plain
< date: Thu, 16 May 2019 18:46:52 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination* Closing connection 0
```

***Cluster Config***
```js
{
    "name": "my-service",
    "type": "EDS",
    "eds_cluster_config": {
        "eds_config": {
            "ads": {}
        }
    },
    "connect_timeout": "10s",
    "health_checks": [{
        "timeout": "10s",
        "interval": "10s",
        "unhealthy_threshold": 5,
        "healthy_threshold": 1,
        "tcp_health_check": {}
    }],
    "http_protocol_options": {},
    "http2_protocol_options": {},
    "protocol_selection": "USE_DOWNSTREAM_PROTOCOL"
}
```

***FilterChain Config***
```js
[{
    "filters": [{
        "name": "envoy.http_connection_manager",
        "typed_config": {
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
            "rds": {
                "config_source": {
                    "ads": {}
                },
                "route_config_name": "xds_routes"
            },
            "tracing": {
                "operation_name": "INGRESS"
            },
            "access_log": [{
                "config": {
                    "path": "/tmp/access.log"
                },
                "name": "envoy.file_access_log"
            }],
            "codec_type": "AUTO",
            "http_filters": [{
                "name": "envoy.router"
            }],
            "generate_request_id": true,
            "stat_prefix": "ingress_http"
        }
    }]
}]
```

***Route Config***
```js
{
    "name": "my-service.local",
    "domains": [
        "my-service.local",
        "my-service.local:*"
    ],
    "routes": [{
        "match": {
            "prefix": "/"
        },
        "route": {
            "weighted_clusters": {
                "clusters": [{
                    "name": "my-service",
                    "weight": 1000
                }],
                "total_weight": 1000
            }
        }
    }]
}
```

***Logs***
Here is the trace log for the unexpected case:
```
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:363] [C4027] parsing 182 bytes
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:476] [C4027] message begin
[2019-05-16 18:55:23.030][19][debug][http] [source/common/http/conn_manager_impl.cc:243] [C4027] new stream
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=Host value=my-service.local
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=User-Agent value=curl/7.64.1
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=Accept value=*/*
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=Connection value=Upgrade, HTTP2-Settings
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=Upgrade value=h2c
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:442] [C4027] headers complete
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:331] [C4027] completed header: key=HTTP2-Settings value=AAMAAABkAARAAAAAAAIAAAAA
[2019-05-16 18:55:23.030][19][trace][http] [source/common/http/http1/codec_impl.cc:450] [C4027] codec entering upgrade mode.
[2019-05-16 18:55:23.030][19][debug][http] [source/common/http/conn_manager_impl.cc:580] [C4027][S7904076430132816131] request headers complete (end_stream=false):
':authority', 'my-service.local'
':path', '/'
':method', 'GET'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'connection', 'Upgrade, HTTP2-Settings'
'upgrade', 'h2c'
'http2-settings', 'AAMAAABkAARAAAAAAAIAAAAA'
[2019-05-16 18:55:23.030][19][debug][http] [source/common/http/conn_manager_impl.cc:1278] [C4027][S7904076430132816131] encoding headers via codec (end_stream=true):
':status', '403'
'date', 'Thu, 16 May 2019 18:55:22 GMT'
'server', 'envoy'
'connection', 'close'
```

**Comment by gnz00** [comment]
@mattklein123 I would argue this could potentially be a bug, a 403 response is unexpected. Please correct me if I'm wrong.

**Comment by mattklein123** [comment]
@gnz00 If Envoy is sending a 403 in this case sounds like a bug, but I'm not sure what is going on here. Would need to debug more deeply on what code path is being hit.

**Comment by gnz00** [comment]
FWIW I am also seeing a 403 Forbidden response when sending a Websocket upgrade request, e.g. `Upgrade: websocket` over H/1.1 with the same configuration. I haven't dug into it any further though.

**Comment by gnz00** [comment]
As it turns out, adding an upgrade_config entry for “websocket” caused websockets to work as intended. However, adding an upgrade_config entry for “h2c” still results in a 403 Forbidden.

**Comment by gnz00** [comment]
@mattklein123 Looking at the code `autoCreateCodec` returns a Http/1.1 connection which at some point returns a 403. Seems like there 2 possible solutions to this and #1502, 

1. We could modify `autoCreateCodec` to choose H2 if Http2ProtocolOptions is defined and `Upgrade: h2c` and `Connection: upgrade` are both present. We would need to prepend an h2c upgrade filter on the response chain that ensures the initial response is `101 Switching Protocols` to close to H1 connection before sending H2 frames. I’m not sure if the filter is the best way of doing this or it could be part of the H2 codec implementation.

2. We could modify the H1 codec implementation to ignore the upgrade request and remove the headers to prevent the underlying error causing the 403.

It seems that doing both of these changes would make upgrade requests work according to spec for all 3 codec types in the config: h1, h2, and auto.

I’d be willing to take a crack at it if you agree this is a worthwhile and sensible approach. I haven’t fully grokked the codebase or the filter chain implementation so would really appreciate any feedback.

**Comment by mattklein123** [comment]
@gnz00 H1 -> H2 upgrade is tracked here: https://github.com/envoyproxy/envoy/issues/1502. I think the correct implementation is a new connection pool type that implements it.

re: 403, I don't think that has anything to do with Envoy. I think your upstream server is returning 403 somehow.

**Comment by gnz00** [comment]
@mattklein123 
I think you're right, just did some testing and I believe that it's hitting the H1 path and the server is rejecting the H1 connection. Seems like H1 codec implementation properly ignores the Upgrade request. I'm trying to come up with a configuration that generically works for all services in service discovery without knowing what the underlying protocols supported by each service are.

By connection pool type are you referring to the `codec_type` config property? From my understanding of the code, if the type is `auto` and it's an Http/1.1 upgrade request it will always hit the Http/1.1 code path here: https://github.com/envoyproxy/envoy/blob/e35380787d4f17b9a422cf92fe5ba23622389955/source/common/http/conn_manager_utility.cc#L44

It seems way simpler to me to just change this to detect an H1->H2 upgrade and opt-in to the H2 path and then handle terminating the H1 connection with a `101 Switching Protocols` response?

**Comment by mattklein123** [comment]
> It seems way simpler to me to just change this to detect an H1->H2 upgrade and opt-in to the H2 path and then handle terminating the H1 connection with a 101 Switching Protocols response?

In Envoy, downstream and upstream are disjoint. https://github.com/envoyproxy/envoy/issues/1502 tracks upstream upgrade. I think you are asking for downstream upgrade, which yes, is different. I would open a different clean issue to track that and we can discuss implementation if you want.

**Comment by gnz00** [comment]
@mattklein123 Awesome, thanks for your time. I'll open up a new one and tag you there.
