### ISSUE TITLE
Request to merge implementation for configuring (add/hide) 'x-forwarded-proto' header by envoy

### ISSUE THREAD

**Issue by ramachaitanyak** [envoyproxy/envoy#6989]
*Description*:
>* Envoy currently is adding the 'x-forwarded-proto' header to the requests from downstream clients to its upstream by default. This patch helps this operation be configuration driven, where in by setting the exclude_request_forwarded_proto variable to true, the header is not added to Envoy's upstream and the header is added all otherwise.
>* The patch includes the addition of 'exclude_request_forwarded_proto' boolean to 'http_connection_manager.proto' and appropriate handling of this variable to either add or hide the 'x-forwarded-proto' header to envoy upstream.
 > * The boolean 'exclude_request_forwarded_proto' does not have any effect on upstream requests where the 'x-forwarded-proto' header is explicitly configured by the client.

[*Relevant Links*:]
> Notes on 'x-forwarded-proto' header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by dio** [comment]
Sorry, 
@ramachaitanyak do you have the relevant link for you patch/PR?

**Comment by ramachaitanyak** [comment]
Hi Dhi, I apologize for the delay. I have a pull request here https://github.com/envoyproxy/envoy/pull/7013 outlining the set of changes. Please let me know your thoughts and comments.

Thanks!
Rama

**Comment by ramachaitanyak** [comment]
Hi Dhi, I realized that I made changes with respect to an older stable release of envoy. I will need to update the patch with latest API and usage; however if you are curious about the overview of my changes; please take a look; if not I will push updated patch soon. Thanks!
