### ISSUE TITLE
Support customizing the scope of stats

### ISSUE THREAD

**Issue by fcfort** [envoyproxy/envoy#6990]
This isn't a concrete proposal, I wanted to get a discussion going to see what's possible in this vein.

The problem that we have is that many classes of stats aren't scoped at a granularity that we'd like to report at. For instance all the [CONN_MAN_LISTENER_STATS](https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_config.h#L121) are listener address/port scoped while we typically want to report stats at the cluster name scope.

Our use of Envoy is multi-tenant at the L7 layer and so the same listener address may go to any of 10k+ cluster names, which means the stats aren't particularly meaningful to us at the listener address level.

While we can use the `AccessLogInstanceFactory` to register an access logger and recreate the stats we need via the request/response headers and stream info, this feels like an unnecessary duplication of effort.

Ideally we'd like some way of providing configuration that allows us to specify the scope or scopes to register particular stats at. This scope would then be used to create the stats so that the scope would be additionally tagged with that scope, e.g. the name of the cluster and would be able to get the name of the cluster from context.

I read through the comments on #3351, and it sounds like when others have encountered issues like this they also solved it via AccessLog hooks. I agree that any proposal should be opt-in due to cardinality issues.

**Comment by mattklein123** [comment]
@fcfort many of the stats you reference are replicated at both the cluster and HCM layer. At a high level I think it's fine to offer stat prefix/scope configuration (and we do that in some places) but could you potentially be a little more specific with what things you want to configure? It might help focus the conversation a bit. Thank you.

**Comment by fcfort** [comment]
I see. Do you have a code reference to where Envoy offers stat scope config? Do you mean like the `stat_prefix` fields in the proto config?

As a more concrete example, `downstream_rq_5xx` from `CONN_MAN_LISTENER_STATS` is scoped at the per-HCM level. We'd like to report these on a per-cluster name basis if possible. As I understand it from your comment, Envoy currently supports specifying a `stat_prefix` on `HttpConnectionManager` proto but then that would entail creating a unique HCM per cluster name. 

I'd prefer to be able to specify or declare that a given stat should be "grouped by" cluster name rather than have to change the cardinality of the HCM itself. 

If the preference is that we should duplicate or move the individual stats that we desire as cluster stats underneath `ALL_CLUSTER_STATS` that's reasonable too, I was just thinking that perhaps other Envoy clients might find the need to customize this in a way that perhaps isn't particular to my desired grouping on cluster name.

**Comment by mattklein123** [comment]
@fcfort we do have upstream_rq_5xx on a per-cluster basis. For this specific question though, how would you always charge a downstream 5xx to a cluster? There might not be any cluster assigned yet. This is why we split downstream and upstream response codes in this way.
