### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by keith** [envoyproxy/envoy#6995]
This issue tracks incompatible bazel changes that cause upstream bazel CI test failures.

Starting today we have upstream bazel CI building and testing envoy so bazel can catch issues sooner. As part of this we want to try and stay ahead of upcoming breaking bazel changes (more discussion [here](https://github.com/bazelbuild/continuous-integration/pull/653)).

Now that this is enabled I want to take a first pass on trying to get us to incompatible change 0, so future changes are easier to keep up with.

Here's the most recent build showing us which specific changes we aren't compatible with https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/110#72eb6717-c478-44de-833d-b7da832ee58e

From a quick test locally most of these incompatibilities are coming from upstream dependencies. I will submit a series of PRs to update these were applicable and link them to this issue.

cc @htuch @laurentlb

**Comment by keith** [comment]
I've submitted a PR against protoc-gen-validate with some changes https://github.com/envoyproxy/protoc-gen-validate/pull/200

**Comment by keith** [comment]
We're being hit by https://github.com/bazelbuild/bazel/issues/7849 which I'm not sure what the migration plan is for, but it appears to be affecting protobuf directly as well.

**Comment by laurentlb** [comment]
Two flags I'd like to flip soon are:
- `--incompatible_depset_is_not_iterable` (broken due to https://github.com/envoyproxy/protoc-gen-validate)
- `--incompatible_disable_deprecated_attr_params` (broken due to grpc, but I think grpc has been fixed)

**Comment by htuch** [comment]
CC @lizan @moderation @fcfort. Do we have any Bazel ninjas who can give the fixes for this a shot? Also @rodaine for PGV aspects.

**Comment by keith** [comment]
I'm currently working on some of these. I'll post an update shortly.


--
Keith Smiley

**Comment by keith** [comment]
Ok so when building on macOS, using [this branch of protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate/pull/198), master from rules_foreign_cc, and ignoring this flag https://github.com/bazelbuild/bazel/issues/7260#issuecomment-494163344

I'm at migration 0. I don't see the issue with `--incompatible_disable_deprecated_attr_params`, @laurentlb any idea why? If we did have to update grpc, we'd need to wait until their current pre-release was actually released.

**Comment by laurentlb** [comment]
Repro:

```
$ bazel build --nobuild --incompatible_disable_deprecated_attr_params test/...
...
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/71d59151158aafb7db935cf8065f6d0c/external/com_lyft_protoc_gen_validate/bazel/protobuf.bzl", line 155, in rule
		attr.label(cfg = "host", default = Label("@co..."), <2 more arguments>)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
```

-> Need to update https://github.com/envoyproxy/protoc-gen-validate/blob/master/bazel/protobuf.bzl (running `buildifier --lint=fix` might be enough)


Repro:

```
$ bazel build --nobuild --incompatible_depset_is_not_iterable test/...
...
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/71d59151158aafb7db935cf8065f6d0c/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 10, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.transitive_imports]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

This comes from grpc (I haven't checked if/when it was fixed in grpc).

**Comment by fcfort** [comment]
Looks like @keith has fixes for both issues in https://github.com/envoyproxy/protoc-gen-validate/pull/198, which are blocked on https://github.com/envoyproxy/protoc-gen-validate/pull/200 going in as well.

**Comment by keith** [comment]
I've submitted the grpc change upstream https://github.com/grpc/grpc/pull/19097 I didn't see that because I was testing against `//source/...` not `//test/...`

**Comment by hlopko** [comment]
Hi all, I'm updating all Bazel incompatible flags related issues - the Bazel team is in increased pressure because 0.27 will start a 3 month window of no incompatible changes). We will have to potentially temporarily disable envoy on our downstream pipeline if we cannot get it fixed this week.

**Comment by hlopko** [comment]
To consolidate efforts, these issues are also related to Bazel incompatible flags:

* https://github.com/envoyproxy/envoy/pull/7058 - migrates for https://github.com/bazelbuild/bazel/issues/7260 and https://github.com/bazelbuild/bazel/issues/7793
* https://github.com/envoyproxy/envoy/issues/6968 - requires for https://github.com/bazelbuild/bazel/issues/7687.
* https://github.com/envoyproxy/envoy/pull/6866 - (seemingly stalled?) update of Bazel to 0.25.

**Comment by keith** [comment]
@hlopko let me know if I can help with any of these!

**Comment by hlopko** [comment]
Both https://github.com/envoyproxy/envoy/issues/6968 and https://github.com/envoyproxy/envoy/pull/6866 could use somebody with Envoy domain knowledge to push them forward :)

https://github.com/envoyproxy/envoy/pull/7058 seems unblocked and will be submitted hopefully soon.

**Comment by hlopko** [comment]
Seems this issue could be closed?

**Comment by mattklein123** [comment]
Closing, thank you @keith @hlopko for driving this forward!
