### ISSUE TITLE
Support google.api.HttpBody for requests in gRPC-JSON transcoder

### ISSUE THREAD

**Issue by RichardSieg** [envoyproxy/envoy#7007]
**Add support for request bodies which are not in JSON format**

*Description*:

It is already possible to make a response with a non-JSON HttpBody thanks to [this PR](https://github.com/envoyproxy/envoy/pull/3793). What about the `google.api.HttpBody` for the request field? Like the following example from the `.proto` [definition](https://github.com/googleapis/googleapis/blob/master/google/api/httpbody.proto):
```
message GetResourceRequest {
   // A unique request id.
   string request_id = 1;

   // The raw HTTP body is bound to this field.
   google.api.HttpBody http_body = 2;
}

service ResourceService {
     rpc GetResource(GetResourceRequest) returns (google.api.HttpBody);
     rpc UpdateResource(google.api.HttpBody) returns
     (google.protobuf.Empty);
}
```

**Comment by dio** [comment]
@RichardSieg to clarify, you want to send the request arbitrarily? e.g. set the content-type with other than application/json?

**Comment by RichardSieg** [comment]
Yes, that's the feature I'd like to have :)

**Comment by alvioshki** [comment]
I am also interested in such a functionality +1

**Comment by hbgongen** [comment]
interested +1~

**Comment by har07** [comment]
also interested +1

**Comment by zhizhen5** [comment]
also interested +1 :)

**Comment by splilly1987** [comment]
also interested! +1

**Comment by AlexRoman** [comment]
also interested! :+1:

**Comment by shixiaoliu** [comment]
also interested!!! +1

**Comment by dounan** [comment]
FYI: https://github.com/envoyproxy/envoy/pull/10110

**Comment by marufmax** [comment]
interested +1

**Comment by dounan** [comment]
@RichardSieg @dio can we close this ticket now that https://github.com/envoyproxy/envoy/pull/10110 is merged?
