### ISSUE TITLE
NO-OP Support for Envoy Routes

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#7017]
We need a feature in envoy where we might have some routes where we don't want to take any action on route match (something like NOOP), subsequently, this request will be matched with the route we want to take action on. we will just maintain some stats on these routes (routes with NOP) and query them later to see how many times we hit those particular routes. This will help us in testing these routes based on route match before we enable traffic to these routes. Do we have something like this in envoy or any easier way to do it ?

**Comment by mattklein123** [comment]
I don't think we have anything like this today. However, it does intersect with a feature that I do want to add which is opt-in per-route stats, which can be also tied in with the ongoing support to add a name to a route. Can you flesh out a concrete design proposal for how this would work and respond back?

**Comment by pitiwari** [comment]
thanks @mattklein123. I will work on it and propose it

**Comment by pitiwari** [comment]
@mattklein123 here is the design document. Please provide the feedback and we will make changes accordingly

https://docs.google.com/document/d/1u_HOy96rp6WL4Y6mVqWmiO1NXySM4uvVTVXsRK9B2FY/edit?usp=sharing

**Comment by mattklein123** [comment]
@pitiwari at a high level this makes sense to me, but the use of a magic "no_op" header feels a bit magic and hacky to me. Any thoughts on a different approach for that part? Either making the header configurable somehow, not using a header and somehow relying on other state for not picking a no-op header again, etc.

Also, what type of stats are you going to increment? How will that work exactly?

**Comment by pitiwari** [comment]
@mattklein123 . I wanted to clarify that we were planning to use the header which is provided in no-op route by the user, it can be any header but for each no-op route header should be different. We will add that header to request headers which will help us in avoiding to pick the same no-route again.

I spent some time to figure out the non header approach. Since currently route match is done by going through the vector of routes and then returning the matched route, so we can keep an index of next route to start matching from instead of doing match from the beginning every time. In this way we can skip the already matched routes. We also had to reset the index to beginning in cases like clearRouteCache calls.

For the metric part, we are planning to add access log entry x-no-op-routes and keep on appending no-op route name to this key.

I had updated design document with the second approach and access log details, please have a look and provide feedback.

**Comment by pitiwari** [comment]
@mattklein123 did you got chance to look at the updated design

**Comment by mattklein123** [comment]
Sorry for the delay. I added some comments to the doc. Let's continue discussion there.

**Comment by pitiwari** [comment]
@mattklein123 i had replied to your comments, please have a look.

**Comment by pitiwari** [comment]
@mattklein123 Thanks for providing your input. I had replied to your new comments, please have a look.

**Comment by pitiwari** [comment]
@mattklein123 I was able to find a way to keep index without being persistent, please check out my reply in the doc
