### ISSUE TITLE
Capture Response Body?

### ISSUE THREAD

**Issue by rp4fx12** [envoyproxy/envoy#7073]
Is there a way to easily capture a response body and headers from requests being sent through envoy? I'm trying to see if there's an easy way to capture them so that I can limit the amount of work that needs to be done on an api. I know I can capture request data by using shadow deployments but not sure about the response.

**Comment by jmarantz** [comment]
Capture it where? A new Envoy filter can be written to capture a response body and write it somewhere; not sure if there's a built-in one that does that.

**Comment by mattklein123** [comment]
You can use tap support: https://www.envoyproxy.io/docs/envoy/latest/operations/traffic_tapping
