### ISSUE TITLE
Envoy process memory much higher than allocated heap

### ISSUE THREAD

**Issue by Strainy** [envoyproxy/envoy#7084]
I'd like to understand the relationship between the envoy process memory and the reported heap stats. 

For context, I'm operating Envoy as a front proxy, with 3 upstreams and it experiences moderate traffic (peaks at ~4rps).

It looks like the envoy process itself is using about 184MB:
```
$ ps ax -o command,rss
COMMAND                       RSS
/usr/local/bin/dumb-init --    88
python /app/hot_restarter.p 54280
envoy -c /etc/envoy.yaml -- 188484
bash                         4168
ps ax -o command,rss         1588
```

However, the memory stats seem to indicate that the heap size is only 19MB.
```
$ wget -qO - http://localhost:10049/memory
{
 "allocated": "13372960",
 "heap_size": "19922944",
 "pageheap_unmapped": "0",
 "pageheap_free": "925696",
 "total_thread_cache": "2935264"
}
```

Is it unusual for the process memory to be so much higher?

**Comment by jmarantz** [comment]
anything interesting in envoy.yaml for you? Do you use xDS to add dynamic configuration after startup?

How was your Envoy built? By you? If so, which build options did you use?

Or if it is a release image, which version?

**Comment by Strainy** [comment]
We're running the official envoy Docker image: `envoyproxy/envoy@sha256:2f61a649cfbcd5ead787f0eed69ad819b035ceebff4f6e064a313f34f71f9696` 

Here's the server info:
```
$ wget -qO - http://localhost:10049/server_info
{
 "version": "ea248e2919db841b4f3cc5e2c44dcbd90565467d/1.9.1/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 48,
  "config_path": "/etc/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "hot_restart_version": false,
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "16384",
  "max_obj_name_len": "60",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "uptime_current_epoch": "24163s",
 "uptime_all_epochs": "24163s"
}
```

In terms of the envoy.yaml, we're using the DataDog extension for tracing and stats. We also have a Lua script in the http.filter chain that performs a JSON decode of a header added by our auth system and appends some of that information as additional headers to the request.

We don't use xDS. We just use the `hot-restarter.py` script, with a small modification to restart Envoy when external configuration changes (this is pull based / polled from within the python script every 60 seconds).

**Comment by jmarantz** [comment]
I have 3 guesses: Lua, envoy binary size, and docker allocation.

My first thought is that Lua is using its own memory management infrastructure which bypasses tcmalloc -- the system used by default in Envoy on many platforms. Lua may be allocating a significant chunk of memory for its own garbage-collected world.

But really I have no data on which to make this claim.  Maybe @dio knows more about Lua and memory management. Does Lua bypass tcmalloc or does it use normal malloc()/new to get its memory?

I would guess that Lua would not allocate that much memory by default, but maybe your access patterns are combing with Lua's GC to release memory too slowly?


Another guess I had was binary size, but that is probably not an issue given you are using the supplied docker image.

What about docker itself? Does that allocate some memory up front when creating its container?

**Comment by Strainy** [comment]
Is it possible to monitor Lua memory allocation? I can only see `server.memory_allocated` and `server.memory_heap_size` reported from the `/stats` endpoint 🤔 

Docker itself might allocate some memory, but I'm really looking at the envoy process memory specifically. 

We recently changed our AWS instance type, and as such the host (not the container) has significantly more memory available. Would that have an impact?

**Comment by AmitKatyal-Sophos** [comment]
I am also observing the same behaviour. Process memory usage is 300 MB but allocated memory reported by admin/memory endpoint is 67 MB.

Any idea what else is contributing to the memory usage ?. RES memory usage after running the top command inside the envoy container gives 334 MB

<img width="557" alt="image" src="https://github.com/envoyproxy/envoy/assets/95272694/7211b1b7-cd8f-4448-8d0e-5ecc1d826dca">

**Comment by behnamnikbakht** [comment]
I have the similar problem with Envoy wasm plugin. I created a reproducable test [here](https://github.com/behnamnikbakht/proxywasm-memory-test)
