### ISSUE TITLE
Endianness issue with encoding IPv6 addresses as uint128_t variables

### ISSUE THREAD

**Issue by pjunodsc** [envoyproxy/envoy#7096]
The line https://github.com/envoyproxy/envoy/blob/a3cb9ad136a8eacbfae12d52f45d6baf4a73fabf/source/common/network/address_impl.cc#L262
is supposed to convert an IPv6 address expressed as an array of 16 bytes in network byte order (aka big-endian) from a POSIX-compliant `struct in6_addr` object in a `uint128_t` variable. Unfortunately, it does so without taking into account endianness issues. 

Network order means big-endianness, i.e., that the most significant byte has the lower address in the array, while the least significant byte has the higher address. So, given an array of 16 bytes `a[0], a[1], ..., a[14], a[15]` in network byte order, the corresponding `uint128_t` integer is supposed to be
```
a[0]*2^120 + a[1]*2^112 + ... + a[14]*2^8 + a[15]
```

That `memcpy()` call does not take into account the way abseil internally encodes the `uint128_t`, which can potentially change and can be (is, in fact) dependent of the underlying CPU endianness.

This code works well on big-endian CPUs. 

On a little-endian CPU, abseil encodes `uint128_t` as

```
class {
   uint64_t _lo;
   uint64_t _hi;
}
```
This means that the `memcpy()` will result in storing the number
```
a[15]*2^120 + a[14]*2^112 + ... + a[8]*2^64 + a[7]*2^56 + a[6]*2^48 + ... + a[1]*2^8 + a[0]
```

In particular, this makes the usage of `uint128_t` Boolean operations problematic when working with IPv6 addresses encoded as integers, which can be useful in certain circumstances.

**Comment by jmarantz** [comment]
@pjunodsc nice catch; are you volunteering to fix?

**Comment by pjunodsc** [comment]
Coming back. After having thought more carefully about this issue, it appears that `envoy` follows the same semantic that the structure `struct in_addr` for IPv4: when fetching the field `sin_addr.s_addr`, you receive the address in network order (aka big endian). Then, it's the responsibility of the application to convert it to host endianness, typically using `ntohl()`. 

My bad. It's a non-issue.
