### ISSUE TITLE
Consider publishing a debug build along with the release build

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/envoy#710]
Since the release builds turn off `trace` and `debug` logging, but those loglevels can be helpful for debugging things in development, publishing a debug build might make things easier for development.

**Comment by mattklein123** [comment]
We are no longer building a pure debug build due to CI pressure so its not easy to publish a docker image from CI. It's buildable locally and documented. Going to punt on this for now until we are on a less crappy CI system.
