### ISSUE TITLE
stats: simplify data structures

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#7109]
There are a few opportunities for both code simplification and moderate memory reduction due to @fredlas removal of shared-memory stats. Off the top of my head:
 * We don't need the Gauge and Counter to share any underlying data structure so fields used by only one of them can be elided in the other. They were previously shared to make it easier to do uniform block allocation in a fixed sized shared-memory block.
 * I don't think we need two levels of reference counting; we should just be able to get away with 1.
 * The basic implementations of the structures are split between heap_stat_data.h and stat_data_allocator_impl.h, which were previously needed for templatizing the system to share impls between heap-allocated and raw-allocated variants. Now there is only one variant so we can un-templatize and collapse some of this.

There may be more exposed after those reductions and simplifications.

**Comment by mattklein123** [comment]
Big +1, these are the kinds of simplifications I was hoping for with shared memory gone.

**Comment by jmarantz** [comment]
Of course I don't want to start down any of these till https://github.com/envoyproxy/envoy/pull/7083 is in :)

**Comment by fredlas** [comment]
Great, sounds like the stats directory will be much easier to read on the other side of this work!

**Comment by jmarantz** [comment]
#7295 is an incremental step toward simplification, mostly collapsing 2 Allocator data structures, removing some templatization.

Next step is to split HeapStatData into Counter and Gauge variants, as Gauge will likely need to add a mutex to resolve a race between value-updating and import-mode resolution. But Gauge doesn't need pending_increment, so I think that can be a wash in size, and would be straightforward and easy to reason about.

A more aggressive idea is to remove the two levels of ref-counting, and that is straightforward to do -- and one of the intermediate commits in #7295 achieves that, but it is actually more expensive in memory so I rolled that back. The reference-counting in HeapStatData is actually free as the 16-bit reference count is hiding in data that would otherwise be wasted in padding. The extra cost is in the use of a complex web of maps, shared_ptr, and weak_ptr structures which are clean but bloated.

To make that save memory over the current state, we could remove the CounterSharedPtr and GaugeSharedPtr usage, and just embed the reference-count in the objects. The shared-pointers are mostly used by scopes and their caches, and an explicit ownership model should mostly work there too, and likely save 16 or more bytes per stat, which would save a material ~1500 bytes per cluster, justifying (arguably) the added complexity. The fly in the ointment is where stats are shared between multiple scopes. I don't fully understand how that situation arises, and will investigate.

**Comment by jmarantz** [comment]
will follow-up off bug with a class rename to finish this off
