### ISSUE TITLE
Add DynamicSecretConfig information in `config_dump` endpoint

### ISSUE THREAD

**Issue by incfly** [envoyproxy/envoy#7111]
*Title*: *Better Secrets Config Dump for SDS*

*Description*

We lack debugging information about secrets (specifically key/cert) that is fetched by SDS.

What we have today
- :<admin_port>/config_dump prints out the listener/cluster/etc, where SDS configuration is inlined.
- :<admin_port>/certs prints out all the certificates from the `ContextManager`.

What we want
- Something similar to [`admin.v2alpha.ListenersConfigDump.DynamicListener`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/admin/v2alpha/config_dump.proto), we can have a 
`admin.v2apha.SecretsConfigDump.DynamicSecrets` (name made up)
- It shows `last_updated`, `version_info`,(these two fields are helpful for debugging) SDS configuration.
- `/config_dump` prints out a separate section about the `dynamic_listener`, and we have one entry per resource name.
- (optional) add a field for different type of secrets, prints out their relevant information. E.G cert prints out the `SAN` `TTL`.

*Alternative*

I considered a separate `/secretes`, but that does not seem suitable given what 'clusters' 'listeners' are all about the stats.

**Comment by mattklein123** [comment]
+1 this sounds great.

**Comment by JimmyCYJ** [comment]
Per discussion with @PiotrSikora we will file a separate issue for /certs to add annotations or something similar to make it clear the type of each cert (static, inline, SDS). Perhaps it would be nice if we can add SDS resource name into the annotation, so that we can associate /certs with /config_dump while debugging SDS related issues.

**Comment by incfly** [comment]
@mattklein123 Could you assign this to me and @JimmyCYJ ? We've sync-ed with @PiotrSikora about this and plan to work on it as part of improving SDS debug-ability in general.
