### ISSUE TITLE
HTTP/1.0 responses without Connection: keep-alive should be closed.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#7123]
**Issue Template**

*Title*: HTTP/1.0 responses without Connection: keep-alive should be closed.

*Description*:
The HTTP/1.0 specification says that connections carry a single request and then are closed unless the response includes "Connection: keep-alive".

[optional *Relevant Links*:]
https://tools.ietf.org/html/rfc1945
https://en.wikipedia.org/wiki/HTTP_persistent_connection

**Bug Template**

*Title*: HTTP/1.0 connections with no Connection header are kept alive when they should be closed.

*Description*:
HTTP/1.0 connections with no Connection header are kept alive when they should be closed.   This can cause 503 errors if the connection is reused.

*Repro steps*:
Set up envoy in front of a flask server (which is HTTP/1.0) and run siege against it.  You will see Failed transactions.

**Comment by mattklein123** [comment]
This is fixed.
