### ISSUE TITLE
What's the best way to send additional side-requests in an ActiveHealthCheckSession?

### ISSUE THREAD

**Issue by canselcik** [envoyproxy/envoy#7144]
Hi,

I am trying to healthcheck a service behind Envoy that requires more than one request to be made from Envoy.

Basically:

1- send request to origin
2- get response, use that response to send another request to the same origin
3- assert something about that response and based on that mark the origin active or not

And I am wondering what would be the best way to do (2).

I could re-use 
```
request_encoder_ = &client_->newStream(*this);
request_encoder_->getStream().addCallbacks(*this);
```

in the same `ActiveHealthCheckSession` however I feel like there might be an easier way. Perhaps something using the `StreamDecoderWrapper` or `AsyncClientImpl`.

Thanks.

**Comment by canselcik** [comment]
@mattklein123 feel free to mark it as a "question". Any pointers are appreciated. :)

**Comment by mattklein123** [comment]
@canselcik I would potentially take a look at integration tests if you want some inspiration. Fundamentally, yes, you need to make multiple streams/requests against the upstream server.
