### ISSUE TITLE
How to force Envoy free up unused memory?

### ISSUE THREAD

**Issue by arjunsanal** [envoyproxy/envoy#7151]
**Issue Template**

*Title*: *How to force Envoy free up unused memory?*

*Description*:
>It is observed that envoy continues to consume memory even after the load on process is gone. I have found from envoy and TCMalloc documentation that this behaviour of not returning memory back to OS is expected. Is there a way to force envoy to release the memory back to OS?
I am using the official docker image envoyproxy/envoy-alpine:v1.10.0.

[optional *Relevant Links*:]
>http://goog-perftools.sourceforge.net/doc/tcmalloc.html 
https://www.envoyproxy.io/docs/envoy/latest/api-v2/admin/v2alpha/memory.proto.html

**Comment by lizan** [comment]
@arjunsanal the link you're referring for tcmalloc is outdated. See https://gperftools.github.io/gperftools/tcmalloc.html, try set `TCMALLOC_RELEASE_RATE` env to a higher value?

Envoy doesn't provide an explicit API to call `ReleaseFreeMemory`, adding an admin endpoint seems reasonable, PR is welcome.

**Comment by arjunsanal** [comment]
Thanks. This helps.
