### ISSUE TITLE
Add HTTP/1.1 tests to test/common/http/htt1/conn_pool_test.cc

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#7158]
**Issue Template**

*Title*: Add HTTP/1.1 tests to test/common/http/htt1/conn_pool_test.cc

*Description*:
Currently the tests in  test/common/http/htt1/conn_pool_test.cc are for HTTP/1.0 because the protocol_ variable is not set because the parser_ is not run.  We should have tests which cover HTTP/1.1 as well.

**Comment by derekargueta** [comment]
It seems the referenced PR (#7124) fixed this by setting the default protocol to HTTP/1.1 for all tests except when overridden for HTTP/1.0-specific tests?
