### ISSUE TITLE
timer: enableTimer with microsecond granularity

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#7170]
QuicAlarm supports alarm at various granularities. For the integration, QuicAlarm will be backed by Event::Timer. But Event::TimerImpl::enableTimer() takes milliseconds and then converts to microseconds before scheduling the underlying timer. If a QuicAlarm is scheduled at microsecond, casting it to millisecond while passing it to Event::Timer::enableTimer() will cause the alarm to be scheduled several event loops later. This isn't a very serious problem consider the RTT is usually much larger than 1ms. But it will be a problem if Envoy is used in an environment with small RTT with QUIC.

It'll be nice if Timer interface can directly support microsecond granularity or even better support std::chrono::duration.

**Comment by htuch** [comment]
I think this partly is a function of `libevent` and its coarse grained timers. I know @mergeconflict was looking into the depths of timer granularity not that long ago..

**Comment by mergeconflict** [comment]
> I know @mergeconflict was looking into the depths of timer granularity not that long ago..

I didn't investigate in any significant detail, but I'm happy to review PRs for this.
