### ISSUE TITLE
Filter stats from stats/prometheus

### ISSUE THREAD

**Issue by StrongMonkey** [envoyproxy/envoy#7173]
**Issue Template**

*Title*: ability to filter stats from stats/prometheus

*Description*:
For `/stats`, there is a way to query(filter) stats based on regexp(adding ?filter). So I am wondering if there are similar expressions for `stats/prometheus`? I have a use case which I want to query stats from `/stats/prometheus` outside of envoy and would like to expect some query paramters  that can be applied through the endpoint.

**Comment by mattklein123** [comment]
It looks like the filter regex is not passed to the prometheus handler. This should be a very simple change if someone would like to do a beginner PR.

https://github.com/envoyproxy/envoy/blob/c167c65b8b93a3bcd92ba24c50c6f175b053f06e/source/server/http/admin.cc#L726

**Comment by StrongMonkey** [comment]
@mattklein123 thanks for the quick response! I ll put a pr

**Comment by mattklein123** [comment]
Fixed
