### ISSUE TITLE
redis: triggering cluster topology rediscovery upon receiving redirection errors

### ISSUE THREAD

**Issue by msukalski** [envoyproxy/envoy#7174]
*Title*: 

redis: triggering cluster topology rediscovery upon receiving redirection errors

*Description*:

The new Redis cluster support discovers the cluster's topology upon startup and periodically at a refresh interval that is configurable. This issue outlines a design proposal to trigger an immediate topology rediscovery upon receiving moved/ask redirection errors from upstream servers, providing responsiveness while allowing periodic refreshes to be minimized.

Key design considerations:
1) realistic limiting controls to prevent too many rediscovery sessions from being triggered, and posts to the main thread dispatcher should be minimized.
2) a safe functor posted on the main thread dispatcher is needed to execute the cluster discovery code, and the functor must be safe when the cluster has been removed/destroyed before it is run.

The controls will be part of the connection pool settings, config.filter.network.redis_proxy.v2.RedisProxy.ConnPoolSettings. A minimum time interval that must be pass before a rediscovery trigger can be issued after the last one will be specified as min_rediscovery_trigger_interval, and will default to 10s. redirects_per_minute_threshold will control how many redirection errors are received per minute (on a second granularity) on all worker threads for a given cluster/connection pool before rediscovery is triggered. These controls will be processed in a ConnPool::Instance::onRedirection() handler, and the statistics will be protected with a Thread::MutexBasicLockable (more later) since this handler will be called from multiple threads.

A rough outline of the code flow follows:

In the existing CommandSplitter onRedirection() calls, upon successful creation of the redirected request, a new void ConnPool::Instance::onRedirection() will be called (via conn_pool_). 

This cross-thread ConnPool handler will call a new cluster manager void onRedirection(cluster_name) routine that will check to see if discovery should be triggered, and if so look up the cluster's shared pointer in active_clusters_, initialize a weak pointer from that pointer, and capture it in a functor that is posted on the main thread dispatcher. 
A new cluster counter statistic will be incremented, upstream_internal_redirect_membership_check, upon posting.

The functor will attempt to lock() the weak pointer to convert it into a shared pointer. If that succeeds then the cluster still exists, and its new Cluster::onRedirection() handler will be called. This handler will not do anything for most clusters, but the RedisCluster version will set it discovery timer to 0 for immediate execution.

[optional *Relevant Links*:]

This is continuation work for Issue #5697 ("Support for redis cluster protocol"). PR #7126 (now closed) extended outlier detection support with a new result code, WRONG_HOST, and supporting code to provide this facility with slightly different configuration parameters.

**Comment by msukalski** [comment]
@HenryYYang , @FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg , and @mattklein123 -- here is my summary of what I'm proposing as a replacement for PR #7126. Please let me know what you think. I'll start putting something together, assuming that I'll need to change direction based on your feedback.

**Comment by mattklein123** [comment]
Thanks @msukalski. This is on the right track but needs a few changes.

> the statistics will be protected with a Thread::MutexBasicLockable (more later) since this handler will be called from multiple threads.

You can use atomics here. I don't think you need any locks.

> This cross-thread ConnPool handler will call a new cluster manager void onRedirection(cluster_name) routine that will check to see if discovery should be triggered

It's not acceptable to add any core code for this feature that is specific to this feature. If you want to add generic facilities that plugins can use, that's fine, although I don't think that's necessary in this case. The way I would implement this is the following:
1) Utilize the singleton manager: https://github.com/envoyproxy/envoy/blob/master/include/envoy/singleton/manager.h (you can search the code base for other uses).
2) Create a `RedisRedirectionManager` singleton, that perhaps creates a `RedisRedirectionTracker` keyed by cluster name. Thus, there is a single redirection manager for the server dynamically created, and then it hands out a tracker that the cluster and filter (connection pool) share keyed by cluster name. This can all get cleaned up if both get torn down.
3) Now that you have a shared tracker, you can roughly implement the logic you have outlined, but it's entirely specific to the redis code. Each conn pool can increment redirections, and then post to the main thread for handling, and then the cluster can register for tracker callbacks to refresh.

Hopefully ^ is enough to go on. LMK if not.

**Comment by msukalski** [comment]
Thanks @mattklein123 for the detailed information and guidance!
