### ISSUE TITLE
quiche: add support for QuicClock::ApproximateNow 

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#7177]
QuicClock::ApproximateNow() provides a cheaper way to get current time than calling std::steady_clock::now(). It returns a slightly lagged timestamp which is usually within acceptable range. But currently EnvoyQuicClock implements it in the same way as Now() which does call std::steady_clock::now().

A typically implementation is to store a timestamp in each event loop and return that timestamp for ApproximateNow(). In Envoy LibeventScheduler::prepare_time_|check_time_ can serve this purpose. Since DispatcherImpl owns libeventScheduler, we can add an interface Dispatcher::getSchedulerPrepareTime() to return LibeventScheduler::prepare_time_. And instead of referencing TimeSystem in QuicClock, we can change it to reference a Dispatcher which also provides TimeSource interface.

**Comment by danzh2010** [comment]
Please reopen this issue

**Comment by danzh2010** [comment]
@mattklein123 It seems that I don't have permission to assign issue. How to get the permission?

**Comment by mattklein123** [comment]
They need to be added to the org. I will send an invite.
