### ISSUE TITLE
build: consistent debug symbols/copts in public images for external deps

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7178]
We set various options in envoy_build_system.bzl, and we should audit to figure out which options should potentially be instead set as part of bazelrc copts for different profiles. The main one that comes to mind is consistent use of `-ggdb3` for envoy and all deps. There may be others.

cc @lizan @keith @jmillikin-stripe

**Comment by keith** [comment]
Another thing we noticed when working on NDK support that is related to this is that the top level cc_binary gets some linkopts like `-lm` that are also required even if you're not using the binary target. I'm not sure how those should be handled but ideally they would be pushed down to the targets that actually need them.

**Comment by htuch** [comment]
As long as you push this to `.bazelrc`, `rules_foreign_cc` should be smart enough to pick up on it and propagate it out to the external deps.

**Comment by mattklein123** [comment]
I think with various bazel rules updates this is working now for external deps. Closing. We can open new issues as needed.
