### ISSUE TITLE
Envoy Buffering TCP connection

### ISSUE THREAD

**Issue by comron** [envoyproxy/envoy#7186]
**Issue Template**

*Buffering TCP Connection*: *Envoy seems to be buffering the initial response from an upstream SMTP*

*Description*:
I'm using envoy in an Istio deployment. I've noticed when I deploy the envoy sidecar to a postfix SMTP server I get strange behavior. Namely the initial MOTD/Banner/220 response from the postfix server is not presented to the client until a message is sent from the client to the server. This causes some clients to timeout while they wait for the initial protocol message.

Here is a connection made without the proxy in between:
```
$ telnet postfix-relay 25
Trying 172.20.232.172...
Connected to postfix-relay.default.svc.cluster.local.
Escape character is '^]'.
220 postfix-relay-749cf779c8-8zhg7.localdomain ESMTP Postfix
HELO example.com
250 postfix-relay-749cf779c8-8zhg7.localdomain
^]
telnet>
```

And here is a connection made with envoy in the middle. 
```
$ telnet postfix-relay 25
Trying 172.20.232.172...
Connected to postfix-relay.default.svc.cluster.local.
Escape character is '^]'.
HELO example.com
220 postfix-relay-6f789ddcd5-fl9qm.localdomain ESMTP Postfix
250 postfix-relay-6f789ddcd5-fl9qm.localdomain
^]
telnet>
```

Note that the client is coming from a Kubernetes pod that does not have the Istio envoy sidecar enabled, so there is only one envoy in the middle of these connections.

*Logs*:
Let me know what other information I can provide since this is in an Istio deployment, I'm not sure what the relevant logs would be. Here are the logs from the postfix container and sidecar, there doesn't seem to be any envoy logging that correlates with the connections that are being made.

[logs-from-istio-proxy-in-postfix-relay-6f789ddcd5-6m7rj (1).txt](https://github.com/envoyproxy/envoy/files/3260318/logs-from-istio-proxy-in-postfix-relay-6f789ddcd5-6m7rj.1.txt)

[logs-from-postfix-in-postfix-relay-6f789ddcd5-6m7rj (1).txt](https://github.com/envoyproxy/envoy/files/3260320/logs-from-postfix-in-postfix-relay-6f789ddcd5-6m7rj.1.txt)

**Comment by lizan** [comment]
This is expected behavior when you have mTLS in permissive mode. Istio proxy is trying to see first bytes to see whether the connection is TLS. Make your mTLS strict or disable it would solve the issue.

**Comment by comron** [comment]
That makes perfect sense, thanks for clearing that up. It works as expected with mTLS turned off via policy.

**Comment by lizan** [comment]
Closing as answered, feel free to re-open or raise a new one if you have more question.
