### ISSUE TITLE
stats_integration_test failing on Bazel CI

### ISSUE THREAD

**Issue by philwo** [envoyproxy/envoy#7196]
Seems like Envoy is red on Bazel CI since Monday:

Last green build: https://buildkite.com/bazel/envoy/builds/318
First red build: https://buildkite.com/bazel/envoy/builds/319

The stats_integration_test is failing, here's a log: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/c6b3f0ac-027d-4295-87e8-1a75bd7510b2/test/integration/stats_integration_test/attempt_1.log

Could you please have a look?

FYI @htuch @keith
also FYI @laszlocsomor (current Bazel Green Team sheriff)

**Comment by htuch** [comment]
@lizan FYI

**Comment by lizan** [comment]
I think we should run `MemoryLargeClusterSizeWithStats` selectively and only check exact number in CI since it is environment dependent. @cmluciano do you have time to work on it?

**Comment by cmluciano** [comment]
@lizan yes I can work on this. Do you think guarding this test with a flag that we only trigger in the envoy ci would suffice?

**Comment by jmarantz** [comment]
Is the issue that we are running with one C++ std library in CI and a different one in development?

Can we just always run with the same C++ std library in dev and CI?

**Comment by jmarantz** [comment]
Alternatively we can pick one libstdc++ implementation and only run the expected-memory tests when using that one. But it would be easier to work with if we were able to reproduce CI failures when testing locally, so just changing the bazel default to whatever we use in CI seems like the best plan.

**Comment by lizan** [comment]
@jmarantz one in our CI is different one in bazel CI.

> Alternatively we can pick one libstdc++ implementation and only run the expected-memory tests when using that one. But it would be easier to work with if we were able to reproduce CI failures when testing locally, so just changing the bazel default to whatever we use in CI seems like the best plan.

We don't know which exact STL class is causing the change between versions so it would be hard to detect. If you're running our build docker image you always get same.

**Comment by jmarantz** [comment]
I was thinking that there must be some build config change to switch STL versions, which we could then augment with something that adds a -DSTL_LIB_XXXX type compile-flag, which we could then use to switch off the tests.  But I don't see that in https://github.com/envoyproxy/envoy/pull/6866

I noticed that when I run stats_integration_test locally now, it fails, but it works in CI.  This is not a great situation; we have to fix this by either making the comparison sloppy, by checking against 2 alternative expected values, or by using an ifdef to have it only run in one mode.

What is Bazel CI and how does that differ from our normal CI that gets run on every PR?

**Comment by jmarantz** [comment]
I have a heuristic that tells me which mode we're in by measuring the tcmalloc stats after allocating some strings. The difference is subtler than I thought, but we can use it to turn off the test. But I think we probably would be better off getting our dev builds and Bazel CI to use the same libraries as we use in CI. @lizan how hard do you think that would be?

**Comment by jmarantz** [comment]
From limited testing with my heuristic I think there's some other difference between what we are doing in CI and what's happening on our local machines, beyond libc++.

We may need more approximate metrics for tracking memory consumption if we can't get our dev and test environments to behave consistently.

**Comment by cmluciano** [comment]
At the inception of this test I also found the memory to fluctuate between a few of my dev machines which caused me to go with approximate value rather than the hard EQ.

@jmarantz Is the value you hit locally greater or less than what we get in CircleCI?

**Comment by cmluciano** [comment]
The [latest BuildKite master build](https://buildkite.com/bazel/envoy/builds/410#06bec4e3-be18-402e-861e-5742350cf05d)  yields `m_per_cluster == 49449` and I get the same value when I run the test locally. 

I'm trying to diff the .bazelrc files b/t the various CI systems now.

**Comment by lizan** [comment]
Anything outside of our build docker image is inconsistent, IMO we can do either (or both):
- bake a config/environment into the build image and do exact eq if that exists.
- do a approximate value comparison

> From limited testing with my heuristic I think there's some other difference between what we are doing in CI and what's happening on our local machines, beyond libc++.

The libraries that bazel is not managing are: libc, libm, libgcc, pthread and libstdc++ (or libc++), so all of those libraries can affect this number.

**Comment by cmluciano** [comment]
Looks like @jmarantz has a WIP with #7208

**Comment by jmarantz** [comment]
Yup, I have gotten it to work with default build, and am now verifying it with `//test/... --config libc++ a`

**Comment by philwo** [comment]
Thank you everyone for getting at this so quickly! :))

By the way, would you like to get Bazel CI status checks for your PRs, too? That way you could immediately see if it something fixes a breakage (or if something breaks it). I should be able to just turn it on in our settings, but wanted to check with you first.

**Comment by jmarantz** [comment]
I still don't know, btw, whether this will work with Bazel CI, or what the difference is between the two CIs and our dev environment. It had seemed all consistent until roughly this week.

RE Bazel CI status checks: can you clarify what that means? What would that do beyond our own integrated CI?

**Comment by philwo** [comment]
> RE Bazel CI status checks: can you clarify what that means? What would that do beyond our own integrated CI?

Bazel CI is a service that the Bazel team provides for free to Bazel and its ecosystem. We provide a user-friendly UI to view test results (thanks to the great folks at [Buildkite](https://buildkite.com/)) and high-performance machines for Linux/Docker, Windows (both currently on 32-core GCE VMs) and macOS (18-core iMac Pros). It comes with RBE support for remote builds and caching, too. It's also super easy to configure (just specify in a YAML file which targets you want to build / test on which platform, we handle the rest). Our mandate is to build the best CI possible for and together with Bazel users. :)

The idea is basically: Everyone gets a free CI and Bazel gets more testing to ensure that we don't accidentally break our users. The only thing we ask for is that projects keep their CI green, because otherwise we can't get any signal whether a change to Bazel broke you or not.

If that sounds cool, you could use it in addition to or instead of other CI solutions that you're currently using. (FYI the initial discussion when we added Envoy to our CI was here: https://github.com/bazelbuild/continuous-integration/pull/653)

**Comment by keith** [comment]
@mattklein123 who I was discussing this with before I went on vacation.

**Comment by mattklein123** [comment]
cc @lizan who is in charge of making our CI better. ^
