### ISSUE TITLE
Envoy breaks on Bazel CI with Bazel@HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [envoyproxy/envoy#7201]
The Envoy pipeline on Bazel CI breaks with Bazel at HEAD.

CI log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1026#e8a068f5-8491-4981-a7ba-5d9951d87b97
Source tree: https://github.com/envoyproxy/envoy/commit/79bdfaf0e4a9769d824bc60994f1030994fb6e7f
Bazel version: built at https://github.com/bazelbuild/bazel/commit/12c7942f45185e15ac26c383644b5d63a3c25269

Looks like the culprit is rules_foreign_cc.

Build log:
```
  | ERROR: An error occurred during the fetch of repository 'foreign_cc_platform_utils':
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/342871ee9762a33d3e13523e61431417/external/rules_foreign_cc/workspace_definitions.bzl", line 9
  | rctx.file("BUILD.bazel", "\n".join([_build_t...)]))
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/342871ee9762a33d3e13523e61431417/external/rules_foreign_cc/workspace_definitions.bzl", line 9, in rctx.file
  | "\n".join([_build_tools(rctx), _build_mode...)])
  | sequence element must be a string (got 'NoneType'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/342871ee9762a33d3e13523e61431417/external/envoy/bazel/foreign_cc/BUILD:32:1: @envoy//bazel/foreign_cc:luajit depends on @foreign_cc_platform_utils//:compilation_mode in repository @foreign_cc_platform_utils which failed to fetch
```

**Comment by laurentlb** [comment]
This is supposed to be fixed at head (since https://github.com/envoyproxy/envoy/pull/7168).
The reason why you saw the error is because we test on the last green build, which is getting old (https://github.com/envoyproxy/envoy/issues/7196).

**Comment by mattklein123** [comment]
I think this is fixed?

**Comment by keith** [comment]
Yea lets close this one and open a new one with new details if there's an issue now that 0.28.0 is out
