### ISSUE TITLE
extenstion / feature request - omit canary hosts during retry of a failed request

### ISSUE THREAD

**Issue by sriduth** [envoyproxy/envoy#7203]
*Title*: *Retry predicate that can omit canary hosts*

*Description*:

In a canary deployment, failures in the canary subset can be retried on other non canary hosts that are part of the cluster.

**Comment by snowp** [comment]
This should be easy to do with a host predicate that just checks for `!host->canary()`, possibly with an accompanying retry priority plugin if this needs to be done across priorities as well.

**Comment by sriduth** [comment]
If this would be a useful addition, I'd like to try to implement this.
