### ISSUE TITLE
handling a response that exceed 1mb

### ISSUE THREAD

**Issue by nesobe123** [envoyproxy/envoy#7204]
Title : handling a response that exceed 1mb

Description: I am using envoy proxy + grpc service written on spring boot. When I add a couple of messages and want to get list of them by http call I am getting next error.

content-type →application/grpc
grpc-status →2
grpc-message →Internal Server Error
content-length →0

sum of all messages exceed 1mb. Looks like it is default value for rq / rs. 
How to handle such case if I want to send or get a message that exceed 100 mb for example. 

Thanks in advance for any help.

**Comment by lizan** [comment]
Try adjusting the `per_connection_buffer_limit_bytes` in your cluster.
See https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto

**Comment by nesobe123** [comment]
> Try adjusting the `per_connection_buffer_limit_bytes` in your cluster.
> See https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto

many thanks for so quick help. Now it works normally. Faced with another issue & going to inspect envoy references for timeout settings =)
