### ISSUE TITLE
memory: test against exact value in CI, approximate at other times.

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#7216]
Until ~June 6, 2019, our memory-delta measurements were byte-accurate, and we could crisply use EXPECT_EQ to track memory bloat in tests.

However around that time, there were divergences whose sources are not completely known. One of these is use of libstdc++ which inlines short strings (length <= 22 bytes) into std::string, however that was not the only source of entropy. Other sources are not known.

Note that we do *not* seem to be having memory allocation pattern variations due to non-deterministic real-time timing in multi-threaded tests, yet. Though that might happen in the future.

In the meantime, as a stop gap, EXPECT_EQ memory tests were changed to EXPECT_LE in https://github.com/envoyproxy/envoy/pull/7208 to resolve https://github.com/envoyproxy/envoy/issues/7196 . We need to allow for the maximum memory used in an operation on any platform where we run memory-tests, including all platforms where we use TCMALLOC.

However this is not ideal: if you are developing on a platform that uses less memory, you may not notice you've bloated memory until the test runs on another platform, such as Bazel CI or Envoy CI on MacOS.

So the idea here is to have exact comparisons run only when running in CI -- which we can convey to the test code with a compile-time define. When running outside of CI we can use some sort of approximation and EXPECT_LE.

@lizan @mattklein123 @htuch WDYT?

**Comment by mattklein123** [comment]
Big +1. Let's just have a compile flag that makes it a hard EQ in only our CI. That way we don't break Bazel CI, dev builds, etc.

**Comment by htuch** [comment]
Yeah, sounds good. If we could set this on exactly one CI job even better. Even more awesome would be if we could compute the replacement diff in the test and emit this :) Then people can copy+paste the log entry and new value to the test.

**Comment by jmarantz** [comment]
Which test should it be in? I haven't figured out exactly what is a canonical functional test in CI. release?

**Comment by htuch** [comment]
Yep, `release`, since that is as close to prod as we can get.
