### ISSUE TITLE
Terminate upstream connection after every request/stream

### ISSUE THREAD

**Issue by conqerAtapple** [envoyproxy/envoy#7217]
**Issue Template**

*Title*: Feature request - Terminate upstream connection after every request/stream

*Description*:
Currently envoy keeps the connection open to upstream cluster. But we want to disable it. Already tried `max_requests_per_connection:1` and `max_concurrent_streams: 1`. We want the upstream connection to close after every request.
One use case is: Upstream instance has multi-process model  and uses SO_REUSEPORT to balance requests between connections. With one persistent connection open to a process, all requests will end up being served by same worker process.

**Comment by conqerAtapple** [comment]
@mattklein123

**Comment by mattklein123** [comment]
@conqerAtapple assuming you are talking about HTTP the settings you specify should work. Will need more config details, etc. to understand what is going on.

**Comment by conqerAtapple** [comment]
@mattklien123 no the request is for gRPC proxying. Since h2 connections are persistent to upstream, it effects upstreams who are load balanced by single-socket multi-processs architecture. How do we opt out of the upstream persistent connection? Essentially a connection pool size of 0.

**Comment by mattklein123** [comment]
The settings you identify should work, effectively max requests per connection.

**Comment by conqerAtapple** [comment]
@mattklein123 We already tried that configuration(max_requests_per_connection). What we see is that -
- Without envoy (grpc client -> grpc server) requests have increasing streamid. This is because grpc client increases streamId on the same connection.
- With envoy in between as gRPC proxy, envoy does not terminate the connection to the gRPC server after the request. Our observation is that envoy sometimes reuses the old connection if the request is sent after a certain time. This causes gRPC server to fail as it sees a duplicate streamid for the same connection.

So the question is : is there a "time" associated with the max_requests_per_connection within which the request is sent to a new connection?

**Comment by mattklein123** [comment]
> So the question is : is there a "time" associated with the max_requests_per_connection within which the request is sent to a new connection?

No, I don't think so. I would take a look at the http/2 connection pool code.

**Comment by conqerAtapple** [comment]
The connection is definitely not closed after each request. We do see new connections (with old connections still open). The "time" factor is something we are still investigating. Your insight will save a lot of time on our end. Thanks!
