### ISSUE TITLE
downstream_pre_cx_timeout stat is incorrectly incremented

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#7219]
While debugging a `no healthy upstream` issue, I figured out that  `downstream_pre_cx_timeout` is incorrectly incremented. We send a request to upstream and it fails with `no healthy upstream` error. The following stats are incremented correctly

`listener.0.0.0.0_8443.http.0.0.0.0_8443.downstream_rq_5xx: 103
listener.0.0.0.0_8443.http.0.0.0.0_8443.downstream_rq_completed: 108`

However after 15s (which is the default listener filter timeout) the stat `listener.0.0.0.0_8443.downstream_pre_cx_timeout` is incremented. 

I think this stat should not be incremented in this case. Is this a bug or am I missing some thing?

**Comment by mattklein123** [comment]
I doubt these two events are related, but definitely take a look at the code and let us know if you see any timer bugs.

**Comment by ramaraochavali** [comment]
@mattklein123 I have not looked at the code yet, but I think it may be a timer issue. As soon as the request fails, I see `no heathy upstream` response and `http.0.0.0.0_8443.downstream_rq_5xx` and `http.0.0.0.0_8443.downstream_rq_completed` are incremented immediately. This makes me think that  filter chain is complete and after 15s `downstream_pre_cx_timeout` is incremented.
