### ISSUE TITLE
FIPS 140-2 for ppc64le

### ISSUE THREAD

**Issue by clyang82** [envoyproxy/envoy#7221]
I saw the document about [FIPS 140-2](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/ssl#fips-140-2)

> BoringSSL can be built in a FIPS-compliant mode, following the build instructions from the Security Policy for BoringCrypto module, using --define boringssl=fips Bazel option. Currently, this option is only available on Linux-x86_64.

@PiotrSikora Does BoringSSL with fips enabled support in ppc64le?

**Comment by mattklein123** [comment]
cc @davidben

**Comment by PiotrSikora** [comment]
@clyang82 per the [Security Policy for BoringCrypto module](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3318.pdf), BoringSSL FIPS is supported on ppc64le only on POWER9 (cc @agl to confirm), but currently there is no support for it in Envoy.

**Comment by agl** [comment]
That's correct: we currently maintain validation on x86-64 and POWER9. (An older version was validated on POWER8 too.)

**Comment by clyang82** [comment]
Thanks @PiotrSikora  and @agl  How hard to support it in Envoy? 
Just change it to `"@bazel_tools//platforms:ppc",`?
https://github.com/envoyproxy/envoy/blob/f7aa9710cd1e2d11dec3ec75b8f6d6b41dc53919/bazel/BUILD#L156

Can you share some experience how to test to ensure envoy supports fips? I think just verify version is not enough. Thanks again.

**Comment by PiotrSikora** [comment]
@clyang82 you'd need to extend [`boringssl_fips.genrule_cmd`](https://github.com/envoyproxy/envoy/blob/f7aa9710cd1e2d11dec3ec75b8f6d6b41dc53919/bazel/external/boringssl_fips.genrule_cmd) to support building on ppc64le, ideally restricted to POWER9.

While this shouldn't be hard, there are no official prebuilt binaries for LLVM 6.0.1 and Ninja for ppc64le, which means that they would need to be built as part of the build process.

Alternatively, we could distribute precompiled BoringSSL libraries for various architectures, but that's probably more of a request to the BoringSSL team. @agl any thoughts on that?

**Comment by clyang82** [comment]
> @clyang82 you'd need to extend [`boringssl_fips.genrule_cmd`](https://github.com/envoyproxy/envoy/blob/f7aa9710cd1e2d11dec3ec75b8f6d6b41dc53919/bazel/external/boringssl_fips.genrule_cmd) to support building on ppc64le, ideally restricted to POWER9.
> 
> While this shouldn't be hard, there are no official prebuilt binaries for LLVM 6.0.1 and Ninja for ppc64le, which means that they would need to be built as part of the build process.
> 
> Alternatively, we could distribute precompiled BoringSSL libraries for various architectures, but that's probably more of a request to the BoringSSL team. @agl any thoughts on that?

Thanks for your guidance. Can you also share how to verify or test it? Do you have automation cases for it?

**Comment by clnperez** [comment]
could we mark this as staleproof?

**Comment by mattklein123** [comment]
Closing this as won't fix. We don't have a ppc build, let alone FIPS for it.
