### ISSUE TITLE
Dynamodb Filters for all table operations

### ISSUE THREAD

**Issue by emise** [envoyproxy/envoy#7240]
*Description*:
It seems like the existing dynamodb filters do not support operations like `TransactWriteItems` (https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html).

What is needed to get support of all existing DynamoDB table operations? If not all, then just

`TransactGetItems`
`TransactWriteItems`

**Comment by hallie** [comment]
Would this mostly just be adding `TransactGetItems` and `TransactWriteItems` to the [RequestParser::BATCH_OPERATIONS](https://github.com/envoyproxy/envoy/blob/3a596a4b0f8a8c3e60ff6240508a1d7395a9bacd/source/extensions/filters/http/dynamo/dynamo_request_parser.cc#L54) vector?

**Comment by mattklein123** [comment]
Correct it should be fairly straightforward to add parsing for new/different APIs using the existing code as a guide.
