### ISSUE TITLE
with_request_body configuration for ExtAuthZ doesnt work with PUT requests

### ISSUE THREAD

**Issue by ec** [envoyproxy/envoy#7247]
*Description*:
Good day!) We are using v1.10.0 and we upgraded from v1.9.0 exactly because of the feature.
For some reasons we need to have request body on our custom AuthZ (for implementing audit logic)

With the following configuration it works fine for query params and for request params for POST requests. But PUT remains empty
```ruby
          - name: envoy.ext_authz
            config:
              http_service:
                with_request_body:
                  max_request_bytes: 8192
                  allow_partial_message: true
```

Expected behaviour: having request params on authz level for PUT

If im missing something - will be thankfull for any clarification

[*Relevant Links*:]
Here is what i am talking about
https://www.envoyproxy.io/docs/envoy/v1.10.0/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto.html?highlight=with_request_body

**Comment by mattklein123** [comment]
cc @gsagula @dio

**Comment by ec** [comment]
Still waiting for any feedback)
Just UP, as issue already go deep

cc @gsagula  @dio  @mattklein123

**Comment by dio** [comment]
@ec sorry missing this. I'll try to check on v1.10.0, since I couldn't reproduce it on master.

**Comment by ec** [comment]
@dio thanks a lot. Looking forward )
If any additional info required from my side - i can get it fast

**Comment by dio** [comment]
@ec Sorry, I couldn't reproduce your issue 😢. This is my repro repo: https://github.com/dio/issue-7247

As you can see, by running the compose file, I can inspect the body of PUT requests from the "ext auth service".

**Comment by ec** [comment]
Thank you @dio I will go and check again. 2 times.
And with your repo as well

Will come back to update situation.
Thanks
