### ISSUE TITLE
Add instrumentation for unexpected upstream closes.

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#7248]
**Issue Template**

*Title*: Add instrumentation for unexpected upstream closes.

*Description*:
HTTP/1.1 has an inherent race where the upstream server can close the connection at any time and an in-flight request can fail.  This is especially problematic for POST requests which may not be idempotent.  We should instrument these closes to determine what additional steps Envoy can take to mitigate errors.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/issues/7228

**Comment by mattklein123** [comment]
There are already stats around this. See the "destroyed with active rq" family of stats.
