### ISSUE TITLE
Support Runtime values in router check tool

### ISSUE THREAD

**Issue by jyotima** [envoyproxy/envoy#7264]
*Title*: Router check tool does not support runtime values

*Description*:
> The router check tool tool today does not support runtime values and its documented [here](https://www.envoyproxy.io/docs/envoy/latest/install/tools/route_table_check_tool.html). 

We use a lot of routes based on runtime configs and will help catch issues better and earlier if runtime was supported.

**Comment by jyotimahapatra** [comment]
#730

**Comment by jyotimahapatra** [comment]
@hennna I observed this enhancement also mentioned in issue #730 . I could use any ideas you already have  around this.
