### ISSUE TITLE
BufferFragmentImpl destructor not called by GoogleGrpcUtils, which may result in memory leak

### ISSUE THREAD

**Issue by curiouserrandy** [envoyproxy/envoy#7266]
*Title*: BufferFragmentImpl destructor not called by GoogleGrpcUtils, which may result in memory leak

*Description*:
In GoogleGrpcUtils::makeBufferInstance, a "placement new" is used to allocate several instances of Buffer::BufferFragmentImpl into a previously allocated memory block that contains all of those objects.  The BufferFragmentImpl's use a releasor function to indicate when they are done with the memory, which releasor function uses a reference counter.  When all BufferFragmentImpls are done with the memory, the memory is deallocated in a block.  This means that the BufferFragmentImpl's *constructor* is called (by the placement new) but the class instances *destructor* is never called.  

If BufferFragmentImpl was a POD (plane old data) class, this would be fine.  However, it includes a std::function<> element.  That element is constructed via copying on construction of the BufferFragmentImpl.  If any memory is allocated in std::function<>'s constructor, it will be leaked.  I'm seeing such a leak in one of the internal tests we run @ Google; the backtrace is provided below.  

This is obviously dependent on the details of and path taken in std::function<>'s constructor.  That may explain why it wasn't seen in any CircleCI tests, and only in one of the many tests run on import into Google.  I'll admit that those two points still confuse me (i.e. why this isn't a more obvious leak than it appears to be) but I'm fairly comfortable in the bug by code inspection, so I figured I'd file it and get any feedback people had.

BufferFragmentImpl placement new construction: https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/google_grpc_utils.cc#L100

BufferFragmentImpl's containing memory block's free: https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/google_grpc_utils.cc#L89

BufferFragmentImpl's definition: https://github.com/envoyproxy/envoy/blob/master/source/common/buffer/buffer_impl.h#L422

**Comment by curiouserrandy** [comment]
Sorry, backtrace actually provided:

E0613 22:14:15.579488    7941 heap-profile-table.cc:489] RAW: Leak of 48 bytes in 6 objects allocated from:
        @ 0x558bb5a3b7ea third_party/crosstool/v18/stable/toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/functional:1879 std::__g::_Funct\
ion_base::_Base_manager<>::_M_clone()
        @ 0x558bb5a3b674 third_party/crosstool/v18/stable/toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/functional:1915 std::__g::_Funct\
ion_base::_Base_manager<>::_M_manager()
        @ 0x558bb5a3c33f third_party/crosstool/v18/stable/toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/functional:2411 std::__g::functi\
on<>::function()
        @ 0x558bb5a3c113 ./third_party/envoy/src/source/common/buffer/buffer_impl.h:425 Envoy::Buffer::BufferFragmentImpl::BufferFragmentImpl()
        @ 0x558bb5a3b193 third_party/envoy/src/source/common/grpc/google_grpc_utils.cc:100 Envoy::Grpc::GoogleGrpcUtils::makeBufferInstance()
        @ 0x558bb5a284fd third_party/envoy/src/source/common/grpc/google_async_client_impl.cc:322 Envoy::Grpc::GoogleAsyncStreamImpl::handleOpCompletion()
        @ 0x558bb5a25352 third_party/envoy/src/source/common/grpc/google_async_client_impl.cc:252 Envoy::Grpc::GoogleAsyncStreamImpl::onCompletedOps()
        @ 0x558bb5a2a1d8 third_party/envoy/src/source/common/grpc/google_async_client_impl.cc:62 Envoy::Grpc::GoogleAsyncClientThreadLocal::completionThread()::$_1::operator()()
        @ 0x558bb5a2a06d third_party/crosstool/v18/stable/toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/functional:2041 std::__g::_Funct\
ion_handler<>::_M_invoke()
        @ 0x558baeceb18e third_party/crosstool/v18/stable/toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/functional:2440 std::__g::functi\
on<>::operator()()
        @ 0x558bb84b426d third_party/envoy/src/source/common/event/dispatcher_impl.cc:198 Envoy::Event

**Comment by mattklein123** [comment]
cc @jplevyak

**Comment by lizan** [comment]
Per https://github.com/envoyproxy/envoy/blob/master/source/common/grpc/google_grpc_utils.cc#L67 I think the BufferFragmentImpl is only freed and its destructor is not called. Thus the destructor of std::function<> in BufferFragmentImpl is not called but just freed. Yeah it depends on the impl detail of std::function<>. I'm working on a fix.
