### ISSUE TITLE
docs: add RBAC and JWT to security arch overview

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7285]
https://github.com/envoyproxy/envoy/tree/master/docs/root/intro/arch_overview

**Comment by lizan** [comment]
cc @yangminzhu @qiwzhang

**Comment by yangminzhu** [comment]
Thanks, I created a PR for rbac: https://github.com/envoyproxy/envoy/pull/7289

I think @qiwzhang should have better knowledge on the JWT filter.
