### ISSUE TITLE
istio envoy dont fallback to http1.1

### ISSUE THREAD

**Issue by tjholwik** [envoyproxy/envoy#7288]
**Issue Template**
we are using istio 1.1.7 which is using envoy under the hood and we have some external tools which is using `http 1.1` and **not** http2, we have tried to change this config via the following which doesn't help, please advice .

see istio tread
https://github.com/istio/istio/issues/14708 

```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-w
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: bide-tls
      hosts:
        - istio.dev1.stv.net.tsr
    - port:
        number: 80
        name: http-wd
        protocol: HTTP
      hosts:
        - istio.dev1.stv.net.tsr
      tls:
        httpsRedirect: true 
```

*Title*: *One line description*

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behavior, what scenario it enables and how it
would be used.

**Comment by tjholwik** [comment]
@mattklein123 - IMO this is a bug and not question :)

**Comment by mattklein123** [comment]
The Envoy project has no knowledge of Istio config. I would bring it up with them. If you have Envoy config that we can look at happy to do so, otherwise I don't have enough information to determine if this is a bug or not.
