### ISSUE TITLE
feature: http and network filter that load and run dynamic filters (.so files)

### ISSUE THREAD

**Issue by atrifan** [envoyproxy/envoy#7291]
**Issue Template**

*Title*: *Write a http & network filter that are capable of running dynamic filters - .so files*

*Description*:
>We would like a native envoy http & network filter capable of invoking dynamic filters compiled as .so. Main reason is that this can easily be integrated to grab remote .so files download them in envoy location and run them - making it easy to deploy a new version of that filter or other filter. Another reason is that you are able to write your filters in go and than with cgo make a .so file that can easily be included and run through this filter 

We can contribute this feature back to envoy if it's relevant for you guys. We would like this to be a part of envoy since we don't want to build our custom envoy. 

Do you think it's worth it? Do you see any performance impact or other potential issues?

Thanks.

**Comment by mattklein123** [comment]
I think this is a duplicate of https://github.com/envoyproxy/envoy/issues/2053. Can we track there? At a high level I would like to see this land and I don't think it would be that difficult. The main thing will be to figure out what ABI guarantees we make, if any, and what symbols get exported from the main binary.
