### ISSUE TITLE
Compilation stalls when building Envoy in a container

### ISSUE THREAD

**Issue by InfoHunter** [envoyproxy/envoy#7309]
*Title*: Build progress stalls in the *envoyproxy/envoy-build-ubuntu* container.

*Description*:

I checked out the latest master and followed the instructions in `ci` directory - `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev` - to build envoy from source inside the ubuntu container. My host OS is a macOS 10.14.5 with docker desktop installed.

After triggering the above command the container is successfully launched but the compilation stalled at:

```
[2,182 / 2,334] 151 actions, 2 running
    Compiling source/extensions/filters/http/jwt_authn/extractor.cc; 22s local
    Compiling source/common/router/header_formatter.cc; 17s local
    [Analy] Compiling external/io_opencensus_cpp/opencensus/exporters/trace/stackdriver/internal/stackdriver_exporter.cc; 1828s
    [Analy] Compiling source/common/http/context_impl.cc; 1778s
    [Analy] Compiling source/extensions/tracers/common/ot/opentracing_driver_impl.cc; 1778s
    [Analy] Compiling source/common/router/header_parser.cc; 1778s
    [Analy] Compiling source/extensions/filters/http/buffer/buffer_filter.cc; 1778s
    [Analy] Compiling source/extensions/filters/http/lua/wrappers.cc; 1778s ...
``` 

If I send Ctrl-C on the terminal, it seems Bazel complained as:

```
^C
Session terminated, terminating shell...
Bazel caught interrupt signal; shutting down.


Could not interrupt server (Deadline Exceeded)
```
And if I use `docker stop [envoy-build-container-id]`, it doesn't work as well.

**Comment by snowp** [comment]
I suspect your docker VM doesn't have enough memory, causing compilation to grind to a halt. Maybe try increasing the resources given to the VM?

**Comment by InfoHunter** [comment]
Yes, you are right. After I increased the memory from 2GB to 8GB, the problem was gone. Thanks for the help!
