### ISSUE TITLE
buffer: Switch from the libevent impl of Envoy::Buffer to Brian Pane's implementation

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#7314]
The codebase has two alternate implementations of Envoy::Buffer. The legacy one is derived from libevent's buffer implementation, and has a ton of mileage on it, but also numerous known fuzzing issues.

A new one was created by @brian-pane which is off by default. There has been some fuzzing work done on it and it looks clean.

We should use this issue to collect experiences canarying the new buffer implementation, by adding command-line option:
```
   --use-libevent-buffers false
```

Potential canaryiers include: @moderation and @mattklein123 .

Once done we can (a) switch the default to use the new buffer implementation, and then later (b) drop the libevent implementation from the codebase, enabling some simplification.

**Comment by derekargueta** [comment]
I'm interested in canarying the new implementation at Pinterest

**Comment by jmarantz** [comment]
CC @htuch @asraa for any more detail available on fuzzing of the new buffers.

**Comment by mattklein123** [comment]
I will give this a smoke test at Lyft in the next few days.

**Comment by moderation** [comment]
I've been running the new buffer implementation in my home network and at work for a couple of weeks. The testing is pretty low volume and low complexity. No Lua, no hot restart etc. But we have tested http, h2, grpc, tcp, rate limiting, external auth etc. at work. No issues thus far.

**Comment by asraa** [comment]
The  buffer_fuzz_test uses the new buffer implementation, and there haven't been any issues reported so far. If there's some interesting cases or things to explore, I can add them in as corpus entries and/or extend the fuzz test.

**Comment by jmarantz** [comment]
per discussion on conf call; will flip default, make an announcement, and add a release note.

**Comment by SecurityInsanity** [comment]
Any update to making this the default? Would be nice to flip our cli flags from having to manually specify it as on.

**Comment by jmarantz** [comment]
Sorry about this; this slipped my mind; thanks for the reminder. Unfortunately I'm a bit overloaded right now so if you want to grab this, please do so!

**Comment by SecurityInsanity** [comment]
No worries! I’ll take a crack at it later today.
