### ISSUE TITLE
Error in listener callback in listener_impl.cc always leading to panic

### ISSUE THREAD

**Issue by siepkes** [envoyproxy/envoy#7316]
I ran into an interesting issue with Envoy crashing on SmartOS (Solaris). Sometimes Envoy would die with a panic when trying to accept a connection on a listener because `listener_impl.cc` -> `void ListenerImpl::errorCallback(evconnlistener*, void*)` always panics on any error. However the "error" was actually `EAGAIN`, not something worth panicking on I think. 

I "fixed" (more of a workaround) this behavior with a simple `if (errno != EAGAIN)`. Obviously since SmartOS / Solaris isn't officially supported I realize this is none of your problem however as far as I can tell other supported platforms might exhibit the same behavior under certain conditions since `EAGAIN` is a valid result to be returned. 

So for the sake of overall stability I was wondering if you guys would be open to a PR for this and if you  have any thoughts on this?

**Comment by mattklein123** [comment]
> So for the sake of overall stability I was wondering if you guys would be open to a PR for this and if you have any thoughts on this?

This sounds reasonable, though I would be curious to understand under what conditions EAGAIN can actually be returned. My understanding is this should be handled by the underlying event platform. If it looks like it actually can happen on Linux/BSD we should definitely look into fixing and adding a test.

**Comment by siepkes** [comment]
Great! I'll see if I can do some digging on this next week (I'm on the move the rest of the week) to figure out what can trigger EAGAIN and what makes sense when dealing with it.

**Comment by siepkes** [comment]
I did some digging in to the lower levels and it seems (from what I understand so far) that some backends implementations of libevent will never return `EAGAIN` and will handle it themselves. However some backends simply return `EAGAIN` as an error if it occurs. 

I've asked on the libevent maillinglist what the contract is (should I as a developer handle it or is it a bug in the backend implementation if it doesnt handle EAGAIN?).

**Comment by siepkes** [comment]
After some digging and conversing with one of the libevent authors it has become clear to me that as a libevent user I should never see the EAGAIN (should be handled in the `event_base` implementation). See the relevant part of my mailinglist conversation [mailinglist entry](https://archives.seul.org/libevent/users/Jun-2019/msg00005.html): 

> Also where did you get EAGAIN in the callback or an error callback? (actually you should not get it in any of them).

So this was a wrong interperation on my part; I thought getting an EGAIN as caller was valid and just didn't happen (often) on Linux.

@mattklein123 So while I have some work to do in troubleshooting the Solaris backend I don't think there is an issue here for Envoy here since this issue is actually something that needs to be solved with libevent. Closing this issue here. If you think there is something to do here for Envoy feel free to re-open.
