### ISSUE TITLE
Enable the OpenLab CI in Envoy

### ISSUE THREAD

**Issue by Yikun** [envoyproxy/envoy#7320]
The OpenLab CI configuration has been approved in https://github.com/envoyproxy/envoy/pull/6981 [1], there is only one step to enable the OpenLab CI in envoy project.

Here is the link to install the OpenLab APP [2]:
https://github.com/apps/theopenlab-ci

Note that the OpenLab CI github APP only require basic permissions to update check status and commit test result log URL in PR comments, you can see permission details in APP installation web page [2].

After installation, the OpenLab CI will be triggered in every PR. 

Note that, as the first version, the job has been marked as `non-voting` [3], that means the build job result is just a reference for developer and would not block the PR to be merged. Once we make sure the job can be executed stable, then we can mark it as normal `voting` job.

[1] https://github.com/envoyproxy/envoy/pull/6981
[2] https://github.com/apps/theopenlab-ci
[3] https://github.com/envoyproxy/envoy/blob/master/.zuul.yaml#L14

**Comment by mattklein123** [comment]
Hi @Yikun, optimally we would not need to setup an app for this. Can we potentially just setup a webhook?

**Comment by Yikun** [comment]
Hi, @mattklein123 , much thanks for your reply. The answer is **Yes** [1], but it's not a recommend way.

AFAIK, the Github app is a **simple way** to set a series webhooks and permisions configurations. I guess your mainly concern is the repo security?

Actually, the Openlab APP only requires minimize permissions, and all requested permission would be listed when you install the app, looks like:

![image](https://user-images.githubusercontent.com/1736354/59813064-bc6e9880-9342-11e9-9bcc-28b0b8e98c10.png)

There is **no access to code**, only requires some read permissions to trigger job, and write the commit status/pull request to set the CI result. 

Note that, If the app permissions is changed, the updated permissions won't take effect on an installation until the owner of the account or organization approves the changes [2].

So, we recommended us to use the Github app to set the webhooks and permissions, it is a safer and more convenient way.

[1] https://zuul-ci.org/docs/zuul/admin/drivers/github.html
[2] https://developer.github.com/apps/managing-github-apps/editing-a-github-app-s-permissions/

**Comment by mattklein123** [comment]
@Yikun it does require write access to status, PRs, etc. Can we just start with a web hook for now and if it becomes problematic we can revisit? If you let me know what webhook to install I can do that.

**Comment by Yikun** [comment]
@mattklein123 I have to sorry to say currently the Openlab only support the Github app way to enable the CI. As I mentioned before, the webhooks way will bring some maintenance problem in the Openlab. Could the team consider to use Github APP? : )

**Comment by lizan** [comment]
@mattklein123 IIUC the r/w access to commit statuses and pull requests means it will update the status of a commit (like Azure Pipeline does for its check), and comment on PRs. It won't be able to commit code etc so I guess it is fine, unless we have other solution for CI that support ARM.

**Comment by mattklein123** [comment]
@lizan I have no idea what OpenLab CI is (sorry @Yikun) so that is where the pushback is coming from. @lizan if you vouch for it no objection from me to add the app.

**Comment by Yikun** [comment]
@mattklein123 Never mind, I guess it was my misleading explanation that led to your misunderstanding. If the team still have some discussion need to be continued, you could feel free to comment, I'd like to do the deep explanation. : )

And looks like the periodic `envoy-build-arm64` [1] are still going on fine, so please go ahead and enable this [2] when appropriate.

[1] http://status.openlabtesting.org/builds?job_name=envoy-build-arm64
[2] https://github.com/apps/theopenlab-ci

**Comment by mattklein123** [comment]
I will just defer to @lizan to approve. If he says it is OK I will enable the app. :)

**Comment by lizan** [comment]
The app seems safe in term of GH permission given that it is also used in some projects in kubernetes org (https://github.com/kubernetes/cloud-provider-openstack), though I'm concerned about it's noisy comments after seeing PRs in that repo. @Yikun can you elaborate more on what the app will do based on the current configuration?

Also the current job doesn't run any tests but just produce binary, I'd like to see it runs full tests as well.

**Comment by Yikun** [comment]
> can you elaborate more on what the app will do based on the current configuration?

@lizan Sure. The OpenLab app will only trigger the `envoy-build-arm64` job in every PR(every update), and will give a result to show the build is passed or failed, just like the demo [1] shown. The job will be also triggered when user type the `recheck` or reopen the PR. And the OpenLab is also using in some other CNCF project like cloud-provider-openstack [2], containerd [3], you can also take a look.

> Also the current job doesn't run any tests but just produce binary, I'd like to see it runs full tests as well.

Yes, the current job only do the `envoy-build-arm64` to verify the envoy can compiled and build in aarch64, it's a first step.

We definitely can also continue to enable the more complex test cases after we enable the OpenLab APP, you could feel to tell me what's we really want to verify when every update commited. : )

[1] https://github.com/theopenlab/envoy/pull/3
[2] https://github.com/containerd/containerd/pull
[3] https://github.com/kubernetes/cloud-provider-openstack/pull

**Comment by Yikun** [comment]
@lizan As we talked F2F in KubeCon Shanghai, the team prefer to use a CI without any extra comments.

And I add a demo to show what the no comments check looks like, and it can be found in https://github.com/theopenlab/envoy/pull/6.

And what we need to change in Envoy is that, change the `check` to `check-no-comments` [1]. If we don not have other question, I will submit a PR. : )

[1] https://github.com/envoyproxy/envoy/blob/1dc5f64/.zuul.yaml#L3
