### ISSUE TITLE
Evaluate accesslog filters in Envoy rather than accesslog implementations

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#7325]
(Cleanup proposal.)

Currently, access log filters are manually evaluated in each implementation. Filters are instantiated and passed to the AccessLog::Instance, and then each AccessLog::Instance's `log()` implementation has logic of `if (filter_ && filter_.evaluate(...)) then log()`. Instead, I propose we move that logic up to some sort of public `bool evaluate_filter(...)` function in the AccessLog interface, and wrap all of Envoy's AccessLog::Instance::log() calls in a conditional.

cc: @ambuc @eziskind @AndresGuedez

**Comment by mattklein123** [comment]
+1 would love to see this happen, agreed the current situation is a lot of copied code.

**Comment by auni53** [comment]
Do you like my proposed design? Or is there a cleaner way to automatically call that evaluate_filter() automatically on Instance::log() calls.

As well, as far as I'm aware this change will have no performance benefits, but make the code better. Correct assessment?

**Comment by auni53** [comment]
Ah, revised question. This log() function offered by the AccessLog seems to be available to all filters. I had considered making this change slyly such that custom implementations of an AccessLog don't have to change anything, but on the other hand if I change the log() call that the HCM makes, should I worry about other consumers' filter implementations relying on calling an accesslog log()?

**Comment by mattklein123** [comment]
@auni53 I think it's probably fine to change the log interface if it makes it better. I would have to sit down and look at all the code in detail to page it back in to have a real opinion, but my general feeling is that there are a bunch of ways you can de-dup the code and I don't feel too strongly about any one method. Feel free to put up a PR and we can discuss if you like one way over the others.
