### ISSUE TITLE
Make Envoy::Grpc::AsyncClient mock friendly

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#7346]
After recent revamp of gRPC interfaces it became difficult to mock gRPC clients that use Envoy::Grpc::AsyncClient template. The problem is that interface is not virtual and now requires dependency injection to mock client objects.
Proposal is to make Envoy::Grpc::AsyncClint interface virtual, as there does not seem to be any downside to it.

**Comment by mattklein123** [comment]
@yanavlasov can you expand on the difficulty and what you are proposing? Here is an example of mocking:

https://github.com/envoyproxy/envoy/blob/2e03ef24060d479fb825d2d0257a1961f502f08d/test/extensions/filters/common/ratelimit/ratelimit_impl_test.cc#L67

I agree it used to be a bit simpler but it's not too bad now so trying to understand the proposal better. Thank you.

**Comment by yanavlasov** [comment]
The Grpc::AsyncClient does not have sendRaw method. This has recently changed. Here is the new class.
https://github.com/envoyproxy/envoy/blob/3c42cf460a2710bbe4dc43e72afc456f72411f04/source/common/grpc/typed_async_client.h#L94
