### ISSUE TITLE
question about http reverse proxy usecase

### ISSUE THREAD

**Issue by Arnold1** [envoyproxy/envoy#7353]
Hi,

i have a question is envoy able to mirror the traffic for the following usecase?
For each incoming request, it clones the request into 2 requests, forwards them to 2 servers. 
The results from server A are returned as usual, but the results from server B (qa_server) are ignored.

teeproxy handles GET, POST, and all other http methods.

cc: https://github.com/chrislusf/teeproxy

is thats already possible could you show me the configuration i need to set and how to run it?

**Comment by mattklein123** [comment]
Yes, see https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#route-routeaction-requestmirrorpolicy

**Comment by Arnold1** [comment]
hi any response? :)
