### ISSUE TITLE
tracers: Upgrade to lightstep-tracer-cpp 0.12.0

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#7363]
*tracer*: *Upgrade to lightstep-tracer-cpp 0.12.0*

*Description*:
Envoy currently uses lightstep-tracer-cpp 0.8.0. 0.12.0 was released on November 25 - [release notes](https://github.com/lightstep/lightstep-tracer-cpp/releases/tag/v0.12.0). Build structure of the project have changed and it is not possible to only bump the version download in `bazel/repository_locations.bzl` /cc @tedsuo @objectiser

**Comment by moderation** [comment]
0.10.1 released - https://github.com/lightstep/lightstep-tracer-cpp/releases/tag/v0.10.1

**Comment by moderation** [comment]
0.11.0 released - https://github.com/lightstep/lightstep-tracer-cpp/releases/tag/v0.11.0

**Comment by moderation** [comment]
0.12.0 released - https://github.com/lightstep/lightstep-tracer-cpp/releases/tag/v0.12.0. Updated title and text @tedsuo @objectiser

**Comment by andrewhsu** [comment]
Should this issue be closed now that #10152 is merged?

**Comment by moderation** [comment]
Closting. We are not using the 0.12.0 release unfortunately but a commit after that release. But good enough
