### ISSUE TITLE
Envoy broken on Bazel CI: "No module named httplib"

### ISSUE THREAD

**Issue by philwo** [envoyproxy/envoy#7379]
**Issue Template**

*Title*: Envoy is currently broken on Bazel's CI.

*Description*:

`//test/integration/hotrestart_test` fails with this error:

```
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/4773/execroot/envoy/bazel-out/k8-fastbuild/bin/test/integration/hotrestart_test.runfiles/envoy/tools/socket_passing.py", line 13, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```

Failing build: https://buildkite.com/bazel/envoy/builds/814#624cf49e-ade8-44a9-967e-a79a77cebe8f
Full log: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/624cf49e-ade8-44a9-967e-a79a77cebe8f/test/integration/hotrestart_test/attempt_1.log

**Comment by philwo** [comment]
FYI @meteorcloudy - current Bazel Green Team sheriff.

**Comment by meteorcloudy** [comment]
I think https://github.com/bazelbuild/bazel/issues/8626#issuecomment-504052013 is related.

**Comment by mattklein123** [comment]
cc @lizan @keith

**Comment by keith** [comment]
I've submitted a fix for this https://github.com/envoyproxy/envoy/pull/7382, I assumed all the failures were host tools and would be fixed by https://github.com/envoyproxy/envoy/pull/7337 but this one appears to not be. We also have some issues tracking moving these off python2 https://github.com/envoyproxy/envoy/issues/7342

**Comment by keith** [comment]
I _think_ I was able to easily update this script to python3 instead https://github.com/envoyproxy/envoy/pull/7386

**Comment by brandjon** [comment]
[This](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1049#cda4d35e-f4ea-40cc-9cc7-cbd25b261d06/44) buildkite run from a few days ago appears to be picking up envoy sources at commit [54e22406c38987d5b0401f18b614501bc184f41f](https://github.com/envoyproxy/envoy/commit/54e22406c38987d5b0401f18b614501bc184f41f), which is dated 10 days ago. Any idea why the downstream pipeline isn't up-to-date?

**Comment by meteorcloudy** [comment]
Because Envoy has been red since Bazel is upgraded to 0.27.0. 
https://buildkite.com/bazel/envoy/builds?page=17

We don't update the last green commit for a project if it's already red with the latest release.

**Comment by brandjon** [comment]
Thanks, looks like the `ModuleNotFoundError: No module named 'httplib'` error case is still live in the most recent build.

**Comment by meteorcloudy** [comment]
If envoy needs `httplib` to be installed, they can add the pip install command in the bazel ci config script. Like TensorFlow does: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/tensorflow-postsubmit.yml#L34
```
    - pip install -U --user pip six numpy wheel setuptools mock future
```

**Comment by keith** [comment]
This should be fixed by https://github.com/envoyproxy/envoy/pull/7391

**Comment by keith** [comment]
Envoy CI is now on 0.27.0, so I'm hoping we're good on the next bazel CI run now

**Comment by keith** [comment]
We're good now, and the other issue has been closed https://buildkite.com/bazel/envoy/builds/819 so we can close this one

**Comment by philwo** [comment]
Thanks, @keith! I'm closing this.
