### ISSUE TITLE
ext-auth and redirect

### ISSUE THREAD

**Issue by RocIngersol555** [envoyproxy/envoy#7380]
Hey Folks,

I’m trying to use the ext_authz filter. The behaviour I’m seeing – requests get routed to my ext-auth cluster, get auth’d but then return 403.

If I disable the ext-auth filter on my auth route I can ‘see’ my auth payload.

I guess my question is – how do I control what header values mean a request is auth’d or denied?

Thx!

**Comment by htuch** [comment]
@RocIngersol555 can you share your ext_auhz filter? That would probably make things a little easier to grok.

**Comment by RocIngersol555** [comment]
Thx. Here’s some addiotnal context and configs.

-	I’m currently running Envoy as a sidecar and it’s fronting a web app.
-	I have an OIDC identify provider and I want to pass web connections off to it for authentication (and then back to Envoy for routing etc).
-	I have a web app (listening on 9090) that will talk to my identity provider, authenticate the user and do a call back with the user token and claims.

If I watch the Envoy logs I see;
-	Connections are passed to ‘ext-authz’ and then to my auth provider.
-	The call back from my auth provider back to Envoy is then met with a 403..

My config is pretty much like the example one from the docs;

`static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8090
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: my_app

          http_filters:
          - name: envoy.ext_authz
            config:
              http_service:
                server_uri:
                  uri: 127.0.0.1:9090
                  cluster: ext-authz
                  timeout: 0.25s
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: my_app
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: my_app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 10902
  - name: ext-authz
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9090

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
`

**Comment by htuch** [comment]
Do you know what your auth provider is returning to Envoy?

**Comment by ides15** [comment]
@RocIngersol555 would you happen to remember what the issue here ended up being? I'm getting the same behavior with my extauth setup.
