### ISSUE TITLE
configurable default circuit breaking config

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#7381]
*configurable default circuit breaking config*

*Description*:
Contour allows circuit breaking fields such as max connections to be configured via annotations. If unset then the Envoy defaults are used. These defaults are much too low, and were one of the callouts at EnvoyCon with regard to sensible defaults in Envoy.

Providing a way to increase these for all IngressRoutes would be ideal. As operators of Contour we'd like to provide some more sensible defaults rather than go out to dozens of service teams and ask them to provide the annotations.

**Comment by mattklein123** [comment]
I think this is a Contour issue. Please file an issue there to allow the defaults to be changed.

**Comment by phylake** [comment]
Whoops I was on the wrong tab. Sorry about that!
