### ISSUE TITLE
Upgrading yapf breaks our build

### ISSUE THREAD

**Issue by cclauss** [envoyproxy/envoy#7389]
**Issue Template**

*Title*: *Upgrading __yapf__ in __tools/requirements.txt__ breaks the build.*

*Description*:

Most projects are moving quickly to [__python/black__](https://github.com/python/black) but we can stick with yapf if we want.  However, we have [__yapf==0.25.0__ hardcoded in __tools/requirements.txt__](https://github.com/envoyproxy/envoy/blob/master/tools/requirements.txt#L2) and when we upgrade to the [current version (0.27.0)](https://pypi.org/project/yapf), our build fails.
* https://github.com/google/yapf/blob/master/CHANGELOG

**Comment by htuch** [comment]
@cclauss we have no strong emotional attachment to `yapf`, if you want to switch to something else without too much churn, you're welcome to switch.
