### ISSUE TITLE
Cannot pass remote downstream port to upstream

### ISSUE THREAD

**Issue by mthebridge** [envoyproxy/envoy#7396]
I would like to be able to pass the original downstream remote IP + port to my service when using Envoy as an ingress HTTP proxy.  At the moment, I can get hold of the remote IP, either reading it from the `x-envoy-external-address` header, or adding my own custom HTTP header using the `%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%` specifier - but as far as I can tell there is no way to add an HTTP header that contains the downstream port.  I considered using the Lua filter, but that doesn't have any connection-level data available to it either.

Am I missing something?   Would there be value in adding `%DOWNSTREAM_REMOTE_ADDRESS%` to the custom header parameters, so that port information can also be passed through?

**Comment by htuch** [comment]
Are you after the source or destination port here? E.g. if a client X connects to Envoy Y on port 80 from some local ephemeral port 21345, which one do you want?

**Comment by mthebridge** [comment]
Hi there - yes, I'm after the source port.  So in your example, I'd like Envoy to forward on somehow the 21345 value.  (I believe that the `X-Forwarded-port` header would contain the destination port).

**Comment by htuch** [comment]
@mthebridge spelunking the history here, I think this is actually supported, just not documented. Access log and header formatters share a common path, and this is available in https://github.com/envoyproxy/envoy/blob/89d81e65df2a6b364bcf0af4c251241c2dd5866e/source/common/access_log/access_log_formatter.cc#L378. 

Want to give that a try? If it works, a PR to update docs would be awesome. Thanks!

**Comment by mthebridge** [comment]
@htuch Thanks for the suggestion - sadly, though, that does not work, returning the error:  
`field 'DOWNSTREAM_REMOTE_ADDRESS' not supported as custom header`.

From my reading of the code I think the format specifiers actually are not shared - the ones for HTTP header generation can be found at https://github.com/envoyproxy/envoy/blob/294d0d73665e6a3f329c54ed641ee1f45bd9fabf/source/common/router/header_formatter.cc#L195-L308, and have only a subset of those available for access logs.

**Comment by htuch** [comment]
@mthebridge ah, right; yes, I was thrown off by the fact that `header_formatter.cc` does call into access log formatter in some cases, e.g. `START_TIME`, and probably wishful thinking here.

Can you just copy+paste the access log formatter into header formatter?

Beyond this, I think we should have much more convergence of the code for access log and header format, at least a large subset can be shared and we shouldn't need to be copying code to achieve this. CC @mattklein123 @dio

**Comment by mattklein123** [comment]
> Beyond this, I think we should have much more convergence of the code for access log and header format, at least a large subset can be shared and we shouldn't need to be copying code to achieve this. CC @mattklein123 @dio

+1 this has come up several times. cc @zuercher also.

**Comment by mthebridge** [comment]
It's a bit of a pain to "just copy+paste", because at the moment I'm using the envoy binaries directly and was trying to avoid the need to fork and re-compile.  If I can get the time I might look at sending a PR, but no promises.

**Comment by jaricftw** [comment]
Can we re-open the issue? Looks like a short-term fix is just to expose `DOWNSTREAM_REMOTE_ADDRESS` for header customization.
