### ISSUE TITLE
Finish implementation of TLS Session Ticket keys delivery via SDS

### ISSUE THREAD

**Issue by mk23** [envoyproxy/envoy#7397]
Currently TLS Session Tickets can only be configured as `DataSource` which limits them to inline string/bytes or individual files.  This type of setup requires a restart of envoy to rotate the keys.  The API already has a provision to pull them from SDS, albeit currently stubbed out.  Further, trying to configure SDS for tickets throws an explicit "SDS not supported" error.

Please consider fully implementing SDS for TLS session ticket keys.

api stub: https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/auth/cert.proto#L357-L358
exception: https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/context_config_impl.cc#L351-L353

**Comment by euroelessar** [comment]
I've started working on the change, please assign it to me.

**Comment by JimmyCYJ** [comment]
cc @JimmyCYJ
