### ISSUE TITLE
How can I compile the external_auth.proto and develope my own gRPC external auth service?

### ISSUE THREAD

**Issue by yzq789** [envoyproxy/envoy#7400]
Hi, I am trying to develop an external auth service here, and I need to decide whether a request should be allowed or not by the token in the request body.  So I have to use a gRPC auth service because Content-length will be set to 0 with a http auth service: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2-authorizationrequest.
So, I need to compile this proto file into java code first, right? (https://github.com/envoyproxy/envoy/blob/1faaed85740a97533484db3232796aef7973677f/api/envoy/service/auth/v2/external_auth.proto#L30)

But this proto file imports two other proto files which are not in the repo of envoy:
import "google/rpc/status.proto";
import "validate/validate.proto";

Where can I get these proto files?

**Comment by dio** [comment]
https://github.com/envoyproxy/protoc-gen-validate/blob/master/validate/validate.proto

https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto

**Comment by splix** [comment]
@yzq789 btw, it's not necessary to compile it by yourself. You can use already compiled stubs as a dependency https://mvnrepository.com/artifact/io.envoyproxy.controlplane/api

**Comment by yzq789** [comment]
It works. Compiled stubs are so convenient, thank you !
