### ISSUE TITLE
xDS protocol: multiple Discovery request/response clarification

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#7401]
*Title*: *xDS protocol: multiple Discovery request/response clarification*

The [xDS protocol docs](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol) state

> A management server does not need to send an update until it determines a new version is available. Earlier requests at a version then also become stale. It may process multiple DiscoveryRequests at a version until a new version is ready.

Before that ☝️ is the following:

> Envoy replies to any DiscoveryResponse with a DiscoveryRequest containing the ACK/NACK immediately after it has been either accepted or rejected. If the management server provides the same set of resources rather than waiting for a change to occur, it will cause Envoy and the management server to spin and have a severe performance impact.

If the management server chooses to "process multiple DiscoveryRequests at a version until a new version is ready" it will also "cause Envoy and the management server to spin and have a severe performance impact", correct? The clarification needed is whether or not "process" indicates replying with a DiscoveryResponse. The diagram indicates "no" but the language could be more precise.

Also, it seems that there will always be a DiscoveryRequest queued (the ACK/NACK) for the management server to receive but it's unclear if or why there might be additional DiscoveryRequests (from the same Envoy) sent for a given `type_url` or `(type_url, resource_name)`. I see it's designed as a queue but I don't see how the queue could ever have more than one DiscoveryRequest in it.

**Comment by htuch** [comment]
Every `DiscoveryResponse` will cause Envoy to do work, so, yeah, if you keep sending these, it will spin. Envoy won't send more than one `DiscoveryRequest` for every `DiscoveryResponse` (at least in state-of-the-world xDS, it will be somewhat different in incremental xDS in the future). PRs to improve wording are welcome.

**Comment by phylake** [comment]
Thanks @htuch. Happy to open a PR for wording since you took the time to answer. While I have your attention would you mind answering #5368? I've been bumping it for awhile now
