### ISSUE TITLE
Envoy Proxy Issue 

### ISSUE THREAD

**Issue by shwetaap** [envoyproxy/envoy#7402]
**Envoy Proxy Issue**

*Envoy Proxy Issue*

*Description*:
>I am trying to deploy envoy as a front proxy for tls termination and http-https redirection, in my kubernetes setup. Every external request is then frowarded to a backend service. Here are my envoy pods and the backend service pod(parp-82-594747ff67-z456h).
[root@kaas-adm-idev-rtp-master-0 ~]# kubectl get pods -n envoylayer
NAME                                READY   STATUS    RESTARTS   AGE
envoy-deployment-68b9474d48-dskrs   1/1     Running   0          22h
envoy-deployment-68b9474d48-jqdmz   1/1     Running   0          22h
envoy-deployment-68b9474d48-l9ml5   1/1     Running   0          22h
parp-82-594747ff67-z456h            1/1     Running   0          6d18h

The services are 
[root@kaas-adm-idev-rtp-master-0 ~]# kubectl get svc -n envoylayer
NAME                  TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)                      AGE
envoy-admin-service   NodePort       10.96.20.49   <none>         80:30684/TCP                 22h
envoy-service         LoadBalancer   10.96.14.1    10.226.194.3   80:32607/TCP,443:30820/TCP   22h
parp-82-service       ClusterIP      10.96.43.70   <none>         81/TCP

when i try to curl the Cluster Ip of the envoy-service. I dont see the request go to the backend service(parp-82-service) I see a 503 error instead.

[root@kaas-adm-idev-rtp-master-0 ~]# curl -kv https://10.96.14.1
* About to connect() to 10.96.14.1 port 443 (#0)
*   Trying 10.96.14.1...
* Connected to 10.96.14.1 (10.96.14.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:

> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.96.14.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Wed, 26 Jun 2019 14:48:56 GMT
< server: envoy
<
* Connection #0 to host 10.96.14.1 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination

My envoy.yaml has the following configuration 
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  path_redirect: "/"
                  https_redirect: true
          http_filters:
          - name: envoy.router
            config: {}
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: ping-service
          http_filters:
          - name: envoy.router
            config: {}
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/example-com.crt"
              private_key:
                filename: "/etc/example-com.key"
  clusters:
  - name: ping-service
    connect_timeout: 3.00s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ping-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: parp-82-service.envoylayer
                port_value: 81
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

Also when i check the logs on the envoy pod,I see this
[2019-06-25 16:29:56.842][8][info][upstream] [source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized
[2019-06-25 16:29:56.842][8][info][main] [source/server/server.cc:462] all clusters initialized. initializing init manager
[2019-06-25 16:29:56.842][8][info][config] [source/server/listener_manager_impl.cc:1006] all dependencies initialized. starting workers
[2019-06-25 16:42:52.880][18][info][client] [source/common/http/codec_client.cc:118] [C6] protocol error: The user callback function failed
[2019-06-25 16:44:56.842][8][info][main] [source/server/drain_manager_impl.cc:63] shutting down parent after drain
[2019-06-25 18:56:35.493][14][info][client] [source/common/http/codec_client.cc:118] [C24] protocol error: The user callback function failed
[2019-06-25 20:29:52.818][16][info][client] [source/common/http/codec_client.cc:118] [C28] protocol error: The user callback function failed

If I login into one of the nvoy pods and try to curl to the backend service using the dns of the service, it works.

root@envoy-deployment-68b9474d48-dskrs:/# curl -kv http://parp-82-service.envoylayer:81
* Rebuilt URL to: http://parp-82-service.envoylayer:81/
*   Trying 10.96.43.70...
* Connected to parp-82-service.envoylayer (10.96.43.70) port 81 (#0)
> GET / HTTP/1.1
> Host: parp-82-service.envoylayer:81
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Wed, 26 Jun 2019 14:55:07 GMT
< Server: Apache/2.4.27 (Red Hat) OpenSSL/1.0.2k-fips
< content-length: 2500
< content-type: text/html;charset=UTF-8
< cache-control: private,no-cache,no-store,max-age=0
< X-Frame-Options: DENY
<
<!DOCTYPE html>

Could you please send me some pointers on how to debug further! Thanks!

**Comment by shwetaap** [comment]
It works once i remove the 'http2_protocol_options: {}' option. When i tried to send curl with the options --http1.1 or --http2. Neither worked. So not sure why removing the 'http2_protocol_options: {}' from the config worked.

**Comment by htuch** [comment]
@shwetaap `http2_protocol_options` applied on the outbound connection to the upstream, which might not have had H2 support (in particular for plaintext H2).

**Comment by shwetaap** [comment]
@htuch - I see. Thanks!
