### ISSUE TITLE
How to read input http body bytes using gRPC-JSON Transcoder?

### ISSUE THREAD

**Issue by mahesh0723** [envoyproxy/envoy#7411]
*Title*: *How to read input http body bytes using gRPC-JSON Transcoder?*

*Description*:
We have exposed our gRPC APIs as JSON using gRPC-JSON Transcoder of Envoy and it works like a charm. 

We are looking forward to integrating the third party application which supports webhook for integration. Apparently, the third-party application sends data as 'form-data' and not like a JSON. 

You can find sample details
![Screenshot 2019-06-27 at 12 18 58 PM](https://user-images.githubusercontent.com/18420449/60243431-d75a8300-98d5-11e9-8d27-f37c64626bd4.png)

How should we configure proto annotations such that it can convert incoming HTTP request body bytes to proto message bytes attribute?

Is it possible to achieve the same using gRPC-JSON Transcoder?

**Comment by htuch** [comment]
@mahesh0723 not quite sure what is meant by proto annotations here, can you provide more context?

**Comment by musaprg** [comment]
gRPC-JSON Trancoder supports requests with only JSON format, not multipart/form-data.

According to docs below, bytes seem to be interpreted as a base64 string. If you want to send bytes data, you must convert it base64 and send with JSON format.

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by musaprg** [comment]
see also: https://github.com/envoyproxy/envoy/issues/7007

**Comment by jroper** [comment]
We just had a use case for this ourselves. I think it would be great if supported was added for passing the body as bytes. Perhaps something like this:

```protobuf
  rpc ReceiveData(ReceiveDataRequest) returns (Empty) {
    option (google.api.http) = {
      post: "/some/path"
      body_bytes: "data"
    };
  }
...
message ReceiveDataRequest {
  bytes data = 1;
}
```

The `body_bytes` option would tell the transcoder not to decode the body as json, but rather, pass the body bytes as the data field. If the `data` field was not `bytes`, this would be flagged as an error, and if both `body_bytes` and `body` options were specified, this would also be flagged as an error.

**Comment by Gurpartap** [comment]
based on https://github.com/envoyproxy/envoy/pull/10110, this works:

```proto
service ServiceX {
  rpc ReceiveData (ReceiveDataRequest) returns (Empty) {
    option (google.api.http) = {
      post: "/some/path/{id}"
      body: "raw_body"
    };
  }
...
message ReceiveDataRequest {
  string id = 1;
  google.api.HttpBody raw_body = 2;
}
```

```go
// read bytes
body := req.GetRawBody().GetData()
```
