### ISSUE TITLE
document idletimeout clearly

### ISSUE THREAD

**Issue by hzxuzhonghu** [envoyproxy/envoy#7420]
As for me, when i looked the idletimeout at http connection manager 、route and also at cluster level。 There is a comment saying route level idletimeout will override http connection manager level.  But what is the relation between cluster level and http connection manager level idletimeout .

**Comment by htuch** [comment]
Agreed it might be good to be clearer here. Something along the lines of https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management.html?highlight=timeout#timeouts would be good.

**Comment by mattklein123** [comment]
+1 we have lots of different idle/stream timeouts and it would be good to do an overview of them and/or also have a FAQ.

**Comment by kopper** [comment]
We'd appreciate clarification on how these stream-level timeouts affect HTTP 1 requests and connections.
