### ISSUE TITLE
RepoKitteh-based selective CODEOWNERS enforcement on select subtrees

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#7423]
As part of the stable API versioning initiative in https://github.com/envoyproxy/envoy/issues/6271, we need to be able to ensure that @envoyproxy/udpa-wg has visibility on API changes and that @envoyproxy/api-shepherds sign-off on any API changes in the `api/` subtree.

While we make use of CODEOWNERS in GitHub to allow more permissive management of extensions and the like, this mechanism is too coarse grained, since when we enabled mandatory CODEOWNERS sign-off along with https://github.com/envoyproxy/envoy/commit/b9a1b6e3022be7147ced572d38af7f4173177e31#diff-5daf978e60e03b3975b485d5f1b449dc, this resulted in all aspects of the Envoy tree requiring CODEOWNERS sign-off.

I think RepoKitteh could be a solution here. We would want the following behavior on `api/`
1. When a PR contains changes to `api/`, @envoyproxy/api-shepherds are notified via a CC comment.
2. When a PR contains changes to `api/udpa`, @envoyproxy/udpa-wg  is notified via a CC comment.
3. An additional GitHub check blocking merge is added that will only be marked as passing once an approval review is received from someone in @envoyproxy/api-shepherds.

I think 1/2 can turned into a general notification mechanism. We could implement them independent of 3, which could also be a mechanism useful elsewhere in the code base.

@itayd WDYT? CC @mattklein123 @caniszczyk for CNCF visibility.

**Comment by itayd** [comment]
makes sense. let me figure out the timing.

**Comment by htuch** [comment]
@alyssawilk I think this will also be useful for date plane change monitoring and review enforcement.

**Comment by itayd** [comment]
description makes sense, i'm working on it.

**Comment by htuch** [comment]
@itayd FWIW, if we can have the ability to extend this facility to other GitHub teams and paths, e.g. to monitor changes to `source/common/http` and require dataplane owners to provide reviews, that will be even better. But, I think if we can start with the concrete implementation mentioned in this issue, this is a good start, and we can iterate. Thanks for making this happen!

**Comment by itayd** [comment]
@htuch i see no other way than making it generic :) it's not much work, it's just configuration. i got it almost ready btw, will prolly finish it tomorrow.

**Comment by itayd** [comment]
@htuch is it ok if i label such prs with the team they mention? otherwise figuring out double-mentions on consecutive commits can be troublesome.

**Comment by itayd** [comment]
@htuch sans ^, things are ready. I just need to test a bit more. For that it'd be super useful if you could create a testers team in envoy that includes me. thanks.

**Comment by itayd** [comment]
@htuch fyi https://github.com/envoyproxy/envoy/pull/7627

**Comment by itayd** [comment]
@htuch ready! demo for you: https://github.com/envoyproxy/envoy/pull/7659

lmk if looks ok, then i'll make a proper pr to integrate into the repo.

**Comment by htuch** [comment]
@itayd looks great, this is exactly what we were after here I think. Can I confirm that the "must approve" checks are dynamic and shrink/grow/disappear based on PR and path?

**Comment by lizan** [comment]
@itayd I feel the comment is a little bit noisy, can we do following?

- exclude Draft PRs until it is made ready for review
- do not add comment on every commit, but just for the commit contains a change in the subtree

**Comment by mattklein123** [comment]
@lizan FYI I already mentioned to @itayd the noise issue. Hopefully he will fix soon. The draft PR suggestion is a great idea also.

**Comment by itayd** [comment]
Sorry for not engaging earlier. I'm still in Israel, back monday.
