### ISSUE TITLE
EDS: Can load_balancing_weight max limit be removed?

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#7425]
*Description*:
We're in process of deploying Envoy and we've noticed the presence of max limit for zone/endpoint weight.
We have a need to send only a small fraction of traffic (≈0.0001) to some zones.
Examples are: validating that some zone is dead/alive, or checking if passive zone doesn't drop traffic on the floor for failover-like scenarios.

Based on the prior discussions (https://github.com/envoyproxy/envoy/issues/1285) it looks like this limit is not useful anymore for WRR/Least Loaded load balancing policies.
If there are no other concerns, can it be just removed? 

*Relevant Links*:
* https://github.com/envoyproxy/envoy/issues/1285
* https://github.com/envoyproxy/envoy/blob/9b096c31d36ee908888c071d2073d126693dc3c0/api/envoy/api/v2/endpoint/endpoint.proto#L85-L92
* https://github.com/envoyproxy/envoy/blob/9b096c31d36ee908888c071d2073d126693dc3c0/api/envoy/api/v2/endpoint/endpoint.proto#L117-L123

**Comment by mattklein123** [comment]
Yes I think the restriction can be removed at this point. cc @htuch @mergeconflict for confirmation.
