### ISSUE TITLE
Trying to add linkopts, Bazel getting in the way...

### ISSUE THREAD

**Issue by canselcik** [envoyproxy/envoy#7441]
Looks like similar opinions were raised before about Bazel but I am also in the opinion that it is overall a hard ecosystem to navigate.

So much so that I am unable to have my project (derived from the `filter-example`) link with an additional system library.

For simplicity, let's say it is `curl`. I simply want to link with `libcurl.so`. I don't need to build curl from source (although I tried that and failed to do that with Bazel and there aren't many examples except for `tensorflow` and `googlecartographer/async_grpc` projects), I have it installed on my system.

I am trying to simply add a `-lcurl` to the `linkopts` but since `envoy_cc_binary` wraps the `cc_binary`, I am unable to specify `linkopts`.

Any help is appreciated. I feel like this should be rather simple but Bazel is getting in the way. :)

**Comment by mattklein123** [comment]
Presumably since you are trying to link against a system library, you have private code. You can define your own binary target like so and pass whatever linkops you want. E.g.,

```
envoy_cc_binary(
    name = "envoy",
    repository = "@envoy",
    stamped = True,
    deps = LYFT_CUSTOM_FILTER_CONFIGS + [
        "@envoy//source/exe:envoy_main_entry_lib",
    ],
)
```

**Comment by canselcik** [comment]
Thanks @mattklein123, that was actually the first thing I had tried but that had resulted in an obscure Bazel error so I had figured the `envoy_cc_binary` wrapper didn't accept a list of `linkopts`. Turns out it was something else. Perhaps my `bazel clean --expunge` from earlier addressed something.

Thanks for the quick response.
