### ISSUE TITLE
network: UdpListener stops abruptly 

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#7465]
ConnectionHandlerImpl::stopListeners() destroy the listener instance immediately to stop listening. This works for TcpListener which only listens for new connections, and existing connections have their own sockets registered in scheduler. But UdpListener has only one socket for all the I/O. If the UdpListener was destroyed, the existing UDP traffic will just stop. It is fine if the UDP traffic is connection-less. But if it's connection oriented, all the existing connections have no way to continue. This behavior is different from the intention of stopListeners(). 

We need to refactor ConnectionHandler and UdpListener to support draining feature. A rough idea is to add an interface ActiveListenerBase::stopListening() with a callback which actually destroy the listener. And stopListening() should
1. For ActiveTcpListener, call the callback immediately.
2. For UdpListenerCallback, tell ListenerFilter to stop listening according the the filters own definition, and call the callback when the filter thinks it finishes draining.

**Comment by danzh2010** [comment]
Same issue also exists in UdpListener::disable/enable()

**Comment by mattklein123** [comment]
@danzh2010 quick comment that it would be optimal to integrate this with the existing drain manager interface/system. I would have a look at that. I can also help a bit with design once we are ready to implement.

**Comment by danzh2010** [comment]
In light of SO_REUSEPORT, even if UDP listeners are destroyed after draining, their sockets shouldn't be closed till all the listeners are drained.

**Comment by danzh2010** [comment]
Actually to simplify the logic, we only need to close all exiting QUIC connection before destroying the UdpListener. It's not necessary to wait for existing requests to be finished. So as long as we make sure a ConnectioClose frame is sent before calling ActiveQuicListener::destroy(), we are good.

Because of SO_REUSEPORT, each UdpListener has their own listening socket. Destroying UdpListener might close the socket. To avoid closing socket in SO_REUSEPORT socket group, ListenSocketFactory should hold a shared_ptr of the socket returned by getListenSocket(), and this socket should be closed when all the ActiveQuicListener's in different workers have destroyed their UdpListener instances.
