### ISSUE TITLE
Does any filter need addListenSocketOption[s]?

### ISSUE THREAD

**Issue by silentdai** [envoyproxy/envoy#7467]
ListenerFactoryContext::addListenSocketOption[s] is [here](
https://github.com/envoyproxy/envoy/blob/master/include/envoy/server/filter_config.h#L174-L181)

I search this repo and no filter is using it. ListenerImpl itself implements `addListenSocketOption` but it doesn't mean this function should be exposed to `ListenerFactoryContext`

If no known use cases we should keep the code base simple by removing this function from `ListenerFactoryContext`. It brings trouble when I further split the filterchainmanager from listener.

**Comment by mattklein123** [comment]
I think this is being used by filters external to the tree.

**Comment by silentdai** [comment]
At the following steps of filter chain discovery service which allows filter chain update without recreate the listener, it's critical to know that if the listener modular filter chain is remaining the same.

One example: if a newly added filter chain need to change the ListenSocketOption, the listener need to created. 
Previously a listener is always created so the `addListenSocketOption` as `ListenerFactoryContext` is fine.

@mattklein123  Could you share some light? Can we move the addListenSocketOption out of ListenerFactoryContext, or, add a function, something like is-current-listen-socket-options works for this filter/filterchain?

**Comment by mattklein123** [comment]
@silentdai fundamentally, I think `addListenSocketOptions` should only be allowed to be called by listener filters, and not network filters, otherwise I don't think it makes any sense. So we might have to look at a change there? I can't imagine this is being used outside of listener filters. Can you look at who added this originally and ask them? I'm guessing @jrajahalme or @klarose?

**Comment by silentdai** [comment]
> addListenSocketOptions should only be allowed to be called by listener filters, and not network filters

Agree!

> Can you look at who added this originally and ask them?

Will look into the git history. Thanks!

**Comment by klarose** [comment]
Looks like it came in before I started working on the src transparency stuff: https://github.com/envoyproxy/envoy/commit/725457cbeca5e49563da3787b424d2f564ec7e9e.

**Comment by silentdai** [comment]
@klarose Yes `addListenSocketOption` was not introduced earlier. However, in https://github.com/envoyproxy/envoy/commit/725457cbeca5e49563da3787b424d2f564ec7e9e 
1. `ListenerFactoryContext` doesn't need `addListenSocketOptions`, it is the `Listener` who need it. `Listener` should implement this function but not because of `ListenerFactoryContext`
2. What I am trying to achieve is that NetworkFilterChains should not use `addListenSocketOptions`. Hopefully ListenerFilters should not use either but it is NBD
3. The feature in 725457cbeca5e49563da3787b424d2f564ec7e9e is gone. Probably moved to a different place.

So @klarose what is the `src transparency stuff` you are mentioning? Is it in this repo or somewhere else?

**Comment by klarose** [comment]
@silentdai It's in tree. It has two filters: one listener filter, and one http filter. The listener filter adds options, but to the connection socket, not the listener socket: https://github.com/envoyproxy/envoy/blob/ba0b5a760acc0a445df47e7cc8bdbae47312776b/source/extensions/filters/listener/original_src/original_src.cc#L32

**Comment by silentdai** [comment]
We should be good. This `addOptions` doesn't belong to class/interface `ListenerFactoryContext`. Happen to be the same name. 

I will create a PR and CC all of you and let you confirm.
