### ISSUE TITLE
Hot restart lead to the abnormal exit of the new process

### ISSUE THREAD

**Issue by zyfjeff** [envoyproxy/envoy#7468]
*Title*: *Hot restart lead to the abnormal exit of the new process*

*Description*:

During the hot restart, the new Envoy process will start a timer to send `sendParentTerminateRequest` messages after taking over the traffic. but if the parent process quits early, can lead to ` sendParentTerminateRequest ` trigger RELEASE_ASSERT send failure, this kind of behavior is unacceptable, because the new process has already started to take over the traffic.

```
void DrainManagerImpl::startParentShutdownSequence() {
  ASSERT(!parent_shutdown_timer_);
  parent_shutdown_timer_ = server_.dispatcher().createTimer([this]() -> void {
    // Shut down the parent now. It should have already been draining.
    ENVOY_LOG(info, "shutting down parent after drain");
    server_.hotRestart().sendParentTerminateRequest();
  });

  parent_shutdown_timer_->enableTimer(std::chrono::duration_cast<std::chrono::milliseconds>(
      server_.options().parentShutdownTime()));
}

void HotRestartingChild::sendParentTerminateRequest() {
  if (restart_epoch_ == 0 || parent_terminated_) {
    return;
  }
  HotRestartMessage wrapped_request;
  wrapped_request.mutable_request()->mutable_terminate();
  sendHotRestartMessage(parent_address_, wrapped_request);
  parent_terminated_ = true;
  // Once setting parent_terminated_ == true, we can send no more hot restart RPCs, and therefore
  // receive no more responses, including stats. So, now safe to forget our stat transferral state.
  //
  // This destruction is actually important far beyond memory efficiency. The scope-based temporary
  // counter logic relies on the StatMerger getting destroyed once hot restart's stat merging is
  // all done. (See stat_merger.h for details).
  stat_merger_.reset();
}

void HotRestartingBase::sendHotRestartMessage(sockaddr_un& address,
                                              const HotRestartMessage& proto) {
......
    const int rc = sendmsg(my_domain_socket_, &message, 0);
    RELEASE_ASSERT(rc == static_cast<int>(cur_chunk_size),
                   fmt::format("hot restart sendmsg() failed: returned {}, errno {}", rc, errno));
  }
  RELEASE_ASSERT(fcntl(my_domain_socket_, F_SETFL, O_NONBLOCK) != -1,
                 fmt::format("Set domain socket nonblocking failed, errno = {}", errno));
}
```

I think need to refactor ` sendHotRestartMessage `, send the results of the return, can be treated with the result of sending calls, rather than a unified RELEASE_ASSERT to deal with.

**Comment by mattklein123** [comment]
This should never happen, the parent process should never terminate early. The hot restart code is written to assume that any deviation from the normal process puts things into an inconsistent state and everything should come up from scratch. Why is the parent process terminating?

**Comment by zyfjeff** [comment]
@mattklein123 parent process may be prematurely quit due to bugs, or be killed by mistake, but in any case, the child process has taken over traffic, can work normally, and should not quit.

**Comment by mattklein123** [comment]
IMO it's not worth it to add the extra complexity of potentially inconsistent state between parent and child. I would recommend fixing whatever bug is causing the parent to shutdown early. We have run hot restart like this at Lyft for many years without any issues with inconsistent state.

**Comment by SunBK201** [comment]
@zyfjeff  We also encountered this problem. How did you solve it? Thank you！
