### ISSUE TITLE
Coverage build no longer covers headers

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7474]
@htuch I know you mentioned this but do you know when this regressed? cc @lizan. It would be great to get this fixed next week.

**Comment by htuch** [comment]
The breaking change is https://github.com/envoyproxy/envoy/pull/6866, i.e. the Bazel 0.26 update. Presumably this has to do with how headers are treated in `bazel-out`. You can see in earlier coverage runs paths such as `coverage.bazel-out_k8-dbg_bin_include_envoy_access_log__virtual_includes_access_log_interface_envoy_access_log_access_log.h.html` (https://circleci.com/gh/envoyproxy/envoy/227465#artifacts/containers/0). Will dig into this more today.

**Comment by htuch** [comment]
So, it looks like the headers are actually mapped where they were before:

```
envoybuild@db6158d4afec:/build/tmp/_bazel_bazel/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy$ find -L . -name access_log.h
./include/envoy/access_log/access_log.h
./bazel-out/k8-dbg/bin/include/envoy/access_log/_virtual_includes/access_log_interface/envoy/access_log/access_log.h
```

It seems the exclusion that was added in https://github.com/envoyproxy/envoy/pull/6866/files#diff-9cdd51e93f8baceb29ebff17ff73e194 is the issue, as it excludes all headers. @lizan do you know why this change was necessary?
