### ISSUE TITLE
Force trace from outside

### ISSUE THREAD

**Issue by aclowkey** [envoyproxy/envoy#7484]
I noticed that `x-envoy-force-trace` can only be used for internal requests.
How can I initiate the request from outside?

I'm using GCP as a load balancer, maybe propagate `X-Cloud-Trace-Context`?

**Comment by alyssawilk** [comment]
When you ask how you can initiate a request from the outside, you mean how can you force a trace from the outside?  

If you're on GCP, I believe XFF should be set to the originating IP, so if you request is issued from a trusted IP and you have the trusted hops set up correctly it should "just work".  The XFF docs may help you with setting that up cleanly: https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for

**Comment by aclowkey** [comment]
Yes, I want my clients to be able to force traces from outside.
I managed to get to do this using `x-client-trace-id`, but then the clients have to generate it. I would prefer something similar to `x-envoy-force-trace: true`, and have envoy generate all necessary ids

I tried getting it to work outside of GCP with no success so far. 
I have a simple set up of envoy to httpbin, all in docker. I've set `xff_num_trusted_hops: 2`, but I'm still not getting the trace to start when I specify `x-envoy-force-trace: true`

**Comment by alyssawilk** [comment]
And also to sanity check, you do have your config so those addresses you're sending trace headers from are in the InternalAddressConfig?

It looks like there's not a lot of logging around final remote address.  If you're running from head, and could spin up an instance with trace logging, I wouldn't mind adding some trace logging around that area of the code - I think it'd be generically useful for debugging problems of this type.

**Comment by zhongfox** [comment]
@aclowkey any lucky? I'm trying to find the same solution...

**Comment by aclowkey** [comment]
I got it to work by sending the header
`x-client-trace-id: 0`

**Comment by jdomag** [comment]
@aclowkey @alyssawilk 
I use envoy via Istio and I'm just curious - which component or logic in envoy remove or doesn't honor "x-envoy-force-trace" header? My first though was that it makes sense to protect the system so nobody from outside don't flood envoy/istio mesh with "x-envoy-force-trace" - but if the workaround is to use  `x-client-trace-id: 0`  then it doesn't make any sense to me

**Comment by alyssawilk** [comment]
I'm not sure offhand, sorry.  If you've got cycles to dig into the code that would be fantastic!

**Comment by matthewgrossman** [comment]
Looking into how this worked myself, and it seems that `x-envoy-force-trace` is one of many headers sanitized here:

https://github.com/envoyproxy/envoy/blob/2c367ef48b3cc99df6298b6fc04bc0f14d2491b1/source/common/http/conn_manager_utility.cc#L292

I don't see `x-client-trace-id` as one of the headers removed there, and it's used later on as a way to force the trace-reason to true:

https://github.com/envoyproxy/envoy/blob/2c367ef48b3cc99df6298b6fc04bc0f14d2491b1/source/common/http/conn_manager_utility.cc#L337-L338

There might be other places where these headers take effect, but that's where I spotted them

**Comment by NaurisSadovskis** [comment]
Hi folks, we're trying to solve a similar problem. Our Envoy is fronted by GLB which generates an `x-cloud-trace-context` which we're trying to use to convert/override existing `traceparent` via Envoy's Lua HTTP filter. This does not seem to be possible, presumably because traceparent is generated earlier and is immutable within the request flow. Any ideas if this can be forced via other methods?
