### ISSUE TITLE
tools: compilation database generation fails

### ISSUE THREAD

**Issue by cyxddgithub** [envoyproxy/envoy#7486]
Title: tools/gen_compilation_database.py fails. (not same as [#6172](https://github.com/envoyproxy/envoy/issues/6172))

Description:
i try to gen compilation database for vscode in mac
bazel version 0.22.0 
envoy tag 1.10.0

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Repro steps:
>$ tools/gen_compilation_database.

get the error:
ERROR: Analysis of aspect '//bazel-compilation-database-0.3.2:aspects.bzl%compilation_database_aspect of //api/envoy/admin/v2alpha:clusters_cc' failed; build aborted: no such package 'envoy/type': BUILD file not found on package path

**Comment by alyssawilk** [comment]
Hm, works locally for me so without digging I'd suspect a platform-specific problem - we've had VSCode breaks before as you've noted.  Just as a sanity check you are running with --vscode as required by @ipuustin 's fix?

**Comment by moderation** [comment]
@cyxddgithub Bazel 0.22.0 is quite old and predates Envoy 1.10.0 which was released on April 5 (which fell between the release dates of Bazel 0.24.1 and 0.25.0). It may be too old for the version of bazel-compilation-database included I would try using the latest Bazel 0.27.1.

**Comment by cyxddgithub** [comment]
> Hm, works locally for me so without digging I'd suspect a platform-specific problem - we've had VSCode breaks before as you've noted. Just as a sanity check you are running with --vscode as required by @ipuustin 's fix?

tks for reply and i try with --vscode still not work error like this:
ERROR: Analysis of target '//api/envoy/admin/v2alpha:clusters_cc' failed; build aborted: no such package 'envoy/type': BUILD file not found on package path
ps:how can i debug the error's reason

**Comment by cyxddgithub** [comment]
> @cyxddgithub Bazel 0.22.0 is quite old and predates Envoy 1.10.0 which was released on April 5 (which fell between the release dates of Bazel 0.24.1 and 0.25.0). It may be too old for the version of bazel-compilation-database included I would try using the latest Bazel 0.27.1.

tks for help. i read [this blog ](https://github.com/indrayam/nerd-notes/blob/master/cncf-apps/envoy.md#build-envoy-on-macos-mojave-10145) as it said need the 0.22.0 bazel version. before read it, i try the last version bazel installed by brew still not work. so can you teach a blog for mac local environment for vscode/clion and setting the compilation database. that must by amazing

**Comment by silentdai** [comment]
It was bazel 0.22.0 probably because that is the latest bazel version at that moment. Mine is 0.26 and it works well(sorry mine is not mac)


> envoy tag 1.10.1
I didn't see this tag on github. Is it your own branch?

**Comment by cyxddgithub** [comment]
> It was bazel 0.22.0 probably because that is the latest bazel version at that moment. Mine is 0.26 and it works well(sorry mine is not mac)
> 
> > envoy tag 1.10.1
> > I didn't see this tag on github. Is it your own branch?

sorry it's a typo. tag is 1.10.0. tks for reply i will try 0.26

**Comment by cstrahan** [comment]
I ran into the same problem. If you're on v1.10.0, you can cherry pick this commit (you'll need to resolve a very minor conflict): https://github.com/envoyproxy/envoy/commit/fa69fad0de6b63a254ce6a9f8164b31163a1ada0

I found that through this other issue: https://github.com/envoyproxy/envoy/issues/6172

**Comment by cstrahan** [comment]
I'll also note that, out of the box, the `bazel-compilation-database-0.3.2/.ycm_extra_conf.py` didn't work, as `ycmd` couldn't find my system's standard c/c++ headers. The following changes resolved this issue for me, at which point (neo)vim+[YouCompleteMe](https://github.com/ycm-core/YouCompleteMe) and vscode+[you-complete-me](https://marketplace.visualstudio.com/items?itemName=RichardHe.you-complete-me) both worked.

In fact, this setup works _much_ better than CLion with the Bazel plugin (while "go to declaration" would work, "go to implementations" and such never worked, and even then things could generally be described as "wonky"); I don't know if that's a problem with CLion, or the Bazel plugin. I have yet to try using CLion with the the compilation database -- that may work better.

```patch
diff --git a/bazel-compilation-database-0.3.2/.ycm_extra_conf.py b/bazel-compilation-database-0.3.2-new/.ycm_extra_conf.py
index 287a61de8..34ddfcfee 100755
--- a/bazel-compilation-database-0.3.2/.ycm_extra_conf.py
+++ b/bazel-compilation-database-0.3.2-new/.ycm_extra_conf.py
@@ -33,6 +33,31 @@ import subprocess
 import sys
 import xml.etree.ElementTree as ElementTree
 
+def SystemIncludeDirectoryFlags():
+  """Determines compile flags to include the system include directories.
+  Use as a workaround for https://github.com/Valloric/YouCompleteMe/issues/303
+  Returns:
+    (List of Strings) Compile flags to append.
+  """
+  try:
+    with open(os.devnull, 'rb') as DEVNULL:
+      output = subprocess.check_output(['clang-7', '-v', '-E', '-x', 'c++', '-'],
+                                       stdin=DEVNULL, stderr=subprocess.STDOUT)
+  except:
+    return []
+  includes_regex = r'#include <\.\.\.> search starts here:\s*' \
+                   r'(.*?)End of search list\.'
+  includes = re.search(includes_regex, output.decode(), re.DOTALL).group(1)
+  flags = []
+  for path in includes.splitlines():
+    path = path.strip()
+    if os.path.isdir(path):
+      flags.append('-isystem')
+      flags.append(path)
+  return flags
+
+_system_include_flags = SystemIncludeDirectoryFlags()
+
 def aspects_bzl(bazel_workspace):
     """bzl file path for compilation database aspect definitions."""
 
@@ -186,7 +211,7 @@ def FlagsForFile(filename, **kwargs):
     aspects_filepath = get_aspects_filepath(labels[0], bazel_bin)
 
     compdb_json = get_compdb_json(aspects_filepath, bazel_exec_root)
-    flags = standardize_flags(get_flags(filepath, compdb_json), bazel_workspace)
+    flags = standardize_flags(get_flags(filepath, compdb_json), bazel_workspace) + _system_include_flags
 
     return {
         'flags': flags,
@@ -196,4 +221,4 @@ def FlagsForFile(filename, **kwargs):
 # For testing; needs exactly one argument as path of file.
 if __name__ == '__main__':
     filename = os.path.abspath(sys.argv[1])
-    print FlagsForFile(filename)
+    print(FlagsForFile(filename))

```

**Comment by cyxddgithub** [comment]
> I'll also note that, out of the box, the `bazel-compilation-database-0.3.2/.ycm_extra_conf.py` didn't work, as `ycmd` couldn't find my system's standard c/c++ headers. The following changes resolved this issue for me, at which point (neo)vim+[YouCompleteMe](https://github.com/ycm-core/YouCompleteMe) and vscode+[you-complete-me](https://marketplace.visualstudio.com/items?itemName=RichardHe.you-complete-me) both worked.
> 
> In fact, this setup works _much_ better than CLion with the Bazel plugin (while "go to declaration" would work, "go to implementations" and such never worked, and even then things could generally be described as "wonky"); I don't know if that's a problem with CLion, or the Bazel plugin. I have yet to try using CLion with the the compilation database -- that may work better.
> 
> ```diff
> diff --git a/bazel-compilation-database-0.3.2/.ycm_extra_conf.py b/bazel-compilation-database-0.3.2-new/.ycm_extra_conf.py
> index 287a61de8..34ddfcfee 100755
> --- a/bazel-compilation-database-0.3.2/.ycm_extra_conf.py
> +++ b/bazel-compilation-database-0.3.2-new/.ycm_extra_conf.py
> @@ -33,6 +33,31 @@ import subprocess
>  import sys
>  import xml.etree.ElementTree as ElementTree
>  
> +def SystemIncludeDirectoryFlags():
> +  """Determines compile flags to include the system include directories.
> +  Use as a workaround for https://github.com/Valloric/YouCompleteMe/issues/303
> +  Returns:
> +    (List of Strings) Compile flags to append.
> +  """
> +  try:
> +    with open(os.devnull, 'rb') as DEVNULL:
> +      output = subprocess.check_output(['clang-7', '-v', '-E', '-x', 'c++', '-'],
> +                                       stdin=DEVNULL, stderr=subprocess.STDOUT)
> +  except:
> +    return []
> +  includes_regex = r'#include <\.\.\.> search starts here:\s*' \
> +                   r'(.*?)End of search list\.'
> +  includes = re.search(includes_regex, output.decode(), re.DOTALL).group(1)
> +  flags = []
> +  for path in includes.splitlines():
> +    path = path.strip()
> +    if os.path.isdir(path):
> +      flags.append('-isystem')
> +      flags.append(path)
> +  return flags
> +
> +_system_include_flags = SystemIncludeDirectoryFlags()
> +
>  def aspects_bzl(bazel_workspace):
>      """bzl file path for compilation database aspect definitions."""
>  
> @@ -186,7 +211,7 @@ def FlagsForFile(filename, **kwargs):
>      aspects_filepath = get_aspects_filepath(labels[0], bazel_bin)
>  
>      compdb_json = get_compdb_json(aspects_filepath, bazel_exec_root)
> -    flags = standardize_flags(get_flags(filepath, compdb_json), bazel_workspace)
> +    flags = standardize_flags(get_flags(filepath, compdb_json), bazel_workspace) + _system_include_flags
>  
>      return {
>          'flags': flags,
> @@ -196,4 +221,4 @@ def FlagsForFile(filename, **kwargs):
>  # For testing; needs exactly one argument as path of file.
>  if __name__ == '__main__':
>      filename = os.path.abspath(sys.argv[1])
> -    print FlagsForFile(filename)
> +    print(FlagsForFile(filename))
> ```

tks for reply!real cool i wil try the method.by the way i try cquery+vscode not work at all.YCM maybe work.
