### ISSUE TITLE
Envoy sidecar proxy not working for gRPC service

### ISSUE THREAD

**Issue by sibendu** [envoyproxy/envoy#7487]
**Issue Template**

*Title*: Envoy sidecar proxy not working for gRPC service

*Description*:
I have deployed a gRPC service (built in Java) on K8S with a envoy sidecar. When another services calls this service directly as a gRPC client, it works. However, as I configure the client service to calls through the envoy sidecar proxy, it gives error : RPC failed: Status{code=UNAVAILABLE, description=upstream connect error or disconnect/reset before headers. reset reason: connection failure, cause=null}
So it reached the envoy sidecar, but failed to propagate the call to profileservice (in same pod, configured as localhost)

*Config*:
My envoy config is as below:

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8980
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              typed_config:
                "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                path: "/var/log/access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: services
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: frontend_service
              cors:
                allow_origin: ["*"]
                allow_methods: GET, PUT, DELETE, POST
                allow_headers: "keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web"
          http_filters:
          - name: envoy.cors
            typed_config: {}
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: frontend_service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: frontend_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9980
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

Thank you for looking into it, and your suggestions.

**Comment by alyssawilk** [comment]
You might get more detail if you run your instance with "-l trace", which dumps a bunch of debug information.
Alternately @lizan may have some gRPC specific debug tips

**Comment by sibendu** [comment]
@alyssawilk  thank you for looking into it. I had my config wrong. Now it is working.
Regards.

**Comment by sibendu** [comment]
Here is the corrected one, in case anybody comes across same:

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8980
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: services
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: frontend_service
          http_filters:
          - name: envoy.cors
            typed_config: {}
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: frontend_service
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    load_assignment:
      cluster_name: frontend_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9980
