### ISSUE TITLE
BAZEL_BUILD_OPTIONS and BAZEL_EXTRA_BUILD_OPTIONS is ignored

### ISSUE THREAD

**Issue by incfly** [envoyproxy/envoy#7502]
**Issue Template**

*Title*: *User provided BAZEL_BUILD_OPTIONS and BAZEL_EXTRA_BUILD_OPTIONS is ignored*

*Description*

[ci/README.md](https://github.com/envoyproxy/envoy/blob/master/ci/README.md#building-and-running-tests-as-a-developer) instructs developers can customize the build options with BAZEL_BUILD_OPTIONS environment variable.

However based on the [implementation](https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L72), we always set it directly without checking whether the env var has value or not. This can be reproduced by 

```bash
BAZEL_BUILD_OPTIONS='--fuzzy-flag should-trigger-error' bash -x ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
```

And the build still proceed.

*Expected behavior*

We check `BAZEL_BUILD_OPTIONS` and `BAZEL_EXTRA_BUILD_OPTIONS` is set or not.

```
BAZEL_EXTRA_BUILD_OPTIONS=${BAZEL_EXTRA_BUILD_OPTIONS-"flag that we want by default"}
```

Also the documention should be updated, I believe, BAZEL_EXTRA_BUILD_OPTIONS is reserved for developers. not BAZEL_BUILD_OPTIONS.

**Comment by alyssawilk** [comment]
cc @htuch @lizan @jmillikin-stripe

**Comment by htuch** [comment]
You need to set these in the Docker environment, probably something like:
```
bash -x ./ci/run_envoy_docker.sh 'BAZEL_BUILD_OPTIONS="--fuzzy-flag should-trigger-error" ./ci/do_ci.sh bazel.release'
```

**Comment by incfly** [comment]
I tried that, but still can't pass valid bazel option to the build,

```shell
bash -x ./ci/run_envoy_docker.sh 'BAZEL_BUILD_OPTIONS="--define a=b"
./ci/do_ci.sh bazel.release'
```

This stops as same as fuzzy-flag above. Adding echo print
${BAZEL_BUILD_OPTIONS} indicates the `--define` is not passed.

**Comment by htuch** [comment]
Yeah, this needs to be `${BAZEL_BUILD_EXTRA_OPTIONS}` as consumed by https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L72.

**Comment by incfly** [comment]
Fixed.
