### ISSUE TITLE
Wrong type for lengths/sizes in source/common/buffer/buffer_impl.*

### ISSUE THREAD

**Issue by danfe** [envoyproxy/envoy#7504]
Currently, `source/common/buffer/buffer_impl.{cc,h}` use `uint64_t` to hold various lengths and sizes, while the correct type is `size_t`.  On 64-bit systems, they are the same 64-bit unsigned type, but on 32-bit machines (where `size_t` is 32-bit, because it's impossible to address more than 4GB) they are incompatible, which breaks the build on i386.  This would also likely allow to remove a few static casts.

See also #3463, which mentions that some of those misspellings of `size_t` (may it be `uint32_t` or `uint64_t`, both are wrong) were fixed before, but more is needed.  Thank you.

**Comment by alyssawilk** [comment]
I think this would be fine to fix (and please do so if it's causing you problems).  I suspect we're likely to have i386 regressions unless we set up a 32-bit CI build.

**Comment by danfe** [comment]
Yup, it should be fixed.  Not just because this particular code make calls to _libevent_-provided methods which correctly accept `size_t` arguments so it would make it generally more correct, but also because the server itself is advertised as having _small memory footprint_, and many of us prefer light 32-bit VMs/containers, even in 64-bit host environment, precisely because of that.

I can provide patches if needed, before you guys setup your 32-bit CI build system.

**Comment by htuch** [comment]
One caution here is we should not be optimizing for `libevent` based buffers, these are likely to disappear soon. So, whatever is built needs to be built assuming the Envoy-owned buffers going forward. 

TBH, I think the use of 32 vs. 64-bit types here is not the high order bit (if you'll excuse the pun) when it comes to Envoy memory use. We already know things like cluster stats and LB structures are where the big impact is. So, while I don't think it's terrible to use `size_t` for buffer sizes, it's probably good to be realistic about why we're doing this, i.e. it's not really to save memory in reality.

**Comment by danfe** [comment]
Fair enough; FWIW, I didn't want to imply that `size_t` buffer sizes bring some magical memory savings, just that having a 32-bit version of Envoy is still useful.

**Comment by htuch** [comment]
Yep, we definitely want Envoy to build for 32-bit systems, there's a bunch of ARM platforms that it would make sense on as well as i386.
