### ISSUE TITLE
[XDS] resolve the inconsistency treatment of parse-error vs validation-error in XDS onConfigUpdate(resources, version) API.

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#7508]
**Issue Template**

*Title*: Fully reject (reject-all) on parse-error or PGV validation-error in the "old" CDS onConfigUpdate(resources, version) API.

*Description*:
> Before the delta API impl, CDS onConfigUpdate rejects a DiscoveryResponse if there is any parse-error (anyConvert failure) or validation-error (PGV validation error). 
In the new CDS impl, the old "status-of-the-world" onConfigUpdate(resources, version) calls the delta form onConfigUpdate(added_resources, removed_resources, version) API, by splitting the "resources" into "added_resources" and "removed_resources". 
The PGV validation errors are treated as forgivable errors (the delta form will skip the invalid ones), while the parse-errors (anyConvert) are treated differently: any parse-error in the old-form onConfigUpdate will cause a "reject-all" failure on the onConfigUpdate(resources, version) API call, as there is no try-catch in the function body.

In the onConfigUpdate(resources, version) function, parse-error should not be forgiven as well: we compute the to-be-removed resource names based on parsed proto's resource name, skipping a parse error means we will erroneously remove a resource.

Talked with @htuch, we'd like the impl to go back to the previous behavior: reject-all if there is any error (parse-error, PGV validation error) in the old form onConfigUpdate(resources, version) API call. And by design deltaAPI onConfigUpdate should tolerate both errors(Partial-reject).

[optional *Relevant Links*:]
>See also discussion around https://github.com/envoyproxy/envoy/issues/5739

**Comment by stevenzzzz** [comment]
loop in @fredlas for discussion.

**Comment by htuch** [comment]
We need to be consistent across all xDS here as well. I would love to be able to have some generic code handle this (appropriately templated) to avoid having each xDS make the same mistake.

**Comment by stevenzzzz** [comment]
sure thing, I will go through all the API impl to have a consistent behavior, there is actually a TODO I am leaving in PR https://github.com/envoyproxy/envoy/pull/7451 about it.

**Comment by stevenzzzz** [comment]
I think we still want this，reopen it.
