### ISSUE TITLE
Add docs describing load balancer policy CLUSTER_PROVIDED 

### ISSUE THREAD

**Issue by adilhafeez** [envoyproxy/envoy#7514]
cluster_provided lb policy was added as part of this change https://github.com/envoyproxy/envoy/pull/6895. But it's missing docs update to explain cluster_provided lb_policy.

**Comment by adilhafeez** [comment]
@HenryYYang

**Comment by mattklein123** [comment]
It is documented here: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#enum-cluster-lbpolicy

**Comment by adilhafeez** [comment]
ah I didn't see it in envoyproxy docs, thanks @mattklein123
