### ISSUE TITLE
Is there a way to build envoy without using bazel?

### ISSUE THREAD

**Issue by zqzzq** [envoyproxy/envoy#7517]
I want to build envoy in mips64 platform, but there are too many difficulties to build envoy with bazel, so Is it possible to manually download the dependencies and then compile envoy directly?

**Comment by danfe** [comment]
Yes, there is.  I build it on FreeBSD with GNU `make(1)`, the way God intended to build software, and two simple makefiles, one for processing API `*.proto` files and another to compile main source code.  You can find them [here](https://svnweb.freebsd.org/ports/head/www/envoy/files/).

Dependencies are downloaded and properly placed within the Envoy's source tree by the FreeBSD Ports framework, see the `Makefile` in the upper directory of that aforementioned link for details.

**Comment by htuch** [comment]
Please note that any non-Bazel flow is not supported by the Envoy OSS community. So, while there exists unofficial community contributions here, we can't offer any guarantees around breaking changes, documentation, support on mailing lists etc. It's highly unlikely we will support a non-Bazel build system in the foreseeable future.

**Comment by moderation** [comment]
https://yastack.io/ have a process to build without Bazel they document at https://medium.com/@chintan_/envoy-cmake-adapting-yastack-build-system-for-regular-envoy-547ee7c227d0. Early on in Envoy's life we had challenges building on aarch64 and PPC platforms but the approach was to fix the toolchain incompatibilities in the path. For aarch64 that was mainly fixing Bazel and rules_go. None of the workarounds at https://gitlab.com/snippets/1742074 are required anymore as things were fixed.
