### ISSUE TITLE
admin: Using SO_REUSEPORT socket option

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#7524]
*Description*:
We plan to use `SO_REUSEPORT` to achieve graceful restart of Envoy (similar to #3804).
It's possible to set socket options for the application listener socket, however it looks like it's impossible to do so for the admin port.

Would it be acceptable to add configuration options to admin port for setting socket options?

**Comment by mattklein123** [comment]
This sounds reasonable to me.

**Comment by euroelessar** [comment]
Please assign task to me, I'll start working on the change shortly.
