### ISSUE TITLE
stats: high memory use when there are a large number of hosts

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#7525]
Load-tests / flame-graphs indicate a huge amount of stats allocated for systems with large numbers of endpoints.

Most likely the per-endpoint stats are of limited value relative to their cost, and there should be an option to have them disabled or folded together.

**Comment by jmarantz** [comment]
@antoniovicente

**Comment by jmarantz** [comment]
1st step IMO is to augment https://github.com/envoyproxy/envoy/blob/master/test/integration/stats_integration_test.cc#L181 with a test that holds clusters constant and scales up endpoint-count. It should not be too difficult to parameterize the helper functions and make a new test method that varies the host-count and measures deltas using a similar pattern.

**Comment by mattklein123** [comment]
As I mentioned offline, I think we can do a few things here:
1) Have config to turn off per-host stats
2) Have config to potentially have per-host stats for X% of hosts per cluster, only canary hosts, etc.

**Comment by antoniovicente** [comment]
stats_integration_test.cc will soon cover memory usage by hosts, see #8189 

I have a change in progress that reduces memory used by host stats that I plan to send out once #8189 is in.  Memory usage before: 2883 after: 1283 https://github.com/envoyproxy/envoy/compare/master...antoniovicente:stats_primitive_host_stats
