### ISSUE TITLE
How should I understand Envoy memory metrics?

### ISSUE THREAD

**Issue by andrzejwaw** [envoyproxy/envoy#7556]
How should understand envoy admin memory metrics?
Envoy metrics shows:
```
server.memory_allocated: 4 676 640 bytes
server.memory_heap_size: 6 291 456 bytes
```

*ps_mem* shows usage: 26 830 336 bytes

*top* RES shows 24 704 kb

*smem*
```
USS (Unique Set Size): 25 612 kilobytes
PSS (Proportional Set Size): 25 953 kilobytes
RSS (resident set size): 26 888 kilobytes
```

what is real memory usage of envoy? May I find it anywhere in metrics?

```
/envoy/envoy  version: e95ef6bc43daeda16451ad4ef20979d8e07a5299/1.10.0/Clean/RELEASE/BoringSSL
```

**Comment by XanderStrike** [comment]
Hey, I'm curious about envoy's memory usage as well. @alyssawilk do you know where we could go to find answers?
