### ISSUE TITLE
bazel build fail for //bazel/foreign_cc:zlib FAILED in macOS Mojave 10.14.5(18F132)

### ISSUE THREAD

**Issue by cyxddgithub** [envoyproxy/envoy#7557]
Title: bazel build //bazel/foreign_cc:zlib FAILED in macOS Mojave 10.14.5(18F132)

Description:
clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

envoy: tag 1.11.0

xcode and xcode-select installed 
and for header missing case run:
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target / 

[step-1]bazel clean --expunge
[step-2]bazel build //bazel/foreign_cc:zlib (or bazel build //source/exe:envoy)
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/micky/playground/cpp/vs_projects/envoy/tools/bazel.rc
Starting local Bazel server and connecting to it...
INFO: Analyzed target //bazel/foreign_cc:zlib (17 packages loaded, 404 targets configured).
INFO: Found 1 target...
ERROR: /Users/micky/playground/cpp/vs_projects/envoy/bazel/foreign_cc/BUILD:164:1: error executing shell command: '/bin/bash -c fun
ction cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory  and dependencies directory  for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify '--sandbox_debug' Bazel command line flag.

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules #0.0.8. Building library 'zlib'
Environment:______________TMPDIR=/var/folders/2g/0pmc7tpx6yz6_fgkyj86_rkr0000gn/T/
EXT_BUILD_ROOT=/private/var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy
INSTALLDIR=/private/var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy/bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/zlib
__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34
PATH=/private/var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
BUILD_TMPDIR=/var/folders/2g/0pmc7tpx6yz6_fgkyj86_rkr0000gn/T/tmp.z0IAgpZn
PWD=/private/var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy
EXT_BUILD_DEPS=/private/var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy/bazel_foreign_cc_deps_zlib
SHLVL=2
BUILD_LOG=bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/zlib/logs/CMake.log
BUILD_SCRIPT=bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/zlib/logs/CMake_script.sh
_=/usr/bin/env
__________________________-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy/external/local_config_cc/cc_wrapper.sh
-- Check for working C compiler: /var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy/external/local_config_cc/cc_wrapper.sh -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     /var/tmp/_bazel_micky/a6abbcdb48435599ae16f2c5f5566378/sandbox/darwin-sandbox/1/execroot/envoy/external/net_zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   zlib

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /var/folders/2g/0pmc7tpx6yz6_fgkyj86_rkr0000gn/T/tmp.z0IAgpZn
[1/37] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
[2/37] Building C object CMakeFiles/zlibstatic.dir/compress.o
[3/37] Building C object CMakeFiles/zlibstatic.dir/adler32.o
[4/37] Building C object CMakeFiles/zlibstatic.dir/crc32.o
[5/37] Building C object CMakeFiles/zlibstatic.dir/gzlib.o
[6/37] Building C object CMakeFiles/zlibstatic.dir/gzread.o
[7/37] Building C object CMakeFiles/zlibstatic.dir/gzwrite.o
[8/37] Building C object CMakeFiles/zlibstatic.dir/inftrees.o
[9/37] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
[10/37] Building C object CMakeFiles/zlibstatic.dir/zutil.o
[11/37] Building C object CMakeFiles/zlibstatic.dir/inffast.o
[12/37] Building C object CMakeFiles/zlib.dir/compress.o
[13/37] Building C object CMakeFiles/minigzip.dir/test/minigzip.o
[14/37] Building C object CMakeFiles/zlib.dir/adler32.o
[15/37] Building C object CMakeFiles/example.dir/test/example.o
[16/37] Building C object CMakeFiles/zlibstatic.dir/infback.o
[17/37] Building C object CMakeFiles/zlib.dir/crc32.o
[18/37] Building C object CMakeFiles/zlib.dir/gzclose.o
[19/37] Building C object CMakeFiles/zlib.dir/gzlib.o
[20/37] Building C object CMakeFiles/zlib.dir/inftrees.o
[21/37] Building C object CMakeFiles/zlib.dir/gzread.o
[22/37] Building C object CMakeFiles/zlib.dir/gzwrite.o
[23/37] Building C object CMakeFiles/zlib.dir/inffast.o
[24/37] Building C object CMakeFiles/zlib.dir/uncompr.o
[25/37] Building C object CMakeFiles/zlib.dir/zutil.o
[26/37] Building C object CMakeFiles/zlibstatic.dir/trees.o
[27/37] Building C object CMakeFiles/zlib.dir/infback.o
[28/37] Building C object CMakeFiles/zlibstatic.dir/deflate.o
[29/37] Building C object CMakeFiles/zlib.dir/trees.o
[30/37] Building C object CMakeFiles/zlibstatic.dir/inflate.o
[31/37] Linking C static library libz.a
FAILED: libz.a 
: && /usr/local/Cellar/cmake/3.14.5/bin/cmake -E remove libz.a && /usr/bin/libtool qc libz.a  CMakeFiles/zlibstatic.dir/adler32.o CMakeFiles/zlibstatic.dir/compress.o CMakeFiles/zlibstatic.dir/crc32.o CMakeFiles/zlibstatic.dir/deflate.o CMakeFiles/zlibstatic.dir/gzclose.o CMakeFiles/zlibstatic.dir/gzlib.o CMakeFiles/zlibstatic.dir/gzread.o CMakeFiles/zlibstatic.dir/gzwrite.o CMakeFiles/zlibstatic.dir/inflate.o CMakeFiles/zlibstatic.dir/infback.o CMakeFiles/zlibstatic.dir/inftrees.o CMakeFiles/zlibstatic.dir/inffast.o CMakeFiles/zlibstatic.dir/trees.o CMakeFiles/zlibstatic.dir/uncompr.o CMakeFiles/zlibstatic.dir/zutil.o && /usr/local/Cellar/cmake/3.14.5/bin/cmake -E touch libz.a && :
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
[32/37] Building C object CMakeFiles/zlib.dir/deflate.o
[33/37] Building C object CMakeFiles/zlib.dir/inflate.o
ninja: build stopped: subcommand failed.

_____ END BUILD LOGS _____
rules_foreign_cc: Build script location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/zlib/logs/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin-fastbuild/bin/bazel/foreign_cc/zlib/logs/CMake.log

Target //bazel/foreign_cc:zlib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.037s, Critical Path: 2.82s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by alyssawilk** [comment]
cc @lizan

**Comment by cdimascio** [comment]
i'm running into the same issue. @cyxddgithub were you to find a solution to this

**Comment by DrewKiino** [comment]
bump

**Comment by lizan** [comment]
Do you have full Xcode installed? Command Line Tools only doesn't work. per #8148.
