### ISSUE TITLE
Support code coverage in router check tool

### ISSUE THREAD

**Issue by jyotima** [envoyproxy/envoy#7567]
*Title*: *Enable router check tool to show code coverage for routes*

*Description*:
We are running into a situation where we want to add tests and establish a baseline coverage so that all further changes to the routes need to a test to maintain the coverage.

**Comment by jyotima** [comment]
#730

**Comment by mattklein123** [comment]
This would be really cool!

**Comment by jyotimahapatra** [comment]
https://github.com/envoyproxy/envoy/pull/7768/files

**Comment by jyotimahapatra** [comment]
https://github.com/envoyproxy/envoy/pull/7727/files

**Comment by dschaller** [comment]
Oh nice! I didn't even see this :)
