### ISSUE TITLE
HCM: buffered data ignored when onData never returns StopIteration

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#7579]
If any `encodeData` callbacks call `addEncodedData` and no StopIteration* return values are returned, the buffered data will never be read, as we never call `commonContinue` due to the `iteration_state_` check in `commonHandleAfterDataCallback`:

```
  if (status == FilterDataStatus::Continue) {
    if (iteration_state_ == IterationState::StopSingleIteration) {
      commonHandleBufferData(provided_data);
      commonContinue();
      return false;
    } else {
      ASSERT(headers_continued_);
    }
```

This becomes problematic because the following code misbehaves when there's only one `encodeData` callback:

```
  Http::FilterDataStatus encodeData(Buffer::Instance& data, bool end_stream) {
    encoder_callbacks_->addEncodedData(data, false);

    if (end_stream) {
      encoder_callbacks_->modifyEncodingBuffer([](auto& buffer) {
        // do something with the buffer
      });
      return Http::FilterDataStatus::Continue;
    }

    return Http::FilterDataStatus::StopIterationNoBuffer;
  }
};
```

Since the first call is has `end_stream = true`, we add data to buffer but since we return `Continue`, the buffer is never passed to the next filter.

**Comment by snowp** [comment]
Thinking about a solution here: maybe we should track whether `add*Data` has been called and enter the `commonContinue` block if that's the case even if `iteration_state_ != IterationState::StopSingleIteration`?

cc @alyssawilk @mattklein123

**Comment by mattklein123** [comment]
cc @soya3129 who has probably been thinking about this code the most recently. I'm guessing she will have some ideas.

**Comment by soya3129** [comment]
> Thinking about a solution here: maybe we should track whether `add*Data` has been called and enter the `commonContinue` block if that's the case even if `iteration_state_ != IterationState::StopSingleIteration`?
> 
> cc @alyssawilk @mattklein123

If we call commonContinue() when `iteration_state_ != IterationState::StopSingleIteration`, are we going to send headers and not buffered data, etc to the following filters twice? Because returning continue will keep iterating through the following filters, and commonContinue() will do the same(?).

I could be wrong. But I thought buffering data implies we need to StopIteration? Otherwise, we might just send data to the next filter? What is the scenario where we need to buffer but don't need to wait? Thanks!!

**Comment by snowp** [comment]
I think sending the data through directly is a valid solution too, it's definitely  better than just dropping the data completely. 

The trade off between the two becomes an API question imo: should the filter author be responsible for tracking whether they are buffering multiple frames? or can they use the addData callback to collect all the data into the buffer regardless of the # of frames? 

Another thing to consider is what the semantics of calling addData multiple times:
```
DataStatus decodeData(Buffer::Instance& data, bool end_stream) {
  decoder_callbacks_->addDecodedData(Buffer::OwnedImpl("data1"));
  decoder_callbacks_->addDecodedData(Buffer::OwnedImpl("data2"));
  decoder_callbacks_->addDecodedData(Buffer::OwnedImpl("data3"));
  return Continue;
}
```

should this pass through the data to the subsequent filters 3 times? or should it be buffered together with the original data as a single callback?

I'm think I'm leaning towards the buffering solution and emptying the buffer on a Continue (without repeating data/headers/etc. that was already sent), wdyt @soya3129

**Comment by soya3129** [comment]
The buffering solution on a Continue sounds good as long as we don't repeat, :)

**Comment by mattklein123** [comment]
I think this was fixed actually.
