### ISSUE TITLE
RFC: Multiple release Envoy images

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7582]
I think we need to start thinking about whether every extension in the tree makes it into our official builds. There are multiple reasons for this:
1) Security implications
2) Feature explosion
3) Support burden for service providers trying to support Envoy generically.

I think we can likely do this via shipping multiple images which perhaps equate to "minimal, "kichen sink," etc. This coupled with management server feature discovery could allow for a sane mechanism to support multiple SKUs (also potentially dynamic extensions).

cc community and @envoyproxy/maintainers for comment. We can also discuss this in the community meeting.

**Comment by mattklein123** [comment]
@htuch should this be folded into https://github.com/envoyproxy/envoy/issues/14078?

**Comment by htuch** [comment]
@mattklein123 I think it's related but not exactly the same. To the extent we're shipping release images, we can do what you describe above with multiple repositories or a single one.

**Comment by lizan** [comment]
Related to this as well as #14078, drafted https://github.com/envoyproxy/envoy/pull/14094 last night to allow enable / disable extension easier, with some possibilities to define flavors.

**Comment by mattklein123** [comment]
I'm going to collapse this issue into https://github.com/envoyproxy/envoy/issues/14078 and we can continue discussion there.
