### ISSUE TITLE
some problems of building envoy with bazel

### ISSUE THREAD

**Issue by zk3326312** [envoyproxy/envoy#7596]
I want to build envoy with bazel in my mac, but i meet some problems 

*Description*:
when i build envoy with bazel, i meet some network problems, it always faild in fetch protobuf and go.googlesource.com/tools. So i download those package manual , but when i build envoy next, bazel still have to fetch those package, so how can I configure bazel manual to solve this problem.

my command:
sudo bazel build //source/exe:envoy-static --action_env=GOPATH=$GOPATH --action_env=PATH="/usr/local/bin:/opt/local/bin:/usr/bin:/bin"

**Comment by zk3326312** [comment]
i'm sure those package have been installed correctly

**Comment by lizan** [comment]
Are you behind some proxy to access those tools in `go.googlesource.com/tools`? If so you can configure [http proxy](https://github.com/envoyproxy/envoy/tree/master/ci#building-and-running-tests-as-a-developer). Or you can download those packages manually and put in a directory, and use [distdir](https://github.com/envoyproxy/envoy/blob/master/bazel/EXTERNAL_DEPS.md#distdir---prefetching-dependencies) to tell bazel to fetch them from there.

**Comment by zk3326312** [comment]
thanks, problems can be solved by distdir
