### ISSUE TITLE
Use Source IP for hash function input - help needed

### ISSUE THREAD

**Issue by pezzati** [envoyproxy/envoy#7598]
Hi, I want TCP load balancer for RabbitMQ upstreams. I want that the service always connect to only one of rabbits over time, so i want to user source ip for hashing.

I couldn't find anything for this, is this even possible currently?

**Comment by mattklein123** [comment]
IIRC this is not supported today but I think it wouldn't be very hard to add a hashing policy for this.

**Comment by x15zhang** [comment]
Is there any plan for the issue? I also want to use source ip for hashing for tcp upstreams.
Becasue nginx support the feature:
```
upstream backend {
    hash $remote_addr;
    server 10.95.110.45:12001;
    server 10.95.220.46:12002;
}
```
