### ISSUE TITLE
Feature Request: automatic https like Caddy

### ISSUE THREAD

**Issue by kokizzu** [envoyproxy/envoy#7600]
*Title*: automatic https like Caddy

*Description*:
>Could envoy also implement something like this [Caddy](https://caddyserver.com) config:

```
x.com, www.x.com {
        root /home/web/x/public
        proxy / 127.0.0.1:8888 {
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-For {remote}
                header_upstream X-Forwarded-Proto {scheme}
        }
}
```

in Caddy, this would automatically fetch letsencrypt SSL/TLS certificates.

**Comment by mattklein123** [comment]
I believe this is a duplicate of https://github.com/envoyproxy/envoy/issues/96

**Comment by kokizzu** [comment]
ah right, i'll follow that issue instead..
