### ISSUE TITLE
build: do basic gcc build in CI

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7607]
As of this week we no longer test GCC in CI. Optimally, we should at least do a server (non-test) build with GCC to make sure we don't have any compile issues.

**Comment by mattklein123** [comment]
cc @lizan

**Comment by lizan** [comment]
FWIW, the Bazel CI we setup uses GCC from Ubuntu 18.04.
https://buildkite.com/bazel/envoy
