### ISSUE TITLE
tracing: Make request id format and tracing behavior configurable

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#7624]
*Description*:
Envoy currently enforces specific format of `x-request-id` header, and piggybacks tracing decisions into it.
However this approach does not play well with existing setups, which already heavily use both request ids and tracing, and rely on transmission of this data in different form (e.g. using explicit distinct headers for tracing-related metadata).

In short we would like to have an ability to use Envoy's tracing configuration (sample ratio, x-force-tracing header, skipping health checks, statistics, etc) with different data format.

Is it reasonable to make this behavior configurable, e.g. by ability to create native extensions which would override behavior of `Envoy::UuidUtils`?

*Relevant Links*:
https://github.com/envoyproxy/envoy/blob/3a596a4b0f8a8c3e60ff6240508a1d7395a9bacd/source/common/runtime/uuid_util.cc#L24-L39
https://github.com/envoyproxy/envoy/blob/3a596a4b0f8a8c3e60ff6240508a1d7395a9bacd/source/common/runtime/uuid_util.cc#L41-L59

**Comment by mattklein123** [comment]
I think it makes sense to make this configurable and/or pluggable. @euroelessar can you put together a more complete proposal before coding? Thank you!

**Comment by euroelessar** [comment]
Sounds good, I'll work with a team to come up with something. Do you prefer a proposal here or in some external location?

**Comment by mattklein123** [comment]
A public gdoc linked here would be best. Thank you!

**Comment by euroelessar** [comment]
@mattklein123 Hi, can you have a look or help us to assign somebody who can, please?

**Comment by mattklein123** [comment]
@euroelessar @rossdylan thanks at a high level this makes sense to me.

**Comment by a-sharma11** [comment]
wondering whats the status of this? There hasn't been any activity for more than a month here.

**Comment by rossdylan** [comment]
I've started work on it and should have a PR in the next couple weeks. I've been a bit backlogged so its going slower than I expected.

**Comment by idouba** [comment]
@rossdylan , what is the status of this PR?

**Comment by a-sharma11** [comment]
@rossdylan Sorry to ping here again but wondering if any updates on this? Internally we are holding up on the adoption of envoy due to this issue.

**Comment by idouba** [comment]
@mattklein123 sorry to ping again, what's the status of this issue?

**Comment by rossdylan** [comment]
Hey all so sorry about this, I got pulled into a bunch of other internal work so this has fallen to the side. If others are better placed to implement I'm happy to advise/review from the perspective of our use case. Other wise I'm aiming to get this done some time in December at the latest.

**Comment by a-sharma11** [comment]
Any updates here @rossdylan

**Comment by rossdylan** [comment]
I've mostly completed the implementation in a [branch](https://github.com/rossdylan/envoy/commit/37ae5a96e437160e73f8274a10843f8171343327). I've still got a few places that need to be updated to work with my changes, and then add tests. I expect to have a preliminary PR ready in the next day or two.
