### ISSUE TITLE
Feature request: gRPC Reflection combiner at the edge from multiple Cluster backends.

### ISSUE THREAD

**Issue by mattbailey** [envoyproxy/envoy#7631]
*Title*: *combine gRPC reflection responses from multiple backends*

*Description*:
>I am using envoy at the edge to route to multiple clusters of different gRPC services. gRPC reflection does not (as far as I know) support any kind of path based namespacing, so routing to `/grpc.reflection.v1alpha.ServerReflection` obviously doesn't work across multiple services.  It would be great if envoy could hit all identified gRPC clusters for `/grpc.reflection.v1alpha.ServerReflection` and combine them into a single response at the edge. Caching the response would be useful as well.

[optional *Relevant Links*:]
>Probably related to https://github.com/envoyproxy/envoy/issues/1182
>Raised question on grpc-go as well: https://github.com/grpc/grpc-go/issues/2912

**Comment by mattklein123** [comment]
This kind of auto-hydration is something I'm interested in from a filter perspective, but it needs a detailed design proposal as it is a large topic.

**Comment by mattbailey** [comment]
Yeah, it's non trivial, and might also warrant a conversation in the alpha reflection spec as well. I got a stopgap service built to serve up a new handler for the reflection proto that hits up the backing services and stores the responses in an LRU. Right now, just relying on a tight coupling between the DNS names of upstream host clusters and the names of my gRPC services to map out connectivity, but really should hook it into the envoy APIs themselves.
