### ISSUE TITLE
ServerInstanceImplTest.BootstrapNodeWithSocketOptions fails in certain environment

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#7636]
*Description*:

The test added #7562 fails in my local env (Debian stretch with Clang-8), error log:

```
[ RUN      ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv4
test/server/server_test.cc:576: Failure
Failed
Exception should take place. It did not.
[  FAILED  ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv4, where GetParam() = 4-byte object <00-00 00-00> (50 ms)
[ RUN      ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv6
test/server/server_test.cc:576: Failure
Failed
Exception should take place. It did not.
[  FAILED  ] IpVersions/ServerInstanceImplTest.BootstrapNodeWithSocketOptions/IPv6, where GetParam() = 4-byte object <01-00 00-00> (23 ms)
```

It does fail regardless whether I build/run this test in build container (i.e. via `ci/run_envoy_docker.sh`) or not, so I guess this is somewhat related to kernel or its config. Just FYI the kernel version is `4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`. Any idea? @euroelessar

**Comment by euroelessar** [comment]
My only theory atm would be that temporary socket somehow uses different ip:port tuple than admin port itself.
Can you try to collect `strace` dump of this failed test run, please?

**Comment by lizan** [comment]
Yes, strace dump: https://gist.github.com/lizan/efa1bd81c70c198aa16419f90889acdc

**Comment by euroelessar** [comment]
Can you check if this behavior is still reproducible on this branch, please?
https://github.com/euroelessar/envoy/tree/reuseport-also-listen

**Comment by lizan** [comment]
Thanks it works! The test doesn't fail on that branch.

**Comment by euroelessar** [comment]
Great, I've modified code a bit again (to remove hard-coded exception text and so on), would appreciate if you give a try to the version in the pull request.
