### ISSUE TITLE
Documentation request: Clarify buffer configuration`max_request_bytes` default value

### ISSUE THREAD

**Issue by sbz** [envoyproxy/envoy#7650]
*Title*: Document the default value of buffer configuration setting `max_request_bytes`

*Description*:

Configuration parameter `max_request_bytes` can be tweaked to increase the size of the buffer to workaround a HTTP Response Status Code [413](https://httpstatuses.com/413) `Payload Too Large` [RFC 7231]. 

There is no information what is the default value in envoy documentations either for [v1-api](https://www.envoyproxy.io/docs/envoy/v1.8.0/api-v1/http_filters/buffer_filter#config-http-filters-buffer-v1) (version 1.8.0) nor [v2-api](https://www.envoyproxy.io/docs/envoy/v1.11.0/api-v2/config/filter/http/buffer/v2/buffer.proto#envoy-api-msg-config-filter-http-buffer-v2-buffer) (latest version 1.12.0).  

For lot of configuration parameters envoy documentation explicit the default values. An example on the [Circuit breaker settings](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto.html?highlight=max_requests#cluster-circuitbreakers-thresholds) 

I tried to figured out what is the default value for that `max_request_bytes` parameter by investigating the code in several places [protocol buffer definition](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/filter/http/buffer/v2/buffer.proto#L23), [cpp BufferFilter object definition](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/buffer/buffer_filter.h#L28) and [test samples](https://github.com/envoyproxy/envoy/blob/master/test/config/integration/server.yaml#L274). 

Would you mind to let me know if I have missed some parts in the documentation which would give me more details or if it's still unspecified.

*Relevant Links*:
[V1 API HTTP Filters Buffer](https://www.envoyproxy.io/docs/envoy/v1.8.0/api-v1/http_filters/buffer_filter#config-http-filters-buffer-v1) documentation link
[V2 API HTTP Filters Buffer](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/buffer/v2/buffer.proto#envoy-api-msg-config-filter-http-buffer-v2-buffer) documentation link

**Comment by sbz** [comment]
Thanks! 🤝

**Comment by k2mahajan** [comment]
I still do not see the default value of mx_request_bytes documented. Can someone clarify here?

**Comment by Brunomachadob** [comment]
> I still do not see the default value of mx_request_bytes documented. Can someone clarify here?

@k2mahajan If I understood correctly, you should take a look on the following docs on how to increase it:
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control

And if you go to the docs of the `per_connection_buffer_limit_bytes` that is mentioned there:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-per-connection-buffer-limit-bytes

It says the default limit is `1mb`
