### ISSUE TITLE
Ring Hash balancing with subsets

### ISSUE THREAD

**Issue by TuvaevAndrey** [envoyproxy/envoy#7651]
*Title*: *Ring Hash LB policy doesn't consider subsets*

*Description*:
>I'm using envoy:v1.11.0 and I have to provide an affinity by the header value. Another goal is to divide cluster into subsets to allow testing local nodes with exactly same routes inside cloud cluster. 
Ring hash policy works just fine but it completely ignores subset configuration although subset routing starts working after switching to round robin or least request policy.

Let me know if I have missed some parts in the [documentation](https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/load_balancing/subsets) which would give me more details.

**Comment by mattklein123** [comment]
I don't remember exactly why this is not supported today. cc @zuercher @snowp

**Comment by TuvaevAndrey** [comment]
Guys, help wanted :)

**Comment by zuercher** [comment]
It looks like it's meant to be supported, but `ClusterManagerImpl::loadCluster` initializes a thread aware LB when the lb type is ring hash, maglev or cluster-provided. That precludes the subset lb from being used.
