### ISSUE TITLE
Ability to do a prefix_write in a route.WeightedCluster.ClusterWeight

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#7668]
*Title*: route.WeightedCluster.ClusterWeight
*Description*:
Feature request to add a `prefix_rewrite` field to `route.WeightedCluster.ClusterWeight`. The use case we have is that we're doing a migration from one service to another using `ClusterWeight` to be incremental. However the new service will use a different path. So we want to traffic split between service A expecting `/` and service B expecting `/foobar`. I think this feature would be generally useful for anyone traffic-splitting between services that expect different paths, and fits well with the existing `request_to_*` and `response_to_*` options.

Currently the only `prefix_rewrite` options are at the `route.RouteAction` level (which would rewrite the prefix for both clusters) and `route.RedirectAction`.

[optional *Relevant Links*:]
[route.RouteAction](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction)
[`route.WeightedCluster.ClusterWeight`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-weightedcluster-clusterweight)

**Comment by derekargueta** [comment]
I have a working PR for this I'll post soon, just cleaning up.

**Comment by derekargueta** [comment]
This is no longer an internal requirement for us - I'd be happy to close this unless others think this is still a desirable feature.

**Comment by mattklein123** [comment]
Let's just close and we can reopen if it is asked for again. Thanks for following up!
