### ISSUE TITLE
some retries are skipped by Envoy

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#7670]
I am debugging some retry failures and noticed that Envoy is skipping retry in some cases even though the retry policy is set for it. This is a gRPC retry.

Here is the retry configuration
num_retries: 5
retry-on: cancelled,connect-failure,gateway-error,refused-stream,resource-exhausted,unavailable

Actual end client sees 503 with error message "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

Here is some relevant stats : 
envoy.cluster.upstream_rq_retry : 7
envoy.cluster.upstream_rq_retry_success: 6
envoy.cluster.upstream_rq_503: 1
envoy.http2.tx_reset:1
envoy.cluster.upstream_rq_pending_failure_eject:7
envoy.cluster.upstream_cx_connect_fail:7
envoy.cluster.upstream_cx_connect_timeout:3

As can be seen from the above stats, one retry is skipped and resulted in 503. 

Looking at the `router` code, I see two places where a retry can be skipped on upstream reset.
One here, But since it is a connection failure - none these conditions should trigger the skip. Also `rq_reset_after_downstream_response_started` stat is not incremented. So I am guessing this is not the case. 
https://github.com/envoyproxy/envoy/blob/7e7486588239f42b4be3a6383e3c0776d2d05bef/source/common/router/router.cc#L850

Second here : 
https://github.com/envoyproxy/envoy/blob/7e7486588239f42b4be3a6383e3c0776d2d05bef/source/common/router/router.cc#L1218

I am not able to confirm whether this is case, because there are no stats to confirm the same. But the comments above seems very relevant on why retry may have been skipped.

One thing we can try is increase connect timeout to see if it resolves. Another thing I want to check, can adding buffer filter before this help?

**Comment by ramaraochavali** [comment]
@mattklein123 does the above analysis make sense? Any thoughts?

**Comment by dio** [comment]
@snowp any comments on this?

**Comment by dio** [comment]
@ramaraochavali is https://github.com/envoyproxy/envoy/pull/7671 related to this?

**Comment by ramaraochavali** [comment]
@dio Added a stat that could possibly confirm the behaviour of retries when request is completed

**Comment by mattklein123** [comment]
> One thing we can try is increase connect timeout to see if it resolves. Another thing I want to check, can adding buffer filter before this help?

Yes, buffer filter would "fix" this case if it works for your use case.

**Comment by ramaraochavali** [comment]
@mattklein123 Thanks. A follow-up question, how does buffer filter work with gRPC streaming requests? And what is the typical max_buffer_size configured? I know the second part depends on use case, but just wondering.

**Comment by mattklein123** [comment]
It doesn't work. :) Streaming requests cannot be buffered or retried. Unfortunately, Envoy has no way of knowing by default whether a request is streaming or not so this needs to be manually configured somehow, potentially on a per-route basis.

**Comment by ramaraochavali** [comment]
I see. Thanks much.
