### ISSUE TITLE
access log: Add ability to batch entries for grpc access log

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#7674]
*Description*:
Currently noticeable chunk of cpu usage (>50%) of grpc access log is spent in syscalls.
This overhead can be eliminated by batching access log entries.

Is it reasonable to extend `CommonGrpcAccessLogConfig` by two new field: `flush_interval` and `batch_byte_size`?

*Relevant Links*:
https://github.com/envoyproxy/envoy/blob/c53b12dc52744f523b5d7431514cffd2ee4c33c4/source/extensions/access_loggers/http_grpc/grpc_access_log_impl.cc#L406

**Comment by dio** [comment]
@euroelessar I think that’s reasonable. Feel free to open a PR 🙂. cc. @mattklein123 @ramaraochavali

**Comment by mattklein123** [comment]
Yes, +1

**Comment by euroelessar** [comment]
I've started working on it, and a bit confused by the structure of the code.
Few cases:
1. There is `GrpcAccessLogStreamer` singleton with global factory, but it uses grpc configuration of the first initialized logger (everyone else's configuration is ignored).
2. `GrpcAccessLogStreamer` manages thread-local state, so for batching we need to either extend it (and complicate code) to replicate efforts in `GrpcAccessLogStreamerImpl` (and in that case it's harder to test).

I would probably expect to have global `GrpcAccessLoggerCache` with `log_name->factory` map.
`GrpcAccessLoggerCache` would ensure that:
1. Each instance of `log_name` is consistent with each other (have exactly the same config).
2. There is at most one `GrpcAccessLogger` object per `thread`-`log_name` pair.

`GrpcAccessLogger` would take care of batching, stats, and stream management.
As it's per-thread object it becomes relatively easy to test it & verify that all logic works as expected.

How does it sound? It we go this road, should I send one pull request to reflect this issue as well, or do it in two steps?

**Comment by mattklein123** [comment]
@euroelessar the code is the way it is because I cut a bunch of corners when I implemented it. :)

Your proposals sound good to me. Please try to do it in incremental PRs and I'm very happy to review. Thank you!
