### ISSUE TITLE
Duplicated setupRetry()?

### ISSUE THREAD

**Issue by hongzimao** [envoyproxy/envoy#7680]
*Title*: *Duplicated setupRetry() during soft per try timeout?*

*Description*:
https://github.com/envoyproxy/envoy/blob/78d35c9775a590d06bcf924fbaaacb29187f7183/source/common/router/router.cc#L738-L739

In the if check, `setupRetry()` will increase `pending_retries_`. This will make the second `setupRetry()` duplicated? Or is it explicitly designed this way?

**Comment by hongzimao** [comment]
Is it because hedge does not cancel old retries and we want to explicitly increase `pending_retries_` by 2 as `doRetry` will decrease a `pending_retries_`?

**Comment by mattklein123** [comment]
cc @mpuncel

**Comment by ramaraochavali** [comment]
Yeah. I was also wondering about this yesterday

**Comment by snowp** [comment]
I think it being called twice like this is pretty confusing, if we need to increment `pending_retries_` again we should probably do so explicitly with a comment. mpuncel is out for the next few months so I can take a look at improving this and understanding why we need this
