### ISSUE TITLE
how can i transfer http+proto to grpc service

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#7688]
For title,i want to know if there has any filter can do this work?

**Comment by dio** [comment]
I don't think we have one. We currently have a [grpc_json_transcoder](https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/http/grpc_json_transcoder) which transcodes HTTP-JSON (application/json) requests to gRPC requests.

Could you explain a bit more on your use-case? Thank you.

**Comment by hbgongen** [comment]
> I don't think we have one. We currently have a [grpc_json_transcoder](https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/http/grpc_json_transcoder) which transcodes HTTP-JSON (application/json) requests to gRPC requests.
> 
> Could you explain a bit more on your use-case? Thank you.

oh,thanks.we now want to use client request via http 1.1 or http 2.0 but with protobuffer not json,we background use grpc service.so i want to know how to make envoy support this func.

**Comment by hbgongen** [comment]
i also want to know.i can see the some log like http request header(content type)and so on.but now i can't see it.i don't know what happened.i need it to debug my process....please help me.

**Comment by zuercher** [comment]
For converting http/1.1 requests with a protobuffer payload, you can use the [grpc_http1_bridge filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_http1_bridge_filter).

HTTP headers are only logged at debug level or higher.
