### ISSUE TITLE
ext_authz http filter does not propagate HttpStatus over http2

### ISSUE THREAD

**Issue by alxyav** [envoyproxy/envoy#7692]
Tested with envoy v1.10.0

*Description*:
The explicit http status code specified by external auth service is not respected when request is performed over http2 - instead the pseudo-header of ":status" always has the value of 200. 

*Details*:
Envoy is setup to talk to a custom (grpc) auth service that implements the ext_authz interface. Here's the implementation of `Check` method:

```go
func (ea *extauth) Check(ctx context.Context, req *pb.CheckRequest) (*pb.CheckResponse, error) {
	return &pb.CheckResponse{
		Status: &google_rpc.Status{
			Code: (int32)(google_rpc.UNAUTHENTICATED),
		},
		HttpResponse: &pb.CheckResponse_DeniedResponse{
			DeniedResponse: &pb.DeniedHttpResponse{
				Status: &pb_type.HttpStatus{
					Code: pb_type.StatusCode_Unauthorized, // == 401
				},
			},
		},
	}, nil
}
```

Here's what shows up in the access log when a request is made over http2:
```
"POST /service.DummyService/Get HTTP/2" 200 UAEX 10 0 15 - "192.168.144.1" "grpc-go/1.20.1" "7b106f1c-dac0-4ec6-8174-7dbbb0ad4c0e" "0.0.0.0:9000" "-"
```

over http1:
```
"GET /service.DummyService/Get HTTP/1.1" 401 UAEX 0 0 2 - "192.168.144.1" "curl/7.54.0" "17dbca5b-a430-4922-900c-5f7f36e84dc5" "0.0.0.0:9000" "-"
```

Although ":status" being 200 in the http2 case sort of makes sense (grpc call did fail, but "transport" (http2) succeeded), I expect it to match the http1 one. Or, alternatively, allow me to explicitly define http1/http2 response codes. Currently, I do this by setting the ":status" pseudo header: 

```go
func (ea *extauth) Check(ctx context.Context, req *pb.CheckRequest) (*pb.CheckResponse, error) {
	return &pb.CheckResponse{
		Status: &google_rpc.Status{
			Code: (int32)(google_rpc.UNAUTHENTICATED),
		},
		HttpResponse: &pb.CheckResponse_DeniedResponse{
			DeniedResponse: &pb.DeniedHttpResponse{
				Status: &pb_type.HttpStatus{
					Code: pb_type.StatusCode_Unauthorized,
				},
				Headers: []*core.HeaderValueOption{
					{
						Header: &core.HeaderValue{
							Key: ":status",
							Value: "401",
						},
					},
				},
			},
		},
	}, nil
}
```

**Comment by dio** [comment]
cc. @gsagula

**Comment by dio** [comment]
Put it as question first while I'm trying to repro this. Thanks.

**Comment by gsagula** [comment]
I think your header key should be `status` instead of `:status`.
```
Header: &core.HeaderValue{
	Key: "status",
	Value: "401",
}
```
