### ISSUE TITLE
ext_authz: allow sending dynamic metadata as context

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#7699]
*Title*: *ext_authz: allow sending dynamic metadata as context*

*Description*:
AFAICT from the docs & code, the ext_authz [attribute context](https://www.envoyproxy.io/docs/envoy/latest/api-v2/service/auth/v2/attribute_context.proto#service-auth-v2-attributecontext) can take "static metadata" only. However, there are certain use-cases where you want to use some metadata passed from one filter and send it to the ext_authz service as context. My specific use-case is using the result of the `jwt_authn` filter via the `payload_in_metadata` flag to pass validated JWT information to the ext_authz filter.

*Relevant Links*:
Not entirely unrelated to https://github.com/envoyproxy/envoy/issues/7272

**Comment by dio** [comment]
Hum, these two are interesting use-cases. @bplotnick Do you have an idea on how the configuration would look like?

cc. @gsagula

**Comment by bplotnick** [comment]
I'm not entirely sure yet, but maybe something like a list of metadata namespaces for config. I don't think we can easily re-use the `context_extensions` field for configuration, but we could have another field (something like "`metadata_context`") of type `repeated string` in [CheckSettings](https://github.com/envoyproxy/envoy/blob/a48143e13154b3c96507f2635339be1a4fb280ed/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L184)

These would be passed to the ext_authz server as opaque structs. In the `ext_authz` service protocol, we'd have another field in [AttributeContext](https://github.com/envoyproxy/envoy/blob/a48143e13154b3c96507f2635339be1a4fb280ed/api/envoy/service/auth/v2/attribute_context.proto#L137), which is of type [core.Metadata](https://github.com/envoyproxy/envoy/blob/a48143e13154b3c96507f2635339be1a4fb280ed/api/envoy/api/v2/core/base.proto#L105), which is already a mapping to opaque structs
