### ISSUE TITLE
routing: ports in authority field

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#7702]
*Description*:
Some clients are sending port in the authority field (e.g. `example.com:443`), but `VirtualHost.domains` [1] field doesn't treat ports in special way. It leads the config with `domains: ["example.com"]` on TLS 443 port to not match requests with `example.com:443` host header.

What would be a good approach forward?

Potential solutions:
1. Double include all domains (with and without ports) in all Envoy configurations
2. Add option to either ignore port (as done by nginx [2])
3. Add option to auto-complete port (as suggested by RFC 2616 [3])

*Relevant Links*:
1. https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-virtualhost
2. https://github.com/nginx/nginx/blob/0ad4393e30c119d250415cb769e3d8bc8dce5186/src/http/ngx_http_request.c#L2059
3. https://tools.ietf.org/html/rfc2616#section-14.23

**Comment by mattklein123** [comment]
This is a duplicate of https://github.com/envoyproxy/envoy/issues/886. @euroelessar can we track there? I would love to see this solved. I would be in favor of (2) and/or (3) based on config.

**Comment by euroelessar** [comment]
Agree, #886 is a superset of this issue.

**Comment by euroelessar** [comment]
Closing in favor of #886
