### ISSUE TITLE
HeaderMap: simplify implementation and reduce unsafe implementation features

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#7706]
We know that HeaderMapImpl (header_map_impl.cc) has been a historical source of multiple security and correctness issues. This is largely because of its complex implementation driven by performance concerns (O(1), dynamic and inline headers) as well as the use of manual memory allocation, memcpy, C string manipulation etc. Opening this issue to track any structural wins we can achieve here. CC @PiotrSikora @mattklein123

**Comment by mattklein123** [comment]
I think all of the known fixes have been done or are in progress, so closing. We can open new/specific issues if necessary.
