### ISSUE TITLE
Allow Envoy::OptionsImpl to take a Bootstrap proto object directly

### ISSUE THREAD

**Issue by fcfort** [envoyproxy/envoy#7713]
*Description*:

I'd like to add a method to `Envoy::OptionsImpl` to specify a Bootstrap proto directly as opposed to using the `setConfigYaml`/`setConfigPath` fields, i.e. add something like:

```c
void setConfigProto(const envoy::config::bootstrap::v2::Bootstrap& config_proto)
```

This would allow clients to directly specify a Bootstrap proto object without having to deal with yaml serialization and would simplify our configuration process since we construct the Bootstrap proto programmatically as a protocol buffer.

Another option might be to have Envoy::OptionsImpl take a text proto, e.g. `configTextProto`.

While `configPath` does allow one to provide a text proto via the command line, I'd prefer a route that avoids the file system if possible.

Do any of these changes sound reasonable?

**Comment by dio** [comment]
@alyssawilk @htuch what do you think?

**Comment by mattklein123** [comment]
This seems fine to me.

**Comment by htuch** [comment]
Please do the direct typed proto, this is a great idea. I would skip text proto, unless there is a product need for this, since it is not a stable format and we're trying to encourage folks to stick to YAML as the canonical text format in Envoy.

**Comment by fcfort** [comment]
SG, I will send a PR soon.

**Comment by stevenzzzz** [comment]
+1, please expose the bootstrap protobuf from OptionsImpl as well, as in our user story, there are components which read from bootstrap config.
