### ISSUE TITLE
x-request-id does surprising things for tracing

### ISSUE THREAD

**Issue by jasonmartens** [envoyproxy/envoy#7718]
**Issue Template**

*Title*: x-request-id does surprising things for tracing

*Description*:
We have an internal Envoy running, and our edge proxy is using x-request-id already for manually correlating requests in our logs. I was investigating why our Datadog tracing stopped working after going through our proxy, and the Datadog engineers discovered that if the value of x-request-id doesn't meet a very specific format then tracing is set to NO_TRACE (thanks Datadog for tracking that down!). Specifically, I observed after going through Envoy, if it didn't recognize the `x-request-id` header the `x-datadog-sampling-priority` header is set to 0. 

It appears there are at least two checks that we are currently failing.

The first is that the x-request-id must be a UUID. We sometimes use other values in our infra, which causes this initial check to fail.
https://github.com/envoyproxy/envoy/blob/master/source/common/runtime/uuid_util.cc#L24-L27

The second is that byte 14 of the UUID must have the correct value:
https://github.com/envoyproxy/envoy/blob/3a596a4b0f8a8c3e60ff6240508a1d7395a9bacd/source/common/runtime/uuid_util.h#L39

I have done some digging, and I can't find this behavior documented anywhere, nor does it seem to be a standard practice that I can find. This leads to at best surprising behavior, especially in situations where Envoy is not the only proxy in use, or not the one that is making the sample decision. 

It also leads to problems if I would like to make the sample decision in something other than Envoy. How do I generate these special UUIDs in nginx for example?

I'm personally not sure what the correct fix is for the issue. Some approaches I've considered:
- Leave the behavior, but document it. However, I think it makes sense to use an envoy-named header here since it appears this behavior is specific to Envoy. Something like `x-envoy-id`.
- Use a different header for determining if a request should be sampled, and let `x-request-id` just be a request id which can be an opaque string.
- Something else?

**Comment by mattklein123** [comment]
This is a duplicate of https://github.com/envoyproxy/envoy/issues/7624. Can we track there?

**Comment by jasonmartens** [comment]
Yup, absolutely.
