### ISSUE TITLE
Telemetry for traffic for cluster with no endpoints i.e. traffic which will be dropped

### ISSUE THREAD

**Issue by nrjpoddar** [envoyproxy/envoy#7725]
*Telemetry for dropped traffic via the black hole cluster*

*Description*:
Istio has a concept of wildcard listeners which are configured with SO_ORIG_DST flag set and have a default cluster called `BlackHoleCluster` which is a static cluster with no endpoints configured:

```json
    {
        "name": "virtual",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15001
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.tcp_proxy",
                        "config": {
                            "cluster": "BlackHoleCluster",
                            "stat_prefix": "BlackHoleCluster"
                        }
                    }
                ]
            }
        ],
        "useOriginalDst": true
    }
```

where the `BlackHoleCluster` is configured like this:
```json
  {
        "name": "BlackHoleCluster",
        "type": "STATIC",
        "connectTimeout": "10s"
    }
```

I updated this filter chain recently to add another filter which will invoke the custom Istio Mixer to generate telemetry for the cases when `BlackHoleCluster` is hit, the new filter chain looks like this:
```json
   {
        "name": "virtual",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15001
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "mixer",
                        "config": {
                            "disable_check_calls": true,
                            "mixer_attributes": {
                                "attributes": {
                                    "context.reporter.kind": {
                                        "string_value": "outbound"
                                    },
                                    "context.reporter.uid": {
                                        "string_value": "kubernetes://productpage-v1-5cb458d74f-tpb4v.default"
                                    },
                                    "destination.service.host": {
                                        "string_value": "BlackHoleCluster"
                                    },
                                    "source.namespace": {
                                        "string_value": "default"
                                    },
                                    "source.uid": {
                                        "string_value": "kubernetes://productpage-v1-5cb458d74f-tpb4v.default"
                                    }
                                }
                            },
                            "transport": {
                                "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                                "network_fail_policy": {
                                    "base_retry_wait": "0.080s",
                                    "max_retry_wait": "1s",
                                    "policy": "FAIL_CLOSE"
                                },
                                "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local"
                            }
                        }
                    },
                    {
                        "name": "envoy.tcp_proxy",
                        "config": {
                            "cluster": "BlackHoleCluster",
                            "stat_prefix": "BlackHoleCluster"
                        }
                    }
                ]
            }
        ],
        "useOriginalDst": true
    }
```

The issue is that in this configuration mode, the Mixer filter never gets invoked and hence we can never get any telemetry for the `BlackHoleCluster`

My question is what's the correct way to achieve this functionality where we have a `SO_ORIG_DST` listener which is a TCP proxy filter that will drop traffic by default and still invoke custom filters in the chain?

*Relevant Links*
https://github.com/istio/istio/pull/15512

**Comment by nrjpoddar** [comment]
@mattklein123 any pointers you can give would be very helpful.

**Comment by mattklein123** [comment]
I'm not sure why that config would not work, if the tcp_proxy filter is being hit. I would discuss with the Istio people for debugging help.

**Comment by nrjpoddar** [comment]
Won't the Mixer filter only get invoked on events related to TCP lifecycle and in this case since there's no TCP connection that is created (BlackHole cluster has no endpoints) I'm assuming filter will not get invoked?

**Comment by kyessenov** [comment]
There could be some optimization to avoid invoking filters when upstream cluster is empty... I guess the request is to opt-out from this optimization.

**Comment by nrjpoddar** [comment]
> There could be some optimization to avoid invoking filters when upstream cluster is empty... I guess the request is to opt-out from this optimization.

Exactly, I feel like that's what happening here.

**Comment by mattklein123** [comment]
There is no such optimization. What is most likely happening is tcp_proxy is failing the request in the connect callback, and mixer is doing things elsewhere, and not taking into account that case.

**Comment by nrjpoddar** [comment]
Yeah, the mixer filter seems to wait until `onData` is invoked: https://github.com/istio/proxy/blob/master/src/envoy/tcp/mixer/filter.cc#L138

Thanks for the help!

**Comment by nrjpoddar** [comment]
Closing as this issue is on Istio's end as to how we are setting up the Mixer filters.
