### ISSUE TITLE
Windows compilation of RetryStateImpl::shouldHedgeRetryPerTryTimeout impl fails

### ISSUE THREAD

**Issue by wrowe** [envoyproxy/envoy#7736]
Windows compilation using MSBuild 15.9, we cannot get this simple line of code, introduced two months ago, to compile;

https://github.com/envoyproxy/envoy/blob/afb2370a11ce9d15ddbb1add68792dc215c0120d/source/common/router/retry_state_impl.cc#L228

source/common/router/retry_state_impl.cc(228): error C2664: 'Envoy::Router::RetryStatus Envoy::Router::RetryStateImpl::shouldRetry(bool,Envoy::Router::RetryState::DoRetryCallback)': cannot convert argument 1 from 'Envoy::Router::RetryStateImpl::shouldHedgeRetryPerTryTimeout::<lambda_f5b81d16bf43f4b112188693c10b6098>' to 'bool'
source/common/router/retry_state_impl.cc(228): note: Ambiguous user-defined-conversion

**Comment by mattklein123** [comment]
@wrowe FWIW, I would just submit PRs to fix any Windows compile issues as I'm pretty sure you are the only person compiling on Windows. :)

**Comment by wrowe** [comment]
Thanks @mklein, those that we can resolve we will escalate strait to a PR. Why this compilation is failing is a mystery to me, so far. Looking for extra C++ savvy eyeballs.

**Comment by wrowe** [comment]
Thanks @mattklein123, those that we can resolve we will escalate strait to a PR. Why this compilation is failing is a mystery to me, so far. Looking for extra C++ savvy eyeballs.

**Comment by wrowe** [comment]
Ping; still looking for a c++ guru to suggest how Win32 CL.exe fails to interpret this correctly.

**Comment by zuercher** [comment]
Given 

`RetryStatus RetryStateImpl::shouldRetry(bool would_retry, DoRetryCallback callback)`

It seems that we're passing a lamba to a function that takes a bool. And I guess gcc and clang implicitly convert it and MSVC doesn't? Seems like the line should just be `shouldRetry(true, callback)`.

**Comment by mergeconflict** [comment]
I agree with @zuercher, we should just be passing `true` to `shouldRetry`, which raises the question of why other compilers accept this code. I think it's because the lambda expression is converted to a `std::function<bool()>`, which has an [`explicit operator bool`](https://en.cppreference.com/w/cpp/utility/functional/function/operator_bool) that, for some reason I can't explain, is being used. Try this experiment:

```c++
#include <iostream>

void foo(bool b) {
  std::cout << b << std::endl;
}

int main(int argc, char** argv) {
  foo([]() -> bool { return false; });
}
```

With clang, this prints `1` regardless of the `false` in the lambda.

**Comment by zuercher** [comment]
I'm going to go ahead and submit a PR to fix this, since it makes me anxious, even if it works.
