### ISSUE TITLE
Can I use Envoy_log() to print some debug infos or log in the files?

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#7748]
for title,i want to know how to use this func.thanks,or other way i can debug in the code.

**Comment by derekargueta** [comment]
If you're referring to writing a custom extension then yes, you can use the `ENVOY_LOG` macro to emit your own messages to the Envoy log. The class you log from needs to inherit the `Logger::Loggable` interface with one of the log identifiers in the template. For example:
```
class MyThing : protected Logger::Loggable<Envoy::Logger::Id::main> {
...
}
```

To use the `main` logging identifier.

**Comment by hbgongen** [comment]
@derekargueta.ok.thanks~
I wonder that if envoy has some log function like printf,i can print some logs to std.
