### ISSUE TITLE
Enhance and extend the Header-to-Metadata filter

### ISSUE THREAD

**Issue by yangminzhu** [envoyproxy/envoy#7771]
*Title*: Enhance and extend the Header-to-Metadata filter

*Description*:
The dynamic metadata is the key component for exchanging information between filters in Envoy, but the limitation is it's hard to exchange information across envoy.

The [Header-To-Metadata](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/header_to_metadata_filter) filter makes this easier as it could convert the header to metadata. But it still has some limitations:
- It doesn't support to convert to protobuf.Struct as the value type
- It doesn't support to convert metadata to header which could be useful in corss envoy information exchange

The limitation could be resolved with relative small changes:
- Add a "STRUCT" [ValueType](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/header_to_metadata/v2/header_to_metadata.proto#enum-config-filter-http-header-to-metadata-v2-config-valuetype), it reads from a base64 encoded header and deserialize to the protobuf Struct message.
- Add a new filter Metadata-To-Header which does the opposite operation compared to the Header-To-Metadata filter.

One use case in Istio is we could configure a "Metadata-To-Header" filter in client side to write some metadata to the header before sending the request. On server side, the "Header-To-Metadata" filter will then decode the metadata from the header which will be used by following filters for various purposes.

Does this feature request sounds reasonable to be added? I'm happy to send out some PRs to implement it if so. Thank you.

cc @mattklein123 @rgs1 @zuercher

[optional *Relevant Links*:]
The feature request for supporting exchanging arbitrary metadata between sidecars: https://github.com/envoyproxy/envoy/issues/6532

**Comment by kyessenov** [comment]
The code to perform the exchange is fairly simple (see implementation https://github.com/istio/proxy/blob/master/src/envoy/http/metadata_exchange/config.cc). I think this is mostly the question whether doing it's preferable to do it at runtime-as-a-filter/plugin vs control plane xDS. My opinion is to push this functionality into core envoy (as a filter) since then we can reuse the produced dynamic metadata as `source` and `destination` properties.

**Comment by rgs1** [comment]
@yangminzhu sounds reasonable to me.
