### ISSUE TITLE
How to create a GRPC Access Log Service?

### ISSUE THREAD

**Issue by aclowkey** [envoyproxy/envoy#7774]
I'm confused about the ALS,
Am I supposed to use the .proto file to generate the GRPc service, or what?

Thanks for guidance

**Comment by dio** [comment]
Hey Alex,

Yes, you need to build a gRPC (streaming) server, with an endpoint that
response to `/envoy.service.metrics.v2.MetricsService/StreamMetrics`. Envoy
then will connect to it to send the logs.

If you use Go, this example: https://github.com/dio/metricsink which uses
https://github.com/envoyproxy/go-control-plane probably will help a little
bit.

Good luck!

Best,

Dhi
PS. If you use Java, please also take a look:
https://github.com/envoyproxy/java-control-plane

**Comment by dio** [comment]
Hey @aclowkey,

Yes, you need to build a gRPC (streaming) server, with an endpoint that
responds to `/envoy.service.metrics.v2.MetricsService/StreamMetrics`. Envoy
then will connect to it to send the logs.

If you use Go, this example: https://github.com/dio/metricsink which uses
https://github.com/envoyproxy/go-control-plane probably will help a little
bit.

Good luck!

PS. If you use Java, please also take a look:
https://github.com/envoyproxy/java-control-plane

**Comment by aclowkey** [comment]
Yes the go-control-pane is the way to go!
Thank you
