### ISSUE TITLE
build envoy v1.10.0 error use envoyproxy/envoy-build-centos

### ISSUE THREAD

**Issue by cl51287** [envoyproxy/envoy#7776]
**Bug Template**

*Title*: *build v1.10.0 error use envoyproxy/envoy-build-centos*

*Description*:
> When I build envoy v1.10.0 use envoyproxy/envoy-build-centos image, I got a error as follow:

<pre>
/source/bazel/repositories.bzl:590:5: error loading package '@com_github_grpc_grpc//': in /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: Label '@com_github_grpc_grpc//:bazel/cc_grpc_library.bzl' crosses boundary of subpackage '@com_github_grpc_grpc//bazel' (perhaps you meant to put the colon here: '@com_github_grpc_grpc//bazel:cc_grpc_library.bzl'?) and referenced by '//external:grpc'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis failed
</pre>

Correcting the error by replacing,

<pre>load("//:bazel/cc_grpc_library.bzl", "cc_grpc_library")</pre>

by

<pre>load("//bazel:cc_grpc_library.bzl", "cc_grpc_library")</pre>

Solves the error.

I found this problem fixed in the 1.19 version of grpc, whether envoy should use the 1.19 version of grpc

**Comment by lizan** [comment]
which tag of envoyproxy/envoy-build-centos are you using? Use same tag in https://github.com/envoyproxy/envoy/blob/v1.10.0/.circleci/config.yml#L7 to build 1.10.0.

**Comment by lizan** [comment]
Also Envoy 1.11.0 uses later version of gRPC so it is already fixed.

**Comment by cl51287** [comment]
@lizan I used 6b9a116b499646031d7a801a8d8ab3ad38fced23. But is the version of grpc not specified in bazel/repository_locations.bzl? Not associated with the build image. Code at line 86 at https://github.com/envoyproxy/envoy/blob/v1.10.0/bazel/repository_locations.bzl

**Comment by lizan** [comment]
@cl51287 that is too new, bazel >= 0.23 or 0.24 (which is baked in the docker image) doesn't work with that version of grpc used in envoy 1.10.0
