### ISSUE TITLE
UT case failed on host not supporting IPV6

### ISSUE THREAD

**Issue by smwyzi** [envoyproxy/envoy#7794]
*Title*: *UT case failed on host not supporting IPV6*

*Description*:
when running envoy UT cases on host not supporting IPV6, I used the command: 
`bazel test //test/... --test_env=ENVOY_IP_TEST_VERSIONS=v4only`
but it seems that some cases for IPV6 only have been executed, and failed.
(Envoy was built directly on host, not using docker)

*Output*:
```
...
[ RUN      ] RouterMatcherHashPolicyTest.HashIpv6DifferentAddresses
unknown file: Failure
C++ exception with description "IPv6 addresses are not supported on this machine: [2001:db8:85a3::]:0" thrown in the test body.
[  FAILED  ] RouterMatcherHashPolicyTest.HashIpv6DifferentAddresses (34 ms)
...
```

so the arg `--test_env=ENVOY_IP_TEST_VERSIONS=v4only` didn't take effect in some UT cases?

**Comment by smwyzi** [comment]
this problem can be fixed by add ip version check before a case:
```
if (!TestEnvironment::shouldRunTestForIpVersion(Network::Address::IpVersion::v6)) {
  return;
}
```

for example,  `RouterMatcherHashPolicyTest.HashIpv6DifferentAddresses`  fail on host not supporting IPV6 can be fixed by adding the ip version check before the case:
```
TEST_F(RouterMatcherHashPolicyTest, HashIpv6DifferentAddresses) {
  if (!TestEnvironment::shouldRunTestForIpVersion(Network::Address::IpVersion::v6)) {
    return;
  }
  firstRouteHashPolicy()->mutable_connection_properties()->set_source_ip(true);
  {
    // Different addresses should produce different hashes.
    Network::Address::Ipv6Instance first_ip("2001:0db8:85a3:0000:0000::");
    Network::Address::Ipv6Instance second_ip("::1");
    Http::TestHeaderMapImpl headers = genHeaders("www.lyft.com", "/foo", "GET");
    const auto hash_policy = config().route(headers, 0)->routeEntry()->hashPolicy();
    const uint64_t hash_1 = hash_policy->generateHash(&first_ip, headers, add_cookie_nop_).value();
    const uint64_t hash_2 = hash_policy->generateHash(&second_ip, headers, add_cookie_nop_).value();
    EXPECT_NE(hash_1, hash_2);
  }
  {
    // Same IP addresses but different ports should produce the same hash.
    Network::Address::Ipv6Instance first_ip("1:2:3:4:5::", 8081);
    Network::Address::Ipv6Instance second_ip("1:2:3:4:5::", 1331);
    Http::TestHeaderMapImpl headers = genHeaders("www.lyft.com", "/foo", "GET");
    const auto hash_policy = config().route(headers, 0)->routeEntry()->hashPolicy();
    const uint64_t hash_1 = hash_policy->generateHash(&first_ip, headers, add_cookie_nop_).value();
    const uint64_t hash_2 = hash_policy->generateHash(&second_ip, headers, add_cookie_nop_).value();
    EXPECT_EQ(hash_1, hash_2);
  }
}
```

Is this fix a proper way?
Can I send a pr to fix some cases like this?

**Comment by lizan** [comment]
What is the host environment are you on? That test shouldn't fail unless you have a kernel/system library that disabled IPv6 completely.

The ENVOY_IP_TEST_VERSIONS is to determine the system has an IPv6 address (usually loopback) assigned so integration test can be performed.

**Comment by skilxnTL** [comment]
May be centos 4.3 or 6.3, I guess.

**Comment by smwyzi** [comment]
my host is `CentOS 6.3`, and the Linux kernel version is `3.10.0_3-0-0-27`

**Comment by lizan** [comment]
@smwyzi Thanks, that is beyond the platform we're supporting. Though if you want to patch, use `Network::Address::ipFamilySupported` instead of `TestEnvironment::shouldRunTestForIpVersion`. I believe there are other cases failing your test on CentOS 6 too, no?

**Comment by smwyzi** [comment]
@lizan 
Our product environment is CentOS6, so we must build and test on it :)
Yes, it has about 30 tests failing totally due to the Ipv6 syscall like description above.

Ok, i will try the solution as you say using `TestEnvironment::shouldRunTestForIpVersion`, if it works, i try to give back a patch.
