### ISSUE TITLE
Support for NSS's SSLKEYLOGFILE to be able to decrypt TLS traffic with TLS_ECDHE* ciphers

### ISSUE THREAD

**Issue by argos83** [envoyproxy/envoy#7795]
**Title**: Support for NSS's `SSLKEYLOGFILE` to be able to decrypt TLS traffic with `TLS_ECDHE` ciphers for debugging purposes.

**Description**:
In order to debug issues I often capture traffic to see what requests/responses look like and how they were modified by envoy (e.g. headers added/removed, encodings, etc). For plain-text traffic that's trivial but for TLS troublesome workarounds are needed to decrypt it. (e.g. fake CA's and disable ECDHE cipher suites, or using LD_PRELOAD to hook into functions to gain access to the secrets).

OpenSSL/BoringSSL applications (browsers, curl, etc) often support logging the pre-master secrets into a file by setting the `SSLKEYLOGFILE` environment variable. The logfile can then be easily imported into tools like Wireshark to decrypt TLS on the fly.

In my case I would particularly like to have this on the TLS client side to capture traffic to/from TLS clusters, I'm not sure if this relevant for the cases when envoy acts as TLS server.

**Relevant Links**:

 * OpenSSL's  [SSL_CTX_set_keylog_callback docs](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_keylog_callback.html)
 * Mozilla's [NSS key log format docs](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format)
 * Implementation example in [boringssl client](https://github.com/ljbade/boringssl/blob/master/tool/client.cc#L59)
 * Peter Wu's [presentation slides about TLS decryption](https://sharkfesteurope.wireshark.org/assets/presentations17eu/15.pdf)

**Comment by lizan** [comment]
Would https://www.envoyproxy.io/docs/envoy/latest/operations/traffic_tapping work for you instead for debugging purpose?

**Comment by mattklein123** [comment]
cc @PiotrSikora also

**Comment by PiotrSikora** [comment]
Yeah, I have the same question as @lizan. I'm not a big fan of `SSLKEYLOGFILE` and TAP should work as good for this purpose.

**Comment by argos83** [comment]
Hi! Thanks for the quick response. I wasn't aware of that traffic tapping functionality, I'll give it a try and get back to this issue with more feedback.
Just out of curiosity, what is it that you don't like about `SSLKEYLOGFILE`? I lack a lot of context here, but at first sight seems simpler to implement and maintain than a tapping filter, and it looks simpler as well from a user perspective (setting and ENV var vs generating a different configuration for 'debug' mode)

**Comment by argos83** [comment]
Hi @PiotrSikora and @lizan, I just took a look at the traffic_tapping docs and the tap2pcap tool (just looked at the code, I haven't actually run it).

I was wondering why did you decide to write and maintain this over using existing tools like tcpdump/tshark/wireshark. Some cons I found with tap2pcap are:
  
 -  It seems I need to setup the bazel project to be able to run it (I've never used bazel before 😞), I suppose I could locate the individual python files and install the python dependencies myself but it's still not straightforward.
 -  It seems you can't use that to perform live captures (only converting to pcap offline), while you can just pipe or stream via network a tcpdump live capture to a remote wireshark instance.
 - all the envoy config setup that needs to be written for every cluster or listener you want to capture traffic from (versus setting an env var), it seems more intrusive and I wonder if it could affect the behavior one is trying to debug.

**Comment by lizan** [comment]
>  -  It seems I need to setup the bazel project to be able to run it (I've never used bazel before 😞), I suppose I could locate the individual python files and install the python dependencies myself but it's still not straightforward.
> -  It seems you can't use that to perform live captures (only converting to pcap offline), while you can just pipe or stream via network a tcpdump live capture to a remote wireshark instance.

Thanks, these are very valid tooling improvement request, @htuch. With HTTP tap sink I think we can support live converting to pcap and feed to Wireshark.

>  - all the envoy config setup that needs to be written for every cluster or listener you want to capture traffic from (versus setting an env var), it seems more intrusive and I wonder if it could affect the behavior one is trying to debug.

This is more by design:
a) [Envoy configuration API is machine generation and consumption](machine generation and consumption), so it is management server's responsibility to generate these for every cluster or listener.
b) More flexibility, the configuration API allows you to enable/disable tapping in specific clusters or listeners, without restarting server, so the other sensitive information are not decrypted nor made decrypt-able. An environment var is far from this flexibility.

**Comment by htuch** [comment]
TBH, `tap2pcap` etc. were written initially to support capturing a fuzz corpus, i.e. not with production use in mind. @mattklein123 has done a ton to make this work better with dynamic configuration and streaming. You still need a pipeline to something like Wireshark however. I don't think that needs to live inside Envoy.

**Comment by wenlxie** [comment]
I am new to this. Does `traffic_tapping` support to capture full  L4 fields or just have L7 content?
@htuch  @lizan @mattklein123

**Comment by lizan** [comment]
@wenlxie both, transport socket tap is L4: https://www.envoyproxy.io/docs/envoy/latest/operations/traffic_tapping

**Comment by wenlxie** [comment]
@lizan  Thanks for reply.

I had a try of this feature.
 
1. L4 packets has many dummy field and not have the whole TCP head.
2. L7 has decrypted http contents, but not TLS field. 

`SSLKEYLOGFILE` way can have all of the L4 and L7 fields that can help to debug the issues.  

From our operation experience, these info is really helpful when we debug network issues.

**Comment by Darkest** [comment]
Could you please provide some step-by-step tutorial on how to use traffic tap on ENvoy? 
I have a rather simple case I think: I want to see the TLS traffic going through envoy on port 8080 decrypted.
How can I achieve this?

**Comment by wd** [comment]
I have tried the tap thing. I only can get the encrypted SSL data. It took me 1 hour to set up the environments and get the data converted to pcap files. But finally, I found that these are encrypted data ... Am I missed something or this is what it is supposed to?

**Comment by zhangbo1882** [comment]
@wd you can try https://github.com/envoyproxy/envoy/pull/19182

**Comment by zhangbo1882** [comment]
@Darkest you can try https://github.com/envoyproxy/envoy/pull/19182
