### ISSUE TITLE
Support wildcards in TLS Validation Contexts

### ISSUE THREAD

**Issue by alexkreidler** [envoyproxy/envoy#7813]
Hey, this seems like a big blocker in Envoy for supporting SPIFFE IDs.

If I want to trust my entire trust domain, I'd love to just set
```
verify_subject_alt_name: "spiffe://mydomain.com/*"
```

It seems like there has been a lot of discussion about this but no real progress:

Issues: https://github.com/envoyproxy/envoy/issues/3705, https://github.com/envoyproxy/envoy/issues/3883, https://github.com/envoyproxy/envoy/issues/1272

PRs: https://github.com/envoyproxy/envoy/pull/3858

**Comment by ramaraochavali** [comment]
@mattklein123 @PiotrSikora Would it be OK to support generic StringMatcher support for [verify_subject_alt_name](https://github.com/envoyproxy/envoy/blob/0aed05aecd17576b0dd96f3e4126acd1c24a02bc/api/envoy/api/v2/auth/cert.proto#L268) similar to how we do the [authenticated match](https://github.com/envoyproxy/envoy/blob/a90aefca2c4175e7acc102bc3f810b020c780602/api/envoy/config/rbac/v2/rbac.proto#L179) in RBAC? If that is acceptable, I think it would be most generic and would satisfy most folks.

**Comment by mattklein123** [comment]
Seems fine to me.

**Comment by ramaraochavali** [comment]
Thanks @mattklein123 . If there are no objections to it, I will implement this as we also need this
