### ISSUE TITLE
Native Jaeger Tracing - Bypass agent?

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#7830]
*Title*: *I'm trying to get Envoy's Jaeger Native tracing to work but running into a few issues*

*Description*:
In the example for configuring native Jaeger, (https://github.com/envoyproxy/envoy/tree/c906df39d13dc416c21ea1977cd163f205d61d1c/examples/jaeger-native-tracing)
the reporter and sampler are configured as such:

        sampler:
          type: const
          param: 1
        reporter:
          localAgentHostPort: jaeger:6831

From the jaeger-client-cpp docs (https://github.com/jaegertracing/jaeger-client-cpp) I've gathered that the sampler URL is the Jaeger collector and the reporter is the Jaeger agent (please correct me if that's wrong). 

The current setup of our application makes it not optimal for us to run a local  Jaeger agent in a sidecar, so I'm looking for other solutions.
Some Jaeger clients allow you to bypass the agent and send spans directly to the collector, but I don't see a way to configure that with this client. I've raised an issue in the github for the jaeger client as well, but I was wondering if anyone here has been able to use Jaeger Native tracing with Envoy, and especially without having a local Jaeger agent.

This is one of the configurations I have tried and has not worked (I see the uber-trace-id header being generated and propagated but no pushes to our Jaeger collector)

(we are pushing to a remote Jaeger collector and values are placeholders that are replaced by a script)

        sampler:
          samplingServerURL: "https://@JAEGER_ADDRESS@:@JAEGER_PORT@@COLLECTOR_ENDPOINT@"
          type: const
          param: 1
        reporter:
          logSpans: true
          localAgentHostPort: "@JAEGER_ADDRESS@:@JAEGER_PORT@"

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_native_tracing
https://github.com/envoyproxy/envoy/tree/c906df39d13dc416c21ea1977cd163f205d61d1c/examples/jaeger-native-tracing
https://github.com/jaegertracing/jaeger-client-cpp

**Comment by mattklein123** [comment]
cc @objectiser

**Comment by objectiser** [comment]
@jaegchoi I don't believe the jaeger C++ client supports HTTP currently.

The other option would be to use the zipkin tracer in envoy and direct it to the zipkin endpoint on the jaeger collector?

Another option could be to use the opencensus tracer, with otagent exporter, and then have the opencensus agent export to the jaeger collector - but this would again have an extra level of indirection.

**Comment by jaegchoi** [comment]
> I don't believe the jaeger C++ client supports HTTP currently.
@objectiser Do you mind elaborating on this? Do you mean that the agent only supports UDP right now, so only local agents are allowed?

We already have a working implementation of the zipkin tracer, but we would prefer to use the native jaeger tracer headers (uber-trace-id) if possible

**Comment by objectiser** [comment]
@jaegchoi The Jaeger C++ client, that is used inside the envoy proxy, currently only supports UDP - and therefore can only communicate with the Jaeger agent. The Jaeger agent would then use HTTP to communicate with the collector. So it is not possible for the Jaeger C++ client to be configured to communicate directly with the Jaeger collector.

So until the C++client supports HTTP directly, your only option will be to use the Jaeger agent.

If you use the `all-in-one` component at the backend, then the agent and collector are co-located, so may help with your scenario - however the agent is intended to be located as close to the client, as UDP is less reliable.
