### ISSUE TITLE
gRPC change needs to be integrated so that Envoy keeps working with Bazel 0.29

### ISSUE THREAD

**Issue by lberki** [envoyproxy/envoy#7835]
Bazel 0.29 reshuffled protocol buffers slightly and it broke gRPC which tried to guess what Bazel does. The Bazel bug is here:

https://github.com/bazelbuild/bazel/issues/9032

The pull request to gRPC to fix it:

https://github.com/grpc/grpc/pull/19860

however, it'll need to be integrated into Envoy so that Envoy keeps working.

**Comment by mattklein123** [comment]
cc @keith @lizan

**Comment by keith** [comment]
I'd be happy to update once that change merges. Is there going to be a release with it? (I assume no)

**Comment by lberki** [comment]
Dunno... ask the gRPC folks.

**Comment by lizan** [comment]
OK, at least we have a patch when we upgrade our Bazel. We're already in bazelisk so there are less chance to break CI widely when updating build image.

**Comment by mattklein123** [comment]
Fixed
