### ISSUE TITLE
xds: omit node in subsequent discovery requests in the gRPC call

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#7860]
xDS requests include a node proto with an arbitrarily large metadata field. This causes a problem if this metadata is a large JSON since it is sent for every EDS request. The proposal is to omit `node` field in a gRPC stream after the first request. Most gRPC servers can save some state per stream, so they can store the node in the local scope. In fact, this optimization is already applied for ALS and metrics services, so it seems like a gap in xDS.

cc @htuch

**Comment by htuch** [comment]
Yes, this should be done if we're not already. I thought we were already doing this.

**Comment by kyessenov** [comment]
I'm pretty sure it's not happening right now. Taking a cursory look at go-control-plane, I see that it does not cache Node from the first request, but it still works. More importantly, this is under-specified in xDS specification.
