### ISSUE TITLE
new filter xx.pb.h file not found

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#7862]
i put the http-filter-example  directory  in the /source/extensions/filters/http/ ,and i compile it with "ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release" .i add this new filter in well_known_names.h.
i change the BUILD in http-filter-example as follows:package(default_visibility = ["//visibility:public"])

load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_cc_binary",
    "envoy_cc_library",
)

load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library")

api_proto_library(
    name = "http_filter_proto",
    srcs = ["http_filter.proto"]
)

envoy_cc_library(
    name = "http_filter_lib",
    srcs = ["http_filter.cc"],
    hdrs = ["http_filter.h"],
    deps = [
        ":http_filter_proto_cc",
        "//include/envoy/server:filter_config_interface",
    ],
)

envoy_cc_library(
    name = "http_filter_config",
    srcs = ["http_filter_config.cc"],
    deps = [
        ":http_filter_lib",
        "//include/envoy/registry",
        "//source/extensions/filters/http:well_known_names",

    ],
)

At last, the error is 
ERROR: /source/source/extensions/filters/http/http-filter-example/BUILD:18:1: C++ compilation of rule '//source/extensions/filters/http/http-filter-example:http_filter_lib' failed (Exit 1)
In file included from source/extensions/filters/http/http-filter-example/http_filter.cc:3:
source/extensions/filters/http/http-filter-example/http_filter.h:7:10: fatal error: 'http-filter-example/http_filter.pb.h' file not found

what should i do?and what else files should i change?thanks a lot.

**Comment by dio** [comment]
Assuming you put it inside the following folder, 

```
├── source
│   ├── extensions
│   │   ├── filters
│   │   │   ├── http
│   │   │   │   ├── example
│   │   │   │   │   ├── BUILD
│   │   │   │   │   ├── http_filter.cc
│   │   │   │   │   ├── http_filter.h
│   │   │   │   │   ├── http_filter.proto
│   │   │   │   │   ├── http_filter_config.cc
...
```

You need to change:

```cpp
#include "http-filter-example/http_filter.pb.h"
#include "http-filter-example/http_filter.pb.validate.h"
```

to:

```cpp
#include "source/extensions/filters/http/example/http_filter.pb.h"
#include "source/extensions/filters/http/example/http_filter.pb.validate.h"
```

**Comment by hbgongen** [comment]
> Assuming you put it inside the following folder,
> 
> ```
> ├── source
> │   ├── extensions
> │   │   ├── filters
> │   │   │   ├── http
> │   │   │   │   ├── example
> │   │   │   │   │   ├── BUILD
> │   │   │   │   │   ├── http_filter.cc
> │   │   │   │   │   ├── http_filter.h
> │   │   │   │   │   ├── http_filter.proto
> │   │   │   │   │   ├── http_filter_config.cc
> ...
> ```
> 
> You need to change:
> 
> ```c++
> #include "http-filter-example/http_filter.pb.h"
> #include "http-filter-example/http_filter.pb.validate.h"
> ```
> 
> to:
> 
> ```c++
> #include "source/extensions/filters/http/example/http_filter.pb.h"
> #include "source/extensions/filters/http/example/http_filter.pb.validate.h"
> ```

oh, thanks,i alter what you say.now i find it also has some errors:ERROR: /source/source/extensions/filters/http/http-filter-example/BUILD:17:1: undeclared inclusion(s) in rule '//source/extensions/filters/http/http-filter-example:http_filter_lib':
this rule is missing dependency declarations for the following files included by 'source/extensions/filters/http/http-filter-example/http_filter.cc':
'source/extensions/filters/http/http-filter-example/http_filter.h'
'source/extensions/filters/http/http-filter-example/http_filter.pb.h'

please help me see my BUILD:

package(default_visibility = ["//visibility:public"])

load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_cc_binary",
    "envoy_cc_library",
)

load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library")


api_proto_library(
    name = "http_filter_proto",
    srcs = ["http_filter.proto"]
)

envoy_cc_library(
    name = "http_filter_lib",
    srcs = ["http_filter.cc"],
    hdrs = ["http_filter.h"],
    deps = [
        ":http_filter_proto_cc",
        "//include/envoy/server:filter_config_interface",
    ],
)

envoy_cc_library(
    name = "http_filter_config",
    srcs = ["http_filter_config.cc"],
    deps = [
        ":http_filter_lib",
        "//include/envoy/registry",
        "//source/extensions/filters/http:well_known_names",

    ],
)

**Comment by dio** [comment]
@hbgongen please take a look at this commit: https://github.com/dio/envoy/commit/88ec949529711df13d0d713daebef9a0006c7d06. Hope this helps.

**Comment by hbgongen** [comment]
Thanks a lot. I'll try it.@dio

**Comment by wangfakang** [comment]
> @hbgongen please take a look at this commit: [dio@88ec949](https://github.com/dio/envoy/commit/88ec949529711df13d0d713daebef9a0006c7d06). Hope this helps.

@dio this commit does not run correctly on the current master branch, could you adapte it?
