### ISSUE TITLE
Integrate gRPC Starlark changes to keep Envoy working with Bazel 1.0

### ISSUE THREAD

**Issue by lberki** [envoyproxy/envoy#7863]
Bazel 1.0 will remove the legacy `.proto.` provider to access information about protocol buffers and only allow`[ProtoInfo]`.

These got fixed in gRPC in ecf04ccf4d8be9378166ec9e0ccf44081e211d11 and 49f0fb9035120d0f5b5fa49846324c0b2d59c257, but gRPC needs to be updated in Envoy so that they take effect.

In the meantime, I sent out https://github.com/grpc/grpc/pull/19860 as a workaround.

Note that this issue has a sister issue https://github.com/envoyproxy/envoy/issues/7835, which deals with a slightly changed directory layout in 0.29 (however, that one is breakage in Bazel 0.29 and this one is breakage in Bazel 1.0)

**Comment by mattklein123** [comment]
Fixed
