### ISSUE TITLE
TCP proxy weighted balancing

### ISSUE THREAD

**Issue by Lookyan** [envoyproxy/envoy#7866]
*Title*: *TCP proxy weighted balancing*

*Description*:

I want to achieve weighted load balancing inside one envoy cluster to several endpoint groups.
My management server provides following information to envoy:
```
resources: <
  [type.googleapis.com/envoy.api.v2.ClusterLoadAssignment]: <
    cluster_name: "payments/payments"
    endpoints: <
      lb_endpoints: <
        endpoint: <
          address: <
            socket_address: <
              address: "172.17.0.5"
              port_value: 80
            >
          >
        >
      >
      load_balancing_weight: <
        value: 30
      >
    >
    endpoints: <
      lb_endpoints: <
        endpoint: <
          address: <
            socket_address: <
              address: "172.17.0.2"
              port_value: 80
            >
          >
        >
      >
      lb_endpoints: <
        endpoint: <
          address: <
            socket_address: <
              address: "172.17.0.6"
              port_value: 80
            >
          >
        >
      >
      lb_endpoints: <
        endpoint: <
          address: <
            socket_address: <
              address: "172.17.0.8"
              port_value: 80
            >
          >
        >
      >
      load_balancing_weight: <
        value: 70
      >
    >
  >
>
```

Then it is used in tcp proxy cluster (everything is provided using management server).

*Description*:
I use it in original dst listener and expect that load will be balanced according to load balancing weights. Cluster is configured with ROUND_ROBIN strategy.
It also worths saying that I don't specify any locality information to these endpoints because for now they are located in the same location.

*Repro steps*:
Run envoy with one cluster, listener and CLA assigned to this cluster with two endpoint groups with different weights. 
Then create HTTP load without keepalive feature.
Load will be distributed in a round robin way.

Is it supposed to balance connections according to load_balancing_weight parameters in CLA endpoints elements or I should follow another approach?

**Comment by mattklein123** [comment]
original_dst is special and I suspect this won't work but I'm not sure. cc @snowp @jrajahalme

**Comment by snowp** [comment]
You might be missing the https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster-commonlbconfig-localityweightedlbconfig config option on the cluster that enables per locality weighting, as well as locality information (https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/endpoint/endpoint.proto#envoy-api-msg-endpoint-localitylbendpoints) so that Envoy can distinguish the different sets of endpoints

**Comment by Lookyan** [comment]
Unfortunately even with localityweightedlbconfig option enabled it doesn't take any effect for weighted balancing. Envoy uses round robin algorithm for balancing. Only with weights assigned to each endpoint (IP address) it starts working properly.
And what's interesting I can't see these weights in envoy admin interface. Maybe it's not included in admin layout.
