### ISSUE TITLE
named filter chains

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#7870]
It would be good from a stats perspective to have names for the filter chains so that users can easily see how many connections matched on a specific filter chain match [say by SNI or ips]. From a FCDS perspective, adding names is also helpful as we can now tender filterchain resources as named objects, spit out informative errors for specific filter chains, etc. 

cc @silentdai ..

**Comment by rshriram** [comment]
I think this has some relation to #7867 in that we need several objects in the API to be named. Even if we dont use the names immediately now, its still useful to ship with one so that we can start taking advantage of it over time.

**Comment by rshriram** [comment]
cc @envoyproxy/api-shepherds

**Comment by mattklein123** [comment]
> I think this has some relation to #7867 in that we need several objects in the API to be named. Even if we dont use the names immediately now, its still useful to ship with one so that we can start taking advantage of it over time.

Yes this is top of mind for v3. We need to figure out a way to do this so that simple configs don't get bogged down but we give advanced configs flexibility. cc @htuch

**Comment by rshriram** [comment]
is it possible to add this to existing filterChains as it currently has no name field.

**Comment by silentdai** [comment]
My 2 cents: we can add the name in current filter chain.
Soon the FCDS need the filter chain name anyway. By then the name uniqueness will be required.
