### ISSUE TITLE
Redact secrets in LDS/CDS config dump.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#7873]
Redact secrets (i.e. TLS private keys and passwords) in LDS/CDS config dump.

Those secrets are already redacted in SDS config dump (see: #7365), but not in LDS/CDS.

cc @incfly @JimmyCYJ

**Comment by lizan** [comment]
related: https://github.com/envoyproxy/envoy/issues/4757

**Comment by PiotrSikora** [comment]
Fixed in #9315.
