### ISSUE TITLE
File Transfer using Envoy's GRPC-JSON transcoder

### ISSUE THREAD

**Issue by vaibhav-gupta-grab** [envoyproxy/envoy#7893]
*Description*:
I am trying to get my HTML form to talk with a back-end (GRPC + Envoy proxy) service by sending POST requests with application/json content-type. This seems to working fine till now, but now I want to send an image to the GRPC service from the HTML form (on browser). GRPC services can accept file transfer with protobuf type `bytes`. But does Envoy's GRPC-JSON transcoder support file transfer? I don't think Envoy grpc-json filter supports multipart/form-data requests. Any other way forward?

**Comment by lizan** [comment]
Currently there is no good way to do this other than setting up a plain HTTP endpoint. It may be possible once we have: https://github.com/envoyproxy/envoy/issues/7007
