### ISSUE TITLE
`bazel test` should exclude all blacklisted extensions/dependencies

### ISSUE THREAD

**Issue by achasveachas** [envoyproxy/envoy#7903]
*Title*: *`bazel test` should exclude all blacklisted extensions/dependencies*

*Description*:
Currently we are excluding blacklisted dependencies using the logic in [extensions_build_system.bzl](https://github.com/envoyproxy/envoy/blob/master/test/extensions/extensions_build_system.bzl), the functions in this file get invoked in the individual `BUILD` files and they get mad if the excluded extension doesn't exist in `EXTENSIONS` (which should have been `WINDOWS_EXTENSIONS` in the windows case), and excluding `PPC_SKIP_TARGETS` and NOBORINGSSL_SKIP_TARGETS` in those cases. 

Ideally we would want to construct a unified `EXTENSIONS` based on blacklists well before evaluating the `BUILD` files.

[optional *Relevant Links*:]
[Slack Discussion](https://envoyproxy.slack.com/archives/C7E6C71QB/p1565722180041200)

CC: @wrowe @lizan

**Comment by lizan** [comment]
Here is some pointer:

We do load default envoy_config [here](https://github.com/envoyproxy/envoy/blob/v1.11.1/bazel/repositories.bzl#L38) to provide `@envoy_build_config//:extensions_build_config.bzl` which defaults to `@envoy//source/extensions:extensions_build_config.bzl`. With the [repository_ctx](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#os) there you can conditionally load different bzl files as `extensions_build_config.bzl`. See `_is_linux` function in `repositories.bzl`.

@wrowe @achasveachas Do you want to take a stab?

**Comment by wrowe** [comment]
Note our confusion spawned from the following;

$ bazel test //test/...

This will build all tests, as pointed out by lizan during a community meeting.

Can you help us identify the "top level test" we should be invoking to observe all included and
excluded //source/... elements given the desired target //source/exe:envoy-static

**Comment by wrowe** [comment]
Ping @lizan 

We understand that one top level test that can be performed is;
  //test/exe:envoy-static

What we remain unclear on is what is the typical top-level test-all target which can be expected to run for only included and none of the excluded extensions, etc?

**Comment by lizan** [comment]
I guess the issue is some integration test is not using extension test but actually relying on extensions. I think we need refactor envoy_cc_test a bit to specify a list of extensions that the test requires, and no-op them if extensions doesn't exist.

**Comment by wrowe** [comment]
Confirming that this remains a sore point, we killed off WINDOWS_EXTENSIONS, but the extension_cc_test is still not looking at the platform's /exclusion/ list.

**Comment by mattklein123** [comment]
I think this is largely fixed. If not we can track specific issues.
