### ISSUE TITLE
Help needed in setting up envoy.metrics_service for stats_sinks

### ISSUE THREAD

**Issue by budanm** [envoyproxy/envoy#7910]
Help needed in setting up envoy.metrics_service

*Description*:

- I am trying to set up the envoy stats_sinks using envoy.metrics_service as it is one of the supported stats_sink in envoy. [envoy metric service](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/metrics_service.proto#envoy-api-msg-config-metrics-v2-metricsserviceconfig)

- All I am trying to verify is when I fire an endpoint call via envoy proxy , the metrics server grpc endpoint ( StreamMetrics(mtserver ms.MetricsService_StreamMetricsServer) error ) should be
fired. I am just logging something in inside that function.

- I am running this setup as part of docker-compose where one container is running the envoy and the other container is running the grpc go service implemention for envoy metric service

- I have created a grpc client separately to test this endpoint locally and it works . 

- However when i run it as part of docker-compose it does not work , I am expecting envoy already has an inbuilt client for this grpc metric service which fires the call for streaming the metrics each time it gets generated

Below are the code snippets

- **Envoy yaml**

`stats_sinks:
  - name: envoy.metrics_service
    config:
      grpc_service:
        envoy_grpc:
          cluster_name: metricsservice
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.google.com
                  cluster: service_google
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
    tls_context:
      sni: www.google.com
  - name: metricsservice
    connect_timeout: "0.25s"
    type: "strict_dns"
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: metricsservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: metricsservice
                port_value: 50052`

- **GRPC Service Implementation for envoy metrics service**

`package main

import (
	"log"
	"net"

	ms "github.com/envoyproxy/go-control-plane/envoy/service/metrics/v2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

type server struct {
}

func (s *server) StreamMetrics(mtserver ms.MetricsService_StreamMetricsServer) error {

	log.Println("Inside metrics service log")
	// if mtserver != nil {
	// 	log.Println(mtserver.Context())
	// }
	return nil
}

func main() {

	// create a TCP listener on port 50052
	lis, err := net.Listen("tcp", ":50052")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	log.Printf("listening on %s", lis.Addr())

	s := grpc.NewServer()
	ms.RegisterMetricsServiceServer(s, &server{})
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}

}
`

- **Docker-compose yaml**

`version: "3.7"
services:

  edge-envoy:
    build:
      context: ./edge-envoy
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "9901:9901"
      - "10000:10000"

  metricsservice:
    build:
      context: ./metricsservice
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - metricsservice
    ports: 
      - "50052:50052"

networks:
  envoymesh: {}`

- **Dockerfile for envoy**

`FROM envoyproxy/envoy-dev:7b0ce0d32a9b584626e8c16b5ae07817eade322d
COPY envoy.yaml /etc/envoy/envoy.yaml`

- **Dockerfile for grpc metric service**
`FROM golang:latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .
EXPOSE 50052
CMD ["./main"]`

Please let me know if I am missed anything . I just want the grpc endpoint to work . Also if possible some documentation regarding consumption would be helpful

**Comment by lizan** [comment]
At a quick glance looks like you missed `http2_protocol_options: {}` from your metricsservice cluster to enable gRPC.

If that doesn't work, can you publish your reproducer to a git repo or gist so it is easier to try?

**Comment by budanm** [comment]
> Help needed in setting up envoy.metrics_service
> 
> _Description_:
> 
> * I am trying to set up the envoy stats_sinks using envoy.metrics_service as it is one of the supported stats_sink in envoy. [envoy metric service](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/metrics_service.proto#envoy-api-msg-config-metrics-v2-metricsserviceconfig)
> * All I am trying to verify is when I fire an endpoint call via envoy proxy , the metrics server grpc endpoint ( StreamMetrics(mtserver ms.MetricsService_StreamMetricsServer) error ) should be
>   fired. I am just logging something in inside that function.
> * I am running this setup as part of docker-compose where one container is running the envoy and the other container is running the grpc go service implemention for envoy metric service
> * I have created a grpc client separately to test this endpoint locally and it works .
> * However when i run it as part of docker-compose it does not work , I am expecting envoy already has an inbuilt client for this grpc metric service which fires the call for streaming the metrics each time it gets generated
> 
> Below are the code snippets
> 
> * **Envoy yaml**
> 
> `stats_sinks:
> 
> * name: envoy.metrics_service
>   config:
>   grpc_service:
>   envoy_grpc:
>   cluster_name: metricsservice
>   admin:
>   access_log_path: /tmp/admin_access.log
>   address:
>   socket_address:
>   protocol: TCP
>   address: 0.0.0.0
>   port_value: 9901
>   static_resources:
>   listeners:
> * name: listener_0
>   address:
>   socket_address:
>   protocol: TCP
>   address: 0.0.0.0
>   port_value: 10000
>   filter_chains:
>   
>   * filters:
>     
>     * name: envoy.http_connection_manager
>       typed_config:
>       "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
>       stat_prefix: ingress_http
>       route_config:
>       name: local_route
>       virtual_hosts:
>       - name: local_service
>       domains: ["*"]
>       routes:
>       - match:
>       prefix: "/"
>       route:
>       host_rewrite: [www.google.com](http://www.google.com)
>       cluster: service_google
>       http_filters:
>       
>       * name: envoy.router
>         clusters:
> * name: service_google
>   connect_timeout: 0.25s
>   type: LOGICAL_DNS
>   dns_lookup_family: V4_ONLY
>   lb_policy: ROUND_ROBIN
>   load_assignment:
>   cluster_name: service_google
>   endpoints:
>   
>   * lb_endpoints:
>     
>     * endpoint:
>       address:
>       socket_address:
>       address: [www.google.com](http://www.google.com)
>       port_value: 443
>       tls_context:
>       sni: [www.google.com](http://www.google.com)
> * name: metricsservice
>   connect_timeout: "0.25s"
>   type: "strict_dns"
>   lb_policy: ROUND_ROBIN
>   load_assignment:
>   cluster_name: metricsservice
>   endpoints:
>   
>   * lb_endpoints:
>     
>     * endpoint:
>       address:
>       socket_address:
>       address: metricsservice
>       port_value: 50052`
> * **GRPC Service Implementation for envoy metrics service**
> 
> `package main
> 
> import (
> "log"
> "net"
> 
> ```
> ms "github.com/envoyproxy/go-control-plane/envoy/service/metrics/v2"
> "google.golang.org/grpc"
> "google.golang.org/grpc/reflection"
> ```
> 
> )
> 
> type server struct {
> }
> 
> func (s *server) StreamMetrics(mtserver ms.MetricsService_StreamMetricsServer) error {
> 
> ```
> log.Println("Inside metrics service log")
> // if mtserver != nil {
> // 	log.Println(mtserver.Context())
> // }
> return nil
> ```
> 
> }
> 
> func main() {
> 
> ```
> // create a TCP listener on port 50052
> lis, err := net.Listen("tcp", ":50052")
> if err != nil {
> 	log.Fatalf("failed to listen: %v", err)
> }
> log.Printf("listening on %s", lis.Addr())
> 
> s := grpc.NewServer()
> ms.RegisterMetricsServiceServer(s, &server{})
> reflection.Register(s)
> if err := s.Serve(lis); err != nil {
> 	log.Fatalf("failed to serve: %v", err)
> }
> ```
> 
> }
> `
> 
> * **Docker-compose yaml**
> 
> `version: "3.7"
> services:
> 
> edge-envoy:
> build:
> context: ./edge-envoy
> dockerfile: Dockerfile
> networks:
> - envoymesh
> ports:
> - "9901:9901"
> - "10000:10000"
> 
> metricsservice:
> build:
> context: ./metricsservice
> dockerfile: Dockerfile
> networks:
> envoymesh:
> aliases:
> - metricsservice
> ports:
> - "50052:50052"
> 
> networks:
> envoymesh: {}`
> 
> * **Dockerfile for envoy**
> 
> `FROM envoyproxy/envoy-dev:7b0ce0d32a9b584626e8c16b5ae07817eade322d COPY envoy.yaml /etc/envoy/envoy.yaml`
> 
> * **Dockerfile for grpc metric service**
>   `FROM golang:latest WORKDIR /app COPY go.mod go.sum ./ RUN go mod download COPY . . RUN go build -o main . EXPOSE 50052 CMD ["./main"]`
> 
> Please let me know if I am missed anything . I just want the grpc endpoint to work . Also if possible some documentation regarding consumption would be helpful



> At a quick glance looks like you missed `http2_protocol_options: {}` from your metricsservice cluster to enable gRPC.
> 
> If that doesn't work, can you publish your reproducer to a git repo or gist so it is easier to try?

Ok will try that now , and if it does not work then will upload it to a git

**Comment by budanm** [comment]
hi @lizan 
Thanks a lot for the help, at least it is hitting the grpc service and the logs are getting printed. However, it would really help if you can provide me with some concrete example as to how do we use it. I have seen the pb.go definition of envoy metrics service on the envoy control-plane git and it does not help much.

Regards
Soumya

**Comment by lizan** [comment]
Those are generated file from proto so not much info there. The only open-source MetricsService implementation I can find now is in Apache SkyWalking, it is in Java though might be helpful for you: https://github.com/apache/skywalking/blob/master/oap-server/server-receiver-plugin/envoy-metrics-receiver-plugin/src/main/java/org/apache/skywalking/oap/server/receiver/envoy/MetricServiceGRPCHandler.java

**Comment by budanm** [comment]
Thanks @lizan 
It's okay I will figure it out. 
I am new to envoy and hence whatever scenarios I am able to achieve with Envoy, I am documenting it with an easy to understand code. I have already created two repositories [Envoy as Load Balancer](https://github.com/budanm/EnvoyLoadBalancer) and [Achieving 2way SSL with Envoy](https://github.com/budanm/Envoy-With-2way-SSL).
I would try to create a simple example with the metrics service stats sink and share the example on Github. You can close the issue and thanks again for the help :)
