### ISSUE TITLE
HCM: support connection level logging

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7917]
In the wake of the last set of CVEs it became obvious that there are certain cases in which we need connection level logging for the HTTP connection manager. This can be similar to what we do for tcp_proxy and configured with all the same set of filters, sinks, etc. The idea here would be to indicate certain security conditions as part of StreamInfo (e.g., flooding), and then allow those conditions to be filtered on, sampled, etc. The goal here is to replace https://github.com/envoyproxy/envoy/commit/f2129cbfeff3b206fb5d00bbae06049a4a21383e with something more robust.

**Comment by kyessenov** [comment]
A few other use cases for listener-level access logs:
1. custom network filters (direct_response, echo, etc)
2. HCM unable to parse the requests.

A few things that would need for feature completeness:
1. StreamInfo needs some indicator for protocol/filter handling (for filtering)
2. propagate data to connection stream info from protocol handlers, and other extensions

**Comment by kyessenov** [comment]
Please take a look at the associated PR for the approach. It seems to work (tested with `nc` to HCM) but it needs more work to populate the stream info and fix up the tests.

**Comment by mattklein123** [comment]
@kyessenov after the last PR can we call this done or do you have more to do? Thank you for your work on this!

**Comment by kyessenov** [comment]
I am working on adding protocol set strings to complete it: #10487 .

**Comment by kyessenov** [comment]
We can close this after #10622  and #10627 get in. I think with those, it is pretty functional.

**Comment by mattklein123** [comment]
@kyessenov can we call this done or is there more to do here?

**Comment by kyessenov** [comment]
Sorry, this is mostly done. The only missing piece is shared filter state at the connection level in https://github.com/envoyproxy/envoy/pull/10622. That PR died to due to neglect, but I can resurrect it.

**Comment by kyessenov** [comment]
Thanks for @snowp finishing https://github.com/envoyproxy/envoy/pull/11787. I think this can be closed now.

**Comment by snowp** [comment]
Thanks!
