### ISSUE TITLE
Support doPeek() and size bounded doRead() in TransportSocket API

### ISSUE THREAD

**Issue by AndresGuedez** [envoyproxy/envoy#7935]
Currently, the TransportSocket API only allows [unbounded reads](https://github.com/envoyproxy/envoy/blob/master/include/envoy/network/transport_socket.h#L129) from the underlying socket, via ` virtual IoResult doRead(Buffer::Instance& buffer) PURE;`.

There are use cases that require being able to peek and then drain the socket via a size bounded read.

I propose extending the API to support both of these requirements as follows:

```
/**
 * Read data, up to a specified upper bound, from the underlying socket into a buffer.
 * @param buffer supplies the buffer to read into.
 * @param read_limit an upper bound on the number of bytes to read into the buffer.
 * @return IoResult the result of the read action.
*/
virtual IoResult doBoundedRead(Buffer::Instance& buffer, size_t read_limit) PURE;

/**
 * Peek data, up to a specified upper bound, from the underlying socket into a buffer.
 * @param buffer supplies the buffer to peek into.
 * @param peek_limit an upper bound on the number of bytes to peek into the buffer.
 * @return IoResult the result of the peek action.
*/
virtual IoResult doBoundedPeek(Buffer::Instance& buffer, size_t peek_limit) PURE;

/* Unbounded peek, behaves similar to doRead(). */
virtual IoResult doPeek(Buffer::Instance& buffer) PURE;
```

The proposal involves extending the API as opposed to modifying the existing function calls, as it seems more readable at the call site to issue a `doBounded*()` call than e.g., `doRead(buffer, /*read_limit=*/0)` to maintain the existing semantics where implementations are free to read in arbitrary sized chunks until `callbacks_->shouldDrainReadBuffer()` is true.

**Comment by lizan** [comment]
@AndresGuedez this API sounds reasonable, do you have plan to migrate existing doRead calls from ConnectionImpl to doRoundedRead/Peak? I'm wondering how the next read event will be triggered if the read is bound.

**Comment by AndresGuedez** [comment]
> @AndresGuedez this API sounds reasonable, do you have plan to migrate existing doRead calls from ConnectionImpl to doRoundedRead/Peak? I'm wondering how the next read event will be triggered if the read is bound.

There is no need to migrate `ConnectionImpl` to bounded reads at the moment, so I am not planning to do that as part of the API enhancement.

**Comment by lizan** [comment]
Then what is the real user for that API other than mock/tests? Do you plan to add another component that use it, or a wrapping transport socket (like tap)?

**Comment by AndresGuedez** [comment]
> Then what is the real user for that API other than mock/tests? Do you plan to add another component that use it, or a wrapping transport socket (like tap)?

We have a wrapping transport socket at Google which requires this API.
