### ISSUE TITLE
[config] /config_dump shows rejected RDS config vs the last valid RDS config envoy is running

### ISSUE THREAD

**Issue by lita** [envoyproxy/envoy#7939]
*config*: */config_dump shows rejected RDS config vs the last valid RDS config envoy is running*

*Description*:
When triaging an invalid RDS config on our fleet, /config_dump showed the version sha of the bad config, rather than version sha envoy was running (which was the last valid configuration). So when a new box came up that was not able to serve traffic, config_dump showed the same sha, making it very difficult to debug. 

We ended up realizing RDS was being rejected via startup logs and update_rejected stat. But we should have solved it faster of config_dump showed the last valid version sha.

*Repro steps*:
Have the control plane send RDS config with a duplicate domain.

*Logs*:
```
[2019-08-13 22:21:07.185][31248][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:72] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain maptiles-staging.lyft.net
```

**Comment by mattklein123** [comment]
cc @htuch this is the issue I was chatting with you about. We can look but this regressed either as part of the VHDS or SRDS work. The fundamental issue is we are calling `onRdsUpdate` which updates config dump info before the config update itself might fail. We have to break this logic apart and only update the applied config if it actually succeeds.

**Comment by htuch** [comment]
I think this is https://github.com/envoyproxy/envoy/pull/3960 @lizan

**Comment by lizan** [comment]
@htuch You're right #3960 is the regression point. Will take a look on a fix.
