### ISSUE TITLE
Question: How do I determine what deprecated features I am using?

### ISSUE THREAD

**Issue by frasercobb** [envoyproxy/envoy#7945]
*Title*: How do I determine what deprecated features I am using?

Envoy version: Varies as we rollout between 1.10.0, 1.11.0, 1.11.1

*Description*:
We have envoy instances emitting the `envoy.runtime.deprecated_feature_use` metric but I am unable to figure out what features we are using that are deprecated.

The breaking change policy mentions the following:

> during the first release cycle after a feature has been deprecated, use of that feature will cause a logged warning, and incrementing the runtime runtime.deprecated_feature_use stat.

However, I am unable to see these logs. These envoys are using the INFO log level.

*How I tried to figure this out:*
1. Compare the deprecation log with our config.
2. Run envoy locally with debug log level and attempt to use a deprecated feature.
3. View the logs of all envoys deployed for any mention of deprecated.

*Questions:*
1. At what log level can I expect to see the logged warning on use of a deprecated feature?
2. How do you expect people to go from `runtime.deprecated_feature_use` to the specific feature that is deprecated?

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated.html
- https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/deprecated.rst

**Comment by mattklein123** [comment]
You should see WARN logs for every deprecated feature you are using: https://github.com/envoyproxy/envoy/blob/cb15cc3d2010aff77d6e022ddf6d723fa8becbc0/source/common/protobuf/utility.cc#L199

It's possible there is some path that is not warning correctly, but we might need more info to debug. cc @alyssawilk who worked on this awesome feature!

**Comment by ramaraochavali** [comment]
Would it be good to have a stat around this so that we do not have to grep through fleet of Envoys?

**Comment by mattklein123** [comment]
@ramaraochavali there is a stat already?

**Comment by ramaraochavali** [comment]
@mattklein123 Ok. Cool. Did not check the stat.

**Comment by alyssawilk** [comment]
Yeah, it should be in warning logs.   I'll add that to the docs for runtime.rst as it's been asked once or twice.

It would be lovely if there were a stat per deprecated feature but I'm not sure if that'd be too expensive.  Internally our equivalent used power of two backoff on both logs and stats and I don't think Envoy has that equivalent yet

**Comment by alyssawilk** [comment]
So I think now that the stat points to the log messages (and gives you something to grep for).

The logs both point to the deprecation docs (https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated) which say how proto field X is replaced by proto field Y, and also to the runtime overrides ("using runtime overrides for deprecated features") for temporary workarounds.  Is there anything else you think we can do to make this easier / more informative?

**Comment by frasercobb** [comment]
Thanks for clarifying. 
We are not seeing any log messages from envoy containing the word "deprecated". I determined this by looking for envoy instances that are consistently outputting the `envoy.runtime.deprecated_feature_use` metric and searching the logs.

Is it possible that there are code paths that send the metric but do not log?

Some more specifics:
* all envoys are statically configured via json file.
* the envoys that are sending the most of these metrics seem to be starting envoy more than others. i.e. It seems that this metric is emitted on startup of envoy.

If it helps, I can send you an example of the static config we use. I would prefer to send this via a private channel if possible.

**Comment by frasercobb** [comment]
I did some further digging and found that the instances on envoy 1.11 and higher were not sending this stat. I have confirmed this locally using our config with the three versions I mentioned earlier. **Only version 1.10.0 emitted this deprecated metric.**

It seems that this was caused by this bug you mention.

Thank you for taking the time.
