### ISSUE TITLE
HTTP 200 infers GrpcStatus::Unknown in access log filter

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#7954]
When filtering traffic that contains both REST and Grpc messages, the access log filter's behavior of inferring `GrpcStatus::Unknown` from `HTTP 200 OK` seems wrong, as it will capture all successful REST traffic.  

https://github.com/envoyproxy/envoy/blob/74e348720af8d157bbdb00b629ac7c6022606fc8/source/common/access_log/access_log_impl.cc#L237-L239

It looks like the implementer expected the Grpc utility to return `nullopt` if there wasn't a clear translation from HTTP to Grpc status. I'd recommend the utility call be wrapped to behave that way.

**Comment by kb000** [comment]
@lita @adilhafeez

**Comment by mattklein123** [comment]
Agreed I think this is a bug. cc @crockeo who originally did this feature. cc @snowp @dio also.

**Comment by snowp** [comment]
The 200 -> UNKNOWN mapping is what gRPC suggests: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md but we should probably not be trying to infer a gRPC code for non-gRPC responses?

**Comment by lita** [comment]
Yeah if there was a setting or a way to not log if the header/trailer doesn't exist, that would be ideal.

**Comment by lizan** [comment]
@snowp is right and it is what gRPC suggests.

You can combine the  `GrpcStatusFilter` (which is questioned here) and `HeaderFilter` with `content-type` to be `application/grpc` to get log of gRPC part, and then the inverted `HeaderFilter` for the REST part?

**Comment by mattklein123** [comment]
Thanks @lizan and @snowp it looks like there is a workaround here. @kb000 if there are any doc updates that would have helped you here PRs super appreciated.
