### ISSUE TITLE
Prometheus: allow opting out of automatic namspacing

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#7957]
*Title*: *Prometheus: allow opting out of automatic namespacing*

*Description*:
PR #2140 added automatic namspacing to all prometheus metrics emitted by envoy per prometheus best practices.

A constant string `envoy_` is prepended to the prometheus metric names, with no way to override or opt out of the namespacing.

As filters add more metrics, they may be namespaced under a different prefix. For example istio would like some filter emitted metrics to be namespaced under `istio_` prefix.
 
Options
1.  Add a convention: example: If a metrics name starts with `_` or some other marker, automatic namspacing will be disabled for that metric. 
2.  Add this option to admin config. 
    a. Add regex list to indicate metric names that would opt out of prometheus automatic namespacing.
    b. Get this config to admin.cc. At present prometheus formatter receives no config.

@ggreenway  @jmarantz

**Comment by mattklein123** [comment]
FWIW I would opt for (2)

**Comment by mandarjog** [comment]
The challenge with admin config is that it forces us to update bootstrap.
This means any new filter injected thru wasm will need to have bootstrap updated in lockstep. It is possible though to use (2) to specify (1) and then all dynamically loaded filters continue to use that convention.

**Comment by jplevyak** [comment]
@lizan we need this before upstreaming.
