### ISSUE TITLE
SSL performance issue: A lot of EC curve25519  calculations eat CPU

### ISSUE THREAD

**Issue by chipitsine** [envoyproxy/envoy#7959]
we use envoy-1.11.1 in https mode. we use RSA ssl certificates, however in `cpuprofiller` mode we observe a lot of EC calculcations

![Screenshot from 2019-08-16 19-20-32](https://user-images.githubusercontent.com/2217296/63270557-d9c3d280-c2b1-11e9-9162-b19bd3a51453.png)

**Comment by mattklein123** [comment]
cc @PiotrSikora @lizan @davidben is this expected?

**Comment by davidben** [comment]
Yes, modern TLS connections, even with RSA certificates, involve an ECDH operation.

Although it is surprising that curve25519 is showing up more than RSA (the bignum bits). An RSA private key operation takes about 10x as long as an X25519 exchange (keygen + ECDH).

Some possibilities:

* Did you build with compiler optimizations enabled? Our curve25519 implementation is in C, so it assumes compiler optimizations for performance.
* The RSA assembly from OpenSSL does not retain a frame pointer and instead relies on CFI annotations to unwind. If your profiler does not interpret those annotations, it's possible some RSA-related samples are getting dropped.
* TLS 1.3 resumption does not use your private key but does perform the ECDH operation (this fixes a flaw in TLS 1.2). If most of your traffic is TLS 1.3 and you have an incredibly high resumption rate, perhaps enough RSA operations are being saved that ECDH actually shows up in the profiler.

**Comment by davidben** [comment]
(To correct a misunderstanding in the issue title, this has nothing to do with renegotiation, which is an old TLS mistake that we don't even implement on the server.)

**Comment by chipitsine** [comment]
hi, I thought it is related to renegotiation, because "cipher change"

![Screenshot from 2019-08-19 23-51-46](https://user-images.githubusercontent.com/2217296/63291220-916dda00-c2dc-11e9-86b2-96bb71366f7c.png)

what do you mean by "our curve25519" implementation ? I thought it comes with BoringSSL. Also, I did have a look to BoringSSL, there's C implementation indeed. no assembler.


I have figured out how to build envoy with profiler, it is a command

```
bazel build //source/exe:envoy-static
```

BoringSSL seems to be built together. I've no idea whether compiler optimization is used or not. Neither I have an idea why is should not be used.


We run special crafted (well, pretty badly crafted) performance testing, so TLS1.2 is used. however, I think TLS1.3 will be used in production.

Also, I tried to build envoy against openssl using

```
CXXFLAGS="-DENVOY_SSL_VERSION=\\\"OpenSSL\\\"" bazel build //source/exe:envoy-static --define boringssl=disabled
```


it is not very usable, for example, it cannot load certs

```
envoy          | [2019-08-18 10:08:19.612][9][warning][config] [source/common/config/grpc_mux_subscription_impl.cc:72] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) ext-https: Didn't find a registered implementation for name: 'envoy.listener.tls_inspector'
envoy          | 2019/08/18 10:08:19 сallbacks.go:38: [DEBUG] Stream request id=1 req='node:<id:"localNode" cluster:"local" build_version:"e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/Clean/DEBUG/OpenSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"45" error_detail:<code:13 message:"Error adding/updating listener(s) ext-https: Didn't find a registered implementation for name: 'envoy.listener.tls_inspector'" > '
envoy          | 2019/08/18 10:08:19 log.go:8: [INFO] respond type.googleapis.com/envoy.api.v2.Listener[] version "" with version "1"
```

looks like a bug. so, what do you mean by "The RSA assembly from OpenSSL ..." ? is there a way to use envoy with OpenSSL ?

thank for your examplanation!
sorry for some misunderstanding from me.

**Comment by chipitsine** [comment]
btw, is there a way to get build configuration from envoy runtime ? something like `nginx -V` ?

**Comment by davidben** [comment]
> hi, I thought it is related to renegotiation, because of "cipher change"

No, that's just a random message used in the TLS handshake.

> what do you mean by "our curve25519" implementation ? I thought it comes with BoringSSL. Also, I did have a look to BoringSSL, there's C implementation indeed. no assembler.

That's right. With a good C compiler, that C implementation performs very well and is synthesized via a [formally-verified pipeline](https://github.com/mit-plv/fiat-crypto), so we switched to using it exclusively at some point. No sense in keeping around assembly that isn't pulling it's weight. (Taking keygen + ECDH together, it actually outperformed the assembly because the C implementation was easier to adapt to Ed25519's base point tables.)

> BoringSSL seems to be built together. I've no idea whether compiler optimization is used or not. Neither I have an idea why is should not be used. Any special way how to enable it ?

That's a question for Envoy folks.

If you can build the bssl tool, you can run `bssl speed -filter 25519` and `bssl speed -filter RSA` to get a comparison of the performance. (I'm comparing against RSA 2048, which is most common. On that note, you should also check what size of key you're benchmarking against. If it's RSA 1024, RSA will look faster than it will be in practice.)

> We run special crafted (well, pretty badly crafted) performance testing, so TLS1.2 is used. however, I think TLS1.3 will be used in production.

You may wish to test both then. TLS 1.2 and TLS 1.3 are very different protocols.

> so, what do you mean by "The RSA assembly from OpenSSL ..." ?

Oh, BoringSSL's assembly is derived from assembly in OpenSSL, so I tend to say OpenSSL assembly out of habit.

**Comment by lizan** [comment]
> That's a question for Envoy folks.

@chipitsine are you using official image or custom build? If you didn't pass `-c opt` to bazel that means you're not running a optimized build.

**Comment by chipitsine** [comment]
Thank for the tip. I've idea why '-c opt' is not enabled by default. Is it buggy?

**Comment by lizan** [comment]
@chipitsine No, it is intentional that the default configuration is `fastbuild`. It is documented to use `-c opt` for production build: https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#production-environments
