### ISSUE TITLE
Envoy latest image performance drop increased high cpu.

### ISSUE THREAD

**Issue by arun0704** [envoyproxy/envoy#7960]
title:- Envoy latest image performance drop increased  cpu consumption.
running envoyalpine:latest image 

expected result:- old envoy performance result with image(envoy v1.5.0 )
/user/bin/local/envoy                               cpu(6m)         RAM(39Mi)
test result:-
/user/bin/local/envoy                               cpu(176m)         RAM(139Mi)
envoy  version: bf169f9d3c8f4c682650c5390c088a4898940913/1.11.0/Clean/RELEASE/BoringSSL

Can please some one tell me why cpu got increased?

**Comment by derekargueta** [comment]
Can you provide more information, such as how you are testing this, what features you're using, and maybe a [`perf` report](https://linux.die.net/man/1/perf-report)? A lot of factors can affect CPU usage, such as health checking, what load balancer you're using, TLS handshakes, etc.

**Comment by arun0704** [comment]
@derekargueta Thanks, CPU rate was going high due to number of worker threads, i found in  old performance test setup 
--concurrency = 10 so it was taking less cpu, in current test bad  --concurrency = 48 , so this was causing high cpu. so i think nothing wrong with envoy, working fine.
