### ISSUE TITLE
please close tcp stream with "tcp rst" (when possible)

### ISSUE THREAD

**Issue by chipitsine** [envoyproxy/envoy#7961]
please have a look (we use envoy 1.11.1)

![Screenshot from 2019-08-14 23-08-42](https://user-images.githubusercontent.com/2217296/63292820-fe36a380-c2df-11e9-99ec-1210d1bbd04e.png)

client sends "Connection: Close", so server knows it can close connection. Good.

if server will terminate connection with TCP RST, there will be no TIME WAIT state. 
some explanation: https://stackoverflow.com/questions/38579973/why-does-the-rst-packet-not-need-the-time-wait-state

I observed, for example IIS uses TCP RST under similar conditions

**Comment by mattklein123** [comment]
Envoy does fully close the connection after the delayed close timeout, which defaults to 1s. See "delayed_close_timeout" here: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
