### ISSUE TITLE
Is it possible to attach tags to envoy.server.live only?

### ISSUE THREAD

**Issue by mauriedo** [envoyproxy/envoy#7985]
We spin up multiple envoys as part of our internal platform, potentially all of them configured differently. Stats from these envoys are sent to a centralised place.

We would like to have an easy way to see what envoys have what top-level features (think auth, retries, circuit breaking) turned on via arbitrary stats and tags, but without having to tag all stats for it. An idea we had was to tag only the envoy.server.live stat, so that metric becomes the "Envoy is alive here and is configured like this".

Is this even possible? How would we go around it?

Thanks!

**Comment by mattklein123** [comment]
No this is not possible. It sounds like a potentially interesting feature though I think details need to be thought out in terms of whether we should do something more generic or there is some other potential solution. cc @jmarantz for stats thoughts.
