### ISSUE TITLE
internal headers being stripped

### ISSUE THREAD

**Issue by acds** [envoyproxy/envoy#7988]
Hi I'm quite new a envoy and having trouble parsing the Header Manipulation [documentation](https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/http_conn_man/headers). Any help appreciated.

*Title*
HTTP Header in mesh being stripped by envoy when one micro-service is calling another internally

*Description*:
Service A is called externalizing passing in "APIKey" header, Service A calls Service B internally passing on the APIKey provided externally on HTTP request to Service B

*Question*
How does one define the envoy configuration such that the "APIKey" header is not stripped by envoy for the internal cal A->B?

Thanks!

**Comment by mattklein123** [comment]
By default Envoy does not strip any headers other than as defined by https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/header_sanitizing, so I'm guessing there is some other issue with your config?
