### ISSUE TITLE
How to set a Dubbo Proxy Route Configuration apply to all interface?

### ISSUE THREAD

**Issue by sennyhan** [envoyproxy/envoy#7991]
I have a sample  dubbo service which have many interfaces. I want set same route Configuration to all interface. When missing interface In Dubbo Proxy Route Configuration, error occurs in envoy logs as follows.
"dubbo router: no cluster match for interface 'org.apache.dubbo.demo.DemoService'"
Can I not specify Interface of Dubbo Proxy Route Configuration? How to set a Dubbo Proxy Route Configuration apply to all interface?

**Comment by mattklein123** [comment]
cc @zyfjeff

**Comment by zyfjeff** [comment]
@sennyhan Currently, the interface does not support wildcards. It can only be configured one by one. This can be used as a new feature.

**Comment by sennyhan** [comment]
> @sennyhan Currently, the interface does not support wildcards. It can only be configured one by one. This can be used as a new feature.

@zyfjeff  The dubbo service which I use has hundreds of interfaces.  It 's too complicated configuring interfaces one by one. Could you tell me when the new feature supporting wildcards of interface will come? And can I submit an issue for tracking it? Thanks alot.

**Comment by zyfjeff** [comment]
@sennyhan You can create an issue to track it and I will process it in the next two weeks.

**Comment by sennyhan** [comment]
> @sennyhan You can create an issue to track it and I will process it in the next two weeks.

thanks

**Comment by sennyhan** [comment]
> @sennyhan You can create an issue to track it and I will process it in the next two weeks.

@zyfjeff  Thanks alot

**Comment by sennyhan** [comment]
> @sennyhan You can create an issue to track it and I will process it in the next two weeks.

@zyfjeff  Could you step up it's resolution?  We need to use this feature urgently. Thanks alot!

**Comment by geoleonsh** [comment]
I have solved this problem and I will submit a pull request
