### ISSUE TITLE
Trustworthy identification of service caller

### ISSUE THREAD

**Issue by boonware** [envoyproxy/envoy#8007]
# Description
I have a service which needs to know the identity of the service calling its API. From reading the documentation I see there is the `x-envoy-downstream-service-cluster` header which can be attached to HTTP requests to carry this information. However, in the docs it says:

> Note that in the current implementation, this should be considered a hint as it is set by the caller and could be easily spoofed by any internal entity

So my question is, is there a _trustworthy_ mechanism to propagate the service identity with a HTTP request?

# Relevant Links
https://www.envoyproxy.io/docs/envoy/v1.5.0/configuration/http_conn_man/headers#x-envoy-downstream-service-cluster

**Comment by mattklein123** [comment]
You would need to set up mTLS, use JWT, etc. so the service identity can be cryptographically verified.

**Comment by boonware** [comment]
@mattklein123 Even with mutual TLS enabled, the called service still needs to know the caller identity at the REST API level, and I'm hoping to get this information from Istio _in order to create_ a JWT.
