### ISSUE TITLE
listener manager: Closing listening sockets on stopListeners

### ISSUE THREAD

**Issue by euroelessar** [envoyproxy/envoy#8031]
*Description*:
As part of draining phase (`Envoy::Server::Instance::drainListeners`) Envoy instructs all workers to stop accepting new connections, however it does not close listening sockets.

This has few consequences:
1. Clients observe it as hung socket and they have to timeout connection attempts instead of receiving fast-failure.
2. If socket uses `SO_REUSEPORT` and some other Envoy instance is bound to the same port - only half of clients are able to establish successful connections, others are hung on draining Envoy.

Is it acceptable to alter `ListenerManagerImpl::stopListeners` behavior to cleanup `active_listeners_` as soon as workers reported that they've stopped accepting new connections?

*Relevant Links*:
* https://github.com/envoyproxy/envoy/blob/dbb11fd6743e8dbc69c2cd3ff63251e898ccafc0/source/server/listener_manager_impl.cc#L793-L797

**Comment by mattklein123** [comment]
Yes this seems reasonable to me. I can't recall any reason why it shouldn't work this way. cc @PiotrSikora for any additional comments.

**Comment by euroelessar** [comment]
Can you re-open this ticket, please? I'll submit a pull request later this week.
