### ISSUE TITLE
drain_connections_on_host_removal poorly named

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#8056]
The field `drain_connections_on_host_removal` on the Cluster is poorly named as there are cases
where endpoints are removed from a `HostSet` based on this field being set (ie active hc enabled, endpoint still healthy) without connections being drained (due to the somewhat recent batch update mechanism now supported by EDS).

A better name might be `ignore_health_on_host_removal`, as this better describes that the option does without implying what the consequence of this is.

**Comment by mattklein123** [comment]
@snowp I think this can be easily fixed now with the new rename capability that @lizan added. Do you mind doing this before we snap v3? cc @lizan @derekargueta
