### ISSUE TITLE
RedisCluster sending commands to the wrong node resulting in MOVED (redirection) errors 

### ISSUE THREAD

**Issue by sabiurr** [envoyproxy/envoy#8079]
*Title*: *RedisCluster sending commands to the wrong node resulting in MOVED (redirection) errors *

*Description*:
> I have a Elasticache cluster of 9 nodes (3 shards) and using `curl http://localhost:8001/clusters`, it does seem that envoy is able to track the cluster topology and is aware of all the nodes. However when I send a redis command like `redis-cli -h localhost -p 1999 GET test`, I received a MOVED error. 

I am trying to set up envoy proxy for redis cluster using https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis.html?highlight=redis#redis-cluster-support-experimental

I know that I can set `enable_redirection` to true but this is not ideal and redirection should be rare and I believe envoy should keep track of the cluster topology and should send the command to the right node and not need to be redirected. From logs, I can see that it is connecting to the wrong node `proxy_1  | [2019-08-29 16:39:47.901][19][debug][connection] [source/common/network/connection_impl.cc:704] [C14] connecting to <IP>:6379`

I am using `FROM envoyproxy/envoy-dev:latest` and have also tried `FROM envoyproxy/envoy:latest` and running `CMD /usr/local/bin/envoy -c /etc/envoy.yaml -l debug --service-cluster proxy`. Interesting thing to note, I've only included the Elasticache configuration endpoint as the host and I believe this should be enough to connect to all nodes

Is this an issue with my config?

*Config*:
>
```static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        config:
          stat_prefix: egress_redis
          prefix_routes:
            catch_all_route:
               cluster: redis_cluster
          settings:
            op_timeout: 5s
  clusters:
  - name: redis_cluster
    connect_timeout: 0.25s
    dns_lookup_family: V4_ONLY
    hosts:
      - socket_address:
          address: REMOVED #AWS Elasticache configuration endpoint
          port_value: 6379
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 1s
          cluster_refresh_timeout: 4s
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

**Comment by mattklein123** [comment]
@HenryYYang @msukalski

**Comment by sabiurr** [comment]
Another interesting note is that it seems to be able to send the command to the right node sometimes. From several requests, some of the commands are sent correctly. This makes me think there may be some kind of random load balancing/routing going on?

**Comment by sabiurr** [comment]
Is there a way to view the cluster topology/slots that envoy is keeping track of?

**Comment by HenryYYang** [comment]
you'll need to change the loadbalancing policy to this:
> lb_policy: CLUSTER_PROVIDED
That will take the topology into account.

**Comment by sabiurr** [comment]
Thanks @HenryYYang. That fixes the issue
