### ISSUE TITLE
Allow specification of operation name when configuring tracing for a http manager

### ISSUE THREAD

**Issue by 1mentat** [envoyproxy/envoy#808]
For our current integration with haproxy, the applications address localhost and a port number. There is other information currently only held in metadata that provides information about what the configured destination service is (though this is also already embedded in the cluster name). We'd like to either be able to specify operation name by destination cluster or be able to explicitly specify it in the tracing configuration.

**Comment by objectiser** [comment]
@1mentat Can this issue be closed based on the ability to be able to specify an operation name via a decorator on the route: https://github.com/envoyproxy/envoy/blob/master/docs/configuration/http_conn_man/route_config/route.rst ?

**Comment by 1mentat** [comment]
Yes, that method should work.

**Comment by mattklein123** [comment]
Cool closing.
