### ISSUE TITLE
v3 API: move tls_context to transport_socket only

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8098]
Currently we setup raw_buffer / tls transport_socket based on existence of tls_context (partly as transition).

The motivation to move tls_context to transport socket (extension config) is to better support the proposed transport_socket_matcher: https://github.com/envoyproxy/envoy/issues/8016

**Comment by lizan** [comment]
@envoyproxy/api-shepherds WDYT? This one might be controversial.

**Comment by mattklein123** [comment]
This makes sense to me, and I think would also make it easier for people to support other SSL engines with an entire alternate config structure.

**Comment by htuch** [comment]
Sure, if we don't get any push back on this issue we can do this.

**Comment by htuch** [comment]
Should we tag `tls_context` as deprecated to kick this off? I think this issue boils down to tagging `tls_context` as deprecated, having it auto-deleted by `protoxform` in v3 and then having folks use the transport socket mechanism instead going forward.
