### ISSUE TITLE
Maximum direct response body size

### ISSUE THREAD

**Issue by sekaninat** [envoyproxy/envoy#8104]
**Description**
Hello, can someone please explain why is the direct response body limited explicitly to 4096B? See https://github.com/envoyproxy/envoy/blob/master/source/common/router/config_utility.cc#L114

I would like to be at least able to change this value.

Thank you.

**Comment by mattklein123** [comment]
Because Envoy reads this file into memory and does not have any capability to efficiently serve from disk. I have no issue with making this value configurable.

**Comment by dio** [comment]
@sekaninat I think the question is answered, I'm closing this. Feel free to re-open it if you need further clarifications.

**Comment by aapeliv** [comment]
If anyone else gets here, it was closed in #13422, `max_direct_response_body_size_bytes` in `RouteConfiguration`.
