### ISSUE TITLE
FIPS compliant version of docker image in docker repository

### ISSUE THREAD

**Issue by sp13-hub** [envoyproxy/envoy#8107]
*Title*: *FIPS compliant version of docker image in docker repository*

*Description*:
>It looks like images available in envoyproxy repo is boringSSL without fips compliance. Right now if we need it we have to build on our own. Is it possible to provide a fips compliant version of image ?

[optional *Relevant Links*:]
>https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl.html?highlight=fips#fips-140-2

**Comment by mattklein123** [comment]
This is a reasonable request but realistically I doubt this will happen any time soon. It might be better to reach out to https://www.getenvoy.io/ and see if they will do it? cc @lizan @dio

**Comment by sp13-hub** [comment]
@mattklein123 Thank you. I just checked the issues there, and looks like there has been already one in their queue.
https://github.com/tetratelabs/getenvoy-package/issues/20

**Comment by lizan** [comment]
Yeah that's in getenvoy roadmap but I don't have an ETA right now

**Comment by sp13-hub** [comment]
@lizan Thank you. Glad it is in your road map. I will follow the other issue.
