### ISSUE TITLE
Audit v3 proto package structure

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8121]
As part of the v3 work, we should re-evaluate the package tree structure to ensure that the decisions made in v2 are still working for us and see what might need tweaking. This should not be a radical restructuring, we should be working along the margins ideally.

**Comment by mattklein123** [comment]
@htuch one of things I think we should do here is split out extension configs to better match the source code. Right now they are intermingled in the config directory. So I would suggest an extensions directory with the same structure as the source code.

**Comment by htuch** [comment]
@mattklein123 flagging this one as being potentially too high churn given everything else going on in v3. This reorganization is very easy to do though via `protoxform` and reflection translation, so I think we might still consider it.

**Comment by htuch** [comment]
Related is https://github.com/envoyproxy/envoy/issues/8490. Also, various `common` packages are unversioned today. We should move them to a versioned scheme to support API evolution for these components.

**Comment by htuch** [comment]
Re: extensions, @mattklein123 have discussed offline the need to have better consistency between the handcrafted RST docs for extensions and the API generated docs, in particular in light of https://github.com/envoyproxy/envoy/pull/8906. Leaving this comment to track further work here.

**Comment by htuch** [comment]
Related to https://github.com/envoyproxy/envoy/issues/8120

**Comment by htuch** [comment]
I'm marking this help wanted and unassigning myself. Technically the implementation of this issue is dependent on us completing the package rename support in the v2 --> v3 tooling, but there is a bunch of parallelism possible; we can have someone do a design proposal for the new package layout and do community discussion, achieve buy-in, and then execute when tooling is available for package movement.

**Comment by htuch** [comment]
This was completed in #9515 and #9555.
