### ISSUE TITLE
Question : Custom filter to split PUT in several multipart requests

### ISSUE THREAD

**Issue by s-vivien** [envoyproxy/envoy#8123]
Let's say I want to upload a large file to Amazon S3 using their multipart API in which the file is sent in several pieces, but I want to do that in a single upload.

Would it be possible to use Envoy for that ? i.e. the client makes a single PUT request, Envoy splits the request in several pieces (and thus several requests to the upstream), all that in full streaming (no buffering whatsoever).

I'm guessing it could be feasible if I code a custom filter, but before investing a lot of time in this I want to make sure I'm not missing some constraints that would make this impossible.

**Comment by mattklein123** [comment]
Yeah you could do this with a custom filter.

**Comment by htuch** [comment]
@s-vivien does this answer your question? If so, can we close out this issue?

**Comment by s-vivien** [comment]
It does answer my question. Thanks.
