### ISSUE TITLE
Hybrid v2/v3 static/dynamic configuration; should we support this?

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8137]
A few questions on how to handle hybrid v2/v3 configs for @envoyproxy/api-shepherds:

It's conceivable that an Envoy might have a v3 bootstrap but only be able to ingest dynamic configuration from v2 servers in some operator configuration. Do we want to support these kinds of mixed configurations?

Should we implement fallback support to v2 endpoints if a v3 server is unavailable but configured?

Is this a blocker to v3 release or can we ship with the API pieces in place but no implementation?

**Comment by mattklein123** [comment]
> Do we want to support these kinds of mixed configurations?

IMO yes, much like we allowed REST v1 to be called for a while.

> Should we implement fallback support to v2 endpoints if a v3 server is unavailable but configured?

IMO we don't need this.

> Is this a blocker to v3 release or can we ship with the API pieces in place but no implementation?

IMO we can ship the API without the implementation.

**Comment by htuch** [comment]
Fixed in https://github.com/envoyproxy/envoy/pull/9526
