### ISSUE TITLE
Compile curl dependency with c-ares support

### ISSUE THREAD

**Issue by troshko111** [envoyproxy/envoy#8140]
*Title*: `curl` is compiled without `c-ares` support and is prone to crashes on DNS timeouts due to `longjmp`.

*Description*: `curl` dependency (via `cmake_external`) was added as part of https://github.com/envoyproxy/envoy/pull/5387 but does not use the already existing `c-ares` library for async DNS resolution and is prone to crashes on modern Linux kernels. 

Suggested fix:

> [Moved to a separate issue, irrelevant] change `curl` from `cmake_external` to Bazel-native with a manually written `BUILD` file like https://github.com/tensorflow/tensorflow/blob/master/third_party/curl.BUILD

- Add ```deps = [//external:ares, //external:zlib]``` and ```-DUSE_ARES, -DHAVE_ZLIB_H``` options

This will use Envoy's `c-ares` and `zlib` dependencies and instruct `curl` to use `c-ares` for DNS resolutions.

**Comment by troshko111** [comment]
I just realized that `zlib` available as an Envoy dependency is not used either, curl has an option to use an existing version of `zlib` via `-DHAVE_ZLIB_H`.

So right now Envoy compiles two potentially different versions of `zlib`.

**Comment by htuch** [comment]
@troshko111 as discussed in https://github.com/envoyproxy/envoy/issues/8141, we are unlikely to take the random Bazel native BUILD file without a clear plan for how it will be updated, maintained and validated against the external dependencies canonical build system for correctness.

I think the problems you point to sound real and we need a solution, but not one that involves us making this change. Can you suggest some other options here?

**Comment by htuch** [comment]
CC @jmillikin-stripe @lizan

**Comment by lizan** [comment]
Just add a deps to curl cmake_external target, like https://github.com/bazelbuild/rules_foreign_cc/blob/master/README.md#building-cmake-projects does for eigen and openblas.

**Comment by troshko111** [comment]
You're right, `-DUSE_ARES`, `-DHAVE_ZLIB_H` should be enough + dependencies on both c-`ares` and `zlib` if keeping it `cmake_external` is preferred.

**Comment by troshko111** [comment]
Ended up being a bit more involved due to the level of `CMake` support in curl and totally different options used. I could not get `BoringSSL` to build but it's unused in the `origin/master` version anyway.

For the reference it seems like https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake#L358 was failing on version parsing as the logs otherwise had no failure, the library was detected correctly and so on. I found no workarounds to skip this somehow as it's used pretty unconditionally from here https://github.com/curl/curl/blob/master/CMakeLists.txt#L357

**Comment by troshko111** [comment]
Also worth noting curl CMake build spits this out:
```
CMake Warning at CMakeLists.txt:50 (message):
  the curl cmake build system is poorly maintained.  Be aware
```

not very encouraging but checking the activity on the CMake lists it seems maintained rather ok (not kept broken and is updated regularly).
