### ISSUE TITLE
[question] Envoy to fail requests if ext_authz is unavailable?

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#8146]
By doing some investigation, looks like this is not supported, but wanted to confirm.
Is it possible to configure Envoy to fail http requests in case ext_authz service is unavailable? This could be useful when one runs cluster of envoys behind L7 LB and LB performs http health checks towards envoy instances. Does envoy support health checking towards ext_authz cluster? Could those maybe be propagated to the envoys health check response?

**Comment by mattklein123** [comment]
ext_authz should be a cluster like any other cluster, meaning that when Envoy goes to send a request to the cluster in the filter, it should handle a no healthy hosts failure condition and fail the request.

**Comment by nezdolik** [comment]
Thanks @mattklein123!
