### ISSUE TITLE
Ambiguity between static listener definition and LDS listeners with the same address

### ISSUE THREAD

**Issue by jessicayuen** [envoyproxy/envoy#8161]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: Inconsistent behavior when defining static listeners and LDS listeners with the same address.

*Description*:
We're in the process of migrating listeners defined in static `envoy.yaml` configuration to dynamic configuration. During a phase of this migration the static listeners will co-exist with our control plane's attempt to send dynamic LDS configuration.

In our testing we observed Envoy increase in stats for LDS `create_failure` and `update_failure`s, with an error log message that the address is already defined. A config dump also shows that the dynamic listeners are being drained. This seems to be consistent with the docs mention of static listeners not being able to be removed or modified: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/lds.html?highlight=lds#listener-discovery-service-lds (Although it is unclear what makes a listener unique - is it the name? address?).

However, this doesn't always appear to be the case. I have observed behavior where the LDS listeners are co-existing (active) with the static listeners (same address and port) in the same config dump. This inconsistent behavior has led to complications in our rollout, where we rely on the LDS configuration being rejected while there is a static one defined.

I would like to better understand what is the variable that makes a static listener unique in order to not be modified.

**Comment by mattklein123** [comment]
The uniqueness property is via the name of the listener. 

https://github.com/envoyproxy/envoy/blob/d21d92ca21cd827e8ab484244a9eefc31bfd8af4/source/server/listener_manager_impl.cc#L505

As long as you define the same name for the static and dynamic listener, I think it should do what you want.
