### ISSUE TITLE
stats: [request] expose the underlying histogram unit

### ISSUE THREAD

**Issue by troshko111** [envoyproxy/envoy#8164]
*Title*: Certain stat backends may distinguish between time and generic histograms and need this distinction when flushing.

*Description*: [Atlas](https://github.com/Netflix/atlas) supports general-purpose histograms (distribution summaries) and timers (histograms whose unit is time, in seconds). Furthermore, Atlas expects all units to be base so they can be represented with [Metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) on the UI. The base unit of time is second, and when shown on the UI, depending on the value, it can be automatically displayed in ms, micros, nanos, etc.

Current histogram design does not expose the underlying unit and reports the time in milliseconds which creates an incompatibility for systems like Atlas - reporting as-is would mean that timers are reported in millis and make no sense on the UI (millis of millis, kilos of millis, etc.) or the values can be divided by 1000 when flushing but then the non-timer histograms stop making sense as their values are essentially off.

The original `Histogram` (`include/envoy/stats/histogram.h`) class states this was by intention:
```
/**
 * A histogram that records values one at a time.
 * Note: Histograms now incorporate what used to be timers because the only difference between the
 * two stat types was the units being represented. It is assumed that no downstream user of this
 * class (Sinks, in particular) will need to explicitly differentiate between histograms
 * representing durations and histograms representing other types of data.
 */
``` 

but I suppose it was done because it was not foreseen, not because it presented an issue per se?

Would you be open to accepting a PR which adds this information to the histogram in some way?

**Comment by zuercher** [comment]
I don't think it would be terribly difficult to introduce a notion of unit or the scaling factor (e.g. millis for time histograms). What do you think, @jmarantz?

**Comment by troshko111** [comment]
Happy to work on this as long as we agree it can be merged and on a specific implementation:

- Include the unit
- Measure in base units (seconds for timers, implies type change to double which would have perf impact)
- Method providing the value in base units (dividing by 1000d for timers, returning as-is for non-timers)
- Potentially something else

**Comment by mattklein123** [comment]
My preference is to include a unit only and do nothing else. Is this sufficient?

**Comment by troshko111** [comment]
Absolutely, any of these is perfectly sufficient, just wanted to make sure you're not opposed to and understand your preference. Thanks.

**Comment by jmarantz** [comment]
Units sound good to me, but I'm not sure the scope of that proposal.

E.g. should the histogram API require a unit (similar to specifying now the ImportMode for Gauge)? Would this just be a string, e.g. "ms" to be conveyed to the UI somehow via Sinks? Or an integer multiplier against (say) a base unit of nanoseconds or microseconds? I think some metrics may be interesting in microseconds, e.g. histograms of epoll latency? Or maybe an enum of common units, including 'unspecified' if the units are not meant to be time?

**Comment by troshko111** [comment]
> E.g. should the histogram API require a unit (similar to specifying now the ImportMode for Gauge)?

IMO it probably should to make the API less surprising, otherwise we'll have to set something by default (assume a non-timer) and require the unit for timers only? No strong preference though. I think assuming a non-timer histogram and base unit is a good default with a possibility to set the unit.

 > Would this just be a string, e.g. "ms" to be conveyed to the UI somehow via Sinks?

This should probably be an enum or a multiplier to the base? Anything the sinks can utilize to report properly, not necessarily some as-is string to be included on the UI. In case of Atlas, it just needs you to call a different API based on timer / non-timer and make sure you specify the base unit (reported in `double` so even though the duration is specified in seconds, the milliseconds precision is preserved underneath).

> I think some metrics may be interesting in microseconds, e.g. histograms of epoll latency? Or maybe an enum of common units, including 'unspecified' if the units are not meant to be time?

This should be covered by either of the approaches, a histogram can optionally accept an enum specifying the unit or a multiplier to base, the rest is the sink's job if one is able to take advantage of this info.

Thoughts?

**Comment by jmarantz** [comment]
I think we are on the same page. I am not familiar with any of the sinks that you would be targeting but I'm moderately in favor of the enum approach. What do others think?

**Comment by mattklein123** [comment]
My preference would be to use an enum for the unit type, and require that the unit be provided when a histogram is constructed (like we do for gauge import type). There are not that may histograms so IMO this not that big of an ask. WDYT?

**Comment by troshko111** [comment]
Finally got to this this week, let me send the PR for the initial feedback.
