### ISSUE TITLE
Redis proxy traffic mirroring runtime default

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#8171]
`MirrorPolicyImpl::shouldMirror` will override a default runtime fraction of 0, and instead mirror 100% of the time.
 https://github.com/envoyproxy/envoy/blob/6ca8500b39568049647f4f40a599b8f8bd2afc3d/source/extensions/filters/network/redis_proxy/router_impl.cc#L17-L32

This is at odds with documentation:
https://github.com/envoyproxy/envoy/blob/6ca8500b39568049647f4f40a599b8f8bd2afc3d/api/envoy/api/v2/route/route.proto#L612-L617

```
    // If not specified, all requests to the target cluster will be mirrored. If
    // specified, Envoy will lookup the runtime key to get the % of requests to
    // mirror. Valid values are from 0 to 10000, allowing for increments of
    // 0.01% of requests to be mirrored. If the runtime key is specified in the
    // configuration but not present in runtime, 0 is the default and thus 0% of
    // requests will be mirrored.
```

And also inconsistent with the behavior of http router traffic mirroring:

https://github.com/envoyproxy/envoy/blob/eff020170c6267e6c8dc235473f7fc85c5b1e07d/source/common/router/config_impl.cc#L180-L185

**Comment by kb000** [comment]
@HenryYYang

**Comment by zuercher** [comment]
Looks like it completely ignores the deprecated runtime_key field and only heeds runtime_fraction if the default numerator is > 0.
