### ISSUE TITLE
Stackdriver spans via Opencensus are missing metadata

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/envoy#8172]
We are having trouble with spans on stackdriver, specifically with getting all the metadata to show up. 

### Configuration

We are using Opencensus config to setup tracing in our bootstrap config:

```
tracing:
  http:
    name: envoy.tracers.opencensus
    typedConfig:
      "@type": type.googleapis.com/envoy.config.trace.v2.OpenCensusConfig
      traceConfig:
        constantSampler:
          decision: ALWAYS_ON
      stackdriverExporterEnabled: true
      stackdriverProjectId: fake-123
```

We have added traces to our custom envoy filters with the code below:

```
request_span_ = parent_span_.spawnChild(Envoy::Tracing::EgressConfig::get(), span_name, time_source_.systemTime());
request_span_->setTag(Tracing::Tags::get().Component, Tracing::Tags::get().Proxy);
request_span_->setTag(Tracing::Tags::get().UpstreamCluster, http_uri_.cluster());
request_span_->setTag(Tracing::Tags::get().HttpUrl, uri_);
request_span_->setTag(Tracing::Tags::get().HttpMethod, "POST");
...
// Make async request
...
<in callback> {
    request_span_->setTag(Tracing::Tags::get().HttpStatusCode, std::to_string(status_code));
    request_span_->finishSpan();
}
```

We also enabled `start_child_span` in [router.proto](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/router/v2/router.proto) for our listeners.

Built using envoy commit `7eed7332d513248a07e493bb8ec7bb3081a18b3e` from 08/21/2019

### Problem Description

We verified that all these spans show up on stackdriver. **However, they are missing metadata set in the code**, such as:
- HTTP Method
- HTTP Status
- Upstream Cluster, etc.

None of this metadata shows up on the console, as seen in this picture:

![image](https://user-images.githubusercontent.com/11142171/64453956-9b465a00-d09e-11e9-955a-eabf3e8a1b44.png)

We also setup a fake gRPC server in golang to intercept [BatchWriteSpan Requests](https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2#google.devtools.cloudtrace.v2.BatchWriteSpansRequest). The following shows a span we intercepted from envoy. Notice it also does not have this metadata:

```
name:"projects/testing-project-123/traces/ac9176c71b4a8db70737920e9159803e/spans/830ff6b5b16b30db" 
span_id:"830ff6b5b16b30db" 
parent_span_id:"7143ff1d3c8d5235" 
display_name:<value:"Fake Span Name" > 
start_time:<seconds:1567796497 nanos:53632914 > 
end_time:<seconds:1567796497 nanos:155113905 > 
attributes:<attribute_map:<key:"g.co/agent" value:<string_value:<value:"opencensus-cpp [0.5.0-dev]" > > > > 
time_events:<> 
links:<> 
status:<> 
same_process_as_parent_span:<value:true > 
```

### Potential Problem and Solution?

I'm guessing that Opencensus is not reading the metadata set by our code correctly before it sends to spans to stackdriver. However, I am not sure if the issue is with envoy's tracing implementation, or with the Opencensus extension. I'm willing to fix the issue if its simple, but I don't know where to look. Please direct me to the appropriate codebase :)

**Comment by kyessenov** [comment]
/sub @kyessenov 
The code is here https://github.com/envoyproxy/envoy/blob/master/source/extensions/tracers/opencensus/opencensus_tracer_impl.cc.

**Comment by nareddyt** [comment]
Looking at that code, it looks like our `setTag` calls should definitely be adding attributes to the span:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/tracers/opencensus/opencensus_tracer_impl.cc#L179

**Comment by nareddyt** [comment]
I guess that means it's an issue with `opencensus_cpp`, since that `addAttribute` call is defined there?

**Comment by nareddyt** [comment]
Solved! After an offline discussion with @kyessenov, we found that there Opencensus Tracing config has fields to set the max number of attributes. They were defaulting to 0...

https://github.com/census-instrumentation/opencensus-proto/blob/5cec5ea58c3efa81fa808f2bd38ce182da9ee731/src/opencensus/proto/trace/v1/trace_config.proto#L41
