### ISSUE TITLE
Inconsistent naming of API proto targets for go

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#8174]
Some of them are explicitly named, i.e. //api/envoy/api/v2:v2 or //api/envoy/api/core:core
the rest has the default name "pkg", i.e. //api/envoy/api/auth:pkg

This inconsistency makes it hard to write automated import tools as target mapping have to be explicitly written and maintained.

**Comment by junr03** [comment]
@kyessenov because you helped a bunch with package naming for go back in the day, and @htuch to flag as something we could potentially fix.

**Comment by kyessenov** [comment]
Yes, it makes sense to keep bazel rule names consistent. Sorry about not making them consistent to begin with. In OSS, the bazel rule names are actually entirely invisible in go world.

**Comment by htuch** [comment]
@kyessenov so, it would be safe to just rename them to `pkg` en masse, without any Go source-level breaking changes? If so, I reckon let's just do that.

**Comment by menghanl** [comment]
@kyessenov Is there any update on this? This would make it easier for us to manage generated code.

**Comment by kyessenov** [comment]
I believe this was fixed as part of https://github.com/envoyproxy/envoy/pull/8495

**Comment by mattklein123** [comment]
Closing as fixed.
