### ISSUE TITLE
Set basic authentication to the endpoint

### ISSUE THREAD

**Issue by boncheo** [envoyproxy/envoy#8175]
Title: How can I set basic authentication to an endpoint.

Description:
Unfortenly there is no enough document for the envoy proxy, Most of documents are code references, After 3 days search, I could not find a simple way in order to add a basic auth to the endpoint (like Nginx). 
How can I set basic authentication to the endpoint?

**Comment by dio** [comment]
You can try this: https://gist.github.com/dio/7a7aa09ea5027c660e0c1c9905be7ffd for now I think. I know it is not pretty, but surely if it is reasonable we can have a basic auth filter. 

The `allow`-and-`deny` thing of nginx basic auth is possible but I need to check if we have that header (client ip) exposed. If not we can extract it through lua API. 

It is defined statically in the above config example, but you can play around with LDS to update the creds.
