### ISSUE TITLE
Developing gRPC external auth service in C#

### ISSUE THREAD

**Issue by ravgupms** [envoyproxy/envoy#8178]
Hi, I'm trying to develop an external auth service in C# but when I trying to generate C# classes from envoy proto file, I'm getting following error.

> 2>--csharp_out : error : validate/validate.proto: C# code generation only supports proto3 syntax

Does anyone has ever successfully complied envoy protos for C# or is there any pre-compiled version available?

**Comment by derekargueta** [comment]
Since the error is from `validate/validate.proto`, I'm guessing it's because [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate) does not support C#.

**Comment by dio** [comment]
For a language that doesn't support proto2, probably removing the validation annotations will help?

**Comment by RaviGitHubAccount** [comment]
I removed validation from protos and its now working for me.

**Comment by ravgupms** [comment]
I removed validation from protos and its now working for me.
