### ISSUE TITLE
Envoy crashes with assertion failure due to strange event while handling websocket traffic

### ISSUE THREAD

**Issue by kflynn** [envoyproxy/envoy#8199]
An Ambassador user is seeing a fairly frequent crash while handling websocket traffic. This is  Ambassador 0.75.0, which is built over Datawire's Envoy, which is Envoy v1.11.1 (e349fb613) plus a few filter fixes.

 We got the corefile, and the stack trace looks like this:

```
#0  0x00007f67540dc34b in raise () from /usr/glibc-compat/lib/libpthread.so.0
#1  0x000000000197d361 in Envoy::SignalAction::sigHandler (sig=6, info=0x7f67509b0830, context=0x7f67509b0700) at source/common/signal/signal_action.cc:73
#2  <signal handler called>
#3  0x00007f6753a0046b in raise () from /usr/glibc-compat/lib/libc.so.6
#4  0x00007f6753a01791 in abort () from /usr/glibc-compat/lib/libc.so.6
#5  0x0000000000f6fb0e in Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::operator()(int, short, void *) const (__closure=0x0, what=32, arg=0x5dc6840) at source/common/event/file_event_impl.cc:64
#6  0x0000000000f6fba4 in Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) () at source/common/event/file_event_impl.cc:66
#7  0x0000000001616609 in event_persist_closure (ev=<optimized out>, base=0x57f2840) at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/processwrapper-sandbox/781/execroot/envoy/external/com_github_libevent_libevent/event.c:1645
#8  event_process_active_single_queue (base=base@entry=0x57f2840, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>)
    at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/processwrapper-sandbox/781/execroot/envoy/external/com_github_libevent_libevent/event.c:1704
#9  0x0000000001619bef in event_process_active (base=0x57f2840) at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/processwrapper-sandbox/781/execroot/envoy/external/com_github_libevent_libevent/event.c:1805
#10 event_base_loop (base=0x57f2840, flags=<optimized out>) at /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/processwrapper-sandbox/781/execroot/envoy/external/com_github_libevent_libevent/event.c:2047
#11 0x0000000000f92a52 in Envoy::Event::LibeventScheduler::run (this=0x58eba90, mode=Envoy::Event::Dispatcher::RunType::Block) at source/common/event/libevent_scheduler.cc:47
#12 0x0000000000f6ae9d in Envoy::Event::DispatcherImpl::run (this=0x58eba40, type=Envoy::Event::Dispatcher::RunType::Block) at source/common/event/dispatcher_impl.cc:192
#13 0x0000000000f5672e in Envoy::Server::WorkerImpl::threadRoutine (this=0x58fdcc0, guard_dog=...) at source/server/worker_impl.cc:104
#14 0x0000000000f55fd0 in Envoy::Server::WorkerImpl::<lambda()>::operator()(void) const (__closure=0x5bc84b8) at source/server/worker_impl.cc:73
#15 0x0000000000f57021 in std::_Function_handler<void(), Envoy::Server::WorkerImpl::start(Envoy::Server::GuardDog&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#16 0x00000000005a60a4 in std::function<void ()>::operator()() const (this=0x5bc84b8) at /usr/include/c++/7/bits/std_function.h:706
#17 0x00000000019809da in Envoy::Thread::ThreadImplPosix::<lambda(void*)>::operator()(void *) const (__closure=0x0, arg=0x5bc84b0) at source/common/common/posix/thread_impl.cc:33
#18 0x00000000019809fe in Envoy::Thread::ThreadImplPosix::<lambda(void*)>::_FUN(void *) () at source/common/common/posix/thread_impl.cc:35
#19 0x00007f67540d1cf8 in ?? () from /usr/glibc-compat/lib/libpthread.so.0
#20 0x00007f6753ac20df in clone () from /usr/glibc-compat/lib/libc.so.6
```

Ignoring frames 1-4 as "Envoy is handling SIGABRT", at frame 5 we're in this callback (`source/common/event/file_event_impl.cc` lines 49-66):

```
      [](evutil_socket_t, short what, void* arg) -> void {
        auto* event = static_cast<FileEventImpl*>(arg);
        uint32_t events = 0;
        if (what & EV_READ) {
          events |= FileReadyType::Read;
        }

        if (what & EV_WRITE) {
          events |= FileReadyType::Write;
        }

        if (what & EV_CLOSED) {
          events |= FileReadyType::Closed;
        }

        ASSERT(events);
        event->cb_(events);
      },
```

From the stack trace we can see that `what` == 32. Reading over `libevent` at commit 0d7d85c2083f7a4c9efe01c061486f332b576d28 (from `repository_locations.txt`), this appears to be `EV_ET` with no other bits set). Since none of `EV_READ`, `EV_WRITE`, or `EV_CLOSED` are set, `events` ends up 0 and the `ASSERT` fails.

Gut feel is that perhaps this should just `return` if `events == 0`, rather than `ASSERT`ing? But I don't know why exactly `libevent` should ever make this callback without setting an actual event...

(This is also tracked as [Ambassador issue 1774](https://github.com/datawire/ambassador/issues/1774).)

**Comment by kflynn** [comment]
(Ambassador issue 1774 notes that downgrading to Ambassador 0.74.0 fixes the issue. 0.74.0 is built from a much earlier Envoy: 0243ded plus some filter fixes.)

**Comment by mattklein123** [comment]
I think this came up recently in the context of the HTTP/2 security issues. @yanavlasov @PiotrSikora do you remember?

Note that this is a debug only issue.

**Comment by kflynn** [comment]
@mattklein123 Good to know, I was wondering how safe it would be to just ignore the `ASSERT`...

**Comment by mnaser** [comment]
How can I help with this?  I'm running into this issue that's causing frequent crashes for our deployment (which uses Ambassador).

**Comment by mattklein123** [comment]
If you are hitting this I would run a release build in production without debug asserts.

**Comment by mnaser** [comment]
@mattklein123 I see, in that case given we're using Ambassador, I'll try to see where I can fix this downstream.  Thank you for your quick response!

**Comment by yanavlasov** [comment]
Sorry for the delay. It is possible that this i caused by the [79cbdc](https://github.com/envoyproxy/envoy/commit/79cbdcae3dda80ed24714b1c0fb1367474386c9f) commit. I'm unsure what libevent would do if the event mask was EV_ET only. Perhaps it could result in this silly callback. I would need the core file to look at the libevent state to confirm.
I think the fix would be to either remove the ASSERT or to not register for events with the libevent if the FileEventImpl::setEnabled() is called with events == 0. But it might be on a riskier side.

**Comment by PiotrSikora** [comment]
> I think this came up recently in the context of the HTTP/2 security issues. @yanavlasov @PiotrSikora do you remember?

I believe this is the culprit -> `file_event_->setEnabled(enable_half_close_ ? 0 : Event::FileReadyType::Closed);` (added in one of the HTTP/2 fixes), i.e. we’re starting to monitor for no events (which expands to `EV_PERSIST|EV_ET`), which is different than stopping to monitor for events. We’re still getting notification, since `EV_ET` happens, but since neither `EV_READ`, `EV_WRITE` nor `EV_CLOSED` are present, we end up with `events == 0` and `ASSERT()`.

We ignored it at the time, because it isn't an issue in release builds.

**Comment by miracle-jia** [comment]
Does anyone know how to reproduce the issue? we met the issue, too.

**Comment by zuercher** [comment]
I'm not convinced that `file_event_->setEnabled(enable_half_close_ ? 0 : Event::FileReadyType::Closed);` (where the argument evaluates to 0) triggers this. As far as I can tell, `enable_half_close_` is never set for the HTTP connection manager and `delayed_close_timeout_` is only ever set for the HTTP connection manager. So the HTTP connection manager may trigger that setEnabled call but should always request `Event::FileReadyType::Closed`.

Could someone who's experiencing this bug share their configuration?

**Comment by htuch** [comment]
See also https://github.com/libevent/libevent/issues/984. I'm not sure if it's so much that we're listening for no events but that libevent isn't filtering events properly.

**Comment by antoniovicente** [comment]
IIRC for sockets, receiving a FIN will trigger a READ event.

This documentation on EV_FEATURE_EARLY_CLOSE may be relevant, not all fd types support CLOSE events.
https://github.com/libevent/libevent/blob/release-2.1.11-stable/include/event2/event.h#L947

**Comment by mattklein123** [comment]
I'm going to close this as this is "fixed" by https://github.com/envoyproxy/envoy/pull/10666. We can track the real fix with the linked libevent issue.

**Comment by htuch** [comment]
This may have been fixed by https://github.com/libevent/libevent/issues/984.
