### ISSUE TITLE
Layer 7 tls passthrough

### ISSUE THREAD

**Issue by hfgbarrigas** [envoyproxy/envoy#8213]
Hi,

 As per the title, is it possible to achieve this with envoy? Went through the docs and searched for a while and didn't find a concrete answer. Found a few issues that touched this subject https://github.com/envoyproxy/envoy/issues/1843 https://github.com/envoyproxy/envoy/issues/5939 and more ... but  only found it achievable through envoy.tcp_proxy which is L4. All in all, it works, but I'd like the capability and statistics of http_manager. 

Ty

**Comment by zuercher** [comment]
Could you elaborate on what http connection manager features and statistics you want to use?

**Comment by hfgbarrigas** [comment]
Thank you clarifying!
