### ISSUE TITLE
Make HTTP response code when backend can't be found configurable

### ISSUE THREAD

**Issue by ahedberg** [envoyproxy/envoy#8214]
**Issue Template**

*Title*: Make HTTP response code when backend can't be found configurable

*Description*:
We've historically returned 502s when a backend can't be found. Envoy currently returns 503s. It'd be nice if we could configure this rather than it being hard-coded.

I'm not sure where the optimal place to configure this would be, so wanted to start the discussion before implementing it.

cc: @AndresGuedez

**Comment by mattklein123** [comment]
@ahedberg I think this is a duplicate or closely related to https://github.com/envoyproxy/envoy/issues/7537. See also proposed API in https://github.com/envoyproxy/envoy/pull/8126. Would you mind collaborating with @lukidzi on this? I would love to see the entire problem of customizing local replies solved holistically as this keeps coming up.
