### ISSUE TITLE
Starting multiple services

### ISSUE THREAD

**Issue by anastayaa** [envoyproxy/envoy#8222]
When i'm trying to run more than one service, i'm getting the error: 
```
unable to bind domain socket with id=0 (see --base-id option)
Error: exit status 1
```

I think this is related to Envoy proxy!!!

**Comment by anastayaa** [comment]
@junr03 thanks for the response. I'm using service mesh to communicate between microservices, for example we have two microservices, and when we start each microservice we start with it an Envoy data plane. the problem is when i want to start the second service, Envoy can't run

**Comment by junr03** [comment]
From your error it looks like you are running both services (and their corresponding envoy process) on the same machine, is that correct?

Did you take a look at the linked issue, is your issue like that one?

**Comment by anastayaa** [comment]
Yes you are right i'm trying to run two microservices in the new kuma service mesh witch use Envoy like a dataplane
