### ISSUE TITLE
Allow setting a list of constant tags for Tracing

### ISSUE THREAD

**Issue by psalaberria002** [envoyproxy/envoy#8224]
*Title*: *Allow setting a list of constant tags for Tracing*

*Description*:
>Currently there is an option for adding tags based on http request headers (request_headers_for_tags). However, there is no option for passing a list of hardcoded tags. It would be great to have such a feature. For example variables like node_id, host_ip, or pod_name could be added to the traces as follows, enriching the traces at will.

```
"tracing": {
  "operation_name": "egress",
  "request_headers_for_tags": [
    "x-cdp-sdk",
    "x-cdp-app",
    "x-cdp-clienttag"
   ],
   "constant_tags": [
     "node_ip=x.x.x.x",
      "pod_name=pod-xyz"
    ]
 },
```

It should be an easy task for someone that knows the codebase. Thank you in advance.

**Comment by yittg** [comment]
@mattklein123 Does this mean that this feature is accepted, I think it's a proper beginner task to get involved in, I would like to start from it if no one else is working on it.

**Comment by mattklein123** [comment]
@yittg yes please go for it.

**Comment by objectiser** [comment]
@yittg One additional requirement, if I may - it would be good to also enable the tag's value to be obtained from environment variables. So if you could support some form of syntax like `"tagName1=tagValue1,tagName2=${envvar2},tagName3=${envvar3:defaultVal3}"`. So `tagName2` would be set if the environment variable `envvar2` has a value, and `tagName3` would be set to the env variable `envvar3` if it exists else use the value `defaultVal3`.

If my explanation is not clear, let me know.

**Comment by yittg** [comment]
@objectiser Got your point. I'm not quite sure why we need it, would you give some scenarios about it? 😄

**Comment by objectiser** [comment]
For example, when deploying in Kubernetes, we may want to record the pod name - which is only available in an environment variable.

**Comment by yittg** [comment]
@objectiser Got it.
Would we introduce a struct like following to describe it instead of parsing variable.
```
CustomTag {
  string tag;
  Type type={Literal, Environment, Header,...};
  string value;
  string default_value;
}
```

**Comment by objectiser** [comment]
@yittg Ok sounds good.

Does this mean you are looking to replace the `request_headers_for_tags` as well? If so, 

1. Consolidating into the one configuration seems reasonable as long as enough time is given to deprecate the old mechanism.
1. Previously I remember someone requesting the ability to rename a tag based on a request header - which wasn't possible with the current approach - but if the `value` field is used to specify the header name, then this mechanism would also support that requirement.

**Comment by yittg** [comment]
@objectiser Thanks for your reply.
I think it's a good idea to unify the inner implementation. But I'm not quite sure whether to expose user with clear extendable structure or simplified expression.

**Comment by objectiser** [comment]
@mattklein123 any thoughts on this?

**Comment by yittg** [comment]
@objectiser I gave a first try about this issue, though still some more work to do, :).

**Comment by khyveasna** [comment]
Guzman HDTV chip 

> `![robot](https://user-images.githubusercontent.com/52799430/69012494-6db74000-096e-11ea-9d0b-83cdfe4fc028.png)mooch`
