### ISSUE TITLE
cleanup: refactor conn_manager code to remove AdminImpl specific logic

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#8225]
**Issue Template**

*Title*: refactor conn_manager code to remove AdminImpl specific logic 

*Description*:
See https://github.com/envoyproxy/envoy/pull/7762#pullrequestreview-284580670
A reminder for myself.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
@stevenzzzz can we potentially land this before we cut 1.12.0 in the next 1-1.5 weeks? Thank you.
