### ISSUE TITLE
ListenerManagerImplQuicOnlyTest.QuicListenerFactory flaky

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#8252]
Looks like this test is failing occasionally.  Dan, would you mind taking a look?  If you have trouble reproducing, there's a README about flaky integration tests which might help, or you can reach out to me.

Sample runs: 

https://circleci.com/gh/envoyproxy/envoy/276808?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
https://circleci.com/gh/envoyproxy/envoy/276812?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
https://circleci.com/gh/envoyproxy/envoy/276813?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

Example failure

[ RUN      ] ListenerManagerImplQuicOnlyTest.QuicListenerFactory
unknown file: Failure
C++ exception with description "Didn't find a registered implementation for name: 'quic_listener'" thrown in the test body.
test/server/listener_manager_impl_quic_only_test.cc:37: Failure
Actual function call count doesn't match EXPECT_CALL(os_sys_calls_, setsockopt_(_, _, _, _, _))...
         Expected: to be called at least once
           Actual: never called - unsatisfied and active
Stack trace:
  0x7f026be536be: testing::internal::GoogleTestFailureReporter::ReportFailure()
  0x7f02cacbbffb: testing::internal::Expect()
  0x7f026be73e9f: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
  0x7f02c2691cfb: testing::internal::FunctionMocker<>::~FunctionMocker()
  0x7f02c2686cd5: Envoy::Api::MockOsSysCalls::~MockOsSysCalls()
  0x7f02caba99ae: testing::NiceMock<>::~NiceMock()
  0x7f02caba59e1: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest::~ListenerManagerImplQuicOnlyTest()
  0x7f02caba2f52: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test::~ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test()
  0x7f02caba2faf: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test::~ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test()
  0x7f026bf867a3: testing::Test::DeleteSelf_()
  0x7f026bfd5acd: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f026bf847ae: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f026bf3c092: testing::TestInfo::Run()
  0x7f026bf3da3f: testing::TestSuite::Run()
... Google Test internal frames ...

test/server/listener_manager_impl_quic_only_test.cc:36: Failure
Actual function call count doesn't match EXPECT_CALL(listener_factory_, createListenSocket(_, Network::Address::SocketType::Datagram, _, true))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
Stack trace:
  0x7f026be536be: testing::internal::GoogleTestFailureReporter::ReportFailure()
  0x7f02cacbbffb: testing::internal::Expect()
  0x7f026be73e9f: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked()
  0x7f02c568f98b: testing::internal::FunctionMocker<>::~FunctionMocker()
  0x7f02c5649385: Envoy::Server::MockListenerComponentFactory::~MockListenerComponentFactory()
  0x7f02cabad86e: testing::NiceMock<>::~NiceMock()
  0x7f02cabada89: Envoy::Server::ListenerManagerImplTest::~ListenerManagerImplTest()
  0x7f02caba59ed: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest::~ListenerManagerImplQuicOnlyTest()
  0x7f02caba2f52: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test::~ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test()
  0x7f02caba2faf: Envoy::Server::(anonymous namespace)::ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test::~ListenerManagerImplQuicOnlyTest_QuicListenerFactory_Test()
  0x7f026bf867a3: testing::Test::DeleteSelf_()
  0x7f026bfd5acd: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f026bf847ae: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f026bf3c092: testing::TestInfo::Run()
  0x7f026bf3da3f: testing::TestSuite::Run()
... Google Test internal frames ...

[  FAILED  ] ListenerManagerImplQuicOnlyTest.QuicListenerFactory (96 ms)

**Comment by danzh2010** [comment]
This is caused by non-matching static registered class name in well_known_names enum and test config. It is actually a constant failure rather than flakiness. I fixed it in the new commit https://github.com/envoyproxy/envoy/pull/7896/commits/ce75217163926e9966e232f060d00af6af765364. Thanks for pointing it out!

**Comment by danzh2010** [comment]
close #8252

**Comment by alyssawilk** [comment]
Ah, my bad, was just scanning build breakages this morning and it hadn't looked consistent
