### ISSUE TITLE
HeaderMatcher with Regex

### ISSUE THREAD

**Issue by stevesloka** [envoyproxy/envoy#8283]
*Title*: HeaderMatcher with Regex 

*Description*:
I'm working to get a HeaderMatcher implemented with Regex. The regex match doesn't seem to work like I'd expect. 

For instance, if I'm looking for a header with the string `abc` in the value, it seems to be doing an exact match vs applying the regex. 

My envoy Route looks like this:
```
{
          "match": {
           "prefix": "/",
           "headers": [
            {
             "name": "x-header",
             "regex_match": "abc"
            }
           ]
          },
          "route": {
           "cluster": "default/kuard/80/da39a3ee5e"
          },
}
``` 

- **[Fails]** curl -i -H "x-header: aaabcaa"  http://kind.local
- **[Suceeds]** curl -i -H "x-header: abc"  http://kind.local

My goal for this example is to allow for routing on any header that contains the character string passed.

**Comment by zuercher** [comment]
Does the version of Envoy you're running support SafeRegex? It's a relative recent addition?

**Comment by stevesloka** [comment]
Hey @zuercher you are correct, I was looking at the 1.12 docs and I'm running 1.11.1, so that answers the first question about why the saferegex wasn't working. Thanks!

I still don't understand why the regular regex doesn't match.

**Comment by zuercher** [comment]
[Per the docs](https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/route/route.proto.html#envoy-api-field-route-headermatcher-regex-match), the regex has to match the entire string. If you want to match the a substring you'll have to use `regex_match: ".*abc.*"`.

**Comment by stevesloka** [comment]
Ahh I that makes sense now, thanks for clarifying! Sorry for the trouble, I think I've been looking at the docs too long. =)

Appreciate the help, all is working now!
