### ISSUE TITLE
Socket options wrapper: Expose configuring socket options through envoy at Filters

### ISSUE THREAD

**Issue by ramachaitanyak** [envoyproxy/envoy#8291]
*Description*:
>Several customized tuning can be performed on the socket file descriptor created during a connection for optimizing performance and building measurements. Here are the several options that can be tuned on the socket

https://linux.die.net/man/7/socket
(eg: SO_RECVBUF, SO_LINGER, etc. ..).

Would you folks think it is useful for envoy to expose an API (wrapper on `setsockopt` and `getsockopt`)available at a filter (l4/l7) abstraction to configure these settings?

I have a variation of this implementation used for an internal project. Let me know if this is something that is interesting for upstream?

Thx!
Rama
[optional *Relevant Links*:]
>https://linux.die.net/man/2/setsockopt

**Comment by mattklein123** [comment]
For the L4 filter stack, yes this sounds like a worthwhile proposal. For the L7 filter stack, I don't think so. Can you potentially provide a complete proposal? Thank you.

**Comment by ramachaitanyak** [comment]
Hello, thanks for the comments.

There are certain uses cases that we have seen where we would like to tweak the connection based on the http requests that are delivered through it. Specifically, we want to apply some intelligence based on the http headers to conserve the compute resources, memory utilization on server and preserve network bandwidth utilization.


```
If you would like to understand one particular motivation, please read ahead...

Consider a scenario where we have a single connection per user; though usually it is not the case, for the sake of identifying the motivation; I would like to propose this case.

•    With the said setup, say there are about 20,000 connections and 20,000 users accessing our application servers through envoy.
•    Each of these users has an unique IPv4 address used to establish connection and are sending requests at around 5K RPS to envoy; which envoy forwards upstream to the application server pool.
•    Say, a malicious user has about 1,000 of these connections with unique IPv4 addresses and wants to do a distributed denial of service attack through flooding http/https `get` requests to the upstream application server pool. The person would increase the requests per second on these connections from 5K RPS to 30K RPS. This would also mean; these requests would consume the network bandwidth in the multi-tenant back bone and our network infrastructure.
•    This would effect the requests per second for the good users who are genuinely interested in getting their requests served. This service to them is now degraded.

In the case, where we wanted to act purely based on IPv4 address, tuning socket options to reduce the attack footprint; at L4 layer of envoy would help. On the other hand if we would want to take action based on any of the http headers; say `user-agent` this can not be done at the L4 layer.

For this very reason, this is a proposal to expose the socket options at the L7 layer.
```
Please let me know your opinions.

Thanks!
Rama

**Comment by mattklein123** [comment]
@ramachaitanyak to date we don't allow L7 filters to directly modify the connection as there can be multiple streams per-connection, and the abstraction breaks down pretty badly if you allow connection modification. 

My suggestion for this would be to create a custom L4/L7 filter pair and have the L7 filter communicate to the L4 filter that it should set socket options.

@alyssawilk any thoughts on this?

**Comment by alyssawilk** [comment]
I have lots of thoughts on this - we've got a couple of options we set in-house from L7-L4 and they have fairly individual behavioral characteristics.  Some we only set early on a connection, some are per-stream and we have a manager which coordinates per-stream settings with live-streams to calculate what the per-connection value ought to be (and tweaks it as streams are created and destroyed).   I'd love some utility classes with generalizable rules which could be used for all of them!

We also might need a similar option for QUIC, where most things would be set per logical QUIC connection (you don't want to accidentally change the size of the send buffer for a globally shared UDP socket, but you might want it to convert into how much you'd be willing to buffer in user-space)

**Comment by mattklein123** [comment]
Per @alyssawilk, to be clear, the utility of this is obvious to me, but the APIs are tricky since we have to have a sane way for streams to interact with the connection. I will meet with @alyssawilk and discuss some use cases and then let's see if we can come up with some common utilities?

I can imagine generalizing the "L4 filter" I propose above as a generalized connection settings manager that is exposed to filters that provides some safeguards and sanity around what can be done.

**Comment by ramachaitanyak** [comment]
Thanks @mattklein123 & @alyssawilk for the feedback. We currently have an internal implementation similar to RBAC filter(L7 filter) to plug into this API. We can improve it based on the feedback. OTOH if it is convenient for you folks; I would enjoy to be a part of the aforementioned discussion if it has not already happened. I can join over a voice call. Please let me know.

Rama

**Comment by ramachaitanyak** [comment]
Hello @mattklein123 and @alyssawilk; thanks for the discussion. I am following up on this thread to gather a summary of design proposals made during the meeting with respect to having a singleton in HCM for exposing this socket options per connection.

In addition, it would be great to get opinion on the common utilities for reading the socket file descriptor.

It would be great if the design is elaborated here. I will work on the implementation once there is a consensus on it. 

Rama

**Comment by mattklein123** [comment]
This is roughly what I had in mind:

```
mklein@localhost:~/Source/envoy$ git diff
diff --git a/include/envoy/http/filter.h b/include/envoy/http/filter.h
index 116506541..ec0f60f6b 100644
--- a/include/envoy/http/filter.h
+++ b/include/envoy/http/filter.h
@@ -119,6 +119,29 @@ enum class FilterMetadataStatus {
   Continue,
 };
 
+/**
+ * An interface for a per-connection object that is created by a filter and then managed by the
+ * HTTP connection manager. This pushes singleton handling into the HTTP connection manager.
+ */
+class PerConnectionObject {
+public:
+  virtual ~PerConnectionObject() = default;
+};
+using PerConnectionObjectSharedPtr = std::shared_ptr<PerConnectionObject>;
+
+/**
+ * An interface for connection attributes that are modifiable by HTTP filters. Generally, these
+ * should be modified only via a PerConnectionObject.
+ */
+class MutableHttpConnection {
+public:
+  virtual ~MutableHttpConnection() = default;
+
+  // Fill with the things that we want HTTP filters to be able to do to the connection such as
+  // setting certain socket options, etc. Everything needs to be abstracted and then flowed through
+  // to the underlying writable Network::Connection.
+};
+
 /**
  * The stream filter callbacks are passed to all filters to use for writing response data and
  * interacting with the underlying stream in general.
@@ -132,6 +155,21 @@ public:
    */
   virtual const Network::Connection* connection() PURE;
 
+  /**
+   * Create a per-connection object. The connection manager will track whether the object exists
+   * already and if so, return it. Otherwise it will be created via the creation function. Objects
+   * are keyed by name and thus can be shared between filters if needed.
+   * @param object_name supplies the name of the object to create or fetch.
+   * @param creation_function supplies function used to create the object if it does not already
+   *        exist. The creation function will be passed a mutable HTTP connection object that it
+   *        can use for singleton operations against the connection.
+   */
+  using PerConnectionObjectCreator =
+      std::function<PerConnectionObjectSharedPtr(MutableHttpConnection& connection)>;
+  virtual PerConnectionObjectSharedPtr
+  createPerConnectionObject(const std::string& object_name,
+                            const PerConnectionObjectCreator& creation_function) PURE;
+
   /**
    * @return Event::Dispatcher& the thread local dispatcher for allocating timers, etc.
    */
```

@alyssawilk WDYT about ^?

**Comment by ramachaitanyak** [comment]
@mattklein123 & @alyssawilk this level of abstraction works for the implementation. I will wait for Alyssa to give the go-ahead before I take a stab on the implementation.

Another thought that occurred to me is whether or not this API should be OS dependent. I understand that macOS supports setsockopt and getsockopt. I am not sure about windows. Any thoughts on this ?

**Comment by alyssawilk** [comment]
I think this is fine at a high level - I'm more interested in what we do with MutableHttpConnection once we have it, so feel free to start in on this and send a draft PR my way, and you or I can tag @danzh2010 as well to make sure it'll play well with non-TCP "connections"

**Comment by ramachaitanyak** [comment]
@alyssawilk thanks for the comments. I will work on it. @danzh2010 if you have comments please let me know.

My impression for this patch; is to only include a wrapper for `getsockopt` and `setsockopt` (specifically a wrapper on http://man7.org/linux/man-pages/man2/setsockopt.2.html)

What we could do with this information; is something I have addressed as other issues like tarpit and gather metrics.

I will send a draft PR as soon as possible.

Rama

**Comment by mattklein123** [comment]
>  I'm more inclined to start with explicit options we want to set and set them via methods, so we can make clear what is supported by QUIC and across various platforms but I'll go with whatever Matt suggests makes sense

+1 to explicit for now until we prove that won't work.

**Comment by ramachaitanyak** [comment]
Hello, I have a draft patch for this. I will open a PR with draft tag soon. Working between schedules, I am trying to resolve abseil compilation issues. Should be soon to get a patch out.

Apologize for the delay.

Rama

**Comment by ramachaitanyak** [comment]
Hello, I have created a PR here https://github.com/envoyproxy/envoy/pull/8851/

I am running into these errors while building:
```
source/common/http/conn_manager_impl.cc:1993: error: undefined reference to 'Envoy::Http::ConnectionManagerImpl::per_connection_object_map_[abi:cxx11]'
source/common/http/conn_manager_impl.cc:1994: error: undefined reference to 'Envoy::Http::ConnectionManagerImpl::per_connection_object_map_[abi:cxx11]'
source/common/http/conn_manager_impl.cc:2004: error: undefined reference to 'Envoy::Http::ConnectionManagerImpl::per_connection_object_map_[abi:cxx11]'
```

I will work on resolving those; however if any of you have suggestions to fix this, please let me know.

Take a look at the PR and let me know your thoughts and hope it aligns with the initial thinking of design.

Thanks!
Rama

**Comment by yuval-k** [comment]
the linker errors is because if you have a declaration of a static member `static std::map<const std::string, PerConnectionObjectSharedPtr>  per_connection_object_map_; `  without a definition.
you need to defined it in the .cc file like so:
```
   std::map<const std::string, PerConnectionObjectSharedPtr>  ConnectionManagerImpl ::per_connection_object_map_; 
```

btw - not sure if a static variable will work here as IIUC this code can be called concurrently so it is not thread safe.

**Comment by ramachaitanyak** [comment]
Thanks @yuval-k for pointing this out. I am able to get past this error; following your suggestion.

Based on my understanding we are required to maintain a single instance of the `ConnectionManagerImpl::per_connection_object_map_` maintained per ConnectionManagerImpl instance.

This allows multiple filters running on the connection to manipulate and reuse connection states.

I recognize having a static map will allow access to multiple ConnectionManagerImpl instances to manipulate the map. I have fixed this by accessing the `parent_.connection_manager_` instance in 
`ConnectionManagerImpl::ActiveStreamFilterBase::createPerConnectionObject` and removed it from being defined as static.

Furthermore; if my interpretation is correct we still will need some synchronization primitives around the access to the map; since there could be two or more filters simultaneosly trying to access/modify the contents inside the map.

Please let me know if you have other thoughts and correct me if my interpretation is inaccurate.

Thanks!
Rama
