### ISSUE TITLE
http: Allow upper bounding lifetime of downstream connections

### ISSUE THREAD

**Issue by veshij** [envoyproxy/envoy#8302]
*Description*:
We use envoy as user-facing edge proxy behind lvs/ipvs.
During the restart of the envoy proxy connections tend to migrate to other processes.
This leads to cascading load imbalance (the last process to restart has most connections, typically several times more than in steady mode).

Does it make sense to add configuration option to HTTP Connection Manager to gracefully drain a connection after certain timeout since connection establishment? (Similar to idle timeout)

**Comment by zuercher** [comment]
Sounds like you're asking for a "max connection age" or "max requests" features for http connection manager.

You could also look at using the hot restart mechanism to avoid shutting down listeners. There may periodically be versions of Envoy that cannot be upgraded with hot-restart, though.

**Comment by veshij** [comment]
>Sounds like you're asking for a "max connection age" or "max requests" features for http connection manager.
Yes, "max connection age" sounds right.

>You could also look at using the hot restart mechanism to avoid shutting down listeners. There may periodically be versions of Envoy that cannot be upgraded with hot-restart, though.
Even with hot restart we'll see imbalance for nodes being allocated/rebooted.

**Comment by euroelessar** [comment]
> You could also look at using the hot restart mechanism to avoid shutting down listeners. There may periodically be versions of Envoy that cannot be upgraded with hot-restart, though.

We're using SO_REUSEPORT-based graceful deploy logic, it has exactly the same properties in regard of traffic imbalance as hot restart.
