### ISSUE TITLE
"no cluster match for URL" error for grpc service

### ISSUE THREAD

**Issue by ChangyuWang** [envoyproxy/envoy#8305]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: *no cluster match for URL*

*Description*:
envoy version: 1.10

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *no cluster match for URL*

*Description*:

I used enovy to proxy my grpc service,  route table had been configured correctly, but no match cluster found in envoy.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:

```
"dynamic_active_listeners": [
{
"listener": {
     "version_info": "2019-08-26T06:39:33Z/1699",
     "listener": {
      "name": "::1_15003",
      "address": {
       "socket_address": {
        "address": "::1",
        "port_value": 15003,
        "ipv4_compat": true
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "config": {
           "rds": {
            "route_config_name": "15003",
            "config_source": {
             "ads": {}
            }
           },
           "use_remote_address": false,
           ...

   "dynamic_route_configs": [
    {
     "version_info": "2019-08-26T07:31:01Z/11",
     "route_config": {
      "name": "15003",
      "virtual_hosts": [
       {
        "name": "eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local:80",
        "domains": [
         "eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local",
         "eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local:80",
         "eipbinding-service",
         "eipbinding-service:80",
         "eipbinding-service.prj-vnpd-uver2-dev.cluster.local",
         "eipbinding-service.prj-vnpd-uver2-dev.cluster.local:80",
         "eipbinding-service.prj-vnpd-uver2-dev.svc",
         "eipbinding-service.prj-vnpd-uver2-dev.svc:80",
         "eipbinding-service.prj-vnpd-uver2-dev",
         "eipbinding-service.prj-vnpd-uver2-dev:80"
        ],
        "routes": [
         {
          "match": {
           "path": "/uver.EIPBindingService/DescribeEIPBinding"
          },
          "route": {
           "cluster": "outbound|80|s1|eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local",
           "timeout": "0s",
           ...
```

*Logs*:

```
[2019-08-26 07:32:20.649][33][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:548] [C2][S17556666753870659064] request headers complete (end_stream=false):
':method', 'POST'
':scheme', 'http'
':path', '/uver.EIPBindingService/DescribeEIPBinding'
':authority', 'eipbinding-service.prj-vnpd-uver2-dev:80'
'content-type', 'application/grpc'
'user-agent', 'grpc-go/1.23.0'
'te', 'trailers'
'grpc-timeout', '29999985u'
'x-request-id', '3cbe2f0d-9c47-4479-b18a-5d0c163c4a7f'

[2019-08-26 07:32:20.649][33][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:774] [C2][S17556666753870659064] decode headers called: filter=0x38dae10 status=0
[2019-08-26 07:32:20.649][33][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:774] [C2][S17556666753870659064] decode headers called: filter=0x38dae60 status=0
[2019-08-26 07:32:20.649][33][debug][router] [external/envoy/source/common/router/router.cc:277] [C2][S17556666753870659064] no cluster match for URL '/uver.EIPBindingService/DescribeEIPBinding'
[2019-08-26 07:32:20.649][33][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1120] [C2][S17556666753870659064] encode headers called: filter=0x3b84080 status=0
[2019-08-26 07:32:20.649][33][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1225] [C2][S17556666753870659064] encoding headers via codec (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '12'
'date', 'Mon, 26 Aug 2019 07:32:20 GMT'
'server', 'envoy'
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by zuercher** [comment]
Is the cluster `outbound|80|s1|eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local` present? You can curl the admin interface's `/clusters` endpoint and see if it exists.

**Comment by ChangyuWang** [comment]
@zuercher
the cluster is present.

```
    {
     "version_info": "2019-08-26T06:08:52Z/1684",
     "cluster": {
      "name": "outbound|80|s1|eipbinding-service.prj-vnpd-uver2-dev.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       },
       "service_name": "outbound|80|s1|eipbinding-service.prj-vnpd-uver2-dev.svc.cluster.local"
      },
      ...
```

**Comment by zuercher** [comment]
That cluster name and the one in the config above are different. The route config's cluster ends with `dev.svc.cluster.local` and the cluster name ends with `dev.cluster.local`. (The service_name field is only used by EDS -- routes look up clusters by name.)

**Comment by jmprusi** [comment]
I've been hit by this too...

I think it is related to https://github.com/envoyproxy/envoy/issues/886, we've been able to "fix" it by using the provided solution in that issue:

```
domains: [ "host", "host:*" ]
```

But it would be amazing to have a fix for envoy to match the gRPC authority properly.
