### ISSUE TITLE
Azure pipelines fail when a proto field is modified in a PR

### ISSUE THREAD

**Issue by venilnoronha** [envoyproxy/envoy#8314]
*Title*: Azure pipelines fail when a proto field is modified in a PR

*Description*:
When a proto field is modified via incremental commits in a single PR, the Azure pipelines fail.

*Repro steps*:
1\. Create a PR with a change in the `api/` protos. The first change should add a new field to a proto.
2\. Add another commit to the PR by modifying the type of the same field. This should cause the Azure pipelines to fail and exit with the following error.
```
Bash exited with code '1'.
```

*Logs*:
Here's the log from PR #8226.
```
envoy/api/v2/cds.proto:703:34: Field number 42 has already been used in "envoy.api.v2.Cluster" by field "dns_failure_refresh_rate".
```

**Comment by mattklein123** [comment]
Lets discuss in the PR in question for now.
