### ISSUE TITLE
How to measure the latencies incurred by envoy when processing the incoming requests

### ISSUE THREAD

**Issue by lekkalapudi** [envoyproxy/envoy#8317]
Envoy emits various statistics with respect to request processing times, such as total duration, upstream response time, request time with respect to external authz cluster etc. When envoy proxy is integrated with external authorization system. Was just curious about the best approach to zero in on latencies incurred by envoy proxy it self in processing the request?

**Comment by nareddyt** [comment]
Have you looked into enabling tracing? Traces should contain information about each downstream request, as well as multiple child spans for each upstream request. This information includes request method, path, timing, etc.

This would give you visual data you can manually inspect, not sure if you wanted data that's easier for other programs to read.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing

**Comment by lekkalapudi** [comment]
@nareddyt thanks for your response, i'm actively pursuing distributed tracing approach. Just wanted to check if there is any way to compute the same using stats generated by envoy
