### ISSUE TITLE
custom proxy version as stat

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#8318]
Many deployments would like a custom proxy version pushed as a stat to stats sinks so that is used along with other stats to compare the behaviours. Current envoy pushes part of SHA `server.version` stat that is not fully usable if envoy version is wrapped with custom proxy wrappers.

The proposal is to introduce a new `proxy_version` field in in bootstrap config and when it is set, the `server.version` should use that value instead of the current value. If there is a value in also sending part of git sha, we can introduce a new stat called `server.proxy_version`.

**Comment by ramaraochavali** [comment]
@mattklein123 @htuch Do you think it is reasonable?

**Comment by howardjohn** [comment]
It could also be any metadata and be generic if that would be more useful, although that may be a bit overkill

**Comment by mattklein123** [comment]
I've always viewed sticking the SHA into a gauge is a hack, though if we already do that for operational reasons, it seems fine to me to allow that to be overridden via configuration. I think if you do allow via configuration it should be an integer though to make it clear that it is getting converted to a gauge?

**Comment by ramaraochavali** [comment]
@mattklein123 Sorry, if it was not clear from my explanation above, actually the `server.version` is converted in to an int from git SHA like this
https://github.com/envoyproxy/envoy/blob/master/source/server/server.cc#L312

You brought up a very good point about defining it as an integer to make it clear that it is getting converted to a gauge. 

Thinking about it more, since typically most of the deployments use semver, should we make it a struct like 
```
proxy_version {
 major:
 minor:
 patch:
}
```
and we can push them as individual stats and let the deployments use it as they want? This may be most generic solution?

**Comment by mattklein123** [comment]
> and we can push them as individual stats and let the deployments use it as they want? This may be most generic solution?

Sure that sounds fine. If we do that I would just make the whole thing optional and just create the stats on demand?

**Comment by ramaraochavali** [comment]
> Sure that sounds fine. If we do that I would just make the whole thing optional and just create the stats on demand?

Sure. We can do that.

**Comment by htuch** [comment]
@ramaraochavali I don't think we should force semver on this particular effort, since it's likely to be confused with the Envoy semver and not everyone will want it. I would just make this a `repeated uint64` or something and synthesize stats from that. It's a weird hacky encoding, and anyone who wants it really needs to know what they are doing.

**Comment by ramaraochavali** [comment]
@htuch If that is the case, I would just leave it with one int and let people encode the version with in it and override `server.version` with this, if it is set. If a custom encoding is followed, I am not seeing benefit of `repeated uint64` and Envoy employing a special logic to synthesize the stats. Single int may be simpler to deal with.

**Comment by howardjohn** [comment]
@ramaraochavali I may be missing something, but how/why do we encode the version as an int? How are you making `1.2.3` into a single int? Or how are you making somethign like `06647a2aa53879cd78414131f256647fbea5e29f/1.12.0-dev/Clean/RELEASE/BoringSSL` into a single int?

**Comment by howardjohn** [comment]
In Istio control plane components we set a gauge like `istio_build{component="pilot",tag="1.3.0-152-gf39281b5b"} 1` which seems to work well. What is the benefit of an integer? I think it has a lot of limitations. For example, version `0.1.12` becomes `112` which is the same as `1.1.2`.

**Comment by mattklein123** [comment]
Envoy gauges are integer only and we don't have a direct API for setting tags, as not all stat backends support tags.

@ramaraochavali I'm fine with a single integer that overrides the existing version gauge if that is less controversial (as long as it is well documented).

**Comment by ramaraochavali** [comment]
@htuch are you good with single integer approach?

**Comment by htuch** [comment]
@ramaraochavali sure. My only concern above was forcing semver on arbitrary end users.

**Comment by ramaraochavali** [comment]
@howardjohn missed to respond your point 
>  I think it has a lot of limitations. For example, version 0.1.12 becomes 112 which is the same as 1.1.2.

Agree it has some limitations and is not an ideal solution- But if we encode the version as `xxxyyyzzz` form  - `0.1.12` can be encoded `1012` where as `1.1.2` can be encoded as `1001002` - so we always parse from right get the necessary components (3 digits) and set to 0 if we do not have sufficient digits as in case of `1012`. Not ideal but works.
