### ISSUE TITLE
Envoy pre-compiled binaries not working on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ravgupms** [envoyproxy/envoy#8319]
*Title*: *Envoy pre-compiled binaries not working on Windows Subsystem for linux*

*Description*:
> On a Windows machine, I enabled [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and installed Ubuntu as part of it. But when I try to run [per-compiled binaries of Envoy](https://www.getenvoy.io/platforms/envoy/ubuntu/), it crashes while trying to connect to upstream service.

![image](https://user-images.githubusercontent.com/32916246/65369276-c3d26600-dbff-11e9-9d90-e6165b19b315.png)

*Repro steps*:
> 1) On a Windows machine, enable Windows Subsystem for Linux: [link](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
>2) Install Envoy using following steps.
https://www.getenvoy.io/platforms/envoy/ubuntu/
>3) Download sample google example config
> 4) Run Envoy: envoy -c google_com_proxy.v2.yaml
> 5) Hit curl http://localhost:10000/

*Config*:
>https://github.com/envoyproxy/envoy/blob/98c35eff10ad170d550fb5ecfc2c6b3637418c0c/configs/google_com_proxy.v2.yaml

**Comment by mattklein123** [comment]
FYI this is not a platform that is likely to receive much community support. I would suggest reporting this to Microsoft.

**Comment by lizan** [comment]
@ravgupms are you on WSL 1 or WSL 2? which version are you running? stable?

**Comment by lizan** [comment]
I was able to repro this in WSL 1 but not in WSL 2. The crash is due to the RELEASE_ASSERT [here](https://github.com/envoyproxy/envoy/blob/v1.11.1/source/common/network/connection_impl.cc#L239). I think this is because WSL doesn't implement `getsockname` system call correctly in WSL 1.

@ravgupms you may want to report to https://github.com/microsoft/WSL, there are several issues around about `getsockname` already. Or just use WSL 2.

**Comment by ravgupms** [comment]
Thanks @lizan for the info!

I have opened a ticket on WSL team.
https://github.com/microsoft/WSL/issues/4538

In the meantime, I will try to check on WSL2 but looks like I have to be on their fast insider ring to get the required build to install WSL2
