### ISSUE TITLE
connection refused error after Envoy server state is Live

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#8321]
After Envoy server state is Live, for some very short duration we get connection refused errors occasionally while accessing the egress listener port.

This is after we see the line "all dependencies initialized. starting workers". 

I think this is because by the time this log line comes, Envoy got all listeners from control plane and init manager is marked "Ready" - After this Envoy creates listeners on the workers via dispatcher posts and starting the event loop on each worker.

Is there an easy way to tie worker initialization to server state - so that Server declares it self Live only after workers are fully initialized?

On a related note, would it make sense to start worker event loop first and then create listeners - so that listeners that get created would not have wait till all the listeners are created (though very little time only) to receive traffic? - Or Am I misunderstanding this piece of code?
https://github.com/envoyproxy/envoy/blob/98c35eff10ad170d550fb5ecfc2c6b3637418c0c/source/server/listener_manager_impl.cc#L815

**Comment by mattklein123** [comment]
It is technically possible that we would not mark the server live until after all listeners have started listening on their sockets, but I'm not sure it's really worth the code churn. How is this actually effecting your production deployment?

**Comment by ramaraochavali** [comment]
Our liveness probes are tied to this server state - so technically it might create problems if Envoy declares it self Live but listeners are not listening sockets. I have not seen this happen in production  yet. However I have seen this happen occasionally on test systems. I am also not sure if it is worth the code churn here - so probably good to wait.

For my education, regarding my second question, do you think it would be better to start the worker loop thread routine before listeners start listening - or it does not make any practical difference?

**Comment by mattklein123** [comment]
> For my education, regarding my second question, do you think it would be better to start the worker loop thread routine before listeners start listening - or it does not make any practical difference?

I don't think it would matter as the event loop needs to run before the listeners would actually start listening, so there would still be a race condition (as the code is written today).

FWIW the readiness probes we use at Lyft actually trying to send a health check request over a listener port, which is why we have not seen this issue.

**Comment by ramaraochavali** [comment]
@mattklein123 Thanks. Will close this for now.
