### ISSUE TITLE
stats: counter created by name for http1/http2 codecs on every admin access

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#8324]
When adding integration tests for https://github.com/envoyproxy/envoy/pull/8116 I noticed that a counter named `"http1.metadata_not_supported_error"` was created by name on every admin request. I am not sure if this impacts proxy requests as well.

Of course the `stats.counter(std::string)` methods are not called on production; this is enforced via check_format. However the stats-macros are free to use. Most often it appears they are used when constructing config or context objects during init, but in the case of the http1 codec they appear to be created per-request.

This bug blocks #4980 and also makes #8116 more annoying, though we can just have kind a messy test in that PR that expects this request to be present.

For HTTP2 the list of stats looked up by name on every request includes:
```
http2.inbound_empty_frames_flood
http2.inbound_priority_frames_flood
http2.inbound_window_update_frames_flood
http2.outbound_control_flood
http2.outbound_flood
http2.rx_messaging_error
http2.rx_reset
http2.too_many_header_frames
http2.trailers
http2.tx_reset
```

**Comment by mattklein123** [comment]
cc @soya3129 

Yeah we should definitely fix this such that these stats are effectively created once at the cluster/HCM level so that they don't have to be looked up for each connection. Nice find!

**Comment by jmarantz** [comment]
@danzh2010

**Comment by mattklein123** [comment]
Fixed.
