### ISSUE TITLE
Redis Proxy isn't reporting INFO (ready) to redis client 

### ISSUE THREAD

**Issue by mosespx** [envoyproxy/envoy#8328]
https://github.com/luin/ioredis

the following client is looking for "Ready" state from redis using the `INFO` command
For now, the `INFO` command isn't supported in envoy and I can workaround using the `ioredis.io` option: `enableReadyCheck` but then I waive the waiting to the "Ready" event from redis cluster which can be risky.

[options.enableReadyCheck] | boolean | true | When a connection is established to the Redis server, the server might still be loading the database from disk. While loading, the server not respond to any commands. To work around this, when this option is true, ioredis will check the status of the Redis server, and when the Redis server is able to process commands, a ready event will be emitted.
-- | -- | -- | --

How can I achieve this check?

**Comment by mattklein123** [comment]
@envoyproxy/redis-dev ^

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
This is currently unsupported. The INFO command semantics don't make sense with respect to Envoy- you are querying a cluster of Redis nodes, and there is no way to choose which one to use. Different nodes have different INFO responses. What is your preferred behavior from INFO against a cluster of Redis nodes?

**Comment by mosespx** [comment]
I'm not looking to run `INFO` against the cluster, I just want to make sure the client gets the `Ready` event from the redis cluster before it starts using it.

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
If I understand your question correctly, you do in fact need to run `INFO` (or rather, your client does). If this is correct, can you explain what behavior you would expect from `INFO` against a cluster?

Alternatively, is it possible to modify the client behavior to use a different ready signal- ie run a successful SET or GET?
