### ISSUE TITLE
Use Source IP for hash 

### ISSUE THREAD

**Issue by x15zhang** [envoyproxy/envoy#8341]
Can envoy support using source ip for hashing for tcp upstreams?
Becasue nginx support the feature:
```
upstream backend {
    hash $remote_addr;
    server 10.95.110.45:12001;
    server 10.95.220.46:12002;
}
```

**Comment by hzxuzhonghu** [comment]
@mattklein123 @htuch we need this feature too

**Comment by mattklein123** [comment]
IIRC we don't support any hashing currently for tcp_proxy: https://github.com/envoyproxy/envoy/blob/ccb303f6f1337966570e4b445d940ccdf76b8f96/source/common/tcp_proxy/tcp_proxy.h#L194

I think this should be easy/useful to add.
