### ISSUE TITLE
ext_authz: config ignored if route does not specify cluster

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#8355]
As in #8262, the ext_authz filter is a no-op if a route is configured with a direct response action or redirect.

Notably, the filter uses the route/route_entry to obtain a ClusterInfoConstSharedPtr which is used for recording stats. Instead, I think that the filter should produce stats in the context's scope (see the JWT Authn filter, for example) and only produce cluster-specific stats if a cluster is available. In any event, it shouldn't silently skip auth.

A related corner case is that it's possible for the ext_authn response to modify headers and clear the route cache. The re-computed route might send proxy requests to a different cluster (or use a direct response or redirect) but the stats always go to the original cluster.

See also #8250 where the ext_authz filter produced no effect because the header used for cluster selection (via [RouteAction.cluster_header](https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/route/route.proto.html#envoy-api-field-route-routeaction-cluster-header)) wasn't set yet.

**Comment by zuercher** [comment]
@nezdolik is going to work on this.

**Comment by derekargueta** [comment]
@zuercher mind assigning @nezdolik and removing `help wanted`?
