### ISSUE TITLE
Dynamic reload of filter config without listener drain

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#8364]
[ If this is already available, please close this issue].

_I am creating this issue for posterity, and do not expect a resolution due to the complexity issues involved._

context: Certain filters like RBAC etc. have the access control rules [something that changes dynamically] embedded inside the filter as static configuration. There are other examples but rbac is a good use case for this problem. When access control rules change, we end up sending an update to the listeners with the updated filter config. This causes all existing connections to drain. A more efficient thing to do would be to reload the rbac filter config alone, and force the rbac filter instances to run some event handler [e.g., onConfigUpdate], wherein they can reevaluate existing connections to check if they still pass the rbac rules.

To realize something like this, we would need to decouple the filterConfig state from the filter implementation. A separate thread could fetch the state dynamically or periodically. All new instances of a filter would do a read of this filter state from the centralized thread, during initialization. All filters would also have to implement this onConfigUpdate event handler to get notified about changes to this config. When the filter's config changes, the centralized thread could notify all the non-draining listeners about this config update which in turn can propagate it to the filter instances. 

This model has several drawbacks, starting with a bottleneck on this centralized thread to read in the config on every new connection [we could optimize this piece]. We could piggyback on LDS updates but make the hash comparison more fine grained by checking individual filters [if the filter chain list has not changed]. Followed by notification mechanism across all cores.

**Comment by mattklein123** [comment]
@rshriram I think this is a dup of https://github.com/envoyproxy/envoy/issues/7867. We plan on implementing this.

**Comment by rshriram** [comment]
hmm yeah.. this is a dup for sure
