### ISSUE TITLE
Add systemd service config to rpm packages envoy

### ISSUE THREAD

**Issue by patsevanton** [envoyproxy/envoy#8387]
I installed envoy by instruction
https://www.getenvoy.io/platforms/envoy/centos/
But rpm getenvoy-envoy dont have systemd service config.
Please add systemd service config to rpm packages envoy

**Comment by lizan** [comment]
@patsevanton https://github.com/tetratelabs/getenvoy.io/issues/100, we didn't add systemd service and wrappers intentionally because use case varies, a sample systemd config is in the issue.
