### ISSUE TITLE
Dynamic configuration of envoy for whitelisted IPs 

### ISSUE THREAD

**Issue by spyroslalos** [envoyproxy/envoy#8388]
Dynamic configuration of envoy for whitelisted IPs 

*Description*:
I have a listener like this one below whitelisting some IPs using the RBAC filtering

`  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
      use_proxy_proto: true
      filters:
      - name: envoy.tcp_proxy
        config:
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
          stat_prefix: ingress_tcp
          cluster: my_service
      - name: envoy.filters.network.rbac
        config:
          stat_prefix: tcp.ip_restrictions.
          rules:
            action: ALLOW
            policies:
              "allow_trusted_ips":
                permissions:
                  - any: true
                principals:
                  - source_ip:
                      address_prefix: some.trusted.ip
                      prefix_len: 32
                  - source_ip:
                      address_prefix: 10.9.0.0
                      prefix_len: 16`

Question:

Is there a way to dynamically update the envoy configuration with a new list of IPs without an envoy restart?

I guess LDS is my only option, but haven't seen a proper example of how to apply it.
Anyone working on a similar issue?

**Comment by cetanu** [comment]
You would need to do this using LDS, which can be either GRPC/JSON-REST or file-based.

If you use a file for example, envoy will reload it every time it is modified. You could write something trivial to update the file periodically... or you can take a look at some of the control-plane libraries/implementations out there to provide the dynamic config via tcp.

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/
