### ISSUE TITLE
[Help wanted] Vscode debugging can't mount source code

### ISSUE THREAD

**Issue by zonghaishang** [envoyproxy/envoy#8394]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: *One line description*

*Description*:
How to view the code in vscode debugging？

Compile everything in my mac，`bazel build -c dbg --copt=-fno-limit-debug-info //source/exe:envoy-static`

Here is my git repo: `https://github.com/zonghaishang/envoy.git` branch:`local_develop`

Here is my debug config（lanch.json）:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bazel-bin/source/exe/envoy-static",
            "args": ["-c", "/Users/yiji/opensource/envoy/bazel-bin/source/exe/basic-front-proxy.yaml"],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
        },
    ]
}
```

![image](https://user-images.githubusercontent.com/15549777/65695956-076b1b00-e0ab-11e9-9c9f-0cd50776d741.png)

```
➜  envoy git:(local_develop) clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by zonghaishang** [comment]
`basic-front-proxy.yaml` file can be found in envoy/examples

**Comment by zonghaishang** [comment]
@mattklein123 @alyssawilk  please take a look.

**Comment by zuercher** [comment]
Debugging bazel-compiled binaries on MacOS has never worked reliably: https://github.com/bazelbuild/bazel/issues/6327. This problem is not exclusive to Envoy.

For the Ubuntu build failure, `C++ compilation of rule '//source/exe:terminate_handler_lib' failed (Killed)` implies to me that something external to bazel killed the process. I can reliably build Envoy in an Ubuntu 16.04 VM with 8 GB of RAM. Less memory, particularly if the VM is configured for 4 or more CPU cores often results in memory allocation failures. Bazel's error messages are often cryptic in this case.

**Comment by zonghaishang** [comment]
@zuercher  thank you for your reply.
-----
In order to speed up the compilation, I did allocate 6 core CPUs to the virtual machine. At present, I have solved the debugging problem in the mac, as a beginner of envoy, thank you again.

I am closing this issue now.

**Comment by konste** [comment]
@zonghaishang How have you solved the debugging problem in the Mac?
