### ISSUE TITLE
re-deprecate opaque Struct config

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8403]
Structs are deprecated once and un-deprecated in #6346. Now protobuf hashing are sorted and moving away from hashing in long term (#8231, #8301). So we can deprecate this and migrate all docs/examples.

cc @htuch @alyssawilk @moderation

**Comment by htuch** [comment]
@lizan agreed. We have a short window to have the deprecation actually remove it from v3, if you can land the relevant PRs in the next week or so. If not, we can do the deprecation in v3 and removal in v4.

**Comment by htuch** [comment]
Actually, while working on https://github.com/envoyproxy/envoy/issues/8082, I realized that it might end up being best to tackle this in 1.12.0. Specifically, if we can ensure all opaque `Struct`s have a type URL included, we can identify whether a `Struct` is from v2 or v3alpha. After chatting with @lizan, the best course of action seems to be:

1. Deprecate the existing untyped `Struct` fields.
2. Introduce a new typed Struct, e.g.
```
message TypedStruct {
  string type_url = 1;
  google.protobuf.Struct value = 2;
}
```

The v3alpha API will no longer have the untyped `Struct` fields, and we can use the `type_url` going forward to figure out major version.

In addition to tagging the relevant fields as deprecated, we need to:
1. Implement the ability for Envoy to accept `TypedStruct` embedded inside `Any` fields. There should be some validation that the `type_url` matches the filter's empty proto type name.
2. Update all docs and examples to typed configs.

**Comment by lizan** [comment]
There's a few places missed from #8472, @yanavlasov can you deprecate them as well?

```
api/envoy/api/v2/auth/cert.proto:113:    google.protobuf.Struct config = 2;
api/envoy/api/v2/listener/udp_listener_config.proto:26:    google.protobuf.Struct config = 2;
api/envoy/config/filter/accesslog/v2/accesslog.proto:248:    google.protobuf.Struct config = 2;
```
