### ISSUE TITLE
Access logging possible to collect only error logs in http and tcp connection manager?

### ISSUE THREAD

**Issue by arun0704** [envoyproxy/envoy#8413]
Title:- Access logging possible to collect only error logs in http and tcp connection manager?

In Our project Envoy is printing so many access logs in the performance test when we are running load test (means many connections) for created envoy listeners . Is this possible to enable only error logs in access logging. Possible with this option any patch can be provided from envoy community?.

**Comment by derekargueta** [comment]
You can use an [Access Log Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto#envoy-api-msg-config-filter-accesslog-v2-accesslogfilter) to filter responses by status code to only log 5xx responses.
