### ISSUE TITLE
gRPC server receives request after 1s and client doesn't receive the response quickly

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#8414]
**Issue Template**

*Title*: gRPC server receives request after 1s and client doesn't receive the response quickly

*Description*:

We found we have Jaeger traces like the below one sometimes, the gRPC server receives the request after a lont time, then returns quickly, but the client still doesn't receive the response in time. Our Jaeger data is collected in Envoy via zipkin collector.

![Jaeger_UI](https://user-images.githubusercontent.com/1253659/65752354-359a3a80-e13f-11e9-8387-9a1d2aecf6dc.png)

From the above screenshot, we can see first the `cms` sent a gRPC request to `content`, `content` received the request after about 1s, then `content` sent the response to `cms`, but `cms` didn't receive the response and timeout because the grpc timeout is 2s.

Here's some details:
![FireShot_Capture_006_-_Jaeger_UI_-_jaeger_production-public_tubi_io](https://user-images.githubusercontent.com/1253659/65753043-b3127a80-e140-11e9-9fc6-d27d4bf4b526.png)

We guess there are two possibilities:
1. The network was bad at that time
2. Envoy was slow to handle the request.

Are there logs and metrics that can help us to verify if it's Envoy's problem?

**Comment by zuercher** [comment]
The "UT" response flags makes me think there were multiple requests to the content cluster and that at least one timed out. I can't say why that doesn't cause multiple spans, but I'd look into that.
