### ISSUE TITLE
Remove Network::Connection::delayedCloseTimeout() from public interface

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#8419]
This method is actually only used within ConnectionImpl. It's not necessary to be part of Connection interface. We should be able to remove it.

Note that currently it's mocked out in MockConnection. Simply removing the interface might cause test failure.

**Comment by koneko096** [comment]
HI. I'd like to work on this. Can you elaborate on what exactly is required here?

**Comment by mattklein123** [comment]
@koneko096 you want to remove this:

https://github.com/envoyproxy/envoy/blob/3a4e276dc3da43010d9ceb846c9b7100889448cd/include/envoy/network/connection.h#L292-L295

And then make the function private inside connection_impl.cc, and remove it in the various places in which it was defined just to adhere to the interface.

**Comment by koneko096** [comment]
Okay. I guess I will take this issue
