### ISSUE TITLE
Improve build experience when consuming prebuilts outside of CI

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#842]
Today, we consume prebuilt external deps in CI via `ci/WORKSPACE` and `ci/prebuilt/BUILD`. Other folks who want to build Envoy are also interested in using their own versions of these libraries.

We should both document how to follow the CI prebuilt flow, make it less clunky (e.g. add some .gitignore entries so that folks don't have dirty trees) and make `ci/prebuild/BUILD` less verbose - ideally we can just specify the `--prefix` of each library (or a global `--prefix` if that's how the environment looks like on the build machine).

@mattwoodyard

**Comment by mattklein123** [comment]
I think this is basically fixed at this point so just going to go ahead and close. We can open specific issues with the current scheme as needed.
