### ISSUE TITLE
upstream: reference to optional lastEjectionTime() doesn't check it exists

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#8420]
Hi -- I don't have a repro for this but https://github.com/envoyproxy/envoy/blob/ef9139a991fb9f7df676430f626b32db93a06932/source/common/upstream/outlier_detection_impl.cc#L336 looks like it has a bug.

It should be checking to see if lastEjectionTime() has a value before taking the value.

**Comment by jmarantz** [comment]
Could eject() race with checkHostForUneject()? E.g. in thread 1:
```
eject calls host_.lock()->healthFlagSet(Host::HealthFlag::FAILED_OUTLIER_CHECK);
last_ejection_time is not set yet
```
then context-swtich to thread 2:
```
checkHostForUneject() is called
if (!host->healthFlagGet(Host::HealthFlag::FAILED_OUTLIER_CHECK)) { passes through
last_ejection_time is accessed
```
Is that plausible? If so we could mutex-protect a few member-vars...it's a little suspicious that there are some atomics here but no mutexes ensuring synchronization. It might be also possible to just re-order the statements in eject() to eliminate this, but it feels like then we should hold the ejection time in an atomic too.

....

Thinking about how this might be working a little more, this could also happen if there were two DetectorHostMonitorImpl which point to the same host, which is held in the structure as a `weak_ptr<Host>`. I think the use of `weak_ptr` here conveys a possibility that two different `DetectorHostMonitorImpl` instances point to the same Host, and thus the guard-statement that @junr03 referenced at the top of `checkHostForUneject()` may not be consistent with the DetectorHostMonitorImpl.

So...that seems to indicate there can only be one `DetectorHostMonitorImpl` per `Host`, but then I don't know why the weak_ptr.

And I'm still not sure whether in production two different threads may access `checkHostForUneject()` and `eject()`.

@junr03 @mattklein123

**Comment by jmarantz** [comment]
Are we relying on exception propagation across libevent callbacks?
Or catching exceptions somewhere that might be thrown in the lastEjectionTime accessor?

It's possible the way we compile stuff locally might make that behave differently.

**Comment by jmarantz** [comment]
Here's the stack-trace from where we saw this crash:
```
std::__u::__throw_bad_optional_access
std::__u::optional::value
Envoy::Upstream::Outlier::DetectorImpl::checkHostForUneject
Envoy::Upstream::Outlier::DetectorImpl::onIntervalTimer
Envoy::Upstream::Outlier::DetectorImpl::DetectorImpl::$_0::operator()
std::__u::__invoke
std::__u::__invoke_void_return_wrapper::__call
std::__u::__function::__default_alloc_func::operator()
std::__u::__function::__policy_invoker::__call_impl
std::__u::__function::__policy_func::operator()
std::__u::function::operator()
Envoy::Event::TimerImpl::TimerImpl::$_0::operator()
Envoy::Event::TimerImpl::TimerImpl::$_0::__invoke
event_process_active_single_queue
event_process_active
event_base_loop
Envoy::Server::InstanceImpl::run
Envoy::MainCommonBase::run
...
```
I don't know much about this code path but I was guessing (without data) this might have been during shutdown.

**Comment by mattklein123** [comment]
> Are we relying on exception propagation across libevent callbacks? Or catching exceptions somewhere that might be thrown in the lastEjectionTime accessor?

No, definitely not. I will take a look at the code later today or tomorrow. I would like to see if I can see the bug before we merge the other PR.
