### ISSUE TITLE
xDS client endpoint discovery

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8421]
Current plan-of-record is to have `ConfigSource` indicate the version (and hence service endpoints), allowing the xDS client to select the correct URLs and translators to use on configuration ingestion.

**Comment by Shikugawa** [comment]
@htuch In my recognition, It enables to update xDS client config like `eds_config` dynamically. For example, update subscribed xDS server(xDS v1) when updating config signal was injected to them and disconnect. after that, establish connection with new xDS server(xDS v2). Please point out my opinion if this is wrong.

**Comment by htuch** [comment]
@Shikugawa I'm not anticipating highly dynamic behavior here; instead we should just expect the more recent management servers and bootstraps are configured to deliver xDS that uses the new config source type, while Envoy retains the ability to still speak to older xDS servers if needed.

**Comment by Shikugawa** [comment]
@htuch So to speak, I think that we need to allow multiple `ApiConfigSource` on single `ConfigSource`.

**Comment by htuch** [comment]
@Shikugawa I think eventually we want to support clients able to try one endpoint at version X and fallback, but for now we can support just a well specified endpoint / config source, at least for 1.13.0

**Comment by htuch** [comment]
Fixed in https://github.com/envoyproxy/envoy/pull/9526

**Comment by htuch** [comment]
I'm reopening this issue as there is some demand for the ability for (in simple cases) to be able to do rollouts using a mechanism that does fallback as described in https://github.com/envoyproxy/envoy/issues/8421#issuecomment-567363234.

**Comment by htuch** [comment]
CC @Shikugawa @mattklein123 @snowp @lita @jyotima

**Comment by htuch** [comment]
See also https://github.com/envoyproxy/envoy/issues/10776 as an alternative approach to rollouts.

**Comment by lita** [comment]
This would be great, as specifying the bootstrap file and rolling that out is painful.

**Comment by mattklein123** [comment]
FWIW I prefer https://github.com/envoyproxy/envoy/issues/10776 over this. IMO it does the same thing and is easier to reason about with less config needed.

**Comment by htuch** [comment]
I think this is obsoleted by https://github.com/envoyproxy/envoy/issues/10776.
