### ISSUE TITLE
protoxform tests

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8428]
We've been developed `protoxform` for the vN -> V(N+1)alpha transform described in https://github.com/envoyproxy/envoy/pull/8399. So far, we've manually inspected diffs against v2 and previous runs of `protoxform` to confirm that behavior is correct. This makes sense while we prototype and define the intended behaviors of the tool. Longer term (post 1.12.0), we will want some tests though.

This task tracks creating some tests for `protoxform`. I think some "golden proto" style tests make the most sense, i.e. example inputs/outputs and proto diffing for correctness. A good example of a similar tool with solid testing is https://github.com/envoyproxy/protoc-gen-validate.

**Comment by Shikugawa** [comment]
@htuch I'm planning to tackle this issue. my implementation loadmap is

1. call protoxform.py by executing build test proto data with protoxform aspect
2. read transformed and golden proto, and diff them

This operation is in single python script, for example `tools/protoxform_test.py`. And add `tools/protoxform_test_data/test` and `tools/protoxform_test_data/golden` for sample data which is used by execution script.

Would you mind letting me know about tackling this issue?

**Comment by htuch** [comment]
@Shikugawa sounds great, golden protos are the way to go IMHO. I would aim to keep each individual proto very simple and self contained, exercising just one specific things under test. I think a great example of this kind of test input is the way in which we've structured the `check_format` tests, see https://github.com/envoyproxy/envoy/tree/master/tools/testdata/check_format
