### ISSUE TITLE
Surfacing TLS/SSL related errors to the filter stack

### ISSUE THREAD

**Issue by nrjpoddar** [envoyproxy/envoy#8432]
*Title*:  **Way to surface TLS/SSL related errors to custom Envoy filters**

*Description*:
Currently, Envoy network filters have no way to get information related to SSL/TLS handshake errors. There are few SSL related errors in Envoy but they are at a Listener level and don't carry all the required context.

The use case here is in Istio where we add special filters for both TCP & HTTP (Mixer filters) which create stats with additional context from the environment which is very powerful. These metrics currently have a blind spot as when you have SSL/TLS related errors, none of the filter APIs & callbacks have the relevant SSL error information to generate the appropriate telemetry.

I'm creating this issue to get guidance on how we can get this information correctly from Envoy to custom filters that is added by Istio or any other system using this mechanism to generate telemetry.

*Relevant Links*:
Related Istio bug: https://github.com/istio/istio/issues/13791

**Comment by nrjpoddar** [comment]
@kyessenov please add any missing information.

**Comment by dio** [comment]
@lizan any comments?

**Comment by lizan** [comment]
@nrjpoddar [upstramTransportFailureReason](https://github.com/envoyproxy/envoy/blob/master/include/envoy/stream_info/stream_info.h#L496) is the one, this is added specifically to helping debugging SSL/TLS related errors.

**Comment by kyessenov** [comment]
upstreamTransportFailureReason works for the downstream clients.
How do we monitor listener socket failures? The filters don't kick in without a connection.

**Comment by lizan** [comment]
@kyessenov what information do you want from a listener socket failures? For listener socket failures I guess you need a listener_filter, and populate information from connection()->ssl() (and add failure info there).

**Comment by kyessenov** [comment]
Are listener filters suitable for telemetry collection? That may work. The goal is to be able to correlate a bad config push (TLS certs, improper TLS set-up) with an increase in SSL error telemetry.

**Comment by lizan** [comment]
It should be suitable, not very sure current implementation allows you do it. I understand the goal, for listener side, listener filter is the only filter can interact with TLS handshake / connection setup. 

OTOH, at client side Envoy you can collect more information for sure.

**Comment by nrjpoddar** [comment]
Client side is definitely doable and useful but doesn't account for the cases when only service is in the mesh for example.

@kyessenov how can telemetry be kicked from listener filter? Make RPC calls in that context to mixer, aren't there performance implications of doing that?

**Comment by kyessenov** [comment]
Listener filter is just a callback at the right time in packet processing. The reason why I asked about suitability, is that it was not used for sending RPCs before, so this would be the first one :)

**Comment by lizan** [comment]
You probably need to add a `onDestroy` or similar callback to it, (I think you can test with implementing destructor for experiment). Dispatcher is already exposed via callback so making RPC calls from there shouldn't be possible.

**Comment by nrjpoddar** [comment]
I guess if we only add RPC calls for error scenarios, performance penalty might be non-impacting as long we have the correct destructors in place. This probably warrants a new metric in Istio instead of bolting on to the existing ones.

Another interesting thing is what contextual information can we add to this metric?

**Comment by kyessenov** [comment]
The context should come from the config, e.g. listener filter config. This is a pretty complex solution though, since we need to apply all the standard optimizations as well (batching, compression).

**Comment by lizan** [comment]
Right you don't have much contextual information other than the listener filter config because the connection couldn't be set.
