### ISSUE TITLE
Add sampled traces metrics

### ISSUE THREAD

**Issue by pavolloffay** [envoyproxy/envoy#8434]
A feature request to add sampled traces counter metric.

The sampled counter for traces determines the number of sampled traces send to tracing backend. 

With the QPS metrics number, it helps the operator to appropriately set the sampling rate (in case of probability head sampling).

The metric should be exposed per rate configuration e.g. one metric per global rate or multiple if service/route rate is being used https://github.com/istio/istio/issues/12818#issuecomment-535946023.

**Comment by dio** [comment]
@objectiser could you elaborate what changes do we need to add to answer this feature request? Thanks!

**Comment by pavolloffay** [comment]
I have realized that envoy might not be able to tell how many traces were actually sampled - unless it has access to the sampling decision. Some information might be exposed as metrics directly from traces, however I see the value of exposing this metric regardless of tracing vendor.

**Comment by objectiser** [comment]
@dio As @pavolloffay mentions, this knowledge is tracing client specific - however it may be possible to expose this information for some of the providers. So we could just report these metrics where the information is available?
