### ISSUE TITLE
Mongo stats have an extra "." after prefix

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#8442]
*Title*: *Mongo stats have an extra "."*

*Description*:
>Mongo stats contain an extra "." in the tree since early September. 

Before: `mongo.mycluster.collection.mycollection.callsite.mycallsite...`
After: `mongo.mycluster..collection.mycollection.callsite.mycallsite...`

![image](https://user-images.githubusercontent.com/7603539/65918852-9750e380-e38f-11e9-938f-a9a7efccaeac.png)

**Comment by mattklein123** [comment]
cc @jmarantz ^

**Comment by kb000** [comment]
I've got a fix in testing.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/8445
