### ISSUE TITLE
HTTP protocol error results in DC access log

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#8446]
The DC stream flag is set in the absence of any other stream flags/response codes: https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L504

When a codec exception happens, we immediately reset the stream, setting neither a stream flag or a response code: https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L263

As a result, protocol errors appear with the DC flag set in the access logs.

We've seen Envoy respond with a 400 for some protocol errors at least (in which case the response code should probably be set), but I'm guessing not all protocol errors result in a 400 so we should at least set a stream flag for protocol errors (PE?)

**Comment by mattklein123** [comment]
This makes sense to me. This is also tangentially related to https://github.com/envoyproxy/envoy/issues/7917 in which the connection level log would clearly show a protocol error.

**Comment by spenceral** [comment]
I'm going to do this.
