### ISSUE TITLE
Configuring Overload manager

### ISSUE THREAD

**Issue by LisaLudique** [envoyproxy/envoy#8447]
*Title*: *Unclear on how to properly configure overload manager*

*Description*:
I have been looking into how to add overload manager to our bootstrap config. I'm using the docs at https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#statistics as a reference. Currently I'm just interested in adding the built-in resource monitor so that related stats are emitted (no actions/thresholds yet), so I've added 
```
overload_manager:
  refresh_interval:
    seconds: 0
    nanos: 250000000
  resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      config:
        max_heap_size_bytes: 2147483648
```
to the config from the example in the docs. 

However, this leads to an error during validation ```[2019-10-01 00:45:38.709][7212][critical][main] [external/envoy/source/server/config_validation/server.cc:60] error initializing configuration '<my config filename here>': Didn't find a registered implementation for name: 'envoy.resource_monitors.fixed_heap'
make: *** [validation_server] Error 1```. What additional steps do I need to take?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by mattklein123** [comment]
You need to add the extensions to your build config: 

https://github.com/envoyproxy/envoy/blob/2d2c9a5fe1614715a98ba9d93a057c3f37c33590/source/extensions/extensions_build_config.bzl#L95-L100

**Comment by LisaLudique** [comment]
Got it, thank you!
