### ISSUE TITLE
Update HeaderMatcher proto to be publicly visible

### ISSUE THREAD

**Issue by EItanya** [envoyproxy/envoy#8460]
*Title*: *Update HeaderMatcher proto to be publicly visible*

*Description*:
>Currently, the HeaderMatcher proto is contained in the `route.proto`file which is in the  `"//envoy/api/v2:friends"` visibility group of the API. However, this matcher, and the associated code is more widely useful than just from this group. My recommendation would be moving this particular advanced matcher, and maybe other related advanced matchers to the `envoy/type/matcher` api subgroup so they may be consumed by protos outside of the core API. Barring this drastic action, simply making the route.proto publicly visible would also solve this issue.

[optional *Relevant Links*:]
>https://github.com/envoyproxy/envoy/blob/c776fc3bd710d1c4a5e576144986cbff8f013bf4/api/envoy/api/v2/route/BUILD#L16
>https://github.com/envoyproxy/envoy/blob/c776fc3bd710d1c4a5e576144986cbff8f013bf4/api/envoy/api/v2/route/route.proto#L1289

**Comment by mattklein123** [comment]
Agreed, cc @htuch

**Comment by htuch** [comment]
I think in v3 this makes sense, ideally we move some of this to `udpa.type.v1`. We should get more of the @envoyproxy/udpa-wg involved as we do this.

**Comment by EItanya** [comment]
@mattklein123 I'm more than happy to take this on. I've never contributed to upstream envoy before, but I've been doing envoy development over at solo.io for a while.  Not sure how it works, does someone need to assign me, or should I assign myself?

**Comment by htuch** [comment]
@eltanya assigned, the WG aspect will make sense when you put the types in https://github.com/cncf/udpa

**Comment by htuch** [comment]
@EItanya friendly ping.

**Comment by EItanya** [comment]
Just started working on this and I have a few questions about the scope of this PR.

When I first opened this, I Was not only referring to the protos themselves, but also the host of utility functions which have been created for them. Most of them located [here](https://github.com/envoyproxy/envoy/tree/master/source/common/http).

I have already extracted them `HeaderMatcher` message and the `QueryParameterMatcher` message from the route proto, but I was wondering if this PR is meant to also update the code, or does that happen when stable v3 comes out?

Should have a PR up soon, just working out the proto dependencies.

**Comment by htuch** [comment]
The code and API changes can be largely handled independently. For the API changes, you'll need to not actually make any breaking changes in the v2 APIs, but instead add in parallel the new paths using the types you are refactoring, and deprecate the old paths with `deprecated` annotations.

The code can actually move today without any breaking change, so up to you how to sequence or handle this. I'd suggest getting a WiP out ASAP to ensure that we're aligned on the direction.
