### ISSUE TITLE
Filtering server live stats breaks health checking filter

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#8473]
When the `server.live` is filtered out, https://github.com/envoyproxy/envoy/blob/master/source/server/server.cc#L210 always returns true, resulting in the health check filter standing in a  503 LH response.

**Comment by snowp** [comment]
I imagine the solution here is to store this information as a bool on the server instead of relying on stats lookup

**Comment by mattklein123** [comment]
Yeah that would be the right solution.

**Comment by lizan** [comment]
This reminds me at #8259, do we know anywhere else that a feature is depending on stats which may be filtered? cc @jmarantz

**Comment by jmarantz** [comment]
There are some integration tests that depend on stats running. So if you wanted to do something like experimentally disable stats to see what else breaks, you wouldn't be able to because the integration tests would definitely break even if production worked :)
