### ISSUE TITLE
Clang-tidy report Server::Instance invoke virtual function in constructor

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#8509]
Create this issue to avoid involving too many things in a single PR.

Not end of the world since the inheritance is only used by test but no production. And tests are passing.

*Repro steps*:
https://github.com/envoyproxy/envoy/pull/8485

#4863

```
source/server/server.cc:406:3: note: Taking false branch
  if (bootstrap_.dynamic_resources().has_lds_config()) {
  ^
source/server/server.cc:418:46: note: Call to virtual function during construction
  Runtime::LoaderSingleton::get().initialize(clusterManager());
```

**Comment by lizan** [comment]
Yes this is legit clang-tidy error because virtual function invoked in constructor are bug-prone, (i.e. base class constructor cannot call virtual function overridden in derived class). Feel free to make clusterManager `final` in InstanceImpl.
