### ISSUE TITLE
Match a route based on the position of query param

### ISSUE THREAD

**Issue by shivanshu21** [envoyproxy/envoy#8518]
We want to match a route only when the first query param is not a specific value.

In the case below first query param should not be "param".

Eg.
www.example.com/deals?param=xyz&arg=123 **should not match**
www.example.com/deals?arg=123&param=xyz **should match**

**Comment by zuercher** [comment]
What's the purpose of routing based on the ordering of parameters? In my experience, HTTP clients often manage query parameters as unordered key-value maps, so it seems to me that depending on parameter ordering in routing isn't reliable.

Currently, the query parameters are available in the `:path` header and can be used for path matching. So a prefix match on `/deals?arg=123&` would actually work (at least for the first parameter).

(I do think we should extend query parameter matching to have inverted matches and, in general, parity with the header matchers.)

**Comment by mattklein123** [comment]
Also FWIW I think you could get this done with Lua.

**Comment by shivanshu21** [comment]
Thanks @zuercher and @mattklein123 . We will use the prefix match `/deals?arg=123&` for this issue.

Since we are discussing here, there is another unrelated feature:

*Can we have the capacity to pull some value out of a query param and put it in the Redirect Location?*

I can open a separate bug for this.

**Comment by zuercher** [comment]
Please open a separate issue.
