### ISSUE TITLE
Use unsynchronized shared_ptr in the hot paths

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/envoy#8521]
When libpthread is linked, `shared_ptr` will use a synchronized pointer. 
I just learned on S.O. that it is possible to explicitly instantiate the unsynchronized version of `shared_ptr`.

E.g.:

```c++
templatetypename T
 using shared_ptr_unsynchronized = std::__shared_ptrT, __gnu_cxx::_S_single;`
```

Probably the change to try this out would be low-risk/mechanical, hence it might be worth applying this to the hot path and test if there's a significant performance gain to be won.

**Comment by oschaaf** [comment]
(S.O. link: https://stackoverflow.com/questions/15129263/is-there-a-non-atomic-equivalent-of-stdshared-ptr-and-why-isnt-there-one-in/15141844#15141844)

**Comment by snowp** [comment]
Would this be portable between GCC and Clang? At a glance it seems very GCC specific

**Comment by mattklein123** [comment]
My understanding is that on almost all platforms we care about shared_ptr should use atomics. Or do you mean not use atomics at all? We definitely can't do the latter as we do use shared_ptr across threads in many places.

**Comment by lizan** [comment]
At a glance it seems libstdc++ specific. I don't think it would work on macOS or Windows.

**Comment by oschaaf** [comment]
> My understanding is that on almost all platforms we care about shared_ptr should use atomics. Or do you mean not use atomics at all? We definitely can't do the latter as we do use shared_ptr across threads in many places.

I was thinking that maybe there are cases where a `shared_ptr` is used, but switching to a non-synchronized version would be a (functional) no-op? 

Also pasting `pprof` peek focussing on `shared_ptr`:
https://gist.github.com/oschaaf/94529253b4f7a4dd9959beecdacb8105
