### ISSUE TITLE
Fix untitled protos in API docs

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8525]
As per screenshot, there's a bunch of protos that are in the build that don't have human readable title or helpful proto level comments (in some cases). We should do a manual pass over the API docs and fix these.

**Comment by dichen16** [comment]
Hi @htuch, 
I really want to get involved, but I feel confused about your description. can u give some example of "untitled protos"?

**Comment by htuch** [comment]
I forgot to attach the screenshot :) Here it is.. the untitled protos are things like "envoy/api/v2/srds.proto", which you can see in this screenshot.
![Screenshot 2019-10-18 at 4 57 53 PM](https://user-images.githubusercontent.com/10914751/67128007-8940f680-f1c8-11e9-9440-52ba2c17c3cb.png)

**Comment by dichen16** [comment]
Hi @htuch 
I'd like to take it, could u assign it to me?

**Comment by dichen16** [comment]
Hi @htuch,
I am confused about the label `"v3 API"`,
I saw the [document](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api), there's only v2 API related stuff.

So my question is this task is for v2 API related proto, right?

**Comment by htuch** [comment]
@dichen16 correct, we've moved most v2 issues to v3 in preparation for the upcoming v3 support.

**Comment by dichen16** [comment]
Hi @htuch,
I found all the `protodoc-title` are well defined, 
for example, 
the `protodoc-title` of `api/envoy/api/v2/srds.proto` is  **HTTP scoped routing configuration**, 
and the `protodoc-title` of `api/envoy/api/v2/cluster/filter.proto` is **Upstream filters**,

kind confused, Is those `protodoc-title` fields that this task need to upgrade?

**Comment by dichen16** [comment]
you mean "envoy/api/v2/srds.proto", is this already well defined?
![Screenshot from 2019-10-24 23-49-51](https://user-images.githubusercontent.com/36980985/67536673-e1b54e00-f70a-11e9-946d-6d8429cf8471.png)

I think it's kind different with your example, "envoy/api/v2/srds.proto".

**Comment by derekargueta** [comment]
That specific example might've been fixed by https://github.com/envoyproxy/envoy/pull/8678 but there are other instances that need fixing, such as
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/filter.proto
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/admin/v2alpha/tap.proto
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/service/discovery/v2/ads.proto

to name a few. Almost anywhere on https://www.envoyproxy.io/docs/envoy/latest/api-v2/api where you see `.proto`, likely implies a missing protodoc title.

**Comment by mattklein123** [comment]
For whoever works on this, let's please actually enforce this in the proto transform / format tool and then make the format check fail?
