### ISSUE TITLE
ext_authz: fallback to a direct response on error

### ISSUE THREAD

**Issue by kindermoumoute** [envoyproxy/envoy#8533]
When the external authorization HTTP filter is down I want to be able to return a direct response with custom headers / grpc status, and body.

**Comment by mattklein123** [comment]
I think this is probably covered by https://github.com/envoyproxy/envoy/pull/8126?

**Comment by kindermoumoute** [comment]
Yes, the gRPC part is missing in the conversation but this is the same topic. 👍
