### ISSUE TITLE
WebSocket over HTTP/2 does not work

### ISSUE THREAD

**Issue by tatsuhiro-t** [envoyproxy/envoy#8547]
*Title*: WebSocket over HTTP/2 does not work

*Description*:

I setup envoy with allow_connect=true in http2_protocol_options and websocket server behind it.  websocket server only handles RFC 6455 handshake.

Sending the request with CONNECT method and :protocol=websocket results in 400 HTTP status code.  The backend websocket server complains that sec-websocket-key header field is missing.  Network capture shows that it is true:

```
GET /echo HTTP/1.1
host: <snip>
sec-websocket-version: 13
origin: https://<snip>
accept: */*
accept-encoding: gzip, deflate
user-agent: <snip>
content-length: 0
upgrade: websocket
connection: upgrade
x-forwarded-proto: https
x-request-id: e0ff4c92-ccc8-4007-83eb-ee0e391db73e
x-envoy-expected-rq-timeout-ms: 15000
```

So it looks like envoy understands RFC8441 and translates the inbound request into RFC6455 style handshake, but it fails to add sec-websocket-key header field.

Sending sec-websocket-key header field from downstream client makes the handshake succeeds, but I don't think it is the intended usecase because RFC 8441 explicitly says that sec-websocket-key and sec-websocket-accept are superseded by the :protocol pseudo-header field.

Tested with envoy 1.11.2

*Repro steps*:

Setup backend websocket server which only handles RFC 6455 style handshake.
Setup envoy to understand frontend HTTP/2 protocol and forward the traffic to upstream websocket server.

Send CONNECT request with :protocol=websocket to envoy.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by alyssawilk** [comment]
Sorry, without time to dig into the specs, can you be a bit more clear about what you think Envoy should be doing?  Creating and validating Sec-WebSocket-Key when not present?
AFIK the current websocket code is to handle tunneling H1 websocket over H2, where I thought the client would originate sec-websocket-key.  If you want to make H2 support more comprehensive and standards compliant, that'd be great!

**Comment by tatsuhiro-t** [comment]
If I understand RFC 8441 correctly, HTTP/2 client which implements RFC 8441 never send sec-websocket-key.
For a proxy which translates HTTP/2 into HTTP/1.1 (like envoy), it has to do RFC 6455 WebSocket handshake with the backend WebSocket server, that is create and validate sec-websocket-key.

**Comment by tatsuhiro-t** [comment]
I think it would be nice to verify that Chrome (which implements RFC 8441 as far as I know) works with envoy.  Please note that Chrome will fallback to RFC 6455 handshake if RFC 8441 does not work.

As far as I understand it, I think websocket over h2 in envoy only works under the following situations:

1. Client performs RFC 6455 handshake, and envoy (incorrectly?) forwards sec-websocket-key generated by client to upstreams:

```
[Client] -- HTTP/1.1 -- [Front Envoy] -- HTTP/2 -- [Sidecar Envoy -- H1 -- App]
```

2. The upstream websocket server understands RFC 8441 (I haven't verify this yet).

```
[Client] -- HTTP/2 or HTTP/1.1 -- [Front Envoy] -- HTTP/2 -- [Sidecar Envoy -- H2 -- App]
```

It suddenly breaks if client does HTTP/2 and App only speaks H1 because no one in the path generates sec-websocket-key:

```
[Client] -- HTTP/2  -- [Front Envoy] -- HTTP/2 -- [Sidecar Envoy -- H1 -- App]
```

So if you think this is not a bug (and is a future enhancement), it would be nice to document the specific deployment requirement in order to make WebSocket over h2 work with envoy.

**Comment by alyssawilk** [comment]
Handling H1 websocket tunneled over H2 hops is as you note and the docs note, the websocket functionality currently supported by Envoy.   I guess I don't consider it a bug to not support native H2 websocket as long as we don't claim to, it's just a feature which Envoy doesn't support yet, like server push.  Handling HTTP/2 websocket does seem like a worthwhile addition and if you have any interest in adding support that'd be great.  If you think we should do a docs update to make it more clear what Envoy does and does not support that'd be fantastic as well.
