### ISSUE TITLE
Linker error building on system lacking a c++11 toolchain

### ISSUE THREAD

**Issue by wbertelsen** [envoyproxy/envoy#8558]
*Title*: 
Linker error building on system lacking a c++11 toolchain

*Description*:
I'm able to build envoy 1.11.2 on a centos-like (amazon linux 2018.03) system that doesn't support the `c++11` toolchain by using `ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1`. However, I'm unable to build current HEAD. I get an error during linking related to `std::allocator<std::string>::allocator()`
```
ERROR: /builds/cloud/envoy-rpm/BUILD/envoy-3582d02f6600057e676629c2afefe5265e669b10/source/exe/BUILD:26:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/source/exe/envoy-static-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/source/extensions/filters/network/common/redis/_virtual_includes/supported_commands_lib/extensions/filters/network/common/redis/supported_commands.h:22: error: undefined reference to 'std::allocator<std::string>::allocator()'
bazel-out/k8-opt/bin/source/extensions/filters/network/common/redis/_virtual_includes/supported_commands_lib/extensions/filters/network/common/redis/supported_commands.h:48: error: undefined reference to 'std::allocator<std::string>::allocator()'
bazel-out/k8-opt/bin/source/extensions/filters/network/common/redis/_virtual_includes/supported_commands_lib/extensions/filters/network/common/redis/supported_commands.h:41: error: undefined reference to 'std::allocator<std::string>::allocator()'
bazel-out/k8-opt/bin/external/com_github_grpc_grpc/_objs/gpr_base/string.o:string.cc:function gpr_leftpad(char const*, char, unsigned long): warning: memset used with constant zero length parameter; this could be due to transposed parameters
collect2: error: ld returned 1 exit status
Target //source/exe:envoy-static failed to build
```
I suspect this is related to this redis change (https://github.com/envoyproxy/envoy/pull/7496) where the extension starts to use `absl::flat_hash_map`. My guess is somehow this change is not compatible with the old-style `std::string`

*Repro steps*:
I have a repro using docker

1) Build a container using this `Dockerfile`
```
FROM amazonlinux:2018.03

ARG BAZEL_VERSION=0.29.1

#  prereqs
RUN yum -y install wget unzip which git patch gcc72 gcc72-c++ autoconf automake libtool rpm-build aws-cli

# cmake > 3.1
RUN yum remove cmake
RUN wget --quiet  https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.sh
RUN chmod +x cmake-3.15.4-Linux-x86_64.sh
RUN ./cmake-3.15.4-Linux-x86_64.sh --skip-license

# bazel
RUN wget --quiet https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linu\
x-x86_64.sh
RUN chmod +x bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
RUN ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh

# ninja
RUN wget --quiet https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
RUN unzip ninja-linux.zip
RUN mv ./ninja /usr/local/bin
RUN chmod +x /usr/local/bin/ninja
```

`docker build -t envoy_linker_repro .`
2) Run bash inside the container
`docker run -it --entrypoint /bin/bash envoy_linker_repro:latest`
3) clone envoy
`git clone https://github.com/envoyproxy/envoy.git && cd envoy`
4) checkout HEAD 
`git checkout 983b3d627dc46222359fa3b36734ed3b9e59606f`
5) build using `ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1`
```
bazel build --verbose_failures --sandbox_debug --copt="-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1" -c opt //source/exe:envoy-static
```
This build will fail.

6) checkout the commit before https://github.com/envoyproxy/envoy/pull/7496 landed
`git checkout e64361bcc3ed77f0721dee83915810b7f6c3ec0d`

7) build using `ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1`
```
bazel build --verbose_failures --sandbox_debug --copt="-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1" -c opt //source/exe:envoy-static
```
This build will succeed.

**Comment by zuercher** [comment]
@lizan do you have any input?

**Comment by lizan** [comment]
TBH I don't have exact answer for this, there are a couple of workaround:
1. use LLVM libc++, then you don't even need `ENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR`, this is the approach we use in getenvoy.io CentOS package.
2. disable redis plugin if you don't use it and it is the only cause (delete the line in source/extensions/extensions_build_config.bzl)

**Comment by wbertelsen** [comment]
Yeah, I resolved this for my usecase by building llvm/libc++ for my platform and then building envoy with it.

I do think at the very least there should be a documentation update to indicate that either a) certain plugins might not be compatible with old toolchains or b) that old toolchains are no longer supported.

**Comment by lizan** [comment]
@wbertelsen https://www.envoyproxy.io/docs/envoy/latest/install/building documented that C++14 is a requirement. Feel free to raise PR if you think this can be clearer.
