### ISSUE TITLE
Migrate to LLVM 9

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#8559]
*Title*: Migrate to LLVM 9

*Description*:
LLVM 9 has been released, we should consider updating the CI infrastructure from 8 to 9. This affects
- clang
- clang++
- clang-tidy
- clang-format

[optional *Relevant Links*:]
- [LLVM 9 release notes](http://releases.llvm.org/9.0.0/docs/ReleaseNotes.html)
- [LLVM 9 downloads page](http://releases.llvm.org/download.html)
- [C++ standard implementation status in clang](https://clang.llvm.org/cxx_status.html)

**Comment by derekargueta** [comment]
@lizan I assume this falls into your domain. Any thoughts? I'd be interested in trying it out in the next few weeks.

**Comment by lizan** [comment]
https://github.com/envoyproxy/envoy-build-tools/pull/6 I'm already using LLVM-9 locally

**Comment by derekargueta** [comment]
@lizan oh nice, didn't know the build tooling got pulled into a separate repo. I assume this ticket is closable then.
