### ISSUE TITLE
Remove v1 API code

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#8561]
*Title*: Remove v1 API code

*Description*:
Top-level ticket for when we're ready to remove v1 completely (v1.12 release). Issue #6362 is a prerequisite, but doesn't cover the actual API removal. That will be done with [this branch](https://github.com/envoyproxy/envoy/compare/master...derekargueta:dereka/the-great-exodus) with small changes picked off and merged early to try to make it a straightforward diff... as straightforward as removing a couple thousand lines can be 🤷‍♂️

**Comment by derekargueta** [comment]
@mattklein123 please assign to me

**Comment by mattklein123** [comment]
@derekargueta do you want to use https://github.com/envoyproxy/envoy/issues/2832 to track this removal? Up to you.

**Comment by derekargueta** [comment]
@mattklein123 SGTM. Just to be clear, removal of the v1 API is covered by the first item on that last, the google group link, right? (btw the second item can be marked done, dunno if there's a way to transfer edit permissions on an issue)

**Comment by mattklein123** [comment]
@derekargueta yup that's right.
