### ISSUE TITLE
Build is broken with Bazel 1.0

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [envoyproxy/envoy#8568]
*Title*: *Build is broken with Bazel 1.0*

*Description*:
With recently released Bazel 1.0 we got error like this:
`ERROR: /build/tmp/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/googleapis/BUILD.bazel:164:1: in srcs attribute of _generate_cc rule @googleapis//:_tracing_proto_grpc_codegen: '@googleapis//:tracing_proto_proto' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /build/tmp/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/googleapis/BUILD.bazel:164:1
ERROR: Analysis of target '@envoy//source/exe:envoy' failed; build aborted: Analysis of target '@googleapis//:_tracing_proto_grpc_codegen' failed; build aborted`

As workaround .bazelversion file can be added, that rollbacks bazel version to 0.29.1

**Comment by lizan** [comment]
hmm, I tried rc3 and that was fine during that time, let me check again

**Comment by moderation** [comment]
Didn't dig into it much but 1.0.0 worked for me on my standard Linux build. It failed big time on MacOS.

**Comment by asraa** [comment]
This is the same problem that's happening on the PGV builds:
```ERROR: /go/src/github.com/envoyproxy/protoc-gen-validate/tests/harness/cases/other_package/BUILD:82:1: in deps attribute of python_proto_gen_validate rule //tests/harness/cases/other_package:python_validate: '//tests/harness/cases/other_package:embed_proto' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'pgv_python_proto_library', the error might have been caused by the macro implementation in /go/src/github.com/envoyproxy/protoc-gen-validate/bazel/pgv_proto_library.bzl:91:16```

https://circleci.com/gh/envoyproxy/protoc-gen-validate/877?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by moderation** [comment]
See https://github.com/envoyproxy/envoy/pull/8739

**Comment by mattklein123** [comment]
Fixed
