### ISSUE TITLE
jwt_authn inline_string with symmetric key cant satisfy validation

### ISSUE THREAD

**Issue by daviderenger** [envoyproxy/envoy#8584]
Hi,

I'm trying to configure jwt auth with an inline string and gets the following errors:

With this config: 
`local_jwks:
                    inline_string: '
                    {
                      "keys":[
                        {
                          "kty":"oct",
                          "kid":"xxx",
                          "alg":"HS256",
                          "k":"xxx",
                        }
                      ]
                    }'`

The error is: **Issuer 'xx' in jwt_authn config has invalid local jwks: [kty] is not supported in [keys]**

Without kty
`local_jwks:
                    inline_string: '
                    {
                      "keys":[
                        {
                          "kid":"xxx",
                          "alg":"HS256",
                          "k":"xxx",
                        }
                      ]
                    }'`

Gives this error:  **Issuer 'xxx' in jwt_authn config has invalid local jwks: [kty] is missing in [keys]**

So I have no idea how to make the validator happy!

Using version 1.11.2 of envoy in docker.

**Comment by daviderenger** [comment]
Realize that HS256 is not supported until 1.12.0, must be better at looking at the version tag in documentation when googling for envoy docs...

I do think that the error message was a little bit confusing still!

**Comment by bernardoVale** [comment]
@daviderenger can you share how you did it? I'm able to configure the authN but it always returns 401 on 1.12.0

**Comment by daviderenger** [comment]
@bernardoVale Still no success with this. Now it doesn't complain about the configuration, but always getting 401 too :/ 

Will try a bit more and see if I can get it to work. A little more logs would be useful, all I see is "Jwt verification fails" with tokens and keys that work in our application.

**Comment by qiwzhang** [comment]
could you post your JWT and JWKS here,  I can take a look? 

Or if you are c++ developer with BAZEL installed.   you can try to clone this [repo](https://github.com/google/jwt_verify_lib/tree/master/src)

change any of verify_xxx_test.cc with your JWT and JWKS and run "bazel test //..." with it

**Comment by qiwzhang** [comment]
Have you used [jwt.io](https://jwt.io/) to verify it?

**Comment by daviderenger** [comment]
@bernardoVale @qiwzhang I actually got it to work now :tada:

The one thing that I missed was to base64 encode the secret string. So this is my configuration now that works:

`const secret =  'a very secret string'; //used to create the token with jsonwebtoken`

- name: envoy.filters.http.jwt_authn
            config:
              providers:
                rpc_jwt_provider:
                  issuer: someIssuer
                  local_jwks:
                    inline_string: '{"keys":[{"typ": "JWT", "kty":"oct","alg":"HS256","kid":"df","k":"YSB2ZXJ5IHNlY3JldCBzdHJpbmc="}]}'
                  from_headers:
                  - name: accessTokenTest
                  forward: false
                  forward_payload_header: x-jwt-payload
              rules:
              - match:
                  prefix: /event-gateway
                requires:
                  provider_name: rpc_jwt_provider


'YSB2ZXJ5IHNlY3JldCBzdHJpbmc=' is just 'a very secret string' base64 encoded.

**Comment by daviderenger** [comment]
Ok, not really done yet. It still doesn't work with the real keys we use, only works with this kind of simple strings. I guess our keys are not ok for some reason so they are transformed somehow when generating the JWT
