### ISSUE TITLE
Supporting host rewrites with the dynamic forward proxy

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#8607]
We have a use case for the dynamic forward proxy in which we want to rewrite the host and use the rewritten host as the upstream endpoint. The following won't work:

1) set a `host_rewrite` on the `RouteAction` -- it's apparently too late, so it doesn't take effect
2) removing/adding the `:authority` or `host` headers -- that's not allowed

Does this sound like a reasonable use case? If so, I'll see what it takes to make option 1) work. Thoughts?

cc: @mattklein123  @fishcakez

**Comment by mattklein123** [comment]
If you want to do this with no code changes I think you could just install a small Lua filter to change the host/authority in front of the dynamic proxy filter and it would probably work. 

The alternative I think would probably be supporting the `host_rewrite` route option directly inside of the dynamic proxy filter? This is a little strange in the sense that the router would try to rewrite it again to the already rewritten value, but I think it would work.

**Comment by rgs1** [comment]
Yeah thought about the filter way in front of the dynamic proxy (C++ tho, not Lua), but if possible I'd rather have `host_rewrite` just work.  I'll take a look, thanks!

**Comment by Asisranjan** [comment]
Hi @rgs1 
can you please share sample filter
