### ISSUE TITLE
Propagate exception from async client to creator of the request

### ISSUE THREAD

**Issue by yxue** [envoyproxy/envoy#8612]
https://github.com/envoyproxy/envoy/blob/4825facf2451b234af737b5af8c792c31bca5d41/include/envoy/http/async_client.h#L223-L234

allows client to send HTTP request asynchronously and the `callback` will be called once there is a response.  

IIUC, when the `callback` throws an exception, the exception will not be caught. I am wondering if there is anyway we can propagate the exception to the creator of the `request`. 

Usage:

https://github.com/envoyproxy/envoy-wasm/pull/216
When initializing wasm filter with async data source, we'd like to throw and propagate the exception to the creator and config manager rather than swallowing the exception inside the code. 

cc @jplevyak @PiotrSikora

**Comment by jmarantz** [comment]
I labelled the issue but I have a question. Is it well-defined in Envoy to have async client callbacks throw exceptions? Who would catch?

**Comment by mattklein123** [comment]
We should not be throwing exceptions out of the callbacks. Can you explain more why you would want to do this?

**Comment by mattklein123** [comment]
> How exactly that should happen is at issue. What would you suggest?

I think we are in new territory here. I don't think I have any advice/thoughts without knowing more detail. Can you potentially flesh out the init flow that you are using and we can discuss more?
