### ISSUE TITLE
Certificates provided inline to Envoy linger even when replaced

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#8614]
Our current setup runs a control plane which has all of our certificates, and these are provided to our fleet of proxies via SDS

We just noticed an odd behavior where a `tls_certificate` secret was updated just yesterday, but the old certificate is still shown in the admin `/certs` endpoint... and this also seems to affect the metric `server.days_until_first_cert_expiring`

The equivalent commands I ran on the envoy node were as follows
```
# http GET http://localhost:9901/certs | jq '.certificates[].cert_chain[] | {days: .days_until_expiration, name: .subject_alt_names[0].dns}' | grep '<redacted common name>' --context 2
{
  "days": "28",
  "name": "<redacted common name>"
}
{
--
{
  "days": "794",
  "name": "<redacted common name>"
}
```

The two redacted names are identical.

Is this known/intended? I'm guessing there is no way to purge these old certificates and that I should just re-deploy the fleet.

**Comment by mattklein123** [comment]
This seems like a bug or some type of confusion. @lizan @lambdai @kyessenov any thoughts? Wondering if this is the same hashing issue that was fixed?

**Comment by kyessenov** [comment]
Yeah, this could be because of hashing. @lizan does SDS force a reload of the cert when SDS payload is identical but version is bumped?

**Comment by lizan** [comment]
@kyessenov No it doesn't: https://github.com/envoyproxy/envoy/issues/7676. but I don't think that is the issue mentioned here specifically.

@cetanu I guess you still have connections alive on the old certificate so it is not being purged, which is expected behavior. Is that the case?

**Comment by cetanu** [comment]
> @cetanu I guess you still have connections alive on the old certificate so it is not being purged, which is expected behavior. Is that the case?

I had not even considered this but that makes sense; unfortunately the machines have already been redeployed.

If this is the expected behavior then I think we can probably close this, but it might be something worth noting in this page under the linked header: https://www.envoyproxy.io/docs/envoy/v1.11.2/configuration/secret#examples-two-sds-server

**Comment by lizan** [comment]
I think we can make this better to mark the one no longer used for new connection as `draining_secrets` or just hide from `/certs`

**Comment by lambdai** [comment]
My understanding is that filter chain manager maintains a ref count to the server ssl context, through ServerSslSocketFactory , no matter if there is connection/transportsocket is alive or not

**Comment by euroelessar** [comment]
We do observe as well that certs used by currently established connections are part of the `/certs` output.
What is actually worse is that it affects `days_until_first_cert_expiring` metric.
In setups with short-living TLS certificates and long-living connections it means that envoy is happy to report that all certs have been expired even if SDS-based cert reloading does work as expected.

**Comment by dsymonds** [comment]
I was bitten by this over the Christmas break. We have an Envoy setup with SDS and some monitoring that watches days_until_first_cert_expiring to alert us if it accidentally gets too low. Our certs actually did get automatically rotated, but the Envoy instances held onto the old certs too long, kept the days_until_first_cert_expiring metric dropping, and triggering our alert.

(Normally our CD system regularly restarts everything, including Envoy, so we didn't notice until the break when the CD was paused.)

**Comment by rmichela** [comment]
I'm seeing this bug too, now that I've started using SDS with Istio. I use short-lived, frequently rotated certificates and worry this will result in a memory leak in Envoy.

**Comment by ramaraochavali** [comment]
@lizan is there a way to identify whether the context is being used by an existing connection or not in the current code? If it is not, is it some thing that can be added?

We are also hit by this with SDS and our cert expiry alerts are firing for lingering certs.

**Comment by ramaraochavali** [comment]
Looked at the code and it looks like we can pass the old context if available when secret is updated here https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/ssl_socket.cc#L356 to `createSslClientContext` and can remove from the list of contexts similar to how we remove expired contexts https://github.com/envoyproxy/envoy/blob/cdd3a837056dc6935c0d8e0fb693d4de89b998e9/source/extensions/transport_sockets/tls/context_manager_impl.cc#L23. The same thing can be done for server contexts.

Does it work? Or Am I not reading the code correctly? Or any better ideas?

**Comment by lizan** [comment]
@ramaraochavali that's right, we use shared_ptr to track whether the SslContext is used, which is count number of active connections in.
