### ISSUE TITLE
Zone aware rounting not enabled

### ISSUE THREAD

**Issue by mshaverdo** [envoyproxy/envoy#8616]
*Title*: *Zone-aware routing not working*

*Description*:
I'm trying to set up service mesh with zone aware routing for 2 kubernetes clusters (named `cluster-1` and `cluster-2`), but it isn't working: requests from `cluster-1` balanced  both to `cluster-1` and `cluster-2`.
Envoy running as a sidecar near the pod curl` in k8s cluster `cluster-1` and proxying outbound requests to upstream pods. Each kubernetes clusters running 2 upstream pods.
Envoy configured local cluster and target clusters as EDS and min_cluster_size=2 each.

How i could diagnose why zone aware routing still disabled on my system?

**envoy args**
`/usr/local/bin/envoy -c /config/envoy.yaml --service-node test-1 --service-zone cluster-1 --service-cluster cluster-1 -l debug --concurrency 3`

**config**
https://gist.github.com/mshaverdo/abdf7248704d8a4a12a0d495be24050d

**/clusters**
https://gist.github.com/mshaverdo/f0944d78e2ff8a5cba9a7f4c184c9f01

**control plane CDS**
https://gist.github.com/mshaverdo/f391d20b7633cc03fe72c8787a0b0070

**control plane EDS**
https://gist.github.com/mshaverdo/feb922ea4205abd536ac0f13864a723f

**Logs**:
https://gist.github.com/mshaverdo/4d40dfa7eaed1adf0b674dce7a30826e

**Comment by derekargueta** [comment]
What do your load balancer stats look like?
https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#load-balancer-statistics
