### ISSUE TITLE
Conditional http filter

### ISSUE THREAD

**Issue by seguidor777** [envoyproxy/envoy#8634]
Is it possible to handle conditional filters?

I have one microservice that is serving grpc-web requests, but I want it to serve pure gRPC requests as well, through the same virtual host.

Thanks in advance

**Comment by zuercher** [comment]
Envoy's grpc web filter ignores non-gRPC-web requests (based on content-type). Any request that doesn't have the appropriate content type (`application/grpc-web`, `application/grpc-web+proto`, `application/grpc-web-text`, or `application/grpc-web-text+proto`) is ignored by that filter. That includes normal gRPC requests (content-type `application/grpc`).

**Comment by seguidor777** [comment]
Hi Stephan, thanks for your reply

It sounds good, it will work for me
What about the cors filter, is it also ignored when the proper headers are
not set?

**Comment by zuercher** [comment]
Definitely, if there's no Origin header or if the request method is not OPTIONS, the CORS filter will ignore the request. There are other mechanisms as well. I'd recommend looking at the code if you need a more detailed answer.

**Comment by seguidor777** [comment]
Excellent
