### ISSUE TITLE
Run fix_format in ci and produce diff

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8636]
We're adding more stuff in the format CI and it become heavier and with more dependencies to run. We can produce a diff in azp in case of check_format fails, so the diff gives what CI expect for the fixable format without environment dependent bit.

@htuch @jmarantz

**Comment by htuch** [comment]
Yes, I think this is a good idea, but will require some work to get `check_format.py` into a position to provide a patchable diff; right now its output formatting isn't quite right for this. I think this would be an awesome task for anyone who wants to take on Python dev infrastructure work, will mark it as help wanted.

**Comment by jmarantz** [comment]
I think the easiest way to approach this is run the format fixer, and then use git to make the diff.

Some of the check_format tests are not able to automatically fix any problems, in which case the format fixer should return an error.

**Comment by htuch** [comment]
+1; in CI we can run the format fixer without worrying about local state as well. Let's take that approach.

**Comment by lizan** [comment]
> I think the easiest way to approach this is run the format fixer, and then use git to make the diff.

Yeah that is what was in my mind. Simply run fix_format and git diff.
