### ISSUE TITLE
SubsetCompatibleLoadBalancers/HttpSubsetLbIntegrationTest.SubsetLoadBalancer/LEASTREQUEST flaked

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#8643]
[ RUN      ] SubsetCompatibleLoadBalancers/HttpSubsetLbIntegrationTest.SubsetLoadBalancer/LEASTREQUEST
test/integration/http_subset_lb_integration_test.cc:169: Failure
Expected: (hosts.size()) > (1), actual: 1 vs 1
Expected multiple hosts to be selected for LEAST_REQUEST
Stack trace:
  0x7102e4: Envoy::HttpSubsetLbIntegrationTest::runTest()
  0x70fb27: Envoy::HttpSubsetLbIntegrationTest_SubsetLoadBalancer_Test::TestBody()
  0x11b7ae4: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x11b7a0c: testing::Test::Run()
  0x11b8a5f: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] SubsetCompatibleLoadBalancers/HttpSubsetLbIntegrationTest.SubsetLoadBalancer/LEASTREQUEST, where GetParam() = 1 (237 ms)

I'm not seeing any sketchy changes of late. 
https://github.com/envoyproxy/envoy/commits/master/source/common/upstream/subset_lb.cc

@zuercher I think you've done the most work on this test - any chance you could take a look at some point?

**Comment by fredlas** [comment]
I saw it too; same failure, except that for me it was RANDOM rather than LEAST_REQUEST. Still the same Expected: (hosts.size()) > (1), actual: 1 vs 1 ).
