### ISSUE TITLE
clang-tidy readability-identifier-naming scheme

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#8656]
This ticket is to
1) track the progress of having clang-tidy enforce casing in the Envoy codebase to make pull requests easier to review
2) Ensure that we agree on the casing scheme before putting up PRs to conform everything.

https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html

(the component being checked/styled will be labeled as a variant of `example.*`)
<table>
<tr>
<td>done</td>
<td>check name</td>
<td>casing style</td>
<td>example</td>
</tr>
<tr>
<td>yes!</td>
<td> ClassCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
class ExampleOne {
...
};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ClassConstantCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
class FooBar {
public:
  static const int ExampleOne;
};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ConstantCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void function() {
  unsigned const example_one[] = {1, 2, 3};
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ConstantParameterCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void fooBar(int foo_bar, const int example_one);
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ConstantPointerParameterCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void fooBar(const int* example_one);
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ConstexprMethodCase</td>
<td> camelBack</td>
<td>
<pre lang="cpp">
class Foo {
public:
  constexpr int exampleOne() { return 2; }
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ConstexprVariableCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
void fooBar() {
  constexpr int ExampleOne = 1;
}
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td>EnumCase</td>
<td> CamelCase </td>
<td>
<pre lang="cpp">
enum class ExampleOne {
...
};
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td>EnumConstantCase</td>
<td> CamelCase </td>
<td>
<pre lang="cpp">
enum class FooBar {
  ExampleOne,
  ExampleTwo
};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> GlobalFunctionCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
void ExampleOne();
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> LocalConstantCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void foo() {
  const int example_one = 3;
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> LocalConstantPointerCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void foo() {
  const int* example_one = 3;
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> LocalPointerCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void foo() {
  int *example_one;
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> LocalVariableCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void foo() {
  int example_one;
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> MemberCase</td>
<td>lower_case (with trailing `_`)</td>
<td>
<pre lang="cpp">
class Foo {
  int example_one_;
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> MethodCase</td>
<td>camelBack</td>
<td>
<pre lang="cpp">
class FooBar {
public:
  void exampleOne();
protected:
  int exampleTwo();
private:
  bool exampleThree();
};
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td> NamespaceCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
namespace ExampleOne {
namespace ExampleTwo {
...
} // namespace ExampleOne
} // namespace ExampleTwo
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td> ParameterCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
void fooBar(int example_one, const int foo_bar);
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> StaticConstantCase</td>
<td> CamelCase</td>
<td>
<pre lang="cpp">
void fooBar() {
  static const int ExampleOne = 1;
  ...
}
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> StaticVariableCase</td>
<td> lower_case</td>
<td>
<pre lang="cpp">
static int example_one = 1;
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td> StructCase</td>
<td> CamelCase</td>
<td>
<pre lang="cpp">
struct ExampleOne {
...
};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> TemplateParameterCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
template &lt;typename ExampleOne&gt; class Foo {};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> TemplateTemplateParameterCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
template &lt;template &lt;typename&gt; class ExampleOne, int foo, typename... Bar&gt;
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> TypeTemplateParameterCase</td>
<td>CamelCase</td>
<td>
<pre lang="cpp">
template &lt;template &lt;typename&gt; class FooBar, int foo, typename... ExampleOne&gt;
</pre>
</td>
</tr>
<tr>
<td>yes!</td>
<td> UnionCase </td>
<td> CamelCase </td>
<td>
<pre lang="cpp">
union ExampleOne {
  ...
};
</pre>
</td>
</tr>
<tr>
<td>no</td>
<td> ValueTemplateParameterCase</td>
<td>lower_case</td>
<td>
<pre lang="cpp">
template &lt;template &lt;typename&gt; class Foo, int example_one, typename... Bar&gt;
</pre>
</td>
</tr>
</table>

cc @lizan

**Comment by derekargueta** [comment]
@lizan / @mattklein123 please assign to me

**Comment by lizan** [comment]
@derekargueta JFYI, you can assign yourself

**Comment by derekargueta** [comment]
@lizan oh sorry, thought it was a maintainer power
