### ISSUE TITLE
Didn't find a registered implementation for name: 'envoy.tcp_grpc_access_log'

### ISSUE THREAD

**Issue by wyxinlx** [envoyproxy/envoy#8660]
Description:
I'm trying to configure TcpGrpcAccessLogConfig, but got the error trying to run the docker container:
    

> [critical][main] [source/server/server.cc:93] error initializing configuration '/etc/envoy/envoy.prj-demo.yaml': Didn't find a registered implementation for name: 'envoy.tcp_grpc_access_log'

docker image version:

> envoyproxy/envoy:v1.11.2

something wrong?
Thx in advance.

the yaml file content

>       filters:
>       - name: envoy.http_connection_manager
>         typed_config:
>           "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
>           stat_prefix: ingress_http
>           http_protocol_options:
>             accept_http_10: true
>           access_log:
>           - name: envoy.file_access_log
>             config:
>               path: /home/q/system/envoy-prj-demo/access.log
>           - name: envoy.tcp_grpc_access_log
>             config:
>               common_config:
>                 log_name: ingress_http
>                 grpc_service:
>                   envoy_grpc:
>                     cluster_name: grpc_log_receiver
>                 buffer_flush_interval: 2s
>                 buffer_size_bytes: 16384
>

**Comment by moderation** [comment]
This feature was added after the release of 1.11.x so it isn't present in the version you have.

- 1.11.2 - https://www.envoyproxy.io/docs/envoy/v1.11.2/api-v2/config/accesslog/v2/als.proto
- 1.12.0-dev - https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/als.proto.html?highlight=tcp_grpc_access_log

So you need to build from master or get the -dev Docker image.

**Comment by wyxinlx** [comment]
thx! i will have a  try
