### ISSUE TITLE
Envoy cuts off nextcloud downloads.

### ISSUE THREAD

**Issue by Barborica-Alexandru** [envoyproxy/envoy#8662]
Description: I have envoy 1.12 set up as an edge proxy, behind it is an apache webserver hosting my nextcloud instance, when I try to download files envoy will cut off the download after what I estimate are 10 seconds. Direct connection through apache works fine.

Sanitized debug log:
[debug.txt](https://github.com/envoyproxy/envoy/files/3745121/debug.txt)

**Comment by mattklein123** [comment]
The default request timeout is 15s. Do you need to extend that and/or move to an idle timeout?

**Comment by Barborica-Alexandru** [comment]
I'm confused as to why envoy is considering it idle since the download is ongoing? I will look up in the documentation how to increase request timeout. I thought the documentation stated that if no stream_idle_timeout is specified then it defaults to off (no timeout).
