### ISSUE TITLE
Feature: stat for XDS config reloads

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#8680]
**Issue Template**

*Title*: Feature: stat for XDS config reloads

*Description*:
It would be useful to have a metric for the number of XDS configs that were deduplicated or had no effect since the same config had already been sent. This would be useful to measure how many wasted pushes the control plane is doing, as well as measuring how [often we are causing listener drains](https://github.com/istio/istio/issues/18088).

**Comment by lizan** [comment]
I guess you want to see per listener stat to see listener drain then?

**Comment by howardjohn** [comment]
Per listener could be useful as well, but I was initially thinking just extending the xds level ones like lds_update_success. 

Looking at the stats again though it looks like this may already exist as config_reload https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview#xds-subscription-statistics.

**Comment by mattklein123** [comment]
> Looking at the stats again though it looks like this may already exist as config_reload

Yes. If this doesn't do what you want let's figure out why?

**Comment by howardjohn** [comment]
100% on our side, we are not including the stat in our stats_matcher. I just tested with including it and looks good, sorry for the noise
