### ISSUE TITLE
how to customize cluster lb_policy in envoy?

### ISSUE THREAD

**Issue by hbgongen** [envoyproxy/envoy#8692]
we want to use our own lb_policy,i find the cluster_provided is to connect lb service out of envoy.How can I customize the lb_policy in envoy.

**Comment by hbgongen** [comment]
![auth](https://user-images.githubusercontent.com/36953705/67194118-15e9ef80-f429-11e9-9b13-8760a1bad92a.png)
for this photo,we want to auth some requests.and we want some requests route to Specified machine.
for example request's header has a property “index”,and auth clusters has 3 machines,
index%3=0 to machine1.
index%3=1 to machine2.
index%3=2 to machine3.
we want to use a property in header to do load balance.
how can i do it?Does it have some interface to make it?
please help me.

**Comment by snowp** [comment]
Have you looked into using the consistent hashing load balancing algorithms? https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash or https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#maglev

If you want to provide your own custom implementation that requires compiling in your own cluster /w a custom load balancing policy. See the original dst cluster for an example of this in the Envoy tree.

**Comment by hbgongen** [comment]
> Have you looked into using the consistent hashing load balancing algorithms? https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash or https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#maglev
> 
> If you want to provide your own custom implementation that requires compiling in your own cluster /w a custom load balancing policy. See the original dst cluster for an example of this in the Envoy tree.

oh,two algorithms i have seen,but we need to use the property of header.these two algorithms have their own parameters.
