### ISSUE TITLE
PGV validations on embedded fields

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#8715]
Hi everyone, I'm running into a protoc-gen-validation issue when using Envoy. It seems like the values of map aren't validated. 

 The RBAC filter configuration includes a map of policies:
```
  map<string, Policy> policies = 2;
```
where in a Policy is defined as:
https://github.com/envoyproxy/envoy/blob/986173ed516dcc1c3dea7db90659ed993d0aad75/api/envoy/config/rbac/v2/rbac.proto#L84-L99

So both embedded repeated fields Permissions and Principals should have at least one item by the PGV constraints.

However, it seems like if we have an empty repeated message field, we can still validate OK. For example, this test crashes and doesn't exit cleanly, despite the PGV validation:
```
TEST(RoleBasedAccessControlEngineImpl, InvalidConfig) {
  envoy::config::rbac::v2::RBAC rbac;
  rbac.set_action(envoy::config::rbac::v2::RBAC_Action::RBAC_Action_ALLOW);
  envoy::config::rbac::v2::Policy policy;
  policy.add_permissions();
  (*rbac.mutable_policies())["foo"] = policy;
  try {
     // Validated the input successfully, yet did not call an exception that min_items = 1 on the
     // Principals field or required rule in Permissions.
    TestUtility::validate(rbac);
     // Crash now, because create Permissions returns panic: not reached because of missing case.
     RBAC::RoleBasedAccessControlEngineImpl engine(rbac);
  } catch (const EnvoyException& e) {
    // Clean exit.
    ENVOY_LOG_MISC(debug, "EnvoyException: {}", e.what());
  }
}
```
(I've added this test in `engine_impl_test` along with including `envoy/config/rbac/v2/rbac.pb.validate.h`)

Is PGV not running validations on the map values' messages?

**Comment by mattklein123** [comment]
cc @rodaine @htuch @akonradi

**Comment by asraa** [comment]
Upon carefully reading the documentation, the answer is no, PGV doesn't support validation on keys or values in C++, which means no recursive validation:
https://github.com/envoyproxy/protoc-gen-validate/blob/master/rule_comparison.md#maps

This also applies to repeated embedded message fields -- they're not validated in C++. Just FYI, in case we are relying on validations for embedded messages in repeated fields or maps.

**Comment by rodaine** [comment]
Originally (predating RBAC), there were no repeated/map fields in the Envoy config messages that required validation, so the C++ implementation for those rules was kicked down the road. I can't couldn't say if I had forgotten this or if I was being optimistic when implementing RBAC.

There are no blockers to add this to PGV, but I do not currently have the bandwidth to work on it now, so if someone else would like to take a stab, it'd be much appreciated.

**Comment by htuch** [comment]
@asraa is this within scope of resolving our fuzz backlog? @rodaine it seems pretty reasonably scoped, just an additional recursive traversal in all languages.

**Comment by rodaine** [comment]
> @rodaine it seems pretty reasonably scoped, just an additional recursive traversal in all languages.

Not saying it’s technically hard. C++ is the only language right now in PGV that doesn’t support it. We skipped it on your initial pass since it wasn’t a requirement for the configs at the time.

**Comment by htuch** [comment]
@asraa sounds good, from what @rodaine says we should be able to figure this out, I can take a look at the WiP next week.

**Comment by zuercher** [comment]
I found some time to work on this. I should have a PR out this afternoon that makes PGV recursively handle validations on maps.

**Comment by zuercher** [comment]
https://github.com/envoyproxy/protoc-gen-validate/pull/281

**Comment by asraa** [comment]
Thank you so much!!!

**Comment by zuercher** [comment]
@rodaine or @akonradi do either of you have time to review https://github.com/envoyproxy/protoc-gen-validate/pull/281?
