### ISSUE TITLE
Have a fallback cluster which matches when the matched upstream cluster for a route is Unhealthy

### ISSUE THREAD

**Issue by shivanshu21** [envoyproxy/envoy#8730]
*Title*: *Have a fallback cluster which matches when your matched upstream cluster is Unhealthy*

*Description*:
We are running an implementation of this feature in our production env. We wanted to know if this feature is desired upstream.
The feature is present at `route_config` level, and takes name of a cluster as its value.
If a route matches an upstream cluster which has `no heathy upstreams`, then instead of sending a 503, we reroute the request to this default cluster (if it is set).

Envoy config looks like this:

```
            "filter_chains": [{
                "filters": [{
                    "name": "envoy.http_connection_manager",
                    "config": {
                        "stat_prefix": "ingress_http",
                        "route_config": {
                            "name": "envoy_route_config",
                            "default_cluster": "echo1", <<<<<<<<<<<<<<<<<<<
                            "virtual_hosts": [
                                {
                                    "name": "backend",
                                    "domains": [
                                        "www.ebay.com"
                                    ],
```

**Comment by lizan** [comment]
@snowp I guess this can be a retry extension?

**Comment by mattklein123** [comment]
I think this could also be done with an HTTP filter that runs before the router FWIW.

**Comment by shivanshu21** [comment]
@mattklein123 @lizan 

Sorry, I didnt quite understand.
```
Lets say there is a decoder filter which runs before router.
It must first "route" this request and match it to a cluster.
Then it should check if the matched cluster is up. If not, change its cluster to the default cluster.
```
In doing so, the new filter will just be another router filter won't it?

The way we do it in our private repo is:

```
// If the cluster is unhealthy then send request to the default cluster.
  if (!conn_pool) {
    Upstream::ThreadLocalCluster* def_cluster = config_.cm_.get(route_entry_->defaultClusterName());
    if (!def_cluster) {
      ENVOY_STREAM_LOG(debug, "unknown default cluster '{}'", *callbacks_, route_entry_->defaultClusterName());
    } else {
      cluster_->stats().upstream_rq_default_cluster_.inc();
      ENVOY_STREAM_LOG(debug, "cluster '{}' unhealthy. Sending to default cluster '{}'", *callbacks_, route_entry_->clusterName(), route_entry_->defaultClusterName());
      cluster_ = def_cluster->info();
      if (!cluster_->maintenanceMode()) {
        conn_pool = getDefaultConnPool();
      }
    }
  }

  if (!conn_pool) {  // <<<<<<<<<<<<<<<<<<<<<<< This is envoy's default behavior
    sendNoHealthyUpstreamResponse();
    return Http::FilterHeadersStatus::StopIteration;
  }
```

**Comment by snowp** [comment]
You can modify the headers and call `callbacks_->clearRouteCache();` to re-resolve the route entry. This would allow you to simplify modify the headers in such a way that a different cluster is resolved, delegating the routing to the router.

**Comment by mattklein123** [comment]
^ correct

**Comment by rshriram** [comment]
Why can’t you do this with aggregate cluster ?

**Comment by shivanshu21** [comment]
Thanks guys, we are exploring different options you have mentioned in responses. For now we have a local fix for this.
