### ISSUE TITLE
Have the ability to fall through to the next best match if the upstream cluster match for a route is unhealthy

### ISSUE THREAD

**Issue by shivanshu21** [envoyproxy/envoy#8731]
This is linked to issue #8730 

If a route matches an upstream cluster that is unhealthy, can we have an option in `route.RouteAction` to trigger rerouting to the next closest match?

Eg.
`/a/b` matches `down_cluster_1`
`/c` matcher `some_cluster_3`
`/a` matches `up_cluster_2`
`/` matches `home_page`

A `/a/b` request should be sent to up_cluster_2 if down_cluster_1 is unhealthy.

We want this option to be a part of `route.RouteAction`

Has someone already worked on something like this?
Is there some feature available today that we can use?
What would be the best way to implement?

**Comment by shivanshu21** [comment]
@lizan Here is something else that is related.
https://github.com/envoyproxy/envoy/issues/7017

The Noop feature described above will allow for a route to be a No-operation route. When such a route is matched to Noop, it will get rerouted to next closest match.

This question extends the concept a little. In this case, I want to reroute ONLY if the upstream cluster is unhealthy. Upon rerouting the request will match the next best routematch.

**Comment by lizan** [comment]
as I commented in the other issue, I guess this can be a retry extension, @snowp can weigh in on that.

**Comment by mattklein123** [comment]
I think this one would be a bit harder to do as a retry extension, but also could potentially be done as an HTTP filter that runs before the router (in general the router is super complex and I would like to try to prevent it from getting even more complex). One way this could potentially be done is a allow a route to be selected w/ optional hints, such as "not this cluster" or something like that. Needs more thinking.

**Comment by snowp** [comment]
I think there is an issue with how route resolution works in Envoy for this to work perfectly: route resolution happens immediately as the HCM runs, so if cluster health is accounted for in route resolution, a route that targets cluster A might be selected. Then, a slow filter is applied (think ext_authz), delaying the actual routing. Now there is no longer any guarantee that cluster A is healthy anymore, so routing to it might still fail. 

Essentially, the fact that route selection is done before the filters run makes this hard to do route fall-through based on host health.  Updating the route entry at routing time is also not great, as prior filters might have made use of the per filter config specified for the previous route. 

I suspect that the idea of having a "fallback cluster" can likely be better expressed with a cluster that handles the fallback without involving the router. Is there a specific reason why a route based fallback would be helpful? Or is this just a suggestion for how a fall-back cluster would be configured?

**Comment by shivanshu21** [comment]
@snowp We are just trying to solve the case where a cluster is down before the routing is done.

```
//I suspect that the idea of having a "fallback cluster" can likely be better expressed with a cluster that handles the fallback without involving the router. //
```
How can we use this idea to go to the next best matching route?

**Comment by pitiwari** [comment]
I am working on PR for noop. Once that pr is merged. For noop i am checking if route has noop action specified then pick next route. @shivanshu21 can put one more check over there to check for the unhealthy cluster. 

If this sounds good, then i can increase priority for working on PR. 

https://github.com/envoyproxy/envoy/pull/8611

**Comment by mattklein123** [comment]
I think we are still unlcear on how NOP is going to land, so let's see how that turns out first and then we can potentially revisit this. We need to be careful about adding too much complexity in the wrong places and will need to step back and figure out the right way for you to solve your use case.

**Comment by snowp** [comment]
@shivanshu21 What is the goal to provide fall through here? What benefit does
```
match /foo
route to A
fallthrough: true

match /f
route to B
```
have over 
```
match /foo
route to A, fail over to B

match /f
route to B
```
?

My point is that if the intent here is to just provide a way to specify this kind of failover in the route table, it can likely be better solved by incorporating the fall through into the load balancer. 

Would love to hear it if you have any use cases that require this to be a route level concept.
