### ISSUE TITLE
config dump: allow search/filtering

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#8743]
It would be nice to have query strings that allow dumping only listeners, only clusters, and potentially searching for specific names within those dumps. 

This could be done by a different tool but it seems useful to have some basic ability built in.

**Comment by spenceral** [comment]
I can work on this.

**Comment by mattklein123** [comment]
@spenceral awesome! Go for it. LMK if you have any questions. This will be super useful.
