### ISSUE TITLE
char32_t not supported in Windows MSVC Studio 2017

### ISSUE THREAD

**Issue by wrowe** [envoyproxy/envoy#8750]
This error appears to be a newly-introduced usage of or support for char32_t strings, perhaps from a recent PGV or logging or envoy v2 API change which occurred on Envoy master branch during the week of October 7th.

ERROR: C:/workspace/envoy/source/exe/BUILD:26:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1120)

pkg_cc_proto.lo.lib(cds.pb.validate.obj) : error LNK2001: unresolved external symbol "public: static class std::locale::id std::codecvt<char32_t,char,struct _Mbstatet>::id" (?id@?$codecvt@_UDU_Mbstatet@@@std@@2V0locale@2@A)

bazel-out/x64_windows-fastbuild/bin/source/exe/envoy-static.exe : fatal error LNK1120: 1 unresolved externals

This is a well-understood problem of Microsoft's runtime, that std::codecvt only instantiated their templates for conversion of 8 and 16 bit char types, and has not (may never) fix the defect due to binary ABI rules. See;
https://social.msdn.microsoft.com/Forums/en-US/8f40dcd8-c67f-4eba-9134-a19b9178e481/vs-2015-rc-linker-stdcodecvt-error?forum=vcgeneral

We need to work around this short term, and it doesn't seem that Envoy should have much need itself for 32-bit chars. We are looking at shifting to VS 2019, but were hoping to avoid having environmental changes derail windows build progress. If the newly introduced change were optional/could be toggled, that would be sufficient.

**Comment by lizan** [comment]
Does VS 2019 solve the problem? Windows CI is on VS 2019 on Windows Server 2019, so even we have short term fix it might be fragile.

**Comment by wrowe** [comment]
A short update; this was caused by this commit;
https://github.com/envoyproxy/protoc-gen-validate/pull/256
which we have backed out in our working tree to unblock us in the very short-term.

Longer term we are looking at a PGV issue/PR and proposing a better mechanism for utf-8 code 
point counting, that would not involve allocating and trans-coding the string into utf-32, which
does not involve the now-deprecated codecvt class. Leaving this ticket open for such a fix, so any 
others who trip over this can find the open issue.

**Comment by lizan** [comment]
Left a comment in that PR https://github.com/envoyproxy/protoc-gen-validate/pull/256#discussion_r340236064

**Comment by wrowe** [comment]
For more comprehensive closure than simply stalebot...

https://github.com/envoyproxy/protoc-gen-validate/pull/284

was the resolution to the compilation issue. 

https://github.com/envoyproxy/protoc-gen-validate/pull/256#discussion_r340769596

is a lingering flaw which was reported to
