### ISSUE TITLE
How to obtain the public IP address from the x-forwarded-for header

### ISSUE THREAD

**Issue by seguidor777** [envoyproxy/envoy#8761]
Hello everyone,

I am trying to get the public IP from the client (original IP) and use it in the actions of the rate limit.
I am using the use_remote_address option, but only inject the first trusted IP from the XFF list, which is the same as my cloud provider's load balancer.

Could you please give me a clue on how to get the public IP?, no matter it could be forged

Edit: Using Envoy v1.10.0

**Comment by seguidor777** [comment]
Config:
```yaml
use_remote_address: true
xff_num_trusted_hops: 1
```

Response headers:
```
'x-forwarded-for', '10.x.x.x'    <--- IP from the Envoy immediate downstream
'x-envoy-internal', 'true'
```

The documentation says:

> If use_remote_address is set to true, the request is internal if and only if the request contains no XFF and the immediate downstream node’s connection to Envoy has an internal (RFC1918 or RFC4193) source address

So I think that my load balancer is not properly setting the x-forwarded-for header (more likely) or Envoy is recognizing its IP as internal

**Comment by seguidor777** [comment]
Config:
```yaml
use_remote_address: true
xff_num_trusted_hops: 1
```

Response headers:
```
'x-forwarded-for', '10.x.x.x'    <--- IP from the Envoy immediate downstream
'x-envoy-internal', 'true'
```

The documentation says:

> If use_remote_address is set to true, the request is internal if and only if the request contains no XFF and the immediate downstream node’s connection to Envoy has an internal (RFC1918 or RFC4193) source address

So I think that Envoy is recognizing the IP of my load balancer as internal

Is there any way to skip this behaviour, maybe using a filter?

**Comment by seguidor777** [comment]
Closing this, since it was a problem with my Kubernetes service.

This guide is very helpful to anyone having the same issue
https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-loadbalancer

**Comment by halemanipooja** [comment]
@seguidor777
I know this was closed long back wanted to check if you were able to get the public ip of the client in x-forwarded-for
