### ISSUE TITLE
Add support for subset load balancing to `envoy.tcp_proxy`

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#8769]
*Title*: Add support for subset load balancing to `envoy.tcp_proxy`

*Context*:

I’m trying to configure Envoy to use load balancer subsets at L4.

E.g., I want to dispatch 10% of traffic to endpoints marked as “master” and 90% to endpoints marked as “replica”.

Ideally, my configuration should look like

```
name: envoy.tcp_proxy
typedConfig:
  '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
  statPrefix: postgres.internal:5432
  weighted_clusters:
    clusters:
    - name: postgres.internal:5432
      metadata_match:                       # NOTE: there is no `metadata_match` field at the moment
        filter_metadata:                    #
          envoy.lb:                         #
            role: master                    #
      weight: 10
    - name: postgres.internal:5432
      metadata_match:                       # NOTE: there is no `metadata_match` field at the moment
        filter_metadata:                    #
          envoy.lb:                         #
            role: replica                   #
      weight: 90
```

However, `envoy.tcp_proxy` does not support `metadata_match` per weighted cluster at the moment.

*Proposal*:

* add `metadata_match` field to `TcpProxy.WeightedCluster.ClusterWeight` (similarly to `route.WeightedCluster.ClusterWeight`)
* use `metadata_match` field to enable subset load balancing at `envoy.tcp_proxy`

**Comment by zuercher** [comment]
Sorry, I don't think I entirely understood your request when I responded in Slack. It's feasible to add metadata fields to the ClusterWeight definition in the tcp_proxy.

That said, it might be simpler to just have separate master and replica clusters and skip the subset load balancer altogether.
