### ISSUE TITLE
Propagate Cluster.alt_stat_name to RouteEntry

### ISSUE THREAD

**Issue by veshij** [envoyproxy/envoy#8774]
We use custom `PassThroughEncoderFilter` which emits some cluster-specific stats.
Currently we use `streamInfo.routeEntry()->clusterName()` for this purpose, but since Cluster.alt_stat_name is not propagated to RouteEntry we can't achieve consistent logging across different code paths.
Would it make sense to provide cluster's alt_stat_name via RouteEntry?

**Comment by mattklein123** [comment]
You can look up the cluster and then get the alt stat name from cluster info right?

**Comment by veshij** [comment]
Yep, that should work, sorry for bothering.
