### ISSUE TITLE
add request timeout in retry policy

### ISSUE THREAD

**Issue by gongcon** [envoyproxy/envoy#8777]
There's no request_timeout enum in `retry_policy`. Only `5xx` and `gateway-error` (502, 503, 504) has the ability to retry on request timeout. `retriable-status-codes` only works when upstream responses. In our use case, we don't want to retry on 503, but definitely retry on request timeout. Given an individual request_timeout enum will give more flexibilities. Users can combine it with `retriable-status-codes` to retry on any code they want. Or adding status_code_exclusion will work as well.

**Comment by snowp** [comment]
Is the `reset` retry policy not sufficient for this? From what I can tell it would retry upstream timeouts (as they result in an upstream reset)

At a glance this seems like a reasonable addition, but if existing retry policies cover this I'd prefer to not add additional complexity.

**Comment by gongcon** [comment]
Thank you for the clarification. `reset` works for us.

**Comment by gongcon** [comment]
Closed it too early. `reset` does not work as expected when a HTTP request times out. May be it's bug. Based on the document, seems it should be the right one.

> 5xx: Envoy will attempt a retry if the upstream server responds with any 5xx response code, or does not respond at all (disconnect/reset/read timeout). (Includes connect-failure and refused-stream)
> reset: Envoy will attempt a retry if the upstream server does not respond at all (disconnect/reset/read timeout.)

**Comment by dio** [comment]
@gongcon to clarify, this is the [`408 Request Timeout`](https://tools.ietf.org/html/rfc7231#section-6.5.7)?

**Comment by gongcon** [comment]
No, the case is when server does not response on time or not response at all, for example, `per_try_timeout` is set to 100ms yet the server responses in 200ms, Envoy should terminate the request and retry at 100ms. `5xx` and `gateway-error` have this behavior but `reset` does not.

**Comment by gongcon** [comment]
Anyone can help on this? @dio @snowp ?
