### ISSUE TITLE
logging support for filter state

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8790]
FilterState is C++ typed so currently there is no easy way to log them. I'm proposing add optional methods to FilterState interface to serialize it to protobuf.Any or string so the gRPC logger / file logger can log them.

**Comment by kyessenov** [comment]
Can we avoid serialization in introspection? Generic protobuf representations are very slow, so it seems like converting to protobuf would defeat the use of filter state over the dynamic metadata.

**Comment by lizan** [comment]
@kyessenov The serialization method will be only called when a logger is configured to log the filter state, if nothing configured in logger there will be no affect on performance.

**Comment by rcash** [comment]
Hi @lizan I'm a student in UT Austin's Virtualization & Containers class, are you looking for help on this? Thanks!

**Comment by lizan** [comment]
@rcash Thanks for your help. I will take this one myself as this is on my priority now, but you are welcome to take any issue marked `help wanted`, if you're new here, look for `beginner` tag as well.

**Comment by kyessenov** [comment]
@lizan that's fair, but if there is a business need to forward the filter state, there is not going to be an alternative. I was hinting at using some language reflection capabilities using plain old code generation, that will eventually align with the latest C++ designs on the subject (e.g. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1240r1.pdf)

**Comment by lizan** [comment]
@kyessenov yeah reflection can be used in future, though is there any usable library / implementation on C++ reflection today?

**Comment by kyessenov** [comment]
@lizan I'm not aware of any quality library for reflection in C++. It also sounds like an overkill to support the entire C++. We just want simple structs for majority of the use cases of the filter state. Just using protobuf message is not a terrible idea since it comes with reflective capabilities by default (albeit there is a hit to performance).
