### ISSUE TITLE
is possible to use envoy grpc proxy/filter embedded  in c++ grpc server binary

### ISSUE THREAD

**Issue by samuelazcona** [envoyproxy/envoy#8800]
Hi guys,

I'm very new with envoy (30 minutes), I'm search for solution to communicate angular http1.1 front ends with my c++ grpc backend and google send me to envoy.

I'm working in backend in c++ that contains a grpc server all is working fine but one of the front ends are in angular/dart.

So I see there is an envoy docker image to up and config to help me to communicate the angular with my grpc backend.

But the question: is possible to build or use envoy embedded in my backend for example from my backend main.cpp start the grpc server on port 8080 and the envoy proxy on port 9090 with my configuration and build it in one single binary, to front ends only need to run the backend binary without needed to run the docker or envoy first and send the request to the port 9090?

Is there any example about this?.

Thanks and sorry if this is not the place to make this question.

**Comment by zuercher** [comment]
https://envoy-mobile.github.io/ is a project that's working on a Enovy-as-a-library for mobile. I don't know of any other examples.
