### ISSUE TITLE
how to enable log fields with envoy jaeger-native-tracing

### ISSUE THREAD

**Issue by alochym01** [envoyproxy/envoy#8805]
Hi 

there are some naming conventions for span tags and log fields
[https://github.com/opentracing/specification/blob/master/semantic_conventions.md](url)

but in the example on tracing there is no glue to add log fields or span tags 
[https://github.com/envoyproxy/envoy/tree/master/examples/jaeger-native-tracing](url)
[https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/service.py](url)

how to add more log fields or span tags

thank you

**Comment by objectiser** [comment]
Do you mean add log/tags from within the Envoy proxy (when handling your requests) or from within the service that is being proxied?

**Comment by alochym01** [comment]
@objectiser i mean add log/tag from within the service

please help

thank you

**Comment by objectiser** [comment]
Which language are you using for your service? You need to instrument your app with the appropriate OpenTracing API and Jaeger tracer.

**Comment by alochym01** [comment]
i use python [https://github.com/jaegertracing/jaeger-client-python](url), 
just using sample 
```python
    with tracer.start_span('TestSpan') as span:
        span.log_kv({'event': 'test message', 'life': 42})

        with tracer.start_span('ChildSpan', child_of=span) as child_span:
            span.log_kv({'event': 'down below'})
```
because envoy auto `generate_request_id: true`

but i don't know how integrated with envoy jaeger-native-tracing

do i need to create new span from within service.py ?? 

thank you

**Comment by objectiser** [comment]
You don't necessarily need to create a span within the service - only if you want to. The important thing is to propagate the context, which can be achieved using [the `extract` and then `inject` functions](https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson03).

**Comment by alochym01** [comment]
thank you, got it
it should be update the example service.py :)

**Comment by objectiser** [comment]
@alochym01 Unfortunately the service `service.py` is shared across multiple examples which use different tracers. If you can think of a way to implement that supports the different examples, feel free to submit a PR :)
