### ISSUE TITLE
add QUICHE stream buffer testing

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#8826]
StreamEncoder::encodeData() assumes transport layer takes all the data. In QUICHE we achieve this by setting FLAGS_quic_buffered_data_threshold to be large enough (512MB) to buffer all the data under the high watermark plus a flow control window DEFAULT_INITIAL_STREAM_WINDOW_SIZE (256MB). This is a really large buffer for each stream, but we don't expect the upstream will negotiate such large flow control window for all backend services. 
Ideally, we should ask the router filter about the negotiated receive flow control window and adjust the down stream send buffer size. 

Another thing to watch out for is FLAGS_quic_buffered_data_threshold doesn't apply to QUIC crypto stream and header stream. So their send buffer in theory can grow infinitely.
In IETF QUIC, we don't have header stream, but send headers on data stream. The total stream count doesn't decrement till all the sent data is ACK'ed.  So the total buffer used by the connection is capped by the max concurrent stream limit. In Google QUIC, after connection buffers headers in headers stream with FIN the data stream is considered as closed and decrement the stream count. And the fix should be as easy as add a uppper limit to header stream send buffer and close the connection if it buffers too much data. The IETF implementation is under testing now, so by the time Envoy support QUIC in production, we very likely already switch to IETF one. 
Crypto stream doesn't honor FLAGS_quic_buffered_data_threshold either, but unless our handshake implementation has problem, it shouldn't transfer more than 16KB data. But currently QUICHE doesn't have this check on the send side, though we check this limit on the receive buffer. These enforcement needs to be added to QUICHE to make sure the QUICHE buffers are always capped.

**Comment by danzh2010** [comment]
To enhance buffer limit on headers stream, it is easier to count bytes buffered in header stream send buffer into connection level buffer in Envoy instead of having its own buffer limit in upstream QUICHE.

**Comment by alyssawilk** [comment]
Tagging as quic alpha just to make sure we are happy with buffer limits as configured before we un-hide config.
I think some of the work can wait for mvp but will let dan document what goes where :-)

**Comment by danzh2010** [comment]
Regarding QUIC crypto stream buffer, we could trust QUICHE handshake implementation wouldn't OOM itself even without send buffer enforcement.
Regarding QUIC header stream buffer, it's send buffer contributes to connection level watermark which is configured via perConnectionBufferLimitBytes.

**Comment by danzh2010** [comment]
We are removing support for gQUIC and thus no need to worry about header and crypto stream. But we need to make sure all the H3 streams' send buffers are bounded, i.e. the peer can't make control stream and Qpack send/receive streams to buffer infinitely.

**Comment by yanavlasov** [comment]
I have constructed tests that I wanted to run and also looked deeper into the integration between Envoy and QUIC. All of my test shave passed, meaning that there I do not currently see a way to abuse QUIC to consume more memory than flow control would allow. It even works for local responses. However I think some missing coverage needs to be improved, without blocking GA. Specifically:

1. There are no tests that verify that downstream stream limit is working (we do not even know if plumbing from listener config to QUIC codec is working).
2. There are no integration tests that validate that Envoy's flow control with QUIC protocol works.

It would good to provide a way to override some behavior for the QUIC client, such as allowing it to ignore peer specified stream limit and also set fixed size for the congestion window, such that high watermark levels can be known.

Apart from that this issue can be resolved.
