### ISSUE TITLE
Support prefix rewrites with after string matches

### ISSUE THREAD

**Issue by drao9** [envoyproxy/envoy#8833]
*Title*: *Prefix rewrite with after string matches*

*Description*:
 In the case of prefix rewrite, we want to match a prefix string and replace it with another but also insert a new string after the designated string in the original matched full string. We would need a field in the config to provide this string (let's call it after_str). For example, if we want  `www.example.com/foo/bar/zoo/1234/abc` to go to `www.example.com/baz/1234/abc`:

we would have config such as: 
```
        {
      "name": "www3",
      "domains": ["example.com", "www.example.com"],
      "routes": [
        {
          "prefix": "/foo",
          "prefix_rewrite": "/baz",
          "after_str": "/zoo",      <<<<<<<<<<< 
          "cluster": "www3"
        },
```
So when the request such as `www.example.com/foo/bar/zoo/1234/abc` comes in, we rewrite `/foo` with `/baz` and then add string after the after_str: zoo, so we form `/baz/1234/abc`. 

I was wondering if there is any other way of doing this? If not, would the upstream community be interested in this feature?

**Comment by mattklein123** [comment]
This feels very specific to me and probably not a general enough use case to add a full feature for. I wonder if this could be done by regex rewrite or a Lua filter or something like that? @zuercher WDYT?

**Comment by zuercher** [comment]
I agree this is something we should support with regex rewrites. There's an open PR for that now (#8462), which will hopefully land eventually.

Otherwise, yeah I think it's probably more appropriate to use the Lua filter.

**Comment by drao9** [comment]
#8462 should cover use cases like these. Thanks for the response! @mattklein123 @zuercher
