### ISSUE TITLE
docs: fix search engine optimization (SEO) to only index latest

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#8838]
We need a robots.txt, map, etc. to make sure that Google only indexes our latest docs. Opening this issue in the hope that someone knows how to do this.

**Comment by moderation** [comment]
I'm not an SEO expert by any means but having a quick look at https://www.robotstxt.org/robotstxt.html I think we need a `robots.txt` file at root with something like
```
User-agent: *
Disallow: /docs/envoy/v1.11.2/
Disallow: /docs/envoy/v1.11.1/
Disallow: /docs/envoy/v1.11.0/
Disallow: /docs/envoy/v1.10.0/
Disallow: /docs/envoy/v1.9.1/
Disallow: /docs/envoy/v1.9.0/
Disallow: /docs/envoy/v1.8.0/
Disallow: /docs/envoy/v1.7.1/
Disallow: /docs/envoy/v1.7.0/
Disallow: /docs/envoy/v1.6.0/
Disallow: /docs/envoy/v1.5.0/
```
And to make it worse we'll need to update it each time there is a new release.

**Comment by mattklein123** [comment]
I would think there is a way to disallow based on wilcard/regex but I have no idea.

**Comment by mattklein123** [comment]
I opened a CNCF service desk ticket to have someone help us fix this. I think it should be easy for someone that knows what they are doing.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoyproxy.github.io/pull/139
