### ISSUE TITLE
limit payload size with lua script

### ISSUE THREAD

**Issue by yoka791** [envoyproxy/envoy#8866]
Hi,
I tried to write to following script in order to limit request size to 2MB, but when using `body():length()` it returns 413 (Payload too large) when reaching 1MB (and doesn't continue with the function).
```yaml
function envoy_on_request(request_handle)
  local max_bytes = 2 * 1024 * 1024
  local body_size = request_handle:body():length()
  if body_size > max_bytes then
    request_handle:respond(
      {[":status"] = "413"})
  end
end
````
Does anyone knows how to solve that? Thanks.

**Comment by mattklein123** [comment]
I would just let Envoy do this limiting for you, either via the buffer filter or the built-in buffering limits. See https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control for more information.
