### ISSUE TITLE
option 'close_connections_on_host_set_change' can't destroy long-live stream

### ISSUE THREAD

**Issue by chijinxina** [envoyproxy/envoy#8867]
I use envoy to proxy long-live server-side grpc stream, the upstream cluster option 'close_connections_on_host_set_change' has been set to 'true'. When hosts changed, the grpc stream can't destroy.

**Comment by mattklein123** [comment]
IIRC this setting invokes draining on the connection which tries to do it gracefully vs. forceful closure. for a long lived stream there would never be any graceful closure so I don't think this is going to work, but cc @nezdolik who can provide more info.

**Comment by nezdolik** [comment]
Hello @chijinxina,  'close_connections_on_host_set_change' most likely would not work for long-lived grpc streams. Could you please provide sample Envoy config for me to confirm.

**Comment by leosunmo** [comment]
I know this is a long-dead issue, but I've just recently run in to an issue where I would like to terminate long-lived gRPC streams when my Cluster changes. Are there any plans to add a `forcefully_close_connections_on_host_set_change`?

Having a function that is identical to this, but if it fails to gracefully terminate the connection withing a certain time-frame (ideally configurable as well), it forcefully closes the connection so it can be re-established.

**Comment by mattklein123** [comment]
> I know this is a long-dead issue, but I've just recently run in to an issue where I would like to terminate long-lived gRPC streams when my Cluster changes. Are there any plans to add a forcefully_close_connections_on_host_set_change?

This has come up several times, and I'm guessing we have tracking issues about this but I haven't searched yet (assuming it hasn't already been implemented). I think it's a reasonable feature to add and I would open an issue if it's not already tracked. cc @snowp

**Comment by leosunmo** [comment]
@mattklein123 I'm glad to hear I'm not the only one running in to this problem!

I am currently in the process of trying to interrogate the Envoy xDS for Cluster updates so I can manually terminate my gRPC streams in my application, which does seem like a hack to me, and it's proving quite difficult to get started _getting_ cluster state/config from Envoy, not _setting_ it. All guides out there are for Control Plane implementations.

I feel like a way for Envoy to terminate long-running gRPC streams would be a very good addition.
