### ISSUE TITLE
change buffer content and headers in reply - encodeData

### ISSUE THREAD

**Issue by aby-rd** [envoyproxy/envoy#8868]
I would like to change the content of the buffer in encodeData according to tests that i'm running in my filter. I also need to change the headers because the new buffer content is from different type (JSON). Is there any way to change them both in this phase? I tried to save ptr to HeadersMap in encodeHeaders but it seems like the headers are deleted although encodeHeaders returns stopIteration. I thought this status stops the headers and not just the body.

**Comment by mattklein123** [comment]
This should work by stopping iteration in headers and then modifying headers and continuing during data processing. There are several filters that do this so I would have a look at the existing examples or provide more info about what you are doing.

**Comment by aby-rd** [comment]
Thanks for your answer!
It can works but I don't know in headers phase if I need to change the buffer, i only know it in data processing. stop iteration doesn't stop headers until data process complete? or at least data continue?
