### ISSUE TITLE
build: enable -Winconsistent-missing-override warning

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#8880]
*Title:*

Enable -Winconsistent-missing-override warning

*Description:*

The Google style guide recommends always using `override` and code reviewers also ask for it to be used. If there's a warning, then contributors will add it before reviewers have to ask.

*Relevant Links:*

Clang:
```
-Winconsistent-missing-override
This diagnostic is enabled by default.

Diagnostic text:
warning: A overrides a member function but is not marked ‘override’
```

GCC:
```
-Wsuggest-override
Warn about overriding virtual functions that are not marked with the override keyword.
```

**Comment by lizan** [comment]
@jpeach I believe we already enabled this and treated as error, do you see anywhere that this is not treated as error?

**Comment by jpeach** [comment]
> On Nov 5, 2019, at 5:11 PM, Lizan Zhou <notifications@github.com> wrote:
> 
> @jpeach I believe we already enabled this and treated as error, do you see anywhere that this is not treated as error?

grep doesn’t find it in the repo. I was asked to add override by the reviewers in #8873.

**Comment by lizan** [comment]
@jpeach because we enable `-Wall` and `-Wextra` which includes `-Winconsistent-missing-override` in clang. I tried your commit with `--cxxopt=-Winconsistent-missing-override` to bazel and it doesn't flag anything either.

**Comment by jpeach** [comment]
[wextra](https://clang.llvm.org/docs/DiagnosticsReference.html#wextra) claims it doesn't enable that warning. But I might have been thinking of [modernize-use-override](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html). Is it possible to enable that for envoy code but not for any 3rd party (or generated protobuf) code?

**Comment by lizan** [comment]
@jpeach itself claims "This diagnostic is enabled by default." so it doesn't need anything, we do `-Werror`. Though I don't think this warning will flag anything on your PR.

**Comment by jpeach** [comment]
modernize-use-override is already in the default [clang-tidy config](https://github.com/envoyproxy/envoy/blob/master/.clang-tidy).
