### ISSUE TITLE
Sticky-session for path based routing with envoy as sidecar proxy

### ISSUE THREAD

**Issue by vichooz** [envoyproxy/envoy#8888]
My apologies if this comes as a beginner's question

I'd like to understand if the following scenario is supported by envoy-proxy
- the first user’s request comes in without session information
- the request bypass the session server choice since it has no session information
- the request pass through the routing algorithm, where a server is chosen and affected to the client
- the server answers back, setting its own session information
- depending on its configuration, envoy router/LB can either use this session information or setup its own before sending the response back to the client
- the client sends a second request, now with session information he learnt during the first request
- the router/LB choose the server based on the client side information
- the request DOES NOT PASS THROUGH the load-balancing algorithm
- the server answers the request

If it is, are there any examples that I can take a look at for understanding the configurations better? Thanks

**Comment by mattklein123** [comment]
TL/DR we don't support this today, but this is also discussed in https://github.com/envoyproxy/envoy/issues/7218. There hasn't been a good proposal yet on how we would encode upstream information into the session cookie.
