### ISSUE TITLE
Statsd sink unable to send metrics via UDS if statsd agent starts after envoy starts.

### ISSUE THREAD

**Issue by prudhvi** [envoyproxy/envoy#8911]
*Title*: *statsd sink not able to send metrics to UnixDomainSocket address if the statsd agent didn't start before envoy starts*

*Description*:
> Envoy unable to send metrics to statsd sink specifically dog_statsd sink configured with pipe path pointing to Unix Domain Socket if statsd agent(eg: Veneur) doesn't start before envoy.

*Repro steps*:
>  We run statsd agent, [Veneur](https://github.com/stripe/veneur)  as a sidecar to our edge envoy and we noticed that envoy stats are not being successfully sent to UDS (Unix Domain Socket) that veneur listens on if veneur starts after envoy starts or if veneur restarts. It works fine as long as envoy starts after veneur starts first and starts reading from UDS. I am attaching the failed and successful strace calls below. 

Successful:
```
 strace -yy -fp 156194  2>&1 | grep sendto
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.cluster.edge_https.up"..., 90, MSG_DONTWAIT, NULL, 0) = 90
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.cluster.edge_http.ups"..., 89, MSG_DONTWAIT, NULL, 0) = 89
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.downstream_cx_rx_byte"..., 98, MSG_DONTWAIT, NULL, 0) = 98
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.downstream_cx_tx_byte"..., 99, MSG_DONTWAIT, NULL, 0) = 99
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.downstream_rq:0|c|#ap"..., 100, MSG_DONTWAIT, NULL, 0) = 100
[pid 156194] sendto(76<UNIX:[404333076->404322827]>, "edge-envoy.downstream_cx_total:1"..., 88, MSG_DONTWAIT, NULL, 0) = 88
[pid 156194] sendto(76<UNIX:[404
```
Unsuccessful:
```
strace -yy -fp 160027 2>&1 | grep sendto

not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_rq_active:"..., 89, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_cx_active:"..., 89, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_cx_active:"..., 99, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.server.live:1|g|#app:"..., 58, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_cx_active:"..., 82, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_rq_active:"..., 82, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downstream_cx_active:"..., 98, MSG_DONTWAIT, NULL, 0) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 160027] sendto(76<UNIX:[662414141]>, "edge-envoy.downst
```
I think the issue might be due the fact we do [connect](https://github.com/envoyproxy/envoy/blob/v1.11.2/source/extensions/stat_sinks/common/statsd/statsd.cc#L27) even for Datagram type in UDS and also write using [send](https://github.com/envoyproxy/envoy/blob/v1.11.2/source/extensions/stat_sinks/common/statsd/statsd.cc#L38) which doesn't explicitly use the configured path under pipe config as the destination socket address instead in a call using [sendto](https://linux.die.net/man/2/sendto). This issue doesn't happen when using udp port as statsd sink address (ie: statsd agent listening on udp port)

*Config*:
> 
```
stats_sinks:
   - name: envoy.dog_statsd
      config:
        address:
          pipe:
            path: "data/app/tmp/veneur.sock"
      prefix: edge-envoy
```

**Comment by mattklein123** [comment]
Thanks for the report. I'm doing a bunch of UDP work now and can potentially take a look at fixing this. Also related to https://github.com/envoyproxy/envoy/issues/1028
