### ISSUE TITLE
Envoy Connections are refreshed when using control plane

### ISSUE THREAD

**Issue by roobalimsab** [envoyproxy/envoy#8912]
*Description*:
We are using golang envoy-control-plane to update the envoy routing configs. Envoy acts as a proxy for grpc requests (persistent connections). What we noticed is, whenever the routing configuration is reset after getting the snapshot from the control plane, all the connections are dropped and recreated. 

We are updating the config snapshot every 10 seconds using SetSnapshot and a new version. This refreshes the configs and the connections and hence we are losing the advantage of persistent connections.

Is there any way to avoid this connection refresh to upstreams during configuration updates? Or are we doing anything wrong here?

**Comment by mattklein123** [comment]
If you use EDS for upstream host changes, there should be no effect to the connections of existing hosts.
