### ISSUE TITLE
Unable to find package for @rules_cc//cc:defs.bzl

### ISSUE THREAD

**Issue by twfx7758** [envoyproxy/envoy#8916]
Version: v1.12.0
ERROR: /root/.cache/bazel/_bazel_root/e7edfd76dba396281986d061d97b39c0/external/envoy_api/envoy/api/v2/BUILD:7:1: error loading package '@com_goog
le_protobuf//': Unable to find package for @rules_cc//cc:defs.bzl: The repository '@rules_cc' could not be resolved. and referenced by '@envoy_api//envoy/api/v2:pkg_cc_proto'

**Comment by lizan** [comment]
@twfx7758 which version of bazel are you using? Follow instruction at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#installing-bazelisk-as-bazel to use right version of Bazel.

**Comment by twfx7758** [comment]
> @twfx7758 which version of bazel are you using? Follow instruction at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#installing-bazelisk-as-bazel to use right version of Bazel.

bazel version 0.28.1 thanks

**Comment by twfx7758** [comment]
> @twfx7758 which version of bazel are you using? Follow instruction at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#installing-bazelisk-as-bazel to use right version of Bazel.

thank you very much

**Comment by jerry2102** [comment]
@twfx7758 does bazel 0.28.1 not work anymore for building envoy? I encountered the same problem as you. but it is hard for me to update bazel use bazelisk as I have no public network access right

**Comment by lizan** [comment]
just use whatever version in .bazelversion file, you don’t have to use bazelisk
