### ISSUE TITLE
Enable Configurability of Internal Redirect HTTP Codes

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#8966]
The internal redirect feature on the router is [hard-coded](https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L1101) to HTTP 302 Found. There are other HTTP status codes that are a redirect-type with a `location` response header to tell the client where to go. This includes
* HTTP 301 Moved Permanently
* HTTP 307 Temporary Redirect
* HTTP 308 Permanent Redirect

We should allow users to select which of the above the internal redirect acts upon. I think this would be particularly handy for egress proxying, i.e. the dynamic forward proxy, and would fix [this request](https://github.com/envoyproxy/envoy/issues/8393).

**Comment by htuch** [comment]
@derekargueta could https://github.com/envoyproxy/envoy/pull/8921 be used to some effect here?
