### ISSUE TITLE
remove persistent envoy.reloadable_features.http2_protocol_options values

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#8993]
As discussed on #8849 the http protocol options values don't really mesh with the rest of the reloadable features.  Since we want to keep them around long term we should probably rename.

@yanavlasov can you pick this up some time in the next couple of months?

**Comment by mattklein123** [comment]
Per discussion in the other PR I think we now agreed we are going to delete them? cc @PiotrSikora

**Comment by PiotrSikora** [comment]
Yup, let's just remove them.

**Comment by alyssawilk** [comment]
As mentioned on 8849 we'll punt this to after the next release.  It's already no-stalebot so we'll check back in after the holidays :-)

**Comment by alyssawilk** [comment]
I'll take this one back as there's a couple of other flags and some associated clean up.
