### ISSUE TITLE
Documentation samples sometimes use deprecated config instead of typed_config

### ISSUE THREAD

**Issue by slovdahl** [envoyproxy/envoy#8996]
Having recently updated to 1.12, I started getting deprecation warnings like this for my statically configured Envoy:
```
envoy_1_fe0e8684e37f | [2019-11-07 06:20:51.140][1][warning][misc] [source/common/protobuf/utility.cc:282] Using deprecated option 'envoy.api.v2.listener.Filter.config' from file listener.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
envoy_1_fe0e8684e37f | [2019-11-07 06:20:51.140][1][warning][misc] [source/common/protobuf/utility.cc:282] Using deprecated option 'envoy.api.v2.listener.FilterChain.tls_context' from file listener.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
envoy_1_fe0e8684e37f | [2019-11-07 06:20:51.171][1][warning][misc] [source/common/protobuf/utility.cc:282] Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config' from file accesslog.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
```

I went through the documentation to find out how to fix the warnings, but quite quickly noticed that configuration samples in the documentation sometimes use `config`, and sometimes `typed_config` with a proper `@type`. For someone that isn't very familiar with Envoy, it was overall quite hard to find out what the right value for the `@type` field in `typed_config` is if a configuration sample was missing.

Is anyone working on fixing the documentation samples to use `typed_config`? If not I'd be willing to go through the samples and try to fix them.

**Comment by htuch** [comment]
@yanavlasov do you think we should update some of these? Also tagging @derekargueta who has done some amazing cleanups like this recently (but feel free to ignore).

**Comment by mattklein123** [comment]
This is a dup of https://github.com/envoyproxy/envoy/issues/5558. IMO this must be fixed as part of the deprecation. @yanavlasov can you help drive this forward even if you don't end up doing all the work?

**Comment by mattklein123** [comment]
Also related to https://github.com/envoyproxy/envoy/issues/8837

**Comment by slovdahl** [comment]
> This is a dup of #5558.

Sorry for that, I tried looking for an existing issue, but somehow missed that one. Feel free to close this one.

**Comment by mattklein123** [comment]
OK let's track in the other issue, I still think it's critical that we get this fixed though. :)

**Comment by yanavlasov** [comment]
Yes, absolutely, this needs to be fixed.
