### ISSUE TITLE
Additional grpc request data on tracing spans

### ISSUE THREAD

**Issue by cgilmour** [envoyproxy/envoy#9002]
Similar to the additional data added for #7944, we've had a user requesting more tags for traces from their grpc traffic.
The specific one requested is the `:path`, but it could be useful to also add `content-type`, `:authority` and `grpc-timeout` from the request.

As always, if the idea is reasonable, I'll be happy to implement it.

**Comment by htuch** [comment]
@cgilmour would https://github.com/envoyproxy/envoy/pull/8279 help here?

**Comment by cgilmour** [comment]
Looks like it would be an alternative way of doing it.
But I think that amount of config effort for a user is a bit high, and makes sense when users are actually doing custom/specialized things.
The ones suggested above are fairly basic grpc items, rather than specialized ones. So I think it'd be nicer if they "worked" out of the box instead of via special config.

**Comment by htuch** [comment]
Seems reasonable, I've assigned the issue to you.

**Comment by cgilmour** [comment]
Still intending to work on this in the near future.
