### ISSUE TITLE
Can you provide an envoy binary package based on ARM64 architecture?

### ISSUE THREAD

**Issue by AL-Cui** [envoyproxy/envoy#9006]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: *One line description*

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behaviour, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by htuch** [comment]
The Envoy OSS project doesn't support or distribute binaries. We do ship a Docker image that contains an exemplar x86 Envoy binary on a best effort basis. You probably want to look to a project like https://www.getenvoy.io or distribution such as Red Hat to provide support here.

**Comment by moderation** [comment]
As @htuch mentioned binaries aren't provided but Envoy does compile on arm64 / aarch64. I successfully compile it on a Pine64 RockPro64 SOC that has 4G RAM.

**Comment by AL-Cui** [comment]
@moderation 
ok,thanks.But,Bazel is really very difficult to use

**Comment by moderation** [comment]
@AL-Cui Bazel not super easy but I compile it from source on aarch64:
- wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-dist.zip
- unzip and cd into directory
- `env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh` (I use Fish shell so modify for your shell)

**Comment by AL-Cui** [comment]
> @AL-Cui Bazel not super easy but I compile it from source on aarch64:
> 
> * wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-dist.zip
> * unzip and cd into directory
> * `env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh` (I use Fish shell so modify for your shell)

yes,I hava installed the bazel from [https://docs.bazel.build/versions/0.22.0/install-redhat.html](url).  But, I can't  build success.

`ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

--------------------------------------------------------------------------------
NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
a developer checkout. Those checkouts do not include the generated output of
the protoc compiler (as we prefer not to version generated files).`

**Comment by AL-Cui** [comment]
> @AL-Cui Bazel not super easy but I compile it from source on aarch64:
> 
> * wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-dist.zip
> * unzip and cd into directory
> * `env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh` (I use Fish shell so modify for your shell)

But,I build failed.
`ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

--------------------------------------------------------------------------------
NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
a developer checkout. Those checkouts do not include the generated output of
the protoc compiler (as we prefer not to version generated files).`
