### ISSUE TITLE
TCP health check leads to the error log(Socket hang up) in upstream hosts

### ISSUE THREAD

**Issue by charliye** [envoyproxy/envoy#9020]
Issue Description:
After I config the tcp_health_check in envoy.yaml. I found there were some error logs in the upstream hosts' log file.
Detail log info as below:
{"type":"error","@timestamp":"2019-11-14T05:35:31Z","tags":["connection","client","error"],"pid":9,"level":"error","error":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:890:25)\n    at emitOne (events.js:121:20)\n    at TLSSocket.emit (events.js:211:7)\n    at _handle.close (net.js:561:12)\n    at Socket.done (_tls_wrap.js:360:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:561:12)","code":"ECONNRESET"},"message":"socket hang up"}
Config file:
- name: kibana_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        hosts:
          socket_address:
            address: kibana-master-svc.default.svc
            port_value: 5601
        health_checks:
          - timeout: {{.Values.envoy.healthCheck.timeout}}
            interval: {{.Values.envoy.healthCheck.interval}}
            interval_jitter: {{.Values.envoy.healthCheck.intervalJitter}}
            unhealthy_threshold: {{.Values.envoy.healthCheck.unhealthyThreshold}}
            healthy_threshold: {{.Values.envoy.healthCheck.healthyThreshold}}
            tcp_health_check: {}

**Comment by mattklein123** [comment]
@charliye I think these logs are coming from your application? What is the issue with Envoy here specifically?
