### ISSUE TITLE
ext_authz: allow receiving dynamic metadata from gRPC authorization server

### ISSUE THREAD

**Issue by erikbos** [envoyproxy/envoy#9049]
*Title*: ext_authz: enable receiving dynamic metadata from gRPC authorization server

*Description*:
I've got a custom authorization server which looks up some additional data for each request that I like to carry forward to other filters, but not upstream. 

Example use cases for setting metadata:

1. Setting dynamic rate limit value, authorization server has bespoke logic to determine rate limiting setting for request (leverages #11595)
2. Passing on internal authorization server fields which should end up in the access log (e.g. customerId, "rate limiter plan")

*Relevant links*
I think this might be the opposite of feature request https://github.com/envoyproxy/envoy/issues/7699 (Fixed with PR https://github.com/envoyproxy/envoy/pull/7818)

**Comment by mattklein123** [comment]
cc @dio @gsagula

**Comment by erikbos** [comment]
@Pchelolo FYI
