### ISSUE TITLE
Dynamic loading of OpenTracing tracers and ABI (in)compatibility 

### ISSUE THREAD

**Issue by gklingler** [envoyproxy/envoy#9055]
Hi, I'm working at Dynatrace and we are currently working on utilizing Envoy's OpenTracing API. 

Currently Envoy supports dynamic loading of tracers implementing the OpenTracing C++ API. The problem with C++ interfaces in general is that a lot of care needs to be taken for the consumer of a shared object and the shared object to be ABI compatible. 

ABI compatibility can only be guaranteed if the consumer (Envoy) and the shared library (the OpenTracing tracer library) are compiled with the same compiler and the same standard C++ library in the same version. 

Making generic assumptions about ABI compatibility is risky and not feasible. A simple compiler upgrade or switch to another C++ standard library implementation may result in an incompatible ABI, potentially leading to nasty crashes. 

This ABI compatibility would not be an issue when using a C interface. The C ABI is much simpler and much more stable the C++ ABI. Thus from an ABI compatibility perspective, a C interface should definitely be preferred over a C++ interface. 

We would like to be able to ensure the following with our tracer implementation: 

- being able to provide a single .so build that can be used as a tracer in any Envoy build, regardless of any differences in the build chain used 
- ensuring that even when facing an Envoy built with an unusual C++ toolchain, our tracer library at least won't make Envoy crash or prevent it from starting 

These goals are a challenge when interfacing a C++-based API. For example the recent switch to libc++ breaks the ABI with all existing tracer libraries. The same applies for switching compiler or compiler version.

It would be way easier to provide single .so tracer library implementing the C-API than a separately built library for potentially each possible current and future ABI variation. 

Note that this problem is not specific to the OpenTracing C++ API, or Envoy’s implementation of it, but it’s a general issue with any API based on C++. 

I’d like to open a discussion on this issue. Are there any plans to support OpenTracing tracer libraries implementing the C interface?

Regards, 
Gernot

**Comment by junr03** [comment]
I am not aware of any particular effort to accomplish this. @lizan do you mind commenting on your opinions/views on this issue?

**Comment by Oberon00** [comment]
Related: https://github.com/opentracing/opentracing-c/issues/18

**Comment by lizan** [comment]
I'm not aware of any effort either. I know that the recent C++ library change breaks the ABI compatibility of the dynamic_ot, as we discussed in #4251. I think it is a great idea to support C interface, if you're interested in doing the work feel free to take it.

**Comment by gklingler** [comment]
Ok, thanks for this info. We (at Dynatrace) are currently discussing our options. While implementing the OpenTracing C interface for envoy would probably the most straight forward way to "fix" this for envoy, some kind of "C++ to C bridge" could solve this OT ABI compatibility issue in a more generic way. I'll let you know once our plans are more concrete.

**Comment by lazy-always** [comment]
@gklingler, were you able to get this working? Any input on the same?

**Comment by gklingler** [comment]
@lazy-always, we work around this issue with appropriate "bridge-tracer libraries" (one for each ABI) which translates the opentracing C++ API calls to Dynatrace internal C API calls.
