### ISSUE TITLE
lua script outputs an error: attempt to index a nil value

### ISSUE THREAD

**Issue by yoka791** [envoyproxy/envoy#9056]
Hi,
I am using Ambassador which is built over envoy.
I wrote the following lua script in order to block requests with a payload bigger than 1KB (There is no option to apply the limit via envoy configuration):
```
function envoy_on_request(request_handle)
  local max_bytes = 1024
  local body_size = request_handle:body():length()
  if body_size > max_bytes then
    request_handle:logWarn("Request body is too large. max bytes is " .. max_bytes)
    request_handle:respond(
      {[":status"] = "413"})
  end
end
```
I get in the log:
`script log: [string "function envoy_on_request(request_handle)..."]:4: attempt to index a nil value`
Is there a problem with the script I wrote?

**Comment by caitong93** [comment]
When request have no body, `request_handle:body()` return nil which cause `length()` call to fail.

**Comment by yoka791** [comment]
> When request have no body, `request_handle:body()` return nil which cause `length()` call to fail.

Thanks! How can I check if a body exist?

**Comment by yoka791** [comment]
solved it:
```
function envoy_on_request(request_handle)
  local max_bytes = 1024
  local body = request_handle:body()
  if body ~=nil and body:length() > max_bytes then
    request_handle:logWarn("Request body is too large. max bytes is " .. max_bytes)
    request_handle:respond(
      {[":status"] = "413"})
  end
end
```
