### ISSUE TITLE
should support bazel startup option

### ISSUE THREAD

**Issue by wornik** [envoyproxy/envoy#9057]
https://github.com/envoyproxy/envoy/blob/4787e0a9b6810ff4cc0dd3f8d78cb8a1d7c2d73a/ci/do_ci.sh#L77

should add an option  for bazel startup， just like this
bazel ${BAZEL_STARTUP_OPTIONS}  build ${BAZEL_BUILD_OPTIONS} -c "${COMPILE_TYPE}" 

 
I am using http proxy. I need to change the bazel javabase to solve cacerts problem. so BAZEL_STARTUP_OPTIONS can use to add --server_javabase=${JAVA_HOME}

**Comment by lizan** [comment]
Just have that in your local user.bazelrc file.

**Comment by wornik** [comment]
OK . I got it. Thanks!
