### ISSUE TITLE
Serving jaeger with istio ingress gateway over http2 causes 503 error.

### ISSUE THREAD

**Issue by mooperd** [envoyproxy/envoy#9058]
Cross posting from istio. Serving jaeger with istio ingress gateway over http2 causes 

503: Upstream connect error or disconnect/reset before headers. reset reason: connection termination

```
# curl --http1.1  -I https://jaeger.foo.com/
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
date: Sat, 16 Nov 2019 17:10:56 GMT
x-envoy-upstream-service-time: 0
server: istio-envoy
transfer-encoding: chunked

# curl --http2  -I https://jaeger.foo.com/
HTTP/2 503 
content-length: 95
content-type: text/plain
date: Sat, 16 Nov 2019 17:11:01 GMT
server: istio-envoy
```

https://github.com/istio/istio/issues/19040

**Comment by junr03** [comment]
Unsure about how istio configures h2 support in the cluster configuration. Is the routing in the h2 attempt getting routed to an envoy cluster properly configured to handle h2 traffic?

**Comment by mooperd** [comment]
@junr03 Jaeger doesn't support http2.

```
root@vagrant:/usr/share/wireshark# curl --http2-prior-knowledge http://localhost:16686/ -Iv
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 16686 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55d9f016b580)
> HEAD / HTTP/2
> Host: localhost:16686
> User-Agent: curl/7.58.0
> Accept: */*
> 
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
* Connection #0 to host localhost left intact
curl: (16) Error in the HTTP2 framing layer
```

**Comment by junr03** [comment]
Yep that was my suspicion. We had a similar encounter with s3 earlier this year on envoy mobile. Closing this.

**Comment by mooperd** [comment]
Shouldn't the proxy transparently allow the client to negotiate the connection with the service?

**Comment by junr03** [comment]
Not implemented right now for upstream connections. Tracked here: https://github.com/envoyproxy/envoy/issues/3431. Envoy mobile will most likely Invest in this are sometime during the first half of next year.

**Comment by mooperd** [comment]
ok, thx

**Comment by moderation** [comment]
With Jaeger being a Go project which has native h2 support, they must explicitly disable it. Seems like a strange choice.

**Comment by objectiser** [comment]
According to the [go docs](https://golang.org/src/net/http/doc.go), "Starting with Go 1.6, the http package has transparent support for the HTTP/2 protocol when using HTTPS." - Jaeger is being accessed via http, not https.
