### ISSUE TITLE
location header shouldn't be set when the DirectResponse returns 200

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#9063]
We are unconditionally setting the `Location: ` header when returning direct responses:

https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L395

Whereas the header should _only_ be set when the response code is either 201 or 3xx per:

https://tools.ietf.org/html/rfc7231#section-7.1.2

cc: @sc0ttbeardsley @mattklein123 @alyssawilk

**Comment by rgs1** [comment]
(I can send a PR to address this in a bit, assuming we agree it needs fixing).

**Comment by rgs1** [comment]
Also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location.

**Comment by sc0ttbeardsley** [comment]
We ran into this while returning non-3xx direct responses.
