### ISSUE TITLE
Add UDP GRO support for efficient read

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#9064]
UDP recvmsg/recvmmsg is CPU costly compare to TCP. Linux 5.0 introduces UDP_GRO socket option to support batch reading [1]. The interface has two steps:
A socket has to signal to be willing to receive coalesced datagram payloads:
```
               if (setsockopt(fd, SOL_UDP, UDP_GRO, &val, sizeof(val)))
                       error(1, errno, "setsockopt gro");
```
And then on recvmsg() pass room for cmsg that holds the gso_size. 

We need to apply this feature to UdpListenerImpl with possibly read interface change.

[1] https://www.spinics.net/lists/netdev/msg523189.html and https://lwn.net/Articles/765309/

**Comment by nezdolik** [comment]
@mattklein123 would like to work on this.

**Comment by nezdolik** [comment]
After consulting with @danzh2010, this issue is allocated to internship project.
