### ISSUE TITLE
downstream_cx_active is matched with opened connections

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#9070]
**Issue Template**

*Title*: *downstream_cx_active is matched with opened connections*

*Description*:

We have only one ingress listener at 50051, and we can see the connections number is 697(`http.ingress.downstream_cx_active` and `listener.0.0.0.0_50051.downstream_cx_active`.
```
$ curl -s localhost:9901/stats | grep downstream_cx_active
http.admin.downstream_cx_active: 1
http.egress.downstream_cx_active: 171
http.ingress.downstream_cx_active: 697
http.kinesis_egress.downstream_cx_active: 3
listener.0.0.0.0_50051.downstream_cx_active: 697
listener.127.0.0.1_12345.downstream_cx_active: 171
listener.127.0.0.1_12346.downstream_cx_active: 3
listener.admin.downstream_cx_active: 1
```
Here's the connections(232):
```
$ sudo netstat -anp | grep :50051 | wc -l
284
# It's even less if we limit the ESTIBLISHED and the local 50051
$ sudo netstat -anp | grep 172.xxx:50051 | grep ESTABLISHED | wc -l
232
```

So why is `downstream_cx_active` bigger than the actual connections number?

My Envoy version:
```
$ envoy --version
envoy  version: 7a12f379e47a9f7cf7211c727fe8fc70b6a0a9ab/1.11.2/Clean/RELEASE/BoringSSL
```

I'm not very sure how to reproduce this, I just found this today on many instances.

**Comment by mattklein123** [comment]
Do you have appropriate idle timeouts configured? https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts

**Comment by tony612** [comment]
We are now using 1.13.1, but still have this issue. For below stats, I guess `listener.0.0.0.0_50051.downstream_cx_active` should equal `listener.0.0.0.0_50051.worker_0.downstream_cx_active` + `listener.0.0.0.0_50051.worker_1.downstream_cx_active` if what I understand is right. But it shows downstream_cx_active(64) > worker_0.downstream_cx_active(26) + worker_1.downstream_cx_active(17)
```
$ curl -s localhost:9901/stats | grep downstream_cx_active
curl -s localhost:9901/stats | grep listener.0.0.0.0_50051
listener.0.0.0.0_50051.downstream_cx_active: 64
listener.0.0.0.0_50051.downstream_cx_destroy: 204150
listener.0.0.0.0_50051.downstream_cx_total: 204193
listener.0.0.0.0_50051.downstream_pre_cx_active: 0
listener.0.0.0.0_50051.downstream_pre_cx_timeout: 0
listener.0.0.0.0_50051.http.ingress.downstream_rq_1xx: 0
listener.0.0.0.0_50051.http.ingress.downstream_rq_2xx: 6245687
listener.0.0.0.0_50051.http.ingress.downstream_rq_3xx: 0
listener.0.0.0.0_50051.http.ingress.downstream_rq_4xx: 0
listener.0.0.0.0_50051.http.ingress.downstream_rq_5xx: 0
listener.0.0.0.0_50051.http.ingress.downstream_rq_completed: 6245687
listener.0.0.0.0_50051.no_filter_chain_match: 0
listener.0.0.0.0_50051.worker_0.downstream_cx_active: 26
listener.0.0.0.0_50051.worker_0.downstream_cx_total: 89500
listener.0.0.0.0_50051.worker_1.downstream_cx_active: 17
listener.0.0.0.0_50051.worker_1.downstream_cx_total: 114693
```

After I restarted Envoy, downstream_cx_active works(. And even after deploying my application and sending some requests, it still works well. So I don't know how to reproduce my issue now. Maybe some bugs happen in some cases, which cause this?
