### ISSUE TITLE
the url of  tclap-1-2-1 is no longer valid

### ISSUE THREAD

**Issue by wornik** [envoyproxy/envoy#9071]
https://github.com/envoyproxy/envoy/blob/b0cbc879fc643d54d0309450bc2c233b3fa3b8fa/bazel/repository_locations.bzl#L84

downloading https://github.com/eile/tclap/archive/tclap-1-2-1-release-final.tar.gz GET returned 404 Not Found

this file url is no longer valid，today
In addition, how to use the  build option --distdir? 
I tried 
`build --distdir=/source/pkg, `
and the local file path is
/`source/pkg/com_github_eile_tclap/tclap-1-2-1-release-final.tar.gz`
 or
` /source/pkg/tclap-1-2-1-release-final.tar.gz`

But it is not succeed.

**Comment by wornik** [comment]
--distdir=/source/pkg
/source/pkg/tclap-1-2-1-release-final.tar.gz is OK

**Comment by moderation** [comment]
Looks like the Github repo has been deleted. May need to switch to https://sourceforge.net/projects/tclap/files/ ?
