### ISSUE TITLE
Support logicalName of host address for consistent hash load balancing

### ISSUE THREAD

**Issue by inf-rno** [envoyproxy/envoy#9074]
**Description**:
Currently consistent hashing is done using the weighted host's resolved address for both [ring hash](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/ring_hash_lb.cc#L130) and [maglev](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/maglev_lb.cc#L27) implementations. This does not work as intended in containerized workloads like docker, kubernetes etc. because when containers come back up they will most likely have a different resolved address and so will no longer maintain the consistent hash.

We, at Shopify, are using envoy to route to large clusters of redis and we need the hashing to be consistent when redis pods are failed over for whatever reason. But with the current implementation the ring is always resized and rehashed leaving behind inconsistent data.

**Recommended Solution**
Switch to using `logicalName` of the [address](https://github.com/envoyproxy/envoy/blob/master/include/envoy/network/address.h#L133) instead. But we will need to keep in mind this [comment](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/ring_hash_lb.cc#L133-L139) which talks about the size of the `hash_key_buffer`.

If this was an intentional use of the resolved address then perhaps we need to introduce an option like `useLogicalName(bool)` in the ring hash LB [config](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#envoy-api-msg-cluster-ringhashlbconfig) and add a similar config for maglev as well.

Once we agree on a solution, I can work on implementing it. Thanks. cc @mattklein123

**Comment by junr03** [comment]
@HenryYYang could you comment on this?

**Comment by inf-rno** [comment]
@junr03 @HenryYYang @mattklein123 I'm bumping this up to get your attention because I think the current behaviour is not usable in any containerized environmen.

Given that almost every example uses docker and the large number of kubernetes production deployments we might want to treat this as a bug fix and not just a new design proposal. Currently the consistent hash ring will always resize the ring whenever an upstream rejoins. 

I do have bandwidth to help fix this issue once we agree on the solution.

**Comment by mattklein123** [comment]
@inf-rno I'm sorry but I don't think I fully understand the problem. It seems appropriate that if a pod IP address change you would want to re-hash? What logical names are we talking about exactly? DNS names?

**Comment by inf-rno** [comment]
Yes. We are talking about DNS names. This would be a common use case for any upstream that has a consistent naming scheme e.g. In Kubernetes, StatefulSets for a ring, or Services without a ClusterIP, or even if you have some sort of managed DNS solution like Cilium, Consul, or a custom solution like what we have.

In all these use cases when Pods come and go either during deployments/failovers we don't want the rest of the ring to get rehashed.

**Comment by mattklein123** [comment]
Sure, having an option to allow the load balancer to use logical name seems fine to me.

**Comment by inf-rno** [comment]
I'll pick this up. Thanks Matt!
