### ISSUE TITLE
Backport of #9071 fix to previous releases

### ISSUE THREAD

**Issue by aserebryakov** [envoyproxy/envoy#9080]
Dependencies fix (#9071) should be back-ported to previous envoy releases, because they are still broken.

**Comment by junr03** [comment]
We currently only support one stable release at a time. The maintainers are working on creating longer term plans for N stable releases, but that is not defined yet.

**Comment by aserebryakov** [comment]
@junr03 Just to clarify, this fix appears only in 1.12.1?

**Comment by lizan** [comment]
Yes we will backport #9071 to previous release when we have next release (i.e. 1.12.2), in short term please use `--distdir` option to provide the tar package to bazel.

**Comment by aserebryakov** [comment]
@lizan, do you have any estimation when next version of envoy will be released?
Even rough estimation like week/month/year will be enough to take an appropriate decisions on our side.
