### ISSUE TITLE
build error: 404 on rules_proto downloading

### ISSUE THREAD

**Issue by sorc1** [envoyproxy/envoy#9081]
When building the last master branch (61201908c18b7), an error occurs:

`
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/f6c112fa4eb2b8f934feb938a6fce41425e41587.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`

**Comment by junr03** [comment]
Interesting, the rule should retry on the alternate [URL](https://github.com/envoyproxy/envoy/blob/61201908c18b71633e4a8393c03978a83faac4d1/bazel/repository_locations.bzl#L252), which is valid. If the original is 404ing, should it be removed @lizan?
