### ISSUE TITLE
Support multiple tracing drivers

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#909]
With the addition of Zipkin support https://github.com/lyft/envoy/pull/905 it would be nice to be able to specify multiple drivers ie. Zipkin _and_ Lightstep.

**Comment by RomanDzhabarov** [comment]
@moderation what is the motivation here? Is that just in case one of the systems down?

**Comment by moderation** [comment]
This is super low priority as the use cases are theoretical. I can imagine that different tracing backends could offer different benefits in terms of reporting, querying, functionality etc. Cost and access could be factors ie. Lightstep is a commercial service. However to really have those levers makes sense you might want to have tracing backend selection choice per listener filter which is probably adding a lot more complexity.
