### ISSUE TITLE
build: upgrade to C++17

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#9091]
We've discussed this in the community meeting in June. Now the Google C++ Style Guide is updated to C++17 too, so I guess it is about the right timing to do. Any objections? If so what is the toolchain you use can't support C++17?

**Comment by mattklein123** [comment]
@lizan just so I understand, what are the driving features we are looking to get? With abseil it seems a lot less critical to move forward. (I don't have any major objection though, just concerned about who this might hurt.)

**Comment by lizan** [comment]
@mattklein123 Nothing much critical, abseil did resolve the major part from library for sure. 

Here is my list to clear:

- std::filesystem mess in test.
- absl::string_view vs std::string_view undefined behavior: see https://github.com/abseil/abseil-cpp/issues/73, this is a blocker for upgrading, and we should minimize this.
- static inline constexpr variables, then we can kill all *Values singleton.

Others are mostly cosmetics, like nested namespace and `if constexpr`, etc.

**Comment by marcomagdy** [comment]
I'd add to that list:

1. `[[nodiscard]]` attribute.
1. structured bindings
1.  if/switch-with-initialization

1 one is great for catching bugs. 2 and 3 are quality of life improvements.

**Comment by lizan** [comment]
@marcomagdy yeah agreed. `[[nodiscard]]` is already there via `ABSL_MUST_USE_RESULT`.

**Comment by lambdai** [comment]
+1 for structured bindings!

**Comment by mattklein123** [comment]
The main blocker is likely to be Android and iOS support. @goaway and @junr03 can you look into this?

**Comment by junr03** [comment]
Yep, going to investigate. I am interested in std::filesystem for Envoy Mobile.

**Comment by junr03** [comment]
From my reading of https://developer.android.com/ndk/guides/cpp-support we have support in Android (pending knowing what is the lowest NDK version we support at Lyft cc @buildbreaker). And it looks from a wide variety of sources that the clang version that has come bundled with Xcode since 10.0 has support.

**Comment by lizan** [comment]
@junr03 specifically for std::filesystem, it is not supported until iOS 13 AFAIK

**Comment by asraa** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/12306 and https://github.com/envoyproxy/envoy/pull/11941
