### ISSUE TITLE
Document exposing grafana via envoy ingress 

### ISSUE THREAD

**Issue by Kishn0211** [envoyproxy/envoy#9092]
Could you please share any document on how to expose grafana via envoy ingress.

Regards

**Comment by junr03** [comment]
Envoy has capabilities for supporting a wide variety of stats sinks https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-statssink.

How to get those stats to grafana depends on the stats pipeline you are using.
