### ISSUE TITLE
Will envoy add RSocket support?

### ISSUE THREAD

**Issue by laosijikaichele** [envoyproxy/envoy#9095]
Does envoy consider adding RSocket support?

**Comment by mattklein123** [comment]
I haven't heard of anyone asking for this yet. Happy to have a design proposal if it makes sense as an extension.

**Comment by moderation** [comment]
The folks at Netifi who are commercializing RSocket position their solution as the anti-sidecar-proxy solution - https://www.netifi.com/solutions-servicemesh. They do have a C++ implementation - https://github.com/rsocket/rsocket-cpp

**Comment by laosijikaichele** [comment]
@moderation Yep, you are right. But, what if envoy add RSocket support, then people will get RSocket benefit in sidecar pattern(without RSocket broker), which probably will  be a kind of defense to RSocket.
