### ISSUE TITLE
Add a flag to disable extensions at startup.

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#9096]
*Title*: 

Add a flag to disable extensions at startup.

*Description*:

Many (all?) extensions can be removed from Envoy, but typical Docker images distributed by the Envoy project and getenvoy.io target a wide audience and can't be aggressive in removing extensions.

My proposal is to add a command-line flag `--disable-extensions=NAME[,NAME...]` to envoy so that the named extensions can be disabled (by nulling the pointer in the relevant factory registry) early in startup, before any configuration is parsed.

If the named extension isn't present in the envoy build, the startup check will log at warning level (i.e. it is not a fatal error).

**Comment by junr03** [comment]
Could you expand on the use case a bit? I am not sure I see what disabling at runtime buys the user, other than maybe preventing higher level users to not configure "not approved"/disabled extensions.

**Comment by jpeach** [comment]
I think there are a variety of reasons why you might not want to expose all extension all the time.

* If you are not ready to support an extension, then you might disable it, and only enable it (via configuration management tooling) when you are ready to support it.

* If you are testing, you might want to verify how your application works with envoy if a specific extension is not present (e.g. if another party brings the envoy and might compile a set of custom extensions).

* If there are security or operational issues with an extension, this provides a lightweight way to disable an extension without needing to build and deploy a whole new version.

* Many envoy users don't build their own envoy, so distributors of envoy images need to include every extension. Consumers of these images don't have any practical way to disable extensions (e.g. you can either consume the official envoy docker image or trim the set of extensions, but not both).

**Comment by junr03** [comment]
Thanks, I was mostly thinking about 3/4.

**Comment by mattklein123** [comment]
In general I'm +1 to this feature, though it should come with some type of warning as there is nothing to prevent an extension from inject code into the binary via static linkage (though obviously it would be highly discouraged in code review other than for registration).

**Comment by jpeach** [comment]
I have most of a patch for this, can you please assign to me?

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/9125

**Comment by antweiss** [comment]
I have a somewhat related question. Is there any way to know what extensions an existing compiled Envoy binary includes? A cli option? An API endpoint?

**Comment by moderation** [comment]
@antweiss if you run the binary from a command line with no options it flags it will report what extensions are in the binary

**Comment by antweiss** [comment]
Great! Thanks a lot?
