### ISSUE TITLE
Invalid Image Tag in Start Docs

### ISSUE THREAD

**Issue by ClaytonNorthey92** [envoyproxy/envoy#9120]
*Title*: *Invalid Image Tag in Start Docs*

*Description*:
In the start docs, located [here](https://www.envoyproxy.io/docs/envoy/latest/start/start#quick-start-to-run-simple-example), the image `envoyproxy/envoy-dev:cddf4acdd5fcd09cc54d829cbe3e5dfd0b36d511` is referenced, but this is not in the Docker registry
```
$ docker pull envoyproxy/envoy-dev:cddf4acdd5fcd09cc54d829cbe3e5dfd0b36d511
Error response from daemon: manifest for envoyproxy/envoy-dev:cddf4acdd5fcd09cc54d829cbe3e5dfd0b36d511 not found: manifest unknown: manifest unknown
```

*Relevant Links*
https://www.envoyproxy.io/docs/envoy/latest/start/start#quick-start-to-run-simple-example
https://hub.docker.com/r/envoyproxy/envoy/tags/

**Comment by mattklein123** [comment]
Probably a spurious failure. I see the images referenced here:
https://www.envoyproxy.io/docs/envoy/latest/start/start
https://hub.docker.com/r/envoyproxy/envoy-dev/tags?page=1

**Comment by ClaytonNorthey92** [comment]
thanks for the reply @mattklein123 , I re-looked at the start page and that image works for me, so this issue is invalid, however, I am wondering why we use a dev image in the docs? instead of the latest stable one?
