### ISSUE TITLE
Envoy in Non Docker Environment caught SIGTERM as soon as user logout

### ISSUE THREAD

**Issue by yks0000** [envoyproxy/envoy#9122]
*Title*: **Envoy in Non Docker Environment caught SIGTERM as soon as user logout**

*Description*:

I am trying to run Envoy in non docker environment to use it as front proxy for http2 for both incoming and outgoing connection and got the build for centos from [getenvoy.io](https://www.getenvoy.io/install/envoy/centos/). Though it runs perfectly, but as soon as I logout from root or ssh session timeout, Envoy caught SIGTERM and stop. I am running enovy in background i.e. 

```nohup envoy --config-path accesslog-envoy.yaml &```

logs:

```
[root@ip-10-89-84-167 ~]# logout
[2019-11-23 08:36:53.974][2835][warning][main] [external/envoy/source/server/server.cc:489] caught SIGTERM
[2019-11-23 08:36:53.974][2835][info][main] [external/envoy/source/server/server.cc:601] shutting down server instance
[2019-11-23 08:36:53.974][2835][info][main] [external/envoy/source/server/server.cc:555] main dispatch loop exited
[2019-11-23 08:36:53.976][2835][info][main] [external/envoy/source/server/server.cc:594] exiting
```

As a alternative I am running envoy in different tty

```
setsid sh -c 'exec envoy --config-path accesslog-envoy.yaml <> /dev/tty4 >&0 2>&1'
```

Am I missing something? and what is the recommended way to run envoy in non docker env in production.

**Comment by mattklein123** [comment]
Typically you would use a process manager such as systemd, runit, etc.

**Comment by yks0000** [comment]
Thank you, I have created it.

```
[root@ip-10-89-84-167 ~]# systemctl status envoy
● envoy.service - Envoy Proxy
   Loaded: loaded (/usr/lib/systemd/system/envoy.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-11-25 01:36:37 PST; 1h 22min ago
  Process: 32176 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 32180 (python)
   CGroup: /system.slice/envoy.service
           ├─32180 python /usr/local/bin/envoy-hot-restarter.py /usr/local/bin/start-envoy.sh
           └─32181 /usr/bin/envoy -c /root/accesslog-envoy.yaml --service-cluster enovy --service-node svc10_envoy --service-zone us-west-2c
```


Closing this.
