### ISSUE TITLE
grpc-json transcoder: HTTP 200 on large response failure

### ISSUE THREAD

**Issue by kveretennicov** [envoyproxy/envoy#9126]
*Title*: *Large response that fails (due to exceeding per_connection_buffer_limit_bytes) is reported as HTTP status 200 instead of 5xx*

*Description*:

See also #6004. Situation is similar: when using gRPC-JSON transcoder and JSON-encoded response exceeds per_connection_buffer_limit_bytes, this results in empty HTTP  response with status 200. Also, there is no ERROR record in the logs that would clearly indicate the failure.

Why a 200 would be returned when the request clearly failed? This is extremely confusing to any HTTP client.

**Comment by qiwzhang** [comment]
This is the problem with http1. The filter has to send the header first before transcoding the response body.   For http2, the error status is send in trailing headers.

**Comment by kveretennicov** [comment]
Thank you, @qiwzhang. So what does it mean in practice? Is there a solution for HTTP/1.1 clients?
