### ISSUE TITLE
Option for read timeout / equivalent of ngix' proxy_read_timeout

### ISSUE THREAD

**Issue by Yogu** [envoyproxy/envoy#9129]
**Issue Template**

*Title*: Option for read timeout

*Description*:

Is there an equivalent of nginx' [`proxy_read_timeout`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) setting? In contrast to envoy's [`stream timeout`](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts), this timeout is reset each time the upstream sends something over the stream.

This would be useful to configure a reasonable to timeout (a few seconds) to catch an unresponsive upstream, but still allow file downloads that could take minutes or hours.

**Comment by zuercher** [comment]
I think you want to look at [RouteAction's](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction) idle_timeout field.

**Comment by zuercher** [comment]
Sorry, that's just a route-specific override of stream_idle_timeout.

Why doesn't stream_idle_timeout provide the functionality you need?

**Comment by Yogu** [comment]
Ah I thought `stream_idle_timeout` was meant to close keep-alive connections when there are no active requests, but you're right, the docs explicitly recommend this for streaming APIs.

It looks like envoy sends [408 Request Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408) if this timeout takes effect. This works well for keep-alive connections (the server informs the client that it wants to close the connection, and the client will reconnect if it wants to send further requests). However, it does not seem to work at all if it's sent *before the response HTTP headers*. At least in chrome, the request will be **retried forever, immediately after the 408 response**. I know this behavior from kept-alive connections that are closed just when a request is sent; I assume chrome just does the same thing on 408. MDN also explicitly states that this status code is meant to be sent when the server wants to close the connection:

> A server should send the "close" Connection header field in the response, since 408 implies that the server has decided to close the connection rather than continue waiting.

Does this make sense to you? To me, it sounds like `stream_idle_timeout` should send a 504 Gateway Timeout if the timeout occurs before the headers are sent. After the headers are sent, I think 408 Request Timeout *might* be ok, but it's still a bit strange to sent this while a request is running (and I don't know if it causes any problems).

Fyi, I'm using ambassador. This is the route config it emitted for the endpoint I configured:

```
                                                    {
                                                        "match": {
                                                            "case_sensitive": true,
                                                            "prefix": "/model-manager/",
                                                            "runtime_fraction": {
                                                                "default_value": {
                                                                    "denominator": "HUNDRED",
                                                                    "numerator": 100
                                                                },
                                                                "runtime_key": "routing.traffic_shift.cluster_model_manager_80"
                                                            }
                                                        },
                                                        "request_headers_to_add": [
                                                            {
                                                                "append": true,
                                                                "header": {
                                                                    "key": "x-forwarded-prefix",
                                                                    "value": "/perf/model-manager"
                                                                }
                                                            }
                                                        ],
                                                        "request_headers_to_remove": [
                                                            "x-forwarded-prefix"
                                                        ],
                                                        "route": {
                                                            "cluster": "cluster_model_manager_80",
                                                            "idle_timeout": "1.000s",
                                                            "prefix_rewrite": "/",
                                                            "priority": null,
                                                            "timeout": "10.000s"
                                                        }
                                                    },
```

**Comment by Yogu** [comment]
Any comment on the status code? Browsers continuously retrying on timeouts seems like a great way to get DOSsed by accident.
