### ISSUE TITLE
Browser getting static files from rewritten URLs instead of matched route

### ISSUE THREAD

**Issue by RisingSun777** [envoyproxy/envoy#9138]
*Title*
Question: Browser getting static files from rewritten URLs instead of matched route

*Description*:
Currently I want Envoy to route to a backend cluster using this endpoint: <some-domain>.com/cluster1.

The virtual host config contains the following:
`
              - match:
                  prefix: "/cluster1/"
                route:
                  cluster: cluster1
                  prefix_rewrite: "/"
`

This routes browser's requests to /cluster1 as expected. However, all the static files (js, css...) from this backend is now resolved to root URL. Ex: <some-domain>.com/index.js instead of <some-domain>.com/cluster1/index.js, resulting in 404 error.

I want to ask if there is a way to configure Envoy to resolve this issue?

Many thanks.

**Comment by zuercher** [comment]
Envoy doesn't support rewriting responses.

It sounds like the responses from cluster1 contains URLs based on the path of requests sent to cluster1. Perhaps that application could use relative URLs?

**Comment by RisingSun777** [comment]
Yeah changing to using relative URLs from the application side works.

Thanks for your support.
