### ISSUE TITLE
can envoy support dubbo or not now?

### ISSUE THREAD

**Issue by CodingSinger** [envoyproxy/envoy#9142]
if yes, there is some samples for this feature?

**Comment by moderation** [comment]
- https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/dubbo_proxy_filter.html?highlight=dubbo
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/dubbo_proxy/v2alpha1/dubbo_proxy.proto.html?highlight=dubbo

**Comment by zyfjeff** [comment]
@CodingSinger Envoy currently supports dubbo filter.

**Comment by CodingSinger** [comment]
> @CodingSinger Envoy currently supports dubbo filter.
have some samples about this?

**Comment by CodingSinger** [comment]
Can i pull the image which support the dubbo filter by cmd `docker pull envoyproxy/envoy-dev:latest` ?
@zyfjeff
