### ISSUE TITLE
how to build envoy on windows

### ISSUE THREAD

**Issue by wornik** [envoyproxy/envoy#9154]
https://github.com/envoyproxy/envoy/blob/ac03b013af22f5ced0daeedb81416603962111f6/windows/.bazelrc#L1

How to build envoy on windows?  This folder does not have a description of how to use it.

**Comment by zuercher** [comment]
I think the Windows build is still a work in progress. If you want to experiment with it, I believe the necessary steps are encapsulated in in the ci/windows_ci_setup.ps1 and ci/windows_ci_steps.sh scripts.

cc @wrowe

**Comment by makefriend8** [comment]
@zuercher   I only find build_test.exe and  go_build_test.exe   and then what to do?

**Comment by wrowe** [comment]
This can be reopened. At this time there is insufficient documentation surrounding what and how the CI is building, which includes the (very minimal) envoy-windows ci/windows_build_steps.sh list. We are currently working to bring the envoy sources into a buildable state, but docs remain a critical component of declaring this phase accomplished.
