### ISSUE TITLE
HealthCheckFilter: manage state via runtime configuration.

### ISSUE THREAD

**Issue by veshij** [envoyproxy/envoy#9162]
Would it make sense to add an ability to manage global healthcheck state via runtime configuration?

Currently calling `/healthcheck/fail` admin endpoint not only fails healthchecks, but also forces connection manager to send GOAWAY/close connections.
In our case we want to fail checks prior to initiating full drain sequence to allow remote side to notice unhealthy state and stop sending traffic to the host.

**Comment by mattklein123** [comment]
I think it would be fine to allow the health check filter to be optionally configured via runtime. We could also allow different types of `/healthcheck/fail`.
