### ISSUE TITLE
Improve gRPC statistics with useful data for autoscaling (active-requests, request-time...)

### ISSUE THREAD

**Issue by juanjoku** [envoyproxy/envoy#9169]
*Title*: *Collect gRPC statistics useful for autoscaling (active-requests, requests-time...)*

*Description*:

Envoy is currently recording statistical data relating to gRPC:

https://www.envoyproxy.io/docs/envoy/v1.12.0/configuration/http/http_filters/grpc_stats_filter.html
```
<grpc service>.<grpc method>.success
<grpc service>.<grpc method>.failure
<grpc service>.<grpc method>.total
<grpc service>.<grpc method>.request_message_count
<grpc service>.<grpc method>.response_message_coun
```

But, thinking in autoscaling (like Kubernetes HPA), I miss information about 
response times, number of active requests, etc...

At least, something like this:
```
<grpc service>.<grpc method>.activeRequests
<grpc service>.<grpc method>.upstream_rq_time  (histogram)
```

**Comment by eightnoteight** [comment]
@juanjoku 

for autoscaling, can you think of any use cases to scale based on method level stats compared to the upstream level stats like `upstream_rq_active` and `upstream_rq_time` from [cluster stats](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats)

**Comment by kindermoumoute** [comment]
We have the same need here. Such statistics would be highly appreciated.

**Comment by QuentinBrosse** [comment]
Such statistics would be very appreciated for us too.
