### ISSUE TITLE
gRPC stats: Support ignoring all query parameters.

### ISSUE THREAD

**Issue by tonyboxes** [envoyproxy/envoy#9173]
*Title*: *gRPC stats: Support ignoring all query parameters.*

*Description*:
> The statistics query parameters occupy a large amount of memory and occupy the performance of Prometheus.

Prometheus:
![image](https://user-images.githubusercontent.com/3871120/69880014-dce44b00-1303-11ea-9cd9-e8f1f9aec088.png)

**Comment by lizan** [comment]
@kyessenov

**Comment by kyessenov** [comment]
This is due to how Envoy extracts the service method from the request. It preserves the query string, which seems like a bug, given that it looks like gRPC is fine with the query params.

**Comment by kyessenov** [comment]
cc @jmarantz since this got mentioned just today.
