### ISSUE TITLE
Envoy crashes when processing a TLS certificate with no SANs or a CN

### ISSUE THREAD

**Issue by erwbgy** [envoyproxy/envoy#9182]
Envoy crashes when processing a TLS certificate that does not have SubjectAltNames or a CN field in the Subject.

This looks to be intentional: https://github.com/envoyproxy/envoy/blob/v1.11.2/source/extensions/transport_sockets/tls/context_impl.cc#L838

While there is no valid use case for having a certificate with no SANs or CN it should not be possible to cause a crash by providing a bad certificate. Perhaps this could be an exception instead like when there are no certificates provided:
https://github.com/envoyproxy/envoy/blob/v1.11.2/source/extensions/transport_sockets/tls/context_impl.cc#L744
?

**Comment by jpeach** [comment]
I'm looking at this. I think the right approach is to throw, and `ServerContextImpl` already does this in some cases. There's also some refactoring needed for other release assertions that should not assert.

Please assign to me?

**Comment by jpeach** [comment]
Not stale, see related PRs.
