### ISSUE TITLE
server_fuzz_test is flaky

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#9207]
https://dev.azure.com/cncf/envoy/_build/results?buildId=21653

from slack:
> rgs 10:19 AM
has server_fuzz_test being flaky lately? got a failure here https://github.com/envoyproxy/envoy/pull/9203/checks?check_run_id=331575941
failure is interesting:
```
[2019-12-03 17:57:00.785][17][info][upstream] [source/common/upstream/cluster_manager_impl.cc:167] cm init: all clusters initialized
/opt/llvm/bin/../include/c++/v1/chrono:888:59: runtime error: signed integer overflow: 12135157018181088 * 1000 cannot be represented in type 'long long'
    #0 0x15863ea8 in std::__1::chrono::__duration_cast<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, std::__1::ratio<1000l, 1l>, false, true>::operator()(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) const /opt/llvm/bin/../include/c++/v1/chrono:888:59
    #1 0x15863c12 in std::__1::enable_if<__is_duration<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::value, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >::type std::__1::chrono::duration_cast<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, long long, std::__1::ratio<1l, 1000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) /opt/llvm/bin/../include/c++/v1/chrono:915:12
```

**Comment by lizan** [comment]
(per @rgs1) potentially due to https://github.com/envoyproxy/envoy/pull/9155? @oschaaf

**Comment by htuch** [comment]
Can we get a corpus entry to repeat this?

**Comment by lambdai** [comment]
Same [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=21685)

**Comment by lizan** [comment]
@htuch https://github.com/envoyproxy/envoy/blob/master/test/server/server_corpus/clusterfuzz-testcase-minimized-server_fuzz_test-5686444035670016

**Comment by oschaaf** [comment]
https://github.com/envoyproxy/envoy/pull/9216 reverts the offending change to buy some time to figure this out offline. I wonder if enableTimer()  should actively guard against (unreasonably) large and/or negative values being handed to it.

**Comment by mattklein123** [comment]
Going to close this out with the revert in.
