### ISSUE TITLE
circuit breaking: Change max_requests to work for both HTTP/1 and HTTP/2

### ISSUE THREAD

**Issue by tonya11en** [envoyproxy/envoy#9215]
The current way circuit breakers are used to limit outstanding requests involves using `max_requests` for HTTP/2 and `max_connections` for HTTP/1. This is unintuitive and and requires special handling for code that requires knowledge of the number of outstanding requests (such as [retry budgets](https://github.com/envoyproxy/envoy/pull/9069)).

I'd like to propose altering the way we increment outstanding requests in the per-cluster resource managers to track requests between both HTTPs. This would allow users to simply set `max_requests` circuit breaker values and be agnostic to the HTTP version.

This is particularly risky because it's a subtle change in behavior for widely used parameters. Hiding this behavior behind a feature flag would certainly be necessary, but I'll defer to maintainers/community on the best approach to making a change like this (if it's desired).

**Comment by mattklein123** [comment]
+1 we should fix this. It has been a longstanding source of confusion. We definitely need to runtime guard this and probably initially default to off. cc @alyssawilk

**Comment by mattklein123** [comment]
Also related to https://github.com/envoyproxy/envoy/issues/7403 in which we would optimally like to unify the H1 and H2 connection pool implementations as much as possible.

**Comment by oschaaf** [comment]
Drive-by comment:

This makes sense to me; a related idea after reading this:

The h2 pool implementation currently implies this, but once it supports multiple connections, perhaps a new `max_requests_per_connection` would make sense?
This could then translate into a (hypothetical) max request-pipelining depth for a semi-equivalent on  h1.
