### ISSUE TITLE
Failure to build tests due to quiche build failure

### ISSUE THREAD

**Issue by dmitri-d** [envoyproxy/envoy#9222]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: Failure to build tests due to quiche build failure

*Description*:
I'm seeing this in master, I'm using gcc 8.3.1

ERROR: /home/wb/.cache/bazel/_bazel_wb/363df6af2a92e025e191d91dc704db31/external/com_googlesource_quiche/BUILD.bazel:2743:1: C++ compilation of rule '@com_googlesource_quiche//:quic_core_session_lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 284 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.cc: In constructor 'quic::QuicCryptoStream::QuicCryptoStream(quic::QuicSession*)':
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.cc:39:52: error: use of deleted function 'quic::QuicCryptoStream::CryptoSubstream::CryptoSubstream(quic::QuicCryptoStream::CryptoSubstream&&)'
                   {this, ENCRYPTION_FORWARD_SECURE}} {
                                                    ^
In file included from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.cc:5:
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.h:158:30: note: 'quic::QuicCryptoStream::CryptoSubstream::CryptoSubstream(quic::QuicCryptoStream::CryptoSubstream&&)' is implicitly deleted because the default definition would be ill-formed:
   struct QUIC_EXPORT_PRIVATE CryptoSubstream {
                              ^~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.h:158:30: error: use of deleted function 'quic::QuicStreamSendBuffer::QuicStreamSendBuffer(quic::QuicStreamSendBuffer&&)'
In file included from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_stream.h:27,
                 from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.h:15,
                 from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_crypto_stream.cc:5:
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_stream_send_buffer.h:65:3: note: declared here
   QuicStreamSendBuffer(QuicStreamSendBuffer&& other) = delete;

**Comment by alyssawilk** [comment]
@danzh2010 @bencebeky to look at actual failures
@lizan because I'm wondering if this should have been caught by CI.  I thought we had some lingering gcc builds - have we done away since last I looked?

**Comment by bencebeky** [comment]
For what it's worth, I have been seeing the same error locally with GCC when I was working on https://github.com/envoyproxy/envoy/pull/9187, but it went away when I changed to Clang.  This is caused by https://quiche.googlesource.com/quiche/+/e4d68dd6e2022d84550eaa378d8dfddf45423a3d.

**Comment by bencebeky** [comment]
I do not know if this is a GCC bug or if the QUICHE code is non-compliant to the C++ standard.  What is Envoy's policy, does it need to be compilable with GCC?

**Comment by bencebeky** [comment]
/assign bencebeky

Since this might cause issues with other embedders, I'll fix QUICHE, then import the fix to Envoy.  I estimate that this will be done by EOD tomorrow.

**Comment by lizan** [comment]
We do run a full build on GCC in CI (without test), but we see there's several difference among toolchains, including libstdc++ version (e.g. #8872). This does actually looks similar to the #8872 issue but not very sure.
