### ISSUE TITLE
TCP HealthCheck - Broken upstreams get requests although HealthCheck is enabled

### ISSUE THREAD

**Issue by alexandru-ersenie** [envoyproxy/envoy#9223]
*Title*: *Broken upstreams are not removed from the balancing list*

*Description*:
This is pretty simple setup:  I have:

- Listener on port 9080 forwarding requests to a so called "kafka" cluster
- The kafka cluster consists of three members, out of which two are for the sake of this test down
- TCP HealthCheck is implemented on cluster level (very strict, upstreams should actually be removed very fast)

Although 60 - 80 % of all requests to this listener get routed to the healthy upstream, there are still 20-40 % of requests still being balanced to the broken members

[optional *Relevant Links*:]

**Bug Template**

*Title*: *Broken cluster members still get requests*

*Description*:

Considering that the broken members are always down, why do i not get the request always routed to the "healthy" member?

*Repro steps*:

- Define one listener balancing requests to a cluster, set a tcp proxy filter
- Define cluster with multiple members, out of which only one working (30900)
- Configure health checking
- Make a tcp request ( i use kafkacat for this - i have a kafka broker listening in the backend) in a loop
- See the results of the request:

> 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
% ERROR: Failed to acquire metadata: Local: Broker transport failure
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
% ERROR: Failed to acquire metadata: Local: Broker transport failure
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
% ERROR: Failed to acquire metadata: Local: Broker transport failure
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
% ERROR: Failed to acquire metadata: Local: Broker transport failure
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
Metadata for all topics (from broker -1: localhost:9080/bootstrap):
 1 brokers:
  broker 0 at kafka.minikube:9000 (controller)
 0 topics:
% ERROR: Failed to acquire metadata: Local: Broker transport failure

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9080
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: kafka
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
          idle_timeout: 0s
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9000
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: kafka-0
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: kafka-1
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9002
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: kafka-2
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
  clusters:
  - name: kafka
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    health_checks:
    - timeout: 1s
      interval: 1s
      unhealthy_threshold: 1
      initial_jitter: 1s
      healthy_threshold: 5
      tcp_health_check: {}
      always_log_health_check_failures: true
      event_log_path: "/dev/stdout"
    close_connections_on_host_health_failure: true
    hosts:
    - socket_address:
        address: 192.168.99.106
        port_value: 30900
    - socket_address:
        address: 192.168.99.106
        port_value: 30905
    - socket_address:
        address: 192.168.99.106
        port_value: 30906

  - name: kafka-0
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 192.168.99.106
        port_value: 30900
  - name: kafka-1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 192.168.99.106
        port_value: 30901
  - name: kafka-2
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 192.168.99.106
        port_value: 30902
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8002
*Logs*:

event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:28.180Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:28.325Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:29.183Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:29.325Z"}
[2019-12-04T17:47:29.703Z] "- - -" 0 - 75 412 4 - "-" "-" "-" "-" "192.168.99.106:30900"
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:30.184Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:30.326Z"}
[2019-12-04T17:47:30.734Z] "- - -" 0 UF,URX 0 0 0 - "-" "-" "-" "-" "192.168.99.106:30905"
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:31.188Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:31.332Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:32.193Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:32.336Z"}
[2019-12-04T17:47:32.737Z] "- - -" 0 UF,URX 0 0 0 - "-" "-" "-" "-" "192.168.99.106:30906"
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:33.195Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:33.338Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30906}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:34.200Z"}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"192.168.99.106","resolver_name":"","ipv4_compat":false,"port_value":30905}},"cluster_name":"kafka-headless","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2019-12-04T17:47:34.343Z"}
[2019-12-04T17:47:34.743Z] "- - -" 0 UF,URX 0 0 0 - "-" "-" "-" "-" "192.168.99.106:30905"

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by agasparovic-sabre** [comment]
@alexandru-ersenie Did you figure out what the issue was here? Trying to figure out whether I'm seeing something similar.

**Comment by jk5228** [comment]
I think we are running into the same issue. @alexandru-ersenie same question! 🙂 Did you figure out what was going on here?

**Comment by cbroglie** [comment]
Panic mode can explain this: https://github.com/envoyproxy/envoy/issues/12997#issuecomment-688868976
