### ISSUE TITLE
doc.: CSRF, CORS: "shadow-only node" -> "shadow-only mode"

### ISSUE THREAD

**Issue by dsbos** [envoyproxy/envoy#9228]
*Title*: CSRF, CORS doc. page says "shadow-only node" instead of "shadow-only mode"

*Description*:
On each of the pages _currently_ at https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/csrf_filter.html and https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/cors_filter.html, the text says:

   When enabled in shadow-only node, the filter will evaluate ...

but seems intended to say:

   When enabled in shadow-only mode, the filter will evaluate ...

**Comment by mattklein123** [comment]
@dsbos can you do a PR to fix the docs please?
