### ISSUE TITLE
Envoy response_flag=UT returning 200 instead of 504

### ISSUE THREAD

**Issue by yks0000** [envoyproxy/envoy#9242]
*Title*: *Envoy response_flag=UT returning 200 instead of 504*

*Description*:
We have an issue where upstream request timedout. Envoy set the right respone_flag as `UT` but response code was set to 200 instead of 504.

`[05/12/2019T16:14:53+0000 1575562493] method=POST authority=localhost:443 txId=- request=/StudentService/get alpn=HTTP/2 response_flag=UT ssl_protocol=TLSv1.3 ssl_cipher=TLS_AES_128_GCM_SHA256 status=200 status_details=upstream_response_timeout request_size=84 response_size=0 envoy_request_id=52220e61-e045-4dc7-bdc3-c8b5e77dd2ee user-agent=grpc-go/1.24.0 xFor=49.207.48.241 x-envoy-upstream-service-time=- total_time_ms=15001 upstream=127.0.0.1:7000`

Access Log format:

`"[%START_TIME(%d/%m/%YT%H:%M:%S%z %s)%] method=%REQ(:METHOD)% authority=%REQ(:AUTHORITY)% txId=%RESP(TID)% request=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% alpn=%PROTOCOL% response_flag=%RESPONSE_FLAGS% ssl_protocol=%DOWNSTREAM_TLS_VERSION% ssl_cipher=%DOWNSTREAM_TLS_CIPHER% status=%RESPONSE_CODE% status_details=%RESPONSE_CODE_DETAILS% request_size=%BYTES_RECEIVED% response_size=%BYTES_SENT% envoy_request_id=%REQ(X-REQUEST-ID)% user-agent=%REQ(USER-AGENT)% xFor=%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT% x-envoy-upstream-service-time=%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% total_time_ms=%DURATION% upstream=%UPSTREAM_HOST%\n"`

Checking on `RESPONSE_CODE_DETAILS`, it return the cause as `upstream_response_timeout`

Envoy version:

`envoy  version: 44f8c365a1f1798f0af776f6aa64279dc68f5666/1.12.1/clean-getenvoy-93e425e-envoy/RELEASE/BoringSSL`

**Comment by mattklein123** [comment]
The timeout can occur after the response headers have been written.
