### ISSUE TITLE
health checking: allow for immediate host removal

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#9246]
In K8s (or other environments with very fast topology changes), we have an issue in which Envoy may detect upstream host health failures faster than the service discovery system catches up and pushes updates. This creates a situation in which Envoy can think it has a very low healthy host count when this update has actually been planned because the upstream hosts are being drained. This can lead to panic routing, inadvertent priority spillover, etc.

The issue proposes a new capability for HTTP health checking that would allow:
- Upstream hosts to indicate they would like to be immediately removed by downstream hosts (i.e., do not stabilize)
- Downstream support for checking this data and acting on it. This would be similar to how degraded processing occurs.

Specifically I propose:
- Updating `POST /healthcheck/fail` to accept a proto specified request body with additional metadata.
- Allow this state to be known to the health check filter.
- Allow the health checker filter to set a new header if the downstream should perform immediate removal on failure.
- Modify downstream HTTP health checking to act on this new header.

cc @snowp

**Comment by theatrus** [comment]
Should /healthcheck just respond with 410 Gone - seems apt for this state instead of using a header.

**Comment by mattklein123** [comment]
> Should /healthcheck just respond with 410 Gone - seems apt for this state instead of using a header.

Sure we can consider this when implementing. The only downside here is that if Envoy is health checking a non-Envoy this might be a legitimate failure in which they don't want immediate removal.

**Comment by mattklein123** [comment]
One case here that needs more thinking (was just talking to @theatrus about this offline) is what happens if a host says to remove itself, and then an EDS update comes in and re-adds the host. With SoTW updates this is very possible, maybe even likely. We could ignore this case, but we probably need to consider some type of dead state in which we keep track of the host, but don't actually add it to any host sets. It wouldn't actually get removed into discovery tells us to.

**Comment by snowp** [comment]
Is this attempting to solve a specific case where endpoints are removed from service discovery before they have been shut down? I don’t know enough about k8s to know if that’s how it works, but if so this seems to be a reasonable way of handling this.

To track the dead hosts it might be feasible to reuse the excluded hosts mechanism I added a while back - it would allow for Envoy to retain knowledge of the hosts without considering them for load balancing (except in the case of panic).

**Comment by mattklein123** [comment]
> Is this attempting to solve a specific case where endpoints are removed from service discovery before they have been shut down? I don’t know enough about k8s to know if that’s how it works, but if so this seems to be a reasonable way of handling this.

The case here is Envoy is using active HC, the upstream starts draining, Envoy does an immediate HC fail, and suddenly we are in panic/spillover before servide discovery (K8s, etc.) actually catches up. This is not really a K8s specific problem, but mainly a problem in very highly dynamic environments.

> To track the dead hosts it might be feasible to reuse the excluded hosts mechanism I added a while back - it would allow for Envoy to retain knowledge of the hosts without considering them for load balancing (except in the case of panic).

Yes. I've thought about this more and this is how it has to work. We have to actually keep the hosts and continue to health check them, but just exclude them entirely from load balancing. This way if they somehow end up coming back and passing health checks again (like the IP gets recycled and we don't get an intermediate remove/add) it would still work.

@snowp WDYT?

**Comment by snowp** [comment]
Got it, makes sense to me. I think this feature would be helpful and not that hard to implement, we'd just need to make sure that we properly remove these hosts eventually.

**Comment by mattklein123** [comment]
Note that this can piggyback on `x-envoy-immediate-health-check-fail` without having to add a new header. I forget we already had this plumbed through.

**Comment by jyotimahapatra** [comment]
@mattklein123 I was [grep](https://github.com/envoyproxy/envoy/search?q=x-envoy-immediate-health-check-fail&unscoped_q=x-envoy-immediate-health-check-fail)'ing for `x-envoy-immediate-health-check-fail` and could not find a place in code where it's set.
Also, i performed an experiment:

```
jmahapatra@pyexample2-xxx:~$ curl 0:9901/healthcheck/fail -X POST
OK
jmahapatra@pyexample2-xxx:~$ curl 0:9901/server_info
{
...
 "state": "DRAINING",
....
xxxxx
....
}
jmahapatra@pyexample2-xxx:~$ curl -vvv -H 'Host: pyexample2' 'http://localhost:9001/healthcheck'
* Connected to localhost (127.0.0.1) port 9001 (#0)
> GET /healthcheck HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: pyexample2
>
< HTTP/1.1 200 OK
* Server envoy is not blacklisted
< server: envoy
< date: Fri, 24 Jan 2020 19:09:46 GMT
< content-type: text/html; charset=utf-8
< content-length: 2
< x-envoy-upstream-service-time: 1
< x-envoy-upstream-healthchecked-cluster: pyexample2-xxx
<
* Connection #0 to host localhost left intact
```

I supposed that in the above described sequence we would get back `x-envoy-immediate-health-check-fail`. Is that assumption correct?

**Comment by mattklein123** [comment]
Here are some implementation notes since I think @jyotimahapatra once to take a shot at implementing this:

1. Modify `HealthCheckFilter::encodeHeaders` so that `EnvoyImmediateHealthCheckFail` is set for all cases (HC and non-HC) in which the server has been health check failed.
2. Add a new health state enum value to `HEALTH_FLAG_ENUM_VALUES` called something like `EXCLUDE_FROM_LB`.
3. Modify `HealthCheckerImplBase::HealthCheckHostMonitorImpl::setUnhealthy()` (callers/callees) to take into account whether this was due to an immediate health check fail (upstream drain) case. This needs to also happen in the HC code itself to account for the change in (1) above. This should ultimately result in `HealthCheckerImplBase::ActiveHealthCheckSession::setUnhealthy` setting the `EXCLUDE_FROM_LB` flag on the host if a result of an upstream drain, and making sure that changed_state is change pending. **Important note:** The HC code must also **clear** this flag (if set) if there is an HC response that does not include the immediate health check fail header. This is to handle the immediate IP recycle case.
4. Modify `ClusterImplBase::partitionHostList` and `ClusterImplBase::partitionHostsPerLocality` so that `EXCLUDE_FROM_LB` is also a reason that a has is put in the excluded list. (Factor this logic out into a shared function.)
5. Doc updates, unit tests, and an integration test that covers all of these cases.
6. Misc changes related to the addition of the `EXCLUDE_FROM_LB` flag.

This is a complicated change so note that ^ may not be 100% accurate until verified by actually implementing. cc @snowp who is currently on vacation to check this when back.

**Comment by jyotimahapatra** [comment]
@mattklein123 Thanks for the map. I have an initial version of changes. I will put out a PR after testing it locally.

**Comment by snowp** [comment]
I don't see anything immediately wrong with the implementation strategy, but I'm sure things will come up during implementation.

**Comment by jyotimahapatra** [comment]
I'm not working on this atm and can be picked up any anyone interested.

**Comment by snowp** [comment]
@mattklein123 Looking into this I'm not quite sure how best to reconcile this behavior with a few points:
- the x-envoy-immediate-health-check fail header can be set on any kind of response, even ones that the health checker today considers successful. Should we be looking for this header at all for successful requests? Or should the presence of this header make the response a failure response?
- how should the presence of this header play with unhealthy/healthy thresholds? If we immediately flag hosts as EXCLUDE_FROM_LB once we see this header, then when unhealthy_threshold > 1 we'll have healthy hosts that we're excluding from the lb, which seems a bit odd. On the other hand, if we receive multiple failures in a row but not all of them set the x-envoy-immediate-health-check header, what should the behavior be? I had thought that x-envoy-immediate-health-check-fail would bypass the unhealthy_threshold (which would simplify things), but it doesn't seem like it currently does.

**Comment by mattklein123** [comment]
> the x-envoy-immediate-health-check fail header can be set on any kind of response, even ones that the health checker today considers successful. Should we be looking for this header at all for successful requests? Or should the presence of this header make the response a failure response?

The use of this header today is actually on normal requests, not HC requests. I don't think it changes normal requests. It's true that we don't set this today on HC requests, so, yes, I would argue this should override the response and cause immediate failure on that path also. I don't think this needs to be config guarded as it makes sense, but it's probably worth it to runtime guard to be on the safe side.

> how should the presence of this header play with unhealthy/healthy thresholds? If we immediately flag hosts as EXCLUDE_FROM_LB once we see this header, then when unhealthy_threshold > 1 we'll have healthy hosts that we're excluding from the lb, which seems a bit odd. On the other hand, if we receive multiple failures in a row but not all of them set the x-envoy-immediate-health-check header, what should the behavior be? I had thought that x-envoy-immediate-health-check-fail would bypass the unhealthy_threshold (which would simplify things), but it doesn't seem like it currently does.

My original intention (and I admit I have not thought about this in a very long time) was the a host in this immediate failure mode would be excluded, so it would not count for thresholds, panic routing, etc. very similar to the exclusion used during initial host health checking.

**Comment by mattklein123** [comment]
Since I'm likely to disappear on leave any moment, here is the current WIP of the change: https://github.com/envoyproxy/envoy/commit/eb702f2ccad1d35fb48a704d231239dfb41b8bc0. It's basically done other than docs and a couple of tests for the runtime flag. I will finish later or tomorrow morning if I have time. cc @snowp @jessicayuen
