### ISSUE TITLE
config envoy for gRPC bidirectional streaming server

### ISSUE THREAD

**Issue by danlanxiaohei** [envoyproxy/envoy#9250]
*Title*: *config envoy for gRPC bidirectional streaming server*

*Description*:

I have a gRPC bidirectional streaming server, and i use envoy as its front-proxy, then many clients request the envoy.(you can suppose the clients are  thousands of iPhone)
but, when the client's count is more than 1024,  the following  clients will not connect success, the error  is 【rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: overflow】. 

I want to know how to config envoy in this usage scenarios

[optional *Relevant Links*:] https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break

**Comment by danlanxiaohei** [comment]
@mattklein123 is this issue is same as https://github.com/envoyproxy/envoy/issues/9215?

**Comment by dio** [comment]
@danlanxiaohei can you try this: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#cluster-circuitbreakers-thresholds? Seems like you want to tweak `max_connections`/`max_requests` to be greater than 1024.

**Comment by danlanxiaohei** [comment]
@dio enlarge the  max_requests works for me ! 
but i still have doubt about this ,  is this the best way to config gRPC bidirectional streaming RPC?

**Comment by danlanxiaohei** [comment]
ok , i think i will follow https://github.com/envoyproxy/envoy/issues/7403
