### ISSUE TITLE
VHDS subscription could refer a destructed init manager

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#9254]
*Description*:

Brainstormed in my PR https://github.com/envoyproxy/envoy/pull/9209 but then I realize the issue is there before. 
https://github.com/envoyproxy/envoy/issues/7617

The background is `RdsRouteConfigSubscription` has been shared by multiple providers across listeners. 
Upon subscription construction the subscription keep a reference to the `Init::Manager` provided by the listener.
If the RDS config has VHDS field, VHDS subscription will be created and that `Init::Manager` reference will be dereferenced.
Since subscription is shared across listeners, the above `Init::Manager` might be already destructed with the initial listener.

Boom.

**Comment by stevenzzzz** [comment]
This is a similar problem as RDS in the scope of SRDS, where a new subscription might be created exceed listenerImpl life-span. I think we can fix it by depending on a noop init manager when we detect that the listener is gone. it's kinda of an addition to the #7617, we can probably solve both in one shot.

**Comment by lambdai** [comment]
Agree. Need to find another signal to indicate `init_manager` is not required.

**Comment by stevenzzzz** [comment]
/assign stevenzzzz
I will grab it

**Comment by stevenzzzz** [comment]
I believe this is fixed by #9779, in RDS onConfigUpdate a local init-manager is used instead of listener's init_manager_ in VHDS's subscription creation.

**Comment by stevenzzzz** [comment]
apparently I can't close it. :)
