### ISSUE TITLE
Should healthcheck clustername check be more strict instead of StartsWith

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/envoy#9263]
We observed that the healthcheck cluster identity does a startwith check https://github.com/envoyproxy/envoy/blob/b08af1fed4fbecb7e0b3555b022e071ed7dc2ffb/source/common/upstream/health_checker_impl.cc#L271-L271

Should it be more strict?

**Comment by mattklein123** [comment]
I don't recall the history here. AFAIK it should be an exact match and that is what all of the documentation says: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#health-check-identity.

I would vote that we fix this, but I think the fix has to be runtime guarded and then removed after the normal deprecation cycle.

**Comment by kb000** [comment]
I know we definitely rely on the prefix matching behavior at Lyft today.  The health checker's `service_name`s are set to strings like `users`, but the `x-envoy-upstream-healthchecked-cluster` header comes back `users-production-iad`

**Comment by mattklein123** [comment]
> I know we definitely rely on the prefix matching behavior at Lyft today. The health checker's service_names are set to strings like users, but the x-envoy-upstream-healthchecked-cluster header comes back users-production-iad

Well, that explains why it's implemented that way. :)

What we should do here is replace this with a `StringMatcher` so it's more clear what the intention is. We can use this issue to track that.
