### ISSUE TITLE
SubjectAlternateName protobuf message omits IP address names

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#9269]
*Title*: 

SubjectAlternateName protobuf message omits IP address names

*Description*:

The `SubjectAlternateName` protobuf introduced in #4566 omits the IP address alternate names. These should be included for completeness and consistency.

**Comment by ramaraochavali** [comment]
not stale. Will work in coming weeks

**Comment by ramaraochavali** [comment]
@dio Thanks for adding help wanted. I meant to do it - but busy with other stuff :-)
