### ISSUE TITLE
Best use case of the tap filter

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#9278]
Also, is it a good practice if I use the tap filter as a daily logging tool to record the request/response body? 
I still have some doubts about the best use case of the tap filter, and I don't know if anyone has any suggestions.

@htuch

**Comment by htuch** [comment]
I think the network TAP filter was only ever designed with developer's needs in minds (as opposed to the HTTP TAP, which does have streaming support). I would not recommend it for production use, I think we probably need to have a streaming interface for that.
