### ISSUE TITLE
Deprecate Http2ProtocolOptions.stream_error_on_invalid_http_messaging

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#9285]
*Title*: Deprecate Http2ProtocolOptions.stream_error_on_invalid_http_messaging

*Description*:
Deprecate Http2ProtocolOptions.stream_error_on_invalid_http_messaging in favor of the mandatory HttpConnectionManager option(s) to ensure that as of now an easily overlooked flag is configured appropriately for the envoy deployment.

**Comment by mk46** [comment]
This one is marked as deprecated in https://github.com/envoyproxy/envoy/blob/268b94b2b96b99b8a764cc75b2d3e214a410af71/api/envoy/config/core/v3/protocol.proto#L340

**Comment by yanavlasov** [comment]
Resolved in #11748
