### ISSUE TITLE
Add additional documentation about Azure Pipelines workflows for contributors

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#9288]
It would be useful for contributors to have some documentation like the `repokitteh` documentation in the Envoy source that gives information about the Azure Pipelines checks and potentially list out common workflows or link to Azure documentation.

(In addition, if contributors could be given access to re-run failed Azure Pipelines builds that would be quite helpful)

*Relevant Links*:
- https://github.com/envoyproxy/envoy/blob/dfe687d49574ef7eb1bf84867bf571e805a2bf97/source/docs/repokitteh.md
- https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers

cc @wrowe @achasveachas

**Comment by lizan** [comment]
We're working to get `/retest` working for both azp and circle, `/azp run` doesn't work for anyone who is not maintainer currently.

**Comment by sunjayBhatia** [comment]
@lizan ah i see, so that may supersede this request and https://github.com/envoyproxy/envoy/pull/9289

Is there anywhere we can keep track of the `repokitteh` changes?

**Comment by sunjayBhatia** [comment]
Has this been addressed in `repokitteh`/the appropriate integration? If we can help out with any issues, let us know
