### ISSUE TITLE
Is it possbile to get the envoy-static.exe?

### ISSUE THREAD

**Issue by makefriend8** [envoyproxy/envoy#9296]
Is it possible to run on windows ? I only find build_test.exe and go_build_test.exe

**Comment by dio** [comment]
cc. @wrowe

**Comment by wrowe** [comment]
The answer is twofold... The master branch at the project does not yet entirely build on windows. We are currently working on this aspect and have an open slack discussion for collaborators on envoy-windows-dev channel.

The second part is that master should be ready for peer development this month. It will not be production ready; only those capable of compiling and then debugging the sources can be of any help until it has reached the point of early community review by users. At that call, envoy-static.exe would become publicly downloadable, which won't happen until 2020.
