### ISSUE TITLE
Envoy Error 503 UC  

### ISSUE THREAD

**Issue by alex3dm** [envoyproxy/envoy#9297]
*Title*: *Envoy Error 503 UC*

*Description*:
We use Envoy version 1.10.0 as part of Istio (1.1.0) in sidecar applications.
Sometimes we get an error on the Envoy client with the UC flag. The default retry policy is set for GRPC . In theory the retry mechanism should work. But it does not.

We tried with a later version of Envoy (1.12.0) but the retry mechanism does not work. Also, with a UC error on the Envoy client, sometimes a 500 DC error appears on the Envoy server at the same time.

The  Envoy configuration and Envoy extended logs with 200 UC error
are attached.
x-request-id= 5d677699-0c95-9529-a905-2401d4ef0697  - envoy_log_203.txt

[envoy_gw1.conf.txt](https://github.com/envoyproxy/envoy/files/3946731/envoy_gw1.conf.txt)
[envoy_log_203.txt](https://github.com/envoyproxy/envoy/files/3946733/envoy_log_203.txt)
[trace_new_503_UC.json.txt](https://github.com/envoyproxy/envoy/files/3946734/trace_new_503_UC.json.txt)

**Comment by dio** [comment]
@alex3dm can you elaborate more? Seems like this issue is incomplete.

**Comment by alex3dm** [comment]
@dio done

**Comment by snowp** [comment]
I think it's because none of the reset retry policies (5xx,gateway-error,reset) are enabled. Could you try setting `reset` retry policy and see if that fixes the issue?

**Comment by alex3dm** [comment]
@snowp 

We only tried repetition policy: 5xx, gateway-errory. It doesn't work.
We didn't try reset policy because it doesn't support "istio". In our project, we use "istio-proxy" base on "envoy" . Settings for "envoy" dynamically load from "istio-pilot". Any solutions to fix it?

**Comment by snowp** [comment]
Are you able to provide a smaller reproduction of the issue? I'm afraid the config/log output is a bit much to go through

**Comment by alex3dm** [comment]
@snowp  does "envoy"  of a retry policy do the checking in the class source /common /router/ retry_state_impl.cc?

**Comment by alex3dm** [comment]
@snowp  @dio Do the retry policies "5xx", "gateway-error", "reset" duplicatе  each other?

**Comment by snowp** [comment]
They are implemented here: https://github.com/envoyproxy/envoy/blob/master/source/common/router/retry_state_impl.cc#L342

Each  policy sets a flag in a bitmap, which is then checked during various retriable events to  see if the request should be retried.
