### ISSUE TITLE
Redis cluster: not ready cluster will block server initializing 

### ISSUE THREAD

**Issue by caitong93** [envoyproxy/envoy#9299]
*Title*: *redis cluster: not ready cluster will block server initializing*

*Description*:

I use redis cluster with CDS. In server initialize phase, envoy receives clusters from config server, including several redis clusters. Some of the redis clusters cannot be connected,  and CDS initializing is blocked due to `initializePhase` for redis cluster is [Primary](
https://github.com/envoyproxy/envoy/blob/v1.12.1/source/extensions/clusters/redis/redis_cluster.h#L117).

Can we consider to make the `initializePhase`  Secondary or optional ? In mesh, we don't want sidecars unable to be ready due to a redis cluster is down.

@HenryYYang @mattklein123 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
I don't think primary vs. secondary is the issue here. I think this is a bug in which the redis cluster is not timing out correctly. @HenryYYang do we have any kind of init timeout for redis that will unblock it eventually?

**Comment by HenryYYang** [comment]
Currently the request to redis cluster will timeout, but it'll periodically and indefinitely retry to initialize the cluster.  There's no timeout for the maximum amount of time for init.  I don't think other discovery type have timeout for init neither.

Back to the original problem, I don't think declaring the sidecar ready while the cluster is not initialized is a great idea.  This would just create another set of problems when the client connect to the sidecar.  And this would make the startup ordering problem even harder to solve.
