### ISSUE TITLE
Create a mailing list just for security announcements

### ISSUE THREAD

**Issue by puskar** [envoyproxy/envoy#9304]
Our security folks would like a mailing list just for security related issues. Others were similarly interested and @mattklein123 felt this was reasonable and proper :)

**Comment by mattklein123** [comment]
@envoyproxy/security-team any thoughts on this? On one hand I feel our announce list is so low volume that a security team can sort through the emails, but this also seems like a reasonable request.

**Comment by yanavlasov** [comment]
I think it is worth while. envoy-security-announce?

**Comment by mattklein123** [comment]
> I think it is worth while. envoy-security-announce?

Yeah that's what I was thinking. I can help make this next week and we can update our procedures to make sure we send security announcements also to this list.

**Comment by uromahn** [comment]
Adding a commend to bump this up. We are going through an internal security review and our security team is pushing to get this resolved as part of our internal process.
