### ISSUE TITLE
dynamic secrets are gettting stuck at warming state

### ISSUE THREAD

**Issue by budanm** [envoyproxy/envoy#9310]
*Title*: *dynamic secrets are getting stuck at warming state*

*Description*:
Hi, we are using Envoy proxy as a reverse proxy as a Kubernetes deployment.

As part of testing, from the envoy control plane, we are passing two secret entries in a snapshot for the envoy node.

However, only one of these secrets is being referred to as part of a tls context configuration for one of the dynamic clusters. The other secret is not at all referred to in the envoy.

As part of the documentation, the envoy client is supposed to ignore any additional resources than asked for. Hence from the envoy control plane, if I pass one additional secret ( which is not referred to in the envoy), it should ignore it. But in the config_dump of the envoy proxy, I see the secrets are getting stuck at dynamic_warming 

Envoy Proxy client version : 1.12.1-alpine

**Comment by dhermes** [comment]
I've seen multiple instances of this as well in `istio` Ingress Gateway containers (version 1.5.0 of Istio).

**Comment by shashankram** [comment]
Hey @budanm, I have seen this issue as well. Was this root caused, if yes - what was the problem?
