### ISSUE TITLE
Make xDS retry backoff configurable

### ISSUE THREAD

**Issue by baojr** [envoyproxy/envoy#9332]
*Title*: *Add configuration parameters for xDS retry backoff strategy*

*Description*:
The gRPC xDS implementation uses hardcoded retry durations for re-establishing the gRPC channel. I'm planning to address the TODO to make the backoff configurable, and I'm opening an issue so that I can get feedback on the configuration options I add.

*Relevant Links*:
https://github.com/envoyproxy/envoy/blob/v1.12.1/source/common/config/grpc_stream.h#L39

**Comment by michaelbor** [comment]
@baojr @snowp is it possible to reopen this issue? Configurable retry backoff is would be very beneficial for our use case.

**Comment by baojr** [comment]
@michaelbor I'm no longer involved with this project so I unfortunately cannot help.

**Comment by michaelbor** [comment]
Thanks, @baojr. I will open a new issue then since I don't see an option to reopen this one. BTW, please let me know if you have by chance any drafts for the code you planned to add for this feature.
