### ISSUE TITLE
ci: update python3 version on envoy docker image

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#9339]
*Title*: update python3 version on envoy docker image

*Description*:
>python3 runtime version in envoy docker image  is old, that is `Python 3.5.2`.
So we can't use latest python features like `capture_output` option defined from `subprocess.run`

**Comment by htuch** [comment]
I believe this has already been fixed in https://github.com/envoyproxy/envoy-build-tools/pull/21, so closing.
