### ISSUE TITLE
gRPC status operator for file access logs

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#9352]
Right now the only way to infer the failure reason for gRPC requests in file access logs is to output `%TRAILER(grpc-status)%`, which outputs the gRPC status as a number. It would be very useful to have an operator that output the error name (e.g. `UNAVAILABLE` instead of `14`).

This would also make it easier to handle the fact that the `grpc-status` header might appear in either the headers or in the trailers: the `%GRPC_STATUS%` operator would just check either.

**Comment by Shikugawa** [comment]
@snowp Is anyone working on this? If not, I will implement.

**Comment by snowp** [comment]
Not that I'm aware, feel free to take this one.
