### ISSUE TITLE
Failure of Bazel build 

### ISSUE THREAD

**Issue by raspberry44** [envoyproxy/envoy#9363]
Hi,

First of all, I'm new to Bazel build environment. I want to contribute envoy and to do so, first I wanted to build the project using the command below in the project directory:

`bazel build //...`

However I got the error below everytime I try this:

```
ERROR: An error occurred during the fetch of repository 'com_github_gperftools_gperftools':

//bazel/foreign_cc:gperftools_build depends on @com_github_gperftools_gperftools//:all in repository 
@com_github_gperftools_gperftools which failed to fetch. no such package 
'@com_github_gperftools_gperftools//': 

ERROR: Analysis of target '//bazel/foreign_cc:gperftools_build' failed; build aborted: Analysis failed
```

I have also tried other methods available on the internet concerning the convertion from Bazel to Cmake but no luck. Bazel plugin for Clion also did not work.

Also I wonder if it's possible to include envoy package from a remote repository using cmake in my project. 

I have handled everything on the implementation side and ready to open PR but this problem made me stuck here and could not open PR. 

Thanks in advance

**Comment by hongzimao** [comment]
Which `bazel version` are you using? I also hit this error with bazel 2.0.0. Same envoy code built with bazel 0.28.1

**Comment by hongzimao** [comment]
Actually, although the trigger occurs at the same repo, my error is different:`autoreconf: not found` and I fixed it by
```
sudo apt-get install dh-autoreconf
```
