### ISSUE TITLE
Confusion over TCP draining

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#9369]
I'm working on improving graceful shutdown/lameduck mode. @mattklein123's comments [here](https://github.com/envoyproxy/envoy/issues/7841#issuecomment-518856436) and [here](https://github.com/envoyproxy/envoy/issues/1990#issuecomment-341489750) imply `/healthcheck/fail` initiates draining, but I'm unclear as to what's outdated here. From my own checking I don't see anyone calling server.cc:drainListeners, and now I'm seeing [someone added](https://github.com/envoyproxy/envoy/pull/8415) a `/drain_listeners` endpoint.

**Comment by mattklein123** [comment]
@auni53 can you clarify exactly what behavior you are after and we can help clarify? There have been many requests/changes in this area of the years and I'm unclear what behavior you are looking for.

**Comment by auni53** [comment]
Hi Matt, thanks for taking a look at this. Here's what I'm looking to have happen on Envoy shut down:

- stop accepting new TCP connections (seems to work via calling /drain_listeners)
- terminate connections on request complete
- terminate idle connections that are in the header phase
- send HTTP2/GOAWAY to all sessions

Especially for idle connections work, this will probably require a more thorough design exploration/doc.

**Comment by mattklein123** [comment]
> stop accepting new TCP connections (seems to work via calling /drain_listeners)
terminate connections on request complete

I think these are both already done?

> terminate idle connections that are in the header phase

What do you mean by this?

> send HTTP2/GOAWAY to all sessions

So the idea here is that you want to basically force shutdown all connections without waiting for the drain timeout? Can you just set the drain timeout to be really short?

I think I'm still not completely clear on which functionality is missing, so maybe you can propose some changes and we can talk through it?

**Comment by auni53** [comment]
Writing up a design doc to explain this better, will post a new issue.

**Comment by ryanmcnamara** [comment]
Hi @auni53, interested in the new issue
