### ISSUE TITLE
filter chain matching for a Thrift cluster using HTTP health checks

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#9371]
For some of our thrift clusters, we'd like to use HTTP health checks over the same port used for thrift/data connections.

We could do this using `FilterChainMatch`'s `application_protocols` field for matching. But for this to work, we'd need to either 1) be able to configure the ALPN on health checks or 2) be able to set ALPN from thrift proxy (doing this via `CommonTlsContext` is no good because it'd be used for both HCs and data requests).

I think I prefer 1). Does it sound reasonable to add an `alpn_protocol` field to the `HealthCheck` message? If so, I'll send in a PR. 

cc: @zuercher @mattklein123 @fishcakez
cc: @htuch for API ergonomics.

**Comment by rgs1** [comment]
Note that for 1), I think that the implementation should be pretty clean since we just need to construct a `TransportSocketOptions` object with the given `alpn_protocol` configured for HCs and pass that along to `createConnection()` from `createHealthCheckConnection()`:

https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L287

So unless someone objects, I'll go down that route. Thanks!

**Comment by htuch** [comment]
@rgs1 I agree that (1) sounds more general and cleaner. I'm wondering if there is any value in thinking about other kinds of TLS override in `HealthCheck` and making use of the `TransportSocketMatch` feature. CC @PiotrSikora

**Comment by rgs1** [comment]
Something like #9378?
