### ISSUE TITLE
A new type of resource monitor to shrink memory

### ISSUE THREAD

**Issue by zyfjeff** [envoyproxy/envoy#9381]
*Title*: *A new type of resource monitor to shrink memory*

*Description*:

Because Envoy uses `TCMalloc`, it will take up a lot of memory(reserved by TCMalloc.), but actually Envoy uses not so much memory, so I need to periodically shrink the memory according to the ratio of the two. The current idea is to implement it through the OverloadManager, but the currently provided fixed_heap resource monitor does not meet the needs. I hope to add an allocated_heap type, which can shrink by the ratio of the two.

**Comment by zyfjeff** [comment]
@eziskind Can you give me some advice?

**Comment by eziskind** [comment]
@zyfjeff The heap shrinker class can be configured with any resource monitor, so if you add a new one you could configure the overload manager with it like this:

actions:
     - name: "envoy.overload_actions.shrink_heap"
       triggers:
         - name: "envoy.resource_monitors.allocated_heap"
           threshold:
             value: 0.95

BTW, what do you mean by "shrink by the ratio of the two"? And why does the fixed_heap resource monitor not meet your needs? What will the allocated_heap resource monitor do differently?

**Comment by zyfjeff** [comment]
@eziskind At present, fixed_heap resource monitor can only set a fixed memory size. When Envoy's memory reaches this value, OverloadAction will be triggered, but the fixed memory size of this configuration is difficult to determine. Different Envoys consume different memory, such as some Use 1g memory, and some use 4g memory, it is difficult to determine a fixed memory size. I hope that when the ratio of both heap_size and current_allocated_bytes reaches a fixed value or differs by a fixed size, memory shrink is triggered.

**Comment by eziskind** [comment]
@zyfjeff I think you might be misunderstanding the fixed_heap resource monitor. The only thing "fixed" about it is the configured maximum size of the heap. It then computes the ratio of how much of the heap is allocated, ie current_allocated_bytes / maximum_heap_bytes. The fixed_heap resource monitor will trigger overload actions based on this ratio of how much of the heap is allocated, not whether Envoy memory reaches a particular absolute value.

**Comment by zyfjeff** [comment]
@eziskind Thank you, I understand, I just need to expand on the basis of fixed_heap.

**Comment by Lynskylate** [comment]
The [pr](https://github.com/envoyproxy/envoy/pull/5945/files) have been implementing the shrink of memory.
This configuration may help
```yaml
  - name: "envoy.overload_actions.shrink_heap"
    triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.50
```

**Comment by zyfjeff** [comment]
@Lynskylate Thanks,  current fixed_heap can't meet my need

> I understand that fixed_heap has not been able to meet my needs at the moment. I want to configure a difference such as 200M. When heap_size
>  -current_allocated_bytes is greater than 200M to trigger memory reclamation or to trigger memory reclamation when the current_allocated_bytes / heap_size ratio is 20%. I want to configure a difference or ratio instead of a maximum_heap_bytes because I cannot give a maximum value. The memory consumed by Envoy is different at different scales.

**Comment by zyfjeff** [comment]
@eziskind Did I make my needs clear? Can you give me some advice?

**Comment by eziskind** [comment]
@zyfjeff I'm not sure I understand you. What do you mean by "heap size" (as opposed to "current allocated bytes")? Is "heap size" the maximum possible size of the heap? Where would you get that number from?

**Comment by zyfjeff** [comment]
`heap_size` and `current_allocated_bytes` are obtained through the tcmalloc api.

```
generic.current_allocated_bytes | Number of bytes used by the application. This will not typically match the memory use reported by the OS, because it does not include TCMalloc overhead or memory fragmentation.

generic.heap_size | Bytes of system memory reserved by TCMalloc.
```

**Comment by eziskind** [comment]
@zyfjeff  Seems fine to me to add a new resource monitor to do this. It will be simplest to go with the ratio approach since the overload manager currently only supports triggering actions based on a percent-based threshold (though we could extend that in the future).

**Comment by zyfjeff** [comment]
@eziskind  Thanks a lot, I will take the time to implement this feature recently, and help review it at that time
