### ISSUE TITLE
Multiple circuit breakers emit the same stat

### ISSUE THREAD

**Issue by jmuia** [envoyproxy/envoy#9392]
*Title*: *Multiple circuit breakers emit the same stat*

*Description*:
It appears that for the HTTP/2 connection pool, the `cluster.<name>.upstream_rq_pending_overflow` stat is emitted when two different circuit breakers are hit: `max_requests` [0] and `max_pending_requests` [1].

This has the potential to be confusing, particularly if the the thresholds are configured to be different.

I believe this was introduced in https://github.com/envoyproxy/envoy/pull/4917

[0] https://github.com/envoyproxy/envoy/blob/2fe5b8a/source/common/http/http2/conn_pool.cc#L92
[1] https://github.com/envoyproxy/envoy/blob/2fe5b8a/source/common/http/http2/conn_pool.cc#L132

**Comment by mattklein123** [comment]
This is a duplicate of https://github.com/envoyproxy/envoy/issues/9215 or very similar. I agree this is extremely confusing and something I would like to fix. cc @tonya11en. Can we potentially merge this into https://github.com/envoyproxy/envoy/issues/9215 if that issue does not cover this also?

**Comment by jmuia** [comment]
I think it's good to merge into #9215.

The only requirement here is that there needs to be a separate stat for requests overflow and for pending requests overflow.  Since the HTTP/1 connection pool already has this, I suspect when the work in #9125 is done the HTTP/2 connection pool will also have it.

Thanks!
