### ISSUE TITLE
Clarify the ordering interaction between fragments of a scoped route and scope key builder

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#9414]
In the docs it says:

> Specifies a key which is matched against the output of the scope_key_builder specified in the HttpConnectionManager. 
> The matching is done per HTTP request and **is dependent on the order of the fragments contained in the Key**.
> https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/srds.proto#scopedrouteconfiguration-key

What needs to be clarified:

- How does the ordering work if the scoped route has a different number of fragments than the scope key builder?

I am guessing that they both need to have the same number of fragments?

**Comment by mattklein123** [comment]
@AndresGuedez @stevenzzzz

**Comment by stevenzzzz** [comment]
sorry for the late response, yes, the number of fragments has to be equal, noteworthy a fragment may not necessarily be a string, though for now a scope key only has string components.
