### ISSUE TITLE
any reason on "no healthy host for HTTP connection pool"

### ISSUE THREAD

**Issue by mailzyok** [envoyproxy/envoy#9417]
Hello,

We have seen many logs like "no healthy host for HTTP connection pool". Envoy failed to establish gRPC to peer side. Could someone shed some light on it?

Thanks a lot!

**Comment by zyfjeff** [comment]
"no healthy" is generally because the health check is configured and the upstream machine's health status is unhealth, so when there is a request, there is no way to find a healthy host.

**Comment by mailzyok** [comment]
@zyfjeff  Thanks for you comment.

Here is additional log which indicated the gRPC cannot be established. It was a response from upstream. It is strange the status code is 200. 
I am still not clear on what the reason for unhealth, because the upstream service is up and running in K8S. Is there any other log i can check?

> [2019-12-20 02:39:18.786][18][debug][http] [external/envoy/source/common/http/async_client_impl.cc:94] async http request response headers (end_stream=true):
> ':status', '200'
> 'content-type', 'application/grpc'
> 'grpc-status', '14'
> 'grpc-message', 'no healthy upstream'
> 

Thanks.

**Comment by zyfjeff** [comment]
@mailzyok can you upload the complete log and config_dump files?

**Comment by mailzyok** [comment]
@zyfjeff Thanks. I cannot upload complete log here, could you let me know which part you want to see for config_dump, i will copy it here.

Here is the log for complete log when the problem happens

> [2019-12-20 02:39:18.784][18][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:74] cm init: adding: cluster=xds-grpc primary=1 secondary=0
> [2019-12-20 02:39:18.784][18][debug][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:42] Establishing new gRPC bidi stream for rpc StreamAggregatedResources(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);
> 
> [2019-12-20 02:39:18.784][18][debug][router] [external/envoy/source/common/router/router.cc:332] [C0][S5272412103284310368] cluster 'xds-grpc' match for URL '/envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources'
> [2019-12-20 02:39:18.784][18][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:1124] no healthy host for HTTP connection pool
> [2019-12-20 02:39:18.786][18][debug][http] [external/envoy/source/common/http/async_client_impl.cc:94] async http request response headers (end_stream=true):
> ':status', '200'
> 'content-type', 'application/grpc'
> 'grpc-status', '14'
> 'grpc-message', 'no healthy upstream'
> 
> [2019-12-20 02:39:18.786][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, no healthy upstream
> [2019-12-20 02:39:18.786][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:49] Unable to establish new stream
> 

Here is the cluster info in config_dump

>      "clusters": [
>       {
>        "name": "prometheus_stats",
>        "type": "STATIC",
>        "connect_timeout": "0.250s",
>        "hosts": [
>         {
>          "socket_address": {
>           "address": "::1",
>           "port_value": 15000
>          }
>         }
>        ]
>       },
>       {
>        "name": "xds-grpc",
>        "type": "STRICT_DNS",
>        "connect_timeout": "10s",
>        "hosts": [
>         {
>          "socket_address": {
>           "address": "istio-pilot",
>           "port_value": 15010
>          }
>         }
>        ],
>        "circuit_breakers": {
>         "thresholds": [
>          {
>           "max_connections": 100000,
>           "max_pending_requests": 100000,
>           "max_requests": 100000
>          },
>          {
>           "priority": "HIGH",
>           "max_connections": 100000,
>           "max_pending_requests": 100000,
>           "max_requests": 100000
>          }
>         ]
>        },
>        "http2_protocol_options": {},
>        "dns_refresh_rate": "300s",
>        "upstream_connection_options": {
>         "tcp_keepalive": {
>          "keepalive_time": 300
>         }
>        }
>       }
>      ]
>

**Comment by zyfjeff** [comment]
@mailzyok 
According to your logs, it should be that you cannot connect to the` istio-pilot` to cause " no health upstream"

**Comment by mailzyok** [comment]
@zyfjeff  Thanks a lot, seems DNS resolution problem, see logs below:

When envoy starting resolution for istio-pilot, it takes 150s no response, i think it is a timeout, but i didn't find the default timeout values,

Then after 300s, envoy start a new resolution, i think 300s is configured as dns_refresh_rate in static cluster configuration.

I will ask the admin to check the issue of DNS resolution. Thanks again and i would take this opportunity to wish you a Merry Xmas and Happy new Year.

> [2019-12-20 08:32:22.245][20][trace][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:88] starting async DNS resolution for istio-pilot
> [2019-12-20 08:34:52.249][20][trace][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:95] async DNS resolution complete for istio-pilot 
> [2019-12-20 08:39:52.252][20][trace][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:88] starting async DNS resolution for istio-pilot
> [2019-12-20 08:39:52.253][20][trace][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:95] async DNS resolution complete for istio-pilot
> [2019-12-20 08:39:52.253][20][debug][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:117] DNS hosts have changed for istio-pilot

**Comment by mailzyok** [comment]
Thank you all for the support. The trace log is useful, we figured out the timeout values finally.
