### ISSUE TITLE
Envoy serves new and old config for a period of time

### ISSUE THREAD

**Issue by aeb-sia** [envoyproxy/envoy#9420]
We are using ambassador to configure routes in kubernetes. We observed seemingly random 404 responses and uppon closer investigation found out that they only occur when we modify a route.
If we for instance add a new route, for a period of time we sometimes get 404s and sometimes the request succeeds.

This can be observed on every route addition/deletion. It looks like the new config slowly takes over. Up to 30 seconds after the new routes have been added we are pretty much at 50% to get the old config. After 30 seconds pass it's much lower.

We are pretty sure it's not ambassadors fault, cause the correct requests are logged and the envoy config is correctly updated with no reference to the old configuration.

We tried to manually SIGHUP envoy after the configuration has been updated but that didn't change anything.

We also tried to update the routes multiple times (from `/first` to `/second` to `/third`) hoping that another update might render the old config obsolete, but that didn't work either. We could still access `/first` for a period of about 30 seconds.

I hope that is enough information to replicate. If not I guess I can provide our generated envoy config.

We tested that using ambassador 0.80.0 and 0.86.0.

**Comment by mattklein123** [comment]
I would recommend raising this issue to ambassador for help debugging. I think this might be due to listener drain timeout if ambassador is not using RDS, but I'm not sure.
