### ISSUE TITLE
skip empty strings when split disabled_extensions option. 

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#9421]
**Bug Template**

*Title*: When parsing disabled_extensions option, we should skip empty strings when strsplit the commandline option string. 

*Description*: When parsing disabled_extensions option, we should skip empty strings when strsplit the commandline option string. Otherwise we end up with a warning msg when MainCommon tries to parse the disabled_extensions, as there is an empty string in the list by default.

**Comment by mattklein123** [comment]
Dup https://github.com/envoyproxy/envoy/issues/9377
