### ISSUE TITLE
Ability to force restart of envoy upon certain trigger?

### ISSUE THREAD

**Issue by justincely** [envoyproxy/envoy#9423]
*Title*: *Force server restart upon triggered condition?*

*Description*:
When setting up Envoy with a central control plane, the static cluster that serves up the xDS interface is vital to the functioning of the server.  If that cluster isn't up/reachable when Envoy is trying to connect, it goes through it's retries and eventually gets into a state where it's never gonna get updates, but also doesn't shut down.

This makes sense from the perspective that the static cluster for xDS is just another cluster, and envoy should stay up.  But now the proxy is in an unrecoverable state and since the server didn't shut down the orchestration tool in use (k8s for instance) won't restart the pod automatically.  

Is there anything like this in Envoy, or do I need to relegate this to readiness probes in the orchestration tool?  I didn't see anything that could force a shutdown in the docs, but wanted to ask here before I gave up.

**Comment by mattklein123** [comment]
> Is there anything like this in Envoy, or do I need to relegate this to readiness probes in the orchestration tool? I didn't see anything that could force a shutdown in the docs, but wanted to ask here before I gave up.

Correct, there is nothing like this today and we suggest defining readiness probes that do what you want. We have quite a few different admin endpoints that help with writing such probes.

**Comment by justincely** [comment]
thanks @mattklein123, i suspected as much, but appreciate the quick reply.  Happy to have this closed, as my question is answered.
