### ISSUE TITLE
SCTP ( Stream Control Transmission Protocol ) traffic support in envoy

### ISSUE THREAD

**Issue by y-gupta** [envoyproxy/envoy#9430]
SCTP ( Stream Control Transmission Protocol ) traffic support in envoy

Use-case:
In Telecommunication industry, Evolved Packet Core (EPC) has a number of entities which use SCTP protocol to communicate with each other.
This will make envoy a viable solution for many telecom vendors.

Is it possible to include SCTP in the development roadmap?

**Comment by y-gupta** [comment]
Does anyone have any opinions on if this is under the scope of what envoy wants to do or not?

**Comment by mattklein123** [comment]
@y-gupta As long as it's fully implemented in an extension(s) I don't think there will be a strong feeling one way or the other, but I doubt you are going to get much feedback on this from the community so you will likely have to do a proposal.
