### ISSUE TITLE
Feature Request: Support Apache RocketMQ's protocol

### ISSUE THREAD

**Issue by aaron-ai** [envoyproxy/envoy#9431]
*Support Apache RocketMQ's protocol*

*Apache RocketMQ intend to make contributions to Envoy by supporting RocketMQ's protocol, and the code is almost ready, open this issue to track the progress.*

A design document is available at the link below: 
> https://docs.google.com/document/d/1_k8HyFAytwjZ-LGGF5O19TM4A66DCxE1sCexvp6RlbM/edit?usp=sharing

issue or pr related: #8036 #8984

**Comment by vongosling** [comment]
https://github.com/envoyproxy/envoy/issues/8036, related issues from the community.
