### ISSUE TITLE
Envoy (istio-proxy) memory keeps growing (HTTP/2 gRPC bidi stream)

### ISSUE THREAD

**Issue by heimweh** [envoyproxy/envoy#9436]
*Description*:

We have a service deployed in our cluster with an istio-proxy sidecar (running envoy).
We're currently seeing an issue where Envoy's memory usage keeps increasing, 
up to the point where it gets OOMKilled (2GB limit).

We've tried doubling the limits for the sidecar,
but it's still growing and didn't settle somewhere.

<img width="1370" alt="Screen Shot 2019-12-20 at 14 03 49" src="https://user-images.githubusercontent.com/13624191/71280369-41bb2000-235b-11ea-80dc-f5f61a6a9c34.png">

We have a bunch of profile files if that's of any interest, but here's a top.

```bash
File: envoy
Type: inuse_space
Showing nodes accounting for 7444519.55kB, 98.91% of 7526712.10kB total
Dropped 210 nodes (cum <= 37633.56kB)
      flat  flat%   sum%        cum   cum%
7207847.51kB 95.76% 95.76% 7526530.58kB   100%  [envoy]
145685.58kB  1.94% 97.70% 153317.23kB  2.04%  _tr_flush_block
43514.89kB  0.58% 98.28% 43514.89kB  0.58%  build_tree
14665.48kB  0.19% 98.47% 52842.67kB   0.7%  opencensus::trace::exporter::SpanExporterImpl::RunWorkerLoop
 8494.69kB  0.11% 98.58% 222554.28kB  2.96%  deflate
 5522.39kB 0.073% 98.66% 38396.39kB  0.51%  Envoy::Extensions::ResourceMonitors::InjectedResourceMonitor::InjectedResourceMonitor::InjectedResourceMonitor
 4618.61kB 0.061% 98.72% 182262.43kB  2.42%  opencensus::trace::exporter::LocalSpanStoreImpl::AddSpan
 4459.19kB 0.059% 98.78% 192979.41kB  2.56%  std::deque::_M_destroy_data_aux
 3587.30kB 0.048% 98.83% 103057.18kB  1.37%  nghttp2_session_mem_send_internal
 1921.69kB 0.026% 98.85% 67639.67kB   0.9%  ares_query
 1580.05kB 0.021% 98.87% 71611.56kB  0.95%  opencensus::proto::trace::v1::Span::InternalSerializeWithCachedSizesToArray
 1345.69kB 0.018% 98.89% 53863.83kB  0.72%  Envoy::Init::WatcherHandleImpl::ready
  490.73kB 0.0065% 98.90% 39085.06kB  0.52%  opencensus::proto::trace::v1::Span_TimeEvent::MergePartialFromCodedStream
  384.12kB 0.0051% 98.90% 79046.68kB  1.05%  google::devtools::cloudtrace::v2::BatchWriteSpansRequest::SerializeWithCachedSizes
  235.66kB 0.0031% 98.91% 182515.98kB  2.42%  opencensus::trace::exporter::SpanData::~SpanData
   96.89kB 0.0013% 98.91% 171327.59kB  2.28%  Envoy::Server::RunHelper::RunHelper
   39.62kB 0.00053% 98.91% 40392.59kB  0.54%  Envoy::Grpc::AsyncRequestImpl::AsyncRequestImpl
   28.97kB 0.00038% 98.91% 159026.39kB  2.11%  Envoy::Registry::FactoryRegistry::allFactoryNames[abi:cxx11]
    0.48kB 6.4e-06% 98.91% 39383.96kB  0.52%  Envoy::InjectableSingleton::get
         0     0% 98.91% 53939.21kB  0.72%  Envoy::Grpc::ContextImpl::chargeStat
         0     0% 98.91% 151531.71kB  2.01%  [libc-2.27.so]
         0     0% 98.91% 71315.13kB  0.95%  google::devtools::cloudtrace::v2::BatchWriteSpansRequest::ByteSizeLong
         0     0% 98.91% 79046.68kB  1.05%  google::devtools::cloudtrace::v2::BatchWriteSpansRequest::MergePartialFromCodedStream
         0     0% 98.91% 194734.63kB  2.59%  google::protobuf::Arena::CreateMaybeMessage
         0     0% 98.91% 199407.34kB  2.65%  longest_match
         0     0% 98.91% 199407.34kB  2.65%  nghttp2_rcbuf_new
         0     0% 98.91% 64988.10kB  0.86%  nghttp2_session_adjust_idle_stream
         0     0% 98.91% 51431.16kB  0.68%  nghttp2_session_on_settings_received
         0     0% 98.91% 238116.45kB  3.16%  nghttp2_stream_dep_remove_subtree
         0     0% 98.91% 67639.67kB   0.9%  opencensus::proto::agent::common::v1::Node::Node
         0     0% 98.91% 89392.74kB  1.19%  opencensus::proto::agent::common::v1::Node::SerializeWithCachedSizes
         0     0% 98.91% 7118209.43kB 94.57%  start_thread
         0     0% 98.91% 192979.41kB  2.56%  std::_Deque_base::~_Deque_base
```

```json
GET /memory
{
 "allocated": "896984896",
 "heap_size": "980434944",
 "pageheap_unmapped": "0",
 "pageheap_free": "15474688",
 "total_thread_cache": "17797264"
}

GET /server_info
{
 "version": "a7b2578494d79fe098f0e99282e0236946562fa0/1.12.0/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 2,
  "config_path": "/etc/istio/proxy/envoy-rev0.json",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "warning",
  "component_log_level": "misc:error",
  "log_format": "[Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "service_cluster": "***",
  "service_node": "***",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "file_flush_interval": "10s",
  "drain_time": "45s",
  "parent_shutdown_time": "60s"
 },
 "uptime_current_epoch": "3252s",
 "uptime_all_epochs": "3252s"
}
```

Envoy stats: [stats.txt](https://github.com/envoyproxy/envoy/files/3989569/stats.txt)
Envoy configuration: [config.txt](https://github.com/envoyproxy/envoy/files/3989567/config.txt)

Any idea why this is happening?

Happy to share any other configuration/stats that I forgot to add here.

Thanks in advance! :pray:

**Comment by mattklein123** [comment]
cc @lizan @dio to take a look. Typically in the past this has been an issue with retry policies on streaming requests but not sure.

**Comment by heimweh** [comment]
Thanks @mattklein123, we tried disabling retries and the `RetryPolicy` is now gone from the configuration (for this service) but we're still seeing the increase in memory usage. 
Is there anything else we can try, to debug this further?

Happy to share the Envoy heap profiles we performed, if that can help track this down 🙂 

Thanks in advance! :pray:

**Comment by lizan** [comment]
Just double check, is this only happening in one of your multiple services? Is there anything the service different from others? Can you share the config/stats after you disabled retry policy?

**Comment by heimweh** [comment]
The memory usage seems stable on all other services actually (other services in the same namespace is using ~ 300mb). The only thing that is different with this service is that it's serving a bidirectional stream.

The config is huge since other services are there but happy to share the config for this service in particular if that helps? 🙂

For some reason, we have two identical virtual hosts defined as inbounds, which is quite confusing 🤔 

[inbound.txt](https://github.com/envoyproxy/envoy/files/4046317/inbound.txt)
[outbound.txt](https://github.com/envoyproxy/envoy/files/4046318/outbound.txt)

**Comment by lizan** [comment]
@heimweh what's the traffic pattern of this service? Is the stream is long lived or not? Do you have some estimate how the memory is correlated to? e.g. increase with bytes or number of connections.

**Comment by mattklein123** [comment]
I took a look at this profile and it's very hard for me to make sense of it. Is it possible that the bidi stream is getting compressed by the zlib filter? I'm wondering if there is a buffering happening there of compression data that needs to get flushed somehow?

**Comment by amir-hadi** [comment]
@mattklein123 How can we validate if this is the case?

**Comment by mattklein123** [comment]
> @mattklein123 How can we validate if this is the case?

Look at the config/stats/etc. and do some debugging?

**Comment by heimweh** [comment]
We managed to track down and mitigate the memory issues by disabling retries on all related services in the mesh. Now we're seeing frequent resets: RST_STREAM(NO_ERROR) and disconnects, not sure if it's related though.

Thank you so much for the help on this issue and the quick replies @mattklein123 @lizan :pray:

**Comment by heimweh** [comment]
I'll go ahead and close this issue for now, and will re-open if we discover anything new.
