### ISSUE TITLE
Quiche fails to build under gcc

### ISSUE THREAD

**Issue by dmitri-d** [envoyproxy/envoy#9437]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: Latest quiche fails to build on gcc

*Description*:
Quiche in master branch fails to build under gcc with messages:
```
azel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_connection.cc: In member function 'virtual bool quic::QuicConnection::OnPacketHeader(const quic::QuicPacketHeader&)':
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_connection.cc:879:18: error: implicitly-declared 'quic::QuicPacketHeader& quic::QuicPacketHeader::operator=(const quic::QuicPacketHeader&)' is deprecated [-Werror=deprecated-copy]
  879 |   last_header_ = header;
      |                  ^~~~~~
In file included from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/crypto/quic_decrypter.h:15,
                 from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_connection.h:27,
                 from bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_connection.cc:5:
bazel-out/k8-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_packets.h:121:3: note: because 'quic::QuicPacketHeader' has user-provided 'quic::QuicPacketHeader::QuicPacketHeader(const quic::QuicPacketHeader&)'
  121 |   QuicPacketHeader(const QuicPacketHeader& other);
      |   ^~~~~~~~~~~~~~~~
``` 
gcc version ```gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by danzh2010** [comment]
This hasn't been changed in QUICHE recently. How come we didn't catch it in GCC workflow earlier?

**Comment by dmitri-d** [comment]
> This hasn't been changed in QUICHE recently. How come we didn't catch it in GCC workflow earlier?

Not sure, it seems that quiche dependency gets built for //test/... target, but not for //source/exe:envoy-static, at least under gcc.

**Comment by dmitri-d** [comment]
I forgot to mention in the original report that the failure occurs when the tests are being built.
