### ISSUE TITLE
udp: UdpListenerImpl use recvmmsg

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#9440]
Utility::readPacketsFromSocket() use recvmsg to read UDP packets. We can definitely change it to use recvmmsg instead so fewer system calls will be made. And right now it reads till the queue is empty. As we want to limit the number of system calls for each event loop, we can make this function return a bool to indicate the caller if it finishes reading from the socket or not.

**Comment by cstrahan** [comment]
I'm working on this issue at the moment -- let me know if I missed anyone else working on this, or if there's a reason to hold off.

**Comment by danzh2010** [comment]
Thanks for taking this issue! Currently no one is working this. I think this will be similar to [QUICHE's](https://source.chromium.org/chromium/chromium/src/+/master:net/third_party/quiche/src/quic/core/quic_packet_reader.cc;drc=7329ada29a5820c4186ee567cbb505df77f179b2;bpv=1;bpt=1;l=77?originalUrl=https:%2F%2Fcs.chromium.org%2F) udp reading logic, which might be helpful.

**Comment by danzh2010** [comment]
Woops, sorry, I totally forgot @cstrahan has already started this work. How far did @cstrahan go?
