### ISSUE TITLE
Feature Request: EGDS support

### ISSUE THREAD

**Issue by gengleilei** [envoyproxy/envoy#9455]
*Title*: *EGDS support*

*Description*:
The current method of updating endpoints in a cluster through EDS is fine when the cluster size is relatively small, but when the cluster size is huge, suppose we have a 10000+ endpoints, and even a small amount of endpoints get changed it causes a full EDS push. Eventually this leads to a performance issue on Envoy and Pilot.

To fix this issue, Pilot ([#19287](https://github.com/istio/istio/issues/19287)) and the Envoy (#8400) community have initiated discussions and proposed to introduced into EGDS (Endpoint Group Discovery Service) protocol.

We are very happy to participate in the development of EGDS, a draft design document is available at below link. https://docs.google.com/document/d/1FFcK4eCndr0w2zt-5FLYd8hvVRL99zwJO13it6ng3lk/edit?usp=sharing

Thanks for your review and comments.

[optional *Relevant Links*:]
The design file for EGDS in Pilot is [here](https://docs.google.com/document/d/1I5B385RMV4m5DohowKdRIdY5s6Xn97_1VdyjjqyLwlQ/edit#heading=h.wbjwxhz7tb9e).

**Comment by mattklein123** [comment]
Per discussion closing in favor of https://github.com/envoyproxy/envoy/issues/10373
