### ISSUE TITLE
Differentiate a Filter's "name" and a "type".

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#9466]
Currently Filter's have a "name" which is actually more of a type.  Filters need a unique identifier (which is more often called a "name" or "id") different from the "type".

How do you want to proceed on this?  Do we want to change "name" -> "type" and then add a new "name" ?   Do we want to add an "id" which is the non-type name?  Do we want to do this 2 step, where we add  "Id" and "type" which is a duplicate of "name" (i.e. reads from "name" if "type" isn't set) then deprecate "name" over time?

References

https://github.com/envoyproxy/envoy/pull/9256
https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L611

**Comment by jplevyak** [comment]
This is a PR https://github.com/envoyproxy/envoy/pull/9391

**Comment by mattklein123** [comment]
Dup of https://github.com/envoyproxy/envoy/issues/9587
