### ISSUE TITLE
Why grpc code ResourceExhausted maps to URX error

### ISSUE THREAD

**Issue by supernan1994** [envoyproxy/envoy#9477]
In the [document](https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/access_log), response flag URX stands for: The request was rejected because the upstream retry limit (HTTP) or maximum connect attempts (TCP) was reached.

I notice there are at least 2 scenes that will cause URX error:
1. upstream connect error or disconnect/reset before headers. reset reason: connection failure.
2. grpc server returns ResourceExhuasted code.

Currently, I use ResourceExhuasted code to represent 429(too many requests). When a user calls API too frequently that out of rate limiter, the server will return ResourceExhuasted and tell the user to retry after a few seconds.
Meanwhile, I use URX response flag to discover if there is any server unavailable and send alert email.  
There is no method to tell whether URX is caused by business error or system error. It seems like URX stands for ResourceExhuasted as well as Unavailable.

Grpc says: ResourceExhausted indicates some resource has been exhausted, perhaps a per-user quota, or perhaps the entire file system is out of space. I think rate limiting is a right scenario to use ResourceExhausted code. 

So I want to ask why grpc code ResourceExhausted maps to URX, and should I use URX response flag to discover server unavailable error?

**Comment by supernan1994** [comment]
Another thing is confusing me. Grpc server also returns ResourceExhausted sometimes(maybe I should ask in grpc repo)：https://github.com/grpc/grpc/blob/master/doc/statuscodes.md.
1.  Sent or received message was larger than configured limit
2. Server temporarily out of resources (e.g., Flow-control resource limits reached)

If I use ResourceExhausted when a user's request frequency reaches the max limit, it's difficult to handle the error.
1. If HTTP/2.0 Flow-control resource limits reached, it's time to scale up.
2. If user level rate limits reached, client should retry.

**Comment by snowp** [comment]
URX simply means that all the retry attempts were exhausted - I'm guessing you're retrying on ResourceExhausted and running out of retry attempts? URX is not tied to any gRPC error in particular

**Comment by supernan1994** [comment]
I think I can reproduce it. I will add a piece of code tomorrow.

**Comment by supernan1994** [comment]
> URX simply means that all the retry attempts were exhausted - I'm guessing you're retrying on ResourceExhausted and running out of retry attempts? URX is not tied to any gRPC error in particular

Yes, I retried on ResourceExhausted. Thanks very much.
