### ISSUE TITLE
Remove shadow artifacts from API tree

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#9479]
As part of https://github.com/envoyproxy/envoy/issues/8082, we introduced shadow protos for Envoy internal use (see https://docs.google.com/document/d/1mGO9LtVo7t4Lph7WlmyGCxXye3h6j29z3JZvIBbs_D0/edit# for rationale). 

Ultimately, we should not be checking into the repository these generated artifacts. If we want to keep shadowing (for convenience), we should be using `protoxform` to generate the desired shadows prior to invoking PGV, to generate shadows.

Preferably, we handle future deprecations without the need for shadowing, in v4+.

**Comment by htuch** [comment]
Tagging for collection in https://github.com/envoyproxy/envoy/issues/10943

**Comment by akonradi** [comment]
Incorporating shadow generation into the Bazel build would greatly speed up development. Running the proto formatter takes a long time and if we can use Bazel for this, we can leverage its caching to avoid unnecessary checks/re-generation.

**Comment by akonradi** [comment]
I think this is something I could take on. I'd love for this to be faster, and building it into our build process should help with that.

**Comment by htuch** [comment]
@akonradi that would be fantastic. Keep in mind that we plan on removing v2 by EOY, so I'd use that to temper how much you invest here. But given your awesome Bazel chops, I'm optimistic :)
