### ISSUE TITLE
retry policies "5xx", "gateway-error", "reset"

### ISSUE THREAD

**Issue by alex3dm** [envoyproxy/envoy#9483]
Do the retry policies "5xx", "gateway-error", "reset" duplicatе each other?

**Comment by zuercher** [comment]
"gateway-error" is a subset of "5xx". Currently, if "gateway-error" or "5xx" is set, upstream resets are retried. There is a comment in the code indicating this may change in the future. So to be future-proof, set "5xx,reset".
