### ISSUE TITLE
Adjust sampling rate of Envoy stats

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#9523]
Is there a way to adjust the percentage of stats that are generated/pushed to a stats listener using the envoy.dog_statsd stats sink? Similar to how you can specify the sampling method and rate for tracing.

**Comment by mattklein123** [comment]
I'm not sure what adjusting a % of the stats that are emitted actually means in practice. You can use the stats flush_interval to control the flush rate though.

**Comment by jaegchoi** [comment]
Is the size of the buffer for the stats configurable? What is the default size of the buffer? We are trying to lessen the memory used by stats
