### ISSUE TITLE
after update cluster.circuit_breakers or cluster.outlier_detection, somtimes accessing encounter 503!

### ISSUE THREAD

**Issue by goith** [envoyproxy/envoy#9528]
# envoy version
- envoyproxy/envoy-alpine:v1.12.2

# description
in the front-envoy, i  configured 2 pods.

At the beginning， accessing the front-envoy return ok. and acessing the envoy admin url `http://127.0.0.1:9901/clusters` , as follow:
>ime-config-gaozhenan.test.odin.local::outlier::success_rate_average::-1
ime-config-gaozhenan.test.odin.local::outlier::success_rate_ejection_threshold::-1
ime-config-gaozhenan.test.odin.local::outlier::local_origin_success_rate_average::-1
ime-config-gaozhenan.test.odin.local::outlier::local_origin_success_rate_ejection_threshold::-1
ime-config-gaozhenan.test.odin.local::default_priority::max_connections::218
ime-config-gaozhenan.test.odin.local::default_priority::max_pending_requests::37
ime-config-gaozhenan.test.odin.local::default_priority::max_requests::18
ime-config-gaozhenan.test.odin.local::default_priority::max_retries::3
ime-config-gaozhenan.test.odin.local::high_priority::max_connections::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_pending_requests::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_requests::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_retries::3
ime-config-gaozhenan.test.odin.local::added_via_api::true
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::cx_active::5
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::cx_connect_fail::0
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::cx_total::5
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::rq_active::0
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::rq_error::0
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::rq_success::265
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::rq_timeout::0
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::rq_total::265
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::hostname::
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::health_flags::healthy
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::weight::1
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::region::
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::zone::
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::sub_zone::
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::canary::false
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::priority::0
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::success_rate::-1
ime-config-gaozhenan.test.odin.local::172.16.1.11:80::local_origin_success_rate::-1
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::cx_active::4
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::cx_connect_fail::0
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::cx_total::4
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::rq_active::0
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::rq_error::0
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::rq_success::261
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::rq_timeout::0
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::rq_total::261
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::hostname::
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::health_flags::healthy
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::weight::1
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::region::
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::zone::
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::sub_zone::
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::canary::false
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::priority::0
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::success_rate::-1
ime-config-gaozhenan.test.odin.local::172.16.78.35:80::local_origin_success_rate::-1

when dynamic update cluster.circuit_breakers or cluster.outlier_detection  by xDS,  after some minutes or seconds, accessing the front-envoy return error.  and no error log,  only output info-level log:
> [2019-12-31 07:54:13.215][1][info][upstream] [source/common/upstream/cds_api_impl.cc:72] cds: add 2 cluster(s), remove 1 cluster(s)
[2019-12-31 07:54:13.216][1][info][upstream] [source/common/upstream/cds_api_impl.cc:88] cds: add/update cluster 'ime-config-gaozhenan.test.odin.local'

And acessing the envoy admin url `http://127.0.0.1:9901/clusters` again , as follow,the cluster's upstream(ip list) disappered. :

>ime-config-gaozhenan.test.odin.local::outlier::success_rate_average::-1
ime-config-gaozhenan.test.odin.local::outlier::success_rate_ejection_threshold::-1
ime-config-gaozhenan.test.odin.local::outlier::local_origin_success_rate_average::-1
ime-config-gaozhenan.test.odin.local::outlier::local_origin_success_rate_ejection_threshold::-1
ime-config-gaozhenan.test.odin.local::default_priority::max_connections::218
ime-config-gaozhenan.test.odin.local::default_priority::max_pending_requests::37
ime-config-gaozhenan.test.odin.local::default_priority::max_requests::18
ime-config-gaozhenan.test.odin.local::default_priority::max_retries::3
ime-config-gaozhenan.test.odin.local::high_priority::max_connections::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_pending_requests::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_requests::1024
ime-config-gaozhenan.test.odin.local::high_priority::max_retries::3
ime-config-gaozhenan.test.odin.local::added_via_api::true

**Comment by mattklein123** [comment]
Sorry can you better describe what the issue is?

**Comment by goith** [comment]
i  changes some description.  and  the problem is clear: the front-envoy config is destoryed after updating by xDs.  @mattklein123
