### ISSUE TITLE
envoy 1.9 failing to build due to missing dependency

### ISSUE THREAD

**Issue by pitiwari** [envoyproxy/envoy#9530]
we are on envoy 1.9.1 and seems like one of the locations of the build dependency is invalid. I tried looking but cant find archive folder location or contents

api/bazel/repositories.bzl:31:        strip_prefix = "protoc-gen-validate-" + PGV_RELEASE,
api/bazel/repositories.bzl:32:        url = "https://github.com/lyft/protoc-gen-validate/archive/v" + PGV_RELEASE + ".tar.gz",

below is the error message from the build 

ERROR: Skipping '//:envoy': error loading package '': in /root/.cache/bazel/_bazel_root/98d36195a0ee79abd52c9d0cdadceb3e/external/envoy_api/bazel/api_build_system.bzl: Encountered error while reading extension file 'bazel/pgv_proto_library.bzl': no such package '@com_lyft_protoc_gen_validate//bazel': java.io.IOException: thread interrupted
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/98d36195a0ee79abd52c9d0cdadceb3e/external/envoy_api/bazel/api_build_system.bzl: Encountered error while reading extension file 'bazel/pgv_proto_library.bzl': no such package '@com_lyft_protoc_gen_validate//bazel': java.io.IOException: thread interrupted
INFO: Elapsed time: 25.015s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
    Fetching @com_lyft_protoc_gen_validate; fetching 21s

**Comment by moderation** [comment]
1.9.x is super old. You are 3 major versions behind - https://www.envoyproxy.io/docs. Bazel versions have moved on a lot. I'd be surprised if 1.9.x from source compiled at all.
