### ISSUE TITLE
[Retry Host Predicate][Feature Request] Add a retry host predicate to omit a host based on endpoint metadata match

### ISSUE THREAD

**Issue by prakhag1** [envoyproxy/envoy#9531]
Currently supported retry host predicates only allow omitting either previously tried or canary hosts. The FR is to add a new host predicate that looks at the endpoint metadata match and omits the host in case of a match with the host metadata. 

Proposed changes are going to be on the lines of:

<pre>
retry_policy:
  ...
  retry_policy:
    retry_host_predicate:
    - name: envoy.retry_host_predicates.omit_host_metadata
      typed_config:
        "@type": type.googleapis.com/envoy.config.retry.omit_host_metadata.v2.OmitHostMetadataConfig
        metadata_match:
          filter_metadata:
            envoy.lb:
              key: value
            ...
</pre>

**Comment by snowp** [comment]
Seems like a totally reasonable addition, I'd be happy to review it.

**Comment by prakhag1** [comment]
@snowp raised a PR for your review.
