### ISSUE TITLE
envoy does not respect the reason phrase for http1.1 call. 

### ISSUE THREAD

**Issue by Jefle2005** [envoyproxy/envoy#9559]
*Title*: *envoy does not respect the reason phrase for http1.1 call. *

*Description*:
for http1.1 call, we customized the reason phrase, e.g. 403 = invalid requestorid, instead of forbidden. but when we use envoy, we found such reason phrase is not treated correctly, which is working well in nginx. 

on application itself, the curl result to localhost looks like below. 
< HTTP/1.1 403 Invalid Requestor ID and Scope
< Content-Length: 0
< Server: Jetty(9.2.15.v20160210)
 but when i curl thru envoy, it's:
< HTTP/1.1 403 Forbidden
< content-length: 0
< server: istio-envoy
< x-envoy-upstream-service-time: 0

pls help advise. Thanks!

**Comment by mattklein123** [comment]
Right now we don't proxy the HTTP/1.1 reason phrase. TBH this will be very complicated to do and does not translate to HTTP/1 -> HTTP/2 proxying. If this is an important thing to solve it will require a bunch of thinking on how to do this without requiring major changes.

**Comment by Jefle2005** [comment]
got it. Thanks!
