### ISSUE TITLE
Switch to slack for community chat

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#956]
I registered envoyproxy.slack.com. We need to figure out:

1) How to handle auto-registration.
2) How to get full history (either by paying for it or asking Slack to help us out).

Then we will likely deprecate IRC/Gitter.

**Comment by mattklein123** [comment]
Can use https://github.com/rauchg/slackin for (1)

**Comment by geeknoid** [comment]
On the Istio team, we've been using Slack and just this morning started experimenting with Gitter instead. We have some issues with Slack and one of the good things about Gitter is that this is where the Envoy folks are.

So what is motivating you from wanting to switch to Slack?

**Comment by mattklein123** [comment]
@geeknoid gitter is pretty bad just in terms of usability. It's not easy to have break out conversations, no search, pinned items, etc. I wonder if Istio/Envoy should share a slack? That might make most sense.

**Comment by geeknoid** [comment]
Whoa, I hadn't noticed the lack of search. That's a killer, Gitter is out.

Our goal is to have a general "users" channel and then N channels exclusively for use by the developers working on Istio. Turns out this kind of control in Slack is only available when you pay for the service. We have an issue in GitHub to the effect we need to figure out how to pay for Slack in order to get infinite retention and permission control.

I'm not sure you'd want Envoy to be so closely tied with Istio. You'll probably have a lot of folks using Envoy sans Istio, and your Envoy conversations would be swamped by a bunch of Istio-specific stuff you probably won't care about.

**Comment by mattklein123** [comment]
Yeah, we have the same issue around figuring out payment. I still think with multiple rooms, it's at least worth considering sharing. We could have istio-users room, envoy-users room, and then as many break out rooms as we want. Not a super huge deal but worth thinking about.

**Comment by moderation** [comment]
I'm not keen on using Slack for open source projects. This article does a good job laying out some of the considerations - https://dave.cheney.net/2017/04/11/why-slack-is-inappropriate-for-open-source-communications. Slack is a proprietary walled garden.

**Comment by moderation** [comment]
Mattermost and Rocket Chat are mentioned as possible good alternatives in the HN discussion of the link above https://news.ycombinator.com/item?id=14087002

**Comment by omnilinguist** [comment]
Should we already start registering accounts in the Slack with the intention that that will soon/eventually become the new official chat? It sounds like there is still some discussion on whether this will be the final call; please advise when this is decided.

**Comment by mattklein123** [comment]
@omnilinguist no, not yet. Unless we can get full paid slack features we won't switch. I'm working on it.

**Comment by mattklein123** [comment]
💥 through some magic we now have full featured slack on envoyproxy.slack.com 💥 

Will figure out signup and switch over from Gitter when I am back from vacation in June.

**Comment by mattklein123** [comment]
Quick update here. Assuming Envoy gets into CNCF, CNCF will manage the slack and signup for us so we can switch then.

**Comment by caniszczyk** [comment]
I'm on it, I'll setup a slackin on envoyslack.cncf.io, give me until next week

**Comment by mattklein123** [comment]
Done!
