### ISSUE TITLE
ENVOY_LOG(warn, ...) vs -l warning inconsistency

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#9560]
In our C++ code we issue warnings by using the `warn` warg to` ENVOY_LOG*` macros.

But when specifying the loglevel we say `-l warning`, and there is no sanity-check for a reasonable `-l foo` arg.

We should make these consistent (at least allowing `-l warn`) and also issue a startup error if you give a bogus argument to `-l`.

**Comment by mattklein123** [comment]
Agreed we should make this better.

**Comment by rulex123** [comment]
Hi! I would like to help out with this.
