### ISSUE TITLE
Reorganize tools directory

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#9568]
https://github.com/envoyproxy/envoy/tree/master/tools

Is getting a little out of control. We should reorganize this directory so that it is more cleanly split into directories of related things. For example, all of the check format scripts, API boosting tooling, etc.

**Comment by rulex123** [comment]
@mattklein123 Hi! I would like to help out with this

**Comment by mattklein123** [comment]
Thanks @rulex123 that would be great. Please try to do a series of small PRs vs. one giant move. My thinking is to arrange things in categories related to checking/fixing format, generating documentation, debugging, etc.

**Comment by rulex123** [comment]
@mattklein123 I will do one last iteration where I separate out debugging-related tools (i.e. valgrind) and proto-format tools.

**Comment by mattklein123** [comment]
I think this is done!
