### ISSUE TITLE
CI check for fuzz coverage

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#9573]
Similar to what we have today for test coverage, a separate job that measures fuzz coverage and prevents check-in when we drop below a certain level will incentivize more fuzzing work done across the developer community. We could narrow this to just extensions and data plane, or make it proxy wide. It won't start as 98%, but even if only 30%, it would provide a useful measure for how we are fairing and prevent regression.

**Comment by asraa** [comment]
We might also want to target certain specific files to have a higher fuzz coverage % -- codec_impls, tokenization libraries, etc.
