### ISSUE TITLE
Rewrite HeaderMap using type safe absl classes

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#9593]
From a side conversation with @htuch I think that with a combination of:
1) https://github.com/abseil/abseil-cpp/blob/master/absl/types/variant.h
2) https://github.com/abseil/abseil-cpp/blob/master/absl/container/inlined_vector.h

We can almost identically replicate the current behavior with little/no performance delta, and in the process remove all of the manual memory management. I don't think this would be very difficult.

**Comment by mattklein123** [comment]
cc @asraa @jmarantz

**Comment by asraa** [comment]
Oh, variant is very cool. I'm assuming inline vector is meant to by a replacement for the `std::list` structure in `HeaderList`?

Happy to start with a PR for using variant in `HeaderString` next week.

**Comment by mattklein123** [comment]
Sorry what I meant is to replace:

https://github.com/envoyproxy/envoy/blob/8057eed8aceaecc29a28fe1cc3818b67cba32585/include/envoy/http/header_map.h#L194-L206

With essentially `absl::variant<absl::string_view, absl::inlined_vector<char, 128>>`.

I think if we do this (roughly) we get rid of all of the manual memory management, the code will get a ton simpler, and we will have essentially the same implementation.

LMK if ^ makes sense. Happy to chat in Slack or hop on a short call also.

**Comment by jmarantz** [comment]
cross-referencing other related issues:
https://github.com/envoyproxy/envoy/issues/4815
https://github.com/envoyproxy/envoy/issues/8795
https://github.com/envoyproxy/envoy/issues/9221

I understand that this proposal is simply to take the existing algorithmic behavior and make it easier to reason about by re-using some absl classes.

**Comment by adisuissa** [comment]
I've got a couple of questions regarding the way I'm going to change this:
1) The `HeaderString::Type` enum will now include "Reference" and "Inline", and "Dynamic" will be omitted. As this is a public enum, and it might be used somewhere else, should "Dynamic" be kept (and given the same value as "Inline"), or should it be removed now?
Here is the original definition:
https://github.com/envoyproxy/envoy/blob/25ce106477428774abbbccda04d0f63bb744a305/include/envoy/http/header_map.h#L95-L97

2) The following test attempts to peek at a value that is beyond the string's length, and assumes the value doesn't change:
https://github.com/envoyproxy/envoy/blob/25ce106477428774abbbccda04d0f63bb744a305/test/common/http/header_map_impl_test.cc#L205-L221

With the proposed approach (using `absl::inlined_vector<char, 128>::reserve` and `absl::inlined_vector<char, 128>::assign`) this seems not to work anymore.
The question is whether this kind of behavior (accessing data beyond the buffer's size) is required?

**Comment by mattklein123** [comment]
1) Can you search the code and see what it's used for? IMO we should kill it.
2) Definitely not required.

Thank you!

**Comment by adisuissa** [comment]
Other than the tests, no access to the Type enum, so I've removed Type::Dynamic.
