### ISSUE TITLE
tools: ability to exclude file regions from spell checking

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#9594]
Would be nice to have some mechanism to disable spell checking on some region of a file. Something like:

```
// NOSPELLCHECK
// not spell checked
// ENDNOSPELLCHECK
```

(It's tempting to stuff this into a NOLINT-style comment. Not sure how that interacts with clang-tidy, for which NOLINT/NOLINTNEXTLINE apply only to single lines.)

N.B. https://github.com/envoyproxy/envoy/pull/9424#discussion_r360568010

**Comment by mattklein123** [comment]
Fixed in https://github.com/envoyproxy/envoy/pull/10188!
