### ISSUE TITLE
Zipkin follow ups

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#960]
- [ ] JSON interface TODO
- [ ] Perf pass
- [ ] End to end docker example would be super amazing (https://lyft.github.io/envoy/docs/install/sandboxes.html)

Might be a few other things missing. Feel free to add. 

cc @adriancole @timperrett @rshriram @fabolive

**Comment by fabolive** [comment]
@mattklein123 Your list sounds like a great starting point for improvements. I should be able to start tackling that next week.

**Comment by kyessenov** [comment]
Is there some plan to filter or sample traces for zipkin?

**Comment by mattklein123** [comment]
> Is there some plan to filter or sample traces for zipkin?

@kyessenov what do you mean exactly? Sampling is already supported (only via runtime, can be trivially added to the config). What do you mean by filtering?

**Comment by rshriram** [comment]
btw, part 3 of this is done.. #993

**Comment by adriancole** [comment]
looks great https://twitter.com/zipkinproject/status/873065607826071553

**Comment by adriancole** [comment]
anybody want to update zipkin's website to show envoy support is in?
https://github.com/openzipkin/openzipkin.github.io/blob/master/_data/community_instrumentations.yml

**Comment by mclarke47** [comment]
@mattkein123 I think filtering refers to excluding endpoints that you probably don't want to trace such as admin resources or health check endpoints.

**Comment by mclarke47** [comment]
I think that another follow up action should be to support 128 bit trace ids ([details](https://github.com/openzipkin/zipkin/issues/1298) [reasons](https://github.com/openzipkin/zipkin/issues/1262)).

**Comment by adriancole** [comment]
Hi, @flier I know this isn't your code, but since you are helping with zipkin in c/c++.. There are a lot of users who'd like this issue to be improved, but less people actively improving. If you can lend a hand, it would be very appreciated.

**Comment by flier** [comment]
@adriancole sure, let me check it later

**Comment by marqub** [comment]
> > Is there some plan to filter or sample traces for zipkin?
> 
> @kyessenov what do you mean exactly? Sampling is already supported (only via runtime, can be trivially added to the config). What do you mean by filtering?

@mattklein123 , can you point me to a sample code or a documentation that shows how to configure these sampling options? Thx

**Comment by mattklein123** [comment]
Here are the runtime settings: https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/runtime

Work is ongoing to make these config settings also: https://github.com/envoyproxy/envoy/issues/1813

**Comment by mattklein123** [comment]
Closing this out as I don't think it's worth tracking the small items here anymore and we have several examples use Jaeger.
