### ISSUE TITLE
Content-length header corrupted by ext_authz

### ISSUE THREAD

**Issue by scranen** [envoyproxy/envoy#9603]
*Description*:
When using ext_authz, requests that specify a content length result in a corrupted content-length header being sent to the authentication application. This seems ~like it is a regression from~ related to #3865. The corruption seems to be due to this line:
https://github.com/envoyproxy/envoy/blob/58e733bfbd0a26e3c86b5de3e6b3a7de436e5269/source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc#L210
If the incoming request already contains a `content-length` header, then this results in a comma-separated list being sent to the authentication server (see for instance in the logs below, where `content-length: 0,4` is sent to the server).

*Repro steps*:
- Configure ext_authz to send authentication requests to an HTTP server
- Try to call a POST endpoint with a request body using e.g. curl

Example curl output:
```
$ curl -iu test:test localhost:8082/endpoint -d'test'
HTTP/1.1 400 Bad Request
content-type: text/plain; charset=utf-8
content-length: 4
date: Wed, 08 Jan 2020 14:39:19 GMT
server: envoy
x-envoy-upstream-service-time: 1

Invalid HTTP Header: Content-Length%                                                                                                                                                                                                      
```

*Config*:
[envoy.yaml.txt](https://github.com/envoyproxy/envoy/files/4035851/envoy.yaml.txt)

*Logs*:
```
[2020-01-08 14:39:19.749][22][debug][http] [source/common/http/conn_manager_impl.cc:259] [C0] new stream
[2020-01-08 14:39:19.750][22][debug][http] [source/common/http/conn_manager_impl.cc:708] [C0][S14461594867658536095] request headers complete (end_stream=false):
':authority', 'localhost:8082'
':path', '/endpoint'
':method', 'POST'
'authorization', 'Basic dGVzdDp0ZXN0'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'content-length', '4'
'content-type', 'application/x-www-form-urlencoded'

[2020-01-08 14:39:19.750][22][debug][router] [source/common/router/router.cc:434] [C0][S14125282183838975606] cluster 'auth' match for URL '/auth/endpoint'
[2020-01-08 14:39:19.750][22][debug][router] [source/common/router/router.cc:549] [C0][S14125282183838975606] router decoding headers:
':authority', 'localhost:8082'
':method', 'POST'
':path', '/auth/api/1/decant/1/confirm'
':scheme', 'http'
'content-length', '0,4'
'x-forwarded-proto', 'http'
'accept', '*/*'
'content-type', 'application/x-www-form-urlencoded'
'user-agent', 'curl/7.64.1'
'authorization', 'Basic dGVzdDp0ZXN0'
'x-request-id', 'c032c6e9-cc9b-424b-8f94-0fe1c2b2b32d'
'x-envoy-internal', 'true'
'x-forwarded-for', '172.20.0.9'
'x-envoy-expected-rq-timeout-ms', '250'
```

**Comment by dio** [comment]
@scranen thanks for reporting. Sorry, to clarify, could paste here the envoy version? Thanks!

**Comment by scranen** [comment]
Yes, sorry, thought about that and then forgot. We're using 1.12.1

**Comment by scranen** [comment]
For other readers of this ticket: the workaround is to configure the ext_authz configuration's `http_service.authorization_request.allowed_headers` property to `{patterns: [ { regex: 'ˆ(?!content-length$).*' } ]}`.
