### ISSUE TITLE
stats_integration_test is failing on Mac

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#9605]
E.g. see https://dev.azure.com/cncf/envoy/_build/results?buildId=26093&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0&l=43917

**Comment by jmarantz** [comment]
I'm guessing this is a merge-issue from https://github.com/envoyproxy/envoy/pull/9069

**Comment by jmarantz** [comment]
In any case this will be fixed when https://github.com/envoyproxy/envoy/pull/9564 merges.

As @mattklein123 seemed OK with the general strategy in that PR and I think I have now successfully delivered on his comment, I'd rather not fix this separately as that would just cause another merge conflict for #9564.
