### ISSUE TITLE
perf: perf testing framework / regression testing

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#961]
@htuch I made this issue for the intern to cover OSS stuff. We can keep track of items here as they come up.

**Comment by htuch** [comment]
We should also investigate #1033 as part of this work.

**Comment by htuch** [comment]
We now have Nighthawk (https://github.com/envoyproxy/nighthawk) with the requisite load generation tools. I think it would be great if someone wants to pick up the creation of an orchestration and CI regression / visualization framework around this. It would be very useful to have an understanding how basic QPS vs. latency tracks over time.

CC @mattklein123 @oschaaf

**Comment by mattklein123** [comment]
Agreed this sounds amazing. Let's discuss this on the next community call?

**Comment by htuch** [comment]
@mattklein123 added to agenda, good idea.

**Comment by mattklein123** [comment]
This is in progress and covered by Salvo and various design documents. Closing this and we can track elsewhere.
