### ISSUE TITLE
tools: tools/proto_format.sh fix deletes files

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#9610]
Minor annoyance but I got bitten multiple times: when adding a new config proto, proto_format will delete it unless it's mentioned in api/docs/BUILD.

**Comment by htuch** [comment]
This is WAI, it's supposed to be removing files that are not linked in. I think we need better documentation, and that's on my TODO list.

**Comment by htuch** [comment]
CC @lizan

**Comment by lizan** [comment]
Yeah I think I did that in to find unlinked protos (especially for those in v3alpha)

**Comment by kyessenov** [comment]
The reason why it's annoying is that to get a proto show up in build tree (via API shadow), one has to run that script. We can either provide a separate script to copy a new proto to shadow without deletion, or make this script skip deletion unless asked.

**Comment by htuch** [comment]
At this stage, any proto that shows up in the build tree that isn't added via this script might not be structurally right. Let's go with this flow for now, I will work on documentation shortly.
