### ISSUE TITLE
Track original type URL in upgraded protos

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#9612]
When we upgrade protos during config ingestion, we throw away the original type information. When providing debug representations or trying to recover things like runtime key, this is problematic. We should smuggle in the original type URL in an unknown field and provide some utils in `ApiTypeOracle` to recover the original message.

This is blocking https://github.com/envoyproxy/envoy/pull/9591#issuecomment-572193677.

CC @lizan (in case you have any thoughts on alternatives)

**Comment by kyessenov** [comment]
Is this for something beyond previous_message_type annotation? Or is this about runtime behavior of maintaining a record that config was converted?

**Comment by htuch** [comment]
@kyessenov the latter, we want to know whether it was v2 or v3alpha on the wire, regardless of the message descriptor history.
