### ISSUE TITLE
xDS: API version fallback

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#9617]
*Title*: *xDS: API version fallback*

I think that API version fallback is needed if envoy specified API version differ from that of Control Plane. 
My planning of implementation is that

1. request to management server with specified xDS version. (that can be extracted from `typeUrl` so It is not needed to add additional field on `DiscoveryRequest`)
2. Management server respond with supporting API version. (Is it needed to add additional field on `DiscoveryResponse`? I think that it is needed to distinguish specified API version and that of management server)
3. If there is not empty string on additional field like `FallbackedSupportedTypeUrl`. Change envoy specified API version dynamically referring to that.

**Comment by htuch** [comment]
@Shikugawa the original thinking was that Envoy would attempt to connect to a v3 endpoint (which is a distinct URL), and if that fails, it will attempt to connect to a v2 endpoint. You're describing an in-band fallback, which is a bit different.

**Comment by lambdai** [comment]
@htuch Is there an alternative solution beside this one?

**Comment by htuch** [comment]
@lambdai https://github.com/envoyproxy/envoy/issues/10776
