### ISSUE TITLE
replace fmt::format with abseil

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#9623]
Abseil has all the string processing functionality we need, this would allow us to remove a dependency.

**Comment by mattklein123** [comment]
@derekargueta I would discuss with @jpeach who was also looking into this. FWIW unless we have a plan to replace it also in logging (it is baked into spdlog pretty heavily) I don't see a huge amount of value in the churn here. If we can replace it everywhere that would be nice.

**Comment by derekargueta** [comment]
Yeah the idea for this was actually from a slack message @jpeach posted a while ago in #envoy-dev. I'll copy the transcript here:
***jpeach 11:15 PM***
Why does envoy use fmt::format() rather than absl::Substitute? It looks like the use cases are similar and the fmt dependency could be dropped if this change was made.
***lizan 12:01 AM***
mostly due to historical reasons, fmt exists before we introduce absl
***jpeach 1:29 AM***
I see, that makes sense
***htuch:envoy: 2:51 AM***
yes, please nuke fmt::format if you see it and replace with absl
it's fine in logging
but if it's on the data path, we would definitely like to see a directional move away from fmtlib

I was able to knock out a lot of easy conversions from `fmt::format("some string: {}", foo);` to `absl::StrCat("some string: ", foo);` with a regex transform from: 
`fmt::format\("(([A-z]|\s)*)\{\}",\s(([A-z]|\.|_|\(|\))*)\);`
to
`absl::StrCat("$1", $3);`
But for the more involved format templates we'll definitely need something a little more complex.

**Comment by jpeach** [comment]
There's clang tooling to do this here: https://github.com/jpeach/rewrite-fmt-format.
Previous discussion in https://github.com/envoyproxy/envoy/pull/8963

There are a very few places (maybe 5) that use fmt formatting specifiers other than "{}". These need to be done by hand. There are also a couple of cases where the format string isn't a literal, which also need to be done by hand.

**Comment by htuch** [comment]
Given that `fmt` is now in C++20, I think we should stick with `fmt` for the long term FWIW.

**Comment by ahedberg** [comment]
It is a little weird to have two formatting libraries, but probably not worth the churn. Maybe some rule like "use fmt in logging, use absl everywhere else" suffices.

If the ultimate goal is to remove dependencies, Abseil is releasing its own logging framework soonish, which could let us cut spdlog and fmt if we wanted.
