### ISSUE TITLE
fixups to deprecation tooling

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#9634]
tools/deprecate_features/deprecate_features.py did old style v2 fatal-by-default annotation

We need a new script that takes protos tagged as deprecated and annotates them as disallowed by default.  
Should be fairly simple with protox, though ideally we might want to only tag things which have been in the code base more than N months to avoid the issue where something is deprecated just before release, which gets a bit tricker.

cc @htuch as we'll want this tooling as we cut the release next week.

**Comment by alyssawilk** [comment]
oh, and it'll have to auto-import the deprecation proto and add it to the build package too

**Comment by htuch** [comment]
I'll take a look at this as we cut 1.13.0, thanks.

**Comment by htuch** [comment]
@alyssawilk is there something we still need here? Trying to figure out what we want out of tooling as we move to the minor/patch versioning policy. CC @adisuissa

**Comment by alyssawilk** [comment]
AFIK we still want folks to incrementally migrate off deprecated config, so make old config fields warn-by-default then fatal-by-default in-envoy, or we'll reintroduce the problem we had years back, which is that people don't migrate until we remove old fields, and only then find bugs.

Now that we have all the fancy proto introspection code I think we just want to be able to annotate the protos for what phase of deprecation they're in for Envoy, and have Envoy do what's appropriate.

**Comment by htuch** [comment]
I see, we basically need to make this script operates via explicit proto annotation update. I'm assigning this @adisuissa's way, since he'll be working in these tools as part of the minor version annotations.
