### ISSUE TITLE
Envoy hot-restart doesn't respect `drain-time-s` and `parent-shutdown-time-s`

### ISSUE THREAD

**Issue by jaricftw** [envoyproxy/envoy#9638]
*Title*: Envoy hot restart takes longer than what's specified in `drain-time-s` and `parent-shutdown-time-s`. 

*Description*:
We are using the Envoy hot restart feature in production, and noticed a change of behavior in the recent release of Envoy. To be exact, I narrow it down to v1.12.0: https://www.envoyproxy.io/docs/envoy/v1.12.0/intro/version_history. 

**TLDR**: before V1.12.0, starting a new Envoy shuts down the parent Envoy with respect to `parent-shutdown-time-s`. After, it takes 30s + `parent-shutdown-time-s`. 

**Repro** to test Envoy graceful restart, with docker:

`start_envoy.sh`
```
docker run -it -v $PWD/envoy:/etc/envoy/  --ipc="host" --net=host envoyproxy/envoy:v1.11.2 /usr/local/bin/envoy -c /etc/envoy/bootstrap.yaml --restart-epoch $RESTART_EPOCH --drain-time-s 10 -l debug --parent-shutdown-time-s 15
```
And here is the bootstrap.yaml content: https://gist.github.com/jaricftw/2d71ef84ccf48927c804ca53fff0fe78

So in one terminal, we do:
```
RESTART_EPOCH=0 ./start_envoy.sh
```

In another, we do:
```
RESTART_EPOCH=1 ./start_envoy.sh
```
For v1.11.2 and before, the behavior is that the parent Envoy will be shut down in around 15 seconds, as shown by the `parent-shutdown-time-s`. 

However, with v1.12.0 and after, the shutdown takes exactly 30s + `parent-shutdown-time-s`, regardless of what I set in the `drain-time-s`.

**Comment by zyfjeff** [comment]
My guess is that this PR #7571 was introduced. Before this PR, if you can't connect to the xDS server, it will drain up immediately. But after this PR is introduced, you will reconnect until timeout. So the total time is about 15 + parent-shutter-time-s.


https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#envoy-api-field-core-configsource-initial-fetch-timeout

**Comment by jaricftw** [comment]
@zyfjeff Yeah, that explained why it took `30s + parent-shutdown-time-s`.  The test I did was not connecting to the xDS server.  That in theory shouldn't be block the hot-restart of Envoy, so we probably need a proper fix.

**Comment by zyfjeff** [comment]
@jaricftw No, Envoy's hot restart is dependent on the xDS server, always has been, and it's only because of init_fetch_timeout that the entire cycle is longer. We can modify init_fetch_timeout to shorten this time.

**Comment by jaricftw** [comment]
@zyfjeff something looks wrong here if that's the case: PR #7571 made the default from `0` to `15s`, and now as the [comment](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/config_source.proto#L172) says:

> // 0 means no timeout - Envoy will wait indefinitely for the first xDS config (unless another
  // timeout applies). The default is 15s.

That indicates, in the old behavior where default was `0`, Envoy will block indefinitely upon bootstrap --- hence blocking hot-reload indefinitely. But that's apparently not the case, the old behavior was that the handoff between two Envoys will start immediately. 

Am I missing anything here?

**Comment by zyfjeff** [comment]
@mattklein123 @ramaraochavali  

At present, our initial-fetch-timeout parameter only controls the timeout time of a single resource subscription, which makes it difficult to calculate the initialization time of the entire envoy, which may cause the envoy initialization to take a lot of time in serious cases.

**Comment by zyfjeff** [comment]
@jaricftw If it is 0, there is no timeout control, so a failure to connect to xDS will cause the initialization to end.

```
void GrpcMuxSubscriptionImpl::onConfigUpdateFailed(ConfigUpdateFailureReason reason,
                                                   const EnvoyException* e) {
  switch (reason) {
  case Envoy::Config::ConfigUpdateFailureReason::ConnectionFailure:
    stats_.update_failure_.inc();
    ENVOY_LOG(debug, "gRPC update for {} failed", type_url_);
    break;
  case Envoy::Config::ConfigUpdateFailureReason::FetchTimedout:
    stats_.init_fetch_timeout_.inc();
    disableInitFetchTimeoutTimer();
    ENVOY_LOG(warn, "gRPC config: initial fetch timed out for {}", type_url_);
    break;
  case Envoy::Config::ConfigUpdateFailureReason::UpdateRejected:
    // We expect Envoy exception to be thrown when update is rejected.
    ASSERT(e != nullptr);
    disableInitFetchTimeoutTimer();
    stats_.update_rejected_.inc();
    ENVOY_LOG(warn, "gRPC config for {} rejected: {}", type_url_, e->what());
    break;
  }

  stats_.update_attempt_.inc();
  if (reason == Envoy::Config::ConfigUpdateFailureReason::ConnectionFailure) {
    // New gRPC stream will be established and send requests again.
    // If init_fetch_timeout is non-zero, server will continue startup after it timeout
    return;
  }
  
  callbacks_.onConfigUpdateFailed(reason, e);
}
```

**Comment by jaricftw** [comment]
@zyfjeff thanks for the explanation. 

So iiuc, PR #7571 caused the following change of default behaviors:
1. if xDS is connected, block for 15s instead of indefinitely for a response
2. If xDS is not connected, block for 15s instead of abort initialization immediately 

1 is a reasonable change, but 2 seems like an unexpected change? 

It's not too bad since this is only an issue when xds is not connected, but ideally we'd want a deterministic graceful shutdown timeout (as specified by `-parent-shutdown-time-s`) so that our Envoy scheduler has better control on the Envoy process.

**Comment by ramaraochavali** [comment]
PR #7571, waits for 15s for Envoy to initialize,  whether there is an initial connection problem or connection problem that happened after exchange of some messages, it does not matter.  So 1 and 2 described above fall in to the same category.

**Comment by mattklein123** [comment]
Yeah I think that was an intentional change to try to give users a sane set of default timeouts. You could potentially configure shorter fetch timeouts if you don't like this behavior?

**Comment by jaricftw** [comment]
okay, closing the issue, since that seems like an intentional change, and don't affect the common happy case --- we probably need to update docs on [hot-restart](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart) so people are aware.
