### ISSUE TITLE
xds: typed_struct doesn't work for upstream network filters

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#9640]
Upstream filter factory appears to unpack typed_config directly into empty config proto (see https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.cc#L776). What should happen is that the config needs to be converted first.

**Comment by htuch** [comment]
@yanavlasov FYI re: `TypedStruct`

**Comment by yanavlasov** [comment]
@kyessenov did you mean converted from v2 to v3alpha?

**Comment by kyessenov** [comment]
I mean just having TypedStruct in typed_config doesn't work (conversion doesn't either I believe). PTAL at PR.
