### ISSUE TITLE
Envoy logs `%ROUTE_NAME%` correctly, but also sets `%RESPONSE_FLAGS%` to `NR` and returns 503??

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#9644]
We are running envoy as a multi-tenanted edge proxy, which is self-service. One of our customers configured some routes and found that one in particular returned a HTTP 503.

We have analyzed the route which was about as simple as:

```yaml
name: example-route
match:
  prefix: /abc-def-ghijklmno
route:
  cluster: some-cluster
```

We verified that the cluster name was valid, and deployed a similar route to another service of ours to make sure there was nothing wrong with the prefix match (there was suspicion that having multiple hyphens was causing some problem). The route worked on an alternative service so we ruled out the possibility of a syntax problem.

Anyway, what we observed in the logs was that the `NR` flags were set. We know that this means that envoy could not find a route that matches the details of the request... however, we also log the macro `%ROUTE_NAME%`, and it logged the expected route name.

So I am perplexed... In what scenario will envoy set the `NR` flag but *also* set the `%ROUTE_NAME%` to something other than the default `-`?

**Comment by snowp** [comment]
NR is also set if the cluster wasn't known to the cluster manager, e.g. that `some-cluster` wasn't known to Envoy

**Comment by cetanu** [comment]
I think I might close this one as I don't have enough data on my side to form a timeline of events; what you said makes perfect sense and is likely the cause of the NR/503.
