### ISSUE TITLE
docs: add missing protodoc-title entries

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#9655]
*Title*: *docs: add missing protodoc-title entries*

*Description*:
There are a number of proto entries that are missing the protodoc-title entries and hence show up in the generated documentation as *.proto entries.

![image](https://user-images.githubusercontent.com/246317/72185613-2471f280-33eb-11ea-9c72-6ce82c127764.png)

Example of proto:

- with  - https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v2alpha/server_info.proto#L11
- without - https://github.com/envoyproxy/envoy/blob/master/api/envoy/admin/v2alpha/tap.proto#L12

Question: I'll update for v2 and v3 protos, but do the protos in `generated_api_shadow` need to be updated manually?

**Comment by mattklein123** [comment]
@moderation I'm actually literally fixing this right now, including making the lack of a protodoc title an error. Do you want to just take over my branch? Also, I think this is a dup of another issue.

**Comment by mattklein123** [comment]
https://github.com/envoyproxy/envoy/issues/8525

**Comment by mattklein123** [comment]
@moderation here is my WIP branch which I'm working on between meetings :)

https://github.com/envoyproxy/envoy/tree/doc_fixes

**Comment by moderation** [comment]
This is a dupe and I'll close. Happy to take over your branch

**Comment by mattklein123** [comment]
@moderation all you need to do is run the formatter and it will update both v3 and the generated API protos.

**Comment by jcchavezs** [comment]
Quick question: is `protodoc-title` some sort of standard?

**Comment by jcchavezs** [comment]
Curious about which tool you use to generate protodoc.

**Comment by phlax** [comment]
`protoc` altho the generation is somewhat complex - involving a bazel aspect  - see the `tools/protodoc` directory for more info

**Comment by stokedout** [comment]
Can you tell me what tool is using these `// [#protodoc-title: TCP Proxy]` to generate the docs?
