### ISSUE TITLE
Copying out from Buffer Instance to another one

### ISSUE THREAD

**Issue by cre4tiv3** [envoyproxy/envoy#9661]
Hi,

I've been looking for a way of copying data from a Buffer::OwnedImpl to another one. What I've done so far is below:

```c++
func(const Envoy::Buffer::Instance& origin_instance){
  std::unique_ptr<uint8_t[]> buff(new uint8_t[1024]);
  origin_instance.copyOut(0, 1024, buff.get());
  target_instance.add(buff.get(),1024);
}
```
Here I want to copy the first 1024 bytes of the `origin_instance` buffer to `target_instance`. However, I could not find a direct solution for that and applied a workaround using `buff`. The above code snipped copies the content two times (for copyOut and add separately). 

Is there a way to prevent the second copy by moving the content of buff directly or something else instead of using Instance::add here? 

Thanks in advance,
Raleigh.

**Comment by htuch** [comment]
Depending on your use case, you could use `getRawSlices()` to access the buffer directly and `add` those slices. That would avoid a second copy. Another option is `linearize()`, but that is potentially expensive. Often `move` makes more sense, which is an operation that `Buffer` supports natively, but depends on use case.
