### ISSUE TITLE
How to get domain from Envoy by Lua

### ISSUE THREAD

**Issue by ak7x13** [envoyproxy/envoy#9664]
I'd like to route requests by different domains. I've read https://www.envoyproxy.io/docs/envoy/v1.12.2/configuration/http/http_filters/lua_filter, but I can not find any mehod can do that. Is there anyway to get domain from Envoy by Lua?

**Comment by htuch** [comment]
@ak7x13 you probable want to look at the host/authority header for this.

**Comment by ak7x13** [comment]
Some requests maybe not include the host/authority. Is there something like `http_host` in nginx?
