### ISSUE TITLE
Envoy gRPC client

### ISSUE THREAD

**Issue by andreysm** [envoyproxy/envoy#9675]
Documentation mentions "Envoy gRPC client" as an alternative to "Google C++ gRPC client" at
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc.html#grpc-services

What is Envoy gRPC client? Is it a gRPC client library? Where do I get it?

**Comment by htuch** [comment]
This just refers to the fact that Envoy has an in-built gRPC client implementation for issuing requests, e.g. for xDS subscriptions, when connecting to metrics service, when a filter needs to make an RPC call. In addition, Envoy can use the standard Google gRPC libraries to make such calls.
