### ISSUE TITLE
Proposal: add suggestion for bad configuration field

### ISSUE THREAD

**Issue by acrazing** [envoyproxy/envoy#9677]
*add suggestion for bad configuration field*

*Description*:

The configuration of envoy is very complex, sometimes the words is confusing, for example: the `socket_address.port_value`, if we provide `socket_address: { address: ..., port: ... }`, and then we are going to get an error like this:

> INVALID_ARGUMENT:(admin.address.socket_address) port: Cannot find field.) has unknown fields

It is hard to find out what the problem is. It would be graceful if the error could give some suggestions like `git`. For example:

```text
INVALID_ARGUMENT:(admin.address.socket_address) port: Cannot find field.) has unknown fields

Did you mean one of these?
       port_value
```

**Comment by htuch** [comment]
I agree this would be a useful enhancement. We could build some edit distance ordered data structure at Envoy startup based on the descriptor pool reflection field names for each type.

I think one complexity here is that the error messages don't come directly from Envoy, but instead the C++ protobuf libraries. For binary protos, we actually don't have field names, only field numbers. For JSON/YAML, there is no support today in proto for obtaining the individual field names for unknowns, see https://github.com/protocolbuffers/protobuf/issues/5967.

I'll leave this open in case anyone wants to work on this (either Envoy-side or Protobuf-side).
