### ISSUE TITLE
/server_info has empty service_[cluster|node|zone] when configured in bootstrap

### ISSUE THREAD

**Issue by derekargueta** [envoyproxy/envoy#9684]
This is a bug report that when one configures service_cluster, service_node, or service_zone using bootstrap configurations (on the `node` object) and not through CLI flags, then the admin interface reports these values as empty on`/server_info`. This is because the admin interface simply dumps whatever is contained in the `CommandLineOptions` struct (https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc#L929).

It would be best to fix this before https://github.com/envoyproxy/envoy/issues/3326

**Comment by htuch** [comment]
Yep, that's broken, it should consume this from the server's `LocalInfo`. @derekargueta are you planning on working on a fix for this?

**Comment by derekargueta** [comment]
@htuch yeah I can put together a patch. Do we have any stability guarantees on the admin interface? I think it'd be best to explicitly enumerate fields in [the ServerInfo message](https://github.com/envoyproxy/envoy/blob/5248a4fb7d4c2a3d1fa151f944d3a63f6b7a06cf/api/envoy/admin/v3/server_info.proto#L20) rather than just [embedding command line args directly](https://github.com/envoyproxy/envoy/blob/5248a4fb7d4c2a3d1fa151f944d3a63f6b7a06cf/api/envoy/admin/v3/server_info.proto#L52). That way if a command line arg goes away (i.e. #3326) or is changed we don't have to necessarily break the ServerInfo interface. And typically operators/SRE's can see the command line args from `ps aux | grep envoy` so I'm not sure it provides much value restating them here verbatim.

If stability is a concern, we could do something like duplicate these keys as fields on the ServerInfo message. I wouldn't want to repopulate items in the CommandLineOptions message if it wasn't actually configured on the command line.

**Comment by htuch** [comment]
The `v3` message is now stable, so we can't make any breaking changes. We could put the `Node` message held in `LocalInfo` in `ServerInfo`, that should address this issue.
