### ISSUE TITLE
Leak of information about cluster member

### ISSUE THREAD

**Issue by hakuno** [envoyproxy/envoy#9689]
Please, how do I retrieve the `envoy_cluster_internal_upstream_rq_xx` by cluster members?

I have a cluster with 2 members... (load_assignment/lb_endpoints)... but I can't find any information to get errors from each cluster nodes.

One of these cluster members is buggy, but I can't find which node. No tip found.

**Comment by htuch** [comment]
@hakuno does the `/clusters` endpoint provide you the information you need?

**Comment by hakuno** [comment]
So I can read `rq_error` as bad HTTP code status response. Nice!

```
cluster::node1::rq_active::0
cluster::node1::rq_error::0
cluster::node1::rq_success::94
cluster::node1::rq_timeout::0
cluster::node1::rq_total::94
```

How do I read that with the Prometheus/Grafana?

**Comment by htuch** [comment]
@hakuno I think that question is outside my domain knowledge, so I'll leave this open for others to comment on for the normal question period of time (2 weeks).

**Comment by mattklein123** [comment]
Per-host stats are not currently exported to the stats sinks, due to cardinality issues.

**Comment by hakuno** [comment]
All right. Thanks!
