### ISSUE TITLE
proxying requests to AWS authenticated services (e.g.: s3)

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#9708]
We've got some use cases where we need to proxy requests to S3 buckets which require authentication.

#7281 added AWS credential providers, so we could potentially have an `s3_auth` http filter that uses that and adds the needed headers. The filter would probably need to support `per_filter_config`, to allow restricting the functionality to a subset of routes.

I think this sounds like a generally useful filter, so I am thinking of developing it for upstream instead of being another in-house filter.

Thoughts?

cc: @mattklein123  @derekargueta

**Comment by mattklein123** [comment]
Agreed this sounds interesting and generally useful. cc @marcomagdy @lavignes in case AWS would like to help out with this.

**Comment by dastbe** [comment]
@rgs1 does the supported signature versions matter to you?

**Comment by rgs1** [comment]
@dastbe i think we want sigv4.

**Comment by rgs1** [comment]
@dastbe maybe v2 is ok actually... waiting for a final answer.

**Comment by mattklein123** [comment]
As an aside, will looking briefly through this code again, I noticed that https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/http/common/aws should probably be moved to here: https://github.com/envoyproxy/envoy/tree/master/source/extensions/common. It would be nice to clean that up as part of this issue, but low priority.

**Comment by dastbe** [comment]
@rgs1 sigv4 would actually be preferable, and would allow for a general "sigv4_auth" filter. AFAIK the only extant service that supports sigv2 is S3 and so would only be valuable for that svc.

**Comment by rgs1** [comment]
@dastbe yeah sigv4 is actually what we want -- so great that it's preferable. Thanks!

**Comment by marcomagdy** [comment]
couple of things to note (that will potentially save you a lot of head scratching) when dealing with S3 signing:
1. Requests made over plain HTTP to S3 require signing the _entire_ body of the request. However, signing the headers is sufficient when going over HTTPS.
1. I believe the current signing implementation in Envoy does not encode the URL path while calculating the signature. This is usually fine for AWS service paths, but when dealing with S3, the path is basically user input, so it will not work for some buckets. This should be an easy fix. You can take a look on how the [C++ SDK handles it](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/auth/AWSAuthSigner.cpp#L90).

**Comment by lavignes** [comment]
@mattklein123 I think I put it aws stuff under `extensions/filters/http/common/aws` because I misinterpreted a comment #5546 and no one stopped me. :) It *is* kind of buried in the extension tree which makes it hard to find.

**Comment by mattklein123** [comment]
> @mattklein123 I think I put it aws stuff under extensions/filters/http/common/aws because I misinterpreted a comment #5546 and no one stopped me. :) It is kind of buried in the extension tree which makes it hard to find.

Not a big deal, just something worth cleaning up if someone is planning on using this code elsewhere.

**Comment by rgs1** [comment]
@marcomagdy thanks for the notes! I am thinking something like (very WIP) #9751. LMK what you think. 

cc: @lavignes

**Comment by rgs1** [comment]
@marcomagdy @lavignes hmm, there's currently no RegionProvider that fetches region from instance metadata:

https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/common/aws/region_provider_impl.cc

Any reasons not to add one that gets it from `http://169.254.169.254/latest/dynamic/instance-identity/document` [0]?

[0] e.g.: `curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region`

**Comment by lavignes** [comment]
@rgs1 The main reason against pulling region from instance metadata was that it is static config. It can be passed in the bootstrap or a stock AWS env var. Plus some services do not exist in all regions. So cross-region calls are necessary. Making it configurable in the bootstrap is MVP to support these use-cases.
