### ISSUE TITLE
Does dubbo proxy support Envoyfilter to ApplyTo ROUTE_CONFIGURATION？

### ISSUE THREAD

**Issue by bingohuang** [envoyproxy/envoy#9713]
**Description**:
EnvoyFilter provides a mechanism to customize the Envoy configuration generated by Istio Pilot, as for ROUTE_CONFIGURATION：

> `Applies the patch to the Route configuration (rds output) inside a HTTP connection manager. This does not apply to the virtual host. Currently, only MERGE operation is allowed on the route configuration objects.`

Does Dubbo proxy support Envoyfilter to ApplyTo ROUTE_CONFIGURATION? And whether the listener will be restarted when ApplyTo ROUTE_CONFIGURATION?

Thanks. @zyfjeff 

 **Relevant Links**:
https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo

**Comment by light-x** [comment]
Is it that dubbo_proxy does not implement rds dynamic update?

**Comment by zyfjeff** [comment]
> Is it that dubbo_proxy does not implement rds dynamic update?

Yes, currently dubbo does not implement RDS

**Comment by zyfjeff** [comment]
@bingohuang Currently, the routing information is embedded in the Dubbo filter, so it can only be updated by modifying the network filter

**Comment by bingohuang** [comment]
Thanks @zyfjeff. Is there a plan to implement RDS update in dubbo proxy? We have a problem which need the feature to resolve.

**Comment by light-x** [comment]
https://github.com/envoyproxy/envoy/issues/9700 
I think this is the same question.

**Comment by light-x** [comment]
Duplicate of #9700 I think this is the same question.

**Comment by zyfjeff** [comment]
@bingohuang Currently, HTTP RDS and dubbo are not compatible. To implement dubbo RDS, we need to re-develop a new xDS protocol, which is not in line with the direction of the community. We need to further explore common routing services. #9656
