### ISSUE TITLE
Dubbo Support RDS 

### ISSUE THREAD

**Issue by zengyuxing007** [envoyproxy/envoy#9714]
*Title*: *Dubbo Support RDS*

*Description*:
>Currently, the dubbo protocol does not support RDS, which means that routing configuration can only be updated through LDS (EnvoyFilter by istio)；but,  there will be a problem connecting drains when updating routing configuration by LDS  (https://github.com/envoyproxy/envoy/issues/9713)

Therefore, it is best to implement a Dubbo RDS similar like http RDS. 

We have now implemented RDS support for the Dubbo protocol and hope to contribute it to the community

**Comment by bingohuang** [comment]
Wonderful!

**Comment by popomen** [comment]
I think you need to coordinate with this issue
[#9656](https://github.com/envoyproxy/envoy/issues/9656)

**Comment by mattklein123** [comment]
Agreed let's try to figure out if we can have some amount of common routing infra that would cover HTTP/gRPC/Dubbo/Thrift/etc.

**Comment by CodingSinger** [comment]
@mattklein123  Where is your discussion address？

**Comment by CodingSinger** [comment]
> _Title_: _Dubbo Support RDS_
> 
> _Description_:
> 
> > Currently, the dubbo protocol does not support RDS, which means that routing configuration can only be updated through LDS (EnvoyFilter by istio)；but,  there will be a problem connecting drains when updating routing configuration by LDS  (#9713)
> 
> Therefore, it is best to implement a Dubbo RDS similar like http RDS.
> 
> We have now implemented RDS support for the Dubbo protocol and hope to contribute it to the community
Is there any problem with modifying the listener to modify the route?

**Comment by CodingSinger** [comment]
> _Title_: _Dubbo Support RDS_
> 
> _Description_:
> 
> > Currently, the dubbo protocol does not support RDS, which means that routing configuration can only be updated through LDS (EnvoyFilter by istio)；but,  there will be a problem connecting drains when updating routing configuration by LDS  (#9713)
> 
> Therefore, it is best to implement a Dubbo RDS similar like http RDS.
> 
> We have now implemented RDS support for the Dubbo protocol and hope to contribute it to the community



Is there any problem with modifying the listener to modify the route?

**Comment by mattklein123** [comment]
@CodingSinger sorry can you clarify what you are asking?
