### ISSUE TITLE
Ratelimit configuration: extract multiple headers and send a tuple of descriptors

### ISSUE THREAD

**Issue by qbrent** [envoyproxy/envoy#9717]
Hi,

I am looking to extract values from multiple headers and send it as a tuple of descriptors to the rate limit service,  but I only seem to be able to use `request_headers` once; I have tried both

```
rate_limits:
- actions:
 - {request_headers: {"header_name": "plan","descriptor_key": "plan"}}
- actions:
 - {request_headers: {"header_name": "clientId","descriptor_key": "clientId"}}
```

or

```
rate_limits:
- actions:
 - {request_headers: {"header_name": "plan","descriptor_key": "plan"}}
 - {request_headers: {"header_name": "clientId","descriptor_key": "clientId"}}
```

With either configuration, I only see one of the `descriptor_key` in the ratelimit service.

Thanks,
Brent

**Comment by tricky42** [comment]
@qbrent I am searching for a solution for very similar requirements. Did you find a solution?
