### ISSUE TITLE
Support specifying tags at metric creation time

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#9730]
Currently Envoy supports tags with a "tag extraction" indirection: all metric names are flat strings, but a set of regexes can be configured that extracts out tag values from this metric name. This makes sense when users want to add tags to existing metrics, but in cases where custom metrics are added through extensions, users might be know a priori what metric tags they want for a given metric. 

Adding a constructor to the metric objects that allow passing a fixed set of tags would greatly simplify this case: instead of specifying a flat string and a set of tag regexes, the final name + tags can be specified directly.

**Comment by mattklein123** [comment]
See also https://github.com/envoyproxy/envoy/issues/9194 which this might be a dup of.

**Comment by snowp** [comment]
I think this issue is a bit narrower in scope but yeah I can close this out in favor of the other one. As a V1 I'll just make the tags settable as string pairs on the metric objects, and then down the line we add in tag optimizations around symbol usage as necessary.
