### ISSUE TITLE
Don't depend on spdlog for `fmt::format`

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#975]
There's a number of places where we depend on `spdlog` just to get at the string formatter `fmt::format`. This is not actually part of `spdlog`, it's from https://github.com/fmtlib/fmt, which `spdlog` bundles. In the interest of logging abstraction down the track, we should make the dependency more explicit and import `fmtlib/fmt` directly.

**Comment by htuch** [comment]
@kmyerson

**Comment by moderation** [comment]
Some notes after testing spdlog 0.14 and chatting with @htuch on Gitter:

- spdlog upgraded to fmt 4.0.0 in release 0.14 - https://github.com/gabime/spdlog/commit/fced34e3d8c31c9f9e69bbad79271f93c989457e
- fmt moved support for printf and sprintf to the printf.h header - https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst
- the printf.h header isn't included in the spdlog repo. spdlog dropped the use of [fmt::sprintf](https://github.com/gabime/spdlog/commit/fced34e3d8c31c9f9e69bbad79271f93c989457e#diff-5dd99e1de3bb056597b3edc1c6df7198L3737)
- this breaks some of the upstream tests that use fmt::sprintf - https://github.com/lyft/envoy/search?l=C%2B%2B&q=%22fmt%3A%3Asprintf%22&type=&utf8=%E2%9C%93

In the short term I think Envoy could move to spdlog 0.14 by changing the use of fmt::sprintf to fmt::format. Longer term making the dependencies explicit as @htuch suggests makes more sense.

**Comment by mattklein123** [comment]
@moderation I believe @kmyerson is going to do this issue soon. @kmyerson can you also do the spdlog thirdparty dep upgrade at the same time since there is going to be some coordinate on making spdlog take the version of fmt that we want.

**Comment by kmyerson** [comment]
Yes, I'll be working on this issue. I can do the spdlog thirdparty dep upgrade at the same time

**Comment by mattklein123** [comment]
This is fixed I think.
