### ISSUE TITLE
Rate limit: Extract multiple headers to a tuple of descriptors

### ISSUE THREAD

**Issue by qbrent** [envoyproxy/envoy#9756]
I am trying to extract a tuple of descriptors from different headers; but Envoy is only taking one of the headers and setting a single descriptor. 

Is this expected?

I have tried both

```
rate_limits:
- actions:
 - {request_headers: {"header_name": "plan","descriptor_key": "plan"}}
- actions:
 - {request_headers: {"header_name": "clientId","descriptor_key": "clientId"}}
```
and

```
rate_limits:
- actions:
 - {request_headers: {"header_name": "plan","descriptor_key": "plan"}}
 - {request_headers: {"header_name": "clientId","descriptor_key": "clientId"}}
```

Thanks,
Brent

**Comment by mattklein123** [comment]
Dup of https://github.com/envoyproxy/envoy/issues/9717. Please don't open duplicate issues.

**Comment by qbrent** [comment]
Sorry; I completely forgot I had already raised this. Thanks for de-duping me.
