### ISSUE TITLE
intro/arch_overview/operations/draining unclear about default

### ISSUE THREAD

**Issue by jamessynge** [envoyproxy/envoy#9761]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining has a list of 4 bullets describing times when draining occurs:

* The server has been manually health check failed via the healthcheck/fail admin endpoint. See the health check filter architecture overview for more information.
* The server is being hot restarted.
* Individual listeners are being modified or removed via LDS.
* Admin initiated drain via drain_listeners.

However, the first of the two `drain_type` values, `default`, says that it applies to all **three** cases (not times) when draining occurs.

I'm happy to offer an doc PR if someone in the know can make it clear what the behavior for default is.

**Comment by mattklein123** [comment]
cc @ramaraochavali who implemented the drain_listeners admin option. From quickly trying to page this back in, I'm not sure that drain_listeners on the admin endpoint actually drains them. I think it just directly stops them? I can't remember if the intention was to have them drain, etc. but agreed the docs are broken right now and would definitely appreciate a doc fix.

**Comment by ramaraochavali** [comment]
Admin initiated drain actually does not drain and it just stops the listeners on workers https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--drain_listeners - so "default type" docs are confusing. Definitely appreciate a doc fix.

**Comment by mattklein123** [comment]
@jamessynge @ramaraochavali would appreciate a doc update from one of you. Thank you!
