### ISSUE TITLE
AMP packager filter

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#9763]
We are thinking of replicating/wrapping the logic in https://github.com/ampproject/amppackager as an Envoy filter. It consist of two steps:

1) cache friendly transformations (maybe done using something like https://github.com/ampproject/amppackager/tree/releases/transformer via a cgo bridge)
2) signed exchange signing (using either https://github.com/google/libsxg or the go sxg signer via the cgo bridge again: https://github.com/WICG/webpackage/tree/master/go/signedexchange)

cc: @cpapazian @derekargueta @fishcakez

**Comment by cpapazian** [comment]
cc: @twifkak

**Comment by twifkak** [comment]
I would also add a bit of request-side logic to validate the [`Accept`](https://github.com/ampproject/amppackager/tree/releases/packager/accept) and [`AMP-Cache-Transform`](https://github.com/ampproject/amppackager/tree/releases/packager/amp_cache_transform) headers and save that in the StreamInfo for the response filter.

**Comment by cpapazian** [comment]
@twifkak are the optimizations/transformations in https://github.com/ampproject/amppackager/tree/releases/transformer the same as those implemented in https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer? another option is to implement the cache friendly optimizations in our frontend web server as we render the AMP HTML, and only do the SXG packaging/signing in the envoy filter.

**Comment by twifkak** [comment]
@Gregable @honeybadgerdontcare re: transformed AMP validation

They are similar but not exact. Two important differences:
 - amppkg rewrites various subresource URLs to point to the Google AMP Cache ([source](https://github.com/ampproject/amppackager/blob/e4bf0430ba152cfe82ccf063df92021dfc0f26a5/transformer/transformers/urlrewrite.go#L61)) and optimizer doesn't; this is signified by the `<html transformed>` attribute, either `google;v=N` or `self;v=N`
 - The HTML serializers are different. Currently, Google's internal AMP SXG validator is very picky about the HTML serialization, so it's unlikely to pass unless it runs through an exact port of [this printer](https://github.com/ampproject/amppackager/blob/releases/transformer/printer/printer.go).

There may be other differences (in terms of the set of transformers that are run), though. We haven't intended the optimizer for use in an SXG, so it was never vetted. You'd probably have to compare the two codebases (or grep [validator protoasciis](https://github.com/search?q=repo%3Aampproject%2Famphtml+filename%3Aprotoascii) for `transformed`). You also run the risk of some old transform becoming invalid in the distant future, as we rev our versions, though we haven't invalidated anything yet. Note that the risk is mitigated: If it fails AMP SXG validation, it should still be able to pass normal AMP validation for display in the viewer.

Also, I've attempted to document the [AMP SXG validation requirements](https://github.com/ampproject/amppackager/blob/releases/docs/cache_requirements.md); hopefully you find some of that useful.

**Comment by cpapazian** [comment]
cc: @nainar @jeffjose

**Comment by honeybadgerdontcare** [comment]
To follow up to @twifkak's comment. The validator will utilize what is written in it's engine and protoascii defined rules to determine if a document is valid. There should not be any divergence from those rules to what is allowed when the attribute `transformed` is present on the `html` tag. As time goes on, more rules may change for the `transformed` type identifier.
