### ISSUE TITLE
Lua script: Reading from dynamicMetadata

### ISSUE THREAD

**Issue by qbrent** [envoyproxy/envoy#9776]
I have some dynamicMetadata set

**key**: envoy.filters.http.jwt_authn
**fields**: jwt_payload.usr

The below produces the following logs

```
function envoy_on_request(request_handle)
  local meta = request_handle:streamInfo():dynamicMetadata()
  for key, value in pairs(meta) do
    request_handle:logInfo("extract dynamicMetadata key: "..key)
    request_handle:logInfo("extract dynamicMetadata value: "..value.jwt_payload.usr)
  end
end
```

```
[info][lua] script log: extract dynamicMetadata value: the-value-I-expected-to-see 
[info][lua] script log: extract dynamicMetadata key: envoy.filters.http.jwt_authn 
```

But I can't work out the correct syntax to read the value for that filter / key / fields directly

Trying to follow - https://www.envoyproxy.io/docs/envoy/v1.12.2/configuration/http/http_filters/lua_filter.html?highlight=dynamicmetadata#id4
I tried:

```local jwtData = meta.get("envoy.filters")["jwt_payload"]```
errors on
```"function envoy_on_request(request_handle)..."]:8: bad argument #1 to 'get' (N5Envoy10Extensions11HttpFilters3Lua25DynamicMetadataMapWrapperE expected, got string)```

I noticed there was an example in the above link which does not use `get` so I tried

```
local jwtData = meta["envoy.filters.http.jwt_authn"]
request_handle:headers():add("jwt-extracted-user", jwtData.jwt_payload.usr)
```
errors on
``` "function envoy_on_request(request_handle)..."]:9: attempt to index local 'jwtData' (a nil value)```

So; I can see the key when looping; and would like to read that filter, key & field directly to keep my Lua script clean.

Thanks

**Comment by dio** [comment]
@qbrent I think you need to use ":" (colon) instead of "." (dot). The colon is for implementing methods that pass self as the first parameter. So `x:bar(3, 4)` should be the same as `x.bar(x, 3, 4)`.

```lua
local meta = request_handle:streamInfo():dynamicMetadata()
local jwtData = meta:get("envoy.filters") -- or meta.get(meta, "envoy.filters") 
```

Seems like the doc is a bit misleading, do you want to help to fix the doc? 🙂
