### ISSUE TITLE
Remove x-envoy-decorator-operation response header?

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#9778]
Is there a way to remove the x-envoy-decorator-operation header from the response to the client? I'm not directly setting that header anywhere, I assume it is being set by Envoy using the decorator value. I've tried setting the response_headers_to_remove setting in the route_config but that has had no effect. Here is the route_config I am using:

>           
          route_config:
            name: xxxx
            response_headers_to_remove:
              - x-envoy-decorator-operation
            virtual_hosts:
            - name: xxxx
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  timeout: 300s
                  idle_timeout:
                  cluster: xxxx
                decorator:
                  operation: xxxx
          http_filters:
          - name: envoy.router
            config:
              suppress_envoy_headers: true

**Comment by mattklein123** [comment]
IIRC there is no way to do this today. cc @objectiser

**Comment by objectiser** [comment]
@jaegchoi If you remove,
```
            decorator:
              operation: xxxx
```
from your route config, that should do it. This is specifying the span name/operation to be used in the tracing data produced by the envoy proxy handling the service request - and then the response header is returning the same information to the envoy proxy handling the client side of the request, so that it can use the same span name/operation in its tracing data - designed to provide consistency in the tracing data.

**Comment by jaegchoi** [comment]
@objectiser We use the decorators to differentiate our different spans in Jaeger. We would like to keep the decorator for the use of tracing, but remove it from the response headers to the client after Envoy has sent all the tracing information to the collector. 

If this is not yet possible, could I make this a feature request? We would like to hide all knowledge of Envoy being used from the client for security reasons

**Comment by objectiser** [comment]
@jaegchoi Its not currently possible, so would need to be a feature request.

@mattklein123 Could this be labelled as feature/enhancement?
