### ISSUE TITLE
Support for PROXY protocol source IP?

### ISSUE THREAD

**Issue by dcarrigerac** [envoyproxy/envoy#9782]
The Envoy documentation states (https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol) that "In this mode, the downstream connection is assumed to come from a proxy which places the original coordinates (IP, PORT) into a connection-string. Envoy then extracts these and uses them as the remote address."

However, PROXY protocol headers (https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) are in the following format:

PROXY TCP4 192.168.0.1 192.168.0.11 56324 443\r\n

It's clear that Envoy extracts the destination IP:PORT and uses that information to proxy the connection, but what about the source IP:PORT?

I have a use case where the software I'm using will inject the desired source IP into the PROXY protocol header. Then I would like Envoy to use that source IP (which will be local to the Envoy server) to make the connection to the remote IP.

Does Envoy support that functionality currently?

**Comment by mattklein123** [comment]
Yes we parse both source and destination: https://github.com/envoyproxy/envoy/blob/d0f7301f7482f45434e3c709f2bc1a5900d871eb/source/extensions/filters/listener/proxy_protocol/proxy_protocol_header.h#L27-L44

**Comment by dcarrigerac** [comment]
Thanks @mattklein123 - forgive my ignorance, but how would I configure Envoy to then use that IP as the source IP when talking to a remote destination?

ie, 192.168.1.100 (my client) talks to 10.20.30.40 (primary IP of the Envoy server) and has a PROXY protocol header of, say, 10.0.0.1 172.217.13.110. The IP 10.0.0.1 is local to the Envoy server as well, how would I get Envoy to use that IP when connecting to the remote destination of 172.217.13.110?

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency

**Comment by dcarrigerac** [comment]
I looked through the IP transparency docs and it didn't seem to match my use case. The upstream_bind_config does work from my testing, however.

Can I reference the PROXY protocol source IP in my Envoy configuration file? If so, how do I reference that variable?

**Comment by juanvasquezreyes** [comment]
> I looked through the IP transparency docs and it didn't seem to match my use case. The upstream_bind_config does work from my testing, however.
> 
> Can I reference the PROXY protocol source IP in my Envoy configuration file? If so, how do I reference that variable?

Were you able to solve the issue? if so, can you please share the details? I'm trying to set the same, but the documentation about proxy protocol is really bad
