### ISSUE TITLE
Envoy routing to statefulsets

### ISSUE THREAD

**Issue by steeling** [envoyproxy/envoy#9793]
Does envoy support anyway of mapping a URL to a k8's statefulset, based on the domain name.

An example would be a rule that could translate
`X.my-domain.com -> X.myservice.default.svc.cluster.local`

**Comment by steeling** [comment]
also to note that this is TCP traffic, not HTTP

**Comment by snowp** [comment]
This kind of mapping is possible with Envoy, but Envoy itself doesn't have any knowledge about Kubernetes. You'll probably want to look into control planes that integrate Kubernetes with Envoy, for example Istio or Kuma.

**Comment by snowp** [comment]
If you're trying to do this kind of mapping on your own you'd just need to generate a virtual host with the desired domain and route that to a cluster that specifies the target (using STRICT_DNS would probably be the easiest).

**Comment by steeling** [comment]
Ah, to clarify we would like to do this without specifying each domain individually, such that we could set up autoscaling.

It would be nice to use a regex rule to take (*).<my-domain> and use the capture group for the result.

It's ok if we had to do this in multiple steps with one filter that extracts the data, and places it in dynamic_metadata, and another that routes on that info
