### ISSUE TITLE
Multiple validation_context's

### ISSUE THREAD

**Issue by steeling** [envoyproxy/envoy#9794]
Is there a way to setup multiple validation_context's with Envoy, particularly for TCP traffic not HTTP?

We'd like to provide a single URL, and use mTLS w/ ~3-10 other external systems. We can't influence the other systems to set unique headers, domains, SNI, or anything else.

We could associate their CA certs with their hostname/IP to match on based on that, or we could eat the cost of trying every cert till one matched.

Or Is this possible to do at the moment leveraging filter chains?

**Comment by mattklein123** [comment]
As long as you can match on hostname/IP I think you can do this with filter chains? cc @lambdai @PiotrSikora

**Comment by PiotrSikora** [comment]
Yes, you could use multiple filter chains to do that, but the cost of matching to a particular certificate is negligible (it's just a quick comparison of hashes), so unless you need/want to segregate traffic from those external systems for some reason (it doesn't sound like you do), the best and easiest solution would be to simply provide `trusted_ca` that contains all the trusted CA certificates or provide multiple valid values in `match_subject_alt_names`.

**Comment by steeling** [comment]
can we match on client IP or hostname?

All of the traffic will come to a single hostname. At the moment we don't have any influence on enforcing a specific CA to use, so we first request their CA cert with us, and we add it to a list we will verify against

**Comment by PiotrSikora** [comment]
Yes, you can match on the client (source) IP address or subnet.

You cannot match on the client's hostname.

**Comment by mattklein123** [comment]
> You cannot match on the client's hostname.

Just to clarify, "hostname" is an L7/HTTP concept. You can match on SNI.

**Comment by PiotrSikora** [comment]
> Just to clarify, "hostname" is an L7/HTTP concept. You can match on SNI.

He means client's hostname (reverse DNS of client's IP address), not SNI / `Host` / `:authority`.

**Comment by steeling** [comment]
Thanks all, that helps!
