### ISSUE TITLE
Caching monotonic time

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/envoy#9795]
To help achieve a consistent view of "now" across different components of the system, it might be nice to have a time source which returns a cached copy of monotonic time when "now" is queried, which Envoy would then update once per event loop cycle. This may help avoid subtle edge cases caused by small differences in perceptions of "now" when components query the clock independently.

[Similar proposed change in Nighthawk](https://github.com/envoyproxy/nighthawk/pull/293)

**Comment by mattklein123** [comment]
See `EnvoyQuicClock::ApproximateNow()`. There was already some discussion of moving this into the base dispatcher / time source so this sounds reasonable to me. cc @jmarantz @danzh2010
