### ISSUE TITLE
proposal: add client id to request metrics emitted by kafka filter 

### ISSUE THREAD

**Issue by amre-abb** [envoyproxy/envoy#9816]
*Title*: Add kafka client id to request metrics emitted by the kafka filter.

*Description*:
Currently, the kafka filter emits metrics with the following format:
`kafka.<stats_prefix>.request.<request_type>`, i.e., values aggregated across all clients.

A more general approach would be to include each request's client ID so one could parse these metrics and create tags. 

Here is an example of such metrics exposed for Prometheus:
<img width="1269" alt="Screen Shot 2020-01-23 at 3 24 59 PM" src="https://user-images.githubusercontent.com/60152834/73036056-16ff3400-3dff-11ea-9c32-dc32732eea0d.png">

**Comment by amre-abb** [comment]
I have a draft PR for such a change since this functionality (ability to gather per-client broker metrics) would be really helpful for my experiments with kafka filter.

**Comment by mattklein123** [comment]
@adamkotwasinski PTAL. My only concern here would be cardinality explosion.

**Comment by adamkotwasinski** [comment]
The number of metrics needs to have an upper bound (it could be filter's metrics configuration property).
The Kafka clients can pick absolutely random client-ids, otherwise getting multiple client requests over time would cause metrics explosion.

**Comment by adamkotwasinski** [comment]
Same concerns apply to other dimensions where one would want to slice the traffic: topic, topic+partition, group-id (for fetch requests).

**Comment by amre-abb** [comment]
Thanks @adamkotwasinski  and @mattklein123, it totally makes sense. However, kafka relies on client-id, for example, for rate limiting (https://cwiki.apache.org/confluence/display/KAFKA/KIP-124+-+Request+rate+quotas) so in a real deployment these IDs should not be completely arbitrary (and finite). It could be a configurable option not enabled by default perhaps?
