### ISSUE TITLE
Make "gRPC config stream closed" more descriptive

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#9827]
*Title*: Make "gRPC config stream closed" more descriptive

*Description*:
For various reasons, we may end up with `gRPC config stream closed` logs when xDS connections are lost. It would be useful to add more context here. I am not sure what is available here, but I would at least like to see "SDS config stream closed" or "ADS config stream closed" to distinguish between those two to facilitate debugging

**Comment by snowp** [comment]
This seems reasonable. Let me put up a quick PR
