### ISSUE TITLE
HTTP1 proxy HTTP2 grpc trailers dropped when content-length is present

### ISSUE THREAD

**Issue by Chuongv** [envoyproxy/envoy#9831]
## Envoy proxy http grpc unary calls with content-length, trailers are dropped when encoding http1

*Description*:

I have the following setup where the downstream client is http1 and envoy is proxying a http2 unary request
```
+------------------+             +----------------------+        +-------------------------+
|                  | <--------+  |                      | <------+                         |
|                  |             |                      |        |                         |
|    http1.client  +--------->   |      envoy           +------> |       http2.grpc        |
|                  |             |                      |        |                         |
+------------------+             +----------------------+        +-------------------------+
```

With `enable_trailers` we can support this without the [http1 grpc bridge](https://www.envoyproxy.io/docs/envoy/v1.5.0/configuration/http_filters/grpc_http1_bridge_filter).

This works well but it falls apart when the http2.grpc sends back a unary response with `content-length`at which point the `enable_trailers` [fails to encode the trailer](https://github.com/envoyproxy/envoy/blob/master/source/common/http/http1/codec_impl.cc#L215-L217).

I forgot the reason why at the time we decided not to send trailers for HTTP1 if it's not chunk_encoding. Looking around the [specs](https://tools.ietf.org/html/rfc7230#section-4.1.2), I do not see any specific call out that advises against this.

The possible fix is to write a custom filter that will stripped the content length header in this scenario but it feels a little hacky. Thoughts?

**Comment by mattklein123** [comment]
IIRC HTTP/1.1 trailers require chunk encoding, and the existence of content-length means that chunk encoding does not happen. Therefore I'm not sure how the encoder could know that trailers might be coming? It seems like stripping content-length in a filter is the right thing to do? Do you have other ideas of how this could be handled generically?

**Comment by Chuongv** [comment]
Yea I think you are right. It doesn't make sense to have trailers if it's not chunk encoding. I'm leaning towards of just stripping the content-length at this moment.
