### ISSUE TITLE
Pass Rate-Limit headers on response even when not Over Limit

### ISSUE THREAD

**Issue by daninthewoods** [envoyproxy/envoy#9838]
*Description*:
>Rate limit response headers only get sent back to the client when Code.OVER_LIMIT is returned from the Rate Limit Service.  However, if that service wants to send a rate limit progress header such as X-Rate-Limit-Remaining, that does not get passed back to the client when Code.OK is returned.

[optional *Relevant Links*:]
>Example of dynamic rate limiting headers that inform the client of usage progress
[https://developer.twitter.com/en/docs/basics/rate-limiting](url)

**Comment by mattklein123** [comment]
I think it would be fine to have an option here that does this.

**Comment by daninthewoods** [comment]
I think I submitted this too soon.  I now see that when/if the RLS is consulted, then headers are returned for both OK and OVER_LIMIT.  Sorry for raising this unnecessarily, what confused me is that sometimes my RLS seems to take too long to respond in which case Envoy continues (failure_mode_deny=false) regardless and so no headers are added.
