### ISSUE TITLE
CacheFilter: Correctly calculate cached response age

### ISSUE THREAD

**Issue by toddmgreer** [envoyproxy/envoy#9859]
CacheFilter doesn't fully implement the algorithms specified in [RFC7234§4.2](https://httpwg.org/specs/rfc7234.html#expiration.model) to calculate freshness lifetime and age, based on the date, age, and expires response headers, the max-age and s-maxage response cache directives, and the max-age request cache directives. The RFC-specified freshness and age algorithms must be fully implemented. This must be fixed before CacheFilter can be appropriate for production deployment.

**Comment by yosrym93** [comment]
In #11727 , LookupRequest::requiresValidation calculates some freshness and age info that might be useful when working on this.
