### ISSUE TITLE
example/zipkin-tracing not collecting tracing data

### ISSUE THREAD

**Issue by brandon-myers-009** [envoyproxy/envoy#9880]
__example/zipkin-tracing not collecting tracing data__: 
*Not able to see tracing data when running the zipkin tracing example*

*Description*:
When trying to run the zipkin-tracing example I am able to get all the docker containers up a running however when I hit http://localhost:8000/service/1 or service/2 and go to the zipkin frontend running on my localhost and search for all serviceName data I am unable to find my recent activity. It seems like the problem started about 3 or so weeks ago. I was able to checkout v1.12.2 and everything worked fine.

**Comment by dio** [comment]
Hum, seems like we need to add [`tracing: {}`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=tracing) to HTTP Connection Manager now.

**Comment by objectiser** [comment]
@dio @mattklein123 This appears to be a regression - not sure we should update the examples to work around it? Istio 1.5.0.alpha0 (based on envoy 1.13) also appears affected.

**Comment by dio** [comment]
@objectiser gotcha, do you think we should fix it code-wise, i.e. to default on always do request tracing?

**Comment by yanavlasov** [comment]
If this was the original behavior, I think we should preserve it. Otherwise it would be a gotcha to a lot customers.

**Comment by objectiser** [comment]
@dio Preference would be to remain backwards compatible - but if the change was intentional then it should be listed as breaking change in the 1.13 release note.

**Comment by dio** [comment]
@objectiser @yanavlasov  Seems like the previous version has the tracing entry inserted:

https://github.com/envoyproxy/envoy/blob/8f2515a19bdcc75bea0bfd7016231a7661d0be6e/examples/zipkin-tracing/front-envoy-zipkin.yaml#L13-L14.

I think it was removed by https://github.com/envoyproxy/envoy/commit/8057eed8aceaecc29a28fe1cc3818b67cba32585#diff-0a4306fc6bec5e6e8010ff79209ebcb9

The `operation_name` is deprecated in favor of [`traffic_direction`](https://github.com/envoyproxy/envoy/blob/46eb08454672710fb77256bca3581927c146da8c/generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L112).

https://github.com/envoyproxy/envoy/blob/46eb08454672710fb77256bca3581927c146da8c/examples/zipkin-tracing/front-envoy-zipkin.yaml#L7

https://github.com/envoyproxy/envoy/blob/46eb08454672710fb77256bca3581927c146da8c/source/extensions/filters/network/http_connection_manager/config.cc#L285-L298

**Comment by objectiser** [comment]
@dio Ok so looks like not an issue - as long as users moving aware from the deprecated operation_name understand the implications of removing the tracing node. Thanks for the investigation!
