### ISSUE TITLE
Dynamic forward proxy support for TLS traffic

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#9916]
Envoy today has support for dynamically resolving the host from the HTTP authority header using the dynamic forward proxy filter (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy). This is very useful when we have to capture and forward arbitrary HTTP traffic under a domain (like `*.google.com`) to an external envoy gateway that in turn forwards to the right destination.

We need a similar mechanism for TLS traffic as well, i.e. dynamically resolve the upstream based on the incoming SNI value and forward. With this support, we can capture all TLS traffic for a set of hosts (e.g., `*.googleapis.com`) and route them through a blessed egress gateway where we can do sni passthrough on the listener side, but dynamic resolution based on the sni on the upstream.

cc @lizan

**Comment by lizan** [comment]
My rough idea for this would be having an L4 equivalent filter of `dynamic_forward_proxy` in HTTP that does DNS resolving based on SNI, which can leverage the DNS cache and `dynamic_forward_proxy` cluster.

**Comment by mattklein123** [comment]
Yes ^ exactly. I don't think this would be hard to implement.

**Comment by Shikugawa** [comment]
Is anyone working on this? I will implement this. @mattklein123 @lizan @rshriram

**Comment by lizan** [comment]
@Shikugawa yes I am, just pending integration test.

**Comment by lizan** [comment]
not stale, PR #10448

**Comment by lizan** [comment]
Erm, stalebot shouldn't close this, is it a bug?
