### ISSUE TITLE
Formalize CVE process

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#992]
Some high level issues:

- Do we have a pre-announce list. Who is on it?
- Announce process. envoy-announce@?
- Explicit policy around what is documented, what severity levels mean, etc.

Should look at boringssl, openssl, and nginx for inspiration. Others?

**Comment by mattklein123** [comment]
@woodrow not sure if you feel like helping with this. Can chat when I'm back from vacation.

**Comment by caniszczyk** [comment]
Just to followup, I suggested we cargo cult this: https://github.com/kubernetes/community/blob/master/contributors/devel/security-release-process.md

@mattklein123 seems cool with it
