### ISSUE TITLE
When Envoy is in warming state and reconnect to new instance of control-plane doesn't send CDS request

### ISSUE THREAD

**Issue by lukidzi** [envoyproxy/envoy#9934]
*Title*: *When Envoy is in warming state and reconnect to new instance of control-plane doesn't send CDS request*

*Description*:
So let's assume Envoy is connected to `Control-plane1`. `Control-plane1` receive information about the new cluster`[Cluster1]` and send CDS response to Envoy using ADS. `Control-plane1` dies and at the same time cluster`[Cluster1]` has been removed. Envoy connects to `Control-plane2` and send[EDS,LDS,RDS] requests - in the meantime Envoy has warming cluster. EDS request from Envoy contains resource name of removed cluster`[Cluster1]` and `Control-plane2` doesn't know about the cluster which was sent by `Control-plane1` to Envoy. Because ADS implementation requires to send only response when all requested resources are in snapshot `Control-plane2` won’t respond (java-control-plane and go-control-plane) but also Envoy won't send new CDS request untill all clusters are warmed. In this situation Envoy stay in warming phase for ever. Is it correct behaviour or how should it be handled? 

I found that PR with change: https://github.com/envoyproxy/envoy/pull/5887/files

**Comment by mattklein123** [comment]
@lizan @wgallagher PTAL, cc @htuch

**Comment by wbpcode** [comment]
I had the same problem. The reason is that some STRICT DNS clusters lack endpoints, which makes the cluster unable to enter the process of DNS resolution, thus unable to complete initialization, and always stay in the warming stage.

**Comment by htuch** [comment]
When re-establishing connection to control plane 2, Envoy should be establishing a CDS DiscoveryRequest (even though it's not part of warming CDS should want to maintain an active subscription). It's the responsibility of control plane 2 to deliver the DiscoveryResponse where cluster 1 is removed, which should then influence the warming.
