### ISSUE TITLE
How to add rDS version to Access logging configuration?

### ISSUE THREAD

**Issue by yunhan0** [envoyproxy/envoy#9945]
The [envoy.http.rds.version](https://docs.datadoghq.com/integrations/envoy/) is reported as gauge in Datadog. The value is in `integer` which makes it difficult to debug. I wonder is it possible to add rDS version to Access logging configuration? So we can at least have some logs to debug the version. Or whether there’s a setting we can enable to look this information?

**Comment by mattklein123** [comment]
IIRC you can get the current configuration version from the `/config_dump` endpoint. If you can't we should add it.
