### ISSUE TITLE
Feature request: add support for logging request/response body in gRPC ALS

### ISSUE THREAD

**Issue by vickilong** [envoyproxy/envoy#9950]
We are interested in logging request/response bodies using the http/gRPC access log service. We did look into logging request/response bodies with a Lua filter and it seems possible to do so, but we are looking at other possible ways to do the same thing.

It looks like both `HTTPRequestProperties` and `HTTPResponseProperties` in the `HTTPAccessLogEntry` (https://www.envoyproxy.io/docs/envoy/latest/api-v3/data/accesslog/v3/accesslog.proto#data-accesslog-v3-httpaccesslogentry) already have access to the HTTP request and response body in bytes. I haven’t delved too deeply into the implementation here, but I am presuming that it would be possible to access the request/response body also. 

Is this something that can be built into the access log service? Are there any suggestions on how this might be done?

**Comment by mattklein123** [comment]
Logging the bodies would require buffering, which would be complicated given the architecture of access logging currently. IMO tap is a better fit for this. Can you take a look at that and see if that generally meets your needs? Right now we don't have gRPC output for that but it's something that we want to add. https://www.envoyproxy.io/docs/envoy/latest/operations/traffic_tapping

**Comment by lhluo** [comment]
Hi @mattklein123, would Lua Filters also work for the above use case? 
Looking at the docs [here](https://www.envoyproxy.io/docs/envoy/v1.13.0/configuration/http/http_filters/lua_filter), seems like we can use the `envoy_on_response` hook to make an outbound gRPC call, but it doesn't seem like there exists an API for gRPC for Lua. 

Is what I've suggested feasible? If so, which approach (Lua or Tap) would you recommend?

**Comment by mattklein123** [comment]
It might be possible to do using Lua out of the box, though IMO it would be better to finish the gRPC output part of https://github.com/envoyproxy/envoy/issues/6110 which I don't think would be difficult.

**Comment by lhluo** [comment]
@mattklein123 thanks for the suggestion! I will look into tap filters as a solution for us.

Meanwhile, I played a bit with the Lua filter and found that, as documented, the `httpcall` causes Envoy to yield the script until the call completes. Are you familiar with any way to make a non-blocking http call (i.e fire-and-forget) the context of a lua filter?

**Comment by mattklein123** [comment]
> Are you familiar with any way to make a non-blocking http call (i.e fire-and-forget) the context of a lua filter?

IIRC it's not possible currently, cc @dio

**Comment by shaofu88** [comment]
@mattklein123, To follow up, is it possible to execute a filter or tap filter in a non-blocking way?

**Comment by mattklein123** [comment]
If we implement gRPC output for TAP it would be non-blocking.
