### ISSUE TITLE
Config to disable TLS session tickets

### ISSUE THREAD

**Issue by jasonewang** [envoyproxy/envoy#9951]
Is there a way to disable TLS session tickets? The Envoy docs and other sources[1][2] mention security considerations and risks for using session tickets, and we don't need session resumption at all so we'd like to not be exposed to any possible risks.

[1] https://www.imperialviolet.org/2013/06/27/botchingpfs.html, also mentioned in the Envoy docs.
[2] https://blog.filippo.io/we-need-to-talk-about-session-tickets/

**Comment by junr03** [comment]
cc @PiotrSikora

**Comment by snowp** [comment]
Pretty sure that TLS session tickets are only enabled if you configure a session ticket key in the TLS context, so it should be disabled by default.

**Comment by PiotrSikora** [comment]
TLS session tickets are enabled by default, and there is currently no way to disable them in Envoy.

It's a trivial change (adding `SSL_CTX_set_options(..., SSL_OP_NO_TICKET)`, glue code and tests), so patches welcome!

**Comment by rulex123** [comment]
Hi! I would like to help out with this.
