### ISSUE TITLE
Eliminate/prevent dependencies on extensions from core

### ISSUE THREAD

**Issue by mergeconflict** [envoyproxy/envoy#9953]
There are some cases where core Envoy code (or tests) depends on extensions. One example:

```
//source/extensions/access_loggers/grpc:http_config
//source/extensions/access_loggers/grpc:tcp_config
```

are used by:

```
//test/integration/http2_upstream_integration_test
//test/common/access_log/access_log_impl_test
```

This poses an issue for users like Google, who import only specific whitelisted extensions. We have to disable tests that depend on non-whitelisted extensions. I think we'd like to add some logic to check_format or similar, to catch these dependencies before they're introduced.

Not sure if this is related to #7903, likely seems related to #2910.

**Comment by mattklein123** [comment]
+1 yes please. If you are going to fix this can you also potentially fix https://github.com/envoyproxy/envoy/issues/6736? It's related in the sense that by default we build and link all extensions into some of the server integration tests. Optimally the core integration tests should depend on only a build with a very limited set of extensions.

**Comment by mattklein123** [comment]
I think @yanavlasov is working on this. Also discussing fixing https://github.com/envoyproxy/envoy/issues/6736 as well.

**Comment by antoniovicente** [comment]
Related: #12315 #12314

**Comment by antoniovicente** [comment]
Tests for core extension (TLS) depending on non-core extension with new cert verifier functionality -> broken build if you only want the transport_sockets TLS extension.

https://github.com/envoyproxy/envoy/pull/14884

**Comment by mattklein123** [comment]
I think @alyssawilk has been picking away at this. @alyssawilk are we done with this or is there more to do?

**Comment by alyssawilk** [comment]
Down from ~30 to ~6 but not compelte

source/extensions/filters/network/common/BUILD:    # Used by core.  TODO(#9953) clean up.
source/extensions/filters/http/buffer/BUILD:    # Legacy test use. TODO(#9953) clean up.
source/extensions/filters/http/ip_tagging/BUILD:    # TODO(#9953) clean up.
source/extensions/filters/listener/tls_inspector/BUILD:    # TODO(#9953) clean up.
source/extensions/filters/listener/tls_inspector/BUILD:    # TODO(#9953) clean up.
source/extensions/access_loggers/file/BUILD:    # TODO(#9953) determine if this is core or should be cleaned up.
