### ISSUE TITLE
Question: Including external libraries for cache filter plugins

### ISSUE THREAD

**Issue by enozcan** [envoyproxy/envoy#9977]
I'm about to contribute a plugin for the new cache filter (#9878) but not sure about the appropriate way of including external libraries in Envoy convention. 

Currently I include the shared library ([of Hazelcast Cpp Client](https://github.com/hazelcast/hazelcast-cpp-client)) in [my workspace](https://github.com/enozcan/hazelcast-envoy-http-cache/blob/d6e870a794e873cc8b0614555970330872f7ec06/WORKSPACE#L24) via `new_local_repository` in BUILD file. However, it has a size of about 10 MB and of course it's not desirable to add it to Envoy repo. What I observed from the current includes in the repo is, `envoy_http_archive` and `envoy_cmake_external` (for a cmake project just as the one I use) rules are used and all the source code for a repository is compiled again during Envoy build, if I'm not wrong. 

However, this makes me confused since in this manner, plugin dependencies are going to be compiled even if the plugin (and/or cache) is not used. Is that actually expected? If not, what is the proper way of doing that? If so, is there a dependency currently included in the repo that similar to my case and I can follow the same procedure? I have also read the doc for external dependencies [here](https://github.com/envoyproxy/envoy/blob/master/bazel/EXTERNAL_DEPS.md#adding-external-dependencies-to-envoy-external-cmake) but couldn't decide if including such a big dependency in the repo is acceptable or not.

**Comment by mattklein123** [comment]
What we need to do is making cache plugins use the standard extension build mechanism. See https://github.com/envoyproxy/envoy/blob/master/source/extensions/extensions_build_config.bzl. This will allow HTTP cache extensions to be explicitly compiled in (along with their dependencies).

**Comment by toddmgreer** [comment]
Added this for SimpleHttpCache in #9974.

**Comment by toddmgreer** [comment]
#9974 is now merged, and you should be able to use the same approach for HazelCache.

**Comment by toddmgreer** [comment]
To be more specific:
Use envoy_cc_extension (with security_posture and status fields) in the plugin's BUILD file.
Add a line to source/extensions/extensions_build_config.bzl referencing the above BUILD rule (in the "CacheFilter plugins" section).
Use envoy_extension_cc_test (with extension_name field referencing the .bzl line) in the plugin's test BUILD file.

**Comment by enozcan** [comment]
Thank you for the answers.

Then I will import the external dependency via http_archive following the `bazel/EXTERNAL_DEPS.md` steps and include it via `external_deps` in `envoy_cc_extension` rule.

Feel free to close the issue.
