### ISSUE TITLE
Question: about envoy network filter

### ISSUE THREAD

**Issue by CalbeeMing0530** [envoyproxy/envoy#9983]
Does Envoy have a network filter that can output the network packets of each proxy request, such as http request/repsonse header details?

**Comment by jyotimahapatra** [comment]
I think the [tap filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter)   provides similar functionality.

**Comment by mattklein123** [comment]
Correct ^

**Comment by CalbeeMing0530** [comment]
> I think the [tap filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter) provides similar functionality.

thanks a lot, I have already tested the tap filter and it worked well
I will close this issue
