### ISSUE TITLE
comment in code: typo error

### ISSUE THREAD

**Issue by popozy** [envoyproxy/envoy#9985]
*Typo error in buffer_impl.h*

*Description*:
>When reading buffer operation at buffer_impl.h, I found that maybe the "()" is redundant。

*Relevant Links*:
> https://github.com/envoyproxy/envoy/blob/d1db56424d39f10715f81d17d80079a22040abbf/source/common/buffer/buffer_impl.h#L71

**Comment by popozy** [comment]
I want to fix it.

**Comment by junr03** [comment]
closing with explanation in https://github.com/envoyproxy/envoy/pull/9986#issuecomment-584224762
