### ISSUE TITLE
Question: on which Linux distros and releases is Envoy Proxy buildable?

### ISSUE THREAD

**Issue by gary-20** [envoyproxy/envoy#9994]
I'm following https://github.com/envoyproxy/envoy/blob/master/bazel/README.md to build an envoy binary via 'bazel build //source/exe:envoy-static'.

However, the build failed on CentOS and Ubuntu 18.04. 
The build does succeed on Ubuntu 16.

Does it mean the envoy code base only works on Ubuntu 16?

Can it be built on CentOS?

Thanks, -Gary

**Comment by moderation** [comment]
I've buillt on Ubuntu 16, 18 and now 19. With the correct dependencies and the latest version of Bazel it should work. I also build on RHEL 7 with the following flag for Bazel - https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L70-L72

**Comment by gary-20** [comment]
Thanks for the info. I just followed https://github.com/envoyproxy/envoy/blob/master/ci/build_setup.sh#L70-L72 and = issued "export BAZEL_BUILD_EXTRA_OPTIONS+="--copt=-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1"", then I run  "bazel build //source/exe:envoy-static". It still failed with the following information "ERROR: /home/tang/envoy_/envoy/source/extensions/filters/network/kafka/BUILD:133:1: C++ compilation of rule '//source/extensions/filters/network/kafka:kafka_response_parser_lib' failed (Exit 1) gcc failed: error executing command /opt/rh/devtoolset-4/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF ... (remaining 73 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox"

Probably there are more dependencies to take care of if I want to run "bazel build //source/exe:envoy-static" to build the envoy binary.

It appears "./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'" can successfully build the envoy binary on CentOS. 

Let me look into ci/run_envoy_docker.sh  and see if I need any dependencies in order to run "bazel build //source/exe:envoy-static" alone to build the envoy binary. My goal is to build an envoy binary with debug symbol without building test source code and running the testing.
